### ISSUE TITLE
Missing rebuild logs

### ISSUE THREAD

**Issue by zmara** [angular/angular-cli#28354]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17

### Description

During (serve) rebuild on save there used to be a log about information that the rebuild started, now there is none - only "Compiled successfully" when rebuild is done.

Why is that a problem? In large codebases the rebuild can take more time and it is important for a developer to see that he saved a file and the rebuild is happening so he needs to wait a moment in order to see changes he made. When there is no log, he will start questioning himself why the changes he made are not there. It is very important and informative log.

### Minimal Reproduction

Latest version of create-nx-workspace with Angular app

### Your Environment

```text
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.2
@angular-devkit/build-angular   18.2.2
@angular-devkit/core            18.2.2
@angular-devkit/schematics      18.2.2
@schematics/angular             18.2.2
rxjs                            7.8.1
typescript                      5.5.4
webpack                         5.90.3
zone.js                         0.14.10
```

### Anything else relevant?

Using @nx/angular: 19.6.4

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
