### ISSUE TITLE
Support where *browser* static assets (js,css,assets) are pulled from

### ISSUE THREAD

**Issue by tsteuwer-accesso** [angular/angular-cli#28365]
### Command

build

### Description

Right now, we're running to a lot of "Chunk loading errors" when using CI/CD with Angular and Angular's SSR. The reason for this is because our CDN reaches out to origin to get static assets, which are served from SSR. As soon as a new build goes out, the CDN is cleared, and the new assets are now live.

This causes issues with people currently on the site as lazy-loaded chunks that are still wanting to be requested in the users browser will try to go back to origin, only for the CDN to find out they no longer exists because chunk file hashes changed, and trigger the "Chunk loading errors" we're constantly seeing.

In order for users to fix this, they must do a hard-refresh, something we do not want our users to have to go through, especially since we're an international company and at any point in time, we can have people millions of people on in any of our regions.

### Describe the solution you'd like

I would like to be able to configure where **browser** static assets are pulled. One solution we thought of is to be able to change the URL where browser assets are pulled from. Think of it like this:

1.) Build 5000 triggers. We somehow prefix in the CLI that **browser ** assets should be loaded from `https://my.cdn.com/5000/`. We then upload all the browser assets from the build to the `/5000` directory in our CDN.
2.) Build 5001 triggers. We somehow prefix in the CLI that **browser ** assets should be loaded from `https://my.cdn.com/5001/`. We then upload all the browser assets from the build to the `/5000` directory in our CDN.

If user was currently on 5000, the static assets from the `/5000` folder can still be loaded from our domain. If the user refreshes, and we had cleared our CDN, they would start getting `/5001` requests because the main html changed.

### Describe alternatives you've considered

As it stands right now, we're thinking about just doing a find and replace on any `./chunk` string in the output dist for `/browser` and doing this ourselves. I'm not sure if the Google team has ran into this, I'm sure they have, but I would also welcome any other solutions you guys come up with. The easiest though, would be to allow us to configure this somehow so that server assets always load locally, but browser assets can be changed where you serve them from.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
