### ISSUE TITLE
bootstrap css are not working properly

### ISSUE THREAD

**Issue by snajperek130** [angular/angular-cli#2836]
I have done everything exactly as it is said on a github and css are not working properly. The formatting is changing, but not properly. I did like this:

```
"styles": [
  "../node_modules/bootstrap/dist/css/bootstrap.css",
  "styles.css"
],
```

What is more when i paste to index.html 
`<link data-require="bootstrap-css@3.3.7" data-semver="3.3.7" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css"/>`

it is working. What is the reason of this bug?

**Comment by peterblazejewicz** [comment]
Do you mean order in which CSS rules are applied? In above configuration the `styles.css` rules are meant to modify Bootstrap styles.

**Comment by snajperek130** [comment]
Hehe sorry, i am dumb :D

**Comment by snajperek130** [comment]
like this is still not working:
"styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.css"
      ],

**Comment by ninj** [comment]
perhaps you could post the content of your `package.json` file?

**Comment by DavideViolante** [comment]
This project has Boostrap working: https://github.com/DavideViolante/Angular2-Full-Stack
Check how the import is done in angular-cli.json

**Comment by filipesilva** [comment]
@snajperek130 if you followed the instructions on https://github.com/angular/angular-cli#global-library-installation, they refer to Bootstrap 4. You seem to be trying to use Bootstrap 3, and might need to adjust your steps to account for that.

**Comment by crsepulv** [comment]
Hi, trying to install Bootstrap v4.0.0-beta I have the same problem, there is a way to debug this? because I have no error on the console. Bootstrap is inside styles.bundle.js but  it is not loaded as css.

and I'm using:
@angular/cli: 1.0.1
node: 6.7.0
os: win32 x64
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.0.1
@angular/compiler-cli: 4.3.6

I'll appreciate any hint to debug this.

**Comment by filipesilva** [comment]
@crsepulv can you give me detailed steps in a new project to see what you're seeing please? In dev builds global styles are built as .js (but loaded correctly) to improve rebuild speed.

**Comment by vatansoni89** [comment]
@filipesilva Could u plz check why the bootstrap is not working properly for
https://github.com/vatansoni89/SaraswatiVidhyaMandir
but working for
https://github.com/DeborahK/Angular-GettingStarted

For me it's not woking properly and very frustreated.

**Comment by kondasMajid** [comment]
I tried working with bootstrap 3.3.7 on my  angular 6 projects sounds good but very terrible with the responsiveness , probably Angular got some issue with Bootstrap ..

**Comment by eranimeshmishra** [comment]
I had the same issue with bootstrap 4 not working on Angular 7 application. Fixed this by uninstalling bootstrap 4->installed bootstrap 3-> Added bootstrap.css, bootstrap.js to styles and scripts array in angular.json file. And it worked.

**Comment by masinn** [comment]
I am also facing exactly the same issue right now ...
