### ISSUE TITLE
builder-angular:application - build ssr only, disable ssr from serve

### ISSUE THREAD

**Issue by stephenlautier** [angular/angular-cli#28378]
### Command

serve

### Description

We are trying to migrate to use `@angular-devkit/build-angular:application` however due to the `ssr` triggering the SSR during `serve` is causing us issues

What we need to have is to be able to disable the ssr handling via vite (ng serve), but build the server only

- no output: SSR output e.g. `dist/server`
- no SSR server: no SSR from dev-server (through vite)

Using the following: **output + SSR server**
```json
"prerender": true,
"ssr": {}
```

Using the following: **no output + SSR server**
```json
"prerender": true,
"ssr": false
```

Using the following: **no output + no SSR server**
```json
"prerender": false,
"ssr": false
```

Just some more context - our SSR is handled via dotnet ATM and changing all the process its not very simple (and needs to work for local/prod). We pass metadata in order to boot up the angular app for configs etc... which we include via provider (and can change dynamically/per request can have different configs e.g. by locale)

### Describe the solution you'd like

Some configuration along these lines

#### via serve opts
```json
"serve": {
  "builder": "@angular-devkit/build-angular:dev-server",
  "options": {
    "disableSsr": true
  }
},
```

#### OR via build
```json
"build": {
  "builder": "@angular-devkit/build-angular:application",
  "options": {
    ...
    "prerender": true,
    "ssr": {
        "devServer": false
    }
  },
```

### Describe alternatives you've considered

Some workarounds

- keep using `"builder": "@angular-devkit/build-angular:dev-server"` (not sure if theres a new version for this)
- and for the client use either:
    -  `"builder": "@angular-devkit/build-angular:application"` and disable `ssr+prerendering`
    - or `"builder": "@angular-devkit/build-angular:browser-esbuild"`

**Comment by alan-agius4** [comment]
Hi @stephenlautier, 

I'm not entirely sure what you mean by disabling SSR in Vite and building only the server. When running `ng serve`, files are kept in memory and are not written to disk.

If your goal is to disable SSR and prerendering while running `ng serve`, you can modify the configurations as shown below and eliminate repetitive options by leveraging configuration composition:


```json
{
  "build": {
    "builder": "@angular-devkit/build-angular:application",
    "options": {
      ...
    },
    "configurations": {
      "production": {
        "outputHashing": "all"
      },
      "development": {
        "optimization": false,
        "extractLicenses": false,
        "sourceMap": true
      },
      "no-ssr": {
        "ssr": false,
        "prerender": false
      }
    },
    "defaultConfiguration": "production"
  },
  "serve": {
    "builder": "@angular-devkit/build-angular:dev-server",
    "configurations": {
      "production": {
        "buildTarget": "angular-dev:build:production,no-ssr"
      },
      "development": {
        "buildTarget": "angular-dev:build:development,no-ssr"
      }
    }
  }
}
```

**Comment by stephenlautier** [comment]
Sorry I wasn't clear; 

For our SSR to work i would need to to use the `build` for the SSR (so `dist/server` is on disk), as they need to be invoked from **dotnet -> node** (though client is not needed at this point)

Then when i launch the client through `ng serve`, i need SSR to be disabled (e.g. this [vite SSR middleware](https://github.com/angular/angular-cli/blob/main/packages/angular/build/src/tools/vite/middlewares/ssr-middleware.ts))  as we are using `import { createServerRenderer } from "aspnet-prerendering";` in `main.server.ts` and it blows up (as its not invoked from dotnet)

So what i was hoping is to only build server (so its on disk) and when i launch `ng serve` i dont have ssr through dev server (vite)

Will give what you suggested a shot; maybe i can get something working like that (tho might have additional build redundant - e.g. when i build the server i will also build the client again). 

Not sure if theres a way to build the server only by any chance? or a new version of `@angular-devkit/build-angular:server` which uses the new stuff? 👀 
As previously we were building server only using `ng run DotnetNgx:server` which is using `"builder": @angular-devkit/build-angular:server`

**Comment by alan-agius4** [comment]
The application builder does not support building only the server-side portion code. Instead it builds the entire application.

Additionally, as far as I know, `aspnet-prerendering` relies on the deprecated .NET SPA Services, which are incompatible with ESM and only work with CommonJS (CJS). So even if the build was outputted to disk, you’ll have some challenges using the output with .NET.

**Comment by stephenlautier** [comment]
> The application builder does not support building only the server-side portion code. Instead it builds the entire application.
> 
> Additionally, as far as I know, `aspnet-prerendering` relies on the deprecated .NET SPA Services, which are incompatible with ESM and only work with CommonJS (CJS). So even if the build was outputted to disk, you’ll have some challenges using the output with .NET.

Yeah, its not going to be easy 😢 .. exactly when you wrote that im in that issue atm 😅 

> Prerendering failed because of error: Error [ERR_REQUIRE_ESM]: require() of ES Module XXX\ClientApp\dist\server\main.server.mjs not supported. Instead change the require of XXX\ClientApp\dist\server\main.server.mjs to a dynamic import() which is available in all CommonJS modules. at findBootModule (anonymous:55:20) at findRenderToStringFunc (anonymous:61:31) at renderToStringImpl (anonymous:19:54) at module.exports (anonymous:111:5) 

  alto i think it should be possible to fix that  - as we are using these:
- https://github.com/JeringTech/Javascript.NodeJS (this invokes node and should support ESM)
- https://github.com/brunolau/BrunoLau.SpaServices
- +some other custom port of some deprecated services also

Anyway using your suggestion `,no-ssr` should get me working, with just an additional redundant build of the client; alto overall it seems still faster than the older version (at least on a smaller app)
