### ISSUE TITLE
tsconfig.json "paths": {} resolution not working

### ISSUE THREAD

**Issue by MPalix86** [angular/angular-cli#28388]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15

### Description

In our company, we have a large Angular project that consists of a `src` directory and various local libraries. Before upgrading from Angular 15 to Angular 18 with the new application builder, we used `paths` configurations in `tsconfig.json`, combined with `baseUr`l and a Webpack plugin, to directly reference the public API from our projects folder (where the libraries are located). This setup allowed Angular to trigger a rebuild whenever we made changes in a library.

Before migrating our main app to Angular 18, I tested this setup with a new Angular 18 project containing a single library. I found that the paths configuration should be supported out of the box with Angular 18 without needing additional changes.

However, after the migration, I haven’t been able to get Angular (or esbuild) to recognize the `paths` defined in the `tsconfig.json` file. It seems that Angular is reading the compiled versions of the libraries inside `node_modules`, ignoring the paths configuration in `tsconfig.json`. I've tried various configurations, including changing `moduleResolution` to `bundler`, but none of these have resolved the issue. While VS Code's IntelliSense correctly recognizes the `paths` defined in `tsconfig.json` and does not show errors, running ng serve results in a series of errors:  
<br>
<b>  TS2307: Cannot find module '...' or its corresponding type declarations.</b>

### Minimal Reproduction

[Reproduction](https://github.com/MPalix86/angular-issue-28388)

### Exception or Error

```text
TS2307: Cannot find module '....' or its corresponding type declarations. [plugin angular-compiler]
```

### Your Environment

```text
Angular CLI: 18.2.3
Node: 18.19.1
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 18.2.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1802.3
@angular-devkit/build-angular      18.2.3
@angular-devkit/core               18.2.3
@angular-devkit/schematics         18.2.3
@angular/material                  17.3.10
@angular/material-moment-adapter   17.3.10
@schematics/angular                18.2.3
ng-packagr                         18.2.1
rxjs                               7.8.1
typescript                         5.5.4
zone.js                            0.14.10
```

**Comment by alan-agius4** [comment]
Without a reproduction it’s hard to tell what is happening. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by MPalix86** [comment]
I have provided the link to the reproduction above.

**Comment by alan-agius4** [comment]
The current behavior is expected because, in https://github.com/MPalix86/angular-issue-28388/blob/426016a53fb25802d5e1ccac4e7d15a24700362d/tsconfig.app.json#L11-L23, there is no path mapping defined for the local library. To resolve the issue, you need to add the appropriate path mapping.
