### ISSUE TITLE
Remove protractor from @angular-devkit/build-angular

### ISSUE THREAD

**Issue by Stargator** [angular/angular-cli#28382]
### Command

new

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

[Protractor was set to End of Life in Sept 2023](https://blog.angular.dev/protractor-deprecation-update-august-2023-2beac7402ce0), but it still resides as a peer dependency in [@angular-devkit/build-angular](https://github.com/angular/angular-cli/blob/18.2.3/packages/angular_devkit/build_angular/package.json#L89) (and maybe others).

This results in new apps including protractor as a transitive peer dependency. And as time goes on any outdated dependencies will likely have vulnerabilities detected and that can result in security scans failing those projects.

### Minimal Reproduction

Just run `ng new` and look in the package-lock.json

### Your Environment

```text
Angular CLI: 17.3.8
Node: 18.18.2
Package Manager: npm 10.8.1
OS: darwin arm64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1703.8 (cli-only)
@angular-devkit/core         17.3.8 (cli-only)
@angular-devkit/schematics   17.3.8 (cli-only)
@schematics/angular          17.3.8 (cli-only)
```

**Comment by Stargator** [comment]
@JeanMeche for SA

**Comment by clydin** [comment]
`protractor` is an optional peer dependency and will not be installed in a new project unless explicitly added by a developer.

**Comment by Stargator** [comment]
It's in the package-lock.json of my application and any new Angular app I create with `ng new`. Even if I don't add it to my dev dependencies or dependencies, it's in my node_modules because other dependencies have it like @angular-devkit/build-angular

**Comment by clydin** [comment]
It's in the `package-lock.json` because the file lists all potential optional dependencies regardless of whether they are installed.
This includes packages such as `tailwindcss`, `@web/test-runner`, `jest`, and more.
`protractor` will not be installed unless manually installed or `ng generate e2e` is used in a project.
`npm ls protractor` will return the following for both the latest v17 and v18:
```
└── (empty)
```

Example `package-lock.json` section from a new project:
```
      "peerDependenciesMeta": {
        "@angular/localize": {
          "optional": true
        },
        "@angular/platform-server": {
          "optional": true
        },
        "@angular/service-worker": {
          "optional": true
        },
        "@web/test-runner": {
          "optional": true
        },
        "browser-sync": {
          "optional": true
        },
        "jest": {
          "optional": true
        },
        "jest-environment-jsdom": {
          "optional": true
        },
        "karma": {
          "optional": true
        },
        "ng-packagr": {
          "optional": true
        },
        "protractor": {
          "optional": true
        },
        "tailwindcss": {
          "optional": true
        }
      }
```

**Comment by alan-agius4** [comment]
Closing as per above.
