### ISSUE TITLE
Detection changes code not working

### ISSUE THREAD

**Issue by CamiloPaternina0910** [angular/angular-cli#28380]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

I have created several projects with different configuration options, but I always have the same problem.

`The source map for "../Documents/projects/angular/licenciaProV1/.angular/vite-root/licenciaProV1/chunk-NMRNJXZ3.mjs" indicates that source files are missing`.

struture: 
Angular CLI: 17.3.9
Node: 18.15.0
Package Manager: npm 9.5.0
OS: win32 x64

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.9
@angular-devkit/build-angular   17.3.9
@angular-devkit/core            17.3.9
@angular-devkit/schematics      17.3.9
@angular/cli                    17.3.9
@angular/ssr                    17.3.9
@schematics/angular             17.3.9
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.10

After that angular doesn't able to refresh after changes on my code, any solution?

### Please provide a screenshot if possible [Bug Report only]

![image](https://github.com/user-attachments/assets/cb73bc9f-3267-4176-96dc-f50d319e60fb)

**Comment by Diaskhan** [comment]
Could u give a link to repo to reproduce that ? 
In few issues I heard bun doesn't support patching, that's why it's not reloaded.
Try hard reset maybe helps.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
