### ISSUE TITLE
live reload fails when proxyConfig specifies location for root

### ISSUE THREAD

**Issue by dsl400** [angular/angular-cli#28391]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

connection to livereload fails when proxyConfig specifies location for "/" 

For a faster development I am trying to integrate the output of ng serve straight into the existing application to reduce the "develop > build > deploy > test" cicle

The current implementation for the development server does not send  the requests made to "localhost:4200/<baseHref>/......." to be evaluated by the proxy manager. This could be a good thing if it where the same for livereload websocket connection.

### Minimal Reproduction

`ng new `

inside `angular.json`
```
"achitect":{
    "build":{
        "configurations":{
            "development":{
                "baseHref": "/custom/test/"
    .......................................
    "serve": {
        "options":{
            "proxyConfig": "proxy.conf.json"
```

inside `proxy.conf.json`

```
{
    "/": {
        "target": "<staging-server>",
        "secure": false,
        "ws": true
    }
}
```

### Exception or Error

```text
connection to live-reload websocket fails 


WebSocketClient.js:16 WebSocket connection to 'ws://localhost:4200/custom/test/ng-cli-ws' failed: Invalid frame header
```
```


### Your Environment

```text
Angular CLI: 14.0.7
Node: 18.18.2 (Unsupported)
Package Manager: npm 10.3.0 
OS: linux x64

Angular: 14.3.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.13
@angular-devkit/build-angular   14.2.13
@angular-devkit/core            14.2.13
@angular-devkit/schematics      14.0.7
@angular/cli                    14.0.7
@schematics/angular             14.0.7
rxjs                            7.5.7
typescript                      4.7.4
```

**Comment by alan-agius4** [comment]
Angular version 14 is no longer supported. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
