### ISSUE TITLE
project structure

### ISSUE THREAD

**Issue by krasevych** [angular/angular-cli#284]
Hello everyone.
All files generate into ```app``` folder.
```
app/services/...
app/components/...
```
And after I generated route with name ```'route1'``` it was generated into ```app/..```  like ```app/route1```
If there are a lot of routers into  ```app/...``` it  looks a little mess.
maybe will be better create routers into ```app/...```(all routers)
and folder like: services, pipe,.... into ```common``` folder?
like:
```
common/services/...
common/components/...
...
```
```
app/route1
app/route2
app/route3
```

**Comment by Brocco** [comment]
There are plans in the pipeline to align the project structure with an approved style guide. So while it currently does not, there is a plan in place.

**Comment by krasevych** [comment]
@Brocco How do you think, when it will be ready?

**Comment by Brocco** [comment]
Not sure at this point, it will be a high priority after a style guide is approved.

**Comment by krasevych** [comment]
@Brocco Thank you!
