### ISSUE TITLE
After first steps "webpack: bundle is now VALID"

### ISSUE THREAD

**Issue by tomekdorobisz** [angular/angular-cli#2842]
Windows 8.1
Node.js 6.9.1

After:
> npm install-g angular-cli
(after that there were some errors and warnings)
>ng new my-dream-app
>cd my-dream-app
>ng serve

All I can see is
"webpack: bundle is now VALID" and nothing is happening.

Is there some solution for that?
I started doing that before installing anything else not counting installation Node.js 
All command were typed in cmd of Windows.

**Comment by grizzm0** [comment]
What do you mean by "nothing is happening"? Is the site running at localhost:4200?

**Comment by tomekdorobisz** [comment]
It wasn't running. After a few starts it is now. 
Typical situation. 
I thought there's something wrong as it didn't return my result as I seen on tutorial.

**Comment by hectorMurillo** [comment]
Check you localhost in my case it was on port 4200 and you shuld be able to see "app works!"

**Comment by memboc** [comment]
same problem

ng new my_app --link-cli
cd my_app
ng serve


```

                                                                     Hash: 86b55ecec2f5b62d6722           Time: 6230ms                                                                                              chunk    {0} main.bundle.js, main.bundle.map (main) 58.7 kB {2} [initial] [rendered]                      chunk    {1} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 1.77 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 176 kB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (D:\projects\ng\my_app\node_modules\typescript\lib\typescript.js:8062:20)
    at Object.createCompilerHost (D:\projects\ng\my_app\node_modules\typescript\lib\typescript.js:44978:26)
    at Object.ngcLoader (D:\projects\ng\my_app\node_modules\@ngtools\webpack\src\loader.js:171:31)
 @ multi main
webpack: bundle is now VALID.
```

On http://localhost:4200/ writes only Loading...

**Comment by davido-valdor** [comment]
Similar issue....

`Time: 9269ms
chunk    {0} main.bundle.js, main.bundle.map (main) 4.47 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 9.96 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.85 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: bundle is now VALID.`

On http://localhost:4200/ writes only Loading...

**Comment by bofcarbon1** [comment]
Where is the port configuration for this build?  It doesn't start up a server. Shouldn't the index.html at least display something that shows us an application is running?  Web pack is there to split the threads into a main UI and background process. I've seen a different result with a YouTube video on angular2-cli. Now on Cloud 9 I have to alter the port to 8080,81 or 82. But I'll be damned if I know where angular2-cli put this. Maybe they never intended to do that. Not what I expected to see.
