### ISSUE TITLE
ng serve returns 404 error when route ends with .html / .xhtml

### ISSUE THREAD

**Issue by tallence-dsulyok** [angular/angular-cli#28439]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

We recently updated our application from Angular v14 to v18.

```
"serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
```

In v14 when using `ng serve` during local development with the above config in angular.json we were able to access routes such as 

```
{path: 'foo.xhtml', component: FooComponent},
{path: 'bar.xhtml', component: BarComponent},
```
Now, in v18 we get a 404 error stating "Cannot GET /app-path/foo.xhtml".

I found several bug reports, but all closed, eg. https://github.com/angular/angular-cli/issues/27905
Is there any configuration / workaround to make the old URLs work again in our application? These are mainly legacy URLs we have to support to not break dozens of clients relying on this URL schema we took over when migrating our app's frontend to Angular.

### Minimal Reproduction

ng serve an application with app routing as follows:
```
...
{path: 'foo.xhtml', component: FooComponent}
...
```

Open foo.xhtml in browser.

### Exception or Error

```text
Cannot GET /app-path/foo.xhtml
```

### Your Environment

```text
Angular CLI: 18.2.4
Node: 20.17.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 18.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.4
@angular-devkit/build-angular   18.2.4
@angular-devkit/core            18.2.4
@angular-devkit/schematics      18.2.4
@schematics/angular             18.2.4
rxjs                            7.5.6
typescript                      5.4.5
zone.js                         0.14.10
```

**Comment by JeanMeche** [comment]
Hi, this was alreay brought up in #28125. 

> As explained in https://github.com/angular/angular-cli/issues/27905, it's generally recommended to avoid including file extensions in URLs. This simplifies server-level routing.
> 
> Possible solutions:
> 
> * Make no changes, but be aware that refreshing the page will not work when using `ng serve`.
> * Remove .html extensions from URLs. To avoid affecting SEO, you can create a server rule that redirects .html URLs to the corresponding pages without extensions using a 301 redirect. This is the recommended long-term approach.

**Comment by alan-agius4** [comment]
To maintain support for the old URL format in production, implement redirect rules at the server level to route `.html/.xhtml` files to their corresponding extensionless versions.
