### ISSUE TITLE
Feature Request: Shows port number in "Compiled Successfully" message when using ng serve, every time after recompiling.

### ISSUE THREAD

**Issue by Prajwal-I** [angular/angular-cli#28438]
### Command

serve

### Description

After using ng serve, port number is visible in cli only for the first time it compiles, but as we make changes and cli recompiles the application, the port number is not show in the subsequent compiled successfully message. 
It would be great if port number is also shown in the message "Compiled Successfully" every time app recompiles.

**Comment by alan-agius4** [comment]
To display the server url at any time you can press `u + enter`.
