### ISSUE TITLE
Building out-of-module TypeScript code

### ISSUE THREAD

**Issue by raybellis** [angular/angular-cli#28455]
### Command

build, serve

### Description

I am migrating a suite of AngularJS applications to Angular.    All of the existing JS code is currently in the main `public` assets folder so is copied verbatim into the `dist` folder.   All of the code is ESM format .mjs files.

Much of the code is generic JS  and not components, etc.   I wish to gradually rewrite these into TypeScript, so that they can be imported by both the existing code and new Angular components with full type checking and intellisense.

This implies a transpiling step, and I would dearly love for this to be automated via the `watch` system so that `ng serve` notices changes and automatically reloads the code on edit.    While a `tsc && ng build` process might work, it would be very tedious to have to manually rebuild after every edit.

### Describe the solution you'd like

I had hoped that the `scripts` setting would work, but alas no.  (I have seen #17125 and #6393)

I need either individual `.(m)js` files to be generated from the TypeScript, or for specific files to end up in particular bundles.  Since importing a typical AngularJS module has implicit side effects the four separate apps can't all end up in one bundle.

**Comment by alan-agius4** [comment]
This specific use case is outside the scope of the Angular CLI. The CLI is intended to manage Angular projects, including TypeScript transpilation and bundling for Angular components. However, it does not support transpiling files that are outside the context of the application bundles.

In this case, a custom solution is required. You can consider using a custom builder to extend the Angular CLI to meet your needs. A custom builder allows you to hook into Angular CLI commands like `ng serve` and introduce additional build steps, such as running `tsc` to transpile specific files and automatically watch for changes.

**Comment by raybellis** [comment]
At my current level of experience with Angular this is *way* beyond my capabilities, and the docs aren't helping much.   All I can find is examples on how to entirely replace the default builder for the app, and none on adding features to it.

Surely _someone_ has done this before?

**Comment by raybellis** [comment]
At my current level of experience with Angular this is *way* beyond my capabilities, and the docs aren't helping much.   All I can find is examples on how to entirely replace the default builder for the app, and none on adding features to it.

Surely _someone_ has done this before?
