### ISSUE TITLE
Status of Web Test Runner introduction as the replacement of Karma

### ISSUE THREAD

**Issue by jacqueminv** [angular/angular-cli#28481]
As I'm not sure if the comment I posted on the commit itself could get any attention, let me open this issue to get more details on this question below.

I'd love to know where to track this.

Thanks a bunch.

> Hi there,
> 
> 
> 
> I read the mentioned blog post and was wondering if that was stale or still actual.
> 
> Then I found this commit and see that the plan would be to give an update "later this year".
> 
> 
> 
> Is there any issue, RFC or discussion tracking the progress on this move to Jest (or anything being the replacement of Karma which has been deprecated since v6.4.3 7 months ago)?
> 
> 
> 
> I'd love to be able to see the progress on this.
> 
> 
> 
> Thanks! 

 _Originally posted by @jacqueminv in [19ea26c](https://github.com/angular/angular/commit/19ea26c2db889266d9ee0f3bcccd06d91e5761a3#r147144139)_

**Comment by alan-agius4** [comment]
The Angular CLI currently offers two experimental alternatives to Karma for running tests: Web Test Runner and Jest.

Both Web Test Runner and Jest builders are still in an experimental phase, meaning they may not yet have full feature parity with Karma .

**Comment by jacqueminv** [comment]
Thanks for your reply Alan. Could you though tell me where I can track the progress on those alternatives?
The doc I commented (link above) mentions:

> Later this year we'll continue making progress towards introducing Web Test Runner as the replacement of Karma.

Thus I can imagine, this progress would be visible somewhere? A PR, a discussion, anything? The blog post you link to dates back to April 2023!

**Comment by alan-agius4** [comment]
There isn’t a single PR nor a discussion where progress is being tracked. However, in the issue tracker there are various issues assigned to a dedicated label

- https://github.com/angular/angular-cli/issues?q=is%3Aopen+is%3Aissue+label%3Adevkit%2Fbuild-angular%3Aweb-test-runner

- https://github.com/angular/angular-cli/issues?q=is%3Aopen+is%3Aissue+label%3Adevkit%2Fbuild-angular%3Ajest
