### ISSUE TITLE
ng update not working for a multi workspace angular project

### ISSUE THREAD

**Issue by ramkumar-SHS** [angular/angular-cli#28499]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

- Try updating angular with a multi workspace angular project.
- If you run ng update in the location where the root/common package.json is present, it throws an error saying 'this is not an angular workspace.
- If run ng update inside any one of the workspace, we get the error saying "angular cli is not available.

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

expected:
ng update should be updating in the location where the root/common package.json is present

Actual:
it throws an error saying 'this is not an angular workspace.

**Comment by alan-agius4** [comment]
This behavior is expected, as the Angular CLI restricts updates to files within the current workspace for security reasons. Rather than using a multi-workspace setup, it's recommended to opt for a single workspace with multiple projects.

Also related to: #14841
