### ISSUE TITLE
Simplify AoT compilation by ignoring genDir

### ISSUE THREAD

**Issue by robwormald** [angular/angular-cli#2849]
Given the AoT plugin no longer writes generated code to disk, allowing a developer to set the genDir for code generation adds a huge amount of complexity to lazy module resolution.

We should simply assume that the generated code ends up in the (virtual) filesystem as a sibling to the original file, and thus resolving for ngfactory code should require simply appending `.ngfactory` to the path.

**Comment by hansl** [comment]
I'm going to remove the `genDir` option to the plugin entirely. There's absolutely no need for it.
