### ISSUE TITLE
Bug build on esbuild

### ISSUE THREAD

**Issue by g-gibosky** [angular/angular-cli#28516]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm updating an application from angular 4 to angular 18 and Django as backend. 
I migrated to esbuild but I'm getting errors on the browser after a successful build and the applications is broken.

### Minimal Reproduction

Here is the pipeline that i build to integrate Django with the Angular Application:

`
upgrade_build_client:
  artifacts:
    paths:
      - app_build.zip
    expire_in: 4 hour
  only:
    refs:
      - /^.*-upgrade.*$/
  except:
    - schedules
  tags:
    - App
    - linux
    - client_build
    - upgrade_2_0
  stage: build
  script:
    - echo "TEMP change of title and colors for UPGRADE App"
    - sudo sed -i "s/{{ activeRouteTitle }}/UPGRADE App/" static/src/index.html
    - >
      sudo sed -i 's/background: #3C4859/background: #F62266/' static/src/assets/css/styles.css;
    - echo "Proceed with client build"
    - export NVM_DIR="$HOME/.nvm"
    - export NVM_BIN=/home/gitlab-runner/.nvm/versions/node/v18.20.4/bin
    - export NVM_INC=/home/gitlab-runner/.nvm/versions/node/v18.20.4/include/node
    - export PATH=/home/gitlab-runner/.nvm/versions/node/v18.20.4/bin:$PATH
    - env
    - node -v
    - npm -v
    - export PYTHON=/usr/bin/python3.10
    - cd static/
    - rm -rf node_modules/
    - npm install
    - npm run build
    - echo $CI_COMMIT_SHA > CI_COMMIT_SHA.txt
    - cd ../
    - tar czf app_build.zip static

upgrade_shutdown:
  needs: ["upgrade_build_client"]
  only:
    refs:
      - /^.*-upgrade.*$/
  except:
    - schedules
  tags:
    - App_upgrade_01
  stage: build
  script:
    - sudo systemctl stop nginx.service
    - sudo systemctl stop uwsgi.service

upgrade_build_venv:
  needs: ["upgrade_shutdown"]
  only:
    refs:
      - /^.*-upgrade.*$/
  except:
    - schedules
  tags:
    - App_upgrade_01
  stage: build
  script:
    - env
    - hostname
    - pwd
    - $BIN_PYTHON -c "$DL_GB_PY3"
    - if [ -d "$WWW_App_APP_DIR/venv" ]; then tar czf $BACKUPS_App_DIR/venv_"`date +%Y%m%d-%H%M`".tgz $WWW_App_APP_DIR/venv ; fi
    - if [ -d "$WWW_App_APP_DIR/venv" ]; then rm -fR $WWW_App_APP_DIR/venv ; fi
    - $BIN_PYTHON gti-bootstrap-7-3-1.py -r requirements.txt $VENV_App_APP_DIR
    - source $VENV_App_APP_DIR/bin/activate
    - export DJANGO_SETTINGS_MODULE="resource_mgmt.upgrade"
    - pip list

upgrade_backup_www:
  only:
    refs:
      - /^.*-upgrade.*$/
  except:
    - schedules
  tags:
    - App_upgrade_01
  stage: build
  script:
    - if [ -d "$WWW_App_APP_DIR/www" ]; then tar czf $BACKUPS_App_DIR/www_"`date +%Y%m%d-%H%M`".tgz $WWW_App_APP_DIR/www; fi
    - if [ -d "$WWW_App_APP_DIR/www" ]; then sudo rm -fR $WWW_App_APP_DIR/www; fi
    - sudo mkdir $WWW_App_APP_DIR/www
    - echo "Clean up DEV backups directory of old backups. We only need like the last 14 days for UPGRADE"
    - find $BACKUPS_App_DIR -type f -mtime +14 -exec rm -f {} \; -ls

upgrade_deploy_www:
  needs: ["upgrade_backup_www", "upgrade_build_client", "upgrade_build_venv"]
  dependencies:
    - upgrade_build_client
  only:
    refs:
      - /^.*-upgrade.*$/
  except:
    - schedules
  tags:
    - App_upgrade_01
  stage: build
  script:
    - pwd
    - ls -l
    - tar xzf app_build.zip
    - sudo cp -pR * $WWW_App_APP_DIR/www/
    - sudo chown -R gitlab-runner:librarian $WWW_App_APP_DIR/www
    - cd $WWW_App_APP_DIR/www
    - source $VENV_App_APP_DIR/bin/activate
    - export DJANGO_SETTINGS_MODULE="resource_mgmt.upgrade"
    - python manage.py collectstatic --noinput
    - sudo cp static/src/dist/dev/index.html templates/
    - cd $WWW_App_APP_DIR/www/static
    - ls -l

upgrade_migrate_db:
  needs: [ "upgrade_shutdown", "upgrade_deploy_www", "upgrade_build_venv" ]
  only:
    refs:
      - /^.*-upgrade.*$/
  except:
    - schedules
  tags:
    - App_upgrade_01
  stage: build
  script:
    - hostname
    - echo "Run database migrations"
    - echo "Backup local db_App"
    - sudo runuser -u postgres -- /usr/pgsql-14/bin/pg_dump db_App > $BACKUPS_App_DIR/postgres_db_App_"`date +%Y%m%d-%H%M`".sql
    - cd $WWW_App_APP_DIR/www
    - source $VENV_App_APP_DIR/bin/activate
    - export DJANGO_SETTINGS_MODULE="resource_mgmt.upgrade"
    - python manage.py migrate

upgrade_deploy_config:
  needs: ["upgrade_deploy_www"]
  only:
    refs:
      - /^.*-upgrade.*$/
  except:
    - schedules
  tags:
    - App_upgrade_01
  stage: build
  script:
    - sudo cp deploy/App-upgrade-01/etc/nginx/conf.d/resource_mgmt_nginx.conf /etc/nginx/conf.d/
    - sudo cp deploy/App-upgrade-01/etc/nginx/conf.d/resource_mgmt_nginx_ssl.conf /etc/nginx/conf.d/
    - sudo cp deploy/App-upgrade-01/etc/nginx/nginx.conf /etc/nginx/
    - sudo cp deploy/App-upgrade-01/etc/systemd/system/uwsgi.service /etc/systemd/system/
    - sudo cp deploy/resource_mgmt_uwsgi.ini /etc/uwsgi/sites/

upgrade_startup:
  needs: ["upgrade_deploy_config", "upgrade_migrate_db", "upgrade_deploy_www"]
  only:
    refs:
      - /^.*-upgrade.*$/
  except:
    - schedules
  tags:
    - App_upgrade_01
  stage: build
  script:
    - export DJANGO_SETTINGS_MODULE="resource_mgmt.upgrade"
    - sudo systemctl start uwsgi.service
    - sudo systemctl start nginx.service
    - echo "Build and Deploy Complete".

upgrade_unit_test:
  needs: ["upgrade_startup"]
  only:
    refs:
      - /^.*-upgrade.*$/
  except:
    - schedules
  tags:
    - App_upgrade_01
  stage: unit_test
  script:
    - echo "NOT IMPLEMENTED"
  when: manual

upgrade_smoke_test:
  needs: ["upgrade_startup"]
  only:
    refs:
      - /^.*-upgrade.*$/
  except:
    - schedules
  tags:
    - App_upgrade_01
  stage: qa
  script:
    - echo "NOT IMPLEMENTED"
  when: manual

upgrade_clean_temp_backups:
  only:
    refs:
      - /^.*-upgrade.*$/
  except:
    - schedules
  tags:
    - App_upgrade_01
  stage: clean
  script:
    - echo "Clean up backup files that are older than 7 days on UPGRADE."
    - cd $BACKUPS_App_DIR
    - find . -type f -mtime +7 -name "venv_*.tgz" -ls
    - find . -type f -mtime +7 -name "www_*.tgz" -ls
    - find . -type f -mtime +7 -name "postgres_*.gz" -ls
  when: manual

`

### Exception or Error

```text
1)
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec. polyfills-QBXW4TBJ.js:1 Failed to load module script: Expected a JavaScript module script 
        
2)        
GET https://app/media/fontawesome-webfont-5GKVPAEF.woff2?v=4.7.0 net::ERR_ABORTED 404 (Not Found)    
    
3)
GET https://app/media/fontawesome-webfont-Z4ARLA73.woff?v=4.7.0 404 (Not Found)
app/:1 Refused to execute script from 'https://app/scripts-JNRFGZAM.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
        
4)       
       GET https://app/media/fontawesome-webfont-RJ6LE7IU.ttf?v=4.7.0 net::ERR_ABORTED 404 (Not Found)
main-E53WES4S.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

5)
app/:1 Refused to apply style from 'https://app/styles-7NCDMDZU.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.2.4
Node: 18.20.4
Package Manager: npm 10.7.0
OS: linux x64

Angular: 18.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.4
@angular-devkit/build-angular   18.2.4
@angular-devkit/core            18.2.4
@angular-devkit/schematics      18.2.4
@schematics/angular             18.2.4
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10
```

### Anything else relevant?

This is the page after loading:

![image](https://github.com/user-attachments/assets/1a8556ed-3e91-424f-9916-ce2d1f9292ed)

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
