### ISSUE TITLE
Unable to migrate from angular 16 to 17!

### ISSUE THREAD

**Issue by khushmanvar** [angular/angular-cli#28520]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I did ng update to migrate all the dependencies of angular from 16 to 17, and the update command has also migrated all deps to 17 (I have attached a screenshot), but when I am trying to build project, it is throwing me error that `This version of CLI is only compatible with Angular versions ^16.0.0,`

### Minimal Reproduction

![image](https://github.com/user-attachments/assets/41c781a5-3780-4291-89d5-074906496938)
![image](https://github.com/user-attachments/assets/d69a5236-1c40-4e6e-92fe-6d7e7c63e91e)

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.10
Node: 18.18.1
Package Manager: npm 9.8.1
OS: linux x64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.10
@angular-devkit/build-angular   17.3.10
@angular-devkit/core            17.3.10
@angular-devkit/schematics      17.3.10
@angular/cdk                    17.3.10
@angular/cli                    17.3.10
@angular/material               17.3.10
@schematics/angular             17.3.10
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.10
```

**Comment by alan-agius4** [comment]
Likely your global version of the Angular CLI is outdated.

Can you try to use `ng` command directly without using `npx`?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
