### ISSUE TITLE
Feature request: Jasmine SpecRunner

### ISSUE THREAD

**Issue by rcomblen** [angular/angular-cli#2853]
Would be great to be able to run unit tests using the Jasmine SpecRunner served by `ng serve`, rather than being forced to use Karma in development.

Karma is great for continuous integration and code coverage reporting, but not so nice for doing test driven development.

I've been using it with Angular 1 + Gulp + Livereload + SpecRunner.html  and it was really great for productivity.

With Karma, I miss the ability to run a single test, and to have a easy view on the failed expectations (and I need to have two processes compiling my sources, `ng serve` and `ng test`.

Any chance to get that in a future release ?

**Comment by leozulfiu** [comment]
The console can sometimes produce a big output, which is hard to use in development because of finding the beginning of a stacktrace for example. The specrunner has the ability to show me instantly which tests have failed.

**Comment by filipesilva** [comment]
This isn't something we're looking at adding per se. We currently only support Karma, which needs a custom build setup as well. Adding another test option would be very time consuming relatively little benefit I believe.
