### ISSUE TITLE
"You seem to not be depending on @angular/core" when using Bun with Angular

### ISSUE THREAD

**Issue by mdex-geek** [angular/angular-cli#28530]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Issue: I am encountering the following error when trying to use Angular with Bun:
i try user all cmd like 
`bun link`
`bun build `
reinstall all package 
Error: You seem to not be depending on @angular/core.
Steps to Reproduce:

Initialize a new Angular project.
Install dependencies using Bun:

```bun add @angular/core @angular/cli```
Attempt to run the Angular application using Bun.
Expected Behavior: The Angular project should run without any errors related to dependencies.

Actual Behavior: The error suggests that @angular/core is missing, despite being added as a dependency in package.json.

Environment:

Bun Version: 1.1.27
Angular Version: 18.2.5
Operating System: window 11
Additional Context: This issue occurs only when using Bun, but the project works fine when running via Node.js. I suspect that Bun might not be fully compatible with Angular’s dependency resolution

### Minimal Reproduction

`ng serve`
`bun start `

### Your Environment

```text
18.2.5
```

**Comment by JeanMeche** [comment]
Fwiw there is a matching issue on Bun's side : oven-sh/bun#11063.

**Comment by mdex-geek** [comment]
having same error

**Comment by clydin** [comment]
Bun is intended to be a drop-in replacement for Node.js. Any errors that occur as a result of using bun as a runtime with the Angular CLI should be directed to the bun project.
