### ISSUE TITLE
Unable to install dependencies on linux

### ISSUE THREAD

**Issue by Choppi** [angular/angular-cli#28543]
### Command

other

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18.1.1

### Description

Hello,

After switching from Angular **18.1.1 to 18.2.6**, I noticed that the package-lock generated no longer includes all lmdb optional dependencies like **_linux-x64 or win32-x64_**
This means after install locally with npm install and then use npm ci in a pipeline that runs on Linux, it wants to use the linux-x64 package while only the win32-x64 is in the package-lock

More generally, running _npm install_ on a linux system does throw the same error as above :

### Minimal Reproduction

I tried to reproduce it from scratch through ng new workspace and then run npm i
It fails for the same dependency problems but for another reason : 
```
npm error path /home/user/Documents/sources/test/node_modules/@angular/build/node_modules/lmdb
npm error command failed
npm error command sh -c node-gyp-build-optional-packages
npm error node:internal/errors:541
npm error       throw error;
npm error       ^
npm error
npm error TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
```

### Exception or Error

```text
command sh -c node-gyp-build-optional-packages
npm error /app/node_modules/node-gyp-build-optional-packages/node-gyp-build.js:85
npm error   throw new Error(errMessage)
npm error   ^
npm error
npm error Error: No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.17.0
npm error     attempted loading from: /app/node_modules/lmdb and package: @lmdb/lmdb-linux-x64
npm error Error resolving package: Cannot find module '@lmdb/lmdb-linux-x64'
```

### Your Environment

```text
Angular CLI: 18.2.6
Node: 20.17.0
Package Manager: npm 10.8.2
OS: linux x64
```

### Anything else relevant?

N.A

**Comment by alan-agius4** [comment]
This is not caused by the Angular CLI but rather by a bug in npm which doesn’t include all optional dependencies in the lock file.

See: https://github.com/npm/cli/issues/4828

**Comment by Choppi** [comment]
Thanks a lot for you reply, did not expect such a behaviour on a upgrade :)

Sorry for the inconvenience
