### ISSUE TITLE
unable to use `ng new` on stackblitz

### ISSUE THREAD

**Issue by jnizet** [angular/angular-cli#28547]
### Command

new

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

Creating a new project on stackblitz fails. It used to work before

### Minimal Reproduction

- go to https://node.new
- execute `npx @angular/cli new foo` in the terminal
- choose to proceed with the installation
- choose CSS as the stylesheet format

The command stops with the error

```
[Inquirer] Hook functions can only be called from within a prompt
```

### Exception or Error

```text
[Inquirer] Hook functions can only be called from within a prompt
```

### Your Environment

```text
On stackblitz:

Angular CLI: 18.2.6
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64
```

### Anything else relevant?

I don't know if it's a regression on stackblitz or if it's a limitation that always existed, but that previous versions of the CLI didn't have a problem with.

Sorry for the noise if it's purely a stackblitz problem. But it would really be nice to be able to use stackblitz for repros of bugs and demos.

**Comment by alan-agius4** [comment]
This is not caused by Angular CLI, please see: https://github.com/SBoudrias/Inquirer.js/issues/1426
