### ISSUE TITLE
`NG_BUILD_OPTIMIZE_CHUNKS` generates the same hash for different files

### ISSUE THREAD

**Issue by ihsnow** [angular/angular-cli#28569]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

It's possible to create a situation, when with enabled `NG_BUILD_OPTIMIZE_CHUNKS=1`
command `npm run build`, after running the second time, generates a different files with the same hash in the name
This may cause problems with cache

It looks like a new hash always must be added to every file on rollup step, even if a hash from esbuild is already present
[link to the source code](https://github.com/angular/angular-cli/blob/6c618d495c54394eb2b87aee36ba5436c06557bd/packages/angular/build/src/builders/application/chunk-optimizer.ts#L108)

### Minimal Reproduction

https://stackblitz.com/github/ihsnow/chunk-names

### Your Environment

Angular CLI: 18.2.7
Node: 20.15.0
Package Manager: npm 10.8.1
OS: darwin arm64

Angular: 18.2.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.7
@angular-devkit/build-angular   18.2.7
@angular-devkit/core            18.2.7
@angular-devkit/schematics      18.2.7
@schematics/angular             18.2.7
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by ihsnow** [comment]
I can get the files with unique names if setting
`chunkFileNames` in `node_modules/@angular/build/src/builders/application/chunk-optimizer.js`
to ````chunkFileNames: chunkInfo => `${chunkInfo.name.replace(/-[a-zA-Z0-9]{8}$/, '')}-[hash].js````

**Comment by clydin** [comment]
Closed via [#28570](https://github.com/angular/angular-cli/pull/28570)
