### ISSUE TITLE
Build error when index is an empty string in angular.json

### ISSUE THREAD

**Issue by HazzMan2409** [angular/angular-cli#28565]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

It used to be that you could pass in an empty string to index in the angular.json and the build would succeed. Recently there has been a change and now this breaks the build.

Note having index as an empty string is useful for many applications that are loaded in but aren't in charge of the index HTML.

**Comment by clydin** [comment]
It can be set to `false` to bypass index HTML processing. An explicit `false` more clearly represents intent in this case.

**Comment by HazzMan2409** [comment]
Ah that works, thanks :)

I wouldn't have raised this if the docs said the value could be false (which they don't) https://angular.dev/reference/configs/workspace-config#index-configuration
