### ISSUE TITLE
$localize in library not working with esbuild

### ISSUE THREAD

**Issue by gongAll** [angular/angular-cli#28576]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I use $localize in a library and use it as a dependency on my app, it works fine when I build the app with `@angular-devkit/build-angular:browser` however when I switch it to `@angular-devkit/build-angular:browser-esbuild` it suddenly throws the following runtime error, which prevents the app from properly loading:

`Uncaught TypeError: $localize is not a function`.

Do you have any idea of what I might be doing wrong?

### Minimal Reproduction

I can surely provide more info, if need be.

### Your Environment

Angular CLI: 18.2.7
Node: 20.14.0
Package Manager: yarn 1.22.22
OS: linux x64

Angular: 18.2.7
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, platform-browser, platform-browser-dynamic
... pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.7
@angular-devkit/build-angular   18.2.7
@angular-devkit/core            18.2.7
@angular-devkit/schematics      18.2.7
@schematics/angular             18.2.7
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.15.0

**Comment by alan-agius4** [comment]
Likely the application doesn’t have `@angular/localize/init` listed in the polyfills sections of the build.

**Comment by gongAll** [comment]
This is how my angular.json is currently defined:

``` json
{
	"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
	"cli": {
		"analytics": false,
		"schematicCollections": [
			"@angular-eslint/schematics"
		]
	},
	"newProjectRoot": "projects",
	"projects": {
		"tom-frontend": {
			"architect": {
				"build": {
					"builder": "@angular-devkit/build-angular:browser-esbuild",
					"configurations": {
						"development": {
							"buildOptimizer": false,
							"extractLicenses": false,
							"namedChunks": true,
							"optimization": false,
							"sourceMap": true,
							"vendorChunk": false
						},
						"pre-production": {
							"budgets": [
								{
									"maximumError": "5mb",
									"maximumWarning": "2.5mb",
									"type": "initial"
								},
								{
									"maximumError": "4kb",
									"maximumWarning": "2kb",
									"type": "anyComponentStyle"
								}
							],
							"i18nDuplicateTranslation": "error",
							"i18nMissingTranslation": "error",
							"localize": [
								"pt-PT"
							],
							"outputHashing": "all"
						},
						"production": {
							"budgets": [
								{
									"maximumError": "5mb",
									"maximumWarning": "2.5mb",
									"type": "initial"
								},
								{
									"maximumError": "4kb",
									"maximumWarning": "2kb",
									"type": "anyComponentStyle"
								}
							],
							"i18nDuplicateTranslation": "error",
							"i18nMissingTranslation": "error",
							"localize": [
								"en-US",
								"pt-PT"
							],
							"outputHashing": "all"
						}
					},
					"defaultConfiguration": "production",
					"options": {
						"assets": [
							{
								"glob": "**/*",
								"input": "src/assets",
								"output": "assets"
							},
							{
								"glob": "**/*.svg",
								"input": "node_modules/ionicons/dist/ionicons/svg",
								"output": "./svg"
							},
							"src/manifest.webmanifest"
						],
						"index": "src/index.html",
						"inlineStyleLanguage": "scss",
						"localize": [
							"pt-PT"
						],
						"main": "src/main.ts",
						"outputPath": "dist/tom-frontend",
						"polyfills": [
							"@angular/localize/init",
							"zone.js"
						],
						"scripts": [],
						"serviceWorker": true,
						"ngswConfigPath": "ngsw-config.json",
						"stylePreprocessorOptions": {
							"includePaths": [
								"node_modules"
							]
						},
						"styles": [
							"src/assets/scss/styles.scss"
						],
						"tsConfig": "tsconfig.app.json"
					}
				},
				"extract-i18n": {
					"builder": "ng-extract-i18n-merge:ng-extract-i18n-merge",
					"options": {
						"browserTarget": "tom-frontend:build",
						"outputPath": "src/assets/locales",
						"prettyNestedTags": false,
						"targetFiles": [
							"messages.pt-PT.xlf"
						]
					}
				},
				"lint": {
					"builder": "@angular-eslint/builder:lint",
					"options": {
						"lintFilePatterns": [
							"src/**/*.ts",
							"src/**/*.html"
						]
					}
				},
				"serve": {
					"builder": "@angular-devkit/build-angular:dev-server",
					"configurations": {
						"development": {
							"buildTarget": "tom-frontend:build:development"
						},
						"pre-production": {
							"buildTarget": "tom-frontend:build:pre-production"
						},
						"production": {
							"buildTarget": "tom-frontend:build:production"
						}
					},
					"defaultConfiguration": "development"
				},
				"test": {
					"builder": "@angular-devkit/build-angular:karma",
					"options": {
						"assets": [
							{
								"glob": "**/*",
								"input": "src/assets",
								"output": "assets"
							},
							{
								"glob": "**/*.svg",
								"input": "node_modules/ionicons/dist/ionicons/svg",
								"output": "./svg"
							},
							"src/manifest.webmanifest"
						],
						"inlineStyleLanguage": "scss",
						"polyfills": [
							"@angular/localize/init",
							"zone.js",
							"zone.js/testing"
						],
						"scripts": [
						],
						"stylePreprocessorOptions": {
							"includePaths": [
								"node_modules"
							]
						},
						"styles": [
							"src/assets/scss/styles.scss"
						],
						"tsConfig": "tsconfig.spec.json"
					}
				}
			},
			"i18n": {
				"locales": {
					"pt-PT": {
						"baseHref": "pt-PT/",
						"translation": "/src/assets/locales/messages.pt-PT.xlf"
					}
				},
				"sourceLocale": {
					"baseHref": "en-US/",
					"code": "en-US"
				}
			},
			"prefix": "tom",
			"projectType": "application",
			"root": "",
			"schematics": {
				"@schematics/angular:component": {
					"style": "scss"
				}
			},
			"sourceRoot": "src"
		}
	},
	"schematics": {
		"@schematics/angular:component": {
			"changeDetection": "OnPush",
			"inlineStyle": true,
			"style": "none"
		}
	},
	"version": 1
}

```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by gongAll** [comment]
@alan-agius4 Ok, I will try to provide the reproduction until the end of the day. Cheers

**Comment by gongAll** [comment]
After debugging this issue on https://github.com/daniel-sc/ng-extract-i18n-merge/issues/116, we concluded that the issue was in fact related to angular, or some misconfiguration on my app.

Either way, the initial minimal repro is now able to reproduce the bug without that dependency.

Minimal repro: https://github.com/gongAll/angular-cli-28576

**Comment by alan-agius4** [comment]
I was able to replicate the problem using `ng serve`. It's unclear how this issue got side tracked to the extraction of i18n translations.

The situation is complicated due to the same library being both an NPM dependency and a local package, which creates a cyclic dependency.

The core issue arises from the use of `$localize` in the third-party dependency `@gongall/example-library`, which is being prebundled. As a result, the translations and `$localize` calls are not being replaced, leading to the error.

To resolve this, you need to exclude this library from prebundling in your configuration:

```json
"serve": {
  "builder": "@angular-devkit/build-angular:dev-server",
  "configurations": {
    "development": {
      "buildTarget": "repro-app:build:development",
      "prebundle": {
        "exclude": ["@gongall/example-library"]
      }
    },
    "production": {
      "buildTarget": "repro-app:build:production"
    }
  },
  "defaultConfiguration": "development"
}
```

While this should work, it does not in your case due to a few factors in your project:

- You have a cyclic dependencies.
- Deep Imports from your library are being used.

However, since the library is a local package, you might not need to add the above configuration. Instead, you can resolve the cyclic dependency and removing the deep imports by applying the following patches:

```diff
diff --git a/projects/demo/src/app/app.component.ts b/projects/demo/src/app/app.component.ts
index fdd1afe..6153312 100644
--- a/projects/demo/src/app/app.component.ts
+++ b/projects/demo/src/app/app.component.ts
@@ -1,8 +1,7 @@
 import { CommonModule } from '@angular/common';
 import { Component } from '@angular/core';
 import { RouterOutlet } from '@angular/router';
-import { getLocalizedTranslation as distGetLocalizedTranslation } from '@example-library';
-import { getLocalizedTranslation as nodeModulesGetLocalizedTranslation } from '@gongall/example-library';
+import { getLocalizedTranslation as distGetLocalizedTranslation, getLocalizedTranslation as nodeModulesGetLocalizedTranslation, } from '@example-library';
 
 @Component({
   selector: 'app-root',
diff --git a/projects/example-library/src/public-api.ts b/projects/example-library/src/public-api.ts
index ff031b3..9dd4879 100755
--- a/projects/example-library/src/public-api.ts
+++ b/projects/example-library/src/public-api.ts
@@ -1 +1 @@
-export * from '@gongall/example-library/src/lib/common';
+export * from './lib/common';
diff --git a/tsconfig.json b/tsconfig.json
index 486a0fc..9688ccc 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -28,9 +28,6 @@
       "@example-library": [
         "dist/example-library",
         "dist/example-library/*",
-      ],
-      "@gongall/example-library/*": [
-        "projects/example-library/*"
       ]
     },
     "skipLibCheck": true,
```

**Comment by gongAll** [comment]
Man this makes absolutely no sense, I'm afraid.

I made the local dependency strictly for you to be able to check how the node modules dependency was being built and published.

From what you wrote it seems that either my example library is not properly setup or you don't understand exactly how the library is setup.

And instead of removing the local dependency, which fine you can do, you remove the node modules dependency, **which is the one that is actually throwing the error**.

Let me remind you that this is a repro, not the original environment, yes?

I'm giving you a reproduction which reproduces (lol) the error. And you close the issue without actually pinpointing what is causing the issue and what can fix the issue...

I also do not understand what cyclic dependency I have, in your opinion, since this was never an issue before (If I had a cyclic dependency I guess I would've had problems with it before...)

But fine, for the sake of arriving to a conclusion I simplified the [minimal repro](https://github.com/gongAll/angular-cli-28576) and removed the local library, so you can see the error still happening without it.

I ask you to see if that helps us arriving to a solution.

**Comment by alan-agius4** [comment]
@GongAll, based on the reproduction provided, I’ve outlined the solution, including a diff that demonstrates how to fix the circular dependency and the necessary configuration changes.

However, the same resolution still applies, with the addition that you must also add `@gongall/example-library` to the prebundle exclude list, as the library is now sourced from NPM rather than a local project.

However, `@gongall/example-library` still has a deep import on `@gongall/example-library/src/lib/common`, which causes the problem.

As a workaround, you could also add `@gongall/example-library/src/lib/common` to the prebundle exclude list, but I recommend eliminating the deep import instead as per my patch above.
