### ISSUE TITLE
Using "npm link" with Angular 18

### ISSUE THREAD

**Issue by fabionolasco** [angular/angular-cli#28575]
### Command

serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular 17

### Description

When working on Angular Libs from independent initiatives, the applications and the libs are set on different folders, projects, and repositories. Then, by using "npm link" inside the dist folder of each lib we are able to add them to our machine's NPM registry. This allow us to go to inside each applications and run "npm link my-lib", creating a seamless connection between local apps and local libs . This setup helps speed up the development process, since changes to the libs will trigger it to be recompiled, which then triggers the applications to be recompiled, leading to a quick browser update. This work setup is efficient, clean, and has worked for years. However, once I updated my whole infrastructure to Angular 18, that workflow stopped working. It turns out, it seems that Angular 18 stopped supporting the symbolic links generated by "npm link my-lib." That is is a big issue, because I cannot bring all apps and libs inside the same project or repo (mono repo). They belong to different organizations and must be kept separated. Also, deploying my libs to a remote npm registry every time I need to test a code change to the libs would make it very impractical.

Would it be possible for the Angular team (or Angular CLI team) to bring back the ability to use "npm link" on Angular projects?

I am sure you had reasons to drop that feature, but it is quite important for many people I know.

I sincerely appreciate your help on this! =)

### Minimal Reproduction

Terminal 1)
$: cd my-lib
$: ng build my-lib
$: cd dist/my-lib
$: npm link
$: cd -
$: ng serve

Terminal 2)
$: ng new myApp
$: cd myApp
$: npm link my-lib-name
$: ng serve

### Your Environment

Angular CLI: 18.2.6
Node: 20.17.0
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 18.2.6
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.6
@angular-devkit/build-angular   18.2.6
@angular-devkit/core            18.2.6
@angular-devkit/schematics      18.2.6
@schematics/angular             18.2.6
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

### Anything else relevant?

This is a Critical issue, as it is significantly impacting the work of many teams.

**Comment by sushilchaurasia1990** [comment]
Same issue happening for me as well. can someone update on this on how to fix this issue. it is impacting the work.

**Comment by clydin** [comment]
Can you provide additional details regarding what is not working? 
Linked dependencies are used fairly frequently when developing and testing the Angular CLI as the framework dependencies are developed in a different repository.

A minimal reproduction demonstrating the problem would also be useful.

**Comment by fabionolasco** [comment]
Ok, let me clarify.
Imagine an Application A and a Lib X.
Both are Angular 18 and they are both independent projects, with their own folders and repos.
Let's say now that app A uses Lib X.
The goal is to work on Lib X, make code changes in it, and to have it automatically update app A on the browser, so I can see the effects. That would be easy if we were using mono repo or multi project work environment. But business constraints does not allow me to do that.

So, for years I have been going to Lib X and running "ng build --watch". In that way, every time I change the Lib X code, it quickly recompiles it. And because I ran "npm link" inside "./dist/lib-x" folder, and then "npm link lib-x" inside app A folder, the app A always automatically refreshes every time Lib X recompiles. This has been working for years and is surprisingly fast. 

This approach might not be ideal, but in the real world, given usual constraints of different projects, this has been the main solution for me. It works great. But it stopped working when I migrated to Angular 18.

Today I came about a possible workaround, which I don't know if it is good or bad. But it is providing some relief for now. I am editing the "angular.json" file as per definitions below:

1) Replace: 
"builder": "@angular-devkit/build-angular:application",
with
"builder": "@angular-devkit/build-angular:browser",
 
2) Replace: 
"browser": "src/main.ts",
with
"stylePreprocessorOptions": {
              "includePaths": [
                     "node_modules"
               ]
 },
 "main": "src/main.ts", 

I am sure that this change of the builder property from "application" to "browser" should carry some implications that I do not know about... but it fixed the issue, causing app A to recompile every time Lib X recompiles automatically because of "ng build --watch".

A) Is this an acceptable solution?
B) Am I losing anything benefit from Angular 18 or Angular CLI by doing that?
C) Can we change the "application" mode of the builder to work with "npm link" as well?

**Comment by alan-agius4** [comment]
For your case you can exclude your library from prebundling.

```
"serve": {
  "builder": "@angular-devkit/build-angular:dev-server",
  "options": {
    "buildTarget": "ng:build",
    "prebundle": {
      "exclude": ["my-lib"]
    }
  },

**Comment by fabionolasco** [comment]
Hi Alan, 
Thank you so much for your reply!
However, I fear you closed this ticket prematurely.
I tested your solution and, interestingly, it did cause the app to recompile when my-lib got recompiled. However, it didn't work, in the sense that the app did not inherit the latest changes from my-lib. 
Did you see the solution I proposed above? It works as expected, though I don't know if it is a good idea to do that.
Do you know if that solution is acceptable?
