### ISSUE TITLE
Feature request: move ɵextractRoutesAndCreateRouteTree to public api

### ISSUE THREAD

**Issue by zip-fa** [angular/angular-cli#28582]
### Command

serve, build

### Description

Hi. We use ɵextractRoutesAndCreateRouteTree to build sitemap.xml without a hassle. Currently, this api is private and i don't think it will last long here. Is it possible to move it to public api?

**Comment by alan-agius4** [comment]
This is an intriguing way to leverage `ɵextractRoutesAndCreateRouteTree`. I can see the potential for exposing this information in different ways in the future, especially as the underlying APIs become more stable. However, it's important to remember that `extractRoutesAndCreateRouteTree` is highly private, and I anticipate changes in the upcoming version. Additionally, the return object consists of an internal data structure. 

It's also worth mentioning that the APIs associated with `extractRoutesAndCreateRouteTree` are currently in developer preview. However, auto-generating a sitemap could be an interesting feature request.
