### ISSUE TITLE
"prerender": false is ignored with "outputMode": "server"

### ISSUE THREAD

**Issue by zip-fa** [angular/angular-cli#28590]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi.
"prerender": false is ignored with "outputMode": "server": angular tries to prerender all my routes and i receive "undefined" message on routes extraction step:

![Image](https://github.com/user-attachments/assets/a2e8e9dc-a706-4c4c-a5dd-869036d95e2c)

ng build command now only reacts to "export NG_BUILD_PARTIAL_SSR=true && ng build" - build does not fail with this setup

### Minimal Reproduction

ng build

### Your Environment

v19.0.0-next.8

**Comment by alan-agius4** [comment]
It is by design that the prerender option is ignored.

The `outputMode` is only intended to be used with the new SSR APIs, where the rendering modes are configured at route level.

That being said, the error is definitely not helpful, can you please provide a minimal reproduction?

**Comment by alan-agius4** [comment]
With this config, indeed none of the routes will be pre-rendered. Although the application will still be bootstrapped during the build to generate the SSR manifest.

**Comment by zip-fa** [comment]
Alright, it took me 2 hours to find the cause of "undefined" error. It's again an http client:

I've modified prerender.js directly in node_modules :))
![Image](https://github.com/user-attachments/assets/37068743-a07b-494c-9749-00bf49d6600b)

To find this:

![Image](https://github.com/user-attachments/assets/1bf6edbb-b0dd-43e5-99e6-764237c8aada)

**Comment by zip-fa** [comment]
I've added catchError with isPlatformServer check to my global http interceptor and now everything works perfect:
- build goes ok
- server doesn't crash
