### ISSUE TITLE
extract-i18n performance issues

### ISSUE THREAD

**Issue by Carlosamouco** [angular/angular-cli#28597]
### Command

extract-i18n

### Description

After installing https://www.npmjs.com/package/stimulsoft-reports-js, I noticed that `ng extract-i18n` became very slow, from approx. 1 minute to almost 4 minutes. This package is very large, and I suspect that it is taking so long because the extract-i18n command is trying to look for messages in the whole chunk that contains this dependency.

### Describe the solution you'd like

Could there be a way to make the tool skip analyzing third-party dependencies that have nothing to do with angular? For example, create a list of dependencies to skip?

### Describe alternatives you've considered

Since I am not using any third party angular libraries, I am considering extracting the messages directly from the source code using a ts parser.

**Comment by alan-agius4** [comment]
You can mark that specific library via another build configuration.

```
"architect": {
"build": {
  "builder": "@angular-devkit/build-angular:application",
  "configurations": {
    "development": {},
    "i18n-extract": {
      "externalDependencies": ["my-deps"]
    },
    "production": {
    }
  },
  ...
},
"extract-i18n": {
  "builder": "@angular-devkit/build-angular:extract-i18n",
  "options": {
    "buildTarget": "my-project:build:production,i18n-extract",
    "outputPath": "locales"
  }
},
```
