### ISSUE TITLE
ng serve outPath info

### ISSUE THREAD

**Issue by betfun** [angular/angular-cli#2860]
Hello,

I just updated to beta.18 and I cannot understand where the output of ng serve is.

The "dist" directory is generated only with the ng build command.

Thanks

### OS?
> Windows 7

### Versions.
angular-cli: 1.0.0-beta.18
node: 6.7.0
os: win32 x64

### Repro steps.
ng serve

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
It's served from memory.

**Comment by DavideViolante** [comment]
ng serve has no output, it runs a server.

**Comment by betfun** [comment]
OK understood. 

Thanks
