### ISSUE TITLE
Ionic component styles not loading with Angular SSR

### ISSUE THREAD

**Issue by sureshkumarsendrayan** [angular/angular-cli#28616]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm using Angular 18 standalone application with Ionic 8 and enabled server side rendering. When I try to run SSR, the styles of ionic components are not loading. It just loads the plain html.
![Image](https://github.com/user-attachments/assets/8ab6078a-699f-4965-901f-9ad67197749a)

### Minimal Reproduction

**server.ts:**
`const commonEngine = new CommonEngine({
	enablePerformanceProfiler: true
});

// Cerca dinamicamente il file CSS generato con hash
const cssFileName = readdirSync(distFolder).find(
	(file) => file.startsWith('styles') && file.endsWith('.css')
);

server.set('view engine', 'html');
server.set('views', distFolder);

// Serve i file statici
server.get(
	'*.*',
	express.static(distFolder, {
		maxAge: '1y'
	})
);

// Gestisce tutte le altre richieste utilizzando l'engine Angular
server.get('*', (req, res, next) => {
	const { protocol, originalUrl, baseUrl, headers } = req;

	commonEngine
		.render({
			bootstrap,
			documentFilePath: indexHtml,
			url: `${protocol}://${headers.host}${originalUrl}`,
			publicPath: distFolder,
			inlineCriticalCss: false,
			providers: [
				{ provide: APP_BASE_HREF, useValue: req.baseUrl },
				{ provide: 'REQUEST', useValue: req },
				{ provide: 'RESPONSE', useValue: res }
			]
		})
		.then((html) => {
			// Inietta dinamicamente il CSS nel contenuto HTML generato
			if (cssFileName) {
				html = html.replace(
					'</head>',
					`<link rel="stylesheet" href="${cssFileName}"></head>`
				);
			}
			res.send(html);
		})
		.catch((err) => next(err));
});

return server;`

### Your Environment

Angular CLI: 18.2.7
Node: 20.15.0
Package Manager: pnpm 9.12.0
OS: win32 x64

Angular: 18.2.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, pwa, router, service-worker, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.7 (cli-only)
@angular-devkit/build-angular   18.2.7
@angular-devkit/core            18.2.7 (cli-only)
@angular-devkit/schematics      18.2.7
@schematics/angular             18.2.7 (cli-only)
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10

--------------------------------

Ionic version:
Ionic:

   Ionic CLI                     : 7.2.0 (C:\Users\ssendrayan\AppData\Roaming\nvm\v20.15.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 8.3.2
   @angular-devkit/build-angular : 18.2.7
   @angular-devkit/schematics    : 18.2.7
   @angular/cli                  : 18.2.7
   @ionic/angular-toolkit        : 12.1.1

Capacitor:

   Capacitor CLI      : 6.1.0
   @capacitor/android : 6.1.2
   @capacitor/core    : 6.1.0
   @capacitor/ios     : 6.1.2

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v20.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.7.0
   OS     : Windows 10

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by sureshkumarsendrayan** [comment]
> This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?
> 
> You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
> 
> This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

Okay. I'll setup a repo and share it here. In the meantime, one update from my side is the ionic component styles are not loading only when hydration is enabled. If I use ngSkipHydration: 'true' in the component, then it's working. But I need to fix this with hydration enabled.

**Comment by sureshkumarsendrayan** [comment]
> This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?
> 
> You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
> 
> This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

Here is the minimal reproducible [repo](https://github.com/skarps0711/ssr-style-issue-repo)

**Comment by sureshkumarsendrayan** [comment]
Also, getting below mentioned error when I try to use <ion-header></ion-header> in the application with hydration. 

**Code:**
`<ion-header>
  <ion-toolbar>
    <ion-title>Header</ion-title>
  </ion-toolbar>
</ion-header>`

**Error:**
![Image](https://github.com/user-attachments/assets/55b23b79-5aea-4430-a1ed-138e26e826d9)
