### ISSUE TITLE
Tree sharking config in template *.html files

### ISSUE THREAD

**Issue by xkx-dev** [angular/angular-cli#28637]
### Command

build

### Description

As the angular has already support  the built-in control workflow in template.

like
``` html
@if( __ENV_PROD__){
   < PROD-COMP>
} @else {
  <some -comp>
}
```
how to config some global vialiables  ` __ENV_PROD__` to enable the tree sharking in both ts and html files ?

**Comment by alan-agius4** [comment]
Tree-shaking cannot be applied to code within the templates.
