### ISSUE TITLE
Default generated favicon.ico doesn't work -> rename to png works

### ISSUE THREAD

**Issue by hci2** [angular/angular-cli#28645]
### Command

new

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When scaffolding a new Angular project via `ng new <PROJECT_NAME>` the generated `favicon.ico` does not work. I just renamed it to `favicon.png` and changed the reference in `index.html` and it works immediately.

How about changing the scaffolding to use PNG instead of *.ico?

## favicon.ico (default after generating via `ng create`):
![Image](https://github.com/user-attachments/assets/81c2ef49-a258-45a9-b8df-bbef22309383)

## favicon.png (after renaming and changing):
![Image](https://github.com/user-attachments/assets/db979dc1-b546-42cd-a2bb-b6512642538b)

### Your Environment

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.2.8
Node: 20.17.0
Package Manager: npm 10.9.0
OS: darwin arm64

Angular: 18.2.8
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.8
@angular-devkit/build-angular   18.2.8
@angular-devkit/core            18.2.8
@angular-devkit/schematics      18.2.8
@schematics/angular             18.2.8
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

### Anything else relevant?

IDE: VS Code (1.94.2 (Universal))
Browser: Chrome (129.0.6668.91 (Official Build) (arm64))
OS: MacOS (15.0.1)

**Comment by hci2** [comment]
Moreover, I also noticed that the docs are not up-to-date regarding `src/assets` and `src/favicon.ico`, see: https://angular.dev/reference/configs/workspace-config#assets-configuration.

**Comment by alan-agius4** [comment]
Hi @hci2, 
I couldn't reproduce the issue you've mentioned.

![Image](https://github.com/user-attachments/assets/82d70074-5e8c-47d0-bd36-0878f22a4e5c)

Regarding the documentation issue, please open an issue at https://github.com/angular/angular.

**Comment by hci2** [comment]
Hmmm, that is weird. I double-checked and it worked in Safari and Firefox as well.

I tried different variants and came to this entry in Stackoverflow (https://stackoverflow.com/a/28436056/11494882) to force the browser to refresh via setting `<link rel="icon" type="image/x-icon" href="favicon.ico?v=2">` in `index.html` and then this finally worked. 

After setting version:
![Image](https://github.com/user-attachments/assets/502f3e57-a85e-46f1-bf48-9b4ff98d0679)

We can close this ticket because it has to do with the caching of Chrome and is not related to the code. Thank you anyway for your help.
