### ISSUE TITLE
Logging from proxy event handlers in `proxy.config.js` is not working for `browser-esbuild` or `application` builders

### ISSUE THREAD

**Issue by whernebrink** [angular/angular-cli#28669]
### Command

serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Works with build-angular:browser

### Description

When using `build-angular:application` or `build-angular:browser-esbuild`, i'm no longer able to log from within the proxy event handlers such as `onProxyReq`,  `onProxyRes`, `onError` etc. This is working fine for `build-angular:browser`.

### Minimal Reproduction

Below is how to reproduce with a simple repository i created.

## angular-builder:browser

1. clone project [Github repro repo]( https://github.com/whernebrink/ng-proxy-config-issue) and run `npm i`
2. `npm start` will use `concurrently` to run a simple express server on `localhost:3000` and then run `ng serve`
3. Initially, the angular.json uses `build-angular:browser`. A logger that will write to a `logs.txt` file is called from `onProxyReq` and `onProxyRes` in the `proxy.conf.js`, which can be seen after page is loaded.

## angular-builder:browser-esbuild

1. Change the builder on line 14 in `angular.json` to `"builder": "@angular-devkit/build-angular:browser-esbuild",`
2. Clear the logs.txt
3. Run `npm start` again.
4. Expected result: `logs.txt` to contain logs
5. Actual result: NO logs

## angular-builder:application

1. Change the builder on line 14 in `angular.json` to `"builder": "@angular-devkit/build-angular:application",`
2. Change on line 18: from `"main": "src/main.ts",` to `"browser": "src/main.ts",`
3. Clear the logs.txt
4. Run `npm start` again.
5. Expected result: `logs.txt` to contain logs
6. Actual result: NO logs

### Your Environment

Angular CLI: 18.2.9
Node: 18.19.1
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 18.2.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.9
@angular-devkit/build-angular   18.2.9
@angular-devkit/core            18.2.9
@angular-devkit/schematics      18.2.9
@angular/cli                    18.2.9
@schematics/angular             18.2.9
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by alan-agius4** [comment]
This is expected, Vite and Webpack use different proxy handlers.
See: https://github.com/vitejs/vite/issues/6129

**Comment by whernebrink** [comment]
> This is expected, Vite and Webpack use different proxy handlers. See: [vitejs/vite#6129](https://github.com/vitejs/vite/issues/6129) and https://vite.dev/config/server-options#server-proxy

Gotcha! Big thanks for the links, appreciate it!
