### ISSUE TITLE
service-worker.js ERR_INVALID_RESPONSE with port other than 4200

### ISSUE THREAD

**Issue by lancevo** [angular/angular-cli#2867]
> ## Please provide us with the following information:
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
> Mac OX X El Capitan
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
> 1.0.0-beta.11-webpack.2  
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
> No
### The log given by the failure.

> Normally this include a stack trace and some more information.

A bad HTTP response code (404) was received when fetching the script.
:4567/service-worker.js:1 GET http://localhost:4567/service-worker.js net::ERR_INVALID_RESPONSE
### Mention any other details that might be useful.

If I start `ng serve --port 4567`, or any port other than 4200, it will display the error above in the console. 

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
You have to look at whatever added that service worker. The CLI itself doesn't add service workers.
