### ISSUE TITLE
Dependency deprecated

### ISSUE THREAD

**Issue by franklinyu** [angular/angular-cli#2871]
There is some deprecation warning when I install:

``` text
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
```

It turns out that this package depends on [1520 package-with-versions](https://gist.github.com/franklinyu/273732e45be9f00fb2a1c8ffe90c5b54#file-angular-dependencies-txt) (there may be different version of same package), making it difficult to track all the dependencies. Dependency chain for the above deprecation:
1. `angular2-template-loader@0.5.0` -> `codecov@1.0.1` -> `execSync@1.0.2` -> `temp@0.5.1` -> `rimraf@2.1.4` -> `graceful-fs@1.2.3`
2. `ember-cli@2.5.0` -> `broccoli-babel-transpiler@5.6.1` -> `babel-core@5.8.38` -> `minimatch@2.0.10`

**Comment by filipesilva** [comment]
A lot of these are beyond our power to change right now so we're not looking at removing these deprecations.
