### ISSUE TITLE
Possible regression with newest AngularNodeAppEngine in @angular/ssr (19.0.0-next.11)

### ISSUE THREAD

**Issue by riccardoperra** [angular/angular-cli#28727]
### Command

build, serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

I created 2 folders in the repository to show use cases that are no longer working

Previously, in <=18 angular applications, we were able to pass `providers` into the CommonEngine options. This allowed to propagate values via injection token retrieved in `server.ts` to the application. 

Not knowing if there is a better approach, those values usually are:
- configurations that must be available also in the angular application. Those values are always present during SSR and sometimes are needed also on the browser, so TransferState is needed to propagate them
  - [app.config.ts](https://github.com/riccardoperra/angular-ssr-repro/blob/aa7b0c50698d981d52446a3043a594d6b69ea21b/18-ssr/src/app/app.config.ts#L16) : example of a token always valuated in both ssr and browser
- server only object that allow to update the request data (e.g. update response headers / status code) / redirect
  - Main use cases are for example the possibility to change the page status to 404 if the requested resource does not exist, preserving navigation.
- static values that must be fetched only on server bootstrap and reused across all requests.

An important use case is that those value **could be used** into other application-level providers, in order to configurate them based on the request providers.

With the new `AngularAppEngine` in v19, I saw from @JeanMeche reproduction that you can pass custom values into the `requestContext` parameter when you render the app ([server.ts](https://github.com/JeanMeche/ssr-v19/blob/eef03da8ab1d2836b135e32f041b62fdb698a9f5/server.ts#L39)), however I have noticed some unusual behaviors that make me think I can't do the same things:

- Those values are not always valuated. It seems that there is a case (the first request?) where those values are null.

![Image](https://github.com/user-attachments/assets/89ec5320-9ed8-4c1c-9184-1d49edbc352f)

Like the screenshot above, (reproducible with `npm run start` into the v19-ssr folder), after the server, the log just show that the first request invoke 2 time the application bootstrap: the first time values in request context (inject via `REQUEST_CONTEXT` token) are null, the second one are valuated. This is critical since the first time an error is thrown, the application breaks.

- Cannot modify request headers/status: with the new native `Response` object, it seems that we are not allowed anymore to update it imperatively into the angular application. [Example](https://github.com/riccardoperra/angular-ssr-repro/blob/aa7b0c50698d981d52446a3043a594d6b69ea21b/19-ssr/src/app/dummy.component.ts#L23)

### Minimal Reproduction

https://github.com/riccardoperra/angular-ssr-repro

### Your Environment

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 19.0.0-next.13
Node: 22.2.0
Package Manager: npm 10.7.0
OS: darwin arm64

Angular: 19.0.0-next.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0-next.13 (cli-only)
@angular-devkit/build-angular   19.0.0-next.13
@angular-devkit/core            19.0.0-next.13 (cli-only)
@angular-devkit/schematics      19.0.0-next.13 (cli-only)
@angular/cli                    19.0.0-next.13
@angular/ssr                    19.0.0-next.13
@schematics/angular             19.0.0-next.13 (cli-only)
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
    
```

**Comment by alan-agius4** [comment]
Providers are intentionally not added directly in `server.ts` by design, as discussed in the [RFC](https://github.com/angular/angular/discussions/56785). Instead, they should be defined within `app.config.server.ts`. To work with `RESPONSE` and `REQUEST`, use the designated DI tokens.

**Before** (in `server.ts`)
```ts
const apiUrl = req.header('x-gw-url') ?? 'http://localhost:3000';

commonEngine.render({
  bootstrap,
  documentFilePath: indexHtml,
  url: `${protocol}://${headers.host}${originalUrl}`,
  publicPath: browserDistFolder,
  providers: [
    { provide: APP_BASE_HREF, useValue: baseUrl },
    { provide: API_URL, useValue: apiUrl },
    {
      provide: SSR_ONLY_UPDATE_STATUS_HANDLER,
      useValue: (code: number) => res.status(code),
    },
  ],
});
```

**Now** (in `app.config.server.ts`)
```ts
const serverConfig: ApplicationConfig = {
  providers: [
    provideServerRendering(),
    provideServerRoutesConfig(serverRoutes),
    {
      provide: API_URL,
      useFactory: () => {
        const req = inject(REQUEST);
        return req?.headers.get('x-gw-url') ?? 'http://localhost:3000';
      },
    },
    {
      provide: SSR_ONLY_UPDATE_STATUS_HANDLER,
      useFactory: () => {
        const res = inject(RESPONSE_INIT);
        return (code: number) => {
           if (res) {
              res.status = code;
           }
        };
      },
    },
  ],
};
```

**Comment by riccardoperra** [comment]
Thanks for the explaination @alan-agius4. 

I just have a doubt with the requestContext. Is it normal that it could be ``null`?
What about data that should be retrieved only at server bootstrap? The ideal case is to use it to load additional information that we want to retrieve inside the bootstrap (one-time only) but the fact that it is not always valued would imply the management of potential cases where it is null
