### ISSUE TITLE
[ERROR] Could not resolve "path"

### ISSUE THREAD

**Issue by UchihaYuki** [angular/angular-cli#28720]
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2 (I haven't tested other versions, since I updated always the way from 14.2 to 18.2)

### Description

Got an error when `npm run build`, but not when `npm run start`.

### Minimal Reproduction
Method 1:
You can run `ng build` in the terminal in this project:
https://stackblitz.com/edit/stackblitz-starters-sux7xx?file=src%2Fmain.ts
Note: the default template uses 18.1, but 18.2 has the same error.

Method 2:
After running:
```
ng new app --defaults --style scss
```
I modified _app.component.ts_
```
import { Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import typescript from 'typescript';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent implements OnInit {
  ngOnInit(): void {
    this.result = typescript.transpile(`class A {}`);
  }
  typescript = typescript;
  result!: string;

  title = 'app';
}
```
Then run:
```
npm run build
```
and got:
![Image](https://github.com/user-attachments/assets/f2aee2af-b319-480c-ae62-f62c1c53d55b)
Since the typescript package has no dependencies, I have no idea where this error came from.

### Exception or Error

See above

### Your Environment

Angular CLI: 18.2.10
Node: 20.14.0
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 18.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.10
@angular-devkit/build-angular   18.2.10
@angular-devkit/core            18.2.10
@angular-devkit/schematics      18.2.10
@angular/cli                    18.2.10
@schematics/angular             18.2.10
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by JoostK** [comment]
`typescript` _does_ import from `source-map-support`, so this dependency is considered by the bundler. That import is guarded by a try-catch clause but that doesn't affect how the bundler processes the dependency graph.

**Comment by JoostK** [comment]
This can be made to work using `externalDependencies` of the `application` buider's options, in particular specifying `source-map-support` as external. This is the right thing to do here as it prevents the dependency from being bundled.

**Comment by UchihaYuki** [comment]
Some more info:
I won't encounter this issue if I update my project from v14 to v18. So I think it's a regression or something.

**Comment by JoostK** [comment]
It may not be a `package.json` dependency, it _is_ imported from the `typescript` bundle:

https://github.com/microsoft/TypeScript/blob/2ac4cb78d6930302eb0a55d07f154a2b0597ae32/src/compiler/sys.ts#L1595-L1602

**Comment by UchihaYuki** [comment]
@JoostK 
Thank you!

But the `browser` property in `package.json` explicitly exclude it, it seems the new bundler doesn't respect it.

**Comment by JoostK** [comment]
That would be #27495.
