### ISSUE TITLE
Karma builder doesn't watch files with "builderMode: application"

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#28730]
### Command

test

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Using the `"builderMode": "application",` option in the Karam builder breaks `ng test` watch capabilities

### Minimal Reproduction

Create a new project with `npx @angular/cli@19.0.0-next.13 new karma-watch --defaults --no-routing`
Add `"builderMode": "application",` to `angular.json` in the `karma`options.
Launch `ng test`
Update any file of the project like `app.component.ts` or `app.component.spec.ts`: the tests don't run again.

### Your Environment

Angular CLI: 19.0.0-next.13
Node: 20.13.1
Package Manager: npm 9.7.1
OS: darwin arm64

Angular: 19.0.0-next.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0-next.13
@angular-devkit/build-angular   19.0.0-next.13
@angular-devkit/core            19.0.0-next.13
@angular-devkit/schematics      19.0.0-next.13
@angular/cli                    19.0.0-next.13
@schematics/angular             19.0.0-next.13
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0

**Comment by jkrems** [comment]
I can repro:

```console
-- Watches for changes:
$ ng test --builder-mode=application --watch

-- Doesn't watch for changes:
$ ng test --builder-mode=application --watch

-- Watches for changes:
$ ng test --builder-mode=browser
```

So it looks like the `--watch` default is different.

**Comment by jkrems** [comment]
Thanks for trying this out & the great bug details. Verified that the following fixes the bug: https://github.com/angular/angular-cli/pull/28739

**Comment by jkrems** [comment]
The fix should be included in this week's `next` release (e.g. ~tomorrow).
