### ISSUE TITLE
SSR: How to disable url normalization?

### ISSUE THREAD

**Issue by JemiloII** [angular/angular-cli#28736]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I just want to stop angular from doing some weird adding a slash then removing a slash. If my route is /products, i don't want it to go to /products/ then have it see another redirect and go back to /products. It's driving me insane that I can't even turn it off.

**Comment by alan-agius4** [comment]
The behavior of Express' static middleware which adds a trailing slash to serve pre-rendered pages; without it, static pages won’t be served.

Here are a couple of potential solutions:
1. Transition to a different framework than Express.js.
2. Manage the serving of pre-rendered pages directly within the Angular App Engine.
