### ISSUE TITLE
ng build --prod router not working

### ISSUE THREAD

**Issue by terrilltang** [angular/angular-cli#2873]
dev model router is working;
but not working in dist directory with nginx server;

ex:
dev model:
locahost:4200/login working 

prod model:
www.xxx.xx/login not working  (dist directory)

angular-cli: 1.0.0-beta.18
node: 4.6.1
os: win32 x64

**Comment by robertbaker** [comment]
Upgrade your node to the latest 6.x, yours is outdated and unsupported. After that you will also need to delete your node_modules and run `npm i. 

Once you do that, please report back if this is still an issue.

**Comment by terrilltang** [comment]
@robertbaker 
do as your suggest,but still not working

**Comment by fxmontigny** [comment]
Hi,

If you use "apache server" to execute your prod env. You need to add rewrite rule into your htaccess like this

`<IfModule mod_rewrite.c>
  Options Indexes FollowSymLinks
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
`

**Comment by clydin** [comment]
As mentioned, this is not related to the CLI.  A quick search on SO lead to this question:
http://stackoverflow.com/questions/7027636/nginx-send-all-requests-to-a-single-html-page

**Comment by terrilltang** [comment]
@clydin thank you! you provide the link solver my question!

>`location / {
    try_files $uri /base.html;
}`
