### ISSUE TITLE
indexHtmlTransformer is missing in buildApplication

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular-cli#28742]
### Command

build

### Description

I am currently trying to prepare `@angular-builders/custom-esbuild` for NG19 and saw that `@angular/build` `buildApplication` has no `indexHtmlTransformer` like dev-server has.

### Describe the solution you'd like

Same `extensions` for `buildApplication` as for dev-server's `execute`.

**Comment by alan-agius4** [comment]
The application builder already supports this.

See: https://github.com/angular/angular-cli/pull/26667

**Comment by muuvmuuv** [comment]
I was talking about `@angular/build` not `@angular-devkit/build-angular` they differ

**Comment by muuvmuuv** [comment]
Oh you right, I have looked up the wrong type definition here: https://github.com/angular/angular-cli/blob/19.0.0-next.13/packages/angular/build/src/builders/application/index.ts#L158

It indeed supports it through "extensions".

**Comment by muuvmuuv** [comment]
Would be nice to export "ApplicationBuilderExtensions" for builder authors tho in "/private" maybe
