### ISSUE TITLE
Component Relative URLs can not be found (getting 404 error)

### ISSUE THREAD

**Issue by SolutiaConsulting** [angular/angular-cli#2874]
> ## Please provide us with the following information:
### OS?

Windows
### Versions.

```
angular-cli: 1.0.0-beta.17                                                                                                                                                        
node: 6.6.0                                                                                                                                                                       
os: win32 x64   
```
### Repro steps.

I'm developing a library that is to be distributed via npm so I can re-use this library in multiple client apps.  This library is a very simple component that works if I use in-line template to render HTML.  However, if I convert the in-line template to a physical HTML file referenced by templateUrl, then I get a 404.  The browser is trying to find the HTML file (my-awesome-component.html) at the root of the app.  The physical HTML actually resides in node_modules (installed via npm install command).

How do you render component relative URLs (HTML and stylesheets) when loading the component from node_modules (this is where the physical files live)?
### The log given by the failure.

Here's the error I receive:

_Failed to load resource: the server responded with a status of 404 (Not Found)
http://local.solutiaconsulting.com/my-awesome-component.html_

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
This isn't something we can resolve in the CLI. The recommendation is that libraries should inline html and css when preparing the package to be distributed via NPM.
