### ISSUE TITLE
Karma builder logs a lot of file changes with "builderMode: application"

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#28755]
### Command

test

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When running `ng test` in watch mode, updating a file triggers a re-run of the tests as expected, but sometimes logs a lot of file changes.

### Minimal Reproduction

Create a new project with `npx @angular/cli@19.0.0-rc.0 new karma-assets --defaults --no-routing`.
Add `"builderMode": "application",` to angular.json in the karmaoptions.
Launch `ng test`
Clear the template `app.component.html` and check the logs.

### Exception or Error

31 10 2024 07:31:27.111:INFO [filelist]: Changed file "/Users/cedric/Code/temp/karma-assets/dist/test-out/c45dfc31-7cf6-461e-b12e-14642f1f29ac/app.component.spec.js.map".
31 10 2024 07:31:27.112:INFO [filelist]: Changed file "/Users/cedric/Code/temp/karma-assets/dist/test-out/c45dfc31-7cf6-461e-b12e-14642f1f29ac/styles.css.map".
31 10 2024 07:31:27.112:INFO [filelist]: Changed file "/Users/cedric/Code/temp/karma-assets/dist/test-out/c45dfc31-7cf6-461e-b12e-14642f1f29ac/styles.css".
31 10 2024 07:31:27.113:INFO [filelist]: Changed file "/Users/cedric/Code/temp/karma-assets/dist/test-out/c45dfc31-7cf6-461e-b12e-14642f1f29ac/init_test_bed.js".
31 10 2024 07:31:27.113:INFO [filelist]: Changed file "/Users/cedric/Code/temp/karma-assets/dist/test-out/c45dfc31-7cf6-461e-b12e-14642f1f29ac/app.component.spec.js".
31 10 2024 07:31:27.113:INFO [filelist]: Changed file "/Users/cedric/Code/temp/karma-assets/dist/test-out/c45dfc31-7cf6-461e-b12e-14642f1f29ac/app.component.css.map".
31 10 2024 07:31:27.114:INFO [filelist]: Changed file "/Users/cedric/Code/temp/karma-assets/dist/test-out/c45dfc31-7cf6-461e-b12e-14642f1f29ac/polyfills.js".
31 10 2024 07:31:27.116:INFO [filelist]: Changed file "/Users/cedric/Code/temp/karma-assets/dist/test-out/c45dfc31-7cf6-461e-b12e-14642f1f29ac/init_test_bed.js.map".
31 10 2024 07:31:27.122:INFO [filelist]: Changed file "/Users/cedric/Code/temp/karma-assets/dist/test-out/c45dfc31-7cf6-461e-b12e-14642f1f29ac/chunk-K7Q6MHAJ.js".
31 10 2024 07:31:27.128:INFO [filelist]: Changed file "/Users/cedric/Code/temp/karma-assets/dist/test-out/c45dfc31-7cf6-461e-b12e-14642f1f29ac/polyfills.js.map".
31 10 2024 07:31:27.155:INFO [filelist]: Changed file "/Users/cedric/Code/temp/karma-assets/dist/test-out/c45dfc31-7cf6-461e-b12e-14642f1f29ac/chunk-K7Q6MHAJ.js.map".

### Your Environment

Angular CLI: 19.0.0-rc.0
Node: 20.13.1
Package Manager: npm 9.7.1
OS: darwin arm64

Angular: 19.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0-rc.0
@angular-devkit/build-angular   19.0.0-rc.0
@angular-devkit/core            19.0.0-rc.0
@angular-devkit/schematics      19.0.0-rc.0
@schematics/angular             19.0.0-rc.0
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0

**Comment by jkrems** [comment]
Thanks for the great reports! I'm hoping that we can get the fixes for this and #28756 / #28754 into the next RC release.
