### ISSUE TITLE
updating to v19-rc.0 cli breaks `ng serve`

### ISSUE THREAD

**Issue by SanderElias** [angular/angular-cli#28764]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

After running `ng upddate @angular/cli --next` to go from `-next.10` 
I goit this error:
![Image](https://github.com/user-attachments/assets/be524e09-4409-45ce-8317-d760896156a9)

reproduction:
pull this branch from my repo: Pull this branch from my repo: https://github.com/SanderElias/Samples/tree/Before_standalone_true_migration
```bash
npm ci 
 ng update @angular/cli --next 
 npm run build.lib  # those are needed for the samples app
 ng serve samples
```

### Please provide a link to a minimal reproduction of the bug

Pull this branch from my repo: https://github.com/SanderElias/Samples/tree/Before_standalone_true_migration

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 19.0.0-rc.0
Node: 22.7.0
Package Manager: npm 10.8.2
OS: linux x64

Angular: 19.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0-rc.0
@angular-devkit/build-angular   19.0.0-rc.0
@angular-devkit/core            19.0.0-rc.0
@angular-devkit/schematics      19.0.0-rc.0
@schematics/angular             19.0.0-rc.0
ng-packagr                      19.0.0-next.3
rxjs                            7.8.1
typescript                      5.6.2

**Comment by alan-agius4** [comment]
@SanderElias, I attempted to run the reproduction but encountered several challenges.

1. I couldn't run `ng update` due to the presence of multiple private packages.
2. There are numerous compilation errors even before the update.

**Comment by SanderElias** [comment]
@alan-agius4 

1. Ah, that is another problem; those packages are not private but part of the Deno std library. Those are installed with:
```bash
npx jsr add @std/toml
npx jsr add @std/front-matter 
```
But yes, I must remove those before I can run `ng update`.  Then afterward, I need to add them back because I use those.
As `npm i` has no issue with those packages, I'm unsure why `ng update` breaks on those. 

2. Sorry. I think I forgot to put in the `npm run build.lib` command to build the libs needed by the app.  I'll update the issue to to add those.

**Comment by alan-agius4** [comment]
Thanks, managed to replicate the problem and it appears that the `✘ [ERROR] No matching export in "src/main.server.ts" for import "default" error was an artifact of the other error which was solved via https://github.com/angular/angular-cli/pull/28767
