### ISSUE TITLE
REQUEST, RESPONSE_INIT deps not resolved in RenderMode.Server

### ISSUE THREAD

**Issue by leo6104** [angular/angular-cli#28798]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When i inject REQUEST / RESPONSE_INIT token in app.config.server.ts, it raise R3InjectorError. 

https://github.com/leo6104/ssr-token-issue/blob/master/src/app/app.config.server.ts 

```
const serverConfig: ApplicationConfig = {
  providers: [
    provideServerRendering(),
    provideServerRoutesConfig(serverRoutes),
    {
      provide: TOKEN_IN_SSR,
      useFactory: (req: Request, res: ResponseInit) => {
        return req.headers.get('host');
      },
      deps: [REQUEST, RESPONSE_INIT]
    }
  ]
};
```

https://github.com/angular/angular-cli/blob/127811203ac73803c53f7412c0b0880c004f455f/packages/angular/ssr/src/app.ts#L292C9-L309C31 

According to this code, as i expected, it should be available to use REQUEST / RESPONSE_INIT token in server side render. 

### Minimal Reproduction

```
git clone https://github.com/leo6104/ssr-token-issue 
ng serve 

// visit localhost:4200 
```

### Exception or Error

```
ERROR Error [NullInjectorError]: R3InjectorError(Environment Injector)[InjectionToken TOKEN_IN_SSR -> InjectionToken REQUEST -> InjectionToken REQUEST]: 
  NullInjectorError: No provider for InjectionToken REQUEST!
```

### Your Environment

Angular CLI: 19.0.0-rc.0
Node: 23.1.0 (Unsupported)
Package Manager: npm 10.9.0
OS: darwin x64

Angular: 19.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0-rc.0
@angular-devkit/build-angular   19.0.0-rc.0
@angular-devkit/core            19.0.0-rc.0
@angular-devkit/schematics      19.0.0-rc.0
@schematics/angular             19.0.0-rc.0
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0

**Comment by alan-agius4** [comment]
This is working as intended.

These tokens are optional and can be null for various reasons. When the routing manifest is built, the application is initialized without a request context. This can also happen during development runtime when the manifest is generated, during prerendering, or when the application is rendered on the client side.

**Comment by leo6104** [comment]
@alan-agius4 Thanks for reply.

But i put `TOKEN_IN_SSR` into `main.server.ts` `bootstrap` only. (Not `main.ts`) and load TOKEN_IN_SSR as optional in `AppComponent`. 

```
  test = inject(TOKEN_IN_SSR, { optional: true });
```

Why server-side providers run on client-side / prerendering ? Is it intended behavior?

**Comment by alan-agius4** [comment]
> Why server-side providers injected to client-side / prerendering code? in perspective of developer side, i expect that its TOKEN_IN_SSR should be null. Is it intended behavior?

I am not following by what you mean.

**Comment by leo6104** [comment]
@alan-agius4 I apologize for my limited English skills.

I'm trying to migrate an Angular 18 project to the latest code patterns. Previously, I only considered 'server-side rendering' and 'browser-side rendering'. Now, as you mentioned, it seems I need to consider the runtime environment for building the routing manifest and prerendering. (In this case, there's no window object and no request context, is that correct?)

If I enable `prerender` option in angular.json, I understand this process is needed. But why is the manifest build process needed at the first server-side render timing even when `prerender` option is disabled in angular.json?

Can you provide more information about the router manifest and prerendering in the angular.dev guide? Some developers who handle APP_BASE_HREF and platform-level InjectionTokens based on the window/request object need to adapt to a new approach.
