### ISSUE TITLE
Disable build warnings for third-party scripts and styles

### ISSUE THREAD

**Issue by HazzMan2409** [angular/angular-cli#28806]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am updating our build from webpack to esbuild. I am being bombarded with warnings for css and javascript in third-party styles and scripts. Is patching the scripts the only way I can remove the warnings from the build?

It looks like from:
* https://github.com/angular/angular-cli/issues/26140#issuecomment-1803975935
* https://github.com/angular/angular-cli/issues/27663#issuecomment-2121259019

that it is the case but I wanted to double check. If so, it isn't documented. If not, I'll convert to a feature request.

### Minimal Reproduction

Pull in [dijit@1.17.2](https://www.npmjs.com/package/dijit)'s css from (./node_modules/dijit/themes/dijit.css).

Pull in [gojs@3.0.13](https://www.npmjs.com/package/gojs)

Or any other example of third-parties generating build warnings.

### Your Environment

Angular CLI: 18.2.11
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 18.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.11
@angular-devkit/build-angular   18.2.11
@angular-devkit/core            18.2.11
@angular-devkit/schematics      18.2.11
@angular/cli                    18.2.11
@schematics/angular             18.2.11
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by alan-agius4** [comment]
At the moment there is no way to turn this warnings off.

This issue is already being tracked in one that you provided.

https://github.com/angular/angular-cli/issues/26140
