### ISSUE TITLE
Unable to use parseTemplate from @angular/compiler in a custom schematic

### ISSUE THREAD

**Issue by XavierDupessey** [angular/angular-cli#28810]
### Command

other

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello,

I'm trying to write a custom migration schematic that updates component templates. To accomplish this, I intended to use the `parseTemplate` function from `@angular/compiler`, as it seems ideal for accessing and manipulating the AST.

However, I'm encountering runtime errors when attempting to use this function (see Minimal Reproduction).

Is this function suitable for my needs, or would you recommend a different approach?

Thank you!

### Minimal Reproduction

**Attempt 1**: using `"module": "commonjs"` in `tsconfig.json`
 1. Add `@angular/compiler": "^18.0.0"` in the schematic project
 2. Add import `{ parseTemplate } from '@angular/compiler';` in the schematic
 3. Run the schematic

Error:
```
An unhandled exception occurred: require() of ES Module [...]\node_modules\@angular\compiler\fesm2022\compiler.mjs not supported.
Instead change the require of [...]\node_modules\@angular\compiler\fesm2022\compiler.mjs to a dynamic import() which is available in all CommonJS modules.
```

-----------------

**Attempt 2**: using `"module": "ES2022"` in `tsconfig.json` + `"type": "module"` in `package.json`
Same reproduction steps

Error:
```
An unhandled exception occurred: Cannot use import statement outside a module
```

### Your Environment

Angular 18

**Comment by JeanMeche** [comment]
Hi Xavier ! 

The framework packages are shipped as ESM but the schematics only support commonjs at the moment. 
We have a related issue on this: 
* #22786

**Comment by XavierDupessey** [comment]
Hey :)
Thanks for the quick reply.
Do you happen to know any workaround or is it simply not possible at all for now?

**Comment by alan-agius4** [comment]
There is a workaround mentioned in the above listed issue.
