### ISSUE TITLE
ng serve dies quietly windows

### ISSUE THREAD

**Issue by damiandennis** [angular/angular-cli#28815]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17

### Description

ng serve running on a windows client seems to die quietly for all new projects. existing projects that I have upgraded etc seem to still be ok.

### Minimal Reproduction

npm install -g @angular/cli
ng new project
cd project
ng serve

pauses then dies without any indication of anything going wrong, even using --verbose nothing happens.

### Exception or Error

no

### Your Environment

os:   Microsoft Windows 10 Enterprise
node: 20.15.0
ng:   18.2.11

**Comment by dgp1130** [comment]
I tried to reproduce this on my Windows machine, but wasn't able to. `ng serve` works just fine. I recommend updating Node and checking your system to look for any configuration issues. Unfortunately I'm not sure there's much we can do without being able to reproduce.
