### ISSUE TITLE
What happened to javascript proxy configuration?

### ISSUE THREAD

**Issue by HazzMan2409** [angular/angular-cli#28821]
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

It looks like the proxy configuration being written in javascript is no longer supported. It looks like it was just silently excluded from the docs and there was no warnings.

I want to have a bit of logic in my proxy config, only supporting json makes this quite limiting.

### Minimal Reproduction

n/a

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 18.2.11
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 18.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.11
@angular-devkit/build-angular   18.2.11
@angular-devkit/core            18.2.11
@angular-devkit/schematics      18.2.11
@angular/cli                    18.2.11
@schematics/angular             18.2.11
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by alan-agius4** [comment]
Proxy configurations written in JS are still supported.

**Comment by HazzMan2409** [comment]
Hmm, I couldn't get a .js file to work. Will try again on Monday and close this if it works.

**Comment by HazzMan2409** [comment]
But yeah, the .js example was removed in the docs

**Comment by HazzMan2409** [comment]
My bad, it is working. Closing.
