### ISSUE TITLE
Proxied Server Takes Priority Over Built Assets

### ISSUE THREAD

**Issue by HazzMan2409** [angular/angular-cli#28822]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

With the webpack dev server and a proxy configuration that looks something like:

```
{
  "/": {
    "target": "http://localhost:8081"
  }
}
```

the server would serve built assets (index.html, main.js etc.) instead of proxying the request. 

With the vite dev server, it doesn't serve the assets but proxies the request.

I need to proxy at the root level, this is no longer possible using the vite dev server.

### Minimal Reproduction

n/a

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 18.2.7
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 18.2.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.7
@angular-devkit/build-angular   18.2.7
@angular-devkit/core            18.2.7
@angular-devkit/schematics      18.2.7
@schematics/angular             18.2.7
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by alan-agius4** [comment]
You need to use configure the `bypass` property

https://github.com/vitejs/vite/discussions/5518

**Comment by HazzMan2409** [comment]
Using bypass will mean I will have to have an allowlist of all the my assets which I would rather avoid if possible.
