### ISSUE TITLE
F5 to debug Angular 18 isn't working.  CTRL-F5 works but not F5

### ISSUE THREAD

**Issue by GearTheWorld** [angular/angular-cli#28847]
### Command

serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

In Visual Studio Code 1.95.2 when building with the new system, if we do F5 to debug the app, the browser spins indefinitely.  If I revert back to the previous build system, it works just fine.

Tried the latest version of Chrome and Edge, same result.

For reference:
https://stackoverflow.com/questions/79179095/angular-18-vs-code-1-95-2-after-ng-serve-hitting-f5-starts-the-browser-and-sp

### Minimal Reproduction

I tried the following to make sure it wasn't my project

npx @angular/cli@latest new ReproProject

### Exception or Error

```text
No error in dev tools console, nothing in Network tab as well, the browser just spins indefinitely.
```

### Your Environment

```text
PS C:\Dev\MyDev> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 18.2.11
Node: 18.20.4
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 18.2.11
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1802.11
@angular-devkit/build-angular      18.2.11
@angular-devkit/core               18.2.11
@angular-devkit/schematics         18.2.11
@angular/cdk                       18.2.12
@angular/google-maps               18.2.12
@angular/material                  18.2.12
@angular/material-moment-adapter   18.2.12
@schematics/angular                18.2.11
rxjs                               7.8.1
typescript                         5.4.5
zone.js                            0.14.10
```

### Anything else relevant?

Probably not specific but here are the browsers I tried

Chrome Version 130.0.6723.117 (Official Build) (64-bit)
Microsoft Edge Version 130.0.2849.80 (Official build) (64-bit)

**Comment by GearTheWorld** [comment]
I tried

![Image](https://github.com/user-attachments/assets/f188f278-98b1-492c-b335-e8adf396c2e4)

Also in Visual Studio Code DEBUG CONSOLE, I see this and I don't know if it's related

Could not read source map for chrome-error://chromewebdata/: Unexpected 503 response from chrome-error://chromewebdata/edge-elixir-neterror.rollup.js.map: Unsupported protocol "chrome-error:"

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by GearTheWorld** [comment]
I created a repro with ng new repro and tested and the behavior is the same.  Are you saying that if you do it as well that you can't reproduce it ?

**Comment by alan-agius4** [comment]
> I created a repro with ng new repro and tested and the behavior is the same. Are you saying that if you do it as well that you can't reproduce it ?

That is correct

**Comment by GearTheWorld** [comment]
Do you have any clues as to why the previous build system works but not the new one ?

**Comment by alan-agius4** [comment]
I'm not sure, as a lot has changed since version 17, both in Angular and the underlying tools like Vite and esbuild. Additionally, no one else has reported this issue.

**Comment by GearTheWorld** [comment]
Where should I write my issue so other people can help me figure out what is going on ?  Here it seems it wasn't the right place
