### ISSUE TITLE
3rdpartylicenses.txt is being created in the wrong folder

### ISSUE THREAD

**Issue by davidgeary** [angular/angular-cli#28852]
The CLI build process creates the file _3rdpartylicenses.txt_ when the configuration is set to 'production' or includes `"extractLicenses": true`.

Prior to the new build system, _3rdpartylicenses.txt_ was saved to the root of the build output, typically _.\dist\my-project_.  This allowed it to be included by default in any distribution.

With the introduction of the new build system, the build process now saves the compiled output to _.\dist\my-project\browser_, but _3rdpartylicenses.txt_ is still being saved to _.\dist\my-project_, meaning that it is no longer included with the project output.  If it needs to be distributed as part of the application, it now needs an additional build step to copy it into the _browser_ subfolder.

**Expected behavior**
Under the new build system, _3rdpartylicenses.txt_ should be saved to the root of the same folder as the compiled output.

### Steps to reproduce

``` sh
ng new extract-licenses --style=css --skip-git=true
cd extract-licenses
ng build --configuration=production
dir .\dist\extract-licenses
```

This should display _3rdpartylicenses.txt_ and the _browser_ folder.  (Listing the contents of the _browser_ folder will list the application files.)

Output from `ng version`:

```
Angular CLI: 18.2.11
Node: 20.14.0
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 18.2.11
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.11
@angular-devkit/build-angular   18.2.11
@angular-devkit/core            18.2.11
@angular-devkit/schematics      18.2.11
@schematics/angular             18.2.11
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by alan-agius4** [comment]
This is working as intended, this file is not meant
to be servable. 

What is the use case of needed this to be servable?

**Comment by davidgeary** [comment]
I don't necessarily need it to be servable, I just want it to be included in the application's files for 
distribution.

_[That said, it's entirely possible that an application may wish to include/display the contents of 3rdpartylicenses.txt alongside its own licence somewhere.  But being able to display or serve the file directly is not the issue here; just the ability to have it included in the output folder.]_

A number of licences include a provision requiring copyright notices, etc, to be included in the final software product; for example, the MIT licence states:

> "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

This may often be ignored when building server-hosted web apps (because the developer manages all copies of the final application), but when Angular is used to build, say, mobile apps, e.g. using Ionic, the software is being distributed to each end user.  In these circumstances, the developer is required to provide a copy of the licence(s) as part of the application and AIUI, including _3rdpartylicenses.txt_ with the compiled output would satisfy that requirement.

**Comment by dgp1130** [comment]
The `browser/` directory is intended to be the one which is served to end users, any many developers might not want or need to serve 3rd party licenses, so we feel it makes the most sense outside of that directory. `dist/my-project/` is the real "root" of the output build, which is the thing I would recommend passing to your deployment infra. Ionic or any other deployment infrastructure can still find `3rdpartylicenses.txt` in that outer directory and use it in their deployments.

**Comment by davidgeary** [comment]
> The browser/ directory is intended to be the one which is served to end users, any many developers might not want or need to serve 3rd party licenses, so we feel it makes the most sense outside of that directory.

And yet, prior to the introduction of the new build system, it was presumably thought to make most sense to be *inside* the project directory, as _3rdpartylicenses.txt_ was previously output to the same folder as the project.  So any developers not wanting to include it would have had to explicitly exclude from their distribution. 🤷‍♀️
