### ISSUE TITLE
ng build odd behavior - reflection_capabilities.js:80 Uncaught TypeError: Cannot read property 'annotations' of undefined(…)

### ISSUE THREAD

**Issue by AltekkeE** [angular/angular-cli#2886]
### OS?

>  Mac OSX  El Capitan
### Versions.

angular-cli: 1.0.0-beta.18
node: 4.4.5
os: darwin x64

this did not happen in beta.16
### Repro steps.

After executing ng build the following error is seen in the browser console.

> Uncaught TypeError: Cannot read property 'annotations' of undefined(…) reflection_capabilities.js:80

The fix is to run ng build -w -o dist/ and then make a minor change to the module file and save and revert it back like ..... retype "BrowserModule". the build will run again and then work.

`@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        routing,
        HttpModule,
        SharedModule,
        SimpleNotificationsModule
    ],
    declarations: [
        AppComponent,
        DashboardComponent,
        NavigationComponent,
        HeaderComponent,
        AdminNavigationComponent,
        OtherNavigationComponent,
        LoginComponent
    ],
    providers: [
        ApplicationRouteGuardService,
        AppStatusGuardService,
        NavigationService,
        { provide: XSRFStrategy, useClass: CustomXSRFStrategy },
        { provide: XHRBackend, useClass: AuthenticationConnectionBackend },
        { provide: RequestOptions, useClass: RequestOptions},
        NotificationsService,
        LoginService
    ],
    exports: [SharedModule],
    bootstrap: [
        AppComponent,
    ],
})
export class AppModule { }`
### The log given by the failure.

No errors from CLI

**Comment by filipesilva** [comment]
Can you give me reproduction steps so that I can see this error?

**Comment by AltekkeE** [comment]
I just added you to a repository. Please use this to reproduce the problem. 

I just tried beta.19-3 and the problem still occurs
ng-serve does not produce the problem

Steps:
npm install
ng build
deploy the dist contents to an apache-tomcat 7.0 server (webapps/ums/)

Thanks for looking into this

**Comment by filipesilva** [comment]
@AltekkeE you're project already has a fair number of changes in it. I'm sorry but I don't have to time to try and distil the bug from your project as is. If you can get a simple repro that doesn't need a specific server I can try to repro locally.

**Comment by AltekkeE** [comment]
It might not need to be run in tomcat. That is just what we are using
currently.  I will check it out on others

**Comment by AltekkeE** [comment]
@filipesilva I reduced the app and only left in my code that is causing the problem.

in main.ts I am creating an exported variable and importing that into a customXSRF strategy.

Reproduction steps:
1. npm install
2. ng build
3. open dist/index.html from the filesystem in chrome
![screen shot 2016-11-07 at 9 37 26 am](https://cloud.githubusercontent.com/assets/11259864/20061458/e991ddba-a4cd-11e6-86cb-993a198a1a74.png)

**Comment by filipesilva** [comment]
@AltekkeE can you put up the simple repo in a github I can access? I don't have access to the other one anymore.

**Comment by AltekkeE** [comment]
@filipesilva  it is now public [repo](https://github.com/AltekkeE/angular-cli-issue-2886)

**Comment by AltekkeE** [comment]
@filipesilva  I also just checked in the main.bundle.js two times so that you can see the diff
the first has the working main.bundle.js 
the second has the bad main.bundle.js

**Comment by kraihn** [comment]
I was having the same issue and fixed it by changing my AppModule import to
be the full path, and bypass the index.ts file.

```
import { AppModule } from './app/'; // old
import { AppModule } from './app/app.module'; // new
```

**Comment by filipesilva** [comment]
Closing as obsolete.
