### ISSUE TITLE
Unnecessary rebuild when using an external plugin

### ISSUE THREAD

**Issue by HazzMan2409** [angular/angular-cli#28890]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When you add an esbuild plugin to use a global that was loaded in via angular.json scripts instead of having it bundled, you get an extra rebuild when you run a build in watch mode on startup.

I've got a minimal setup in the linked repo with Leaflet. If you run `ng serve --verbose` you will see what I mean.

I've checked and running the exact same plugin with esbuild directly does not cause this extra rebuild. Note that I'm using https://www.npmjs.com/package/@angular-builders/custom-esbuild to run the esbuild plugin.

### Minimal Reproduction

https://github.com/HazzMan2409/ng-extra-rebuild

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 18.2.12
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 18.2.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.12
@angular-devkit/build-angular   18.2.12
@angular-devkit/core            18.2.12
@angular-devkit/schematics      18.2.12
@schematics/angular             18.2.12
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by dgp1130** [comment]
Angular does not support custom esbuild, so we can't provide any real guidance on what might be going on here.

**Comment by HazzMan2409** [comment]
Ok. I'll try and re-create the issue with a minimal reproduction using angular's builder api to add an esbuild plugin.
