### ISSUE TITLE
Can't set verbose for library build

### ISSUE THREAD

**Issue by aleksander351** [angular/angular-cli#28891]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

✔ Compiling with Angular sources in Ivy partial compilation mode.
✔ Writing FESM bundles
✖ Copying assets
error Command failed with exit code 1.

Can't really do anything with the upper error message, so I tried to run the build with verbose.
Can't use verbose not in the terminal and it is also not accepted in the angular.json file.

### Minimal Reproduction

as described above

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 18.2.9
Node: 23.2.0 (Unsupported)
Package Manager: yarn 1.22.21
OS: win32 x64

Angular: 18.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.11
@angular-devkit/build-angular   18.2.11
@angular-devkit/core            18.2.9
@angular-devkit/schematics      18.2.9
@schematics/angular             18.2.9
ng-packagr                      18.2.1
rxjs                            7.8.1
typescript                      5.5.4
```

**Comment by alan-agius4** [comment]
The `ng-packagr` library builder does not offer a `verbose` mode, which might have helped provide a more detailed error message. 

I tested locally, the error was displayed as expected. 

However, the `ng version` output indicates that you are using an unsupported version of Node.js. Please switch to a supported version. If the issue persists after addressing this, kindly provide a minimal reproduction for further investigation.

**Comment by aleksander351** [comment]
I managed to setup the assets folder properly so no need to follow up from my side. Didn't know the packagr doesn't have that option. Yeah, probably need to stay at node 22 for now. Merci vielmals. :)
