### ISSUE TITLE
Custom WebWorker doesn't start while using esbuild serve

### ISSUE THREAD

**Issue by Stas-tolpekin** [angular/angular-cli#28900]
### Command

serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

The application runs locally using `ng serve` command. When the Worker runs I see the following error in the console:
```text
Uncaught SyntaxError: Cannot use import statement outside a module (at worker-YG675EHQ.js?worker_file&type=classic:4:1)
```

The place in code where the error occurs:
```js
// src/app/test-worker.worker.ts
import {first, map, of} from "/@fs/D:/projects/worker-test/.angular/cache/19.0.0/worker-test/vite/deps/rxjs.js?v=ac3c3c24";
```

This is not a problem of this specific import. If I remove this import an error will occur on the next import statement (at least on imports from node_modules).

This problem is reproduced only on `ng serve` with the `development` configuration; it doesn't exist in the production build.

**Workaround** - disable Angular CLI cache by adding `"cli": { "cache": { "enabled": false} },` to `angular.json`

### Minimal Reproduction

Repo with minimal reproduction: https://github.com/Stas-tolpekin/ng-worker-problem-reproduce
The commit with adding all necessary to reproduce: https://github.com/Stas-tolpekin/ng-worker-problem-reproduce/commit/441a9dd85d9184493ff99f20addabbbbbc27950e

1. run the application with `ng serve`
2. Open in browser
3. Inspect SharedWorker "test-worker" in the browser (`chrome://inspect/#workers` in Chrome)
4. In console there will be an error. The worker is not working.

### Exception or Error

```text
Uncaught SyntaxError: Cannot use import statement outside a module
```

### Your Environment

```text
Angular CLI: 19.0.0
Node: 20.18.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 19.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0
@angular-devkit/build-angular   19.0.0
@angular-devkit/core            19.0.0
@angular-devkit/schematics      19.0.0
@schematics/angular             19.0.0
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by sedghi** [comment]
I'm experiencing a similar issue. I'm using an app in my Angular project that includes a web worker, but the worker is part of the library I depend on, not within my Angular project.

I'm seeing a 404 Not Found 

![Image](https://github.com/user-attachments/assets/5a8df682-57e2-465d-9f5d-97ad4146e097)

I'm taking a long shot here, but do you have any comments that might help me?

P.S. The worker is generated using `type: 'module'`, and interestingly, it works in all our other Vite setups if we exclude it from `optimizeDeps`. However, even with `"cli": { "cache": { "enabled": false } }`, Angular doesn't accept it.
