### ISSUE TITLE
Module not found: Error: Can't resolve 'webpack-dev-server' ...  on 1.0.0-beta.18

### ISSUE THREAD

**Issue by mmilkov** [angular/angular-cli#2891]
### OS?
> Linux CentOS

### Versions.
> angular-cli: 1.0.0-beta.18
> node: 6.9.1
> os: linux x64

Hello guys. :)
    I tried to update my angular-cli from beta.17 to beta.18. I uninstalled the angular-cli.. Cleaned the npm cache and installed angular-cli@latest.. I created a new project with ng new ProjectName, but when I tried to ng serve I got:

```
ERROR in multi main
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://IP:4200/' in '/home/user/.nvm/versions/node/v6.9.1/lib/node_modules/angular-cli/models'
 @ multi main

```

Anyone?
Thanks :)))

**Comment by lucky-lou** [comment]
Same here

**Comment by alexlacasa86** [comment]
Using _angular-cli@latest_ will install you a weird beta called _mobile.whatever_ instaead of beta.18. You should specify beta.18 when installing.

**Comment by mmilkov** [comment]
@alexlacasa86 
Same error, 'npm i -g angular-cli@1.0.0-beta.18' with node v7.0.0 on ng serve

**Comment by knobo** [comment]
What if you run "npm install" in your project directory?

**Comment by alexlacasa86** [comment]
I have _angular-cli_ installed both globally and locally in the _package.json_. Make sure both of them are the same version. I am currently working with _beta18_ with no issues.

**Comment by mmilkov** [comment]
@knobo Already tried this. Thank you.
@alexlacasa86 I am uninstalling the node version with 'nvm uninstall vX'.. That remove all packages... I cleaned the cache and I maked a new installation. I am trying to generate new project and still getting this error when I try to serve the application. The version of the project is beta.18

LOL installing angular-cli locally fixed the issue. Thank you guys

**Comment by Chris2011** [comment]
I installed angular-cli locally and did a npm install, still the same problem after run "ng serve".

**Comment by Chris2011** [comment]
Possible to reopen the issue?

**Comment by mmilkov** [comment]
What I did was Installing typescript globally, angular-cli@1.0.0-beta.18 globally, ng new AppName. npm i angular-cli@1.0.0-beta.18 --save

**Comment by Chris2011** [comment]
I updated to the latest 6.* version, deleted node_modules folder and did a npm install again, after this it worked.

**Comment by youssefgh** [comment]
updating to the latest versions of node/npm worked for me too ! thanks

**Comment by yahyaKacem** [comment]
this is really frustrating I'm still having this problem,
```
$ ng version
  angular-cli: 1.0.0-beta.19-3
  node: 7.0.0
  os: linux x64
$ npm -v
  npm: 3.10.9
```
I did everything here, I started a new project I got this error from the start!
I deleted node_modules and run `npm install` again same error!!
is there a solution for this?

**Comment by mmilkov** [comment]
Hello @yahyaKacem.

If you are using nvm, try to uninstall your node version and install the latest node again. Run 'npm cache clear' and update your npm - 'npm update npm -g' 

Try to install angular-cli again. If this not works on beta.19-3, try to install beta.18 before other releases :)) 

Regards

**Comment by yahyaKacem** [comment]
@mmilkov I did in a new project root directory:
```
$ nvm uninstall v7.0.0
$ nvm clear-cache
$ nvm install v7.0.0
$ npm cache clean
$ npm install angular-cli -g
$ npm update npm -g
$ rm node_modules -r
$ npm install
$ ng serve
```
after that npm version became 4.0.1.
but still the same error, then I installed the beta.18 and had the same error.
I also tried with node 6.9.1 and 6.9.0, the same result.
I even tried making a new project after installing the beta.18 but still the same error.
it may be worth mentioning that I get errors during the install of angular-cli:
> node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.1 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp)

then it complain about 2 missing packages reflect-metadata and portfinder after I install those globaly and locally it work but with the same error:
> ERROR in multi main
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localhost:4200/' in 'project/folder/node_modules/angular-cli/models'
 @ multi main

but as you can see it complains about the local angular-cli not the global one `'project/folder/node_modules/angular-cli/models'`

**Comment by yahyaKacem** [comment]
My problem was that I have set npm to install the packages in a legacy bundling way by adding this line to `/home/user/.npmrc` file: `legacy-bundling=true`, removing that file and reinstalling everything solved my problem.

**Comment by Alayode** [comment]
Running on OSX El Capitan

Updated to the Beta.18 locally and globally made sure to do 

`npm uninstall angular-cli`
`npm uninstall angular-cli` -g
`npm cache clean`

make sure it is removed by testing the `ng serve`
remove the node_modules globally if the angular-cli folder is anywhere outside the project
my build is running fine

**Comment by JoseTapiaG** [comment]
I had to install the modules:

webpack-dev-server
ansi-regex
debug
inherits
json3
ms
querystringify
requires-port
sockjs-client
strip-ansi
url-parse

**Comment by matthiasdv** [comment]
I resolved this issue by installing the dev-dependencies. 

`ng init`
`npm i`
`npm i --only=dev` --> somehow _npm i_ does not suffice to install dev dependencies
`ng serve`

**Comment by chrisdemetriad** [comment]
Installing angular-cli locally worked for me.

`npm install angular-cli --save-dev`

**Comment by vanilla-thunder** [comment]
angular cli 1.0.0-rc.2 with latest node + npm on Ubuntu 16.04.2 LTS
this stuff is broken again and earlier fixes do not work anymore.

make angular-cli great again!

**Comment by radiocity** [comment]
`webpack-dev-server --no-inline`

**Comment by kksrini89** [comment]
I just deleted node_modules folder then do "npm install" it worked!

**Comment by iSanchezDev** [comment]
Solved!

Installing right version of angular cli worked!

Angular packages are 4.4.3,
Angular-Cli updated to 1.0.0-beta.28.3
