### ISSUE TITLE
ng g module module-name TypeError

### ISSUE THREAD

**Issue by blackat** [angular/angular-cli#2893]
> ## Please provide us with the following information:
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
> Mac OSX Sierra
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
> 
> ``` bash
> angular-cli: 1.0.0-beta.11-webpack.8
> node: 6.6.0
> os: darwin x64
> ```
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
> No, the app has been freshly created from scratch with CLI, just tried to add a new module.
### The log given by the failure.

> Normally this include a stack trace and some more information.
> 
> ``` bash
> blackat:ng-navbar eugenio$ ng g module navbar
> Could not start watchman; falling back to NodeWatcher for file system events.
> Visit http://ember-cli.com/user-guide/#watchman for more info.
> installing module
>   create src/app/navbar/navbar.module.ts
> installing component
>   create src/app/navbar/navbar.component.css
>   create src/app/navbar/navbar.component.html
>   create src/app/navbar/navbar.component.spec.ts
>   create src/app/navbar/navbar.component.ts
> astUtils.addComponentToModule is not a function
> TypeError: astUtils.addComponentToModule is not a function
>     at Class.afterInstall (/Users/eugenio/Projects/Github/ng-navbar/node_modules/angular-cli/addon/ng2/blueprints/component/index.js:125:18)
>     at tryCatch (/Users/eugenio/Projects/Github/ng-navbar/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
>     at invokeCallback (/Users/eugenio/Projects/Github/ng-navbar/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
>     at publish (/Users/eugenio/Projects/Github/ng-navbar/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
>     at flush (/Users/eugenio/Projects/Github/ng-navbar/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> ```

Thanks a lot for your help 😉

**Comment by filipesilva** [comment]
@Brocco can you have a look?

**Comment by Brocco** [comment]
Component generation for modules had been fixed. And apparently the current approach will be to generate the two entities separately making this a non-issue. Thank you for taking time to submit the issue.
