### ISSUE TITLE
Github pages deploy problem with path

### ISSUE THREAD

**Issue by kodiua** [angular/angular-cli#2894]
In my project I put angular into subfolder and after github pages deploy
I have got wrong urls in the released application.
https://github.com/kodiua/ng-europe-hackaton
https://kodiua.github.io/ng-europe-hackaton/ng-app/

**Comment by ochervak** [comment]
Same here

**Comment by filipesilva** [comment]
Heya, I think you can fix this with the `--base-href` flag. Can you try `ng github-pages:deploy --base-href="ng-europe-hackaton/ng-app/"`?

**Comment by filipesilva** [comment]
Closing as inactive.
