### ISSUE TITLE
Styles from components (.scss) are not included in the styles production bundle .css

### ISSUE THREAD

**Issue by razor09** [angular/angular-cli#28951]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Styles from components (`.scss` in my case) are not included in the styles production bundle `.css`. Instead, they go to `.js` bundle. Only the global styles specified in the `build.options.styles` in `angular.json` settings are included in the final `.css` bundle.

### Minimal Reproduction

ng new my-project

write some styles in `app.component.scss` and `app.component.html`

npm run buld

styles-[hash].css - 0 bytes

styles go in `.js` bundle instead of `.css`

### Exception or Error

```text

```

### Your Environment

```text
node.js version: 22.11.0
npm version: 10.9.0
angular version: 19.0.0
angular-cli version: 19.0.1
```

**Comment by JeanMeche** [comment]
This works as designed.
