### ISSUE TITLE
Uncaught (in promise) Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:4200/src/main.ts(…)

### ISSUE THREAD

**Issue by Sri276286** [angular/angular-cli#2896]
Hi,

I am using angular-cli project structure 

I want to use systemjs with angular-cli.

I included the following in index.html file 

 <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.40/system.src.js"></script>
  <script>
  System.import('../src/main.ts');
</script>

I have main.ts file present under src . But still,it's throwing error like

![image](https://cloud.githubusercontent.com/assets/19607054/19722855/375e2ef4-9b96-11e6-9962-c0ab79ea2d2e.png)

Please let me know what wriong I am doing.

**Comment by deebloo** [comment]
@Sri276286 I would avoid using SystemJs as well as Webpack (which is used by the cli under the hood). Also you are just pointing to a typescript file which can't be loaded into the browser without being compiled.

**Comment by filipesilva** [comment]
We don't support using SystemJS anymore, since we have moved to webpack.
