### ISSUE TITLE
*ngFor Unknown Template Directive Event

### ISSUE THREAD

**Issue by endnagy** [angular/angular-cli#2898]
> ## Please provide us with the following information:
### OS?

> Windows 7 64 Bit
> Eclipse Neon
> Angular2 Eclipse Plugin
### Versions.

 angular-cli: 1.0.0-beta.18
node: 6.9.1
os: win32 x64
### Repro steps.

Created Angular 2 Eclipse project in Eclipse Neon
Followed instruction of an online Angular2 Tutorial
All non-HTML artifacts (eg service and component typescript) are OK
Any non-standard Angular2 specific HTML elements (tags)  are not recognised
example *ngFor in HTML indicates error  "Unknown Template Directive Event" in Eclipse editor
### The log given by the failure.

> Normally this include a stack trace and some more information.
### Mention any other details that might be useful.

Ive followed the instruction at angular-cli/readme.md carefully
The angular 2 tutorial Im following does not provide any particular include or import for the HTML
The Eclipse project is a "standard" project,
The project was created using 
ng new <proectname>
In Eclipse Ive tried conversion to a AngularJS and Javascript eclipse project but without luck

Endre

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
can you post your app module?

**Comment by endnagy** [comment]
Hi deebloo

Ive provided you with a zip 

I will post the relevant component and its resolution for readers of the thread 8^)

E

**Comment by filipesilva** [comment]
@endnagy you'll have to report this on the Angular2 Eclipse Plugin bug tracker.

**Comment by nazareornelo** [comment]
Any solution

**Comment by nazareornelo** [comment]
I am using Eclipse.

<tr *ngFor = "let item of list">
