### ISSUE TITLE
bug(*): Issue with `ng add @angular/material` in Angular CLI

### ISSUE THREAD

**Issue by samir-dahal** [angular/angular-cli#28985]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.3.5

### Description

Dear Angular Team,

I encountered an issue while using the Angular CLI to integrate `@angular/material` into a new project. Here are the steps I followed and the problem I observed:

1. **Environment**:
   - Angular project created using the Angular CLI.
   - Angular CLI version: [18.2.12].
   - Node.js version: [22.11.0].

2. **Issue**:
   - I ran the command `ng add @angular/material` in the terminal.
   - The installation was marked as successful, but the necessary project files (e.g., `angular.json`, `app.config.ts, styles.css`, etc) were not modified.
   - Additionally, the following error was displayed:
     ```
     Cannot find module '\node_modules\@angular\cli\node_modules\@schematics\angular\private\components.js'
     ```
I also checked the node_modules folder but didn't find any folder named "private"

### Reproduction

StackBlitz link: Sorry, I am working on my local machine, so cannot provide the link here.
Steps to reproduce:
1. Create a new project using angular CLI
2. Add the @angular/material using `ng add @angular/material`

### Expected Behavior

Should properly install the @angular/material package.

### Actual Behavior

Error after installing the package.
```
     Cannot find module '\node_modules\@angular\cli\node_modules\@schematics\angular\private\components.js'
```

### Environment

- Angular: 18.2.12
- CDK/Material: 19.0.0
- Browser(s): Microsoft Edge 131.0.2903.63 (Official build) (64-bit) 
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by alan-agius4** [comment]
The problem appears that you have an outdated version of `@angular/material` installed.

**Comment by json-derulo** [comment]
@alan-agius4 I think you misunderstood the issue. When creating a fresh Angular 18 non-standalone workspace **without Material**, after running `ng add @angular/material` the wrong version of Angular Material is chosen, which probably leads to the described issue.

**Comment by alan-agius4** [comment]
Sorry I misunderstood the issue.

**Comment by deerbuster** [comment]
this was not fixed.  I have the issue today.  I force cleared my NPM cache, and create a fresh angular 18.2.12 app, ng add @angular/material, and it chose material v17 again. "found compatible package version: @angular/material@17.0.0"

**Comment by JeanMeche** [comment]
@deerbuster The fixed was merged (for v19) but wasn't released yet. Also you have a workaround mentionned in Alan last message.

**Comment by YasminHernandes** [comment]
Hi guys, I had the same problem with a new **Angular 18** project. I installed Angular Material using:

```
ng add @angular/material
```

and it gave me the same error message: 
```
Cannot find module '\node_modules\@angular\cli\node_modules\@schematics\angular\private\components.js'. 
```

Without updating anything other than package.json.

I just removed the `@angular/material` and `@angular/cdk` dependencies from the `package.json` and made a new installation declaring the desired version:
```
ng add @angular/material@18
```

I tested it and it worked perfectly!

**Comment by Hi-AY** [comment]
Hello, I was getting this same issue. 

As said above, I removed `@angular/material` and `@angular/cdk` dependencies from the `package.json` and made a new installation declaring the desired version, 

Now I am getting this,

`Cannot read properties of null (reading 'endTag')`

Any idea about this?

**Comment by YasminHernandes** [comment]
Check your code for duplicate or missing end tags.
https://stackoverflow.com/questions/62203754/ng-add-angular-material-fails-with-cannot-read-property-endtag-of-null

**Comment by Hi-AY** [comment]
It was resolved. Thank you @YasminHernandes !!
