### ISSUE TITLE
Angular CLI is hiding files from system but codebase is running

### ISSUE THREAD

**Issue by saikatmahapatra** [angular/angular-cli#28988]
### Command

generate

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

While I was creating a new module with routing, noticed that existing modules are vanished from file explorer and VS code also. Initially I thought it was deleted but git status is showing that its up-to-date. For my own interest I checked if application is running or not and found working perfectly even if the modules are not seen from system. I faced this issue before and I had to re-clone the project into a new workspace. 

### Minimal Reproduction

> ng  g m modules/abc --routing --flat

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 15.2.11
Node: 18.18.0
Package Manager: npm 10.2.0
OS: win32 x64

Angular: 15.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.11
@angular-devkit/build-angular   15.2.11
@angular-devkit/core            15.2.11
@angular-devkit/schematics      15.2.11
@angular/cdk                    12.2.13
@angular/cli                    15.2.11
@schematics/angular             11.2.19
rxjs                            6.5.5
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
Angular 15 is no longer under support. The actively supported versions are Angular 17, 18, and 19.  

For additional details, visit [[Angular's release reference](https://angular.dev/reference/releases#actively-supported-versions)](https://angular.dev/reference/releases#actively-supported-versions).
