### ISSUE TITLE
Asset bundling?

### ISSUE THREAD

**Issue by rjcoupe** [angular/angular-cli#290]
How are assets (i.e. images) handled by `ng build`? This appears not to be included (or, at least, undocumented).

**Comment by jkuri** [comment]
Hi @rjcoupe, they are copied to `dist`.

**Comment by rjcoupe** [comment]
@jkuri From where?

**Comment by jkuri** [comment]
Put them in `src/assets/` or somewhere you like it in the `src` folder.

**Comment by rjcoupe** [comment]
@jkuri Oh, I assumed they had to be placed in a specific directory. Thank you for the help!
