### ISSUE TITLE
Static build with localization

### ISSUE THREAD

**Issue by gobeli** [angular/angular-cli#29000]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Static builds do not start the express server, which is specified by the ssr entry file in the `angular.json` when using localization.

When localization is enabled the http client uses `http://ng-localhost` as the base-path instead of the server startet during the build.

How can I do http calls during build time for static site generation with localization enabled?

### Minimal Reproduction

https://github.com/gobeli/angular-repro

The Reproduction includes a simple express server, which serves an api under `/api`. This endpoint is called by the `app.component.ts` and the response used in the `app.component.html`. 

- `ng build -c development` Works as expected. The rendered HTML contains the server response.
- `ng build -c production` Does not work. The rendered HTML contains `null` .

If I disable `localization` the production build works as well.

### Exception or Error

```text

```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 19.0.2
Node: 20.17.0
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 19.0.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.2
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2
@angular-devkit/schematics      19.0.2
@angular/cli                    19.0.2
@angular/ssr                    19.0.2
@schematics/angular             19.0.2
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by alan-agius4** [comment]
This is has been addressed in the new SSR API which is currently in developer preview.


See https://angular.dev/guide/hybrid-rendering for more information.
