### ISSUE TITLE
AOT: Compilation sometimes fails on serve

### ISSUE THREAD

**Issue by SeerUK** [angular/angular-cli#2900]
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac OSX 10.11.6 (El Capitan)
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
$ ng --version
angular-cli: 1.0.0-beta.18
node: 6.9.1
os: darwin x64
```
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

The app was created with the CLI tool. I created a completely fresh, brand-new project, ran `$ ng serve --aot`, and then made a (any) change to a file. At this point, the browser reloads, and _sometimes_ the error shown below is given.
### The log given by the failure.

> Normally this include a stack trace and some more information.

Note, this doesn't happen every time. It seems like it's only sometimes, randomly. Perhaps a race condition?

```
style_sanitizer.js:95 Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/seer/git/github.com/SeerUK/angular2-cli-issue-test/src/app/app.module.ngfactory.ts'(…)(anonymous function) @ style_sanitizer.js:95__webpack_require__ @ bootstrap 03ed31e…:52(anonymous function) @ main.ts:8__webpack_require__ @ bootstrap 03ed31e…:52(anonymous function) @ zone.js:1428__webpack_require__ @ bootstrap 03ed31e…:52webpackJsonpCallback @ bootstrap 03ed31e…:23(anonymous function) @ main.bundle.js:1
client:38 [WDS] Errors while compiling.
client:80 ./src/app/app.module.ngfactory.ts
Module build failed: Error: ENOENT: no such file or directory, open '/Users/seer/git/github.com/SeerUK/angular2-cli-issue-test/src/app/app.module.ngfactory.ts'
    at Error (native)
 @ ./src/main.ts 4:0-64
 @ multi main
```
### Mention any other details that might be useful.

N/A currently.

**Comment by sime** [comment]
I have the same problem since this morning.

I believe it is something to do with the codebase? If I create a fresh project, with `ng new` I don't get the error.

**Comment by SeerUK** [comment]
It doesn't happen every time, but it definitely happened on a completely new, fresh project. The only thing I changed was "app works!" to "app doesn't work!".

To add a tiny bit more information here, I'm using a 15" mid-2014 Retina MacBook Pro (base model). I was inside of a tmux session. I use iTerm2 v3, and fish shell.

**Comment by sime** [comment]
Strange, now it is working for me without a problem.

**Comment by alexbyk** [comment]
Can confirm the same error happens when some file is changed, than goes away when I save a file a second/third time.
Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/home/foo/projects/bar/src/app/app.module.ngfactory.ts'

Very annoying bug.
