### ISSUE TITLE
HTML/ScrInject.B trojan in the sample code?

### ISSUE THREAD

**Issue by jdell64** [angular/angular-cli#2902]
I didn't see this one already posted, so sorry if it is a dupe.

I am running through the migration steps (https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14) and got to this step:

```
ng new migration-project
```

my AV software (on my mac) said there was a trojan in the examples file:

```
 /usr/local/lib/node_modules/.staging/redeyed-91a8e7f5/examples/browser/index.html
```

The trojan in question is called: `HTML/ScrInject.B`

I am skeptical to the validity of this claim, but I figured I'd pass it along for you all to check out. 

> ## Please provide us with the following information:
### OS?

> macOS Sierra 10.12.1
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

$ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.18
node: 6.3.1
os: darwin x64
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
> start a new project?

The AV software I am running is Open ESET Cyber Security ( https://www.eset.com/us/ )
### The log given by the failure.

> Normally this include a stack trace and some more information.
> N/A
### Mention any other details that might be useful.

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by philiptzou** [comment]
I have the same problem too. The `redeyed` package is all used in `react-scripts`. The anti-virus software I used is System Center 2012 on OSX El Captan. It seems it's just an example file so it won't affect anything once. But this is really annoying.

**Comment by niklas-dahl** [comment]
same here with ESET Endpoint Antivirus, it pointet me to this: http://www.virusradar.com/en/HTML_ScrInject.B/description

**Comment by filipesilva** [comment]
There isn't anything we can do specifically here, but I'll keep the issue open so the community can pitch in.

**Comment by philiptzou** [comment]
@filipesilva `redeyed` is now 1.0.1 and solved the problem. See https://github.com/thlorenz/redeyed/issues/18.

**Comment by filipesilva** [comment]
@philiptzou good to know, thanks!
