### ISSUE TITLE
Command-line environment variable declaration not working

### ISSUE THREAD

**Issue by tijsmoree** [angular/angular-cli#29039]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

The command-line environment variable declaration (`--define`) is not working for me. I did the following:

- `ng new`
- Added `declare global { var mytitle: string; }` to `app.component.ts` and changed the title to `title = globalThis.mytitle;`
- `ng build --define "mytitle='blablablabla'"`

`globalThis.mytitle` remains `undefined` and the title in the default Angular application remains empty. Also, searching the `dist` folder for `'blablablabla'` returns nothing.

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.2
Node: 20.16.0
Package Manager: npm 10.8.1
OS: linux x64

Angular: 19.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.2
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2
@angular-devkit/schematics      19.0.2
@angular/cli                    19.0.2
@schematics/angular             19.0.2
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by alan-agius4** [comment]
The blog post in this case is indeed incorrect. I have contacted @mgechev to try to get that fixed.

The documentation about `define` can be found https://angular.dev/tools/cli/build-system-migration#build-time-value-replacement-define
