### ISSUE TITLE
Iteration plan? List features to avoid "does cli support..."

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#2904]
Guys you aren't tired by:
Does cli support aot with lazy loading ?
Dies cli support rollup?
Does cli support Hot Reload Module?
Where find cli command supported?
How add 3th party remotly?
Does cli support bla bla bla...its always same on github and on gitter WOW!!! Always same question without response !

Please guys can you dedicate more time to inform people what and for when are you doing?
I don't work for microsoft but can you chek this kind or wiki
https://github.com/Microsoft/vscode/wiki/Iteration-Plans
Just click on interstion plan of each month, work is awesome !

Today I don't know how I can myself check if cli support some thing !?!? Like AoT with lazyloading
Response from you will be maybe ng help?!! Stackoverflow? It's beta!?!? Stop use cli !?!?

 Lol yes all philosophical response are expected... To fight against me :-S

Cheers

**Comment by filipesilva** [comment]
That iteration plan is quite nice, yes. But I don't think the solution for the admittedly missing information is in having an iteration plan, but rather in having better docs, which is being tracked in https://github.com/angular/angular-cli/issues/2711.

**Comment by istiti** [comment]
Yes why close this issue @filipesilva If it's quite nice... I think a FAQ or iteration plan is an important enhancement request to have ... material2 had same request and they get it on 😉
