### ISSUE TITLE
NG_HMR_TEMPLATES not working

### ISSUE THREAD

**Issue by cesco69** [angular/angular-cli#29049]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I tried the template HMR on a new project created with Angular v19.0.2. As I read some days ago into [another issue](https://github.com/angular/angular/issues/39367) related to template HMR, there was a problem that's now fixed in the v19.0.1 by [this commit](https://github.com/angular/angular/commit/d33af5cba6df0903826a9cf8c1b7a6d54d959016)... but it isn't working at all: the CLI prints a message saying _"Component update sent to client(s)."_, an event is sent in the Angular websocket but nothing happens.

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.2
Node: 20.13.1
Package Manager: pnpm 9.1.2
OS: win32 x64

Angular: 19.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.2 (cli-only)
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2 (cli-only)
@angular-devkit/schematics      19.0.2 (cli-only)
@angular/cli                    19.0.2
@schematics/angular             19.0.2 (cli-only)
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by cesco69** [comment]
Are there any updates on this?

**Comment by taylorhutchison** [comment]
This must be a Windows thing. I cannot get template HMR to work on my Windows machine, but the same code works on my Mac.

**Comment by taylorhutchison** [comment]
Seems like it is related to windows vs POSIX path separators and a fix could be coming based on this commit:
https://github.com/angular/angular-cli/commit/88759982241ec2c30e00f62691347893d36bbfac

**Comment by taylorhutchison** [comment]
@spock123 have you tried version 19.0.5 of the angular cli? It just came out a day ago and includes a fix for template HMR. I'm curious if it fixes your issue. I don't have an ARM Mac to test on.

**Comment by draylegend** [comment]
@taylorhutchison updated packages in my [repo](https://github.com/draylegend/ng19-bugs) and it works fine for html files (app.component.html). Thank you!

**Comment by zygarios** [comment]
Unfortunately, HMR for templates works only on the Bash terminal but not on PowerShell, which I use daily. Does anyone know what might be the issue?

![Image](https://github.com/user-attachments/assets/4f87512a-9829-4dc0-8a7b-8a967c99754e)

**Comment by zygarios** [comment]
I need to add something off-topic. HMR for styles and templates is something I've been waiting for a long time, and I have to admit it works brilliantly. For me, it's definitely the most important feature introduced in Angular 19, and I'm surprised it didn't get as much attention as other features. The productivity of writing code has increased significantly, especially when it comes to styling or adding content to templates, such as in step 3 of a stepper dialog. Until now, working on something like this required going through the same path a million times to see the changes. Thank you for this, Angular Team, truly! I hope you can also tackle the issues with PowerShell in the future. Cheers!

**Comment by spock123** [comment]
@taylorhutchison  I can confirm it now works for templates on my MAC (ARM)

wonderful and magical!

**Comment by jmerro** [comment]
> Unfortunately, HMR for templates works only on the Bash terminal but not on PowerShell, which I use daily. Does anyone know what might be the issue?
> Bash:
> ![Image](https://github.com/user-attachments/assets/af6872e7-e691-4898-ace8-98d9c052b5c4)
> 
> Powershell:
> ![Image](https://github.com/user-attachments/assets/4f87512a-9829-4dc0-8a7b-8a967c99754e)
> 

Assign the environment variable to the process like using something like`set NG_HMR_TEMPLATES=1` enter,  then `ng serve` should work.

**Comment by JeanMeche** [comment]
Is anyone still experiencing the issue ?

**Comment by spock123** [comment]
@JeanMeche  I think it's solved for this case. I think it still won't update when changing classes for a html element but that's for another github issue that's already open I think

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
