### ISSUE TITLE
Observables Called Twice in Dev SSR Server

### ISSUE THREAD

**Issue by lennybakkalian** [angular/angular-cli#29084]
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

No

### Description

In Angular SSR, observables are triggered (at least) twice **on the server** during the **first** page load. To demonstrate this issue, I created a fresh Angular project on StackBlitz. This only happen when running a dev server -> in prod, this behaviour doesnt happen.

Additionally, the `provideAppInitializer` function is also called twice. Afterward, everything works as expected without duplicate calls.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/~/github.com/lennybakkalian/angular-bug?file=src/app/app.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.4
Node: 20.17.0
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 19.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.4
@angular-devkit/build-angular   19.0.4
@angular-devkit/core            19.0.4
@angular-devkit/schematics      19.0.4
@angular/cli                    19.0.4
@angular/ssr                    19.0.4
@schematics/angular             19.0.4
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by alan-agius4** [comment]
This is expected. During the first request in development, the application bootstraps to extract the routes and build a routing table. After this initial process, the application is re-bootstrapped to render the request as usual. In production, this step doesn't occur because the routes are extracted during the build process.

**Comment by lennybakkalian** [comment]
@alan-agius4 Thank you for your answer. Are you sure that the observables need to be subscribed to? i don't see why it is necessary to subscribe to an observable to create the routing table. i personally think this should still be included as a bug ticket, as this is an inconsistency between backend and frontend and causes unexpected behavior in the dev server.

Is there a workaround for this strange behavior? I am building a library and this unnecessary call is causing errors because a page load in ssr is done without a “REQUEST” token.
