### ISSUE TITLE
Add CSS Imports to Index HTML

### ISSUE THREAD

**Issue by Char2sGu** [angular/angular-cli#29082]
### Command

build

### Description

When one add the following to their `styles.css`:
```css
@import 'https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap';
```
The desired stylesheet is only fetched after `styles.css` is ready.

### Describe the solution you'd like

Instead, when top-level CSS imports are detected, automatically generate a `<link rel="stylesheet">` in `index.html`, to enable parallel stylesheet loading.

Remove from `styles.css`:

```css
@import 'https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap';
```

Add to `index.html`:

```html
<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap" rel="stylesheet">
```

### Describe alternatives you've considered

Print warning while building to suggest the developer to prefer `<link rel="stylesheet">` than `@import`.

**Comment by JeanMeche** [comment]
Hi, 
Those css files should be added to the `styles` entry in the `angular.json`.

**Comment by alan-agius4** [comment]
@Char2sGu, it’s enabled by default on production builds when using the application builder.

It’s part of the fonts optimization: https://angular.dev/reference/configs/workspace-config

**Comment by Char2sGu** [comment]
Yes, but only in index.html. I would hope to aggregate all the styles in one file though.
It would be great if CSS `@import` can be optimzied too.

**Comment by alan-agius4** [comment]
Yes can.

**Comment by Char2sGu** [comment]
Ah I see. The `@import` is fetched and inlined in the CSS file.
I was wondering if it would be more performant to inline them in the HTML instead?
