### ISSUE TITLE
Custom index output name is not taken into consideration in SSR app

### ISSUE THREAD

**Issue by pawelfras** [angular/angular-cli#29088]
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

19.0.2

### Description

The output name for index set in `angular.json` file is not taken into consideration in app with SSR (regardless if pre-renderign is set to true).
Regardless of the provided name, builder generates `browser/index.csr.html`. The problem was probably introduced with the https://github.com/angular/angular-cli/commit/21f21eda39c62e284c6cbee0d0ebfe271f605239 - `indexOutput` is set to the value from `options.index.value` but later it is overwritten:
```
    indexOutput =
      (ssrOptions || prerenderOptions) && indexBaseName === 'index.html'
        ? INDEX_HTML_CSR
        : indexBaseName;
```

### Minimal Reproduction

Create new application with SSR:
```bash
npx @angular/cli@19 new ng-19-ssr --ssr --server-routing=false
```
In angular.json, change `index` option:
```diff
- "index": "src/index.html"
+"index": {
+   "input": "src/index.html",
+   "output": "index.html
+}
```
optionally, set `"prerendering": false` in `angular.json` (to reduce noise in `dist/browser`)

run `ng build` and see generated files:
![Image](https://github.com/user-attachments/assets/931e9bd9-5408-4126-ab61-10bb030a047c)

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 19.0.4
Node: 20.18.0
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 19.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.4
@angular-devkit/build-angular   19.0.4
@angular-devkit/core            19.0.4
@angular-devkit/schematics      19.0.4
@angular/cli                    19.0.4
@angular/ssr                    19.0.4
@schematics/angular             19.0.4
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by alan-agius4** [comment]
Why do you need `index.html` when using SSR? The reason for this is that many providers will serve the `index.html` file by default, regardless of whether SSR (Server-Side Rendering) is enabled. As a result, a request to `/` will not trigger SSR but instead return the static `index.html`, defeating the purpose of server-side rendering.

**Comment by pawelfras** [comment]
Hi @alan-agius4, apologies for the late reply. Without going into details, our provider requires an `index.html` for some actions. It was possible to achieve the mentioned option in `angular.json` until the patch version 19.0.3 was released. 
Regardless of my needs, I'm wondering whether it can be considered as a breaking change.
I'd appreciate the information if previous behaviour can be considered a bug and whether the provided change (even if breaking) is a mandatory fix for the actual shape of the Angular.

Thank you!

**Comment by alan-agius4** [comment]
The fix is necessary because, in most cases, outputting an index.html file during Server-Side Rendering (SSR) leads providers to treat this file as a static asset. Consequently, the request is served directly as a static file rather than being passed to the SSR engine for dynamic processing. This behavior defeats the purpose of SSR, as the rendered content remains static instead of dynamically generated.

Out of curiosity, which provider are you using that explicitly requires an index.html file when SSR is enabled? This is unusual because most modern providers designed for SSR environments bypass such static file handling and instead route requests appropriately to the SSR engine. Understanding your specific use case or provider requirements might help identify a more suitable approach or workaround.

**Comment by pawelfras** [comment]
Hi @alan-agius4,
Thank you very much for the explanation! I do agree with your arguments and understand the necessity of this change.
This is not one of the well-known commercial providers but our corporate one. Fortunately, we'll be able to fix its limitations, which are the root cause of the issue.
I hope you don't mind if I close the ticket.

Happy holidays for the whole Angular Team!
