### ISSUE TITLE
Issue debugging beta.18. Sourcemap issue?

### ISSUE THREAD

**Issue by EricBichara** [angular/angular-cli#2909]
### OS?

Mac OSX  10.12.1
### Versions.

angular-cli: 1.0.0-beta.18
node: 6.8.1
os: darwin x64

Npm: 4.0.0
Chrome:  54.0.2840.71
### Repro steps.

new project created with "ng new testproject". Changed **only** to the following code in app.component.ts

```
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  ngOnInit(): void {
    this.dosomething();
  }

  title = 'app works!';

  dosomething() {
    this.title = "trying to do something";
    this.title = "trying to do something else";
  }
}
```

In chrome dev tools, breakpoint doesn't seem to match the scope
<img width="973" alt="screen shot 2016-10-26 at 07 20 26" src="https://cloud.githubusercontent.com/assets/4727892/19714263/f759abc4-9b4c-11e6-9877-ad5e247cb9c0.png">

I've tested in my other projects which i've updated to beta.18, get the same issue. 

Also tried reinstalling angular-cli to make sure there where no issues there:
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli
ng new testproject

**Comment by patrickoneill46** [comment]
Having this issue as well. It seems a 2-3 lines offset for me.

**Comment by Steveiwonder** [comment]
I have the same problem too, hits the break-point then when I attempt to step over it jumps to somewhere completely random.

**Comment by zackarychapple** [comment]
after updating the project I was able to get this working again by going back down to beta.15 of just the cli.

**Comment by EricBichara** [comment]
@zackarychapple , thanks Zack, did you change to beta.15 both globally and in the project?

**Comment by zackarychapple** [comment]
@EricBichara just the project.

**Comment by chadbr** [comment]
See the fix in #2811 from @un33k - this has been fixed in master for the next release.


un33k commented 6 days ago • edited
I also confirm the line number issue in beta.18. A quick workaround for me was to update this file node_modules/angular-cli/models/webpack-build-development.js in my project and replace cheap-module-source-map to source-map. Takes much longer to compile, but line numbers are matching on breakpoints.

**Comment by Autushka** [comment]
@chadbr Thanks, modification of node_modules/angular-cli/models/webpack-build-development.js helped.

**Comment by michaeloryl** [comment]
I have the same problem. In my case it is 10 lines off, as you can see in the screen shot below.
<img width="699" alt="breakpoint_offset_10" src="https://cloud.githubusercontent.com/assets/1957513/19942993/f247cad4-a10b-11e6-84d8-d3fb1ddd8400.png">

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/2857
