### ISSUE TITLE
AngularNodeAppEngine - Support for custom static providers

### ISSUE THREAD

**Issue by stewieoO** [angular/angular-cli#29103]
### Command

serve, build, run

### Description

The `renderApplication` function from `@angular/platform-server` supports providing your own static providers.

It is not possible to provide custom static providers when using the  `AngularNodeAppEngine` and it's `handle` function.

Yes, you can provide a request context that is later available through DI, but that is not the same as having direct access to the static providers.

Is this maybe something already planned for a later release?

### Describe the solution you'd like

I would like the possibility to provide my own set of providers when initializing the `AngularNodeAppEngine` and then request specific providers when calling `handle`.

For example:
```ts
  const server = express();
  const serverDistFolder = dirname(fileURLToPath(import.meta.url));
  const browserDistFolder = resolve(serverDistFolder, '../browser');

  const angularNodeAppEngine = new AngularNodeAppEngine([
   { provide: MY_STATIC_TOKEN, value: 'same-value-for-each-request' }
  ]);

  server.get('**', (req, res, next) => {
    // Yes, this is executed in devMode via the Vite DevServer
    console.log('request', req.url, res.status);

    angularNodeAppEngine
      .handle(req, { server: 'express' }, [{ provide: MY_REQUEST_TOKEN, value: 'request-specific-value' }])
      .then((response) =>
        response ? writeResponseToNodeResponse(response, res) : next()
      )
      .catch(next);
  });
```

From what i can see in the source code this would be just passing through and merging some provider arrays.

**Comment by alan-agius4** [comment]
@stewieo, this is by design.

What is the use-case of passing additional providers in the server.ts file as opposed to the adding providers directly in the `app.config.server.ts`, which can be based on the request. 

Example:
```ts
const serverConfig: ApplicationConfig = {
  providers: [
    provideServerRendering(),
    provideServerRoutesConfig(serverRoutes),
    {
      provide: MY_REQUEST_TOKEN,
      useFactory: () => {
        const req = inject(REQUEST);
        
       return req?.headers….
      },
    },
  ],
```

**Comment by stewieoO** [comment]
@alan-agius4 That is a good point. Maybe i was just being stupid not thinking of that. 
I will check if there is any reason i can't do it this way and report back.

**Comment by stewieoO** [comment]
@alan-agius4 Yeah...nevermind. Everything is working, some extra steps required but i couldn't observe any degredation in render performance, so i'm happy. Thanks!

Just one more thing, you mentioned 
> this is by design as the server.ts has Angular DI ...

Don't you mean it has NO Angular DI?

**Comment by alan-agius4** [comment]
> Don't you mean it has NO Angular DI?

Yes, updated the comment.
