### ISSUE TITLE
Disabling autoRefresh while development

### ISSUE THREAD

**Issue by morriq** [angular/angular-cli#2911]
Hello. 

Is there any global command which I can use in dev console in browser to stop refreshing page after changing in code?
I need test something in private mode but I want to still code in normal mode with autorefesh.

**Comment by filipesilva** [comment]
No, there isn't such functionality. My recommendation would be to build the project onto a specific directory, and serve it statically.
```
npm install -g http-server
ng build --output-path static
http-server static/
```

That way you get a second server running that specific build.
