### ISSUE TITLE
Handling missing assets

### ISSUE THREAD

**Issue by radoslavpetranov** [angular/angular-cli#2912]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 8.1

### Versions.
angular-cli: 1.0.0-beta.18
node: 6.4.0
os: win32 x64

### Repro steps.
try accessing an asset that isn't there. Ex:
localhost:4200/assets/myTest.html

This is more of a question - right now a missing asset would just redirect to the home page localhost:4200. Is there a way to replace this behavior by throwing a good ol' 404?

**Comment by grizzm0** [comment]
All non existing paths are sent to your angular2 application to let the router handle it. That's how the router works. This has nothing to do with angular-cli and 404s is something you should handle yourself in your application.

**Comment by radoslavpetranov** [comment]
Ok I feel slightly dumber than usual. Not sure why I was so sure that the assets would be handled by your dev server and are not part of the angular app. Anyway, thanks for the reply.
