### ISSUE TITLE
Component bootstrapping during route extraction is not disabled when using provideAppInitializer()

### ISSUE THREAD

**Issue by stewieoO** [angular/angular-cli#29131]
### Command

serve, build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The issue of component bootstrapping was discussed in #29085 and fixed in version 19.0.5 with #29101 

This generally works, except when you're using an app initializer.

### Minimal Reproduction

I have created a repro repo [here](https://github.com/stewieoO/angular-route-extraction-issue).

When you `run npm` start and open the page, you can see that the console log inside the app component (and route guard) is called without a REQUEST present (indicating the route extraction process).

When you comment out the `provideAppInitializer()` in the app.config.ts this doesn't happen anymore (as expected).

### Exception or Error

```text

```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 19.0.5
Node: 20.11.1
Package Manager: pnpm 9.12.2
OS: win32 x64

Angular: 19.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.5 (cli-only)
@angular-devkit/build-angular   19.0.5
@angular-devkit/core            19.0.5 (cli-only)
@angular-devkit/schematics      19.0.5 (cli-only)
@angular/cli                    19.0.5
@angular/ssr                    19.0.5
@schematics/angular             19.0.5 (cli-only)
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by stewieoO** [comment]
@alan-agius4 First of all thanks for fixing this.
I ran into another case:

If i inject a service in the provideAppInitializer
```ts
provideAppInitializer(() => {
  const serv = inject(MyService);
})
```

That service will be constructed during route extraction

```ts
@Injectable()
export class MyService {
  constructor() {
    const request = inject(REQUEST, { optional: true });
    console.log('Service Called', request != null);
  }
}
```

Getting the log with request being null.

So the question being, another bug or expected behavior.

**Comment by alan-agius4** [comment]
Running the application initializers during route extraction is the intended behavior as of now.

You can check if `REQUEST` is null in `provideAppInitializer` and exit early to prevent unnecessary execution.

That said, you’re welcome to submit a feature request if you'd like the ability to disable running all application initializers

**Comment by stewieoO** [comment]
> Running the application initializers during route extraction is the intended behavior as of now.

Got it. Thanks for clarifying.

> You can check if `REQUEST` is null in `provideAppInitializer` and exit early to prevent unnecessary execution.

Yeah, that's what i did as a workaround anyways. 

> That said, you’re welcome to submit a feature request if you'd like the ability to disable running all application initializers.

Thanks, might do that.
