### ISSUE TITLE
Need more documentation for using assets 

### ISSUE THREAD

**Issue by guidoffm** [angular/angular-cli#2913]
Until angular-cli beta 16 I can place an asset (e.g. image) file in an arbitrary folder. When the file is referenced from an HTML template with relative path and then an "ng build" is done, we find this file with a new egneric name in the dist folder. When an asset is referenced with a non existing path then we cat a build error saying the file does not exist.

Starting form angular-cli beta 17 it seems that there is a new behavior. Only files that are in the assets folder are copied to the dist folder. References in HTML files to other assets ar ignored and also non existing paths are ignored.

Is there a documentation about that and how can I control this behavior?

**Comment by grizzm0** [comment]
As of beta 18 the assets key in angular-cli.json can be an array of assets to copy over to dist during prod build.

**Comment by filipesilva** [comment]
@guidoffm that was actually a bug in beta.17 - we didn't intend to change that behaviour. It was fixed in https://github.com/angular/angular-cli/pull/2537 and released on `beta.18`.
