### ISSUE TITLE
npm ERR! code EINTEGRITY

### ISSUE THREAD

**Issue by aliashfak178** [angular/angular-cli#29156]
### Command

run

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

before two days my project is working fine but now when i hit **npm i** so give me error 

npm ERR! code EINTEGRITY
npm ERR! sha512-/Tb/JcjK111nNScGob5MNtsntNM1aCNUDipB/TkwZFhyDrrE47SOx/18wF2bbjgc3ZzCSKW1T5nt5EbFoAz/Vg== integrity checksum failed when using sha512: wanted sha512-/Tb/JcjK111nNScGob5MNtsntNM1aCNUDipB/TkwZFhyDrrE47SOx/18wF2bbjgc3ZzCSKW1T5nt5EbFoAz/Vg== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)     
------------------------------------------------------------------------------------------------------------------------------------

i  trying to find root cause and found the issue if used "@angular-devkit/build-angular": "~15.2.11", in dev dependency so this is soing error

"dependencies": {
    "@angular/animations": "~15.2.10",
    "@angular/common": "~15.2.10",
    "@angular/compiler": "~15.2.10",
    "@angular/core": "~15.2.10",
    "@angular/elements": "^15.2.10",
    "@angular/forms": "^15.2.10",
    "@angular/platform-browser": "~15.2.10",
    "@angular/platform-browser-dynamic": "~15.2.10",
    "@angular/router": "~15.2.10",
    "@ngtools/webpack": "^10.0.1",
    "@salesforce-ux/design-system": "2.25.4",
    "angular-persistence": "^1.0.1",
    "axios": "^0.19.2",
    "axios-mock-adapter": "^1.18.2",
    "class-transformer": "^0.2.3",
    "jquery": "^3.5.0",
    "jqueryui": "^1.11.1",
    "jsplumb": "2.13.3",
    "jszip": "^3.10.1",
    "ngx-image-cropper": "^3.1.9",
    "rxjs": "6.5.4",
    "rxjs-compat": "^6.6.0",
    "tslib": "^2.8.0",
    "zone.js": "~0.11.8",
    "ng-keyboard-shortcuts": "^6.1.1",
    "ngx-device-detector": "^2.0.5",
    "xlsx": "^0.17.0",
    "ngx-monaco-editor": "^9.0.0",
    "pdfmake": "^0.2.2",
    "@swimlane/ngx-charts": "^12.0.1",
    "@angular/cdk": "7.x || 8.x",
    "lightning-container": "^1.0.0",
    "node": "^14.20.1",
    "ngx-doc-viewer": "0.1.27"
  },
  "devDependencies": {
    "@angular/cli": "^15.2.11",
    "@angular/compiler-cli": "~15.2.10",
    "@angular/language-service": "~15.2.10",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.34",
    "@types/jqueryui": "^1.12.10",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~6.4.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^15.2.2",
    "protractor": "~7.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.0",
    "typescript": "4.9.5",
    "worker-thread": "^1.1.0",
    "setimmediate": "^1.0.5",
    "ajv": "^8.17.1",
    "ajv-keywords": "^5.1.0"
  }

### Minimal Reproduction

"dependencies": {
    "@angular/animations": "~15.2.10",
    "@angular/common": "~15.2.10",
    "@angular/compiler": "~15.2.10",
    "@angular/core": "~15.2.10",
    "@angular/elements": "^15.2.10",
    "@angular/forms": "^15.2.10",
    "@angular/platform-browser": "~15.2.10",
    "@angular/platform-browser-dynamic": "~15.2.10",
    "@angular/router": "~15.2.10",
    "@ngtools/webpack": "^10.0.1",
    "@salesforce-ux/design-system": "2.25.4",
    "angular-persistence": "^1.0.1",
    "axios": "^0.19.2",
    "axios-mock-adapter": "^1.18.2",
    "class-transformer": "^0.2.3",
    "jquery": "^3.5.0",
    "jqueryui": "^1.11.1",
    "jsplumb": "2.13.3",
    "jszip": "^3.10.1",
    "ngx-image-cropper": "^3.1.9",
    "rxjs": "6.5.4",
    "rxjs-compat": "^6.6.0",
    "tslib": "^2.8.0",
    "zone.js": "~0.11.8",
    "ng-keyboard-shortcuts": "^6.1.1",
    "ngx-device-detector": "^2.0.5",
    "xlsx": "^0.17.0",
    "ngx-monaco-editor": "^9.0.0",
    "pdfmake": "^0.2.2",
    "@swimlane/ngx-charts": "^12.0.1",
    "@angular/cdk": "7.x || 8.x",
    "lightning-container": "^1.0.0",
    "node": "^14.20.1",
    "ngx-doc-viewer": "0.1.27"
  },
  "devDependencies": {
    "@angular/cli": "^15.2.11",
    "@angular/compiler-cli": "~15.2.10",
    "@angular/language-service": "~15.2.10",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.34",
    "@types/jqueryui": "^1.12.10",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~6.4.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^15.2.2",
    "protractor": "~7.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.0",
    "typescript": "4.9.5",
    "worker-thread": "^1.1.0",
    "setimmediate": "^1.0.5",
    "ajv": "^8.17.1",
    "ajv-keywords": "^5.1.0"
  }

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 15.2.11
Node: 14.21.3
Package Manager: npm 6.14.18
OS: win32 x64
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
