### ISSUE TITLE
npm prune --production errors when trying to unbuild Karma

### ISSUE THREAD

**Issue by jimulle** [angular/angular-cli#2915]
### OS?

&nbsp;&nbsp;&nbsp; Windows 7 Enterprise (as well as on Jenkins Linux Build Server)
### Versions.

&nbsp;&nbsp;&nbsp; angular-cli: 1.0.0-beta.18
&nbsp;&nbsp;&nbsp; node: 6.2.1
&nbsp;&nbsp;&nbsp; os: win32 x64
### Repro steps.

```
ng init
ng serve
npm prune --production
```
### The log given by the failure.

```
...
unbuild ember-cli@2.5.0
unbuild babel-core@5.8.38
npm WARN gentlyRm not removing C:\Users\jim\Desktop\test_cli_18\node_modules\.bin\karma.cmd as it wasn't installed by C:\Users\jim\Desktop\test_cli_18\node_modules\karma-cli
npm WARN gentlyRm not removing C:\Users\jim\Desktop\test_cli_18\node_modules\.bin\karma as it wasn't installed by C:\Users\jim\Desktop\test_cli_18\node_modules\karma-cli
```
### Mention any other details that might be useful.
- When i run this directly in command prompt, I get the warning above
- When i run this from an npm script (`"npm run prune": "npm prune --production && npm run some_other_task"`) I get the following error (killing my chained scripts):

```
...
unbuild ember-cli@2.5.0
unbuild babel-core@5.8.38
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jim\\Desktop\\test_cli_18\\node_modules\\npm\\bin\\npm-cli.js" "prune" "--production"
npm ERR! node v6.2.1
npm ERR! npm  v2.14.21
npm ERR! path C:\Users\jim\Desktop\test_cli_18\node_modules\.bin\karma.cmd
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall unlink

npm ERR! enoent ENOENT: no such file or directory, unlink 'C:\Users\jim\Desktop\test_cli_18\node_modules\.bin\karma.cmd'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
```

**Comment by filipesilva** [comment]
I tried on a local install I have but couldn't repro myself. This was on Windows 10. Leaving the issue open but not sure what we can do.

**Comment by filipesilva** [comment]
Oh snap, spoke too soon. On a beta.17 project I couldn't repro, but on a beta.18 I could. Still not sure what do to about it.

**Comment by filipesilva** [comment]
Closing as obsolete.
