### ISSUE TITLE
Generated build scripts ('/dist') point to relative paths on host domain when rendered from a CDN

### ISSUE THREAD

**Issue by ericis** [angular/angular-cli#2916]
> ## Please provide us with the following information:
### OS?

> Windows 10
### Versions.

> angular-cli: 1.0.0-beta.17
> node: 4.4.7
> os: win32 x64
### Repro steps.

App was created with CLI with SCSS support. I integrated Bootstrap with ng2-bootstrap. I added the bootstrap to the `angular-cli.json` file:

```
"styles": [
    "../node_modules/bootstrap/dist/css/bootstrap.min.css",
    "styles.scss"
]
```

Main application is hosted under a different URL (http://localhost:8080) than the CDN (http://localhost:4200/dist). Scripts are loaded from the CDN, including the styles bundle (`styles.b7984559634a76f9fa52.bundle.js`). But, images and fonts are loaded from the host URL (http://localhost:8080) instead of from the CDN under the same relative URL as the scripts (e.g. '/dist'). *The assets (images and fonts) are correctly output to the '/dist' folder. It's just that the script never loads it from it's own origin URL.
### The log given by the failure.

> Chrome 'Network' tab reports: `448c34a56d699c29117adc64c43affeb.woff2 404 font`
### Mention any other details that might be useful.

I modified the styles bundle script to output the path prefix, which was empty in this function:

```
724:function(o,t,e){console.log(e.p);o.exports=e.p+"448c34a56d699c29117adc64c43affeb.woff2"}
```

The source example I have is too complicated and sensitive to share at this point. I will attempt to provide a simple example, but please attempt to resolve if you think you know the answer.

**Comment by filipesilva** [comment]
I can't really see how this is a CLI issue. It seems you have a very specific custom setup that I can't even begin to reproduce. 

If you can frame this in a simple way that exemplifies how its a CLI bug I'll reopen and look into it.
