### ISSUE TITLE
Avoid installing LMDB for systems that dont support

### ISSUE THREAD

**Issue by AlvinChacko** [angular/angular-cli#29174]
### Command

add

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v15

### Description

Im trying to build an angular app on z/OS and it looks like @angular/build@18.2.12 uses lmdb. Lmdb doesnt build on z/OS or have that support wondering if I can avoid installing lmdb. Here is what I see:

```
npm ERR! In file included from ../src/lmdb-js.cpp:1:
npm ERR! ../src/lmdb-js.h:101:12: fatal error: 'byteswap.h' file not found
npm ERR!   #include <byteswap.h>  // bswap_64
npm ERR!            ^~~~~~~~~~~~
npm ERR! 3 warnings and 1 error generated.
npm ERR! make: *** [lmdb.target.mk:195: Release/obj.target/lmdb/src/lmdb-js.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
```

I dont see lmdb as an optional dependency is this needed in the new version of angular cli?

I have added the following but it didnt work:
```
  "optionalDependencies": {
    "lmdb": "3.0.13"
  },
```

### Minimal Reproduction

Run a npm install or add for @angular-devkit/build-angular on a unsupported OS. 

### Exception or Error

```text

```

### Your Environment

```text
Angular: 18.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.12
@angular-devkit/build-angular   18.2.12
@angular-devkit/core            18.2.12
@angular-devkit/schematics      18.2.12
@angular/cdk                    18.2.14
@angular/cli                    18.2.12
@angular/material               18.2.14
@schematics/angular             18.2.12
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10
```

**Comment by alan-agius4** [comment]
This library is already listed as an optional dependency. This seems more of a problem of the package manager which is causing an fatal error for optional dependencies. Does this happen with an another package manager?

See: https://github.com/angular/angular-cli/blob/307eda17e669c3edc9e7cd5603eca1b59828a267/packages/angular/build/package.json#L48

**Comment by alan-agius4** [comment]
@clydin, corrected me that we moved this dependency as option in version 19 and hence why you are seeing the error. 

Please update to the latest version, and if the problem persists please file a new issue.

**Comment by fhuttere** [comment]
@alan-agius4 Any chance at a backport to version 18? We can't update to 19 yet due to other packages we're using.
