### ISSUE TITLE
Add first-class support for bun:test

### ISSUE THREAD

**Issue by NateRadebaugh** [angular/angular-cli#29205]
### Command

test

### Description

The Angular Roadmap calls out that modern testing library integration is a theme of angular.
> https://angular.dev/roadmap#improve-tooling

Currently, angular's components are not able to be tested using bun:
https://bun.sh/docs/cli/test

### Describe the solution you'd like

Would be great to support bun:test out of the box.

Currently, see this type of error when running:

```
error: Component 'CreateNoteDialogComponent' is not resolved:
 - templateUrl: ./note-dialog.component.html
Did you run and wait for 'resolveComponentResources()'?
```

**Comment by alan-agius4** [comment]
Thank you for your feature request and interest in enhancing Angular CLI with bun test support. 

At this time, we do not plan to introduce direct support for bun test within Angular CLI. One of the primary reasons is that `bun test` operates exclusively in the bun runtime environment and is not compatible with Node.js, which remains the primary runtime for Angular projects.

Angular CLI is designed to work consistently across all supported environments, with Node.js being at the core of the development, testing, and production pipelines. Supporting bun test would introduce a significant divergence, as it requires running tests in a different runtime, potentially leading to inconsistencies and fragmentation.
