### ISSUE TITLE
Load remote TemplateUrl

### ISSUE THREAD

**Issue by maytis** [angular/angular-cli#2922]
How do I load remote template Url's in the component directive.

```
const merchantid = "xfhdfggjdf67688c";

templateUrl: 'http://example.com/templates/' +merchantid + '.html',
```

**Comment by deebloo** [comment]
@maytis I am not sure if this is something currently supported. it will almost certainly break with AOT. Try asking in the gitter channel and see if there are other people trying to solve a similar problem.

**Comment by filipesilva** [comment]
We don't support this currently, no.
