### ISSUE TITLE
Workspace Extension Recommendations

### ISSUE THREAD

**Issue by reaction1989** [angular/angular-cli#2924]
Since the latest release of VSCode it is possible to define recommended Extensions per workspace.

It would be cool if this could be implemented. So no one needs to look for all the needed Extensions.

Have a look here : [Latest VSCode Releasenotes](https://code.visualstudio.com/updates/v1_6#_extensions)

**Comment by filipesilva** [comment]
I don't think we should add IDE specific config items to new projects, but it would be nice to have this documented as part of https://github.com/angular/angular-cli/issues/2672 instead.
