### ISSUE TITLE
Cli gives strange lint warnings when using in-memory-web-api (referred to here by wardbell)

### ISSUE THREAD

**Issue by mmc41** [angular/angular-cli#2925]
> ## Please provide us with the following information:
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

MacOS 10.12.1
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.18
node: 7.0.0
os: darwin x64
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Please see attached demo app for the bug:

[bugdemoproject.zip](https://github.com/angular/angular-cli/files/557697/bugdemoproject.zip)

 Unzip, "npm install" and "ng test" on a Mac to reproduce. You might also be able to reproduce on a PC (not sure) but in this case you need to make sure you DO NOT have folder on it called "C:/github/angular.in-memory-web-api" !!
### The log given by the failure.

Note strange logs message below since I am using a Mac and have no "C:" drive: 

WARNING in ./~/angular-in-memory-web-myprojectapi/index.js
Cannot find source file 'C:/github/angular.in-memory-web-api/src//src/index.ts': Error: Can't resolve './C:/github/angular.in-memory-web-api/src//src/index.ts' in '/Users/mmc/repos/myproject/projects/client/node_modules/angular-in-memory-web-api'
 @ ./src/app/fakedata/fake-data-memory-service.ts 9:70-106
 @ ./src/app/shared/services/categories.service.spec.ts
 @ ./src .spec.ts
 @ ./src/test.ts

WARNING in ./~/angular-in-memory-web-api/http-status-codes.js
Cannot find source file 'C:/github/angular.in-memory-web-api/src//src/http-status-codes.ts': Error: Can't resolve './C:/github/angular.in-memory-web-api/src//src/http-status-codes.ts' in '/Users/mmc/repos/myproject/projects/client/node_modules/angular-in-memory-web-api'
 @ ./~/angular-in-memory-web-api/index.js 1:0-36
 @ ./src/app/fakedata/fake-data-memory-service.ts
 @ ./src/app/shared/services/categories.service.spec.ts
 @ ./src .spec.ts
 @ ./src/test.ts

WARNING in ./~/angular-in-memory-web-api/in-memory-backend.service.js
Cannot find source file 'C:/github/angular.in-memory-web-api/src//src/in-memory-backend.service.ts': Error: Can't resolve './C:/github/angular.in-memory-web-api/src//src/in-memory-backend.service.ts' in '/Users/mmc/repos/myproject/projects/client/node_modules/angular-in-memory-web-api'
 @ ./~/angular-in-memory-web-api/index.js 2:0-44
 @ ./src/app/fakedata/fake-data-memory-service.ts
 @ ./src/app/shared/services/categories.service.spec.ts
 @ ./src .spec.ts
 @ ./src/test.ts

WARNING in ./~/angular-in-memory-web-api/in-memory-web-api.module.js
Cannot find source file 'C:/github/angular.in-memory-web-api/src//src/in-memory-web-api.module.ts': Error: Can't resolve './C:/github/angular.in-memory-web-api/src//src/in-memory-web-api.module.ts' in '/Users/mmc/repos/myproject/projects/client/node_modules/angular-in-memory-web-api'
 @ ./~/angular-in-memory-web-api/index.js 3:0-43
 @ ./src/app/fakedata/fake-data-memory-service.ts
 @ ./src/app/shared/services/categories.service.spec.ts
 @ ./src .spec.ts
 @ ./src/test.ts.
### Mention any other details that might be useful.

The warnings also occurs with latest 2.1.2 of angular and with earlier versions of node.

Also reported [here](https://github.com/angular/in-memory-web-api/issues/43), but the in-memory-web-api author wardbell does not use angular-cli and requests me to raise the issue here instead as he is "not using the CLI so I personally don't know how to configure it properly.".

**Comment by filipesilva** [comment]
These are source map warnings. Can you try and see if you still get them in `beta.19-3` please? I think I changed the test build step in the last release and all source maps for `node_modules` should be ignored.

**Comment by mmc41** [comment]
Yes. Fixed in beta 19. Thanks.

**Comment by filipesilva** [comment]
Awesome, happy to hear!
