### ISSUE TITLE
Debugging not working.

### ISSUE THREAD

**Issue by piernik** [angular/angular-cli#2926]
There is something wrong with sourcemaps I think.
I can't get debugging correspond to correct lines in ts.
Here are some screenshots:
http://stackoverflow.com/questions/40279812/debugging-angular-cli-in-webstorm?noredirect=1

**Comment by feisel** [comment]
I have same problem. 
It seems that old mapfiles loaded.

**Comment by nukuuk** [comment]
am having same problem.  debugging was working until I reached a certain number of components (around 20) then it become impossible to set proper breakpoints: either they weren't hit or off by x number of lines.

**Comment by hartz89** [comment]
I was able to fix this by following the upgrade steps in the readme.
I upgraded from 1.0.0-beta.18 to 1.0.0-beta.19-3.
I'm working against master, so I also did a git pull in my local repo and ran npm link again.

**Comment by filipesilva** [comment]
`beta.18` had a sourcemap problem which was fixed and released in `beta19-3`. If you can find me a way to repro in a brand new `beta.19-3` project I'm happy to look at it.
