### ISSUE TITLE
AOT setup for tsconfig.json conflicts with ng test

### ISSUE THREAD

**Issue by mmc41** [angular/angular-cli#2927]
> ## Please provide us with the following information:
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

mcOS 10.12.1
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.18
node: 7.0.0
os: darwin x64
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

1) ng create experiment
2) cd experiment
3) npm install

4) As specified by official [Ahead-of-time compilation steps](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) guidelines add the following to tsconfig.json: 
  "files": [
    "app/app.module.ts",
    "app/main.ts"
  ],

P.S: I would like to use the same tsconfig.json for both AOT and normal usage, rather than creating a new one for AOT - is that supported ? 
### The log given by the failure.

> Normally this include a stack trace and some more information.

ERROR in [default] /Users/mmc/temp/experiment/src/test.ts:19:2 
Cannot find name 'System'.

ERROR in [default] /Users/mmc/temp/experiment/src/test.ts:20:2 
Cannot find name 'System'.
### Mention any other details that might be useful.

Happens also with later versions of Angular 2 and earlier versions of nodejs.

**Comment by filipesilva** [comment]
https://angular.io/docs/ts/latest/cookbook/aot-compiler.html was written with the https://github.com/angular/quickstart base setup in mind. 

When using the CLI you don't need to change anything in the base project setup, `ng build --aot` should suffice. We take care of all code transforms and changes behind the scenes. This feature is experimental though, there's a few bugs.
