### ISSUE TITLE
how to build

### ISSUE THREAD

**Issue by xcsweb** [angular/angular-cli#2928]
how to build

**Comment by michal-kroliczek** [comment]
seriously? Read doc....

**Comment by deebloo** [comment]
@xcsweb do you have a specific issue you are running into? If you have a more general questions asking on stackoverflow or the gitter channel may yield better results.

**Comment by filipesilva** [comment]
@xcsweb you can use `ng build` to build a new project. If you want to build the CLI itself for local development, you don't actually need to, instead just do `npm link` to have it globally available.
