### ISSUE TITLE
no details about npm installing packages when doing ng new or ng init

### ISSUE THREAD

**Issue by ganqqwerty** [angular/angular-cli#2930]
> ## Please provide us with the following information:
### OS?

>  Mac OSX Yosemite
### Versions.

angular-cli: 1.0.0-beta.17
node: 5.7.1
os: darwin x64
### Repro steps.

on the fresh directory I run `ng new dataset-browser`
after answering the question of the application I end up looking at the following: 

```
Installing packages for tooling via npm.
Installed packages for tooling via npm.
```

no details are given even if I run it with `-v` flag.

**Comment by gelliott181** [comment]
This is as verbose as the CLI gets about installing packages right now. A couple of the dependencies are large packages, and the tree to display them all scrolls for days if you run `npm install` yourself.

Now for my thoughts: Yes, I'd love to see how far in my installation is. That said, the maintainers have some major features which they should and are focusing on. This leads me to believe we're unlikely to see cosmetic work like this until someone with a little weight behind their decisions wants to see it done, the Final release has come and gone, or someone puts in a PR.

**Comment by amaredeus** [comment]
A blinking cursor or some sort would do wonders, just my 2 cents.

**Comment by clydin** [comment]
Progress is now displayed in the latest version.
