### ISSUE TITLE
AOT writes wrong scss file to app.component.ngFactory

### ISSUE THREAD

**Issue by simonh1000** [angular/angular-cli#2938]
> ## Please provide us with the following information:
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
> OSX El Capitan
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.18
node: 6.3.1
os: darwin x64
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
> ng build --prod --aot
> I'm ending up with 
> import \* as import14 from '../../app/app.component.scss';
> in app.module.ngfactory.ts whereas it would seem it should be
> import \* as import14 from './app.component.scss';
### The log given by the failure.

> Normally this include a stack trace and some more information.

ERROR in ./src/aot/app/app.component.ngfactory.ts
Module build failed: Error: /Users/simon/code/wp_af2015/wp-content/themes/af2016/afapp/src/aot/app/app.component.ngfactory.ts (21,27): Cannot find module '../../app/app.component.scss'.)
    at _transpile (/Users/simon/code/wp_af2015/wp-content/themes/af2016/afapp/node_modules/@ngtools/webpack/src/loader.js:101:19)
    at /Users/simon/code/wp_af2015/wp-content/themes/af2016/afapp/node_modules/@ngtools/webpack/src/loader.js:125:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/aot/app/app.module.ngfactory.ts 41:0-54
 @ ./src/main.ts
 @ multi main
### Mention any other details that might be useful.

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Can you provide me some repro steps so that I can look into this?

**Comment by daniele-zurico** [comment]
same here.
This is my repo project: https://github.com/daniele-zurico/webpack-aot

**Comment by BrainCrumbz** [comment]
It might be worth noting that a (very very) similar behaviour has already been flagged in these two angular issues:

1. https://github.com/angular/angular/issues/12539
1. https://github.com/angular/angular/issues/11688

**Comment by filipesilva** [comment]
Closing as answered by @BrainCrumbz, thanks for finding the right issues!
