### ISSUE TITLE
Feature Request overloads

### ISSUE THREAD

**Issue by jmurphzyo** [angular/angular-cli#2946]
I don't know if this is something that might already be planned but I think it would be nice to have the generate module command have an overload that could add services.

**Comment by Brocco** [comment]
This type of behavior has been discussed and might be implemented later on. But for now, we're going to focus on making each of our blueprints (i.e. component, service, directive) as valuable as possible. Combination generations may be investigated later. Thanks for the suggestion, but not right now.
