### ISSUE TITLE
Serve Without Watching Files?

### ISSUE THREAD

**Issue by JimTheMan** [angular/angular-cli#2947]
> ## Please provide us with the following information:
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

All
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
> yes

Is it possible to run the app using ng serve but not have it reload automatically when files have changed? The angular cli browser refresh is waaaaay too slow, and I want to use LiveEdit in WebStorm instead.

**Comment by filipesilva** [comment]
No, there's no such functionality currently. I suppose you can `ng build --watch`.

**Comment by JimTheMan** [comment]
Strange, I guess I'll have to wait for them to finish the ngrx Redux hot reload that doesn't refresh the browser. : /
