### ISSUE TITLE
using the --aot flag breaks custom annotations

### ISSUE THREAD

**Issue by fshchudlo** [angular/angular-cli#2952]
### OS?

Windows 8
### Versions.

angular-cli: 1.0.0-beta.19-3  
node: 6.7.0  
os: win32 x64 
### Repro steps.

I create [the repo to demonstrate this issue](https://github.com/fshchudlo/aot-bug-sample) 
This is regular app which was created with `ng new` command.
I added definition of dumb `log` annotation inside `app.component.ts` file and decorate `title` property of the app component with this annotation.
If I run this app with `ng serve` it works well.
If I run this app with `ng serve --aot` message doesn't appears to the console.

Same case works well with [angular2webpack2-starter](https://github.com/qdouble/angular2webpack2-starter)

**Comment by Meligy** [comment]
Looks like an Angular Compiler problem more than an Angular CLI problem.

I'd suspect you'll get the same with other repos like https://github.com/mgechev/angular-seed or https://github.com/qdouble/angular-webpack2-starter (which seems to have had more fun with AoT judging by https://github.com/qdouble/angular-webpack2-starter#aot--donts).

**Comment by fshchudlo** [comment]
No, it's problem with Angular-CLI.
As I wrote in issue description, I tried to reproduce same issue with webpack2-starter and the error did not occur.

**Comment by clydin** [comment]
Dup: #2799
