### ISSUE TITLE
"ng build --prod --aot" gives error "Error encountered resolving symbol values statically. Function calls are not supported."

### ISSUE THREAD

**Issue by Mufasa** [angular/angular-cli#2954]
### OS?

> macOS Siera 10.12.1
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
> angular-cli: 1.0.0-beta.19-3
> node: 6.7.0
> os: darwin x64
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
> I have been using the CLI successfully with **angular 2.1.2**, **angular material 2.0.0-alpha.9-3**, and **Promact/md2 0.0.6** (**select** and **datepicker** components).
> Today I tried to use the AoT by running `ng build --prod --aot` and got a stack trace complaining about **lambda** functions so (after googling around) I extracted the one **lambda** function I had in my `app.module.ts` file into its own function and reran `ng build --prod --aot` but it still failed.
### The log given by the failure.

> Normally this include a stack trace and some more information.
> 
> ```
>   0% compilingError encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/anjum/Documents/workspace/go2travel-ng-cli/src/app/app.module.ts, resolving symbol AppModule in /Users/anjum/Documents/workspace/go2travel-ng-cli/src/app/app.module.ts
> Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/anjum/Documents/workspace/go2travel-ng-cli/src/app/app.module.ts, resolving symbol AppModule in /Users/anjum/Documents/workspace/go2travel-ng-cli/src/app/app.module.ts
>     at simplifyInContext (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:532:15)
>     at StaticReflector.simplify (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:536:20)
>     at StaticReflector.annotations (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:93:28)
>     at NgModuleResolver.resolve (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/@angular/compiler/bundles/compiler.umd.js:14050:46)
>     at CompileMetadataResolver.getNgModuleMetadata (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/@angular/compiler/bundles/compiler.umd.js:14296:49)
>     at /Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/@angular/compiler/bundles/compiler.umd.js:13284:43
>     at Array.forEach (native)
>     at _extractModulesAndPipesOrDirectives (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/@angular/compiler/bundles/compiler.umd.js:13283:28)
>     at analyzeNgModules (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/@angular/compiler/bundles/compiler.umd.js:13039:16)
>     at OfflineCompiler.compileModules (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/@angular/compiler/bundles/compiler.umd.js:13115:20)
>     at CodeGenerator.codegen (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:71:26)
>     at AotPlugin._make (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/@ngtools/webpack/src/plugin.js:186:43)
>     at Compiler.<anonymous> (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/@ngtools/webpack/src/plugin.js:151:75)
>     at Compiler.applyPluginsParallel (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/tapable/lib/Tapable.js:156:14)
>     at Compiler.<anonymous> (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/webpack/lib/Compiler.js:463:8)
>     at Compiler.applyPluginsAsync (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/tapable/lib/Tapable.js:73:70)
>     at Compiler.compile (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/webpack/lib/Compiler.js:456:7)
>     at Compiler.<anonymous> (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/webpack/lib/Compiler.js:219:10)
>     at Compiler.readRecords (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/webpack/lib/Compiler.js:367:10)
>     at Compiler.<anonymous> (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/webpack/lib/Compiler.js:216:9)
>     at next (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/tapable/lib/Tapable.js:81:11)
>     at Compiler.<anonymous> (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/webpack/lib/CachePlugin.js:34:58)
>     at Compiler.applyPluginsAsync (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/tapable/lib/Tapable.js:85:13)
>     at Compiler.<anonymous> (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/webpack/lib/Compiler.js:213:8)
>     at next (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/tapable/lib/Tapable.js:81:11)
>     at Compiler.<anonymous> (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:23:3)
>     at Compiler.applyPluginsAsync (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/tapable/lib/Tapable.js:85:13)
>     at Compiler.run (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/webpack/lib/Compiler.js:210:7)
>     at /Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/angular-cli/tasks/build-webpack.js:26:29
>     at Class.run (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/angular-cli/tasks/build-webpack.js:25:16)
>     at Class.run (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/angular-cli/commands/build.js:50:26)
>     at Class.<anonymous> (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/angular-cli/lib/models/command.js:152:17)
>     at tryCatch (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
>     at invokeCallback (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
>     at publish (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
>     at flush (/Users/anjum/Documents/workspace/go2travel-ng-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> ```
### Mention any other details that might be useful.

My `app.module.ts` file looks like this:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { CurrencyPipe } from '@angular/common';
import { RouterModule } from '@angular/router';
import { MaterialModule } from '@angular/material';

import { MockBackend } from '@angular/http/testing';
import { Http, BaseRequestOptions } from '@angular/http';

import { Md2Module } from 'md2';

import { AppComponent } from './app.component';
import { APP_CONFIG, APP_CONFIG_t } from './app.config.data';
import { ROUTES } from './app.routes';

import { StartupService } from './lib/startup.service';
import { UkCurrencyPipe } from './lib/uk.currency.pipe';
import { MapToIterablePipe } from './lib/map.to.iterable.pipe';
import { getUrlQueryParams } from './lib/url';

import { TripTypes } from './trip/trip';
import { PolicyTypes } from './policy/policy';
import { QuoteService } from './quote/quote.service';
import { HomeComponent } from './home/home.component';
import { StepsComponent } from './steps/steps.component';
import { StepsNavComponent } from './steps/steps-nav.component';
import { QuoteComponent } from './quote/quote.component';
import { PolicyComponent } from './policy/policy.component';

import { Go2TravelMockApi } from './api/go2travel.mock.api';

export function httpFactory(backend: any, options: any): Http {
  return new Http(backend, options);
}

@NgModule({
  declarations: [
    UkCurrencyPipe,
    MapToIterablePipe,
    AppComponent,
    HomeComponent,
    StepsComponent,
    StepsNavComponent,
    QuoteComponent,
    PolicyComponent
  ],
  imports: [
    BrowserModule,
    ReactiveFormsModule,
    HttpModule,
    RouterModule.forRoot(ROUTES, { useHash: true }),
    MaterialModule.forRoot(),
    Md2Module.forRoot()
  ],
  providers: [
    { provide: APP_CONFIG_t, useValue: APP_CONFIG },
    CurrencyPipe,
    TripTypes,
    PolicyTypes,
    StartupService,
    QuoteService,
    BaseRequestOptions,
    MockBackend,
    {
      provide: Http,
      deps: [MockBackend, BaseRequestOptions],
      useFactory: httpFactory
    },
    Go2TravelMockApi
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(startupService: StartupService, private go2TravelMockApi: Go2TravelMockApi) {
    startupService.urlParams = getUrlQueryParams(window.location.search.substring(1));
  }
}
```

**Comment by rolandoldengarm** [comment]
Try commenting out your imports / providers one by one, to see which one is the culprit.

**Comment by Mufasa** [comment]
Hmmm - the culprit seems to be:
```
import { Md2Module } from 'md2';
```
Should I report this on their GitHub or is there another way to resolve this?

**Comment by rolandoldengarm** [comment]
They have to fix that. Probably they need to add .metadata.json file.
In any case, not an issue with angular-cli.

**Comment by filipesilva** [comment]
Yeah this isn't something we can fix on the CLI itself. You'd have the same error if you were using AoT without the CLI. Perhaps the lib maintainers can fix it there to make their lib AoT ready.
