### ISSUE TITLE
include a specific library path  (ex: moment-with-locales.js instead of moment.js) 

### ISSUE THREAD

**Issue by ljacques** [angular/angular-cli#2955]
### OS?
> Windows 10

### Versions.
> angular-cli: 1.0.0-beta.18
> node: 4.4.4
> os: win32 x64

### Repro steps.
> Hello,
> I've included the library 'moment' in my project but I do not find a way to set angular-cli to take 
> moment-with-local.js instead of moment.js
> may be a noob issue
> thank you in advance

**Comment by phra** [comment]
you can import a specific file with this syntax:

```javascript
import moment from 'moment/path/to/moment-with-local';
```

**Comment by ljacques** [comment]
I have tried in this way but it does not work. after some research here is what seems to work:
`import * as moment from 'moment';`
`import 'moment/min/locales.min';`
