### ISSUE TITLE
ng new <Project name> does not create app component related files

### ISSUE THREAD

**Issue by k123009** [angular/angular-cli#2961]
Hi,
I am new to angular 2 and using angular-cli tool to create my first project. I am using ng new <Project name> but files that this command generates is different than what usually tutorials and books are saying. 

For example mostly tutorials are saying app folder should contains below files
create src/app/app.component.css
create src/app/app.component.html
create src/app/app.component.spec.ts
create src/app/app.component.ts
create src/app/app.module.ts
create src/app/index.ts
create src/app/shared/index.ts 

but in my case app folder contains  
create src\app\test-application.component.css
create src\app\test-application.component.html
create src\app\test-application.component.spec.ts
create src\app\test-application.component.ts
create src\app\environment.ts
create src\app\index.ts
create src\app\shared\index.ts

why in my case these files are not generating ? (i-e app.component.ts)
Have I missed some thing ?
Kindly suggest

### Versions.
Windows 10, x64
angular-cli: 0.1.0
node: 5.4.1
os: win32 x64
npm : 3.3.12
tsc : Version 2.0.6

Thanks

**Comment by deebloo** [comment]
app.component is just a naming convention that is sometimes used. The exact files created by the cli also may not match exactly what some from scratch tutorials may say. Also what version of the CLI are you using.

**Comment by Meligy** [comment]
Your version of the CLI is super old. The current hierarchy is very different.

Please run the following:

```
npm uninstall -g angular-cli
npm cache clear
npm install -g angular-cli@1.0.0-beta.19-3
```

Ideally upgrade your Node to 6.x and NPM to 3.10.x as well before this.

This issue is no longer applicable to current version of the CLI.

**Comment by k123009** [comment]
yes, it works by upgrading node js and angular-cli.

Thank you

**Comment by smsuresh** [comment]
I did update node & npm, still files not getting generated..
