### ISSUE TITLE
3rd Party Library Installation not working and not add to dist

### ISSUE THREAD

**Issue by otrifo** [angular/angular-cli#2963]
### OS?
> Mac OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.19-3
node: 6.3.1
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
i followed the steps you described : this app created by angular-cli 
I try to add a ng2-select folder to dist but after i do ng build is׳t don׳t add to dist folder.
in dist folder i have only this file: 
favicon.ico,
index.html,
inline.js,
inline.map,
main.bundle.js,
main.map,
styles.bundle.js,
styles.map

### The log given by the failure.
> Normally this include a stack trace and some more information.
i dong have a error message in the app 

### Mention any other details that might be useful.
I used a previous version of Angular cli and  I was working with systemJs
I did not understand the new version upgrade and how to work white this.

thanks :)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filoxo** [comment]
Perhaps you should refer to the migration guide. 

https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14

**Comment by filipesilva** [comment]
See https://github.com/angular/angular-cli#3rd-party-library-installation for a up to date 3rd party lib install guide.
