### ISSUE TITLE
Feature Request: ng cli option for angular-cli.json name and/or location

### ISSUE THREAD

**Issue by jgainfort** [angular/angular-cli#2964]
I have found a need to modify properties inside the angular-cli.json, particularly the styles and scripts property, depending on what libs I want compiled for various clients.

The ability to provide the name or location of an angular-cli.json config file would solve this easily.

Something like:

ng <command> -config angular-cli.alt.json

Im assuming the optional property would need to default to angular-cli.json and be available for all of the cli commands. I know there is already error handling for improper config files so I dont see much of a risk with this property.

I would be willing to provide a PR if a) this isn't already in the works, b) there isn't an alt approach that doesn't require modification to this project and c) someone quickly points me to the file where this would occur in.

**Comment by jgainfort** [comment]
Another use case is for changing the apps.index, apps.main file names and or locations as well.

**Comment by filipesilva** [comment]
This is part of a bigger feature that we want to do, and the reason why `apps` is an array. The plan is to be able to have several apps inside the same project, with per-app settings. It's a post 1.0 thing though.

**Comment by jgainfort** [comment]
@filipesilva  I know you have said this is a post 1.0 feature but would you be able to provide a rough estimate? Would it be available sometime this year or 2018?

Would there be anything I could potentially help with?
