### ISSUE TITLE
Improper relative path for images or static files

### ISSUE THREAD

**Issue by ahaan729** [angular/angular-cli#2966]
### OS?
>Windows 10

### Versions.
> angular-cli: 1.0.0-beta.19-3
node: 7.0.0
os: win32 x64

### Repro steps.
> Trying to give a relative path to the static files/image present in the assets folder.
If I have -->  **img src="/first-app/assets/path/to/image/trial.png"**
it works fine on the server where I have deployed my application. But the same fails on the localhost... and only this works on localhost --> **img src="/assets/path/to/image/trial.png"**

>So I tried... **ng build --base-href /first-app/**
This works as a relative path for the scripts present in the index.html but not for the images which are referenced in different components. 

### The log given by the failure.
> GET http://10.106.3.120/assets/path/to/image/small.png 404 (Not Found)
GET http://10.106.3.120/assets/path/to/image/trial.png 404 (Not Found)

### Mention any other details that might be useful.
I am clueless on how to get the images referenced. 
The files generated after build are placed under **/first-app** folder. How to get this fixed?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
You're using a root relative URL for your assets.  Take out the first `/`.

**Comment by ahaan729** [comment]
@clydin  Thanks.. That worked for me. :)
