### ISSUE TITLE
Lazy loading breaks with 3rd party library

### ISSUE THREAD

**Issue by slubowsky** [angular/angular-cli#2967]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 7.0.0
os: win32 x64

### Repro steps.
(See comments below. Added link to project showing issue)
Generate simple app add simplest lazy loading. (https://github.com/angular/angular-cli/issues/2865 with fix as described there might be a good starting point). Make sure multiple bundles created. Add an ng2-bootstrap alert as described at https://github.com/valor-software/ng2-bootstrap/blob/development/docs/getting-started/ng-cli.md. Lazy loading stops working, Only one bundle created. (Would attach project here with the described changes already included but github not allowing the attachment for some reason. Pretty simple to reproduce as above though) 

See also https://github.com/valor-software/ng2-bootstrap/issues/1187

### The log given by the failure.
No error

### Mention any other details that might be useful.
Dont know if this a cli issue or a ng2-bootstrap issue.

**Comment by Meligy** [comment]
Hello,

Can you please try to fork https://github.com/meligy/routing-angular-cli, and try to reproduce the issue in that repo, and push it to github, link to it here?

The only thing I remember that might be related is when you have barrels (`index.ts` file that `export *` from all files in the directories, or other modules), which I think broke lazy loading somewhere, but I'm unable to find a relevant issue now. The above repo is a good start as it already has lazy loading setup, you just include the alert and see if it continues to work.

Thanks a lot.

Cheers,

**Comment by slubowsky** [comment]
@Meligy Great idea, thanks.
Forked repo is at https://github.com/slubowsky/routing-angular-cli
Before changes ng-serve builds with 2 bundles, main.bundle and 0.chunk
![chunks](https://cloud.githubusercontent.com/assets/270589/19888980/981ef3ce-a008-11e6-88ea-eb63a38e5166.png)
Make exactly three changes:
1 - add ng2-bootstrap to package.json
2 - import a module from it in app.module.ts
3 - add the module to AppModule imports
Now only one bundle, main.bundle
![nochunks](https://cloud.githubusercontent.com/assets/270589/19889020/f374b59c-a008-11e6-9fec-f77a1f548310.png)

(Note to actually use the module add `<alert type="success">hello</alert>` to app.component.html. To make it look right add bootstrap css. Just importing it as above without actually using it is enough to break lazy loading)

**Comment by JiriBalcar** [comment]
Is this duplicate with #2496?

**Comment by slubowsky** [comment]
@JiriBalcar Yes. Looks like it is. See https://github.com/angular/angular-cli/issues/2496#issuecomment-252155012 which addresses ng2-bootstrap directly and thats probably the issue referenced by @Meligy above
