### ISSUE TITLE
Port and Proxy Config on ng-build

### ISSUE THREAD

**Issue by markus138** [angular/angular-cli#2969]
Hello, I have 2 problems at the moment with the `ng-build`. I have created an `environment.int.ts` file (+ an entry in angular-cli.apps[0] just like the entry for dev and prod) and a `proxy.conf.integration.ts`. When I run `ng build --int --port 3000 --proxy-config src/config/proxy/proxy.conf.integration.json` I get the errors:

```
The option '--int' is not registered with the build command. Run `ng build --help` for a list of supported options.
The option '--port' is not registered with the build command. Run `ng build --help` for a list of supported options.
The option '--proxy-config' is not registered with the build command. Run `ng build --help` for a list of supported options.
```

so my question is: how can I add a proxy_config/port to my ng-build?

**Comment by deebloo** [comment]
The proxy and port configs are just for the dev server not for the static build. If you have other static files that you want to copy into your dist folder you can add them to the assets array

**Comment by markus138** [comment]
is this a planned feature for the future?

**Comment by deebloo** [comment]
@markus138 I am not sure I totally understand. The result of building with the CLI is static html and javascript that can be hosted by any server.

**Comment by markus138** [comment]
I have a frontend running for example on `int.myapp.com` and it's backend on `int.backend.myapp.com`. I thought I can do the proxing with the proxy.conf like this:

```
 "/api": {
    "target": "https://int.backend.myapp.com",
    "secure": true,
    "changeOrigin": true
  }
```

I got a running version right now anyway I was just wondering it this is something the config could do.

closing this issue since I misunderstood the docs

**Comment by yaotzin68** [comment]
@deebloo hi, do you a example? I'm trying to use the proxy when im building the prod version, but it's not working, I dont know how to set the proxy in prod version

**Comment by dinukanadeeshan** [comment]
how to add The proxy and port configs for static build?

**Comment by moochdt003** [comment]
@dinukanadeeshan Did you ever find an answer for  your questions? "how to add The proxy and port configs for the static build?"

**Comment by dinukanadeeshan** [comment]
No, @moochdt003

**Comment by jesusmariajurado** [comment]
@dinukanadeeshan and @moochdt003 no way to add proxy or port on build script, on prod env this is not a responsibility for your angular application. On prod you have to config your proxies, for example, if you are in a dockerized env you could add this to a Dockerfile file in the root of your app:

`FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf

WORKDIR /usr/share/nginx/html
COPY dist/ .`

So you'll have a nginx container with your prod distribution, then you can config easily your nginx server with this nginx.conf content:

`worker_processes  1;

events {
    worker_connections  1024;
}

http {
    server {
        listen 80;
        server_name  localhost;

        root   /usr/share/nginx/html;
        index  index.html index.htm;
        include /etc/nginx/mime.types;

        gzip on;
        gzip_min_length 1000;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        location /api {
            rewrite /api/(.*) /$1  break;
            proxy_pass http://myapiserver:port;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
`

you can see if you have call to /api/ the proxy rewrite and redirect to http://myapiserver:port. that'd be equivalent to this proxy.conf.js entry for dev environment:

`const proxyConfig = [
  {
    context: '/api/',
    pathRewrite: { '^/api': '' },
    target: 'http://myapiserver:port',
    changeOrigin: true,
    secure: false
  },...`

**Comment by TonyYule** [comment]
Maybe this can help you.
https://itnext.io/angular-cli-proxy-configuration-4311acec9d6f

**Comment by dinukanadeeshan** [comment]
Thank you @jesusmariajurado.

**Comment by DiegoVeronezi** [comment]
Yeehh, thanks @jesusmariajurado
