### ISSUE TITLE
npm linked version of angular-cli returns error when generating a new project

### ISSUE THREAD

**Issue by seanrkerr** [angular/angular-cli#2970]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
OSX 10.12

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: local (v1.0.0-beta.19, branch: master)
node: 6.3.1
os: darwin x64

### Repro steps.
1. git clone https://github.com/angular/angular-cli.git
2. cd angular-cli
3. npm link
4. ng new foo >> this is where the error happens

### The log given by the failure.
> Normally this include a stack trace and some more information.

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

npm ERR! No compatible version found: angular-cli@1.0.0-beta.19
npm ERR! Valid install targets:
npm ERR! 1.0.0-beta.2-mobile.4, 1.0.0-beta.2-mobile.3, 1.0.0-beta.2-mobile.2, 1.0.0-beta.2-mobile.1, 1.0.0-beta.2-mobile, 1.0.0-beta.19-3, 1.0.0-beta.12-1, 1.0.0-beta.11-webpack.9-4, 1.0.0-beta.11-webpack.9-3, 1.0.0-beta.11-webpack.9-2, 1.0.0-beta.11-webpack.9-1, 1.0.0-beta.11-webpack.9, 1.0.0-beta.11-webpack.8, 1.0.0-beta.11-webpack.7, 1.0.0-beta.11-webpack.6, 1.0.0-beta.11-webpack.5, 1.0.0-beta.11-webpack.4, 1.0.0-beta.11-webpack.3, 1.0.0-beta.11-webpack.2, 1.0.0-beta.11-webpack, 1.0.0-beta.18, 1.0.0-beta.17, 1.0.0-beta.16, 1.0.0-beta.15, 1.0.0-beta.14, 1.0.0-beta.12, 1.0.0-beta.10, 1.0.0-beta.9, 1.0.0-beta.8, 1.0.0-beta.6, 1.0.0-beta.5, 1.0.0-beta.4, 1.0.0-beta.1, 1.0.0-beta.0, 0.1.0, 0.0.39, 0.0.37, 0.0.34, 0.0.33, 0.0.31, 0.0.30, 0.0.29, 0.0.28, 0.0.27, 0.0.26, 0.0.25, 0.0.24, 0.0.23, 0.0.22, 0.0.20, 0.0.19, 0.0.18, 0.0.17, 0.0.16, 0.0.15, 0.0.14, 0.0.13, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1, 0.0.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by sdiazvi** [comment]
+1 here.

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/2992
