### ISSUE TITLE
SilentError: Multiple module files found: \clerking

### ISSUE THREAD

**Issue by st-clair-clarke** [angular/angular-cli#2973]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 6.6.0
os: win32 x64

### Repro steps.
1. Create a module in a `clerking` folder
2. Create another module in the same `clerking` folder
2. Attempt to run `ng g component mycomponent` in the same `clerking` folder

### The log given by the failure.
Error locating module for declaration
        SilentError: Multiple module files found: \clerking

### Mention any other details that might be useful.
The above error might very well be the intended result from the tooling. However, can there be an option to override the behaviour when it is required. So I might be able to give the command the name of the module to place the component or simply let the command run without the error, allow us to placed the component in its respective module?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
Looks like there is a `--skip-import` option but it only skips the actual importing step.  It should probably skip the module location step as well.

**Comment by filipesilva** [comment]
@Brocco can you weigh in?

**Comment by Brocco** [comment]
When that flag is specified, the current error can be converted to show a warning. Assigning this issue to myself for implementation.
