### ISSUE TITLE
Diff after upgrade shows files which have not changed

### ISSUE THREAD

**Issue by reaction1989** [angular/angular-cli#2983]
### OS?
> Windows 10

### Versions.
> angular-cli: 1.0.0-beta.19-3
node: 4.4.7
os: win32 x64

### Repro steps.
> Upgrade from beta18 to beta19

### Mention any other details that might be useful.

> ![image](https://cloud.githubusercontent.com/assets/873751/19919016/5cdf1ae6-a0d0-11e6-947c-322145e56224.png)
The diff on the automatically created files could be made a lil bit more intelligent. In this example nothing got changed. It would be cool to see only files which will get a change.

**Comment by grizzm0** [comment]
The diff is double-quotes (") vs single-quotes (').

**Comment by reaction1989** [comment]
oO My fault.
