### ISSUE TITLE
References to external resources do not work in @import'ed SCSS files

### ISSUE THREAD

**Issue by rstropek** [angular/angular-cli#2986]
### OS
Windows 10

### Version
1.0.0-beta.19-3

### Repro steps.
1. Create new app: `ng init --style scss`
1. Create folder `externalStyles` in the root folder of your app (adjacent to `src`)
1. Place a small sample image `cat.png` in the `externalStyles` folder (this will be the resource we reference in the SCSS file)
1. Place the following SCSS file called `myStyles.scss` in the `externalStyles` folder (references the previously created image)
    ```
    $image-dir: './' !default;
    body { background-image: url('#{$image-dir}cat.png'); }
    ```
1. Add a reference to `myStyles.css` to `angular-cli.json` in the `styles` section:
    ```
    {
      ...,
      "apps": [ {
        ...,
        "styles": [
          "styles.scss",
          "../externalStyles/myStyles.scss"
        ],
        ...
      } ],
      ...
    }
    ```
1. Run the app: `ng serve`. The image file will become part of the bundle and it will be correctly shown as the background image of the app.
1. Remove the reference to `myStyles.scss` from `angular-cli.json`
1. Instead, add a reference to `myStyles.scss` in `src/styles.scss`:
    ```
    @import '../externalStyles/myStyles.scss';
    ```
1. **Now Webpack can no longer resolve `./cat.png`. Therefore, the app has no background images.**

### The log given by the failure
```
ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module not found: Error: Can't resolve './cat.png' in 'C:\temp\scssNg2Cli\src'
 @ ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss 6:143-163
 @ ./src/styles.scss
 @ multi styles
```

### Mention any other details that might be useful.
In practice, this error is critical because it prevents importing Kendo UI's SCSS file.

Attached you find the project showing the error.
[scssNg2Cli.zip](https://github.com/angular/angular-cli/files/566256/scssNg2Cli.zip)

**Comment by grizzm0** [comment]
What's the reason of having the style outside the project?

The first one works as those files are merged at compile time.
The second one doesn't work because @import is a CSS function and your browser will try to load the path that's outside of the src folder.

This is not a bug.

**Comment by rstropek** [comment]
Let me first describe why we think the problem is important: We faced the problem when using Kendo UI for Angular 2 with Angular CLI. Their SCSS styles are in the `node_modules` folder (`@telerik/kendo-theme-default` package). Inside their SCSS files, they reference e.g. fonts with relative urls. As a result, importing the Kendo UI styles does not work. Webpack fails because it cannot find the fonts. You can find more details about the Kendo UI SCSS approach in their GitHub repository at https://github.com/telerik/kendo-theme-default

I have created my small repro app to demonstrate the basic problem. The app doesn't make much sense. However, it shows that the problem we have with Kendo can be reproduced in a much smaller sample without the complexity of Kendo UI.

You write that the browser tries to load something. I don't think that's the problem. The error is thrown at compile time (`ng serve` or `ng build`) by Webpack. Webpack cannot find the resource and therefore it cannot create the bundle correctly. As far as I understand, Webpack recognizes `url`s in SCSS and tries to bundle the referenced resources.

**Comment by grizzm0** [comment]
Using the package from node_modules works just fine. You'll just have to override all paths.

I've got this in my style.scss. 
```scss
$flag-icon-css-path: '~flag-icon-css/flags' !default;
@import "~flag-icon-css/sass/flag-icon";

$image_path: '~material-design-lite/src/images' !default;
@import "~material-design-lite/src/material-design-lite";
```

**Comment by rstropek** [comment]
Awesome, thank you. I could apply your tip to the Kendo styles. It works for most of their controls. However, they have two controls where you cannot override paths and their docs are incomplete. I will file and issue in their GitHub repo.

Thanks again for your help!
