### ISSUE TITLE
this.selectOrCreateHostElement is not a function

### ISSUE THREAD

**Issue by mattma** [angular/angular-cli#2988]
```
MacOS Sierra 10.12
Angular-cli  v1.0.0-beta.19
node: 6.9.1
```

I have fixed all outstanding compiling issues in my code. When I run `ng build --prod --aot` in the root of my Angular 2 application, webpack successfully compile out a `dist` folder with application files. 

I run a local server to serve the `dist` folder, then I run into this issue. 

```
EXCEPTION: this.selectOrCreateHostElement is not a function

Error: Uncaught (in promise): TypeError: this.selectOrCreateHostElement is not a function
```

I have searched all over the angular and angular cli docs, but I still could not find a solution.  Is it a known issue?

**Comment by deebloo** [comment]
@mattma try updating to beta.19-3 and see if you still have the same issue. there were some deployment issues with 19.

**Comment by mattma** [comment]
@deebloo I am using the "symlink" to local angular-cli `master` branch. In my project `package.json`, it has `angular-cli.beta.19-3` defined due to `angular-cli.beta.19` is not registered on NPM registry. 

I believe i am using the latest `angular-cli.beta.19-3` codebase and experience this issue. thanks

**Comment by filipesilva** [comment]
I have no idea what that error means. If you can get me a basic repro, I can look into it.

**Comment by matthewhegarty** [comment]
FWIW I had a similar issue using `bs3-ng2-modal` (`TypeError: this.$modal.modal is not a function`).  I solved it by adding required script (bootstrap.js) to scripts declaration.  See [this issue](https://github.com/dougludlow/ng2-bs3-modal/issues/116)

**Comment by mattma** [comment]
@filipesilva I use d3 v4. I believe it is d3 selection issue, not an Angular or CLI issue. I am glad that I can eliminate the problems and isolated down. I have not found the root cause yet. Will report if I do. Thanks all.
