### ISSUE TITLE
Add support for "--watch-poll" webpack-dev-server flag to ng serve

### ISSUE THREAD

**Issue by CamusAran** [angular/angular-cli#2991]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu Trusty Tahr (14.04) [LTS] 64 vagrant guest OS on Windows 10 host.

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.19-3
node: 6.4.0
os: linux x64

The file change detection isn't working with ng serve in vagrant on a Windows host. I've had the same issue using Browsersync and fixed it using "usePolling" in "watchOptions".
There is a similar configuration option in webpack.config.js but you can't edit that in angular-cli, so how about adding support for the "--watch-poll" flag to ng serve instead?

According to these comments "--watch-poll" should fix the issue:
https://github.com/webpack/webpack-dev-server/issues/155#issuecomment-159140735
https://github.com/webpack/webpack-dev-server/issues/324#issuecomment-241204865
http://stackoverflow.com/a/34937378

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/1814. There's no documentation for this feature thogh, which is unfortunate.
