### ISSUE TITLE
"ng build" does not bail on an error where "environment.dev.ts" is not found

### ISSUE THREAD

**Issue by huyph** [angular/angular-cli#2993]
### OS?
Mac OSX - EL Capitan

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 6.4.0
os: darwin x64

### Repro steps.
- Have a standard angular-cli setup in place
- Remove "environment.dev.ts"
- Run "ng build --dev"

It will generate an error complaining "environment.dev" is not found. But the build does not exit with failure, instead it continues and completes.

### The log given by the failure.
```javascript
....
ERROR in ./src/environments/environment.ts
Module build failed: Error: ENOENT: no such file or directory, open '<path>/src/environments/environment.dev.ts'
    at Error (native)
 @ ./src/main.ts 4:0-57
 @ multi main
.....
.....
(Completes and Exits with successful code)
```

**Comment by filipesilva** [comment]
That's a bug. Odd little thing, will look into it.

**Comment by josersleal** [comment]
Hi this is happening on my code with version 1.0.0-beta.28.3

**Comment by filipesilva** [comment]
This should now be fixed.
