### ISSUE TITLE
Production build without compression

### ISSUE THREAD

**Issue by JoshuaNovak919** [angular/angular-cli#2995]
Is there a way to make a production build without compression, or at least without uglifying the code?

**Comment by piernik** [comment]
As far as I know `ng build` will build app without uglyfing and compression.

**Comment by clydin** [comment]
That will do a dev build so there will be other differences as well. For global stylesheet handling, you're going to get a js bundle instead of css.  Output filenames will have no hashes.  Probably some others as well.

Also, your builds will be significantly larger without the minification step.

**Comment by JoshuaNovak919** [comment]
Basically I want the JS bundled, but no uglifying on the index HTML or the CSS.

**Comment by clydin** [comment]
The CLI is meant to be an opinionated build system.   So if you're interested in full control, it's probably not what your looking for.

In regards to what you want, index.html is not minifying or compressed currently.  Component CSS is bundled with their respective component's JS.  Global CSS will be combined and minifying in production builds.  (In development builds they will be combined into a JS bundle).

**Comment by filipesilva** [comment]
What @clydin said is very accurate. I can also say that as far as future plans are concerned, we aren't looking specifically at adding this toggle but it might happen if we end up giving more granular build control overall.

**Comment by JoshuaNovak919** [comment]
It would be good if the files could at least be in folders or something. Most clients complain about having one folder full of fonts, images, scripts, and styles. If they were at least broken into folders it would be less of a mess. Is there anyway to have it keep the folder structure or have a folder structure?
