### ISSUE TITLE
Create a library with angular-cli

### ISSUE THREAD

**Issue by enricosecondulfo** [angular/angular-cli#2996]
Hello guys,
Can I create a library with angular-cli? 

Thanks

**Comment by stevermeister** [comment]
not yet, but it's already in the list

**Comment by enricosecondulfo** [comment]
Thank you so much for the answer

**Comment by filipesilva** [comment]
See https://github.com/angular/angular-cli/issues/1692, but as @stevermeister said it's on the list of important features.
