### ISSUE TITLE
Can't set test threshold for TypeScript files

### ISSUE THREAD

**Issue by marsis** [angular/angular-cli#3002]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
>  Linux Ubuntu 16.04

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
App was created using CLI

### The log given by the failure.
> Normally this include a stack trace and some more information.

Istanbul's reports doesn't match karma-coverage reports . I need to set test threshold for unit tests in typescript files. I installed karma-coverage, but it creates reports with test coverage for javascript files. Threshold compares with  coverage for javascript files and I receive unreliable information 

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
If I remember correctly, just using `karma-coverage` wasn't enough because code needed to be instrumented as it is compiled, before hitting the karma plugin. 

I'm not too familiar with this threshold functionality though, so not sure what we can do. A bit of a shot in the dark, but does https://github.com/angular/angular-cli/issues/1735 help?

**Comment by tuhoojabotti** [comment]
We're also wondering about this. With karme-coverage you can set the `check`-object to add coverage thresholds, but the karma-remap-istanbul does not seem to support this.

Has anyone managed to configure coverage thresholds?

**Comment by filipesilva** [comment]
Newer versions of `karma-coverage-instanbul-reporter` seem to have threshold related functionality: https://github.com/angular/angular-cli/pull/5519
