### ISSUE TITLE
Karma browser plugin doesn't seem to work

### ISSUE THREAD

**Issue by Njoror** [angular/angular-cli#3004]
### OS?
Windows 7

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 7.0.0
os: win32 x64

### Repro steps.
This was done with the default project generation. I did not change anything.

### Mention any other details that might be useful.
```
03 11 2016 10:17:35.832:WARN [karma]: No captured browser, open http://localhost:9876/
03 11 2016 10:17:35.847:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
03 11 2016 10:17:35.848:INFO [launcher]: Launching browser Chrome with unlimited concurrency
03 11 2016 10:17:35.852:INFO [launcher]: Starting browser Chrome
03 11 2016 10:17:37.267:INFO [Chrome 54.0.2840 (Windows 7 0.0.0)]: Connected on socket /#s2NnXGzzPGkQzyf6AAAA with id 13289535
Chrome 54.0.2840 (Windows 7 0.0.0): Executed 3 of 3 SUCCESS (0.16 secs / 0.154 secs)
```

The tests run fine in the CLI, but when it opens the browser I get the Connected screen and nothing else. Here is a screenshot: http://i.imgur.com/AfjG4mw.png

Clicking on the debug button just brings me to a page that says *app works!*

**Comment by filipesilva** [comment]
This is how it's supposed to look like. At least that's how all Karma runs look for me. If it's supposed to look differently let me know and I'll have a look.
