### ISSUE TITLE
ng build not get styles.css to dist/

### ISSUE THREAD

**Issue by otrifo** [angular/angular-cli#3006]
### OS?
Mac OSXEl Capitan

### Versions.
 "angular-cli": "1.0.0-beta.19-3",
 node : 6.3.1

### Repro steps.
App was created with CLI with CSS support. angular-cli.json file:
"styles": [
        "styles.css"
      ],

### The log given by the failure.
 Scripts are not loaded to dist folder.  But, images and fonts are loaded from the assets.
The assets (images and fonts) are correctly output to the '/dist' folder. It's just that the script never output to dist folder.

 Thanks :)

**Comment by grizzm0** [comment]
What do you mean by scripts? Do you mean styles?

In beta-19 all styles in the style array gets compiled into style.*.js which then is copied over to `<head>` at runtime. In the next beta release there will be an actual .css file instead. See #2646

**Comment by filipesilva** [comment]
^ what @grizzm0 said 💃
