### ISSUE TITLE
fix: declare ROUTER_PROVIDERS on root component rather than bootstrap

### ISSUE THREAD

**Issue by cburgdorf** [angular/angular-cli#301]
According to [this style guide](https://github.com/mgechev/angular2-style-guide/blob/4e1b26d6466883d18ceae65bbb28fc4da85236ef/README.md) it's a best practice to declare the providers on the root component rather than the bootstrap.

**Comment by filipesilva** [comment]
We're actually waiting for a definite style guide to change all the blueprints to something a little better structured, which is why these providers are still in the bootstrap.

That being said, I won't say no to a PR fixing this bit for now.

**Comment by cburgdorf** [comment]
Ah ok. Feel free to close the PR if you rather like to wait on a definite style guide. I sent the PR as we are teaching people to not maintain providers in the `bootstrap` in our thoughtram training. We are soon switching over to use angular-cli in our workshops hence I though I sent a PR for this change.

**Comment by filipesilva** [comment]
Really? That's great news for the CLI! 

I hope you come back to the cli repo with a lot of tasty feedback from your trainees :D
