### ISSUE TITLE
relative imports not supported with i18n

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#3015]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
$ ng --version
angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

- Added baseUrl for relative imports
- Relative import in a component, e.g. import { TermsAndConditions} from 'app/termsandcondition'
- ng serve works fine.
- Adding i18n attribute and running ng-xi18n:
$ ng-xi18n
Error: Unexpected value 'TermsAndConditions' exported by the module 'SharedModule'

**Comment by filipesilva** [comment]
@rolandoldengarm can you open this on https://github.com/angular/angular instead? The CLI doesn't yet have i18n integration.
