### ISSUE TITLE
Windows ngtools/webpack AoT compilation hangs infinitely at 95% emitting

### ISSUE THREAD

**Issue by mariussl** [angular/angular-cli#3019]
### OS
Windows 7 x64

### Versions

angular-cli: 1.0.0-beta.18
node: 5.10.1
os: win32 x64

and after upgrading

angular-cli: 1.0.0-beta.18
node: 6.9.1
os: win32 x64

### Repro steps.
[I set up a repo with a testcase and description here](https://github.com/mariussl/ngtools-webpack-winbug).

In short: On Windows7 webpack aot compilation hangs indefinitly on "95% emitting". I did some debugging and finally wound up in webpack/lib/Compiler.js Compiler.prototype.emitAssets line 288.. . It seems that the path for the source-map file is generated incorrectly by concatenating 2 absolute paths in line 310: this.outputFileSystem.join(outputPath, dir) . This leads to an endless loop of failed directory creations and hangs the compilation process.

Removing devtool from the webpack configuration solves the problem (albeit loosing the source-map). Further testing shows that replacing styleUrls with styles in app.component.ts also solves the problem (albeit loosing the external css file).

### The log given by the failure.
 66% building modules 468/474 modules 6 active ...node_modules\rxjs\util\errorOb
 66% building modules 468/475 modules 7 active ...ules\rxjs\util\UnsubscriptionE
 66% building modules 469/475 modules 6 active ...ules\rxjs\util\UnsubscriptionE
 66% building modules 470/475 modules 5 active ...ules\rxjs\util\UnsubscriptionE
 66% building modules 471/475 modules 4 active ...ules\rxjs\util\UnsubscriptionE
 66% building modules 472/475 modules 3 active ...ules\rxjs\util\UnsubscriptionE
 66% building modules 473/475 modules 2 active ...ules\rxjs\util\UnsubscriptionE
 66% building modules 474/475 modules 1 active ...ules\rxjs\util\UnsubscriptionE
 95% emitting

### Mention any other details that might be useful.

The bug was reproducable on another Windows7 development system.

### Update, 2016-12-16

I upgraded to @ngtools/webpack 1.1.9 and the bug is still there. But I found a workaround by switching from css to less: In webpack.config.js: 
```javascript
{ test: /\.less$/, loaders: ['to-string-loader', 'css-loader', 'less-loader']},
```
And in app.component.ts:
```javascript
styleUrls: ['./app.component.less']
```
Works for me so far.

### Update, 2017-01-04

I updated to node 6.9.3 and npm 4.1.1. Additionally I upgraded @angular, @ngtools and various dependecies (see [package.json in test repo](https://github.com/mariussl/ngtools-webpack-winbug/blob/master/package.json)).

Result: Still hangs at 95€ emitting.

**Comment by yurlovm** [comment]
+1

**Comment by unsafecode** [comment]
+1

**Comment by carol-braileanu** [comment]
+1

**Comment by kamarouski** [comment]
Have the same issue here with ngtools 1.2.1 & webpack 2.1.0-beta.25 

The process hangs on 95% when referencing SASS files for components. That's pretty much a show stopper for us to using AoT compilation :(

**Comment by drooks** [comment]
I had this issue and was able to fix after:

- updating node to 6.9.2 https://nodejs.org/en/
- updating npm `npm install npm@latest -g`

Hope this helps

**Comment by mariussl** [comment]
> I had this issue and was able to fix after:
> updating node to 6.9.2 https://nodejs.org/en/
> updating npm npm install npm@latest -g

I updated to node 6.9.3 and npm 4.1.1. Additionally I upgraded @angular, @ngtools and various dependecies (see [package.json in test repo](https://github.com/mariussl/ngtools-webpack-winbug/blob/master/package.json)).

**Result: Still hangs at 95€ emitting.**

**Comment by sustwater** [comment]
+1

**Comment by dobbydog** [comment]
I've found that it's caused by component style's source maps. Webpack tries to emit something like
`C:\Users\***\project\dist\C:\Users\***\project\some\component\style.css.map`
but it's invalid in windows. So stopping sourcemaps fixes this temporarily.

**Comment by kamarouski** [comment]
Still have this issue with the latest ngtools and webpack

Environment:
OS: Windows 10 x64
Node: v6.9.5\v7.5.0
Webpack: 2.2.1
@ngtools\webpack: 1.2.8

Webpack hangs indefinitely on 95% emitting phase.

**Comment by minagawah** [comment]
me too
I downgraded my NodeJS to see what it happens. No luck...
Still stops silently saying "emitting".

OS: Windows 10 x64
Node: v6.9.2
Webpack: v2.2.1

I thought it has to do with the reserved character issue
with my "config.output.path" having "C:\\" but I'm not sure.

```
path: path.resolve(__dirname, 'build')
```

I'm running `webpack-dev-server --env.dev --progress --profile --colors` with my config:

```
devtool: process.env.WEBPACK_DEVTOOL || 'eval-source-map',
devServer: {
	contentBase: path.join(__dirname, 'build'),
	host:		process.env.HOST || '127.0.0.1',
	port:		process.env.PORT || '8080',
	historyApiFallback: true,
	noInfo:		true
}
```

**Comment by mariussl** [comment]
I updated @ngtools/angular to version 1.2.9. Now it works. Bug closed.

**Comment by kamarouski** [comment]
Updated to 1.2.9 and still the same. Works fine without SASS, though hangs right after including reference to a sass file.

@mariussl Can you please share your webpack and tsconfig.

**Comment by mariussl** [comment]
@kamarouski : Just have a look at the [repo with the testcase](https://github.com/mariussl/ngtools-webpack-winbug). You can verify that it works and examine the config.

**Comment by bstaley** [comment]
@mariussl I pulled down your repo and it worked until i swapped out the raw-loader on the css rule to a style-loader. This change produced the `95% emitting` freeze for me.

**Comment by dobbydog** [comment]
@bstaley Components styles (and templates) need to be loaded with raw-loader. If you need to use style-loader for other styles, you should change rules like this
```
{
  test: /\.component\.css$/,
  use: ['raw-loader']
},
{
  test: /\.css$/,
  exclude: /\.component\.css$/,
  use: ['style-loader']
},
```

**Comment by kamarouski** [comment]
@mariussl the test case uses css not sass. I'll try to change it to sass to see if the issue can be reproduced.

**Comment by MarkPerryBV** [comment]
@dobbydog Thank you so much for this. I had been following an ngTool/webpack error for DAYS!!!

Turned out it was the `styleUrls` in the @component decorators causing the bug. Your comment just helped me fix it.

**Comment by nitimmerman** [comment]
@kamarouski I've tested this last week with sass and it looks like this library still has problems with handling SASS files. Does anyone know if there's a change that this will be fixed?

**Comment by mcm-ham** [comment]
I'm experiencing this with SASS files with AOT build. In `mkdirP` I added a console.log and see that all the invalid paths are like this:
```
c:\output\c:\component
```

**Comment by JohnGalt1717** [comment]
@mcm-ham me too! Any work around?

**Comment by olezt** [comment]
For me after 2 days, I found that I had to manually install "node-sass" and add these loaders (also for node modules):
`    resolve: {
        extensions: ['.ts', '.js', '.json']
    },`

`{
                test: /\.css$/,
                use: [
                    'style-loader',
                    'css-loader'
                ]
            },
            {
                test: /\.scss$/,
                use: [
                    'raw-loader',
                    'sass-loader'
                ]
            }`
