### ISSUE TITLE
Add poll documentation

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#3020]
The CLI has an undocumented poll option that helps in some environments, such as Vagrant. We should document it. 

PRs for reference: https://github.com/angular/angular-cli/pull/1814, https://github.com/angular/angular-cli/pull/1837, https://github.com/angular/angular-cli/pull/2486.

**Comment by sumitarora** [comment]
Closing has been added to the documentation.

**Comment by proverbed** [comment]
Good day, where is this documentation?

**Comment by proverbed** [comment]
Got it: `defaults.poll`

https://github.com/angular/angular-cli/pull/1814/files
