### ISSUE TITLE
Has anyone integrated a angular-cli project with a .net core application?

### ISSUE THREAD

**Issue by minuz** [angular/angular-cli#3025]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS
> Windows 10

### Question
> I have a requirement where I need the main application to be a .net core app but part of the application will be developed with Angular 2. So I was wondering if any of you ever tried to do this integration. I have been able to integrate using SystemJS (Using the Angular 2 Quick Start) but I would like to use the structure provided by the CLI scaffolding project. At the moment, my issue is to load the `main.js` into the `.cshtml`
Can anyone help me out please?

**Comment by Daxaar** [comment]
Have you taken a look at the ASP.NET Core - Angular 2 yeoman generator?  Even if you choose not to use the final generated output it may provide some guidance on project & file setup.

**Comment by wendelstam** [comment]
Since I wanted the application to use the prod builds with cache busting suffixes I pointed the CLI config to an empty .html file which then gets filled with the script tags as index.html in the dist folder. I then load and append that file to the .cshtml in the appropriate location through the MVC controller action and razor.

Its perhaps not the cleanest solution but it solved that problem for me.

**Comment by filipesilva** [comment]
I can't answer myself but flagged it for community help.

**Comment by tomeeraerts** [comment]
maybe this blog post can help you?
[Angular2 CLI with ASP.NET Core application - tutorial](https://devblog.dymel.pl/2016/10/25/angular2-cli-with-aspnet-core-application-tutorial/)

**Comment by minuz** [comment]
@tomeeraerts thanks for the article! I have been able to achieve what I was after using this tutorial as base idea.

@Daxaar This structure also helped me to understand a few things. 

Thanks for the help guys.

**Comment by filipesilva** [comment]
Cool, glad to hear you got it sorted, and thanks for the wonderful community help!

**Comment by davidreher** [comment]
I am now using this setup here: https://dustinewers.com/angular-cli-with-net-core/

**Comment by ShyamK39** [comment]
I got one running with usespa and stuff - check out the project template for angular look in start.cs and try the usespa with the dir setting and so on
