### ISSUE TITLE
Not working with Bash on Ubuntu for Windows

### ISSUE THREAD

**Issue by timmythetiny** [angular/angular-cli#3028]
### OS?
Windows 10, running commands in the new Bash interface.  

### Versions.
> Supplying --version produces the same error text as anything else, though I did install it from NPM as of 5 November 2016 so it should be the latest.  

### Repro steps.
This is simply installing the CLI with Node 7.0.0 and NPM 3.10.8 and trying to use any commands.  Following the same steps on my Mac was successful.  

### The log given by the failure.
/usr/local/lib/node_modules/angular-cli/node_modules/portfinder/lib/portfinder.js:395
  var interfaces = os.networkInterfaces(),
                      ^

Error: EINVAL: invalid argument, uv_interface_addresses
    at /usr/local/lib/node_modules/angular-cli/node_modules/portfinder/lib/portfinder.js:395:23
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/portfinder/lib/portfinder.js:410:2)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:7:19)

### Mention any other details that might be useful.
I received the following warnings during installation:
npm WARN deprecated graceful-fs@1.2.3: **graceful-fs v3.0.0 and before will fail on node releases >= v7.0**. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional Skipping failed optional dependency /angular-cli/chokidar/fsevents:
npm WARN notsup **Not compatible with your operating system or architecture: fsevents@1.0.15**

I've bolded the two that look most concerning to me.  Note that I use Node 7.0.0 with my Mac install of the CLI as well and I run into no issues.  

Let me know if there is any more information I can offer.

**Comment by filipesilva** [comment]
You'll have to open this on the Bash for Windows tracker, it seems like a problem with it instead of with Angular-CLI. This project works in Windows, Linux and OSX. If it doesn't work with Bash for Windows, that seems a specific issue of that project.

**Comment by jacquesdev** [comment]
For what it's worth, I have just upgraded to Ubuntu 16.10, and also suddenly getting the error:
`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15`

**Comment by figuerres** [comment]
I just ran into this and will be interested to see if the change fixes it...

**Comment by mattmcardle** [comment]
I'm still running into this issue with the updated version of portfinder, has anyone been able to resolve it or do we have to wait for the creator update for windows 10 to fix memory issues? - as this thread suggests: https://github.com/angular/angular-cli/issues/3944
