### ISSUE TITLE
Use Webpack Proxy Bypass function

### ISSUE THREAD

**Issue by mildfuzz** [angular/angular-cli#3029]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
1.0.0-beta.19-3

### Mention any other details that might be useful.

I want to use the webpack proxy bypass function, but the config file is a JSON document, so does not support methods. Happy to have a work around if one is available. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by timmythetiny** [comment]
In case you haven't found it already, this walkthrough should do you well: https://github.com/angular/angular-cli#proxy-to-backend.

**Comment by mildfuzz** [comment]
thanks, I did find that
