### ISSUE TITLE
No Coverage folder created when running unit tests

### ISSUE THREAD

**Issue by daBishMan** [angular/angular-cli#3031]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.19-3
node: 6.5.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Yes, this project was created using the cli.  
No changes to the code at all .  
run `ng test`
No coverage folder for instanbul

### The log given by the failure.
> Normally this include a stack trace and some more information.
no error 

### Mention any other details that might be useful.
> C:\dabishman\ng2-material-demo>ng test
05 11 2016 15:46:54.037:WARN [karma]: No captured browser, open http://localhost:9876/
05 11 2016 15:46:54.049:WARN [karma]: Port 9876 in use
05 11 2016 15:46:54.054:INFO [karma]: Karma v1.2.0 server started at http://localhost:9877/
05 11 2016 15:46:54.055:INFO [launcher]: Launching browser Chrome with unlimited concurrency
05 11 2016 15:46:54.134:INFO [launcher]: Starting browser Chrome
05 11 2016 15:46:55.435:INFO [Chrome 54.0.2840 (Windows 10 0.0.0)]: Connected on socket /#YlJzeVl6pKZjtOagAAAA with id 60490789
Chrome 54.0.2840 (Windows 10 0.0.0): Executed 3 of 3 SUCCESS (0.155 secs / 0.151 secs)

> Thanks! We'll be in touch soon.

**Comment by VilleSalonen** [comment]
Code coverage analysis is disabled by default. You should run `ng test --code-coverage`.

**Comment by daBishMan** [comment]
@VilleSalonen  thank you so much for your reply.   I will check this out.   The reason this is confusing to me, at work we are running CLI beta-15 and it generates the code coverage automatically.  I tried this at home using CLI Beta-19 and they do not generate.  

Do you mind telling me when this option change if you know.  I will try to read the change log and see if I missed it.  

Thanks again.
