### ISSUE TITLE
allow overriding `bailMode`

### ISSUE THREAD

**Issue by tycho01** [angular/angular-cli#3034]
`angular-cli` hardcodes webpack's `bail` setting as [`true`](https://github.com/angular/angular-cli/blob/master/packages/angular-cli/tasks/build-webpack.ts#L30), which cancels any build while there are remaining TS errors.
I find this unfortunate as TypeScript is [imperfect](https://esdiscuss.org/topic/es8-proposal-optional-static-typing#content-8), meaning there may be cases where it would be significantly harder to fully resolve all TS errors, while functionality may be just fine.
I understand that bail mode has significant advantages (error codes) as well. Would it perhaps be an option to allow having certain/general webpack settings overridden by the user using `angular-cli.json` somehow?
I'm actually a bit surprised I hadn't found things about extending webpack settings yet, as this might make ng-cli more flexible in general, hopefully allowing the user to add Pug/Less/Stylus at will as well (without having to bloat ng-cli with additional dependencies).
Thoughts?

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/2879.
