### ISSUE TITLE
Using Angular 1.5 directives in an angular-cli

### ISSUE THREAD

**Issue by dolanmiu** [angular/angular-cli#3037]
Is this possible?

I am currently in a migration process from Angular1 to Angular2 and want to slowly upgrade.

We want to include the Angular1 directives into the angular-cli project first, then convert them after, as our Angular1 app is pretty big

**Comment by filipesilva** [comment]
Heya @dolanmiu, my advice is that you follow https://angular.io/docs/ts/latest/guide/upgrade.html to upgrade your app. 

The CLI doesn't give any specific upgrade support as it is out of scope for us. You might be able to make it work with good use of the [global libs](https://github.com/angular/angular-cli#global-library-installation) functionality, but you might run into problems doing it with the CLI.
