### ISSUE TITLE
AOT build fail if there's no semicolon at the end of ViewChild() declaration

### ISSUE THREAD

**Issue by thibaultsavary** [angular/angular-cli#3040]
### OS?
> Windows 10

### Versions.
>beta.19-3

### Repro steps.
Doesn't work
`@ViewChild('some') some`
Works
`@ViewChild('some') some;`

### The log given by the failure.
> not useful

### Mention any other details that might be useful.
Not using semicolon at end of declaration for @ViewChild causes AOT build to fail.
Found this information on stack-overflow after hours...

Can something be done about that please ?
For those of us who don't use semicolon.

**Comment by deebloo** [comment]
@thibaultsavary I doubt this is a cli issue. it may be a angular compiler issue. @filipesilva I seem to recall this issue popping up before, was it the aot compiler?

**Comment by thibaultsavary** [comment]
Yeah, I guess it make sense that the problem may be coming from the AOT compiler itself. It may not have ASI built-in, it also can be some kind of manipulation of the code by the cli before compilation. Honestly absolutely no idea of the internals of the build chain.

I'll wait an answer from someone in the cli team, then if it's confirmed that this is a problem from the compiler I'll close this issue and open a new one on the angular repository.

**Comment by filipesilva** [comment]
I don't know what caused this originally, but I can't repro it in the latest CLI nor outside of it. I suspect it was a problem in a older version of `ngc` that has been fixed since.

This is the component I used to test:
```
import { Component, ViewChild } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @ViewChild('some') some: any
  title = 'app works!';
}
```
