### ISSUE TITLE
Node Sass Upgrade for WIndows 10 Node v7

### ISSUE THREAD

**Issue by markheron91** [angular/angular-cli#3041]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10 64 bit

### Versions.
> angular-cli: 1.0.0-beta.19-3
node: 7.0.0
os: win32 x64

### Repro steps.
> Try to run an ng serve command using the setup provided above. Console complains about an unsupported runtime

### The log given by the failure.
> ERROR in ./src/app/setup/skin/list/skin-list.component.scss
Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (51) For more information on which environments are supported please see: https://github.com/sass/node-sass/releases/tag/v3.10.1

### Mention any other details that might be useful.
On the node-sass github it states that v3.11.1 supports all node versions on all os apart from FreeBSD - it would be good for the dependency in the repo to be updated to support the newest version of node.
https://github.com/sass/node-sass/issues/1766
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wulfsberg** [comment]
Be aware that you'll break on Node 7 anyway: #837

**Comment by Brocco** [comment]
The node-sass dep has been updated. Also, while we have tests for node 7, it is not officially a supported node version, yet.
