### ISSUE TITLE
I can't debug in chrome after upgrading to beta 14.0

### ISSUE THREAD

**Issue by ElanMu** [angular/angular-cli#3043]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
>angular-cli: 1.0.0-beta.17
  node: 6.5.0
  os: win32 x64

### Repro steps.
> When I upgrading the beta of cli to 14.0, I use 'ng serve',there is only the compress file  in chrome.
So I can't debug when I am developing.

### The log given by the failure.
> Normally this include a stack trace and some more information.
![image](https://cloud.githubusercontent.com/assets/22315478/20052485/29121072-a50f-11e6-89ca-f7097b3f6200.png)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by neilhem** [comment]
Try to update to the latest version `npm i -g angular-cli@1.0.0-beta.19-3`

**Comment by ValeryVS** [comment]
Original files are in "webpack://". Last menu item at your screenshot.

**Comment by JJkip** [comment]
I upgraded to cli 1.0.0-beta.19.3 and faced the issue of Page reload and refresh of content not working. #3064

**Comment by ElanMu** [comment]
Thanks all! I found the original file.

**Comment by intellix** [comment]
Still getting this: https://github.com/angular/angular-cli/issues/3080

**Comment by filipesilva** [comment]
Closed as it seems solved.
