### ISSUE TITLE
Importing heroku env variables

### ISSUE THREAD

**Issue by XPilot** [angular/angular-cli#3044]
### Issue story ###

```
As a FE developer
I need to be able to import system variables added in heroku
So that I can provide API keys dynamically based on dyno environment
```

### Additional information ###

I would like to know if there's any chance to send variables via node command line such as:

```
ng build --target=production --env=prod --myvar=1 --myvar2=2
```

This should be either as node args or via a an external file while not touching the existing environment files. 

The addition should not create any additional files in the process and should use pre-existing hooks combined with webpack DefinePlugin methodology

Thank you

**Comment by filipesilva** [comment]
The functionality we have for this scenario is environment files: https://github.com/angular/angular-cli#build-targets-and-environment-files
