### ISSUE TITLE
ng completion command fails

### ISSUE THREAD

**Issue by the-destro** [angular/angular-cli#3048]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> macOS Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.19-3
node: 5.0.0
os: darwin x64

### Repro steps.
ng completion 1 >> ~/.bashrc 2>>&1

### The log given by the failure.
-bash: syntax error near unexpected token `&'

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by the-destro** [comment]
doing `ng completion 1 >> ~/.bashrc` seems to achieve the desired result. Bash version on Sierra is 
```bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.```

**Comment by catull** [comment]
Confirmed that there is a difficulty with bash 4.4.0 which shows the same error (bash: syntax error near unexpected token `&').

There are two solutions.
1. as suggested by @the-destro, using `ng completion 1>> ~/.bashrc` or `ng completion >> ~/.bashrc`.
2. Drop the extra '>' after the 2, like so `ng completion 1 >> ~/.bashrc 2>&1`

This was already suggested in PR #3319 with https://github.com/angular/angular-cli/pull/3319/commits/927d3345dbae1be2760606c30f51cc92584dd955

Turn out, zsh exhibits the same error with "2>>&1".
Will incorporate the fix in my PR #3981.

**Comment by catull** [comment]
The clean solution is to not capture std error at all, this the call becomes `ng completion 1>> ~/.bashrc`.   Or `ng completion 1>> ~/.zshrc`.

**Comment by filipesilva** [comment]
I believe this is now fixed, @catull did a bunch of great work around the completion command.
