### ISSUE TITLE
If project root contains firebase.json, copy it to dist/ upon building

### ISSUE THREAD

**Issue by jelbourn** [angular/angular-cli#305]
The presence of a `firebase.json` file indicates that the app is hosted on firebase. It would be very convenient to simply copy that file, if it exists, to the `dist/` directory in order to deploy from there.

**Comment by zackarychapple** [comment]
Maybe we should also be generating the `firebase.json` if a firebase project is selected.  Kind of how Ionic does `ionic install ios` we can use `ng install firebase` or `ng deploy firebase`

**Comment by filipesilva** [comment]
Following the example of https://github.com/IgorMinar/angular-cli-github-pages, I suppose we'll have a `ng firebase:deploy` via addon.

**Comment by hansl** [comment]
@jelbourn do you need the `firebase.json` file to be at the root of the project?

**Comment by jelbourn** [comment]
Not _need_, but that seems like the most natural place to put it

**Comment by filipesilva** [comment]
This is solved by putting `firebase.json` in the `public/` dir, the contents of which are directly copied to `dist/` root.
