### ISSUE TITLE
why not compress when run "ng build"

### ISSUE THREAD

**Issue by wqdjl** [angular/angular-cli#3053]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> 
angular-cli: 1.0.0-beta.19-3
node: 6.2.0
os: win32 x64

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
As the README states `ng build` defaults to the development target.  The production target (`ng build --prod`) optimizes and compresses the output.

**Comment by wqdjl** [comment]
ok,Thanks
