### ISSUE TITLE
No install angular-cli node -v 4.2.6 npm 3.5.2

### ISSUE THREAD

**Issue by joelunmsm2003** [angular/angular-cli#3055]
I can not install angular-cli

Debian GNU/Linux 8 
node -v
v4.2.6
npm
3.10.9
npm install -g angular-cli

npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/root/.nvm/v4.2.6/bin/ng -> /root/.nvm/v4.2.6/lib/node_modules/angular-cli/bin/ng

> execSync@1.0.2 install /root/.nvm/v4.2.6/lib/node_modules/angular-cli/node_modules/execSync
> node install.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/root/.nvm/v4.2.6/lib/node_modules/angular-cli/node_modules/execSync/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:245:9)
[               ...] | install: info lifecycle execSync@1.0.2~install: Failed to exec install script

**Comment by B0BBB** [comment]
me neither... following

**Comment by joelunmsm2003** [comment]
i solved when changed Ubuntu 14

**Comment by filipesilva** [comment]
This seems to be a problem with the nvm setup. There isn't much we can do here, the install itself is mostly out of our hands.
