### ISSUE TITLE
in ng serve, specify different angular-cli name or directory

### ISSUE THREAD

**Issue by vrustia-owens** [angular/angular-cli#3057]
Can we allow to specify a different file name for angular-cli.json or different directory aside from the project root when running command line such as NG SERVE?

e.g.

`ng serve /build/admin/angular-cli.json`

This is already possible with webpack and rollup. This make sense if one project codebase has multiple independent business modules and multiple deployment configuration as well.

Or do you have already an existing solution to this which is different from what I expected?

**Comment by filipesilva** [comment]
We aren't currently looking at supporting different `angular-cli.json` for a single project. We do plan to extend it to support several apps in in the same config though, but that's a medium term goal.

**Comment by chrisalexander55** [comment]
+1

**Comment by garysb** [comment]
+1 from me too. This to me is almost a core requirement for any app. Let us specify the config file please.

**Comment by hawaiikaos** [comment]
+1 from me. Using docker as well.
