### ISSUE TITLE
ng serve with aot paused at 20% of building

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#3058]
I'm using beta19-3 and I run my webapp with "ng serve --aot --prod" but the compilation stop at this step :  ` 20% building modules 89/89 modules 0 active ` 

Without any errors and I just have this module in my project: https://github.com/swimlane/angular2-data-table/tree/master/release  

Does it due to this 3th party lib error durning `ngc` 

thanks

**Comment by istiti** [comment]
I find error when running ng build --aot ..... you can close this issue ASAP but still not understand why I don't have same error when running "ng serve"

in my code I had: 
```
    @HostBinding() get setSome(){
        console.log('binding')
        return true;
    }
```

Yes I know this code is not correct but I expect from cli to get me error... it freezed at 20% .... 

thanks

**Comment by movingbytes** [comment]
Maybe you don't have installed all used packages.
