### ISSUE TITLE
Ng Core Addons postinstall failure: Exit Status 1

### ISSUE THREAD

**Issue by Foobin** [angular/angular-cli#3060]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Ubuntu 16.04 LTS

### Versions.
> v6.9.1

### Repro steps.
> I created a new app using `ng new my-project` using the default template and got an installation error with ng-core-addons

### The log given by the failure.
> npm ERR! ng-core-addons@0.0.9 postinstall: `node ./node_modules/fs-concatenate -i content -o snippets.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng-core-addons@0.0.9 postinstall script 'node ./node_modules/fs-concatenate -i content -o snippets.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng-core-addons package,

### Mention any other details that might be useful.
Running ng --version inside the app after installation throws an error; 'cannot find module ... node_modules/ng-core-addons'
> ---------------------------------------------------------------

I'm new to reporting errors on Github, sorry if I messed up the formatting :)

**Comment by clydin** [comment]
This is the repository for "angular-cli".  You appear to be using "ngcli", an unrelated project.

**Comment by filipesilva** [comment]
I second what @clydin said 💃
