### ISSUE TITLE
Charset only loaded correctly in index.html, not in components via ng serve

### ISSUE THREAD

**Issue by rodneyjoyce** [angular/angular-cli#3061]
Hi,

I am using Chrome Version 53.0.2785.143 m and Angular 2.1.0 on Windows 10.
Webpack 2.1.0 Beta 25
Angular-CLI - 1.0.0 Beta 18

The problem is that when I use "ng serve" while developing locally then extended characters are not rendered correctly in the Components. Extended chars directly in index.html work fine. 

I suspect it is something to do with the way the files are being saved and served but I am new to ng2, webpack and CLI so not really sure how to test that theory just yet.

The charset in index.html is set to "charset=UTF-8" and if I view the individual component HTML page BEFORE bundling in the browser it renders correctly.

**Repro Steps:**
Copy and paste "Próximamente" into the Index.html output area, as well as into a component's template. Run "ng-serve". The one in index.html will render correctly but the one in the template will not

**Comment by filipesilva** [comment]
Your example worked for me:
![image](https://cloud.githubusercontent.com/assets/4172079/20484037/37fde69a-afed-11e6-847b-ea80a3cee97a.png)

I suspect your editor might be saving stuff in a different charset. What editor are you using?

**Comment by rodneyjoyce** [comment]
Thanks for trying it - I have found the solution - http://stackoverflow.com/questions/40504558/angular-cli-angular2-non-standard-chars-only-load-correctly-in-index-html-not
