### ISSUE TITLE
Serve plain JS-File

### ISSUE THREAD

**Issue by NilsQuirmbach** [angular/angular-cli#3062]
I need to serve a plain JS file from  angular-cli, not a bundled version.
When i try to link it from the assets folder I get the index.html as a return value.

Is there any way or plan to support this? Otherwise I will serve it from a file-server.

### OS?
Win 10

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 4.6.1
os: win32 x64

**Comment by deebloo** [comment]
@NilsQuirmbach can you show us your example? it sounds like a path is incorrect.
