### ISSUE TITLE
ng new creates app but completed with an undefined exit Code instead of 0

### ISSUE THREAD

**Issue by indcoder** [angular/angular-cli#3065]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 Pro

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
ng new <app name>

### The log given by the failure.
> Normally this include a stack trace and some more information.
\ Installing packages for tooling via npm
├── es6-shim (global)
├── angular-protractor (global dev)
├── jasmine (global dev)
└── selenium-webdriver (global dev)

Installed packages for tooling via npm.
  angular-cli:testing cli: command run complete. exitCode: **undefined** +6m

### Mention any other details that might be useful.
The app gets created with all the components. At least I didnt find anything missing or a miss.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I think it was probably a fluke with `npm` dying midway due to a network hickup or something. I don't think this happens overall. If it keeps happening I'm happy to reopen it.
