### ISSUE TITLE
Support for glob/wildcard patterns for global styles

### ISSUE THREAD

**Issue by jongunter** [angular/angular-cli#3069]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 8

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.19-3
node: 6.3.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

I added a bunch of Bootsstrap LESS files to the /assets directory, and added the following line to angular-cli.json:
```
 "styles": [
        "assets/less/**/*.less"
      ],
```

### The log given by the failure.
> Normally this include a stack trace and some more information.

Module not found: Error: Can't resolve 'C:\Projects\my-project\src\assets\less\**\*.less' in 'C:\Projects\my-project\node_modules\angular-cli\models'
 @ multi styles

### Mention any other details that might be useful.
I have nearly 50 LESS styles (a Bootstrap theme). Adding them all to this list (or to another LESS file using @import would be tedious.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
We're not looking at adding glob support to `styles`, because loading order is relevant. Instead, just make a single file that imports everything in the order you want and put that in the `styles` array.
