### ISSUE TITLE
Dependencies hosted on AWS behind corporate firewalls

### ISSUE THREAD

**Issue by slashbrackets** [angular/angular-cli#3070]
I think since beta 18 there are dependencies both during installation of angular-cli as well as some commands like ng new, which also resolves dependencies, that are hosted on AWS sites. These in some corporate environments are blocked by firewalls. Are there any alternatives? - The firewall will **NOT** be changed.

An example is the SASS dependencies.

**Comment by filipesilva** [comment]
There are some such dependencies, yes. Basically packages that need to be natively compiled and, when that is not possible, a binary is downloaded instead (typically from AWS).

I understand this might be a problem in some environments. Not sure we can completely get around it though... Can you list the ones that are giving you trouble?

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/5282
