### ISSUE TITLE
Failed at the node-sass@3.11.2 postinstall script 'node scripts/build.js'.

### ISSUE THREAD

**Issue by MUBUSHER** [angular/angular-cli#3074]
Hi,

i got 'Failed at the node-sass@3.11.2 postinstall script 'node scripts/build.js'.' error while installing angular-cli globally on my system.

System Information:
>Windows 7 Professional Service Pack 1 (x64)
>Node 4.6.1
>NPM 3.10.9

Debug File Info:
>187936 silly lifecycle yargs@4.8.1postinstall: no script for postinstall, continuing
>187937 silly postinstall yargs@4.8.1 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\yargs-8b3c9e8c
>187938 info lifecycle yargs@4.8.1postinstall: yargs@4.8.1
>187939 silly lifecycle yargs@4.8.1postinstall: no script for postinstall, continuing
>187940 silly postinstall yeast@0.1.2 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\yeast-a096d536
>187941 info lifecycle yeast@0.1.2postinstall: yeast@0.1.2
>187942 silly lifecycle yeast@0.1.2postinstall: no script for postinstall, continuing
>187943 silly postinstall engine.io-client@1.7.0 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\engine.io-client-61fcb080
>187944 info lifecycle engine.io-client@1.7.0postinstall: engine.io-client@1.7.0
>187945 silly lifecycle engine.io-client@1.7.0postinstall: no script for postinstall, continuing
>187946 silly postinstall socket.io-client@1.5.0 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\socket.io-client-64758957
>187947 info lifecycle socket.io-client@1.5.0postinstall: socket.io-client@1.5.0
>187948 silly lifecycle socket.io-client@1.5.0postinstall: no script for postinstall, continuing
>187949 silly postinstall socket.io@1.5.0 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\socket.io-530792f2
>187950 info lifecycle socket.io@1.5.0postinstall: socket.io@1.5.0
>187951 silly lifecycle socket.io@1.5.0postinstall: no script for postinstall, continuing
>187952 silly postinstall testem@1.13.0 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\testem-e398506e
>187953 info lifecycle testem@1.13.0postinstall: testem@1.13.0
>187954 silly lifecycle testem@1.13.0postinstall: no script for postinstall, continuing
>187955 silly postinstall @angular-cli/base-href-webpack@1.0.6 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\@angular-cli\base-href-webpack-66cfc099
>187956 info lifecycle @angular-cli/base-href-webpack@1.0.6postinstall: @angular-cli/base-href-webpack@1.0.6
>187957 silly lifecycle @angular-cli/base-href-webpack@1.0.6postinstall: no script for postinstall, continuing
>187958 silly postinstall @angular/common@2.1.2 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\@angular\common-656b907f
>187959 info lifecycle @angular/common@2.1.2postinstall: @angular/common@2.1.2
>187960 silly lifecycle @angular/common@2.1.2postinstall: no script for postinstall, continuing
>187961 silly postinstall @angular/compiler@2.1.2 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\@angular\compiler-eee12a4a
>187962 info lifecycle @angular/compiler@2.1.2postinstall: @angular/compiler@2.1.2
>187963 silly lifecycle @angular/compiler@2.1.2postinstall: no script for postinstall, continuing
>187964 silly postinstall @angular/compiler-cli@2.1.2 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\@angular\compiler-cli-2576bcb3
>187965 info lifecycle @angular/compiler-cli@2.1.2postinstall: @angular/compiler-cli@2.1.2
>187966 silly lifecycle @angular/compiler-cli@2.1.2postinstall: no script for postinstall, continuing
>187967 silly postinstall @angular/core@2.1.2 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\@angular\core-79de65ad
>187968 info lifecycle @angular/core@2.1.2postinstall: @angular/core@2.1.2
>187969 silly lifecycle @angular/core@2.1.2postinstall: no script for postinstall, continuing
>187970 silly postinstall @angular/platform-browser@2.1.2 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\@angular\platform-browser-950be809
>187971 info lifecycle @angular/platform-browser@2.1.2postinstall: @angular/platform-browser@2.1.2
>187972 silly lifecycle @angular/platform-browser@2.1.2postinstall: no script for postinstall, continuing
>187973 silly postinstall @angular/platform-server@2.1.2 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\@angular\platform-server-2313b1ec
>187974 info lifecycle @angular/platform-server@2.1.2postinstall: @angular/platform-server@2.1.2
>187975 silly lifecycle @angular/platform-server@2.1.2postinstall: no script for postinstall, continuing
>187976 silly postinstall @ngtools/webpack@1.1.4 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\@ngtools\webpack-abbdde23
>187977 info lifecycle @ngtools/webpack@1.1.4postinstall: @ngtools/webpack@1.1.4
>187978 silly lifecycle @ngtools/webpack@1.1.4postinstall: no script for postinstall, continuing
>187979 silly postinstall angular2-template-loader@0.5.0 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\angular2-template-loader-f59bf38e
>187980 info lifecycle angular2-template-loader@0.5.0postinstall: angular2-template-loader@0.5.0
>187981 silly lifecycle angular2-template-loader@0.5.0postinstall: no script for postinstall, continuing
>187982 silly postinstall awesome-typescript-loader@2.2.4 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\awesome-typescript-loader-ae718f1d
>187983 info lifecycle awesome-typescript-loader@2.2.4postinstall: awesome-typescript-loader@2.2.4
>187984 silly lifecycle awesome-typescript-loader@2.2.4postinstall: no script for postinstall, continuing
>187985 silly postinstall common-tags@1.3.1 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\common-tags-59538a9b
>187986 info lifecycle common-tags@1.3.1postinstall: common-tags@1.3.1
>187987 silly lifecycle common-tags@1.3.1postinstall: no script for postinstall, continuing
>187988 silly postinstall compression-webpack-plugin@0.3.2 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\compression-webpack-plugin-3c2ab5ca
>187989 info lifecycle compression-webpack-plugin@0.3.2postinstall: compression-webpack-plugin@0.3.2
>187990 silly lifecycle compression-webpack-plugin@0.3.2postinstall: no script for postinstall, continuing
>187991 silly postinstall css-loader@0.23.1 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\css-loader-173337ae
>187992 info lifecycle css-loader@0.23.1postinstall: css-loader@0.23.1
>187993 silly lifecycle css-loader@0.23.1postinstall: no script for postinstall, continuing
>187994 silly postinstall ember-cli@2.5.0 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\ember-cli-5f678b5d
>187995 info lifecycle ember-cli@2.5.0postinstall: ember-cli@2.5.0
>187996 silly lifecycle ember-cli@2.5.0postinstall: no script for postinstall, continuing
>187997 silly postinstall exports-loader@0.6.3 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\exports-loader-1dc951e2
>187998 info lifecycle exports-loader@0.6.3postinstall: exports-loader@0.6.3
>187999 silly lifecycle exports-loader@0.6.3postinstall: no script for postinstall, continuing
>188000 silly postinstall expose-loader@0.7.1 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\expose-loader-f122e597
>188001 info lifecycle expose-loader@0.7.1postinstall: expose-loader@0.7.1
>188002 silly lifecycle expose-loader@0.7.1postinstall: no script for postinstall, continuing
>188003 silly postinstall file-loader@0.8.5 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\file-loader-973ac2d0
>188004 info lifecycle file-loader@0.8.5postinstall: file-loader@0.8.5
>188005 silly lifecycle file-loader@0.8.5postinstall: no script for postinstall, continuing
>188006 silly postinstall html-webpack-plugin@2.24.1 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\html-webpack-plugin-4879f630
>188007 info lifecycle html-webpack-plugin@2.24.1postinstall: html-webpack-plugin@2.24.1
>188008 silly lifecycle html-webpack-plugin@2.24.1postinstall: no script for postinstall, continuing
>188009 silly postinstall istanbul-instrumenter-loader@0.2.0 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\istanbul-instrumenter-loader-1447bbf2
>188010 info lifecycle istanbul-instrumenter-loader@0.2.0postinstall: istanbul-instrumenter-loader@0.2.0
>188011 silly lifecycle istanbul-instrumenter-loader@0.2.0postinstall: no script for postinstall, continuing
>188012 silly postinstall json-loader@0.5.4 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\json-loader-e5bbe23d
>188013 info lifecycle json-loader@0.5.4postinstall: json-loader@0.5.4
>188014 silly lifecycle json-loader@0.5.4postinstall: no script for postinstall, continuing
>188015 silly postinstall karma-sourcemap-loader@0.3.7 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\karma-sourcemap-loader-d1d864cf
>188016 info lifecycle karma-sourcemap-loader@0.3.7postinstall: karma-sourcemap-loader@0.3.7
>188017 silly lifecycle karma-sourcemap-loader@0.3.7postinstall: no script for postinstall, continuing
>188018 silly postinstall karma-webpack@1.8.0 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\karma-webpack-9b2f4d31
>188019 info lifecycle karma-webpack@1.8.0postinstall: karma-webpack@1.8.0
>188020 silly lifecycle karma-webpack@1.8.0postinstall: no script for postinstall, continuing
>188021 silly postinstall less@2.7.1 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\less-37f0df5c
>188022 info lifecycle less@2.7.1postinstall: less@2.7.1
>188023 silly lifecycle less@2.7.1postinstall: no script for postinstall, continuing
>188024 silly postinstall less-loader@2.2.3 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\less-loader-6cbe9318
>188025 info lifecycle less-loader@2.2.3postinstall: less-loader@2.2.3
>188026 silly lifecycle less-loader@2.2.3postinstall: no script for postinstall, continuing
>188027 silly postinstall node-sass@3.11.2 C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging\node-sass-3fcd2f19
>188028 info lifecycle node-sass@3.11.2postinstall: node-sass@3.11.2
>188029 verbose lifecycle node-sass@3.11.2postinstall: unsafe-perm in lifecycle true
>188030 verbose lifecycle node-sass@3.11.2postinstall: PATH: C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass\node_modules\.bin;C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\angular-cli\node_modules\.bin;C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.bin;C:\Users\mubusher_netaq\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Enterprise Vault\EVClient\x64\;C:\Users\mubusher_netaq\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\mubusher_netaq\AppData\Roaming\npm
>188031 verbose lifecycle node-sass@3.11.2postinstall: CWD: C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass
>188032 silly lifecycle node-sass@3.11.2postinstall: Args: [ '/d /s /c', 'node scripts/build.js' ]
>188033 silly lifecycle node-sass@3.11.2postinstall: Returned: code: 1  signal: null
>188034 info lifecycle node-sass@3.11.2postinstall: Failed to exec postinstall script
>188035 verbose unlock done using C:\Users\mubusher_netaq\AppData\Roaming\npm-cache\_locks\staging-22966f5a5559d75b.lock for C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\.staging
>188036 silly rollbackFailedOptional Starting
>188037 silly rollbackFailedOptional Finishing
>188038 silly runTopLevelLifecycles Finishing
>188039 silly install printInstalled
>188040 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\angular-cli\node_modules\chokidar\node_modules\fsevents):
>188041 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
>188042 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
>188042 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
>188042 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
>188042 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
>188043 warn optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.1 (node_modules\angular-cli\node_modules\node-zopfli):
>188044 warn optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.1 install: `node-pre-gyp install --fallback-to-build`
>188044 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
>188045 verbose optional SKIPPING OPTIONAL DEPENDENCY:
>188045 verbose optional Failed at the node-zopfli@2.0.1 install script 'node-pre-gyp install --fallback-to-build'.
>188045 verbose optional SKIPPING OPTIONAL DEPENDENCY: Make sure you have the latest version of node.js and npm installed.
>188045 verbose optional SKIPPING OPTIONAL DEPENDENCY: If you do, this is most likely a problem with the node-zopfli package,
>188045 verbose optional SKIPPING OPTIONAL DEPENDENCY: not with npm itself.
>188045 verbose optional SKIPPING OPTIONAL DEPENDENCY: Tell the author that this fails on your system:
>188045 verbose optional SKIPPING OPTIONAL DEPENDENCY:     node-pre-gyp install --fallback-to-build
>188045 verbose optional SKIPPING OPTIONAL DEPENDENCY: You can get information on how to open an issue for this project with:
>188045 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm bugs node-zopfli
>188045 verbose optional SKIPPING OPTIONAL DEPENDENCY: Or if that isn't available, you can get their info via:
>188045 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm owner ls node-zopfli
>188045 verbose optional SKIPPING OPTIONAL DEPENDENCY: There is likely additional logging output above.
>188046 verbose stack Error: node-sass@3.11.2 postinstall: `node scripts/build.js`
>188046 verbose stack Exit status 1
>188046 verbose stack     at EventEmitter.<anonymous> (C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
>188046 verbose stack     at emitTwo (events.js:87:13)
>188046 verbose stack     at EventEmitter.emit (events.js:172:7)
>188046 verbose stack     at ChildProcess.<anonymous> (C:\Users\mubusher_netaq\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
>188046 verbose stack     at emitTwo (events.js:87:13)
>188046 verbose stack     at ChildProcess.emit (events.js:172:7)
>188046 verbose stack     at maybeClose (internal/child_process.js:854:16)
>188046 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
>188047 verbose pkgid node-sass@3.11.2
>188048 verbose cwd C:\stuff
>188049 error Windows_NT 6.1.7601
>188050 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mubusher_netaq\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli@latest"
>188051 error node v4.6.2
>188052 error npm  v3.10.9
>188053 error code ELIFECYCLE
>188054 error node-sass@3.11.2 postinstall: `node scripts/build.js`
>188054 error Exit status 1
>188055 error Failed at the node-sass@3.11.2 postinstall script 'node scripts/build.js'.
>188055 error Make sure you have the latest version of node.js and npm installed.
>188055 error If you do, this is most likely a problem with the node-sass package,
>188055 error not with npm itself.
>188055 error Tell the author that this fails on your system:
>188055 error     node scripts/build.js
>188055 error You can get information on how to open an issue for this project with:
>188055 error     npm bugs node-sass
>188055 error Or if that isn't available, you can get their info via:
>188055 error     npm owner ls node-sass
>188055 error There is likely additional logging output above.
>188056 verbose exit [ 1, true ]

**Comment by FredUK** [comment]
It appears that node-sass 3.11.2 has just been released. From checking the logs my last successful build was installing node-sass 3.11.1 then all the builds started failing as soon as 3.11.2 was released. Even though I'm using a different framework (Ember JS) it seems to be the same issue. It throws the same error when doing npm install since node-sass 3.11.2 release.

**Comment by vivek4c4** [comment]
Hi I am new to this npm, I am facing 
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
can any one let me how can I resolve this issue? Thanks

**Comment by MUBUSHER** [comment]
how come the same thing successfully installed on another system (Windows 10 Enterprise).

**Comment by techunits** [comment]
I am also facing similar issue:
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"
})

**Comment by gelliott181** [comment]
@vivek4c4 @techunits you are both experiencing a warning that is perfectly normal. When using OS X there's a nice filesystem feature provided by the OS by which file changes emit events, making "watching" files for changes the reverse, where they're passively "listened" for (Change Detection vs an Event Emitter if you need an analogy).

This is made possible by fsevents, a package that is only available for OS X and macOS installations due to dependence on the OS's functionality.

**Comment by joshdanhall** [comment]
I'm getting the same issue (error, not a warning - so cannot proceed):-
```
npm ERR! Linux 2.6.32-642.3.1.el6.x86_64
npm ERR! argv "/opt/node-v6.9.1-linux-x64/bin/node" "/usr/bin/npm" "--loglevel" "verbose" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.11.2 postinstall: `node scripts/build.js`
```

**Comment by joshdanhall** [comment]
I was able to get around this issue by adding the `--unsafe-perm` option (seems to be a requirement if running npm as root):-
`npm install --unsafe-perm node-sass@3.11.2`

**Comment by MUBUSHER** [comment]
Hi Guys,

after spending too much time on this issue, finally i reach to this conclusion, 

some of the amazon cloud server is blocked by the network. which is started from something like s3.amazon.etc etc

i request to network admin and he gave access now it works for me.

**Comment by filipesilva** [comment]
@MUBUSHER glad to hear you got it sorted. Meanwhile, the source of this issue is being tracked in https://github.com/angular/angular-cli/issues/3070.
