### ISSUE TITLE
Cannot instal angular-cli

### ISSUE THREAD

**Issue by CarlosReta** [angular/angular-cli#3075]
Trying to install it on Windows 10.

Node version 7.1.0
npm  v3.10.9

From PoweShell --> npm instal -g angular-cli

14440 error node v7.1.0
14441 error npm  v3.10.9
14442 error code ELIFECYCLE
14443 error windows-build-tools@0.6.0 postinstall: `node ./lib/index.js`
14443 error Exit status 1
14444 error Failed at the windows-build-tools@0.6.0 postinstall script 'node ./lib/index.js'.
14444 error Make sure you have the latest version of node.js and npm installed.
14444 error If you do, this is most likely a problem with the windows-build-tools package,
14444 error not with npm itself.
14444 error Tell the author that this fails on your system:
14444 error     node ./lib/index.js
14444 error You can get information on how to open an issue for this project with:
14444 error     npm bugs windows-build-tools
14444 error Or if that isn't available, you can get their info via:
14444 error     npm owner ls windows-build-tools
14444 error There is likely additional logging output above.
14445 verbose exit [ 1, true ]

**Comment by dmastag** [comment]
I am having a problem with my existing projects since upgrading to node 7.1.0. Working fine after downgrading to 7.0.0.

This might be related

**Comment by CarlosReta** [comment]
I expirencied the same problem with some node versions 4.4.2, 6.9.1 and 7.1.0.

**Comment by filipesilva** [comment]
We currently don't support node7 but we plan to. Tracking in https://github.com/angular/angular-cli/issues/3218
