### ISSUE TITLE
Can't set test directory outside of folder where test.ts is located in -beta.19

### ISSUE THREAD

**Issue by harunurhan** [angular/angular-cli#3077]
### OS?

macOS Sierra

### Versions.

angular-cli: 1.0.0-beta.19-3
node: 5.12.0
os: darwin x64

### Repro steps.

in generated `test.ts`, I only changed the test files path `require.context('../other-folder', true, /\.spec\.ts/);`. It was working in `beta.15` but with `beta.19` I get 
`ERROR in ENOTDIR: not a directory, scandir '/path/to/other-folder/index.ts'`, just before karma is started, in other words before `[karma]: Karma v1.2.0 server started at http://localhost:9876/` log. And for this reason it doesn't find any test, prints `Chrome 54.0.2840 (Mac OS X 10.12.1): Executed 0 of 0 ERROR (0.004 secs / 0 secs)`.

Same setup works when I use `./` path but my tests are in another folder.

### The log given by the failure.

`ERROR in ENOTDIR: not a directory, scandir '/path/to/other-folder/index.ts'`

there is no stack trace or more log messages even if when I start karma with `verbose` flag.

**Comment by valorkin** [comment]
I have same issue, but reproduce steps a bit easier:
- create new app (ng create ...)
- rename `src/main.ts` to `src/index.ts` (update angular-cli.json accordingly)
- run `ng test`

and `ERROR in ENOTDIR: not a directory, scandir '/path/to/other-folder/index.ts'` appears

**Comment by BernhardRode** [comment]
Same issue.. 

i'm using the <root>/src/index.ts to be able to import my stuff from another repo.

**Comment by valorkin** [comment]
status update: issue is related to `.then(() => require.context('./', true, /\.spec\.ts/))`
pointing `require.context` to any folder with `index.ts` produces an issue
digging deeper...

**Comment by valorkin** [comment]
@hansl do you have an idea where in `require.context` chain
`./src` could be replaced with `./src/index.ts` if `index.ts` file exists
which leads later to `fs.readdir(`./src/index.ts`)` and this one leads to mentioned exception

**Comment by valorkin** [comment]
@hansl @Brocco may I bring your attention to this issue?
it is a bit of blocker if you are using index.ts files

**Comment by filipesilva** [comment]
This might have been a side effect of https://github.com/angular/angular-cli/pull/2291/files. Can you try locally deleting `modules: [path.resolve(projectRoot, 'node_modules')]` to see if that fixes it?

**Comment by valorkin** [comment]
@filipesilva I will try to

**Comment by bfwg** [comment]
Same error.
angular-cli: 1.0.0-beta.21
node: 6.9.2
os: darwin x64
I'm building an lib project using CLI and I want to run tests in my lib folder instead of the demo app folder.

**Comment by charpeni** [comment]
@filipesilva @valorkin Unfortunately, that does not solve this issue, `require.context` still resolve inner `index.ts` instead of folder.

**Comment by harunurhan** [comment]
@bfwg  I am trying to do same, but now had to pin to the version, however I need the latest for some   new fixes.

any plan to fix this soon? @filipesilva

**Comment by harunurhan** [comment]
I upgraded `cli` to `1.0.0-beta.28.3`lately, was painful and now it works for me.

**Comment by Brocco** [comment]
@harunurhan that's great to hear!!!

Closing this issue as it is reported to be working now.

**Comment by hanvyj** [comment]
I'm having this issue in 1.4.5. Replacing:
```
    const context = require.context('./', true, /\.spec\.ts$/);
```
with:

```
    const context = require.context('../server', true, /\.spec\.ts$/);
```
fails. I can manually add files using absolute path:
```
    const context = require.context('c:/Projects/project/server/models', true, /\.spec\.ts$/);
```
But it doesn't seem to be combining relative paths correctly, as using:
```
    context.push(require.resolve('../server/models/client.spec'));
```
I'm getting the error:
```
ERROR in ./src/test.ts
Module not found: Error: Can't resolve '../server/models/client.spec' in 'C:\Projects\project\src'
 @ ./src/test.ts 19:13-60
```
