### ISSUE TITLE
Do I need to locally import a service to a component or to NgModule?

### ISSUE THREAD

**Issue by beatscode** [angular/angular-cli#3078]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**Mac OSX Sierra**

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
**angular-cli: 1.0.0-beta.19-3
node: 4.5.0
os: darwin x64**

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

1. ng new test1
2. ng g component test2
3. ng g service my-service

4. added MyServiceService to app.module.ts
```
providers: [MyServiceService],
```
5. added constructor to AppCompopnent injecting my-service
```
constructor(private ms:MyServiceService){}
```

### The log given by the failure.
> Normally this include a stack trace and some more information.

![image](https://cloud.githubusercontent.com/assets/1777648/20141597/0bcec66c-a65f-11e6-9317-50e33fc0d905.png)

------------------

I thought I could import everything in my app.module.ts file. Is there something I'm missing.

![image](https://cloud.githubusercontent.com/assets/1777648/20141654/516981b2-a65f-11e6-85ba-db4c1f9615c1.png)

**Comment by clydin** [comment]
Adding the service to `providers` in the NgModule adds it to the dependency injector.
But you'll also need to add the `MyServiceService` import to the component file.  Otherwise Typescript won't know about the type.

**Comment by beatscode** [comment]
Thank you
