### ISSUE TITLE
Dynamically require module

### ISSUE THREAD

**Issue by NilsQuirmbach** [angular/angular-cli#3079]
I need to dynamically require a module.
In webpack I did it via require.ensure, but this is not working.

**Case:** 
I am getting data from the server and have to map these to a ts classes and create an object tree. 
The data can be nested infinitely, so I have to load the module dynamic depending on a type attached to the data.

**Comment by filipesilva** [comment]
@TheLarkInn can you give some assistance as to how to dynamically require modules in webpack2? I believe it's just doing `System.import` but some typings might be needed as well.

**Comment by NilsQuirmbach** [comment]
I tried it with `System.import`, but it fails the same as it does with `require`.

![image](https://cloud.githubusercontent.com/assets/22655797/20525146/5a95afd6-b0be-11e6-8e42-6535722d7f82.png)

**Comment by NilsQuirmbach** [comment]
I made a small example to make it more clear, what I am trying to archive.

https://github.com/NilsQuirmbach/dynamic-require
