### ISSUE TITLE
Debugging/Sourcemaps do not work at all in OSX Chrome 54

### ISSUE THREAD

**Issue by intellix** [angular/angular-cli#3080]
### Versions.
angular-cli: 1.0.0-beta.19-3
node: 5.12.0
os: darwin x6 (OSX Sierra)
browser: Chrome Version 54.0.2840.98 (64-bit)

### Repro steps.
```
ng new something
cd something
ng serve
```
go to Chrome and press Cmd + P to search for a file to place a breakpoint

### Mention any other details that might be useful.
I'm still unsure if debugging is meant to be working or not. I'm using the latest 19-3 and still when I do Cmd + P to find a file and place a breakpoint, all I see are ngfactory files. 

Isn't AOT supposed to be behind a flag, why does it run during development? 

Was expecting to see app.component.ts but just see factories: https://www.dropbox.com/s/02gbjuqp73t2you/Screenshot%202016-11-09%2016.01.31.png?dl=0

If I look inside node_modules/angular-cli/models/webpack-build-development.js, I'm seeing `source-map` instead of the cheap one, so I don't think I'm running old code. I'm really confused as I haven't seen anyone else bring up any of this yet.

**Comment by intellix** [comment]
Still impossible to debug in beta.20
Source maps aren't created and they don't exist.
aot = false still creates and uses an ngfactory file
aot = true creates one bundle containing ngfactories

Would love a bit of clarification what the story is here: @filipesilva

**Comment by nbuso** [comment]
Hi I just tried, I'm on this version:
$ ng --version
angular-cli: 1.0.0-beta.20-4
node: 6.6.0
os: linux x64

In the source pane of chrome I can Ctrl+P and loog for app.component.ts and it's exactly the source code generated by the CLI. Do you have a way to share your generate project?

**Comment by intellix** [comment]
Right ok so it's just me then. I'll reinstall all my node versions and figure out when it dies

**Comment by intellix** [comment]
I'm seeing the source code in Firefox, so now I need to drill down a little further to see how to get them in Chrome

**Comment by intellix** [comment]
ok... at some point JavaScript sourcemaps were disabled... I have no idea when but it seems that was the case -.-
