### ISSUE TITLE
github-pages:deploy doesn't clean up obsolete files

### ISSUE THREAD

**Issue by rongchaua** [angular/angular-cli#3081]
Hi,
I would like to ask if the command "ng github-pages:deploy" should clean up the "dist" folder when deploying? I see the obsolete files aren't deleted from "gh-pages" branch.

![1](https://cloud.githubusercontent.com/assets/6661713/20142610/c2ff5fa0-a695-11e6-9d37-00e64de73f39.png)

The "gh-pages" branch keeps growing up with these obsolete files. Should I clean up the "gh-pages" manually?

**Comment by filipesilva** [comment]
No, you shouldn't have to do it manually. It's a bug.
