### ISSUE TITLE
inline.js gets cached by the browser, which then caused issues in loading the right chunks

### ISSUE THREAD

**Issue by divyeshpuk** [angular/angular-cli#3082]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
os: linux x64

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.16
node: 5.4.0
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
In our Angular CLI app, src="inline.js" got cached by the browser, which then created issues in loading the right chunks.

### The log given by the failure.
> Normally this include a stack trace and some more information.
404 not found, chunk.*.js is not found

### Mention any other details that might be useful.
In our Angular CLI app, src="inline.js" got cached by the browser, which then created issues in loading the right chunks.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by grizzm0** [comment]
I believe that is what #2899 fixed. Will be in next release.

**Comment by divyeshpuk** [comment]
Good news. Any idea when the next release is due? Thank you so much.

On Wed, Nov 9, 2016 at 3:51 PM, Kristofer Karlsson <notifications@github.com

**Comment by grizzm0** [comment]
New beta releases seems to be released every 1-2 weeks. The current release was released on October 28th. But that's no guarantee there'll be another released any day now.

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/2899.
