### ISSUE TITLE
Adding query parameter to inline.js (e.g. src="inline.js?1478695804") in index.html caused an error

### ISSUE THREAD

**Issue by divyeshpuk** [angular/angular-cli#3083]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
os: linux x64

### Versions.
angular-cli: 1.0.0-beta.16
node: 5.4.0
os: linux x64

### Repro steps.
Added query parameter to inline.js (e.g. src="inline.js?1478695804") in index.html to bust browser cache

### The log given by the failure.
Type Error: cannot read property call of undefined
Unhandled promise rejection: cannot read property call of undefined, zone: Angular, Task: Promise.then, value: Type Error...

### Mention any other details that might be useful.
The query parameter was added to bust browser cache.
![pasted_image_at_2016_11_08_02_10_pm](https://cloud.githubusercontent.com/assets/11209798/20145803/560438cc-a699-11e6-856b-575697adf9de.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by grizzm0** [comment]
I can't see how that would break anything and it works just fine here. 

Anyhow, reporting an issue after altering anything the cli gives you doesn't really make sense as it's out of the scope of the cli.

**Comment by divyeshpuk** [comment]
Thank you. But this works much better for Beta-16 that we are using.
var timestamp = Date.now();
new webpack.optimize.CommonsChunkPlugin({
                minChunks: Infinity,
                name: 'inline',
                filename: 'inline.'+timestamp+'.js',
                sourceMapFilename: 'inline.'+timestamp+'.map'
            }),

**Comment by inska** [comment]
@divyeshpuk Do you build with custom webpack build options? how? is it possible with latest angular cli?

**Comment by divyeshpuk** [comment]
@inska I changed the config/index.html both through Bash script in the Jenkins build.

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/2899
