### ISSUE TITLE
Modifying component template in AOT mode has no affect only after restart

### ISSUE THREAD

**Issue by blacksonic** [angular/angular-cli#3084]
### OS?
Linux Ubuntu 16.04

### Versions.
Node: 6.7.0
Angular 2: 2.1.2
@ngtools/webpack: 1.1.4

### Repro steps.
Using @ngtools/webpack with webpack-dev-server compiles the application right at startup, but when modifying a component template it still serves the old version after refresh.

Clone [this repository](https://github.com/blacksonic/angular2-aot-webpack) and start the application with ```npm run start-plugin``` and modify the ```HelloWorldComponent```.
If i stop the server and start it again, it shows the new version.

**Comment by filipesilva** [comment]
It's working from within the CLI, but am unsure why it wouldn't work with just the plugin. Maybe @hansl can shed some light on it.

**Comment by blacksonic** [comment]
Needed to add `@ngtools/webpack` to `rules` also.
