### ISSUE TITLE
Global Library Installation error in angular-cli 1.0.0-beta.19-3

### ISSUE THREAD

**Issue by zhengchaotext** [angular/angular-cli#3091]
I just using  angular-cli 1.0.0-beta.19-3 to build Global Library following Global Library Installation ,but it can not work!   
chrome show   Uncaught Error: Bootstrap's JavaScript requires jQuery(…)

**Comment by RicardoVaranda** [comment]
Try clearing you cache before you perform an install like:

npm cache clean
npm install -g angular-cli@latest
