### ISSUE TITLE
CLI does not start browser on port 4200 with active reload

### ISSUE THREAD

**Issue by peterheard01** [angular/angular-cli#3092]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OSX Yosimite

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```bash
angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: darwin x64
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

All of it was cli.

### The log given by the failure.
> Normally this include a stack trace and some more information.

```bash
EHEARD-M-N20B:my-dream-app peteheard$ n6076ms building modules                   2ms add01675ms1320ms asset41ms emittingHash: 28ce1f0add2ae1d07014                                                                                               
Version: webpack 2.1.0-beta.25
Time: 9685ms
           Asset       Size  Chunks             Chunk Names
  main.bundle.js    2.71 MB    0, 2  [emitted]  main
styles.bundle.js    10.2 kB    1, 2  [emitted]  styles
       inline.js    5.53 kB       2  [emitted]  inline
        main.map    2.81 MB    0, 2  [emitted]  main
      styles.map    14.1 kB    1, 2  [emitted]  styles
      inline.map    5.59 kB       2  [emitted]  inline
      index.html  477 bytes          [emitted]  
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.81 kB       0       
webpack: bundle is now VALID.
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Meligy** [comment]
The `ng serve` command does not open the browser by default. You need to add the argument `-open` to it, like `ng serve -open`.

**Comment by Meligy** [comment]
Oh. That document is very outdated!

It doesn't even have the `serve` command!

Might be a good idea to remove it, redirect to readme or something.
// CC @filipesilva

**Comment by Meligy** [comment]
An outdated doc file is a separate issue from what this issue is though.

**Comment by peterheard01** [comment]
Do I have to make a new issue or can I rename this one then?

What does //CC @filipesilva mean?

**Comment by Meligy** [comment]
It's like a "mention" in twitter/facebook :)

Since he hasn't replied anyway, I expect it'll be a bit until there's talks about it. Maybe close this issue and create another one, linking to this issue for context.

Thanks a lot man!

**Comment by dilipkosuri** [comment]
"start": "ng serve -open" or  "start": "ng serve -opn" opens the browser before the compilation is done and moreover, it opens an empty browser window. Does anyone have a precise solution?
