### ISSUE TITLE
It seems "ng build" has no option to build ts, map and js files to same folder

### ISSUE THREAD

**Issue by jasondu168** [angular/angular-cli#3093]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular: 2.1.0
angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Code can be generated. 

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
Couldn't find the option that can be used to output ts, map and js files to the same output folder.
Also the options below can't be used in the same tsconfig.json file.
"sourceMap": true,
"inlineSourceMap": true,

Can't be use at the same time.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Meligy** [comment]
That's not how the CLI is meant to be used. It's meant to build apps. It bundles stuff perfectly for the app. Compiling each file in the same dir isn't the best way to serve the app files.

However, it's technically possible.

From the root of the CLI project you can run something like:

```
./node_modules/.bin/tsc -project src/
```

Which will generate the files in `./dist/out-tsc`.

(of course you can go to the `src` dir and simply run `../node_modules/.bin/tsc`, or just `tsc` if you have TypeScript globally installed)

The path `./dist/out-tsc` comes from the `./src/tsconfig.json` file `outDir` property. You can change that to `.` or simply comment it.

Again, this is **not** a supported scenario, and it's NOT how the CLI is meant to be used.

Now to the sourcemaps error.

This is a TypeScript error. The `sourceMap` and `inlineSourceMap` bits are TypeScript stuff not Angular CLI stuff, and the error that they cannot be used together is shown as expected as this is how it works in TypeScript.

Cheers,

**Comment by jasondu168** [comment]
I really appreciate your rapid reply. Got it!
I tried to generate the map and js file into the same folder just because when debugging the ts file, it will try to find the map and js files. I am using tsc commands to do this now. For the sourceMap and inlineSourceMap question, I copied some configuration from the https://github.com/angular/angular-cli/blob/master/tsconfig.json file  but there was an error. I was thinking maybe the CLI add some restriction... Anyway, both of my problems can be solved by change the config file and using tsc command. Thank you very much for your help!

**Comment by jasondu168** [comment]
I generated the map and js files successfully into the src folder. But I think debugging the source code created by cli is difficult because it's using the webpack. The source files were output to 1 bundle.js file. Although I generated the js and map files and put them to the webroot folder, the debugger still seeing the bundle.js files. It can jump into the main.bundle.js file and debug step by step but can't link to the ts file. I am trying to use the systemJS. Is there some settings can let the webpack keep the original files?

**Comment by hansl** [comment]
There will not be unbundled JS output when using `ng build` or `ng serve`. You can open files from the sourcemaps in your browser, and if you need the JS and sourcemaps for each files you can use `tsc` as mentioned above.

Why do you need JS files per module? There's no reason for you to use SystemJS as webpack takes care of everything for you.

**Comment by jasondu168** [comment]
Thank you. Just want to debug the ts files directly using Visual Studio Code. But I tried many times and the breakpoints in ts files doesn't work. I am trying to find where the problem is.

**Comment by filipesilva** [comment]
@jasondu168 ah, if that is what you need, check out this issue instead: https://github.com/angular/angular-cli/issues/2453. The community found good debug configs for VSCode and put them there.

**Comment by yogeshgadge** [comment]
@Meligy How/where does angular-cli produce type packages which can be published to npm as a part of your angular-cli so that others can install your npm module and consume these types. E.g. say someone has a cool angular2 component that they want to publish. 
Should we use `tsc` for that separately ? I was referring at the angular/material2 project but they use gulp and not angulcar-cli.

**Comment by filipesilva** [comment]
@yogeshgadge the CLI does not support creating libraries at the moment. There is a RFC thread at https://github.com/angular/angular-cli/issues/6510, and inside there are a couple of library starters and managers created by the community.
