### ISSUE TITLE
Unclear error message when generating components

### ISSUE THREAD

**Issue by jusefb** [angular/angular-cli#3096]
### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 5.10.1
os: darwin x64

### Repro steps.
1. Create an angular 2 module in a file titled index.ts
2. Use the generator command to add a component to the module ```ng g component test-component```
3. You get an error "Error locating module for declaration SeilentError: No module files found"
4. Changing the name of the file from indext.ts to index.module.ts fixes the problem

### Mention any other details that might be useful.
It would be very helpful for the error message to specify the convention used by the generator

**Comment by Brocco** [comment]
This is a known issue, a better way to determine whether a file is an NgModule or not will need to be determined, while at the same time ignoring routing modules.

**Comment by filipesilva** [comment]
Nowadays we have better error messages for this sort of thing.
