### ISSUE TITLE
Deprecated / Security Warnings 

### ISSUE THREAD

**Issue by realtebo** [angular/angular-cli#3097]
**OS**: Windows 7 and 10
**Version**: unable to retrieve
**Repro** 

- install last NODE lts con a clean windows env
- npm install -g typescript
- npm install -g angular-cli@1.0.0-beta.18

**Logs**

> npm WARN deprecated tough-cookie@2.2.2: **ReDoS vulnerability** parsing Set-Cookie https://nodesecurity.io/advisories/130
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a **RegExp DoS issue**
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a **RegExp DoS issue**
> npm WARN deprecated lodash-node@2.4.1: **This package is discontinued**. Use lodash@^4.0.0

**Comment by filipesilva** [comment]
We're working on trimming unused packages as part of a separate effort to reduce install size. A lot of these will be removed there.
