### ISSUE TITLE
Sourcemaps for production environment 

### ISSUE THREAD

**Issue by c-muresan** [angular/angular-cli#3100]
Is there a way to generate source maps for production? I have a bug that only reproduces after uglify/mangle

**Comment by lordmat0** [comment]
Source maps are generated for production, there is currently no way to disable them.

**Comment by aggarwalankush** [comment]
I'm looking for disabling source map in production :P

**Comment by Perezmarc** [comment]
Hey!
You can use --no-sourcemap ;)

**Comment by filipesilva** [comment]
Closing as `--no-sourcemap` is now available.

**Comment by awerlang** [comment]
Since #3963 the default has changed. No source maps by default, enable them with `--sourcemap`

**Comment by adnan-kamili** [comment]
`--sourcemap` has been changed to `--source-map` in angular 6
