### ISSUE TITLE
TypeError: compiler.HtmlParser is not a constructor (ng-xi18n)

### ISSUE THREAD

**Issue by lfv89** [angular/angular-cli#3103]
The error happens when the `./node_modules/.bin/ng-xi18n` command is executed.

### OS?
OSX El Capitan

### Versions.
angular-cli: 1.0.0-beta.17
node: 6.3.1
os: darwin x64

### The log given by the failure.

```
TypeError: compiler.HtmlParser is not a constructor
    at Function.Extractor.create (/Users/lfv89/Projects/foobar/node_modules/@angular/compiler-cli/src/extractor.js:63:54)
    at extract (/Users/lfv89/Projects/foobar/node_modules/@angular/compiler-cli/src/extract_i18n.js:18:43)
    at Object.main (/Users/lfv89/Projects/foobar/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/Users/lfv89/Projects/foobar/node_modules/@angular/compiler-cli/src/extract_i18n.js:46:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
Extraction failed

```

### Mention any other details that might be useful.

The error occurs with `@angular2/compiler-cli` v2.1.2
I rolled back to v2.1.0 and everything works fine.

**Comment by quiringk** [comment]
I am having the same problem but with compiler.AnimationParser.

when I run ng--version it says I am using angular-cli: 1.0.0-beta.19-3. I tried "rolling back" to 2.1.0 in package.json, uninstalling, and then installing but the version for cli isn't changing. Npm installs 

+-- @angular/compiler-cli@2.2.0

even when I have 2.1.0 in package.json. Any ideas why this is happening?

**Comment by Sri276286** [comment]
I am also having the same issue.

@lfv89 I did what you suggested but it didn't work.

I got "@angular/compiler-cli": "^2.2.0" in package.json. I tried to rollback to 2.1.0 and then I started getting many errors.

**Comment by quiringk** [comment]
I think this is an error with compiler-cli and not angular-cli (different things, kind of confusing.) The way I got rid of it was using 2.2.0 for all the angular packages including compiler-cli. Then I don't know if this was necessary but I deleted the node_modules and then npm install to reload fresh everything and it worked.

**Comment by lfv89** [comment]
Yes it's definitely not an error with angular-cli, good catch. I might have opened the issue in the wrong place 😢

**Comment by BenDevelopment** [comment]
@lfv89 did you find a solution? I'm facing the same problem.

**Comment by quiringk** [comment]
Yeah I ended up upgrading to 2.2.0 for alll my angular classes and it worked

**Comment by BenDevelopment** [comment]
Thank you (I've removed my post before you answere because I found the solution in your previous post ^^).

**Comment by quiringk** [comment]
FAsho you the man homie good luck 👌🏽

**Comment by filipesilva** [comment]
Yeah this isn't isn't CLI related, you should open it on https://github.com/angular/angular instead.
