### ISSUE TITLE
Random error: "Uncaught TypeError: __webpack_require__.d is not a function"

### ISSUE THREAD

**Issue by mgol** [angular/angular-cli#3104]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

macOS Sierra 10.12.1 (16B2555)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

I created an app using:
```
ng new yg-angular-app --style=scss --prefix=yg --routing
```
I then created some components, copied in bundles from an Angular 1 app & included them in HTML. Now when I invoke `ng serve` I usually get an error:

> Uncaught TypeError: __webpack_require__.d is not a function

When I remove some code (e.g. all the code related to ngUpgrade, sub-modules & sub-components) and restart the server (`ng serve`) and it succeeds, I can then often restore the deleted code piece by piece and the server will live-reload my app to the working state, even though it was failing originally.

You can play with it in the repo: https://github.com/mgol/angular2-upgrade-test-app. Just run:
```
npm install
ng serve
```
and open http://localhost:4200 in a browser & look at the console.

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
Uncaught TypeError: __webpack_require__.d is not a function
    at Object.<anonymous> (index.js:1)
    at e (vendor-1.bundle.js:1)
    at window.webpackJsonp (vendor-1.bundle.js:1)
    at webpackJsonpCallback (bootstrap fa7a23a…:18)
    at main.bundle.js:1
```

### Mention any other details that might be useful.

I see the same error if I make any mistake in my app, e.g. I forget to import a module needed to render a specific component and then run `ng serve`. If I fix the issue, restart `ng serve` and re-introduce the issue I see the pretty detailed error info which is actionable but I never see it if the app has an error during the server startup.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mgol** [comment]
I've found a reliable way to work around it. Once you see this error, you can open `src/main.ts`, comment out the whole file and then restart `ng serve` (weirdly, this step seems to be required; even though the app recompiles & starts without an error, uncommenting the file causes the site to show the same `__webpack_require__.d is not a function` error if you haven't restarted `ng serve` at this point) and uncomment the file; it works then.

**Comment by filipesilva** [comment]
Closing as I've responded to this issue offline with @mgol.

**Comment by kopertop** [comment]
What was the issue here? I just now started having this problem:

```
angular-cli: 1.0.0-beta.28.3
node: 6.9.5
os: darwin x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.6
@angular/compiler-cli: 2.4.1
```

**Comment by mgol** [comment]
@kopertop The issue was having Webpack bundles generated by two apps loaded on the same site - I had another Webpack-compiled AngularJS 1.x app and wanted to use its bundles in an Angular app generated by Angular CLI. When I changed the AngularJS app to be compiled to a single bundle, the problem went away.

For a while I thought this is because my AngularJS app used Webpack 1 and Angular CLI was on Webpack 2 but updating the AngularJS app to Webpack 2 hasn't resolved the issue.

**Comment by ChrisProlls** [comment]
Hi @mgol ! I think I have the same issue as yours.
Firstly, I have one Angular app (with multiple components I want to reuse) that I bundled and delivered to NPM. Then, I have a second Angular app that consume this NPM package to access to my previous components. 
I was careful to not deliver files like `main.ts`, `index.html` and so on ... But only my components + `index.ts` to export only the big module of my first application. 
My error with Chrome debugger :
```
notification.service.ts:4 Uncaught TypeError: __webpack_require__.i(...) is not a function
    at Object.__window (notification.service.ts:4)
    at __webpack_require__ (bootstrap d3317c6…:52)
    at Object.<anonymous> (navigation.service.ts:277)
    at __webpack_require__ (bootstrap d3317c6…:52)
    at Object.<anonymous> (scheduler.utils.ts:90)
    at __webpack_require__ (bootstrap d3317c6…:52)
    at Object.<anonymous> (vendor.bundle.js:26659)
    at __webpack_require__ (bootstrap d3317c6…:52)
    at Object.<anonymous> (login.component.ts:59)
    at __webpack_require__ (bootstrap d3317c6…:52)
```

The error occured when the app hit this line (when my app need the `Injectable` decorator for one of my service) :
`__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__angular_core__["Injectable"])(),`
