### ISSUE TITLE
__dirname returns '/' 

### ISSUE THREAD

**Issue by Judahh** [angular/angular-cli#3108]
Every time I use __dirname it returns '/' and if I use __filename returns '/index.js'.
I know It's from webpack, but I do not know how to configure webpack through the angular-cli (and I tried to find it in the web, but there is no solution).
Is there a way to avoid this problem?

### OS:
> Mac OSX Sierra

### Versions:
> angular-cli: 1.0.0-beta.19-3
> node: 7.0.0
> os: darwin x64

**Comment by filipesilva** [comment]
Using `__dirname` assumes the app should run as a node app, as that doesn't exist in a browser environment. We don't have much support for that. Can you tell me more about your usecase?

**Comment by filipesilva** [comment]
Closing as inactive.

**Comment by somombo** [comment]
@filipesilva __dirname returns '/'  in angular universal as well.. Which is not correct
