### ISSUE TITLE
Generate Component with additional files

### ISSUE THREAD

**Issue by wadewalker25** [angular/angular-cli#3110]
> Please provide us with the following information:
> ---------------------------------------------------------------

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: win32 x64

### Mention any other details that might be useful.
We would like the option to modify what ng g c will generate. We would like to be able to use the generate logic to generate some additional files for us. Is it possible to maybe define additional folders/files to generate?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
@wadewalker25 at the moment there is no addon system for angular-cli. The only way to change what is generated would be to fork the repo and make the changes yourself

**Comment by wadewalker25** [comment]
Another way would be to wrap the ng g c in another build tool such as gulp. Which is probably what we'll end up doing, it just sux that we are back to having to use multiple tools. So we'll have gulp run the ng command (so that it does the automatic imports and basic files) and then the gulp command will build the additional files/folders we need. 
Is this something that will be added at a later time?

**Comment by clydin** [comment]
I believe it is targeted as a post-1.0 feature.

**Comment by filipesilva** [comment]
We do not currently have this functionality, no.
