### ISSUE TITLE
ng e2e doesn't use existing ng serve session 

### ISSUE THREAD

**Issue by finalight** [angular/angular-cli#3111]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
mac sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.19-3
node: 7.0.0
os: darwin x64

Current behavior
opens a new session everytime i test, which is very slow

Expected behavior
expects to use existing sessions

Minimal reproduction of the problem with instructions
just try to run ng serve, then run ng e2e

What is the motivation / use case for changing the behavior?
test faster

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by finalight** [comment]
how's the resolve coming along?

**Comment by filipesilva** [comment]
The way Protractor (the e2e library) works is by opening a new browser window and running your commands in it. 

This is how it should work, it shouldn't use your existing browser window. If it did, you wouldn't be testing a full journey through your app.

**Comment by finalight** [comment]
yes that i can understand

however, it's taking too long for every e2e test, may I know how can I
speed it up faster?

**Comment by filipesilva** [comment]
e2e is slow overall, but maybe we can find some tips in https://github.com/angular/protractor

**Comment by JeremyIglehart** [comment]
@filipesilva He's not talking about *another* browser session, he's talking about the server.  So, `ng serve` will serve up your app... and then `ng e2e` will use the already served up app with a new browser session *each* time you run it.

**Comment by realappie** [comment]
@JeremyIglehart This would speed e2e development up a lot, as the project doesn't have to recompile every time is called `ng e2e`

**Comment by filipesilva** [comment]
You can actually do that with now with `ng e2e --serve=false` ( see https://github.com/angular/angular-cli/wiki/e2e for details).
