### ISSUE TITLE
Using backticks 'templateUrl' Component Medata results in templateName being displayed rather than displaying content

### ISSUE THREAD

**Issue by mwamufiya** [angular/angular-cli#3116]
I'm not sure if this is intended behavior or not, but not having seen this behavior documented, here's a heads up.
### OS?
Windows 10. version 1511 (OS Build 10586.589)

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 4.6.0
os: win32 x64

### Repro steps.
1. create a new app with ng. (ng new 'helloworld')
2. run (ng serve) -> page loads and the app works. you see "app works" in the browser.
3. go into the src/app/app.component.ts.
4. change the 'templateUrl' metadata from
`templateUrl: './app.component.html',`
To 
_writting backtick because I can't escape it in this editor._
`templateUrl: [backtick]./app.component.html[backtick]`
5. reload page or re-run ng serve

**Expected result**
- the page would still load as it did before

**Actual result**
- the page shows "./app.component.html" in the browser
- the text 'App works' does not appear.

### The log given by the failure.
no error logs in the console

### Mention any other details that might be useful.

- It should be noted that using backticks for the "selector" works as expected. 
- I have not tested to see if this also fails for "styleUrls" metadata.

In converting my project from systemjs to use angular-cli, this eventually came out as the culprit for downstream issues.

In this screenshot we see the expected result

- "selector" has backticks.
- "templateUrl" has singlequote

![image](https://cloud.githubusercontent.com/assets/20046256/20231259/6e2ad05a-a82e-11e6-8d06-0d99cdd2e408.png)

In this screenshot we see the observed behavior

- "selector" has singlequote.
- "templateUrl" has backticks

![image](https://cloud.githubusercontent.com/assets/20046256/20231293/a01d2fea-a82e-11e6-88cb-ec8d6393dd00.png)

**Comment by filipesilva** [comment]
Can you open this issue in https://github.com/TheLarkInn/angular2-template-loader? That is where this functionality comes from.
