### ISSUE TITLE
ng build -> segmentation fault

### ISSUE THREAD

**Issue by KevinGruber** [angular/angular-cli#3118]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux Debian 7.11

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` 

and paste the result here:
angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

I get the problem when including theming from material angular 2 in my angular-cli. only when i @import something from theming. And this only happens on my linux machine (works on Mac and Windows)

### The log given by the failure.
> Normally this include a stack trace and some more information.

 69% building modules 1329/1331 modules 2 active ...bootstrap/stylesheets/_bootstrap.scss
Speicherzugriffsfehler (Speicherabzug geschrieben)

and sometimes 
Segmentation fault (core dumped)

### Mention any other details that might be useful.

Only happens on linux.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by christiandreher** [comment]
Try this:

In your project root:

```bash
npm install
cd node_modules/node-sass
node scripts/build -f
```

Source: [know bug in node-sass for debian] (https://github.com/sass/node-sass/issues/1738) 

If that doesn't work, pin `node-sass@3.5.3`

**Comment by filipesilva** [comment]
Seems to be https://github.com/sass/node-sass/issues/1738, will have to wait for a solution there.

**Comment by christiandreher** [comment]
@filipesilva thats exactly what I referenced to. I had the same problem, but the workaround which is mentioned in this issue works very well. I wouldn't recommend pinning an older version (`3.5.3`, like mentioned in the node-sass issue) of `node-sass` either, since it produces a bunch of weird error logs and what not. At least for me... (It also messed up my CI's by the way)

**Comment by brainstrategist** [comment]
@christiandreher Great it's working like a charm
