### ISSUE TITLE
CLI does not use TSC from the generated project

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#312]
Currently the CLI only uses the version of TSC that is bundled with the CLI, however as TSC updates and people update their projects and bump the version of TSC in their project the expectation is that they can begin to use those new features. However since the CLI is pointing towards an internal TSC the only way to get the new version of TSC is to update the CLI itself.  IMO the CLI should look for the project to have a TSC and if it doesn't then default to its own. 

Cli < .25

**Comment by filipesilva** [comment]
I actually just assumed the one in the generated project was used. Bummer.

**Comment by filipesilva** [comment]
This kinda means that the TS installed in a generated project is, essentially, useless. I guess it satisfies the IDE plugins, but still, the expectation is that it is the one used.

We should really fix this.

**Comment by hansl** [comment]
This is probably a matter of using a `peerDependency` instead of a direct dependency. That means the project _will_ have to include typescript, which they should anyway so we should be okay.

**Comment by chapati23** [comment]
yes, `peerDependency` should solve this. just make sure to define _lenient_ (meaning: non-strict) version numbers. from the npm docs:

> One piece of advice: peer dependency requirements, unlike those for regular dependencies, should be lenient. You should not lock your peer dependencies down to specific patch versions. It would be really annoying if one Chai plugin peer-depended on Chai 1.4.1, while another depended on Chai 1.5.0, simply because the authors were lazy and didn't spend the time figuring out the actual minimum version of Chai they are compatible with.

Source: https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by jjstrat3** [comment]
@hansl Happy to take this on if that's ok?  Looking to make my *first open-source contribution*, and this seems like a great project to participate in...  Do you need to assign me to it?

**Comment by filipesilva** [comment]
Heya @jjstrat3, no need to assign yourself - just check out https://github.com/angular/angular-cli#development-hints-for-hacking-on-angular-cli and try your hand at it!

**Comment by filipesilva** [comment]
Closed as this PR was made obsolete by https://github.com/angular/angular-cli/pull/1455.
