### ISSUE TITLE
No watch for files in deep sub-folders

### ISSUE THREAD

**Issue by eshcharc** [angular/angular-cli#3128]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Linux x64, Ubuntu 16.04

### Versions.
> angular-cli: 1.0.0-beta.18
> node: 6.5.0
> os: linux x64

### Repro steps.
> Create a new app with the CLI.
> Generate a new component in a deep sub-folder: {root}/src/app/sub1/sub2/comp/comp.component.ts
> Any change in that file does not trigger a page/component refresh and status stays VALID.

### The log given by the failure.
> No log of a change in file/s is apparent. Log stays "webpack: bundle is now VALID." on change.

### Mention any other details that might be useful.
> Change does happen on a less deeper files such as {root}/src/app/sub1/comp/comp.component.ts
> It's the same behavior, with or w/o Facebook Watchman.

**Comment by Meligy** [comment]
Hi Chen,
Can you please:

- Try with latest version (beta.19-3 at the time of writing)
- Give specific insurrections that involve `mkdir` commands and `ng generate` command etc

Thanks!

**Comment by clydin** [comment]
Watchman is unfortunately not actually used.

**Comment by eshcharc** [comment]
@Meligy  I've tried to reproduce with a brand new project, but couldn't.
I've also noticed that when I edit and save outside of my editor domain (vscode), it does refresh, so now I have no explanation for this issue. I can't see any difference b/w my project and the one I've created for reproduction steps purposes. 
Maybe it's an editor issue after all, and I should direct vscode team instead.

**Comment by eshcharc** [comment]
May well be related to #1610

**Comment by eshcharc** [comment]
Increasing **fs.inotify.max_user_watches** in **/etc/sysctl.conf** solved this issue.
Closing.
