### ISSUE TITLE
Error When Unit Testing Generator Functions

### ISSUE THREAD

**Issue by JesterXL** [angular/angular-cli#3130]
When I use generator functions for ng-redux and redux-saga, they work for `ng serve`, but not for `ng test`. I get this error:

Generators are only available when targeting ECMAScript 2015 or higher.

I've tried modifying tsconfig.json with various settings, but nothing seems to work. In another Webpack / ES6 project, I fixed this by using the babel-polyfill loader. Perhaps that could help here?

> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan 10.11.6

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.19-3
node: 5.12.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
No, used angular cli.

### The log given by the failure.
> Normally this include a stack trace and some more information.

ERROR in [default] /Users/jesterxl/Documents/myproject/angular2-starter/src/app/login/login.saga.ts:9:16 
Generators are only available when targeting ECMAScript 2015 or higher.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
Typescript will not be supporting the down-leveling of generator functions (outside of async/await).  I'm curious as to why ng serve is working.  What browser are you testing in?

**Comment by JesterXL** [comment]
@clydin Chrome.

**Comment by JesterXL** [comment]
@clydin Firefox works, Safari crashes (lulz).

**Comment by clydin** [comment]
My guess is that a tsconfig module setting of `es6`  is allowing the generator functions to pass through.  ng test is hardcoded to use commonjs as the module format which is probably why your getting the error.

**Comment by filipesilva** [comment]
Typescript 2.1 seems to be targeting es5 support of generator functions, but in 2.0 it doesn't exist yet.

**Comment by JesterXL** [comment]
Update on this:

1. Manually install TypeScript 2.1 or higher.
2. Ensure the `tsconfig.json` has target of "ES6".

While I still get the compilation errors of "can't find Promise" ect., `ng test` it works. All tests pass including my Redux Saga generator functions. `ng serve` continues to work as normal.
