### ISSUE TITLE
Image from local folder not included in the final build

### ISSUE THREAD

**Issue by hitpopdimestop** [angular/angular-cli#3132]
### OS?
MacOS Sierra 10.12.1

### Versions.
angular-cli: 1.0.0-beta.18
node: 7.0.0
os: darwin x64

### Repro steps.
The app was completely built with CLI. I included an `<img src="LOCAL_PATH">` in one of my templates and this file was lost in my final build in dist folder. The CLI just hasn't put it there. This is what I got instead of an image:
<img width="173" alt="screen shot 2016-11-14 at 12 02 46" src="https://cloud.githubusercontent.com/assets/20238682/20260498/8e4116b6-aa62-11e6-9d46-aef0b3631402.png">

I inspected the element and saw that path was the same relative `LOCAL_PATH` as I put it in development mode, but of course, the file wasn't there. I fixed the problem by putting an image on external hosting, but I guess it should be working just fine without that.

#### No errors were thrown while building and deploying the app.

Dmytro

**Comment by deebloo** [comment]
Any static assets that you want copied to the dustbin folder need to be defined in the angular-cli.josn file.

**Comment by hitpopdimestop** [comment]
Could you please give me a link to read about it? By the way, images used as a background in CSS are exported to dist folder just fine. I find it a little confusing

**Comment by deebloo** [comment]
This probably has to do with the weback loader behind the scenese that is compiling your css. Here is the direct link to the readme section about project assets.

https://github.com/angular/angular-cli#project-assets

**Comment by hitpopdimestop** [comment]
Ok, now the file is included, but the path to the file is broken. It's just the same `LOCAL_PATH`. Am I considered to just manually repair it in main.bundle.js?

**Comment by filipesilva** [comment]
Stuff in css/sass/etc does get auto bundled but not stuff in html files. After adding your image to the assets, you should adjust your `LOCAL_PATH` accordingly. Folder structure will be preserved e.g. `src/assets/img.png` will go to `dist/assets/img.png`.
