### ISSUE TITLE
custom css file

### ISSUE THREAD

**Issue by yanai101** [angular/angular-cli#3133]
who in angular cli - i set all the sass file export as file and not embeded in the header?

**Comment by yanai101** [comment]
who in angular cli - i set all the sass file export as file and not embeded in the header?

**Comment by grizzm0** [comment]
See my answer [here](https://github.com/angular/angular-cli/issues/3006#issuecomment-258217643).

**Comment by yanai101** [comment]
@grizzm0  great !!! when the next version will appear ??

**Comment by grizzm0** [comment]
There is currently no set release cycle. You can [work with master](https://github.com/angular/angular-cli#working-with-master) if you want to which already has this feature.

Could you please close this issue as it's solved?

**Comment by yanai101** [comment]
thanks!!!
