### ISSUE TITLE
Turning off sourcemaps

### ISSUE THREAD

**Issue by davidstellini** [angular/angular-cli#3134]
I would like to turn off sourcemaps. Is there a configuration for it?

**Comment by clydin** [comment]
There will be shortly: PR #3113

**Comment by Destreyf** [comment]
@davidstellini in the case that the PR doesn't get merged soon (or in the next release) an option is to edit node_modules/angular-cli/models/webpack-build-<target>.js you can find the "sourceMap" option, you can also add comments: false if you want to remove those.

**Comment by filipesilva** [comment]
Fixed in #3113
