### ISSUE TITLE
Import external libraries, local scope

### ISSUE THREAD

**Issue by juanfeorar** [angular/angular-cli#3139]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Linux (ubuntu).

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here: angular-cli: 1.0.0-beta.17
node: 6.3.1
os: linux x64

### Mention any other details that might be useful.

I imported external libraries for angular-cli.json as follows:

```

"../node_modules/jquery/dist/jquery.min.js",
"../node_modules/bootstrap/dist/js/bootstrap.min.js"
```

etc...

And it works very well, but these are library global scope.

How to include libraries that only used in a component (local scope)?

for exmaple `"/plugins/datatables/jquery.dataTables.min.js"` the use in a single component

Thanks

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by AlejandroDelRioAlbrechet** [comment]
Hi @juanfeorar I do not think that is possible. You can create separate module and export providers. but still it will be in window scope.

**Comment by filipesilva** [comment]
Since jquery plugin need access to jquery, you should add them in the `scripts` as well. Then they will be in the global scope.
