### ISSUE TITLE
Support Migration and Upgrade Path

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#314]
We need a way to perform upgrades on Angular CLI applications.

The story is more or less:

``` base
ng install angular-firebase2

# Some time pass, new versions of angular, angular-firebase and angular-cli comes out.
ng upgrade
```

The app should still work with the latest versions of everything.

**We should try to make it as hard as possible to upgrade any other way.** This is to protect the user from making a mistake.

**Comment by zackarychapple** [comment]
Am I correct in assuming `ng upgrade` would also upgrade the generated files?  If so will we have incremental upgrade's that way when things go wrong we can let people know when / where there is a breaking change that they have to fix, then we can resume automated upgrade?

**Comment by delasteve** [comment]
I don't think this is relevant anymore due to the removal of `ng upgrade` and `ng init` in `beta.32`.

Upgrades going forward will have associated documentation on how to perform the upgrade.

**Comment by hansl** [comment]
Closed with v6.
