### ISSUE TITLE
When trying to run the index.html from dist\ folder  it is not working. Please help

### ISSUE THREAD

**Issue by idc1407** [angular/angular-cli#3140]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> Bet1.19.3

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by AlejandroDelRioAlbrechet** [comment]
@idc1407 Please try to build project with following command:

`ng build --bh ./ `

That will build application with base href which will be not absolute.

**Comment by idc1407** [comment]
Thank U very much.

It worked.
