### ISSUE TITLE
missing angular-cli-build.js

### ISSUE THREAD

**Issue by lichenbuliren** [angular/angular-cli#3142]
### OS
>  Mac OS X El Capitan 10.11.6

### Versions.
> angular-cli: 1.0.0-beta.19-3

I have the same problem [#558](https://github.com/angular/angular-cli/issues/558)，and I can't find the file `lib/broccoli/angular-broccoli-sass.js` in my global `angular-cli` directory。I can't find `angular-cli-build.js` either。

tks!

**Comment by spongessuck** [comment]
angular-cli has used Webpack instead of Broccoli since beta-14, so it's normal that you're not seeing those files.

**Comment by deebloo** [comment]
@lichenbuliren what @spongessuck said. https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14 here is a link to how to transition to the webpack build. I am not sure how up to date it is but it should put you in the right direction.

**Comment by lichenbuliren** [comment]
@spongessuck ，
so, what can i do if i wanna use scss variables with the angular-cli@latest

**Comment by spongessuck** [comment]
Check the angular-cli.json config file for an entry called styles, it'll be
a CSS file by default, but you can change it to scss. Then change the
actual file to scss and add your global styles/variables there. I'm not
sure if you can go reference those variables in your component styles,
though; I remember having trouble getting that to work.

**Comment by lichenbuliren** [comment]
@spongessuck , it's my fault, I found that I forget to import the `_variable.scc` file .
forgive me...

i will close this issue
