### ISSUE TITLE
Update version of the ember-cli to the latest version

### ISSUE THREAD

**Issue by Brocco** [angular/angular-cli#315]
Current version of the ember-cli is 2.4.2 and our basis is 1.13.15

**Comment by jkuri** [comment]
We need to check if there was some major changes when they changed from v1 to v2. If you look at their website the whole configurations are different. Please see https://github.com/ember-cli/ember-cli/blob/master/CHANGELOG.md, I think this is quite a *big* task and cannot be just changed to v2.

**Comment by hansl** [comment]
Actually the ember-cli now simply updated to follow the ember versioning. There's no major difference between v1 and v2.
