### ISSUE TITLE
Cmder/clink completion file (Lua)

### ISSUE THREAD

**Issue by mikesigs** [angular/angular-cli#3151]
Windows
angular-cli: 1.0.0-beta.19-3
node: 6.7.0
os: win32 x64

Hi guys,

I have written a completion script in Lua that provides command completion in [Cmder](http://cmder.net/), a popular console emulator on Windows based on ConEmu. The completions use [Clink](https://github.com/mridgers/clink) (bundled with Cmder) and enable ng completions to work without using Bash or Zsh in Windows. 

Would you be interested in including this as part of the completions offered by Angular-CLI?

If so, how would I go about doing a PR for this. I'm thinking it would basically be a documentation PR?

Thanks,
Mike

**Comment by hansl** [comment]
Hi Mike,

As much as this would be useful for the community, I think this is better served by an unofficial package. We can't maintain completion scripts for all shells out there, unfortunately.

`ng completion` is in a different spot as bash and zsh are already popular in both Linux, Mac and Windows world. This however would probably be better served as a package published on its own. You can have installation instructions in your README on your repo and let users install it the way it works best.

Sorry.
- Hans

**Comment by mikesigs** [comment]
Fair enough. If anyone comes across this issue and is looking for the completions file, I did a PR to the clink-completions project here.
https://github.com/vladimir-kotikov/clink-completions/blob/master/angular-cli.lua
