### ISSUE TITLE
Please help. This is using latest node js v7.1.0

### ISSUE THREAD

**Issue by PacejetRepository** [angular/angular-cli#3154]
Windows 10

ng new FirstApp

D:\2016\BeGreatWithNg>ng new FirstApp
Cannot find module '@angular/core'
Error: Cannot find module '@angular/core'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\TETAY\AppData\Roaming\npm\node_modules\angular-cli\node_modules\@ngtools\webpack\src\plugin.js:5:14)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\TETAY\AppData\Roaming\npm\node_modules\angular-cli\node_modules\@ngtools\webpack\src\index.js:6:10)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)

**Comment by hansl** [comment]
This has just been fixed. You should uninstall and  reinstall again. Sorry for the inconvenience.

**Comment by PacejetRepository** [comment]
I did all that and nothing happened?

**Comment by hansl** [comment]
What version do you see with `ng version`?

**Comment by PacejetRepository** [comment]
angular-cli: 1.0.0-beta.20-4
node: 7.1.0
os: win32 x64

**Comment by PacejetRepository** [comment]
npm install -g angular-cli 
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.                              npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue                                                     npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\TETAY\AppData\Roaming\npm\ng -> C:\Users\TETAY\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
C:\Users\TETAY\AppData\Roaming\npm
`-- angular-cli@1.0.0-beta.20-4
  +-- @angular/compiler@2.2.0                                                     +-- @angular/compiler-cli@2.2.0
  | `-- @angular/tsc-wrapped@0.4.0
  +-- @angular/core@2.2.0
  +-- lodash@4.17.2
  `-- reflect-metadata@0.1.8

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\angular-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by hansl** [comment]
Not sure what to tell you, but it works locally here. It seems you are installing `@angular/core`. If you do `npm list`, what does it say?

**Comment by hansl** [comment]
I feel this is a case where you are in a directory with an invalid `node_modules`.

**Comment by PacejetRepository** [comment]
What do you mean? Now i get this error

D:\2016\BeGreatWithNg\First-App>ng serve
** NG Live Development Server 7261ms building modules                                                                                                                                                                                   2ms add01297ms 115ms asset43ms emittingevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.process.stderr.write (D:\2016\BeGreatWithNg\First-App\node_modules\angular-cli\lib\cli\index.js:40:27)
    at Console.warn (console.js:51:16)
    at printErrorAndExit (D:\2016\BeGreatWithNg\First-App\node_modules\awesome-typescript-loader\node_modules\source-map-support\source-map-support.js:406:11)
    at process.emit (D:\2016\BeGreatWithNg\First-App\node_modules\awesome-typescript-loader\node_modules\source-map-support\source-map-support.js:419:16)
    at process._fatalException (bootstrap_node.js:292:26)
                                      7023ms add11423ms 132ms asset43ms emitting
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.process.stderr.write (D:\2016\BeGreatWithNg\First-App\node_modules\angular-cli\lib\cli\index.js:40:27)
    at Console.warn (console.js:51:16)
    at printErrorAndExit (D:\2016\BeGreatWithNg\First-App\node_modules\awesome-typescript-loader\node_modules\source-map-support\source-map-support.js:406:11)
    at process.emit (D:\2016\BeGreatWithNg\First-App\node_modules\awesome-typescript-loader\node_modules\source-map-support\source-map-support.js:419:16)
    at process._fatalException (bootstrap_node.js:292:26)

**Comment by PacejetRepository** [comment]
you can close this now. I reverted back to v6.9.1 LTS and all my initial problems are gone. Please next time don;t release something that you haven't tested as working.

**Comment by jmesa-sistel** [comment]
@hansl @PacejetRepository 
I have the same issue using node 7.1.0
Why is this closed? 
I have had to revert back to v6.9.1
At this moment angular-cli is not compatible with node 7.1.0
I am using windows 10

**Comment by jbeja** [comment]
I have this very same issue on Windows 10.

```npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\browser-sync\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})```



After that installation stops.

**Comment by jonasschulte** [comment]
And the same issue on Ubuntu 16.04:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by tforster** [comment]
Folks, I am here after googling the same error as it pertains to setting up Swagger tools. I believe it is because I am running `npm install` inside the Linux Subsystem for Windows which is relatively new to Windows 10. My hypothesis is that the particular module is confused between the host OS (Windows 10) and the filesystem (Linux). @jonasschulte @jbeja @PacejetRepository are you running npm in cmd, Powershell, Git bash or LSW? Trying to see if we have a consistent pattern.

**Comment by WALR** [comment]
The same issue on Deepin 15.3 x64, node v6.9.1. I reverted back to node v6.9.1 and same issue.

`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/ionic/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

**Comment by Freddessson** [comment]
Looks similar to my warnings:
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\angular-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.`

**Comment by SleekDevigner** [comment]
This is similar to the warning I had too while trying to install browser -sync. I am using a windows 10 and node version 6.9.5.

### npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\browser-sync\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

is there any way to correct the problem in order to clear the warning?

**Comment by ngooide** [comment]
same goes here.
node v7.2.1
ubuntu 14.04

**Comment by Danilo-Araujo-Silva** [comment]
Same here:
node v7.6.0
Ubuntu 14.04.5 LTS

How to solve this? I'd appreciate a clean install without any issues.

**Comment by ronaldo-getreveel** [comment]
any update?

**Comment by tolawho** [comment]
Same here:
node v7.7.1, npm 4.1.2
windows 10 x64
...

**Comment by Adesubomi** [comment]
Please someone should come out and help out on this issue. Its screwing with my time...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by tolawho** [comment]
@Adesubomi see my comment above.

**Comment by lisa13** [comment]
Anyone? :(

**Comment by tolawho** [comment]
@lisa13 add option **--no-optional** at the end of command.

**Comment by chekkanaveen** [comment]
@lisa13  try this command 
npm install -g angular-cli

**Comment by lisa13** [comment]
@chekkanaveen I have installed the latest angular version:   npm install -g @angular/cli
but no use!

**Comment by lisa13** [comment]
@tolawho Thanks I tried that as well, no changes so far! I am uninstalling everything and reinstalling again. If this doesn't work either I am changing my OS :/

**Comment by msaiyaff** [comment]
Still facing this issue after the @angular/cli v.1.0.0. What is actually causing this error?

**Comment by dvk2591** [comment]
I have node v6.10.0 on my windows 7 machine. I am getting the below eror in the output window when I try to save package.json file. 
Error:

**npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})**

I am unable to load gulp tasks due to this.

Please help me resolve this issue.

**Comment by vprasanth** [comment]
Node version: 7.7.3
NPM: 4.1.2
ng-cli: 1.0.0

Same issue: 
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by interaminense** [comment]
I was able to work by going back to the 2.15.11 version of npm

**Comment by Danilo-Araujo-Silva** [comment]
Although that I have the same issue, as I pointed above, for me is just a non clean install.
Everything works without problem.

I'm using, for now, `npm` 4.2.0, `node` 7.8.0, `n` 2.1.6.

**Comment by Ajith55** [comment]
Any update??

**Comment by macroramesh6** [comment]
same issue.. Any updates?

**Comment by Ajith55** [comment]
Yeah, worked for me, Reinstall NodeJs

**Comment by github-cloudyi** [comment]
Hey guys , I was wondering if this question is still active 

I am running on 

Windows 10 ,
node: 6.10.2 LTS 
npm: 3.10.10

I dont have this issue because of the angular-cli but instead with **laravel**, everytime I try to "npm install"  it shows the following errors:


**npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})**


I already tried what most people did , like reinstalling node js, or downgrading to the versions mentioned above (6.9.1LTS , 7.8.0)

Still not working , anyone out there got a new solution? It would really help me out , been stuck with this issue for hours now. Thank you in advance :>

**Comment by shijilesh** [comment]
try this 

npm cache clear
npm install --no-optional

**Comment by juandiego26** [comment]
@shijilesh yeah, this worked for me.

**Comment by qwertyuiop6** [comment]
The same issue on Deepin 15.4

**Comment by mox63** [comment]
Ubuntu 16.04 LTS + Node v6.10.3 LTS + npm 3.10.10
Same issue

Resolve with (thx @shijilesh)
npm cache clear
npm install -g forever express --no-optional

**Comment by roughmatrix** [comment]
Resoved with 

`npm cache clear
npm install -g forever express --no-optional`

Thanks @mox63 & @shijilesh

**Comment by nhattinit310** [comment]
i hope it work for you
npm cache clear
npm install angular-route --no-optional

**Comment by ForzaGreen** [comment]
Thanks, this worked for me:
```
npm cache clear
npm install -g [your-package] --no-optional
```

**Comment by lorduwahz** [comment]
npm cache clear
npm install --no-optional
@shijilesh

**Comment by Zainab-Ally** [comment]
"www" directory cannot be found. Please make sure the working directory is an Ionic project.
There was an error serving your Ionic application: "www" directory cannot be found. Please make sure the working directory is an Ionic project.


I need help please I cannot proceed with the program

**Comment by nhattinit310** [comment]
can you show me a error images, i hope i can help you
