### ISSUE TITLE
Request: Change bundle file name

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#3155]
My issue is pretty simple: The generated JS bundle names are always main.bundle.js / styles.bundle.js, etc. 
When we deploy a new release to production, the site stops working to random users as some or all of the scripts / artefacts are retrieved from cache.
An option would be to have the option in Angular CLI to append a random string to the generated bundle file names.
Or is this not the right way? We are struggling to find a proper solution for this.

**Comment by clydin** [comment]
Production builds add a file hash to the output filnames.  Are you building with the --prod option?

**Comment by rolandoldengarm** [comment]
Ah yeah of course. Then my caching issue is something different :)
