### ISSUE TITLE
Paths should follow the styleguide

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#316]
Following the Houston app demo;

- [ ] The directory structure need to be only including routes (not components, services or pipes). Components, services and pipes need to be in an `_` directory inside the route 
  The following commands need to be changes (feel free to check those that are solved):
  - [ ] `new`: simply a matter of updating the scaffold.
  - [ ] `generate`: 
    - [ ] `component`/`service`/`pipe`: need to be added to an `_` directory in the route specified. For example, `ng generate component foo/bar/blah` should be generated in the directory `foo/bar/_/blah`. If the `_` is included then we don't need to add it (an `_` route would be invalid here).
    - [ ] `route`: the scaffold need to include an empty `_` directory under the route itself.

- [ ] Adding an `index.ts` file to all scaffolds that export the component/route/service/pipe of that directory.

I think that's it for this.

**Comment by filipesilva** [comment]
We should put off merging this this PR until the official style guide is in. Otherwise users will have no idea nor guidance as to how the structure is meant to be used.

**Comment by hansl** [comment]
That is the official styleguide though. The document is going to adhere to this, not the other way around.

**Comment by filipesilva** [comment]
The repo is not a document. We can't direct users to the repo for insights on style guide issues. 

We need a document that users can read and understand before we change the CLI to use it.

**Comment by Brocco** [comment]
At the current state of the project (pre-alpha) I think we can make changes without documentation in place. Especially given our milestone goals.

**Comment by mattcarp** [comment]
Hi @hansl. Would you have a link to the repo mentioned?

**Comment by Brocco** [comment]
Fixed via #427
