### ISSUE TITLE
No longer possible to use templating to generate index.html

### ISSUE THREAD

**Issue by 7er** [angular/angular-cli#3161]
https://github.com/angular/angular-cli/commit/d3fd8b0 broke my build

### OS
Linux Ubuntu 16.04

### Versions.
1.0.0-beta.20-4

### Repro steps.
Change index.html to index.html.ejs. Change angular.cli.json#apps[0].index to "index.html.ejs". 
Have some <%= %> code in index.html.ejs, but observe that it is emitted as index.html.ejs instead of index.html which it did in beta.19-3.

### Mention any other details that might be useful.

The templating feature for generating index.html that was present in beta.19.3 was very useful and allowed us to manipulate the final index.html very easily. I understood that someone wanted to create another filename but I think generating index.html with some simple templating is a quite common case

**Comment by clydin** [comment]
I don't think templating index.html is a supported scenario; similar to using internal functions of a library, expect it to break or disappear.

**Comment by 7er** [comment]
Fair enough, what is the "clean" way to build in such a fashion with ng build? Is there another way to hook into the build process?

**Comment by clydin** [comment]
Unfortunately, as of now there is not.  An add on system is planned for post-1.0.

**Comment by filipesilva** [comment]
Index templating was an unintended side effect, it was never a feature we wanted to offer. I'm sorry the update broke your build though. I don't have any alternative for now.
