### ISSUE TITLE
When  "--code-coverage" does not present, text summary should not be printed out

### ISSUE THREAD

**Issue by huyph** [angular/angular-cli#3166]
### OS
Mac OSX - El Capitan

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 6.4.0
os: darwin x64

### Repro steps.
- Create a new app using `ng new` command
- Modify remapIstanbulReporter config in karma.conf.js, to the following:
```javascript
    remapIstanbulReporter: {
      reports: {
        'text-summary': null, // 'null' means falling back to the default console.log
      }
    },
```
- Execute `ng test` (NOTE: without `--code-coverage`)

### The log given by the failure.
```
$ ng test
....
=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================

```

### Expected behavior
The coverage summary above should not be printed out at all.

### Mention any other details that might be useful.
Maybe it is an issue with `karma-remap-istanbul`.

**Comment by filipesilva** [comment]
Hm... I understand the argument. We do some config manipulation so maybe we should remove the `remapIstanbulReporter` entry when we're not doing code coverage.

**Comment by filipesilva** [comment]
This is fixed in recent versions.

**Comment by huyph** [comment]
cheers
