### ISSUE TITLE
Usage section in README : ng --help isn't working. 

### ISSUE THREAD

**Issue by ganeshbabu91** [angular/angular-cli#3168]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.20-4
node: 6.6.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Type ng --help and press enter

### The log given by the failure.
> Normally this include a stack trace and some more information.
The specified command --help is invalid. For available options, see `ng help`.

### Mention any other details that might be useful.
ng help is working but not ng --help. Do we need to update the usage section to say "ng help" ?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Meligy** [comment]
Related: https://github.com/angular/angular-cli/pull/3159

**Comment by Brocco** [comment]
The associated PR addressed the documentation, reopening to fix the actual issue with `ng --help`
