### ISSUE TITLE
BUG - 3rd party script can not load propertly

### ISSUE THREAD

**Issue by AmitMY** [angular/angular-cli#3172]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: win32 x64

### Repro steps.
> Install a new app. As stated here: http://valor-software.com/ng2-charts/, you need to include the "node_modules/chart.js/src/chart.js" as a script. The right way is to add it to the "scripts" under app.
This returns an error: 

### The log given by the failure.
> VM2787:4Uncaught ReferenceError: require is not defined(…)(anonymous function) @ VM2787:4module.exports @ addScript.js:9494 @ chart.js?ef5d:1__webpack_require__ @ bootstrap 7ccc16a…:52947 @ addScript.js:10__webpack_require__ @ bootstrap 7ccc16a…:52webpackJsonpCallback @ bootstrap 7ccc16a…:23(anonymous function) @ scripts.bundle.js:1
lang.js:88Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.

### Mention any other details that might be useful.
> This is a 3rd party including problem. I post it here because it does work in the normal html way

**Comment by Meligy** [comment]
Try opening `angular-cli.json` and finding the `scripts` array, then inside it add:

```
"../node_modules/chart.js/src/chart.js"
```

**Comment by AmitMY** [comment]
Thanks @Meligy , but that is what I did.
> The right way is to add it to the "scripts" under app.
This returns an error:

**Comment by valorkin** [comment]
@AmitMY have you created an issue in ng2-charts? if yes link it here please

**Comment by Meligy** [comment]
I have a feeling the instructions in that repo are wrong.

When you include libraries in `scripts`, they are usually bundled files that do not need further processing. I wonder why the path has `src` in there.

Maybe try this instead:

```
"../node_modules/chart.js/dist/Chart.bundle.min.js"
```

**Comment by AmitMY** [comment]
@Meligy Yes that works, thanks a lot.
I will now create an issue on their repo, asking them to link to the normal file.
