### ISSUE TITLE
Angular Lazy loading modules

### ISSUE THREAD

**Issue by electricfire** [angular/angular-cli#3174]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: win32 x64

### Repro steps.
Created the package through the CLI and added my files from a different package.  In my previous package i was using systemjs .  I was lazy loading the modules calling a service from the app.component this service essentially pushes new module path's to the router configuration.  I just migrated my module and router services into the new CLI project and it fails to find the module.  However applying the same route path the normal way 

const routes: Routes = [
    { path: 'directory', loadChildren: "app/default/app.default.module" },
];

This works just fine but through the service as shown below

this.router.config.push({ path: 'directory', loadChildren: this.res.test }); - where the variable is a webapi lookup fails.  As mentioned above using systemjs way all worked just fine

### The log given by the failure.
error_handler.js:47 EXCEPTION: Uncaught (in promise): Error: Cannot find module 'app/default/app.default.module'.
Error: Cannot find module 'app/default/app.default.module'.
    at webpackEmptyContext (http://localhost:4200/main.bundle.js:53193:8)
    at SystemJsNgModuleLoader.loadAndCompile (http://localhost:4200/main.bundle.js:61659:40)
    at SystemJsNgModuleLoader.load (http://localhost:4200/main.bundle.js:61651:60)
    at RouterConfigLoader.loadModuleFactory (http://localhost:4200/main.bundle.js:15179:128)
    at RouterConfigLoader.load (http://localhost:4200/main.bundle.js:15170:81)
    at MergeMapSubscriber.project (http://localhost:4200/main.bundle.js:72265:111)
    at MergeMapSubscriber._tryNext (http://localhost:4200/main.bundle.js:10867:27)
    at MergeMapSubscriber._next (http://localhost:4200/main.bundle.js:10857:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:4200/main.bundle.js:3645:18)
    at ScalarObservable._subscribe (http://localhost:4200/main.bundle.js:52065:24)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
Just to clarify, are you lazy loading the modules yourself via the mentioned service?

The CLI statically analyzes the routes at build time and handles the lazy loading and module bundling for you.

**Comment by electricfire** [comment]
Clydin,

Yes i am loading the modules post build via the Router.  The problem is i would like to do this during the build phase but i get a message saying that i need to have atleast one component loaded before i can access the Router hence why i am calling the service after my first component loads.  If i am pushing this into the Router configuration along with the path why can it not access the module?  Could you please clarify about loading the module manually,  FYI i am trying to put together a multi-tenant app where it will obtain the routes which will be stored server-side and of-course I only want the to access links relative to them.  I guess you could argue that i can load all the lazy modules statically regardless as they would only get loaded when accessed,  I am looking for the right approach if you could assist.  Final question how does this work with systemJS

Thanks

**Comment by filipesilva** [comment]
We don't support generating the lazy loaded routes dynamically, because we need to be able to statically analyse the code to bundle stuff. That's the kind of thing you can only reasonably do with SystemJS I believe.
