### ISSUE TITLE
NgFactory not generated when creating a bundle

### ISSUE THREAD

**Issue by rafiwardak2003** [angular/angular-cli#3178]
I am using Webpack 2 and it seems that a bundle is created and everything works fine. Why are there so many examples given where a factory is generated? Is that a must? Also, is it okay to use platformBrowserDynamic to load this bundle? I see examples where platformBrowser is used to load an ngFactory. Is that a must? I am doing this and it seems to work, but not sure the overhead:

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app';
platformBrowserDynamic() .bootstrapModule(AppModule)

**Comment by Meligy** [comment]
The CLI translates the platform code from dynamic to AoT, and creates the factories, but this is all abstracted away from you. If you want to see it you run something like `./node_modules/.bin/ngc -p ./src`, but this is not how it's intended to be used. The CLI takes care of all that and you just get the result and not worry about intermediate steps or multiple bootstrapping files, etc.

**Comment by rafiwardak2003** [comment]
Okay I suspected that was the case. Thank you for confirming.

Should we be using platformBrowserDynamic or just platformBrowser to load my bundle generated?

**Comment by Meligy** [comment]
Whatever `ng new ...` generates I guess?

Unless you are suggesting the template needs updating...

**Comment by hansl** [comment]
The Factories are generated in memory; you won't find them on your disk.
