### ISSUE TITLE
Provide options to receive webpack --json 

### ISSUE THREAD

**Issue by JohannesRudolph** [angular/angular-cli#3179]
### Versions
angular-cli: 1.0.0-beta.20-4
node: 6.9.1

### Request
It would be very helpful if angular-cli did provide an option to receive output of `webpack --json` during `ng build` for further analysis of webpack chunks and code size (e.g. using the excellent webpack-visualizer: https://chrisbateman.github.io/webpack-visualizer/ or https://webpack.github.io/analyse/)

**Comment by Destreyf** [comment]
@JohannesRudolph I think this is a great idea for being able to produce dumps of information, in an attempt to see if it was possible, i ended up modifying 1 file and installing 1 package.

For those willing to play around with their node_modules for some fun, replace `node_modules/angular-cli/models/webpack-config.js` with this [raw gist](https://gist.githubusercontent.com/Destreyf/f795c10a681ae63339921d01ed449e31/raw/ba99bd03f0dcf6596c3b4078e258001fa88277dc/webpack-config.js) or you can [view the gist](https://gist.github.com/Destreyf/f795c10a681ae63339921d01ed449e31)

and then run `npm install --save-dev webpack-stats-plugin` and then whenever you do a build the stats are dumped in the outDir (typically `dist/stats.json`).

**Comment by filipesilva** [comment]
I agree that this would be helpful, but am unsure if we want to do it anytime soon because it would break the build system abstraction.

**Comment by Destreyf** [comment]
@filipesilva I agree this would be nice to have, the build system functioning is definitely more important than some stats, i would opt for a having people make the simple change i made if the stats are important to them (maybe for integration purposes).  I've definitely grown accustomed to using the CLI and openly hacking away at anything that i'm curious on.
