### ISSUE TITLE
Sass doesn't work

### ISSUE THREAD

**Issue by zh-wowtv** [angular/angular-cli#3188]
I got the follow error message when I generate a project with --style=sass:

```
ERROR in ./~/css-loader?sourcemap!./~/postcss-loader!./~/sass-loader?sourcemap!./src/styles.sass
Module build failed: 
body {
     ^
      Invalid CSS after "body {": expected "}", was "{"
      in /Users/myproject/src/styles.sass (line 2, column 7)
 @ ./src/styles.sass 4:14-179
 @ multi styles

```

Then I changed the `angular-cli.json` to replace all sass into `scss`. It works fine then. Does that mean we should generate the project with --style=sass?

**Comment by clydin** [comment]
SASS uses an indented syntax.  Based on the error received, everything appears to be working.

**Comment by zh-wowtv** [comment]
@clydin I see. Then I prefer scss more. Thanks.

**Comment by hansl** [comment]
Closing as fixed.
