### ISSUE TITLE
How to compress js as small as possible by ng build -prod

### ISSUE THREAD

**Issue by suplch** [angular/angular-cli#3189]
I make a angular2 project by angular-cli tool, and write little business code.
However, In dist folder, the output file main.xxxxxxxxxxx.bundle.js still have 1M size.
Are there good way to reduce its size as small as posible.

**Comment by grizzm0** [comment]
With --prod and --aot your js.gz file should be around 250-300kb.

**Comment by deebloo** [comment]
@suplch like @grizzm0 said. using the --prod and --aot flag should give you a hello world app between 80 and 100kb depending on which angular modules you are using. My company has one angular2 app in prod now and it is sitting ~210k for the main bundle.

**Comment by suplch** [comment]
Thanks very much, I add --aot flag, the main bundle file reduce from 1M to 780K, that is very ok.
Another question, I explore website angular.io about "AoT" and "Tree Shaking", Is Our "--aot" flag from "Tree Shaking" principle?

**Comment by a-pavlov-parc** [comment]
`ng build --prod --aot` generate `.map`. One of them is quite big. Do I something wrong?

http://take.ms/0wBTz

**Comment by grizzm0** [comment]
@a-pavlov-parc  Those are just source maps. Nothing a "normal" user will download. Those are for debugging purposes.

**Comment by a-pavlov-parc** [comment]
@grizzm0 please let me know is there a way to turn generating of that off?

**Comment by elvirdolic** [comment]
@a-pavlov-parc wait for the new release. It will have this option. Check latest master commit.

**Comment by Olgagr** [comment]
@deebloo I took brand new application generated by angular-cli and built it with --prod and --aot flag and the size of main.bundle.js.gz file is 353kb. It is quite a lot for application that does nothing. You mentioned that the size should have been between 80 and 100kb. What is the source of this difference ?

**Comment by filipesilva** [comment]
Closing as the most excellent @grizzm0, @deebloo and @elvirdolic have already answered everything, cheers!

To turn off sourcemap generation you can use `--no-sourcemap`.

**Comment by PardeepWildnet** [comment]
@filipesilva can you please explain the function of those `.map` files at the time of `ng build` ? 
also once i ran ,`ng build --aot --prod` angular will automatically remove `.map` files , i haven't set `sourceMap` to `false` yet. how's it possible any comments on this ?

**Comment by grizzm0** [comment]
@PardeepWildnet Source maps are no longer generated by default during production build as this "exposes" your non uglified/minimized application. Aot is also default these days so `ng build --prod` is enough. If really want to use sourcemaps in prod you'd have to do `ng build --prod --sourcemap`

**Comment by renilbabu03** [comment]
The following solution assumes you are serving your dist/ folder using nodejs. Please use the following app.js in root level


    const express = require('express'),http = require('http'),path = require('path'),compression = require('compression');
    
    const app = express();
    
    app.use(express.static(path.join(__dirname, 'dist')));
    app.use(compression()) //compressing dist folder 
    app.get('*', (req, res) => {
      res.sendFile(path.join(__dirname, 'dist/index.html'));
    })
    
    const port = process.env.PORT || '4201';
    app.set('port', port);
    
    const server = http.createServer(app);
    server.listen(port, () => console.log('Running at port ' + port))

Make sure you install dependencies;

    npm install compression --save
    npm install express --save;

Now build the app

    ng build --prod --build-optimizer


> If you want to further compress the build say reduce 300kb(approx)
> from , then follow the below process;

Create a folder called **`vendor`** inside the **`src`** folder and inside vendor folder create a file **`rxjs.ts`**  and paste the below code in it;


    export {Subject} from 'rxjs/Subject';
    export {Observable} from 'rxjs/Observable';
    export {Subscription} from 'rxjs/Subscription';

And then add the follwing in the **`tsconfig.json`** file in your angular-cli application;

    "paths": {
          "rxjs": [
            "./vendor/rxjs.ts"
          ]
        }

 
This will make your build size way too smaller. In my project I reduced the size from 11mb to 1mb.
Hope it helps

**Comment by ashishsober** [comment]
is any body having idea to reduce the size of main.ts file of Angular6 ,as i already tried 
ng build --prod --build-optimizer
ng build --aot --prod 

m using rxjs6 ,search alot but haven't got the proper answer for the currentt version on Angular

**Comment by HardikDG** [comment]
@re

> The following solution assumes you are serving your dist/ folder using nodejs. Please use the following app.js in root level
> 
> ```
> const express = require('express'),http = require('http'),path = require('path'),compression = require('compression');
> 
> const app = express();
> 
> app.use(express.static(path.join(__dirname, 'dist')));
> app.use(compression()) //compressing dist folder 
> app.get('*', (req, res) => {
>   res.sendFile(path.join(__dirname, 'dist/index.html'));
> })
> 
> const port = process.env.PORT || '4201';
> app.set('port', port);
> 
> const server = http.createServer(app);
> server.listen(port, () => console.log('Running at port ' + port))
> ```
> 
> Make sure you install dependencies;
> 
> ```
> npm install compression --save
> npm install express --save;
> ```
> 
> Now build the app
> 
> ```
> ng build --prod --build-optimizer
> ```
> 
> > If you want to further compress the build say reduce 300kb(approx)
> > from , then follow the below process;
> 
> Create a folder called **`vendor`** inside the **`src`** folder and inside vendor folder create a file **`rxjs.ts`** and paste the below code in it;
> 
> ```
> export {Subject} from 'rxjs/Subject';
> export {Observable} from 'rxjs/Observable';
> export {Subscription} from 'rxjs/Subscription';
> ```
> 
> And then add the follwing in the **`tsconfig.json`** file in your angular-cli application;
> 
> ```
> "paths": {
>       "rxjs": [
>         "./vendor/rxjs.ts"
>       ]
>     }
> ```
> 
> This will make your build size way too smaller. In my project I reduced the size from 11mb to 1mb.
> Hope it helps

By this, we are getting circular definition errors for the modules which are exported manually from vendor/rxjs.ts
