### ISSUE TITLE
Add ReadMe tip for speeding up unit tests

### ISSUE THREAD

**Issue by JeremyTCD** [angular/angular-cli#3190]
### OS?
Windows 10

### Version
v1.0.0-beta.20-1

### Repro steps
1.  Run `ng test` with chrome in focus. 

2. Run `ng test` with chrome minimized. 

3. Test run time can differ by more than an order of magnitude.

### Other details that might be useful
I was running ~200 tests (30 of them were component tests). Execution time was either ~0.7s or ~20s and the test runner would eventually crash. Turns out the slow and unstable tests were a result of chrome being out of focus. Chrome windows that are out of focus get [throttled](https://bugs.chromium.org/p/chromium/issues/detail?id=485425&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=).  

Looking through the rebuild speed thread, #1980, I noticed some complaints about `ng test` test speed. Specifically [this comment](https://github.com/angular/angular-cli/issues/1980#issuecomment-255026095). I'd like to suggest including a tip in ReadMe to keep chrome in focus. Since this is quite a hard to diagnose issue I think it will be very helpful.

**Comment by filipesilva** [comment]
The problem with `ng test` in that thread was mostly fixed by https://github.com/angular/angular-cli/pull/2840, because at the time code coverage was always being added.

A comment like this would be nice, even though there isn't anything else we can do. Would you be interested in adding it?

**Comment by antonybudianto7** [comment]
no blueprint update after https://github.com/angular/angular/pull/16250/files ? @filipesilva

**Comment by filipesilva** [comment]
Newer karma-chrome-launcher versions fix this automatically.
