### ISSUE TITLE
Code Coverage Not Propagating Through Top Level Folder

### ISSUE THREAD

**Issue by markheron91** [angular/angular-cli#3192]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
While running tests using ng test, opening the coverage main index.html shows nothing - need to go into src/ folder and open each one individially to see code coverage. As far as I remember the top level index.html is supposed to show everything and give an overall view.

### The log given by the failure.
> Normally this include a stack trace and some more information.
![angualr-cli-coverage-ss-1](https://cloud.githubusercontent.com/assets/22199294/20432243/1dfac3fc-ad96-11e6-8fb6-502532621313.PNG)
![angular-cli-coverage-ss-2](https://cloud.githubusercontent.com/assets/22199294/20432246/210c7248-ad96-11e6-9587-2e841b46dec4.PNG)

### Mention any other details that might be useful.
Not entirely sure that this is a problem with angular-cli or a problem with karma-remap-instanbul itself.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
@markheron91 at least from your screenshot everything looks like it is working correctly. What exactly is the issue you are referring to?

**Comment by markheron91** [comment]
@deebloo Sorry probably didn't explain it very well. Before I started using the angular-cli when I looked at the index.html generated in the top level of the coverage folder I could see the tests for each folder inside my entire app rather than just the individual files in the folder. In this case the first screenshot would have stuff like /app and /app/auth etc instead of being completely empty, and then I could drill down into the index.html files in the subsequent folders by clicking on each link, which doesn't seem to be possible anymore.

In contrast to the screenshots above, I've found quite an old coverage report from an older version of the app before I started using angular-cli. It shows the output in the top level index.html file and you can see that it shows all of the subfolders in the app

![angular-cli-coverage-ss-3](https://cloud.githubusercontent.com/assets/22199294/20519886/a1f39612-b09c-11e6-9a8f-ad36b336b31c.PNG)

**Comment by filipesilva** [comment]
Huh, I see what you mean. Code coverage is kinda useless if it just shows `tests.ts`. Will investigate.

**Comment by delasteve** [comment]
Just tried this on a new build using:

```
angular-cli: 1.0.0-beta.26
node: 6.7.0
os: darwin x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
```

![screencap-1](https://cloud.githubusercontent.com/assets/595925/22424093/dc431304-e6c2-11e6-830f-e4a8925f7595.png)

![screencap-2](https://cloud.githubusercontent.com/assets/595925/22424090/da8bd19a-e6c2-11e6-9968-212984c95d65.png)

**Comment by filipesilva** [comment]
According to @delasteve it seems to be fine now. 
@markheron91 let me know if you're still experience the original issue.

**Comment by maxime1992** [comment]
I do have the same problem. I tried to create a new project from scratch and it's working well.

In my project, only few files are displayed : 
![image](https://cloud.githubusercontent.com/assets/4950209/24704564/87385b66-1a08-11e7-8775-4491e2313d92.png)

![image](https://cloud.githubusercontent.com/assets/4950209/24704626/be470ecc-1a08-11e7-8214-007289dc389a.png)

(I really, really have more files than that).

If you want to give a try @filipesilva : 
```
git clone git@gitlab.com:linagora/petals-cockpit.git
git checkout b7fac7a412a
cd petals-cockpit/frontend
yarn
ng test --code-coverage
```

Let me know if you need more information :)
