### ISSUE TITLE
Can't generate files after renaming of the top component (app)

### ISSUE THREAD

**Issue by carttrac** [angular/angular-cli#3194]
### Version: 1.0.0-beta.20-4

ng g component test
installing component
Invalid path: ...\src\app"" is not a valid path.

**Comment by lordmat0** [comment]
Having the same issue

In Angular-cli
"root": "src/main/app",

ng g component test
installing component
Invalid path: "/Users/mat/idea/project/src/main/app/app"" is not a valid path.

**Comment by deebloo** [comment]
currently the when the cli will only generate components into the app directory.

**Comment by filipesilva** [comment]
@Brocco this seems related to generators, maybe auto-adding the imports. Can you have a look?

**Comment by Brocco** [comment]
@carttrac & @lordmat0 are you still experiencing this issue?

**Comment by Brocco** [comment]
I have not heard any feedback whether this is still an issue. Can you please confirm whether you are still experiencing this issue or not? Thanks!

**Comment by lordmat0** [comment]
Sorry for the delay, will check in the next few days

**Comment by lordmat0** [comment]
I tried changing to src/main2 which worked correctly with generating so closing. Thank you!

**Comment by Brocco** [comment]
Thanks, glad everything is working for you!
