### ISSUE TITLE
ng serve problem

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#3196]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX (Capitan?)

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 4.6.0
os: darwin x64

### Repro steps.

start with 
ng serve

then I run in the code:

```
this.http.get('http://localhost:4200/assets/non-exists/image.jpg')
                .catch((err: any): any =>
                {
                    console.log('err = ' + err);
                })
                .subscribe((res: Response) =>
                {
                    console.log('sub: ' + res);
                });
``` 

it always return 200 as everything is ok, it should behave like any other server returning Not Found

### Mention any other details that might be useful.
I am trying to test if the resource exists under assets folder, but the http requests always givess me response status 200 like the file exists.

I know it might not nessesarry relates to this CLI, but the library you are using to serve these resources, but still its angular-cli

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
What does the response contain?

**Comment by fkolar** [comment]
The response contains HTML along with its content. Just like a router woudl kicked it and redirect the requests _GIVE ME IMAGE_ to main page index.html page - the app page.

I havent looked what exactly page it is. 

-Fk

**Comment by filipesilva** [comment]
The dev server is configured to fallback to `index.html` for all request it doesn't know. This is required for routing in SPAs.

**Comment by fkolar** [comment]
I see. Thanks
