### ISSUE TITLE
ng github-pages:deploy creating wrong urls in CSS

### ISSUE THREAD

**Issue by sandeeprana011** [angular/angular-cli#3197]
### OS?
>  Mac OSX (Sierra)

### Versions.
> angular-cli: 1.0.0-beta.19-3
> node: 6.7.0
> os: darwin x64

### Repro steps.
ng serve creates the complete path for relative paths in CSS 
Like if I add  `/app/images/icon.png` this will be something like `http://localhost:4200/app/images/icon.png`
But when I deploy the site using `ng github-pages:deploy` it doesn't create complete paths . Relative path remains as it is Like `/app/images/icon.png`

### The log given by the failure.
> Build was successful without any error

**Comment by taylorjb** [comment]
Try removing the preceding forward slash such that `/app/images/icon.png` becomes `app/images/icon.png` to work the relative paths.

**Comment by hansl** [comment]
Closing this as a solution has been suggested.
