### ISSUE TITLE
ng new project --skip-npm hangs

### ISSUE THREAD

**Issue by NHKK** [angular/angular-cli#3208]
OS windows 10
node version 7.1.0
npm version 3.1.0

I tried ng new project hangs at installing packages .... then I tried ng new project --skip-npm and still hangs but now it wont even get to installing packages and hangs. I tried clean cache and uninstall then clean cache then reinstall all of these methods failed

**Comment by clydin** [comment]
There are issues with using node 7.  Try with latest v6

**Comment by filipesilva** [comment]
We don't currently support node7 as @clydin mentioned, but it shouldn't hang in node6 as you describe. 

I can't repro myself, but if there's a repro I can investigate.

**Comment by filipesilva** [comment]
Closed as inactive.
