### ISSUE TITLE
Error When deploy angular 2 cli to github

### ISSUE THREAD

**Issue by hoanggianguet** [angular/angular-cli#3209]
> Please provide us with the following information:
> ---------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/15229287/20461299/ea6a16c2-af2b-11e6-8da9-5bfbb8dbfa96.png)

I deploy angular 2 project to github but error. Can You help me fix it. Thanks

**Comment by Destreyf** [comment]
@hoanggianguet It looks like you need to build with the following argument

`--base-href /cucucu/`

As you can see from the network requests it thinks they'll be in `https://hoanggianguet.github.com/groceries/X.js` 
But from what i can tell about the project, are you modifying the files/path at all manually that would case it to try to look in the `groceries` sub directory? (default base-href is just /)

**Comment by filipesilva** [comment]
@Destreyf's answer is spot on. You need to set the base href tag for github deployments.
