### ISSUE TITLE
Updating to new version ignores app root

### ISSUE THREAD

**Issue by qwert789** [angular/angular-cli#3212]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
Beta 20

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Changed angular-cli.json root folder, prefix,StyleExt 

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
When updating to new version of angular-cli, it ignores custom root and prefix defined in angular-CLI.json
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
This is a bug, but I should mention that the solution will likely be to remove `ng init` and actually make an `ng upgrade` that (for now) would mostly just look at updating `angular-cli.json` and `package.json`.

We shouldn't need user-code changes for upgrades anymore.

**Comment by filipesilva** [comment]
Closing as obsolete.
