### ISSUE TITLE
Skip tests in AoT compilation process

### ISSUE THREAD

**Issue by Serginho** [angular/angular-cli#3216]
### OS?
Ubuntu 16.04

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 4.6.0
os: linux x64

### Repro steps.
Was this an app that wasn't created using the CLI? Yes

### The log given by the failure.
```
›  $ ng build --prod --environment=dev --aot                  
                                                                                                  
  0% compiling
Cannot determine the module for class TestComponent in .../switch.component.spec.ts!
Cannot determine the module for class Test2Component in .../switch.component.spec.ts!
Cannot determine the module for class Test3Component in .../switch.component.spec.ts!
```

### Mention any other details that might be useful.

I think it would be great to skip testing with AoT because Angular AoT compiler doesn't detect the test host components module. This class declaration is only configured in TestBed. For this reason AoT causes this exception.

**Comment by elvirdolic** [comment]
This is fixed in the latest version. Please upgrade!

**Comment by Serginho** [comment]
Oh, that's true. Thanks.

**Comment by Serginho** [comment]
I have the same problem with Beta-31

@angular/cli: 1.0.0-beta.31
node: 6.9.1
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

**Comment by hccampos** [comment]
@Serginho #4701

**Comment by Serginho** [comment]
I replaced the code in node_modules in order to try if it works, and I have the same problem fixing the pattern `.replace(/\*\*/g, '(?:.*)')`

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/4924
