### ISSUE TITLE
Support node 7

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#3218]
Currently we do not support node 7. We should support it and add a Travis task as well.

**Comment by aderbas** [comment]
`ERR! node-sass@3.13.0 postinstall: `node scripts/build.js`` I'm using Node 6.9.1

angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: linux x64 Ubuntu 14.04

**Comment by hansl** [comment]
@jkuri you want to take this?

**Comment by jkuri** [comment]
yup, I'll take this.

**Comment by khalidabuhakmeh** [comment]
So it seems to work with `node 7.2.1`

![image](https://cloud.githubusercontent.com/assets/228256/21051099/a3bda110-bdec-11e6-9bf7-e2ce274096a4.png)

Great Job.... ¯\_(ツ)_/¯

**Comment by hansl** [comment]
Closing this as done.
