### ISSUE TITLE
chunkHash in filenames of inline & styles JS bundle not changing even if the content changes

### ISSUE THREAD

**Issue by maulsea** [angular/angular-cli#3221]
### OS?
> Windows 10

### Versions.
angular-cli: 1.0.0-beta.20-4
node: 4.4.4
os: win32 x64

### Repro steps.
Please note, I'm using LESS for pre-processing.

Whenever I run `ng build --prod`, I'm expecting chunkHash to be different for main, inline & styles bundle. However, I noticed, even though the content has changed, chunkHash is not changing for inline & styles bundle. This will most likely create caching issue, which it is supposed to resolve in first place. :)

Run 1 : http://i.imgur.com/vyftUs7.png
--- Change content of few less files & added a test service ---
Run 2 : http://i.imgur.com/2ts7lBt.png

### Any other details that might be useful.
I understand this could be an issue of a webpack than angular cli. But, since there is no way to alter webpack config for now & this being in important functionality for production builds, I am hoping this fix can be prioritized here.

**Comment by grizzm0** [comment]
Did you make any changes to any file located in apps[0].styles in angular-cli.json? Less files of your components gets compiled into the component itself and does not affect styles.[hash].bundle.css.

**Comment by elvirdolic** [comment]
When you use CDN this issue prevents the APP to run. It doesn't even bootstrap. Can we have a fix for that?

**Comment by maulsea** [comment]
@grizzm0 Thanks for getting back to me! You are correct, styles.[hash].bundle.css does change. But, issue persists with `styles.[hash].bundle.js` & `inline.[hash].bundle.js`.

**Comment by grizzm0** [comment]
If the content of the file does not change the hash will stay the same. inline.bundle.js and styles.bundle.js doesn't change just because you edit your styles. They contain the same content every time which basically is some webpack related stuff.

**Comment by maulsea** [comment]
@grizzm0 Ok, I did not know that. I will close this issue for now. Thanks for your help! :)
