### ISSUE TITLE
How to configure tests to import third-party modules

### ISSUE THREAD

**Issue by quanterion** [angular/angular-cli#3223]
What is the intended way to include 3rd-party components like Material2 to all specs?
So I can import MaterialModule in AppModule and can use Material components on any page, but how to include the same module for all test? By default after running ng test I'm getting errors like:
"md-nav-list" is not a known element

**Comment by deebloo** [comment]
@quanterion you would have to import your app module into your test module.

**Comment by filipesilva** [comment]
@deebloo's answer is very accurate 💃
