### ISSUE TITLE
Errors with zonejs v0.7.0

### ISSUE THREAD

**Issue by alexbyk** [angular/angular-cli#3227]
zone.js:21Uncaught ReferenceError: Zone is not defined

**Comment by FieryCod** [comment]
You have to add @types for it.

**Comment by the-destro** [comment]
I added the @types and still got an error with ng serve

**Comment by vcdassen-home1** [comment]
It's not just with ng-serve...it happens running under IIS as well.  It's a run-time issue when zone.js is run in the browser.  Adding the @types for zone.js won't help.  I reverted my zone.js back to 0.6.xx and everything was fine.  I haven't tried the cli@beta.21 yet.  We are on the bleeding edge here :)

**Comment by vcdassen-home1** [comment]
looks like it is fixed with a combination of angular-cli beta.21 and zone.js 0.7.2 (latest), at least for running ng serve.
