### ISSUE TITLE
Installation failure on Ubuntu Node 7: node-sass@3.13.0 postinstall failed

### ISSUE THREAD

**Issue by wcxaaa** [angular/angular-cli#3228]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?

Linux Ubuntu x64

### Versions.

node v7.1.0
npm  v3.10.9

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Angular cli installation failure.

### The log given by the failure.

```
node-sass@3.13.0 postinstall /usr/local/lib/node_modules/angular-cli/node_modules/node-sass
node scripts/build.js
```

Binary found at /usr/local/lib/node_modules/angular-cli/node_modules/node-sass/vendor/linux-x64-51/binding.node
Testing binary
Bus error (core dumped)
/usr/local/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/angular-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli@latest"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the node-sass@3.13.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/valorad/npm-debug.log
npm ERR! code 1

### Mention any other details that might be useful.

1. Was trying to install using sudo.
2. Could successfully install node-sass@3.13.0 directly, but not with angular-cli.

> ---------------------------------------------------------------

**Comment by srix55** [comment]
Node 7 isn't supported by ng-cli yet.

**Comment by wcxaaa** [comment]
OK got it. See #3218 for details.

**Comment by aderbas** [comment]
same error here with Node v6.9.1

**Comment by wcxaaa** [comment]
I downgraded to Node v6.9.1 and this issue is solved.

**Comment by amet123** [comment]
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
