### ISSUE TITLE
Angular2 project using angular-cli version 1.0.0 beta-19 unable to deploy on heroku

### ISSUE THREAD

**Issue by akshayextentia** [angular/angular-cli#3230]
### Problem

We are trying to deploy angular-cli: 1.0.0-beta.19-3 app into heroku and got error :-  **Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch**

We provided our app details below, please reply on it.

> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 8

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

App is created and running successfully in local machine only.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
The CLI produces a set of static files.  How they are deployed is up to the developer.  Deploying just the built app on heroku is probably overkill but heroku has a guide: https://devcenter.heroku.com/articles/static-sites-ruby

**Comment by filipesilva** [comment]
This isn't a problem with the CLI, but rather you Heroku deployment process. I can't help you there since I don't use it myself.

**Comment by wooltar** [comment]
I had the same isuue. Finally, I solved change the scripts of package.json 
```
   "start": "http-server",
    "preinstall": "npm install -g http-server",
    "postinstall": "ng build && mv dist/* ."
```
versions
 "@angular/cli": "^1.6.2",
    "@angular/compiler-cli": "^5.1.2",
    "typescript": "~2.4.2",

"engines": {
    "node": "8.2.0",
    "npm": "5.3.0"
  },
