### ISSUE TITLE
index.ts not created 

### ISSUE THREAD

**Issue by mahassan** [angular/angular-cli#3231]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, win 32, x64

### Versions.
> node 6.9.1
> angular-cli 1.0.0 beta 20-4

### Repro steps.
>ng g c databinding 

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
I cannot see index.ts created.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by grizzm0** [comment]
Barrels are no longer part of the style guide and was removed in #1658.

**Comment by filipesilva** [comment]
So sayeth the @grizzm0 💃
