### ISSUE TITLE
Pug and SCSS support.

### ISSUE THREAD

**Issue by FieryCod** [angular/angular-cli#3234]
I saw that there were a lot of discussions about the Pug and Scss official support. As I know the proper poor request was merged to a repo. Still we do not know how to configure angular-cli to generate .pug and .scss file. Can someone help me with it?

**Comment by Ionaru** [comment]
For Scss support, look here: https://github.com/angular/angular-cli#css-preprocessor-integration

**Comment by FieryCod** [comment]
Thanks I found your link very helpful. What about Pug support?

**Comment by Ionaru** [comment]
As far as I know Jade/Pug support is not currently being worked on by the Angular team, however another contributor has started to work this feature.

See PR #2205 and issue #1886

**Comment by filipesilva** [comment]
As @Ionaru says, we do have scss support and jade support is being tracked in https://github.com/angular/angular-cli/issues/1886.

**Comment by paramsingh88** [comment]
Please, we want Pug support

**Comment by svallory** [comment]
@paramsingh88 @FieryCod I made a pull request to allow tweaking webpack config with a file in the project root. For now, you can use the cli at https://github.com/cashfarm/angular-advanced-cli

and add a `webpack.config.js` with this to root of your project: 
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.(pug|jade)$/,
        use: ['pug-ng-html-loader']
      }
    ]
  }
}
```
Then your components can use pug
```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.pug',
  styleUrls: ['./app.component.styl']
})
```
But your index has to stay in html.
