### ISSUE TITLE
local domains over https

### ISSUE THREAD

**Issue by richardsengers** [angular/angular-cli#3235]
### OS?
> Windows 10

### Versions.
angular-cli: 1.0.0-beta.20-4
node: 4.4.7
os: win32 x64

Hi all,
I'm not quite sure if this is related with angular-cli or webpack, but the problem is, when I'm trying to access my project over https with a local domain, say https://app.dev I'm getting an error saying "Can't proxy request to http://localhost:4200."
I can access my project though, https://app.dev:4200 is working just fine. But it would be nice not to inlcude the port.

I've generated local domains with [Hotel](https://www.npmjs.com/package/hotel) and I've used Hotel already a couple of times with [json-server](https://github.com/typicode/json-server) without any problems.
I just can't get it properly working, without the port number, in an angular-cli project.

Sorry if this is not related in any way to Angular-cli, could anybody then please provide me a hint of where to look?

My npm start script: "ng serve --ssl --proxy-config proxy.conf.json" using "npm start"

**Comment by benjamincharity** [comment]
Not a direct answer.. but I have been using https://ngrok.com/ for about a year now (used hotel in the past). It's pretty cheap and _well_ worth it imo.

**Comment by filipesilva** [comment]
I don't have an answer for it myself, but will leave it open for a while so that the community can help.

**Comment by filipesilva** [comment]
Closing as outdated.

**Comment by kynetiv** [comment]
In case it's helpful for others using ngrok.io or similiar, you'll likely need to serve the project like this:
```bash
ng serve --host=0.0.0.0 --disable-host-check
```
Or you may get an `invalid Host header` error.
