### ISSUE TITLE
[Feat] Add @ngtools/webpack AoT option for outputting to fs instead of virtual file system.

### ISSUE THREAD

**Issue by luchillo17** [angular/angular-cli#3236]
This is a feature request, i have a webpack app, i need to config the webpack config file manually, so the feature i suggest is to allow the `@ngtools/webpack` AoT to output the app module factory to file system, maybe only the app module or every file (open to discussion).

### Reason to propose feature
I keep getting error `Module not found` for the app module factory, and i don't know if it isn't being created, if i have it configured in a different folder or what, being able to `flag` the plugin to force it to output to file system, so we can see it in project file tree would help clarify this kind of issues.

### Repro steps.
Check this repo branch: https://github.com/Luchillo/angular2-webpack-starter/tree/aot
Clone, checkout branch `aot`, `npm install`, `npm run build:aot` and the error should pop out.

### The log given by the failure.
```sh
ERROR in ./src/main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in '/Users/aplicaciones2/Documents/angular2-webpack-starter/src'
 @ ./src/main.aot.ts 10:29-62
```

**Comment by hansl** [comment]
@Luchillo: I've never gotten this error without another error above which was the real source of the problem. Could you try to 

I'm not entirely sold on not having a virtual filesystem, since you can always run `ngc` yourself to get that. The webpack plugin simply run the same code as `ngc` but using an in memory host. So you can get the result of it yourself.

**Comment by Luchillo** [comment]
It's just to make sure i'm setting the paths correctly, i'm not saying it shouldn't use virtual filesystem, i'm saying it should have the option to output to disk to debug potential path misconfiguration.

**Comment by Luchillo** [comment]
@hansl Btw did you test with the repo branch i linked?, that's exactly the project i'm trying to put AoT support to work.

**Comment by Luchillo** [comment]
I'm still trying to figure this out, here's how the error is shown to me:

![image](https://cloud.githubusercontent.com/assets/9698639/21501439/f4171088-cc15-11e6-9d46-bf2b9918d55c.png)

The other error you mention might be that one about `AppModule` not being an `NgModule`?

**Comment by filipesilva** [comment]
Mostly superseded by https://github.com/angular/angular-cli/issues/6203.
