### ISSUE TITLE
Services not Singleton's after update to 1.0.0-beta.20-4

### ISSUE THREAD

**Issue by martinmcwhorter** [angular/angular-cli#3238]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.20-4
node: 6.7.0
os: win32 x64

Previously 1.0.0-beta.19-3

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

I followed the upgrade steps for updrading angular-cli. 

During the upgrade I took the new package.json file. 

Services provided in a child lazy-loaded module would be instantiated each time they were injected. 

This issue was fixed for me by rolling back this portion of my package.json:
+    "@angular/common": "^2.1.0",
+    "@angular/compiler": "^2.1.0",
+    "@angular/core": "^2.1.0",
+    "@angular/forms": "^2.1.0",
+    "@angular/http": "^2.1.0",
+    "@angular/platform-browser": "^2.1.0",
+    "@angular/platform-browser-dynamic": "^2.1.0",
+    "@angular/router": "^3.1.0",
back to 
-    "@angular/common": "~2.1.0",
-    "@angular/compiler": "~2.1.0",
-    "@angular/core": "~2.1.0",
-    "@angular/forms": "~2.1.0",
-    "@angular/http": "~2.1.0",
-    "@angular/platform-browser": "~2.1.0",
-    "@angular/platform-browser-dynamic": "~2.1.0",
-    "@angular/router": "~3.1.0",

Then deleting my node_modules and doing an npm install. 

Obviously this is not a direct issue with angular-cli. But I believe you would like to be aware of the issue. 

I would like to spend some more time and find out exactly which of these packages, and what version, is causing the problem.  

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by slubowsky** [comment]
See https://github.com/angular/angular/issues/12869 and many others just like it... Unfortunately have not seen it acknowledged by Angular developers as of yet (or any of the other severe router issues that have recently been opened)

**Comment by martinmcwhorter** [comment]
This seems to be fixed in recent versions of the router.
