### ISSUE TITLE
ng build --dev vs ng build --prod : Why is prod build larger?

### ISSUE THREAD

**Issue by lebsral** [angular/angular-cli#3239]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX 10.12.1

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.20-4
node: 7.1.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
ng new testing
cd testing
ng build --dev

size of dist folder is 5.1mb

ng build --prod

size of dist folder is now 6.8mb.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

Why does the prod build produce a larger dist folder?  Isn't it doing tree shaking and uglification?

**Comment by clydin** [comment]
If you compare the contents, you'll see that production produces both compressed (gzip) and uncompressed bundles for deployment.

**Comment by lebsral** [comment]
@clydin ok thanks.
I only see 1 gzip file in there.  Which is at 188 kb.
So for deployment are you saying that we only need the index.html and the gzip file?  Or the opposite of that?

**Comment by clydin** [comment]
A minimum would be index.html, CSS bundle (if present), and all JS files.  The gz versions are there so that they don't need to be compressed on the fly during transit.  The gz versions reflect the typical overthewire size. The sourcemap files allow for debugging.

**Comment by lebsral** [comment]
-dev
favicon.ico 5kb
index.html 481bytes
inline.bundle.js 6kb
inline.map 6kb
main.bundle.js 2.5mb
main.map 2.5mb
styles.bundle.js 10kb
styles.map 14kb


-prod
favicon.ico 5kb
index.html 625bytes
inline.d41d8cd98f00b204e980.bundle.js 1kb
inline.d41d8cd98f00b204e980.bundle.map 14kb
main.b0be6a822be694707dbb.bundle.js 816kb
main.b0be6a822be694707dbb.bundle.js.gz 188kb
main.b0be6a822be694707dbb.bundle.js.map 5.8mb
styles.b2328beb0372c051d06d.bundle.js 146bytes
styles.b2328beb0372c051d06d.bundle.map 127bytes
styles.d41d8cd98f00b204e9800998ecf8427e.bundle.css 62bytes


When you say gz represents the 'otherwise' size, otherwise from what?

Also, would it be more fair when comparing sizes that matter in production, instead of the method I used in the original question, would be to add up...

-dev
favicon.ico 5kb
index.html 481bytes
inline.bundle.js 6kb
main.bundle.js 2.5mb
styles.bundle.js 10kb

about 2.52 megabytes total

vs

-prod
favicon.ico 5kb
index.html 625bytes
inline.d41d8cd98f00b204e980.bundle.js 1kb
main.b0be6a822be694707dbb.bundle.js 816kb
styles.b2328beb0372c051d06d.bundle.js 146bytes
styles.d41d8cd98f00b204e9800998ecf8427e.bundle.css 62bytes

about 822.8 kilobytes total

right?

**Comment by clydin** [comment]
Yes.  My comment should have been "over the wire"; the size that would actually be sent to the client.

**Comment by hansl** [comment]
You should not be sending source map files to your users (`js.map` files), so don't include those in your calculation. Also, it seems like we're missing a few `.gz` files (there should be 1 for every source file), I'll be investigating why.

**Comment by clydin** [comment]
@hansl, there is a 10k threshold set on the compression plugin.
