### ISSUE TITLE
What is Icon when generating module?

### ISSUE THREAD

**Issue by xg-wang** [angular/angular-cli#3240]
angular-cli: 1.0.0-beta.18
node: 7.1.0
os: darwin x64 macOS Sierra

When using `ng g module overview`, it would generate two 'Icon\r' files.

```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing module
  identical Icon
  create src/app/overview/Icon
  create src/app/overview/overview.module.ts
installing component
  identical Icon
  identical src/app/overview/Icon
  create src/app/overview/overview.component.css
  create src/app/overview/overview.component.html
  create src/app/overview/overview.component.spec.ts
  create src/app/overview/overview.component.ts
```

I've searched for this but there seems no related info and I have no idea what this 'Icon' is about. Can I delete these Icon files?

**Comment by filipesilva** [comment]
@Brocco do you know what this is?

**Comment by Brocco** [comment]
I have no idea what those files are. Does that file exist on disk in your app? If so, are the contents?

**Comment by xg-wang** [comment]
@Brocco Yes they do exist. And I removed them and add Icon? to .gitignore and they would appear no more. I googled it and it might be related to macOS.

**Comment by Brocco** [comment]
@xg-wang are you still having this issue? I don't think this is related to the CLI. I am closing this, but if you or anyone else is still experiencing this, comment here and we can reopen it.
