### ISSUE TITLE
Error: ngCompiler.ReflectorHost is not a constructor

### ISSUE THREAD

**Issue by prsolucoes** [angular/angular-cli#3241]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX (Sierra)

### Versions.
> ngtools/webpack - 1.1.7

### Repro steps.
> git clone github.com/prsolucoes/angular2-starter-project
> cd angular2-starter-project
> npm install
> npm start

### The log given by the failure.

```
paulo@MacBook-Pro-de-Paulo:~/Developer/workspaces/node/angular2-starter-project (master) $ npm start

> angular2-starter-project@1.0.0 start /Users/paulo/Developer/workspaces/node/angular2-starter-project
> npm run ngc && concurrently -r "webpack-dev-server --config webpack.config.js" "node ./bin/ngc-watch.js"


> angular2-starter-project@1.0.0 ngc /Users/paulo/Developer/workspaces/node/angular2-starter-project
> ngc -p ./tsconfig.json

/Users/paulo/Developer/workspaces/node/angular2-starter-project/node_modules/@ngtools/webpack/src/plugin.js:127
        this._reflectorHost = new ngCompiler.ReflectorHost(this._program, this._compilerHost, this._angularCompilerOptions);
                              ^

TypeError: ngCompiler.ReflectorHost is not a constructor
    at AotPlugin._setupOptions (/Users/paulo/Developer/workspaces/node/angular2-starter-project/node_modules/@ngtools/webpack/src/plugin.js:127:31)
    at new AotPlugin (/Users/paulo/Developer/workspaces/node/angular2-starter-project/node_modules/@ngtools/webpack/src/plugin.js:35:14)
    at Object.<anonymous> (/Users/paulo/Developer/workspaces/node/angular2-starter-project/webpack/plugins.js:12:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/paulo/Developer/workspaces/node/angular2-starter-project/webpack.config.js:15:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

### Mention any other details that might be useful.

> My repository with the current problem:
> https://github.com/prsolucoes/angular2-starter-project

My plugin initialization:

```
let ngtools = require('@ngtools/webpack');
module.exports = [
	new ngtools.AotPlugin({
		tsConfigPath: './tsconfig.json',
		baseDir: path.join(process.cwd(), 'src'),
		entryModule: path.join(process.cwd(), 'src', 'app', 'modules', 'app.module') + '#AppModule'
	}),
....

```

**Comment by jessezhang91** [comment]
I think this is due to the angular 2.2.2 moving ReflectorHost to `@angular/language-service`.

**Comment by prsolucoes** [comment]
I think you are correct. Because with version 2.2.1 everything is working fine :(

**Comment by MartinNowak** [comment]
Intermediately fixed by https://github.com/angular/angular-cli/pull/3242, updating to angular-cli to "1.0.0-beta.21" as described [here](https://github.com/angular/angular-cli/tree/54ef7383e1e63633e1ab9622563989a5220e686f#user-content-updating-angular-cli) fixes aot compilation for now.

**Comment by prsolucoes** [comment]
Thanks. But i dont use angular-cli. I have backed all angular2 deps to 2.2.1 version until it be solved.

**Comment by hansl** [comment]
@prsolucoes Yes, we also updated the peer dependency of the webpack plugin. This will be resolved properly in the future (next week, because this week is thanksgiving). In the meantime you have to use Angular v2.2.1. This is unfortunate and we're looking at long term solutions to prevent this in the future.

**Comment by digimax** [comment]
I'm not sure why HanZ closed this. Everything was working perfect for me with angular-cli-b21, this morning i update angular-cli-b22. I'm certain this has something to do with minor project configuration impedance, and you might like to call it a bug, no bug has ever stopped me before, so why would this one stop me now? And, no, I'm not rolling back any of dependencies, i keep everything on the bleeding edge.

**Comment by colemickens** [comment]
I'm also seeing this issue with `angular-cli 1.0.0-beta.22-1`.

**Comment by alvipeo** [comment]
Same here with angular 2.3.0. Please re-open.

**Comment by stanislavromanov** [comment]
Also same problem. 

Angular: 2.3.0
CLI: 1.0.0-beta.22-1

**Comment by petercn** [comment]
Same with my project too!

Angular: 2.3.0
CLI: 1.0.0-beta.22-1

**Comment by PG2000** [comment]
@hansl any news on this

**Comment by vapits** [comment]
Same here, I don't think as correct @colemickens said in the other issue that is productive to close the issues when they are still actually issues, because people cannot track internal "tickets" of the team @hansl.

Please re-open or update the subscribers for the process.
In our team whoever did an npm install simply cannot work, even if he downgrades.

**Comment by vapits** [comment]
@jesselpalmer thanks for your fix, though for me if I do what you said, I get a unmet peer dependency (which is needed), warnings and at the end webpack is stops in 20%.

```
├── typescript@2.0.10
└── UNMET PEER DEPENDENCY zone.js@0.7.2
npm WARN @angular/http@2.2.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/router@3.2.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/core@2.2.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/core@2.2.1 requires a peer of zone.js@^0.6.21 but none was installed.
npm WARN tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none was installed.
npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/compiler-cli@2.2.3 but none was installed.
npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/core@2.2.3 but none was installed.
➜  WebApp git:(version-update) ✗ npm start

> web-app@0.0.3-alpha start /Projects/Jexia/WebApp
> ng serve

** NG Live Development Server is running on http://localhost:4200. **
 10% building modules 2/2 modules 0 active(node:57199) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 144:19 in the original .ts file), resolving symbol AppModule in /Projects/Jexia/WebApp/src/app/app.module.ts
 20% building modules 84/84 modules 0 active
```

Did the fix work to someone else also?

**Comment by ritox842** [comment]
Same issue here..
I can't run my project and getting 
`ngCompiler.ReflectorHost is not a constructor
`

Using angular-cli": "1.0.0-beta.22-1 and angular 2.3.0

**Comment by unsafecode** [comment]
Same here with `@ngtools/webpack@1.1.9`

**Comment by kevinsherman** [comment]
I ran into this problem after updating angular-cli from `beta.20-4` to` beta.22-1`. After running `ng init` and diffing `package.json`, I noticed that I had `"@angular/compiler-cli" : "^2.2.4"` in the `dependencies` object, and `"@angular/compiler-cli" : "2.2.3"` in the `devDependencies` object. I removed the entry from `dependencies`, and was able to run `npm start`.

**Comment by Miced** [comment]
@kevinsherman what version of angular are you using?

**Comment by kevinsherman** [comment]
@Miced 

 ```
 "dependencies": {
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/router": "3.2.3",
    "@types/node": "^6.0.51",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "ng2-bootstrap": "^1.1.16",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  }
```

**Comment by zakdances** [comment]
Seeing the same problem as above with both 2.2.4 and 2.2.3.

**Comment by reginaldocmrg** [comment]
I was able to get the angular 2.3.0 working downgrading the angular-cli from version angular-cli@1.0.0-beta.22-1 to version angular-cli@1.0.0-beta.21. Now the error gone.

**Comment by sclausen** [comment]
@reginaldocmrg WOW that worked!

**Comment by Adrriver** [comment]
How do you actually rollback, though?  I performed a global install of angular-cli@1.0.0-beta.21 and still have .beta22!  I feel liked I'm negotiating with a cartoon.

**Comment by reginaldocmrg** [comment]
I installed angular-cli@1.0.0-beta.21 locally.

**Comment by sclausen** [comment]
@Adrriver it worked well for me
``` sh
sudo npm uninstall -g angular-cli
sudo npm install -g angular-cli@1.0.0-beta.21

**Comment by ritox842** [comment]
@Adrriver solution works for me also...

**Comment by mahindar5** [comment]
I'm getting the same error but I'm not using angular-cli. I'm using webpack. My package.json looks like this
{
  "version": "1.0.0",
  "name": "sample",
  "private": true,
  "dependencies": {
    "@angular/common": "~2.3.0",
    "@angular/compiler": "~2.3.0",
    "@angular/core": "~2.3.0",
    "@angular/forms": "~2.3.0",
    "@angular/http": "~2.3.0",
    "@angular/platform-browser": "~2.3.0",
    "@angular/platform-browser-dynamic": "~2.3.0",
    "@angular/router": "~3.3.0",
    "angular-in-memory-web-api": "~0.1.17",
    "core-js": "^2.4.1",
    "ionic-angular": "^2.0.0-rc.3",
    "jquery": "^3.1.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-rc.4",
    "systemjs": "0.19.40",
    "typescript": "^2.1.4",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.0",
    "@ngtools/webpack": "^1.1.9",
    "@types/jquery": "^2.0.34",
    "angular2-template-loader": "0.6.0",
    "html-webpack-plugin": "^2.24.1",
    "raw-loader": "^0.5.1",
    "ts-loader": "1.3.1",
    "webpack": "2.1.0-beta.27"
  }
}

**Comment by stanislavromanov** [comment]
@mahindar5 Error actually comes from webpack, either you use ng cli or not.

**Comment by mahindar5** [comment]
Hi @stanislavromanov  is there any workaround to fix this? Thanks

**Comment by daviddsingleton** [comment]
Tried all suggested solutions still nothing working.
@angular2.3
@ngtools/webpack 1.1.9

**Comment by jessezhang91** [comment]
@daviddsingleton you need angular 2.2.4 (and 3.2.4 for router)

**Comment by AlvaroOrduna** [comment]
Same issue here with **1.0.0-beta.23**, as in (#3501, #3467 and #3367). Besides the problem building, I do not know why *__UNMET PEER DEPENDENCY__* message when installing latest CLI release.

> **ng --version**
```
angular-cli: 1.0.0-beta.23
node: 6.9.2
os: win32 x64
```
> **npm ls --depth=0**
```
+-- UNMET PEER DEPENDENCY @angular/common@2.3.1
+-- @angular/compiler@2.3.1
+-- @angular/compiler-cli@2.3.1
+-- UNMET PEER DEPENDENCY @angular/core@2.3.1
+-- @angular/forms@2.3.1
+-- @angular/http@2.3.1
+-- @angular/material@2.0.0-alpha.11-3
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.3.1
+-- @angular/platform-browser-dynamic@2.3.1
+-- @angular/router@3.2.3
+-- @types/hammerjs@2.0.33
+-- @types/jasmine@2.5.38
+-- @types/node@6.0.52
+-- angular-cli@1.0.0-beta.23
+-- angularfire2@2.0.0-beta.6
+-- codelyzer@2.0.0-beta.3
+-- core-js@2.4.1
+-- firebase@3.6.4
+-- font-awesome@4.7.0
+-- hammerjs@2.0.8
+-- jasmine-core@2.5.2
+-- jasmine-spec-reporter@2.5.0
+-- karma@1.2.0
+-- karma-chrome-launcher@2.0.0
+-- karma-cli@1.0.1
+-- karma-jasmine@1.1.0
+-- karma-remap-istanbul@0.2.2
+-- protractor@4.0.13
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-rc.4
+-- ts-helpers@1.1.2
+-- ts-node@1.2.1
+-- UNMET PEER DEPENDENCY tslint@4.1.0
+-- typescript@2.0.10
`-- zone.js@0.7.2

npm ERR! peer dep missing: @angular/common@2.2.3, required by @angular/router@3.2.3
npm ERR! peer dep missing: @angular/core@2.2.3, required by @angular/router@3.2.3
npm ERR! peer dep missing: @angular/platform-browser@2.2.3, required by @angular/router@3.2.3
npm ERR! peer dep missing: rxjs@5.0.0-beta.12, required by @angular/router@3.2.3
npm ERR! peer dep missing: rxjs@5.0.0-beta.12, required by angularfire2@2.0.0-beta.6
npm ERR! peer dep missing: tslint@~4.0.0, required by codelyzer@2.0.0-beta.3
npm ERR! peer dep missing: @angular/compiler-cli@2.2.3, required by @ngtools/webpack@1.1.9
npm ERR! peer dep missing: @angular/core@2.2.3, required by @ngtools/webpack@1.1.9
npm ERR! peer dep missing: tslint@^3.0.0, required by tslint-loader@2.1.5
```
> **ng serve**
```
ngCompiler.ReflectorHost is not a constructor
TypeError: ngCompiler.ReflectorHost is not a constructor
     at AotPlugin._setupOptions (.\node_modules\@ngtools\webpack\src\plugin.js:136:31)
     at new AotPlugin (.\node_modules\@ngtools\webpack\src\plugin.js:37:14)
     at Object.exports.getWebpackAotConfigPartial (.\node_modules\angular-cli\models\webpack-build-typescript.js:44:13)
     at new NgCliWebpackConfig (.\node_modules\angular-cli\models\webpack-config.js:25:42)
     at Class.run (.\node_modules\angular-cli\tasks\serve-webpack.js:20:22)
     at .\node_modules\angular-cli\commands\serve.js:108:26
     at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by keyiis** [comment]
Has progress?i has same issuse,i used webpack(2.1.0-beta.25) @angular(2.2.3) @ngtools/webpack(1.1.9)

**Comment by soccio** [comment]
had the same problem with beta 24, try creating a new project , then copy your source folder to that new project. then modify config files as required. It worked for me.

**Comment by mgol** [comment]
I had the same issue; all that was required to fix it was to remove `node_modules` and run `npm install`.

If you're using yarn you need to remove both `node_modules` and `yarn.lock` and run `yarn` afterwards. I suspect a dependency of a dependency is fixed in a newer version and you just need to update it.

**Comment by maxime1992** [comment]
@mgol Thanks a lot, the problem was with yarn. I removed the yarn.lock and it's now working !

**Comment by arunswaminathank** [comment]
getting same error with angular 2.4.1 . Any specific details on which version of angular AOT works ?

**Comment by mgol** [comment]
@arunswaminathank Have you tried removing node_modules (and yarn.lock if you use yarn) and reinstalling dependencies?

**Comment by arunswaminathank** [comment]
Yes, I tried , still the same error

**Comment by ichent** [comment]
This is unreal. I can't build my project about 2 weeks. Every combination of versions gives different errors.

**Comment by zackarychapple** [comment]
I'm using AOT with `beta.24` and the below versions. 

```
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.24",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3"
  }
```

**Comment by alvipeo** [comment]
Let me try that today too. I put my prj on hold because of these issues like 3 weeks ago. Let's hope it'll work...

**Comment by stanislavromanov** [comment]
Still does not work. This is ridiculous.

**Comment by bliitzkrieg** [comment]
Was there a fix for this? I am experience this as well :(

**Comment by alvipeo** [comment]
That's fixed pretty long time ago. My suggestion is to create a new project with beta.26 (the current version as I write this).

**Comment by keyiis** [comment]
I update all package to last version,the issuse fixed.

**Comment by naujfract** [comment]
I use this package.json and fixed!
"dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@ionic-native/core": "3.4.2",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.0.1",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.4",
    "@ionic-native/background-mode": "^3.4.4",
    "@ionic-native/geolocation": "^3.4.4",
    "@types/google-maps": "^3.2.0",
    "angularfire2": "^2.0.0-beta.7",
    "firebase": "^3.6.9",
    "geofire": "^4.1.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.0",
    "typescript": "~2.2.1"
  }
