### ISSUE TITLE
Create a route module when generating a module

### ISSUE THREAD

**Issue by mhmo91** [angular/angular-cli#3243]
#Routing_module 
According to angular documentation, it's considered the best practice to add  routing module for each module, so my suggestion is, when generating a module, i think it makes sense to create a route module for it.
#update
Because it's not usually the case, may be another command like 
`ng g module routing x` instead of `ng g module x`
Namaste

**Comment by delasteve** [comment]
Have you tried the `--routing` flag when generating a module? This will generate you a `some.module.ts` and `some-routing.module.ts` file.

`ng generate module SomeModule --routing` (or `ng g m SomeModule --routing`, for short)

**Comment by mhmo91** [comment]
I didn't know about that command! 
thanksss

**Comment by mhmo91** [comment]
@delasteve Can u update the readme with this feature for others?

**Comment by delasteve** [comment]
https://github.com/angular/angular-cli/wiki/module

Additionally, @Brocco has a PR out there to move the docs to the repo https://github.com/angular/angular-cli/pull/3382

**Comment by josephdgb1996** [comment]
And if I need the html , scss annd the component of this ?

**Comment by waleedshkt** [comment]
Hi @delasteve, I tried using your method for generating routing module. But it seems like it doesn't do the trick. I have another just module ts file in my directory. When I try to generate routing module, the latest versioned angular-cli I am using throws me an error of already-existing-module inside the directory.

**Comment by atom-morgan** [comment]
@waleedshkt If the module already exists, the CLI will throw errors. Just delete that file and then run the command again with the `--routing` flag.

**Comment by atom-morgan** [comment]
@josephdgb1996 You just generate a component with the same name as your module. Using the example @delasteve gave you'd just run `ng generate component SomeModule`.

**Comment by wagnergrilo85** [comment]
ng g m moduleName --routing

**Comment by nikhilbhalwankar** [comment]
> Have you tried the `--routing` flag when generating a module? This will generate you a `some.module.ts` and `some-routing.module.ts` file.
> 
> `ng generate module SomeModule --routing` (or `ng g m SomeModule --routing`, for short)

Thanks. Did not know such command exist. This works perfect !

**Comment by mtoloto** [comment]
@josephdgb1996 module does not have html or scss. 
module has components wich has the html and stylesheets like css, scss, etc...
