### ISSUE TITLE
Ng serve should compile only the lazy loaded module change and not the whole app

### ISSUE THREAD

**Issue by iwoogy** [angular/angular-cli#3247]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX: El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.18
node: 6.3.0

### Repro steps.
Create Module to lazy load.
Change code and save
Wait for ng serve to reload

### The log given by the failure.
It does not fail. However the time to reload for a complex app does not seem to be reduced between an app without lazy loading and an app with lazy loading.

I would be great if any modification to a component into a lazy loaded module would trigger only the compilation of the changed module and not the whole app.

I'm not sure if it's already the case.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
We do this now.
