### ISSUE TITLE
ng build or ng serve aSource + '" is not in the SourceMap

### ISSUE THREAD

**Issue by doliver3** [angular/angular-cli#3248]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.21
node: 7.1.0
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
No, no changes to code. Brand new ng init in brand new folder and fails immediately at first attempt to run.
I was following this super-basic tutorial with just the ng init step to reproduce, but the only step I did relevant to this defect is to make a new folder, do an ng init then an ng serve in that folder.  I expect that it should work without error rather than failing to compile and run because a sourcemap cannot be found. 
https://auth0.com/blog/angular-2-authentication/
https://github.com/auth0-blog/angular-2-authentication-tutorial

I did a ng init in a new folder
then I did an ng serve
I immediately get the following error below. I also get this same error if I just do a ng build.
A brand new ng init with no changes should produce a fully working application. It is obviously a defect if a a brand new ng init cannot run. 

/var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:704
      throw new Error('"' + aSource + '" is not in the SourceMap.');
            ^
Error: "/var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/angular2-template-loader/index.js!/srv/batch/automation/auth0ang/angular-2-authentication-tutorial/ng2auth/src/app/auth.service.ts" is not in the SourceMap.

I have my node npm prefix set to 
prefix = "/var/www/.npm-packages"
as viewed with npm config -g ls

### The log given by the failure.
> Normally this include a stack trace and some more information.
Stack track is longer, but I'll include just the initial lines below.
/var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:704
      throw new Error('"' + aSource + '" is not in the SourceMap.');
            ^
Error: "/var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/angular2-template-loader/index.js!/srv/batch/automation/auth0ang/angular-2-authentication-tutorial/ng2auth/src/app/auth.service.ts" is not in the SourceMap.
    at BasicSourceMapConsumer.SourceMapConsumer_sourceContentFor [as sourceContentFor] (/var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:704:13)
    at /var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:133:40
    at Array.forEach (native)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:132:32)
    at SourceMapSource.node (/var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/SourceMapSource.js:42:20)
    at ReplaceSource.node (/var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ReplaceSource.js:66:29)
    at CachedSource.node (/var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:12:23)
    at /var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /var/www/.npm-packages/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by not-for-me** [comment]
#1490 
This issue is also occurred on my project in angular-cli 1.0.0-beta21

if I add the option '--no-sourcemap', then serve and build command is working correctly.

**Comment by not-for-me** [comment]
I think that this issue is related to source folder.
Here is some snippet of my angular-cli.json

**Comment by filipesilva** [comment]
This was actually an issue we had with node-sass, should be fixed in the latest releases.
