### ISSUE TITLE
Continuous Integration Support

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#325]
Should probably be part of `ng deploy` for production push out.

**Comment by shairez** [comment]
Do we have a design doc for this issue?

**Comment by filipesilva** [comment]
Not yet iirc. Basically it would use a command similar to `ng github-pages:deploy` in that it would use a lot of `exec` shenenigans and third party apis to fully configure your project to use a specific CI integration.

**Comment by hansl** [comment]
This will not be supported before 1.0 final, if ever. Good use case for addon support.
