### ISSUE TITLE
Updating NPM Dependencies with Angular-cli

### ISSUE THREAD

**Issue by Nikki1993** [angular/angular-cli#3251]
Hello there,

What is the proper way to update dependencies in package.json? I am currently using npm-check-updates to check & update all my packages listed in the package.json file but does it affect angular-cli tool in any way? Should I be running 

```
rm -rf node_modules dist tmp
npm install --save-dev angular-cli@latest
npm install
ng init
```

each time I am upgrading dependencies or is there a better way to make sure that all npm deps stay up-to-date and angular-cli is happy :) 

P.S. not that I had any issues right now just simply updating but figured worth asking to do things proper way :)

**Comment by hansl** [comment]
That is the proper way for now. You don't have to `rm -rf` the `dist` and `tmp` folders, just `node_modules`.

**Comment by Nikki1993** [comment]
@hansl just to be sure, so if there is no update to angular-cli, simply upgrading packages is alright? :)

**Comment by hansl** [comment]
Yes.
