### ISSUE TITLE
AOT compiled app doesn't work when served from cdn

### ISSUE THREAD

**Issue by elvirdolic** [angular/angular-cli#3254]
We have an aot compiled app which works when we access it directly and not from cdn.

When we use akamai as cdn it't doesn't bootstrap. It loads the main bundle but the bootstrap process is never triggered and the lazy loaded route is also not loaded. All our static files were served from akamai. The main.hash.js file is downloaded as expected.

Serving the same app with JIT compiler over cdn works. It only doesn't work when the app is AOT compiled.

Any possible reasons for that? No errors are raised in the console and the network traffic is also without issues.

**Comment by manekinekko** [comment]
@elvirdolic this looks like an issue related to Angular project not the CLI. Please report this issue to angular/angular.

**Comment by elvirdolic** [comment]
It's caching related. Thx

**Comment by elvirdolic** [comment]
This issue is related to: #3221
