### ISSUE TITLE
Github Pages: User page

### ISSUE THREAD

**Issue by austinzuffi** [angular/angular-cli#3259]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
mac os 10.11.6

### Versions.
1.0.0-beta.18

### Repro steps.
deploying an angular-cli created app
all remote git references removed
`ng github-pages:deploy --user-page`

### Mention any other details that might be useful.
 Github Pages [spec](https://help.github.com/articles/user-organization-and-project-pages/) for user page:

> You must use the username.github.io naming scheme.

Output of `ng github-pages:deploy --user-page` creates github project name matching that of local project name. Terminal returns a success message and link to [username].github.io, a link that returns 404 on load. Re-naming github project to [username].github.io results in successful live deployment.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
