### ISSUE TITLE
ng build is working but ng-build --prod not

### ISSUE THREAD

**Issue by previousdeveloper** [angular/angular-cli#3260]
> Please provide us with the following information:
> ng-build --prod not working.

### OS?
> Linux (UBUNTU 14.0)

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
13374ms building modules
60ms sealing
0ms optimizing
1ms basic module optimization
136ms module optimization
1ms advanced module optimization
20ms basic chunk optimization
0ms chunk optimization
12ms advanced chunk optimization
3320ms building modules
1ms module and chunk tree optimization
189ms module reviving
2ms module order optimization
6ms module id optimization
7ms chunk reviving
35ms chunk order optimization
35ms chunk id optimization
1116ms hashing
2ms module assets processing
292ms chunk assets processing
5ms additional chunk assets processing
3ms recording
1649ms additional asset processing
519ms chunk asset optimization
 94% asset optimizationKilled

I am getting optimizationKilled error when build with prod 

> Thanks!

**Comment by filipesilva** [comment]
I think this is a memory issue. Linux will kill processes when it's low on memory. See http://stackoverflow.com/questions/30747314/webpack-uglify-plugin-returns-killed-on-ubuntu

**Comment by previousdeveloper** [comment]
@filipesilva thanks i will check it
