### ISSUE TITLE
Can't use Foundation SCSS

### ISSUE THREAD

**Issue by gjuchault** [angular/angular-cli#3263]
### OS?
> macOS Sierra

### Versions.
```
angular-cli: 1.0.0-beta.21
node: 7.1.0
os: darwin x64
```

### Repro steps.
1. Create an app using `ng new scssy-project --style=scss`
2. Install foundation + foundation-sites
3. Try requiring `/node_modules/foundation-sites/scss/settings/settings` in styles.scss for example

### The log given by the failure.
```
@import 'util/util';
^
      File to import not found or unreadable: util/util
```

### Mention any other details that might be useful.

Related foundation issue is https://github.com/zurb/foundation-sites/issues/7744
Solution is to add `foundation-sites/scss` to sass import paths.
Impossible to do because of https://github.com/angular/angular-cli/issues/1656

**Comment by grizzm0** [comment]
This is already tracked in #2747

**Comment by gjuchault** [comment]
Indeed, thanks for your time
