### ISSUE TITLE
viewEncapsulation is not defined

### ISSUE THREAD

**Issue by ritz078** [angular/angular-cli#3264]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX el capitan

Mac OSX el capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.21
node: 6.6.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Ran command `ng g component purchase-leads`

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
viewEncapsulation is not defined (Error in blueprint template: /Users/ritz078/projects/housing-assist/node_modules/angular-cli/blueprints/component/files/__path__/__name__.component.ts)
ReferenceError: viewEncapsulation is not defined (Error in blueprint template: /Users/ritz078/projects/housing-assist/node_modules/angular-cli/blueprints/component/files/__path__/__name__.component.ts)
    at eval (eval at <anonymous> (/Users/ritz078/projects/housing-assist/node_modules/lodash/template.js:225:12), <anonymous>:9:5)
    at processTemplate (/Users/ritz078/projects/housing-assist/node_modules/angular-cli/angular-cli/lib/models/file-info.js:20:36)
    at /Users/ritz078/projects/housing-assist/node_modules/angular-cli/angular-cli/lib/models/file-info.js:97:20
    at tryCatch (/Users/ritz078/projects/housing-assist/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/ritz078/projects/housing-assist/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/ritz078/projects/housing-assist/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/ritz078/projects/housing-assist/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mitorski** [comment]
I have the same issue with..

angular-cli: 1.0.0-beta.20-4
node: 4.2.6
os: linux x64

Any idea what happend in the last changes? Two weak ago everythinks works fine..

**Comment by teledemic** [comment]
I am also getting this when trying to generate a component. It started on beta.20-4 for me.

angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64

**Comment by teledemic** [comment]
I think it may have broken by this feature: #2822 

You can kludge around it by adding
```
		"viewEncapsulation": "Emulated",
		"changeDetection": "Default",
```
to the "defaults" section of your angular-cli.json. It's supposed to leave out those properties in the new component if the defaults aren't specified, but instead it crashes.

**Comment by b4youleap** [comment]
angular-cli: 1.0.0-beta.21
node: 5.12.0
os: win32 x64

I could not get the error in either a new or existing project.

**Comment by dallasacook** [comment]
As of my last update of Angular CLI, I am also receiving this error when generating components. 

`angular-cli: 1.0.0-beta.20-4
node: 4.5.0
os: darwin x64`

**Comment by finalxcode** [comment]
i have same issue, 

`ng generate component test1
installing component
Error locating module for declaration
        SilentError: Multiple module files found:`

when i try to use '--skip-import', i'm also receive this error.

then i try to use @teledemic advise
                 `"viewEncapsulation": "Emulated",
		"changeDetection": "Default",`
i got:
`ng generate component "test1" --skip-import
installing component
  identical src\app\test1\test1.component.css
  identical src\app\test1\test1.component.html
  identical src\app\test1\test1.component.spec.ts
  identical src\app\test1\test1.component.ts
Path must be a string. Received undefined`

angular-cli: 1.0.0-beta.21
node: 6.4.0
os: win32 x64

**Comment by zain3x** [comment]
angular-cli: 1.0.0-beta.22-1
node: 6.3.1
os: win32 x64

thx @teledemic. your solution work for me.

**Comment by filipesilva** [comment]
@Brocco can you have a look? It seems https://github.com/angular/angular-cli/issues/2822 broke this for older project configs.

**Comment by Meligy** [comment]
This seems to be working fine in master

**Comment by masaanli** [comment]
Also got this error. Tried several things already :)

**Comment by hansl** [comment]
Closing this as fixed.

**Comment by mzvast** [comment]
change **.angular-cli.json** like this, working on 1.0.0
```
  "defaults": {
    "styleExt": "css",
    "component": {
      "viewEncapsulation": "Emulated",
      "changeDetection": "Default"
    }
  }
```
