### ISSUE TITLE
autoprefixer not work, when run `ng build --prod`

### ISSUE THREAD

**Issue by vuuvv** [angular/angular-cli#3268]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). 

### Versions.
> angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64

Run `ng build`, autoprefixer works fine.
Run `ng build --prod`, autoprefixer not work.

Change file `angular-cli\models\webpack-build-production.ts`, add `autoprefixer()` to `LoaderOptionsPlugin`, then `ng build --prod` works fine.

**Comment by grizzm0** [comment]
Already fixed in #3164 waiting for merge.
