### ISSUE TITLE
add watch option for ng lint command

### ISSUE THREAD

**Issue by Jyamurugan** [angular/angular-cli#3269]
### OS
> Windows 10

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 6.5.0
os: win32 x64

Currently **ng lint** runs only one time. add **watch** option for **ng lint** command

**Comment by grizzm0** [comment]
If you got a proper IDE you might have TSLint support built into the IDE itself. PhpStorm/WebStorm for example has this. It will run quietly in the background and highlight any errors for you.

**Comment by Jyamurugan** [comment]
closing this issue

**Comment by ahelord** [comment]
@grizzm0 you have link? please

**Comment by fabiohbarbosa** [comment]
Watch option is cool, please consider reopening the issue.

**Comment by coldiary** [comment]
Pointing that another tool offers the functionality is not really a suitable answer, in my opinion, as people that does not use these IDE won't benefit from this useful option.

I think it would be consistent if one can make compiler, tests runner and linter run in background while coding with the CLI, without the need of an IDE.

**Comment by ravishtiwari** [comment]
@coldiary - Totally agree. Saying that X IDE has this feature is good information, but, I am not sure if it is solution. For example, Visual Studio has a starter project for Angular 2, which is good to know for a .Net guy, and may not be useful for others who do not use Visual Studio.

**Comment by WilliamRADFunk** [comment]
I agree this is a relevant issue. Being able to run watch on ng lint allows the ng serve to choke and throw out errors when a developer saves on unclean code. This is a preventative measure for enterprise level code. Do IDEs have the linters built in, yes. Will they underline questionable code, yes. Do they prevent developers from pushing dirty code passed standards into the build, unfortunately no.

Angular-CLI does a wonderful job of abstracting many of the tedious aspects of the everyday dev environment. On the flip side, it hides and prevents developers from doing additional positives as mentioned in this issue. Please don't discount these requests so easily.

**Comment by phmiller** [comment]
The response to this issue and the prior issue ([https://github.com/angular/angular-cli/issues/3437](https://github.com/angular/angular-cli/issues/3437)) is remarkable. For each issue, contributors to this repo have essentially told people to get a better IDE or do it yourself. The whole point of the CLI is to provide a nice developer experience. If you are going to tell everyone to just a different IDE or script it yourself, why have the CLI? This is a very arrogant and dismissive attitude

**Comment by Fieel** [comment]
I agree with everyone in this thread - we should be able to comfortably use only a simple editor (note, not IDE) with the angular cli, depending on IDE extensions doesn't look like a good idea..
