### ISSUE TITLE
Add more properties for UglifyJsPlugin

### ISSUE THREAD

**Issue by FilipeQ** [angular/angular-cli#3270]
Hi,
Is there any way to set up more properties for webpack.optimize.UglifyJsPlugin?

For example I want use more properties for the production bundle, like remove comments, reduce vars, etc.

Thx.

**Comment by grizzm0** [comment]
There is currently no build in support for altering the webpack config. This is something that has been discussed and will be looked closed at after v1.0.

The "easiest" way to do it right now is to checkout angular-cli and [link it up to npm](https://github.com/angular/angular-cli#working-with-master) and your project. Then you can simply edit `packages/angular-cli/models/webpack-build.*.ts`

**Comment by FilipeQ** [comment]
Ok, but why angular-cli for production environment don't use more properties like remove comments, or others that help to improve the production bundle?

**Comment by grizzm0** [comment]
I myself added [postcss-discard-comments](https://github.com/ben-eb/postcss-discard-comments) which saved lots of kilobytes. See #2593

There is an open issue about JS-comments not being removed in #2386. This has to be advised by the google legal team before being applied.

**Comment by grizzm0** [comment]
Just tried removing comments in the JS aswell. Made my main.bundle.js.gz go from 303kb to 298kb. Not that much of a difference.

**Comment by filipesilva** [comment]
Closing as there are other issues that cover this as @grizzm0 mentioned.
