### ISSUE TITLE
ng serve don't work on windows7

### ISSUE THREAD

**Issue by havefan-cccoder** [angular/angular-cli#3276]
OS:Windows 7 x64
 Versions:
angular-cli:  1.0.0-beta.21
node:  6.3.1
os:  win32 x64

steps:
E:\>ng new test_project
E:\>cd test_project
E:\test_project>ng serve

log:
** NG Live Development Server is running on http://localhost:4200. **
9013ms building modules
19ms sealing
2ms optimizing
0ms basic module optimization
260ms module optimization
1ms advanced module optimization
20ms basic chunk optimization
1ms chunk optimization
2ms advanced chunk optimization
0ms module and chunk tree optimization
96ms module reviving
4ms module order optimization
4ms module id optimization
5ms chunk reviving
1ms chunk order optimization
17ms chunk id optimization
87ms hashing
1ms module assets processing
173ms chunk assets processing
5ms additional chunk assets processing
1ms recording
1ms additional asset processing
1677ms chunk asset optimization
110ms asset optimization
49ms emitting
E:\test_project>

run 'ng serve' command in terminal, but it only run in a while and then directly break.
I paste "http://localhost:4200"in address bar,and my browser says "ERR_CONNECTION_REFUSED"

**Comment by Alex-Torres** [comment]
I am running latest on Windows 7 X64 with no issues.

**Comment by b4youleap** [comment]
I am on Win 7 as well - no issues here. I still run terminal as admin.
angular-cli: 1.0.0-beta.21
node: 5.12.0
os: win32 x64

**Comment by filipesilva** [comment]
I also work on Windows. Not sure what's happening in your case tbh. If you can get me a repro, I can investigate, but I think it has to do with your environment.

Sorry I can't be of more help.
