### ISSUE TITLE
[Question | Feature] : building library current status

### ISSUE THREAD

**Issue by sebastian-heinz** [angular/angular-cli#3277]
Hello,

will angular-cli provide the ability to create library projects? 
So that one can create a module via angular-cli and import it via the package.json file in an existing project?

I think especially with the ability to separate your project into ng-modules it would be good to have support from angular-cli to create module library projects easy, so they can be published to npm. 

Would like to know about the current state, and future plans. I feel like i'm having a hard time to accomplish this, and after searching I found some projects that promise to do it for you.
(ex. https://github.com/jvandemo/generator-angular2-library)

Maybe i'm missing something and its already possible?

**Comment by valorkin** [comment]
You can try https://github.com/valor-software/npm-submodules, it is a core repository for ngm-cli
I am managing ng2-bootstrap, it is missing docs, but has cli help command :)

**Comment by attilacsanyi** [comment]
Thanks @valorkin, nice job!

**Comment by filipesilva** [comment]
We don't have this feature yet, but it's being tracked in https://github.com/angular/angular-cli/issues/1692.
