### ISSUE TITLE
Visual Studio Code displays experimentalDecorators warning.

### ISSUE THREAD

**Issue by bryanerayner** [angular/angular-cli#3278]
### OS?
> macOS

### Versions.
angular-cli: 1.0.0-beta.18
node: 4.6.0
os: darwin x64

### Repro steps.
Load app created with this version in VS Code 1.6
Upgrade VS Code to 1.7
Preview any screen in the app

### The log given by the failure.
No log is given, this is some error arising in VSCode related to it not loading a `tsconfig.json` file correctly.
![image](https://cloud.githubusercontent.com/assets/1864716/20614108/58f23626-b290-11e6-8874-857bbe5380af.png)

### Mention any other details that might be useful.
Really, just trying to figure out what is to be done to resolve this error. I'm wary of modifying `tsconfig.json` as I think this is something that would be best to leave unmodified?

**Comment by ogix** [comment]
You should specify VS Code to use workspace typescript: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Comment by filipesilva** [comment]
Yeah you're getting that because your VSCode doesn't support 2.0. Newer VSCode versions should be fine, as well as @ogix's suggestion.
