### ISSUE TITLE
require.context not working in dev mode

### ISSUE THREAD

**Issue by winkerVSbecks** [angular/angular-cli#3279]
I am trying to load multiple files using a similar startegy to what is done in `test.ts`. 
It doesn't seem to work in dev mode. But works fine when running tests.

```
let context = require.context('./', false, /\.svg/);
context.keys().map(context);
```

### OS?
macOs Sierra 10.12.1

### Versions.
```
angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: darwin x64
```

### Repro steps.

Add this to `app.component.ts`
```
let context = require.context('./', true, /\.ts/);
context.keys().map(context);
console.log(context.keys());
```

then run `npm start`

### The log given by the failure.
<img width="772" alt="screen shot 2016-11-25 at 12 01 39 am" src="https://cloud.githubusercontent.com/assets/42671/20614938/615f771c-b2a2-11e6-9fb8-c13089095c23.png">

**Comment by filipesilva** [comment]
The `require.context` usage we do in `test.ts` is kind of a special test-only thing. It's fine to do it there because it assumes webpack and there's special tooling to make it work with karma. 

I don't think there's any real way to make it work in the app itself.
