### ISSUE TITLE
Javascript file corresponding to each typescript file in Angular-cli

### ISSUE THREAD

**Issue by praneshuh-Infy** [angular/angular-cli#3281]
we are not able to see javascript file for every typescript file. What we are able to see after ng serve is bundle.js for the overall application.
Is there any way that we can get javascript file for corresponding typescript file?

**Comment by scttcper** [comment]
`./node_modules/.bin/tsc -p src -d` will output the javascript files to `/dist/out-tsc`

**Comment by praneshuh-Infy** [comment]
Yup this worked. 

Thanks
