### ISSUE TITLE
Help  running angular-cli without network connection

### ISSUE THREAD

**Issue by gioragutt** [angular/angular-cli#3283]
Hi, In my workplace we have no connection to WWW, meaning that we can't `npm install` every little dependency we have, but instead we have to make complete packages so that we can whiten them inside of our network and use them, which is a long process.
How do I make a complete package which I can install with an offline `npm` to have angular2 working, with some of the good libraries people tend to use? I'm been looking for such a thing for ages and I couldn't find anything. Neither for Angular2 nor for React
> ---------------------------------------------------------------

### OS?
I'm using Debian8 linux.

### Versions.
Node version 4.5.0 (can install higher version if needed to run)

### What I've tried
I've tried to whiten React before, with all the dependencies needed, but when I tried building it with webpack it throws a "es6.object.to-string missing" message every time. We checked the files that tried to `require` that given path, and it seems that they are in a correct path, corresponding to the files they're trying to require.

**Comment by filipesilva** [comment]
Hrm.... I'm not too sure myself. Probably you'd want a private npm repo like https://www.npmjs.com/package/sinopia, running somewhere on your network.
