### ISSUE TITLE
Regression: separated config for index.html source and output

### ISSUE THREAD

**Issue by ishitatsuyuki** [angular/angular-cli#3289]
angular-cli: 1.0.0-beta.21 *patched webpack config to support pug*
node: 7.2.0
os: linux x64
The patch is simply a dirty version of #2205.

I have configured like this so pug is compiled:
`"index": "index.pug"`
However, this also changes the output extension, which not only doesn't make sense but also breaks development server(`ng serve`).

Random notes:
webpack dev-server seems to have index.html hardcoded, and it's the default for most static servers too.

**Comment by filipesilva** [comment]
That kind of support needs to come in #2205 really. It doesn't make a lot of sense to have it otherwise.
