### ISSUE TITLE
linking an image from template html requires path from app root

### ISSUE THREAD

**Issue by entzik** [angular/angular-cli#3292]
### OS? 
OSX El Capitan

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.2.2
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

- create a component under app, say AppHeaderComponent. 

- in the component directory - app-header - create an 'images' directory. 

- put an image in that directory, say 'company-logo.png'. 

- in the template link the image as '&lt;img src="images/company-logo.png"&gt;'. now serve the application

- serve the app using ng-serve

=> this used to be possible when building with 1.0.0-beta16, the image would show up as expected. when building with 1.0.0.beta21 the image is not found. for it to work, I need to specify the full path from root: "&lt;img src="app/header-panel/images/company-logo.png"&gt;. This is annoying because if I decide to refactor the project by renaming the components or moving it deeper in the hierarchy I need to also refactor all the templates. Being able to specify a relative path relative to the template is a big advantage. Also I need to publish this "app-header" as a reusable component, the image belongs next to the template.

### The log given by the failure.
no specific log

> Thanks! We'll be in touch soon.

**Comment by Nikki1993** [comment]
You are supposed to put images in the assets folder that is inside src folder then you can specify path as `assets/../image.png `

**Comment by entzik** [comment]
that would be OK if you're thinking "website". I am thinking "reusable component". that image exclusively belongs to the component and I would like it to stay next to the template that uses it.

**Comment by Nikki1993** [comment]
**offtopic**: I am curious still why would you want to have image attached to the template and not in assets folder even if you are thinking "reusable component"? I am building websites mainly with Angular so I am really interested in the use case you want to use it in :)

**Comment by filipesilva** [comment]
We had this in once, by using `HTML-loader`, but it broke a lot of projects (see https://github.com/angular/angular-cli/issues/2396). 

I agree that the scenario you're proposing is super relevant.

**Comment by filipesilva** [comment]
Closing in favor of https://github.com/angular/angular-cli/issues/3415, there's some more discussion in that one.

**Comment by dlarr** [comment]
@entzik . I am looking for a way to do the exact same thing. Embbed an image into component that will be reused. Did you overcome this ? If yes How ? 

regards

**Comment by ryager01** [comment]
Best way I can come up with is to include the image inline, either in the html or the css, Here is a walk through

http://www.websiteoptimization.com/speed/tweak/inline-images/
