### ISSUE TITLE
Regex pattern in version.ts

### ISSUE THREAD

**Issue by kkleokrish** [angular/angular-cli#3296]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS? All
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions. 1.0.0-alpha-1
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps. Any ng command
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
The current regex in version.ts under upgrade/ looks like:

 `   ? this._version.match(/^(\d+)\.(\d+)(?:\.(\d+))?(?:-(alpha|beta|rc)\.(.*))?$/).slice(1)`

This does not match the version 1.0.0-alpha-1 and causes slice call on null.

Changing this to:

 `   ? this._version.match(/^(\d+)\.(\d+)(?:\.(\d+))?(?:-(alpha|beta|rc)-(.*))?$/).slice(1)`

removes the error. 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
This is something we're not very interested in fixing, since we don't propose to support versions that old. If you are willing to do a PR for it I'll be happy to review you though. It should support both `.` and `-` though.
