### ISSUE TITLE
disable the validation of *.d.ts files from npm dependencies

### ISSUE THREAD

**Issue by noelmace** [angular/angular-cli#3302]
### OS?

 Windows 10

### Versions.

angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64

### Repro steps.

For example with @types/jquery.

In your angular-cli project :
```
npm i --save-dev @types/jquery
```
then add the following code anywhere : 
```
import * as jquery from 'jquery';
````
Then run ng serve or build, and you'll get the following log in the console.

### The log given by the failure.
```
[default] C:\Documents and Settings\nmace\dev\github\angular-buzz\node_modules\@types\jquery\index.d.ts:3246:5
    Duplicate identifier 'export='.
[default] C:\Users\nmace\dev\github\angular-buzz\node_modules\@types\jquery\index.d.ts:623:5
    Duplicate string index signature.
[default] C:\Users\nmace\dev\github\angular-buzz\node_modules\@types\jquery\index.d.ts:2872:5
    Duplicate string index signature.
[default] C:\Users\nmace\dev\github\angular-buzz\node_modules\@types\jquery\index.d.ts:2873:5
    Duplicate number index signature.
[default] C:\Users\nmace\dev\github\angular-buzz\node_modules\@types\jquery\index.d.ts:3246:5
    Duplicate identifier 'export='.
[default] Checking finished with 6 errors
```

### Mention any other details that might be useful.

Any project using this kind of dependencies with angular-cli@1.0.0-beta.21 will have this kind of errors showing, which will break any ``ng build -prod``. I think we should ignore this files by default.

**Comment by filipesilva** [comment]
I don't think these are CLI-specific. I would expect any typescript project to behave similarly.
