### ISSUE TITLE
Cannot redefine property

### ISSUE THREAD

**Issue by Judp0m** [angular/angular-cli#3308]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux (Ubuntu)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

ng --version
angular-cli: 1.0.0-beta.21
node: 4.2.1
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

I have been using bootstrap with prior version of angular-cli without an issue. After upgrading to beta.21:
1) no problem via ng serve and local deployment
2) ng build --prod and deployment on app-engine leads to the following error in the console
Uncaught TypeError: Cannot redefine property: b
    at Function.defineProperty (<anonymous>)

The code it references (bootstrap 0c41236…:111)

 ```
// define getter function for harmory exports
 	__webpack_require__.d = function(exports, name, getter) {
 		Object.defineProperty(exports, name, {
 			configurable: false,
 			enumerable: true,
 			get: getter
 		});
 	};
```

The version of bootstrap: `"bootstrap": "^4.0.0-alpha.5",`
And in angular-cli.json:

 ```
     "scripts": [
        "../node_modules/tether/dist/js/tether.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js"
        ],
```

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I don't know why you're getting this problem, but if it works on `ng serve` then I don't think it's a CLI problem. You can also try doing `ng build` and then using another server locally. 

If you can repro outside of AppEngine I'll reopen and take a look.
