### ISSUE TITLE
Getting 'Map' is undefined error.

### ISSUE THREAD

**Issue by Shijir** [angular/angular-cli#3309]
### OS?
```
Windows 7 (running on a VM)
```

### Versions.
```
angular-cli: 1.0.0-beta.20-4
node: 6.6.0
os: darwin x64
```

### Repro steps.

I am trying to use the custom elements v1 polyfill (custom-elements.min.js) in the angular-cli.json by using the following pattern:

```
      "scripts": [
        "../node_modules/mutationobserver-shim/dist/mutationobserver.min.js",
        "../node_modules/@webcomponents/custom-elements/custom-elements.min.js",
      ],
```
This works across all browsers except IE10. In the console, it says:

```
SCRIPT5009: 'Map' is undefined 
```

### Mention any other details that might be useful.

The polyfill works fine when loaded through `script` tag in a non angular-cli static website. However, in angular-cli generated projects, it logs an error when I try to use it in the scripts section of angular-cli.json. The error will be gone and the polyfill will start working fine if I insert es6-shim in the script: 

```
      "scripts": [
        "../node_modules/es6-shim/es6-shim.min.js",
        "../node_modules/mutationobserver-shim/dist/mutationobserver.min.js",
        "../node_modules/@webcomponents/custom-elements/custom-elements.min.js"
      ],
```

However, I don't want to use `es6-shim` because there is `core-js/es6/map` imported in the `polyfills.ts` file. Also, it does work fine with no es6 shims so for the polyfill, I believe I don't need either of them. 

The log error was pointing at the polyfill (https://github.com/webcomponents/custom-elements/blob/master/custom-elements.min.js). 

<img width="336" alt="screenshot 2016-11-28 23 56 57" src="https://cloud.githubusercontent.com/assets/3958008/20701208/9ad6e44a-b5c6-11e6-9f49-9ac7acb8ce11.png">

I would like to know why it's getting this error on only IE10.

Thank you!

**Comment by filipesilva** [comment]
I think I know the reason for this. It's true that you have `core-js/es6/map` in `polyfills.ts`, but the scripts array is loaded before the main bundle. So `custom-elements.min.js` never sees the Map shim.

The solution is to add es6-shim to scripts instead of `polyfills.ts`. Maybe the CLI should do that by default really.

**Comment by filipesilva** [comment]
Also related to https://github.com/angular/angular-cli/issues/2752

**Comment by Shijir** [comment]
@filipesilva thank you for the response. Your explanation really helped me to confirm my assumption of what was causing the error. I am wondering why script arrays are loaded before polyfills. In the documentation, it's recommended to have those 3rd party libraries in the scripts array. But there are some libraries that depend on the polyfills such as `core-js` and other shims. So I thought it would make sense if angular-cli loads those 3rd pary libraries after loading the polyfills.ts.
