### ISSUE TITLE
Issue upgrading karma.conf.js for latest angular-cli

### ISSUE THREAD

**Issue by sreenivasulun** [angular/angular-cli#3310]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.20-4
node: 6.1.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Upgrading angular-cli from 1.0.0-beta.9 to 1.0.0-beta.20-4 webpack

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
We are upgrading angular 2 RC4 to angular 2.1.0 stable. Initially project was created using angular-cli version  1.0.0-beta.9, now we are upgrading both angular-cli and angular 2 stable version. I created project again using angular-cli version 1.0.0-beta.20-4 webpack. And then started upgrading. 

I am able to upgrade both angular-cli and angular 2. After upgrade, the whole application is working fine. Now stuck with upgrading karma.conf.js. 

Please find attached karma.conf.js file. Please provide help on how to make it work the below script. 

```
module.exports = function (config) {
  config.set({
    basePath: '..',
    frameworks: ['jasmine'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-phantomjs-launcher'),
      require('karma-junit-reporter'),
      require('karma-verbose-reporter'),
      require('karma-coverage')
    ],
    customLaunchers: {
      // chrome setup for travis CI using chromium
      Chrome_travis_ci: {
        base: 'Chrome',
        flags: ['--no-sandbox']
      },
      'PhantomJS_flags': {
        base: 'PhantomJS',
        flags: ['--load-images=false']
      }
    },
    files: [
      'https://code.jquery.com/jquery-2.1.4.min.js',
      'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js',
      {pattern: 'dist/vendor/es6-shim/es6-shim.js', included: true, watched: false},
      {pattern: 'dist/vendor/zone.js/dist/zone.js', included: true, watched: false},
      {pattern: 'dist/vendor/reflect-metadata/Reflect.js', included: true, watched: false},
      {pattern: 'dist/vendor/systemjs/dist/system-polyfills.js', included: true, watched: false},
      {pattern: 'dist/vendor/systemjs/dist/system.src.js', included: true, watched: false},
      {pattern: 'dist/vendor/zone.js/dist/async-test.js', included: true, watched: false},
      {pattern: 'dist/vendor/zone.js/dist/fake-async-test.js', included: true, watched: false},

      {pattern: 'config/karma-test-shim.js', included: true, watched: true},

      // Distribution folder.
      {pattern: 'dist/**/*', included: false, watched: true}
    ],
    exclude: [
      // Vendor packages might include spec files. We don't want to use those.
      'dist/vendor/**/*.spec.js'
    ],
    preprocessors: {
      'dist/app/**/*.js': 'coverage'
    },
    reporters: ['progress', 'verbose', 'junit', 'coverage'],
    junitReporter: {
      outputFile: 'ocui_unit_test-results.xml'
    }
    ,
    coverageReporter: {
      dir: 'coverage/',
      reporters: [
        {type: 'cobertura'},
        {type: 'html'}
      ]
    },
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    //browsers: ['PhantomJS'],
    browsers: ['Chrome'],
    singleRun: true,
    browserNoActivityTimeout: 50000
  })
  ;
};

```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by sreenivasulun** [comment]
except generating coverage report in 'cobertura' format, achieved running unit tests and junitReporter. 
I am thinking to try, https://github.com/sshev/karma-remap-coverage to generate coverage report in  'cobertura' format. Hope I can achieve it.

**Comment by filipesilva** [comment]
That's a big upgrade that you're trying to do there. My advise is to start with the karma config (and `src/test.ts` file) from a brand new project and work from there. 

We changed from SystemJS to Webpack after beta.9 and that deeply affected the test setup. With the current one you don't need to list the script files but you do need to list them in `angular-cli.json` which adds them to the build. `ng test --code-coverage` also does code coverage via remap automatically now.
