### ISSUE TITLE
Issue with webpack2

### ISSUE THREAD

**Issue by gjuchault** [angular/angular-cli#3320]
### OS?
macOs Sierra

### Versions.
```
angular-cli: 1.0.0-beta.21
node: 7.1.0
os: darwin x64
```

I guess the bug comes from webpack2 that now understands import/export. I have a shared folder with a lot of services, and I import them inside my `app.module.ts`:

`app/shared/logger/logger.ts`:
```
export enum Level { OFF = 0, ERROR = 1, WARN = 2, INFO = 3, DEBUG = 4, LOG = 5 }
```

`app/shared/logger/index.ts`:
```
export * from './logger.service';
export * from './level';
```

`app/shared/index.ts`
```
export * from './logger';
// ... other services
```

`app/app.module.ts`:
```
import {
  // ... other services
  LoggerService,
  Level
} from './shared';

console.log(Level); // undefined
```

If I change the last line to `console.log(Level, require('./shared').Level);` they both get printed

**Comment by clydin** [comment]
Is there an index.ts in the animation directory?

**Comment by gjuchault** [comment]
Indeed, I added it to the post

**Comment by clydin** [comment]
the only thing that's exported is 'reflow'.

**Comment by gjuchault** [comment]
I fixed all code examples sorry

**Comment by clydin** [comment]
Does it only happen with the enum?  I remember reading about an issue regarding exports and enums but don't remember where I saw it.

**Comment by gjuchault** [comment]
It's with everything I export with `*` somehow

**Comment by gjuchault** [comment]
Weird thing: if I `console.log(module.exports)` inside `app/shared/logger/index.ts`, and I get this:

https://i.imgur.com/wSDmsle.png

**Comment by filipesilva** [comment]
I wonder if this is related to `ngc` as well. Needs some investigation.

**Comment by gjuchault** [comment]
I'm not using ngc or I did nothing to do so. Maybe that is related to typescript handling of `export *` ?

**Comment by filipesilva** [comment]
Closing as outdated, please let me know if you still experience this error. Might also be related to https://github.com/angular/angular-cli/issues/2741.
