### ISSUE TITLE
Enable ts-helpers by default in generated projects

### ISSUE THREAD

**Issue by bryanforbes** [angular/angular-cli#3325]
All projects generated by `angular-cli` have a dependency on `ts-helpers`, but `ts-helpers` is not imported into the projects (or test harness) and the compiler outputs helpers in every file that needs them (which is every file that uses decorators or `extends`). Using `ts-helpers` in generated projects by default will have the benefit of reducing build sizes for the average user.

Generated projects should have the following modifications:

1. Add `import 'ts-helpers';` at the top of `src/main.ts` and `src/test.ts` after `import './polyfills.ts';`
2. Add `"noEmitHelpers": true` to the `compilerOptions` object in `src/tsconfig.json`
### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: darwin x64

### Repro steps.
1. `ng new test-project`
2. `grep` for `import 'ts-helpers';` and find 0 instances
3. Inspect `src/tsconfig.js` and find no `"noEmitHelpers": true`

**Comment by clydin** [comment]
I'm pretty sure that dependency is a leftover that was never removed.
And with the imminent release of TS 2.1, it will no longer be needed either way.

**Comment by nadavsinai** [comment]
although TS 2.1 has better support for external helpers some steps are still needed:

tsconfig.ts (aot too) --> add flag importHelpers:true
package.json --> add 'tslib' (official TS lib for helpers)

Typescript will insert the import statements itself
[see here](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#support-for-external-helpers-library-tslib)

this will give  an important improvement in dist code size

**Comment by clydin** [comment]
Yes. However, this is blocked until the CLI supports 2.1.

**Comment by filipesilva** [comment]
I think the TS 2.1 approach is the more adequate one for this problem, yeah.

**Comment by sublimator** [comment]
When is angular-cli going to support TypeScript 2.1 ?

**Comment by filipesilva** [comment]
Superseded by https://github.com/angular/angular-cli/pull/6277
