### ISSUE TITLE
Installation of typed-json

### ISSUE THREAD

**Issue by aleyango** [angular/angular-cli#3327]
Hi, 

Is possible that you provide me the way to install typed-json? I dont get how to install it correctly.

### OS?
> Mac OSX  Sierra

### Versions.
>angular-cli: 1.0.0-beta.19-3
node: 7.2.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
typed-json

### The log given by the failure.
> Normally this include a stack trace and some more information.
typedjson-npm@0.1.6

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I'm sorry but I don't have time to look into specific libs for usage. There's lib instructions in https://github.com/angular/angular-cli#3rd-party-library-installation, but you'll more likely to get help in StackOverflow or that repos issue tracker.
