### ISSUE TITLE
ng serve reports error after importing new module

### ISSUE THREAD

**Issue by diminutivesloop** [angular/angular-cli#3328]
### OS?
Windows 7

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.3.1
os: win32 x64

### Repro steps.
1. Run `ng serve`.
2. Create a new TypeScript or JavaScript module and import it into the project via an `import` statement.

### The log given by the failure.
    Cannot find module '<module import path>'.
    [default] Checking finished with 1 errors

### Mention any other details that might be useful.
Despite this error the project builds successfully and the new module is included in the bundle.

**Comment by jongunter** [comment]
I'm seeing this sometimes, too. It's hard to pin down exactly what triggers it, but often after importing something new into a file and saving.  Everything works, but I still see error messages in my browser and the console.

If I `ctrl+c` out of `ng serve` and re-run `ng-serve` the errors go away in the next build.

```
angular-cli: 1.0.0-beta.19-3
node: 6.3.0
os: win32 x64
```

**Comment by filipesilva** [comment]
Odd. I suppose some files aren't being added correctly by the webpack plugin.

**Comment by filipesilva** [comment]
Closing as outdated. If this still happens, please let me know.
