### ISSUE TITLE
CLI default output is too verbose

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular-cli#333]
Executing either `ng` or `ng --help` outputs the entire list of possible commands + their options. This can be very overwhelming.

Is that something we want to trim down a little bit?

For example, `git` gives us a nice little overview of the most commonly used commands. I think this is a good way to handle this.

```
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

The most commonly used git commands are:
   add        Add file contents to the index
   bisect     Find by binary search the change that introduced a bug
   branch     List, create, or delete branches
   checkout   Checkout a branch or paths to the working tree
   clone      Clone a repository into a new directory
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   fetch      Download objects and refs from another repository
   grep       Print lines matching a pattern
   init       Create an empty Git repository or reinitialize an existing one
   log        Show commit logs
   merge      Join two or more development histories together
   mv         Move or rename a file, a directory, or a symlink
   pull       Fetch from and integrate with another repository or a local branch
   push       Update remote refs along with associated objects
   rebase     Forward-port local commits to the updated upstream head
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index
   show       Show various types of objects
   status     Show the working tree status
   tag        Create, list, delete or verify a tag object signed with GPG

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
```

**Comment by filipesilva** [comment]
This comes from `ember-cli` at the moment. It has a mechanism were it lists all commands from itself and addons.

I don't think it's feasible to change it *right now* but I also got scared when I ran `ng --help` three days ago, so yeah. Very verbose.

**Comment by PascalPrecht** [comment]
@filipesilva so, do we want to discuss this and maybe determine what subset of commands ng-cli should display by default?

**Comment by filipesilva** [comment]
I think it should be discussed, but while keeping in mind it is hard to change right now. Overwriting the current one will drop support for addons. We're moving away from them right now but want to revisit after ng-conf.

Discussion wise... I think all commands the CLI supports should be there, but without the flags. And that `ng help command-name` should show the flags.

**Comment by jkuri** [comment]
We can override [this](https://github.com/ember-cli/ember-cli/blob/master/lib/commands/help.js) command as we are overriding some others already. I think it's not so hard to change it.

**Comment by filipesilva** [comment]
I went to check and there is actually an option to set help verbosity in [ember-cli](https://github.com/ember-cli/ember-cli/blob/master/lib/commands/help.js)... which doesn't seem to be used. Maybe it's actually a bug.

**Comment by jkuri** [comment]
It could be a bug, yes. If we decided to override this command it actually provides availability for `json` output with the `--json` flag which can be used to prettify the output.

**Comment by filipesilva** [comment]
Checked `ember-cli` itself, and `--verbose` is working. It makes stuff even more verbose though.

**Comment by hansl** [comment]
As we are fully concentrated on the alpha release, `ng help` will remain unchanged until ng-conf. There's a plan to clean up everything inherited from ember-cli in the future, after the release.

Closing this.
