### ISSUE TITLE
Sensitive environment variables

### ISSUE THREAD

**Issue by mikesigs** [angular/angular-cli#3336]
Hi guys,

I am wondering if there is any plan to support something like [dotenv](https://www.npmjs.com/package/dotenv)

It would be nice to be able to store sensitive environment settings (e.g. api keys) this way. It's a really helpful npm package and would make a great addition to the CLI.

Thanks!

**Comment by antonybudianto7** [comment]
I agreed with using dotenv, but not for storing sensitive information

https://softwareengineering.stackexchange.com/questions/194045/securely-storing-secret-data-in-a-client-side-web-application

using dotenv really helps with many environments and is scalable

even create-react-app bundled dotenv by default https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-development-environment-variables-in-env

**Comment by mikesigs** [comment]
Y'know I didn't realize how dumb of a question I had asked until just now. Of course you're not going to be able to use dotenv in a client side app. You're not going to access environment variables on the clients machine. And yeah... Obviously not going to store sensitive data there either. 

Closing to hide my shame...

**Comment by antonybudianto7** [comment]
Well, some key like firebase apiKey, is non-secret, and can be bundled to client-side code, since they have domain whitelist mechanism. Using dotenv in a client side app is possible, like create-react-app, but you still store secret information on server side.

**Comment by mikesigs** [comment]
I was just thinking about not committing certain settings to the repository and dotenv enables that. But I didn't consider that anything you put in dotenv will wind up in your compiled code anyways.

So I guess the real question is, what does dotenv provide that the current environment configuration in the CLI doesn't?

**Comment by antonybudianto7** [comment]
well, if the env is used for things like debug flag, production flag, or API url, then current configuration is enough, **but** since it's committed to source control, then it'll affect other developers that uses the same environment. and,.... it's not the problem with dotenv, since each developer have their own `.env` :+1:

**Comment by frankfullstack** [comment]
I tried with the **dotenv** package, and several **webpack** plugins without exit.

Anyone tried these packages: [webpack-dotenv-plugin](https://github.com/nwinch/webpack-dotenv-plugin) and [dotenv-webpack](https://github.com/mrsteele/dotenv-webpack)?

I want to inject some environment api keys to my Angular services but I'm not be able to do it.

**Comment by antonybudianto** [comment]
Example starter using dotenv
https://github.com/antonybudianto/angular-webpack-starter

**Comment by filipesilva** [comment]
Discussion on how to do this sort of thing can be found in https://github.com/angular/angular-cli/issues/3855.
