### ISSUE TITLE
Add customization options for HtmlWebpackPlugin

### ISSUE THREAD

**Issue by miltador** [angular/angular-cli#3338]
Currently app configuration doesn't allow to configure `HtmlWebpackPlugin` to use it's templating features.

It might be useful to have separate option in app config to specify different value for template option,
e.g. `index.ejs` to use ejs templates and allow `HtmlWebpackPlugin` to process it and generate `index.html`.

Also it would be useful to know the current environment inside the template to conditionally add things to resulting `index.html`.

**Comment by filipesilva** [comment]
I understand that there are uses for such a feature, but it's something we want to add at the moment.

**Comment by timbru31** [comment]
> at the moment.
This was >1 year ago. Care to re-consider this decision? We'd like to customize this, too, but don't want to inject, since we ❤️ the Angular CLI.

**Comment by that70schris** [comment]
this is a real bummer for adding tracking to a site that requires different environments. it pretty much prevents loading 3rd party tracking products using the index file to make sure they load as fast as possible
