### ISSUE TITLE
feat: make git repo initialization optional

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular-cli#334]
By default `ng new PROJECT` initializes a git repo and even performs a commit as angular-cli@angular.io.

I could imagine that there'll be projects where only authorised/white-listed users should commit into the repo. Maybe we should make the repo initialization and commit optional? Or at least the commit?

What are you thoughts on this?

**Comment by filipesilva** [comment]
Hm. Good catch. That's definitely a thing.

**Comment by jkuri** [comment]
This is achievable already running `ng new project --skip-git`.

**Comment by PascalPrecht** [comment]
@jkuri Perfect. Closing.

**Comment by santhoshsiddamshetty** [comment]
its working thankyou
