### ISSUE TITLE
Move reflect-metadata to a peer dependancy

### ISSUE THREAD

**Issue by waterfoul** [angular/angular-cli#3342]
### OS?
All

### Versions.
All versions after 1.0.0-beta.20-1

### Repro steps.
Look at the package.json in an installed angular-cli

### Mention any other details that might be useful.
If two modules import different versions of this module it will cause some very confusing errors. By including it as a peer npm will output a warning upon detecting a version mismatch and will only install the newer of the mismatched versions. Situations like this is the whole reason the concept of peer dependencies exists

**Comment by CarreraPHP** [comment]
#3655 pull request removes the need for reflect-metadata in cli and @ngtools webpack. If & when merged, this issue will no longer be required.

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/3655
