### ISSUE TITLE
@ngtools/webpack can't  load a module when AOT

### ISSUE THREAD

**Issue by kunl** [angular/angular-cli#3350]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows  10

### Versions.
 "@angular/compiler": "~2.2.3",
 "@angular/compiler-cli": "~2.2.3",
 "@ngtools/webpack": "^1.1.6",
 "webpack": "^2.1.0-beta.27",

### Repro steps.
**webpack.aot.ts**
``` typescript 
let webpackConfig = {
    entry: {
        polyfills: './src/polyfills.ts',
        vendor: './src/vendor.ts',
        app: './src/main.ts'
    },
    output: {
        publicPath: 'aot/',
        path: path.resolve(__dirname, './aot')
    },
    plugins: [
        new AotPlugin.AotPlugin({
            tsConfigPath: './ts-aot.json',
            entryModule: path.join(process.cwd(), 'src', 'app', 'app.module') + '#AppModule'
        }),
      
    ],
}
```
**app.router.ts**
-------------
export function loadHome(){ return HomeModule }
{ path: 'home', loadChildren:  loadHome },
-------------
``` typescript 
import { Routes } from '@angular/router';

import { AboutComponent } from './components/about/about.component';
import { contactComponent } from './components/contact/contact.component';
import { HomeModule } from './components/home/home.module';


import { ListComponent } from './components/home/list/list.component';
import { DetailComponent } from './components/home/detail/detail.component';

export function loadHome(){ return HomeModule }

export const rootRouterConfig: Routes = [
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: 'home', loadChildren:  loadHome },
    { path: 'about', component: AboutComponent},
    { path: 'contact', component: contactComponent },

    {
        path:'news', loadChildren: './components/news/news.module#NewsModule'
    }
];


```

### The log given by the failure.
``` bash
 webpack --config webpack.aot.ts

src/app/app.module#AppModule  --entry
StaticSymbol {
  filePath: 'D:/code/angular2/Angular-webpack-AOT/src/app/app.router.ts',
  name: 'loadHome',
  members: undefined } ' --entry'
TypeError: entry.split is not a function
    at Function.ModuleRoute.fromString (D:\code\angular2\Angular-webpack-AOT\node_modules\@ngtools\webpack\src\plugin.js:25:27)
    at D:\code\angular2\Angular-webpack-AOT\node_modules\@ngtools\webpack\src\plugin.js:245:34
    at Array.map (native)
    at AotPlugin._processNgModule (D:\code\angular2\Angular-webpack-AOT\node_modules\@ngtools\webpack\src\plugin.js:244:14)
    at D:\code\angular2\Angular-webpack-AOT\node_modules\@ngtools\webpack\src\plugin.js:218:39
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Windows_NT 10.0.14971

```

### Mention any other details that might be useful.

**I want use @ngtools/webpack to complier AOT and loadChildren, but it only used by sting 
<code>loadChildren: './components/news/news.module#NewsModule'</code>, not work when i used 
<code>export function loadHome(){ return HomeModule }  { path: 'home', loadChildren:  loadHome },</code>.**

**Comment by hansl** [comment]
Where are those logs from?

**Comment by borislemke** [comment]
@kunl try to change the path from `loadChildren: './components/news/news.module#NewsModule'` to `loadChildren: 'app/components/news/news.module#NewsModule'` or `loadChildren: 'src/app/components/news/news.module#NewsModule'`. I can't surely remember which of the two it is, but I had a similar issue with these little pitas. Relative doesn't seem to work for some odd reason.

**Comment by kunl** [comment]
@hansl  @borislemke  
when i use router  like this
``` typescript
import { HomeModule } from './components/home/home.module';
export function loadHome(){ return HomeModule }
[{ path: 'home', loadChildren: loadHome }]
````

**Comment by marcuskrahl** [comment]
I have the same problem. When I define a route like `{ path: 'lazyModule', loadChildren: loadLazyModule}` (which is allowed according to the angular source) webpack fails with the error message `entry.split is not a function`

This is because the reference to the function, i.e. `{"filePath":"C:/Users/user/Project/routes.ts","name":"loadLazyModule"}` is passed to `ModuleRoute.fromString` in `AotPlugin._processNgModule`

I can provide further information if necessary

**Comment by DzmitryShylovich** [comment]
@kunl You need to return `NgModuleFactory` instead of `NgModule` in aot https://github.com/angular/angular/issues/11075#issuecomment-272384125

@hansl webpack plugin should automatically rewrite
```
export function loadProfileModule() {
	return ProfileModule;
}
```
into 
```
export function loadProfileModule() {
	return ProfileModuleNgFactory;
}
```
similar to `bootstrapModule` and `bootstrapModuleFactory`

**Comment by filipesilva** [comment]
Closing as outdated. If this still happens, please let me know.
