### ISSUE TITLE
AOT fails at runtime with ViewEncapsulation.None

### ISSUE THREAD

**Issue by armstrjare** [angular/angular-cli#3353]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

MacOS Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.22
node: 7.2.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

1. Create app `mkdir cli-test && cd cli-test && ng init`
2. Set ViewEncapsulation.None on AppComponent
```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  encapsulation: ViewEncapsulation.None // <---
})
```
3. `ng serve --aot` (NB: this issue also ocurrs in `ng serve --aot --prod`)
4. Browser errors due to `component.styles` is an array of 1 element, but that value is `undefined` (`[undefined]`)

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
vendor.bundle.js:12175 TypeError: Cannot read property 'replace' of undefined
    at flattenStyles (vendor.bundle.js:9776)
    at new DomRenderer (vendor.bundle.js:9555)
    at DomRootRenderer_.DomRootRenderer.renderComponent (vendor.bundle.js:9513)
    at DebugDomRootRenderer.renderComponent (vendor.bundle.js:28996)
    at ViewUtils.renderComponent (vendor.bundle.js:3608)
    at View_AppComponent0.AppView (vendor.bundle.js:20106)
    at new View_AppComponent0 (main.bundle.js:138)
    at View_AppComponent_Host0.createInternal (main.bundle.js:108)
    at View_AppComponent_Host0.AppView.createHostView (vendor.bundle.js:20137)
    at ComponentFactory.create (vendor.bundle.js:7684)
```

This happens because  `componentProto.styles`  is an array of 1 element, but that value is `undefined` (`[undefined]`)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
Experimental build should not be used.

**Comment by armstrjare** [comment]
@hansl apologies if I'm missing something, but can you clarify? What have I used that was experimental?

**Comment by hansl** [comment]
Beta.22 is not released yet.

**Comment by armstrjare** [comment]
Oh, sorry I didn't realise. I had installed via `npm` so I had assumed it was released. Thanks!

**Comment by anabulsi** [comment]
I'm using Beta 20 and I'm getting the same error :(

**Comment by anabulsi** [comment]
Its related to this issue: https://github.com/angular/angular/pull/12203#issuecomment-252980372

**Comment by yfain** [comment]
In beta.24 using ng serve -aot or ng serve -aot -prod works fine. No errors. 
This issue can be closed.
