### ISSUE TITLE
ng build and serve defaults to AOT

### ISSUE THREAD

**Issue by bialad** [angular/angular-cli#3354]
### OS?
Linux (Ubuntu 16.10)

### Versions.
ng version
angular-cli: 1.0.0-beta.22
node: 6.9.1
os: linux x64

### Repro steps.
Run `ng build`, `ng build --aot` and even `ng build -aot`. They all produce the same files in the `dist` folder.

### Mention any other details that might be useful.

I noticed this because the update to beta.22 broke my absolute paths in `ng build` and `ng serve`, this has before been an issue only when running in AOT-mode.

Also, the build times are now 20 to 30 s. From 2 - 3 s before.

**Comment by slubowsky** [comment]
And due to https://github.com/angular/angular-cli/issues/2496 I am unable to run my application as the workaround fails when using AOT.
I'm sure this will be fixed shortly but right now it seems not to be just a default value issue. I tried --aot=false but it made no difference

**Comment by rosslavery** [comment]
Can confirm. My app is not AoT ready yet, and I can no longer run `ng serve`.

Running `ng serve --aot=false` and `ng serve --aot false` seems to have no effect either.

**Comment by kylecordes** [comment]
I have also observed that many of our applications don't yet work on AOT, and am surprised to see AOT as the default before is more robust. (Making AOT default eventually is of course a wonderful idea, really looking forward to it.)

**Comment by rosslavery** [comment]
I get the feeling it wasn't meant to be enabled by default, especially since the flag seems to be having no impact on whether AoT is used or not.

Hoping for a hotfix either way, as I'd like the speed improvements of beta 22 without the brokenness of AoT :D

**Comment by clydin** [comment]
It should be using the AoT plugin but skipping the code generation step (no ngfactory generation).  So any issues with the plugin's typescript compilation are now present in either mode.

**Comment by hansl** [comment]
Using experimental builds is at your own risks. We're aware of some performance reasons, that's why beta 22 is not released entirely and still tagged experimental.

**Comment by bialad** [comment]
The changelog has no indication that this was an experimental release. 

The issue here does not regard performance, but rather that it prevents usage unless the application supports AOT.

For myself, I'll continue using this release. But I'd rather this issue not be closed, since it needs to be fixed. If it's been fixed, I'll also like to know about it.

**Comment by digimax** [comment]
What is Hans talking about here? If I can find F'ing beta22 with about 10 key strokes, and you're telling me "b22 is not released entirely"? FTW?
Look, thats just stupid. Do you get paid for being so lazy?

**Comment by digimax** [comment]
If you want to play with a wang, play with your own, never mine. comprende vato?

**Comment by digimax** [comment]
I can't even get far enough in the build process, to create the dist/ directory. How did u get that far?

**Comment by digimax** [comment]
Jons-MacBook-Pro:scratchlee jonwilliams$ ng build
ngCompiler.ReflectorHost is not a constructor
TypeError: ngCompiler.ReflectorHost is not a constructor
    at AotPlugin._setupOptions (/Users/jonwilliams/wrk/digimaxCustomer/scratchlee/node_modules/@ngtools/webpack/src/plugin.js:136:31)
    at new AotPlugin (/Users/jonwilliams/wrk/digimaxCustomer/scratchlee/node_modules/@ngtools/webpack/src/plugin.js:37:14)
    at Object.exports.getWebpackNonAotConfigPartial (/Users/jonwilliams/wrk/digimaxCustomer/scratchlee/node_modules/angular-cli/models/webpack-build-typescript.js:20:13)
    at new NgCliWebpackConfig (/Users/jonwilliams/wrk/digimaxCustomer/scratchlee/node_modules/angular-cli/models/webpack-config.js:23:42)
    at Class.run (/Users/jonwilliams/wrk/digimaxCustomer/scratchlee/node_modules/angular-cli/tasks/build-webpack.js:17:22)
    at Class.run (/Users/jonwilliams/wrk/digimaxCustomer/scratchlee/node_modules/angular-cli/commands/build.js:54:26)
    at Class.<anonymous> (/Users/jonwilliams/wrk/digimaxCustomer/scratchlee/node_modules/angular-cli/angular-cli/lib/models/command.js:152:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Jons-MacBook-Pro:scratchlee jonwilliams$

**Comment by digimax** [comment]
Hans, have you even read the CHANGELOG? Do you have any employment opportunities coming up, when Hans get fired?

1.0.0-beta.22 (2016-12-02)

Bug Fixes

@ngtools/webpack: fixed path resolution for entry modules and lazy routes (#3332) (45d5154)
build: don't inline sourcemaps (#3262) (859d905)
build: use custom index value when copying to 404.html during github deploy (#3201) (b1cbf17)
ngtools/webpack: move the generate directory to a separate dir (#3256) (d1037df)
version: bump ast-tools and webpack versions to correct mismatch with published packages (54ef738)
Features

angular: Update Angular2 version to 2.2.3 (#3295) (ed305a2)
build: add --verbose and --progress flags (#2858) (f6f24e7), closes #1836 #2012
build: auto generate vendor chunk (#3117) (bf9c8f1)
new: include routing in spec and inline template when called with --routing (#3252) (53ab4df)
serve: add --hmr flag for HotModuleReplacement support (#3330) (46efa9e)
BREAKING CHANGES

build: ng build/serve now generates vendor.bundle.js by default.

**Comment by digimax** [comment]
I am here to appologize to Hans. Hans, the notion of you being "fired" for any mistake, is a very mistaken notion I realize now. 
Thanks for all your help in delivering what is probably the greatest thing since that last eyedropper of LSD i gargled with.

**Comment by digimax** [comment]
from the docs (https://www.npmjs.com/package/@ngtools/webpack)...
seems like you are going to have to pass an additional parameter (or different parameters)
where you are instantiating and contributing the AotPlugin instance.

import {AotPlugin} from '@ngtools/webpack'
 
exports = { /* ... */
  module: {
    rules: [
      {
        test: /\.ts$/,
        loader: '@ngtools/webpack',
      }
    ]
  },
 
  plugins: [
    new AotPlugin({
      tsConfigPath: 'path/to/tsconfig.json',
      entryModule: 'path/to/app.module#AppModule'
    })
  ]
}

**Comment by digimax** [comment]
I am still quite curious why/how/what? way it is possible that @bialad gets the dist/ directory to be created. Please some one else try, my attempts at building blow up long before the script does the mkdir. ?? how could this be working for him and not for me? Seemingly defying all kinds of logic?

**Comment by digimax** [comment]
why can't we have a handle into the webpack config that cli uses? just put a flag on the command line, and turn off access as a default. this would take no time at all to do. I'm curious to know why it is necessary to exercise so much control over the part that needs to be flexible to do anything non-trivial?

**Comment by JanStureNielsen** [comment]
@digimax -- your behavior is completely inappropriate and highly unprofessional. Please stop this immediately.

**Comment by digimax** [comment]
what? go look at all the code I dumped on YOUR github this morning. go look at all the issues. I don't give a rat's ass what the f you think about anything. pretty no one else does either. hopeless 'tards everywhere. Fetch me my GUN MABEL. queer, and intensley ghey.

**Comment by naomiblack** [comment]
I've deleted comments on this issue that were in violation of Angular's Code of Conduct and banned the user in question.

**Comment by hansl** [comment]
@bialad we were in the process of releasing the Beta.22 when we discovered an issue that needed investigation, so we kept the Beta.22 in the `experimental` tag. The official Beta.22-1 has been released.
