### ISSUE TITLE
Webpack Beta 27?

### ISSUE THREAD

**Issue by jwuliger** [angular/angular-cli#3355]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Any

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
N/A

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
N/A

### The log given by the failure.
> Normally this include a stack trace and some more information.
N/A

### Mention any other details that might be useful.

I just wanted to ask if there were plans to update to the latest Webpack Beta in the near future? Thanks!

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
Sure, but it's unclear what features the latest beta would bring to us. We'll probably skip the beta until RC is available.
