### ISSUE TITLE
rel preload

### ISSUE THREAD

**Issue by johnqiuwan** [angular/angular-cli#3359]
Hi All,

  Does anyone know if angular-cli support "rel preload" on build --prod? 

Thanks

**Comment by hansl** [comment]
We don't do anything special for `rel=preload` and should be supported. What issues do you see with it?

**Comment by rtm** [comment]
Isn't the intent of this question to ask how to get scripts included via the `scripts` property in `.angular-cli.json` to be included in `index.html` with `rel=preload`?

**Comment by JoseRoman** [comment]
@rtm is that possible? I would love to do it that.
