### ISSUE TITLE
ng doc <keyword> uses wrong querystring parameter name

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#3363]
### OS?
Mac OSX Sierra

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: darwin x64

### Repro steps.
`ng doc pipe`

### Mention any other details that might be useful.
This opens https://angular.io/docs/ts/latest/api/#!?apiFilter=pipe but it appears it should open https://angular.io/docs/ts/latest/api/#!?query=pipe

Perhaps the querystring parameter name changed from `apiFilter` to `query`

**Comment by johnpapa** [comment]
cc @Brocco

**Comment by baruchvlz** [comment]
I know this is probably very low priority but I'm not a great developer and I do want to help where I can. With that said, this seems to work fine with apiFilter but once inside the the API Reference page and you change the search input, the url changes to something like so 

https://angular.io/docs/ts/latest/api/#!?apiFilter=component&query=commonmodule

Not the prettiest URL but it works.
