### ISSUE TITLE
Feature Request: Generate a new module without a component

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#3365]
### OS?
Mac OSX Sierra

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: darwin x64

### Option 1
`ng g m foo --no-component`
This would generate the module without the component ts, css, spec, html

### Option 2
`ng g m foo`

Or ideally the default would be to *not* generate a component at all. It can easily be created after by doing `ng g c bar`.

### Why?
1. It is easy to add a component when needed. 

2. It is distracting to generate a module and have 4 extra files created when you do not want them.

3.  Avoids having to delete 4 files with `rm bar.component.*`

### Details ###

use case ... 
https://github.com/johnpapa/event-view/blob/master/src/app/core/core.module.ts

Notice this one … common use case for a module that contains mostly reusable services and only one component. And in this case, the component is not named the same as the module (and shouldnt be).

**Option 2 above is my preference.**

**Comment by baruchvlz** [comment]
I agree that the default behavior of `ng g m <name>` should be to create an empty module file and pass a `component` flag, maybe something like `ng g m foo --component=true`.  I have added this option to my local copy of the cli, `{ name: 'component', type: Boolean, default: false }`, and added a conditional in the `afterInstall` method to create a component if the flag is true.

**Comment by Brocco** [comment]
After having a few conversations about this and thinking about it some more, I think we should have the modules just generate modules with one exception... routing modules. Routing modules can be created at two times: new app creation and module creation.

So what I'm suggesting on your PR, @baruchvlz, is to completely remove the `--component` option and only generate the module.

Thoughts?

**Comment by deebloo** [comment]
I personally think it makes sense. Especially with component generation adding the declaration to the closest module up the tree.

**Comment by baruchvlz** [comment]
@Brocco : Reading what @deebloo  said, it would make sense to have the command only generate the module unless the `--routing` flag is passed.

One questions though, should the `spec` file be generated by default as well just to match the other generate command of components, directives, etc... or are unit tests for modules not necessarily required?

**Comment by Brocco** [comment]
I would leave it as is, it will pick up the default from [here](https://github.com/angular/angular-cli/blob/09f9aa98e109065810f3703b6b65016fbc29c86e/packages/angular-cli/lib/config/schema.json#L181-L183) if it is not specified in angular-cli.json or passed in as an argument.

**Comment by baruchvlz** [comment]
Oh, interesting thanks for pointing that out. I will make the changes to the PR.

**Comment by baruchvlz** [comment]
PR has been updated.

**Comment by Brocco** [comment]
PR merged, closing
