### ISSUE TITLE
Add one line comment to explain the purpose of test.ts

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#3370]
### OS?
Mac OSX Sierra

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: darwin x64

### Details
Add a one line comment to the top of `src/test.ts` to explain its purpose

**Comment by digimax** [comment]
uhm, not sure iof it was a typo, but src/app is not where your test.ts belongs. It should in src/ with the rest of the bootstrapping stuff. just FYI.

**Comment by johnpapa** [comment]
typo fixed

**Comment by Brocco** [comment]
This has been addressed by #4081
