### ISSUE TITLE
More help with providing services

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#3371]
### OS?
Mac OSX Sierra

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: darwin x64

### Repro steps
```
ng new foo
cd foo
ng g s bar
```

### Suggestion
A warning message is shown that says 
`WARNING Service is generated but not provided, it must be provided to be used`

Perhaps we can extend this to say 

`WARNING Service is generated but not provided, it must be provided to be used. Consider providing it in the closest NgModule [put module name here]. Read this link for more information about where to provide services [link to docs]`

### Details
I think *not* providing the service is correct behavior for the CLI because it is not clear cut. But adding suggestions and/or a link to docs may help the user.

**Comment by digimax** [comment]
+1

**Comment by iainplimmer** [comment]
+1 - clambered around why this wasn't working from the CLI turns out it was me moving files around a not receiving correct warnings, but this pointed me right at what I was missing. So no googling would have been required.

**Comment by Brocco** [comment]
This could also be used when generating services: #3806

**Comment by clydin** [comment]
For services, I was thinking maybe a `--provide` option with support for several (tentatively named) keywords:
- `closest-module`  [default]
- `closest-component`
- `root`

**Comment by Brocco** [comment]
For now I'm content with the warning showing when no additional config is provided and allowing the path of a module to be specified. Providing to a component is an approach that can be manually taken after viewing the provided warning.

**Comment by Brocco** [comment]
When generating a service you can now specify where it will be provided with this PR #3811

**Comment by sabbarbutt** [comment]
ng g s services/bar--module=app.module
