### ISSUE TITLE
Don't create typings.d.ts by default

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#3372]
### OS?
Mac OSX Sierra

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: darwin x64

### Repro steps
```
ng new foo
```

Notice the `typings.d.ts` file is created by default. it is empty.

### Suggestion
1. Do not create `typings.d.ts` since it is empty
2. Add a command for creating an empty file ... see [issue here](https://github.com/angular/angular-cli/issues/3373)

**Comment by digimax** [comment]
Perhaps it would be more useful to provide a link to the typings project, specifically the examples section. If you are coming from JS, and trying to get with the TS program, you best be learning how the darn typings command works.

**Comment by johnpapa** [comment]
Adding a link to docs about typings could be helpful, especially since typings have evolved so much over the past year (tsd --> typings --> @types). 

However my request was more about the empty file, which some projects may not need. Once we need the file, we can add it. I prefer the CLI to create the files I need, and leave it to me to create the ones I may need.

**Comment by samuelrobertson** [comment]
I think this is inconsistent behavior and may surprise users. For example, styles.css is empty. Most users need it. The ones that don't can delete it.

**Comment by samuelrobertson** [comment]
Maybe create it empty with a helpful comment or link like John said. Styles.css is created empty with a helpful comment at the top.
