### ISSUE TITLE
Add command to create empty file

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#3373]
### OS?
Mac OSX Sierra

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: darwin x64

### Suggestion
Add "ng g e bar" command that creates an empty file with .ts as default extension

Useful for creating files that there are no templates for.

e.g.

typings.d.ts
rxjs-extensions.ts

This might useful for creating scripts that generate projects, like this 
```
# ng new event-view -p ev -sn
#####################
cd event-view
echo *** turn off spec generation ***
ng set defaults.spec.class false
ng set defaults.spec.component false
ng set defaults.spec.directive false
ng set defaults.spec.module false
ng set defaults.spec.pipe false
ng set defaults.spec.service false
echo *** work on the shared folder ***
ng g m core
rm src/app/core/core.component.*
ng g s core/auth-guard
ng g cl core/can-deactivate-guard
ng g cl core/config
rm src/app/core/config.spec.ts
ng g s core/entity
ng g s core/exception
ng g s core/message
ng g s core/module-import-guard
ng g cl core/preload-strategy
ng g cl core/rxjs-extensions
ng g s core/user-profile
ng g m core/modal
ng g s core/modal
ng g m core/nav
ng g m core/spinner
ng g s core/spinner
ng g m core/toast
ng g s core/toast
ng g cl core/rxjs-operators
...
```

**Comment by digimax** [comment]
uhm, disagree strongly, what's wrong with just using "touch suchandsuch.satan"?

**Comment by johnpapa** [comment]
Does 'touch foo.txt` work in Windows?

**Comment by digimax** [comment]
so now we have to write Powershell scripts for the most profoundly retarded
people in the development community?

**Comment by johnpapa** [comment]
I feel the CLI should work the same (as close as we can) on either OSX or Windows. This way we can create scripts that work in either environment and generate projects. This feature would help that parity.

If the team choose this is not valuable, I'm fine with that. These are suggestions.

But please keep your comments respectful @digimax .

**Comment by digimax** [comment]
Pardon my ego. It doesn't belong here. I'm putting it away right now. FREE ADVICE for people doing ANY KIND OF SOFTWARE DEVELOPMENT WHAT SO EVER: cygwin!

**Comment by digimax** [comment]
thanks for all the negative karma you are creating by posting a picture of an inverted thumb. much appreciated. keep it coming.

**Comment by JanStureNielsen** [comment]
GitHub comments are for technical commentary, @digimax. Please be respectful of everyone's time and efforts by not polluting an issue with non-technical commentary. You can delete your comments above...

**Comment by digimax** [comment]
again, you re hoeless ghey. an no one cares about you. not even you mother
prolly. i'll fork this bitch and then I squish your head. f u.

**Comment by naomiblack** [comment]
I've deleted comments on this issue that were in violation of Angular's Code of Conduct and banned the user in question.

**Comment by filipesilva** [comment]
I see how it can be useful as a simple command for scripts, and as something of a conceptual proto generator. In the future it would be nice to extend the AST codegen to create all generators from a base one and this could be it.

What do you think @Brocco?

**Comment by deebloo** [comment]
@naomiblack thank you :)

**Comment by Brocco** [comment]
I struggle to see the usefulness of this feature. The power of blueprints IMO are to create boilerplate code to get you coding faster. All IDEs/editors provide this functionality, so I struggle to see the added benefit of adding it into the CLI. I'm not against it, just not convinced based upon the script example from @johnpapa above.

Using a script to create an application is something that **very** few people will actually use, especially when that script could do the same thing via `touch bar.ts`.

**Comment by JanStureNielsen** [comment]
@johnpapa -- could you use `echo $null >> somefile.ts` to create your empty file? This *should* work on OSX and Windows as well as Linux, but I can only vouch for Linux... To me, folding this type of work into Angular CLI moves away from the tool's core mission, but I have the luxury of only needing Linux. :-D

**Comment by johnpapa** [comment]
The only use case I have for this is scripting for file creation. If that is not something in scope, I agree that this can be closed @Brocco .

I'm fine using OS commands to do it, if there are no other requests for it.

Feel free to close if you wish

**Comment by Brocco** [comment]
Closing for now, but if there's more feedback about adding this feature we can re-evaluate.
