### ISSUE TITLE
why not show the localhost://4200 in the terminal?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [angular/angular-cli#3376]
**angular-cli 1.0.0.beta-22**
localhost://4200 lost in terminal

![beta-22-error](https://cloud.githubusercontent.com/assets/18028768/20861525/53074140-b9cd-11e6-91e7-e794fd1358c4.PNG)
## latest version
![4200-error](https://cloud.githubusercontent.com/assets/18028768/20861527/5827a1d8-b9cd-11e6-9dba-5a2f77a886fd.PNG)
## old version
![4200-ok](https://cloud.githubusercontent.com/assets/18028768/20861529/5e5b4744-b9cd-11e6-9ae8-1e59d66a9f63.PNG)

**Comment by xgqfrms-GitHub** [comment]
why not make it **auto** open **Chrome** with URL === **http://localhost:4200**/ ?

**just like browsersync does!**

[https://www.browsersync.io/](https://www.browsersync.io/)

**Comment by digimax** [comment]
why not log it to the console yourself?

**Comment by digimax** [comment]
console.log('da url is:... wait for it...', url);

**Comment by xgqfrms-GitHub** [comment]
The goal of tools should be easy using & save time !

**Comment by digimax** [comment]
wrong, that's not the point at all. you'll have to figure it out for yourself.

**Comment by xgqfrms-GitHub** [comment]
**In my views, you are totally wrong!**
[waste of my time!](https://github.com/angular/angular-cli/issues/3376)

**Comment by xgqfrms-GitHub** [comment]
# update CLI 1.0.0.beta22

```
$ npm i -g angular-cli@v1.0.0-beta.22

$ ng new app
# very slowly , just waiting for it install all mpackages!

$ cd app
# open app folder path

## test version (./src)
$ ng server

# why not show the localhost://4200 in the terminal? 
# browser-sync for (./dist)
$ browser-sync start --server

## publish development version (./dist)
$ ng build

## publish production version (./dist)  
## (./angular-cli.json & ./src/environments/environment.prod.ts)
$ ng build --env=prod
```

**Comment by hansl** [comment]
Hi @xgqfrms-GitHub.  I do not see this in my console using the latest beta 22-1:

<img width="1058" alt="screen shot 2016-12-05 at 5 58 33 pm" src="https://cloud.githubusercontent.com/assets/681969/20910114/74235588-bb14-11e6-88b0-892b3a146752.png">


Are you sure you have the latest version? What's your command line? Closing this but please answer with more info if that doesn't answer your issue.

Cheers.

**Comment by hansl** [comment]
(as you can see above, it says `NG Live Development Server is running on http://localhost:4200.`)

**Comment by hansl** [comment]
@xgqfrms-GitHub also please note that `--open` opens the browser as you'd expect.

**Comment by xgqfrms-GitHub** [comment]
no Mac

**Comment by xgqfrms-GitHub** [comment]
[https://docs.c9.io/docs/run-an-application]( https://docs.c9.io/docs/run-an-application)

# how can I change the **http://localhost:4200** or **http://1270.0.1:4200** to **https://0.0.0.0:3000**?

# Available ports on a hosted Cloud9 workspace

If you're developing a server application, please note that you need to listen to **0.0.0.0** ($IP) and **8080** ($PORT). Listening to this port will enable your app to be viewable at **https://<workspacename>-<username>.c9users.io**

You can also bind to ports 8081, and 8082, which can be accessed by **https://<workspacename>-<username>.c9users.io:8081** and **https://<workspacename>-<username>.c9users.io:8082** respectively.

Please note that 8080, 8081, and 8082 are the only available ports on a hosted Cloud9 workspace.

**Comment by hansl** [comment]
Don't use `ng serve` in production. It's exclusively for local development, and its security has never been tested.

**Comment by xgqfrms-GitHub** [comment]
https://community.c9.io/search?q=https%20user%3Abradydowling

https://docs.c9.io/docs/multiple-ports

> If you try to load your site in the preview embedded into the IDE then it won't load there and you can only load over HTTPS. Why can't you open your application in the embedded view using HTTP?


https://community.c9.io/t/why-cant-i-load-my-app-with-http-in-the-embedded-preview/2555/3  
https://community.c9.io/t/why-cant-i-load-my-app-with-http-in-the-embedded-preview/2555

**Comment by hansl** [comment]
If you have an issue related to the CLI, please file a new issue. I'm locking this conversation, since this exact issue has been resolved.
