### ISSUE TITLE
How TO disable Source Code Bundel ?

### ISSUE THREAD

**Issue by Nishanth2** [angular/angular-cli#3377]
> Please provide us with the following information:
> ---------------------------------------------------------------

Is ther Anyway TO disable The source Code ? 

because I tried  
ng build --target=production --environment=prod

To Bundle The app  But Still i can See All the Source Code on Webpack ,

Is there anyway to Disable  Source Code on bundle  ?

Please check the screenshot ,
![build](https://cloud.githubusercontent.com/assets/2277794/20861915/e298f5a2-b9c2-11e6-953b-3b6b6c0cb472.jpg)

**Comment by hansl** [comment]
You don't have to send your source maps. That's from map files.

**Comment by Nishanth2** [comment]
@hansl   Do i need To Disable Anything on angular-cli.json file ?
 I'm   Just newbee to Anuglar2 and even for coding too !

**Comment by grizzm0** [comment]
Those are source maps. You can add --no-sourcemap to remove them from the build. This required beta 22.

**Comment by Nishanth2** [comment]
@grizzm0  Updated to  beta 22  , Added --no-sourcemap  And It's WOrks  Perfectly !

Thanks @grizzm0

**Comment by grizzm0** [comment]
@Nishanth2 No problem. Please close the issue. :)

**Comment by ajeeshc** [comment]
can any one please ex give with the code am trying all possible thinks. still in browser its coming in bundle. 
Details question is [here](https://stackoverflow.com/questions/44507799/how-to-disable-the-default-bundling-in-angular-cli-with-angular-4)
