### ISSUE TITLE
Mod rewrite Traceur 404

### ISSUE THREAD

**Issue by doczoidberg** [angular/angular-cli#338]
My Joomla CMS rewrites urls and now traceur is not found:

`VM987:23 Error: XHR error (404 Beitrag nicht gefunden) loading http://myurl/index.php/de/service-de/traceur(…)`

any ideas?

htaccess.txt:
```
IndexIgnore *

Options +FollowSymlinks
Options -Indexes

RewriteEngine On

RewriteCond %{QUERY_STRING} base64_encode[^(]*\([^)]*\) [OR]
RewriteCond %{QUERY_STRING} (<|%3C)([^s]*s)+cript.*(>|%3E) [NC,OR]
RewriteCond %{QUERY_STRING} GLOBALS(=|\[|\%[0-9A-Z]{0,2}) [OR]
RewriteCond %{QUERY_STRING} _REQUEST(=|\[|\%[0-9A-Z]{0,2})
RewriteRule .* index.php [F]

RewriteCond %{REQUEST_URI} !^/index\.php
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule .* index.php [L]
```

**Comment by hansl** [comment]
Not CLI related. This seems like it's problem for either Joomla or Traceur.

Note that we do not use Traceur. We use the TypeScript offline compiler before we even serve any files.

Closing this.
