### ISSUE TITLE
docs: document folder structure

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular-cli#339]
ember-cli comes with a `public` folder where one could create an `assets` for example, where assets like images can be put into. Those will later be served automatically.

angular-cli however, doesn't create such a folder. In angular-cli it's the `src` folder where we can put assets which will automatically be copied to `dist` and served accordingly.

This (and maybe other differences) should be documented somewhere.

**Comment by cironunes** [comment]
Maybe you can just send a PR w/ the angular logo for example so we can get it whenever we init a new project?

**Comment by filipesilva** [comment]
It is true that certain commands behave differently, or might not even be supported and thus lead to an error state in the managed project. 

I don't think this is such a case though. There is no expectation that `angular-cli` will create the same folders as `ember-cli`. For instance, the test folder also doesn't exist, and many others.

I don't think there should be a 'there are the differences between angular-cli and ember-cli' section. We are not trying to get people that use `ember-cli` to use `angular-cli`.

**Comment by PascalPrecht** [comment]
@filipesilva I think my concern is to have at least **something** until angular-cli has its own proper docs. Currently, the ember-cli docs are the best resources to learn about angular-cli, because angular-cli simply sits on top of it. This of course causes confusion when things are different.

I don't say this should be something forever, but as long as ember-cli docs are the goto resource, it might make sense to have a reference that clarifies what's different in these terms.

Or, even better, document it right away. As in "Here's where you need to put your assets".

**Comment by filipesilva** [comment]
Yeah you're completely right that our docs are lacking. The vendor files question has come up *loads* of times so far, and assets has come up a couple of times only.

We either instruct that directly, or we have it included in the style guide and just follow that.

**Comment by hansl** [comment]
I disagree that we should document differences with `ember-cli`. The same reason we shouldn't document differences with Meteor, for example.

I agree we should have a document for something. We're still waiting on the Houston project to get tight enough that we can consider it canonical.

I'm renaming this accordingly. Let's keep this issue for tracking documentation.

**Comment by PascalPrecht** [comment]
That sounds good to me.

**Comment by hansl** [comment]
Closing this as fixed with the new config.
