### ISSUE TITLE
Build w/o bundling

### ISSUE THREAD

**Issue by ashernevins** [angular/angular-cli#3397]
Are there any plans to support builds that do not concatenate all the files together? Concatenation was very useful in HTTP1/1.1 but keeping files separate has advantages in HTTP2. Are there plans to support this natively?

**Comment by hansl** [comment]
Not yet. We will probably think about it in the future, but for now HTTP2 is as fast as HTTP1 when you're splitting your vendor files (as they might be cached better).

**Comment by hansl** [comment]
Closing this as answered.
