### ISSUE TITLE
node_modules directory outside src.

### ISSUE THREAD

**Issue by Pinank** [angular/angular-cli#3398]
I want to import some of global css files into my index.html file. But as node_modules directory is outside of my src directory i'm not getting the accurate path and hence css is not applying.

I'm using path in following meaner,

**<link href="../node_modules/ng2-toastr/bundles/ng2-toastr.min.css" rel="stylesheet"/>** 

I have tried without **../** also but it's also not working.

Is anything wrong i'm doing?

Here is the app structure.

![screen shot 2016-12-05 at 6 00 09 pm](https://cloud.githubusercontent.com/assets/3683505/20885059/c48ff558-bb14-11e6-910f-50a2d7b77472.png)

**Comment by grizzm0** [comment]
You're not supposed to edit index.html. You can use ../node_modules in your angular-cli.json under script/style keys. In your CSS files you can also use `@import "~vendor/src/foo.css"` for example.

**Comment by hansl** [comment]
@grizzm0 has the answer; use `~` followed by the `node_modules` directory. Closing this as fixed.
