### ISSUE TITLE
fix(generate/component): generated templateUrl and styleUrls paths are broken

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular-cli#340]
Starting off with a fresh new A2 app using

```
$ ng new my-app
```

And creating a component using
```
$ ng g component test
```

Scaffolds the component fine in `src/app/test` however, `templateUrl` and `styleUrls` look like this:

```
templateUrl: 'app///test/test.html',
styleUrls: ['app///test/test.css']
```

angular-cli version: 0.0.26
node version: 4.3.2

**Comment by Brocco** [comment]
The dynamic path feature has broken this, I will have a PR pushed up soon to fix this

**Comment by PascalPrecht** [comment]
Awesome @Brocco thank you!

**Comment by PascalPrecht** [comment]
This issue is still present with angular-cli version 0.0.29

/cc @hansl @Brocco

**Comment by jkuri** [comment]
Closing as it is resolved now on master.
