### ISSUE TITLE
Error with ng github-pages:deploy

### ISSUE THREAD

**Issue by tschaka1904** [angular/angular-cli#3405]
### OS?
Mac OSX Yosemite

### Versions.
node: 6.2.2
os: darwin x64

### Repro steps.
I'm working on a project, using the CLI, and updated it to the recent version. `ng-serve` works. `ng-build` works as well. Executing `ng github-pages:deploy` throws an error :( 

### The log given by the failure.
stdout maxBuffer exceeded
Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:265:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:542:20)

### Repo.
https://github.com/tschaka1904/complex-portal-view

**Comment by usmanchaudhri** [comment]
did you resolve this issue ? I am facing a similar issue.

**Exception:**
stdout maxBuffer exceeded.
Error: stdout maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:244:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)

**Comment by chaiyuxin** [comment]
Same for me, just started a new project, trying to deploy but got this error

> stdout maxBuffer exceeded
> Error: stdout maxBuffer exceeded
>     at Socket.<anonymous> (child_process.js:266:14)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
>     at Socket.Readable.push (_stream_readable.js:110:10)
>     at Pipe.onread (net.js:523:20)

**Comment by tschaka1904** [comment]
I was including an asset, containing a node module, which I wanted to include for temp reasons. Removing it solved my issue.

**Comment by donvadicastro** [comment]
Where was the problem? Could you share more information.
Thanks.

**Comment by tschaka1904** [comment]
I was adding a npm-module to the assets folder. I need to do that for some reason at that time. It worked perfectly on my local machine, but running `ng github-pages:deploy` broke it. I'm not sure why, but I think it was just to big and it couldn't deal with that. Anyway, removing the module out the the assets folder did the trick.
