### ISSUE TITLE
Anguar2 routerLink returning inaccurate URL

### ISSUE THREAD

**Issue by keymanjacob** [angular/angular-cli#3407]
I am trying to implement angular2 routers and by using the URL pattern like '/detail/:index'  to pass something like ':detail/1234' . but it's getting "someDomain/detail/%3AitemIndex;itemIndex=123" which means "/detail/:itemIndex;itemIndex=123". How to fix this and get the expected result which is "/detail/123" OR "/detail/itemIndex=123"  and get rid of that ":itemIndex;" and replace it with slash (Please ignore my typos)

"app.routes.ts"
```
export const rootRouterConfig: Routes = [
  { path: '', redirectTo: 'SomeHomeComponent', pathMatch: 'full' },
  { path: 'home', component: SomeHomeComponent },
  { path: 'detail/:itemIndex', component: SomeDetailComponent }];

```
"list.component.html"

```
<a *ngFor="let item of items; let i = index" 
[routerLink]="['/detail/:itemIndex', { itemIndex: i }]"> 
{ item.name }
</a>

```
"SomeDetail.Component.ts"

```
import { ActivatedRoute } from '@angular/router';
export class SomeDetailComponent {
  private itemIndex:string;

  constructor(private  route: ActivatedRoute){

  }
  ngOnInit () {

    this.route.params.subscribe(params => { this.itemIndex = params['itemIndex'];
    });
}
}

```

**Comment by grizzm0** [comment]
This is a place to post issues with how angular-cli works. For angular2 questions please ut stackoverflow or similar.

**Comment by hansl** [comment]
What @grizzm0 said, this is not a cli-specific issue, but a router help request. Gitter and/or stackoverflow would be best. Thanks!
