### ISSUE TITLE
Relative Path CSS not working

### ISSUE THREAD

**Issue by ezforms** [angular/angular-cli#3409]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> MAC OSX El Capitan

### Versions.
> angular-cli: 1.0.0-beta.15
node: 6.3.1
os: darwin x64

### Repro steps.
> Project was created from cli

### Mention any other details that might be useful.
I am trying to reference a relative path css file located in my modules folder. If I get the path wrong it complains, but if its right it compiles without a problem, but the css styles are not loaded at run time. In my example I am using scss, but I have also tried with .css. The project is setup for scss.

```
@Component({
    selector: 'mymodulecomponent',
    template: '<view></view>',
    styleUrls: ['./mystyle.component.scss']
})

```
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
Could you try to update to the latest beta 22-1? I don't see that issue on my computer, and it might have been a bug in Beta.15 that has since been fixed.

**Comment by ezforms** [comment]
sorry, I ran ng --version on the wrong project, I am on  "version": "1.0.0-beta.21". Are there any dependencies on component or style creation using the cli? I imported my components from a systemjs project that I was sick of using systemjs.
