### ISSUE TITLE
CSS file included in angular-cli.json results in empty <styles> tag

### ISSUE THREAD

**Issue by alcfeoh** [angular/angular-cli#3417]
### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64

### Repro steps.
The following CSS dependency (https://github.com/HubSpot/offline/blob/master/themes/offline-language-english.css) when listed in angular-cli.json as a CSS dependency, generates an empty styles tag in my index.html when served - so it's not really included:

"styles": [
        "styles.css",
        "../node_modules/offline-js/themes/offline-language-english.css"
      ]

### The log given by the failure.
None

### Mention any other details that might be useful.
It's the only CSS file that behaves like this. Could it be characters in it or something?

**Comment by hansl** [comment]
Did you mean `../node_modules/`? Or just simply `node_modules`?

**Comment by hansl** [comment]
Note that, as an error, we should probably check that the files exist, so I'll fix that.

**Comment by alcfeoh** [comment]
My path is alright, other CSS files in `node_modules ` are included. My actual styles arrays looks like this and only that specific file is not included:

"styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "../node_modules/angular2-toaster/lib/toaster.css",
        "../node_modules/offline-js/themes/offline-language-english.css",
        "../node_modules/offline-js/themes/offline-theme-default.css"
      ],

**Comment by hansl** [comment]
oh I see. That's strange. Let me investigate.

**Comment by alcfeoh** [comment]
Thanks ;-)

**Comment by hansl** [comment]
Could you double check that the content of that file isn't in `styles.bundle.js`? When I include it locally I see it there. It's a really small style file so it might get included.

**Comment by alcfeoh** [comment]
I can see the contents of my CSS file in `styles.bundle.js`. The result is not working though. As a temporary workaround I had to include the CSS stylesheet manually in my index.html.

**Comment by hansl** [comment]
When I serve the page I see the style tag being full. Sorry, without a project I can't really see what's wrong. Closing as non reproducible.

![screen shot 2016-12-05 at 5 22 40 pm](https://cloud.githubusercontent.com/assets/681969/20909287/83d5a6fc-bb0f-11e6-99c6-296a5997be02.png)

**Comment by alcfeoh** [comment]
I can provide you with a package.json file if needed. There's still a bug somewhere.

**Comment by hansl** [comment]
If you can provide me with a project that repros it I'm willing to take a look.

**Comment by mbakker96** [comment]
I've the same problem when I import the flexboxgrid.css

**Comment by alcfeoh** [comment]
@hansl  Unfortunately my client's project is not an open-source one and I can't share it.

**Comment by mbakker96** [comment]
https://github.com/mbakker96/overview-application here is my project

**Comment by hansl** [comment]
@mbakker96 just cloning that, `npm install` then `ng serve`, I get the CSS properly inserted in the page:

![screen shot 2016-12-06 at 4 59 24 pm](https://cloud.githubusercontent.com/assets/681969/20950586/6e4713c2-bbd5-11e6-8cf3-e2154729138a.png)


There's an empty tag (from a component), but it's not flexbox. That project works fine.

**Comment by mbakker96** [comment]
But why is the style then not applied to the links (left) midden (middle) and rechts (right). I use flexboxgrid to create columns but it is not applied to the html style.
