### ISSUE TITLE
Correctly resolve WebPack loaders within npm linked modules

### ISSUE THREAD

**Issue by garkbit** [angular/angular-cli#3419]
### OS?
OSX Sierra

### Versions.
angular-cli: 1.0.0-beta.18
node: 6.9.1
os: darwin x64

### Repro steps.
Install NPM linked package that uses a WebPack loader. Loader cannot be resolved.

### The log given by the failure.
`Module not found: Error: Can't resolve 'style' in '...'`

### Mention any other details that might be useful.
Merge #2291 was incomplete, in that it does not fully address the issue raised in #1875. It fixes _module_ resolution, but not _loader_ resolution. The following needs to be added to the object returned from `getWebpackCommonConfig()` in `webpack-build-common.ts` in order to match current module resolution strategy:
```
resolveLoader: {
  modules: [path.resolve(projectRoot, 'node_modules')]
}
```

Also, I would submit a pull request, but the the corporate overhead of getting a CLA in place are prohibitive.

**Comment by hansl** [comment]
Yeah I dunno  `__dirname` was merged, it was obviously incorrect. We'll fix.

**Comment by hansl** [comment]
As for the CLA, it's a one time cost that really takes 5 minutes to complete. If you have legal complications I can understand, though.

**Comment by garkbit** [comment]
@hansl, thank you sir.

You're right, submitting the CLA is easy enough. It's the internal process of getting an approval for it on my end that's a pain. Again, thanks for making the change. :)
