### ISSUE TITLE
Feature request: Mechanism for extending and overriding CLI-generated Webpack config

### ISSUE THREAD

**Issue by garkbit** [angular/angular-cli#3420]
There's a pretty consistent trend of issues requiring tweaks to Webpack config. While many of these kinds of things are within the realm of sensible defaults, there are two presenting issues with the current opaque approach:

- Non-standard, or otherwise complex projects quickly run into Webpack config issues
- Issues that could be addressed with simple Webpack config changes are now subject to the issue > discussion > pull request > probably more discussion > acceptance > release cycle.

Please consider a mechanism permitting override and extension of the generated Webpack config object. Perhaps a `webpack` field in `angular-cli.json` or similar.

**Comment by hansl** [comment]
The CLI tool right now is not fitted to be used for complex projects or non standard ones, and we're okay. If your project is complex, you should probably control the pipeline more. You can still use the CLI without `ng build` or `ng serve`, to generate your files and tests.

**Comment by JonET** [comment]
lol so what you're saying is that angular-cli is worthless for non trivial applications and my time would be better spent with something else?
