### ISSUE TITLE
Process freezes multiple times until the user presses enter

### ISSUE THREAD

**Issue by timothy** [angular/angular-cli#3433]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> 
angular-cli: 1.0.0-beta.22-1
node: 6.8.1
os: win32 x64

### Repro steps.
> 
`npm install -g angular-cli`
`ng new my-app`
`ng serve`

### The log given by the failure.
> N/A

### Mention any other details that might be useful.
During `ng serve` the process freezes multiple times until the user presses enter. The `ng serve` eventually will complete and start serving successfully but not without the user babysitting it.

Not sure if this helps but I am using a Dell Precision | M 4700 -- so relatively old hardware...
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
There's nothing that should/could be waiting for Enter.

Just a theory; I notice you're on Windows. Windows has the unfortunate bad UX that if you select something using the mouse in the command prompt, it will pause the current running process. Pressing Enter would unselect it so the process would resume. Could that be what's happening? Try to avoid using the mouse after running `ng serve`, see if that helps.

**Comment by kiddy2910** [comment]
I was stuck at `ng serve` and nothing run event press Enter after I upgrade to `1.0.0-beta.22-1`. Before that 5 minutes, everything is ok

**Comment by timothy** [comment]
I tried it a few more times making sure not to select anything and found that it still happens but not consistently... It may be my environment. I will post back if I find the root cause.

**Comment by kiddy2910** [comment]
I downgraded to version `1.0.0-beta.21` and it's working

**Comment by e-schultz** [comment]
ng test just hangs on me - no output, cant ctrl-c to quit out of it, need to kill the angular-cli process

**Comment by noelklein** [comment]
I'm running windows 10 and am having the same issue as @timothy . Often times I have to switch to my console window and hit enter as it just gets stuck sometimes. When I hit enter it just resumes.

**Comment by panicst8** [comment]
Same issue just occurred Windows 7 -- beta.32.3 --- was just froze at 92 forever and i just hit enter and poof finished .... probably something weird with command prompt as npm install does this same behavior.

**Comment by timothy** [comment]
I upgraded and now this problem is no longer happening on my system. I am going to close the issue.
