### ISSUE TITLE
Implement legacyWatch parameter for ng serve

### ISSUE THREAD

**Issue by brunogoossens** [angular/angular-cli#3434]
When using the command "ng serve" on a mounted fs (or in my case a vagrant shared folder), file changes aren't noticed.

Nodemon already solved this problem by adding a legacyWatch parameter:
https://github.com/remy/nodemon#application-isnt-restarting

**Comment by hansl** [comment]
We already have a `poll` option that we pass to webpack dev server. Try using `ng set defaults.poll 100` (100 would be the interval, see [here](https://webpack.github.io/docs/webpack-dev-middleware.html#watchoptions-poll)), and report back here if that doesn't help.

Closing this in the meantime. Cheers!

**Comment by brunogoossens** [comment]
thx! It worked! You made my day!

$ ng set defaults.poll 100 && ng serve;
