### ISSUE TITLE
Code Coverage Requirement does not fail.

### ISSUE THREAD

**Issue by JT-Bruch** [angular/angular-cli#3435]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10.

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: win32 x64

### Repro steps.
> Create repro and add code.
> Add 
```coverageReporter: {
      check: {
        global: {
          statements: 99,
          branches: 99,
          functions: 99,
          lines: 99
        },
        each: {
          statements: 99,
          branches: 99,
          functions: 99,
          lines: 99
        }
      },
      watermarks: {
        statements: [ 85, 95 ],
        functions: [ 85, 95 ],
        branches: [ 85, 95 ],
        lines: [ 85, 95 ]
      }
    }
```
to karma.conf.js
> Expect failure with no unit tests for code.

### The log given by the failure.
> N/A

### Mention any other details that might be useful.

> Ideally, if the code coverage is less than what is defined in the coverageReporter, the ng test task will error out.
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Is this the behaviour when you configure test coverage via karma outside of the CLI?

**Comment by JT-Bruch** [comment]
Yes

**Comment by schechter** [comment]
👍

**Comment by filipesilva** [comment]
Closing as outdated. If this still happens, please let me know.
