### ISSUE TITLE
Add test filter option

### ISSUE THREAD

**Issue by mattdistefano** [angular/angular-cli#3436]
Would like to see `ng test` support executing a subset of tests via something like karma's --grep or (perhaps better?) by passing a glob pattern. We use the latter in our pure webpack build today and it's pretty useful when you're working on a single component (or service, directive, etc) and don't need/want  the entire suite to build/execute.

**Comment by antonybudianto** [comment]
for testing specific block you can append `f` (focused) to the test syntax

```
fdescribe(...)

fit(...)
```

ref https://jasmine.github.io/2.4/focused_specs.html

**Comment by mattdistefano** [comment]
@antonybudianto Yes and no. 

I'd prefer to filter without having to edit the test source.
Ideally, we'd also shave a couple seconds off the build time by only including the tree for the specified tests, vs. building everything and only executing some tests.

**Comment by filipesilva** [comment]
This issue came up before https://github.com/angular/angular-cli/issues/3603, but since that one has more discussion I'll keep it open instead.

**Comment by aitchkhan** [comment]
I am looking for something like the same, any updates on this?

**Comment by EugeneSnihovsky** [comment]
@aitchkhan it's quite a late, but maybe it can be useful for some developers. See [this](https://github.com/angular/angular-cli/issues/3603#issuecomment-311293256)
