### ISSUE TITLE
How to autorun "ng lint" whenever a file is changed?

### ISSUE THREAD

**Issue by thardy-pd** [angular/angular-cli#3437]
I can't seem to figure out how to cause ng serve to autorun "ng lint" whenever a js file is changed.  Leaving it out of the watch functionality is basically advocating not linting at all, and I refuse to believe the angular-cli team would think so poorly of linting js source code.  Please tell me I'm just missing a simple configuration somewhere!

The ability to hook whatever I want to execute when a file of a configured type is changed would be even better.  I can wait on a flexible solution, but the lack of linting is downright painful for a javascript development organization.

**Comment by hansl** [comment]
Multiple editors understand tslint configurations and have plugins/extensions to perform linting as you code. Or you could watch the file system (see https://www.npmjs.com/package/node-watch) yourself and run linting when it changes.

We will not implement a watch mode for lint.

**Comment by thardy-pd** [comment]
The problem is that angular-cli is positioned squarely in the "watch utility" category.  It REPLACES grunt and gulp.  I've never had two separate watch utilities running on the same repo at one time.  That sounds kinda nasty to me.  I like to have one watch utility handling everything, and I think most people do.

If you're going to be THE watch utility for a repo, you need to at least provide the basics, like hooks for people to call out to whatever custom functionality they want. "Run another watch utility" is not a very good answer in my opinion.
