### ISSUE TITLE
How to exclude certain folder from bundling

### ISSUE THREAD

**Issue by estradamarkie** [angular/angular-cli#3438]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.21
node: 6.9.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

When doing `ng build` does this take the whatever is in the src folder and bundle it? if so I have put extra folder in the src folder which I want to exclude during the build so it won't bundle up but still copies it to the /dist after the build.

Say my folder is called 'excludethisfolder', I want this to be excluded but still want it to be in the dist folder.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
It does not compile everything, only what's imported from your code. Also, it seems you want an assets folder which we support.

**Comment by estradamarkie** [comment]
I actually meant to include certain folder, but I found it where to add them now.
