### ISSUE TITLE
After upgrading to version 1.0.0-beta.22-1, serving the app fails with devserver/socket.js error

### ISSUE THREAD

**Issue by david-bulte** [angular/angular-cli#3440]
### OS?
Windows 7

### Versions.
angular-cli: 1.0.0-beta.22-1
node: 6.5.0
os: win32 x64

### Repro steps.
I did all the update steps (install angular-cli global, perfom "ng init" etc... etc...
Start serving the application with "ng serve". After the application is built successfully, I get the webpack-dev-server/socket.js exception...

### The log given by the failure.

ERROR in (webpack)-dev-server/client/socket.js
Module not found: Error: Can't resolve 'sockjs-client' in 'c:\system9\sourcesWEB\MYNEXUZ\MyNexuz\node_modules\webpack-de
v-server\client'
 @ (webpack)-dev-server/client/socket.js 1:13-37
 @ (webpack)-dev-server/client?http://localhost:4200/
 @ multi main

**Comment by hansl** [comment]
I've never seen that. Could you try to `rm -rf` your `node_modules` folder and reinstall, see if that helps?  If not, would you mind providing repro steps?

I'm closing this unless you can provide a reproducible case.

**Comment by david-bulte** [comment]
removing the node_modules folder worked. Thanks @hansl

**Comment by steady-daddy** [comment]
Encountered similar issue. Removing and installing node_modules worked.
