### ISSUE TITLE
Do no override changed settings on ng init

### ISSUE THREAD

**Issue by tzachov** [angular/angular-cli#3448]
### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.22-1
node: 6.9.1
os: win32 x64

### Repro steps.
1. Add a package dependency to package.json or change a setting in tslist.json
2. Run ng init

If you choose to take the updated settings, the package you added will be removed and the setting you changed will be reverted.

We need a way to merge updates.

**Comment by gelliott181** [comment]
It's available and has been for a long time. When you perform `ng init` you're asked if you'd like to overwrite a number of files and presented four choices: `Yndh` which correspond to `Yes`, `No`, `Diff`, and `Help`. Choose diff and you get a listing of the differences between the current file and the one that would overwrite it so you can skip the file and merge the changes yourself.

**Comment by tzachov** [comment]
The difference check is per section (i.e "dependencies") so you either choose override and add all your packages again or choose not to override and add the updated CLI packages yourself.

I think there should be at least an option to make this check per-key (or more complex solution - find only changed properties)

This will make updating CLI version easier and faster.

**Comment by hansl** [comment]
`ng init` needs a lot of user interaction and is a delicate process. We are aware of that issue, but there's nothing that will be done before 1.0 final, except better documentation.
