### ISSUE TITLE
UNMET PEER DEPENDENCY tslint@3.15.1

### ISSUE THREAD

**Issue by nickiewooster** [angular/angular-cli#3453]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX El Capitan

### Versions.
> angular-cli: 1.0.0-beta.22-1
> node: 6.0.0
> os: darwin x64

### Repro steps.
> Cant finish `npm install` after `ng init` replacing the package.json

### The log given by the failure.
.
.
│ ├── through@2.3.8 
│ ├─┬ ts-loader@0.8.2 
│ │ ├─┬ enhanced-resolve@0.9.1 
│ │ │ ├── graceful-fs@4.1.11 
│ │ │ ├── memory-fs@0.2.0 
│ │ │ └── tapable@0.1.10 
│ │ └── object-assign@2.1.1 
│ ├─┬ UNMET PEER DEPENDENCY tslint@3.15.1
│ │ └── underscore.string@3.3.4 
│ ├─┬ tslint-loader@2.1.5 
│ │ └── strip-json-comments@1.0.4 
│ ├─┬ url-loader@0.5.7 
│ │ └── mime@1.2.11 
│ ├── uuid@3.0.1 
.
.

### Package.json
{
  "name": "*",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/router": "3.2.3",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.2.3",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.22-1",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3",
    "webdriver-manager": "10.2.5"
  }
}

### Mention any other details that might be useful.
`npm ls angular-cli codelyzer`
customer-portal-web@0.0.0 /Users/Juanta/Documents/CustomerPortalWeb
`-- UNMET PEER DEPENDENCY tslint@3.15.1

npm ERR! peer dep missing: tslint@~4.0.0, required by codelyzer@2.0.0-beta.1
npm ERR! code 1

It looks like there is a miss match between tslint version of angular-cli and codelyzer 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by blacksonic** [comment]
```tslint-loader``` now needs 4+ version of ```tslint```

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/3462
