### ISSUE TITLE
Helpful hints not so helpful :(

### ISSUE THREAD

**Issue by phillip-haydon** [angular/angular-cli#3454]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
$ ng --version
angular-cli: 1.0.0-beta.22-1
node: 7.2.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Attempted to run a build that worked prior to updating to latest version but got a message saying an option doesn't exist.

```
$ ng build --prod --aot --no-sourcemaps
The option '--sourcemaps' is not registered with the build command. Run `ng build --help` for a list of supported options.
```

Attempted to run the recommended command:

```
$ ng build --help
undefined
```

Help only exists on the root level doing `ng help`

### The log given by the failure.
> Normally this include a stack trace and some more information.
n/a

### Mention any other details that might be useful.

Just need to update the messages, I would send a PR but I have no idea where to start. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by grizzm0** [comment]
It's --no-sourcemap. Singular, not plural. About the help command, a PR to fix the docs has already been created.

**Comment by phillip-haydon** [comment]
Thanks @grizzm0, yeah i got it working. The `ng help` showed me the right command. Just thought the message needed to be updated for other users :)
