### ISSUE TITLE
How to Remove default favicon bundle with beta.22-1

### ISSUE THREAD

**Issue by Meet91** [angular/angular-cli#3455]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> os: win32 x64

### Versions.
>angular-cli: 1.0.0-beta.22-1
node: 7.1.0

### Repro steps.
>
1) Remove the line `<link rel="icon" type="image/x-icon" href="favicon.ico">` from index.html
2) ng build
3) ng serve
4) browse through http://localhost:4200/ ,still shows the default angular favicon.

Also tried the above steps after clearing the browser cache and still the same issue.

Below browser are used to reproduced the issue:

1) Chrome(Version 54.0.2840.99 m)
2) IE(Version 11.0.98600.18499)

> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
You need to do three things to remove the icon from the build:
- remove `<link rel="icon" type="image/x-icon" href="favicon.ico">` from `index.html`
- remove `"favicon.ico"` from `apps[0].assets` in `angular-cli.json`
- delete `src/favicon.ico`

This way you eliminate all traces of the default favicon. If you still see it in your browser, it is likely being cached somewhere and should go away in time.

**Comment by shehzadshafi42** [comment]
thanks @filipesilva its working but after 

1) Restart the app , If still not change
2) Restart the system (I dont know it is better way or not but it works for me)
3) Clear browsing data and cache.

If still not working then follow this i am sure it works.

To refresh your site's favicon you can force browsers to download a new version using the link tag and a query string on your filename. This is especially helpful in production environments to make sure your users get the update.
<link rel="icon" href="http://www.yoursite.com/favicon.ico?v=2" />

**Comment by vikasmis** [comment]
clear cache ...after deleting the favicon icon..it will work

**Comment by vikasmis** [comment]
![image](https://user-images.githubusercontent.com/46219790/61132186-63f66b00-a4aa-11e9-970c-415e316aef7b.png)
