### ISSUE TITLE
Can't build project wit typescript 2.1.4

### ISSUE THREAD

**Issue by alexbyk** [angular/angular-cli#3456]
### VERSIONS?
angular-cli: 1.0.0-beta.22-1
node: 7.2.0
os: linux x64

### Repro steps.
> Create new project, update typescript to 2.1.4

### The log given by the failure.
```
 10% building modules 2/2 modules 0 active(node:6139) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: AppModule is not an NgModule
(node:6139) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Hongbo-Miao** [comment]
Same here, stuck at this place:
> ** NG Live Development Server is running on http://localhost:4200. **
>  20% building modules 84/84 modules 0 active

**Comment by hansl** [comment]
We don't support 2.1 officially, unfortunately.

@Hongbo-Miao that's a problem with webpack dev server, and unrelated to this issue. It blocks because it's reporting an error. Try `ng build`.

**Comment by Hongbo-Miao** [comment]
@hansl thanks, I found out that my issue is related with "angular-cli". It starts from after updating from angular-cli 1.0.0-beta.21 to 1.0.0-beta.22, also happens to 1.0.0-beta.22-1

**Comment by chadbr** [comment]
@hansl in the pipeline? Any ETA? Can't wait for some async/await

**Comment by hansl** [comment]
Once Angular itself support TypeScript 2.1

**Comment by Hongbo-Miao** [comment]
@hansl thanks!

**Comment by castamir** [comment]
I'm already using typescript v2.1 with angular-cli but the latest beta-22 is broken for me, beta-21 works fine. Async and await made my code much more readable.

**Comment by ReneVallecillo** [comment]
TS 2.0.10 stuck at 20%

**Comment by mrin9** [comment]
To use typescript 2.1 
 - include "awesome-typescript-loader": `"^3.0.0-beta.9"` in package.json
 - rollback angular-cli version to `"1.0.0-beta.21"` 
 - update tsconfig.json with 
   ` "typingOptions": { "enableAutoDiscovery": false, "include": [], "exclude": [] }`
