### ISSUE TITLE
Getting the npm ERR! 404 : no such package available : @angular-cli/ast-tools

### ISSUE THREAD

**Issue by tomer78** [angular/angular-cli#3460]
When i run the npm install -g angular-cli command I  get this error0
It seems like the @angular-cli/ast-tools does not exist or renamed.
(or i'm missing something...)
any idea?
Thanks
Tomer

windows 10

**Comment by hansl** [comment]
Which npm version? Which node version? [@angular-cli/ast-tools](https://www.npmjs.com/package/@angular-cli/ast-tools) does exist. Closing this without more info.
