### ISSUE TITLE
Error: ERROR in multi main

### ISSUE THREAD

**Issue by a-sitnikov** [angular/angular-cli#3468]
trying "ng serve" and get this error

ERROR in multi main
Module not found: Error: Can't resolve 'E:\' in 'E:\!Data\js\projects\!ang-cli\node_modules\angular-cli\models'
 @ multi main

ERROR in multi styles
Module not found: Error: Can't resolve 'E:\' in 'E:\!Data\js\projects\!ang-cli\node_modules\angular-cli\models'
 @ multi styles
and so on

node : 6.9.1 (also tried on 7)
npm: 3.0.8
angular-cli: angular-cli@1.0.0-beta.22-1
win 10 x64
Tried on fresh install node and npm.
Then 
npm install -g angular-cli
then
ng new !ang-cli

**Comment by a-sitnikov** [comment]
Perhaps the problem is in ! in project name

**Comment by hansl** [comment]
I'm actually going to make sure that only valid project names are created, to avoid this.

**Comment by hidegh** [comment]
Awesome. What other valid path characters can't be used in the path?

**Comment by daniyalnagori** [comment]
what is the best solution of this?
