### ISSUE TITLE
Feature Request: Add the ability to add filter to ng test so that single spec files can be tested

### ISSUE THREAD

**Issue by PG2000** [angular/angular-cli#3469]
### OS?
> Ubutnu 16.04

### Mention any other details that might be useful.

Very often it would be useful to test a single .spec file or to provide a wildcard
I think a line like this would be very nice:

ng test --filter=some-filter*

**Comment by mattdistefano** [comment]
Actually requested this very thing a couple days ago in #3436. Should probably consolidate there.

**Comment by PG2000** [comment]
Ah perfect...

**Comment by hansl** [comment]
Dupe of #3436
