### ISSUE TITLE
Exported variable 'X' has or is using name errors with AOT off

### ISSUE THREAD

**Issue by the-destro** [angular/angular-cli#3470]
### OS?
Sierra

### Versions.
```
imac:js fridder$ ng version
angular-cli: local (v1.0.0-beta.22-1, branch: tsconfig_issue)
node: 7.2.0
os: darwin x64
```
(exists in non local version as well)

### Repro steps.
It seems to be when I import * from a submodule that does not export all of its members.
I ran a build with `ng build --aot=false` and `ng build` and that produced an error. `ng build --aot` no error.

### The log given by the failure.
```
imac:angular_qq fridder$ ng build --aot=false
Hash: d69badf52a00bd8b9ea5
Time: 11255ms
chunk    {0} main.bundle.js, main.bundle.map (main) 63.4 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 144 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 3.56 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/app/reducers/index.ts
Module build failed: Error: /Users/fridder/code/angular_qq/src/app/reducers/index.ts (12,14): Exported variable 'reducers' has or is using name 'Action' from external module "/Users/fridder/code/angular_qq/node_modules/@ngrx/store/src/dispatcher" but cannot be named.)
/Users/fridder/code/angular_qq/src/app/reducers/index.ts (12,14): Exported variable 'reducers' has or is using name 'InitilizeCarAction' from external module "/Users/fridder/code/angular_qq/src/app/actions/car" but cannot be named.)
/Users/fridder/code/angular_qq/src/app/reducers/index.ts (12,14): Exported variable 'reducers' has or is using name 'SelectMakeAction' from external module "/Users/fridder/code/angular_qq/src/app/actions/car" but cannot be named.)
/Users/fridder/code/angular_qq/src/app/reducers/index.ts (12,14): Exported variable 'reducers' has or is using name 'SelectModelAction' from external module "/Users/fridder/code/angular_qq/src/app/actions/car" but cannot be named.)
/Users/fridder/code/angular_qq/src/app/reducers/index.ts (12,14): Exported variable 'reducers' has or is using name 'SelectStyleAction' from external module "/Users/fridder/code/angular_qq/src/app/actions/car" but cannot be named.)
/Users/fridder/code/angular_qq/src/app/reducers/index.ts (12,14): Exported variable 'reducers' has or is using name 'SelectValuesFromFormAction' from external module "/Users/fridder/code/angular_qq/src/app/actions/car" but cannot be named.)
/Users/fridder/code/angular_qq/src/app/reducers/index.ts (12,14): Exported variable 'reducers' has or is using name 'SelectYearAction' from external module "/Users/fridder/code/angular_qq/src/app/actions/car" but cannot be named.)
/Users/fridder/code/angular_qq/src/app/reducers/index.ts (12,14): Exported variable 'reducers' has or is using name 'SetUserDataAction' from external module "/Users/fridder/code/angular_qq/src/app/actions/user" but cannot be named.)
    at _checkDiagnostics (/Users/fridder/code/angular-cli/packages/@ngtools/webpack/src/loader.ts:115:15)
    at /Users/fridder/code/angular-cli/packages/@ngtools/webpack/src/loader.ts:140:17
 @ ./src/app/app.module.ts 18:0-38
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
```

### Mention any other details that might be useful.
googling the error message suggested that it is related to `declaration: true` being in the tsconfig or somehow set during compilation. I have it set to false in my code base and verified that it is looking at the correct tsconfig all the way down to the config models and in the build task.

**Comment by mattdistefano** [comment]
I had this issue as well and IIRC the problem was that I had properties/methods with an implicit return type that I wasn't actually importing. So for example even just a `return this.$http.get()` would cause a problem if I didn't also import `Observable` in the same file.

**Comment by the-destro** [comment]
What is annoying though is the different behavior on the different aot flags and also how this changed from one beta to this one. I suspect, though can not verify, that it is related to the skipCodeGeneration bit.

**Comment by hansl** [comment]
Before we were using Awesome-TypeScript-Loader, now we use the AoTPlugin for both AoT and non-AoT mode. It's actually faster than A-T-L, we just do the same thing but skip AoT code generation. That's the context for skipCodeGeneration.

To go back to your error, this is actually a TypeScript error and your code is missing something: https://github.com/Microsoft/TypeScript/issues/5711

**Comment by the-destro** [comment]
I get that @hansl however why does this only occur during skipCodeGeneration: true? Especially if I don't have declaration set as is mentioned in that bug?

**Comment by veliancreate** [comment]
Considering angular-cli sets `"declaration": false,` in tsconfig, I would expect these types of Typescript errors to go away?
