### ISSUE TITLE
Template reference variables not recognized by the linter

### ISSUE THREAD

**Issue by kirjai** [angular/angular-cli#3472]
### OS
> Mac OSX (El Capitan)

### Versions.
```
angular-cli: 1.0.0-beta.22-1
node: 4.4.2
os: darwin x64
```

### Repro steps.
Linter doesn't seem to understand template reference variables. 
For example, for a given block of HTML:
```
<input type="text" #myInput>
<p>{{ myInput.value }}</p>
```
With the default `tslint` config, I get the following error when running `ng lint`:
`The property "myInput" that you're trying to access does not exist in the class declaration.`

Other than that, HTML linting is a great addition to the linter, thank you!

**Comment by hansl** [comment]
This is a bug with codelyzer itself, please file it on their repo: https://github.com/mgechev/codelyzer
