### ISSUE TITLE
ng init root folder

### ISSUE THREAD

**Issue by philconibere** [angular/angular-cli#3475]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.22-1
node: 6.8.1
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
running ng init within any sub folder of the user's home folder creates the files and structure at the root instead of the current folder

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
You have a `node_modules` created somewhere. That's a known issue if you `npm install` something in your home directory for example. Try to see if you have one in your home folder or your root.
