### ISSUE TITLE
generate from sample apps

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#348]
I would really like if as I create a new application I have two main options:  one would create the basic generated app `ng new myapp`, the second would use a sample application as the base for my generated app. `ng new myapp from bootstrap` would create a generated application with examples using bootstrap4.  `ng new myapp from todo` would be another good one to have. 

@johnpapa any thoughts on this?

**Comment by filipesilva** [comment]
I think the plan is to support such functionality via addons, with their own set of blueprints.

**Comment by zackarychapple** [comment]
Wonder how yoeman does it?

**Comment by johnpapa** [comment]
I like this idea as it helps keep the MVP concept in place for the base app that the CLI generates. Don't give them anything more than the user absolutely needs. Anything extra should come form custom templates.

cc // @wardbell

**Comment by Brocco** [comment]
While I agree that having some sample app templates would be nice, I don't think they should actually be part of the CLI, at least not for now. I would suggest having some repos setup that people can clone/copy/download rather than have them produced from via the CLI.

**Comment by johnpapa** [comment]
This is not an MVP ... to me, get the core MVP working first. simplest app. everything else should be optional

**Comment by zackarychapple** [comment]
I agree @Brocco that the templates should not be part of the CLI but the ability to use them should be. @johnpapa definitely not MVP :)

**Comment by hansl** [comment]
Support for custom blueprints is on the roadmap, closing this.
