### ISSUE TITLE
UI composition with angular-cli?

### ISSUE THREAD

**Issue by atticae** [angular/angular-cli#3483]
Is it somehow possible to work on and deploy modules independently and dynamically load them at runtime? We are building a microservice architecture with an angular2 frontend and would like to split the work on the frontend to multiple independent teams.

I am looking at lazy loading right now, but the way it looks to me the whole code still has to be built together in one `ng build`, correct? 

I need a way to create separate bundles and load them from a URL at application start. Is this possible with angular cli?

**Comment by hansl** [comment]
If you use `System.import(...)` this should work, but whether or not Angular itself supports this case is a question for the core repo.

**Comment by hansl** [comment]
The bundle will be split on `System.import()` is what I meant.
