### ISSUE TITLE
'ng' commands continue to be very slow to START executiing

### ISSUE THREAD

**Issue by momoadeli** [angular/angular-cli#3484]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX  Sierra

### Versions.
> 1.0.0-beta.19-3 (any ng 'X' command is extremely slow to START executing

### Repro steps.
> Type ng serve. It will take around 1 minute to START execution.  Most ng 'xxx' are the same.  (eg: ng --version)

### Mention any other details that might be useful.

I've mentioned this before in #2791 (for ng --version).  Continues to be an issue for every command.  Not sure if this is a bug or something quirky with my iMac. I don't experience it for any other NPM package. The was happening in previous version of cli AND Yosemite as well.
NOTE: I've un/re installed multiple times.

**Comment by hansl** [comment]
There is a LOT of requires done when you start the command. We are working on this.

Although https://github.com/angular/angular-cli/issues/3199 is tracking install time, I also reduced significantly the amount work (from 5 seconds to 3 when developing locally, where we also compile TS). I'm closing this as this is vague, but I added a point to that issue to drop bootstrap time as well.

**Comment by momoadeli** [comment]
@hansl , I want to be clear this is not about execution times of various commands.  As indicated, this is about **starting** execution. Is that what you're referring to by 'bootstrap time'?  Thanks!

**Comment by hansl** [comment]
Yes.

**Comment by jdhenckel** [comment]
Why not add a **terminal mode** to cli, such as "ng term" which just opens a prompt into which you can type several commands?  this would "solve" the startup time issue with very little effort.
