### ISSUE TITLE
ng build --target=production --base-href ./ works in Chrome, not IE or FF

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#3485]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```ng build --target=production --base-href ./```
works  in Chrome, blows up in FF or IE
see: http://secure.digitalsignage.com/boiler/

I did include
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.0/es6-shim.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
```

**Expected behavior**
that it works or updated docs if more steps to be taken for IE / FF

regards

Sean

**Comment by beeman** [comment]
Does it work when you set `--base-href` to `/` ?

`ng build --target=production --base-href /`

**Comment by born2net** [comment]
let me try...

**Comment by born2net** [comment]
no luck

**Comment by born2net** [comment]
closing as I believe internal issues

**Comment by born2net** [comment]
issue was that I missed a '''this'''
chrome was fine with it. ie and ff not.
fixed!

**Comment by vishuhanda001** [comment]
may be you can try
"ng build --target=production --environment=prod --output-path cordova/www/ --base-href ."

**Comment by ravivit9** [comment]
Hi,

I have the same error. Anyone fixed this issue?

Thanks.

**Comment by YABO-AlarmTILT** [comment]
same error, No suggestion ?
