### ISSUE TITLE
Webstorm: Error:Initialization error (typescript). this.typingsInstaller.attach is not a function

### ISSUE THREAD

**Issue by jongunter** [angular/angular-cli#3486]
### OS?
Mac OS El Capitan
Windows 8

### Versions
For my mac: 
angular-cli: 1.0.0-beta.22-1
node: 5.3.0
os: darwin x64

### Repro steps.
I initialized a new ng cli project with WebStorm (using the WS UI) Everything works as intended, but I occasionally get this error popping up in Webstorm. Can't seem to replicate it easily and it seems random, but usually occurs when I create a new project.
```
Error:Initialization error (typescript). this.typingsInstaller.attach is not a function
```

### The log given by the failure.
Error:Initialization error (typescript). this.typingsInstaller.attach is not a function

**Comment by hansl** [comment]
I don't think this is CLI related, maybe check with IntelliJ?
