### ISSUE TITLE
setting spec default for modules to false still generates *component.spec.ts

### ISSUE THREAD

**Issue by aavelyn** [angular/angular-cli#3487]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?

macOS El Capitain

### Versions.
"1.0.0-beta.19-3

    "defaults": {
       ...
        "spec": {
            "class": false,
            "component": false,
            "directive": false,
            "module": false,
            "pipe": false,
            "service": false
        }
    }

Setting module to false still generates spec.ts files for the component.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
This was fixed by https://github.com/angular/angular-cli/pull/3389.
