### ISSUE TITLE
Expose url-loader limit parameter in config

### ISSUE THREAD

**Issue by mattdistefano** [angular/angular-cli#3489]
Would be nice to have this parameter exposed in the config so we can tweak as needed or disable.

**Comment by hansl** [comment]
The goal of the config is to stay high level. We don't want to expose any implementation or webpack-specific option.

**Comment by mattdistefano** [comment]
I get that, but you're already basically forcing users into what should be an opt-in optimization. So there should be a way to disable and/or configure. 

TBH I think you guys are getting too hung up on the webpack configuration. Just because this happens to be implemented via a webpack loader now doesn't mean it's a webpack-specific feature. Base64ing images into CSS is a pretty common optimization and supported by a whole bunch of other tools. Ditto the html minification issue I submitted earlier - these are _general_ feature that can be supported with or without webpack.
