### ISSUE TITLE
what options are available for production build?

### ISSUE THREAD

**Issue by aggarwalankush** [angular/angular-cli#3490]
For production build, `--prod` flag is available. In github issues, I see mentions of other flags such as `--aot`, `--no-sourcemap` which can be useful in production. Do we have a list of all flags and their description that we can use for faster execution in production?

**Comment by grizzm0** [comment]
`ng help`

```
ng build <options...>
  Builds your app and places it into the output path (dist/ by default).
  aliases: b
  --target (String) (Default: development)
    aliases: -t <value>, -dev (--target=development), -prod (--target=production)
  --environment (String) (Default: )
    aliases: -e <value>
  --output-path (Path) (Default: null)
    aliases: -o <value>
  --watch (Boolean) (Default: false)
    aliases: -w
  --watcher (String)
  --suppress-sizes (Boolean) (Default: false)
  --base-href (String) (Default: null)
    aliases: -bh <value>
  --aot (Boolean) (Default: false)
  --sourcemap (Boolean) (Default: true)
    aliases: -sm
```

**Comment by Cito** [comment]
By the way, it would be nice to have separate help commands like `ng help build`, so you don't need to scroll through the complete help output to find the relevant command.

**Comment by baruchvlz** [comment]
@Cito That's being fixed with #3442 I believe.

**Comment by noelmace** [comment]
Yep #3442 add ``ng help build``, and ``ng help`` (3490#issuecomment-265972136) is the right answer for now. This is not an issue, but a support request, and it was answered.

**Comment by Cito** [comment]
@baruchvlz @noelmace Cool - feels like writing to a wish fairy :)

**Comment by filipesilva** [comment]
Closed as answered.
