### ISSUE TITLE
Cannot read property 'replace' of undefined   at Object.normalizeSlashes

### ISSUE THREAD

**Issue by ialex90** [angular/angular-cli#3491]
Hi there,

I'm facing a problem on VSTS with my angular-cli app, could you have a look in here to see more details?
http://stackoverflow.com/questions/41057361/cannot-read-property-replace-of-undefined-at-object-normalizeslashes-angular-c?noredirect=1#comment69323042_41057361

Just to let you know that the command which triggers that is `ng build` there is not flag for aot or another params. Same project same build it was working previous week but not anymore.

Version used:     1.0.0-beta.18

**Comment by ialex90** [comment]
Writing the error, I just realized that I was using the caret symbol "^" and there must be a new version of angular cli which is making this error comes up, So I changed it in this way:
"angular-cli": "^1.0.0-beta.18" -> "angular-cli": "1.0.0-beta.18"

And now, I am using that version and I dont have the problem anymore (if I don't update)

Well, it's not the best solution but it's a valid workaround, at least for me, close the ticket if you consider is done (even do, I wish to know what's the cause of that problem with a newer version)

**Comment by filipesilva** [comment]
Since it seems you have been using and upgrading your app for a while, this might mostly be a dependency thing. Try creating a new project with the latest CLI and moving your files there. `tsconfig.json` changed recently to use libs, so that might be it.
