### ISSUE TITLE
Way to import sass mixins  in the final sass file

### ISSUE THREAD

**Issue by kyashan** [angular/angular-cli#3492]
Hi there. I got some issues when trying to import a sass mixins file into the final sass file (the one which get compiled). When I try to access that mixins in other sass components partials, I got the following error
```
./src/app/components/main-page/_main-page.component.scss
Module build failed: 
@include center('x');
No mixin named center
```

All sass files except the one that get compiled at the end start with "_"
This is the final **styles.scss**
```
@import "app/stylesheets/normalize/import-now";
@import "app/stylesheets/mixins"; // This is the mixins file
@import "app/stylesheets/partials"; // This is where I import all components partials
```

This is the file where I get the error, **_main-page.component.scss**
```
// @import '../../stylesheets/mixins'; 

#main-page {
    position: absolute;
    top: 0px;
    left: 300px;
    bottom: 0px;
    width: 600px;
    background-color: yellow;
    @include center('x');
}
```
The only way to make it working is to uncomment the first line in component partial and doing the same in any other file where I use the mixins.
Is it the normal way to proceed?

The app was entirely built with this version on angular-cli
angular-cli: 1.0.0-beta.16
node: 7.2.0
os: darwin x64

**Comment by clydin** [comment]
The component's scss styles are essentially isolated.  An mixins need to be imported per component.

**Comment by filipesilva** [comment]
It is as @clydin says 💃 .
