### ISSUE TITLE
Problems adding angular-cli

### ISSUE THREAD

**Issue by Steve2106** [angular/angular-cli#3493]
Hi There,
Angular-cli seems to install but I cannot do an ng --version I get the error:
'ng' is not recognized as an internal or external command,
Any ideas? Windows 7 64 bit PC

  +-- semver@5.3.0
  +-- silent-error@1.0.1
  +-- source-map-loader@0.1.5
  | +-- async@0.9.2
  | `-- source-map@0.1.43
  +-- sourcemap-istanbul-instrumenter-loader@0.2.0
  +-- string-replace-loader@1.0.5
  | `-- lodash@3.10.1
  +-- style-loader@0.13.1
  +-- stylus@0.54.5
  | +-- css-parse@1.7.0
  | +-- glob@7.0.6
  | +-- sax@0.5.8
  | `-- source-map@0.1.43
  +-- stylus-loader@2.4.0
  | `-- when@3.6.4
  +-- temp@0.8.3
  | `-- rimraf@2.2.8
  +-- through@2.3.8
  +-- ts-loader@0.8.2
  | +-- arrify@1.0.1
  | +-- colors@1.1.2
  | +-- enhanced-resolve@0.9.1
  | | +-- graceful-fs@4.1.11
  | | +-- memory-fs@0.2.0
  | | `-- tapable@0.1.10
  | `-- object-assign@2.1.1
  +-- tslint@3.15.1
  | +-- findup-sync@0.3.0
  | | `-- glob@5.0.15
  | `-- underscore.string@3.3.4
  |   `-- util-deprecate@1.0.2
  +-- tslint-loader@2.1.5
  | `-- strip-json-comments@1.0.4
  +-- typescript@2.0.10
  +-- url-loader@0.5.7
  | `-- mime@1.2.11
  +-- uuid@3.0.1
  +-- walk-sync@0.2.7
  | +-- ensure-posix-path@1.0.2
  | `-- matcher-collection@1.0.4
  +-- webpack@2.1.0-beta.25
  | +-- acorn@3.3.0
  | +-- ajv@4.9.2
  | | `-- co@4.6.0
  | +-- async@1.5.2
  | +-- clone@1.0.2
  | +-- interpret@1.0.1
  | +-- loader-runner@2.2.0
  | +-- node-libs-browser@1.1.1
  | | +-- assert@1.4.1
  | | +-- browserify-zlib@0.1.4
  | | | `-- pako@0.2.9
  | | +-- buffer@4.9.1
  | | | +-- base64-js@1.2.0
  | | | `-- ieee754@1.1.8
  | | +-- console-browserify@1.1.0
  | | | `-- date-now@0.1.4
  | | +-- constants-browserify@1.0.0
  | | +-- crypto-browserify@3.11.0
  | | | +-- browserify-cipher@1.0.0
  | | | | +-- browserify-aes@1.0.6
  | | | | | `-- buffer-xor@1.0.3
  | | | | +-- browserify-des@1.0.0
  | | | | | `-- des.js@1.0.0
  | | | | `-- evp_bytestokey@1.0.0
  | | | +-- browserify-sign@4.0.0
  | | | | +-- bn.js@4.11.6
  | | | | +-- browserify-rsa@4.0.1
  | | | | +-- elliptic@6.3.2
  | | | | | +-- brorand@1.0.6
  | | | | | `-- hash.js@1.0.3
  | | | | `-- parse-asn1@5.0.0
  | | | |   `-- asn1.js@4.9.0
  | | | +-- create-ecdh@4.0.0
  | | | +-- create-hash@1.1.2
  | | | | +-- cipher-base@1.0.3
  | | | | +-- ripemd160@1.0.1
  | | | | `-- sha.js@2.4.8
  | | | +-- create-hmac@1.1.4
  | | | +-- diffie-hellman@5.0.2
  | | | | `-- miller-rabin@4.0.0
  | | | +-- pbkdf2@3.0.9
  | | | +-- public-encrypt@4.0.0
  | | | `-- randombytes@2.0.3
  | | +-- domain-browser@1.1.7
  | | +-- events@1.1.1
  | | +-- https-browserify@0.0.1
  | | +-- os-browserify@0.2.1
  | | +-- path-browserify@0.0.0
  | | +-- process@0.11.9
  | | +-- punycode@1.4.1
  | | +-- querystring-es3@0.2.1
  | | +-- stream-browserify@2.0.1
  | | +-- stream-http@2.5.0
  | | | +-- builtin-status-codes@2.0.0
  | | | `-- to-arraybuffer@1.0.1
  | | +-- string_decoder@0.10.31
  | | +-- timers-browserify@1.4.2
  | | +-- tty-browserify@0.0.0
  | | +-- url@0.11.0
  | | | +-- punycode@1.3.2
  | | | `-- querystring@0.2.0
  | | +-- util@0.10.3
  | | | `-- inherits@2.0.1
  | | `-- vm-browserify@0.0.4
  | |   `-- indexof@0.0.1
  | +-- source-map@0.5.6
  | +-- supports-color@3.1.2
  | | `-- has-flag@1.0.0
  | +-- uglify-js@2.7.5
  | | +-- source-map@0.5.6
  | | +-- uglify-to-browserify@1.0.2
  | | `-- yargs@3.10.0
  | |   +-- camelcase@1.2.1
  | |   +-- cliui@2.1.0
  | |   | +-- center-align@0.1.3
  | |   | | +-- align-text@0.1.4
  | |   | | | +-- longest@1.0.1
  | |   | | | `-- repeat-string@1.6.1
  | |   | | `-- lazy-cache@1.0.4
  | |   | `-- right-align@0.1.3
  | |   `-- window-size@0.1.0
  | +-- watchpack@1.1.0
  | | +-- async@2.0.0-rc.4
  | | `-- graceful-fs@4.1.11
  | `-- yargs@4.8.1
  |   +-- cliui@3.2.0
  |   | `-- wrap-ansi@2.1.0
  |   +-- lodash.assign@4.2.0
  |   +-- os-locale@1.4.0
  |   | `-- lcid@1.0.0
  |   |   `-- invert-kv@1.0.0
  |   +-- require-directory@2.1.1
  |   +-- require-main-filename@1.0.1
  |   +-- which-module@1.0.0
  |   +-- window-size@0.2.0
  |   +-- y18n@3.2.1
  |   `-- yargs-parser@2.4.1
  |     +-- camelcase@3.0.0
  |     `-- lodash.assign@4.2.0
  +-- webpack-dev-server@2.1.0-beta.9
  | +-- chokidar@1.6.1
  | | +-- anymatch@1.3.0
  | | +-- async-each@1.0.1
  | | +-- glob-parent@2.0.0
  | | +-- is-binary-path@1.0.1
  | | | `-- binary-extensions@1.8.0
  | | +-- is-glob@2.0.1
  | | | `-- is-extglob@1.0.0
  | | `-- readdirp@2.1.0
  | |   +-- graceful-fs@4.1.11
  | |   `-- set-immediate-shim@1.0.1
  | +-- compression@1.6.2
  | | +-- accepts@1.3.3
  | | | `-- negotiator@0.6.1
  | | +-- bytes@2.3.0
  | | +-- compressible@2.0.9
  | | +-- debug@2.2.0
  | | | `-- ms@0.7.1
  | | +-- on-headers@1.0.1
  | | `-- vary@1.1.0
  | +-- connect-history-api-fallback@1.3.0
  | +-- express@4.14.0
  | | +-- array-flatten@1.1.1
  | | +-- content-disposition@0.5.1
  | | +-- content-type@1.0.2
  | | +-- cookie@0.3.1
  | | +-- cookie-signature@1.0.6
  | | +-- debug@2.2.0
  | | +-- depd@1.1.0
  | | +-- encodeurl@1.0.1
  | | +-- escape-html@1.0.3
  | | +-- etag@1.7.0
  | | +-- finalhandler@0.5.0
  | | | +-- debug@2.2.0
  | | | +-- statuses@1.3.1
  | | | `-- unpipe@1.0.0
  | | +-- fresh@0.3.0
  | | +-- merge-descriptors@1.0.1
  | | +-- methods@1.1.2
  | | +-- on-finished@2.3.0
  | | | `-- ee-first@1.1.1
  | | +-- parseurl@1.3.1
  | | +-- path-to-regexp@0.1.7
  | | +-- proxy-addr@1.1.2
  | | | +-- forwarded@0.1.0
  | | | `-- ipaddr.js@1.1.1
  | | +-- qs@6.2.0
  | | +-- send@0.14.1
  | | | +-- debug@2.2.0
  | | | `-- destroy@1.0.4
  | | +-- serve-static@1.11.1
  | | +-- type-is@1.6.14
  | | | `-- media-typer@0.3.0
  | | `-- utils-merge@1.0.0
  | +-- http-proxy-middleware@0.17.3
  | | +-- http-proxy@1.16.2
  | | | +-- eventemitter3@1.2.0
  | | | `-- requires-port@1.0.0
  | | +-- is-glob@3.1.0
  | | | `-- is-extglob@2.1.0
  | | `-- micromatch@2.3.11
  | |   +-- arr-diff@2.0.0
  | |   | `-- arr-flatten@1.0.1
  | |   +-- array-unique@0.2.1
  | |   +-- braces@1.8.5
  | |   | +-- expand-range@1.8.2
  | |   | | `-- fill-range@2.2.3
  | |   | |   +-- is-number@2.1.0
  | |   | |   +-- isobject@2.1.0
  | |   | |   `-- randomatic@1.1.6
  | |   | +-- preserve@0.2.0
  | |   | `-- repeat-element@1.1.2
  | |   +-- expand-brackets@0.1.5
  | |   | `-- is-posix-bracket@0.1.1
  | |   +-- extglob@0.3.2
  | |   +-- filename-regex@2.0.0
  | |   +-- kind-of@3.1.0
  | |   +-- normalize-path@2.0.1
  | |   +-- object.omit@2.0.1
  | |   | +-- for-own@0.1.4
  | |   | | `-- for-in@0.1.6
  | |   | `-- is-extendable@0.1.1
  | |   +-- parse-glob@3.0.4
  | |   | +-- glob-base@0.3.0
  | |   | `-- is-dotfile@1.0.2
  | |   `-- regex-cache@0.4.3
  | |     +-- is-equal-shallow@0.1.3
  | |     `-- is-primitive@2.0.0
  | +-- opn@4.0.2
  | +-- serve-index@1.8.0
  | | +-- batch@0.5.3
  | | +-- debug@2.2.0
  | | `-- http-errors@1.5.1
  | |   `-- setprototypeof@1.0.2
  | +-- sockjs@0.3.18
  | | +-- faye-websocket@0.10.0
  | | | `-- websocket-driver@0.6.5
  | | |   `-- websocket-extensions@0.1.1
  | | `-- uuid@2.0.3
  | +-- sockjs-client@1.1.1
  | | +-- eventsource@0.1.6
  | | | `-- original@1.0.0
  | | |   `-- url-parse@1.0.5
  | | +-- faye-websocket@0.11.0
  | | +-- json3@3.3.2
  | | `-- url-parse@1.1.7
  | |   `-- querystringify@0.0.4
  | +-- spdy@3.4.4
  | | +-- handle-thing@1.2.5
  | | +-- http-deceiver@1.2.7
  | | +-- select-hose@2.0.0
  | | `-- spdy-transport@2.0.18
  | |   +-- hpack.js@2.1.6
  | |   +-- obuf@1.1.1
  | |   `-- wbuf@1.7.2
  | |     `-- minimalistic-assert@1.0.0
  | +-- supports-color@3.1.2
  | `-- yargs@4.8.1
  |   +-- cliui@3.2.0
  |   +-- lodash.assign@4.2.0
  |   `-- window-size@0.2.0
  +-- webpack-md5-hash@0.0.5
  | `-- md5@2.2.1
  |   +-- charenc@0.0.1
  |   +-- crypt@0.0.1
  |   `-- is-buffer@1.1.4
  +-- webpack-merge@0.14.1
  | +-- lodash.find@3.2.1
  | | +-- lodash._basecallback@3.3.1
  | | | +-- lodash._baseisequal@3.0.7
  | | | `-- lodash.pairs@3.0.1
  | | +-- lodash._baseeach@3.0.4
  | | +-- lodash._basefind@3.0.0
  | | `-- lodash._basefindindex@3.6.0
  | +-- lodash.isequal@4.4.0
  | `-- lodash.isplainobject@3.2.0
  |   `-- lodash._basefor@3.0.3
  +-- yam@0.0.18
  | `-- fs-extra@0.16.5
  |   `-- graceful-fs@3.0.11
  |     `-- natives@1.1.0
  `-- zone.js@0.6.26

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\an
gular-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})

C:\>ng
'ng' is not recognized as an internal or external command,
operable program or batch file.

**Comment by clydin** [comment]
Did you do a global install?

**Comment by Diegotxz** [comment]
I have the same problem, when I try to add angular-cli

when I use npm install -g angular-cli show me the following 
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

and finally

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\browser-sync\node_modules\chokidar\node_mo
dules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})


any solution?

**Comment by clydin** [comment]
@Diegotxz those aren't errors. You should be good if that's all it said.
My guess is this is more of a windows/nodejs issue than a CLI issue.

**Comment by aarndt** [comment]
I am experiencing the same issue. 

Repro steps:

1. npm install -g angular-cli
2. Upon completion, type 'ng version' and hit Enter
3. Receive error: 'ng' is not recognized as an internal or external command,
operable program or batch file.

**Comment by hansl** [comment]
What version of NPM are you using? The CLI requires NPM 3. You have to install NPM 3 manually if you're using Node 4.

This is not an issue with the CLI itself, closing this as such.

**Comment by tyroneje** [comment]
I have using npm 4.0.3 and node 7.2.1. 
i have received the error: {file path} is not recognized as an internal or external command,
operable program or batch file.

**Comment by bofcarbon1** [comment]
I am getting this error....

Cannot find module 'ajv'
npm 3.10.3
node 6.5.0

:(

**Comment by born2net** [comment]
did u ever figure out Cannot find module 'ajv' ?

**Comment by bofcarbon1** [comment]
I did get past the 'ajv' error.
Unfortunately I couldn't tell you exactly why.
Possibly had to do with using the right version of node when installing angular2-cli.
Now I'm on Cloud 9 which defaulted to 4.6.1 or something.
First thing is to get node to 6.5.0 at least
Then make sure you are using that version so 

$ nvm use 6.5.0

Should display a message verifying the version you are on.

You may have to uninstall and reinstall angular2-cli
Verify that the install completed.
Then change to the directory that your project is at
$ cd myProject

The start up the server by entering

$ ng serve

Hopefully the 'ajv' or similar message disappear.
I saw the web worker tools chunk messages
then finally I saw this message...

$ webpack: bundle is now VALID.

Now go to your URL and verify 'App Works!'

**Comment by born2net** [comment]
I see, got it tx!
