### ISSUE TITLE
app that uses isDevMode() api, cuases an error when built or served in prod mode

### ISSUE THREAD

**Issue by forforeach** [angular/angular-cli#3495]
### OS?
> Windows 10

### Versions.
> angular-cli: 1.0.0-beta.22-1
node: 6.5.0
os: win32 x64

### Repro steps.
> 

1. Create an app using CLI 
2. Add reference to [isDevMode](https://angular.io/docs/ts/latest/api/core/index/isDevMode-function.html)
3. Use isDevMode()
4. Serve or build an app with --prod flag

```typescript
if (isDevMode()) {
  console.log('devmode');
}
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    HttpModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

### The log given by the failure.
> Uncaught Error: Cannot enable prod mode after platform setup.
@ application_ref.js:43367 
@ main.ts:9r 
@ bootstrap 521fad9…:52690 
@ main.cd1f6e0….bundle.js:222r 
@ bootstrap 521fad9…:52window.webpackJsonp 
@ bootstrap 521fad9…:23(anonymous function) 
@ main.cd1f6e0….bundle.js:1

> ---------------------------------------------------------------

**Comment by noelmace** [comment]
I didn't investigated that enough for now, but I could reproduce it, and it seems to be an angular/angular issues. I'll search any existing issue about that and investigate more as soon as I could.

**Comment by noelmace** [comment]
Found it : https://github.com/angular/angular/issues/10643
I seems to have nothing to do with angular-cli, but tell me if I'm wrong.

**Comment by clydin** [comment]
This is expected behavior.  You can't use isDevMode before enableProdMode.

**Comment by martinmcwhorter** [comment]
Shouldn't you check the environment provider rather than call isDevMode()?

**Comment by filipesilva** [comment]
As @clydin said, you can't use `isDevMove` before `enableProdMode`. It might seem that it isn't happening in that order, but remember that you're calling the `AppModule` import *before* the code in `main.ts` runs.

There might be something to angular/angular#12200, but this will probably be an API change that we'll implement when available.
