### ISSUE TITLE
ngtools/webpack can't resolve template / styles using only filename

### ISSUE THREAD

**Issue by dimavt** [angular/angular-cli#3497]
Angular cli fails with error `Module not found` when resolving `templateUrl:['client.component.html']` 

### OS?
> Linux (ubuntu). Mac OSX (Yosemite? El Capitan?)

### Versions.
```
angular-cli: 1.0.0-beta.22-1
node: 6.2.0
os: darwin x64

"@ngtools/webpack@^1.0.0":
  version "1.1.9"
```

### Repro steps.
app created with angular-cli and followed [style guide](https://angular.io/docs/ts/latest/guide/style-guide.html#!#05-04) syntax:
```js
@Component({
  selector: 'toh-heroes',
  templateUrl: 'heroes.component.html',
  styleUrls:  ['heroes.component.css']
})
```

### The log given by the failure.
```
ERROR in ./src/app/+client/client.component.ts
Module not found: Error: Can't resolve 'client.component.html' in '...../src/app/+client'
 @ ./src/app/+client/client.component.ts 120:22-54
 @ ./src/app/+client/client.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
```

### Mention any other details that might be useful.
Works fine in beta.21.  
workaround: add `./` in templateUrl and styleUrls
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dimavt** [comment]
maybe this could be fixed with adding `./` in 
https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/loader.ts#L113

**Comment by bthharper** [comment]
I get this too, but since upgrading to beta 22-1.

**Comment by noelmace** [comment]
Adding ./ Is the way to deal with webpack projects, instead of using module.id, according to the angular.io documentation https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html#!#webpack. I don't see any reason to fix that, but I may be wrong.

**Comment by hansl** [comment]
We use TypeScript resolution for templates now, which means `some-file.html` will be resolved relative to the base path (your `src/` directory). Think of it as importing the file; `import './some-file.html'` is what you'd want.

Please note we always generate the right templates.
