### ISSUE TITLE
ngCompiler.ReflectorHost is not a constructor

### ISSUE THREAD

**Issue by ritox842** [angular/angular-cli#3501]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.22-1

### The log given by the failure.
ngCompiler.ReflectorHost is not a constructor
TypeError: ngCompiler.ReflectorHost is not a constructor

### Mention any other details that might be useful.
Its a fresh project , Only created the project and update all npm packages to the latest.
When i ng-serve I get the ngCompiler.ReflectorHost  error
> 

- [ ] ---------------------------------------------------------------

> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
Angular 2.3.0 is not supported. Revert back to 2.2.4 or earlier.

**Comment by ritox842** [comment]
Hey.
When I downgrade to 2.2.4 I dont get the ngCompiler.ReflectorHost error, but still the project don't run... It stack on 20%.
I dont know if it relevent but I get this error just before the 20%:

>  10% building modules 2/2 modules 0 active(node:4308) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: AppModule is not an NgModule
> (node:4308) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
