### ISSUE TITLE
Feature: provide redbox functionality in dev mode.

### ISSUE THREAD

**Issue by robwormald** [angular/angular-cli#3502]
Problem: I've sat in on a number of in-person training / teaching sessions / gitter - newer developers (whether to JS or Angular) don't have the immediate reflex to go check the console when their app fails to boot. This manifests with questions like "why does it just say Loading...?" or "it just doesn't work"

React Native (and React, recently) implement a feature called the "Red Box of Death" - if the app throws an exception, it displays a massive red box containing the error - in effect, it surfaces the errors out of the console. See https://www.npmjs.com/package/redbox-react for example.

We should implement a similar feature to be available in devmode - this is obviously not something you want to ship to production, but as a default-on option for new users it would solve a lot of confusion.

(perhaps this should be implemented in Zones or CLI? discuss?)

**Comment by martinmcwhorter** [comment]
Maybe this should be implemented outside the cli.  The cli and seeds can then include this functionality at will.

Maybe a WebPack plugin to only include it in dev, rather than including it in prod and disabling it with the environment config. 

Would a try/catch around the bootstrap method catch all exceptions thrown?

**Comment by antonybudianto** [comment]
I tried by creating custom ErrorHandler and did sweetalert the error, but not all exceptions can be caught. Simple case like when `element is not known` didn't get caught by ErrorHandler

The same one when using try/catch block, cannot get all exceptions.

**Comment by cexbrayat** [comment]
@filipesilva could be closed now that #4513 has been merged ?

**Comment by filipesilva** [comment]
@cexbrayat right-o, I forgot that!
