### ISSUE TITLE
"We currently do not support a name of "test"."

### ISSUE THREAD

**Issue by ehyko** [angular/angular-cli#3505]
### OS?
> Windows 7 

### Versions.
angular-cli: 1.0.0-beta.22-1
node: 6.9.2
os: win32 x64

### Repro steps.
ng new test

### The log given by the failure.
We currently do not support a name of "test".

### ERROR while installing angular-cli

npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
<PATH>\AppData\Roaming\npm\ng -> <PATH>\AppData\Roaming\npm\node_modules\angular-cli\bin\ng

> execSync@1.0.2 install <PATH>\AppData\Roaming\npm\node_modules\angular-cli\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
# { Error: spawn node-gyp ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ] }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.

> node-zopfli@2.0.2 install <PATH>\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

[node-zopfli] Success: "<PATH>\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node" is installed via remote

> node-sass@3.13.1 install <PATH>\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-48_binding.node
Download complete  ] - :
Binary saved to <PATH>\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass\vendor\win32-x64-48\binding.node
Caching binary to <PATH>\AppData\Roaming\npm-cache\node-sass\3.13.1\win32-x64-48_binding.node

> node-sass@3.13.1 postinstall <PATH>\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass
> node scripts/build.js

Binary found at <PATH>\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass\vendor\win32-x64-48\binding.node
Testing binary
Binary is fine
> ---------------------------------------------------------------

**Comment by filipesilva** [comment]
As the error message indicates, we don't support that name for creating a new app. Please choose another name.

**Comment by AndreySchmidt** [comment]
For testing this you can use somthing like "ng new angular-test"

**Comment by Chris2011** [comment]
Any name should be possible. What is the reason to not support name "test"?

**Comment by goraxe** [comment]
just hit this myself, wondering what the rational behind requiring a hyphen in the name?  Looks like this is a re-occurring issue/question #912 #2645

I did a little more testing to see what was a valid naming scheme.  

my-app, my.app, myApp, MyApp all work my_app did not, nor did my app,  my|app, my+app, my#app, my:app (note all were tested with appropriate shell quoting)  .

my#App got a bit more of a verbose error message (223 chars vs the 44 chars in response to ng new app)

My personal opinion here is the rules for the name convention should be included in the output of ng help new, it saves everyone's time in looking at github issues and head scratching on 'why does it not work?'  I'm big fan of 'rule of least surprise'  here not being able to create an app called 'test' is actually pretty surprising.

It would also be honest to doc the reason behind the rule (not required, just ya know nice) ie 'we parse the name and use it as part of a namespace and we do our best to figure out your naming schema', 'we think it looks pretty', or 'not really sure its just the way we have always done it'.
