### ISSUE TITLE
Cannot install angular-cli

### ISSUE THREAD

**Issue by Stormcore** [angular/angular-cli#351]
> Select one of the following:
>
> I am filing a bug.
>
> > In this case you need the following information:
>
> ---------------------------------------------------------------
1. Mac OS X El Capitan
2. angular-cli: 0.0.27
node: 5.8.0
os: darwin x64
3. Ive run npm install -g angular-cli
4. Log:
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.3
npm ERR! path /usr/local/lib/node_modules/.staging/abbrev-e9ea1451
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-e9ea1451' -> '/usr/local/lib/node_modules/angular-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-e9ea1451' -> '/usr/local/lib/node_modules/angular-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dzmitrysukhau/Workspace VisualStudio/angular2-seed/npm-debug.log
npm ERR! code 1

5. npm cache clean has no result, ng is not working

**Comment by Stormcore** [comment]
Solved by rolling back from latest NPM to LTS.

**Comment by filipesilva** [comment]
Hey, I'm glad you got this sorted!
