### ISSUE TITLE
Setup custom service workers

### ISSUE THREAD

**Issue by ShadowManu** [angular/angular-cli#3514]
I'm asking for some guidance: I'm in need to setup a Service Worker file in the app. I could do it with a post-build script for production, but it could be problematic for development. Is there a way to set it up in the actual state of the CLI? I know the `--mobile` flag is disabled from #2228, but what can be done to only achieve an entry point for a custom service worker?

Thanks.

**Comment by filipesilva** [comment]
@ShadowManu no, there is no way to add it from inside the CLI at the moment. @jeffbcross mentioned the possibility of a service worker plugin in https://github.com/angular/angular-cli/issues/2228#issuecomment-253053168, but none exists at the moment.
