### ISSUE TITLE
Nested roots not working using the browser`s adress bar

### ISSUE THREAD

**Issue by MiroKov** [angular/angular-cli#3517]
### OS?
> Windows 10. 

### Versions.
angular-cli: 1.0.0-beta.22-1
node: 6.9.2
os: win32 x64

### Repro steps.
> Created an app using ng new. Pasted und updated my code that worked before using angular-CLI so that there are no more errors.

### The log given by the failure.
The app compiles fine. The error is in Chrome, when using refreshing the webpage from the browser:

Uncaught SyntaxError: Unexpected token <

response is:
![grafik](https://cloud.githubusercontent.com/assets/18582187/21080724/a58b4382-bfb6-11e6-90cb-b74412c01772.png)

### Mention any other details that might be useful.
My application uses an MVC server-side routing that points to ~/index.html.
Index.html looks like this:

<head>
  <base href="./">
  <meta charset="utf-8">
  <title>Title</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link href="styles.776819fdea0d19f568ead4711b3873e7.bundle.css" rel="stylesheet"></head>
<body>
  <app-root>Loading...</app-root>
      
<script type="text/javascript" src="inline.d41d8cd98f00b204e980.bundle.js"></script>
    <script type="text/javascript" src="styles.5f7f16a82a4f91544984.bundle.js"></script>
    <script type="text/javascript" src="scripts.4cc5cca4ad2b0c20ad9d.bundle.js"></script>
    <script type="text/javascript" src="vendor.bdd774df3cfec44bf929.bundle.js"></script>
    <script type="text/javascript" src="main.b68070036956df1649d5.bundle.js"></script>
</body>

Scripts mentioned live in the same directory as index.html. The thing is, as soon as I change the directory by nesting roots
 (by adding a one more '/' -> for instance when I change http://myApp/accounts to http://myApp/accounts/)
,I get the errors mentioned. Just to be explicit, routing within angular2 works good, the problem is when the request comes from browser/server.
Then I need to put something in the index.html, for instance:
<script type="text/javascript" src="**../**inline.d41d8cd98f00b204e980.bundle.js"></script> in order to get the script loaded, but naturally, the routes no longer work, and would ve  a solution just for this depth of the application, when it would work. But at least it seems to point where the problem is, namely changing the directory seems to cause the problem.

**Comment by clydin** [comment]
It looks like your base href is the issue.  Try setting it to '/'.

**Comment by MiroKov** [comment]
Thank you. You have saved me weeks...

**Comment by MiroKov** [comment]
Hi, 
maybe I closed this issue too fast..it really worked for me yesterday, probably I tested just the routing at one route... however, I have other problems now.
Nested routing works, but chunks now need to be loaded from 

> http://localhost:54276/dist/:

Currently I am hosting at: http://192.168.3.147/AdminWebClient/ . Where does the http://localhost:54276 come from? I have hosted locally at this address before. I rebuilded the project and have done `ng build --prod ` multiple times, both before and after the new build. How do I set up from where the chunks are read?

Here is what I get from Chrome:

![image](https://cloud.githubusercontent.com/assets/18582187/21093661/5db697bc-c053-11e6-8881-596d266791f5.png)

My index.html:
`<!doctype html>
<html>
<head>

  <base href="/AdminWebClient/">
  <meta charset="utf-8">
  <title>xy</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link href="styles.776819fdea0d19f568ead4711b3873e7.bundle.css" rel="stylesheet">

  <body>
    <app-root>Loading...</app-root>
    <script type="text/javascript" src="inline.d41d8cd98f00b204e980.bundle.js"></script><script type="text/javascript" src="styles.5f7f16a82a4f91544984.bundle.js"></script>
    <script type="text/javascript" src="scripts.4cc5cca4ad2b0c20ad9d.bundle.js"></script><script type="text/javascript" src="vendor.bdd774df3cfec44bf929.bundle.js"></script>
    <script type="text/javascript" src="main.9d5d92e03905545002c0.bundle.js"></script>
      <script src="signalr/hubs" type="text/javascript"></script>
  </body>

</html>`

**Comment by MiroKov** [comment]
Found the culprit:

```
declare var __webpack_public_path__: any;
__webpack_public_path__='http://localhost:54276/dist/';
```
