### ISSUE TITLE
Fix ng generate instructions in README.md

### ISSUE THREAD

**Issue by leehericks** [angular/angular-cli#3519]
Instructions for using `ng generate` are unclear.

`ng g component my-new-component` will generate MyNewComponentComponent, so this example is misleading and results may scare newer developers and requires manually deleting files and imports because there is no `ng destroy` as in Rails.

**Comment by baruchvlz** [comment]
Or screen the input and maybe throw an error if a "protected" word is used (component, module, directive, etc), or just not add the suffix if one of the words is being used.

`ng g c test-component`

**Comment by leehericks** [comment]
Yes, I think it is more intuitive and open for all styles to check for the existence of the suffix word so that all the following work:
```
ng generate component HeroDetail
ng generate component HeroDetailComponent
ng generate component hero-detail
ng generate component hero-detail-component
```

**Comment by baruchvlz** [comment]
Right, one thing though. If user inputs `ng g c test-component-one` removing the suffix word from the string would generate `TestOneComponent` which might create even more confusion. That's why I suggested the error. 

One walk around would be to not add the suffix and just leave it as `TestComponentOne`, but that wouldn't follow the [style guide](https://angular.io/styleguide#!#naming).

**Comment by leehericks** [comment]
Convention over configuration, follow the style guidelines.
`ng g c test-component-one` should generate `TestComponentOneComponent`. 

User learns quickly. User messes up, would be nice to `ng d c test-component-one` to roll that back.

Can also make this clear in the README documentation. That two-column table showing all the templates could have a third column "Generates" that shows the class name.

**Comment by filipesilva** [comment]
@Brocco what do you think?

**Comment by filipesilva** [comment]
(closed by accident)

**Comment by baruchvlz** [comment]
I have a branch in my fork that takes care of this, I figured I'd wait to see which direction you guys wanted to take on this before I opened a PR. 

Essentially `ng g c my-test-component` will remove `-component` to avoid `MyTestComponentComponent` generates `MyTestComponent` file name `my-test.component.ts`. But if user created `ng g c my-test-directive` (for whatever reason) it will stay `MyTestDirectiveComponent`.

**Comment by Brocco** [comment]
With the adopted file naming convention, I have no issue with stripping off the blueprint name to control confusing names. But at the same time, this could be handled by just updating the documentation to be less confusing. This would give users the correct information while not adding code, but I'm fine with either or both fixes.

**Comment by filipesilva** [comment]
Closing as outdated. If this is still a problem, please let me know.
