### ISSUE TITLE
ng serve throws "LISTEN UNKNOWN"

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#3520]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

1.0.0 beta.22-1

### Repro steps.
Re-installed machine. Just run ng serve throws the error below.

### The log given by the failure.
````
$ ng serve
listen UNKNOWN 0.0.0.0:49152
Error: listen UNKNOWN 0.0.0.0:49152
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1246:19)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
````

**Comment by filipesilva** [comment]
I can't repro it, do you have any hing of what can cause it in your env?

**Comment by rolandoldengarm** [comment]
It's a new machine, with some GPO's on it and firewall rules. 
I tried a different live-reload-port, and that worked. And then suddenly the default port works as well...

So seems machine issue. Thanks @filipesilva for replying.
