### ISSUE TITLE
ng build --dev or ng build --prod doesn't work

### ISSUE THREAD

**Issue by kresogalic8** [angular/angular-cli#3523]
Hey guys, I've got an error with the build.

After running commands "ng build  --dev" and "ng build --prod", I get error 404 which says build files like a bundle or inline js are not found.

I tried to see is that a path error but I think you have problems with it. Do you have the solution for that? 

![screen shot 2016-12-12 at 11 01 57 am](https://cloud.githubusercontent.com/assets/7289406/21095141/6cd27052-c05a-11e6-84e8-bce2c7c0d12d.png)

**Comment by wembernard** [comment]
Try:
- `cd dist`
- `python -m SimpleHTTPServer 8000`
- Open your favorite browser at `localhost:8000`

Enjoy?

**Comment by filipesilva** [comment]
Heya, the problem you are having is related to the server you are using. 

You see how you are accessing `192.168.33.10/gaussBoxNew/dist/`? When you're not serving directly from the root (`192.168.33.10`), you need to set base tag in `index.html` with the right subdirectory href. 

In your case this would be `<base href="gaussBoxNew/dist/">` I think. The CLI also adds it for you with the following flag `ng build --base-href=gaussBoxNew/dist/`.

**Comment by kresogalic8** [comment]
Ok that works for me. Thanks
