### ISSUE TITLE
Support for Typescript 2.1

### ISSUE THREAD

**Issue by henriquecustodia** [angular/angular-cli#3525]
Hi folks! 

Would be very good angular-cli to support Typescript 2.1.

https://blogs.msdn.microsoft.com/typescript/2016/12/07/announcing-typescript-2-1/

Thanks!

**Comment by filipesilva** [comment]
Heya, we plan to add it soon but currently waiting on https://github.com/angular/angular/pull/13294.

**Comment by hccampos** [comment]
@filipesilva looks like this is moving. https://github.com/angular/angular/pull/13294
