### ISSUE TITLE
comments and absolute file paths in AoT ouput

### ISSUE THREAD

**Issue by m4mbart** [angular/angular-cli#3526]
HI,

The --aot output (main.***.bundje.js) is full of comments with instructions like these: 
* @return {Observable<T>} An Observable of the first item that matches the\n * condition.\n *
/** A <body> element that can be safely used to parse untrusted HTML. Lazily initialized below. *

And license agreements from Google. Not sure if that is required? If so it might also be fetched async later?

The file is also full of references to absolute paths on my development machine or buildserver:

"/Users/***/Projects/***/frontend/src/app/app.route.ts"
"sourceURL=webpack:////Users/***/Projects/***/frontend/src/app/ui-components/fnc-file-drop/fnc-file-drop.component.scss.shim.ts"

### OS?
> Mac OSX sierra

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.2
os: darwin x64

### Repro steps.
ng build --prod --aot --env=*** --sm false

**Comment by filipesilva** [comment]
The comments bit is being tracked in https://github.com/angular/angular-cli/issues/2386

The absolute paths are unintended. Will look into it.

**Comment by baruchvlz** [comment]
Possibly related to #3506 ?

**Comment by filipesilva** [comment]
I just checked and this doesn't seem to happen anymore.
