### ISSUE TITLE
ng e2e fails with WebDriver exit code 1 when run through ng-cli

### ISSUE THREAD

**Issue by fonzy2013** [angular/angular-cli#3527]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
```
Mac OS X El Capitan
```

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
angular-cli: 0.0.39
node: 5.0.0
os: darwin x64
```
### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
```
ng new app
ng serve
CMD+c
ng e2e
```
### The log given by the failure.
> Normally this include a stack trace and some more information.
```
[niklas@Niklass-MacBook-Air grok-pattern-ui]$ ng e2e

> grok-pattern-ui@0.0.0 pree2e /Users/niklas/Documents/angular2/grok-pattern-ui
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> grok-pattern-ui@0.0.0 e2e /Users/niklas/Documents/angular2/grok-pattern-ui
> protractor "config/protractor.conf.js"

[15:12:56] I/direct - Using ChromeDriver directly...
[15:12:56] I/launcher - Running 1 instances of WebDriver
[15:12:58] E/launcher - Process exited with error code 1

Some end-to-end tests failed, see above.
```
### Mention any other details that might be useful.
Runnig `ng serve`and in another terminal run `protractor config/protractor.conf.js` works.
```
[niklas@Niklass-MacBook-Air grok-pattern-ui]$ protractor config/protractor.conf.js
[15:15:21] I/direct - Using ChromeDriver directly...
[15:15:21] I/launcher - Running 1 instances of WebDriver
Spec started

  grok-pattern-ui App
    ✓ should display message saying app works

Executed 1 of 1 spec SUCCESS in 3 secs.
[15:15:27] I/launcher - 0 instance(s) of WebDriver still running
[15:15:27] I/launcher - chrome #01 passed
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by baruchvlz** [comment]
`angular-cli: 0.0.39` Try upgrading the CLI.

```bash
npm uninstall angular-cli
npm install --global angular-cli@latest
```

**Comment by baruchvlz** [comment]
Mac OS X Sierra

```
➜  test-app git:(master) ng --version
angular-cli: 1.0.0-beta.21
node: 7.2.1
os: darwin x64
```

After doing repro steps I got the following error.
```bash
1) test-app App should display message saying app works
  - Failed: Angular could not be found on the page http://localhost:4200/ : retries looking for angular exceeded

Executed 1 of 1 spec (1 FAILED) in 10 secs.
[09:31:44] I/launcher - 0 instance(s) of WebDriver still running
[09:31:44] I/launcher - chrome #01 failed 1 test(s)
[09:31:44] I/launcher - overall: 1 failed spec(s)
[09:31:44] E/launcher - Process exited with error code 1
```

**Comment by filipesilva** [comment]
This is intended behaviour. To run your e2e tests you need to have a server running, so that protractor can connect to it and control the browser. If you disconnect the server, protractor will not work.
