### ISSUE TITLE
ERROR in multi main Module not found: Error: Can't resolve 'D:\'

### ISSUE THREAD

**Issue by kolkov** [angular/angular-cli#3529]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

`Windows 10`

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
D:\!Projects\TypeScript\test\ui-router-ng2>ng --version
angular-cli: 1.0.0-beta.22-1
node: 7.2.1
os: win32 x64
```
No any changes in code.
![image](https://cloud.githubusercontent.com/assets/3740898/21106564/9c0b3c1a-c09f-11e6-8323-caf503d46935.png)

**Comment by kolkov** [comment]
My angular-cli not working today. Yesterday all is ok, but today nothing helped (
I tried all combination of versions, deinstalling all local and global node_modules etc., but nothing good happened (((
I did not change anything in the source code.
![image](https://cloud.githubusercontent.com/assets/3740898/21118722/2fec89fe-c0d0-11e6-8958-1a15988d7c96.png)
My mind flew on rocket! :(
![image](https://cloud.githubusercontent.com/assets/3740898/21118854/d69de20c-c0d0-11e6-9c5b-2620e663048a.png)

**Comment by kolkov** [comment]
Today I install node 7.2.1 and angular-cli 22-1 on my second notebook and everything works as it should.
Where can I find the cause of the errors?

**Comment by kolkov** [comment]
**I found what are cause this problem.**
For all new test projects I used root path `D:\!Projects\TypeScript\tests`.
If I understand correctly, you filter out the character **`!`** from path, but **`!`** is legal character in Windows path.
https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/plugin.ts#L116

For reference:
https://msdn.microsoft.com/ru-ru/library/windows/desktop/aa365247(v=vs.85).aspx

Please correct this!
Thanks!

**Comment by n0v1** [comment]
Please see #3468.

**Comment by kolkov** [comment]
Thanks! It's not a project name, is's path to project.

**Comment by filipesilva** [comment]
@hansl see https://github.com/angular/angular-cli/issues/3529#issuecomment-266737336

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
