### ISSUE TITLE
Double files generated when performing `ng generate pipe`

### ISSUE THREAD

**Issue by jkuri** [angular/angular-cli#353]
I am filing a bug.

1. Mac OSX El Capitan 10.11.4
2. angular-cli: 0.0.27 node: 5.8.0 os: darwin x64
3. When generating new pipe double files with different paths are created, in my case:

```sh
ng generate pipe seconds-to-time

installing pipe
  create src/app/seconds-to-time/seconds-to-time.spec.ts
  create src/app/seconds-to-time/seconds-to-time.ts
  create src/app/pipes/seconds-to-time/seconds-to-time.spec.ts
  create src/app/pipes/seconds-to-time/seconds-to-time.ts
```

**Comment by Brocco** [comment]
I have not been able to reproduce this locally.

The `pipes` directory concept was removed in a commit on March 9th by me to facilitate dynamic paths.

You may have some old code in your blueprints directory?

**Comment by jkuri** [comment]
I checked again on newly generated project and it works fine. Closing.

**Comment by alundiak** [comment]
@jkuri what version u checked and it was OK?

**Comment by jkuri** [comment]
@alundiak I am not sure for two years ago which version it was :) I am pretty sure  `> 6.0.0` works good.
