### ISSUE TITLE
[Suggestion] - export declarations, imports, providers for reuse

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/angular-cli#3532]
This is not a bug, which is why I'm not providing any information required by "new issue template".

Often I run into this issue (and I see others run into that as well) when the code I write works in the browser but fails tests due to the fact that my imports/declarations/providers get out of sync in the module and in the tests. So I started writing something like this:

**app.module.ts**
```typescript
...
export const declarations: any[] = [
  AppComponent
];

export const imports: any[] = [
  AppRoutes,
  BrowserModule,
  FormsModule,
  HttpModule
];

export const providers: any[] = [
  { provide: APP_BASE_HREF, useValue: '/' }
];

@NgModule({
  declarations: declarations,
  imports: imports,
  providers: providers,
  bootstrap: [AppComponent]
})
export class AppModule { }
```
**app.component.spec.ts**
```typescript
...
import { declarations, imports, providers } from './app.module';

describe('AppComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations, imports, providers
    });
    TestBed.compileComponents();
  });
...
```
So when I add another declaration, my tests won't be broken. Also, tests look much cleaner.

I'm wondering if there is any downside to doing things this way, and if not, why not default module generation template and tests template to this syntax?

**Comment by clydin** [comment]
The testing module should only be configured with the individual needs of the component under test; not everything the owning module contains (which could be quick large). Ideally tests should be as controlled as possible.  Also mocks may need to be configured instead of an actual dependency.

**Comment by filipesilva** [comment]
There's a docs section about this: https://angular.io/docs/ts/latest/guide/testing.html#!#setup-with-module-imports

I don't think the CLI should enforce the approach suggested in this issue though.
