### ISSUE TITLE
Compiled scss not being output

### ISSUE THREAD

**Issue by jaimeburnap** [angular/angular-cli#3534]
I created a new project using ng new with the --styles=scss option. Then I did an `npm install --save foundation-sites`. When I add `@import '../node_modules/foundation-sites/scss/foundation';` to the /src/styles.scss and then do an `ng serve` all I get in the styles tag is the block comment from the top of node_modules/foundation-sites/scss/foundation.scss file. There is no compiled css being output.

Debian Jessie x64
angular-cli: 1.0.0-beta.22-1
node: 7.1.0
os: linux x64

**Comment by filipesilva** [comment]
Closing as outdated. If this is still a problem, please let me know.
