### ISSUE TITLE
protractor's browser.setLocation() does not work.

### ISSUE THREAD

**Issue by krotscheck** [angular/angular-cli#3536]
### OS?

OSX

### Versions.

angular-cli: 1.0.0-beta.22-1
node: 7.2.0
os: darwin x64
protractor: 0.17.9

#### TL/DR version
Write an e2e test that uses `browser.setLocation` rather than `browser.get`. Even after initializing the angular application using the latter, the following error will be thrown:

```
InvalidElementStateError: invalid element state: Failed to execute 'querySelector' on 'Document': The provided selector is empty.
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.1 x86_64)
```

#### ng init setup
This setup demonstrates how the error is thrown, even though it initializes an app without any serious routing.

```bash:
ng init
mkdir src/assets
touch src/favicon.ico
npm start

# New console window

# Run webdriver-manager update
npm run pree2e
protractor --elementExplorer
browser.setLocation('test');

```

### The log given by the failure.

See above. The exception in question exists within the selenium-webdriver code.

### Mention any other details that might be useful.

How it should work:

```bash:
# Do not execute in a project directory.
protractor --elementExplorer
browser.get('http://angular.github.io/protractor/#/tutorial');
browser.setLocation('api');
browser.setLocation('protractor-setup');
```

**Comment by OvidiuBan** [comment]
Going through the same thing with angular 2. browser.setLocation() doesnt change the url.

**Comment by filipesilva** [comment]
This doesn't sound like a problem with the CLI. Please open it in https://github.com/angular/protractor instead.

**Comment by krotscheck** [comment]
Hrm. A quick test against https://github.com/AngularClass/angular2-webpack-starter shows that it can be reproduced there, which suggests that the issue is in the interaction of webpack and protractor. I assumed that it's got something to do with the webpack configuration (which angular-cli locks) so I figured this'd be the right place to post this, but I'll check with @juliemr and the protractor team to see what they think.

**Comment by molcik** [comment]
I'am using systemjs and have the same issue.
