### ISSUE TITLE
Need to change bootstrap-sass' icon-font-path to customize

### ISSUE THREAD

**Issue by asfernandes** [angular/angular-cli#3537]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Ubuntu Xenial.

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.22-1
node: 7.2.1
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

I can include bootstrap via angular-cli.json by styles:

```
"styles": [
  "../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss",
  "../node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_theme.scss",
  "styles.scss"
]
```

But in this way I can't customize it (for example to change font-family-sans-serif). Then I removed the angular-cli.json bootstrap entries and put in styles.scss:

```
$icon-font-path: '../node_modules/bootstrap-sass/assets/fonts/bootstrap/';
$font-family-sans-serif: Tahoma;
$font-size-base: 8pt;

@import '../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss';
@import '../node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_theme.scss';
```

The problem is that change to icon-font-path should not be needed but currently is.

**Comment by filipesilva** [comment]
Yeah you shouldn't need to specify the font path just because you're importing it from a scss file. Sounds like a bug.

**Comment by filipesilva** [comment]
I seem to remember from another issue that this is actually intended as per how SASS works.
