### ISSUE TITLE
how to config multi-environment url

### ISSUE THREAD

**Issue by floraluo** [angular/angular-cli#3539]
I look for many document and resource. however, I dont find something that I want. Our project have more than 2 environment. For example,It will release to a test env,country A env, countryB env. But I dont know the angular-cli how to config it.I just do this.

environment.prod.ts
```
export const environment = {
  apiUrl: 'http://api-a.xxx.com/'
};
```
`ng server --prod` all request will use `http://api-a.xxx.com/`
environment.dev.ts
```
export const environment = {
  apiUrl: 'http://api-b.xxx.com/'
};
```
`ng server` all request will use `http://api-b.xxx.com/`

Now, I want know that how to get `http://api-c.xxx.com/`or `http://api-d.xxx.com/`.Can I achieve it? And how to do it?

Any reply will appreciate!

**Comment by vfedoriv** [comment]
add new files in environments directory and edit angular-cli.json
"environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }

**Comment by floraluo** [comment]
@vfedoriv only production or development are supported.So,can't add a new files in environments directory.I had try to do this way.But, no effect.

**Comment by vfedoriv** [comment]
Beacose you use --target key.
Try use --environment key:
ng serve --environment=you_environment_variable_name

**Comment by hansl** [comment]
What @vfedoriv said; use `ng build --env=my_environment` to select the environment file.

The `--target` flag is for optimizations; whether you want a minified build or not. You can have any environment with any optimization (debug or prod).

**Comment by floraluo** [comment]
Thank you @vfedoriv  @hansl . I get it.
