### ISSUE TITLE
Generated services are not added to files array in tsconfig.json

### ISSUE THREAD

**Issue by whtouche** [angular/angular-cli#354]
# I am filing a bug.

Mac OSX (El Capitan)
### Versions:
angular-cli: 0.0.27
node: 4.2.1
os: darwin x64

### Repro steps:
1. Generate new project:
"$ ng new project"

2. Generate new service:
"$ ng g service my-service"

3. Navigate to my-service.ts:
Observe warning for "MyService: "Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning."

4. Navigate to tsconfig.json:
Observe that the "files" array does not include "my-service.ts"

---------------------------------------------------------------

I'm new to open source and if it is within my ability I would love to work on this, but would probably need some guidance.

**Comment by Brocco** [comment]
`app.ts` is in the files list of `tsconfig.json` all other project files will be pulled in by walking the module import tree of references. So once you have something that will be using `my-service` it will be included in the TypeScript compilation.

I hope that explains this for you and there are no changes needed to the CLI to ensure your generated files are compiled.
