### ISSUE TITLE
ng build --prod does not preserve escaped '\x1B' sequence.

### ISSUE THREAD

**Issue by chunghha** [angular/angular-cli#3544]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 7

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.2
os: win32 x64

### Repro steps.
- ng new test11
- cd test11
- edit src/app/app.component.ts with
title = 'app works!' + '\x1B';
- ng build
![image](https://cloud.githubusercontent.com/assets/24458075/21152802/879767de-c12d-11e6-8a25-7c44673c96ad.png)
**'\x1B' sequence is preserved.**
- ng build --prod
![image](https://cloud.githubusercontent.com/assets/24458075/21152867/c8e8613e-c12d-11e6-8891-495a2e7fb5bd.png)
**becomes raw 0x1B character.**

Above steps are just to demo the issue I am facing now. But, my real problem is with angular's 
[browser_adapter.ts line 30](https://github.com/angular/angular/blob/7295a5e7f208af0cc3503f33403979f7898c8ba2/modules/%40angular/platform-browser/src/browser/browser_adapter.ts)

the Escape sequence on line 30 becomes invalid character (raw 0x1B) while building for prod by the cli command. 

Is there any way in CLI to fix this erroneous behavior of bundling?

**Comment by clydin** [comment]
This is the expected behavior of uglifyjs.  Is there an underlying issue you're trying to solve?

**Comment by chunghha** [comment]
@clydin thanks for looking at this issue.

I have a vendor product ( including a command line tool written in Java which I am using it with my gulp script to push generated JS files by CLI ) rejects invalid characters such as raw 0x1B in bundled JS file per XML standard. Also, mainly due to certain file size restriction by the product, I also got to supply --prod option to CLI while bundling my project code.

I tried following uglifyJS options against app.component.js transpiled by tsc just for my test.

1)  uglifyjs -c -m **-b beautify=false -b ascii-only** -o a.js -- app.component.js
2)  uglifyjs -c -m -o b.js -- app.component.js

Seems both produce same uglified code except the escaped \x1B. So, if the options in 2) are used by default in CLI, I like to set the options in 1) with CLI and try to bundle actual my project.

Even though I am not sure the options in 2) will solve my issue but at least I like to try. But, I don't know yet how to specify the options with CLI so if someone sheds a light on that, that would be great.

**Comment by clydin** [comment]
Based on your needs, the ascii only option is what you'd want.  Unfortunately, there is currently no way to adjust the setting with the CLI.

**Comment by chunghha** [comment]
Thank you, clydin. As you said "currently", I look forward to that CLI will provide a way to handle this issue near future.

**Comment by filipesilva** [comment]
For consistency, I think the chars should be preserved simply because they are in non-prod builds. I'd review a PR that adds this option to the Uglify Plugin, unless there is a reason why it shouldn't be there by default.

**Comment by harikrishnan-u01** [comment]
I also need this ascii_only option in angular/cli. Is there a fix in pipeline for the same?

**Comment by filipesilva** [comment]
We have no plans for adding the `ascii_only` option. The reasoning for that is described in https://github.com/angular/angular-cli/issues/6155#issuecomment-316324293.

**Comment by filipesilva** [comment]
Please see https://github.com/angular/angular-cli/issues/6155#issuecomment-320292038 for an update on this issue.
