### ISSUE TITLE
export 'Routes' was not found in '@angular/router'

### ISSUE THREAD

**Issue by Difinity** [angular/angular-cli#3547]
I just created a new Angular-CLI project and started migrating some components from a previous webpack project.  When I migrated the NavMenu component, I started getting the error...
> **export 'Routes' was not found in '@angular/router'**

...because of line...
```javascript
@Input() menuRoutes: Routes = [];`
```

I have the import statement and can (CTRL + Click) to navigate directly to the exported declaration:
```javascript
export declare type Routes = Route[];
```

The odd thing is that when  I import **Route** instead of **Routes** and rewrite the line...
```javascript
@Input() menuRoutes: Route[] = [];
```

...I get no error.

Does anyone have any suggestions?  Thanks in advance

### OS?
Windows 7

### IDE?
WebStorm 2016.3.2
Build #WS-163.9166.30, built on December 12, 2016
JRE: 1.8.0_112-release-408-b2 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

### Versions.
angular-cli: 1.0.0-beta.22-1
node: 6.9.1
os: win32 x64

### Repro steps.
> Import Routes from @angular/router and use type Routes.

### The log given by the failure.
> export 'Routes' was not found in '@angular/router'

### Package.json
```javascript
  "dependencies": {
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/router": "3.2.3",
    "@progress/kendo-angular-charts": "^0.10.3",
    "@progress/kendo-angular-dropdowns": "^0.19.1",
    "@progress/kendo-angular-grid": "^0.7.0",
    "@progress/kendo-angular-inputs": "^0.15.1",
    "@progress/kendo-angular-sortable": "^0.7.0",
    "@progress/kendo-angular-upload": "^0.11.1",
    "animate.css": "^3.5.1",
    "bootstrap": "^3.3.7",
    "broccoli-merge-trees": "^1.2.1",
    "broccoli-sass": "^0.7.0",
    "core-js": "^2.4.1",
    "easy-pie-chart": "^2.1.7",
    "font-awesome": "^4.7.0",
    "git": "^0.1.5",
    "glob": "^7.1.1",
    "google-maps": "^3.2.1",
    "group-array": "^0.3.1",
    "ionicons": "^3.0.0",
    "jquery": "^3.1.1",
    "jquery-slimscroll": "^1.3.8",
    "leaflet": "^1.0.2",
    "leaflet-map": "^0.2.1",
    "lodash": "^4.17.2",
    "ng2-ace": "0.0.15",
    "ng2-bootstrap": "^1.1.16",
    "normalize.css": "^5.0.0",
    "rxjs": "5.0.0-beta.12",
    "tether": "^1.4.0",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.2.3",
    "@types/electron": "^1.3.20",
    "@types/hammerjs": "^2.0.33",
    "@types/jasmine": "2.5.38",
    "@types/lodash": "0.0.28",
    "@types/node": "^6.0.42",
    "@types/source-map": "^0.1.27",
    "angular-cli": "1.0.0-beta.22-1",
    "codelyzer": "~2.0.0-beta.1",
    "electron": "^1.4.0",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "node-sass": "^4.0.0",
    "parse5": "^3.0.0",
    "protractor": "4.0.9",
    "ts-helpers": "^1.1.2",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typedoc": "^0.5.1",
    "typescript": "~2.0.3",
    "webdriver-manager": "10.2.5"
  }
```

**Comment by filipesilva** [comment]
I tried this on a brand new project and it would build and serve with no errors:

```
// src/app/app.component.ts

import { Component, Input } from '@angular/core';
import { Routes } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';
  @Input() menuRoutes: Routes[] = [];
}
```

Can you put up a repo that I can clone and see the error?

**Comment by Difinity** [comment]
I need to correct something above...  it's not an error, it's a warning, in both WebStorm and Chrome.  

Despite the warning though, it still works. :-S

To be honest, I don't know what the cause is.  I can see the export of Routes = Route[], but it's saying it can't find it.  It's not causing me an issue to just use Route[] instead, so I'm just going to stick with this.  If I update Angular later, I'll go back and check again.  In the mean time, if no one else is having this issue, then I guess you can close this issue.

Thanks.

**Comment by filipesilva** [comment]
Closing as outdated. If this is still a problem, please let me know.
