### ISSUE TITLE
Custom Templates for Each Type of Component

### ISSUE THREAD

**Issue by jongunter** [angular/angular-cli#3549]
I know there's still a lot more higher-priority stuff be done with `angular-cli`, but a feature allowing custom templates for services/components/pipes/specs/etc. would be a good future addition, in my opinion.

While the templates that `angular-cli` generates are excellent, organizations often have their own stuff they like to add to the defaults (jsdoc directives, naming conventions, etc). I've worked on Angular1 projects where a folder was kept in the repository with project/company specific templates for each type of Angular component. Really helped speed up the on-boarding of new devs onto projects and kept repetitive code to a minimum.

**Comment by filipesilva** [comment]
We're looking to add something like this in the future via custom blueprints. It would allow you to chose the blueprint from somewhere (like github) instead of always use the default.

It's a medium/long term plan though.

**Comment by filipesilva** [comment]
This sort of functionality is being tracked on https://github.com/angular/angular-cli/issues/2618.
