### ISSUE TITLE
npm start failed due to "debug" package.

### ISSUE THREAD

**Issue by noizbuster** [angular/angular-cli#3553]
### OS?
Linux - Ubuntu 14.04

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.21
node: 5.12.0
os: linux x64

because debug package have a typo, npm start failed
see more info : https://github.com/visionmedia/debug/issues/361

It looks like need to upgrade debug package to 2.4.1

**Comment by filipesilva** [comment]
That's really up to the `debug` package. It's an error in it and there's nothing to be done on this repo.
