### ISSUE TITLE
karma singleRun broken (browser stays open)

### ISSUE THREAD

**Issue by display-none** [angular/angular-cli#3554]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.22-1
node: 6.9.1
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
1. create project using `ng new`
2. change `autoWatch` to `false` and `singleRun` to `true` in `karma.conf.js`
3. run `ng test`

expected: tests are run once and the browser is closed
actual: tests do not run and the browser stays open (when `autoWatch` is `true` the tests are run, but browser stays open nonetheless)

### The log given by the failure.
> Normally this include a stack trace and some more information.

nothing happens (no error message or stack trace)

### Mention any other details that might be useful.
Such config was last running fine on angular-cli@1.0.0-beta.19-3.

Running `ng test --watch false --single-run true` works as expected.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by veliancreate** [comment]
seconded

**Comment by filipesilva** [comment]
Currently we have defaults for `--single-run` and `--watch` on the test command that overwrite the ones in Karma config. We really shouldn't overwrite them if the user doesn't use the flags.

**Comment by sadgit** [comment]
##This works -
`ng test --watch false --single-run true`

##This does not work -
`npm run ng test --watch false --single-run true`

node v7.7.2, npm v3.10.7, @angular/cli v1.0.0-rc.1

**Comment by PhilippSoehnlein** [comment]
@sadgit Yes, because all the `--`-options go to npm and not to ng. 
`npm run -- ng test --watch false --single-run true` should work.

See http://unix.stackexchange.com/a/11382

**Comment by sadgit** [comment]
Added script to package.json
`scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "ci-build": "ng build -prod",
    "ci-test": "ng test --watch false --single-run true",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },`

Then `npm run ci-test works too`

**Comment by filipesilva** [comment]
Closing as outdated. If this is still a problem, please let me know.

**Comment by mrj04** [comment]
@filipesilva 
Yes the problem still exists. 
ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 8.1.2
os: darwin x64
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/core: 4.2.2
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic: 4.2.2
@angular/router: 4.2.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.2.2


setting     singleRun: true in karma.config does not exit after execution. 
works only through command line
 ng test --single-run true

**Comment by jgfet** [comment]
https://karma-runner.github.io/latest/intro/installation.html
Installation says Karma doesn't work with node 8.1.2 - is that still the case? Maybe that's why mrj04 still has the issue. It's halted my foray into using Karma for now too.

**Comment by blaineadams** [comment]
I still get problems with --single-run option. 

angular-cli version: 1.5.6
Angular 5.1.3
OS: win32 x64

Anytime the --single-run flag is added the following error message is displayed.
```
ng test --code-coverage --browsers ChromeHeadless --reporters html --watch false --single-run true

returns at end of test run

02 02 2018 13:53:53.395:WARN [launcher]: ChromeHeadless was not killed in 2000 ms, sending SIGKILL.
```

Output is generated but if I want to run the unit tests with coverage as part of a build that will not work because NPM exits on the error. If I don't use the --single-run flag on the ```ng test``` script it never stops.
