### ISSUE TITLE
[Question] How to set relative paths for scripts, styles, etc, injected to index.html

### ISSUE THREAD

**Issue by lexigren** [angular/angular-cli#3557]
### OS?
Ubuntu
### Versions.
1.0.0-beta.17

My angular2 application, built with ng build --prod, is mounted to https://domain/app.
The problem is that scripts and styles injected in index.html have paths like src="styles.8e0edbbd6ad2cb36be49.bundle.js", so page is trying to look for them in root.
How to change it to src="./styles.8e0edbbd6ad2cb36be49.bundle.js"?
Thank you.

**Comment by grueny** [comment]
You can use 'ng build --prod --base-href /app/ ' to set the base href in the index.html to your directory.

**Comment by BernhardFuchs** [comment]
In the <head> section of your index.html add the line:
<base href="/<base-folder>/">

That worked for me

**Comment by lexigren** [comment]
--base-href parameter helped, thank you.

**Comment by blackn1ght** [comment]
I'm using Angular 6, and setting `--base-href` didn't work for me, but setting `deployUrl` in `angular.json` did.

You can set it in `projects -> $projectName -> architect -> build -> options`.

E.g.
`"deployUrl": "/app/"`

**Comment by dtebo** [comment]
Huge Thum

> I'm using Angular 6, and setting `--base-href` wasn't enough to solve this, but setting `deployUrl` in `angular.json` did.
> 
> You can set it in `projects -> $projectName -> architect -> build -> options`.
> 
> E.g.
> `"deployUrl": "/app/"`

Two thumbs way up! I spent the whole day trying to figure this out and I stumbled across your solution and it works great! Thank you very much for your assistance!
