### ISSUE TITLE
ng install does not support @ versions

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#356]
Version: `0.0.27`
OS:  OSX - Mavericks

Tried doing `ng install bootstrap@4.0.0-alpha.2`

Got the following error. `Install failed. Could not find addon with name: bootstrap@4.0.0-alpha.2`

**Comment by filipesilva** [comment]
For now `ng install` is postponed (see https://github.com/angular/angular-cli/pull/294#issuecomment-205409198), so I think this issue is outdated.

It should go on the list of features for the future iteration though.
