### ISSUE TITLE
Update read me from '--style=sass' to '--style=scss'

### ISSUE THREAD

**Issue by pcafstockf** [angular/angular-cli#3563]
> Please provide us with the following information:
> ---------------------------------------------------------------
ReadMe.md should probably say:
ng new sassy-project --style=scss

instead of:
ng new sassy-project --style=sass

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
N/A

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.22-1
node: 6.9.1
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
N/A

### The log given by the failure.
> Normally this include a stack trace and some more information.
N/A

### Mention any other details that might be useful.
Simple ReadMe.md update.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
Both are valid. SCSS and SASS are different. Closing this as WAI.
