### ISSUE TITLE
Angular CLI as DAEMON or Windows Service

### ISSUE THREAD

**Issue by bastienlemaitre** [angular/angular-cli#3567]
### OS?
> Windows Server 2012

### Versions.
> Last version of Angular-CLI (beta 22)

### Repro steps.
> Hi !
I try to serve my project on a production server, but how to use "ng serve" as a daemon or a windows service ? Any idea ?
And how can I put an alias on it ? Like www.whatiwant.com

**Comment by hansl** [comment]
`ng serve` is not meant to be used as a production server. You should build your app (using `ng build --prod`) and deploy using a proper server with a secure configuration.
