### ISSUE TITLE
ng-promote / ng-export

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#357]
ng-promote:
As components are more widely used in an application there should be a way to promote them via the CLI however once they reach the top level of the app the next promotion step should be an extraction to its own published npm module.

ng-export / ng-import:
As code re-use increases there becomes a need to export and import configurations.  With the ability to generate entire cli projects from a meta json object we should also be able to export / import routes and all their child components. As we are generating the application we should be keeping track of whats generated in a meta json for the project.

**Comment by hansl** [comment]
Closing this. This will not be done before we move to having a proper static analyzer and toolkit.
