### ISSUE TITLE
Feature: Scaffold basic Jasmine test skeletons/boilerplate for existing Components / Directives / Modules / Services

### ISSUE THREAD

**Issue by agatlin** [angular/angular-cli#3572]
**Use Case**

A developer has existing ng2 items (e.g. components, directives, modules, and services) which do not currently have associated unit tests. The developer desires to quickly add unit tests for some or all of these items. Unfortunately, manually creating these tests requires significant time--even with the use of code snippets. The developer needs some mechanism to intelligently add simple jasmine tests (e.g. instance creation tests) similar to those tests generated by `angular-cli` for new items. 

The developer would like to be able to generate basic test skeletons for individual items, for selected items, or for all items in a directory sub-tree (i.e. all items in a given application. )

**Suggested Syntax / Functionality**

`ng g test-skeleton [path/]<typescript-filename[.ts] (typeof: component|directive|module|service)>` - Automatically detect the item type (component, directive, module, service) and scaffold a basic creation test for a typescript file if the test does not already exist. 

`ng g test-skeleton [--component|directive|module|service] [path] --recursive` - Automatically scaffold basic creation tests for all items of a given type (or types) within a given directory which do not already have test coverage. By default, the command runs against the current directory. With `--recursive`, the command traverses the entire directory sub-tree.

**Examples**

`ng g test-skeleton ./src/app/app.component` - Generate test for single component

`ng g test-skeleton --component`  **_or_** `ng g test-skeleton --c`  - Generates tests for all components in the current directory without defined tests.

`ng g test-skeleton --component --recursive` **_or_** `ng g test-skeleton --c --r` or `ng g test-skeleton --cr` - Generates tests for all components in the entire directory sub-tree without defined tests.

`ng g test-skeleton --component --module ./src/app/my-feature-module` **_or_** `ng g test-skeleton --cm ./src/app/my-feature-module`  - Generates tests for all components and modules in the my-feature-module directory.

**Sample Test Structure for a Component**

The sample test structure for a component might look exactly like what is created by angular-cli when new components are generated. 

```
/* tslint:disable:no-unused-variable */
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { DebugElement } from '@angular/core';

import { MyComponent } from './my.component';

describe('MyComponent', () => {
  let component: MyComponent;
  let fixture: ComponentFixture<MyComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ MyComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(MyComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

Other tests would be similar to `angular-cli`'s generated tests for those items. 

**General Note**

Despite well-known best practices, developer time constraints; limited familiarity with test tools; and other factors, there is often very limited test coverage in many projects. While the `angular-cli` attempts to motivate test usage by scaffolding tests for new items, it does nothing to facilitate testing of existing items. I believe that inclusion of this sort of tool to back-fill basic tests for existing items would be of great value to many developers and would be well-received and well-used.

**Comment by hansl** [comment]
We don't have a great story for taking over a project that already existed prior to the CLI. We are considering doing it and it's on the roadmap for next year, but that will be beyond final.
