### ISSUE TITLE
Suggestion about generate smaller  *.chunk.js

### ISSUE THREAD

**Issue by suplch** [angular/angular-cli#3573]
> a little suggestion about generate smaller *.chunk.js
I run command ng build -aot, and then generate some *.chunk.js file in dist folder.
I open a file '0.b7bbe93ad30bd6c6f312.chunk.js, this file size is about 474kb,  I search by matching text "this.renderer.createText" in file, there are 432 matches, I can also see other long variable name or method name. Can we generate a short name for them. or we create convenient method for them.
like this
```
 transform "this.renderer.createText" to "this.r.c",   this can save (7 + 9) * 432 = 6912 character
 transform "this._text_..." to "this.txt...",  this can save 3 * 909 = 2727 character
 transform "this._anchor_..." to "this.ac..."  this can save 6 * 228 character
and others.....
```

### OS?
> Mac OSX 

### Versions. 
angular-cli: 1.0.0-beta.20-4
node: 7.0.0
os: darwin x64

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
Dev builds are intentionally unoptimized.  Production builds are minified and compressed.  Try ng build --aot --prod

**Comment by hansl** [comment]
@clydin provided the reason. We don't do optimization ourselves anyway, we use a tool for that (right now, Uglify, but we're looking at Closure as well).

Closing this as having an answer already.

**Comment by istiti** [comment]
almost 5 months, any news about Closure in cli ? 
cc @hansl
