### ISSUE TITLE
Running angular cli on cloud 9 IDE, ng serve does not work

### ISSUE THREAD

**Issue by boriskogan81** [angular/angular-cli#3574]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Ubuntu 14.04.3 LTS

### Versions.
angular-cli: 1.0.0-beta.22-1
node: 6.9.2
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

App is created with the CLU.

### The log given by the failure.
> Normally this include a stack trace and some more information.

No failure is evident, but when I go to the address linked below, there's no page found:

baruchkogan:~/workspace/my-cli-app (master) $ ng serve
** NG Live Development Server is running on http://localhost:8080. **
Hash: 9e648c8fd6cb8172535d                                                               
Time: 10998ms
chunk    {0} main.bundle.js, main.bundle.map (main) 4.66 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 9.99 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.22 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: bundle is now VALID.

### Mention any other details that might be useful.

I've tried ng serve --host 0.0.0.0 --port 8080 and updating NPM. Updating NPM helped last week, but this week it doesn't seem to work.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
This seems more like a configuration issue with Cloud 9. We didn't release a new beta this week yet, so something changed on your Ubuntu machine between last week and today.

Closing this as there's nothing we can do on our side. Check that you don't have a blocking firewall, maybe?
