### ISSUE TITLE
ng g * should add files to git by default

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#358]
version: `0.0.27`

when I generate new components / pipes / * my expectation is that they would be added to git tracking by default.

**Comment by Brocco** [comment]
I disagree with this, I think the idea of trying to add git functionality is going too far outside the scope of the CLI. Along those lines, when new-ing up a project there's an option to `--skip-git` which would not create a repo at all, so that scenario would need to be handled. And what about devs using *gasp* other version control software (mercurial, team foundation version control, SVN) should the CLI also handle them?

**Comment by jkuri** [comment]
Me too, I don't like the idea that `git add` works automatically.

**Comment by zackarychapple** [comment]
Then maybe we should support the base two (git and SVN) and if the project is either it should add them to tracking when created?

**Comment by jkuri** [comment]
What if you want to make a separate commits and add just files that you want?

**Comment by deebloo** [comment]
I agree with @jkuri and @Brocco that this seems like a reach to far. I personally think that creating a git repo may even be a bit to far. but i like that I can skip it if I need/want to.

**Comment by filipesilva** [comment]
Yeah I'm not a big fan of auto adding stuff myself. `ng new/init` is a bit of a special case, in that we want to streamline it as much as possible for the common usecase.

But for normal generate operations I would be quite surprised if stuff was getting auto added.

**Comment by Brocco** [comment]
@deebloo as for creating a git repo upon new/init, that can easily be bypassed by passing the argument `--skip-git` when making a call to `ng new` or `ng init`

I am going to close this issue as the consensus thus far is against this idea.

**Comment by rcollette** [comment]
It seems odd (to me) however that the initial project artifacts are added, you generate new artifacts that update already added artifacts (system.js) and now if you commit, your overall project isn't in sync unless you manually add the artifacts you just generated.   Why add the generated project in the first place if the intent is to not support GIT?
