### ISSUE TITLE
AoTPlugin breaks with Webpack 2.2.0-rc.0

### ISSUE THREAD

**Issue by tinchou** [angular/angular-cli#3581]
### OS?
> Windows 10

```
C:\Users\...........\node_modules\webpack\bin\webpack.js:285
                throw e;
                ^

TypeError: Cannot read property 'plugin' of null
    at AotPlugin.apply (C:\Users\...........\node_modules\@ngtools\webpack\src\plugin.js:174:34)
    at Compiler.apply (C:\Users\...........\node_modules\tapable\lib\Tapable.js:270:16)
    at WebpackOptionsApply.process (C:\Users\...........\node_modules\webpack\lib\WebpackOptionsApply.js:61:18)
    at webpack (C:\Users\...........\node_modules\webpack\lib\webpack.js:32:48)
    at C:\Users\...........\node_modules\webpack\lib\webpack.js:22:11
    at Array.map (native)
    at webpack (C:\Users\...........\node_modules\webpack\lib\webpack.js:21:40)
    at processOptions (C:\Users\...........\node_modules\webpack\bin\webpack.js:275:14)
    at Object.<anonymous> (C:\Users\...........\node_modules\webpack\bin\webpack.js:335:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by daniele-zurico** [comment]
Any news on that? I've the same issue

**Comment by jusefb** [comment]
Having the same problem would be great to get a resolution

**Comment by MrCooper42** [comment]
Also having the same issue! has anyone reverted back to an older version?

**Comment by CarmenPopoviciu** [comment]
indeed. having the same problem. I reverted from ` "@ngtools/webpack": "1.1.5"` with `"webpack": "2.2.0-rc.1"` to ` "@ngtools/webpack": "1.1.5"` with `"webpack": "2.1.0-beta.28"` and the problem is gone.

**Comment by TheLarkInn** [comment]
I have this error solved but I need to work with @hansl to fix the second error. Does anyone have an example of this plugin used outside of the CLI that I can test?

**Comment by tinchou** [comment]
Maybe you can try
https://github.com/MarkPieszak/aspnetcore-angular2-universal

**Comment by tinchou** [comment]
Maybe you can try with https://github.com/angular/universal-starter

**Comment by daniele-zurico** [comment]
@TheLarkInn  https://github.com/daniele-zurico/webpack-aot just update the versions and is ready.
It has the essential exactly what you need

**Comment by CarmenPopoviciu** [comment]
@TheLarkInn or this: https://github.com/blacksonic/angular2-aot-webpack

**Comment by TheLarkInn** [comment]
Thank you

**Comment by TheLarkInn** [comment]
Alright I'm going to leave my findings continuously as I get them. 

First issue is access to resolvers needs to happen after they are created: 

Since I am working in the JS version and not the TS source, it may look a little different in this example but I already showed this to @hansl:

```javascript
        var tsConfigPath = this._tsConfigPath;
        var compilerOptions = this._compilerOptions;
        var compilerHost = this._compilerHost;
        compiler.plugin("after-resolvers", function(compiler) {
            compiler.resolvers.normal.plugin('resolve', function (request, cb) {
                if (request.request.match(/\.ts$/)) {
                    _this.done.then(function () { return cb(); });
                }
                else {
                    cb();
                }
            });
            compiler.resolvers.normal.apply(new paths_plugin_1.PathsPlugin({
                tsConfigPath: tsConfigPath,
                compilerOptions: compilerOptions,
                compilerHost: compilerHost
            }));
        });
```

It looks like now for some reason there is a failure to resolve the virtually created factory file: 
<img width="843" alt="screen shot 2016-12-23 at 3 10 15 pm" src="https://cloud.githubusercontent.com/assets/3408176/21462483/404cc39a-c922-11e6-97b7-5fcdcf11df4f.png">

**Comment by vlodko** [comment]
@hansl do you have any information about release date?

**Comment by hansl** [comment]
It's been released 2 betas ago.
