### ISSUE TITLE
ng generate (whatever) in specific module

### ISSUE THREAD

**Issue by GustavoCostaW** [angular/angular-cli#3591]
Hey friends, when we use ng generate component name the angular cli add this component in main module AKA app.module.ts but we know that it's good to create an Angular module for all distinct features in an application but generate command ever add in main module, is possible specific which module we want to add?

**Comment by deebloo** [comment]
@GustavoCostaW there is not a way to specify a module. however the cli will add the import and declaration to the first module it runs into up the tree.

**Comment by GustavoCostaW** [comment]
@deebloo okay, nice, but you know the better way for example: when our module have a new service and we can add in specific module

ng g s spefic-module/service

but this service isn't add in this module automatically, Am I doing something wrong?

**Comment by deebloo** [comment]
@GustavoCostaW services aren't added automatically. I believe even the message says that it hasn't been added to the providers array. I am not 100 percent sure why that is though but it seems to be on purpose.

**Comment by GustavoCostaW** [comment]
@deebloo all right box thank you for help.
