### ISSUE TITLE
Time load page on apache is too slow

### ISSUE THREAD

**Issue by fdxfdcfd** [angular/angular-cli#3595]
Hi. I try upload code in folder dist to my apache free host. http://shopbanhangphp.esy.es/muahangmy/trang-chu
Its take a long time to load (about more than 1min) this file vender.bundle.js. Anyone can show me why and the way to fix it. Thanks so much.

**Comment by mattdistefano** [comment]
Try `ng build -prod` or `ng build -prod --aot`.

**Comment by fdxfdcfd** [comment]
Hi @mattdistefano. It work like a charm. Thanks so much.
