### ISSUE TITLE
Default Class For Lazy Loaded Module Does Not Work

### ISSUE THREAD

**Issue by guidoffm** [angular/angular-cli#3596]
### Versions.
1.0.0-beta.22-1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
- Make an app that uses a lazy loaded module
- Normally the 'loadChildren' string ist the path to the module file appended with a '#' sign and the module class name.
- In earlier release there was the option to omit the '#' sign and the module class name when the module class was marked with the 'default' keyword
- 

### The log given by the failure.
can't find symbol null exported from module ...

**Comment by andershagebakken** [comment]
This also happens to me. Subscribing.

**Comment by filipesilva** [comment]
@hansl is there a problem with using `default` on lazy modules?

**Comment by guidoffm** [comment]
Yes. There is.

**Comment by filipesilva** [comment]
Closing as outdated. If this is still a problem, please let me know.
