### ISSUE TITLE
ng serve --prod and ng build --prod doesn't work

### ISSUE THREAD

**Issue by gitsad** [angular/angular-cli#3597]
> Please provide us with the following information:
> ---------------------------------------------------------------
I've got some issues with ng serve --prod and ng build --prod. When I'm running these commands I get this kind of bugs
![screenshot from 2016-12-16 12-42-23](https://cloud.githubusercontent.com/assets/13887724/21261749/8c6a7820-c38d-11e6-941e-719dfe704620.png)

I tried to update to the latest version but after that I still have the same problem. What can I do with that. I've seen that prod version works generally but I don't know what is wrong with my app.

### OS?
>  Linux (Ubuntu 16.04). 

### Versions.
>angular-cli: 1.0.0-beta.18
node: 6.3.1
os: linux x64

### Repro steps.
> It happens when I run ng serve --prod and ng build --prod 

### The log given by the failure.
> zone.js:1382 POST http://localhost:4200/null 404 (Not Found)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattdistefano** [comment]
The chatter in the logs looks like fairly normal info/warnings from uglifyjs. The error in your browser console is a different story. Are you expecting your app to do a POST here?

**Comment by gitsad** [comment]
Yes, I want to login to my app but it doesn't seem to finding url

**Comment by gitsad** [comment]
It is trying to post to localhost which is wrong. In dev version it is posting correctly on normal API url. What can be wrong?

**Comment by mattdistefano** [comment]
Where is your URL set?

**Comment by gitsad** [comment]
export const environment = {
    production: true,
    api_url: 'http://localhost:3000/mockapi/',
    api_cf: 'http://url-to-post.com/api/',
    api_cf_login: 'http://url-to-post.com/Token'
};

This. is my environment.ts file which I'm importing to my post.service.ts file and there I'm creating proper URL. In that case in post.service.ts I'm creating a private loginUrl = environment.api_cf_login. Is it wrong?

**Comment by mattdistefano** [comment]
Try duplicating those settings in your environment.prod.ts.

**Comment by filipesilva** [comment]
Right, it's as @mattdistefano debugged. You're missing your api setting for prod.
