### ISSUE TITLE
Module build failed, Cannot find name '$'. After upgrading from Beta 21 to Beta 22.

### ISSUE THREAD

**Issue by expy** [angular/angular-cli#3598]
OS: OSX El Capitan 10.11.6
angular-cli: 1.0.0-beta.22
node: 6.8.1

Description:
----------
My app ran fine under angular-cli beta 21, but after upgrading to beta 22 to use hot module reloading, I'm unable to get a build without errors, and the app won't run in the browser due to JS errors. Specific error message is: Module build failed: Error: /Users/andrewip/newproject/src/app/player/player.component.ts (24,5): Cannot find name '$'.)

Any help would be appreciated.

Log:
----------

> ERROR in ./src/app/player/player.component.ts
> Module build failed: Error: /Users/andrewip/newproject/src/app/player/player.component.ts (24,5): Cannot find name '$'.)
> /Users/andrewip/newproject/src/app/player/player.component.ts (25,5): Cannot find name '$'.)
>     at _checkDiagnostics (/Users/andrewip/newproject/node_modules/@ngtools/webpack/src/loader.js:115:15)
>     at /Users/andrewip/newproject/node_modules/@ngtools/webpack/src/loader.js:140:17
>  @ ./src/app/app.module.ts 21:0-60
>  @ ./src/app/index.ts
>@ ./src/main.ts
> @ multi main

**Comment by vitaly-t** [comment]
Have you tried with Beta 23?

**Comment by mattdistefano** [comment]
What is `$` in your code?

**Comment by expy** [comment]
@vitaly-t  There is no beta 23 afaik.

@mattdistefano  I don't have any explicit '$' reference in my code, I'm guessing it's a jQuery injection from included node modules.

**Comment by filipesilva** [comment]
No idea. Looks like a TS error. If you can get me a repro I can look at it, but otherwise there's nothing I can do.

**Comment by filipesilva** [comment]
Closed as inactive.

**Comment by Choyhow** [comment]
not solution for this? i hit the same error. i using angular/cli RC1
