### ISSUE TITLE
Not working with latest angular2 releases

### ISSUE THREAD

**Issue by tapas4java** [angular/angular-cli#36]
1. Created new app `ng new todoapp`
2. `cd todoapp` and `ng serve`
3. App works fine
4. In `index.html` change angular version and systemjs 
5. App stops working(See error in log)

**Comment by jimthedev** [comment]
Can you post the error? Seems like it is working now, although you need node > 4.1.0.

**Comment by IgorMinar** [comment]
I've updated the blueprints recently. So this should not be a problem any more.

**Comment by tapas4java** [comment]
Thanks for the update @igorminar
