### ISSUE TITLE
vendors 404

### ISSUE THREAD

**Issue by chaiyuxin** [angular/angular-cli#3611]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX (El Capitan)

### Versions.
angular-cli: 0.0.39
node: 5.3.0

### Repro steps.
No changes after the ng new, just tried to see if it worked first

### The log given by the failure.
404 on verdors on github pages but not locally

### Mention any other details that might be useful.
I've been trying to host my angular2 project with Github pages so i tried this tutorial using Angular-cli like this : http://developer.telerik.com/featured/quick-angular-2-hosting-angular-cli-github-pages

index.html works but when it tries to load the vendors i get a 404 as you can see :
https://chaiyuxin.github.io/website

Do you have any ideas about why ?

Thanks ! :)

**Comment by mattdistefano** [comment]
`angular-cli: 0.0.39` is pretty old. Are you able to upgrade and try with the newer version?

**Comment by chaiyuxin** [comment]
Fixed with the last version thanks !
