### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by chaiyuxin** [angular/angular-cli#3615]
### OS?
Mac OSX (Yosemite)

### Versions.
angular-cli: 1.0.0-beta.22-1
node: 5.3.0

### Repro steps.
New project just trying to push and test

### The log given by the failure.

> stdout maxBuffer exceeded
> Error: stdout maxBuffer exceeded
>     at Socket.<anonymous> (child_process.js:266:14)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
>     at Socket.Readable.push (_stream_readable.js:110:10)
>     at Pipe.onread (net.js:523:20)

### Mention any other details that might be useful.
After a ng github-pages:deploy, the build succeed but can't upload it due to that error, i've been trying on multiple repo i get the same error and the project have just been created, nothing custom.

Do you guys had this error ? Any solution ?

Thanks ! :)

**Comment by BathgateIO** [comment]
Yea same here! I have absolutely no idea whats going on!

**Comment by BathgateIO** [comment]
So I found my issue where I had accidently placed an initiated git repo folder in another git repo. github-pages:deploy first flamed out with a bunch of errors than every successive deploy command produced this error. Hope this helps.

**Comment by filipesilva** [comment]
Never see that error myself. Does this happen with a brand new project? Does it only happen on big projects?

**Comment by petermezei** [comment]
I have the same issue. Here is my repro: [https://github.com/petermezei/angular2-cli](https://github.com/petermezei/angular2-cli)

**Comment by petermezei** [comment]
My project is just an init project.

**Comment by donvadicastro** [comment]
Did you found hove to overcome this?

**Comment by petermezei** [comment]
Hi guys, I found where this issue might come:
Node mayBuffer size for child_process is too small. Once I wrote my own git commands using node simple-git I got the same error. When I set my mayBuffer value to 500kb it works smoothly.

So somewhere you should set the maxBuffer size higher in the process.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
