### ISSUE TITLE
Using css-loader in 'main'

### ISSUE THREAD

**Issue by bmitchenko** [angular/angular-cli#3617]
Is there a reason why component styles and other styles in 'main' are not processed by css-loader?

Let's say I have component with ~15 icons. These are small in size and I want them to be encoded in BASE64. The only way to do it now is to move some component's css rules including 'background[-url]' to styles.scss. But it doesn't help me to make this component reusabe in future (I want to move some components to standalone npm package).

**Comment by indywill** [comment]
I'm new also, but I think what you want to do is add the stylesheet you want loaded to app.styles array in angular-cli.json in the project root. Note that the path is relative to the app root, so for instance, use         "../node_modules/font-awesome/css/font-awesome.min.css",
if you want to add font-awesom from your node modules.

Hope this helps.

**Comment by filipesilva** [comment]
This would be useful, yes. 

Relevant to this is https://github.com/angular/angular-cli/pull/3511, where we actually had `css-loader` for component styles but removed it to fix an issue.

Maybe we can look at re-adding it.

**Comment by filipesilva** [comment]
Superseded by https://github.com/angular/angular-cli/issues/4285

**Comment by asnowwolf** [comment]
@filipesilva I vote to css-loader too.
But if only add css-loader, the sourcemap of the component style will be lose, I submitted two PRs about this issue: https://github.com/angular/angular-cli/pull/4491 and https://github.com/angular/angular/pull/14175

**Comment by filipesilva** [comment]
@asnowwolf your PR as is won't fix sourcemaps since your fix in angular/angular is not in. Can you resubmit your PR here after https://github.com/angular/angular/pull/14175 is accepted?

**Comment by asnowwolf** [comment]
Ok, I will resubmit it. I've verified it with my patched version.

**Comment by filipesilva** [comment]
I trust it works in your patched version, mind you. It's just that it might be merged in a different form (or not merged at all) and until then, the code in the CLI would not be verifiable.

**Comment by asnowwolf** [comment]
Yes, I understand. It's a really good rule.

2017-02-13 23:31 GMT+08:00 Filipe Silva <notifications@github.com>:
