### ISSUE TITLE
Beta 23 not on npm

### ISSUE THREAD

**Issue by FallenRiteMonk** [angular/angular-cli#3618]
Is there a reason why beta 23 is not published on npm yet?

**Comment by rosdi** [comment]
Probably intentional? As a buffer a bit? If you want the latest bleeding edge, you could clone this git and use `npm link` so that your project could use the latest build.

**Comment by indywill** [comment]
I don't understand why this was closed with no explanation... and no update on npm. Perhaps there is a good reason for it not being on npm or perhaps it is being added while I type. It seems unhelpful to just close an issue and not explain why it is being closed. I'm looking at you @hans! :-)

**Comment by hansl** [comment]
Beta 23 has not been released yet.

**Comment by Splaktar** [comment]
You can find more details about this in the [changelog](https://github.com/angular/angular-cli/blob/master/CHANGELOG.md).
