### ISSUE TITLE
fail to build with (COMPILER_PROVIDERS (@angular/compiler)) as a provider

### ISSUE THREAD

**Issue by JohanPolon** [angular/angular-cli#3619]
### OS
Microsoft Windows [Version 10.0.14393]

### Versions
angular-cli: 1.0.0-beta.22-1
node: 6.6.0
os: win32 x64

### Repro steps
1. ng new testApp
2. go to "app.module.ts".
3. add "import { COMPILER_PROVIDERS } from '@angular/compiler';" in topp.
4. and add "COMPILER_PROVIDERS" as a provider.
5. and finally "ng server"

### The log given by the failure.
```
C:\Users\johan\Desktop\TestProj\src\app>ng server
** NG Live Development Server is running on http://localhost:4200. **
 10% building modules 2/2 modules 0 activeError: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 54:17 in the original .ts file), resolving symbol COMPILER_PROVIDERS in C:/Users/johan/Desktop/TestProj/node_modules/@angular/compiler/src/compiler.d.ts, resolving symbol AppModule in C:/Users/johan/Desktop/TestProj/src/app/app.module.ts, resolving symbol AppModule in C:/Users/johan/Desktop/TestProj/src/app/app.module.ts
    at positionalError (C:\Users\johan\Desktop\TestProj\node_modules\@angular\compiler-cli\src\static_reflector.js:595:18)
    at simplifyInContext (C:\Users\johan\Desktop\TestProj\node_modules\@angular\compiler-cli\src\static_reflector.js:473:27)
    at StaticReflector.simplify (C:\Users\johan\Desktop\TestProj\node_modules\@angular\compiler-cli\src\static_reflector.js:478:22)
    at StaticReflector.annotations (C:\Users\johan\Desktop\TestProj\node_modules\@angular\compiler-cli\src\static_reflector.js:60:36)
    at AotPlugin.getNgModuleMetadata (C:\Users\johan\Desktop\TestProj\node_modules\@ngtools\webpack\src\plugin.js:330:41)
    at AotPlugin._processNgModule (C:\Users\johan\Desktop\TestProj\node_modules\@ngtools\webpack\src\plugin.js:271:42)
    at C:\Users\johan\Desktop\TestProj\node_modules\@ngtools\webpack\src\plugin.js:242:39
    at process._tickCallback (internal/process/next_tick.js:103:7)
 70% building modules 679/679 modules 0 active
```

### Mention any other details that might be useful.
you can get around the problem by commenting "providers: [COMPILER PROVIDERS],".
save and run ng server and then uncomment the line. this complis but the problem recurs if you restart ng server.

**Comment by clydin** [comment]
As of beta.22, the CLI requires your app to be statically analyzable even in JIT mode.

**Comment by rolandoldengarm** [comment]
@clydin that's a bug; not a new feature...

**Comment by filipesilva** [comment]
@rolandoldengarm that is by design actually.

**Comment by SebastianFree** [comment]
Could someone please drop a line or two on how to reference COMPILER_PROVIDERS in the 'providers' sections of an NgModule correctly? It resides in @angular/compiler just like the JitCompiler class.
We seriously need the functionality to create dynamic components and can't work around this. Thanks!

**Comment by deebloo** [comment]
@SebastianFree if you need to dynamically create instances of components you can do something like the following. Keep in mind that any components you want to dynamically create need to be in the entryComponents list in the NgModule

```TS
import { Injectable, ComponentRef, ComponentFactoryResolver, Injector } from '@angular/core';

@Injectable()
export class ComponentCreatorService {
  constructor(private resolver: ComponentFactoryResolver, private injector: Injector) { }

  createComponent<T>(ComponentClass: any): ComponentRef<T> {
    // the component factory resolver is used to create a component factory
    const factory = this.resolver.resolveComponentFactory(ComponentClass);

    // factory.create() accepts a single argument which is an Injector reference
    const component: ComponentRef<any> = factory.create(this.injector);

    return component;
  }
}
```

**Comment by rolandoldengarm** [comment]
@filipesilva 

> @rolandoldengarm that is by design actually.

I meant that it's a bug that Angular CLI always builds in AOT mode. I hope that that is not by design?

**Comment by clydin** [comment]
It doesn't.  Both JIT and AOT mode require statically analyzable code which is why it may look like it does.

**Comment by SebastianFree** [comment]
Hi, thanks for replying. There is in fact a [question regarding this topic on StackOverflow](http://stackoverflow.com/questions/40622619/angular2-aot-error-function-calls-are-not-suppoted). It didn't have an answer until now, when I found the good workaround, or actually it does seem to be a proper solution.

There is the 'JitCompilerFactory' in '@angular/compiler'. When using this factory, you can leave out COMPILER_PROVIDERS and JitCompiler from the 'providers' section of the module, and use the factory directly. I included this answer in the SO link, as well as [here](http://stackoverflow.com/questions/38888008/how-can-i-use-create-dynamic-template-to-compile-dynamic-component-with-angular) for others to not have the same problem.
