### ISSUE TITLE
Chunks per Module rather than lazy-route

### ISSUE THREAD

**Issue by intellix** [angular/angular-cli#3620]
I'm currently trying to optimise the code size of my application. I have a structure like:

- app
  - shared
  - core
  - deposit (lazy)
  - withdraw (lazy)
  - payment

`app` <- `shared`, `core`
`deposit` <- `shared`, `payment`
`withdraw` <- `shared`, `payment`

```html
 <!-- withdraw.component.html -->
 <h1>Withdraw</h1>
 <my-payment type="withdraw"></my-payment>
```

```html
 <!-- deposit.component.html -->
 <h1>Deposit</h1>
 <my-payment type="deposit"></my-payment>
```

I'm seeing that with this structure, I have chunks created like:
  - main.chunk.js
  - vendor.chunk.js
  - deposit.chunk.js
  - withdraw.chunk.js

Interestingly, SharedModule isn't included in deposit and withdraw lazily loaded chunks, as it's already in app, so I don't have duplicated code there.

One surprising detail to me is that my PaymentModule is included in both Deposit AND Withdraw.

I created my modules with lazy-loading and optimisation in mind. I knew that I was going to re-use a lot of logic between deposit and withdraw so abstracted things into a PaymentModule. I expected there to actually be the following chunks:
 - app.chunk.js
 - shared.chunk.js
 - core.chunk.js
 - deposit.chunk.js
 - withdraw.chunk.js
 - payment.chunk.js

Going to `withdraw` would load 2 files: `withdraw.chunk` and `payment.chunk`. Afterwards the user goes to `deposit` and would only need to dynamically load `deposit.chunk` as `payment.chunk` was already loaded from visiting `withdraw` previously.

Shouldn't a chunk be created per module rather than lazily loaded routes to avoid code duplication and generate chunks as users expected to be created?

**Comment by masaanli** [comment]
I'm also having this question.

**Comment by intellix** [comment]
I've managed to achieve what I expected, but I have to use the router to manage it:

**deposit.module.ts**
```ts
import { NgModule } from '@angular/core';
import { SharedModule } from '../shared/shared.module';
import { DepositRoutingModule } from './deposit-routing.module';
import { DepositComponent } from './deposit.component';

@NgModule({
  imports: [
    SharedModule,
    DepositRoutingModule,
  ],
  declarations: [
    DepositComponent,
  ],
})
export class DepositModule { }
```
 
**deposit-routing.module.ts**
```ts
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { DepositComponent } from './deposit.component';

const routes: Routes = [
  {
    path: '',
    component: DepositComponent,
    children: [
      {
        path: '',
        loadChildren: '../payment/payment.module#PaymentModule',
      },
    ]
  },
];

@NgModule({
  imports: [ RouterModule.forChild(routes) ],
  exports: [ RouterModule ]
})
export class DepositRoutingModule { }
```

```html
 <!-- deposit.component.html -->
 <h1>Deposit</h1>
 <router-outlet></router-outlet>
```

**payment.module.ts**
```ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { PaymentComponent } from './payment.component';

@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild([
      {
        path: '',
        component: PaymentComponent
      }
    ]),
  ],
  exports: [
    PaymentComponent,
  ],
  declarations: [
    PaymentComponent,
  ],
})
export class PaymentModule { }
```

**Comment by intellix** [comment]
Closing this as I guess it works as currently expected. All of the lazily loaded stuff works around routing and I suppose the CLI isn't able to do more than that. Could be an optimisation for Angular itself maybe.
