### ISSUE TITLE
angular-cli@1.0.0-beta.23 is NOT on npm

### ISSUE THREAD

**Issue by st-clair-clarke** [angular/angular-cli#3622]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows  10. 

Although angular-cli 1.0.0-beta.23 (2016-12-15) is released, I cannot install it from npm - the current npm version is angular-cli@1.0.0-beta.22-1. Is this an oversight? Could we correct it please?

**Comment by nikoTM** [comment]
I think this is intentional, to give a bit of breathing room. Might be wrong.

**Comment by clydin** [comment]
Releases are generally not done on Fridays.  We'll probably see a formal release next week.
