### ISSUE TITLE
Could not resolve route 

### ISSUE THREAD

**Issue by aep** [angular/angular-cli#3623]
angular-cli: 1.0.0-beta.22-1
node: 7.1.0
os: linux x64

i'm new to angular2 and not sure how loadChildren is supposed to work.
I upgraded coreui from angular 2.1.2 to 2.2.3 and it broke here:

````
Could not resolve route "app/dashboard/dashboard.module#DashboardModule" from file 
"/home/aep/kram/CoreUI-Free-Bootstrap-Admin-
Template/Angular2_CLI_Full_Project/src/app/app.module".
````

````
        children: [
            {
                path: 'dashboard',
                loadChildren: 'app/dashboard/dashboard.module#DashboardModule'
            },
````

what's the path supposed to be with this relative structure?

````
src/app/app.module.ts
src/app/dashboard/dashboard.module.ts
````

i tried:

- app/dashboard/dashboard.module#DashboardModule
- dashboard/dashboard.module#DashboardModule
- ../app/dashboard/dashboard.module#DashboardModule
- ../../dashboard/dashboard.module#DashboardModule
- src/app/dashboard/dashboard.module#DashboardModule

**Comment by DajMiNazwe** [comment]
I have the same issue as above

**Comment by Nikki1993** [comment]
I am not sure that this is CLI related but could you paste in your routes somewhere? (parent and a child route)

**Comment by karocksjoelee** [comment]
I have the same issue as well ....

**Comment by xwb1989** [comment]
I think somehow angular has changed their path resolver. By changing the path from 

`app/dir1/dir2/...`

(assuming the routes module is configured inside `app` directory) to 
`./dir1/dir2/...`

Can solve this problem.

**Comment by karocksjoelee** [comment]
@xwb1989 save the day !!

**Comment by shuangxia1** [comment]
After changing it as @xwb1989  says , it works! THX

**Comment by kharagpur** [comment]
@xwb1989 Thanks!

**Comment by rkumar654** [comment]
i getting same problem..
   how to solve?

**Comment by shuangxia1** [comment]
Just do it like  @xwb1989 says, change the app directory to **./dir1/dir2/...**

**Comment by rkumar654** [comment]
yes change like this 
./requests/requests.module#RequestsModule

**Comment by rkumar654** [comment]
but i getting same problem

**Comment by rkumar654** [comment]
{
        path:'requests',
        loadChildren:'./requests/requests.module#RequestsModule'
      },

**Comment by rkumar654** [comment]
these are my angular versions...
@angular/cli: 1.0.0-rc.2
node: 6.1.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/compiler-cli: 2

**Comment by rkumar654** [comment]
pls tell me how to solve?
