### ISSUE TITLE
i18nfile: Path must be a string or a buffer

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#3625]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
````
$ ng --version
angular-cli: local (v1.0.0-beta.23, branch: master)
node: 6.9.2
os: win32 x64
````

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
````
ng build --aot --locale zh --i18nFormat xtb --i18nFile "./src/i18n/messages.zh.xtb"
````
error:
````
$ ng build --aot --locale zh --i18nFormat xtb --i18nFile './src/i18n/messages.zh.xtb'
Hash: 81af1eecaeec3091ea3e
Time: 5732ms
chunk    {0} main.bundle.js, main.bundle.map (main) 9.52 kB {1} [initial] [rendered]
chunk    {1} vendor.bundle.js, vendor.bundle.map (vendor) 1.25 MB [initial] [rendered]
chunk    {2} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in path must be a string or Buffer

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './app/client.module.ngfactory' in 'C:\projects\Dev\src\client\src'
 @ ./src/main.ts 4:0-70
 @ multi main

ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
Module not found: TypeError: Cannot convert undefined or null to object
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 69:15-36 85:15-102
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi main
````

If I omit i18nfile, it works fine.
So it seems it cannot find the file. I've tried all options, also tried using quotes, single quotes, double quotes, etc as per @tdesmet his previous suggestion. Tried typescript@2.0.3 as well as 2.1.4 as suggested by @hansl before.
Also tried using full paths, and relative paths. About relative paths, the i18n folder is in /src/i18n; the app is in /src/app. Not sure if that makes a difference?

**Comment by rolandoldengarm** [comment]
Found the solution: I had to use i18n-file instead of i18nFile...
This works:
````
 ng build --aot --locale zh --i18n-format xtb --i18n-file src/i18n/messages.zh.xtb
````
But why is i18nFile accepted by ng as well?

**Comment by tdesmet** [comment]
The commands are indeed --i18n-file, --i18n-format and --locale
The cli just ignores i18nFile.

Because you are passing locale angular compiler is expecting --i18n-file, since you did not give it to the cli a null value is passed on to the compiler.

**Comment by rolandoldengarm** [comment]
@tdesmet thanks for your reply. I figured something like that indeed. Maybe good to have some validation? 
And why does Angular CLI accept i18nFormat? Because on .beta-21 it will throw an error as your PR is not merged yet in .beta-21...

**Comment by tdesmet** [comment]
I have no idea, I'm just guessing here :), might be I made a mistake somewhere...

**Comment by rolandoldengarm** [comment]
it's working now, but I've spent hours on debugging this... Until I found your unit test, and I found out I had made a typo...

**Comment by hansl** [comment]
Seems like there's a bug with the way flags are resolved. A random flag shows a warning that it doesn't exist, while `i18nFile` doesn't. We'll investigate.

**Comment by hansl** [comment]
Found the source cause and coming up with a fix; Ember-CLI treats `--i18nFormat` as a boolean, while it should be a string.
