### ISSUE TITLE
I am not able to install beta.23

### ISSUE THREAD

**Issue by naveenprincep** [angular/angular-cli#3627]
Windows 10 64 bit
When trying to install beta.23 I am getting error.

`> node-sass@3.13.1 install C:\Users\Naveen\AppData\Roaming\npm\node_modules\angular-cli\nod
e_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-48_bin
ding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-48_binding.no
de":

tunneling socket could not be established, statusCode=403

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\Users\Naveen\AppData\Roaming\npm\node_modules\angular-cli
\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files (x86)\nodejs\node.exe C:\Users\Naveen\AppData\Roaming\npm\node_m
odules\angular-cli\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_
cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Naveen\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_m
odules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.3.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Naveen\AppData\Roaming\npm\node_m
odules\angular-cli\node_modules\which\which.js:13:12)`

 I have already set proxy for git and it was working fine. Also I had no issue installing beta.22

**Comment by rosdi** [comment]
I didnt download the binary, instead I cloned this project and then run `npm link`... inside the project folder. Works without problem.

**Comment by naveenprincep** [comment]
OK, let me try that

**Comment by naveenprincep** [comment]
Ahhh!!! [https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-48_binding.node](url)
is redirecting to https://github-cloud.s3.amazonaws.com/releases/4128353/.............. and currently I cant access that link behind my proxy

**Comment by Krisa** [comment]
> I didnt download the binary, instead I cloned this project and then run npm link... inside the project folder. Works without problem.

I've not been very successful on Mac with that. Maybe working fine on other platforms, but I'm getting this error https://github.com/webpack/webpack/issues/2356, happening randomly. Not sure it's exactly the same one, but it's a very similar error messages and beyond failing, it especially breaks the DNS resolution of the machine... All in all, if you're on Mac, it's safer to properly build the module, than to symlink it.

**Comment by skie** [comment]
Any reason that beta.23 tag exists here but on npmjs.com i still see 1.0.0-beta.22-1 as lastest version?

**Comment by thinkingmedia** [comment]
@skie they haven't published 23 yet. I was told on gitter that there might be some issues that need to be fixed first.

**Comment by hansl** [comment]
Beta 23 is coming today or tomorrow (after the next release of Angular).

**Comment by daBishMan** [comment]
So this version of the cli is going to supports Angular 2.4?
