### ISSUE TITLE
feature: support multiple "apps" into a single angular-cli.json file

### ISSUE THREAD

**Issue by alexandrehebert** [angular/angular-cli#3629]
Hi,

I wanted to know if you planned to introduce the support for multiple projects into one single `angular-cli.json` file (as the current `angular-cli.json` file structure suggest it, with an array type for the "apps" configuration).

The expected behavior would be to produce multiple Angular2 applications (different JS files) by running a single `ng build` command from the project root folder.

Regards,
Alex.

**Comment by Destreyf** [comment]
@alexandrehebert This has been brought up in the past, i have a small solution that i wrote up as an attempt to test this concept, the angular-cli only processes the first angular-cli.json app entry, so you can  use a small node.js (could even be gulp) script to swap their orders, here's a link to that issue.

[My Comment](https://github.com/angular/angular-cli/issues/3213#issuecomment-261922391)

Issue: #3213

**Comment by alexandrehebert** [comment]
Thanks a lot for your answer, closing this issue and lets continue this conversation in the #3213 feed.

**Comment by leocaseiro** [comment]
Check https://github.com/angular/angular-cli/pull/5737

**Comment by shoagraw** [comment]
This is really awesome, if you wand detailed pls check here also.
https://yakovfain.com/2017/04/06/angular-cli-multiple-apps-in-the-same-project/

**Comment by delpast1** [comment]
I've followed this guide but it didn't work
https://yakovfain.com/2017/04/06/angular-cli-multiple-apps-in-the-same-project/

**Comment by bresleveloper** [comment]
@delpast1 hi i follows it and it worked, try again step by step carefully
