### ISSUE TITLE
Including external fonts in uppercase throws error

### ISSUE THREAD

**Issue by jpbretanha** [angular/angular-cli#3631]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.22-1
node: 6.5.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
App created with CLI.

### The log given by the failure.
> Normally this include a stack trace and some more information.
Error in ./src/assets/fonts/NEUTRAFACE2CONDENSED-TITLING.OTF
Module parse failed: C:/Users/user/Desktop/Client/site/src/assets/fonts/NEUTRAFACE2CONDENSED-TITLING.OTF Unexpected character ' ' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omtted for this binary file)
@ ./~/css-loader?sourcemap!./~/postcss-loader!./src/styles.css 6:89-147
@ ./src/styles.css
@ multi styles

### Mention any other details that might be useful.
When I change font name file to lowercase it works.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Source of this error seems to be these tests: https://github.com/angular/angular-cli/blob/master/packages/angular-cli/models/webpack-build-common.ts#L128-L133

They should be case insensitive.

**Comment by jpbretanha** [comment]
Yes, they do. But, if I just change to lowercase work perfectly.

**Comment by OfirZinkerz** [comment]
I also tried to replicate the bug but it works just fine.
I also renamed the font file to lowercase and uppercase to test it.

**Comment by hansl** [comment]
Closing this as fixed.
