### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by nottinhill** [angular/angular-cli#3633]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX El Capitan

### Versions.

```
angular-cli: 1.0.0-beta.20-4
node: 6.2.2
os: darwin x64
```

### Repro steps.

Using latest Angular throws dependency errors.   

### The log given by the failure.
```
npm i @ngtools/webpack
myProject@0.0.0 /Users/myUser/devel/myProject
├── UNMET PEER DEPENDENCY @angular/compiler-cli@2.3.1
├── UNMET PEER DEPENDENCY @angular/core@2.3.1
├─┬ angular-cli@1.0.0-beta.20-4
│ └─┬ @ngtools/webpack@1.1.9
│   ├─┬ magic-string@0.16.0
│   │ └── vlq@0.2.1
│   └── source-map@0.5.6
└── UNMET PEER DEPENDENCY rxjs@5.0.0-rc.4
```

**Comment by hansl** [comment]
CLI currently isn't compatible with Angular 2.3. This week's beta will be.
