### ISSUE TITLE
ng github-pages:deploy is not working

### ISSUE THREAD

**Issue by asif633** [angular/angular-cli#3638]
### OS?
> Windows 10.

### Versions.
> angular-cli: 1.0.0-beta.22-1
> node: 6.9.2
> os: win32 x64
> git: 1.9.4

### Repro steps.
> This app was generated using normal `ng new angular2-rxjs`. Then I run `cd angular2-rxjs` then ng` serve`. Worked properly in local browser. After running `ng github-pages:deploy` A github repository was created successfully also in the master branch the source code uploaded successfully. I got the below error. There was no gh-pages branch on github repository. My local project files were also deleted after the `ng github-pages:deploy` command. Auto created repositoy [https://github.com/asif633/angular2-rxjs](https://github.com/asif633/angular2-rxjs) by `ng github-pages:deploy` command.

### The log given by the failure.
```
In order to deploy this project via GitHub Pages, we must first create a repository for it.
It's safer to use a token than to use a password so you will need to create one
Go to the following page and click "Generate new token".
https://github.com/settings/tokens

Choose "public_repo" as scope and then click "Generate token".

? Please enter GitHub token you just created (used only once to create the repo): token-hidden
? and your GitHub user name: asif633
Command failed: git rm -r
usage: git rm [options] [--] <file>...

    -n, --dry-run         dry run
    -q, --quiet           do not list removed files
    --cached              only remove from the index
    -f, --force           override the up-to-date check
    -r                    allow recursive removal
    --ignore-unmatch      exit with a zero status even if nothing matched


Error: Command failed: git rm -r
usage: git rm [options] [--] <file>...

    -n, --dry-run         dry run
    -q, --quiet           do not list removed files
    --cached              only remove from the index
    -f, --force           override the up-to-date check
    -r                    allow recursive removal
    --ignore-unmatch      exit with a zero status even if nothing matched


    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by taylorjb** [comment]
I'm responsible for this and am truly sorry.  I wish it hadn't been included in `1.0.0-beta.22-1`.

It has been fixed as of `1.0.0-beta.23` with the [following](https://github.com/angular/angular-cli/blob/v1.0.0-beta.23/packages/angular-cli/commands/github-pages-deploy.ts#L220-L223).

Your files have not been deleted. You are just on the gh-pages branch, so within the app directory run:

```
git checkout master
```

Update to `1.0.0-beta.23` and the `ng github-pages:deploy` command will work fine.

**Comment by asif633** [comment]
npm could not found `angular-cli@1.0.0-beta.23`. So I downgraded after uninstalling angular-cli. I am now using `angular-cli@1.0.0-beta.21`. Now `ng github-pages:deploy` is working fine. I will update to the latest version later. Thank you for your help.

**Comment by joyanta** [comment]
hi i faced the same issue .. but beta 21 is not working for me

**Comment by taylorjb** [comment]
I see that `angular-cli@1.0.0-beta.23` is not on npm. Apparently there are other issues with that version and another release is coming soon.

Please double check your version by running:

```
ng --version
```

Also make sure your project is not on the `gh-pages` branch:

```
git checkout master
```

**Comment by an0nh4x0r** [comment]
Did as all y'all guys suggested.
Its giving the following error message.
`No changes found. Deployment skipped.`

**Comment by priyeshn** [comment]
Getting "Failed to create GitHub repo. Error: 401 Unauthorized" when tries to deploys angular 2 app to my organization guthub page . Asking for a token and fails with 401

ng github-pages:deploy

? Please enter GitHub token you just created (used only once to create the repo): 
? and your GitHub user name: 
Failed to create GitHub repo. Error: 401 Unauthorized

**Comment by thiagolimaa** [comment]
It's not working for me too.
