### ISSUE TITLE
Ability to publish to github-pages on GitHub Enterprise

### ISSUE THREAD

**Issue by stratus1011** [angular/angular-cli#3641]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> MacOS Sierra

### Versions.
> angular-cli: 1.0.0-beta.21
node: 4.2.3
os: darwin x64

### Repro steps.
> 1) Create repo with angular-cli on GitHub Enterprise
> 2) Ran github-pages:deploy
> 3) Was prompted for GitHub token.
> 4) Enter token created from settings/tokens on GitHub page
> 5) Entered userid when prompted
> 6) Got error: "Error: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)"

### The log given by the failure.
>  "Error: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)"

### Mention any other details that might be useful.
> Since some companies have GitHub Enterprise accounts and host GitHub internally can we get the ability to override the default GitHub url's in order to publish to internally hosted GitHub instances?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Yeah that makes sense. It's low prio for us though.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
