### ISSUE TITLE
Can't install angular-cli

### ISSUE THREAD

**Issue by AmithMendis** [angular/angular-cli#3644]
### OS?
> Windows 7 64-bit

### Versions.
> Node js : v6.9.2
    npm     : 4.0.3

### Repro steps.

I have tried to install Angular-cli using 
- npm install -g angular-cli 
- npm install -g -f angular-cli

Output for npm install -g -f angular-cli is as follow

C:\Windows\system32>npm install -g -f angular-cli
npm WARN using --force I sure hope you know what you are doing.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[               ...] \ finalize:block-stream: sill finalizesers\amithm\AppData\Roaming\npm\node_modules\angular-cli\node_modules\indexof

### The log given by the failure.
> 
When I try to run ng -help, It gives following error message
- 'ng' is not recognized as an internal or external command,
   operable program or batch file.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by metavurt** [comment]
Amith ~ I am unfortunately unable to replicate your current experience, mainly because my environment is os x, not windows. However, I have done some serious searching and two things seem to be a recurring thing in your environment: 1. running as or not as admin (do all -g install as admin), and 2. [this link](http://stackoverflow.com/questions/37991556/ng-is-not-recognized-as-an-internal-or-external-command) in SO has a problem with PATH identified and solved. I hope that helps you in your search to resolve this issue.

Other than that, all that I can tell you is I am running node@7.2.1 and npm@4.0.5 and have ng installed with no problems. Let me know though if you want me to try and dig up more info for you.

**Comment by AmithMendis** [comment]
Hi @metavurt,

Thank you for helping me. I have run install commands as admin and in my PATH variables I have %AppData%\npm;%AppData%\npm\node_modules\angular-cli\bin;. 
But when I went to %AppData%\npm\node_modules\angular-cli\bin after angular-cli folder there is no bin folder. 
![angularcli](https://cloud.githubusercontent.com/assets/14071021/21333979/d120b35a-c679-11e6-84e1-ad658a7cfcb7.PNG)

It has only node_modules folder.

**Comment by metavurt** [comment]
Ah - well remember, the angular-cli folder is (or should be) inside the node_modules folder. And then inside *that* would hopefully be the bin folder.  The screenshot you have included, is that with the node_modules folder view expanded? 

Let me know what you find inside the node_modules folder. If angular-cli folder is not in there, then angular-cli still has not installed at all. 

Also, was that the entire log file you included before? An install of angular-cli will not be stopped by warnings, but will be stopped by errors. I'm not sure I see any errors in that log file that would terminate the installation process. Let me know, and we'll get you going, sooner than later! :)

**Comment by AmithMendis** [comment]
Hi, 
**In node_modules folder angular-cli folder is exist.**
![capturewe](https://cloud.githubusercontent.com/assets/14071021/21336531/15d45602-c68c-11e6-8a1a-d77619f6390d.PNG)


**But inside angular-cli folder bin folder is not appear. Instead of that it have another node_modules folder.**
![captureang](https://cloud.githubusercontent.com/assets/14071021/21336575/5dabd8ec-c68c-11e6-8f38-32dbc25cd3e7.PNG)


**Inside that node_modules folder there are some other folders.** 
![captureang2](https://cloud.githubusercontent.com/assets/14071021/21336601/8032c344-c68c-11e6-9c88-b542eddb92ce.PNG)

**Comment by Nikki1993** [comment]
Try completely uninstalling angular-cli & clearing npm cache

`npm uninstall -g angular-cli`
`npm cache clean`

Then, make sure you are running CMD or Terminal of choice always with admin rights and execute
`npm i -g angular-cli`, do not install with -f force option. It should not be necessary at all. 

P.S. you could also completely remove node and all related stuff as npm etc (you can find tutorials online what and where to delete manually) and instead install node with package manager, it's going to ensure that it is installed correctly (provided you again use terminal with ADMIN rights, doing so without it will result in stuff not working).

https://chocolatey.org/ and after installing it simply running in the terminal `choco install nodejs`

**Comment by AmithMendis** [comment]
Hi @Nikki1993 ,
I have completely remove node and all npm related stuff. After that I have installed nodejs using choco. Now what can I do to install angular-cli? Because now I do not have npm.

**Comment by AmithMendis** [comment]
I did all the steps, But it didn't work.

![angularcli](https://cloud.githubusercontent.com/assets/14071021/21386177/9cd202f6-c797-11e6-80bb-3bbb991fcb32.PNG)

First time it stopped at finalize stage. Then I have run it again and again and got this error. What could be this error?

**Comment by filipesilva** [comment]
I'm sorry but I'm not able to help. No code from `angular-cli` actually runs, you seem to have a problem with `npm` instead. You can try their issue tracker instead https://github.com/npm/npm
