### ISSUE TITLE
webpack-dev-server 2.1.0-beta.9 has ssl certificate issues

### ISSUE THREAD

**Issue by sumigoma** [angular/angular-cli#3645]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
N/A

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Running app with --ssl flag. The certificate provided by webpack-dev-server 2.1.0-beta.9 has some issues on Windows (https://github.com/webpack/webpack-dev-server/issues/648) that were resolved with beta.10. Can we update the webpack-dev-server dependency in angular-cli to beta.10 OR use ^/~? I'd rather not npm shrinkwrap if I don't have to, assuming there aren't major config changes between webpack-dev-server beta.9 and 10.

It'd be nice if the webpack and webpack-dev-server versions could be updated to coincide with the angular-cli bump to beta.23.

**Comment by filipesilva** [comment]
Latest webpack was updated in https://github.com/angular/angular-cli/pull/3786. If you open a PR for the dev-server I'll review it. Look in the same files as the ones in that PR.
