### ISSUE TITLE
Lastest release has an issue with Firebase reference / not recognized. 

### ISSUE THREAD

**Issue by Energy4216** [angular/angular-cli#3648]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
>windows 10

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Nothing changed except the version of angular cli betta 22-1. Reverted back to beta 17 and firebase reference works just fine. Only picked 17 because thats what I had before the issue. 

Try using angularfire2 with betta 22-1 and use a firebase reference like this and see if you get an error: 
userPost(postForm) {
 let userPost = this.af.auth.subscribe( (user) => {
  if (user) {
    firebase.database().ref('users/' + user.uid + '/userposts').push(postForm.value.postText);
    this.postForm.reset();  
  } else {
    console.log("No user logged in!")
  }
  });
} 

### Mention any other details that might be useful.
Have everything set up correctly and has worked in all previous version as far as I know. Currently using the latest angularfire2 npm install.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Can you setup a repo that shows the error with the latest version? Also what's the error that shows up?

**Comment by filipesilva** [comment]
Closed as inactive.
