### ISSUE TITLE
Please upload the latest angular-cli version to the npm repo

### ISSUE THREAD

**Issue by saurabhajmera** [angular/angular-cli#3649]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

MAC OSX

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

1.0.0-beta.22-1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
I tried to upgrade my angular-cli to the latest release by doing the following:

npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest

I noticed that npm is still downloading: 
└─┬ angular-cli@1.0.0-beta.22-1

### The log given by the failure.
> Normally this include a stack trace and some more information.

Also, noticed that latest is still pointing to beta.22-1. See below:
sajmera$ npm view angular-cli | grep 'latest'
  'dist-tags': { latest: '1.0.0-beta.22-1' },

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rolandoldengarm** [comment]
And you please look through previous issues....
E.g.: https://github.com/angular/angular-cli/issues/3627#issuecomment-268058848

**Comment by filipesilva** [comment]
Closed as dupe.
