### ISSUE TITLE
Abandon 1.0.0-beta.23 and Release 1.0.0-beta.23-1 or .24

### ISSUE THREAD

**Issue by AilisObrian** [angular/angular-cli#3650]
### OS?
MacOS 10.12.1 (16B2657)

### Versions.
angular-cli@1.0.0-beta.23
@angular/*@2.3.1
@angular/router@3.3.1

### Repro steps.
Installing above packages, failed caused by #3513

### The log given by the failure.
```
npm ERR! peer dep missing: tslint@^3.0.0, required by tslint-loader@2.1.5
```

**Comment by vapits** [comment]
@AilisObrian How did you install the `.23`? I cannot find it on npm.

**Comment by serhiisol** [comment]
@vapits try to install from this repository, steps to reproduce in the main README

**Comment by clydin** [comment]
The PR you linked updates the required version of tslint-loader to ^3.3.0.  You seem to have a mix of dependencies.

**Comment by exequiel09** [comment]
Beta 24 has now been released.

**Comment by AilisObrian** [comment]
Thanks folks!
