### ISSUE TITLE
"ng serve" not slow compile error

### ISSUE THREAD

**Issue by kgtkr** [angular/angular-cli#3654]
Even if you write a code that normally becomes an error, no error is displayed when it is "ng serve".

example

    //Importing file that do not exist.
    import {Foo} from './not-exist-file';

Sorry I'm not good in English.

**Comment by gelliott181** [comment]
Not sure what you're talking about. TSLint complains about that in Atom, `serve` and `build` complain about that in their output, and there are error messages logged to the browser's console along with the app never bootstrapping properly. I don't think the errors have any more places left to appear.

**Comment by kgtkr** [comment]
Even if you code incorrectly, no error is displayed.

**Comment by hassanasad** [comment]
I believe this was a reported issue before. Some developers use the command `ng build` to check for errors that are not shown with `ng serve`. I know its not a good solution but it works for now at-least :)

**Comment by kgtkr** [comment]
OK.Thanks You.
