### ISSUE TITLE
ng serve can't resolve module @angular/core/src/di/opaque_token from [..]/src/index.ts

### ISSUE THREAD

**Issue by invious** [angular/angular-cli#3658]
/src/index.ts doesn't even exist... I don't see it in the /src/ folder in any project I've ever tried to run... what's looking for that and why?

```
$ ng serve
can't resolve module @angular/core/src/di/opaque_token from /Users/aymon/Downloads/migration-project/src/index.ts
Cannot read property 'parse' of undefined
TypeError: Cannot read property 'parse' of undefined
    at ReflectorHost.normalizeAssetUrl (/Users/aymon/Downloads/migration-project/node_modules/@angular/compiler-cli/src/reflector_host.js:54:43)
```

**Comment by jwiggers** [comment]
same problem here

**Comment by filipesilva** [comment]
Don't know myself. It might be a version problem but you'll have to track it down since I can't repro.

I advise starting with a brand new CLI project and checking how your deps differ. Pay special attention to angular versions and typescript.
