### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular-cli#3659]
I'm pretty new to npm and github so my question might sounds stupid.

Is it normal that the @latest version of angular-cli on npm is 22-1 when you posted the version 23 changelog 5 days ago and the 24 version on github 2 hours ago ?

**Comment by exequiel09** [comment]
@Ploppy3 GitHub and NPM are different platforms. Repo maintainers and collaborators needs to publish the code to NPM for you to be able to fetch the latest versions. Publishing code here in GitHub will not automatically publish in NPM.

So far the latest published version in NPM is `1.0.0-beta.22-1`.

**Comment by ecsnavarretemit** [comment]
For more information i think it's best to refer to this issue/thread: https://github.com/angular/angular-cli/issues/3627#issuecomment-268058848

**Comment by hansl** [comment]
That was a mistake; we removed beta 23 because it had problems. The CHANGELOG was not removed as part of this, but now we've done it and everything is in order. :D

**Comment by exequiel09** [comment]
@hansl, Does beta 24 supports Angular 2.4.0?

**Comment by Ploppy3** [comment]
@hansl Thank you for the info.

@exequiel09 the package.json of the CLI 24 does not allow ng 2.4.0 by default.

**Comment by filipesilva** [comment]
@exequiel09 yes.
