### ISSUE TITLE
How to enable source map for saas? ("1.0.0-beta.22-1)

### ISSUE THREAD

**Issue by sergamers** [angular/angular-cli#3666]
{
  "project": {
    "version": "1.0.0-beta.22-1",
    "name": "ups"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.scss"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/materialize-css/dist/js/materialize.js"
      ],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}

**Comment by montella1507** [comment]
i think this may work after beta.23. Where the source map option should be fixed. Havent tried yet.

**Comment by filipesilva** [comment]
Yeah I think I fixed it in the latest versions. Let me know if it's not working.

**Comment by MickL** [comment]
Im using beta 24 and i dont see any source maps. The .map file seems to be empty:

`{"version":3,"sources":[],"names":[],"mappings":"","file":"styles.bundle.css","sourceRoot":""}`

**Comment by MickL** [comment]
I hope [#2020](https://github.com/angular/angular-cli/issues/2020) will fix this.
