### ISSUE TITLE
ngCompiler.ReflectorHost is not a constructor

### ISSUE THREAD

**Issue by maxime1992** [angular/angular-cli#3668]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Ubuntu 16.10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
$ ng -v
angular-cli: 1.0.0-beta.24
node: 6.8.0
os: linux x64
@angular/common: 2.3.1
@angular/compiler: 2.3.1
@angular/core: 2.3.1
@angular/forms: 2.3.1
@angular/http: 2.3.1
@angular/material: 2.0.0-alpha.11-3
@angular/platform-browser: 2.3.1
@angular/platform-browser-dynamic: 2.3.1
@angular/router: 3.3.1
@angular/compiler-cli: 2.3.1
```

(I did also try with 2.2.4 but I get `This version of CLI is only compatible with angular version 2.3.1 or better` and with 2.4.0 but it's not working either).

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Upgrade an app to beta-24
`ng serve`

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
ngCompiler.ReflectorHost is not a constructor
TypeError: ngCompiler.ReflectorHost is not a constructor
    at AotPlugin._setupOptions (/home/maxime/Documents/petals-cockpit/frontend/node_modules/@ngtools/webpack/src/plugin.js:127:31)
    at new AotPlugin (/home/maxime/Documents/petals-cockpit/frontend/node_modules/@ngtools/webpack/src/plugin.js:35:14)
    at Object.exports.getWebpackNonAotConfigPartial (/home/maxime/Documents/petals-cockpit/frontend/node_modules/angular-cli/models/webpack-build-typescript.js:20:13)
    at new NgCliWebpackConfig (/home/maxime/Documents/petals-cockpit/frontend/node_modules/angular-cli/models/webpack-config.js:26:42)
    at Class.run (/home/maxime/Documents/petals-cockpit/frontend/node_modules/angular-cli/tasks/serve-webpack.js:20:22)
    at /home/maxime/Documents/petals-cockpit/frontend/node_modules/angular-cli/commands/serve.js:108:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Mention any other details that might be useful.

As https://github.com/angular/angular-cli/issues/3607, https://github.com/angular/angular-cli/issues/3587 are now closed, I decided to open a new issue because it was supposed to be fixed in beta-24.

(at least, I presume you were talking about beta-24 @hansl)
![image](https://cloud.githubusercontent.com/assets/4950209/21382819/e585dbd8-c762-11e6-82a1-f4aa44fe5ea2.png)

**Comment by intellix** [comment]
```
bash-4.4$ ng version
angular-cli: 1.0.0-beta.24
node: 7.1.0
os: darwin x64
@angular/common: 2.4.0
@angular/compiler: 2.4.0
@angular/core: 2.4.0
@angular/forms: 2.4.0
@angular/http: 2.4.0
@angular/platform-browser: 2.4.0
@angular/platform-browser-dynamic: 2.4.0
@angular/router: 3.4.0
@angular/compiler-cli: 2.4.0

bash-4.4$ ng serve
ngCompiler.ReflectorHost is not a constructor
TypeError: ngCompiler.ReflectorHost is not a constructor
    at AotPlugin._setupOptions (/Users/dominic/Sites/stash/xcaf/r2d2/node_modules/@ngtools/webpack/src/plugin.js:136:31)
    at new AotPlugin (/Users/dominic/Sites/stash/xcaf/r2d2/node_modules/@ngtools/webpack/src/plugin.js:37:14)
    at Object.exports.getWebpackNonAotConfigPartial (/Users/dominic/Sites/stash/xcaf/r2d2/node_modules/angular-cli/models/webpack-build-typescript.js:20:13)
    at new NgCliWebpackConfig (/Users/dominic/Sites/stash/xcaf/r2d2/node_modules/angular-cli/models/webpack-config.js:26:42)
    at Class.run (/Users/dominic/Sites/stash/xcaf/r2d2/node_modules/angular-cli/tasks/serve-webpack.js:20:22)
    at /Users/dominic/Sites/stash/xcaf/r2d2/node_modules/angular-cli/commands/serve.js:108:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by intellix** [comment]
ok, so I was told to try following the upgrade options specified in README.md... afterwards it now works.

```
bash-4.4$ ng version
angular-cli: 1.0.0-beta.24
node: 7.1.0
os: darwin x64
@angular/common: 2.4.0
@angular/compiler: 2.4.0
@angular/core: 2.4.0
@angular/forms: 2.4.0
@angular/http: 2.4.0
@angular/platform-browser: 2.4.0
@angular/platform-browser-dynamic: 2.4.0
@angular/router: 3.4.0
@angular/compiler-cli: 2.4.0

bash-4.4$ ng serve
** NG Live Development Server is running on http://localhost:4200. **
Hash: 9fbb594e5458db2f5d7c
Time: 25475ms
chunk    {0} main.bundle.js, main.bundle.map (main) 185 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 182 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 3.16 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
```

How can everything work now with the exact same versions as above?

**Comment by maxime1992** [comment]
You're totally right for Typescript. I'm using `Typescript 2.1.4`.

Having a yarn.lock would be good but in case of conflicts with users when upgrading, might be more complicated, what do you think ?

**Comment by ciesielskico** [comment]
Same issue with beta.24

```
angular-cli: 1.0.0-beta.24
node: 6.9.2
os: linux x64
@angular/common: 2.4.0
@angular/compiler: 2.4.0
@angular/core: 2.4.0
@angular/forms: 2.4.0
@angular/http: 2.4.0
@angular/platform-browser: 2.4.0
@angular/platform-browser-dynamic: 2.4.0
@angular/router: 3.1.1
@angular/compiler-cli: 2.4.0
@angular/language-service: 2.3.0

"typescript": "~2.1.4",
```

> ng serve
> 
> ngCompiler.ReflectorHost is not a constructor
> TypeError: ngCompiler.ReflectorHost is not a constructor
>     at AotPlugin._setupOptions (/home/ciesielskico/Documents/app/node_modules/@ngtools/webpack/src/plugin.js:136:31)
>     at new AotPlugin (/home/ciesielskico/Documents/app/node_modules/@ngtools/webpack/src/plugin.js:37:14)
>     at Object.exports.getWebpackNonAotConfigPartial (/home/ciesielskico/Documents/app/node_modules/angular-cli/models/webpack-build
> -typescript.js:20:13)
>     at new NgCliWebpackConfig (/home/ciesielskico/Documents/app/node_modules/angular-cli/models/webpack-config.js:26:42)
>     at Class.run (/home/ciesielskico/Documents/app/node_modules/angular-cli/tasks/serve-webpack.js:20:22)
>     at /home/ciesielskico/Documents/app/node_modules/angular-cli/commands/serve.js:108:26
>     at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by dojchek** [comment]
It stops on 21% for me as well. I have the exact same setting as you.
This is because the beta.22-1 is not compatible with angular 2.3.0+

So, for now I'm downgrading back to angular 2.2.3 (router 3.2.3) and angular-cli beta.22-1

**Comment by maxime1992** [comment]
@dojchek we're talking about beta-24 here and look what I wrote in the topic : 
> I did also try with 2.2.4 but I get "This version of CLI is only compatible with angular version 2.3.1 or better and with 2.4.0" but it's not working either

So with beta-24, we just can't downgrade to 2.2.3

**Comment by dojchek** [comment]
@maxime1992 
Yes, I know - Just wanted to share my troubles, since I ran into the same issue. Ended up spending half a day trying to get it work and eventually downgraded until this gets fixed..

**Comment by wesleycho** [comment]
This is basically an issue with Angular 2.3+ and `@ngtools/webpack` I believe. This is fixed in the latest releases I believe.

**Comment by alexbyk** [comment]
+1

**Comment by filipesilva** [comment]
Seems to be fixed in latest now.

See https://github.com/angular/angular-cli/issues/3426#issuecomment-269669853 regarding TS2.1 compatibility.
