### ISSUE TITLE
Cannot complete npm install after upgrading to beta.24 and angular 2.4.0

### ISSUE THREAD

**Issue by vapits** [angular/angular-cli#3669]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

MacOS Siera 10.12.2

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```bash
angular-cli: 1.0.0-beta.24
node: 6.6.0
os: darwin x64
@angular/common: 2.4.0
@angular/compiler: 2.4.0
@angular/core: 2.4.0
@angular/forms: 2.4.0
@angular/http: 2.4.0
@angular/platform-browser: 2.4.0
@angular/platform-browser-dynamic: 2.4.0
@angular/material: 2.0.0-alpha.11
@angular/router: 3.4.0
@angular/compiler-cli: 2.4.0
```
Of course if I try to run the app with `ng serve` i'm getting errors. Specifically this:
>patterns.map is not a function
TypeError: patterns.map is not a function
    at GlobCopyWebpackPlugin.apply (/Projects/WebApp/node_modules/angular-cli/plugins/glob-copy-webpack-plugin.js:16:29)
    at Compiler.apply (/Projects/WebApp/node_modules/tapable/lib/Tapable.js:270:16)
    at WebpackOptionsApply.process (/Projects/WebApp/node_modules/webpack/lib/WebpackOptionsApply.js:59:18)
    at webpack (/Projects/WebApp/node_modules/webpack/lib/webpack.js:28:48)
    at Class.run (/Projects/WebApp/node_modules/angular-cli/tasks/serve-webpack.js:38:27)
    at /Projects/WebApp/node_modules/angular-cli/commands/serve.js:108:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

This is an app created with the cli. I just upgrade from 2.2.1 (Angular) to 2.4.0 and cli from beta.21 to beta.24

### The log given by the failure.
> Normally this include a stack trace and some more information.
```bash
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.0
├── UNMET PEER DEPENDENCY @angular/core@2.4.0
├── UNMET PEER DEPENDENCY tslint@4.1.1

npm WARN codelyzer@2.0.0-beta.3 requires a peer of tslint@~4.0.0 but none was installed.
npm WARN codelyzer@2.0.0-beta.3 requires a peer of @angular/compiler@<=2.3 >=2.2.0 but none was installed.
npm WARN codelyzer@2.0.0-beta.3 requires a peer of @angular/core@<=2.3 >=2.2.0 but none was installed.
```
### Mention any other details that might be useful.
I delete of course first the `node_modules` directory and did a clean `npm install` and of course before I have upgrade the global cli version  with uninstall, clean cache and install the latest version.

I guess this is a codelyzer issue but on the other hand as it is published I guess there is a workaround, correct? If so please share it in order to be able to upgrade our projects.

**Comment by StephenFluin** [comment]
I ran into this same error. I believe I fixed it locally by replacing my angular-cli.json with a version generated by beta 24's `ng new`.

**Comment by vapits** [comment]
Thx @StephenFluin 
I'm getting only the warnings now but the project can run!

I'm leaving it open for a team member response, if He/she wants something to add.

**Comment by JayFunky** [comment]
I have the same problem. Today I install Angular-CLI beta.24 and when I try to install angularfire2 and firebase, I get the same error
`
npm WARN angularfire2@2.0.0-beta.6 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN codelyzer@2.0.0-beta.3 requires a peer of @angular/compiler@<=2.3 >=2.2.0 but none was installed.
npm WARN codelyzer@2.0.0-beta.3 requires a peer of @angular/core@<=2.3 >=2.2.0 but none was installed.
npm WARN codelyzer@2.0.0-beta.3 requires a peer of tslint@~4.0.0 but none was installed.
`

with this error, my app want start normaly. Please help

**Comment by vapits** [comment]
@JayFunky I did what @StephenFluin said. Copy the new `angular-cli.json` that is created if you try to create a new project.

This solved this for me but now ALL my project components and files are missing in the compile minning that I get a `Module not found` error.

**Comment by vapits** [comment]
FYI the `moule not found` errors was there because at the latest version the `templateUrl` and `styleUrls` should always start with a `./`.

**Comment by gilbertowa** [comment]
On angular-cli.json replace **"assets": "assets"** to **"assets": ["assets"]**, works to me.

**Comment by drewjocham** [comment]
Have the same issue and when I tried **"assets": "assets" to "assets": ["assets"],** I got the following error:

`Module not found: Error: Can't resolve 'script' in '/web/src/app/shared/forms/input/select2'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'script-loader' instead of 'script'.
 @ ./src/app/shared/forms/input/select2/select2.directive.ts 17:8-62
 @ ./src/app/shared/forms/input/select2/select2.module.ts
 @ ./src/app/shared/forms/smartadmin-forms-lite.module.ts
 @ ./src/app/shared/smartadmin.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main`
