### ISSUE TITLE
Update node-sass to 4.x to support alpine users

### ISSUE THREAD

**Issue by mrfelton** [angular/angular-cli#3673]
### OS?
Alpine Linux

### Versions.
angular-cli: 1.0.0-beta.22

### Mention any other details that might be useful.

As of node-saas 4.1.0, node-saas now provides a pre-built binary for Alpine Linux. We should update to this version to better support our Alpine user base.

**Comment by filipesilva** [comment]
Would you be interested in opening a PR for it? These two files are the ones you need to update:

- https://github.com/angular/angular-cli/blob/master/packages/angular-cli/package.json
- https://github.com/angular/angular-cli/blob/master/packages/angular-cli/package.json
