### ISSUE TITLE
ng help shows ember as the command instead of ng (Angular CLI 1.0.0-beta.24)

### ISSUE THREAD

**Issue by exequiel09** [angular/angular-cli#3675]
### OS
> macOS 10.12.2
> Node 6.9.2

### Versions.
> 1.0.0-beta.24

### Repro steps.
> Just execute `ng help` and it shows the help list with the `ember` as the command. Previous versions show `ng` instead of `ember`

### The log given by the failure.
> N/A

### Mention any other details that might be useful.

![screen shot 2016-12-21 at 7 11 19 pm](https://cloud.githubusercontent.com/assets/1289472/21387355/3524b516-c7b2-11e6-8cad-e9dd48f8ddb0.png)

**Comment by deecm22** [comment]
I'm seeing the same thing. And when I type ng new test for example, I get the following error: "You cannot use the new command inside an ember-cli project."

ng --version produces:
ng --version
angular-cli: 1.0.0-beta.24
node: 6.9.1
os: darwin x64
@angular/common: 2.2.1
@angular/compiler: 2.2.1
@angular/core: 2.2.1
@angular/forms: 2.2.1
@angular/http: 2.2.1
@angular/platform-browser: 2.2.1
@angular/platform-browser-dynamic: 2.2.1
@angular/router: 3.2.1
@angular/compiler-cli: 2.2.1

ng help produces:

ng help
ember build <options...>
  Builds your app and places it into the output path (dist/ by default).
  aliases: b
  --target (String) (Default: development)
    aliases: -t <value>, -dev (--target=development), -prod (--target=production)
  --environment (String) (Default: )
    aliases: -e <value>
  --output-path (Path) (Default: null)
    aliases: -o <value>
  --watch (Boolean) (Default: false)
    aliases: -w
  --watcher (String)
  --suppress-sizes (Boolean) (Default: false)
  --base-href (String) (Default: null)
    aliases: -bh <value>
  --aot (Boolean) (Default: false)
  --sourcemap (Boolean) (Default: true)
    aliases: -sm
  --vendor-chunk (Boolean) (Default: true)
  --verbose (Boolean) (Default: false)
  --progress (Boolean) (Default: true)
  --i18n-file (String) (Default: null)
  --i18n-format (String) (Default: null)
  --locale (String) (Default: null)

ember completion
  Adds autocomplete functionality to `ng` commands and subcommands

ember doc <keyword>
  Opens the official Angular documentation for a given keyword.

ember e2e
  Run e2e tests in existing project

ember generate <blueprint> <options...>
  Generates new code from blueprints.
  aliases: g
  --dry-run (Boolean) (Default: false)
    aliases: -d
  --verbose (Boolean) (Default: false)
    aliases: -v
  --pod (Boolean) (Default: false)
    aliases: -p
  --classic (Boolean) (Default: false)
    aliases: -c
  --dummy (Boolean) (Default: false)
    aliases: -dum, -id
  --in-repo-addon (String) (Default: null)
    aliases: --in-repo <value>, -ir <value>

ember get
  Get a value from the configuration.

ember help <command-name (Default: all)>
  Shows help for the CLI

ember init <glob-pattern> <options...>
  Creates a new angular-cli project in the current folder.
  aliases: i
  --dry-run (Boolean) (Default: false)
    aliases: -d
  --verbose (Boolean) (Default: false)
    aliases: -v
  --link-cli (Boolean) (Default: false)
    aliases: -lc
  --skip-npm (Boolean) (Default: false)
    aliases: -sn
  --name (String) (Default: )
    aliases: -n <value>
  --source-dir (String) (Default: src)
    aliases: -sd <value>
  --style (String) (Default: css)
  --prefix (String) (Default: app)
    aliases: -p <value>
  --mobile (Boolean) (Default: false)
  --routing (Boolean) (Default: false)
  --inline-style (Boolean) (Default: false)
    aliases: -is
  --inline-template (Boolean) (Default: false)
    aliases: -it

ember lint
  Lints code in existing project

ember new <options...>
  Creates a new directory and runs ng init in it.
  --dry-run (Boolean) (Default: false)
    aliases: -d
  --verbose (Boolean) (Default: false)
    aliases: -v
  --link-cli (Boolean) (Default: false)
    aliases: -lc
  --skip-npm (Boolean) (Default: false)
    aliases: -sn
  --skip-git (Boolean) (Default: false)
    aliases: -sg
  --directory (String)
    aliases: -dir <value>
  --source-dir (String) (Default: src)
    aliases: -sd <value>
  --style (String) (Default: css)
  --prefix (String) (Default: app)
    aliases: -p <value>
  --mobile (Boolean) (Default: false)
  --routing (Boolean) (Default: false)
  --inline-style (Boolean) (Default: false)
    aliases: -is
  --inline-template (Boolean) (Default: false)
    aliases: -it

ember serve <options...>
  Builds and serves your app, rebuilding on file changes.
  aliases: server, s
  --port (Number) (Default: 4200)
    aliases: -p <value>
  --host (String) (Default: localhost) Listens only on localhost by default
    aliases: -H <value>
  --proxy-config (Path)
    aliases: -pc <value>
  --watcher (String) (Default: events)
    aliases: -w <value>
  --live-reload (Boolean) (Default: true)
    aliases: -lr
  --live-reload-host (String) Defaults to host
    aliases: -lrh <value>
  --live-reload-base-url (String) Defaults to baseURL
    aliases: -lrbu <value>
  --live-reload-port (Number) (Defaults to port number within [49152...65535])
    aliases: -lrp <value>
  --live-reload-live-css (Boolean) (Default: true) Whether to live reload CSS (default true)
  --target (String) (Default: development)
    aliases: -t <value>, -dev (--target=development), -prod (--target=production)
  --environment (String) (Default: )
    aliases: -e <value>
  --ssl (Boolean) (Default: false)
  --ssl-key (String) (Default: ssl/server.key)
  --ssl-cert (String) (Default: ssl/server.crt)
  --aot (Boolean) (Default: false)
  --sourcemap (Boolean) (Default: true)
    aliases: -sm
  --vendor-chunk (Boolean) (Default: true)
  --verbose (Boolean) (Default: false)
  --progress (Boolean) (Default: true)
  --open (Boolean) (Default: false) Opens the url in default browser
    aliases: -o
  --hmr (Boolean) (Default: false) Enable hot module replacement
  --i18n-file (String) (Default: null)
  --i18n-format (String) (Default: null)
  --locale (String) (Default: null)

ember set <options...>
  Set a value in the configuration.
  --global (Boolean) (Default: false)
    aliases: -g

ember test <options...>
  Runs your app's test suite.
  aliases: t
  --watch (Boolean) (Default: true)
    aliases: -w
  --code-coverage (Boolean) (Default: false)
    aliases: -cc
  --lint (Boolean) (Default: false)
    aliases: -l
  --single-run (Boolean) (Default: false)
    aliases: -sr
  --progress (Boolean) (Default: true)
  --browsers (String)
  --colors (Boolean)
  --log-level (String)
  --port (Number)
  --reporters (String)
  --build (Boolean) (Default: true)
  --sourcemap (Boolean) (Default: true)
    aliases: -sm

ember version <options...>
  outputs angular-cli version
  aliases: v, --version, -v
  --verbose (Boolean) (Default: false)

**Comment by daco** [comment]
I have the same output, 
daco$ ng help
ember build <options...>
And when I try to ng serve, I get "You have to be inside an ember-cli project in order to use the serve command."
This is after I've upgraded from beta.18 to beta.24

**Comment by CarreraPHP** [comment]
Same happens in windows7 OS. I have submitted a #3687 to fix it.

Below is the output from my Local:

<img width="664" alt="screen shot 2016-12-21 at 11 56 04 pm" src="https://cloud.githubusercontent.com/assets/422070/21401150/201df976-c7d9-11e6-9e01-fe7ac047c9d5.png">

**Comment by CarreraPHP** [comment]
#3688 has the code changes done in #3687(closed) & it has been merged. This issue can be closed.

**Comment by exequiel09** [comment]
Thanks @CarreraPHP. Refer to @CarreraPHP statement above for more information. Closing this issue.

**Comment by nstubi** [comment]
Hi,

Still have the issue: "You have to be inside an ember-cli project in order to use the generate command"

when installing from npm.

Regards,
Nicolas

**Comment by exequiel09** [comment]
@nstubi They have not yet published the version which fixes this. So wait for the next version to be released.

**Comment by nstubi** [comment]
noted @exequiel09, thanks.

**Comment by deecm22** [comment]
Just to be clear, I called out two specific issues in my comment above.  I see a lot of talk about the alias issue being fixed but I do not see this as a technical issue.  The technical issue is that I am getting an error message from the CLI saying that "You cannot use the new command inside an ember-cli project."  I am certain that I am not inside an ember-cli project as I have created a random folder on my desktop and tried running the "ng new test" command and get this specific error.  This does not happen on my windows 8 machine.  Only on my mac.

**Comment by beeman** [comment]
@deecm22 on version 1.0.0-beta.24 creating a new project in an empty folder should just work. If not, could you please create a separate issue with the exact test-steps you take?

Thanks!

**Comment by rajdeep26** [comment]
so when is beta.25 releasing?

**Comment by rajdeep26** [comment]
I'm also facing same error. Getting to see the ember help commans when i type ng help. What is the fix for now? User lower version? If yes, which?

**Comment by beeman** [comment]
@rajdeep26 beta 25 got released today.

**Comment by rajdeep26** [comment]
Thanks @beeman. Will check it out

**Comment by adammendoza** [comment]
Do we need to completely remove the old version or will just upgrade suffice to have a proper working environment?
