### ISSUE TITLE
CSS HMR broken

### ISSUE THREAD

**Issue by scottwio** [angular/angular-cli#3677]
The latest release seems to have broken HMR for CSS with the --hmr flag. Used to work fine in build 22 just upgraded to build 24 and now I have to do full page reloads again.

**Comment by montella1507** [comment]
HMR used to work for me with beta.22 from start, but then (maybe because lazy loaded routes) it stopped working and had to reload everytime entire page :-/

**Comment by ghidoz** [comment]
The same for me :/

**Comment by filipesilva** [comment]
Heya can you post a detailed repro? If code changes are needed please make a repo for it to make it easier.

**Comment by montella1507** [comment]
@filipesilva  i would try to prepare minimal repro.

**Comment by scottwio** [comment]
I tired to reproduce this in a new project and could not. I think it was something wrong with the project I was working on. To fix it I created and new project and copied all the dependencies from the fresh package.json into my project and then reinstall node_modules.

**Comment by scottwio** [comment]
Repo steps below

### OS?
Mac OSX Sierra 

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.9.1
os: darwin x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2

### Repro steps.
1) Create a new project 
`$ ng new [my-porject] --style=scss`
2) Run the server
`$ ng serve --hmr`
3) Open http://localhost:4200/ in the browser
4) edit and save src/styles.scss I changed the background-color
```
body{
  background-color: blue;
}
```
5) Scss changes will not appear in the browser until you do a full reload. In previous versions of angular-cli the changes would be injected. 

### Mention any other details that might be useful.
v1.0.0-beta.24 -Broken
v1.0.0-beta.22-1 - Working

**Comment by scottwio** [comment]
This seems to be fixed in 1.0.0-beta.25.5

**Comment by filipesilva** [comment]
It was fixed in https://github.com/angular/angular-cli/pull/3943, released in 25.5.
