### ISSUE TITLE
Add .log to .gitignore

### ISSUE THREAD

**Issue by tzachov** [angular/angular-cli#3686]
### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.9.1
os: win32 x64
@angular/common: 2.4.0
@angular/compiler: 2.4.0
@angular/core: 2.4.0
@angular/forms: 2.4.0
@angular/http: 2.4.0
@angular/platform-browser: 2.4.0
@angular/platform-browser-dynamic: 2.4.0
@angular/router: 3.1.2
@angular/compiler-cli: 2.4.0

### Mention any other details that might be useful.
A file name debug.log is created and in use so git actions fails.
This file should not be under source control anyway so ignoring it is a good solution.

**Comment by hansl** [comment]
The CLI doesn't create `.log` files. If your environment creates those you should check your tooling.
