### ISSUE TITLE
ng generate route issue: angular-cli.json file missing

### ISSUE THREAD

**Issue by damianmk** [angular/angular-cli#369]
I have a strange issue with using generator for routes.
I am following all steps to generate a new route in my blank angular2 project.
Having generated the project and nothing else I am typing:
ng g route hero

What I get is some silly reference to a supposedly missing file angular-cli.json
Now I absolutely cannot find any "how-to" related to this file.
So what gives?
How do I generate this file?
Do I actually need it?
Is this a bug or a feature?

Please look into it or update readme accordingly.

Thanks,
Damian

**Comment by Brocco** [comment]
I will be updating the templates associated to routes within the next week which will resolve the issue you are seeing. I am closing this issue and you can track that progress via #316
