### ISSUE TITLE
Force reload JSON configs.

### ISSUE THREAD

**Issue by HFTSOL** [angular/angular-cli#3692]
Apologies if this isn't the place for this question, but I have searched for 20 minutes and can't seem to find anything related...

When running the dev server (ng serve), is there a way to force reload the configs (angular-cli.json) without stop/start the server?

Thanks.

**Comment by hansl** [comment]
No unfortunately. We do a lot before even starting the compilation and detecting a change on that file (or `tsconfig.json`) requires restarting the whole process.
