### ISSUE TITLE
ng help display ember instead of ng

### ISSUE THREAD

**Issue by alyahmedaly** [angular/angular-cli#3697]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows10

### Versions.
>angular-cli: 1.0.0-beta.24
node: 6.9.2
os: win32 x64
@angular/common: 2.4.0
@angular/compiler: 2.4.0
@angular/core: 2.4.0
@angular/forms: 2.4.0
@angular/http: 2.4.0
@angular/platform-browser: 2.4.0
@angular/platform-browser-dynamic: 2.4.0
@angular/router: 3.4.0
@angular/compiler-cli: 2.4.0

### Repro steps.
> ng help
sample of result
ember build <options...>
Builds your app and places it into the output path (dist/ by default).
ember completion
Adds autocomplete functionality to ng commands and subcommands
ember doc 
Opens the official Angular documentation for a given keyword.
ember e2e
Run e2e tests in existing project

**Comment by thierabsy** [comment]
I have the same issue in window 8 64bit
![ng help issue](https://cloud.githubusercontent.com/assets/17255107/21428726/6201dcac-c853-11e6-92a0-ea5430d0e80d.PNG)

**Comment by hansl** [comment]
Fixed in https://github.com/angular/angular-cli/pull/3688, will be published with the next version.
