### ISSUE TITLE
Module not found: Error: Can't resolve 'PouchDB'

### ISSUE THREAD

**Issue by aralroca** [angular/angular-cli#3698]
### OS?
> Linux (Amazon Linux AMI)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

    angular-cli: 1.0.0-beta.22-1
    node: 6.6.0
    os: linux x64

### Repro steps.

I installed recently PouchDB:

    npm i pouchdb --save
    npm i @types/pouchdb --save-dev

I added this in **typings.d.ts**:

    declare module 'PouchDB';

And now I import PouchDB in my service:

    import * as PouchDB from 'PouchDB';

Well, all is okey in my laptop (MacOS Sierra); `ng serve`, `ng build` without problems and PouchDB is working well.

But... Not the same thing in my server (Amazon Linux AMI)... 😐  

I'm getting the next error trying to execute `ng build`:

    ERROR in ./src/app/pictures.service.ts
    Module not found: Error: Can't resolve 'PouchDB' in '/home/aral/project/src/app'
     @ ./src/app/pictures.service.ts 11:0-35
     @ ./src/app/app.module.ts
     @ ./src/app/index.ts
     @ ./src/main.ts
     @ multi main

I have the same angular-cli version and node version that in my laptop... 😧 

And I compared doing `tree` command in my laptop and my server and both have the same files. (Except some sub-dependency in `node_modules`).

*Thank you!*

**Comment by vapits** [comment]
Make sure that you have correct paths and follow the rules of the latest version like:
* Same folder files path always start with `./`
* Import of app.module should be like `<path>/app/app.module/` and not `<path>/app/` etc

**Comment by aralroca** [comment]
@vapits I have all the paths with `./` because I started the project directly with `1.0.0-beta.22-1` and not from a previous version, and in my laptop is working well, only have this issue in my server. If was a problem with paths, in my laptop should be the same error, wasn't it? 🤔  

And the error is:

    Module not found: Error: Can't resolve 'PouchDB'

Can't resolve 'PouchDB', not a path. Thank for helping!

**Comment by hansl** [comment]
Are you using a Mac?  The Mac main filesystem is case insensitive. Linux is not so forgiving. So when you're import from `PouchDB` the system is looking for a node_modules names `PouchDB`, but it's really named `pouchdb` (lowercase). Try it out.

Closing this but you're welcome to reopen it if that doesnt solve your problem.

**Comment by aralroca** [comment]
@hansl just this. Thank you so much!
