### ISSUE TITLE
command "npm install -g angular-cli" is not working

### ISSUE THREAD

**Issue by sireendra** [angular/angular-cli#3703]
Hi,

The command "npm install -g angular-cli" is not working for me. I am getting below error. Can anyone help me to solve this.

D:>npm install -g angular-cli
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.9.2
npm ERR! npm v3.10.9
npm ERR! code E404
npm ERR! 404 no such package available : @angular-cli/ast-tools
npm ERR! 404
npm ERR! 404 '@angular-cli/ast-tools' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular-cli'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! Please include the following file with any support request:
npm ERR! D:\npm-debug.log

**Comment by CanKattw** [comment]
Works for me. Clean npm cache and try https://github.com/angular/angular-cli/issues/2150#issuecomment-256257770

**Comment by clydin** [comment]
My guess is that your environment blocks scoped packages.

**Comment by filipesilva** [comment]
Yeah what @clydin says is the most probable cause. You're probably using a private npm server or a proxy.
