### ISSUE TITLE
in 1.0.0-beta.24 getting lazy load error: ERROR in Could not resolve "./...

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#3705]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10 64

### Versions.
latest ng 2.4.1 and latest cli .24

### repo:
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink

ng-cli: ```ERROR in Could not resolve "./comps/app1/lazyone/index" from "C:/msweb/Angular-kitchen-sink/src/app/app.module.ts".1```

Using latest ng-cli I am getting lazy load router error as seen above.
This was not the case in 1.22 and let me add that even with the error, lazy loading still works.
This is how my router is configured:
```
}, {
        path: 'LazyLoad',
        loadChildren: './comps/app1/lazyone/index#MessagesModule'
    }, {
```

and to see full:
https://github.com/born2net/Angular-kitchen-sink/blob/master/src/App.routes.ts

**Comment by AlanChauchet** [comment]
Exactly the same for me. Was using cli .19-3 but now that I have updated nothing seems to work. Even with an whole new angular cli project + my old src files

**Comment by lichenbuliren** [comment]
I have the same problem，
I just update my cli from beta.19 to beta.24 todoay, and then my lazy load module doesn't works, but it works well in beta.19

here is my code

app-routing.module.ts
``` ts
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { IndexComponent } from "./index/index.component";

export const routes: Routes = [
  { path: '', redirectTo: 'index', pathMatch: 'full' },
  { path: 'index', component: IndexComponent, data: { title: '我要维修' } },
  { path: 'delivery', loadChildren: 'app/modules/delivery/delivery.module#DeliveryModule' },
  { path: 'home', loadChildren: 'app/modules/home/home.module#HomeModule' },
  { path: 'order', loadChildren: 'app/modules/order/order.module#OrderModule' },
  { path: '**', redirectTo: 'index' }
]

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

`AppModule.ts`

``` ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { CoreModule } from './core/core.module';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    CoreModule,
    AppRoutingModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}

```

**Comment by AlanChauchet** [comment]
Hi @lichenbuliren , Looks like the path recognition have changed a bit and you should now use './modules/delivery/delivery.module#DeliveryModule' instead of 'app/modules/delivery/delivery.module#DeliveryModule' (same goes for the other lazy modules). Hope that helps !

**Comment by lichenbuliren** [comment]
@AlanChauchet ,yeah it works , thank you very much!

**Comment by filipesilva** [comment]
@born2net I don't know why you're getting that error. If you can get me a simpler repro I can investigate.

**Comment by born2net** [comment]
closing as not repr now

**Comment by tsm91** [comment]
it breaks if u do

```
@NgModule({
  imports: [RouterModule.forRoot(routes, {useHash: true, preloadingStrategy: PreloadAllModules})],
  exports: [RouterModule]
})
export class AppRoutingModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: AppRoutingModule,
      providers: [
        {provide: AuthGuard, useClass: AuthGuard}
      ]
    };
  }
}
```

it works if u do 

```
@NgModule({
  imports: [RouterModule.forRoot(routes, {useHash: true, preloadingStrategy: PreloadAllModules})],
  exports: [RouterModule],
  providers: [
    {provide: AuthGuard, useClass: AuthGuard}
  ]
})
export class AppRoutingModule {
}
```

at least for me on beta 24

**Comment by cgebe** [comment]
path changed resolved the problem for me! Thanks to @AlanChauchet

**Comment by pengzhuoxu** [comment]
@AlanChauchet Thanks.
