### ISSUE TITLE
Feature Request: Generate directives with ElementRef already imported or add it as an option to the command

### ISSUE THREAD

**Issue by baruchvlz** [angular/angular-cli#3710]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Not Applicable

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

Not Applicable

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Make:  `ng g d some-directive-name` or `ng g d some-directive-name --eleref=true` generate the following
```typescript
import { Directive, ElementRef } from '@angular/core';

@Directive({
  selector: '[appSomeDirectiveName]'
})
export class SomeDirectiveNameDirective {

  constructor(
    public eleRef: ElementRef
  ) {  }

}
```

### The log given by the failure.
> Normally this include a stack trace and some more information.

Not applicable.

### Mention any other details that might be useful.
Not applicable.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
This doesn't strike me as something super important tbh. It's trivial to add that code.
