### ISSUE TITLE
listLazyRoutes  is now undefined did something change

### ISSUE THREAD

**Issue by SteveStrong** [angular/angular-cli#3714]
> Please provide us with the following information:
> ---------------------------------------------------------------

![image](https://cloud.githubusercontent.com/assets/500861/21447317/0c1d5e30-c8a1-11e6-8a02-3f046604070e.png)

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jopitan** [comment]
Good thing I'm not the only one. Just created a new project with "ng new [project_name]" and tried "ng build" immediately. Gave me the error on a completely new project.

**Comment by gotik** [comment]
@hansl https://github.com/angular/angular/commit/7256d0ede5fbfda5d22cdf09efac5c1a22007da7 (the change that added support to `__NGTOOLS_PRIVATE_API_2.listLazyRoutes` and `__NGTOOLS_PRIVATE_API_2.codeGen`) didn't make it into the @angular/compile-cli version 2.3.x ([~2.3.1](https://github.com/angular/angular-cli/commit/bd0310095a71799588523eecbec7fe38e9f63020#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R46)), also, it seems like it only made into the 4.0.0-beta.1 version

2.3.1, 2.4.0-marker, 2.4.0, [2.4.1](https://github.com/angular/angular/compare/2.4.1...master) all those versions lack the needed [commit](https://github.com/angular/angular/commit/7256d0ede5fbfda5d22cdf09efac5c1a22007da7) (Commits on Dec 13, 2016)

I looked into the https://github.com/angular/angular/releases I could be wrong if those are not in sync with npm's releases.

**Comment by filipesilva** [comment]
Seems to be fixed now.
