### ISSUE TITLE
Can't generate inside module folder

### ISSUE THREAD

**Issue by Sakuto** [angular/angular-cli#3719]
I'm working with an Angular 2 application based on Angular-CLI skeleton, I had the habit of structuring my src folder with one directory by module, and each component related to this module in the same folder.

    src
    	app
    		documents
    			document-list.component.ts
    			document-list.component.html
    			documents.component.ts
    			documents.component.html
    			document.module.ts
    		app.component.ts
    		app.module.ts
    	main.ts	

Now that I'm using Angular-CLI, I would like to take profit of each feature, but when I'm generating a new component, no matter what, it keep creating a new folder for my component when I just want to put it inside the related folder.

    src
    	app
    		documents
    			document-list
    				document-list.component.ts
    				document-list.component.html
    			documents.component.ts
    			documents.component.html
    			document.module.ts
    		app.component.ts
    		app.module.ts
    	main.ts	

Is it possible to keep my previous structure, is it a bad practice? The guideline recommends to avoid useless directory depth so I'm kind of disturbed.

**Comment by delasteve** [comment]
Generally, the default way the CLI creates components is what the style guide suggests, as found here: https://angular.io/styleguide#!#04-06.

If you want your old structure, though, when you generate a component use the `--flat` flag. 

This should work... `ng g c documents/document-list --flat`

**Comment by filipesilva** [comment]
Great answer by @delasteve, cheers!
