### ISSUE TITLE
how can apply 4.0.0-beta?

### ISSUE THREAD

**Issue by goldenbearkin** [angular/angular-cli#3720]
angular-cli: 1.0.0-beta.24
node: 6.9.1
os: darwin x64
@angular/common: 4.0.0-beta.1
@angular/compiler: 4.0.0-beta.1
@angular/core: 4.0.0-beta.1
@angular/flex-layout: 2.0.0-beta.0
@angular/forms: 4.0.0-beta.1
@angular/http: 4.0.0-beta.1
@angular/material: 2.0.0-beta.0
@angular/platform-browser: 4.0.0-beta.1
@angular/platform-browser-dynamic: 4.0.0-beta.1
@angular/router: 3.4.1
@angular/compiler-cli: 4.0.0-beta.1

Run 'ng serve' yields
````
This version of CLI is only compatible with angular version 2.3.1 or better. Please
upgrade your angular version, e.g. by running:

npm install @angular/core@latest
````

**Comment by rdrrichards** [comment]
Just tried this a minute ago, same issue. Rolled back to cli 1.0.0-beta.21 to get ng serve to work with 4.0.0-beta.1.

**Comment by xgqfrms-GitHub** [comment]
# the ng2-cli need to be update sync with the ng2 4.x!

**Comment by abdulhaq-e** [comment]
I have submitted a PR that should fix this error. However, other things that I may not be aware of may need to be changed for V4.

**Comment by JohannesHoppe** [comment]
I created a small fork for very impatient people:
https://github.com/angular-buch/angular-cli-ng4

It includes the required fix and has an updated `ng new` blueprint, too.
