### ISSUE TITLE
"Updating angular-cli" instructions in docs do not work on Windows

### ISSUE THREAD

**Issue by jongunter** [angular/angular-cli#3721]
### OS?
Windows 8

### Repro steps.
Per your documentation, tried to run:
```
rm -rf node_modules dist tmp
```

### The log given by the failure.
```
'rm' is not recognized as an internal or external command,
operable program or batch file.
```

### Mention any other details that might be useful.
`rm -rf` is not a windows command. Yeah, most of us are smart enough to figure out we should use `rmdir ` instead, but you still might want to add a note to the docs.

**Comment by baruchvlz** [comment]
You need to use the bash terminal and not the command prompt. To remove a folder using the command prompt use `rmdir FOLDERNAME /s`.

**Comment by filipesilva** [comment]
Good point. Would you be willing to make a PR for that? Maybe saying
```
rm -rf node_modules dist # use rmdir on Windows
```
(tmp is also not needed anymore)
