### ISSUE TITLE
ng-annotation support planned/wanted?

### ISSUE THREAD

**Issue by Itrulia** [angular/angular-cli#3722]
For those who don't know what [ng-annotate](https://github.com/olov/ng-annotate) is: ng-annotate is a library for Angular 1.x that allows you to minify your Code without using the array syntax or without adding `ctrl.$inject = [..]`. 

# Motivation for or Use Case

Since the majority of Angular applications are built with the version 1 I guess a lot of people want to migrate their Angular application with `@angular/upgrade`. Since AoT/Tree shaking is really important for Angular applications many people upgrading their 1.x projects would love to use angular-cli. We (ESL or also known Electronic Sport League) would love to use the angular-cli in the future.

If the general census is yes that you want to support it, I could implement it if you want.

**Comment by hansl** [comment]
We do not officially support Angular 1 ng-updrade apps, but some people have had success stories with it. Unfortunately, this will not be supported by the CLI as it's a small use case, already have a work around (run ng-annotate on your files and save them to your git repo), and it would require a lot of work to make sure we don't mess with Angular 2 apps in general.

That would be a good idea for addons, but those are planned for Q2 of 2017. In the meantime, I suggest you save your Angular 1 files with the annotations in them.

Alternatively, you can use your own webpack config with the `@ngtools/webpack` plugin to support AOT.
