### ISSUE TITLE
Test Results Cut Off in Some Terminals

### ISSUE THREAD

**Issue by jongunter** [angular/angular-cli#3725]
### OS?
Windows 8

### Versions.
angular-cli: 1.0.0-beta.19-3
node: 6.3.0
os: win32 x64

### Repro steps.
1. Run `ng test` on an unfortunate project that has 27 failing unit tests
2. You will not be able to see the errors associated with your first few tests, as the Windows Command Prompt truncates its output history after a certain number of lines

### Mention any other details that might be useful.
I've  implemented `karma-jasmine-html-reporter` into my CLI projects to solve the above problem. This allows me to view the test results in a nice UI inside a web browser. Since I'm not likely the only `angular-cli` user on Windows, maybe we could implement a similar HTML reporter the CLI by default?

Also, the terminal, in general, is a poor user interface for viewing test results.  Something HTML-based would be much better.

**Comment by gelliott181** [comment]
Windows 10 over here. The Command Prompt can be swapped for PowerShell just fine. PowerShell doesn't truncate. Using the newer console interface solves the cut off bit.

Then we get to the reporter bit. It seems you want to cater the CLI to your workflow, and you've done so by installing a package that fits your needs. I don't need that package and it's unnecessary to use the CLI's features. I'm happy to see results in a CLI and my Jenkins server takes JUnit XML. What makes your fancy HTML reporter so much more important than my disk space? Why don't we have an JUnit reporter installed by default too?

We both have valid opinions about how we expect our test results to be displayed, and many others have even more diverse opinions. I don't believe the CLI should integrate anything more than the bare minimum when the effects only make the workflow more opinionated.

**Comment by jongunter** [comment]
Thank you for that tip! I didn't realize PowerShell didn't truncate.

I just discovered that, on MacOS, the WebStorm terminal truncates, as does iTerm, but not the built-in terminal. While I understand the CLI shouldn't have to cater to every developer's unique workflow, these terminals are both tools that *many people* working on Angular2 projects use.

**Comment by filipesilva** [comment]
Well that's true of many commands with a long output. It's not something I'm too concerned about because you can still customise the karma output. It's also preferable to default to the simplest possible setup because it will be the most familiar.

Also, personally speaking, whenever I have a lot of errors in unit tests I just assume some are duds and I should focus on solving them bit by bit, and by the time I'm done with a couple then the rest will also be gone.
