### ISSUE TITLE
Changing the project prefix still leads to the creation of new components in the src/app folder

### ISSUE THREAD

**Issue by madoar** [angular/angular-cli#3728]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux Mint 18.1

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.24
node: 4.2.6
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

marc@marc-desktop ~/WebstormProjects $ ng new ng2-wizard --prefix=components

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
marc@marc-desktop ~/WebstormProjects $ ng new ng2-wizard --prefix=components
installing ng2
  create .editorconfig
  create README.md
  create src/app/app.component.css
  create src/app/app.component.html
  create src/app/app.component.spec.ts
  create src/app/app.component.ts
  create src/app/app.module.ts
  create src/assets/.gitkeep
  create src/environments/environment.prod.ts
  create src/environments/environment.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/polyfills.ts
  create src/styles.css
  create src/test.ts
  create src/tsconfig.json
  create angular-cli.json
  create e2e/app.e2e-spec.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tslint.json
Successfully initialized git.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
```

### Mention any other details that might be useful.

My understanding of the --prefix argument is, that through it I can set the foldername inside the src folder where the source files will be saved. Which means that I would expect the AppComponent to be created in `src/components/` and not in `src/app`. 
Is my understanding of the --prefix argument for the `ng new` command wrong, or is this a bug that the components aren't created in `src/components/`?

In addition, when I create a new test component with `ng g c Test --flat` I get the following output:

```
marc@marc-desktop ~/WebstormProjects/ng2-wizard/src/components $ ng g c Test --flat
installing component
  create src/app/test.component.css
  create src/app/test.component.html
  create src/app/test.component.spec.ts
  create src/app/test.component.ts
  update src/app/app.module.ts
```

Here I would also expect that the newly created test component would be created inside the components folder instead of the app folder. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
The prefix option changes the default selector prefix.  It doesn't affect the folder structure.

**Comment by madoar** [comment]
Thanks for the answer. 
I would be interested in changing the folder structure, is there a way to do this?
In addition it would be helpful to change the default module name. After generating a new project with angular-cli it's always called AppModule, which is not always the most fitting module name for a project. Can I change the module name too? If yes, how?

**Comment by delasteve** [comment]
The only thing you can currently change is the root directory. That's found in the `angular-cli.json` folder. The resulting structure would be `src/components/app`. This is in part due to the styleguide which this CLI tries it's best to follow. https://angular.io/styleguide#!#04-06

**Comment by clydin** [comment]
Not currently unfortunately.  It looks like your trying to make a component library.  The CLI is really geared towards apps right now so it is probably not the best choice if that is the case.

**Comment by madoar** [comment]
Thanks for you answers!

@clydin You're right, currently I'm writing a component library. I would like to use angular-cli for the component library too, because it makes creation of new components and directives quite easy. What I think is really strange about the generate command of angular-cli is, that it totally ignores your current folder. If you're inside the folder `src/components` and use `ng g c ./Test --flat` it still generates the component inside `src/app`.

@delasteve Thanks for the link to the angular 2 styleguide. What I think is strange is that the given example structure doesn't contain a `src` folder. The app folder is a direct childfolder unter the project root folder. 
About the name change of the AppModule: How do I do this? As far as I understand angular 2 a normal rename of the files shouldn't be enough, especially when commands like `ng generate` make modifications inside the `app.module.ts` file.

**Comment by delasteve** [comment]
To better organize the folders, the CLI project is broken up into essentially two roots. One being the node/cli root (what you are thinking of). This contains all the git, node, cli, etc information to *make your project run*. The other root is the project root (`src`). This contains all the html, css, and ts that *is your project*.

As for the rename, do the following (assuming no routing module):
- Rename `src/app/app.module.ts` -> `src/app/foo.module.ts`
- In `src/app/foo.module.ts`, change `export class AppModule { }` -> `export class FooModule { }`
- In `src/main.ts`, change `import { AppModule } from './app/app.module';` -> `import { FooModule } from './app/foo.module';`
- In `src/main.ts`, change `platformBrowserDynamic().bootstrapModule(AppModule);` -> `platformBrowserDynamic().bootstrapModule(FooModule);`

**Comment by filipesilva** [comment]
I think @clydin and @delasteve already answered almost everything, but I'd also like to mention that you can also do `ng new project-name --source-dir=something` to have everything created in `something/` instead of `src/`:

```
kamik@T460p MINGW64 /D/sandbox
$ ng new project-name --source-dir=something
installing ng2
  create .editorconfig
  create README.md
  create something\app\app.component.css
  create something\app\app.component.html
  create something\app\app.component.spec.ts
  create something\app\app.component.ts
  create something\app\app.module.ts
  create something\assets\.gitkeep
  create something\environments\environment.prod.ts
  create something\environments\environment.ts
  create something\favicon.ico
  create something\index.html
  create something\main.ts
  create something\polyfills.ts
  create something\styles.css
  create something\test.ts
  create something\tsconfig.json
  create angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tslint.json
```

**Comment by filipesilva** [comment]
Ah and about the generation not taking into account the folder, that seems to be a bug: https://github.com/angular/angular-cli/issues/3570
