### ISSUE TITLE
ng new [app_name] within another app shows ember messaging

### ISSUE THREAD

**Issue by evasilevsky** [angular/angular-cli#3731]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.24
node: 6.9.2
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
This error happened creating a new app inside an existing app. 

### The log given by the failure.
> Normally this include a stack trace and some more information.
You cannot use the new command inside an ember-cli project. 

### Mention any other details that might be useful.
I'm only asking you change the messaging from ember-cli to angular-cli. 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Equinox** [comment]
[This PR](https://github.com/angular/angular-cli/pull/3726/files) seems to be related.

**Comment by doubleUTF** [comment]
Does this have anything to do with running 'ng help' showing ember messages as well? I'm confused since I thought I downloaded angular-cli only to see ember commands.

**Comment by baruchvlz** [comment]
@doubleUTF Angular CLI is built on top of Ember CLI.

**Comment by doubleUTF** [comment]
@baruchvlz Right, but if I'm using it in an Angular environment, I shouldn't expect to see ember commands(ember build, ember lint, ember init, etc.) when I hit 'ng help' . If I tried to enter any of them, they would all fail in the Angular environment. Check out the screenshots:
![ng version](https://cloud.githubusercontent.com/assets/17230520/21473077/0cd52916-caae-11e6-8e5c-4e5174dec076.JPG)
![ng help](https://cloud.githubusercontent.com/assets/17230520/21473078/0e9eb118-caae-11e6-8059-3ddd476309c9.JPG)

**Comment by exequiel09** [comment]
Reported also on #3675

**Comment by doubleUTF** [comment]
@exequiel09 Thank you sir.

**Comment by hansl** [comment]
This is temporary, we found the issue and corrected it in master. It will be fixed in beta 25. Sorry for the inconvenience.

**Comment by obkalu** [comment]
Awesome! Thanks hansl.
