### ISSUE TITLE
ng new with empty prefix produces wrong tags

### ISSUE THREAD

**Issue by Dgiulian** [angular/angular-cli#3732]
When creating a new app with an empty prefix
`ng new myApp --prefix ""`

the CLI creates the root container as follows
```
<body>
  <-root>Loading...</-root>
</body>
```
when it should be without the dash
```
<body>
  <root>Loading...</root>
</body>
```

the selector of the app.component is also "-root" which is not valid.

### OS?
 > Windows 7
### Versions.

>angular-cli: 1.0.0-beta.22-1
>node: 7.1.0
>os: win32 x64

### Repro steps.
> the app was created using CLI

**Comment by superdyzio** [comment]
Shouldn't it create root container with default prefix value?
```
<body>
  <app-root>Loading...</app-root>
</body>
```
