### ISSUE TITLE
ng help is displaying info about ember commands instead in angular-cli version 1.0.0-beta.24 

### ISSUE THREAD

**Issue by obkalu** [angular/angular-cli#3738]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10. 

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.22-1
node: 6.9.1
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
I simply updated angular-cli from version 1.0.0-beta.22-1 to the latest (version 1.0.0-beta.24) and when I ran 'ng help', the output displays info about ember commands instead in angular-cli's, ng commands. So, I promptly reverted by to version 1.0.0-beta.22-1 . 

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by baruchvlz** [comment]
More here: https://github.com/angular/angular-cli/issues/3731#issuecomment-269139876

**Comment by exequiel09** [comment]
Reported also on #3675

**Comment by Splaktar** [comment]
This issue should be closed since this is fixed in master and [will be in beta.25](https://github.com/angular/angular-cli/issues/3731#issuecomment-269414546).

**Comment by obkalu** [comment]
Great! Thanks.
