### ISSUE TITLE
Package install failed, when ng new newApp

### ISSUE THREAD

**Issue by shengqiu** [angular/angular-cli#3739]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> aws redhat

### Versions.
> 
angular-cli: 1.0.0-beta.24
node: 6.9.2
os: linux x64

### Repro steps.
> failure after run this command:
ng new newApp

### The log given by the failure.
> 
Installing packages for tooling via npm.

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

Package install failed, see above.

**Comment by baruchvlz** [comment]
Those warnings don't mean the packages weren't install, can you verify that after running `ng new newApp` the folder `node_modules` is not created?

**Comment by shengqiu** [comment]
No when I run ng serve it will return error                                                                                                                                                                        Sent from my BlackBerry - the most secure mobile device - via the Bell Network                                                                                                                                                                            From: notifications@github.comSent: December 25, 2016 7:53 PMTo: angular-cli@noreply.github.comReply-to: reply@reply.github.comCc: shengqiu.purdue@gmail.com; author@noreply.github.comSubject: Re: [angular/angular-cli] Package install failed, when ng new newApp (#3739)  Those warnings don't mean the packages weren't install, can you verify that after running ng new newApp the folder node_modules is not created?

**Comment by Equinox** [comment]
What error does it return?

**Comment by hansl** [comment]
@shengqiu Need more information. What error?

**Comment by filipesilva** [comment]
Closing as inactive.
