### ISSUE TITLE
the folder assets and the favicon.ico are not presents when using angular-cli locally 

### ISSUE THREAD

**Issue by drtapha** [angular/angular-cli#3740]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX (Sierra)

### Versions.
> 1.0.0-beta.24

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I'm sorry but I don't understand what you mean and you really didn't bother filling in the template either, so I'm closing. Feel free to open a new issue with a filled template.
