### ISSUE TITLE
ability to specific module or module dir as flag for cli create

### ISSUE THREAD

**Issue by biggiesmallsAG** [angular/angular-cli#3746]
angular-cli: 1.0.0-beta.24
node: 7.2.1
os: darwin x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

________________________________________

Because ive nested modules and folders that house each component/service/module etc, if i initiate a;

```
ng g c testcomponent 
```

it fails because it cant find app.module in the root of the application. It should be flag specified as to what module you want to load the component (or any ng generate performed), i nest the modules to decouple many aspects of my application and the app.module is really just the bind for all my modules (not components). What is the chance of getting this fixed in upcoming release?

Ive tested it with app.module in the app/, works fine. I think there should be more flexibility in generating the moving parts of the application specific to where you want to house them. The same should go for generating the styles/templates as again these are housed in their respective folders. I guess the other side of the coin is to let cli generate your app for you in the default way and then move component declarations to the corresponding modules but that seems counter intuitive to me.

**Comment by beeman** [comment]
Hi @biggiesmallsAG,

When generating components you can specify in which module you like them to appear.

For example: 

```
$ ng g m messages
installing module
  create src/app/messages/messages.module.ts

$ ng g c messages/list
installing component
  create src/app/messages/list/list.component.ts
  update src/app/messages/messages.module.ts

$ ng g c messages/view
installing component
  create src/app/messages/view/view.component.ts
  update src/app/messages/messages.module.ts
```
And you can even go further in-depth:

```
$ ng g c messages/list/item
installing component
  create src/app/messages/list/item/item.component.ts
  update src/app/messages/messages.module.ts

$ ng g c messages/list/item/date
installing component
  create src/app/messages/list/item/date/date.component.ts
  update src/app/messages/messages.module.ts
```

**Comment by filipesilva** [comment]
Thanks for the answer @beeman!
