### ISSUE TITLE
rename index.html will lead that the app is not available

### ISSUE THREAD

**Issue by MienDev** [angular/angular-cli#3748]
IMHO, the index file for the app is configurable,  and a file named such as `main.html` can be used if the value for `index` in `angular-cli.json` is given.
however, rename index.html file will lead that the app is not available after I upgrade the angular-cli to beta.24.  (while working well in beta.18)

> --------------------------------------------------------------

### OS?
> windows 10

### Versions.
>angular-cli: 1.0.0-beta.24
>node: 6.5.0
> os: win32 x64
> @angular/common: 2.4.1
> @angular/compiler: 2.4.1
> @angular/compiler-cli: 2.4.1
> @angular/core: 2.4.1
> @angular/forms: 2.4.1
> @angular/http: 2.4.1
> @angular/platform-browser: 2.4.1
> @angular/platform-browser-dynamic: 2.4.1
> @angular/platform-server: 2.4.1
> @angular/router: 3.4.1

### Repro steps.
> 1. ng init  ( npm install)
> 2. rename file `index.html` to `main.html`
> 3. change the value of `index` key to `main.html`
> 4. ng serve (build ok)
> 5. visit the default url (http://localhost:4200)

```
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "main.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ]
```

### The log given by the failure.
> page shows "Cannot GET /"
> http status code is "404"

### Mention any other details that might be useful.
> when switch angular-cli to version `beta.18`, everything goes smoothly.

> ---------------------------------------------------------------

**Comment by Besendorfer** [comment]
Also having this issue.

**Comment by filipesilva** [comment]
Older versions had the output hardcoded to always be `index.html`, but we fixed that in https://github.com/angular/angular-cli/pull/2767. If you use a different name for index, it will be output with that name. That is by design.

**Comment by Besendorfer** [comment]
I think the issue is that if you change the name of `index.html` to be something else, webpack-dev-server doesn't recognize that the new .html/.htm file should be served instead. 

For example, I changed the name to be `default.htm`, went to http://localhost:4200, and received the error "Cannot GET /". Going to http://localhost:4200/default.htm works just fine though. So the server isn't recognizing the change. Is this desired behavior?

**Comment by MienDev** [comment]
@Besendorfer  yeah, exactly,  that is what I wanna to say. 

@filipesilva Maybe, you misunderstand this issue, also plz refer to @Besendorfer 's words.

Issue can be easily reproduced by steps provided.

**Comment by filipesilva** [comment]
Ok I understand better now. I understood the reproduction but mostly thought that it was ok that you'd go manually to `http://localhost:4200/default.htm` yourself, since you changed it.

But defaulting to a particular file is important, especially for refreshes.
