### ISSUE TITLE
ng serve fails at 15% building

### ISSUE THREAD

**Issue by AmithMendis** [angular/angular-cli#3750]
### OS?
os: win32 x64

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.9.2

### Repro steps.
New app created by angular-cli. Didn't done any changes.

### The log given by the failure.
** NG Live Development Server is running on http://localhost:4200. **
 15% building modules 46/148 modules 102 active ...core-js\modules\es6.array.index-of.js

Can please anyone help me on this? I'm stuck with this.

**Comment by hansl** [comment]
Give it time.

**Comment by AmithMendis** [comment]
@hansl , I didn't stop it. It automatically stopping.  I have tried multiple times and gave hours of time. But it stops at 15%.

**Comment by PG2000** [comment]
@AmithMendis 
Can you try to reload all deps with `npm i`
Can you do a ng version and post the output ?

**Comment by AmithMendis** [comment]
@PG2000
I have tried **npm i**, But it is not working and **ng version** gives following output.

![error](https://cloud.githubusercontent.com/assets/14071021/21594393/11a340ea-d148-11e6-9d83-bc3ac352a01b.PNG)

**Comment by AmithMendis** [comment]
@hansl, @PG2000 

This is the npm-debug.log output for **npm run start** command.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle temwe@0.0.0~prestart: temwe@0.0.0
6 silly lifecycle temwe@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle temwe@0.0.0~start: temwe@0.0.0
8 verbose lifecycle temwe@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle temwe@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\ApitLab\ERP\WebApp\temwe\node_modules\.bin;C:\app\amithm\product\11.2.0\client_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Java\jdk1.8.0_20\bin;C:\Program Files\TortoiseSVN\bin;C:\Python34;C:\Program Files (x86)\Skype\Phone\;C:\SpringRoo\spring-roo-1.3.2.RELEASE\bin;C:\maven\apache-maven-3.3.9\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\amithm\AppData\Roaming\npm
10 verbose lifecycle temwe@0.0.0~start: CWD: E:\ApitLab\ERP\WebApp\temwe
11 silly lifecycle temwe@0.0.0~start: Args: [ '/d /s /c', 'ng serve' ]
12 silly lifecycle temwe@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle temwe@0.0.0~start: Failed to exec start script
14 verbose stack Error: temwe@0.0.0 start: `ng serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid temwe@0.0.0
16 verbose cwd E:\ApitLab\ERP\WebApp\temwe
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error temwe@0.0.0 start: `ng serve`
22 error Exit status 1
23 error Failed at the temwe@0.0.0 start script 'ng serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the temwe package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ng serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs temwe
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls temwe
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**package.json** file is like this

{
  "name": "temwe",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.24",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3"
  }
}

**Comment by Toxicable** [comment]
Are you still getting this error on the latest version?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
