### ISSUE TITLE
ERROR in multi styles

### ISSUE THREAD

**Issue by keithmichelson** [angular/angular-cli#3757]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.24
node: 5.1.1
os: darwin x64
@angular/common: 2.3.1
@angular/compiler: 2.3.1
@angular/core: 2.3.1
@angular/forms: 2.3.1
@angular/http: 2.3.1
@angular/platform-browser: 2.3.1
@angular/platform-browser-dynamic: 2.3.1
@angular/router: 3.3.1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Updated cli from 14 to the 24
fixed any issues with ng-init
added this in angular-cli
"styles": [
       "../node_modules/bootstrap/dist/css/boootstrap.css",
       "styles.scss"
     ]

### The log given by the failure.
> Normally this include a stack trace and some more information.

ERROR in compiler_1.StaticSymbolResolver is not a function

ERROR in multi styles
Module not found: Error: Can't resolve '/Users/jl/Documents/w/flan/node_modules/bootstrap/dist/css/boootstrap.css' in '/Users/jl/Documents/w/flan'
@ multi styles

### Mention any other details that might be useful.
also ran into problems when running
npm install bootstrap@4.0.0-alpha.5 --save
├── UNMET PEER DEPENDENCY @angular/compiler@2.3.1
├── UNMET PEER DEPENDENCY @angular/core@2.3.1
├── bootstrap@4.0.0-alpha.5
└── UNMET PEER DEPENDENCY rxjs@5.0.1

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@keithmichelson I think the issue lies in the fact that you're mixing `scss` with `css`, this is why it mentions `@ multi styles`. 

One way to fix this is to include bootstrap in your `styles.scss` like this: 

`@import '~bootstrap/dist/css/boootstrap.css';`

**Comment by keithmichelson** [comment]
@beeman Thanks for the reply. I will give that a try but I do have 3 other projects doing it the same way that work fine on older cli betas. (14 and 18)

**Comment by keithmichelson** [comment]
That gets rid of the error, but I'm still getting the other error so I can't see if the styles actually work. compiler_1.StaticSymbolResolver

Using both styles should be fine though, it used to work. Something has changed.

**Comment by billysyrett** [comment]
Also getting this error but I'm not using a mix of CSS and SCSS:

```
      "styles": [
        "assets/css/stylenew.css",
        "assets/css/normalize.css",
        "assets/css/skeleton.css",
        "assets/css/font-awesome.min.css"
      ],
```

ng version:
```
angular-cli: 1.0.0-beta.24
node: 4.4.7
os: darwin x64
@angular/common: 2.3.1
@angular/compiler: 2.3.1
@angular/core: 2.3.1
@angular/forms: 2.3.1
@angular/http: 2.3.1
@angular/platform-browser: 2.3.1
@angular/platform-browser-dynamic: 2.3.1
@angular/router: 3.3.1
@angular/compiler-cli: 2.4.1
```

**Comment by filipesilva** [comment]
There shouldn't be any issue in mixing sass/less/css/whatever. 

If you can get me a simple repro, I can try to debug, but with just this information there isn't much I can do.

**Comment by keithmichelson** [comment]
Thanks for the replies. Yes dumb mistake with that typo @pushingrobot good find. I am still getting the other error though. ERROR in compiler_1.StaticSymbolResolver is not a function
I'll try and setup a repo, thanks for the help.

**Comment by billysyrett** [comment]
@keithmichelson if it helps, I had the same problem and updating my packages resolved it: #3799

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by whisher** [comment]
Hello there,
ng cli version **7.3.1**

Just run

ng new mytest
router yes
sass

npm run build

ERROR in multi ./src/styles.sass

in angular.json

> "schematics": {
>         "@schematics/angular:component": {
>           "style": "sass"
>         }
>       },

**Comment by filipesilva** [comment]
@whisher I think you're seeing https://github.com/angular/angular-cli/issues/13550 / https://github.com/angular/angular-cli/issues/13631.
