### ISSUE TITLE
npm link not working

### ISSUE THREAD

**Issue by trainerbill** [angular/angular-cli#3760]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.24
node: 6.4.0
os: linux x64
@angular/flex-layout: 2.0.0-beta.1
@angular/material: 2.0.0-beta.1
@angular/common: 2.4.1
@angular/compiler-cli: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
```
git clone git@github.com:alxhub/ng2-library.git
cd ng2-library/
npm install
npm run build
npm link
cd ..
ng new clitesting
cd clitesting
```
import the ng2 library on on app.module.ts
```
import * as test from 'ng2-library';
```

### The log given by the failure.
> Normally this include a stack trace and some more information.

![image](https://cloud.githubusercontent.com/assets/3578259/21511988/59ecddaa-cc6d-11e6-8757-9448b06b3629.png)

### Mention any other details that might be useful.
I am assuming this would work with the ng2-library module.  My issue is in a different module but this is the easiest to reproduce with steps.  
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
Did you try `npm link ng2-library`? This seems like it's a problem with npm, not the CLI.

**Comment by trainerbill** [comment]
Yeah it still doesnt work.  do you have an example that does work to rule out the cli?

**Comment by murati** [comment]
even if you install dependencies one by one, still huge DI's on them required.
