### ISSUE TITLE
ES6 Set

### ISSUE THREAD

**Issue by maytis** [angular/angular-cli#3762]
this.myset = new Set(flat.map(item => JSON.stringify(item)));
console.log([...this.myset]);

This compiles fine. But in run time, this gives the following error:
_this.myset.slice is not a function

I have added experimental decorators to tsconfig. What else can I do ?

**Comment by mrgoos** [comment]
can you try to put in `compilerOptions` `"lib": ["es6"],` and `"target": "es5",`?

**Comment by mattdistefano** [comment]
Maybe take a look at https://github.com/Microsoft/TypeScript/issues/8856 too.

**Comment by filipesilva** [comment]
Seems to be a Typescript issue as @mattdistefano mentioned.
