### ISSUE TITLE
How to access externally on npm start? Seems like only localhost unlike LiteServer

### ISSUE THREAD

**Issue by dylanh724** [angular/angular-cli#3765]
1. I used the CLI (via a digitalOcean droplet)
2. npm start
3. I try to access via my Windows PC **myserver:4200** .... connection refused - I'm not localhost. LiteServer allows external connections, why not the CLI's "new" test server?

**Comment by clydin** [comment]
As per the README, use the --host option.  Exposing a Dev server publicly by default has security implications.

**Comment by tarlepp** [comment]
Personally I have solved this with `"start": "ng serve --host 0.0.0.0",` on package.json - and note that only devs uses pure npm commands like that.

**Comment by filipesilva** [comment]
I think @clydin and @tarlepp have answered this thoroughly. Cheers!

**Comment by eduardolucioac** [comment]
To access externally running "npm start" open the file...

`vi project_path/project_path/project_path/package.json`

... and change (example)...

`    "start": "http-server ./app -a localhost -p 8000 -c-1",`

... to...

`    "start": "http-server ./app -a 0.0.0.0 -p 8000 -c-1",`

Chers!

**Comment by engineer-nadeem** [comment]
getaddrinfo ENOTFOUND localhost
Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

Any one help for this ???
unable to run my angular project

**Comment by Deedu** [comment]
For anyone still thinking about this, take a look at ngrok (https://ngrok.com/). It solves exactly this issue by exposing a public url for requests.

**Comment by Sumeetkaushiik** [comment]
> getaddrinfo ENOTFOUND localhost
> Error: getaddrinfo ENOTFOUND localhost
> at errnoException (dns.js:28:10)
> at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
> 
> Any one help for this ???
> unable to run my angular project

USE THIS to run

HOST=localhost npm start
