### ISSUE TITLE
angularfire2 can't install in latest angular cli

### ISSUE THREAD

**Issue by prithviraju1369** [angular/angular-cli#3766]
**npm WARN angularfire2@2.0.0-beta.6 requires a peer of rxjs@5.0.0-beta.12 but none was installed.**

versions:
"**angular-cli": "1.0.0-beta.24",
"@angular/compiler-cli": "^2.3.1",
"@angular/core":^2.3.1
"rxjs": "5.0.1",**

**Comment by clydin** [comment]
That's a warning not a failure.

Also the warning is an issue with the library not the CLI.  Angular 2.4 has a peer dependency on rxjs ^5.0.1.

**Comment by robertbaker** [comment]
I installed it and it works (except in prod mode)

**Comment by filipesilva** [comment]
Closing as @clydin has answered it.
