### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by johannesjo** [angular/angular-cli#3771]
### OS?
Ubuntu 16.10

### Versions.
Node: v5.9.1 (via nvm)
ng-cli: undefined (but it should be 1.0.0-beta.24, EDIT: so it doesn't work with earlier betas neither)

### Repro steps.
Trying to install angular-cli via `npm install -g angular-cli`.

### The log given by the failure.
```
npm ERR! cb() never called!
```
### Mention any other details that might be useful.
I tried npm cache clean beforehand and also manually uninstalling and reinstalling the module with no effect. All other global and local npm installations are running just fine.

**Comment by clydin** [comment]
NPM version?  3 or higher is required

**Comment by johannesjo** [comment]
It's 3.7.1 I think. Definitely higher than 3. But I'll check tomorrow.

**Comment by johannesjo** [comment]
I also installed ng-cli successfully about a month earlier on the very same setup.

**Comment by johannesjo** [comment]
npm is 3.7.3.

**Comment by hansl** [comment]
Wait, running `ng version` does not work? Does it show the above version?  Does it show that log and that's it? This seems like a bug in node itself, so unless `ng version` actually works or you have additional log, I'll close this in favor of your issue npm/npm#15344.

**Comment by johannesjo** [comment]
No, it doesn't really install properly.
