### ISSUE TITLE
feature request(ng new): generate new project base on scaffolding.json and have a tool to generate the scaffolding.json

### ISSUE THREAD

**Issue by rxjs-space** [angular/angular-cli#3779]
Before running `ng new`, we can do something like `ng scaffolding`, it will ask a bunch of questions and generate a `scaffolding.json` based on user answers, then `ng new` will generate codes based on the `scaffolding.json` file.  
For example, the `scaffolding.json` could look like this:  
```json
{
  "projectOptions": {
    "nameParam": "bootstrap"
  },
  "rootModule": {
    "name": "__nameParam__",
    "options": {
      "routing": true
    },
    "children": [
      {
        "type": "component",
        "name": "__nameParam__-home",
        "options": {
          "flat": false
        }
      },
      {
        "type": "module",
        "name": "__nameParam__-accordion",
        "options": {...},
        "children": [...]
      }
    ]
  }
}
```
Then we have something similar like running these commands as: 
```bash
ng new bootstrap
cd bootstrap
ng g c bootstrap-home --flat=false
ng g m bootstrap-accordion
```

**Comment by hansl** [comment]
Thanks for the feature request, but we won't follow with this.

Closing because we already have a story for custom blueprints.
