### ISSUE TITLE
Copy static file in Root during 'ng build'

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#3780]
> Please provide us with the following information:
> ---------------------------------------------------------------
I have a file called 'web.config' and now I added it to the Root of my application so in /app/src/web.config.

now when I make an build trough 'ng build --target=production --environment=prod' it's not adding the web.config to the root of the dist folder.

How can I achieve this?

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
22-1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
ng build --target=production --environment=prod

### The log given by the failure.
> Normally this include a stack trace and some more information.
no logs.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rxjs-space** [comment]
Try play with [project-assets](https://github.com/angular/angular-cli#project-assets).
