### ISSUE TITLE
Bug/Feature request 

### ISSUE THREAD

**Issue by AmitMY** [angular/angular-cli#3784]
### OS?
> Mobile devices (under Cordova)

### Versions.
- All

### Repro steps.
- Create an angular-cli project, and compile it using cordova (phonegap is automatic)

### The log given by the failure.
- 404 error for scripts and styles
- cause: <base href="/">

### Mention any other details that might be useful.
- Removing <base href="/"> causes angular not to work.
- Changing to <base href=""> makes local content somewhat work, but remote urls doesn't, and local paths are relative to paths like "users" and "user/1" making stuff not work.

I think mobile development support will go a long way for angular-cli in comparison to ionic, plus, if you already make an app using angular-cli, converting to ionic is not ideal

This is a feature request, but somewhat a bug request, because it is a failure of angular-cli in a required environment

**Comment by hansl** [comment]
We have an internal Mobile project here, and we had a mobile flag at some point that we had to kill to focus on desktop apps. Our final 1.0 release will be desktop only (although you can technically support mobile using custom configuration).

I'm going to close this as we have a roadmap that tracks the support of addons, which mobile is going to be a part of .

**Comment by AmitMY** [comment]
Thanks!
> (although you can technically support mobile using custom configuration).

Can you give me a lead?
