### ISSUE TITLE
feature: MPA support

### ISSUE THREAD

**Issue by telubeer** [angular/angular-cli#3788]
**Feature**: build multiple applications from one repository
myrepo
-dist1
-dist2
-src
--app1
--app2

**Suggestion**: 
1 option: extend angular-cli.json _apps_ section to be a real array (or object like _entry_ section of webpack)
`apps: [{root:"src/app1",outDir:"dist1"},{root:"src/app2", outDir:"dist2"}]`

when i "run ng build" it must produce two dist folders (dist1 and dist2)

2 option: implement support for CLI_CONFIG_FILE_NAME parameter
`ng build --angular-cli-config-file-name my-angular-cli.json`

and whe can 
`ng build --angular-cli-config-file-name app1-angular-cli.json` produce dist1 folder
`ng build --angular-cli-config-file-name app2-angular-cli.json` produce dist2

**Comment by hansl** [comment]
Multiple application is already in the work (we use an array of apps). It will come after 1.0 though. Closing this as WAI.

**Comment by leocaseiro** [comment]
That would be an easy way to setup temporary for multiple apps.

**Comment by evkw** [comment]
@hansl  was there a task i could follow for progress on this? I gave it a search but didnt have much luck

**Comment by kasperhhk** [comment]
There is not support for MPA using the same task. You have to run build / serve / test etc. for each app individually.
If you don't provide a specific app, then it just defaults to the first app:
https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/utilities/app-utils.ts#L26

Would be nice to have the option to compile and process ALL the apps at the same time, so we don't have to run a build script for our build script (isn't that the whole point of all this? simplify tooling so we don't have to use custom buildscripts). Not to mention the myriad of performance issues that goes into running webpack 50 times if you have 50 apps, that share 90% of files.
