### ISSUE TITLE
SCRIPT445 object doesn't support this action when run on IE9

### ISSUE THREAD

**Issue by tamtran-asnet** [angular/angular-cli#3790]
EXCEPTION: Uncaught (in promise): Error: Loading chunk 0 failed.
Unhandled Promise rejection:Loading chunk 0 failed.;
Zone:angular; Task:Promise.then; Value:Error: Loading chunk 0 failed.undefined
Error: Uncaught (in promise): Error: Loading chunk 0 failed.
SCRIPT438 object does'nt support property or method bind
SCRIPT445 object doesn't support this action

Please help me fix!

**Comment by filipesilva** [comment]
Please fill in new issue template. I have no idea what's happening, why, or how.
