### ISSUE TITLE
Add --skip-tests flag to ng init

### ISSUE THREAD

**Issue by tsm91** [angular/angular-cli#3791]
It would be nice to have a `--skip-tests` flag in the `ng new / init` command. 

I know it is a very bad practice to omit writing unit and e2e tests but it would be a useful flag for barbarians like me. :dancer: 

I wanted to know your opinion about it before making a PR.

**Comment by baruchvlz** [comment]
If `ng new myApp --skip-tests` is run, should the `angular-cli.json` be updated to change the following:

```json
    "spec": {
      "class": false, 
      "component": true, # change to false
      "directive": true, # change to false
      "module": false,
      "pipe": true, # change to false
      "service": true # change to false
    }
```

**Comment by sumitarora** [comment]
Closing as it has been implemented.
