### ISSUE TITLE
Error updating browser Angular 2 app

### ISSUE THREAD

**Issue by juanfarBSU** [angular/angular-cli#3792]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?

os: linux x64 Ubuntu 16.04

### Versions.

angular-cli: 1.0.0-beta.24
node: 7.2.0
npm: 3.10.9

Hi, I created a project in angular cli, but the problem is that when updating the browser is redirected to the root of the web and I must stay in the same url route.

Does anyone know what happens?

1. My project runs in localhost/produccion.

2. then I log in and go to localhost/produccion/reports/ balance.

3. when I refresh the page it redirects to localhost/produccion again, and block the view

Thank you all!

**Comment by baruchvlz** [comment]
How do you mean, updating the browser?

**Comment by filipesilva** [comment]
Going to need some more details here. Also repro steps if possible.

**Comment by juanfarBSU** [comment]
thanks @baruchvlz sorry i mean refresh de page

**Comment by juanfarBSU** [comment]
thanks @filipesilva, sorry I'm a new user, the problem is te following: 

1. My project runs in localhost/produccion.

2. then I log in and go to localhost/produccion/reports/ balance.

3. when I refresh the page it redirects to localhost/produccion again, and block the view

**Comment by filipesilva** [comment]
That sounds related to your server. How are you serving the app?

**Comment by juanfarBSU** [comment]
It runs in NG Live Development Server on http://localhost:4200

**Comment by juanfarBSU** [comment]
without answers
