### ISSUE TITLE
Successfully deploying to unsuccessful Github Pages

### ISSUE THREAD

**Issue by doubleUTF** [angular/angular-cli#3794]
> Please provide us with the following information:
> ---------------------------------------------------------------
After 'successfully' deploying a basic site to Github Pages, the link shows a 404 Error site not found. 
The link provided in console is [https://doubleutf.github.io//personal-portfolio/](https://doubleutf.github.io//personal-portfolio//). I'm told it may take a few minutes but it's been an hour and still there is no page. The git repo is here: [https://doubleutf.github.io//personal-portfolio/](https://doubleutf.github.io//personal-portfolio/). Here is a screenshot of the success message:
![github-success](https://cloud.githubusercontent.com/assets/17230520/21571401/d7c89102-ce83-11e6-967f-1b001110b733.JPG)
Since the page obviously did not successfully push and no error message is shown, I don't know what exactly went wrong after entering 'ng github-pages:deploy'. Please help!

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Win7
### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli 1.0.0-beta.24

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Purely made by angular-CLI

### The log given by the failure.
> Normally this include a stack trace and some more information.
No log error, this isn't a normal issue!

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Odd... recently that logic changed a bit, so maybe something is broken. Will investigate when I have time.

**Comment by kailash-a** [comment]
Hi,
Having the Same issues as above 
Repo link : `https://github.com/kailash-a/Profile`

`OS: WIN 7 Home basic`

**Version:**
```
E:\Kailash\Projects\PProfile\Profile>ng github-pages:deploy
Hash: 09a4c93d34f2b4332ac8
Time: 63469ms
chunk    {0} main.97a5a1a67aaee37b81da.bundle.js, main.97a5a1a67aaee37b81da.bundle.map (main) 2.93 MB {2} [initial] [rendered]
chunk    {1} styles.91ed41036aa61712f7f3.bundle.css, styles.91ed41036aa61712f7f3.bundle.map, styles.91ed41036aa61712f7f3.bundle.map (styles) 155
kB {2} [initial] [rendered]
chunk    {2} inline.a7f34afba5aebe8c2d71.bundle.js, inline.a7f34afba5aebe8c2d71.bundle.map (inline) 0 bytes [entry] [rendered]
Deployed! Visit https://kailash-a.github.io//profile//
Github pages might take a few minutes to show the deployed site.

E:\Kailash\Projects\PProfile\Profile>ng --version
angular-cli: 1.0.0-beta.24
node: 6.9.1
os: win32 x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

E:\Kailash\Projects\PProfile\Profile>
```
App is created using angular cli completely

**Comment by davery22** [comment]
This may or may not be helpful, but I was having a similar issue on macOS Sierra, with a repo freshly boilerplated with angular-cli. I also have a custom domain tied to my GitHub Project Pages, so I have a CNAME in the `gh-pages` branch.
After running `ng github-pages:deploy`, when I browsed to my custom domain name I could see a page with the default `Loading...`, and if I viewed the page source I could see that `index.html` loaded, but it failed to load 3 other inlined resources. Note that `ng github-pages:deploy` writes over `<base href="/">` in `index.html`, trying to make the path work for GitHub I believe. I changed it back to `<base href="/">` in both `index.html` and `404.html` on the generated `gh-pages` branch, and that seemed to fix the problem.

**Comment by DanGeffroy** [comment]
I was having the same issue as you, I manage to solve it, here is how : 

clean the gh-pages branch (don't know if that mandatory to solve this propleme but i'v done it)
```bash
# deleted the gh-pages branch on github
git push origin --delete gh-pages

# deleted the gh-pages branch on local
git branch -D gh-pages
```

correct the name in angular-cli.json file, the case where wrong in mine (probably my fault ^^),
```bash
"name": "oph"
-- replaced with
"name": "OPH"
```
the name was also wrong in the package.json file

re-deploy on gh-pages
```bash
ng github-pages:deploy --message "your message commit"
```
In my case the problem was solved by doing this.
I don't know if in your case this will solve your problem.

Hope it helps you guys

**Comment by doubleUTF** [comment]
@DanGeffroy I tried to redeploy but it only resulted in deleting my Angular /src folder and removing root files such as package.json, angular-cli.json, etc. I don't know why the program runs the 'clean' command if I just want to upload to pages: 

```
ng github-pages:deploy -m "Deploying portfolio project
Hash: 479d5013cec8861b8e77
Time: 38767ms
chunk    {0} main.b1690e73a2ede421a645.bundle.js, main.b1690e73a2ede421a645.bundle.map (main) 2.63 MB {3} [initial] [rendered]
chunk    {1} scripts.03cd147e0c3c0808e993.bundle.js, scripts.03cd147e0c3c0808e993.bundle.map (scripts) 462 kB {3} [initial] [rendered]
chunk    {2} styles.30a1c49a21a36c3d6fa5.bundle.css, styles.30a1c49a21a36c3d6fa5.bundle.map, styles.30a1c49a21a36c3d6fa5.bundle.map (styles) 103 kB {3} [initial] [rendered]
chunk    {3} inline.04b4b926e91c8df62247.bundle.js, inline.04b4b926e91c8df62247.bundle.map (inline) 0 bytes [entry] [rendered]
Command failed: git clean -f -d
warning: failed to remove src/

There was a permissions error during git file operations, please close any open project files/folders and try again. You might also need to return to the initial branch manually.
```

**Comment by kailash-a** [comment]
@filipesilva  i have observed following points while trying to resolve this may help you.

1.) with using `angular-cli :deploy` my gh-pages branch is not commmitted to my github repo.(committed it with `git push`)
2.) `<base href="/">` is somehow changed to `<base href="/profile/">` `profile` is given as name in package.json and angular-cli.json. After changing it back to `<base href="/">` Loading.. page starts showing with js/css not found. (may be it is breaking the routing of application)
3.) Even after changing css and js path `(appending project-name in front of path)` application works but with a lot of error messages in browser console. and other paths for folder like (assets ) are breaking

hope this information will help in resolving the issue

**Comment by josecordaz** [comment]
I'm I am having the same issues like yours guys. :(

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
