### ISSUE TITLE
html includes with webpack support

### ISSUE THREAD

**Issue by llehn** [angular/angular-cli#3796]
Currently if I want to include some 3rd part html files, as for polymer in this guide:
https://vaadin.com/vaadin-documentation-portlet/elements/angular2-polymer/ng-cli-webpack.html
I have to install the whole bower dependency tree into "assets" and do something really really ugly as
````
 <link rel="import" href="assets/bower_components/paper-styles/color.html">
 <link rel="import" href="assets/bower_components/paper-styles/typography.html">
````
inside my index.html

This is against the philosophy of webpack as I interpret it. Including tons of garbage bypassing all logic.

There is a "solution" to this in form of a webpack plugin:
https://github.com/DevWurm/html-includer-webpack-plugin
however there is no possibility to use that with angular-cli, since it does not offer an overrideable webpack config (and there are no plans to do so as I understand) 

A better solution is needed for that. In the discussion about webpack config there was a mention of addon model, maybe that. I'd like to install polymer paper elements with npm, just link to the required files, and the cli should take care of the rest, magically making everything work without hassle, still producing a nice tidy webpack package. At least this would fit my interpretation of the cli philosophy.

**Comment by flpms** [comment]
I like to propose simple use to it. In `.angular-cli.json` create a key like `styles` and  `scripts`, named was `webComponents` that insert  webComponents to project and make easy to understand.

**Comment by filipesilva** [comment]
The current glob functionality for assets should alleviate this problem.
