### ISSUE TITLE
ERROR in compiler_1.StaticSymbolResolver is not a function

### ISSUE THREAD

**Issue by billysyrett** [angular/angular-cli#3799]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Mac OSX Sierra 10.12.1

### Versions.
angular-cli: 1.0.0-beta.24
node: 4.4.7
os: darwin x64
@angular/common: 2.3.1
@angular/compiler: 2.3.1
@angular/core: 2.3.1
@angular/forms: 2.3.1
@angular/http: 2.3.1
@angular/platform-browser: 2.3.1
@angular/platform-browser-dynamic: 2.3.1
@angular/router: 3.3.1
@angular/compiler-cli: 2.4.1

### Repro steps.
Upgraded from CLI v16 to v24, followed ng init steps to bring application up to date.

### The log given by the failure.
ERROR in compiler_1.StaticSymbolResolver is not a function

### Mention any other details that might be useful.
Application does compile fine when running ng serve and when building and deploying to AWS.  Error does not cause compilation to fail.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by billysyrett** [comment]
Mismatched packages

**Comment by leedavidr** [comment]
Hey Billy, I'm getting the same error, do you know which packages were mismatched?

**Comment by billysyrett** [comment]
@leedavidr I had an old compiler-cli in my package.json - updated to  "@angular/compiler-cli": "2.4.1" and issue was resolved (StaticSymbolResolver was not present in the version I was using (^2.3.1))

**Comment by leedavidr** [comment]
@billysyrett Thank you for your help! I overrode my existing project's files (package.json, etc.) with everything from ng-init, and it seemed to work after. I must've diff'ed incorrectly.
