### ISSUE TITLE
Safari is not loading the generated .gz file?

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#3804]
> Please provide us with the following information:
> ---------------------------------------------------------------
Maybe it does not belong here but, when you make an production build it generates .gz files (gzipped) I can see the gzipped files loaded inside Chrome.!!

But in Safari it’s loading the .js file! instead of the .gz file!

I Serve it on Windows IIS.

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
MacOS

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
24

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
ng build --target=production --environment=prod --no-sourcemap

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by photostu** [comment]
@masaanli This issue is in the realm of how your webserver handles compression when serving content. Nothing to do with ang-cli

**Comment by masaanli** [comment]
Same issue goes for cached index.html after new published version?

**Comment by hansl** [comment]
This is an issue with your web server, not related to CLI. You should configure IIS to serve the gzip if the browser supports it.
