### ISSUE TITLE
[Generate Component] Not registering on the closest Module

### ISSUE THREAD

**Issue by Sakuto** [angular/angular-cli#3819]
### OS?
> Windows 10

### Versions.
> λ ng --version
angular-cli: 1.0.0-beta.24
node: 7.2.0
os: win32 x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

### Repro steps.
Project freshly generated.

1. Generate a module `ng g m Heroes`
2. Generate a component `ng g c Heroes`
3. Generate another component `ng g c HeroesList`

Expecting to get both components declared inside the HeroesModule, instead, the HeroesComponent is declared inside the AppModule, shouldn't it been in the closest module so HeroesModule? Or did I misunderstood the convention.

### The log given by the failure.
No error, just not the expected behavior.

### Mention any other details that might be useful.
/

**Comment by sarunint** [comment]
I believe it's the expected behavior. To register both components in hero modules, use `ng g c heroes/heroes`

**Comment by Sakuto** [comment]
Wouldn't it be better if this was automatic since the destination directory is the same?

**Comment by baruchvlz** [comment]
When you genarate a module it will create a folder insider `src/app` with the module name, the expected behavior is for you to use `ng g c heroes/heroes` to generate a component inside the folder. If you do `ng g c heroes` it will generate inside `src/app` and update `app.module.ts`. 

Automating this requires a lot of work to gain basically nothing.

**Comment by Sakuto** [comment]
The problem with `ng g c heroes/heroes` is that it will create a new folder heroes under the heroes folder, which is not right according to the documentation.

I did not looked a lot at the code, but as far as I understand, it could just be a new condition on [findParentModule](https://github.com/angular/angular-cli/blob/master/packages/angular-cli/utilities/find-parent-module.ts)

**Comment by Sakuto** [comment]
Bump.

**Comment by filipesilva** [comment]
The intended approach here is to use `ng g c heroes/heroes`, yes. You can also use `--flat` to not create the folder.
