### ISSUE TITLE
ng build no longer working with v0.0.29

### ISSUE THREAD

**Issue by markjritchie** [angular/angular-cli#382]
I am filling a bug
Windows 7 Enterprise
node v5.7.0
npm 3.6.0

{ name: 'angular-cli',
  time:
   { modified: '2016-03-30T18:10:47.060Z',
     created: '2014-10-07T04:34:38.078Z',
     '1.0.0': '2014-10-07T04:34:38.078Z',
     '0.0.0': '2014-10-11T11:38:24.914Z',
     '0.0.1': '2015-08-03T17:12:04.553Z',
     '0.0.2': '2015-10-18T17:46:40.146Z',
     '0.0.3': '2015-10-18T21:42:52.445Z',
     '0.0.4': '2015-10-19T01:14:13.216Z',
     '0.0.5': '2015-10-19T09:14:01.712Z',
     '0.0.6': '2015-10-19T09:36:51.644Z',
     '0.0.7': '2015-10-19T11:48:24.233Z',
     '0.0.8': '2015-10-19T11:51:59.318Z',
     '0.0.9': '2015-10-19T21:18:13.725Z',
     '0.0.10': '2015-10-19T22:18:13.091Z',
     '0.0.11': '2015-11-03T05:03:06.345Z',
     '0.0.12': '2015-11-15T10:10:48.551Z',
     '0.0.13': '2015-12-04T17:16:43.662Z',
     '0.0.14': '2015-12-05T01:40:39.377Z',
     '0.0.15': '2015-12-05T05:50:59.226Z',
     '0.0.16': '2015-12-10T12:23:28.722Z',
     '0.0.17': '2015-12-14T19:37:08.400Z',
     '0.0.18': '2015-12-15T12:51:47.990Z',
     '0.0.19': '2015-12-15T18:23:33.077Z',
     '0.0.20': '2015-12-15T20:39:55.357Z',
     '0.0.22': '2016-02-20T00:36:56.908Z',
     '0.0.23': '2016-02-20T01:44:13.897Z',
     '0.0.24': '2016-02-25T17:41:20.619Z',
     '0.0.25': '2016-03-10T02:10:05.410Z',
     '0.0.26': '2016-03-23T00:39:46.402Z',
     '0.0.27': '2016-03-23T22:05:56.538Z',
     '0.0.28': '2016-03-28T22:39:45.766Z',
     '0.0.29': '2016-03-30T18:10:47.060Z' },
  maintainers:
   [ 'angularcore <angular-core+npm@google.com>',
     'rodyhaddad <npm@rodyhaddad.com>' ],
  description: 'CLI tool for Angular2',
  versions:
   [ '0.0.0',
     '0.0.1',
     '0.0.2',
     '0.0.3',
     '0.0.4',
     '0.0.5',
     '0.0.6',
     '0.0.7',
     '0.0.8',
     '0.0.9',
     '0.0.10',
     '0.0.11',
     '0.0.12',
     '0.0.13',
     '0.0.14',
     '0.0.15',
     '0.0.16',
     '0.0.17',
     '0.0.18',
     '0.0.19',
     '0.0.20',
     '0.0.22',
     '0.0.23',
     '0.0.24',
     '0.0.25',
     '0.0.26',
     '0.0.27',
     '0.0.28',
     '0.0.29' ],
  'dist-tags': { latest: '0.0.29' },
  readmeFilename: 'README.md',
  homepage: 'https://github.com/angular/angular-cli',
  keywords: [],
  repository:
   { type: 'git',
     url: 'git+https://github.com/angular/angular-cli.git' },
  author: 'Angular Authors',
  bugs: { url: 'https://github.com/angular/angular-cli/issues' },
  license: 'MIT',
  contributors:
   [ 'Rody Haddad <npm@rodyhaddad.com> (http://rodyhaddad.com/)',
     'Igor Minar <igor@angularjs.org>' ],
  version: '0.0.29',
  main: 'lib/cli/index.js',
  trackingCode: 'UA-8594346-19',
  bin: { ng: './bin/ng' },
  scripts:
   { test: 'node tests/runner',
     lint: 'eslint -c eslint.json \'./**/*.js\' ' },
  engines: { node: '>= 4.1.0' },
  dependencies:
   { broccoli: '^1.0.0-beta.6',
     'broccoli-caching-writer': '^2.2.1',
     'broccoli-concat': '^2.2.0',
     'broccoli-funnel': '^1.0.1',
     'broccoli-merge-trees': '^1.1.1',
     'broccoli-writer': '^0.1.1',
     chalk: '^1.1.1',
     'ember-cli': '2.4.2',
     exit: '^0.1.2',
     'fs-extra': '^0.26.6',
     leek: '0.0.21',
     lodash: '^4.6.1',
     multidep: '^2.0.0',
     resolve: '^1.1.7',
     shelljs: '^0.6.0',
     'silent-error': '^1.0.0',
     'symlink-or-copy': '^1.0.1',
     typescript: '^1.8.7',
     typings: '^0.7.9' },
  'ember-addon': { paths: [ './addon/ng2/' ] },
  devDependencies:
   { chai: '^3.5.0',
     'clang-format': '^1.0.37',
     eslint: '^2.4.0',
     'exists-sync': '0.0.3',
     glob: '^7.0.3',
     minimatch: '^3.0.0',
     mocha: '^2.4.5',
     rewire: '^2.5.1',
     through: '^2.3.8',
     tslint: '^3.6.0',
     'walk-sync': '^0.2.6' },
  gitHead: 'c3c1612d534d0a975afeee167ea685c9617f940c',
  dist:
   { shasum: '4c79ae7dd5faf61ee0732f35a68dc45786d1c3ed',
     tarball: 'https://registry.npmjs.org/angular-cli/-/angular-cli-0.0.29.tgz' },
  directories: {} }

Steps:
I'd been having problems trying to get http.get from Angular http to work with options so I decided to update my modules to see if there was a bug somewhere that had been fixed.

I updated my global modules and then my local ones. When I ran ng build I recived the following error

`TypeError: Cannot read property 'push' of undefined
    at addPathRecursive (D:\EOX2\depots\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:21)
    at D:\EOX2\depots\node_modules\angular-cli\lib\broccoli\angular2-app.js:57:9
    at Array.forEach (native)
    at addPathRecursive (D:\EOX2\depots\node_modules\angular-cli\lib\broccoli\angular2-app.js:56:32)
    at D:\EOX2\depots\node_modules\angular-cli\lib\broccoli\angular2-app.js:57:9
    at Array.forEach (native)
    at addPathRecursive (D:\EOX2\depots\node_modules\angular-cli\lib\broccoli\angular2-app.js:56:32)
    at Array.forEach (native)
    at Angular2App.toTree (D:\EOX2\depots\node_modules\angular-cli\lib\broccoli\angular2-app.js:50:29)
    at module.exports (D:\EOX2\depots\angular-cli-build.js:9:14)
`

I attempted removed my spec files to see if I could get further but now get the following error:

`TypeError: Cannot read property 'push' of undefined
    at addPathRecursive (D:\EOX2\depots\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:21)
    at D:\EOX2\depots\node_modules\angular-cli\lib\broccoli\angular2-app.js:57:9
    at Array.forEach (native)
    at addPathRecursive (D:\EOX2\depots\node_modules\angular-cli\lib\broccoli\angular2-app.js:56:32)
    at D:\EOX2\depots\node_modules\angular-cli\lib\broccoli\angular2-app.js:57:9
    at Array.forEach (native)
    at addPathRecursive (D:\EOX2\depots\node_modules\angular-cli\lib\broccoli\angular2-app.js:56:32)
    at Array.forEach (native)
    at Angular2App.toTree (D:\EOX2\depots\node_modules\angular-cli\lib\broccoli\angular2-app.js:50:29)
    at module.exports (D:\EOX2\depots\angular-cli-build.js:9:14)
`

**Comment by jkuri** [comment]
Please run `ng init` in your project.

**Comment by markjritchie** [comment]
Thanks for the quick feedback.

That appears to have resolved the problem. I did receive an error during the init but I think its a problem with typings and github:

`Installing packages for tooling via npm..? May typings anonymously report usage statistics to improve the tool over time
typings ERR! message Unable to read typings for "selenium-webdriver". You should check the path is correct
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a83677ed1
3add14c2ab06c7325d182d0ba2784ea/selenium-webdriver/selenium-webdriver.d.ts"
typings ERR! caused by connect ETIMEDOUT 185.31.17.133:443

typings ERR! cwd D:\EOX2\depots
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\EOX2\\depots\\node_modules\\typings\\dist\\bin\\typings-
install.js" "--ambient"
typings ERR! node -v v5.7.0
typings ERR! typings -v 0.6.10

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

depots@0.0.0 postinstall: `typings install --ambient`
Exit status 1
Error: depots@0.0.0 postinstall: `typings install --ambient`
Exit status 1
    at EventEmitter.<anonymous> (D:\EOX2\depots\node_modules\npm\lib\utils\lifecycle.js:217:16)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at ChildProcess.<anonymous> (D:\EOX2\depots\node_modules\npm\lib\utils\spawn.js:24:14)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
`

**Comment by jkuri** [comment]
Yes, that happens from time to time. Try `typings install` again.

**Comment by markjritchie** [comment]
When I try typings install --ambient its failing for me every time. Normally with a different typings that can't be installed. I'm still not sure if this is to do with the proxy settings, but given that everything else installs it feels more like something is a little broken in the typings package or that github may be throttling requests.

Here's the trace from trying to do the typings install three times in a row:

D:\EOX2\depots>typings install --ambient
typings ERR! message Unable to read typings for "selenium-webdriver". You should check the entry paths in "selenium-webd
river.d.ts" are up to date
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a83677ed13add14c2ab06c7325d182d0ba2784ea/selenium-webdriver/selenium-webdriver.d.ts"
typings ERR! caused by connect ETIMEDOUT 185.31.17.133:443

typings ERR! cwd D:\EOX2\depots
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mextmr\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install" "--ambient"
typings ERR! node -v v5.7.0
typings ERR! typings -v 0.7.11

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

D:\EOX2\depots>typings install --ambient
typings ERR! message Unable to read typings for "jasmine". You should check the entry paths in "jasmine.d.ts" are up to
date
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/26c98c8a9530c44f8c801ccc3b2057e2101187ee/jasmine/jasmine.d.ts"
typings ERR! caused by connect ETIMEDOUT 185.31.17.133:443

typings ERR! cwd D:\EOX2\depots
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mextmr\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install" "--ambient"
typings ERR! node -v v5.7.0
typings ERR! typings -v 0.7.11

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

D:\EOX2\depots>typings install --ambient
typings ERR! message Unable to read typings for "selenium-webdriver". You should check the entry paths in "selenium-webdriver.d.ts" are up to date
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a83677ed13add14c2ab06c7325d182d0ba2784ea/selenium-webdriver/selenium-webdriver.d.ts"
typings ERR! caused by connect ETIMEDOUT 185.31.17.133:443

typings ERR! cwd D:\EOX2\depots
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mextmr\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install" "--ambient"
typings ERR! node -v v5.7.0
typings ERR! typings -v 0.7.11

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

D:\EOX2\depots>typings install --ambient
typings ERR! message Unable to read typings for "jasmine". You should check the entry paths in "jasmine.d.ts" are up to
date
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/26c98c8a9530c44f8c801ccc3b2057e2101187ee/jasmine/jasmine.d.ts"
typings ERR! caused by connect ETIMEDOUT 185.31.17.133:443

typings ERR! cwd D:\EOX2\depots
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mextmr\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install" "--ambient"
typings ERR! node -v v5.7.0
typings ERR! typings -v 0.7.11

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

**Comment by markjritchie** [comment]
Not sure if I missed it in the docs, but it might be worth mentioning the need to run ng install after upgrading somewhere other than here. Again if its there sorry.
