### ISSUE TITLE
ts

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#3822]
https://github.com/rintoj/angular2-virtual-scroll/issues/11

**Comment by Sakuto** [comment]
Please use the proper format instead of just linking us to the issue.

**Comment by istiti** [comment]
That's all I can give for community!

**Comment by filipesilva** [comment]
Please resubmit this issue filling out the issue template. 

I know it's easier for users to just open an issue with the minimum amount of keystrokes possible but it's not sustainable for maintainers to ask the same questions over and over again to figure out what's wrong, what's the version, what are the repro steps, etc. 

There are only a handful of maintainers but literally tens of thousands of users.
