### ISSUE TITLE
feature request (ng new): add option to generate hmr-ready app

### ISSUE THREAD

**Issue by rxjs-space** [angular/angular-cli#3829]
Please consider enable `ng new some-project --hmr` to generate hmr-ready app. A sample blue print is [here](https://github.com/jschwarty/angularcli-hmr-example). After code is generated, we can do something like `ng serve --hmr -e=dev-hmr` to use the hmr feature. Thanks.

**Comment by filipesilva** [comment]
This is not something we wish to add to the base blueprint. In the future, when the custom blueprints functionality is added, you should be able to use custom blueprints.
