### ISSUE TITLE
When installing angular-cli using npm, process failed on brocolli install

### ISSUE THREAD

**Issue by bwalker72956** [angular/angular-cli#383]
Potential bug or security issue with El Capitan OS.

I experienced a problem installing angular-cli on my mac.  I was able to get the package to install by using the following command: 
     sudo npm install -g angular-cli --unsafe-perm=true

I think it may be an issue with El Capitan.  Thought others might want to know about this potential workaround.  Everything appears to be working correctly after install.

1. OS. Mac OSX (El Capitan)
2. Versions. 
> ng --version:
>         angular-cli: 0.0.29
>         node: 4.4.1
>         os: darwin x64
> 
>node --version: v4.4.1
>
>npm --version: 2.14.20
> 
>npm info angular-cli:
> { name: 'angular-cli',
>   time: 
>    { modified: '2016-03-30T18:10:47.060Z',
>      created: '2014-10-07T04:34:38.078Z',
>      '1.0.0': '2014-10-07T04:34:38.078Z',
>      '0.0.0': '2014-10-11T11:38:24.914Z',
>      '0.0.1': '2015-08-03T17:12:04.553Z',
>      '0.0.2': '2015-10-18T17:46:40.146Z',
>      '0.0.3': '2015-10-18T21:42:52.445Z',
>      '0.0.4': '2015-10-19T01:14:13.216Z',
>      '0.0.5': '2015-10-19T09:14:01.712Z',
>      '0.0.6': '2015-10-19T09:36:51.644Z',
>      '0.0.7': '2015-10-19T11:48:24.233Z',
>      '0.0.8': '2015-10-19T11:51:59.318Z',
>      '0.0.9': '2015-10-19T21:18:13.725Z',
>      '0.0.10': '2015-10-19T22:18:13.091Z',
>      '0.0.11': '2015-11-03T05:03:06.345Z',
>      '0.0.12': '2015-11-15T10:10:48.551Z',
>      '0.0.13': '2015-12-04T17:16:43.662Z',
>      '0.0.14': '2015-12-05T01:40:39.377Z',
>      '0.0.15': '2015-12-05T05:50:59.226Z',
>      '0.0.16': '2015-12-10T12:23:28.722Z',
>      '0.0.17': '2015-12-14T19:37:08.400Z',
>      '0.0.18': '2015-12-15T12:51:47.990Z',
>      '0.0.19': '2015-12-15T18:23:33.077Z',
>      '0.0.20': '2015-12-15T20:39:55.357Z',
>      '0.0.22': '2016-02-20T00:36:56.908Z',
>      '0.0.23': '2016-02-20T01:44:13.897Z',
>      '0.0.24': '2016-02-25T17:41:20.619Z',
>      '0.0.25': '2016-03-10T02:10:05.410Z',
>      '0.0.26': '2016-03-23T00:39:46.402Z',
>      '0.0.27': '2016-03-23T22:05:56.538Z',
>      '0.0.28': '2016-03-28T22:39:45.766Z',
>      '0.0.29': '2016-03-30T18:10:47.060Z' },
>   maintainers: 
>    [ 'angularcore <angular-core+npm@google.com>',
>      'rodyhaddad <npm@rodyhaddad.com>' ],
>   description: 'CLI tool for Angular2',
>   versions: 
>    [ '0.0.0',
>      '0.0.1',
>      '0.0.2',
>      '0.0.3',
>      '0.0.4',
>      '0.0.5',
>      '0.0.6',
>      '0.0.7',
>      '0.0.8',
>      '0.0.9',
>      '0.0.10',
>      '0.0.11',
>      '0.0.12',
>      '0.0.13',
>      '0.0.14',
>      '0.0.15',
>      '0.0.16',
>      '0.0.17',
>      '0.0.18',
>      '0.0.19',
>      '0.0.20',
>      '0.0.22',
>      '0.0.23',
>      '0.0.24',
>      '0.0.25',
>      '0.0.26',
>      '0.0.27',
>      '0.0.28',
>      '0.0.29' ],
>   'dist-tags': { latest: '0.0.29' },
>   readmeFilename: 'README.md',
>   homepage: 'https://github.com/angular/angular-cli',
>   keywords: [],
>   repository: 
>    { type: 'git',
>      url: 'git+https://github.com/angular/angular-cli.git' },
>   author: 'Angular Authors',
>   bugs: { url: 'https://github.com/angular/angular-cli/issues' },
>   license: 'MIT',
>   contributors: 
>    [ 'Rody Haddad <npm@rodyhaddad.com> (http://rodyhaddad.com/)',
>      'Igor Minar <igor@angularjs.org>' ],
>   version: '0.0.29',
>   main: 'lib/cli/index.js',
>   trackingCode: 'UA-8594346-19',
>   bin: { ng: './bin/ng' },
>   scripts: 
>    { test: 'node tests/runner',
>      lint: 'eslint -c eslint.json \'./**/*.js\' ' },
>   engines: { node: '>= 4.1.0' },
>   dependencies: 
>    { broccoli: '^1.0.0-beta.6',
>      'broccoli-caching-writer': '^2.2.1',
>      'broccoli-concat': '^2.2.0',
>      'broccoli-funnel': '^1.0.1',
>      'broccoli-merge-trees': '^1.1.1',
>      'broccoli-writer': '^0.1.1',
>      chalk: '^1.1.1',
>      'ember-cli': '2.4.2',
>      exit: '^0.1.2',
>      'fs-extra': '^0.26.6',
>      leek: '0.0.21',
>      lodash: '^4.6.1',
>      multidep: '^2.0.0',
>      resolve: '^1.1.7',
>      shelljs: '^0.6.0',
>      'silent-error': '^1.0.0',
>      'symlink-or-copy': '^1.0.1',
>      typescript: '^1.8.7',
>      typings: '^0.7.9' },
>   'ember-addon': { paths: './addon/ng2/' },
>   devDependencies: 
>    { chai: '^3.5.0',
>      'clang-format': '^1.0.37',
>      eslint: '^2.4.0',
>      'exists-sync': '0.0.3',
>      glob: '^7.0.3',
>      minimatch: '^3.0.0',
>      mocha: '^2.4.5',
>      rewire: '^2.5.1',
>      through: '^2.3.8',
>      tslint: '^3.6.0',
>      'walk-sync': '^0.2.6' },
>   gitHead: 'c3c1612d534d0a975afeee167ea685c9617f940c',
>   dist: 
>    { shasum: '4c79ae7dd5faf61ee0732f35a68dc45786d1c3ed',
>      tarball: 'https://registry.npmjs.org/angular-cli/-/angular-cli-0.0.29.tgz' },
>   directories: {} }

3. When installing angular-cli, process failed on brocolli install
4.  Error Details:

> $sudo npm install -g angular-cli
> Password:
> npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
> npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
>  
> > broccoli@1.0.0-beta.6 postinstall /usr/local/lib/node_modules/angular-cli/node_modules/broccoli
> > multidep test/multidep.json
> 
> broccoli-plugin 1.0.0: Installing
> npm ERR! Darwin 15.3.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "broccoli-plugin@1.0.0"
> npm ERR! node v4.4.1
> npm ERR! npm  v2.14.20
> npm ERR! path /Users/MyUserName/.npm/broccoli-plugin/1.0.0
> npm ERR! code EACCES
> npm ERR! errno -13
> npm ERR! syscall mkdir
> 
> npm ERR! Error: EACCES: permission denied, mkdir '/Users/MyUserName/.npm/broccoli-plugin/1.0.0'
> npm ERR!     at Error (native)
> npm ERR!  { [Error: EACCES: permission denied, mkdir '/Users/MyUserName/.npm/broccoli-plugin/1.0.0']
> npm ERR!   errno: -13,
> npm ERR!   code: 'EACCES',
> npm ERR!   syscall: 'mkdir',
> npm ERR!   path: '/Users/MyUserName/.npm/broccoli-plugin/1.0.0' }
> npm ERR! 
> npm ERR! Please try running this command again as root/Administrator.
> |
> npm ERR! Please include the following file with any support request:
> npm ERR!     /usr/local/lib/node_modules/angular-cli/node_modules/broccoli/test/multidep/broccoli-plugin-1.0.0/npm-debug.log
> Error: npm exited with exit code 243, signal null
>     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/multidep/index.js:90:28)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> npm ERR! Darwin 15.3.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
> npm ERR! node v4.4.1
> npm ERR! npm  v2.14.20
> npm ERR! code ELIFECYCLE
> 
> npm ERR! broccoli@1.0.0-beta.6 postinstall: `multidep test/multidep.json`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the broccoli@1.0.0-beta.6 postinstall script 'multidep test/multidep.json'.
> npm ERR! This is most likely a problem with the broccoli package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     multidep test/multidep.json
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs broccoli
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! 
> npm ERR!     npm owner ls broccoli
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/MyUserName/Documents/mobile/npm-debug.log
> 

5. Useful details: I was able to get the package to install by using the following command: 
     sudo npm install -g angular-cli --unsafe-perm=true
I think it may be an issue with El Capitan.

**Comment by filipesilva** [comment]
This issue seems to be a dupe of https://github.com/angular/angular-cli/issues/345.

The solution is found in https://github.com/angular/angular-cli/issues/345#issuecomment-201276673.
