### ISSUE TITLE
Do I need to manually update @angular packages when updating Angular-CLI?

### ISSUE THREAD

**Issue by ukaaa** [angular/angular-cli#3832]
When I simply follow the instructions to upgrade Angular-CLI, I sometimes end up with issues. 

Most recently when I run `ng init` I get the error `core_1.Version is not a constructor`. In another issue I found that I need to lock my `@angular` packages to a specific version. So that means I need to manually update my `@angular` packages prior to running `npm i` and `ng init`?

**Comment by zackarychapple** [comment]
What version of the CLI are you running and what versions of angular are currently installed?

**Comment by ukaaa** [comment]
I had `@angular` packages at `"~2.1.0"` and the latest Angular-CLI (`"^1.0.0-beta.24"`). Then it gave me that error.

**Comment by ukaaa** [comment]
After manually updating all `@angular` packages to `"~2.4.0"` it works, but this is not mentioned in the docs. So hence my question, is this the normal thing to do? If so, how do I know which version I should update my `@angular` packages to in order to make them work with the latest version of Angular-CLI?

**Comment by zackarychapple** [comment]
Cli `beta.24` should come with `2.3.1`, having it on `2.1.0` is interesting.  Did you forget to bump when you upgraded?
![image](https://cloud.githubusercontent.com/assets/2133184/21608465/9bdd6460-d18a-11e6-96fe-301b39e648f6.png)

**Comment by zackarychapple** [comment]
When you update the CLI make sure that you are running an `ng-init`.  One of the files it lets you upgrade / gives you diff for, shows you the "blessed" combination for versions with that version of the cli.

**Comment by ukaaa** [comment]
Hmm that crossed my mind, but the doc section [Updating Angular-CLI](https://github.com/angular/angular-cli#updating-angular-cli) mentions that I need to run:

```bash
# Global package:
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest

# Local project package:
rm -rf node_modules dist tmp
npm install --save-dev angular-cli@latest
npm install
ng init
```

Which is exactly what I did. 
But the error immediately occurred when I ran `ng init`, so it failed before it even got to the step where it shows the diffs between the auto generated files.

**Comment by zackarychapple** [comment]
What version were you upgrading from?  I know there was a couple versions (forget which) that you had to step through the immediate next cli version to get ready for the subsequent versions.

**Comment by ukaaa** [comment]
I see, maybe that's the case then. I jumped from `angular-cli@1.0.0-beta.19-3` to `angular-cli@^1.0.0-beta.24`.

**Comment by filipesilva** [comment]
Yeah I think it was related to the big jump as @zackarychapple mentioned. We do have a warning in case you have `@angular/*` at less that `2.3.1` but the jump in versions might have been so big that the `ng` commands couldn't even function. Sorry about that :/

**Comment by ukaaa** [comment]
No problem. Thanks for clarifying @filipesilva!

**Comment by leesaenz** [comment]
Why does angular-cli install 2.3.1 versions of @angular packages on `ng-init` instead of 2.4.x?

**Comment by filipesilva** [comment]
@leesaenz it doesn't. It installs `^2.3.1`, which resolves to the latest minor e.g. `2.4.5`. 

`2.3.1` is the minimum supported version for the CLI.
