### ISSUE TITLE
cannot generate class in sub folder

### ISSUE THREAD

**Issue by YanweiJiang** [angular/angular-cli#3846]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX ( El Capitan)

### Versions.
> 1.0.0-beta.22-1

### Repro steps.
> The app is created by angular cli.
I tried to generate a class in a sub folder as the instructions as generating a component, but it always generate a src/app.ts file, eg. in root folder I run: `ng g cl ./recipes/recipe`, in return it generated `src/app.ts`

### The log given by the failure.
> no failure info, just wrong file generated.

**Comment by baruchvlz** [comment]
Does it fail if you do `ng g sl recipies/recipe` as well?

**Comment by YanweiJiang** [comment]
Thank you. It works when I run: ng g cl recipes/recipe. Sorry I tried to run: ng g c ./recipes/recipe to create component and it worked, thought it will work for class as well
