### ISSUE TITLE
Advanced documentation

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#3849]
Documentation should be advanced.

Currently i see 3 sources which give different amount of informations:

- [GitHub Readme](https://github.com/angular/angular-cli/blob/master/README.md)
- [Reference PDF](https://cli.angular.io/reference.pdf)
- Command: `ng help`

Whats missing?
For example when generating a component there are options that i know from tutorials, but cant find them on any of these sources like `--inline-styles` or `spec false`.

Another example: Reference PDF shows what is able to generate with some options, but not specific options like inline-styles. ng help does not show  what can be generated, but different options than PDF.

**Comment by MickL** [comment]
I didnt find any documentation for building AOT. Again i found the `ng build` option `--aot`within a tutorial and not in angular-cli readme, but in `ng help`.

**Comment by RicardoVaranda** [comment]
The readme is not really the appropriate place to go for documentation, you should have a look in here:
https://github.com/angular/angular-cli/tree/master/docs/documentation

If you are looking for documentation for build command in particular then look at this:
https://github.com/angular/angular-cli/blob/master/docs/documentation/build.md

**Comment by filipesilva** [comment]
I agree that the documentation is disjointed at the moment. This is already being tracked in https://github.com/angular/angular-cli/issues/2711 however, and thus this issue should be closed.
