### ISSUE TITLE
Generating multiple style files

### ISSUE THREAD

**Issue by fuitattila** [angular/angular-cli#3850]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10.

### Versions.
>angular-cli: 1.0.0-beta.24
node: 5.11.0
os: win32 ia32
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

### Question, feature

> ---------------------------------------------------------------
Hi,
Is there a way to generate multiple style files (during build process)?
It is required beacause we have a **normal** stlye and a **WAI** style.
We must them seperate because size limits.
Currently I see that there is only one file generated after ng serve or build.

This thread doesn't helps for me: #2722

Thank you for your help!

**Comment by jasonkrot** [comment]
I just came to say hello

I have the same problem, and it really blocks our refactoring process (we just started using the cli instead of npm-gulp-bower-etc building to reach greater page load time with aot).

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/issues/3401 this should suit your usecase.

**Comment by eredessil** [comment]
Same issue here...

**Comment by fuitattila** [comment]
Dear @filipesilva!

Thank you for your quick response! I tried and that works perfectly!

Best wishes,
Attila

**Comment by jasonkrot** [comment]
thank you very much https://www.youtube.com/watch?v=ax02yrBqpa0

**Comment by filipesilva** [comment]
Glad to hear that was what you needed! Let me know if you have any problem with it, it's not documented so not a lot of people are using it.
