### ISSUE TITLE
Question:  Can you mix and match CSS and Less in the same project?

### ISSUE THREAD

**Issue by daBishMan** [angular/angular-cli#3852]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
$ ng -v
angular-cli: 1.0.0-beta.24
node: 7.2.0
os: win32 x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/compiler-cli: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/platform-server: 2.4.1
@angular/router: 3.4.1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
I have used the bootstrap 3.3.7 css files and created my own less file to override somethings.

### The log given by the failure.
> Normally this include a stack trace and some more information.

No error
### Mention any other details that might be useful.
The styles in less are not included.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

Is the best way to use all less or all css, I was under the impression you can mix and match with webpack.

Any suggestions?

**Comment by zackarychapple** [comment]
I use both only from the standpoint that I have to because of an issue around pathing and references for component libraries.  Have not noticed any ill side effects.

**Comment by gelliott181** [comment]
You can still use CSS files with a custom style interpreter, but the best way to ensure they're all safely bundled would be to import the pure CSS files into a Less file which you use as the component style.

**Comment by hansl** [comment]
To answer your original question; yes you can. Everywhere where we take LESS/SASS files you can just pass in a CSS too.
