### ISSUE TITLE
Replace `source` in environments with separate `environmentDefault` entry

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#3857]
Currently use use the `source` key inside the `environments` object to specify which file should be replaced:

```
"environments": {
  "source": "environments/environment.ts",
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}
```

But this is already the `dev` file. It would be cleaner to specify the default environment instead in a separate key:

```
"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}
```

**Comment by jsanchezgarcia** [comment]
I just noticed that @filipesilva was assigned to this issue. Filipe, let me know if you want me to do any modifications to my PR (or feel free to do your own and discard mine).
