### ISSUE TITLE
Copying assets from node module

### ISSUE THREAD

**Issue by samherrmann** [angular/angular-cli#3859]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.9.1
os: win32 x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

### Repro steps.
This issue follows the [comment made in issue #2837](https://github.com/angular/angular-cli/issues/2837#issuecomment-258457033). @filipesilva suggested to copy complex libraries, such as Cesium, into the assets folder. Building on that suggestion, I changed my `angular-cli.json` file to the following:

    ...
    "assets": [
        "assets",
        "favicon.ico",
        "../node_modules/cesium/Build/Cesium"
     ],
    ...

With this configuration, I expected to find a Cesium folder within the `dist` folder when running`ng build`. That is however not the case. No errors are encountered during the build, but the folder is not copied into `dist`. When I run tests by adding other folders within `src` to `assets`, then that works as expected.

**Comment by filipesilva** [comment]
@jsanchezgarcia is right. https://github.com/angular/angular-cli/issues/3555 is tracking the enhancement.
