### ISSUE TITLE
Specify options to uglify via angular-cli

### ISSUE THREAD

**Issue by pleerock** [angular/angular-cli#3861]
Is there any ways to specify uglify options via angular-cli ? uglify strips class names which is not acceptable for me because Im relying on class names in my code.

**Comment by pleerock** [comment]
From what I see in `webpack-build-production` there is no way to specify custom options. Process of building apps for different environments can be pretty dynamic depend depend on use case, I hope angular-cli will cover all such scenarios in the future, otherwise there is small point in using it. Also I think having all options in a single angular-cli.json cant cover all cases, despite my personal favorite of simplicity, because build process is non trivial sometimes, and should be and angular-cli should be flexible

**Comment by filipesilva** [comment]
We're not looking at adding this option, no. It's a pretty granular setting and does make bundles larger.

I've had that problem myself, mind you, as have others (see http://stackoverflow.com/questions/29310530/get-the-class-name-of-es6-class-instance).

I wouldn't say it's a bad practice to rely on it, but I think it's very brittle. Even if you don't mangle names in your app, library authors cannot rely on it because they can't control how people uglify their code.

**Comment by xnnkmd** [comment]
@filipesilva It would be really useful to be able  keep the correct class names at runtime in certian dynamic scenarios (for instance if what component to display is decided at runtime based on a string value provided by an external entity such as a workflow engine etc.).

**Comment by shoudaos** [comment]
@filipesilva, please, add this possibility to specify uglify options

**Comment by smknstd** [comment]
> It's not well known, but whitespace removal and symbol mangling accounts for 95% of the size reduction in minified code for most JavaScript - not elaborate code transforms. One can simply disable compress to speed up Uglify builds by 3 to 4 times. 

https://github.com/mishoo/UglifyJS2/blob/ae67a4985073dcdaa2788c86e576202923514e0d/README.md#uglify-fast-minify-mode

**Comment by zbuhler** [comment]
I think it would still be nice to be able to specify some uglify options. I like @smknstd am really interested in being able to turn off compression. We did that in our prior webpack build before moving to the CLI and it made almost 3 times as fast. We got the idea from a post from [slack](https://slack.engineering/keep-webpack-fast-a-field-guide-for-better-build-performance-f56a5995e8f1) which quotes the author just like @smknstd did.

It would be nice to have a flag for that at least as having our build server take 3 times as long doing builds for 5% improvement is definitely not ideal.

If people are interested in other UglifyJS options it seems like perhaps a viable option would be to handle UglifyJS options like the `proxy.conf.json` and allow fine tuning?

**Comment by astalegale** [comment]
Me too, in our project mangle breaks the production build.

**Comment by davidnjuko** [comment]
+1

**Comment by atteeela** [comment]
+1

Our issue is that various cryptographic libraries are broken when running in `production`:

Background:

`bitcoinjs` uses typeforce to verify types during run-time and for good reason:  If there is a problem with key generation then people will *lose money*.  Uglify mangles the names and therefore typeforce is not able to verify that the run-time types are correct.  When dealing with peoples money, it's probably a good idea to keep the intention of the developer intact or at least have the option to keep the safety checks in there.

Solution Ideas...

- Not use Angular, and instead re-build with another platform (!)

- Include `bitcoinjs` as a separate script include (where does this end?)

- Implement the ability to pass options in Angular cli down to uglify.

- ???

Has anyone else been able to solve the issue of passing options to uglify for their use-case? 

Thanks again,

**Comment by keenondrums** [comment]
@filipesilva it would be great to have at least ["regex" property](https://github.com/mishoo/UglifyJS2#mangle-properties-options) for mangling exposed. It would allow us to keep class names we absolutely want to keep.
[flux-action-class](https://github.com/keenondrums/flux-action-class) relies on class names to avoid creating constants for action types in our ngrx apps and uses class names instead. Absence of this tuning forces us to use the workaround mentioned by @atteeela, which is not very pretty.

**Comment by keenondrums** [comment]
@filipesilva don't you think developers should have as much freedom as they want?
Btw, terser has even better option for my case ['keep_calssnames'](https://github.com/terser-js/terser#minify-options)

**Comment by keenondrums** [comment]
@pleerock  I created a [small custom builder for that](https://github.com/keenondrums/angular-builder-custom-terser-options). Hopefully we won't have to use for a long time and Angular teams adds this functionality at some point to their default builder.

**Comment by pppppp1996** [comment]
@hansl @filipesilva @clydin @alan-agius4 @Brocco any chance you could re-visit this one?

**Comment by keenondrums** [comment]
As to the bundle size 'keep_classnames' increased it only by 4-5% in my app, which is not much. It could be even less since 'keep_classnames' allows RegEx as a value only those classes we need.

**Comment by vittoriozamboni** [comment]
> We're not looking at adding this option, no. It's a pretty granular setting and does make bundles larger.
> 
> I've had that problem myself, mind you, as have others (see http://stackoverflow.com/questions/29310530/get-the-class-name-of-es6-class-instance).
> 
> I wouldn't say it's a bad practice to rely on it, but I think it's very brittle. Even if you don't mangle names in your app, library authors cannot rely on it because they can't control how people uglify their code.

@filipesilva What is the point of limiting user options? You can add the default values you think work better, but not allowing developers to change them at their own risk sounds like a bad statement.

There are libraries that relies on reserved words and are quite well used (https://github.com/SAP/chevrotain for example). Not being able of using them in an Angular project it's a pity :( 

Can you please revisit your decision? This would be such a great improvement!
