### ISSUE TITLE
[feature] Component generation with configuration file

### ISSUE THREAD

**Issue by mp3por** [angular/angular-cli#3862]
> Please provide us with the following information:
> ---------------------------------------------------------------

Hello,

I would like to be able to use a configuration file to automatically configure things during component generation. For example:

1) I want to be able to generate custom files and put content in them. In my workflow during main modules generation I always create**_component-name.scss** file which is holds general component styles and also connects to the main **.scss** file of the project via `@import "../core/core-base`.  I would like to offload this to the generator.

2) In my inner components the **.scss** file always includes the **_component-name.scss**. Currently I have to manually add the add`@import "settings-base";` or `@import "../settings-base";` and so on which I believe could be offloaded to the generator.

2)  I also add a custom style to the **host** property.

3) I always include a logger in my components - this is 1 import statement and 1 variable which is in every component. I want to be able to offload this to the generator. More over I would like to be able to specify default imports and constructor variables. 

I would like to automate all of these little things which I do for every component if possible.

Best regards

**Comment by filipesilva** [comment]
We have planned a custom blueprint functionality for the future that would allow you to add your own. This is a post 1.0 feature though.
