### ISSUE TITLE
Component's styles are not included

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#3866]
> Please provide us with the following information:
> ---------------------------------------------------------------

### Versions.
angular-cli: 1.0.0-beta.24
node: 4.6.0
os: darwin x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

------

All is almost fine after an upgrade I just found my components styles are not included during a build as they used to be in angular -cli 21 and therefore I am unable to override some LIB styls

```

@Component({
    selector: 'w-basic-navigator' ,
    templateUrl: './basic-navigator.component.html' ,
    styleUrls: ['./basic-navigator.component.scss']
})
export class BasicNavigatorComponent extends BaseComponent implements OnInit
{

```

and styles inside the ./basic-navigator.component.scss - is missing just like from any other component

angular-cli example:

```
{
  "project": {
    "version": "1.0.0-beta.24",
    "name": "xxxxxxx"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.scss",
        "assets/themes/default.scss",
        "../node_modules/primeng/resources/themes/bootstrap/theme.css",
        "../node_modules/primeng/resources/primeng.min.css",
        "../node_modules/font-awesome/scss/font-awesome.scss"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js"
      ],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}
```

The only thing I changed from previous version is that I have in the angular-cli - mixture of sass and css and I had to change :

```
styleUrls: ['basic-navigator.component.scss']

```

to
```
styleUrls: ['./basic-navigator.component.scss']

```

because ng build have me this error

```
Module not found: Error: Can't resolve 'basic-navigator.component.scss' in '/.....
```

**Comment by fkolar** [comment]
it seems that it is similar problem like this #3545, it is just after fixing the paths, the outcome is that styles that are inside my scss files are not included in the final styles.bundle.css

**Comment by fkolar** [comment]
Just created brand new angular project and all is working there, so I assume that ng init might not update it correctly. Which happened to me in past as I kept updated angular-cli. 

All good closing.

**Comment by CraigWarford** [comment]
I don't know if this went away and came back, or what, but I'm seeing the same thing. Created a new app, configured for scss, added routing, set up a component as one of the routes, and the scss file for the component is processed, but the contents are empty:
`exports = module.exports = require("../../../../node_modules/css-loader/lib/css-base.js")(false);
// imports


// module
exports.push([module.id, "", ""]);

// exports


/*** EXPORTS FROM exports-loader ***/
module.exports = module.exports.toString();


//////////////////
// WEBPACK FOOTER
// /home/craigwarford/Projects/d3-playground/src/app/chart/basic/basic-chart.component.scss
// module id = ../../../../../src/app/chart/basic/basic-chart.component.scss
// module chunks = main`
