### ISSUE TITLE
ng build --watch doesn't runs http and proxy server?

### ISSUE THREAD

**Issue by fuitattila** [angular/angular-cli#3880]
Is there any way, to run http server and proxy with `ng build --watch` like `ng serve` does?

I didn't find any information about this. But I need to run `gulp tasks` on some files manually in generated `dist` folder, but with `--watch` I cant check my app on: `http://localhost:4200/`.

@filipesilva is there any way to run this?

**Comment by filipesilva** [comment]
`ng build` doesn't run a server nor proxy, no. You'll have to provide another server for that. 

If it's something that you need to do as part of your everyday tasks I suggest using a npm script with https://github.com/kimmobrunfeldt/concurrently.

Something like 
```
"start": "concurrently --kill-others \"ng build --watch\" \"gulp taskname" \"server --options\""
```
