### ISSUE TITLE
Docs on "build" page show no hyphen for "build". 

### ISSUE THREAD

**Issue by tcoz** [angular/angular-cli#3883]
AT this link, take a look at the instructions for "build". 

There's some confusion. Is it ng build:

--prod
-prod
prod

?

I cloned the wiki and it looks like --prod is correct. But maybe all three work? I ran all three and there's no errors, --prod and -prod seem to do the same thing, plain "prod" seems to get ignored.

**Comment by hansl** [comment]
`--prod` is the proper one; `-prod` works but IMO shouldn't, `prod` shouldn't work and that's correct.

**Comment by tcoz** [comment]
Right, this makes the docs confusing though, since it says "prod", the other two args have hyphens, and elsewhere you can find --prod. It'd probably be a good idea to make that crystal clear in the docs.

**Comment by RicardoVaranda** [comment]
You are correct I have created #3915 to resolve this confusion.

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/3915
