### ISSUE TITLE
Tracking: Document what breaking changes mean for the CLI

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#3887]
- Production logs
- command flags (including defaults)
- config changes
- update tooling

**Comment by jponeill** [comment]
I'd like to suggest that a change like the recent static analysis one be considered a "breaking change" going forward. I got things working but probably would have put the update off until I had the time to spend on it.

**Comment by hansl** [comment]
Done here: https://docs.google.com/document/d/1xLys_Id97YFNrfIvxpdfmoxNTbHzQnpXjxoO0Hyjrno/preview
