### ISSUE TITLE
Document webpack plugins that the CLI is using

### ISSUE THREAD

**Issue by Destreyf** [angular/angular-cli#3892]
### Versions.
angular-cli: 1.0.0-beta.24
node: 6.9.1
os: win32 x64
- @angular/common: 2.4.1
- @angular/compiler: 2.4.1
- @angular/compiler-cli: 2.4.1
- @angular/core: 2.4.1
- @angular/forms: 2.4.1
- @angular/http: 2.4.1
- @angular/platform-browser: 2.4.1
- @angular/platform-browser-dynamic: 2.4.1
- @angular/platform-server: 2.4.1
- @angular/router: 3.4.1

### Mention any other details that might be useful.
It might be useful to document all the webpack plugins that the CLI is currently using, this is a list i compiled from a quick skim, it would be nice to add to this list if i'm missing any or as new plugins are used.  It might also be useful if we can notate the origin of the plugin (custom or url to repo or npm page for each one) to give users an indication of who/where to post if there are known issues.

My List.
- AotPlugin
- ExtractTextPlugin
- GlobCopyWebpackPlugin
- ProgressPlugin
- SuppressEntryChunksWebpackPlugin
- CommonsChunkPlugin
- HotModuleReplacementPlugin
- PrerenderWebpackPlugin
- LoaderOptionsPlugin

**Comment by hansl** [comment]
Hi,

First of all, thanks for filing this feature request. Unfortunately, I'm going to close this issue. AFAIK your list is correct, but it takes too much work finding if there's anything else.

We change plugins regularly and keeping a list up to date is difficult. We also don’t feel people should worry about it too much. The goal of abstracting webpack away is that we don't have to maintain users expectation regarding webpack itself (just expectations regarding the CLI).

I hope this answer your question. Cheers!
