### ISSUE TITLE
while hosting the app changes to ts files are not being reflected

### ISSUE THREAD

**Issue by jmurphzyo** [angular/angular-cli#390]
I don't know if I am just being dumb or if this is the way the live-reload works but while I am hosting the app if I make changes to .ts files the changes are being recognized but the browser itself doesn't reflect the changes. Is there a setting I didn't enable or is this just the way the package is suppose to work?

**Comment by markjritchie** [comment]
I'm not sure if this is the same problem but since I upgraded to the latest version my ts files are no longer being copied to the dist folder.

**Comment by hansl** [comment]
The `ts` files being copied were a bug; you shouldn't need the source files in your `dist` folder, we removed those.

Using `ng serve` and changing the `ts` files has been fixed by https://github.com/angular/angular-cli/pull/367. Closing this as fixed.

**Comment by markjritchie** [comment]
When the ts files were being copied I could set breakpoints in the ts files and debug the ts code. I'd suggest that the ts are copped to the `dist` folder during dev builds / serves and not copied for production releases

**Comment by jkuri** [comment]
I believe you don't need source files in the `dist` folder, the compiler gives you a nice error output when something goes wrong.

**Comment by markjritchie** [comment]
It wasn't for the compiler error point of view, it was for using the debugging tools in chrome
