### ISSUE TITLE
angular-cli addons[] and packages[]

### ISSUE THREAD

**Issue by mkoczorowski** [angular/angular-cli#3901]
Hi there,

I would like to ask for the purpose of those please ?

Thanks for the awesome work

**Comment by beeman** [comment]
Hi @mkoczorowski ,

The Angular CLI is based on the ember-cli project, which supports addons and packages. 

This is currently not a future in Angular CLI but there will be some sort of plugin system in the future.

In the code you can find references to these 2 keys that reveal they have a future. It's hard to say when this is available, but there will be a roadmap soon, I expect it to be on there.

https://github.com/angular/angular-cli/blob/master/packages/angular-cli/lib/config/schema.json#L123

`"description": "Configuration reserved for installed third party addons.",`
`"description": "Configuration reserved for installed third party packages.",`
