### ISSUE TITLE
Base href bug or usage error

### ISSUE THREAD

**Issue by FallenRiteMonk** [angular/angular-cli#3903]
I have a little mockup app build using angular-cli and since I use gitlab, I wanted to host it using gilab pages.
Now if the project gets build using ```build --prod --aot``` and hosted at the url "groupname.gilab.io/mockup" it doesn't work as all the other bundles are not found because it tries to get them form "groupname.gilab.io/main.***.js" and so on.
But if I build the project using ```build --prod --aot --base-href=mockup``` the app loads up and works fine, only that then I get a url like this "groupname.gilab.io/mockup/mockup/login" for example. This has the result that one can not reload the page as then a 404 error occurs since gitlab doesn't know such a url.

My question is now if this is a bug or if I'm just using the ```--base-href``` option wrong?

ng --version:
```
angular-cli: 1.0.0-beta.24
node: 6.9.2
os: linux x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1
```

**Comment by gelliott181** [comment]
If I'm not mistaken, the base href indicates something added to your URLs beforehand. In this case it means you use `--base-href=mockup` it will automatically change `/*` to `/mockup/*`.

**Comment by FallenRiteMonk** [comment]
OK, but what can I then do in order to get my app running on gitlab? how does an app get build deployed on github so that it works?

**Comment by beeman** [comment]
@FallenRiteMonk if you look at a project that is deployed on GitHub Pages you can see that it uses the full path with a slash as prefix and suffix as base href:

On this demo https://beeman.github.io/angular-cli-sweetalert2-demo/ the base href is set as   `<base href="/angular-cli-sweetalert2-demo/">`

So in your case this means you should probably define it as `ng build --base-href='/mockup/'`

**Comment by FallenRiteMonk** [comment]
@beeman Thanks that did the trick to fix the ulr. Still I get a 404 error on page reload, but this is probably something on gitlab site which I hope to be able to fix by adding a custom 404 site which redirects to the base index.html.
