### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by ericel** [angular/angular-cli#3905]
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Latest beta-24 branch

I am getting the error when I do the following in my app. 
```
import * as services from './services';
import { Store } from './store';
const mapValuesToArray = (obj) => Object.keys(obj).map(key => obj[key]);

export const providers = [
  Store,
  ...mapValuesToArray(services)
];
```
And my appModule.ts providers
```
import { providers } from './index'
`providers: [providers, AnimationService],`
```

I get the following error. I can't figure out what am doing wrong!
```
ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'mapValuesToAr..
ray'. Consider exporting the symbol (position 3:7 in the original .ts file), resolving symbol providers in D:/angular2/e
noeasy/src/app/index.ts, resolving symbol AppModule in D:/angular2/myapp/src/app/app.module.ts, resolving symbol AppMo..
dule in D:/angular2/myapp/src/app/app.module.ts
```

**Comment by baruchvlz** [comment]
The error seems to give you the solution.

Change `const mapValuesToArray = (obj) => Object.keys(obj).map(key => obj[key]);` to
` export const mapValuesToArray = (obj) => Object.keys(obj).map(key => obj[key]);`.

Also, this is a StackOverflow question rather than an issue with the CLI

**Comment by ericel** [comment]
But I am exporting that a;ready here:
```
export const providers = [
  Store,
  ...mapValuesToArray(services)
];
```

**Comment by Meligy** [comment]
This is a limitation with the Angular Compiler. Change it to:

```
export function mapValuesToArray (obj) {
  return Object.keys(obj).map(key => obj[key]);
}
```

(Not sure if lambda support -the `() => {}` syntax- is available in latest compiler. You can try first adding an `export` first, and if this doesn't work, change the lambda to the `function` syntax above)

AS @baruchvlz said, this is a support question not really a github issue.

**Comment by filipesilva** [comment]
The answers given by @baruchvlz and @Meligy seem to address this issue so I am closing it.

**Comment by ericel** [comment]
@filipesilva  not really.  But I got it figured out!
The AoT compiler cannot statically analyse the services I was providing, as I was using the Object.keys method to enumerate them.

**Comment by ganySA** [comment]
@ericel - how did you fix the above issue i seem to have exactly the same problem.
