### ISSUE TITLE
SASS doesn't compile and apply

### ISSUE THREAD

**Issue by n2lose** [angular/angular-cli#3921]
I have followed the docs to create new project and sass as style default: [css-preprocessor-integration
](https://github.com/angular/angular-cli#css-preprocessor-integration) and install third party bootstrap
But, seems the sass files doesn't compile, i don't see anything apply styles i created in app.component.scss .
Do i need install some 3rd party like sass-loader?

### OS?
> Windows 10

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.9.2
os: win32 x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2

### Repro steps.
i just create new ng app via command: 
`ng new myapp --style=scss`
Then, i install bootstrap: 
`npm install bootstrap@next --save`
Finally, i try to add some html and style in app.component.scss, but i don't see it work

### The log given by the failure.
There is no errors, but it doesn't work

### Mention any other details that might be useful.
I don't know what's wrong i did? Could someone check and help me to make it works?

Thanks a lots.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@n2lose thanks for creating the issue.

This should just work.

Can you please show the changes you made to the app component? Or even better, share the repo?

**Comment by CarreraPHP** [comment]
@n2lose , Can u explain the issue? Is the bootstrap styles not being applied or any styling within `*.scss` file? If bootstrap styles are not getting applied, can you confirm whether the `../node_modules/bootstrap/dist/css/bootstrap.min.css` file is included in the styles array in `angular-cli.json`?

**Comment by n2lose** [comment]
@beeman : here is the app component:
```
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">{{title}}</a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a routerLink='dashboard'>Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a routerLink='about'>About</a>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class="container">
  <router-outlet></router-outlet>
</div><!-- /.container -->
```

@CarreraPHP : Here you:

     ```
 "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.css",
        "styles.scss"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/tether/dist/js/tether.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js"
      ],
```

**Comment by n2lose** [comment]
Finally, i fixed this issue by the way install sass-loader to compile .scss , so, i close it. Thanks.
