### ISSUE TITLE
as a new user i want a flag and a simple md css layout generated with my angular 2 app

### ISSUE THREAD

**Issue by NilsHolger** [angular/angular-cli#3922]
> Please provide us with the following information:
> ---------------------------------------------------------------
as a new user i want to have a flag to set that scaffolds angular app with md css like this: http://materializecss.com/templates/starter-template/preview.html  header, body and footer components plus routing to two or 3 pages
it's beautiful
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux x64 Ubuntu 16.04.01 LTS on zorin os 12 ultimate dream config

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.24
node: 7.4.0
os: linux x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

ng new my-dream-app --md (generates scaffolded material design app)

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
increase growth of user base
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
Custom templates are going to be after 1.0 final. But there is a point on the roadmap to support them, so stay tuned!
