### ISSUE TITLE
Exclude spec files from AoT

### ISSUE THREAD

**Issue by antonybudianto7** [angular/angular-cli#3928]
> ## Please provide us with the following information:
### OS?

> Linux, Ubuntu
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
> 
> ```
> angular-cli: 1.0.0-beta.24
> node: 6.7.0
> os: linux x64
> ```
### Repro steps.

Originally #2758 , and works until beta 24, most likely it's because of this line changes
https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/plugin.ts#L109

and it's always `true`, so it will never filter spec files.

The filter statement is on the `else` block
https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/plugin.ts#L132

https://github.com/angular/angular/issues/11276
1. Generate new project

```
ng new test-app
```
1. Open app.component.spec.ts
   and add RouterTestingModule

``` ts
import { TestBed, async } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { AppComponent } from './app.component';

describe('App: TestBug', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [
        RouterTestingModule
      ]
    });
  });
```
1. Then try build

```
ng build -prod -aot
```
1. Breaks

``` sh
$ ng build -prod -aot                                                                              
Could not start watchman; falling back to NodeWatcher for file system events.                      
Visit http://ember-cli.com/user-guide/#watchman for more info.                                     
  0% compilingparameters received {"filePath":"/home/antony-budianto/Desktop/personal-project/test-
bug/node_modules/@angular/common/src/location/location.d.ts","name":"Location"} which is not a Stat
icSymbol                                                                                           
Error: parameters received {"filePath":"/home/antony-budianto/Desktop/personal-project/test-bug/nod
e_modules/@angular/common/src/location/location.d.ts","name":"Location"} which is not a StaticSymbo
l 
```

Current workaround:
- Add `**/*.spec.ts` to `exclude` option in `src/tsconfig.json`
### The log given by the failure.

Please see https://github.com/angular/angular/issues/11276
### Mention any other details that might be useful.

AoT should not compile spec files

> ---
> 
> Thanks! We'll be in touch soon.

cc @hansl

**Comment by mattdistefano** [comment]
FYI I just tried this w/ beta 25.5 and wasn't able to reproduce. I also have various tests in my existing that use RouterTestingModule and don't have errors on beta 25.5 or beta 24. I'm on Windows though, so it may be something unique about the Linux environment?

**Comment by antonybudianto7** [comment]
I also got 
```
Calling function 'jasmine', function calls are not supported
```

obviously, it tried to "aot"-ify the spec files....

**Comment by filipesilva** [comment]
Just tried it myself, no issues either:
![image](https://cloud.githubusercontent.com/assets/4172079/22252656/d18a0aa6-e246-11e6-9d3e-3a0645a2ed8c.png)

Maybe it's something in your setup, or deps? Try making a new project and see if it happens there. If you can find a repro where this happens I'll reopen.
