### ISSUE TITLE
ng build disable build *.map and *.gz files

### ISSUE THREAD

**Issue by javist7** [angular/angular-cli#3929]
How to disable build *.map and *.gz file when i run` ng build --prod `?

**Comment by grizzm0** [comment]
You can use `--no-sourcemap` to disable sourcemaps. Gzipped files can not be turned of.

**Comment by ersurajnegi** [comment]
do we need .map files on server?

**Comment by javist7** [comment]
We need .map files to transpose js in ts in your browser.
