### ISSUE TITLE
ng serve does not pick up vendorNpmFiles

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#393]
when doing a ng build it picks up and moves the vendorNpmFiles to the dist directory.  The automated build that is completed as part of the ng serve does not pick up the files. 

version `0.0.29`

**Comment by cironunes** [comment]
this is probably because of my updates on `angular2-app.js` I can take a look at it today.

**Comment by PascalPrecht** [comment]
I confirm this is still present in `0.0.30`

**Comment by PascalPrecht** [comment]
Also it seems that the thirdparty/libs.js file isn't available

![screen shot 2016-04-07 at 16 33 39](https://cloud.githubusercontent.com/assets/445106/14354692/9142fb04-fcde-11e5-90e7-029ffc7bc601.png)

**Comment by cironunes** [comment]
@PascalPrecht: `thirdparty/libs.js`was removed: https://github.com/angular/angular-cli/commit/1819afe3c9b8012525921894ce15c5c887131a54

**Comment by filipesilva** [comment]
This issue has since been fixed.
