### ISSUE TITLE
CDN support with fallback mechanism

### ISSUE THREAD

**Issue by StefanRKarlsson** [angular/angular-cli#3933]
### OS?
> Windows 10

### Versions.
> angular-cli: 1.0.0-beta.24
node: 6.9.1
os: win32 x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/compiler-cli: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1

### Mention any other details that might be useful.

> Is there any plans to support loading script & styles from a CDN with fallback to the local file system?
I would like it to be dependent on which environment you set. Is this possible to do with or without the cli right now?

### Why do i want this?
> Let's say i use the minified and bundled versions of jQuery and jQueryUI i will get the pros that most people already have it cached.
I also imagine that loading from a CDN i faster and makes my local files smaller for webpack to handle.

**Comment by martinmcwhorter** [comment]
In a previous project we would build two index.html files, one without CDN prefixes and one  with them. 

To turn CDN on/off we would just symlink index.html to the generated index-cdn.html or index-nocdn.html

I would imagine you would really want to think long and hard about the security impact of pushing application bundles into a CDN.  

It might be best to just push css bundles, fonts and images to CDN.

**Comment by StefanRKarlsson** [comment]
Thats one option that can work, the only problem i can see is how to implement the fallback mecanism.

What security issues do you mean? Clientside code is allways visible. What would putting it in CDN change?

**Comment by martinmcwhorter** [comment]
The security implication is not that the bundles can be read. The concern
is that your application is only as secure as your CDN provider when you
offload JavaScript bundles.

This is not so much a concern for css bundles, fonts and images.

**Comment by brookhutchinson** [comment]
How do you implement a CDN with a fallback solution inside an Angular Project that was created with angular-cli.  I have the same environment as @StefanRKarlsson

I am having trouble understanding how to implement the fallback solution to the local CSS and JavaScript File References when the CDN is unavailable. I would like to define the CSS files and JavaScript CSS files inside angular-cli.json using the styles property and scripts property and then have the angular-cli to inject the local reference to a CSS or a JavaScript only if the CDN is not available.

In projects that are not angular-cli projets here is the code that I use to reference a CDN and then fallback if CDN is unavailable... (jquery, tether, bootstrap)

`
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>

<script>window.jQuery || document.write('<script src="app/js/jquery.min.js"><\/script>')</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>

<script>window.Tether || document.write('<script src="app/js/tether.min.js"><\/script>')</script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>

<script>$.fn.modal || document.write('<script src="app/js/bootstrap.min.js"><\/script>')</script>`

**Comment by filipesilva** [comment]
Dupe of https://github.com/angular/angular-cli/issues/1310
