### ISSUE TITLE
--aot support for github-pages:deploy

### ISSUE THREAD

**Issue by CanKattwinkel** [angular/angular-cli#3939]
### OS?
Ubuntu 16.04

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.5.0
os: linux x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/compiler-cli: 2.4.2
@angular/core: 2.4.2
@angular/flex-layout: 2.0.0-beta.1
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.3.1

### Repro steps.
`ng github-pages:deploy --aot
`
### The log given by the failure.
The option '--aot' is not registered with the github-pages:deploy command. Run `ember github-pages:deploy --help` for a list of supported options.

**Comment by scttcper** [comment]
https://github.com/angular/angular-cli/pull/3776
