### ISSUE TITLE
Styles .js bundle generated for production

### ISSUE THREAD

**Issue by ShadowManu** [angular/angular-cli#3942]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux Ubuntu 16.04 x64

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.24
node: 6.9.2
os: linux x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Yes

### The log given by the failure.
> Normally this include a stack trace and some more information.
No errors

### Mention any other details that might be useful.
I'm not sure if its a bug, but in former versions production bundles packaged the styles in a `styles.[hash].bundle.js` file. Now it looks that is bundled in a `.css` file.

However, there's still a `styles.[hash].bundle.js.gz` file generated, although never requested by the app. Maybe its something that needs to be cleaned up in webpack? It gets generated when running `ng build --prod --aot`.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
This is fixed now as far as I can tell:

```
$ ls -la dist/
total 592
drwxr-xr-x 1 kamik 197609      0 Jan 24 15:07 ./
drwxr-xr-x 1 kamik 197609      0 Jan 24 15:07 ../
-rw-r--r-- 1 kamik 197609   5430 Jan 24 15:07 favicon.ico
-rw-r--r-- 1 kamik 197609    721 Jan 24 15:07 index.html
-rw-r--r-- 1 kamik 197609   1460 Jan 24 15:07 inline.822fa779af434f39d08b.bundle.js
-rw-r--r-- 1 kamik 197609  13544 Jan 24 15:07 main.cce079314a9ce4a931da.bundle.js
-rw-r--r-- 1 kamik 197609   3309 Jan 24 15:07 main.cce079314a9ce4a931da.bundle.js.gz
-rw-r--r-- 1 kamik 197609  83728 Jan 24 15:07 polyfills.8fd3cf3f83a10c5c5736.bundle.js
-rw-r--r-- 1 kamik 197609  26583 Jan 24 15:07 polyfills.8fd3cf3f83a10c5c5736.bundle.js.gz
-rw-r--r-- 1 kamik 197609      0 Jan 24 15:07 styles.d41d8cd98f00b204e980.bundle.css
-rw-r--r-- 1 kamik 197609 368101 Jan 24 15:07 vendor.f170748eaff64ce6f8f8.bundle.js
-rw-r--r-- 1 kamik 197609  73882 Jan 24 15:07 vendor.f170748eaff64ce6f8f8.bundle.js.gz
```
