### ISSUE TITLE
App performance issues

### ISSUE THREAD

**Issue by PEsteves8** [angular/angular-cli#3948]
I noticed than in an app that I'm building, which frequently has a lot of in memory data (large table data), the app gets significantly slower with user interaction after AOT, than with JIT. 

Is this something to be expected? A side effect that wasn't mentioned?

I'm not sure if I should consider this a bug or a support request.

I'm specifically using ng-bootstrap and ngx-datatable. The bundled aot version using angular cli, is a lot faster to load, as promised. However, the larger the amount of data being available in memory (from the data tables), the more noticeable it is the delay when clicking a dropdown or any other user interaction. With the JIT version, everything works much faster.

Is this something already known? Maybe having a lot of in memory data is known to cause this. I tried using gitter, but had no answers. Thanks

### OS?
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.24
node: 4.4.5
os: win32 x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2

### Repro steps.
> Originally it wasn't created on the cli. I decided to migrate it to make use of aot and bundling, since following the instructions of aot without the cli always produced errors.
I then created an new cli project, and moved my code to it.

EDIT:
Actually it seems this only happens in chrome Version 55.0.2883.87 m
Edge gets slightly faster with AOT, and firefox is about the same.

**Comment by deebloo** [comment]
Can you share the exact xmand you are running to generate the bundle?

**Comment by deebloo** [comment]
Command*

**Comment by PEsteves8** [comment]
I used: ng build --prod --aot

I suppose I should try to keep smaller quantities of data in memory and use server pagination or similar solutions to avoid that. Also, from what I saw, although ngx-datatable is well designed, it's also possible that the large amount of features end up with heavy performance costs. 

Independently of that, it's still weird that on chrome things seem to be slower after build.

**Comment by gelliott181** [comment]
I think you're seeing the effects of Angular's overhead at this point. Browsers may not be willing or able to store all your data to memory due to OS restrictions or caching profiles. Have you considered storing and accessing your data as part of the [IndexDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API)?

**Comment by filipesilva** [comment]
There's some nice advice from @gelliott181, thanks! I have to close the issue though, this isn't a CLI question but rather a more general Angular one.

**Comment by PEsteves8** [comment]
Thanks! I posted as a CLI issue, because it specifically happened only when using the cli. Anyway, whatever it was, it seems to be fine now. Thanks, guys. :)
