### ISSUE TITLE
Where is app.module.ts file?

### ISSUE THREAD

**Issue by kingkarki** [angular/angular-cli#3949]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
angular-cli: 0.0.39
node: 6.9.4
os: darwin x64
mac version: 10.12.1  

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 0.0.39
Node version: v6.9.4

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
  `ng new myapp
`
There is no app.module.ts file on my src folder in project. Is app.module.ts depreciated or i m angular cli wrong version or something is wrong? 

App works when i do ng server. But i m unable to find app.module.ts file. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by baruchvlz** [comment]
Current version is 1.0.0-beta.24. Also, to create a new app run 'ng new myApp'.

**Comment by kingkarki** [comment]
i just installed angular cli today. how it is came version 0.0.39? I did with  ` ng new myapp ` but still app.module.ts is missing. How can i upgrade the cli version?

**Comment by baruchvlz** [comment]
``` bash
npm uninstall angular-cli --global
npm cache clean
npm install --global angular-cli@latest
``
When you run `ng new myApp` the file should be under `src/app`.

**Comment by filipesilva** [comment]
Closing as answered by @baruchvlz.
