### ISSUE TITLE
Able to extend webpack config from angular-cli.json

### ISSUE THREAD

**Issue by feng-xiao** [angular/angular-cli#3951]
> Please provide us with the following information:
> ---------------------------------------------------------------
Please provide a way to extend webpack configuration, e.g. rules, plugins, etc. Similar to what it's done for scripts and styles. I like to modify sourcecode's content on the fly, I can't do it without adding new rules to webpack.

### OS?
> Windows 10

### Versions.
> 1.0.0-beta.24

### Repro steps.
> no issues

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Dupe of https://github.com/angular/angular-cli/issues/1656
