### ISSUE TITLE
Allow path exclusion for AoT builds

### ISSUE THREAD

**Issue by SebastianSchenk** [angular/angular-cli#3953]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OSX El Capitan 10.11.4

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.24
node: 6.7.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

- Create a new app with `ng new my-app`
- Add a folder called testing in /app/src
- Add a file to the testing folder called router-stubs.ts
- Add a stub for RouterLink to this file:
`export class RouterLinkStubDirective {`
  `@Input('routerLink') linkParams: any;`
  `navigatedTo: any = null;`

  `onClick() {`
    `this.navigatedTo = this.linkParams;`
  `}`
`}`

- Run `ng build --prod --aot`

- The following error will occur: Cannot determine the module for class RouterLinkStubDirective 

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

According to the official Angular AOT documentation, an own tsconfig-aot.json should be used for AOT compiling. [https://angular.io/docs/ts/latest/cookbook/aot-compiler.html]
The CLI is currently using the normal tsconfig.json for AOT, which leads to some problems. In AOT I have to exclude some paths like my testing folder that includes my stubs. Otherwise it will lead to errors like: Cannot determine the module for class RouterLinkStubDirective.

It would be great to pass a tsconfig to the aot flag or to use tsconfig-aot.json by default for AOT compiling.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattdistefano** [comment]
You can just create a module for your testing code and the error will go away. That seems cleaner than maintaining separate tsconfigs, unless there's another use case for them.

**Comment by filipesilva** [comment]
The CLI does not need a separate tsconfig, this is by design. 

The feature to ignore some paths makes sense though. I'll edit your issue name to reflect this, since otherwise it won't be very actionable.

**Comment by kailashravuri** [comment]
With new CLI apps, You can mention exclude files and paths in tsconfig.app.json. where tsconfig.app.json is default file as part of angular cli seed project teample.

"exclude": [
    "test.ts",
    "**/*.spec.ts",
    "testing/helpers/**.ts"
  ]

**Comment by gpradeepjain** [comment]
I have a folder inside assets folder called mockJson. I am trying to skip this folder in build. I made changes like 
"exclude": [
"test.ts",
"/*.spec.ts",
"assets/mockJson/*"
]

But could not see any changes. folder or files was still included in build.

**Comment by filipesilva** [comment]
@gpradeepjain changing the `tsconfig` files only relates to typescript configuration. If you want to not include that file in the assets array, you have to not add it there in the first place.
