### ISSUE TITLE
Assets are not being copied to dist folder

### ISSUE THREAD

**Issue by tsm91** [angular/angular-cli#3957]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

ububntu 1604, win 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```sh
angular-cli: local (v1.0.0-beta.24, branch: master)
node: 6.9.2
os: linux x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Create an `img` sub directory under assets, place an image file inside `smth.png`. With `ng serve` the img is being served by the webpack-dev-server, however if you do `ng build --prod`. The `web/dist` does not contain `smth.png`, neither a hashed version of it.

```json
"apps": [
    {
      "root": "frontend",
      "outDir": "web/dist",
      "assets": [
        "assets/i18n",
        "assets/img",
        "assets/mocks"
      ],
```

Including ` "assets/img",` i expected to see this file under `web/dist`. 

### The log given by the failure.
> Normally this include a stack trace and some more information.

no error happens during the process

### Mention any other details that might be useful.

These are files not being referenced in css or javascript. So it skips the bundling process. I used to use https://github.com/kevlened/copy-webpack-plugin for this.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I added edited the following entries in `angular-cli.json`:

```
// ...
      "outDir": "web/dist",
      "assets": [
        "assets/img",
        "favicon.ico"
      ],
```

And ran the following commands:
```
kamik@T460p MINGW64 /D/sandbox/master-project (master)
$ mkdir src/assets/img

kamik@T460p MINGW64 /D/sandbox/master-project (master)
$ touch src/assets/img/smth.png

kamik@T460p MINGW64 /D/sandbox/master-project (master)
$ git st
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        src/assets/img/

nothing added to commit but untracked files present (use "git add" to track)

kamik@T460p MINGW64 /D/sandbox/master-project (master)
$ ng build
Hash: e370f84e614ba873508e
Time: 11070ms
chunk    {0} main.bundle.js, main.bundle.map (main) 10.4 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 1.77 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.6 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

kamik@T460p MINGW64 /D/sandbox/master-project (master)
$ ls web/dist/in
index.html         inline.bundle.js   inline.bundle.map

kamik@T460p MINGW64 /D/sandbox/master-project (master)
$ ls web/dist/assets/img/
smth.png
```

The image is copied over and is present in `web/dist/assets/img/`.

**Comment by tsm91** [comment]
Sorry i was wrong, it is working

**Comment by sgentile** [comment]
it is also - for me - including the contents of the file inside the bundle - ie. I have a JSON file in assets that is copied properly, but it's also including it in the bundle
