### ISSUE TITLE
ng serve - webpack: bundle is now VALID

### ISSUE THREAD

**Issue by memboc** [angular/angular-cli#3965]
**$ cmd /k ver**
Microsoft Windows x64 [Version 6.3.9600]

**$ node -v**
v6.9.4

**$ npm -v**
3.10.10

**$ npm install -g angular-cli**
```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\User\AppData\Roaming\npm\ng -> C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
- es6-symbol@3.1.0 node_modules\angular-cli\node_modules\es6-symbol
- array-index@1.0.0 node_modules\angular-cli\node_modules\array-index
- es6-iterator@2.0.0 node_modules\angular-cli\node_modules\es6-iterator
- es5-ext@0.10.12 node_modules\angular-cli\node_modules\es5-ext
- d@0.1.1 node_modules\angular-cli\node_modules\d
supports-color@0.2.0 node_modules\angular-cli\node_modules\npmlog\node_modules\supports-color -> node_modules\angular-cli\node_modules\gauge\node_modules\supports-color
- has-color@0.1.7 node_modules\angular-cli\node_modules\has-color
- npmlog@3.1.2 node_modules\angular-cli\node_modules\node-gyp\node_modules\npmlog
- gauge@2.7.2 node_modules\angular-cli\node_modules\npmlog\node_modules\gauge
- path-array@1.0.1 node_modules\angular-cli\node_modules\path-array
C:\Users\User\AppData\Roaming\npm
`-- angular-cli@1.0.0-beta.24
  +-- @angular/compiler@2.4.3
  +-- @angular/compiler-cli@2.4.3
  +-- @angular/core@2.4.3
  +-- autoprefixer@6.6.1
  | +-- caniuse-db@1.0.30000607
  | `-- postcss@5.2.9
  +-- css-loader@0.23.1
  | +-- cssnano@3.10.0
  | | +-- postcss-merge-rules@2.1.1
  | | | `-- caniuse-api@1.5.2
  | | |   +-- lodash.memoize@4.1.2
  | | |   +-- lodash.uniq@4.5.0
  | | |   `-- shelljs@0.7.6
  | | |     `-- rechoir@0.6.2
  | | +-- postcss-normalize-url@3.0.8
  | | | `-- normalize-url@1.9.0
  | | `-- postcss-ordered-values@2.2.3
  | `-- source-list-map@0.1.8
  +-- node-sass@3.13.1
  | +-- node-gyp@3.5.0
  | `-- npmlog@4.0.2
  |   `-- gauge@2.7.2
  +-- source-map-loader@0.1.6
  +-- webpack@2.1.0-beta.25
  | `-- tapable@0.2.6
  `-- webpack-merge@0.14.1
    `-- lodash.isequal@4.5.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\angular-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

**$ ng -v**
```
angular-cli: 1.0.0-beta.24
node: 6.9.4
os: win32 x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3
```

**$ ng new my-app --link-cli**
```
installing ng2
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.json
  create angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tslint.json
Successfully initialized git.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Successfully linked to angular-cli.
```

**$ cd my-app**
**$ ng serve**
```
Hash: f384e4b9cc9230719983
Time: 6263ms
chunk    {0} main.bundle.js, main.bundle.map (main) 58.7 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 1.77 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 176 kB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (D:\projects\ng\my-app\node_modules\typescript\lib\typescript.js:8062:20)
    at Object.createCompilerHost (D:\projects\ng\my-app\node_modules\typescript\lib\typescript.js:44978:26)
    at Object.ngcLoader (D:\projects\ng\my-app\node_modules\@ngtools\webpack\src\loader.js:171:31)
 @ multi main
webpack: bundle is now VALID.
```

localhost:4200 writes only `Loading...`

**Comment by alanjhonnes** [comment]
Check your console, you probably have a runtime error.

**Comment by adammendoza** [comment]
Any fix for this so far?

**Comment by adammendoza** [comment]
As a workaround I deleted node_modules, updated the typescript devDependency manually to "typescript": "~2.0.10" and ran npm install again. The app started without errors.

**Comment by gelliott181** [comment]
This isn't a bug, your application isn't properly written and therefore won't load. Check the browser console for an error.

**Comment by gelliott181** [comment]
You likely didn't have the right Typescript installed which meant your app would compile to invalid JS. As you said, updating TS worked for you. Next time something like this happens check out the browser console for a more verbose error.

**Comment by adammendoza** [comment]
Thanks gelliot181, this is only about my 10th Angular 2 app. However, I'm new to angular-cli and I mistakenly thought it produced a working app.

**Comment by gelliott181** [comment]
It does, however given this is not your first Angular 2 app, you likely had pre-existing TypeScript artifacts that matched the Semver, especially if you've had TypeScript installed globally. A framework CLI tool can't help you manage packages (That's all NPM.)

**Comment by filipesilva** [comment]
Closing as solved.

**Comment by gatemediang** [comment]
I have this during ng serve
 67% building modules 545/564 modules 19 active ...node_modules\@angular\common\
 68% building modules 546/564 modules 18 active ...node_modules\@angular\common\
 68% building modules 547/564 modules 17 active ...node_modules\@angular\common\
 68% building modules 548/564 modules 16 active ...node_modules\@angular\common\
 68% building modules 548/565 modules 17 active ...orapp\node_modules\debug\src\
 68% building modules 549/565 modules 16 active ...orapp\node_modules\debug\src\
 68% building modules 550/565 modules 15 active ...orapp\node_modules\debug\src\
 68% building modules 551/565 modules 14 active ...orapp\node_modules\debug\src\
 68% building modules 552/565 modules 13 active ...orapp\node_modules\debug\src\
 68% building modules 553/565 modules 12 active ...orapp\node_modules\debug\src\
 68% building modules 553/566 modules 13 active ...odules\webpack\buildin\amd-op
 68% building modules 554/566 modules 12 active ...odules\webpack\buildin\amd-op
 68% building modules 554/567 modules 13 active ...c\directives\number_value_acc
 68% building modules 554/568 modules 14 active ...rc\directives\range_value_acc
 68% building modules 554/569 modules 15 active ...\rxjs\util\ObjectUnsubscribed
 68% building modules 554/570 modules 16 active ...torapp\node_modules\rxjs\util
 68% building modules 554/571 modules 17 active ...ode_modules\rxjs\util\toSubsc
 68% building modules 554/572 modules 18 active ...e_modules\rxjs\symbol\rxSubsc
 68% building modules 554/573 modules 19 active ...ode_modules\rxjs\symbol\obser
 68% building modules 555/573 modules 18 active ...ode_modules\rxjs\symbol\obser
 68% building modules 555/574 modules 19 active ...e\src\animation\view_animatio
 68% building modules 556/574 modules 18 active ...e\src\animation\view_animatio
 68% building modules 556/575 modules 19 active ...wser\src\dom\web_animations_p
 67% building modules 556/576 modules 20 active ...rc\browser\generic_browser_ad
 67% building modules 556/577 modules 21 active ...\@angular\compiler\src\identi
 67% building modules 556/578 modules 22 active ...s\@angular\compiler\src\injec
 67% building modules 556/579 modules 23 active ...r\compiler\src\private_import
 67% building modules 556/580 modules 24 active ...angular\compiler\src\ml_parse
 67% building modules 556/581 modules 25 active ...ar\compiler\src\style_url_res
 67% building modules 556/582 modules 26 active ...template_parser\template_prep
 67% building modules 556/583 modules 27 active ...\compiler\src\output\class_bu
 67% building modules 556/584 modules 28 active ...lar\compiler\src\output\outpu
 67% building modules 556/585 modules 29 active ...lar\compiler\src\output\value
 66% building modules 556/586 modules 30 active ...lar\compiler\src\provider_ana
 66% building modules 556/587 modules 31 active ...odules\@angular\compiler\src\
 66% building modules 556/588 modules 32 active ...src\template_parser\binding_p
 66% building modules 556/589 modules 33 active ...s\@angular\compiler\src\asser
 66% building modules 556/590 modules 34 active ...r\compiler\src\lifecycle_refl
 66% building modules 556/591 modules 35 active ...s\@angular\compiler\src\shado
 66% building modules 556/592 modules 36 active ...r\compiler\src\ml_parser\html
 66% building modules 556/593 modules 37 active ...compiler\src\i18n\i18n_html_p
 66% building modules 556/594 modules 38 active ...r\src\animation\animation_com
 66% building modules 556/595 modules 39 active ...ar\compiler\src\aot\generated
 65% building modules 556/596 modules 40 active ...ompiler\src\aot\summary_seria
 65% building modules 556/597 modules 41 active ...ler\src\ml_parser\icu_ast_exp
 65% building modules 556/598 modules 42 active ...ngular\compiler\src\ml_parser
 65% building modules 556/599 modules 43 active ...iler\src\output\output_interp
 65% building modules 556/600 modules 44 active ...lar\compiler\src\output\outpu
 65% building modules 556/601 modules 45 active ...ular\compiler\src\ml_parser\p
 65% building modules 556/602 modules 46 active ...ngular\compiler\src\i18n\extr
 65% building modules 556/603 modules 47 active ...r\compiler\src\i18n\message_b
 65% building modules 556/604 modules 48 active ...ler\src\schema\dom_security_s
 65% building modules 556/605 modules 49 active ...\src\view_compiler\compile_el
 65% building modules 556/606 modules 50 active ...ler\src\view_compiler\compile
 64% building modules 556/607 modules 51 active ...iler\src\view_compiler\view_b
 64% building modules 556/608 modules 52 active ...ler\src\view_compiler\view_bu
 64% building modules 556/609 modules 53 active ...ar\compiler\src\view_compiler
 64% building modules 556/610 modules 54 active ...mpiler\src\output\abstract_em
 64% building modules 556/611 modules 55 active ...compiler\src\expression_parse
 64% building modules 556/612 modules 56 active ...mpiler\src\animation\animatio
 64% building modules 556/613 modules 57 active ...er\src\animation\styles_colle
 64% building modules 557/613 modules 56 active ...er\src\animation\styles_colle
 64% building modules 558/613 modules 55 active ...er\src\animation\styles_colle
 64% building modules 559/613 modules 54 active ...er\src\animation\styles_colle
 64% building modules 559/614 modules 55 active ...\lib\transport\lib\buffered-s
 64% building modules 559/615 modules 56 active ...s-client\lib\transport\lib\po
 64% building modules 559/616 modules 57 active ...src\directives\normalize_vali
 64% building modules 559/617 modules 58 active ...owser\src\browser\location\hi
 64% building modules 559/618 modules 59 active ...\@angular\compiler\src\facade
 64% building modules 559/619 modules 60 active ...lar\compiler\src\facade\colle
 64% building modules 559/620 modules 61 active ...angular\compiler\src\facade\e
 64% building modules 559/621 modules 62 active ...\src\compiler_util\identifier
 63% building modules 559/622 modules 63 active ...ler\src\compiler_util\binding
 63% building modules 559/623 modules 64 active ...compiler_util\expression_conv
 63% building modules 559/624 modules 65 active ...iler\src\compiler_util\render
 63% building modules 559/625 modules 66 active ...er\src\i18n\serializers\seria
 63% building modules 559/626 modules 67 active ...ompiler\src\i18n\serializers\
 63% building modules 559/627 modules 68 active ...\compiler\src\i18n\serializer
 63% building modules 559/628 modules 69 active ...\compiler\src\i18n\serializer
 63% building modules 559/629 modules 70 active ...latform-browser\src\facade\br
 63% building modules 559/630 modules 71 active ...modules\_array-species-constr
 63% building modules 559/631 modules 72 active ...lib\transport\browser\abstrac
 63% building modules 559/632 modules 73 active ...s\core-js\modules\_collection
 62% building modules 559/633 modules 74 active ...orms\src\directives\error_exa
 62% building modules 559/634 modules 75 active ...\rxjs\observable\PromiseObser
 62% building modules 560/634 modules 74 active ...\rxjs\observable\PromiseObser
 63% building modules 561/634 modules 73 active ...\rxjs\observable\PromiseObser
 63% building modules 562/634 modules 72 active ...\rxjs\observable\PromiseObser
 63% building modules 563/634 modules 71 active ...\rxjs\observable\PromiseObser
 63% building modules 564/634 modules 70 active ...\rxjs\observable\PromiseObser
 63% building modules 565/634 modules 69 active ...\rxjs\observable\PromiseObser
 63% building modules 565/635 modules 70 active ...p\node_modules\requires-port\
 63% building modules 566/635 modules 69 active ...p\node_modules\requires-port\
 63% building modules 566/636 modules 70 active ...\node_modules\querystringify\
 63% building modules 567/636 modules 69 active ...\node_modules\querystringify\
 63% building modules 568/636 modules 68 active ...\node_modules\querystringify\
 63% building modules 569/636 modules 67 active ...\node_modules\querystringify\
 63% building modules 570/636 modules 66 active ...\node_modules\querystringify\
 63% building modules 571/636 modules 65 active ...\node_modules\querystringify\
 63% building modules 572/636 modules 64 active ...\node_modules\querystringify\
 64% building modules 573/636 modules 63 active ...\node_modules\querystringify\
 64% building modules 574/636 modules 62 active ...\node_modules\querystringify\
 64% building modules 575/636 modules 61 active ...\node_modules\querystringify\
 64% building modules 576/636 modules 60 active ...\node_modules\querystringify\
 64% building modules 577/636 modules 59 active ...\node_modules\querystringify\
 64% building modules 578/636 modules 58 active ...\node_modules\querystringify\
 64% building modules 579/636 modules 57 active ...\node_modules\querystringify\
 64% building modules 580/636 modules 56 active ...\node_modules\querystringify\
 64% building modules 581/636 modules 55 active ...\node_modules\querystringify\
 64% building modules 582/636 modules 54 active ...\node_modules\querystringify\
 64% building modules 583/636 modules 53 active ...\node_modules\querystringify\
 65% building modules 584/636 modules 52 active ...\node_modules\querystringify\
 65% building modules 585/636 modules 51 active ...\node_modules\querystringify\
 65% building modules 586/636 modules 50 active ...\node_modules\querystringify\
 65% building modules 587/636 modules 49 active ...\node_modules\querystringify\
 65% building modules 588/636 modules 48 active ...\node_modules\querystringify\
 65% building modules 589/636 modules 47 active ...\node_modules\querystringify\
 65% building modules 590/636 modules 46 active ...\node_modules\querystringify\
 65% building modules 591/636 modules 45 active ...\node_modules\querystringify\
 65% building modules 592/636 modules 44 active ...\node_modules\querystringify\
 65% building modules 593/636 modules 43 active ...\node_modules\querystringify\
 66% building modules 594/636 modules 42 active ...\node_modules\querystringify\
 66% building modules 595/636 modules 41 active ...\node_modules\querystringify\
 66% building modules 596/636 modules 40 active ...\node_modules\querystringify\
 66% building modules 597/636 modules 39 active ...\node_modules\querystringify\
 66% building modules 598/636 modules 38 active ...\node_modules\querystringify\
 66% building modules 599/636 modules 37 active ...\node_modules\querystringify\
 66% building modules 600/636 modules 36 active ...\node_modules\querystringify\
 66% building modules 601/636 modules 35 active ...\node_modules\querystringify\
 66% building modules 602/636 modules 34 active ...\node_modules\querystringify\
 66% building modules 603/636 modules 33 active ...\node_modules\querystringify\
 66% building modules 604/636 modules 32 active ...\node_modules\querystringify\
 67% building modules 605/636 modules 31 active ...\node_modules\querystringify\
 67% building modules 606/636 modules 30 active ...\node_modules\querystringify\
 67% building modules 607/636 modules 29 active ...\node_modules\querystringify\
 67% building modules 608/636 modules 28 active ...\node_modules\querystringify\
 67% building modules 609/636 modules 27 active ...\node_modules\querystringify\
 67% building modules 610/636 modules 26 active ...\node_modules\querystringify\
 67% building modules 611/636 modules 25 active ...\node_modules\querystringify\
 67% building modules 612/636 modules 24 active ...\node_modules\querystringify\
 67% building modules 613/636 modules 23 active ...\node_modules\querystringify\
 67% building modules 614/636 modules 22 active ...\node_modules\querystringify\
 68% building modules 615/636 modules 21 active ...\node_modules\querystringify\
 67% building modules 615/637 modules 22 active ...\node_modules\rxjs\util\isFun
 67% building modules 615/638 modules 23 active ...ctorapp\node_modules\rxjs\Obs
 67% building modules 615/639 modules 24 active ...app\node_modules\rxjs\util\is
 67% building modules 615/640 modules 25 active ...pp\node_modules\rxjs\util\isO
 67% building modules 615/641 modules 26 active ...pp\node_modules\rxjs\util\try
 67% building modules 615/642 modules 27 active ...node_modules\rxjs\util\errorO
 67% building modules 615/643 modules 28 active ...ules\rxjs\util\Unsubscription
 67% building modules 616/643 modules 27 active ...ules\rxjs\util\Unsubscription
 67% building modules 617/643 modules 26 active ...ules\rxjs\util\Unsubscription
 67% building modules 618/643 modules 25 active ...ules\rxjs\util\Unsubscription
 67% building modules 619/643 modules 24 active ...ules\rxjs\util\Unsubscription
 67% building modules 620/643 modules 23 active ...ules\rxjs\util\Unsubscription
 67% building modules 621/643 modules 22 active ...ules\rxjs\util\Unsubscription
 68% building modules 622/643 modules 21 active ...ules\rxjs\util\Unsubscription
 68% building modules 623/643 modules 20 active ...ules\rxjs\util\Unsubscription
 68% building modules 624/643 modules 19 active ...ules\rxjs\util\Unsubscription
 68% building modules 625/643 modules 18 active ...ules\rxjs\util\Unsubscription
 68% building modules 626/643 modules 17 active ...ules\rxjs\util\Unsubscription
 68% building modules 627/643 modules 16 active ...ules\rxjs\util\Unsubscription
 68% building modules 628/643 modules 15 active ...ules\rxjs\util\Unsubscription
 68% building modules 629/643 modules 14 active ...ules\rxjs\util\Unsubscription
 68% building modules 630/643 modules 13 active ...ules\rxjs\util\Unsubscription
 68% building modules 631/643 modules 12 active ...ules\rxjs\util\Unsubscription
 68% building modules 632/643 modules 11 active ...ules\rxjs\util\Unsubscription
 69% building modules 633/643 modules 10 active ...ules\rxjs\util\Unsubscription
 68% building modules 633/644 modules 11 active ...modules\@angular\common\src\c
 69% building modules 634/644 modules 10 active ...modules\@angular\common\src\c
 68% building modules 634/645 modules 11 active ...compiler\src\i18n\extractor_m
 68% building modules 634/646 modules 12 active ...mpiler\src\i18n\translation_b
 68% building modules 634/647 modules 13 active ...ler\src\output\abstract_js_em
 68% building modules 634/648 modules 14 active ...gular\compiler\src\ml_parser\
 68% building modules 634/649 modules 15 active ...r\src\view_compiler\compile_m
 68% building modules 634/650 modules 16 active ...ler\src\view_compiler\compile
 68% building modules 634/651 modules 17 active ...er\src\view_compiler\compile_
 68% building modules 634/652 modules 18 active ...ar\compiler\src\view_compiler
 68% building modules 634/653 modules 19 active ...mpiler\src\view_compiler\cons
 68% building modules 634/654 modules 20 active ...ler\src\view_compiler\event_b
 68% building modules 634/655 modules 21 active ...src\view_compiler\lifecycle_b
 67% building modules 634/656 modules 22 active ...\src\view_compiler\property_b
 67% building modules 634/657 modules 23 active ...ler\src\view_compiler\query_b
 67% building modules 634/658 modules 24 active ...\compiler\src\ml_parser\xml_p
 67% building modules 634/659 modules 25 active ...\@angular\compiler\src\i18n\d
 67% building modules 634/660 modules 26 active ...angular\compiler\src\i18n\i18
 67% building modules 634/661 modules 27 active ...gular\compiler\src\i18n\parse
 67% building modules 634/662 modules 28 active ...er\src\i18n\serializers\xml_h
 67% building modules 635/662 modules 27 active ...er\src\i18n\serializers\xml_h
 67% building modules 636/662 modules 26 active ...er\src\i18n\serializers\xml_h
 67% building modules 637/662 modules 25 active ...er\src\i18n\serializers\xml_h
 67% building modules 638/662 modules 24 active ...er\src\i18n\serializers\xml_h
 67% building modules 639/662 modules 23 active ...er\src\i18n\serializers\xml_h
 68% building modules 640/662 modules 22 active ...er\src\i18n\serializers\xml_h
 68% building modules 641/662 modules 21 active ...er\src\i18n\serializers\xml_h
 68% building modules 642/662 modules 20 active ...er\src\i18n\serializers\xml_h
 68% building modules 643/662 modules 19 active ...er\src\i18n\serializers\xml_h
 68% building modules 644/662 modules 18 active ...er\src\i18n\serializers\xml_h
 68% building modules 645/662 modules 17 active ...er\src\i18n\serializers\xml_h
 68% building modules 646/662 modules 16 active ...er\src\i18n\serializers\xml_h
 68% building modules 647/662 modules 15 active ...er\src\i18n\serializers\xml_h
 68% building modules 648/662 modules 14 active ...er\src\i18n\serializers\xml_h
 68% building modules 649/662 modules 13 active ...er\src\i18n\serializers\xml_h
 68% building modules 650/662 modules 12 active ...er\src\i18n\serializers\xml_h
 69% building modules 651/662 modules 11 active ...er\src\i18n\serializers\xml_h
 69% building modules 652/662 modules 10 active ...er\src\i18n\serializers\xml_h
 69% building modules 653/662 modules 9 active ...er\src\i18n\serializers\xml_he
 69% building modules 654/662 modules 8 active ...er\src\i18n\serializers\xml_he
 69% building modules 655/662 modules 7 active ...er\src\i18n\serializers\xml_he
 69% building modules 655/663 modules 8 active ...collectorapp\node_modules\ms\i
 69% building modules 656/663 modules 7 active ...collectorapp\node_modules\ms\i
 69% building modules 657/663 modules 6 active ...collectorapp\node_modules\ms\i
 69% building modules 658/663 modules 5 active ...collectorapp\node_modules\ms\i
 69% building modules 659/663 modules 4 active ...collectorapp\node_modules\ms\i
 69% building modules 660/663 modules 3 active ...collectorapp\node_modules\ms\i
 69% building modules 661/663 modules 2 active ...collectorapp\node_modules\ms\i
 69% building modules 662/663 modules 1 active ...collectorapp\node_modules\ms\i
 69% building modules 662/664 modules 2 active ...s\@angular\common\src\localiza
 69% building modules 662/665 modules 3 active ...\@angular\common\src\common_mo
 69% building modules 662/666 modules 4 active ...odules\@angular\common\src\ver
 69% building modules 662/667 modules 5 active ...ular\compiler\src\i18n\i18n_pa
 69% building modules 662/668 modules 6 active ...@angular\common\src\location\i
 69% building modules 662/669 modules 7 active ...ngular\common\src\directives\i
 69% building modules 662/670 modules 8 active ...es\@angular\common\src\pipes\i
 69% building modules 662/671 modules 9 active ...ar\compiler\src\ml_parser\xml_
 69% building modules 663/671 modules 8 active ...ar\compiler\src\ml_parser\xml_
 69% building modules 664/671 modules 7 active ...ar\compiler\src\ml_parser\xml_
 69% building modules 665/671 modules 6 active ...ar\compiler\src\ml_parser\xml_
 69% building modules 666/671 modules 5 active ...ar\compiler\src\ml_parser\xml_
 69% building modules 667/671 modules 4 active ...ar\compiler\src\ml_parser\xml_
 69% building modules 668/671 modules 3 active ...ar\compiler\src\ml_parser\xml_
 69% building modules 669/671 modules 2 active ...ar\compiler\src\ml_parser\xml_
 69% building modules 670/671 modules 1 active ...ar\compiler\src\ml_parser\xml_
 69% building modules 671/672 modules 1 active ...r\src\i18n\serializers\placeho
 69% building modules 671/673 modules 2 active ...mon\src\location\platform_loca
 69% building modules 671/674 modules 3 active ...mon\src\location\location_stra
 69% building modules 671/675 modules 4 active ...rc\location\hash_location_stra
 69% building modules 671/676 modules 5 active ...rc\location\path_location_stra
 69% building modules 671/677 modules 6 active ...gular\common\src\location\loca
 69% building modules 671/678 modules 7 active ...lar\common\src\directives\ng_c
 69% building modules 671/679 modules 8 active ...gular\common\src\directives\ng
 69% building modules 671/680 modules 9 active ...ngular\common\src\directives\n
 69% building modules 671/681 modules 10 active ...ar\common\src\directives\ng_p
 69% building modules 671/682 modules 11 active ...lar\common\src\directives\ng_
 68% building modules 671/683 modules 12 active ...ar\common\src\directives\ng_s
 68% building modules 671/684 modules 13 active ...\src\directives\ng_template_o
 68% building modules 671/685 modules 14 active ...ngular\common\src\pipes\async
 68% building modules 671/686 modules 15 active ...angular\common\src\pipes\date
 68% building modules 671/687 modules 16 active ...\common\src\pipes\i18n_plural
 68% building modules 671/688 modules 17 active ...\common\src\pipes\i18n_select
 68% building modules 671/689 modules 18 active ...angular\common\src\pipes\json
 68% building modules 671/690 modules 19 active ...ar\common\src\pipes\lowercase
 68% building modules 671/691 modules 20 active ...gular\common\src\pipes\number
 68% building modules 671/692 modules 21 active ...ngular\common\src\pipes\slice
 68% building modules 671/693 modules 22 active ...ar\common\src\pipes\uppercase
 68% building modules 672/693 modules 21 active ...ar\common\src\pipes\uppercase
 68% building modules 673/693 modules 20 active ...ar\common\src\pipes\uppercase
 68% building modules 674/693 modules 19 active ...ar\common\src\pipes\uppercase
 68% building modules 675/693 modules 18 active ...ar\common\src\pipes\uppercase
 68% building modules 676/693 modules 17 active ...ar\common\src\pipes\uppercase
 68% building modules 677/693 modules 16 active ...ar\common\src\pipes\uppercase
 68% building modules 678/693 modules 15 active ...ar\common\src\pipes\uppercase
 68% building modules 679/693 modules 14 active ...ar\common\src\pipes\uppercase
 68% building modules 680/693 modules 13 active ...ar\common\src\pipes\uppercase
 68% building modules 681/693 modules 12 active ...ar\common\src\pipes\uppercase
 69% building modules 682/693 modules 11 active ...ar\common\src\pipes\uppercase
 69% building modules 683/693 modules 10 active ...ar\common\src\pipes\uppercase
 69% building modules 684/693 modules 9 active ...ar\common\src\pipes\uppercase_
 69% building modules 685/693 modules 8 active ...ar\common\src\pipes\uppercase_
 69% building modules 686/693 modules 7 active ...ar\common\src\pipes\uppercase_
 69% building modules 687/693 modules 6 active ...ar\common\src\pipes\uppercase_
 69% building modules 688/693 modules 5 active ...ar\common\src\pipes\uppercase_
 69% building modules 689/693 modules 4 active ...ar\common\src\pipes\uppercase_
 69% building modules 690/693 modules 3 active ...ar\common\src\pipes\uppercase_
 69% building modules 690/694 modules 4 active ...es\@angular\common\src\facade\
 69% building modules 690/695 modules 5 active ...gular\common\src\facade\collec
 69% building modules 691/695 modules 4 active ...gular\common\src\facade\collec
 69% building modules 692/695 modules 3 active ...gular\common\src\facade\collec
 69% building modules 692/696 modules 4 active ...lar\common\src\private_import_
 69% building modules 692/697 modules 5 active ...\pipes\invalid_pipe_argument_e
 69% building modules 692/698 modules 6 active ...les\@angular\common\src\pipes\
 69% building modules 693/698 modules 5 active ...les\@angular\common\src\pipes\
 69% building modules 694/698 modules 4 active ...les\@angular\common\src\pipes\
 69% building modules 695/698 modules 3 active ...les\@angular\common\src\pipes\
 69% building modules 696/698 modules 2 active ...les\@angular\common\src\pipes\
 69% building modules 697/698 modules 1 active ...les\@angular\common\src\pipes\
 69% building modules 697/699 modules 2 active ...\@angular\common\src\facade\er
 69% building modules 698/699 modules 1 active ...\@angular\common\src\facade\er
Hash: 4c2cc1386399ffa7e656
Time: 14600ms
chunk    {0} main.bundle.js, main.bundle.map (main) 4.7 kB {2} [initial] [render
ed]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 9.96 kB {3} [initial]
[rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.85 MB [initial] [ren
dered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rende
red]
webpack: bundle is now VALID.


I have this during npm install -g angular-cli

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})

C:\Users\tunji\Documents\angularapp1\ninjaApp>

I am fustrated now, I have not found solution anywhere, I would then do no angular2 if no help!!
