### ISSUE TITLE
Implement trailing-comma tslint rule and enforce on generation

### ISSUE THREAD

**Issue by intellix** [angular/angular-cli#3966]
I'm working in a team of around 10 frontenders and there's 2 things which have given us no end of git conflicts over the years:
 - trailing commas
 - re-ordering of imports

Now we have a pre-compilation step, I'd like to enforce trailing commas for multi-line statements to avoid this:

```
<<<<<<< HEAD
'SomeModule'
=======
'SomeModule',
>>>>>>> branch-a
```

TSLint rule: https://palantir.github.io/tslint/rules/trailing-comma/

Is it possible to add trailing commas for multi-lines on the generation statements?

**Comment by Brocco** [comment]
This is a stylistic decision which would best be handled with custom blueprints/templates when they are that implemented.

Leaving this issue open as a placeholder.

**Comment by cacogr** [comment]
I think a lot of things in angular-cli are stylistic decisions, it's opinionated after all. If it helps reducing conflicts and has no drawbacks I'd welcome it, at least as default behavior.

**Comment by filipesilva** [comment]
Superseded by https://github.com/angular/angular-cli/issues/6272, since that rule has a fixer it could be done there.
