### ISSUE TITLE
[bug] build --prod doesn't produce inline.HASH.bundle.js.gz

### ISSUE THREAD

**Issue by demirk4n** [angular/angular-cli#3968]
Hi,

`ng build --prod --aot ` doesn't produce a gzip version of the "inline.HASH.bundle.js" file.  Other files are gzip'd as expected.

### Versions.

angular-cli: 1.0.0-beta.24
node: 7.3.0
os: linux x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2

**Comment by demirk4n** [comment]
Noticed the following threshold parameter in the code. Only the files above 10KB  get compressed?
```
     new CompressionPlugin({
          asset: '[path].gz[query]',
          algorithm: 'gzip',
          test: /\.js$|\.html$|\.css$/,
          threshold: 10240
      }),
```

**Comment by clydin** [comment]
Yes. It's intentional.

**Comment by demirk4n** [comment]
Thanks.
