### ISSUE TITLE
bootstrap navigation comes vertical 

### ISSUE THREAD

**Issue by samrandhawa4** [angular/angular-cli#3978]
I used bootstrap  with npm install bootstrap@next, but when i used bootstrap navigation code , my navigation comes vertical .
- You have to change your bootstrap.css file in "../node_modules/bootstrap/dist/css/bootstrap.css".
- Use " flex-direction: row " not " flex-direction: column".
- Here is the correct css for nav-bar
`.navbar-nav {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -ms-flex-direction: row;
    flex-direction: row;
    padding-left: 0;
    margin-bottom: 0;
    list-style: none;
}
.navbar-brand {
    display: inline-block;
    margin-right: 1rem;
    line-height: inherit;
    white-space: nowrap;
}`

**Comment by beeman** [comment]
@samrandhawa4 this is most likely not an angular-cli issue. Please file here https://github.com/twbs/bootstrap
