### ISSUE TITLE
not able to use ng serve web app using public IP or Domain

### ISSUE THREAD

**Issue by gauravbansal74** [angular/angular-cli#3991]
> Please provide us with the following information:
> not able to use "ng serve" web app using public IP or domain for testing in development.

### OS?
> Ubuntu

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
 ng --version
angular-cli: 1.0.0-beta.24
node: 7.4.0
os: linux x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
App was created using ng new 

I didnt change anything in code. Just running using ng serve. Please find screen-shot.
<img width="838" alt="screen shot 2017-01-13 at 3 43 33 pm" src="https://cloud.githubusercontent.com/assets/5467284/21926313/3d7e93e2-d9a7-11e6-8cd8-6f4b316cd674.png">

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I don't see anything wrong in that screenshot. You ran the command, bundles were built and are being served. You're going to have to give me more details.

**Comment by gauravbansal74** [comment]
Its working fine now. Sorry my bad
