### ISSUE TITLE
@ngtools/logger not installed?

### ISSUE THREAD

**Issue by jtsom** [angular/angular-cli#3996]
Installed the latest Angular-cli. The change log new features indicate:

`@ngtools/logger: Implement a reactive logger. (#3774) (e3b48da)`

However, after installing / upgrading, that package is not in the node_modules folder.
Is it supposed to be? Is it supposed to be a user accessible feature?

### OS?
Mac OS Sierra

### Versions.

angular-cli: 1.0.0-beta.25.5
node: 7.4.0
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

### Repro steps.
Create new app. Look for new logger. Not there.

**Comment by filipesilva** [comment]
It's a separate package from `angular-cli` proper. This repo actually contains some 5 or 6 packages.

In this case it's published to `npm` and you can use it, but internally we just use it for our e2e suite.

**Comment by bgaillard** [comment]
Hi, i'm new to Angular CLI and Typescript.

I would like to use the logger to no reinvent the wheel so I install it with `npm install @ngtools/logger`, no problem.

But when I use it I encounter the following error.

```
Module build failed: Error: D:/workspace/vgm-admin/src/app/app.module.ts (26,38): Cannot find module '@ngtools/logger'.)
```

The only peace of code I added was the following, is it enough ? 

```
import { Logger } from '@ngtools/logger';
```

Thanks for your help
