### ISSUE TITLE
After --prod build which all files do we need to copy to th server to run the app.

### ISSUE THREAD

**Issue by ersurajnegi** [angular/angular-cli#3998]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by RicardoVaranda** [comment]
Hi @ersurajnegi, after running ng build --prod, you should copy the dist folder onto your server.

**Comment by filipesilva** [comment]
@RicardoVaranda beat me to it, that's what I was gonna say 💃

**Comment by ersurajnegi** [comment]
all the files map,gz as well we need to put it there????

**Comment by ersurajnegi** [comment]
whats is the significabce of these files?
i tried googling it but didn't get proper answer.
Sorry for asking here.
