### ISSUE TITLE
Change from css to less/scss or from html to jade.

### ISSUE THREAD

**Issue by krasevych** [angular/angular-cli#40]
Hello.
I like to use Jade and Less, but I can't understand how I can change generator?
I would like that generator creates less and jade instead of html or css.

**Comment by cironunes** [comment]
This feature is not supported by the CLI yet, but I agree that this would be useful.

**Comment by filipesilva** [comment]
Less support is being tracked on https://github.com/angular/angular-cli/pull/115

**Comment by hansl** [comment]
I'll close this, but just want to let you know that we do take generating special scaffolds for different types of templates (like LESS, Compass, Jade, Javascript, ...). This is being investigated.

**Comment by NullVoxPopuli** [comment]
how would somebody set up Jade? would following this be sufficient? https://github.com/angular/angular-cli/wiki/3rd-party-libs

/cc @etkirsch

**Comment by hansl** [comment]
You'd need it to be part of your build broccoli tree. This is entirely doable though; all you have to do is build a tree that transfers the JADE to HTML, then pass that tree with your source to Angular2App.

**Comment by filipesilva** [comment]
There is an open PR for jade/pug functionality: https://github.com/angular/angular-cli/pull/626
