### ISSUE TITLE
Mistake in CLI error message

### ISSUE THREAD

**Issue by lasharela** [angular/angular-cli#4000]
When I'm writing non existing command (Ex.: ng cl someClassname) error text is: 

"The specified command cl is invalid. For available options, see `ember help`."

As you know 'ember help' doesn't work 

### OS?
> Windows  10

### Versions.
> 1.0.0-beta.24

**Comment by beeman** [comment]
@lasharela please update to the latest version of the CLI, where this error is fixed.

https://github.com/angular/angular-cli#updating-angular-cli
