### ISSUE TITLE
Installation Failing

### ISSUE THREAD

**Issue by cimoca** [angular/angular-cli#4004]
> npm install angular-cli@1.0.0-beta.25.5
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
>Node.js version:    v7.4.0
NPM version:        4.0.5

### Repro steps.
> Create a new Angular 2 application using Angular IDE in Eclipse Neon. I used the latest version for CLI, Node.je and NPM

### The log given by the failure.
> 95592 verbose stack Error: node-sass@4.3.0 postinstall: `node scripts/build.js`
95592 verbose stack Exit status 1
95592 verbose stack     at EventEmitter.<anonymous> (C:\Users\i70898\.webclipse\nodejs\7.4.0\node_modules\npm\lib\utils\lifecycle.js:279:16)
95592 verbose stack     at emitTwo (events.js:106:13)
95592 verbose stack     at EventEmitter.emit (events.js:191:7)
95592 verbose stack     at ChildProcess.<anonymous> (C:\Users\i70898\.webclipse\nodejs\7.4.0\node_modules\npm\lib\utils\spawn.js:40:14)
95592 verbose stack     at emitTwo (events.js:106:13)
95592 verbose stack     at ChildProcess.emit (events.js:191:7)
95592 verbose stack     at maybeClose (internal/child_process.js:885:16)
95592 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
95593 verbose pkgid node-sass@4.3.0
95594 verbose cwd C:\Workspace\NEON\HelloAngular
95595 error Windows_NT 6.1.7601
95596 error argv "C:\\Users\\i70898\\.webclipse\\nodejs\\7.4.0\\node.exe" "C:\\Users\\i70898\\.webclipse\\nodejs\\7.4.0\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular-cli@1.0.0-beta.25.5"
95597 error node v7.4.0
95598 error npm  v4.0.5
95599 error code ELIFECYCLE
95600 error node-sass@4.3.0 postinstall: `node scripts/build.js`
95600 error Exit status 1
95601 error Failed at the node-sass@4.3.0 postinstall script 'node scripts/build.js'.
95601 error Make sure you have the latest version of node.js and npm installed.
95601 error If you do, this is most likely a problem with the node-sass package,
95601 error not with npm itself.
95601 error Tell the author that this fails on your system:
95601 error     node scripts/build.js
95601 error You can get information on how to open an issue for this project with:
95601 error     npm bugs node-sass
95601 error Or if that isn't available, you can get their info via:
95601 error     npm owner ls node-sass
95601 error There is likely additional logging output above.
95602 verbose exit [ 1, true ]

### Mention any other details that might be useful.

> Same error occurs using different version of CLI, Node.js and NPM. 
> Thank you.

**Comment by gelliott181** [comment]
You have a project, generated with Eclipse Neon, that you're trying to install a local copy of the CLI to? This is the exact opposite of the workflow the tool is created for. Please re-read the Readme.md to be sure you understand this isn't something like a Yeoman generator or a CSS deduplication tool. It's everything but the text editor. That's a slight oversimplification, but the idea is that you wouldn't expect a project made in Eclipse to be able to build with Visual Studio without porting the project to VS.

You **must** generate the project with the CLI, then you build the app in the `src` directory. A pre-existing app can be placed into the `src` directory and ported to the CLI.

**Comment by cimoca** [comment]
The Angular IDE is issuing the  npm install angular-cli@1.0.0-beta.25.5 comand.
The install is failing with this error: error node-sass@4.3.0 postinstall: node scripts/build.js.
If I issue the  npm install angular-cli using a node.js terminal window I get the same error.

**Comment by mattdistefano** [comment]
@cimoca what happens if you `npm install node-sass@4.3.0` from the command line?

**Comment by gelliott181** [comment]
It's weird that it's asking for 4.3.x, the CLI is pinned to 4.1.x (`~4.1.1`) in the package.json.

**Comment by filipesilva** [comment]
Can you also try `npm install angular-cli@1.0.0-beta.25.5 --no-optional`?

It looks like your system is either:
- having trouble downloading the node-sass binary
- having trouble building node-sass

Usually it's enough to download the binary but something might be preventing that.

**Comment by catull** [comment]
@cimoca Is the problem still happening, or were you able to resolve it ?  Did the trick @filipesilva suggested help ?

**Comment by sumitarora** [comment]
@cimoca Is it still an issue? Please reopen if it's still with more details.
