### ISSUE TITLE
version info

### ISSUE THREAD

**Issue by gandra** [angular/angular-cli#4017]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I'm sorry but you don't seem to have filled in anything in the issue template. Please open a new issue with the details filled it, otherwise we cannot do anything.

**Comment by gandra** [comment]
Do not know how I did it. Now I have lost context info.
