### ISSUE TITLE
Set/omit the hash in distribution files?

### ISSUE THREAD

**Issue by SanderElias** [angular/angular-cli#4018]
### OS?
all

### Mention any other details that might be useful.
While building for specific environments, the variable hash in the distribution files is not helpful. We need a way to set it to a known one, or omit it all together. We need a flag or config file setting to accomplish this. 
Or did I miss something and is this already in somewhere?

**Comment by clydin** [comment]
It is strongly advised to use some form of cache busting for production deployments.
To remove the output file hashing use the following build command option: --output-hashing=none
This requires beta.25 or higher.

**Comment by filipesilva** [comment]
Closed as answered by @clydin. Also big thanks to him, as he's the one that implemented the `--output-hashing` option.

**Comment by SanderElias** [comment]
Thanks @clydin! 
Sometimes you need to do some extra processing on the distribution files, and is the cache-busting done elsewhere. The --output-hashing=none caters this use case perfectly!
