### ISSUE TITLE
Angular Cli not working Linux mint 17.02  /usr/bin/ng: line 40: exec: --: invalid option

### ISSUE THREAD

**Issue by Rebaiahmed** [angular/angular-cli#4019]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Linux (linux mint 17.02). 

### Versions.
> Please run `ng --version`. 
when i run ng--version i get this error 
![angularcli](https://cloud.githubusercontent.com/assets/13053759/21962027/1c59120e-db1a-11e6-99d6-6f2f4bfbebdf.png)

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@Rebaiahmed it might be that you have the Linux package `ng-common` installed, that one also has a command called `ng`.

**Comment by beeman** [comment]
If this is not the case please post the output of `file /usr/bin/ng`.

**Comment by filipesilva** [comment]
You seem to have some other `ng` command installed, like @beeman is saying. It's mostly a matter of replacing that, there's nothing to be done on the CLI side.
