### ISSUE TITLE
Serving with AOT takes 10+ minutes

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#4020]
> Please provide us with the following information:
> ---------------------------------------------------------------
Call I did:

**node --max_old_space_size=8192 ./node_modules/.bin/ng serve --env=prod --aot=true**

in v24 of the Cli it was just taking 50 seconds?

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
MacOS Siera

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
25.5 / 6.9.1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
Can you provide console output of beta.24 vs beta.25 to get a better understanding of what's happening?

Also, a production AOT build is never going to be "fast".  It's meant to optimize the output as much as possible.  So except for a test scenario, it's not going to provide a very productive development experience in combination with `serve`.

**Comment by masaanli** [comment]
@clydin the output is nothing more then 33 chunks being generated?

**Comment by filipesilva** [comment]
@hansl any clue on why this changed so drastically?

**Comment by CanKattwinkel** [comment]
I just updated my project from beta.24 to 25.5. There was no performance losses for me when running 
`node --max_old_space_size=8192 ./node_modules/.bin/ng serve --env=prod --aot=true`

**Comment by gelliott181** [comment]
No performance loss on MacOS for me, in fact things are working a little better than before. 

You re-initialized the project after upgrading, correct?

**Comment by hansl** [comment]
I haven't seen any loss in performance for AOT, _but_ it might be depending on the app itself.

@masaanli Could you provide an example application that we could test on? I'm really curious about such a performance hit and we definitely want to investigate.

Thanks!

**Comment by masaanli** [comment]
@hansl it;s a application with 100+ pages and there is a lot of stuff. So I don't know how to reproduce it  in a plunker I think a Plunker with SystemJS loading time is already 5 minutes hehe.

Teamviewer is possible?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
