### ISSUE TITLE
StoreDevtoolsModule.instrumentStore not compatible with AOT 

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#4021]
```StoreDevtoolsModule.instrumentOnlyWithExtension()```  works with AOT.
```StoreDevtoolsModule.instrumentStore not compatible with AOT```
getting an error of:
```
ERROR in Error encountered resolving symbol values statically. Calling function 'StoreDevtoolsModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/msweb/studiotouch/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/studiotouch/src/app/app.module.ts
```

And we rely on ```instrumentStore``` as we need to provide maxAge, otherwise our dev tools will not work (large data set)

can we please fix it so it works just like ```instrumentOnlyWithExtension```

```
angular-cli: 1.0.0-beta.25.5
node: 6.5.0
os: win32 x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.2.1
@angular/compiler-cli: 2.4.3
@angular/language-service: 2.4.3
```

thanks as always,

Sean

**Comment by filipesilva** [comment]
Please open issues related to static analysis on https://github.com/angular/angular instead. The CLI tool just implements static analysis of code as they exist on https://github.com/angular/angular.
