### ISSUE TITLE
NG Commands are slow in 25.5 (maybe before too)

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#4022]
> Please provide us with the following information:
> ---------------------------------------------------------------
When running an ng command it is first thinking 30 seconds and after that it is running the command.

This is annoying, because it's not needed. My machine is a new MacBook Pro with everything to the max ;)

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
MacOS Siera

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
25.5
6.9.1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
ng lint
ng serve

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
That's weird, startup time should have gone down this version. Did you follow https://github.com/angular/angular-cli#updating-angular-cli while upgrading?

**Comment by masaanli** [comment]
@filipesilva yeah ruined exactly that steps. (copy based it from there in my terminal)

**Comment by beeman** [comment]
@masaanli maybe you can try and run one of this slow commands like this to see where it delays:

`DEBUG=angular-cli*,ember-cli* ng serve`

**Comment by masaanli** [comment]
@beeman I tried it this morning what u said and everything seemed a lot faster, so not having it all the time it seems.

Btw. when running ng serve it takes now 5 seconds before doing anything.
and when doing it with the `DEBUG=angular-cli*,ember-cli* ng serve` it starts immediately. 

Tried is 10x times :)
