### ISSUE TITLE
execSync@1.0.2 is Throwing ELIFECYCLE Error During 'ng new' Command

### ISSUE THREAD

**Issue by tramel-woodard** [angular/angular-cli#4027]
After installing angular-cli globally on my Ubuntu 12.04 server, the installation seems fine, until I try to run an "ng new" command.

OS:
Ubuntu 12.04.5 LTS (Precise Pangolin)

Versions:
Node v6.9.4
NPM v4.1.1

Repro Steps:
Initial setup - "npm install angular-cli -g"
Issue when - "ng new APPLICATION"

Receive the following error:

ERROR
=====

npm ERR! Linux 3.2.61-grsec-modsign
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! execSync@1.0.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the execSync@1.0.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the execSync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs execSync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls execSync
npm ERR! There is likely additional logging output above.

**Comment by beeman** [comment]
@tramel-woodard you can close issues that are no longer relevant. 

If you want to create an issue about the error `execSync@1.0.2 is Throwing ELIFECYCLE Error During 'ng new' Command` please provide the information that is requested in the [New Issue](https://github.com/angular/angular-cli/issues/new) form

**Comment by beeman** [comment]
@tramel-woodard it looks like this is a similar issue: https://github.com/angular/angular-cli/issues/2161 . Can you please try the steps suggested there?

**Comment by tramel-woodard** [comment]
@beeman thanks, I was actually led to start this issue after not being able to find my solution at #2161. Thanks, I will update issue with the appropriate specs.

**Comment by filipesilva** [comment]
Are you still having this problem? If so, can you post the full console log you get from `ng new`? The last bit is from `npm` and doesn't help much.

Alternatively, can you try:
```
ng new project-name --skip-npm
cd project-name
npm install
```
