### ISSUE TITLE
extractCss for ng serve

### ISSUE THREAD

**Issue by mkoczorowski** [angular/angular-cli#4039]
Hi there,

Is there a way to extract css to separate css files when running ng serve ?
I tried ng serve --extractCss but with no luck.

Is there a page or a file with all available commands and options for serve or build ?

Thank a lot for all the help.

**Comment by filipesilva** [comment]
Heya @mkoczorowski, you can find all the flags in our wiki: https://github.com/angular/angular-cli/wiki/serve

The one you wanted is `--extract-css`.
