### ISSUE TITLE
Setting CSS preprocessor corrupts the environment settings

### ISSUE THREAD

**Issue by mizdler** [angular/angular-cli#4044]
### OS?
> Mac OSX El Capitan

### Versions.
> angular-cli: 1.0.0-beta.25.5
node: 4.2.6
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

### Repro steps.
> Just create a new project and change the CSS preprocessor using cli: 
`ng set defaults.styleExt sass`
but this corrupts environments settings in angular-cli.json:
![screen shot 2017-01-16 at 3 21 43 pm](https://cloud.githubusercontent.com/assets/6818522/21982047/b9c23bde-dbff-11e6-8237-6ef1ae9e985c.png)

**Comment by filipesilva** [comment]
This looks like a bug, thanks for reporting it!

@hansl this looks like an unintended side-effect of the new `@ngtools/json-schema`.

**Comment by youneschaoui** [comment]
same issue I am facing !!

**Comment by nashimus** [comment]
I just ran into this last night, glad to see someone reported it already. Thanks!
