### ISSUE TITLE
`ng github-page:deploy` not generating files with hashes, only `main.bundle.js`

### ISSUE THREAD

**Issue by rxjs-space** [angular/angular-cli#4048]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows10. 

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: local (v1.0.0-beta.25.5, branch: master)
node: 6.5.0
os: win32 x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
My app created using `ng new`.

### The log given by the failure.
> Normally this include a stack trace and some more information.
No error.

### Mention any other details that might be useful.
I can have ` main.addad3558a8e7df8de84.bundle.js` with `ng build --prod`, but only `main.bundle.js` with `ng github-paged:deploy`. Even `ng github-paged:deploy --prod` won't give any hashes.
No such thing in v1.0.0-beta24.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rxjs-space** [comment]
I added `outputHashing: 'bundles'` after [this line](https://github.com/angular/angular-cli/blob/master/packages/angular-cli/commands/github-pages-deploy.run.ts#L71) , and there I have the hashes.

**Comment by filipesilva** [comment]
This is a bug. With the introduction of https://github.com/angular/angular-cli/pull/3885, the deploy command (and test) weren't updated to also generate/verify the hashes.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
