### ISSUE TITLE
Problem to load css

### ISSUE THREAD

**Issue by eluizbr** [angular/angular-cli#4049]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX Captian

### Versions.
> angular-cli: 1.0.0-beta.24
node: 6.9.4
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

### Mention any other details that might be useful.
> When use routerLink to change page,  from LOGIN PAGE to MAIN PAGE, the css no load completely, in need make an page reload to css completely load..
That's an bug? Or i'm forget some config?

Thanks
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
That sounds like a bug really. Can you you give me a repro that I can follow to see this?

**Comment by eluizbr** [comment]
Filepe, 

Thanks for you quickly feedback...

here: https://github.com/eluizbr/cli-bug

Click on SING IN and you see de problem...

**Comment by eluizbr** [comment]
#

**Comment by clydin** [comment]
Component templates are not intended to be full HTML pages.

To get a feel for the development model, I'd suggest reading through the Angular documentation at https://angular.io/docs/ts/latest/guide/learning-angular.html

**Comment by filipesilva** [comment]
Thanks for looking into it @clydin, that does seem to be the problem: https://github.com/eluizbr/cli-bug/blob/master/src/app/login/login.component.html

Closing as answered.
