### ISSUE TITLE
Unable to create sprites. 

### ISSUE THREAD

**Issue by neha-s16** [angular/angular-cli#4054]
### OS?
Virtual Box running Linux 4.8.0-26-generic on Windows 10

### Versions.
angular-cli: 1.0.0-beta.21
node: 7.2.1
os: linux x64

### Repro steps.
1. App created using angular-cli.
2. Copy normal and retina images in assets/images/common/normal and assets/images/common/retina folders respectively.
3. Run ng-build

No log generated / no console errors. Images are copied to dist folder but sprites are not generated.

**Comment by filipesilva** [comment]
Ok I was totally misunderstanding the usecase. Now that I went to look up sprite tools for webpack (like https://github.com/kezoo/sprite-webpack-plugin) I understand this better.

No, there is no CLI support for sprites currently. I'll mark it as a feature request.

**Comment by neha-s16** [comment]
Thanks.

 It would be a good to have feature for sure. Can I use https://github.com/kezoo/sprite-webpack-plugin or https://www.npmjs.com/package/sprity to generate sprites as of now? I am trying to configure sprity with angular-cli.json. Any other ideas on what can work?

**Comment by filipesilva** [comment]
There is no way to extend extend the webpack config or build system, but I can see `sprity` being ran manually.

**Comment by filipesilva** [comment]
This is something that could be added as an addon, when the addon system is available (https://github.com/angular/angular-cli/issues/2906).

**Comment by lucaswxp** [comment]
From what I understood, there's no way to generate automatically generate sprites in angular-cli?
