### ISSUE TITLE
Feature Request: lint option at ng serve

### ISSUE THREAD

**Issue by willgm** [angular/angular-cli#4056]
Would be good to see lint errors as warnings live while dev serving my code.

**Comment by dvanhoek-mobiquityinc** [comment]
I Agree if this is not hurting the Performance

**Comment by hansl** [comment]
This is not a priority for 1.0, but we will keep it in mind for a future release. Thanks!

**Comment by deli6z** [comment]
This would be super helpful to have, any plans to add it to later versions ?
