### ISSUE TITLE
TsLint= >Implement lifecycle hook interface OnInit for method ngOnInit 

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#4060]
### Running
angular-cli: 1.0.0-beta.24
node: 4.6.0
os: darwin x64

### Description
Tried to utilize latest Angular's addition for the inheritance 
[Angular Commit](https://github.com/angular/angular/commit/f5c8e0989d85bc064f689fc3595207dfb29413f4)

where lifecycle hook interface is implemented on the parent level and Child component just override the method and it seems tslint is not uptodate with this .

```
"use-life-cycle-interface": true,
```
It should probably check all the way up to the parent if the interface is implemented. 

Thank you, 

Frank

**Comment by filipesilva** [comment]
Please open this issue on https://github.com/mgechev/codelyzer instead, which is the linter that implements the rule.

**Comment by fkolar** [comment]
thanks I will

**Comment by LabuschagneB** [comment]
Add "implements Oninit"

export class AppComponent implements OnInit
