### ISSUE TITLE
Failed to create GitHub repo. Error: 422 Unprocessable Entity

### ISSUE THREAD

**Issue by goleary** [angular/angular-cli#4061]
### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.25.5
node: 6.9.2
os: win32 x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

### Repro steps.
use cli to create app.
create repo on github.
add repo as remote to newly created app
try `ng github-pages:deploy`
follow instructions
=> error: `Failed to create GitHub repo. Error: 422 Unprocessable Entity`

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

It looks like this happens because the cli attempts to create a repo itself (which already exists). Can the cli not check to see if a remote is already attached and if so just create the new branch with the deployed app?  This error is not clear and requiring users to delete their repo on github (my workaround) seems like it is not the best solution.

**Comment by beeman** [comment]
@goleary the cli already checks if the remote is set up as you can see [here](https://github.com/angular/angular-cli/blob/a54bc1682f6644cf9801a518e39e79ea5d19163f/packages/angular-cli/commands/github-pages-deploy.run.ts#L121).

Can you manually run `git remote -v` in the project dir and see if there is an `origin` defined?

**Comment by goleary** [comment]
I did and there was a remote defined. I deleted my repo on github, removed the remote, and then re ran the github-pages command and it worked.

**Comment by filipesilva** [comment]
If you had a remote defined then it sounds like a bug.

**Comment by goleary** [comment]
just repeated the steps listed in my repro on the original and another machine and was unable to repro the error.

Not sure what the cause was yesterday, perhaps this can be closed until seen again?

**Comment by ivanderbu2** [comment]
I got the same error right now, my setup:

MacOS Sierra Version 10.12.2

angular-cli: 1.0.0-beta.26
node: 7.2.0
"@angular/common": "^2.3.1",
"@angular/compiler": "^2.3.1",
"@angular/core": "^2.3.1",
"@angular/forms": "^2.3.1",
"@angular/http": "^2.3.1",
"@angular/platform-browser": "^2.3.1"

Error is the same as one mentioned above, no stack trace.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
