### ISSUE TITLE
How to use webpack plugin

### ISSUE THREAD

**Issue by RevolCat** [angular/angular-cli#4062]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
1.0.0-beta.25.5

### Repro steps.
how to use webpack plugin such as UglifyJsPlugin  ？
maybe I didn't read the tutorial carefully

**Comment by grizzm0** [comment]
You can not configure webpack with angular-cli. Angular-cli is a tool that aims to work "as is" for most projects. If it doesn't fit your needs you're better of using your own webpack setup.

Btw, UglifyJsPlugin is already part of the cli. See https://github.com/angular/angular-cli/blob/d3e7c8020707a890d9bc6e246fc638fa483c1605/packages/angular-cli/models/webpack-build-production.ts#L29

**Comment by filipesilva** [comment]
When you do a production build (`ng build --prod`), it will use `UglifyJsPlugin`.

**Comment by RevolCat** [comment]
ok,thank you
