### ISSUE TITLE
Support for string replacement with external properties

### ISSUE THREAD

**Issue by nithril** [angular/angular-cli#4066]
### OS?
Windows 7

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.9.4
os: win32 x64

### Mention any other details that might be useful.

Hi,

It does not seems yet possible with angular-cli to replace strings (a placeholder) contained in HTML or TS files by a value stored inside an external properties files or simply by the `package.json` version. I'm looking for something very similar too [string-replace-webpack-plugin](https://github.com/jamesandersen/string-replace-webpack-plugin) or [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin).

Is it a planned feature ?

Thanks,

Nicolas

**Comment by filipesilva** [comment]
This is not a planned feature. It has come up a few times but we made the choice to not add. Some setups use it with success, but we don't feel it's an absolute necessity.

**Comment by nithril** [comment]
Thanks for your feedback
