### ISSUE TITLE
ERROR in Could not resolve "D:/" from "D:/".

### ISSUE THREAD

**Issue by hendrawidjaja** [angular/angular-cli#4069]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Window 10 pro

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.25.5
node: v7.2.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Fresh installation using "ng new" 

### The log given by the failure.
> Normally this include a stack trace and some more information.
![ps-ss](https://cloud.githubusercontent.com/assets/2580855/22030743/e0952e26-dcde-11e6-858c-ffe66d6c1f21.PNG)
![browser-ss](https://cloud.githubusercontent.com/assets/2580855/22030745/e5725bd0-dcde-11e6-9749-a6ff06ee969f.PNG)

### Mention any other details that might be useful.
running ng serve with full admin powershell

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gelliott181** [comment]
Something is attempting to access `D:/` which is an invalid location in Windows, and should be `D:**\**`. The CLI uses relative directories, have you specified code or assets that reside on a `D:\` drive?

**Comment by hendrawidjaja** [comment]
I have 2 partition on single disk. The main installation of node is on drive C and the project is on drive

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by marcosanfilippo** [comment]
I still have the same problem with the last version of CLI.

**Comment by sabinkarki** [comment]
I do have the same issue however changing project name it works.My project was in D drive. i.e D:\#test then I changed  to D:\test.

Rest:
npm install
npm install --save-dev @angular/cli@latest

**Comment by smackjax** [comment]
I don't understand what you mean about the project name. Both folders and new Angular projects can't start with a slash. Could you please elaborate?

I've had this problem for quite a while; frankly to the point where I just didn't use Angular. I reinstalled Windows 10(and 7), messed with local/global installs, reinstalled(and purged) node, and changed drives.

The only way I've gotten ng serve to work is let it fail to load chunks, then(while the process is still running) change the base href to a backslash in the 'index' file.  Then the dev server works, but I haven't figured out a way to use ng build. 

I think it might be something with html-webpack-plugin, from looking at the --verbose output. 
...But I don't know enough about Webpack to debug it. Yet.  

In the mean time, cli works great on Linux Mint. :)

**Comment by smackjax** [comment]
@sabinkarki 
My bad, forgot the tag.
