### ISSUE TITLE
feature: skip lazy loaded modules from compiling on every save

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#4080]
### OS?
all

### Versions.
all

### feature:
I would love to be able to break down my application to lazy loaded modules and have the cli (webpack) skip modules which are lazy loaded (separate bundles)  and thus there is no need to re-compile them on every save while in development mode.

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by hansl** [comment]
We already do that (breaking down on lazy routes). Webpack should be smart enough to know when a bundle has changed or not.

**Comment by born2net** [comment]
ok good to know, I asked on Gitter and people didn't know
I will inform them
tx!
