### ISSUE TITLE
Error occur after reinstall node modules

### ISSUE THREAD

**Issue by duynb** [angular/angular-cli#4084]
My layout component is like this:

`
@Component({

  selector: 'admin-main-layout',   
  templateUrl: './main-layout.component.html', 
  styleUrls: 
  [
    'assets/admin/css/bootstrap.min.css',
    'assets/admin/css/font-awesome.min.css',
    ...
  ],
  encapsulation: ViewEncapsulation.None
})
`

That work fine untill ..
Recently when I delete the node_modules folder  and reinstall using `npm install`

The error occur when I run `ng server` : 

`

ERROR in ./src/app/admin/main-layout.component.ts
Module not found: Error: Can't resolve './assets/admin/css/bootstrap.min.css' in ...
...
@ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi main
`

Is there any new update in core that couse the problem? 
Thank you.

**Comment by filipesilva** [comment]
Style urls should be relative, and it looks like you're using an absolute path. Try making the url relative to the component.

**Comment by duynb** [comment]
Thanks :)
 Relative path solve the problem.
