### ISSUE TITLE
ng serve continuously building bundle with out changing source code

### ISSUE THREAD

**Issue by manikumaar** [angular/angular-cli#4085]
OS  Windows 7

 Versions angular-cli 25.5 beta

When run ng serve in my windows(OS 7) machine it is getting build continuously without changing source code but not happening in mac.

Is there any solution?

**Comment by filipesilva** [comment]
This is likely an editor issue. Something in your machine is continuously saving or touching those files, which triggers a rebuild.

**Comment by manikumaar** [comment]
No, I have tried with three editors .. How come all the editors giving issue.. I don't think its editor issue
