### ISSUE TITLE
terminal log update src/app/app.module.ts when creating components

### ISSUE THREAD

**Issue by youneschaoui** [angular/angular-cli#4087]
When calling `ng g component <component>` terminal logs `update src/app/app.module.ts
`. I don't think file is really updated and I don't even think it should be.

**Comment by filipesilva** [comment]
It is being updated actually. When you create a new component, we automatically add the import to it to the closes NgModule. You can skip this behaviour though, via `--skip-import`.

https://github.com/angular/angular-cli/wiki/component

**Comment by MrPardeep** [comment]
@filipesilva Great, Can you please add some more explanation on this, I mean how files are being updated? I am curious to know the background process.
