### ISSUE TITLE
ng generate without specified blueprint produces incorrect warning

### ISSUE THREAD

**Issue by joalepampala** [angular/angular-cli#4088]
### OS?
Ubuntu 16.04

### Versions.
angular-cli: 1.0.0-beta.25.5
node: 6.9.1

command `ng generate` without specified blueprint/name produces warning below 

The `ember generate` command requires a blueprint name to be specified. For more details, use `ember help`.

**Comment by filipesilva** [comment]
Are you absolutely sure you have the latest version? You can double check your local version of the CLI with `npm ls angular-cli`.

We fixed this in `beta.25.5` so I find it weird you're still getting it:
```
kamik@T460p MINGW64 /D/sandbox/master-project (master)
$ ng generate
The `ng generate` command requires a blueprint name to be specified. For more details, use `ng help`.
```

**Comment by filipesilva** [comment]
Oh my bad, it's actually fixed on master only via https://github.com/angular/angular-cli/pull/4026 by @clydin. The fix will be out on the next release.

**Comment by pipiscrew** [comment]
hi, experiencing the same... :( 

`
>ng generate
The `ng generate` command requires a blueprint name to be specified. For more de
tails, use `ng help`.


>npm -v
4.1.2


>ng --version
@angular/cli: 1.0.0-beta.31
node: 7.5.0
os: win32 ia32
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7`

**Comment by hasanalbukhari** [comment]
getting this eroor on the following version:

ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0-rc.1
node: 6.10.0
os: darwin x64

**Comment by pipiscrew** [comment]
the cmd use is 
`ng generate component my-new-component`
