### ISSUE TITLE
Project local cli installation doesn't allow use of ng command

### ISSUE THREAD

**Issue by chrillewoodz** [angular/angular-cli#4098]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
Using beta25, can't run ng --version :D 

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
After upgrading to beta24/beta25 from a beta18 installation, and removing the globally installed angular-cli I can no longer use the `ng` command. Despite it being in `package.json` under `scripts`. I might have misunderstood how to use the project local installation commands as I can't find any other issues on this.

**Comment by beeman** [comment]
@chrillewoodz if you want to run it as just `ng` you need to have it installed globally.

Recent projects scaffolded by the angular-cli add a lint like this in scripts `"ng": "ng"`, which allows you to run the version from your project with `npm run ng`, though this gets a bit messy if you want to add extra parameters (`npm run ng serve -- --port 4321`) 

The recommended way is to install angular-cli globally.
