### ISSUE TITLE
Ng2DropdownModule is not an NgModule

### ISSUE THREAD

**Issue by anvesh48** [angular/angular-cli#4099]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.25.5                                                                                                                                                          
node: 6.6.0                                                                                                                                                                           
os: win32 x64                                                                                                                                                                         
@angular/common: 2.4.3                                                                                                                                                                
@angular/compiler: 2.4.3                                                                                                                                                              
@angular/core: 2.4.3                                                                                                                                                                  
@angular/forms: 2.4.3                                                                                                                                                                 
@angular/http: 2.4.3                                                                                                                                                                  
@angular/platform-browser: 2.4.3                                                                                                                                                      
@angular/platform-browser-dynamic: 2.4.3                                                                                                                                              
@angular/router: 3.4.3            

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
npm start

### The log given by the failure.
> Normally this include a stack trace and some more information.
ERROR in Ng2DropdownModule is not an NgModule 

### Mention any other details that might be useful.

> I updated my angular-cli and all other plugins to the latest versions. And i am seeing this error i did check my package.json file it doesn't have any Ng2DropdownModule. I don't know where it is coming from.

> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@anvesh48 can you please paste your dependencies/devDependencies from your package.json?

It's most likely an outdated dependency (or dependency from dependency).

**Comment by anvesh48** [comment]
{
  "name": "project",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "tslint \"src/**/*.ts\" --force && ng serve --proxy-config proxy.conf.json",
    "build": "tslint \"src/**/*.ts\" && ng test --watch=false && ng build",
    "lint": "tslint \"src/**/*.ts\" --force",
    "postinstall": "typings install",
    "test": "ng test --watch=false",
    "test:watch": "ng test --watch=true",
    "typings": "typings",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.18",
    "@ng-idle/core": "2.0.0-beta.4",
    "@ng-idle/keepalive": "2.0.0-beta.4",
    "@types/jasmine": "^2.5.41",
    "ag-grid": "7.2.x",
    "ag-grid-ng2": "7.2.x",
    "angular2-hotkeys": "^1.0.1",
    "angular2-toaster": "^2.0.0",
    "bootstrap": "4.0.0-alpha.4",
    "components-font-awesome": "^4.7.0",
    "core-js": "2.4.1",
    "jquery": "^3.1.0",
    "ng-click-outside": "2.0.2",
    "ng2-material-dropdown": "^0.6.2",
    "ng2-tag-input": "^0.7.4",
    "npm-check-updates": "^2.8.9",
    "rxjs": "5.0.3",
    "ts-helpers": "^1.1.1",
    "typings": "2.1.0",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/lodash": "^4.14.37",
    "angular-cli": "1.0.0-beta.25.5",
    "codelyzer": "~2.0.0-beta.4",
    "css-loader": "^0.26.1",
    "graceful-fs": "4.1.11",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.4.0",
    "less": "^2.7.1",
    "lodash": "^4.16.3",
    "minimatch": "3.0.3",
    "moment": "^2.15.1",
    "protractor": "5.0.0",
    "style-loader": "^0.13.1",
    "ts-node": "2.0.0",
    "tslint": "4.3.1",
    "typescript": "2.1.5",
    "typings": "2.1.0"
  }
}

**Comment by beeman** [comment]
@anvesh48 it looks like that module comes from`ng2-material-dropdown`. 

What might help is delete `node_modules` and do a fresh `npm install`.

**Comment by anvesh48** [comment]
Thanks beeman. 
The below is the error that i am seeing now in the console:

ERROR in TagInputModule is not an NgModule 

Browser console:
metadata_resolver.js:979 Uncaught Error: Can't resolve all parameters for APEXXHRBackend: (?, ?, ?, ?, ?, ?, ?)

**Comment by beeman** [comment]
@anvesh48 that's most likely the next one on the list: `ng2-tag-input`

It basically means that the modules you are depending on are not in the right shape to be used in Angular 2 apps built with the cli. It's up to the package maintainer to fix this.

**Comment by anvesh48** [comment]
Thanks beeman.

**Comment by anil-agrawal** [comment]
Update module declaration file ng2-dropdown.module.d.ts as below

import { NgModule } from '@angular/core';
@NgModule() export declare class Ng2DropdownModule{
