### ISSUE TITLE
Production build

### ISSUE THREAD

**Issue by SonicGD** [angular/angular-cli#41]
```
ng build --environment=production
```

generate dist with dev versions of angular and systemjs, and my app files with .ts and source maps.

**Comment by jimthedev** [comment]
Are you getting a specific error? I was able to run this it generates to dist/

Make sure you've got node > 4.1.0.

**Comment by SonicGD** [comment]
No, i don't say it fails, i say it not 'production'. Production build should contain .min lib files, no ts or sourcemaps and etc

**Comment by IgorMinar** [comment]
Prod builds (or any custom environment builds) are currently not supported. It's one of the many things that need to happen in order to make this project production ready.

**Comment by sivaah** [comment]
Looks like the /dist directory contains the exact copy of src directory including typescript files. I think the typescript files are not required in /dist. The /dist/vendor directory is clean, which has only the javascript files.

**Comment by cironunes** [comment]
In order to do the production build we can take the current build and:

- [ ] remove livereload references in the `index.html`
- [ ] stop copying the `ts` files
- [ ] stop copying the `tsconfig.json` file
- [ ] add a CNAME?
- [ ] enableProdMode()

What else?

**Comment by Brocco** [comment]
Assure that pre-compiled style (LESS/SASS) files are not copied to the dist directory

**Comment by filipesilva** [comment]
Config files perhaps, with API addresses and 3rd party services tokens.

**Comment by alexpaluzzi** [comment]
I think this list looks good @cironunes. Will we also be minifying/mangling?

Really, this production flow is the only thing missing for me to start using this hard right now.

**Comment by hansl** [comment]
Picked this as the official production build issue to follow.

**Comment by cironunes** [comment]
Still missing:

- [ ] add a CNAME?
- [ ] enableProdMode()
- [ ] inlining HTML and CSS resources

**Comment by hansl** [comment]
Added 2 points to your todo list above.

**Comment by alexpaluzzi** [comment]
So we are bundling now? That would be the best news I've heard all week.

**Comment by cironunes** [comment]
I'd love to continue working on that, but I just don't have the time at the moment :(
I'm glad that Filipe is taking care of it. :smile:

**Comment by JohannesHoppe** [comment]
You are talking about adding a `CNAME` file, which implies that Github Pages is a "first citizen". If you directly support gh-pages, than you also want to copy `dist/index.html` to `dist/404.html`. This will enable browser-reloads together with the `PathLocationStrategy`.

**Comment by alexpaluzzi** [comment]
I know still WIP here, but am I missing a flag for using the production vendor libs or is it just unfinished? I can only get `angular2.dev.js` for instance. That ~1 second bootstrapping time is maddening. Cheers!

**Comment by filipesilva** [comment]
That bit is the next one I'm working on, to be able  to bundle stuff.

**Comment by cdarken** [comment]
Is there any way to add a custom environment by creating a file named for instance config/environment.stage.ts and then execute ng build --environment=stage ? It looks like it's defaulting to dev now.

**Comment by filipesilva** [comment]
@cdarken no, it is not currently possible to have more environments other than dev and prod. It's one of my next action items though.

I should mention though (since I haven't yet updated the readme), all builds using `-prod` use bundling and tree shaking at the moment.

**Comment by cdarken** [comment]
Thanks, I will wait patiently then.

**Comment by mashhoodr** [comment]
hello @filipesilva do we have an approximate timeline for this? I have a project that I will need to deploy to production soon, is there anything you recommend we should use until this is completed?

**Comment by filipesilva** [comment]
@mashhoodr you can already do production builds, the thing that is missing is more than 2 environments.

**Comment by marcalj** [comment]
What about Service Workers?
Also images are minifyed and filerevved? (for permanent caching)

Thanks guys!!!

**Comment by filipesilva** [comment]
Currently service workers are only enabled for mobile projects, but we're looking at having them in all prod builds.

Images are not processed at the moment either.

**Comment by filipesilva** [comment]
I think this issue is obsolete by now. All of the features mentioned so far have been addressed, with the possible exception of having service workers in all prod builds. That warrants discussion though so probably should be another issue.

**Comment by pardipbhatti9187** [comment]
can anyone tell plz how to run angular cli production mode forever. i want to deploy production build on live server. But i am not getting it.

**Comment by neilhem** [comment]
Run `ng build -prod`

**Comment by Avien** [comment]
Currently ng build --prod still generates source maps
How can I build without suorce maps?
Thanks

**Comment by lime-green** [comment]
Is there a plan to disable source maps in production? My bundle source map is 6.3 MB which is just too much

**Comment by Misiu** [comment]
@neilhem is there an option to skip sourcemaps generation when building using `ng build -prod`?

**Comment by Perezmarc** [comment]
Hey @Misiu, I'm using `ng build --prod --aot --no-sourcemap  --no-vendor-chunk` for my production build.

Still, I get too many files that I believe are unnecessary (but maybe they're not). Would be nice to have all the production deployment options such as: How to deploy gzipped version, how to deploy not gzipped version, with sourcemaps, without sourcemaps... 

This are all the files I get when I execute that command. Would appreciate a way to tidy up the production build, maybe include folders to separate files. I also would like to know if I can upload to my cloudfront the .gz without uploading the .js

![captura de pantalla 2016-12-21 a les 10 34 17](https://cloud.githubusercontent.com/assets/9431228/21384197/c9e38bee-c769-11e6-8555-b985f841f877.png)

my angular-cli.json

`{
  "project": {
    "version": "1.0.0-beta.22-1",
    "name": "webapp-21b"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "download",
        ".well-known",
        "robots.txt",
        "sitemap.xml"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.css",
        "./css/main.scss",
        "./css/buttons.scss",
        "./css/forms.scss",
        "./css/navbar.scss",
        "./css/nouislider.scss",
        "./css/mixins.scss",
        "./css/spinner.scss",
        "./css/utils.scss",
        "./css/vars.scss"
      ],
      "scripts": [
        "./assets/js/noUiSlider.9.0.0/nouislider.min.js",
        "./assets/js/wNumb.js"
      ],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "addons": [
  ],
  "packages": [
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}
`

**Comment by Mahi8686** [comment]
How to run forever with angular-cli?
