### ISSUE TITLE
`ng github-page:deploy` not deploying, but report it does - beta.26

### ISSUE THREAD

**Issue by genereux** [angular/angular-cli#4104]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 8

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.25.5
node: 4.2.1
os: win32 x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
ng new
ng serve
ng github-page:deploy 

### The log given by the failure.
> Normally this include a stack trace and some more information.
No error.

### Mention any other details that might be useful.
There was no branch created, and no error reported
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by genereux** [comment]
After upgrading to beta.26 the issue is still there

**Comment by filipesilva** [comment]
Ok, will investigate.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
