### ISSUE TITLE
v.1.0.0-beta.25.5 not generating an angular-cli-build.js file

### ISSUE THREAD

**Issue by Optiq01** [angular/angular-cli#4107]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows Vista 32bit

### Versions.
> Node v.5.7.0, NPM 3.6.0, Angular-CLI v.1.0.0-beta.25.5, Angular 2

### Repro steps.
> I was following this video https://youtu.be/riDcgOVfiXA up to the point where he goes to add to the angular-cli.js file.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
>I seen a couple other posts on here about this issue from back in August and tried the things suggested there which was deleting all the node modules, clearing the cache then running npm install again.  Then someone suggested deleting angular-cli and reinstalling it without making it global.  Seeing that I just installed it I'm guessing I have the latest version.
>
>Upon closer inspection I also noticed when he went into the typings folder to show angularfire2 was added he had 6 or 7 things generated into the file with the setup.  Mine only had one and I followed the same exact steps.  So I'm guessing there may be other things that didn't get added somewhere too that I haven't bumped into yet.  Why is this happening?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@Optiq01 the video is talking about an old version of angular-cli, and it has changed a lot over the last few months. The cli is now configured using a json file, uses webpack instead of SystemJS and uses 'types' instead of typings. 

It's probably best to check for a more up to date tutorial, there's a lot out there

**Comment by Optiq01** [comment]
oh wow... smh... I set the filter on youtube to only show videos from this month.  The Publishing date on it is from Dec 11th so I figured it was the newest method.  I'll see if I can find something newer, thanks.

**Comment by martinmcwhorter** [comment]
@Optiq01 The documentation in the README.md should be enough to get you started.

**Comment by DeekshaPandit** [comment]
Hi guys,

I made a project in Angular2 using angular cli  version : angular-cli: 1.0.0-beta.25.

"Error in Error encountered resolving symbol values statically. Function calls are not supported.Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /../../../../src/app/app.module.ts, resolving symbol AppModule in /../../../../src/app/app.module.ts".


`{
  "name": "od-cli",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\" --project src/tsconfig.json --type-check && tslint \"e2e/**/*.ts\" --project e2e/tsconfig.json --type-check",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.3.1",
    "@angular/compiler": "2.3.1",
    "@angular/core": "2.3.1",
    "@angular/forms": "2.3.1",
    "@angular/http": "2.3.1",
    "@angular/platform-browser": "2.3.1",
    "@angular/platform-browser-dynamic": "2.3.1",
    "@angular/router": "3.3.1",
    "aws-sdk": "2.6.6",
    "bootstrap": "3.3.7",
    "core-js": "2.4.1",
    "linq-es2015": "2.4.13",
    "ng2-auto-complete": "0.8.2",
    "ng2-bootstrap": "1.1.14",
    "ng2-bs3-modal": "0.10.4",
    "ng2-ckeditor": "1.1.5",
    "ng2-completer": "0.4.0",
    "ng2-img-cropper": "0.7.6",
    "ng2-meta": "2.0.3",
    "ng2-sharebuttons": "1.1.1",
    "ng2-toasty": "2.1.0",
    "ng2-ui-auth": "4.1.0",
    "rxjs": "5.0.1",
    "ts-helpers": "1.1.1",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "6.0.42",
    "angular-cli": "1.0.0-beta.25.5",
    "codelyzer": "2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.0.2",
    "karma-remap-istanbul": "0.2.1",
    "protractor": "4.0.13",
    "ts-node": "1.2.1",
    "tslint": "4.3.0",
    "typescript": "2.0.3"
  }
}`

and app.module.ts

`import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from "@angular/forms";
import { HttpModule } from "@angular/http";
import { MetaModule, MetaService } from 'ng2-meta';

import { AppRoutes } from "./routes/app.route";
import { MyAuthConfig, metaConfig } from './config';
import { CKEditorModule } from 'ng2-ckeditor';
import { Ng2BootstrapModule } from 'ng2-bootstrap';
import { Ng2UiAuthModule } from 'ng2-ui-auth'
import { Ng2Bs3ModalModule, ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';
import { ImageCropperComponent, CropperSettings, Bounds } from 'ng2-img-cropper';
import { ToastyModule } from 'ng2-toasty';
import { asEnumerable } from 'linq-es2015';
import { ShareButtonsModule } from 'ng2-sharebuttons';
import { Ng2AutoCompleteModule } from 'ng2-auto-complete';
import { Ng2CompleterModule } from "ng2-completer";

import { AppComponent } from './app.component';


@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        AppRoutes,
        
        Ng2AutoCompleteModule,
        Ng2CompleterModule,
        CKEditorModule,
        ShareButtonsModule,
        Ng2BootstrapModule,
        Ng2Bs3ModalModule,
        Ng2UiAuthModule.getWithConfig(MyAuthConfig),
        ToastyModule.forRoot(),
        MetaModule.forRoot(metaConfig),

    ],

    declarations: [
        AppComponent,
        UserHomeComponent,    
    ],

    bootstrap: [AppComponent],
    providers: [SharedService, ToastService, MetaService, SocketService, HeaderService]
})
export class AppModule { }`

Can Anyone tell what is wrong in app.module.ts?

**Comment by beeman** [comment]
@DeekshaPandit can you please create a new issue for this question?

**Comment by DeekshaPandit** [comment]
sure
