### ISSUE TITLE
Using external dependancies and CDN for vendor

### ISSUE THREAD

**Issue by Sakuto** [angular/angular-cli#4110]
### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.24
node: 7.2.0
os: win32 x64

### Repro steps.
Take any project without external dependancies

### The log given by the failure.
No failure, just a misunderstanding.

### Mention any other details that might be useful.
I'm currently working a large company where we want to develop a wide variety of inter-connected micro application. We have chosen Angular 2 for this task but came across a problem.

Considering that we currently have 2500 active users each day and around 30 applications for certain users, even if we compress the generated bundle, it will still make: 2500 * 30 * 300 so 22.5gb per day of bandwidth since the cache is cleaned each day.

If we could just put the vendor on the CDN, we would reduce this by the number of applications and we will get to only 750 mb (which is way better).

Is it possible to generate a bundle with the vendor only, and if yes, which vendor should I put in it? I supposed that I could put all these in the vendor: `@angular/common`, `@angular/compiler`, `@angular/core`, `@angular/forms`, `@angular/http`, `@angular/platform-browser`, `@angular/platform-browser-dynamic`, `@angular/router`, `core-js`, `ts-helpers`, `zone.js` since they are all my dependencies defined in package.json

From this list: 

- How can I generate a bundle with these vendors?
- How can I tell webpack not to bundle them?
- Can I just put them in the head of my html? 
(For reference: [thread on SO](http://stackoverflow.com/questions/41697985/bundling-angular-vendor-to-put-them-on-a-cdn)

I've read about [externals](https://webpack.github.io/docs/library-and-externals.html) configuration of Webpack, but since we do not have direct access to the webpack configuration...

Many thanks!

**Comment by rodneyjoyce** [comment]
Hi,

I don't understand the requirement fully: why can you not just put everything on a CDN? ie. when it's built you deploy the whole thing to something with a CloudFlare CDN in front so that the CDN is taking the hit and not your servers?

**Comment by filipesilva** [comment]
There isn't a way to do this with the CLI. You'd need some kind of DLL bundle. When webpack bundles up everything, it rewrites the module IDs and more. The bundles look the same but the `wiring` is different.

So even if you factored it out, any number of small structural changes could mess it up.
