### ISSUE TITLE
Can we build lazyModules independently?

### ISSUE THREAD

**Issue by AbhilashThomas** [angular/angular-cli#4111]
Hi ,

Please guide me.

Consider a simple app with **100** router links:

1. Amodule
2. Bmodule
3. Cmodule
...and so on

<router-outlet></router-outlet>

All the 100 modules are configured to be loaded lazily in the router-outlet of app.component

Now suppose I make a change in Bmodule. When I run ng build, it seems that the entire app is rebuild-ed, the existing dist folder is removed and a new dist with the main bundle and **100 chunks** are created.

What I need is that I just build  Bmodule and replace that chunk alone. 

1. Is this possible?
2. Will ng build, build the entire app or just the changed module, incremental build, hence saving time for consequent ng builds?

My main aim is to automate the builds, so if the whole application is going to be built, it will take a lot of time, right?

**Comment by filipesilva** [comment]
That exact proposal is not reasonably possible, no. The 'wiring' between the modules would still be different. We're working on faster builds and rebuilds overall though on https://github.com/angular/angular-cli/issues/1980

**Comment by AbhilashThomas** [comment]
So how do you propose to build a large angular app with many teams working on it? Bundling everything every time someone checks in a 'ts' file; even for a tiny change; consumes a lot of time.

**Comment by AbhilashThomas** [comment]
Hi, do we have any update on the above?
