### ISSUE TITLE
AOT error when using Module.forRoot with variable in static function scope

### ISSUE THREAD

**Issue by rversteeg** [angular/angular-cli#4112]
### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.25.5
node: 6.5.0
os: win32 x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

### Repro steps.
Create a new angular-cli project (ng new Name), add a Module (ng g m test)

In the TestModule add a static forRoot method

```typescript
static forRoot() : ModuleWithProviders {
  let someVar = [];
  return {
    ngModule: TestModule
  }
}
```

and then add this to the imports of the AppModule

```typescript
TestModule.forRoot()
```

### The log given by the failure.
ERROR in Error encountered resolving symbol values statically. Calling function 'TestModule', function calls are not supported. Consider replacing the function or lambda with a referen
ce to an exported function, resolving symbol createTestModule in D:/Roy/projects/beta25/src/app/app.module.ts, resolving symbol AppModule in D:/Roy/projects/beta25/src/app/app.module.t
s, resolving symbol AppModule in D:/Roy/projects/beta25/src/app/app.module.ts

### Mention any other details that might be useful.
When removing the variable declaration in the forRoot function this works correctly.

**Comment by deebloo** [comment]
@rversteeg I think this is is an issue with the angular compiler more then the cli.

**Comment by rversteeg** [comment]
@deebloo https://github.com/angular/angular/issues/13931 ok, this is the same issue at the angular repo. So this can be closed.

**Comment by Ismaestro** [comment]
Check [this](https://stackoverflow.com/questions/48225993/angular-call-function-in-forroot-method). Maybe it can helps.
