### ISSUE TITLE
Proposal: remove `--lint` flag from `ng test`

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#4114]
Currently `ng test` offers the option of linting in addition to running unit tests.

This is sounds like a desirable feature since it is surely better to get both linting and testing feedback continuously via a single command.

The reality, however, is that doing both at the same in anything but a toy project time is slow. 

The purpose of running unit tests in a watch loop is to get very fast feedback on your changes, thus anything that slows it down is a problem.

When not running in watch mode, it would be just as easy to do `ng test --single-run --lint` as it is to do `ng test --single-run && ng lint`.

Additionally, different linting setups are used in each command which can lead different results/presentation.

Thus I argue that the linting flag in `ng test` should be removed because it is a 'trap', in the sense that it is only useful in trivial scenarios.

/cc @clydin

**Comment by clydin** [comment]
Related issue: #3317

**Comment by hansl** [comment]
I'm okay with this.
