### ISSUE TITLE
routing to a module freezes the build with ng serve

### ISSUE THREAD

**Issue by lebsral** [angular/angular-cli#4116]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OS 10.12.2

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.25.5
node: 6.9.4
os: darwin x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.
nimbus:catalog larsb$ ng serve
** NG Live Development Server is running on http://localhost:4200. **
 64% building modules 501/555 modules 54 active ...log/node_modules/debug/src/browser.jsError: No module factory available for dependency type: ContextElementDependency
    at Compilation.addModuleDependencies (/Users/larsb/Documents/mycode/catalog/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:190:20)
    at Compilation.processModuleDependencies (/Users/larsb/Documents/mycode/catalog/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:179:7)
    at /Users/larsb/Documents/mycode/catalog/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:319:12
    at /Users/larsb/Documents/mycode/catalog/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:126:4
    at Array.forEach (native)
    at callback (/Users/larsb/Documents/mycode/catalog/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:125:12)
    at /Users/larsb/Documents/mycode/catalog/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:149:10
    at ContextModule.<anonymous> (/Users/larsb/Documents/mycode/catalog/node_modules/angular-cli/node_modules/webpack/lib/ContextModule.js:118:3)
    at /Users/larsb/Documents/mycode/catalog/node_modules/@ngtools/webpack/src/utils.js:11:13
    at /Users/larsb/Documents/mycode/catalog/node_modules/@ngtools/webpack/src/plugin.js:196:124
    at ContextModule.resolveDependencies (/Users/larsb/Documents/mycode/catalog/node_modules/@ngtools/webpack/src/utils.js:5:9)
    at ContextModule.build (/Users/larsb/Documents/mycode/catalog/node_modules/angular-cli/node_modules/webpack/lib/ContextModule.js:99:7)
    at Compilation.buildModule (/Users/larsb/Documents/mycode/catalog/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:129:9)
    at factoryCallback (/Users/larsb/Documents/mycode/catalog/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:308:10)
    at /Users/larsb/Documents/mycode/catalog/node_modules/angular-cli/node_modules/webpack/lib/ContextModuleFactory.js:96:12
    at /Users/larsb/Documents/mycode/catalog/node_modules/tapable/lib/Tapable.js:204:11
    at /Users/larsb/Documents/mycode/catalog/node_modules/@ngtools/webpack/src/plugin.js:197:28
 70% building modules 952/952 modules 0 activ

### Mention any other details that might be useful.

Adding a 2nd routed module seems to set it off, for example adding baz to the app.routing.ts
`
import { NgModule } from '@angular/core';
import { Routes, RouterModule  } from '@angular/router';

// import { ProductsComponent } from './products/products.component';

// import { PageNotFoundComponent }    from './not-found.component';

const appRoutes: Routes = [
  // {
  //   path: 'products',
  //   loadChildren: 'app/products/products.module#ProductsModule'
  // },
  //   {
  //   path: 'users',
  //   loadChildren: 'app/users/users.module#UsersModule'
  // },
  // {
  //   path: 'admin',
  //   loadChildren: 'app/admin/admin.module#AdminModule'
  // },
  {
    path: 'baz',
    loadChildren: './baz/baz.module#BazModule'
  }
  // { path: '**', component: PageNotFoundComponent }
];

@NgModule({
  imports: [RouterModule.forRoot(appRoutes)],
  exports: [RouterModule],
  providers: []
})
export class AppRoutingModule { }
`
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by lebsral** [comment]
Hmm, I make a new project and copied stuff over from the old.  The new project is working.  I wont be able to help diagnose it beyond what it is above.

So you can go ahead and close this.

**Comment by filipesilva** [comment]
We were working on something very related to the error you showed, and had a release 5 days ago. I guess there was something broken in the deps, maybe transiently so. Anyhoo, glad it's working for you now!
