### ISSUE TITLE
Proxy options not working

### ISSUE THREAD

**Issue by kikar** [angular/angular-cli#4117]
### OS?
> macOS Sierra (10.12.2)

### Versions.
```
angular-cli: 1.0.0-beta.25.5
node: 6.9.4
os: darwin x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4
```

### Repro steps.
1. Create new project
2. Create file `proxy.conf.json` in project root
3. Run `ng serve --proxy-config proxy.conf.json --open --hmr`

There is no error given, but the proxying isn't working.
I noticed the webpack-dev-server version is 2.x, while angular-cli README points to webpack 1.x doc, so I used devServer configuration from [Webpack 2.x](https://webpack.js.org/configuration/dev-server/)
Here is my `proxy.conf.json` content:
```
{
  "proxy": {
    "/api": "http://localhost:8021"
  },
  "compress": true
}
```

You can even see that the files served and not gzipped

**Comment by splintercode** [comment]
Experiencing the same issue on Mac and CLI 25.5

**Comment by Sakuto** [comment]
I've tried right now, the proxy is not displayed anymore in the console but it's still working.

Also, my proxy.conf.json is different from yours:

```
{
  "/api": {
    "target": "http://localhost:1691/",
    "secure": false
  },

  "/oauth": {
    "target": "http://localhost:1691/",
    "secure": false
  }
}
```

Maybe you could give it a try with this structure?

```
{
  "/api": {
    "target": "http://localhost:8021/",
    "secure": false
  }
}
```

**Comment by kikar** [comment]
When inspecting angular-cli code, I noticed it doesn't take advantage of webpack 2.x devServer options, that are a bit more useful, like serving gzip files.
These `proxy.conf.json` seem to be options for [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware#http-proxy-options)

**Comment by killrazor** [comment]
So no resolution?
