### ISSUE TITLE
ng init wants to compare even when the differences are just spacing

### ISSUE THREAD

**Issue by killrazor** [angular/angular-cli#4120]
### OS?
>Red Hat Enterprise Linux Server release 6.6 (Santiago)

### Versions.
>angular-cli: 1.0.0-beta.25.5
>node: 6.6.0
>os: linux x64
>@angular/common: 2.4.4
>@angular/compiler: 2.4.4
>@angular/core: 2.4.4
>@angular/forms: 2.4.4
>@angular/http: 2.4.4
>@angular/platform-browser: 2.4.4
>@angular/platform-browser-dynamic: 2.4.4
>@angular/router: 3.4.4
>@angular/compiler-cli: 2.4.4

### Repro steps.
>run `ng init` in your local project after upgrading CLI. Have a tab instead of a space in one of the 

### The log given by the failure.
> No failure log but this is an example of the output
>
```terminal
? Overwrite src/environments/environment.prod.ts? Diff
Index: /projectLocation/environments/environment.prod.ts
===================================================================
--- /clogic/u/www/alpha/html/trackJcl/src/environments/environment.prod.ts
+++ /clogic/u/www/alpha/html/trackJcl/src/environments/environment.prod.ts
@@ -1,3 +1,3 @@
 export const environment = {
-        production: true
+  production: true
};
```

**Comment by killrazor** [comment]
I'm aware this is a minor issue that will probably be pushed back to the end of time but I thought it worth mentioning. At the least, the response from this might give time back to someone else thinking the same.

**Comment by clydin** [comment]
Dup: #1115

**Comment by killrazor** [comment]
Thanks
