### ISSUE TITLE
.ngfactory not found when upgrading @ngtools/webpack to >1.2.0

### ISSUE THREAD

**Issue by tinchou** [angular/angular-cli#4124]
### OS?
> Windows 10

### Versions.
> node v6.9.4

### Repro steps.
> I have an app set up with `@ngtools/webpack` v1.2.0 and `webpack` v2.1.0-beta.27. When I try to upgrade to any of v1.2.1, v1.2.2, v1.2.3 or v1.2.4 (and also the required webpack version) I get the following error:

```
    ERROR in ./src/boot-client-aot.ts
    Module not found: Error: Can't resolve './components/main.aot.ngfactory' in 'XXXXX\src'
     @ ./src/boot-client-aot.ts 5:0-70
```

`boot-client-aot.ts`:

```ts
import "./polyfills";
import "./rxjs-operators";

import { enableProdMode } from '@angular/core';
import { platformBrowser } from "@angular/platform-browser";
import { MainModuleNgFactory } from "./components/main.aot.ngfactory";

enableProdMode();

// Boot the application, either now or when the DOM content is loaded
const platform = platformBrowser();
const bootApplication = () => { platform.bootstrapModuleFactory(MainModuleNgFactory); };
if (document.readyState === "complete") {
    bootApplication();
}
else {
    document.addEventListener("DOMContentLoaded", bootApplication);
}
```

Webpack config:

```js
var ngToolsWebpack = require("@ngtools/webpack");
// ....
    plugins: [
        new ngToolsWebpack.AotPlugin({
            tsConfigPath: path.resolve(__dirname, "tsconfig.aot.json"),
            entryModule: path.resolve(__dirname, "ClientApp", "components", "main.aot#MainModule"),
        }),
```

It's worth noting that I tried different paths for the plugin configuration without success, including setting them through my `tsconfig.aot.json`.

Any help would be appreciated. Thanks!

**Comment by filipesilva** [comment]
@hansl any idea what's going wrong?

**Comment by tinchou** [comment]
just tried `v1.2.8` and it's still not working.

**Comment by wuzhouyang** [comment]
resolved ?

**Comment by tinchou** [comment]
Sorry I'm not able to provide a repro at the moment. Are you having this same issue? Can you help with a repro?

Thanks!

**Comment by wuzhouyang** [comment]
Sorry i just only used the @ngtool/webpack in my project. It's work in my [repo](https://github.com/wuzhouyang/angular2-seed-starter) but when i run my other project i got some error 
![image](https://cloud.githubusercontent.com/assets/12148043/22774536/8698610c-eee2-11e6-89e6-7622ea54c137.png)

**Comment by tinchou** [comment]
It seems to work if I use a simple main file and let the tools do their magic by convention like here: https://github.com/kunl/Angular-webpack-AOT/blob/master/src/main.ts

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
