### ISSUE TITLE
Deploying to github pages with custom domain is not working correctly

### ISSUE THREAD

**Issue by SlimDogs** [angular/angular-cli#4127]
> Please provide us with the following information:
When deploying Angular-cli application it uses repository name to define a base path. This is an issue when you deploy application to Github repository witch has custom domain enabled for it's Github pages.

You still need to define repository name to get app deployed but in such case you wouldn't want to have that name as absolute path of your application.

"<base href="{{ REPOSITORY NAME }}">"
in index.html should become
"<base href="{{ REPOSITORY NAME or "/" if custom domain is enabled }}">"

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
All OS

### Versions.
angular-cli: 1.0.0-beta.25.5
node: 7.3.0
os: win32 x64

### Repro steps.
1. Have a repository where Github pages setup uses custom domain
2. Deploy your app (app must contain components)
3. Test it

### The log given by the failure.
Application tries to load component files using such link structure:

{{ Custom domain}}/**{{ Repository name }}**/{{ Rest of the path to the component files }}
(I did bold out the problematic part)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by MrGrigri** [comment]
I too am having this same issue. It appears to me that it needs to maintain the `<base href="/">` tag instead of trying to inject the repository name. Maybe this could be accomplished in the `angular-cli.json` file in a `githubPages" object where you could customize the CNAME location and href value.

**Comment by jevenson** [comment]
The CLI could check for the presence of a CNAME file in the repository, and when one is detected, do not modify the base tag.

**Comment by MrGrigri** [comment]
I can confirm that it works with angular-cli version 1.0.0-beta.26. I still believe that there should be a better way. GitHub looks at the CNAME file, why can't the CLI?

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/3392.  Sorry it wasn't well documented, we're going through the docs and fixing these gaps nowadays.

@MrGrigri that PR actually creates the CNAME file. You might have one in your project, or you might not.
