### ISSUE TITLE
Polyfills for IE11 not working, for example .includes()

### ISSUE THREAD

**Issue by suuuunto** [angular/angular-cli#4128]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 8, 10. Linux (Ubuntu15.10). Mac OSX ( El Capitan)

### Versions.
angular-cli: 1.0.0-beta.24
node: 5.12.0
os: linux x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

### Repro steps.
1. App was created with angular-cli beta 24, github example on https://github.com/suuuunto/includes-example

2. Component has an function includes() and the result goes to console.

3. For ng build, tsconfig.json had to be adjusted to "es7" for "lib", with "es6" a build error occurs

4. Open page with IE 11 on Win 8.1 an error occurs in console: 
EXCEPTION: Object doesn't support property or method 'includes' 

5. Imo core-js polyfills should solve that.

### The log given by the failure.
 EXCEPTION: Object doesn't support property or method 'includes' 

Thanks, suuuunto

**Comment by clydin** [comment]
See here: https://github.com/zloirock/core-js#ecmascript-7-proposals
You need to add the appropriate import(s) to `polyfills.ts`.  Only those required by angular are included by default.

**Comment by suuuunto** [comment]
Ok, I though the function includes belongs the es6 string. But obviously I am working with an array ... and the array includes is es7. 

I added "import 'core-js/es7/array';" to polyfills.ts --> works perfect!

Thanks a lot!

**Comment by tolgabalci** [comment]
Go to your polyfills.ts and find the import statements commented out under the section:
`/** IE9, IE10 and IE11 requires all of the following polyfills. **/`

Uncomment these to have your app working with these IE browsers.

**Comment by roopkt** [comment]
Thanks @tolgabalci I uncommented the IE related imports line from polyfills.ts file. I think one more point is we have to install couple of npm packages mentioned on polyfill.ts file. I overlooked them and it was not working. Then I had to go install classlist.js and web-animations-js etc.. npm packages.
`//import 'classlist.js';   // Run `npm install --save classlist.js`.`
`//import 'web-animations-js';  // Run `npm install --save web-animations-js`.`  so on..

**Comment by phani257** [comment]
I dont see polyfill.ts getting created along with the app.

**Comment by tolgabalci** [comment]
@phani257 polyfills.ts is created under the src folder.

**Comment by snibbo** [comment]
I got the same issue. Thanks for the solution.
Can anyone explain why the import statements are commented out by default?

**Comment by rotatopoti** [comment]
Is it possible to choose these polyfills when running the cli?

**Comment by hawkwind2** [comment]
I have polyfills.js but can't find polyfills.ts...

**Comment by matthewswallace** [comment]
why are these not uncommented, to begin with?

**Comment by adamdport** [comment]
If anyone else tries @suuuunto's es7 fix and gets `Exception thrown and not caught` errors, I learned that you should **add** the es7 import, **not** replace the es6 one. That is, **don't remove the es6 import!** You should end up with 

```
import 'core-js/es6/array';
import 'core-js/es7/array';
```

**Comment by etonyali** [comment]
Don't forget to add this as well.
**index.html**
`<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>`

**Comment by sgentile** [comment]
This is still broken, core-js has changed and object.freeze throws errors.

ie. 

https://github.com/zloirock/core-js/issues/412

**Comment by hpawe01** [comment]
@etonyali: you don't need to add this meta tag (X-UA-Compatible) anymore: https://stackoverflow.com/questions/26346917/why-use-x-ua-compatible-ie-edge-anymore

**Comment by etonyali** [comment]
@hpawe01 if you are developing locally, you should add it. Please review the link you posted.

**Comment by hpawe01** [comment]
@etonyali: fair enough. It sounded like an edge case and I didn't thought, that you also need it for local development. Updated my comment.

**Comment by Yohandah** [comment]
this is working for me just doing so :
`import "core-js/es/array";`

no need for es6/ + es7/

**Comment by changhuixu** [comment]
you can further break down to just doing:
`import 'core-js/modules/es.array.includes';`
