### ISSUE TITLE
CLI beta.26 adds CLI 25.5 as a dependency to package.json

### ISSUE THREAD

**Issue by montella1507** [angular/angular-cli#4129]
NG NEW with angular-cli beta.26 adds   "angular-cli": "1.0.0-beta.25.5" to package.json devDependencies.

**Comment by grizzm0** [comment]
It looks like beta 26 haven't been tagged properly. @hansl has already been notified.

**Comment by Meligy** [comment]
Try again now. It looks like angular-cli@latest now points to 1.0.0-beta.26.

**Comment by montella1507** [comment]
@Meligy   i have cli beta.26  
ng v:
angular-cli: 1.0.0-beta.26

ng new app 
app/package.json 
angular-cli: "1.0.0-beta.25.5"

**Comment by grizzm0** [comment]
@hansl Forgot to push after he tagged. :) He'll fix it as soon as he gets to work.

**Comment by montella1507** [comment]
So i can close the issue?

**Comment by grizzm0** [comment]
Yes, will be fixed in a few hours.
