### ISSUE TITLE
ng version display beta.21 despite .26 is installed on win7-x64

### ISSUE THREAD

**Issue by psaussure** [angular/angular-cli#4131]
### Type
Bug, not blocking

### Summary
Version displayed using `ng --version` on win7-x64 is wrong.

### OS
Windows 7

### Versions.
> angular-cli: 1.0.0-beta.21
> node: 7.4.0
> os: win32 x64

### Repro steps.

- Installed clean node
- Check no global node_modules is here except npm
- `npm install -g npm` to update NPM
- `npm install -g angular-cli`: installs the angular-cli 

> +-- angular-cli@1.0.0-beta.26
> | +-- @angular-cli/ast-tools@1.0.15
> | | `-- @angular/tsc-wrapped@0.5.1
> | |   `-- tsickle@0.2.4
> | |     `-- source-map-support@0.4.10
> | +-- @angular-cli/base-href-webpack@1.0.15
> ...

- `ng --version`: 
> angular-cli: 1.0.0-beta.21
> node: 7.4.0
> os: win32 x64

### Additional comment
Was tested under linux and max, I don't encounter the problem and proper version is displayed.

**Comment by RicardoVaranda** [comment]
@psaussure Try to clear your cache before re-installing angular-cli:

```
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest
```

**Comment by Brocco** [comment]
This could also be an issue with the local project's version of angular-cli. The global install hands off to the local installation within projects.

So ensure that if you are in a project directory that you update that version as well.

**Comment by psaussure** [comment]
I'm **outside of any project** (C: root).

```
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest
```

The same result occurs:
```
ng --version
angular-cli: 1.0.0-beta.21
node: 7.4.0
os: win32 x64
```

**Comment by filipesilva** [comment]
You probably have another set of global node_modules somewhere. This can happen especially if you're using `nvm`. These problems are often very hard to diagnose, and completely outside the purview of the CLI.

My best advice is to reinstall NPM (and NVM if you use it). You can also try to manually track down this second global node_modules location and fix it.

**Comment by psaussure** [comment]
Thanks, will check on this.
