### ISSUE TITLE
Force AOT in prod

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#4138]
Just set the AOT default to true for production builds.

**Comment by tsabirgaliev** [comment]
This + i18n can bring headaches to users

**Comment by filipesilva** [comment]
@tsabirgaliev what problems do you predict? Mind you that it's a default, you can always do `ng build prod --no-aot`.

**Comment by tsabirgaliev** [comment]
Yes, you are right, actually no big problems. Just disabling AoT will solve that.

**Comment by cacogr** [comment]
The title is a bit misleading then. It probably should be "Default to AOT in prod".
