### ISSUE TITLE
fix(build): use baseUrl and paths from tsconfig (filipesilva )

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#4147]
While checking current file from #26:
   packages/angular-cli/models/webpack-build-test.js

And the one of the fix submitted under this forked branch of @filipesilva :
filipesilva/angular-cli/ packages/angular-cli/models/webpack-build-test.js

Are there any plans to merge ? Or in other words if I want this mapping simlar the way @angular is using it should I merge this over? 

So not sure what is the status of this feature .

Thanks, 
Frank

**Comment by filipesilva** [comment]
Paths from tsconfig should work, since `ng test` is wired to compile your code with it. Not too sure about baseUrl, but if it works on `ng serve` it should work on `ng test.

**Comment by fkolar** [comment]
Yeap it seams to work nicely using @scoped packages which are mapped using paths. I wish you guys prioritize work on "Angular-Cli for library developement " ;-) 

Thank you, 
-Fk
