### ISSUE TITLE
ng init looks at parent folder instead of pwd

### ISSUE THREAD

**Issue by QuantumInformation** [angular/angular-cli#4148]
### OS?
 Mac OSX

### Versions.
1.0.0-beta.24

ng init in an empty folder tries to overwrite files in the parent directory:

![image](https://cloud.githubusercontent.com/assets/216566/22173404/85edb7a8-dfb9-11e6-9f6d-3783f7280eb0.png)

**Comment by Meligy** [comment]
Let me guess, it looks at the nearest folder with a `package.json` file?

**Comment by QuantumInformation** [comment]
Yeah most likely. Not what I want in my case as I'm wanting to create a standalone project in the demo folder, to test the angular lib in the parent.

**Comment by filipesilva** [comment]
Yeah it's the package.json, it's the project 'marker'. At the moment this is "working as intended" though... 

In the future the init functionality is likely to be removed as a followup to https://github.com/angular/angular-cli/issues/4007.

**Comment by QuantumInformation** [comment]
Creating an empty package.json fixed it!
