### ISSUE TITLE
angular-cli: 1.0.0-beta.26 is not pointing on parameters fixed in ember-cli

### ISSUE THREAD

**Issue by selem1** [angular/angular-cli#4149]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Linux x64
Ubuntu 14.04 LTS 

### Versions.
angular-cli: 1.0.0-beta.26
node: 7.4.0

### Repro steps.
Once I'd upgraded my `angular-cli` to the above mentioned version, it would not recognize the parameters fixed in `ember-cli` when running `ng serve` as usually. So, I could not run my application on a specific domain name different from the basic `http://localhost:4200`. Here is how my `ember-cli` file looks like: 
```
{
  "ssl": true,
  "open": true,
  "port": 3000,
  "liveReload": true,
  "host": "dev.dev.com",
  "ssl-key": "./key.pem",
  "ssl-cert": "./cert.pem",
  "checkForUpdates" : false
}

```

### The log given by the failure.
There is no failure, except the mentioned issue

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
It is recommended to not rely on ember-cli specific functionality.  There is no guarantee it will be available in a future release.

Augmenting the npm start script with your options and using npm start instead of ng serve  is a currently viable alternative for your use case.

**Comment by filipesilva** [comment]
`ember-cli` file functionality was fully removed in one of the last releases, but tbh it was never really supported since beta.12 I think.

@clydin's advice is solid.

**Comment by selem1** [comment]
Well, it was supported actually with beta.24, anyway Thank you both indeed for the swift feedbacks @clydin  & @filipesilva .
