### ISSUE TITLE
Feature req: Environment specific assets/ angular-cli files

### ISSUE THREAD

**Issue by mmc41** [angular/angular-cli#4150]
Currently, one can add asset folders by adding them to angular-cli.json's assets key. These assets will always be added regardless of environment.

I need to add test assets (stub-data) for test/development environments only - they should not be added to production. Hence I would like, angular-cli to support specifying different sets of asset folders depending on the build environment. 

Another more general option, would be for  angular-cli to support multiple angular-cli*.json files (additional files with environment specific overrides).

**Comment by filipesilva** [comment]
I know some users are adding stubs via the environment files (see https://github.com/angular/angular-cli/issues/3940) but I understand your request is different.

I'll tag it for discussion but don't have any plans to add it for now.

**Comment by mmc41** [comment]
Thanks for the link. Yes, my case is different. I need to add different json files (and other resource files) depending on the environment.

**Comment by mmc41** [comment]
@filipesilva Just found out that the "apps" option in angular-cli.json is really an array although it seems only first element is currently supported. If angular was changed to fully support multiple elements in the configuration "apps" array than my use case (and many, many other use-cases) would be solved!

**Comment by ciesielskico** [comment]
+1, need to load different images for different environments

**Comment by d0nkeyBOB** [comment]
+1, We're going through the same problem, right now. Environment based assets would be beneficial.

**Comment by filipesilva** [comment]
Heya @mmc41, you can now use the apps array as documented here: https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/multiple-apps.md

**Comment by KashMoneyMillionaire** [comment]
I believe this has moved here now: https://github.com/angular/angular-cli/wiki/stories-multiple-apps

**Comment by takahser** [comment]
Is this feature still available in Angular 8?

Currently, I have several directories:

- src/assets/images/customer1
- src/assets/images/customer2
- src/assets/images/customer3

After the build, the folder of the configured customer should be available 1 directory level higher.
E.g. when running `ng serve --app=customer1` all files in `src/assets/images/customer1` should be available in `src/assets/images`. None of the other customer's assets should be available there.

(I've taken a look at the links above, but they either refer to the old `angular-cli.json` file or didn't contain any helpful information to solve my problem)

**Comment by MickL** [comment]
Instead could instead have:

- assets/ (shared assets)
- assets/customer1/`
- assets/customer2/`
- assets/customer3/`

And then you can add it to the build of each customer:

```
"assets": [
                "src/assets",
                {
                  "glob": "**/*",
                  "input": "src/assets/customer1",
                  "output": "/assets"
                }
],
```

**Comment by takahser** [comment]
@MickL thanks, that worked 👍🏼
