### ISSUE TITLE
Rxjs code throws error and fails to run.

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular-cli#4152]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Ubuntu Linux

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.25.5
node: 7.2.1
os: linux x64

Linux flash 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

See code below

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

The following code generates a TS error and fails to run. I've tried something similar using Rxjs and TS on a console test code, I see the same tsc error but the code runs as expected.

**RxJS version:**
"rxjs": "^5.0.3",

**Code to reproduce:**

```js
import { Component } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { Subject } from 'rxjs/Subject';
import 'rxjs/Rx';

@Component({
  selector: 'app-root',
  template: `
    <button (click)='click$.next()'>Update</button>
    <h1>{{clock$ | async | date:'y MMM d jms'}}</h1>
  `,
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  click$ = new Subject();
  clock$;

  constructor() {
    this.clock$ = Observable.merge(
      this.click$,
      Observable.interval(1000)
    )
    .startWith(new Date())
    .scan((acc, curr)=> {
      const date = new Date(acc.getTime());
      date.setSeconds(date.getSeconds() + 1);
      return date;
    });
  }
}
```

Throws and error and fails to run:
```
ngrx-app: master$ ng s
** NG Live Development Server is running on http://localhost:4200. **
Hash: 4b06c933b6a34917c731                                                               
Time: 10139ms
chunk    {0} main.bundle.js, main.bundle.map (main) 3.42 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 9.96 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.84 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/app/app.component.ts
Module build failed: Error: /tmp/ngrx-app/src/app/app.component.ts (28,33): Property 'getTime' does not exist on type 'number | {}'.)
    at _checkDiagnostics (/tmp/ngrx-app/node_modules/@ngtools/webpack/src/loader.js:145:15)
    at /tmp/ngrx-app/node_modules/@ngtools/webpack/src/loader.js:172:17
 @ ./src/app/app.module.ts 14:0-47
 @ ./src/main.ts
 @ multi main
webpack: bundle is now VALID.
```

**Comment by clydin** [comment]
The error does not appear to be CLI related.
StackOverflow may be a more appropriate forum for issues such as this.

**Comment by rajinder-yadav** [comment]
So why is the generates JS code not running? I've coded this with a simple console test app using TS with Rxjs and the code at least runs.

**Comment by clydin** [comment]
You're getting a typescript error. 
You have an observable of type `Observable<number | {}>`.  Neither `number` nor `{}` have a `getTime()` function.

**Comment by rajinder-yadav** [comment]
My question is why does the code not run? I see "Loading..." in the browser window.

As for the TS error, I am chasing this down with the TypeScript team. However `.startWith(new Date())`, (should) clearly sets the value in `acc` to be a `Date` object that has `getTime()` function.

**Comment by rajinder-yadav** [comment]
OK found a fix to at least get the code working by setting type for `acc` and `curr` to be `any`. Doing this the code works and the errors are gone.
