### ISSUE TITLE
Documentation needed for angular-cli.json

### ISSUE THREAD

**Issue by mmc41** [angular/angular-cli#4154]
I can not find any documentation for angular-cli.json and how to properly configure it.

For instance:
a) What is the "addons" and "packages" keys for ?

b) The value of the "apps" key is an array where it appears only first entry is presently used. It would be nice if I can add multiple configuration values and chose which one to use from the CLI interface. Is that possible or planned for the future (as the array type seems to indicate) ?

**Comment by beeman** [comment]
@mmc41 there is currently no documentation for angular-cli.json that I know of, it might be useful to have it though.

One of the places to read up on what the various components do is in this schema file:

https://github.com/angular/angular-cli/blob/08bb738af2a3a257e003081caa154f014cb5365b/packages/angular-cli/lib/config/schema.json

A lot of things are inherited from being based off ember-cli, like addons, packages and the support for multiple apps but all this is currently all not supported. 

Please note that addons, packages recently got removed from the default generated app as it raised too much questions #4052

I hope this answers your questions.

**Comment by mmc41** [comment]
@beeman Thank you very much for your answer. It helps.

**Comment by filipesilva** [comment]
We do plan on having multiple app support, but currently they are not supported.

I agree we need better docs. That's being tracked in https://github.com/angular/angular-cli/issues/2711. I'll add the config file item there as well.

**Comment by decodeJarvis** [comment]
You can refer to their wiki:
https://github.com/angular/angular-cli/wiki/stories

**Comment by filipesilva** [comment]
There's also a dedicated wiki page for `.angular-cli.json` https://github.com/angular/angular-cli/wiki/angular-cli, and multiple apps https://github.com/angular/angular-cli/wiki/stories-multiple-apps.

**Comment by cili93** [comment]
pozdrav

**Comment by MickL** [comment]
@filipesilva Both pages are missing in the wiki list: https://github.com/angular/angular-cli/wiki/stories

**Comment by filipesilva** [comment]
@MickL the multiple apps story was replaced by the multiple project story: https://github.com/angular/angular-cli/wiki/stories-multiple-projects

The config information is also there at https://github.com/angular/angular-cli/wiki/angular-workspace. It doesn't go very deep in detail but it is there.
