### ISSUE TITLE
ERROR in Cannot read property 'content' of null

### ISSUE THREAD

**Issue by beeman** [angular/angular-cli#4165]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?

macOS Sierra

### Versions.

**Running of angular/angular-cli#master**

angular-cli: 1.0.0-beta.26
node: 7.2.0
os: darwin x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

### Repro steps.

- Set up the [development setup of angular-cli](https://github.com/angular/angular-cli#development-hints-for-hacking-on-angular-cli)
- ng new --link-cli content-of-null
- cd content-of-null
- ng serve
- Edit something in `src/app/app.component.html`

### The log given by the failure.
> Normally this include a stack trace and some more information.

After editing the app rebuilds and this message appears:

`ERROR in Cannot read property 'content' of null`

No further stack-trace available.

### Mention any other details that might be useful.

The app seems to work though this message persists.

**Comment by filipesilva** [comment]
Can confirm this happens:

![image](https://cloud.githubusercontent.com/assets/4172079/22186955/0ba14d00-e0f6-11e6-9980-830febdab4c0.png)
```
kamik@T460p MINGW64 /d/sandbox/master-project (master)
$ ng serve -o
** NG Live Development Server is running on http://localhost:4200. **
 10% building modules 6/11 modules 5 active ...t\node_modules\@angular\core\index.jswebpack: wait until bundle finished: /
Hash: 2583d4a7fddc703271c3
Time: 9820ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.map (main) 62.2 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 9.96 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.57 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
Hash: 70192ef2c5a1c620ab15
Time: 956ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial]
chunk    {1} main.bundle.js, main.bundle.map (main) 62.2 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 9.96 kB {4} [initial]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.57 MB [initial]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]

ERROR in Cannot read property 'content' of null
webpack: bundle is now VALID.

kamik@T460p MINGW64 /d/sandbox/master-project (master)
$
```

**Comment by filipesilva** [comment]
Also seems to happen when changing `.ts` and `.css` files.
