### ISSUE TITLE
How to pass environment variables to my code?

### ISSUE THREAD

**Issue by blackcatIan** [angular/angular-cli#4170]
There is 
environment.prod.ts  and environment.ts 
I put different variables value in them like:

//environment.ts 
export const environment = {
  production: false,
  loginurl:"localhost:8080"
};

//environment.prod.ts 
export const environment = {
  production: false,
  loginurl:"xxx.xxx.com"
};

how can I read loginurl variable with  defferent webpack environment?

**Comment by beeman** [comment]
@blackcatIan from the documentation in `environment.ts`:

```
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
```

**Comment by hansl** [comment]
Considering this as closed from @beeman comment. Cheers!
