### ISSUE TITLE
Property 'status' does not exist on type 'XMLHttpRequestEventTarget'

### ISSUE THREAD

**Issue by darkkean** [angular/angular-cli#4171]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac OSX El Capitan 10.11.6

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.26
node: 6.9.4
os: darwin x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/compiler-cli: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/platform-server: 2.4.4
@angular/router: 3.4.4

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

No, this is an app create with CLI.

I have a code which uses `XMLHttpRequest`. See below.

```
   public exportToPdf(inputParam: Object): Observable<boolean> {
        let finish: Observable<boolean> = Observable.create(observer => {
            let xhr = new XMLHttpRequest();
            xhr.open('POST', environment.webservice_url, true);

            xhr.responseType = 'arraybuffer';

            xhr.onload = function(e) {
                observer.next(true);

                if (this.status === 200) {
                    console.dir(this.response);
                }
            };
            xhr.send(JSON.stringify(inputParam));
        });

        return finish;
    }
```

### The log given by the failure.
> Normally this include a stack trace and some more information.

`Property 'status' does not exist on type 'XMLHttpRequestEventTarget'.)`
and
`Property 'response' does not exist on type 'XMLHttpRequestEventTarget'.)`

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@darkkean this looks like it's an TypeScript issue, `Property 'X' does not exist on type 'Y'.` and is most likely unrelated to Angular CLI

**Comment by hansl** [comment]
You probably meant `xhr.status == 200` instead of `this`. See https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests

**Comment by darkkean** [comment]
Thanks guys @beeman @hansl.
