### ISSUE TITLE
InMemoryWebApiModule does not work.

### ISSUE THREAD

**Issue by blackcatIan** [angular/angular-cli#4175]
npm install --save angular2-in-memory-web-api
then do like the tutorial

**step 1  add in-memory-data.service.ts**
//in-memory-data.service.ts
```typescript
import {InMemoryDbService} from "angular2-in-memory-web-api/index";
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    let heroes = [
      {id: 11, name: 'Mr. Nice'},
      {id: 12, name: 'Narco'},
      {id: 13, name: 'Bombasto'},
      {id: 14, name: 'Celeritas'},
      {id: 15, name: 'Magneta'},
      {id: 16, name: 'RubberMan'},
      {id: 17, name: 'Dynama'},
      {id: 18, name: 'Dr IQ'},
      {id: 19, name: 'Magma'},
      {id: 20, name: 'Tornado'}
    ];
    return {heroes};
  }
}
```

**step2 update AppModule**
//app.module.ts
```typescript
import {BrowserModule, Title} from "@angular/platform-browser";
import {NgModule} from "@angular/core";
import {FormsModule} from "@angular/forms";
import {HttpModule} from "@angular/http";
import {AppComponent} from "./app.component";
import {AppRoutingModule} from "./app-routing.module";
import {PageNotFoundComponent} from "./common/page-not-found/page-not-found.component";
import {InMemoryWebApiModule} from "angular2-in-memory-web-api/index";
import {InMemoryDataService} from "./memory-data/in-memory-data.service";

@NgModule({
  declarations: [
    AppComponent,
    PageNotFoundComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    InMemoryWebApiModule.forRoot(InMemoryDataService),
    AppRoutingModule
  ],
  providers: [
    Title
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

After done the steps above,I just run `start` script in package.json(ng serve)
Output an error:

ERROR in Error encountered resolving symbol values statically. Calling function 'InMemoryWebApiModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in D:/angular2/cli-demo/src/app/app.module.ts, resolving symbol AppModule in D:/angular2/cli-demo/src/app/app.module.ts

What's wrong?How could I make it works?

**Comment by filipesilva** [comment]
Heya, you seem to be using an old version of https://github.com/angular/in-memory-web-api. 

Install `npm install --save angular-in-memory-web-api` instead (without the `2`), that version should be ok. The old version wasn't statically analyzable which caused problems with AoT.

**Comment by thoughtpalette** [comment]
Like to reopen this if possible. Running into the same issue, even after `npm install --save angular-in-memory-web-api`

According to the third comment on this answer [SO](http://stackoverflow.com/a/37390321), I need to update my `angular-cli-build.js` file, though I do not have one on my system. I also do not have a system-config file generated by the cli. Only a `.tsconfig.json` & `angular-cli.json`.

Any direction on how to move forward? 

Versions, etc
```
@angular/cli: 1.0.0-beta.32.3
node: 6.10.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8
```

**Comment by DwordPtr** [comment]
@thoughtpalette I had that same issue I added the following to my package.json
` "angular-in-memory-web-api": "0.1.0"`

Although now I'm getting 404 errors in my console.

**Comment by xmlking** [comment]
I am using `"angular-in-memory-web-api": "~0.3.1"` with ` "@angular/cli": "1.0.3"` and angular `4.1.1`
`ng serve` works but  `ng serve  --target=production` is not working. getting 404 error. 

code example
https://github.com/xmlking/hub

**Comment by ddwolf** [comment]
encountered the same problem, with angular-in-memory-web-api: 0.5.3 @angular/cli 1.6.7

**Comment by aelkoussy** [comment]
Encountered the same issue, following angular tour of heroes tutorial:
```
npm install angular-in-memory-web-api --save
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ angular-in-memory-web-api@0.5.3
updated 1 package in 25.102s
```

_Getting error:
src/app/app.module.ts(13,48): error TS2307: Cannot find module '@angular-in-memory-web-api'_

**Comment by aelkoussy** [comment]
Actually it was due to a mistake in typing import itself , I was using @angular in the import while I shouldn't
The import should be : (without @)
`import { HttpClientInMemoryWebApiModule } from 'angular-in-memory-web-api';`

The angular-cli is working fine in this case.

**Comment by DwordPtr** [comment]
honestly I think providing new users with a minimal backend in various states of completion might be favorable.

**Comment by SMAK1993** [comment]
Faced version compatibility issues:
```
npm install angular-in-memory-web-api --save
npm WARN angular-in-memory-web-api@0.6.0 requires a peer of @angular/common@^6.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-in-memory-web-api@0.6.0 requires a peer of @angular/core@^6.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-in-memory-web-api@0.6.0 requires a peer of @angular/http@^6.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-in-memory-web-api@0.6.0 requires a peer of rxjs@^6.0.0-beta.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ angular-in-memory-web-api@0.6.0
added 1 package in 6.927s
```
According to changelog: https://github.com/angular/in-memory-web-api/blob/master/CHANGELOG.md
Version 0.6.0 has breaking changes and is probably only compatible with Angular 6 (not LTS yet).

Made it work by downgrading to angular-in-memory-web-api@0.5.4.

`npm install angular-in-memory-web-api@0.5.4 --save`

**Comment by selimelawwa** [comment]
@SMAK1993  hello
I downgrading to angular-in-memory-web-api@0.5.4. as you suggested and it loads and updates data fine on the front end but it doesn't update the saved data in "in-memory-data-service" file. so when I refresh all data is back to original. Do you have a solution for this ? or is that the code is only for editing/adding/deleting data temporarily?

**Comment by selimelawwa** [comment]
Ok Thanks alot

**Comment by ibnthani2016** [comment]
Thanks all.I have tried all options stated here and other places but  still found the in-memory-web-api was not saved in my src folder.why

**Comment by jorgealmeidafrede** [comment]
Hi ,
After trying all the options, I work after reloading server, with version @ 0.5.4.
But do not try to do this with @ 0.6.0.
thanks to all

**Comment by groberge** [comment]
I came to this thread after installing 0.6.0 so I did an uninstall

npm uninstall angular-in-memory-web-api --save

And then did an install of 0.5.4 and it seems to be working

npm install angular-in-memory-web-api@0.5.4 --save

**Comment by advancewarsbest** [comment]
I'm coming here straight from tour of heroes: 

Module not found: Error: Can't resolve './in-memory-data.service'

I've run it twice; npm install angular-in-memory-web-api --save

checked and my package.json and package-lock.json have both been updated but no in-memory service file has been created:

"angular-in-memory-web-api": "^0.6.1",

both say 0.6.1. will try what some of the suggestions say here and update accordingly.

**Comment by mayank-aggarwal28** [comment]
> 
> 
> Faced version compatibility issues:
> 
> ```
> npm install angular-in-memory-web-api --save
> npm WARN angular-in-memory-web-api@0.6.0 requires a peer of @angular/common@^6.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
> npm WARN angular-in-memory-web-api@0.6.0 requires a peer of @angular/core@^6.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
> npm WARN angular-in-memory-web-api@0.6.0 requires a peer of @angular/http@^6.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
> npm WARN angular-in-memory-web-api@0.6.0 requires a peer of rxjs@^6.0.0-beta.1 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> + angular-in-memory-web-api@0.6.0
> added 1 package in 6.927s
> ```
> 
> According to changelog: https://github.com/angular/in-memory-web-api/blob/master/CHANGELOG.md
> Version 0.6.0 has breaking changes and is probably only compatible with Angular 6 (not LTS yet).
> 
> Made it work by downgrading to angular-in-memory-web-api@0.5.4.
> 
> `npm install angular-in-memory-web-api@0.5.4 --save`

I did this but I am still getting issues

> npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\maggarwal\package.json'
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\maggarwal\package.json'
> npm WARN angular-in-memory-web-api@0.5.4 requires a peer of @angular/common@>=2.0.0 <6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN angular-in-memory-web-api@0.5.4 requires a peer of @angular/core@>=2.0.0 <6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN angular-in-memory-web-api@0.5.4 requires a peer of @angular/http@>=2.0.0 <6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN angular-in-memory-web-api@0.5.4 requires a peer of rxjs@^5.1.0 but none is installed. You must install peer dependencies yourself.
> npm WARN maggarwal No description
> npm WARN maggarwal No repository field.
> npm WARN maggarwal No README data
> npm WARN maggarwal No license field.
> 
> + angular-in-memory-web-api@0.5.4
> updated 1 package and audited 1 package in 1.397s
> found 0 vulnerabilities

**Comment by fabki00** [comment]
If you are using `"@angular/core": "^7.0.0",` you can update angular-in-memory-web-api to version 7 in your package.json :
`
"angular-in-memory-web-api": "^0.7.0",
`

**Comment by alefeio** [comment]
> `"`

Your solution worked perfectly. Thank you!
