### ISSUE TITLE
ng generate module 

### ISSUE THREAD

**Issue by carlosdv4** [angular/angular-cli#4176]
Will be possible to add this command to ng g module?

--flat flag to indicate if a dir is created

**Comment by filipesilva** [comment]
@Brocco what do you think?

Related: https://github.com/angular/angular-cli/issues/4155

**Comment by Brocco** [comment]
I don't have an issue with this, even though I don't think I'd use it. But I do not want this implemented until a decision is made no the related issue from above #4155.

**Comment by Brocco** [comment]
This option was added via this PR: #4767 - closing this issue.
