### ISSUE TITLE
Error on Object Rest/Spread Properties syntax

### ISSUE THREAD

**Issue by aksyonov** [angular/angular-cli#4178]
### OS?
Ubuntu 16.04

### Versions.
```
angular-cli: 1.0.0-beta.26
node: 6.8.1
os: linux x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/compiler-cli: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/material: 2.0.0-beta.0
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
```

### Repro steps.
Use `Object Rest/Spread Properties` syntax inside any file:
```ts
let a = { ...b, c };
```

### The log given by the failure.
```
ERROR in ./src/app/app.component.ts
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at _getContentOfKeyLiteral (/home/sergey/ng2-project/node_modules/@ngtools/webpack/src/loader.js:8:13)
    at /home/sergey/ng2-project/node_modules/@ngtools/webpack/src/loader.js:83:62
    at Array.some (native)
    at /home/sergey/ng2-project/node_modules/@ngtools/webpack/src/loader.js:83:32
    at Array.filter (native)
    at _removeModuleId (/home/sergey/ng2-project/node_modules/@ngtools/webpack/src/loader.js:82:10)
    at /home/sergey/ng2-project/node_modules/@ngtools/webpack/src/loader.js:167:48
 @ ./src/app/app.module.ts 8:0-89
```
### Mention any other details that might be useful.

I didn't have this error when using `angular-cli: 1.0.0-beta.24`. Looks like it started failing after fix #4078.

**Comment by intellix** [comment]
Object Rest/Spread is only supported in TS 2.1 and Angular don't officially support that yet :)

**Comment by filipesilva** [comment]
Closing as answered.

**Comment by aksyonov** [comment]
As a matter of fact, Angular supports TS 2.1 - in version [2.4.2](https://github.com/angular/angular/blob/master/CHANGELOG.md#242-2017-01-06) one of changes is `support TypeScript 2.1`, that's probably partial support, but still my application worked well with `TS 2.1` and `angular-cli: 1.0.0-beta.24` until I updated `angular-cli` to `1.0.0-beta.26`.

**Comment by stevenjob** [comment]
Any update on this?
