### ISSUE TITLE
tslint : The method "<METHOD or PROP>" that you're trying to access does not exist in the class declaration

### ISSUE THREAD

**Issue by SMAH1** [angular/angular-cli#4181]
angular-cli: 1.0.0-beta.26
node: 7.4.0
os: linux x64 (Ubuntu 16.04.1 LTS)
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/upgrade: 2.4.4

I inherit component like 
`export class SubComponent extends BaseComponent { ... }`
and use method or property of `BaseComponent` in `sub.component.html` (`sub.component.ts` is empty).
when run `ng lint` show error like

> The method/property **** that you're trying to access does not exist in the class declaration

for SubComponent.
But method or property define in BaseComponent.
So program compile and it's OK.

**Comment by filipesilva** [comment]
This seems like a bug in the linter itself. Can you open this on https://github.com/mgechev/codelyzer instead?
