### ISSUE TITLE
"Getting started with angular-cli" Demo app not working (css failure?)

### ISSUE THREAD

**Issue by SproutFallout** [angular/angular-cli#4182]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10 Pro

### Versions.
angular-cli: 1.0.0-beta.26
node: 6.9.4
os: win32 x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

### Repro steps.
I followed the instructions on "Getting started with angular-cli"

### The log given by the failure.
No error evident, apart from the "Green" Hello ng alert doesn't display.

It does work on when running a previous version on angular-cli....

angular-cli: 1.0.0-beta.25.5
node: 6.9.4
os: win32 x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
Can you provide a link to the instructions you followed?

**Comment by SproutFallout** [comment]
No problems here you go.... https://github.com/valor-software/ng2-bootstrap/blob/development/docs/getting-started/ng-cli.md

**Comment by filipesilva** [comment]
@SproutFallout you'll have to open up an issue at that repo instead. They probably have some problem in their setup.

**Comment by SproutFallout** [comment]
Ok, this was a pebcak moment, thanks for your time
