### ISSUE TITLE
Error with usage NgFor from @angular/common

### ISSUE THREAD

**Issue by CisSasGot** [angular/angular-cli#4185]
> My information about the problem (step by step) with usage `NgFor from @angular/common`,
> ---------------------------------------------------------------

###   the environment 
> Windows 10 Pro x64  Insider build 15014
> angular-cli: 1.0.0-beta.26
> node: 7.4.0
> os: win32 x64

### the dependence Versions.
> @angular/common: 2.4.4;  _and local in project : **2.3.1** initiated by this CLI_
> @angular/compiler: 2.4.4;  _and local in project : **2.3.1** initiated by this CLI_
> @angular/core: 2.4.4;  _and local in project : **2.3.1** initiated by this CLI_
> @angular/forms: 2.4.4;  _and local in project : **2.3.1** initiated by this CLI_
> @angular/http: 2.4.4;  _and local in project : **2.3.1** initiated by this CLI_
> @angular/platform-browser: 2.4.4;  _and local in project : **2.3.1** initiated by this CLI_
> @angular/platform-browser-dynamic: _2.4.4;  and local in project : **2.3.1** initiated by this CLI_
> @angular/router: 3.4.4;  _and local in project : **3.3.1** initiated by this CLI_
> @angular/compiler-cli: 2.4.4;   _and local in project : **2.3.1** initiated by this CLI_

### Repro steps.
> 1) I run command `ng new PROJECT_NAME`
> 2.1) I added to the `app.component.ts` line with
> ```TypeScript
> import { NgFor } from '@angular/common';
> ```
> 2.2) I changed the content of exported class, to:
>  ```TypeScript
> export class AppComponent {
>     days: string[];
>     constructor () {
>        this.days = ['Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota', 'Niedziela'];
>        }
>    }
> ```
> 2.3) I changed the template on `app.component.html`, to:
> ```HTML
> <div><h1>Nazwy dni tygodnia</h1>
> <ul><li *ngFor="day of days">{{day}}</li></ul></div>
> 
> ```

### The log given by the failure.
> 3.0) then run `ng serve` ..this is result
> ```PowerShell
> Hash: 94387eb96eb8d861fc88
> Time: 2738ms
> chunk    {0} main.bundle.js, main.bundle.map (main) 6.75 kB {2} [initial] [rendered]
> chunk    {1} styles.bundle.js, styles.bundle.map (styles) 9.96 kB {3} [initial]
> chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.84 MB [initial]
> chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]
> webpack: bundle is now VALID.
> ```
> 4.0) and open `http://localhost:4200/` and here comes the problem so you should see a list of days of the week, but there is only a message from the master file `index.html` that **`Loading...`** 

### Mention any other details that might be useful.
> 5.0 ) Then run the suite of Developer Tools in `Chrome Canary` and going to `console` and havetwo  **log error** `zone.js:420` and `zone.js:422`. **[My project is also online on github https://github.com/Cisowscy/Cisowscy.github.io](https://github.com/Cisowscy/Cisowscy.github.io)**
>
> **`zone.js:420`**
>
> ```console
> Unhandled Promise rejection: Template parse errors:
> Can't bind to 'ngFor' since it isn't a known property of 'li'. ("
>   <h1>Nazwy dni tygodnia</h1>
>   <ul>
>     <li [ERROR ->]*ngFor="day of days">{{day}}</li>
>     
>   </ul>
> "): AppComponent@3:8
> Property binding ngFor not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
>   <h1>Nazwy dni tygodnia</h1>
>   <ul>
>     [ERROR ->]<li *ngFor="day of days">{{day}}</li>
>     
>   </ul>
> "): AppComponent@3:4 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: > Error: Template parse errors:
> Can't bind to 'ngFor' since it isn't a known property of 'li'. ("
>   <h……}message: (...)name: (...)originalStack: (...)stack: (...)toSource: function ()arguments: (...)caller: (...)length: 0name: "value"prototype: Object__proto__: function ()apply: function apply()arguments: (...)bind: function bind()call: function call()caller: (...)constructor: function Function()length: 0name: ""toString: function toString()Symbol(Symbol.hasInstance): function [Symbol.hasInstance]()get arguments: function ThrowTypeError()set arguments: function ThrowTypeError()get caller: function ThrowTypeError()set caller: function ThrowTypeError()__proto__: Object[[FunctionLocation]]: <unknown>[[FunctionLocation]]: zone.js:734[[Scopes]]: Scopes[5]toString: function ()zoneAwareStack: (...)__zone_symbol__error: Error: Template parse errors:
> Can't bind to 'ngFor' since it isn't a known property of 'li'. ("
>   <h1>Nazwy dni tygodnia</h1>
>   <ul>
>     <li [ERROR ->]*ngFor="day of days">{{day}}</li>
>     
>   </ul>
> "): AppComponent@3:8
> Property binding ngFor not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
>   <h1>Nazwy dni tygodnia</h1>
>   <ul>
>     [ERROR ->]<li *ngFor="day of days">{{day}}</li>
>     
>   </ul>
> "): AppComponent@3:4
>     at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:87146:33)
>     at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:66363:16)
>     at new SyntaxError (http://localhost:4200/vendor.bundle.js:5941:16)
>     at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:18361:19)
>     at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:48626:68)
>     at http://localhost:4200/vendor.bundle.js:48509:62
>     at Set.forEach (native)
>     at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:48509:19)
>     at createResult (http://localhost:4200/vendor.bundle.js:48391:19)
>     at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:86577:26)
>     at Zone.run (http://localhost:4200/vendor.bundle.js:86448:43)
>     at http://localhost:4200/vendor.bundle.js:86870:57
>     at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:86610:35)
>     at Zone.runTask (http://localhost:4200/vendor.bundle.js:86486:47)
>     at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:86768:35)__zone_symbol__message: > "Template parse errors:↵Can't bind to 'ngFor' since it isn't a known property of 'li'. ("↵  <h1>Nazwy dni > tygodnia</h1>
> ↵  <ul>
> ↵    <li [ERROR ->]*ngFor="day of days">{{day}}</li>
> ↵    
> ↵  </ul>
> ↵"): AppComponent@3:8↵Property binding ngFor not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("↵  <h1>Nazwy dni tygodnia</h1>
> ↵  <ul>
> ↵    [ERROR ->]<li *ngFor="day of days">{{day}}</li>
> ↵    
> ↵  </ul>
> "): AppComponent@3:4"__zone_symbol__stack: "Error: Template parse errors:↵Can't bind to 'ngFor' since it isn't a known property of 'li'. ("↵  <h1>Nazwy dni tygodnia</h1>
> ↵  <ul>
> ↵    <li [ERROR ->]*ngFor="day of days">{{day}}</li>
> ↵    
> ↵  </ul>
> ↵"): AppComponent@3:8↵Property binding ngFor not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("↵  <h1>Nazwy dni tygodnia</h1>
> ↵  <ul>
> ↵    [ERROR ->]<li *ngFor="day of days">{{day}}</li>
> ↵    
> ↵  </ul>
> "): AppComponent@3:4↵    at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:87146:33)↵    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:66363:16)↵    at new SyntaxError (http://localhost:4200/vendor.bundle.js:5941:16)↵    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:18361:19)↵    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:48626:68)↵    at http://localhost:4200/vendor.bundle.js:48509:62↵    > at Set.forEach (native)↵    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:48509:19)↵    at createResult (http://localhost:4200/vendor.bundle.js:48391:19)↵    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:86577:26)↵    at Zone.run (http://localhost:4200/vendor.bundle.js:86448:43)↵    at http://localhost:4200/vendor.bundle.js:86870:57↵    > at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:86610:35)↵    at Zone.runTask (http://localhost:4200/vendor.bundle.js:86486:47)↵    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:86768:35)"_nativeError: ZoneAwareErrorget message: function ()set message: function (value)get name: function ()set name: function (value)get originalStack: function ()set originalStack: function (value)get stack: function ()set stack: function (value)get zoneAwareStack: function ()set zoneAwareStack: function (value)__proto__: BaseError Error: Template parse errors:
> Can't bind to 'ngFor' since it isn't a known property of 'li'. ("
>   <h1>Nazwy dni tygodnia</h1>
>   <ul>
>     <li [ERROR ->]*ngFor="day of days">{{day}}</li>
>     
>   </ul>
> "): AppComponent@3:8
> Property binding ngFor not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
>   <h1>Nazwy dni tygodnia</h1>
>   <ul>
>     [ERROR ->]<li *ngFor="day of days">{{day}}</li>
>     
>   </ul>
> "): AppComponent@3:4
>     at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:87146:33)
>     at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:66363:16)
>     at new SyntaxError (http://localhost:4200/vendor.bundle.js:5941:16)
>     at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:18361:19)
>     at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:48626:68)
>     at http://localhost:4200/vendor.bundle.js:48509:62
>     at Set.forEach (native)
>     at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:48509:19)
>     at createResult (http://localhost:4200/vendor.bundle.js:48391:19)
>     at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:86577:26)
>     at Zone.run (http://localhost:4200/vendor.bundle.js:86448:43)
>     at http://localhost:4200/vendor.bundle.js:86870:57
>     at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:86610:35)
>     at Zone.runTask (http://localhost:4200/vendor.bundle.js:86486:47)
>     at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:86768:35)
> consoleError @ zone.js:420
> _loop_1 @ zone.js:449
> drainMicroTaskQueue @ zone.js:453
> ```
>
> **error log `zone.js:422`  about of Can't bind to 'ngFor'**
>
> ```console
> zone.js:422 ZoneAwareErrormessage: (...)name: (...)originalStack: (...)promise: ZoneAwarePromiserejection: SyntaxErrorstack: (...)task: ZoneTasktoSource: function ()toString: function ()zone: ZonezoneAwareStack: (...)__zone_symbol__error: Error: Uncaught (in promise): Error: Template parse errors:
> Can't bind to 'ngFor' since it isn't a known property of 'li'. ("
>   <h1>Nazwy dni tygodnia</h1>
>   <ul>
>     <li [ERROR ->]*ngFor="day of days">{{day}}</li>
>     
>   </ul>
> "): AppComponent@3:8
> Property binding ngFor not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
>   <h1>Nazwy dni tygodnia</h1>
>   <ul>
>     [ERROR ->]<li *ngFor="day of days">{{day}}</li>
>     
>   </ul>
> "): AppComponent@3:4
> Error: Template parse errors:
> Can't bind to 'ngFor' since it isn't a known property of 'li'. ("
>   <h1>Nazwy dni tygodnia</h1>
>   <ul>
>     <li [ERROR ->]*ngFor="day of days">{{day}}</li>
>     
>   </ul>
> "): AppComponent@3:8
> Property binding ngFor not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
>   <h1>Nazwy dni tygodnia</h1>
>   <ul>
>     [ERROR ->]<li *ngFor="day of days">{{day}}</li>
>     
>   </ul>
> "): AppComponent@3:4
>     at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:87146:33)
>     at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:66363:16)
>     at new SyntaxError (http://localhost:4200/vendor.bundle.js:5941:16)
>     at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:18361:19)
>     at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:48626:68)
>     at http://localhost:4200/vendor.bundle.js:48509:62
>     at Set.forEach (native)
>     at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:48509:19)
>     at createResult (http://localhost:4200/vendor.bundle.js:48391:19)
>     at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:86577:26)
>     at Zone.run (http://localhost:4200/vendor.bundle.js:86448:43)
>     at http://localhost:4200/vendor.bundle.js:86870:57
>     at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:86610:35)
>     at Zone.runTask (http://localhost:4200/vendor.bundle.js:86486:47)
>     at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:86768:35)
>     at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:87146:33)
>     at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:66363:16)
>     at new SyntaxError (http://localhost:4200/vendor.bundle.js:5941:16)
>     at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:18361:19)
>     at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:48626:68)
>     at http://localhost:4200/vendor.bundle.js:48509:62
>     at Set.forEach (native)
>     at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:48509:19)
>     at createResult (http://localhost:4200/vendor.bundle.js:48391:19)
>     at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:86577:26)
>     at Zone.run (http://localhost:4200/vendor.bundle.js:86448:43)
>     at http://localhost:4200/vendor.bundle.js:86870:57
>     at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:86610:35)
>     at Zone.runTask (http://localhost:4200/vendor.bundle.js:86486:47)
>     at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:86768:35)
>     at resolvePromise (http://localhost:4200/vendor.bundle.js:86836:31) [<root>]
>     at resolvePromise (http://localhost:4200/vendor.bundle.js:86821:17) [<root>]
>     at http://localhost:4200/vendor.bundle.js:86870:17 [<root>]
>     at Zone.runTask (http://localhost:4200/vendor.bundle.js:86486:47) [<root> => <root>]
>     at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:86768:35) [<root>]get message: function ()set message: function (value)get name: function ()set name: function (value)get originalStack: function ()set originalStack: function (value)get stack: function ()set stack: function (value)get zoneAwareStack: function ()set zoneAwareStack: function (value)__proto__: Object
> consoleError @ zone.js:422
> _loop_1 @ zone.js:449
> drainMicroTaskQueue @ zone.js:453
> ```
> ---------------------------------------------------------------
> I'm chartered with NG2, still learning and I bought a course in which one initial lesson is to use `NgFor`  and `NgIf` elements from the module `@angular/common`, but I get this error .. please help, 
> **[My project is also online on github https://github.com/Cisowscy/Cisowscy.github.io](https://github.com/Cisowscy/Cisowscy.github.io)**
>
> Sincerely John, @CisSasGot @Cisowscy :) 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by grizzm0** [comment]
This issue is not related to angular-cli. Please use stackoverflow for questions regarding angular in the future.

You no longer need to import NgFor and it should be `*ngFor="let day of days"` (note the let keyword)

**Comment by nousacademy** [comment]
getting this same error, heres my code:

angular-cli shows no errors, but I see this error in browser

`import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-expertise',
  template: '<div *ngFor="d of expertise" class="card mb-4 box-shadow">{{d.type}}</div>',
  styleUrls: ['./expertise.component.css']
})

export class ExpertiseComponent implements OnInit{
   expertise: any[] = [
    {
      "type": "Language",
      "name": "HTML5",
      "badgeImg": "assets/img/HTML5.png"
    },
    {
      "type": "Language",
      "name": "CSS",
      "badgeImg": "df"
    },
    {
      "type": "Language",
      "name": "Javascript",
      "badgeImg": "dv"
    }
  ];

      ngOnInit() { }
}`
