### ISSUE TITLE
ng new creates project in home directory instead of the current directory

### ISSUE THREAD

**Issue by lestard** [angular/angular-cli#4186]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux Mint 17.3 (based on Ubuntu 14.04)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.26
node: 7.0.0
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

`cd ~/some/subdirectory/of/home`
`ng new testproject`

### The log given by the failure.
> Normally this include a stack trace and some more information.

No error messages. The CLI prints `Project 'testproject' successfully created.`

### Mention any other details that might be useful.

Expected behavior: The project is created in a subdirectory of the current directory, for instance `~/some/subdirectory/of/home/testproject`.

Actual behavior: The project is created directly in the home directory under `~/testproject`. The current directory is empty.

**Comment by hansl** [comment]
You have a rogue `node_modules` in your home directory. Delete it and it should work again.

**Comment by lestard** [comment]
Hi, thanks for the quick response. I had a `node_modules` in my home directory. However, even after deleting it the problem still exists. New projects are still created in the home directory.

**Comment by filipesilva** [comment]
@lestard you should also have a rogue `package.json` in your home directory. Deleting that should fully take care of the problem.

**Comment by lestard** [comment]
Thanks you. Now it works. 
Where does this behavior comes from? Is this a "bug" or is this the desired behavior - and if this is the case, why?
