### ISSUE TITLE
Nested route generation

### ISSUE THREAD

**Issue by amindunited** [angular/angular-cli#419]
Generating a route using:

       ng g route admin/group

results in a doubling of file path names:

        src/client/app/admin/group/admin/group.service.ts
instead of:

       src/client/app/admin/group/group.service.ts

happens on:
angular-cli: 0.0.30
node: 4.1.2
os: darwin x64

**Comment by Brocco** [comment]
@amindunited we are in the process of refactoring the route generations and that work can be tracked under issue #316.

Closing this issue in favor of the mentioned issue.
