### ISSUE TITLE
Are there any plans to publish @ngtools as a standalone package

### ISSUE THREAD

**Issue by maximusk** [angular/angular-cli#4194]
We have a large platform that allows other parties to build applications on top of the platform. To correctly build and plug-in these application we need to configure webpack's `externals`  and `output.library` options. Based on [this discussion](https://github.com/angular/angular-cli/issues/1656), it seems that this option will not be provided by the angular-cli in the near future. Also, support for libraries (apps without angular source code) is also [not the near term option](https://github.com/angular/angular-cli/issues/1692).

So we decided to go without angular-cli, but I've noticed that angular-cli  1.0.0-beta.25.5
doesn't use popular loaders, like `awesome-typescript-loader` and `angular-router-loader`, but rather has something else implemented internally inside `@ngtools/webpack`. For example, `class TypeScriptFileRefactor` that transpiles typescript. My question is are there any plans to publish these tools as standalone package that can we can use outside of angular-cli?

**Comment by filipesilva** [comment]
It is currently published actually:

```
$ npm info @ngtools/webpack dist-tags
{ latest: '1.2.4' }
```

Check out https://github.com/angular/angular-cli/tree/master/packages/%40ngtools/webpack for more info.
