### ISSUE TITLE
component's template not showing when building with --prod

### ISSUE THREAD

**Issue by fursad** [angular/angular-cli#4203]
> Please provide us with the following information:
I know this bug has been closed for a long time ago, but I am experiencing this again. When I build my angular2 application with --prod target, the angular2 templates in my components are not working. 
I updated my webpack-build-production.js file with **mangle: { screw_ie8: true, keep_fnames: true }**, then it works again. 

Is this a bug? if so, hope you can fix it soon

### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.26
node: 6.9.1
os: win32 x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

### Repro steps.
build the application with --prod target

### The log given by the failure.
No failure, Angular2 template are not rendering

### Mention any other details that might be useful.
I updated my webpack-build-production.js file with following:

mangle: { screw_ie8: true, keep_fnames: true },

Then its work.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I can't repro this myself on a new app. Can you make a minimum repro that I could follow to see this happen? If I had to bet, it's related to some third party lib you're using that absolutely needs the function names.

**Comment by hansl** [comment]
Closing this. We need a reproducible project.
