### ISSUE TITLE
environment.production valuable not available outside of main.ts

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#4205]
### OS?
Mac OSX (El Capitan)

### Versions.
```
angular-cli: 1.0.0-beta.25.5
node: 6.3.1
os: darwin x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1
```

### Repro steps.
When accessing `environment.production` from `./environments/environment` in `app.module` in `src/app` the value returns `false` even if `--prod` is set.  However within `main.ts` `environment.production` returns `true` from the same import. 

### Expectation
`environment.production` should return the same value everywhere.

**Comment by Meligy** [comment]
That would explain some of the comments in https://github.com/angular/angular-cli/issues/933 especially https://github.com/angular/angular-cli/issues/933#issuecomment-260913566, that's assuming it's an old issue.

**Comment by deebloo** [comment]
can you post your app.module and main.ts?

**Comment by filipesilva** [comment]
I couldn't repro it myself:
![image](https://cloud.githubusercontent.com/assets/4172079/22252084/f98ac42a-e244-11e6-83fd-46f9104e5301.png)

Maybe there's more to it, but I'm going to need a repro to investigate.

**Comment by zackarychapple** [comment]
Closing this issue.  It was due to migration and changing of locations of the environment variables.  Non issue.
