### ISSUE TITLE
Upgrading to Angular 2 with Angular CLI

### ISSUE THREAD

**Issue by bedag-moo** [angular/angular-cli#4210]
We are looking into incrementally upgrading an angular 1 app to angular 2 using the UpgradeModule. We'd like to use Angular CLI, not the least because it configures Webpack for us. However, we need to extend the webpack config so we can build our legacy code until it has all been migrated.

Could you provide a way to extend (or, in the case of node shims, modify) the webpack config generated by angular-cli?

**Comment by clydin** [comment]
Webpack is considered an internal implementation detail. It is recommended that a CLI based app not assume the presence or use of webpack.

**Comment by hansl** [comment]
What @clydin said, basically. We do not want to expose the webpack config as the user should not have to manage his build. You can always create a webpack configuration yourself (and the webpack plugin managed by the CLI team).

**Comment by bedag-moo** [comment]
Well, if you want to manage my project's legacy build for me, you are most certainly welcome :-)

On a more serious note, I'd prefer reusing the CLI's webpack config to forking it, so I automatically get your changes and improvements for the angular 2 part, and can smoothly transition to the CLI once the migration is complete.
