### ISSUE TITLE
Add build number to index.html / main.ts #FeatureRequest

### ISSUE THREAD

**Issue by manuelfink** [angular/angular-cli#4213]
Is it anyhow possible to add a build number / current git hash / version number / timestamp to index.html / main.ts while building and increment it with every build?

**Comment by deebloo** [comment]
@manuelfink as far as I know there isn't a way out of the box, but wouldn't be something to difficult to add as your own step after the fact. There are also plans for a post 1.0 plugin system that would be a good fit for this type of feature

**Comment by filipesilva** [comment]
There are no plans for this sort of functionality. My advice would be to add in a script that does it.
