### ISSUE TITLE
refusing import @vimeo/player

### ISSUE THREAD

**Issue by macliems** [angular/angular-cli#4214]
Importing the vimeo player (import Player from '@vimeo/player') fails with error Cannot find module '@vimeo/player'.

Problem with scoped packages?

Mac OSX
angular-cli: 1.0.0-beta.25.5
node: 6.4.0
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

**Comment by clydin** [comment]
All of angular's packages are scoped.

It looks like `@vimeo/player` does not include type definitions.  Have you installed them separately?

**Comment by macliems** [comment]
Yes, I installed: npm install --save-dev @types/vimeo

but no go ...

**Comment by clydin** [comment]
In that case, only thing I can suggest is open an issue in regards to typescript support with the package owner.

**Comment by macliems** [comment]
I did, and I got the advise to open an issue on angular-cli ;)

**Comment by clydin** [comment]
You can also define the module and associated types in your app directly.  I think typescript has a guide.

**Comment by pusherman** [comment]
could also try manually creating one as explained in https://github.com/angular/angular-cli#3rd-party-library-installation

**Comment by macliems** [comment]
Thanks,

I tried it exactly as it says there, but no, still 'cannot find module'

**Comment by hansl** [comment]
do you have an example project that we can look at?

**Comment by hansl** [comment]
Also, seems like `@vimeo/player` is missing typings. You can `require()` instead of `import`, but you won't get typing informations. You need to contact them to add typings to their packages.

Closing this as there's nothing we can do.

**Comment by macliems** [comment]
Thank you,

I found the Vimeo typings (there appear to be 2 github repos, one of the
player itself, and one of just the typings, which are not mentioned in the
first: not very helpful!).
