### ISSUE TITLE
Multiple app defintions in the angular-cli.json "apps" : [ ] property

### ISSUE THREAD

**Issue by benwinding** [angular/angular-cli#4215]
## Multiple app definitions

I noticed that inside the `angular-cli.json` file, the `"apps":` property is defined as an array. Is the following a valid example of the intended use for this property?

**angular-cli.json  :**
```
{
  "project": {
    "version": "1.0.0-beta.26",
    "name": "example1"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      ...
    }, 
    {
      "root": "src2",
      "outDir": "dist2",
      ...
    }
  ],
  ...
}
```

I've tested with multiple definitions in the **"apps":** property. And `ng build` always builds the first app defintiion.

If all these assumptions are correct, How do you use `ng build` to compile the second app definition? 

## Current Config.

angular-cli: 1.0.0-beta.26
node: 6.5.0
os: win32 x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

**Comment by clydin** [comment]
That is the intended future use.  However, only one app is currently supported.

**Comment by filipesilva** [comment]
Closing as answered by @clydin.

**Comment by sarathdr** [comment]
Is there a timeline for this? Could you suggest a workaround until then?

**Comment by leocaseiro** [comment]
Check https://github.com/sumitarora/angular-cli/blob/8eacff23dee2ea9b9c29d9733dac3759133f5609/docs/documentation/stories/multiple-apps.md

**Comment by benwinding** [comment]
Thanks, that looks great Leo!
