### ISSUE TITLE
Proposal: Stop `ng new` going up one directory in search for package.json

### ISSUE THREAD

**Issue by gotofritz** [angular/angular-cli#4216]
Hi. I have also got bitten by https://github.com/angular/angular-cli/issues/1079 (summary: if you do `ng new xxx` in an empty folder, and the _parent_ folder has a package.json, the new project will be created in the parent folder). 

I fail to see a realistic user case where one may need that. It causes only confusion (if you look at the original bug it has already 5 duplicates, showing that it is a common enough problem). And as far as I can see, `new` doesn't actually fetch any information from the package.json, so I'm at a loss to explain why it is actually looking for it. I think it all stems from the `packageJson` var in ng, https://github.com/angular/angular-cli/blob/224250c113543f9828bd5fe27169cc92f7ed74e6/packages/angular-cli/bin/ng#L8 but I think `ng new` should disregard it since not relevant in that case.

**Comment by SanderElias** [comment]
I agree that looking for a package.json does _not_ make sense for ng new. If you have a package.json somewhere up the tree, that does not mean you intend to create the new project there. Usually, you intend to create a new project right where you are.

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/4901
