### ISSUE TITLE
Component styles are not added to the style.bundle.css

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [angular/angular-cli#4217]
### OS?
Mac OSX (El Capitan)

### Versions.
angular-cli: 1.0.0-beta.26
node: 7.4.0
os: darwin x64

### Repro steps.
- I've build a new project with the cli: ng new myproject
- added a new component with the cli: ng g component mycomp
- Included the new component in the standard mycomp.component.html
- Made a change to the mycomp.component.css
- build the project: ng build

### The log given by the failure.
no error, all green output.

### Mention any other details that might be useful.
The css files i'm explicitly referencing in the angular-cli.json are being added to the style.bundle.css.
I'm actually using scss but for simplification I've tested with plain css.

**Comment by filipesilva** [comment]
That's intended actually. Global styles go in the style bundle, while component styles go in main.

**Comment by tobi-or-not-tobi** [comment]
@filipesilva fair enough, however there is no main style bundle generated. I've updated the description accordingly.

**Comment by grizzm0** [comment]
It's part of your application and main.bundle.js.

**Comment by filipesilva** [comment]
@tobi-or-not-tobi  there shouldn't be one generated, it is by design.
