### ISSUE TITLE
Fail when compiling project with custom paths (wrong location for tsconfig.json)

### ISSUE THREAD

**Issue by elgibit** [angular/angular-cli#4218]
### OS?
MacOS Sierra

### Versions.
angular-cli: 1.0.0-beta.26
node: 7.4.0
os: darwin x64
angular/*: 2.4.4

### Repro steps.
just use `ng new` to create a project and add paths into `tsconfig.json` like:
```
  "baseUrl": ".",
  "paths": {
      "@app-root/*": ["src/app/*"],
      "@app-core/*": ["src/app/core/*"],
      "@app-shared/*": ["src/app/shared/*"],
      "@app-features/*": ["src/app/features/*"]
```

Create some sample feature module like home.module

### The log given by the failure.
ng serve failed at compiling project (same for --aot and for running test)
```
ERROR in ./src/app/app.module.ts
Module build failed: Error: /Users/***/test/src/app/app.module.ts (7,28): Cannot find module '@app-features/home/home.module'.)
    at _checkDiagnostics (/Users/***/test/node_modules/@ngtools/webpack/src/loader.js:145:15)
    at /Users/***/test/node_modules/@ngtools/webpack/src/loader.js:172:17
 @ ./src/$$_gendir/app/app.module.ngfactory.ts 13:0-48
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
```

### Mention any other details that might be useful.
I think the problem is place where tsconfig.json is located (currently `/src/tsconfig.json`). Also it is hard for IDEs to recognize/adapt changes inside tsconfig.json since he's not in the projects root (mentioned paths were not recognized by Visual Studio Code).
When I moved it into project root folder and edited angular-cli.json file with
```
"tsconfig": "../tsconfig.json"
```
everything works fine.

**Comment by beeman** [comment]
@elgibit I think you might need to leave out the `src` part from the paths in your `paths` key.

**Comment by elgibit** [comment]
@beeman You're right! Thanks 🥇 
I didn't catch that, also VSC is reacting to it correctly.

**Comment by beeman** [comment]
Awesome! Thanks for the gold @elgibit 😎
