### ISSUE TITLE
ng serve makes OS very slow 

### ISSUE THREAD

**Issue by amineparis** [angular/angular-cli#4228]
After minutes of running ng serve ubuntu start getting very slow

**output of df command showing /dev/loop full**

> Filesystem     1K-blocks     Used Available Use% Mounted on
udev             1951244        0   1951244   0% /dev
tmpfs             394276     6484    387792   2% /run
/dev/sda1      957277844 22956360 885671552   3% /
tmpfs            1971376   350356   1621020  18% /dev/shm
tmpfs               5120        4      5116   1% /run/lock
tmpfs            1971376        0   1971376   0% /sys/fs/cgroup
/dev/loop0         76416    76416         0 100% /snap/core/641
/dev/loop2         36224    36224         0 100% /snap/postgresql96/6
/dev/loop1         77952    77952         0 100% /snap/core/714
tmpfs             394276       48    394228   1% /run/user/1000

**Comment by beeman** [comment]
@youneschaoui can you please provide all the details that are requested when opening an issue?

**Comment by filipesilva** [comment]
We really do need the information in the issue template to be able to help :/

**Comment by youneschaoui** [comment]
# OS
Ubuntu 16.04 
# node -- version
v7.4.0
# ng --version
angular-cli: 1.0.0-beta.26
node: 7.4.0
os: linux x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
