### ISSUE TITLE
ng new [project-name] - length out of bounds error

### ISSUE THREAD

**Issue by NathanWalker** [angular/angular-cli#4229]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OS X Sierra `10.12.2`

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

`1.0.0-beta.26`
node: `6.9.1`
npm: `3.10.9`

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

`ng new my-project-name`

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
installing ng2
  create .editorconfig
  create README.md
  create src/app/app.component.css
  create src/app/app.component.html
  create src/app/app.component.spec.ts
  create src/app/app.component.ts
  create src/app/app.module.ts
  create src/assets/.gitkeep
  create src/environments/environment.prod.ts
  create src/environments/environment.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/polyfills.ts
  create src/styles.css
  create src/test.ts
  create src/tsconfig.json
  create angular-cli.json
  create e2e/app.e2e-spec.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tslint.json
Successfully initialized git.
Installing packages for tooling via npm.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/nathan/.nvm/versions/node/v6.9.1/bin/node" "/Users/nathan/.nvm/versions/node/v6.9.1/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9

npm ERR! length out of bounds
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Meligy** [comment]
That looks like an `npm install`. It might be a network issue, or might be an NPM issue.

You can try to clean `node_modules` if it was created and run `npm install` again.

Also, I see you are using `nvm`. Maybe try reinstalling the angular CLI after the nvm switching to the version you want. Like:

```
npm rm -g angular-cli
npm cache clear
npm i -g angular-cli
```

I don't recall any specific nvm+angular-cli issues recently, but it could well be something going wrong in your nvm installation.

**Comment by filipesilva** [comment]
You seem to have a problem during your npm install like @Meligy said.

My best advise to get better information on it is to generate a project without automatically doing `npm install`, then doing it manually:
```
ng new project-name --skip-npm
cd project-name
npm install
```

If it's a network thing, you should be fine just doing it again. If not, you'll have to debug what's wrong with your `npm` :/
