### ISSUE TITLE
Import component in app Component

### ISSUE THREAD

**Issue by GuillaumeUnice** [angular/angular-cli#423]
Hi every,

I install angular-cli and i create a new project. All it's right but when I begin to add a component I juste make :  
`ng g component myComponent`

First bug : spec file generated import : 
`import {MyComponent} from './my-component'; `
instead of
`import {MyComponent} from './myComponent';`

Then, I juste want to import myComponent in app Component so I write in my app Component ts : 
`import {MyComponent} from './myComponent/myComponent';`

and in @Component I add : 
`directives: [ROUTER_DIRECTIVES, MyComponent]`

And in app Component template html I add :
`<my-component></my-component>`

That compile there is no error but app Component HTML tag it's not interpreted so I have just : "loading..."

So, could you explain me how import a component in app Component?

Thanks a lot :D

**Comment by Brocco** [comment]
Please you take a look in the browser's console for errors to share then and report the version of the CLI you're using

**Comment by GuillaumeUnice** [comment]
In fact the problem was what I have mentionned the camelCase rules in not respect all 
this issue is the same : #424 

Thanks a lot
