### ISSUE TITLE
Cann

### ISSUE THREAD

**Issue by deecm22** [angular/angular-cli#4230]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
MacOS Sierra: 10.12.2 (16C67)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
Running this command yields the following results:

" __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.25.5
node: 6.9.1
os: darwin x64
@angular/common: 2.2.1
@angular/compiler: 2.2.1
@angular/core: 2.2.1
@angular/forms: 2.2.1
@angular/http: 2.2.1
@angular/platform-browser: 2.2.1
@angular/platform-browser-dynamic: 2.2.1
@angular/router: 3.2.1
@angular/compiler-cli: 2.2.1
Christophers-MacBook-Air:App Dev deecm22$ "

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
I simply ran the command "ng new test"

### The log given by the failure.
> Normally this include a stack trace and some more information.

The error message was "You cannot use the new command inside an angular-cli project."

There was no stack trace.

### Mention any other details that might be useful.
I have had this problem consistently on my Mac even with the previous version of the cli tool.  
I do not have this issue on my Windows 10 box.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@deecm22 your issue is most likely because of an existing `node_modules ` directory in one of your parent directories. See here: https://github.com/angular/angular-cli/issues/2818#issuecomment-257964822

**Comment by hansl** [comment]
Closing this unless @deecm22 provides more information, considering this solved from @beeman comments.
