### ISSUE TITLE
cannot install on macbook

### ISSUE THREAD

**Issue by bobugeorgep** [angular/angular-cli#4231]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX (Yosemite)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
Bobus-MBP:~ dolphin$ ng --version
-bash: ng: command not found
Bobus-MBP:~ dolphin$ node --version
v7.4.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@bobugeorgep did you install angular-cli globally? `npm install -g angular-cli@latest` ? If you do this, what's the output?

**Comment by bobugeorgep** [comment]
Bobus-MBP:~ dolphin$ npm install -g angular-cli@latest
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli@latest"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Invalid name: "@angular-cli/ast-tools"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dolphin/npm-debug.log

**Comment by beeman** [comment]
It might be an issue with the permissions of npm on your system. Can you try the first option here?

https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-1-change-the-permission-to-npms-default-directory

If that does not work, can you add the file `/Users/dolphin/npm-debug.log` to this issue?

**Comment by bobugeorgep** [comment]
Bobus-MBP:~ dolphin$ sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
Password:
Bobus-MBP:~ dolphin$ npm install -g angular-cli@latest
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli@latest"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Invalid name: "@angular-cli/base-href-webpack"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dolphin/npm-debug.log
Bobus-MBP:~ dolphin$

**Comment by beeman** [comment]
`If that does not work, can you add the file /Users/dolphin/npm-debug.log to this issue?`

**Comment by beeman** [comment]
Also, this looks similar: https://github.com/angular/angular-cli/issues/2187#issuecomment-252432022

**Comment by bobugeorgep** [comment]
[npm-debug.txt](https://github.com/angular/angular-cli/files/730877/npm-debug.txt)

**Comment by bobugeorgep** [comment]
Yes the #2187 did good

**Comment by bobugeorgep** [comment]
Closing... #2187 worked...

**Comment by MartychDenys** [comment]
Hello, I have a problem wi
<img width="1365" alt="screen shot 2018-03-01 at 2 23 25 pm" src="https://user-images.githubusercontent.com/33865751/36844996-93092430-1d5d-11e8-81aa-ceff8d41f969.png">
th installation angular/cli on my MacBook.   Can u help me?

**Comment by beeman** [comment]
@MartychDenys it looks like there is something wrong with the npm permissions that prevent you from installing packages globally.

You can refer to this document to fix it: https://docs.npmjs.com/getting-started/fixing-npm-permissions
