### ISSUE TITLE
"Project name "try-25" is not valid. New project names must start with a letter, and must contain only alphanumeric characters or dashes."

### ISSUE THREAD

**Issue by JanStureNielsen** [angular/angular-cli#4232]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux openSUSE 13.2

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
jan@linux-zd16:~/src/fm-repos/fm-ui> ng --version

                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.25.5
node: 6.9.1
os: linux x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/material: 2.0.0-beta.1
@angular/compiler-cli: 2.4.4
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

`ng new try-25`

Brand new project with the name `try-25` which complies with the project name restrictions mentioned in the error message. So, either the error message is wrong, or there's a bug.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@JanStureNielsen the message is wrong and a fix is in place, that will be in the next release.

That being said, we're discussing wether or not we allow a name like this, and today I accidentally found a way around this check:

```
mkdir try-25
ng init
```

This will leave you with the project in the name you want it. Please note, this is not supported nor well-tested, it just occurred to me that it can be created this way.

**Comment by JanStureNielsen** [comment]
Ahh, sorry, @beeman -- should have searched first. 

Duplicate of #3816.
