### ISSUE TITLE
rollup problem with rxjs

### ISSUE THREAD

**Issue by feof** [angular/angular-cli#4240]
Hi, 
i use angular-cli@1.0.0-beta.26, in mac Sierra.

I am following the angular official guide for the compilation aot.
I have a problem with a rollup. This is my configuration file

import rollup      from 'rollup'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs    from 'rollup-plugin-commonjs';
import uglify      from 'rollup-plugin-uglify'

export default {
  entry: 'main.js',
  dest: 'dist/build.js',
  sourceMap: true,
  sourceMapFile: 'aot/dist/build.js.map',
  format: 'iife',
  plugins: [
    nodeResolve({jsnext: true, module: true}),
    commonjs({
      include: 'node_modules/**'
    }),
    uglify()
  ]
}

I always get the same error:
🚨   'Subject' is not exported by ../node_modules/rxjs/Subject.js

I also tried:
include: 'node_modules/rxjs/**',
namedExports: {
  'node_modules/rxjs/Subject.js': [ 'Subject' ]
}
but it does not work.
Help me, please!

(
angular-cli: 1.0.0-beta.26
node: 7.2.0
os: darwin x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/compiler-cli: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/platform-server: 2.4.4
@angular/router: 3.4.4
)

**Comment by deebloo** [comment]
@feof the cli will handle AOT compilation for you. ```ng build --aot --prod``` for production builds

**Comment by feof** [comment]
ok, but if you have ideas you would like to understand the problem

**Comment by deebloo** [comment]
@feof since rollup isn't used by the cli this may be a better question for stackoverflow since it isn't an issue with the cli itself

**Comment by filipesilva** [comment]
Heya @feof, the guide you are reading is meant to be used with the Official Quickstart (https://github.com/angular/quickstart), and not with the CLI.

The way to build projects with the CLI is using `ng build`. The flags @deebloo mentioned should give you a pretty good prod build.
