### ISSUE TITLE
Support for scaffolding angular libraries

### ISSUE THREAD

**Issue by oliverjanik** [angular/angular-cli#4247]
Say, I want to create a reusable datepicker and package it for consumption for angular2 app. What options do I have today? As an example angular2-material has an incredibly complex gulp based process.

After build and publish, such a library would be readily usable by just issuing `npm install my-datepicker` for both JIT and AOT angular 2 apps.

Please provide a **canonical** way to author Angular2 libs and components. I strongly believe this is important for the ecosystem to flourish.

**Comment by oliverjanik** [comment]
Found a dupe #1692.

**Comment by beeman** [comment]
@oliverjanik I agree that it would be an awesome addition to the cli, sadly it's not going to be there before the v1 release, and it's not yet clear when it will be there.

Some ways to get you started might be these starters: 

https://github.com/preboot/angular-library-seed
https://github.com/beeman/generator-ngx-module

and reading through these blogs:

http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/
https://medium.com/@cyrilletuzi/how-to-build-and-publish-an-angular-module-7ad19c0b4464#.9y88ipdk7
