### ISSUE TITLE
Feature: ng serve build and watch only

### ISSUE THREAD

**Issue by papaiatis** [angular/angular-cli#4254]
I'm hosting my website with apache (backend is written in Perl). I configured the cli to output the compiled/built files to the apache www folder.
I'd like to use "ng serve" (or another command) to continuously watch my files and run the build if there were changes. "ng serve" would do, but I don't need to host my website on any port, apache does it for me.

**Comment by filipesilva** [comment]
`ng build --watch` should do it for you.

**Comment by papaiatis** [comment]
It's not doing it. Doesn't capture when I change the files.
System: latest Gentoo with Gnome 3.2
Latest angular-cli, latest npm, latest node.

**Comment by filipesilva** [comment]
Eh that's weird. So `ng serve` captures the file changes, but `ng build --watch` doesn't?

**Comment by papaiatis** [comment]
Sorry, ng serve doesn't capture either. :\

**Comment by papaiatis** [comment]
That's all it says:

```
$ ng build --watch
Hash: e1fda1b06970e21f1e6e
Time: 11412ms
chunk    {0} main.bundle.js, main.bundle.map (main) 24.4 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 177 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.92 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
```

**Comment by filipesilva** [comment]
Ok then that's a different issue... One I don't have an answer to off the top of my head.

The answer to this issue is `ng build --watch`, but there seems to be something stopping the file watchers from working in your setup. Can you open a new issue for this?

We have a somewhat obscure poll option but it only works for `ng serve`, so it's no good for your case.
