### ISSUE TITLE
Uncaught reflect-metadata shim is required when using class decorators

### ISSUE THREAD

**Issue by CarreraPHP** [angular/angular-cli#4257]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Mac OS Sierra

### Versions.
```
                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.26
node: 6.2.2
os: darwin x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
```

### Repro steps.
run `ng new appname --routing` and then `ng build --prod` or `ng serve`. Above error is show within the browser console.

### The log given by the failure.
No error at console

**Comment by CarreraPHP** [comment]
Works fine

**Comment by mikeumus** [comment]
@CarreraPHP, how did it start working fine for you? I'm getting this error now after upgrading to cli v1.0
