### ISSUE TITLE
Can I convert my existing angular2 project to angular-cli project?

### ISSUE THREAD

**Issue by nitishkumarnitc** [angular/angular-cli#4263]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by intellix** [comment]
Issue tracker isn't for general questions :) You can ask away at: http://stackoverflow.com/
I'd suggest you generate a new project with `ng new something` and then shove your code into the source directory. The CLI doesn't really generate much boilerplate so it should be fairly easy to see what you need there.

**Comment by filipesilva** [comment]
Heya @nitishkumarnitc, you can yes. We'll be documenting the steps in https://github.com/angular/angular-cli/issues/3198. 

Meanwhile, @intellix's advice is solid.

**Comment by kartikgreen** [comment]
Hey @filipesilva  Did you already document the steps? Can you please share me the link?

**Comment by rtdp** [comment]
@kartikgreen https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/moving-into-the-cli.md
