### ISSUE TITLE
Passing options (not includePaths) to sass compiler

### ISSUE THREAD

**Issue by altschuler** [angular/angular-cli#4272]
Is there a way to add options to the sass compiler, besides `includePaths` (introduced in beta.26)? I need to add `browsers: ["> 2%", "last 3 versions", "last 5 iOS versions"]` to the compiler options.

Thanks!

**Comment by clydin** [comment]
Those settings are used with autoprefixer.  You can use a browser list file to set those options.  For further details see here: https://github.com/ai/browserslist/blob/master/README.md

**Comment by altschuler** [comment]
That solves it, thanks!
