### ISSUE TITLE
ng github-pages:deploy. Command does not work out of the box. 

### ISSUE THREAD

**Issue by NikiforovAll** [angular/angular-cli#4277]
### Description 
I tried to publish angular 2 project and encountered that bundled files are not loaded. The project is in a sub-folder and the base URL is specified manually (e.g  base href=/[repository-name]/[sub-folder] ). Is there way to customize how do I refer project dependencies so I can host angular project entirely on gh-pages without manually changing index.html?  

Thanks!

### OS?
Release:	16.04
### Versions.
angular-cli: 1.0.0-beta.26
### Repro steps.
ng github-pages:deploy 
### The log given by the failure.
Request: https://nikiforovall.github.io/IMEMium/imem/
Log:
nikiforovall.github.io/:13 GET https://nikiforovall.github.io/imem/styles.bundle.css 
nikiforovall.github.io/:16 GET https://nikiforovall.github.io/imem/scripts.bundle.js 
nikiforovall.github.io/:16 GET https://nikiforovall.github.io/imem/inline.bundle.js 
nikiforovall.github.io/:16 GET https://nikiforovall.github.io/imem/main.bundle.js 
nikiforovall.github.io/:16 GET https://nikiforovall.github.io/imem/scripts.bundle.js 
nikiforovall.github.io/:16 GET https://nikiforovall.github.io/imem/main.bundle.js

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
