### ISSUE TITLE
ng serve taking  Time: 51013ms could be due to limited system resources memory 3,1GIB 84,4% of  3,6GIB i'm getting new linux and android hardware next week, i need to buy new hardware for personal usage, or install a lighter weight linux distribution, like zorin lite ... there are many awesome light weight linux distributions to select: lubuntu, remixOS, debian , it's all a question of time ... https://www.linux.com/news/best-lightweight-linux-distros-2017

### ISSUE THREAD

**Issue by NilsHolger** [angular/angular-cli#4279]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
zorin OS 12 running on ubuntu 16.04.1 LTS os: linux x64

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

ANGULAR-CLI: 1.0.0-beta.26
node: 7.4.0
os: linux x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

how can i get v 4?
### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

created with CLI. just added a bunch of components. she wants a bunch. :)

### The log given by the failure.
> Normally this include a stack trace and some more information.
...
 65% building modules 945/1030 modules 85 active ...odules/webpack/buildin/amd-o 65% building modules 946/1030 modules 84 active ...odules/webpack/buildin/amd-o 65% building modules 947/1030 modules 83 active ...odules/webpack/buildin/amd-o 65% building modules 948/1030 modules 82 active ...odules/webpack/buildin/amd-o 65% building modules 949/1030 modules 81 active ...odules/webpack/buildin/amd-o 65% building modules 950/1030 modules 80 active ...odules/webpack/buildin/amd-o 65% building modules 951/1030 modules 79 active ...odules/webpack/buildin/amd-o 65% building modules 952/1030 modules 78 active ...odules/webpack/buildin/amd-o 65% building modules 953/1030 modules 77 active ...odules/webpack/buildin/amd-o 65% building modules 954/1030 modules 76 active ...odules/webpack/buildin/amd-o 65% building modules 955/1030 modules 75 active ...odules/webpack/buildin/amd-o 65% building modules 956/1030 modules 74 active ...odules/webpack/buildin/amd-o 65% building modules 957/1030 modules 73 active ...odules/webpack/buildin/amd-o 65% building modules 958/1030 modules 72 active ...odules/webpack/buildin/amd-o 65% building modules 959/1030 modules 71 active ...odules/webpack/buildin/amd-o 65% building modules 960/1030 modules 70 active ...odules/webpack/buildin/amd-o 65% building modules 961/1030 modules 69 active ...odules/webpack/buildin/amd-o 66% building modules 962/1030 modules 68 active ...odules/webpack/buildin/amd-o 66% building modules 963/1030 modules 67 active ...odules/webpack/buildin/amd-o 66% building modules 964/1030 modules 66 active ...odules/webpack/buildin/amd-o 66% building modules 965/1030 modules 65 active ...odules/webpack/buildin/amd-o 66% building modules 966/1030 modules 64 active ...odules/webpack/buildin/amd-o 66% building modules 967/1030 modules 63 active ...odules/webpack/buildin/amd-o 66% building modules 968/1030 modules 62 active ...odules/webpack/buildin/amd-o 66% building modules 969/1030 modules 61 active ...odules/webpack/buildin/amd-o 66% building modules 970/1030 modules 60 active ...odules/webpack/buildin/amd-o 66% building modules 971/1030 modules 59 active ...odules/webpack/buildin/amd-o 66% building modules 972/1030 modules 58 active ...odules/webpack/buildin/amd-o 66% building modules 973/1030 modules 57 active ...odules/webpack/buildin/amd-o 66% building modules 974/1030 modules 56 active ...odules/webpack/buildin/amd-o 66% building modules 975/1030 modules 55 active ...odules/webpack/buildin/amd-o 66% building modules 976/1030 modules 54 active ...odules/webpack/buildin/amd-o 66% building modules 977/1030 modules 53 active ...odules/webpack/buildin/amd-o 66% building modules 978/1030 modules 52 active ...odules/webpack/buildin/amd-o 67% building modules 979/1030 modules 51 active ...odules/webpack/buildin/amd-o 66% building modules 979/1031 modules 52 active .../lib/transport/lib/buffered- 66% building modules 979/1032 modules 53 active ...s-client/lib/transport/lib/p 66% building modules 980/1032 modules 52 active ...s-client/lib/transport/lib/p 67% building modules 981/1032 modules 51 active ...s-client/lib/transport/lib/p 67% building modules 982/1032 modules 50 active ...s-client/lib/transport/lib/p 67% building modules 983/1032 modules 49 active ...s-client/lib/transport/lib/p 67% building modules 984/1032 modules 48 active ...s-client/lib/transport/lib/p 67% building modules 985/1032 modules 47 active ...s-client/lib/transport/lib/p 67% building modules 986/1032 modules 46 active ...s-client/lib/transport/lib/p 67% building modules 987/1032 modules 45 active ...s-client/lib/transport/lib/p 67% building modules 988/1032 modules 44 active ...s-client/lib/transport/lib/p 67% building modules 989/1032 modules 43 active ...s-client/lib/transport/lib/p 67% building modules 990/1032 modules 42 active ...s-client/lib/transport/lib/p 67% building modules 991/1032 modules 41 active ...s-client/lib/transport/lib/p 67% building modules 992/1032 modules 40 active ...s-client/lib/transport/lib/p 67% building modules 993/1032 modules 39 active ...s-client/lib/transport/lib/p 67% building modules 994/1032 modules 38 active ...s-client/lib/transport/lib/p 67% building modules 995/1032 modules 37 active ...s-client/lib/transport/lib/p 67% building modules 996/1032 modules 36 active ...s-client/lib/transport/lib/p 67% building modules 997/1032 modules 35 active ...s-client/lib/transport/lib/p 68% building modules 998/1032 modules 34 active ...s-client/lib/transport/lib/p 68% building modules 999/1032 modules 33 active ...s-client/lib/transport/lib/p 68% building modules 1000/1032 modules 32 active ...s-client/lib/transport/lib/ 68% building modules 1001/1032 modules 31 active ...s-client/lib/transport/lib/ 68% building modules 1002/1032 modules 30 active ...s-client/lib/transport/lib/ 68% building modules 1003/1032 modules 29 active ...s-client/lib/transport/lib/ 68% building modules 1004/1032 modules 28 active ...s-client/lib/transport/lib/ 68% building modules 1005/1032 modules 27 active ...s-client/lib/transport/lib/ 68% building modules 1006/1032 modules 26 active ...s-client/lib/transport/lib/ 68% building modules 1007/1032 modules 25 active ...s-client/lib/transport/lib/ 68% building modules 1008/1032 modules 24 active ...s-client/lib/transport/lib/ 68% building modules 1009/1032 modules 23 active ...s-client/lib/transport/lib/ 68% building modules 1010/1032 modules 22 active ...s-client/lib/transport/lib/ 68% building modules 1011/1032 modules 21 active ...s-client/lib/transport/lib/ 68% building modules 1012/1032 modules 20 active ...s-client/lib/transport/lib/ 68% building modules 1013/1032 modules 19 active ...s-client/lib/transport/lib/ 68% building modules 1014/1032 modules 18 active ...s-client/lib/transport/lib/ 69% building modules 1015/1032 modules 17 active ...s-client/lib/transport/lib/ 69% building modules 1016/1032 modules 16 active ...s-client/lib/transport/lib/ 69% building modules 1017/1032 modules 15 active ...s-client/lib/transport/lib/ 69% building modules 1018/1032 modules 14 active ...s-client/lib/transport/lib/ 69% building modules 1019/1032 modules 13 active ...s-client/lib/transport/lib/ 69% building modules 1020/1032 modules 12 active ...s-client/lib/transport/lib/ 69% building modules 1021/1032 modules 11 active ...s-client/lib/transport/lib/ 69% building modules 1022/1032 modules 10 active ...s-client/lib/transport/lib/ 69% building modules 1022/1033 modules 11 active ...lib/transport/browser/abstr 69% building modules 1023/1033 modules 10 active ...lib/transport/browser/abstr 69% building modules 1024/1033 modules 9 active ...lib/transport/browser/abstra 69% building modules 1024/1034 modules 10 active ...compiler/src/i18n/extractor 69% building modules 1024/1035 modules 11 active ...mpiler/src/i18n/translation 69% building modules 1024/1036 modules 12 active ...gular/compiler/src/ml_parse 69% building modules 1025/1036 modules 11 active ...gular/compiler/src/ml_parse 69% building modules 1025/1037 modules 12 active ...ler/src/output/abstract_js_ 69% building modules 1025/1038 modules 13 active ...r/src/view_compiler/compile 69% building modules 1025/1039 modules 14 active ...er/src/view_compiler/compil 69% building modules 1025/1040 modules 15 active ...mpiler/src/view_compiler/co 69% building modules 1025/1041 modules 16 active ...ar/compiler/src/view_compil 69% building modules 1026/1041 modules 15 active ...ar/compiler/src/view_compil 69% building modules 1026/1042 modules 16 active ...ler/src/view_compiler/compi 69% building modules 1027/1042 modules 15 active ...ler/src/view_compiler/compi 69% building modules 1027/1043 modules 16 active ...ler/src/view_compiler/event 69% building modules 1027/1044 modules 17 active ...src/view_compiler/lifecycle 68% building modules 1027/1045 modules 18 active .../src/view_compiler/property 68% building modules 1027/1046 modules 19 active ...ler/src/view_compiler/query 68% building modules 1027/1047 modules 20 active ...d/node_modules/rxjs/util/is 68% building modules 1027/1048 modules 21 active ...rxjs/observable/IteratorObs 68% building modules 1027/1049 modules 22 active ...xjs/observable/ArrayLikeObs 68% building modules 1027/1050 modules 23 active .../node_modules/rxjs/InnerSub 68% building modules 1027/1051 modules 24 active ...d/node_modules/rxjs/util/is 68% building modules 1027/1052 modules 25 active ...oard/node_modules/rxjs/util 68% building modules 1027/1053 modules 26 active ...node_modules/rxjs/util/MapP 68% building modules 1028/1053 modules 25 active ...node_modules/rxjs/util/MapP 68% building modules 1028/1054 modules 26 active .../compiler/src/ml_parser/xml 68% building modules 1028/1055 modules 27 active .../@angular/compiler/src/i18n 68% building modules 1028/1056 modules 28 active ...angular/compiler/src/i18n/i 68% building modules 1028/1057 modules 29 active ...gular/compiler/src/i18n/par 68% building modules 1028/1058 modules 30 active ...er/src/i18n/serializers/xml 68% building modules 1028/1059 modules 31 active ...modules/@angular/common/src 68% building modules 1029/1059 modules 30 active ...modules/@angular/common/src 68% building modules 1029/1060 modules 31 active ...d/node_modules/requires-por 68% building modules 1029/1061 modules 32 active .../node_modules/querystringif 68% building modules 1030/1061 modules 31 active .../node_modules/querystringif 68% building modules 1031/1061 modules 30 active .../node_modules/querystringif 68% building modules 1032/1061 modules 29 active .../node_modules/querystringif 68% building modules 1033/1061 modules 28 active .../node_modules/querystringif 68% building modules 1034/1061 modules 27 active .../node_modules/querystringif 68% building modules 1035/1061 modules 26 active .../node_modules/querystringif 68% building modules 1036/1061 modules 25 active .../node_modules/querystringif 68% building modules 1037/1061 modules 24 active .../node_modules/querystringif 68% building modules 1038/1061 modules 23 active .../node_modules/querystringif 68% building modules 1039/1061 modules 22 active .../node_modules/querystringif 68% building modules 1040/1061 modules 21 active .../node_modules/querystringif 68% building modules 1041/1061 modules 20 active .../node_modules/querystringif 68% building modules 1042/1061 modules 19 active .../node_modules/querystringif 68% building modules 1043/1061 modules 18 active .../node_modules/querystringif 69% building modules 1044/1061 modules 17 active .../node_modules/querystringif 69% building modules 1045/1061 modules 16 active .../node_modules/querystringif 69% building modules 1046/1061 modules 15 active .../node_modules/querystringif 69% building modules 1047/1061 modules 14 active .../node_modules/querystringif 69% building modules 1048/1061 modules 13 active .../node_modules/querystringif 69% building modules 1049/1061 modules 12 active .../node_modules/querystringif 69% building modules 1050/1061 modules 11 active .../node_modules/querystringif 69% building modules 1051/1061 modules 10 active .../node_modules/querystringif 69% building modules 1052/1061 modules 9 active .../node_modules/querystringify 69% building modules 1053/1061 modules 8 active .../node_modules/querystringify 69% building modules 1054/1061 modules 7 active .../node_modules/querystringify 69% building modules 1055/1061 modules 6 active .../node_modules/querystringify 69% building modules 1056/1061 modules 5 active .../node_modules/querystringify 69% building modules 1057/1061 modules 4 active .../node_modules/querystringify 69% building modules 1058/1061 modules 3 active .../node_modules/querystringify 69% building modules 1058/1062 modules 4 active ...ular/compiler/src/i18n/i18n_ 69% building modules 1059/1062 modules 3 active ...ular/compiler/src/i18n/i18n_ 69% building modules 1060/1062 modules 2 active ...ular/compiler/src/i18n/i18n_ 69% building modules 1061/1062 modules 1 active ...ular/compiler/src/i18n/i18n_ 69% building modules 1061/1063 modules 2 active ...ar/compiler/src/ml_parser/xm 69% building modules 1061/1064 modules 3 active ...s/@angular/common/src/locali 69% building modules 1061/1065 modules 4 active .../@angular/common/src/common_ 69% building modules 1061/1066 modules 5 active ...odules/@angular/common/src/v 69% building modules 1061/1067 modules 6 active ...mdldashboard/node_modules/ms 69% building modules 1061/1068 modules 7 active ...@angular/common/src/location 69% building modules 1061/1069 modules 8 active ...ngular/common/src/directives 69% building modules 1061/1070 modules 9 active ...es/@angular/common/src/pipes 69% building modules 1062/1070 modules 8 active ...es/@angular/common/src/pipes 69% building modules 1063/1070 modules 7 active ...es/@angular/common/src/pipes 69% building modules 1064/1070 modules 6 active ...es/@angular/common/src/pipes 69% building modules 1065/1070 modules 5 active ...es/@angular/common/src/pipes 69% building modules 1066/1070 modules 4 active ...es/@angular/common/src/pipes 69% building modules 1067/1070 modules 3 active ...es/@angular/common/src/pipes 69% building modules 1068/1070 modules 2 active ...es/@angular/common/src/pipes 69% building modules 1068/1071 modules 3 active ...r/src/i18n/serializers/place 69% building modules 1069/1071 modules 2 active ...r/src/i18n/serializers/place 69% building modules 1070/1071 modules 1 active ...r/src/i18n/serializers/place 69% building modules 1070/1072 modules 2 active ...mon/src/location/platform_lo 69% building modules 1070/1073 modules 3 active ...mon/src/location/location_st 69% building modules 1070/1074 modules 4 active ...rc/location/hash_location_st 69% building modules 1070/1075 modules 5 active ...rc/location/path_location_st 69% building modules 1070/1076 modules 6 active ...gular/common/src/location/lo 69% building modules 1070/1077 modules 7 active ...lar/common/src/directives/ng 69% building modules 1070/1078 modules 8 active ...gular/common/src/directives/ 69% building modules 1070/1079 modules 9 active ...ngular/common/src/directives 69% building modules 1070/1080 modules 10 active ...ar/common/src/directives/ng 69% building modules 1070/1081 modules 11 active ...lar/common/src/directives/n 69% building modules 1070/1082 modules 12 active ...ar/common/src/directives/ng 69% building modules 1070/1083 modules 13 active .../src/directives/ng_template 69% building modules 1070/1084 modules 14 active ...ngular/common/src/pipes/asy 69% building modules 1070/1085 modules 15 active ...angular/common/src/pipes/da 69% building modules 1070/1086 modules 16 active .../common/src/pipes/i18n_plur 69% building modules 1070/1087 modules 17 active .../common/src/pipes/i18n_sele 69% building modules 1070/1088 modules 18 active ...angular/common/src/pipes/js 68% building modules 1070/1089 modules 19 active ...ar/common/src/pipes/lowerca 68% building modules 1070/1090 modules 20 active ...gular/common/src/pipes/numb 68% building modules 1070/1091 modules 21 active ...ngular/common/src/pipes/sli 68% building modules 1070/1092 modules 22 active ...ar/common/src/pipes/upperca 68% building modules 1071/1092 modules 21 active ...ar/common/src/pipes/upperca 68% building modules 1072/1092 modules 20 active ...ar/common/src/pipes/upperca 68% building modules 1073/1092 modules 19 active ...ar/common/src/pipes/upperca 69% building modules 1074/1092 modules 18 active ...ar/common/src/pipes/upperca 69% building modules 1075/1092 modules 17 active ...ar/common/src/pipes/upperca 69% building modules 1076/1092 modules 16 active ...ar/common/src/pipes/upperca 69% building modules 1077/1092 modules 15 active ...ar/common/src/pipes/upperca 69% building modules 1078/1092 modules 14 active ...ar/common/src/pipes/upperca 69% building modules 1079/1092 modules 13 active ...ar/common/src/pipes/upperca 69% building modules 1080/1092 modules 12 active ...ar/common/src/pipes/upperca 69% building modules 1081/1092 modules 11 active ...ar/common/src/pipes/upperca 69% building modules 1082/1092 modules 10 active ...ar/common/src/pipes/upperca 69% building modules 1083/1092 modules 9 active ...ar/common/src/pipes/uppercas 69% building modules 1084/1092 modules 8 active ...ar/common/src/pipes/uppercas 69% building modules 1085/1092 modules 7 active ...ar/common/src/pipes/uppercas 69% building modules 1086/1092 modules 6 active ...ar/common/src/pipes/uppercas 69% building modules 1087/1092 modules 5 active ...ar/common/src/pipes/uppercas 69% building modules 1088/1092 modules 4 active ...ar/common/src/pipes/uppercas 69% building modules 1089/1092 modules 3 active ...ar/common/src/pipes/uppercas 69% building modules 1090/1092 modules 2 active ...ar/common/src/pipes/uppercas 69% building modules 1091/1092 modules 1 active ...gular/common/src/pipes/numbe 69% building modules 1092/1093 modules 1 active ...es/@angular/common/src/facad 69% building modules 1092/1094 modules 2 active ...gular/common/src/facade/coll 69% building modules 1092/1095 modules 3 active .../pipes/invalid_pipe_argument 69% building modules 1092/1096 modules 4 active ...les/@angular/common/src/pipe 69% building modules 1092/1097 modules 5 active ...lar/common/src/private_impor 69% building modules 1093/1097 modules 4 active ...lar/common/src/private_impor 69% building modules 1094/1097 modules 3 active ...lar/common/src/private_impor 69% building modules 1094/1098 modules 4 active .../@angular/common/src/facade/ 69% building modules 1095/1098 modules 3 active .../@angular/common/src/facade/ 69% building modules 1096/1098 modules 2 active .../@angular/common/src/facade/ 69% building modules 1097/1098 modules 1 active .../@angular/common/src/facade/Hash: 06a0e20a4bafdccdd34b                      
**Time: 51013ms**
chunk    {0} main.bundle.js, main.bundle.map (main) 74.8 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 10 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 3.68 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: bundle is now VALID.

### Mention any other details that might be useful.
you guy are doing an awesome job. keep it up. as they say in france: chapeau. hats off to the angular CLI team. i'll soon become an active contributor, right now just reading everything that is happening ...

is there any way to speed this angular compilation process up? already did ng build --prod --aot

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
If you're developing you shouldn't use prod and AoT as it slows down the build significantly. We also have speed improvements on master coming this week. 

I'm going to close this issue, but thanks a lot for the kind words :)
