### ISSUE TITLE
ngtools/webpack not work

### ISSUE THREAD

**Issue by keyiis** [angular/angular-cli#4284]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows10

### Versions.
>node 6.9.2 
```
    "@angular/compiler-cli": "2.4.4",
    "@angular/platform-server": "2.4.4",
    "@ngtools/webpack": "1.2.4",
    "webpack": "^2.2.0",
    "webpack-dev-server": "^2.2.0",
```

### Repro steps.
> 
**tsconfig.aot.json**
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2015",
      "dom"
    ],
    "noEmit": true,
    "strictNullChecks": false,
    "skipDefaultLibCheck": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
      "node_modules/@types/",
      "typings/"
    ]
  },
  "angularCompilerOptions": {
    "skipMetadataEmit": true
  },
  "compileOnSave": false,
  "exclude": [
    "node_modules",
    "output"
  ]
}
```
**webpack.aot.js**
```
new AotPlugin({
                tsConfigPath: helpers.root('tsconfig.aot.json'),
                entryModule: helpers.rootAngular('app/app.module#AppModule'),
                skipCodeGeneration:true
            }),
```

### The log given by the failure.
> no error,but generate file size(app.js 6067kb) is same for aot and jit,so i think @ngtools/webpack not work?

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
`skipCodeGeneration:true` means you will not generate AoT code. Are you setting this to false for AoT runs?

**Comment by keyiis** [comment]
@filipesilva if set `skipCodeGeneration:false` get below error
```
ERROR in ./src/angular/app/main.ts
Module not found: Error: Can't resolve './../../../$$_gendir/src/angular/app/app.module.ngfactory' in 'D:\work\nodejs\keypos\aot\src\angular\app'
 @ ./src/angular/app/main.ts 2:0-95

ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
Module not found: Error: Can't resolve 'D:\work\nodejs\keypos\aot\$$_gendir' in 'D:\work\nodejs\keypos\aot\node_modules\@angular\core\src\linker'
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 71:15-36 87:15-102
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/angular/app/main.ts
```

**Comment by filipesilva** [comment]
That's a different problem though, and the real reason why you can't get size reductions. @hansl do you know the cause of that error?

**Comment by keyiis** [comment]
@filipesilva the error means i need set `"genDir":"some path"` in "angularCompilerOptions"?

**Comment by keyiis** [comment]
@filipesilva @hansl  after i change all template:require('...') to templateUrl:'....',the error disappears,but generate file size(4126KB after minify) big than use jit.

**Comment by keyiis** [comment]
@filipesilva @hansl can give me some pointers?

**Comment by keyiis** [comment]
@filipesilva @hansl still get big size bund file
![11](https://cloud.githubusercontent.com/assets/7766085/22453148/a4e16af0-e7b7-11e6-9509-83f655118890.JPG)

**Comment by filipesilva** [comment]
@keyiis you have to wait for a release to get the latest version. The PR fixing this has been merged but not released to npm yet.

**Comment by keyiis** [comment]
@filipesilva  i already update @ngtools/webpack & @angular/cli to last version,but aot still not work!
