### ISSUE TITLE
Angular-cli : not compile files of subfolders

### ISSUE THREAD

**Issue by kamalkech** [angular/angular-cli#4286]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX 10.6.8

### Versions.
> angular-cli: 1.0.0-beta.18
   node: 6.7.0
   os: darwin x64

### Repro steps.
> 
 - When i update files "src/app/**/*.ts" angular-cli not compile files !
 - When i update files  "src/app/*.ts" angular-cli compile fine the files.

So angular-cli cannot compile files of subfolders

### Log
> The log give any errors

Any idea ?!!

**Comment by deebloo** [comment]
you are using an old version of the cli. can you try updating to the latest see if that is still giving you issues?

**Comment by filipesilva** [comment]
Please update to the latest version, and also provide a repo where we can debug this behaviour. 

Testing locally I see the app being rebuilt, so I don't know how to repro it.

**Comment by kamalkech** [comment]
@deebloo @filipesilva

i follow intruction to update angular-cli

npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest

of course with sudo but i get this message error :

Failed at the node-sass@4.4.0 postinstall script 'node scripts/build.js'.

**Comment by filipesilva** [comment]
Installing npm packages with sudo leads to errors such as that one. See https://docs.npmjs.com/getting-started/fixing-npm-permissions for how to fix it.

**Comment by kamalkech** [comment]
@filipesilva it's not about permission cuz when i try to install i run this : 

sudo npm install -g angular-cli@latest

after un i put my password, installation run good but after cannot install module node-sass

**Comment by filipesilva** [comment]
It is because of permissions, because when you run `npm install`s with sudo, you mess you up your global folder permissions. 

Notice the `EACCES: permission denied` in the image you just posted. Please read the link I gave you to know more about it.

**Comment by kamalkech** [comment]
@filipesilva i follow all instructions of your link  but some errors : 

Build failed with error code: 1
/Users/kamal/npm-global/lib
└── (empty)

npm ERR! Darwin 10.8.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli@latest"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.4.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.4.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kamal/npm-global/npm-debug.log
npm ERR! code 1

**Comment by sumitarora** [comment]
@kamalkech Are you still having the issue?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
