### ISSUE TITLE
Custom Path for assets when using ng build

### ISSUE THREAD

**Issue by fahidmohammad** [angular/angular-cli#4287]
### OS?
> Windows 10

### Versions.
angular-cli: 1.0.0-beta.26
node: 6.4.0
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/compiler-cli: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5

Nodejs = v6.4.0

**lazy.module.ts**

`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LazyComponent } from './lazy.component';
import { lazyRouting } from './lazy.routes';

@NgModule({
  imports: [
    CommonModule,
    lazyRouting
  ],
  declarations: [LazyComponent]
})
export class LazyModule { }`

**lazy.routes.ts**

`import { ModuleWithProviders }  from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { LazyComponent } from './lazy.component';

const lazyRoutes: Routes = [
  {
    path: '',component: LazyComponent
  }
];
export const lazyRouting: ModuleWithProviders = RouterModule.forChild(lazyRoutes);`

**app.routes.ts**

`// Imports
import { ModuleWithProviders }  from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { HomeRoutes }  from './Home/home.route';

const appRoutes: Routes = [
  { path: '', redirectTo: '/home', pathMatch: 'full' },
  ...HomeRoutes,
   { path: 'about', loadChildren: './lazy/lazy.module#LazyModule' }
];

export const Routing: ModuleWithProviders = RouterModule.forRoot(appRoutes);`

While running the application using `ng serve` all works fine. But when using a production build `ng build --prod --sm=false --aot=true` im getting the below error on initial load.

**Error: Permission denied to access property "rejection"**

Any clue what i am messing around?

Regards
Fahid Mohammad

**Comment by fahidmohammad** [comment]
Just found what causing this error.  
Once the application is built i'm using express to server the static files. initial load all works fine but when i access the lazy load route its trying to load the **0.chunk.js** file which is considering as root path.
If i set the dynamic path this problem will be resolved. 
Is there any way i can set the path for the dynamic files ?

**Comment by Meligy** [comment]
Look at the `public-path` and `base-href` arguments of `ng build`.

**Comment by filipesilva** [comment]
Closed as answered by @Meligy.
