### ISSUE TITLE
ng build --prod: Cannot find module css-loader/index.js?sourcemap&minimize

### ISSUE THREAD

**Issue by francisoud** [angular/angular-cli#4292]
### Versions.
> ng --version
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64

### Repro steps.
> npm cache clean
> npm install --no-optional
> ng build --prod

### The log given by the failure.
    Module build failed: Error: Cannot find module '/var/bamboo/xml-data/build-dir/JOB1/node_modules/css-loader/index.js?sourcemap&minimize'
	        at Function.Module._resolveFilename (module.js:469:15)
	        at Function.Module._load (module.js:417:25)
    ...

### Mention any other details that might be useful.
Well actually I found the reason and the fix (it just for the record if anyone has the same issue...):
In angular-cli@1.0.0-beta.21 / package.json this following line:

    "extract-text-webpack-plugin": "^2.0.0-beta.4",

Resolved to different incompatible extract-text-webpack-plugin version:

**25 jan. 17**	

    +-- angular-cli@1.0.0-beta.21
    ...
    +-- extract-text-webpack-plugin@2.0.0-beta.5
    | +-- async@2.1.4
    | +-- loader-utils@0.2.16
    | | +-- big.js@3.1.3
    | | +-- emojis-list@2.1.0
    | | `-- json5@0.5.1
    | `-- webpack-sources@0.1.4
    |   `-- source-map@0.5.6
    ...

Changed to:

**30 jan. 17**	

    | +-- extract-text-webpack-plugin@2.0.0-rc.2
    | | `-- async@2.1.4

### Solution
Do a `npm shrinkwrap` but if it's too late, add the following line to your `package.json`:

    "devDependencies": {
        "extract-text-webpack-plugin": "2.0.0-beta.5"
    },

### Another problem
After fixing this you may get a lodash error:

    Error in bail mode: [default] /var/bamboo/xml-data/build-dir/JOB1/node_modules/@types/lodash/index.d.ts:245:24 
    Cannot find name 'Partial'.

change the dependency to

    "@types/lodash": "4.14.50",

make sure you don't take the v4.14.51

ps: Don't forget to delete you node_modules and run `npm cache clean` before `npm install`

**Comment by itsforbabu** [comment]
The fix suggested above didn't work for me on 1.0.0-beta.21, I continue to see the following

cannot find module css-loader

**Comment by castamir** [comment]
@ngtools/webpack@1.2.4 broke it, adding `"@ngtools/webpack": "1.2.3",` to package.json for temporal workaround fixed if me... for now...

**Comment by cnvill** [comment]
steps
npm install -g angular-cli@1.0.0-beta.21
npm cache clean
npm install

"devDependencies": {
    "extract-text-webpack-plugin": "2.0.0-beta.5",
    "webpack": "2.2.0-rc.3",
    "@types/lodash": "4.14.50",
    "@ngtools/webpack": "1.2.3"
},

**Comment by byungjuJin** [comment]
extract-text-webpack-plugin is upgraded to 2.0.0-rc.2.
just add "extract-text-webpack-plugin": "2.0.0-beta.5" works for me.
Thanks!

**Comment by castamir** [comment]
after "double" npm install I've got nprm error `UNMET DEPENDENCIES`.

I fixed all dependencies by specifying these dependencies explicitly:

```

        "@ngtools/webpack": "1.1.5",
        "extract-text-webpack-plugin": "2.0.0-beta.5",
        "webpack": "2.1.0-beta.25",
        "loader-runner": "2.2.0",
        "tsickle": "0.2.4",
        "source-map-support": "0.4.10"
```

most important are `extract-text-webpack-plugin` and `webpack` itself

**Comment by itsforbabu** [comment]
The "ng build --prod" doesn't fail anymore, thanks for the folks in thread here, but we are yet to smoke test. Will keep posted.

**Comment by hydra1983** [comment]
All the solutions above doesn't work for me. 
I added 

```
{
    "extract-text-webpack-plugin": "2.0.0-beta.5",
}
```

But ```2.0.0-rc.3``` still be installed.
 
```
peerDependencies WARNING [extract-text-webpack-plugin@2.0.0-rc.3] in /var/jenkins_home/workspace/jianji-dev/jianji-web2-pipeline/node_modules/.2.0.0-rc.3@extract-text-webpack-plugin requires a peer of webpack@^2.2.0 but webpack@2.1.0-beta.25 was installed
```

After I run

```shell
rm -rf node_modules/.2.0.0-rc.3@extract-text-webpack-plugin
```

And re-build production again, it works.

**Comment by castamir** [comment]
make a fresh new `npm install` and then hit `npm ls extract-text-webpack-plugin` to see which package depends on it

**Comment by itsforbabu** [comment]
Can anyone from angular-cli DEV community please comment and let us know if this will be fixed on the newer version so that we don't have to use this hack with older version?

**Comment by bertolo1988** [comment]
# +1

**Comment by miscoo1** [comment]
+1

**Comment by GeorgeZhai** [comment]
# +1

**Comment by mikekeda** [comment]
+1

**Comment by itsforbabu** [comment]
With @angular/cli: 1.0.0-rc.1, I see this is now fixed. Just create a new project out of RC1 version and try to use the generated package.json and it should work. Pasted my package.json below and this works now. I dont see the issue anymore. I was referring https://github.com/angular/angular-cli/pull/4435 and understood that they have taken care of this in beta 31 fix itself.

  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
},
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.1",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "~2.0.0"
  }

**Comment by mikekeda** [comment]
@itsforbabu Thanks
I updated angular/cli to 1.0.0-rc.1, and now it works

**Comment by bertolo1988** [comment]
@mikekeda How have you updated to rc.1 ? Last pubished version is still [beta.28.3](https://www.npmjs.com/package/angular-cli).

**Comment by deebloo** [comment]
```BASH
npm uninstall -g angular-cli
npm cache clear
npm install -g @angular/cli@latest
```

**Comment by filipesilva** [comment]
Closing as fixed in latest releases.

**Comment by bertolo1988** [comment]
Why not publish under angular-cli as usual?
