### ISSUE TITLE
Uncaught Error: Cannot find module "./$$_gendir/app/app.module.ngfactory"

### ISSUE THREAD

**Issue by manuelfink** [angular/angular-cli#4294]
Compiling an app with angular-cli with 

``` 
ng build --prod --env=prod --aot
````

I end up the the following error in the browser

```
Uncaught Error: Cannot find module "./$$_gendir/app/app.module.ngfactory"
    at Object.<anonymous> (main.925377c….bundle.js:31562)
    at r (bootstrap 6ea98d3…:52)
    at Object.<anonymous> (main.925377c….bundle.js:51201)
    at r (bootstrap 6ea98d3…:52)
    at window.webpackJsonp (bootstrap 6ea98d3…:23)
    at main.925377c….bundle.js:1
``` 

the code causing the error is: 

```
/***/ },
/* 208 */
/***/ function(module, exports, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__polyfills_ts__ = __webpack_require__(285);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__polyfills_ts___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0__polyfills_ts__);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__angular_core__ = __webpack_require__(1);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__environments_environment__ = __webpack_require__(284);
throw new Error("Cannot find module \"./$$_gendir/app/app.module.ngfactory\"");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__angular_platform_browser__ = __webpack_require__(270);
```

### Versions

MacOS 10.12.2
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: darwin x64

Any idea what may be the origin of the error?

**Comment by Meligy** [comment]
Can you share a repository showing a sample project with this error?

That is, create a new Angular CLI project, and then try to reproduce the error?

Thanks.

**Comment by annvnzndrvn** [comment]
Having same issue here.

`Uncaught Error: Cannot find module "./$$_gendir/app/app.module.ngfactory"
    at Object.<anonymous> (main.78a068d….bundle.js:21992)
    at r (bootstrap 3bff2fc…:52)
    at Object.<anonymous> (main.78a068d….bundle.js:34716)
    at r (bootstrap 3bff2fc…:52)
    at window.webpackJsonp (bootstrap 3bff2fc…:23)
    at main.78a068d….bundle.js:1`

This is happening only when serving dist folder content generated with `ng build --prod --env=prod --aot` and directly on the log output after running ng build command. When skipping --aot parameter it returns no error.

I finally managed to resolve it by deleting every single test file in my application folder. I was working under the assumption that angular-cli would exclude these files by default but it seems it's not the case with my current setup (using angular-cli@1.0.0-beta.21).

**Comment by filipesilva** [comment]
Closing as there was no reproducion given by original author. 

@annvnzndrvn you're using a pretty old version, I recommend updating.
