### ISSUE TITLE
build target subfolder for static app scripts

### ISSUE THREAD

**Issue by manuelfink** [angular/angular-cli#4298]
Is it anyhow possible do define a subfolder of the target where the application code should be located in? 

This would make defining caching strategies and hosting much easier eg.:

 * /index.html (5min cached)
 * /static-app/ (cache for ever)
    * 0.hash.js
    * 1.hash.js
    * ....

**Comment by adam77** [comment]
this would be useful. i'm looking for something similar - ability to include `package.version` in the chunk name. eg:

```
index.html (5min cached)
chunkA.1.0.0.js (cache for ever)
chunkB.1.0.0.js
...
chunkA.1.1.0.js
chunkB.1.1.0.js
...
```

**Comment by filipesilva** [comment]
The `--public-url` option for `ng build` does this I believe.

**Comment by adam77** [comment]
`--public-url` [PR for reference](https://github.com/angular/angular-cli/pull/3285)
