### ISSUE TITLE
Module discovery and loading

### ISSUE THREAD

**Issue by EduardoOliveira** [angular/angular-cli#4299]
Im starting to develop a front end for a completely modular backend (a vertx verticles docker cluster).

The main idea/problem is to have a base ng2 application that defines a dashboard, sidemenu, other base components, and connects to the backend discovering which modules are enabled, via some kind of list of manifests containing the the path for the required JS files/bundles, the modules should be completely independent, something that you would be able to download from github and place in a folder.

So far the closest thing I've found was this question, http://stackoverflow.com/questions/40039825/angular2-loading-modules-dynamically-from-a-given-folder , that shows how to load modules in runtime, but I hanven't found a way to develop and build the bundles independently.

Is this even possible? Can you guys point me in the right direction? Have I missed any example of this?

**Comment by Meligy** [comment]
This is a StackOverflow question not really an issue.

I don't know if that would be an option, but you can lazy load all modules, and maybe if needed have route guards that allow these routes only if the backend agrees.

**Comment by EduardoOliveira** [comment]
I thought so, I've created the question there (http://stackoverflow.com/questions/41946481/ng2-cli-module-discovery-and-loading) but after receiving an instant down vote I assumed it was better placed here as an issue. I know its a quite abstract problem and at the moment I have nothing concrete to give back in this matter.

**Comment by filipesilva** [comment]
Closing as this isn't an actionable issue. I don't have any better advise though than to ask on SO.
