### ISSUE TITLE
Command `ng update` not working

### ISSUE THREAD

**Issue by hpawe01** [angular/angular-cli#4304]
### OS
Linux Ubuntu 16.04 LTS

### Versions
```
angular-cli: 1.0.0-beta.26
node: 4.7.2
os: linux x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
```

### Repro steps
`ng new cli-test`
`cd cli-test`
`ng update`

### The log given by the failure
`The specified command update is invalid. For available options, see 'ng help'.`

### Mention any other details that might be useful.
I noticed this behavior when I updated my angular-cli version from beta.25.5 to beta.26 (https://github.com/angular/angular-cli#updating-angular-cli).
I thought this was working with the previous angular-cli version, but with beta.25.5 I get the same message.

**Comment by MTechDE** [comment]
They die not released this Feature with the Last Beta. Wait for Beta 27.
They commited this Feature today.

**Comment by MTechDE** [comment]
They die not released this Feature with the Last Beta. Wait for Beta 27.
They commited this Feature today.

**Comment by marcoturi** [comment]
I'm getting the same error, migrating to beta 30 from 26
