### ISSUE TITLE
immediately restart build on file change?

### ISSUE THREAD

**Issue by grauschnabel** [angular/angular-cli#4308]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
```
uname -a
Linux martin-arch 4.9.6-1-ARCH #1 SMP PREEMPT Thu Jan 26 09:22:26 CET 2017 x86_64 GNU/Linux

```
This is current arch linux.

### Versions.
```
angular-cli: 1.0.0-beta.26
node: 7.4.0
os: linux x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/flex-layout: 2.0.0-beta.4
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

```
### Repro steps.
Start `ng serve` or `ng serve --hmr` on any of your projects.
Save a file and while the rebuid process is running change something and save it again.
Then you will see ng building the first process till the end and restarts a new build.

But to be faster in development it would be great to stop the build when the file changes and start the rebuild immediately because the other changes from the first build arent needed anymore.

maybe there is a flag for this, but if it seems not to be documented...  I have seen this feature somewhere else, maybe the angular2-webpack on github?  I'm not sure anymore.

Thanks for your help.

**Comment by grizzm0** [comment]
When you edit some code you might need to rebuild one or more chunks. If we would cancel the first rebuild in favour of the second change the chunks might end up invalid.

**Comment by filipesilva** [comment]
If there's a good way of doing this, I do not know of it. Would be happy to implement if someone can point me to it.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
