### ISSUE TITLE
Deploying via gh-pages: No changes found. Deployment skipped. You might also need to return to the initial branch manually.

### ISSUE THREAD

**Issue by vorugantia** [angular/angular-cli#4314]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.26
node: 6.3.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Deploying for the first time.

### The log given by the failure.
> Normally this include a stack trace and some more information.

Upon calling `ng github-pages:deploy` in the master branch, I get the error message "No changes found. Deployment skipped. You might also need to return to the initial branch manually." It seems that the bundling stopped half-way into deployment.

Any ideas for what is causing this?

**Comment by vorugantia** [comment]
Could webpack be causing this error? It's currently not listed in my `package.json` as a dependency, not sure if that matters...

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
