### ISSUE TITLE
Latest points to 1.0.0-beta.26 not 1.0.0-beta.28

### ISSUE THREAD

**Issue by mp3por** [angular/angular-cli#4316]
I tried to update to the latest version.

I used the commands specified in the Update section however when I ran `npm install -g angular-cli@latest` it installed version 1.0.0-beta.26 not 1.0.0-beta.28 ? 

Side note: `ncu -n` told me about 1.0.0-beta.28 however I was unable to find any info about what has changed in the newest version. Where can I find such information ?

**Comment by delasteve** [comment]
There were issues with it being released last night. It wasn't moved to `latest` because of that. The team is working hard on getting it out as fast as they can.

**Comment by mp3por** [comment]
Right. Ok. No pressure. I was just curious. :)
