### ISSUE TITLE
Build error when adding LOG_LOGGER_PROVIDERS from angular2-logger

### ISSUE THREAD

**Issue by tasstwa** [angular/angular-cli#4317]
### OS?
Ubuntu precise (12.04.5 LTS)

### Versions.
angular-cli: 1.0.0-beta.26
node: 6.9.2
os: linux x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
typescript@2.0.10 

### Repro steps.
$ ng new testapp
$ cd testapp/
$ npm install angular2-logger --save
$  cd src/app
$ patch -p0 <<-EOF
```
diff --git a/src/app/app.module.ts b/src/app/app.module.ts
index 67ae491..34ef2fa 100644
--- a/src/app/app.module.ts
+++ b/src/app/app.module.ts
@@ -4,6 +4,7 @@ import { FormsModule } from '@angular/forms';
 import { HttpModule } from '@angular/http';
 
 import { AppComponent } from './app.component';
+import { LOG_LOGGER_PROVIDERS } from "angular2-logger/core";
 
 @NgModule({
   declarations: [
@@ -14,7 +15,7 @@ import { AppComponent } from './app.component';
     FormsModule,
     HttpModule
   ],
-  providers: [],
+  providers: [LOG_LOGGER_PROVIDERS],
   bootstrap: [AppComponent]
 })
 export class AppModule { }
EOF
```
$ ng build

### The log given by the failure.
```
ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 48:14 in the original .ts file), resolving symbol LOG_LOGGER_PROVIDERS in /home/user/testapp/node_modules/angular2-logger/core.d.ts, resolving symbol AppModule in /home/user/testapp/src/app/app.module.ts, resolving symbol AppModule in /home/user/testapp/src/app/app.module.ts
```

### Mention any other details that might be useful.
* Not sure if the issue is with Typescript, or angular-cli, or webpack, or angular2-logger...
* I have seen other similar case here.
* I will be working on a workaround.

**Comment by Meligy** [comment]
There's a known issue with Angular compiler and `export * from ...`, which is how LOG_LOGGER_PROVIDERS is exported from `"angular2-logger/core"`.

For a workaround, try importing from `"angular2-logger/core/providers"` instead, as [it seems declared there](https://github.com/code-chunks/angular2-logger/blob/master/app/core/providers.ts).

**Comment by tasstwa** [comment]
That works, but the exact line is
`import { LOG_LOGGER_PROVIDERS } from "angular2-logger/app/core/providers";`

Many thanks! This ticket can be closed if unrelated to angular-cli.

**Comment by uberspeck** [comment]
I've followed the steps above and i'm still getting an error. I'm using beta 31 of angular-cli. 

```
undefined is not an object (evaluating '_this.logger.info')
```
