### ISSUE TITLE
Routes in ng build --prod 

### ISSUE THREAD

**Issue by alfredoizjr** [angular/angular-cli#4319]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
W 10
### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.26

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
Hi I have a simple app with two  components,  I make a router archive too, but  when I execute the command ng build --prod,  my routes stop working but in my developer version is working well , I move all the archive from inside the dist folder to my root of my domain can you help me ??
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Meligy** [comment]
Can you share a simple app repository that we can use to reproduce this?

**Comment by filipesilva** [comment]
Heya, I think you have an issue with deployment. See https://angular.io/docs/ts/latest/guide/deployment.html for deployment information.
