### ISSUE TITLE
Cache Busting when deploying new angular-cli (angular2) app to production Nginx server

### ISSUE THREAD

**Issue by subatomicglue** [angular/angular-cli#4320]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Running on AWS.   
- Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-36-generic x86_64)
- Nginx/1.10.0 (Ubuntu)
- Chrome Version 55.0.2883.95 (64-bit)
- Safari Version 10.0.3 (11602.4.8.0.1)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.21
node: 7.0.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

`ng build -prod` gives me a driectory that looks like this:
```
.                                                  inline.d41d8cd98f00b204e980.bundle.js              main.d55402e0a3445d5fdc2a.bundle.map
..                                                 inline.d41d8cd98f00b204e980.bundle.map             styles.58e065928ed8ebd0b582.bundle.js
assets                                             main.d55402e0a3445d5fdc2a.bundle.js                styles.58e065928ed8ebd0b582.bundle.map
index.html                                         main.d55402e0a3445d5fdc2a.bundle.js.gz             styles.d60e9d4f379e32123bd8c956db2f317d.bundle.css
```
Which I push to the server at AWS.

### The log given by the failure.
> Normally this include a stack trace and some more information.

Whenever I push this code to production server, all our users get an infinite loading screen.   
To fix they need to hold down SHIFT while hitting refresh button, presumably clearing the cache and getting the fresh copy.

I _suspect_ that the `index.html` is cached from last time, and that the `.css` and the `.js` files being included from that old `index.html` are pointing at the old names which are generated with a filehash to uniquify the name...   

`css` and `js` Lines from my `index.html`:
```
<link href="styles.d60e9d4f379e32123bd8c956db2f317d.bundle.css" rel="stylesheet">
...
<script type="text/javascript" src="inline.d41d8cd98f00b204e980.bundle.js"></script><script type="text/javascript" src="styles.58e065928ed8ebd0b582.bundle.js"></script><script type="text/javascript" src="main.d55402e0a3445d5fdc2a.bundle.js"></script>
```

### Mention any other details that might be useful.

Is there a way for `index.html` to auto reload if the js or css files fail to load?   Or to output a helpful error to the user to hit CTRL-R or SHIFT-reload?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
Your server needs to be configured to send the appropriate cache control headers.
If you don't have control over the server configuration, you can also look at adding meta tags to index.html.

**Comment by subatomicglue** [comment]
Thanks!

To help internet searches on this topic,
Here's what I ended up with:

In `index.html`:
```
  <meta http-equiv="cache-control" content="no-cache, must-revalidate, post-check=0, pre-check=0">
  <META HTTP-EQUIV="Expires" CONTENT="0">
  <meta http-equiv="pragma" content="no-cache">
```

In Nginx conf `/etc/nginx/conf.d/default.conf`:
```
server {
  //  ...
  location /index.html {
      add_header    Cache-Control  public;
      add_header    Cache-Control  no-store;
      add_header    Cache-Control  no-cache;
  }
  //  ...
}
```

**Comment by subatomicglue** [comment]
Ok, `index.html` is loading off server, not cached.   But now the `.css` and `.js` bundles **are** loading from disk cache.   The effect I see in my browser is that my `Loading...` is on screen infinitely - the **angular2 app never starts**.   I get **no errors** in the browser.

Has anyone seen this behavior with angular-cli before?

I was under the impression that the `.js` and `.css` filename was generated with file hash, to uniquify the filename, and force a load only if the code has changed.   This is ideal, because we _want_ cacheing when the code hasn't changed, for faster page load.

ideas?

**Comment by subatomicglue** [comment]
Well, here's a HACK that works (for my case).    It certainly isn't very general!

```
<!-- reload if angular doesn't start in a reasonable amount of time -->
<script> type="text/javascript">
window.setTimeout(function() {
  if (window.MY_APP_IS_RUNNING == undefined)
    location.reload(true);
}, 5000);
</script>
<!-- end - reload if angular doesn't start in a reasonable amount of time -->
```

And then in `app.module.ts` I set the variable:
```
export class AppModule {
  constructor(){
    // so that index.html can detect we started up (if it doesn't detect, then it'll reload)
    window['MY_APP_IS_RUNNING'] = true;
  }
}
```

And it actually worked, it broke my frozen `loading...` screen after 5 seconds into the actual app.

**Comment by subatomicglue** [comment]
More info, this is from Chrome `Network/Headers` tab under `Developer Tools`:

`inline.d41d8cd98f00b204e980.bundle.js`, `main.710e96c682d60bc8807d.bundle.js`
```
Cache-Control:max-age=0
Cache-Control:no-cache
Cache-Control:no-store
Cache-Control:public
```

`styles.58e065928ed8ebd0b582.bundle.js`, `styles.d60e9d4f379e32123bd8c956db2f317d.bundle.css`
```
Cache-Control:max-age=2678400
Cache-Control:public
```

**Comment by subatomicglue** [comment]
Tracked down the problem to this block in my nginx `conf` file:

```
  location ~ ^/(assets|bower_components|scripts|styles|views) {
    expires     31d;
    add_header  Cache-Control public;
  }
```

Add one `/` character to limit to **directories**, here's the change:
```
  location ~ ^/(assets|bower_components|scripts|styles|views)/ {
    expires     31d;
    add_header  Cache-Control public;
  }
```

**Comment by subatomicglue** [comment]
Noticed that after this change, users are still having the issue with frozen at "Loading..." page.   They have to manually SHIFT-reload the page.

Any other ideas?

**Comment by grizzm0** [comment]
There was a bug until beta 24 och 25 where the hash of inline.js wasn't changed and thus not busting the cache while the main/vendor.js was busted. This resulted in the app trying to load the old no longer existing files included in the cached inline.js.

Please update to latest beta. 21 is quite old.

**Comment by grizzm0** [comment]
@subatomicglue Could you close as solved if that helped you?

**Comment by subatomicglue** [comment]
For sure.   I will once I have a chance to try it.   (Upgrading isn't a trivial 1second operation), need to find a moment to work on this.

**Comment by filipesilva** [comment]
Closing as answered. This actionable part of this bug was fixed a while ago.

**Comment by ahexdev1** [comment]
Hi @grizzm0 @subatomicglue  , i am facing same issue, we are using Angular 5 + Jenkins with nginx server setup.

angular-cli - 1.0.0-beta.25.5

still not working for me, can you tell me what all changes are required to solve issue in mine case?

Thanks and regards
