### ISSUE TITLE
Webpack rebuild error

### ISSUE THREAD

**Issue by digital216** [angular/angular-cli#4326]
### OS?
Ubuntu 16.04

### Versions
angular-cli: 1.0.0-beta.28.3
node: 7.4.0
os: linux x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

### Repro steps.
Created the app with the `angular-cli` (`ng new`).  Ran `ng serve` to make sure everything was working.  All was good, webpack worked and reported:

    Hash: 7a95e8c73d53b9f210c7                    
    Time: 8041ms
    chunk    {0} main.bundle.js, main.bundle.map (main) 17.2 kB {3} [initial] [rendered]
    chunk    {1} styles.bundle.js, styles.bundle.map (styles) 205 kB {4} [initial] [rendered]
    chunk    {2} scripts.bundle.js, scripts.bundle.map (scripts) 375 kB {4} [initial] [rendered]
    chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.83 MB [initial] [rendered]
    chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
    webpack: Compiled successfully.

I was able to load the app in a browser.  Made a small change to the `app.component.ts` file (removed the trailing new line).  Saved the file, webpack attempted to re-bundle the file, but failed.

### The log given by the failure.
    Hash: 7a95e8c73d53b9f210c7                
    Time: 613ms
    chunk    {0} main.bundle.js, main.bundle.map (main) 17.2 kB {3} [initial]
    chunk    {1} styles.bundle.js, styles.bundle.map (styles) 205 kB {4} [initial]
    chunk    {2} scripts.bundle.js, scripts.bundle.map (scripts) 375 kB {4} [initial]
    chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.83 MB [initial]
    chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]

    ERROR in Cannot read property 'length' of undefined
    webpack: Failed to compile.

**Comment by born2net** [comment]
same issue, works fine on first build, subsequent builds fail.
```
ERROR in ./src/app/campaigns/sequencer.ts
Module build failed: Error
    at WebpackCompilerHost.populateWebpackResolver (C:\msweb\studioweb\node_modules\@ngtools\webpack\src\compiler_host.js:218:51)
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\plugin.js:352:33
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/campaigns/index.ts 26:0-40
 @ ./src async
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4208/ ./src/main.ts
webpack: Failed to compile.
```

**Comment by diicar** [comment]
Same issue ... :( 
rebuilld is too fast 🥇

**Comment by born2net** [comment]
I agree, I started crying from joy of how fast it was... but started crying again when it crashed 👍 💯

**Comment by johannesjo** [comment]
Same here on ubuntu 16.10 and node 6.9.2.

**Comment by yarrgh** [comment]
I may be wrong, but I believe it may have to do with the fact that the typescript doesn't get compiled, or at least compiled correctly after the first initial build. See my [other comment](https://github.com/angular/angular-cli/issues/4329#issuecomment-276812560)

**Comment by intellix** [comment]
I'm getting the same issue and have been debugging a little. Not found anything yet but here's an example project: https://github.com/intellix/angular-cli-b28/tree/master/src/app/lazy

I only have the problem when saving lazy SCSS or HTML. Saving a TS doesn't give `Module build failed: error` though

**Comment by born2net** [comment]
ok I reverted back to .26 so I can work for now but that was not enough.
I also had to:
```npm install --save @ngtools/webpack@1.2.4```
until .28 gets stable

**Comment by web-dave** [comment]
@born2net I'll try it out

**Comment by johannesjo** [comment]
```
npm install --save @ngtools/webpack@1.2.4 
```
That's it! Works also with the new version.

**Comment by born2net** [comment]
so u r using @1.2.4  with .28 works?

**Comment by web-dave** [comment]
pew, have to do a workshop tomorrow. saved my day/night

**Comment by alshdavid** [comment]
I have this problem.

Windows 10
Node 6.9.5

running `ng serve`
When I change an HTML file it throws in cmd:
`
ERROR in ./src/app/components/side-menu/side-menu.component.html
Module build failed: Error
    at WebpackCompilerHost.populateWebpackResolver (C:\sandbox\admin.marshallinstalls.co.nz\node_modules\@ngtools\webpack\src\compiler_host.js:218:51)
    at C:\sandbox\admin.marshallinstalls.co.nz\node_modules\@ngtools\webpack\src\plugin.js:352:33
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/components/side-menu/side-menu.component.ts 21:22-59
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main
`

However when I run `ng serve --aot` it compiles and runs just fine

**Comment by web-dave** [comment]
beta 29 has the same error

**Comment by Sviatique** [comment]
The same thing with beta.30

**Comment by alshdavid** [comment]
I have updated to node 7.5 + cli beta.30 (from 6.9.5 & beta.28) and it seems the problem is no longer present.

**Comment by rickardd** [comment]
npm install --save @ngtools/webpack@1.2.4 

Worked for me too! yay

**Comment by emreavsar** [comment]
anybody facing this issue `"@angular/cli": "^1.0.0-rc.0"` in `package.json`?

**Comment by emreavsar** [comment]
I did some research based on my problem, maybe it helps someone else as well:

i introduced typings into the project, and since I did this, this problem happens with the live-reload of lazy loaded modules. No idea why this happens. 

Maybe someone can give a brief info about this?

I'm using the oldschool way of typings as follows:

package.json:
```
{
  "scripts": {
    ...
    "install": "typings install"
  }
...
  dependencies: {
...
    "typings": "^2.1.0",
...
  }
}
```

typings.json:
```
{
  "globalDependencies": {
    "typings": "github:t4deon/FHIR-STU3-TS-Typings/typings.d.ts#e36b4cf4bb07734b97ea8d14893f7747fd990438"
  }
}
```

src/tsconfig.app.json:
```
...
{
  "files": [
    "../typings/index.d.ts"
  ]
}
```

**Comment by mhadaily** [comment]
this works for me 

`yarn add @ngtools/webpack@1.3.0`

ng details:
@angular/cli: 1.0.0
node: 7.9.0
os: darwin x64
```
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2
@ngtools/webpack: 1.3.0
```

**Comment by zinderud** [comment]
hocam su adresde https://github.com/angular/angular-cli/issues/4326 da birkaç kişi sorun yaşamış
yarn add @ngtools/webpack@1.3.0  ile biri sorunu çözmüş  şimdiki güncel i
yarn add @ngtools/webpack@1.8.2  bir denermisiniz

**Comment by emreavsar** [comment]
@zinderud bende problem cözüldü bile aga
