### ISSUE TITLE
environment.prod.ts is always included when doing ng serve --env=source (or other environments)

### ISSUE THREAD

**Issue by dereklin** [angular/angular-cli#4331]
I am using angular-cli 1.0.0-beta.26

I want to differentiate between environments, but environment.prod.ts is always included when running ng serve --env=source or --env=other

And the settings in environment.prod.ts overrides settings in environment.ts or other

**Comment by filipesilva** [comment]
Can you give me reproduction steps so I can see this happening?

**Comment by dereklin** [comment]
This is fixed in angular-cli 1.0.0-beta.28.3
