### ISSUE TITLE
Github Deploy failed and erased my local repo

### ISSUE THREAD

**Issue by markgoho** [angular/angular-cli#4333]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10

### Versions. 
angular-cli: 1.0.0-beta.26
node: 7.4.0

### Repro steps.
I ran the github-pages deploy command from the windows power shell.

### The log given by the failure.
[master ≡]> ng github-pages:deploy -m "Trying to deploy using angular cli"
Hash: 14405ceffd8e1bebe48d
Time: 24975ms
chunk    {0} main.bundle.js, main.bundle.map (main) 3.03 MB {2} [initial] [rendered]
chunk    {1} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 1.69 kB {2} [initial] [rendered]
chunk    {2} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
Command failed: git clean -f -d
warning: failed to remove debug.log
warning: failed to remove mockup/node_modules/node-sass/vendor/win32-x64-51/binding.node
warning: failed to remove src/app/categories
warning: failed to remove src/app/posts

There was a permissions error during git file operations, please close any open project files/folders and try again.
You might also need to return to the master branch manually. You might also need to return to the initial branch manually.

### Mention any other details that might be useful.
This command removed all existing files from my project and appears to have like re-initialized the whole repo. I'm not a Git power user, so this might have something to do with branches, but I basically have to re-clone my repo from Github because nothing is left.

**Comment by tobymurray** [comment]
>erased my entire repo

> I basically have to re-clone my repo from Github because nothing is left

I think your title is a little bit misleading - if anything, it appears you lost a copy (your local copy) of your repo. The fact that you were able to re-clone it means that at least the remote repository is still there, and was not erased.

From my understanding, deploying to GitHub Pages happens by creating a `gh-pages` branch. It appears that the branch is not off of an existing branch, as most branches are in Git, but an "orphan" - almost like a brand new repository inside your existing repository (but also not a lot like that...). You can read the generally excellent Git documentation on orphan branches [here](https://git-scm.com/docs/git-checkout/#git-checkout---orphanltnewbranchgt).

As you noted, it sounds like perhaps the CLI errored out while it was on the `gh-pages` branch, which wouldn't have any of your work on it. Presumably you could just switch back to your regular branch with something like `git checkout develop`, and you would see your work again. I would be extremely surprised if the CLI somehow managed to delete your local repository entirely.

As a side note, I personally feel that a workable understanding of Git (or other VCS) is one of the most fundamental skills a developer can have - I think it's definitely worth investing some time into understanding the basics.

**Comment by tobymurray** [comment]
@markgoho - while it looks like there is a bug in the GitHub pages deploy, did you confirm that your local repo was actually erased? You weren't just on a different (and empty) `gh-pages` branch?

**Comment by markgoho** [comment]
Yes, in Windows Explorer most of the folders were non-existent and those that were left were totally empty.

**Comment by tobymurray** [comment]
To be clear, that's exactly what you would expect to see if you were on the `gh-pages` branch and your repo was not "deleted". `git rev-parse --abbrev-ref HEAD` would show you which branch you're currently on. I don't know, but to me it seems extremely likely that you were on a different branch than you were expecting and not that the Angular CLI had deleted your local repo.

**Comment by filipesilva** [comment]
@tobymurray's explanation makes sense to me. I think you just got left in the wrong branch due to the permissions error. If your main branch is `master`, do `git checkout master` and all your work will still be there.

Closed via https://github.com/angular/angular-cli/pull/4385.
