### ISSUE TITLE
Reflect metadata shim error after update to 28.3

### ISSUE THREAD

**Issue by hassanasad** [angular/angular-cli#4335]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> macOS Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.28.3
node: 7.5.0
os: darwin x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

Upgraded to beta.28.3 just now and getting this error in console:
```
Uncaught reflect-metadata shim is required when using class decorators
```

`decorators.js:193`

**Comment by albinscode** [comment]
Hi @hassanasad, 

I dit get the same issue and I fixed it by adding the following two lines on top on my main.ts.
```
import 'zone.js';
import 'reflect-metadata';
```
See https://github.com/AngularClass/angular2-webpack-starter/issues/353

**Comment by hassanasad** [comment]
Thanks @albinscode - It works for me if i put:
```
import 'zone.js';
import 'reflect-metadata';
```
in main.ts (on top)

and
```
import 'reflect-metadata';
```
in polyfills.ts (on top) otherwise it still gives pretty weird errors.

I am still not sure why this is happening because a new app created by `ng new` doesn't seem to replicate these errors even without the patch you told above.

**Comment by albinscode** [comment]
Yes, I agree, it is homemade job and I don't have any clear explanation as far as this is a very specific issue... Thanks for your feedback.

Hope we will get a technical answer soon ;)

**Comment by deebloo** [comment]
with the newest beta there is a new option in the angular-cli.json file to include polyfills. Maybe when upgrading you updated main.ts but not angular-cli.json?

**Comment by maxime1992** [comment]
I'm not sure if this is related or not.

But I had this strange issue this morning : https://github.com/angular/angular-cli/issues/4343#issuecomment-276918967

And adding (at least) a type `any` to my `@Inject` solved my problem.

As @deebloo said, make sure you have the line with `polyfills` in your `angular-cli.json` : 
![image](https://cloud.githubusercontent.com/assets/4950209/22551291/8523dc72-e954-11e6-98e3-249a3599acdf.png)

and try to add a type to your @Inject, before adding 
```
import 'zone.js';
import 'reflect-metadata';
```

I'm saying that because I changed to a branch were I didn't have my `@Inject() someVar: any` and your error popped out. I rebased from master were I added it and it's now working.

**Comment by hassanasad** [comment]
@deebloo and @maxime1992 That was it!

When i added the line `"polyfills": "polyfills.ts"` in my `angular-cli` everything started working as before.

I did not overwrite my `angular-cli.json` file while upgrading because of all the custom settings in there. Each update is becoming rather painful. I updated the `lint` options but somehow missed that one line which caused all the havoc :)

This case is solved - thanks guys for all the help!

**Comment by ArtturiSipila** [comment]
It doesn't look like it's adding polyfills to index.html as  an entry chunk. It probably should do that?

**Comment by Albosonic** [comment]
import 'zone.js';
import 'reflect-metadata';

worked for me too. had to put it at the top of the file.

**Comment by rsheptolut** [comment]
For anyone who's as dumb as I am: you need to put these lines of code **on the very friggin top** of the main.ts file. Above all other imports. This took me several hours to notice, because I just put them somewhere near the top, but above @angular/core.
