### ISSUE TITLE
ng generate route only creates one file?

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#434]
I am filing a bug. Windows 10. 
````
$ ng --version
angular-cli: 0.0.31
node: 4.4.3
os: win32 ia32
````
I just tested generation of routes, and it doesn't work like documented?

````
 C:\Projects\temp\youjustgo-client
$ ng generate route hero
installing route
  create \src\client\app\hero\hero.ts
````
only one file is created, not all the files as documented?
The hero.ts file just contains one component.

**Comment by Brocco** [comment]
Correct, this is an issue that we're aware of. The routes are currently being implemented to generate the correct files, you can track that via issue #316 and corresponding (in progress as of now pull request #427).

I'm closing this issue in favor of the referenced issue and PR.
