### ISSUE TITLE
[BUG] CLI overwrites base href by default

### ISSUE THREAD

**Issue by MTechDE** [angular/angular-cli#4340]
> Please provide us with the following information:
> ---------------------------------------------------------------
Since beta 28.3, when i use `ng build` or `ng build --prod` , the CLI automaticly overwrites the index.html base href path to '<base href="/">'
I don't want to use now --bh in every build step.

**Update: I also have this problem in Beta 29**

By default, the CLI shouldn't override the base href path.

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here: 

```
angular-cli: 1.0.0-beta.28.3
node: 6.9.4
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/compiler-cli: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Updated angular-cli from beta 26 to beta 28.3

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by kevfuzz** [comment]
I have the exact same problem. Just updated from 26 to 28 and now my base href in the index.html is ignored.

**Comment by medeirosrich** [comment]
Same problem
