### ISSUE TITLE
Set Up the Angular 2 Project - semi-colon (;) in scaffolded scss files extension (*.scss;)

### ISSUE THREAD

**Issue by ericbrunner** [angular/angular-cli#4342]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10 Pro x64, Intel i/-6700 CPU @ 3.40Ghz

### Versions.
>PS C:\dev\ASP.NET-CORE\Telerik\my-first-angular2-project> ng --version
angular-cli: 1.0.0-beta.26
node: 6.9.4
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> I walked throught that [Kendo UI tutorial 
](http://www.telerik.com/kendo-angular-ui/getting-started/) and scaffolded the angular app with that commands:

    npm install -g angular-cli;
    ng new my-first-angular2-project --style=scss;
    cd my-first-angular2-project;

I followed how to add the styles in src/styles.scss and noticed that error when I entered 

    ng serve

### Error

> ERROR in ./src/styles.scss;
Module parse failed: C:\dev\ASP.NET-CORE\Telerik\my-first-angular2-project\src\styles.scss; Unexpected character '@' (3:0)
You may need an appropriate loader to handle this file type.
| /* You can add global styles to this file, and also import other style files */
|
| @import "~@progress/kendo-theme-default/scss/all";
 @ multi ./src/styles.scss;

I saw that all .scss files where scaffolded from angular-cli with a semi-colon in the extension as .scss; .

### Mention any other details that might be useful.

**Workaround:**

After renaming the 

src/styles.scss; => src/styles.scss 
src/app/app.component.scss; => src/app/app.component.scss 

and fixing that same extensions in the **angular-cli.json** file

**before**:

  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "**styles.scss;**"

. . .

  "defaults": {
    "styleExt": "**scss;**",

**after**:

  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "**styles.scss**"

. . .

  "defaults": {
    "styleExt": "**scss**",
all worked well.

**Comment by RicardoVaranda** [comment]
Thanks for reporting this, I'll create a PR in a sec to fix this issue.

**Comment by filipesilva** [comment]
Closing as fixed.
