### ISSUE TITLE
Cannot extend lint process anymore

### ISSUE THREAD

**Issue by sinedied** [angular/angular-cli#4344]
With the release of the `beta28` version and due to [this PR](https://github.com/angular/angular-cli/pull/4248/files), we cannot extend the `ng lint` command which is a serious regression for my projects.

With the previous `beta26`, by changing the `npm scripts` section we could extend the lint process like this:
```
  "scripts": {
    "lint": "tslint \"src/**/*.ts\" \"e2e/**/*.ts\" && stylelint \"src/**/*.scss\" --syntax scss && htmlhint \"src\""
```

Now that this was removed, we cannot extend the behavior of `ng lint` anymore with the addition of `stylelint` and `htmllint`...

This is quite a regression, while I understand the move to the tslint API for better integration, it also complicates the process by hiding it behind JSON settings and kills any customization like the one I was doing. For the meanwhile I'll move my process to use `npm scripts` directly, but it would be nice to find some middle ground on this.

This sort of breaking changes kinda make me worry about the future of `angular-cli`, removing customization features like this are bad in a maintenance update (yeah I understand it's still beta, still).

**Comment by Meligy** [comment]
A few comments, all non official but I understand them having monitored the project for a bit:

- The versioning process will not respect semver before v1.0.0 final.
- The team wants extensibility points to be explicit and planned and optional
  - For v1, full control for the CLI is the direction
  - Extension points (a plug-in system yet to start being defined) planned AFTER v1.0.0.
- tslint is still included as dev dependency. The same npm `lint` script should still work, just not from `ng lint`. Note that the `--lint` option in `ng test` removed (or deprecated if still there).

  It's worth mentioning that I have a project that I just migrated to beta.29. It uses the npm `lint` task directly called from another npm script I created for my CI, and it still works. So, I'm telling this from first hand experience.

**Comment by delasteve** [comment]
@sinedied, as @Meligy mentioned, I don't think that will be a thing should be considered for `1.0@final`. 

Your extension of the `npm` script is an unintended use case as it was intended to only be for `tslint`. When we have the addon system in place (post `1.0@final`), I think you will see additional linting processes available. 

For now, you are still able to use `ng lint` in combination with other linters. 

```json
"scripts": {
  "lint": "ng lint && other-linter-here && other-linter-here"
}
```

You said you do understand it, but I feel it's appropriate to call it out again. This is a beta application. I realize it's sometimes not treated as such, but it hasn't reached rc/final for a reason. There are some features (in this case linting) that aren't fully fleshed out yet.

**Comment by sinedied** [comment]
Ok, so I ended up relying only on npm scripts for now so I can avoid future troubles until `1.0@final` is out, but that sorta kills the `ng` cli idea.

Sorry if I seemed too demanding, but the quality of what you qualify as a `beta` is already *way better* that any other production-ready systems out there for Angular 2 (and even for general frontend development), so you may understand I have high expectations for it :)

I'll way for the addon system, but I really like the idea of extending `ng` commands via simple `npm scripts`, that should be kept in mind for consideration ;)

**Comment by delasteve** [comment]
You're not being demanding at all. It's definitely something to consider and it pays to call out how people were using the `ng lint` command previously. 

That said, I don't think it kills the `ng` cli idea. We're just not at the point of having addons. It's something that's on the radar and having ideas of what addons would be useful will help with the final design of the addon system.

To your last comment, I'll beat the dead horse a little more... addon 😉

**Comment by mmmichl** [comment]
I am having the same issue as my fellow developer and going for the same solution. Just want to drop, that I also _really_ like the simple and straight forward way to extend the functionality via simple npm scripts. E.g. I use a similar approach for `ng server` where I have this start script:
`"start": "ng serve --proxy-config proxy.conf.json & npm run mock-rest"`.

But overall, thank you for your effort! This CLI is awesome and such a help I cannot describe! 👍
