### ISSUE TITLE
@ngtools/webpack v.1.2.6 - not building lazy routes

### ISSUE THREAD

**Issue by unsafecode** [angular/angular-cli#4346]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
`node@6.9.2`
`npm@4.1.2`

`@ngtools/webpack@1.2.6`
`webpack@2.2.0`
`angular@2.4.5`
__not an angular-cli project__

### Repro steps.
After upgrading from v1.2.3 to v1.2.6, all the lazy routes chunks are missing from output. With v1.2.3, they were all included in the main bundle - which was still a mistake, but more manageable.

### The log given by the failure.
No actual failure: other chunks are simply missing in output.

### Mention any other details that might be useful.
`app.routes.ts` format:
```typescript
export const ROUTES: Routes = [
{path: 'lazy', loadChildren: './lazy.module#LazyModule'},
{path: '', component: HomeView}
]
```

**Comment by born2net** [comment]
yes we see the same issue in latest .28-3

**Comment by unsafecode** [comment]
@born2net AFAIK, I was able to fix this by changing the configuration of CommonChunksPlugin, which I originally copied from [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter), this way:

```javascript
		new CommonsChunkPlugin({
			name: 'polyfills',
			chunks: ['polyfills']
		}),
		// This enables tree shaking of the vendor modules
		new CommonsChunkPlugin({
			name: 'vendor',
			chunks: ['main'],
			minChunks: module => /node_modules/.test(module.resource)
		}),
		// Specify the correct order the scripts will be injected in
		new CommonsChunkPlugin({
			name: ['polyfills', 'vendor'].reverse()
		}),
```

__and__ by expliciting writing a vendor.bundle file.

**Comment by splintercode** [comment]
Seeing the same here

**Comment by born2net** [comment]
@unsafecode I am using cli so can't access webpack config
and same issue with .30 as well
if I install ng-tools 1.2.6 manually chunks will be created BUT re-builds do not work

**Comment by filipesilva** [comment]
To the best of my knowledge, this does not happen on the latest release (`1.2.12`).

If you are still experiencing this please open a new issue with a simple repro we can follow. We test the lazy route generation on our test suites, so if it's broken we really need a simple repro to investigate the particulars of your scenario.

**Comment by JohnGalt1717** [comment]
https://github.com/angular/angular-cli/issues/4431 is still an issue that's related to this.
