### ISSUE TITLE
Critical dependency warning during build

### ISSUE THREAD

**Issue by sinedied** [angular/angular-cli#4348]
### OS?
> Mac OSX El Capitan 10.11.6

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.28.3
node: 6.9.4
os: darwin x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
```

### Repro steps.

> Create an app with the CLI, then add `ng-translate` and `@biesbjerg/ng2-translate-po-loader` libraries.

### The log given by the failure.

When building the app, I have this warning:
```
WARNING in ./~/encoding/lib/iconv-loader.js
9:12-34 Critical dependency: the request of a dependency is an expression
```
This warning is not present when using the beta26.

### Mention any other details that might be useful.

Seems that something has changed between beta26 and beta28 regarding the webpack loaders, according to this: https://github.com/webpack/webpack/issues/3078

Apparently, adding a json loader should solve the issue
```
loaders: [
  {test: /\.json$/, loader: 'json-loader'}
]
```

**Comment by filipesilva** [comment]
We now have a json loader included.

**Comment by lahdekorpi** [comment]
I'm still having this with 1.0.1
```
@angular/cli: 1.0.1
node: 7.9.0
os: darwin x64
@angular/animations: 4.0.3
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.1
@angular/compiler-cli: 4.0.3
```

Any ideas?

@sinedied Did you get this working?
