### ISSUE TITLE
Core module changes break compilation

### ISSUE THREAD

**Issue by samalexander** [angular/angular-cli#4353]
### OS?
macOS Sierra (10.12.3)

### Versions.
angular-cli: 1.0.0-beta.28.3
node: 6.9.2
os: darwin x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

### Repro steps.
Our app was created using the angular-cli and has a core module, as documented [here](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#core-module). The app compiles successfully when running `ng serve`. Changes to any files outside of the core module cause the app to recompile, which completes successfully. However, changes to any files inside the core module cause recompilation, which fails with the error below. All subsequent changes that trigger recompilation will then also fail.

I am currently trying to reproduce this in a basic new project. I will link here if successful.

### The log given by the failure.
```
ERROR in ./src/app/core/auth.service.ts
Module build failed: RangeError: Maximum call stack size exceeded
    at Array.filter (native)
    at _diagnoseDeps (/Users/sam/Developer/ng-project/node_modules/@ngtools/webpack/src/loader.js:261:10)
    at /Users/sam/Developer/ng-project/node_modules/@ngtools/webpack/src/loader.js:264:9
    at Array.forEach (native)
    at _diagnoseDeps (/Users/sam/Developer/ng-project/node_modules/@ngtools/webpack/src/loader.js:262:10)
    at /Users/sam/Developer/ng-project/node_modules/@ngtools/webpack/src/loader.js:264:9
    at Array.forEach (native)
    at _diagnoseDeps (/Users/sam/Developer/ng-project/node_modules/@ngtools/webpack/src/loader.js:262:10)
    at /Users/sam/Developer/ng-project/node_modules/@ngtools/webpack/src/loader.js:264:9
    at Array.forEach (native)
***repeated a few hundred times, removed for brevity***
 @ ./src/app/app.component.ts 13:0-50
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
```

### Mention any other details that might be useful.
We believe this issue has been introduced by angular-cli v1.0.0-beta.28.3, since it works with v1.0.0-beta.26.

**Comment by clydin** [comment]
The underlying cause is a circular dependency involving the file mention in the error.

There were some changes in diagnostics reporting that make it sensitive to circular dependencies.

**Comment by samalexander** [comment]
Thanks for the heads up @clydin. 

Currently struggling to see where the circular dependency is being introduced. The auth service only injects a couple of dependencies (see below), none of which reference the auth service.

```
constructor(
    private authHttp: AuthHttp,
    private zone: NgZone,
    private router: Router
  ) { }
```

Any ideas?

**Comment by Jonatthu** [comment]
It is happening to me when is recompiling :/

**Comment by fulcircle** [comment]
We're experiencing the same issue.  Is there a version number for webpack where this was not an issue, so we can force it to that version in package.json until this is resolved?

**Comment by jschwarty** [comment]
We see this issue happening with the @ngtools/webpack version 1.2.5 that dropped. We ended up doing an
```
npm i -D @ngtools/webpack@1.2.4
```
to force the version back for the time being so we can get our stuff working until this is figured out.

**Comment by intellix** [comment]
@ngtools/webpack@1.2.6 is out btw

**Comment by samalexander** [comment]
@intellix I am still experiencing the same issue with `@ngtools/webpack@1.2.6`

**Comment by jschwarty** [comment]
@intellix Same...still experiencing the same issue with @ngtools/webpack@1.2.6

**Comment by Jonatthu** [comment]
@jschwarty  after do npm i -D @ngtools/webpack@1.2.4
Now is working normally :/

**Comment by jschwarty** [comment]
`@ngtools/webpack@1.2.7` solved it for us. Thank you!

**Comment by lebnic** [comment]
Hi all; I'l experiencing the same problem; Can you tell me how to solve the issue? Do I simply need to re-install with npm install?

**Comment by MRamos62786** [comment]
@jschwarty, When you say that version 1.2.7 solved it. Do you mean you have a locally built copy of the angular cli that you updated to use this version? Or am I misunderstanding?

**Comment by jschwarty** [comment]
@MRamos62786 I did an install of that specific version of @ngtools/webpack
```
npm i @ngtools/webpack@1.2.7
```
That ensured that the @ngtools/webpack in my node_modules was that version.

**Comment by bviale** [comment]
The webpack downgrade fix doesn't work anymore : "Cannot read property 'newLine' of undefined" occured when trying to `ng build`

**Comment by naveenkumarkg19** [comment]
When I run ng serve I can see my webpage reflected with changes . But when ng serve is on auto build and I try to make changes in the html or ts files the auto compiling of ng serve breaks and keeps repeating . Tried to re install node modules and also did n "pm i -D @ngtools/webpack@1.2.4" now it shws errors in the console . Inorder for me to see the changes I need to break manually ctrl + c and do a ng serve again
