### ISSUE TITLE
UNMET PEER DEPENDENCY rxjs@^5.0.1 during npm install 1.0.0-beta.28.3

### ISSUE THREAD

**Issue by AlainD-** [angular/angular-cli#4357]
Hi, I am trying to update my angular-cli, but I get this error during the installation, I don't know who's responsible for it (angular-cli or angular): `UNMET PEER DEPENDENCY rxjs@^5.0.1`

### OS?
- Windows 7
- Mac OSX (El Capitan)

### Versions.
angular-cli: 1.0.0-beta.28.3
node: 7.2.1
os: win32 x64

### Repro steps.
Reproducible on 2 machines (Mac and Windows) during `npm install -g angular-cli@latest` which is supposed to install with version of angular 2.4.5

### The log given by the failure.
```
  +-- rsvp@3.3.3
  +-- UNMET PEER DEPENDENCY rxjs@^5.0.1
  +-- sass-loader@4.1.1

...

npm WARN @angular/core@2.4.5 requires a peer of rxjs@^5.0.1 but none was installed.
```

### Mention any other details that might be useful.
When I install manually `npm install -g rxjs` it correctly installs rxjs
```
`-- rxjs@5.1.0
  `-- symbol-observable@1.0.4
```

**Comment by deebloo** [comment]
it is a warning not an error. It all has to do with how the cli configures its dependencies and is something you will only get when installing globally as when you install locally your project will include rxjs. I

**Comment by AlainD-** [comment]
OK, sorry for the ticket then. Can be closed if there nothing to do with it then.
Thank you for the info anyway.

**Comment by RicardoVaranda** [comment]
Another point just to make you aware is that the cli has recently changed project names when installing from npm to get the latest beta.29 do the following:

```
npm uninstall -g angular-cli
npm clear cache
npm install -g @angular/cli
```

**Comment by AlainD-** [comment]
Yes I just realised that when running the ng serve command through the forewarning message :-)
Thanks a lot, I appreciate your concern.

**Comment by JediSange** [comment]
I actually just got this issue from a fresh install. The homepage seems to say to use the old version (`angular-cli`) -- https://cli.angular.io/. But I got the deprication warning from the command line and followed similar steps to what you outlined @RicardoVaranda. However, now when I try to run `ng help` from any arbitrary point in my terminal, I get outcome that looks like this...

```
user-33:workspace user.user$ npm install -g @angular/cli
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng
/usr/local/lib
└─┬ @angular/cli@1.0.0-beta.29
  └── UNMET PEER DEPENDENCY rxjs@^5.0.1

npm WARN @angular/core@2.4.5 requires a peer of rxjs@^5.0.1 but none was installed.
user-33:workspace user.user$ ng help
Cannot find module 'rxjs/Subject'
Error: Cannot find module 'rxjs/Subject'
```

Followed by a very verbose stack trace. I wound up editing out my real name and substituting 'user', but otherwise that is how it reads.

**Comment by JediSange** [comment]
Update here: It looks like it only happens on `ng help`. My issue is summarized by #4363.

**Comment by didymu5** [comment]
ditto @JediSange

**Comment by eaktadiur** [comment]
I also have UNMET PEER DEPENDENCY rxjs@^5.0.1 issue

└─┬ @angular/cli@1.0.0-beta.30 
  ├─┬ autoprefixer@6.7.2
  │ └── caniuse-db@1.0.30000621 
  ├─┬ node-sass@4.5.0
  │ └─┬ meow@3.7.0
  │   └─┬ normalize-package-data@2.3.5
  │     └── hosted-git-info@2.2.0 
  ├── UNMET PEER DEPENDENCY rxjs@^5.0.1
  └─┬ webpack@2.2.0
    └── acorn@4.0.9

**Comment by kimwer** [comment]
Same here. As a result every usage of RXJS in our project leads to an error because of the missing dependency. As a workaround we switched back to 1.0.0-beta.26 for the moment.

**Comment by AlainD-** [comment]
Or, as a workaround, you can install rxjs globally prior to @angular/cli and still benefit from the new module.

**Comment by vivian7169** [comment]
I tried 'npm install -g rxjs ' before or after 'npm install -g @angular/cli@1.0.0-beta.29', both can't solve the issue >>> 
└─┬ @angular/cli@1.0.0-beta.29 
  └── UNMET PEER DEPENDENCY rxjs@^5.0.1

**Comment by d3lm** [comment]
I have the same issue. I was trying to update my angular-cli to the latest version by uninstalling the pervious version and installing the new one via `npm i -g @angular/cli`. The installation ends with a warning. However, if I then list my global packages using `npm list -g --depth=0` I get the following error:

```
npm ERR! peer dep missing: rxjs@^5.0.1, required by @angular/core@2.4.6
npm ERR! extraneous: tsickle@0.2.5 /usr/local/lib/node_modules/@angular/cli/node_modules/@angular-cli/ast-tools/node_modules/tsickle
```

I also can't run `ng help` which results in the following error:

```
Cannot find module 'rxjs/symbol/observable'
Error: Cannot find module 'rxjs/symbol/observable'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
...
```

So essentially the angular-cli doesn't work globally right now. It works locally when I execute it using `./node_modules/angular-cli/bin/ng serve`.

**Comment by reminvestor** [comment]
anyone figure out this issue?

**Comment by d3lm** [comment]
@reminvestor There was actually a commit that fixed the unmet peer dependency error. However, if you update to the latest version you'll probably run into different errors. But give it a try. I have already filed a new issue for beta.31 https://github.com/angular/angular-cli/issues/4583

**Comment by filipesilva** [comment]
Fixed in beta.31.

**Comment by sooyoung32** [comment]
@filipesilva Hi. I installed the latest angular-cli (@angular/cli@1.0.0-beta.31). Now I can not see 'unmet peer dependency rejs@5.1.0' but it shows now "
 @angular/cli@1.0.0-beta.31
  ├── UNMET PEER DEPENDENCY @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0
  ├── UNMET PEER DEPENDENCY @angular/compiler-cli@^2.3.1 || >=4.0.0-beta <5.0.0
  ├── UNMET PEER DEPENDENCY @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0
  ├── UNMET PEER DEPENDENCY @angular/tsc-wrapped@^0.5.0"

i am using node version 7.5.0 and my npm version is 4.1.2

is that okay?

**Comment by AlainD-** [comment]
@sooyoung32 You should have read the comments before posting. You would have noticed then that @d3lm already pointed that out, and following the link you would have realised that the point is already covered in the issue #4575 :-)

**Comment by AntonioNieto92** [comment]
The answer by **RicardoVaranda** works perfectly:

Another point just to make you aware is that the cli has recently changed project names when installing from npm to get the latest beta.29 do the following:

npm uninstall -g angular-cli
npm clear cache
npm install -g @angular/cli

**Comment by davidlwatsonjr** [comment]
Minor pedantic note: `npm cache clear`. So:

```
npm uninstall -g angular-cli
npm cache clear
npm install -g @angular/cli
```

**Comment by dannyserena** [comment]
Ok. I follow the steps
```
npm uninstall -g angular-cli
npm cache clear
npm install -g @angular/cli
```
 and in my case the problem of cli to ionic 2 still persists, any suggestions? I need to run the command and I can not get past it: `npm install angularfire2 firebase --save`

**Comment by dannyserena** [comment]
I follow the steps 
```
npm uninstall -g angular-cli
npm cache clear
npm install -g @angular/cli
```
and in my case the problem of cli to ionic 2 still persists, any suggestions? I need to run the command and I can not get past it:` npm install angularfire2 firebase --save`

**Comment by befikirhm** [comment]
I got Changing the target on tsconfig.json from "es5" to "es6" solved my problem.

**Comment by SebastienCoste** [comment]
When I have an unmet peer dependency on packX while installing packY I add packX like this and everything works : 
> sudo install -g grunt-cli bower yo packX packY

**Comment by maiasmith** [comment]
running `npm update` in the same directory as my package.json worked for me.

**Comment by agrpriyal** [comment]
i was facing unmet peer dependancy of rxjs and zone.js .
This issue got resolved for me. Steps I followed:
1. npm update
2. npm -g ls --depth=0
3. removed the angular/core because that was not required for my project. i just needed angular cli.
4. repeated the second step again and all the issues got resolved.

**Comment by ketansahils** [comment]
It is quite strange that to update angular cli, we uninstall it first, clear cache and wait for an excruciatingly long time to install it again.

**Comment by amritsubedi** [comment]
I got the same error over and over while trying to install ionic. This hopefully works for angular/cli too.
I resolved it by following:
1. npm install -g rxjs@6
2. npm run reinstall
