### ISSUE TITLE
bug: component relative path generation on windows: \\

### ISSUE THREAD

**Issue by HJHorst** [angular/angular-cli#436]
When generating a component in a subfolder on windows, the url in templateUrl en styleUrls is not correct: \\ should be /.

1. OS. Windows 7

2. Versions.
angular-cli: 0.0.31
node: 4.2.6
os: win32 x64

3. Repro steps. 
Generate a component in subfolder of app:
ng g component feature/new-component

In new-component.ts:
```
  templateUrl: 'app\\feature/new-component/new-component.html',
  styleUrls: ['app\\feature/new-component/new-component.css'],
```

This leads to failed tests:
```
Chrome 48.0.2564 (Windows 7 0.0.0) NewComponent Component should ... FAILED
        Failed: Failed to load app%5Cfeature/new-component/new-component.html
            at C:/workspaces/angular2/cli-test/node_modules/angular2/bundles/tes
ting.dev.js:2059:20

```

**Comment by Brocco** [comment]
Having the paths in these attributes will be going away when aligning with the style guide, you can follow the progress of that implementation in issue #316.

Closing this issue in favor of the mentioned issue.
