### ISSUE TITLE
ng github-pages:deploy Fails with "Error: 401 Unauthorized"

### ISSUE THREAD

**Issue by priyeshn** [angular/angular-cli#4362]
> ---------------------------------------------------------------
Trying to push to GH pages using ng deploy .And it i asking to enter GitHub token , but it is failing with authorization error . Below is the screen shot of ng deploy . How to stop ng deploy from asking for token, or hw to resolve the token issue

*******************
ng github-pages:deploy  
 
undefined
In order to deploy this project via GitHub Pages, we must first create a repository for it.
It's safer to use a token than to use a password so you will need to create one
Go to the following page and click "Generate new token".
https://github.com/settings/tokens

Choose "public_repo" as scope and then click "Generate token".

? Please enter GitHub token you just created (used only once to create the repo): <Token Masked>
? and your GitHub user name: <user ID>

Failed to create GitHub repo. Error: 401 Unauthorized

*******************

**OS**
OSX E l Capitan

**ng Version**
angular-cli: 1.0.0-beta.28.3
node: 6.6.0
os: darwin x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
