### ISSUE TITLE
Proposal: add server config for static mocks via webpack-dev-server

### ISSUE THREAD

**Issue by kdimatteo** [angular/angular-cli#4367]
When developing large apps which require many static mocks, we need to run a separate instance of a server so that we can proxy API calls so an endpoint which return known results.

Since `ng serve` already invokes `webpack-dev-server`, we just need a way to pass a `setup()` method ([webpack docs](https://webpack.github.io/docs/webpack-dev-server.html#api)) to handle the routing.

...this save us from spinning up a second server.
 
[PR is open](https://github.com/angular/angular-cli/pull/3661), hoping to get some perspective whether this approach makes sense.

**Comment by filipesilva** [comment]
Closing with reasoning on https://github.com/angular/angular-cli/pull/3661#issuecomment-279787418.

The proxy docs can be found at https://github.com/angular/angular-cli/wiki/stories-proxy.

**Comment by eikishi01** [comment]
I'm thinking that maybe the reason given in #3661 is a different use case, yeah you can add proxies to the configuration to point to ANOTHER api server how ever I also consider it an overkill to create a server instance to serve simple JSON when you already have a running server with ng serve and you just need to add the paths mapping with the setup method already available in webpack-dev-server
