### ISSUE TITLE
cli.angular.io references old npm package name

### ISSUE THREAD

**Issue by delasteve** [angular/angular-cli#4369]
<img width="388" alt="screen shot 2017-02-02 at 2 31 46 pm" src="https://cloud.githubusercontent.com/assets/595925/22564942/68b94c8e-e954-11e6-9814-b927b08fa334.png">

**Comment by hansl** [comment]
Yes we're doing a pass of renaming/branding. The cli.angular.io will be changed soon.

**Comment by hansl** [comment]
cc @StephenFluin @robwormald @IgorMinar

**Comment by hansl** [comment]
Fixes: https://github.com/angular/microsites/pull/6, https://github.com/angular/microsites/pull/7

**Comment by filipesilva** [comment]
Fixed by angular/microsites#6, angular/microsites#7.
