### ISSUE TITLE
ng build -w endless loop

### ISSUE THREAD

**Issue by dsoltesz** [angular/angular-cli#4376]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7
### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

1.0.0-beta.28.3

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

run command "ng build -w"  everything will compile fine and watch is running.  Then make a change to a file and save, will go into a long loop for awhile and then finally just sit there

if I just run ng build --dev everything works correctly

### The log given by the failure.
> Normally this include a stack trace and some more information.
its does this loop numerous times before finally just ending

 at _diagnoseDeps (C:\VPS\Source\QA1\Fng.Vps.Portal.Web\Client\node_modules\@
ngtools\webpack\src\loader.js:262:10)
    at C:\VPS\Source\QA1\Fng.Vps.Portal.Web\Client\node_modules\@ngtools\webpack
\src\loader.js:264:9
    at Array.forEach (native)
    at _diagnoseDeps (C:\VPS\Source\QA1\Fng.Vps.Portal.Web\Client\node_modules\@
ngtools\webpack\src\loader.js:262:10)
    at C:\VPS\Source\QA1\Fng.Vps.Portal.Web\Client\node_modules\@ngtools\webpack
\src\loader.js:264:9
    at Array.forEach (native)
    at _diagnoseDeps (C:\VPS\Source\QA1\Fng.Vps.Portal.Web\Client\node_modules\@
ngtools\webpack\src\loader.js:262:10)
    at C:\VPS\Source\QA1\Fng.Vps.Portal.Web\Client\node_modules\@ngtools\webpack
\src\loader.js:264:9
    at Array.forEach (native)
    at _diagnoseDeps (C:\VPS\Source\QA1\Fng.Vps.Portal.Web\Client\node_modules\@
ngtools\webpack\src\loader.js:262:10)
    at C:\VPS\Source\QA1\Fng.Vps.Portal.Web\Client\node_modules\@ngtools\webpack
\src\loader.js:264:9
    at Array.forEach (native)
    at _diagnoseDeps (C:\VPS\Source\QA1\Fng.Vps.Portal.Web\Client\node_modules\@
ngtools\webpack\src\loader.js:262:10)
    at C:\VPS\Source\QA1\Fng.Vps.Portal.Web\Client\node_modules\@ngtools\webpack
\src\loader.js:293:21
 @ ./src/app/components/+programs/edit/containers/production/program-episode-dyn
amic-props.ts 2:29-87
 @ ./src/app/components/+programs/edit/containers/production/productioncycles/pa
nels/episodes.production-cycles.component.ts
 @ ./src/app/components/+programs/edit/index.ts
 @ ./src/app/components/+programs/edit/program-edit-routing.module.ts
 @ ./src/app/components/+programs/edit/program-edit.module.ts
 @ ./src async
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi ./src/main.ts

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by splintercode** [comment]
Just ran into this as well on the same version latest CLI

**Comment by dsoltesz** [comment]
working in @angular/cli 1.0.0-beta.30

**Comment by vtsoft** [comment]
I have the same problem. when I execute "ng build -w" or "ng build" it only generate 2 files: favicon.ico and index.html excluding the needed files below:

inline.bundle.js
inline.bundle.js.map
polyfills.bundle.js
polyfills.bundle.js.map
styles.bundle.js
styles.bundle.js.map
vendor.bundle.js
vendor.bundle.js.map
main.bundle.js
main.bundle.js.map

I think there's a configuration missing on this which I don't know. Please help advise... Thanks in advance.
