### ISSUE TITLE
"You have to be inside an angular-cli project in order to use the  build command." due to global and local cli version being out of sync

### ISSUE THREAD

**Issue by wardbell** [angular/angular-cli#4379]
note: this was filed by @IgorMinar from wards computer, so blame @IgorMinar for any pain this issue has caused to you.

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

MacOS

### Versions.

global:
```
$ ng version

@angular/cli: 1.0.0-beta.29
node: 6.9.5
os: darwin x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
```

local:
```
$ $(yarn bin)/ng version

angular-cli: 1.0.0-beta.28.3
node: 6.9.5
os: darwin x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

```
$ ng build
You have to be inside an angular-cli project in order to use the
 build command.
```

but if I do:
```
$ $(yarn bin)/ng build
.... works just fine ....
```

**Comment by wardbell** [comment]
fyi, to resolve this problem we did the following:

```
yarn remove angular-cli
yarn add @angular/cli --dev
```

**Comment by beeman** [comment]
@wardbell the local package.json should be updated to have `"@angular/cli": "^1.0.0-beta.29",` instead of `"angular-cli": "1.0.0-beta.28.3"`.

**Comment by victorblq** [comment]
does not work here, still having the error

**Comment by beeman** [comment]
@victorblq can you remove `node_modules` and `npm install` ?

**Comment by victorblq** [comment]
I fix changing the package.json file this way:
from:
```
 "devDependencies": {
    "@angular/compiler-cli": "2.4.5",
    "angular-cli": "1.0.0-beta.26",
    ...
```
to:
```
"devDependencies": {
    "@angular/cli": "1.0.0-beta.29",
    "@angular/compiler-cli": "^2.3.1",
    ...
```

and the angular-cli.json like @hansl said.
After that `rm -rf node_modules` and `npm install` and `ng serve` works.
I don't know if it's relevant, but I did it all in a existing project, not a new one.

**Comment by beeman** [comment]
@victorblq yep, only existing packages (created by `angular-cli`, ran with`@angular/cli` are affected). 

The next beta adds support for both though.

**Comment by azollai** [comment]
You should run "npm install -g @angular/cli@latest". It solved for me.

**Comment by naveennavi2106** [comment]
@azollai Thanks

**Comment by ramanimukesh** [comment]
Yes this worked for me as well thanks
 npm install -g @angular/cli@latest
