### ISSUE TITLE
Not compile files ts

### ISSUE THREAD

**Issue by kamalkech** [angular/angular-cli#4383]
### OS?
> Windows 10

### Versions.
angular-cli: 1.0.0-beta.28.3
node: 6.9.4
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

### Repro steps.
> after update code files ts webpack not compile this files, but work fine for files html

### The log given by the failure.
typescript not compiled

**Comment by kuncevic** [comment]
temporary fix `npm install @ngtools/webpack@1.2.4`

**Comment by Ledzz** [comment]
Still have this issue in 1.0.0-beta.30

**Comment by DaveXCS** [comment]
same here with 1.0.0-beta.30. Temporary fix from kuncevic is working.

**Comment by splintercode** [comment]
Still having this issue in 1.0.0-beta.30 as well

**Comment by kzay** [comment]
Bad bug for productivity!

**Comment by kamalkech** [comment]
try with : npm install @ngtools/webpack@1.2.4

**Comment by Jonatthu** [comment]
After change a file the website is not reloading with "@ngtools/webpack": "^1.2.5",
Why is this closed?

**Comment by kamalkech** [comment]
@Jonatthu : first update your angular-cli to get last version if reload not work install @ngtools/webpack@1.2.4

**Comment by DaveXCS** [comment]
But even if a fix exist by downgrade/upgrade a dependency it is still a bug with priority high or blocker.
So it shouldn't be closed until it is fixed isn't it?
Latest version is still beta30 with this bug.

**Comment by kuncevic** [comment]
@DaveXCS the but has being fixed with `@ngtools/webpack@1.2.8` https://github.com/angular/angular-cli/commit/9fcf10a89b0995c2da606fbbe5a341d42044654b
