### ISSUE TITLE
style bundles not created with dev build but works correctly with prod build

### ISSUE THREAD

**Issue by dsoltesz** [angular/angular-cli#4388]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-beta.30
node: 6.9.5
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
@angular/flex-layout: 2.0.0-beta.4
@angular/cli: 1.0.0-beta.30

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

`ng build --dev `

no style.bundle.css or inline styles, site looks broken, 
dev tools network tab no style.bunde.css and no link created in index.html

`ng build --prod`

dev tools network tab styles.9fcf67e3836bcf7b5c7f.bundle.css is loaded and link is created in index.html

`<link href="styles.9fcf67e3836bcf7b5c7f.bundle.css" rel="stylesheet"/>`

### The log given by the failure.
> Normally this include a stack trace and some more information.

This was an existing site that I just updated to @angular/cli: 1.0.0-beta.30

angular-cli.json styles
```

"styles": [
        "styles.css",
        "../node_modules/font-awesome/css/font-awesome.css",
        "../node_modules/primeng/resources/primeng.css",
        "../../Content/scss/styles.css"
      ],
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by cacogr** [comment]
https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#breaking-changes

`build: - --extractCss defaults to false on all --dev (ng build with no flags uses --dev)`

**Comment by dsoltesz** [comment]
Thanks, missed that somehow
