### ISSUE TITLE
route-config.ts is not created

### ISSUE THREAD

**Issue by vapits** [angular/angular-cli#439]
1. OS. El Capital (but also on Win 10)
2. Versions. 
    angular-cli: 0.0.31
    node: 5.10.1

Hi there,
amazing tool!

I'm (and my team) having the following issue.
When we are generating a new ***route*** then the ***route-config*** file is never created. Even with thin the other created files (component etc) the Routeconfig stays empty.

I didn't manage to find something that explains that here on as I tried to make it work.

Any ideas? Is this a known behaviour or bug? The docs doesn't provide such info.

**Comment by hansl** [comment]
The CliRouterConfig has been deprecated in favor of updating the parent route source file instead.

Are you on 0.0.31?  You can safely delete that file now and remove its import and usage in your routes.

**Comment by vapits** [comment]
@hansl Yes I'm on the 0.0.31.
So based to the docs, when I'm generating a new route what should I expect?
Just the files so I have to go and create the route config for each route? Then what is the purpose of generating new route?

**Comment by Brocco** [comment]
@vapits the generation of routes has been and currently is a pain point. This has been addressed in PR #427 and will continue to be refined. You can take advantage of this by working off of a local version of this repo, or await the next release of the CLI to npm.

**Comment by vapits** [comment]
Thx @Brocco for your answer.

PR is closed though, still have thoughts on the implementation? Can I help somehow?

**Comment by Brocco** [comment]
@vapits the PR is closed because it was merged in. I do appreciate the offer for help though 🎉👍
