### ISSUE TITLE
CSS incorrect ordering

### ISSUE THREAD

**Issue by phil-cap** [angular/angular-cli#4392]
The CSS is being applied in the incorrect order.
I have in `styles.css` the following

> @font-face {
  font-family: 'SomeFont';
  src: url('./assets/some-font.woff') format('woff');
}
\* {
  font-family: 'SomeFont';
} 

My `angular-cli.json` file is
> "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.css",
        "styles.css"
      ],

However, the resulting CSS is such that the Bootstrap font family overwrites my custom font. Changing the order does not have an impact.

I am using Windows 7 with ng version `1.0.0-beta.26`.

**Comment by phil-cap** [comment]
@RicardoVaranda thanks for your efforts! That is very strange because i have the exact same scenario with a different result.  I have resolved the issue by specifying the `*` selector at each component's CSS style file. Its an ugly solution however. Are you using production ready code? I only end up with a single styles file after using the `prod` command of `angular-cli`. Perhaps that plays a role... I will have another look at my set up and prepare a Plunker.

**Comment by filipesilva** [comment]
Closing as answered by @RicardoVaranda.

**Comment by dev008webO** [comment]
hello @RicardoVaranda . well in mycase,
