### ISSUE TITLE
angular-cli closes Windows cmd command line console terminal

### ISSUE THREAD

**Issue by martinmcwhorter** [angular/angular-cli#4396]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.28.3
node: 6.9.2
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/flex-layout: 2.0.0-beta.4
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

* Open a Windows CMD.exe console
* type in `ng --version` and hit enter. 

The command line console window will close immediately. 

This is also reproducible in the:
* terminal in VSCode
* terminal in IntelliJ
* Git CMD 

This is NOT reproducible in Git Bash on Windows. Using Git Bash has been an acceptable workaround for me. I suspect it would not be acceptable to everyone.  

### The log given by the failure.
> Normally this include a stack trace and some more information.

none

### Mention any other details that might be useful.

The Angular-Cli is a fantastic tool. The rebuild speed and bundle size keep getting smaller and smaller. Great job. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by martinmcwhorter** [comment]
This issue went away when I upgraded to beta.30

**Comment by filipesilva** [comment]
Heya @martinmcwhorter nice to find you again here! I'm glad the issue went away and that you're enjoying the CLI.
