### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular-cli#4397]
Hello,

I'm willing to create a Progressive Web App with Angular CLI but I realized you removed the outdated "-mobile" parameter in the latest build.

Do you still plan to support PWA ?

Thank you.

**Comment by splintercode** [comment]
I think there are still plans for the Mobile Toolkit and Universal once the plugin system is in place. Until then you can get some aspects of PWA working with the CLI by extending the npm scripts 
https://coryrylan.com/blog/fast-offline-angular-apps-with-service-workers

**Comment by alfredoperez** [comment]
@splintercode Awesome post! do you have any idea how to use the app-shell?

**Comment by Ploppy3** [comment]
@splintercode Thank you for the blog post.

**Comment by filipesilva** [comment]
Closing as answered by @splintercode.
