### ISSUE TITLE
Errors on ng new with bower & angular router.

### ISSUE THREAD

**Issue by Nopzen** [angular/angular-cli#44]
When running ng new myproject you will get this:

`bower angular-route#* ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular-route.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.128]: errno=Operation timed out`

still succeeds, then running: ng serve gives you this expected result:
`Module not found: Error: Cannot resolve module 'angular-route'`

when then trying to run a bower i angular-route --save:
`bower angular-deferred-bootstrap#~0.1.5 ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/philippd/bower-angular-deferred-bootstrap.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.130]: errno=Operation timed out`

**Comment by cironunes** [comment]
Which version of Node do you have? Make sure to use v4.

**Comment by Nopzen** [comment]
node -v
0.12.5

**Comment by cironunes** [comment]
So you'll need to install v4 to be able to run `angular-cli`.

**Comment by Nopzen** [comment]
Giving it a go, comming back if issue is stil there :)

**Comment by Nopzen** [comment]
Fixed the issue thanks @cironunes .
