### ISSUE TITLE
Generate new component template and style path issue

### ISSUE THREAD

**Issue by vapits** [angular/angular-cli#440]
![image](https://cloud.githubusercontent.com/assets/8594758/14557309/f0fd440e-02fc-11e6-9672-fd7d1a4f120e.png)

When I'm creating a new component the `templateUrl` and `styleUrls` have a double slash after app folder.

Is this expected behaviour?

OS. El Capital (but also on Win 10)
Versions. angular-cli: 0.0.31 node: 5.10.1

**Comment by PascalPrecht** [comment]
This happens when your folder structure is still the one that was used before `0.0.30`

It's not `src/client/app` not `src/app`

**Comment by vapits** [comment]
I see. I never used 0.30 though. This project just created with 0.0.31.

**Comment by PascalPrecht** [comment]
What's the version of your global angular-cli installation?

**Comment by vapits** [comment]
0.0.31

**Comment by PascalPrecht** [comment]
Hm.. okay leaving this here as it seems related: https://github.com/angular/angular-cli/issues/340

**Comment by hansl** [comment]
@Brocco: is this going to be solved by your Styleguide PR?

**Comment by Brocco** [comment]
@hansl yes, this will be handled via PR #427 which is currently being reviewed.

**Comment by Brocco** [comment]
PR #427 has been merged, closing this issue
