### ISSUE TITLE
Is it possible to let build continue when there is an error?

### ISSUE THREAD

**Issue by zh-wowtv** [angular/angular-cli#4401]
I got an error when I'm running `ng serve` for a newly created project after adding `ng2-smart-table`:

> ERROR in /Users/Projects/myapp/node_modules/ng2-smart-table/src/ng2-smart-table/lib/data-source/server/server.data-source.ts (70,12): Type 'Observable<Response>' is not assignable to type 'Observable<any>'.
>   Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.)

By looking through the source code, I found the code causes error has not been called by my project at all. But the project stop running because of the compiling error. For a temp solution, is it possible to let my app continue even when there is webpack compiling error ? Thanks.

**Comment by grizzm0** [comment]
Could be a mismatch between versions. Try deleting node_modules and run install again.

**Comment by clydin** [comment]
The library should be using a peerDep for `rxjs` not a direct dependency.

**Comment by zh-wowtv** [comment]
@grizzm0 Did that a few times already.
@clydin Can you explain more on peerDep? How I can deal with this? Thanks.

**Comment by clydin** [comment]
`ng2-smart-table`'s package.json contains this:
```
  "dependencies": {
    "ng2-completer": "^1.0.0",
    "rxjs": "~5.0.2"
  },
```
but `rxjs` should be here instead:
```
  "peerDependencies": {
    "@angular/common": "2.4.4",
    "@angular/compiler": "2.4.4",
    "@angular/core": "2.4.4",
    "@angular/forms": "2.4.4",
    "rxjs": "^5.0.2"
  },
```

**Comment by zh-wowtv** [comment]
@clydin It works, thank you so much!

**Comment by filipesilva** [comment]
Closing as answered, thanks @grizzm0 and @clydin!
