### ISSUE TITLE
[feature-needed ?] How can I use typedoc in my angular-cli generated project ?

### ISSUE THREAD

**Issue by wandroll** [angular/angular-cli#4403]
> Hello,
> I've tried to use typedoc on my project but since angular-cli relies on webpack, I needed to override the webpack config to add a dedicated plugin to integrate typedoc.

>Since webpack config is not accessible in angularcli projects , it would be nice to be able to generate project documentation in the future.

_( If you know how I could do this on my own, please enlight me and I'll propose a pull request)_

**Comment by zacol** [comment]
Follow this step:
1) Install Typedoc globally with this command `npm install --global typedoc`.
2) Add `typedoc.json` with Typedoc configuration:

```json
{
  "mode": "modules",
  "out": "doc",
  "theme": "default",
  "ignoreCompilerErrors": "true",
  "experimentalDecorators": "true",
  "emitDecoratorMetadata": "true",
  "target": "ES5",
  "moduleResolution": "node",
  "preserveConstEnums": "true",
  "stripInternal": "true",
  "suppressExcessPropertyErrors": "true",
  "suppressImplicitAnyIndexErrors": "true",
  "module": "commonjs"
}
```
3) Add these two lines to the `package.json`:

```json
"docs": "npm run typedoc -- --options typedoc.json --exclude '**/*.spec.ts' ./src/",
"typedoc": "typedoc"
```

4) Now you can run Typedoc using `npm run docs`.

Have fun with Typedoc :)

**Comment by filipesilva** [comment]
@zacol thanks for the detailed writeup!

**Comment by luismiguelbravo** [comment]
hello, I have this problem when I hit npm run docs.

You must either specify the 'out' or 'json' option

![image](https://user-images.githubusercontent.com/5140529/34389638-971744d8-eb19-11e7-8564-020a5747f301.png)

**Comment by mooziedog** [comment]
i had same problem. but i solved this way.
"docs": "typedoc --json typedoc.json --exclude '**/*.spec.ts' ./src/"

**Comment by sevenlol** [comment]
@luismiguelbravo If you are using typedoc `0.9.0`, there is an [issue](https://github.com/TypeStrong/typedoc/issues/604) saying `--options typedoc.json` is broken on this version. 

Replacing `typedoc.json` with `typedoc.js` works for me. 
1. Add `typedoc.js` with the same configuration

```javascript
module.exports = {
  mode: 'modules',
  out: 'doc',
  theme: 'default',
  ignoreCompilerErrors: true,
  excludePrivate: true,
  excludeNotExported: 'true',
  target: 'ES5',
  moduleResolution: 'node',
  preserveConstEnums: 'true',
  stripInternal: 'true',
  suppressExcessPropertyErrors: 'true',
  suppressImplicitAnyIndexErrors: 'true',
  module: 'commonjs'
};
``` 
2. Change the corresponding command in `package.json`

`"docs": "npm run typedoc -- --options typedoc.js --exclude '**/*.spec.ts' ./src/",`

Hope this helps.

**Comment by luismiguelbravo** [comment]
work perfect
