### ISSUE TITLE
Generating Routing Module ignores "spec"-setting in angular-cli.json

### ISSUE THREAD

**Issue by Springrbua** [angular/angular-cli#4404]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-beta.30
node: 7.3.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

1. Create an app using the "--skip-tests" flag, or set all specs in the angular-cli.json to "false":
```
    "spec": {
      "class": false,
      "component": false,
      "directive": false,
      "module": false,
      "pipe": false,
      "service": false
    }
```

2. Generate a new routing module using "ng g module test --routing"

### Expected output/files generated.
```
installing module
  create src\app\test\test-routing.module.ts
  create src\app\test\test.module.ts
installing component
  create src\app\test\test.component.scss
  create src\app\test\test.component.html
  create src\app\test\test.component.ts
  update src\app\test\test.module.ts
```
### Actual output/files generated.
```
installing module
  create src\app\test\test-routing.module.ts
  create src\app\test\test.module.ts
installing component
  create src\app\test\test.component.scss
  create src\app\test\test.component.html
  create src\app\test\test.component.spec.ts    <------- This file shouldn't be generated
  create src\app\test\test.component.ts
  update src\app\test\test.module.ts
```

### Mention any other details that might be useful.
Note the generated "test.component.spec.ts" file.  
I would expect, that no "spec.ts"-File is generated, when the spec-generation for Components is disabled inside the angular-cli.json

**Comment by Springrbua** [comment]
It seems like the "inline-style" and "inline-template" setting is ignored to. The ".html" and ".css" will always be generated.

**Comment by filipesilva** [comment]
We don't generate a component with a routing module anymore, so this shouldn't happen.
