### ISSUE TITLE
You cannot use the new command inside an Angular CLI project.

### ISSUE THREAD

**Issue by Ionaru** [angular/angular-cli#4405]
### OS?
Linux Ubuntu 16.10

### Versions.
node: 7.2.0
os: linux x64
@angular/cli: 1.0.0-beta.30

### Repro steps.
`npm install -g @angular/cli`
`mkdir newApp`
`cd newApp`
`ng new`

### The log given by the failure.
`You cannot use the new command inside an Angular CLI project.`
But the folder is completely empty.

**Comment by beeman** [comment]
@Ionaru can you check if you still have an `angular-cli` package installed globally? If you, please remove it.

And please verify if there is a mention of `angular-cli` in you package.json.

**Comment by Ionaru** [comment]
```
> npm -g list --depth=0
/usr/local/lib
├── @angular/cli@1.0.0-beta.30
├── bower@1.7.7
├── coffeedoc@0.3.1
├── grunt-cli@0.1.13
├── npm@3.10.9
├── npm-check-updates@2.8.9
├── phantomjs@2.1.3
├── plangage@0.0.0
├── rxjs@5.1.0
├── typescript@2.0.10
└── yo@1.6.0
```

**Comment by beeman** [comment]
Ok, that does not seem to be the case. 

So of you want to create the project dir yourself, you should use `ng init` instead of `ng new`

```
mkdir newApp
cd newApp
ng init
```

Of use `ng new` like this:

```
ng new newApp
```

**Comment by Ionaru** [comment]
Do you have the same CLI version?

**Comment by beeman** [comment]
```
❯ ng --version

                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
@angular/cli: 1.0.0-beta.30
node: 7.5.0
os: darwin x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6
```

**Comment by Ionaru** [comment]
You have Angular installed globally as well, is this needed?

**Comment by beeman** [comment]
No, it's not installed globally. I run this command from inside the project dir that I just created reproducing your steps.

**Comment by Ionaru** [comment]
Completely removing @angular/cli and reinstalling it seems to have done the trick.

**Comment by rinoldit** [comment]
hello friends I got the issues when trying to do " ng new MyApp1 "
" **You cannot use the new command inside an Angular CLI project** "

**Comment by vickytechkey** [comment]
remove the package.json file in the following path
C:\Users\name of user\node_modules\@angular\cli
its work me fine

**Comment by ASrima** [comment]
I had the similar problem and nothing was working out but then when I ran cmd as administrator it worked for me. First run the Command Prompt as administrator ans then create the new project and if it still doesn't create the project run the code rm -r -f // and then run ng new and then run ng serve and it should work. If nothing works just uninstall node and every other file related to it  and run the previous code again it will work.

**Comment by filipesilva** [comment]
@ASrima `rm -r -f //` might will probably delete a bunch of things that you don't expect. It's a bad idea to advise people to run this command.

**Comment by ASrima** [comment]
Hi filipesilva thank you for the advice. I only suggest to run it if nothing works and you really need to create the project otherwise you can try running the Command Prompt as administrator and then create the new project

**Comment by jhonazsh** [comment]
Hi i have the same problem. I need a solution. please help me!. I have Angular CLI version 1.6.3. I suppose that is the latest version because i used the command `npm install -g  @angular/cli` but nothing. 

```
>ng new my-project
you cannot use the new command inside an angular cli project
```

And i used this too:

```
>mkdir my-project
>cd my-project
>ng init
```

But nothing.

Please help me! - My OS is Windows x64.

**Comment by ASrima** [comment]
jhonazsh   Run the Command Prompt as administrator and then create the new project and it should work and when you use the IDE open it as administrator to be able to edit and save the project. Also use the latest version of node if nothing works uninstall and reinstall the latest version and then follow the same process of running CMD and IDE as administrator.

**Comment by jhonazsh** [comment]
Hi @ASrima  I uninstalled node and i installed the latest version for node and i installed the latest version for Angular CLI and works. Thanks for your help. 👍 i follow you on github :)

**Comment by Crystyanno** [comment]
Se estiver iniciar a instalação usando o  "CMD" como Administrador você só irá conseguir criar novos projetos da mesma forma sempre no modo Adm.
