### ISSUE TITLE
Angular-cli webpack failed after ng serve

### ISSUE THREAD

**Issue by phani257** [angular/angular-cli#4409]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

 1.0.0-beta.28.3
### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Yes it is from CLI. No changes made

### The log given by the failure.
> Normally this include a stack trace and some more information.

** NG Live Development Server is running on http://localhost:4200. **
 10% building modules 0/1 modules 1 active ...00/ c:\Projects\Dashboard\src\main
 10% building modules 1/2 modules 1 active ...:\Projects\Dashboard\src\polyfills
 10% building modules 2/3 modules 1 active ... c:\Projects\Dashboard\src\styles.
Hash: 6a38e9bf99d82af8f7ee
Time: 1685ms
chunk    {0} styles.bundle.js, styles.bundle.map (styles) 28 bytes {3} [initial]
 [rendered]
chunk    {1} polyfills.bundle.js, polyfills.bundle.map (polyfills) 28 bytes {3}
[initial] [rendered]
chunk    {2} main.bundle.js, main.bundle.map (main) 40 bytes [initial] [rendered
]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rende
red]

ERROR in multi ./src/styles.css
Module not found: Error: Can't resolve 'style-loader' in 'c:\Projects\Dashboard'

 @ multi ./src/styles.css

ERROR in multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localho
st:4200/' in 'c:\Projects\Dashboard'
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in 'c:\Projects\Dashbo
ard'
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in 'c:\Projects\Dashbo
ard'
 @ multi ./src/polyfills.ts

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'raw-loader' in 'c:\Projects\Dash
  board':
  Error: Can't resolve 'raw-loader' in 'c:\Projects\Dashboard'

  - compiler.js:76
    [Dashboard]/[angular-cli]/[html-webpack-plugin]/lib/compiler.js:76:16

  - Compiler.js:280 Compiler.<anonymous>
    [Dashboard]/[angular-cli]/[webpack]/lib/Compiler.js:280:10

  - Compiler.js:480
    [Dashboard]/[angular-cli]/[webpack]/lib/Compiler.js:480:13

  - Tapable.js:138 next
    [Dashboard]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:138:11

  - CachePlugin.js:62 Compiler.<anonymous>
    [Dashboard]/[angular-cli]/[webpack]/lib/CachePlugin.js:62:5

  - Tapable.js:142 Compiler.applyPluginsAsyncSeries
    [Dashboard]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:142:13

  - Compiler.js:477
    [Dashboard]/[angular-cli]/[webpack]/lib/Compiler.js:477:10

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [Dashboard]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:615 self.applyPluginsAsync.err
    [Dashboard]/[angular-cli]/[webpack]/lib/Compilation.js:615:19

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [Dashboard]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:606 self.applyPluginsAsync.err
    [Dashboard]/[angular-cli]/[webpack]/lib/Compilation.js:606:11

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [Dashboard]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:601 self.applyPluginsAsync.err
    [Dashboard]/[angular-cli]/[webpack]/lib/Compilation.js:601:10

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [Dashboard]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:597 sealPart2
    [Dashboard]/[angular-cli]/[webpack]/lib/Compilation.js:597:9

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [Dashboard]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:545 Compilation.seal
    [Dashboard]/[angular-cli]/[webpack]/lib/Compilation.js:545:8

  - Compiler.js:474
    [Dashboard]/[angular-cli]/[webpack]/lib/Compiler.js:474:16

  - Tapable.js:225
    [Dashboard]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:225:11

  - Compilation.js:452 _addModuleChain
    [Dashboard]/[angular-cli]/[webpack]/lib/Compilation.js:452:11

  - Compilation.js:345 Compilation.errorAndCallback
    [Dashboard]/[angular-cli]/[webpack]/lib/Compilation.js:345:4

  - Compilation.js:362 moduleFactory.create
    [Dashboard]/[angular-cli]/[webpack]/lib/Compilation.js:362:12

  - NormalModuleFactory.js:234
    [Dashboard]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:234:19

  - NormalModuleFactory.js:59 onDoneResolving
    [Dashboard]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:59:20

  - NormalModuleFactory.js:183
    [Dashboard]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:183:21

  - async.js:3694
    [Dashboard]/[angular-cli]/[async]/dist/async.js:3694:9

  - async.js:356
    [Dashboard]/[angular-cli]/[async]/dist/async.js:356:16

  - async.js:934 iteratorCallback
    [Dashboard]/[angular-cli]/[async]/dist/async.js:934:13

  - async.js:840
    [Dashboard]/[angular-cli]/[async]/dist/async.js:840:16

  - async.js:3691
    [Dashboard]/[angular-cli]/[async]/dist/async.js:3691:13

  - async.js:21 apply
    [Dashboard]/[angular-cli]/[async]/dist/async.js:21:25

  - async.js:56
    [Dashboard]/[angular-cli]/[async]/dist/async.js:56:12

  - async.js:1013
    [Dashboard]/[angular-cli]/[async]/dist/async.js:1013:9

  - async.js:356
    [Dashboard]/[angular-cli]/[async]/dist/async.js:356:16

  - async.js:934 iteratorCallback
    [Dashboard]/[angular-cli]/[async]/dist/async.js:934:13

  - async.js:840
    [Dashboard]/[angular-cli]/[async]/dist/async.js:840:16

  - async.js:1010
    [Dashboard]/[angular-cli]/[async]/dist/async.js:1010:13

  - NormalModuleFactory.js:262
    [Dashboard]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:262:19

  - Resolver.js:70 onResolved
    [Dashboard]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:70:11

  - createInnerCallback.js:31 loggingCallbackWrapper
    [Dashboard]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallba
    ck.js:31:19

  - Resolver.js:138 afterInnerCallback
    [Dashboard]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:138:1
    0

  - createInnerCallback.js:31 loggingCallbackWrapper
    [Dashboard]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallba
    ck.js:31:19

  - Tapable.js:181 Resolver.applyPluginsAsyncSeriesBailResult1
    [Dashboard]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:181:46

  - Resolver.js:125 innerCallback
    [Dashboard]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:125:1
    9

  - createInnerCallback.js:31 loggingCallbackWrapper
    [Dashboard]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallba
    ck.js:31:19

  - Tapable.js:283
    [Dashboard]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:283:15

  - UnsafeCachePlugin.js:38
    [Dashboard]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/UnsafeCachePlugin
    .js:38:4

  - createInnerCallback.js:31 loggingCallbackWrapper
    [Dashboard]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallba
    ck.js:31:19

  - Resolver.js:138 afterInnerCallback
    [Dashboard]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:138:1
    0

  - createInnerCallback.js:31 loggingCallbackWrapper
    [Dashboard]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallba
    ck.js:31:19

  - Tapable.js:181 Resolver.applyPluginsAsyncSeriesBailResult1
    [Dashboard]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:181:46

webpack: Failed to compile.

### Mention any other details that might be useful.
Created a new project using angular-cli. After doing ng serve above error is thrown. On the browser at http://localhost:4200/, only Loading.. is displayed.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by L0G1C** [comment]
This may or may not be related but I had a problem with ngServe not kicking off browser after building changes and the fix had to do with webpack.

#4338

**Comment by dandamoodi** [comment]
Same problem here. I am using Windows 10

Below is my `ng version`


@angular/cli: 1.0.0-beta.30
node: 4.5.0
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6
