### ISSUE TITLE
Include yarn.lock file in new project generation?

### ISSUE THREAD

**Issue by Brocco** [angular/angular-cli#4417]
With the PR (4321) to specify which package manager to use it will allow users to use yarn for their applications.

I wanted to open discussion as to whether the blueprints for new projects should include a yarn.lock file when the project is generated. If that is decided upon then the conversation can be moved on to implementation details.

**Comment by Meligy** [comment]
If the package uses yarn install, this'll add the lock file anyway.

If it doesn't, I don't think it's good to add it.

**Comment by Brocco** [comment]
The difference is that by defining it and deploying with it you're locking in the initial child dependencies that are known to be working. And not just taking the derived versions at the time of running `ng new`

**Comment by martinmcwhorter** [comment]
The yarn.lock should be generated. Developers should be encouraged to commit the yarn.lock in their app repo. 

The ng upgrade instructions should indicate deleting the yarn.lock at the start of the ng upgrade process.

**Comment by LukeHowellDev** [comment]
I think the `yarn.lock` should be generated, however, I think the `yarn.lock` should be included in the initial commit if the commit is added. Currently, when generated and not skipping git or skipping the commit, there are immediately pending changes because the lock file is added.

**Comment by intellix** [comment]
Yarn all the things for deterministic installations!

**Comment by filipesilva** [comment]
@Brocco what's the status of this issue?

**Comment by Brocco** [comment]
With the release of npm 5, we don't want to tie the CLI to supporting a specific or worse multiple client package managers. I feel this issue can be resolved by creating the necessary file (`yarn.lock` or `package-lock.json`) on their own machine.
