### ISSUE TITLE
ng build or ng serve alter <base href>

### ISSUE THREAD

**Issue by weihotline** [angular/angular-cli#4418]
With the latest angular-cli update (1.0.0-beta.26 and 1.0.0-beta.30), the base href="/xyz/" in the index.html will be reverted to base href="/" if not specified in ng serve or ng build.

In my project, I explicitly set the base href="/xyz/" in the index.html. But after the project compiles (ng serve or ng build), base href will become "/" in the index.html. The issue was not present before beta.26.

**Comment by weihotline** [comment]
The temporary fix for me is to do `ng serve --base-href /xyz/`

**Comment by sgybas** [comment]
This has already been reported as #4340.

**Comment by weihotline** [comment]
Closed as this is reported in #4340
