### ISSUE TITLE
App crashes while ng serve

### ISSUE THREAD

**Issue by Nishchit14** [angular/angular-cli#442]
I want to help!

Os: Ubuntu 15.10
npm: 3.7.3
angular-cli: 0.0.31
node: 5.8.0
os: linux x64

App crashes while `ng serve`, It gives some watchman error, I install watchman globally still it crashes.

![screenshot from 2016-04-15 17-57-57](https://cloud.githubusercontent.com/assets/5078921/14561808/8d675792-0336-11e6-9a05-f899f78e0b8a.png)

**Comment by hansl** [comment]
Watchman is optional. Could you try without it? If it works without it we might want to consider removing its dependency.

**Comment by Nishchit14** [comment]
It still crashes, if i remove wathman then it moves to NodeWatcher and gives warning as below then crash
> Could not start watchman; falling back to NodeWatcher for file system events.

**Comment by anode7** [comment]
ENOSPC (No space left on device)

A solution is proposed here #130

**Comment by hansl** [comment]
According to issue 130, you can find a solution here: http://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached

Closing this as resolved.
