### ISSUE TITLE
Update wiki documentation generation

### ISSUE THREAD

**Issue by Brocco** [angular/angular-cli#4420]
Update the process to flatten the directory structure when migrating from the documentation folder (https://github.com/angular/angular-cli/tree/master/docs/documentation) to the site wiki (https://github.com/angular/angular-cli/wiki)

**Comment by sumitarora** [comment]
@Brocco Have we decided how we want to do it? I can help with this one simultaneously.

**Comment by Brocco** [comment]
Not officially, but the thought I had was this....

repo
- overview.md
- generation
  - component.md
- stories
  - using-webpack.md

Would translate to this

wiki
- overview.md
- generation_component.md
- stories_using-webpack.md

The interesting part would be that all of the internal links would need to be updated as well.
