### ISSUE TITLE
Output dist directory for ng serve

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular-cli#4421]
I'm submitting a **feature request**

I'm wondering if it's applicable to introduce an optional flag for `ng serve` to output `dist` directory.
Using this flag along with the [**Proxy To Backend**](https://github.com/angular/angular-cli#proxy-to-backend) feature will support serve environment for whom are using the CLI within an external server such as `IIS` and `Apache`

Related issue #4271

**Comment by hansl** [comment]
This is by design, and you should never use `ng serve` for anything other than development. It's not performant and it's not secure.

**Comment by MurhafSousli** [comment]
@hansl did you understand my request?! I said I want to use `ng serve` for development!! why did you close it?

**Comment by MurhafSousli** [comment]
@hansl you are saying this is by design, but doesn't mean it can't be extended, for example `ng serve --aot` gives the `dist` directory, the only downside that it's slower!

**Comment by MurhafSousli** [comment]
Tell me where did I mention **PRODUCTION**, I said I need the `dist` directory, because `APACHI` or `IIS` needs to load the angular app from there **FOR LOCAL DEVELOPMENT ONLY**

**Comment by delasteve** [comment]
@MurhafSousli, if you're needing the `dist` directory, just use `ng build --prod`. I don't see what benefits `serve` gives you if you're using IIS or Apache in front of you app.

**Comment by grizzm0** [comment]
You might want to throw in `--watch` aswell to rebuild on changes.

**Comment by MurhafSousli** [comment]
@delasteve How do you want do live reload with `ng build --dev` ?

**Comment by hansl** [comment]
@MurhafSousli You edited your original comment, and it wasn't clear.

What you're really looking for is `ng build --watch`, which outputs `dist/` and will update it when files change.

**Comment by MurhafSousli** [comment]
@hansl yes I changed `support serve environment` to `support dev environment`, still same meaning

**Comment by grizzm0** [comment]
Livereload is part of webpack-dev-server and is not something you'll get access to if you're using IIS or apache. As stated before you can use `--watch` to rebuild on change. But you'll still ned to manually refresh the page to see changes.

**Comment by MurhafSousli** [comment]
@grizzm0  Check the [Proxy To Backend](https://github.com/angular/angular-cli#proxy-to-backend).

**Comment by MoxxNull** [comment]
I'd vote for MurhafSousli's request aswell. It is needed if you use ng serve for hot-reloading dev with some backend like iis.
I use a config where my  Prod server routes to /dist  for example for some images or other assets, accessed via proxy to backend. 
Now during development, /dist is missing with the new beta, so are my images etc. .  I use a workaround telling my dev-backendserver to route to /src during dev, that works while src & dist have the same folder / file structure, but get's complicated if not.   Life would be so much easier if one could use  ng serve with a optional dist folder!

**Comment by grizzm0** [comment]
ng serve uses webpack-dev-server which serves the content from memory.

**Comment by MurhafSousli** [comment]
@grizzm0 we know that, but can you tell where does it serve the content from when `ng serve --aot` is used?

**Comment by grizzm0** [comment]
Its still being served from memory. That's how webpack-dev-server works.

**Comment by wesamco** [comment]
I hope `ng build --bh "./" --watch` woks for chrome extension development.
