### ISSUE TITLE
ng serve not creating new hash on code updates

### ISSUE THREAD

**Issue by rohitsodhia** [angular/angular-cli#4422]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Win 8

### Versions.
 1.0.0-beta.30

### Repro steps.
Originally created in 1.0.0-beta.26, I followed the update steps on the main GIT page to update to 30.

### The log given by the failure.
Not a failure, persay. When I run ng serve, the initial compilation works out. When I change code, it triggers the compiler to rebuild the files, but the same hash is served, and the files don't seem to update. I have to stop ng serve and restart it each time I make a code change to see my changes reflected.

**Comment by nerumo** [comment]
Same on Win 10, the hash stays the same. If I change the html it works, but not for TS.

**Comment by hansl** [comment]
Seems like this is a problem mostly with Windows. We'll investigate. Thanks!

**Comment by Ionaru** [comment]
Can confirm issue on Windows 10, changing something in the stylesheets will also trigger a refresh correctly.

**Comment by Jonatthu** [comment]
Same here with ngtools 1.2.7 is happening, I've installed 1.2.4 for keep working

**Comment by mattdistefano** [comment]
Dup of #4338?

**Comment by ulymor** [comment]
The same problem.
OS:  Ubuntu 16.04
CLI: 1.0.0-beta.30
node: 6.9.2
npm: 4.1.2
