### ISSUE TITLE
fallbackLoader option has been deprecated - replace with "fallback" loader option has been deprecated - replace with "use"

### ISSUE THREAD

**Issue by beeman** [angular/angular-cli#4434]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

- macOS Sierra
- Ubuntu 16.04.1 LTS (clean machine)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
@angular/cli: 1.0.0-beta.30
node: 7.5.0
os: darwin x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6
```
### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

```
$ ng new fallbackloader
$ cd fallbackloader
$ ng serve
```

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
** NG Live Development Server is running on http://localhost:4200. **
```
### Mention any other details that might be useful.

The project seems to work correctly. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattma** [comment]
I experienced the same issue. I think this pr fixed it. Thanks

**Comment by shakhrillo** [comment]
I'm using windows 7 and everything is up to date. But still warn is giving. Could you help?
![default](https://cloud.githubusercontent.com/assets/3455633/22752181/68307a62-ee59-11e6-92e9-10f054742670.PNG)

**Comment by bjornharvold** [comment]
Getting the same error as everyone else: Angular CLI beta 30 with Angular 2.4.6

**Comment by MatGhp** [comment]
+1

**Comment by StrontsitskiyVolodymyr** [comment]
+(

**Comment by Kozlo** [comment]
+1

**Comment by nerdyzia** [comment]
+1

**Comment by MeMeMax** [comment]
+1

**Comment by beeman** [comment]
There's no need to +1 the issue, the problem is confirmed and the fix is in place and will ship with the next release.

I don't know when that next release is but I expect it to be soon as there are more issues that need a fix.

**Comment by beeman** [comment]
https://twitter.com/hanslatwork/status/829570400384278528

It looks like there will be a new beta today :)

**Comment by bertolo1988** [comment]
+1

**Comment by ccabanero** [comment]
+1

**Comment by intellix** [comment]
There's no need to +1 guys, it just causes unnecessary notifications. That's why Github added reactions: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by marcusvy** [comment]
+1

**Comment by mattma** [comment]
Confirmed. The latest Beta.31 works great and this bug has been squashed.

**Comment by omachala** [comment]
npm uninstall -g angular-cli @angular/cli
npm cache clean
npm install -g @angular/cli@latest

**Comment by niilante** [comment]
@omachala having errors starting ng serve after the 3 steps

**Comment by omachala** [comment]
@niilante tested for now project (ng new + ng serve) and this fixed 'fallbackLoader option has been deprecated' and worked fine. What errors do you see?

**Comment by shy001** [comment]
![image](https://cloud.githubusercontent.com/assets/19182583/23692763/46184a64-03d9-11e7-8e0f-860b32c582ae.png)
after running the 3 steps i say ng serve and i get this

**Comment by jmachete** [comment]
+1

**Comment by aucevica** [comment]
Reinstall everything (node, npm, Angular, Angular-cli, Typescript, etc...) and .....
fallbackLoader option has been deprecated - replace with "fallback"
> ng -v
@angular/cli: 1.0.0
node: 6.9.4
os: win32 x64
> npm -v
4.5.0
rmdir node_modules
npm install
npm start

**Comment by daryn-k** [comment]
Same problem

**Comment by moohkooh** [comment]
same problem.

**Comment by hithto** [comment]
angular-cli: 1.0.0-beta.28.3
node: 8.6.0
os: win32 x64

Same problem
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"

**Comment by MeMeMax** [comment]
Do this as suggested by omachala:

npm uninstall -g angular-cli @angular/cli
npm cache clean
npm install -g @angular/cli@latest

**Comment by micksatana** [comment]
In my case, I need `npm cache verify` instead of `npm cache clean`

````
npm uninstall -g angular-cli @angular/cli
npm cache verify
npm install -g @angular/cli@latest
````
