### ISSUE TITLE
patterns.map is not a function

### ISSUE THREAD

**Issue by kumaraksi** [angular/angular-cli#4436]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.28.3
node: 6.6.0
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/compiler-cli: 2.4.6

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
I upgraded from beta 16 to beta 28.3

### The log given by the failure.
> Normally this include a stack trace and some more information.
![angular-cli](https://cloud.githubusercontent.com/assets/1006860/22622191/fad8b1a2-eb59-11e6-90aa-dd27b1934831.PNG)

### Mention any other details that might be useful.
I updated angularjs from 2.0 to 2.4. This required me to update my cli as well. However since the update I am not able to run my project on localhost. I get "patterns.map is not a fumction" error when running "ng serve" command.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@kumaraksi if you not did so after upgrading your packages, can you remove `node_modules` and `npm install` ?

Also, please note that the latest version of the project lives in the `@angular/cli` package. 

To work with this version uninstall angular-cli globally: `npm uninstall -g angular-cli`, locally `npm uninstall --save-dev angular-cli` and install `@angular/cli` globally and locally.

**Comment by kumaraksi** [comment]
@beeman I removed the `node_modules` and then ran `npm install`. Still getting the same error. 
Also unistalled angular-cli globally and locallyand installed `@angular-cli` globally and locally.
Still getting the same error.

My package.json is as below : 

`{
  "name": "invoice",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "serve": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "~3.4.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2",
    "angular2-jwt": "^0.1.23",
    "angular2-materialize": "^5.1.4",
    "hammerjs": "^2.0.8",
    "materialize-css": "^0.97.7"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "^1.0.0-beta.28.3",
    "codelyzer": "~2.0.0-beta.1",
    "electron-prebuilt": "^1.4.1",
    "faker": "^3.1.0",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "json-server": "^0.8.22",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "^4.0.9",
    "ts-node": "^1.2.1",
    "tslint": "^4.0.0",
    "typescript": "^2.0.2"
  }
}
`

**Comment by Meligy** [comment]
You need to remove `angular-cli` and install `@angular/cli`.

Please [see here](https://www.gurustop.net/blog/2017/02/03/how-to-upgrade-from-angular-cli-beta-28-3-and-lower-to-angularcli/) for specific steps to ensure a successful upgrade.

**Comment by Exertive** [comment]
Just a quick note to say that I had exactly the same problem attempting to run Jeremy Elbourn's (jelbourn) Material 2 App straight out of the Github box. I successfully solved the issue with a combination of 1) Meligy's Angular CLI upgrade; and 2) rebuilding the app from a fresh 'ng new material2app' project andcpy across relevant content.

**Comment by kumaraksi** [comment]
Thanks mate for the help. Issue was resolved after I followed the steps mention in the link provided by @Meligy . Was searching the net for a similar article on upgrading  from `angular-cli` to `@angular-cli`.
