### ISSUE TITLE
polyfills.bundle.js not included when you serve app through npm script

### ISSUE THREAD

**Issue by david-bulte** [angular/angular-cli#4438]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 7

### Versions.
@angular/cli: 1.0.0-beta.30
node: 6.9.5
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6

### Repro steps.
After updating the CLI to 1.0.0-beta.30 my app fails to start because of:

`Uncaught reflect-metadata shim is required when using class decorators`

The reason is that the polyfills.bundle.js is not included at the end of the index.html file. 

I am starting the CLI with an npm script (npm start), that delegates to 'ng serve'. Here's a snippet from my package.json:

```
"scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --port 9020 --proxy-config proxy.conf.json",
``` 

The weird thing is that if I am starting directly with 'ng serve' (or do an 'ng build'), the polyfills.bundle.js file *is* included.

### Logs

Here are 2 logs, the first one started as npm script. Notice that in the first one the 'polyfills' step is missing.
 
Starting with 'npm start':

c:\system9\sourcesWEB\MYNEXUZ\MyNexuz>npm start

> my-nexuz@2.0.0-beta.1 start c:\system9\sourcesWEB\MYNEXUZ\MyNexuz
> ng serve --host 0.0.0.0 --port 9020 --proxy-config proxy.conf.json

fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
** NG Live Development Server is running on http://0.0.0.0:9020. **
Hash: 9bec9d501fb9b6bf10f0
Time: 144698ms
chunk    {0} main.bundle.js, main.bundle.map (main) 992 kB {3} [initial] [rendered]
chunk    {1} scripts.bundle.js, scripts.bundle.map (scripts) 2.25 MB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 245 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 4.8 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.

Starting with 'ng serve':

c:\system9\sourcesWEB\MYNEXUZ\MyNexuz>ng serve --host 0.0.0.0 --port 9020 --proxy-config proxy.conf.json
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
** NG Live Development Server is running on http://0.0.0.0:9020. **
Hash: a9286aa44bfac0ba8443
Time: 137779ms
chunk    {0} main.bundle.js, main.bundle.map (main) 992 kB {4} [initial] [rendered]
chunk    {1} polyfills.bundle.js, polyfills.bundle.map (polyfills) 394 kB {5} [initial] [rendered]
chunk    {2} scripts.bundle.js, scripts.bundle.map (scripts) 2.25 MB {5} [initial] [rendered]
chunk    {3} styles.bundle.js, styles.bundle.map (styles) 245 kB {5} [initial] [rendered]
chunk    {4} vendor.bundle.js, vendor.bundle.map (vendor) 4.8 MB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.

### Mention any other details that might be useful.

I have tried running with variations like 'npm start', 'npm run start', 'npm run ng-start' (where I renamed my npm script name) but none of them were succesful.

When I include the 'import './polyfills.ts';' import in the 'main.ts' file (as was the case in previous versions of the CLI), I am *not* getting the error.

**Comment by grizzm0** [comment]
Did you add `"polyfills": "polyfills.ts"` to your angular-cli.json? I missed that diff myself at first.

See: https://github.com/angular/angular-cli/blob/c889dd8e9408f02bf8b1138c9cff15d27d1140dc/packages/%40angular/cli/blueprints/ng2/files/angular-cli.json#L16

**Comment by david-bulte** [comment]
Yes i did. And when I just run 'ng serve' everything is working fine.

**Comment by david-bulte** [comment]
Ok my bad. When updating the CLI, the old "angular-cli" entry was still in my package.json.

**Comment by ramyabhavanam** [comment]
Hey there is "polyfills": "polyfills.ts" in my angular-cli.json but still i am seeing the same error message like rendered as shown below. Can you please suggest me what is the issue with.

Your global Angular CLI version (1.2.7) is greater than your local
version (1.0.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
Hash: 20629e0f8550f16d409b
Time: 8486ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 178 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 115 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 65.6 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.56 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
