### ISSUE TITLE
Why use class rather than interface for defining types?

### ISSUE THREAD

**Issue by sharpmachine** [angular/angular-cli#444]
Hi there,

Just wondering why the CLI generates types using `class` rather than `interface`. Isn't `interface` better when using the types in components when it comes to runtime errors?

So does the CLI generate this:
```
export class Subject {
  constructor(
    public firstName: string,
    public lastName: string,
    public dateOfBirth: string,
    public dateCreated?: string,
    public id?: number
  ) { }
}
```

Rather than this:
```
export interface Subject {
  firstName: string,
  lastName: string,
  dateOfBirth: string,
  sadsd: string,
  dateCreated?: string,
  id?: number
}
```

**Comment by hansl** [comment]
Your two examples are strongly different and don't do the same thing at all; your first example actually creates a function that can be instantiated. The second one is a type and outside of TypeScript, won't have any resulting code.

For example, `new Subject(...)` will result in an error with your second example.
