### ISSUE TITLE
'ng' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by LunaBawa** [angular/angular-cli#4442]
Am getting this at after setup

C:\Users\USER>ng --version
'ng' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\USER>node --version
v6.9.5

Am using Windows 10/ 64 bit

> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by david-bulte** [comment]
Either you haven't installed the CLI globally or you haven't added your NPM home dir to your PATH?

**Comment by LunaBawa** [comment]
![image](https://cloud.githubusercontent.com/assets/11213175/22629353/9ac153a6-ebe4-11e6-90fd-1734e3db17ba.png)

Please, how do i add NPM home dir to my path?

**Comment by david-bulte** [comment]
http://stackoverflow.com/questions/27864040/fixing-npm-path-in-windows-8 might help?

Have a look at Yar's answer for finding the npm path. The other answers for how to add that path to your Windows PATH environment variable.

**Comment by eran12** [comment]
The problem is NOT the install of the NPM nor the path !
If you want to use the "ng" commend you need to install the angular-cli.

[https://cli.angular.io/](https://cli.angular.io/)

**Comment by deebloo** [comment]
like @eran12 said it doesn't look like you have @angular/cli installed. verify that the installation was completed successfully.

**Comment by LunaBawa** [comment]
Thanks everyone i think i found a way around this

**Comment by RBroden** [comment]
@LunaBawa Would you share please?

**Comment by skbelalmd** [comment]
Would you please share?

**Comment by Ardeshir81** [comment]
yep! share is good!

I believe his solution is to install [@angular/cli](https://cli.angular.io/)

this documentation would help : [Angular CLI Quickstart ](https://angular.io/docs/ts/latest/cli-quickstart.html)

**Comment by emrhzc** [comment]
have the same problem after installing cli globally; "npm install -g @angular/cli"
npm is working fine, suggesting it is among path variables. 
@LunaBawa, would you mind sharing your solution?

**Comment by gautamjgithub** [comment]
Just open your command prompt (run as administrator). Ensure node --v is 6.9.0 or higher and npm --v is 3.0.0 r higher.

After that run the following command: 

npm install -g @angular/cli

Once angular is installed. you can see an entry of angular cli in the path

C:\Users\Dell\AppData\Roaming\npm\node_modules\@angular

Then try ng help. It will work.

**Comment by Elichii** [comment]
it doesn't do for me. any other suggestions?

**Comment by raferbop** [comment]
I am having the same issue, and I am using Windows 7 home premium.

**Comment by naru6be** [comment]
Hi Friends!
At last find the solution for ng command is not working issue ,Find the solution below
http://itechiesol.blogspot.com/2017/07/angular-cli-ng-command-is-not-working.html

**Comment by PHuhn** [comment]
I just got a new computer (win 10) and experienced the same problem moving to new environment.  I added %APPDATA%\npm to the PATH environment variable.  That is where the ng command is (thanks emrhzc).

**Comment by alfmoh** [comment]
This blog post helped me solved this problem. [http://ovinitech.blogspot.ru/2017/08/ng-is-not-recognized-as-internal-or.html](url)

**Comment by richardmpadre** [comment]
emrhzc's solution worked, thank you!

**Comment by StruggleYang** [comment]
thanks emrhzc。I met the same problem and now I've solved it.

**Comment by TechiePriyaRanjan** [comment]
I tried to install via **npm** and the following error given by the terminal

```
λ npm install -g @angular/cli
npm ERR! Unexpected end of JSON input while parsing near '...erify":"latest","@typ'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Priya Ranjan Dubey\AppData\Roaming\npm-cache\_logs\2018-09-17T10_54_38_949Z-debug.log
```

the angular-cli was installed using **yarn** but after running ```ng --version```  ng was not recognized
```
λ ng --version
'ng' is not recognized as an internal or external command,
operable program or batch file.
```

What to do?

**Comment by PHuhn** [comment]
Hey Techie: It seem you are on a windows computer.  Verify that CLI is installed:
```
> CD %APPDATA%\npm
> ng --version

```
If installed configure your local PATH to include the above folder.

**Comment by NiraliB** [comment]
Hi I have face this error while am trying to create new app using ng new -Myapp syntax.
and i have already installed latest version of npm cli.

Still i getting following error.
Error: 
'ng' : The term 'ng' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ ng --version
+ ~~
    + CategoryInfo          : ObjectNotFound: (ng:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by tarundvarma49** [comment]
Please try to use **Node.js command prompt** in your windows. It will work.

**Comment by KunalAsh95** [comment]
> The problem is NOT the install of the NPM nor the path !
> If you want to use the "ng" commend you need to install the angular-cli.
> 
> https://cli.angular.io/

I installed the angular cli as well and also added the environment variables, but still getting the error.
