### ISSUE TITLE
NPM page of @angular/cli links to angular-cli

### ISSUE THREAD

**Issue by janklan** [angular/angular-cli#4443]
### What's happening?

The description at https://www.npmjs.com/package/@angular/cli links one of the status indicators to an old repository, causing a wrong "current" version to be displayed.

> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

N/A

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

v1.0.0-beta.30

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Open https://www.npmjs.com/package/@angular/cli

### The log given by the failure.
> Normally this include a stack trace and some more information.

N/A

### Mention any other details that might be useful.

I can't imagine many things of lower priority, though it is a bit confusing.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
We've fixed this since, thanks for reporting!
