### ISSUE TITLE
changed location install -g Windows 10

### ISSUE THREAD

**Issue by GoNode5** [angular/angular-cli#4448]
Windows 10 ( cli version .18)
npm uninstall -g angular-cli @angular/cli
npm cache clean
npm install -g @angular/cli@latest

I was expecting a refreshed ng.cmd. Then I found out that now it's installed at:
- C:\Program Files\nodejs\node_modules\@angular
- ng.cmd now in C:\Program Files\nodejs
It used to be:
 C:\Users\Office\AppData\Roaming\npm

Its working because the path is now:
C:\where ng
C:\Program Files\nodejs\ng
C:\Program Files\nodejs\ng.cmd
C:\Users\dev-pc\AppData\Roaming\npm\ng
C:\Users\dev-pc\AppData\Roaming\npm\ng.cmd

Not sure this is a right install. I think the problems are caused by the new @angular that doesn't seem to take account of the older installs

**Comment by Meligy** [comment]
That's a bit odd and looks like a problem with Node/Npm not Angular CLI.

Can you please share your Node and NPM versions?

Are they installed via official installer or via some other way?
(As in: portable node, or using Chocolatey)

Anything interesting in your .npmrc file in your user folder?

One more thing: Does it happen with other global CLI packages? Try installing something else (typescript, yeoman, etc.) and see.

Thanks a lot.

**Comment by GoNode5** [comment]
node v7.4.0 / npm  v4.0.5
I use NVM to switch node versions, never had any problems before.

Last week before I installed angular-cli local (without -g) that worked ok. Wanted to upgrade last week but then .28 broke everything. Also local install was not possible anymore because changed ng.cmd  where node_modules\@angular\cli\bin\ng is not compatible with node_modules\angular-cli\bin\ng
Now I understand why and how it works.

But if AppData\Roaming\npm is the place where it should be, I can move it manually to the right place?

**Comment by itsnotvalid** [comment]
@GoNode5 Guessing you should uninstall the old version (beta.28 or below) completely before installing the one in new namespace (beta.30 or above in @angular/cli ).

**Comment by filipesilva** [comment]
Closing as a NPM problem. We can't really control where NPM installs stuff. It might also be NVM related, if you use it.

But we have updated our readme to highlight that you should uninstall older versions: https://github.com/angular/angular-cli#updating-angular-cli

There's also a RC update guide: https://github.com/angular/angular-cli/wiki/stories-rc-update
