### ISSUE TITLE
Is there a way to conditionally include scripts in index.html as in analytics?

### ISSUE THREAD

**Issue by sfabriece** [angular/angular-cli#4451]

**Comment by Ionaru** [comment]
Here are a few helpful things I found on Google:
https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications
https://github.com/angulartics/angulartics2

**Comment by sfabriece** [comment]
Thanks @Ionaru I'll have a look.

**Comment by pdjota** [comment]
Hi I have the same question. The problem I have is when doing ng build the script code in the index is not included.
I also created this question for the same reason
http://stackoverflow.com/questions/42388641/how-to-include-google-analytics-in-angular-cli-application

Any updates?
Thanks in advance

**Comment by Ionaru** [comment]
@pdjota and you killed StackOverflow, well done ;-)

Be sure not to put the script code inside the <app-root> tags, because anything inside those tags gets replaced by the Angular application.

**Comment by pdjota** [comment]
thanks @Ionaru including the tag in the HEAD is working for me.

**Comment by qatsi** [comment]
The initial question has not really been answered here, I'm also wondering how that could be solved.

Consider if you add f.e. Google Tag Manager or Google Analytics integration to your site, and you have different workspaces (or properties in GA) setup for your different environments. The appropriate script&noscript tags area added to the `head` and `body` of `index.html` but the tracking-id differs between environments.

Best case scenario would of course be if `ng build --env=staging/prod` would produce two different `index.html`s where the tracking id has been set via some dynamic variable.

Until there is support for that, what would be a decent workaround? I guess checking environment variables on server side and serve two different index.html files would be one option. Am using a simple static files server currently though so curious to whether there is some more elegant way of solving this as part of the build process instead

**Comment by Ionaru** [comment]
You could try making a function to add different Analytics properties when running in different environments. Like this:
```typescript
if (environment.production) {
  document.getElementById('analytics').innerHTML = 'Production-analytics-code-here';
} else if (environment.staging) {
  document.getElementById('analytics').innerHTML = 'Staging-analytics-code-here';
}
```

If you do this in main.ts, then the code gets added to the webpage as early as possible.

**Comment by filipesilva** [comment]
The CLI doesn't provide any such functionality, no. This was requested in https://github.com/angular/angular-cli/issues/4288.

In past projects what I did was having Angular services that correctly run these scripts, and use the correct analytics token provided inside the environment files.

@Ionaru has provided some pretty good solutions though, cheers!

**Comment by mackelito** [comment]
Wont this fail tests? (using document?)

**Comment by AndreiShostik** [comment]
@filipesilva I don't think it's a 'pretty good solution', it's mostly a workaround which fortunately works fine

**Comment by jfcere** [comment]
@Ionaru solution is the best workaround I found so far.

**There is a "but" to this workaround**
Adding the `<noscript>` section dynamicaly when bootstraping Angular makes no sense as it needs javascript to bootstrap but the tag is to track disabled javascript users.

So be ready to throw away non javascript users tracking if you want to use that workaround OR you could keep the `<noscript>` section in the body of the `index.html` file but you'll get tracking for non javascript user from every environments mixed together.

**Comment by edodusi** [comment]
Solution provided here will not work in Angular Universal, due to direct access to the `document` object.
You should instead use the `DOCUMENT` object exported by the platform-browser.  This way I could set a dynamic tagManager id for each environment.

So in the **AppComponent**:

```typescript
import { DOCUMENT } from '@angular/platform-browser';
...
  public constructor(
    @Inject(DOCUMENT) private doc: any
  ) {
```

Then I used a private method called on `ngOnInit()` to insert the tag in `<head>`:

```typescript
  private setGTagManager() {
    const s = this.doc.createElement('script');
    s.type = 'text/javascript';
    s.innerHTML = '(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push'
      + '({\'gtm.start\':new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)'
      + '[0],j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src='
      + '\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);})'
      + '(window,document,\'script\',\'dataLayer\',\'' + environment.tagManagerId + '\');';
    const head = this.doc.getElementsByTagName('head')[0];
    head.appendChild(s);
  }
```

As you can see I imported the tagManager ID from the global `environment`, so I could use different ones for dev and production.

Also if you use Angular Universal be sure to run this code only on the server, or it will import the script twice in the browser.

Hope this helps.

**Comment by ramk-bharathi** [comment]
@pbazurin-softheme how to change between different index.html files with configurations, any example or snippets? I tried with changing "options" but it didnt worked.

**Comment by pcwa-ahendricks** [comment]
@pbazurin-softheme it seems like your snippet would work for my needs (adding <meta> tags instead of <script> tags) but it doesn't. Are  you certain that it works for you? If not, maybe the index.html in /src is handled differently in Angular CLI vs other files. Currently I have to use pre and post hooks with my npm package scripts in order to swap out the correct index.html.

**Comment by meetai** [comment]
Seemingly that example from @pbazurin-softheme would work starting from Angular CLI 6.1.0-beta.2, as explained [above](https://github.com/angular/angular-cli/issues/4451#issuecomment-395651237).

Check the [releases](https://github.com/angular/angular-cli/releases).

**Comment by wheredoesyourmindgo** [comment]
@meetai ahh. Yes. My comment was specific to cli 6.0.8. Apprciate the clarification.

**Comment by anywhichway** [comment]
This client side package should also address the original question outside the context of the Angular CLI: https://github.com/anywhichway/scriptswitch.

**Comment by bor-yo** [comment]
@lonaru solution worked for me also. Thanks!

**Comment by nicky-lenaers** [comment]
@pbazurin-softheme Your solution is the most stable one. It prevents adding script tags at runtime (which would nullify the `<noscript>` tag usage). It's a little bit of maintenance overhead, but in my opinion it prevents possibly hard-to-debug errors when injecting script tags dynamically. Thanks!

**Comment by toby5box** [comment]
> The CLI doesn't provide any such functionality, no. This was requested in #4288.
> 
> In past projects what I did was having Angular services that correctly run these scripts, and use the correct analytics token provided inside the environment files.
> 
> @Ionaru has provided some pretty good solutions though, cheers!

Please edit this to point to the much better answer at https://github.com/angular/angular-cli/issues/4451#issuecomment-399888807
