### ISSUE TITLE
Re-compile does not always trigger browser update

### ISSUE THREAD

**Issue by Ionaru** [angular/angular-cli#4453]
### OS?
Linux Kubuntu 16.10

### Versions.
@angular/cli: 1.0.0-beta.30
node: 7.4.0
os: linux x64

### Repro steps.
`ng new newApp`
`cd newApp`
`ng serve`
Edit app.component.ts (I changed 'app works!' to 'app works!!') and save.
This will trigger a re-compile.

### The log given by the failure.
[WDS] App updated. Recompiling...
[WDS] App updated. Recompiling...
[WDS] Nothing changed.

### Mention any other details that might be useful.
The hash between compile runs does not change.

I've seen an issue on this topic before, but it appears this is not a Windows-specific problem.

**Comment by biwin** [comment]
this happens for _minor_ changes and most of us are not concerned about it.

**Comment by vaags** [comment]
If this is the case: what kind of changes are considered to be _minor_? (genuine question)

**Comment by biwin** [comment]
may be adding/removing a semi colon. who knows!

**Comment by ajinkyau** [comment]
I am also facing this same issue.

When I try to add / remove a piece of code like (console.log() or a tag from html)

**Comment by eklee** [comment]
Also happens to me on Windows, for a new ng project, and an existing project that had been updated to 1.0.0-beta.30.

Changing a character in app.component.html triggers the browser update, but changing something in app.component.ts does not.

**Comment by klinki** [comment]
I'm facing the same problem. I will investigate it little bit further, but from what I observed, I can tell changing .ts triggers recompilation, BUT browser is still seeing old data.

**Comment by rgurgul** [comment]
I also have the same problem on Win 10.

**Comment by phil-cap** [comment]
Same here with Win7, node v6.9.1, npm v3.10.8

**Comment by jsBrian** [comment]
Same issue here: Win10 pro, Node.js v7.4.0, NPM v4.1.2.
When saving a .ts, the scripts compile, but:
- the  package sizes don't seem to change
- the webapp doesn't refresh

For both my upgraded and new project.
Doesn't seem to matter if the change is small or big.

**Comment by jsBrian** [comment]
Tested, and v1.0.0-beta.29 doesn't seem to have the same issue for me.

**Comment by jsBrian** [comment]
I reinstalled beta 30, and I don't seem to have the issue anymore. :-\

**Comment by Brocco** [comment]
@Ionaru can you please re-test and report back? make sure you run `npm cache clean` before you reinstall your dependencies.

Thanks!

**Comment by jwuliger** [comment]
FYI - To anyone who has not tried it yet. If you work directly from Master using `npm link` like shown in the README (at the bottom). It works, because the code for this has been fixed already. It can be a pain developing like that but I can always get through the NPM posted version error/bugs this way.

**Comment by MateEke** [comment]
We have the same issue on 3 Windows 10 machines with an existing project that had been updated to 1.0.0-beta.30 from 1.0.0-beta.26. All machines have Node 6.9.x. 
One of the machines has a clean install of Windows, so no npm cache was present when the packages had been installed, it has 1.0.0-beta.30 from the beginning.

**Comment by Brocco** [comment]
@MateEke are you able to share that repo?

**Comment by MateEke** [comment]
Sorry, but unfortunately not possible, as it's not an open source project.

**Comment by Brocco** [comment]
That's cool... can you share your package.json and angular-cli.json?

**Comment by MateEke** [comment]
[cli.zip](https://github.com/angular/angular-cli/files/759080/cli.zip)

**Comment by ifynk** [comment]
I have some problem too. I just create new application with **ng new**. Then i started **ng serve**. Webpack compiled successfully. If i change template file or css then recompiled successful and live reload works. But if i change some in .ts files then live reloading not works and .ts files not compiled. Although webpack shown compiled successfully. If restart **ng serve** all changes apply successfully.

OS: Ubuntu 16.04 LTS
Node: v7.4.0
Npm: 4.0.5

> {
>   "name": "slots",
>   "version": "0.0.0",
>   "license": "MIT",
>   "angular-cli": {},
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "test": "ng test",
>     "pree2e": "webdriver-manager update --standalone false --gecko false",
>     "e2e": "protractor"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/common": "^2.3.1",
>     "@angular/compiler": "^2.3.1",
>     "@angular/core": "^2.3.1",
>     "@angular/forms": "^2.3.1",
>     "@angular/http": "^2.3.1",
>     "@angular/platform-browser": "^2.3.1",
>     "@angular/platform-browser-dynamic": "^2.3.1",
>     "@angular/router": "^3.3.1",
>     "core-js": "^2.4.1",
>     "rxjs": "^5.0.1",
>     "ts-helpers": "^1.1.1",
>     "zone.js": "^0.7.2"
>   },
>   "devDependencies": {
>     "@angular/cli": "1.0.0-beta.30",
>     "@angular/compiler-cli": "^2.3.1",
>     "@types/jasmine": "2.5.38",
>     "@types/node": "^6.0.42",
>     "codelyzer": "~2.0.0-beta.1",
>     "jasmine-core": "2.5.2",
>     "jasmine-spec-reporter": "2.5.0",
>     "karma": "1.2.0",
>     "karma-chrome-launcher": "^2.0.0",
>     "karma-cli": "^1.0.1",
>     "karma-jasmine": "^1.0.2",
>     "karma-remap-istanbul": "^0.2.1",
>     "protractor": "~4.0.13",
>     "ts-node": "1.2.1",
>     "tslint": "^4.3.0",
>     "typescript": "~2.0.3"
>   }
> }

**Comment by Ionaru** [comment]
@Brocco 

I can confirm this is still not working, I used a completely clean installation of @angular/cli.
What I did:
`sudo npm -g remove @angular/cli`
`npm cache clean`
`sudo npm cache clean` (just to be safe)
`sudo npm -g install @angular/cli`
`ng new myNewApp`
`cd myNewApp`
`ng serve`
Edited app.component (Two seperate edits, one with Kate and one with gedit)
But the hash in the `ng serve` terminal was still the same, and the website did not refresh.

I also tried doing the same steps using a direct clone and install of the Master branch as suggested by @jwuliger, no luck there either.

**Comment by ocombe** [comment]
I have the same problem on windows x64, node 6.9.5, and cli beta 30. I just started a new project so it is clean and it's probably not because of something in my code.

**Comment by andyflatt** [comment]
I am seeing this too.  I tried running off master as @jwuliger suggested and got a puzzling result. 

At first it was not working, I thought I would try to trick it into doing a reload by purposely putting and error in the code then fixing it.  To see if a failed build will force an update.  This however did not work, and made all following builds fail, with the same error being shown even though it does not exist in the code.

I then quit the build and tried again.  This time the reload started working.  It now seems to be working.

Versions.
@angular/cli: 1.0.0-beta.30 and master
node: 7.4.0
os: Windows 7 x64

**Comment by LunaBawa** [comment]
It wouldnt be bad if i add myself to the list of those with a similar issue here... experienced it yesterday and till today i have done all i can think off and yet....still here standed.

![image](https://cloud.githubusercontent.com/assets/11213175/22858334/7ab07bf2-f0ba-11e6-93d9-024951bac41e.png)

**Comment by Ionaru** [comment]
@LunaBawa is that with the latest Angular CLI version (Beta 31)?

**Comment by Pumych** [comment]
The same for me, on different machines:
Windows 7, Windows 10:
@angular/cli: 1.0.1
node: 7.5.0
os: win32 x64

No matter the changes size. Hash is the same, only possible solution is to re-run 'ng serve' (or 'npm start' )

**Comment by RenaldasK** [comment]
I am experiencing this issue on @angular/cli: 1.3.0-rc.3
