### ISSUE TITLE
proxy config is not working after build the code by ng build

### ISSUE THREAD

**Issue by uyadav0001** [angular/angular-cli#4454]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by uyadav0001** [comment]
proxy config is not working after build the code by ng build

**Comment by Brocco** [comment]
The proxy configuration is intended to proxy calls when running the dev server via `ng serve`. After you run `ng build` you are responsible for the web server and its configurations when you run/host the output in the `dist` dir.

This is a misunderstanding of the proxy functionality... closing.

**Comment by uyadav0001** [comment]
I am consuming rest api. So I need proxy config after build the code

**Comment by unstephenk** [comment]
@uyadav0001 Were you able to resolve this. I am also having the same issue.

In order to aviod CORS errors, I set up the proxy similar to yours. When I use ng build, it totally ignores the start line in the package.json that launches the proxy with npm start

**Comment by ashwinpatiljumia** [comment]
Any update here ?

**Comment by 20k-ultra** [comment]
@Brocco has mentioned above the proxy configuration is strictly just for local development. When you build, you have to configure the server serving the app to proxy the requests.

**Comment by switch120** [comment]
I feel like I need to chime in here and say just how LUDICROUS this is. Honestly I'm beside myself that this is the "accepted" answer. Who the hell makes their Dev workflow THAT MUCH different from Prod? I mean seriously - there's no way to seamlessly recreate that sort of a proxy, so you've completely left ANY developer who's used this (awesome) feature out in the cold. We've used that feature extensively to get around CORS, so basically you're saying it's OK and "the plan" to make it so Angular can't use ANY remote APIs out of the box, even though this feature exists? This has to be the absolute dumbest and most frustrating thing I've ever seen, and that's counting how frustrated I was going from AngularJS to Angular 2+. Just ... Shame.

**Comment by TonyYule** [comment]
Maybe this can help you.
https://itnext.io/angular-cli-proxy-configuration-4311acec9d6f
