### ISSUE TITLE
ng build prod - 'require' function calls are not supported

### ISSUE THREAD

**Issue by doczoidberg** [angular/angular-cli#4456]
### OS?
Windows 10

### Versions.
@angular/cli: 1.0.0-beta.30
node: 6.9.5
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/compiler-cli: 2.4.6
@angular/language-service: 2.4.6
@angular/cli: 1.0.0-beta.30

### Repro steps.
ng build --prod

### The log given by the failure.
ERROR in Error encountered resolving symbol values statically. Calling function 'require', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AccountComponent ...

### Mention any other details that might be useful.
ng serve runs fine but not the ng build --prod

**Comment by deebloo** [comment]
@doczoidberg  can you share the offending code?

**Comment by doczoidberg** [comment]
```
...

@Component({

  selector: 'footer',
  template: require('./footer.html'),
  styles: [require('./footer.css')],
})
export class Footer {
...
```

**Comment by elmccd** [comment]
I have the same issue using '@ngtools/webpack', when I try to use require to load an HTML file.

**Comment by deebloo** [comment]
@doczoidberg can you try without the require?  the cli uses a loader under the hood to inline the resources.

```TS
@Component({
  selector: 'footer',
  template: './footer.html',
  styleUrls: ['./footer.scss']
})
```

**Comment by doczoidberg** [comment]
this does not work. ./footer.html is rendered as a string not the file.

**Comment by deebloo** [comment]
Apologies. I meant templateUrl

**Comment by doczoidberg** [comment]
the error is gone
