### ISSUE TITLE
proxy config is not working after build the code by ng build . I am not using json files. I am consuming rest api. So I need proxy config after build the code.

### ISSUE THREAD

**Issue by uyadav0001** [angular/angular-cli#4457]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Equinox** [comment]
It's a good idea to fill out the template provided as it helps explain what issue you're facing, and makes it easier to help you.

**Comment by deebloo** [comment]
@uyadav0001 proxy config is only for the dev server when using ```ng serve``` if you need a proxy in production you will have to configure your own server.

**Comment by hansl** [comment]
Closing this; please refill with the template and provide an example project for complex issues.
