### ISSUE TITLE
Underscore as external library

### ISSUE THREAD

**Issue by Vi-dot** [angular/angular-cli#4459]
Hello,

I'm trying to include underscore as external library but it doesn't work.

During execution on firefox, I get this error :
```
__WEBPACK_IMPORTED_MODULE_3_underscore__.groupBy is not a function
```

There are the source files :

- in **package.json**
```
"dependencies": {
    "underscore": "1.8.3"
    ...
},
"devDependencies": {
    "@types/underscore": "1.7.36"
    ...
}
```

- in **angular-cli.json**
```
"scripts": [
   "../node_modules/underscore/underscore.js"
   ...
]
```
- in **polyfills.js**
```
...
import 'underscore/underscore';
```

- in **my-component.ts**
```
import * as underscore from 'underscore';
...
var res = underscore.groupBy([1.3, 2.1, 2.4], function(num){ return Math.floor(num); });
console.log(res);
```

Thank you for your help

**Comment by grizzm0** [comment]
I'm using lodash myself (instead of underscore). All I've got is the following. Nothing in angular-cli.json or polyfills.js. Works fine.

- package.json

```
  "dependencies": {
    "lodash": "^4.16.4"
  },
  "devDependencies": {
    "@types/lodash": "^4.14.37"
  }
```

- my-component.ts

`import * as _ from 'lodash';`

**Comment by Vi-dot** [comment]
I'm trying with lodash, with your process and same versions, but I have those errors

```
[default] /it/node_modules/@types/lodash/index.d.ts:244:13 
    Duplicate identifier '_'.
[default] /it/node_modules/@types/lodash/index.d.ts:244:16 
    Cannot find namespace '_'.
[default] /it/node_modules/@types/lodash/index.d.ts:246:25 
    Cannot find name 'Partial'.
...
[default] /it/node_modules/@types/lodash/index.d.ts:19258:23 
    Cannot find namespace '_'.
[default] /it/node_modules/@types/lodash/index.d.ts:19281:21 
    Cannot find namespace '_'.
[default] /it/node_modules/@types/lodash/index.d.ts:19441:1 
    Declaration or statement expected.
[default] Checking finished with 140 errors
```

**Comment by grizzm0** [comment]
Could you run `rm -rf node_modules && npm install`

**Comment by Vi-dot** [comment]
It gives the same errors :/

I found that an other library previously included in the project has already **lodash** as dependency.
Then if I remove lodash from _package.json_ and _node_modules_, **lodash** is still downloaded in _node_modules_.
But it's not the same for **@types/lodash**, then I add only this one in _package.json_ to get it.. and it gives the same errors.

**Comment by Vi-dot** [comment]
It was because I had a old version of angular-cli, I updated angular-cli and changed its version in package.json. And now it works.
Thx for your help @grizzm0

**Comment by grizzm0** [comment]
@Vi-dot Could you please close your issue as it's solved? Thanks.
