### ISSUE TITLE
ng build --prod is throwing error.

### ISSUE THREAD

**Issue by MateenKadwaikar** [angular/angular-cli#4461]
### OS?
> Windows 10. 

### Versions.
@angular/cli: 1.0.0-beta.30
node: 7.5.0
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6
@ngtools/webpack: 1.2.8

### Repro steps.
> Whenever I try to build the ng app by "ng build --prod" I always get the below error message.
> ng build does create the dist folder.
> I tried remove all my node_modules files and reinstalled again. I did ng clean too. But no luck.

### The log given by the failure.
>ERROR in Can't resolve all parameters for provideLocationStrategy in F:/On-Going Code/MGM/MGMWeb/node_modules/@angular/router/src/router_module.d.ts: ([object Object], ?, [object Object]).
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'F:\On-Going Code\MGM\MGMWeb\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

**Comment by deebloo** [comment]
@MateenKadwaikar can you provide a minimal example repo that throws this error? It seems like you are missing an import somewhere. Is it working correctly when not doing a prod build or serving?

**Comment by MateenKadwaikar** [comment]
@deebloo  yes my code is working correctly when I doing ng build or ng serve.  I am able to run the code properly. The time I get error is when I do ng build --prod. Attached please find screenshot for the ng serve.
![image](https://cloud.githubusercontent.com/assets/6949959/22658560/897daba8-ecc0-11e6-8a2e-a242eb995fb7.png)

**Comment by MateenKadwaikar** [comment]
@NgModule({
  declarations: [
  
  ],
  imports: [
   
  ],
  providers: [ { provide: LocationStrategy, useClass: HashLocationStrategy }],
  bootstrap: []
})

@deebloo  here is my app.module.ts file.

**Comment by papaiatis** [comment]
I generated my angular app with ng cli version 1.0.0-beta.28.
When I try to execute `ng build --prod` I'm getting this error:

```
It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and has a lot of improvements including a simpler
workflow, a faster build, and smaller bundles.

To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14
```

**Comment by MateenKadwaikar** [comment]
@papaiatis I get the error for the project in which I am using providers: [ { provide: LocationStrategy, useClass: HashLocationStrategy }] . Are you using the same in your project ?

**Comment by papaiatis** [comment]
Sorry, my bad. I changed the "version" in angular-cli.json because, I though it is my application's version.

**Comment by MateenKadwaikar** [comment]
Any update I am still facing the same issue.

**Comment by MateenKadwaikar** [comment]
Some module was giving error. I  removed and check each module which was giving an error.

**Comment by generalcss** [comment]
Had the same problem, turned a class was written as an '@Injectable()' but was used as a normal class. Therefore the builder crashed during optimising (I guess).
