### ISSUE TITLE
Unable to run unit tests using npm scripts

### ISSUE THREAD

**Issue by m0t0r** [angular/angular-cli#4463]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Linux (Ubuntu). Mac OSX (El Capitan)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
@angular/cli: 1.0.0-beta.30
node: 6.9.1
os: darwin x64
```
### Repro steps.

I have npm script to run unit tests on CI

```
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "npm run ng -- test --single-run"
   ...
```
when I try to run `npm t` I get an error as shown below. It was working fine before beta.30.
### The log given by the failure.

`You have to be inside an angular-cli project in order to use the test command.`

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@m0t0r check my answer here https://github.com/angular/angular-cli/issues/4439#issuecomment-277576090 , i think your issue is related.

**Comment by m0t0r** [comment]
@beeman, yes that helped, thanks a lot!

**Comment by m0t0r** [comment]
@hansl, would it possible to add a note on migration from `angular-cli` `beta.28 ` to `@angular/cli` `beta.30` that there should not be any devDependency on `angular-cli`in package.json as it seems to cause different issues. I can do a PR if you could guide where it should be added. Thank you

**Comment by beeman** [comment]
@m0t0r I'm working on a check that detects this. Hope to have it in the cli within the next release

**Comment by m0t0r** [comment]
@beeman great, thanks!
