### ISSUE TITLE
ERROR in compiler_1.StaticSymbolCache isnt a constructor

### ISSUE THREAD

**Issue by wgbn** [angular/angular-cli#4464]
I have gotten the following error when using ng serves in my angular-cli project:

**ERROR in compiler_1.StaticSymbolCache isnt a constructor**

This has not affected in any way the behavior of my project itself, but it causes NG Serve's live-reload to stop working.

I can not identify what is causing this error.

### OS?
Xubuntu 16.04

### Versions.
angular-cli: 1.0.0-beta.26
node: 6.9.4
os: linux x64
@angular/common: 2.2.3
@angular/compiler: 2.2.3
@angular/core: 2.4.5
@angular/forms: 2.2.3
@angular/http: 2.2.3
@angular/platform-browser: 2.2.3
@angular/platform-browser-dynamic: 2.2.3
@angular/router: 3.2.3
@angular/compiler-cli: 2.4.5

### Repro steps.
This application was created totallyb using the cli.
This is my package.json content:

```
{
  "name": "viva-ads-module",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.4.5",
    "@angular/compiler": "^2.2.3",
    "@angular/core": "^2.4.5",
    "@angular/forms": "2.4.5",
    "@angular/http": "2.4.5",
    "@angular/platform-browser": "2.4.5",
    "@angular/platform-browser-dynamic": "2.4.5",
    "@angular/router": "3.4.5",
    "angular-cli": "^1.0.0-beta.26",
    "angular2-materialize": "^6.3.0",
    "angularfire2": "^2.0.0-beta.6",
    "core-js": "^2.4.1",
    "css-loader": "^0.26.1",
    "firebase": "^3.6.4",
    "hammerjs": "^2.0.8",
    "jquery": "^3.1.1",
    "materialize-css": "^0.98.0",
    "ngx-uploader": "^2.0.12",
    "rxjs": "^5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.4.5",
    "@types/jasmine": "2.5.41",
    "@types/node": "^7.0.4",
    "angular-cli": "^1.0.0-beta.26",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.1",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.4.0",
    "protractor": "5.0.0",
    "ts-node": "2.0.0",
    "tslint": "^4.0.2",
    "typescript": "~2.1.5",
    "webdriver-manager": "11.1.1"
  }
}
```

### The log given by the failure.
ERROR in compiler_1.StaticSymbolCache is not a constructor

**Comment by cagline** [comment]
I'm having same issue
`{
  "name": "payd-webclient",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "^2.1.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "^2.1.2",
    "@angular/router": "3.0.0",
    "angular-pipes": "^5.8.2",
    "core-js": "^2.4.1",
    "material-design-lite": "^1.2.1",
    "ng2-img-cropper": "^0.7.7",
    "ng2-translate": "^3.1.3",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0-beta.31",
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.16",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "ng2-pagination": "^0.5.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}
`

**Comment by mikeeus** [comment]
same here

                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
@angular/cli: 1.0.0-beta.31
node: 6.9.4
os: linux x64
@angular/common: 2.2.1
@angular/compiler: 2.2.1
@angular/core: 2.4.7
@angular/forms: 2.2.1
@angular/http: 2.2.1
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.2.1
@angular/platform-browser-dynamic: 2.2.1
@angular/router: 3.2.1
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

**Comment by norricorp** [comment]
Same here - updated node from 4 to 6.9.5, angular from beta 16 to beta 31.
Only difference to above is that OS is windows.
Followed upgrade instructions at https://github.com/angular/angular-cli#updating-angular-cli

**Comment by norricorp** [comment]
And upgraded to beta 32 and still same problem.
Is there any help on this?

**Comment by SanderElias** [comment]
@norricorp have you tried removing the node_modules folder followed by an `npm install`?

**Comment by wgbn** [comment]
Guys, I fixed my problem.
The message that the "angular-cli was deprecated" began to appear.
So I removed the "angular-cli" from my project and globally and replaced it with "@angular/cli".
After this change everything went back to working as before.

**Comment by norricorp** [comment]
C:\Temp\angularjs_example\angular2\heroes_new>ng --version
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.31]
node: 6.9.5
os: win32 x64
@angular/common: 2.2.1
@angular/compiler: 2.2.1
@angular/core: 2.4.7
@angular/forms: 2.2.1
@angular/http: 2.2.1
@angular/platform-browser: 2.2.1
@angular/platform-browser-dynamic: 2.2.1
@angular/router: 3.2.1
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.7

Mine already says @angular/cli so it may be a premature close.
Yes I did delete node_modules and dist as the update instructions specify.
