### ISSUE TITLE
Problem with ng serve -  reflect-metadata shim 

### ISSUE THREAD

**Issue by MikeNats** [angular/angular-cli#4467]
### OS.
 > Mac OSX  El Capitan.

### Versions.
> angular-cli: 1.0.0-beta.28.3
> node: 6.9.5

### Repro steps.
> `ng new projectName --style=sass`

### The log given by the failure.
> ONLY in FireFox getting error messages:
> `NS_ERROR_FACTORY_NOT_REGISTERED: polyfil...ndle.js (line 2201)`
> `uncaught exception: reflect-metadata shim is required when using class decorators`

I have `npm i reflect-metadata --save` and imported it in `polyfills.ts`
The error is still there!!!

**Comment by filipesilva** [comment]
Are you still getting this problem? If so, can you provide a simple repro?

**Comment by filipesilva** [comment]
Closing as inactive.
