### ISSUE TITLE
Question: How to generate a library project?

### ISSUE THREAD

**Issue by battmanz** [angular/angular-cli#4468]
I would like to generate a library project. What I mean by that is that project will be published as an npm module and used by other projects. The project will not be run by itself. So it doesn't need an index.html file or global styles.css file or any e2e tests. 

My question is, does it make sense to use the angular cli for this? Would it make sense for the angular cli to have an option for generating a library type project?

**Comment by beeman** [comment]
@battmanz dupe of #4247,  see my comment here https://github.com/angular/angular-cli/issues/4247#issuecomment-275586177

**Comment by battmanz** [comment]
Wow! Thanks for the quick reply! Closing as a dupe.
