### ISSUE TITLE
Issues with angular-cli and node docker official image.

### ISSUE THREAD

**Issue by omata-metamax** [angular/angular-cli#4471]
Hello,

I'm new with angular, so I'm using the `node:6.9.4-alpine` to get `angular-cli` installed to create a development docker image. So even when all is working I can't connect to the exposed port from outside the container. You can read the related history from [here](https://github.com/nodejs/docker-node/issues/326), where I posted the issue on the node official docker image and I figured out that the issue was not related with node image, but with **angular-cli**. Anyone has a clue about what is happening?

angular-cli version:

```
angular-cli@1.0.0-beta.28.3
```

Another issue that I found is related with project creation. when I issue `ng new project` it fails when npm is installing modules, but if I issue `ng new project --skip-npm` and then I run `npm install` it works without errors.

Best regards.

**Comment by clydin** [comment]
As per the readme (https://github.com/angular/angular-cli/blob/master/README.md#usage), you can set the bound host and port via the `--host` and `--port` arguments.

**Comment by omata-metamax** [comment]
Thanks for the reply

> As per the readme (https://github.com/angular/angular-cli/blob/master/README.md#usage), you can set the bound host and port via the --host and --port arguments.

The issue is not related with bounding port perse, but with binding any bounded port from angular to a docker container, please read the related [link](https://github.com/nodejs/docker-node/issues/326) in my previous post, to get some background. The port by default works fine from inside the container when I issue `curl http://localhost:8080`, but not from outside it. I had test bounding ports `8080`, `4200`, and random with the same result.

You can reproduce the issue as follow:

```bash
docker pull node:6.9.5-alpine
docker run --name test -ti --rm -p 4200:4200 node:6.9.5-alpine sh
```

From inside docker container
```bash
npm install angular-cli -g
ng new test1 --skip-npm
cd test1
npm install
ng server
```

Then go to your browser and try `http://localhost:4200` You will see an error with a connection refuse message. But you can go inside the container and try:

```bash
apk --update add curl ca-certificates
curl http://localhost:4200
```

You will state that the connection is made without issues from inside the docker container.

Regards.

**Comment by delasteve** [comment]
Under `defaults` in your `angular-cli.json` you can do the following:

```json
serve: {
  port: 4200,
  host: '0.0.0.0'
}
```

**Comment by filipesilva** [comment]
Closing as answered, thanks @clydin and @delasteve !

**Comment by imar26** [comment]
Hi All,

I tried the steps mentioned above by @omata-metamax and @delasteve 

I am still not able to load my app in the browser. Please let me know if I am missing anything. 

Below is my Dockerfile

`FROM node:8.9.4

RUN mkdir /usr/src/app

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json /usr/src/app/

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . /usr/src/app

EXPOSE 4200

CMD [ "npm", "start" ]`

Any help would be appreciated. Thanks!
