### ISSUE TITLE
ElasticSearch / Import module

### ISSUE THREAD

**Issue by kamalkech** [angular/angular-cli#4472]
### OS?
> Windows 10

### Versions.
angular-cli: 1.0.0-beta.28.3
node: 6.9.4
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

### Versions Elastic Search
5.x

### Repro steps.
> I follow solution of this issue #2503 but not working
import * as elasticsearch from 'elasticsearch';

### Get error:
 Cannot find module 'elasticsearch'

**Comment by deebloo** [comment]
does elasticsearch come with typings? If not try installing this https://www.npmjs.com/package/@types/elasticsearch. I believe that would allow you to import the module.

**Comment by kamalkech** [comment]
@deebloo yep it's work after install @types/elasticsearch, thank you ;)
