### ISSUE TITLE
UNMET PEER DEPENDENCY Error occurred When I have use another module in my project 

### ISSUE THREAD

**Issue by smartHasmukh** [angular/angular-cli#4477]
**I have checked UNMET PEER DEPENDENCY related all issues and have tried as well but not found this issue.**

UNMET PEER DEPENDENCY @angular/common@2.3.1
├── UNMET PEER DEPENDENCY @angular/compiler@2.3.1
├── UNMET PEER DEPENDENCY @angular/core@2.3.1
├── @angular/material@2.0.0-beta.1 
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.3.1
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
└── UNMET PEER DEPENDENCY zone.js@0.6.26

UNMET PEER DEPENDENCY @angular/common@2.3.1
├── UNMET PEER DEPENDENCY @angular/compiler@2.3.1
├── UNMET PEER DEPENDENCY @angular/core@2.3.1
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.3.1
├── md2@0.0.10-2 
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
└── UNMET PEER DEPENDENCY zone.js@0.6.26

UNMET PEER DEPENDENCY @angular/common@2.3.1
├── UNMET PEER DEPENDENCY @angular/compiler@2.3.1
├── UNMET PEER DEPENDENCY @angular/core@2.3.1
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.3.1
├── ng2-slimscroll@1.2.1 
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
└── UNMET PEER DEPENDENCY zone.js@0.6.26

UNMET PEER DEPENDENCY @angular/common@2.3.1
├── UNMET PEER DEPENDENCY @angular/compiler@2.3.1
├── UNMET PEER DEPENDENCY @angular/core@2.3.1
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.3.1
├── ng2-auto-complete@0.8.9 
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
└── UNMET PEER DEPENDENCY zone.js@0.6.26

UNMET PEER DEPENDENCY @angular/common@2.3.1
├── UNMET PEER DEPENDENCY @angular/compiler@2.3.1
├── UNMET PEER DEPENDENCY @angular/core@2.3.1
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.3.1
├── angular2-select@1.0.0-beta.2 
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
└── UNMET PEER DEPENDENCY zone.js@0.6.26

**I have installed** `npm install -g @angular/cli` 

![cli](https://cloud.githubusercontent.com/assets/8941195/22679256/be2ca1b8-ed26-11e6-9d77-6fa7aa5e63e1.png)

![material](https://cloud.githubusercontent.com/assets/8941195/22679219/60700236-ed26-11e6-9362-0421ca328a7a.png)
![md2](https://cloud.githubusercontent.com/assets/8941195/22679220/60703652-ed26-11e6-861b-95a5cd4e1096.png)
![scroll_issue](https://cloud.githubusercontent.com/assets/8941195/22679221/6071e754-ed26-11e6-963c-926bbe20c1a7.png)
![autocomplete](https://cloud.githubusercontent.com/assets/8941195/22679223/6073632c-ed26-11e6-8e38-59870b11c6f4.png)
![angularselect](https://cloud.githubusercontent.com/assets/8941195/22679222/60733294-ed26-11e6-92ce-60157199aa88.png)

**Comment by smartHasmukh** [comment]
Please help me @evmar @jesperronn @mprobst @miguel4ngelc @gonzaloruizdevilla @hansl @chaeusler @changLiuUNSW

**Comment by edelCustodio** [comment]
Also I got the similar error.

![image](https://cloud.githubusercontent.com/assets/7378797/22767601/6779ae18-ee4a-11e6-8849-2a0b656564a6.png)

Any help?

**Comment by catull** [comment]
That is for the moment, something to ignore.
Do you incur other errors ?

Can you create a simple app, and `ng serve` it ?
Those are issues to report, not some colorful warnings.

**Comment by smartHasmukh** [comment]
sure @catull

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/4473
