### ISSUE TITLE
Flakey-ness in e2e tests with `ng serve`

### ISSUE THREAD

**Issue by gkalpak** [angular/angular-cli#4478]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
All

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
1.0.0-beta.29

### Mention any other details that might be useful.
In order to run e2e tests, one has to run `ng serve` and `ng e2e` in parallel. Now, because `ng serve` does some preprocessing before serving (webpack build), it seems that protractor may timeout before the Angular app is served. This leads to flakey-ness on CI.

We (think we) have run into this [here][1] (which is a cli-generated app), but this issue will probably affect all projects using the cli. I think @filipesilva was running into something similar recently. We have tried several things, from [increasing timeouts][2] to [other hacks][3], but a more robust solution is necessary.

Something like [this helper][4] might be useful for users or maybe another way is more appropriate. But it sounds like something that would benefit most users and it would be nice if the cli provided an easy way out.

cc @IgorMinar 

[1]: https://github.com/angular/angular/tree/80b66edfa7cfb34f5cddd2ca9710462f40ed6bb4/angular.io
[2]: https://github.com/angular/angular/blob/fb91b2f/angular.io/protractor.conf.js#L9
[3]: https://github.com/wardbell/angular/blob/6ac593d38e76f9f1123abfeb4780e0227f47eed2/angular.io/e2e/app.e2e-spec.ts#L6-L10
[4]: https://github.com/angular/angular-cli/blob/7bd165b12600137da7d6ad5a73c93bd184ff09da/tests/e2e/utils/project.ts#L27-L30

**Comment by filipesilva** [comment]
My usual solution to this is to not use `ng serve` for e2e tests in CI. Instead I use a simpler static server (like `lite-server`), which is guaranteed to start up fast.

Something like this (in terms of npm scripts):
```
    "pree2e": "ng build",
    "e2e": "concurrently \"lite-server\" \"npm run protractor\" --kill-others --success first",
```

I recognize the convenience of not having to manage processes to run e2e tests though. Maybe as part of https://github.com/angular/angular-cli/issues/4256 a new flag could be introduced that would manage this on the CLI side.

Hypothetically something like `ng e2e --serve`, defaulting to true.
