### ISSUE TITLE
How To: Limit console output?

### ISSUE THREAD

**Issue by schmuli** [angular/angular-cli#4486]
### OS

Windows 10

### Versions

```
@angular/cli: 1.0.0-beta.30
node: 7.2.1
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/material: 2.0.0-beta.1
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6
```

### Question
How can I limit or turn off progress information when running @angular/cli for a specific environment?

Running `ng test` on a CI (such as Circle CI) prints so much output to the console, over 400,000 characters, that the whole output cannot be viewed in the browser, and must be downloaded as a file.

This happens since when building with Webpack, a lot of progress details are printed to the console, which is usually replaced on update. However, Circle CI doesn't support replacing and instead just prints everything received, including the `backspace` characters.

**Comment by grizzm0** [comment]
`ng build --prod --progress=false`

**Comment by schmuli** [comment]
Okay, so I found it: https://github.com/angular/angular-cli/pull/2858
