### ISSUE TITLE
Problems with loading image or parse img tag

### ISSUE THREAD

**Issue by prsolucoes** [angular/angular-cli#4488]
### OS?
> Mac OSX (El Capitan)

### Versions.
> @ngtools/webpack@1.2.7 or @ngtools/webpack@1.2.8

### Repro steps.
> git clone https://github.com/prsolucoes/angular-starter-project.git
> cd angular-starter-project
> [change on @ngtools/webpack dependency from 1.2.6 to 1.2.7 or 1.2.8]
> npm install
> npm start

### The log given by the failure.
> No error log

### Mention any other details that might be useful.
> The image tag is there, but the image is not copied to memory or dist folder. But it works on version 1.2.6.

**Comment by RicardoVaranda** [comment]
This has nothing to do with Angular Cli, the issue should be reported on https://github.com/prsolucoes/angular-starter-project/

**Comment by prsolucoes** [comment]
It has a dependency of ngtools/webpack@1.2.7 or ngtools/webpack@1.2.8. With this two versions IMG tag was not parsed and images was not copied to dist folder.

**Comment by donovankim** [comment]
it breaks my project. 
+1

**Comment by prsolucoes** [comment]
I have tested with 1.2.9 and problems still happen.

**Comment by prsolucoes** [comment]
Any solution to this problems?

**Comment by gniewkos** [comment]
+1 The same problem for 1.2.9

**Comment by prsolucoes** [comment]
My problem was solved using last release version: 1.2.12

https://github.com/prsolucoes/angular-starter-project
