### ISSUE TITLE
Is it possible to not output the favicon.ico and the index.html when running the "ng build" command?

### ISSUE THREAD

**Issue by jaygazula27** [angular/angular-cli#4492]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
> angular/cli: 1.0.0-beta.30
  node: 6.9.1
  os: win32 x64
  angular/common: 2.4.6
  angular/compiler: 2.4.6
  angular/core: 2.4.6
  angular/forms: 2.4.6
  angular/http: 2.4.6
  angular/platform-browser: 2.4.6
  angular/platform-browser-dynamic: 2.4.6
  angular/router: 3.4.6
  angular/cli: 1.0.0-beta.30
  angular/compiler-cli: 2.4.6

### Repro steps.
> Created an angular app in an existing directory using `ng init`.

### The log given by the failure.
> None

### Mention any other details that might be useful.
I'm using a Java backend where I'm serving an HTML page which includes server-side tags (like JSPs) within the HTML. Therefore, I would like to still use the same HTML page I have right now.
My plan is to use `ng build` to produce the transpiled JS files, and then manually include them in the script tags within the already existing HTML file (the one that includes the server side tags). 

Now granted, this isn't really a big deal and is not urgent. Currently, I'm just ignoring the favicon.ico and index.html that is produced by the `ng build`. However, it's not as clean as I would like because the output is in my JS file of my project. Ideally, I just want that folder to only have JS files and not the favicon.ico and index.html

Thanks for your help!

**Comment by grizzm0** [comment]
favicon is part of the assets array in angular-cli.json. The index.html output can not be disabled.

**Comment by jaygazula27** [comment]
Thanks for the response! I hope eventually there's an option to turn off the output of the html file as well.
