### ISSUE TITLE
I tried install nodemon and i get this crash error

### ISSUE THREAD

**Issue by LunaBawa** [angular/angular-cli#4494]
Fist it started by skipping dependable which i had to install one after the other still the crash report seems to be constant. 

Any idea why?

![image](https://cloud.githubusercontent.com/assets/11213175/22698229/4b9fcd5e-ed54-11e6-91cd-ae127c3ed2cd.png)

> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by LunaBawa** [comment]
This is my package.json file

![image](https://cloud.githubusercontent.com/assets/11213175/22698359/9d65e4de-ed54-11e6-907d-1a292b4ea03b.png)

**Comment by grizzm0** [comment]
This does not seem to have anything to do with angular-cli. Did you post this issue to the wrong repo?

**Comment by LunaBawa** [comment]
True....sorry
