### ISSUE TITLE
ng build -prod uglify?

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#4498]
I just wondered if there is an option to uglify the compiled JavaScript.
I don't want my variable- and function-names to show up in code. Also it would save alot of space.

I read on a page that `ng build -prod` does uglify, but i don't see that in my dist folder. Maybe it got removed? Or is there any option i'm missing?

**Comment by hansl** [comment]
We do run Uglify on your code, but unfortunately Uglify does not rename properties, only function and variable names. A lot of your methods will be properties and not renamed by Uglify. We're looking at solutions but for the time being this is probably not going to change.
