### ISSUE TITLE
--dry-run creates empty folder

### ISSUE THREAD

**Issue by niklas-dahl** [angular/angular-cli#4500]
### OS?
> Windows 7

### Versions.
@angular/cli: 1.0.0-beta.30
node: 7.5.0
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
1. `ng new proj && cd proj`
2. `ng g module settings3 --routing --dry-run`

```
λ ng g module settings3 --routing --dry-run
installing module
You specified the dry-run flag, so no changes will be written.
  create src\app\settings3\settings3-routing.module.ts
  create src\app\settings3\settings3.module.ts
installing component
You specified the dry-run flag, so no changes will be written.
  create src\app\settings3\settings3.component.css
  create src\app\settings3\settings3.component.html
  create src\app\settings3\settings3.component.spec.ts
  create src\app\settings3\settings3.component.ts
```
Despite saying no changes will be written an empty folder `src/app/settings3` is created.

### Mention any other details that might be useful.
Without the `routing` flag no empty folder is generated.

**Comment by delasteve** [comment]
I just attempted this with `rc.0` and was not able to reproduce it.

```
test-app (master) » ng g module settings3 --routing --dry-run
installing module
You specified the dry-run flag, so no changes will be written.
  create src/app/settings3/settings3-routing.module.ts
  create src/app/settings3/settings3.module.ts
```

```
test-app (master) » ls src/app
app.component.css     app.component.html    app.component.spec.ts app.component.ts      app.module.ts
```

**Comment by niklas-dahl** [comment]
from https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#breaking-changes-1

> 1.0.0-beta.32 (2017-02-17)
> ...
> BREAKING CHANGES
> ...
> @angular/cli: Generating a module with routing will no longer generate an associated component.

Thats probably why..
