### ISSUE TITLE
Install angular CLI ends with Warning  

### ISSUE THREAD

**Issue by sandrobirke** [angular/angular-cli#4505]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX (Sierra 10.12.2)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-beta.30
node: 7.5.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

After Install the following Warning in Terminal:

npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.

How can i fix it? Every Results from google failed

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vovikdrg** [comment]
1. Try to remove node_modules folder
2. in package.json check if you allow to install latest rxjs should be similar to **"rxjs": "^5.0.1",**
3. run npm install.

**Comment by MarcelCorleone** [comment]
Did you install globally? The rxjs is only needed locally in the app itself (in the package.json), hence the warning.

**Comment by sandrobirke** [comment]
@MarcelCorleone Yes, i installed globally. package.json looks good. Means i can get ignore the warning?

**Comment by vovikdrg** [comment]
@sandrobirke  run command "npm ls rxjs"

**Comment by MarcelCorleone** [comment]
@sandrobirke Yes. Refer to this: https://github.com/angular/angular-cli/issues/4357

**Comment by catull** [comment]
@sandrobirke Do you still have an issue with this ?  If not, as a common curtesy, could you please close the issue ?

**Comment by catull** [comment]
@sandrobirke Still having this problem ? Did you try with the latest, such as `npm install -g @angular/cli@latest` ?

**Comment by filipesilva** [comment]
This has been fixed since. Sorry about that.
