### ISSUE TITLE
Broken ng serve auto-refresh

### ISSUE THREAD

**Issue by cclow** [angular/angular-cli#4511]
### OS?
Mac OSX Sierra (10.12.3)

### Versions.
@angular/cli: 1.0.0-beta.30
node: 7.4.0
os: darwin x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6

### Repro steps.
I'm running `ng serve` to use the live reload in my development.
If I create a new component, say with `BoardComponent` with selector `app-board`, and add the `app-board` element to a parent's template **before** I declare `BoardComponent` in the Module, I get an error in the browser complaining that "app-board is not a known element". Even if we now remove the element from the parent's template, the error does not go away.

1. `ng serve` does not show any error, and restarting `ng serve` removes the browser error.
2. This does not occur if I declare `BoardComponent` in the Module before I add the element to the parent's template.

This is a problem because it disrupts the development workflow.

### The log given by the failure.
From browser console:

> Unhandled Promise rejection: Template parse errors:
'app-board' is not a known element:
> 1. If 'app-board' is an Angular component, then verify that it is part of this module.
> 2. If 'app-board' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

**Comment by ifynk** [comment]
I have some problem too. I just create new application with **ng new**. Then i started **ng serve**. Webpack compiled successfully. If i change template file or css then recompiled successful and live reload works. But if i change some in .ts files then live reloading not works and .ts files not compiled. Although webpack shown compiled successfully.

OS: Ubuntu 16.04 LTS
Node: v7.4.0
Npm: 4.0.5

`{
  "name": "slots",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-beta.30",
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }
}
`
