### ISSUE TITLE
errors while livereload app

### ISSUE THREAD

**Issue by felek000** [angular/angular-cli#4516]
### OS?
> Windows1- 

### Versions.
@angular/cli: 1.0.0-beta.30
node: 6.9.1
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6

### Repro steps.
Update from beta 24, or new project

I see at start fallbackLoader option has been deprecated - replace with "fallback", but compilation is going on.

After i made any changes in component there is recompilation and reload page event but No chages detect so i have to rebuild content ng serve again and agian

on my prev project on beta 24 all works fine....

**Comment by felek000** [comment]
I follow all steps but its no working i start on fresh or update project any diffidence. Even if i Manually refresh it by CTRL + R. Still no working proper. Some times also cant even do ng build.

After update component.
```
[WDS] App updated. Recompiling...
client?93b6:38 [WDS] Nothing changed.
```

**Comment by catull** [comment]
@felek000 Did you check #4515 and the solution described there?
Is it still an issue ?

**Comment by felek000** [comment]
I will try it in few days and report back.

**Comment by felek000** [comment]
After update to beta 31 it worked. I create new project then copy paste all to old one.
