### ISSUE TITLE
gives 404 not found error on refresh the url in production.

### ISSUE THREAD

**Issue by uyadav0001** [angular/angular-cli#4519]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
This isn't an issue with the CLI. By default angulars router uses the history API. Because of this you will need to set up your server to always redirect to index.html or change the location strategy to hashLocationStrategy.

**Comment by deebloo** [comment]
Also in the future please fill out the issue template

**Comment by filipesilva** [comment]
Closing as answered.
