### ISSUE TITLE
Can't import tether library

### ISSUE THREAD

**Issue by wm1sr** [angular/angular-cli#4522]
### OS?
Windows 10

### Versions.
@angular/cli: 1.0.0-beta.30
node: 6.9.1
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6

### Repro steps.

1. Run `ng new my-project`
2. Install any library (I tried tether, tether-drop and physicsjs), using `npm install library --save`
3. In the `app.component.ts` import the library using `import * as Tether from 'tether'` (I tried `import Tether from 'tether'` but the same problem occurs)
4. run `ng serve`

### The log given by the failure.
```
ERROR in C:/path/to/project/src/app/app.component.ts (4,21): Cannot find module 'tether'.)
webpack: Failed to compile.
```

### Mention any other details that might be useful.

I don't know if that's useful, but right after I execute `ng serve` this is printed out:
```
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
** NG Live Development Server is running on http://localhost:4200. **
Hash: 302e581564dd4cf9fb57
Time: 9261ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.map (main) 4.22 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 10.1 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.62 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
```

I'm a newbie with angular 2 and angular-cli, so I appreciate any help. Thanks in advance.

**Comment by deebloo** [comment]
@wm1sr try including https://www.npmjs.com/package/@types/tether. This is actually an issue with Typescript. In order for Typescript to import a module it needs typings so it knows about it.

**Comment by wm1sr** [comment]
@deebloo ok, I've added @types/tether and it works! 
But what about libraries that don't have typings? I won't be able to use them?

**Comment by filipesilva** [comment]
@wm1sr see https://github.com/angular/angular-cli#3rd-party-library-installation for instructions on how to use libraries without typings.
