### ISSUE TITLE
Angular2(2.4.6) with latest cli giving error on ng serve in browser

### ISSUE THREAD

**Issue by pritspatel** [angular/angular-cli#4534]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Window 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
2.4.6

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
No, it was built with angular-cli beta 18

### The log given by the failure.
> Normally this include a stack trace and some more information.

Unhandled Promise rejection: appInits[i] is not a function ; Zone: ; Task: Promise.then ; Value: TypeError: appInits[i] is not a function

### Mention any other details that might be useful.

NG-CLi - 1.0.0-beta.28.3
Angular2 : 2.4.6
here is my function in app.module.ts

 export function authFactory(auth : LoginService){
  return auth.loginUser();
}

Providers are reference like this in app.module.ts

{
  provide: APP_INITIALIZER,
  //useFactory: (auth: AuthService) => () => auth.authUser(),
  useFactory : authFactory,
  deps: [LoginService],
  multi: true
}

When app runs, browser is giving error

Unhandled Promise rejection: appInits[i] is not a function ; Zone: ; Task: Promise.then ; Value: TypeError: appInits[i] is not a function

**Comment by deebloo** [comment]
@pritspatel can you show your package.json?

**Comment by filipesilva** [comment]
@pritspatel please provide a simple repro, without it we can't investigate.

**Comment by choucry13** [comment]
any news about that ?

**Comment by filipesilva** [comment]
Closing as abandoned, original author never provided repro.

**Comment by choucry13** [comment]
@filipesilva , okay thank you

**Comment by GopiAnnan** [comment]
Still any one looking for answer on this, 

Instead of this
export function authFactory(auth : LoginService){
return auth.loginUser();
}
has to be changed to 
export function authFactory(auth : LoginService){
return () => auth.loginUser();
}

**Comment by chandralanka** [comment]
Thank you @GopiAnnan. Your solution worked.

**Comment by googlicius** [comment]
@GopiAnnan, You saved my life bro.

**Comment by khosiDigital** [comment]
@GopiAnnan WOW!!! I have been searching for a solid week! Thank you so much!

**Comment by inthegarage** [comment]
@GopiAnnan For president, the best solution of 2017. In all environments, for all languages and operating systems.

**Comment by asmith2306** [comment]
@GopiAnnan nice one!

**Comment by VaaniSai** [comment]
@GopiAnnan I tried the solution you suggested. No luck. Still facing the same issue.
Here is how my **app.module.ts** looks like

providers: [{
      provide: APP_INITIALIZER,
      useFactory: InitializeFn,
      deps: [Store],
      multi: true
    }]

export function InitializeFn(store: Store<fromApp.AppState>) {
  store.select('cart')
  .take(1)
  .subscribe(
    (data) => {
      if (data.isCartEmpty) {
        //  todo: should be created only once in 11 months
        console.log("!!!From App Comp subscription-should be executed only once!!!!!");
        // Create cart if doesn't exists
        return () => store.dispatch(new CartActions.CreateCart());
      }}
  );
}

Error: `Unhandled Promise rejection: this.appInits[i] is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: this.appInits[i] is not a function`

**Comment by GopiAnnan** [comment]
Hi,

I think, You suppose to return at  Store level. like below.
return () => store.select('cart')
.take(1)
.subscribe(
(data) => {
if (data.isCartEmpty) {
// todo: should be created only once in 11 months
console.log("!!!From App Comp subscription-should be executed only
once!!!!!");
// Create cart if doesn't exists
return () => store.dispatch(new CartActions.CreateCart());
}});

I think without return also you  can implement

store.select('cart')
.take(1)
.subscribe(
(data) => {
if (data.isCartEmpty) {
store.dispatch(new CartActions.CreateCart());
}});

Note : I have not tested.
