### ISSUE TITLE
Aot compilation succeeds without warnings or errors for bad templates

### ISSUE THREAD

**Issue by cenkentimist** [angular/angular-cli#4538]
Aot compilation succeeds without warnings or errors for bad templates for me. I was unable to find any documentation or hints as to why this might be. Is there any configuration I can do to get the benefits of template type checking from AOT compilation? 
### OS
El Capitan

### Versions.
@angular/cli: 1.0.0-beta.30
node: 7.2.1
os: darwin x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6

### Repro steps.
put a non existent tag such as {{invalid}} in app.component.html in the project generated by `ng new` then do `ng build --aot`

**Comment by nicojs** [comment]
Same here! In addition, file sizes generated by a build with `--aot` is the same as without `--aot`. It doesn't seem to be working for me. `@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.30]`

**Comment by ribizli** [comment]
I can also confirm this: I'm using a custom configuration with only the `@ngtools/webpack` loader, and making an intentional property typo compiles without any error.
I also tried with an initial `@angular/cli` project, writing `{{title2}}` in the _app.component.html_ and it compiles (`ng build --aot`) without any error.

**Comment by filipesilva** [comment]
@hansl can you weigh in?

**Comment by cenkentimist** [comment]
Really cool thanks for the type checking!
