### ISSUE TITLE
UNMET PEER DEPENDENCY webpack@2.2.0  and also 2.2.1

### ISSUE THREAD

**Issue by infofromca** [angular/angular-cli#4539]
please see the scree
![webpack-unmet](https://cloud.githubusercontent.com/assets/297675/22758209/acf04d3c-ee1b-11e6-8e4a-dd284edcec7f.png)
![cli-op](https://cloud.githubusercontent.com/assets/297675/22758341/412d40c2-ee1c-11e6-8c1e-c94bdc1e4cf6.png)

> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
win 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
`{
  "name": "rrm",
  "version": "5.1.1",
  "keywords": [
    "angular2",
    "webpack",
    "typescript"
  ],
  "scripts": {
    "build:dev": "webpack --config config/webpack.dev.js --progress --profile",
    "build:docker": "npm run build:prod && docker build -t angular2-webpack-start:latest .",
    "build": "npm run build:dev",
    "clean:dist": "npm run rimraf -- dist",
    "clean:install": "npm set progress=false && npm install",
    "clean:start": "npm start",
    "clean": "npm cache clean && npm run rimraf -- node_modules doc coverage dist",
    "docker": "docker",
    "github-deploy:dev": "webpack --config config/webpack.github-deploy.js --progress --profile --env.githubDev",
    "github-deploy": "npm run github-deploy:dev",
    "postversion": "git push && git push --tags",
    "prebuild:dev": "npm run clean:dist",
    "preclean:install": "npm run clean",
    "preclean:start": "npm run clean",
    "server:dev:hmr": "npm run server:dev -- --inline --hot",
    "server:dev": "webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/",
    "server": "npm run server:dev",
    "start:hmr": "npm run server:dev:hmr",
    "start": "npm run server:dev",
    "version": "npm run build",
    "watch:dev:hmr": "npm run watch:dev -- --hot",
    "watch:dev": "npm run build:dev -- --watch",
    "watch:prod": "npm run build:prod -- --watch",
    "watch:test": "npm run test -- --auto-watch --no-single-run",
    "watch": "npm run watch:dev",
    "webdriver-manager": "webdriver-manager",
    "webdriver:start": "npm run webdriver-manager start",
    "webdriver:update": "npm run webdriver-manager update",
    "webpack-dev-server": "webpack-dev-server --inline",
    "webpack": "webpack"
  },
  "dependencies": {
    "@angular/common": "2.4.6",
    "@angular/compiler": "2.4.6",
    "@angular/core": "2.4.6",
    "@angular/forms": "2.4.6",
    "@angular/http": "2.4.6",
    "@angular/platform-browser": "2.4.6",
    "@angular/platform-browser-dynamic": "2.4.6",
    "@angular/platform-server": "2.4.6",
    "@angular/router": "3.4.6",
    "@angularclass/conventions-loader": "^1.0.13",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.20",
    "adal-angular": "^1.0.13",
    "angular2-modal": "^2.0.3",
    "assets-webpack-plugin": "^3.5.1",
    "bootstrap": "^3.3.7",
    "bootstrap-loader": "^2.0.0-beta.20",
    "clipboard": "^1.6.0",
    "core-js": "^2.4.1",
    "http-server": "^0.9.0",
    "ie-shim": "^0.1.0",
    "jquery": "^3.1.1",
    "mydatepicker": "1.6.9",
    "ng2-adal": "0.2.8",
    "ng2-pagination": "^2.0.0",
    "ngx-clipboard": "^3.0.5",
    "reflect-metadata": "^0.1.9",
    "rxjs": "5.1.0",
    "zone.js": "~0.7.6"
  },
  "devDependencies": {
    "@types/node": "^7.0.5",
    "@types/source-map": "^0.5.0",
    "@types/uglify-js": "^2.6.28",
    "@types/webpack": "^2.2.5",
    "angular-router-loader": "^0.5.0",
    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "^3.0.3",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "exports-loader": "^0.6.3",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.10.0",
    "html-webpack-plugin": "^2.28.0",
    "imports-loader": "^0.7.0",
    "istanbul-instrumenter-loader": "1.2.0",
    "json-loader": "^0.5.4",
    "node-sass": "^4.5.0",
    "parse5": "^3.0.1",
    "raw-loader": "0.5.1",
    "resolve-url-loader": "^1.6.1",
    "rimraf": "~2.5.4",
    "sass-loader": "^5.0.1",
    "script-ext-html-webpack-plugin": "^1.7.0",
    "source-map-loader": "^0.1.6",
    "string-replace-loader": "1.0.5",
    "style-loader": "^0.13.1",
    "to-string-loader": "^1.1.5",
    "ts-helpers": "1.1.2",
    "ts-node": "^2.0.0",
    "typescript": "2.1.5",
    "url-loader": "^0.5.7",
    "v8-lazy-parse-webpack-plugin": "^0.3.0",
    "webpack": "2.2.0",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-dev-server": "2.3.0",
    "webpack-md5-hash": "^0.0.5",
    "webpack-merge": "~2.6.1"
  },
  "engines": {
    "node": ">= 4.2.1",
    "npm": ">= 3"
  }
}

`
i also try "webpack": "2.2.1", the same result
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
This should be fixed now.
