### ISSUE TITLE
$$_gendir issue

### ISSUE THREAD

**Issue by scttcper** [angular/angular-cli#4555]
Here's the repo https://github.com/scttcper/ngx-toastr

Angular cli is used to manage the tests/github pages/demo

Command used is `ng github-pages:deploy --aot`
package.json is in repo
I'm on osx with node v7.5.0 and have tried with both yarn and npm.

```
ERROR in ./src/$$_gendir/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve '../../../lib/toast-component.ngfactory' in '/Users/scoope7/toastr-ng2/src/$$_gendir/app'
 @ ./src/$$_gendir/app/app.module.ngfactory.ts 37:0-67
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**Comment by Shijir** [comment]
Could be the same as or related to #4551

**Comment by catull** [comment]
You do not state which version of Angular CLI you are using.

**Note**: as of version 1.0.0.beta.28.3 github-pages:deploy has been removed.
You have to use a different npm package in future.

**Comment by scttcper** [comment]
@catull sorry. Its @angular/cli beta.30

I was unaware of the github-pages being removed. Either way, `ng build --prod --aot` throws the same error.

**Comment by badigerroopa007** [comment]
Could you please elaborate? Are you talking about node_modules?
What did you do to fix it?

**Comment by vpozzebon** [comment]
Comigo o problema era o @angular/cli@1.02... Atualizei para @1.2.7 e resolveu...

**Comment by mohamedaboelmagd** [comment]
check your package.json has the same value like that
    "@angular/animations": "4.0.2",
    "@angular/common": "^4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@angular/router": "4.0.2",
