### ISSUE TITLE
Command is not available："ng serve --live-reload false"

### ISSUE THREAD

**Issue by liangzhanyong** [angular/angular-cli#4556]
Use this command start the service,  browsers still automatically refresh after modify the component's code.

### OS
>  Mac OSX 
### Versions.
> 1.0.0-beta.28.3

**Comment by catull** [comment]
I believe the correct syntax is `ng serve --live-reload=false`.
Does that work you ?  Please confirm.

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/3952
