### ISSUE TITLE
ng update should be line ending agnostic

### ISSUE THREAD

**Issue by kaznovac** [angular/angular-cli#4559]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-beta.30
node: 6.9.4
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.7

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
run `ng update` on existing project
whole files (even if they are same, excluding the line endings) will be marked as changed while viewing diff

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by catull** [comment]
What is the problem ? What happened ?

**Comment by filipesilva** [comment]
We'll be removing this command soon (https://github.com/angular/angular-cli/issues/4416) so this is a non-issue.
