### ISSUE TITLE
Better sourcemap paths for development mode

### ISSUE THREAD

**Issue by jelbourn** [angular/angular-cli#456]
Currently, the CLI generates source maps with the source files embedded into the `.js.map` file. This works very well for "production" builds, but is not the ideal experience for development.

When doing development, the source maps should point to the actual, real source TS file in your project. There are a couple of advantages to this:
1. Chrome lets you specify a workspace directory, which lets you edit and save your real source files through the Chrome dev tools while you're debugging.
2. WebStorm has a karma test runner that will give you links to file positions when there's a test failure. This doesn't point anywhere useful, though, when the sources are embedded into the map.

**Comment by filipesilva** [comment]
Closed via #1455.
