### ISSUE TITLE
ng build --watch and ng serve don't always build updated files after new changes

### ISSUE THREAD

**Issue by JavierPDev** [angular/angular-cli#4566]
I usually need to save changes multiple times in order for angular-cli to actually build files with those changes. 

### OS?
Ubuntu 16.10 x64

### Versions.
angular-cli: 1.0.0-beta.28.3
node: 7.1.0
os: linux x64

### Repro steps.
This happens for any angular-cli app I make, even fresh ones. 

In the log below you can see the initial build when running `ng build --watch` with Hash: 91bb893998276a59bbb3. Then I make a change to `app.component.ts` and save it. Angular-cli responds with those next builds with the same Hash: 91bb893998276a59bbb3 which results in dist files without the new change. I go back to `app.component.ts` and save again. Finally angular-cli responds with new Hash: 99e3be9aeef7c621e6f3 and the dist files include the new change.

### The log given by the failure.
```bash
Hash: 91bb893998276a59bbb3
Time: 7868ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.map (main) 3.94 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 10 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.38 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
Hash: 91bb893998276a59bbb3
Time: 625ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial]
chunk    {1} main.bundle.js, main.bundle.map (main) 3.94 kB {3} [initial]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 10 kB {4} [initial]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.38 MB [initial]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]
Hash: 91bb893998276a59bbb3
Time: 594ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial]
chunk    {1} main.bundle.js, main.bundle.map (main) 3.94 kB {3} [initial]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 10 kB {4} [initial]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.38 MB [initial]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]
Hash: 91bb893998276a59bbb3
Time: 568ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial]
chunk    {1} main.bundle.js, main.bundle.map (main) 3.94 kB {3} [initial]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 10 kB {4} [initial]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.38 MB [initial]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]
Hash: 99e3be9aeef7c621e6f3
Time: 526ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial]
chunk    {1} main.bundle.js, main.bundle.map (main) 3.97 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 10 kB {4} [initial]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.38 MB [initial]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]
Hash: 99e3be9aeef7c621e6f3
Time: 576ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial]
chunk    {1} main.bundle.js, main.bundle.map (main) 3.97 kB {3} [initial]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 10 kB {4} [initial]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.38 MB [initial]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]
```

### Mention any other details that might be useful.
I thought this problem might be due to the Inotify Watches Limit on Linux that has been mentioned in some issues but setting it to 524288 does not fix the problem and it seems to me that angular-cli knows when the changes happen but doesn't include them in the build for some reason. Also none of the directories have spaces or special characters in their name and webpack runs fine in other projects.

**Comment by efstathiosntonas** [comment]
This is a known issue, going back to "@ngtools/webpack" : "1.2.4" fixes the issue but you will lose the new perfomance improvements in building time.

**Comment by JavierPDev** [comment]
Thanks a bunch, efstathiosntonas. Just ran `npm install @ngtools/webpack@1.2.4` and now things are working as they should. Apologies for bringing up a known issue, I didn't see it when looking through the issues for anything similar to my problem, I only came across the Windows/special character directories and Inotify watches limit issues.

**Comment by hccampos** [comment]
Having the same issue here actually, on Ubuntu. Will try to dig into it some more. So far I figured out that it is always the same files that it refuses to rebuild, so I think it is something related to the current dependency graph.

**Comment by instantepiphany** [comment]
Installing 1.2.4 of webpack doesn't fix it for me, is there any workaround to use in the meantime? Killing and then running `ng serve` after each file save is annoying and takes so long compared to recompiling when already running.

**Comment by filipesilva** [comment]
Heya, let's talk about this in https://github.com/angular/angular-cli/issues/5117 since it's still open and has a fair amount of replies there. I can't get a repro of this issue and would appreciate if someone has one.

**Comment by halben** [comment]
Have you tried removing --aot option? That works for me.
