### ISSUE TITLE
"host" parameter not being read from .ember-cli JSON file

### ISSUE THREAD

**Issue by danielzen** [angular/angular-cli#4578]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
1.0.0-beta.26 through
1.0.0-beta.30

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
edit .ember-cli JSON object and create  "host": "x.x.x.x" property. Run `ng serve`. host is completely ignored. However, --host command line parameter is still recognized (i.e. `ng serve --host x.x.x.x`)

This feature used to work, and has stopped, but I believe other .ember-cli features are still working

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
Would gladly have another way of storing settings beside .ember-cli file, but have been using them for close to a year without problem... 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@danielzen It looks like support for this file is removed: 
https://github.com/angular/angular-cli/pull/4030

I'm afraid at this point I can't tell you what the alternative is, as I never worked with `.ember-cli`.

**Comment by danielzen** [comment]
Thanks @beeman. The only alternative at the moment is to manually adding the command line flags....
