### ISSUE TITLE
When saving multiple files changes at the same time, "ng serve" can't detect part of the files.

### ISSUE THREAD

**Issue by owen26** [angular/angular-cli#4586]
### OS?
Mac OSX El Capitan

### Versions.
angular-cli: 1.0.0-beta.26
node: 6.9.1
os: darwin x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/compiler-cli: 2.4.6

### Repro steps.
1. Use any IDE that have "save all files" feature. (I use WebStorm);
2. Save all your existing file changes, run `ng serve`;
3. Open homepage in browser, see the browser console is clean;
4. Insert `console.log()` in multiple files but do not save the files yet. eg. 
```
console.log('app update 1'); // app.module.ts
console.log('layout update 1'); // layout.module.ts
console.log('home update 1'); // home.module.ts
```
5. Save all files at once in your IDE, then check browser console outputs;
6. See browser console only one line output `app update 1`, without the other 2;
7. Update all 3 files again to print `update 2`
8. Observe browser console now output `update 2` from one file, `update 1` another file, and no output from the last file.

**Comment by filipesilva** [comment]
This was fixed in https://github.com/angular/angular-cli/pull/4542, released in beta.31. 

It was actually quite hard to track down this problem, and it was exactly what you described. Wish we had known sooner!

**Comment by owen26** [comment]
Glad to hear it has been solved, thanks a lot!
