### ISSUE TITLE
minify css ⚡️

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#4588]
### Versions:
win10 & v31

### Steps:
1. add style.**scss**  in `angular-cli.json`
2. In this style.**scss** I import non-minified css file using `@import '...../style.css`
3. after run` ng build --prod ` my style bundle doesn't minify imported style

### Details:
If I add all my non-minified css in `angular-cli.json` so it's OK  they will be minified

**Comment by filipesilva** [comment]
Hey is this still happening? I think we fixed this pipeline.

**Comment by filipesilva** [comment]
Closing as inactive.
