### ISSUE TITLE
[beta.31] ng XXX -h or --help returns "undefined"

### ISSUE THREAD

**Issue by victornoel** [angular/angular-cli#4595]
Using beta.31, when I execute `ng lint -h` or `ng lint --help` or the same for any other command, I get the following output:
```
➜  frontend git:(master) ✗ ng lint --help
undefined
```

I feel like it wasn't the case before?

**Comment by Blasz** [comment]
Same goes for:

`ng help xxx`

**Comment by shmool** [comment]
The bug originated in commit https://github.com/angular/angular-cli/commit/b20d87ed2bf2e23bf96d72d5a0979e4dac11bfb8

Digging deeper... :)
#goodnessSquad

**Comment by hansl** [comment]
@shmool This issue has been fixed by another PR. Let me find it...

**Comment by hansl** [comment]
Fixed by https://github.com/angular/angular-cli/pull/4726

**Comment by shmool** [comment]
Thanks @hansl for the update and @sumitarora for the PR!
Congrats on the RC, you're all doing an amazing work :)
