### ISSUE TITLE
Update to angular-cli: 1.0.0-beta.31, none of the ng command will run.

### ISSUE THREAD

**Issue by chenhuang06804** [angular/angular-cli#4605]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:1.0.0-beta.31
 any ng command results in errors.

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
just follow the instruction to upgrade to the latest CLI version as follow:
npm uninstall -g angular-cli @angular/cli
npm cache clean
npm install -g @angular/cli@latest
 
After that, when you run any ng command such as "ng --version" will result in the following errors:

### The log given by the failure.
> Normally this include a stack trace and some more information.

/usr/local/lib/node_modules/@angular/cli/models/config/config.js:15
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/config.js:2:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

### Mention any other details that might be useful.

If you  remove node_modules directory of any existent project and rebuild it, your build will fail too.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by RichardSilveira** [comment]
Same issue for me too, i'm was working with angular-cli.beta-19 and upgrading to beta-28.3 (latest with node 5.5 support) and this same error occurs...
There is a way to downgrade to older angular-cli version under beta-28.3?

**Comment by hansl** [comment]
You might be using the newer `@ngtools/webpack` plugin. Do this:

```
npm install --save-dev @ngtools/webpack@1.2.8
```

to make sure you use the one that shipped with 28.3.
