### ISSUE TITLE
ng build fails to copy .htaccess to dist folder

### ISSUE THREAD

**Issue by gandra** [angular/angular-cli#4607]
`ng build` does not copy `.htaccess` to `dest`  dir. I have tried to put `.htaccess` in both `src` and `src/assets` folder but in both cases `.htaccess` does not appears in `dist` folder.  
Here are more details about:  

### OS?

> Linux Mint 18.1 “Serena”

### Versions.

> angular-cli: 1.0.0-beta.28.3
> node: 7.5.0
> os: linux x64
> @angular/common: 2.4.7
> @angular/compiler: 2.4.7
> @angular/core: 2.4.7
> @angular/forms: 2.4.7
> @angular/http: 2.4.7
> @angular/platform-browser: 2.4.7
> @angular/platform-browser-dynamic: 2.4.7
> @angular/router: 3.4.7
> @angular/compiler-cli: 2.4.7

### Repro steps.

> ng new angular-cli-test
> cp kibernum-dnc-client/src/.htaccess  angular-cli-test/src/
> cd angular-cli-test
> 
> ng build
> ls -la dist/
> 
> mv src/.htaccess src/assets/
> ng build
> ls -la dist/

### The log given by the failure.
There is no log error. Errror is that I expect that file `.htaccess` is copied in `dist` folder.

**Comment by filipesilva** [comment]
When you put it in `src/assets/.htaccess`, it will be copied into `dist/assets/.htaccess`. 

If you want it to be in `dist/.htaccess`, then you should be in `src/.htaccess` AND you need to add it to `angular-cli.json` in the `assets` array (like `favicon.ico`).

**Comment by gandra** [comment]
@filipesilva ,
in such case `.htaccess` is copied in `assets/.htaccess`.
I want to have `assets` in the root of `dest` folder.

**Comment by filipesilva** [comment]
Change this bit:
```
      "assets": [
        "assets",
        "favicon.ico"
      ],
```
to 
```
      "assets": [
        "assets",
        "favicon.ico",
        ".htaccess"
      ],
```

**Comment by gandra** [comment]
Now works. Thanks!
So, for others as reference here. is fix:


1. Put `.htaccess` in `src` folder (final path for is src/.htaccess)
2. Have something similar to this:
```
            "assets": [
                "assets",
                "assets/images/favicon.ico",
                ".htaccess"
            ],
```

Kudos to @filipesilva !

**Comment by bkdotcom** [comment]
unrelated...   why are files in my assets folder ending up in 
`/dist` and in `/dist/assets` ?

**Comment by arun-awnics** [comment]
Hey @filipesilva , can you please let me know what should be the content of `.htaccess`? 

I tried this, but of no use:

```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
```

I have set `<base href="http://146.148.47.134/mm-coming-soon/">`

Need your guidance.

**Comment by javierojeda94** [comment]
@arun-awnics I know this may be late but this is my `.htaccess` file:

```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]
    RewriteRule ^(.*) index.html [NC,L]
</IfModule>
```

But in my case, I have set `<base href="/">`

Hope this helps.

**Comment by sandipsanap** [comment]
i have deployed the angular project on apache server  and i have added .htaccess file in src folder but when i am refreshing the page at that time i am getting 404 error.

Please find .htaccess file

<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]
    RewriteRule ^(.*) index.html [NC,L]
</IfModule>

**Comment by bleuscyther** [comment]
@sandipsanap try with  RewriteBase /
you can change it to /dist for example or the name of your sub_directory

**Comment by jbkhellas** [comment]
I know this might sound silly but angular.json has two sections, one for test and one for build. So add the entries to the correct one! :-)

**Comment by AhmadRaza786** [comment]
I have generated the `.htaccess` file. Now I want to make changes in `.htaccess` file while building the angular build. currently I have the following in `.htaccess` file.
```
RewriteEngine On
# If an existing asset or directory is requested go to it as it is
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d
RewriteRule ^ - [L]

# If the requested resource doesn't exist, use index.html
RewriteRule ^ /test/index.html
```

I need to change the last line of this file `RewriteRule ^ /test/index.html`.
How can i achieve it.
