### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by mithun-daa** [angular/angular-cli#4608]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
beta.31

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
N/A

### The log given by the failure.
> Normally this include a stack trace and some more information.
N/A

### Mention any other details that might be useful.
The [Upgrading from Beta.10 to Beta.14 wiki](https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14) needs to be updated to 
```
npm install -g @angular/cli
```
It does not let me edit the Wiki.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by getjack** [comment]
I noticed that the Wiki is heavily out of sync with the ng help command. I tried to run ng build -vb but it would not recognize the flag which is correct by the output of ng help.

**Comment by filipesilva** [comment]
These discrepancies and others have been fixed in the last few weeks. The wiki has gotten the much needed love it deserved.
