### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/linux-x64-51_binding.node"

### ISSUE THREAD

**Issue by justkj7** [angular/angular-cli#4612]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 14.04.4 LTS
I am running my linux machine in VMWare.

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.28.3
node: 7.4.0
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
$ ng new angular-tour-of-heroes
Then, I see below error messages even though my network does not have proxy.

### The log given by the failure.
> Normally this include a stack trace and some more information.

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global node-gyp@3.5.0 should be installed with -g
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/linux-x64-51_binding.node":

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
Bus error (core dumped)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.2.0-30-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 135
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kkj41/angularjs_dev/angular-tour-of-heroes/npm-debug.log

Package install failed, see above.

### Mention any other details that might be useful.
Project folder is created, though, even with error happening. But it looks incomplete.
I would appreciate it if you have any comment about this matter.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@justkj7 this is not a problem with Angular CLI but with the npm installation of node-sass.

Your project is (most likely) generated correctly and you can retry the npm installation by doing:

```
$ cd angular-tour-of-heroes
$ npm install
```

**Comment by justkj7** [comment]
@beeman Thanks a lot for your quick explanation. It works now.

**Comment by beeman** [comment]
Glad to hear that @justkj7, have fun with your app! 👍

**Comment by neilhem** [comment]
Using `cd your_project_root && npm rebuild` also helps.
