### ISSUE TITLE
I can not install additional node package !!! Help me please (

### ISSUE THREAD

**Issue by installerUzb** [angular/angular-cli#4617]
### OS
> Windows 10. 

### Versions.
angular-cli: 1.0.0-beta.26
node: 6.9.1
npm: 3.10.8
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/compiler-cli: 2.4.6

### Error
ERROR in D:/Fozilbek/test/pay-stat/src/app/components/home/top-bar/top-bar.component.ts (4,23): 

Cannot find module 'json-from-xml'.)

![angular](https://cloud.githubusercontent.com/assets/22218672/22854039/7ba36bb6-f086-11e6-816c-d91120142d51.jpg)

**Comment by mattdistefano** [comment]
This isn't really a CLI issue, so you may have more luck on StackOverflow. 

That said, I would guess the json-to-xml package doesn't have a typescript definition. You may need to supply a typescript definition yourself.

**Comment by hansl** [comment]
What @mattdistefano said is true. You need a type definition to import files in typescript. The good news is that it's rather easy to fix; add a file `json-from-xml.d.ts` in your source folder, with something like:

```typescript
declare module "json-from-xml" {
  export default XmlParser: any;
}
```

This will declare the module which exports a default value of type `any`.
