### ISSUE TITLE
build + flex layout is failing on beta.31

### ISSUE THREAD

**Issue by julianobrasil** [angular/angular-cli#4621]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10

### Versions.
node: 6.9.5
os: win32 x64
@angular/cli: 1.0.0-beta.31
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/flex-layout: 2.0.0-beta.5
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/compiler-cli: 2.4.7

### Repro steps.
"ng build --aot -prod" was working normally in cli beta.31. After the updating it stop working. Tried to drop the --aot flag, but the problem still happens

### The log given by the failure.
ERROR in Error encountered resolving symbol values statically. Calling function 'FlexLayoutModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AdministracaoModule in E:/xxxxxx/src/app/restrito/administracao/administracao.module.ts, resolving symbol AdministracaoModule in E:/xxxxxx/src/app/restrito/administracao/administracao.module.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'E:\xxxxxx\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

### Mention any other details that might be useful.

The project runs normally with npm start. The problem seems to be with the building.

The AdminsracaoModule refered above contains (among other things):

imports: [
    CommonModule,
    FormsModule,
    MaterialModule.forRoot(),
    FlexLayoutModule.forRoot(),
    AdministracaoRoutingModule,
    SharedModule
  ]

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
Flex layout's forRoot call is deprecated.

**Comment by derekkite** [comment]
https://github.com/angular/flex-layout/blob/master/CHANGELOG.md
beta 5 has fixed this.
