### ISSUE TITLE
@angular/service-worker does not work with -p option (instead of --prod)

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular-cli#4623]
### OS?
Windows 10

### Versions.
@angular/cli: 1.0.0-beta.31
node: 6.9.1
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
@angular/service-worker: 1.0.0-beta.3

### Repro steps.
ng new test-mobile
npm install --save-dev @angular/service-worker
ng set apps.0.serviceWorker=true
ng build -p

### Mention any other details that might be useful.
It works with --prod as expected.

**Comment by clydin** [comment]
`-p` controls the progress option.

**Comment by Ploppy3** [comment]
@clydin Well, I feel really dumb now 😆 
Thank you !
