### ISSUE TITLE
Code watching not works in projects which contains parenthesis or square brackets in path

### ISSUE THREAD

**Issue by vadim-shb** [angular/angular-cli#4627]
### OS:
Linux Ubuntu 16.04

### Versions:
@angular/cli: 1.0.0-beta.31
node: 7.5.0
os: linux x64

### Repro steps.
1) Create project in path which contains parenthesis or square brackets 
2) Run `ng serve` or `ng test` 
3) Change some code
4) Server NOT reloaded and tests NOT restarted automatically.

example:
```
mkdir ~/"proj(angular)" # ~/"proj[angular]" behaves the same way
cd ~/"proj(angular)"
ng new web-app
cd web-app
ng test
```

So now when I change some code while "ng test" work:
`sed -i "s/app works/app hangs/" ~/"proj(angular)"/web-app/src/app/app.component.ts`

Nothing happens. But tests must show errors.

**Comment by sthuck** [comment]
According to 54541a1975ce1052c4e42933d67d918360f452e6 you can't really create a project in a path that has parenthesis or square brackets. I guess it was possible in previous versions, but my best bet right now would be to just change the folder name. 

#goodnessSquad

**Comment by filipesilva** [comment]
Hm... it is true we don't allow the base folder to have such names, but you should still be able to have your folders named as whatever you want.

I had a go on a brand new project, chaging the name of `src/app` to `src/app[[test]]` and can verify reloads don't happen on `ng serve`.

Need to investigate more.

**Comment by sumitarora** [comment]
@vadim-shb It seems like an issue with `webpack-dev-server` which `ng serve` uses. It doesn't pick up the paths with `[]` or `()` and do the reloading of code which it should.

**Comment by clydin** [comment]
CLI 1.0 prerelease versions are no longer supported. If this error still occurs on the latest version (6.1.4 currently). Please open a new issue describing the problem.
