### ISSUE TITLE
Add option in angular-cli.json to change src directory of bundle

### ISSUE THREAD

**Issue by LukeNZ** [angular/angular-cli#4630]
When you run `ng build`, it seems absurd to me that there is no option in `angular-cli.json` to specify the path of the JS bundles in the `<script src="" />` of `index.html`.

Right now, they are generated as a relative path with no prefix, i.e. `<script src="vendor.bundle.js" />`, but this isn't very useful if you have a backend stack which is serving files from a different location, or you want more fine tuned control of your directory structure.

Consider adding a `bundle-src-prefix` option or similar to `angular-cli.json` that would prepend the JS bundle with a customizable path.

### OS?
> All

### Versions.
> All (including beta.30)

**Comment by Meligy** [comment]
If all you want is to serve the app from `/custom/path/`, you can use the `--base-href` parameter and set it to that `/custom/path/`.

If you want control, separate folder etc, try the `deploy-url` parameter.

**Comment by clydin** [comment]
`deployUrl` is also available for use in `angular-cli.json`

**Comment by hansl** [comment]
Closing this as answered.
