### ISSUE TITLE
Angular app not running on android browser

### ISSUE THREAD

**Issue by ghost** [angular/angular-cli#4632]
Hello, thanks for the great support. I just updated to CLI v1.0.0-beta.31 and realized that for some reason the generated prod aot build is not running on Android Internet Browser (4.4.2 and some other Android I tested).

The issue is basically that the default text: "Loading..." keeps there forever.

 I first thought it was something in my code but a few minutes ago I created a new fresh project with the CLI and generated the aot prod build (without touching anything, as is) but I got the same result. It is interesting that it fails on Android browsers only, not in mobile Chrome, FF, nor any desktop, and of course it does not throw any error in the console.

Windows  10.

### Repro steps.
Detailed above.

Thanks guys!

**Comment by Meligy** [comment]
Check the polyfills.ts file. You might be able to uncomment some polyfills (some will require extra NPM packages, mentioned above each) for it to work the browser.

**Comment by EmmitRemus** [comment]
Checking now... Thank you :)

**Comment by EmmitRemus** [comment]
Hi again, I uncommented all polyfills in the .ts file and installed the below but still getting the same. Not sure if this info helps but ... last week I was working with beta 30 version and I did not need to install anything and the app was running fine on mentioned Android browser.

Installed these NPM packages:
npm i core-js
npm install --save intl
npm install --save web-animations-js
npm install --save classlist.js

Thanks for helping the world to be a better place.

**Comment by Meligy** [comment]
That's very interesting. If you updated your polyfills to the latest file (to the one with all the many comments and instructions to download other libraries via npm) when you upgrades to beta 30, then this part shouldn't be different in beta 31.

Would you be able to revert to beta 30 (via git, deleting node_modules, and running npm install again), and see again?

If it's not polyfills, it could be a compiler issue or minification issue, or unrelated code in your application.

The last option (non-CLI application code issue) can be tested by creating a new project from the CLI and seeing if the same problem  happens.

**Comment by FabianAlvaradoDotCom** [comment]
Hello!
Sorry I´ve been in a rush to finish this thing so I did not remember to check the post again. Another thing really interesting is that even with those polyfills uncommented/packages installed, I noticed later that even IE was failing the same as the Android browser.

 What I did a couple of hours ago to be able to continue working on the project was downgrading to CLI beta30 (which worked, now on Android 4.4.2 Browser and IE 11 it is good) by doing this:

- npm uninstall -g angular-cli @angular/cli
- npm cache clean
- npm install -g @angular/cli@1.0.0-beta.30

Please note that for this to work I did not need to touch the polyfills, just created a new project, installed Sass, Bootstrap and copied my previous code.
By now I will continue working with beta30 version, but in case there is anything I can help with please let me know, I can perform any testing and report my results.

Thanks again for your your kind assistance.

**Comment by filipesilva** [comment]
Heya, can you give me detailed repro steps? How did you test this? I don't have an old android phone around so it would be nice to have a way to test that didn't involve one.

**Comment by FabianAlvaradoDotCom** [comment]
Hello!
Yep, better than that, later today I will make a video so you can see exactly what I did, stay tuned.

Have a great day :)

**Comment by osixia** [comment]
Same here.
Just created a new angular cli project and try to use it in cordova app (webview) or access ng serve directly from the default android browser and get the error: 

Uncaught TypeError: Cannot read property 'apply' of undefined intl.js:187

**Comment by kenjinsama** [comment]
I can confirm, i'm compiling with "ng build --target=production" (angular-cli 1.0.0-beta.31). I tried with a newly generated application and got the same in android default browser (android 7.1):
```
Uncaught TypeError: Cannot read property 'apply' of undefined
```
Several things tested:
- Android adblock browser : working
- Line link preview : working
- Android 5.x default browser : working

**Comment by sebhildebrandt** [comment]
Same here ...

```
Uncaught TypeError: Cannot read property 'apply' of undefined intl.js:187
```
on Chrome (I have to check version) ... same build works fine on Safari (no error)

**Comment by sebhildebrandt** [comment]
Second machine, same code, Chrome 56 ... works fine. Will post other chrome version later this evening ...

**Comment by sebhildebrandt** [comment]
So:

	Chrome Version 43.0.2357.81 (64-bit) 

caused that problem ...

Upgraded now to 

	Chrome Version 56.0.2924.87 (64-bit)

Everything works fine now ...

**Comment by kenjinsama** [comment]
Working on default browser, 6.0.1.

**Comment by FabianAlvaradoDotCom** [comment]
Installed CLI RC vesion, and it works on Android Browser, OS 4.4.2., from my standpoint the bug has been squashed.

**Comment by filipesilva** [comment]
Coolio, closing then. Thanks all for testing this!
