### ISSUE TITLE
Angular2 quickstart example installation error

### ISSUE THREAD

**Issue by LamShuiYing** [angular/angular-cli#4634]
### OS?
Win10

### Versions.
angular-cli: 1.0.0-beta.26
node: 7.5.0
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
unzipping quickstart-master.zip and run npm install

### The log given by the failure.
> Normally this include a stack trace and some more information.
G:\Google Drive\ITProjects\ProjectsJavaScript\2>npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
angular-quickstart@1.0.0 G:\Google Drive\ITProjects\ProjectsJavaScript\2
+-- @angular/common@2.4.7
+-- @angular/compiler@2.4.7
+-- @angular/core@2.4.7
+-- @angular/forms@2.4.7
+-- @angular/http@2.4.7
+-- @angular/platform-browser@2.4.7
+-- @angular/platform-browser-dynamic@2.4.7
+-- @angular/router@3.4.7
+-- @types/jasmine@2.5.36
+-- @types/node@6.0.63
+-- angular-in-memory-web-api@0.2.4
+-- canonical-path@0.0.2
+-- concurrently@3.2.0
| +-- chalk@0.5.1
| | +-- ansi-styles@1.1.0
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@0.1.0
| | | `-- ansi-regex@0.2.1
| | +-- strip-ansi@0.3.0
| | `-- supports-color@0.2.0
| +-- commander@2.6.0
| +-- date-fns@1.27.2
| +-- rx@2.3.24
| +-- spawn-default-shell@2.0.0
| +-- supports-color@3.2.3
| | `-- has-flag@1.0.0
| `-- tree-kill@1.1.0
+-- core-js@2.4.1
+-- jasmine-core@2.4.1
+-- karma@1.4.1
| +-- bluebird@3.4.7
| +-- body-parser@1.16.1
| | +-- bytes@2.4.0
| | +-- content-type@1.0.2
| | +-- debug@2.6.1
| | | `-- ms@0.7.2
| | +-- depd@1.1.0
| | +-- http-errors@1.5.1
| | | +-- setprototypeof@1.0.2
| | | `-- statuses@1.3.1
| | +-- iconv-lite@0.4.15
| | +-- on-finished@2.3.0
| | | `-- ee-first@1.1.1
| | +-- qs@6.2.1
| | +-- raw-body@2.2.0
| | | `-- unpipe@1.0.0
| | `-- type-is@1.6.14
| |   +-- media-typer@0.3.0
| |   `-- mime-types@2.1.14
| |     `-- mime-db@1.26.0
| +-- chokidar@1.6.1
| | +-- anymatch@1.3.0
| | | `-- arrify@1.0.1
| | +-- async-each@1.0.1
| | +-- glob-parent@2.0.0
| | +-- inherits@2.0.3
| | +-- is-binary-path@1.0.1
| | | `-- binary-extensions@1.8.0
| | +-- is-glob@2.0.1
| | | `-- is-extglob@1.0.0
| | +-- path-is-absolute@1.0.1
| | `-- readdirp@2.1.0
| |   +-- readable-stream@2.2.2
| |   | +-- buffer-shims@1.0.0
| |   | +-- isarray@1.0.0
| |   | `-- process-nextick-args@1.0.7
| |   `-- set-immediate-shim@1.0.1
| +-- colors@1.1.2
| +-- combine-lists@1.0.1
| +-- connect@3.5.0
| | +-- debug@2.2.0
| | | `-- ms@0.7.1
| | +-- finalhandler@0.5.0
| | | +-- debug@2.2.0
| | | | `-- ms@0.7.1
| | | `-- escape-html@1.0.3
| | +-- parseurl@1.3.1
| | `-- utils-merge@1.0.0
| +-- di@0.0.1
| +-- dom-serialize@2.2.1
| | +-- custom-event@1.0.1
| | +-- ent@2.2.0
| | +-- extend@3.0.0
| | `-- void-elements@2.0.1
| +-- expand-braces@0.1.2
| | +-- array-slice@0.2.3
| | +-- array-unique@0.2.1
| | `-- braces@0.1.5
| |   `-- expand-range@0.1.1
| |     +-- is-number@0.1.1
| |     `-- repeat-string@0.2.2
| +-- glob@7.1.1
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.6
| | | `-- wrappy@1.0.2
| | `-- once@1.4.0
| +-- graceful-fs@4.1.11
| +-- http-proxy@1.16.2
| | +-- eventemitter3@1.2.0
| | `-- requires-port@1.0.0
| +-- isbinaryfile@3.0.2
| +-- lodash@3.10.1
| +-- log4js@0.6.38
| | +-- readable-stream@1.0.34
| | | +-- core-util-is@1.0.2
| | | +-- isarray@0.0.1
| | | `-- string_decoder@0.10.31
| | `-- semver@4.3.6
| +-- mime@1.3.4
| +-- minimatch@3.0.3
| | `-- brace-expansion@1.1.6
| |   +-- balanced-match@0.4.2
| |   `-- concat-map@0.0.1
| +-- optimist@0.6.1
| | +-- minimist@0.0.10
| | `-- wordwrap@0.0.3
| +-- qjobs@1.1.5
| +-- range-parser@1.2.0
| +-- safe-buffer@5.0.1
| +-- socket.io@1.7.2
| | +-- debug@2.3.3
| | +-- engine.io@1.8.2
| | | +-- accepts@1.3.3
| | | | `-- negotiator@0.6.1
| | | +-- base64id@1.0.0
| | | +-- cookie@0.3.1
| | | +-- debug@2.3.3
| | | `-- engine.io-parser@1.3.2
| | |   +-- after@0.8.2
| | |   +-- arraybuffer.slice@0.0.6
| | |   +-- base64-arraybuffer@0.1.5
| | |   +-- blob@0.0.4
| | |   `-- wtf-8@1.0.0
| | +-- has-binary@0.1.7
| | | `-- isarray@0.0.1
| | +-- object-assign@4.1.0
| | +-- socket.io-adapter@0.5.0
| | | `-- debug@2.3.3
| | +-- socket.io-client@1.7.2
| | | +-- backo2@1.0.2
| | | +-- component-bind@1.0.0
| | | +-- component-emitter@1.2.1
| | | +-- debug@2.3.3
| | | +-- engine.io-client@1.8.2
| | | | +-- component-emitter@1.2.1
| | | | +-- component-inherit@0.0.3
| | | | +-- debug@2.3.3
| | | | +-- has-cors@1.1.0
| | | | +-- parsejson@0.0.3
| | | | +-- parseqs@0.0.5
| | | | +-- xmlhttprequest-ssl@1.5.3
| | | | `-- yeast@0.1.2
| | | +-- indexof@0.0.1
| | | +-- object-component@0.0.3
| | | +-- parseuri@0.0.5
| | | | `-- better-assert@1.0.2
| | | |   `-- callsite@1.0.0
| | | `-- to-array@0.1.4
| | `-- socket.io-parser@2.3.1
| |   +-- component-emitter@1.1.2
| |   +-- debug@2.2.0
| |   | `-- ms@0.7.1
| |   +-- isarray@0.0.1
| |   `-- json3@3.3.2
| +-- source-map@0.5.6
| +-- tmp@0.0.28
| | `-- os-tmpdir@1.0.2
| `-- useragent@2.1.12
|   `-- lru-cache@2.2.4
+-- karma-chrome-launcher@2.0.0
| +-- fs-access@1.0.1
| | `-- null-check@1.0.0
| `-- which@1.2.12
|   `-- isexe@1.1.2
+-- karma-cli@1.0.1
| `-- resolve@1.2.0
+-- karma-jasmine@1.1.0
+-- karma-jasmine-html-reporter@0.2.2
+-- lite-server@2.2.2
| +-- browser-sync@2.18.7
| | +-- browser-sync-client@2.4.4
| | | +-- etag@1.7.0
| | | `-- fresh@0.3.0
| | +-- browser-sync-ui@0.6.3
| | | +-- async-each-series@0.1.1
| | | +-- stream-throttle@0.1.3
| | | | `-- limiter@1.1.0
| | | `-- weinre@2.0.0-pre-I0Z7U9OV
| | |   +-- express@2.5.11
| | |   | +-- connect@1.9.2
| | |   | | `-- formidable@1.0.17
| | |   | +-- mime@1.2.4
| | |   | +-- mkdirp@0.3.0
| | |   | `-- qs@0.4.2
| | |   +-- nopt@3.0.6
| | |   | `-- abbrev@1.0.9
| | |   `-- underscore@1.7.0
| | +-- bs-recipes@1.3.4
| | +-- dev-ip@1.0.1
| | +-- easy-extender@2.3.2
| | | `-- lodash@3.10.1
| | +-- eazy-logger@3.0.2
| | | `-- tfunk@3.1.0
| | |   +-- chalk@1.1.3
| | |   | +-- ansi-styles@2.2.1
| | |   | +-- has-ansi@2.0.0
| | |   | | `-- ansi-regex@2.1.1
| | |   | +-- strip-ansi@3.0.1
| | |   | `-- supports-color@2.0.0
| | |   `-- object-path@0.9.2
| | +-- emitter-steward@1.0.0
| | +-- fs-extra@1.0.0
| | | +-- jsonfile@2.4.0
| | | `-- klaw@1.3.1
| | +-- http-proxy@1.15.2
| | +-- immutable@3.8.1
| | +-- localtunnel@1.8.2
| | | +-- debug@2.2.0
| | | | `-- ms@0.7.1
| | | +-- openurl@1.1.0
| | | `-- yargs@3.29.0
| | |   +-- camelcase@1.2.1
| | |   `-- window-size@0.1.4
| | +-- micromatch@2.3.11
| | | +-- arr-diff@2.0.0
| | | | `-- arr-flatten@1.0.1
| | | +-- braces@1.8.5
| | | | +-- expand-range@1.8.2
| | | | | `-- fill-range@2.2.3
| | | | |   +-- is-number@2.1.0
| | | | |   +-- isobject@2.1.0
| | | | |   +-- randomatic@1.1.6
| | | | |   `-- repeat-string@1.6.1
| | | | +-- preserve@0.2.0
| | | | `-- repeat-element@1.1.2
| | | +-- expand-brackets@0.1.5
| | | | `-- is-posix-bracket@0.1.1
| | | +-- extglob@0.3.2
| | | +-- filename-regex@2.0.0
| | | +-- kind-of@3.1.0
| | | | `-- is-buffer@1.1.4
| | | +-- normalize-path@2.0.1
| | | +-- object.omit@2.0.1
| | | | +-- for-own@0.1.4
| | | | | `-- for-in@0.1.6
| | | | `-- is-extendable@0.1.1
| | | +-- parse-glob@3.0.4
| | | | +-- glob-base@0.3.0
| | | | `-- is-dotfile@1.0.2
| | | `-- regex-cache@0.4.3
| | |   +-- is-equal-shallow@0.1.3
| | |   `-- is-primitive@2.0.0
| | +-- opn@4.0.2
| | | `-- pinkie-promise@2.0.1
| | |   `-- pinkie@2.0.4
| | +-- portscanner@2.1.1
| | | +-- async@1.5.2
| | | `-- is-number-like@1.0.7
| | |   +-- bubleify@0.5.1
| | |   | `-- buble@0.12.5
| | |   |   +-- acorn@3.3.0
| | |   |   +-- acorn-jsx@3.0.1
| | |   |   +-- acorn-object-spread@1.0.0
| | |   |   +-- chalk@1.1.3
| | |   |   | +-- ansi-styles@2.2.1
| | |   |   | +-- has-ansi@2.0.0
| | |   |   | | `-- ansi-regex@2.1.1
| | |   |   | +-- strip-ansi@3.0.1
| | |   |   | `-- supports-color@2.0.0
| | |   |   +-- magic-string@0.14.0
| | |   |   | `-- vlq@0.2.1
| | |   |   +-- minimist@1.2.0
| | |   |   `-- os-homedir@1.0.2
| | |   `-- lodash.isfinite@3.3.2
| | +-- resp-modifier@6.0.2
| | +-- rx@4.1.0
| | +-- serve-index@1.8.0
| | | +-- batch@0.5.3
| | | `-- debug@2.2.0
| | |   `-- ms@0.7.1
| | +-- serve-static@1.11.1
| | | +-- encodeurl@1.0.1
| | | `-- send@0.14.1
| | |   +-- debug@2.2.0
| | |   +-- destroy@1.0.4
| | |   `-- ms@0.7.1
| | +-- server-destroy@1.0.1
| | +-- socket.io@1.6.0
| | | +-- debug@2.3.3
| | | `-- engine.io@1.8.0
| | |   +-- base64id@0.1.0
| | |   `-- engine.io-parser@1.3.1
| | |     +-- after@0.8.1
| | |     `-- has-binary@0.1.6
| | |       `-- isarray@0.0.1
| | +-- socket.io-client@1.6.0
| | | +-- component-emitter@1.2.1
| | | `-- engine.io-client@1.8.0
| | +-- ua-parser-js@0.7.12
| | `-- yargs@6.4.0
| |   +-- camelcase@3.0.0
| |   +-- cliui@3.2.0
| |   | +-- strip-ansi@3.0.1
| |   | | `-- ansi-regex@2.1.1
| |   | `-- wrap-ansi@2.1.0
| |   |   `-- strip-ansi@3.0.1
| |   |     `-- ansi-regex@2.1.1
| |   +-- decamelize@1.2.0
| |   +-- get-caller-file@1.0.2
| |   +-- os-locale@1.4.0
| |   | `-- lcid@1.0.0
| |   |   `-- invert-kv@1.0.0
| |   +-- read-pkg-up@1.0.1
| |   | +-- find-up@1.1.2
| |   | | `-- path-exists@2.1.0
| |   | `-- read-pkg@1.1.0
| |   |   +-- load-json-file@1.1.0
| |   |   | +-- parse-json@2.2.0
| |   |   | | `-- error-ex@1.3.0
| |   |   | |   `-- is-arrayish@0.2.1
| |   |   | `-- strip-bom@2.0.0
| |   |   |   `-- is-utf8@0.2.1
| |   |   +-- normalize-package-data@2.3.5
| |   |   | +-- hosted-git-info@2.2.0
| |   |   | +-- is-builtin-module@1.0.0
| |   |   | | `-- builtin-modules@1.1.1
| |   |   | `-- validate-npm-package-license@3.0.1
| |   |   |   +-- spdx-correct@1.0.2
| |   |   |   | `-- spdx-license-ids@1.2.2
| |   |   |   `-- spdx-expression-parse@1.0.4
| |   |   `-- path-type@1.1.0
| |   +-- require-directory@2.1.1
| |   +-- require-main-filename@1.0.1
| |   +-- set-blocking@2.0.0
| |   +-- string-width@1.0.2
| |   | +-- code-point-at@1.1.0
| |   | +-- is-fullwidth-code-point@1.0.0
| |   | | `-- number-is-nan@1.0.1
| |   | `-- strip-ansi@3.0.1
| |   |   `-- ansi-regex@2.1.1
| |   +-- which-module@1.0.0
| |   +-- window-size@0.2.0
| |   +-- y18n@3.2.1
| |   `-- yargs-parser@4.2.1
| |     `-- camelcase@3.0.0
| +-- connect-history-api-fallback@1.3.0
| +-- connect-logger@0.0.1
| | `-- moment@2.17.1
| `-- minimist@1.2.0
+-- lodash@4.17.4
+-- protractor@4.0.14
| +-- @types/q@0.0.32
| +-- @types/selenium-webdriver@2.53.37
| +-- adm-zip@0.4.7
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.1.1
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0
| +-- jasmine@2.4.1
| | +-- exit@0.1.2
| | `-- glob@3.2.11
| |   `-- minimatch@0.3.0
| |     `-- sigmund@1.0.1
| +-- jasminewd2@0.0.10
| +-- q@1.4.1
| +-- saucelabs@1.3.0
| | `-- https-proxy-agent@1.0.0
| |   `-- agent-base@2.0.1
| |     `-- semver@5.0.3
| +-- selenium-webdriver@2.53.3
| | +-- adm-zip@0.4.4
| | +-- tmp@0.0.24
| | +-- ws@1.1.1
| | | +-- options@0.0.6
| | | `-- ultron@1.0.2
| | `-- xml2js@0.4.4
| |   +-- sax@0.6.1
| |   `-- xmlbuilder@8.2.2
| +-- source-map-support@0.4.11
| `-- webdriver-manager@10.3.0
|   +-- del@2.2.2
|   | +-- globby@5.0.0
|   | | `-- array-union@1.0.2
|   | |   `-- array-uniq@1.0.3
|   | +-- is-path-cwd@1.0.0
|   | +-- is-path-in-cwd@1.0.0
|   | | `-- is-path-inside@1.0.0
|   | |   `-- path-is-inside@1.0.2
|   | `-- pify@2.3.0
|   +-- ini@1.3.4
|   +-- minimist@1.2.0
|   +-- request@2.78.0
|   | +-- aws-sign2@0.6.0
|   | +-- aws4@1.6.0
|   | +-- caseless@0.11.0
|   | +-- combined-stream@1.0.5
|   | | `-- delayed-stream@1.0.0
|   | +-- forever-agent@0.6.1
|   | +-- form-data@2.1.2
|   | | `-- asynckit@0.4.0
|   | +-- har-validator@2.0.6
|   | | +-- chalk@1.1.3
|   | | | +-- ansi-styles@2.2.1
|   | | | +-- has-ansi@2.0.0
|   | | | | `-- ansi-regex@2.1.1
|   | | | +-- strip-ansi@3.0.1
|   | | | `-- supports-color@2.0.0
|   | | +-- commander@2.9.0
|   | | | `-- graceful-readlink@1.0.1
|   | | `-- is-my-json-valid@2.15.0
|   | |   +-- generate-function@2.0.0
|   | |   +-- generate-object-property@1.2.0
|   | |   | `-- is-property@1.0.2
|   | |   +-- jsonpointer@4.0.1
|   | |   `-- xtend@4.0.1
|   | +-- hawk@3.1.3
|   | | +-- boom@2.10.1
|   | | +-- cryptiles@2.0.5
|   | | +-- hoek@2.16.3
|   | | `-- sntp@1.0.9
|   | +-- http-signature@1.1.1
|   | | +-- assert-plus@0.2.0
|   | | +-- jsprim@1.3.1
|   | | | +-- extsprintf@1.0.2
|   | | | +-- json-schema@0.2.3
|   | | | `-- verror@1.3.6
|   | | `-- sshpk@1.10.2
|   | |   +-- asn1@0.2.3
|   | |   +-- assert-plus@1.0.0
|   | |   +-- bcrypt-pbkdf@1.0.1
|   | |   +-- dashdash@1.14.1
|   | |   | `-- assert-plus@1.0.0
|   | |   +-- ecc-jsbn@0.1.1
|   | |   +-- getpass@0.1.6
|   | |   | `-- assert-plus@1.0.0
|   | |   +-- jodid25519@1.0.2
|   | |   +-- jsbn@0.1.1
|   | |   `-- tweetnacl@0.14.5
|   | +-- is-typedarray@1.0.0
|   | +-- isstream@0.1.2
|   | +-- json-stringify-safe@5.0.1
|   | +-- node-uuid@1.4.7
|   | +-- oauth-sign@0.8.2
|   | +-- qs@6.3.0
|   | +-- stringstream@0.0.5
|   | +-- tough-cookie@2.3.2
|   | | `-- punycode@1.4.1
|   | `-- tunnel-agent@0.4.3
|   `-- semver@5.3.0
+-- rimraf@2.5.4
+-- rxjs@5.0.1
| `-- symbol-observable@1.0.4
+-- systemjs@0.19.40
| `-- when@3.7.7
+-- tslint@3.15.1
| +-- diff@2.2.3
| +-- findup-sync@0.3.0
| | `-- glob@5.0.15
| `-- underscore.string@3.3.4
|   +-- sprintf-js@1.0.3
|   `-- util-deprecate@1.0.2
+-- typescript@2.0.10
`-- zone.js@0.7.6

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

### Mention any other details that might be useful.
I already updated nodejs to the latest version 7.5
tried the quickstart install in dozens of different maps

**Comment by baruchvlz** [comment]
So, what's the error? If you're talking about the warnings, those are optional dependencies. The app should still run.

**Comment by itsnotvalid** [comment]
fsevents is a dependency that only needed on mac. There is warning for that though (https://github.com/npm/npm/issues/11632).

**Comment by filipesilva** [comment]
I have no idea what's the problem here, nor do I know what `quickstart-master.zip` is. Please open a new issue with a better description of what the problem you are experiencing is, and hot to reproduce it.

**Comment by Jayawardhana** [comment]
This is not a error.this is about warn optional dependancy, if you want you can install them you can do your works without them
