### ISSUE TITLE
Cannot find module 'underscore'.

### ISSUE THREAD

**Issue by JesseSoldat** [angular/angular-cli#4636]
I am trying to include Underscore     "underscore": "^1.8.3"
and I get this error  Cannot find module 'underscore'.

This is how I try to import it.
import * as _ from 'underscore';

I went online to look for a solution which there where many from last year by including it in the system-config.js and typings.json files. However I do not have these files in my project. I guess they are no longer provided. 

Is there a current solution for importing underscore?

This is the first time to report an issue so hopefully my issue makes sense

Thanks,
Jesse Soldat

**Comment by shrej** [comment]
@JesseSoldat : 
I am new to this project, but it looks like [Lodash](https://lodash.com/) already exists in this [project](https://github.com/angular/angular-cli/blob/master/package.json#L75) . Maybe you could just use that ?

**Comment by beeman** [comment]
If you have a recent Angular CLI project you should be able to fix this by running this:

```
$ npm install --save-dev @types/underscore
```

Typings have been replaced by `@types` and SystemJS is no longer used by apps created by Angular CLI - these now use WebPack.

**Comment by hansl** [comment]
Closing this as answered.

**Comment by JesseSoldat** [comment]
npm install -g typescript@next
And then

npm install --save underscore
npm install --save @types/underscore

This worked for me. Thanks everyone

**Comment by cw-sangram** [comment]
Following script worked for me.
`npm install --save @types/underscore`

**Comment by sisimogangg** [comment]
@JesseSoldat's solution worked for me.  Wish someone could explain why.

**Comment by mahmoudElhawary** [comment]
cl;lfcf

**Comment by stvenyin** [comment]
Thank you!
