### ISSUE TITLE
ngtools/webpack generate big size file! 

### ISSUE THREAD

**Issue by keyiis** [angular/angular-cli#4646]
### OS?
> win10 x64

### Versions.
> node 6.9.2

```
"@angular/compiler-cli": "^2.4.6",
    "@angular/platform-server": "^2.4.6",
    "@ngtools/webpack": "^1.2.8",
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.0",

```

### Repro steps.
complier process no error and running ok,but the generate bundle file size nearly 7M,if i set skipCodeGeneration:true,generate bundle file size 6.4M, so ngtools/webpack not work ?
below is config files
**tsconfig.aot.json**

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2015",
      "dom"
    ],
    "noEmit": true,
    "skipDefaultLibCheck": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
      "node_modules/@types/",
      "typings/"
    ]
  },
  "angularCompilerOptions": {
    "skipMetadataEmit": true
  },
  "compileOnSave": false,
  "exclude":["node_modules","output"]
}
```

**webpack.aot.js**

```
module.exports = webpackMerge(commonConfig, {
  entry: {
    'app': helpers.rootAngular('app/main.ts')
  },
  output: {
    path: helpers.outputBuild(),
    filename: '[name].[hash].bundle.js',
		chunkFilename: '[id].[chunkhash].chunk.js'
  },

  module: {
    loaders: [
      { test: /\.ts$/, loaders: ['@ngtools/webpack'] },
      {
        test: /\.css$/,
        exclude: helpers.rootAngular('app'),
        loader: ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader' })
      },
    ]
  },
  plugins: [
    new AotPlugin({
        skipCodeGeneration:false,
        tsConfigPath: helpers.root('tsconfig.aot.json'),
        entryModule: helpers.rootAngular('app/app.module#AppModule')
    }),
    new webpack.LoaderOptionsPlugin({
      test: /\.css$/, // optionally pass test, include and exclude, default affects all loaders
      minimize: true,
      debug: false,
    }),
    new webpack.NoEmitOnErrorsPlugin(),
    new HtmlWebpackPlugin({
      template: helpers.rootAngular('index.html'),
      minify:{
        removeComments:true,
        collapseWhitespace: true
      }
    }),
    new ExtractTextPlugin('[name].[hash].css'),
    new webpack.DefinePlugin({
      'process.env': {
        'ENV': JSON.stringify(ENV)
      }
    })
  ]
});
```

### The log given by the failure.
> no failure,but it seems like not work

**Comment by LosD** [comment]
You seem to be mixing dependencies and devDependencies?

**Comment by tk5641** [comment]
I think something is wrong.
Even if you did not use uglify and minify files 7MB is too big..
Did you used lazy loading in ng2?
can you compare with my example project in here ?

[https://github.com/tk5641/angular2-webpack2-aot](url)

**Comment by tk5641** [comment]
When I test from my project, my bundle file is
app.1eef97e087da9383d.js  is          439KB ,
pollyfills.1eef97e087da9383d.js is    143KB

**Comment by keyiis** [comment]
@LosD i confrim not mixed,i used process.env.NODE_ENV to control JIT or AOT in webpack.common.js
```
switch (process.env.NODE_ENV) {
  case 'prod':
  case 'production':
    module.exports = require('./config/webpack.aot');
    break;
  case 'dev':
  case 'development':
  default:
    module.exports = require('./config/webpack.dev');
}
```

**Comment by keyiis** [comment]
@tk5641  i won't use lazy loading,i only hope get AOT and shaketree through ngtools/webpack

**Comment by tk5641** [comment]
@keyiis Did you import in your app any other external js files or plugins size is big ?

**Comment by keyiis** [comment]
@tk5641 i already set big size plugin to externals,and if this is the reason,why JIT bundle file size(6.4M) small than AOT?
```
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const helpers = require('./helpers');
module.exports = {
  entry: {
    'polyfills': helpers.rootAngular('polyfills.ts'),
    'vendor': helpers.rootAngular('vendor.ts')
  },

  resolve: {
    extensions: ['.js', '.ts']
  },

  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /(node_modules|output)/,
        loader: 'babel-loader', // 'babel-loader' is also a legal name to reference
        options: {
          presets: ['latest']
        }
      },
      
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.html$/, loader: 'raw-loader' },
      {
        test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
        loader: 'file-loader?name=assets/[name].[hash].[ext]'
      },
      {
        test: /\.css$/,
        include: helpers.rootAngular('app'),
        use: 'raw-loader'
      }
    ]
  },
  externals: {
    "electron":"require('electron')",
    "sequelize": "require('sequelize')",
    "moment":"require('moment')",
    "pinyin":"require('pinyin')",
    "sqlite3":"require('sqlite3')",
    "printer": "require('printer')",
    "serialport": "require('serialport')",
    "fs":"require('fs')"
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: ['app', 'vendor', 'polyfills']
    })
  ]
};

```

**Comment by tk5641** [comment]
can you add this plugin in your webpack.aot.js ? (push in plugins array)

`new webpack.optimize.UglifyJsPlugin({
      compress: {
          warnings: false,
          drop_console: true
      },
      output: {
          comments: false
      }
    }),`

unless you installed uglify-js module you have to install it first
`npm install --save -dev@types/uglify-js`

And can you show me your bundle file size with aot compile ?

**Comment by keyiis** [comment]
@tk5641 i already try uglify-js,after uglify,the bundle size nearly 4M,still to big, below is my webpack.aot.js plugins
```
plugins: [
    new AotPlugin({
        skipCodeGeneration:false,
        tsConfigPath: helpers.root('tsconfig.aot.json'),
        entryModule: helpers.rootAngular('app/app.module#AppModule')
    }),
    new webpack.LoaderOptionsPlugin({
      test: /\.css$/, // optionally pass test, include and exclude, default affects all loaders
      minimize: true,
      debug: false,
    }),
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.optimize.UglifyJsPlugin({
            beautify: false,
            mangle: {
                screw_ie8: true,
                keep_fnames: true
            },
            compress: {
                warnings: false,
                screw_ie8: true
            },
            comments: false
    }),
    new HtmlWebpackPlugin({
      template: helpers.rootAngular('index.html'),
      minify:{
        removeComments:true,
        collapseWhitespace: true
      }
    }),
    new ExtractTextPlugin('[name].[hash].css'),
    new webpack.DefinePlugin({
      'process.env': {
        'ENV': JSON.stringify(ENV)
      }
    })
  ]
```

**Comment by keyiis** [comment]
@tk5641 Latest screenshots,after Uglify.
![qq 20170214141832](https://cloud.githubusercontent.com/assets/7766085/22917567/899548ac-f2c0-11e6-9d4d-5877b15ee9ef.png)

**Comment by keyiis** [comment]
@tk5641 i guess ngtools/webpack contain all imported package in compile process,so ignore webpack's externals property?

**Comment by tk5641** [comment]
I guess at least in file size issue,  your app have too many external dependencies.
And I think **JIT bundle file size(6.4M) can be smaller than AOT at least in bundle file itself, because AOT make sense in faster rendering.**
When you use JIT, your browser  more than anything else, have to load vendor.js first, and compile your ng2-app just in time. it will make your site rendering too slow.
AOT compile will make your app to be interpreted immediately without browser compile.
Additionally, When you use JIT compile,  you have to measure file size with your bundle files + vendor.js file. 
Because AOT do not need vendor file.

**Comment by keyiis** [comment]
@tk5641 i find some different from you example
**your tsconfig-aot.json**
```
"angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit" : true
  }
```
**my tsconfig.aot.json**
```
"angularCompilerOptions": {
    "skipMetadataEmit": true
  },
```
why you set genDir?ngtools/webpack will auto gen aot file in memory and auto replace app.module#AppModule.

**Comment by tk5641** [comment]
you are right, when use @ngtools/webpack 
angularCompileOption doesn't need genDir property.

I have to fix it :)

**Comment by keyiis** [comment]
@filipesilva @hansl  please help me :pray:

**Comment by tk5641** [comment]
Can I ask why don't you use lazy loading in ng2 ?

When I used lazy load, I could reduce my bundle file size almost in half.

**Comment by keyiis** [comment]
@tk5641 Because my app run in local,not on webserver,i just want reducing published app size.
i think lazy load is not what the cause of the problem,maybe webpack‘s config/tsconfig/ngtools/webpack

**Comment by filipesilva** [comment]
@keyiis I investigated this a bit, and for applications with big templates the AoT'd bundle size **can** be bigger. This is because the compiled templates may end up being bigger than uncompiled html. The application will always be faster to run though since there's no runtime compilation.

There's also major improvements in AoT bundle size coming in Angular version 4.

**Comment by nikolasleblanc** [comment]
@keyiss, have you tried the CompressionPlugin? With an AoT bundle you can yield some serious wins with it in terms of file size, and using compression on your production bundles is generally part of a production pipeline to begin with.

**Comment by keyiis** [comment]
@nikolasleblanc thks reply! i think maybe has many not used imported module in js bundle file ,but shaketree not work,so that's the file so large,if in development mode,the bundle file nearly 19M(contain sourcemap),my app first load nearly 10s.
