### ISSUE TITLE
tslint says inferable types schema is invalid

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#4648]
tslint says 

```
file: 'file:///Users/john/_git/angular-event-view-cli/tslint.json'
severity: 'Warning'
message: 'Incorrect type. Expected "array"'
at: '49,28'
source: ''
```

for this line ...

https://github.com/angular/angular-cli/blob/601f9b38f8ce53052d623a4b8a2dc5bb30f9eee1/packages/%40angular/cli/blueprints/ng2/files/tslint.json#L49

**Comment by ruffiem** [comment]
What about `"no-inferrable-types": [true, "ignore-params"]` ?

**Comment by johnpapa** [comment]
yep, that's the fix.  i just havent had time to make the PR yet.
