### ISSUE TITLE
Karma runner logs warning for public assets

### ISSUE THREAD

**Issue by CrisGrec** [angular/angular-cli#465]
The `karma.conf.js` currently proxies requests as follows: `'/app/': '/base/dist/app/'`.

However if you put an asset such as an image in the `public` directory, the asset is placed into the root of the `dist` directory when built. The result is that karma will log a warning each time the asset is requested:

`19 04 2016 23:34:57.334:WARN [web-server]: 404: /image.png`

Not sure if it's a valid solution, but changing the proxy to `'/': '/base/dist/'` allows requests to `app` to behave as normal, while including requests to assets in the root of `dist`, eliminating the warnings.

**Comment by filipesilva** [comment]
I'll put up a PR with your fix. If it horribly breaks everything, our tests should be able to show since they run `ng test` a whole lotta times.

**Comment by filipesilva** [comment]
Seems fine really, it's in!
