### ISSUE TITLE
The app loading is very slow when 'ng serve' or dev mode. But it good when deploying to production

### ISSUE THREAD

**Issue by dinhduongrestaff** [angular/angular-cli#4651]
After I update my Angular CLI to version beta30. I see `ng serve` bundle so fast but the site loading very slow. But when I deploy to production it back good. Because of the reloading very slow so it will affect my speed to ng2 app development.

Thanks all.

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Window 8

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.7
@ngtools/webpack: 1.2.9

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
This app created by Angular CLI beta30

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
That sounds like you need to change some stuff in your project, to make it load faster. 

Try using the chrome devtools to debug what's making it slow.
