### ISSUE TITLE
Google Crawling 

### ISSUE THREAD

**Issue by kakul232** [angular/angular-cli#4652]

**Comment by RicardoVaranda** [comment]
@kakul232 Can you pleases use the template provided when creating an issue.

**Comment by grizzm0** [comment]
I guess you're asking about SEO with angular2. For this you need server-side rendering using angular universal.

See: https://universal.angular.io/quickstart/

**Comment by filipesilva** [comment]
Closing as this was a zero effort issue. Please open a new issue where you actually fill in the template and give a useful description of what your issue is.
