### ISSUE TITLE
base href gets overwritten with / even though no --build-href parameter given

### ISSUE THREAD

**Issue by alpengeist** [angular/angular-cli#4655]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
W10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.28.3                     
node: 6.9.1                                      
os: win32 x64                                    
@angular/common: 2.4.7                           
@angular/compiler: 2.4.7                         
@angular/core: 2.4.7                             
@angular/forms: 2.4.7                            
@angular/http: 2.4.7                             
@angular/platform-browser: 2.4.7                 
@angular/platform-browser-dynamic: 2.4.7         
@angular/router: 3.4.7                           
@angular/compiler-cli: 2.4.7                     

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Built with CLI.
I have the `base href` /monitor/ui/ in index.html. This used to be preserved with `ng build` in beta 25.5.  With 28.3. it gets overwritten with /. I had to supply the `-bh` parameter to fix it.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
@alpengeist can you try with the latest beta-31 and see if this is still an issue?

**Comment by alpengeist** [comment]
@deeblo yes, still the same.

**Comment by clydin** [comment]
Can you confirm that you are seeing the problem with 1.0.0-beta.31?  Please note that the package name has changed to '@angular/cli'.

**Comment by alpengeist** [comment]
Argh. I have confusion in my npm packages. Let me fix that first.

**Comment by alpengeist** [comment]
Okay, sorry, I have not noticed that beta-28 was still active after installing 31. I can confirm that 31 has fixed the problem. Thanks!
