### ISSUE TITLE
tsmagicString.insertLeft(...) is deprecated. Use magicString.appendLeft(...) instead

### ISSUE THREAD

**Issue by Nikki1993** [angular/angular-cli#4657]
### OS?
macOS 10.12.3

### Versions.

- @angular/cli: 1.0.0-beta.31
- node: 7.5.0
- os: darwin x64
- @angular/common: 2.4.7
- @angular/compiler: 2.4.7
- @angular/core: 2.4.7
- @angular/flex-layout: 2.0.0-beta.5
- @angular/forms: 2.4.7
- @angular/http: 2.4.7
- @angular/material: 2.0.0-beta.1
- @angular/platform-browser: 2.4.7
- @angular/platform-browser-dynamic: 2.4.7
- @angular/router: 3.4.7
- @angular/cli: 1.0.0-beta.31
- @angular/compiler-cli: 2.4.7

### Repro steps.

1. Create a new project
2. Upgrade all components to latest version
3. Add new service component
4. Call a simple http.get method to anything, in my case it's a firebase database like this 
```
getFirebase() {
    const firebase = 'https://sampledatabase.firebaseio.com/mydb.json'; // not the actual databse, dummy url

    return this.http.get(firebase).map(response => response.json());
  };
```
5. Run `ng serve --aot --live-reload`
6. Witness the error in the title `myservice.service.tsmagicString.insertLeft(...) is deprecated. Use magicString.appendLeft(...) instead`

### The log given by the failure.
`myservice.service.tsmagicString.insertLeft(...) is deprecated. Use magicString.appendLeft(...) instead
`
### Mention any other details that might be useful.
I am using yarn to install dependencies

**Comment by Nikki1993** [comment]
Not sure, but possibly related to this issue [#4640](https://github.com/angular/angular-cli/issues/4640) however in that case person runs test suit, I am using ng serve.

**Comment by clydin** [comment]
This is fixed in master (https://github.com/angular/angular-cli/pull/4582) but thanks for reporting.

Also,  live reload is enabled by default for serve.  You don't have to specify it manually.

**Comment by Nikki1993** [comment]
Cheers :)
