### ISSUE TITLE
Eliminate duplication of reporters in karma.conf.js

### ISSUE THREAD

**Issue by rkrisztian** [angular/angular-cli#4658]
### OS?
Red Hat Enterprise Linux Workstation release 6.8 (Santiago)

### Versions.
```
@angular/cli: 1.0.0-beta.31
node: 6.9.4
os: linux x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
```

### Repro steps.
(N/A)

### The log given by the failure.
(N/A)

### Mention any other details that might be useful.
I've seen some projects wanting to change the current way reporters are configured in `karma.conf.js`, because in the current form, they can't easily add additional reporters used unconditionally, e.g, `junit`. So I suggest to do a small change like this:

**Current:**

```
reporters: config.angularCli && config.angularCli.codeCoverage
	? ['progress', 'coverage-istanbul']
	: ['progress'],
```

**Better:**

```
reporters: ['progress'].concat(
	config.angularCli && config.angularCli.codeCoverage ? ['coverage-istanbul'] : []),
```

**Comment by Meligy** [comment]
Sounds like a good idea.

Would you like to create a small pull request for that?

Here's the file to modify
https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng2/files/karma.conf.js

Cheers

**Comment by rkrisztian** [comment]
Sure, done.

**Comment by rkrisztian** [comment]
https://github.com/angular/angular-cli/pull/4689

**Comment by filipesilva** [comment]
Closing, reason in https://github.com/angular/angular-cli/pull/4689#issuecomment-279769770
