### ISSUE TITLE
Where is the command "ng github-pages:deploy"?

### ISSUE THREAD

**Issue by only-gale** [angular/angular-cli#4659]
How can I publish the github page?

**Comment by only-gale** [comment]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Linux (Ubuntu 16.04LTS).

### Versions.
> @angular/cli: 1.0.0-beta.31
node: 7.5.0
os: linux x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
@angular/flex-layout: 2.0.0-beta.5
@angular/material: 2.0.0-beta.1

### Repro steps.
> Run the command on the CLI: ng github-pages:deploy

### The log given by the failure.
> The specified command github-pages:deploy is invalid. For available options, see `ng help`.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by delasteve** [comment]
It was removed in `beta.31` 

https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#code-refactoring

> @angular/cli: The deploy command is being removed from the core of the CLI. There are several options for deploying CLI-based applications outside the scope of this project. One of which being https://github.com/angular-buch/angular-cli-ghpages

**Comment by only-gale** [comment]
@delasteve Thanks a lot. I'll find an another way! But I still think that was a very convenient command.

**Comment by krishnaUIDev** [comment]
Am facing the same issue with ng:github-pages:deploy
`$ ng github-pages:deploy
The specified command github-pages:deploy is invalid. For available options, see `ng help`.
`
