### ISSUE TITLE
ng serve ignores assets

### ISSUE THREAD

**Issue by kaynz** [angular/angular-cli#4663]
### OS?
ArchLinux, Windows 10

### Versions.
@angular/cli: 1.0.0-beta.31
node: 7.5.0
os: linux x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

### Repro steps.
ng new test
touch test/src/assets/test.json
ng serve

### Bug
There's no assets available, see chrome sources: https://paste.xinu.at/DQf5y/

**Comment by sthuck** [comment]
The assets are available and are not ignored. Try adding an image, or a css stylesheet, something that will cause the browser to download the file, and you will see it in chrome dev tools under 'localhost:4200'. 

#goodnessSquad

**Comment by kaynz** [comment]
Yea, sorry :(

**Comment by uli-weltersbach** [comment]
I'm having trouble getting this to work.
E.g. when I place a file in, say "/assets/my-data.json", it gets copied to the "/dest" dir just fine when I run "ng build", but when I run "ng serve" I don't see it anywhere and the app can't find it either (i.e. can't get it using the HTTP service).
