### ISSUE TITLE
Debug angular cli app on external device

### ISSUE THREAD

**Issue by gkucmierz** [angular/angular-cli#4671]
How can I debug angular cli app on external device?
ng serve is running server on localhost, which is not visible in my private network, so I am not able to reach it by 192.168....:4200

**Comment by beeman** [comment]
@gkucmierz you can use `ng serve --host 0.0.0.0` to make it listen on all IP addresses.

**Comment by gkucmierz** [comment]
I found out I can use also USB debug or bluetooth debug.
But your solution is much better in my case.
Thanks man!

**Comment by filipesilva** [comment]
Closing as answered by @beeman, thanks!
