### ISSUE TITLE
ng --v returns "SyntaxError: Use of const in strict mode."

### ISSUE THREAD

**Issue by 2rik** [angular/angular-cli#4672]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7 64 bit.

### Versions.
> angular/cli: v1.0.0-beta.30 
> npm: 4.2.0
> System Path: C:\Users\{user}\AppData\Roaming\npm

### Repro steps.
> Running ng --version returns:

C:\Users\{user}\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng:7
const CliConfig = require('../models/config').CliConfig;
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by sthuck** [comment]
try using node v6.9.x.

#goodnessSquad

**Comment by Brocco** [comment]
@2rik can you please confirm your version of node?

The minimum supported version is 6.9 for `@angular/cli` beta.30+

**Comment by 2rik** [comment]
@sthuck @Brocco 
Thanks, resolved now.
Had to manually download and replace nodejs.exe, cause automatic installation have not replaced executable.

**Comment by Brocco** [comment]
Reported as fixed/working, closing this issue.

**Comment by rajneeshkumardev** [comment]
@sthuck 
I am getting the same error  on ng --v returns
Can you suggest what you have exactly?
