### ISSUE TITLE
Spread operator doesn't work in Angular generated project but runs in plain typescript

### ISSUE THREAD

**Issue by Nikki1993** [angular/angular-cli#4688]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Running this piece of code inside ngOnInit
```
const progressDefault = {
        bgRadius: 60,
        bgColor: this.colors.orange,
        rounded: false,
        reverse: false,
        animationSecs: 2,
        labels: [],
        segments: []
      };

      const object2 = {
        ...progressDefault
      };

      console.log(object2);
```

results in an error 

```
./src/app/app.component.ts
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at _getContentOfKeyLiteral (/Users/kononnik/git/alicia/node_modules/@ngtools/webpack/src/loader.js:9:13)
    at node.properties.some.prop (/Users/kononnik/git/alicia/node_modules/@ngtools/webpack/src/loader.js:205:56)
    at Array.some (native)
    at refactor.findAstNodes.filter (/Users/kononnik/git/alicia/node_modules/@ngtools/webpack/src/loader.js:205:43)
    at Array.filter (native)
    at _removeModuleId (/Users/kononnik/git/alicia/node_modules/@ngtools/webpack/src/loader.js:205:10)
    at Promise.resolve.then.then (/Users/kononnik/git/alicia/node_modules/@ngtools/webpack/src/loader.js:301:33)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/app.module.ts 14:0-47
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
```

**Expected behavior**

Object properly copied and printed in the console like in this example https://www.typescriptlang.org/play/index.html#src=const%20ar%20%3D%20%7B%0D%0A%20%20%20%20text%3A%20'Hello'%0D%0A%7D%3B%0D%0A%0D%0Aconst%20ar2%20%3D%20%7B%0D%0A%20%20%20%20...ar%2C%0D%0A%20%20%20%20label%3A%20'Nikki'%0D%0A%7D%3B%0D%0A%0D%0Aconsole.log(ar)%3B%0D%0Aconsole.log(ar2)%3B

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
macOS 10.12.3, Node 7.5.0 latest beta31 angular-cli 

* **Angular version:** 2.0.X
2.4.7

* **Browser:** Chrome 56 but fails alread at webpack compilation
 
* **Language:** Typescript

**Comment by Meligy** [comment]
Is this a duplicate of https://github.com/angular/angular-cli/issues/4600?

If so, it should be fixed in https://github.com/angular/angular-cli/pull/4642, which is merged in master, but not released yet.

**Comment by Nikki1993** [comment]
@Meligy by the looks of it yea, weird, I tried searching for the error message before posting issue but nothing came up. Apologies for the dupe.
