### ISSUE TITLE
Services and pipes don't have a folder anymore

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#470]
With angular-cli 0.0.33, generating a new service or pipe add all the files in `src/client/app` whereas it used to add them in a dedicated folder, is that on purpose or a bug?
This is going to rapidly stop scaling, even with a few services or pipes.

**Comment by Brocco** [comment]
By default pipes & services are generated without their own dedicated folders in a manner that is being referred to as `flat` meaning no additional folder structure. This can be overridden when generating by specifying the argument: `--flat false`

The reason for the change is that there are only 2 files and therefore do not necessitate a new folder by default.

**Comment by cexbrayat** [comment]
Thanks. I was pointing out that a folder by default would probably make things easier as a typical project will quickly grow (and have 10s of files in src/client/app). Don't you think?

**Comment by Brocco** [comment]
Yes, that can be a concern. But that concern is being addressed by the style guide, which is what this change was based upon.

The style guide dictates that when a route is generated a shared dir is created with the intention that the related services/pipes/directives/(non-routable)components will get generated into that shared directory, associated to the corresponding route.

Does that makes sense?

**Comment by cexbrayat** [comment]
That would only leave the services and pipes that are not associated with a particular route but shared between multiple components. And that tends to be quickly quite a few, at least in my apps...

**Comment by PascalPrecht** [comment]
@cexbrayat you can always explicitly generate a folder structure by setting `--flat false`

**Comment by cexbrayat** [comment]
Of course, I get that. I was just pointing out that the previous default was more suited in my opinion. If you're confident that the switch is better, I'll close the issue.

**Comment by Brocco** [comment]
@cexbrayat something on the roadmap is making things more configurable at all levels (user/project/command args) I can certainly see a setting which will specifies how pipes and services get generated expanding beyond its current command arg specification into the project and user config level
