### ISSUE TITLE
Build -prod don't use environment.prod.ts parameters

### ISSUE THREAD

**Issue by bvaissade** [angular/angular-cli#4711]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10 (32bits)

### Versions.

@angular/cli: 1.0.0-beta.31
node: 7.5.0
os: win32 ia32
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

### Repro steps.
When building with -prod param, the environment.prod.ts in src/environments folder is not use !

### Mention any other details that might be useful.
It was ok with the angular-cli 1.0.0-beta.26.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bvaissade** [comment]
All others params (target, env..) fail the same way.

**Comment by phillip-haydon** [comment]
#4710

**Comment by deebloo** [comment]
can you share the code where you are using the environment file? May I assume you are "providing" the environment file?

**Comment by phillip-haydon** [comment]
It's not being used anywhere... we just use the same build command across different projects for consistency. Only 1 of 5 projects uses it and this isn't one of them.

**Comment by RicardoVaranda** [comment]
Can you post an example on how you are loading the environments file?

Please be sure to import from environments/environment and not environments/environment.prod

**Comment by bvaissade** [comment]
Try with a brand new project (made with `ng init`). 
Always en dev mode with `ng serve --env=prod` !

**Comment by RicardoVaranda** [comment]
@bvaissade I did the following on app.component.ts:
```
import {environment} from './../environments/environment'
...

ngOnInit(){
    console.log('ENV IS ', environment)
  }
```

My environment.prod.ts looks like:
```
export const environment = {
  production: true,
  test: 'hi'
};
```

Once I ran the applications I get those parameters.

**Comment by bvaissade** [comment]
I have try your code. Same bug !
Here my **environment.prod.ts**

```
export const environment = {
  production: true
};
```

Here my **app.component.ts** :

```
import { Component } from '@angular/core';
import {environment} from './../environments/environment'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';

  ngOnInit(){
    console.log('ENV IS ', environment)
  }
}
```

Here my console log after **ng serve --env=prod** :

```
Mode DEV...
app.component.ts:  ENV IS  Object production: false

Angular is running in the development mode. Call enableProdMode() to enable the production mode.
```

**Comment by ukaaa** [comment]
I have the same problem after upgrading from `angular-cli@1.0.0-beta.24` to `@angular/cli@1.0.0-beta.30`.

**Comment by ukaaa** [comment]
```
ng serve
```
This correctly takes the content from the environment specified as `environments.dev` in `angular-cli.json`.

```
ng serve --prod
```
This seems to take the content from the environment specified as `environments.source` in `angular-cli.json`. The environment specified under `environments.prod` in `angular-cli.json` is either never read or never written. I don't get it.

**Comment by bvaissade** [comment]
Ok I have try with @ukaaa command 

`ng serve --target=production --environment=prod`

but allway en DEV mode :-(

**Comment by filipesilva** [comment]
@bvaissade I don't see that with the latest version (beta.32-3):

![image](https://cloud.githubusercontent.com/assets/4172079/23064665/3e48bac8-f509-11e6-8766-f12018a6bb7d.png)

**Comment by bvaissade** [comment]
Can't test it ! Lot of errors in my .angular.cli.json.
Like :
` "$schema": `"./node_modules/@angular/cli/lib/config/schema.json",``


And `ng new` don't works.

**Comment by ukaaa** [comment]
@bvaissade I'm sorry, I could have sworn it works but today I try again and it doesn't. This is very frustrating.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
