### ISSUE TITLE
infinite loop with live reload build

### ISSUE THREAD

**Issue by lebesnec** [angular/angular-cli#4714]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.28.3
node: 6.9.5
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.7

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

The app was copied from here : https://github.com/angular-starter-kit/ngx-starter-kit I don't know if it was created with the CLI or not.

### The log given by the failure.
> Normally this include a stack trace and some more information.

the initial ng serve seem to work well, but when I start to edit files I've got the following looping over and over in the CLI :

![image](https://cloud.githubusercontent.com/assets/49292/22980640/5b1cf1ac-f39a-11e6-97c0-8b29b34ab3a9.png)

and in the chrome console :

![image](https://cloud.githubusercontent.com/assets/49292/22980726/a3595438-f39a-11e6-9616-44e0fc3b5129.png)

### Mention any other details that might be useful.

I was using visual studio code and it seem there is/was some similar issues with it (see https://github.com/angular/angular-cli/issues/2497 ). But the problem remain even when visual studio code is closed.
I'm behind a corporate proxy and I have to use cntlm in order to have the install command to download the dependencies. Also I have to run the command line as an admin (rigth clic on cmd.ewe / run as an adminsitrator) in order to have the permission to launch the serve command.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by lebesnec** [comment]
it turn out the antivirus (mcAffe) is messing with the files ... And I can't disable it on my machine :(

**Comment by renaudaste** [comment]
A bit late, but if anyone else encounter this issue, you can try a workaroung with the `--poll  ` option (https://github.com/angular/angular-cli/wiki/serve) 
```bash
ng serve --poll 1000
```
