### ISSUE TITLE
ng serve --proxy-config proxy.conf.json no longer works for me when going to beta 31 (from beta 24)

### ISSUE THREAD

**Issue by emcpadden** [angular/angular-cli#4727]
After upgrading from cli beta 24 to beta 31 the proxy functionality has changed and no longer generates a /dist folder when doing a ng serve.  This is causing a problem because I use the proxy functionality to serve the app from an express app in the same project.

### OS?
> Mac OSX Sierra

### Versions.  
node --version: 6.9.1
ng --version:
@angular/cli: 1.0.0-beta.31
node: 6.9.1
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-alpha.10
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

### Repro steps.
I just upgraded from beta 24 to beta 31.  
I am running:
ng serve --proxy-config proxy.conf.json

my proxy.conf.json is as follows:
```
{
  "/": {
    "target": "http://localhost:3000",
    "secure": false
  }
}
```

NOTE: my project contains an express app that is used to serve the angular app.  We also use the express app for our API. Also, we serve the index.html file from the express app because we are dynamically setting the base href.  I guess we could figure out a better way to deal with the base href if needed.

Previously, in beta 24 this worked worked great, but in beta 31 it does not create the /dist folder so this proxy no longer works because the express app (running on port 3000) cannot find any of the files in the /dist folder because it is not there.

I thought that maybe there was a way to only proxy the API calls and not the index.html or any of the css or js, so I tried the following proxy.conf.json:

```
{
  "/analytics/api-dev": {
    "target": "http://localhost:3000/analytics/api-dev",
    "secure": false
  }
}

```
When I run:

It will now start to load the app, it looks like it was able to find my indext.html but I get a 404 on all of the CSS and js files, for instance here are a couple it 404's on:
GET http://localhost:4200/fleet/assets/dsh_main.css 
GET http://localhost:4200/fleet/inline.bundle.js 
GET http://localhost:4200/fleet/scripts.bundle.js 

Is there a way to only proxy the API calls and have the index.html, css and js files not go thru the proxy?

Or is there a way to still get it to build the /dist folder and keep it up to date?

I won't be able to upgrade until I can solve this problem.

Thanks so much for your help!!!
... Ed

**Comment by clydin** [comment]
`ng serve` builds and serves everything in memory (beta.24 did this as well).  A recent change was made that causes `ng serve` to delete the output directory upon execution to prevent confusion in this regard.

An option, if you are serving the app with express, is to use `build --watch`.  This will give you an up to date output that express can then serve.

**Comment by emcpadden** [comment]
@clydin THANKS!!! This works great!

Do you know if there is a way to get the live reload to work with a `build --watch`?

**Comment by clydin** [comment]
Unfortunately, there's no live reload support for `build --watch`.

**Comment by emcpadden** [comment]
@clydin ok, thanks so much for your help.
