### ISSUE TITLE
Cache-busting (--prod)

### ISSUE THREAD

**Issue by lucianocn** [angular/angular-cli#4728]
`ng build --prod` or `ng serve --prod` create css/js files with a HASH, like:

styles.6f851ef5ed61f94dfc02.bundle.css
inline.97f84214598998adf604.bundle.js
scripts.7bf3eef718d3d11d4686.bundle.js
...

I'm using UpUp (https://github.com/TalAter/UpUp), to have a Offline version of my website.
I need to know exactly the files name to cache them.

How can I get those bundle names to use with UpUp in my index.html?

Thanks,

**Comment by hansl** [comment]
You can remove the hashes by using `ng build --prod --output-hashing=none`. Otherwise, you'll have to do it outside of the CLI, either by making a JSON from the output of the build and loading it in your app, or some external mechanism.
