### ISSUE TITLE
Cannot load third party assets outside src folder

### ISSUE THREAD

**Issue by MohitSuhane** [angular/angular-cli#4731]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 8.1 Pro

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
Angular-cli: 1.0.0-beta.24
node: 6.2.1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
1. I have to load third party assets but in the angular-cli.json the assets parameter only accepts files or folder that is inside src folder. 
2. If we give any file or folder that are outside src folder it never gets copied to build folder.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
The styles and scripts parameter in angular-cli are able to load third party styles and scripts.
Can we have the same for assets parameter as well.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/4691
