### ISSUE TITLE
TypeError: Cannot read property 'config' of null

### ISSUE THREAD

**Issue by soodvarun** [angular/angular-cli#4736]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
@angular/cli: 1.0.0-beta.31
node: 6.9.4
os: win32 x64
@angular/cli: 1.0.0-beta.31
@angular/common: 2.2.4
@angular/compiler: 2.2.4
@angular/compiler-cli: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.2.4
@angular/http: 2.2.4
@angular/platform-browser: 2.2.4
@angular/platform-browser-dynamic: 2.2.4
@angular/router: 3.2.4
@angular/upgrade: 2.2.4
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Added cli later and did ng init

### The log given by the failure.
> Normally this include a stack trace and some more information.

 ```
ng build --prod --verbose
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (C:\Projects\Someplace\Portal\Someplace\node_modules\@angular\cli\tasks\build.js:14:89)
    at Class.run (C:\Projects\Someplace\Portal\Someplace\node_modules\@angular\cli\commands\build.js:49:26)
    at Class.<anonymous> (C:\Projects\Someplace\Portal\Someplace\node_modules\@angular\cli\ember-cli\lib\models\command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

```
### Mention any other details that might be useful.
The offending line 
` const outputPath = runTaskOptions.outputPath ||  config_1.CliConfig.fromProject().config.apps[0].outDir;`

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ardiadrianadri** [comment]
I know why it is happening but I don't know how to solved. The problem is that the transpiled JS code remove the "." at the beginning  of the string ".angular-cli.json", so angular-cli cannot find the configuration file because it is looking for a file that doesn't exist. Let me show you:

This is the content of packages/@angular/cli/models/config.ts:
```
(...)
import * as chalk from 'chalk';
import * as fs from 'fs';
import * as path from 'path';

export const CLI_CONFIG_FILE_NAME = '.angular-cli.json';
const CLI_CONFIG_FILE_NAME_ALT = 'angular-cli.json';
(..)
``` 
As you can see, the variable CLI_CONFIG_FILE_NAME stores the name of the angular-cli configuration file that is in the root path of your project. However, once you create a new project with angular-cli, the same variable has another value:

node_modules/@angular/cli/models/config.js
```
(...)
const chalk = require('chalk');
const fs = require('fs');
const path = require('path');
exports.CLI_CONFIG_FILE_NAME = 'angular-cli.json';
function _findUp(name, from) {
(...)
```
The "." of ".angular-cli.json" has gone. This is the reason why we are getting a null in the config, because angular-cli is looking for 'angular-cli.json' but the real file is .angular-cli.json. I don't know why it is happening. My guess is that there is a problem with the TypeScript configuration but I'm not sure.

The workaround is easy. First, change the name of the ".angular-cli.json" in the root folder for "angular-cli.json". After that, add the property app.environments.sorce with the relative path of the environment configuration file that you want use by default:

```
"environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
 }
```
I hope this helps.

**Comment by bougnat12** [comment]
I have the same issue after installing @angular/cli 1.0.0-beta.32.3 package but it was caused by the remaining angular-cli 1.0.0-28.3 package in my package.json file! After removing it everything works well. (when exploring my app node_modules directory I found @angular/cli, @angular-cli and angular-cli sub directories - this why I found the solution...)

Hope that helps

**Comment by jdschmitt** [comment]
I am seeing this issue. Never install angular cli before now so it's not a collision with older version. I've got "@angular/cli": "^1.0.0-rc.0" in package.json.

> \> ng serve
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/Users/jason/Development/repos/shield/node_modules/@angular/cli/tasks/serve.js:22:63)
    at check_port_1.checkPort.then.port (/Users/jason/Development/repos/shield/node_modules/@angular/cli/commands/serve.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

I can see that a change has been made to account for the 2 file names as pointed out above:

```
...
const path = require("path");
const find_up_1 = require("../utilities/find-up");
exports.CLI_CONFIG_FILE_NAME = '.angular-cli.json';
const CLI_CONFIG_FILE_NAME_ALT = 'angular-cli.json';
function getUserHome() {
...
```

Am I supposed to create that file myself? I can find one here `node_modules/@angular/cli/blueprints/ng/files/angular-cli.json` but I doubt that's the one it's supposed to be looking for.

**Comment by dpalita** [comment]
It also happens if the project is in the home directory (something related to global config file being the same as the project config file)... in my case it was because I used to mount the project in the home of a docker user for building.

**Comment by labs-scnm** [comment]
I got this error on an Docker build. I set the `HOME` env to the same directory as the project root. That's why the `configPath` and `this.globalConfigFilePath()` are the same and returned every time with null. 😒 

```js
const configPath = this.configFilePath(projectPath);
if (!configPath || configPath === this.globalConfigFilePath()) {
  return null;
}
```
https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/models/config.ts#L82

**Comment by simonstewart** [comment]
Seeing the same issue on Win10.  All fine on macOS with same codebase.

**Comment by simonstewart** [comment]
@jdschmitt nice!  Owe you a beer/coffee when in South Africa.

**Comment by jdschmitt** [comment]
On my way! ✈️ 🍻

**Comment by RickStrahl** [comment]
Also running into this on Windows. For me build and serve work fine, but any `ng generate` commands fails with:

```
TypeError: Cannot read property 'apps' of null
```

New project created with ng new.

```
@angular/cli: 1.0.0-rc.0
node: 7.6.0
os: win32 x64
@angular/common: 2.0.0
@angular/compiler: 2.0.0
@angular/core: 2.0.0
@angular/forms: 2.0.0
@angular/http: 2.0.0
@angular/platform-browser: 2.0.0
@angular/platform-browser-dynamic: 2.0.0
@angular/platform-server: 2.0.0
@angular/router: 3.0.0
@angular/upgrade: 2.0.0
@angular/cli: 1.0.0-rc.0
```

**Comment by cgebe** [comment]
same issue for me:
```

2017-03-07T16:30:34.549+01:00 [APP/PROC/WEB/0] [ERR] Cannot read property 'config' of null
2017-03-07T16:30:34.550+01:00 [APP/PROC/WEB/0] [ERR] at check_port_1.checkPort.then.port (/home/vcap/app/node_modules/@angular/cli/commands/serve.js:103:26)
2017-03-07T16:30:34.550+01:00 [APP/PROC/WEB/0] [ERR] at process._tickCallback (internal/process/next_tick.js:103:7)
2017-03-07T16:30:34.550+01:00 [APP/PROC/WEB/0] [ERR] TypeError: Cannot read property 'config' of null
2017-03-07T16:30:34.550+01:00 [APP/PROC/WEB/0] [ERR] at Class.run (/home/vcap/app/node_modules/@angular/cli/tasks/serve.js:22:63)
```

removing the '.' from .angular-cli.json didn't solve the problem.

versions:
```
"node": "7.6.0",
"npm": "4.1.2"
```

**Comment by OneMuppet** [comment]
I had the same issue but solved it by running, (ng init): 
`./node_modules/.bin/ng init`

Then you will get questions regarding which files to overwrite and which to keep. 

After that I could run, (ng build): 
`./node_modules/.bin/ng build`
without any problems.

**Comment by mouna92** [comment]
Thank you so much, it works very good, i had the same probl and i solved it :)

**Comment by filipesilva** [comment]
Heya all, I believe this must be a problem on your cli configs. There must be some kind of outdated entry there, or maybe you're using an old version of the CLI.

Have a look at https://github.com/angular/angular-cli/wiki/stories-rc-update to see how to update your project.

If someone can provide me with a repro that I can follow to see this error, I can look at it further.

**Comment by al-tr** [comment]
Those, who have this problem: try to wipe `node_modules` directory. 
Helped me. Maybe some old and cached by the server dependencies caused this.

**Comment by Ludevik** [comment]
I have same problem when trying to build the app on bitbucket pipelines with docker image.

```
20:35:33.019 [QUIET] [system.out] 
20:35:33.019 [QUIET] [system.out] > frontend@0.0.0 build /opt/atlassian/pipelines/agent/build/frontend
20:35:33.019 [QUIET] [system.out] > ng build
20:35:33.019 [QUIET] [system.out] 
20:35:34.503 [ERROR] [system.err] Cannot read property 'config' of null
20:35:34.504 [ERROR] [system.err] TypeError: Cannot read property 'config' of null
20:35:34.504 [ERROR] [system.err]     at Class.run (/opt/atlassian/pipelines/agent/build/frontend/node_modules/@angular/cli/tasks/build.js:16:56)
20:35:34.504 [ERROR] [system.err]     at Class.run (/opt/atlassian/pipelines/agent/build/frontend/node_modules/@angular/cli/commands/build.js:143:26)
20:35:34.504 [ERROR] [system.err]     at Class.<anonymous> (/opt/atlassian/pipelines/agent/build/frontend/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
20:35:34.504 [ERROR] [system.err]     at process._tickCallback (internal/process/next_tick.js:103:7)
20:35:34.513 [ERROR] [system.err] 
20:35:34.518 [ERROR] [system.err] npm ERR! Linux 4.9.9-coreos-r1
20:35:34.518 [ERROR] [system.err] npm ERR! argv "/opt/atlassian/pipelines/agent/build/frontend/node/node-v7.6.0-linux-x64/bin/node" "/opt/atlassian/pipelines/agent/build/frontend/node_modules/npm/bin/npm-cli.js" "run" "build"
20:35:34.518 [ERROR] [system.err] npm ERR! node v7.6.0
20:35:34.518 [ERROR] [system.err] npm ERR! npm  v4.1.2
20:35:34.518 [ERROR] [system.err] npm ERR! code ELIFECYCLE
20:35:34.518 [ERROR] [system.err] npm ERR! frontend@0.0.0 
```

Works ok on Win 10 machine locally.

**Comment by mezoistvan** [comment]
We had the same problem after updating to an RC version of cli from beta. We were running the project in an ubuntu docker image on a CI. Because .angular-cli.json is considered a hidden file in linux, it was not copied to the image originally. `shopt -s dotglob` before copying solved the issue.

**Comment by Ludevik** [comment]
Thanks @mezoistvan for hint. Now it works on docker image too :)

**Comment by gtzinos** [comment]
Guys you maybe moved your files to another subdirectory.

**Comment by HDaghash** [comment]
guys i found the solution ! :D
in my case i moved the project to another directory 
there is a hidden file called **.angular-cli** 
show the hidden file in the old project and copy this file and past it in the new distention .
this is solved the issue for me .

**Comment by ishandutta2007** [comment]
I have .angular-cli.json in the same directory but still sudo npm run build gives me this error

**Comment by lflores** [comment]
@HDaghash, this worked for me!! thanks. In my case I have created it, with `ng new`, but I don't want another directory, then I have moved the generated code, to my project root, and I forgot mentioned file.

**Comment by justfathi** [comment]
Guys, quickest solution is to do this
$ sudo rm -rf node_modules
$ npm install
$ ng serve

**Comment by pshisbey** [comment]
@HDaghash, Thanks!  copying .angular-cli.json from an old project to the new worked!

**Comment by megamindbrian** [comment]
This is a really bad error message.

**Comment by luigitonno** [comment]
Copying the .angular-cli.json worked (fine)... But it could't be the plan that I have to copying this file when I create a new project...!

**Comment by megamindbrian** [comment]
@luigitonno someone cares about our problems.

**Comment by abhalve** [comment]
We had a similar problem and it was because of the fact that we deleted all the hidden files, guess config file also got deleted and hence the error.

**Comment by peasandpetals** [comment]
ng-init did the job for me :)

**Comment by abhalve** [comment]
init seems the right way

**Comment by gtzinos** [comment]
This issue is closed and is reproduced for 1/2 people who use angular-cli.

**Comment by rekhasinghal08** [comment]
I know how to resolve this issue.
At the time of moving files from one folder to another, there is a hidden file .angular-cli.json.
paste it into new folder.
It works for me.

**Comment by TimeIsGoOn** [comment]
you must have ` .angular-cli.json`
it use my one day

**Comment by brucepc** [comment]
Looks like an usage problem of almost of app(skeleton) generators....
I believe a simple option to set directory to create the app should solve this issue...
something like ```ng new app-name [dir-name]```

**Comment by karocksjoelee** [comment]
If you are using MAC-OS , you can enter `defaults write com.apple.finder AppleShowAllFiles TRUE;\killall Finder` in your terminal for showing the hidden files .

**Comment by yosiasz** [comment]
I already had an existing application I wanted to start using angular-cli in. When trying to implement angular-cli for an existing application, for me,  just doing `npm install -g @angular/cli` and then trying to use the ng commands did not work.
After having install angular-cli I did the following.
In a command line, in windows, I went to my C:\ folder and ran the command
`ng new foo`. After nicely scaffolding my app, I copied the necessary files from this new folder and started moving them to my existing app folder and start sorting out the issues until I got my app running fine using angular-cli. This is the solution that worked for me when trying to implement angular-cli for an already existing application. Hope it helps

**Comment by fmmajd** [comment]
it's happened to me several times. All of them, the problem was I had moved the project to different folders, and I did it through files/finder/explorer, so some hidden files weren't copied. 
try removing the new project, and copying it with the command line. worked awesome for me.

**Comment by artuska** [comment]
Well, did anyone in this thread mentioned it is because `.angular-cli.json` is a hidden file and it is lost when you move your project to another folder? Did anyone or it is just me first? ;)

**Comment by adilsonmenezes** [comment]
SOLUTION: Na pasta do projeto deve conter um arquivo chamado: .angular-cli.json

PS: Caso tenha sido trocado a pasta do projeto para outro local sem ser exibido os arquivos ocultos, este arquivo acaba por não ser copiado junto com o projeto, ocasionando o erro!

**Comment by felixivance** [comment]
i found the solution ! :D
in my case i moved the project to another directory
there is a hidden file called .angular-cli
show the hidden file in the old project and copy this file and past it in the new distention .
this is solved the issue for me .

**Comment by jzapantis** [comment]
These responses helped me identify the solution. I have an older version of angular, and I pulled teammates code and got this error. 

In my project root I had _angular-cli.json - I changed it to .angular-cli.json and it worked!

**Comment by nirmalk31** [comment]
I had same problem with 
@angular/cli: 1.0.0
node: 6.10.3
os: win32 x64

first i tried with command  "ng init" and ng build. It didn't worked. 
In my case I just restarted the "Visual Studio code" it worked.

**Comment by 09abhishek** [comment]
@soodvarun @ardiadrianadri @bougnat12 @jdschmitt @dpalita 

Guys first of all try to check whether the the given file is there or not in the below project specified path.
file name : **.angular-cli.json** 
note : 
1. This **.angular-cli.json** file should must be there.
 It should be .angular-cli.json only,not like (_ angular-cli.json) or anything else.

Check the screenshot :+1: 

![image](https://user-images.githubusercontent.com/16036641/32408598-cd85c544-c1c0-11e7-8212-06b843c4e444.png)


The reason why it is showing error is basically due to above to mentioned points : 

![image](https://user-images.githubusercontent.com/16036641/32408636-7f81fb32-c1c1-11e7-9661-d29f7f7a1288.png)


I hope it may help you guys!!  :+1:  :-)

**Comment by django18** [comment]
It was caused due to missing .angular-cli.json as I created my repo in Linux environment and then was trying to run it in the windows environment by cloning the repo.

**Comment by narendrasinghrathore** [comment]
Got same issue.
Cause of this error:
Copying project files from directory to another, .angular-cli.json not copied to new directory.
Solved:
By copying .angular-cli.json file from old project directory to new one.
Project building successfully.

**Comment by Quentinb** [comment]
Got the same issue today.
    macOS Sierra (10.12.6)
    Node v9.4.0
   ngCli 1.6.5

Pulled a 3 month old NG app from a repo.

Fix:
I created a new App using "ng new foo" and copied the .angular-cli.json file form the new project into the cloned existing one.

**Comment by kryaksy** [comment]
Same issue. I solved with this one.
https://stackoverflow.com/questions/45207900/how-to-generate-angular-cli-json-file-in-angular-cli

**Comment by humanborg** [comment]
Hit the same issue as @narendrasinghrathore @django18, due to missing .angular-cli.json (when copying on macosx finder these .abc files are not visible)

**Comment by gatzkerob** [comment]
My solution was embarrassingly simple: First, make sure you are in the correct directory before trying to use "ng serve".

**Comment by srikanthps** [comment]
My solution is to delete my app folder and recreate using "ng new".

First time I created the app, the download of NPM modules was slow and I switched by networks - later I cancelled the ng new and re-ran it withouth cleaning the dirs.  That caused the issue for me.  So, deleting the app directory and re-creating the app solved my issue.

This was on Windows

**Comment by ahmedkamr** [comment]
in my case
there is a hidden file called .angular-cli.json
just remove . from it name to be  angular-cli.json

**Comment by jonahbron** [comment]
This happened to me because I renamed the project/repo/everything, but forgot to rename the project name in `.angular-cli.json`.  After I fixed it there, it worked just fine.

**Comment by developerndm** [comment]
Happened to me uploading a repo from windows to an online drive.

Made a new app and copped over the missing files.

**Comment by PaloMiklo** [comment]
I had the same error when I tried to run ng test. The solution was easy. I was located in wrong folder. I have to cd one level deeper, where all my files were located.

**Comment by anandbabud1987** [comment]
Same here. I copied to a new directory using cp -r  command where it did not copy .angular-cli.json file which is a hidden file. if your machine is unix/mac then run this command on your source folder to find the .angular-cli.json . after copying to the destination folder it worked like charm.
`ls -ltr A `command should show hidden files.

**Comment by trungtruc1094** [comment]
@anandbabud1987 Your solution worked for me. I really appreciate your way. Thanks a lot, mate

**Comment by montheryounis** [comment]
@HDaghash, Thanks! copying .angular-cli.json from an old project to the new worked perfect

**Comment by Ramaprasath** [comment]
The 'Cannot read property 'config' of null' was came after i did git checkout new branch. 
Please do once the 'npm install'. The error got cleared for me. Now I can do 'ng serve' normally. Thanks !

**Comment by MarkPieszak** [comment]
Note for others, ensure you don't have `angular-cli` installed as a dependency anywhere in your package.json. This can also cause it to become the `ng` inside your `node_modules/.bin` folder, which will cause this error.  You can see by going there and opening the `ng` file, and you'll notice the `angular-cli` project references. 

If that's the case, just remove angular-cli dependency, delete node_modules and run `npm i` again - and you'll reinstall everything and the new symlinks will be created pointing to the correct `@angular/cli` "ng". Hope that helps anyone else in this situation!
