### ISSUE TITLE
app should not reload on global css/etc style change when using the --extract-css flag 

### ISSUE THREAD

**Issue by Radu-Dunarentu** [angular/angular-cli#4737]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10. 

### Versions.
@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

### Repro steps.
> ng new test-app --styles=scss
> ng serve --extract-css
>modify global styles
result: app reloads every file.
expected result: app should inject the css files and should not reload.

### The log given by the failure.
Time: 796ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 153 kB {4} [initial]
chunk    {1} main.bundle.js, main.bundle.map (main) 7.2 kB {3} [initial]
chunk    {2} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 69 bytes {4} [initial]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 3.09 MB [initial]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]
webpack: Compiled successfully.

**Comment by filipesilva** [comment]
I think you're thinking of the `--hmr` flag instead. Without it, everything triggers a live reload.
