### ISSUE TITLE
Add information about ng new options in README page. Sync with pdf

### ISSUE THREAD

**Issue by gotofritz** [angular/angular-cli#4740]
Hi. The documentation seems to be all over the shop

* The options --style=sass and --routing for `ng new xxx` are not listed in the documentation
* The documentation in the pdf at  [cli.angular.io/reference.pdf](https://cli.angular.io/reference.pdf) (linked to with a big fat button on the website) and the README file are different.

I understand this is still beta, but I'm sure --style=sass was there before and it's now gone, although it still seems to be functional. Is it on the way out or something? Some clarity would be good. Thanks

**Comment by DmitryEfimenko** [comment]
It looks like the [latest commit](https://github.com/angular/angular-cli/commit/49177151c8ea0d3618420b4f176f26f53477abf6) to README moves this info to wiki.
That's perfectly fine. Just need to let people know to look there.

As a side note, wiki does not have info about command `new`

**Comment by sumitarora** [comment]
Should be fixed with this: https://github.com/angular/angular-cli/pull/4960

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/4960
