### ISSUE TITLE
A question about chunk sourcemaps

### ISSUE THREAD

**Issue by andershagebakken** [angular/angular-cli#4741]
Hi. I was just wondering why the sourcemap file is named as follows: 0.93f2....bundle.map. but the js chunks are named as such: 0.93f2....chunk.js ? The reason I am wondering is that I am using sentry.io, and I upload the sourcemaps I get when building with --prod --aot --sourcemap to sentry.io, instead of making them public. Sentry.io can not detect the sourcemap reference because the names does not match, as they do with main, styles, inline and vendor. Thanks in advance, and the great work you do with this tool. 

@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: darwin x64

**Comment by filipesilva** [comment]
That's a bug actually, good catch!
