### ISSUE TITLE
how to set the root path for production

### ISSUE THREAD

**Issue by yaronmil** [angular/angular-cli#4743]
on my prod server the app is hosted under "some-folder".

i would like that the build generated index.html will refer src scripts and styles to "some-folder"

```
<script type="text/javascript" src="some-folder/inline.bundle.js"></script>
<script type="text/javascript" src="some-folde/vendor.bundle.js"></script>
<script type="text/javascript" src="some-folder/main.bundle.js"></script>
```

**Comment by Meligy** [comment]
Try

```
ng build -prod --base-href="/some-folder/"
```

**Comment by yaronmil** [comment]
thanks,

as .netGuro maybe you know how to use angular cli with vs2015 ? (question is not relation to this thread)

**Comment by filipesilva** [comment]
Closing as answered. Thanks @Meligy !

**Comment by shakram02** [comment]
tiny fix: `--prod` instead of `-prod`
```
ng build --prod --base-href="/some-folder/"
```
