### ISSUE TITLE
ng build --prod fails

### ISSUE THREAD

**Issue by IlyaSurmay** [angular/angular-cli#4750]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux mint 17.3

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: linux x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
@ngtools/webpack: 1.2.9
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
App was created with CLI, I updated it from beta.28 to beta.31

### The log given by the failure.
> Normally this include a stack trace and some more information.
```
Hash: 2a99f13b5b62365e1c82                                                               
Time: 22299ms
chunk    {0} scripts.eba1fd04cb853331827e.bundle.js (scripts) 1.59 MB {4} [initial] [rendered]
chunk    {1} styles.7fa2a0ee5b161732eff6.bundle.css (styles) 652 bytes {4} [initial] [rendered]
chunk    {2} main.83c4de0f806812b7af3c.bundle.js (main) 1.47 kB {3} [initial] [rendered]
chunk    {3} vendor.3c9407a92164ae98a7fe.bundle.js (vendor) 1.06 MB [initial] [rendered]
chunk    {4} inline.c4d016c6bd1a57a97f49.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in this._input.charCodeAt is not a function

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/vs/Work/GoFactTables/GoFactFrontend/src'
 @ ./src/main.ts 5:0-74
 @ multi ./src/main.ts
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mjamin** [comment]
Same issue for me (also updated to 1.0.0-beta.31), except the error is different:

    ERROR in Can't resolve all parameters for provideLocationStrategy in C:/path/to/project/node_modules/@angular/router/src/router_module.d.ts: ([object Object], ?, [object Object]).

**Comment by IlyaSurmay** [comment]
Error doesn't appear when using command with aot turned off (`--aot=false`). Is there any way to check what goes wrong with aot?

**Comment by IlyaSurmay** [comment]
Closing issue. The problem was in application itself, there was a component with template loaded as `require(...)` . Build went ok when I replaced this template with inline one.
