### ISSUE TITLE
File names and directory created with a custom prefix stills ay app

### ISSUE THREAD

**Issue by the-destro** [angular/angular-cli#4755]
> macOS Sierrra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-beta.31
node: 7.5.0
os: darwin x64

### Repro steps.
`ng new --routing --style=scss --p qq foo`
 Looking through the code it looks like the directory and the files themselves are hardcoded to app and not templetized.

**Comment by clydin** [comment]
This is intentional.  Please see the style guide for details: https://angular.io/styleguide

**Comment by filipesilva** [comment]
Closing as answered. Thanks @clydin!
