### ISSUE TITLE
@ngtools/webpack: Error Cannot find module 'engine.io-client' 

### ISSUE THREAD

**Issue by snics** [angular/angular-cli#4758]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
MacOS Sierra

### Versions.
   - angular-cli: 1.0.0-beta.25.5
   - node: 6.9.1
   - os: darwin x64
   - @angular/common: 2.4.4
   - @angular/compiler: 2.4.4
   - @angular/core: 2.4.4
   - @angular/forms: 2.4.4
   - @angular/http: 2.4.4
   - @angular/platform-browser: 2.4.4
   - @angular/platform-browser-dynamic: 2.4.4
   - @angular/router: 3.4.4
   - @angular/compiler-cli: 2.4.4

### Repro steps.
1. I created an Angular 2 project with angular-cli
   - angular-cli: 1.0.0-beta.25.5
   - node: 6.9.1
   - os: darwin x64
   - @angular/common: 2.4.4
   - @angular/compiler: 2.4.4
   - @angular/core: 2.4.4
   - @angular/forms: 2.4.4
   - @angular/http: 2.4.4
   - @angular/platform-browser: 2.4.4
   - @angular/platform-browser-dynamic: 2.4.4
   - @angular/router: 3.4.4
   - @angular/compiler-cli: 2.4.4
2. Install engine.io-client module with npm
3.Import engine.io-client in angular component (```import * as eio from 'engine.io-client';```)
4. Add engine.io-client.js file to Scripts area in angular-cli.json
 ```
"scripts": [
        "../node_modules/engine.io-client/engine.io.js"
      ]
```
4. I start the develop server  with ```ng serve``` and then get a error message
```
ERROR in ./src/app/campaign/campaign.component.ts
Module build failed: Error: /Users/Max/Development/bmt/bmt-ui/angular/src/app/campaign/campaign.component.ts (6,22): Cannot find module 'engine.io-client'.)
    at _checkDiagnostics (/Users/Max/Development/bmt/bmt-ui/angular/node_modules/@ngtools/webpack/src/loader.js:145:15)
    at /Users/Max/Development/bmt/bmt-ui/angular/node_modules/@ngtools/webpack/src/loader.js:173:17
 @ ./src/app/campaign/campaign.module.ts 12:0-57
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main
```

**Comment by jwuliger** [comment]
I can report having the same issue. However my component that shows as erroring out is `app.component.ts`

I am able to easily recreate the problem by doing a fresh global CLI install, and then creating a new NG2 or  NG4 app. `ng new` > `ng serve `

I am also on Windows 10. So it seems like a cross OS issue.

**Comment by filipesilva** [comment]
If I'm reading this correctly, you're missing the typings for the library. See https://github.com/angular/angular-cli/wiki/stories-third-party-lib for more info.
