### ISSUE TITLE
Help documentation for 'ng new' doesn't mention name parameter

### ISSUE THREAD

**Issue by andrewseguin** [angular/angular-cli#4760]
Running `ng help new` does not say that you need any parameter for a name. Running `ng new` does complain however.

### OS?

Linux Ubuntu

### Versions.

@angular/cli: 1.0.0-beta.30
node: 6.9.0
os: linux x64

### Repro steps.

Run `ng help new`

### The log given by the failure.

N/A

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bvaissade** [comment]
Same error in `@angular/cli: 1.0.0-beta.32.3` !

`ng new` send error : 
`The "ng new" command requires a name argument to be specified. For more details, use "ng help".`

**Comment by sumitarora** [comment]
Merged in master: https://github.com/angular/angular-cli/commit/39aef95fd9539cf135cde08345333119219bed95
