### ISSUE TITLE
[beta.31] ng serve error on css-loader, postcss-loader, sass-loader

### ISSUE THREAD

**Issue by Harry-Jeong** [angular/angular-cli#4763]
### OS?
Windows 7

### Versions.

@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

### Repro steps.
First, App created using CLI(angular-cli 1.0.0-beta.24). 
When I cloned a git project. and npm install, ng serve. but error was coming
If I comment on the error part, it can be executed. but css(scss, styles,css, ..) does not seem to apply.

angular-cli.json

>{
  "project": {
    "version": "1.0.0-beta.24",
    "name": "bixby-admin"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "bap",
      "mobile": false,
      "styles": [
        "styles.css",
        "bap-custom.scss",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css"
      ],
      "scripts": [
        "../node_modules/core-js/client/shim.min.js"
      ],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "dev1": "environments/environment.dev1.ts",
        "dev2": "environments/environment.dev2.ts",
        "stg": "environments/environment.stg.ts",
        "prd": "environments/environment.prd.ts"
      }
    }
  ],
  "addons": [
  ],
  "packages": [
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}

### The log given by the failure.

Normally this include a stack trace and some more information.
D:\vscode\portal\front>ng serve
** NG Live Development Server is running on http://localhost:4200. **
Hash: 9bb57085a40f1e3fcce4
Time: 16998ms
chunk    {0} main.bundle.js, main.bundle.map (main) 410 kB {3} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 134 kB {4} [initial] [rendered]
chunk    {2} scripts.bundle.js, scripts.bundle.map (scripts) 80.9 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 5.4 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

`ERROR in ./~/css-loader?{"sourceMap":false}!./~/postcss-loader!./~/sass-loader!./src/bap-custom.scss
Module build failed:
@include md-core();
        ^
      No mixin named md-core
Backtrace:
        stdin:3
      in D:\vscode\portal\front\src\bap-custom.scss (line 3, column 10)
 @ ./src/bap-custom.scss 4:14-185
 @ multi ./src/styles.css ./src/bap-custom.scss ./~/bootstrap/dist/css/bootstrap.min.css
webpack: Failed to compile.`

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
`md-core` was part of `@angular/material2`.
Please see here for details: https://github.com/angular/material2/pull/2790
Here is the changelog as well: https://github.com/angular/material2/blob/master/CHANGELOG.md

**Comment by filipesilva** [comment]
You're trying to use a mixin that does not exist: `No mixin named md-core`.
