### ISSUE TITLE
ng update comand not working

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#4765]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
MAC

### Versions.
```
@angular/cli: 1.0.0-beta.31
node: 6.9.0
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
```

I just updated form #30 to # 31 and after standard procedure of uninstalling and installing new NPMs I run ng update that usually works but now after first questions and aswer NO to skip it exits back to terminal 
```

installing ng2
? Overwrite .editorconfig? (yndH) 

```

Is there any update task available for this version or should I create new empty project and update files manually?

Thank you, 
frank

**Comment by prathamesh7pute** [comment]
Noticed same issue on windows also.... 
For now I am currently creating a new project and manually overwrite the files. 

Also it will be good when we overwrite the files like package.json it will update the dependencies version only related to cli and not remove the independently installed dependencies like bootstrap

**Comment by fkolar** [comment]
I see. so it must be something in new version. I just created new project and used merge tool and did little manual work.

**Comment by grizzm0** [comment]
Dupe of #4653.
ng update was broken in beta 31 and has been removed from beta 32 in #4628

See changelog for more info: https://github.com/angular/angular-cli/blob/3ad2856b27889a50a742c9dca9554a190c8509bf/CHANGELOG.md

**Comment by fkolar** [comment]
Cool. I will start again. I just hope in the next few minutes there will not be version 33 ;-)

**Comment by grizzm0** [comment]
Next release will be rc0.

**Comment by fkolar** [comment]
You might want to also update documentation as in README.md there is still 👍 
```
rm -rf node_modules dist # use rmdir on Windows
npm install --save-dev @angular/cli@latest
npm install
ng update
```

**Comment by itsnotvalid** [comment]
So the update doesn't work, what can we do to update? We now need to resolve to what @prathamesh7pute does before there was such command...

**Comment by grizzm0** [comment]
To update you need to follow the breaking changes instructions in CHANGELOG.md
