### ISSUE TITLE
cannot ng build, get TypeError: Path must be a string.

### ISSUE THREAD

**Issue by sjc01234** [angular/angular-cli#4766]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
macOS Sierra 10.12.2
(also happens on a windows server 2012 R2)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.16
node: 6.9.4
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
It was created with the CLI, however I am new enough to angular and the CLI that I do not quite know how to answer this question...  I was not the one who started the project, but I want to understand how to fix the problem myself.

### The log given by the failure.
> Normally this include a stack trace and some more information.
Path must be a string. Received undefined
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Object.getWebpackCommonConfig (/<appPath>/node_modules/angular-cli/models/webpack-build-common.js:109:80)
    at new NgCliWebpackConfig (/<appPath>/node_modules/angular-cli/models/webpack-config.js:15:29)
    at Class.run (/<appPath>/node_modules/angular-cli/tasks/build-webpack.js:17:22)
    at Class.run (/<appPath>/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/<appPath>/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/<appPath>/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/<appPath>/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/<appPath>/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/<appPath>/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Mention any other details that might be useful.
I can't tell _what_ is the thing that might be the problem... so I would like to understand the steps to take to diagnose the problem.

my app's project.json:
{
  "name": "my-app",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve --env=source",
    "build": "ng build",
    "build-replace": "ng build --env=replace",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "2.2.4",
    "@angular/core": "2.0.0",
    "@angular/flex-layout": "2.0.0-beta.3",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/material": "2.0.0-alpha.10",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "angular2-select": "1.0.0-alpha.12",
    "core-js": "2.4.1",
    "hammerjs": "2.0.8",
    "jsrsasign": "6.1.1",
    "jwt-decode": "2.1.0",
    "lodash": "4.16.4",
    "material-design-lite": "1.2.1",
    "moment": "2.15.1",
    "ng2-pagination": "0.5.1",
    "ng2-translate": "4.0.0",
    "normalize.css": "4.2.0",
    "primeng": "1.0.0-rc.6",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "1.1.1",
    "xmljson": "0.2.0",
    "zone.js": "0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "2.2.30",
    "@types/lodash": "4.14.37",
    "angular-cli": "1.0.0-beta.16",
    "codelyzer": "0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.0.2",
    "karma-remap-istanbul": "0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rolandjitsu** [comment]
I got the same issue and I noticed there was a new release. Check the changelog, after I did the necessary updates I got rid of this issue.

**Comment by galta** [comment]
Having the same problem.... :-1: 
Any Solution?

**Comment by galta** [comment]
Found it: 

Well, 
It looks like it is a wrong configuragion file for the angular-cli version you are using. 
In angular-cli.json file, try to change the following: 
from: 
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }

to: 
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }

**Comment by filipesilva** [comment]
Closing as answered.

**Comment by avkr1234** [comment]
still same error i am getting after changing angula-cli.json file , Any Solution?
