### ISSUE TITLE
Created Code fails linter

### ISSUE THREAD

**Issue by zbindenren** [angular/angular-cli#477]
I am filing a bug.
-------------------------------------------------------------
1. OS. Linux (Arch).
2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 

        node --version
        v5.10.1
        npm --version
        3.8.6
        npm info angular-cli
        0.0.33

3.  Procedure

        ng new ngtest
        cd ngtest
        ng lint 

        src/client/system-config.ts[23, 3]: file should end with a newline
        src/client/system-config.ts[6, 30]: shadowed variable: 'barrels'
        src/client/typings.d.ts[3, 34]: file should end with a newline

**Comment by filipesilva** [comment]
Thanks for the report, @deebloo got it fixed in a PR before I managed to :D

**Comment by deebloo** [comment]
☺️
