### ISSUE TITLE
Update to last version / ng command not found

### ISSUE THREAD

**Issue by kamalkech** [angular/angular-cli#4777]
### OS
> Windows 10

### Versions.
node : v6.9.5
npm : 3.10.10

### Repro steps.
i try to update version of angular-cli with this commandes : 
npm uninstall -g angular-cli @angular/cli
npm cache clean
npm install -g @angular/cli@latest

And i reinstall again node js but get always same error : 
ng help => ng command not found

**Comment by Equinox** [comment]
Do any other ng commands work?

If not, maybe it hasn't been added to your PATH for whatever reason, [check that and add it if not](http://stackoverflow.com/a/28339816/2221808).

**Comment by mjenny** [comment]
There seem to be something broken.
When installing angular-cli everything is working as expected (PATH variable contains npm path).
However, when installing @angular/cli@latest ng is not found. I guess this has to do with the renaming.

**Comment by kamalkech** [comment]
Try to change PATH variable (variable environnement), if use cmder change it

**Comment by prashantkurlekar** [comment]
this issue is happening when you install/update node using brew. 
solution: delete ng from usr/local/bin/
and 
```
npm install -g @angular/cli@latest
```
