### ISSUE TITLE
Project version in .angular-cli.json

### ISSUE THREAD

**Issue by dzonatan** [angular/angular-cli#4784]
Is there any need of having project **version** property in `.angular-cli.json`?
```json
"project": {
  "version": "1.0.0-beta.32.3", 
  "name": "my-project-name"
}
```

Sometimes it might be misleading (especially for ones who are not familiar with angular-cli yet) if you're not manually keeping it in sync with real one used in `package.json`.
After `update/init` command deprecation it's so easy to miss to update it... 😞

**Comment by dzonatan** [comment]
shit, accidentally clicked `close` button but as I see @Meligy and @filipesilva noticed it anyway. :D You're fabulous! 🍻

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/4795 💃
