### ISSUE TITLE
ng build -prod nog generating .gz files anymore

### ISSUE THREAD

**Issue by oji** [angular/angular-cli#4790]
### OS?
OSX Sierra

### Versions.
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.30]
node: 7.5.0
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.7

### Repro steps.
1. I had ng 1.0.0-beta.31, and when running `ng build -prod --aot=false`, I got .gz files in my output folder.
2. I updated today to ng 1.0.0-beta.32.3, and when I run the same command, I don't get any .gz files. 

### The log given by the failure.
No log, as there was no failure issued.

### Mention any other details that might be useful.
In case now there's a threshold for generating .gz files, below are the size of the files that I get: 

```bash
$ du -h *.js
112K	0.82156de2633f6a32bd6b.chunk.js
108K	1.d9694e3d561d7e5b0531.chunk.js
 72K	10.1af2cc80a335e28fa545.chunk.js
 76K	11.8f5c1733da08f579f11a.chunk.js
4.0K	12.8e35860729aaa877da5d.chunk.js
1.1M	16.c580b8fa4c3869dc7a80.chunk.js
120K	17.f716694aa2dca5138863.chunk.js
 68K	18.c3b6e3b0c18cccb41229.chunk.js
4.0K	19.847c1a10f29f70e8ca93.chunk.js
 96K	2.b2a9491baa954330f7f3.chunk.js
 96K	3.4ba7465dae5552d96a59.chunk.js
100K	4.8197559d380195569df0.chunk.js
 72K	5.996e7894be996816241f.chunk.js
 68K	6.88a302ef8a1148f07881.chunk.js
 88K	7.d3bac4c875c570ce929b.chunk.js
 72K	8.55f8bce91743bc741781.chunk.js
 68K	9.40d4429934db866332ae.chunk.js
4.0K	inline.7152345370f5ac6e8bb7.bundle.js
120K	main.d6d974e691a9bc510821.bundle.js
 88K	polyfills.44d6f0f42183a939b0ee.bundle.js
1.7M	vendor.6eee5e13d93f9ecf6f20.bundle.js
``` 

Thanks a lot!

**Comment by RicardoVaranda** [comment]
Check out the changelog:
https://github.com/angular/angular-cli/blob/master/CHANGELOG.md

Recent changes on rc32:
@angular/cli: compressed output (.gz) is no longer generated on production builds.
