### ISSUE TITLE
Where do I go to read release notes for different versions of angular-cli?

### ISSUE THREAD

**Issue by brookhutchinson** [angular/angular-cli#4793]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.7

### Question
Where do I go to read release notes for different versions of angular-cli?

**Comment by filipesilva** [comment]
You can find them in the changelog: https://github.com/angular/angular-cli/blob/master/CHANGELOG.md
