### ISSUE TITLE
Adding/Altering styles in SCSS/CSS from component.scss/css doesn't work

### ISSUE THREAD

**Issue by maxpfandl** [angular/angular-cli#4797]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Win10 x64

### Versions.
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.28.3]
node: 7.4.0
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.7

### Repro steps.
Create a new project, add a component (my-component.ts), add bootstrap to the project. Add styles and JS from bootstrap to .angular-cli.json

`"styles": [
            "../node_modules/bootstrap/dist/css/bootstrap.css",
            "styles.scss"
        ],
        "scripts": [
            "../node_modules/jquery/dist/jquery.js",
            "../node_modules/bootstrap/dist/js/bootstrap.js",
        ],`

Use a button from bootstrap in the newly added component.
`<button type="button" class="btn btn-primary btn-xs">TEST</button>`

Add some style to the class btn or btn-primary to the in the component referenced css/scss (my-component.scss)
`.btn{
        text-decoration: line-through;
}`

This style from the component.scss will not get applied.

If I now move this class to the central style.css/scss it will get applied.
### The log given by the failure.
There is no log or any output pointing to the issue

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by alfupe** [comment]
If you debug the css rule in the browser dev tools: is you css rule overriden by another one with more specificity? If yes, a few things I would try are:
* make the component style as !important
* overload the `.btn`selector with parent selecto to increase its specificity, for instance `#foo .bar .btn { ...`
* set the encapsulation to none in the @Component metadata (`encapsulation: ViewEncapsulation.None`) https://angular.io/docs/ts/latest/guide/component-styles.html#!#view-encapsulation

**Comment by maxpfandl** [comment]
thanks @alfupe ! The viewencapsulation.none did the trick! I forgot to mention that I already tried the !important marker and the more specific css selector.

**Comment by alfupe** [comment]
@maxpfandl I'm glad to read that :-)
