### ISSUE TITLE
starting new project and running ng-serve   - just see  'loading' in browser

### ISSUE THREAD

**Issue by bkbonner** [angular/angular-cli#48]
Running node v4.2.1

Installed bower, angular-cli and typescript

```javascript
ng new greetings-ac
ng serve
```

version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 2610ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
DiffingTSCompiler                             | 2495ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
DiffingTSCompiler (1)                         | 2495ms      

After opening link at http://localhost:4200

i just see
```
'Loading...'
```
in the browser.   I see these error msgs in the console:

angular2.dev.js:168 Uncaught RangeError: Maximum call stack size exceededZone.addEventListener @ angular2.dev.js:168obj.addEventListener @ angular2.dev.js:1092Zone.addEventListener @ angular2.dev.js:168obj.addEventListener @ angular2.dev.js:1092Zone.addEventListener @ 
etc.

**Comment by bkbonner** [comment]
Ok, I believe it's because I'm not using an es6 browser and I have to have a transpiler handle it with traceur.    I watched the angular-connect keynote and was following along until I hit this roadblock.

**Comment by IgorMinar** [comment]
What browser are you using?

**Comment by bkbonner** [comment]
dang.    I thought I was on Chrome 46 on my linux laptop, but it turns out I'm only at chrome 42.  I'm upgrading it and I'll try it again.   Should it work in 46?

**Comment by bkbonner** [comment]
I updated to 46.0.2490.80 (64-bit).  I still only see the loading...

**Comment by bkbonner** [comment]
I enabled harmony via chrome://flags/#enable-javascript-harmony, still no luck.   'Loading...'

**Comment by bkbonner** [comment]
looks like Arrow functions will be in Chrome 47.  I might try Canary on the Mac to see if that works.

**Comment by bkbonner** [comment]
I installed Canary on the Mac  (48.0.2544.0 64-bit) with the same results.  :(

**Comment by alexpaluzzi** [comment]
TypeScript is transpiling to ES5. You don't need ES2015 support in the browser. That is unrelated to the issue you are having.

**Comment by bkbonner** [comment]
Ok.   I ended up creating a new project on my mac with V4.2.1 and I used Chrome 46 (not canary) and it seemed to work fine.  I also tested it on linux from scratch and it worked fine there, too.

I don't know what changed.    Thank you.

**Comment by alexpaluzzi** [comment]
Glad to hear it. But you don't need to use Canary. You can use any newer browser, just FYI.

**Comment by bkbonner** [comment]
So I did a diff against my non-working version and working version and the difference was in the system-config section:

Working:

```
    System.config({
      packages: {
        app: {
          format: 'register',
          defaultExtension: 'js'
        }
      }
    });
```

Not working:
```
 System.config({
        map: {
    traceur: 'node_modules/traceur/bin/traceur.js'
  }
  });
```
