### ISSUE TITLE
angular-cli not installing globally 

### ISSUE THREAD

**Issue by pinalbhatt** [angular/angular-cli#480]
angular-cli not installing globally. 
Trying to install angular-cli with following command sudo npm i angular-cli -g  and getting following error.

Note that it installs fine without -g parameter.

```
NYMAC: aaa USER1$ sudo npm i angular - cli - g
npm WARN deprecated lodash - node@ 2.4.1: This package has been discontinued in favor of lodash@ ^ 4.0.0.
npm WARN deprecated graceful - fs@ 3.0.8: graceful - fs version 3 and before will fail on newer node releases.Please update to graceful - fs@ ^ 4.0.0 as soon as possible. / Users / USER1 / .npm - global / bin / ng - > /Users/USER
1 / .npm - global / lib / node_modules / angular - cli / bin / ng

    > broccoli@ 1.0.0 - beta.6 postinstall / Users / USER1 / .npm - global / lib / node_modules / angular - cli / node_modules / broccoli > multidep test / multidep.json

broccoli - plugin 1.0.0: Installing
npm WARN locking Error: EACCES: permission denied, open '/Users/USER1/.npm/_locks/broccoli-plugin-b76c834f71e14cb0.lock'
npm WARN locking at Error(native)
npm WARN locking / Users / USER1 / .npm / _locks / broccoli - plugin - b76c834f71e14cb0.lock failed {
    [Error: EACCES: permission denied, open '/Users/USER1/.npm/_locks/broccoli-plugin-b76c834f71e14cb0.lock']
    npm WARN locking errno: -13,
        npm WARN locking code: 'EACCES',
        npm WARN locking syscall: 'open',
        npm WARN locking path: '/Users/USER1/.npm/_locks/broccoli-plugin-b76c834f71e14cb0.lock'
}
npm ERR!Darwin 15.4.0
npm ERR!argv "/usr/local/bin/node"
"/Users/USER1/.npm-global/lib/node_modules/angular-cli/node_modules/.bin/npm"
"install"
"broccoli-plugin@1.0.0"
npm ERR!node v4.4.3
npm ERR!npm v2.14.21

npm ERR!Attempt to unlock / Users / USER1 / .npm - global / lib / node_modules / broccoli - plugin, which hasn 't been locked
npm ERR!
    npm ERR!If you need help, you may report this error at:
    npm ERR! < https: //github.com/npm/npm/issues>

    npm ERR!Please include the following file with any support request:
    npm ERR!/Users/USER
1 / .npm - global / lib / node_modules / angular - cli / node_modules / broccoli / test / multidep / broccoli - plugin - 1.0.0 / npm - debug.log
Error: npm exited with exit code 1, signal null
at ChildProcess. < anonymous > (/Users/USER
    1 / .npm - global / lib / node_modules / angular - cli / node_modules / multidep / index.js: 90: 28)
at emitTwo(events.js: 87: 13)
at ChildProcess.emit(events.js: 172: 7)
at Process.ChildProcess._handle.onexit(internal / child_process.js: 200: 12) / Users / USER1 / .npm - global / lib└──(empty)

npm ERR!Darwin 15.4.0
npm ERR!argv "/usr/local/bin/node"
"/Users/USER1/.npm-global/bin/npm"
"i"
"angular-cli"
"-g"
npm ERR!node v4.4.3
npm ERR!npm v3.8.6
npm ERR!code ELIFECYCLE

npm ERR!broccoli@ 1.0.0 - beta.6 postinstall: `multidep test/multidep.json`
npm ERR!Exit status 1
npm ERR!
    npm ERR!Failed at the broccoli@ 1.0.0 - beta.6 postinstall script 'multidep test/multidep.json'.
npm ERR!Make sure you have the latest version of node.js and npm installed.
npm ERR!If you do,
    this is most likely a problem with the broccoli package,
    npm ERR!not with npm itself.
npm ERR!Tell the author that this fails on your system:
    npm ERR!multidep test / multidep.json
npm ERR!You can get information on how to open an issue
for this project with:
    npm ERR!npm bugs broccoli
npm ERR!Or
if that isn 't available, you can get their info via:
npm ERR!npm owner ls broccoli
npm ERR!There is likely additional logging output above.

npm ERR!Please include the following file with any support request:
    npm ERR!/Users/USER
1 / Projects / aaa / npm - debug.log
npm ERR!code 1
```

**Comment by hansl** [comment]
Are you running 2 npm at the same time? If not, try clearing your lock files and reinstall.

**Comment by pinalbhatt** [comment]
@hansl  not sure how can we have 2 npms. If at all any pointer how can i clear it? 
currently my /Users/USER1/.npm/_locks/ folder is empty

**Comment by pinalbhatt** [comment]
Tried uninstalling node and npm and reinstalling all again. now i get following error:

: ~USER1$ sudo npm i - g angular - cli

    > broccoli@ 1.0.0 - beta.6 postinstall / Users / USER1 / .npm - global / lib / node_modules / angular - cli / node_modules / broccoli > multidep test / multidep.json

broccoli - plugin 1.0.0: Installing
npm ERR!Darwin 15.4.0
npm ERR!argv "/usr/local/bin/node"
"/usr/local/bin/npm"
"install"
"broccoli-plugin@1.0.0"
npm ERR!node v4.4.3
npm ERR!npm v2.14.12
npm ERR!path / Users / USER1 / .npm / graceful - fs / 4.1.3 / package / package.json.5 f23f5b2bfb52b459d2970e8b539886a
npm ERR!code ENOENT
npm ERR!errno - 2
npm ERR!syscall scandir

npm ERR!enoent ENOENT: no such file or directory, scandir '/Users/USER1/.npm/graceful-fs/4.1.3/package/package.json.5f23f5b2bfb52b459d2970e8b539886a'
npm ERR!enoent This is most likely not a problem with npm itself
npm ERR!enoent and is related to npm not being able to find a file.
npm ERR!enoent

npm ERR!Please include the following file with any support request:
    npm ERR!/Users/USER
1 / .npm - global / lib / node_modules / angular - cli / node_modules / broccoli / test / multidep / broccoli - plugin - 1.0.0 / npm - debug.log
Error: npm exited with exit code 254, signal null
at ChildProcess. < anonymous > (/Users/USER
    1 / .npm - global / lib / node_modules / angular - cli / node_modules / multidep / index.js: 90: 28)
at emitTwo(events.js: 87: 13)
at ChildProcess.emit(events.js: 172: 7)
at Process.ChildProcess._handle.onexit(internal / child_process.js: 200: 12)
npm WARN deprecated lodash - node@ 2.4.1: This package has been discontinued in favor of lodash@ ^ 4.0.0.
npm WARN deprecated graceful - fs@ 3.0.8: graceful - fs version 3 and before will fail on newer node releases.Please update to graceful - fs@ ^ 4.0.0 as soon as possible.
npm ERR!Darwin 15.4.0
npm ERR!argv "/usr/local/bin/node"
"/usr/local/bin/npm"
"i"
"-g"
"angular-cli"
npm ERR!node v4.4.3
npm ERR!npm v2.14.12
npm ERR!code ELIFECYCLE

npm ERR!broccoli@ 1.0.0 - beta.6 postinstall: `multidep test/multidep.json`
npm ERR!Exit status 1
npm ERR!
    npm ERR!Failed at the broccoli@ 1.0.0 - beta.6 postinstall script 'multidep test/multidep.json'.
npm ERR!This is most likely a problem with the broccoli package,
    npm ERR!not with npm itself.
npm ERR!Tell the author that this fails on your system:
    npm ERR!multidep test / multidep.json
npm ERR!You can get their info via:
    npm ERR!npm owner ls broccoli
npm ERR!There is likely additional logging output above.

npm ERR!Please include the following file with any support request:
    npm ERR!/Users/USER
1 / npm - debug.log

**Comment by hansl** [comment]
You shouldn't `sudo npm install -i`, `npm install` should be more than enough.

That might be your problem actually. Using a mix of sudo and non-sudo installations could lead to files that normal users don't have access to.

See if this: https://docs.npmjs.com/getting-started/fixing-npm-permissions solves your problem. It looks like the symptoms are the same.

**Comment by pinalbhatt** [comment]
Executed 
` sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`

and then tried 
` npm i angular - cli - g`

and finally angular-cli got installed.

Thanks @hansl
