### ISSUE TITLE
dry run of generating a component should display updated module, but does not

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#4801]
### OS?
Mac OSX

### Versions.
@angular/cli: 1.0.0-beta.31
node: 6.9.1
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

### Repro steps.
`ng g c dashboard/foobar --dry-run`

produces 

```
installing component
You specified the dry-run flag, so no changes will be written.
  create src/app/dashboard/foo/foo.component.css
  create src/app/dashboard/foo/foo.component.html
  create src/app/dashboard/foo/foo.component.spec.ts
  create src/app/dashboard/foo/foo.component.ts
```

and it should have also logged 

```
  update src/app/dashboard/dashboard.module.ts
```

as discussed with  @filipesilva

**Comment by filipesilva** [comment]
@Brocco can you have a look?
