### ISSUE TITLE
ng g --help advises us incorrectly

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#4802]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
when running a command incorrectly we sometimes get a help message advising us how to get help. This is good. However it is not always working.

For example, I make this mistake (--dryrun should be --dry-run)

```
$ ng g c dashboard/foobar --dryrun
The option '--dryrun' is not registered with the generate command. Run `ng generate --help` for a list of supported options.
```

ok, so i run `ng g —help` and my output says ... 

> The `ng generate --help` command requires a name to be specified.

so  i run `$ ng g c —help` and there is no output, but it seems there should be

cc @filipesilva

**Comment by filipesilva** [comment]
@sumitarora could this be related with your recent fix to `ng help`?

**Comment by sumitarora** [comment]
@filipesilva looking into it
