### ISSUE TITLE
make testing functionality optional

### ISSUE THREAD

**Issue by jahtalab** [angular/angular-cli#4811]
Provide a way to exclude the test functionality and subsequent spec files when generating a new project

**Comment by clydin** [comment]
You should be able to use the '--skip-tests' option on 'ng new'.

**Comment by grizzm0** [comment]
You can also disable spec generation from your angular-cli.json.

See: https://github.com/angular/angular-cli/blob/d2bef98bb908cb7d4b34be389fae7eeb65de67a3/packages/%40angular/cli/lib/config/schema.json#L281-L400

**Comment by jahtalab** [comment]
Thanks @clydin and @grizzm0 👍

**Comment by shramee** [comment]
Hi @clydin,
Since which version is `--skip-tests` supported..?
Also would be nice to have it in docs 🙂

**Comment by benjamincharity** [comment]
The [Changelog](https://github.com/angular/angular-cli/blob/master/CHANGELOG.md) shows it was added in `beta.25`.
