### ISSUE TITLE
error while deploying to github-pages

### ISSUE THREAD

**Issue by gkucmierz** [angular/angular-cli#4812]
I don`t want to repeat myself.
Here is the problem with github-pages:deploy

http://stackoverflow.com/questions/42306569/angular2-ngrx-error-while-deploying-to-github-pages

What can cause this issue?
How to solve it?

**Comment by Equinox** [comment]
That command has been removed as of [1.0.0-beta.31](https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#100-beta31-2017-02-09), you may want to look into the suggested alternatives from this thread [here](https://github.com/angular/angular-cli/pull/4385).

**Comment by clydin** [comment]
The github pages deploy command has been removed and is no longer supported.  There are third party options available. For example, https://github.com/angular-buch/angular-cli-ghpages

**Comment by gkucmierz** [comment]
Otherwise app dont want to build.

<img width="1070" alt="zrzut ekranu 2017-02-18 o 15 05 56" src="https://cloud.githubusercontent.com/assets/739084/23093771/1ba3ef5e-f5ec-11e6-923c-ad668fd73454.png">

**Comment by clydin** [comment]
Please try updating to the latest version.  If the issue  persists, please open another issue with the full template details so that we can further assist you.

**Comment by gkucmierz** [comment]
Ok, let me update ng-cli

**Comment by JohannesHoppe** [comment]
The error message 

```
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 12:42 in the original .ts file), resolving symbol compose in /Users/gkucmierz/learn/coin-tools/node_modules/@ngrx/core/compose.d.ts, resolving symbol AppModule in /Users/gkucmierz/learn/coin-tools/src/app/app.module.ts, resolving symbol AppModule in /Users/gkucmierz/learn/coin-tools/src/app/app.module.ts, resolving symbol AppModule in /Users/gkucmierz/learn/coin-tools/src/app/app.module.ts, resolving symbol AppModule in /Users/gkucmierz/learn/coin-tools/src/app/app.module.ts, resolving symbol AppModule in /Users/gkucmierz/learn/coin-tools/src/app/app.module.ts
```
is pretty clear. You have to make your code statically analyzable for AoT.
See here: https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.3ipjxwp1z
This error has nothing to do with github pages.
