### ISSUE TITLE
ng-test still expects old angular-cli.json

### ISSUE THREAD

**Issue by niwrA** [angular/angular-cli#4815]
instead of the one prefixed with '.'

> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.26]
node: 7.5.0
os: win32 ia32
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/flex-layout: 2.0.0-beta.5
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.7

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Just doing a fresh install on a different machine which I do occasionally to see if others can still install the package (so I don't forget to update package.json etc.)

ng-test still expects old angular-cli.json

### The log given by the failure.
> Normally this include a stack trace and some more information.

E:\angular2\Software-Management-Angular2-Client\node_modules>ng test
Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at getTestConfig (E:\angular2\Software-Management-Angular2-Client\node_modules\angular-cli\models\webpack-configs\test.js:108:25)
    at init (E:\angular2\Software-Management-Angular2-Client\node_modules\angular-cli\plugins\karma.js:44:25)
    at Array.invoke (E:\angular2\Software-Management-Angular2-Client\node_modules\di\lib\injector.js:75:15)
    at Injector.get (E:\angular2\Software-Management-Angular2-Client\node_modules\di\lib\injector.js:48:43)
    at E:\angular2\Software-Management-Angular2-Client\node_modules\karma\lib\server.js:143:20
    at Array.forEach (native)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Ionaru** [comment]
`ng version` outputs `@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.26]`

I suspect 1.0.0-beta-26 is still installed on your system (perhaps you forgot to upgrade the global module).

**Comment by mykemd** [comment]
check that your karma.conf.js has  this
`angularCli: {
      config: './.angular-cli.json',
      ...
  }
`

**Comment by laumair** [comment]
@mykemd Yep. I have this and I am running into the same issue.

**Comment by niwrA** [comment]
It was actually the renaming of the angular-cli to @angular/cli that wasn't updated in the karma.conf.js. 

It needs to have the config file renamed to the . prefixed version, and the frameworks and require paths use @angular/cli instead of angular-cli

**Comment by nevraun** [comment]
Thanks for the solution:

Updating karma.conf.js with @angular/cli (3 entries):
...
`frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-remap-istanbul'),
      require('@angular/cli/plugins/karma')
    ],
    files: [
      { pattern: './src/test.ts', watched: false }
    ],
    preprocessors: {
      './src/test.ts': ['@angular/cli']
    },`
...

**Comment by filipesilva** [comment]
Closing as answered.

There's a https://github.com/angular/angular-cli/wiki/stories-rc-update that covers everything that changed in the last few months.
