### ISSUE TITLE
ng generate model is returning invalid blueprint

### ISSUE THREAD

**Issue by ramirio** [angular/angular-cli#482]
```ng generate model taco filling:belongs-to:protein toppings:has-many:toppings name:string price:number misc```

returns ```Invalid blueprint: model```

angular-cli: 0.0.33
node: 5.10.1
os: linux x64 debian-jessie

**Comment by Brocco** [comment]
Currently there is no model blueprint within the angular-cli, hence the error you're seeing.

**Comment by iloveyo123u1** [comment]
ng g component [your_app]

**Comment by jesselpalmer** [comment]
THANKS!!!!
