### ISSUE TITLE
angular cli host address or hostname issue :: 

### ISSUE THREAD

**Issue by Prasenjiit** [angular/angular-cli#4820]
ng serve :: works fine in http://localhost:4200

ng serve --host 52.24.233.144 --port 4200
Provided host 52.24.233.144 could Not be bound. Please provided a different host address or hostname
But, when upload it to my AWS server then error occurred. Its a demo code from algular cli guide

@angular/cli: 1.0.0-beta.32.3
node: 7.0.0
npm: 3.10.8
os: linux x64

**Comment by deebloo** [comment]
@Prasenjiit can you please fill out the issue template? I am having a little trouble following what your actual issue is.

**Comment by filipesilva** [comment]
According to the error message, you cannot use that port.

**Comment by abhaychaware** [comment]
Is this resolved ? I am facing exact same issue with angular on AWS

**Comment by suchidomelo** [comment]
Same for me trying to launch app with the different public host causing this error message:
Provided host 49.248.213.2 could NOT be bound. Please provide a different host address or hostname
Error: Provided host 49.248.213.2 could NOT be bound. Please provide a different host address or hostname

**Comment by zengtane** [comment]
Same for me.Trying to launch app with the different public host.

**Comment by m-chitti** [comment]
Is this resolved, I am seeing the same issue, can some one help me on this.

Angular CLI: 1.7.4
Node: 10.13.0
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.5.13
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.4.2
webpack: 3.11.0
