### ISSUE TITLE
Error IE11

### ISSUE THREAD

**Issue by alexrmg** [angular/angular-cli#4822]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows  10. Linux 

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

ng new myapp -p gt
(No modification has been done to the application)
ng build
ng serve

(IE11) http://localhost:4200/
F5 again -- > then, jscript browser console throws error:

[Error]
SCRIPT5007: No se puede obtener la propiedad 'apply' de referencia nula o sin definir
vendor.bundle.js (43881,5)

... and the app crash.

Sorry, my OS is spanish. 

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
You'll need to adjust the `polyfills.ts` file for your target browsers by uncommenting the appropriate sections.

**Comment by alexrmg** [comment]
that's right... i'd missed adjust polyfills.ts... 

Thank you very much...

**Comment by AntiCZ** [comment]
This should be uncomment by default. Certainly for IE 11

**Comment by eddieedease** [comment]
So which lines needs to be uncommented for IE 11 to work?

**Comment by HarindraNarayan** [comment]
how to adjust polyfills ?
please explain

**Comment by AndreyPatseiko** [comment]
You make find polyfills.ts into you general project folder (by default src) 
Then you find section  /** IE9, IE10 and IE11 requires all of the following polyfills. **/, and delete comments in this section.

**Comment by eddieedease** [comment]
Also, what I found out was that when I made the app via the CLI, it was like a year ago. The polyfills.ts file has changed in that time. So if that's also your case, you could copy/paste if from a fresh ng new, adjust by removing comments and your set.
IE works good now

**Comment by sergamers** [comment]
I've error in ie 11 - proxy object is undefined.
ERROR ReferenceError: "Proxy" не определено

**Comment by sergamers** [comment]
Now i've this polyfills.ts
https://gist.github.com/sergamers/21ba3fc86d09ce0a9b23bbc518d1870e

**Comment by c-science1** [comment]
I have tried all of the above, uncommenting and installing the packages but still on IE it's giving "Syntax Error" polyfills file attached

![image](https://user-images.githubusercontent.com/19345360/37462770-f8e2d84e-284a-11e8-9fcd-574b40bf22d7.png)

**Comment by zachrickards** [comment]
Having the exact same problem as @c-science1
