### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Function calls are not supported.

### ISSUE THREAD

**Issue by smartHasmukh** [angular/angular-cli#4824]
I am facing an error when I have setup new CLI project. so my project doesn't run/work so please check it and let me know. below error are occurred. 

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 22:25 in the original .ts file), resolving symbol UtilityModule in /var/www/html/vadtal-CLI/src/app/utility/utility.module.ts
webpack: Failed to compile.

**Latest CLI**
```
"dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "angular2-moment": "^1.2.0",
    "angular2-select": "^1.0.0-beta.3",
    "autotable": "^1.0.0",
    "core-js": "^2.4.1",
    "jspdf": "^1.3.2",
    "md2": "0.0.14",
    "ng2-auto-complete": "^0.10.9",
    "ng2-pagination": "^2.0.0",
    "ng2-toastr": "^1.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.28.3",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }
}

```

**Selected function error occured.**
![utilityerror](https://cloud.githubusercontent.com/assets/8941195/23100837/0364f4e6-f6b0-11e6-9231-6767fefdae0d.png)

**Comment by grizzm0** [comment]
This is not CLI related.

Create a file with the following.

```
export function httpServiceFactory(args here...) {
  return new HttpService(args here...);
}
```

then in your module

```
import { httpServiceFactory } from './path';
...
useFactory: httpServiceFactory,
...
```

**Comment by smartHasmukh** [comment]
@grizzm0  I have done But now I am facing another issue 

VM1688:8 Unhandled promise rejection ZoneAwareError 

Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.

![zonefileissue](https://cloud.githubusercontent.com/assets/8941195/23102276/8c2b108c-f6cc-11e6-9457-d25886e129d8.png)

**Comment by grizzm0** [comment]
Could you close this one aswell? :)

**Comment by smartHasmukh** [comment]
@grizzm0 I have closed.

**Comment by grizzm0** [comment]
You closed your new issue. Not this one. :p
