### ISSUE TITLE
Angular CLI project is not working in Internet Explorer 11

### ISSUE THREAD

**Issue by navneetsharma1988** [angular/angular-cli#4825]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
No. The app was created using CLI and I have not changed the code.

### The log given by the failure.
> 
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: localhost:4200
SCRIPT5007: Unable to get property 'apply' of undefined or null reference
File: vendor.bundle.js, Line: 43860, Column: 5

### Mention any other details that might be useful.
Create a new app using `ng new app-name` and launch app in IE
 > ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
Dup #4822
Please adjust 'polyfills.ts' for your target browsers.

**Comment by navneetsharma1988** [comment]
Thanks it worked...

**Comment by kudorgyozo** [comment]
What did you do to make it work?

**Comment by navneetsharma1988** [comment]
@kudorgyozo  as stated above please adust 'polyfills.ts' and uncomment entries for IE

**Comment by bijayy33** [comment]
@navneetsharma1988  Thanks buddy it worked. I am still facing issue with FireForx. In Fireforx content are partially loaded and I see no errors in console.

**Comment by manoj30dec** [comment]
Yup just open pollyfils.ts and uncomment following lines..

// import 'core-js/es6/symbol';
// import 'core-js/es6/object';
// import 'core-js/es6/function';
// import 'core-js/es6/parse-int';
// import 'core-js/es6/parse-float';
// import 'core-js/es6/number';
// import 'core-js/es6/math';
// import 'core-js/es6/string';
// import 'core-js/es6/date';
// import 'core-js/es6/array';
// import 'core-js/es6/regexp';
// import 'core-js/es6/map';
// import 'core-js/es6/weak-map';
// import 'core-js/es6/set';

**Comment by shoomkloom** [comment]
I also had to uncomment the following lines for it to work on IE11:
import 'intl';  // Run `npm install --save intl`.
import 'intl/locale-data/jsonp/en';

**Comment by Belmiris** [comment]
Yikes! Thank you all.

**Comment by c-science1** [comment]
I have tried all of the above, uncommenting and installing the packages but still on IE it's giving "Syntax Error"

![image](https://user-images.githubusercontent.com/19345360/37460995-e54139c6-2844-11e8-83aa-9e1511f5568b.png)

**Comment by bencesz** [comment]
@c-science1 same problem here. SCRIPT1006 error, but for me is at the eval(" ... sourceURL=webpack-internal:///../../../../@ngrx/store/src/utils.js\n"); Seems like there is an character in that vendor file which is unrecognised by IE...

**Comment by bencesz** [comment]
My issue has been solve by replacing
import { combineReducers } from '@ngrx/store/src/utils';
to:
import { combineReducers } from '@ngrx/store';

so it was an ngrx import related, not polyfill related. Although it is possible that they are somehow related as well :)
