### ISSUE TITLE
test fails after ng generate module 

### ISSUE THREAD

**Issue by vcorr** [angular/angular-cli#4827]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

```
ng new myApp
cd myApp
ng generate module myModule --spec=true --routing=true
ng test

```

### The log given by the failure.
> Normally this include a stack trace and some more information.

Chrome 56.0.2924 (Windows 10 0.0.0) MyModuleModule should create an instance FAILED
        TypeError: myModule_module_1.default is not a constructor

### Mention any other details that might be useful.

It seems that there are curly braces missing from the module import in the generated spec. Adding them fixes the problem.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
We've fixed this since, thanks for the report!

**Comment by johanb** [comment]
@filipesilva could you elaborate on how this was fixed ? I'm running into this same issue.
