### ISSUE TITLE
 Unhandled promise rejection ZoneAwareError

### ISSUE THREAD

**Issue by smartHasmukh** [angular/angular-cli#4829]
I am facing another issue. Unhandled promise rejection ZoneAwareError  Error: Zone.js has detected that ZoneAwarePromise (window|global).Promise has been overwritten.

 Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.

![zonefileissue](https://cloud.githubusercontent.com/assets/8941195/23102331/634f91c8-f6cd-11e6-9b1e-4688c952399c.png)

**Comment by grizzm0** [comment]
Please close #4824 as you opened another issue.

These are not issues with the Angular CLI but with your code. Please use stackoverflow for such questions in the future.

Compare your polyfills.ts with the latest one from AngularCLI.

See: https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng2/files/__path__/polyfills.ts

**Comment by smartHasmukh** [comment]
Not a questions on CLI
