### ISSUE TITLE
`ng serve` removes the `dist` folder, don't see why developing should remove my production build

### ISSUE THREAD

**Issue by ohjames** [angular/angular-cli#4830]
### OS?
Linux (arch)

### Versions.
1.0.0-beta30

### Repro steps.
1. ng build --prod
2. ng serve
3. `ng serve` has now removed my `dist` folder.

**Comment by grizzm0** [comment]
This was done on purpose.

See: #4293, #4366

**Comment by ohjames** [comment]
Seems to me like documenting behaviour would have been a better approach to #4293 than deleting the folder. Looks to me like you're treating the symptoms rather than the disease with the current approach and this philosophy concerns me. There's also an element of "capitulating to ignorance" about the approach you took which also niggles at me ;)

In my instance I was building some server code into `dist`. Perhaps I should have built it into a folder under `/dev/shm` but the simplest quick solution seemed to be to put the code alongside the client output. angular-cli deleting my code was an inconvenience.
