### ISSUE TITLE
Component images are not included in build

### ISSUE THREAD

**Issue by LeonLiber** [angular/angular-cli#4831]
### OS?
> Mac OSX El Capitan

### Versions.
> 1.0.0-beta.26

### Repro steps.
> Added images in src/app/componenet/images and added links to them from HTML

The images are shown properly in dev mode but once built, they are missing.

Looks like none of the images referenced in css/html are passing through webpack image loader and thus are not base64'ed nor copied over..

I would love to keep the images with the component and __not__ use assets/ for that.

What am I missing?
Thanks in advance

**Comment by clydin** [comment]
HTML is not processed.  However, component stylesheets are but there is currently an issue when used in combination with AOT (which is the default for production builds).

See this issue for details: https://github.com/angular/angular-cli/issues/4806

**Comment by janwo** [comment]
The issue #4806 was closed and does not solve image recognition in html files.

**Comment by filipesilva** [comment]
Closing as answered by @clydin. The CLI doesn't process images in HTML.
