### ISSUE TITLE
NG G component fails after updating to beta.32

### ISSUE THREAD

**Issue by ndcunningham** [angular/angular-cli#4832]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10.

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.31]
node: 6.9.4
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.7

### Repro steps.
> `ng g component task-filter`

### The log given by the failure.
> $ ng g component task-filter
installing component
  create src\app\task\components\task-filter\task-filter.component.less
  create src\app\task\components\task-filter\task-filter.component.html
  create src\app\task\components\task-filter\task-filter.component.spec.ts
  create src\app\task\components\task-filter\task-filter.component.ts
viewEncapsulation is not defined (Error in blueprint template: C:\repos\far-cli\node_modules\@angular\cli\blueprints\component\files\__path__\__name__.component.ts)
ReferenceError: viewEncapsulation is not defined (Error in blueprint template: C:\repos\far-cli\node_modules\@angular\cli\blueprints\component\files\__path__\__name__.component.ts)
    at eval (eval at <anonymous> (C:\repos\far-cli\node_modules\lodash\template.js:224:12), <anonymous>:9:5)
    at processTemplate (C:\repos\far-cli\node_modules\@angular\cli\ember-cli\lib\models\file-info.js:20:36)
    at C:\repos\far-cli\node_modules\@angular\cli\ember-cli\lib\models\file-info.js:97:20
    at tryCatch (C:\repos\far-cli\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\repos\far-cli\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (C:\repos\far-cli\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (C:\repos\far-cli\node_modules\rsvp\dist\rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

### Mention any other details that might be useful.

Worked previously, i also tried ng g component 'task-filter'
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Brocco** [comment]
Can you post your `angular-cli.json` file? And also the the results of running `ng --version` outside of a CLI project?

**Comment by ndcunningham** [comment]
`ng --version` Outside of cli

`
@angular/cli: 1.0.0-beta.32.3
node: 6.9.4
os: win32 x64
`

`.angular-cli.json`

```
{
  "project": {
    "version": "1.0.0-beta.31",
    "name": "far-cli"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico",
        "config.json"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "cet",
      "styles": [
        "styles.less"
      ],
      "scripts": [
        "cet-config-bootstrap.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "files": "src/**/*.ts",
      "project": "src/tsconfig.json"
    },
    {
      "files": "e2e/**/*.ts",
      "project": "e2e/tsconfig.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "less",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  },
  "packageManager": "yarn"
}
```

**Comment by Brocco** [comment]
The structure of the `defaults` section has changed for clearer defaults. Can you delete everything under there except for `styleExt` and try again?

**Comment by AloeDream** [comment]
`"version": "1.0.0-beta.31",`
Are you sure your local CLI package and project itself were properly updated? Looks like they're still beta.31

**Comment by ndcunningham** [comment]
@Brocco i did and got the same error message
@AloeDream i did `rm -rf on node_modules`  and did `yarn add @angular/cli@latest --dev`

**Comment by Brocco** [comment]
Is this repo online somewhere that it can be cloned/tested against?

**Comment by ndcunningham** [comment]
No we are in the middle of moving from systemJS to @angular/cli. 

It's an internal project, strange that updating from the previous beta broke this though.

**Comment by ndcunningham** [comment]
@Brocco it seems the error is with `lodash` i create a new project with `ng g c` working 
then i installed i added `lodash: ts2.0` inside my `package.json` and ran `npm i` tried `ng g c` again and got the error.

Since i am not on TS `2.1` yet is why i installed that version of `lodash` or am i mistaken?

**Comment by Brocco** [comment]
@ndcunningham I will take a look into the inclusion of lodash, thanks!

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by jspizziri** [comment]
I also experienced this issue after installing `lodash@^4.15.0` & `@angular/cli@1.1.2`.
