### ISSUE TITLE
owlCarousel how to run the owl carousel script to add function to jquery

### ISSUE THREAD

**Issue by dereklin** [angular/angular-cli#4838]
I tried different ways to make it work but couldn't get anywhere.  I tried solutions found at https://github.com/angular/angular-cli/issues/4533 and https://github.com/angular/angular-cli/issues/2760

My source is at https://github.com/dereklin/angular-cli-owl-carousel

Here is the error message:
![angular-cli-owl-carousel](https://cloud.githubusercontent.com/assets/2231799/23111725/5ff6ce9e-f6df-11e6-85df-c58c524bddbd.PNG)

**Comment by eapostol** [comment]
Experiencing the same issue even after following callback thread discussion  at [https://github.com/angular/angular-cli/issues/4533](url)

**Comment by filipesilva** [comment]
Please see https://github.com/angular/angular-cli/issues/5139#issuecomment-283634059 (same problem with local and global jquery).
