### ISSUE TITLE
Unable to load background image since beta 32

### ISSUE THREAD

**Issue by FallenRiteMonk** [angular/angular-cli#4842]
### OS?
OpenSuse Tumbleweed

### Versions.
```
@angular/cli: 1.0.0-beta.32.3
node: 6.9.3
os: linux x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/flex-layout: 2.0.0-beta.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.5
```

### Repro steps.
Have a component with the following 'example.component.scss':
```
...
background: url("assets/imgs/background.jpg") no-repeat center center fixed;
...
```

### The log given by the failure.
```
ERROR in ./src/app/core/components/example/example.component.scss
Module not found: Error: Can't resolve './assets/imgs/background.jpg' in '<COMPONENT_FOLDER_PATH>'
 @ ./src/app/core/components/example/example.component.scss 6:137-173
 @ ./src/app/core/components/example/example.component.ts
 @ ./src/app/core/core.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
```

### Mention any other details that might be useful.
Removing the mentioned line from scss file and running a build results in the image being in the right place within the dist folder, so it is not just some wrong path issue.

**Comment by Nikki1993** [comment]
Try this `background: url("../assets/imgs/background.jpg") no-repeat center center fixed;`

**Comment by FallenRiteMonk** [comment]
@Nikki1993 Thanks, it wasn't exactly the line you wrote due to the component being further nested, but using the relative path solved the problem.

**Comment by ernerock** [comment]
this doesn't work when running "ng build". It strips the "../" but leaves it as  url("/assets/imgs/...); while it should leave it as ./assets/... in order for it to work

**Comment by slangley** [comment]
In order to get this to work, I had to provide a full relative path to the image location in the application source folder (not webroot).  In my case, this took ../../../images/image.png

After this was done, SCSS was able to compile, and the image file was inlined into the final CSS.

**Comment by Boxroma** [comment]
Has this issue been resolved cause I am also having the same issue..
