### ISSUE TITLE
ng serve or build does not take production environment

### ISSUE THREAD

**Issue by ukaaa** [angular/angular-cli#4843]
### OS?
Windows 10

### Versions.
```bash
@angular/cli: 1.0.0-beta.30
node: 6.9.0
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.7
```

### Repro steps.
```bash
ng serve --environment=prod --target=production
```
When I call the above, it doesn't use the version `apps.environments.prod` specified in `angular-cli.json`.

### Mention any other details that might be useful.
When I specify `--environment=dev --target=development`, _or_ when I leave these flags out, it correctly sets the environment to `apps.environments.dev` specified in `angular-cli.json`.

### Related issues
Possibly #4711, but that one mentions the shorthand `-prod` flag to not work.

**Comment by Nikki1993** [comment]
It seems like you are running an outdated version of angular-cli. Could you update it and see if you still observe issues with running ng serve on production? 

Do look through changelog as there is some changes (not much) that needs to be made to make you project compatible with the latest version.

**Comment by deebloo** [comment]
@ukaaa I believe this issue was fixed in beta.31.

**Comment by ukaaa** [comment]
I've just created a blank project using beta.32, then updated the files of my existing project by copying and overwriting any differences I could find. Then I removed node_modules and reinstalled the packages.

So now my existing project should be up to date with beta.32.

And indeed, running the following seems to work now:
```
ng serve --environment=prod --target=production
```
