### ISSUE TITLE
Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by trueflywood** [angular/angular-cli#4844]
### OS?
 >Mac OSX (El Capitan)

### Versions.
>@angular/cli: 1.0.0-beta.32.3 [1.5.10]
node: 7.4.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/upgrade: 2.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

### Repro steps.
> ng serve

### The log given by the failure.
> ** NG Live Development Server is running on http://localhost:4200. **
Hash: b701c02e6491ec078712                                                                 
Time: 24550ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 135 kB {5} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 86.5 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 461 kB {5} [initial] [rendered]
chunk    {3} scripts.bundle.js, scripts.bundle.js.map (scripts) 360 kB {5} [initial] [rendered]
chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.58 MB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
ERROR in Error encountered resolving symbol values statically. Calling function 'CookieService', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol routes in /Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/src/app/app.routing.ts, resolving symbol routes in /Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/src/app/app.routing.ts, resolving symbol AppRoutingModule in /Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/src/app/app.routing.ts, resolving symbol AppRoutingModule in /Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/src/app/app.routing.ts, resolving symbol AppRoutingModule in /Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/src/app/app.routing.ts
webpack: Failed to compile.

### Mention any other details that might be useful.

app.routing.ts
>import { NgModule }                 from '@angular/core';
import { Routes, RouterModule }     from '@angular/router';
import {CookieService}              from 'angular2-cookie/core';
// Layouts
import { FullLayoutComponent }      from './layouts/full-layout.component';
import { SimpleLayoutComponent }    from './layouts/simple-layout.component';
let cookieService = new CookieService();
export const routes: Routes = [
    {
        path: '',
        redirectTo: cookieService.get('access_token') ? 'dashboard' : 'login',
        pathMatch: 'full',
    },
    .....
];
@NgModule({
    imports: [ RouterModule.forRoot(routes) ],
    exports: [ RouterModule ]
})
export class AppRoutingModule {}

**Comment by deebloo** [comment]
This is the part I believe is the culprit. rather than a conditional redirect try using a router guard. https://angular.io/docs/ts/latest/guide/router.html#!#guards

Any code that ends up in a decorator needs to be statically analyzable. (no function calls, conditional statements, etc)

```TS
let cookieService = new CookieService();
export const routes: Routes = [
{
path: '',
redirectTo: cookieService.get('access_token') ? 'dashboard' : 'login',
pathMatch: 'full',
},
```

**Comment by filipesilva** [comment]
Closing as answered by @deebloo, cheers!
