### ISSUE TITLE
Question: Performance of 'ng test' - possibility of using more than one CPUs

### ISSUE THREAD

**Issue by zsfarkas** [angular/angular-cli#4848]
> Please provide us with the following information:
> ---------------------------------------------------------------

Is there a way to use more the one cpu at the same time for the test cases? Maybe more browser instances?

Currently, if you run karma with `ng test`, it only uses one cpu. If you have more than 400 test cases, which is easy to reach if you do TDD in a proper way, it takes a long time (more than 10 minutes in our case). 

No question, we should improve the test cases, as well. 

But still I have the question, whether it is possible to utilize the capabilities of the underlying computer?

I know, it sounds like a Karma question. But Karma has a parameter `concurrency`, which has no effect if I use the CLI. Even if I have to admit, I have not checked, if it had an effect, without the CLI. But I found the preprocessing in the `test.ts` very suspicious.

So I would appreciate, if somebody could share his/her experiences to the topic.

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux (Ubuntu)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.25.5
node: 7.4.0
os: linux x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Just run ng test with over 400 test cases.

### The log given by the failure.
> Normally this include a stack trace and some more information.

No stack trace.

### Mention any other details that might be useful.

Nothing more
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattdistefano** [comment]
Is that 10 minutes for compilation + test execution or just test execution? Number of tests is a tricky metric but our project has over 1000 and only takes a couple minutes (which, granted, is still a couple minutes longer than I'd like), so 10 minutes for 400 does seem excessive.

**Comment by zsfarkas** [comment]
Thank you for your feedback. Actually it is pretty quick if you test pure javascript functionality, but if you have lot of big `TestBed`-s with lot of `DebugElement.query`-s, then it becomes somehow slow. I think asynchronism plays a role in performance, as well.

Could you check if more than one CPUs are used while your test cases are running?

Apart from that, please, let me know if your project is open source, then I would have a look at it. Thank you.

**Comment by intellix** [comment]
Just wondering. Did it take 10 minutes when you have the browser minimised? I've noticed that Chrome throttles a tab/window that's minimised/inactive and causes tests to go slow. As soon as you bring the window to the foreground my tests speed up dramatically.

**Comment by zsfarkas** [comment]
@intellix: Thank you. That's a good point. I will test it tomorrow. 

Nevertheless, it runs with PhantomJS (headless) over 15 minutes. :-(

**Comment by mattdistefano** [comment]
@zsfarkas FWIW I found PhantomJS much, much slower than Chrome, at least on Windows.

**Comment by zsfarkas** [comment]
Thank you for your comments. It seems to be a topic at karma-runner, as well:

karma-runner/karma#439

So I think, I close it here.
