### ISSUE TITLE
I have install new cli but below error occured on my project

### ISSUE THREAD

**Issue by smartHasmukh** [angular/angular-cli#4856]
```
 npm ERR! Linux 4.4.0-63-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! vadtal-cli@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vadtal-cli@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vadtal-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vadtal-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vadtal-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/sampleproject/public/vadtal_upgradation/npm-debug.log
```

**Comment by beeman** [comment]
@smartHasmukh can you please use the issue template when filing an issue?

**Comment by smartHasmukh** [comment]
@beeman Yes, sure. But can you please tell me what is issue template because I am aware of this. You mean by screenshot?? 
Thanks

**Comment by beeman** [comment]
It's the template you get when you create a new issue: https://github.com/angular/angular-cli/issues/new

**Comment by smartHasmukh** [comment]
@beeman Got it Thanks. but please answer me my question. I have tried to find out this solutions but I cant solved this

**Comment by beeman** [comment]
@smartHasmukh Without the information in the issue template there's not so much to solve. Please submit the issue as requested. These questions are asked for a reason: to make troubleshooting easier.

**Comment by aminsmartsense** [comment]
Hello @beeman,

We have update angular CLI version and node version so on running project we got some errors and we are using WebStrom in that whenever I open my project that time only opened files not displaying any folders. and when I am installing npm and CLI that time I am facing error like first comment.

We are using Ubutnu OS.
Ubutnu Version 16.04 LTS

Node Version : 7.4.0
npm Version : 4.0.5

We are using 3 laptops with same configurations but in one system working fine other two are facing same issue.

Thanks

**Comment by beeman** [comment]
@aminsmartsense it's probably best to open your own issue for this, not hijacking the one from @smartHasmukh

**Comment by aminsmartsense** [comment]
@beeman Sorry for say this. I know this is our own issue, but we are not able to where we solve this issue and add issue. so we are just taking help from your side.

Thanks

**Comment by smartHasmukh** [comment]
I have fixed issue my self. Please follow below step for resolve your issue.

1.First you need to update `node sudo n stable`
2. Install letest CLI `npm install -g angular-cli`
3. Clone your project or create your project
4. `npm install`
5. If any error accrued then remove `node_module` directory
6. `npm install`
7. Install Typescript `npm install typescript -g`

If any module not install please try with `sudo.`

**Comment by clausche** [comment]
thanks you

**Comment by smartHasmukh** [comment]
@clausche  Welcome
