### ISSUE TITLE
I am facing warning

### ISSUE THREAD

**Issue by smartHasmukh** [angular/angular-cli#4857]
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/upgrade@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/upgrade@2.2.1 requires a peer of @angular/compiler@2.2.1 but none was installed.
npm WARN @angular/upgrade@2.2.1 requires a peer of @angular/platform-browser@2.2.1 but none was installed.
npm WARN @angular/upgrade@2.2.1 requires a peer of @angular/platform-browser-dynamic@2.2.1 but none was installed.
npm WARN jss-camel-case@0.1.2 requires a peer of jss@^2.1.0 but none was installed.
```

**Comment by beeman** [comment]
@smartHasmukh can you please use the issue template when filing an issue?

Generally warnings are safe to ignore btw.

**Comment by smartHasmukh** [comment]
sure @beeman

**Comment by smartHasmukh** [comment]
Resolve my self

**Comment by jorgebermudez** [comment]
how you resolve?

**Comment by smartHasmukh** [comment]
@jorgebermudez Check it #4856. Above issue also resolved.

**Comment by anilthummar** [comment]
@smartHasmukh 
When i am installed cordova  i am getting following message.

Please help me.


**C:\Users\Android>npm install -g ionic cordova
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.3.3: Use uuid module instead
C:\Users\Android\AppData\Roaming\npm\cordova -> C:\Users\Android\AppData\Roaming\npm\node_modules\cordova\bin\cordova
C:\Users\Android\AppData\Roaming\npm\ionic -> C:\Users\Android\AppData\Roaming\npm\node_modules\ionic\bin\ionic
C:\Users\Android\AppData\Roaming\npm**

**Comment by playnox** [comment]
`sudo chown -R $USER /usr/local`
Then run angular install one more time...
`npm install -g @angular/cli`

This fixed problem on my end, not sure if it's related :)

**Comment by anilthummar** [comment]
I fix the  installation cordova problem,In my system amazon web api block so i was ublock and its work perfect.

**Comment by harshkant** [comment]
I have this problem 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@angular/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by Satish-Charmal** [comment]
I also have the same problem.

Does anyone has any solution for the particular issue?
 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@angular/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by beeman** [comment]
@harshkant  @Satish-Charmal the messages you are seeing are actually warnings and can thus be safely ignored.

The `fsevents` library is only relevant for systems running macOS, that's why you get the ` Unsupported platform` message if you run it on Linux or Windows.
