### ISSUE TITLE
please update this website's docs to the latest version! 

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [angular/angular-cli#4861]
# please update this website's docs to the latest version!

![new-ng2-cli](https://cloud.githubusercontent.com/assets/18028768/23159060/5f17d152-f85c-11e6-8e1c-636178742c4f.png)

## enhancement

![ng-cli warning2017](https://cloud.githubusercontent.com/assets/18028768/23159117/8b4a647e-f85c-11e6-9435-4fec8cd4320c.png)

**Comment by Equinox** [comment]
Looks like to me the [fix is already there](https://github.com/angular/microsites/pull/6), but the site needs to be re-built first, which the core CLI guys might be holding off until the documentation stuff is done (or maybe it's an internal-thing, who knows -- either way, the fix should be done soon). :)

**Comment by Equinox** [comment]
@hansl / @filipesilva for [cli.angular.io's footer, it uses the `microsite-ui`'s _footer partial](https://github.com/angular/microsites/blob/master/cli.angular.io/index.ejs#L61). The microsite-ui repo, https://github.com/ericjim/microsite-ui, is a dead link apparently so I can't correct the footer's wrong <a> [link to wwww.angular.io (4 w's)](https://i.imgur.com/zJOqfvw.png) but you guys might have better access/idea of how to fix it [if necessary].

**Comment by filipesilva** [comment]
We're working on updating it atm. I'm sorry for the confusion it's causing meanwhile. That whole site is quite old atm.
