### ISSUE TITLE
vender.bundle.js occurs error in IE 11.

### ISSUE THREAD

**Issue by zhxx** [angular/angular-cli#4862]
### OS?
Windows 7

### Versions.
@angular/cli: 1.0.0-beta.31
node: 6.9.1
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.8

### Repro steps.

1. Create a new folder.
2. Run 'ng init' in it.
3. Run 'ng serve' in it.
4. Open http://localhost:4200 in Internet Explorer.

### The log given by the failure.
No error information

### Mention any other details that might be useful.
More information please refer to https://github.com/angular/angular/issues/14592

**Comment by mattdistefano** [comment]
Are you loading the appropriate polyfills in `src\polyfills.ts`? I believe in newer versions of the CLI the IE11 polyfills are commented out by default.

**Comment by zhxx** [comment]
@mattdistefano You are right, after importing polyfills.ts in main.ts, it works. Thanks

**Comment by killrazor** [comment]
Linking [polyfills.ts](angular/aio/src/polyfills.ts) for those looking for the updates like me.

**Comment by abbymrs** [comment]
Hi,

My angular 5 project also has error in` vendor.bundle.js` even importing the `polyfill.ts` and enable polyfills for IE browser, not sure why this happens. It works well in chrome and firefox.

```
SCRIPT1002: Syntax error 
File: vendor.bundle.js, Line: 5552, Column: 1
```

**Comment by miloskovacevic** [comment]
@abbymrs  same problem

**Comment by nohanna** [comment]
Same problem, did you find anything @abbymrs @miloskovacevic ?

**Comment by miloskovacevic** [comment]
@nohanna  hey, in my case problem was signalr library that we use.

**Comment by nohanna** [comment]
Ok thanks, I will investigate but I tried a lot of solutions and nothing works...

**Comment by miloskovacevic** [comment]
Usually is some library that is creating a problem.

**Comment by nohanna** [comment]
Ok thank you, I'll try to remove libraries one by one

**Comment by miloskovacevic** [comment]
np

**Comment by tuckergordon** [comment]
In case it's useful to anyone who finds this thread, we ran into this issue because we were using the latest version of [d3-array](https://github.com/d3/d3-array). Went looking through the [release notes](https://github.com/d3/d3-array/releases) and found nugget in v2.0:

> this release adopts ES2015 language features such as for-of and drops support for older browsers, including IE. If you need to support pre-ES2015 environments, you should stick with d3-array 1.x or use a transpiler.
