### ISSUE TITLE
Please enhancement the ng cli commands para  for more easy using!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [angular/angular-cli#4866]
![image](https://cloud.githubusercontent.com/assets/18028768/23161562/a1153474-f865-11e6-8f28-c77e854e50d6.png)
# just like npm did!

## npm (bad)
```
$ npm install --global --save--dev
$ npm install --global --save
```
## npm (good)
```
$ npm i -g -D
$ npm i -g -S
```

## need enhancement
```
$ ng server --open

# please make the following shorthands

$ ng server -O
$ ng server -o
```

**Comment by xgqfrms-GitHub** [comment]
# Another question, why the fonts's color became to dark after run the commands `ng sever` ?

it should be always brightness, which more comfortable for users!

**Comment by beeman** [comment]
These colors are a setting of the terminal you're using.

**Comment by filipesilva** [comment]
The `-o` alias for `--open` already exists. It's better to not use both `-o` and `-O` for the same alias since they could be for difference commands in the future.

You can see all the aliases with `ng serve --help`.
