### ISSUE TITLE
How to dependence other ng2 project

### ISSUE THREAD

**Issue by suplch** [angular/angular-cli#4867]
### OS?
>  Mac OSX (Yosemite)

### Versions.
> angular-cli: 1.0.0-beta.26
node: 7.0.0
os: darwin x64

### Repro steps.
> I want to create ng2 common project that include some common component for other projects, and then I create different another ng2 project that need to import some common component from that common project. because I need create many ng2 project, and I want to use common components for these ng2 project, how to get such goal.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by nikoTM** [comment]
You need to manually copy your components from common project. You could publish your common to npm, and add it as a dependency to your projects. Either way it's not something that angular-cli tries to achieve.

**Comment by filipesilva** [comment]
Angular CLI does not currently support building libraries. It is being tracked in https://github.com/angular/angular-cli/issues/1692.
