### ISSUE TITLE
Deprectation warning for loaderUtils.parseQuery() from loader-utils on ng build

### ISSUE THREAD

**Issue by anderaus** [angular/angular-cli#4869]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 8.1 Pro

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-beta.32.3
node: 7.4.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Brand new app created using the CLI.
Run `ng new myproject` then `ng build`.
No changes to any code.

### The log given by the failure.
> Normally this include a stack trace and some more information.

λ ng build
 10% building modules 4/4 modules 0 active(node:10396) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: 4a28dd932abdbd64b02a
Time: 6930ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 153 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 4.23 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 10.1 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.39 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

### Mention any other details that might be useful.

Related to loader-utils issue 56:  https://github.com/webpack/loader-utils/issues/56

**Comment by cebor** [comment]
The deprecation warning is caused by ExtractTextWebpackPlugin.

Issue: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/421
