### ISSUE TITLE
Getting error throw 'reflect-metadata shim is required when using class decorators';

### ISSUE THREAD

**Issue by alltej** [angular/angular-cli#4873]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windos 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-beta.32.3
node: 6.9.5
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Created using the CLI

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
Error occured when trying to run the ts-node 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I have no idea what you're trying to do or how to reproduce this. Please open a new issue and fill in the issue template.
