### ISSUE TITLE
Option to run tests on previous build

### ISSUE THREAD

**Issue by janostik** [angular/angular-cli#4875]
# Feature request:

### Reason
For larger projects this will greatly increase build time on automated build servers where running tests is prerequisite for successful build. For example our builds now take 10-15min. Having also tests doubles that time.

### Example usage
`ng test --path path/to/existing/build --query=<something to pass through to phantom via query params>`

### What I tried
`ng test --build false` didn't help and the build was run

### Possible issues
can this work with --aot flag?

> ---------------------------------------------------------------
### Links to existing feature and pull requests in ember-cli
- https://github.com/ember-cli/ember-cli/issues/4872
- https://github.com/ember-cli/ember-cli/pull/4874

**Comment by filipesilva** [comment]
Angular CLI and Ember CLI use vastly different build systems.

In ours, it doesn't make sense to use an existing build for unit tests. A build application has no unit test code, nor does it have the TS code needed for the unit tests to import.
