### ISSUE TITLE
Need build documentation

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular-cli#4879]
As far as I know there is absolutely no documentation to build the app.

The main documentation is completely outdated : https://cli.angular.io/reference.pdf

Maybe I'm missing something.

**Comment by deebloo** [comment]
https://github.com/angular/angular-cli/wiki/build

**Comment by Ploppy3** [comment]
Thank you very much.
Maybe you should consider removing the outdated PDF on the main website.

**Comment by deebloo** [comment]
Work is being done to update documentation as the cli approaches RC and then final 1.0 release

**Comment by Ploppy3** [comment]
I realized the Wiki is also not up to date. Missing --no-sourcemap info in build documentation.
I'm gonna close the issue now.

**Comment by filipesilva** [comment]
Yeap we're aware of the problems with the CLI site and we have someone on it. Apologies from the troubles it might have caused you.

Regarding `--no-sourcemap`, it's there as `--sourcemap`. Boolean options in general default to true, and you can switch them with `--no-optionname`. This isn't mentioned anywhere though, so yeah.
