### ISSUE TITLE
Angular cli is throwing an error when I create a jQuery OpaqueToken.

### ISSUE THREAD

**Issue by deepthinker430** [angular/angular-cli#4885]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 8

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here: @angular/cli: 1.0.0-beta.31

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
I'm developing an app using angular cli.

### The log given by the failure.
> Normally this include a stack trace and some more information.
ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'jQuery'. Consider exporting the symbol (position 28:13 in the original .ts file), resolving symbol AppModule in D:/public/src/app/app.module.ts

### Mention any other details that might be useful.
I've included the jquery script file as a sependency in the scripts array in the angular-cli.json file.
```
"scripts": [
            "../node_modules/jquery/dist/jquery.js",
        ]
```
I created a simple service that exports a token for jquery.

```
import {OpaqueToken} from '@angular/core'

export let JQUERY_TOKEN = new OpaqueToken('jQuery');
```
I imported the token and declared the jQuery object in my app.module.ts file,

```
import {JQUERY_TOKEN} from './shared/jquery'
declare let jQuery:any;

```

and also included the token in the providers array:
`providers: [{provide:JQUERY_TOKEN, useValue: jQuery}]`

When I run the "ng build" command, angular cli is throwing the following error:

ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'jQuery'. Consider exporting the symbol (position 28:13 in the original .ts file), resolving symbol AppModule in D:/public/src/app/app.module.ts

Could someone help me solve this issue?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
useValue needs to be statically analyzable (at build time). useFactory with an exported function should work.

However,  jQuery is a global.  You could also just add the declare line where needed, if desired.

**Comment by filipesilva** [comment]
Closing as answered, thanks @clydin!
