### ISSUE TITLE
Support deep linking for ng serve

### ISSUE THREAD

**Issue by Brocco** [angular/angular-cli#489]
# Deep Linking Support Request

Currently when running ng serve and developing within a route, the current route is not reloaded, just the root of the application. As a developer using the CLI to `ng serve` while doing development I expect the current route to reload when I make a change to my code. The actual result is that the application root is loaded and no additional routes are reloaded.

**Steps to Reproduce**

``` bash
ng new foo
ng generate route test-route
#open foo.ts, find the test-route configuration and add the property: `useAsDefault: true`
ng serve
```
In the browser navigate to `http://localhost:4200/` (which will redirect you to `http://localhost:4200/test-route` because of the `useDefaultRoute`) and you will see:
![image](https://cloud.githubusercontent.com/assets/1565117/14717641/6e154672-07c0-11e6-841a-2e6233a52164.png)

Refresh the browser (or make a change to your code, which will reload the browser) and you will see this:
![image](https://cloud.githubusercontent.com/assets/1565117/14717688/95e31936-07c0-11e6-9318-6369117f85ec.png)

**Comment by hansl** [comment]
This is a new issue, it should work as expected.

**Comment by Brocco** [comment]
I believe this is working now... closing
