### ISSUE TITLE
PS C:\aaa-angular2\foundation\ag2-tubes> ng help C:\Users\Ted-Home\AppData\Roaming\npm\node_modules\@angular\cli\models\config\config.js:15     constructor(_configPath, schema, configJson, fallbacks = []) {                                                            ^  SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by tedrob** [angular/angular-cli#4892]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
Angular CLI requires node 6.9 or greater.

**Comment by phil294** [comment]
a proper error message would be nice.
