### ISSUE TITLE
Don't delete the dist / output-path until the build has complete successfully

### ISSUE THREAD

**Issue by gianpaj** [angular/angular-cli#4900]
I'm not sure if there's a command line option for this already.

This is particularly useful when you're building an angular app in production and, because a build can take few minutes to complete on a small server, your website could be down for that amount of time.

If the build could use a temporary folder and move the files to the `dist` or `output-path` only when the build successed, that would be lovely 🙏

**Comment by grizzm0** [comment]
You are not really supposed to use the build directory directly.

Your deploy script should copy over the build directory to the desired destination after success.

**Comment by gianpaj** [comment]
Ok. I'll write my own build script to do that
