### ISSUE TITLE
ng eject creates a source-map error when @angular/material is used

### ISSUE THREAD

**Issue by ricketysplit** [angular/angular-cli#4905]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-beta.32.3 (e)
node: 6.9.1
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8
@angular/material: 2.0.0-beta.2

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Created a brand new app
Added latest @angular/material and added it to app.module
ng serve runs fine.
Ran ng eject to expose webpack.config
Now running npm start creates the error below

### The log given by the failure.
> Normally this include a stack trace and some more information.
 10% building modules 4/4 modules 0 active(node:11492) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
 92% chunk asset optimizationC:\Projects\san-diego-house\node_modules\source-map\lib\source-node.js:95
          var code = nextLine.substr(0, mapping.generatedColumn -
                             ^

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (C:\Projects\san-diego-house\node_modules\source-map\lib\source-node.js:95:30)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (C:\Projects\san-diego-house\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (C:\Projects\san-diego-house\node_modules\source-map\lib\source-node.js:80:24)
    at SourceMapSource.node (C:\Projects\san-diego-house\node_modules\webpack-sources\lib\SourceMapSource.js:42:20)
    at ReplaceSource.node (C:\Projects\san-diego-house\node_modules\webpack-sources\lib\ReplaceSource.js:69:29)
    at CachedSource.node (C:\Projects\san-diego-house\node_modules\webpack-sources\lib\CachedSource.js:12:23)
    at C:\Projects\san-diego-house\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\Projects\san-diego-house\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
    at C:\Projects\san-diego-house\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\Projects\san-diego-house\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
    at C:\Projects\san-diego-house\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\Projects\san-diego-house\node_modules\webpack-sources\lib\ConcatSource.js:39:60)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Aides359** [comment]
Same problem occured to me yesterday - haven't found any solution yet.

**Comment by Aides359** [comment]
As a quick workaround setting `"devtool": "eval"` in `webpack.config.js` makes the build run again.

However a proper solution is needed.

**Comment by kamalkech** [comment]
@Aides359 : i can't find webpack.config.js in root folder of project

**Comment by thatguywithcamera** [comment]
@kamalkech 'ng eject' should have generated webpack.config.js at your root.

I am having this exact issue as well.. Trying to override the default url-loader for .cur and .ani files and I thought I found the solution with ng eject but alas.... hopefully this issue is the last hurdle..

**Comment by jackytse** [comment]
Don't write two or more classes in the same ts file. I think it's a bug of 'source-map'.

**Comment by Aides359** [comment]
I am 100% sure that I have no file with more than one class in it.
If anything it is a problem with import/export and not with class declarations.

**Comment by jackytse** [comment]
Maybe you can try this solution.

[http://stackoverflow.com/questions/41907409/typeerror-cannot-read-property-substr-of-undefined-source-node-js](url)

**Comment by Aides359** [comment]
That's it!

PS: @jackytse your link is not referencing the correct target

**Comment by jackytse** [comment]
I'm sorry.

[http://stackoverflow.com/questions/41907409/typeerror-cannot-read-property-substr-of-undefined-source-node-js/41923610](url)

**Comment by mactr0n** [comment]
We have exactly the same problem. Under macOS 10.12 it's working find but under Windows 7 the error described above arises.

**Comment by clydin** [comment]
CLI 1.0 prerelease versions are no longer supported. If this error still occurs on the latest version (6.1.4 currently). Please open a new issue describing the problem.
