### ISSUE TITLE
Compress production build

### ISSUE THREAD

**Issue by Anufriev** [angular/angular-cli#4909]
### OS?
> Windows 10

### Versions.
@angular/cli: 1.0.0-beta.32.3
node: 6.9.5
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

### Repro steps.

- ng new
- ng build -t=production -e=prod

### Mention any other details that might be useful.

dist folder contains .js files but js.gzip files are missing.

**Comment by Ionaru** [comment]
"@angular/cli: compressed output (.gz) is no longer generated on production builds."

From the changelog: https://github.com/angular/angular-cli/blob/master/CHANGELOG.md

**Comment by Anufriev** [comment]
Thanks. I missed it.

**Comment by gedclack** [comment]
@Ionaru @Anufriev and how do we do the compression now from cli ?
using Angular + Material 2, with `ng build --prod --aot` my simple app still produce total size of 1.3MB.
*super-noobie here
