### ISSUE TITLE
Cross domain

### ISSUE THREAD

**Issue by YealZoy** [angular/angular-cli#4910]
+ how I set cross domain? help me,if I can see the file of `webpack.config.js`,I can do it, but I just see the file of `protrator.conf.js`
this is my `protrator.conf.js`,if everybody find some problems,please tell me,you are a good person,the god like you!!!!!!!!!!
```javascript
// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/docs/referenceConf.js

/*global jasmine */
var SpecReporter = require('jasmine-spec-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    './e2e/**/*.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  webDriverProxy: 'http://130.10.7.123:8080',
  useBlockingProxy: true,
  blockingProxyUrl: '/api'
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  useAllAngular2AppRoots: true,
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e'
    });
  },
  onPrepare: function() {
    jasmine.getEnv().addReporter(new SpecReporter());
  }
};

```

**Comment by Wykks** [comment]
I have no idea what you're talking about, but if you want to access `webpack.config.js`, then just `eject` from angular-cli
https://github.com/angular/angular-cli/blob/master/docs/documentation/eject.md

**Comment by filipesilva** [comment]
I'm sorry but I can't figure out what you want to do here. Please open a new issue and fill in the template.
