### ISSUE TITLE
ng build doesnt work

### ISSUE THREAD

**Issue by zolekm** [angular/angular-cli#4911]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX

### Versions.
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.32]
node: 7.5.0
os: darwin x64
@angular/cli: 1.0.0-beta.32.3
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/compiler-cli: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8

### Repro steps.
Start ng build command and then there was an error

### The log given by the failure.
10% building modules 6/6 modules 0 active(node:64841) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
 86% hashingcrypto.js:74                                                                   
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:74:16)

### Mention any other details that might be useful.
When i try to use ng build method it throws an error

**Comment by zolekm** [comment]
https://github.com/webpack/webpack/issues/4072#issuecomment-278626604

**Comment by renjit00** [comment]
Hi,
how do you resolve the issue.even i got the same. don't know how to resolve it,please lead

**Comment by zolekm** [comment]
@renjit00 the problem was wrong import in one of the project file, answer here: https://github.com/webpack/webpack/issues/4072#issuecomment-278626604
