### ISSUE TITLE
How to turn off generating chunk files during `ng build --prod`?

### ISSUE THREAD

**Issue by webcat12345** [angular/angular-cli#4912]
### OS?
 Ubuntu14.04

### Versions.
 angular-cli: 1.0.0-beta.26
node: 7.2.1
os: linux x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6

### 1.*.chunk.js ~  is the problem we are getting.
 I have to inject generated js files to other index.html.
In this case all these js files are not in the root. As result when I tried on server it does not find 1.*.chunk.js from localhost:9000/

Is there any way to turn off generating chunk files? only generate vendor, inline, main .
It is okay that they have large size.

Please help me to solve this issue.

Thank you very much!

**Comment by Mage111** [comment]
Maybe you need to add the .js type (text/javascript or application/javascript) to site mime types

**Comment by webcat12345** [comment]
Could you please let me know more details?

**Comment by deebloo** [comment]
Chunks are created when lazy loading modules. If you don't lazy load you should get no chunks

**Comment by grizzm0** [comment]
You might want to update to beta 32.3 and try again. Beta 26 is quite old.

**Comment by filipesilva** [comment]
Closing as answered by @deebloo. Simply remove lazy loading from your code and you will not have extra chunks.
