### ISSUE TITLE
Reusing/caching pre-compiled artifacts between build/serve

### ISSUE THREAD

**Issue by victornoel** [angular/angular-cli#4915]
I saw there was multiple issues related to performance, but I couldn't find any related to this use case.

Basically, in my CI, I need to run multiple things:
 - e2e tests (i.e., running `ng serve --prod` with a specific environment)
 - a `build --prod` with a given environment
 - another `build --prod` with another environment

So each of these are very similar except for the environment, and compiling each of these takes more or less 2 or 3minutes.

I was wondering if it wouldn't be interesting to reuse the artifacts between each of these builds instead of only working in memory. A bit like what is done with the rebuild of `ng serve`.

**Comment by janostik** [comment]
Might be related to #4875

**Comment by victornoel** [comment]
@janostik yes, this is totally related!

It's a bit different, because I don't want to reuse exactly the same build but a slight variation of it (because of the environment).

**Comment by filipesilva** [comment]
I think this is an interesting idea, although I can't quite imagine how that would actually be implemented.

**Comment by mgechev** [comment]
webpack 5 will introduce disk cache. Bazel already does. This will be implemented but no need to be tracked by this issue.
