### ISSUE TITLE
ng build --prod Mix Up The Page Style-Sheet

### ISSUE THREAD

**Issue by Mage111** [angular/angular-cli#4921]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 7, 8 or 10. 

### Versions.
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.15]
node: 6.9.5
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/compiler-cli: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3

### Repro steps.
Upgrade angular/cli version to latest. 

>------------------------------------------------------------------------
 The build works fine, but when I load the site, many of css declaration (not all of them) doesn't appear.
I using scss files. and it seems that there is problem with the bundle creating.
> Thanks! We'll be in touch soon.

**Comment by chancleta** [comment]
It sounds to me like if you are not importing the scss files to the main scss (unless they are imported by a component of course)

**Comment by Mage111** [comment]
All scss files are imported. All worked fine. It nixed up since I upgraded to latest angular/cli (@angular/cli 1.0.0-beta.32.3), and only when doing `ng build --prod`. (`ng build` works well)

**Comment by Mage111** [comment]
OK, I found the reason, Its a bug! 
It happened because we moving the `ViewEncapsulation` from  each component to global declaration in `main.ts` file
Apparently` build --prod `do not support this option.

If I put the following code one time in main.ts- it doesn't work:
`platformBrowserDynamic().bootstrapModule(AppModule, { defaultEncapsulation : ViewEncapsulation.None});`
I must to write if for each component.

**Comment by filipesilva** [comment]
Closing as it seems you figured it out. AOT (prod does AOT by default) doesn't support that I think.
