### ISSUE TITLE
css problem on component

### ISSUE THREAD

**Issue by feof** [angular/angular-cli#4922]
macos 10.12
angular cli 1.0.0 beta 32.3
angular 2.4.8

Hi all. I have a problem, perhaps I'm wrong. If I write in app.component.css:
body{
  background-color: black !important;
}

I find the css inline in the head of view but it is not applied.
The inline css is:
<style>body[_ngcontent-oht-0]{
  background-color: black !important;
}</style>

the body element is:
<body cz-shortcut-listen="true">

why is this happening?
Tnx.

**Comment by beeman** [comment]
@feof this question is not related to Angular CLI. It probably makes more sense to ask this on StackOverflow.

**Comment by clydin** [comment]
I'd suggest reading through the angular documentation related to view encapsulation:  https://angular.io/docs/ts/latest/guide/component-styles.html#!#view-encapsulation

**Comment by filipesilva** [comment]
Closing as answered by @beeman and @clydin, thanks!
