### ISSUE TITLE
ng build passes with scss errors

### ISSUE THREAD

**Issue by paulbota** [angular/angular-cli#4925]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10

### Versions.
@angular/cli: 1.0.0-beta.32.3 [1.0.0]
node: 6.9.5
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.32.3

### The log given by the failure.

The ng build passes and no warning or error is shown while having invalid scss files. Same happens for serve.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by tscheinecker** [comment]
this is incredibly annoying in a CI environment
having the build pass with exit code 0 although errors exist is really bad

**Comment by filipesilva** [comment]
I understand this might be annoying but not bothering to fill the template or giving reproduction steps isn't really helpful. Please open a new issue and fill in the template.
