### ISSUE TITLE
Integrated angular 2 component library with angular/cli throws an error

### ISSUE THREAD

**Issue by nicolae536** [angular/angular-cli#4926]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-beta.32.3
node: 6.9.5

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

> The app was created with the cli, and his purpose is to present a library. And the purpose of the library
> is work fine with the cli/webpack/systemjs
> Clone this [repository]( https://github.com/nicolae536/nicolae536.github.io/tree/develop/ng2-tools.io),
> Run npm install and the npm run ng serve.
> In the console you will receive the following error.

    `ERROR in Ng2ToolsModule is not an NgModule`

> If you enter in app.module.ts erase one module and add it again the application compiles fine.
> And the error is lost, Biggest problem is that I cannot build the application.

> 
Ng2ToolsModule is part of a library called ng2-tools created and published by me. Here is a link with the [repository](https://github.com/nicolae536/ng2Tools) . Is this a cli bug or a library build bug ? Let me kow how I should change the build for the library to just work with the cli, if the problem comes from my build.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I think this is due to your lib not being AOT ready. Unfortunately there really aren't good instructions for that right now.

The best I can point you to is https://github.com/angular/angular-cli/issues/1692#issuecomment-285363067, it has a link to a WIP aot lib guide.
