### ISSUE TITLE
ng build -prod/production build no longer gzipping files

### ISSUE THREAD

**Issue by chancleta** [angular/angular-cli#4936]
> Please provide us with the following information:

### OS?
Ubuntu 16.04

### Versions.
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.28.3]
node: 6.9.5
os: linux x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

### Repro steps.
 ng build -prod / ng build --target=production

![image](https://cloud.githubusercontent.com/assets/2196905/23234180/9ac2245c-f927-11e6-9b50-5d4e65a65b70.png)

**Comment by delasteve** [comment]
Unfortunately, gzip is no longer supported as of `beta.32`.

https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#breaking-changes

**Comment by chancleta** [comment]
thanks @delasteve

**Comment by abcfy2** [comment]
Thanks. But why? Gzip_static is a very good feature, why removed?

**Comment by delasteve** [comment]
@abcfy2 You can find the answer to your question here: https://github.com/angular/angular-cli/pull/4618#issuecomment-279175818
