### ISSUE TITLE
GZip Files missing in Beta 32

### ISSUE THREAD

**Issue by JPM84** [angular/angular-cli#4945]
Production builds with Beta 32 don't seem to produce a gzip version anymore. Is there a reason for this change?

### OS?
> Mac OSX (El Capitan)

### Versions.
> 1.0.0-beta.32.3

### Repro steps.
> Run ng build --prod

### The log given by the failure.
> None

### Mention any other details that might be useful.
None

**Comment by grizzm0** [comment]
They were removed in #4702. The PR and the linked PR has plenty of answers on why.

**Comment by filipesilva** [comment]
Closing as answered.

**Comment by JPM84** [comment]
Thanks for the quick answer! I did a search but could find it.
