### ISSUE TITLE
Cannot use ng new to create a new project

### ISSUE THREAD

**Issue by bvaissade** [angular/angular-cli#4946]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
`Windows 10 (32 bits)`

### Versions.
```
@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: win32 ia32
```

### Repro steps.
I want to create a new project with : `ng new myproject`

### The log given by the failure.
Impossible ! Show error  

`The "ng new" command requires a name argument to be specified. For more details, use "ng help".`

### Mention any other details that might be useful.
Try to uninstall and reinstall angular cli without succés

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rinoldit** [comment]
try installing new version of nodejs and install angular-cli 
click this link which helped me to get latest version of nodejs https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

**Comment by bvaissade** [comment]
Thanks but my PC is on Windows 10 !
My nodejs version is 7.5.0.

**Comment by ArielSaldana** [comment]
Hey, can you try : 

``` 
ng new <name>
```

**Comment by bvaissade** [comment]
I update to 1.0.0-rc-0 : (uninstall and clean re-install)

```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0-rc.0
node: 7.5.0
os: win32 ia32
```

Still the same error 

`The "ng new" command requires a name argument to be specified. For more details, use "ng help".`

Same problem with `ng generate`...

**Comment by filipesilva** [comment]
I can't reproduce this myself:

```
kamik@T460p MINGW64 /D/sandbox
$ ng new myproject
installing ng
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Successfully initialized git.
Installing packages for tooling via npm.
```

I have no idea why your system seems to have a problem with those commands. If you have any hint I'll try to repro.

**Comment by mackelito** [comment]
@filipesilva just a quick question...
The file "tsconfig.json" should it not be "tsconfig.app.json"?

**Comment by sumitarora** [comment]
@bvaissade Are you still facing the issue? If yes please reopen the issue with more details.

**Comment by skyfall947** [comment]
Please, somebody solucion this??
