### ISSUE TITLE
Support for html 5 push state in servers

### ISSUE THREAD

**Issue by zwolej** [angular/angular-cli#4948]
So I wonder is there any help in configuration angular cli with html 5 push state to common application servers. I found out working solutions for web servers like nginx but what about deploying angular as war to some application servers like JBOSS? 
I found some wird solution but I need to explicitly put there files that the should't be redirected to index.html like:

     "/assets/",
     "/favicon.ico",
     "/inline",
     "/main",
     "/styles",
     "/vendor",
     "/polyfills",

and second it would be great to create some documentation for those files generated in prod env. In one version of angular-cli vendor.*.js is generated in another not, one time polyfills.*.js are generated in another one not and it is kinda confusing.

**Comment by filipesilva** [comment]
The CLI isn't a production server. It just builds a static app that you then deploy to your servers.
