### ISSUE TITLE
keep angular cli development application running in the background on the server ?

### ISSUE THREAD

**Issue by helxsz** [angular/angular-cli#4951]
I am running a angular cli development on a remote server, would it possible to run this development application in daemon mode? like what we use in forever.js

thanks in advance!!

**Comment by Meligy** [comment]
The CLI serve feature is only for development. It does not support production server scenario. If you run `ng serve -prod` you'll get a warning about that.

The typical story is that you run `ng build -prod`, and then take the `dist` (or whatever your output folder is) and serve it under any server program you like (Apache, nginx, IIS, etc.). At the end of the day, this is a folder of just static files, so, it doesn't have any special server requirements.

**Comment by filipesilva** [comment]
Closing as answered by @Meligy, thank you!

**Comment by samehelhawary** [comment]
you can use the following command to run ng with forever

`forever start node_modules/@angular/cli/bin/ng serve`

**Comment by melvinmoses123** [comment]
its running in local host only. What I do to make it on ip address.

**Comment by samehelhawary** [comment]
`forever start node_modules/@angular/cli/bin/ng serve --host {ip_address or domain} --prod`

**Comment by kingNoOne** [comment]
And what is the command if I want to stop the infinite running server?

**Comment by melvinmoses123** [comment]
You can use 

> forever stop <Id|Uid|Pid|Index|Script> 

for a particular server or 

> forever stopall

to stop all servers starting using forever.

**Comment by bbmattieu9** [comment]
How do i make angular run indefinitely on the server? With forever.
