### ISSUE TITLE
[Documentation] Information about proxy

### ISSUE THREAD

**Issue by marciomsm** [angular/angular-cli#4953]
I started using CLI Angular three weeks ago and at that time I had information about proxy configuration, but now I can not seem to find it anymore. Have information been removed from the documentation? Does anyone know why? Thanks.

**Comment by filipesilva** [comment]
Heya @marciomsm, documentation was moved to the wiki but there was a period of time where links weren't set up.

You can find the proxy docs at https://github.com/angular/angular-cli/wiki/stories-proxy

**Comment by marciomsm** [comment]
Thank you!
