### ISSUE TITLE
Question:  How do you exclude a module from code coverage when running unit tests?

### ISSUE THREAD

**Issue by daBishMan** [angular/angular-cli#4958]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10. 

### Versions.
@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/compiler-cli: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/platform-server: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3

### Repro steps.
> I am trying to exclude files from code coverage results.

### The log given by the failure.
> no failures.

### Mention any other details that might be useful.
We have code that we would like to exclude from code coverage when running unit tests.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by delasteve** [comment]
When RC is released you will be able to configure the following section in the `.angular-cli.json` file:

```json
"test": {
  "codeCoverage": {
    "exclude": ["glob/to/ignore"]
  },
  ...
}
```

**Comment by hansl** [comment]
Fixed in master.

**Comment by daBishMan** [comment]
Thank you so much for your update.   I will wait on RC. 

Thanks for all your hard work.
