### ISSUE TITLE
Feature: Add --out flag to ng lint

### ISSUE THREAD

**Issue by philipooo** [angular/angular-cli#4959]
# Use-case
In our CI we use SonarQube and the TypeScript plugin which can parse the tslint output and translate it into issues. To generate the output I want to use `ng lint`.

# Request
Because there is no way to store the output of `ng lint --format json` into a valid json file it would be useful to add the `--out` argument and pass it to tslint.

**Comment by clydin** [comment]
The next release will allow you to properly redirect the output to a file.
ref: https://github.com/angular/angular-cli/pull/4917

**Comment by filipesilva** [comment]
Closing as answered. Thanks to @moritz-h for implementing it!

**Comment by philipooo** [comment]
Awesome. Thank you!

**Comment by moritz-h** [comment]
@filipesilva @clydin @philipooo 
Thanks for mentioning my fix. But this was only the easy small part I did. There is a even bigger issue for using ng lint formatted output in CI. See #4849. There I found the error source, but I don't know how it could be fixed. I just have a workaround for pmd format:
```sh
ng lint --format pmd > result.xml
tr -d '\n' < result.xml > result-fix.xml # all text in one line for sed
sed -i -e 's/<\/pmd><pmd version="tslint">//g' result-fix.xml # fix xml
```

**Comment by denisharder** [comment]
Hello, which release has the --out option in? I can't seem to find it in the code.
I don't see it within the latest beta tag:
https://github.com/angular/angular-cli/blob/v1.5.0-beta.2/packages/%40angular/cli/commands/lint.ts

**Comment by LayZeeDK** [comment]
Thanks for the workaround, @moritz-h. I had some trouble on Windows but got it working with two commands:

    ng lint --format pmd > result.xml
    sed -i -r -n -e "/<pmd version=\"tslint\">/,${p}" result.xml

**Comment by moritz-h** [comment]
@LayZeeDK The problem with messed up xml is fixed long time ago. See the issue I referenced above.
The `tr` and `sed` workaround is not needed anymore, just do:
```
ng lint --format pmd > result.xml
```

**Comment by siegenthalerroger** [comment]
This was never actually added from what I can see, please revisit this. It would be a great simplification.

**Comment by GregorioPerego** [comment]
It would be really great to have that "--output" option.

Right now the only possibility to store the tslint result in a file is by redirecting standard output stream to a file, but it sometimes includes the ANSI escapes (colors) in the generated file, making the file not well-formatted. Example:
`ng lint wp --format checkstyle --force > ../target/tslint-result.xml`

Thanks

**Comment by westonpace** [comment]
@GregorioPerego It appears redirecting to a file is the intended way to do this.  The fix mentioned above by @moritz-h was to enable that.  If the format is non-human readable and there are illegal characters in the output then that would be a separate bug on it's own.

**Comment by rtaft** [comment]
`ng lint --format json > lint.json`
The content of the file is not json as all the other log output is there.  --silent hides the json and leaves the debug output.

**Comment by westonpace** [comment]
@rtaft I think you are encoutnering https://github.com/angular/angular-cli/issues/12674

**Comment by rtaft** [comment]
@westonpace yes, that sounds about right, thank you
