### ISSUE TITLE
Angular cli -ng build's bundles doesn't work in production

### ISSUE THREAD

**Issue by phani257** [angular/angular-cli#4965]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows Server 2012
### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
28.3

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Yes using CLI. No other changes.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

I have generated a new app using angular cli. I used ng build to bundle the application and hosted it on my local machine. The app works fine. When I use this bundles to host it on my dev server, the app doesn't work. It shows loading. Do I need to install anything over there?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ctrl-brk** [comment]
Check out your console output, it there any errors?

**Comment by phani257** [comment]
![image](https://cloud.githubusercontent.com/assets/25534790/23270817/2317e364-f9c3-11e6-9169-82de376401f8.png)

**Comment by markheron91** [comment]
This is the same looking error that happens when you try and run angular on a too old version of IE (<10). Make sure you are not accidentally running compatibility mode in the emulation tab in the dev tools for something IE9 and before.

**Comment by filipesilva** [comment]
It looks like you're missing polyfills for the browser you're using in your server. Check out the `src/polyfills.ts` files.
