### ISSUE TITLE
Provide specific scopes in contributing guidelines

### ISSUE THREAD

**Issue by comewalk** [angular/angular-cli#4967]
This repository runs tests on Travis CI and AppVeyor. Although checking commit message, no one provides specific scopes in CONTRIBUTING.md.

> ### Scope
> The scope could be anything specifying place of the commit change. For example
> `Compiler`, `ElementInjector`, etc.

Actually [validate-commit-message.js](https://github.com/angular/angular-cli/blob/master/scripts/validate-commit-message/validate-commit-message.js) checks scopes. If someone write wrong scopes in commit message, Travis CI and AppVeyor will fail. (me, too. at [build #6536](https://travis-ci.org/angular/angular-cli/jobs/204657564))

It's about time to provide specific scopes in CONTRIBUTING.md.
It looks like below.
```
### Scope
The scope could be anything specifying place of the commit change.
* @angular/cli
* @ngtools/json-schema
* @ngtools/logger
* @ngtools/webpack
* packaging
* changelog
```

Any thought?

**Comment by clydin** [comment]
A documentation update is in progress.

**Comment by comewalk** [comment]
@clydin sounds good 👍
