### ISSUE TITLE
Deep import references - not yarn friendly

### ISSUE THREAD

**Issue by AlexanderVangelov** [angular/angular-cli#4968]
Is there any chance to avoid deep import references, so the cli will be [yarn](https://yarnpkg.com) compatible?

For example the following code [tasks/e2e.ts#L43](https://github.com/AlexanderVangelov/angular-cli/blob/master/packages/%40angular/cli/tasks/e2e.ts#L43):
`// webdriver-manager can only be accessed via a deep import from within
// protractor/node_modules. A double deep import if you will.
  const webdriverUpdate = requireProjectModule(projectRoot,
    'protractor/node_modules/webdriver-manager/built/lib/cmds/update');`

is raising:
Error: Cannot find module 'protractor/node_modules/webdriver-manager/built/lib/cmds/update'
(yarn keeps only the `.bin` cmd refs inside `protractor/node_modules/`)

Thank you.

**Comment by cacogr** [comment]
related https://github.com/angular/angular-cli/pull/4597

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/4597
