### ISSUE TITLE
"ng test" is failing when using symbol alias

### ISSUE THREAD

**Issue by magrabow** [angular/angular-cli#4970]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

MacOS (Sierra)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
@angular/cli: 1.0.0-beta.32.3
node: 6.9.1
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

* create new project `ng new example`
* add *googlemaps* typings `npm i @types/googlemaps --save-dev`
* in *app.component.ts* add method `foo() { const b = new google.maps.Marker(); }`
  *  so far so good, both `ng serve` and `ng test` produce no errors
* now since we will have this marker all over our app, we want to shorten its type, so above the component *App* we add symbol alias: `import Marker = google.maps.Marker;` and change our method *foo* to: `foo() { const b = new Marker(); }`
  * and now `ng serve` is still working, but `ng test` starts failing with an error (log below).

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
Chrome 56.0.2924 (Mac OS X 10.12.3) ERROR
  Uncaught ReferenceError: google is not defined
  at webpack:///src/app/app.component.ts:3:0 <- src/test.ts:64807
```

### Mention any other details that might be useful.

* It's natural that the saved typings for *googlemaps* contain only type information not the actual information, so one question is what would be the best way to provide mocks for tests? The running app of course loads the actual google maps implementation (using `script` tag).
* A bit unclear thing here is that `ng test` is starting to fail only if both the import is used and the imported class is being actually used. Following implementation of method *foo* (when using import): `foo() { const b: Marker = null; }` produces no errors for `ng test`.
* I am not sure if this is actually caused by `angular-cli` lib itself, but it looks like most reasonable place to report this issue.

Thanks!

**Comment by mattdistefano** [comment]
> in app.component.ts add method foo() { const b = new google.maps.Marker(); }
> so far so good, both ng serve and ng test produce no errors

I take it you're not actually invoking `foo` in any of your tests? I imagine if you were, you'd find the same issue - there's just not a `google` variable in scope.

**Comment by magrabow** [comment]
Indeed, the method is not invoked at all.

_BTW finding a good way to provide runtime mocks for these `google.*` classes in tests is a different (unanswered) question, but not strictly part of the issue reported._

**Comment by mattdistefano** [comment]
TBH I'd say it's kind of the same question/issue - the absence of a google object (with a .maps property) is the problem in both cases, you just don't notice it within foo because that code won't execute until foo is invoked, whereas the (transpiled) import is executed (and fails) immediately.

**Comment by mattdistefano** [comment]
Which is to say, if you just had a `var Marker = google.maps.Marker;` at the top of your file, the test would probably fail in the same way.

**Comment by magrabow** [comment]
@mattdistefano thanks to your hint I figured out a way to provide mock implementation that works. I did that by adding below code to `test.ts` that is part of *Angular CLI* project scaffold:
```
global['google'] = {
  maps: {
    Marker: class {
      // mock implementation ...
    }
  }
};
```

But... this looks like a bit of hack, even if we pull out the mocks to a separate file...
 
So, I am wondering if handling such case in a particular way should be made part of *Angular CLI* guidelines? Similar to the case of, for example, adding *polyfills* which is nicely prepared for use and described in the scaffold. Granted, that this use case will be less frequent than using *polyfills*, but once someone comes across it, it's quite tricky to solve.

**Comment by mattdistefano** [comment]
Re. moving to a separate file - you can use the karma.conf `files` array for that or do some sort of `import './mocks'` from another file.

Re. what the CLI should do - I'm not sure it's realistic to expect it to provide mocks. It provides the polyfills since those are largely the dependencies of angular itself, but the mocks are really specific to your application, your testing style, etc.

**Comment by magrabow** [comment]
@mattdistefano Well, to some extent I agree, but I believe that to some extent it could concern the **CLI** itself. Of course, the testing style could vary among people, but even the solution that you provided is - I believe - against the recent updates in the **CLI**, where the *karma.conf* `files` entry is now just:
```
files: [
      { pattern: './src/test.ts', watched: false }
    ]
```

So I believe the intention of the authors was to move all customisation from the `files` entry itself to the `test.ts` file which is being loaded. But that is just my assumption, having at least some sort of guideline would be imho helpful, as it would allow to better align with potential future development of the scaffold generated by **CLI**.

**Comment by mattdistefano** [comment]
Yeah I agree the documentation could offer some better guidance here.

Re. the karma.conf file - my general read on the situation is that if the CLI emits a config file at all, you as an end user are welcome to modify it.

**Comment by mattdistefano** [comment]
I should add, this is only really an issue for objects that are expected to exist in the global scope rather than being managed by angular's DI. If you're dealing with, say, an injected service, you can easily mock within your spec file. So possibly another way to solve this is by wrapping the google maps global as an angular provider, injecting that into your classes, and providing the mock when setting up your test module in your spec file.

**Comment by filipesilva** [comment]
The core of your problem is that you're using a script tag to import google maps in your app. That script tag is nowhere to be found in tests though.

If you add it to the `scripts` array in `.angular-cli.json` instead, tests will load it as well.

**Comment by magrabow** [comment]
This is rather not feasible in unit tests, mocking looked like a better solution and it worked nicely. 
No problems with closing this issue, thanks!
