### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. When performing a production build

### ISSUE THREAD

**Issue by evkw** [angular/angular-cli#4976]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-beta.32.3
node: 6.9.5
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

- Sample project made with issue https://github.com/evkw/StaticProdBuildIssue
- run ng b command, should compile and work without any issue
- run ng b --prod, get error detailed in below stack trace

### The log given by the failure.
> Normally this include a stack trace and some more information.

 10% building modules 4/6 modules 2 active ...StaticProdBuildIssue\src\polyfills.ts(node:21508) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: f0511f1d2473b3eacea7
Time: 8221ms
chunk    {0} polyfills.6133e549b3f9773e274f.bundle.js (polyfills) 153 kB {4} [initial] [rendered]
chunk    {1} main.2f25ef73d45f3ebfcc67.bundle.js (main) 781 bytes {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.3fd0c0039e2fea7797fb.bundle.js (vendor) 835 kB [initial] [rendered]
chunk    {4} inline.3c16ee6bf5fc3db5d011.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Calling function 'makeValueProvider', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol GenericInputComponent in C:/Development/Prototypes/StaticProdBuildIssue/src/app/shared/generic-input/generic-input.component.ts, resolving symbol GenericInputComponent in C:/Development/Prototypes/StaticProdBuildIssue/src/app/shared/generic-input/generic-input.component.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Development\Prototypes\StaticProdBuildIssue\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

### Mention any other details that might be useful.

This code used to work fine in while building in prod mode via older versions of the CLI (1.0.0-beta.16)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by EliaRohana** [comment]
same issue with me on 1.0.0-rc.0 version

**Comment by evkw** [comment]
Apparently its an AOT issue.

Using this build command i was able to build and serve in prod

ng build --prod --aot false
