### ISSUE TITLE
Wrong ng lint warning for inherited component properties: the property "xxxx" that you're trying to access does not exist in the class declaration.

### ISSUE THREAD

**Issue by mmc41** [angular/angular-cli#4978]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Max OS X El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-beta.32.3
node: 7.4.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

The app was created with the CLI. It also uses component inheritance, where a base class declares properties that many component classes inherits from. App works fine at runtime but the "ng lint" command does not inspect subclasses so it wrongly gives a warning like the one below:

/myt.component.html[5, 85]: The property "xxx" that you're trying to access does not exist in the class declaration.

**Comment by delasteve** [comment]
This looks like a `codelyzer` issue. You should be able to see the same thing by running 

```bash
./node_modules/.bin/tslint --project=./src/tsconfig.app.json
```

I just tested it with `BarComponent` inheriting from `FooComponent` that has `foo` property and got

```
/Users/stephencavaliere/development/test-lint/src/app/bar/bar.component.html[1, 3]: The property "foo" that you're trying to access does not exist in the class declaration.
```

**Comment by ctrl-brk** [comment]
https://github.com/mgechev/codelyzer/issues/191

**Comment by filipesilva** [comment]
Closing as a codelyzer issue.
