### ISSUE TITLE
CLI compiles lazy loaded html, but no ts files

### ISSUE THREAD

**Issue by cre8** [angular/angular-cli#4981]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-beta.32.3
node: 7.5.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Lazy Loaded Module that loads correctly
Updated cli to latest version (fresh install and then copying the src folder)

### The log given by the failure.
> Normally this include a stack trace and some more information.
Every time when I change one of the ts files of any lazy loaded Module (component, service), I have to run `ng serve` again. Can't remember to do it this often with `.30`. But html and css files will be updated every time.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by darksniper87** [comment]
I'm surprised that no one noticed this bug with the latest angular-cli update.

**Comment by anabulsi** [comment]
Me and my colleague are both having this issue since we upgraded to beta 30. We even don't use lazy loading. Whenever we modify a ts file, we have to terminate cli and run ng serve again. This happens only when modifying ts files. We are both on Windows 8 machines

**Comment by darksniper87** [comment]
Are you using Webstom/IntelliJ IDE?

**Comment by anabulsi** [comment]
using VS Code while running ng serve in the background

**Comment by darksniper87** [comment]
The issue on WebStorm was that when I was saving a file, the changes where saved on a temp file and after successful save, the temp file was replacing the original one. So when I was making changes, the webpack would see that original file was not modified because my IDE was saving the changes on a temp file.

Disabling this behavior solved this issue. Of course now in Visual Code Studio I don't know what the issue could be. I don't think it's the same case as mine.

**Comment by cre8** [comment]
@darksniper87 , I use WebStrom too. Which settings have you changed to disable the temp file?
