### ISSUE TITLE
`ng e2e --environment=foo` doesn't work as expected

### ISSUE THREAD

**Issue by tsabirgaliev** [angular/angular-cli#4982]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX Sierra

### Versions.
> @angular/cli: 1.0.0-beta.32.3
> node: 6.9.5
> os: darwin x64
> @angular/common: 2.4.8
> @angular/compiler: 2.4.8
> @angular/core: 2.4.8
> @angular/forms: 2.4.8
> @angular/http: 2.4.8
> @angular/platform-browser: 2.4.8
> @angular/platform-browser-dynamic: 2.4.8
> @angular/router: 3.4.8
> @angular/cli: 1.0.0-beta.32.3
> @angular/compiler-cli: 2.4.8

### Repro steps.
> ng new my-app; cd my-app; ng e2e --environment=prod

**Comment by clydin** [comment]
Can you provide some additional information?What are you expecting and what is actually happening?

**Comment by tsabirgaliev** [comment]
@clydin I'm importing environment in e2e tests like this:

    import { environment } from '../src/environments/environment';
    console.log(environment);

and expect the actual environment imported to depend on `--environment` flags

**Comment by filipesilva** [comment]
@tsabirgaliev environment replacement only works in your app and unit tests. e2e tests are their own separate app, outisde webpack, and do not support that feature.

**Comment by kklear** [comment]
Hello,

and how we will make e2e tests for all the different environments that we have if it accepts by default only the enviroment.ts?

**Comment by jozzhart** [comment]
I was able to get it working, details here.

https://stackoverflow.com/questions/45330680/how-to-run-protractor-e2e-tests-using-different-angular-environment-variables

**Comment by SirWojtek** [comment]
I confirm: `ng e2e` works with `-e` or `--environment` flag with CLI in version `1.5.5`.

**Comment by denyo** [comment]
The `e2e` docs state 
> Please note that options that are supported by ng serve are also supported by ng e2e

And from the `serve` docs
> --environment (aliases: -e)
> Defines the build environment.

But when I do `ng e2e --environment prod` he is still picking up the `test` environment. It looks like the CLI is checking but ignoring it since
```
ng e2e --environment whatever
Environment "whatever" does not exist.
```

**Comment by thilo-fester** [comment]
IMHO its working partly. The server is starting and providing the environment to the app but it is not available in e2e tests.

**Comment by tgallimore** [comment]
Any update on this? I'm trying to use `ng e2e --environment mock` and it's using `environment.dev.ts`. 

Versions

```
"dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.2",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "protractor": "~5.1.2"
  }
```
