### ISSUE TITLE
Scss Preprocessor doesn't include all the vendor prefixes

### ISSUE THREAD

**Issue by levaigabor** [angular/angular-cli#4985]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.9.1
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/compiler-cli: 2.4.7

### Repro steps.
> just run ng serve

### The log given by the failure.
> I'd like to include all the  vendor prefixes for css3 properties, that are declared in a 'mixins.scss' file, and I use @include(css3property) to include these prefixes. When run ng serve, the compiler doesn't include all of the prefixes. I double checked the file, but there is no problem with the declaration, for example the node-sass compiler does include the prefixes.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks in advance! If you need more detail, please let me know.

**Comment by mattdistefano** [comment]
autoprefixer will remove outdated prefixes. Try setting up a [browserslist](https://github.com/ai/browserslist) to specify which browsers you want to support.

Also since the CLI uses autoprefixer anyway, you might as well just write non-prefixed CSS and let it add prefixes.

**Comment by levaigabor** [comment]
@mattdistefano Thanks a lot! It works perfectly now
