### ISSUE TITLE
[FEATURE REQUEST] Should be able to import raw TypeScript files from npm

### ISSUE THREAD

**Issue by QuantumInformation** [angular/angular-cli#4986]
Demo was created using cli  1.0.0-beta.24

**Current behavior**
Try to import npm module with raw ts files like so:

https://github.com/QuantumInformation/angular-finance/blob/master/src/component.ts#L2

ng serve shows error:
```
ERROR in ../src/component.ts
Module not found: Error: Can't resolve 'vanilla-typescript' in '/Users/nikos/WebstormProjects/angular-finance/src'
```

**Expected behavior**
Compiles the external module with no extra steps

**Minimal reproduction of the problem with instructions**
this demo project: https://github.com/QuantumInformation/angular-finance/tree/master/demo

**What is the motivation / use case for changing the behavior?**

We really should be able to use native ts libs. here is a successful example:
https://github.com/quantumjs/solar-popup/blob/master/src/SolarPopup.ts#L2
https://github.com/quantumjs/solar-popup/blob/master/webpack.config.js#L26

the npm lib main:
https://github.com/quantumjs/vanilla-typescript/blob/master/package.json#L5

**Please tell us about your environment:**
Mac OSX

* **Angular version:** 2.3.1

originally raised https://github.com/angular/angular/issues/14704

**Comment by mattdistefano** [comment]
You sure this doesn't work? I couldn't get your demo project to run, but I just added `import { KeyCodes } from 'vanilla-typescript';` to one of my projects and it built without issue.

**Comment by QuantumInformation** [comment]
I'm upgrading my cli to check

**Comment by QuantumInformation** [comment]
I upgraded it all to latest and now I get:
```
ERROR in Error encountered resolving symbol values statically. Could not resolve money-input relative to /Users/nikos/WebstormProjects/angular-finance/demo/src/app/app.module.ts., resolving symbol AppModule in /Users/nikos/WebstormProjects/angular-finance/demo/src/app/app.module.ts, resolving symbol AppModule in /Users/nikos/WebstormProjects/angular-finance/demo/src/app/app.module.ts

ERROR in /Users/nikos/WebstormProjects/angular-finance/demo/src/app/app.module.ts (7,26): Cannot find module 'money-input'.)

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'money-input' in '/Users/nikos/WebstormProjects/angular-finance/demo/src/app'
 @ ./src/app/app.module.ts 12:0-41
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
webpack: Failed to compile.

```

**Comment by QuantumInformation** [comment]
Upgrading the cli fixed it! thx!

**Comment by QuantumInformation** [comment]
One more solution for the search engine!
