### ISSUE TITLE
NG build href

### ISSUE THREAD

**Issue by wieseknows** [angular/angular-cli#4993]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16.04

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
`ng --version`
@angular/cli: 1.0.0-beta.32.3
node: 6.9.5
os: linux x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

`node --version`
v6.9.5

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
ng new eumk
ng g c subsid
ng g c theory
ng build

### The log given by the failure.
> Normally this include a stack trace and some more information.
no errors

### Mention any other details that might be useful.
Build the project with `ng build`, got a dist folder.
I run index.html, everything works. The address is `file:///home/wiese/src/eumk/dist/main/index.html`
But when i click a button with href='#' adress is changing into `file:///home/wiese/src/eumk/dist/main/#`
So i just can't use buttons and dropdowns

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattdistefano** [comment]
See https://github.com/angular/angular/issues/7294

Or practice more semantic markup and use an actual `button` tag.

**Comment by Brocco** [comment]
@wieseknows you are attempting to run the web application without a web server (the file server does not handle this for you). You can use a separate web server to host the dist folder, or you can run `ng serve` which will build the application and start a web server with the application running on  port 4200. So once you've run that you can open your browser and navigate to `http://localhost:4200/` to see your application.
