### ISSUE TITLE
ng-xi18n should include some contextual info in the .xlf file

### ISSUE THREAD

**Issue by OndraZizka** [angular/angular-cli#4995]
Angular version: 2.4.5

The ng-xi18n tool generates the translation file based on what it finds in the templates' i18n attribute, see [here](https://angular.io/docs/ts/latest/cookbook/i18n.html).

The generated file doesn't contain the context in which the string was found. To give that context, the template must have an explanatory text in the i18n attribute. That is quite a lot of extra content, which makes the template less readable and maintainable. Besides, just to wriite that text takes time.

The tool could include some context automatically:
1) The content of the nearest h1-h6 predecessor. The idea is that these contain what the current page, section or component is. For instace:

    `<div> <h3>Server error</h3> <div>...</div> <button i18n>Dismiss</button> </div>`

Here, the "Dismiss" text would be accompanied by `nearestHeading="Server error"`

2) The full path CSS selector. The idea is that the path will most likely contain identifier and classes that can give a hint what the current text is. For instance:

    `<div> <h3>Server error</h3> <div>...</div> <button i18n>Dismiss</button> </div>`

Here, the "Dismiss" text would be accompanied by `cssSelector="div > button"`, which would be quite useful hint that it is a label of a button.

3) The file name. The "Dismiss" would be accompanied by `file="server-error-modal-dialog.component.html"`.

**Comment by hansl** [comment]
This is the wrong repository to ask this. Please report this in http://github.com/angular/angular as the CLI only uses the xi18n tool and does not implement it.
