### ISSUE TITLE
ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by Maksi1994** [angular/angular-cli#4998]
### OS?
> Windows 10

### Versions.
@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

I use commands `ng build --prod` or `ng build --prod --aot` for production my projects,
 after connected file in document index.html -> errors occur:

>   Uncaught ReferenceError: webpackJsonp is not defined
>         at vendor.bundle.js:1

and

> TypeError: Cannot read property 'call' of undefined
>     at r (inline.fc1c1a5….bundle.js:1)
>     at Object.585 (main.caf6b13….bundle.js:11)
>     at r (inline.fc1c1a5….bundle.js:1)
> Previously everything worked fine... thank you in advance

**Comment by masaanli** [comment]
I have the same error!

**Comment by Maksi1994** [comment]
my solution

<script type="text/javascript" src="/javascripts/inline.c36e4ea421785d053d7f.bundle.js" defer></script>
<script type="text/javascript" src="/javascripts/vendor.7aa5613277cc5d97af42.bundle.js" defer></script>
<script type="text/javascript" src="/javascripts/main.f40c5b60e8aad8074c2d.bundle.js" defer></script>

=)

**Comment by MortimerCat** [comment]
Problem still exists in CLI RC.0   I created a new project and this is the result of running ng build --prod

```
Uncaught ReferenceError: Invalid left-hand side expression in postfix operation
polyfills.9dab997….bundle.js:1 Uncaught ReferenceError: Invalid left-hand side expression in postfix operation
vendor.c95ab59….bundle.js:50 Uncaught ReferenceError: Invalid left-hand side in assignment
main.b18fc53….bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at main.b18fc53….bundle.js:1
```
 
Running following versions....
angular/cli: 1.0.0-rc.0
node: 7.4.0
os: linux x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

**Comment by MortimerCat** [comment]
I mysteriously started working again without doing anything!  My guess is that a npm package has been updated within the last hour, and the npm update/install has loaded the fix.

**Comment by mscahill** [comment]
I'm still seeing this issue

**Comment by kipy-be** [comment]
@mscahill's solution worked for me. Thank you
