### ISSUE TITLE
@angular/cli: 1.0.0-rc.0

### ISSUE THREAD

**Issue by Maksi1994** [angular/angular-cli#5002]
> Windows 10

### Versions.
>@angular/cli: 1.0.0-rc.0

What is this version -  @angular/cli: 1.0.0-rc.0?

**Comment by filipesilva** [comment]
@Maksi1994 this is the new version of `@angular/cli`. `rc.0` stands for Release Candidate 0. By convention beta versions are followed by release candidates, and then we go to final 1.0.
