### ISSUE TITLE
Global defaults.styleExt in globalconfig not honored when creating a new project

### ISSUE THREAD

**Issue by Cammisuli** [angular/angular-cli#5009]
Setting the global config to have a default style extenstion does not get honored when creating a new application.

I expect that we can set the defaults in the global config and have the cli respect those settings.

### OS?
> Mac OSX (El Capitan)

### Versions.
> @angular/cli: 1.0.0-rc.0

### Repro steps.
* Set global config with `ng set --global defaults.styleExt=scss`
* Create new application with `ng new`
* Notice that the component styles are still css

Note: creating a new application with `ng new appname --style=scss` still works. Also doing `ng set defaults.styleExt=scss` works as well.

**Comment by Brocco** [comment]
The fix for this should depend upon the merging of PR #5023

**Comment by Brocco** [comment]
The logic for finding the default globally set style extension was resolved in PR #5023

**Comment by Cammisuli** [comment]
I just got the lastest (rc.1) and doing `ng new app` does not read the `defaults.styleExt` from the global config. From the mention PR, it looks like everything reads from the local config, and if it's not there, it reads from the global. 

Nevertheless, doing `new` does not read the global config settings. Maybe I'm missing something?
