### ISSUE TITLE
 `ng generate route` command doesn't respect the `--default` flag

### ISSUE THREAD

**Issue by antonmoiseev** [angular/angular-cli#501]
1. Mac OSX (El Capitan)
2. `ng --version`:

  ```
  angular-cli: 0.0.33
  node: 5.10.1
  os: darwin x64
  ```
3. Steps:
  1. `ng new my-app`
  2. `cd my-app`
  3. `ng g route home --default`

  The generated route config is:
  ```
  {path: '/home/...', name: 'Home', component: HomeComponent}`
  ```
  The expected config is:
  ```
  {path: '/home/...', name: 'Home', component: HomeComponent, useAsDefault: true}
  ```

**Comment by Brocco** [comment]
I saw this parameter/argument the other day and wondered if it was implemented, apparently not.
