### ISSUE TITLE
Angular CLI RC.0 Adding Facebook SDK or Google Map SDK or other @types failing

### ISSUE THREAD

**Issue by bjornharvold** [angular/angular-cli#5013]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?

Mac OSX Sierra

### Versions.

@angular/cli: 1.0.0-rc.0
node: 7.6.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/platform-server: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

### Repro steps.

This is an Angular CLI created app and has been working fine until RC.0

Added @types for Facebook and Google Maps. 

In package
"devDependencies": {
    "@angular/cli": "^1.0.0-rc.0",
    "@angular/compiler-cli": "2.4.8",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.60",
    "@types/facebook-js-sdk": "^2.8.0",
    "@types/googlemaps": "^3.26.2",
    "@types/markerclustererplus": "^2.1.28",
    "codelyzer": "~2.0.0",
    "jasmine-core": "2.5.2",
    "karma": "1.4.1",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "markerwithlabel": "^2.0.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "~2.0.10"
  }

### The log given by the failure.

Cannot find namespace 'google'.
Cannot find name 'FB'

When I start the app with 'ng serve' I get the errors above that it cannot find the namespaces for these types. However, when I force a re-compile by changing anything in my app, everything compiles fine again. I can replicate this over and over again. First compile fails. All subsequent 'live reload compilations' succeed. It's as if the first compile doesn't have access to the types because they were loaded too late.

### Mention any other details that might be useful.

I do not use typings.d.ts or import * as google from 'googlemaps' because neither has an impact on this error. Everything looks to be working fine without them as well. 

Please advise. Cheers.
Bjorn

**Comment by vandut** [comment]
You also need to add types explicitly to `tsconfig.app.json` file, like so:
```
"types": ["hammerjs"]
```

**Comment by bjornharvold** [comment]
That did the trick. I thought Angular CLI would automatically pull in anything under node_modules/@types.

**Comment by antonybudianto7** [comment]
removing the whole "types" prop works too

**Comment by bjornharvold** [comment]
@antonybudianto7 For some reason, types works for me. Otherwise, it compiles successfully only at random. Definitely feels like a timing issue.
