### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by yogibearke** [angular/angular-cli#5015]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
 Windows  10

### Versions.
@angular/cli: 1.0.0-rc.0
node: 6.9.4
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

### Repro steps.
> ng new
> npm install angular2-highcharts --save

change app.module.ts:
(see: https://www.npmjs.com/package/angular2-highcharts )
- import { ChartModule } from 'angular2-highcharts';
- imports: [      .......... , 
      ChartModule.forRoot(require('highcharts')
    ],

> ng serve

### The log given by the failure.
ERROR in Error encountered resolving symbol values statically. Calling function 'ChartModule', function calls are not supported. .......

### Mention any other details that might be useful.
save app.module.ts again without changing anything and the error is gone !! "ng serve" is functioning normally.
buit no "ng build"

Thx for taking your time

**Comment by clydin** [comment]
The instructions provide by the library are not AOT compatible (I.e., not statically analyzable).  Please see the following issue from the project fir more details: https://github.com/gevgeny/angular2-highcharts/issues/163
