### ISSUE TITLE
Angular Cli installation takes ages to install

### ISSUE THREAD

**Issue by anantgoldie** [angular/angular-cli#5016]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7 Professional

### Versions.
> node --version
v6.10.0

### Repro steps.
> npm install -g angular-cli

This is taking ages to install. I dont know why its installing all the packagez which i wont be using. I see that this package itself is tightly coupled to other dependencies. 

### The log given by the failure.
> 
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd C:\Users\ach405\Desktop\Work\Personal\cheqsterapp

C:\Users\ach405\Desktop\Work\Personal\cheqsterapp>npm install -g angular-cli
npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[       ...........] \ fetchMetadata: sill mapToRegistry uri http://registry.npmjs.org/on-headers

### Mention any other details that might be useful.
I am on 100MB/s internet and internet connection is the not the issue, i can gaurantee that. But this installation is wasting my time. Can we please check what is going wrong in the latest angular-cli. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by anantgoldie** [comment]
After 1 hr of installation the extraction failed because of missing python and rxjs package. what a complete waste of time. 

If there are an prerequisites these must be clearly detailed out on the installation guide.

**Comment by electric-head** [comment]
Did you make sure to use "@angular/cli", instead of just "angular/cli"? angular/cli is very deprecated now, so that could be part of the problem (see your log output: "npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.")

**Comment by anantgoldie** [comment]
i followed along with https://cli.angular.io/ where it mentioned npm install -g angular-cli

I am installing it again, if this time it didnt work i would go for @angular/cli

**Comment by emostafa** [comment]
its a mistake on angular-cli website, they are working on fixing it, you should now install @angular/cli instead of angular-cli.

**Comment by anantgoldie** [comment]
started now with @angular/cli lets see how much time this takes :)

**Comment by clydin** [comment]
The website is quite outdated.  Please use the wiki for more up to date information: https://github.com/angular/angular-cli/wiki

**Comment by anantgoldie** [comment]
this still doesnt work. 

Here are the logs where it is failing now. 

```
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\admach405\.node-gyp\6.10.0
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp verb "Release" dir needed to be created? C:\Users\admach405\.node-gyp\6.10.0\Release
gyp verb copying "node.lib" for x64 C:\Users\admach405\.node-gyp\6.10.0\Release\node.lib
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 26-02-2017 14:29:24.
Project "C:\Users\admach405\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Micros
oft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\admach405\AppData\Roaming\
npm\node_modules\@angular\cli\node_modules\node-sass\build\binding.sln]
Done Building Project "C:\Users\admach405\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\binding.sln" (default targets) -
- FAILED.


Build FAILED.

"C:\Users\admach405\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\binding.sln" (default target) (1) ->
(_src_\libsass target) ->
  MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Micr
osoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\admach405\AppData\Roamin
g\npm\node_modules\@angular\cli\node_modules\node-sass\build\binding.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.31
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\admach405\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-gyp\lib\build.js:276:23)

gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admach405\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-g
yp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\admach405\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
Build failed with error code: 1
C:\Users\admach405\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
ch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ach405\Desktop\Work\Personal\cheqsterapp\npm-debug.log
npm ERR! code 1

```

**Comment by clydin** [comment]
Are you behind a restrictive proxy or firewall? 
It shouldn't be trying to build unless it can't download the prebuilt binary or you're on an exotic platform.

**Comment by anantgoldie** [comment]
yes i am behind a proxy, but i have set configs . 
npm config set proxy and npm config set https-proxy

isn't it supposed to work after setting the proxies.

**Comment by clydin** [comment]
The node-sass prebuilt binaries are hosted on S3 which is probably not working with your proxy setup.

**Comment by anantgoldie** [comment]
This was an issue with the proxy. I tried on my personal laptop and this works. closing this issue. thanks all for inputs.

**Comment by VisheshSingh** [comment]
Hey, I am facing the same issue. I think I am behind a proxy or firewall. What needs to be done in this case? Please help.

**Comment by VisheshSingh** [comment]
My command prompt is stuck on this:
 C:\WINDOWS\system32>npm install -g @angular/cli
[    ..............] / loadRequestedDeps: sill install loadAllDepsIntoIdealTree

**Comment by anantgoldie** [comment]
This cannot be fixed if you are behind a proxy

**Comment by ctrl-brk** [comment]
This is npm issue, not cli. Look at this post: http://stackoverflow.com/questions/7559648/is-there-a-way-to-make-npm-install-the-command-to-work-behind-proxy
