### ISSUE TITLE
how to include 3rd party style in component scoped without using ViewEncapsulation.None

### ISSUE THREAD

**Issue by guzuomuse** [angular/angular-cli#5017]
how to include external 3rd plugin that has some css (maybe the css also with some images);

for example:
when use jquery ui datepicker,this plugin along with some self-css rules, jquery-ui.css and jquery-ui-theme.css;  
1: i'don't want include these css files into .angular-cli.json's [styles]
2:assume the css with some background-images, where to place these images?
like this?
```
"assets": [
  { "glob": "**/*", "input": "../node_modules/some-package/images", "output": "./some-package/" },
]
```
here is an example:

```
import { Component, AfterViewInit, ViewChild, ElementRef, OnInit, ViewEncapsulation ,Inject} from '@angular/core';


import * as $ from 'jquery';
import 'jqueryui';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: [
    './app.component.css',
    '../../node_modules/jqueryui/jquery-ui.css',
    '../../node_modules/jqueryui/jquery-ui.theme.css',
  ],
// encapsulation: ViewEncapsulation.None//
})
export class AppComponent implements OnInit {

  @ViewChild('test_input_for_angular') ceshi_input: ElementRef;

  ngOnInit() {
    const el = this.ceshi_input.nativeElement;
    console.log($(el).val());
    $(el).datepicker();

    
  }
}
```

if we comment theencapsulation: ViewEncapsulation.None",the plugin style can't be applied.

so i want to know what's the best solution for this situation?

thanks.

**Comment by slmyers** [comment]
I would import the third party css in `src/styles.css` and move the images into the asset folder.

**Comment by guzuomuse** [comment]
@slmyers ,thanks for replying...but as your said, the bundled file may very large and  most of the css rules not be applied.  load 3rd party css only required pages is better. i just want to find that way...

**Comment by clydin** [comment]
If you're using the styles in your component, native encapsulation is required.  Including them via the angular-CLI styles field is probably cleaner as the styles are intended to be global.  Also,  if you include the styles in the root component with native view encapsulation, they effectively become global anyway.

Either way,  the CLI supports CSS url() and import processing so the images should be automatically processed.

**Comment by guzuomuse** [comment]
thank you guys.
