### ISSUE TITLE
RC.0 on Ubuntu 16.04 any command of ng gives error

### ISSUE THREAD

**Issue by mrudangit** [angular/angular-cli#5022]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Linux hostname  4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Versions.
ng -v gives error
/usr/lib/node_modules/@angular/cli/bin/ng:94
  const hasOldDep = !!packageJsonProject.dependencies['angular-cli'];
                                                     ^

TypeError: Cannot read property 'angular-cli' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/bin/ng:94:54)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Did this 

npm uninstall -g angular-cli
npm uninstall -g @angular/cli
npm cache clean

npm install -g @angular/cli@latest

Works fine on Winddows 10

**Comment by danimality** [comment]
I had a similar error on OSX which seemed to stem eventually from not having a devDependencies key in my package.json - I added devDependencies and dependencies as empty objects to my package.json and then ng started working!

**Comment by mrudangit** [comment]
I can't even create a project to begin with. 

even ng -v gives eror

**Comment by jwuliger** [comment]
Hello I have the same problem but on Windows 10. Completely fresh install of everything from scratch and just trying to use `ng help` throws the following:

Stack Trace:

```
const hasOldDevDep = !!packageJsonProject.devDependencies['angular-cli'];
                                                           ^

TypeError: Cannot read property 'angular-cli' of undefined
    at Object.<anonymous> (C:\Users\jwuliger\AppData\Roaming\nvm\v7.6.0\node_modules\@angular\cli\bin\ng:95:60)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
```

So I am not even dealing with a project yet. What am I missing here? Did something change with how you are supposed to install the CLI in RC0?

Thanks.

**Comment by altschuler** [comment]
@jwuliger Did you remove `angular-cli` from your package.json?

**Comment by jwuliger** [comment]
@altschuler Oh yeah, I had that removed already. Everything was working with Beta.32-3. Its odd I am investigating now.

**Comment by danimality** [comment]
what happens if you manually create a package.json with an empty object for the dev dependencies?

**Comment by jwuliger** [comment]
What was strange is I had just installed the cli globally using NPM. I wasn't even creating a project yet. I was fiddling with some things and now everything works except trying to run an NG4 version.

**Comment by cdarken** [comment]
As @mrudangit said, the error appears when trying to run `ng new`. It runs inside an older project. But how do we create a new one? :)

**Comment by cdarken** [comment]
Found this commit: https://github.com/angular/angular-cli/commit/211270d85fc53bfb16bf5db80e56ce329655f54f
It looks like that might prevent the error.

**Comment by ronenwo** [comment]
created a package.json as danimality  suggested and it worked for me

**Comment by filipesilva** [comment]
Closing as it seems to be sorted.
