### ISSUE TITLE
ng test not working on updated sources

### ISSUE THREAD

**Issue by alvipeo** [angular/angular-cli#5024]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10 x64

### Versions.
> RC.0

### Repro steps.
> Added more complicated tests and while 'ng test' is watching, I change some code, and it doesn't really get the updated code. So the new test iteration works on previous code (unchanged). Also, I get weird errors after the code changed:
>>ERROR in [path]/services/myservice.service.spec.ts (24,1): Cannot find name 'describe'.)
[path]/services/myservice.service.spec.ts (45,9): Type 'undefined' is not assignable to type 'string'.)
[path]/services/myservice.service.spec.ts (48,5): Cannot find name 'beforeEach'.)
[path]/services/myservice.service.spec.ts (61,5): Cannot find name 'beforeEach'.)
[path]/services/myservice.service.spec.ts (65,27): Cannot find name 'jasmine'.)
[path]/services/myservice.service.spec.ts (66,9): Cannot find name 'jasmine'.)

So now I have to restart 'ng test' every time I change the code :( This is actually a blocker.

**Comment by anderaus** [comment]
Do you have `"dom"` included in your `"lib"` array in `src\tsconfig.spec.json`? Does adding it help?

**Comment by MateEke** [comment]
I have the same error with Angular 4, I have copied the tsconfig files from a new project.

ng -v
```@angular/cli: 1.0.0-rc.0
node: 6.9.1
os: win32 x64
@angular/common: 4.0.0-rc.1
@angular/compiler: 4.0.0-rc.1
@angular/core: 4.0.0-rc.1
@angular/forms: 4.0.0-rc.1
@angular/http: 4.0.0-rc.1
@angular/platform-browser: 4.0.0-rc.1
@angular/platform-browser-dynamic: 4.0.0-rc.1
@angular/router: 4.0.0-rc.1
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 4.0.0-rc.1
```

tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016"
    ]
  }
}
```

tsconfig.spec.json
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "module": "commonjs",
    "target": "es6",
    "baseUrl": "",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts"
  ],
  "include": [
    "**/*.spec.ts"
  ]
}
```

```
ERROR in .../src/app/main/admin/partners/details/details.resolve.spec.ts (15,1): Cannot find name 'describe'.)
.../src/app/main/admin/partners/details/details.resolve.spec.ts (45,3): Cannot find name 'beforeEach'.)
.../src/app/main/admin/partners/details/details.resolve.spec.ts (74,3): Cannot find name 'it'.)
.../src/app/main/admin/partners/details/details.resolve.spec.ts (77,5): Cannot find name 'expect'.)
.../src/app/main/admin/partners/details/details.resolve.spec.ts (78,5): Cannot find name 'expect'.)
.../src/app/main/admin/partners/details/details.resolve.spec.ts (79,5): Cannot find name 'expect'.)
.../src/app/main/admin/partners/details/details.resolve.spec.ts (82,3): Cannot find name 'it'.)
.../src/app/main/admin/partners/details/details.resolve.spec.ts (85,5): Cannot find name 'expect'.)
.../src/app/main/admin/partners/details/details.resolve.spec.ts (86,5): Cannot find name 'expect'.)
.../src/app/main/admin/partners/details/details.resolve.spec.ts (87,5): Cannot find name 'expect'.)
```

**Comment by alvipeo** [comment]
@anderaus why? I got all files from 'ng new'. why should I add more to test my project?

**Comment by robertohuertasm** [comment]
@anderaus this doesn't seem to help. I'm getting this issue since upgrading to `rc1`

**Comment by robertohuertasm** [comment]
For the record, this is only happening when using the `--ng4` flag in `rc0`. I've tried it without the flag and everything seems to be working as expected.

**Comment by alvipeo** [comment]
I don't use any flags, and it happens to me.

**Comment by luechtdiode** [comment]
OK, **that did the trick**. Thanks to @stuarthallows comment about TypeScript update to `2.2`. I returned to `2.0.10` and everything works as expected.

**Comment by robertohuertasm** [comment]
Steps to reproduce this just with the `hello-world` app (`@angular/cli@1.0.0-rc.1`):

1. `ng new test-ng2` , `ng test`, while running, change a test and break it. I will work as expected. Using typescript `2.0.10`

2. `ng new test-ng4 --ng4` , `ng test`, while running, change a test and break it. I will show some errors about not finding `describe`, `it`... and then the result will be the first one. Using typescript `2.0.10` doesn't work. I tried with `2.1.6`  and even `2.2.1`. Still the same issue...

**Comment by Toxicable** [comment]
Also getting this issue on a new and upgraded project. Windows 10 and RC.1 on ng4

**Comment by MateEke** [comment]
The new tsconfig files with @angular/cli@1.0.0-rc.2 seems to solve the problem for me. I had to fix zone.js on 0.8.0, because 0.8.1 caused typeerrors in my tests.

ng -v
```
node: 6.10.0
os: win32 x64
@angular/common: 4.0.0-rc.3
@angular/compiler: 4.0.0-rc.3
@angular/core: 4.0.0-rc.3
@angular/forms: 4.0.0-rc.3
@angular/http: 4.0.0-rc.3
@angular/platform-browser: 4.0.0-rc.3
@angular/platform-browser-dynamic: 4.0.0-rc.3
@angular/router: 4.0.0-rc.3
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 4.0.0-rc.3
``` 

tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```
tsconfig.spec.json
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "module": "commonjs",
    "target": "es5",
    "baseUrl": "",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts"
  ],
  "include": [
    "**/*.spec.ts"
  ]
}
```

**Comment by filipesilva** [comment]
Seems to have been a bad update. This should help https://github.com/angular/angular-cli/wiki/stories-rc-update.
