### ISSUE TITLE
.angular-cli.json add wildchar styles

### ISSUE THREAD

**Issue by albanx** [angular/angular-cli#5025]
Is there any way to add more styles by a regex or wildchar in the cli configuration file, ex:
```
      "styles": [
        "assets/css/*.css"
      ],
```

**Comment by filipesilva** [comment]
No, we don't support globs. I also really wouldn't advise doing that with CSS, since order of loading matters.

**Comment by albandaft** [comment]
Why you wouldn't advise doing that?
