### ISSUE TITLE
ng serve removes dist folder from the project, but it stops PhpStorm IDE from updating project folder structure.

### ISSUE THREAD

**Issue by owen26** [angular/angular-cli#5027]
Every time I do `ng build` then follows `ng serve`, my PhpStorm project folder view freezes  and stop updating file structure.

MacOS 10.12.3 + angular-cli beta.31 + PhpStorm 2016.3

It maybe an IDE bug rather than angular-cli bug, or not...

![image](https://cloud.githubusercontent.com/assets/385786/23344339/77ea6496-fc72-11e6-999b-6d654c41fc98.png)

**Comment by Meligy** [comment]
Definitely IDE specific. I wouldn't expect VS Code to have this for example.

Try disabling plugins just in case, and if the problem continues, please report it to JetBrains tracker.

**Comment by stauvel** [comment]
No problem for me with this IDE (angular-cli.rc0 + PhpStorm 2016.3 + Win7 64)

**Comment by owen26** [comment]
Thanks. I guess this is something only happens on macOS + JetBrains then.
