### ISSUE TITLE
Should "ng serve" be able to serve static html files?

### ISSUE THREAD

**Issue by derobiom** [angular/angular-cli#5029]
I have a app that runs just fine with "ng serve". BUT if I try to retrieve another (static) html file that is in my src directory, I get a 304 and it just serves up the angular app again.  The only way that I can see that static html file is to change the app->index value in the .angular-cli.json file.  But then my angular 2 app does not run.  Is "ng serve" only meant for SPA so that it CANNOT serve up separate static html files?  I wanted to have some exterior (not logged in) pages with a very different look than my "app".  Just trying to find the least painful way, if there is one.

**Comment by Meligy** [comment]
Any extra files you want to include in the build/serve should be added to the `assets` property in `.angular-cli.json`.

**Comment by derobiom** [comment]
Thank you! works great now!

**Comment by bresleveloper** [comment]
1. ng-build with your index.html set properly with its components. (or conditional app-components)
2. rename and copy the rendered to (for example) /src/search.html
3. in angular.json (angular-cli.json for pre v5) find "assets":

```
"assets": [
"src/favicon.ico",
"src/search.html",
"src/assets"
],
```
browse localhost:4200/search.html
enjoy :)

[source](http://bresleveloper.blogspot.com/2018/07/angular-add-more-html-pages.html)

**Comment by RonNewcomb** [comment]
... aaaaand restart "ng serve" so the change takes effect.  :)

**Comment by stevefiedler** [comment]
I have spent literally hours trying this, with long directory/file names, restarting constantly and still nothing appears for my http request either in the browser or by using HttpClient.

http://localhost:4203/badge1.html

Not sure what it could be.

**Comment by bresleveloper** [comment]
did you put it in "assets" in the angular json?

**Comment by bresleveloper** [comment]
> I did, but actually it seems I inadvertently was not setting it up correctly. Even though my target asset is down the directory structure a bit, I was able to access it finally.
> 
> angualr.json:
> 
> ```
>         "assets": [
>           "src/favicon.ico",
>           "src/assets",
>           "src"
>         ],
> ```
> Reference - finally got a '200' - yay!
> 
> http://localhost:4203/app/sample/examples/elements/badge-example/badge1.html
> 
> Thanks for making me re-look at it.

well, now we all learned something new
