### ISSUE TITLE
How do I debug angular-cli

### ISSUE THREAD

**Issue by waiholiu** [angular/angular-cli#5030]
Hi,

Not sure if this is the right place to post a question (if not, let me know). I'm new to open source development - and I would like to start contributing to open source projects. Angular-cli seems like a good one to contir as I often use it.

So I'm trying to learn the code base and how it all works. I was wondering, can anyone post steps on how I can get line by line debugging? I have followed the steps on "Development Hints for hacking on Angular CLI" in the Readme page and have my own copy of angular-cli. And I've put lots of ui.writeline commands everywhere to try to see how it all works. 

But I would be really great if I can step through line by line. I am using Visual Studio Code - to debug an angular site, it's really easy. Just need to point to the right port number in launch.json file. However, I'm unsure how to attach the debugger to the cli.

Thanks,

Wai

**Comment by RicardoVaranda** [comment]
Personally I use Developer Tools in google chrome to debug, if you run the cli without the command --no-sourcemap or without being in --prod mode you will have access to the webpack in sources which allows you to navigate through your project files and place a breakpoints in your code base.

I would also recommend using Augury. Augury is a Chrome Dev Tools extension for debugging Angular 2 applications.

**Comment by waiholiu** [comment]
Sorry do you mean debugging angular apps generated by angular-cli or do you mean debugging angular-cli itself when it does the code generation?

I'm looking for a solution for the latter because I'm trying to get up to speed with the code base so that I can make contributions to this project.

**Comment by RicardoVaranda** [comment]
I was under the impression you were referring to the apps generated by the angular-cli.

In regards to debugging the angular-cli project itself I wouldn't be the best person to ask, @filipesilva will be able to help you better with this.

**Comment by filipesilva** [comment]
I think the easiest way is to run the CLI via node with inspect+bebug break+a debugger statement somewhere.

So imagine you want to check the arguments going into `ng serve`. 
- setup everything like shown in https://github.com/angular/angular-cli#development-hints-for-hacking-on-angular-cli
- Add a `debugger;` statement here https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/commands/serve.ts#L114
- run `node --inspect --debug-brk ./node_modules/\@angular/cli/bin/ng serve`
![image](https://cloud.githubusercontent.com/assets/4172079/23359601/e17987f4-fcde-11e6-86d1-34ffc6295faa.png)
- open your browser on the link that appears on your console
- the debugger will be stopped on the very first statement, click `Resume script execution`
![image](https://cloud.githubusercontent.com/assets/4172079/23359631/01f42b56-fcdf-11e6-8e0d-8e13d5ceea03.png)
- you should be at your `debugger;` statement

**Comment by waiholiu** [comment]
oh wow, that worked. 

Fantastic!

Thanks a lot

**Comment by filipesilva** [comment]
@waiholiu glad you found it useful :D

**Comment by willyelm** [comment]
have you tried https://atom.io/packages/atom-bugs-nodejs?

**Comment by YonatanKra** [comment]
Hi @filipesilva - this solution doesn't work for me. I've installed a new CLI project and run:
`run node --inspect --debug-brk ./node_modules/\@angular/cli/bin/ng serve`
This is what I get in the console:
![image](https://user-images.githubusercontent.com/6459899/55936987-81643080-5c40-11e9-89d7-1f8f84265494.png)

When I open in Chrome I cannot see any file to debug:
![image](https://user-images.githubusercontent.com/6459899/55937032-a22c8600-5c40-11e9-838e-f58607e6e408.png)

Is there a new way to debug the `ng` commands?

**Comment by pos1tron** [comment]
@YonatanKra Not sure if this helps, but thought i'd share. I see the same thing in the console as you, but in chrome if I browse to: `chrome://inspect` I see it listed under "Remote Target" and can inspect from there.
