### ISSUE TITLE
How to publish cli project with angular-cli.json deps, such as assets, styles and scripts?

### ISSUE THREAD

**Issue by yairtawil** [angular/angular-cli#5037]
here is my angular-cli.json content:

 "assets": [
        "assets",
        "favicon.ico",
        "styles.css"
      ],
...
...
      "styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.css",
        "../node_modules/leaflet/dist/leaflet.css",
        "../node_modules/openlayers/css/ol.css",
        "../node_modules/cesium/Build/Cesium/Widgets/widgets.css",
        "../node_modules/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css"
      ],
      "scripts": ["../node_modules/rison/js/rison.js"],

**Comment by RicardoVaranda** [comment]
I think the command you are looking for is ng build, this compiles your project and creates a dist folder with your project requirements. You can have a look at the possible options here:
https://github.com/angular/angular-cli/wiki/build

**Comment by filipesilva** [comment]
Closing as answered, thanks @RicardoVaranda !
