### ISSUE TITLE
Corrections to Angular CLI RC.0 migration guide

### ISSUE THREAD

**Issue by PlatinumEagle** [angular/angular-cli#5039]
### Versions
angular-cli v1.0.0-rc.0

### Repro steps
Original application created with v1.0.0-beta.26, followed the guide to migrate to RC.0, but there are some corrections that need to be made for a successful migration.

#### package.json corrections
- Typo: `Packages in dependencies:` is listed twice. The second instance should be `Packages in devDependencies:`
- The guide indicates that the `jasmine-spec-reporter` should be removed from devDependencies, but is still required and the version was updated to `~3.2.0`.
- The 'build' option is missing from "scripts".  `"build": "ng build"` should be added.
- `ts-helpers` was removed, but there is no reference to this in the doc

**Comment by PlatinumEagle** [comment]
PR Submitted

**Comment by magnattic** [comment]
I tripped over the removal of `jasmine-spec-reporter` while following the upgrade guide. Turns out it is still needed for protractor.
