### ISSUE TITLE
Can't resolve certain @types packages (eg: fb)

### ISSUE THREAD

**Issue by instantepiphany** [angular/angular-cli#5040]
When attempting to use the fb typings for typescript, angular-cli throws errors when running `ng serve` (and I assume `ng build`).
At first I assumed it was an issue with the typings package (`fb`) but I can run `tsc` on the same project and it compiles into JS with no errors. Am I right in thinking that it then is something to do with `angular-cli` or maybe `webpack`?

Note, if you run into TS2304 errors complaining of missing names `HTMLElement` and `Element`, edit `tsconfig.json` and add `dom` to the `lib` section.

### OS
OpenSUSE

### Versions

@angular/cli: 1.0.0-rc.0
node: 7.2.1
npm: 3.10.10

### Repro steps
```
ng new foo
cd foo
npm install @types/fb --save-dev
```
Now edit `src/app/app.component.ts` to match the following:
```
import { Component } from '@angular/core';
import * as FB from 'fb';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';
  constructor() {
    FB.getAuthResponse();
  }
}
```
### The log given by the failure.

```
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'fb' in '/home/jordan/Documents/foo/src/app'
 @ ./src/app/app.component.ts 11:0-25
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.
```

**Comment by instantepiphany** [comment]
Why is it (apparently) just searching in `~/Documents/foo/src/app` and not in `foo/node_modules/@types/fb`?

**Comment by Brocco** [comment]
Looks like you've only installed the types for `fb`, you will also need to install the actual package (not just the types).

The steps you should follow to get this to work are:

```bash
ng new foo
cd foo
npm install fb --save
npm install @types/fb --save-dev
# add your coding changes
ng build
```

**Comment by instantepiphany** [comment]
It isn't on NPM, it is pulled in at runtime. A couple days after posting this issue I disabled type checking for `FB`, which let me use the API, albeit without the compiler enforcing type safety. If you want to look into this further I can do some more testing, if that helps.

**Comment by simeyla** [comment]
I always have a nightmare with these type def files. Is is `import *` or `import X`.

This is a useful article 

I did the following to get it working with `@types/fb`

```
import '@types/fb';

declare global 
{
    interface Window
    {
        FB: FBSDK
    }
}

```

The declaration is optional. I like to use `window.FB` personally, but you can just do `FB`.
