### ISSUE TITLE
Home.md has broken links

### ISSUE THREAD

**Issue by metamaker** [angular/angular-cli#5042]
https://github.com/angular/angular-cli/blob/master/docs/documentation/home.md

```
* [ng new](new)
* [ng serve](serve)
* [ng generate](generate)
* [ng test](test)
* [ng e2e](e2e)
* [ng build](build)
* [ng get/ng set](config)
* [ng docs](docs)
```
instead of 
```
* [ng new](new.md)
* [ng serve](serve.md)
* [ng generate](generate.md)
* [ng test](test.md)
* [ng e2e](e2e.md)
* [ng build](build.md)
* [ng get/ng set](config.md)
* [ng docs](docs.md)
```

**Comment by sumitarora** [comment]
@metamaker Repository is just used to maintain the documentation not view. Please visit wiki to view the detailed documentation. https://github.com/angular/angular-cli/wiki

**Comment by metamaker** [comment]
@sumitarora So you will just leave broken links on github in the repository.

I didn't even have a look at wiki, honestly, because I always check `docs/` folders first. And usually people can navigate docs via links from one .md file to other, which is not possible here.
