### ISSUE TITLE
css/scss double slash will be replaced by single

### ISSUE THREAD

**Issue by aslan92** [angular/angular-cli#5044]
```css
background: url(//maps.gstatic.com/tactile/icons/settings-48a771f248fcf5f4fbf21d1c0ff20841.png)
```
> actual:
```css
background: url(/maps.gstatic.com/tactile/icons/settings-48a771f248fcf5f4fbf21d1c0ff20841.png)
```
> expected:
```css
background: url(//maps.gstatic.com/tactile/icons/settings-48a771f248fcf5f4fbf21d1c0ff20841.png)
```

### OS?
> Windows 10

### Versions.
@angular/cli: 1.0.0-rc.0
node: 6.9.4
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

### Mention any other details that might be useful.
maybe this:
https://github.com/angular/angular-cli/commit/a2e819a8dd7ee51f69c80550b3b71b053a13f503#diff-aa06fda1fc53d1b1e6d1259f3cf4ca2dR53

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/5238
