### ISSUE TITLE
Where can I find example of all options that can be used in .angular-cli.json?

### ISSUE THREAD

**Issue by metamaker** [angular/angular-cli#5045]
After some googling, I can't find example of `.angular-cli.json` that contains all possible options to configure (something like https://symfony.com/doc/current/reference/configuration/doctrine.html, but for your .JSON config). Is it available somewhere?

*P.S. Documentation can be improved majorly. To put straight, this page will come to my worst nightmares: https://github.com/angular/angular-cli/blob/master/docs/documentation/config.md. `ng get` `ng set` - serious?*

**Comment by grizzm0** [comment]
https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/lib/config/schema.json

**Comment by metamaker** [comment]
Thanks for help 👍 ! This could be included somewhere in documentation.

**Comment by grizzm0** [comment]
It's already part of angular-cli.json with the property $schema in new projects. If you're updating from an older version you should always read the changelog. :)

**Comment by metamaker** [comment]
I haven't expected that I should look at some path that was in pregenerated  `.angular-cli.json`, like  "$schema": "./node_modules/@angular/cli/lib/config/schema.json". I have something about 70 dependencies in `package.json`, and if I had to read every changelog every day, I would have gone nuts. I even didn't mention that there was $schema parameter till you told me :) .

**Comment by filipesilva** [comment]
Closing as answered, thanks @grizzmo!
