### ISSUE TITLE
Cannot use linked lib in ejected cli project

### ISSUE THREAD

**Issue by Dinistro** [angular/angular-cli#5049]
### OS?
Ubuntu 16.04

### Versions.
@angular/cli: 1.0.0-rc.0 (e)
node: 7.5.0
os: linux x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8
npm: 4.1.2

### Repro steps.

1. Clone an ng-bootstrap and link it:
```
git clone https://github.com/ng-bootstrap/ng-bootstrap.git
cd ng-bootstrap
gulp build
cd dist/
npm link
```
2. Create new cli project and execute `ng eject`
3. Link ng-bootstrap into your new project:
```
npm link @ng-bootstrap/ng-bootstrap 
```
4. Import the NgbModule in the app.module.ts:
```
...
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    ...,
    NgbModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```
5. Execute npm start 

### The log given by the failure.
In the browsers console, you will see an error like this:

`Error: Unexpected value '[object Object]' imported by the module 'AppModule' ...`

### Mention any other details that might be useful.
After some debugging, I noticed, that ng-bootstrap was bundled in the `main.bundle.js` and not in the `vendor.bundle.js`. It's peerDependencies were as well in the `main.bundle.js`.

**Comment by Dinistro** [comment]
After some more debugging, I noticed, that `ng-bootstrap` is also bundled in the `main.bundle.js` if the project isn't ejected. But the peerDependencies aren't added to the `main.bundle.js`, like it should be.

**Comment by filipesilva** [comment]
I'm sorry but after you eject you're on your own. We try to guarantee it works for the majority of cases via tests but now you have a webpack config so you should be able to adapt it at will.
