### ISSUE TITLE
Unable to create OpaqueToken service to bridge Angular2 to JQuery

### ISSUE THREAD

**Issue by amrdarwish1975** [angular/angular-cli#5050]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 7 Professional (64 bit)

### Versions.
@angular/cli: 1.0.0-rc.0
node: 6.9.5
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

### Repro steps.
> Was this an app that wasn't created using the CLI? YES
What change did you do on your code? See the following steps
**Step 1:** Install latest angular cli: npm install -g @angular/cli
**Step 2:** create a new file & name it jquery.service.ts under app folder with the following contents:
import { OpaqueToken } from '@angular/core';
export const JQ_TOKEN = new OpaqueToken('jQuery');
export declare let jQuery: Object;
// providers
export const JQUERY_PROVIDER = [
    { provide: JQ_TOKEN, useValue: jQuery },
];
**Step 3:** append the following statements to app.module.ts:
...
import { JQUERY_PROVIDER } from './jquery.service';
@NgModule({
  ...
providers: [JQUERY_PROVIDER],
...
}) 
**Step 4**: Go to system CMD window & cd to project directory & run: ng serve
**Step 5**: "ng serve" command fails throwing error below

### The log given by the failure.
**ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 4:20 in the original .ts file), resolving symbol jQuery in C:/Projects/HelloWorld/src/app/jquery.service.ts, resolving symbol JQUERY_PROVIDER in C:/Projects/HelloWorld/src/app/jquery.service.ts, resolving symbol AppModule in C:/Projects/HelloWorld/src/app/app.module.ts, resolving symbol AppModule in C:/Projects/HelloWorld/src/app/app.module.ts
webpack: Failed to compile.**

### Mention any other details that might be useful.
This failure prevents me to bridge Angular2 to JQuery. Kinldy fix or advise a workaround.
Pls refer to attached app.zip file having the 2 files in question: jquery.service.ts, app.module.ts

[app.zip](https://github.com/angular/angular-cli/files/803417/app.zip)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
try changing
```TS
export declare let jQuery: Object;
```
to 
```TS
export declare let jQuery: any;
```

**Comment by amrdarwish1975** [comment]
@deebloo After applying your advice I still have same error as follows:

> ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the templa
> te compiler (position 4:20 in the original .ts file), resolving symbol jQuery in C:/Projects/HelloWorld/src/app/jquery.service.ts, resolving symbol JQUERY_PROVIDER in C:/Projects/H
> elloWorld/src/app/jquery.service.ts, resolving symbol AppModule in C:/Projects/HelloWorld/src/app/app.module.ts, resolving symbol AppModule in C:/Projects/HelloWorld/src/app/app.mo
> dule.ts

**Comment by deebloo** [comment]
@amrdarwish1975 did you try after I updated my comment?

**Comment by amrdarwish1975** [comment]
@deebloo yes (please compare time of our comments)

**Comment by deebloo** [comment]
Yes I use the same pattern for other global variables

**Comment by amrdarwish1975** [comment]
@deebloo pls share you angular-cli & OS versions?

**Comment by deebloo** [comment]
Sure I'll post it a few (on my way to work)

**Comment by deebloo** [comment]
Create a small repo to show it working

https://github.com/deebloo/JQUERY-TOKEN

**Comment by amrdarwish1975** [comment]
@deebloo I have just created 2 pull requests. Pls check?

**Comment by deebloo** [comment]
@amrdarwish1975 sorry forgot to push the actual provider code :D

**Comment by amrdarwish1975** [comment]
No problem

**Comment by amrdarwish1975** [comment]
@deebloo I used suggested factory approach above & build error disappeared however another error found whenever I try to reference $ as jquery tag. here is the code I am using through a new component:
**EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: this.$ is not a function**
`import { Component, Inject, AfterViewInit } from '@angular/core';
import { JQ_TOKEN } from './jquery.service';

@Component({
  templateUrl: './myComponent.component.html',
  styleUrls: ['./myComponent.component.css']
})
export class MyComponent implements AfterViewInit {
  constructor(@Inject(JQ_TOKEN) private $: any) { }
  public ngAfterViewInit(): void{
    this.$("#id").modal();
  }
}
`

**Comment by amrdarwish1975** [comment]
@deebloo See my updated comment above.

**Comment by deebloo** [comment]
@amrdarwish1975  I updated the sample repo to show it is working. I think this issue can be closed as it isn't an bug in the cli

**Comment by amrdarwish1975** [comment]
How it can be closed in  the time I still can reuse it as part of a new component?

**Comment by amrdarwish1975** [comment]
@deebloo I have just tried it using same code under repo however I encountered error in my browser console log as follows:
**_Array [ "jQuery" ]
EXCEPTION: Error in :0:0 caused by: this.$ is not a function_**

> Notice that the 1st line in above comment is a result of  console.log($);

Are you sure you had a look in your browser's console log if there any errors?

**Comment by deebloo** [comment]
<img width="1440" alt="screen shot 2017-02-28 at 9 28 31 am 2" src="https://cloud.githubusercontent.com/assets/6563621/23409122/6a4620b0-fd98-11e6-8bb8-d2265cb47547.png">

**Comment by deebloo** [comment]
Yes. the repository is working. make sure you have jquery in your scripts array. I would still say you should close this issue as it isn't a bug with the CLI

**Comment by amrdarwish1975** [comment]
@deebloo thanks for your support. May I ask how to have jquery in my scripts array?

**Comment by deebloo** [comment]
https://github.com/angular/angular-cli/wiki/stories-global-lib

**Comment by amrdarwish1975** [comment]
@deebloo It is working now. I missed to code correctly jqueryFactory under jquery-provider.ts file + missed to add jquery reference under .angular-cli.json.
## **_Many Thanks!_**

**Comment by deebloo** [comment]
@amrdarwish1975 no problem. glad it is working!

**Comment by amrdarwish1975** [comment]
@deebloo once I used same approach using an Injectable service (not through app.component), it throws error:
**_Unhandled Promise rejection: No provider for [object Object]!_** 

I know it is not angular-cli issue. Can you help anyway? If not, pls advise what is the correct repo I should re-open issue on?

**Comment by RobRoch** [comment]
Hello,

At the moment I have same problem.
Going through explanations, it still doesn't work in my app with JQUERY_PROVIDER.

![image](https://cloud.githubusercontent.com/assets/22058721/24835629/23926618-1d07-11e7-8f5b-f056852cecbe.png)

I've uploaded my code, "MovieRating". Hope someone will find few minutes to check this out :).

**Comment by amrdarwish1975** [comment]
@RobRoch , Did you try proposed code by deebloo? Recalling [https://github.com/deebloo/JQUERY-TOKEN](https://github.com/deebloo/JQUERY-TOKEN)
