### ISSUE TITLE
ng new prefix <empty> creates a false route-app in index.html -> selector:'-root'

### ISSUE THREAD

**Issue by HansS** [angular/angular-cli#5054]
@Component({
  selector: '-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = ' works!';
}

**Comment by filipesilva** [comment]
I'm sorry, but I don't get what you're trying to say. Can you give a concrete example?

**Comment by filipesilva** [comment]
Closing as inactive.
