### ISSUE TITLE
Can't run any ng commands 

### ISSUE THREAD

**Issue by 72gm** [angular/angular-cli#5058]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
>1.0.0-beta.26

### Repro steps.
> I uninstalled angular cli and then re-installed it and now none of my ng commands work!?!?

![untitled](https://cloud.githubusercontent.com/assets/12847881/23365500/3c9de3e8-fcfb-11e6-9cac-2d5e19f75b50.jpg)

**Comment by 72gm** [comment]
Needed a later version of node since there was a new version of angular cli.....

**Comment by delasteve** [comment]
@72gm, can this be closed?

As you noticed, with the change from `angular-cli` to `@angular/cli` there was a breaking change. Going forward, the cli requires v6.9 or higher.

https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#breaking-changes-3

**Comment by 72gm** [comment]
yeah you can close
