### ISSUE TITLE
VS Code shows lint errors for getters and setters: "Accessors are only available when targeting ECMAScript 5 and higher" for new RC.0 projects

### ISSUE THREAD

**Issue by ogix** [angular/angular-cli#5059]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-rc.0
node: 6.10.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
1. ng new test-app (Angular CLI RC.0)
2. Open with VS Code
3. Add getter/setter inside app component

### The log given by the failure.
> Normally this include a stack trace and some more information.
Shows lint error: "Accessors are only available when targeting ECMAScript 5 and higher"

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by diicar** [comment]
@ogix I think you needs to add **es5** in **tsconfig.json** at root conf file
```
...
"lib": [
   ...
   "es5",
   ...
 ]
...	
```

**Comment by ogix** [comment]
Actually only adding `"target": "es5"` at root `tsconfig.json` helped. I wonder if it is the only solution.

**Comment by sumitarora** [comment]
Added `"target": "es5"` to tsconfig by default https://github.com/angular/angular-cli/pull/5060
