### ISSUE TITLE
AoT compiles even when templates are accessing private properties

### ISSUE THREAD

**Issue by Shijir** [angular/angular-cli#5073]
AoT compiles successfully without giving any warnings when templates are accessing private properties. AoT compilation is supposed to fail when there are templates that access private properties.

It's easily reproducible in Angular CLI project (But I noticed this issue in my own project first). I tested it in a default Angular CLI project, where I made the title (accessed in the template) property private. After that, I run both ng serve --aot and ng build --aot one after another. In both cases, AoT was compiling without any failures and complaining.

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

macOS

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli version = ^1.0.0-beta.30
node version = v7.5.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

- make public properties private
- build or serve with `--aot` and check if the compiler complains about the private methods.

### The log given by the failure.
> Normally this include a stack trace and some more information.

N/A

### Mention any other details that might be useful.

References:
https://github.com/angular/angular/issues/11978
https://github.com/rangle/angular-2-aot-sandbox
http://stackoverflow.com/questions/34574167/angular2-should-private-variables-be-accessible-in-the-template

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by marcusreese** [comment]
#14739

**Comment by filipesilva** [comment]
Closing in favor of https://github.com/angular/angular/issues/14739, it seems to contain the needed context and root of the issue. Will reopen if this isn't something to be solved on that end.
