### ISSUE TITLE
Rename root tsconfig.json to tsconfig.ide.json

### ISSUE THREAD

**Issue by seescode** [angular/angular-cli#5076]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-rc.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
N/A

### The log given by the failure.
> Normally this include a stack trace and some more information.
N/A

### Mention any other details that might be useful.

I just upgraded to @angular/cli 1.0.0-rc.0.  As I'm working through the upgrade guide I saw that the tsconfig files got more specific names like tsconfig.e2e.json, tsconfig.app.json, and tsconfig.spec.json.  I think it would also be helpful if the root tsconfig was more specifically named tsconfig.ide.json.  

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by grizzm0** [comment]
It's named like that and placed in the root so that your IDE will find it.

**Comment by seescode** [comment]
Yep, that makes sense.  Thanks for clearing this up!
