### ISSUE TITLE
7.1 MB vendor.bundle? and an empty project 2.84 MB

### ISSUE THREAD

**Issue by stefanaerts** [angular/angular-cli#5077]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
mac os x

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
![image](https://cloud.githubusercontent.com/assets/3684599/23378579/ef3a6d86-fd33-11e6-8899-85d0f7f4df7e.png)

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
https://drive.google.com/open?id=0By7_cJqSCsKNcEJrNE02WU04dHc
Even after --aot --prod i have almost 4MB
Is this standard? Is this an issue? Must i split somehow the vendor.bundle file?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
Try upgrading to the latest CLI (`RC.0`). Currently  a new application stands at 1.2 MB uncompressed:

```
 ng build --prod
Hash: afebf57d068f8e5780d4
Time: 10015ms
chunk    {0} polyfills.f780e0efbb9b8993af20.bundle.js (polyfills) 155 kB {4} [initial] [rendered]
chunk    {1} main.4b8746a21b4cc11d7b03.bundle.js (main) 21.8 kB {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.2a603356da79bfa11188.bundle.js (vendor) 1.04 MB [initial] [rendered]
chunk    {4} inline.79bb710d84f824f5db5d.bundle.js (inline) 0 bytes [entry] [rendered]
```

Please note that 4MB is likely including source maps, which should not be deployed and won't be downloaded by your users. Closing this as answered.

**Comment by stefanaerts** [comment]
why you close?
i put sm=false,so no sourcemaps include.

**Comment by stefanaerts** [comment]
![image](https://cloud.githubusercontent.com/assets/3684599/23381005/3e8cc790-fd3d-11e6-9498-b3476c8bea03.png)
