### ISSUE TITLE
Blueprint for polyfill.ts has redundant information

### ISSUE THREAD

**Issue by rodrigopandini** [angular/angular-cli#5080]
### OS?
Windows 10.

### Versions.
@angular/cli: 1.0.0-rc.0
node: 7.6.0
os: win32 x64

### Repro steps.
The lines [39](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts#L39) and [40](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts#L40) can be joined with the line [48](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts#L48) and [49](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts#L49).

[Lines 39 e 40](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts#L39-L40):
```
/** IE10 and IE11 requires the following to support `@angular/animation`. */
import 'web-animations-js';  // Run `npm install --save web-animations-js`.
```
[Lines 48 and 49](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts#L48-L49):
```
/** ALL Firefox browsers require the following to support `@angular/animation`. **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.
```
### Mention any other details that might be useful.
Lines 39 e 40 can be like this:
```
/** IE10, IE11 and all Firefox requires the following to support `@angular/animation`. */
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.
```

**Comment by hansl** [comment]
The reason the poly fills are separated like this is because we separate them by browsers, not features. People should look through the file and uncomment the browsers they want to support; some people will not see the `IE9, IE10` and might skip it.

This is really hard to fine tune for everyone, but duplicating that line was an okay compromise for us. I'll chat with developers relationship about this issue, to see if we can make a better messaging.

**Comment by rodrigopandini** [comment]
@hansl OK. Now I understand why.

**Comment by Meligy** [comment]
@hansl the problem with duplication is that it's probably easy for people to uncomment both lines, which could cause weird runtime errors.

Maybe we can go for a standard comment format that shows browsers clearly (separate lines, obvious header, etc).

**Comment by filipesilva** [comment]
Closing as answered.
