### ISSUE TITLE
option for "template" in AOT webpack build

### ISSUE THREAD

**Issue by pborunda** [angular/angular-cli#5081]
I'm using 3rd-party module (ng2-bootstrap) in my AOT webpack build.

At this time, this module's components do not reference "templateUrl", only "template". As a result, the html templates are not compiled to javascript in my AOT bundle output. 
See https://github.com/valor-software/ng2-bootstrap/blob/8305a56cd7aaebfd33920fe6b7ab86813449fac0/src/pagination/pagination.component.ts

Is there an option to force AOT code generation when using inline template?

**Comment by hansl** [comment]
Hi. Unfortunately that's up to the library (in this case `ng2-bootstrap`) to publish javascript files without the decorators built in. The CLI does not have control on that code. We're working on a proper solution, but in the meantime there's nothing you can do. We'll try to communicate with ng2-bootstrap to help them publish a better version of their library.
