### ISSUE TITLE
"No module files found" when using cli to generate components

### ISSUE THREAD

**Issue by gloomylumi** [angular/angular-cli#5087]
### OS
OSX Sierra

### Versions.
@angular/cli: 1.0.0-rc.0
node: 7.1.0

### Repro steps.

```
ng g component [component-name]
installing component
Error locating module for declaration
	SilentError: No module files found
```

I tried everything mentioned in #https://github.com/angular/angular-cli/issues/2962 to no avail. I moved app.module.ts all over the place and attempted to generate component from varying directory paths, same error.

**Comment by saynot** [comment]
if you have same name with app.*  
in my project , I have app.router.module.ts in src/app . I move it to src/app/routers/app.router.module.ts, the error is hidden.

**Comment by phacic** [comment]
In my case i happen to have another `.angular-cli.json` file in my src folder. Removing it solved the problem

**Comment by Voronchov** [comment]
oh great phacic is right. thank you
