### ISSUE TITLE
Docs: angular/material wrong import

### ISSUE THREAD

**Issue by harilal** [angular/angular-cli#5088]
> Please provide us with the following information:
> ---------------------------------------------------------------
https://github.com/angular/angular-cli/wiki/stories-include-angular-material

The angular MaterialModule import wrong . There is no forRoot() for MaterialModule in the latest release. Only MaterialModule . Please correct it
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by yairtawil** [comment]
try this:
`import {MaterialRootModule} from "@angular/material";`
```
@NgModule({
...
imports:[MaterialRootModule]
)}
```

**Comment by harilal** [comment]
It's a wrong entry in Docs.

**Comment by RicardoVaranda** [comment]
#5128 Posted a PR to fix this.
