### ISSUE TITLE
should add the content of "Global Library Installation" into "Include Bootstrap"

### ISSUE THREAD

**Issue by zhibinr** [angular/angular-cli#5093]
[Include Bootstrap](https://github.com/angular/angular-cli/wiki/stories-include-bootstrap#include-bootstrap) is incomplete, it miss the content of add javascript files, like 
```
"scripts": [
  "../node_modules/jquery/dist/jquery.js",
  "../node_modules/tether/dist/js/tether.js",
  "../node_modules/bootstrap/dist/js/bootstrap.js"
],
```

**Comment by filipesilva** [comment]
@Brocco can you weight in?

**Comment by istiti** [comment]
@zhibinr  i think it's not incomplete and souldn't include these js files, you need get workin bootstrap design using angular. 

> Do you really want something like jquery with angular :S

**Comment by Brocco** [comment]
I do concur that those JS files should not be included, the docs as written are to include bootstrap's CSS, not the behaviors/JS-backed components.

**Comment by zhibinr** [comment]
It's confused with [Global Library Installation](https://github.com/angular/angular-cli/wiki/stories-global-lib).

> Some javascript libraries need to be added to the global scope, and loaded as if they were in a script tag. We can do this using the apps[0].scripts and apps[0].styles properties of .angular-cli.json.
> 
> As an example, to use Bootstrap 4 this is what you need to do:
> 
> First install Bootstrap from npm:
> 
> npm install bootstrap@next
> Then add the needed script files to apps[0].scripts:
> 
> "scripts": [
>   "../node_modules/jquery/dist/jquery.js",
>   "../node_modules/tether/dist/js/tether.js",
>   "../node_modules/bootstrap/dist/js/bootstrap.js"
> ],
> Finally add the Bootstrap CSS to the apps[0].styles array:
> 
> "styles": [
>   "../node_modules/bootstrap/dist/css/bootstrap.css",
>   "styles.css"
> ],
> Restart ng serve if you're running it, and Bootstrap 4 should be working on your app.
