### ISSUE TITLE
what's the purpose to scaffold a tsconfig.json in the root dir?

### ISSUE THREAD

**Issue by royling** [angular/angular-cli#5094]
With the version 1.0.0-rc.0 of cli, a `tsconfig.json` is created in the root dir. **Is this intended or a bug?**  Also noting that there are different config json files created for app/spec/e2e respectively, which are very clear.
- src/tsconfig.app.json
- src/tsconfig.spec.json
- e2e/tsconfig.e2e.json

`ng --version` output:
@angular/cli: 1.0.0-rc.0
node: 7.5.0
os: darwin x64

**Comment by filipesilva** [comment]
You can find some more information about the multiple tsconfigs in https://github.com/angular/angular-cli/pull/4924 and https://github.com/angular/angular-cli/wiki/stories-rc.0-update#one-tsconfig-per-app
