### ISSUE TITLE
Option to use ES2015 Flat ESM format with Angular 4+

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#5097]
Angular 4.0.0-rc.1 changelog : 

> ES2015 Builds
> 
> We now also ship our packages in the ES2015 Flat ESM format. This option is experimental and opt-in (configure your webpack to resolve "es2015" property in package.json over the regular "module" property).

Is it possible to add an option to use this new format in `--ng4` projects ?

I'm impressed by `@angular/cli` rc.0, my only concern is the bundles sizes. With the same app, and manual (but very simple) config of a packager, vendor + main was 1,0Mo with rollup and 1,2Mo with webpack 2 / `@ngtools/webpack` AotPlugin. With `@angular/cli` (prod mode), it's 1,5Mo...

Is at least classic tree shaking with `module: "es2015"` activated by default ?

Would like to help/test, but I don't know where the webpack config is managed in this project.

**Comment by filipesilva** [comment]
I was looking into this yesterday and there wasn't much improvement actually. It stems from webpack not actually doing tree shaking (https://github.com/angular/angular-cli/issues/2901). It's one of the next big action items for webpack so we're waiting for that.

**Comment by cyrilletuzi** [comment]
OK, thanks.

Is there a reason to the current 0,3Mo surplus with `@angular/cli` ? I was using manually AotPlugin of `@ngtools/webpack`, like `@angular/cli`, so I don't understand such an important difference.
