### ISSUE TITLE
ng test not running in rc.0 (probably due to an undocumented breaking change)

### ISSUE THREAD

**Issue by cladera** [angular/angular-cli#5100]
### OS?

Mac OSX Sierra

### Versions.

@angular/cli: 1.0.0-rc.0
node: 6.9.5
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.7

### Repro steps.

1. Update cli from beta.32 to rc.0
2. Try running `ng test`

### The log given by the failure.

The process seems to build the project (twice) right but when it tries to run karma it throws an error saying `no captured browser`. 

### Mention any other details that might be useful.

I created a new project using rc.0 and copied the new tsconfig files to mine and I made it work. So I believe the commit (69e6c71) introduced a breaking change which was not included in the changelog.

**Comment by mikedanylov** [comment]
`ng test` works as expected after creating separate `tsconfig.spec.json` according to the updated blueprint from the commit mentioned above and declaring it in `angular-cli.json` as `"testTsconfig": "tsconfig.spec.json"`.

**Comment by cladera** [comment]
https://github.com/angular/angular-cli/wiki/stories-rc-update explains how to migrate from beta to rc so I'm closing this issue.

However, I still think this change should be listed as a breaking change :)
