### ISSUE TITLE
why is vendor.<..>.bundle.js bigger when you run ng serve --prod vs ng build --prod

### ISSUE THREAD

**Issue by stefanaerts** [angular/angular-cli#5102]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
mac os x

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
![image](https://cloud.githubusercontent.com/assets/3684599/23404059/5b9a8e46-fdb3-11e6-9c6c-5b92c191bc08.png)

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

ng new project
ng build --prod  gives a file of 1.16 MB according log info
ng serve --prod gives a file of 1.45 MB according log info
### The log given by the failure.
> Normally this include a stack trace and some more information.
![image](https://cloud.githubusercontent.com/assets/3684599/23404156/c94729d6-fdb3-11e6-814f-af4c1b6c8d10.png)

### Mention any other details that might be useful.
Why is it showing 1.16 MB and 1.45 MB when it is actually:
1.16 MB file is on the file system 364 KB
1.45 MB file is on the file system 489 KB
![image](https://cloud.githubusercontent.com/assets/3684599/23404221/2b62aa8c-fdb4-11e6-9839-9ce3693d4b17.png)

When i run the dist folder with lite-server i get the expected 364 KB vendor file
So what is ng serve running/doing/adding to the vendor file?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by stefanaerts** [comment]
I updated angular version to angular4.
Now the vendor file is 366KB, so 2 KB bigger.
If i do ng build --prod or ng build --aot --prod --sm=false
it seems  nod difference for a new project -> it stays always 366KB
![image](https://cloud.githubusercontent.com/assets/3684599/23405881/8a6b6f0c-fdbc-11e6-8708-fcd9c7514d2e.png)

**Comment by mattdistefano** [comment]
`ng serve` AFAIK will produce a bigger bundle since the client code for webpack's dev server is included in your bundle.

Also I think the displayed file sizes may include the sourcemaps, though I may be wrong about that.

**Comment by stefanaerts** [comment]
no sourcemaps included.
But thats not the important question.
The important question to me is:
"When i run the dist folder with lite-server i get the expected 364 KB vendor file
So what is ng serve running/doing/adding to the vendor file?"

ng serve makes the file bigger,why?

**Comment by mattdistefano** [comment]
I'm 90% sure that the extra bytes are the webpack dev server code to enable HMR and livereload.

**Comment by stefanaerts** [comment]
Ok,Thx. What is HMR?

**Comment by mattdistefano** [comment]
Hot module reloading - kind of a component-level live reloading.
