### ISSUE TITLE
can not find module "socket.io-client".

### ISSUE THREAD

**Issue by ZikZakJainy** [angular/angular-cli#5103]
My project is working fine in Angular CLI "1.0.0-beta.15" but when, I updated Angular CLI from "1.0.0-beta.15" to "1.0.0-beta.32.3" it's shown an error **"module socket.io-client not found"** when, I am importing socket.io-client  as like - **import * as io from 'socket.io-client'** .

**Comment by JGdijk** [comment]
did you try to install it with typings? 

npm install @types/socket.io-client

**Comment by ZikZakJainy** [comment]
Thanks for advice 🥇

**Comment by filipesilva** [comment]
Closing as answered.
