### ISSUE TITLE
ng server - caseSensitive URL?

### ISSUE THREAD

**Issue by montella1507** [angular/angular-cli#5107]
hello,

is the new NG (32.3) case sensitive during  NG SERVE? 

In previous version it worked with url /something.jpg to link file /SoMeThing.jpg. Now it has to be exactly the same.

If there is a change to case sensitive serving, i think it should be added as breaking change.

**Comment by filipesilva** [comment]
I'm not aware of a change in serve behaviour regarding case. In what beta did you observe the case insensitive behaviour?

**Comment by montella1507** [comment]
Well, ATM we build our global SCSS style with GULP and GULP-SASS. Built SCSS (css) is then linked directly in index.html. There are (were) two main reasons for that:

1) It was way faster than Angular-cli way - GULP SCSS rebuiilt = 150ms + refresh of browser - 
 versus Angular-cli  8sec (2sec after beta 31) + refresh browser

2) The biggest reason is, there work sourceMaps correctly. We still havent found any solution how to build GLOBAL SCSS file quickly  and with WORKING sourcemaps. 

Despite of that.. i try everytime to build our Global SCSS with every new version of Angular-cli -> To try. If the source maps are already working correctly ..  In beta 32.3 i have realized the  images are not working, because of case-senstive behaviour.  

So maybe.. it is case-sensitive from startm but it used to be case insensitive in case, when you linked CSS directly in .html (it wasnt processed by webpack). 


p.s.:
Is there a WAY / tutorial how to build Global SCSS where:
1) SourceMaps work
2) Its quick (<8sec)
3) Browser refreshes correctly
4) Livereload works?

**Comment by tomwanzek** [comment]
The change in case sensitivity replicates for me. I migrated an app from `beta.30` to `rc.1` and noticed the same change with images in the `assets` folder. Running on a Windows 10 machine.

**Comment by MarkoCen** [comment]
Any updates on this issue?

**Comment by filipesilva** [comment]
We've gone through a couple of major versions so far so I don't think this behaviour will change. We're not looking at making the dev server case insensitive because some file systems are case insensitive.

**Comment by Zarepheth** [comment]
Can the dev server's case sensitivity match that of the host machine's file system?

I dislike having images fail because the file name casing does not match the actual file name. When using IIS Express, we had no problem, but now that I'm working with `ng serve`, this difference is case is breaking things. I'd rather not dig through 300+ files to find the mismatched image file names...
