### ISSUE TITLE
barrel not created in manually created folder after creating services in it

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#511]
*SUGGESTION* when I run these commands, no barrel is created in the folder. I think it should be.

```
mkdir speaker-services && cd speaker-services
ng g service svc1
ng g service svc2
```
HANS - agreed. That's a bug.

cc @hansl @Brocco

**Comment by johnpapa** [comment]
did this one make it into the latest PR batch?

**Comment by hansl** [comment]
Not that I know of.

**Comment by shairez** [comment]
@hansl still relevant after the ngModules update?
If so, please assign me

**Comment by Brocco** [comment]
@shairez this is no longer relevant, the idea of barrels while still valid will be manually created and used by devs, not by the CLI. The reason is that their usage will be on a case-by-case basis and therefore not determinable by the CLI based upon any set of rules.

**Comment by shairez** [comment]
OK thanks @Brocco !
