### ISSUE TITLE
get error when running ng serve on newly created app when app is on d:\ drive

### ISSUE THREAD

**Issue by andromeda7** [angular/angular-cli#5115]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.

node: v7.5.0
npm: 4.1.2
@angular/cli: 1.0.0-rc.0

### Repro steps.
App was newly created with CLI 1.0.0-rc.0 no modifications were made.

### The log given by the failure.

ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve 'D:\' in 'D:\!Nauka-Programowania\cliApp'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve 'D:\' in 'D:\!Nauka-Programowania\cliApp'
 @ multi ./src/polyfills.ts

ERROR in multi ./src/styles.css
Module not found: Error: Can't resolve 'D:\' in 'D:\!Nauka-Programowania\cliApp'
 @ multi ./src/styles.css

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'D:\' in 'D:\!Nauka-Programowania\cliApp':
  Error: Can't resolve 'D:\' in 'D:\!Nauka-Programowania\cliApp'

  - compiler.js:76
    [cliApp]/[html-webpack-plugin]/lib/compiler.js:76:16

...

### Mention any other details that might be useful.
It works fine when the same proces is reproduced on drive c:\

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Uhm I actually do all of my CLI work on the `d:\` drive. I haven't found this issue so far.

Do you have a repo I can see that shows this?

**Comment by BarbaraWiacek** [comment]
Try changing the folder name so it doesn't contain the "!"

**Comment by andromeda7** [comment]
After removing ‘!” mark it works as it supposed to. 

THX for help.

Wysłane z aplikacji Poczta dla Windows 10

Od: BarbaraWiacek
Wysłano: czwartek, 20 kwietnia 2017 14:29
Do: angular/angular-cli
DW: andromeda7; Author
Temat: Re: [angular/angular-cli] get error when running ng serve on newlycreated app when app is on d:\ drive (#5115)

Try changing the folder name so it doesn't contain the "!"

**Comment by filipesilva** [comment]
Closing as answered, thanks @BarbaraWiacek 👍
