### ISSUE TITLE
https://cli.angular.io gives blank page on Safari 10.0.3

### ISSUE THREAD

**Issue by mmucklo** [angular/angular-cli#5122]
### OS?
Mac OS 10.12.3

### Safari
Version 10.0.3 (12602.4.8)

cli.angular.io loads on Chrome and Firefox, but not Safari 10.0.3

Happens on multiple different machines.

**Comment by mattdistefano** [comment]
Can confirm. Safari doesn't like the height: 100% on `.mdl-layout`.

**Comment by hansl** [comment]
Fixed.
