### ISSUE TITLE
Cannot find name 'localStorage' or any other built-in modules after updating to RC

### ISSUE THREAD

**Issue by ndkcha** [angular/angular-cli#5124]
### OS
macOS Sierra 10.12.3

### Versions.
@angular/cli: 1.0.0-rc.0
node: 7.6.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

### Repro steps.
I recently re-installed my operating system. And i installed latest versions of node and angular-cli.
1. Created new app using `ng new <name>`
2. Created a new component which required storing data in localStorage.

In code editor, it shows compiler error. But it runs without error. I also have an application which was created by angular-cli-beta. It doesn't show any compiler error in that.

*I don't know if it is an issue for angular-cli or vscode. Do let me know.*

### The log given by the failure.
<img width="1280" alt="screen shot 2017-03-01 at 12 13 15 pm" src="https://cloud.githubusercontent.com/assets/8328240/23448873/89c353d6-fe79-11e6-8bf7-f6e3a463e579.png">

### Mention any other details that might be useful.
I also have uploaded the code on github.
You can find [repository here](https://github.com/ndkcha/vscode-issue/tree/issue-21543).
My [tsconfig.json](https://github.com/ndkcha/vscode-issue/blob/issue-21543/tsconfig.json) file.
My [package.json](https://github.com/ndkcha/vscode-issue/blob/issue-21543/package.json) file.
I have commented on a specific file to elaborate the issue. You can it [here](https://github.com/ndkcha/vscode-issue/blob/issue-21543/src/app/shared/toolbar/toolbar.component.ts) (logout function at the bottom of the page)

I hope this helps.

**Comment by ndkcha** [comment]
There was an issue with tsconfig. Added a field there and it was working.

**Comment by fabianderijk** [comment]
Can you explain what the issue was and how you fixed this? I've got almost the same error.

**Comment by ndkcha** [comment]
I updated my tsconfig.json. added `dom` in `lib` property of `compilerOptions` ([like this](https://github.com/ndkcha/vscode-issue/blob/issue-21543/tsconfig.json)) and restarted IDE. And it worked.

**Comment by carlosfaria94** [comment]
Same problem here.

The above solution solve the problem. Thanks @ndkcha

**Comment by guenam** [comment]
Thanks @ndkcha. I didn't even need to restart VS Code.
