### ISSUE TITLE
two blanks are added in css strings after special chars like german umlauts

### ISSUE THREAD

**Issue by dschemmel** [angular/angular-cli#5125]
### OS?
> Windows 10

### Versions.
> 1.0.0-rc.0

### Repro steps.
> 
ng new test
ng serve (showing "app works")
then add `h1:before { content: "zurück--"; }` in app.component.css
browser now shows "zurü  ck--app works"

reason for this: the css is compiled to:
`exports.push([module.i, "h1:before { content: \"zur\\FC  ck\"; }\r\n", ""]);`
(two additional spaces after \\FC)

this happens only, when a hex-code [0-9a-fA-F] follow after the special character.

### Mention any other details that might be useful.
css file must be utf (utf-8 in my case)

**Comment by filipesilva** [comment]
Sounds like a bug. Thank you for reporting.

**Comment by aduarteraposo** [comment]
I have exactly the same problem.

**Comment by sumitarora** [comment]
@dschemmel @aduarteraposo Tried to replicate the issue seems like it works exactly the same on a blank webpack project too and is a CSS issue, not the CLI. To fix the issue you can do below things.
- use `html` code for `ü`
- you can set  `Content-Type: text/css; charset=utf-8` for css files.
