### ISSUE TITLE
ng xi18n fails silently

### ISSUE THREAD

**Issue by ocombe** [angular/angular-cli#5129]
### OS?
Windows 10

### Versions.
@angular/cli: 1.0.0-rc.0
node: 6.9.5
os: win32 x64
@angular/animations: 4.0.0-rc.1
@angular/common: 4.0.0-rc.1
@angular/compiler: 4.0.0-rc.1
@angular/compiler-cli: 4.0.0-rc.1
@angular/core: 4.0.0-rc.1
@angular/forms: 4.0.0-rc.1
@angular/http: 4.0.0-rc.1
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0-rc.1
@angular/platform-browser-dynamic: 4.0.0-rc.1
@angular/platform-server: 4.0.0-rc.1
@angular/router: 4.0.0-rc.1
@angular/cli: 1.0.0-rc.0

### Repro steps.
```sh
git clone https://github.com/StephenFluin/ames.git
cd ames
git checkout 64bde5ea0958a9bb325126a2e297e8c6631b0689
npm install
ng xi18n
```
---> no log, the command just ends after a while but nothing happened and you don't know why.

But if you manually call xi18n like this:

```sh
./node_modules/.bin/ng-xi18n -p src/tsconfig.json
```

You should see the following error:
```
Error: Could not mark an element as translatable inside a translatable section ("
                Type
                <select [(ngModel)]="newContent.type">
                    [ERROR ->]<option i18n>Presentation</option>
                    <option i18n>Blog Post</option>
            "): ames/src/app/developers/expert-form.component.ts@43:20
Could not mark an element as translatable inside a translatable section ("l)]="newContent.type">
                    <option i18n>Presentation</option>
                    [ERROR ->]<option i18n>Blog Post</option>
                    <option i18n>Other</option>
                </s"): ames/src/app/developers/expert-form.component.ts@44:20
Could not mark an element as translatable inside a translatable section ("18n>Presentation</option>
                    <option i18n>Blog Post</option>
                    [ERROR ->]<option i18n>Other</option>
                </select>
            </label>
"): ames/src/app/developers/expert-form.component.ts@45:20
    at ames\node_modules\@angular\compiler\bundles\compiler.umd.js:21695:25
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Extraction failed
```

Which in this case is because there is an error in a template with embedded i18n tags.

### The log given by the failure.
There is no log, and that's the problem. Outputting errors to the terminal is important because it lets you fix it instead of wondering why it failed. Even the `--verbose` option doesn't output this error

**Comment by yechenchao** [comment]
I have the same problem too, the error log is very important.
