### ISSUE TITLE
Barrels not being updated 

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#513]
*BUG* I generated `/app/shared/modal` for a modal component, then cd’d into that `modal` folder and ran `ng g service modal`. It created the service properly, but it did not update the barrels properly. The `/app/shared/index.ts` barrel was reaching into the `./modal/modal.service` and `./modal` …. and the `/app/shared/modal/index.ts` did not export the new service.

cc @Brocco @hansl

**Comment by shairez** [comment]
@hansl I'm guessing this is not relevant because we stopped generating barrels, right?

**Comment by hansl** [comment]
Correct. I'm closing this. Thanks!
