### ISSUE TITLE
Uncaught (in promise): Error: DI Error / Unhandled Promise rejection: No provider for t! ; Zone: angular ; Task: Promise.then

### ISSUE THREAD

**Issue by mitosandov** [angular/angular-cli#5130]
> Windows 10 and apache server

### Versions.
@angular/cli: 1.0.0-rc.0
node: 6.10.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

### Repro steps.
> i had a project made via cli beta 19-3 and using angular 2.2, updated it to latest version of cli by installing it, making a new project with it and replacing the generated *.json/*.js  files in the project and  polifils + *.json files in the src folder   with the one from the newly generated version of the new cli project

Now everything works fine with ng serve --dev, buuut when i do ng serve --prod i receive error from the log it seems similar to [http://stackoverflow.com/questions/42032943/angular2-no-provider-for-t-and-uncaught-in-promise-error-di-error](url) but i am not using ng2-Toastr ... i am using 
"angular2-cookie": "^1.2.5",
"primeng": "^2.0.0",  
as only none standart libs

### The log given by the failure.
[http://i.imgur.com/ZCgWCh7.jpg](url)

**Comment by mattdistefano** [comment]
Seems likely it's https://github.com/salemdar/angular2-cookie/issues/37

**Comment by filipesilva** [comment]
Closing as answered, thanks @mattdistefano !
