### ISSUE TITLE
ng serve doesn't load or reload the page when Chrome DevTools are open

### ISSUE THREAD

**Issue by stefanedberg** [angular/angular-cli#5134]
### OS?
macOS Sierra 10.12.3 (16D32)

### Versions.
@angular/cli: 1.0.0-rc.0
node: 6.10.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

### Repro steps.
If i manually reload http://localhost:4200 with DevTools open in Google Chrome 56.0.2924.87 (64-bit) it loads the html-file but nothing more. The only request listed in the network pane is the initial html-file request. The file watch feature also stops working. If I close the DevTools it works as expected. Also works in latest Firefox and Safari.

Worked until recently. My guess is that it happened when i updated npm packages. angular-cli 1.0.0-beta.30 -> 1.0.0-rc.0. Doesn't work when I reset to 1.0.0-beta.30.

Edit: Also tested with a new project and disabled all Chrome extensions. Same problem.

How to reproduce:
ng new lol
cd lol
ng serve

### The log given by the failure.
No error in the console or terminal.

**Comment by instantepiphany** [comment]
Possibly related to https://github.com/angular/angular-cli/issues/5117

**Comment by instantepiphany** [comment]
I believe this may be fixed by a pending PR: https://github.com/angular/angular-cli/pull/5164

**Comment by stefanedberg** [comment]
Just noticed that the problem persists even after running ng build --prod and publishing to staging server. The application works as expected when closing the DevTools.

**Comment by instantepiphany** [comment]
Easy thing to forget you changed! Better close the issue.
