### ISSUE TITLE
ERROR in AppModule is not an NgModule

### ISSUE THREAD

**Issue by gkucmierz** [angular/angular-cli#5135]
### OS?
OSX El Capitan

### Versions.
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0-rc.0
node: 6.9.1
os: darwin x64
@angular/common: 4.0.0-rc.1
@angular/compiler: 4.0.0-rc.1
@angular/core: 4.0.0-rc.1
@angular/forms: 4.0.0-rc.1
@angular/http: 4.0.0-rc.1
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0-rc.1
@angular/platform-browser-dynamic: 4.0.0-rc.1
@angular/router: 4.0.0-rc.1
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 4.0.0-rc.1
```

### Repro steps.
```ng serve```

### The log given by the failure.
```
ERROR in AppModule is not an NgModule

ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in '/Users/gkucmierz/learn/coin-tools'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in '/Users/gkucmierz/learn/coin-tools'
 @ multi ./src/polyfills.ts
webpack: Failed to compile.
```

### Mention any other details that might be useful.
After solved issue with typescript #5131 I have another issue after upgrade ng cli to 1.0.0-rc.0

**Comment by RicardoVaranda** [comment]
Hey @gkucmierz ,

Can you give me the repro steps to get this issue, I'm not really sure if you are getting this after a new generated project or after upgrading an existing one, the more info the better so that we can reproduce this ourselves to narrow down the issue, Thank you :)

**Comment by gkucmierz** [comment]
@RicardoVaranda sure
It is project generated with:
```1.0.0-beta.28.3```
https://github.com/gkucmierz/coin-tools/blob/master/package.json#L27

**Comment by RicardoVaranda** [comment]
It seems you still have an old instance of the cli installed in your local project:

https://github.com/gkucmierz/coin-tools/blob/master/package.json#L27

Can you delete this using:
```npm uninstall --save angular-cli```

Here is an updated package json for your project:

```
{
  "name": "coin-tools",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular-redux/store": "^6.0.1",
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "@angular/material": "^2.0.0-beta.2",
    "@ngrx/core": "^1.2.0",
    "@ngrx/store": "^2.2.1",
    "base64-js": "^1.2.0",
    "hammerjs": "^2.0.8",
    "jsqr": "^0.2.1",
    "ng2-slim-loading-bar": "^2.4.0",
    "ngrx-store-logger": "^0.1.7",
    "ts-helpers": "^1.1.1",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.0",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "~2.0.0"
  }
}

```

**Comment by gkucmierz** [comment]
Nope, I had indeed and it was showing me this warning:
```
The package "angular-cli" has been renamed to "@angular/cli". The old package will be deprecated soon.

Please take the following steps to avoid issues:
"npm uninstall --save angular-cli" 
```
After I uninstalled it warning disappeared, but there is still that error.

**Comment by RicardoVaranda** [comment]
Do the following steps within your project and report back:

```
rm -rf node_modules
npm install
ng serve
```

**Comment by gkucmierz** [comment]
```ls node_modules/ | grep angular-cli``` returns nothing

**Comment by gkucmierz** [comment]
```
MacBook-Pro-gkucmierz:coin-tools gkucmierz$ ls -al node_modules/ | grep angular
drwxr-xr-x   16 gkucmierz  staff    544  1 mar 12:02 @angular
drwxr-xr-x    3 gkucmierz  staff    102 19 lut 17:33 @angular-redux
```

**Comment by RicardoVaranda** [comment]
It seems your are missing a dependency of ngrx-store-freeze also:

```
npm i --save-dev ngrx-store-freeze
```

I was able to do a git pull and ng serve with no errors after installing that dependency:

![image](https://cloud.githubusercontent.com/assets/6951312/23463135/683a569c-fe88-11e6-97b3-a1f9d2a38443.png)

**Comment by gkucmierz** [comment]
After reinstalling all packages, all systems are working, thx!

**Comment by jasonspick** [comment]
I cleared node_modules and reinstalled. no luck. 
`{
  "name": "Atlas",
  "version": "0.0.1",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "install": "napa",
    "start": "ng serve",
    "test": "ng test",
    "lint": "ng lint",
    "modernizr": "modernizr -c modernizr-config.json -d src/modernizr.js",
    "postinstall": "node ./node_modules/protractor/bin/webdriver-manager update",
    "e2e": "ng e2e"
  },
  "private": true,
  "napa": {
    "jquery.flot.spline": "miloszfalinski/jquery.flot.spline",
    "ika.jvectormap": "kakirigi/ika.jvectormap"
  },
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.0.0",
    "@angular/router": "^4.0.0",
    "ag-grid": "8.1.0",
    "ag-grid-ng2": "8.0.0",
    "angular2-color-picker": "git://github.com/zefoy/angular2-color-picker.git#npm-package",
    "angular2-datatable": "0.5.3",
    "angular2-google-maps": "0.17.0",
    "angular2-infinite-scroll": "0.3.1",
    "angular2-jwt": "^0.1.28",
    "angular2-text-mask": "5.0.0",
    "angular2-toaster": "2.0.0",
    "angular2-tree-component": "2.8.2",
    "bootstrap": "3.3.7",
    "chart.js": "2.5.0",
    "codemirror": "5.24.2",
    "core-js": "2.4.1",
    "easy-pie-chart": "2.1.7",
    "flot": "0.8.0-alpha",
    "font-awesome": "4.7.0",
    "fullcalendar": "3.2.0",
    "jqcloud2": "2.0.2",
    "jquery": "3.1.1",
    "jquery-slimscroll": "1.3.8",
    "jquery-sparkline": "2.4.0",
    "jquery.browser": "0.1.0",
    "jquery.flot.tooltip": "github:krzysu/flot.tooltip",
    "lodash": "4.17.4",
    "modernizr": "3.3.1",
    "moment": "2.17.1",
    "ng2-bootstrap": "1.3.3",
    "ng2-charts": "1.5.0",
    "ng2-dnd": "2.2.2",
    "ng2-file-upload": "1.2.0",
    "ng2-img-cropper": "0.7.7",
    "ng2-select": "1.2.0",
    "ng2-table": "1.3.2",
    "ng2-tag-input": "0.8.4",
    "ng2-translate": "5.0.0",
    "ng2-validation": "3.8.0",
    "node-sass": "3.13.0",
    "rxjs": "5.1.0",
    "screenfull": "3.0.2",
    "simple-line-icons": "2.4.1",
    "spinkit": "1.2.5",
    "summernote": "0.8.2",
    "ts-helpers": "1.1.1",
    "weather-icons": "github:erikflowers/weather-icons",
    "whirl": "github:jh3y/whirl",
    "zone.js": "0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "2.4.0",
    "@types/codemirror": "0.0.38",
    "@types/jasmine": "2.5.38",
    "@types/lodash": "4.14.58",
    "@types/moment": "2.13.0",
    "@types/node": "6.0.60",
    "codelyzer": "2.0.0-beta.4",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.1",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "0.2.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-read-json": "1.1.0",
    "loaders.css": "0.1.2",
    "napa": "2.3.0",
    "ngrx-store-freeze": "^0.1.9",
    "protractor": "5.1.0",
    "ts-node": "2.0.0",
    "tslint": "4.4.2",
    "typescript": "2.2.2",
    "webdriver-manager": "10.2.5"
  }
}
`

**Comment by laurentsd** [comment]
> I cleared node_modules and reinstalled. no luck. Using Angular 4, angular cli 1.0.0 and typescript 2.2.2

same here

**Comment by Nasruddin** [comment]
I solved the issue by updating Typescript version to "~2.3.0"
