### ISSUE TITLE
Jasmine HTML report not displayed when code coverage enabled during test

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular-cli#5136]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OSX Yosemite

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
@angular/cli: 1.0.0-rc.0
node: 6.9.5
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

1. Create a new application
2. Run `npm test`
3. Note test results are displayed in the karma browser window above `app works!`
4. Run `npm test -- --code-coverage`
5. Note test results are not displayed and `app works!` is displayed

### The log given by the failure.
> Normally this include a stack trace and some more information.

N/A

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Zyzle** [comment]
From what I can see this is a simple fix in projects karma.conf.js but not sure if it has any other issues:

```diff
--- a/karma.conf.js
+++ b/karma.conf.js
@@ -32,7 +32,7 @@ module.exports = function (config) {
       environment: 'dev'
     },
     reporters: config.angularCli && config.angularCli.codeCoverage
-              ? ['progress', 'coverage-istanbul']
+              ? ['progress', 'coverage-istanbul', 'kjhtml']
               : ['progress', 'kjhtml'],
     port: 9876,
     colors: true,

```

**Comment by delasteve** [comment]
@Zyzle, I don't believe it will have any issues. Thanks for the PR!

**Comment by hansl** [comment]
I pulled the plug on this one because it's a change in the output of the CLI and will have to wait until at least 1.1. Will keep the issue open as something work on.

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/6160.
