### ISSUE TITLE
When running `ng new myapp` we should generate `/src/client/assets`

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#514]
*SUGGESTION* When running `ng new myapp` we should generate `/src/client/assets`

cc @Brocco @hansl

**Comment by jkuri** [comment]
aren't we using `public/` for that?

**Comment by cgmartin** [comment]
@jkuri Thanks, I totally missed `public/` at the root level of project. Just now looking at build command, it already copies everything under `public/` (any static assets) to `dist/`. Going to close my PR unless @johnpapa had a different intent/use-case for this feature request.

**Comment by johnpapa** [comment]
is that what public is for? assets? if so, ok
