### ISSUE TITLE
ng test fails when using ngrx and module.Id

### ISSUE THREAD

**Issue by alvipeo** [angular/angular-cli#5143]
### OS?
Win 10 x64

### Versions.
RC.0

### Repro steps.
use moduleId in @Component() decorator in a project where @nxrx is used. Run 'ng test' -> get weird errors.

### The log given by the failure.
Module build failed: TypeError: Cannot read property 'getChildAt' of undefined
    at refactor.findAstNodes.filter.forEach (E:\Documents\Visual Studio 2015\Projects\prj\node_modules\@ngtools\webpack\src\loader.js:221:54)
    at Array.forEach (native)
    at _removeModuleId (E:\Documents\Visual Studio 2015\Projects\prj\node_modules\@ngtools\webpack\src\loader.js:215:10)
    at Promise.resolve.then.then (E:\Documents\Visual Studio 2015\Projects\prj\node_modules\@ngtools\webpack\src\loader.js:298:33)

**Comment by hansl** [comment]
Hi @alvipeo, I tried reproducing this but couldn't. Could you give me a repository or some code example? What does your Component looks like?

**Comment by alvipeo** [comment]
@hansl thanks for looking into this. Can I give you the link to the private repo? I have it in VSTS. I will need your MS account. Or I can zip it and give a private link (via email). Sorry, can't make that repo public.

**Comment by yusijs** [comment]
I'm getting the same error, without ngrx in my project (although with angular-material):

> ERROR in ./src/app/home/home.component.ts
> Module build failed: TypeError: Cannot read property 'getChildAt' of undefined

and 

> ERROR in ./src/app/help/help.component.ts
> Module build failed: TypeError: Cannot read property 'getChildAt' of undefined

I'm also getting this:

> code: 'ENOENT',
>   errno: 34,
>   message: 'no such file or directory',
>   path: '/_karma_webpack_/src/polyfills.ts' }

Not certain if it's a related issue, but same module build error at least (I'm on rc.1) 

Wrote up a quick repo that reproduces the error for me. 

ng -v:

> @angular/cli: 1.0.0-rc.1
> node: 6.10.0
> os: linux x64
> @angular/common: 2.4.9
> @angular/compiler: 2.4.9
> @angular/core: 2.4.9
> @angular/forms: 2.4.9
> @angular/http: 2.4.9
> @angular/material: 2.0.0-beta.2
> @angular/platform-browser: 2.4.9
> @angular/platform-browser-dynamic: 2.4.9
> @angular/router: 3.4.9
> @angular/cli: 1.0.0-rc.1
> @angular/compiler-cli: 2.4.9


Hope this helps :)
