### ISSUE TITLE
ng xi18n takes 3 times longer than it should to compile

### ISSUE THREAD

**Issue by ocombe** [angular/angular-cli#5144]
### OS?
Windows 10

### Versions.
@angular/cli: 1.0.0-rc.0
node: 6.9.5
os: win32 x64
@angular/animations: 4.0.0-rc.1
@angular/common: 4.0.0-rc.1
@angular/compiler: 4.0.0-rc.1
@angular/compiler-cli: 4.0.0-rc.1
@angular/core: 4.0.0-rc.1
@angular/forms: 4.0.0-rc.1
@angular/http: 4.0.0-rc.1
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0-rc.1
@angular/platform-browser-dynamic: 4.0.0-rc.1
@angular/platform-server: 4.0.0-rc.1
@angular/router: 4.0.0-rc.1
@angular/cli: 1.0.0-rc.0

### Repro steps.
Use the following commands to checkout the repo:
```sh
git clone https://github.com/ocombe/ames.git
cd ames
git checkout  ng-xi18n-bug
npm install
```

Then use the following 2 commands to compare the current ng cli i18n generation and the manual ng-xi18n generation:
```sh
npm run i18n:ng
npm run i18n:bin
```

Both of these commands do the same thing, but the first one uses `ng xi18n` when the second one directly use the ng-xi18n binary.
As you can see, the ng cli implementation takes ~3 times longer (30s instead of 10s) because it does a full compilation of the project with ngc. This is no longer necessary for ng-xi18n to work (this was fixed here: https://github.com/angular/angular/pull/14115)

**Comment by hansl** [comment]
We need a full compilation in our case because we run the resources (templates and styles) through web pack to build them. For example, you can use `styleUrls: [ "some-file.sass" ]` and the SASS will be compiled to CSS before being passed to xi18n.

We might be able to make performance improvements in the future, but certainly not in the short term.

**Comment by ocombe** [comment]
CSS files are not really needed for the i18n extractor, but it makes sense for templates files yes
