### ISSUE TITLE
single quotes as default in lint config?

### ISSUE THREAD

**Issue by wolfgangmeyers** [angular/angular-cli#5151]
I noticed that single quotes seem to be the default setting in the lint config when generating a new project. Any reason why? The coding guidelines recommend double quotes for strings: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines

> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
Please note those are the Microsoft guidelines.

The CLI team discusses really closely with the Angular style guide team (available [here](https://angular.io/docs/ts/latest/guide/style-guide.html)). In cases where the Angular style guide lacks guidance we use the Google JS style guides when possible (see [here](https://google.github.io/styleguide/jsguide.html)), which recommends single quote for strings.

You can file an issue on the Style Guide itself ([here](https://github.com/angular/angular.io/issues)).
