### ISSUE TITLE
Suggestion: allow configuration of a base directory for components to be created in

### ISSUE THREAD

**Issue by kibbled** [angular/angular-cli#5152]
Currently
`ng generate component my-new-component`

Will always create the new component directory in the root of the app. Many developers like to have all components nested under a shared directory, example: app/components/

I'd propose a new property in the angular-cli.json under apps named componentsDir

`  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "componentsDir": "components"`

**Comment by clydin** [comment]
The command should generate the component from the current working directory within the project.

**Comment by 1-0-1** [comment]
This works:

ng generate component shared/my-new-component

**Comment by sumitarora** [comment]
@kibbled Running command `ng g component components/Test` would generate components in the specified directory.
```
