### ISSUE TITLE
Uncaught ReferenceError: Invalid left-hand side expression in postfix operation

### ISSUE THREAD

**Issue by sarn3792** [angular/angular-cli#5156]
Hi.

When I run ng build --prod command the following error is shown:
![error_](https://cloud.githubusercontent.com/assets/9375416/23487939/0aa056ae-feaf-11e6-9794-fc54f9d8fded.png)

After that, I copy the files within dist folder and past them onto IIS folder and this error is thrown:
![image](https://cloud.githubusercontent.com/assets/9375416/23487990/5e0dda28-feaf-11e6-9b9c-bf772a687caf.png)

It's important to mention that when the project is running by ng serve runs without errors
![image](https://cloud.githubusercontent.com/assets/9375416/23488017/8fb46a88-feaf-11e6-9875-b3d2d07a2e87.png)

I'm using ng2-charts and bootstrap.

The source code is on: https://github.com/sarn3792/CRMInformation

Hope you can help me!

Thanks :)

**Comment by sarn3792** [comment]
Sorry but I'm a beginner in angular2. Should I remove my project's node_modules path, then run the above commands and after that recreate my project?

Thanks!

**Comment by Brocco** [comment]
No problem.

I think the first thing you should do is update your version of the CLI.

Run these command in sequence to uninstall, clean your npm's local cache and re-install the latest verision
```bash
npm uninstall angular-cli -g
npm cache clean
npm install @angular/cli -g
```

With that being done, create a test project and build to ensure we're at a good point.
```bash
ng new test-project
cd test-project
ng build -prod
```
Now copy the dist folder to your IIS folder and verify if it is working or not.

If it's not working, please post your log from the prod build and any errors in the browser's console.

If it is working, I would suggest creating a new project and moving your CRM project's code into the new project.

**Comment by erlingne** [comment]
This issue is caused by the `uglifyjs-webpack-plugin` implementation of `uglify-js@2.8.0`. 
`uglify-js@2.8.1`  was quickly released for compability.

See: 
https://github.com/mishoo/UglifyJS2/issues/1516

**Comment by sarn3792** [comment]
After that @Brocco instructions my project is working correctly.

Thanks so much!
