### ISSUE TITLE
AOT caused runtime error with APP_INITIALIZER code

### ISSUE THREAD

**Issue by joehauw** [angular/angular-cli#5158]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
> @angular/cli: 1.0.0-rc.0
node: 6.10.0
os: win32 x64

### Repro steps.
> The app is an CLI project, but the service invoked by APP_INITIALIZER is an npm package angular 2 service library.

In app.module.ts - here is the code:

import { StartupConfigService } from 'my-startup-config/dist/main';
import { APP_INITIALIZER } from '@angular/core';
import { Utilities } from 'my-utilities/dist/main';
import { environment } from '../environments/environment';
const globalConfigPath: string = Utilities.getConfigPath(environment.configPath);

providers: [
    StartupConfigService,
    {
      provide: APP_INITIALIZER,
      useFactory(config: StartupConfigService) { return function() { config.load(globalConfigPath); } },
      deps: [StartupConfigService], multi: true
    }
]

It works fine for both dev & prod mode in beta.25.5 version.

After upgraded to rc.0, still no issue in dev mode, but got run time error in prod mode.
It compiled without error, but when I ran it, got a blank page and error below.

### The log given by the failure.
> Normally this include a stack trace and some more information.

Uncaught TypeError: t[o] is not a function
    at new t (vendor.0d0ad7751ef2b4618eaf.bundle.js:190)
    at e.createInternal (main.16783d9958956f383ed2.bundle.js:1)
    at e.create (vendor.0d0ad7751ef2b4618eaf.bundle.js:1082)
    at t.create (vendor.0d0ad7751ef2b4618eaf.bundle.js:1082)
    at vendor.0d0ad7751ef2b4618eaf.bundle.js:1005
    at t.invoke (polyfills.4c0ce7b93680c8a51db9.bundle.js:36)
    at Object.onInvoke (vendor.0d0ad7751ef2b4618eaf.bundle.js:254)
    at t.invoke (polyfills.4c0ce7b93680c8a51db9.bundle.js:36)
    at n.run (polyfills.4c0ce7b93680c8a51db9.bundle.js:36)
    at t.run (vendor.0d0ad7751ef2b4618eaf.bundle.js:254)
    at e._bootstrapModuleFactoryWithZone (vendor.0d0ad7751ef2b4618eaf.bundle.js:1005)
    at e.bootstrapModuleFactory (vendor.0d0ad7751ef2b4618eaf.bundle.js:1005)
    at Object.x35b (main.16783d9958956f383ed2.bundle.js:1)
    at r (inline.097b9d0557e2934e0cd1.bundle.js:1)
    at Object.2 (main.16783d9958956f383ed2.bundle.js:1)

### Mention any other details that might be useful.

The library currently has only 1 service - which read a json file and load it to its key-value store.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mickymots** [comment]
work around on this issue:

Step 1 : export a factory function from StartupConfigService

export function ConfigInitializer   (configService: StartupConfigService) {
  return () => (configService.load())
}

Step 2: Update provider to use this factory function

 { provide: APP_INITIALIZER, useFactory: ConfigInitializer, deps: [StartupConfigService], multi: true },

**Comment by joehauw** [comment]
Tried it already, and got the same error. Thanks for the suggestion though.

**Comment by joehauw** [comment]
Resolved - by changing mickymots suggestion as follow:

export function ConfigInitializer (configService: StartupConfigService) {
return function () { configService.load(); };
}

Thanks again mickymots !

Note: is this how we should do it now ? Any comment or feedback is appreciated before I close the issue. Thanks.

**Comment by hansl** [comment]
Yes, non-exported functions are not supported, and you cannot export a lambda or inline function.

**Comment by subarroca** [comment]
I tried that solution but did not work for me. This is what I have:

```
    {
      provide: APP_INITIALIZER,
      useFactory: initSession,
        deps: [
          SessionService,
          AlertCenterService,
          SessionDataService,
          OrganizationService,
          PropertiesService,

          HttpModule
        ],
      multi: true
    }
```

and then

```
export function initSession(sessionService: SessionService) {
  // cannot export a '=>'
  return function () { sessionService.initialLoad(); };
}
```

It keeps throwing
```
ERROR in /home/salvador/projects/mybloo/branches/BBDSDT-1667/src/$$_gendir/app/core/core.module.ngfactory.ts (1,1): Supplied parameters do n
ot match any signature of call target.
```

**Comment by joehauw** [comment]
Looks like your SessionService might have dependency that need to be included as parameters in initSession.

**Comment by subarroca** [comment]
sorry, my fault, you're totally right.Thanks! For future reference I leave the code as I have it now:
The first part remains the same, only the second block changes
```
export function initSession(
  sessionService: SessionService,
  alertCenterService: AlertCenterService,
  sessionDataService: SessionDataService,
  organizationService: OrganizationService,
  propertiesService: PropertiesService,
  http: Http
) {
  return () => sessionService.initialLoad();
}
```

**Comment by cleitonCotrin** [comment]
this.appInits[i] is not a function

Same problem...
ng build --prod aot or ng build --prod not working for me.
Any solution ??

**Comment by jakehockey10** [comment]
I'm still running into this issue, even if I use the workarounds suggested in this thread and similar ones.  Even if I don't use any lambdas (switch to just a function) it still complains about lambdas.  Here is my versions:
```
$ ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.2.3
Node: 10.9.0
OS: win32 x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.1
@angular-devkit/build-angular      0.8.1
@angular-devkit/build-ng-packagr   0.8.1
@angular-devkit/build-optimizer    0.8.1
@angular-devkit/build-webpack      0.8.1
@angular-devkit/core               0.7.4
@angular-devkit/schematics         0.7.4
@angular/cli                       6.2.3
@angular/pwa                       0.7.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.2.1
@schematics/angular                0.7.4
@schematics/update                 0.8.3
ng-packagr                         4.1.1
rxjs                               6.3.3
typescript                         2.9.2
webpack                            4.18.0
```

**Comment by jakehockey10** [comment]
Solution finally:

I have an APP_INITIALIZER as well as an OKTA_CONFIG that I'm providing for through factories.  Both useFactory properties need to point to an exported function.  I was only doing that for the APP_INITIALIZER.
