### ISSUE TITLE
Issue building project for prod after upgrading to rc.0

### ISSUE THREAD

**Issue by AVatch** [angular/angular-cli#5160]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX 10.12.3

### Versions.
> @angular/cli: 1.0.0-rc.0
> node: 7.5.0
> os: darwin x64
> @angular/common: 2.4.8
> @angular/compiler: 2.4.8
> @angular/core: 2.4.8
> @angular/forms: 2.4.8
> @angular/http: 2.4.8
> @angular/material: 2.0.0-beta.2
> @angular/platform-browser: 2.4.8
> @angular/platform-browser-dynamic: 2.4.8
> @angular/router: 3.4.8
> @angular/cli: 1.0.0-rc.0
> @angular/compiler-cli: 2.4.8

### Repro steps.
> This was an application generated with ng-cli and then updated to rc.0 following the guidelines.

### The log given by the failure.

> ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 48:14 in the original .ts file), resolving symbol UniDashboardContainer in /Users/avatchinsky/Development/uni/uni-client/src/app/components/shared/dashboard.container.ts

> ERROR in ./src/main.ts
> Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/avatchinsky/Development/uni/uni-client/src'
> @ ./src/main.ts 4:0-74
> @ multi ./src/main.ts

### Mention any other details that might be useful.

> The builds under dev settings and can be served. This issue arises only when trying to build for prod. Having a hard time parsing the error message so any help would be appreciated

**Comment by mattdistefano** [comment]
What's at line 48 in your dashboard.container.ts?

**Comment by AVatch** [comment]
The issue was being raised since I was doing string interpolation in the Component's `styles` field  (for some quick media queries).
This was not an issue previously when building for prod, but I suppose with all of the library updates it now is. 

I will close this since I don't think anymore this has anything to do w/ the cli package
