### ISSUE TITLE
无法获取未定义或 null 引用的属性“apply”

### ISSUE THREAD

**Issue by ffey** [angular/angular-cli#5161]
Windows  10  angular-cli 1.0.0-rc.0

The code run in Chrome browser or Firefox browser was succeed,but it run in IE(9,10,11) was failed and report the error message '无法获取未定义或 null 引用的属性“apply”'。at 
`function combine(options) {
    return (_a = ((Object))).assign.apply(_a, [{}].concat(options));
    var _a;
}`

**Comment by mattdistefano** [comment]
Check your `polyfills.ts` and make sure you're including everything noted for IE. Most likely the error is `Object.assign` not being present in IE (the polyfills will fix this).

**Comment by ffey** [comment]
thanks.

**Comment by filipesilva** [comment]
Closing as answered.
