### ISSUE TITLE
ng generate doesn't have route blueprint

### ISSUE THREAD

**Issue by kplese** [angular/angular-cli#5163]
### OS?
> Any

### Versions.
> @angular/cli: 1.0.0-rc.0
node: 6.9.5

### Repro steps.
> The main site [Angular CLI](https://cli.angular.io/) says that `ng generate` can "Generate components, **routes**, services ..." however  `ng generate` doesn't have `route` blueprint

### Mention any other details that might be useful.
> So, please change the site or even better, add support for generating routes in the future release.
Thanks!

**Comment by killrazor** [comment]
Routes haven't been in CLI for a while. They probably just haven't updated that specific wording on the website.

**Comment by delasteve** [comment]
The style guide suggests creating a routing module to handle routes. This can be accomplished with the following command:

```bash
ng g m foo --routing
```

**Comment by filipesilva** [comment]
Closing as answered.

**Comment by coolsambit** [comment]
What is m?

**Comment by FlightToFreedom** [comment]
I think you forgot to specify the type you want to generate, it should be: `ng g component {yourComponentName}`
https://github.com/angular/angular-cli/wiki/generate-component

**Comment by delasteve** [comment]
@coolsambit `m` is an alias for `module`.

**Comment by eisenek** [comment]
also providing generated route module in app`s main module (or whatever else if required) in this one step seems reasonable `ng g m route --routing --module=app.module`
