### ISSUE TITLE
Production build fails if styles directory is a hard link

### ISSUE THREAD

**Issue by gavinm-ulogic** [angular/angular-cli#5167]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10

### Versions.
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.32-3]
node: 7.3.0
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.7

### Repro steps.
1.) Move directory containing styles to different location.
2.) Create hard link (junction) with mklink /J {source} {target} - map link back to original position

### The log given by the failure.
ERROR in   TypeError: Cannot read property 'match' of undefined

  - suppress-entry-chunks-webpack-plugin.js:40 filterFn
    [External]/[@angular]/cli/plugins/suppress-entry-chunks-webpack-plugin.js:40:91

  - Array.filter

  - suppress-entry-chunks-webpack-plugin.js:42 Compilation.compilation.plugin
    [External]/[@angular]/cli/plugins/suppress-entry-chunks-webpack-plugin.js:42:59

  - Tapable.js:208 Compilation.applyPluginsAsyncWaterfall
    [External]/[tapable]/lib/Tapable.js:208:13

  - util.js:16 Compilation.tryCatcher
    [External]/[bluebird]/js/release/util.js:16:23

  - index.js:642
    [External]/[html-webpack-plugin]/index.js:642:12

  - index.js:152
    [External]/[html-webpack-plugin]/index.js:152:16

  - util.js:16 tryCatcher
    [External]/[bluebird]/js/release/util.js:16:23

  - promise.js:510 Promise._settlePromiseFromHandler
    [External]/[bluebird]/js/release/promise.js:510:31

  - promise.js:567 Promise._settlePromise
    [External]/[bluebird]/js/release/promise.js:567:18

  - promise.js:612 Promise._settlePromise0
    [External]/[bluebird]/js/release/promise.js:612:10

  - promise.js:691 Promise._settlePromises
    [External]/[bluebird]/js/release/promise.js:691:18

  - async.js:133 Async._drainQueue
    [External]/[bluebird]/js/release/async.js:133:16

  - async.js:143 Async._drainQueues
    [External]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues
    [External]/[bluebird]/js/release/async.js:17:14

### Mention any other details that might be useful.
As per the trace the error occurs at:
suppress-entry-chunks-webpack-plugin.js:40:91
updating that line to:
const filterFn = (tag) => !(tag.tagName === 'script' && tag.attributes.src && tag.attributes.src.match(/\.css$/));
stops the error and doesn't seem to effect my build - but guess that lack of tag.attributes.src would cause errors in some builds

For background:
The reason I want to do this is to allow for multiple styles and assets directories that I can switch in and out for different look & feel builds - if there's a better way to achieve this I'd be happy to change.

Thanks  Gavin

**Comment by filipesilva** [comment]
Actually, your fix should be fine. I don't see it breaking any builds, and it was mostly my fault for assuming `src` was a property there. Can you make a PR?

**Comment by gavinm-ulogic** [comment]
Hi Filipe,

As you say, my fix can't make anything worse - stops the script crashing
when tag.attributes.src is null / undefined.

My question is why tag.attributes.src is null / undefined when the source
directory is a link? I think that the filter function will not be running
properly in this case - css files won't be matched.

Gavin

**Comment by filipesilva** [comment]
@gavinm-ulogic does this still happen?

**Comment by gavinm-ulogic** [comment]
Yes, I never got around to raising a pull request. There is still no
checking for null.

I'll have a go at raising the pull request.

Gavin

**Comment by gavinm-ulogic** [comment]
Hi,

I tried to follow the instructions for contributing.

I got an error when trying to push the branch I created:

PS C:\Data\Dev\angular-cli> git push origin issue-5167-fix
remote: Permission to angular/angular-cli.git denied to gavinm-ulogic.
fatal: unable to access 'https://github.com/angular/angular-cli.git/': The
requested URL returned error: 403

The fix is a change line 41 of suppress-entry-chunks-webpack-plugin.ts

const filterFn = (tag) => !(tag.tagName === 'script' && tag.attributes.src
&& tag.attributes.src.match(/\.css$/));

Regards  Gavin

**Comment by filipesilva** [comment]
You don't have push permissions for this repository. Instead, you should fork it, push your changes onto your fork and submit a pull request.

**Comment by steve-todorov** [comment]
I seem to be encountering the same issue. The `./src/styles.scss` cannot be renamed nor moved in another directory as it will give a similar error. Did anybody had the chance to make a PR for this?

**Comment by filipesilva** [comment]
There doesn't seem to be a PR yet, no. @gavinm-ulogic had a suggested fix in his post. Would you like to make a PR for it?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
