### ISSUE TITLE
there is a problem to get a real constructor name after ng build --prod

### ISSUE THREAD

**Issue by valera911** [angular/angular-cli#5168]
### OS?
> Mac OSX (Yosemite? El Capitan?)

### Versions.
@angular/cli: 1.0.0-rc.0
node: 7.5.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

### Repro steps.
Hello.
there is a problem to get a real constructor name after ng build --prod
I have following code :
export class MyClass {
    getClassName(){
        return this.constructor.name
    }
}

After compilation we have the code like this :
    DdHI: function(t, e, n) {
        "use strict";
        var i = function() {
            function t() {}
            return t.prototype.getClassName = function() {
                return this.constructor.name
            }
            ,
            t
        }();
        e.MyClass = i
    },

Unfortunately it's impossible to get the name of constructor in this case.
Is there any different way to get a constructor name ( or class name ) in runtime ?

**Comment by sumitarora** [comment]
@valera911 You can get class name where ever you are using instance of the class as below.
```
class Hello {
}

let x: Hello = new Hello();
console.log(x.constructor.name);
```

**Comment by valera911** [comment]
thanks a lot!

**Comment by sebastiangseijo** [comment]
I have faced this problem with --prod and --aot and the solution i have found was this:
i modified production.js so constructor.name can give you the correct name and not a simple letter.

node_modules//models/webpack-configs/production.js

...
new webpack.optimize.UglifyJsPlugin({
...
mangle: { screw_ie8: true, keep_fnames: true }, /* added keep_fnames: true so SomeClass.constructor.name works */
...
})

**Comment by CSchulz** [comment]
@sumitarora I suggest that this issue is not fixed until it is possible to configure the UglifyJsPlugin from an external file.
Can you mark it as feature request?

**Comment by mister-walter** [comment]
For anyone who needs to disable mangling temporarily (like I did), you can do so without `ng eject` by modifying the file that sets the Webpack settings: `node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js`.

Warning: this is very much unsupported by Angular, and will be overwritten by an update to `@angular-devkit/build-angular`!

In that file, I changed `uglifyOptions` in `new UglifyJSPlugin({ ... }),` to `uglifyOptions: Object.assign(uglifyOptions, {"mangle": false})`

I needed to do this because I was having issues with sourcemaps not correctly mapping a few dependencies I was using, making debugging difficult.

**Comment by Elvynia** [comment]
@sumitarora I don't understand, this issue should be opened...

I am using `obj.constructor.name`, but I can't modify angular-devkit's configuration files on my production environment. Has anyone found a workaround on production builds ?

**Comment by capslocky** [comment]
@Elvynia I was able to use `instanceof` instead in my case.

**Comment by maurei** [comment]
Why is this issue closed?  Would like to see this fixed. I need to get to `constructor.name` in runtime.

**Comment by alexandranb** [comment]
In add a reference to your config section, to a new uglify.config.js file, and set mangle to false. 
This way, you will be able to get full name of the constructor. I had the same problem and this fixed my problem, based on what was said above.

**Comment by MicMicMon** [comment]
What is the preferred way to go with this?
I'm a bit relunctant to modify something in node_modules, it is not practical with usual deployment strategies.

**Comment by no-more** [comment]
I ended up by setting "manually" a string property in each class.
You can also automate the process with a script which would define this property for you. I used ts-simple-ast for this.
Eventually you can define a pre:build script to automate the process.

**Comment by maurei** [comment]
Wondering why this issue is still closed. Anyone of the team care to elaborate why this won't be addressed?

**Comment by jscssphtml** [comment]
I'm using a autogenerated id right now, but it still would be helpful.

**Comment by jorisdeguet** [comment]
I have encountered the same problem with:
"@angular/cli": "^7.3.0",
"@angular/compiler-cli": "^7.2.3",
node v10.15.0
npm 6.7.0

I realized I did not really needed the constructor.name but it was hell to find the bug.

The value returned was an empty string.

Joris

**Comment by wouterv** [comment]
> @Elvynia I was able to use `instanceof` instead in my case.

This worked for us, so it is a recommendation not to use constructor.name.

**Comment by keenondrums** [comment]
Guys, you can [this custom builder](https://github.com/keenondrums/angular-builder-custom-terser-options) if you need constructor.name.
