### ISSUE TITLE
importing main.js --> importing main

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#517]
1b. We are importing main.js … shouldn't we be using systemjs config so we can import main?

cc @Brocco @hansl

**Comment by deebloo** [comment]
```defaultExtension: 'js'``` ?

**Comment by johnpapa** [comment]
yep. it's not configured for the main right now in the CLI, but it is configured for all other folders/files

@hansl may know why

**Comment by filipesilva** [comment]
I've been working on SystemJS and can add that to this PR https://github.com/angular/angular-cli/pull/481

**Comment by hansl** [comment]
https://github.com/angular/angular-cli/pull/550 will fix that. 481 will probably be closed.
