### ISSUE TITLE
Feature Request / Issue : Minification not an option in build process?

### ISSUE THREAD

**Issue by ganeshkbhat** [angular/angular-cli#5174]
> Please provide us with the following information:
> Why is minification not an option in the build process?

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
@angular/cli: 1.0.0-beta.32.3
node: 6.9.4
os: Win10 win32 x64

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-beta.32.3
node: 6.9.4
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
NA

### The log given by the failure.
> Normally this include a stack trace and some more information.
NA

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ganeshkbhat** [comment]
FYI:
Noticed this in wiki
Bundling: All builds make use of bundling, and using the --prod flag in ng build --prod or ng serve --prod will also make use of uglifying and tree-shaking functionality.

Seems it does seem to work for me in prod.

**Comment by Vnuuk** [comment]
Doesn't work for me also.. Using 

`npm run ng build --prod --env=prod`

doesn't minify my bundles..
