### ISSUE TITLE
Should default tsconfig combines es5 target with es2015 module system?

### ISSUE THREAD

**Issue by victornoel** [angular/angular-cli#5177]
According to https://www.typescriptlang.org/docs/handbook/compiler-options.html:
> "ES6" and "ES2015" values may not be used when targeting "ES5" or lower.

And in src/tsconfig.app.json we have:
```json
    "target": "es5",
    "module": "es2015",
```

Is it an error or am I missing something?

**Comment by clydin** [comment]
That documentation is outdated.  I noticed that as well.

**Comment by victornoel** [comment]
@clydin so there shoudln't be any problem with that, right? I can close this issue?

**Comment by clydin** [comment]
There's no problem with the combination with TS 2+.
