### ISSUE TITLE
root tsconfig.json needs "target": "ES5" for IDE Integration

### ISSUE THREAD

**Issue by martinmcwhorter** [angular/angular-cli#5183]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

All

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0-rc.0
node: 6.9.2
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.9
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Open VSCode and use the `get` and/or `set` property accessors: 

      set currencyCode(code: string) {
      // . . . 
       get currencyCode() {

VSCode will display red squiggles under these lines with the following message 

    Accessors are only available when targeting ECMAScript 5 and higher.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

Add the following to the root tsconfig.json fixes this issue:

    "target": "ES5"

This should be updated in both the blueprints and the Update Guide(s).

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
Fix is already in mastee

**Comment by deebloo** [comment]
Master*

**Comment by filipesilva** [comment]
Closing as answered.
