### ISSUE TITLE
neutrino?

### ISSUE THREAD

**Issue by tycho01** [angular/angular-cli#5184]
Apparently [Neutrino](https://github.com/mozilla-neutrino/neutrino-dev) is a Mozilla initiative allowing people to publish/use webpack configs as presets. Obviously, ng-cli already addresses webpack concerns by itself. I'd wonder though, might it make sense to publish configs used by angular-cli as some officially endorsed angular preset?

**Comment by hansl** [comment]
We change the config regularly (and dynamically as well), while our API surface (command line flags and arguments) is relatively stable. Releasing the webpack config would be a statement that the CLI's config is stable and limit our ability to improve on it.

The good news is that there's nothing interestingly complex about our webpack config and we let you generate one and output it, through the `eject` command. But we do not guarantee that using eject on the same app twice (between versions) would lead to the same webpack config; just that building your app would result in a working bundle.

**Comment by tycho01** [comment]
Alright. Thanks for commenting on this. :)
