### ISSUE TITLE
ng serve does not use source environment

### ISSUE THREAD

**Issue by reaction1989** [angular/angular-cli#5188]
I am having following environment configuration:

![image](https://cloud.githubusercontent.com/assets/873751/23524953/125ab32e-ff8d-11e6-9e5a-537bf8d42b09.png)

When i run ng serve the dev environment will be used. I rather expected that the source one should be used? Am i on the wrong path here?

How can i use the environmentSource?  When source was a own config entry it was possible to use it with ng serve --e=source --> This is not possible atm? Perhaps i am doing something wrong :)

**Comment by clydin** [comment]
In previous versions the source environment was merely a placeholder to keep IDEs from showing errors.  recent versions eleminated the separate file and use the Dev environment has the default.

**Comment by sumitarora** [comment]
@reaction1989 The build system defaults to the dev environment which uses `environment.ts` you can override that with different environments as you prefer. In your case `environment.dev.ts` will be used as default not `environment.ts`.
