### ISSUE TITLE
RC.0 migration guide: IDEs will throw error without a target

### ISSUE THREAD

**Issue by jakeNiemiec** [angular/angular-cli#5189]
The Typescript service will throw: Accessors are only available when targeting ECMAScript 5

![image](https://cloud.githubusercontent.com/assets/16782063/23525755/16e5c506-ff55-11e6-95dc-ad4b6e242b60.png)

The root level `tsconfig.json` needs any "target" over ES5 and Typescript will stop throwing errors. e.g.:
`"target": "es5",`

Wiki diff:
https://github.com/jakeNiemiec/angular-cli/wiki/stories-rc.0-update/_compare/efe56cf9b6e19be290a2404527ee8f65b577106a...ee9348c302d1ea6e64f43ea7c157342cfb4d8d18

**Comment by deebloo** [comment]
Fixed in master

**Comment by sumitarora** [comment]
Fixed in RC.1 https://github.com/angular/angular-cli/pull/5060
