### ISSUE TITLE
Routes dont open with the latest version

### ISSUE THREAD

**Issue by rahulbats** [angular/angular-cli#519]
the latest version generates routes without any children.
But the routeconfig inside the app.ts still has `path:/<route_name>/...`
Instead it should be `path:/<route_name>`

**Comment by Brocco** [comment]
Route generations are being worked on currently, this should be working as you expect once the generation of routes is completed. This should be included in the next release.

**Comment by filipesilva** [comment]
This is already fixed I believe. Please tell me if that isn't the case so I can reopen the issue.
