### ISSUE TITLE
How to display app version?

### ISSUE THREAD

**Issue by AlecTaylor** [angular/angular-cli#5190]
My package.json has a version number, let's say I want to show that in the footer of my application.

How would I do so?

All I could find is this, but that's not relevant to current angular-cli right? http://stackoverflow.com/questions/34907682/how-to-display-app-version-in-angular2

**Comment by mattdistefano** [comment]
I'm not on the very latest version but as of beta 30 importing package.json did work. I'd give it a try.

**Comment by AlecTaylor** [comment]
I couldn't import it, and `require`ing it didn't work with `ng build -prod`.

**Comment by clydin** [comment]
Something to consider is that importing or requiring your `package.json` has the potential to expose development information into your production build.
Two other possible options include:
* Hard-code the value in the source -- the environment file would probably be the best place
* Create a _pre-build_ script that injects the version into the source before each build

**Comment by Brocco** [comment]
I concur with @clydin that the value should be set in your environment files and should be put there via a process outside of the CLI itself. I'm closing this issue as the suggested approach is manual and outside of the CLI.

**Comment by dherges** [comment]
If you're doing semver, `git describe` is a cool thing!

```js
// @ts-check
const chalk = require('chalk');
const git = require('git-describe');
const path = require('path');
const fs = require('fs-extra');

const info = git.gitDescribeSync({ longSemver: true });
const file = path.resolve(__dirname, '..', 'src', 'environments', 'version.ts');

fs.writeFileSync(
    file,
    `export const VERSION = ${JSON.stringify(info)};` ,
    { encoding: 'utf-8' });

console.log(chalk.green(`Wrote version info ${info.raw} to ${path.relative(path.resolve(__dirname, '..'), file)}`));
```

```json
  "scripts: {
    "postinstall": "node scripts/version.js"
  }
```

**Comment by MA-Maddin** [comment]
> I couldn't import it, and requireing it didn't work with ng build -prod.

    const { version: appVersion } = require('../../package.json')

this soultion ( from http://stackoverflow.com/questions/34907682/how-to-display-app-version-in-angular2 )
works well for me in Angular 5.
Just make sure to add `"node"` type inside `"types"` property in `tsconfig.app.ts` as mentioned in comments there.

**Comment by thijsvanbuuren** [comment]
I know this is an older issue, but when trying to solve the same problem i combined the above solution with a line in your packages.json, this makes sure it keeps your version.ts up to date, when using npm version:

`"version": "node set-version.js && git add -A .",`

Whenever you run `npm version x.x.x` it will update your version.ts and include it in the commit and tag.

**Comment by menehune23** [comment]
Thanks @thijsvanbuuren for your suggestion. I was able to simplify it a bit with a script to run from the `package.json` scripts:

__version.sh__
```bash
version_file=src/app/app.version.ts
> $version_file
echo "// This file was generated on $(date)
export const appVersion = '$1';" >> $version_file
git add $version_file
```

__package.json__
```
...
"version": "0.0.0",
"scripts": {
  "version": "./version.sh $npm_package_version",
  ...
```

Then from a component:
```
import { appVersion } from 'path/to/app.version';
```

Note that calling `git add` from the version script will cause the file to be staged while npm is updating the version (but just after the version is updated, so you have access to the newest version number). See [the npm docs](https://docs.npmjs.com/cli/version)

**Comment by JaxonWright** [comment]
@menehune23 any way you could convert the shell script to a batch file for Windows usage?

**Comment by menehune23** [comment]
@JaxonWright I don't have a Windows machine and haven't run batch scripts in a long time, though the logic is pretty simple: we're just writing some literal text to a file called `src/app/app.version.ts`.  The only variable parts are the date (optional, honestly, but I like to have it), and the first argument.

In Windows, I believe `echo` works, and the argument can be referenced by `%1`. Not tested, but should be a good start.

If anyone else with Windows experience wants to chime in, feel free 😉.

**Comment by btsiders** [comment]
The shell script works fine as-is for me on Windows 10.
