### ISSUE TITLE
ng build --aot gives error but ng build works fine

### ISSUE THREAD

**Issue by deepatr** [angular/angular-cli#5198]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
MacOS Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-beta.32.3
node: 7.4.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
This is a angular-cli project

### The log given by the failure.
> Normally this include a stack trace and some more information.
ERROR in Unexpected value 'QRCodeComponent in /../angular-cli/../node_modules/ng2-qrcode/dist/ng2-qrcode.d.ts' declared by the module 'AppModule in /angular-cli/../src/app/app.module.ts'

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'angular-cli/../src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

### Mention any other details that might be useful.
I have been able to narrow down the issue to this component which was installed with 
npm ng2-qrcode.
By commenting the code related to this component, ng build --aot works fine.

app.module.ts:
import {QRCodeComponent} from 'ng2-qrcode';
import { QrcodesComponent } from './core/qrcodes/qrcodes.component';
..
@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    routes,
    MaterializeModule
  ],
  declarations: [
    AppComponent,
    ...
    QRCodeComponent,
    QrcodesComponent
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by borntodesign** [comment]
I have the same issue:

$ ng build -prod --aot
Hash: d230164e916b758d0692                                                              
Time: 18475ms
chunk    {0} polyfills.c55f89f35c48bf2c6e88.bundle.js (polyfills) 153 kB {5} [initial] [rendered]
chunk    {1} scripts.4df4da6c643df8224363.bundle.js (scripts) 750 kB {5} [initial] [rendered]
chunk    {2} styles.bd44f3c52773890a1208.bundle.css (styles) 281 bytes {5} [initial] [rendered]
chunk    {3} main.daff98269318dace91c3.bundle.js (main) 668 bytes {4} [initial] [rendered]
chunk    {4} vendor.094b768043954986be41.bundle.js (vendor) 834 kB [initial] [rendered]
chunk    {5} inline.4a76813170987b826954.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in Maximum call stack size exceeded

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/baypublishing/projects/vvink/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

@angular/cli: 1.0.0-rc.1
node: 6.9.2
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

I even created a new project and copied over but no joy?

**Comment by clydin** [comment]
@deepatr the published version of the `ng2-qrcomponent` package is outdated.  Please raise an issue with the package maintainer.

@borntodesign Please open a separate issue with additional details regarding your project.  Also note that AOT is enabled by default with a production build.

**Comment by filipesilva** [comment]
Closing as answered. Thanks @clydin !
