### ISSUE TITLE
http://localhost:4200/contact returns 404

### ISSUE THREAD

**Issue by mistercz** [angular/angular-cli#52]
I have simple project with router. 
1) Navigating to contacts changes url to localhost:4200/contact and all works as expected. 
2) Changes in source code triggers page reload
3) Page reload results to 404 Cannot GET /contact.  <= ERROR

**Comment by mistercz** [comment]
Still no feedback ?

**Comment by IgorMinar** [comment]
the issue is that the server is not setup for [`PathLocationStrategy`](https://angular.io/docs/js/latest/api/router/PathLocationStrategy-class.html) yet. In general the component router support is currently every poor.

I'll file a separate issue for this feature.

**Comment by IgorMinar** [comment]
#66
