### ISSUE TITLE
ng init is not a command 

### ISSUE THREAD

**Issue by maheshwarLigade** [angular/angular-cli#5201]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX (Yosemite)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-rc.1
node: 7.7.1
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
I want to create sample using angular cli

### The log given by the failure.
> Normally this include a stack trace and some more information.

The specified command init is invalid. For available options, see `ng help`.
### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by grizzm0** [comment]
The commands init and update has been removed.

Read the changelog for more info: https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#100-beta32-2017-02-17

**Comment by mtr986** [comment]
link not working

**Comment by grizzm0** [comment]
The changelog has been removed. See https://github.com/angular/angular-cli/releases instead.
This is a really old issue tho. Doubt this is the issue you're having yourself.

**Comment by muneebshafiq** [comment]
You can add missing modules using `npm install`
