### ISSUE TITLE
Ng serve not picking up environmentSource in Git branch

### ISSUE THREAD

**Issue by Houghruo** [angular/angular-cli#5202]
OS: Windows 10
CLI Version: 1.0.0-rc.1

The CLI doesn't seem to be picking up the env set in environmentSource when running 'ng serve' from a Git branch (and reverts to running the in environment set as "dev", as it was in the beta). However, when running from Git master, it works fine. The .angular-cli.json and package.json files are exactly the same. Creating a fresh local branch from master also causes the issue (with no difference other than it being in a new branch), which leads me to think it is an issue with Git branching. Any insight?

Thanks in advance

**Comment by sumitarora** [comment]
@Houghruo When running `ng serve` The build system defaults to the dev environment which uses `environment.ts`. You can override it by specifying your own environment files.

**Comment by Houghruo** [comment]
@sumitarora Yeah, that's fine when I'm in master, it defaults to environmentSource, as you can see below:
`"environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.dev.ts",
        "test": "environments/environment.test.ts"
      }`
However, as soon as I switch to a new branch (fresh from master, absolutely nothing different other than the Git aspect of it), it stops doing that and instead defaults to the "dev" environment (using environment.dev.ts). It's the change in behaviour that's weird. To get around that, I've basically had to do as was done in the beta, as below:
`"environmentSource": "environments/environment.ts",
      "environments": {
        "local": "environments/environment.ts",
        "dev": "environments/environment.dev.ts",
        "test": "environments/environment.test.ts"
      }`

Is there anything that comes to mind about this?

Thanks in advance!
