### ISSUE TITLE
Allow comments in tsconfig referenced in AotPlugin conf

### ISSUE THREAD

**Issue by csentis** [angular/angular-cli#5216]
### OS?
> Windows 10

### Versions.
> node @ v7.5.0

### Repro steps.
> This happens in an app that wasn't created using the CLI.

- Provide AotPlugin with tsConfigPath
- tsconfig.json referenced has comments starting with '//' in it.
- AotPlugin throws error due to unexpected token '/'.

MS allows for comments in tsconfig, Would be great if ngtools supported this, too.

**Comment by hansl** [comment]
@sumitarora This is not for 1.0. Sorry for the mis-assignment. For now let's push this one further down the road.
