### ISSUE TITLE
Error loading global js files

### ISSUE THREAD

**Issue by valeriemaite** [angular/angular-cli#5219]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-rc.0
node: 6.10.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4
@angular/platform-browser-dyna
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.9

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
--created app using angular-cli-->added js files to be loaded in .angular-cli.json in script: ["filePaths.js"]:
    "scripts": ["../src/assets/spread/gc.spread.sheets.all.10.0.0.min.js",
      "../src/assets/spread/angular.gc.spread.sheets.10.0.0.min.js", "../src/assets/spread/gc.spread.excelio.10.0.0.min.js",
      "../src/assets/spread/license.js"],

ng serve-->app loads fine, open dev tools and see:
![image](https://cloud.githubusercontent.com/assets/4131500/23575640/c24c94c8-0055-11e7-991b-1e1073f12950.png)

### The log given by the failure.
> Normally this include a stack trace and some more information.

Uncaught TypeError: Cannot read property 'module' of undefined
    at eval (eval at webpackJsonp.133.module.exports (scripts.bundle.js:14), <anonymous>:17:56)
    at eval (eval at webpackJsonp.133.module.exports (scripts.bundle.js:14), <anonymous>:1107:2)
    at eval (<anonymous>)
    at webpackJsonp.133.module.exports (scripts.bundle.js:14)
    at Object.328 (scripts.bundle.js:23)
    at __webpack_require__ (inline.bundle.js:53)
    at Object.562 (scripts.bundle.js:80)
    at __webpack_require__ (inline.bundle.js:53)
    at webpackJsonpCallback (inline.bundle.js:24)
    at scripts.bundle.js:1

### Mention any other details that might be useful.
Placed a breakpoint and see it failing here:

![image](https://cloud.githubusercontent.com/assets/4131500/23575651/0da8af92-0056-11e7-944a-a17833dfd11f.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
your paths are incorrect. By default the cli looks in the src folder.

```JSON
{
  "scripts": [
  "assets/spread/gc.spread.sheets.all.10.0.0.min.js",
  "assets/spread/angular.gc.spread.sheets.10.0.0.min.js",     "assets/spread/gc.spread.excelio.10.0.0.min.js",
  "assets/spread/license.js"
],
}
```

**Comment by valeriemaite** [comment]
Thanks deebloo, however I changed it and still get the error:

![image](https://cloud.githubusercontent.com/assets/4131500/23732835/1820daba-043b-11e7-92a6-99f2ff19e351.png)

**Comment by filipesilva** [comment]
Hm I think one of those libraries must be using `module.id` in their components. That isn't well supported outside of SystemJS environments. A hack you can use to work around it is add this to your `index.html`:
```
   <!-- Workaround for module.id -->
    <script>window.module = 'aot';</script>
```

But even then they might not work properly.

**Comment by valeriemaite** [comment]
Thanks @filipesilva, that didn't work :(.  However i do notice that when I remove the scripts from the angular-cli and actually add directly to index.html the error is "reduced".  This time the error is just because app.js loads after the custom scripts, is there a way to change the ordering of the scripts in index.html?

![image](https://cloud.githubusercontent.com/assets/4131500/23964884/12bddc78-0984-11e7-8fb1-7a084c51ec38.png)

**Comment by filipesilva** [comment]
@valeriemaite you need to open a bug with that library and let them know they shouldn't be publishing code that uses `module.id`. That's the real fix here.
