### ISSUE TITLE
What is the proper --live-reload-port replacement

### ISSUE THREAD

**Issue by mmucklo** [angular/angular-cli#5222]
The README.md mentions using --live-reload-port

However, it seems that --live-reload-port no longer works, so I'm wondering the proper way to set it up?

I've tried:

```
--live-reload true --live-reload-client http://localhost:49153 
```

but I'm getting a "Failed to load resource: net::ERR_EMPTY_RESPONSE" when I load the page.

(caveat I'm running inside a docker container and explosing port 49153 with port 3000, which works fine).

**Comment by clydin** [comment]
The live reload port is identical to the development server port (`--port`).  There is no longer a separate live reload server.

**Comment by filipesilva** [comment]
Closed as answered, thanks @clydin !
