### ISSUE TITLE
Error in IE 11

### ISSUE THREAD

**Issue by ded100let** [angular/angular-cli#5226]
Hi! In IE 11 error.
SCRIPT5007: Не удалось получить свойство "apply" ссылки, значение которой не определено или является NULL

code:return(e=Object).assign.apply(e,[{}].concat(t))
Asking for your help. The problem is only in IE 11. Thank you!
Where can I see the prototype of the method apply?

error: SCRIPT5007: unable to get property 'apply' links whose value is not undefined or NULL reference

ng -version

@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/flex-layout: 2.0.0-beta.5
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

In dev. console browser IE 11.
In Edge no error.
screenshot https://yadi.sk/i/Kn988PEx3F2XUY

function combine(options) {
return (_a = ((Object))).assign.apply(_a, [{}].concat(options));
var _a;
}

function in node_modules@angular\common\bundles\common.umd.js

**Comment by mattdistefano** [comment]
Make sure you have all the polyfills for IE11 included in your polyfills.ts.

**Comment by saimonsez** [comment]
Including the mentioned IE11 polyfills fixed this error for me.

**Comment by filipesilva** [comment]
Closing as answered.

**Comment by luongto** [comment]
unrem polyfills in the polyfills.ts would help

**Comment by pinku-4132** [comment]
**is anyone found any details for this??**

`/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/shim';//added mahendra
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/promise';//added mahendra
import 'es6-shim/es6-shim.js';//added mahendra
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/typed';//mahendra
import 'core-js/es6/weak-map';//mahendra

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.
import 'es6-shim/es6-shim.js';

/** IE10 and IE11 requires the following to support `@angular/animation`. */
import 'web-animations-js';  // Run `npm install --save web-animations-js`.


/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'core-js/es7/observable';


/** ALL Firefox browsers require the following to support `@angular/animation`. **/
import 'web-animations-js';  // Run `npm install --save web-animations-js`.



/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */

/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
import 'intl';  // Run `npm install --save intl`.


//mahendra added
import 'intl/locale-data/jsonp/en';
// import 'typedarray/index';

import '../node_modules/blob';
// import '';
import '../node_modules/form-data';

`

**Comment by kschwarz1980** [comment]
I found those information that let my app also work in IE11: https://github.com/aspnet/JavaScriptServices/wiki/Supporting-Internet-Explorer-11-(or-older)
