### ISSUE TITLE
Unable to run basic Angular 2 App

### ISSUE THREAD

**Issue by abhiramravipati** [angular/angular-cli#5227]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
node:6.10.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
There are no code changes I have just installed CLI and created a project using ng new my-app and navigated to project folder and executed ng serve. The web page is stuck at loading forever 
### The log given by the failure.
> Normally this include a stack trace and some more information.
Uncaught TypeError: Cannot read property 'apply' of undefined

### Mention any other details that might be useful.
I am trying to setup Angular App using angular CLI by following the steps mentioned in angular website.

But when I use ng serve command and try to open the url http://localhost:4200/

It is stuck in loading screen forever.

Steps followed for Setup:

1) Installed Node Js

2) npm install -g typescript

3) npm install -g @angular/cli

4) ng new PROJECT_NAME

5) cd PROJECT_NAME

6) ng serve

in chrome developer tools Uncaught TypeError: Cannot read property 'apply' of undefined is being shown.

Pls Help.Thanks in Advance

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattdistefano** [comment]
Try uncommenting some of the polyfills in polyfills.ts. Chrome shouldn't require much but you may be running an older version.

**Comment by abhiramravipati** [comment]
Thanks, updated the chrome browser it is working now.

**Comment by filipesilva** [comment]
Closing as answered, thanks @mattdistefano !
