### ISSUE TITLE
`tether_drop_1.default is not a constructor` only on tests

### ISSUE THREAD

**Issue by awerlang** [angular/angular-cli#5228]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows  10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
@angular/cli: 1.0.0-rc.1
node: 6.9.1
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Repo: https://github.com/awerlang/tether-ng-cli
Run `npm start`. It runs okay.
Run `npm test`. A test fails with `tether_drop_1.default is not a constructor`.

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
  Uncaught Error: Error in ./AppComponent class AppComponent - inline template:4:0 caused by: tether_drop_1.default is not a constructor
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I don't think this is a CLI issue. I'd say you're importing this library incorrectly and thus it's not included in the unit test. Try adding it as a global script instead.

**Comment by awerlang** [comment]
@filipesilva the workflow with `ng start` works correctly, and I don't need to include as a script. That's what makes me wonder how they have different results. Can you help explain why `ng start` works without addind as script?

**Comment by filipesilva** [comment]
I think it works with the import on `ng serve` because the app itself uses es2015 modules, while unit tests use commonjs modules. This is necessary because some of the tooling around unit tests wouldn't work otherwise.

Maybe you can also get it to work by using a different style of import, but it is heavily dependent on how the library is distributed. You can try these:
```
import * as foo from 'foo';
import {foo} from 'foo';
```

The safest way I've found for browser libs that are mostly meant to be included as script tags is to use the scripts array though.

**Comment by awerlang** [comment]
Thanks @filipesilva! Knowing this difference is helpful, I guess I should be able to work around it now. Perhaps I'll re-package the library.
