### ISSUE TITLE
ng test --build false should skip the build

### ISSUE THREAD

**Issue by andregs** [angular/angular-cli#5234]
I'm trying to test without building, but I get:
```
PS C:\Users\andre\Workspace> ng new myproj
PS C:\Users\andre\Workspace> cd myproj
PS C:\Users\andre\Workspace\myproj> ng test --build false
 45% building modules 329/562 modules 233 active ...@angular\core\src\profile\wtf_impl.js
```

The same happens with `--build=false`

Isn't `--build false` supposed to skip the build?

### OS?
> Windows 10

### Versions.
@angular/cli: 1.0.0-rc.1
node: 7.4.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/compiler-cli: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1

**Comment by filipesilva** [comment]
This option is not present anymore in the latest release. It was probably cleaned up meanwhile:
```
kamik@T460p MINGW64 /D/sandbox/master-project (master)
$ ng test --build false
The option '--build' is not registered with the test command. Run `ng test --help` for a list of supported options.
```

**Comment by odahcam** [comment]
Is it possible to skip the build in the tests if already have built code?
