### ISSUE TITLE
Unable to proceed with Angular CLI installation

### ISSUE THREAD

**Issue by iprasadraju** [angular/angular-cli#5236]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10. 

### Versions.
> ng v3.10.10 & node v6.10.0

### Repro steps.
> I just downloaded the nodejs latest version from https://nodejs.org/ site. I want to work on Angular 2, so I am trying to install angular CLI, but unable to proceed with installation. I am trying to install this in my personal laptop. I found few articles mentioning that I need to set the proxy, but in my case I don't need to set the proxy settings to access the internet, am I still need to set the proxy? if yes please let me know the format. 
I am completely new to this forum and not sure if this question was already answered, please execute. 

### The log given by the failure.
> Displayed the below log information on console. Also attached the generated log file for more details

npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect
npm ERR! network connect ETIMEDOUT 151.101.60.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

[npm-debug.txt](https://github.com/angular/angular-cli/files/819607/npm-debug.txt)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Nikki1993** [comment]
First of all, did you try following steps mentioned in this github page? Cause if you did, you shouldn't be seeing this 
`npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. `
As you are trying to install deprecated version of angular cli. https://github.com/angular/angular-cli#prerequisites

**Comment by iprasadraju** [comment]
Hi @Nikki1993, I had the same error except deprecated message even with "npm install -g @angular/cli" 

With the help of setup guide in below link i got it install using GIT cloning
https://angular.io/docs/ts/latest/guide/setup.html

**Comment by juandata** [comment]
Hello, download the current version (not the recommended for most users) which today is 8.7.0 and also use npm install -g @angular/cli as Nikki1993 mentioned.
