### ISSUE TITLE
Missing addition of bootstrap.min.js to the scripts array in with bootstrap wiki-story

### ISSUE THREAD

**Issue by madoar** [angular/angular-cli#5239]
I've just discovered, that some parts of bootstrap aren't usable after following the guide given in the corresponding [wiki article](https://github.com/angular/angular-cli/wiki/stories-include-bootstrap).

More clearly, an alert I've added, wasn't closed after pressing the corresponding "x" link in the alert div.
My guess is, that the addition of `bootstrap.min.js` to the scripts array inside `.angular-cli.json` is missing in the wiki article.

**Comment by mattdistefano** [comment]
I wouldn't say it's missing, exactly; rather, the focus of the article is on including the bootstrap CSS only. Using the JS-based bootstrap functionality is probably best done via something like [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap).

**Comment by madoar** [comment]
You may be right, the use of ng2-bootstrap may be better in this case, but I would suggest to add a few sentences saying, that the tutorial in the article only adds the CSS classes and that JS-based bootstrap functionally can't be used with only the given steps.

**Comment by GoNode5** [comment]
Just create a pull request.. 
https://github.com/angular/angular-cli/pull/5248

**Comment by Brocco** [comment]
This story is about adding CSS/SCSS, adding logic behind bootstrap is a much larger discussion that involves jQuery or one of the Angular related bootstrap libraries.
