### ISSUE TITLE
Comments in SASS files are treated as SASS code

### ISSUE THREAD

**Issue by PhilippSoehnlein** [angular/angular-cli#5243]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OS 10.11 (El Capitan)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

<pre>@angular/cli: 1.0.0-rc.1 (e)
node: 6.9.3
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9</pre>

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
1. `ng new`
2. Rename `app.component.css` to `app.component.scss` and change the `styleUrls` in `app.component.ts`, too.
3. Add a comment to the SCSS file that contains an `@import`. Example: 
```scss
/**
 * @import 'path/to/this/file';
 */
:host {
    $color: #f0f;

    display: block;
    background-color: $color;
}
```
4. `ng serve`
5. Browser tries to load `path/to/this/file`

### The log given by the failure.
> Normally this include a stack trace and some more information.

Browser console shows a `ZoneAwareError` with the following message: 
> Unhandled Promise rejection: Failed to load path/to/this/file ; Zone: <root> ; Task: Promise.then ; Value: Failed to load path/to/this/file

### Mention any other details that might be useful.
The example above is a bit pointless, but I step into this problem every time I include a mixin that has a DocBlock on top with an usage example.

**Comment by filipesilva** [comment]
I can verify this happens. It seems to happen only on component CSS though. And it also happens on plan css, it doesn't have to be sass.

It doesn't seem to be a CLI problem though, but rather a Angular problem itself. I could reproduce it in a plunker: https://plnkr.co/edit/AQFWDsIHasYsfCr0HnoE?p=preview

**Comment by filipesilva** [comment]
Reported in https://github.com/angular/angular/issues/15255
