### ISSUE TITLE
How to Name Chunks?

### ISSUE THREAD

**Issue by Narasimha969** [angular/angular-cli#5244]
How to name chunks created by angular/cli in webpack
![capture](https://cloud.githubusercontent.com/assets/20059343/23605580/4e36f7f6-0283-11e7-87e0-0a2d61d9933e.PNG)

**Comment by figuerres** [comment]
@Narasimha969 : why ? what is the problem ?
the files with the 0,1,2,3,4 names are generatd by the compiler as it finds what code needs to be in a chunk, the need for a given chunk may not be the same for each compile if you add code to the app or change the code ....

**Comment by Narasimha969** [comment]
I want to set my own defined names for those 0,1,2,3, 4  etc ..

**Comment by RicardoVaranda** [comment]
DUP of https://github.com/angular/angular-cli/issues/5171

**Comment by rudzikdawid** [comment]
webpack 2.4.0 has nice Features

> import() now allows to configure a chunk name
```
import(/* webpackChunkName: "my-chunk-name" */ "module")
```

https://github.com/webpack/webpack/releases/tag/v2.4.0

**Comment by meyer20** [comment]
When i run with dev mode, all the chunks are generated with your names, in prod mode, the chunks are generated with sequential numbers. In my case, i need the sequential number in both modes.

Dev mode:
https://imgur.com/a/JGRQEuF

Prod mode:
https://imgur.com/a/Z7tZPsb

Someone knows why this happen?

**Comment by Narasimha969** [comment]
@meyer20 In angular.json file, check for configurations

"dev": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": true,
              "aot": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            },

change namedChunks to false

**Comment by meyer20** [comment]
Hi @Narasimha969, sorry for reply you too late.

I tried your suggestion today, but i don't had success :/

My configuration: 
         "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            },
            "dev": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }

Any suggestion?
Thank you for your attention :)

**Comment by simeyla** [comment]
Would really love to be able to name chunks with the datestamp. Then when I see them in error logs I can see if someone is getting an old chunk somehow.

     main.883c6d4bef6e254fc614.js   =>   main.20190903115501XXXXXXXX.js
