### ISSUE TITLE
root tsconfig.json breaking atom-typescript on new project

### ISSUE THREAD

**Issue by scttcper** [angular/angular-cli#5257]
Autocomplete and all inteli type features are broken in atom-typescript without the addition of an exclude in root tsconfig.json:
```
"exclude": ["node_modules"]
```

vscode seems fine. Could be related to https://github.com/TypeStrong/atom-typescript/issues/1106

OSX latest - atom 1.14.4 - atom-typescript 10.1.15

**Comment by dave11mj** [comment]
Thanks ! I was experiencing the same issue and the exclude seems to optimize it for me! ^^

**Comment by Meligy** [comment]
Which version are you using?

There was an issue affecting VS Code as well in RC0, and it should be fixed in new projects generated by RC1, thanks to #5060 [changes](https://github.com/angular/angular-cli/pull/5060/files).

**Comment by dave11mj** [comment]
I am using the following versions:
```
OS X El Capitan version 10.11.6
Angular Cli 1.0.0-rc.0
Atom 1.14.4
atom-typescript 10.1.13
```

**Comment by scttcper** [comment]
1.0.0-rc.1
what I have after adding the exclude
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "lib": [
      "es2016",
      "dom"
    ],
  },
  "exclude": ["node_modules"]
}
```

**Comment by Meligy** [comment]
There were more changes in RC2, check again in a new project please.

**Comment by scttcper** [comment]
Still not working without the exclude. Waiting for https://github.com/TypeStrong/atom-typescript/pull/1166 or people can install atom-typescript-beta. Not really something angular-cli needs to solve since atom-typescript is what's wrong.
