### ISSUE TITLE
Compilation error : Cannot find module 'util'.

### ISSUE THREAD

**Issue by yuridolzhenko** [angular/angular-cli#5258]
### OS?
>Mac OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-rc.0
node: 7.5.0
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.9

### Repro steps.
easy to reproduce. _isNull_ function of _util_ module was accessible before update to RC, now compilation fails.

import statement is following:
import {isNull} from "util";

### The log given by the failure.
ERROR in ... (3,22): Cannot find module 'util'.)

**Comment by jarockja** [comment]
Same problem here with:

`@angular/cli: 1.0.0-rc.1`
`node: 6.9.5`
`os: win32 x64`
`@angular/common: 2.4.9`
`@angular/compiler: 2.4.9`
`@angular/core: 2.4.9`
`@angular/flex-layout: 2.0.0-beta.5`
`@angular/forms: 2.4.9`
`@angular/http: 2.4.9`
`@angular/material: 2.0.0-beta.1`
`@angular/platform-browser: 2.4.9`
`@angular/platform-browser-dynamic: 2.4.9`
`@angular/router: 3.4.9`
`@angular/cli: 1.0.0-rc.1`
`@angular/compiler-cli: 2.4.9`

**Comment by sumitarora** [comment]
@yuridolzhenko `import {isNull} from "util";` imports it from `@types/node` not from Angular CLI. Which package are you importing it from?

**Comment by yuridolzhenko** [comment]
@sumitarora indeed it's coming from @types/node ,  but it there in the freshly generated application and in previous version of cli it was working fine, while in a new one it's not.

**Comment by sinhpn92** [comment]
I have same problem when i use `debuglog` module by import: `import {debuglog} from "util";`.
I checked and found util module in path: `myproject/node_modules/@types/node/index.d.ts:3562`

But when i compile, i got error: `Cannot find module 'util'.`

What's wrong here? Have any suggestion for fix it?

My Version: 
```
@angular/cli: 1.0.0-rc.1
node: 7.7.1
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/upgrade: 2.2.4
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9
```

Project on GitHub: [https://github.com/sinhpn92/angular2-example-types-node](https://github.com/sinhpn92/angular2-example-types-node)

**Comment by yuridolzhenko** [comment]
This https://github.com/angular/angular-cli/wiki/stories-third-party-lib fixed the issue for me. Looks like it's not a bug of angular-cli.

**Comment by filipesilva** [comment]
Closing as answered by @yuridolzhenko, cheers!
