### ISSUE TITLE
Feature: Minify HTML templates before run AOT Compiler in Production

### ISSUE THREAD

**Issue by mbellezi** [angular/angular-cli#5262]
A large part of my AOT compiled templates look like this:

`this.renderer.createText(this._el_0, "             \n ", null)
`

Maybe a good option to get ride of this in production is minify the html templates before AOT compilation.

**Comment by RicardoVaranda** [comment]
Hi @mbellezi,

This sounds like a great idea sadly for version 1.0 the cli is currently not accepting any new features, but I could see potential in this being implemented as part of the add-on functionality that will be implemented for 2.0

**Comment by ciesielskico** [comment]
I'm surprised this is not being done. 
If this is a case there is huge potential for performance and bundle size gains.

**Comment by kylecordes** [comment]
This may make sense as an improvement to Angular itself, benefitting all AOT users rather than only CLI.

**Comment by filipesilva** [comment]
Please open this issue in https://github.com/angular/angular itself instead, since that functionality is part of that repo. I think similar improvements are in 4.0 though.
