### ISSUE TITLE
AOT Webpack Plugin doesn't seem to find errors; ex. for non-public property rule in template

### ISSUE THREAD

**Issue by jbarr33** [angular/angular-cli#5264]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10

### Versions.
@angular/cli: 1.0.0-rc.1
node: 6.9.4
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/compiler-cli: 2.4.9
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/platform-server: 2.4.9
@angular/router: 3.4.5
@ngtools/webpack: 1.2.12

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
No, the app wasn't created with CLI.  It is using AOT webpack plugin

### The log given by the failure.

Well, it's sort of lack of trace/log but I am expecting to see things like below which is what I get if I try to build with ngc directly.

`user-login.component.ngfactory.ts:439:48: Property 'UserName' does not exist on type 'UserLoginComponent'.
`

### Mention any other details that might be useful.
I thought all template properties need to exist and be public in the component code.  I do get errors in when running the AOT build but I thought they would be caught by the AOT compile.  Maybe I don't understand the rules for AOT or the rules have been relaxed or somehow the AOT Webpack plugin is fixing the problem.

Thanks.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
@hansl can you weigh in?

**Comment by StephenFluin** [comment]
It looks like we're silencing any AOT errors.

Repro: https://github.com/StephenFluin/2017-03-22-repro-cli-silent-aot-errors

cc @hansl @robwormald
