### ISSUE TITLE
Assets not working after update

### ISSUE THREAD

**Issue by FunnyGhost** [angular/angular-cli#5268]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-rc.1
node: 7.4.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.
@angular/platform-browser-dynam
@angular/router: 3.4.9
@angular/compiler-cli: 2.4.9

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
The app was created with Angular-CLI

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
I have several images in my src/assets folder. In the html for different components I used to reference them like this:  `href="/assets/some-name.ico"`. This worked before the update. Now it expects a folder src/assets in the dist folder. Not sure what's wrong.
In the angular-cli I have this:
```
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by sumitarora** [comment]
@FunnyGhost When running `ng serve` it runs `dist` in memory and serves assets from `dist\assets` directory.  When running `ng serve --verbose` Do you see file being added in memory as below?
```
   styles.bundle.js.map    13.4 kB    2, 4  [emitted]         styles
   vendor.bundle.js.map    3.45 MB    3, 4  [emitted]         vendor
   inline.bundle.js.map    5.82 kB       4  [emitted]         inline
     assets/angular.svg  899 bytes          [emitted]
            favicon.ico    5.43 kB          [emitted]
             index.html  608 bytes          [emitted]
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 155 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 3.66 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 9.77 kB {4} [initial] [rendered]
```

**Comment by FunnyGhost** [comment]
@sumitarora It does shows that the files are added in memory. 
So, now I use `<img src="assets/image.png">` and it works on `build --prod ` but it doesn't work on ng serve.
If I use `<img src="/assets/image.png">`  it works on `build --prod ` but it doesn't work locally
If I use `<img src="src/assets/image.png">`  it doesn't work on `build --prod ` but it does work locally

**Comment by mmmichl** [comment]
Running into the same issue and I even found a bug. To reproduce, lets assume I have an image `assets/img.jpg` and would like to deploy the application here: `https://x.org/webapp/`. To display the image in a template via HTML and HTML5 navigation, I need to use `<img src="/webapp/assets/img.jpg">`.

With the following command the build works on the target URL: `ng build --prod --aot --deploy-url webapp --base-href webapp`.

Now I would expect to be able to serve my app in similar conditions via `ng serve --base-href webapp`, but all files are served from the root directory:
```
...
          vendor.bundle.js.map    4.78 MB    3, 4  [emitted]         vendor
          inline.bundle.js.map    5.83 kB       4  [emitted]         inline
                assets/img.jpg    2.06 MB          [emitted]  [big]  
                   favicon.ico    15.1 kB          [emitted]         
                    index.html  666 bytes          [emitted]         
```
Adding the `--deploy-url` parameter does not change this behaviour.

As a result, the image is broken on the development server, or worse: if the image works on the development server, it will be broken in production!


⁄Found bug:/ When you run `ng serve --base-href webapp` and access http:/localhost:4200 you will be redirected http://0.0.0.0:4200/webapp/ and your app works. If you hit refresh immediately, the page is broken with following logs in the console:
```
GET http://0.0.0.0:4200/webapp/inline.bundle.js [HTTP/1.1 404 Not Found 7ms]
GET http://0.0.0.0:4200/webapp/polyfills.bundle.js [HTTP/1.1 404 Not Found 7ms]
...
```
Workaround: `ng serve --base-href webapp --deploy-url /webapp`

**Comment by Mufasa** [comment]
I am suffering the same issue. I was on angular-cli **1.0.0-beta.26** and spent the whole day reading all the release notes and update notes to upgrade to **1.0.0**.

When I run `ng serve` or even `ng serve -prod --aot`, my site now fails to load any of the images from my `src/assets` folder - example error:
```
GET http://localhost:4200/assets/img/logo.png 404 (Not Found)
```
If I copy this URL and paste it in a new browser tab then it just redirects me back to the home page of my app. If I paste it and then change the URL to:
```
http://localhost:4200/src/assets/img/logo.png
```
then it correctly fetches the image. Note I added **/src** as a prefix to the **/assets** path above.

If I build it using `ng build --prod --aot` and put the distribution onto my production server then all `normal` assets are delivered correctly. However, my landing page has a background image that is specified within the CSS as:
```
background: url(/assets/img/background.jpg) no-repeat 50%;
```
and this fails to show up on my landing page. If I copy the URL for this image and paste it with my sites host URL in-front then it loads the image with no issues.

My `index.html` contains this in `<head>` section:
```
<base href="/">
```

**apps** section from my `.angular-cli.json` file:
```
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.scss"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
```

**Comment by Mufasa** [comment]
**Some thoughts on the CSS issue**
I just compared the results with my site before the upgrade and noticed the CSS on my previous site came out as:
```
background: url("/assets/img/background.jpg") no-repeat center;
```
Notice that the **url** function parameter is quoted here where as in the new version (shown above) the quotes are missing.
Also notice that it says **center** at the end where as the new version generates **50%**.

The **source** SCSS for this was:
```
#banner {
  background: url("/assets/img/background.jpg") no-repeat center;
  background-size: cover;
  height: 700px;
  padding: 0;
  color: white;
}
```

**Comment by Mufasa** [comment]
Hmmm - it seems if I run this using `ng serve --base-href /` then it all works as expected.

Why do I need to specify the `--base-href` parameter now?

**Comment by NoopDog** [comment]
I had this problem as well.  For me `ng serve --base-href /`  did not help.  Instead it turns out, in my ` .angular-cli.json` i was not specifying `assets` as an array. changing from 

`assets: "assets"` to `assets: ["assets"]` fixed it for me.

This worked before the upgrade from beta 17 to 1.0.1 perhaps the upgrade guide could be upgraded to indicate assets must now be an array if in fact that is the case.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by jas75** [comment]
Hello everyone, I have the exact same issue despite the fact that my angular CLI version is the latest, I can't find a way out since days. Can someone help me with this ?

**Comment by jvnicholson** [comment]
@jas75 i used the latest angular CLI (v1.4.1) and was still having the issue. Doing @NoopDog suggestion worked ("assets" ==> ["assets"])

**Comment by jas75** [comment]
@jvnicholson It's already set

**Comment by Praveenrv24** [comment]
Hi,

My CLI Version is shown below.
C:\Users\admin\Desktop\study>ng -v
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.4
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4

And getting an error while running the application with ng serve
Uncaught TypeError: pre,template,textarea,script,style is not iterable! polyfills.bundle.js:859
GET http://localhost:4200/polyfills.js.map 404 (Not Found) :4200/polyfills.js.map:1
GET http://localhost:4200/InnerSubscriber.js.map 404 (Not Found) :4200/InnerSubscriber.js.map:1
GET http://localhost:4200/app.component.js.map 404 (Not Found)

**Comment by inradius** [comment]
@Praveenrv24 In your polyfills.js file, you probably need to uncomment the lines 
```
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/string';
import 'core-js/es6/array';
```

Usually I will just add one line to cover everything like
```
import 'core-js/es6';
```

**Comment by Praveenrv24** [comment]
Awesome that works.. Thank you... What may the root cause of this?

**Comment by ShoaibIqbal452** [comment]
I am facing same problem but in a different manner. Images I added in assets folder before update are working. But images I added after update are not working at all. Anybody having workaround please share.

**Comment by SgElite** [comment]
Dont know if my problem is related to the above, I have a scenario that I have image files uploaded to the assets\images folder, however, there is a problem is displaying the latest uploaded image files unless I restart or made changes to any typescript file (I guess this is a reload of the environment). 
Is there a way to get angular to always refresh the assets\images folder for the latest files ? 

I am using the following version of angular.
@angular/cli: 1.4.3
node: 6.10.2
os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.3
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
typescript: 2.4.0

**Comment by ShoaibIqbal452** [comment]
i am unable to load any photo from assets that i added after npm update. I get response 404 not found. All photos that i added to assets before update are still accessible. following is sc of network tab.
 
![scree](https://user-images.githubusercontent.com/31730120/32443941-a979b918-c322-11e7-9e57-6c3ed0f75bc0.png)

 Two resoucres down arrow and enterprise logo are also from same asset folder and are asscssible but arrow-down0512 is not
images accessible are those i added to assets before update and one with 404 is added after update

**Comment by a-gerold** [comment]
Same problem here.
With angular/cli 1.5.0 the assets folder is not created.
ng serve and ng build do not create assets folder in /dist/

![image](https://user-images.githubusercontent.com/26137827/32463198-61c99330-c33c-11e7-85b5-675bde50f8b6.png)


"apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",

+-- @angular/animations@5.0.0
+-- @angular/cdk@2.0.0-beta.12
+-- @angular/cli@1.5.0
+-- UNMET PEER DEPENDENCY @angular/common@5.0.0
+-- @angular/compiler@5.0.0
+-- @angular/compiler-cli@5.0.0
+-- UNMET PEER DEPENDENCY @angular/core@5.0.0
+-- @angular/forms@5.0.0
+-- @angular/http@5.0.0
+-- @angular/language-service@5.0.0
+-- @angular/material@2.0.0-beta.12
+-- @angular/platform-browser@5.0.0
+-- @angular/platform-browser-dynamic@5.0.0
+-- @angular/router@5.0.0
+-- @types/jasmine@2.6.2
+-- @types/jasminewd2@2.0.3
+-- @types/node@8.0.48
+-- codelyzer@4.0.1
+-- core-js@2.5.1
+-- hammerjs@2.0.8
+-- jasmine-core@2.8.0
+-- jasmine-spec-reporter@4.2.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.2.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.0
+-- karma-jasmine@1.1.0
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.2.0
+-- rxjs@5.5.2
+-- ts-node@3.3.0
+-- tslint@5.8.0
+-- UNMET PEER DEPENDENCY typescript@2.6.1
`-- zone.js@0.8.18

**Comment by RandyRam** [comment]
I dont find any of the import statements in my pollyfill.ts.

**Comment by tanguiano** [comment]
@mmmichl 's solution worked for me! THANK YOU SO MUCH!!!!!!

**Comment by sachinpachori** [comment]
None of the solution mentioned above worked for me. Has anyone found solution to this issues?

**Comment by demiahmed** [comment]
Hey guys! I'm new to angular and I'm facing the same problem in my app where the local version works perfectly great whereas the github deployment breaks all the URLs for images. My images are placed in src/assets/xyz.jpg directory and I have tried changing the base href as well as my image url and still the image appears to be broken.

I'm using angular 6. Would be really thankful if I get my issue sorted out.

Thanks in advance.

**Comment by PavelFranta** [comment]
@demiahmed > in developer tools you can see why... It is because the path to your images is wrong. 
All of your files are downloaded from for example `localhost/AngularApp/  ` so your images are on `localhost/AngularApp/assets` .... but unfortunately browser looks them on `localhost/assets` and thats why it doesnt get anything.
