### ISSUE TITLE
`npm test` ignoring webpack config (after `ng eject`)

### ISSUE THREAD

**Issue by stevermeister** [angular/angular-cli#5269]
### Versions.
@angular/cli: 1.0.0-rc.1 (e)
node: 6.9.4
os: darwin x64

### Repro steps.
It looks like `npm test` **ignores webpack config** changes: did not work for me with extension for saas-loader.  
I created repo to show the issue - https://github.com/stevermeister/angular-cli-webpack-test

**Comment by filipesilva** [comment]
It seems like the unit tests are still using the CLI plugin. This is a bug.

**Comment by Hagendorn** [comment]
Is there a workaround?

**Comment by sparkbuzz** [comment]
We should be able to export different WebPack configs for example for dev, prod and testing. So perhaps getting a webpack.config.js that imports webpack.(dev|prod|test).js when running ng eject would be a better approach.

**Comment by clydin** [comment]
eject functionality is no longer available in the latest version (6.0+).  For custom webpack configurations the following unofficial add-on is a suggested solution: https://github.com/manfredsteyer/ngx-build-plus
