### ISSUE TITLE
is ng serve --prod a good choice for deployement ?

### ISSUE THREAD

**Issue by amineparis** [angular/angular-cli#5274]
is ng serve --prod an alternative to expressjs configuration to deploy angular 2 apps ?

**Comment by grizzm0** [comment]
ng serve uses webpack-dev-server which is a development server and not suited for production.

**Comment by amineparis** [comment]
do I need to define my own expressjs configuration file ?

**Comment by deebloo** [comment]
@amineparis you will need to setup your own web server. It can be anything, node, apache etc.

**Comment by Brocco** [comment]
@amineparis both @grizzm0 & @deebloo are correct, you do not want to use `ng serve` in production even if you use the `--prod` flag.

The reason that flag exists is to mimic the compilation steps of a production build in a dev environment locally to ease your development process if you so desire.

Summary: use `ng serve` for development with or without `--prod` and use a production ready web server for deployments.

**Comment by filipesilva** [comment]
Just wanted to add that you can find some deployment information at https://angular.io/docs/ts/latest/guide/deployment.html

**Comment by ellvtr** [comment]
URL changed to https://angular.io/guide/deployment
The link above is broken @filipesilva
