### ISSUE TITLE
Cannot install Angular cli globally

### ISSUE THREAD

**Issue by MShah890** [angular/angular-cli#5277]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
ng --version

module.js:472
    throw err;
    ^
Error: Cannot find module 'C:\Users\nimo\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

node --version

7.1.1

npm --version

4.3.0

### The log given by the failure.
> Normally this include a stack trace and some more information.

![image](https://cloud.githubusercontent.com/assets/9371688/23654927/f61c3410-0358-11e7-9a5f-671175bd3181.png)

![image](https://cloud.githubusercontent.com/assets/9371688/23654956/1817910e-0359-11e7-8301-e5f3aee22db3.png)

![image](https://cloud.githubusercontent.com/assets/9371688/23654962/24781c52-0359-11e7-9ee5-1f4f597368eb.png)

### As per instructions on website uninstalled angular-cli locally and globally, cleaned cache and then tried to install it globally. Was giving error so I uninstalled npm and node and installed their latest versions 4.3.0 and 7.1.1 respectively. Errors are shown in screenshots. Also tried with node version 6.10.0

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by RicardoVaranda** [comment]
From your first screenshot it seems like node-sass requires Windows SDK 8.1, this is due to you most likely being behind a proxy or aws is blocked which is stopping you from downloading pre-built binary. 

You have two options here, either manually install Windows SDK 8.1 or download the cli without being behind a proxy.

**Comment by filipesilva** [comment]
There's something else you can try... but it's not really recommended. You can try a forced install, which should ignore the unavailable node-sass install.

You'd also have to always manually install CLI with force on projects though. This is far from optimal but... it's better than nothing.

```
npm install @angular-cli -g --force
ng new project-name --skip-install
cd project-name
npm install --force
```

**Comment by MShah890** [comment]
Solved opened cmd with administrator
