### ISSUE TITLE
Missing loader for xlf files (i18n files)

### ISSUE THREAD

**Issue by aviadisr** [angular/angular-cli#5285]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-rc.1 (e)
node: 6.9.5
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

### Repro steps.
> The application was created using the CLI. Added Angular translation module with the cookbook instructions and a fix to adjust to webpack (see http://stackoverflow.com/questions/40635736/angular-2-translations-with-webpack). 
When building the application I get error saying that a loader is missing and the translation is not working.

### The log given by the failure.
> Normally this include a stack trace and some more information.

WARNING in ./src/assets/locale/messages.tst.xlf
Module parse failed: C:\GIT\aps_ng_skeleton\src\assets\locale\messages.tst.xlf Unexpected token (1:0)
**You may need an appropriate loader to handle this file type.**
| <?xml version="1.0" encoding="UTF-8" ?>
| <xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
|   <file source-language="en" datatype="plaintext" original="ng2.template">
 @ ./src/assets/locale ^\.\/messages\..*\.xlf$
 @ ./src/app/i18n-providers.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4201 ./src/main.ts

### Mention any other details that might be useful.
The only way I found to workaround it is to do "ng eject" and add a loader to the webpack configuration. But then I get issues with the router, so it would be great if you can add the loader to the CLI.

Thanks.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by aviadisr** [comment]
This is the loader that worked for me:

rules: [
            {
        "test": /\.xlf/,
        "loader": "promise-loader?es6-promise!raw-loader"
      },

**Comment by clydin** [comment]
The ng build command with a production build supports the AOT section of the referenced  tutorial.

**Comment by chatoooo** [comment]
This works for me.
`require('raw-loader!../locale/messages.' + locale + '.xlf')`
Cannot use backticks, webpack won't know which files to include in the bundle.

**Comment by aviadisr** [comment]
Thanks!. worked for me too.

**Comment by bimal72** [comment]
@aviadisr  Where did you put require() ? I am facing similar issue  issue from ng2-webcam plugin..
Failed to compile.

./~/ng2-webcam/lib/fallback/jscam.swf
Module parse failed: f:\projects\edu\hops\webcam\node_modules\ng2-webcam\lib\fallback\jscam.swf Unexpected character '' (1:3)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/ng2-webcam/index.ts 4:0-34
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
