### ISSUE TITLE
Use environments to configure api endpoint ?

### ISSUE THREAD

**Issue by amineparis** [angular/angular-cli#5292]
How to use environments to configure api endpoint after build ? is it mean to be usefull for such use cases ?

**Comment by RicardoVaranda** [comment]
Hey @amineparis ,

This can be achieved by doing the following:

In your environments.ts:

```
export const environment = {
  production: false,
  productionApi: "https://test-url.com"
};
```

Within your components you just have to import it like:

```
import { environment } from '../../environments/environment';
```

The relative path depends on where your component is.

**Comment by amineparis** [comment]
Strange world ! why 52 + 73 upvotes in stackoverflow talks about something else [here](http://stackoverflow.com/questions/34986922/define-global-constants-in-angular-2)

**Comment by RicardoVaranda** [comment]
Looks like they aren't using the cli so I'm guessing they don't have the environments file, but the concept of import is the same :)

**Comment by filipesilva** [comment]
Closing as answered, thanks @RicardoVaranda !

**Comment by b-mi** [comment]
Another false solution. Endpoint in environments.ts IS HARD-CODED.
