### ISSUE TITLE
is it normal to have dist/index.html showing white page ?

### ISSUE THREAD

**Issue by amineparis** [angular/angular-cli#5293]
after executing the build, what is the proper way to test if the build is ok without interacting with a web server. opening dist/index.html displays a white page and I can't explain why ?

**Comment by deebloo** [comment]
@amineparis you will need to have a server running so that the page can fetch the required resources.

If you want to test your production build using the build in dev server you can run.

```TS
ng serve --prod
```

For future reference the angular cli gitter channel would be a better place to ask questions like this.

**Comment by amineparis** [comment]
why directly opening dist/index.html displays white page knowing that it is only html/css/js ?

**Comment by deebloo** [comment]
if you look at the console it is an issue with paths to resources

**Comment by deebloo** [comment]
it is an issue with paths to resources

**Comment by amineparis** [comment]
thank you ! PS : I am wondering on how to thank someone on github other than poluting the issue with a useless comment like this one ?

**Comment by deebloo** [comment]
haha. unfortunately I don't know of  great way. :)

**Comment by israr2018** [comment]
I was facing the same issue when trying to  render index.html file from dist folder, I a figure out that there was issue with specifying the static filles to the express server. So you should dobule check if you are specifying  correctly the static folder to express server where the index.html file resides.

**Comment by mohammadiyan** [comment]
I think you should change the value of <base href="/"> in the index.html file.

**Comment by ar-to** [comment]
comment out the `<base>` tag and try it again for testing it. I would also manually set the base tag href when building the `/dist` folder try setting it within the command:

```
ng build --base-href domain.com/whatever/ --prod
```

**Comment by rakeshnayak360** [comment]
I followed following command to test service worker in my angular 7 project.

ng build --prod
cd dist/appname
http-server -p 8082

![image](https://user-images.githubusercontent.com/19386889/58458946-f5eb2400-8147-11e9-85fc-6b6eaddb31dc.png)

And page showing like this
![image](https://user-images.githubusercontent.com/19386889/58458994-0ef3d500-8148-11e9-8c6d-a54d1fa44ceb.png)


how to fix
