### ISSUE TITLE
sample nodejs/expressjs configuration file for angular-cli build generated project ?

### ISSUE THREAD

**Issue by amineparis** [angular/angular-cli#5297]
since it's a common need, I am wondering how I can't find such a resssource available in the web ?

**Comment by deebloo** [comment]
The output of angular cli is just static html, js and css. You can use whatever server you want. Here is a link that should give you an example. NOTE: The article is using an old version of the cli.

https://scotch.io/tutorials/mean-app-with-angular-2-and-the-angular-cli

**Comment by amineparis** [comment]
but it would be greate if repo wiki tab provide such sample files for major web servers

**Comment by deebloo** [comment]
https://angular.io/docs/ts/latest/guide/deployment.html
