### ISSUE TITLE
long update time 285707ms

### ISSUE THREAD

**Issue by krasevych** [angular/angular-cli#53]
on Windows 8. I started with 'ng serve'. then I changed something and I wait for update a lot of time:
http://i.piccy.info/i9/027b0071fa9fcdda914dbbf8c8804ce4/1445783730/39770/964005/Untitled.png

**Comment by cebor** [comment]
Readme.md
```markdown
...
On Windows you need to run the build and serve commands with Admin permissions otherwise the performance really sucks.
...
```

**Comment by krasevych** [comment]
@cebor Thank you. I missed it when I read Readme.md.
but now after some changes, page doesn't refresh automatically. I should refresh page manually

**Comment by IgorMinar** [comment]
automatic refresh should work if it doesn't please file a new issue.

the windows perf issues are a known issue and we have a plan to fix that down the road without the need for admin privileges.
