### ISSUE TITLE
Environement files generated twice when changing sourceDir parameter

### ISSUE THREAD

**Issue by maxailloud** [angular/angular-cli#530]
Hi there,

After sawing this Pull Request https://github.com/angular/angular-cli/pull/412 I wanted to give it a try.
So I made a change in my angular-cli-build.js file:

```js
/* global require, module */

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
    return new Angular2App(defaults, {
        vendorNpmFiles: [],
        sourceDir: 'src'
  });
};
````

Just added the sourceDir parameter.

It's working great, now I don't have the client folder that I was useless to me.
But the environement.js file is still copied in the `build/client/app` folder.
So I end up having 2 environement.js file, in the right folder `build/app`and in the wrong, that should not exist, folder `build/client/app/`.

FYI:

Mac OSX El Capitan
angular-cli: 0.0.33
node: 5.0.0
os: darwin x64

**Comment by filipesilva** [comment]
Ah that is entirely my fault. Will fix it asap.

**Comment by maxailloud** [comment]
Ok, thank you.
