### ISSUE TITLE
ng serve doesn't work in new project rc.1

### ISSUE THREAD

**Issue by gmasarczyk** [angular/angular-cli#5300]
### OS?
Windows 10 

### Versions.
@angular/cli: 1.0.0-rc.1
node: 7.7.1
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

### Repro steps.
npm uninstall -g angular-cli
npm uninstall --save-dev angular-cli
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@latest
rm -rf node_modules dist # use rmdir on Windows
npm install --save-dev @angular/cli@latest
npm install
ng new PROJECT_NAME
cd PROJECT_NAME
ng serve

### The log given by the failure.
C:\Users\gm\Documents\repositories\angapp>ng serve
** NG Live Development Server is running on http://localhost:4200 **
Hash: 8e89993c40a9afc78324
Time: 2685ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 553 bytes {3} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.js.map (styles) 28 bytes {3} [initial] [rendered]
chunk    {2} main.bundle.js, main.bundle.js.map (main) 565 bytes [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localhost:4200' in 'C:\Users\gm\Documents\repositories\angapp'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in multi ./src/styles.css
Module not found: Error: Can't resolve 'style-loader' in 'C:\Users\gm\Documents\repositories\angapp'
 @ multi ./src/styles.css

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'raw-loader' in 'C:\Users\gm\Documents\repositories\angapp':
  Error: Can't resolve 'raw-loader' in 'C:\Users\gm\Documents\repositories\angapp'

  - compiler.js:76
    [npm]/[cli]/[html-webpack-plugin]/lib/compiler.js:76:16

  - Compiler.js:280 Compiler.<anonymous>
    [npm]/[cli]/[webpack]/lib/Compiler.js:280:10

  - Compiler.js:480
    [npm]/[cli]/[webpack]/lib/Compiler.js:480:13

  - Tapable.js:138 next
    [npm]/[cli]/[webpack]/[tapable]/lib/Tapable.js:138:11

  - CachePlugin.js:62 Compiler.<anonymous>
    [npm]/[cli]/[webpack]/lib/CachePlugin.js:62:5

  - Tapable.js:142 Compiler.applyPluginsAsyncSeries
    [npm]/[cli]/[webpack]/[tapable]/lib/Tapable.js:142:13

  - Compiler.js:477
    [npm]/[cli]/[webpack]/lib/Compiler.js:477:10

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:640 self.applyPluginsAsync.err
    [npm]/[cli]/[webpack]/lib/Compilation.js:640:19

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:631 self.applyPluginsAsync.err
    [npm]/[cli]/[webpack]/lib/Compilation.js:631:11

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:626 self.applyPluginsAsync.err
    [npm]/[cli]/[webpack]/lib/Compilation.js:626:10

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:622 sealPart2
    [npm]/[cli]/[webpack]/lib/Compilation.js:622:9

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:570 Compilation.seal
    [npm]/[cli]/[webpack]/lib/Compilation.js:570:8

  - Compiler.js:474
    [npm]/[cli]/[webpack]/lib/Compiler.js:474:16

  - Tapable.js:225
    [npm]/[cli]/[webpack]/[tapable]/lib/Tapable.js:225:11

  - Compilation.js:472 _addModuleChain
    [npm]/[cli]/[webpack]/lib/Compilation.js:472:11

  - Compilation.js:365 Compilation.errorAndCallback
    [npm]/[cli]/[webpack]/lib/Compilation.js:365:4

  - Compilation.js:382 moduleFactory.create
    [npm]/[cli]/[webpack]/lib/Compilation.js:382:12

  - NormalModuleFactory.js:234
    [npm]/[cli]/[webpack]/lib/NormalModuleFactory.js:234:19

  - NormalModuleFactory.js:59 onDoneResolving
    [npm]/[cli]/[webpack]/lib/NormalModuleFactory.js:59:20

  - NormalModuleFactory.js:183
    [npm]/[cli]/[webpack]/lib/NormalModuleFactory.js:183:21

  - async.js:3694
    [npm]/[cli]/[webpack]/[async]/dist/async.js:3694:9

  - async.js:359
    [npm]/[cli]/[webpack]/[async]/dist/async.js:359:16

  - async.js:933 iteratorCallback
    [npm]/[cli]/[webpack]/[async]/dist/async.js:933:13

  - async.js:843
    [npm]/[cli]/[webpack]/[async]/dist/async.js:843:16

  - async.js:3691
    [npm]/[cli]/[webpack]/[async]/dist/async.js:3691:13

  - async.js:21 apply
    [npm]/[cli]/[webpack]/[async]/dist/async.js:21:25

  - async.js:56
    [npm]/[cli]/[webpack]/[async]/dist/async.js:56:12

  - async.js:1012
    [npm]/[cli]/[webpack]/[async]/dist/async.js:1012:9

  - async.js:359
    [npm]/[cli]/[webpack]/[async]/dist/async.js:359:16

  - async.js:933 iteratorCallback
    [npm]/[cli]/[webpack]/[async]/dist/async.js:933:13

  - async.js:843
    [npm]/[cli]/[webpack]/[async]/dist/async.js:843:16

  - async.js:1009
    [npm]/[cli]/[webpack]/[async]/dist/async.js:1009:13

  - NormalModuleFactory.js:262
    [npm]/[cli]/[webpack]/lib/NormalModuleFactory.js:262:19

  - Resolver.js:70 onResolved
    [npm]/[cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:70:11

  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19

  - Resolver.js:138 afterInnerCallback
    [npm]/[cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:138:10

  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19

  - Tapable.js:181 Resolver.applyPluginsAsyncSeriesBailResult1
    [npm]/[cli]/[webpack]/[tapable]/lib/Tapable.js:181:46

  - Resolver.js:125 innerCallback
    [npm]/[cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:125:19

  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19

  - Tapable.js:283
    [npm]/[cli]/[webpack]/[tapable]/lib/Tapable.js:283:15

  - UnsafeCachePlugin.js:38
    [npm]/[cli]/[webpack]/[enhanced-resolve]/lib/UnsafeCachePlugin.js:38:4

  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19

  - Resolver.js:138 afterInnerCallback
    [npm]/[cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:138:10

  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19

  - Tapable.js:181 Resolver.applyPluginsAsyncSeriesBailResult1
    [npm]/[cli]/[webpack]/[tapable]/lib/Tapable.js:181:46

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (C:\Users\gm\Documents\repositories\angapp\node_modules\typescript\lib\typescript.js:8062:20)
    at Object.createCompilerHost (C:\Users\gm\Documents\repositories\angapp\node_modules\typescript\lib\typescript.js:44978:26)
    at Object.ngcLoader (C:\Users\gm\Documents\repositories\angapp\node_modules\@ngtools\webpack\src\loader.js:338:33)
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/polyfills.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (C:\Users\gm\Documents\repositories\angapp\node_modules\typescript\lib\typescript.js:8062:20)
    at Object.createCompilerHost (C:\Users\gm\Documents\repositories\angapp\node_modules\typescript\lib\typescript.js:44978:26)
    at Object.ngcLoader (C:\Users\gm\Documents\repositories\angapp\node_modules\@ngtools\webpack\src\loader.js:338:33)
 @ multi ./src/polyfills.ts
webpack: Failed to compile.

**Comment by jlouros** [comment]
this might help https://github.com/angular/angular-cli/issues/3781#issuecomment-285022870

**Comment by filipesilva** [comment]
@jlouros comment seems spot on - you seem to have a broken install and maybe even an old version of the CLI.
