### ISSUE TITLE
Warning issued when private "number" property with default value used in constructor

### ISSUE THREAD

**Issue by cryptobrains** [angular/angular-cli#5304]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10, Mac OSX El Capitan

### Versions.

node: 6.9.5
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9
@angular/platform-server: 2.4.9

### Repro steps.

Create a service whose constructor will have this form:

  constructor(private maxCapacity: number = -1) {
    this.itemAdded$ = new EventEmitter();
    this.collectionChanged$ = new EventEmitter();
  }

### The log given by the failure.

ng build will have this issue with it:

WARNING in ./src/$$_gendir/app/app.module.ngfactory.ts
722:80-95 "export 'number' (imported as 'import49') was not found in '../../app/services/collection/collection.service'

This was seen in the particular case where that service was used by a component with no default value passed to its constructor.

### Mention any other details that might be useful.

Removing this prevented odd crashes in seemingly-unrelated parts of my app where during bootstrap the angular app would crash with a complaint that number was not an exported class.

**Comment by filipesilva** [comment]
Right, the constructor of an Angular service receives it's parameters via Dependency Injection. It doesn't make a lot of sense to add a default there, and it's not supported as far as I know.
