### ISSUE TITLE
Inconsistent naming for services

### ISSUE THREAD

**Issue by thorstenschaefer** [angular/angular-cli#531]
Based on the official Angular2 documentation, it seems that the standard for naming services is:
UserService, defined in class user.service.ts
If I generate a service using "ng g service user", it creates the correct file (create src/client/app/user.service.ts), but the class itself is named "User" instead of "UserService". 

Is this the intention or a bug? Note that when using "ng g service UserService", the class name would be "user-service.service.ts", which doesn't seem nice either.

**Comment by Brocco** [comment]
Good catch, we will update blueprint to handle this command

```bash
ng generate service user
```

to generate this code (_whitespace removed for brevity_):
```javascript
import {Injectable} from 'angular2/core';
@Injectable()
export class UserService {
  constructor() {}
}
```
