### ISSUE TITLE
Internal js that prints </body> makes compiler place *.styles.js at the wrong place

### ISSUE THREAD

**Issue by jeroenptrs** [angular/angular-cli#5311]
### OS?
macOS sierra

### Versions.
@angular/cli: 1.0.0-rc.1
node: 6.10.0
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

### Repro steps.
Created with the CLI, index.html was adjusted to include a JS script that shows a popup, somewhere showing </body>. It can be reproduced by putting this before </head>:
```
<script type="text/javascript">
    console.log('</body>');
</script>
```

### The log given by the failure.
Not really a stack trace, app stays stuck at loading screen though.
```
(index):144 Uncaught SyntaxError: Invalid or unexpected token
styles.bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at styles.bundle.js:1
(anonymous) @ styles.bundle.js:1
vendor.bundle.js:1Uncaught ReferenceError: webpackJsonp is not defined
    at vendor.bundle.js:1
(anonymous) @ vendor.bundle.js:1
main.bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at main.bundle.js:1
```

### Mention any other details that might be useful.

I'm not saying it's good practice to do any of these steps. But, it fails to compile the project regardless.

**Comment by mattdistefano** [comment]
I think some of your repro steps got lost - if there was code in there, can you post in a code block?

**Comment by JeroenPtrs** [comment]
@mattdistefano the code was a jquery prepend script, but a console.log('</body>') does the exact same thing.

**Comment by mattdistefano** [comment]
Can you post the code that causes the problem, though? It's not quite clear what's meant by printing body.

**Comment by JeroenPtrs** [comment]
@mattdistefano I updated the repro! This reproduces the error. Any reference to \</body> in the code will result in the *.bundle.js scripts to be prepended to that first reference.

**Comment by Meligy** [comment]
That could be an issue in https://github.com/jantimon/html-webpack-plugin actually, which the CLI uses.

However, closing tags in script tags are known to be problematic in general (specific to inline script tags, if it's in files loaded via script src, that's different and OK).

A workaround would be replacing `"</body>"` with silly `"<" + "/body>"`, with a comment explaining why.

**Comment by clydin** [comment]
Closing as the listed version is a 1.0 pre-release and 6.0 has changed the html processing to use full HTML parsing.
