### ISSUE TITLE
Import order in styles.scss

### ISSUE THREAD

**Issue by JoshuaNovak919** [angular/angular-cli#5312]
When you add @import files to the `styles.scss` file they are not added to the page in the order that they are in in the file. For me it's adding bootstrap after my theme, even though I have bootstrap before the them in the file.

### OS?
Mac

### Versions.

@angular/cli: 1.0.0-rc.0
node: 6.9.2
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.9

**Comment by builtbyjay** [comment]
Can we see the import statements in your SCSS file?

**Comment by JoshuaNovak919** [comment]
This is my `styles.scss` file:

```
@import 'variables';
@import '../node_modules/bootstrap/scss/bootstrap';
@import 'assets/css/mdb.css';
```

It loads bootstrap last for some reason and my theme for bootstrap before, so the styles are all messed up. I ended up putting them in the `angular-cli.json` for now, but this will make it tough to override the theme when needed.

**Comment by builtbyjay** [comment]
If you declare the `.css` extension in a SASS import, it will compile to a traditional CSS import and hoist `@import 'assets/css/mdb.css';` to the top of your file.

Remove the file extension and SASS will inline the contents of that file at the position where you declare the import.

So, in conclusion, remove the `.css` from your final import.

**Comment by JoshuaNovak919** [comment]
@builtbyjay Oh ok. Thanks!!
