### ISSUE TITLE
angular 2 error file not found

### ISSUE THREAD

**Issue by NaomiRison** [angular/angular-cli#5314]
> Please provide us with the following information:
I am using chrome on windows 10.  Instead of getting an output of a text I'm getting "loading....."
I looked in console and got this message:

" Failed to load resource: net::ERR_FILE_NOT_FOUND file:///C:/favicon.ico "
what the heck do I do now?
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by NaomiRison** [comment]
I am trying to get started with angular 2 ....HELP

**Comment by mattdistefano** [comment]
Make sure you're running `ng serve` and browsing via the web server URL.

**Comment by NaomiRison** [comment]
what do you mean? just type" ng serve " in terminal and try the program again?

**Comment by NaomiRison** [comment]
it still not showing text it instead reads {{title}}
here is program:

html file:
<h1>
  {{title}}
</h1>

components.tss file:
import { Component } from '@angular/core';

@Component({
  selector:  'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'I changed it!';
}

**Comment by mattdistefano** [comment]
Take a look at https://github.com/angular/angular-cli/wiki

**Comment by NaomiRison** [comment]
so typing "ng test" will help?

**Comment by deebloo** [comment]
Are you viewing the app at localhost:4200?

**Comment by NaomiRison** [comment]
i dont know

**Comment by NaomiRison** [comment]
sorry

**Comment by NaomiRison** [comment]
im trying to view it on chrome

**Comment by NaomiRison** [comment]
its not on a website but on my desktop

**Comment by mattdistefano** [comment]
If you run `ng serve` from the command line in your project folder, that will start a development web server on `http://localhost:4200/`. So if you open Chrome to `http://localhost:4200/` you should see your app.

**Comment by filipesilva** [comment]
@NaomiRison heya, there seems to be a lot of confusion here and not a lot of information. Let's take a couple of steps back.

- First, are you using Angular CLI?
- Did you make your project using the `ng new project-name` command?
- As @mattdistefano and @deebloo trying to figure out, it seems like you are *double clicking* `index.html` instead of running the Angular CLI server. To run the server, use `ng serve` then open your browser on `localhost:4200`

**Comment by filipesilva** [comment]
Closing as inactive.

**Comment by kcpeter** [comment]
my problem  is making a head from  here The CLI created the first Angular component for you. This is the root component and it is named app-root. You can find it in ./src/app/app.component.ts.

Open the component file and change the title property from Welcome to app!! to Welcome to My First Angular App!!:     i dont  understand ./scr/app/app.component.ts

**Comment by kcpeter** [comment]
hello markdown
