### ISSUE TITLE
Tracking: document `--prod` and add minification flag

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#5315]
We should document what `--prod` really does. 

It's actually a sort of meta-flag that adds a bunch of defaults: https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/models/webpack-config.ts#L84-L89

Besides setting these defaults, it also adds minification and a few more things: https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/models/webpack-configs/production.ts#L85-L93

Minification should perhaps be opt-in however, via a flag.

**Comment by johnnliu** [comment]
I was able to figure out that --prod seem to have done AOT and -environment=prod but wasn't sure what else it did.

The really shocking part was actually that I find the documentation missing and that filled me with worry.

Thanks for clarifications on twitter.

**Comment by sumitarora** [comment]
@filipesilva we can add that in `build` command wiki ?

**Comment by filipesilva** [comment]
@sumitarora I'm adding the docs bit in https://github.com/angular/angular-cli/pull/6232, can you add the minification flag while you're fixing the UglifyJS problems you are working on?
