### ISSUE TITLE
routerLinkActive doesnt work

### ISSUE THREAD

**Issue by mapsgeek** [angular/angular-cli#5316]
Windows 8

@angular/cli: 1.0.0-rc.1
node: 7.6.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

the router works and it changes components templates but 
routerLinkActive="active", doesn't set active class to the active link

**Comment by ClemensSchneider** [comment]
What is the exact way you are using it in your template?  
It should work like this:

```
<a [routerLink]="['/home']" [routerLinkActive]="['active']">Home</a>
```

**Comment by MeMeMax** [comment]
This should be definately an issue of angular 2. Not CLI.
Remember that in most cases you set the active class on a <li> element not on the <a> element like this:

`<li routerLinkActive="active"><a routerLink="/anypage">any page</a></li>`

**Comment by mapsgeek** [comment]
Ok sorry for inconvenient, still doesn't work the way it should be neither on the <li> or the <a> tag as it's in the documentation.
