### ISSUE TITLE
tsconfig paths fails subsequent compiles

### ISSUE THREAD

**Issue by m0tter** [angular/angular-cli#5318]
I'm using paths in tsconfig to resolve a module outside of the client folder. The first time I run 'ng server' it works perfectly, every subsequent re-compile on change fails with a 'Cannot find module robocomp' error.

tsconfig.app.json  contains:
`"baseUrl": ".",
"paths": {
      "robocomp": ["../../common/robocomp.d.ts"]
    }, ...`

tsconfig.json contains:
`"baseUrl": ".",
"paths": {
      "robocomp": ["../common/robocomp.d.ts"]
}, ...`

Folder structure:
/client/
--/tsconfig.json
--/src/app/tsconfig.app.json
/common/
--/robocomp.d.ts

robocomp.d.ts
`export module 'robocomp' {
export interface User {
name: string
password: string
}
}`

I've tried it in one tsconfig and not the other, I've tried it with the baseurl set to a fullstop and without. It compiles fine on first run.

Windows 10
@angular/cli: 1.0.0-rc.0
node: 6.9.2
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.9

Thanks

**Comment by filipesilva** [comment]
Heya, can you put up a simple repo where this happens? I'm trying to reproduce it without much success.

**Comment by m0tter** [comment]
Hi,
Here you go: 
https://github.com/m0tter/clitest

I've added the steps to the readme.

Thanks!

**Comment by m0tter** [comment]
Hi,
1.0.0-rc.2 fixes the problem. When I posted this I was still running rc.0

Thanks for following it up.
