### ISSUE TITLE
 Cannot find name 'require'

### ISSUE THREAD

**Issue by zhujintao** [angular/angular-cli#5322]
Hi, angular-cli update to @angular/cli: 1.0.0-rc.1      An error has occurred .  pls help  

**npm**

npm install crypto-js
npm install @types/crypto-js
typings install dt~crypto-js

**app.component.ts**
import { Component } from '@angular/core';

var CryptoJS = require('crypto-js');

**ng serve**

ERROR in C:/Users/Jino/Documents/ngProject/slb/src/app/app.component.ts (3,16): Cannot find name 'require'.)

C:\Users\Jino\Documents\ngProject\slb>ng -v
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0-rc.1
node: 7.7.2
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

**Comment by splintercode** [comment]
Just hit this as well. If I get a fix I'll post back.

**Comment by filipesilva** [comment]
I wouldn't encourage importing packages using `require`, but if you need to make sure you've added `node` to the `types` array in `.angular-cli.json`.

**Comment by sven42** [comment]
@filipesilva 
I can not find any information about an `types` array in `.angular-cli.json`
Did you mean the `types` array in `tsconfig.json` or do you have any further information?

**Comment by coryrylan** [comment]
@sven42 `types` goes in the `tsconfig.json`

**Comment by HoosierWrangler** [comment]
Why not copy an example of what you mean exactly for those of us getting the same error? Have no idea what you are talking about but getting the same error

**Comment by filipesilva** [comment]
Apologies, it indeed meant `tsconfig.json` instead of `.angular-cli.json`. More specifically, `src/tsconfig.app.json`. It has a `"types": []` entry, where you can add more types (such as `"node"`). Again though, I don't suggest doing it.

**Comment by code1line** [comment]
I don't want to use require either. Is there a better way for importing a localization-file (.json), which is included in a npm-package?

**Comment by realappie** [comment]
@filipesilva Why do you recommend against using `require` and what is a better alternative ?

**Comment by leosudeep1** [comment]
in src folder open tsconfig.app.json and add 
"compilerOptions": {
   ...
    **"types": [
      "node"
    ]**
  },
