### ISSUE TITLE
using require('fs')

### ISSUE THREAD

**Issue by loongdefect** [angular/angular-cli#5324]
Hi,
I try use 'filesystem' for working with file.
but when use code: `import * as fs from "fs"` or `var fs = require('fs')`. Result of both way incorrect

**Comment by deebloo** [comment]
@loongdefect you can't use nodes filesystem api in a front end application.

**Comment by filipesilva** [comment]
Closing as answered.

**Comment by dneeleman** [comment]
Angular-CLI supports Universal now, so there is a solution needed for that now right?

**Comment by Lecha1** [comment]
I think the problem here is that people do not really get what do you mean when you just say angular and frontend you have to give a bit more details on the subject!
