### ISSUE TITLE
ng build --app="non-existent app name in .angular-cli.json" builds first defined app

### ISSUE THREAD

**Issue by varadero** [angular/angular-cli#5325]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-rc.1
node: 7.7.1
os: win32 x64
@angular/common: 4.0.0-rc.2
@angular/compiler: 4.0.0-rc.2
@angular/core: 4.0.0-rc.2
@angular/forms: 4.0.0-rc.2
@angular/http: 4.0.0-rc.2
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0-rc.2
@angular/platform-browser-dynamic: 4.0.0-rc.2
@angular/router: 4.0.0-rc.2
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 4.0.0-rc.2

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
The app was created with ```ng new ...```
Repro steps:

1. Create new project with ```ng new whatever```
2. Navigate to whatever - ```cd whatever```
2. Execute ```ng build --app="non existent app name"```

### The log given by the failure.
> Normally this include a stack trace and some more information.
Log from app build process

### Mention any other details that might be useful.
When the user wants to build specific app defined in .angular-cli.json file but it mistypes the name, angular-cli builds the first defined app. I believe this is wrong since it can and will confuse the user and also automated scripts - instead of desired app the first one will be build and the result will be wrong. angular-cli must throw error if specified app name in ```--app``` parameter does not exist. Further more, if there are two or more apps defined in .angular-cli.json, ```ng build``` must also throw error. In such cases ```--app``` must be mandatory.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I agree when you use a app name that doesn't exist we should throw an error. That is a bug.

I don't agree that `--app` should be mandatory when you have multiple apps. We default to the first app. We should have a config item to choose the default app though.
