### ISSUE TITLE
Module not found: Error: Can't resolve '@types/applicationinsights-js/index'

### ISSUE THREAD

**Issue by harry671003** [angular/angular-cli#5328]
### OS?
> Windows 10

### Versions.
> @angular/cli: 1.0.0-rc.1
node: 6.9.1
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

### Repro steps.
> npm install --save ng2-appinsights

Import AppInsightsModule into AppModule

> ng build -prod

### The log given by the failure.
> ERROR in ./src/$$_gendir/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve '@types/applicationinsights-js/index' in 'C:\Users\hajohn\Source\Test\ng2-app-test\src\$$_gendir\app'
 @ ./src/$$_gendir/app/app.module.ngfactory.ts 48:0-64
 @ ./src/main.ts
 @ multi ./src/main.ts

### Mention any other details that might be useful.

The package `ng2-appinsights` has a dependency on another JS library `applicationinsights-js`. The definitions of the library are present in `@types/applicationinsights-js`

**Comment by filipesilva** [comment]
That package seems to be broken or to have broken types.
