### ISSUE TITLE
Getting EJSONPARSE error on running 'npm install -g @angular/cli'

### ISSUE THREAD

**Issue by RohitRane** [angular/angular-cli#5331]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Ubuntu 16.04 LTS

### Versions.
N/A. Unable to install angular-cli itself

### Repro steps.
> I ran 'npm install -g @angular/cli'

### The log given by the failure.
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@angular/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/home/mymachine/.nvm/versions/node/v6.9.2/bin/node" "/home/mymachine/.nvm/versions/node/v6.9.2/bin/npm" "install" "-g" "@angular/cli"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! file /home/mymachine/.npm/html-entities/1.2.0/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/mymachine/.npm/html-entities/1.2.0/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mymachine/RnD/angular-cli/npm-debug.log

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by markfejes** [comment]
Can you please attach your `/home/mymachine/.npm/html-entities/1.2.0/package/package.json` file? :)

**Comment by RohitRane** [comment]
Hi @markfejes sorry for the delayed response, was on a vacation. The file that you asked for '/home/mymachine/.npm/html-entities/1.2.0/package/package.json' exists but in my machine but is completely empty.

**Comment by filipesilva** [comment]
You seem to have a broken package, `html-entities`. Try removing it and then you should be able to install the CLI.

**Comment by RohitRane** [comment]
I tried `npm remove -g html-entities`. But the problem persists.

**Comment by RohitRane** [comment]
`npm cache clean`

Does the job. After that I ran `npm install -g @angular/cli` again.
