### ISSUE TITLE
Enhancement: ng g -help should show help for all blueprints

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#5335]
### OS?
Mac OSX Sierra 10.12.3

### Versions.
@angular/cli: 1.0.0-rc.1
node: 6.9.1
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

### Repro steps.
`ng g -h`

### The log given by the failure.
`Invalid blueprint: -h`

### Mention any other details that might be useful.
It would be super helpful to have this list the availalble blueprints

**Comment by ocombe** [comment]
While you're on it, I think that there should be a help command for `ng g`, right now it throws an error 
 ```ng g -h
Invalid blueprint: -h
```

but `ng g component -h` works (and prints the help for all blueprints, not just component)
