### ISSUE TITLE
Enhancement: ng g guard has no alias g

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#5336]
### OS?
Mac OSX Sierra 10.12.3

### Versions.
@angular/cli: 1.0.0-rc.1
node: 6.9.1
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

### Repro steps.
`ng g g foo`

### The log given by the failure.
`Invalid blueprint: g`

### Mention any other details that might be useful.
When we run `ng g guard foo` it works. I believe guard should have an alias of `g`

**Comment by yeganehaym** [comment]
angular-cli: 1.0.0-beta.28.3
node: 6.9.5
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10

when i enter the command
`ng g guard Authenticate`
i encounter to this message:
`Invalid blueprint: guard`
