### ISSUE TITLE
i am looking for documentation about how to open/view/export the code coverage report,is there any?

### ISSUE THREAD

**Issue by stefanaerts** [angular/angular-cli#5341]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
I would like to find some doc about how to view the code coverage report generated by angular-cli, i run  "coverage": "lite-server -c bs-config.json"
 ,but is that the preferred way to do it? How can we export it to travis and watch it on some coverage reporting site(i read about coveralls, but is that what you recommend and how to do this)? Is there documentation? Thanks 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by stefanaerts** [comment]
so in the mean time i see you use karma-coverage-istanbul-reporter,
1) what does this mean coverageIstanbulReporter: {
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true

2) i see there is a file lcov.info generated in coverage folder, is there documentation on how to use this file(s) in the coverage folder to export in travis to a public website like Coveralls for example?

3) i noticed i had to add  'kjhtml' at the end of the first array to have the test report work together with the codecoverage report. ng test -cc wil not show the test results without this extra param.

reporters: config.angularCli && config.angularCli.codeCoverage
      ? ['progress', 'coverage-istanbul', 'kjhtml']
      : ['progress', 'kjhtml'],

**Comment by filipesilva** [comment]
Heya @stefanaerts, we don't have any CLI specific documentation on how to use the generated code coverage. Instead, we mostly make sure the karma reporter can work.

How I do it is run `ng test --code-coverage`, and directly double click `./coverage/index.html`. That is enough to see the html report.

The `lvoc.info` file is a common format that a lot of tools can read and generate reports from. I can't say I have a lot of experience with it though. 

The original `lcov` tool is http://ltp.sourceforge.net/coverage/lcov.php, but you can also find a lot of lcov parsers in the NPM ecosystem: https://www.npmjs.com/browse/keyword/lcov

I tried a couple and the easiest one I found was https://www.npmjs.com/package/lcov-summary.

Also flagging this issue for community help to see if someone more knowledgeable can give better insight.

**Comment by stefanaerts** [comment]
when i enabled my public repo on coveralls and run
cat ./coverage/lcov.info | coveralls 
i get this error -> Couldn't find a repository matching this job

**Comment by filipesilva** [comment]
Can't help you there, I don't know anything about coveralls.

**Comment by stefanaerts** [comment]
i just want to have it in travis running and published somewhere online,
for me its also new. I read about coveralls.

**Comment by filipesilva** [comment]
If I get this right, you can get a coveralls badge in github via their integration: https://github.com/integrations/coveralls

You'll have to read how to configure it though.

**Comment by stefanaerts** [comment]
i did,but not working.
i have enabled my github project and a badge is added to my readme.md from coveralls.
but i am trying to run it local on my laptop running node and npm.
coveralls -f ./coverage/lcov.info  keeps hanging
cat ./coverage/lcov.info | coveralls  gives the error message
I didn't run it on travis yet.

**Comment by filipesilva** [comment]
I'm sorry @stefanaerts, but I can't help you with that tool more than this. I don't have time to go learn how to use it right now.

**Comment by stefanaerts** [comment]
i understand @filipesilva ,thanks for your time and help.
I will figure it out.

**Comment by stefanaerts** [comment]
In the mean time i run it on travis and it works!
So the most important thing is that it works in the whole process with travis.
I run 
after_success:
  - npm run coveralls
Then i have results on coveralls and a badge in my readme.md in github
![image](https://cloud.githubusercontent.com/assets/3684599/23867789/5f6aedbc-081d-11e7-8e6f-97d5d766295a.png)
![image](https://cloud.githubusercontent.com/assets/3684599/23867818/7285fc16-081d-11e7-9050-90edd7303655.png)



if i want to a codecoverage report view local in a browser i can just open it local with 
lite-server -c bs-config.json
"server": {
    "baseDir": "./coverage"
  }

![image](https://cloud.githubusercontent.com/assets/3684599/23867851/8b1a3c38-081d-11e7-8ba4-9658d1f8a29d.png)

or use the command line tool like you mentioned:
$(npm bin)/lcov-summary ./coverage/lcov.info
![image](https://cloud.githubusercontent.com/assets/3684599/23867911/c194e344-081d-11e7-82b6-71fb29eb5137.png)

**Comment by filipesilva** [comment]
Hey I'm really glad you got it working, and thanks for coming back to document what you did! Now other people that have the same problem can follow your steps.

Cheers!
