### ISSUE TITLE
Bug: ng set defaults.component doesn't work for any properties of type string

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#5345]
### OS?
Mac  OSX Sierra 10.12.3

### Versions.
@angular/cli: 1.0.0-rc.1
node: 6.9.1
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

### Repro steps.
this works `ng set defaults.component.flat true`

but this does not work `ng set defaults.component.viewEncapsulation Emulated`

seems it works with the component defaults that are booleans. but not the domain ones, like `changeDetection` and `viewEncapsulation`

I would expect that these values should be able to be set, since they are in the schema file https://github.com/angular/angular-cli/blob/1f8363a95a19ab70bd99769aed904983d8878bfa/packages/%40angular/cli/lib/config/schema.json#L338-L344

**Comment by sumitarora** [comment]
@johnpapa adding string types to enum fixes the value created PR 😄

**Comment by johnpapa** [comment]
wow, that simple? cool!
