### ISSUE TITLE
tsconfig.app.json types are ignored

### ISSUE THREAD

**Issue by coryrylan** [angular/angular-cli#5351]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10 x64

### Versions.
@angular/cli: 1.0.0-rc.1
node: 6.9.1
os: win32 x64

### Repro steps.
Update package.json from `@angular/cli": "1.0.0-rc.0` to `@angular/cli": "1.0.0-rc.1`. 

### The log given by the failure.
`Cannot find name 'require'`
`Cannot find namespace 'ol'`
`Cannot find name 'describe'`
`Cannot find name 'beforeEach'`
`Cannot find name 'it'`
`Cannot find name 'expect'`

### Mention any other details that might be useful.
When using certain 3rd party libraries or `require()`  you need to add the types to the `tsconfig.app.json` as described here https://github.com/angular/angular-cli/wiki/stories-third-party-lib. In the latest RC1 it looks like the `types` option is ignored resulting the above error.  If I remove the `types` entry and replace it with the global `typeRoots` entry it seems to work but is not ideal to pull in all types.  This also affects the `tsconfig.spec.json`.

## Breaks in RC1, used to work in RC0
```
{
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "outDir": "../out-tsc/app",
    "target": "es5",
    "module": "es2015",
    "baseUrl": "",
    "types": [
      "node",
      "openlayers"
    ]
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

## Work around for RC1
```
{
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "outDir": "../out-tsc/app",
    "target": "es5",
    "module": "es2015",
    "baseUrl": "",
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

**Comment by GustavoMantuan** [comment]
Thank you so much, Its helped me a lot.

**Comment by zurie** [comment]
this helped me, would be nice to know a official workaround is in place or if i need to just memorize this as a 'gotcha' fix

**Comment by filipesilva** [comment]
There has to be something else going on here. I know for a fact that `ng test` worked in all RCs and it relies on having the jasmine types.

I also just tried the https://github.com/angular/angular-cli/wiki/stories-third-party-lib example and it worked.

Have you tried clearing your local node_modules? Maybe there's something wrong in there.

I can't reproduce this myself. If you can provide a repo where this happens I can investigate.

**Comment by coryrylan** [comment]
Yeah this has persisted since rc1 after clearing nodemodules. Going to update the project to the latest RC Monday and will report back

**Comment by filipesilva** [comment]
Actually, I was investigating https://github.com/angular/angular-cli/issues/5332 and it seems they are related.

The reason `ng test` works and has it's typings seems to be due to a weird (and erroneous) compilation setup. 

That error was seems to be masking this one.

**Comment by filipesilva** [comment]
Further investigation reveals this is a windows specific problem. A fix is on the way.
