### ISSUE TITLE
ERROR in vendor... from UglifyJs Unexpected character '`'

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#5352]
When I build or serve using --prod I get: 
```
ERROR in vendor.8ebdc3713b6c81a2665a.bundle.js from UglifyJs
Unexpected character '`' [vendor.8ebdc3713b6c81a2665a.bundle.js:70273,25]
```

I don't have this without aot, what a mess!

### Config:
_@angular/cli: 1.0.0-rc.1
node: 6.9.2
os: win32 x64
@angular/common: 4.0.0-rc.2
@angular/compiler: 4.0.0-rc.2
@angular/core: 4.0.0-rc.2
@angular/forms: 4.0.0-rc.2
@angular/http: 4.0.0-rc.2
@angular/platform-browser: 4.0.0-rc.2
@angular/platform-browser-dynamic: 4.0.0-rc.2
@angular/router: 4.0.0-rc.2
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 4.0.0-rc.2_

**Comment by hansl** [comment]
Did you change your tsconfig to output ES6? UglifyJS isn't compatible with ES6.

**Comment by istiti** [comment]
you mean target? here's my tsconfig.app.json
```
{
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "outDir": "../out-tsc/app",
    "target": "es5",
    "module": "es2015",
    "baseUrl": "",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

**Comment by istiti** [comment]
cc @hansl
