### ISSUE TITLE
Does angular-cli compress/optimize the assets content such as images?

### ISSUE THREAD

**Issue by johnqiuwan** [angular/angular-cli#5356]
Hi Guys,

  I am wondering if the angualr-cli will compress/optimize the assets contents such as images when we run 'ng build --prod'  or 'ng serve --prod'

Thank you

**Comment by filipesilva** [comment]
No, images are not compressed.

**Comment by glebmachine** [comment]
How do i able to add compression loader, without webpack config extraction?
That will be awesome
