### ISSUE TITLE
ng build --aot completes without error - Build does not work

### ISSUE THREAD

**Issue by EmersonGGS** [angular/angular-cli#5357]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.28.3
node: 7.3.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/compiler-cli: 2.4.9

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Application was created with the CLI

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

Once the application is created and packages are installed, i run `ng build --aot` and the dist is created as expected. Once the dist/index.html is opened, the log  has 404 errors for the compiled files:

inline.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
polyfills.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
styles.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
main.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
main.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattdistefano** [comment]
Do those files exist in your dist folder? How are you serving the app after build?

**Comment by istiti** [comment]
@EmersonGGS  i dont' understand dude you have ng 2.4.9 and cli 28
how can you stay at 28 ? what is your reason?
can't you simply update to rc1 and check if problem's again here

**Comment by devkonyan** [comment]
I also facing the same issue with @EmersonGGS, Without error while ng build in new project, dist folder is created and all of the js files/assets are located. but browsing index.html fail to load all of js resources.

ng --version

@angular/cli: 1.0.0-rc.1
node: 6.10.0
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

**Comment by istiti** [comment]
I think it's normal behavior, can you check in html file  if your base tag is correct
`<base href="....">`

@EmersonGGS  @devkonyan

**Comment by EmersonGGS** [comment]
@istiti I updated my ng to RC, created a new application using the new version, ran the AOT build and had the same issue as before. Then I changed the the base href and it seems to be working as expected, thanks!

**Comment by devkonyan** [comment]
Phewww .. Angular 2 updates are too dramatically changes.
thank @istiti , You make my  day.
