### ISSUE TITLE
Can't polyfill imported scripts

### ISSUE THREAD

**Issue by Simon-Briggs** [angular/angular-cli#5358]
### OS?
Mac OSX El Capitan

### Versions.
@angular/cli: 1.0.0-rc.1
node: 6.9.5
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/compiler-cli: 2.4.9
@angular/cli: 1.0.0-rc.1

### Repro steps.
I cannot load a  third party library in the scripts tag of angular cli, if that library requires an ES6 polyfill:

      "scripts": [
        "../node_modules/zooming/build/zooming.js"
      ],

In polyfills.ts I have:

    import 'core-js/es6/map';

### The log given by the failure.
During my test I get the following error:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: Map
  at node_modules/zooming/build/zooming.js:306
```

### Mention any other details that might be useful.

Are the polyfills applied only after importing third party scripts? I'm not sure how to debug from here. Even if I delete all uses of this library, as long as it is in my angular-cli scripts tag, phantomJS cannot load my project.

**Comment by mattdistefano** [comment]
See https://www.npmjs.com/package/zooming#option-2-module-loader

**Comment by Simon-Briggs** [comment]
Ah whups, I don't know I was so adamant this library needed to be in the angular-cli scripts tag...thanks!

But for reference I can't use ES6 features in files imported via the angular-cli scripts tag then?
