### ISSUE TITLE
Global deps: broccoli-plugin and broccoli-source?

### ISSUE THREAD

**Issue by cebor** [angular/angular-cli#536]
Why does angular-cli install `broccoli-plugin` and `broccoli-plugin` globally?

Is this really needed, i like to have my global deps clean :)

**Comment by cebor** [comment]
Ok, its releated to: https://github.com/broccolijs/broccoli/issues/302

**Comment by filipesilva** [comment]
Yeah, there isn't much we can do about it from this side.

**Comment by cebor** [comment]
its fixed now in the latest broccoli release: https://github.com/angular/angular-cli/pull/553
