### ISSUE TITLE
Angular2 Installation

### ISSUE THREAD

**Issue by maniJoe** [angular/angular-cli#5361]
npm -v 
4.1.2
node -v
v7.7.2

I have installed angular-CLI using this command

npm install -g @angular/cli 

after installation i used this command

ng -v
![screenshot from 2017-03-10 11-45-35](https://cloud.githubusercontent.com/assets/22447754/23784395/c5060816-0587-11e7-9d04-59ca97666408.png)

Please resolve this if anyone is willing

**Comment by psks1204** [comment]
https://youtu.be/Mu6btqWZszg

try this hope it helps you!

**Comment by filipesilva** [comment]
@maniJoe you might have another binary by the name of `ng`. What's the output of `which ng`?


@psks1204 the issue tracker is meant to track issues and solutions, not to publicize youtube videos. Please stop posting your video on unrelated issues.

**Comment by maniJoe** [comment]
@filipesilva 
$:which ng
/usr/bin/ng

**Comment by filipesilva** [comment]
Yeah I don't know what that `ng` is, but it doesn't look like the global Angular CLI `ng`, which should be in some node_modules. If you rename or get rid of that one you should be fine... although something in your machine might require it. Proceed at your own peril.

**Comment by maniJoe** [comment]
@filipesilva 
When i type ng in linux i get this screen.
i am unable to do anything

![ng](https://cloud.githubusercontent.com/assets/22447754/24236360/8cf015c6-0fc7-11e7-9c66-9bba633340f0.png)

**Comment by filipesilva** [comment]
@maniJoe you have a binary called `ng` that is not Angular CLI, and when you run `ng` that's what runs instead. I don't know what it is, nor do I use Ubuntu in general, so I can't help you much there.
