### ISSUE TITLE
use `html-loader` instead of `raw-loader` for html files

### ISSUE THREAD

**Issue by indooorsman** [angular/angular-cli#5363]
use `html-loader` instead of `raw-loader` for html files, so assets referenced in html files can be handled by file-loader correctly

**Comment by filipesilva** [comment]
We tried that a couple of times and overall we considered it unsafe. Willing to try again though.

**Comment by mkoczorowski** [comment]
+1
html-loader supports requiring html inside of html files. Feature very useful if we have a large template. If we are allowed to require html in other html files we should be able to break the large template down into smaller, maintainable files.

**Comment by kylecordes** [comment]
@mkoczorowski  Is it a really good practice though, to have a giant template so big that you need to break into multiple files? When my templates get too big, I decompose components so that each has a tolerable size template.

**Comment by mkoczorowski** [comment]
@kylecordes Thanks for replying. I tend to do the same... However, there may be a use case for this. I had to embed a lot of plain html in the page some time ago, without any selectors or logic, just plain html. Creating a @Component just to populate templateUrl with plain html it's a bit overkill in my opinion. Why do I need to addon javascript, increase bundle size to just to inject some plain html ? The above option will at least would give you the flexibility. It's always up to the developer what to decide should / should not this be used in a particular instance.

**Comment by filipesilva** [comment]
Consolidating discussion in https://github.com/angular/angular-cli/issues/3415
