### ISSUE TITLE
@ngtools/webpack provides invalid design:type metadata for enum properties

### ISSUE THREAD

**Issue by kkovalevskiy** [angular/angular-cli#5367]
Hi!
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 8.1

### Versions.
>  node --version v6.9.4
> @ngtools/webpack 1.12.1

### Repro steps.
I have 2 files: `MyEnum.ts` which looks like
```
export enum MyEnum {
    Zero = 0,
    One = 1,
    Two = 2
}
```

and other file which uses this enum as a property type with decorator smth like this.
`MyClass.ts`
```
import {MyEnum} from "./MyEnum";

export class MyClass {
        @myDecorator()
        myProperty:MyEnum;
}
```

@ngtools/webpack provides the following output for this case
```
// output looks smth like this.
...
tslib_1.__decorate([
    XXX.myDecorator(),
    tslib_1.__metadata("design:type", typeof (_a = typeof YYY.MyEnum !== "undefined" && YYY.MyEnum) === "function" && _a || Object)
], MyClass.prototype, "myProperty", void 0);
...
```

while typescript compiler provides the following one
```
....
tslib_1.__decorate([
    XXX.myDecorator(),
    tslib_1.__metadata("design:type", Number)
], MyClass.prototype, "myProperty", void 0);
....
```
So, it looks like enum cannot be recognized by typescript compiler and it falls back to Object type. This can be due to CompilerHost implementation (tsc recognizes enums very well).

**Comment by kkovalevskiy** [comment]
Looks like the same issue if I use `Array<string>` instead of `string[]`

**Comment by clydin** [comment]
This should be corrected in the latest version of the CLI (currently 6.0.8).  If you are still encountering this problem after upgrading, please open a new issue with updated information.  Thank you.
