### ISSUE TITLE
Compiler throws TS2354 when returning multiple objects

### ISSUE THREAD

**Issue by alvaro9210** [angular/angular-cli#5371]
### OS?
MacOS 10.12.2

### Versions.
node v.6.9.0

### Repro steps.
1.  Have an Angular2 app with Webpack
2. Implement the @ngtools/webpack AOTPlugin.
3. Make sure to have an @Directive returning multiple different types, like this one:
```typescript
@Directive( {
    selector: "[cp-uri-fragment]",
    providers: [ { provide: NG_VALIDATORS, useExisting: URIFragmentValidator, multi: true } ]
} )
export class URIFragmentValidator implements Validator {
    validate( control:AbstractControl ):{ [key:string]:any; }|null {
        if( ! control.value ) return null;
        if( ! control.value.match( /^(ftp|https?):\/\/(\w+:{0,1}\w*@)?((?![^\/]+\/(?:ftp|https?):)\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?$/ ) ) return { "invalidURIAddress": true };
        if( ! URI.Util.hasFragment( control.value ) ) return null;
        if( URI.Util.getFragment( control.value ).trim().length === 0 ) return { "missingFragment": true };

        return null;
    }
}
```
4. Bundle your project

### The log given by the failure.
```
[at-loader] Checking finished with 51 errors
Error in bail mode: [at-loader] ./node_modules/carbonldp-panel/directives/custom-validators.ts:63:47 
    TS2354: No best common type exists among return expressions.
```

### Mention any other details that might be useful.

This is the part of code that causes the error. Notice how the line 63 (the one that the compiler complains about) is actually empty! So the compiler is not identifying correctly the conflicting lines.
![screen shot 2017-03-10 at 11 19 36 am](https://cloud.githubusercontent.com/assets/4240006/23806157/37e2e130-0586-11e7-8057-189aa52e1948.png)

And also, when I return the following, the compiler continues compilation (return the same object):
```typescript
@Directive( {
	selector: "[cp-uri-fragment]",
	providers: [ { provide: NG_VALIDATORS, useExisting: URIFragmentValidator, multi: true } ]
} )
export class URIFragmentValidator implements Validator {

    validate( control:AbstractControl ):{ [key:string]:any; }|null {
        if( ! control.value ) return null;
        if( ! control.value.match( /^(ftp|https?):\/\/(\w+:{0,1}\w*@)?((?![^\/]+\/(?:ftp|https?):)\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?$/ ) ) return { "invalidURIAddress": true };
        if( ! URI.Util.hasFragment( control.value ) ) return null;

        v—— Causes ERROR TS2354
        // if( URI.Util.getFragment( control.value ).trim().length === 0 ) return { "missingFragment": true };   
        v—— Continues compilation OK.
        // if( URI.Util.getFragment( control.value ).trim().length === 0 ) return { "invalidURIAddress": true };

        return null;
    }
}
```

**Comment by clydin** [comment]
That's a typescript error coming from the awesome typescript loader.   Doesn't seem like an angular CLI issue.
Also, the AOT plugin is meant to be used with its accompanying loader.  Unless you have specific webpack configuration requirements, I'd recommend using the CLI proper if possible.

**Comment by hansl** [comment]
Like @clydin said, you seem to be using 2 loaders for typescript: the `@ngtools/webpack` one and the `at-loader`. You don't need the `at-loader`, since the `@ngtools/webpack` loader will also transpile typescript.

**Comment by alvaro9210** [comment]
Yes, that was it.
