### ISSUE TITLE
Bundle only application files and import other modules

### ISSUE THREAD

**Issue by pauldaustin** [angular/angular-cli#5375]
### OS?
Mac OSX El Capitan?

### Versions.
@angular/cli: 1.0.0-rc.1 (e)
node: 7.7.1
os: darwin x64
@angular/common: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler: 2.4.9
@angular/compiler-cli: 2.4.9
@angular/platform-server: 2.4.9

### Repro steps.
Created using Angular cli

### The log given by the failure.
N/A

### Mention any other details that might be useful.

Would it be possible to add an option to bundle only the source files and resources for the current application's source tree. Any other modules would be included at runtime from a CDN.

Bundling applications typically result in 1MB size js bundles. When loading from some remote servers those files are not fully downloaded in browsers and the application fails.

By using a CDN for common files those mail already be in the browser cache so wouldn't need to be reloaded as often and as slowly.

I've tried about 20 different options of manually doing this with webpack and none of them seem to work correctly.

**Comment by filipesilva** [comment]
We don't have this functionality in the CLI, no. It's not something we're planning to add either. It doesn't work too well with tree shaking and that kind of optimization.

If you absolutely need it, I'd recommend using a SystemJS based solution.
