### ISSUE TITLE
build with aot - provideLocationStrategy error

### ISSUE THREAD

**Issue by TheILPlace** [angular/angular-cli#5382]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
win10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli v rc1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

i've created an interface

import {ModuleWithProviders} from '@angular/core';

export interface IRouting {
    routes: ModuleWithProviders,
    components: any[]
};

i use that interface when declaring my routing class

import { Routes, RouterModule } from '@angular/router';
import { IRouting } from './shared/interfaces/IRouting';

import { HomeComponent } from './home.component';

const routes: Routes = [
  
  { path: 'home', component: HomeComponent }
  
];

export const appRouting: IRouting = { 
    routes: RouterModule.forRoot(routes),
    components: [ HomeComponent ]
};

and in my app.module, i import the appRouting const in two places

import { appRouting } from './app.routing';

@NgModule({
  declarations: [
    AppComponent,
    appRouting.components
  ],
  imports: [
    BrowserModule,
    appRouting.routes
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

----
ng serve works .
ng build, does not

ERROR in Can't resolve all parameters for provideLocationStrategy in C:/path/to/project/node_modules/@angular/router/src/router_module.d.ts: ([object Object], ?, [object Object]).

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\path\to\project\src'
@ ./src/main.ts 6:0-74
@ multi ./src/main.ts

why i use the interface above ?
because , as i import the components to be used in the routing, i can put them in an array, 
and importing the components in the app.module via the interface, saves me from importing them again, and then declaring them.
so i use
appRouting.components  in the declaration part
and 
appRouting.routes in the imports part

anyway, building with AOT doesnt work
if i do: ng build --aot false    then it works.
if i remove the interface, export the router module and import the router module+components in the app.module - then things work with AOT

another insight- if i use the interface only in a lazy loaded module, it seems to not complain during compile, and also during runtime even with AOT

**Comment by filipesilva** [comment]
If I remember correctly, AOT does not support that usage. Please open an issue in https://github.com/angular/angular if you belief this should be supported.
