### ISSUE TITLE
docs: make the flags consistent

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#5386]
https://github.com/angular/angular-cli/blob/master/docs/documentation/build.md

The snippet below from the above link shows `--env` and `--e` but then lter in the doc the alias is shown as `-e`. We should be consistent

Here it is defined as `-e` ... https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/commands/build.ts#L21-L24

```
# these are equivalent
ng build --target=production --environment=prod
ng build --prod --env=prod
ng build --prod
# and so are these
ng build --target=development --environment=dev
ng build --dev --e=dev
ng build --dev
ng build
```

**Comment by Brocco** [comment]
This has been covered in a separate PR.
