### ISSUE TITLE
Build --extract-css does not do anything

### ISSUE THREAD

**Issue by xe4me** [angular/angular-cli#5390]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac OSX Siera

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-rc.1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Created a new cli project , added some css to one of my components, expected the ``` --extract-css ``` to extract to css into one file as per the documentation says, but the css is still is inside the js file when looking at the dist folder.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
The extraction option applies to global styles.  Global styles are the stylesheets referenced in the styles field within the project's angular-cli config file.

**Comment by xe4me** [comment]
@clydin, alright , didn't know that.
I'd be better to add that to the documentation.
I would've thought that would extract the inline css, that would be cooler :)
The global styles are already extracted, no point in putting it and then extracting it for me.

**Comment by filipesilva** [comment]
Closing as answered by @clydin, thanks!
