### ISSUE TITLE
template bindings={ "ng-reflect-ng-for-of": null } " even i have data.

### ISSUE THREAD

**Issue by praveenkumarS7** [angular/angular-cli#5397]
when i'm using http response array in template, it doesn't show anything. in template i got this error like  "template bindings={ "ng-reflect-ng-for-of": null } ".If i'm using custom defined array ,there is no problem.
 But i can see all the response in console in an array format. Is there any option to view these data in view?

**Comment by deebloo** [comment]
@praveenkumarS7 this isn't a CLI issue. Make sure you are correctly assigning the result of the http request to a component property.

**Comment by filipesilva** [comment]
Closing because this is not a CLI issue like @deebloo said.

**Comment by rahulc21** [comment]
It is because you are using something extra such as router-template
