### ISSUE TITLE
You have to be inside an ember-cli project in order to use the serve command.

### ISSUE THREAD

**Issue by stojankukrika** [angular/angular-cli#5398]
Hi,
I have windows 10 and install angular cli, when I run:
ng --version
angular-cli: 1.0.0-beta.24
node: 7.6.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

and when I run:
ng help
ember build <options...>
  Builds your app and places it into the output path (dist/ by default).
  aliases: b
  --target (String) (Default: development)
    aliases: -t <value>, -dev (--target=development), -prod (--target=production)
  --environment (String) (Default: )
    aliases: -e <value>
  --output-path (Path) (Default: null)
    aliases: -o <value>
  --watch (Boolean) (Default: false)
    aliases: -w
  --watcher (String)
  --suppress-sizes (Boolean) (Default: false)
  --base-href (String) (Default: null)
    aliases: -bh <value>
  --aot (Boolean) (Default: false)
  --sourcemap (Boolean) (Default: true)
    aliases: -sm
  --vendor-chunk (Boolean) (Default: true)
  --verbose (Boolean) (Default: false)
  --progress (Boolean) (Default: true)
  --i18n-file (String) (Default: null)
  --i18n-format (String) (Default: null)
  --locale (String) (Default: null)

ember completion
  Adds autocomplete functionality to `ng` commands and subcommands

ember doc <keyword>
  Opens the official Angular documentation for a given keyword.

ember e2e
  Run e2e tests in existing project

ember generate <blueprint> <options...>
.....

can you help how to solve this?

**Comment by Equinox** [comment]
You should update your Angular cli version, latest being 1.0.0-rc.1

`npm uninstall -g @angular/cli`
`npm cache clean`
`npm install -g @angular/cli@latest`

**Comment by stojankukrika** [comment]
Hm, I list them in package.json  "@angular/cli": "^1.0.0-rc.1" . But it's works now. TNX.

Do you use ember cli or something that is the reason why I get that error before this steps?

**Comment by Equinox** [comment]
Yeah, Angular CLI is based on Ember CLI (there was an issue a while ago where the commands referenced Ember CLI's context instead of the Angular CLI ones -- that's why the update definitely was the way to fix it)

**Comment by stojankukrika** [comment]
Aha.Tnx for information and have a nice work!It's nice to have tool like this in angular also.Tnx
