### ISSUE TITLE
Typings files not picked up

### ISSUE THREAD

**Issue by scottwio** [angular/angular-cli#54]
If you build a new project from scratch the *.d.ts files in node_modules/angular2/ are not picked up in visual studio code or sublime text with the typescript plugin.

**Comment by doczoidberg** [comment]
I have the same problems. There seems to be something broken with the folder structures.

In the IDEs I need other folder paths than the ts compiler needs.

**Comment by IgorMinar** [comment]
this sounds weird. have you customized tsconfig.json? I intentionally set things up to make this particular scenario work out of the box.

**Comment by doczoidberg** [comment]
I didn't customize tsconfig.json

**Comment by scottwio** [comment]
This is working for me now just made a new project and opened it in vs code and everything is good. Not sure if it was a editor problem or angular-cli problem but whatever it was seems to have been fixed for me. I hadn't customised tsconfig.json

**Comment by doczoidberg** [comment]
where are your .d.ts files stored? do you use them with reference ?
