### ISSUE TITLE
Static JS assets not copying

### ISSUE THREAD

**Issue by raghunat** [angular/angular-cli#540]
Hello Angular-Cli Folks!

I am having trouble getting static JS files (like jquery components for a static page) to copy over the dist folder in version 0.0.34.

Placing the JS folder in the client, or app/assets does nothing, and they are just skipped. Other non JS files are not however in these areas.

Let me know what is the right approach to have static JS files.

**Comment by jkuri** [comment]
Hi @raghunat. Everything from the `public/` directory gets copied as is to the `dist/`.

**Comment by JonGaribay** [comment]
I'm not finding this to be the case when the -prod flag is used.  It seems like whenever a production build is done, js files inside of public are not included.

**Comment by BenevidesLecontes** [comment]
@JonGaribay I'm having this issue too. I'm using bower files on public folder, but js files are not included on dist folder when use ng serve -prod, only the .map are included

**Comment by raghunat** [comment]
@jkuri this is still happening. Public JS files are not copied when using the -prod flag

**Comment by briananderson1222** [comment]
Not sure this is exactly the same but I load an HttpInterceptor from the main.ts that doesn't seem to be getting copied when using the build for production environments.

// main.ts
`import {HttpInterceptor} from './app/shared/http/http.interceptor';`

Everything builds fine but when loading the web page I get:
`zone.js:101 GET http://localhost:4200/app/shared/http/http.interceptor.js 404 (Not Found)`

I have tried commenting out this line an am now noticing issues with other files not getting included.. So I would guess this is not specific to the main.ts module imports. 

For example after commenting the interceptor out.. I now see issues with my app.components css file not getting included. Just as a heads up here, we are using sass which works perfectly in the development environment but I guess not in the production environment (not sure it is specific to the scss conversion so just thought i'd include this..)

**Comment by fadeojo** [comment]
@jkuri I am also seeing this. The javascript files in my public folder are not getting copied over.

**Comment by steveblue** [comment]
@jkuri this issue should be reopened. I can replicate on latest master with ---prod flag set, nothing in the vendor folder is getting copied to dist.

**Comment by filipesilva** [comment]
I added in https://github.com/angular/angular-cli/pull/1129 that should address this issue. If it's accepted, it should be in the next beta.

**Comment by oxeno** [comment]
We are having the same problem. Any idea when this will be fixed?

**Comment by Splaktar** [comment]
I agree. This seems like an obvious fix and there have been no comments in the PR about there being a problem. Why has this sat for almost a month without getting merged? It missed beta.9.
