### ISSUE TITLE
styles problem

### ISSUE THREAD

**Issue by ileler** [angular/angular-cli#5401]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
```
$ ng -v
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0-rc.0
node: 6.10.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8
```

### Repro steps.
.angular-cli.json
```json
"styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css"
      ],
```
build/start not errors, but page none style...

index.html
```html
<link rel="stylesheet" href="./node_modules/bootstrap/dist/css/bootstrap.min.css" />
```
Only in this way can the normal display style...why????

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I cannot reproduce this. 

I install bootstrap via `npm install bootstrap.

Add it to the styles array:
```
      "styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css"
      ],
```

And change `app.component.html` to have a bootstrap class:
```
<h1 class="text-danger">
  {{title}}
</h1>
```

I can see the effect of that class in the html:

![image](https://cloud.githubusercontent.com/assets/4172079/24072036/6f29dd36-0bd7-11e7-9143-140b6f9ecb0e.png)

If you upload a repository where you see a different result, I can take a look.

**Comment by Makeon** [comment]
It depends of angular-cli version.
In beta version it works.
even 
"styles": [
        "styles.css",
        "styles1.scss"
      ], works
in last version it not works
Hope, this bug will excluded in the next version.

**Comment by herohoner** [comment]
```
$ ng -v
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.9.4
os: win32 x64

```

# as this bug ,  page none style,only ``index.html`` inline the style file

**Comment by filipesilva** [comment]
Closing as inactive, original reporter never got back to the issue.
