### ISSUE TITLE
[Feature Request] outDir for environments

### ISSUE THREAD

**Issue by farkaspeter** [angular/angular-cli#5403]
It would be nice if I could set different outDir-s for the different environments in .angular-cli.json. I know I can set the --output-path for the build command, but since I (almost) always use the same output directory for a given environment, it would be nice to store in a config file.

**Comment by BustyLoli-Chan** [comment]
Any word on this? It looks semi dead in the water from a person who is now almost a year in the future.

**Comment by ArtemLyssenko** [comment]
This is the answer https://stackoverflow.com/questions/51079442/angular-cli-different-paths-for-develop-and-publish-output
In my case, it was a bit different `ng build --output-path RELEASEPATH --configuration prod`

**Comment by filipesilva** [comment]
Using configurations in `angular.json` this is possible now.

**Comment by jlberrocal** [comment]
@filipesilva if is possible can you please provide an working example on how to achieve it??? i mean it will be very helpful since you closed the issue

**Comment by skeemer** [comment]
I got this working by setting "outputPath": to the one I wanted for dev and then added an "outputPath" setting to the configurations.production section.
