### ISSUE TITLE
Bug: `ng eject --prod` fails for project with static assets

### ISSUE THREAD

**Issue by alxhub** [angular/angular-cli#5409]
The `StaticAssetPlugin` is not imported properly in the webpack config when ejecting from a CLI project that uses it.

`ng eject` in angular/angular's aio/ for example fails to produce a webpack config that will build.

**Comment by clydin** [comment]
@alxhub is this still needed? The plugin appears to only be needed for the legacy service worker.

**Comment by hansl** [comment]
Closing this as obsolete.
