### ISSUE TITLE
Feature: ng generate should use configurable quotmarks

### ISSUE THREAD

**Issue by NCC1701M** [angular/angular-cli#5413]
@angular/cli: 1.0.0-beta.32.3
node: 6.10.0
os: win32 x64

When generating components, modules, etc. with ng generate all quotemarks are ' but we use " so it would be great when ng generate would use those quotemarks as well. This should be configurable via angular-cli.json. It is not workable to use`ng lint --fix` every time you used ng generate.

**Comment by filipesilva** [comment]
This is being considered for 2.0 using a new blueprint system that would allow for that sort of configuration. The current one does not.

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/6213.
