### ISSUE TITLE
issue with installation

### ISSUE THREAD

**Issue by miha-** [angular/angular-cli#5414]
Helllo

I am having hard time to install angular-cli.

What could be the issue?

tnx

Windows 10

nodejs: v6.5.0

Logs: http://pastebin.com/BAbr2REA

**Comment by gelidus** [comment]
Looks like you are using old version of node. angular-cli required Node >= 6.9.0 [here](https://github.com/angular/angular-cli/blob/master/package.json#L34)

**Comment by filipesilva** [comment]
Closing as answered by @gelidus, thanks!
