### ISSUE TITLE
Node modules are not getting downloaded

### ISSUE THREAD

**Issue by mailtoab** [angular/angular-cli#5415]
### ng --version
                   angular-cli: 1.0.0-beta.28.3
                   node: 6.10.0
                   os: win32 x64

### node --version
                   v6.10.0

### I have installed angular2 IDE in eclipse. Node modules are not getting downloaded. It is showing the following error and hanging for long time.

npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json

### The log given by the failure.
> Normally this include a stack trace and some more information.
npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json

Please help.

**Comment by filipesilva** [comment]
You seem to be using an old CLI version. Please use `@angular/cli` instead.
