### ISSUE TITLE
Why in folder dist (-prod) has gzip files as well as not gzip files?

### ISSUE THREAD

**Issue by marciomsm** [angular/angular-cli#5418]
Why in folder dist (-prod) has gzip files as well as not gzip files? I didn't find this information on angular-cli documentation.

Is there a way to not generate gzip files?

Thanks.

**Comment by Meligy** [comment]
The latest versions of the CLI don't output these anymore.

ensure you have the latest version of the package named `@angular/cli`.

**Comment by filipesilva** [comment]
Closing as answered by @Meligy, thanks!
