### ISSUE TITLE
Unable to generate a component under a specified module

### ISSUE THREAD

**Issue by JayQuellin** [angular/angular-cli#5421]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
@angular/cli: 1.0.0-rc.2
node: 6.9.5
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9

### Repro steps.
`ng g m bar`
`ng g c foo -m bar`

### The log given by the failure.

```
installing component
  create src\app\foo\foo.component.scss
  create src\app\foo\foo.component.html
  create src\app\foo\foo.component.spec.ts
  create src\app\foo\foo.component.ts
EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at Class.afterInstall (C:\app\node_modules\@angular\cli\blueprints\component\index.js:209:34)
    at tryCatch (C:\app\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\app\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (C:\app\node_modules\rsvp\dist\rsvp.js:522:7)
    at flush (C:\app\node_modules\rsvp\dist\rsvp.js:2374:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```
The generated component is not under the specified module either.

### Desired functionality.
Ideally this would generate a new component under the specified module and corresponding directory.

**Comment by delasteve** [comment]
Doing `ng g c bar/foo -m bar/bar.module` will get you your desired behavior.

**Comment by dandax** [comment]
Perhaps a better error message would do the trick for anyone else that runs into this issue.

**Comment by architruc** [comment]
After reading the [documentation](https://github.com/angular/angular-cli/wiki/generate-component), I also understood it exactly the same way as @JayQuellin, expecting the component to be placed in the module folder automatically. Thus googled the error message and found this topic. If the CLI is not expected to be used this way, an example / details on the doc would be appreciated :smiley: (and/or as @dandax suggested, clarify the error).

**Comment by delasteve** [comment]
@architruc, the `--module` flag is getting a facelift coming soon. It will have better resolution of where to find the module file when you specify something in the flag, as @JayQuellin does. The `--module` flag is documented on what it does. 

I'll talk to the team about where to document the `path/to/component` (`bar/foo` in my post) part as it works for all types, not just components.

**Comment by sujithtomy** [comment]
I had the similar issue while generating component inside components folder.
my directory structure was: `src/app/components/main-component-name/sub-component-name`

so running 
_src/app/components_ > `ng g gallery/image-list --module gallery/image-list`
gave error : 

> Error: Specified module does not exist

but running from `src/app` was fine. 👍 
 _src/app_ > `ng g c components/gallery/image-list --module components/gallery/image-list`

> create src/app/components/gallery/image-list/image-list.component.scss (0 bytes)
> create src/app/components/gallery/image-list/image-list.component.html (34 bytes)
> create src/app/components/gallery/image-list/image-list.component.spec.ts (685 bytes)
> create src/app/components/gallery/image-list/image-list.component.ts (305 bytes)
> update src/app/components/gallery/gallery.module.ts (633 bytes)

The cli need module resolution relative to the path where the command run.
Thanks to @delasteve for giving advise regarding module path in command.
