### ISSUE TITLE
Inconsistent folder name casing

### ISSUE THREAD

**Issue by AsherFoster** [angular/angular-cli#5424]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.

macOS Sierra
@angular/cli: 1.0.0-rc.2
node: 7.4.0
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9

### Repro steps.

`ng new`
`ng g m exampleName`
`ng g c exampleName/anotherExample`

### The log given by the failure.

$ ng g m **exampleName**
installing module
  create src/app/**example-name**/example-name.module.ts
$ ng g c **exampleName**/anotherExample
installing component
  create src/app/**exampleName**/another-example/another-example.component.css
  create src/app/**exampleName**/another-example/another-example.component.html
  create src/app/**exampleName**/another-example/another-example.component.spec.ts
  create src/app/**exampleName**/another-example/another-example.component.ts
  update src/app/app.module.ts
(Emphasis on exampleName and example-name)
### Desired functionality.

I would expect the directory names to be consistent (Both exampleName or example-name) instead of differing

**Comment by Brocco** [comment]
The implementation of this behavior will only occur if the directory to be created does not already exist. So in the example above if `src/app/exampleName` already existed the case would not change.
