### ISSUE TITLE
Error in Maximum call stack size exceeded

### ISSUE THREAD

**Issue by alapasset** [angular/angular-cli#5427]
### Bug Report or Feature Request
- [x] bug report
- [ ] feature request

### Versions.
@angular/cli: 1.0.0-rc.2
node: 6.9.2
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9

### Repro steps.
I run ng serv / ng test or ng build and i have : "ERROR in Maximum call stack size exceeded"

### The log given by the failure.

After "ng serve"
![image](https://cloud.githubusercontent.com/assets/8247042/23937585/8d8900e4-0958-11e7-8ebe-89684a4d521d.png)
After I save one time and all is alright : 
![image](https://cloud.githubusercontent.com/assets/8247042/23937613/b6cb6f64-0958-11e7-83ac-5113876ce95b.png)

But for "ng test":
![image](https://cloud.githubusercontent.com/assets/8247042/23937627/caa81bfe-0958-11e7-96a3-e0ae71fb0efb.png)

### Desired functionality.
I have this issue since 3 - 4 days. Any idea to resolve this ? 

Thx a lot :)

**Comment by filipesilva** [comment]
I have no idea. Never ran into it myself. Do you have a repo that I can checkout and see this?

**Comment by Rodrigo54** [comment]
I'm also having this problem in
Https://github.com/Rodrigo54/angular2

When I give ng it displays the error, but if I change some file the error disappears
With this I can not use ng build and ng test

### Versions.
@angular/cli: 1.0.0
node: 7.5.0
os: win32 x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

**Comment by alapasset** [comment]
I have resolve this.

I had a parent import module inside a child module. That doing an "import loop". Check ?

**Comment by vaibhavbparikh** [comment]
https://github.com/angular/angular-cli/issues/6309

Similar issue but scenario is different.

**Comment by sumitarora** [comment]
Closing above being tracked at above issue.

**Comment by DenisKondrachukYi** [comment]
@alapasset Nice!Thank you👏🏼

**Comment by kasius** [comment]
revisen la manera en que utilizan el router de cada modulo, tenía este mismo problema y era que estaba declarando mal el router en uno de mis modulos

**Comment by nikhildesu** [comment]
This is due to the modules which are calling in loop that never exists. check the module references/imports to resolve it.
