### ISSUE TITLE
Cannot use NPM Link with angular/cli v1.0.0-rc.2 any more

### ISSUE THREAD

**Issue by markuseckstein** [angular/angular-cli#5428]
### Bug Report or Feature Request (mark with an `x`)
- [x ] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
@angular/cli: 1.0.0-rc.2
node: 7.6.0
os: win32 x64
@angular/common: 4.0.0-rc.3
@angular/compiler: 4.0.0-rc.3
@angular/core: 4.0.0-rc.3
@angular/forms: 4.0.0-rc.3
@angular/http: 4.0.0-rc.3
@angular/platform-browser: 4.0.0-rc.3
@angular/platform-browser-dynamic: 4.0.0-rc.3
@angular/router: 4.0.0-rc.3
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 4.0.0-rc.3

### Repro steps.
Create two simple Projects with cli:
```
ng new --ng4 project-a
ng new --ng4 project-b
```

Create a very simple component in project-b and export it in a module.
In project-b do:

`npm link`

In project-a do:

`npm link project-b`

and use the simple component from project-b. ng serve and ng build fails, regardless if using flag --aot or not.
If I pack the project-b with npm pack and then install the tarball in project-a instead of npm linking, everything works as expected.

### The log given by the failure.
```
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 6.58 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 9.89 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 1.96 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in C:/temp/test1/projA/node_modules/proj-b/node_modules/@angular/core/typings/core.d.ts, resolving symbol BeeModule in C:/temp/test1/projA/node_modules/proj-b/src/app/bee/bee.module.ts, resolving symbol BeeModule in C:/temp/test1/projA/node_modules/proj-b/src/app/bee/bee.module.ts
```

### Desired functionality.
I want to be able to use NPM LINK because this saves so much time during development.

### Mention any other details that might be useful.
It still worked in angular-cli@v1.0.0-beta.26

**Comment by filipesilva** [comment]
Heya, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

The CLI always runs statical analysis on code to ensure it will run when compiled with AOT. This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

A good resource on how to to debug these errors is https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts.

**Comment by markuseckstein** [comment]
Hi @filipesilva ,
thanks for the AOT tipp, but this issue is somewhat different because it happens even for two totally fresh projects created by the CLI (which surely do not use any AOT-incompatible code). 

And as stated in the issue, it happens only of you use NPM  Link to reference the two projects. When I use for example NPM pack and install the generated tarball in the other project, everything works fine.

We tried on Linux as well, there the issue exists as well. When referencing the tarball, everything works as expected. When using NPM link, `ng build` fails.

For our project it's really a pain that we cannot use NPM link any more. This slows us down tremendously.

best regards,
Markus

**Comment by filipesilva** [comment]
If it works without npm link, then you might be getting https://github.com/angular/angular-cli/issues/3847 or a number of the other issues we have with npm link.
