### ISSUE TITLE
 "--ssl" and "--open" don't work correctly.

### ISSUE THREAD

**Issue by Gcuencam** [angular/angular-cli#5430]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
angular-cli: 1.0.0-beta.18
node: 6.6.0
os: darwin x64

### Repro steps.
````
  "scripts": {
    "start-dev": "ng serve --host dummyhost.com --port 4200 --live-reload-port 49153 --ssl --open"
  }
````

````
npm run start-dev
````

### The log given by the failure.
Nothing to add. 

### Desired functionality.
This opens the url with http. It should open the url with https.

**Comment by clydin** [comment]
You appear to be using a fairly old version.  Please update to the latest (1.0.0-rc.2).

**Comment by filipesilva** [comment]
Closing as answered by @clydin, thanks!
