### ISSUE TITLE
AOT : Factory with parameter, "Error encountered resolving symbol values statically"

### ISSUE THREAD

**Issue by will421** [angular/angular-cli#5434]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.

@angular/cli: 1.0.0-rc.1
node: 6.9.4
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

### Repro steps.

I'm trying to create a resolver factory and use it multiple times with various 'type'.
'RESOLVERS' is then used in providers of app module.

I understand that AOT does not allow this. I tried solutions from 
https://github.com/rangle/angular-2-aot-sandbox#func-in-providers-usefactory-top
and from other issues.

```
export function labelResolverFactory(type: string) {
  return (labelService: LabelService) => {
    return (): Observable<Array<Label>> => {
      return labelService.getLabels(type);
    };
  };
}

export const RESOLVERS: Provider[] = [
  {
    provide: 'buildings',
    useFactory: labelResolverFactory("BUILDING"), deps: [LabelService]
  }
];

```

### The log given by the failure.

`ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 104:10 in the original .ts file), resolving symbol labelResolverFactory `

### Desired functionality.

A way to use factory with parameters

**Comment by filipesilva** [comment]
As you said, AOT does not allow this. If you which to submit a request for AOT to support this usage, please file an issue in https://github.com/angular/angular instead.

**Comment by jogelin** [comment]
Did ou create the corresponding issue in the angular repository ? Could you link it ?

There is still no way to provide static values to a factory ?

**Comment by will421** [comment]
I did not create a corresponding issue but there is similar issue : https://github.com/angular/angular/issues/17295

I tried another way to provide static values to a factory using DI but it did not work. I created an issue for this one :
https://github.com/angular/angular/issues/17564
