### ISSUE TITLE
ng serve --open always gives issue (webpack: Failed to compile.)

### ISSUE THREAD

**Issue by AndroidHitchhiking** [angular/angular-cli#5436]
**Created App By _ng new_, successfull, but running by _ng serve_ always a pain**
```
ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localho
st:4200' in 'D:\javascript\angular2\HelloWord'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in multi ./src/styles.css
Module not found: Error: Can't resolve 'style-loader' in 'D:\javascript\angular2
\HelloWord'
 @ multi ./src/styles.css

ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in 'D:\javascript\angu
lar2\HelloWord'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in 'D:\javascript\angu
lar2\HelloWord'
 @ multi ./src/polyfills.ts

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'raw-loader' in 'D:\javascript\an
  gular2\HelloWord':
  Error: Can't resolve 'raw-loader' in 'D:\javascript\angular2\HelloWord'

  - compiler.js:76
    [HelloWord]/[cli]/[html-webpack-plugin]/lib/compiler.js:76:16

  - Compiler.js:280 Compiler.<anonymous>
    [HelloWord]/[cli]/[webpack]/lib/Compiler.js:280:10

  - Compiler.js:480
    [HelloWord]/[cli]/[webpack]/lib/Compiler.js:480:13

  - Tapable.js:138 next
    [HelloWord]/[cli]/[webpack]/[tapable]/lib/Tapable.js:138:11

  - CachePlugin.js:62 Compiler.<anonymous>
    [HelloWord]/[cli]/[webpack]/lib/CachePlugin.js:62:5

  - Tapable.js:142 Compiler.applyPluginsAsyncSeries
    [HelloWord]/[cli]/[webpack]/[tapable]/lib/Tapable.js:142:13

  - Compiler.js:477
    [HelloWord]/[cli]/[webpack]/lib/Compiler.js:477:10

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [HelloWord]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:640 self.applyPluginsAsync.err
    [HelloWord]/[cli]/[webpack]/lib/Compilation.js:640:19

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [HelloWord]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:631 self.applyPluginsAsync.err
    [HelloWord]/[cli]/[webpack]/lib/Compilation.js:631:11

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [HelloWord]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:626 self.applyPluginsAsync.err
    [HelloWord]/[cli]/[webpack]/lib/Compilation.js:626:10

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [HelloWord]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compilation.js:622 sealPart2
    [HelloWord]/[cli]/[webpack]/lib/Compilation.js:622:9

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [HelloWord]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46


webpack: Failed to compile.
```

### Versions.
@angular/cli: 1.0.0-rc.2
node: 6.9.2
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9

**Comment by w4songwang** [comment]
I have the same problem too

**Comment by noogn** [comment]
Also have the same issue. I'm on Windows 10, upgraded Node and npm to the latest versions to be sure. Did an `npm install` in the project directory as well - didn't make a difference.

Installing Angular CLI locally to my project solved the serve/build issue, it's more of a workaround than a solution.

**Comment by filipesilva** [comment]
You seem to have a broken install. A lot of packages that the CLI depends on are not there. @noogn reported reinstalling everything and it still did not work though.

So I'm not sure what's happening.

What's your node and npm versions? And what's the result of running these commands?
```
npm ls @ngtools/webpack
npm ls raw-loader
```

**Comment by noogn** [comment]
Node: 6.9.1
npm: 4.4.1

The first time I ran it, I got nothing from running both commands, like they didn't exist. 

Since then I've reinstalled Node, npm (even though they were already the latest versions) and angular-cli and rebooted. ng serve and build now seems to work without a hitch.

**Comment by zartdinov** [comment]
os: win32 x64
node: 6.10.0 (LTS)
npm: 3.10.10 (LTS)

Maybe it will be useful for someone else.
I have same errors when using `ng serve`, `ng build`.

I tried all instructions from other related issues (also properly reinstalled all globally).
I was confused when get same error in docker container too (Linux image, Docker on same machine).

I solved problem by using yarn as default package manager for angular-cli.
```
npm install yarn -g
ng set --global packageManager=yarn
```

**Comment by filipesilva** [comment]
Closing as it seems it's an install issue. There isn't much we can do for those... the CLI never even gets installed, much less run. It's usually some problem with npm, or the npm install.

**Comment by supriyasuresh** [comment]
Not able run the ng serve command its showing error like this.if any body knows please suggest me.
![image](https://cloud.githubusercontent.com/assets/26717770/24363366/4aaf41b4-132d-11e7-9e49-138f5388fa3d.png)

**Comment by Tyshark9** [comment]
run this for the kendo errors

`npm install --save @progress/kendo-angular-l10n@^0.2.0`

**Comment by fahad-nxvt** [comment]
@zartdinov using Yarn fixed the issue.

**Comment by uditguru** [comment]
I am getting the following error : what could be the issue ?
i've tried everything here 

```
`ERROR in C:/Users/Udit/yatrum/src/app/components/trips/trip-detail/trip-detail.component.ts (14,26): Cannot find module 'ng2-cable/js/index'.

ERROR in C:/Users/Udit/yatrum/src/app/components/trips/trip-detail/trip-detail.component.ts (17,29): Cannot find module 'ng2-cable/js/index'.

ERROR in C:/Users/Udit/yatrum/src/app/components/trips/trip-detail/trip-detail.module.ts (9,39): Cannot find module 'ng2-cable/js/index'.

ERROR in Error encountered resolving symbol values statically. Could not resolve ng2-cable/js/index relative to C:/Users/Udit/yatrum/src/app/components/trips/trip-detail/trip-detail.module.ts., resolving symbol TripDetailModule in C:/Users/Udit/yatrum/src/app/components/trips/trip-detail/trip-detail.module.ts, resolving symbol TripDetailModule in C:/Users/Udit/yatrum/src/app/components/trips/trip-detail/trip-detail.module.ts

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (C:\Users\Udit\yatrum\node_modules\typescript\lib\typescript.js:9426:20)
    at Object.createCompilerHost A(C:\Users\Udit\yatrum\node_modules\typescript\lib\typescript.js:62475:26)
    at Object.ngcLoader (C:\Users\Udit\yatrum\node_modules\@ngtools\webpack\src\loader.js:202:31)
 @ multi webpack-dev-server/client?http://localhost:4200 `./src/main.ts``
```

**Comment by mmanavaz** [comment]
I'm having a similar issue. Below is my error:

ERROR in ./src/main.ts
Module build failed: [object Object]
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
ERROR in ./src/polyfills.ts
Module build failed: [object Object]
 @ multi ./src/polyfills.ts

**Comment by Vishals05** [comment]
![capture](https://user-images.githubusercontent.com/29504845/32942400-f4e9147c-cbae-11e7-8eb8-ba5efad8c07e.PNG)
what will be the possible solution for this to get rid of this error?

**Comment by hardy1334** [comment]
![ghhg](https://user-images.githubusercontent.com/31733278/34665821-b7eb4228-f487-11e7-9124-6c0f538e1166.png)
I'm also facing the same problem
![error](https://user-images.githubusercontent.com/31733278/34665778-8e6626a2-f487-11e7-976e-0b886712267c.png)

**Comment by Akhilesh789** [comment]
![error1](https://user-images.githubusercontent.com/30531958/34971978-72d7783c-faa4-11e7-82f0-87abae27c4c8.png)
![error2](https://user-images.githubusercontent.com/30531958/34971981-79d65720-faa4-11e7-8af2-757c171aef3b.png)

what will be the possible solution for this to fixed this error?

**Comment by hardy1334** [comment]
If you have grammarly extension installed in Chrome make sure to remove
that bcoz sometimes it gives error

I was also facing similar issue that was removed by removing grammarly
extension from Chrome, it is also the issue on GitHub , there I came to
know that it gives problem with grammarly
