### ISSUE TITLE
How to build files without bundle to one file

### ISSUE THREAD

**Issue by amabdelmongy** [angular/angular-cli#5440]
i'm using Microsoft visual Studio with Angular CLI 

Could the cli build and generate same files not to bundle file ?

**Comment by alvaro450** [comment]
This may not be possible, the CLI uses webpack which is a bundler, although the option to generate separate chunks is available, in the end webpack is used to bundle a collection of files into one or many chunks. What are you trying to do specifically?

**Comment by amabdelmongy** [comment]
I want to run the Angular CLI project by using run of Microsoft visual Studio

**Comment by filipesilva** [comment]
We always bundle and there is no way to turn it off. There are ways to run the CLI with Visual Studio though. We don't document it here, but you can find it on google.
