### ISSUE TITLE
Angular cli e2e test with Proxy

### ISSUE THREAD

**Issue by zwolejo** [angular/angular-cli#5441]
So I am trying to run e2e test behind proxy. At the moment chromedrivers, selenium etc are downloaded automaticly when running npm run e2e. Problem is that I have proxy. For older version of protractor 4 i w been using webdriver-manager update --alternative_cdn xxx before protractor tests. How can I force to use alternative cdns when webdriver update is build into npm run e2e command? I am not even sure if this flag stiill works when using embedded webdriver in protractor 5.

**Comment by zwolej** [comment]
when I downgraded protractor to ~4.x I am able to use it with:

> "pree2e": "webdriver-manager update --alternate_cdn=<YOUR_PROXY>",
> "e2e": "ng e2e",

with protractor 5 alternate_cdn it is not working. Maybe there is more elegant way than using pre task ?

**Comment by zwolej** [comment]
yup there is bug in webdriver. You can use protractor 5.0.0 which includes webdriver-managaer 11.1.1 which is free of that bug.
