### ISSUE TITLE
RFE: timestamp after compiler output

### ISSUE THREAD

**Issue by sgbeal** [angular/angular-cli#545]
ng server "really should" output a timestamp at the end of its incremental compilation output, else it's impossible to confirm that it's doing anything unless one just happens to have it in view when it kicks in and can see it scroll by (it is normally hidden behind intelliJ).

e.g.

```
file added app\components\msisdn-search\msisdn-search-form.component.ts___jb_bak___
...    
Build successful - 532ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
BroccoliTypeScriptCompiler                    | 275ms
...

2016-04-27 09:17 <<<<------ here
```

that would be a big usability improvement,

**Comment by jkuri** [comment]
@hansl is this something that we should work on?

**Comment by filipesilva** [comment]
I think it would involve having our own override to `Builder`, so it's not that trivial.

**Comment by jkuri** [comment]
I think it can be done with some extra hack in https://github.com/angular/angular-cli/blob/master/lib/cli/index.js, but it also doesn't seem so important to me.

**Comment by hansl** [comment]
Not important right now. Pushed after ng-conf.

**Comment by sgbeal** [comment]
Not important unless you're trying to use it daily :/. Not being able to see if it's actually running and processing the current code is a real drag.

**Comment by jkuri** [comment]
It is running. Its just fast enough you can't see the changes.

**Comment by sgbeal** [comment]
That's the gag - we've had it _stop_ running more than once, and we like to have a visual indication that it hasn't done so again.

**Comment by filipesilva** [comment]
#1455 changed the build step drastically, can you check if this is still needed?

**Comment by filipesilva** [comment]
Sample of `ng serve` output:

```
kamik@T460p MINGW64 /D/sandbox/webpack-project (master)
$ ng serve
(node:12676) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
 10% building modules 1/1 modules 0 active
*
*
 NG Live Development Server is running on http://localhost:4200.
*
5368ms building modules
12ms sealing
0ms optimizing
0ms basic module optimization
18ms module optimization
2ms advanced module optimization
7ms basic chunk optimization
2ms chunk optimization
0ms advanced chunk optimization
0ms module and chunk tree optimization
45ms module reviving
8ms module order optimization
4ms module id optimization
7ms chunk reviving
1ms chunk order optimization
11ms chunk id optimization
29ms hashing
2ms module assets processing
52ms chunk assets processing
4ms additional chunk assets processing
1ms recording
0ms additional asset processing
104ms chunk asset optimization
691ms asset optimization
12ms emitting
Hash: da0621dd0d54cc99ff06
Version: webpack 2.1.0-beta.18
Time: 6387ms
              Asset       Size  Chunks             Chunk Names
     main.bundle.js    2.18 MB    0, 2  [emitted]  main
polyfills.bundle.js     225 kB    1, 2  [emitted]  polyfills
          inline.js    4.96 kB       2  [emitted]  inline
           main.map    2.58 MB    0, 2  [emitted]  main
      polyfills.map     287 kB    1, 2  [emitted]  polyfills
         inline.map    5.13 kB       2  [emitted]  inline
         index.html  502 bytes          [emitted]
         .gitignore    0 bytes          [emitted]
         .npmignore    0 bytes          [emitted]
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.44 kB       0
webpack: bundle is now VALID.
```

**Comment by mkelley82** [comment]
It would be great to see a timestamp on ng build output .... is this being worked on by anyone?

**Comment by gelliott181** [comment]
I've got a PR coming together, it should be in tomorrow.

**Comment by catull** [comment]
@gelliott181 What is the progress with your PR ?  Is it bundled with https://github.com/angular/angular-cli/pull/4057 ?

**Comment by gelliott181** [comment]
This PR hit a snag after I dove down again and kept peeling away the calls.
To implement this either there needs to be a PR over in webpack-dev-server
as mentioned, or we need to write a custom webpack plugin. I think a plugin
is the best way to go, but I'd like to accumulate some more related
functionality before I add a whole new plugin to the build process and
maintenance list.

There isn't anywhere in the actual CLI code which outputs on serve builds,
it's all down the webpack hole. Someone could PR webpack-dev-server with a
couple new lines to do this, but that won't help here if it's rejected.

**Comment by filipesilva** [comment]
There is a feature request for this in Webpack, if it gets in we can add it to the CLI: https://github.com/webpack/webpack/issues/4718
