### ISSUE TITLE
ng build shows "not an ngModule" error for external imported module

### ISSUE THREAD

**Issue by Niraj-Sharma** [angular/angular-cli#5450]
-[ x] bug report -> ng build shows error as "not an ngModule" for imported modules ..i tried with "RoundProgressModule", "BusyModule"

### Versions.
@angular/cli: 1.0.0-rc.2
node: 6.10.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9

 Windows- 7

### Repro steps.
1. install "angular-svg-round-progressbar"/"angular2-busy" modules
2. Import these modules in app.module.ts
3. try generating app build using command "ng build"
### The log given by the failure.
$ ng build
Hash: 980672e02756722e94b2                                                      Time: 9290ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 143 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 9.78 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.44 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
ERROR in BusyModule is not an NgModule
-----------------------
$ ng build
Hash: c60aebedac43613bbe64                                                      Time: 9361ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 143 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 9.78 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.44 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 79:22 in the original .ts file), resolving symbol AUTH_PROVIDERS in D:/source-code/nks-git/amdocs-ng/amdocsacademyv3.0/node_modules/angular2-jwt/angular2-jwt.d.ts, resolving symbol AppModule in D:/source-code/nks-git/amdocs-ng/amdocsacademyv3.0/src/app/app.module.ts, resolving symbol AppModule in D:/source-code/nks-git/amdocs-ng/amdocsacademyv3.0/src/app/app.module.ts

### Desired functionality.
Successful build..

### Mention any other details that might be useful.
ng serve works fine after any single file edit and save..

**Comment by filipesilva** [comment]
Heya, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

The CLI always runs statical analysis on code to ensure it will run when compiled with AOT. This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

A good resource on how to to debug these errors is https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts.
