### ISSUE TITLE
e2e tests with mocked backend

### ISSUE THREAD

**Issue by zwolej** [angular/angular-cli#5451]
I want to run protractor tests on mocked environment. My start command at the moment looks like:

> "start": "npm-run-all -s mock-backend serve",//2 task parallel
> "serve": "ng serve --proxy-config proxy.conf.json",

How exactly ng e2e works? I thought it runs npm run start and then it runs protractor tests. But from what I see e2e is running something else than npm run start because my e2e test are not using mocked-backend.

At the momeent I have created something like:

> "e2e": "npm-run-all -s start protractor",//2 task in sequence
>  "protractor": "protractor protractor.conf.js",

I am trying to avoid using ng e2e, but my solution is not working since start is never ending, so I should run those commands in parallel but then how can I delay running protractor to wait for npm will start serving server?

**Comment by zwolej** [comment]
I figure out that you can pass proxy flag to e2e command so solution is to use:

> "e2e": "npm-run-all -p -r mock-backend protractor",
> "protractor": "ng e2e --proxy-config proxy.conf.json",

I think that all commands should be build from existing npm scripts. If e2e would use npm start it would be always automaticly configured.

**Comment by filipesilva** [comment]
The way you discovered is the right way to do it. You need to send the proxy config in an argument to `ng e2e`.

We actually tried having commands that just used the npm scripts. It didn't work out very well. Hard to debug errors, no access to public APIs, stuff like that.
