### ISSUE TITLE
protractor.conf.js discrepency in RC migration guide

### ISSUE THREAD

**Issue by arlowhite** [angular/angular-cli#5458]
### Bug Report or Feature Request (mark with an `x`)
- [x] documentation bug report -> please search issues before submitting
- [ ] feature request

### Versions.

> @angular/cli: 1.0.0-rc.2
> node: 6.9.1
> os: linux x64

### Repro steps.

Create new project with `ng new`
Compare protractor.conf.js to https://github.com/angular/angular-cli/wiki/stories-rc-update#protractorconfjs

### Current documentation shows:

```
beforeLaunch: function() {
  require('ts-node').register({
    project: 'e2e'
  });
},
```

### Desired documentation (new project's protractor.conf.js).

```
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
  },
```

**Comment by filipesilva** [comment]
Bug in our docs, will be fixed as part of https://github.com/angular/angular-cli/issues/5484
