### ISSUE TITLE
RC Upgrade documentation root tsconfig.json differs

### ISSUE THREAD

**Issue by snicolai** [angular/angular-cli#5464]
### Bug Report or Feature Request (mark with an `x`)
- [X] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
@angular/cli: 1.0.0-rc.2
node: 6.9.4
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9

### Repro steps.

```
ng new test
```
compare the root tsconfig.json file with the root tsconfig in the RC upgrade directions.  ng new adds a baseUrl field, the RC upgrade directions are missing it.
```
$ diff upgraded/tsconfig.json test/tsconfig.json 
4a5
>     "baseUrl": "src",
```

### Desired functionality.

The RC upgrade directions should be comparable to creating the project with the 1.0 version.

**Comment by filipesilva** [comment]
Will be fixed as part of https://github.com/angular/angular-cli/issues/5484.
