### ISSUE TITLE
What is the difference between npm install @latest and npm install specific version

### ISSUE THREAD

**Issue by brookhutchinson** [angular/angular-cli#5465]
### Bug Report or Feature Request (mark with an `x`)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Versions.
@angular/cli v1.0.0-rc.2
node: 7.6.0
os: Win32 x64 (Windows 10)

### Question.
If I want to use npm to install the latest @angular/cli package and @angular/cli v1.0.0-rc2 is the latest released version...
**What is the difference between the following npm commands?**
`npm install @angular/cli@latest`
and
`npm install @angular@1.0.0-rc2`

**Comment by grizzm0** [comment]
`@1.0.0-rc2` will install a specific version while `@latest` will pull the latest version from npm. In this case they would do the same as 1.0.0-rc2 currently is the latest version.
