### ISSUE TITLE
Unable to run production mode when have dynamical component

### ISSUE THREAD

**Issue by vivian7169** [angular/angular-cli#5466]
### Bug Report
- [ bug report ]
When I build it using the latest Angular CLI with a non-production setting, it all works fine. However, once I use the production setting (e.g: ng serve --prod --host 0.0.0.0 --port 4200) I get the following error trace in the browser immediately when trying to load a page that has dynamically created content:

ERROR in Cannot determine the module for class XXXXXXXComponent in /.../src/app/xxxxx/xxxxx.component.ts! Add XXXXXXXComponent to the NgModule to fix it.

### Versions.
node 6.9.4
npm 3.10.10
macOS Sierra
angular cli 1.0.0-rc.1
angular 4.0.0-rc.2

### Mention any other details that might be useful.

constructor(injector: Injector) {
       this.injector = ReflectiveInjector.resolveAndCreate(COMPILER_PROVIDERS, injector);
       this.compiler = this.injector.get(Compiler);
}

then in createComponentFactory function:

this.compiler.compileModuleAndAllComponentsAsync(createComponentModule(comp))
       .then((moduleWithFactories: ModuleWithComponentFactories<any>) =>  {
                 factory = moduleWithFactories.componentFactories.find(x => x.componentType === comp);
		this.cache.set(type, factory);
		this.resolveCompHelper$.next({ type, factory});
		resolve(factory);
      });

**Comment by filipesilva** [comment]
AOT requires your code to be statically analyzable and does not support your usecase. You can disable AOT via `ng prod --no-aot`.
