### ISSUE TITLE
Unable to install angular-cli from npm registry

### ISSUE THREAD

**Issue by JayBhusari** [angular/angular-cli#5468]
Hi Team,

We are trying to install angular-cli using below command:
./node npm install -g angular-cli

but we are getting below errors:
npm ERR! registry error parsing json
npm ERR! Unexpected token < in JSON at position 0 
npm ERR! <p>The requested URL /content/groups/NPM_All/@angular-cli/ast-tools was not found on this server.</p>

**registry used**: http://registry.npmjs.org/
**node version**: 6.10.0
**npm version**: 3.10.10
**package downloaded**: node-v6.10.0-linux-x64.tar.xz
**Server Details**: Red Hat Enterprise Linux Server release 6.5 (Santiago)

Also tried npm clean cache but didn't work
Also tried to install through below command:
./node npm install -g @angular/cli
getting error:
npm ERR! 404 Not Found
npm ERR! </head><body>
#npm ERR! Not Found
npm ERR! <p>The requested URL /content/groups/NPM_All/@angular/cli was not found on this server.</p>
npm ERR! </body></html>

PS: We are using Nexus for proxy registry setup

Kindly suggest us.

**Comment by clydin** [comment]
The correct package is '@angular/cli'.
Your proxy may be blocking scoped packages.

**Comment by filipesilva** [comment]
Closing as answered by @clydin, thanks!

**Comment by JayBhusari** [comment]
Hi @clydin / @filipesilva 
Thanks for your response..!
I used correct package '@angular/cli'
 
Yes may be proxy is blocking so is there any other registry where I can download the dependencies 
Or any other way I can install @angular/cli ?

**Comment by filipesilva** [comment]
I don't think there's any other way besides npm :/

**Comment by JayBhusari** [comment]
I'm using Nexus proxy repository to access registry: http://registry.npmjs.org/

On My browser I'm hitting URL(http://registry.npmjs.org/@angular/cli) to access package '@angular/cli' it is giving me  output {"error":"Not found"}

while URL(http://registry.npmjs.org/angular-cli) to access package 'angular-cli' giving me proper output.

I guess '@angular-cli' doesn't exist over registry:http://registry.npmjs.org/ while 'angular-cli' exist.
Am I wrong ?

**Comment by filipesilva** [comment]
I don't know how the registry resolves scoped package names (the ones `@something/something`) but I know it's available on npm: https://www.npmjs.com/package/@angular/cli.

This works for instance: https://registry.npmjs.org/@angular/core/-/core-2.4.9.tgz

Also make sure you're using at least npm 3 or more and your registry supports scoped packages.

**Comment by kondaurovDev** [comment]
I have the same issue. I can't install it on my mac

Aleksandrs-Mini:~ aleksandr$ npm install @angular/cli -g --registry https://registry.npmjs.org
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@angular/cli" "-g" "--registry" "https://registry.npmjs.org"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 User not found : @angular/cli
npm ERR! 404 
npm ERR! 404  '@angular/cli' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url

**Comment by kondaurovDev** [comment]
I've found solution:

I'm using private npm repository at bintray. So i had do provide credentials for it and these credentials were written in npm config. I removed auth section in it and now it works

run this command and edit: npm config edit

**Comment by cshunger** [comment]
Getting rid of the auth section in my *npm config edit* worked. 

Thanks @kondaurovDev
