### ISSUE TITLE
'ng build' provide flag to build just changed files 

### ISSUE THREAD

**Issue by shral** [angular/angular-cli#5471]
### Bug Report or Feature Request (mark with an `x`)
- [x] feature request

### Versions.

Output from: `ng --version`:
angular-cli: 1.0.0-beta.19-3
node: 6.2.2
os: linux x64

### Repro steps.

I'm using angular 2 in an maven java project and every time that I'm building my java project the maven calls 'ng build' the problem with that is that every time ng build builds the angular 2 project even if nothing was changed, is there any flag that ng build builds just if something was changed (like the watch flag after the first call, but without watching)?

**Comment by filipesilva** [comment]
We only have the watch flag. You can maybe have a solution outside of the CLI (or by using `ng eject`) by using https://github.com/mzgoddard/hard-source-webpack-plugin.

**Comment by soumyakantiroychowdhury** [comment]
I am facing the same issue and would really like to have a `--incremental` option.

**Comment by playground** [comment]
Me 2, I have a project with multiple apps, would be great to have --incremental option to only build apps with modified files.
