### ISSUE TITLE
Cannot install latest 1.0.0-rc2 version

### ISSUE THREAD

**Issue by igortd** [angular/angular-cli#5474]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.

node v6.10.0
npm  v4.0.3

### Repro steps.

Trying to install the latest angular-cli version gives me 
@angular/cli: 1.0.0-beta.32.3 [undefined]

### The log given by the failure.

npm install @angular/cli@1.0.0-rc2
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IC186012\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@angular/cli@1.0.0-rc2"
npm ERR! node v6.10.0
npm ERR! npm  v4.0.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: @angular/cli@1.0.0-rc2
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.0-beta.32.3, 1.0.0-beta.32.2, 1.0.0-beta.32, 1.0.0-beta.31, 1.0.0-beta.30, 1.0.0-beta.29, 1.0.0-beta.28.3
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IC186012\workspace\ui-notification-center-ng2\npm-debug.log

### Desired functionality.

To install latest angular-cli version

**Comment by clydin** [comment]
The version is '1.0.0-rc.2'.  Note the period between rc and 2.

**Comment by igortd** [comment]
Same error with 1.0.0-rc.2

**Comment by igortd** [comment]
It was internal network problem.
