### ISSUE TITLE
--deployUrl causes webpack chunks to fail loading

### ISSUE THREAD

**Issue by logic01** [angular/angular-cli#5478]
### Bug Report or Feature Request (mark with an `x`)
- [X ] bug report -> please search issues before submitting
- [ ] feature request

This feature caused this bug:
[https://github.com/angular/angular-cli/commit/0ce64a48a4b44a8d6b7f9b67a8182bfd2c3fb455](feature)

### Versions.

@angular/cli: 1.0.0-rc.2
node: 6.10.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9

Windows 10. 64 bit

### Repro steps.

**1.  Edit:** 
- [x] .angular-cli.json

**2. Add:**
- [ ] "deployUrl": "content"

**3. ng build**
- [ ] chunk    {0} 0.chunk.js, 0.chunk.js.map 76.1 kB {1} {2} {4} [rendered]
- [ ] chunk    {1} 1.chunk.js, 1.chunk.js.map 44 kB {0} {2} {4} [rendered]
- [ ] chunk    {2} 2.chunk.js, 2.chunk.js.map 2.92 kB {0} {1} {4} [rendered]
- [ ] chunk    {3} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 232 kB {7} [initial] [rendered]
- [ ] chunk    {4} main.bundle.js, main.bundle.js.map (main) 6.56 kB {6} [initial] [rendered]
- [ ] chunk    {5} styles.bundle.js, styles.bundle.js.map (styles) 9.77 kB {7} [initial] [rendered]
- [ ] chunk    {6} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.69 MB [initial] [rendered]
- [ ] chunk    {7} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered

**4. Deploy - IIS**
- [ ] Deploy index.html to a root path.
- [ ] Deploy chunks and bundles into a content folder

**5. Run**
- [ ] Navigate to page that causes chunk files to load.

### The log given by the failure.

1. In Chrome Developer Tools under Network notice that we attempt to load **content0.chunk.js**

EXCEPTION: Uncaught (in promise): Error: Loading chunk 0 failed.
Error: Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete (https://{domain}/content/inline.bundle.js:92:33) [angular]
    at HTMLScriptElement.wrapFn (https://{domain}/content/polyfills.bundle.js:7110:29) [angular]
    at Object.onInvokeTask (https://{domain}/content/vendor.bundle.js:28844:37) [angular]
    at ZoneDelegate.invokeTask (https://{domain}/content/polyfills.bundle.js:6234:36) [angular]
    at Zone.runTask (https://{domain}/content/polyfills.bundle.js:6034:47) [<root> => angular]
    at HTMLScriptElement.ZoneTask.invoke (https://{domain}/content/polyfills.bundle.js:6288:38) [<root>]
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:338
Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:557
drainMicroTaskQueue @ zone.js:566
ZoneTask.invoke @ zone.js:424

### Desired functionality.

The chunk file should be loaded correctly with content/0.chunk.js

### Mention any other details that might be useful.

I understand this may be a webpack issue and not a angular-cli issue. However, the deployUrl was implemented in the .angular-cli.json and it appears to be missing some additional webpack configuration to make chunking to work correctly.

**Comment by clydin** [comment]
Can you try with 'content/' instead of just 'content'.

**Comment by logic01** [comment]
Using 'content/' worked.

**Comment by filipesilva** [comment]
This is working as intended, although I understand the argument. We don't really edit `--base-url` or `--deploy-url` values, mostly out of concern it might negatively affect some use case.

If it's something that comes up a few more times maybe we will edit it.
