### ISSUE TITLE
Improve error message for running build statically

### ISSUE THREAD

**Issue by phil294** [angular/angular-cli#5479]
### Bug Report or Feature Request (mark with an `x`)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Versions. (latest, 4.0)

@angular/cli: 1.0.0-rc.2
node: 6.10.0
os: linux x64
@angular/animations: 4.0.0-rc.3
@angular/common: 4.0.0-rc.3
@angular/compiler: 4.0.0-rc.3
@angular/compiler-cli: 4.0.0-rc.3
@angular/core: 4.0.0-rc.3
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.0.0-rc.3
@angular/http: 4.0.0-rc.3
@angular/platform-browser: 4.0.0-rc.3
@angular/platform-browser-dynamic: 4.0.0-rc.3
@angular/platform-server: 4.0.0-rc.3
@angular/router: 4.0.0-rc.3
@angular/cli: 1.0.0-rc.2
@ngtools/webpack: 1.2.13

### Repro steps.

A `ng build` generates a `dist/index.html`. Running this file in your browser (aka `file:///home/.../index.html`) might seem intuitive but will not work (reason: [cannot issue XHR requests](https://github.com/angular/angular-cli/issues/641)).
However, the error message is not helpful at all, **saying nothing but**

> EXCEPTION: Uncaught (in promise): SecurityError: The operation is insecure.
BrowserPlatformLocation.prototype.replaceState@file:///home/phi/d/ls/repo/web/dist/vendor.bundle.js:22446:13

### Desired functionality.

Any hint to solve this error would be helpful. 
Note: For local testing, I then set up an apache server inside the `dist` directory: `php -S localhost:9090 -t . -c "/etc/php/7.0/apache2/php.ini"'`. Seemed quickest to me.

**Comment by markuseckstein** [comment]
Not a solution but a quicker workaround:

you can install the npm package http-server globally. Then you can spin up a simple http-server in any directory you like, no need for a full blown Apache:

`npm i -g http-server`

Then use

`http-server -o -c-1`

in any directory. The -o option opens a browser automatically and -c-1 disables http caching.

**Comment by filipesilva** [comment]
Please open this issue on https://github.com/angular/angular instead. That error is in an angular lib (`BrowserPlatformLocation`).
