### ISSUE TITLE
Cannot Install on Node v6

### ISSUE THREAD

**Issue by minhazfm** [angular/angular-cli#548]
Cannot install angular-cli on newly released NodeJS v6.0.0.
 
1. OS: Mac OSX El Capitan - 10.11.3
2. Versions:
        node --version: v6.0.0
        npm --version: v3.8.6
        npm info angular-cli: v0.0.34

3. Reproduction Steps:
```
npm install -g angular-cli
```
4. Log:
```
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/developer/.nvm/versions/node/v6.0.0/bin/node" "/Users/developer/.nvm/versions/node/v6.0.0/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! Invalid Version: 0.0.6pre2
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/developer/Desktop/npm-debug.log
```
5. I'm aware NodeJS v6 just came out, so this is expected, but just thought I would post it here so others are aware.

**Comment by alexpaluzzi** [comment]
Can you try clearing your npm cache? I was not able to reproduce on El Capitan or Windows 7/10. Both of them were able to install cleanly on Node 6.0.0 for me.

**Comment by minhazfm** [comment]
Hey @alexpaluzzi, thanks for the information and tip. I tried an npm cache clean, and still got the same error. I am using nvm on my Mac to switch between different Node versions if that helps in someway. The strange thing is I'm able to install the angular-cli just fine when I'm running Node v4.2.2, but v6.0.0 produces the error above.

**Comment by jkuri** [comment]
@minhazfm this seems like an issue with `nvm` and not `angular-cli`.

**Comment by minhazfm** [comment]
@jkuri Yup, looks like it was because I was running nvm v0.30.1. Once I updated to the latest nvm version (v0.31.0) it let me install the angular-cli with no issues. Thanks for the help, closing this out.
