### ISSUE TITLE
Update version of zone.js for Angular 4.0.0-rc.4

### ISSUE THREAD

**Issue by Brocco** [angular/angular-cli#5480]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Create a new project
`ng new foo --ng4`
Ensure version of @angular/core
`npm ls @angular/core`

### The log given by the failure.
```bash
<!-- Normally this include a stack trace and some more information. -->
└── UNMET PEER DEPENDENCY zone.js@0.7.8

npm ERR! peer dep missing: zone.js@^0.8.4, required by @angular/core@4.0.0-rc.4
```

### Desired functionality.

Update the version of zone.js to the version above for apps created using Angular 4.0.0-rc.4 or later.

**Comment by jvaranam** [comment]
While I updated to "zone.js": "^0.8.4". issue looks resolved.

**Comment by filipesilva** [comment]
See https://github.com/angular/angular-cli/issues/5432 for why frequency is critical (it breaks unit tests).

**Comment by shijilesh** [comment]
Hi.
What is the syntax for updating zone.js ?
i tried npm install tsd but didnt worked 

@angular/core@4.0.1 requires a peer of zone.js@^0.8.4 but none was installed.

**Comment by oanapat** [comment]
@shijilesh Try this: npm install zone.js@^0.8.4

**Comment by jose2007kj** [comment]
i tried npm install zone.js@^0.8.4 and also .5 but am getting error as invalid
