### ISSUE TITLE
Not able to include external component with aot

### ISSUE THREAD

**Issue by sugarg** [angular/angular-cli#5481]
OS: Windows 10
angular version: 2.4.0
angular-cli version: 1.0.0-rc.0
Node version: 6.9.5
Npm version: 3.10.10

**Following is my directory structure:**
<pre>
├── MainProject
│   ├── package.json
│   ├── .angular.cli.json
│   ├── src
│   │   ├── components
│   │   │   ├── widgets
│   │   │   │   ├── widget.component.ts
├── common
│   ├── widgets
│   │   ├── chart.component.ts
</pre>

My angular-cli project is in MainProject directory. 
widget.component.ts is using common/widgets/chart.component.ts
 Developer build and non aot prod of MainProject is working fine but aot prod build is giving following error. If I move chart.component.ts in src folder then it works fine. Please if someone can help in resolving it.

<pre>
ERROR in ./src/$$_gendir/components/widgets/widget.component.ngfactory.ts
Module not found: Error: Can't resolve '../../../../../common/widgets/chart.component.ngfactory' in 'C:\****\src\$$_gendir\components\widgets'
</pre>

**Comment by filipesilva** [comment]
That doesn't seem a CLI problem per se, but rather a problem with how you publish and consume your library. We're working on a library cookbook for www.angular.io soon, but it's not ready yet. 

Meanwhile my advice is to validate your library works in another app using `ngc`.
