### ISSUE TITLE
Production environment is not minifying resources

### ISSUE THREAD

**Issue by bertolo1988** [angular/angular-cli#5482]
I am running my server on production and i am noticing that none of the hosted resources is minified/uglified.

**How do i need to run my project in order to have gzip compression and resources minification?**

What is the environment `'production': false,` attribute for ?

We have been discussing the problem countless times at my workplace. We have choosen to use `ng serve` for development only. How is everyone else doing ?

PS: keep up good work, angular-cli is getting better and better. thanks alot.

**Comment by clydin** [comment]
The production build target controls optimizations/hashing/minification/etc.,  not the environment.
Also,  ng serve is purely for development purposes.  Actual deployments should be using a hosting service or production appropriate web server.

**Comment by grizzm0** [comment]
Use `ng build --prod --aot --no-sourcemap` (pretty sure --aot and --no-sourcemap is default these days) to build for production.

Gzipping has been removed from the CLI itself. Your webserver could handle the gzipping for you or you could pipe on a gulp task or similar to compress your dist folder after build.

**Comment by bertolo1988** [comment]
> The production build target controls optimizations/hashing/minification/etc., not the environment.
`ng serve --environment=production` is the same as `ng serve --prod`

**Comment by grizzm0** [comment]
`ng serve --environment=production` changes the environment, not the target. That would run a dev target with prod env.

**Comment by clydin** [comment]
'ng serve --prod' is the same as 'ng server --target=production --environment=production'

**Comment by bertolo1988** [comment]
I didn't know that either!

**Comment by grizzm0** [comment]
The environment files are where you can put different type of configs depending on the environment. API urls etc etc. The default "production" key is used in main.ts to call `enableProdMode();` which is part of angular itself.

**Comment by bertolo1988** [comment]
Thanks @grizzm0.
And what is target all about?

**Comment by grizzm0** [comment]
Target runs different webpack configs. Production does minification, optimization, hashing etc that development doesn't.

**Comment by bertolo1988** [comment]
I  got all my questions answered. Thanks @grizzm0 and @clydin

**Comment by filipesilva** [comment]
Just wanted to add that you can find some more info in https://github.com/angular/angular-cli/wiki/build.

Cheers to @clydin and @grizzm0 !

**Comment by bertolo1988** [comment]
@filipesilva that has everything i needed.Cheers!

**Comment by KhaledElAnsari** [comment]
how to did you solve your issue?

**Comment by simeyla** [comment]
If you're looking in Chrome at your files it can appear they are not minified even though they in fact are. This can be due to enabling the [pretty print feature](https://developers.google.com/web/tools/chrome-devtools/javascript/reference#format). 

This tripped me up with `ng serve` which in fact does minify when using `--prod` but I thought it hadn't. If this is happening to you then turn off the pretty print, or open the file in a blank tab to view it directly.
