### ISSUE TITLE
Please add @angular/language-service to dependencies

### ISSUE THREAD

**Issue by Arelav** [angular/angular-cli#5497]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

Does not matter

### Mention any other details that might be useful.

Please add @angular/language-service to generated projects package.json it will help to IDEs like next version WebStorm to better angular support.

More information from WebStorm site:
Angular language service

To help you even more when working with Angular, WebStorm adds support for the Angular language service, developed by the Angular team to improve code analysis and completion for Angular-TypeScript projects.

Run npm install @angular/language-service --save-dev to enable that in your project.

https://www.jetbrains.com/webstorm/nextversion/

**Comment by filipesilva** [comment]
We're looking at adding it for 1.1.

**Comment by niklas-dahl** [comment]
somebody know when vs code will take advantage of this?

**Comment by wKoza** [comment]
@niklas-dahl , there is a plugin VSC for use it.

**Comment by niklas-dahl** [comment]
with the VS code plugin already installed, what does installing `@angular/language-service` exactly do? is this just for webstorm users?

**Comment by wKoza** [comment]
Webstorm users have to install it, yes
