### ISSUE TITLE
Subsequent variable declarations error on typings.d.ts

### ISSUE THREAD

**Issue by dave11mj** [angular/angular-cli#5499]
### Bug Report or Feature Request (mark with an `x`)
- [X] bug report -> please search issues before submitting
- [ ] feature request

### Versions.

@angular/cli: 1.0.0-rc.2
node: 6.9.5
os: darwin x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.10

### Repro steps.

1.  `ng new test-typings`
2. `cd test-typings/`
3. Open `src/typings.d.ts` using `Atom` with `TypeStrong/atom-typescript` package
4. Notice error `Subsequent variable declarations must have the same type.` on line `2:13`

### The log given by the failure.

![image](https://cloud.githubusercontent.com/assets/6619371/24074438/c3c012f0-0bde-11e7-98b7-879836e7c433.png)

### Desired functionality.

I would like to not see errors when using `typings.d.ts` 

### Mention any other details that might be useful.

Using `Atom Version 1.15.0` and `TypeStrong/atom-typescript 10.1.14`

**Comment by filipesilva** [comment]
I can verify this also happens in VS Code. 

This happens because the editor tsconfig does include node typings, so when the editor reads `typings.d.ts` there's an error.

`ng build` uses a tsconfig without node typings so it's fine.

The approaches that you're trying in #5500 aren't going to work though... this probably needs a more sophisticated solution.

**Comment by dave11mj** [comment]
@filipesilva which package do you use on VS Code ? That way I can test if the proposed solution works on it.

Also is there a specific reason you feel https://github.com/angular/angular-cli/pull/5500 isn't working or is not the correct implementation ? It seems to be working on my editor and passing the test for https://github.com/angular/angular-cli/pull/5193 along with the others so far.

**Comment by filipesilva** [comment]
VS Code does not need any plugin, it should work with TS out of the box.

This is what I see there with your solution:
![image](https://cloud.githubusercontent.com/assets/4172079/24075589/56e5e60e-0c16-11e7-9821-5e2378b03531.png)

**Comment by dave11mj** [comment]
Cool !! What package is that ? I wanted to test on VS Code but didn't know which package is similar to TypeStrong

**Comment by filipesilva** [comment]
No package needed, just a vanilla install of VS Code 😄

**Comment by dave11mj** [comment]
Yeah ... Updated comment when I realized "plugin" meant package ... Overall I realized I was having same error as you on atom when I tested the tested the fix on it .. I was being too reliant on the CLI tests. I updated the PR so it doesn't use `module: any;` but rather extends `NodeModule` .. So far is working on both editors, and hopefully passes all tests.

**Comment by filipesilva** [comment]
You know what, I think that's the right solution. I hadn't thought about how declaration merging would kick in and make this whole work. Great job fixing this!

**Comment by dave11mj** [comment]
No problem ! xD .. Thanks for the VS Code screenshot btw, I hadn't realize the first solution that actually passed all tests wasn't working even on my own text editor until you showed me that ~ lol
