### ISSUE TITLE
Continued use of `ember-addon` package.json keyword poised to cause trouble

### ISSUE THREAD

**Issue by endash** [angular/angular-cli#55]
Obviously there's extensive name leakage from the wrapped EmberCLI library, but this one has present-day consequences:

http://www.emberaddons.com/?query=angular

There's only a single angular addon listed, but I moved my app over to angular-cli today partly to start packaging some of my code as addons. So I anticipate that changing.

**Comment by cironunes** [comment]
This is being addressed here https://github.com/IgorMinar/angular-cli-github-pages/pull/1

The actual issue is on the [angular-cli-github-pages](https://github.com/IgorMinar/angular-cli-github-pages) project.

**Comment by endash** [comment]
Except that https://github.com/ember-cli/ember-cli/blob/ae5e72614e40f5e6dd57463e526c65da899fde07/lib/models/addon-discovery.js#L206 will result in the addon not being discovered.

**Comment by IgorMinar** [comment]
yup. I know about this one. my plan is to talk to @stefanpenner about this and see if we can do better.

To be honest I don't think that the current strategy of creating angular-cli as an addon for ember-cli will work beyond tech demo. There way too many assumption in the current system. The only way I can see this working is for us to extract all the reusable bits from ember-cli into a separate project and then build both angular and ember cli on top of this project. The alternative is to rebuild most of the current stuff from scratch, but that would be sad.

**Comment by stefanpenner** [comment]
Im in-board with further parametrization/extraction/configuration as needed.  We just need extra people power :)

**Comment by cironunes** [comment]
I'd love to help.

**Comment by hansl** [comment]
I'm going to close this issue as this discussion seems to be closed. Once we hit alpha we need to revisit our long term plans with @stefanpenner and see how we can help make both projects better (and awesome-er)
