### ISSUE TITLE
Angular 2 Error: TypeError: Cannot read property 'stateChangeExpr' of null

### ISSUE THREAD

**Issue by tatokhorava** [angular/angular-cli#5503]
I've all latest packages installed, when I run my app in browser getting this error..  what can be the issue?

TypeError: Cannot read property 'stateChangeExpr' of null
    at _parseAnimationStateTransition (http://localhost:4200/vendor.bundle.js:31828:68)
    at http://localhost:4200/vendor.bundle.js:31792:97
    at Array.map (native)
    at AnimationParser.parseEntry (http://localhost:4200/vendor.bundle.js:31792:64)
    at http://localhost:4200/vendor.bundle.js:31749:49
    at Array.map (native)
    at AnimationParser.parseComponent (http://localhost:4200/vendor.bundle.js:31748:67)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:63445:71)
    at http://localhost:4200/vendor.bundle.js:63331:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:63331:19)
    at createResult (http://localhost:4200/vendor.bundle.js:63213:19)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:126265:26)
    at Zone.run (http://localhost:4200/vendor.bundle.js:126025:43)
    at http://localhost:4200/vendor.bundle.js:126660:57
Error: Uncaught (in promise): TypeError: Cannot read property 'stateChangeExpr' of null

**Comment by vbudilov** [comment]
Same here.

**Comment by sumitarora** [comment]
@tatokhorava @vbudilov Is there a repo we can look at?

**Comment by vbudilov** [comment]
@sumitarora , that was my mistake. No longer an issue on my side.

**Comment by filipesilva** [comment]
@tatokhorava please open a new issue and fill in the issue template, otherwise we cannot help you.

**Comment by imjonsnow** [comment]
Anyone have a solution for this?

**Comment by avgalon** [comment]
I don't have a solution but also have this error...
i just upgraded ng2-toastr from 1.36 to 4.01 and @angular/animation was missing.
After installing it, i got this error.
Any advise?

**Comment by tatokhorava** [comment]
Sorry guys for delay.. I could not find concrete solution, though I have updated all my packages to latest and it helped..  Thanks.

**Comment by wuyanxin** [comment]
console output this warning
```npm WARN @angular/animations@4.0.1 requires a peer of @angular/core@4.0.1 but none was installed.```
so update your angular packages to 4.0+ can solve the problem
angular is now on version 4.0
and don't forget to update angular-cli

**Comment by seize11** [comment]
the same and have u found a solution？

**Comment by darin-cardin** [comment]
Solved this issue on my machine. if you are using earlier versions of angular2 (2.4.10 in my case), then the animate package is included in core. Refer to it like this: 
import {  trigger, state,  style,  transition,  animate,  keyframes} from '@angular/core';

**Comment by Midhilaj** [comment]
any solution?
ERROR in Cannot read property 'stateChangeExpr' of null

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/opt/lampp/htdocs/todo/todoclient/src'
 @ ./src/main.ts 6:29-76
 @ multi ./src/main.ts
