### ISSUE TITLE
Is moduleId a reserved Keyword in Angular?

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular-cli#5509]
export class AppComponent {
title = 'app works!';

  constructor() {

      let test1 = {
            id: 'test',
            moduleId1: 'moduleId1',
            moduleId: 'IsThisReserverdWord',
            moduleId2: 'moduleId2'
        };

      console.log(test1.moduleId);

      let test2 = {
            moduleId: 'moduleId3',
        };
  }
It is very strange that the console log part is never hit and there is no exception. By removing the moduleId: 'IsThisReserverdWord' property it is all fine.

Is moduleid reserved key word as when i try and print the moduleId without having any other property in test it gives undefined and also if i try and print moduleId2 in the above test object it throws error test1 is not defined.

[Issue was previously opened in Angular github link](https://github.com/angular/angular/issues/15286#issuecomment-287607114)

**Comment by filipesilva** [comment]
It is reserved... of sorts. It's a compromise we made to seamlessly support a lot of existing documentation that does use `moduleId: module.id`.

So we remove it when we parse app code. We know this isn't ideal.
