### ISSUE TITLE
AOT compilation issue with i18n

### ISSUE THREAD

**Issue by adityamr15** [angular/angular-cli#5512]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.0-rc.2
node: 7.4.0
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9
```

### Repro steps.
To support i18n in my app, I follow [this](http://www.savethecode.com/angular2-i18n-native-support/) approach in to my code. Converting `.xlf` to `.ts`.
When I build my app with development target, the internationalization works fine but fail with production target (AOT true).
So I try to turn off the AOT compilation with production target, the internationalization is working fine as well.

This what my code looks like on `main.ts` to load the dictionary.
```javascript
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import { Language } from './i18n';

if (environment.production) {
  enableProdMode();
}

const providers = Language.dictionaryProviders;
platformBrowserDynamic().bootstrapModule(AppModule, { providers });
```

and this is my `language.ts`
```javascript
import { TRANSLATIONS, TRANSLATIONS_FORMAT, LOCALE_ID } from '@angular/core';
import en_US from './messages.en_US';

export class Language {
  static dictionary = { en_US };
  static lang_ID = localStorage['locale'] || 'in_ID';

  static get dictionaryProviders(): Array<Object> {
    const dictionary = this.dictionary;
    const lang_ID = this.lang_ID;

    if (!lang_ID && lang_ID !== 'in_ID') { return []; };

    return [
      { provide: TRANSLATIONS, useValue: dictionary[lang_ID] },
      { provide: TRANSLATIONS_FORMAT, useValue: 'xlf' },
      { provide: LOCALE_ID, useValue: lang_ID }
    ];
  }
}
```

### The log given by the failure.
There is no log error given when build. The i18n is not work when I build with production and AOT is true.

Thanks in advance

**Comment by filipesilva** [comment]
The guide you linked seems to be for generic webpack, not for the CLI. To use i18n with the CLI see https://github.com/angular/angular-cli/wiki/stories-internationalization instead,
