### ISSUE TITLE
Error while installing angular-cli with npm 

### ISSUE THREAD

**Issue by anais1477** [angular/angular-cli#5518]
Hello,

I tried to install angular-cli with npm using this command `npm install -g -f @angular/cli`
I work on Windows 8 and I'm behind a corporate proxy so i used npm config set proxy to configure my proxy settings. 

I've changed the registry : `npm config set registry http://registry.npmjs.org/`
I've also changed the registry : `npm config set "@angular/cli:registry" http://registry.npmjs.org/`
But it didn't work. It took a very long time and then threw the following errors : 

> \>npm install -generate @angular/cli
npm ERR! fetch failed http://registry.npmjs.org/tar/-/tar-2.2.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed http://registry.npmjs.org/tar/-/tar-2.2.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed http://registry.npmjs.org/tar/-/tar-2.2.1.tgz
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-generate" "@angular/cli"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! fetch failed with status code 503
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\myuser\Documents\dev\angular2_test\angular-cli-test\npm-debug.log

I've also tried these commands before installing : 
`npm uninstall -g @angular/cli `
`npm cache clean`

Still doesn't work.
If I try to reach http://registry.npmjs.org/ on firefox, it works, but http://registry.npmjs.org/tar/-/tar-2.2.1.tgz throw an error from my firewall I think whereas https://registry.npmjs.org/tar/-/tar-2.2.1.tgz
works fine.
So I put back registry to https but now I face the following error when I try to install angular-cli : 

> npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "install" "-generate" "@angular/cli"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ECONNRESET
npm ERR! network tunneling socket could not be established, cause=write EPROTO 1
01057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
npm ERR! network
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\myuser\Documents\dev\angular2_test\angular-cli-test\npm-debug.log

Here are my node and npm versions : 
`node -v
v6.10.0`
`npm -v
3.10.10`

Do you have any ideas to fix this ?

**Comment by delasteve** [comment]
This should help :)

```
npm install -g @angular/cli
```

**Comment by anais1477** [comment]
Yes sorry, that is what I'm doing, I made a mistake in my description of issue

**Comment by delasteve** [comment]
`-generate` is not a valid flag. The flag `-global` is what you are looking for.

**Comment by anais1477** [comment]
Same problem with the following `npm install -g -f @angular/cli`

**Comment by Raouf87** [comment]
This command worked for me in addition to the usual set-proxy command:

npm config set https-proxy http://yours.com:1234

**Comment by firefury** [comment]
If you are behind a corporate  proxy, you need to set proxy for both port 80 and 443 (proxy and https_proxy)
example:
npm config set proxy http://example.com:8080
npm config set https-proxy http://example.com:8080

**Comment by sistasi** [comment]
Hi I also have the same error, after setting proxy also still got error .. :( any idea?
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to http://registry.npmjs.org/os-browserify/-/os-browserify-0.3.
0.tgz failed, reason: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_G
ET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:825:
npm ERR!

**Comment by rose2001** [comment]
sistasi, how did you solved the problem? Im having the same problems. please help

**Comment by p0nku** [comment]
Yea, I also have this same problem

**Comment by sivasumanth483** [comment]
Bro I'm also getting same problem........... kindly suggest me the solution
