### ISSUE TITLE
ng test lacks sass loader options, fails to import, fails to execute tests

### ISSUE THREAD

**Issue by evanbb** [angular/angular-cli#5521]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

angular-cli: 1.0.0-beta.28.3
node: 6.10.0
os: win32 x64
Windows 10

### Repro steps.

1. ng new sass --style=scss
2. npm install bootstrap-sass
3. update angular-cli.json to include ```
      "stylePreprocessorOptions": {
        "includePaths": [
          "../node_modules/bootstrap-sass/assets/stylesheets"
        ]
      },```
4. update app.component.scss to ```@import 'bootstrap';```
5. ng serve works
6. ng test fails with exception below

### The log given by the failure.

ERROR in ./src/app/app.component.scss
Module build failed: 
@import 'bootstrap';
^
      File to import not found or unreadable: bootstrap.
Parent style sheet: stdin
      in C:\projects\sass\src\app\app.component.scss (line 1, column 1)
 @ ./src/app/app.component.ts 20:21-52
 @ ./src/app/app.component.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

### Desired functionality.

Third-party sass imports work for the app, so they should work for tests, too.

### Mention any other details that might be useful.

In the serve task, the webpack config is generated through the NgCliWebpackConfig constructor, whereas the karma plugin calls getTestConfig inside models/webpack-configs/test. Could this be related to https://github.com/angular/angular-cli/issues/5269?

**Comment by filipesilva** [comment]
That is an old CLI version that did not have that functionality. Newer version have that fixed.
