### ISSUE TITLE
How install webpack in one project created with angular-cli

### ISSUE THREAD

**Issue by capcar** [angular/angular-cli#5522]
Hi,
I have one project created with angular-cli and I want integrate webpack in it. 
How must i do it?

Thanks

**Comment by mattdistefano** [comment]
The CLI already uses webpack, so you can't exactly *add* webpack to a CLI project, but you can initialize a project via the CLI then convert it to webpack via `ng eject`.

**Comment by clydin** [comment]
Something to note is that once you eject, the CLI no longer manages the build process.  So you are on your own in regards to the capabilities the CLI would otherwise provide you.

**Comment by capcar** [comment]
ok, thanks

**Comment by sumitarora** [comment]
Closing as per comments.
