### ISSUE TITLE
angular-cli package on npm should be deprecated in favor of @angular/cli

### ISSUE THREAD

**Issue by bonnici** [angular/angular-cli#5529]
Right now if you run a google search for "npm angular cli", the first result takes you to [angular-cli](https://www.npmjs.com/package/angular-cli) and [@angular/cli](https://www.npmjs.com/package/@angular/cli) is not visible in the results. Also in the angular-cli package page there is no mention of @angular/cli. I think this is pretty confusing and the package should be deprecated or the readme should be updated to point at the new @angular/cli package.

**Comment by Nikki1993** [comment]
Package has been already deprecated. It throws a big console warning that you should use @angular/cli instead. 

Github readme is update and points to the right installation. As to NPM package readme, afaik it pulled the data from the old GitHub so I am not sure that's possible to edit, but I agree the deprecation warning has been there for a while now, however, I assume Angular CLI team is waiting for a 1.x stable release to completely remove angular-cli.

**Comment by bonnici** [comment]
I'm thinking more just about the first-time user experience of hearing about Angular CLI, searching for it, installing it, then getting a message about needing an update and having to do a full uninstall and reinstall.

**Comment by filipesilva** [comment]
@hansl is there anyway we can change the README present in npmjs.com?
