### ISSUE TITLE
ng eject produces a source-map-loader rule which doesn't correctly exclude node_modules on Windows

### ISSUE THREAD

**Issue by SaltyDH** [angular/angular-cli#5530]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0-rc.2
node: 7.5.0
os: win32 x64
@angular/cli: 1.0.0-rc.2
@angular/common: 4.0.0-beta.5
@angular/compiler: 4.0.0-beta.5
@angular/compiler-cli: 4.0.0-beta.5
@angular/core: 4.0.0-beta.5
@angular/forms: 4.0.0-beta.5
@angular/http: 4.0.0-beta.5
@angular/platform-browser: 4.0.0-beta.5
@angular/platform-browser-dynamic: 4.0.0-beta.5
@angular/platform-server: 4.0.0-beta.5
@angular/router: 4.0.0-beta.5
@angular/upgrade: 4.0.0-beta.5

### Repro steps.
I ran ng eject which correctly produced my webpack config

### The log given by the failure.
Upon running webpack, a number of warnings were produced indicating that a source file was not found.

Ex. `WARNING in ./~/ag-grid-angular/main.js
Cannot find source file 'main.ts': Error: Can't resolve './main.ts' in '<Path redacted>\node_modules\ag-grid-angular'
 @ ./app/app.module.ts 23:0-52
 @ ./app/main.ts
 @ multi ./app/main.ts`

Looking at the generated source-map-loader rule, it attempts to exclude the node_modules folder using the following regex:

`"exclude": [
                    /\/node_modules\//
                ]`

This pattern doesn't seem to work correctly on Windows. For my setup at least, the rule is expecting forward slashes but webpack is trying to path match on backslashes.

### Desired functionality.
The following alternative regex correctly excludes the node_modules folder for this rule.

`"exclude": [
                    /[\/\\]node_modules[\/\\]/
                ]`

**Comment by Nandan108** [comment]
I experience pretty much the same issue, although I did not `ng eject`:
`Cannot find source file 'main.ts': Error: Can't resolve './main.ts' in <Path redacted>/node_modules/ag-grid-angular'
 @ ./src/app/app.module.ts 21:0-52
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
`
This error shows up on `ng build`, but not if `-prod` or `-aot`.

**Comment by clydin** [comment]
`source-map-loader` is no longer used and therefore no longer present in the ejected config.
