### ISSUE TITLE
Can use angular-cli build a standalone ng2 module and deploy it to npm?

### ISSUE THREAD

**Issue by dequn** [angular/angular-cli#5533]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions
1.0.0-rc.2

### Repro steps.
None.

### The log given by the failure.
None.

### Desired functionality.
As the title described, can add a feature to angular-cli that I can use it to build a standalone module and deploy it to npm conveniently.

**Comment by hansl** [comment]
Unfortunately, we do not support building libraries yet.

**Comment by matheuscaldasrj** [comment]
still not supported?? Without angular cli, what would be the best way to do it?

**Comment by dequn** [comment]
Yes, you can refer to NPM doc, just do it like a normal npm lib,  it's also very easy.
