### ISSUE TITLE
Less Sourcemap only references files inside 'styles' config

### ISSUE THREAD

**Issue by cvharris** [angular/angular-cli#5534]
### Bug Report or Feature Request
```
- [x] bug report
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0-rc.2
macOS El Capitan

### Repro steps.

My `angular-cli.json`:
```
 "styles": [
        "styles.less"
      ],
```
My `styles.less`
```
@import "less/vars";
@import "less/base";
@import "less/layout";
// ...etc.
```
When I run `ng serve -ec -sm` I can see the sourcemap file generated, but Chrome's devtools lists `styles.less` as the sole source file instead of `base.less` or `layout.less`, etc.

### The log given by the failure.

Here's what I skimmed out of the generated sourcemap file. You can see there's no mention of the imported files whatsoever.
```
{"version":3,"sources":["webpack:///./src/styles.less"], ... \n\n\n\n// WEBPACK FOOTER //\n// ./src/styles.less"],"sourceRoot":""}
```

### Desired functionality.

I should see the individual imported files in the Chrome devtools and not just the main file.

### Mention any other details that might be useful.

Wonder if this is solved by today's release of [less-loader v4.0.0](https://github.com/webpack-contrib/less-loader/releases/tag/v4.0.0)?

**Comment by cvharris** [comment]
I was able to verify that this is still an issue on new 1.0.0 projects using Less as the preprocessor.

**Comment by mgechev** [comment]
@cvharris would you check the latest Angular CLI release?

**Comment by mgechev** [comment]
Closing the issue due to inactivity. If the problem still exists in the latest version of the CLI, please open a new issue following the template and providing a minimal demo where we can reproduce it. Thanks! :-)
