### ISSUE TITLE
Error while creating new project with angular-cli

### ISSUE THREAD

**Issue by parmpreet** [angular/angular-cli#5535]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0-rc.4
node: 7.0.0
os: darwin x64 macos Sierra
npm: 4.4.1

### Repro steps.

ng new app_name

### The log given by the failure.

npm ERR! code ETARGET
npm ERR! notarget No compatible version found: append-transform@^0.4.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.4.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'istanbul-lib-hook'

### Desired functionality.

Initialize new angular app

**Comment by Nikki1993** [comment]
As a workaround you can use `yarn install ` which will prompt you to select valid version for the installation.

**Comment by tiratano** [comment]
Even though I can choose valid version, I have the same problem here. :<

Couldn't find any versions for "append-transform" that matches "^0.4.3"

**Comment by parmpreet** [comment]
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli

fixed this issue for me

**Comment by filipesilva** [comment]
This sounds like a problem with a third party lib that released a version with bad deps. That reinstalling fixed the issue supports this theory.

**Comment by rajsuvariya** [comment]
I am getting the same error in existing project while updating packages with npm install
