### ISSUE TITLE
The Return of ERROR in AppModule is not an NgModule with Angular-Cli rc4

### ISSUE THREAD

**Issue by Nikki1993** [angular/angular-cli#5536]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0-rc.4
node: 7.7.3
os: darwin x64
@angular/cli: 1.0.0-rc.4
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/compiler-cli: 2.4.10
@angular/core: 2.4.10
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10

### Repro steps.
1. Update CLI
2. Update Typescript to version higher than 2.0.10 (prior to rc4 I ran 2.2.1 with no issues)
3. run yarn install
4. ng serve will result in AppModules is not a NgModule

### Desired functionality.
You can continue to use the latest typescript as you could before with rc2

### Mention any other details that might be useful.
As mentioned previously, this appears to be a regression in the cli as I could run the latest typescript with cli rc2 before the upgrade so smth must have broken the compatibility along the way.

**Comment by ajinkyau** [comment]
In my case after updating cli locally, I did "yarn" to install dependencies and encountered the same issue.

However when I removed the "node_modules" folder and did npm install instead of "yarn" and then tried to serve the application using "ng serve" it works fine.

**Comment by Nikki1993** [comment]
I see, so certain commit caused yarn breakage then. I just reverted to rc2 and tested it with yarn, everything works as expected.

**Comment by filipesilva** [comment]
Angular 2.x does not support typescript 2.1+ (for the purposes of AOT/statical analysis). If you had a setup that worked before, it's probably because yarn was installing 2.0 and you didn't notice.

**Comment by coryrylan** [comment]
Just ran into this as well. On CLI RC2 everything works but with CLI RC4 I get the  `AppModule is not an NgModule `

**Comment by Nikki1993** [comment]
@filipesilva that can't be possible or very weird. I nuke my node_modules and yarn.lock file with each cli upgrade. It's even listed as typescript 2.2.1 in the package.json when I initiate yarn install. In any case, I guess I am back on 2.0.10.
