### ISSUE TITLE
Changelog or Release Notes

### ISSUE THREAD

**Issue by vapits** [angular/angular-cli#554]
Hi there guys and once more thanks for your awesome work!

I do believe that a Changelog file or at least some Release Notes or releases tags would be awesome for people that are using for test or even production purposes.

As the project is still to young IMO Release Notes are important in order to know what bugs was solved and what new features are added to each version so the user can decide if he'll upgrade his version etc.

This is something that it very difficult for someone who's not in the team to implement and make a PR. If the knowledge on this is somehow shared I'll be more than happy to help.

Regards

**Comment by filipesilva** [comment]
The idea is to, post ng-conf, both provide patch notes and also provide a `ng upgrade` command that would help users upgrade existing projects to both new versions of the CLI and new Angular 2 versions.

So in a couple of weeks, this issue should be addressed promptly.

**Comment by vapits** [comment]
That's great!
