### ISSUE TITLE
FR: Diagnostic tool suite

### ISSUE THREAD

**Issue by moniuch** [angular/angular-cli#5541]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

I would welcome a set of project diagnosis tools, that would especially be helpful during migration to a higher angular-cli version. It's just an example of two tests that I would have recently found useful to have:

- being able to diagnose the project integrity, eg. presence and structure of angular-cli.json file (I had problems after migration to .angular-cli.json)
- being able to verify AoT integrity

These two might not seem enough for now to implement the feature, but over time I would really see a big benefit to the users in having such a diagnostic module. An instruction on environmentSources is an example of where it becomes a true value.

Hope more people find it useful and perhaps could add more examples for the test cases.

**Comment by filipesilva** [comment]
We are designing a full fledged upgrade command that would do this (and more) for 2.0.
