### ISSUE TITLE
Can't use '# ng init'

### ISSUE THREAD

**Issue by leduong** [angular/angular-cli#5543]
![screenshot from 2017-03-21 21-08-00](https://cloud.githubusercontent.com/assets/1042749/24151187/9618bdcc-0e7a-11e7-9f7e-f5afdf7c73fe.png)

**Comment by RicardoVaranda** [comment]
ng init has been removed in a recent release, please read more on it here:
https://github.com/angular/angular-cli/issues/5176

**Comment by leduong** [comment]
Hi!

How to create new a project with angular-cli?

![screenshot from 2017-03-21 21-15-27](https://cloud.githubusercontent.com/assets/1042749/24151500/900cba90-0e7b-11e7-85ab-5f511f9130b0.png)

**Comment by sumitarora** [comment]
`ng new <project name>` check `ng new --help` for more details

**Comment by leduong** [comment]
Hi
Are you check? You look the last picture, i try with "ng new PROJECT_NAME"

**Comment by Equinox** [comment]
Check if you have any stray package.json files in the files above that one you're trying it in.

**Comment by leduong** [comment]
Hi @Equinox 
It's empty, you look that picture, "ls -la"
