### ISSUE TITLE
Proxy for third party library don't work 

### ISSUE THREAD

**Issue by sergeu90** [angular/angular-cli#5549]
I have got js file which do query.but proxy don't work but with typescript in Angular all right

**Comment by coryrylan** [comment]
@sergeu90 please follow the issue submission guidelines https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#submit

**Comment by filipesilva** [comment]
^ what @coryrylan said 💃 

The new issue template contains all that's needed, please do fill it out on a new issue.
