### ISSUE TITLE
Enable user-defined blueprints/templates

### ISSUE THREAD

**Issue by thorstenschaefer** [angular/angular-cli#556]
Currently Angular2 CLI provides a fixed set of blueprints to generate. A reoccurring pattern I have seen while using CLI is that I create a service using "ng g service MyService", get the stub which is pretty empty, and then perform similar modifications every time. 

For instance, if we create services for REST CRUD operations, they follow a certain pattern:
- we have a constant for the URL
- we need to import Observable and Http
- we have methods like get<EntityName>s, delete<EntityName>, create<EntityName>, etc.

Is there something like a plugin-model/extension point where I can provide my own blueprints to generate and register them to CLI, so I could perform the command "ng g crud-service MyCrudService" in the example above?

**Comment by filipesilva** [comment]
Well, `angular-cli` actually uses `ember-cli` which is very extensible and would allow for that. For now though, we haven't plugged it in such as way as to be very extensible but you could hypothetically do that *right now* with an ember-cli plugin.

I just can't guarantee that it'd be well supported - or supported at all - in the future. Check out the extending bit of http://ember-cli.com/.

**Comment by billfranklin** [comment]
@thorstenschaefer, couldn't you modify the __name__.service.ts file to put the changes you want to always be there?

**Comment by thorstenschaefer** [comment]
@billfranklin: I'm not sure if I understand your suggestion: are you recommending changing the blue print file? If so, it would probably be possible for the use case above, but imagine I have 3 kinds of services (the regular one, services that use REST APIs and old school web services), I'd have to choose between a single service template. User-defined additions would enable users to add n templates depending on their needs.
