### ISSUE TITLE
angular-cli RC3 or RC4 ?

### ISSUE THREAD

**Issue by GulajavaMinistudio** [angular/angular-cli#5561]
What's the current version of this CLI ? i check commit message, it's "v1.0.0-rc.3" , but in changelog, i see "1.0.0-rc.4 (2017-03-20)" ? 

Is this some kind of typo or what ?

**Comment by filipesilva** [comment]
The latest version is rc.4. There was a problem publishing the rc.3 git tag so it was republished as rc.4.
