### ISSUE TITLE
`npm test` from a cli app broke my chrome.desktop shortcut

### ISSUE THREAD

**Issue by zladuric** [angular/angular-cli#5565]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.0.0-rc.2
node: 6.9.0
os: linux x64 (Ubuntu 16.04 + up-to-date Unity)
browser: Google Chrome Version 56.0.2924.87 (64-bit)
```

### Repro steps.

I've wanted to check out ng-cli and angular material, now that it's out, so I went and installed ng-cli and started a test app. I've also launched the tests (`npm test`), which opens that karma chrome launcher - that is, a no-profile chrome outside of my regular user profile.

After that, each time I've opened Chrome (from Ubuntu launcher) or a new window from an existing session, it would open that test url at `http://localhost:9876/?id=61917528`. That was quite anoying, I found the `npm test` terminal, quit that too, exited Chrome completely, but the behavior completed. I've then launched chrome from console, and it didn't happen - my regular user profile was open. So I've suspected the `chrome.desktop` desktop shortcut was altered, and checked, and it was indeed the case.

I cannot remember the exact steps: I might have quit my regular chrome window(s), then the `ng test` window - or some such order.

So, the approximate steps:

1. Install ng-cli.
2. Create a dummy app and install packages.
3. Make minimal change to package.json (install angular material).
4. Run `ng serve` in one terminal
5. Run `npm test` in another terminal.
6. Quit Chrome (both the test window and the regular Chrome window)
7. Find the `Exec` line in `.local/share/applications/chrome.desktop` altered, even after I quit the `ng serve` and `npm test`, to launch chrome with `--no-profile` and other options, and open the test url: `http://localhost:9876/?id=61917528`

### The log given by the failure.

N/A

### Desired functionality.

Desired functionality is to return my chrome.desktop to original state - or better yet, don't even modify it in the first place.

But I'm posting this issue more to kick off discovery - was it something that I did that has caused this? Have any other people had this case (search through the issues didn't bring up anything)? I guess it's probably not directly related to Angular, but it still might be worth looking into or noting here.

Also, where would I go next - to Chrome or Ubuntu forums - to find out more about this?

### Mention any other details that might be useful.

_Edit:_ This might be useful - the specific line that I get inserted in my chrome.desktop app launcher is this:

    Exec=/opt/google/chrome/chrome --user-data-dir=/tmp/karma-63694901 --no-default-browser-check --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate --disable-background-timer-throttling --disable-device-discovery-notifications http://localhost:9876/?id=63694901
-- 
Zlatko

**Comment by filipesilva** [comment]
Huh, I don't know what happened there. The CLI doesn't interact with chrome per se... `npm test` is running https://github.com/webpack-contrib/karma-webpack. There might be a bug there somewhere.

**Comment by xoanteis** [comment]
Exactly the same happened to me in Ubuntu.

**Comment by zladuric** [comment]
@xoanteis, maybe you can add some details in the linked issue at the karma launcher issue tracker?

**Comment by lastboy** [comment]
I had the same weird behavior.

Probably, if you'll lookup in the following folder ~/.local/share/applications you'll be amazed to find a new google-chrome.desktop launcher. In this file there's Karma settings that overrides the one in /usr/share/applications folder   
All you have to do is delete this file. 

It all started when I added `--open` option to  `ng serve` command that opened the chrome browser with karma URL http://localhost:9876... I thought this is a CLI issue

I cannot tell how the local launcher was created.

Hope that helps

**Comment by zladuric** [comment]
@lastboy yes, I did delete that, but it got recreated. After reboot. (or before, I don't know). That's part of the problem.

**Comment by filipesilva** [comment]
Please follow https://github.com/karma-runner/karma-chrome-launcher/issues/112 for more information about this issue.
