### ISSUE TITLE
Installation issue, unable to run commands

### ISSUE THREAD

**Issue by bviale** [angular/angular-cli#5569]
[x] bug report

Hi, I wanted to give a try at angular-cli, but after installing it with npm the tools seems to be broken, I'm not event able to run `ng --version`.

### Versions.
C:\Users\xxx\xxx\Angular2>node --version
v4.4.5

C:\Users\xxx\xxx\Angular2>npm --version
4.2.0

### Repro steps.
`ng --version`

### The log given by the failure.

> C:\Users\xxx\xxx\Angular2>ng --version
> C:\Users\xxx\AppData\Roaming\npm\node_modules\@angular\cli\models\config\config.js:16
>     constructor(_configPath, schema, configJson, fallbacks = []) {
>                                                            ^
> 
> SyntaxError: Unexpected token =
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\@angular\cli\models\config.js:3:18)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)

**Comment by clydin** [comment]
The required node version is 6.9 or greater.

**Comment by filipesilva** [comment]
Closing as answered by @clydin 👍

**Comment by bviale** [comment]
That's right, thank you
