### ISSUE TITLE
ng build: Cannot read property 'stateChangeExpr' of null , ng serve is OK

### ISSUE THREAD

**Issue by uf4b** [angular/angular-cli#5573]
Hi
When I'm running the app with ng serve , it compiles without errors, but when I build for production I get this error

### Versions
@angular/cli: 1.0.0-rc.0
node: 7.0.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

### Console output
Hash: 0e78f043bbd732e8b010                                                              
Time: 46558ms
chunk    {0} polyfills.e92502d0e1d036701b5e.bundle.js (polyfills) 199 kB {5} [initial] [rendered]
chunk    {1} main.fc755cdcc1507cc22ae8.bundle.js (main) 1.97 kB {4} [initial] [rendered]
chunk    {2} scripts.db891f10370c00a89c7d.bundle.js (scripts) 28.9 kB {5} [initial] [rendered]
chunk    {3} styles.be4f1a7ed5b36274c3d2.bundle.css (styles) 122 bytes {5} [initial] [rendered]
chunk    {4} vendor.0d067de8c0a25625ad14.bundle.js (vendor) 1.03 MB [initial] [rendered]
chunk    {5} inline.c6d90cdc4fb73c8982a1.bundle.js (inline) 0 bytes [entry] [rendered]

**ERROR in Cannot read property 'stateChangeExpr' of null

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/module.ngfactory' in '/Users/fabio/Sites/cordova.apps/app.ng2test/src'
 @ ./src/main.ts 5:0-70
 @ multi ./src/main.ts**

The last time it was built without errors I had another kind of structure of the app,  now I changed the structure using a more better module separation .. But ng serve works!

There is not any clear indication of where to investigate in term of number of line ..  

Any ideas of the problem?

Thanks in advance

**Comment by maxime1992** [comment]
@uf4b you closed this issue yourself, have you found a fix ? 

I think I might have something similar and would appreciate any help :smile:

**Comment by codelovesme** [comment]
Me either. Please share your steps ?

**Comment by uf4b** [comment]
@maxime1992  @codelovesme  Sorry for late reply, I forgot to mention the error 😅
The error was thrown because of a wrong module path in my imports.
While running the app with ng serve the wrongly imported module was not requested by components, so no error was shown , but building with ng build all the code and imports have been checked then the attempt to load the wrong path has thrown the mentioned error. 
Be sure you haven't some hidden wrongly imported module somewhere in the project code. 
Hope that helps!

**Comment by paqogomez** [comment]
This error occurred for me when I had version 4.1.0 of @angular/animations, but earlier versions of @angular/core, compiler, common etc.

Updating everything to the same version (4.1.0) fixed it for me.
