### ISSUE TITLE
Need a flag for not creating new folder while generating new module

### ISSUE THREAD

**Issue by afganhalbana** [angular/angular-cli#5578]
Hey guys since the documentation for angular style guide told us to use *-routing as a suffix for routing, i thought we need a flag to determine whether it is necessary to generating a module into a new folder or not or it could be an auto detect feature to our module name, like whenever encountered the suffix while generating a module it wont created any new folder, thanks.

**Comment by afganhalbana** [comment]
sorry ive found that while creating new module it also creating a module for routing too.

**Comment by clydin** [comment]
`--routing` will generate a routing module along with the module.

For further option information:
https://github.com/angular/angular-cli/wiki/generate-module

**Comment by afganhalbana** [comment]
worked as excpected 👍 sorry that ive missed that one tho, thanks @clydin

**Comment by afganhalbana** [comment]
Hi @clydin, i got one question left, is there any way to generate multiple components in one command?

**Comment by clydin** [comment]
No, sorry.

https://github.com/angular/angular-cli/wiki/generate-component
