### ISSUE TITLE
Auto version suffix on global libraries

### ISSUE THREAD

**Issue by koen-serneels** [angular/angular-cli#5581]
As explained in the [docs](https://www.npmjs.com/package/angular-cli#global-library-installation) global scoped libraries can be included in the package and loaded via the script option. But is there a way to control the auto suffixing of the included libraries one way or the other? If we now run the build we get auto suffixed application bundles, but the included libraries do not get this kind of suffix

**Comment by filipesilva** [comment]
I'm sorry, what suffix do you mean? Can you give me an example?

**Comment by filipesilva** [comment]
Closing as inactive.
