### ISSUE TITLE
ng generate page-object

### ISSUE THREAD

**Issue by Slevender** [angular/angular-cli#5584]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

ng generate page-object

Generate page-object based on templates or components for e2e testing. Any plans to create such a feature?

**Comment by filipesilva** [comment]
No plans currently. Will label as a feature request to be considered. It's probably the kind of thing that will be an addon, once the addon system is in.

**Comment by szmeti** [comment]
We have a tool that can generate Protractor page objects for AngularJS and Angular applications. You can check it out here:
[pageobject.io](url)
https://github.com/pageobject-io

We would be happy to integrate it with the CLI as an addon.

**Comment by filipesilva** [comment]
This is generally being tracked in https://github.com/angular/angular-cli/issues/2618.
