### ISSUE TITLE
cannot find module 'abbrev' after installation of Angular CLI RC4

### ISSUE THREAD

**Issue by mattalco** [angular/angular-cli#5588]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
![image](https://cloud.githubusercontent.com/assets/13972013/24251029/2cbd54d8-0faf-11e7-9d37-a6b27c0f5695.png)

Ubuntu 16.04

node -v
v6.10.1

npm -v
3.10.10

### Repro steps.
run npm install -g @angular/cli@latest
run ng -v

**Comment by filipesilva** [comment]
I think this is a dupe of an old issue: https://github.com/angular/angular-cli/issues/1190. It seems to be a problem with npm.

**Comment by yabbes** [comment]
I also had this same problem what I did to fix it on Linux Mint:

- change ownership of /usr/lib/node_modules to my user to stop executing npm with sudo as this is highly discouraged. 
- run npm uninstall -g @angular/cli and npm cache clean (--force) 
- check if ~/.npm was clean, else rm -rf ~/-npm
- try reinstalling npm install -g @angular/cli
- go to ...node_modules/angular-cli and run npm install
- run npm install --save-dev @angular/cli@latest
- and finally i can run ng -v with no error.. 

but this was quite a lot of trouble I faced lol, I'm posting this here so maybe it helps other people
