### ISSUE TITLE
rc.4 error. with lodash

### ISSUE THREAD

**Issue by tonymk** [angular/angular-cli#5592]
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0-rc.4
node: 6.9.5
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.4
@angular/compiler-cli: 2.4.10

### Repro steps.
ng new
npm install --save lodash
npm install --save-dev @types/lodash

add import * as _ from 'lodash' too app.component.ts

ng serve

### The log given by the failure.
ERROR in C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,21): ']' expected.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,22): ';' expected.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,23): Declaration or statement expected.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,33): ']' expected.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,34): ')' expected.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,35): Declaration or statement expected.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,37): Declaration or statement expected.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19499,1): Declaration or statement expected.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (244,13): Duplicate identifier '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (248,19): Duplicate identifier '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (244,16): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (246,25): Cannot find name 'Partial'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (366,39): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (2083,24): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5636,44): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5643,44): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5650,44): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5657,44): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5690,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5699,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5706,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5713,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5722,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5729,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5736,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5745,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5752,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5759,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5768,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5775,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (5782,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,9): A computed property name must be of type 'string', 'number', 'symbol', or 'any'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,10): Cannot find name 'P'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,15): Cannot find name 'keyof'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,21): Cannot find name 'T'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,26): A parameter initializer is only allowed in a function or constructor implementation.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,31): Cannot find name 'T'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11502,40): Cannot find name 'boolean'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11511,29): Cannot find name 'ConformsPredicateObject'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (11522,42): Cannot find name 'ConformsPredicateObject'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (12762,29): Cannot find name 'object'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15452,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15461,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15494,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15503,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15538,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15547,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15580,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15589,12): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15622,22): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15629,22): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15662,24): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15669,24): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15685,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15694,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15704,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15714,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15724,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15734,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15744,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15754,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15789,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15797,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15804,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15836,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15844,21): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15851,21): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15914,21): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15914,37): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (15930,21): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16591,33): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16601,33): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16611,33): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16680,33): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16689,33): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16698,33): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16758,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16767,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16777,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16787,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16797,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16807,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16817,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16827,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16846,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16855,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16864,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16874,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16882,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16892,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16900,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16922,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16932,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16942,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16953,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16962,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16973,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (16982,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (17139,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (17147,21): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (17154,21): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (17170,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (17179,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (17188,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (17197,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (17207,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (17215,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (17225,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (17233,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (17984,39): Cannot find name 'TemplateSettings'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18604,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18612,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18734,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18742,19): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18751,47): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18760,47): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18876,31): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18913,43): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18920,43): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18927,43): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18934,43): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18941,43): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18953,40): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18960,40): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18967,40): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18974,40): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18981,40): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (18993,39): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19000,39): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19007,39): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19014,39): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19021,39): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19032,39): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19072,53): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19079,58): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19086,58): Cannot find name 'Many'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19246,22): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19270,22): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19293,23): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19316,23): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19339,21): Cannot find namespace '_'.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19507,15): All declarations of 'WeakMap' must have identical type parameters.)
C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19507,33): Cannot find name 'object'.)

**Comment by jonaslalin** [comment]
You can downgrade the `@types/lodash` dependency to `ts2.0`, i.e.,
```
"dependencies": {
	"@types/lodash": "ts2.0",
	"lodash": "^4.17.0"
}
```

**Comment by filipesilva** [comment]
Closed as answered by @jonaslalin, good job tracking it down! There's a fair number of `@types/` packages that are not compatible with ts2.0 anymore...

**Comment by tonymk** [comment]
With @types/lodash": "ts2.0", still produces an error: 

ERROR in C:/Users/tony.kroger/Projects/admit-controller/node_modules/@types/lodash/index.d.ts (19417,15): All declarations of 'WeakMap' must have identical type parameters.

found an issue on it in @types/lodash
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15316

And version @types/lodash@4.14.57 (latest atm.) fixed the issue for me.
