### ISSUE TITLE
1.0.0-rc.4: is ng lint broken and trying to fix things by default?!

### ISSUE THREAD

**Issue by victornoel** [angular/angular-cli#5593]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.0.0-rc.4
node: 6.10.0
os: linux x64
@angular/animations: 4.0.0-rc.6
@angular/common: 4.0.0-rc.6
@angular/compiler: 4.0.0-rc.6
@angular/core: 4.0.0-rc.6
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.0.0-rc.6
@angular/http: 4.0.0-rc.6
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0-rc.6
@angular/platform-browser-dynamic: 4.0.0-rc.6
@angular/router: 4.0.0-rc.6
@angular/cli: 1.0.0-rc.4
@angular/compiler-cli: 4.0.0-rc.6
```

### Repro steps.

I left a tslint error in a file (an unused import, I enabled `"no-unused-variable": [true, {"ignore-pattern": "^_"}]` in `tslint.json`)

When I run ng lint, I get the following:
``` sh
$ ng lint
Fixes caused errors in /home/vnoel/Linagora/Petals/dev/git/petals-cockpit-new/frontend/src/app/core/core.module.ts
All files pass linting.
```

### Desired functionality.

I would expect the linting not to pass AND not seeing this warning in the logs…

### Mention any other details that might be useful.

I guess there could be some links to #5406 which would explain why it can't fixes the error… but it shouldn't even try anyway :)

**Comment by sumitarora** [comment]
@victornoel Can you provide repo with the issue or file in which you have lint error?

**Comment by victornoel** [comment]
You can reproduce it by running `ng lint` in the `frontend` directory
(after running `yarn` or `npm install`) of
https://gitlab.com/linagora/petals-cockpit/tree/front/upgrade-angular-deps
Note the branch, it is not on master!

Thanks :)

**Comment by victornoel** [comment]
Seems to be fixed with v1.0.0

With the tslint error:
```
$ ng lint

/home/vnoel/Linagora/Petals/dev/git/petals-cockpit-new/frontend/src/app/core/core.module.ts[22, 1]: Unused import: 'import { StoreDevtoolsModule } from '@ngrx/store-devtools';'

Lint errors found in the listed files.
```

Without:
```
$ ng lint
All files pass linting.
```

All as expected!

**Comment by filipesilva** [comment]
@victornoel glad to hear this was fixed for you! I thought that @sumitarora's https://github.com/angular/angular-cli/pull/5589 would fix it but I couldn't be sure.

**Comment by victornoel** [comment]
@filipesilva that's why ng lint is much faster now, type checking was disabled!

But then, enabling type checking shouldn't generate this output when there is a tslint error then
```
$ ng lint --type-check
Fixes caused errors in src/app/features/cockpit/workspaces/api-content/api-content-routing.module.ts
All files pass linting.
```

So I will reopen this issue :)

**Comment by filipesilva** [comment]
That's fair. Can you tell me if that also happens when just running `tslint` with the project tsconfig and type check on?

**Comment by victornoel** [comment]
@filipesilva yep it does:
```sh
$ ./node_modules/.bin/tslint --project src/tsconfig.app.json --type-check --exclude "**/node_modules/**"
Fixes caused errors in /home/victor/code/eclipse/petals-cockpit/frontend/src/app/core/core.module.ts
```

**Comment by filipesilva** [comment]
So then I think it's a `tslint` bug, right? We're just running tslint and it seems to be broken in this scenario.

**Comment by victornoel** [comment]
yep, you are right, or even maybe a codelyzer bug, who knows... I will open an issue there after investigating a bit to find the potential source.

**Comment by victornoel** [comment]
Here it is palantir/tslint#2400, thanks for your guidance @filipesilva, you can close this issue now or I will do it when the tslint one is fixed, as you desire :)

**Comment by filipesilva** [comment]
I read through that thread and it seems that it's due to a rule that needs `--type-check` on. That's a tricky case... it requires users to know that their rules need it.

I think this specific issue is solved, but I'm glad you opened and followed through. Now we have a trail here for other users to follow.
