### ISSUE TITLE
ng generate component - TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by scotmeiste** [angular/angular-cli#5595]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0-rc.4
node: 6.9.5
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/compiler-cli: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/platform-server: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-rc.4

Windows 10

### Repro steps.

This project was started with the seed project, not the cli. I was trying to just add a component via the cli.

1. cd to directory i wanted to create the component in
2. run `ng generate component usersettings --flat --dry-run`

### The log given by the failure.

installing component
You specified the dry-run flag, so no changes will be written.
Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at Object.getAppFromConfig (C:\source\lg-mbc\src\MBC.LG.Web\node_modules\@angular\cli\utilities\app-utils.js:6:19)
    at Class.normalizeEntityName (C:\source\lg-mbc\src\MBC.LG.Web\node_modules\@angular\cli\blueprints\component\index.j
s:124:39)
    at Class.Blueprint._normalizeEntityName (C:\source\lg-mbc\src\MBC.LG.Web\node_modules\@angular\cli\ember-cli\lib\mod
els\blueprint.js:454:24)
    at Class.Blueprint.install (C:\source\lg-mbc\src\MBC.LG.Web\node_modules\@angular\cli\ember-cli\lib\models\blueprint
.js:513:8)
    at Class.run (C:\source\lg-mbc\src\MBC.LG.Web\node_modules\@angular\cli\ember-cli\lib\tasks\generate-from-blueprint.
js:59:49)
    at Class.run (C:\source\lg-mbc\src\MBC.LG.Web\node_modules\@angular\cli\ember-cli\lib\commands\generate.js:71:17)
    at Class.<anonymous> (C:\source\lg-mbc\src\MBC.LG.Web\node_modules\@angular\cli\ember-cli\lib\models\command.js:134:
17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Desired functionality.

generate component without errors

**Comment by filipesilva** [comment]
I have no idea what the seed project is. CLI projects really need to be generated by the CLI to work.

**Comment by scotmeiste** [comment]
Seed project is referenced in the docs. 

https://github.com/angular/quickstart

The cli didn't exist when the project was started. 

So the cli can't be used just to stub out a generic empty controller?

**Comment by scotmeiste** [comment]
It won't let me edit my previous comment....

I meant component not controller. :)

**Comment by filipesilva** [comment]
You can probably use only the generators as long as you have a `.angular-cli.json` with the right configuration for your project. Otherwise there's no way for the CLI to know what's your app folder and such.

Using the CLI on non-CLI projects isn't something we test for or explicitly support though.

**Comment by edenmanny25** [comment]
hello guys I believe  this is due to the feature  module 
just specify  with  ng g c module_name/components_name
if you have multiple modules

**Comment by Sevensnake** [comment]
I just stared having this problem using ng g component newfilename
worked one day now the next it stopped.
`Error: Cannot read property '0' of null
Cannot read property '0' of null`

**Comment by chriscurnow** [comment]
@Sevensnake Same here. Just this morning. Was working last week.

**Comment by gknight4** [comment]
One more. This is a project that is only a few days old, with no old versions that I'm aware of. I deleted a bunch of unused components (5), and now when I try to add a new one, I get:
Cannot read property '0' of null

This was create with CLI, and still runs fine with ng serve.

These are the current versions:
Angular CLI: 6.0.8
Node: 8.9.4
OS: linux x64
Angular: 6.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.2.1
@angular/cli                      6.0.8
@angular/material                 6.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

**Comment by gknight4** [comment]
This creates the error:

git clone https://github.com/gknight4/postops-angular\
cd postops-angular\
npm i\
ng serve (to verify that it runs OK)\
ng g component newone

result is:\
Cannot read property '0' of null

**Comment by Gerardlc** [comment]
Same problem here, What can we do?

**Comment by jasonwismer** [comment]
Is there no solution for this yet?  I'm getting the same issue.
