### ISSUE TITLE
ng serve fails after upgrading to rc4

### ISSUE THREAD

**Issue by tbarth17** [angular/angular-cli#5598]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Output from: `ng --version`
@angular/cli: 1.0.0-rc.4
node: 7.6.0
os: darwin x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.4
@angular/compiler-cli: 2.4.10

`npm --version`
4.1.2

### Repro steps.
Upgraded from angular-cli version 1.0.0-beta.30 to rc4, ng serve now outputs errors related to .spec files

ERROR in /src/app/campaigns/campaign-creator/campaign-creator-form.component.spec.ts (93,11): Supplied parameters do not match any signature of call target.)

ERROR in /src/app/content/content-creator/content-creator-form.component.spec.ts (72,9): Supplied parameters do not match any signature of call target.)

ERROR in src/app/triggers/trigger-creator/trigger-creator-form.component.spec.ts (62,11): Supplied parameters do not match any signature of call target.)

### Desired functionality.
ng serve and ng test continue to function as designed after upgrade to rc4

### Mention any other details that might be useful.
It seems that the tsconfig files have been separated into a few files in this rc, but upgrading the cli version doesn't generate the new config files.

**Comment by asiftasleem** [comment]
https://github.com/angular/angular-cli/issues/5559

It says that: 

CLI recently broke up the `tsconfig.json` into 4 files, a main `tsconfig.json` at the root of the project, `tsconfig.app.json`, `tsconfig.spec.json`, and `tsconfig.e2e.json`.

**Comment by yarrgh** [comment]
Have you created the 4 tsconfig files? Did you follow the [RC Update](https://github.com/angular/angular-cli/wiki/stories-rc-update)?

**Comment by tbarth17** [comment]
@yarrgh that's the document I was looking for, thank you!
