### ISSUE TITLE
getting message: Names must contain a dash either include a dash or multiCase name. (i.e. multiCase -> multi-case)

### ISSUE THREAD

**Issue by cmosguy** [angular/angular-cli#560]
I am filing a bug.

Using:
1. OS. Windows 7
2. Versions. 
angular-cli: 0.0.34
node: 5.2.0
os: win32 x64
npm: 3.3.12

3. Ran:
ng generate route welcome

4. Getting message:
Names must contain a dash either include a dash or multiCase name. (i.e. multiCase -> multi-case).

5. Mention any other details that might be useful.
So, it seems to me the cli changed and I do not understand why one would want to restrict routes or any other feature in angular to redistricted to multiple cases?  Please advise why this is being forced, otherwise, I would recommend take this out, unless there is a strong case for this.  There probably is and I need to understand the proper way here, but it is not clear in any other doc or tutorial besides this command

Thanks!
Adam

**Comment by Brocco** [comment]
This has been addressed via PR #544 and will be part of the next release of the CLI.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/544
