### ISSUE TITLE
on e2e tests -port flag does not work with --serve false

### ISSUE THREAD

**Issue by itslenny** [angular/angular-cli#5602]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.0.0-rc.4
node: 6.9.1
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.4
@angular/cli: 1.0.0-rc.4
@angular/compiler-cli: 2.4.10
```

### Repro steps.

If you run `ng e2e -port 1234 --serve false` the e2e tests still run against the default port (4200). If you use `ng e2e -port 1234` without the `--serve false` flag it works fine.

### The log given by the failure.

No errors. It just runs on the wrong port

### Desired functionality.

This should start the e2e tests against a server running on the specified port.

The use case is to run pre-built e2e tests against my own http server (instead of having it run `ng serve` internally)

### Additional info

On a loosely related note the flags are defined in ng help as specified above (some single - some double --). They all work with either, but the help screen should be consistent.

**Comment by filipesilva** [comment]
Yeah that's fair. It's a flag combo that I didn't correctly allow for. Will fix.
