### ISSUE TITLE
windows 10 Package install failed, see above

### ISSUE THREAD

**Issue by bodekbeska** [angular/angular-cli#5611]
### Versions.
npm --version
3.10.9
node --version
v6.9.2
ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.9.2
os: win32 x64

uninstalled node and cli then updated cli.
ran **ng new a4**
this is the result: 
installing ng
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Directory is already under version control. Skipping initialization of git.
Installing packages for tooling via npm.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--quiet" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path C:\Users\nick\Desktop\a4\node_modules\.staging\rxjs-28ca1497
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nick\Desktop\a4\node_modules\.staging\rxjs-28ca1497' -> 'C:\Users\nick\Desktop\a4\node_modules\rxjs'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nick\Desktop\a4\node_modules\.staging\rxjs-28ca1497' -> 'C:\Users\nick\Desktop\a4\node_modules\rxjs'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\nick\Desktop\a4\node_modules\.staging\rxjs-28ca1497' -> 'C:\Users\nick\Desktop\a4\node_modules\rxjs'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nick\Desktop\a4\node_modules\.staging\rxjs-28ca1497' -> 'C:\Users\nick\Desktop\a4\node_modules\rxjs'
npm ERR!     at Error (native) parent: 'a4' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nick\Desktop\a4\npm-debug.log

Package install failed, see above.
Not sure what's going. All i did was update the cli and now I can't create a new project

**Comment by RicardoVaranda** [comment]
Hi @bodekbeska ,

According to these lines it seems you are trying to run the command with a directory which already exists and throws errors when it tries to rename files since you do not have permissions to do so:

```
Directory is already under version control. Skipping initialization of git.

...

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nick\Desktop\a4\node_modules.staging\rxjs-28ca1497' -> 'C:\Users\nick\Desktop\a4\node_modules\rxjs'
```

Could you try generating a project with a different name and/or run the Command Prompt as administrator and report back, Thank you 👍

**Comment by filipesilva** [comment]
You got a bunch of permissions errors there. If I had to bet, you're running `ng serve` (or an editor that's watching files) on a project already, and then you tried to make a new project on top of that one. Either way, it's all about the permissions and file watchers.

**Comment by bodekbeska** [comment]
rebooted computer. made sure no other ng processes is running. opened command prompt as administrator. ran ng new newProjectName. still getting this error.
C:\Users\nick\Desktop>ng new newproject
installing ng
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Directory is already under version control. Skipping initialization of git.
Installing packages for tooling via npm.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--quiet" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path C:\Users\nick\Desktop\newproject\node_modules\.staging\rxjs-c0e1698f
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nick\Desktop\newproject\node_modules\.staging\rxjs-c0e1698f' -> 'C:\Users\nick\Desktop\newproject\node_modules\rxjs'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nick\Desktop\newproject\node_modules\.staging\rxjs-c0e1698f' -> 'C:\Users\nick\Desktop\newproject\node_modules\rxjs'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\nick\Desktop\newproject\node_modules\.staging\rxjs-c0e1698f' -> 'C:\Users\nick\Desktop\newproject\node_modules\rxjs'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nick\Desktop\newproject\node_modules\.staging\rxjs-c0e1698f' -> 'C:\Users\nick\Desktop\newproject\node_modules\rxjs'
npm ERR!     at Error (native) parent: 'newproject' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nick\Desktop\newproject\npm-debug.log

Package install failed, see above.

C:\Users\nick\Desktop>

please assist

**Comment by RicardoVaranda** [comment]
@bodekbeska There are several external causes that can be causing this so sadly it's not trivial, Could you try and temporarily disable your antivirus and also running `npm cache clean` before the npm install.

**Comment by bodekbeska** [comment]
hi. just to add on. i tried on a different directory and still got the same error. the only difference is I got "Successfully initialized got."
![capture](https://cloud.githubusercontent.com/assets/6441054/24303609/d954e7c8-1073-11e7-888a-77f23fa01856.JPG)
. i will try the npm cache clean again and disable antivirus software. i will get back to you

**Comment by bodekbeska** [comment]
Hi. ran npm cache clean and disabled windows defender. that seemed to work. weird. thank you so much! this only happened after i updated to the latest cli.

**Comment by john-dempsey** [comment]
I am trying to run the command

ng new ng4

I am getting the same error:

```
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\John\Documents\ng4\node_modules\.staging\rx-13071a3d' -> 'C:\Users\John\Documents\ng4\node_modules\rx'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\John\Documents\ng4\node_modules\.staging\rx-13071a3d' -> 'C:\Users\John\Documents\ng4\node_modules\rx'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\John\Documents\ng4\node_modules\.staging\rx-13071a3d' -> 'C:\Users\John\Documents\ng4\node_modules\rx'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\John\Documents\ng4\node_modules\.staging\rx-13071a3d' -> 'C:\Users\John\Documents\ng4\node_modules\rx'
npm ERR!     at Error (native) parent: 'ng4' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\John\Documents\ng4\npm-debug.log
```
I am using node 6.10.2, npm 3.10.10, and @angular/cli: 1.0.0

I have disabled Windows Defender, run npm cache clean, run above command in cmd window as Administrator. I have logged out of iCloud and SkyDrive just in case. npm debug log attached.

Any suggestions would be welcome. Thanks in advance.

[npm-debug.log.txt](https://github.com/angular/angular-cli/files/907859/npm-debug.log.txt)
