### ISSUE TITLE
Generating component for module fails

### ISSUE THREAD

**Issue by NCC1701M** [angular/angular-cli#5614]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.10.0
os: win32 x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Repro steps.
Create a new project and change into dir.
`ng new MyNgProject`

Add a new module
```
>ng g module admin --routing
installing module
  create src\app\admin\admin-routing.module.ts
  create src\app\admin\admin.module.ts
```
Try to add component to module
`ng g component my-admin --module admin`
### The log given by the failure.
```
installing component
  create src\app\my-admin\my-admin.component.scss
  create src\app\my-admin\my-admin.component.html
  create src\app\my-admin\my-admin.component.spec.ts
  create src\app\my-admin\my-admin.component.ts
EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at Class.afterInstall (C:\Entwicklung\Visual Studio Code\test\MyNgProject\node_modules\@angular\cli\blueprints\component\index.js:209:34)
    at tryCatch (C:\Entwicklung\Visual Studio Code\test\MyNgProject\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\Entwicklung\Visual Studio Code\test\MyNgProject\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (C:\Entwicklung\Visual Studio Code\test\MyNgProject\node_modules\rsvp\dist\rsvp.js:522:7)
    at flush (C:\Entwicklung\Visual Studio Code\test\MyNgProject\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

### Desired functionality.
1. I set the module with the --module flag. Therefore it should create the component in the module directory not in the app directory `create src\app\my-admin\my-admin.component.scss`
2. The error happens because it tries to do file i/o on a directory. You can see it when you dry run it. See below

### Mention any other details that might be useful.
```
> ng g component my-admin --module admin --dry-run
installing component
You specified the dry-run flag, so no changes will be written.
  create src\app\my-admin\my-admin.component.scss
  create src\app\my-admin\my-admin.component.html
  create src\app\my-admin\my-admin.component.spec.ts
  create src\app\my-admin\my-admin.component.ts
  update src\app\admin <-- Error happens here, admin is the module folder not the file
```

**Comment by filipesilva** [comment]
Heya, I think you forgot to copy over the command you used to generate the component. Could you add it please?

**Comment by NCC1701M** [comment]
Hi @filipesilva 
No it's on top of the _Mention any other details that might be useful_ block

**Comment by filipesilva** [comment]
Oh duh. I didn't even think of that :D

**Comment by filipesilva** [comment]
Ok so I'm looking at how we do this... and we do require the path to the module proper. That's why it's hitting the folder.

```
> ng g component my-admin --module admin/admin.module.ts
// .ts is optional
> ng g component my-admin --module admin/admin.module
```

So this isn't a bug, it's intended.

But maybe we should try to be smarter about it, and when it's a folder we look inside.

**Comment by NCC1701M** [comment]
When I use ng g module without the --flat flag it creates the following structure
src/app/new-module/new-module.module.ts

Therefore it's My opinion that when you use the --module flag with e.g ng g component or the other options it should use the exact same folder structure to find the correct module.

**Comment by Hirse** [comment]
@filipesilva Could you update [the Wiki](https://github.com/angular/angular-cli/wiki/generate-component#options) with that example?

The Wiki just states:
> module
`--module` (alias: `-m`)
Allows specification of the declaring module.

And the `--help` of `ng g` isn't helpful either:
> --module (String) Allows specification of the declaring module.
        aliases: -m <value>

I have run into the same problem because it is unclear how the module should be specified (`admin`, `Admin`, `AdminModule`, `admin.module`).

**Comment by filipesilva** [comment]
I'm closing this one in favor of #5461, because it has a better spec of the intended change and also a PR to go with it.
