### ISSUE TITLE
Unable to find "@angular/cli" in devDependencies

### ISSUE THREAD

**Issue by Ionaru** [angular/angular-cli#5616]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 7.7.3
os: linux x64

### Repro steps.

`sudo yarn global upgrade @angular/cli`

`sudo yarn global remove @angular/cli`
`sudo yarn global add @angular/cli`

Run any ng command

### The log given by the failure.

```
Unable to find "@angular/cli" in devDependencies.

Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest"
```

### Desired functionality.

ng command runs without issues.

### Mention any other details that might be useful.

I am not sure this is related, but all new Angular apps I create using the CLI appear in the Home directory instead of the directory the command was run in.

**Comment by Ionaru** [comment]
It appears this was caused by having a `node_modules` folder and `package.json` file in the home directory, probably caused by doing an incorrect `npm install` command in the past.

**Comment by filipesilva** [comment]
I'm going to keep this open actually, we shouldn't check that root `package.json` really.

**Comment by AnCze** [comment]
I have this same issue

**Comment by AnCze** [comment]
I have this same issue, how can I fix this?

**Comment by fbownz** [comment]
I got the same issue, this was after updating my angular cli on my project folder.

**Comment by AnCze** [comment]
I got it, in my case I had to delete package.json which I create earlier in application folder.

**Comment by hectorggp** [comment]
I have the same issue. Please tell me whats is happening. I already run the commands suggested without success and I don't think than need to delete package.json.

**Comment by otonielguajardo** [comment]
This happens to me only if a package.json already exists in same directory where running "ng new app-name", in my case the package.json I use for my server side node app.

**Comment by Saladg** [comment]
Hi,
I ran into the same problem when I tried to create a component in Angular2 quickstart project. This is what solved my problem. 
First make sure you install angular cli as;
**npm install -g @angular/cli**
then cd to where you want to put your project.

**ng new your_project_name
cd your_project_name
ng serve**

To add a component, cd to your_project_name and run;
comp@debian:~/Desktop/your_project_name$**ng generate component mycompo**

This will create your componet under mycompo folder in src/app/mycompo

**Comment by Aroniez** [comment]
I changed the following line in _package.json_ from
    `"angular-cli": "1.0.0-beta.21",`
to
`"@angular/cli": "1.0.4",`
and it worked. For my case that was the solution.

**Comment by gaikwad411** [comment]
I had the same issue following steps helped me to resolve it,

1. Update package json 
**from** 
"angular-cli": "anything"
**to**
"@angular/cli": "1.0.4"

2. Deleted node_modules and installed node modules again with
npm install
 
3. Change angular-cli.json for
**from** 
"environments": {
      "source": "environments/environment.ts"
      "dev": "environments/environment.ts",
      "prod": "environments/environment.prod.ts"
    }
**to**
"environmentSource": "environments/environment.ts",
    "environments": {
      "dev": "environments/environment.ts",
      "prod": "environments/environment.prod.ts"
    }

**Comment by filipesilva** [comment]
Closing as this doesn't seem to be an issue anymore.

**Comment by tschubach** [comment]
As **otonielguajardo** mentioned, this happens when package.json exists in the directory where 'ng new-app-name' is run, as when creating a front-end for a server-side node app.  To resolve this, I ran the command in a separate directory, then moved the created folder under my original app folder.

**Comment by Sayan751** [comment]
I have a monorepo with following structure:

```
root
|-packages
| |-angular-package1\
| |-angular-package2\
| ...
|-lerna.json
|-package.json
```

I am facing the following problem while `ng new myapp --routing --directory packages/myapp`. If I don't include `"@angular/cli": "^1.7.3"` in `devDependencies` it complaints about `Unable to find "@angular/cli" in devDependencies.`, and when I do, it tells me `You cannot use the new command inside an Angular CLI project.`. 🙁

**Comment by Sreekanth1234** [comment]
I using mac.. My node -v **8.11.1** .. I have removed @angular/cli... 
Then i have given **sudo npm install -g @angular/cli@1.4.9** is it Angular4?
After that it's showing error ..
I need to install Angular4 on Mac?
