### ISSUE TITLE
Update from angular/cli1.0.0-rc4 to angular/cli 1.0.0 does not update angular to version 4

### ISSUE THREAD

**Issue by AlMuIssues** [angular/angular-cli#5617]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.9.5
os: linux x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10

### Repro steps.

Update angular/cli from 1.0.0-rc4 to 1.0.0.
In package.json are old angular versions. I expected angular 4.
Output after run ng -v: 
@angular/cli: 1.0.0
node: 6.9.5
os: linux x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10

**Comment by aslan92** [comment]
Updating angular-cli version will not update your packege.json, you should create new app with 
```ng new MyAngularApp```

**Comment by AlMuIssues** [comment]
I have updated my angular to version 4.0( description from angular blog page):
npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@latest typescript@latest --save  

Is it the same as updating with ng new MyProject?

**Comment by RicardoVaranda** [comment]
While there is currently no upgrade suggested plan I find it easier to simply create a new project and copy/compare both package.json files, take it consideration that some of the other files may have changed for example the tsconfig changed from the src folder to the project root.

**Comment by filipesilva** [comment]
Yeah we have a 'real' update command planned but we're not there yet. There's an upgrade guide you can follow though: https://github.com/angular/angular-cli/wiki/stories
