### ISSUE TITLE
docs: Remove @latest from update instructions

### ISSUE THREAD

**Issue by TB-Andrew** [angular/angular-cli#5625]
![image](https://cloud.githubusercontent.com/assets/7580744/24295238/8acc24cc-1078-11e7-935b-5eeb221109f8.png)

As 1.0.0 has just been release, I don't believe that the @latest is required anymore and should be removed. It made me question whether or not I was going to get a newer version than the current stable.

This is an awesome tool! Congratulations on releasing 1.0.0!

**Comment by RicardoVaranda** [comment]
Hey @areid31891 ,

Thanks very much for the suggestion, I agree with your point in removing it in order to get the latest stable version the @latest should be removed, thus I've created a PR to match your request:
https://github.com/angular/angular-cli/pull/5626

**Comment by filipesilva** [comment]
Closing as answered, thanks @RicardoVaranda and @clydin !
