### ISSUE TITLE
relative templateUrl not working

### ISSUE THREAD

**Issue by El4a** [angular/angular-cli#5630]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.10.0
os: darwin x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

macOs - sierra 10.12.3s

### Repro steps.
I have updated an angular-cli generated project from beta.22-1 to the last version (1.0.0) released 24/03.

### The log given by the failure.
No logs.

### Desired functionality.

Before i could load the templates as ./app.component.html.  That doesn't work anymore. A full path (ex. templateUrl: './src/app/app.component.html') does work.

I know this is a very vague issue but maybe there is something obvious I'm missing?

**Comment by RicardoVaranda** [comment]
Hi @El4a ,

Any chance you can upload an example project for this issue, I currently have the same setup as you and I am still able to load all of my templates / styles with the relative path.

Thanks 👍

**Comment by filipesilva** [comment]
This sounds like something related to `tsconfig.json` and a `baseUrl` being set somewhere. If you provide a repo we can have a look!

**Comment by El4a** [comment]
Hi @RicardoVaranda @filipesilva 

I quickly made a repo of my project (and stripped it a bit) https://github.com/El4a/cli1.0.0-example

It has 2 components: 
app.component.ts has the full path and it working
insz.component.ts has a relative path and is not working (and thus the browser errors)

It's probably something incredibly stupid though. Thanks in advance!

**Comment by RicardoVaranda** [comment]
Hey @El4a ,

I've cloned your repo and managed to get it working with relative paths quite easily simply change your insz.component.ts to:

```
@Component({
  selector: 'app-main',
  templateUrl: './insz.component.html'
})
```

Notice the difference in the templateUrl, this is how you should reference it by relative path rather than having to define the absolute which you were doing previously.

Likewise change your app.component.ts to:

```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
```

Hope this helps 👍

**Comment by filipesilva** [comment]
Closing as answered by @RicardoVaranda. Relative paths are from the component itself.

**Comment by El4a** [comment]
See that's what I did first...

but I can't get it to work because it throws this error
![image](https://cloud.githubusercontent.com/assets/15727732/24348890/965acc1e-12dd-11e7-917e-3acbea781163.png)

**Comment by RicardoVaranda** [comment]
How are you hosting/serving the files? 

It seems you are getting 404 errors which is quite common if the baseUrl is incorrect.

**Comment by El4a** [comment]
Everything was correct! Note to self: try re-installing the nodemodules a bit earlier in the debugging process instead of after 5 days...

No idea which lib was the problem but a reinstall fixed it :)
