### ISSUE TITLE
Please provide an option in config to ignore errors

### ISSUE THREAD

**Issue by e-oz** [angular/angular-cli#5638]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions.
1.0

Please create an option to don't break compilation if there are errors during compilation. Some errors are not critical, some are produced by stupidity of compiler/linter, but build still should be created. It's extremely important for existing apps. Currently we can't use AngularCLI 1.0 because of minor error, produced by variable compiler can't see (created in template). Nobody cares about this error and it works just fine with previous version (in runtime too).

**Comment by kondi** [comment]
I would say this is even more important for serve command, during the development. I don't think there is an error what you could not fix for the build (by casting, maybe even to any, or adding extra typings). It is a very bad practice to allow your production build with errors.

**Comment by e-oz** [comment]
@kondi 
> I don't think there is an error what you could not fix for the build

But there are such errors.

> It is a very bad practice

Each project and each team should have own rules. "Bad/good practices" are just sets of advices, not laws.

**Comment by e-oz** [comment]
Not needed anymore after https://github.com/angular/angular-cli/pull/5698, thanks.

**Comment by vernjensen** [comment]
I am looking for a way to continue a build even with errors. e-oz, is there a way to specify this in config?

The error I'm getting is "ERROR in Cannon read property 'getSourceFile' of undefined' which does not reference any file, and I have been unable to fix it. It seems to maybe be an issue in WebPack with Windows systems. I'd like to just IGNORE the error and continue the build...
