### ISSUE TITLE
Is there a way I can just build for production without using gh-pages?

### ISSUE THREAD

**Issue by NullVoxPopuli** [angular/angular-cli#564]
I want to upload my minified project to a different hosting service, like s3. :-\

**Comment by filipesilva** [comment]
There is, yes! You can just do `ng build -prod`, and the `dist/` folder will contain a self sufficient production ready project.

You can then deploy the contents of that folder to wherever you choose.

**Comment by NullVoxPopuli** [comment]
Ah ha! I tried production instead of -prod. Thanks!

**Comment by filipesilva** [comment]
Yeah that happened to me a couple of times as well. Not really sure why those aren't alias really, it's something carried over from `ember-cli`.

**Comment by etkirsch** [comment]
Nice, this helps me too. Thanks!

**Comment by NullVoxPopuli** [comment]
ok, so -- I just tried it, and there are still all of the files (js, html, e2e per component). Shouldn't there be just:

- index.html
- appName.js
- appName.css
- vendor.js
- vendor.css
?

**Comment by filipesilva** [comment]
At the moment, bundling isn't in yet. It's soon to be merged though: https://github.com/angular/angular-cli/pull/549

The files should be uglified though, and the config used is the production one (eg no `Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.` message).

**Comment by NullVoxPopuli** [comment]
cool, thanks for the link to that!
