### ISSUE TITLE
zone.js cannot read property 'instance' of undefined

### ISSUE THREAD

**Issue by brunonmelo** [angular/angular-cli#5642]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.9.2
os: darwin x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
@angular/language-service: 2.4.10
@ngtools/webpack: 1.3.0
zone.js: 0.8.4

### Repro steps.

It was working fine on previous version, the problem starts after I update my project to the newest release.
Previous version: 
@angular/cli: 1.0.0-rc.4
node: 6.9.2
os: darwin x64
@angular/common: 2.4.0
@angular/compiler: 2.4.0
@angular/core: 2.4.0
@angular/forms: 2.4.0
@angular/http: 2.4.0
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.0
@angular/platform-browser-dynamic: 2.4.0
@angular/router: 3.4.0
@angular/cli: 1.0.0-rc.4
@angular/compiler-cli: 2.4.0
@angular/language-service: 2.4.10
@ngtools/webpack: 1.3.0
zone.js: 0.7.6

### The log given by the failure.

![captura de tela 2017-03-24 as 14 47 08](https://cloud.githubusercontent.com/assets/14285854/24307097/9ac99be2-10a1-11e7-95bd-c3e9cdc7a81d.png)

### Mention any other details that might be useful.

this error occur when I navigate using lazyload, and on Chrome, it's not happens on Safari

**Comment by hansl** [comment]
That looks like the error is coming from a Chrome extension. Also, we updated Zone from 0.7 to 0.8, which might be a new bug. @mhevery does this error rings a bell?

**Comment by brunonmelo** [comment]
Could It be from Augury plugin?

**Comment by Rhymes2k** [comment]
getting the same error when navigating using lazyload and Augury extension is enabled. Without Augury the error is gone.
project generated with: @angular/cli: 1.0.0

**Comment by brunonmelo** [comment]
I'm going to close this issue. Seems like the Augury plugin was updated to fix this problem.
