### ISSUE TITLE
Feature request: Create a library project like angular/material

### ISSUE THREAD

**Issue by jdavidls** [angular/angular-cli#5643]
### Feature request: Create a library project like angular/material
```
- [X] feature request
```

`ng new --lib materialLikeProject`

Creates all the project boilerplate for build a AOT library (multiple modules in one package).

All the things currently in ng-cli can operate well as a testing application of the library. 

`ng serve`: starts a 'demo' application (excluded from output boundle).
`ng build`: build and rollup the library (commonjs, amd, es6 module packages).

Something planned like that?

**Comment by hansl** [comment]
This will not be done with Angular CLI 1, but is a main use case taken in the design of version 2. Cheers!

**Comment by bmbell** [comment]
@hansl: Being able to build a library/module similar to angular/material is a critical item for our company to move from AngularJS to Angular, but it is very hard to find any help on how to do this.  If this will be supported by the angular-cli, that will be excellent!  However, is there any estimate as to when this feature may appear?  This feature request came out nearly a year ago.  Thanks!

**Comment by beeman** [comment]
@bmbell if you want to use this for structuring your app, and you don't have the intention to publish those libraries to the npm registry you can look into https://github.com/nrwl/nx . It offers a great solution for splitting up you Angular application into libraries/modules.

I know it's not the answer to your question but I figured it might help.
