### ISSUE TITLE
Cannot find variable in JS script: Cannot find name 'Hammer'

### ISSUE THREAD

**Issue by Cogitaria** [angular/angular-cli#5644]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] WTF?
```

### Versions.

Upgrading everything to RC4 from beta.28 :
@angular/cli: 1.0.0-rc.4
node: 6.10.0
os: darwin x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.4
@angular/compiler-cli: 2.4.10

### Repro steps.

 Reference Hammer:  this.whichWayIsUp = Hammer.DIRECTION_VERTICAL

### The log given by the failure.

... Cannot find name 'Hammer'

### Desired functionality.

NPM installed the hammerjs and pointed it at it in .angular-cli.json scripts tag:

      "scripts": [
        "../node_modules/hammerjs/hammer.min.js",

My assumption (which may be in error) is that we need only include the script and then we can reference the variables in that script (e.g., Hammer).  Please advise, thanks!

**Comment by clydin** [comment]
You'll need to install the types as well: '@types/hammerjs'

**Comment by hansl** [comment]
@clydin is right. Closing this as answered.

**Comment by Robouste** [comment]
I have the same issue. Installing @types/hammerjs removed the error from VS Code, but it's still present on compilation.

![hammer-cli](https://cloud.githubusercontent.com/assets/5463032/24363608/a12361aa-1310-11e7-8d0f-4852d14905a6.jpg)

`let wiper = new Hammer(document.getElementById('gallery-wrapper'));`

**Comment by chozharajan** [comment]
@clydin  am new angular can you explain it step by step i can't understand "You'll need to install the types as **_well:"_**  and @hansl  also

**Comment by avBerenger** [comment]
@chozharajan probably with `npm install @types/hammerjs --save-dev`
