### ISSUE TITLE
Can't Download NPM

### ISSUE THREAD

**Issue by laynefaler** [angular/angular-cli#5646]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Repro steps.

npm i -g @angular/cli@latest
or
npm i -g @angular/cli

### The log given by the failure.

In photo

### Desired functionality.

![screen shot 2017-03-24 at 1 34 40 pm](https://cloud.githubusercontent.com/assets/14255968/24312639/b3345af6-1096-11e7-84bd-e36acd3541c9.png)

**Comment by hansl** [comment]
I cannot reproduce this here with my Mac. Used `nvm` to install Node 7.7. How did you install Node?

**Comment by hansl** [comment]
For reference, this is definitely not an issue with the CLI.

**Comment by laynefaler** [comment]
brew

Please help me download this CLI so I can possibly help my company look Angular 4 over React

**Comment by RicardoVaranda** [comment]
Hi @laynefaler ,

Could you post the result of these three commands:

1. npm config get registry
2. npm config get http-proxy
3. npm config get https-proxy

**Comment by filipesilva** [comment]
Closing as inactive.
