### ISSUE TITLE
Cannot spawn `ng`

### ISSUE THREAD

**Issue by rohan-deshpande** [angular/angular-cli#5647]
### Feature Request
```
- [] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.9.0
os: darwin x64

### Repro steps.
```
spawn.sync(
    'ng',
    ['new', 'myApp'],
    { stdio: 'inherit' }
  );
```

### The log given by the failure.
```
The specified command new,myApp is invalid. For available options, see `ng help`.
```

### Desired functionality.
Should be able to spawn this process without it failing

### Mention any other details that might be useful.
Not sure why I can't spawn the process. This is related to my NW.js CLI which I'm about to publish. Currently support kicking off the NW.js app from a variety of sources, commands such as `create-react-app` and `vue` are supported, wanted to support `ng` as well but ran into this issue.

**Comment by hansl** [comment]
Do you have `ng` installed globally and in your $PATH?

Which library is `spawn` from? It works locally when I use `child_process.spawnSync`.

**Comment by rohan-deshpande** [comment]
Yep it's installed globally, can `ng new myApp` regularly.

I'm using `cross-spawn` but it's identical to the node implementation other than cross platform support.

**Comment by rohan-deshpande** [comment]
Okay, user error, in my actual code I was passing the arguments incorrectly. Apologies.
