### ISSUE TITLE
'ng new ' is not working

### ISSUE THREAD

**Issue by ahag** [angular/angular-cli#5650]
`D:\Work\learn\angular>node --version
v6.10.1

D:\Work\learn\angular>npm --version
3.10.10

D:\Work\learn\angular>ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.10.1
os: win32 x64

D:\Work\learn\angular>ng new myapp
installing ng
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Successfully initialized git.
Installing packages for tooling via cnpm.

  error: unknown option `--quiet'

Package install failed, see above.

D:\Work\learn\angular>`

**Comment by tex23bm** [comment]
I've also hit a problem attempting to run the CLI new command. 

[fail.txt](https://github.com/angular/angular-cli/files/869671/fail.txt)

**Comment by tex23bm** [comment]
I thought this might be a side effect of my not properly uninstalling angular-cli, but I did that, cleared the cache and re-installed. Still getting this same error.

**Comment by rdrrichards** [comment]
@ahag You are passing in an option (--quiet) that is not valid. Use `ng new --help` to see the valid options. Or, go here: https://github.com/angular/angular-cli/wiki/new

**Comment by Ajeey** [comment]
@ahag update your node to >=  6.9.0

**Comment by clydin** [comment]
It appears `cnpm` does not have a `--quiet` flag.  As a workaround you can use the `--skip-install` option on `ng new` and run the package install manually afterwards with `cnpm`.

**Comment by Alber70g** [comment]
I've figured that running `ng new angular-project` creates a new project in the home directory. In my case on MacOS in `/Users/<username>/angular-project`. 

Moving it from there to the desired location will serve as a workaround.

**Comment by Timm-Lee** [comment]
It seems that the package manager "cnpm" added `--quite` to `ng new`, but actually `ng new` has no such option. So you have to set back to npm.

**Comment by filipesilva** [comment]
This is a bug, we should not pass `--quiet` when using `cnpm`.

**Comment by anupping** [comment]
hitting error on using
>ng new
Soln: install node.js from nodes.org
run this : it will take time to install have patient. 
>npm install -g @angular/cli
