### ISSUE TITLE
Error encountered resolving symbol values statically. Can't resolve './$$_gendir/app/app.module.ngfactory' in `path`.

### ISSUE THREAD

**Issue by Chlebamaticon** [angular/angular-cli#5655]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report -> please search issues before submitting

### Versions.
```
`@angular/cli: 1.0.0-beta.32.3
node: 7.7.1
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.10`
```

There's link to repo: https://github.com/Chlebamaticon/ng2-trouble
Error is occurring when I trying to build this application with this command: `ng build --prod`.

### The log given by the failure.
```
`ERROR in Error encountered resolving symbol values statically. Reference to a non-exported function (position 7:10 in the original .ts file), resolving symbol routerTransition in D:/dev/portfolio-sec/src/app/home/router.animation.ts, resolving symbol HomeComponent in D:/dev/portfolio-sec/src/app/home/home.component.ts, resolving symbol HomeComponent in D:/dev/portfolio-sec/src/app/home/home.component.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\dev\portfolio-sec\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts`
```

This code's working at `ng serve` but I wish to deploy this application, but this bug(?) or my lack of knowledge's breaking down.
I'm really exhausted by looking for solution, can you help me, and short my suffering? 😃

**Comment by achimha** [comment]
`routerTransition` calls `slideToLeft` which is not exported.

**Comment by Chlebamaticon** [comment]
@achimka, you're my Saviour.  Thread to close, capitan!

**Comment by eliteproxy7** [comment]
i got this error as well, where would I export it? here is my router.animtions.ts code 

`

import {trigger, state, animate, style, transition} from '@angular/core';

export function routerTransition() {
return slideToLeft();

}

function slideToLeft() {
  return trigger('routerTransition', [
    state('void', style({position:'absolute', width:'100%', height:'calc(100% - 110px)',top:'110px'}) ),
    state('*', style({position:'absolute', width:'100%', height:'calc(100% - 110px)',top:'110px'}) ),
    transition(':enter', [
      style({transform: 'translateX(100%)'}),
      animate('0.3s ease-in-out', style({transform: 'translateX(0%)'}))
    ]),
    transition(':leave', [
      style({transform: 'translateX(0%)'}),
      animate('0.3s ease-in-out', style({transform: 'translateX(-100%)'}))
    ])
  ]);
}

`

**Comment by filipesilva** [comment]
Closing as answered by @achimha, cheers!
