### ISSUE TITLE
[Bug] Following upgrade to ng4 from 2.4, dependency injection breaks on --prod

### ISSUE THREAD

**Issue by alshdavid** [angular/angular-cli#5658]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report
- [ ] feature request
```

### Versions.
Output from: `ng --version`.

![image](https://cloud.githubusercontent.com/assets/12656294/24328999/77d316f8-1255-11e7-972f-b780040de877.png)

### Repro steps.
I upgraded from 2.4 to 4 via the instructions here: http://angularjs.blogspot.co.nz/2017/03/angular-400-now-available.html

I then upgraded @angular/cli with:
```
rmdir /S/Q node_modules dist
npm install --save-dev @angular/cli@latest
npm install
```
Had to make a change the the angular-cli.json which was:
```
"environmentSource": "environments/environment.ts",
      "environments": {
          "dev": "environments/environment.ts",
          "prod": "environments/environment.prod.ts"
      }
```

### The log given by the failure.

![image](https://cloud.githubusercontent.com/assets/12656294/24328977/f582c504-1254-11e7-83b4-849f284e1073.png)

anything with `--prod` or `--prod --aot` fails to work. The red text above is `ng build --prod`
The text below is `ng serve`

The thing's it's pointing out are the services I'm injecting in the constructors like:
```
constructor(
    private myService: MyService
){}
```

### moreinfo

I call things from the constructor directly inside the template:
`<button (click)="location.back()">Back</button>`

When I remove these, it has works.

**Comment by achimha** [comment]
You have to make your injected services `public` if you want to access them from the template in AOT mode. Also you cannot call anything but public component member methods so `location.back()` will not work.

**Comment by alshdavid** [comment]
I changed all of the things which are injected and used directly in the temples from private to public.

There was also a component that I never used, which was asking for a bunch of variables that didn't exist - causing a whole bunch of errors..
