### ISSUE TITLE
Unable to find any apps in `.angular-cli.json`.

### ISSUE THREAD

**Issue by cozzbie** [angular/angular-cli#5661]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
angular/cli: 1.0.0
node: 7.3.0
os: darwin x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Repro steps.
ng new [project]
ng serve

### The log given by the failure.
Unable to find any apps in `.angular-cli.json`.

### Desired functionality.
ng serve should run

**Comment by demirk4n** [comment]
Hi, I couldn't reproduce the issue in my env.  `ng serve` works corretly. Can it be your global @angular/cli installation got corrupt? You may try a cache clean and reinstall..

```
npm cache clean
npm -g i @angular/cli
```


```
@angular/cli: 1.0.0
node: 7.7.4
os: linux x64
```

```
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
```

**Comment by hansl** [comment]
@cozzbie Could you please provide you `angular-cli.json` file or a git repo we could clone and look at? Thanks.

**Comment by cozzbie** [comment]
@demirk4n is right. it was a corrupt install. After wiping it all and reinstalling all is fine now.

**Comment by pranaysand** [comment]
I got the same issue when tried to create a component using the angular/cli.  "npm cache verify" have fixed issue.

**Comment by bilazik** [comment]
Thanx a lot. I am got same issue in `ng generate component` - and `npm cache verify` command have fixed this problem

**Comment by mobinsb** [comment]
I had the same problem. Project can't find .angular-cli.json file I replace it then build project again
It is solved.
