### ISSUE TITLE
Markdown in the CLI wiki is not working in the nested options

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#5664]
Check out https://github.com/angular/angular-cli/blob/master/docs/documentation/test.md and scroll down to the options. (see image below). 

![2017-03-26_11-32-36](https://cloud.githubusercontent.com/assets/1202528/24332640/27267cb4-1218-11e7-9aac-d63b2ef8ec7a.gif)

Also, the arrows are not user-friendly. I recommend listing all of the options as being visible all the time.

**Comment by coryrylan** [comment]
I can get a pull request in to improve this today

**Comment by coryrylan** [comment]
If this looks good for a new format I can submit a pull request today to update them @filipesilva @hansl Thanks! :)

**Comment by johnpapa** [comment]
Thanks for the help. I like this better

I think an `h4` (or whatever header is appropriate here) may look better. The bullets don't do much for it. Just my 2 cents

Just heads up - There is another issue open somewhere for defaults to be shown too. @Brocco is working on that

**Comment by coryrylan** [comment]
Ok I think I  found the referenced issue here:  https://github.com/angular/angular-cli/issues/5386 

Updated proposal with just headers no list items: 

### app
  `--app` (alias: `-a`) _default value: 1st app_

  Specifies app name or index to use.
  
### browsers
  `--browsers`

  Override which browsers tests are run against.
  
  

### code-coverage
  `--code-coverage` (alias: `-cc`) _default value: false_

  Coverage report will be in the coverage/ directory.
  
  

### colors
  `--colors`

  Enable or disable colors in the output (reporters and logs).

**Comment by johnpapa** [comment]
It seems this is throughout other pages in the docs too. for example `e2e`

**Comment by coryrylan** [comment]
Yeah I saw this as well. I can make individual pull requests for each doc if that would be better instead of a large single

**Comment by johnpapa** [comment]
yeah, that's probably easiest

**Comment by filipesilva** [comment]
@sumitarora was actually fixing this, but I don't think he pushed up a PR yet.

**Comment by sumitarora** [comment]
@johnpapa @filipesilva @coryrylan There is already a PR open for the issue https://github.com/angular/angular-cli/pull/5633 and issue I created for the same https://github.com/angular/angular-cli/issues/5632

**Comment by filipesilva** [comment]
@sumitarora thanks for clarifying, I'll close this in favor of https://github.com/angular/angular-cli/issues/5632.
