### ISSUE TITLE
ng test -sm false seems to generate sourcemaps

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#5666]
### OS
Mac  OSX Sierra 10.12.3

### Versions
@angular/cli: 1.0.0
node: 6.9.1
os: darwin x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Repro steps.
`ng test -sm false`

This should run tests without the source maps. However, we can still debug into source maps. 

// As noted by @wardbell, also

![2017-03-26_11-52-26](https://cloud.githubusercontent.com/assets/1202528/24332829/38fe18fe-121b-11e7-9c49-3680671a4e1c.gif)

**Comment by filipesilva** [comment]
This is not intended, it is a bug. Sourcemaps are not being correctly turned off.

@johnpapa this explains why disabling sourcemaps didn't improve test rebuilds anymore.

**Comment by johnpapa** [comment]
Good to know I'm not nuts :)

**Comment by hccampos** [comment]
@filipesilva any idea when a minor bump will be released with this? Seems like all the development is going on in 1.1.x while 1.0.0 is left with several bugs that have been fixed a while back.
