### ISSUE TITLE
typeChecking: false has no effect

### ISSUE THREAD

**Issue by frederikschubert** [angular/angular-cli#5675]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

node: v6.9.5
npm: 3.10.10

### Repro steps.

Set `typeChecking: false` in AotPlugin options.

### Desired functionality.

Skip type check.

### Mention any other details that might be useful.

I am using `@ngtools/webpack` directly in my own setup. The issue was introduced with the `1.3.0` release. `1.2.13` is the last release where this works.

**Comment by chenop** [comment]
Here is what we tried:
- create new cli project
- ng eject
- edit the webpack.config.js:
 ```
new AotPlugin({
      ...,
      "typeChecking": false
    })
```
- tried to assign a number into a string variable

Got: 

> webpack: failed to compile

#goodnessSquad

**Comment by unsafecode** [comment]
Is there a plan to fix this issue?

**Comment by frederikschubert** [comment]
This is blocking some of our older apps to migrate to using the AOT compiler. If I had some directions on where to look for the error, I would try to come up with a PR myself. @hansl

**Comment by unsafecode** [comment]
@filipesilva Is there a way we can quickly fix this? We had a lots of trouble lately due to the `enhanced-resolve` bug and being unable to patch to the latest version because of this issue. 

@frederikschubert  @chenop

**Comment by rahuljayaraman** [comment]
Having the same problem. Guessing that the issue crops up because of https://github.com/angular/angular-cli/commit/4bd8bd2519cb339551150e6adca2205c56ae3b73

Don't have much context about why re-diagnosing is required, but adding a guard clause solves it for me.
```js
if (this._typeCheck) {
  const changedFilePaths = this._compilerHost.getChangedFilePaths();
  changedFilePaths.forEach(filePath => this.diagnose(filePath));
}
```

**Comment by unsafecode** [comment]
@rahuljayaraman Any chances to have that fix merged?

**Comment by rahuljayaraman** [comment]
@unsafecode I'm not sure. Looks like @hansl will review it. Feel free to experiment with my branch though, or cherry-pick the commits onto the version you're using.

**Comment by huerlisi** [comment]
A related question: in my understanding there is no configuration option for `ng lint` to always use the `--type-check` parameter. While it is possible to add such an argument to the `lint` script in `package.json`, `ng lint` calls from the command line won't respect that.

We would like to set this configuration as some TSLint rules require it. There's even a default rule in freshly generated projects that trigger a "Warning: The 'no-use-before-declare' rule requires type checking" warning.

Would you consider a PR that introduces this? And would there be some blocker on making it even the default?

**Comment by alan-agius4** [comment]
Closing as per @hansl comment in https://github.com/angular/angular-cli/pull/7574

> Sorry for the slow answer, going through my inbox one by one.

If you're not using type checking, why use typescript at all? Also, the Typescript compiler (and ngc) doesn't support disabling type checking, so this is not something we will support.

Closing this as this is not a feature we want. Sorry.
