### ISSUE TITLE
Webstorm TSlint issue for .spec files

### ISSUE THREAD

**Issue by scopsy** [angular/angular-cli#5676]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.0
node: 7.6.0
os: darwin x64
```

### Repro steps.
After upgrading to the latest angular-cli version and splitting my TSConfig files webstorm alerts me on my spec files that it cannot find all jasmine/karma names. I guess this happens because webstorm only searches inside one of the ts config files. 

Any workarounds there are? (without adding the spec types to the main app tsconfig file)

**Comment by Opticsponge** [comment]
Issue for me was package.json changes, I created a fresh ng4 install and just copied em over

**Comment by filipesilva** [comment]
@scopsy I think you probably forgot to add the rootlevel `tsconfig.json` as described in https://github.com/angular/angular-cli/wiki/stories-1.0-update. That's the one that provides typings for IDEs.
