### ISSUE TITLE
installing angular in memory web api is not recognising @angular/core modules

### ISSUE THREAD

**Issue by Diego-Romero** [angular/angular-cli#5677]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

trying to install the tutorial module in memory api

[diegoromero:~/eudaimony]$ npm i angular2-in-memory-web-api

### The log given by the failure.

eudaimony@0.0.0 /Users/diegoromero/eudaimony
├── UNMET PEER DEPENDENCY @angular/core@4.0.0
├── UNMET PEER DEPENDENCY @angular/http@4.0.0
├── angular2-in-memory-web-api@0.0.21
├── UNMET PEER DEPENDENCY rxjs@5.2.0
└── UNMET PEER DEPENDENCY zone.js@0.8.5

### Mention any other details that might be useful.

my package son

{
  "name": "eudaimony",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "angular2-in-memory-web-api": "0.0.21",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}

**Comment by yarrgh** [comment]
Try switching from `angular2-in-memory-web-api` to `angular-in-memory-web-api`. Current version is 0.3.1 where you're trying to use 0.0.21.

[https://github.com/angular/in-memory-web-api/blob/master/README.md](https://github.com/angular/in-memory-web-api/blob/master/README.md)
> As of v.0.1.0, the npm package was renamed from angular2-in-memory-web-api to its current name, angular-in-memory-web-api. All versions after 0.0.21 are shipped under this name. Be sure to update your package.json and import statements.

**Comment by Diego-Romero** [comment]
cheers boss, it worked.

**Comment by filipesilva** [comment]
Closing as answered by @yarrgh, cheers!
