### ISSUE TITLE
changed `root` property in .angular-cli.json doesn't work properly

### ISSUE THREAD

**Issue by alexanderPastornicky** [angular/angular-cli#5679]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.0
node: 6.9.1
os: linux x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
```

### Repro steps.
in `.angular-cli.json`

`"root": "src/angular"`

### The log given by the failure.
```
src/angular/app/app.component.ts (1,33): Cannot find module '@angular/core'.
src/angular/app/app.component.ts (7,14): Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
```
...

### Desired functionality.
Working

### Mention any other details that might be useful.

in `src/tsconfig.app.json` there is `"extends": "../tsconfig.json"` ... it should not have relative value

**Comment by filipesilva** [comment]
If you change the root value manually, you also need to change relative paths such as the extends in `src/tsconfig.app.json`. We can't do that for you when you change values manually.

If you want to make a new app with a different root directory (`ng new my-proj --source-dir=src/angular`), we change all values for you.
