### ISSUE TITLE
CLI not creating the spec files

### ISSUE THREAD

**Issue by trichetriche** [angular/angular-cli#5681]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

angular-cli: 1.0.0-beta.28.3

### Repro steps.

In the console, `ng ng c blabla`

### The log given by the failure.

It's not really a failure : the component is created, but the spec files aren't.

    installing component
        create src/app/blabla/blabla.component.less
        create src/app/blabla/blabla.component.html
        create src/app/blabla/blabla.component.ts
        update src/app/app.module.ts

### Mention any other details that might be useful.

in the `angular-cli.json` file : 

    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }

**Comment by Nikki1993** [comment]
Please, upgrade to the latest version of the angular/cli and report if you are experiencing issues with it. Don't forget to check out the migration guide here https://github.com/angular/angular-cli/wiki/stories-1.0-update

**Comment by trichetriche** [comment]
I wanted to avoid updating it for some reason ... But I guess I have no choice. I updated it and it works great, thank you @Nikki1993
