### ISSUE TITLE
Lazy Loading on ng-cli 1.0.0 Error: BrowserModule has already been loaded. 

### ISSUE THREAD

**Issue by Perezmarc** [angular/angular-cli#5684]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 7.0.0
os: darwin x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/animations: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Repro steps.
Lazy Loading worked before for me in beta.26, I have updated following the guide and everything but lazy loaded modules work. When I try to render a lazy loaded module I get the following error at the console browser: 

**Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.**

In my routes module I load it like so:
`{
    path        : 'p/:postId',
    loadChildren: './postView/postView.module#PostViewModule',
    canActivate : [ AuthChecker ]
  },`

and this is how my lazy loaded module looks like:
`export const lazyPostRoutes: Routes = [
  {
    path     : '',
    pathMatch: 'full',
    component: PostViewComponent,
  },
];

@NgModule( {
             imports     : [ CommonModule, SharedModule, PostElementModule, RouterModule.forChild( lazyPostRoutes ) ],
             declarations: [ PostViewComponent ],
             exports     : [ PostViewComponent ]
           } )

export class PostViewModule {
}
`

### The log given by the failure.
ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
    at y (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at new t (main.67dfa38472fde81d5107.bundle.js:739)
    at e.createInternal (4.ad08eede51bd3ba4065a.chunk.js:1)
    at e.t.create (main.67dfa38472fde81d5107.bundle.js:365)
    at t.create (main.67dfa38472fde81d5107.bundle.js:365)
    at e.project (main.67dfa38472fde81d5107.bundle.js:442)
    at e._next (main.67dfa38472fde81d5107.bundle.js:772)
    at e.next (main.67dfa38472fde81d5107.bundle.js:766)
    at main.67dfa38472fde81d5107.bundle.js:766
    at t.invoke (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at Object.onInvoke (main.67dfa38472fde81d5107.bundle.js:365)
    at t.invoke (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at e.run (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at polyfills.cabf62930fce2e0f0442.bundle.js:36
    at t.invokeTask (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at y (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at new t (main.67dfa38472fde81d5107.bundle.js:739)
    at e.createInternal (4.ad08eede51bd3ba4065a.chunk.js:1)
    at e.t.create (main.67dfa38472fde81d5107.bundle.js:365)
    at t.create (main.67dfa38472fde81d5107.bundle.js:365)
    at e.project (main.67dfa38472fde81d5107.bundle.js:442)
    at e._next (main.67dfa38472fde81d5107.bundle.js:772)
    at e.next (main.67dfa38472fde81d5107.bundle.js:766)
    at main.67dfa38472fde81d5107.bundle.js:766
    at t.invoke (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at Object.onInvoke (main.67dfa38472fde81d5107.bundle.js:365)
    at t.invoke (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at e.run (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at polyfills.cabf62930fce2e0f0442.bundle.js:36
    at t.invokeTask (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at y (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at l (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at l (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at polyfills.cabf62930fce2e0f0442.bundle.js:36
    at t.invokeTask (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at Object.onInvokeTask (main.67dfa38472fde81d5107.bundle.js:365)
    at t.invokeTask (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at e.runTask (polyfills.cabf62930fce2e0f0442.bundle.js:36)
    at a (polyfills.cabf62930fce2e0f0442.bundle.js:36)

### Desired functionality.
Load a lazy loaded module

**Comment by intellix** [comment]
You should only import BrowserModule in AppModule. I'm guessing you've declared it in your SharedModule

**Comment by Perezmarc** [comment]
I found the error, I had browserAnimationsModule in sharedModule and in AppModule.

**Comment by intellix** [comment]
I guess that's one for angular/angular as the errors are channeled from there :)

**Comment by zmkn** [comment]
@Perezmarc @intellix  I also found this error, I want to know how to solve?

**Comment by intellix** [comment]
@zmkn only import BrowserModule and the animations one once (app and not shared)

**Comment by Perezmarc** [comment]
Watch out to not be including browserAnimationsModule twice, Angular throws the error as "BrowserModule" is imported twice.

**Comment by akomarovsky** [comment]
thanks for the answer. It was very annoying error

**Comment by aebmknrl** [comment]
Ok the same here... i fixed moving my browserAnimationsModule from the shared module to the app.module.ts

But.. the question is.... WHY?

**Comment by gimox** [comment]
+1 same problem here. the only solution is to declare  browserAnimationsModule in AppModule

**Comment by devmpep** [comment]
If you have `BrowserAnimationsModule` imported at the AppModule, then remove `BrowserModule`

**Comment by jesseteweehi** [comment]
Same problem here declare browserAnimationsModule in AppModule. Not in a shared Module

**Comment by ZhiliangGong** [comment]
Same here. Why can I not import BrowserAnimationsModule in the SharedModule?

**Comment by rollwhistler** [comment]
But if you imported on app.module.ts then your child modules which feeds from shared module won't have BrowserAnimation available. How are you handling this?

**Comment by DrMueller** [comment]
As rollwhistler asked: If I import the BrowserAnimationsModule in the app Module, my shared Module doesn't recognize the Animations directive. Interesting enough, if I load the BrowserAnimationsModule ONLY in the shared Module, I still get the BrowserModule error.

**Comment by SherlockStd** [comment]
@rollwhistler why wouldn't they have BrowserAnimation ? If they are child module of `AppModule` it's fine, even if they import shared module.
Example from my project:

> `admin.module.ts` (main module, same as AppModule)
```typescript
import { NgModule, ApplicationRef } from '@angular/core'
import { RouterModule, PreloadAllModules } from '@angular/router'
import { BrowserAnimationsModule } from '@angular/platform-browser/animations'

/*
 * Platform and Environment providers/directives/pipes
 */
import { ENV_PROVIDERS } from '../environment'
import { ROUTES } from './admin.routes'

/*
 * Guards
 */
import { AuthGuard, AdminGuard } from '../shared/guards'

/*
 * Vendor
 */
import { SimpleNotificationsModule } from 'angular2-notifications'

/*
 * Shared Modules
 */
import { GlobalSharedModule } from '../shared/shared.module'
import { AdminSharedModule } from './shared/shared.module'

/*
 * Services
 */
import { AppReadyEvent } from '../shared/components/app-ready'

/*
 * Components
 */
import { AdminComponent } from './admin.component'
import { FullscreenMenuComponent } from './shared/components'
import { NotFoundComponent } from './errors'

/*
 * Styles
 */
import '../styles/admin.scss'

@NgModule({
  bootstrap: [ AdminComponent ],
  declarations: [
    AdminComponent,
    FullscreenMenuComponent,
    NotFoundComponent
  ],
  imports: [
    BrowserAnimationsModule,
    GlobalSharedModule,
    AdminSharedModule,
    RouterModule.forRoot(ROUTES, { preloadingStrategy: PreloadAllModules }),
    SimpleNotificationsModule.forRoot()
  ],
  providers: [
    AppReadyEvent
  ]
})
export class AdminModule {
}
```

> `admin.routes.ts`
```typescript
// Core
import { Routes } from '@angular/router'

// Guards
import { AuthGuard, AdminGuard } from '../shared/guards'

// Components
import { AdminComponent } from './admin.component'
import { FullscreenMenuComponent } from './shared/components'
import { NotFoundComponent } from './errors'

// Routes
export const ROUTES: Routes = [
  { path: '', component: FullscreenMenuComponent, pathMatch: 'full', canActivate: [AdminGuard] },
  { path: 'webinar', loadChildren: './+webinar#WebinarModule', canActivate: [AdminGuard] },
  { path: 'auth', loadChildren: '../shared/modules/authentication#AuthenticationModule'},
  { path: '**', component: NotFoundComponent, canActivate: [AdminGuard] }
]
```

> `webinar.module.ts` (child module of `admin.module.ts`)
```typescript
import { NgModule } from '@angular/core'
import { RouterModule } from '@angular/router'

import { GlobalSharedModule } from '../../shared/shared.module'
import { AdminSharedModule } from '../shared/shared.module'

import { routes } from './webinar.routes'
import { WebinarComponent } from './webinar.component'
import { CreateComponent } from './create'

@NgModule({
  declarations: [
    WebinarComponent,
    CreateComponent
  ],
  imports: [
    GlobalSharedModule,
    AdminSharedModule,
    RouterModule.forChild(routes)
  ],
  providers: [
  ]
})
export class WebinarModule {
}
```

**Comment by rollwhistler** [comment]
Mmmm, I'd swear my material components were not working when I moved browseranimation app to the root module, but maybe I was doing something else wrong, I'll double check.

**Comment by AsmisAlan** [comment]
@rollwhistler i have the same problem, the lazy loading modules haven't the BrowserAnimationsModule available, but the child modules have it.

**Comment by Sushant1791** [comment]
After moving BrowserAnimationModule to App.module.ts it is giving me an error of toastr module.

ERROR Error: Uncaught (in promise): Error: ToastrModule is already loaded. It should only be imported in your application's main module.
Error: ToastrModule is already loaded. It should only be imported in your application's main module.

Does that mean we need to move all the shared module to App.module.ts ?

**Comment by aebmknrl** [comment]
@Sushant1791 do you check the specifications of the own of Toastr module about the config?

**Comment by gshireesh** [comment]
i got lazyload animation import solved by changing the order of the browserModule and BrowserAnimationsModule. 

imports: [
    BrowserModule,
    BrowserAnimationsModule
]  thows error with lazyloding modules
`BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

imports: [
    BrowserAnimationsModule,
    BrowserModule
]  works. Solved my problem

**Comment by sanchesking9** [comment]
Today had the same problem :-) 
Thank you guys! :-) 
Added to SharedModule BrowserAnimationsModule and exported :-)

**Comment by nikbabchenko** [comment]
Today had the same problem :-) 
Thank you guys! :-) 
Added to the SharedModule - `BrowserAnimationsModule` and exported :-)

**Comment by MPauletta** [comment]
Wooow. I have been looking for a solution for more than a day now and gshireesh got it right for me.
You are the man, gshireesh.
Angular can be so confusing sometimes with these non trivial errors. :-(

**Comment by Rumsha001** [comment]
[SOLVED]
If anyone is still facing errors on shared Module then add 'CommonModule' in your SharedModule

Finally it worked for me after so many efforts!!

**Comment by michaeljota** [comment]
I just want to add, that you need to import every module from the `@angular/platform-browser` into the main application module. It is not just that you should not have them replicated, it just that you can't import any module from the `@angular/platform-browser` into any lazy loaded module.

**Comment by jcroll** [comment]
Should this issue not be reopened? If you're lazy loading modules you cannot have a `SharedModule` that exports `BrowserAnimationsModule` as far as I can tell.

**Comment by michaeljota** [comment]
@jcroll That kind of modules need to be loaded just once, in the main application. You just can't import any module from `@angular/platform-browser` into a lazy loaded module. 

If you think about it, it makes total sense, because that kind of modules have to tell the entire application how to work, and you still can use that features from lazy loaded modules, because you are using them directly (As far I can say).

**Comment by jcroll** [comment]
@michaeljota Correct me if I am wrong tho, if you wrote a third party module that had animations in it, you'd have to instruct the consumer to also import `BrowserAnimationsModule` into `AppModule` for your library to work properly?

**Comment by michaeljota** [comment]
Yes. I have. See [angular/material2](https://github.com/angular/material2) for an example of that.

**Comment by jcroll** [comment]
Yeah fair enough @michaeljota appears to be the case in the docs https://material.angular.io/guide/getting-started

Ok coolio, good enough for me.

**Comment by emeli-frank** [comment]
What I did was add `BrowserAnimationsModule ` to the exports array of  `CoreModule `'s NgModule instead of of doing it in `SharedModule`. But am a bit shocked as to how feature modules are able to access `BrowserAnimationModule `since it was was not exported from `SharedModule`

**Comment by michaeljota** [comment]
There are certain modules, mainly the one in Browser, that you will need to load only once.
Your application will be able to use those service widely because, for Angular all of the modules will be part of only one big module.

**Comment by maksonhan** [comment]
i solved problem by import CommonModule in shared module( and delete BrowserModule and BrowserAnimationModule here) and import BrowserAnimationModule in app module

**Comment by intergleam** [comment]
so finally do I have to import both     BrowserModule and BrowserAnimationsModule in app.module? Because no other options work.

**Comment by michaeljota** [comment]
What you don't have to do, is import modules that have to be imported only once in app.module (Yes, both BrowserModule and BrowserAnimationsModule have to be imported only one).

**Comment by A-lee-201** [comment]
> browserAnimationsModule

Thanks!
