### ISSUE TITLE
Angular-cli build fails on jenkins with node-sass error

### ISSUE THREAD

**Issue by nehaagrawal** [angular/angular-cli#5690]
NPM: v3.10.10
Node: v6.10.0
OS: Linux
My team is trying to build a project created using angular-cli on Jenkins. 'npm install' command is failing with some node-sass error. We were really looking forward to building our production application using angular-cli but we this issue, we have started using webpack-starter-kit on github for now. I hope to resolve this issue. Please help.

During npm install I get some errors (see below)

[EnvInject] - Loading node environment variables.
Building remotely on *********(java nodejs el6.x86_64) in workspace /local/build/jenkins/cibuild/slave/workspace/blah/blahblah/blahblahblah
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
Cloning the remote Git repository
Cloning repository ssh://git@git.myCompany.com:somePort/blah/blahblah.git
 > /usr/local/blah/git-2.11.0/bin/git init /local/build/jenkins/cibuild/slave/workspace/blah/blahblah/blahblahblah # timeout=10
Fetching upstream changes from ssh://git@git.myCompany.com:somePort/blah/blahblah.git
 > /usr/local/devtools/git-2.11.0/bin/git --version # timeout=10
 > /usr/local/devtools/git-2.11.0/bin/git fetch --tags --progress ssh://git@git.myCompany.com:9102/awt/angular-starter-kit.git +refs/heads/*:refs/remotes/origin/*
 > /usr/local/devtools/git-2.11.0/bin/git config remote.origin.url ssh://git@git.myCompany.com:9102/awt/angular-starter-kit.git # timeout=10
 > /usr/local/devtools/git-2.11.0/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > /usr/local/devtools/git-2.11.0/bin/git config remote.origin.url ssh://git@git.myCompany.com:9102/awt/angular-starter-kit.git # timeout=10
Fetching upstream changes from ssh://git@git.myCompany.com:9102/awt/angular-starter-kit.git
 > /usr/local/devtools/git-2.11.0/bin/git fetch --tags --progress ssh://git@git.myCompany.com:9102/awt/angular-starter-kit.git +refs/heads/*:refs/remotes/origin/*
 > /usr/local/devtools/git-2.11.0/bin/git rev-parse origin/master^{commit} # timeout=10
Checking out Revision 2db6c325d349f06d5e97fe7fe4f9590e29717696 (origin/master)
 > /usr/local/devtools/git-2.11.0/bin/git config core.sparsecheckout # timeout=10
 > /usr/local/devtools/git-2.11.0/bin/git checkout -f 2db6c325d349f06d5e97fe7fe4f9590e29717696
 > /usr/local/devtools/git-2.11.0/bin/git rev-list 2db6c325d349f06d5e97fe7fe4f9590e29717696 # timeout=10
 > /usr/local/devtools/git-2.11.0/bin/git tag -a -f -m Jenkins Build #76 jenkins-Angular2Build-76 # timeout=10
[Angular2Build] $ /bin/sh -xe /build/tmp/hudson557220114582388009.sh
+ /u1/cibuild/devtools/thirdparty/nodejs/nodejs-v6.10.0/node-v6.10.0-linux-x64/bin/node /u1/cibuild/devtools/thirdparty/nodejs/nodejs-v6.10.0/node-v6.10.0-linux-x64/bin/npm install
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN prefer global node-gyp@3.6.0 should be installed with -g

> node-sass@4.5.1 install /local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.1/linux-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.1/linux-x64-48_binding.node": 

connect ECONNREFUSED 192.30.253.113:443

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> phantomjs-prebuilt@2.1.7 install /local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading http://artifactory.myCompany.com:8081/artifactory/blk-npm/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Received 22866K total.
Extracting tar contents (via spawned process)
Removing /local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1490623846195/phantomjs-2.1.1-linux-x86_64 -> /local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> node-sass@4.5.1 postinstall /local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build/node_modules/node-sass
> node scripts/build.js

Building: /u1/cibuild/devtools/thirdparty/nodejs/nodejs-v6.10.0/node-v6.10.0-linux-x64/bin/node /local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/u1/cibuild/devtools/thirdparty/nodejs/nodejs-v6.10.0/node-v6.10.0-linux-x64/bin/node',
gyp verb cli   '/local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.0
gyp info using node@6.10.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.6.6\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.10.0
gyp verb command install [ '6.10.0' ]
gyp verb install input version string "6.10.0"
gyp verb install installing version: 6.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 6.10.0
gyp verb ensuring nodedir is created /u1/cibuild/.node-gyp/6.10.0
gyp verb created nodedir /u1/cibuild/.node-gyp/6.10.0
gyp http GET https://nodejs.org/download/release/v6.10.0/node-v6.10.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '6.10.0' ]
gyp verb remove using node-gyp dir: /u1/cibuild/.node-gyp
gyp verb remove removing target version: 6.10.0
gyp verb remove removing development files for version: 6.10.0
gyp ERR! configure error 
gyp ERR! stack Error: connect ECONNREFUSED 104.20.23.46:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Linux 2.6.32-642.13.1.el6.x86_64
gyp ERR! command "/u1/cibuild/devtools/thirdparty/nodejs/nodejs-v6.10.0/node-v6.10.0-linux-x64/bin/node" "/local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build/node_modules/node-sass
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 
Build failed with error code: 1
angular-starter-kit@0.0.0 /local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build
+-- @angular/common@2.4.8 
+-- @angular/compiler@2.4.8 
+-- @angular/compiler-cli@2.4.8 
| +-- @angular/tsc-wrapped@0.5.2 
| | `-- tsickle@0.2.6 
| +-- minimist@1.2.0 
| `-- reflect-metadata@0.1.10 
+-- @angular/core@2.4.8 
+-- @angular/forms@2.4.8 
+-- @angular/http@2.4.8 
+-- @angular/platform-browser@2.4.8 
+-- @angular/platform-browser-dynamic@2.4.8 
+-- @angular/router@3.4.8 
+-- @types/jasmine@2.5.43 
+-- @types/node@7.0.5 
+-- codelyzer@2.0.1 
| +-- app-root-path@2.0.1 
| +-- css-selector-tokenizer@0.7.0 
| | +-- cssesc@0.1.0 
| | +-- fastparse@1.1.1 
| | `-- regexpu-core@1.0.0 
| |   +-- regenerate@1.3.2 
| |   +-- regjsgen@0.2.0 
| |   `-- regjsparser@0.1.5 
| |     `-- jsesc@0.5.0 
| +-- cssauron@1.4.0 
| | `-- through@2.3.8 
| +-- semver-dsl@1.0.1 
| | `-- semver@5.3.0 
| +-- source-map@0.5.6 
| `-- sprintf-js@1.0.3 
+-- core-js@2.4.1 
+-- cpx@1.5.0 
| +-- babel-runtime@6.23.0 
| | `-- regenerator-runtime@0.10.3 
| +-- chokidar@1.6.1 
| | +-- anymatch@1.3.0 
| | | `-- micromatch@2.3.11 
| | |   +-- arr-diff@2.0.0 
| | |   | `-- arr-flatten@1.0.1 
| | |   +-- braces@1.8.5 
| | |   | +-- expand-range@1.8.2 
| | |   | | `-- fill-range@2.2.3 
| | |   | |   +-- is-number@2.1.0 
| | |   | |   +-- isobject@2.1.0 
| | |   | |   +-- randomatic@1.1.6 
| | |   | |   `-- repeat-string@1.6.1 
| | |   | +-- preserve@0.2.0 
| | |   | `-- repeat-element@1.1.2 
| | |   +-- expand-brackets@0.1.5 
| | |   | `-- is-posix-bracket@0.1.1 
| | |   +-- extglob@0.3.2 
| | |   +-- filename-regex@2.0.0 
| | |   +-- kind-of@3.1.0 
| | |   | `-- is-buffer@1.1.5 
| | |   +-- normalize-path@2.0.1 
| | |   +-- object.omit@2.0.1 
| | |   | +-- for-own@0.1.5 
| | |   | | `-- for-in@1.0.2 
| | |   | `-- is-extendable@0.1.1 
| | |   +-- parse-glob@3.0.4 
| | |   | +-- glob-base@0.3.0 
| | |   | `-- is-dotfile@1.0.2 
| | |   `-- regex-cache@0.4.3 
| | |     +-- is-equal-shallow@0.1.3 
| | |     `-- is-primitive@2.0.0 
| | +-- async-each@1.0.1 
| | +-- glob-parent@2.0.0 
| | +-- inherits@2.0.3 
| | +-- is-binary-path@1.0.1 
| | | `-- binary-extensions@1.8.0 
| | +-- is-glob@2.0.1 
| | | `-- is-extglob@1.0.0 
| | +-- path-is-absolute@1.0.1 
| | `-- readdirp@2.1.0 
| |   +-- readable-stream@2.2.6 
| |   | +-- buffer-shims@1.0.0 
| |   | +-- isarray@1.0.0 
| |   | +-- process-nextick-args@1.0.7 
| |   | `-- util-deprecate@1.0.2 
| |   `-- set-immediate-shim@1.0.1 
| +-- duplexer@0.1.1 
| +-- glob@7.1.1 
| | +-- fs.realpath@1.0.0 
| | +-- inflight@1.0.6 
| | | `-- wrappy@1.0.2 
| | `-- once@1.4.0 
| +-- glob2base@0.0.12 
| | `-- find-index@0.1.1 
| +-- minimatch@3.0.3 
| | `-- brace-expansion@1.1.6 
| |   +-- balanced-match@0.4.2 
| |   `-- concat-map@0.0.1 
| +-- mkdirp@0.5.1 
| | `-- minimist@0.0.8 
| +-- resolve@1.3.2 
| | `-- path-parse@1.0.5 
| +-- safe-buffer@5.0.1 
| +-- shell-quote@1.6.1 
| | +-- array-filter@0.0.1 
| | +-- array-map@0.0.0 
| | +-- array-reduce@0.0.0 
| | `-- jsonify@0.0.0 
| `-- subarg@1.0.0 
+-- jasmine-core@2.5.2 
+-- jasmine-spec-reporter@2.7.0 
| `-- colors@1.1.2 
+-- karma@1.5.0 
| +-- bluebird@3.5.0 
| +-- body-parser@1.17.1 
| | +-- bytes@2.4.0 
| | +-- content-type@1.0.2 
| | +-- debug@2.6.1 
| | | `-- ms@0.7.2 
| | +-- depd@1.1.0 
| | +-- http-errors@1.6.1 
| | | +-- setprototypeof@1.0.3 
| | | `-- statuses@1.3.1 
| | +-- iconv-lite@0.4.15 
| | +-- on-finished@2.3.0 
| | | `-- ee-first@1.1.1 
| | +-- qs@6.4.0 
| | +-- raw-body@2.2.0 
| | | +-- bytes@2.4.0 
| | | `-- unpipe@1.0.0 
| | `-- type-is@1.6.14 
| |   `-- media-typer@0.3.0 
| +-- combine-lists@1.0.1 
| +-- connect@3.6.0 
| | +-- debug@2.6.1 
| | +-- finalhandler@1.0.0 
| | | +-- encodeurl@1.0.1 
| | | `-- escape-html@1.0.3 
| | +-- parseurl@1.3.1 
| | `-- utils-merge@1.0.0 
| +-- di@0.0.1 
| +-- dom-serialize@2.2.1 
| | +-- custom-event@1.0.1 
| | +-- ent@2.2.0 
| | +-- extend@3.0.0 
| | `-- void-elements@2.0.1 
| +-- expand-braces@0.1.2 
| | +-- array-slice@0.2.3 
| | +-- array-unique@0.2.1 
| | `-- braces@0.1.5 
| |   `-- expand-range@0.1.1 
| |     +-- is-number@0.1.1 
| |     `-- repeat-string@0.2.2 
| +-- graceful-fs@4.1.11 
| +-- http-proxy@1.16.2 
| | +-- eventemitter3@1.2.0 
| | `-- requires-port@1.0.0 
| +-- isbinaryfile@3.0.2 
| +-- lodash@3.10.1 
| +-- log4js@0.6.38 
| | +-- readable-stream@1.0.34 
| | | +-- core-util-is@1.0.2 
| | | +-- isarray@0.0.1 
| | | `-- string_decoder@0.10.31 
| | `-- semver@4.3.6 
| +-- mime@1.3.4 
| +-- optimist@0.6.1 
| | +-- minimist@0.0.10 
| | `-- wordwrap@0.0.2 
| +-- qjobs@1.1.5 
| +-- range-parser@1.2.0 
| +-- rimraf@2.6.1 
| +-- socket.io@1.7.3 
| | +-- debug@2.3.3 
| | +-- engine.io@1.8.3 
| | | +-- accepts@1.3.3 
| | | | `-- negotiator@0.6.1 
| | | +-- base64id@1.0.0 
| | | +-- cookie@0.3.1 
| | | +-- debug@2.3.3 
| | | +-- engine.io-parser@1.3.2 
| | | | +-- after@0.8.2 
| | | | +-- arraybuffer.slice@0.0.6 
| | | | +-- base64-arraybuffer@0.1.5 
| | | | +-- blob@0.0.4 
| | | | `-- wtf-8@1.0.0 
| | | `-- ws@1.1.2 
| | |   +-- options@0.0.6 
| | |   `-- ultron@1.0.2 
| | +-- has-binary@0.1.7 
| | | `-- isarray@0.0.1 
| | +-- object-assign@4.1.0 
| | +-- socket.io-adapter@0.5.0 
| | | `-- debug@2.3.3 
| | +-- socket.io-client@1.7.3 
| | | +-- backo2@1.0.2 
| | | +-- component-bind@1.0.0 
| | | +-- component-emitter@1.2.1 
| | | +-- debug@2.3.3 
| | | +-- engine.io-client@1.8.3 
| | | | +-- component-emitter@1.2.1 
| | | | +-- component-inherit@0.0.3 
| | | | +-- debug@2.3.3 
| | | | +-- has-cors@1.1.0 
| | | | +-- parsejson@0.0.3 
| | | | +-- parseqs@0.0.5 
| | | | +-- xmlhttprequest-ssl@1.5.3 
| | | | `-- yeast@0.1.2 
| | | +-- indexof@0.0.1 
| | | +-- object-component@0.0.3 
| | | +-- parseuri@0.0.5 
| | | | `-- better-assert@1.0.2 
| | | |   `-- callsite@1.0.0 
| | | `-- to-array@0.1.4 
| | `-- socket.io-parser@2.3.1 
| |   +-- component-emitter@1.1.2 
| |   +-- debug@2.2.0 
| |   | `-- ms@0.7.1 
| |   +-- isarray@0.0.1 
| |   `-- json3@3.3.2 
| +-- tmp@0.0.31 
| | `-- os-tmpdir@1.0.2 
| `-- useragent@2.1.13 
|   `-- lru-cache@2.2.4 
+-- karma-chrome-launcher@2.0.0 
| +-- fs-access@1.0.1 
| | `-- null-check@1.0.0 
| `-- which@1.2.14 
|   `-- isexe@2.0.0 
+-- karma-cli@1.0.1 
+-- karma-coverage-istanbul-reporter@0.2.0 
| `-- istanbul-api@1.1.7 
|   +-- async@2.2.0 
|   +-- fileset@2.0.3 
|   +-- istanbul-lib-coverage@1.0.2 
|   +-- istanbul-lib-hook@1.0.5 
|   | `-- append-transform@0.4.0 
|   |   `-- default-require-extensions@1.0.0 
|   +-- istanbul-lib-instrument@1.7.0 
|   | +-- babel-generator@6.24.0 
|   | | +-- babel-messages@6.23.0 
|   | | +-- detect-indent@4.0.0 
|   | | +-- jsesc@1.3.0 
|   | | `-- trim-right@1.0.1 
|   | +-- babel-template@6.23.0 
|   | +-- babel-traverse@6.23.1 
|   | | +-- debug@2.6.3 
|   | | +-- globals@9.17.0 
|   | | `-- invariant@2.2.2 
|   | |   `-- loose-envify@1.3.1 
|   | +-- babel-types@6.23.0 
|   | | `-- to-fast-properties@1.0.2 
|   | `-- babylon@6.16.1 
|   +-- istanbul-lib-report@1.0.0 
|   | `-- supports-color@3.2.3 
|   |   `-- has-flag@1.0.0 
|   +-- istanbul-lib-source-maps@1.1.1 
|   +-- istanbul-reports@1.0.2 
|   | `-- handlebars@4.0.6 
|   |   +-- async@1.5.2 
|   |   +-- optimist@0.6.1 
|   |   | `-- minimist@0.0.10 
|   |   +-- source-map@0.4.4 
|   |   | `-- amdefine@1.0.1 
|   |   `-- uglify-js@2.8.16 
|   |     +-- uglify-to-browserify@1.0.2 
|   |     `-- yargs@3.10.0 
|   |       +-- camelcase@1.2.1 
|   |       +-- cliui@2.1.0 
|   |       | +-- center-align@0.1.3 
|   |       | | +-- align-text@0.1.4 
|   |       | | | `-- longest@1.0.1 
|   |       | | `-- lazy-cache@1.0.4 
|   |       | `-- right-align@0.1.3 
|   |       +-- decamelize@1.2.0 
|   |       `-- window-size@0.1.0 
|   `-- js-yaml@3.7.0 
|     +-- argparse@1.0.9 
|     `-- esprima@2.7.3 
+-- karma-jasmine@1.1.0 
+-- karma-phantomjs-launcher@1.0.2 
| `-- lodash@4.17.4 
+-- phantomjs-polyfill@0.0.2 
+-- phantomjs-prebuilt@2.1.7 
| +-- extract-zip@1.5.0 
| | +-- concat-stream@1.5.0 
| | | +-- readable-stream@2.0.6 
| | | `-- typedarray@0.0.6 
| | +-- debug@0.7.4 
| | +-- mkdirp@0.5.0 
| | | `-- minimist@0.0.8 
| | `-- yauzl@2.4.1 
| |   `-- fd-slicer@1.0.1 
| |     `-- pend@1.2.0 
| +-- fs-extra@0.26.7 
| | +-- jsonfile@2.4.0 
| | `-- klaw@1.3.1 
| +-- hasha@2.2.0 
| | +-- is-stream@1.1.0 
| | `-- pinkie-promise@2.0.1 
| +-- kew@0.7.0 
| +-- progress@1.1.8 
| +-- request@2.67.0 
| | +-- aws-sign2@0.6.0 
| | +-- bl@1.0.3 
| | | `-- readable-stream@2.0.6 
| | +-- caseless@0.11.0 
| | +-- combined-stream@1.0.5 
| | | `-- delayed-stream@1.0.0 
| | +-- forever-agent@0.6.1 
| | +-- form-data@1.0.1 
| | +-- har-validator@2.0.6 
| | | +-- commander@2.9.0 
| | | | `-- graceful-readlink@1.0.1 
| | | `-- is-my-json-valid@2.16.0 
| | |   +-- generate-function@2.0.0 
| | |   +-- generate-object-property@1.2.0 
| | |   | `-- is-property@1.0.2 
| | |   `-- jsonpointer@4.0.1 
| | +-- hawk@3.1.3 
| | | +-- boom@2.10.1 
| | | +-- cryptiles@2.0.5 
| | | +-- hoek@2.16.3 
| | | `-- sntp@1.0.9 
| | +-- http-signature@1.1.1 
| | | +-- assert-plus@0.2.0 
| | | +-- jsprim@1.4.0 
| | | | +-- assert-plus@1.0.0 
| | | | +-- extsprintf@1.0.2 
| | | | +-- json-schema@0.2.3 
| | | | `-- verror@1.3.6 
| | | `-- sshpk@1.11.0 
| | |   +-- asn1@0.2.3 
| | |   +-- assert-plus@1.0.0 
| | |   +-- bcrypt-pbkdf@1.0.1 
| | |   +-- dashdash@1.14.1 
| | |   | `-- assert-plus@1.0.0 
| | |   +-- ecc-jsbn@0.1.1 
| | |   +-- getpass@0.1.6 
| | |   | `-- assert-plus@1.0.0 
| | |   +-- jodid25519@1.0.2 
| | |   +-- jsbn@0.1.1 
| | |   `-- tweetnacl@0.14.5 
| | +-- is-typedarray@1.0.0 
| | +-- isstream@0.1.2 
| | +-- json-stringify-safe@5.0.1 
| | +-- mime-types@2.1.15 
| | | `-- mime-db@1.27.0 
| | +-- node-uuid@1.4.8 
| | +-- oauth-sign@0.8.2 
| | +-- qs@5.2.1 
| | +-- stringstream@0.0.5 
| | +-- tough-cookie@2.2.2 
| | `-- tunnel-agent@0.4.3 
| `-- request-progress@2.0.1 
|   `-- throttleit@1.0.0 
+-- rxjs@5.2.0 
| `-- symbol-observable@1.0.4 
+-- ts-helpers@1.1.2 
+-- ts-node@2.1.0 
| +-- arrify@1.0.1 
| +-- chalk@1.1.3 
| | +-- ansi-styles@2.2.1 
| | +-- escape-string-regexp@1.0.5 
| | +-- has-ansi@2.0.0 
| | | `-- ansi-regex@2.1.1 
| | +-- strip-ansi@3.0.1 
| | `-- supports-color@2.0.0 
| +-- diff@3.2.0 
| +-- make-error@1.2.3 
| +-- pinkie@2.0.4 
| +-- source-map-support@0.4.14 
| +-- tsconfig@5.0.3 
| | +-- any-promise@1.3.0 
| | +-- parse-json@2.2.0 
| | | `-- error-ex@1.3.1 
| | |   `-- is-arrayish@0.2.1 
| | +-- strip-bom@2.0.0 
| | | `-- is-utf8@0.2.1 
| | `-- strip-json-comments@2.0.1 
| +-- v8flags@2.0.11 
| | `-- user-home@1.1.1 
| +-- xtend@4.0.1 
| `-- yn@1.2.0 
+-- tslint@4.4.2 
| +-- babel-code-frame@6.22.0 
| | +-- esutils@2.0.2 
| | `-- js-tokens@3.0.1 
| +-- findup-sync@0.3.0 
| | `-- glob@5.0.15 
| +-- optimist@0.6.1 
| | `-- minimist@0.0.10 
| `-- update-notifier@1.0.3 
|   +-- boxen@0.6.0 
|   | +-- ansi-align@1.1.0 
|   | | `-- string-width@1.0.2 
|   | |   `-- is-fullwidth-code-point@1.0.0 
|   | +-- camelcase@2.1.1 
|   | +-- cli-boxes@1.0.0 
|   | +-- filled-array@1.1.0 
|   | +-- object-assign@4.1.1 
|   | +-- repeating@2.0.1 
|   | | `-- is-finite@1.0.2 
|   | +-- string-width@1.0.2 
|   | | +-- code-point-at@1.1.0 
|   | | `-- is-fullwidth-code-point@1.0.0 
|   | |   `-- number-is-nan@1.0.1 
|   | `-- widest-line@1.0.0 
|   |   `-- string-width@1.0.2 
|   |     `-- is-fullwidth-code-point@1.0.0 
|   +-- configstore@2.1.0 
|   | +-- dot-prop@3.0.0 
|   | | `-- is-obj@1.0.1 
|   | +-- osenv@0.1.4 
|   | +-- uuid@2.0.3 
|   | `-- write-file-atomic@1.3.1 
|   |   +-- imurmurhash@0.1.4 
|   |   `-- slide@1.1.6 
|   +-- is-npm@1.0.0 
|   +-- latest-version@2.0.0 
|   | `-- package-json@2.4.0 
|   |   +-- got@5.7.1 
|   |   | +-- create-error-class@3.0.2 
|   |   | | `-- capture-stack-trace@1.0.0 
|   |   | +-- duplexer2@0.1.4 
|   |   | +-- is-redirect@1.0.0 
|   |   | +-- is-retry-allowed@1.1.0 
|   |   | +-- lowercase-keys@1.0.0 
|   |   | +-- node-status-codes@1.0.0 
|   |   | +-- read-all-stream@3.1.0 
|   |   | +-- timed-out@3.1.3 
|   |   | +-- unzip-response@1.0.2 
|   |   | `-- url-parse-lax@1.0.0 
|   |   |   `-- prepend-http@1.0.4 
|   |   +-- registry-auth-token@3.1.0 
|   |   | `-- rc@1.1.7 
|   |   |   +-- deep-extend@0.4.1 
|   |   |   `-- ini@1.3.4 
|   |   `-- registry-url@3.1.0 
|   +-- lazy-req@1.1.0 
|   +-- semver-diff@2.1.0 
|   `-- xdg-basedir@2.0.0 
|     `-- os-homedir@1.0.2 
+-- typescript@2.2.1 
`-- zone.js@0.7.8 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 2.6.32-642.13.1.el6.x86_64
npm ERR! argv "/u1/cibuild/devtools/thirdparty/nodejs/nodejs-v6.10.0/node-v6.10.0-linux-x64/bin/node" "/u1/cibuild/devtools/thirdparty/nodejs/nodejs-v6.10.0/node-v6.10.0-linux-x64/bin/npm" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.5.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.1 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build/npm-debug.log
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by filipesilva** [comment]
The error message you pasted here contains some helpful information about the error.

```
node-sass@4.5.1 install /local/build/jenkins/cibuild/slave/workspace/awt/angularStarterKit/Angular2Build/node_modules/node-sass
node scripts/install.js
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.1/linux-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.1/linux-x64-48_binding.node":

connect ECONNREFUSED 192.30.253.113:443

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

  export HTTP_PROXY=http://example.com:1234
or configure npm proxy via

  npm config set proxy http://example.com:8080
```

If you're having trouble installing `node-sass` or `phantomjs`, I suggest you open an issue on their issue tracker instead. They can give you better help.

In the latest version of Angular CLI (`1.0.0`) `node-sass` is also optional. If can try using that version and see if the error just goes away.

**Comment by kdekooter** [comment]
@filipesilva how do you make node-sass optional? Whenever I do an `npm install` it gets pulled in.
