### ISSUE TITLE
add function to refresh page if new code

### ISSUE THREAD

**Issue by Opticsponge** [angular/angular-cli#5695]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Desired functionality.

The problem I am trying to solve is...
Need an angular solution to alert users they need to refresh site, due to new code push.

As I am running apps in cloudfrount, I can't use webserver to help with this, I was thinking of somehow using output-hashing, but not sure how other people have solved this, but seems it would nice addition

**Comment by delasteve** [comment]
I would argue this is not within the scope of the CLI. The CLI is meant for creating, testing, and building your Angular solution. It doesn't deal with implementation details, such as informing users there's an upgrade available. This question would be best asked on StackOverflow, not here.

**Comment by Opticsponge** [comment]
I think you are right it is a slippery slope, yet I think if hashing is turned on it would be nice to have cli save a hash in a meta tag in root index.html and also save a text file with same hash

**Comment by clydin** [comment]
Is your goal to display a notification or simply ensure that users have the latest code available for use?
If it is the second, then a production build already supports long-term caching.  Ensure that your cache control headers are setup properly and you should be set.

**Comment by hansl** [comment]
This is not something we should control or do.

Your backend should know when there is a new push and keep a live/non-live connection with clients. This is entirely doable with scripts that are used during deploy, and deployment is not a case that the CLI covers.

Basically:

1. when deploying to your static content, also send the hash to your backend to keep in a database.
1. have clients ping the server API to know what's the latest hash.
1. if latest hash != hash of page, tell user to refresh.

Closing this as we won't support this use case, and it can/should be automated from outside the CLI.
