### ISSUE TITLE
Using ng set puts a new line character in scripts key value of an empty array

### ISSUE THREAD

**Issue by indcoder** [angular/angular-cli#5697]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

angular-cli: 1.0.0-beta.26
node: 7.4.0
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/compiler-cli: 2.4.10

### Repro steps.

This is not a major bug but rather something thats slighly off skew

When I run
`ng set defaults.styleExt scss`

I expected only one change in the angular-cli.json : in the styleExt key value but git was reporting two changes

### Desired functionality.

No new line in the empty array value of the scripts key

**Comment by indcoder** [comment]
<img width="960" alt="angularcli" src="https://cloud.githubusercontent.com/assets/2099300/24373567/5ebbbf94-134f-11e7-9157-74191cfbe595.png">

**Comment by sumitarora** [comment]
PR Merged: https://github.com/angular/angular-cli/commit/204d3126c66144069d97106d64d5d2638797e064
