### ISSUE TITLE
How to integrate purifycss plugin?

### ISSUE THREAD

**Issue by munjalpatel** [angular/angular-cli#5699]
Hello,

Is there any way I can easily integrate purifycss or similar plugins to remove all of the unused css rules from my final build output?

**Comment by filipesilva** [comment]
There is no way to do this, no. An addon system is planned for 2.x+ that would allow similar customizations.

**Comment by cynx** [comment]
similar customizations are now available?

**Comment by sergeome** [comment]
I add an answer that might help you in another discussion:
[Does this work for Angular 2? Any examples?](https://github.com/purifycss/purifycss/issues/122)
