### ISSUE TITLE
Invalid watchman found, version: [4.1.0] did not satisfy [^3.0.0], falling back to NodeWatcher.

### ISSUE THREAD

**Issue by arlowhite** [angular/angular-cli#57]
I realize this is probably upstream, but thought I'd mention it since you'll have to bump the ember-cli version to fix it.

angular-cli 0.0.10
ng --version
```
version: 1.13.8
Invalid watchman found, version: [4.1.0] did not satisfy [^3.0.0], falling back to NodeWatcher.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 0.12.7
npm: 2.14.8
os: linux x64
```
Ubuntu 15.10

As it seems to be recommended, I decided to install watchman.

When creating a new project (and with other commands), I see this message:
> Invalid watchman found, version: [4.1.0] did not satisfy [^3.0.0], falling back to NodeWatcher.

I've tried installing watchman 4.1, 3.9, 3.8 (from source using the git tag), but all of these versions show the warning.

For some reason, **watchman v3.7.0 is the one that works**.

Since watchman has been fixing some serious sounding bugs, it'd be nice to be able to use the latest version.
https://facebook.github.io/watchman/docs/release-notes.html

**Comment by tragiclifestories** [comment]
this seems to have been fixed by https://github.com/angular/angular-cli/commit/10eae9e8d5454d8e82c73b553b830cfb1749fd96

**Comment by cironunes** [comment]
@arlowhite, I'm closing this. Feel free to reopen if necessary
