### ISSUE TITLE
Using localIdentName from css-loader

### ISSUE THREAD

**Issue by munjalpatel** [angular/angular-cli#5700]
Hello,

Is there an easy way for me to configure `localIdentName` for the css-loader so that I can uniquely namespace all class names at the component level?

**Comment by clydin** [comment]
Angular handles this for you.  I'd suggest reading through the Angular guides; in particular this one on component styles: https://angular.io/docs/ts/latest/guide/component-styles.html

**Comment by filipesilva** [comment]
Closing as answered by @clydin, cheers!
