### ISSUE TITLE
How cli support postcss, angular-cli.json file how to configure

### ISSUE THREAD

**Issue by jiayisheji** [angular/angular-cli#5701]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.9.2
os: win32 x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Desired functionality.
How cli support postcss, .angular-cli.json file how to configure

**Comment by filipesilva** [comment]
We don't support postcss configuration in version 1 of the CLI. An addon system is planned for the future that would allow build customization though.
