### ISSUE TITLE
ng e2e not following protractor.conf.js baseUrl

### ISSUE THREAD

**Issue by ravenjohn** [angular/angular-cli#5705]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 7.7.3
os: linux x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Repro steps.

1. Change the `baseUrl` on `protractor.conf.js` to http://dev.sample.com
2. Run `ng e2e`

### The log given by the failure.

```
** NG Live Development Server is running on http://localhost:49152 **
```

### Desired functionality.

```
** NG Live Development Server is running on http://dev.sample.com **
```

### Mention any other details that might be useful.

This was working on version 1.0.0-beta.24

**Comment by ravenjohn** [comment]
Just found out about `--no-serve` in other issue and baseUrl worked. Closing this issue now.

**Comment by danieljin** [comment]
Worth adding this to the wiki. https://github.com/angular/angular-cli/wiki/e2e

**Comment by ganqqwerty** [comment]
Why is it closed? The base url change still doesn't work.
