### ISSUE TITLE
Uncaught TypeError: Cannot redefine property on global listener

### ISSUE THREAD

**Issue by tschaka1904** [angular/angular-cli#5706]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 7.4.0
os: darwin x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/compiler-cli: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/platform-server: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0

### Repro steps.

In my index.html I have a global function, because of a third party dependency. I would love to treat this dependency different, but I needs to call the global scope.

> index.html
`<script>
 function onDiagramReady() {
    window.dispatchEvent(new CustomEvent('onDiagramReady', {detail: this.Diagram}));
  }
</script>`

The problem is, after changing to Angular 4.0, I get this error: 
`Uncaught TypeError: Cannot redefine property: onReactomeDiagramReady
    at Function.defineProperty (<anonymous>)
    at patchProperty (zone.js:1235)
    at patchOnProperties (zone.js:1246)
    at propertyDescriptorPatch (zone.js:1795)
    at zone.js:1951
    at NO_ZONE.name (zone.js:9)
    at Object.<anonymous> (zone.js:12)
    at Object.<anonymous> (zone.js:2067)
    at __webpack_require__ (bootstrap f7e4e75…:52)
    at Object.<anonymous> (polyfills.ts:1)
    at __webpack_require__ (bootstrap f7e4e75…:52)
    at Object.<anonymous> (zone.js:2067)
    at __webpack_require__ (bootstrap f7e4e75…:52)
    at webpackJsonpCallback (bootstrap f7e4e75…:23)
    at polyfills.bundle.js:1
patchProperty @ zone.js:1235
patchOnProperties @ zone.js:1246
propertyDescriptorPatch @ zone.js:1795
(anonymous) @ zone.js:1951
NO_ZONE.name @ zone.js:9
(anonymous) @ zone.js:12
(anonymous) @ zone.js:2067
__webpack_require__ @ bootstrap f7e4e75…:52
(anonymous) @ polyfills.ts:1
__webpack_require__ @ bootstrap f7e4e75…:52
(anonymous) @ zone.js:2067
__webpack_require__ @ bootstrap f7e4e75…:52
webpackJsonpCallback @ bootstrap f7e4e75…:23
(anonymous) @ polyfills.bundle.js:1`

Everything seems to work fine, but I've this error on my console and I'm not sure what to do about it.

**Comment by filipesilva** [comment]
I'm sorry but this doesn't seem to be a bug with the CLI itself. It seems to be an application runtime error, as we don't build anything differently in those cases. 

I'm happy to reopen if there's a simple repro you can provide that shows how it's CLI bug.
