### ISSUE TITLE
Module not found: Error: Can't resolve '@angular/http/testing/src/mock_backend'

### ISSUE THREAD

**Issue by jordivila** [angular/angular-cli#5707]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 7.0.0
os: win32 x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Repro steps.

Added a module that uses MockBackend, "ng build --prod" fails. No error thrown when executing "ng build"

[repo sample](https://github.com/jordivila/angular4_mockbackend_fail_when_aot)

### The log given by the failure.

ERROR in ./src/$$_gendir/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve '@angular/http/testing/src/mock_backend' in 'C:\Users\XXXXX\Documents\GitHub\angularCliStableFirst\src\$$_gendir\app'
 @ ./src/$$_gendir/app/app.module.ngfactory.ts 25:0-66
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by lothArkady** [comment]
We have quite the same issue when trying to include isPropertyUpdated from @angular/forms/src/directives/shared

import {isPropertyUpdated} from "@angular/forms/src/directives/shared";
Module not found: Error: Can't resolve '@angular/forms/src/directives'

It seems it is related to the fact that we try to include directly a declaration file rather than a module.

**Comment by wtospit** [comment]
I'm facing this issue as well

**Comment by wtospit** [comment]
@lothArkady  It's already described in the below link that you shouldn't use deep import with angular module

https://angular-update-guide.firebaseapp.com/

**Comment by diicar** [comment]
Yeah the deep imports are not allowed.

**Comment by jordivila** [comment]
please take a look at [the repo I posted on the first message](https://github.com/jordivila/angular4_mockbackend_fail_when_aot). There is a module under [/src/app/core/services/http](https://github.com/jordivila/angular4_mockbackend_fail_when_aot/tree/master/src/app/core/services/http) which uses Mockbackend. Importing this module is done by `import { MockBackend, MockConnection } from '@angular/http/testing';` as [the angular docs mentioned](https://angular.io/docs/ts/latest/api/http/testing/index/MockBackend-class.html). That's why I think this is a bug and not a problem related to deep imports

**Comment by landesko** [comment]
@wtospit so what should we do instead?

**Comment by wtospit** [comment]
@jordivila @landesko  sorry for making a confusion, my reply is just for @lothArkady,
for our issue I still can't fix it yet.

**Comment by wtospit** [comment]
by the way I'm watching the issue [#15521](https://github.com/angular/angular/issues/15521) in angular repo, It seems somebody is facing the issue as well

**Comment by jordivila** [comment]
@wtospit [15521](https://github.com/angular/angular/issues/15521) looks similar but I'm not sure by reading the ticket if the application can run without AoT. This issue is related only to building the application with --prod flag as far as ng serve runs ok.

**Comment by vascofernandes** [comment]
Same problem in Aot.

**Comment by filipesilva** [comment]
Closing because this seems to be an issue in Angular itself that's being tracked in https://github.com/angular/angular/issues/15521.

**Comment by leocaseiro** [comment]
I had a similar issue, and I realised I added by mistake the "RouterTestingModule" instead of the "RouterModule".

The error message was:
```
ERROR in ./src/$$_gendir/app/modules/mymodule/mymodule.module.ngfactory.ts
Module not found: Error: Can't resolve '@angular/common/testing/src/location_mock' in '/Volumes/site/$$_gendir/app/modules/mymodule'
 @ ./src/$$_gendir/app/modules/mymodule/mymodule.module.ngfactory.ts 21:0-69
 @ ./Source/$$_gendir async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
```
