### ISSUE TITLE
Multiple api request in hierarchical components

### ISSUE THREAD

**Issue by Niraj-Sharma** [angular/angular-cli#5708]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.10.0
os: win32 x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Repro steps.
Note: I am working on e-learning modules which has components like
Learning Tracks > Courses > Units > Items
1. Create different components e.g. Track, course, unit,item etc
2. Manage component hierarchy as "Track > Course > Unit > Item"
3.  Each component has http calls on onInit using @Input as "parent id" e.g. course using trackid as input, to display all courses(embedding course component) of track and so on for rest child component in hierarchy.
4. if i have 2 track each containing 2 courses and each courses with 2 units and each unit with 4 items.
5. we have 1 call for track, 2 call for courses(c1 and c2), 4 calls for unit(c1-u1,c1-u2,c2-u1,c2-u2), 16 calls for items
4. but if i see total api request count for items it shows 64 calls..seems approx 4 times 

### The log given by the failure.
NA

### Desired functionality.
Number of api calls should be as per component calls

**Comment by sumitarora** [comment]
@Niraj-Sharma Check if your components are being initialized multiple times while running the project? Also, this doesn't seem to be `Angular CLI` issue?

**Comment by Niraj-Sharma** [comment]
Thanks sumitarora..
