### ISSUE TITLE
ng serve ignores SCSS and doesn't compile it

### ISSUE THREAD

**Issue by psaussure** [angular/angular-cli#5710]
### Bug Report or Feature Request
- [x] bug report
- [ ] feature request

### Versions.
```
@angular/cli: 1.0.0
node: 7.7.2
os: win32 x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
```

### Repro steps.
I have a global styles.scss file. Containing for example my main loader scss and a couple of imports.
While running `ng serve` the SCSS is not rendered. Only the comments are visible. 

Here is the result in chrome:
```
<style type="text/css">/*Base Font Size*/
/* Colors */
/* Base Font color */
/*control*/
/*Blues*/
/*Reds*/
/*Pinks*/
/*Greys*/
/* MEDIA QUERIES - REM*/
/* Mixins*/
</style>
```
So nothing here. I looked around in all the inline css produced by ng serve and it doesn't contain the compile CSS from my SCSS file.

#### Content of .angular-cli.json styles section:
```
"styles": [
        "../node_modules/font-awesome/css/font-awesome.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "../node_modules/angular2-toaster/toaster.css",
        "styles.scss"
      ],
```

### Desired functionality.
I would like, using `ng serve` command, to be able to have my SCSS rendered and compiled by angular CLI.

### Mention any other details that might be useful.
I tried to install sass-loader without more success.

I think running ng serve -prod, since it builds a css bundle, works. But it's not a proper solution for me since I need development environment.

**Comment by demirk4n** [comment]
@psaussure 
Where are the files you actually import are located? On the same level of styles.scss? Could it be that style.scss can't find the files to import?

I am using similar scss imports in my Angular 4.0 app and couldn't reproduce your problem for both serve and prod.

[angular-material-demo/src/angular-material-demo-theme.scss](https://github.com/demirk4n/angular-material-demo/blob/master/src/angular-material-demo-theme.scss)

**Comment by psaussure** [comment]
Some loader actually didn't install properly with npm install and something messed the scss files. After further analysis and multiple reinstalls, everything seems to work properly. 

I will then close this issue as it's only related to my dev environment and not CLI.
