### ISSUE TITLE
ngc exits with base64 is not a function

### ISSUE THREAD

**Issue by lexon0011** [angular/angular-cli#5711]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

node --version: v4.4.7
npm --version: 4.4.1

### Repro steps.

1. Download the attached sample
2. Open console (cmd in our case) and navigate to the base directory (where the package.json is located)
2. run `npm install`
3. run `"node_modules/.bin/ngc" -p src/tsconfig-aot.json`

### The log given by the failure.

![base64error](https://cloud.githubusercontent.com/assets/16290662/24402313/413a47a6-13b8-11e7-937b-745515dc135d.png)

### Mention any other details that might be useful.
[quickstart_aot.zip](https://github.com/angular/angular-cli/files/875416/quickstart_aot.zip)

**Comment by Meligy** [comment]
I might be because you have a non supported version of Node.

As per [README](https://github.com/angular/angular-cli#prerequisites):

> Both the CLI and generated project have dependencies that require Node 6.9.0 or higher, together with NPM 3 or higher.

**Comment by lexon0011** [comment]
It works with the current node version. Thanks!
