### ISSUE TITLE
run ng e2e without running the server ?

### ISSUE THREAD

**Issue by amineparis** [angular/angular-cli#5712]
I make many iterations when defining e2e test cases.  After each single modification I run `ng e2e` which makes 30 seconds to run the server before launching test cases. 

Is theire a way to run `ng serve ` **once** and use the same server each time I run `ng e2e ` without running a new server

**Comment by clydin** [comment]
You can run ng serve in one terminal and then ng e2e with the --no-serve option in another.

**Comment by amineparis** [comment]
TY. this should be documented ASAP

**Comment by sumitarora** [comment]
@amineparis @clydin Added to docs PR https://github.com/angular/angular-cli/pull/5633/commits/b590a04e2f4343b2cb002ac190650524962355a7

**Comment by amineparis** [comment]
@sumitarora  think to add it to[ e2e wiki page]( https://github.com/angular/angular-cli/wiki/e2e)

**Comment by sumitarora** [comment]
@amineparis Docs get published when we do release. Should be published with next release.

**Comment by Manzurkds** [comment]
This doesn't work now, it says 
`Unknown option: 'no-serve`
