### ISSUE TITLE
Project not recognised after upgrade

### ISSUE THREAD

**Issue by legolas** [angular/angular-cli#5714]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

angular-cli: 1.0.0-beta.21
node: 6.9.5
os: linux x64

### Repro steps.

npm uninstall -g angular-cli
npm uninstall --save-dev
npm cache clean
npm install -g @angular/cli@latest
npm install --save-dev @angular/cli@latest

npm update
ng serve

### The log given by the failure.

You have to be inside an angular-cli project in order to use the serve command.

### Desired functionality.

I have even copied my angular-cli.json to .angular-cli.json to no avail.

**Comment by sumitarora** [comment]
@legolas what version of CLI you get after installing it globally. You should see something as below.
```shell
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: local (v1.0.0, branch: fix-wiki-docs)
node: 7.5.0
os: darwin x64
@angular/compiler: 4.0.0
@angular/compiler-cli: 4.0.0
@angular/core: 4.0.0
```

**Comment by legolas** [comment]
Hi, here is the version info for the global
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.9.5
os: linux x64

**Comment by legolas** [comment]
This morning, back at work, I first renamed `angular-cli.json` to `.angular-cli.json` then ran `ng serve` again with this result:
```
Environment configuration does not contain "environmentSource" entry.

A new environmentSource entry replaces the previous source entry inside environments.

To migrate angular-cli.json follow the example below:

Before:

"environments": {
  "source": "environments/environment.ts",
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}


After:

"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}
```
Then I again ran `ng serve` giving me a bunch of compilation errors I had not seen before the update, fixed those as well, but one:
```
ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/home/marcel/loket/frontend/src/main/angular/node_modules/typescript/lib/typescript.js:9514:20)
    at Object.createCompilerHost (/home/marcel/loket/frontend/src/main/angular/node_modules/typescript/lib/typescript.js:63770:26)
    at Object.ngcLoader (/home/marcel/loket/frontend/src/main/angular/node_modules/@ngtools/webpack/src/loader.js:338:33)
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```
The version info currently says:
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.9.5
os: linux x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
```

**Comment by RicardoVaranda** [comment]
Hi @legolas ,

Could you please remove your node_modules and do a fresh npm install.

Make sure you move the tsconfig from src folder to the root of the project also :)

**Comment by legolas** [comment]
Thank you for your response, I have removed the `npm_modules` directory several times now, but I've done it again followed by `npm install` and moved the `tsconfig.json`to project root.
The latter resulted in `ENOENT: no such file or directory, stat '/home/marcel/dev/rws/dso/pr02/loket/frontend/src/main/angular/src/tsconfig.json'`.

**Comment by RicardoVaranda** [comment]
Sounds like you still have the old version of angular-cli.json, I would recommend creating a new project and copying the new one over and applying your personal changes.

New one looks like the following:
![image](https://cloud.githubusercontent.com/assets/6951312/24456106/db8af1a8-1489-11e7-874c-40a6936e2f67.png)

**Comment by legolas** [comment]
Thanks, 

After my previous reply I moved the tsconfig.json file back to its initial location, after that the code started compiling correctly. It scares me though that I do not understand what the actual reason is.
But it is working now.
