### ISSUE TITLE
ng new should place you in the generated directory

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#572]
Currently, if a user wants to generate an app and serve it's content they need to do the following:
```
npm install -g angular-cli
ng new my-dream-app
cd my-dream-app
ng serve
```
We could cut out the `cd my-dream-app` step by having `ng new` place you in the generated folder.

**Comment by filipesilva** [comment]
Huh, it seems it can't be done?
http://stackoverflow.com/questions/19563737/change-current-directory-with-node

**Comment by hansl** [comment]
Can't be done for the parent process. One way would be to have a function in bash for `ng`, but that's unrealistic. Closing this as can't be done.
