### ISSUE TITLE
can't load lazy module with eject

### ISSUE THREAD

**Issue by guzuomuse** [angular/angular-cli#5721]
Output from: `ng --version`.

> @angular/cli: 1.0.0 (e)
> node: 6.9.5
> os: win32 x64
> @angular/common: 4.0.0
> @angular/compiler: 4.0.0
> @angular/core: 4.0.0
> @angular/forms: 4.0.0
> @angular/http: 4.0.0
> @angular/platform-browser: 4.0.0
> @angular/platform-browser-dynamic: 4.0.0
> @angular/router: 4.0.0
> @angular/cli: 1.0.0
> @angular/compiler-cli: 4.0.0

when using eject, we can't make lazy module work; access the route,just get something like 

` Cannot GET /here_is_the_lazy_module_route`

 
but "npm start" without error;

other routes binding on main module work right.

and "ng server" also works right ,if disable eject  (in .angular-cli.json file  “”ejected:false“”)

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
