### ISSUE TITLE
ng new could have a skip-e2e option

### ISSUE THREAD

**Issue by agoncal** [angular/angular-cli#5724]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

1.0.0

### Desired functionality.

At the moment the `ng new` command has some very helpful options to customize the way we want to create a new project (`--skip-commit`, `-skip-tests`, `--skip-git`,  `--routing`, `--skip-install`). It would be useful in some cases to have a `--skip-e2e` option. Activating this option would not create the `e2e` folder, would skip the `protractor.conf.js` file as well as the `protractor` dependencies.

WDYT ?

**Comment by dave11mj** [comment]
I like the suggestions, specially since when I first ran `--skip-tests` I was surprised to see `e2e` since thats technically a test.

**Comment by agoncal** [comment]
I just gave it a try. I've created a new Angular project with the `--skip-e2e` option. Most of the e2e files are gone, expect `tsconfig.e2e.json` which is under the `e2e` directory.

I think this file shouldn't be there at all. WDYT ?

**Comment by shumy** [comment]
I can't make it work!
@angular/cli: 1.4.5
node: 6.11.4
os: linux x64

$ ng new viu-ui --dry-run --skip-tests --skip-e2e --skip-git --style=stylus
The option '--skip-e2e' is not registered with the new command. Run `ng new --help` for a list of supported options.
  create viu-ui/README.md (1021 bytes)
  create viu-ui/.angular-cli.json (1247 bytes)
  create viu-ui/.editorconfig (245 bytes)
  create viu-ui/src/assets/.gitkeep (0 bytes)
  create viu-ui/src/environments/environment.prod.ts (51 bytes)
  create viu-ui/src/environments/environment.ts (387 bytes)
  create viu-ui/src/favicon.ico (5430 bytes)
  create viu-ui/src/index.html (292 bytes)
  create viu-ui/src/main.ts (370 bytes)
  create viu-ui/src/polyfills.ts (2498 bytes)
  create viu-ui/src/styles.stylus (80 bytes)
  create viu-ui/src/test.ts (1085 bytes)
  create viu-ui/src/tsconfig.app.json (211 bytes)
  create viu-ui/src/tsconfig.spec.json (304 bytes)
  create viu-ui/src/typings.d.ts (104 bytes)
  create viu-ui/e2e/app.e2e-spec.ts (288 bytes)
  create viu-ui/e2e/app.po.ts (208 bytes)
  create viu-ui/e2e/tsconfig.e2e.json (235 bytes)
  create viu-ui/karma.conf.js (923 bytes)
  create viu-ui/package.json (1311 bytes)
  create viu-ui/protractor.conf.js (722 bytes)
  create viu-ui/tsconfig.json (363 bytes)
  create viu-ui/tslint.json (2968 bytes)
  create viu-ui/src/app/app.module.ts (314 bytes)
  create viu-ui/src/app/app.component.stylus (0 bytes)
  create viu-ui/src/app/app.component.html (1120 bytes)
  create viu-ui/src/app/app.component.ts (210 bytes)

**Comment by androidovshchik** [comment]
@shumy run `ng help new` and now there is no skip tests option
