### ISSUE TITLE
Can't get enough info about a ng build error

### ISSUE THREAD

**Issue by scot1289** [angular/angular-cli#5725]
### Bug Report or Feature Request (mark with an `x`)
```
- [] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 7.5.0
os: linux x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.10
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/compiler-cli: 2.4.8
@angular/cli: 1.0.0

### Repro steps.
ng build --prod

### The log given by the failure.
ERROR in ...$$_gendir/app/nav/sub-nav/sub-nav.component.ngfactory.ts (65,9): Supplied parameters do not match any signature of call target.

### Desired functionality.
I can't determine exactly where this error is because the ngfactory.ts file isn't generated. I got about 20 of these errors during build and can't find any of them and have to modify a file one at a time and rebuild to see if I fixed it or not.

**Comment by ctrl-brk** [comment]
It most likely refers to your sub-nav.component.ts file

**Comment by scot1289** [comment]
I finally figured it out. The function was a pipe.

**Comment by sumitarora** [comment]
Closing as above comment.

**Comment by dhilgarth** [comment]
I disagree with closing this. It is a very valid feature request! A lot of people are having these issues.
