### ISSUE TITLE
Details on how multiple apps are supposed to work

### ISSUE THREAD

**Issue by the-destro** [angular/angular-cli#5726]
- [X] feature request
 So there is the --app option for several command and apps has been an array in the .angular-cli.json for some time, however there is not really any documentation on what the supported use cases are.

**Comment by filipesilva** [comment]
It's true we're not documenting it yet. We should. It's a bit of an experimental feature at the moment.

**Comment by aifrim** [comment]
How about now? Is it still experimental?

**Comment by filipesilva** [comment]
No, it's not experimental anymore. In CLI 6 we made it official. You can read here https://github.com/angular/angular-cli/wiki/stories-multiple-projects about how to use it.
