### ISSUE TITLE
Cannot install @angular/cli

### ISSUE THREAD

**Issue by VisheshSingh** [angular/angular-cli#5727]
Hi,

I am trying to work on angular2 for which I have installed nodeJS. I have followed the steps given here [https://github.com/angular/angular-cli#prerequisites](url) but there seems to be an issue. Here's what I did in the Command Prompt(Admin):

`C:\WINDOWS\system32>node -v
v6.10.1

C:\WINDOWS\system32>npm -v
3.10.10

C:\WINDOWS\system32>npm install -g @angular/cli
[    ..............] / loadRequestedDeps: sill install loadAllDepsIntoIdealTree`

My command prompt is stuck at this command and shows no sign of response. I will be glad if there are any suggestions on solving this issue of mine.

**Comment by RicardoVaranda** [comment]
Hi @VisheshSingh ,

This sounds like a npm issue you should open an issue on that project instead.

After doing a quick search on that project, it seems to be related to this one:
https://github.com/npm/npm/issues/8685

**Comment by filipesilva** [comment]
@RicardoVaranda that sounds about right, thanks for looking up the right issue on the npm tracker 👍
