### ISSUE TITLE
how generate a new project with angular 2

### ISSUE THREAD

**Issue by Yura13** [angular/angular-cli#5731]
The latest version of angular-cli generates a new project with angular 4 by default. But I should use only angular 2 on the project. 

### Versions.
@angular/cli: 1.0.0
node: 6.10.0
npm: 3.10.10
os: Windows 10

### Desired functionality.
How can I generate a new project with angular 2?

**Comment by RicardoVaranda** [comment]
Hi @Yura13 ,

Currently the cli only supports creation of projects with the latest major release of Angular.

**Comment by Yura13** [comment]
Would the latest cli support creation of projects with angular 2?

**Comment by RicardoVaranda** [comment]
No, The last version to support creation of angular 2 projects was rc4.

**Comment by Yura13** [comment]
Thank you
