### ISSUE TITLE
Import simple class : Break at runtime

### ISSUE THREAD

**Issue by maxime1992** [angular/angular-cli#5736]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.0
node: 7.7.4
os: linux x64
```

### Repro steps.
```
git clone https://maxime1992@gitlab.com/linagora/petals-cockpit.git
git checkout front/bug-ng-cli-or-webpack
cd petals-cockpit/frontend
# npm install if you don't have yarn
yarn
ng serve
```

Go to [http://localhost:4200](http://localhost:4200).

### The log given by the failure.

**First of all, it's a simple bug to understand : Just an import resulting in an undefined at runtime.**  
I'll try to give as many info as I can to let you know where is it in the code, that's why it's quite long.
<hr>
It's a runtime error :  

![image](https://cloud.githubusercontent.com/assets/4950209/24462264/d81da7ee-14a3-11e7-9018-5353377148dc.png)

If you take a look to this file which is here : `petals-cockpit/frontend/src/app/features/cockpit/workspaces/state/service-units/service-units.reducer.ts`, [line 229/230](https://gitlab.com/linagora/petals-cockpit/blob/front/bug-ng-cli-or-webpack/frontend/src/app/features/cockpit/workspaces/state/service-units/service-units.reducer.ts#L229), I'm creating an object with an action name as a key, and a class method to execute when this actions is dispatched (using ngrx but this have nothing to do with the problem).

```
{
  [Components.DEPLOY_SERVICE_UNIT_SUCCESS]: ServiceUnits.deployServiceUnitSuccess
}
```

- `Components.DEPLOY_SERVICE_UNIT_SUCCESS` is a simple string
- `ServiceUnits.deployServiceUnitSuccess` is a (static) method

Using `Visual Studio Code`, when I `ctrl + click` on the `Components.DEPLOY_SERVICE_UNIT_SUCCESS` (deploy part), VSC shows me the static class variable. So the import is working well. It's defined like that : 
```
export class Components {
  private static reducerName = 'COMPONENTS_REDUCER';

  // ... some other code

  // tslint:disable-next-line:member-ordering
  public static DEPLOY_SERVICE_UNIT_SUCCESS = `${Components.reducerName}_DEPLOY_SERVICE_UNIT_SUCCESS`;
}
```

I've done that a lot across my app, so I don't understand why it's breaking now.

I'm not sure it's fully related to angular/cli and might be related to webpack.

Of course if I change : 
```
{
  [Components.DEPLOY_SERVICE_UNIT_SUCCESS]: ServiceUnits.deployServiceUnitSuccess
}
```

To the value of `Components.DEPLOY_SERVICE_UNIT_SUCCESS` :
```
{
  ['COMPONENTS_REDUCER_DEPLOY_SERVICE_UNIT_SUCCESS']: ServiceUnits.deployServiceUnitSuccess
}
```

everything is working fine. 

### Mention any other details that might be useful.

Project link : https://gitlab.com/linagora/petals-cockpit/tree/front/bug-ng-cli-or-webpack

I've seen (recent) issues with webpack but these are build errors :
https://github.com/angular/angular-cli/issues/5639
https://github.com/angular/angular-cli/issues/4207
https://github.com/angular/angular-cli/issues/5580

This one is not a build issue but was closed right away by it's author without explanation
https://github.com/angular/angular-cli/issues/5573

**Comment by filipesilva** [comment]
I understand that this is a frustrating bug that you're experiencing, but as presented I'm not too sure it's a CLI bug proper now of what may be causing it. It's very hard to try and figure that out in the fullblown project that you've provided.

Can you make a smaller repro that shows how this is a CLI bug? Something simple like a brand new CLI project with the minimum of changes possible.

**Comment by maxime1992** [comment]
Lot of things to do lately but I'll try to make a repro ASAP.

I understand that it's a really big project and nobody wants to debug that kind of things here so I'll do my best :+1:

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
