### ISSUE TITLE
 ERROR in ./~/@angular/material/tooltip/tooltip.css

### ISSUE THREAD

**Issue by jorawarsingh** [angular/angular-cli#5738]
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.3.0 ngtools/webpack

### Repro steps.
https://bitbucket.org/jorawarsingh/modal-driven-form

### The log given by the failure.
unexpected token in @angular/material
 ERROR in ./~/@angular/material/tooltip/tooltip.css
    Module parse failed: D:\lab\modal-driven-form\node_modules\@angular\material\tooltip\tooltip.css Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.

### Desired functionality.
not sure if it should go in node_modules to bundle the material.

**Comment by RicardoVaranda** [comment]
Hi @jorawarsingh ,

I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of project https://github.com/angular/angular or file issue on their issue tracker.

**Comment by hansl** [comment]
@jorawarsingh Hey. It seems like you're excluding the `node_modules` from using the `css-loader`, which is needed for loading the CSS files when using AOT. Removing that fixes that particular problem (there are others).

Cheers!

**Comment by jorawarsingh** [comment]
@hansl Hi, it didn't work for me even afte including the node_modules,
this
```
{
  test: /\.ts?$/,
  use: '@ngtools/webpack',
  exclude: [/node_modules\/(?!(ng2-.+|ngx-.+))/]
},
{
  test: /\.css$/,
 //exclude:'node_modules',
 include: path.resolve(process.cwd(), 'src', 'app'),
 use: ['to-string-loader', 'css-loader']
 }
```

I have been struggling with this plugin from past three days without any good result, if one thing works then another is broken.

**Comment by hansl** [comment]
Why are you excluding `node_modules` from `css-loader`?  Using an `include` is not better in this case.

**Comment by jorawarsingh** [comment]
@hansl the line exclude is commented so it should automatically include. I am not including it by using include. I have raised this question in material as well so they can test. Thanks
