### ISSUE TITLE
Error in Multi . Module not found pointing to root folder without any module

### ISSUE THREAD

**Issue by Jflima92** [angular/angular-cli#5739]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10

### Repro steps.

I've  migrated my project to a cli one by copying and changing the needed files.
Running ng build at the root folder gives the following error.

### The log given by the failure.

ERROR in multi .
Module not found: Error: Can't resolve 'D:\Source\CliTest' in 'D:\Source\CliTest'
 @ multi .

### Desired functionality.

I really don't know what is wrong, just want it to build :)

### Mention any other details that might be useful.

This is my cli file:

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "cli-test"
  },
  "apps": [
    {
      "root": "",
      "outDir": "dist",
      "assets": [
        "Assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "App/Main.ts",
      "polyfills": "",
      "test": "",
      "tsconfig": "tsconfig.json",
      "testTsconfig": "",
      "prefix": "",
      "styles": [
        ""
      ],
      "scripts": ["Assets/Vendors/AmCharts/amcharts",
            "Assets/Vendors/AmCharts/plugins/responsive",
            "Assets/Vendors/AmCharts/plugins/export"],
      "environmentSource": "App/Environment/environment.ts",
      "environments": {
        "dev": "App/Environment/environment.ts",
        "prod": "App/Environment/environment.prod.ts"
      }
    }
  ],
  "lint": [
    {
      "project": "tsconfig.json"
    }
  ],
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
```

And this is my folder structure inside CliTest:
![image](https://cloud.githubusercontent.com/assets/5619521/24468662/e43ead68-14b0-11e7-8dd6-ddbb79811940.png)

I don't have a structure as the seed projects since my source folders are not in the src folder but in the root one, but I don't think that's it causing the issue.

It's trying to find a module where there isn't one, and it's not supposed to be there aswell as I could see from the seed project.

Any help would be appreciated.
Thanks in advance.

**Comment by RicardoVaranda** [comment]
Hi @Jflima92 ,

Any chance you can create a repo with the same issue so I can evaluate it, by the sound of things while you were restructuring your application you might have missed refactoring one the paths. Anyway having a repo project would really help us helping you 😄

**Comment by Jflima92** [comment]
Hi @RicardoVaranda, this is not the full project, but it replicates the issue: [Replication#5739](https://github.com/Jflima92/angular-cli-issue-5739)

Thanks in advance!

**Comment by Jflima92** [comment]
Hi @RicardoVaranda ,
I overcame this issue by placing all the source folders within a src folder following the seed structure, and adjusting the cli.json.
however I would like to know if it is possible to use the cli without the src folder.
I think you can close this issue.
Thanks

**Comment by filipesilva** [comment]
Heya @Jflima92, the CLI does need a source folder configured.... but off the top of my head I can't quite see why it being root should be a problem. I'll have a look.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
