### ISSUE TITLE
Updating some libs

### ISSUE THREAD

**Issue by mfcar** [angular/angular-cli#5746]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality.
Update some libs:

- autoprefixer 6.5.3 -> [6.7.7](https://github.com/postcss/autoprefixer/releases)
- debug 2.1.3 -> [2.6.3](https://github.com/visionmedia/debug/releases)
- diff 3.1.0 -> [3.2.0](https://github.com/kpdecker/jsdiff/releases)
- html-webpack-plugin 2.19.0 -> [2.28.0](https://github.com/jantimon/html-webpack-plugin/releases)
- rsvp 3.0.17 -> [3.5.0](https://github.com/tildeio/rsvp.js/releases)
- rxjs 5.0.1 -> [5.2.0](https://github.com/ReactiveX/rxjs/releases)
- webpack 2.2.0 -> [2.3.2](https://github.com/webpack/webpack/releases)
- webpack-dev-server 2.3.0 -> [2.4.2](https://github.com/webpack/webpack-dev-server/releases)
- webpack-merge 2.4.0 -> [4.1.0](https://github.com/survivejs/webpack-merge/releases)
- ts-node 2.0.0 -> [3.0.2](https://github.com/TypeStrong/ts-node/releases)
- tslint 4.0.2 -> [5.0.0](https://github.com/palantir/tslint/releases)

I believe that with the update of these libraries, the Angular CLI, could make use of the bugfix that these latest versions corrected and the new functionalities implemented, making the applications more stable.

**Comment by filipesilva** [comment]
Would you be available to make a Pr that adds these updates? These files would need the update:
- https://github.com/angular/angular-cli/blob/master/package.json
- https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/package.json

**Comment by nickroberts** [comment]
FYI, tslint will need some additional configuration updates, as well. I mention this, as I tried to upgrade another project to 5.x (from 4.x), and 💥

**Comment by clydin** [comment]
These appear to be updated (or removed from the project).
