### ISSUE TITLE
ng e2e --server=false --base-href xxx not working

### ISSUE THREAD

**Issue by xnnkmd** [angular/angular-cli#5749]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```
### Description
I would like to use "ng e2e" to run tests against various deployments of my angular project by specifying the base url in the command line script. Using protractor I can do this in a script with "protractor --baseUrl=xxx". I can not do this using "ng e2e". It only allows me to turn off the server but not to specify the base url (-base-href is apparently ignored when server is off).

### Versions.
@angular/cli: 1.0.0
node: 7.7.1
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.6

### Repro steps.
Add npm scripts to existing deployments of a project like f.x.:
```
"e2e:test": "ng e2e --server=false --base-href=https://xxxx",
"e2e:dev": "ng e2e --server=false --base-href=https://xxxx2",
```
and do a "npm run e2e:test"

The test will open the browser but fail to set baseUrl correctly. 

### Mention any other details that might be useful.
Works if I use "protractor" command line:
```
protractor --baseUrl=https://xxxx
```

**Comment by leachryanb** [comment]
+1
