### ISSUE TITLE
How to hook 3rd party scripts before serving / building an app with angular-cli?

### ISSUE THREAD

**Issue by luisfpg** [angular/angular-cli#5759]
Question: 
I have a script that generates typescript classes from a source descriptor. Those classes are used by the angular project.
However, I have to manually run the script when the descriptor changes.
Is it possible to hook some event in angular cli, so the script can be called before an `ng build` or `ng serve`, for example?
Ideally the descriptor should be watched during the `ng serve`, and the callback invoked whenever it changes, such as what happens with SASS -> CSS.

### Versions.
```
@angular/cli: 1.0.0
node: 7.7.3
os: linux x64
```

**Comment by coryrylan** [comment]
I have a project thatdoes something similar. You can use npm scripts in your package.json

`"start": "pretasks && ng serve"`

Then run `npm run start`


This will run the prebuild task before running the project. As for runtime build hooks I am unsure.

**Comment by luisfpg** [comment]
Thanks @coryrylan, this is a nice workaround.
I've been researching on this and found the issue https://github.com/angular/angular-cli/issues/1656 which, if done, could allow writing a webpack plugin for watching resources on runtime and emitting additional files.
But, as it seems, direct access to the webpack configuration won't be allowed (unless the project is `ng eject`ed, which is not ideal either, because we loose some benefits of angular-cli).
Maybe in the future it will be possible to write angular-cli plugins, let's see.
