### ISSUE TITLE
Component creation with metadata factory

### ISSUE THREAD

**Issue by Jflima92** [angular/angular-cli#5760]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10

Using es2015 as module.

### Repro steps.

Creation of a component using a static metadata factory such as:
```
@Component(MetadataFactory.Create(module.id))
```

which returns:

```
public static Create(moduleId: string): Component
    {
        return {
            moduleId: moduleId,
            selector: "dummy-selector,
            templateUrl: "DummyView.html"
        };
}
```

Found out that as cli uses webpack there shouldn't be the moduleId, so I removed it and update the return to:

```
public static Create(moduleId: string): Component
    {
        return {
            selector: "dummy-selector,
            templateUrl: "./DummyView.html"
        };
}
```
But the same error occurs :\

### The log given by the failure.

![image](https://cloud.githubusercontent.com/assets/5619521/24508656/081debb2-155c-11e7-8063-b76dead2a293.png)

The error appears to be in the line of the templateUrl.

### Desired functionality.

Just a normal behaviour when creating a component.

### Mention any other details that might be useful.

This worked fine when using System.js, but got broken after switching to the cli.

Thanks in advance.

**EDIT:**
After a few more debug I found out that it is looking for the template in the folder of the factory.. Is there any way to overcome this?

[SO Thread](http://stackoverflow.com/questions/43136652/angular-cli-webpack-cannot-find-module-when-component-metadata-is-given-by-a-fac/)

**Comment by filipesilva** [comment]
I don't think we support creating the metadata via a function like this. @hansl and you weight in?

**Comment by Jflima92** [comment]
We overcame it by using both the function and directly defining the view and styles since the problem was in the paths, like:
```
@Component(Object.assign(MetadataFactory.Create(DummyViewInjector, module.id),
    {
        templateUrl: "./DummyView.html.html",
        styleUrls: ["./DummyViewStyles.less"]
    }))
```
But it would be a nice to have feature.

Thanks for the answer @filipesilva

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this. However at this moment this is outside of the scope of the Angular CLI project.
