### ISSUE TITLE
Upgrading CLI rc1 to 1 (Angular 2.4 to 4.0) getting below error for .spec.ts

### ISSUE THREAD

**Issue by SirajGadhia** [angular/angular-cli#5771]
windows 10 (64bit) and Visual studio Code

C:/ ... src/app/about/about.component.spec.ts (7,3): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'beforeEach'.
C:/ ... src/app/about/about.component.spec.ts (7,15): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'beforeEachProviders'.
C:/ ... src/app/about/about.component.spec.ts (8,3): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'describe'.
C:/ ... src/app/about/about.component.spec.ts (8,13): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'xdescribe'.
C:/ ... src/app/about/about.component.spec.ts (9,3): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'expect'.
C:/ ... src/app/about/about.component.spec.ts (9,11): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'it'.
C:/ ... src/app/about/about.component.spec.ts (9,15): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'xit'.

**Comment by ctrl-brk** [comment]
What version of @types/jasmine do you have? 2.5.46 does this.

**Comment by enderjs** [comment]
Running into the same problem. I have 2.5.38 and have tried it with 2.5.47 and got the same type of errors. 

Except mine are:
Namespace 'jasmine' has no exported member 'CustomMatcher'

**Comment by filipesilva** [comment]
When updating to 1.0 final, these are the versions that should be used: https://github.com/angular/angular-cli/wiki/stories-1.0-update#packagejson
