### ISSUE TITLE
How to uglify when use 'ng build'

### ISSUE THREAD

**Issue by eminoda** [angular/angular-cli#5772]
### How to uglify when use 'ng build'

I use ng build,the vendor.bundle.js size is 6M!

which options I can use?

**Comment by ishitatsuyuki** [comment]
https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#question

`ng build --prod`

Disclaimer: Angular is a big library, with latest version (tree shaking enabled) it's reduced to 200KB gzipped.

**Comment by eminoda** [comment]
@ishitatsuyuki  got it
