### ISSUE TITLE
Upgrading to angular-cli 1.0.0 problems with root: 404 file not found

### ISSUE THREAD

**Issue by pgsfredda** [angular/angular-cli#5776]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

OSX Yosemite 10.10.5
@angular/cli: 1.0.0
node: 6.9.5
os: darwin x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/compiler-cli: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/platform-server: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0

### Repro steps.

After the start, the app try to load e json file in the root dir but ng-server responds with 404 - file not found

### The log given by the failure.

Angular is running in the development mode. Call enableProdMode() to enable the production mode.
zone.js:1990 GET http://localhost:4200/app/app.menu.json 404 (Not Found)
scheduleTask @ zone.js:1990
ZoneDelegate.scheduleTask @ zone.js:384
onScheduleTask @ zone.js:274
ZoneDelegate.scheduleTask @ zone.js:378
Zone.scheduleTask @ zone.js:209
Zone.scheduleMacroTask @ zone.js:232
(anonymous) @ zone.js:2014
send @ VM10395:3
(anonymous) @ http.es5.js:1254
Observable._trySubscribe @ Observable.js:57
Observable.subscribe @ Observable.js:45
CatchOperator.call @ catch.js:79
Observable.subscribe @ Observable.js:42
pgMenuLoaderService.loadMenus @ pg-menu-loader.service.ts:68
(anonymous) @ app.component.ts:41
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
MapSubscriber._next @ map.js:83
Subscriber.next @ Subscriber.js:89
onLoad @ http.es5.js:1205
ZoneDelegate.invokeTask @ zone.js:398
onInvokeTask @ core.es5.js:4116
ZoneDelegate.invokeTask @ zone.js:397
Zone.runTask @ zone.js:165
ZoneTask.invoke @ zone.js:460
pg-http-file.service.ts:15 404 - Not Found
pgHttpFileService._handleError @ pg-http-file.service.ts:15
CatchSubscriber.error @ catch.js:104
onLoad @ http.es5.js:1210
ZoneDelegate.invokeTask @ zone.js:398
onInvokeTask @ core.es5.js:4116
ZoneDelegate.invokeTask @ zone.js:397
Zone.runTask @ zone.js:165
ZoneTask.invoke @ zone.js:460
pg-menu-loader.service.ts:74 pg-menu-loader.loadMenus error:  404 - Not Found
(anonymous) @ pg-menu-loader.service.ts:74
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.error @ Subscriber.js:195
Subscriber._error @ Subscriber.js:128
Subscriber.error @ Subscriber.js:102
OuterSubscriber.notifyError @ OuterSubscriber.js:22
InnerSubscriber._error @ InnerSubscriber.js:26
Subscriber.error @ Subscriber.js:102
ErrorObservable._subscribe @ ErrorObservable.js:76
Observable._trySubscribe @ Observable.js:57
Observable.subscribe @ Observable.js:45
subscribeToResult @ subscribeToResult.js:22
CatchSubscriber.error @ catch.js:111
onLoad @ http.es5.js:1210
ZoneDelegate.invokeTask @ zone.js:398
onInvokeTask @ core.es5.js:4116
ZoneDelegate.invokeTask @ zone.js:397
Zone.runTask @ zone.js:165
ZoneTask.invoke @ zone.js:460

### Desired functionality.

With the previous version of angular-cli there was no problem

### Mention any other details that might be useful.

I migrated also the angular version from 2.3 to 4
Of course, the mentioned file is the right position (app.menu.json)
I can resolve it if ai use a long url like /src/app/app.menu.json but this is not good, imho, because in the prod version i have to modify all url.

### angular-cli.json
{
  "project": {
    "version": "1.0.0-alpha.1",
    "name": "pg-objects"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "files": "src/**/*.ts",
      "project": "src/tsconfig.json"
    },
    {
      "files": "e2e/**/*.ts",
      "project": "e2e/tsconfig.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}

**Comment by Meligy** [comment]
Although the server runs in-memory server, you can imagine as if it's serving from a `dist` folder under the root.

For stuff to be served, they need to be included in the production build. This is done via the `assets` property in the `.angular-cli.json` file.

Check out the documentation for this feature here to learn how to use it:
https://github.com/angular/angular-cli/wiki/stories-asset-configuration

**Comment by pgsfredda** [comment]
Thank you @Meligy .
I moved the file into the assets dir and configurated them in .angular-cli.json.
Now all works fine.

**Comment by Kevin-Deason** [comment]
The below link should be added to the upgrade guide as it worked without needing to add the assets to the config before the upgrade to latest version

https://github.com/angular/angular-cli/wiki/stories-asset-configuration

**Comment by WebDev2013** [comment]
I had the same problem with a json config file. The above resolves it when running **ng serve** in VS Code, but there are some questions not clear from the wiki page referenced above.
As @pgsfredda says above, 
> in the prod version i have to modify all url.  

After moving the file to './assets/file-to-load.json', I have to add ''./assets' to the url to for it to work in dev.
So now must either maintain an assets folder in production, or fiddle with the url by querying the environment const. It can be worked around, but this change seems to make coding a config file less straight-forward and also testing harder (cannot unit test for the production scenario).

**Comment by Meligy** [comment]
Read the wiki page again. You can have objects not just strings in the `assets` array in `.angular-cli.json`.

The default value is a folder also called `assets`. But you can have something else, like:

```json
...
"assets": [
  "assets",
  { "glob": "**/*", "input": "./my-json-files/", "output": "./api/" },
  { "glob": "favicon.ico", "input": "./", "output": "./" }
],
...
```
