### ISSUE TITLE
ng build --prod 

### ISSUE THREAD

**Issue by doczoidberg** [angular/angular-cli#5779]
### Versions.
@angular/cli: 1.0.0-rc.2
node: 6.9.5
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 4.0.1
@angular/language-service: 4.0.1

### Repro steps.
Component inject firebase in constructor:

`@Inject(FirebaseApp) firebase: firebase.app.App`

### The log given by the failure.
```
ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 80:176 in the original .ts file), resolving symbol Editor in /app/components/editor/editor.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in ...
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

this error occurs only with `ng build --prod`

**Comment by malecki-se** [comment]
Try with stable release of angular-cli 1.0. You have @angular/cli: 1.0.0-rc.2

**Comment by filipesilva** [comment]
Heya, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

The CLI always runs statical analysis on code to ensure it will run when compiled with AOT. This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

A good resource on how to to debug these errors is https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts.
