### ISSUE TITLE
Cannot style component root with SASS

### ISSUE THREAD

**Issue by forwardadvance** [angular/angular-cli#5780]
### Bug Report or Feature Request (mark with an `x`)

- [ x] bug report
- [   ] feature request

### Versions.

```
@angular/cli: 1.0.0
node: 6.10.1
os: darwin x64
```

### Repro steps.

1. Create an app passing the `--style scss` option: `ng new cat-app --style scss`
2. Create a component with `ng g component cat`
3.  A component will be made with an app-cat-component selector
4. Try to write style rules for app-cat-component, for example, to make the background of the component green.

The generated app.component.scss automatically wraps the content in an app-cat-component selector, so I can only write style rules for the component contents, not the component itself. If I want a background colour on the component, I need to add a non-semantic nested div with a class inside the component.

### Desired functionality.

Would love to be able to style component roots, not just component contents. I'd love to be able to write SASS like this:

```
background: red;
p {
  background:green;
}
```

to get the output:

```
app-cat-component { background:red; }
app-cat-component p { background:green; }
```

**Comment by clydin** [comment]
For information regarding component styling, please see this guide: https://angular.io/docs/ts/latest/guide/component-styles.html
Note the special selectors section (i.e., `:host`).

Also, please note that this issue tracker is not suitable for support requests, please use [StackOverflow](http://stackoverflow.com/) for general support related requests.
Thank you.

**Comment by sumitarora** [comment]
Closing as per above comment.

**Comment by forwardadvance** [comment]
Yes, I am a moron, sorry. I had not appreciated these were built into the component decorator.
