### ISSUE TITLE
Load js files dynamically from code

### ISSUE THREAD

**Issue by Ristaaf** [angular/angular-cli#5781]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [*] feature request
```

### Versions.
1.0.0

### Desired functionality.
We need to load different culture files depending on selected culture on our page, currently in our systemjs/gulp based project we have the following construct, this is just one example, we have similar situations with other packages, where we do not know until runtime what to actually load.

System.import("kendo/cultures/kendo.culture." + getLocale() + ".min.js")
   .then(() => System.import("kendo.core.min")
   .then(() => kendo.culture(getLocale());

The feature request here is that I cannot really find any documentation on how to solve this issue, I really hope it can be done already in angular-cli so my hope is that this feature request is for better documentation.

**Comment by filipesilva** [comment]
Heya, according to your answer in https://github.com/angular/angular-cli/issues/6164#issuecomment-299020277 I think your question has been answered. If you're still having trouble let me know.
