### ISSUE TITLE
There is no dependencies(@angular/animations) when I use ng new ****

### ISSUE THREAD

**Issue by trueVitality** [angular/angular-cli#5782]
There is no dependencies(@angular/animations) when I use ng new ****

Fix that guys.

thx

**Comment by sumitarora** [comment]
@trueVitality You can always add it to `package.json` if you need it.

**Comment by dave11mj** [comment]
This might be related to a feature request I had a in mind https://github.com/angular/angular-cli/pull/5786

**Comment by filipesilva** [comment]
Marking as as dupe of https://github.com/angular/angular-cli/issues/5785, there's more information there.
