### ISSUE TITLE
Feature request: Add and configure @ngrx/store & ngrx/effects

### ISSUE THREAD

**Issue by Waterstraal** [angular/angular-cli#5784]
### Bug Report or Feature Request (mark with an `x`)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Versions.

@angular/cli: 1.0.0
node: 6.9.4
os: win32 x64

### Repro steps.

Not relevant.

### The log given by the failure.

Not relevant.

### Desired functionality.

Most Angular starters come equipped with a state manager library such as [ngrx](https://github.com/ngrx) or [angular-redux](https://github.com/angular-redux) because they are in agreement that it greatly benefits the architecture of an Angular app. Since angular-cli would be the natural starting point of new developers it would be great to help them set up an Angular app that 's maintainable. 

It could be implemented as an opt-in option, e.g. `ng new [name] --ngrx`.

**Comment by filipesilva** [comment]
This isn't something we're looking at doing. I understand it's useful and a lot of starters do it, but it's not essential by any stretch of imagination. It's also rather trivial to add after-the-fact.
