### ISSUE TITLE
Add animation support to ng new command

### ISSUE THREAD

**Issue by dave11mj** [angular/angular-cli#5785]
### Bug Report or Feature Request (mark with an `x`)

- [ ] bug report -> please search issues before submitting
- [x] feature request

### Versions.

Not relevant

### Repro steps.

1. `ng new test-animation`
2. Open the `app.component.ts`
3. Add `import { trigger, state, style, animate, transition } from '@angular/animations';`
4. `ng serve`

### The log given by the failure.

`ERROR in /PATH/test-animation/src/app/app.component.ts (2,60): Cannot find module '@angular/animations'.`

### Desired functionality.

I would like to be able to create new applications that support `@angular/animations` without additional configurations.

An option I would propose is a `--animation` flag to the `ng new` command which would allow users to opt-in on user `@angular/animations`.

### Mention any other details that might be useful.

Animations is one of the features I really like about angular. ^^

**Comment by filipesilva** [comment]
Closing in favor of https://github.com/angular/angular-cli/issues/5928 as it's better aligned with what we decided to do.
