### ISSUE TITLE
On build, output a manifest of bundles

### ISSUE THREAD

**Issue by dylanlawrence** [angular/angular-cli#5787]
**- [ x ] feature request**

### Desired functionality.
The webpack build output essentially references a few(5) files in "index.html" and allows one to work within, which is ok.  But, it would be helpful for placing these bundles into other arrangements outside of this static scenario.

### Example  - _dist/manifest.json_

```
{
    "data": {
        "production": true
    },
    "css": [
        "styles.*.bundle.css"
    ],
    "js": [
        "inline.*.bundle.js",
        "polyfills.*.bundle.js",
        "vendor.*.bundle.js",
        "main.*.bundle.js"
    ]
}
```

### Currently 
I can only find awful hacks where you leave the index.html empty and fish out the elements with gulp like [this SO question](http://stackoverflow.com/questions/39622090/how-to-set-up-angular-cli-with-visual-studio-2015-in-mvc-5/40866538#40866538.)  - yuck!

### plugin example
It seems like [this webpack-manifest-plugin](https://github.com/danethurber/webpack-manifest-plugin) is the basic idea but it can probably be added to the cli in a way to offers additional parameters etc.

**Comment by taozhiw** [comment]
+1

**Comment by dylanlawrence** [comment]
Thanks, that works, it's just quite large.
I was able to use `JSONStream.parse(["assetsByChunkName"])` for just the bit I need. 
There could be a less verbose version of this maybe.

**Comment by filipesilva** [comment]
This isn't something we're looking at adding per se, but for now `--stats-json` serves that need.

**Comment by kirillgroshkov** [comment]
Didnt't work for me! Enabled `--stats-json`, it produces `stats.json` file, but not expected `manifest.json`

**Comment by kirillgroshkov** [comment]
Aaaa, now I get it. You extract the data from `stats.json`. Ok, I can to the same.
