### ISSUE TITLE
Angular-cli is --mobile still an option?

### ISSUE THREAD

**Issue by MatteoNY** [angular/angular-cli#5791]
Re: documentation for mobile-toolkit: 
https://github.com/angular/mobile-toolkit/blob/master/guides/cli-setup.md

It references: (Note: this recipe is based on version 1.0.0-beta.4 of Angular CLI.)
Not generating "Web Application Manifest" file. 

I've noticed that some of Angular-cli apps were getting 404 errors from the  Service Worker from non --mobile generated versions. Not sure if there is some flag set in the angular-cli.json file that I've been using after converting prior angular-cli projects. 

I'd like to use the Angular PWA and it would be nice to have updated documentation on how to use it. 

Thanks,
Matt

**Comment by beeman** [comment]
@MatteoNY the `--mobile` option is removed some time ago: https://github.com/angular/angular-cli/pull/4143

**Comment by MatteoNY** [comment]
@beeman Thanks for your quick response. I'll be watching ng-conf for updates on PWA's. If anything the Angular-cli tool should put out a message, for example,  opps! you picked a command that is in the process of being updated or no longer supported. The Angular-cli put out a message when the router option was removed. Before Angular-cli's release 1.0 the --mobile option did prepare the manifest and service-worker code,  it was buggy but there. The Angular-cli change log did not mention anything about pulling the plug on the PWA --mobile option. I understand options that are experimental but to the loyal followers of Angular-cli it would be great to communications thru the change log. It looked like the --mobile options was lagging or out of date. I was noticing  404 errors in the console from service-worker without the --mobile option. It makes good sense to pull the --mobile option of it's not ready for production. 

By the way the Angular-cli team is doing a great job, I've been using the Angular-ci since it was introduced, it's great when it works.  Based on YouTube videos it appears that Yarn is faster and consistent with it's yarn.lock file then NPM. It would be nice to know if Yarn will work with the Angular-cli. It did for a while and then for some reason broke. It would be great if the read me file had official instructions on the usage of npm and yarn. Many thanks!

**Comment by spongessuck** [comment]
@MatteoNY You can tell the CLI to use Yarn:

https://github.com/angular/angular-cli/issues/3886#issuecomment-287542841

**Comment by filipesilva** [comment]
Closing as answered, thanks @beeman and @spongessuck !
