### ISSUE TITLE
/usr/local/lib/node_modules/@angular/cli/models/config/config.js:16

### ISSUE THREAD

**Issue by ralmarri12** [angular/angular-cli#5793]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.
Output from: `error`.
`node --version: v4.4.7` and `npm --version: 4.3.0`.
 macOS (Sierra 10.12.4)

i did install angular-cli using this command
`npm install -g @angular/cli`

and whenever I use `ng` command this is the output:

/usr/local/lib/node_modules/@angular/cli/models/config/config.js:16
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/config.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by ralmarri12** [comment]
I solved the problem by updating Node

**Comment by NGorco** [comment]
Currently got that problem. Updated to node 6. Thx

**Comment by sebavega** [comment]
thanks

**Comment by deepakpookkote** [comment]
how to update the node ..???  i have tried all the ways to update or upgrade still my node version is 
v4.2.6?? wt should i do?

**Comment by ralmarri12** [comment]
@deepakpookkote deepakpookkote have you tried this:
https://www.solarianprogrammer.com/2016/04/29/how-to-upgrade-nodejs-mac-os-x/

**Comment by janaka120** [comment]
I think this will help

```
npm cache clean -f
npm install -g n
n stable
```

**Comment by chef-danny-d** [comment]
You can update it using nvm as well using:

```
$ sudo apt-get update
$ sudo apt-get install build-essential libssl-dev
$ curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | sh
$ source ~/.profile
$ nvm ls-remote
$ nvm install 8.9.4
```
