### ISSUE TITLE
sass comile error in new project with style=sass

### ISSUE THREAD

**Issue by abdul-qadirdeveloper** [angular/angular-cli#5796]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 7.7.3
os: win32 x64
  Windows (10)
### Repro steps.
>ng new sassy-project --style=sass
>npm install
>ng serve
edit src\styles.sass and add style 
h1{
    color:red;
}
command console and browser both will show sass comiler error

### The log given by the failure.
ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./~/sass-loader!./src/styles.sass
Module build failed:
h1{
    color:red;
}

  ^
      Invalid CSS after "h1{": expected "}", was "{"
      in E:\Angular2\sassTest\sassy-project\src\styles.sass (line 1, column 4)
 @ ./src/styles.sass 4:14-195
 @ multi ./src/styles.sass

### Desired functionality.
it should simply apply the style

**Comment by clydin** [comment]
Based on the stylesheet content,  you want "scss" not "sass".  They are two different formats.

**Comment by MRokas** [comment]
Sass uses python-like syntax - no brackets, just spaces indention. 

```
nav
  ul
    margin: 0
    padding: 0
    list-style: none

  li
    display: inline-block

  a
    display: block
    padding: 6px 12px
    text-decoration: none
```

**Comment by abdul-qadirdeveloper** [comment]
@clydin. Yes. I want new scss syntex instead of old sass.

**Comment by MRokas** [comment]
rename files to *.scss
