### ISSUE TITLE
generate duplicates sub-directories when given an argument with slashes

### ISSUE THREAD

**Issue by arlowhite** [angular/angular-cli#58]
Using Ubuntu Linux. nodejs 4.2.1, angular-cli 0.0.10

I want to nest a component in another directory for organization.
(This issue affects all generate commands)

**ng generate component my-category/my-component**
> version: 1.13.8
installing component
  create src/app/components/my-category/my-component/my-category/my-component.css
  create src/app/components/my-category/my-component/my-category/my-component.html
  create src/app/components/my-category/my-component/my-category/my-component.ts
installing component-test
  create src/app/components/my-category/my-component/my-category/my-component.spec.ts

For some reason, this puts an extra *my-category* directory in the path; this shouldn't happen.

With more subdirectories, it's clear that the argument is doubled when generating the path.

**ng generate pipe 1/2/3/4**
> version: 1.13.8
installing pipe
  create src/app/pipes/1/2/3/4/1/2/3/4.spec.ts
  create src/app/pipes/1/2/3/4/1/2/3/4.ts

**Comment by hansl** [comment]
This isn't happening anymore. Closing this as deprecated.
