### ISSUE TITLE
ng g directive|component --valueaccessor 

### ISSUE THREAD

**Issue by vovikdrg** [angular/angular-cli#5801]
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Desired functionality.
I am using forms allot and usually i need to write components inherited from ControlValueAccessor. And each time it require some copy paste to configure component 

Would be handy to be able to generate class configured automatically. Here is example of of default class

https://github.com/angular/angular/blob/5efc86069ff92d980bb460c15deccb1e0fff9363/packages/forms/src/directives/default_value_accessor.ts

Possible class to be generated

```
@Directive|Component({
  selector: 'GENERATED-SELECTOR',
  providers: [{
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => DefaultValueAccessor),
  multi: true
}]
})
export class DefaultValueAccessor implements ControlValueAccessor {
  onChange = (_: any) => {};
  onTouched = () => {};

  constructor(){  }

  writeValue(value: any): void {
    throw new Error('Method not implemented.');
  }

  registerOnChange(fn: (_: any) => void): void { this.onChange = fn; }
  registerOnTouched(fn: () => void): void { this.onTouched = fn; }

  
}
```

One more parameter could be handy is --validator

https://angular.io/docs/ts/latest/api/forms/index/Validator-interface.html

**Comment by filipesilva** [comment]
We're not looking at adding such granular flags, but do have a custom blueprint functionality planned for the future.
