### ISSUE TITLE
Ability to specify different styling per environment

### ISSUE THREAD

**Issue by jstoppa** [angular/angular-cli#5803]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.9.1
os: win32 x64

### Desired functionality.

Ability to specify different styling per environment

### Mention any other details that might be useful.

I’d like to have the ability to pass the styling when executing ng serve or ng build in the same way the environment parameter works (or… is it a way to do this already with angular cli?)
We need this because we are building a product that will have different styling per client

Example:
At the moment, the angular-cli.json takes styling like in the example below (adding the environment configuration to put more context to the desired functionality):
```javascript
"styles": [
 	"styles.scss"
 ],
"environment": "environments/environment.ts",
"environmentSource": "environments/environment.ts",
"environments": {
	"development ": "environments/development/environment.ts",
	"client1": "environments/client1/environment.ts",
	"client2": "environments/client1/environment.ts"
}
```
I would ideally like to be able to set a different style list per environment, I’m suggesting something like this:
```javascript
"styles": {
 	"development": [
 		"environments/development/styles/styles.scss"		
 	],
 	"client1": [
 		"environments/client1/styles/styles.scss"		
 	],
 	"client2": [
		"environments/client2/styles/styles.scss"
 	]
 }
"environment" : "environments/environment.ts",
"environmentSource": "environments/environment.ts",
"environments": {
	"development ": "environments/development/environment.ts",
	"client1": "environments/client1/environment.ts",
	"client2": "environments/client1/environment.ts"
}
```
Then I would run:
for development:
`
ng serve --environemnt:development --style:development
`
`
ng build --bh /development/ --environemnt:development --style:development
`

for client1:
`
ng serve --environemnt:client1 --style:client1
`
`
ng build --bh /client1/ --environemnt:client1 --style:client1
`

for client2:
`
ng serve --environemnt:client2 --style:client2
`
`
ng build --bh /client2/ --environemnt:client2 --style:client2
`

**Comment by carndacier** [comment]
+1

**Comment by mattngan** [comment]
Would be good to have this feature :)

**Comment by nilsbeuth** [comment]
Sounds super dandy

**Comment by jcoo02** [comment]
+1 Have a requirement for this.

**Comment by dougfrench** [comment]
+1

**Comment by davkraid** [comment]
Would be great for templates too.

**Comment by changLiuUNSW** [comment]
+1 I have requirement for it too

**Comment by werthdavid** [comment]
+1

**Comment by marvinhuebner** [comment]
+1

**Comment by filipesilva** [comment]
I see there's some interest in this sort of feature. I can't promise something like this is going to happen but will keep the issue open for discussion.

I think it's overloading the environment feature somewhat, since it's meant to separate different deployment environments (such as dev/staging/prod) but in here it also means different variations of the same app.

For instance, if you want to use a certain styling and scripts for Client 1, it stands to reason that you should also have dev/staging/prod environments for that client.

**Comment by Blacktiger** [comment]
In my case, I'm looking at using ExtJS for some of my views. ExtJS has it's own build tool, so I'd like to include the appropriate build (testing, dev, prod etc) in the same angular cli build. Maybe there's another way to accomplish the same thing though?

**Comment by marvinhuebner** [comment]
Any updates on this?

**Comment by aharonbarel** [comment]
+1

**Comment by Khanji** [comment]
+1

**Comment by usmanahmed061** [comment]
any updates ?

**Comment by hkreddy** [comment]
+1

**Comment by markpenaranda** [comment]
+1

**Comment by gimlidc** [comment]
+1

**Comment by felipe-mena** [comment]
+1

**Comment by inesvanstappen** [comment]
+1

**Comment by jstoppa** [comment]
It would be nice to have this functionality. we got this working using a very convoluted way by running a bash script before the build runs which changes the style.scss programmatically to point the imports to the right environment. Not ideal but works.

**Comment by filipesilva** [comment]
You can can do this today using the `--configuration` option to override any part of the build options. Please see https://angular.io/guide/workspace-config#alternate-build-configurations for more information.
