### ISSUE TITLE
Build error when using template versioning in components (ng build --prod)

### ISSUE THREAD

**Issue by millersdk** [angular/angular-cli#5805]
### Versions.
@angular/cli: 1.0.0

### Repro steps.
When you use template versioning in components, the command "ng build --prod" will fail. (Other commands like "ng serve" or just "ng build" works fine).

@Component({
   selector: 'app-root',
   templateUrl: './my.component.html?v=1',
   styleUrls: ['./styles.css']
})

ng build --prod fails with error: 

ERROR in ENOENT: no such file or directory...

**Comment by filipesilva** [comment]
I don't think the AOT compiler itself supports that usage. You can try submitting a feature request in https://github.com/angular/angular for it.

**Comment by millersdk** [comment]
Hi Filipe

 

Thank you for your answer – it used to word in the beta releases – and as I wrote – it works fine when you do a “ng serve”

 

Regards, Dennis

**Comment by filipesilva** [comment]
Older beta releases didn't do AOT properly actually... which is why some of that stuff went by undetected. When you do `ng serve --prod` AOT is turned on as well.
