### ISSUE TITLE
Allow configuration of Sass precision

### ISSUE THREAD

**Issue by veeti** [angular/angular-cli#5807]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

The default precision in Sass is [too low](https://github.com/sass/sass/issues/1122) and causes visual issues with many common libraries like Bootstrap. This needs to be adjustable or set to a sane default in angular-cli.

**Comment by intellix** [comment]
I believe the recommended SASS precision for Bootstrap is 10
