### ISSUE TITLE
Eject Script Generates Webpack Config With Wrong GlobCopyWebpackPlugin cwd

### ISSUE THREAD

**Issue by spsoto** [angular/angular-cli#5811]
### Summary

When running `ng eject`, the auto generated file loads the `GlobCopyWebpackPlugin` with the current cwd where the project is being ejected instead of replacing with `process.cwd() + "/src"` or similar.

This makes the `/assets` folder unavailable when running the same project in another computer (`webpack` / `webpack-dev-server`). No stack is shown by the console, so it's hard to find this error.

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0 (e)
node: 7.5.0
os: darwin x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
```

### Repro steps.

```
npm install -g @angular/cli
ng new testng2
cd testng2
ng eject
cat webpack.config.js
```

### The log given by the failure.

There's no log / stack trace. It just don't work and the `webpack.config.js` has the `GlobCopyWebpackPlugin` as follows:

```javascript
  /* ... */
  "plugins": [
    /* ... */
    new GlobCopyWebpackPlugin({
      "patterns": [
        "assets",
        "favicon.ico"
      ],
      "globOptions": {
        "cwd": "/Users/spsoto/Work/Coddde/Proyectos/commvault/testng2/src", // <--- !!
        "dot": true,
        "ignore": "**/.gitkeep"
      }
    })
    /* ... */
  ]
  /* ... */
```

### Desired functionality.

`globOptions.cwd` should be replaced with `process.cwd() + "/src"` or similar instead of `"/Users/spsoto/Work/Coddde/Proyectos/commvault/testng2/src"` (that's my case). `assets`  and `favicon.ico` become unavailable when running the project in a shared ejected project.

Didn't find an easy way in the eject script to replace it.

### Mention any other details that might be useful.

Didn't find a similar issue, because this kind of usage is not very common. Maybe this is a expected behavior previously discussed, idk.

**Comment by filipesilva** [comment]
Sounds like a bug, thanks for bringing it up!

**Comment by clydin** [comment]
The `GlobCopyWebpackPlugin` webpack plugin is no longer used to copy assets.

**Comment by ruipimentel** [comment]
Just in case anyone is dealing with this problem in @angular/cli@1.6.6, after `ng eject` I had to tweak "webpack.config.js", specifically at the `"plugins"` setting of its `module.exports`:

![screenshot from 2018-01-29 09 13 29](https://user-images.githubusercontent.com/4542150/35507801-29f4ba68-04d5-11e8-8710-a31a046bde13.png)

As you can see, the `"glob"`setting had an unnecessary `"src/"` prefix.

I'm actually no Webpack expert (quite the reverse!), so any feedback on this solution is welcome :)

**Comment by dyh333** [comment]
hi, @filipesilva . after eject and npm run build, it seems not copy the assets folder to dist, is it a ng-cli bug?

**Comment by ruipimentel** [comment]
Hi @dyh333, I had this very same problem too.

Solved it by removing the 2 extra `"src/"` in "webpack.config.js":

![screenshot from 2018-02-08 11 39 25](https://user-images.githubusercontent.com/4542150/35975722-db7142e2-0cc4-11e8-8ddf-c70dcde19b8f.png)
