### ISSUE TITLE
Webpack config

### ISSUE THREAD

**Issue by Dominionys** [angular/angular-cli#5815]
### Versions.
@angular/cli: 1.0.0-rc.1
node: 7.7.2
os: darwin x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/compiler-cli: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/platform-server: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0-rc.1

Is it possible to override/redefine a function that calculates hash value for bundle?

For example, the `hash` value in code `main.bundle.hash.js` should be calculated with manually specified rules.

Any suggestions?

**Comment by filipesilva** [comment]
We don't have such configuration available, no. You can try ejecting (`ng eject`) to manipulate your configuration yourself, but then you're on your own mostly. See https://github.com/angular/angular-cli/wiki/eject for more info.
