### ISSUE TITLE
Angular 2 form is not working in sub routing for Universal CLI

### ISSUE THREAD

**Issue by BattiniSantthosh** [angular/angular-cli#5816]
### Versions.
universal-cli: 1.0.0-alpha.universal.3
angular-cli: 1.0.0-beta.23
node: 7.5.0
os: win32 x64

### server.routes.ts
export const routes: string[] = [
	'home',
	'contact'
];
### app.routes.ts

export const appRoutes: Routes = [
  { path: 'home', component: HomeComponent },
  { path: 'contact', component: ContactComponent },
  { path: '',   redirectTo: '/home', pathMatch: 'full' }
];

### contact.component.html

&lt;form #f=&quot;ngForm&quot; (ngSubmit)=&quot;addContact()&quot;&gt;<br />
			&lt;input name=&quot;newName&quot; [(ngModel)]=&quot;newName&quot;&gt;<br />
			&lt;input name=&quot;newEmail&quot; [(ngModel)]=&quot;newEmail&quot;&gt;<br />
			&lt;button&gt;Submit&lt;/button&gt;<br />
&lt;/form&gt;

### contact.component.ts

export class ContactComponent implements OnInit {
	newName: string; 
	newEmail: string;
  constructor() { }

  ngOnInit() {
  }
  addContact(){
  	console.log(this.newName, this.newEmail)
  }

}

### Issue.
addContact() function is not responding while submit the form in contact page

Please resolve this issue

**Comment by tabvn** [comment]
try modify 

<button>Submit</button>

to <button type="submit">Submit</button>


and in contact.component.ts

change 
newName: string;
newEmail: string;

to 

newName: string = "";
newEmail: string = "";

i hope it helps

**Comment by BattiniSantthosh** [comment]
### I have updated as mentioned after submitting the form, values are displaying in the URL as below

http://localhost:8000/contact?newName=test&newEmail=test%40gmail.com

I don't want to display the values in the URL, 

How could i get values in addContact() function?

**Comment by filipesilva** [comment]
I'm sorry, but this issue is not caused by Angular CLI itself. Please contact the author(s) of project Universal-CLI at https://github.com/devCrossNet/universal-cli or file issue on their issue tracker.
