### ISSUE TITLE
npm install -g @angular/cli ERROR

### ISSUE THREAD

**Issue by danipi79** [angular/angular-cli#5818]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Last version

### Repro steps.

![image](https://cloud.githubusercontent.com/assets/18738791/24647410/177a00f6-1920-11e7-8550-a45e3a7165e0.png)

npm install -g @angular/cli
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</title>
npm ERR!     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
npm ERR!
npm ERR!     <link rel="icon" type="image/png" href="http://10.113.52.95:8081/nexus/c/favicon.png">
npm ERR!     
npm ERR!
npm ERR!     <link rel="stylesheet" href="http://10.113.52.95:8081/nexus/c/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</h1>
npm ERR!     <p>Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\0012416\npm-debug.log

### The log given by the failure.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData @angular/cli
8 silly fetchNamedPackageData @angular/cli
9 silly mapToRegistry name @angular/cli
10 silly mapToRegistry scope (from package name) @angular
11 verbose mapToRegistry no registry URL found in name for scope @angular
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry http://10.113.52.95:8081/nexus/content/groups/npm-group-repo/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@angular/cli',
14 silly mapToRegistry   scope: '@angular',
14 silly mapToRegistry   escapedName: '@angular%2fcli',
14 silly mapToRegistry   name: '@angular/cli',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri http://10.113.52.95:8081/nexus/content/groups/npm-group-repo/@angular%2fcli
16 verbose request uri http://10.113.52.95:8081/nexus/content/groups/npm-group-repo/@angular%2fcli
17 verbose request no auth needed
18 info attempt registry request try #1 at 10:03:42
19 verbose request id 5033ba8961c0aa6e
20 http request GET http://10.113.52.95:8081/nexus/content/groups/npm-group-repo/@angular%2fcli
21 http 404 http://10.113.52.95:8081/nexus/content/groups/npm-group-repo/@angular%2fcli
22 verbose bad json <html>
22 verbose bad json   <head>
22 verbose bad json     <title>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</title>
22 verbose bad json     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
22 verbose bad json
22 verbose bad json     <link rel="icon" type="image/png" href="http://10.113.52.95:8081/nexus/c/favicon.png">
22 verbose bad json     
22 verbose bad json
22 verbose bad json     <link rel="stylesheet" href="http://10.113.52.95:8081/nexus/c/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
22 verbose bad json   </head>
22 verbose bad json   <body>
22 verbose bad json     <h1>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</h1>
22 verbose bad json     <p>Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</p>
22 verbose bad json   </body>
22 verbose bad json </html>
23 error registry error parsing json
24 verbose headers { date: 'Tue, 04 Apr 2017 08:03:42 GMT',
24 verbose headers   server: 'Nexus/2.12.0-01',
24 verbose headers   'x-frame-options': 'SAMEORIGIN',
24 verbose headers   'x-content-type-options': 'nosniff',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   'content-type': 'text/html',
24 verbose headers   'transfer-encoding': 'chunked' }
25 silly get cb [ 404,
25 silly get   { date: 'Tue, 04 Apr 2017 08:03:42 GMT',
25 silly get     server: 'Nexus/2.12.0-01',
25 silly get     'x-frame-options': 'SAMEORIGIN',
25 silly get     'x-content-type-options': 'nosniff',
25 silly get     'accept-ranges': 'bytes',
25 silly get     'content-type': 'text/html',
25 silly get     'transfer-encoding': 'chunked' } ]
26 silly fetchPackageMetaData SyntaxError: Unexpected token < in JSON at position 0
26 silly fetchPackageMetaData <html>
26 silly fetchPackageMetaData   <head>
26 silly fetchPackageMetaData     <title>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</title>
26 silly fetchPackageMetaData     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
26 silly fetchPackageMetaData
26 silly fetchPackageMetaData     <link rel="icon" type="image/png" href="http://10.113.52.95:8081/nexus/c/favicon.png">
26 silly fetchPackageMetaData     
26 silly fetchPackageMetaData
26 silly fetchPackageMetaData     <link rel="stylesheet" href="http://10.113.52.95:8081/nexus/c/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
26 silly fetchPackageMetaData   </head>
26 silly fetchPackageMetaData   <body>
26 silly fetchPackageMetaData     <h1>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</h1>
26 silly fetchPackageMetaData     <p>Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</p>
26 silly fetchPackageMetaData   </body>
26 silly fetchPackageMetaData </html>
26 silly fetchPackageMetaData
26 silly fetchPackageMetaData     at Object.parse (native)
26 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
26 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
26 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
26 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
26 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
26 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
26 silly fetchPackageMetaData     at emitOne (events.js:96:13)
26 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
26 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
26 silly fetchPackageMetaData  error for @angular/cli SyntaxError: Unexpected token < in JSON at position 0
26 silly fetchPackageMetaData <html>
26 silly fetchPackageMetaData   <head>
26 silly fetchPackageMetaData     <title>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</title>
26 silly fetchPackageMetaData     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
26 silly fetchPackageMetaData
26 silly fetchPackageMetaData     <link rel="icon" type="image/png" href="http://10.113.52.95:8081/nexus/c/favicon.png">
26 silly fetchPackageMetaData     
26 silly fetchPackageMetaData
26 silly fetchPackageMetaData     <link rel="stylesheet" href="http://10.113.52.95:8081/nexus/c/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
26 silly fetchPackageMetaData   </head>
26 silly fetchPackageMetaData   <body>
26 silly fetchPackageMetaData     <h1>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</h1>
26 silly fetchPackageMetaData     <p>Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</p>
26 silly fetchPackageMetaData   </body>
26 silly fetchPackageMetaData </html>
26 silly fetchPackageMetaData
26 silly fetchPackageMetaData     at Object.parse (native)
26 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
26 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
26 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
26 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
26 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
26 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
26 silly fetchPackageMetaData     at emitOne (events.js:96:13)
26 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
26 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
27 silly rollbackFailedOptional Starting
28 silly rollbackFailedOptional Finishing
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack SyntaxError: Unexpected token < in JSON at position 0
31 verbose stack <html>
31 verbose stack   <head>
31 verbose stack     <title>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</title>
31 verbose stack     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
31 verbose stack
31 verbose stack     <link rel="icon" type="image/png" href="http://10.113.52.95:8081/nexus/c/favicon.png">
31 verbose stack     
31 verbose stack
31 verbose stack     <link rel="stylesheet" href="http://10.113.52.95:8081/nexus/c/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
31 verbose stack   </head>
31 verbose stack   <body>
31 verbose stack     <h1>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</h1>
31 verbose stack     <p>Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</p>
31 verbose stack   </body>
31 verbose stack </html>
31 verbose stack
31 verbose stack     at Object.parse (native)
31 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
31 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
31 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
31 verbose stack     at emitTwo (events.js:106:13)
31 verbose stack     at Request.emit (events.js:191:7)
31 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
31 verbose stack     at emitOne (events.js:96:13)
31 verbose stack     at Request.emit (events.js:188:7)
31 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
32 verbose cwd C:\Users\0012416
33 error Windows_NT 6.1.7601
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
35 error node v6.9.2
36 error npm  v3.10.9
37 error Unexpected token < in JSON at position 0
37 error <html>
37 error   <head>
37 error     <title>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</title>
37 error     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
37 error
37 error     <link rel="icon" type="image/png" href="http://10.113.52.95:8081/nexus/c/favicon.png">
37 error     
37 error
37 error     <link rel="stylesheet" href="http://10.113.52.95:8081/nexus/c/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
37 error   </head>
37 error   <body>
37 error     <h1>404 - Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</h1>
37 error     <p>Path /@angular/cli not found in group repository &quot;npm-group-repo&quot; [id=npm-group-repo].</p>
37 error   </body>
37 error </html>
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

### Desired functionality.

Install @Angular/cli

**Comment by starquake** [comment]
Do you have a company proxy or something?

Firstly, it's trying to download from a LAN ip address, and not the internet: 
10.113.52.95
Secondly it's trying to download from a non-standard port:
8081

**Comment by filipesilva** [comment]
As @starquake says this seems related to your npm proxy, perhaps it doesn't not support scoped packages.

I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of project Sonatype or file issue on their issue tracker.
