### ISSUE TITLE
Webpack fails on initial compile but on second recompile it works

### ISSUE THREAD

**Issue by kevincam3** [angular/angular-cli#5823]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 7.8.0
os: win32 x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Repro steps.
Here's a link to a video of what I'm doing.
http://www.youtube.com/watch?v=gEm8Ju4ONDY

I start my app and it compiles with an error that seems to be related to a variable I declare.
Webpack initially compiles and gives an error but making any change to any file and re-saving it fixes the error.

### The log given by the failure.
ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'toastr'. Consider exporting the symbol (position 25:13 in the original .ts file), resolving symbol AppModule in C:/wamp/www/angular4/src/app/app.module.ts
webpack: Failed to compile.

### Desired functionality.
It should compile on the first time

**Comment by filipesilva** [comment]
Heya, thanks for filing this issue and making a video showing this problem happening. 

This bug looks a lot like https://github.com/angular/angular-cli/issues/4810 except it's happening for static analysis errors. It looks like https://github.com/angular/angular-cli/pull/5489 missed that bit.

**Comment by filipesilva** [comment]
To be clear though, the error you see is a real error, but the CLI is failing to report it on rebuilds.

**Comment by kevincam3** [comment]
@filipesilva 

Why is it a real error since I'm declaring the variable and it's a global variable being included in the index.html file?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
