### ISSUE TITLE
Pairing Session e2e Tests

### ISSUE THREAD

**Issue by Anzumana** [angular/angular-cli#5824]
Hey, i did not manage to get e2e Test on my mac working yet. In any of my projects.
Over the last 6 month or so i tried multiple different approaches to fix the ongoing issue. But never managed to solve it. ( in chrome , firefox worked for a little bit until they updated :) )
If anyone could help me out i would rly appreciate it.
For Paring we could use tmux or some other sweet tool.
Regards
Anzumana

**Comment by delasteve** [comment]
@Anzumana, while I feel your pain, this issue tracker is not the appropriate place for such a request. You might want to try Gitter or another Angular community forum / chat platform.

**Comment by Anzumana** [comment]
they work now.
i did not change anything but for some unknown reason they work :)
great work on the angular cli btw. love working with it soooo much.
Have an amazing weekend.
take care.
