### ISSUE TITLE
Angular 2 project with cli 1.0

### ISSUE THREAD

**Issue by pavankd** [angular/angular-cli#5835]
unable to find options to create Angular 2 project with Angular cli 1.0

**Comment by AnianZ** [comment]
'Angular 2' in the sense of Angular v2.* ? If you want to create a new project, you should probably use Angular v4. If you need to downgrade to v2 you could do it in the package.json manually but I don't think there is an option in the CLI for it.

**Comment by filipesilva** [comment]
There isn't an option to start a new project preconfigured for Angular version 2.x, but you can just change it in the package.json as @AnianZ said.

This is the list of packages you need to change: https://github.com/angular/angular-cli/blob/master/tests/e2e/utils/project.ts#L83-L97
