### ISSUE TITLE
View Encapsulation not working between multiple Angular 4 Apps (built with aot)

### ISSUE THREAD

**Issue by d-bechtel** [angular/angular-cli#5837]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

node: 6.9.4
npm: 3.10.10

I'm using webpack 2.3.3 with @ngtools/webpack loader (v. 1.2.13)

### Repro steps.

Here is an working example with JIT-compiled Apps, both apps get different css selectors. If i build these apps with AOT, both Apps get the same css selector:
http://plnkr.co/edit/fFTrK07EWBV6vSxhYaFe?p=preview

### Desired functionality.

If i boot multiple (different) Angular 4 Apps (in different zones), the styles of each app will be adopt to all apps, because of the same css selector ( .app[_ngcontent-c0] ) 

![angular_aot_bug](https://cloud.githubusercontent.com/assets/22303562/24702325/90ddc0fc-19fe-11e7-9013-d3f43363496c.PNG)

One possible solution should be a configurable prefix for the css-selector.

**Comment by filipesilva** [comment]
Heya, could you open this on https://github.com/angular/angular instead? It seems to be related with the AOT compiler itself and not the CLI (which merely uses it).
