### ISSUE TITLE
Subresource integrity

### ISSUE THREAD

**Issue by zygimantas** [angular/angular-cli#5839]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 7.2.1
os: win32 x64

### Repro steps.

ng build --prod

### The log given by the failure.

None

### Desired functionality.

I would like to see the ```integrity``` attribute added to the script tags:

```<script src="vendor.95345e6c28ff2e09fc6f.bundle.js" integrity="sha384-6ePHh72Rl3hKio4HiJ841psfsRJveeS+aLoaEf3BWfS+gTF0XdAqku2ka8VddikM"></script>```

instead of:

```<script type="text/javascript" src="vendor.95345e6c28ff2e09fc6f.bundle.js">```

### Mention any other details that might be useful.

https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by filipesilva** [comment]
This might be something we add, yes. Requires some discussion regarding best practices, and possible bad interactions with some usecases, but it's a nice feature.

**Comment by MrTimms** [comment]
@filipesilva 

I noticed there is a PR for this: https://github.com/angular/angular-cli/pull/5841

Is there any more work that needs to be done before it is accepted?

**Comment by KLuuKer** [comment]
I would love to have this feature implemented, we are building a new app and I want to check every security box there is!

So if someone could look at this\the pull request that would be awesome.
