### ISSUE TITLE
ng serve proxy-conf and cors problem

### ISSUE THREAD

**Issue by amineparis** [angular/angular-cli#5845]
I have two days trying to make Angular 2 access api returned cookies ((back port 8000, front port: 4200)). I have configured cors, withcredentials and the probleme still here set-cookie is present and cookies are not written. Is ng serve proxy-conf meant to solve this problem ?

**Comment by diicar** [comment]
https://juristr.com/blog/2016/11/configure-proxy-api-angular-cli/

**Comment by textbook** [comment]
This appears to be the same error as angular/angular#15804, where you also haven't provided enough information to even start investigating it. See e.g. http://sscce.org/, https://stackoverflow.com/help/mcve for help creating an example that others can use to recreate your issue.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
