### ISSUE TITLE
Upgrade to Angular/Cli 1.0.0 ng build --env=qa only uses environmentSource

### ISSUE THREAD

**Issue by SEAN-LANOUE** [angular/angular-cli#5849]
## Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.9.1
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10

npm version = 3.10.8

### Repro steps.
ng build --output-path D:\\Solution\\MyWebSite\\a --base-href /a/ ----target=development --env=qa

### The log given by the failure.
environment variables from my environment.qa.ts are not the correct values.  It appear to ONLY take the environmentSource ( environment.ts ).

baseUrl = http://xyz.com

### Desired functionality.
ng build --output-path D:\\Solution\\MyWebSite\\a --base-href /a/ ----target=development --env=qa

This environment variable should be...
baseUrl = http://www.qa.com

### Mention any other details that might be useful.
Contents of my environment files.
environment.ts
export const environment = {
  production: false,
  baseUrl: 'http://xyz.com'
};

environment.dev.ts
export const environment = {
  production: false,
  baseUrl: 'http://www.dev.com'
};

environment.qa.ts
export const environment = {
  production: false,
  baseUrl: 'http://www.qa.com'
};
environment.prod.ts
export const environment = {
  production: false,
  baseUrl: 'http://www.prod.com'
};

Contents of my angular-cli.json

{
  "project": {
    "version": "1.0.0",
    "name": "gb-ng2"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "gb",
      "mobile": false,
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environmentSource": "environments/environments.ts",
      "environments": {
        "dev": "environments/environment.dev.ts",
        "qa": "environments/environment.qa.ts",
        "prod": "environments/environment.prod.ts",
      }
    }
    
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}

**Comment by sathiyavasagam** [comment]
I have also same issue.  Actually we should not specify any value properties on source file., we specified in corresponding env files . So while n build or ng serve  compilation it throws an error as Property 'something' does not exist on type '{ dev: boolean; local: boolean; qa: boolean; }'

**Comment by soetaertie** [comment]
I am also having this issue. After some testing, it seems that it is not the evironmentSource that is being used. I changed is to another environment file and nothing changed. I think that the problem lies with the environment.ts. The environment declared here is always used.

**Comment by josersleal** [comment]
This is an issue for e2e also. 
1st: for app to be served, I need to explicitly add --serve=true
2nd: for CI purposes we need different environments and the build fails because it cannot run with the correct app variables (@ env file)

this makes it impossible for us to run e2e

**Comment by filipesilva** [comment]
Using the environment files you provided and adding `console.log(environment)` to `main.ts`, I got these results in the browser console:
- `ng build`
![image](https://cloud.githubusercontent.com/assets/4172079/26110996/c8982772-3a4b-11e7-9867-ac7867161e1a.png)

- `ng build --env=dev`
![image](https://cloud.githubusercontent.com/assets/4172079/26110941/a4b6e028-3a4b-11e7-8f51-c62e98d18c6a.png)

- `ng build --env=qa`
![image](https://cloud.githubusercontent.com/assets/4172079/26111047/ef6c23b2-3a4b-11e7-9901-45897aef58c3.png)

- `ng build --env=prod`
![image](https://cloud.githubusercontent.com/assets/4172079/26111076/0243ae9c-3a4c-11e7-8b6a-c849a666efe6.png)

So as far as I can see here, the values within each environment file are in fact being used at runtime.

I cannot reproduce the issue you are describing. If you can provide a simple repository where you see this bug, I can reopen and investigate.
