### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Calling function 'MetaModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

### ISSUE THREAD

**Issue by ds-manish** [angular/angular-cli#5852]
ERROR in Error encountered resolving symbol values statically. Calling function 'MetaModule', function calls are not supported. Consider replacing
the function or lambda with a reference to an exported function, resolving symbol AppModule in /Applications/XAMPP/xamppfiles/htdocs/app.diplomasaf
e.com/src/app/app.module.ts, resolving symbol AppModule in /Applications/XAMPP/xamppfiles/htdocs/app.diplomasafe.com/src/app/app.module.ts

got this error while doing

> ng serve

@angular/cli: 1.0.0-beta.31
node: 6.9.5
npm: 4.4.4
os: darwin x64

**Comment by AnianZ** [comment]
There are many issues concerning this problem with aot-compilation like #5833 on this repo. I'm afraid it's hard to help you with so little context.

**Comment by ds-manish** [comment]
hi there,
thanks for the reply.

what details should i provide so that you can help me in solving the issue?

regards,
Manish Baral

**Comment by ds-manish** [comment]
I have used

> import { MetaModule } from 'ng2-meta';
from here: https://github.com/vinaygopinath/ng2-meta

**Comment by AnianZ** [comment]
It seems this library hasn't been updatet in some time. [There is an open PR to fix your issue](https://github.com/vinaygopinath/ng2-meta/pull/30) but it hasn't been merged yet. You either have to wait until this get's fixed and disable the cli's aot features or you use a different library like this one: https://www.npmjs.com/package/@nglibs/meta

**Comment by filipesilva** [comment]
Unfortunately, that library doesn't yet support AOT or being statically analyzed. You'll have to wait for it to fix that issue.
