### ISSUE TITLE
Multi-level base href not working

### ISSUE THREAD

**Issue by nmlandge** [angular/angular-cli#5853]
### Bug Report
```
- [x] bug report
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 7.8.0
os: linux x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Repro steps.
Use two-level (or multi-level) base href in app
    e.g. "/dir/subdir"
Observe the URLs hit to load resources.
Only first part of the base href is prepended to the URLs
    e.g in this case, URLs start with "/dir" only; "/subdir" is ignored altogether

The behavior is observed in case of hard-coding base href with `<base href="">`
    as well as setting base href using `--base-href` while ng building.

### Desired functionality.
The value of base href should be used as provided (including multi-level paths).
i.e. If built using `ng build --prod --base-href /dir/subdir` , should generate URLs: `http://<domain>/dir/subdir/<resource>`
     And
     If index.html contains `<base href="/dir/subdir" />`, should generate URLs: `http://<domain>/dir/subdir/<resource>`

**Comment by clydin** [comment]
What you are describing is the standard base href behavior.  For your use case the base href should be `/dir/subdir/`.  Note the trailing `/`.

Please note that general support questions should be posted to sites such as [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

**Comment by nmlandge** [comment]
Yes. Got it working with trailing `/`. Was unaware of this behavior and got confused. Closing the issue.
Thanks for the reply though.
