### ISSUE TITLE
Problem after installing angular-split

### ISSUE THREAD

**Issue by AdityaDaksha** [angular/angular-cli#5855]
Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in C:/Users/**/git/**/node_modules/angular-split/node_modules/@angular/core/core.d.ts, resolving symbol AngularSplitModule in C:/Users/**/git/**/node_modules/angular-split/dist/angularSplit.module.d.ts, resolving symbol AngularSplitModule in C:/Users/**/git/**/node_modules/angular-split/dist/angularSplit.module.d.ts

### Versions.
@angular/cli: 1.0.0-rc.1
node: 6.10.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9

###Message while installing angular-split
npm install angular-split --save
cwb-ui@0.0.0 C:\Users\**\git\**I
+-- UNMET PEER DEPENDENCY @angular/core@2.4.9
`-- angular-split@0.2.0

**Comment by clydin** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of project `angular-split` or file an issue on their issue tracker.

Please note that the package in question has dependencies on Angular 4.0.  In addition it is erroneously using dependencies instead of peer dependencies for the aforementioned.

**Comment by AdityaDaksha** [comment]
Thanks! after changing angular-split version to 0.1.20, problem solved.
