### ISSUE TITLE
Generate style into css instead of js

### ISSUE THREAD

**Issue by danielszenasi** [angular/angular-cli#5857]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.9.1
os: win32 ia32
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Desired functionality.
New angular cli generates the compiled scss into JavaScript, that appends those styles into the html head tag between style tags.
Is it possible to rather generate .css files and import them in link tags?

### Mention any other details that might be useful.
In the JS, these styles aren't minified, they contain even the \n linebreaks in the style string.

@filipesilva: do you have any clue?

**Comment by clydin** [comment]
Production builds by default extract global stylesheets into a CSS bundle.  This can also be controlled independently via the `--extract-css` build command option.

**Comment by fuitattila** [comment]
@clydin: that worked perfectly! Thank you!
