### ISSUE TITLE
unable to install angular-cli@1.0.0

### ISSUE THREAD

**Issue by nehaagrawal** [angular/angular-cli#5858]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.9.4
os: win 32 x64

### Repro steps.

npm install angular-cli@1.0.0

### The log given by the failure.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "insta
 "angular-cli@1.0.0"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: angular-cli@1.0.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.0-beta.22-1, 1.0.0-beta.20-4, 1.0.0-beta.20-3, 1.0.0-beta.20-2, 1.0.0-beta.20-1, 1.0.0-beta.2-mobile
 1.0.0-beta.2-mobile.3, 1.0.0-beta.2-mobile.2, 1.0.0-beta.2-mobile.1, 1.0.0-beta.2-mobile, 1.0.0-beta.19-3, 1.0.0-beta.12-
1.0.0-beta.11-webpack.9-4, 1.0.0-beta.11-webpack.9-3, 1.0.0-beta.11-webpack.9-2, 1.0.0-beta.11-webpack.9-1, 1.0.0-beta.11-
pack.9, 1.0.0-beta.11-webpack.8, 1.0.0-beta.11-webpack.7, 1.0.0-beta.11-webpack.6, 1.0.0-beta.11-webpack.5, 1.0.0-beta.11-
pack.4, 1.0.0-beta.11-webpack.3, 1.0.0-beta.11-webpack.2, 1.0.0-beta.11-webpack, 1.0.0-beta.28.3, 1.0.0-beta.28.2, 1.0.0-b
.28, 1.0.0-beta.27, 1.0.0-beta.26, 1.0.0-beta.25.5, 1.0.0-beta.25.4, 1.0.0-beta.25.3, 1.0.0-beta.25.2, 1.0.0-beta.25, 1.0.
eta.24, 1.0.0-beta.22, 1.0.0-beta.21, 1.0.0-beta.18, 1.0.0-beta.17, 1.0.0-beta.16, 1.0.0-beta.15, 1.0.0-beta.14, 1.0.0-bet
2, 1.0.0-beta.10, 1.0.0-beta.9, 1.0.0-beta.8, 1.0.0-beta.6, 1.0.0-beta.5, 1.0.0-beta.4, 1.0.0-beta.1, 1.0.0-beta.0, 0.1.0,
0.39, 0.0.37, 0.0.34, 0.0.33, 0.0.31, 0.0.30, 0.0.29, 0.0.28, 0.0.27, 0.0.26, 0.0.25, 0.0.24, 0.0.23, 0.0.22, 0.0.20, 0.0.
 0.0.18, 0.0.17, 0.0.16, 0.0.15, 0.0.14, 0.0.13, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3,
.2, 0.0.1, 0.0.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\neagrawa\npm-debug.log

### Desired functionality.

I want to install latest version of angular-cli i.e. angular-cli@1.0.0

**Comment by clydin** [comment]
Please try `npm install -g @angular/cli`.

**Comment by RPGillespie6** [comment]
See #5842. The old angular-cli could be stuck in a path that npm no longer searches.

**Comment by nsholmes** [comment]
I'm having a similar issue. I've spent the last 6 hours searching the web for a solution. I am using `npm install -g @angular/cli`

**Comment by RPGillespie6** [comment]
@nsholmes Did you try running this command as Administrator? This looks like a permissions issue.

**Comment by nsholmes** [comment]
I opened CMD as administrator.

**Comment by olegkon** [comment]
Install that target:     "@angular/cli": "1.0.0"   instead of   "angular-cli": "1.0.0"
It was recently renamed.

**Comment by filipesilva** [comment]
The name changed, as @clydin and @olegkon mentioned. @nsholmes you seem to be having permission problems instead. Not sure what the problem is but it's a npm/windows thing.
