### ISSUE TITLE
Instability after upgrading to @angular/cli 1.0.0

### ISSUE THREAD

**Issue by Tomagi** [angular/angular-cli#5859]
Hi all,

After upgrading to @angular/cli 1.0.0 we're having hard time with launching our project using ng serve.
Very often compilation fails with errors, which don't exist.

Errors can be it can't find a component, which is definately exist on that route and after several attempts [without changing anything!] it worked out.

Are you familiar with these issues?

Thanks.

**Comment by filipesilva** [comment]
I haven't heard of anything similar thus far. If you can provide us with a repro, we can look into it.

**Comment by alan-agius4** [comment]
Closing as no repo was provided
