### ISSUE TITLE
Only working in Edge & Chrome

### ISSUE THREAD

**Issue by GuerrillaCoder** [angular/angular-cli#5860]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Windows 10
@angular/cli: 1.0.0
node: 6.10.0
os: win32 x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/compiler-cli: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/platform-server: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0

### Repro steps.
When building my project with `ng build --prod` it only works in edge & chrome.

### The log given by the failure.
The are no errors in console, the site just doesn't load

### Desired functionality.
App to load in all browsers on supported list.

### Mention any other details that might be useful.

I am using the web animation api so I have run `npm install --save web-animations-js` and also uncommented `import 'web-animations-js';` in polyfills.ts.

App works fine in latest chrome and edge but I tried in IE11 and it doesn't work.  Just a blank screen with background colour

**Comment by clydin** [comment]
Additional polyfills are required for IE9, IE10 and IE11.  Try uncommenting the relevant lines in `polyfills.ts`.

**Comment by GuerrillaCoder** [comment]
Thanks, I had missed them.

**Comment by guenam** [comment]
@GuerrillaCoder: I'm having the same symptoms but for all browsers on iOS + Safari on MacOS (works on Firefox & Chrome). Have you by any chance tested your app on those configurations? I'm asking by despair: I have spent 6 hours already on this and you're the only one I found yet with similar symptoms.

**Comment by GuerrillaCoder** [comment]
@guenam I am not on mac so not sure.  You can check my url though: https://moboz.co.uk

**Comment by guenam** [comment]
I just tested your website on my iPhone 4s (old... safari 9): everything seems fine. At least my website passed your mobile tests! ;-)

Thanks for your super quick reply!

**Comment by GuerrillaCoder** [comment]
@guenam Did you uncomment everything in polyfils.ts?  My issue was that there was some individual modules I hadn't uncommented.

**Comment by guenam** [comment]
Yes, I did and even tried adding others... Nothing is the log makes it super frustrating. Thanks again.

**Comment by GuerrillaCoder** [comment]
@guenam all I can suggest is to make a new default project and then test it.  Then re-add elements one by one until it breaks.  Super annoying but it should isolate the issue.

**Comment by guenam** [comment]
@GuerrillaCoder I did that and found out that an "url slugifier" package called limax was the source of the issue. Quite a good package though, I'll henceforth use it only on server side. 

Thanks for your good counsel!
