### ISSUE TITLE
Options for script files in .angular-cli.json

### ISSUE THREAD

**Issue by pbarringer3** [angular/angular-cli#5861]
### Bug Report or Feature Request
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
```
$ ng --version

@angular/cli: 1.0.0
node: 7.2.1
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
```

### Desired functionality.
I want the ability to choose where the script is loaded. For example, MathJax operates by looking in the head for where it was loaded to provide some of its functionality. This is a problem because the scripts are loaded in the body instead of the head. I would like the ability to choose this on a case by case basis, possibly with the syntax:

```
{"location" : "path/to/script.js", "inject" : "head"}
```

If a solution to this problem already exists, please let me know.

Thanks!

**Comment by clydin** [comment]
For exact placement within `index.hml`, you can add the script as an asset and then add the script tag to the desired location in the source `index.html`.  This allows fine-grained control over not only the placement but any additional attributes you may desire on the script tag.

**Comment by filipesilva** [comment]
Closing as answered by @clydin, cheers!

**Comment by polyglotinc** [comment]
how about giving an actual simple example of that answer, since this is being closed out.
