### ISSUE TITLE
JIT I18n support

### ISSUE THREAD

**Issue by zh99998** [angular/angular-cli#5869]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
seems angular-cli now only support i18n with AOT build?
it's hard during development without JIT compiler..

**Comment by Angular2Guy** [comment]
Have look at issue https://github.com/angular/angular-cli/issues/3540

**Comment by filipesilva** [comment]
This is the only supported approach in the CLI, yes. We don't have plans to support it in JIT since ng-i18n needs AOT compilation. You can submit a feature request in https://github.com/angular/angular

**Comment by mashbrno** [comment]
If so, can you please update the official [documentation](https://angular.io/guide/i18n)? It refers to Angular CLI on top and describes JIT version below. At least put a big warning there!

**Comment by kwiesmueller** [comment]
I think I stumbled into this Problem.
So to clarify, the description shown in the docs using JIT won't work?

When running ng i18n I am getting weird templating errors I don't get when building the app. But the docs tell me no other way to extract the messages.

Maybe I did not understand AOT vs. JIT correctly, but building the app in different languages makes no sense to me, as it would require different deployments then, right?
So we would need JIT but "by accident" I now find this issue telling me, JIT is not supported?

**Comment by mashbrno** [comment]
Yes, AFAIK JIT is not supported. Most of the users stick to a single language and the overhead of downloading, parsing and processing resource files on the client was simply too high. You can always deploy the application into subdirectories, eg. /en, /de, /jp
