### ISSUE TITLE
'ng' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by fstbraz** [angular/angular-cli#5872]
### Versions
Node v6.10.1
NPM 3.10.10
Windows 10

### Repro steps
npm install -g @angular/cli@latest

### The log given by the failure
'ng' is not recognized as an internal or external command, operable program or batch file.

### Details
Hello, after installing angular-cli the 'ng' command simply doesn't work on windows.
There are other issues reporting this bug, but they don't have clear solutions.
Note: I don't have administrator access on this computer.

![screnshoot](https://cloud.githubusercontent.com/assets/1130728/24794554/fc0beee6-1b7d-11e7-9c62-bd89ecd65a4a.jpg)

**Comment by MRokas** [comment]
What does `echo %PATH%` return? And where did angular-cli get installed?

**Comment by fstbraz** [comment]
The echo %PATH% returns C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;C:\Users\fausto.braz\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\fausto.braz\AppData\Local\Microsoft\WindowsApps;C:\Users\fausto.braz\AppData\Local\atom\bin

**Comment by MRokas** [comment]
What about `dir C:\Users\fausto.braz.dnx\AppData\Roaming\npm` ?

**Comment by fstbraz** [comment]
Returns "The system cannot find the path specified."

**Comment by babilog** [comment]
Have you installed @angular/cli globally? Try npm install -g @angular/cli

**Comment by fstbraz** [comment]
@babilog  yes, please read my first description --> Repro steps.

**Comment by MRokas** [comment]
Hm.. what about `dir %AppData%\npm\node_modules`? -

**Comment by fstbraz** [comment]
@MRokas 

07/04/2017  11:11    <DIR>          .
07/04/2017  11:11    <DIR>          ..
07/04/2017  10:19    <DIR>          @angular
07/04/2017  11:06    <DIR>          gulp
07/04/2017  11:11    <DIR>          modular
07/04/2017  09:45    <DIR>          typescript

**Comment by fstbraz** [comment]
Any solution for this guys,?

Can't find anyone to people without adiministrator access...

**Comment by MRokas** [comment]
From what I see, your angular-cli didn't install properly, nor you've global's in your PATH variable.
You should find where your ng file is located at, and add that location to PATH variable.

**Comment by fstbraz** [comment]
@MRokas 

In `C:\Users\fausto.braz\AppData\Roaming\npm` the commands are working.
![cli](https://cloud.githubusercontent.com/assets/1130728/24905646/95119fba-1eac-11e7-9e8e-6f8f609f0473.jpg)

How can I add this to the windows PATH? (Windows noob here :D).

**Comment by fstbraz** [comment]
I get it worked by adding to my user account enviroment PATH:

For that go to 

> Control Panel > User accounts > Change my environmnet variables

 and add the path to your npm  AppData\Roaming\npm in my case 

> C:\Users\fausto.braz\AppData\Roaming\npm

**Comment by filipesilva** [comment]
Thanks for everyone that helped solve this, cheers!

**Comment by naru6be** [comment]
At last find the solution for ng command is not working issue ,Find the solution below http://itechiesol.blogspot.com/2017/07/angular-cli-ng-command-is-not-working.html

**Comment by Dinesh1430** [comment]
thanks for the clean Solution for the Issue 
it been an helpfull Resource :+1:

**Comment by RahulSolanki1487** [comment]
> At last find the solution for ng command is not working issue ,Find the solution below http://itechiesol.blogspot.com/2017/07/angular-cli-ng-command-is-not-working.html

this helped me to resolve issue on windows 10.
