### ISSUE TITLE
ng new --prefix seems to be ignored

### ISSUE THREAD

**Issue by SanderElias** [angular/angular-cli#5873]
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.10.1
os: win32 x64

### Repro steps.
ng new AppshellSample --prefix app-shell --style scss --routing -d

### The log given by the failure.
installing ng
You specified the dry-run flag, so no changes will be written.
  create .editorconfig
  create README.md
  create src\app\app-routing.module.ts
  create src\app\app.component.scss
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.scss
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Project 'AppshellSample' successfully created.

### Desired functionality.
this part:
  create src\app\app-routing.module.ts
  create src\app\app.component.scss
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts

Should be:
  create src\app-shell\app-shell-routing.module.ts
  create src\app-shell\app-shell.component.scss
  create src\app-shell\app-shell.component.html
  create src\app-shell\app-shell.component.spec.ts
  create src\app-shell\app-shell.component.ts
  create src\app-shell\app-shell.module.ts

### Mention any other details that might be useful.
Sometimes you just need a differently named top-level component.

**Comment by clydin** [comment]
The `--prefix` option controls the selector prefix for components/directives.  The file structure and naming is intentional and follows the [style guide](https://angular.io/styleguide).

**Comment by SanderElias** [comment]
@clydin There are times the style-guide need an override. In this case, I need a different starting point. I can do it manually, but when I do that, and I ng create anything it ends up in the ./src/app. And that's the wrong place.

**Comment by PascalPrecht** [comment]
As @clydin said, there seems to be a misunderstanding here. You can ng create in subfolders to create a different structure but `--prefix` configure selector prefixes.

**Comment by SanderElias** [comment]
@PascalPrecht Ok, so, what do I need to do to generate the thing I'm describing using the CLI, preferably without manual intervention?

**Comment by PascalPrecht** [comment]
I think `src/app` is mandatory. But you can configure a different `root` in angular-cli.json.

Other than that you just

```
$ mkdir app-shell
$ cd app-shell
$ ng g ...
```

**Comment by SanderElias** [comment]
@PascalPrecht I tried, but somehow it failed me. Let me give it another go.
(BTW I'm in the Grand America Lobby right now, care to join and take a look at this?)

**Comment by SanderElias** [comment]
@clydin @PascalPrecht, I have discussed this with the style-guide (That materialised to me in the form of @wardbell ) and what I need and want is allowed by the guide. After some more digging, it turns out to be a bug in the CLI. I will keep this item closed, as the actual problem has nothing to do with --prefix.
