### ISSUE TITLE
cli component ignores changeDetection config

### ISSUE THREAD

**Issue by ritox842** [angular/angular-cli#5874]
I'm trying to set the .angular-cli.json config file and I want every component by default will be with the 'onPush' change detection strategy.

I've added this to the config file:
```
  "component": {
      "changeDetection": "onPush"
    }, 
```
As I saw in the cli wiki, but when I'm generating new components it not taken effect..
I also changed the default style extension and this one did work, since they both under the 'defaults' key  
I'm guessing its not some syntax error..

Anyone knows how to solve it? 
I'm using angular cli 1.0.0

Thanks.

**Comment by clydin** [comment]
The schema appears to require the value to be `OnPush` (note the capitalization).

There should probably be a warning or error message for invalid values.
Although in cases such as this, the alternate casing styles should probably be supported as well.
