### ISSUE TITLE
.ts file added to .angular-cli.json "scripts" section is no longer transpiled 

### ISSUE THREAD

**Issue by mr-alede** [angular/angular-cli#5881]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.10.2
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
Windows 10

### Repro steps.
.angular-cli.json
```javascript
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "test-prj"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [
	"vendor.ts"
	],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
```

vendor.ts
```javascript
import * as jquery from 'jquery';
window['jQuery'] = window['$'] = jquery;
```

It is a boilerplate project generated by Angular CLI 1.0.
I installed jQuery, created vendor.ts in "src" folder and added a reference to that .ts into "scripts" section of .angular-cli.json

"ng serve" works fine. But in browser console I see following:
```javascript
Uncaught SyntaxError: Unexpected token import
    at eval (<anonymous>)
    at webpackJsonp.208.module.exports (scripts.bundle.js:28)
    at Object.107 (scripts.bundle.js:6)
    at __webpack_require__ (inline.bundle.js:53)
    at Object.247 (scripts.bundle.js:37)
    at __webpack_require__ (inline.bundle.js:53)
    at webpackJsonpCallback (inline.bundle.js:24)
    at scripts.bundle.js:1
```
scripts.bundle.js contains following:
```javascript
/***/ (function(module, exports) {
module.exports = "import * as jquery from 'jquery';\r\nwindow['jQuery'] = window['$'] = jquery;\r\n//# sourceMappingURL=vendor.js.map"
```

It looks like vendor.ts is no longer transpiled. It used to work fine in Angular CLI 1.0.0-beta.26.

Could someone help me with resolving this problem?

### The log given by the failure.
Uncaught SyntaxError: Unexpected token import
    at eval (<anonymous>)
    at webpackJsonp.208.module.exports (scripts.bundle.js:28)
    at Object.107 (scripts.bundle.js:6)
    at __webpack_require__ (inline.bundle.js:53)
    at Object.247 (scripts.bundle.js:37)
    at __webpack_require__ (inline.bundle.js:53)
    at webpackJsonpCallback (inline.bundle.js:24)
    at scripts.bundle.js:1

**Comment by delasteve** [comment]
You should be able to the `scripts` to the following

```
"scripts": [
  "../node_modules/jquery/dist/jquery.js"
],
```

The `scripts` array is meant to be for global JavaScript (not TypeScript) libraries that need to be loaded before the main app.

**Comment by mr-alede** [comment]
The problem is that I have SummernoteJS and KendoUI in my real project. Summernote depends on jQuery placed onto the window, and KendoUI depends on jQuery via "require('jquery')". It means that this way of integrating jQuery 
```javascript
"scripts": [
  "../node_modules/jquery/dist/jquery.js"
],
```
leads to creating two instances of jQuery: a global instance for Summernote and a local instance for KendoUI.

Integrating jQuery via "vendor.ts" covered both the cases perfectly.
```javascript
import * as jquery from 'jquery';
window['jQuery'] = window['$'] = jquery;
```
 I imported a local instance and immediately placed it onto the window. 

Of course, I can try following: when I need a global instance, I just use $ without importing jQuery, and when I need a local instance of jQuery, I can import it via
```javascript 
import * as $ from 'jquery';
```
but it looks a bit weird to me. 
Could you please suggest a way to integrate jQuery which would cover both the cases: 
1 libraries that depend on global instance of jquery
2 libraries that depend on jquery via "require('jquery')"?

**Comment by ciesielskico** [comment]
Have you tried putting `import './vendor.ts'` inside `main.ts`?

**Comment by mr-alede** [comment]
Many thanks! Works fine.
