### ISSUE TITLE
Module not found. Can't resolve @types/bcrypt

### ISSUE THREAD

**Issue by jried31** [angular/angular-cli#5891]
Problem: Unable to resolve "@types/bcrypt" in an angular2 Typescript project.
Installation: npm install --save @types/bcrypt

Declaration inside file.ts
import {hashSync} from '@types/bcrypt';

Error Received: Module not found: Error: Can't resolve '@types/bcrypt'
Angular2 Server Command: "ng serve" from Angular CLI

Is there a configuration that Im missing in the files that's making the module not seen?

**Comment by robwormald** [comment]
You should import from 'bcrypt', not @types/bcrypt - typescript is smart enough to link up bcrypt with @types/bcrypt
