### ISSUE TITLE
ng: command not found

### ISSUE THREAD

**Issue by Cptmorgan27** [angular/angular-cli#5893]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

node:7.8.0
npm:4.2.0
MacOs Sierra 10.12.14

### Repro steps.

Ran in my home directory: `npm install -g @angular/cli `
fallowed by `ng new my-app`

### Mention any other details that might be useful.

I attempted [-bash: ng: command not found #5021](https://github.com/angular/angular-cli/issues/5021) did not correct issue.

**Comment by beeman** [comment]
@Cptmorgan27 it looks like the node binaries are not in your path. Can you paste the output of `echo $PATH` and `npm install -g @angular/cli` ?

**Comment by Cptmorgan27** [comment]
echo $PATH : /Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin


npm install -g @angular/cli: 
/usr/local/Cellar/node/6.5.0/libexec/npm/bin/ng -> /usr/local/Cellar/node/6.5.0/libexec/npm/lib/node_modules/@angular/cli/bin/ng

> fsevents@1.1.1 install /usr/local/Cellar/node/6.5.0/libexec/npm/lib/node_modules/@angular/cli/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/Cellar/node/6.5.0/libexec/npm/lib/node_modules/@angular/cli/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> node-sass@4.5.2 install /usr/local/Cellar/node/6.5.0/libexec/npm/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/User/.npm/node-sass/4.5.2/darwin-x64-51_binding.node

> node-sass@4.5.2 postinstall /usr/local/Cellar/node/6.5.0/libexec/npm/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/build.js

Binary found at /usr/local/Cellar/node/6.5.0/libexec/npm/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/darwin-x64-51/binding.node
Testing binary
Binary is fine

**Comment by beeman** [comment]
So it looks like your global node binaries get installed in `/usr/local/Cellar/node/6.5.0/libexec/npm/bin`, but it's not in your path.

To fix this you can add this line to the file `.bashrc` in your home dir.
 
```
export PATH="/usr/local/Cellar/node/6.5.0/libexec/npm/bin:$PATH"
```

After adding this and opening a new terminal window, your globally installed npm binaries should work.

**Comment by Cptmorgan27** [comment]
@beeman Sorry for the time lapse but I didn't have a .bashrc. So, I created one added what you suggested, restart and nothing.

**Comment by Cptmorgan27** [comment]
@beeman Thanks!! didn't have a .bashrc but had .bash_profile. Now, everything is working.

**Comment by SriramJothiswaran** [comment]
@Cptmorgan27  can you explain what you did to resolve the problem

**Comment by sumitarora** [comment]
Closing as above.
