### ISSUE TITLE
Having trouble installing packages

### ISSUE THREAD

**Issue by DhavalRu** [angular/angular-cli#5894]
**### Bug Report or Feature Request (mark with an `x`)**
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

**### Versions**
node v6.10.2
npm  v3.10.10
ng: @angular/cli 1.0.0
OS: Windows 10, win32 x64

**### Repro steps.**
So everytime I try to run ng new projectname, I get the Error: EPERM: operation not permitted, rename

**### The log given by the failure.**
104997 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\Dhaval\desktop\first\first\node_modules\.staging\zone.js-a001375e' -> 'C:\Users\Dhaval\desktop\first\first\node_modules\@angular\cli\node_modules\zone.js'
104997 verbose stack     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
104997 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
104997 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
104997 verbose stack
104997 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\Dhaval\desktop\first\first\node_modules\.staging\zone.js-a001375e' -> 'C:\Users\Dhaval\desktop\first\first\node_modules\@angular\cli\node_modules\zone.js'
104997 verbose stack     at Error (native)
104998 verbose cwd C:\Users\Dhaval\desktop\first\first
104999 error Windows_NT 10.0.14393
105000 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--quiet" "install"
105001 error node v6.10.2
105002 error npm  v3.10.10
105003 error path C:\Users\Dhaval\desktop\first\first\node_modules\.staging\zone.js-a001375e
105004 error code EPERM
105005 error errno -4048
105006 error syscall rename
105007 error Error: EPERM: operation not permitted, rename 'C:\Users\Dhaval\desktop\first\first\node_modules\.staging\zone.js-a001375e' -> 'C:\Users\Dhaval\desktop\first\first\node_modules\@angular\cli\node_modules\zone.js'
105007 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
105007 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
105007 error     at FSReqWrap.oncomplete (fs.js:123:15)
105007 error
105007 error Error: EPERM: operation not permitted, rename 'C:\Users\Dhaval\desktop\first\first\node_modules\.staging\zone.js-a001375e' -> 'C:\Users\Dhaval\desktop\first\first\node_modules\@angular\cli\node_modules\zone.js'
105007 error     at Error (native)
105007 error  { Error: EPERM: operation not permitted, rename 'C:\Users\Dhaval\desktop\first\first\node_modules\.staging\zone.js-a001375e' -> 'C:\Users\Dhaval\desktop\first\first\node_modules\@angular\cli\node_modules\zone.js'
105007 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
105007 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
105007 error     at FSReqWrap.oncomplete (fs.js:123:15)
105007 error
105007 error Error: EPERM: operation not permitted, rename 'C:\Users\Dhaval\desktop\first\first\node_modules\.staging\zone.js-a001375e' -> 'C:\Users\Dhaval\desktop\first\first\node_modules\@angular\cli\node_modules\zone.js'
105007 error     at Error (native) parent: '@angular/cli' }
105008 error Please try running this command again as root/Administrator.
105009 verbose exit [ -4048, true ]

**### Mention any other details that might be useful.**
I've tried everything that has been suggested to fix this problem, such as restarting computer, cleaning cache, disabling antivirus, giving permissions to nodejs install folder, running as administrator, giving permissions to git install folder, and nothing seems to work. Thanks.

**Comment by beeman** [comment]
@DhavalRu to isolate the problem, does it work when you run `ng new projectname --skip-npm`?

If so, the problem is related to the installation of the packages using `npm install`

**Comment by DhavalRu** [comment]
Hey, yea I don't get any errors when I skip npm, but then I would have to manually install all the packages..zz
Thanks for your help.

**Comment by filipesilva** [comment]
There''s something in your system that's not allowing `npm` to do what it needs to do. It's not something we can solve from within the CLI, it's a permissions thing in your machine. Sorry I can't help more.
