### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'forEach' of undefined     at Promise.resolve.then.then.then

### ISSUE THREAD

**Issue by jamilalisgandarov** [angular/angular-cli#5895]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 7.8.0
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/compiler-cli: 2.4.10

Windows 10

### The log given by the failure.
ERROR in ./src/app/dashboard/contents/profile/profile.component.ts
Module build failed: TypeError: Cannot read property 'forEach' of undefined
    at Promise.resolve.then.then.then (C:\Users\Pinkman\Desktop\Projects\Kometa\node_modules\@ngtools\webpack\src\loader.j
s:350:40)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/dashboard/dashboard.module.ts 17:0-72
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

### Mention any other details that might be useful.
It is Angular 2 project, it was working totally fine before updating angular-cli. I can not find what really problem is.

**Comment by beeman** [comment]
@jamilalisgandarov can you show the content of `./src/app/dashboard/contents/profile/profile.component.ts` ?

**Comment by jamilalisgandarov** [comment]
I have solved this by **downgrading @angular/cli version to "^1.0.0-rc.0"**.  @beeman

**Comment by jamilalisgandarov** [comment]
But here is the content of profile.component.ts, it gives error in higher versions.

`    
     import { Component } from '@angular/core';

    import { RouterModule } from "@angular/router";

    import { CommonModule } from '@angular/common';

    import { LoadingComponent } from '../../../shared/loading/loading.component';

    import { AuthService } from '../../../auth/auth.service';
    import {
    FormGroup,
    FormControl,
    Validators,
    FormBuilder
    } from "@angular/forms";
    import { DashboardService } from '../../dashboard.service';
    import { NgClass } from '@angular/common';
    import { ProfileService } from './profile.service';

    @Component({

    selector: 'ca-profile',

    templateUrl: './profile.component.html',

    styleUrls: [],

    providers: [AuthService, ProfileService]

    })

    export class ProfileComponent {

    user = {};

    isChecking = false;

    isSuccess = false;

    hasError = false;

    isLoading = false;

    userForm: FormGroup;

    hasErrors(field) {
        return this.userForm.get(field).errors;
    };

    isTouched(field) {
        return this.userForm.get(field).touched;
    }

    isPristine(field) {
        return this.userForm.get(field).pristine;
    }

    constructor(private _authService: AuthService,
        private _dashboardService: DashboardService,
        private _fb: FormBuilder,
        private _profileService: ProfileService) {
        this.userForm = _fb.group({
            oldPass: ['', [Validators.required], [this.equalToOld.bind(this)]],
            newPass: ['', [Validators.required, Validators.minLength(4)]],
            confirmPass: ['', [Validators.required, Validators.minLength(4)]]
        })
    }

    ngOnInit() {
        this.isLoading = true;
        this._dashboardService.setSectionName({ name: 'Sənin hesabın', isVisible: true });
        this.user["name"] = this._authService.getCookie("user_name");
        this.user["mail"] = this._authService.getCookie("user_email");
        this.user["type"] = this._authService.getCookie("user_type");
        this.isLoading = false;
    }

    changePassword() {
        this.isLoading = true;
        this._profileService.changePassword({
            oldPass: this.userForm.get('oldPass').value,
            newPass: this.userForm.get('newPass').value,
            confirmPass: this.userForm.get('confirmPass').value
        }).subscribe(data => {
            if (data.status) {
                this.userForm.reset();
                this.isSuccess = true;
            } else
                this.hasError = true;
        }, err =>
                this.hasError = true,
            () =>
                this.isLoading = false)
    }

    confirmPass() {
        var newPass = this.userForm.get('newPass').value;
        var confirmPass = this.userForm.get('confirmPass').value;

        if (newPass == '' && confirmPass == '')
            return null;

        if (newPass == confirmPass)
            return true;

        return false
    }

    //async validator
    equalToOld(control) {
        this.isChecking = true;
        return new Promise((resolve, reject) => {
            this._profileService.checkPassword(control.value)
                .subscribe(data => {
                    if (data.status)
                        return resolve(null);
                    else
                        return resolve({ equalToOld: true });
                }, err =>
                    this.hasError = true,
                () =>
                    this.isChecking = false)
        });
    }
}`

**Comment by zhaxi** [comment]
same issue

**Comment by jamilalisgandarov** [comment]
**SOLUTION**

You need to show your css file , otherwise you will get error. As you can see I have not showed it in my component: 

`@Component({

selector: 'ca-profile',

templateUrl: './profile.component.html',

**styleUrls: [],**

providers: [AuthService, ProfileService]

})
`
