### ISSUE TITLE
ng test does not display test results in console

### ISSUE THREAD

**Issue by odannyboy000** [angular/angular-cli#5902]
### Bug Report or Feature Request (mark with an `x`)
`x`

ng test does not display test results in console *unless* specifying --single-run

### Versions.
ng --version:

@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.

cmd> ng test

### Desired functionality.

You should see all the tests that pass/fail

**Comment by filipesilva** [comment]
I'm not sure what you mean. I can see tests passing in the console output:

```
D:\sandbox\master-project>ng test
04 05 2017 15:42:55.893:WARN [karma]: No captured browser, open http://localhost:9876/
04 05 2017 15:42:55.908:INFO [karma]: Karma v1.4.1 server started at http://0.0.0.0:9876/
04 05 2017 15:42:55.909:INFO [launcher]: Launching browser Chrome with unlimited concurrency
04 05 2017 15:42:55.980:INFO [launcher]: Starting browser Chrome
04 05 2017 15:42:57.624:INFO [Chrome 57.0.2987 (Windows 10 0.0.0)]: Connected on socket QJZ5LXvh04fhg8q0AAAA with id 38922174
Chrome 57.0.2987 (Windows 10 0.0.0): Executed 3 of 3 SUCCESS (0.186 secs / 0.146 secs)
```

(Focus on ` Executed 3 of 3 SUCCESS`).

**Comment by spinachandkale** [comment]
Hi,

I have the same problem with ng test, it is not showing list of tests executed, and success/fail info for an individual test. I tried with --log-level=debug option, but not much help. 

My scenario is: There are around 250 tests, but it's saying 97/97 success, I like to know which tests were considered and why the others were not taken into account.

Please let me know if I can find out this info through ng test command. 

Thanks

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
