### ISSUE TITLE
ng e2e behind a corporate proxy fails due to a self-signed certificate in chain

### ISSUE THREAD

**Issue by Viehwoidler** [angular/angular-cli#5903]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 7.6.0
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.
Start ng e2e behind a corporate proxy and it will fail due to a self-signed certificate in chain

### The log given by the failure.
Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1081:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:186:7)
    at TLSSocket._finishInit (_tls_wrap.js:599:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:429:38)

### Desired functionality.
Webdriver Update without certificate check

### Mention any other details that might be useful.
It works when I add ignore_ssl: true to the parameters of webdriverUpdate.program.run (e2e.js:55)

**Comment by cexbrayat** [comment]
You can add a script to manually download the webdrivers in your `package.json`,
that will ignore the SSL certificate:
```
"scripts": {
  "pree2e": "webdriver-manager update --ignore_ssl"
}
```
Then run the e2e tests without downloading the drivers:

    ng e2e -wu false

See [the docs](https://github.com/angular/angular-cli/blob/master/docs/documentation/e2e.md)

**Comment by Viehwoidler** [comment]
If I use this setup with yarn run e2e I get the following error (code. 135): Could not find update-config.json...

**Comment by filipesilva** [comment]
On Angular CLI's side the best we can do is not run webdriver update, like @cexbrayat showed. 

Please open a new issues for the `update-config.json` problem you are experiencing.
