### ISSUE TITLE
i have problem with generation dist in other path in server 

### ISSUE THREAD

**Issue by Programmercito** [angular/angular-cli#5905]
i have a project with angular cli "@angular/cli": "1.0.0-beta.32.3", runs perfect in localhost:4200/ but i need in server runs in localhost:4200/pathroot but i find in google this solution:

in index.html:     base href="./"

and runs perfect but in urls with path large , for example:

localhost:7001/pathroot/forms/standard i get this error when refresh the page:

inline.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
polyfills.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
scripts.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
styles.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
main.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
 on ly in refresh page.

but in  path : localhost:7001/pathroot/forms the resfresh works

this is a bug or how configurate angular cli for runs well in other path?

**Comment by jamilalisgandarov** [comment]
It can be solved by htacess. This one works for me: 

Options +FollowSymLinks

<ifModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !index
    RewriteRule (.*) index.html [L]
    Header set Access-Control-Allow-Origin "*"
</ifModule>

**Comment by Programmercito** [comment]
i dont use apache :(

**Comment by dave11mj** [comment]
@Programmercito this might be helpful https://github.com/angular/angular-cli/blob/master/docs/documentation/build.md 

when you run `ng build` you can provide a `--base-href` for the base path your application will run on. I haven't tried it myself, but might be more appropriate than updating `index.html` directly.

**Comment by filipesilva** [comment]
You need to configure your server to have fallback to index.html. You can read more about that in https://angular.io/docs/ts/latest/guide/deployment.html

**Comment by Programmercito** [comment]
yes the server needed modified but, other alternative is use hash in the urls, works for me
