### ISSUE TITLE
Angular 2 AOT Compilation Error - New Instance of object when create routes

### ISSUE THREAD

**Issue by eronalves** [angular/angular-cli#5909]
I've implemented a RouteConfigBuilder for my specific purpose clear the routes declarations with custom variables.

route-builder.type.ts

 ```
export class RouteBuilder {
  private routeConfigBuilders: RouteConfigBuilder[] = [];
  private currentRouteConfig: RouteConfigBuilder;

  public add(routeConfigBuilder: IRouteConfigBuilder): RouteBuilder {
    this.routeConfigBuilders.push(RouteConfigBuilder.get(routeConfigBuilder));
    return this;
  }

  public build(): Routes {
    const routes: Routes = [];
    let routeConfig: IRouteConfig;

    for (const routeConfigBuilder of this.routeConfigBuilders) {
      routeConfig = routeConfigBuilder.build();
      routes.push(this.routeConfigToRoute(routeConfig));
    }

    return routes;
  }

  private routeConfigToRoute(routeConfig: IRouteConfig): Route {
    const route: Route = {};

    for (const prop in routeConfig) {
      if (routeConfig[prop]
        || ((typeof routeConfig[prop] === 'string')
          && (routeConfig[prop] === ''))
      ) {

        if ((prop === 'loadChildren')
          && !((typeof routeConfig[prop] === 'string'))
        ) {
          route[prop] = () => routeConfig[prop];
        } else if (prop === 'addChildrenCallback') {
          route['children'] = routeConfig[prop]().build();
        } else {
          route[prop] = routeConfig[prop];
        }
      }
    }

    return route;
  }

}
```

And in my routing-module declarations:

```
export function appRoutes() {
  return new RouteBuilder()
    // always first
    .add({
      path: '',
      redirectTo: 'dashboard',
      pathMatch: 'full'
    })

    .add({
      path: '',
      loadChildren: AuthModule
    })

    .add({
      path: '',
      loadChildren: FeaturesModule,
      canActivate: [AuthGuard]
    })

    // always last
    .add({
      path: '**',
      component: PageNotFoundComponent
    })

    .build();
}


@NgModule({
  imports: [
    RouterModule.forRoot(appRoutes())
  ],
  exports: [
    RouterModule
  ]
})
export class AppRoutingModule { }
```

When I run ng build is returning:

> ERROR in Error encountered resolving symbol values statically. Calling function 'RouteBuilder', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol appRoutes in /Users/eronalves/Documents/thinkwork/frontend/thinkerp-web/src/app/app-routing.module.ts, resolving symbol appRoutes in /Users/eronalves/Documents/thinkwork/frontend/thinkerp-web/src/app/app-routing.module.ts, resolving symbol appRoutes in /Users/eronalves/Documents/thinkwork/frontend/thinkerp-web/src/app/app-routing.module.ts, resolving symbol appRoutes in /Users/eronalves/Documents/thinkwork/frontend/thinkerp-web/src/app/app-routing.module.ts, resolving symbol appRoutes in /Users/eronalves/Documents/thinkwork/frontend/thinkerp-web/src/app/app-routing.module.ts, resolving symbol appRoutes in /Users/eronalves/Documents/thinkwork/frontend/thinkerp-web/src/app/app-routing.module.ts, resolving symbol AppRoutingModule in /Users/eronalves/Documents/thinkwork/frontend/thinkerp-web/src/app/app-routing.module.ts, resolving symbol AppRoutingModule in /Users/eronalves/Documents/thinkwork/frontend/thinkerp-web/src/app/app-routing.module.ts, resolving symbol AppRoutingModule in /Users/eronalves/Documents/thinkwork/frontend/thinkerp-web/src/app/app-routing.module.ts

My declarations is the same in other modules but only in app-routing.module.ts and auth-routing.module.ts it's happen. If I remove my instance of RouteConfigBuilder it's working perfectly.

I tried in many ways to modify how I instantiate my RouteConfigBuilder and until now nothing helps me.

How do I do to instantiate my object in routes and AOT not show errors again?

Thanks a lot.

**Comment by filipesilva** [comment]
We don't currently support dynamically generated route definitions because they are not statically analyzable (so we can't make then work in AOT).
