### ISSUE TITLE
tslint above 5.0.0 does not lint semicolons

### ISSUE THREAD

**Issue by icepeng** [angular/angular-cli#5910]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.10.2
os: linux x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.

ng new yoshi
Then write code without semicolons.
ng lint

### The log given by the failure.

All files pass linting.

### Desired functionality.

lint error should occur.

### Mention any other details that might be useful.

https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/tslint.json#L72

4.x.x worked with ["always"]. But with tslint 5.0.0 and above, semicolon rule has to be [ true, "always" ]

**Comment by clydin** [comment]
A new project will use tslint version 4.5.x.  Following your steps with a new project produced lint errors.
Also the [recommended rules](https://github.com/palantir/tslint/blob/b9444e31dfa2557aec5bcd47d71435f71007b5ff/src/configs/recommended.ts#L151) for tslint 5.0 only use `always`.

**Comment by icepeng** [comment]
But @angular/material team is using tslint^5.0.0
https://github.com/angular/material2/blob/master/package.json
Or maybe I should go to the issue of tslint.

**Comment by clydin** [comment]
Codelyzer does not currently support 5.x.  Once it does, the default project template can support it as well.
Your described issue is still unreproducible.  Unfortunately, there is not much more that can be done.

**Comment by icepeng** [comment]
ok, I forgot to mention about package update in repro steps.
Codelyzer@3.0.0-beta should support 5.x.
Should open new issue when `ng new` project uses tslint^5.0.0 and same problem occurs.
