### ISSUE TITLE
I cannot disable AOT for tests, even so project generated without aot

### ISSUE THREAD

**Issue by gorshkov-leonid** [angular/angular-cli#5913]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report 
- [ ] feature request
```

### Versions.
1.0.0

### Repro steps.
hi, I ejected webpack config for project without aot. karma config contains frameworks: ['jasmine', '@angular/cli'], and 'angular-cli/plugins/karma'. But I got Reference to a local (non-exported) symbol '...'. Consider exporting the symbol. I like angular-cli/plugins/karma, it solve some problems of compatibility karma, webpack, phantom js. But I wont to use AOT. How to disable it?

**Comment by clydin** [comment]
An Angular static analysis pass is run on all builds (both AOT and JIT).

**Comment by gorshkov-leonid** [comment]
Yes, I see. Is it true, is it work as designed? I generated project **without --aot option**....

**Comment by clydin** [comment]
It is working as designed.  The static analysis supports lazy loading and is not linked to the AOT option.

**Comment by gorshkov-leonid** [comment]
static analysis imposes restrictions https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5

**Comment by filipesilva** [comment]
It does, yes. But on the flipside it also gives advance warning so that users don't have a nasty surprise of a lot of errors when they do decide to use AOT. Using `@ngtools/webpack` (which the CLI uses) does come with these restrictions by design.
