### ISSUE TITLE
Update guidance for @angular/* packages

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#5919]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
```
@angular/cli: 1.0.0
node: 6.9.5
os: darwin x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/platform-server: 4.0.0
@angular/router: 4.0.0
@angular/service-worker: 1.0.0-beta.8
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
```

### Repro steps.
n/a

### The log given by the failure.
n/a

### Desired functionality.
One of the major initiatives within Angular is to ensure that developers are using the latest versions of all of our packages. This includes `@angular/core` as well as `@angular/cli` and `@angular/material`.

Currently, we don't have a good way to ensure that developers know about our releases. We publish new versions to npm and announce them on twitter, but then it's up to developers to actually pull the latest versions of all packages to their project.

If a developer is using yarn or npm with shrinkwrap, then they have to take a step to update the lock files. If they don't use lock files, then they receive updates the next time they happen to reinstall their npm dependencies.

It would be great if we could find a way to notify developers about available updates in a way that strikes the balance between being helpful in ensuring that projects have up-to-date dependencies and not being annoying.

Several options to consider:
- before scaffolding a new project, check if there is a new version of cli that the user should update to before the project is scaffolded
- when developer calls `ng serve` they could get a notification to that their dependencies are outdated, with instructions on how to update.
- when updates are available, it would be great to have a single command that they can use to bump the versions.

**Comment by babilog** [comment]
@IgorMinar , great idea! Not sure yet of the complexity behind this feature, would you consider this a good first PR issue? Willing to progress this if so. Thanks!

**Comment by chaosmonster** [comment]
* checking for version before scaffolding is a great idea.
* `ng serve` feels a little bit heavy to me, as I use it very frequently and if I don't want to update this can get a little bit noisy and a lot of unnecessary calls. So I don't prefer that.
* a way to bump the versions sounds nice and I like that.

I would like to have a `ng update` command that bumps the versions runs tests and reverts the version with warnings if the tests failed otherwise the version bump will (if existing) be commited to the git.

**Comment by alan-agius4** [comment]
Related also to: https://github.com/angular/angular-cli/issues/14603

**Comment by alan-agius4** [comment]
This has been mainly addressed with the introduction of `ng update`.
