### ISSUE TITLE
Request: Build Stress Test

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#5921]
### Bug Report or Feature Request (mark with an `x`)
Feature request

### Versions.
n/a

### Repro steps.
n/a

### The log given by the failure.
n/a

### Desired functionality.

Create a script that creates CLI application with 1000 components, a lot of services and a 100 lazy routes. This should live in a separate repository under the `angular` organization.

Then create a simple script that clone, install and run a build on the application. For now this is enough to consider this issue closed. We need a separate issue for benchmarking.

**Comment by alan-agius4** [comment]
Closing as out of scope for the time being.
