### ISSUE TITLE
ng get or ng set cannot access array properties in .angular-cli.json

### ISSUE THREAD

**Issue by LuigiAndrea** [angular/angular-cli#5922]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.9.4
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.

`ng new my-app`
`cd my-app`
`ng get apps[0].prefix` or `ng get apps.0.prefix`, neither way works
I get this message. "value cannot be found"
The same happens using`ng set` to set a property in an array

**Comment by blaineadams** [comment]
I am getting the exact same issue. Only software difference is using node 6.9.0.

**Comment by somombo** [comment]
I am getting this issue too!
and I was about to report it so I elaborately recreated it for @hansl since he said he wasnt getting it.

Here you go:
https://github.com/somombo/ngSetGetIssue

**Comment by filipesilva** [comment]
Heya, I'm not sure in which PR this was fixed but atm I can't see it happening in master. 

```
kamik@T460p MINGW64 /d/sandbox/master-project (master)
$ ng get apps[0].prefix
app
```

Fix will be out in either next patch or minor version.
