### ISSUE TITLE
Use double quotes in unit tests to avoid needing to escape single quotes

### ISSUE THREAD

**Issue by DavidFrahm** [angular/angular-cli#5923]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.9.4
os: darwin x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.

Generate a new angular app:

`ng new my-app`

### The log given by the failure.

N/A

### Desired functionality.

The starter app uses single quotes for the strings which give descriptions to the unit test `describe` and `it` blocks, like this:

`it('should create the app',`...

However, the second unit test in `app.component.spec.ts` highlights how using common words with single quotes have to be dealt with differently:

`it(`should have as title 'app works!'`,`...

IMHO a better format would be to use double quotes, to require less thinking and more consistency between tests.

### Mention any other details that might be useful.

Single quotes are also used in tests created by other commands in the CLI such as `ng g component my-new-component`, and ideally all tests generated by any/all CLI commands would use this same new double quote syntax.

**Comment by filipesilva** [comment]
I'm sorry but this is one of those style concerns that we're just not addressing currently. Similar to https://github.com/angular/angular-cli/issues/1252, the solution is to allow users to configure it according to preference, and this isn't something we can do currently.

My advice meanwhile is to change the tslint rule to use double quotes, and make use of the autofix feature it has to auto convert new files.

I know it's not ideal, but it's something that you can do right now.
