### ISSUE TITLE
ng generate <blueprint> assumes top level component is named "app"

### ISSUE THREAD

**Issue by SanderElias** [angular/angular-cli#5927]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.0

### Repro steps.
Generate an app. Manually rename 'top component' 
I have done this in [this repo](https://github.com/SanderElias/cliDoesntAcceptDifferntTop)

now generate a new component/class/whatever.

### The log given by the failure.
The above steps will create an app folder, and put the generated files in there.

### Desired functionality.
Files should get generated in the right place, in my sample that's the shell folder.

### Mention any other details that might be useful.
I believe this [line](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/utilities/dynamic-path-parser.ts#L9) is responsible

**Comment by SanderElias** [comment]
@sumitarora Any progress? Is there something I can do?

**Comment by hansl** [comment]
This is a hard problem (since it's fixed in a lot of places), but fixable. @sumitarora do you need any help?

**Comment by pkamdem** [comment]
@sumitarora @hansl any update on this one?

Thanks for the great work guys!

**Comment by somombo** [comment]
looks like #6079 fixes this

**Comment by Brocco** [comment]
This issue was resolved with the introduction of schematics as the "blueprint" engine for the CLI.
