### ISSUE TITLE
Add dependency on @angular/animations for ng new projects

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#5928]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
@angular/cli: 1.0.0

### Desired functionality.
The CLI should add `@angular/animations` by default to the package.json. This would make it easier to use animations and Angular Material, without any downside on rendered bundles unless the user imports them.

**Comment by dave11mj** [comment]
Sounds like a duplicate of https://github.com/angular/angular-cli/issues/5785 .. There should be a PR open to add that feature https://github.com/angular/angular-cli/pull/5786

**Comment by filipesilva** [comment]
@dave11mj we're looking at just adding the dependency with no generated files. This is part of some improvements we're making for the new projects.

**Comment by dave11mj** [comment]
@filipesilva I opened a PR for the dependency on https://github.com/angular/angular-cli/pull/5786 it seemed alright with @Brocco except for a change request to remove the generated file which I already applied on the commit. Could you take a look at it and let me know if its aligned with the requirements ? ^^

Thanks ! :D

**Comment by filipesilva** [comment]
I'll ping @Brocco about it to see what should be done.

**Comment by filipesilva** [comment]
Heya, turned out work as ongoing in https://github.com/angular/angular-cli/pull/6144 now so I closed your PR in favor of that one. Thanks for taking the time to help out!

**Comment by dave11mj** [comment]
@filipesilva https://github.com/angular/angular-cli/pull/6144 fixes this issue too literally only by adding `@angular/animations` to the `package.json`. If thats the only requirement to address this ticket, then could we reopen https://github.com/angular/angular-cli/issues/5785, @Brocco seemed to like the idea, and it's significantly different given it asks not only for the `@angular/animations` package to be downloaded into the `node_modules` but also for animations to be supported out of the box by the cli, which involves a little more than just adding the package to the `package.json` .
