### ISSUE TITLE
templateUrl starting from root dir

### ISSUE THREAD

**Issue by CSchulz** [angular/angular-cli#5930]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [x] feature request (see below)
```

### Versions.
@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64
@angular/animations: 4.0.2
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2

### Repro steps.
Create component like the following:
```
@Component({
    selector: 'metricconfiglist',
    templateUrl: 'html/app.template.html',
})
export class AppComponent {
```

.angular-cli.json:
```
  "apps": [
    {
      "root": "",
```

### The log given by the failure.
```
ERROR in ./src/app.component.ts
Module not found: Error: Can't resolve './html/app.template.html' in 'webclient\src'
 @ ./src/app.component.ts 22:18-53
 @ ./src/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

### Desired functionality.
I am expecting that my path is understand as subfolder of root.

### Mention any other details that might be useful.
I have tried it with leading slash. Doesn't work either, it is translated into **'.//html/app.template.html'**

./ is kept as ./

folder structure

```
| webclient
| -> html
| -> src
   | - app.module.ts
   | - app.component.ts
   | - main.ts
```

### EDIT
Seems more to be a feature request regarding loader.js:

https://github.com/angular/angular-cli/blob/7cdf56ba02561dfe3f61c5a67f6bdd4f2e00992a/packages/%40ngtools/webpack/src/loader.ts#L270
```
function _getResourceRequest(element, sourceFile) {
    if (element.kind == ts.SyntaxKind.StringLiteral) {
        const url = element.text;
        // If the URL does not start with ./ or ../, prepends ./ to it.
        return `'${/^\.?\.\//.test(url) ? '' : './'}${url}'`;
    }
    else {
        // if not string, just use expression directly
        return element.getFullText(sourceFile);
    }
}
```

**Comment by filipesilva** [comment]
We only allow relative paths on templateUrl/styleUrls and aren't looking to allow absolute paths due to how loader semantics work. If you change it to `templateUrl: '../../../html/app.template.html',` (or however levels deep you are) it should work.

**Comment by maytis** [comment]
But, is there a way to introduce a dynamic variable in the path.
`templateUrl: '../../../html/${foldername}/app.template.html'`

**Comment by filipesilva** [comment]
@maytis no, that is not supported.

**Comment by CSchulz** [comment]
Can we create a pull request for it?

**Comment by filipesilva** [comment]
That isn't something we want to add to the CLI at this time, so PRs wouldn't be accepted for it.

**Comment by ranjit-redekar** [comment]
@filipesilva  Then how to achieve this.? is there any other ways.?

**Comment by mightytyphoon** [comment]
Hi, I love Angular and what the team is achieving.

I am looking for this option also, using the absolute path of tsconfig or an absolute path like `@templates/whatevertemplate.html`.

I will look into this even if `../../templates/whatever.html` works for now of course.

Regards.
