### ISSUE TITLE
A newly created, unmodified project doesn't work in some version of Chrome and IE

### ISSUE THREAD

**Issue by dxxvi** [angular/angular-cli#5932]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 7.8.0
os: win32 x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
npm --version: 4.4.4

### Repro steps.

generate a new project with ng new ... then ng serve
browse http://localhost:4200
Firefox 53.0 (maybe beta 10) 64-bit is ok.
Chrome Version 43.0.2357.134 m and IE 11.0.9600.18617 (document mode Edge) (that's what my company is using) show Loading ... The Chrome console says: Uncaught TypeError: Cannot read property 'apply' of undefined  common.es5.js:3109

### The log given by the failure.

N/A

### Desired functionality.

N/A

### Mention any other details that might be useful.

N/A

**Comment by clydin** [comment]
You need to adjust `polyfills.ts` for your project's support browsers.  The file is heavily commented to aid you in the process.

**Comment by smorhaim** [comment]
The default polyfill should work the way it is, and even then, brand-new... out-of-the-box should work.

Brand new app
Steps:
ng new test
cd test
ng start

This will gives the apply undefined error on Chrome and other browsers.

**Comment by guodong** [comment]
@smorhaim same error~

**Comment by dinvlad** [comment]
It worked before, I haven't modified anything in my code, just rerun my CD build (CodeBuild), it suddenly started to show this error with Chrome (58.0.3029.81-1)

**Comment by guodong** [comment]
zone.js issue, seems trying to fix it~ https://github.com/angular/zone.js/issues/746

**Comment by EladZucker** [comment]
@guodong  why do the suggest zone.js issue here ?

notice the error is :
 Uncaught TypeError: Cannot read property 'apply' of undefined **common.es5.js:3109**

it is not the same as the zone.js case.
