### ISSUE TITLE
How Can I maintain two different versions of angular-cli

### ISSUE THREAD

**Issue by sampath-karupakula** [angular/angular-cli#5933]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

**Comment by clydin** [comment]
Each project has its own local copy of the CLI.  The global version delegates to the project's local version if available.

**Comment by sampath-karupakula** [comment]
could you please some steps related to this. fully confused.

**Comment by grizzm0** [comment]
@sampath-karupakula hopefully the answer in #5955 answers your question.
