### ISSUE TITLE
Custom decorators does not work with AOT build

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular-cli#5938]
### Versions
1.0.0

### Repro steps
1. Create a class decorator with debugger statement 
```js
export function Test() {
  return function ( constructor ) {
     debugger;
  }
}
```
2. Use the class on a component
```js
@Component({...})
@Test()
export class TestComponent {}

```
3. Run the command `ng build --aot --prod`

### The log given by the failure.
The debugger statement never called. The decorator **doesn't** work. 

I also tried to create the decorator as npm package and compile the source file with the angular compiler `ngc -p tsconfig.json` but with no luck. 

### Desired functionality.
Custom decorators should be support out of the box by AOT.

**Comment by filipesilva** [comment]
@hansl I thought this was fixed, can you weigh in?

**Comment by ArielGueta** [comment]
This is related to the angular compiler, the issue on the angular repo.

**Comment by filipesilva** [comment]
Can you link the issue here for other users that run into it?

**Comment by ArielGueta** [comment]
https://github.com/angular/angular/issues/16023
