### ISSUE TITLE
ERROR in this. symbolResolver. getSymbolByModule is not a function

### ISSUE THREAD

**Issue by Karthi-SRV** [angular/angular-cli#5940]
While compiling i got this error
```
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 5.47 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 9.77 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.36 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in this.symbolResolver.getSymbolByModule is not a function
```
Angular version 4.0 and angular/angualr-cli version 1.0

**Comment by matheo** [comment]
Last night my package was Ok,
but today I installed `"@angular/platform-server": "^4.0.2"` and got this ERROR too.
`ng serve` runs fine, but build fails :(

**Comment by matheo** [comment]
```
npm update -D && npm update -S
```
did the trick, 4.02 out :D

**Comment by GBora** [comment]
@matheo  I'm having the exact same issue but running the commands which you provided doesn't help at all, the error remains the same.

Did you by any chance do anything extra ?

**Comment by mgm87** [comment]
I also needed to make sure that the "@angular/compiler-cli" vrsion matched the @angular version. In my case the version was upgraded to "^4.0.2"

**Comment by LimarenkoDenis** [comment]
I also have this issue, but then I re-save project in the editor, and 'ng serve' automatically re-compile again and the error disappears, but it is still strange

**Comment by mgm87** [comment]
My project has started doing this as well. At least it runs but I am concerned about automatic builds not working.

**Comment by filipesilva** [comment]
Seems like this was a dependency problem. Thanks for everyone that helped out!

**Comment by yesroh** [comment]
I have the same problem 

![image](https://cloud.githubusercontent.com/assets/7999914/26583785/f0684184-451c-11e7-878d-3e3f27284f7a.png)

My `package.json` is this:

```
{
  "name": "hello world",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/router": "3.4.8",
    "core-js": "^2.4.1",
    "rxjs": "5.1.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.7"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@angular/cli": "1.0.0-beta.32.3",
    "codelyzer": "~2.0.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.6.0",
    "protractor": "5.1.1",
    "ts-node": "2.1.0",
    "tslint": "4.4.2",
    "typescript": "2.1.6"
  }
}
```
my node and npm version is:
`node -v` : v7.9.0
 `npm -v` : 4.2.0

**Comment by wickedrahul** [comment]
install with save exact. remove '^' from all and then rm -Rf node_modules/
npm install. That might help

**Comment by bobbypulpel** [comment]
Thank you @matheo , it did solve my issue
