### ISSUE TITLE
Background image in SCSS not translated correctly for production builds

### ISSUE THREAD

**Issue by Mufasa** [angular/angular-cli#5942]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 7.9.0
os: darwin x64
@angular/animations: 4.0.2
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/platform-server: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2
```
macOS (Sierra v10.12.4)

### Repro steps.
I have a working site that was running on angular 2.4.10 and angular-cli 1.0.0-beta.26. I read all the change logs and upgrade guides today and managed to upgrade the site to angular 4.0.2 and angular-cli 1.0.0. However, I am experiencing a couple of issues, one of which is reported here.

My landing page has a background image that is specified within a components SCSS file as:
```
#banner {
  background: url("/assets/img/background.jpg") no-repeat center;
  background-size: cover;
  height: 700px;
  padding: 0;
  color: white;
}
```

When I run `ng build --prod --aot` and transfer the dist files to my production server then my site loads but this background image seems to be missing. On inspecting the page I noticed that the CLI has translated the **background** element to:
```
background: url(/assets/img/background.jpg) no-repeat 50%;
```
Notice that the double quotes around the **url** function parameter are missing and that **center** has been translated to **50%**.

If I run `ng serve` instead to test my site locally then I see this element getting translated correctly. However, in this case, none of my assets get loaded as the local build seems to have an issue with how it creates the assets in memory (I think). I added some comments to a related issue to describe this other failure here: https://github.com/angular/angular-cli/issues/5268

### The log given by the failure.
None

### Desired functionality.
SCSS **background** element should be translated to:
```
  background: url("/assets/img/background.jpg") no-repeat center;
```
as it did with angular-cli **v1.0.0-beta.26**.

**Comment by clydin** [comment]
The two background values are equivalents with the output version being shorter in length.  Quotes are optional and center is a keyword for 50%.

The root relative URL being used means that the CLI will not process the image and that it needs to be available on the server at that location.

**Comment by Mufasa** [comment]
The version without quotes and with 50% doesn't seem to work on Chrome browser (Version 57.0.2987.133 (64-bit)). The developer tools page inspector marks this CSS as invalid. If I edit it in the browser and add quotes and leave 50% as-is then it shows the image correctly.
MDN spec also documents this as having quotes around it.

**Comment by clydin** [comment]
MDN documentation ([see here](https://developer.mozilla.org/en-US/docs/Web/CSS/url)) says the following:
```
The URL may be unquoted, or quoted by single or double quotes.
```

**Comment by Mufasa** [comment]
Hmmm... OK I didn't look into the MDN docs deep enough - apologies.

But the fact is that without quotes it is no longer working in Chrome. What do I need to do in order to put quotes back in?

I tried editing the **main.**...**.bundle.js** file that get produced and adding the quotes in myself but that results in an error on the browser - something about a missing token. I use the Atom editor on a Mac.

**Comment by clydin** [comment]
No need to apologize.
Just tried all three browsers with an unquoted root relative URL without issue.  So not sure what's going on.  All css is minified in a production build, so you can't really put them back in unless you do it manually.

However, I would recommend allowing the CLI to process the asset by using a relative URL (build time relative).  The asset will be hashed/copied or inlined if small enough.  In the future, assets may also be further processed (e.g., image file size optimization passes).

**Comment by Mufasa** [comment]
Aha! Found the issue. My actual background image name has a space in it and it seems if an image name has a space in it then it must be quoted. If I use another mage that has no spaces in it then all works as expected.
Would this be considered a bug in the CLI? (i.e. should it leave the quotes in if the image name has spaces in it).

**Comment by clydin** [comment]
URL's that require escaping should either be escaped or have quotes added (or kept); whichever is shorter in character length.  So yes, this appears to be an issue with the CSS minification.

**Comment by clydin** [comment]
Would you mind running 'npm ls cssnano' and 'npm ls postcss-normalize-url' within your project?

**Comment by Mufasa** [comment]
`npm ls cssnano` gives:
```
go2travel-ng-cli@0.0.0 /Users/anjum/Documents/workspace/go2travel-ng-cli
├─┬ @angular/cli@1.0.0
│ └── cssnano@3.10.0 
├── UNMET PEER DEPENDENCY @angular/common@4.0.2
├── UNMET PEER DEPENDENCY @angular/core@4.0.2
├── UNMET PEER DEPENDENCY @angular/http@4.0.2
└── UNMET PEER DEPENDENCY tslint@5.1.0

npm ERR! peer dep missing: @angular/common@^2.3.0, required by md2@0.0.17-2
npm ERR! peer dep missing: @angular/core@^2.3.0, required by md2@0.0.17-2
npm ERR! peer dep missing: @angular/http@^2.3.0, required by md2@0.0.17-2
npm ERR! peer dep missing: tslint@^4.0.0, required by codelyzer@2.1.1
```

`npm ls postcss-normalize-url` gives:
```
go2travel-ng-cli@0.0.0 /Users/anjum/Documents/workspace/go2travel-ng-cli
├─┬ @angular/cli@1.0.0
│ └─┬ cssnano@3.10.0
│   └── postcss-normalize-url@3.0.8 
├── UNMET PEER DEPENDENCY @angular/common@4.0.2
├── UNMET PEER DEPENDENCY @angular/core@4.0.2
├── UNMET PEER DEPENDENCY @angular/http@4.0.2
└── UNMET PEER DEPENDENCY tslint@5.1.0

npm ERR! peer dep missing: @angular/common@^2.3.0, required by md2@0.0.17-2
npm ERR! peer dep missing: @angular/core@^2.3.0, required by md2@0.0.17-2
npm ERR! peer dep missing: @angular/http@^2.3.0, required by md2@0.0.17-2
npm ERR! peer dep missing: tslint@^4.0.0, required by codelyzer@2.1.1
```

**Comment by clydin** [comment]
Thanks.  Just wanted to check if the latest versions were being used and it looks like it.

I submitted a PR to use a safer set of stylesheet minification settings which should cover your issue.

**Comment by filipesilva** [comment]
@clydin's fix (thanks a bunch!) in https://github.com/angular/angular-cli/pull/5974 is now in, but I'll leave this open while `css-loader` doesn't update.
