### ISSUE TITLE
open other command rather than default browser

### ISSUE THREAD

**Issue by zh99998** [angular/angular-cli#5946]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
I see there is a --open switch to launcher default browser, it's great for debug convince, but could it be extended to another custom command (e.g. electron) rather than only browser?

extends could completable with current usage.
--open   // default browser
--open "npm run electron" // custom command

**Comment by filipesilva** [comment]
We're not looking at doing this, since we only officially support browser apps currently. There's some work being done to allow other browsers though, it could allow this as a side effect.
