### ISSUE TITLE
AotPlugin fails when combined with webpack's multi compiler

### ISSUE THREAD

**Issue by Torins** [angular/angular-cli#5947]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.0 (e)
node: 7.7.4
os: darwin x64
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
```

### Repro steps.
1. Create a new angular-cli project (ng new multi-test)
2. Eject a webpack config for AOT compilation (ng eject -prod --aot)
3. Install missing dependencies (npm install)
4. Edit the config, changing module.exports into an array of copies of the existing configuration, each with a different value in output.path ([example file](https://gist.github.com/Torins/4261480fcc51a8b0a50a141d62504178), changes compared to original in lines 21, 23, 51)
5. Try building (npm run build)

### The log given by the failure.
```
 ERROR in ./src/$$_gendir/app/app.module.ngfactory.ts
    Module not found: Error: Can't resolve '@angular/core/core' in '/Users/daniel/Documents/multi-test/src/$$_gendir/app'
     @ ./src/$$_gendir/app/app.module.ngfactory.ts 17:0-46
     @ ./src/main.ts
     @ multi ./src/main.ts
    
    ERROR in ./src/$$_gendir/app/app.component.ngfactory.ts
    Module not found: Error: Can't resolve '@angular/core/core' in '/Users/daniel/Documents/multi-test/src/$$_gendir/app'
     @ ./src/$$_gendir/app/app.component.ngfactory.ts 8:0-46
     @ ./src/$$_gendir/app/app.module.ngfactory.ts
     @ ./src/main.ts
     @ multi ./src/main.ts
```
In the case of my example config file, the first two configs ("pl" and "en") fail due to the above errors, while the last one succeeds and only dist/es is created.

### Desired functionality.
I want to build my app for all the languages I have a translation for, leveraging webpack's multi compiler for simultaneous building and the fact that the config is a js file to generate as many config objects in an array as I have xlf files with translations.

### Mention any other details that might be useful.
Everything works fine as long as I export an array of one config. As soon as more are added, all but the last one fail. 
As far as I can see it's something about the AotPlugin, because with skipCodeGeneration set to true, the errors stop appearing and everything compiles fine.

The workaround I have for now is to call webpack separately for each language, as showcased [here](https://medium.com/@feloy/deploying-an-i18n-angular-app-with-angular-cli-fc788f17e358).

Thanks in advance for any help on this one.

**Comment by ranstyr** [comment]
@Torins, I followed your "Repro steps" and everything is working properly. Could you please retry it and update on the result?

#goodnessSquad

**Comment by Torins** [comment]
I've re-did exactly my reproduction steps and I still get an error.
Assuming you've used my example file: 
Did you get all three subfolders (en, pl, es)?
Did you scroll up for the errors?

Using the multicompiler, my config runs three builds in parallel, which in turn means three "entire" outputs. As I've mentioned, the last build always succeeds, which may lead onto a false sense of the entire config to run properly. 

[Here](https://gist.github.com/Torins/1be1ac84d086aae324630db297a23f92) is the entire output I've got from a fresh attempt. The result was that only the "es" folder got created, instead of all three

**Comment by Reuvenc** [comment]
Having the exact same issue. Tried to execute two builds using webpack's multi compiler, and only the last succeeds.
In order to be sure that the issue is AotPlugin related, I didn't use the plugin in the first build, and seems that both builds succeeded in this case. Both build configurations are completely the same, except the output paths.

The error message I'm getting is huge. Basically this is the error, and it repeats for each resource that imports @angular/core:
```
ERROR in ./app-www/client/dist/www/modules/app/app.module.browser.ngfactory.ts
Module not found: Error: Can't resolve '@angular/core/core' in '/Users/chacha/ironbuzz/git_wa/waterfall/app-www/client/dist/www/modules/app'
resolve '@angular/core/core' in '/Users/chacha/ironbuzz/git_wa/waterfall/app-www/client/dist/www/modules/app'
  Parsed request is a module
  using description file: /Users/chacha/ironbuzz/git_wa/waterfall/package.json (relative path: ./app-www/client/dist/www/modules/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/chacha/ironbuzz/git_wa/waterfall/package.json (relative path: ./app-www/client/dist/www/modules/app)
    resolve as module
      looking for modules in /Users/chacha/ironbuzz/git_wa/waterfall
        using description file: /Users/chacha/ironbuzz/git_wa/waterfall/package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/chacha/ironbuzz/git_wa/waterfall/package.json (relative path: .)
          using description file: /Users/chacha/ironbuzz/git_wa/waterfall/package.json (relative path: ./@angular/core/core)
            as directory
              /Users/chacha/ironbuzz/git_wa/waterfall/@angular/core/core doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chacha/ironbuzz/git_wa/waterfall/@angular/core/core doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chacha/ironbuzz/git_wa/waterfall/@angular/core/core.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chacha/ironbuzz/git_wa/waterfall/@angular/core/core.js doesn't exist
      looking for modules in /Users/chacha/ironbuzz/git_wa/waterfall/node_modules
        using description file: /Users/chacha/ironbuzz/git_wa/waterfall/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/chacha/ironbuzz/git_wa/waterfall/package.json (relative path: ./node_modules)
          using description file: /Users/chacha/ironbuzz/git_wa/waterfall/node_modules/@angular/core/package.json (relative path: ./core)
            as directory
              /Users/chacha/ironbuzz/git_wa/waterfall/node_modules/@angular/core/core doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chacha/ironbuzz/git_wa/waterfall/node_modules/@angular/core/core doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chacha/ironbuzz/git_wa/waterfall/node_modules/@angular/core/core.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chacha/ironbuzz/git_wa/waterfall/node_modules/@angular/core/core.js doesn't exist
[/Users/chacha/ironbuzz/git_wa/waterfall/@angular/core/core]
[/Users/chacha/ironbuzz/git_wa/waterfall/@angular/core/core]
[/Users/chacha/ironbuzz/git_wa/waterfall/@angular/core/core.ts]
[/Users/chacha/ironbuzz/git_wa/waterfall/@angular/core/core.js]
[/Users/chacha/ironbuzz/git_wa/waterfall/node_modules/@angular/core/core]
[/Users/chacha/ironbuzz/git_wa/waterfall/node_modules/@angular/core/core]
[/Users/chacha/ironbuzz/git_wa/waterfall/node_modules/@angular/core/core.ts]
[/Users/chacha/ironbuzz/git_wa/waterfall/node_modules/@angular/core/core.js]
 @ ./app-www/client/dist/www/modules/app/app.module.browser.ngfactory.ts 17:0-46
 @ ./app-www/client/dist/main.ts
```

**Comment by filipesilva** [comment]
I don't think `@ngtools/webpack` supports multi compiler at all, but @hansl can answer this better.

**Comment by luchillo17** [comment]
@filipesilva Really? i've been using it with a multi, first one deals with Angular 2 code, and second one with an `Electron` `main.ts` file and it works just fine.

**Comment by hansl** [comment]
It's not in our scope to support this setup. You can run web pack twice. If this works, then great, but it was never intended to be run in the same process/memory with another build. Please note that in the past we did have global state, we got rid of most (if not all, can't double check right now) of it, so this might be fixed.

Regardless, this is out of our support scope.
