### ISSUE TITLE
specify the `setup` option for webpack-dev-server in `serve` command

### ISSUE THREAD

**Issue by royling** [angular/angular-cli#5948]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

able to specify the `setup` option for webpack-dev-server in `serve` command, similar to `--proxy-config` option.

### Mention any other details that might be useful.

for the setup option of webpack-dev-server, refer to https://webpack.js.org/configuration/dev-server/#devserver-setup

**Comment by royling** [comment]
not sure if this follows the design principle of `@angular/cli`...
if this is acceptable, I can submit a PR.

**Comment by franktroia** [comment]
I would also find this very useful

**Comment by filipesilva** [comment]
This isn't something we're looking at doing for 1.x. It's a great candidate for the addon system coming in 2+ though.

**Comment by tBlabs** [comment]
+1
