### ISSUE TITLE
Problem to run Build Angular in Apache Server

### ISSUE THREAD

**Issue by AhmedHadjTaieb** [angular/angular-cli#5952]
### Bug Report
I turn my build angular project (with Webpack) in server apache local in the mac OS Sierra, and I found a problem with resource file in index.html but when I turn the same build in Ubuntu project run correctly with no error.

I try this build with two methods in the first method I run the build project on server MAMP Pro and the result is:
![capture d ecran 2017-04-13 a 14 14 231](https://cloud.githubusercontent.com/assets/22799068/25006916/9c67079a-2056-11e7-81c3-dc86a9db1768.JPG)

and in the second method I run the build project in the default server Apache on mac OS Sierra 10.12.4 and the result is:
![capture d ecran 2017-04-13 a 14 12 581_1](https://cloud.githubusercontent.com/assets/22799068/25006924/a06e5622-2056-11e7-97d6-d87abf8aebb9.JPG)

When I run the same build project in Ubuntu 16.04 LTS the result is :
![screenshot from 2017-04-13 06-19-04](https://cloud.githubusercontent.com/assets/22799068/25006942/a7ca8648-2056-11e7-96ab-4140012025cc.jpg)

### Versions:

First System: MacOS Sierra 10.12.4
MAMP PRO V3.5.2 
Second System: Ubuntu 16.04 LTS

Angular: 2.4.8
Angular CLI: 1.0.0-rc.0
webpack: 2.2.1

**Comment by RicardoVaranda** [comment]
Seems like you aren't defining the base-href when you are building your dist folder,

Could you try build it with: 
```
ng build --prod --base-href=/dist/
```

**Comment by AhmedHadjTaieb** [comment]
@RicardoVaranda 
I can't build with ng , I used ng eject to change project into Webpack and I run Build with npm run Build.
But my problem is why apache in ubuntu turn build project correctly and in macOS not.

**Comment by RicardoVaranda** [comment]
You can change it manually in your index.html, there should be a `<base href="/">`

**Comment by AhmedHadjTaieb** [comment]
@RicardoVaranda 
I don't think the problem in the link path because I run the build with two methods in apache with macOS and with MAMP PRO(Read the report), but also I try your solution and I found the same problem in result.
![capture d ecran 2017-04-14 a 10 40 53](https://cloud.githubusercontent.com/assets/22799068/25040710/020ba022-2103-11e7-9bd8-76d8300b7124.jpg)

Do you think it's problem in Apache server or in base path build ???

**Comment by RicardoVaranda** [comment]
@AhmedHadjTaieb Go to the following url:

http://localhost/~AhmedHt/dist/inline.bundle.js

Your base url is anything that is after the server url in your case localhost.

**Comment by AhmedHadjTaieb** [comment]
@RicardoVaranda 

url: http://localhost/~AhmedHt/dist/inline.bundle.js
result:
![capture d ecran 2017-04-14 a 11 23 24](https://cloud.githubusercontent.com/assets/22799068/25041032/f5f5f452-2104-11e7-8e04-25dfbefba5cb.jpg)

But the Status of loading files in browser 403, it's problem of Apache server ?????

![capture d ecran 2017-04-14 a 11 23 12](https://cloud.githubusercontent.com/assets/22799068/25041073/354bc528-2105-11e7-8f57-fe40877ffae1.jpg)

**Comment by RicardoVaranda** [comment]
@AhmedHadjTaieb Did you change your base url to match /~AhmedHt/dist/ ?

403 is a forbidden error, check what permissions you have on the files inside of that directory. If you need help figuring out what permissions you should have take a look at this: https://serverfault.com/a/357109

**Comment by AhmedHadjTaieb** [comment]
Problem Solved with this link:
https://medium.com/@JohnFoderaro/how-to-set-up-apache-in-macos-sierra-10-12-bca5a5dfffba
