### ISSUE TITLE
ng-xi18n should trim messages

### ISSUE THREAD

**Issue by DIDoS** [angular/angular-cli#5954]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

4.2.0 Windows 10

### Repro steps.

create a component with two i18n enabled tags like this:

```
<h1 i18n>test</h1>
<h1 i18n>    
    test    
</h1> 
```
run extract (i18n:extract)
### The log given by the failure.

The second message is extracted with leading newline and whitespaces.

### Desired functionality.

Left and right trim newlines and spaces from i18n messages in tags.

### Mention any other details that might be useful.

I don't see a reason to preserve leading and trailing newlines and whitespaces. They change the hash ids and are confusing during the translation process. Sometimes newlines are added because of style guides (max cols) when another tag is added - this should anyway not change the hash id nor the message.

**Comment by filipesilva** [comment]
I think this is actually a feature request to the base extract functionality, you should open it in https://github.com/angular/angular instead.
