### ISSUE TITLE
Error when trying to create application with name containing npmscope in part of name

### ISSUE THREAD

**Issue by phillipgreenii** [angular/angular-cli#5957]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.9.1
os: win32 x64

### Repro steps.
ng new @my-company/core --prefix my  --skip-git

### The log given by the failure.
Project name "@my-company/core" is not valid. New project names must start with a letter, and must contain only alphanumeric characters or dashes. When adding a dash the segment after the dash must also start with a letter.
@my-company/core

### Desired functionality.
Project to be created with project name of @my-company/core (ie, project core under scope of @my-company)

**Comment by filipesilva** [comment]
Part of `ng new` is creating a folder, and that folder name is not valid. You can just create the `@my-company` folder manually, and inside it do `ng new core`. You'd have to change `package.json` to reflect the scope as well.
