### ISSUE TITLE
Change semver from tilde to caret for dependencies

### ISSUE THREAD

**Issue by ishitatsuyuki** [angular/angular-cli#5959]
Currently the blueprint has many occurrences of `~`(tilde). This prevents seamless upgrades of minor versions.

As far as I [know](https://nodesource.com/blog/semver-tilde-and-caret/), it's quite safe to use `^` (caret). Is there any history for this semver usage, or it's just too old and not updated?

Since upgrading blueprints is a annoying work, let's minimize the effort to change them.

**Comment by clydin** [comment]
It is safe if the package follows semver and doesn't introduce breaking changes in patch or minor versions.  The versioning strategy was chosen to emphasize safety and minimize breakage.

If someone is comfortable with the increased risk potential, they can always adjust the versioning for their individual project.  In general, as a project grows and ages, the packages and their required versions will become more specific to the project regardless.

**Comment by filipesilva** [comment]
To be honest even `~` has proved problematic in many occasions. This isn't something that we're looking to relax.
