### ISSUE TITLE
[Enhancement] Progress bar on ng new {project_name} after "Installing packages for tooling via npm."

### ISSUE THREAD

**Issue by pumano** [angular/angular-cli#5960]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.9.1
npm: 4.0.2
os: Windows 10 x64

### Repro steps.

ng new {projectname}

### Desired functionality.
What would like to see implemented?

Please add progress bar when new project created via "ng new {project_name} " after "Installing packages for tooling via npm."

What is the usecase?

Possibility to see progress bar as it provided by NPM / Yarn itself

**Comment by filipesilva** [comment]
I can see this being nice especially with slower connections.

**Comment by narainsagar** [comment]
@filipesilva I would like to give it a shot.

**Comment by filipesilva** [comment]
@narainsagar go for it 👍 

Bear in mind this might be especially hard given that different versions of npm display progress in different ways, and so does yarn. I don't even know how other package managers deal with it. 

This isn't something we'd like to add if it's a massive undertaking though, so if you see it's non-trivial just let us know.

**Comment by narainsagar** [comment]
@filipesilva Thanks. Yeah sure - will let you guys know here. Since I also don't know much about how all package managers are exactly doing this.. So will study and share my findings here. Thanks for your positive response 👍
