### ISSUE TITLE
Less verbose build output for dumb terminals (like Jenkins)

### ISSUE THREAD

**Issue by leonboot** [angular/angular-cli#5962]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

```
@angular/cli: 1.0.0
node: 6.9.5
os: linux x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/compiler-cli: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/platform-server: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
```

### Repro steps.

Perform a regular production build:
```shell
$ ng build --prod
```

### The log given by the failure.

We're using Jenkins to perform automated builds of our Angular project, so we can catch errors that only occur during compilation early on in the development process. The output of the `ng` command is very verbose, however. Especially for 'dumb terminals', like the Jenkins console output log. I have to plough through 900+ of lines like `building modules 534/781 modules 247 active ...node_modules/rxjs/util/errorObject.js` first before getting to the first compilation error.

### Desired functionality.

It would be really nice if there was some sort of `--quiet` or `--no-ansi` flag for the `ng` command. Specifying that flag during build would result in something like `Building 900 modules...` instead of 900 lines of `building modules nnn/900 modules nnn active ...node_modules/module/src/some_file.js`.

**Comment by clydin** [comment]
There is the '--no-progress' option.  This should reduce the amount of text significantly.

**Comment by leonboot** [comment]
@clydin That'll do! I've added it to build command and there's a lot less clutter now. It makes the build log a heck of a lot easier to read. Thanks!

**Comment by rferrerasm** [comment]
It would be nice to have a `--silent` or `--quiet` option for build scripts that suppresses _all_ the chatter.

**Comment by filipesilva** [comment]
Closing as answered by @clydin, cheers! 

@rferrerasm I think `--no-progress` covers most of the need for a `--silent` flag. We try to keep most output brief. Can you open a new issue if you have some usecases where it's still inconvenient?
