### ISSUE TITLE
ng serve also serves stuff not marked as asset

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular-cli#5966]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.10.1
os: win32 x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/platform-server: 4.0.0
@angular/router: 4.0.0
@angular/service-worker: 1.0.0-beta.8
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Repro steps.

Clone the [Angular Repo](https://github.com/angular/angular).

Go to the `aio/` folder, then run:

```
$ yarn
$ yarn boilerplate:add
```

The latter command is going to create a new `node_modules` inside `tools/examples/shared` folder and create a symlink in around 50 examples inside `content/examples`.

Now if you do a `ng serve` it will take a while before webpack kicks in. And when it does, you can for example go to:

http://localhost:4200/content/examples/animations/src/main.ts

And that will try to download the file for you and it should not be served.

Another example:

http://localhost:4200/tools/examples/shared/package.json

Both those `tools` and `content` folders are outside `src` and not marked as assets.

### Desired functionality.

they should not be served.

**Comment by clydin** [comment]
This should be fixed via https://github.com/angular/angular-cli/commit/1bc174b0decb291baa1d7043e2bae87158783482

**Comment by filipesilva** [comment]
Closing as per @clydin's already merged fixed.
