### ISSUE TITLE
3rd party library fails - #2141 has returned...

### ISSUE THREAD

**Issue by MHacker9404** [angular/angular-cli#5969]
- [x ] bug report -> please search issues before submitting

Output from: `ng --version`.  cli version 1.0.0, node: 7.8.0 win32 x64

created new angular-cli app.
Tried every combination of fix suggested, but the end result is:
__WEBPACK_IMPORTED_MODULE_1_jquery__.delay is not a function.

How hard can it be to import a library?

**Comment by cenkentimist** [comment]
Hard. Have you tried the following?
`npm install --save jquery`
`npm install --save @types/jquery`
`import "jquery"`
To get bootstrap working I had to add `"../node_modules/jquery"` to the scripts array in .angular-cli.json this should not be necessary in your case.

**Comment by MHacker9404** [comment]
I’m pretty sure that I have.  But I’ll try that specific scenario again here in about 30-45 minutes.

**Comment by MHacker9404** [comment]
Here’s what I’ve accomplished so far:

  1.  Brand new CLI project from scratch
  2.  npm i jquery and @types/jquery
  3.  import ‘jquery’ in component
  4.  add “$.delay(5000);” to component – causes build error
  5.  Added JQueryStatic interface with delay method to src/typings.d.ts
  6.  App builds, but get ReferenceError: $ is not defined at run-time
  7.  Add “declare var $: any” after import statements to component
  8.  Still get same error as 6

**Comment by MHacker9404** [comment]
Changing “import ‘jquery’;” to “import * as $ from 'jquery';” gives a different run-time error:
ERROR TypeError: __WEBPACK_IMPORTED_MODULE_1_jquery__.delay is not a function

Which I think is caused by how the default webpack.config used by angular-cli is loading the jquery.

**Comment by cenkentimist** [comment]
short version:
$.delay is not a static jquery method. 
see https://api.jquery.com/delay/ 

installing @types/jquery should be sufficient to get the type. $.delay is a build error because $.delay is defined on the jquery type it's for animations as I understand it. so $("#myid").delay exists but $.delay doesn't. according to the doc the typings in @types/jquery are correct https://api.jquery.com/delay/

**Comment by MHacker9404** [comment]
Thank you so much for putting up with my bone-headedness.  Those 7 words were the only answer that I have so far to help me:
$('app-root').delay(5000);  <-- works like a charm
