### ISSUE TITLE
Generating code from blueprint on existing components does not overwrite files.

### ISSUE THREAD

**Issue by gopinav** [angular/angular-cli#5970]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting

```

### Versions.
Output from: `@angular/cli: 1.0.0-rc.1`.
  Windows 10

### Repro steps.

1) `ng new demoApp`
2) `cd demoApp`
3) `ng generate component test`
4) Edit test.component.html or css or ts file.
5) Run `ng generate component test` again.
6) Type 'y' or 'n' when asked to overwrite. 

No changes in the html, css, ts file of the test.component in either case.

### Desired functionality.
The files should be overwritten with blueprint code if 'y' is typed.
If there is a need to regenerate the component without having to individually clean up the files

**Comment by Tallyb** [comment]
@1.3.0-rc5 work as expected with n and y.

**Comment by clydin** [comment]
Closing as version `1.0.0-rc.1` is a prerelease version and no longer supported.  If the problem persists within the latest stable version (currently 6.2.3), please open a new issue detailing the problem.
