### ISSUE TITLE
angular-cli app build and serve error for factory function

### ISSUE THREAD

**Issue by ansuman273** [angular/angular-cli#5971]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

![ng-version](https://cloud.githubusercontent.com/assets/4735068/25061345/c551e270-21d1-11e7-972d-ceea26781fd5.PNG)

### Repro steps.

ng serve , ng build
Here is a sample snippet of the auth.module , I added for having token in header globally for each request for authentication process.
![global auth module](https://cloud.githubusercontent.com/assets/4735068/25061395/f93d9f10-21d2-11e7-9a4b-8abc5fe75a99.png)
And here I have Imported it to the app.module too.
![app module](https://cloud.githubusercontent.com/assets/4735068/25061430/ee20d7d6-21d3-11e7-9232-2dd6b946015a.png)

### The log given by the failure.

Error on Build
![error on build](https://cloud.githubusercontent.com/assets/4735068/25061440/221a649e-21d4-11e7-9a18-784610082f7e.PNG)
Error on ng serve (after changing any file by putting a space and saving the auto compile of webpack works though and application accessible on http://localhost:4200)

### Desired functionality.

Make auth.module work fine with RequestOptions (it has an exported class in the library )

### Mention any other details that might be useful.

Need to know about why it's failing at first but any change makes it work fine on auto recompile of webpack. I believe there is some issue with RequestOptions from @angular/http ( was working fine with angular 2 system.js though). Stuck in midway need a fix.

**Comment by ansuman273** [comment]
Here is a snapshot of project working after auto recompile
![ng serve fails on first but modifying any file and then saving makes the webpack work fine](https://cloud.githubusercontent.com/assets/4735068/25061490/7d8fb724-21d5-11e7-9543-0ba1fd9673a6.PNG)

**Comment by clydin** [comment]
Position 5:10 appears to be the factory function itself not RequestOptions.  Factory functions are required to be exported.
For reference, here is the Http module's setup code: https://github.com/angular/angular/blob/master/packages/http/src/http_module.ts

**Comment by ansuman273** [comment]
**@clydin I have tried that and exported it but it throwing new error now and it's quite popular with the new angular-cli i believe .**

Similar to this issue
[](https://github.com/angular/angular-cli/issues/3707)

![err](https://cloud.githubusercontent.com/assets/4735068/25063744/79c077fc-220a-11e7-8662-6bc82a1c2706.PNG)

**Comment by ansuman273** [comment]
Some how we are now able to build with  **ng build --watch** (for development) and **ng build -env=prod --watch** (for production), it fails at first but then a small change like putting a space does recompiling of build process(--watch) which passes somehow and the dist is generated and works fine with my express server in the back end.

**Comment by filipesilva** [comment]
Heya, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

The CLI always runs statical analysis on code to ensure it will run when compiled with AOT. This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

Good resource on how to to debug these errors are https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60 and  https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts.

If your problem still persists, it might be a bug with the Angular Compiler itself. In that case, please open an issue in https://github.com/angular/angular.
