### ISSUE TITLE
angular-cli intall error

### ISSUE THREAD

**Issue by Caibiy** [angular/angular-cli#5972]
how to fix this issue

![image](https://cloud.githubusercontent.com/assets/16449809/25061604/e9242152-21ec-11e7-9ce9-0ec7f67af139.png)

**Comment by hofa77** [comment]
I think you should use **@angular/cli** instead of @angular-cli
with the latest version of node and npm

**Comment by Caibiy** [comment]
![xq3 whyb 3 i s4s6ug a2](https://cloud.githubusercontent.com/assets/16449809/25062610/ce88322e-2201-11e7-8148-698a618f3bb8.png)

**Comment by Caibiy** [comment]
thank you very much  but not working...

**Comment by clydin** [comment]
As per the Readme, node 6.9.0 or higher is required.

**Comment by hofa77** [comment]
upgrade the node.js , download from website
install npm again 
then make this 3 steps to uninstall and install with the latest version of angular

npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@latest

**Comment by filipesilva** [comment]
Closing as answered, thanks @hofa77 and @clydin!
