### ISSUE TITLE
angular-cli installation fails

### ISSUE THREAD

**Issue by debender495** [angular/angular-cli#5977]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### The log given by the failure.

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData @angular/cli
8 silly fetchNamedPackageData @angular/cli
9 silly mapToRegistry name @angular/cli
10 silly mapToRegistry scope (from package name) @angular
11 verbose mapToRegistry no registry URL found in name for scope @angular
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@angular/cli',
14 silly mapToRegistry   scope: '@angular',
14 silly mapToRegistry   escapedName: '@angular%2fcli',
14 silly mapToRegistry   name: '@angular/cli',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/@angular%2fcli
16 verbose request uri https://registry.npmjs.org/@angular%2fcli
17 verbose request no auth needed
18 info attempt registry request try #1 at 11:44:43
19 verbose request id 08ae7c97317c9fbb
20 http request GET https://registry.npmjs.org/@angular%2fcli
21 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.36.162:443
22 info attempt registry request try #2 at 11:45:15
23 http request GET https://registry.npmjs.org/@angular%2fcli
24 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.36.162:443
25 info attempt registry request try #3 at 11:46:36
26 http request GET https://registry.npmjs.org/@angular%2fcli
27 silly fetchPackageMetaData Error: connect ETIMEDOUT 151.101.36.162:443
27 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1050:11)
27 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1073:20)
27 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
27 silly fetchPackageMetaData  error for @angular/cli { Error: connect ETIMEDOUT 151.101.36.162:443
27 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1050:11)
27 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1073:20)
27 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
27 silly fetchPackageMetaData   code: 'ETIMEDOUT',
27 silly fetchPackageMetaData   errno: 'ETIMEDOUT',
27 silly fetchPackageMetaData   syscall: 'connect',
27 silly fetchPackageMetaData   address: '151.101.36.162',
27 silly fetchPackageMetaData   port: 443 }
28 silly rollbackFailedOptional Starting
29 verbose stack TypeError: Cannot read property 'path' of null
29 verbose stack     at Installer.rollbackFailedOptional (D:\nodejs\node_modules\npm\lib\install.js:511:29)
29 verbose stack     at Array.<anonymous> (D:\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
29 verbose stack     at LOOP (D:\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
29 verbose stack     at D:\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
29 verbose stack     at D:\nodejs\node_modules\npm\lib\install.js:337:5
29 verbose stack     at Array.<anonymous> (D:\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
29 verbose stack     at LOOP (D:\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
29 verbose stack     at chain (D:\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
29 verbose stack     at D:\nodejs\node_modules\npm\lib\install.js:294:5
29 verbose stack     at D:\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
30 verbose cwd D:\Angular
31 error Windows_NT 6.1.7601
32 error argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
33 error node v7.9.0
34 error npm  v4.2.0
35 error Cannot read property 'path' of null
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by AmalinJustBreathe** [comment]
Hi @debender495, Is that a bug report or a feature request ?
If it is a bug -> please change the [x] mark at the top of the issue and add Repro steps.
If it is a feature request -> please explain the desired functionality.
#goodnessSquad

**Comment by filipesilva** [comment]
From your log, it seems like your connection went down midway. If you try again it should be fine.
