### ISSUE TITLE
AoT lambda error with `skipCodeGeneration`: true

### ISSUE THREAD

**Issue by tycho01** [angular/angular-cli#5985]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report

### Versions.
```
ng --version
@angular/cli: local (v1.0.0, branch: master) (e)
node: 7.7.3
os: linux x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

OS:
Ubuntu 17.04 zesty
```

### Repro steps.

I'd like to use lambdas before Angular bootstraps. Under AoT (the default in `angular-cli`), this errors with the following, as currently expected:
```
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
```

At this point, I'd also used `ng eject`, so as to enable support for [Pug](https://github.com/angular/angular-cli/issues/1886#issuecomment-282193172). At this point I looked for a way to disable AoT to work around the error, then found that [ejection should disable AoT](https://github.com/angular/angular-cli/issues/5393) by default. Oddly enough, even with the default `AotPlugin`'s `"skipCodeGeneration": true`, I'm still getting the above error on `npm start`.

**Comment by deebloo** [comment]
@tycho01 can you post the code that is causing this error

**Comment by clydin** [comment]
Something to note as well is that a static analysis pass is performed regardless of the use of AOT to provide support for lazy loading.

**Comment by tycho01** [comment]
@clydin Thanks, that's somewhat enlightening here. I knew the error comes from the [`StaticReflector`](https://github.com/angular/angular/blob/86396a43e9a8bea335f77af1301772b72d0444a2/packages/compiler/src/aot/static_reflector.ts) class, though I haven't really found static analysis calls in that [`AotPlugin`](https://github.com/angular/angular-cli/blob/204d3126c66144069d97106d64d5d2638797e064/packages/%40ngtools/webpack/src/plugin.ts) myself. At this point I'd wonder if there'd be any alternative to this. I never used lazy routing before myself. Might it be possible to sacrifice that functionality in order to skip the static pass and trade it in for lambdas again?

I'll try to make a minimum repro.

**Comment by tycho01** [comment]
Minimum repro: [this](https://github.com/tycho01/ng-cli-lambda-error/commit/9944c1f86454d19b09fd0fa0569f8389e1b9ef2e) suffices to have it throw the error after ejecting (no AoT). Interestingly, on the minimum repro `npm start` does successfully appear to run the server despite this error getting thrown (this hadn't appeared the case in my further edited version, though there were no other errors there, so presumably this had been what blocked it there.).

**Comment by tycho01** [comment]
Minimum repro: [this](https://github.com/tycho01/ng-cli-lambda-error/commit/9944c1f86454d19b09fd0fa0569f8389e1b9ef2e) suffices to have it throw the error after ejecting (no AoT).

Interestingly, on the minimum repro `npm start` does successfully appear to run the server despite this error getting thrown.
This hadn't appeared the case in my further edited version, though there were no other errors there, so presumably this had been what blocked it there.

**Comment by filipesilva** [comment]
There's no way to disable the static analysis that detect lazy routes, no. If you need a simpler setup that doesn't do that sort of stuff, I think you'd be better off with one of the TS-only webpack plugins instead. Should be a bit faster too.

**Comment by tycho01** [comment]
Thanks @filipesilva. I tried `angular2-template-loader` mentioned [here](https://github.com/angular/angular-cli/issues/5393#issuecomment-287259244), which helps work around the issue.

I would consider the decision to sacrifice lambdas in favor of lazy routes an opinionated one, and would have appreciated if both were supported / acknowledged in the docs.
Then again, it does appear the Angular team intends to add lambda support in AoT ([thread](https://github.com/angular/angular/issues/13138)), so I suppose long-term this should be a moot concern anyway...
