### ISSUE TITLE
css escape \a results in A

### ISSUE THREAD

**Issue by manuelfink** [angular/angular-cli#5992]
I'm having issues with the escaping of "\a" within the css.

```
br {
  content: " ";
}

br::after {
  content: "↵\a";
  white-space: pre;
  color: #6495ED;
}

```

`\a` gets escaped to a "A" and not stays \a. How can I escape \a within angular style sheets? Using the html escape code `&#xa;` does not work in css either

**Comment by AmalinJustBreathe** [comment]
Hi @manuelfink, the team requieres writing issues according to a template, which you can see when you click on the "New Issue" button. In order to get the team handle your issue, please edit it.
#goodnessSquad

**Comment by AmalinJustBreathe** [comment]
I have managed to reproduce the bug. 
This is a real issue.
