### ISSUE TITLE
SCRIPT1002: Syntax error after ng build --prod and run it on VM with IE10

### ISSUE THREAD

**Issue by estradamarkie** [angular/angular-cli#5993]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
node: 6.9.2
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.
I did `ng build --prod` on my local machine and copy the dist folder into my VM which has IE10, when trying to load the page console.log error says `SCRIPT1002: Syntax error `

I also enabled Polyfills for IE10, IE11
```
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
```

### The log given by the failure.

 `SCRIPT1002: Syntax error ` when loading the page on VM IE10
![image](https://cloud.githubusercontent.com/assets/17979376/25127190/f0585050-242c-11e7-8665-b369641676b7.png)

**Comment by estradamarkie** [comment]
Looks like it was my `base href="/appsrc/"` to `base href="/"` however nothing is being loaded just `loading...`

**Comment by estradamarkie** [comment]
Fixed my issue, just wrong base href!

**Comment by mingmLiang** [comment]
Can you talk to how to fixed?
