### ISSUE TITLE
@ngtools/webpack Lots of duplicate modules

### ISSUE THREAD

**Issue by unsafecode** [angular/angular-cli#5997]
### Bug Report or Feature Request
```
- [X] bug report
- [ ] feature request
```

### Versions.
node v.6.10.2
npm v.4.5.0
Windows 10 1703 build 15063.138

### Repro steps.
```javascript
// webpack.common.js
        new CommonsChunkPlugin({
            name: 'polyfills',
            chunks: ['polyfills']
        }),
        new CommonsChunkPlugin({
            name: 'vendor',
            chunks: ['main'],
            minChunks: module => /node_modules/.test(module.resource)
        }),
        new CommonsChunkPlugin({
            name: ['polyfills', 'vendor'].reverse()
        }),

//webpack.prod.js
    new AotPlugin({
      tsConfigPath: "./tsconfig.aot.json",
      typeChecking: false,
      entryModule: helpers.root("src/app/app.module#AppModule")
    }),
```

### The log given by the failure.
In the resulting bundles' stats I see many shared modules present in each lazy route chunk (so far 41!). The same **does not happen** when AoTPlugin is not present (dev build).

### Desired functionality.
Trying adding one more CommonChunkPlugin instance in the production configuration yields no effect. Additionally, in the past we used to have an "extras.aot.ts" file for AoT build to manually include (via `require.include`) to list all *hint* from Webpack Analyze tool that actually worked. In latest releases it seems not to have any effect anymore.

### Mention any other details that might be useful.
N/A

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Can you provide a repository with a simple repro where this happens? It's also worth mentioning that, if you're only using the AoTPlugin in production, then you're just not using the same build process in dev.

**Comment by josephliccini** [comment]
I am seeing my shared `@NgModules()` show up in both my lazy chunks and my eager chunks.  It definitely started happening after moving off of `angular2-load-children-loader` and into `@ngtools/webpack`.  I validated this with a `git bisect` and was able to find the commit that caused it.

Is there a setting to ensure that shared `@NgModules()` don't get placed into lazy and eager chunks?

**Comment by bfricka** [comment]
Same for me w/ ng5 + ngtools 1.9.8. Previously, I used a custom AoT w/ ngc + webpack, but the recent ng5+ changes to the compiler emit have led me to try this.

**Comment by josephliccini** [comment]
Let's see what happens here once webpack 4 merges into CLI.  I think that one will fix this any many other problems
