### ISSUE TITLE
AOT build doesn't work when I compile a module outside of my project

### ISSUE THREAD

**Issue by wKoza** [angular/angular-cli#5998]
Hi, I'm trying to migrate the ng-bootstrap test application to Angular CLI. Unfortunately, the AOT compilation does not work with `ng build --aot`. Here is my project : https://github.com/wKoza/ng-bootstrap/tree/migration_to_angular_cli/demo

However, when I run the command : `./node_modules/.bin/ngc -p src/tsconfig.app.json`, I can compile my code.

Is it possible to do this with the CLI ?

**Comment by cenkentimist** [comment]
are you getting the You have to be inside an Angular CLI project in order to use the build command.
error? because that's what it says on the tin. Angular CLI manages a number of things automatically. I would start a new project (ng new) and paste in code instead of trying to convert an old project wholesale. Perhaps someone else has a better idea though.

**Comment by wKoza** [comment]
Yes, `demo` is a new project (I have pasted the code  inside). This is the start of the log : 

> 10% building modules 6/10 modules 4 active ...ode_modules/style-loader/addStyles.jsTemplate parse warnings:
bootstrap/src/accordion/accordion.ts.NgbAccordion.html@2:4                                                                       Hash: c1bdb18bfd1b85b747e9                                                          Time: 45102ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 2.25 MB {3} [initial] [rendered]
chunk    {1} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 167 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 203 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 1.41 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
ERROR` in /Users/william/WebstormProjects/ng-bootstrap/demo/src/$$_gendir/src/accordion/accordion.ngfactory.ts (1,1): Cannot find module './accordion'.
/Users/william/WebstormProjects/ng-bootstrap/demo/src/$$_gendir/src/accordion/accordion.ngfactory.ts (1,1): Cannot find module './accordion-config'.
ERROR in /Users/william/WebstormProjects/ng-bootstrap/demo/src/$$_gendir/src/accordion/accordion.module.ngfactory.ts (1,1): Cannot find module './accordion.module'.

...

**Comment by cenkentimist** [comment]
@wKoza ok I see what happened. When you generate a component with `npm run ng generate component 'widget'` it automatically adds the import to the top of app.module.ts and the class to the declarations list in there. You pasted the classes in though so you need to add that manually.

**Comment by wKoza** [comment]
@cenkentimist, NgbdAccordion is imported by NgbdDemoModule. Without --aot , the project build without any problems, `ng serve`works also. You can checkout my project if you want to see in more detail.

**Comment by cenkentimist** [comment]
@wKoza Actually did try this. It didn't work at all for me. I don't have a global install of angular and that wasn't the error I got. The project is also missing the scripts generated by the default angular project. IE `npm run -- ng foo` and `npm start` did not work. what do you get from `ng --version`?

**Comment by wKoza** [comment]
> ng -v

>  @angular/cli: 1.0.0
node: 6.9.5
os: darwin x64
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2

The project is in the `demo`folder, on the branch `migration_to_angular_cli`of my repo

**Comment by kylecordes** [comment]
Same issue as #5986 ?

**Comment by wKoza** [comment]
Yes , it's possible @kylecordes .

**Comment by elclanrs** [comment]
I think this may be the same issue I reported here https://github.com/angular/angular-cli/issues/5990.

**Comment by valorkin** [comment]
@wKoza works fine for ngx-bootstrap, but I am linking lib src into modules

**Comment by wKoza** [comment]
yes @valorkin , with this strategy, it's work but it's not that I want to.

**Comment by mgechev** [comment]
@wKoza can you still reproduce this issue?

**Comment by wKoza** [comment]
Hi @mgechev, I don't think so. Angular CLI have grown since ;) We can close it.

**Comment by mgechev** [comment]
Thanks for the response!
