### ISSUE TITLE
i got an error while running angular cli by using "ng serve"-"You have to be inside an angular-cli project in order to use the serve command." But i am in the particular folder.

### ISSUE THREAD

**Issue by santhoshkumarch** [angular/angular-cli#5999]
i got an error while running angular cli by using "ng serve"-"You have to be inside an angular-cli project in order to use the serve command." But i am in the particular folder

**Comment by sumitarora** [comment]
@santhoshkumarch You should run the command inside Angular CLI project you created. Make sure you have `.angular-cli.json` file in the folder from which you are running the command.

**Comment by delasteve** [comment]
Based on the error message, it appears you are using an older version of the CLI. I would recommend upgrading to the latest version. 

```
npm uninstall -g angular-cli
npm cache clean
npm install -g @angular/cli
```

**Comment by cgosiak** [comment]
Thank you @delasteve ! You are an absolute gem!

I have run those identical commands a few times to try and resolve this issue; with the exception being that I have not done it with the -g flag. Rookie mistake I suppose.

**Comment by sumitarora** [comment]
Closing as above.

**Comment by ylcinyakup** [comment]
Finally it works :) Thank you @delasteve

**Comment by SunaliBandara** [comment]
npm install -g @angular/cli@latest
