### ISSUE TITLE
Implement addon hooks

### ISSUE THREAD

**Issue by rodyhaddad** [angular/angular-cli#6]
The [Angular2App](https://github.com/angular/angular-cli/blob/master/lib/broccoli/angular2-app.js) should implement the [Addon Hooks of ember-cli](https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md)

The only hook that doesn't make sense for now is `config`, as Angular2 applications don't have configuration settings.

Let's use this issue to track our progress, but open up a new issue for each hook we intend to implement now and work on.

**Comment by hansl** [comment]
Same as #7, third party installation will include hooks.

**Comment by chandan4028** [comment]
how to show no records found in angular 6
