### ISSUE TITLE
Install additional packages / task runner

### ISSUE THREAD

**Issue by doczoidberg** [angular/angular-cli#60]
What do I have to do to install for example bootstrap and put it (automatically) into the dist folder?

The project doesn't use a task runner as gulp or grunt? It uses it's own type of taskrunner (ember-cli)?
Is it possible (recommended) to use gulp with this project?

**Comment by doczoidberg** [comment]
I installed different packages via npm and via jspm. How can I use them in my project?

**Comment by Peekmo** [comment]
Hey @doczoidberg did you find a way or a doc about that problem ?

Thank you,
Peekmo

**Comment by doczoidberg** [comment]
I copied them in my dist folder. You can look here for a more clean solution:

https://github.com/angular/angular-cli/pull/62

**Comment by Peekmo** [comment]
Thank you :+1:

**Comment by IgorMinar** [comment]
The 3rd party packages story is pretty weak right now, but I understand that this is a must.

ember-cli solves this in various ways. I want to avoid wrapper packages for existing packages that provide metadata or integration with the cli. I'd rather use package.json as the source of truth.

**Comment by IgorMinar** [comment]
Integrating grunt or gulp into the current setup doesn't make sense. The whole point of broccoli build pipeline is that the build pipeline is unified, but flexible enough that addons can plug into it.

**Comment by intellix** [comment]
Achieved this will the following ember-cli-build.js:

```js
/* global require, module */

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');
var Funnel = require('broccoli-funnel');
var mergeTrees = require('broccoli-merge-trees');

module.exports = function(defaults) {
    var app = new Angular2App(defaults);

    var myTree = new Funnel('node_modules', {
        files: [
            'bootstrap/dist/css/bootstrap.css'
        ],
        destDir: 'vendor'
    });
    var appTree = app.toTree();
    return mergeTrees([myTree, appTree], { overwrite: true });
}
```

Now I just need to figure out how to inject my other build processes in there, like SASS compilation

**Comment by DaNautilus** [comment]
@intellix Thanks for this workaround
