### ISSUE TITLE
Deduped during npm install

### ISSUE THREAD

**Issue by gtzinos** [angular/angular-cli#6000]
Hello,

Please check this screenshot: http://prntscr.com/exvhis

I execute npm install and i get some "warnings". Is it issue from angular-cli ?

My package.json

"dependencies": {
   "@angular/animations": "^4.0.1",
   "@angular/common": "^4.0.1",
   "@angular/compiler": "^4.0.1",
   "@angular/core": "^4.0.1",
   "@angular/flex-layout": "^2.0.0-beta.7",
   "@angular/forms": "^4.0.1",
   "@angular/http": "^4.0.1",
   "@angular/material": "^2.0.0-beta.3",
   "@angular/platform-browser": "^4.0.1",
   "@angular/platform-browser-dynamic": "^4.0.1",
   "@angular/router": "^4.0.1",
   "@swimlane/ngx-datatable": "^8.0.0",
   "core-js": "^2.4.1",
   "font-awesome": "^4.7.0",
   "ng2-cookies": "^1.0.11",
   "primeng": "^4.0.0-rc.1",
   "rxjs": "^5.1.0",
   "zone.js": "0.8.4"
 },
 "devDependencies": {
   "@angular/cli": "1.0.0",
   "@angular/compiler-cli": "^4.0.1",
   "@types/jasmine": "2.5.38",
   "@types/node": "~6.0.60",
   "codelyzer": "~2.0.0",
   "jasmine": "^2.5.3",
   "jasmine-core": "~2.5.2",
   "jasmine-spec-reporter": "~3.2.0",
   "karma": "^1.4.1",
   "karma-chrome-launcher": "~2.0.0",
   "karma-cli": "~1.0.1",
   "karma-coverage-istanbul-reporter": "^0.2.0",
   "karma-jasmine": "~1.1.0",
   "karma-jasmine-html-reporter": "^0.2.2",
   "protractor": "~5.1.0",
   "protractor-browser-logs": "^1.0.350",
   "ts-node": "~2.0.0",
   "tslint": "~4.5.0",
   "typescript": "~2.2.2"
 }

**Comment by cenkentimist** [comment]
Don't know if this answers your question but 'deduped' just means that npm had two different versions of something as dependencies so it has thrown away the older of the two.

**Comment by filipesilva** [comment]
Closing as answered by @cenkentimist, cheers!
