### ISSUE TITLE
Question: What is the current status of the Docker Deploy Design?

### ISSUE THREAD

**Issue by KyleMcNutt** [angular/angular-cli#6004]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 7.8.0
os: darwin x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.
N/A

### The log given by the failure.
N/A

### Desired functionality.
The Docker Deploy design that has been discussed in [this](https://github.com/angular/angular-cli/blob/master/docs/design/docker-deploy.md) design doc.

### Mention any other details that might be useful.
So I came across [this](https://github.com/angular/angular-cli/blob/master/docs/design/docker-deploy.md) design doc the other day, and really think it would be a seriously welcome addition to the Angular CLI. I was wondering if this work is currently being tracked anywhere or what the progress on this design doc currently is?

**Comment by choucry13** [comment]
+1

**Comment by filipesilva** [comment]
No update that I know of. It hasn't been worked on further. I know @DanWahlin used Docker with the CLI on ng-conf https://www.youtube.com/watch?v=socWfhPJptE.

**Comment by KyleMcNutt** [comment]
@filipesilva I'm aware that you _can_ use Docker with the CLI, and have seen @DanWahlin's talk which is great, but it doesn't answer the question here, Is the CLI team planning to incorporate some tools to integrate with Docker? If not should the design doc in the repo be removed? If yes, what are the next steps for this, is the CLI team open to PR's to get this moved forward?

I think what the design doc proposes would be a great addition to the CLI, currently trying to get a Docker image running that can run all the CLI commands like `ng e2e` and `ng test` requires a lot of manual configuration, and changing some of the base karma/protractor config's that come with projects generated by the CLI. Not to mention the pain of actually getting Chrome and other dependencies actually installed into the Docker image so that the CLI can run those commands.

If there was a docker image that the CLI came with that automatically worked with all of those tools and that you could execute CLI commands in, then I think it would a fantastic addition to the toolset.

**Comment by filipesilva** [comment]
Is this something you'd be interested in working on? The original effort was community driven but then lost momentum.

**Comment by KyleMcNutt** [comment]
@filipesilva yes! I would be very interested in working on this if the CLI team is still open to adding this to the CLI!

What exactly would the next steps be? To review the design doc more and see if any additions/changes need to be made?
