### ISSUE TITLE
Error encountered resolving symbol values statically on ng prod flag

### ISSUE THREAD

**Issue by basherr** [angular/angular-cli#6005]
### Bug Report or Feature Request (mark with an `x`)
Bug

### Versions.
@angular/cli: 1.0.0
@angular/compiler-cli: "^2.4.0",
node: 6.9.5
os: win32 x64

### Repro steps.
The following code is compiled on simple build but when I try to compile with `--prod` flag It just start throwing errors. I've tried compiling the same code  [here](https://www.typescriptlang.org/play/#src=%0D%0Aimport%20%7B%20List%2C%20Record%7D%20from%20'immutable'%3B%0D%0A%0D%0Aconst%20CustomerRecord%20%3D%20Record(%7B%0D%0A%09id%3A%200%2C%0D%0A%20%20%20%20name%3A%20''%2C%0D%0A%09email%3A%20''%2C%0D%0A%09customer_meta%3A%20%7B%0D%0A%09%09_address%3A%20''%2C%0D%0A%09%09_secondary_email%3A%20''%2C%0D%0A%09%09_phone%3A%20''%2C%0D%0A%09%09_cell%3A%20''%2C%0D%0A%09%09qb_id%3A%20''%2C%0D%0A%09%7D%0D%0A%7D)%3B%0D%0A%0D%0Aexport%20class%20Customer%20extends%20CustomerRecord%20%7B%0D%0A%0D%0A%09id%3A%20number%3B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%09email%3A%20string%3B%0D%0A%09customer_meta%3A%20%7B%0D%0A%09%09_address%3A%20string%3B%0D%0A%09%09_secondary_email%3A%20string%3B%0D%0A%09%09_phone%3A%20any%3B%0D%0A%09%09_cell%3A%20any%3B%0D%0A%09%09qb_id%3A%20any%3B%0D%0A%09%7D%3B%0D%0A%0D%0A%20%20%20%20constructor(props)%20%7B%0D%0A%20%20%20%20%20%20%20%20super(props)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%7D) and I didn't get any compilation error.
```
import { List, Record} from 'immutable';
const CustomerRecord = Record({
	id: 0,
    name: '',
	email: '',
	customer_meta: {
		_address: '',
		_secondary_email: '',
		_phone: '',
		_cell: '',
		qb_id: '',
	}
});

export class Customer extends CustomerRecord {
   id: number;
    name: string;
	email: string;
	customer_meta: {
		_address: string;
		_secondary_email: string;
		_phone: any;
		_cell: any;
		qb_id: any;
	};
    constructor(props) {
        super(props);
    }
}
```

### The log given by the failure.
ERROR in Error encountered resolving symbol values statically. Symbol reference expected (position 17:31 in the original .
ts file), resolving symbol Customer in C:/xampp/htdocs/angular/src/app/customer/customer.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\xampp\htdocs\angular\src

### Mention any other details that might be useful.
[Facebook immutable Record example](https://facebook.github.io/immutable-js/docs/#/Record)

**Comment by filipesilva** [comment]
Heya, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

The CLI always runs statical analysis on code to ensure it will run when compiled with AOT. This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

Good resource on how to to debug these errors are https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60 and  https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts.

If your problem still persists, it might be a bug with the Angular Compiler itself. In that case, please open an issue in https://github.com/angular/angular.
