### ISSUE TITLE
The "ng build" dist html file is compiling incorrectly

### ISSUE THREAD

**Issue by totallytotallyamazing** [angular/angular-cli#6006]
### Please go to the below link to StackOverflow and see the correct (green check marked) answer for a good explanation

http://stackoverflow.com/questions/37558656/angular-clis-ng-build-doesnt-produce-a-working-project

question title:
"Angular CLi's “ng build” doesn't produce a working project?"

correct question answer:
```
change:
<base href="/">

to:
<base href="./">
```

### Versions.
angular-cli 1.0.0
on
Linux and  macOSsierra, that I'm aware of.

### Desired functionality.
should load angular js instead just loads html
This appears to be a bug.

**Comment by sumitarora** [comment]
@totallytotallyamazing From the question seems like you are opening index.html using file system not using a server. If you run any http server in the dist you should not see the issue which is correct.
http-server: https://www.npmjs.com/package/http-server

**Comment by totallytotallyamazing** [comment]
@sumitarora Yes I was opening it using file system but also uploading via FTP to my web service provider which is a Linux based Apache server and it will not work there either until I make that edit to the index.html file in the build "dist" folder.

**Comment by sumitarora** [comment]
@totallytotallyamazing Which version of Apache you are using and Which Linux?

**Comment by totallytotallyamazing** [comment]
@sumitarora I called goDaddy tech support to be sure and verify the below info is correct...Thanks!
cPanel Shared Hosting
Apache 	2.4.25
Linux       2.4

**Comment by filipesilva** [comment]
Heya @totallytotallyamazing, when you run `ng build` you get a bunch of file that you can deploy to a server.

There's a couple of things your server needs to do to server Angular apps however. We detail that in https://angular.io/docs/ts/latest/guide/deployment.html#!#server-configuration. 

I don't know the details of your server, but you might also need configure the base tag if you're serving from a subfolder: https://angular.io/docs/ts/latest/guide/deployment.html#!#base-tag

Hope this helps!

**Comment by totallytotallyamazing** [comment]
Heya @filipesilva Thanks for your response sorry for any delay in my response, I didn't see yours till just now. 
I'm not sure if what you're saying is true for me or not. My localhost for test serving which has many sub folders works fine with <base href="/"> but on my live web server which also has many sub folders <base href="./"> is required in order for things to serve properly. Perhaps this is because my my live web server is a shared Linux server as opposed to a dedicated one, I'm not sure.

Anyway my issue is cleared up now and I'm very happy with the angular-cli project so far. I know from my searches that I'm not the only one who has encountered this issue so hopefully this information helps someone else.

**Comment by filipesilva** [comment]
Yeah deployment isn't a very easy topic overall, glad to hear you got it sorted!
