### ISSUE TITLE
How install module crypto ?

### ISSUE THREAD

**Issue by pogran** [angular/angular-cli#6009]

**Comment by deebloo** [comment]
@pogran please fill out the issue template

**Comment by choucry13** [comment]
https://www.npmjs.com/package/npmdoc-angular-crypto may help you.

**Comment by filipesilva** [comment]
Dupe of https://github.com/angular/angular-cli/issues/1548

**Comment by agabardo** [comment]
Why close a topic if the answer in the other topic mentioned don't actually cover the issue?
This Crypto library is by far the messiest thing I ever encountered in Angular.
