### ISSUE TITLE
$ ng github-pages:deploy fails to delete src/client/app and wipes the directory

### ISSUE THREAD

**Issue by Aidurber** [angular/angular-cli#601]
I'm trying to deploy to github pages however it's failing remove "src/client/app", and wiping my directory. 

**OS**: `Microsoft Windows 10 Pro, Version 10.0.10586 Build 10586`

**Versions**: 
```
angular-cli: 0.0.34
node: 5.0.0
os: win32 x64
```

**Repro steps**
1. Committed all changes
2. Ran `ng github-pages:deploy --message "Optional commit message`

**Log**
```
$ ng github-pages:deploy --message "Optional commit message"
Built project successfully. Stored in "dist/".
Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git clean -f -d"
warning: failed to remove src/client/app

Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git clean -f -d"
warning: failed to remove src/client/app

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

Full source is here if needed: https://github.com/Aidurber/Ng2-ImgurClone

**Comment by Aidurber** [comment]
Sorry guys, I should have investigated further. Atom editor was holding onto the folder. Closing

**Comment by filipesilva** [comment]
You're right though, the error message doesn't help at all really. I was getting the same. Yesterday a PR landed that makes the message a bit better: https://github.com/angular/angular-cli/commit/7dc08a737705d64d1f0657ce5dd32a79d9325e8c
