### ISSUE TITLE
Add resolver blueprint

### ISSUE THREAD

**Issue by lobo-tuerto** [angular/angular-cli#6011]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality

Would like to have a blueprint for resolvers, they are commonly used for getting data when going to a route.

`ng g resolver config` -> `config.resolver.ts`

### Mention any other details that might be useful.

For more info on the use case, check this out: https://blog.thoughtram.io/angular/2016/10/10/resolving-route-data-in-angular-2.html

**Comment by hansl** [comment]
Closing every Blueprints related issue and PR.

**Comment by inorganik** [comment]
What's the reason this was closed? Would love to see `ng g r`

**Comment by groupsvkg** [comment]
Is **ng generate resolver <name>**  feature added?

**Comment by Albosonic** [comment]
:(

**Comment by marlonlom** [comment]
:(

**Comment by MikeProcudin** [comment]
:(

**Comment by cesar2064** [comment]
:(

**Comment by koraysels** [comment]
whyyyyy nooottt?

**Comment by neil-119** [comment]
Wow.

**Comment by mbejda** [comment]
:(

**Comment by pwsm50** [comment]
#ShamelessBump

**Comment by Nexeuz** [comment]
:( * 100

**Comment by johnfedoruk** [comment]
> Closing every Blueprints related issue and PR.

Oh - thanks.

**Comment by JiaHongL** [comment]
:(

**Comment by MRMokwa** [comment]
Why is this issue closed?
