### ISSUE TITLE
Support opening browser on WSL (Ubuntu for Windows)

### ISSUE THREAD

**Issue by ciesielskico** [angular/angular-cli#6012]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

With the lastest Creator Update and updates and bugfixes to the WSL it is possible to open Windows apps from the Ubuntu Bash console.

Therefore, I would like the `-o` option to work on WSL (Ubuntu for Windows).
Everything else works, it is just a minor annoyance to not have the browser open.

**Comment by clydin** [comment]
You can track the progress of WSL support via this [PR](https://github.com/sindresorhus/opn/pull/50) for the [opn](https://github.com/sindresorhus/opn) project.

**Comment by filipesilva** [comment]
Seems like that Pr was merged, but released under a new major version. Will make a Pr to update.

**Comment by filipesilva** [comment]
Oh there's a PR already, cool!

**Comment by clydin** [comment]
Closing as solved.
