### ISSUE TITLE
Errors from production mode does not appears on development mode

### ISSUE THREAD

**Issue by calebeaires** [angular/angular-cli#6013]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli@1.0.0 
MacOS

### Repro steps.
`ng build --prod`

### The log given by the failure.
`ng: gaio-front/src/app/views/studio/canvas/canvas-tree/canvas-tree.component.html (349,6): Property 'showRemoveProcessModal' does not exist on type 'CanvasTreeComponent'.`

### Desired functionality.
When build the app, this erros is printed on terminal/console. It would be helpfully if this errors appears on dev mode too.

1. Why this errors does not show on `ng serve`, but shows on `ng build --prod`?
2. How make this erros show on development mode too(`ng serve`)?

**Comment by sumitarora** [comment]
@calebeaires Is there a repo I can take a look at?

**Comment by calebeaires** [comment]
@sumitarora, thanks for your help!

My team is working on a **private** repo right now even if it is an open source project. But, about this issue, I release that this is related to variables that have been declared on template (html) but not on component (private/public properties)

Maybe it is related to this issue: [Error with build --prod & templates since angular/cli 1.0](https://github.com/angular/angular-cli/issues/5623).

So, how to make angular-cli show thoses errors via a development server mode, not only on build --prod time.

**Comment by sumitarora** [comment]
@calebeaires I see this has been merged in master but yet to be release. You can try using the master branch and see if error still exists or not.

**Comment by clydin** [comment]
You can enable AOT (--aot) for development which should generate any errors related to the compilation of the templates.  Please note this will significantly increase rebuild times.

**Comment by filipesilva** [comment]
@calebeaires such errors only happen during AOT compilation, which is used for production builds. I agree it's a nasty surprise to find new errors when doing prod builds, but the alternative would be to use AOT all the time and as @clydin said this would massively increase rebuild times.

**Comment by NeelBhatt** [comment]
Is there any way I can suppress those errors occurred only with AOT compilation? For example, there is an error comes with --prod but if I try to fix that error, it breaks my functionality, is there a way to suppress specific error and allow the build to pass in --prod?
