### ISSUE TITLE
ng new could generate a proxy.conf.json

### ISSUE THREAD

**Issue by agoncal** [angular/angular-cli#6014]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.

1.0.0

### Desired functionality.

I find my self creating a `proxy.conf.json` file on every project. It makes life easier in development when dealing with a back end (you can easily switch environment, don't have to worry with CORS...). So what about `ng new` generating a basic `proxy.conf.json` and a new script (I usually call it `start-with-proxy`) to execute the app with the proxy ? 

`package.json`

```json
  "scripts": {
    "start": "ng serve",
    "start-with-proxy": "ng serve --proxy-config proxy.conf.json",
  }
```

`proxy.conf.json`

```json
{
  "/": {
    "target": "http://localhost:3000",
    "secure": false
  }
}
```

WDYT ?

**Comment by filipesilva** [comment]
I do recognize that for certain setups this is just something that always happens, but for the majority of users I don't think they do it.

We try to not add these blueprint customization flags if we can avoid it. What I can say is that we are planning custom blueprints for 2+.
