### ISSUE TITLE
Polyfill fail with es7->array

### ISSUE THREAD

**Issue by tingtingli911** [angular/angular-cli#6019]
### Bug Report or Feature Request (mark with an `x`)
```
I add es7->array to polyfill.ts, but the includes function fail
```

### Versions.
@angular/cli: 1.0.0
node: 7.8.0
os: darwin x64
@angular/animations: 4.0.2
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/compiler-cli: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/platform-server: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0

### Repro steps.

add es7's array to the polyfills.ts

![image](https://cloud.githubusercontent.com/assets/15266022/25216490/89f66798-25d5-11e7-8eeb-239576b54f41.png)

then I use it

![image](https://cloud.githubusercontent.com/assets/15266022/25216519/afe9f6d6-25d5-11e7-9e7e-e9291d6dbae6.png)

run it and see it from the broswer
![image](https://cloud.githubusercontent.com/assets/15266022/25216550/c801f5fc-25d5-11e7-9b93-8d8536489c21.png)

It fails then for IE11

**Comment by filipesilva** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of project core.js or file issue on their issue tracker.
