### ISSUE TITLE
Wrong description of get in ng help

### ISSUE THREAD

**Issue by alexandermikuta** [angular/angular-cli#602]
1.
Ubuntu 14.04
2. 
angular-cli: 0.0.34
node: 5.11.0
os: linux x64
3.
ng -h

The description of the get-command in the help is propably wrong.
Instead of 'Set a value in the configuration.' I guess it should be something like 'Get a value from the configuration.'

I think the wrong definition is done at: angular-cli/addon/ng2/commands/get.ts

**Comment by Brocco** [comment]
You are correct the description should read

```
Get a value from the configuration
```

Code is [here](https://github.com/angular/angular-cli/blob/cb695d473c0773ca4a4fc296fd708c58a5233369/addon/ng2/commands/get.ts#L8)

**Comment by jeremymwells** [comment]
I just submitted [PR 603](https://github.com/angular/angular-cli/pull/603) to fix this.
