### ISSUE TITLE
IE11 - vendor.bundle.js - fuction combine() - Unable to get property 'apply' of undefined or null reference

### ISSUE THREAD

**Issue by jefftham** [angular/angular-cli#6024]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 7.8.0
os: win32 x64
@angular/cli: 1.0.0
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/compiler-cli: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
npm: 4.2.0
windows 7
IE11

### Repro steps.

unknown, it works fine with chrome and firefox. it is only happens in IE.

### The log given by the failure.

Format: ![vedor.bundle.js error](http://i.imgur.com/PO5tvWd.jpg)

### Desired functionality.

IE compatible.

### Mention any other details that might be useful.

Please visit this website with IE11.
[Angular 4 app](https://jeff-stocks-monitor.herokuapp.com/)

**Comment by clydin** [comment]
Please try adjusting the polyfills.ts file according to your browser requirements.  It is well commented to assist you in the process.

**Comment by jefftham** [comment]
@clydin , thanks for helping.  it solved my problem.  I suggest to update the ReadMe so that other people aware of this.

**Comment by tata-abhi** [comment]
@clydin  I am beginner in angular development.

Can you please shed some light on adjusting polyfill.js.

Thanks.

**Comment by jefftham** [comment]
@tata-abhi  ,  polyfill.js is well commented, just follow the instruction to install the dependencies and uncomment the relevant lines.

**Comment by ruchisamit** [comment]
@jefftham  I am getting same issue in IE and Safari , I uncomment  the relevant lines in polyfill.js after this it working on IE but  safari still showing same error.

Can you please suggest how to resolve this in safari.

Thanks

**Comment by jefftham** [comment]
@ruchisamit , I am sorry that i am not familiar with the polyfill support for safari.

**Comment by masudshrabon** [comment]
In IE 10, I got the following error: (but OK in IE 11)

_**TypeError: Unable to get property 'ngMetadataName' of undefined or null reference**_ 

The property 'ngMetadataName' has been found in vendor.js.

The polyfills.ts is as the following:

/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';


/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';


/**
 * Web Animations `@angular/platform-browser/animations`
 * Only required if AnimationBuilder is used within the application and using IE/Edge or Safari.
 * Standard animation support in Angular DOES NOT require any polyfills (as of Angular 6.0).
 **/
import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/**
 * By default, zone.js will patch all possible macroTask and DomEvents
 * user can disable parts of macroTask/DomEvents patch by setting following flags
 */

// (window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
// (window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
// (window as any).__zone_symbol__BLACK_LISTED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames

/*
* in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js
* with the following flag, it will bypass `zone.js` patch for IE/Edge
*/
(window as any).__Zone_enable_cross_context_check = true;

/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */

Can you please suggest how to resolve this for IE 10.

Thanks

**Comment by masudshrabon** [comment]
In IE 10, I got the following error: (but OK in IE 11)

_TypeError: Unable to get property 'ngMetadataName' of undefined or null reference_

I have  updated the angular-cli  from 6.0.8 to 6.2.3 (Latest) and it solved the above error.

This link [#24339](https://github.com/angular/angular/issues/24339) might be helpful.
