### ISSUE TITLE
angularjs 2 bootstrap loading issue 

### ISSUE THREAD

**Issue by uttamui** [angular/angular-cli#6030]
@angular/cli: 1.0.0
node: 6.10.2
os: win32 x64
bootstrap loading issue

**Comment by delasteve** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by sumitarora** [comment]
Please fill in the above format and reopen issue if needed.

**Comment by uttamui** [comment]
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.10.2
os: win32 x64
bootstrap css  is working  bootstrap.min.js is not working  


Uncaught Error: Bootstrap's JavaScript requires jQuery
    at eval (eval at webpackJsonp.215.module.exports (addScript.js:9), <anonymous>:6:37) [<root>]
    at eval (<anonymous>) [<root>]
    at webpackJsonp.215.module.exports (addScript.js:9) [<root>]
    at Object.110 (bootstrap.min.js?ffe6:1) [<root>]
    at __webpack_require__ (bootstrap 32adcf9…:52) [<root>]
    at Object.256 (addScript.js:10) [<root>]
    at __webpack_require__ (bootstrap 32adcf9…:52) [<root>]
    at webpackJsonpCallback (bootstrap 32adcf9…:23) [<root>]
    at :4200/scripts.bundle.js:1:1 [<root>]

**Comment by uttamui** [comment]
**how to add script.js**

**Comment by nimatullah** [comment]
Add your script file inside of angular-cli.json and import your css file inside of style.css or style.scss

**Comment by uttamui** [comment]
already i added css and jquery.js file in   angular-cli.json

This is the my angular-cli.json    file

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "projects"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.css",
        "styles.css"
      ],
      "scripts": [
       "../node_modules/bootstrap/dist/js/bootstrap.min.js",
       "../node_modules/jquery/dist/jquery.js"
 ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}




still jquery file is not working

**Comment by uttamui** [comment]
**now it's working fine**
