### ISSUE TITLE
Add git-revision-webpack-plugin

### ISSUE THREAD

**Issue by ishitatsuyuki** [angular/angular-cli#6032]
As we currently don't have a plugin architecture, we need changes in the core to add new features.

[git-revision-webpack-plugin](https://github.com/pirelenito/git-revision-webpack-plugin) is a plugin that obtains the git commit hash. It's a major use case for pre build scripts (see https://github.com/angular/angular-cli/issues/4419#issuecomment-278903128, https://github.com/angular/angular-cli/issues/1656#issuecomment-249918311). (By the way, the proposed use case of putting secret is useless, because anyone can extract it from the bundle.)

We should implement it combined with the DefinePlugin ([reference](https://github.com/pirelenito/git-revision-webpack-plugin#plugin-api)).

**Comment by filipesilva** [comment]
This isn't something we're looking at doing. I understand it's something some users might want, but it's also something that's not hard to do manually.
