### ISSUE TITLE
--dry-run  for generating service writes import statement and includes service in providers

### ISSUE THREAD

**Issue by Kulbhushan18** [angular/angular-cli#6035]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> --dry-run  for generating service writes import statement and includes in providers
```

### Versions.
```
Output from: `ng --version`.
@angular/cli: 1.0.0
node: 7.0.0
os: win32 x64
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.3

 Windows (10)
```
### Repro steps.
- ng g s core\exception -m core\core.module -d
- commands run:
  - ng new APP -sg -sc -r
  - ng g c home
  - ng g m core
  - ng g s core\exception -m core\core.module -d

### The log given by the failure.
No log generated, but following is the output of command
```
installing service
You specified the dry-run flag, so no changes will be written.
  create src\app\core\exception.service.spec.ts
  create src\app\core\exception.service.ts
  update src\app\core\core.module.ts
```

### Desired functionality.
--dry-run  for generating service should not modify anything

**Comment by sumitarora** [comment]
@Kulbhushan18 This has already been addressed and fix is in the master. Will be available with next release. https://github.com/angular/angular-cli/issues/5862
