### ISSUE TITLE
main.bundle.js for each component

### ISSUE THREAD

**Issue by Danieleeee** [angular/angular-cli#6037]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.10.0
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10

### Desired functionality.

There is a way to disable the minification in AngularCli?
After I launch the command ng build I need to have all files.js, in dist folder, separate and legible.

### Mention any other details that might be useful.

Like happens in SystemJs configuration.

**Comment by sumitarora** [comment]
@Danieleeee By default Angular CLI builds are generated in `dist` folder configured in `.angular-cli.json` which you can change as well. Running `ng build` will generate build in dist folder which is not minified if you want minified build you need to run `ng build --prod`.

**Comment by Danieleeee** [comment]
Hi @sumitarora ,
ng build have the same result of ng build --prod, only one file.js with all components.
I need one file.js for each component, like SystemJs do.

**Comment by bmayen** [comment]
@Danieleeee, that's not how Webpack works. It's a module bundler, which, by definition, takes your separate modules and outputs a bundle. What is your use case that you *need* separate files output? Are sourcemaps not sufficient?

**Comment by Danieleeee** [comment]
I work with many Components (like forms). 
In the porduction is much more functional to update only the component that you want to update(change).
Instead with this configuration I have to buld and update all Components everytime.
How can be useful sourcemaps in this situation?

**Comment by bmayen** [comment]
I think there's still either a misunderstanding here about how Webpack works or how to use it. Are you concerned that all of your components, TS, css, etc is being rebuilt on every change? Are you running in watch mode? Webpack is smart enough to watch the filesystem and only rebuild things which have changed. It outputs everything to a single bundle, but that doesn't mean it rebuilds everything every time. You should see that the initial build takes a while and subsequent builds are reasonably fast.

**Comment by Danieleeee** [comment]
I know that watch mode (-w) rebuild only things that are changed. But I think it's useful during the development phase. Not for update in production.
If I create the build today and I want to upgrade a component after a week, I have to leave the watch mode active for all the time?

**Comment by deebloo** [comment]
@Danieleeee if you have to make a change you will need to redeploy all of your bundles.

**Comment by bmayen** [comment]
Not sure what problem you're trying to solve here. You don't want to do a full rebuild for a new production deployment? That seems like a non-issue unless you're redeploying production every few minutes... in which case I'd argue for a change in your process over a change in angular-cli. In any case, the use case is not supported; again, webpack is a module *bundler* :)

**Comment by Danieleeee** [comment]
> webpack is a module bundler :)

If I have several modules, webpack make only one main bundle?
I tell you this because each of my components is a mudule (@NgModule) with its own routingModules.

**Comment by Danieleeee** [comment]
I have a similar behavior with route lazy loading, but files have incomprensible name (like 0.chunk.js, 1.chunk.js,....).

**Comment by bmayen** [comment]
There's a difference between ngModule and ES modules. Check out https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-ng-vs-js-modules for lots of good info on this and other ngModule topics.

You can also read up on "output" and CommonChunks on the webpack website for more information. Remaining questions around this general usage would be better suited for Stackoverflow. 

Hope this helps!

**Comment by filipesilva** [comment]
@Danieleeee the way the build system in the CLI works, everything gets bundled. I understand that in some cases you might not want that, but overall it's not optional (in the CLI) and usually better to bundle. It allows for a smaller total load time.

The only time you will get more than one bundle is when you have lazy loaded routes - the CLI will detect that and make separate bundles automatically.

For a CLI application, when making changes, you would always redeploy the generated build artifacts.

**Comment by vspatil678** [comment]
How to unbundle the app.bundle.js file in angular?
