### ISSUE TITLE
Create Angular2 Application using Angular CLI and Asp.Net Mvc5 and Gulp

### ISSUE THREAD

**Issue by unalun** [angular/angular-cli#6038]
Hi,
Create Angular2 Application using Angular CLI and Asp.Net Mvc5(.netframework) and Gulp ?
Code example ?

**Comment by sumitarora** [comment]
@unalun Angular CLI scaffolds application that can be integrated with any of the backend frameworks and served using any of the servers. Build system used is webpack which supports a lot of the features out of the box. 

Is there anything specific you are having the issue? Please reopen issue with information filled according to the template.
