### ISSUE TITLE
update stories include angular material

### ISSUE THREAD

**Issue by manunoly** [angular/angular-cli#6039]
### Versions.
angular 4.0

### Wiki documentation
 include angular material should be update,  css-loader failing finding relative url, in the story are using 
`@import '~@angular/material/core/theming/prebuilt/deeppurple-amber.css';`
and should be replace by this
 `@import '~@angular/material/prebuilt-themes/indigo-pink.css';`

here the issue an the solution  #5026

**Comment by asnelling** [comment]
PR with fix #5963 just waiting to be merged in.

**Comment by filipesilva** [comment]
Fixed via https://github.com/angular/angular-cli/pull/5963
