### ISSUE TITLE
ng eject: Your package.json scripts must not contain a build script as it will be overwritten.

### ISSUE THREAD

**Issue by Danieleeee** [angular/angular-cli#6040]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

`@angular/cli: 1.0.0
node: 6.10.0
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10`

### Repro steps.

when I run `ng eject`
`Your package.json scripts must not contain a build script as it will be overwritten.`

this is my package.json:
`  "dependencies": {
    "@angular/common": "^2.4.10",
    "@angular/compiler": "^2.4.10",
    "@angular/core": "^2.4.10",
    "@angular/forms": "^2.4.10",
    "@angular/http": "^2.4.10",
    "@angular/platform-browser": "^2.4.10",
    "@angular/platform-browser-dynamic": "^2.4.10",
    "@angular/router": "^3.4.10",
    "@types/file-saver": "0.0.0",
    "angular2-ie9-shims": "0.0.2",
    "classlist": "^1.0.1",
    "core-js": "^2.4.1",
    "intl": "^1.2.5",
    "file-saver": "^1.3.3",
    "moment": "2.18.1",
    "primeng": "^2.0.5",
    "rxjs": "^5.2.0",
    "ts-helpers": "^1.1.2",
    "web-animations-js": "^2.2.2",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^2.4.10",
    "@types/jasmine": "2.5.46",
    "@types/node": "~7.0.12",
    "codelyzer": "~3.0.0-beta.4",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.5.0",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^1.0.0",
    "protractor": "~5.1.1",
    "ts-node": "~3.0.2",
    "tslint": "~4.5.1",
    "typescript": "~2.2.2"
  }
}
`

**Comment by sumitarora** [comment]
@Danieleeee This is working as specified. `ng eject` adds build script to package.json and it will override build script if it's already present.

**Comment by Danieleeee** [comment]
I have to insert ng eject --force for execute it.
Ok thanks.

**Comment by sumitarora** [comment]
Closing as above.
