### ISSUE TITLE
ng eject: The specified command eject is invalid. For available options, see `ng help`.

### ISSUE THREAD

**Issue by najafsen** [angular/angular-cli#6045]
I'm trying to eject an angular app, but I'm getting this error:
`The specified command eject is invalid. For available options, see 'ng help'.`

### Versions.
angular-cli: 1.0.0-beta.28.3
node: 6.10.2
os: linux x64
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 3.4.10
@angular/compiler-cli: 4.0.3

**Comment by Gillespie59** [comment]
You should update @angular/cli. This command is available since 1.0.0-beta.32 I think. https://github.com/angular/angular-cli/commit/7ac0d0562641bc862a3487084cd090bce40713b4
