### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by prasanthtr575** [angular/angular-cli#6047]
My application is working, but I'm getting an error in console as following

"
**Uncaught TypeError: Cannot read property 'apply' of undefined**
"
![image](https://cloud.githubusercontent.com/assets/5172124/25319646/ba28752e-28bd-11e7-9b25-bf719301a497.png)

This is happening when the "zone.js": "^0.8.4". 
It's not for "zone.js": "0.8.5"

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by iainplimmer** [comment]
Already opened an issue here.

https://github.com/angular/angular-cli/issues/6036
