### ISSUE TITLE
where can i add ref to external library in project created by cli 

### ISSUE THREAD

**Issue by khaledafifi** [angular/angular-cli#6051]
where can I add ref to external library in project created by cli

**Comment by delasteve** [comment]
This issue doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please next time post your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

https://github.com/angular/angular-cli/wiki/stories-global-lib
https://github.com/angular/angular-cli/wiki/stories-global-scripts

**Comment by sumitarora** [comment]
Closing as above.
