### ISSUE TITLE
The --skip-test option still generates test artifacts

### ISSUE THREAD

**Issue by agoncal** [angular/angular-cli#6054]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: local (v1.0.0, branch: master)
node: 7.9.0
os: darwin x64

### Repro steps.

ng new myproj --skip-tests --skip-e2e

### Desired functionality.

Using the `--skip-tests` option, I expect not to find any test artifacts at all in the project. But when I create a new project, I still have the following : 

`tsconfig.spec.json` and `karma.conf.js` files

In the `.angular-cli.json` file still appears : 

```json
  "testTsconfig": "tsconfig.spec.json",
  "lint": [
    {
      "project": "src/tsconfig.spec.json"
    },
  ],
```
In the `package.json` file we still have :

```json
  "scripts": {
    "test": "ng test",
  },
  "devDependencies": {
    "@types/jasmine": "2.5.38",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
  }
```

The readme still mentions : 

> ## Running unit tests
> 
> Run `ng test` to execute the unit tests via [Karma](https://karma-runner.github.io).

**Comment by Brocco** [comment]
The initial implementation of `skip-test` is to not generate the spec file for the default component, not to remove all testing functionality from the application.

Implementing this strategy would be a breaking change as it would change the functionality of the `skip-test` flag.

That being said, I'm not certain this is something we should be implementing right now as it may be better suited for the next major version which will allow for finer grain control over the templates/blueprints being generated.

**Comment by agoncal** [comment]
I understand. In JBoss Forge you can generate a project without any tests... and later, if you want, use a command (setup test) which will then generate test classes, but also add the needed dependencies, readme... and so on. It is very handy because you can start a project with just the minium dependencies, and add them later if needed.... but I know how difficult it is to implement.

**Comment by Brocco** [comment]
This is something we will be considering for future versions, but for now I'm not sure adding in that type of complexity makes the most sense.

**Comment by agoncal** [comment]
I agree

**Comment by locohost** [comment]
Running ng new my-app --skip-tests --skip-e2e and I'm still getting test folders, apps and e2e junk. What am I doing wrong?

**Comment by Brocco** [comment]
@locohost nothing, to get rid of all test artifacts the only ways are manually removing them or using the `--minimal` flag on `ng new`

**Comment by PierBover** [comment]
Apparently the `--minimal` flag doesn't work anymore.

It's not documented either: https://github.com/angular/angular-cli/wiki/new

**Comment by thismarcoantonio** [comment]
`--minimal` flag was removed from Angular Cli, unfortunately there is no way to generate a project without tests at the moment...
