### ISSUE TITLE
Disconnect from live reload on purpose

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#6055]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report
- [X] feature request
```

### Versions.
latest

### Desired functionality.
Is it possible to disconnect the live reload on purpose?
I just don't want to reload the page in a special browser-tab when i make a change.

**Comment by maxbellec** [comment]
This feature has been implemented (passing `--live-reload false` to `ng serve`), but is currently not working.

See https://github.com/angular/angular-cli/issues/1755 for more details.

Please close this issue.

**Comment by clydin** [comment]
It's definitely implemented and working in the latest version.

You can also use the negation shorthand "--no-live-reload".

**Comment by MickL** [comment]
Sounds cool! Is there also a function for the browser-console to disable it spontaneously?

**Comment by clydin** [comment]
Unfortunately, not that I'm aware of.

**Comment by filipesilva** [comment]
Closing as answered by @clydin, thanks!

**Comment by bunyaminsg** [comment]
I do it by running `delete window.Zone` in the browser console. It throws error when trying to reconnect after a change, but at least it does not reload the current tab :sweat_smile:
