### ISSUE TITLE
ng new could have a skip-editorconfig option

### ISSUE THREAD

**Issue by agoncal** [angular/angular-cli#6056]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

1.0.0

### Desired functionality.

I'm being a bit lazy here ;o)  But all my projects already have an `.editorconfig` file. So when I generate an Angular application with Angular CLI, the first thing I do is delete the generated `.editorconfig` and instead use the one from our project.

Just wondering if we could have a `--skip-editorconfig` option so no `.editorconfig` file is generated ?

**Comment by clydin** [comment]
I'm not sure that an option is necessary for the removal of a single file that can be easily deleted after the fact; and, in and of itself, is useful to the overwhelming majority of users.  There's also a cost to each added feature both in terms of upfront development and ongoing maintenance that needs to be considered.
The good news is that the next major version will offer far more customization via a plugin system.

**Comment by agoncal** [comment]
Yes, I know, I'm being lazy ;o)

Is just that I tend to script my projects with a bunch of NG CLI commands. So the more precise I can be on my scripts, the better. But I understand the cost of having such option (I actually run a `rm .editorconfig` in my script to delete the file).

**Comment by sumitarora** [comment]
Closing as above.
