### ISSUE TITLE
Angular2 + Electron = Node Core Modules

### ISSUE THREAD

**Issue by codekraft-studio** [angular/angular-cli#6062]
### Versions.
@angular/cli: 1.0.0 

### Desired functionality.
Load node core modules inside application.

### Question
Since electron is not a browser and can handle all the node core modules, I would like to know if is possible to load node core modules and if it is, how?

In [this](https://scotch.io/tutorials/creating-desktop-applications-with-angularjs-and-github-electron) scotch.io tutorial they use angular1 and electron with node-mysql (that require __net__ node core module) and it's working fine.

Similar question #5324 but this time with Electron we are not limited to the browser.

**Comment by filipesilva** [comment]
Discussion about this is ongoing in https://github.com/angular/angular-cli/issues/5767
