### ISSUE TITLE
build prod provide useValue: window doesn't work

### ISSUE THREAD

**Issue by marciomsm** [angular/angular-cli#6067]
When I compile to prod, the provide "useValue: window" doesn't work. Does anyone know if it is an issue? When I compile it to dev, everything works.

app.module.ts
```
...
providers: [
{ provide: WindowService, useValue: window }
]
...
```

**Comment by deebloo** [comment]
@marciomsm this is expected behavior with AOT. The value "window" does not exist at build time. instead of useValue try useFactory

```TS
export function windowFactory() {
  return window:
}

...
providers: [
   { provide: WindowService, useFactory: windowFactory }
]
...
```

**Comment by marciomsm** [comment]
@deebloo thank you. I changed as you said and it worked.
