### ISSUE TITLE
the question about compile

### ISSUE THREAD

**Issue by deepthan** [angular/angular-cli#6073]
Start the project after, is not an error, page rendering submitted to compile errors after a second, there is only one warning information is as follows:

Failed to compile.

./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles/bootstrap.scss
autoprefixer: D:\project\mynewProje\seczone-platform-frontend\src\styles\bootstrap.scss:167:3: You should write display: flex by final spec instead of display: box
 @ ./src/styles/bootstrap.scss 4:14-201
 @ multi ./src/styles/bootstrap.scss ./~/angular2-toaster/toaster.css

What should I do

**Comment by maxbellec** [comment]
This is not the right place to ask for help debugging.

Please post a properly formatted question with more details on how to reproduce your bug (ideally with a link to a plunker) to http://stackoverflow.com/ and close this issue.

**Comment by delasteve** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by sumitarora** [comment]
Closing as above.
