### ISSUE TITLE
When generating a class with 'component' in the name (e.g. component base class), anything after the 'component' is ignored

### ISSUE THREAD

**Issue by williamBurgeson** [angular/angular-cli#6074]
```ng generate class xxx.component.base``` produces a file called 'xxx.component', which clearly wasn't the intention.

**Comment by filipesilva** [comment]
@Brocco can you clarify if this is intentional or a bug?

**Comment by williamBurgeson** [comment]
Might be good to add an extra param to the generator command, not only for components but for services, classes an any other createable artefact, e.g. so you can specify the filename and the class name separately.

**Comment by shairez** [comment]
@Brocco ping ☝️ 

#goodnessSquad

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
