### ISSUE TITLE
[Bug] - TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#6075]
### OS
Mac  OSX Sierra 10.12.4

### Versions
@angular/cli: 1.0.1
node: 6.9.1
os: darwin x64
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.1
@angular/compiler-cli: 4.0.3

### Repro steps.
```
npm i -g @angular/cli
ng new foo
ng s -o
```

The app renders, but check the developer tools console and you will see ...

![image](https://cloud.githubusercontent.com/assets/1202528/25386829/b2b7bba4-2996-11e7-94ed-e4f5d4d0eeb6.png)

I am using Chrome

**Comment by hccampos** [comment]
It seems to be a `zone.js` problem. Using `0.8.7` instead of `0.8.8` works. 

Duplicate of #6036 and #6047

**Comment by johnpapa** [comment]
Just tested by pinning to zones `0.8.7` and it works.

**Comment by intellix** [comment]
Supposedly fixed in: https://github.com/angular/zone.js/pull/747

**Comment by iainplimmer** [comment]
Hi @johnpapa this is a dupe of https://github.com/angular/angular-cli/issues/6036

**Comment by johnpapa** [comment]
yep. i see that above

**Comment by intellix** [comment]
0.8.9 released with a fix :) https://github.com/angular/zone.js/blob/master/CHANGELOG.md#089-2017-04-25

**Comment by sumitarora** [comment]
@johnpapa Working as expected no errors. 😄

**Comment by johnpapa** [comment]
confirmed fixed with zones 0.8.9.

thanks!
