### ISSUE TITLE
No SourceMaps for global styles.scss imported files

### ISSUE THREAD

**Issue by nadhir-falta** [angular/angular-cli#6077]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 6.10.0
os: win32 x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/compiler-cli: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/platform-server: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0

### Repro steps.

Adding imports to global styles.scss in an Angular-cli projects and using --ec=true in the serve command, won't generate sourceMap for the imported files, but instead will generate a sourceMap for only the styles.scss.
changing styles.js line 95 to 
{ test: /\.scss$|\.sass$/, loaders: ['sass-loader?sourceMap'] },
get me the sourceMaps for those imported files, but still then I hit this issue #2826
![scss](https://cloud.githubusercontent.com/assets/9285569/25392118/ce165874-29a5-11e7-9def-1aa91b7546c6.PNG)

### Desired functionality.

Angular-CLI should be able to generate sourceMaps for files imported inside global styles.scss file.

**Comment by filipesilva** [comment]
This isn't intended, and I actually thought it was working.

**Comment by lnewalu** [comment]
I have the same issue.  Was able to get it working with @nadhir-falta  suggestion of changing line 95, 

![image](https://cloud.githubusercontent.com/assets/8127022/26001828/a0f2e232-36fb-11e7-9ba4-87685691df5f.png)

I also also updated line 148,
![image](https://cloud.githubusercontent.com/assets/8127022/26001885/d341b862-36fb-11e7-93f3-5a76c7dd45e8.png)

My question now is it looks like the styles are getting loaded twice?
![image](https://cloud.githubusercontent.com/assets/8127022/26002043/5a2f6306-36fc-11e7-9ebf-12909fb2d06d.png)

is this the correct or is there a way to change that from happening?
loading/importing my global SCSS (app.scss) in the styles.scss file.

**Comment by filipesilva** [comment]
I can't reproduce this issue on latest master (`1.0.0-rc.0` on npm).

I added a new `src/imported-style.scss` with `body { color: #456 }`, renamed `styles.css` to `styles.scss` (also changed it on `.angular-cli.json`), then added `@import './imported-style';` to it.

Then I ran `ng serve` and opened the page in Chrome (Version 58.0.3029.110 (64-bit)), inspected body, and could see the correct file and line:

![image](https://cloud.githubusercontent.com/assets/4172079/26111847/2edc4070-3a4e-11e7-9826-ee0750d49c19.png)
