### ISSUE TITLE
ng build -html false

### ISSUE THREAD

**Issue by jmurphzyo** [angular/angular-cli#6078]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X ] feature request
```

### Versions.
@angular/cli: 1.0.1
node: 7.7.1
os: win32 x64
@angular/animations: 4.0.3
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/platform-server: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.1
@angular/compiler-cli: 4.0.3
@angular/language-service: 4.0.3

### Repro steps.
N/A

### The log given by the failure.
N/A

### Desired functionality.
I would like to see an option to skip generating the html file. One of the use cases I would be using it for is for a .net project. Currently I just setup a npm script to delete the html file after the build completes.

**Comment by filipesilva** [comment]
This isn't something that we're thinking of doing for 1.x, but users should be able to do with the upcoming addon system.
