### ISSUE TITLE
error Windows_NT 6.1.7600

### ISSUE THREAD

**Issue by ankushkale** [angular/angular-cli#6080]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cpi' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData @angular/cpi
8 silly fetchNamedPackageData @angular/cpi
9 silly mapToRegistry name @angular/cpi
10 silly mapToRegistry scope (from package name) @angular
11 verbose mapToRegistry no registry URL found in name for scope @angular
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@angular/cpi',
14 silly mapToRegistry   scope: '@angular',
14 silly mapToRegistry   escapedName: '@angular%2fcpi',
14 silly mapToRegistry   name: '@angular/cpi',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/@angular%2fcpi
16 verbose request uri https://registry.npmjs.org/@angular%2fcpi
17 verbose request no auth needed
18 info attempt registry request try #1 at 12:59:16 AM
19 verbose request id 16d0c762aed36ee9
20 http request GET https://registry.npmjs.org/@angular%2fcpi
21 http 404 https://registry.npmjs.org/@angular%2fcpi
22 verbose headers { 'content-type': 'application/json',
22 verbose headers   'cache-control': 'max-age=0',
22 verbose headers   'content-length': '21',
22 verbose headers   'accept-ranges': 'bytes',
22 verbose headers   date: 'Tue, 25 Apr 2017 19:29:17 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   age: '0',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-lhr6346-LHR',
22 verbose headers   'x-cache': 'MISS',
22 verbose headers   'x-cache-hits': '0',
22 verbose headers   'x-timer': 'S1493148557.679248,VS0,VE677' }
23 silly get cb [ 404,
23 silly get   { 'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=0',
23 silly get     'content-length': '21',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Tue, 25 Apr 2017 19:29:17 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-lhr6346-LHR',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1493148557.679248,VS0,VE677' } ]
24 silly fetchPackageMetaData Error: Not found : @angular/cpi
24 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:304:12)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:292:14)
24 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:212:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:186:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1081:10)
24 silly fetchPackageMetaData     at emitOne (events.js:96:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1001:12)
24 silly fetchPackageMetaData  error for @angular/cpi { Error: Not found : @angular/cpi
24 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:304:12)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:292:14)
24 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:212:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:186:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1081:10)
24 silly fetchPackageMetaData     at emitOne (events.js:96:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1001:12) pkgid: '@angular/cpi', statusCode: 404, code: 'E404' }
25 silly rollbackFailedOptional Starting
26 verbose stack TypeError: Cannot read property 'path' of null
26 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:511:29)
26 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
26 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
26 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
26 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:337:5
26 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
26 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
26 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
26 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:294:5
26 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
27 verbose cwd C:\Windows\system32
28 error Windows_NT 6.1.7600
29 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cpi"
30 error node v7.9.0
31 error npm  v4.2.0
32 error Cannot read property 'path' of null
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]

**Comment by clydin** [comment]
Please try "@angular/cli" instead of "@angular/cpi"; note the "l" instead of "p".
