### ISSUE TITLE
Proxy to backend for WebSocket

### ISSUE THREAD

**Issue by lemonado** [angular/angular-cli#6081]
It's perfectly working for Http, but not for WebSocket. I did not find the documentation about this. How can I do proxy for WS?
`ng serve --proxy-config proxy.conf.json`
proxy.conf.json:
```
{
  "/": {
    "target": "http://localhost:8080",
    "secure": false
  }
}
```

**Comment by lemonado** [comment]
```
{
  "/": {
    "target": "http://localhost:8080",
    "secure": false
    "ws":true
  }
}
```

**Comment by lidebug** [comment]
"/ws": {
    "target": "ws://localhost:4000",
    "secure": false,
    "ws": true
  }

**Comment by ankushsood** [comment]
Its old thread, but i am still stuck with same issue. In my websocket instance I have to pass complete url.
`self.socket =this.protocols ? new WebSocket(this.url, this.protocols) : new WebSocket(this.url);`

I cannot pass relative path in webSocket. Please suggest me how to use proxy in such scenario.
