### ISSUE TITLE
Error when use private variable with command ng build -prod 

### ISSUE THREAD

**Issue by rainstormza** [angular/angular-cli#6089]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.1
node: 6.10.0
os: darwin x64
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.1
@angular/compiler-cli: 4.0.3
Vertices-MacBook-Pro:ang1.0.1 vertice$ 

### Repro steps.

app.component.ts
private title = 'app works!';

### The log given by the failure.

ERROR in /Users/vertice/Desktop/ang1.0.1/src/$$_gendir/app/app.component.ngfactory.ts (31,30): Property 'title' is private and only accessible within class 'AppComponent'.

### Mention any other details that might be useful.

#5623 
I've seen that @hansl already fixed this problem
but I've tried to use private variable
but error still happens after use ng build -prod.

**Comment by clydin** [comment]
Public access for variables used in a template is an Angular requirement and is reported as an error by the Angular template compiler.  The fix mentioned was to report warnings as warnings instead of errors; which doesn't apply in this situation.

**Comment by Fallenstedt** [comment]
I really wish I knew this before I finished my project. There should be a way to report warnings in development that a private variable is being used in a template.
