### ISSUE TITLE
ng build works fine, but ng build --prod fails

### ISSUE THREAD

**Issue by shoebsd31** [angular/angular-cli#6091]
I get the following error : 

**ERROR in Can't resolve all parameters for UserApi in E:/Source/Dev/Frontend2/src/app/services/api/UserApi.ts: ([object Object], ?).

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'E:\Source\Dev\Frontend2\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts**

Everything works fine on ng --build and ng --serve.

I am not able to understand what does it do differently  in --prod that it is throwing such error.

Also I checked UserApi.ts, which looks perfectly fine to me

my package.json is as follows : 

`{
  "name": "demo-client",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "build": "ng build --prod",
    "start": "ng serve --sourcemap --host localhost --port 8000",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "@angular/core": "^4.0.1",
    "@angular/forms": "^4.0.1",
    "@angular/http": "^4.0.1",
    "@angular/platform-browser": "^4.0.1",
    "@angular/platform-browser-dynamic": "^4.0.1",
    "@angular/platform-server": "^4.0.1",
    "@angular/router": "^4.0.1",
    "angular-in-memory-web-api": "~0.2.4",
    "core-js": "^2.4.1",
    "ng2-accordion": "0.0.15",
    "ng2-bootstrap": "^1.4.2",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "typescript": "^2.2.2",
    "zone.js": "^0.7.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "lodash": "^4.16.4",
    "protractor": "~4.0.13",
    "rimraf": "^2.5.4",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }
}
`

I am using angular/cli version 1.0.0 and node : 7.7.2

**Comment by rochapablo** [comment]
I'm not sure if (https://github.com/Gbuomprisco/ng2-tag-input/issues/345#issuecomment-297517857) could be related.

But running locally works fine, but not when I build the application at Heroku.

```
"heroku-postbuild": "ng build --prod"
```

I still trying to understand where exactly it's the problem.

**Comment by rochapablo** [comment]
https://github.com/angular/angular-cli/issues/6020

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
