### ISSUE TITLE
Feature: add *include* option to AotPlugin

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular-cli#6093]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
node 6.9.5
npm 3.10.10
Windows 8.1

### Desired functionality.
AotPlugin should have `include` option which overrides (or appends to?) `include` from tsconfig. AotPlugin  already has `compilerOptions` and `exclude` options. This way, one could use the same tsconfig to build multiple applications, since @ngtools/webpack doesn't support multiple entry points.

### Mention any other details that might be useful.
@ngtools/webpack doesn't work for me unless I add bootstrap script to `include` in tsconfig.

**Comment by filipesilva** [comment]
I don't think that would work too well with statical analysis actually. It does expect a single application.

If you need to build multiple applications, it's better to separately build each of them instead.

**Comment by dawidgarus** [comment]
@filipesilva
> If you need to build multiple applications, it's better to separately build each of them instead.
That's what i want to achieve. But to do so, I need to include some declaration files, different for each app:
```
"include": [
  "src/app1/declarations.d.ts"
]
```
Add I don't want to create separate tsconfig for each app only with different `include`.
