### ISSUE TITLE
don't reload page after the file changed (on windows)

### ISSUE THREAD

**Issue by krasevych** [angular/angular-cli#61]
When I changed some file then the page don't refresh and I see the message:
livereload.js?snipver=1	GET	(pending)		ember-cli-live-reload.js:6		Pending

**Comment by krasevych** [comment]
I fixed this bug but I can't create branch and pull request

**Comment by cironunes** [comment]
Hi @krasevych, do you need help? Maybe you can share your screen and we get the branch and the pull request. :)

**Comment by krasevych** [comment]
when I try to create new branch I get 403(

**Comment by Kwaq** [comment]
Hi,
Any news on this issue?

**Comment by filipesilva** [comment]
I've using windows and this isn't happening to me. Is it still happening to you @krasevych ?

**Comment by hansl** [comment]
Closing this as non repro.
