### ISSUE TITLE
Production build failed with --aot option

### ISSUE THREAD

**Issue by paulmajora** [angular/angular-cli#6101]
> ng build --prod --aot=false --bh /
W
Hash: 86f7d968fb1338f6973e
Time: 30760ms
chunk    {0} polyfills.02e94b9ade803b61d4c0.bundle.js (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.024acb443441716d1306.bundle.js (main) 301 kB {3} [initial] [rendered]
chunk    {2} styles.060ad473ce1fab4aca04.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.3c6658b0d60af4afe8fb.bundle.js (vendor) 3.24 MB [initial] [rendered]
chunk    {4} inline.6ff93049aee59bfd2317.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Calling function 'BusyModule', function calls are not supported. Consider replacing the function
 or lambda with a reference to an exported function, resolving symbol AppModule in C:/xampp/htdocs/Hubtel.Me/src/app/app.module.ts, resolving symbol AppModule
in C:/xampp/htdocs/Hubtel.Me/src/app/app.module.ts

Kindly provide a way to fix this issue or skip errors of some sort

**Comment by sumitarora** [comment]
@paulmajora Can you provide an example of the project or module you are having issues with.

**Comment by paulmajora** [comment]
Hi , Arora ,  Here's the module details

link : https://www.npmjs.com/package/angular2-busy

npm install --save angular2-busy

ModuleName : BusyModule

Thanks for your time

**Comment by filipesilva** [comment]
Heya, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

The CLI always runs statical analysis on code to ensure it will run when compiled with AOT. This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

Good resource on how to to debug these errors are https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60 and  https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts.

If your problem still persists, it might be a bug with the Angular Compiler itself. In that case, please open an issue in https://github.com/angular/angular.
