### ISSUE TITLE
jQuery error in new ng-client project while trying to load jquery-ui

### ISSUE THREAD

**Issue by vimal** [angular/angular-cli#6102]
```
Uncaught ReferenceError: jQuery is not defined
    at eval (eval at webpackJsonp.89.module.exports (addScript.js:9), <anonymous>:6:75)
    at eval (eval at webpackJsonp.89.module.exports (addScript.js:9), <anonymous>:6:84)
    at eval (<anonymous>)
    at webpackJsonp.89.module.exports (addScript.js:9)
    at Object.109 (jquery-ui.min.js?40ad:1)
    at __webpack_require__ (bootstrap aa1aa00…:52)
    at Object.249 (scripts.bundle.js:35)
    at __webpack_require__ (bootstrap aa1aa00…:52)
    at webpackJsonpCallback (bootstrap aa1aa00…:23)
    at scripts.bundle.js:1
```

### Repro steps.
```
ng new new-client
npm install jquery --save
npm install jqueryui --save
npm install @types/jquery --save-dev
npm install @types/jqueryui --save-dev
ng serve
```

### .angular-cli.json
```
"scripts": [
    "../node_modules/jquery/dist/jquery.min.js",
    "../node_modules/jqueryui/jquery-ui.min.js"
]
```

**Comment by RicardoVaranda** [comment]
Use
`declare let jQuery: any;`

After your imports.

**Comment by vimal** [comment]
@RicardoVaranda : I haven't used any kind of ```jQuery``` or ```$``` related code in my components yet. However I have added it to the app.component.ts after the imports, but still the same error.

**Comment by RicardoVaranda** [comment]
What version of cli are you using? I just ran your repo steps on:

@angular/cli: 1.0.0
node: 6.10.2
os: darwin x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.0


And got no errors.

**Comment by vimal** [comment]
@RicardoVaranda : I forgot to mention the fact that I was using the angular client based app inside an Electron application. Yes, it works fine in browser without any issues. I understand that the above issue is entirely not related to the angular client app and is an issue with the electron app.
