### ISSUE TITLE
ng build -prod fails

### ISSUE THREAD

**Issue by amitport** [angular/angular-cli#6104]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.0.1
node: 7.9.0
os: win32 x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0
```

### Repro steps.

```
ng new <project> --style scss --routing
cd <project>
ng build -prod
```
(not sure if the `scss` and `routing` are relevant)

### The log given by the failure.

`
ERROR in main.662bf8bc43ad8d8efd54.bundle.js from UglifyJs
Invalid assignment [main.662bf8bc43ad8d8efd54.bundle.js:71,21]
`
### Desired functionality.

no error

**Comment by delasteve** [comment]
I just attempted to reproduce this with a clean install of the CLI and was unable to do so. Are you positive you didn't make any other changes to the project?

**Comment by sumitarora** [comment]
@amitport I have checked that too. Can you try it again with a fresh install and in a new project. If it's still an issue, please reopen this issue.

**Comment by amitport** [comment]
OK, tried to reproduce this cleanly but couldn't either. 

Something did happen, possibly relates to https://github.com/angular/angular-cli/issues/6101.

In any case, closing this until someone manages to reproduce.
(you just beat me to it)

**Comment by shah-smit** [comment]
@amitport I am getting the same error!
