### ISSUE TITLE
ng build -w does not see changes in .ts files

### ISSUE THREAD

**Issue by artpoddybnyy** [angular/angular-cli#6107]
I'm working on a project on different computers, on one of the computers ng build -w does not see changes in .ts files. In html files sees, when i change ts file оccurs rebuild but сhanges do not take effect and hash code rebuild same as before!

**Comment by clydin** [comment]
Please use and fill out the provided issue template.  Without the information we will be unable to provide assistance.

**Comment by stevehouel** [comment]
Same issue on #6092, you should have all information on it.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
