### ISSUE TITLE
Property is private and only accessible within class   -  ANGULAR 4.0.2 and ANGULAR CLI 1.0.0

### ISSUE THREAD

**Issue by jmcsoberano** [angular/angular-cli#6108]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

node: 7.8.0
os: win32 x64
@angular/animations: 4.0.2
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2

### Repro steps.

ng serve --prod
ng build --target=production

### The log given by the failure.

** NG Live Development Server is running on http://localhost:4200 **
Hash: 3071d6f09df59f02e1f2
Time: 104994ms
chunk    {0} main.122b50d0f5d7273a07b7.bundle.js (main) 2.65 MB {4} [initial] [rendered]
chunk    {1} polyfills.4c21eef50ed17035194d.bundle.js (polyfills) 158 kB {5} [initial] [rendered]
chunk    {2} scripts.3e5462ba4a6ac843db5c.bundle.js (scripts) 168 kB {5} [initial] [rendered]
chunk    {3} styles.d050faff9c5ce0fd798a.bundle.css (styles) 175 bytes {5} [initial] [rendered]
chunk    {4} vendor.e57b46e39823dfdef121.bundle.js (vendor) 3.19 MB [initial] [rendered]
chunk    {5} inline.42db1f3e0c40a6c88ded.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/login/login.component.html (14,31): Property 'auth' is private and only accessible within class 'LoginComponent'.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/page/page.component.html (151,14): Property 'auth' is private and only accessible within class 'PageComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/page/page.component.html (83,21): Property 'auth' is private and only accessible within class 'PageComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/page/page.component.html (162,5): Property 'auth' is private and only accessible within class 'PageComponent'.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/inscripciones/inscripciones.component.html (13,28): Property 'listFilter' does not exist on type 'InscripcionesComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/inscripciones/inscripciones.component.html (4,5): Property 'listFilter' does not exist on type 'InscripcionesComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/inscripciones/inscripciones.component.html (13,9): Property 'listFilter' does not exist on type 'InscripcionesComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/inscripciones/inscripciones.component.html (4,5): Property 'pageTitle' does not exist on type 'InscripcionesComponent'.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/cobro/cobro.component.html (31,15): Property 'alumnosData' is private and only accessible within class 'CobroComponent'.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/facturas/facturas.component.html (12,28): Property 'listFilter' does not exist on type 'FacturasComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/facturas/facturas.component.html (4,5): Property 'listFilter' does not exist on type 'FacturasComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/facturas/facturas.component.html (12,9): Property 'listFilter' does not exist on type 'FacturasComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/facturas/facturas.component.html (4,5): Property 'pageTitle' does not exist on type 'FacturasComponent'.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/pagos/pagos.component.html (13,28): Property 'listFilter' does not exist on type 'PagosComponent'.
C:/git/zenkotec/CRM2/CRM/CRM/src/$$_gendir/app/process/pagos/pagos.component.ngfactory.ts (1,1): Property 'listFilter' does not exist on type 'PagosComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/pagos/pagos.component.html (13,9): Property 'listFilter' does not exist on type 'PagosComponent'.
C:/git/zenkotec/CRM2/CRM/CRM/src/$$_gendir/app/process/pagos/pagos.component.ngfactory.ts (1,1): Property 'pageTitle' does not exist on type 'PagosComponent'.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/catalog/modalidades/modalidades.component.html (30,51): Supplied parameters do not match any signature of call target.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/catalog/niveles/niveles.component.html (30,51): Supplied parameters do not match any signature of call target.

ERROR in C:/git/zenkotec/CRM2/CRM/CRM/src/$$_gendir/app/catalog/profesores-imagenes/profesores-imagenes.component.ngfactory.ts (1,1): Property 'profesores' does not exist on type 'ProfesoresImagenesComponent'.

ERROR in C:/git/zenkotec/CRM2/CRM/CRM/src/$$_gendir/app/catalog/calificaciones/calificaciones.component.ngfactory.ts (1,1): Property 'type' does not exist on type 'CalificacionesComponent'.

ERROR in C:/git/zenkotec/CRM2/CRM/CRM/src/$$_gendir/app/catalog/direccion/direccion.component.ngfactory.ts (1,1): Property 'type' does not exist on type 'DireccionComponent'.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/page/page.component.html (151,14): Property 'auth' is private and only accessible within class 'PageComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/page/page.component.html (83,21): Property 'auth' is private and only accessible within class 'PageComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/page/page.component.html (162,5): Property 'auth' is private and only accessible within class 'PageComponent'.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/catalog/modalidades/modalidades.component.html (30,51): Supplied parameters do not match any signature of call target.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/catalog/niveles/niveles.component.html (30,51): Supplied parameters do not match any signature of call target.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/inscripciones/inscripciones.component.html (13,28): Property 'listFilter' does not exist on type 'InscripcionesComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/inscripciones/inscripciones.component.html (4,5): Property 'listFilter' does not exist on type 'InscripcionesComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/inscripciones/inscripciones.component.html (13,9): Property 'listFilter' does not exist on type 'InscripcionesComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/inscripciones/inscripciones.component.html (4,5): Property 'pageTitle' does not exist on type 'InscripcionesComponent'.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/cobro/cobro.component.html (31,15): Property 'alumnosData' is private and only accessible within class 'CobroComponent'.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/facturas/facturas.component.html (12,28): Property 'listFilter' does not exist on type 'FacturasComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/facturas/facturas.component.html (4,5): Property 'listFilter' does not exist on type 'FacturasComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/facturas/facturas.component.html (12,9): Property 'listFilter' does not exist on type 'FacturasComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/facturas/facturas.component.html (4,5): Property 'pageTitle' does not exist on type 'FacturasComponent'.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/pagos/pagos.component.html (13,28): Property 'listFilter' does not exist on type 'PagosComponent'.
C:/git/zenkotec/CRM2/CRM/CRM/src/$$_gendir/app/process/pagos/pagos.component.ngfactory.ts (1,1): Property 'listFilter' does not exist on type 'PagosComponent'.
ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/process/pagos/pagos.component.html (13,9): Property 'listFilter' does not exist on type 'PagosComponent'.
C:/git/zenkotec/CRM2/CRM/CRM/src/$$_gendir/app/process/pagos/pagos.component.ngfactory.ts (1,1): Property 'pageTitle' does not exist on type 'PagosComponent'.

ERROR in ng:///C:/git/zenkotec/CRM2/CRM/CRM/src/app/login/login.component.html (14,31): Property 'auth' is private and only accessible within class 'LoginComponent'.

ERROR in C:/git/zenkotec/CRM2/CRM/CRM/src/$$_gendir/app/catalog/calificaciones/calificaciones.component.ngfactory.ts (1,1): Property 'type' does not exist on type 'CalificacionesComponent'.

ERROR in C:/git/zenkotec/CRM2/CRM/CRM/src/$$_gendir/app/catalog/direccion/direccion.component.ngfactory.ts (1,1): Property 'type' does not exist on type 'DireccionComponent'.
webpack: Failed to compile.

### Mention any other details that might be useful.

With this ng serve everything works fine, but when you place it ng serve --prod is where it is detailed

**Comment by ctrl-brk** [comment]
Production build uses ahead of time compilation and for that to work all properties used in templates must be public. You can try to build without AOT by using `ng build -prod --aot=false`

**Comment by sumitarora** [comment]
Closing as above.

**Comment by jmcsoberano** [comment]
# **Thank you very much for the support ... solved**

**Comment by harshasaha** [comment]
I need to build with AOT, Because it reduces the loading time but getting the error while building with AOT, is there any solution to build with AOT?
