### ISSUE TITLE
The selector "my-app" did not match any elements

### ISSUE THREAD

**Issue by ryan0270** [angular/angular-cli#6111]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.1
node: 7.7.3
os: linux x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0

### Repro steps.
- Create basic project with 
app.component.ts:
```
import { Component } from '@angular/core';

@Component({
	selector: 'my-app',
	template: `
		<h2>Alive!</h2>
	`
})
export class AppComponent  {
}
```

app.module.ts:
```
import { NgModule} from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }  from './app.component';
@NgModule({
	imports: [
		BrowserModule,
	],
	declarations: [
		AppComponent,
	],
	providers: [
	],
	bootstrap:    [ AppComponent ],
})
export class AppModule { }
```
main.ts:
```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';

platformBrowserDynamic().bootstrapModule(AppModule);
```

.angular_cli.json:
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "web"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "tsconfig": "tsconfig.app.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": []
    }
  ]
}
```
- Run 'ng serve'
- Open localhost:4200 in browser
- Console reports the error 'ERROR: the selector "my-app" did not match any elements'

### The log given by the failure.
see attached log
[browser_log.txt](https://github.com/angular/angular-cli/files/962715/browser_log.txt)

### Desired functionality.
App main page should be displayed without error

### Mention any other details that might be useful.
attached is a minimal package tarbal
[minimal.zip](https://github.com/angular/angular-cli/files/962702/minimal.zip)

**Comment by sumitarora** [comment]
@ryan0270 You didn't change `app-root` in `index.html`. Changing `<app-root>Loading...</app-root>` to `<my-app>Loading...</my-app>` works.
