### ISSUE TITLE
Errors installing @angular/cli 

### ISSUE THREAD

**Issue by FananticCoder** [angular/angular-cli#6113]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Window 7 Professional, Service Pack 1
I tried it on node v6.10.2, npm  v3.10.10
and node v7.9.0, npm  v4.2.0

### Repro steps.

npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@latest

### The log given by the failure.

This is the log I have for using node v6.10.2, npm  v3.10.10:

82218 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fsevents):
82219 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
82220 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
82220 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
82220 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
82220 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
82221 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
82221 verbose stack     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
82221 verbose stack     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
82221 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
82221 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
82221 verbose stack
82221 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
82221 verbose stack     at Error (native)
82222 verbose cwd c:\CLDEV\CLAPP\material2
82223 error Windows_NT 6.1.7601
82224 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli@latest"
82225 error node v6.10.2
82226 error npm  v3.10.10
82227 error path C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli
82228 error code EPERM
82229 error errno -4048
82230 error syscall rename
82231 error Error: EPERM: operation not permitted, rename 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
82231 error     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
82231 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
82231 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
82231 error     at FSReqWrap.oncomplete (fs.js:123:15)
82231 error
82231 error Error: EPERM: operation not permitted, rename 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
82231 error     at Error (native)
82231 error  Error: EPERM: operation not permitted, rename 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
82231 error     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
82231 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
82231 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
82231 error     at FSReqWrap.oncomplete (fs.js:123:15)
82231 error
82231 error Error: EPERM: operation not permitted, rename 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
82231 error     at Error (native)
82232 error Please try running this command again as root/Administrator.
82233 verbose exit [ -4048, true ]

---------------------------------------------------------------------------------------

This is the log I have for using node v7.9.0, npm  v4.2.0:

110270 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fsevents):
110271 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
110272 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
110272 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
110272 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
110272 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
110273 warn Error: EPERM: operation not permitted, lstat 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\mixin-object\node_modules'
110273 warn  { Error: EPERM: operation not permitted, lstat 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\mixin-object\node_modules'
110273 warn   errno: -4048,
110273 warn   code: 'EPERM',
110273 warn   syscall: 'lstat',
110273 warn   path: 'C:\\Users\\fcoder\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\mixin-object\\node_modules' }
110274 verbose Please try running this command again as root/Administrator.
110275 verbose stack Error
110275 verbose stack     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:42:5)
110275 verbose stack     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:31:7)
110275 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
110275 verbose stack     at FSReqWrap.oncomplete (fs.js:114:15)
110275 verbose stack
110275 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
110276 verbose cwd c:\CLDEV\CLAPP\material2
110277 error Windows_NT 6.1.7601
110278 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli@latest"
110279 error node v7.9.0
110280 error npm  v4.2.0
110281 error path C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli
110282 error code EPERM
110283 error errno -4048
110284 error syscall rename
110285 error Error
110285 error     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:42:5)
110285 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:31:7)
110285 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
110285 error     at FSReqWrap.oncomplete (fs.js:114:15)
110285 error
110285 error Error: EPERM: operation not permitted, rename 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
110285 error  Error
110285 error     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:42:5)
110285 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:31:7)
110285 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
110285 error     at FSReqWrap.oncomplete (fs.js:114:15)
110285 error
110285 error Error: EPERM: operation not permitted, rename 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\fcoder\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
110286 error Please try running this command again as root/Administrator.
110287 verbose exit [ -4048, true ]

### Mention any other details that might be useful.

I have done quite a bit of research and tried many combination of different ways like the followings with the v6.10.2 LTS and v7.9.0 latest node but still getting error during the installation.  I have full administrative rights to my PC and when I ran those commands in Administrator mode. Please help. Thanks!

npm uninstall -g @angular/cli
npm cache clean
npm cache -g clean
npm cache -g -f clean
npm install -g @angular/cli
npm install -g @angular/cli@latest
npm install -g -f @angular/cli@latest

**Comment by Equinox** [comment]
>110286 error Please try running this command again as root/Administrator.

You're definitely sure you're running the cmd or whatever shell as administrator? This line would seem to suggest otherwise.

If so, are you able to install anything else via npm or do they error too?

**Comment by FananticCoder** [comment]
Hi Equinox,
Yes, I am definitely sure I am running cmd as administrator and have been using npm without any error in the past. One more note, I installed angular/cli couple months back and it was successful without any error.  This time I was trying to update my angular/cli and I ran into this problem/error.  Thanks!

**Comment by filipesilva** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of project npm or file issue on their issue tracker (https://github.com/npm/npm).

I'm sorry I can't help you more, but Angular CLI doesn't even get installed. Something's breaking down on npm's side.
