### ISSUE TITLE
Feature Request: Ability to lint AOT template warnings/errors before build

### ISSUE THREAD

**Issue by leocaseiro** [angular/angular-cli#6116]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.1
node: 7.5.0
os: darwin x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0
@angular/language-service: 4.1.0

```

### Desired functionality.

Currently, there's a bug (#4252) with ```ng serve --aot```, so I'm not using aot for development. However, I'm gettings lot's of errors and warnings on my `build --prod` that checks for AOT errors (#5623) and quit the build.

I have two git hooks: `ng lint --type-check` and `ng test`, however, the AOT errors are not showing in these steps.

It 'd be good if we could check for these errors (such as `private properties` that are used in the template and should be converted to `public`), before the build process.

I was thinking of something like: `ng lint --aot` or even a new command, like: `ng lint-aot`

**Comment by filipesilva** [comment]
I agree that this would be super useful, but the right repro to ask for it in is https://github.com/mgechev/codelyzer. That's the addon to tslint we use and that implements the Angular specific fules.

**Comment by leocaseiro** [comment]
Hi @filipesilva, thank you for your reply.

I've contacted the author of Codelyzer (@mgechev) and it seems that this issue should be reported by the Angular compiler.

I was wondering what kind of process run before the `ng build` which is where I see all theses warning and bugs. Is there any chances to run the same process in a separate command?

Thanks

**Comment by mgechev** [comment]
@leocaseiro as far as I understand once the issue related to `ng serve --aot` is resolved your feature request will be resolved?

[Here's the issue](https://github.com/mgechev/codelyzer/issues/264) in codelyzer related to removing the rules which are interfering with the compile-time errors supposed to be reported by ngc.

**Comment by leocaseiro** [comment]
Hi @mgechev, 
It would work for the development.

However I'd like to stop the building for someone of my team that didn't use the flag `--aot` in development and I believe a task such as `ng compile-lint` would avoid issues. In my case, I would add as a git hook, avoiding the commits going to master with compile errors.

**Comment by mgechev** [comment]
ngc will become default soon, which means that your team will have the opportunity to use consistent build environment. This way ngc will be responsible for reporting all compile-time errors and the linter will take care of the rest.

**Comment by FabioAntunes** [comment]
Sorry guys, but is there any update on this?

**Comment by xtianus79** [comment]
this would be an awesome feature and something for @ngtools @StephenFluin

**Comment by ianqueue** [comment]
agreed, dealing with dev mode and prod mode/aot is a bear for my development teams who write perfectly good TS, then realize after the fact they did something that makes AOT unhappy due to tree shaking etc. and are just given a horrible error message... 

Also if ngc becomes default, I hope the build time increases as it is sloooooooooow.
