### ISSUE TITLE
Files removed while using GIT and ng serve

### ISSUE THREAD

**Issue by mateuszwitkowski** [angular/angular-cli#6118]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.10.2
os: linux x64
@angular/animations: 4.0.2
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2

### Repro steps.
1. Run ng serve.
2. Change something in one of the components and save (just so code will recompile).
3. Try to discard change with GIT (I'm using SourcTree v. 1.9.10). Action is rejected because file is used by another process (ng serve obviously).
4. Stop CLI server.
5. Hit git status / check in your favourite IDE -> file is deleted.

### Desired functionality.
Angular CLI should not mess with GIT.

### Mention any other details that might be useful.
Sometimes to get an error you need to changes&save several times.

**Comment by ddimaria** [comment]
I don't think this is an angular issue.  How can this be duplicated?

**Comment by filipesilva** [comment]
Angular CLI does not mess with git. The only time it does anything git related is on `ng new`. This sounds like some interaction between editors/sourcetree/cli/filesystem.
