### ISSUE TITLE
ng serve fails to display app after successful build resulting in a 404.

### ISSUE THREAD

**Issue by ebertsch** [angular/angular-cli#6119]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.1
node: 6.10.2
os: win32 x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0
```

### Repro steps.
run `ng serve` in the root directory of an application with a path like `c:\source\organization\my%20project`

Navigate to the default URL. http://localhost:4200.

The application is not displayed instead you see a 404 page from webpack with no other information displayed.

### The log given by the failure.
There is no failure in the cli or from webpack so here is a screen cap of
the site in chrome with developer tools open.

![ng-serve-error](https://cloud.githubusercontent.com/assets/3743344/25530803/9487a6d8-2bf5-11e7-81d9-5caee59bae78.png)

### Desired functionality.
I would expect the CLI to warn the users about using an unsafe path when they run `ng serve`.

### Mention any other details that might be useful.
You can also avoid this issue if you run `ng serve -op c:\temp` even though no files are created. It appears that it fools the cli or webpack into thinking path is okay.

In @angular/cli@1.0.0-rc.1 the project ran fine. It was not until
we upgraded to  @angular/cli@1.0.1 that this was an issue.

I also realized you should try to avoid special characters in paths but Microsoft Visual Studio Team Services for some reason allows you to create projects with spaces which results in projects and paths having special characters in their name.

**Comment by yoannjauffroy** [comment]
+1

**Comment by filipesilva** [comment]
Sounds like a bug alright. Likely related to webpack-dev-server (or how we configure it). Thanks for reporting it!

**Comment by sumitarora** [comment]
Seems to be working fine on Mac but not on windows.

**Comment by filipesilva** [comment]
I've verified this problem outside the CLI and reported it on https://github.com/webpack/webpack-dev-server/issues/915. Once it is fixed there we can update.
