### ISSUE TITLE
@angular/http missing from package.json of newly generated project

### ISSUE THREAD

**Issue by mmrath** [angular/angular-cli#612]
@angular/http missing from package.json of newly generated project

**Comment by aciccarello** [comment]
Did the cli get updated to use the release candidate yet? The imports changed with rc.0

https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02

**Comment by hansl** [comment]
The CLI got updated with the new packages.

We do NOT install packages we don't need. If you need more packages than the one that come by default, you need to `npm install` them. This is a deliberate choice; you might want universal, mobile, and other stuff, or you don't. If you don't then installing them can be a huge cost as the angular add more and more packages.

I'll close this. You should simply run `npm install --save @angular/http`.

**Comment by mmrath** [comment]
@hansl If http is an optional package it should be removed from the generated system-config.ts file?
