### ISSUE TITLE
ng xi18n builds into the dist folder (and can't take environment flag)

### ISSUE THREAD

**Issue by itslenny** [angular/angular-cli#6120]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions

```
@angular/cli: 1.0.0
node: 6.9.1
os: win32 x64
```

### Repro steps.

```
ng build -prod
```
Creates dist folder with normal prod settings (cache busting hashes, etc)

```
i18n --output-path localizations --locale en
```
Adds a main.bundle.js (no hashing) to the dist folder and re-writes index.html to use the non-prod bundle.

### Desired functionality.

**Option A**
`ng xi18n` should not write to the dist folder. If it needs to put file on disk maybe add a `.tmp` folder or something. This seems like the most intuitive behavior to me as "extract i18n" does not sound like it'd effect your dist folder at all. It should just "extract i18n".

**Option B**

Let `ng xi18n` take all of the `ng build` flags so it could just "kill two birds with one stone" and do the build and localization at once. e.g. `i18n --output-path localizations --locale en -prod` would do the extraction and create a prod build in the `dist` folder. The behavior seems a little counter intuitive, but it would save a step for CI scenarios. Rather than doing extraction (which does an AOT build) and then running another AOT build it could just all happen at once.

Additionally, with this option it should probably delete the dist folder so it's not adding 2 versions of the build to the folder. Currently, if you have an existing prod build it will just add the dev build on top of it and retain all of the unused prod bundles.

**Comment by filipesilva** [comment]
The `xi18n` command is following a different format than the others, which leads to the problems you highlighted. This will require a refactor to fix.

/cc @ocombe

**Comment by ocombe** [comment]
The real ng-xi18n compiles the files with the option `{noEmit: true}` for ngc: https://github.com/angular/angular/blob/master/packages/compiler-cli/src/extract_i18n.ts#L34 which means that it doesn't write tsc files, only the extracted messages.
The api used by the cli is different, it's the cli that does the compilation and then ng-xi18n only does the extraction of the messages.
You could probably add `{noEmit: true}` to the compiler options here: https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/extract_i18n_plugin.ts#L107 and it would do the same (compile in memory but not write the files).

**Comment by MickL** [comment]
This is really annoying :(

**Comment by hansl** [comment]
This has been fixed a long time ago, never marked. If this still happens please create a new issue so we can follow up.
