### ISSUE TITLE
Allow configuration for base path to request asset files.

### ISSUE THREAD

**Issue by jaesung2061** [angular/angular-cli#6121]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.0.1 . 
node: 7.5.0 . 
os: darwin x64

### Repro steps.
My build target is in `./public/assets` directory. The generated files (`*.js`, `*.js.map`, `index.html`) all go into that directory. When the files are generated the script tag urls are like so: `http://example.com/file.js`

### Desired functionality.
I need the script tag urls to be `http://example.com/assets/file.js`. Notice the `/assets/`. This is because `public` is the web root and I'm serving `index.html` through my backend application. Therefore, when they hit `http://example.com`, `index.html` is served even though it's in `http://example.com/assets/index.html`. I apologize if this is confusing, please ask for clarification if needed.

### Mention any other details that might be useful.
http://github.com/jaesung2061/anvel

I currently have it so that the `index.php`, `.htaccess` and other files are copied from the `angular` src directory. Because of https://github.com/angular/angular-cli/pull/4293

**Comment by bviale** [comment]
I think it can be done through the "deployUrl" node of your .angular-cli.json config file.
If you set 
```
"apps": [
    {
      ...
      "deployUrl": "/assets/",
      ...
    }
  ],
```
it should do what you are looking for.
Reference : https://github.com/angular/angular-cli/wiki/angular-cli

**Comment by jaesung2061** [comment]
@bviale thanks :)
