### ISSUE TITLE
Error with "ng serve --prod" (but not "ng serve") on ngUpgrade hybrid app

### ISSUE THREAD

**Issue by scottschafer** [angular/angular-cli#6124]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.9.5
os: darwin x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/upgrade: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.
git clone https://github.com/scottschafer/ng2hybrid.git
cd ng2hybrid
npm install
ng serve --prod

### The log given by the failure.
The browser console log gives "A platform with a different configuration has been created. Please destroy it first."

Note that I don't get this error with just "ng serve". I have played around with calling destroyPlatform(), but that seems to just lead to other areas.

### Desired functionality.
I'd like for ng serve --prod (as well as ng build) to produce functioning code.

**Comment by filipesilva** [comment]
This is a somewhat complicated scenario that'll need some investigation. The problem might be due to how the app is configured, how the upgrade adapter functions when using AOT, or a couple of other factors. I'll have to dig in a bit and figure it out.

Thank you for taking the time to make the repro and opening this issue, much appreciated.

**Comment by filipesilva** [comment]
Heya, I looked around your app a bit and decided to go the other way around: I grabbed some hybrid app code I already knew worked (from the docs), and put it in a CLI app. It seems to work, and you can find it here https://github.com/filipesilva/hybrid-app.
