### ISSUE TITLE
Please add tslint-language-service to dependencies

### ISSUE THREAD

**Issue by angelozerr** [angular/angular-cli#6125]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Mention any other details that might be useful.

Like https://github.com/angular/angular-cli/issues/5497 please add [TSLint Language Service](https://github.com/angelozerr/tslint-language-service) plugin.

And give an option to declare it in the tsconfig.json like this:

```json
{
  "compilerOptions": {
    "plugins": [
      { "name": "tslint-language-service"}
    ]
  }
}
```
This TypeScript plugin can be used with any IDE (VSCode, WebStorm, Eclipse, etc) to provide tslint diagnostic and codefix in your editor.

Thanks!

**Comment by filipesilva** [comment]
Oh sorry, this wasn't fixed by #6144.

**Comment by filipesilva** [comment]
I'm marking this as a discussion though, adding it depends on up to date versions of a lot of things so it's not a cut and dry thing.

**Comment by ValeryVS** [comment]
As far as I know, it depends on `typescript@2.3`. And `@angular/cli@1.1.x` also depends on this typescript version.

I installed package, add lines in tsconfig and disable tslint extension in my vscode.
All seems to be working properly.

**Comment by ValeryVS** [comment]
With `tslint-language-service` it is possible to view errors for rules, that require type checking.
But not all...
For example, I can't see `no-unused-variable` errors in VSCode.

**Comment by angelozerr** [comment]
@ValeryVS the goal of this issue is to integrates tslint-language-service with angular-cli.

https://github.com/angelozerr/tslint-language-service
If you have problems with tslint-language-service, please create issues at https://github.com/angelozerr/tslint-language-service/issues

**Comment by mgechev** [comment]
For now `tslint` without the language service has been sufficient for the CLI. Let's close this feature request for now and revisit in future.
