### ISSUE TITLE
Skip-tests should skip a lot more

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular-cli#6134]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] feature request
```

### Versions.
@angular/cli: 1.0.1
node: 6.10.2
os: win32 x64

### Repro steps.
ng new foo --skip-tests

### Desired functionality.
When the user opts-out from testing it should not create e2e folder, karma.conf and protractor.conf.

**Comment by sumitarora** [comment]
@mbeckenbach `--skip-tests` Is just meant to skip the spec files. Please read more about the same issue here. https://github.com/angular/angular-cli/issues/6054#issuecomment-296747721

**Comment by filipesilva** [comment]
Closing as answered by @sumitarora.

**Comment by nerudaj** [comment]
@sumitarora I would recommend clarifying this on the [wiki](https://github.com/angular/angular-cli/wiki/new). It now says:
```
Skip creating spec files. 
Skip including e2e functionality. 
```
After that I've thought that e2e folder and related stuff will not be created, only to find it does not and subsequently finding this issue. Also at this point there is no way to force not creating this file while maintaining `--inline-template` and `--inline-style` set to false as `--minimal` forces them to enabled.
