### ISSUE TITLE
Confusing docs

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular-cli#6135]
The cli installs ng4 at the moment, so what does this do?

https://github.com/angular/angular-cli/wiki/new

```
ng4
`--ng4` _default value: false_

Create a project with Angular 4 in the template.
```

**Comment by CarreraPHP** [comment]
--ng4 was used earlier to create Angular version 4 project when Cli was supporting Angular version 2 by default.

**Comment by sumitarora** [comment]
@mbeckenbach Change has been made already and pushed to master. Docs need to be published will be done in next release. https://github.com/angular/angular-cli/blob/master/docs/documentation/new.md
