### ISSUE TITLE
Runtime Error Uncaught (in promise): Error: Cannot find module "./pages/login"

### ISSUE THREAD

**Issue by afzal415** [angular/angular-cli#6139]
Hi guys,

  I am new to ionic . Have been trying using Lazy module. I tried all the solution given , still i am getting the same error. I have been sitting with this error for 2 days. Please let me know where i am making mistake.

Runtime Error
Uncaught (in promise): Error: Cannot find module "./pages/login" Error: Cannot find module "./pages/login" at d (http://localhost:8100/build/polyfills.js:3:3991) at Object.261 

Ionic Framework: 3.1.1
Ionic App Scripts: 1.3.6
Angular Core: 4.0.2
Angular Compiler CLI: 4.0.2
Node: 7.4.0
OS Platform: Windows 8.1
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

APP.Module
----------
![image](https://cloud.githubusercontent.com/assets/27876738/25576095/1baa5dfe-2e8f-11e7-90cc-a5aa4195916c.png)

app.component
----------------
![image](https://cloud.githubusercontent.com/assets/27876738/25576116/41c7c468-2e8f-11e7-9b69-6d21b26f45b0.png)

Login.Module
![image](https://cloud.githubusercontent.com/assets/27876738/25576123/5bc5e9e4-2e8f-11e7-88a3-a22e1cbf7bf8.png)

Login.ts
![image](https://cloud.githubusercontent.com/assets/27876738/25576134/7124fdb6-2e8f-11e7-8c13-310f5a7e4057.png)

Providers
![image](https://cloud.githubusercontent.com/assets/27876738/25576246/0b303d9e-2e90-11e7-80a1-3093fdd49297.png)
![image](https://cloud.githubusercontent.com/assets/27876738/25576250/17464380-2e90-11e7-8ade-a4329cd1857a.png)

If i tried changing the root page  in app.component to any other page like RegisterPage or HomePage i am getting cannot find module for that particular Page.

**Comment by sumitarora** [comment]
@afzal415 Is there a repo to look at or if it's private Can you create example replicating the issue?

**Comment by afzal415** [comment]
@sumitarora  Found the mistake, my bad . I was exporting the classes as LoginPage , HomePage and importing it as just Login . Thanks .
