### ISSUE TITLE
Angular CLI dependencies - why do I need to install @angular/router if I don't use it?

### ISSUE THREAD

**Issue by yuriykuzin** [angular/angular-cli#6141]
It is not clear, why do I need @angular/router as a dependency in package.json if I do not use use router and any related imports?

I've created a question with a bigger description and an example on a stackoverflow:
http://stackoverflow.com/questions/43717367/angular-cli-dependencies-why-do-i-need-to-install-angular-router-if-i-dont-u

Thanks in advance! 

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0-rc.1
node: 6.10.1
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/compiler-cli: 2.4.9
@angular/core: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/platform-server: 2.4.9
@angular/forms: 2.4.9
@angular/cli: 1.0.0-rc.1
macOS Sierra

### Repro steps.
Described here: 
http://stackoverflow.com/questions/43717367/angular-cli-dependencies-why-do-i-need-to-install-angular-router-if-i-dont-u

**Comment by hansl** [comment]
Hi @yuriykuzin,

If you don't need `@angular/router`, you can safely remove it from your `package.json` file. We include it by default because most people use it, and it's convenient to have it there.

Cheers!
