### ISSUE TITLE
Integrate postcss with AngularCLI

### ISSUE THREAD

**Issue by mmdsharifi** [angular/angular-cli#6151]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.

 ng -v
,    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.1
node: 6.9.5
os: win32 x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/platform-server: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0

### Mention any other details that might be useful.

Hello guys,

I want to use `postcss` to with Angular CLI to make template RTL via `rtlcss`, I use [this tutorial](https://www.codementor.io/stevebelovarich/compiling-sass-postcss-with-angular-cli-du107x931) guides  but it not worked and this error appear in terminal.

```
PS E:\Work\ng2-admin\ng2-admin-rtl> ng serve

It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and has a lot of improvements including a simpler
workflow, a faster build, and smaller bundles.

To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14

```

any solutions?

**Comment by sumitarora** [comment]
@mmdsharifi Article uses an old version of CLI. Which is why you are getting the error. The current version of CLI uses postcss. If you want to customize it further you can use eject command to eject webpak config and make changes and run the project.

**Comment by filipesilva** [comment]
Closing as answered, thanks @sumitarora !
