### ISSUE TITLE
Nested multiple router outlets

### ISSUE THREAD

**Issue by gtzinos** [angular/angular-cli#6152]
Hello guys,

Thanks for your great job. I am trying to create an app which i need to have multiple templates structure. Inside of each template i will have nested router-outlets. Is there any way to work like this ? Check a live example (https://plnkr.co/edit/GSY4dvSFTOxXZMBgR6lF?p=preview). This code not works cause i can't complete it, just get the vision.

Thank you very much for your time.

**Comment by sumitarora** [comment]
@gtzinos Is there a repo with the project generated from CLI where you are getting this issue.

**Comment by gtzinos** [comment]
Hello @sumitarora i sent you a url of a plnkr project.

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by renyaoxiang** [comment]
https://github.com/angular/angular-cli/issues/6152#issue-225699378

**Comment by renyaoxiang** [comment]
I have the same problem. How to resolve it?
