### ISSUE TITLE
Gradient has outdated direction syntax : Updating to angular final 1.0

### ISSUE THREAD

**Issue by harilalinapp** [angular/angular-cli#6156]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```
Got the "Gradient has outdated direction syntax"  error while running ng serve after updating final.

Is it possible to disable his autoprefixer warning?

### Versions.

@angular/cli: 1.0.1
node: 6.9.1
os: linux x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0

**Comment by filipesilva** [comment]
There's no way to disable this, no. If you can provide a simple repro we can look at that usecase and see what can be done.

**Comment by harilalinapp** [comment]
@filipesilva Thanks for the update. I have changed the css styles to wrk with Autoprefixer
