### ISSUE TITLE
Run Angular CLI tests in parallel

### ISSUE THREAD

**Issue by BustyLoli-Chan** [angular/angular-cli#6157]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

1.0.0

### Desired functionality.

I would like the ability to run multiple component tests in parallel, or just multiple tests in parallel in general. It seems that karma supports the ability to run multiple browsers in parallel, and while I am unaware of whether the current jasmine framework will support it, I think it would be extremely helpful to be able to run the tests within multiple describe blocks at the same time. 

Our entire test suite takes about 5 minutes at this time, and I truly believe that parallel test execution would cut that number down by a lot.

**Comment by filipesilva** [comment]
This feature request is better suited for the https://github.com/karma-runner/karma repo. We just run it in the CLI, and there isn't an existing config item for karma that allows for this functionality.
