### ISSUE TITLE
[BUG]: Error when upgrading a working app to 1.0.1

### ISSUE THREAD

**Issue by Harelebel** [angular/angular-cli#6165]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.1
node: 6.10.2
os: win32 x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/compiler-cli: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1

### Repro steps.

1. Created an app using 1.0.0-rc-beta2 (app works) - https://github.com/Webiks/MapMip/
2. Upgraded angular cli
3. Upgrade all packages
4. Run ng build --prod
5. An error occurs during build

### The log given by the failure.

ERROR in main.82958491e3e733a62d2f.bundle.js from UglifyJs
Unexpected token: name (PositionFormService) [main.82958491e3e733a62d2f.bundle.js:53,6]

ERROR in vendor.46e5cc0d8b51be45d7f4.bundle.js from UglifyJs
Unexpected token: punc ()) [vendor.46e5cc0d8b51be45d7f4.bundle.js:84368,18]

### Desired functionality.

I would expect the build to complete and the dist to be created.

### Mention any other details that might be useful.

This is the working app with the pre 1.0.1 version: https://github.com/Webiks/MapMip/
Upgrading angular-cli reproduces the issue.

**Comment by clydin** [comment]
ES5 output is currently required.  It looks like you're targeting ES6.

**Comment by DanielKucal** [comment]
I am targetting ES5 and get the following error since dependencies upgrade yesterday:
```
ERROR in vendor.47dda95464a1d0c36749.bundle.js from UglifyJs
Unexpected token: name (Codes) [vendor.47dda95464a1d0c36749.bundle.js:75798,6]
```
I have described it wider in https://github.com/AngularClass/angular-starter/issues/1719

**Comment by filipesilva** [comment]
Closing because @Harelebel's seems to have been answered.

@DanielKucal you'll need to away a response on that repo, that doesn't seem to be a CLI issue.
