### ISSUE TITLE
ng build fails after installing socket.io

### ISSUE THREAD

**Issue by gioragutt** [angular/angular-cli#6168]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```
similar issue: [Link](http://stackoverflow.com/questions/43667705/socket-io-angular-cli-cannot-resolve-socket-io-client-package)

### Versions.

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 7.4.1-nightly20170104e07b6516d7
os: win32 x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.0

### Repro steps.

* `ng new project`
* `cd project`
* `npm install --save {@types/,}socket.io` to install socket.io
* in `app.component.ts` add the following:
# `import * as socketIo from 'socket.io'
# in constructor: `const io = socketIo();`
* `ng build`

### The log given by the failure.

Given that the log is huge, I thought maybe a [pastebin](https://pastebin.com/bBU6kckx) would be more reasonable

### Desired functionality.

My usecase is trying to connect to a NodeJs server via `socket.io`. I've managed to do this with a simple `html` file, but I wanted to see how it goes when I wrap the game in an angular application. Inside the project, I have a `game` folder, which has `.ts` files that are the server files, which are compiled separately using `tsc` with a separate `tsconfig.json` file.

What I would like to see implemented is basically allow me to import `socket.io` in Angular. I've seen from googling that this has a lot to do with `webpack` and `3rd party libraries`, but I wanted to raise it here also, seeing that another person (in the top-most link I gave)  had the exact same issue.

### Mention any other details that might be useful.

* If needed, the repo for my project is [angular-socketio-game](https://github.com/gioragutt/angular-socketio-game).
* One issue (I believe that it's the one the prints the huge uglified .js file) can be resolved by going to `node_modules/socket.io/lib/index.js` and changing the line `var clientVersion = require('socket.io-client/package').version;` to `var clientVersion = require('socket.io-client/package.json').version;`.

### EDIT!

Changing the import path from `import * as socketIo from 'socket.io'` to `import * as socketIo from 'socket.io-client'` seems to have solved the problem.

But why wouldn't `socket.io` work as is?

**Comment by filipesilva** [comment]
As far as I can tell, `socket.io` itself is meant to be ran in node enviroments (hence that specific use of require). It won't work at runtime in a browser environment, which is where a SPA runs.

`socket.io-client`, on the other hand, is mean for use in browser environments.
