### ISSUE TITLE
What is the proper way to setup e2e testing?

### ISSUE THREAD

**Issue by jbhue** [angular/angular-cli#6169]
### Issue Category
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### Versions
```
@angular/cli: 1.0.0
node: 6.9.1
os: win32 x64
@angular/animations: 4.0.2
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2
```

### Error Log
```
[09:56:36] I/update - chromedriver: unzipping chromedriver_2.29.zip
[09:56:36] I/update - chromedriver: chromedriver_2.29.exe up to date
[09:56:36] I/launcher - Running 1 instances of WebDriver
[09:56:36] I/direct - Using ChromeDriver directly...
[10964:11880:0503/095637.806:ERROR:configuration_policy_handler_list.cc(92)] Unknown policy: DisableSpdy
[10964:11880:0503/095637.807:ERROR:configuration_policy_handler_list.cc(92)] Unknown policy: DnsPrefetchingEnabled
[10964:11880:0503/095637.807:ERROR:configuration_policy_handler_list.cc(92)] Unknown policy: PasswordManagerAllowShowPasswords
[10964:11880:0503/095637.850:ERROR:configuration_policy_handler_list.cc(92)] Unknown policy: DisableSpdy
[10964:11880:0503/095637.850:ERROR:configuration_policy_handler_list.cc(92)] Unknown policy: DnsPrefetchingEnabled
[10964:11880:0503/095637.852:ERROR:configuration_policy_handler_list.cc(92)] Unknown policy: PasswordManagerAllowShowPasswords
[09:56:40] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'jasmine'. (2688)
Cannot find type definition file for 'node'. (2688)
e2e\app.e2e-spec.ts (3,1): Cannot find name 'describe'. (2304)
e2e\app.e2e-spec.ts (6,3): Cannot find name 'beforeEach'. (2304)
e2e\app.e2e-spec.ts (10,3): Cannot find name 'it'. (2304)
e2e\app.e2e-spec.ts (12,5): Cannot find name 'expect'. (2304)
```

### Desired functionality.

I would like to be able to run `ng e2e` successfully. I am new to typescript and feel I could be falling short setting it up for success. They way I read the error message is typescript can't compile because it can't find the type definition file for jasmine or node. I then went on to install them `npm install --save @types/node` and `npm install --save @types/jasmine`.

After installing them I got the same error log and decided to look at the `tsconfig.json` file in the root of the project folder. I noticed there was not types arrow but there was a typesRoots array. I added the types array and then added node and jasmine to it.

./tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "node",
      "jasmine"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```
I got the same error from doing this. I then saw there are two more files named tsconfig in the /src directory. tsconfig.app.json and tsconfig.spec.json. I added the types array from above into these files and still got the same error. I also noticed that the tsconfig.e2e.json file has the types array.

I have done many searches to attempt to solve this problem on my own. I keep running into issues that seem to be resolved and are from older versions of the CLI. I have looked at the wiki page about "ng e2e" but it doesn't go into depth on how to get it all setup; just the options of the command.

What am I doing wrong? How can I get ng e2e to find the type definition files and run my tests?

**Comment by ctrl-brk** [comment]
This kind of questions are more suitable for stackoverflow.com but what version of @types/jasmine do you have in your package.json? I remember one of them being problematic.

**Comment by jbhue** [comment]
@ctrl-brk you may be right. I guess the reason I posted here is deep down i think there may be some sort of bug or at least an opportunity to add more documentation.

```
"@types/jasmine": "^2.5.38"
"@types/node": "^6.0.71"
```

**Comment by ctrl-brk** [comment]
Here's mine:
    "@types/node": "7.0.14",
    "@types/jasmine": "2.5.47"

**Comment by filipesilva** [comment]
Heya @jbhue, I'm not sure if your project has been updated a couple of times or not, but you seem to have ended up with a bad compo of dependencies. Some of the jasmine typings, as @ctrl-brk mentioned, don't work.

My advice is to have a look at https://github.com/angular/angular-cli/wiki/stories-1.0-update#packagejson, and maybe try generating a new project which should work properly and copy over the deps.

**Comment by jbhue** [comment]
thanks @ctrl-brk and @filipesilva I'll go ahead and do those things.
