### ISSUE TITLE
Runtime error with symbol aliases from typings file

### ISSUE THREAD

**Issue by elekktrisch** [angular/angular-cli#6172]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

Potentially related:
- #2034

### Versions.
ng --version
```
@angular/cli: 1.0.1
node: 6.9.1
os: win32 x64
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0
```

### Repro steps.
1. Generate project (ng new)
2. declare module in typings.d.ts: 
```
declare module foo {
  module v1 {
    export interface Bar {
      helloWorld?: string;
    }
  }
}
```
3. Use interface Bar in app.component.ts with a symbol alias:
```
import {Component, Input} from "@angular/core";
import Bar = foo.v1.Bar;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';

  @Input()
  bla: Bar = {};

  constructor() {
    console.log(this.bla);
  }

}
```

### The log given by the failure.
```
Uncaught ReferenceError: foo is not defined
    at Object.116 (app.component.ts:2)
    at __webpack_require__ (bootstrap 1dadfe7…:52)
    at Object.117 (app.component.ts:10)
    at __webpack_require__ (bootstrap 1dadfe7…:52)
    at Object.108 (src async:7)
    at __webpack_require__ (bootstrap 1dadfe7…:52)
    at Object.248 (main.bundle.js:172)
    at __webpack_require__ (bootstrap 1dadfe7…:52)
    at webpackJsonpCallback (bootstrap 1dadfe7…:23)
    at main.bundle.js:1
```

### Desired functionality.
Should work with the alias.

### Mention any other details that might be useful.
- using the "fully-qualified" name of the type (`foo.v1.Bar`) in the app.component makes it work like a charm, even if the symbol alias stays at the top
- using the alias outside of the component works (hence, only when used in the constructor, it reports the stacktrace mentioned above)
- when adding a separate typings file in a different folder, declaring the additional typeRoot seems not to be sufficient. However, adding a `/// <reference path=` to the typings.d.ts helps (even though that seems to be quite inconvenient

This problem is currently the only thing blocking us from using ng cli. Other than that, we managed to replace our entire ui build setup by cli.

**Comment by filipesilva** [comment]
I think I once read about this... that style of import does not seem to be supported by webpack itself. HEre's some more information about that error and workarounds: http://stackoverflow.com/questions/39758237/typescript-module-importing-webpack

It's not something actionable from the CLI itself though, which is why I'm closing the issue.

**Comment by elekktrisch** [comment]
Thanks for the quick reply. Not sure if I understand though, since I tried various styles for imports (or rather aliases). And I believe what I am trying to achieve is quite straight forward, at least after reading the namespace documentation from https://www.typescriptlang.org/docs/handbook/namespaces.html

Note: The exact same thing does work with most of the webpack starter repositories out there. 

The "export module" syntax is deprecated in the latest Typescript version, but also with the "namespace" syntax it fails to execute the tests when using the following setup to reproduce:

1. ng new demo
2. ng generate component child
3. add the child component to the `app.component.ts`:
```
<h1>
  {{title}}
</h1>
<app-child></app-child>
```
4. add some typings namespace to `typings.d.ts`:

```
/* SystemJS module definition */
declare var module: NodeModule;
interface NodeModule {
  id: string;
}

declare namespace foo {
  export interface Bar {
    helloWorld?: string;
  }
}
```
5. add a reference to foo.Bar in the child component:
```
import {Component, Input, OnInit} from '@angular/core';
import Bar = foo.Bar;

@Component({
  selector: 'app-child',
  templateUrl: './child.component.html',
  styleUrls: ['./child.component.css']
})
export class ChildComponent implements OnInit {

  @Input()
  bar: Bar;

  constructor() {
  }

  ngOnInit() {
  }

}
```
6. try executing the tests (`ng test`):
```
15 05 2017 17:51:15.632:INFO [Chrome 58.0.3029 (Windows 7 0.0.0)]: Connected on socket 4II36jRoRHGjr34zAAAA with id 58441844
Chrome 58.0.3029 (Windows 7 0.0.0) ERROR
  Uncaught ReferenceError: foo is not defined
  at webpack:///src/app/child/child.component.ts:2:0 <- src/test.ts:53705

Chrome 58.0.3029 (Windows 7 0.0.0) ERROR
  Uncaught ReferenceError: foo is not defined
  at webpack:///src/app/child/child.component.ts:2:0 <- src/test.ts:53705
```

**Comment by elekktrisch** [comment]
Ok, I guess the world is moving away from supporting namespaces in favor of ES modules. So the most straight forward way is probalby just ditch the namespaces. That way it works fine.
