### ISSUE TITLE
AOT compilation - Parsing pipes with a non-string argument fails

### ISSUE THREAD

**Issue by iliketomatoes** [angular/angular-cli#6174]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.1
node: 7.7.4
os: linux x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/material: 2.0.0-beta.3
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0

Debian GNU/Linux 8.7 (jessie)

### Repro steps.

I'm using the latest version (3.1.0) of an [Angular library used for translating messages, dates and currency amounts](https://github.com/robisim74/angular-l10n). 
This library also implement a pipe that you can use to translate text inside HTML templates like this:

```html
<span>{{ "errors.password.minlength" | translate:lang:{ minlength: 5 } }}</span>
```
This pipe has a legit syntax and it works as expected out of the AOT mode.
It used to work until recently and it would correctly compile in AOT mode too.

AOT compilation doesn't work anymore with the above-given set of dependencies, and I don't know which is the exact dependency (or sub-dependency) that cannot handle this kind of pipes anymore and is causing the error.

I have made a test, wrapping the argument lang into double quotes - e.g. "lang" instead of lang - so that the first argument passed to the **translate** pipe would be a string. Indeed, the error in the AOT compilation disappeared (even though I had a nonfunctioning translation pipe at that point for obvious reasons).

So it's evident that something can't digest pipes with non-string arguments in the AOT compilation.

### The log given by the failure.
```
ERROR in ng:///home/gsoverini/github/angular-test-cli/src/app/+users/settings/password.component.html (7,5): Property 'lang' does not exist on type 'PasswordComponent'.
```

### Desired functionality.

I would expect this kind of pipes to be correctly parsed by the AOT compiler.

**Comment by clydin** [comment]
This does not appear to be a CLI issue and also appears to be a legitimate error.  Is there a "lang" property/variable on PasswordComponent?  The pipe usage shown won't work otherwise.

**Comment by iliketomatoes** [comment]
Sorry, no it doesn't have a lang property, its parent component does have it though, and apparently it's enough for making it work on JIT compilation.

I understand that's the mistake I made. I was misled by the fact that this app was not throwing errors during development, but only during AOT compilation. 

Thank you for your attention.
