### ISSUE TITLE
ng build --prod SCSS error - Syntax Error: Unknown word

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/angular-cli#6175]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

I'm trying to upgrade an ng1 app that used foundation (heavily modified 5.x)  to angular-cli.  I got everything working until I tried to build it.

Something in the pipeline doesn't like the way the Foundation SCSS passed its version number and other information to the javascript.

It seems to be the { braces that are causing the issue.

But I'm actually more concerned with how unhelpful the error message was.

### Versions.

```
$ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.1
node: 7.9.0
os: win32 x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0

```

### Repro steps.

```
$ ng new scss-err --style scss
$ cd scss-err
$ cat > src/app/app.component.scss
/* These comments prevent me from getting error info. */
/* These comments prevent me from getting error info. */
meta.foundation-version {
  font-family: "/{{VERSION}}/";
}

$ ng build --prod
```

### The log given by the failure.

```
$ ng build --prod
Hash: e4d9ed7cfdf78a1f6945
Time: 5741ms
chunk    {0} polyfills.60187f338ba5b0a175a8.bundle.js (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.b837c50ef766c8f16081.bundle.js (main) 679 bytes {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.65f0715c6a79018f843d.bundle.js (vendor) 806 kB [initial] [rendered]
chunk    {4} inline.7cfde260e39232d58c18.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in Child compilation failed:
Module build failed: Unknown word (4:2)


:
Syntax Error: Unknown word (4:2)




ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\snap\ws\scss-err\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

```
### Desired functionality.

The SCSS to compile so the javascript can extract the data it needs from the styles value.

But also, I would like a better error message.  I spent around 1/2 a day just figuring out the error was in SCSS, and another hour or two figuring out what SCSS was the problem.

I'm not sure what the (4:2) lines up to, and nothing in the error message tells me what file the error is in or even what type of file.

### Mention any other details that might be useful.

If you remove the two comment lines in the SCSS file, you can get a better idea of what it's complaining about.

```
$ cat > src/app/app.component.scss
meta.foundation-version {
  font-family: "/{{VERSION}}/";
}

$ ng build --prod
Hash: 55e87c91f855c6b339ac
Time: 5251ms
chunk    {0} polyfills.60187f338ba5b0a175a8.bundle.js (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.b837c50ef766c8f16081.bundle.js (main) 679 bytes {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.65f0715c6a79018f843d.bundle.js (vendor) 806 kB [initial] [rendered]
chunk    {4} inline.7cfde260e39232d58c18.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in Child compilation failed:
Module build failed: Unknown word (2:2)

  1 | meta.foundation-version{font-family:\/{{VERSION}}/}
:
Syntax Error: Unknown word (2:2)

  1 | meta.foundation-version{font-family:\/{{VERSION}}/}


ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\snap\ws\scss-err\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

**Comment by grizzm0** [comment]
Where does {{VERSION}} come from? Are you trying to inject the version from your component or something?

**Comment by james-schwartzkopf** [comment]
I believe it was the place holder that was in the original foundation SCSS before it was modified.  I imagine it was supposed to be replaced by an actual version string in their build process.

I'm not too concerned with the actual error, nothing in my code cares about this particular case other than it has some value.  I can workaround by just setting it to a string that doesn't need any escaping.  I was more concerned with the poor error message, and that it probably shows a class of problem (not sure if the minification removing the quotes is wrong, or the part failing to parse it with unknown word)..

**Comment by filipesilva** [comment]
I agree that the error reporting is kinda bad here. Maybe it's something we can improve on from our side, but it might also be the error reporting given by one of the third party libs down in our pipeline.

**Comment by siddhanttambe** [comment]
Any progress on this?

I'm having the same issue as @james-schwartzkopf , but I am not even getting any specifics about the error.

Hash: bf5f13fc55dcd8b5f943
Time: 27372ms
chunk    {0} polyfills.bf60006aaec36e430fd3.bundle.js (polyfills) 177 kB {4} [in
itial] [rendered]
chunk    {1} main.bd6680bd93fa3aca6765.bundle.js (main) 1.1 kB {3} [initial] [re
ndered]
chunk    {2} styles.21dcdcba35167de851da.bundle.css (styles) 69 bytes {4} [initi
al] [rendered]
chunk    {3} vendor.b7b323411e40e563b03e.bundle.js (vendor) 849 kB [initial] [re
ndered]
chunk    {4} inline.8bb24d7ad94fddd0790d.bundle.js (inline) 0 bytes [entry] [ren
dered]

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in
 'E:\TFS\MyAngularApp\src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

**Comment by siddhanttambe** [comment]
@james-schwartzkopf - I know that this is a hack, but try doing `ng build --prod --aot=false`. That should work for the moment.

**Comment by filipesilva** [comment]
@siddhanttambe your error does not seem the same as the one described in this issue, as this one is related to the SCSS pipeline. Please open a new issue for yours.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
