### ISSUE TITLE
Child Component reload/refresh not working on updates done from events in Parent

### ISSUE THREAD

**Issue by ansuman273** [angular/angular-cli#6178]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

![angular](https://cloud.githubusercontent.com/assets/4735068/25691632/73f08ec0-30ba-11e7-9d3c-1f18e877601c.PNG)

### Repro steps.

I have dashboard component which is the parent one containing few child chart components on it.
In the parent i am handling one event for the child chart component update process. I am able to fetch the update data after hitting the service method and assign to the child components input variable but it's not reflecting the changes. When i reload the page then only it reflects the changes correctly

### Desired functionality.

I want that the child component gets instantly updated after the success of the event.

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
