### ISSUE TITLE
[lint] tslint.json could extend tslint:recommended

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#6179]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
@angular/cli: 1.1.0-beta.0
node: 7.4.0

### Desired functionality.
TSLint has introduced `tslint:recommended` (and `tslint:latest`) for a while, allowing a config to extend the recommended default, and just override a few rules.

It means we could simplify the configuration, and just keep a few overrides that are common in the Angular community.

### Mention any other details that might be useful.

See the recommended set of rules: https://github.com/palantir/tslint/blob/master/src/configs/recommended.ts

I gave it a naive first try, this is how the tslint.json would look like (to keep the configuration really close to the one we have right now):

```json
{
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "extends": "tslint:recommended",
  "rules": {
    "array-type": false,
    "arrow-parens": false,
    "interface-name": false,
    "import-blacklist": [true, "rxjs"],
    "max-line-length": [
      true,
      140
    ],
    "member-access": false,
    "member-ordering": [
      true,
      "static-before-instance",
      "variables-before-functions"
    ],
    "no-console": [
      true,
      "debug",
      "info",
      "time",
      "timeEnd",
      "trace"
    ],
    "no-empty": false,
    "no-inferrable-types": [true, "ignore-params"],
    "no-non-null-assertion": true,
    "no-string-literal": false,
    "no-switch-case-fall-through": true,
    "object-literal-sort-keys": false,
    "ordered-imports": false,
    "one-line": [
      true,
      "check-open-brace",
      "check-catch",
      "check-else",
      "check-whitespace"
    ],
    "quotemark": [
      true,
      "single"
    ],
    "trailing-comma": false,
    "variable-name": false,

    "directive-selector": [true, "attribute", "pr", "camelCase"],
    "component-selector": [true, "element", "pr", "kebab-case"],
    "use-input-property-decorator": true,
    "use-output-property-decorator": true,
    "use-host-property-decorator": true,
    "no-input-rename": true,
    "no-output-rename": true,
    "use-life-cycle-interface": true,
    "use-pipe-transform-interface": true,
    "component-class-suffix": true,
    "directive-class-suffix": true,
    "no-access-missing-member": true,
    "templates-use-public": true,
    "invoke-injectable": true
  }
}
```
If you think it is interesting, I can work on a PR.

**Comment by filipesilva** [comment]
I think this would be a nice addition, because it means less rules for us to keep up to date.

**Comment by laumair** [comment]
@filipesilva Are you working on this? If you aren't I'd like to pick this up.

**Comment by cexbrayat** [comment]
@laumair I already have a PR nearly ready :)

**Comment by laumair** [comment]
@cexbrayat Ah! :+1:

**Comment by fetis** [comment]
Extremely upvote for this. I was very surprised that this's not turned on by default. Have to clean up some shitty code because of it now.

**Comment by mgechev** [comment]
I see that the previous PR didn't make it to master. Does anyone want to give it a try? If there's still interest around this, we'll be happy to merge the PR. Just make sure that you preserve the same `tslint.json` config.

**Comment by cexbrayat** [comment]
@mgechev I can give it a go. Do you mean that at first we need the exact same result as the current config, even if that means taking an opposite choice than the recommended set?

For example, we currently don't enforce `adjacent-overload-signatures`, whereas the recommended set does. That means we'll have to set `adjacent-overload-signatures: false` in the config if we extend the recommended set. What do you think?

**Comment by mgechev** [comment]
@cexbrayat yes, this would be ideal.
