### ISSUE TITLE
ng serve fails due to watchman failure

### ISSUE THREAD

**Issue by ehzShelter** [angular/angular-cli#618]
.  Linux (xenial xerus). 

ehz@ubuntu(~): ng --version
(node:1862) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 0.0.37
node: 6.0.0
os: linux x64

I am running linux in VMware workstation 12(hypervisor)

May be the issue with watcher , with backtracking files (recursively)

I have allocated enough memory but don't why it fails...

I think  the problem with this cli...Beacuse Angularquickstart from augular.io just works fine..

ehz@ubuntu(~/angularSecond):(master) ng serve
(node:1679) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 8934ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
BroccoliTypeScriptCompiler                    | 6507ms              
vendor                                        | 1520ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
BroccoliTypeScriptCompiler (1)                | 6507ms              
vendor (1)                                    | 1520ms              

[sane] Warning: Lost connection to watchman, reconnecting..
[sane] Warning: Lost connection to watchman, reconnecting..
[sane] Warning: Lost connection to watchman, reconnecting..
[sane] Warning: Lost connection to watchman, reconnecting..
A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1462327545: inotify-add-watch(/home/ehz/angularSecond/node_modules/angular-cli/node_modules/systemjs-builder/node_modules/babel-core/node_modules/minimatch) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch

Error: A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1462327545: inotify-add-watch(/home/ehz/angularSecond/node_modules/angular-cli/node_modules/systemjs-builder/node_modules/babel-core/node_modules/minimatch) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch

    at BunserBuf.<anonymous> (/home/ehz/angularSecond/node_modules/angular-cli/node_modules/angular-cli/node_modules/sane/node_modules/fb-watchman/index.js:95:23)
    at emitOne (events.js:96:13)
    at BunserBuf.emit (events.js:188:7)
    at BunserBuf.process (/home/ehz/angularSecond/node_modules/angular-cli/node_modules/angular-cli/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:289:10)
    at /home/ehz/angularSecond/node_modules/angular-cli/node_modules/angular-cli/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:244:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

![hey](https://cloud.githubusercontent.com/assets/12381692/15003697/86bfaedc-11d0-11e6-8903-763b4c962a1e.png)

**Comment by mackelito** [comment]
Upgrade to latest angular-cli.. Should work there

**Comment by ehzShelter** [comment]
:+1:
