### ISSUE TITLE
webpack-dashboard support

### ISSUE THREAD

**Issue by tamascsaba** [angular/angular-cli#6182]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
Add [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard) to ng serve like this:

```ng serve --dashboard```
``` ng serve --host 0.0.0.0 --port 4201 --dashboard```

Default no use dashboard.

**Comment by filipesilva** [comment]
This isn't something we're looking at adding. It would be a nice community addon in the upcoming addon system though.
