### ISSUE TITLE
ng generate should use tslint configuration

### ISSUE THREAD

**Issue by NCC1701M** [angular/angular-cli#6192]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
|Software|Version|
|--------|-------|
|@angular/cli|1.0.2|
|node|7.10.0|
|os|win32 x64|
|@angular/animations|4.1.1|
|@angular/common|4.1.1|
|@angular/compiler|4.1.1|
|@angular/core|4.1.1|
|@angular/forms|4.1.1|
|@angular/http|4.1.1|
|@angular/material|2.0.0-beta.3|
|@angular/platform-browser|4.1.1|
|@angular/platform-browser-dynamic|4.1.1|
|@angular/platform-server|4.1.1|
|@angular/router|4.1.1|
|@angular/cli|1.0.2|
|@angular/compiler-cli|4.1.1|

### Repro steps.
Execute
`ng generate component test --module=app.module --spec=false`

### Behavior
When you open test.component.ts the indention is set to space and the strings are surrounded by '
In my tslint.json I set the following (extraction):
````json
{
   "indent": [
      true,
      "tabs"
   ],
   "quotemark": [
      true,
      "double"
   ],
}
````

### Desired functionality.
ng generate should - at least (further settings are also welcome) - use the indention and quotemarks that are configured in tslint.

**Comment by filipesilva** [comment]
@clydin has suggested a similar approach, to automatically use tslints fix option on generated files according to a option/flag.

I think that's a good compromise for these stylistic issues.

**Comment by NCC1701M** [comment]
@filipesilva  But tslint doesn't fix indent issues. This must do be done manually and this isn't optimal. Optimal would be some kind of configuration which would be used by ng generate. tslint.json already offers this configuration.

**Comment by clydin** [comment]
Not completely ideal, but most editors offer a formatting option to quickly handle whitespace issues.

With the referenced PR, `ng generate` will transparently transform the created/modified files based on a tslint.config.  However, as you said, it is limited to what tslint can currently fix.
I'd suggest raising an issue over at [tslint](https://github.com/palantir/tslint/issues) for a feature request to provide fix support for the indent rule.  If implemented, any downstream user of tslint would benefit; including the CLI.

**Comment by NCC1701M** [comment]
@filipesilva @clydin But then should - at least - ng generate call tslint on the newly generated ts files otherwise the developer had to do it for each file.

**Comment by clydin** [comment]
The referenced PR (#6213) essentially does what you're suggesting and will be included in an upcoming version.
