### ISSUE TITLE
"Error encountered resolving symbol values statically" for simple function on @Component style attribute

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/angular-cli#6194]
### Bug Report or Feature Request (mark with an `x`)

- [x] bug report
- [ ] feature request

### Versions.

@angular/cli: 1.0.2
node: 7.9.0
os: darwin x64
@angular/animations: 4.1.1
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.1

### Repro steps.

```
import { getStyles } from './util';

@Component({
    template: '<div></div>',
    styles: getStyles('foo')
})
export class SampleComponent {

}
```

### The log given by the failure.

You get an error:

```
[Angular] Error encountered resolving symbol values statically. Calling function 'getStyles', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
```

The thing is that AoT can actually work with this, but in order for the CLI to stop complaining about it, I need to put `foo` in another module and import it like this:

```
// in foo, we have export const foo = getStyles('foo');
import { foo } from './foo';

@Component({
    template: '<div></div>',
    styles: foo
})
export class SampleComponent {

}
```

So, unless I am mistaken, setting the `styles` attribute to the result of a function should not be an error and the CLI should allow this.

### Desired functionality.

I should be able to do this:

```
import { getStyles } from './util';

@Component({
    template: '<div></div>',
    styles: getStyles('foo')
})
export class SampleComponent {

}
```

### Mention any other details that might be useful.

I asked @Brocco about this issue he said something to the effect of "wow, Jeff, that is a really serious issue that I would love to fix for you. just add a GitHub issue with the details and I will have a PR submitted by the end of the day."

Thanks, Mike. You da man.

In all seriousness, though, this is actually a pretty big deal for enabling CSS in JS solutions that are catered specifically for Angular.

**Comment by jeffwhelpley** [comment]
Closed b/c this is a core issue. Opening something there.

**Comment by filipesilva** [comment]
@jeffwhelpley can you link it here as well, so people with the same question can follow it?

**Comment by jeffwhelpley** [comment]
Yes, @filipesilva I created this: https://github.com/angular/angular/issues/16584
