### ISSUE TITLE
If yarn is available and package manager is "default", Yarn should be preferred as default

### ISSUE THREAD

**Issue by Trion129** [angular/angular-cli#6197]
### Bug Report or Feature Request
```
- [ ] bug report
- [x] feature request
```

### Versions.

```
@angular/cli: 1.0.2
node: 6.10.3
os: linux x64
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.1
```

### Repro steps.

I installed angular/cli and ran `new` command. It initialised the project but it used npm by default. I thought maybe it cannot detect yarn but at end of installation `You can 'ng set --global packageManager=yarn'` appeared. So I got an idea that it would be better if the yarn detection functionality was used before defaulting to npm

### The log given by the failure.

```
Successfully initialized git.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
You can `ng set --global packageManager=yarn`.
Project 'starter' successfully created.
```

### Desired functionality.

```
Successfully initialized git.
Default package manager selected as yarn.
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
You can `ng set --global packageManager=npm` if you prefer npm.
Project 'starter' successfully created.
```

### Mention any other details that might be useful.

I would like to contribute fix to this issue myself, might also make my ts skills better. This is a low priority thing but adding might save bandwidth and extra commands for many devs.

Also would it be ok to prefer yarn > cnpm > npm as default?

**Comment by filipesilva** [comment]
This is a matter of user preference really, I don't think the CLI should try to infer preference but rather allow different options.
