### ISSUE TITLE
Add a switch to allow a component, service etc to implement an interface / extend a base class etc

### ISSUE THREAD

**Issue by williamBurgeson** [angular/angular-cli#6200]
Enhancement: Add a switch to allow a component, service etc to implement an interface / extend a base class etc

This could even examine the base class or interface and stub out any members as required.

I am specifically thinking along the lines of the functionality in Visual Studio which does this for C#

**Comment by filipesilva** [comment]
This is fairly complex behaviour that our blueprint setup does not currently support. In the future we should have a costumizable blueprint system that allows users to add this sort of stuff.
