### ISSUE TITLE
Initial JavaScript-Function should wait for the DOM to be ready before searching for the root-component

### ISSUE THREAD

**Issue by DrMueller** [angular/angular-cli#6205]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues befre submitting
- [x ] feature request
```

### Versions.
@angular/cli: 1.0.1
node: 6.9.1
os: win32 x64

### Desired functionality.
Visual Studio Services Extensions currently allow only to add Javascript in their headers.
See this discussion: http://stackoverflow.com/questions/43766463/vsts-extension-with-angular2
And my Repo with a test: https://github.com/DrMueller/Ng-Vsts

Unfortunately, this doesn't work with the Angular-CLI JavaScript packages, since they expect the DOM to be loaded, throwing an error because the logic doesn't find the root-component.

I would like like the JavaScript to listen to the DOM-Ready event, before starting to search for the root.

**Comment by Meligy** [comment]
You can change the bootstrapping code in the `src/main.ts` file from:

```typescript
platformBrowserDynamic().bootstrapModule(AppModule);
```

```typescript
document.addEventListener('DOMContentLoaded', () => {
  platformBrowserDynamic().bootstrapModule(AppModule);
});
```

**Comment by filipesilva** [comment]
Closed as answered by @Meligy, thank you!
