### ISSUE TITLE
cli command not working 

### ISSUE THREAD

**Issue by chkashif167** [angular/angular-cli#6206]
https://www.screencast.com/t/w4qT61dPJC
I ran this command 3 hours ago and still waiting response
what is issue with this?

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by RicardoVaranda** [comment]
@chkashif167 This sounds like an issue with your connection with npm, are you able to install any other packages?

**Comment by filipesilva** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of project https://github.com/npm/npm or file issue on their issue tracker.
