### ISSUE TITLE
Possible issue:  should the  "types": [] be included in the tsconfig.app.ts

### ISSUE THREAD

**Issue by daBishMan** [angular/angular-cli#6208]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.2
node: 7.7.4
os: win32 x64
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.1

### Repro steps.

Create a new project using the CLI.  
add types to the project, for example (    "@types/googlemaps": "^3.26.11",)
when you try to use the google maps types in your code cli complains in about google maps not found.

### Desired functionality.

from https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
- By default all visible “@types” packages are included in your compilation. 
- Specify "types": [] to disable automatic inclusion of @types packages.

Removing the   "types": [] from tsconfig.app.ts solves the error, keeping it, will require declare var google: any; to be declared in your component to use the types, which is not type safe.

Am I missing something or we should not include in tsconfig.app.ts when we create a new project?

**Comment by clydin** [comment]
The intent is for types to be opt-in for the app.  The types needed would be added to the empty array.  This prevents types necessary to unit and e2e testing from being erroneously included within the app (e.g., node or jasmine typings).

**Comment by daBishMan** [comment]
so I would the types for google maps in this array?

**Comment by filipesilva** [comment]
@daBishMan yes, like so: `types:[ "@types/googlemaps"]`.

Leaving them opt-in is better for setups where a single project supports multiple apps, and they use different typings. In the case of the CLI, there are 3 apps (e2e, app, specs) and each of them really shouldn't automatically have access to the other's typings (e.g. your app should use `describe`, only specs should).
