### ISSUE TITLE
Allow chunk name in loadChildren path

### ISSUE THREAD

**Issue by lekhnath** [angular/angular-cli#6210]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.

Node v6.9.5
NPM v3.10.10

### Repro steps.

```
  {
    path: 'lazy',
    loadChildren: 'app/lazy/lazy.module#LazyModule?chunkName=Lazy'
  }
```

### The log given by the failure.

"LazyModule?chunkName=Lazy is not an NgModule"

### Desired functionality.

`angular-router-loader` allows to specify lazy loaded chunk name as **`#LazyModule?chunkName=Lazy`**, which helps to identify the specific lazy loaded chunk in webpack. As this syntax is not allowed by @ngtools/webpack it breaks the compilation process when build for production.  If the chunk name information is not necessary for this tool it can simply extract the module name and ignore the rest of it?

### Mention any other details that might be useful.

https://github.com/brandonroberts/angular-router-loader/blob/master/docs/options.md#chunkname-require-loader-only

**Comment by filipesilva** [comment]
This could be nice, but I don't think it's a good idea to add. It's more code to maintain that is very specific to another loader. Since that is a specific feature of that loader, it's better to just stop using it when you change loaders.
