### ISSUE TITLE
Getting Error while configuring angular after installing angular CLI , attached is the log file

### ISSUE THREAD

**Issue by abhishekkmr71** [angular/angular-cli#6211]
### Getting below error while executing command "ng new my-dream-app"
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "--quiet" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\sysName\AppData\Local\Temp\npm-6532-c
da04632\registry.npmjs.org\_40angular\core\-\core-4.1.1.tgz
npm ERR! Expected: 1230645c842f8a6a050403d4947f982e7ef70c60
npm ERR! Actual:   e80740e6aabf0902f37fd7cc91d881af6617c9e9
npm ERR! From:     https://registry.npmjs.org/@angular/core/-/core-4.1.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Angular\Angular2\first\first\npm-debug.log
```

### Versions.
 
Output from: `ng --version`. : error
   node v6.10.3
  npm  v3.10.10
Windows 7
 

### Repro steps.
 
to Reproduce just install angular CLI and then setup angular for the application using command "ng new 
 {app name}"
 

### The log given by the failure.(attached the log file)
[npm-debug.txt](https://github.com/angular/angular-cli/files/981822/npm-debug.txt)

**Comment by filipesilva** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of project https://github.com/npm/npm or file issue on their issue tracker.
