### ISSUE TITLE
Extend lint task for tslint type checking

### ISSUE THREAD

**Issue by CSchulz** [angular/angular-cli#6215]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
@angular/cli: 1.1.0-beta.0
node: 6.9.5
os: win32 x64
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.1.0-beta.0
@angular/compiler-cli: 4.1.1
tslint: 5.2.0

### Desired functionality.
Some newer rules of tslint 5 requires type info. This can be enabled by type checking of tslint https://palantir.github.io/tslint/usage/type-checking/

There is a need to adjust the `createProgram` method in https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/tasks/lint.ts#L33

**Comment by filipesilva** [comment]
You can do `ng lint --type-check`, does that not suffice?

**Comment by CSchulz** [comment]
I am sorry I had only checked the changelog and searched for type checking.

It is already fixed https://github.com/angular/angular-cli/commit/bab9a565514d600873d72c30e1136816650caf1e
