### ISSUE TITLE
noUnusedLocals: true in tsconfig makes AoT compilation fail

### ISSUE THREAD

**Issue by cacogr** [angular/angular-cli#6223]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.2
node: 6.10.0
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.2
@angular/compiler-cli: 2.4.10

primeng: 2.0.6

### Repro steps.
Having imported in your code any of the offending modules, run `ng build --prod`

### The log given by the failure.
Lots of errors like this one for different components:
```
ERROR in D:/XXXXX/src/$$_gendir/node_modules/primeng/components/common/shared.ngfactory.t
s (883,11): 'parentRenderNode' is declared but never used.
```

### Desired functionality.
To not complain about third-party modules, only check own code. This was working fine in CLI beta.32

**Comment by cacogr** [comment]
It looks like this is not happening anymore after upgrading to angular 4

**Comment by filipesilva** [comment]
Heya @cacogr, this might have been a bug in either the AOT compiler or TypesScript itself. It doesn't sound intentional. If you can't use 4.0 but still need this fixed, please open an issue in https://github.com/angular/angular.

**Comment by cacogr** [comment]
It looks like this is not happening anymore after upgrading to angular 4
