### ISSUE TITLE
Angular4 webpack build error

### ISSUE THREAD

**Issue by surajpoddar16** [angular/angular-cli#6224]
Hi, I was trying to add AOT feature along with JIT. I am using webpack to bundle my app. So I followed the steps mentioned in https://angular.io/docs/ts/latest/guide/universal.html

Now, when I am trying to create a normal build without AOT, I am getting the following error.

94% asset optimization                                                       y [at-loader] Checking started in a separate process...

[at-loader] Checking finished with 2 errors
chunk    {0} vendor.js (vendor) 2.65 MB {2} [initial] [rendered]
chunk    {1} app.js, app.css (app) 2.94 kB {0} [initial] [rendered]
chunk    {2} polyfills.js (polyfills) 575 kB [entry] [rendered]

ERROR in [at-loader] ./src/main-aot.ts:2:36 
    TS2307: Cannot find module '../aot/src/app/app.module.ngfactory'.

ERROR in [at-loader] ./src/main-aot.ts:4:3 
    TS2304: Cannot find name 'enableProdMode'.
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 323 bytes [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 1.97 kB [entry] [rendered]
webpack: Failed to compile.

Since, I have not specified main-aot.ts as entry point in webpack config, I am unable to understand why it is still being accessed. This resolves when I delete main-aot.ts

**Comment by filipesilva** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the https://github.com/angular/angular.io project or file an issue on their issue tracker.

**Comment by surajpoddar16** [comment]
Yeah, the problem seems to be with at-loader, I am looking for the solution. Thanks anyways
