### ISSUE TITLE
Integration of ng2-webcam  Failed to compile

### ISSUE THREAD

**Issue by bimal72** [angular/angular-cli#6226]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.1
node: 7.7.4
os: win32 x64
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/compiler-cli: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/platform-server: 4.0.0

### Repro steps.

```
npm install ng2-webcam --save
```
Add this ng2-webcam dependancy in app.module.ts

```
import { WebCamComponent } from 'ng2-webcam';
...
@NgModule({
  declarations: [
    AppComponent,
    WebCamComponent
  ],
 ....
})
export class AppModule { }
```
On ``` ng serve ``` it fails to compile and throws the following error:

### The log given by the failure.

```
Failed to compile.

./~/ng2-webcam/lib/fallback/jscam.swf
Module parse failed: f:\projects\edu\hops\webcam\node_modules\ng2-webcam\lib\fallback\jscam.swf Unexpected character '' (1:3)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/ng2-webcam/index.ts 4:0-34
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

### Desired functionality.

It should load .swf file as dependency.

**Comment by clydin** [comment]
The package is doing several things that are not recommended for an Angular library:
* publishing typescript source (especially source that requires webpack with a specific config)
* not exposing NgModule(s) representing the libraries functionality
* not adding peerDependencies for the angular packages and versions used

**Comment by filipesilva** [comment]
It also seems to be directly importing a `.swf` file, which isn't standard by any means. My advice is to open an issue on their issue tracker about these problems.
