### ISSUE TITLE
CI: take care of yarn.lock

### ISSUE THREAD

**Issue by ishitatsuyuki** [angular/angular-cli#6237]
```
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```

So the solution is run Travis build with the `--frozen-lockfile` option on `yarn [install]`, and fail if it's outdated. Otherwise the lockfile would be useless...

**Comment by ishitatsuyuki** [comment]
@filipesilva mind adding `--frozen-lockfile`?

**Comment by filipesilva** [comment]
I'm sorry, I don't follow. Where are you seeing that error?

**Comment by ishitatsuyuki** [comment]
It was outdated before dbbede8. I closed the PR as it was no longer outdated with the commit. However, we should validate the lockfile in CI so nobody would forget to update it again.

**Comment by filipesilva** [comment]
I don't really see that option documented in https://yarnpkg.com/en/docs/cli/install, nor it seems to be used in https://github.com/angular/angular/. 

What does it do, and how does it help?

**Comment by ishitatsuyuki** [comment]
Try `yarn install --help`.

It prevents lockfile from being written, thus requiring an up to date yarn.lock.
What's more, from my experience, the CI cache will be invalidated too if an outdated lockfile is there.

**Comment by filipesilva** [comment]
Ok, thank you for the explanation. I see how that's useful. I'll add a PR.
