### ISSUE TITLE
Primeng's styles config is not working

### ISSUE THREAD

**Issue by agasbzj** [angular/angular-cli#6249]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

angular-cli 1.0.2
Windows 7/10
macOS Sierra

### Repro steps.

When intergrating Primeng, the primeng's styles are not included.
You can easily reproduce it by building the primeng's [official example](https://github.com/primefaces/primeng-quickstart-cli).

My styles config in .angular-cli.json is:
```json
"styles": [
        "styles.scss",
        "../node_modules/primeng/resources/primeng.min.css",
        "../node_modules/primeng/resources/themes/omega/theme.css",
        "../node_modules/font-awesome/css/font-awesome.min.css"
      ],
```

### Desired functionality.

I don't know it's the problem of angular-cli's build script or primeng's. Please indicate a way to solve this. Thanks.

**Comment by filipesilva** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the primefaces/primeng-quickstart-cli project or file an issue on their issue tracker.
