### ISSUE TITLE
Hope app can run and visit a url with parameters after index.html

### ISSUE THREAD

**Issue by junjunruan** [angular/angular-cli#6258]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.0.2
node: 6.10.1
os: darwin x64

### Desired functionality.

I migrated my app to use angular-cli, when run the app, I hope it can visit the url like: `https://localhost:3000/index.html?debug=true`, which means I need to add parameter after index.html. 

Before switching to angular-cli, I used systemjs for modular and lite-server to serve my app, so I have these code in bs-config.json file:
```
{
    "startPath": "index.html?debug=true",
    "https": true
}
```
After migrate to angular-cli, I tried to put `"index": "index.html?debug=true",` in .angular-cli.json configuration file and `"start": "ng serve --ssl --port 3000 --open"` in package.json. However, It won't do what I want. It just opens this website: `https://localhost:3000/`, I need to manually add `?debug=true` after the url every time.

**Comment by filipesilva** [comment]
The `index` entry in `.angular-cli.json` is merely to specify the file, and not the url opened when you do `--open`. There is no facility to automatically open a custom url, this is something you will have to do yourself.

**Comment by junjunruan** [comment]
@filipesilva How can I do by myself? Can you give me some advice and examples?

**Comment by junjunruan** [comment]
I end up putting debug flash into the environmental files, instead of adding it at the end of index.html url.
