### ISSUE TITLE
dependencies pulled by project generated with @angular/cli@1.0.2 fail yarn check

### ISSUE THREAD

**Issue by entzik** [angular/angular-cli#6259]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.2
node: 6.10.2
os: darwin x64
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.1

### Repro steps.
- install @angular/cli 1.0.2
- configure angular cli to install packages with yarn
- run "ng new FooBar"
- cd FooBar
- run "yarn check"
you'll see these errors:
========
yarn check v0.21.3
error "tmp" is wrong version: expected "0.0.28", got "0.0.31"
warning "\u001b[2mchokidar#\u001b[22mfsevents#node-pre-gyp@^0.6.29" could be deduped from "0.6.34" to "node-pre-gyp@0.6.34"
error "external-editor#tmp" not installed
error Found 2 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
=========

### The log given by the failure.
- the first error is because karma and @angular/cli pull different versions of "tmp"
- haven't been able to track the second issue

### Desired functionality.
"yarn check" should not fail on a newly generated project.

**Comment by filipesilva** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the yarn project or file an issue on their issue tracker.

**Comment by entzik** [comment]
well I would argue that Angular CLI  generates a project that ends up pulling inconsistent dependencies. to be precise, two direct dependencies declared by AngularCLI are pulling different versions of the same transitive dependency.

this is definitely not a problem with yarn, yarn correctly report the inconsistent dependencies issue, but it's probably temporary...
