### ISSUE TITLE
Configure custom HTTP headers

### ISSUE THREAD

**Issue by tpetersheim** [angular/angular-cli#6262]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
I would like to be able to configure webpack server HTTP headers through the angular cli.  I am interested in configuring security headers so that I can determine their effects on my project.

### Mention any other details that might be useful.
It looks like this could be done very similarly to how the proxy config is passed through to the WebpackDevServer config options.  A separate config file could be used or maybe a combined configuration file could be used to hold both proxy and headers settings.

There is an existing request for adding proxy headers (https://github.com/angular/angular-cli/issues/5968) but this request is just for headers in general.

I am interested in contributing this enhancement.  Implementation feedback is welcomed.

**Comment by filipesilva** [comment]
This level of configuration is beyond the scope of `ng serve`. An alternative is to use `ng build --watch` and serve the contents of dist with a custom server that implements all the setting you need.
