### ISSUE TITLE
when i  build -prod，the images is in rootPath，i want they in a specified floder。

### ISSUE THREAD

**Issue by ermu592275254** [angular/angular-cli#6269]
i try to change the webpack config,like  that:

**common.js**
```
   {
                    test: /\.(jpg|png|gif|otf|ttf|woff|woff2|cur|ani)$/,
                    loader: `url-loader?name=images/[name]${hashFormat.file}.[ext]&limit=10000`
                }
```
it's fruitful,but i think it is not the best solution.
What should I do?

**Comment by filipesilva** [comment]
We don't provide configuration to change the folder, but if you server is just expecting all files to be in a particular path you can use the `--deploy-url=some/path` flag. It won't change the path stuff is in the file system, but all imports will be preceded by the path you choose.
