### ISSUE TITLE
JIT build raises AOT errors

### ISSUE THREAD

**Issue by milkisevil** [angular/angular-cli#6270]
### Bug Report or Feature Request

- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.

```
macOS Sierra 10.12.4

@angular/cli: 1.0.3
node: 6.10.3
os: darwin x64
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.2
```

### Repro steps.

1. Create a new cli project:

        $ ng new ng-jit-demo 

1. Open `app.module.ts` and replace with the following code to force an AOT error:

    ```ts
    import { BrowserModule } from '@angular/platform-browser';
    import { NgModule } from '@angular/core';
    import { FormsModule } from '@angular/forms';
    import { HttpModule } from '@angular/http';
    
    import { AppComponent } from './app.component';
    
    const doItJitStyle = () => [AppComponent];
    
    @NgModule({
      declarations: [
        AppComponent
      ],
      imports: [
        BrowserModule,
        FormsModule,
        HttpModule
      ],
      providers: [],
      bootstrap: [
        ...doItJitStyle()
      ]
    })
    export class AppModule { }
    ```

#### :zap: Build attempt 1

Build normally using `ng build --prod`

<details>
<summary>Expand to see log output</summary>

```
Hash: 4d550410a6e2a310e9fb                                                              
Time: 4491ms
chunk    {0} polyfills.39c939ce6d269d8796c3.bundle.js (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.7e863a477e6796f928cf.bundle.js (main) 668 bytes {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.74ddf70e43ac497bfb0d.bundle.js (vendor) 813 kB [initial] [rendered]
chunk    {4} inline.d4ed5370a83106fa58e6.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'doItJitStyle'. Consider exporting the symbol (position 8:7 in the original .ts file), resolving symbol AppModule in /Users/philipbulley/web/ng-jit-demo/src/app/app.module.ts, resolving symbol AppModule in /Users/philipbulley/web/ng-jit-demo/src/app/app.module.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/philipbulley/web/ng-jit-demo/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

</details>

#### :zap: Build attempt 2

Build whilst disabling AOT `ng build --prod --aot=false` [as suggested on gitter](https://gitter.im/angular/angular-cli?at=5913390873b39c5f1573cd2a)

<details>
<summary>Expand to see log output</summary>

```
Hash: 74cb0ee59a17c02ded26                                                              
Time: 9505ms
chunk    {0} polyfills.39c939ce6d269d8796c3.bundle.js (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.2910c51c5fac97b5ff99.bundle.js (main) 3.27 kB {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.7ef6611ab7ef458f7a60.bundle.js (vendor) 2.1 MB [initial] [rendered]
chunk    {4} inline.abcc3829176bfe99c423.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'doItJitStyle'. Consider exporting the symbol (position 8:7 in the original .ts file), resolving symbol AppModule in /Users/philipbulley/web/ng-jit-demo/src/app/app.module.ts, resolving symbol AppModule in /Users/philipbulley/web/ng-jit-demo/src/app/app.module.ts
```

</details>

#### :zap: Build attempt 3

Build whilst disabling AOT `ng build --prod --no-aot` [as suggested on this CLI issue](https://github.com/angular/angular-cli/issues/5153#issuecomment-286355681)

<details>
<summary>Expand to see log output</summary>

```
Hash: 74cb0ee59a17c02ded26                                                              
Time: 9351ms
chunk    {0} polyfills.39c939ce6d269d8796c3.bundle.js (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.2910c51c5fac97b5ff99.bundle.js (main) 3.27 kB {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.7ef6611ab7ef458f7a60.bundle.js (vendor) 2.1 MB [initial] [rendered]
chunk    {4} inline.abcc3829176bfe99c423.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'doItJitStyle'. Consider exporting the symbol (position 8:7 in the original .ts file), resolving symbol AppModule in /Users/philipbulley/web/ng-jit-demo/src/app/app.module.ts, resolving symbol AppModule in /Users/philipbulley/web/ng-jit-demo/src/app/app.module.ts
```

</details>

### Desired functionality.

When running a JIT build, AOT errors should not be thrown. In this case, compilation should be successful.

**Side note:** Better documentation on how to invoke a JIT build would also be appreciated (`ng build --help` is no help here). Is it JIT by default, or must a flag be used. Please clarify.

### Mention any other details that might be useful.

⚠️  Please, no comments on the benefits of AOT vs JIT. I am very specifically after a JIT build here.

**Comment by filipesilva** [comment]
Heya, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

The CLI always runs *some* statical analysis, even on JIT mode, on code to ensure it will run when compiled with AOT. This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

Good resource on how to to debug these errors are https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60 and  https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts.

If your problem still persists, it might be a bug with the Angular Compiler itself. In that case, please open an issue in https://github.com/angular/angular.

**Comment by filipesilva** [comment]
To expand, the reason we always do some statical analysis on JIT is to detect lazy routes. During that process, AOT errors can come up.

**Comment by milkisevil** [comment]
@filipesilva has AOT become compulsory for all Angular developers? I was always under the impression that AOT was opt-in, or at the very least opt-out.

> This may cause a lot of static analysis errors to surface when importing your project into the CLI

You're right, this is quite a big issue for me in porting a large codebase to the CLI.
