### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yaroslavert** [angular/angular-cli#6271]
I update to new version angular cli(1.03) and i create new project include angular materign and include BrowserAnimationsModule after i hava broblem 
![image](https://cloud.githubusercontent.com/assets/19486652/25947060/8ff96258-3656-11e7-937e-49bb74999252.png)

**Comment by yaroslavert** [comment]
![image](https://cloud.githubusercontent.com/assets/19486652/25947078/9e9587e2-3656-11e7-98cd-3451d4849970.png)

**Comment by yaroslavert** [comment]
![image](https://cloud.githubusercontent.com/assets/19486652/25947125/cee9672e-3656-11e7-9527-96cc09fb6566.png)

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

PS:. I'd say you have dependency problem, where some of your packages aren't correctly installed with other versions. Check the error log you got from `npm install` and fix the peer dependency errors.
