### ISSUE TITLE
Add automatic style fixing for `ng new` and all generators.

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#6272]
With https://github.com/palantir/tslint/pull/2723 merged, TS Lint will allow both quotemark and indentation auto-fix. This, together with https://github.com/angular/angular-cli/pull/6213, allows generators to automatically fix such style issues in generated files.

A flag to always auto-fix should be added to `.angular-cli.json` to always fix on generators:
```
  "defaults": {
    "lintFix": true,
    "styleExt": "css",
    "component": {}
  }
```

To allow this functionality for new projects, the global `.angular-cli.json` needs to be include some style information that will be used to override `tstlint` and `.editorconfig` settings, and linting must run post install.

**Comment by filipesilva** [comment]
Related https://github.com/angular/angular-cli/issues/5599, should probably be addressed in the same PR (but separate commit).

**Comment by filipesilva** [comment]
Currently blocked waiting for `tslint@5.3.0` to be released.

**Comment by imcotton** [comment]
tslint v5.3.0 has just released

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/6415 is updating to the new tslint.

Meanwhile, https://github.com/angular/angular-cli/pull/6213 already added `lintFix` to the CLI json file. It can be set on a project with `ng set defaults.lintFix true`.

I'm not as confident on how we should automatically do it for new projects though... https://github.com/angular/angular-cli/issues/3966 requests `trailing-comma` as well, so it might be a slippery slope to just add some lint properties to the CLI config.

Perhaps a path to a `.tslint` could be provided instead, and we copy it over for new projects, then run `ng lint --fix`.

**Comment by rsheptolut** [comment]
Doesn't do it for me when I want to specify 4 spaces per indentation level, instead of the 2 spaces generated by Angular CLI. But I guess it's a [bug in tslint](https://github.com/palantir/tslint/issues/2814).

**Comment by danyg** [comment]
does this work at all? I cannot make it work, using latest angular-cli 
```
Angular CLI: 1.6.1
Node: 6.11.3
OS: win32 x64
Angular: 5.1.1
```
with
```
"tslint": "~5.7.0",
"typescript": "~2.4.2"
```
With indent setting
```
"indent": [true, "tabs"],
```
and the feature lintFix to true

I've tried to also use the command ```ng lint --fix``` and does nothing, and also tried ```node_modules/tslint/bin/tslint --fix --project .```

**Comment by clydin** [comment]
Tslint does not provide a fixer for the indent rule.  See here for details: https://palantir.github.io/tslint/rules/

**Comment by tommck** [comment]
@clydin , the docs say "hasFixer".. so... ?

**Comment by tommck** [comment]
oh... but "NOTE: auto-fixing will only convert invalid indent whitespace to the desired type, it will not fix invalid whitespace sizes."

**Comment by studds** [comment]
Not sure if this is the place for this, but I think it would be ab fab if before running `lint --fix` on the altered files, `prettier` was also run (if installed / configured). See also https://github.com/angular/angular-cli/issues/7379 which seems to be mostly about adding prettier during `ng new`, as opposed to style fixing.

**Comment by tommck** [comment]
maybe just have some custom post-processor that can be run on all files?

**Comment by michahell** [comment]
@studds
> ab fab 
😂  after figuring out what that means to abbreviate

**Comment by lacolaco** [comment]
@filipesilva Since CLI v6, `--lintFix` option looks disappeared. There is no way to fix generated code automatically. Was it removed on purpose?

**Comment by tx8821** [comment]
https://github.com/angular/angular-cli/issues/11034

**Comment by buchmiller** [comment]
**The following should help those using tab indentation.**

Angular cli code generation currently defaults to 2 space indentation. The indent setting in tslint.json needs to be set to 2 spaces to pick up the indentation in the generated angular cli files.

```
// tslint.json
"indent": [
    true,
    "tabs",
    2
]

//.angular-cli.json
"defaults": {
    "lintFix": true
}
```

The part that I needed from the tslint rules page was

> Indentation size is **required** for auto-fixing, but not for rule checking.
