### ISSUE TITLE
Cannot read property 'length' of undefined, while installing any package in "office-ui-fabric-react/apps/fabric-website/",

### ISSUE THREAD

**Issue by pradeemi** [angular/angular-cli#6278]
Detail:
 --- Downloaded the code from "https://github.com/OfficeDev/office-ui-fabric-react" official website.
 --- using "office-ui-fabric-react/apps/fabric-website/" package
 ---  while installing any package for example "npm install azure-search" getting error "Cannot read property 'length' of undefined".
 --- check below for error detail

24 verbose etag https://registry.npmjs.org/azure-search from cache
25 verbose get saving azure-search to C:\Users\campus\AppData\Roaming\npm-cache\registry.npmjs.org\azure-search\.cache.json
26 verbose correctMkdir C:\Users\campus\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 verbose stack TypeError: Cannot read property 'length' of undefined
28 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:643:27
28 verbose stack     at Array.forEach (native)
28 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:642:19
28 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
28 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:175:5
28 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
28 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
28 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
28 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:175:5
28 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
29 verbose cwd F:\PradeepN\office-ui-fabric-react-master\apps\fabric-website
30 error Windows_NT 6.3.9600
31 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "azure-search"
32 error node v7.10.0
33 error npm  v4.2.0
34 error Cannot read property 'length' of undefined
35 error If you need help, you may report this error at:
35 error     <https://github.com/npm/npm/issues>
36 verbose exit [ 1, true ]

**Comment by sumitarora** [comment]
@pradeemi I think you logged the issue on the wrong repo. Please reopen if it's related to CLI and fill in the issue template with more details. Thanks!!

**Comment by pradeemi** [comment]
I am new to github site, Please let me know steps to raise this request..
