### ISSUE TITLE
Type 'T' is not a constructor function type

### ISSUE THREAD

**Issue by mrpmorris** [angular/angular-cli#6283]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

function classDecorator<T extends {new(...args:any[]):{}}>(constructor:T) {
    return class extends constructor {
        "a b c" = true
    }
}

@classDecorator
class Test {
  one: string = "x";
  two: string = "y";
  constructor() {
    console.log("length=" + Object.keys(this).length);
    console.log("x=" + Object.getPrototypeOf(this)["ServerApi:url"]);
  }
}

### The log given by the failure.
ERROR in C:/Data/Mine/Code/Web/AngularWithWebApi/ClientSide/src/app/app.component.ts (10,26): Type 'T' is not a constructor function type.

ERROR in C:/Data/Mine/Code/Web/AngularWithWebApi/ClientSide/src/app/app.component.ts (27,1): Unable to resolve signature of class decorator when called as an expression.
  Type 'typeof (Anonymous class)' is not assignable to type 'typeof Test'.
    Type 'classDecorator<typeof Test>.(Anonymous class)' is not assignable to type 'Test'.
      Property 'one' is missing in type 'classDecorator<typeof Test>.(Anonymous class)'.

ERROR in C:/Data/Mine/Code/Web/AngularWithWebApi/ClientSide/src/app/app.component.ts (10,26): Type 'T' is not a constructor function type.

ERROR in C:/Data/Mine/Code/Web/AngularWithWebApi/ClientSide/src/app/app.component.ts (27,1): Unable to resolve signature of class decorator when called as an expression.
  Type 'typeof (Anonymous class)' is not assignable to type 'typeof Test'.
    Type 'classDecorator<typeof Test>.(Anonymous class)' is not assignable to type 'Test'.
      Property 'one' is missing in type 'classDecorator<typeof Test>.(Anonymous class)'.

### Desired functionality.
In Visual Studio Code this syntax works fine, but "ng serve" throws the above exception. Is angular-cli using an older version of TSC or something?

**Comment by clydin** [comment]
Please update to the latest stable version of the CLI (currently 1.0.3). Note that the package name is "@angular/cli".

**Comment by mrpmorris** [comment]
That was exactly what I needed to know (the alternative package name) - thank you very much!

**Comment by sumitarora** [comment]
Closing as above.
