### ISSUE TITLE
Regarding to call .Less file in angular component

### ISSUE THREAD

**Issue by sumitjoshi2013** [angular/angular-cli#6303]
This is regarding to call .less file in the component using the StyleURLs. I am using angular JS 2 version. Please see the issue/error while implementing the .less file in styleurls.

The error is:

"Unhandled Promise rejection: Failed to load ../Style/type-default.less ; Zone: <root> ; Task: Promise.then ; Value: Failed to load ../Style/type-default.less

zone.js:632 Error: Uncaught (in promise): Failed to load ../Style/type-default.less"

Also I install the less using "npm install less" command.

**Comment by sumitarora** [comment]
@sumitjoshi2013 Is there a repo replicating the issue?
