### ISSUE TITLE
ASP NET MVC

### ISSUE THREAD

**Issue by EfrainPerez** [angular/angular-cli#6304]
**Does Anyone know how to implement angular/cli with ASP NET MVC, i tried a lot of things and nothing happends, only errors. If Anyone knows please help! and thanks for your time**

**Comment by ctrl-brk** [comment]
These kind of questions are more suitable for stackoverflow.com
It's not clear what exact "only errors" you have.
You can create restful web api server and access it from your angular app. I personally keep these two projects separate.

**Comment by delasteve** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by sumitarora** [comment]
Closing as above.
