### ISSUE TITLE
Calling external APIs from angular in .NET Core app returns 404.

### ISSUE THREAD

**Issue by marekdano** [angular/angular-cli#6305]
### Repro steps.
I setup .Net Core project following [this tutorial](http://www.sparkhound.com/learn/blog/setting-up-an-asp-net-core-project-with-angular-2-utilizing-angular-cli). I added angular cli into the project, built it through command "ng build --prod". The angular app is served as static files from wwwroot folder in the .Net Core app.
I also setup proxy.config server to serve other APIs. When I start command "ng serve --proxy-config proxy.conf.json" the app starts and calling the other APIs within the app works fine. The issue is when I start .Net Core app as "dotnet run", the angular app loads and runs fine, but calling APIs returns 404. Do you know why it is? Do I miss anything?

**Comment by delasteve** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by sumitarora** [comment]
Closing as above.
