### ISSUE TITLE
I find bug ng cli version @angular/cli: 1.0.3 node: 7.10.0 os: win32 x64

### ISSUE THREAD

**Issue by yaroslavert** [angular/angular-cli#6307]
Hello i find a bug 
![image](https://cloud.githubusercontent.com/assets/19486652/26028285/0d36c8ca-3826-11e7-89ca-e712c8a72a6e.png)
I create interface
![image](https://cloud.githubusercontent.com/assets/19486652/26028294/236322f6-3826-11e7-9efa-b5a224b4bef7.png)
include in the file
![image](https://cloud.githubusercontent.com/assets/19486652/26028297/32af67b0-3826-11e7-9001-70c422504eb8.png)
work
i change
![image](https://cloud.githubusercontent.com/assets/19486652/26028298/40a95aec-3826-11e7-9ad3-4e9e1d54be71.png)
![image](https://cloud.githubusercontent.com/assets/19486652/26028299/48c85dfe-3826-11e7-9481-49f3455af55b.png)
not word 
![image](https://cloud.githubusercontent.com/assets/19486652/26028303/5070c03c-3826-11e7-99fb-df0b741ef062.png)
i exit 
![image](https://cloud.githubusercontent.com/assets/19486652/26028306/58b67638-3826-11e7-86b7-0b4cdbf1f5f7.png)
run serve 
![image](https://cloud.githubusercontent.com/assets/19486652/26028312/7358f9ac-3826-11e7-8ca8-3182350328aa.png)
work

**Comment by rolandoldengarm** [comment]
I believe this is by design. Any new imports requires that you restart ng serve.
