### ISSUE TITLE
Adding a route fails

### ISSUE THREAD

**Issue by nareshbhatia** [angular/angular-cli#631]
Version: angular-cli@0.0.39

    ng g route home --default

Running the app gives the following error:

    The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
    Error: Typescript found the following errors:
    /Users/nbhati/projects/angular2-seed-cli/tmp/broccoli_type_script_compiler-input_base_path-jPwD2Y7Q.tmp/0/src/app/angular2-seed-cli.component.ts (13, 45): Argument of type '{ path: string; component: typeof HomeComponent; useAsDefault: boolean; }[]' is not assignable to parameter of type 'RouteMetadata[]'.
    Type '{ path: string; component: typeof HomeComponent; useAsDefault: boolean; }' is not assignable to type 'RouteMetadata'.

**Comment by nareshbhatia** [comment]
FYI, this is still not working for me. I am running from master and did the npm-link thingy as described in README.md, but still the same issue.

**Comment by nareshbhatia** [comment]
@Brocco, as far as I can tell, the commit above does not address this issue. The rc.1 router requires routes to be like this:

    @Routes([
      new Route({path: '/home', component: HomeComponent})
    ])

The cli is generating this:

    @Routes([
      {path: '/home', component: HomeComponent, useAsDefault: true}
    ])

**Comment by Brocco** [comment]
@nareshbhatia right now it appears that the router does not support default, so when generating routes please do not use `--default`

Also an issue was found about adding the route provider when the provider array already exists on the root component.

This will be tracked via #656

**Comment by nareshbhatia** [comment]
Sounds good.

**Comment by nareshbhatia** [comment]
It seems that the new way to specify the default path is to simply set it to '/':

    @Routes([
      new Route({path: '/', component: HomeComponent})
    ])

So the CLI may have to translate `ng g route home --default` to a path of `/`.

**Comment by nareshbhatia** [comment]
The RC 1 [router documentation](https://angular.io/docs/ts/latest/guide/router.html#!#configuration) is starting to come in. The examples are instantiating the default route in `ngOnInit()`. Here's how I modified the CLI generated code to start the app with the default route:

    import { Component, OnInit } from '@angular/core';
    import { HomeComponent } from './+home';
    import { Routes, Route, Router, ROUTER_DIRECTIVES, ROUTER_PROVIDERS} from '@angular/router';
    import { AboutComponent } from './+about';

    @Component({
      moduleId: module.id,
      selector: 'angular-cli-demo-app',
      templateUrl: 'angular-cli-demo.component.html',
      styleUrls: ['angular-cli-demo.component.css'],
      directives: [ROUTER_DIRECTIVES],
      providers: [ROUTER_PROVIDERS]
    })
    @Routes([
      new Route({path: '/', component: HomeComponent}),
      new Route({path: '/about', component: AboutComponent})
    ])
    export class AngularCliDemoAppComponent implements OnInit {
      title = 'Angular CLI Demo';

      constructor(private router: Router) {}

      ngOnInit() {
        this.router.navigate(['/']);
      }
    }

**Comment by scastaldi** [comment]
after you import.. Route, Router, you don't need new Route()
also I'm not sure why is creating the routes with +   (./+home, ./+about)

**Comment by shangab** [comment]
Ah, what?? @Routes ??
