### ISSUE TITLE
Flag in configuration to exclude html serving

### ISSUE THREAD

**Issue by harisb2012** [angular/angular-cli#6311]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
I'm not using angular-cli because of simple reason - I don't want html file to be generated as I want to handle some things from express js server (rendering from there). I would like to have option to exclude html and save hash to json file after the build so it is possible to load js and css files manually.

**Comment by harisb2012** [comment]
@sumitarora - Anything?

**Comment by mgechev** [comment]
@harisb2012 although this feature looks attractive for some use cases, we need to set scope boundaries of the CLI, otherwise we risk to introduce big complexity and bloat the tool. I'd close the issue for now. If the need for this use case increases, feel free to open a new feature request.
