### ISSUE TITLE
'ng g module' should include empty 'exports' property

### ISSUE THREAD

**Issue by tijwelch** [angular/angular-cli#6312]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.
@angular/cli: 1.0.0-rc.2
node: 7.2.1
os: darwin x64
@angular/animations: 4.1.1
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/compiler-cli: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/platform-server: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.0-rc.2
@ngtools/webpack: 1.2.13

### Repro steps.
'ng g module foo'

### Desired functionality.
The metadata object passed to @NgModule in the generated module should include an 'exports' property with value of an empty array.

@NgModule({
  imports: [
    CommonModule
  ],
  declarations: [],
  exports: []
})

A common progression for beginners building apps with angular-cli is to start out with a single module. Without specifying a module`ng g component bar` adds the new bar component to the declarations property in app.module. At some point, it makes sense to start organizing components into chunks of functionality by using multiple modules. So the developer creates 'ProductsModule', moves a few product related components out of app.module and into products.module and adds ProductsModule to the 'imports' proprty in app.module. It's reasonable to think that this is all that needs to be done to start using components from the ProductsModule but the console complains with the "can't bind to component" error. 

It's not obvious to beginners that components need to be added to the exports property of a module because they aren't aware that the exports property exists. Including an empty 'exports' property would help express the input / output nature of a module. 
 
Happy to help on a PR for this if the feature request is accepted.

**Comment by tytskyi** [comment]
In fact there is only 1 module in the app should have `exports`: SharedModule.  https://angular.io/docs/ts/latest/guide/ngmodule.html#!#shared-module

Feature modules need to export components only if they are not lazy. If module is lazy loaded for specific route it does not need to export anything. 

Otherwise i assume that you want to not use lazy loaded modules at all.

**Comment by Brocco** [comment]
I disagree that the default blueprint should contain the empty array for exports. This is a property of NgModule that most people will not use and by including it the CLI is forcing developers to delete unnecessary code.

In fact, I would argue that the appropriate change would be to remove the declarations array. Generating components/directives/pipes would auto-add the declarations property if needed. More to that point you can use the `--export` option to auto-export generated components/directives/pipes which would auto-add the exports property to the NgModule.

**Comment by filipesilva** [comment]
Closing as issue was discussed offline and the previous opinions still stand.
