### ISSUE TITLE
Angular cli install - Host key verification failed

### ISSUE THREAD

**Issue by cwisking** [angular/angular-cli#6313]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

node -- version : V7.10.0
npm --version 1.4.9

### Repro steps.

Install angular cli via npm
npm install -g @angular/cli

### The log given by the failure.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@1.4.9
3 info using node@v7.10.0
4 verbose cache add [ '@angular/cli', null ]
5 verbose cache add name=undefined spec="@angular/cli" args=["@angular/cli",null]
6 verbose parsed url Url {
6 verbose parsed url   protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: '@angular/cli',
6 verbose parsed url   path: '@angular/cli',
6 verbose parsed url   href: '@angular/cli' }
7 verbose cache add name="" spec="angular/cli" args=["","angular/cli"]
8 verbose parsed url Url {
8 verbose parsed url   protocol: null,
8 verbose parsed url   slashes: null,
8 verbose parsed url   auth: null,
8 verbose parsed url   host: null,
8 verbose parsed url   port: null,
8 verbose parsed url   hostname: null,
8 verbose parsed url   hash: null,
8 verbose parsed url   search: null,
8 verbose parsed url   query: null,
8 verbose parsed url   pathname: 'angular/cli',
8 verbose parsed url   path: 'angular/cli',
8 verbose parsed url   href: 'angular/cli' }
9 silly lockFile 5cecaa1c-angular-cli angular/cli
10 verbose lock angular/cli C:\Users\chriswi\AppData\Roaming\npm-cache\5cecaa1c-angular-cli.lock
11 info maybeGithub Attempting angular/cli from git://github.com/angular/cli
12 silly lockFile 057ccbdd-git-github-com-angular-cli git://github.com/angular/cli
13 verbose lock git://github.com/angular/cli C:\Users\chriswi\AppData\Roaming\npm-cache\057ccbdd-git-github-com-angular-cli.lock
14 verbose addRemoteGit [ 'git://github.com/angular/cli', 'master' ]
15 warn `git config --get remote.origin.url` returned wrong result (git://github.com/angular/cli)
16 verbose git clone git://github.com/angular/cli Cloning into bare repository 'C:\Users\chriswi\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-057ccbdd'...
16 verbose git clone git://github.com/angular/cli remote: Repository not found.
16 verbose git clone git://github.com/angular/cli fatal: repository 'https://github.com/angular/cli/' not found
17 silly lockFile 057ccbdd-git-github-com-angular-cli git://github.com/angular/cli
18 silly lockFile 057ccbdd-git-github-com-angular-cli git://github.com/angular/cli
19 info maybeGithub Attempting angular/cli from git+ssh://git@github.com:angular/cli
20 silly lockFile 515723dd-git-github-com-angular-cli git@github.com:angular/cli
21 verbose lock git@github.com:angular/cli C:\Users\chriswi\AppData\Roaming\npm-cache\515723dd-git-github-com-angular-cli.lock
22 verbose addRemoteGit [ 'git@github.com:angular/cli', 'master' ]
23 warn `git config --get remote.origin.url` returned wrong result (git@github.com:angular/cli)
24 error git clone git@github.com:angular/cli Cloning into bare repository 'C:\Users\chriswi\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-515723dd'...
24 error git clone git@github.com:angular/cli Host key verification failed.
24 error git clone git@github.com:angular/cli fatal: Could not read from remote repository.
24 error git clone git@github.com:angular/cli
24 error git clone git@github.com:angular/cli Please make sure you have the correct access rights
24 error git clone git@github.com:angular/cli and the repository exists.
25 silly lockFile 515723dd-git-github-com-angular-cli git@github.com:angular/cli
26 silly lockFile 515723dd-git-github-com-angular-cli git@github.com:angular/cli
27 silly lockFile 5cecaa1c-angular-cli angular/cli
28 silly lockFile 5cecaa1c-angular-cli angular/cli
29 error addLocal Could not install angular/cli
30 error Error: ENOENT: no such file or directory, stat 'C:\WINDOWS\system32\angular\cli'
31 error If you need help, you may report this *entire* log,
31 error including the npm and node versions, at:
31 error     <http://github.com/npm/npm/issues>
32 error System Windows_NT 10.0.10240
33 error command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
34 error cwd C:\WINDOWS\system32
35 error node -v v7.10.0
36 error npm -v 1.4.9
37 error path C:\WINDOWS\system32\angular\cli
38 error syscall stat
39 error code ENOENT
40 error errno -4058
41 verbose exit [ -4058, true ]

### Mention any other details that might be useful.

I cant seem to be able to install the cli via npm. I have installed other frameworks before, just angular for some reason. Any ideas?

**Comment by sumitarora** [comment]
@cwisking Seems like you are using an old version of npm `npm --version 1.4.9` Please update to npm 3. Here are the prerequisites for Angular CLI https://github.com/angular/angular-cli#prerequisites

**Comment by cwisking** [comment]
Hey yup, I thought as much, but seeing as I had updated npm to the latest version ( I even uninstalled node and reinstalled ) with the same result. npm -v still showed the same version.

FYI for others that may have the same issue. I also have Chocolatey installed, and it seems that npm was also installed via Chocolately which seems to overide the npm path. Uninstalling npm from Chocolately resolved the npm version issue.

After that angular/cli installs correctly from npm.

**Comment by cljk** [comment]
@cwisking Thanks for pointing out problems with `npm`/`choco` - was my source of problem too...

**Comment by BillPennock** [comment]
Well I don't even know that chocolately is and i'm having the same problem with npm -v resolving 6.4.1
how do I know if something I have done has added chocolately and messed me up without my knowledge
