### ISSUE TITLE
Component Style not working with extract-text-webpack-plugin in AOT mode

### ISSUE THREAD

**Issue by Mocha--** [angular/angular-cli#6314]
**Question: Is it possible to extract the component style that is generated by angular with hash, to a separate css file, instead of appending 'html style tag' in 'html head'?**

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
@angular/compiler-cli: 4.1.2
OS: Windows 10
node: 6.9.5
npm: 3.10.10

**Comment by sumitarora** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
