### ISSUE TITLE
Generating Component into module fails when there is a Component with the same name of the Module

### ISSUE THREAD

**Issue by ShinDarth** [angular/angular-cli#6316]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.3
node: 6.10.3
os: linux x64
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.2

### Repro steps.

- Create a module named *MyTest* using ``ng generate module MyTest``
- Create a component also named *MyTest* into the *MyTest* module using ``ng generate component MyTest --module my-test``  (sidenote: ``--module MyTest`` does not work because of another issue reported here https://github.com/angular/angular-cli/issues/6287)

So far so good, a directory named ``my-test`` has been created containing both the *MyTest Module* and the *MyTest Component*.

- Create another component  named *MyOtherTest* into the *MyTest* module using ``ng generate component MyOtherTest --module my-test``

now we would expect that the *MyOtherTest Component* is also created under the module directory, which is ``my-test``, instead it's created under ``my-other-test`` directory, which leads to confusion.

### The log given by the failure.

➜  ng-exercises git:(master) ✗ ng generate module MyTest    
installing module
  create src/app/my-test/my-test.module.ts

➜  ng-exercises git:(master) ✗ ng generate component MyTest --module my-test
installing component
  create src/app/my-test/my-test.component.css
  create src/app/my-test/my-test.component.html
  create src/app/my-test/my-test.component.spec.ts
  create src/app/my-test/my-test.component.ts
  update src/app/my-test/my-test.module.ts

➜  ng-exercises git:(master) ✗ ng generate component MyOtherTest --module my-test
installing component
  create src/app/my-other-test/my-other-test.component.css
  create src/app/my-other-test/my-other-test.component.html
  create src/app/my-other-test/my-other-test.component.spec.ts
  create src/app/my-other-test/my-other-test.component.ts
  update src/app/my-test/my-test.module.ts

### Desired functionality.
Explained in retro steps.

### Mention any other details that might be useful.

No extra information required.

**Comment by clydin** [comment]
What you are describing is intended and expected behavior.  The module option does not affect the location of the component rather it specifies the module that will import the component.  Also, the module option takes a file path not the name of the module (either the name of the directory containing the module or the module file name itself).  Also by default components and modules will be created within a directory based on their respective names.  In this case, you used the same name for the module and component causing both to be created in the same directory.

**Comment by ShinDarth** [comment]
alright, closing it
