### ISSUE TITLE
Unable to access files with umlauts (ä, ü, ö) in their file name when running ng serve

### ISSUE THREAD

**Issue by mmathys** [angular/angular-cli#6317]
### Bug Report or Feature Request
```
- [x] bug report
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.3
node: 6.10.3
macOS: 10.12.4 Sierra

### Repro steps.

```shell
ng new umlauts-test && cd umlauts-test

cd src/assets
echo "asset file without umlauts works." >> test.txt # create simple text file without umlauts.
echo "this asset file is never shown." >> ä.txt # one will not able to access that file!
cd ../..

ng serve
```

- `http://localhost:4200/assets/test.txt` returns the text ✅
- `http://localhost:4200/assets/ä.txt` **returns a 404** and redirects to the app❗️
- `http://localhost:4200/assets/%C3%A4.txt` **returns a 404** and redirects to the app❗️

### The log given by the failure.

When accessing `view-source:http://localhost:4200/assets/ä.txt` on Chrome, one is being redirected to the normal app!

### Desired functionality.

The `ng serve` http server should encode properly and support special characters.

**Comment by mmathys** [comment]
Note that the error log shows `Cannot GET /assets/%C3%83%C2%A4.txt`.

`%C3%83%C2%A4` url decoded is `Ã¤`. Sometimes when `ä` is incorrectly encoded (UTF-8 --> ASCII) it is displayed as `Ã¤`.

When url encoding in UTF-8, `ä.txt` should result in `%C3%A4.txt`.

I might get mixed up here, but I think there's an issue with encoding

**Comment by mmathys** [comment]
yeh this project seems to be dead thx bye

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
