### ISSUE TITLE
EXCEPTION: Uncaught (in promise): Error: DI Error Error: DI Error

### ISSUE THREAD

**Issue by Duraimurugan** [angular/angular-cli#6318]
### Versions.
@angular/cli: 1.0.3
node: 6.9.1
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.3
@angular/compiler-cli: 2.4.10

Other libraries used in package.json:
"angular2-fontawesome": "^0.8.0",
    "angular2-logger": "^0.5.1",
    "bootstrap": "^3.3.7",
    "compression-webpack-plugin": "^0.4.0",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.3",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "karma": "^1.2.0",
    "minimatch": "^3.0.3",
    "moment": "^2.17.1",
    "mydatepicker": "^2.0.4",
    "ngx-bootstrap": "^1.6.6",
    "primeng": "^2.0.6",
    "rxjs": "^5.0.1",
    "tether": "^1.4.0",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"

### Repro steps.
application works perfect when `ng serve` but when ran `ng serve -dev --aot` I got the error as follows in the browsers,

### The log given by the failure.
EXCEPTION: Uncaught (in promise): Error: DI Error
Error: DI Error
    at NoProviderError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:88531:33)
    at NoProviderError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:23523:16)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4200/vendor.bundle.js:44051:16)
    at new NoProviderError (http://localhost:4200/vendor.bundle.js:44113:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:4200/vendor.bundle.js:56698:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/vendor.bundle.js:56737:25)
    at ReflectiveInjector_._getByKey (http://localhost:4200/vendor.bundle.js:56669:25)
    at ReflectiveInjector_.get (http://localhost:4200/vendor.bundle.js:56538:21)

### Desired functionality.
no error should be thrown

**Comment by sumitarora** [comment]
@Duraimurugan Is there a repo replicating the issue or you can create one?

**Comment by Duraimurugan** [comment]
I do not have a repo that I can share with you and also its not easy to create one as the application is complex and confidential one. @sumitarora 
Is there any way to look into this?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
