### ISSUE TITLE
[Bug] Eject missing '@ngtools/webpack' reference in package.json

### ISSUE THREAD

**Issue by luchillo17** [angular/angular-cli#6319]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Versions.
```sh
    _                      _                 ____ _     ___                             
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|                            
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |                             
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |                             
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|                            
                   |___/                                                                    

@angular/cli: 1.1.0-beta.1 (e)                                                          
node: 7.8.0                                                                             
os: darwin x64                                                                                                                                 @angular/animations: 4.1.2                                                                                                                                                  @angular/common: 4.1.2                                                                  
@angular/compiler: 4.1.2                                                                
@angular/core: 4.1.2                                                                    
@angular/forms: 4.1.2                                                                   
@angular/http: 4.1.2                                                                    
@angular/language-service: 4.1.2                                                        
@angular/platform-browser: 4.1.2                                                        
@angular/platform-browser-dynamic: 4.1.2                                                
@angular/router: 4.1.2                                                                  
@angular/cli: 1.1.0-beta.1                                                              
@angular/compiler-cli: 4.1.2  
```

### Repro steps.
1. Create new project.
2. Eject project.
3. Check and verify the `package.json` lack for `@ngtools/webpack` in dev deps.

### The log given by the failure.
None, just noticed the lack of the reference to such loader after eject.

### Desired functionality.
If ejected and still using `@ngtools/webpack` it should add a reference in package.json to it, if for whatever reason the user decides to execute `npm prune` it would be removed from `node_modules` and effectively leaving the user scratching their heads about what broke.

### Mention any other details that might be useful.
Should be an easy and little fix.

**[Update]:** Actually i runned the `npm prune` command and i'm shocked, it wasn't removed, so i'm scratching my head right now, is it because the `@angular/cli` has it as dependency? is it better to let the `@angular/cli` package to manage the `@ngtools/webpack` version instead?

**Comment by sumitarora** [comment]
@luchillo17 Yes it's the peer dependency of Angular CLI itself https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/package.json#L31 so it's not there in `package.json` for the newly created project, they only have `"@angular/cli": "1.1.0-beta.0",` as a dependency.

**Comment by luchillo17** [comment]
I see, my bad, guess this issue was due to my lack of knowledge on the cli itself.

**Comment by sumitarora** [comment]
@luchillo17 No worries 😄
