### ISSUE TITLE
Parametrize the blueprint that shall be used to generate started app

### ISSUE THREAD

**Issue by ajit-kumar-azad** [angular/angular-cli#6327]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Desired functionality.
Parametrize the blueprint name that needs to be used to generate a started app. E.g. add support for --template (or --tpl) option to let the user mention what starter app template they want to use to generate the starter app. Default value for the option shall be 'ng' so that it is backward compatible. 

So, if I want to generate an app using the current ng starter app, I would type:
```
ng new MyApp
```
However, if I want to generate an app using another app template, say todo, which create a different sample app, then I would type:
```
ng new --template='todo' MyApp
```
OR
```
ng new --tpl='todo' MyApp
```
This will let people build their own app templates and use it in their projects.

I have done the changes and tested it. Let me know if it makes sense and I shall be able to submit a PR.

Thanks
Ajit

**Comment by sumitarora** [comment]
@ajit-kumar-azad Currently Angular CLI only works with templates which are internal. In future versions of CLI we would have the option to create your own templates and generate apps based on those.

**Comment by ajit-kumar-azad** [comment]
So, may be for now, can we take this as a patch so that it enables the user today and later in future when we have the complete functionality this change can be dropped?

**Comment by mgechev** [comment]
You can already do this in the CLI by providing a custom collection.
