### ISSUE TITLE
Building multiple variants of an application - add option to override styles in `ng-build`?

### ISSUE THREAD

**Issue by JohannesRudolph** [angular/angular-cli#6331]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
```@angular/cli: 1.0.3
node: 7.3.0
os: win32 x64
```

### Desired functionality.
We build a large angular application that has grown to needing to support different build targets (i.e. _compile time_ configuration) and deployment targets (i.e. runtime configuration). We abuse angular-cli's environment files to allow us to build this application for different build targets and use server-side includes in our index.html to inject runtime configuration. It's a really nice setup that gives us maximum tree-shakeability (I should probably blog about it one day...). 

However, we currently lack a clean way to configure different scss imports for different build targets. It is important this configuration happens at compile time, e.g. so that we can set bootstrap variables before importing bootstrap.scss itself. I do currently see two ways to implement this: 

1. declare multiple apps in angular-cli.json
2. allow us to override styles.scss with a cmdline flag
3. expand environments to allow inclusion of more than just ts files

I don't like 1) because it adds repition to our configuration (assets etc.) and I quite like the way we can build all our build targets in parallel with [npm-run-all](https://www.npmjs.com/package/npm-run-all). Not sure how angular-cli deals with multiple apps defined in the same angular-cli.json

2) would be easy to add, considering that angular-cli already allows users to override selected parameters like `outDir`. On a sidenote, we also had a similar issue with `protractor.conf` in `ng e2e` (i.e. we run different scenarios based on the build target) and we could solve those again by overriding the `protractor.conf` file via the `--config` flag. 

3) Would be verify flexible but it's probably difficult to decide on a sensible scope for inclusion or not. 

Taken together, I think option 2) is the most consistent.

**Comment by JohannesRudolph** [comment]
Having tinkered with this for a while, I think that it actually would be even better for me to be able to override `stylePreprocessoroptions.includePaths` rather than styles as this allows proper theming with scss (i.e. component scss files can just import `_theme.scss` which is sourced from a different include path). 

However, there's also the issue of `assets`. The more and more I think about this whole thing, option 1) looks attractive again as I discovered that I can use `ng build --app xxx`. I'm leaving this issue open for discussion as I think it highlights an advanced use case that angular-cli should try to handle consistently (e.g. why don't we have protractor conf on the app level as well in angular-cli.json?) and the whole angular-cli.json vs cmdline option is interesting as well.

**Comment by soulfresh** [comment]
@JohannesRudolph I've been *mostly* able to work around this by ejecting the webpack config and specifying the sass-loader include paths there. I then change the include paths based on an environment variable that I set when I run my builds. For assets, I use a separate build step to build the assets I need before I run webpack. I mostly try to compile assets into my output bundle so I don't have to worry about multiple asset folders but I would expect you could easily configure asset locations with a config file or service.

The only issue I've run across with this so far is that unit tests do not seem to honor my webpac config or even `stylePreprocessorOptions.includePaths` in `angular-cli.json`. I currently have a fork of the `@angular/cli/plugins/karma.js` to work around this but I'm also not sure if I've missed something with my `stylePreprocessorOptions` config. I'm curious to know if you've had any issues with this.

Here's some of the relevant code for my solution in case it helps you out:

```js
// This is the default path you want to use to discover SASS files.
const defaultThemePath = 'path/relative/to/webpack/config';
// Then we check to see if an environment variable is set to override the default path.
const themePath = process.env.THEME_DIR ? process.env.THEME_DIR : defaultThemePath;

// These are the options we'll use to setup SASS.
const sassLoaderOptions = {
  includePaths: [
    return path.join(process.cwd(), themePath);
  ],
  // Any other SASS config you want to pass can go here as well.
  outputStyle: "compressed"
};

module.exports = {
  ...
  "module": {
    "rules": [
      ...
      {
        "test": /\.scss$|\.sass$/,
        ...
        "loaders": [
          ...
          // Repeat this for all of your sass-loader definitions.
          {
            loader: "sass-loader",
            options: sassLoaderOptions
          }
        ]
      },
      ...
    ]
  }
}

```

Now your SASS files need to import the theme functionality in a generic way:

```scss
@import 'theme';

@include thing-from-theme-file();
```

And now you can configure a different theme folder for your build commands:

```console
$ THEME_DIR=path/to/theme webpack-dev-server --port 8090
```

Hopefully someone finds this useful. I'm definitely interested to know if there's a better way to do this.

**Comment by ggirou** [comment]
As an alternative, it could be great to have javascript file insteadof `.angular-cli.json` for configuration :

```js
module.export = {
    // ...
    "styles": [
        "styles.css",
        process.env.THEME_DIR + "/theme.css"
    ]
    // ...
};
```

    THEME_DIR=path/to/theme ng build

**Comment by filipesilva** [comment]
I believe the configuration array today in Angular CLI caters for this use case. You can use `ng build --configuration=something` to override only a subset of options.
