### ISSUE TITLE
Can I target es6 for debugging only (ng s)?

### ISSUE THREAD

**Issue by chadbr** [angular/angular-cli#6333]
Using:
    "@angular/cli": "1.1.0-beta.1",
    "@angular/compiler-cli": "^4.1.2",

Is there a workflow for targeting es6 for local debugging only?

I'm using async/await with typescript -- the coding is fantastic, but the debugging is... less than desirable :)
Targeting es6 for local debugging makes this much, much better (usable!).

Is there some way to target es6 without modifying the tsconfig files (i.e. from the command line?)
Or is there some way to add another configuration like tsconfig.app.json and tsconfig.spec.json? Like a tsconfig.localdebug.json or something?

Thanks! Chad

**Comment by sumitarora** [comment]
@chadbr You should be able to change it in `tsconfig.app.json` as below.

**Comment by chadbr** [comment]
@sumitarora I understand -- but I want to deploy with es5 -- debug with es6... can I add another tsconfig configuration? Like a tsconfig.debug.json?

**Comment by clydin** [comment]
The only current method is to make an additional copy of the app configuration section inside `.angular-cli.json` and then create a different tsconfig (with the desired settings) that is then used in the second app _copy_ configuration.  The `--app` command line option can then be used to switch between the two different _apps_.
