### ISSUE TITLE
proxy.conf.json and corporate proxy

### ISSUE THREAD

**Issue by alexandrepetrillo** [angular/angular-cli#6336]
Hello,
I use proxy.conf.json to redirect my api request to an other server. this server is in the cloud and i need use a corporate proxy.

my is proxy.conf.json:

{
  "/individuel/api/*": {
    "target": "http://mycloudserveur:8081",
    "pathRewrite": {
      "^/individuel": ""
    },
    "secure": true,
    "changeOrigin": true
  }
}

How can i add my cloud proxy information?
Thanks

For exemple when i use npm install i need set following configuration :
proxy http://noevipncp2n.edf.fr:3128/
https-proxy http://noevipncp2n.edf.fr:3128/
http-proxy http://noevipncp2n.edf.fr:3128
set strict-ssl false -global

**Comment by dave11mj** [comment]
@alexandrepetrillo have you tried this doc ?
https://github.com/angular/angular-cli/wiki/stories-using-corporate-proxy
