### ISSUE TITLE
@ngtools/webpack - Allow passing custom file contents modifier and resource path modifier

### ISSUE THREAD

**Issue by Reuvenc** [angular/angular-cli#6337]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] feature request
```

### Desired functionality.

In some cases, I need to insert/modify a file, or change the path of resource based on different configuration values. 

Currently it is possible to override a list of files with `hostReplacementPaths`, but when speaking on large amount of files, this option gets not flexible enough. As far as I can see, two extra options could be added to AotPluginOptions:

``` typescript
export interface AotPluginOptions {
    ...
    // modifies the file contents after read from file system and before file contents are set in compiler host.
    modifyFileContents: (filename: string, contents: string) => string;
    // transform the resource path before actually reading the contents.
    modifyResourcePath: (resourcePath) => string; 
}
```

I believe these configuration entries might be useful for many purposes and will add flexibility to the plugin.

Thanks, 
Reuven.

**Comment by Reuvenc** [comment]
Any updates regarding this feature?

**Comment by giniedp** [comment]
this functionality is given by the nature of webpack. If only we could pre-chain custom loaders, see https://github.com/angular/angular-cli/issues/8870.

**Comment by mgechev** [comment]
Looks like https://github.com/angular/angular-cli/issues/8870 covers the limitation.
