### ISSUE TITLE
How to use postcss plugins like autoprefixer

### ISSUE THREAD

**Issue by neilhem** [angular/angular-cli#634]
Hi, is there any way to process css files with postcss plugin like autoprefixer?

**Comment by griezma** [comment]
Not sure if this is the best way, but it works...

In angular-cli-build.js:
<pre>
var Angular2App = require('angular-cli/lib/broccoli/angular2-app');
var autoprefixer = require('broccoli-autoprefixer');  // add autoprefixer

module.exports = function(defaults) {
  var app = new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/*.js',
      'es6-shim/es6-shim.js',
      'reflect-metadata/*.js',
      'rxjs/**/*.js',
      '@angular/**/*.js'
    ]
  });
  return autoprefixer(app, { browsers: ['last 2 version'] }); // use autoprefixer
};
</pre>

**Comment by cristianurbano** [comment]
I need also to integrate `postcss-import` and `postcss-cssnext`

**Comment by SethDavenport** [comment]
Heavy PostCSS/CSSNext/Autoprefixer user as well - very easy to set up with webpack.  Would love some docs or insight on how to use this toolchain with angular-cli.

**Comment by knikel** [comment]
@SethDavenport I'm working with a similar stack, here are relevant parts of my `angular-cli-build.js` file.

```
/* global require, module */

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

var postcss = require('broccoli-postcss');

var atImport = require('postcss-import');
var customMedia = require('postcss-custom-media');
var customProps = require('postcss-custom-properties');
var calc = require('postcss-calc');
var discardComments = require('postcss-discard-comments');
var removeRoot = require('postcss-remove-root');
var autoprefixer = require('autoprefixer');

module.exports = function (defaults) {
  var app = new Angular2App(defaults, {
    vendorNpmFiles: [
      /* Vendor stuff */
    ]
  });

  var cssOptions = {
    plugins: [
      {
        module: atImport,
        options: {
          path: ['src/client/css/'], // A way to import custom CSS modules, given they're in this directory and are module-name/index.css
          plugins: [] // this has to be set, otherwise atImport plugin flops, no idea why
        }
      },
      {
        module: discardComments
      },
      {
        module: customMedia
      },
      {
        module: customProps
      },
      {
        module: calc
      },
      {
        module: removeRoot
      },
      {
        module: autoprefixer // your prefixer settings here
      }
    ]
  };

  return postcss(app, cssOptions);
};
```

**Comment by SethDavenport** [comment]
Thanks, I'll give that a try. Time to learn what broccolis is :)

**Comment by cristianurbano** [comment]
@knikel that works for me, thanks!

**Comment by drejohnson** [comment]
Thanks @knikel This should be documented. The ability to use PostCSS is awesome.

**Comment by pavel06081991** [comment]
Hello, what about sugarss? how to use sugarss parser?

**Comment by pavel06081991** [comment]
And how to exclude css files of external libs? now I have:
```
module.exports = function(defaults) {
  var app = new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/*.js',
      'es6-shim/es6-shim.js',
      'reflect-metadata/*.js',
      'rxjs/**/*.js',
      '@angular/**/*.js',
      'lodash/lodash.js',
      'primeng/**/*',
      'primeui/**/*',
      'moment/moment.js',
      'ng2-bootstrap/**/*.js'
    ]
  });

  var cssOptions = {
    plugins: [
      {
        module: $.autoprefixer,
        options: {
          browsers: ['> 5%']
        }
      }
    ]
  };

  return $.postcss(app, cssOptions);
```
and postcss compiles css of all external libs such as primeui

**Comment by filipesilva** [comment]
This issue has been made obsolete by #1455.
