### ISSUE TITLE
Don't delete destination folder until current compilation is complete.

### ISSUE THREAD

**Issue by jaesung2061** [angular/angular-cli#6344]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
```
@angular/cli: 1.0.2
node: 6.10.2
os: linux x64
@angular/animations: 4.1.1
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.1
```

### Repro steps.
Run build command

### Desired functionality.
Don't delete destination folder until current compilation is complete. Perhaps put it in a `.compiling` directory until compilation is completed, then delete the destination directory and rename `.compiling` to the destination directory.

**Comment by sumitarora** [comment]
@jaesung2061 There is flag not to delete dest folder and has been merged in 1.1.0-beta https://github.com/angular/angular-cli/issues/5925
