### ISSUE TITLE
--mobile is not accepted with ng new

### ISSUE THREAD

**Issue by amishra511** [angular/angular-cli#6346]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.3
node: 6.9.2
os: win32 x64
@angular/cli: 1.0.3

### Repro steps.
I am following the steps given in Angular Mobile guide to create new app with Angular CLI
https://mobile.angular.io/guides/

On executing: **ng new hello-mobile --mobile**
I get:
> The option '--mobile' is not registered with the new command.

As a result, the angular app gets generated but without the files required for mobile development

### The log given by the failure.

> The option '--mobile' is not registered with the new command.

### Desired functionality.

Expecting an angular app to be generated with files required for mobile development

**Comment by kacase** [comment]
The mobile option was removed some time ago because it did not work properly. #4143

The only way to create a mobile angular app is currently adding the manifest and service worker yourself.

**Comment by tytskyi** [comment]
@amishra511 this guide is totally outdated, 
`npm install -g angular-cli` this is not correct name of package

As for now you should make you app "mobile" manually, as @kacase pointed above

**Comment by kacase** [comment]
@amishra511 
There is a pretty good guide by @coryrylan about how to work with the manifest and service-worker available. I just tested it and it works like a charm.
He suggests using a combination of a manual manifest and sw-precache which is maintained by google.

Check out his guide here:
https://coryrylan.com/blog/fast-offline-angular-apps-with-service-workers

**Comment by amishra511** [comment]
@kacase I will check this guide out.

**Comment by sumitarora** [comment]
@amishra511 Is it still an issue?

**Comment by amishra511** [comment]
No, not anymore. I can create an angular mobile app now the way suggested by @kacase
