### ISSUE TITLE
ng build --prod issue 

### ISSUE THREAD

**Issue by YadJosan** [angular/angular-cli#6355]
ERROR in Expected 'styles' to be an array of strings.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\Projects\simplifyng2\src'
@ ./src/main.ts 5:0-74
@ multi ./src/main.ts

**Comment by RicardoVaranda** [comment]
Hi @YadJosan ,

Could you please post your angular-cli.json
This error normally occurs when you don't have styles declared in the correct way:

```
"styles": [
        "styles.scss"
      ],
```

In older versions of the cli this was declared different, if you are updating your application from an older version you must ensure all changes to the angular-cli.json are compliant with the new standards.

**Comment by YadJosan** [comment]
{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "project": {
        "name": "smartadmin"
    },
    "apps": [{
        "root": "src",
        "outDir": "dist",
        "assets": [
            "assets"
        ],
        "index": "index.html",
        "main": "main.ts",
        "polyfills": "polyfills.ts",
        "test": "test.ts",
        "tsconfig": "tsconfig.app.json",
        "testTsconfig": "tsconfig.spec.json",
        "prefix": "app",
        "styles": ["styles.css"],
        "scripts": [],
        "environmentSource": "environments/environment.ts",
        "environments": {
            "dev": "environments/environment.ts",
            "prod": "environments/environment.prod.ts"
        }
    }],
    "e2e": {
        "protractor": {
            "config": "./protractor.conf.js"
        }
    },
    "lint": [{
        "project": "src/tsconfig.app.json"
    }, {
        "project": "src/tsconfig.spec.json"
    }, {
        "project": "e2e/tsconfig.e2e.json"
    }],
    "test": {
        "karma": {
            "config": "./karma.conf.js"
        }
    },
    "defaults": {
        "styleExt": "css",
        "component": {
            "style": false,
            "template": false
        }
    }
}

**Comment by RicardoVaranda** [comment]
Issue seems to be fixed according to user https://github.com/angular/angular-cli/issues/5989#issuecomment-302464344
