### ISSUE TITLE
ng build Error with OfficeJS

### ISSUE THREAD

**Issue by TheSamsterZA** [angular/angular-cli#6359]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.2
node: 7.10.0
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.3

TypeScript 2.3.2
Visual Studio Code 1.12.1

npm package versions:

```
npm list --depth=0

+-- @angular/cli@1.0.2
+-- @angular/common@4.1.3
+-- @angular/compiler@4.1.3
+-- @angular/compiler-cli@4.1.3
+-- @angular/core@4.1.3
+-- @angular/forms@4.1.3
+-- @angular/http@4.1.3
+-- @angular/platform-browser@4.1.3
+-- @angular/platform-browser-dynamic@4.1.3
+-- @angular/router@4.1.3
+-- @microsoft/office-js-helpers@0.7.1
+-- @types/jasmine@2.5.38
+-- @types/node@6.0.73
+-- @types/office-js@0.0.43
+-- codelyzer@2.0.1
+-- core-js@2.4.1
+-- jasmine-core@2.5.2
+-- jasmine-spec-reporter@3.2.0
+-- karma@1.4.1
+-- karma-chrome-launcher@2.0.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@0.2.3
+-- karma-jasmine@1.1.0
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.1.2
+-- rxjs@5.4.0
+-- ts-node@2.0.0
+-- tslint@4.5.1
+-- typescript@2.3.2
`-- zone.js@0.8.10
```

```
npm list --dev --depth=0
 
+-- @angular/cli@1.0.2
+-- @angular/compiler-cli@4.1.3
+-- @types/jasmine@2.5.38
+-- @types/node@6.0.73
+-- @types/office-js@0.0.43
+-- codelyzer@2.0.1
+-- jasmine-core@2.5.2
+-- jasmine-spec-reporter@3.2.0
+-- karma@1.4.1
+-- karma-chrome-launcher@2.0.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@0.2.3
+-- karma-jasmine@1.1.0
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.1.2
+-- ts-node@2.0.0
+-- tslint@4.5.1
`-- typescript@2.3.2
```

### Repro steps.

```
npm install @microsoft/office-js-helpers --save
npm install @types/office-js --save-dev
```

Then, in `src/main.ts`, add:

```
import { Utilities } from '@microsoft/office-js-helpers';
```

### The log given by the failure.

```
ng build

Hash: 150cb5f78f54c3bec235
Time: 7588ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 232 kB {4} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.js.map (styles) 65.2 kB {4} [initial] [rendered]
chunk    {2} main.bundle.js, main.bundle.js.map (main) 5.01 kB {3} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.43 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in test/node_modules/@microsoft/office-js-helpers/dist/office.helpers.d.ts (303,41): Cannot find namespace 'Excel'.

ERROR in test/node_modules/@microsoft/office-js-helpers/dist/office.helpers.d.ts (303,106): Cannot find namespace 'Excel'.
```

### Desired functionality.

I expected the build to succeed. I have installed the typings, and Visual Studio Code / TypeScript are happy, so I expected the Angular CLI to also be happy.

### Mention any other details that might be useful.

Although it appears [Script Lab](https://github.com/OfficeDev/script-lab) isn't using the Angular CLI, they are using Angular 4 and their Webpack build succeeds.

I have already tried matching the versions of `@types/office-js` and `@microsoft/office-js-helpers` with those in Script Lab, and `ng build` still fails.

Related issue: https://github.com/OfficeDev/office-js-helpers/issues/28.

**Comment by clydin** [comment]
Types are opt-in for the application itself.  You can add `office-js` to the `types` array in `tsconfig.app.json`.

**Comment by TheSamsterZA** [comment]
@clydin That works, thanks. :/

```
tsconfig.app.json

{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    ...
    "types": [
      "@types/office-js"
    ]
  },
  ...
}
```

Not quite sure why I need to do that though, because:

```
tsconfig.json

{
  ...
  "compilerOptions": {
     ...
    "typeRoots": [
      "node_modules/@types"
    ],
    ...
  }
}
```
which I expected the Angular CLI to use to find the office-js types.

So,  there's a workaound, but I still feel like this is a bug that should be fixed.

**Comment by clydin** [comment]
The `@types/` part of `@types/office-js` shouldn't be needed in the `types` array.

The behavior is intentional. `typeRoots` defines where types can be found.  `types` defines which of the found types will be used.  An empty array means no types will be used.  Unit and E2E tests use types (e.g., `node` and `jasmine`) which are not relevant (and may be problematic) to the application itself and therefore the application uses the opt-in approach to ensure that only required types are used.

**Comment by TheSamsterZA** [comment]
> The @types/ part of @types/office-js shouldn't be needed in the types array.

You're right, of course. Thank you.

> The behavior is intentional. `typeRoots` defines where types can be found. `types` defines which of the found types will be used.

Is there documentation that explicitly states this as the case? I think it would be quite beneficial for newcomers (like me) who are learning as they go, and who make incorrect assumptions.

**Comment by mrsquish** [comment]
Hey TheSamsterZA,

I'm trying to do something very similar, basically trying to bootstrap an Angular CLI project into an Excel Addin project. I'd be interested in hearing how your achieving this and what your experiences have been.

**Comment by TheSamsterZA** [comment]
HI @mrsquish,

It took me quite a bit of fiddling to get to the point where I could develop an OfficeJS add-in using Angular 4. Here's a quick-and-dirty list of things I did:

### Prerequisites

```
ng new
```

Add OfficeJS CDN link to a `<script>` tag in `index.html`:
```
<script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
```

Install OfficeJS-related dependencies:
```
npm install @microsoft/office-js-helpers --save
npm install office-ui-fabric-core --save
npm install office-ui-fabric-js --save
npm install jquery --save
```

Install OfficeJS-related dev-dependencies:
```
npm install @types/office-js --save-dev
npm install @types/jquery --save-dev
```

Add missing type declarations:

```
tsconfig.app.ts

{
  ...
  "compilerOptions": {
    ...
    "types": [
      "office-js"
    ]
  },
  ...
}
```

Bootstrap OfficeJS:

```
main.ts

Office.initialize = () => {
  const platform = platformBrowserDynamic();
  platform.bootstrapModule(AppModule);
};
```
### Hosting

I use the Angular CLI to host in my dev environment.

[Create a self-signed certificate using OpenSSL](https://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl) and save the files in an `ssl/` folder. Then:

```
ng serve --port 44301 --ssl --ssl-key ssl\development-certificate.key --ssl-cert ssl\development-certificate.crt
```

### OfficeJS Manifest File

In my case, I already had a manifest file which I [side-load into Office](https://dev.office.com/docs/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins). You can create one using the [Yeoman generator for Office](https://github.com/OfficeDev/generator-office).

Remember to update the URLs in there to point to the in-memory server loaded by `ng serve`.

### Miscellaneous Stuff

I am using VSCode as my IDE, but you _could_ use Visual Studio proper with a few changes:

You'll need a solution file containing the manifest project (with the above manifest file) and the web project containing the files in your Angular project.

DO NOT make the SSL port on the web project the same as the one `ng serve` uses. We will let VS _think_ it's hosting the add-in via IIS Express but in reality our manifest points to the in-memory server hosted by the Angular CLI.

Install the Visual Studio extension [NPM Task Runner](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.NPMTaskRunner).

Add VS bindings:

```
project.json

{
  ...
  "scripts": {
    "setup": "npm install",
    "start": "powershell start-process ng-serve.bat",
    "clean": "rimraf dist"
  },
  "-vs-binding": {
    "BeforeBuild": [
      "start"
    ],
    "Clean": [
      "clean"
    ],
    "ProjectOpened": [
      "setup"
    ]
  }
  ...
}
```

Create that batch file:

```
ng-serve.bat

REM Kill any previously-running ng serve
powershell -Command "& Get-WmiObject Win32_Process -Filter \"name = 'cmd.exe'\" | where {$_.CommandLine.Contains(\"ng\") -And $_.CommandLine.Contains(\" serve \")} | ForEach-Object { TASKKILL /PID $_.ProcessId /T /F }"

REM Run ng serve
start ng serve --port 44301 --ssl --ssl-key ssl\development-certificate.key --ssl-cert ssl\development-certificate.crt
```

Why go through all this trouble for VS? Because debugging with breakpoints is easier and there's that nice "hit F5" experience.

I haven't yet tried to debug with VSCode but my quick dabble didn't work. I can still use [F12 Developer Tools](https://msdn.microsoft.com/en-us/library/bg182326(v=vs.85).aspx) in IE to debug though.

This got a little long but hopefully you find it useful. :)

**Comment by TheSamsterZA** [comment]
Closing since [@clydin's comment](https://github.com/angular/angular-cli/issues/6359#issuecomment-302564567) fixes my problem.

**Comment by mrsquish** [comment]
TheSamsterZA - Thanks heaps for that mate. It would seem that decent info on Office.js is pretty few and far between. I'm currently using VSCode with side loading, but I'll give your VS solution a bash, being a predominantly c# dev, I do like the f5 experience :)
