### ISSUE TITLE
Scripts are included in the wrong order

### ISSUE THREAD

**Issue by jasonswett** [angular/angular-cli#637]
This SO question/answer of mine pretty much says it all: http://stackoverflow.com/questions/37050830/ngoninit-not-triggered-on-page-load

There's apparently a bug in Angular 2 that only surfaces if certain scripts are included in a certain order, but not in a certain other order. Seems like if the order of the scripts can be controlled within Angular CLI, might as well put them in the order that doesn't surface the bug.

I'd be willing to try to implement the fix.

**Comment by metric152** [comment]
Is that this bug?
https://github.com/angular/angular-cli/pull/623

**Comment by jasonswett** [comment]
I can't say if it's that bug or not but I installed Angular CLI version 0.1.0 and the problem doesn't seem to be present anymore.
