### ISSUE TITLE
ng test and two source folders

### ISSUE THREAD

**Issue by netTrek** [angular/angular-cli#6371]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.3
node: 7.5.0
os: darwin x64

macOS (Sierra?)

### Repro steps.

- create new projekt with cli
- edit tsconfig to work with two source folders
    "paths": {
      "@modules/*": [ "../@modules/*" ]
    }
- use new karma test context for both folder
const context = require.context('../', true, /\/(@modules|src)\/.*\/.*\.spec\.ts$/);
- run 'ng test'

### The log given by the failure.
I’m working with two source folders. Therefore I have implemented the context, in order that tests will be searched in two folders. 

const context = require.context('../', true, /\/(@modules|src)\/.*\/.*\.spec\.ts$/);

If I’m starting ng test, only tests from src run. If I start the test again through a watcher, all tests are found. It is crazy, that an abort with „Error in“ comes with the third reload and with the fourth reload everything is found again and running. These two conditions repeat with every other reload. Can I use ng test only with every „straight“ run reliably? Could be difficult to define in my Jenkins environment.

BTW: Whenever the tests are not in the default source folder. No tests will be found
see http://stackoverflow.com/questions/44047895/karma-finds-no-test-files-on-start-but-finds-every-file-when-reloading/44052076#44052076 also.

### Desired functionality.
All test-files should be found

### Mention any other details that might be useful.

THX Saban

**Comment by Brocco** [comment]
Can you please provide some steps to reproduce this issue? Ideally this would be via a github repo.

**Comment by netTrek** [comment]
Hi,

here the repo: https://github.com/netTrek/angular-cli-issues

Repro steps.

  *   create new projekt with cli
  *   edit tsconfig to work with two source folders
"paths": {
"@modules/": [ "../@modules/" ]
}
  *   Use a Component from the second Source-Folder
  *   use new karma test context for both folder
const context = require.context('../', true, //(@modules<https://github.com/modules>|src)/./..spec.ts$/);
  *   run 'ng test'

Warm regards

___
Saban Ünlü


Von: Mike Brocchi <notifications@github.com>
Antworten an: angular/angular-cli <reply@reply.github.com>
Datum: Donnerstag, 18. Mai 2017 um 19:23
An: angular/angular-cli <angular-cli@noreply.github.com>
Cc: "info@netTrek.de" <info@nettrek.de>, Author <author@noreply.github.com>
Betreff: Re: [angular/angular-cli] ng test and two source folders (#6371)


Can you please provide some steps to reproduce this issue? Ideally this would be via a github repo.

**Comment by netTrek** [comment]
In my case it works, when I move die @modules folder inside die src folder.
See: https://github.com/netTrek/angular-cli-issues/tree/works
But it would be much cooler, when we could use more then one source folders.

**Comment by filipesilva** [comment]
@netTrek we don't directly support that usecase and there's a fair number of things that can go wrong with it from a setup point of view.

There's some limited support for multiple apps (https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/multiple-apps.md), but currently no support for libraries (https://github.com/angular/angular-cli/issues/1692).

**Comment by filipesilva** [comment]
I should mention that with `1.1.0-rc.0` a new test plugin was introduced which may (or may not) help in your usecase.
