### ISSUE TITLE
File cannot be found after CLI upgrade

### ISSUE THREAD

**Issue by yvessabourin** [angular/angular-cli#6372]
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.3
node: 6.9.2
os: darwin x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/platform-server: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.3
@angular/compiler-cli: 4.0.1
Mac OS: 10.12.5
zone.js: 0.8.5


### Repro steps.
After migrating to Angular 1.0.3 the angular http.get method cannot find the file is should. zone.js raises an exception.


### The log given by the failure.
<!-- Normally this include a stack trace and some more information. -->


### Desired functionality.
Recover the initial functionality with a fix or a workaround.


### Mention any other details that might be useful.
<!-- Please include a link to the repo if this is related to an OSS project. -->

**Comment by yvessabourin** [comment]
I proceeded with a clean creation of the application in order to eliminate the possibility of a migration error. I resolved all compilation errors, but the result is the same. In the migration I had zone.js 0.8.5, but the new creation downgraded to zone.js 0.8.4.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
