### ISSUE TITLE
Incorrect position at file for AOT compilation error

### ISSUE THREAD

**Issue by x1unix** [angular/angular-cli#6374]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.3
node: 6.10.2
os: darwin x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.3
```

### Repro steps.
When I'm trying to serve a project using AOT (`ng serve --aot`), I have errors:

```
ERROR in ng:///Users/dsedchenko/Projects/limon-ng2/src/app/ports/ports.component.html (35,15): Supplied parameters do not match any signature o
f call target.
```

But there is no function call at that position:

**ports.component.html**
```
           <div class="table-wrapper"
              [guCollection]="events"
              [guLimit]="selectedPortsPerPage"
              [guFilter]="filter"
              [guPage]="currentPage"
              [guGroup]="groupProperty"
              [guSearch]="searchQuery"
              [guSearchProps]="searchProps"
              [guSort]="sortProp"
              [guSortDirection]="sortDir"
              (guOnReady)="onCollectionSort($event)"
              (guOnRefresh)="onCollectionRefreshing($event)"
              [hidden]="isLoading"> <!-- This line (35, 15) -->
```
**ports.component.ts**

```
public selectedPercent: string = 'empty'; // This line (35,15)
```

When I remove a specified line - I get the same error at the same position.

### The log given by the failure.
```
ERROR in ng:///Users/odin3/Projects/project/src/app/events/events.component.html (35,15): Supplied parameters do not match any signature o
f call target.
```

### Desired functionality.
Correct error file location and more informative error

**Comment by Brocco** [comment]
Are you getting the same error when running `ng build --aot`?

**Comment by tytskyi** [comment]
> events.component.html (35,15)

> ports.component.ts

wrong file?

**Comment by odin3** [comment]
@tytskyi, position at file (line number, char number)

**Comment by clydin** [comment]
I believe @tytskyi was suggesting that you may be looking in the wrong file.  The error is in `events.component.html` but the file shown above appears to be `ports.component.html`.

**Comment by odin3** [comment]
@clydin, sorry, I took error from a wrong file. But I had the same situation with ```ports.component.html```

**Comment by frostbytedata** [comment]
Any updates on this? I am seeing a very similar error whereby the `Supplied parameters do not match any signature of call target.` error is pointing to a place in the html where there is no function call. It is a static 
 hard-coded HTML <span> tag. Thanks!

**Comment by mackelito** [comment]
do you get the error if you run ´ng serve --aot=false´ ?

**Comment by odin3** [comment]
@mackelito, no. Everything runs well

**Comment by muffinrecon** [comment]
Getting a similar error to this. Pointing to a <li> tag in the html.

**Comment by mateuswetah** [comment]
Hey guys, facing the same problem here. 

My `ng build --aot` (or `--prod`) points to a _....component.html (405,13): Supplied parameters do not match any signature of call target._ But the line is really just a _</div>_... 

There must be some way to check this kind of error before all the AOT do it's magic.... it actually surprises me that it passes on normal compilation :(

**Comment by vaidd4** [comment]
I often get the same problem. When it occurs (for me), it's always due to the fact that the line mentionned doesn't count empty or coment lines.

**Comment by mgechev** [comment]
Is this issue still reproducible?
