### ISSUE TITLE
ng test running in watch mode by default

### ISSUE THREAD

**Issue by tapas4java** [angular/angular-cli#638]
`ng test` command runs test in watch mode. Watch mode should only enabled if user provides -w flag

**Comment by bschlosser** [comment]
I tripped over this in our CI environment too. Added `--watch false` to get passed it for now. Not a fan of defaulting boolean flags to true.

**Comment by alexandermikuta** [comment]
I changed autoWatch to false in karma.conf.js as workaround...

**Comment by hansl** [comment]
Yes, `autoWatch` is true by default in karma. If that's not what you want, you should change that value and `ng test` will us it.

Cheers!

**Comment by ciroque** [comment]
+1 watch by default is not desirable
