### ISSUE TITLE
ng serve compiles all files in src directory, even those not imported anywhere

### ISSUE THREAD

**Issue by pcroc** [angular/angular-cli#6382]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.2
node: 7.9.0
os: linux x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.3
```

### Repro steps
1. Add a .ts file somewhere within your src tree (e.g. /src/app/dummy.ts) containing some code that does not compile.
2. `ng serve`
3. Note that the compiler complains about the added file dummy.ts even though it is not imported from anywhere

### The log given by the failure.
N/A

### Desired functionality.
Only .ts files that are explicitly imported from somewhere (starting in main.ts) are compiled.

### Mention any other details that might be useful.
I am migrating a large project from an old version of Angular 2 and would like to comment out imports for components/services/etc which are broken, until they are fixed. The compiler seems to be attempting to build everything within src so I am forced to completely remove or modify such files (and of course still comment out the imports).

**Comment by filipesilva** [comment]
This isn't controlled by the CLI directly, but rather by `src/tsconfig.app.json`. If you add `"files": [ "main.ts" ]` there, you will get the behaviour you want.

Although, whether or not we do that by default for new project is a discussion point.

**Comment by shivangsanghi** [comment]
Mine case is opposite. Files are not added if they are imported. In my project, i need such scenario where all  files should be added. Is there any way to achieved this apart from files.

**Comment by clydin** [comment]
Closing as it is intended that all files configured via the application's `tsconfig` are compiled.  This also mimics `tsc` behavior.
