### ISSUE TITLE
SCSS Compile error "Invalid CSS after"

### ISSUE THREAD

**Issue by squadwuschel** [angular/angular-cli#6388]
- [x ] bug report -> please search issues before submitting

### Versions.
@angular/cli: 1.0.4
node: 7.0.0
os: win32 x64
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.4
@angular/compiler-cli: 4.0.0

### Repro steps.
I want to migrate my NG2 project from my own webpack compillation to the CLI and I was using scss in my old webpack compiller.

I've created a new project with the cli and set the scss 

     ng set defaults.styleExt scss

when I now try to ng build the project I get the following error for all my scss files

### The log given by the failure.

    ERROR in ./App/app.component.scss
     Module build failed:
     undefined
          ^
         Invalid CSS after ".test {": expected "}", was "{"
          in C:\TFS\DEV\80_Internal\Internal.WebLogViewer\R0.7_Angular4Update\10_Gui\Web\App  \app.component.scss (line 10, column 8)
        @ ./App/app.component.ts 92:17-48
        @ ./App/app.module.ts
        @ ./App/main.ts
       @ multi ./App/main.ts

### Desired functionality.

that I can compile the SCSS Files from my components

### Mention any other details that might be useful.

I am also using Bootstrap 4 with scss and Font Awesome with scss.

thats my source dir

![grafik](https://cloud.githubusercontent.com/assets/1572878/26250187/90d4c95c-3ca9-11e7-837c-2e3ca372f7fe.png)

that are the settings in my .angular-cli.json
      
     "styles": [
         "styles.sass"
        ],
       ....
  
       "defaults": {
           "styleExt": "scss",

the content from my "styles.sass"

    @import 'variables';
    @import '../node_modules/bootstrap/scss/bootstrap';
    @import '../node_modules/font-awesome/scss/font-awesome';
    @import "~@progress/kendo-theme-default/scss/all";

my _variables.scss file content

    $icon-font-path: '../node_modules/bootstrap-sass/assets/fonts/bootstrap/';
    $fa-font-path: '../node_modules/font-awesome/fonts';

**Comment by RicardoVaranda** [comment]
Hi @squadwuschel , 

Not sure if it's by mistake but you styles extension is sass not scss as you defined in the styleExt.
You can fix this by one of two ways

1. Leave the dafaults.styleExt as `scss` and rename your `styles.sass` to `styles.scss`
2. Change your defaults.styleExt to `sass`

**Comment by RicardoVaranda** [comment]
Hi @squadwuschel,

Could you please post your ./App/app.component.scss

The error appears to be in line 10.

**Comment by squadwuschel** [comment]
hi,

I've deleted the hole project and I've reloaded all files again and then it was working. thx for your help.

**Comment by gopalarajanaika** [comment]
i have same issue
