### ISSUE TITLE
ng build --prod Does not work with static properties

### ISSUE THREAD

**Issue by jhertz123** [angular/angular-cli#6394]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/compiler-cli: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/platform-server: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0

### Repro steps.
* Create a static class MyClass
* Create a public static myTest :string = "Hello bug"; in MyClass
* Create a component MyComponent 
* Create a getter for the class in MyComponent `get myClass():MyClass{return MyClass;}`
* Use myClass in the template accessing the static field `{{ myClass.myTest  }}`

### The log given by the failure.
my-component.component.html (4,1): Property 'myTest ' does not exist on type 'MyClass'.

### Desired functionality.
Access to static fields in a class from the template.

### Mention any other details that might be useful.
Does not happen when using ng build --prod --aot=false

**Comment by clydin** [comment]
Static methods are accessible from the class type itself ("MyClass") not the instance of the class.
You can read further here: https://www.typescriptlang.org/docs/handbook/classes.html

**Comment by jhertz123** [comment]
Sorry if I were unclear in my description. I am not using a instance of the class. It is just a get property in the component so it can be referenced in the template. 

(let me know if this is still unclear)

**Comment by clydin** [comment]
You've defined an accessor that returns an object instance of type MyClass.  Also as written above you should be getting a stackoverflow error as it is calling itself.
You should (never tried myself though) be able to export MyClass and use the type and property directly.

**Comment by jhertz123** [comment]
No, I return the actual class, not an instance. The class has static fields that can be accessed in code. The problem is while building it for prod, that is when I get the above error. 

Another way of "fixing" it is changing the return type of the getter to any.

**Comment by clydin** [comment]
The return type of the accessor is the relevant aspect of the issue.  The above accessor has a return type of MyClass which means according to typescript it will return an instance of MyClass.  Changing it to "any" essentially disables type checking.  Targeting production enables AOT compilation which compiles the templates into code and therefore enables (among other things) an additional level of error detection for the templates.  Type checking being a major one.  This is why you see the error only for production.
