### ISSUE TITLE
Add a parameter to set "subfolder" for the generated files in the index.html

### ISSUE THREAD

**Issue by squadwuschel** [angular/angular-cli#6395]
- [x ] feature request

### Versions.
    @angular/cli: 1.0.4
    node: 6.10.3
    os: win32 x64
    @angular/common: 2.2.1
    @angular/compiler: 2.2.1
    @angular/core: 2.2.1
    @angular/forms: 2.2.1
    @angular/http: 2.2.1
    @angular/platform-browser: 2.2.1
    @angular/platform-browser-dynamic: 2.2.1
    @angular/platform-server: 2.2.1
    @angular/router: 3.2.1

### Desired functionality.

- I'am using .NET Web Application with NG2 as frontend framework and currently I've created my own webpack configuration, that works so far, but It would be nice if I could switch to the Angular CLI

## My current Situation:

- webpack generates the NG2 code into the "wwwroot" folder, but this folder is just a "subfolder" in my Webapplication and so the Path to the javascript and style files in my indext.html looks like

      <link href="/wwwroot/vendors.css" rel="stylesheet"></head>
      <script type="text/javascript" src="/wwwroot/polyfills.bundle.js"></script>
      <script type="text/javascript" src="/wwwroot/vendors.bundle.js"></script>
      <script type="text/javascript" src="/wwwroot/app.bundle.js"></script>

so the IIS returns the index.html and all Client side files are generated into the wwwroot.

and when I use HMR then webpack creates a webserver which generates me the source files and the authentication and so on works just in the IIS, then the index.html looks like 

      <link href="http://localhost:4356/vendors.css" rel="stylesheet"></head>
      <script type="text/javascript" src="http://localhost:4356/polyfills.bundle.js"></script>
      <script type="text/javascript" src="http://localhost:4356/vendors.bundle.js"></script>
      <script type="text/javascript" src="http://localhost:4356/app.bundle.js"></script>

### Feature Request

add the possibility to create a Build where you can specify the "subfolder" Path like "wwwroot" for the Script files like mentioned above and perhaps add a ng serve with hmr feature where the server itself only hosts the sources files, so that you can use your own Server like IIS what makes the authentication easier.

**Comment by clydin** [comment]
The "--deploy-url" option provides the functionality requested.

For that second part you could also use "ng build --watch" and serve with whatever server you prefer.  Obviously you lose live reload.  Multiple people have mentioned using this setup with IIS.

**Comment by squadwuschel** [comment]
@clydin thaks the "--deploy-url " is what I am looking for - description should perhaps be modified because that I never expected for the current description.

for the second part  - currently I am using hmr and its quite nice :-), perhaps such a feature ist possible in the future with "ng serve  --remote" or something

**Comment by clydin** [comment]
Your welcome.  I'll make a note for the documentation.
You can also use an absolute URL for the "--deploy-url" option and their is an "--hmr" option so you might be able to get it working with some experimenting.  Note that your application will need to add the relevant hot reloading code as the hmr option only enables the serving portion.

**Comment by Brocco** [comment]
Closing as this seems to be resolved via the `deploy-url` flag.
