### ISSUE TITLE
Issue when deploying to github page

### ISSUE THREAD

**Issue by chiholiu** [angular/angular-cli#6396]
Mixed Content: The page at 'https://chiholiu.github.io/coolpad/' was loaded over HTTPS, but requested an insecure script 'http://chiholiu.github.io/coolpad/inline.ba791ab170d77bc756d4.bundle.js'. This request has been blocked; the content must be served over HTTPS.

Mixed Content: The page at 'https://chiholiu.github.io/coolpad/' was loaded over HTTPS, but requested an insecure script 'http://chiholiu.github.io/coolpad/inline.ba791ab170d77bc756d4.bundle.js'. This request has been blocked; the content must be served over HTTPS.

Anyone here who knows how to solve this issue? I have executed all the steps mentioned in the online tutorial, but when I want to open https://chiholiu.github.io/coolpad/, I get the error which is shown above.

**Comment by delasteve** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by sumitarora** [comment]
Closing as above.
