### ISSUE TITLE
Add the ability to generate routes

### ISSUE THREAD

**Issue by dpurp** [angular/angular-cli#64]
Consider generating the initial app integrated with component router.

Add the ability to generate new routes, with something like:

```
ng generate route 'heroes/:id'  hero-details-component
```

**Comment by vikeen** [comment]
How do you see the routes getting created? Where would they live?

**Comment by dpurp** [comment]
hmm.. I was expecting a single, top-level routes file.

I can see how projects may want to register their routes in a sub-folder, but it seems like that would be more of an advanced user case.  For the casual user wanting to start a new Angular2 project, it would be nice if routing worked "right-out-of-the-box."

**Comment by IgorMinar** [comment]
My current thinking is that routes should really be routable components. These unlike regular components get generated in as a nested directory structure that maps to the route directory structure.

**Comment by filipesilva** [comment]
I can pick this up soon.

**Comment by samjulien** [comment]
@filipesilva I am happy to help out with this too. I'm still learning ng2 but this project is great - the ember-cli is super useful.

**Comment by filipesilva** [comment]
@samjulien thanks! I think it's going to be easy enough, but adding routes will need these two PRs in as well https://github.com/angular/angular-cli/issues/66 https://github.com/angular/angular-cli/pull/100

@IgorMinar Routable components seems the way to go, like described [here](https://angular.io/docs/ts/latest/guide/router.html#!#child-routing-component) in angular.io. Maybe even doing the routable component + list component + detail component + service all at once.

Thus, running

```
ng generate route heroes
```

Would generate the following folder structure
```
...
|-- app
|   |-- ...
|-- heroes
|   |-- heroes.component.ts
|   |-- heroes-detail.component.ts
|   |-- heroes-list.component.ts
|   |-- heroes.service.ts
|-- app.ts
...
```

And would add the child route definition to the router in `app.ts`:

```
...
  {
    path: '/heroes/...',
    name: 'Heroes',
    component: HeroesComponent
  },
...
```

**Comment by filipesilva** [comment]
I've a PR proposal for route generation in https://github.com/angular/angular-cli/pull/139. It does somewhat more than adding a single route.
