### ISSUE TITLE
Following wiki guide to setup bootstrap does not work

### ISSUE THREAD

**Issue by guoliang** [angular/angular-cli#6401]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.4
node: 7.4.0
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.4
@angular/compiler-cli: 4.1.3

  Windows 10
```
### Repro steps.

1. ng new bootstrap-test-project
2. cd to project and run `yarn add bootstrap`
3. Follow this [wiki](https://github.com/angular/angular-cli/wiki/stories-include-bootstrap) to setup Bootstrap3
4. ng serve
5. go to localhost:4200

### The log given by the failure.
Nothing is displayed in console

### Desired functionality.
Button example using bootstrap CSS should be shown, but it is just normal standard styling

**Comment by clydin** [comment]
Did you follow the CSS or SASS instructions?
Based on the repo steps above, step 3 should only require the addition of `"../node_modules/bootstrap/dist/css/bootstrap.min.css"` to the `styles` array within `.angular-cli.json`.

**Comment by guoliang** [comment]
Strange, I tried it now again, however in OS X, and it works. I followed the step which you use the CSS version of Bootstrap. I'm going to retry it again when I'm on a Windows machine.

**Comment by Brocco** [comment]
Closing this as it is working for you, if there's an issue when you re-test in Windows, please comment or open another issue.
