### ISSUE TITLE
IE 9 ISSUE

### ISSUE THREAD

**Issue by tata-abhi** [angular/angular-cli#6402]
#6024 ```

I am running with **ng serve** . 

It's working fine for chrome and firefox but not for IE9 + versions.

Please provide the suggesitions.
Thanks in advance.

**Comment by RicardoVaranda** [comment]
Hi @tata-abhi ,

Have you had a look at the `polyfills.ts` file with the src folder?

You need to follow a set of instructions in there on how you can make your application available for IE 9, 10 & 11. Simply read the inline comments for this information.

**Comment by Brocco** [comment]
Yes, the comments in the [polyfills file](https://github.com/angular/angular-cli/blob/9760ef96aac04dc1c28e6ab5f87fd08921585224/packages/%40angular/cli/blueprints/ng/files/__path__/polyfills.ts) will lead you to the appropriate changes.

**Comment by tata-abhi** [comment]
Thanks @RicardoVaranda , @Brocco.... Its working..
