### ISSUE TITLE
ng lint not working

### ISSUE THREAD

**Issue by roopkt** [angular/angular-cli#6411]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

 
```
@angular/cli: 1.0.3
node: 7.10.0
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.3

Windows 2010
```

### Repro steps.

In app.component.spec.ts I have below line
`import { AppComponent } from'./app.component'`
When I run `ng lint` command it shows 2 errors 
```
ng lint
src/app/app.component.spec.ts[4, 24]: Add space after 'from'
src/app/app.component.spec.ts[4, 46]: Missing semicolon
```
then I run `ng lint --fix` it updated the line with below 
`import { AppComponent } from'./app.component;'`
Here is the output
```
ng lint --fix
Fixed 1 error(s) in src/app/app.component.spec.ts

src/app/app.component.spec.ts[4, 24]: Add space after 'from'
src/app/app.component.spec.ts[4, 47]: Missing semicolonAuthLit.Web\authlit-app>

Lint errors found in the listed files.
```

### The log given by the failure.

```
ng lint
src/app/app.component.spec.ts[4, 24]: Add space after 'from'
src/app/app.component.spec.ts[4, 46]: Missing semicolon

ng lint --fix
Fixed 1 error(s) in src/app/app.component.spec.ts

src/app/app.component.spec.ts[4, 24]: Add space after 'from'
src/app/app.component.spec.ts[4, 47]: Missing semicolonAuthLit.Web\authlit-app>

Lint errors found in the listed files.
```

### Desired functionality.

I would like ng lint --fix to update the file with this line
`import { AppComponent } from './app.component';`

**Comment by filipesilva** [comment]
@roopkt running `ng lint --fix` does not automatically fix all linting errors, it only fixes the ones that have an auto-fixer.

You can see the list of linting rules in https://palantir.github.io/tslint/rules/, and the ones that can be automatically fixed are marked with `Has Fixer`.

**Comment by roopkt** [comment]
@filipesilva Thank you very much. I was ignorant of Has Fixer list of angular lint.
