### ISSUE TITLE
GET API request not working in IE

### ISSUE THREAD

**Issue by phani257** [angular/angular-cli#6412]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
bug report
### Versions.

Windows 7

### Repro steps.

```
this.userService.getDashboards().subscribe(dashboardsData => {
    this.dashboardsList = dashboardsData;
});
```
In userService.ts
```
getDashboards() {
    return this._http.get(this._dashboards, { headers: this.getHeaders() })
        .map((res: Response) => res.json());
}
```

This works absolutely fine if I use Chrome. I am able to get the dashboardsList from DashboardData. This fails if I use IE.This is just a get request which works on Chrome but not IE. Does the above dashboardsData => { supported in IE?

**Comment by Brocco** [comment]
This is not an issue with the CLI, I suggest opening a question on a site like StackOverflow or potentially taking this to a gitter channel (angular or angular-cli).

But to answer your question: 
>dashboardsData => { supported in IE?
Yes, that is supported in IE because typescript will transpile it to not use `=>`

**Comment by phani257** [comment]
My tsconfig.json is as below. Does this config settings will take care of IE compatible code when I do ng build. I mean will ng build throw errors if my code is not compatible with IE if I have the below config settings.

{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "target": "es5",
    "experimentalDecorators": true,
    "lib": [
      "es5"
    ]
  }
}
