### ISSUE TITLE
angular cli need a option for building npm modules

### ISSUE THREAD

**Issue by turnerguo** [angular/angular-cli#6416]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.0.4
node: 6.9.5
os: darwin x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.4
@angular/compiler-cli: 4.1.3

macOS El Capitan (10.11.6)

### Repro steps.

When I want to build a npm module I got no options from angular-cli.

### Desired functionality.

Simply, it is better if there is a option for 'ng build' like:
```bash
ng build --npm-module
# or
ng build --npm --output-path=../node-packages/
```

### Mention any other details that might be useful.

It would be very easy for product contains both app and related customised module when using ng cli.

**Comment by Brocco** [comment]
There is an issue open for creating libraries via the CLI, you can track the progress here: #1692 

Closing as a duplicate.

**Comment by turnerguo** [comment]
@Brocco Thanks for reply, I'll track on it.
