### ISSUE TITLE
Improve webpack build using happypack

### ISSUE THREAD

**Issue by Toub** [angular/angular-cli#6419]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

I am not using the very last version, but this is not relevant here.

``` console
@angular/cli: 1.0.0
node: 6.9.5
os: linux x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.0
@angular/compiler: 4.1.0
@angular/compiler-cli: 4.1.0
```

### Desired functionality.

Looks like happypack now deals well with typescript loaders.

What about using it to improve build time?

### Mention any other details that might be useful.

@see  https://github.com/amireh/happypack/issues/33#issuecomment-303216237

**Comment by johnnyreilly** [comment]
In case it's helpful we've put some docs in place: https://github.com/typestrong/ts-loader#happypackmode-boolean-defaultfalse

**Comment by johnnyreilly** [comment]
And it's now in the official happypack documentation as well: https://github.com/amireh/happypack#does-it-work-with-typescript

**Comment by alan-agius4** [comment]
Closing as this doesn't fall in our roadmap especially considering AOT compilation.

**Comment by kondi** [comment]
:( We have more and more threads even in mainstream CPUs, would be useful to benefit in parallelization in project build times. Also, especially useful for AOT compilation, because it takes more time.
Are there other plans for parallelization?
