### ISSUE TITLE
blueprints conflict with format

### ISSUE THREAD

**Issue by FallenRiteMonk** [angular/angular-cli#642]
I just ran ```ng format``` for the first time and figured out that it reformats all the imports.
While creating a component using ```ng g component hero``` creates a import like ```import { Component, OnInit } from '@angular/core';```, running ```ng format``` over it changes that import to ```import {Component, OnInit} from '@angular/core';``` (removes the spaces at the beginning and the end of brackets).
Even though it doesn't break anything, it bothers and I would appreciate it being fixed.
If one could tell me what the right form would be, I would even do it my self.

Thanks and Greetings

**Comment by hansl** [comment]
Hi @FallenRiteMonk!  Thanks for the issue.

It seems like that one slipped in a crack. We're looking at it with the Styleguide team to make sure the `ng format` follows the styleguide. Expect this to be fixed soon.

Cheers!

**Comment by filipesilva** [comment]
Currently `ng format` has been removed so this issue is now obsolete.
