### ISSUE TITLE
Allow to pass a custom filename for component and module

### ISSUE THREAD

**Issue by jooras** [angular/angular-cli#6420]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality.

I think it would be really useful if I could set the custom filename when creating either component or module, ie:
`ng g component CrmClientsTableFilteringWrapper --filename=filtering-wrapper.component.ts`

Sometimes the component names are becoming longer and longer and I need to rename the files manually to make the project tree more readable.

**Comment by Brocco** [comment]
This would be handled by the feature to allow for customization of the blueprints, you can track the progress here #2618. Closing as a duplicate.

**Comment by jimsleon** [comment]
It seems that 'customization blueprint' was released already, does anyone know how to pass a custom filename when creating a component?
