### ISSUE TITLE
Styles are not bundled on --prod mode

### ISSUE THREAD

**Issue by yonatannn** [angular/angular-cli#6422]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.1
node: 6.10.3
os: win32 x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/platform-server: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0

### Repro steps.
1. Withing any ng component refer to .scss file using styles:
@Component({styles: [require('./filter.component.scss')]...
2. Run ng build --prod

Output: the styles are not bundled at all. In --dev mode it works fine. Also tried --extract-css=true & false with no success

### Desired functionality.
The referred CSS are bundled as part of the component JS code. It indeed work that way in --dev mode but not in --prod mode

### Mention any other details that might be useful.
No CLI build errors. Tried to change build aot, extract-css with no luck. When I change my component style decorator to styleUrls (instead of style) it works fine also in production mode.

This works: @Component({styleUrls: ['./filter.component.scss'],
This does NOT work: @Component({ styles: [require('./filter.component.scss')],

**Comment by clydin** [comment]
The `--extract-css` option applies to only global styles.  Component styles are combined and built with the component templates and code itself.

Angular metadata is meant to be statically analyzed.  The first form (i.e., `styleUrls`) is the method that should be used.  The second form works with the development target because the components are compiled and executed at runtime.  Production adds an Ahead-of-Time build step which compiles the components at build time.

**Comment by yonatannn** [comment]
Thanks for your help.

Are you sure that this holds true - "The second form works with the development target because the components are compiled and executed at runtime"?

Based on my understanding, the second form (styles: [require('./filter.component.scss')],Styles), is based on WebPack during build time which feeds the component with all the styles from the referred file. Consequently, if aot happens after webpack concatenation the second form should also work.

Do I miss anything?

**Comment by clydin** [comment]
Webpack will essentially turn the require call into function call that will return a string containing the stylesheet which is then executed at runtime.
Also, the AoT step is one of the first steps as it generates additional code that is then compiled and bundled into the output.

**Comment by sumitarora** [comment]
Closing as above.
