### ISSUE TITLE
ng e2e --watch

### ISSUE THREAD

**Issue by gviligvili** [angular/angular-cli#6424]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.4
macOS -Sierra

When trying to use ng e2e --watch, the tests run once.
I've seen a post here about this issue, but it was closed and it still keep happening.

**Comment by filipesilva** [comment]
We still don't support that, but it's being tracked on https://github.com/angular/angular-cli/issues/2861, which has been reopened.
