### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined common.es5.js

### ISSUE THREAD

**Issue by vighneshbendre** [angular/angular-cli#6430]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Windows 7 Professional
@angular/cli: 1.0.4
node: 6.10.3
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.4
@angular/compiler-cli: 4.1.3
```

### Repro steps.
```
npm -v
3.10.10

node -v
v6.10.3

npm install -g @angular/cli
ng new Angular4
cd Angular4
ng serve
```
### The log given by the failure.
```
ng serve does not throw errors. But browser has following error:

Uncaught TypeError: Cannot read property 'apply' of undefined
combine @ common.es5.js:3091
ENTITIES @ common.es5.js:2941
__webpack_require__ @ bootstrap 6518a66546b9401e7158:52
module.exports @ http.es5.js:2185
__webpack_require__ @ bootstrap 6518a66546b9401e7158:52
webpackJsonp.104 @ src async:7
__webpack_require__ @ bootstrap 6518a66546b9401e7158:52
webpackJsonp.243 @ main.bundle.js:160
__webpack_require__ @ bootstrap 6518a66546b9401e7158:52
webpackJsonpCallback @ bootstrap 6518a66546b9401e7158:23
(anonymous function) @ main.bundle.js:1
```
### Desired functionality.
```
I would like to run a sample application provided in https://cli.angular.io/
```

### Mention any other details that might be useful.
```
This is a fresh start. This system had no node/npm/Angular/CLI installed before.
```

**Comment by grapgrap** [comment]
i have same issue in ie11 only

**Comment by ahmetkizilkaya** [comment]
I have same issue in ie11 and chrome. firefox is well.

**Comment by vighneshbendre** [comment]
Few more details: 
Chrome Version 44.0.2403.157 m.
IE Version 11.0.9600.18638CO

This error occurs even when upgrading from Angular 2

**Comment by librasean** [comment]
I've just encountered this also.
Seems to be browser version dependent, 
Serving a prod build from single web server.
browser running Chrome 44.0.2403.107 has problem
browser running Chrome 48.0.2546.97  ran it fine

**Comment by vighneshbendre** [comment]
Hi, just checking to see if there's any update on the issue...

**Comment by jamsiedaly** [comment]
I would also be interested in any update

**Comment by gioragutt** [comment]
Any update on that?

**Comment by kabb5** [comment]
Anyone come up with a workaround?

**Comment by detonateyin** [comment]
Same problem.Is anyone solved now?

**Comment by kkotak** [comment]
Angular CLI: 1.6.6
Node: 9.2.1
OS: darwin x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

@angular/cdk: 5.1.0
@angular/cli: 1.6.6
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.1.17
typescript: 2.6.1
webpack: 3.10.0

Just started seeing this error on Chrome 63.03239. Only shows with prod build.


main.0df4f12bc48121b66222.bundle.js:1 ERROR TypeError: Cannot read property 'apply' of undefined
    at e.project (main.0df4f12bc48121b66222.bundle.js:1)
    at e._next (main.0df4f12bc48121b66222.bundle.js:1)
    at e.next (main.0df4f12bc48121b66222.bundle.js:1)
    at e._next (main.0df4f12bc48121b66222.bundle.js:1)
    at e.next (main.0df4f12bc48121b66222.bundle.js:1)
    at e.next (main.0df4f12bc48121b66222.bundle.js:1)
    at e._next (main.0df4f12bc48121b66222.bundle.js:1)
    at e.next (main.0df4f12bc48121b66222.bundle.js:1)
    at n.observe (main.0df4f12bc48121b66222.bundle.js:1)
    at e.dispatch (main.0df4f12bc48121b66222.bundle.js:1)


Interestingly Firefox 59.0b4 shows the following instead - 

ERROR 
TypeError: c.a.merge is undefined
Stack trace:
fn/</<@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:1264165
5jKg/r</e.prototype._next@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:196719
E9/g/a</e.prototype.next@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:337931
E9/g/a</e.prototype._next@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:338248
E9/g/a</e.prototype.next@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:337931
TO51/c</e.prototype.next@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:1002683
E9/g/a</e.prototype._next@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:338248
E9/g/a</e.prototype.next@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:337931
PAZ8/o</n.prototype.observe@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:646762
YRqN/r</e.dispatch@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:1191340
GTlS/u</e.prototype._execute@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:391880
Gcw1/o</e.prototype.execute@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:393145
wclm/i</e.prototype.flush@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:7661648
Gcw1/o</e.prototype.schedule@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:393018
wclm/o</n.prototype.schedule@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:7661263
cDNt/on</n.prototype.schedule/<@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:1262146
eFQL/</</</u</t.prototype.invoke@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:44995
eFQL/</</</o</e.prototype.run@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:40149
cDNt/on</n.prototype.schedule@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:1262114
YRqN/r</e.prototype.scheduleMessage@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:1191447
YRqN/r</e.prototype._next@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:1191552
E9/g/a</e.prototype.next@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:337931
PAZ8/o</n.prototype.observe@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:646762
Bu8b/s</e.dispatch@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:308187
GTlS/u</e.prototype._execute@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:391880
GTlS/u</e.prototype.execute@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:391696
wclm/i</e.prototype.flush@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:7661648
eFQL/</</</u</t.prototype.invokeTask@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:45670
onInvokeTask@http://localhost:8080/main.31c90e2b90310b432853.bundle.js:1:508447
eFQL/</</</u</t.prototype.invokeTask@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:45583
eFQL/</</</o</e.prototype.runTask@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:40840
eFQL/</</</c</e.invokeTask@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:46784
e/this.invoke<@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:46666
c/n.args[0]@http://localhost:8080/polyfills.75d6e1366e9ec579513e.bundle.js:1:62984

**Comment by filipesilva** [comment]
I tried running a CLI app created with the latest CLI version on IE 11 and could get it to run.

These are the important things you should do:
- If you need to support IE11, make sure to uncomment the polyfills in `./src/polyfills.ts` for the IE version you need. 
- Depending on the version of Angular CLI you use, some of the performance optimizations might not work on older browsers when running `ng serve`. These optimizations don't affect `ng build` as they are only meant for debugging during development.

To use a different server to serve the contents of `dist/`, you can install `http-server`:
- `npm install -g http-server`
- `ng build`
- `http-server dist/` (this serve the dist folder on http://localhost:8080/).

Although this is somewhat bothersome, it's not that common that developers use IE11 to debug their apps so we think the reduced rebuild time on `ng serve` is worth it.
