### ISSUE TITLE
Ng Generator does not save components in correct directory

### ISSUE THREAD

**Issue by iamclaytonray** [angular/angular-cli#6431]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.3
node: 7.10.0
os: darwin x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.3

### Repro steps.

`ng new my-app`
`cd my-app/src/app && mkdir components`
`cd components`
`ng g component posts`

Those are the only steps I took. I didn't touch the code. I just ran those commands. However, the posts component did not save under the `components` directory. They were saved in the `app` directory, even though I was in the `components` directory when running the generator. I am pretty new to Angular (first day) so I am not sure if that is the expected result or not. I wouldn't imagine that being the case, though.

### The log given by the failure.
No logs. 

### Desired functionality.

The answer is for both questions. When you are in a specific directory and run `ng g component component-name`, the generated files should be a child of your current directory via the command line.

### Mention any other details that might be useful.

Here's a screenshot of the file structure.
<img width="262" alt="screen shot 2017-05-23 at 7 56 55 pm" src="https://cloud.githubusercontent.com/assets/16495816/26381339/09c8fd1a-3ff2-11e7-9a7f-79b284265dc4.png">

**Comment by sumitarora** [comment]
@iamclaytonray `ng` command runs relative to you project location. To generate components to a specific folder you can just do `ng g c components/hello` which will generate hello component in `src\app\components` folder.

**Comment by iamclaytonray** [comment]
Ahh, okay. That worked for me. Maybe that could be a future feature? It seems like it would be more logical to be absolute over relative.

**Comment by sumitarora** [comment]
@iamclaytonray It is the default behavior as all other commands run based on root `ng s`, `ng b`, `ng test` etc. no matter where in the project path you are.

**Comment by iamclaytonray** [comment]
I didn't think or expect that to be the behavior, especially for Google's codebase but I just dealt with it. Honestly, I didn't entertain Angular after that and moved to React. I could test it out again and see what the results are, if you'd like?

**Comment by chriscurnow** [comment]
@iamclaytonray - no problems. No need to test it out. I'm quite happy it works. I just didn't want others coming to this answer and think Angular was harder than it was.
