### ISSUE TITLE
ng-xi18n: Relative path for context-type="sourcefile" instead of absolute path

### ISSUE THREAD

**Issue by rubyduby** [angular/angular-cli#6439]
### Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
When extracting language specific strings with ng-xi18n the context of the string is saved by writing the sourcefile and linenumber into the xlf file. However the context saving the sourcefile is saving the absolute path including os-specific drive etc, which is quite annoying if there are more people working on a project and you want to keep track of the position of language strings.

### Versions.
@angular-cli: 1.0.0

### Repro steps.
Using **ng-xi18n --i18nFormat=xlf** in a project on windows/mac os will yield different filepaths in ```<context context-type="sourcefile">``` tags.

### Desired functionality.
Use a path relative to project root that is not os-specific.

**Comment by r-ising** [comment]
+1

**Comment by ocombe** [comment]
Hello, thanks for the report but this is a bug in angular, not in the cli. Follow the issue here: https://github.com/angular/angular/issues/16639
I'm closing this one.
