### ISSUE TITLE
CSS3 `grid-template-columns` property gets ignored

### ISSUE THREAD

**Issue by Kamilius** [angular/angular-cli#6445]
### Bug Report
```
- [ x] bug report
```

### Versions.
@angular/cli: 1.0.2
node: 6.10.3
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.3
node: v6.10.3
npm: v3.10.10
Windows 10
Chrome v58.0.3029.110

### Repro steps.
1. Add properties: 
```css
display: grid;
grid-template-columns: 50px repeat(12 1fr) 50px;
```
to any element's styles
2. Wait for build and page reload.
3. `grid-template-columns` was removed from element's properties, and isn't visible in dev-tools

### The log given by the failure.
No error logs, everything seems fine

### Desired functionality.
CSS3 Grid properties aren't removed from compiled CSS

**Comment by filipesilva** [comment]
Sounds like a bug alright, no idea why that gets taken out.

**Comment by classicmatsuo** [comment]
@Kamilius you are missing a comma after the parameter number 12.

display: grid;
grid-template-columns: 50px repeat(12**,** 1fr) 50px;

from https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns:
/* <auto-track-list> values */
grid-template-columns: 200px repeat(auto-fill, 100px) 300px;

**Comment by sumitarora** [comment]
@Kamilius Is it still the issue after making above fix?

**Comment by okozolin** [comment]
Seems like @classicmatsuo offered a valid solution and it has been a while . So maybe we should consider closing this issue.

**Comment by shairez** [comment]
@Brocco ☝️

**Comment by filipesilva** [comment]
Thanks @okozolin and @shairez, closing now 👍

**Comment by j4nma11ew** [comment]
guys still im getting this error, says unexpected token 'fr'

**Comment by filipesilva** [comment]
@j4nma11ew I'm not sure that's the same. Can you open a new issue please?

**Comment by jarbydacillo** [comment]
![image](https://user-images.githubusercontent.com/16823254/38240001-fe41c566-3736-11e8-888f-fa8ea86e9281.png)

**Comment by Nicxzmiller** [comment]
hello, if you're still facing this issue, check your html file. probably have to do with your class attributes. make sure all the items to be used are under a single glass which takes the arguments under your-projects container. i suggest introduction of sass to your project.
