### ISSUE TITLE
This error manifets only with ng build --prod  if I do ng build without production flag all is good

### ISSUE THREAD

**Issue by diegomary** [angular/angular-cli#6446]
endered]
chunk    {5} inline.30992410119167cbbf85.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in C:/Users/Diego/Desktop/Ang2NodeOauthJWT/FrontendNg2/src/$$_gendir/app/components/appcomponent/app.component.ngfactory.ts (289,78): Property 'token' does not exist on type '{}'.

ERROR in C:/Users/Diego/Desktop/Ang2NodeOauthJWT/FrontendNg2/src/$$_gendir/app/components/appcomponent/app.component.ngfactory.ts (289,78): Property 'token' does not exist on type '{}'.

Diego@DESKTOP-SHVI84P MINGW64 ~/Desktop/Ang2NodeOauthJWT/FrontendNg2 (master)

**Comment by delasteve** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

If you believe I am incorrect and this is an actual issue with the CLI, please file a new issue and ensure you provide all of the required information when filling out the issue template.

That said, this looks like an AoT compilation issue.

**Comment by Brocco** [comment]
Agreed the amount of information provided does not give us enough information to work with. When filing an issue please follow the new issue template. If you are seeking support StackOverflow is a great site to resolve issues. If you do believe this is a bug with the CLI please file another issue.

**Comment by samassango** [comment]
ERROR in C:/Users/Pulego-PC/TshwaneSafety/new-dashboard/src/$$_gendir/app/forms/addalerts/addalerts.component.ngfactory.ts (818,55): Property 'suburb' does not exist on type '{}'.
C:/Users/Pulego-PC/TshwaneSafety/new-dashboard/src/$$_gendir/app/forms/addalerts/addalerts.component.ngfactory.ts (837,55): Property 'title' does not exist on type '{}'.
C:/Users/Pulego-PC/TshwaneSafety/new-dashboard/src/$$_gendir/app/forms/addalerts/addalerts.component.ngfactory.ts (847,55): Property 'message' does not exist on type '{}'.
C:/Users/Pulego-PC/TshwaneSafety/new-dashboard/src/$$_gendir/app/forms/addalerts/addalerts.component.ngfactory.ts (886,59): Property 'suburb' does not exist on type '{}'.
C:/Users/Pulego-PC/TshwaneSafety/new-dashboard/src/$$_gendir/app/forms/addalerts/addalerts.component.ngfactory.ts (896,59): Property 'title' does not exist on type '{}'.
C:/Users/Pulego-PC/TshwaneSafety/new-dashboard/src/$$_gendir/app/forms/addalerts/addalerts.component.ngfactory.ts (906,59): Property 'message' does not exist on type '{}'.
