### ISSUE TITLE
Missing changes in v1.1.0-rc.1 Changelog 

### ISSUE THREAD

**Issue by laco0416** [angular/angular-cli#6449]
I think that [Changelog of v1.1.0-rc.1](https://github.com/angular/angular-cli/releases/tag/v1.1.0-rc.1) should include [this _feature_ commit](https://github.com/angular/angular-cli/commit/c268b5889fa66c3f8f925edf11115cf1c03cbdad). Current changelog on GitHub releases has only bugfixes.

I cannot contribute to correct this because this is not markdown! :(

**Comment by Brocco** [comment]
Correct, this has been updated... THANKS!
