### ISSUE TITLE
@angular-cli 1.1.0 rc.1 not support baseUrl import ?

### ISSUE THREAD

**Issue by Feng-JY** [angular/angular-cli#6451]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.1.0-rc.1
node: 6.10.2
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0-rc.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

### Repro steps.

ng new angular-new-cli
yarn install
new until.ts in app/
this is until.ts content export const TEST = 'test';
in app.component.ts import { TEST } from 'app/until'; 

### The log given by the failure.

ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'app/until' in '/Users/feng/ng/angular-new-cli/src/app'
 @ ./src/app/app.component.ts 8:0-33
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

### Desired functionality.

@angular-cli 1.1.0 rc.0 -> 1.1.0 rc.1 not support baseUrl import ?
if have multi-level directory
how to do more elegant

**Comment by Simon-Briggs** [comment]
I'm getting the same error having just upgraded to @angular-cli 1.0.5

**Comment by wtospit** [comment]
I have got this issue as well in my project, but it's look strange that, when I tried to reproduce this issue by creating new project, it doesn't show any error, and went well....

I'm using version 1.0.5

**Comment by hansl** [comment]
Seems like it is a regression on 1.0.4. I'll revert and do a re-release right away.
