### ISSUE TITLE
Unable to launch project in chrome which created using angular-cli

### ISSUE THREAD

**Issue by sitaram676** [angular/angular-cli#6452]
### Bug Report or Feature Request (mark with an `x`)
```
Bug Report: Issue is only in Chrome
```

### Versions.
@angular/cli: 1.0.5
node: 6.9.1
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.
@angular/platform-browser-dynam
@angular/router: 4.1.3
@angular/cli: 1.0.5
@angular/compiler-cli: 4.1.3

### Repro steps.
create an angular project using angular-CLI as mentioned in  https://angular.io/docs/ts/latest/cli-quickstart.html
Run ng serve
access application using http://localhost:4200/

### The log given by the failure.
This site can’t be reached
localhost refused to connect.

### Mention any other details that might be useful.
Able to access in Firefox without issues
In IE after uncommenting  the below lines in polyfills worked fine
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/set';

**Comment by sumitarora** [comment]
@sitaram676 Is there any error you are getting? Try closing and reopening the chrome or incognito mode and see if it works.

**Comment by kirillshilin** [comment]
I have the same issue. It works in chrome incognito, but not in regular chrome

**Comment by ShivaniKshatriya** [comment]
I am facing same issue. I have even enabled localhost on my windows machine. 127.0.0.1 port is working. but localhost:4200 is still not working (not even in incognito mode).

**Comment by briznad** [comment]
I'm also experiencing this. Both Firefox & Chrome Incognito mode work fine, but non-incognito Chrome immediately forwards http://localhost:8100/ to secure https://localhost:8100/,  and shows the following error:
```
This site can’t be reached
localhost unexpectedly closed the connection.
```
