### ISSUE TITLE
`ng serve --environment` flag not copying targeted environment file when environments directory inside `app` directory

### ISSUE THREAD

**Issue by KeithGillette** [angular/angular-cli#6464]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.6
node: 6.10.2
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.6
@angular/compiler-cli: 4.1.3
```
### Repro steps.

When executing `ng serve --environment=prod`
#### Works:
The following configuration correctly imports the contents of `./environments/environment.prod.ts` into `main.ts`:

*.angular-cli.json*
```json
			"environmentSource": "./environments/environment.ts",
			"environments": {
				"dev": "./environments/environment.dev.ts",
				"prod": "./environments/environment.prod.ts"
			}
```
*main.ts*
```typescript
import { environment } from './environments/environment';
```

#### Fails:
The following configuration always loads the contents of `./app/core/environments/environment.ts` into `main.ts`:

*.angular-cli.json*
```json
			"environmentSource": "./app/core/environments/environment.ts",
			"environments": {
				"dev": "./app/core/environments/environment.dev.ts",
				"prod": "./app/core/environments/environment.prod.ts"
			}
```
*main.ts*
```typescript
import { environment } from './app/core/environments/environment';
```

### The log given by the failure.

No errors reported.

### Desired functionality.

I have a combined Angular browser + NativeScript project in which I use the same environment configurations for the browser and mobile clients. Due to a limitation of the NativeScript CLI, modules outside of the `app` directory cannot be imported, so I am trying to load the `environment` module from a location within the `app` directory.

### Mention any other details that might be useful.

"Real fact" 121: The only bird that can swim but not fly is the penguin.

**Comment by hansl** [comment]
Hi @KeithGillette.  It seems I cannot reproduce this locally. Could you provide a github repo that has this issue?

Here are the changes I did from a new project from `master` (using 1.0.6):

```patch
diff --git a/.angular-cli.json b/.angular-cli.json
index a113fee..ad7396d 100644
--- a/.angular-cli.json
+++ b/.angular-cli.json
@@ -22,10 +22,10 @@
         "styles.css"
       ],
       "scripts": [],
-      "environmentSource": "environments/environment.ts",
+      "environmentSource": "./app/core/environments/environment.ts",
       "environments": {
-        "dev": "environments/environment.ts",
-        "prod": "environments/environment.prod.ts"
+        "dev": "./app/core/environments/environment.dev.ts",
+        "prod": "./app/core/environments/environment.prod.ts"
       }
     }
   ],
diff --git a/package.json b/package.json
index 90b67d5..90b9bf2 100644
--- a/package.json
+++ b/package.json
@@ -26,7 +26,7 @@
     "zone.js": "^0.8.4"
   },
   "devDependencies": {
-    "@angular/cli": "1.1.0-rc.2",
+    "@angular/cli": "1.0.6",
     "@angular/compiler-cli": "^4.0.0",
     "@angular/language-service": "^4.0.0",
     "@types/jasmine": "2.5.45",
diff --git a/src/main.ts b/src/main.ts
index a9ca1ca..8e5ddb7 100644
--- a/src/main.ts
+++ b/src/main.ts
@@ -2,7 +2,9 @@ import { enableProdMode } from '@angular/core';
 import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

 import { AppModule } from './app/app.module';
-import { environment } from './environments/environment';
+import { environment } from './app/core/environments/environment';
+
+console.log(environment);

 if (environment.production) {
   enableProdMode();
```

The output is the correct expected one from `environment.prod.ts`.

**Comment by KeithGillette** [comment]
Thanks for investigating this, @hansl. I have recreated the problem using Angular CLI 1.1.0 in my [`angular-cli-environment-directory` repository](https://github.com/KeithGillette/angular-cli-environments-directory). In recreating this from scratch, I found that issue occurs when the when `apps.root` in `.angular-cli.json` is another level deeper than standardly generated by the CLI, which then pushes the also-relocated `environments` directory even deeper in the configuration I am using in my project.

**Comment by KeithGillette** [comment]
Hi @hansl. Just following-up to see whether you have had an opportunity to recreate the failure condition I experienced based on the [sample repository](https://github.com/KeithGillette/angular-cli-environments-directory) I provided last week and, if so, whether the `apps.root` and `environments` configuration contained therein will be supported by Angular CLI. Thanks!
