### ISSUE TITLE
I am facing warning

### ISSUE THREAD

**Issue by aliridha1510** [angular/angular-cli#6467]
```
npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})***

```

***********************************************************************************
+-- @ionic/app-scripts@1.3.7
| +-- babili@0.0.10
| | `-- babel-cli@6.24.1
| |   `-- babel-core@6.24.1
| |     `-- minimatch@3.0.2  deduped
| +-- chokidar@1.6.1
| | `-- readdirp@2.1.0
| |   `-- minimatch@3.0.2
| +-- glob@7.1.2
| | `-- minimatch@3.0.4
| +-- node-sass@4.5.0
| | +-- gaze@1.1.2
| | | `-- globule@1.1.0
| | |   `-- minimatch@3.0.2  deduped
| | `-- node-gyp@3.6.1
| |   `-- minimatch@3.0.2  deduped
| +-- rollup-plugin-json@2.1.1
| | `-- rollup-pluginutils@1.5.2
| |   `-- minimatch@3.0.2  deduped
| +-- rollup-plugin-node-globals@1.1.0
| | `-- rollup-pluginutils@1.5.2
| |   `-- minimatch@3.0.2  deduped
| `-- tslint@3.15.1
|   `-- findup-sync@0.3.0
|     `-- glob@5.0.15
|       `-- minimatch@3.0.2  deduped
`-- cordova-android@6.2.3
  `-- cordova-common@2.0.2
    +-- glob@5.0.15
    | `-- minimatch@3.0.3  deduped
    `-- minimatch@3.0.3

Please help

**Comment by tytskyi** [comment]
Those warnings are OK. 

You should not and cannot do anything with them.

Note `OPTIONAL DEPENDENCY`, which means it is not strict. 

Both modules are available only on Mac OS. But you are using Windows.

I get the same warnings on Linux, everything is working as expected.

**Comment by sumitarora** [comment]
Closing as above.

**Comment by henryoh007** [comment]
Good to hear Thanks

**Comment by webmobiles** [comment]
i'm not ussing windows, it's a ubuntu folder, shared with samba to windows, i do 'npm start' from ubuntu shell and i get this error, anyone can help me? why npm thinks i'm on windows environment?

**Comment by lmmfranco** [comment]
@webmobiles please read again what tytskyi wrote.
It happens on all OS that are not Mac OS.

**Comment by wolenskyatwork** [comment]
Any thoughts - I see this warning only in my circleci env, and it still caused npm to faill with exit code 1.
