### ISSUE TITLE
ERROR in main.2e428a61692f268eadaa.bundle.js from UglifyJs Invalid assignment [main.2e428a61692f268eadaa.bundle.js:31,15]

### ISSUE THREAD

**Issue by shah-smit** [angular/angular-cli#6470]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

> @angular/cli: 1.0.4
> node: 7.4.0
> os: darwin x64
> @angular/common: 4.1.3
> @angular/compiler: 4.1.3
> @angular/core: 4.1.3
> @angular/forms: 4.1.3
> @angular/http: 4.1.3
> @angular/platform-browser: 4.1.3
> @angular/platform-browser-dynamic: 4.1.3
> @angular/router: 4.1.3
> @angular/cli: 1.0.4
> @angular/compiler-cli: 4.1.3
> 
> 

### Repro steps.
When I doing `ng build -prod` it gave the error.

### The log given by the failure.
```
Hash: 925bd38b160e12a43edd
Time: 18025ms
chunk    {0} polyfills.3402294612387ae1f127.bundle.js (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.2e428a61692f268eadaa.bundle.js (main) 403 kB {3} [initial] [rendered]
chunk    {2} styles.a4e7cf3e5d7179497716.bundle.css (styles) 122 bytes {4} [initial] [rendered]
chunk    {3} vendor.653c996e01b732eda185.bundle.js (vendor) 2.54 MB [initial] [rendered]
chunk    {4} inline.44df931cc1bf46a33008.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in main.2e428a61692f268eadaa.bundle.js from UglifyJs
Invalid assignment [main.2e428a61692f268eadaa.bundle.js:31,15]
```

### Desired functionality.
build for production

**Comment by thatsprettyfaroutman** [comment]
WHAT DID YOU FIND!???!

**Comment by shah-smit** [comment]
That one of the library that I was loading(to be specific: Full-Calendar) was throwing that error.

**Comment by thatsprettyfaroutman** [comment]
Thanks 🙏

**Comment by shah-smit** [comment]
@thatsprettyfaroutman Here is my ts.config file. Which fixed it! You may want to try it
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "target": **"es5"**,
    "module": "commonjs",
    "baseUrl": "",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ],
  "typeRoots": [
      "node_modules/@types"
    ],
    **"lib": [
      "es2016",
      "dom"
    ]**
}
```

The bold-ed ones is the one i changed.
