### ISSUE TITLE
`--base-href` to be configurable in `.angular-cli.json`

### ISSUE THREAD

**Issue by rkrisztian** [angular/angular-cli#6477]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
```
@angular/cli: 1.0.2
node: 6.9.4
os: linux x64
@angular/animations: 4.1.1
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/platform-server: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.1
@angular/language-service: 4.1.1
```

### Desired functionality.
I need to configure multiple apps with different `--base-href` values. Right now the only place where I can set this setting is via command line, but that leads to too complex NPM scripts. A better solution would be a setting inside the `app` array of `.angular-cli.json`. We already have `deployUrl`, so I don't understand why there is no `baseHref` yet.

**Comment by mhartvig** [comment]
You have my vote, looking for exactly the same feature.

**Comment by clydin** [comment]
There's a pending PR: https://github.com/angular/angular-cli/pull/6461

**Comment by rkrisztian** [comment]
Thanks!

I've just noticed, #3010 already considered this feature, but then got dismissed due to the last comment realizing that it is enough to change the base href in the `index.html`. However, I've seen certain StackOverflow answers pointing out that it may not be enough to change the HTML:

- https://stackoverflow.com/questions/41515028/set-base-href-from-an-environment-variable-with-ng-build
- https://stackoverflow.com/questions/38112891/set-base-href-dynamically-angular-2

**Comment by aboudard** [comment]
Would love to see that feature !

**Comment by meyacine** [comment]
just add "baseHref" : "YOUR_CUSTOM_HREF" to the "apps" in the angular-cli.json
```
{
   ....
 "apps": [
    {
       "baseHref" : "YOUR_CUSTOM_HREF"
     }
  ],
}
```

**Comment by ffMathy** [comment]
How does this work in Angular 6 with the new `angular.json` file?

**Comment by JohnathanCena** [comment]
@ffMathy 

It's more or less the same way. In your angular.json file:

Build -> Configurations -> YOUR_CONFIG -> "baseHref" : "YOUR_CUSTOM_HREF"
