### ISSUE TITLE
Property 'TotalProducts' does not exist on type 'string'.

### ISSUE THREAD

**Issue by ulisesinfante** [angular/angular-cli#6479]
ng build --prod (using firebase)

**Comment by RicardoVaranda** [comment]
Hi @ulisesinfante , Could you please use the template provided when filling out a issue report in order for us to assist you properly, the information you provided is not sufficient.

**Comment by sumitarora** [comment]
@ulisesinfante Please fill in the more details as per template and reopen the issue. Thanks!!
