### ISSUE TITLE
Please provide stories to deploy different platforms like Electron and chrome extension

### ISSUE THREAD

**Issue by surenrao** [angular/angular-cli#6484]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
Hello, was going through the stories, nicely done! thanks for that! although it will be nice to have that on the [main site](https://cli.angular.io/).
Can you please add a story to create a chrome extension with popup.html, option.html and background.html?
One more story to write Electron app using angular cli
Thanks

**Comment by shoudaos** [comment]
Yes, the story about using the Electron will be very helpfull

**Comment by michaeljota** [comment]
I think that if you want to deploy on that platform, `ng eject` would be a better fit for that. And it would be also a better way to do it. As @ruipimentel said, in #9107 I posted a story already about basic integration of  the `ng` with `electron`. There are somethings that are still missing, but I will work around it to make the integration as strong as possible, without breaking the `CLI`.

**Comment by joaocc** [comment]
@ruipimentel We have been using electron-angular-toolkit for this, and it supports HMR quite well. However we would prefer a more "native" solution (esp since it seems to be unsupported for some time).

**Comment by ruipimentel** [comment]
Thanks @joaocc, I have also checked out `electron-angular-toolkit`, but I too abandoned it due to lack of active development.

**Comment by michaeljota** [comment]
Here is the story: 
https://dev.to/michaeljota/integrating-an-angular-cli-application-with-electron---the-ipc-4m18
I hope I understood everything correctly and also explain it properly. It is in deed very complex to understand, but at the end is about thinking in plain simple Javascript. 

Thanks to all the people that are following this thread, I'd learned a lot these days about techs that I love.

**Comment by dashkan** [comment]
All,

I spent a couple of days reviewing the cli codebase. The build system is very extensible. I ended up creating a new npm package named **ng-electron-devkit** that extends angular 6 build system to support electron-renderer. My goal is to add support for electron main process and packaging electron assets in the build pipeline in future updates.

This is not a hack to the CLI. You can target both electron-renderer and the browser and have completely different build settings!

[Check it out](https://github.com/dashkan/ng-electron-devkit)

**Comment by mgechev** [comment]
@dashkan fantastic job! I see there's a lot of community work which documents lots of use cases. Closing the issue for now. Thank you all sharing these resources!
