### ISSUE TITLE
css with background-image broken after updating to latest angular-cli

### ISSUE THREAD

**Issue by jordandreassen** [angular/angular-cli#6489]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/CLI 1.0.6
@angular/* 4.2.0-rc.1

### Repro steps.
http://i.imgur.com/EzQNW9y.png is the file structure

### The log given by the failure.
```
Failed to compile.

./src/app/top-nav/top-nav.component.css
Module not found: Error: Can't resolve '../images/logo.png' in '.......\src\app\top-nav'
 @ ./src/app/top-nav/top-nav.component.css 6:160-189
 @ ./src/app/top-nav/top-nav.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

### Desired functionality.
Have the images load.

**Comment by clydin** [comment]
The path should be relative to the CSS file.  So based on your file structure, `../../images/logo.png` should work.
