### ISSUE TITLE
Errors in ng build -aot

### ISSUE THREAD

**Issue by username34980** [angular/angular-cli#6497]
### OS?
Windows 7

### Versions.
@angular/cli: 1.0.0
node: 6.10.1
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser/dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.3

### Repro steps.
Application created with angular-cli

### The log given by the failure.
ERROR in Child compilation failed:
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example at Object.module.exports.pitch <C:\...\node_modules\@angular\cli\node_modules\extract-text-webpack-plugin\loader.js:27:9>:
Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin , refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\...\src'
@ ./src/main.ts 4:0-74
@ multi ./src/main.ts

### Command
Errors happen when running `ng build -aot`, but when running `ng build` or `ng serve` everything works fine

**Comment by clydin** [comment]
Can you try updating to the latest stable version (1.0.6) and see if you still receive the error?

**Comment by username34980** [comment]
I already tried it and my application was not working anymore and I had two errors :
ERROR in self is not defined and the second one about ngfactory

**Comment by username34980** [comment]
So I followed [this tutorial](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#compiling-aot) : install @angular/platform-server, create a tsconfig-aot.json, run `"node_modules/.bin/ngc" -p tsconfig-aot.json` and edit my main.ts from

```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';

platformBrowserDynamic().bootstrapModule(AppModule);
```
to

```
import { platformBrowser } from '@angular/platform-browser';
import { AppModuleNgFactory } from '../aot/src/app/app.module.ngfactory';

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```

and now I have only one error :

> Tried to find boostrap code, but could not.Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
>     at Object.resolveEntryModuleFromMain C:...\node_modules\@ngtools\webpack\src\entry_resolver.js:128:11
>     at AotPlugin._setupOptions C:...\node_modules\@ngtools\webpack\src\plugin.js:142:50
>     at new AotPlugin C:...\node_modules\@ngtools\webpack\src\plugin.js:26:14
>     at _createAotPlugin C:...\node_modules\@angular\cli\models\webpack-configs\typescript.js:55:12
>     atObject.exports.getNonAotConfig C:...\node_modules\@angular\cli\models\webpack-configs\typescript.js:70:19
>     at NgCliWebpackConfig.buildConfig C:...\node_modules\@angular\cli\models\webpack-configs.js:27:37
>     at Class.run C:...\node_modules\@angular\cli\tasks\serve.js:37:98
>     at check_port_1.checkPort.then.port C:...\node_modules\@angular\cli\commands\serve.js:103:26
>     at process._tickCallback internal/process/next_tick.js:109:7
>

**Comment by clydin** [comment]
The CLI automatically handles the AOT refactoring steps.  No bootstrap (or tsconfig) code changes should be necessary to support AOT.
Either `ng build --aot` or `ng build --prod` (it includes AOT) is all that is necessary.

**Comment by filipesilva** [comment]
As @clydin mentioned, you don't need to (nor should) follow that guide when using Angular CLI because it does all the needed steps for you.

Your original error really looks like a broken dependency somewhere. Any chance you could get a repro or your project somewhere? I can take a look and debug if you can do that.

**Comment by username34980** [comment]
@filipesilva I can't provide you my entire project, it is too large. Which file should I provide in order to see where the errors might come from? (config, package, main...?)

**Comment by filipesilva** [comment]
Unfortunately, I really have no idea. There's isn't much I can do to help without a repro. I'm sorry :/
