### ISSUE TITLE
Trying to resolve module in object literal

### ISSUE THREAD

**Issue by debasispanda** [angular/angular-cli#6498]
### Bug Report
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
OS-  Windows 10
IDE- Visual Studio 2015
`node --version` =   v 7.7.4
Package manager- npm
`npm--version` =   v 4.1.2
`ng --version` = 

```
@angular/cli: 1.0.1
node: 7.7.4
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.3
```

### Repro steps.
* Create a new app using angular cli. 
* Add the following code to app.component.ts.
```
let data: any = {
      templateUrl: ''
    }
```
* Run `ng serve`

You will get the following error.

### The log given by the failure.
```
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve './' in 'D:\DemoProjects\demo-app\src\app'
 @ ./src/app/app.component.ts 24:22-35
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

### Desired functionality.
It should be normal string value.

### Mention any other details that might be useful.
Unable to reproduce the same issue in plunker as there we have systemjs config.

**Comment by clydin** [comment]
Currently, if either `templateUrl` or `styleUrls` is used as describe, you will receive the error indicated.  There is ongoing work to fix this.  However, for now, the only option is to not use those exact names in the manner described.
