### ISSUE TITLE
Wiki for 3rd party libs - typo

### ISSUE THREAD

**Issue by blundell** [angular/angular-cli#6502]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

n/a

### Repro steps.
Goto https://github.com/angular/angular-cli/wiki/stories-third-party-lib and read

### The log given by the failure.

<img width="817" alt="screen shot 2017-05-29 at 21 57 38" src="https://cloud.githubusercontent.com/assets/655860/26561915/06317ade-44ba-11e7-96c6-4fc5125c3035.png">

### Desired functionality.

remove the word **not**

### Mention any other details that might be useful.

sorry I don't have wiki edit rights

**Comment by clydin** [comment]
That statement is correct.  Some libraries directly include the typings within the library's package itself (e.g., momentjs).

**Comment by blundell** [comment]
Ah right, you can close then.

This is what confused me, both paragraphs so "if you don't have typings"

![screen shot 2017-05-30 at 08 11 53](https://cloud.githubusercontent.com/assets/655860/26571887/b9965d60-450f-11e7-90bb-0f707a212fbc.png)

**Comment by sumitarora** [comment]
Closing as above.
