### ISSUE TITLE
Unable to find any apps in `.angular-cli.json`.

### ISSUE THREAD

**Issue by PeterDavidCarter** [angular/angular-cli#6503]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

  ```
  _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.6
node: 6.9.1
os: linux x64
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.6
```

### Repro steps.

Ran `npm install --save-dev @angular/cli@latest`

Got `Bus error (core dumped)`

and `├── UNMET PEER DEPENDENCY @angular/animations@^4.0.0`

Attempted to use angular cli generate command. Got:

`Unable to find any apps in `.angular-cli.json`.`

Tried removing and reinstalling. Didn't help. Tried removing animations. Same problem. Tried installing cli with -g flag. Didn't help.

### The log given by the failure.

`Unable to find any apps in `.angular-cli.json`.`

### Desired functionality.

`ng generate s` should work

**Comment by sumitarora** [comment]
@PeterDavidCarter Are you running commands within Angular CLI generated project or it's some old project and you are migrating to CLI?

**Comment by HassanHashemi** [comment]
having same issue when using it visual studio 2017 spa templates. the project is not generated with Angluar CLI. any ideas how to fix it?

**Comment by zorgoz** [comment]
Same issue with `ng g component`.
Got:
![image](https://user-images.githubusercontent.com/1569170/27835837-fedf66a8-60dc-11e7-873b-ede4d90afb6e.png)
```
@angular/cli: 1.2.0
node: 8.1.3
os: win32 x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/compiler-cli: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/platform-server: 4.2.5
@angular/router: 4.2.5
@angular/tsc-wrapped: 4.2.5
@angular/upgrade: 4.2.5
@angular/cli: 1.2.0
```

**Comment by juandrn** [comment]
Same issue in VS 2017 with net core angular project.

![image](https://user-images.githubusercontent.com/13983901/28471075-d7e5bd24-6e09-11e7-845f-fdfb8bedb3e8.png)

**Comment by amhuhn2** [comment]
Is there a workaround for this?  I'm running into the same issue.

**Comment by zorgoz** [comment]
Actually, if you create a new project (ng new) you should get one. I simply copied the new one into the root of the old one. It looks that this file is some quite new addition and if you are using an older template to start building your app, you won't have it.

**Comment by amhuhn2** [comment]
Thank you, zorgoz.  I created this project just last week, but perhaps my install of angular-cli was old.  I’ll try it with a new install.

**Comment by shachar058** [comment]
@zorgoz  - This is what worked for me as well, apparently they changed how `ng g` works.
@amhuhn2  - Did this solve your issue? Interested if that was the problem or if there was something else.

**Comment by amhuhn2** [comment]
@shachar058 yes, that took care of the issue.  I re-installed angular-cli and recreated the project, and that took care of it!

**Comment by YuxuanLin** [comment]
Hi all, here the problem is how can I fix or add .angular-cli.json into the existed project? It is not practical for me recreating whole project for .angular-cli.json.

**Comment by pranaysand** [comment]
I got the same issue when tried to create a component using the angular/cli. "npm cache verify" have fixed issue.

**Comment by raxitp02** [comment]
I have tried same!!
npm cache verify , but still getting same error for generating new component "Unable to find any apps in.angular-cli.json." Does any one have solution for this?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
