### ISSUE TITLE
Component library local development with npm link error: "Please add a @NgModule annotation"

### ISSUE THREAD

**Issue by ernestbofill** [angular/angular-cli#6505]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.6
node: 6.9.5
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.6
@angular/compiler-cli: 4.1.3

### Repro steps.

1. Create an empty angular-cli project
1. Create a new Angular component library with at least one module and one component.
1. Build the component library with `ngc -p ./src/tsconfig.lib.json`
1. Register the component library running `npm link` at the `/dist` folder of the library.
1. From the angular-cli project link to the component library: `npm link component-library-package-name`
1. Use the component library (import a module and use a component).
1. Start the angular-cli project with `ng serve`.
1. It compiles but it will fail in the browser with the following error: `Unexpected value 'MyModule' imported by the module 'AppModule'. Please add a @NgModule annotation.`

### The log given by the failure.

**Chrome error log:**
```
compiler.es5.js:1540 Uncaught Error: Unexpected value 'MyModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (http://localhost:4200/vendor.bundle.js:29720:34)
    at http://localhost:4200/vendor.bundle.js:42674:44
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:42657:49)
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:53810:66)
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:53769:52)
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:53731:23)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:5731:25)
    at PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:5717:21)
    at Object.122 (http://localhost:4200/main.bundle.js:303:124)
```

**Comment by clydin** [comment]
You can find information related to using linked libraries here: https://github.com/angular/angular-cli/wiki/stories-linked-library

If you are still having issues, please let us know and if possible provide a sample library or other repro.

**Comment by ernestbofill** [comment]
@clydin thanks, I still have issues. I believe my component library follows the guidelines from the [link you provided](https://github.com/angular/angular-cli/wiki/stories-linked-library).

I attach a zip file with a sample library and an angular-cli application using it which can be used to reproduce the issue:

[npmlinktest.zip](https://github.com/angular/angular-cli/files/1038312/npmlinktest.zip)

**Comment by clydin** [comment]
Your component library setup looks fine.
The app needs some slight adjustment to ensure that the application's Angular libraries are used and not the library's development dependencies.  This change will essentially mimic the standard behavior of the Angular peer dependencies for a linked library.
In `src/tsconfig.app.json`, add this:
```
{
  "compilerOptions": {
    // ...
    "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    }
  }
}
```

**Comment by ernestbofill** [comment]
Great. That fixes it. I can see now that it was also explained in the [guide you provided earlier](https://github.com/angular/angular-cli/wiki/stories-linked-library) but I didn't understand it there.

**Comment by matthewhegarty** [comment]
Adding `paths` didn't work for me.  I removed linked library's `node_modules` and that is a pain but fixes the issue.  See [this thread](https://github.com/angular/angular-cli/issues/3854#issuecomment-2743447713)

**Comment by DooMMasteR** [comment]
I have the same issue, but only in development, the result of the production compile run works just fine.
``"paths": { "@angular/*": ["../node_modules/@angular/*"] }`` is already set up in my ``tsconfig.app.json`` but in development I still get an ``@NgModule`` annotation error.
```
@angular/cli: 1.4.3
node: 6.11.3
os: linux x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
@ngtools/webpack: 1.7.1
typescript: 2.3.4
```

**Comment by kalyan-anna** [comment]
deleting the node_modules folder from linking library solved the error for me

**Comment by endy21osu** [comment]
I am having the same issue when i try to link a module after running ngc. 

The issue goes away if i use "@angular/cli": "1.2.7" but if i use 1.3.0 and up to 1.4.7 i have the issue where i am asked to "Please add a @NgModule annotation." in the console of the browser. any ideas?

**Comment by matthewhegarty** [comment]
@endy21osu Hi Jeff - you can try removing the linked library's `node_modules` directory (or just `@angular/node_modules`) - see [above](https://github.com/angular/angular-cli/issues/6505#issuecomment-329824023).

See also [this issue](https://github.com/angular/angular-cli/issues/6482)

**Comment by endy21osu** [comment]
Hi Matt, 

Thanks for the response. If you are talking about the node_modules folder that might be in the dist folder after running ngc then yes I did delete that.  Is there a different one i should be deleting?

**Comment by matthewhegarty** [comment]
It will be the `node_modules` folder in whatever is the target of your npm link

**Comment by endy21osu** [comment]
yes i did delete it. here is what it looks like 
![image](https://user-images.githubusercontent.com/8715434/31826498-38fcdd34-b583-11e7-93e7-92ce7f729ab3.png)

**Comment by magemello** [comment]
@endy21osu, I explained how I fix it here: https://github.com/angular/angular/issues/15763#issuecomment-339343522, I hope it can help you...

**Comment by mprinc** [comment]
Here i tried to elaborate more on the problem: https://github.com/angular/angular-cli/issues/2154#issuecomment-343288877
