### ISSUE TITLE
Follow the offical Angular 2 style guide when generating components

### ISSUE THREAD

**Issue by uli-weltersbach** [angular/angular-cli#6509]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.0.6
node: 7.10.0
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.6
@angular/compiler-cli: 4.1.3

### Repro steps.
`ng generate component hello-world` 

### Desired functionality.
Follow the offical style guide by not including "component" in the html-file's name (or change the style guide if it's outdated).
See https://angular.io/docs/ts/latest/guide/style-guide.html#!#04-05.

**Comment by dave11mj** [comment]
I fail to see an issue here ...
![image](https://cloud.githubusercontent.com/assets/6619371/26603053/7b8f90a6-4553-11e7-95b6-77fd214078e5.png)

The example clearly says `hero.component.ts|html|css|spec.ts` which to me means `hero.component.ts` or `hero.component.html` (or any other extension) ... Let me know if there is something I am missing or misinterpreting. ^^

**Comment by uli-weltersbach** [comment]
> [...] For example, **it's redundant to name a template hero-view.component.html because with the .html extension, it is obviously a view.** But if something is not obvious or departs from a convention, then spell it out.

**Comment by uli-weltersbach** [comment]
Sorry, I was confused by the statement that .html-files are always "views", so the style guide suggests not naming things "hero-view.component". I thought the comment referred to the "component" part :|

**Comment by dave11mj** [comment]
Yeah ... I actually found that quote you mentioned under `Try to be DRY` .. Thats actually something good to know I wasn't aware of when creating component views .. Maybe a nicer feature request would be a flag for `--view` or something of the sort to remove the `component` from the when generating new components, and expose more people that that best practice from the guidelines. ^^

**Comment by hansl** [comment]
This seems to be answered above. Thanks!
