### ISSUE TITLE
404 Error trying to import @angular/router-deprecated

### ISSUE THREAD

**Issue by cquillen2003** [angular/angular-cli#651]
Looking at the Angular docs, I just noticed the beta router is deprecated.  The app created by this CLI uses the new router package.  Is there any documentation for the new router?

I tried using the old router by npm installing @angular/router-deprecated and importing as follows:

import { ROUTER_DIRECTIVES, RouteConfig } from '@angular/router-deprecated';

But I am getting the following error:

zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/vendor/@angular/router-deprecated

**Comment by hansl** [comment]
Did you `npm install @angular/router-deprecated`?

**Comment by percy1984** [comment]
The beta Router is no longer supported by CLI. It's replaced by the rc1 Router. You should switch to using this one, instead of using the deprecated Router!

**Comment by guillaumeleone** [comment]
@cquillen2003 try this https://github.com/angular/angular-cli/pull/674
@hansl I've just opened a PR if you want

**Comment by cquillen2003** [comment]
I found an example app using the new router so I'm using it now.  I mostly had to change my @RouteConfig entries to @Routes to get it working.  No need to support the deprecated router from my end.

**Comment by omeryounus** [comment]
what is the angular module name which support routes? @cquillen2003
