### ISSUE TITLE
feature request custom hash in cache busting

### ISSUE THREAD

**Issue by abdulmoizeng** [angular/angular-cli#6513]
### Bug Report or Feature Request (mark with an `x`)
```
- [custom hash in cache busting ] feature request
```

### Desired functionality.

Required is custom hashes for cache busting

**Comment by abdulmoizeng** [comment]
I have included some work for this feature
https://github.com/angular/angular-cli/pull/6500

**Comment by hansl** [comment]
I don't think this feature is useful. What problem are you strying to solve?

**Comment by abdulmoizeng** [comment]
@hansl in one of my project I need a way to control hash (used for cache busting), in that way I will change it whenever I want to bust bust user's cache .

**Comment by abdulmoizeng** [comment]
In a custom way hash can reflect the version of project build I am using . Like following example `[name].[version +md5hash].[ext]` 
In the above provided implementation app has control of the hash and it will be provided as an argument (it can be any string)

**Comment by filipesilva** [comment]
This isn't something we're looking at adding at this point. The default outputHashing settings seem to cover the vast majority of cases.
