### ISSUE TITLE
Module splitting in AOT Angular 2

### ISSUE THREAD

**Issue by AbinayaSubbiah** [angular/angular-cli#6515]
i am having more number or components with multiple routing. While running sample with ngc compiler i cant able to get build and facing issue 

> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap
> out of memory

So i have added --max-old... option also but its not working for me. Since i planned to split entry module as separate component model, but still am facing issue. Any one help me to find out issue

**webpack.aot.config**

    module.exports = {

    entry: {
        'polyfill': './polyfill.ts',
        'vendor': './vendor.ts',
        'comp1': './components/comp1/comp1.module.ts',
        'comp2': './components/comp2/comp2.module.ts',
        . . . . . 
        'app': './app.module.ts',
        'main': './main.aot.ts'
    },

**Comment by filipesilva** [comment]
@AbinayaSubbiah you don't seem to be using Angular CLI itself, are you using `@ngtools/webpack`?

If so, you shouldn't add all lazy modules to the entry points. Main is all you need, as `@ngtools/webpack` figures out all lazy modules.

**Comment by AbinayaSubbiah** [comment]
@filipesilva  yes m using `@ngtools/webpack`

I must need more entry in my case so i need to bundle my files separately. 

I can successfully build separate bundles in webpack as like i mentioned above. but in AOTPlugin i can't...

Is any other way to generate module as separate bundle bcoz i dont have another options to do i must need it.

**Comment by filipesilva** [comment]
Application module splitting with `@ngtools/webpack` is done via Angular Lazy routes. I don't think we support what you're trying to do with each NgModule being a separate entry point.
