### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Expression form not supported

### ISSUE THREAD

**Issue by bezigon** [angular/angular-cli#6517]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
`-> please search issues before submitting`
I was looking for _similar_ issues, but I could not find an answer.

### Versions.

```
@angular/cli: 1.0.6
node: 6.10.0
os: darwin x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.6
@angular/compiler-cli: 4.1.3
```
### Repro steps.

1. With this code below
```typescript
@NgModule({
  imports: [RouterModule.forRoot(routes, { useHash: true } as ExtraOptions)],
  exports: [RouterModule],
})
```
2. Run `ng build --watch`

### The log given by the failure.

```
ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 45:42 in the original .ts file), resolving symbol AppRoutingModule in (skipped)/src/app/app-routing.module.ts
```

### Desired functionality.

Output messages without errors.

### Mention any other details that might be useful.

1. If I enter any noncode character, for example newline, `ng` with `--watch` feature rebuilds without error.
2. Changed the code to the one below, builds without errors.
```typescript
@NgModule({
  imports: [RouterModule.forRoot(routes, <ExtraOptions>{ useHash: true })],
  exports: [RouterModule],
})
```

**Comment by filipesilva** [comment]
Heya, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

The CLI always runs *some* statical analysis, even on JIT mode, on code to ensure it will run when compiled with AOT. This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

Good resource on how to to debug these errors are https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60 and  https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts.

If your problem still persists, it might be a bug with the Angular Compiler itself. In that case, please open an issue in https://github.com/angular/angular.
