### ISSUE TITLE
Missing ROUTER_PROVIDERS when bootstrapping an app

### ISSUE THREAD

**Issue by alvipeo** [angular/angular-cli#652]
I tried CLI for a new app and then found out that initial bootstrapping is not injecting ROUTER_PROVIDERS. So whenever you ng generate route - nothing works.

**Comment by hansl** [comment]
It is added to the main application component with the first route generation. https://github.com/angular/angular-cli/issues/656 is taking care of fixing a bug that happens sometimes, which might be what you're seeing now.

Thanks.
