### ISSUE TITLE
Loaders do not work when running unit tests

### ISSUE THREAD

**Issue by abdulhaq-e** [angular/angular-cli#6525]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

v1.2.0-beta.0 (and previous versions as well)

### Repro steps.

1- Start a new project: `ng new`
2- Edit `typings.d.ts` so that `JSON` files can be imported (just an example):
```ts
declare module "*.json" {
    const value: any;
    export default value;
}
```
3- Place a random JSON file in `src/app`.
4- Load the JSON file in `app.component.ts` and `app.component.spec.ts` using:
```ts
import testFile from './random.json'
```
5- Log the JSON to the console in both files and run `ng serve` and `ng test`.
6- In `app.component.ts`  the file shows as expected while when running the tests the file is `undefined`.

### The log given by the failure.

The file which is supposed to be parsed by the loader is `undefined`. No errors at all.

### Mention any other details that might be useful.

I first experienced this when trying custom loaders, however as shown above the issue exists with loader already used by the CLI such as `json-loader`.

**Comment by filipesilva** [comment]
We don't really support custom loaders, but we do have some limited support for json loader. So it's odd that it doesn't work in `ng test` but works in others.

**Comment by abdulhaq-e** [comment]
I am using a local version of the CLI but that doesn't make a difference.

In case it helps anyone, the loader is "recognised" by Webpack even in `ng test` because when I try to remove the loader and try to import the JSON file I will get:
> you may need an appropriate loader to handle this file type

**Comment by abdulhaq-e** [comment]
@filipesilva I've finally figured this one out! The chosen `module` in TS `compilerOptions` needs to be set to `es2015` for `tsconfig.spec.json` (similar to the app tsconfig). If there is no reason for choosing `commonjs` then I'll submit a PR.

**Comment by filipesilva** [comment]
@abdulhaq-e IIRC it needs to be commonjs for code coverage, but that might have changed meanwhile.

**Comment by Manduro** [comment]
Setting it to es2015 works fine with code coverage here!

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
