### ISSUE TITLE
When generating a route CLI should have an option to name a component (or route) - feat req

### ISSUE THREAD

**Issue by alvipeo** [angular/angular-cli#653]
When generating a new route, its name will not always be the same as components name. Like when I have a list of subscribers and I need these routes:
- subs
- subs/new
- subs/edit/:id

for the **new** and **edit** I will be using the same SubEditComponent. And not NewComponent and EditComponent

**Comment by filipesilva** [comment]
Using the current router, you cannot have names for routes. That was a feature of the old router only.
