### ISSUE TITLE
Unit testing code coverage : unable to change the reporter to JUnit

### ISSUE THREAD

**Issue by trichetriche** [angular/angular-cli#6530]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

**@angular/cli: 1.1.0**

### Repro steps.

Change `the karma.conf.js` file as follows : 

    module.exports = function (config) {
      config.set({
        basePath: '',
        frameworks: ['jasmine', '@angular/cli'],
        plugins: [
          require('karma-jasmine'),
          // require('karma-chrome-launcher'),
          require('karma-phantomjs-launcher'),
          require('karma-junit-reporter'),
          require('@angular/cli/plugins/karma')
        ],
        files: [
          { pattern: './src/test.ts', watched: false }
        ],
        preprocessors: {
          './src/test.ts': ['@angular/cli']
        },
        mime: {
          'text/x-typescript': ['ts', 'tsx']
        },
        junitReporter: {
          outputDir: 'coverage', // results will be saved as $outputDir/$browserName.xml
          useBrowserName: false, // add browser name to report and classes names
          outputFile: 'test-report.xml', // if included, results will be saved as $outputDir/$browserName/$outputFile
        },
        angularCli: {
          config: './angular-cli.json',
          environment: 'dev'
        },
        reporters: ['junit'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: [
          'PhantomJS',
          // 'Chrome'
        ],
        singleRun: false
      });
    };

### The log given by the failure.

    $ npm run test -- --watch=false --code-coverage

        > harfang@0.1.5-SNAPSHOT test D:\mtrichard\harfangv2_frontend
        > ng test "--watch=false" "--code-coverage"

        10% building modules 1/1 modules 0 active01 06 2017 11:27:42.547:ERROR [reporter]: Can not load reporter "coverage-istanbul", it is not registered!
          Perhaps you are missing some plugin?

### Desired functionality.

I would like to change the reporter used for the code coverage, but `coverage-istanbul` is always used, even though I don't have the package (I removed it from `package.json` and used `npm prune`)

**Comment by filipesilva** [comment]
The `--code-coverage` does a couple of things:
- adds `coverage-istanbul` to the reporters
- adds `istanbul-instrumenter-loader` to the webpack build system

If you want to use a custom reporter for code coverage, then you shouldn't use the `--code-coverage` option since it's geared and tested for the default setup.

I had a brief look at `karma-junit-reporter` and it doesn't seem to require webpack tooling. You should be able to create a separate karma config file for your code coverage setup and load it via `ng test --config=your-custom.config.js`.

**Comment by trichetriche** [comment]
Thanks for the intel. But I still have one question remaining : what is the point of having those lines 

    reporters: config.angularCli && config.angularCli.codeCoverage ?
      ['mocha', 'junit'] :
      ['mocha'],

in the `karma.conf.js`, if they're not used ?

**Comment by Simon-Briggs** [comment]
I started getting this error once I upgraded from 1.0.4 to 1.1.0 as well (even though I wasn't using a custom reporter?):
```
ERROR [reporter]: Can not load reporter "coverage-istanbul", it is not registered!
  Perhaps you are missing some plugin?
```

To fix it I mirrored the changes made here in my local karma.conf.js:
https://github.com/angular/angular-cli/commit/1cd0a0811df2b7a45cbffb413dd56e3ac21a96e4

**Comment by filipesilva** [comment]
@Simon-Briggs is spot on: we changed that boilerplate in `1.1.x` and even though we ensure old default configs don't break, we don't really cater for custom setup.

**Comment by sri-ni** [comment]
```
reporters:
      config.angularCli && config.angularCli.codeCoverage
        ? ['spec', 'html', 'coverage-istanbul', 'junit']
        : ['spec', 'html', 'junit'],
```
