### ISSUE TITLE
VS Code language service is broken in 1.1.0 due to unessecary package

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#6536]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report 
```

### Versions.
cli 1.1.0
VS Code Angular Language Service 0.1.3

### Repro steps.
1. Use VS Code with official Angular Language Service plugin installed.
2. Create a project with CLI.
3. Completion and error checking in HTML external templates doesn't work.
4. `npm uninstall @angular/language-service`
5. Restart VS Code.
6. Now it works.

### Desired functionality.
VS Code Angular Language Service plugin seems to use : 
- it's own install of `@angular/language-service` if it's not present in `node_modules`
- if present, it uses the project dependency, and unfortunately, the plugin is not always up to date with the last release of `@angular/language-service`.

I see no use to pre-install `@angular/language-service` as the developer won't use it directly, and plugins should manage their own dependencies to be sure to use the good version.

So I think commit [bb99fac](https://github.com/angular/angular-cli/commit/bb99fac) should be reverted.

I've open the same issue in VS Code Angular Language Service project too : angular/vscode-ng-language-service#102

**Comment by cyrilletuzi** [comment]
Note : adding the `@angular/language-service` by default will be great when we'll be able to just add in `tsconfig.json` : 

`"plugins": [{ "name": "@angular/language-service" }]`

Then Angular language service will be working out of the box, with no plugin needed.

But it's not ready yet, as it only works with inline templates for now (external templates support is waiting for a new TypeScript feature).

**Comment by filipesilva** [comment]
@sumitarora can you take a look?

**Comment by sumitarora** [comment]
@filipesilva I can confirm it's not working as expected for external templates. We can wait for the plugin to fix the issue as it seems to be an issue with VS code only.

**Comment by lemontreelxs** [comment]
这个玩意儿，不能用好久了，我看了很多的讨论，都没什么结果，总之就是一句话，等！！！！！我靠

**Comment by cyrilletuzi** [comment]
Closing, as it seems to be OK with last versions (even if the issue in angular/vscode-ng-language-service#102 wasn't closed).
