### ISSUE TITLE
ng test / e2e fail in 1.1.0 due to mismatch between test and template - inline templates

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#6537]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
```

### Versions.
cli 1.1.0

### Repro steps.
1. ng new app -it
2. ng e2e > fails
3. ng test > fails

~~Because the new tests doesn't match the app.component template.~~
Because the inline app component template doesn't match the new external one.

I'm doing the PR right now, but shouldn't it have been caught by some test before release ?

**Comment by filipesilva** [comment]
We do have tests for exactly this. Let me try to repro.

**Comment by filipesilva** [comment]
I did the following:

```
ng new v1.1.0-app
cd v1.1.0-app
ng test
ng e2e
```

All pass. Is there some other step that's missing?

**Comment by cyrilletuzi** [comment]
Yes, sorry, as mentioned in the PR, it's with inline template : 
```
ng new v1.1.0-app -it
cd v1.1.0-app
ng test
ng e2e
```
Correcting the PR now.

**Comment by filipesilva** [comment]
@sumitarora can you take a look please?

**Comment by sumitarora** [comment]
@filipesilva I can confirm it's the issue with inline templates.

**Comment by cyrilletuzi** [comment]
Fixed in last releases.
