### ISSUE TITLE
 1.1.0 ng lint no-use-before-declare Warning

### ISSUE THREAD

**Issue by ccadieux** [angular/angular-cli#6539]
```
- [] bug report
- [X] feature request
```

### Versions.
@angular/cli@1.1.0

### Repro steps.
ng new project-name
cd project-name
ng lint 
Warning: The 'no-use-before-declare' rule requires type checking

ng lint --type-check
No Warning

### Desired functionality.
Should --type-check be the default? Or at least a way to set it as default would be nice.

**Comment by filipesilva** [comment]
We defaulted to not running `--type-check`in https://github.com/angular/angular-cli/pull/5589 by default because it was much slower in some cases. Maybe that's not a problem anymore. We can revisit this.

**Comment by clydin** [comment]
It's still slower.  However, tslint recently changed its default behavior to where rules requiring type information are enabled if the project option is used; regardless of the type-check option.  The type check option only controls whether type errors are reported.

**Comment by filipesilva** [comment]
That makes me think we should follow suit, but since we still have projects with older versions of tslint it might be a bad idea to just change it. Would likely need some version aware warnings.

**Comment by johnpapa** [comment]
Any further thoughts on this?

I agree making it slower is not ideal. I wonder if a warning or message when running `ng lint` that tells the user how to handle this warning may be nice.

**Comment by BurningDog** [comment]
> it was much slower in some cases

Which cases are those? I have a fairly large Angular project (over 20k lines of typescript code). Running `ng lint` with `type-check` disabled takes 11 seconds, and with it enabled, 12 seconds.

**Comment by fredgate** [comment]
I do not know if `ng lint` should run `--type-check`, but I think that the command of the linter and the content of tslint.json should be consistent. A rule that requires `--type-check` should not be enabled in the TSLint configuration file, if the command `ng lint` does not allow `--type-check` option, as the two are managed by ng CLI.

**Comment by clydin** [comment]
With the current version of the CLI and a TSLint version greater than 5.5 (new projects have 5.7), rules requiring type information are automatically supported if a project file is configured (default for new projects).  The `--type-check` option is not needed.

**Comment by johnpapa** [comment]
Hi @hansl ... thanks for all of the hard work. Cna you provide an update on the status of this one? Thanks!
