### ISSUE TITLE
Build environment flag ignored: ng build --env=dev

### ISSUE THREAD

**Issue by seevee** [angular/angular-cli#6543]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.1.0
node: v8.0.0
npm: 5.0.0
yarn: v0.24.5
http-server: 0.10.0
OS: Ubuntu 17.04

#### In project root:

```
ng build --env=dev
cd dist
http-server -a localhost
```

#### In `.angular-cli.json`:
```
{
  ...
  "environmentSource": "environments/environment.ts",
  "environments": {
    "source": "environments/environment.ts",
    "dev": "environments/environment.dev.ts",
    "staging": "environments/environment.staging.ts",
    "prod": "environments/environment.prod.ts"
  }
  ...
}
```

### The log given by the failure.

No useful log, no errors. Bug is indicated by inappropriate network requests in Chrome/Firefox debuggers (using production API URL specified only in `environment.prod.ts`).

### Desired functionality.

I would like to generate production and development-targeted builds locally using environment settings from `environment.dev.ts`. I would also like to generate production builds for a staging environment using `environment.staging.ts`. These things should be acheivable using default `angular-cli.json` config syntax.

### Mention any other details that might be useful.

The issue can be solved by adding `./` to the beginning of each environment path, like so:
```
{
  ...
  "environmentSource": "./environments/environment.ts",
  "environments": {
    "source": "./environments/environment.ts",
    "dev": "./environments/environment.dev.ts",
    "staging": "./environments/environment.staging.ts",
    "prod": "./environments/environment.prod.ts"
  }
  ...
}
```

`ng serve --env=dev` works properly and is unaffected by the path syntax. I can run `ng serve` using any environment file I wish.

May be related to #5407

**Comment by sumitarora** [comment]
@seevee I tried to replicate the issue seems to be working fine. The only issue I saw is when running `http-server` it was caching the files so have to check in incognito mode and everything looked good. Can you check again?

**Comment by seevee** [comment]
Wow, I totally spaced that! Thank you for the help.

**Comment by rodrigoporcionato** [comment]
wow!!! thanks for this issue!
