### ISSUE TITLE
"ng new" stuck when installing packages via npm

### ISSUE THREAD

**Issue by wanpeng2008** [angular/angular-cli#6545]
angular-cli: 1.0.0-beta.28.3
node: 7.8.0
os: darwin x64

Installing packages for tooling via npm.
npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Unexpected end of input at 1:12441
npm ERR! rc.0","@angular/common":"2.2.0-rc.0"},"directories":{},"dist":{"shasu
npm ERR!

**Comment by wanpeng2008** [comment]
i uninstall angular-cli and update @angular/cli to 1.1.0, the error remains

**Comment by filipesilva** [comment]
`1.0.0-beta.28.3` is not supported anymore and you should update to `1.x+`. An upgrade guide can be found in https://github.com/angular/angular-cli/wiki/stories-1.0-update. You might still have the old version in your package.json and that's why you get a warning.

**Comment by wanpeng2008** [comment]
oh yeah, it works after removing the old version completely. Thanks very much
