### ISSUE TITLE
Angular CLI trys to compile non-focused/(excluded?) tests

### ISSUE THREAD

**Issue by DickSmith** [angular/angular-cli#6555]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.0
node: 7.10.0
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

### Repro steps.
Have a test with a compile time error such as `Property ... does not exist on type ...` or `Module ... has no exported member ...`.
`npm run test` with only compilable tests focused (or uncompilable tests excluded?) [See note below]
Angular CLI still attempts to compile excluded or non-focused tests

### The log given by the failure.
The compile for the tests fail because it is trying to run the broken tests:
ERROR in ...): Property '...' does not exist on type '.'.

ERROR in ...: Module '"..."' has no exported member '...'.

ERROR in ...: Module '"..."' has no exported member '...'.

### Desired functionality.
It works as 1.0.6 did and doesn't try to compile excluded or non-focused tests. An excluded or non-focus test may likely be so because it can't compile in the first place.

### Mention any other details that might be useful.
If I do nothing other than run `npm i @angular/cli@1.0.6` and rerun `npm run test` everything works properly again, but the moment I reinstall `npm i @angular/cli@1.1.0` and run `npm run test` they fail again.

***Note: may only occur with non-focused tests when others have been focused. Previously I had only been using focus to exclude tests, rather than direct exclusion.***

_keywords: fdescribe, fit, xdescribe, xit, karma, jasmine_

**Comment by DickSmith** [comment]
N/M

**Comment by filipesilva** [comment]
This sounds like it's working as it should really. When you use `fdescribe/fit/xdescribe/xit` it only affects the runtime behaviour of karma. It doesn't affect compilation in any way.

So if you have a test file that doesn't compile and it's included in the compilation, you should get an error. If this didn't happen in 1.0.6 then it was probably a bug there.
