### ISSUE TITLE
ng test failing after upgrading to @angular/cli:1.1.0

### ISSUE THREAD

**Issue by SathvikPaturi** [angular/angular-cli#6557]
I installed the latest version today and ng test is failing . 
![angular version 1 1 0](https://cloud.githubusercontent.com/assets/29151864/26741985/ac06d840-47a9-11e7-97c3-ed1af81f6468.PNG)
![errors 1](https://cloud.githubusercontent.com/assets/29151864/26741987/ad73079e-47a9-11e7-8057-2e055539ab93.PNG)
![errors 2](https://cloud.githubusercontent.com/assets/29151864/26741989/ae7fc6d6-47a9-11e7-8d38-7f7281f8668f.PNG)

"devDependencies": {
"@angular/cli": "^1.1.0",
"@angular/compiler-cli": "^4.1.3",
"": "2.5.38",
"": "^4.14.63",
"": "^6.0.75",
"angular2-template-loader": "^0.6.2",
"codelyzer": "~2.0.0",
"electron": "^1.7.2",
"jasmine-core": "~2.5.2",
"jasmine-spec-reporter": "~3.2.0",
"karma": "~1.4.1",
"karma-chrome-launcher": "~2.0.0",
"karma-cli": "~1.0.1",
"karma-coverage-istanbul-reporter": "^0.2.0",
"karma-jasmine": "~1.1.0",
"karma-jasmine-html-reporter": "^0.2.2",
"protractor": "^5.1.2",
"ts-node": "~2.0.0",
"tslint": "~4.5.0",
"typescript": "^2.3.4",
"wallaby-webpack": "0.0.34"

**Comment by SathvikPaturi** [comment]
"devDependencies": {
    "@angular/cli": "^1.1.0",
    "@angular/compiler-cli": "^4.1.3",
    "@types/jasmine": "2.5.38",
    "@types/lodash": "^4.14.63",
    "@types/node": "^6.0.75",
    "angular2-template-loader": "^0.6.2",
    "codelyzer": "~2.0.0",
    "electron": "^1.7.2",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.1.2",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "^2.3.4",
    "wallaby-webpack": "0.0.34"

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

Something you can try meanwhile is checking the `lib` field in `tsconfig` and make sure you follow https://github.com/angular/angular-cli/wiki/stories-1.0-update. Without a repro there isn't much we can do to help however.
