### ISSUE TITLE
error project update - package-lock.json problem ?

### ISSUE THREAD

**Issue by vfedoriv** [angular/angular-cli#6566]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
```

### Versions.
@angular/cli: 1.1.0
node: 8.0.0
npm: 5.0.2
os: win32 x64

### Repro steps.
It's update project problem with package-lock.json file presence.
Steps (in documentation) for update local project:
```
rm -rf node_modules dist 
npm install --save-dev @angular/cli@latest
npm install
```
After
`
npm install --save-dev @angular/cli@latest
`
 we have package-lock.json created.
This prevent correct work step 3 
`npm install
` - as result, angular packages not installed.
When I try build project (ng built), I have error
"You seem to not be depending on "@angular/core". This is an error."

After delete package-lock.json file  and rerun "npm install", build work correct, error gone.

### Desired functionality.
So, need fix documentation or resolve problem with package-lock.json

**Comment by vfedoriv** [comment]
UPD.
It's seems like npm5 problem:
https://github.com/npm/npm/issues/16866

**Comment by filipesilva** [comment]
Yeah this is a NPM thing, not a Angular CLI issue per se. Resolution should come from that issue.
