### ISSUE TITLE
"ng g route" is not generating comma before a route entry under @Routes

### ISSUE THREAD

**Issue by ramachandrann** [angular/angular-cli#658]
1. OS. Windows 7 Enterprise Service Pack1 64-bit 
2.  angular-cli: 0.0.39 <br>
     node: 5.10.1 <br>
     os: win32 x64 <br>
     npm: 3.8.3 <br>
     npm info (attached)
3. Steps <br>
    a. Installed angular-cli globally. <br>
    b. created a project successfully <br>
    c. ng serve (app work well!!) <br>
    d. create a route typing the command <br>
        ng g route new-component <br>
       This doesn't prefix comma (,) after adding in the route for NewComponent under @Routes <br>
        @Routes([ {path:'/', component: ProductsComponent} {path:'/new-component', component: NewComponent}]) <br>

  
[npminfo.txt](https://github.com/angular/angular-cli/files/252193/npminfo.txt)

**Comment by hansl** [comment]
Could you repro this with the beta version (`1.0.0-beta.0`)? This was fixed.

Closing this, please reply here if it's still a bug and I'll reopen. Cheers!
