### ISSUE TITLE
remove angular decorators in third part library (@angular/material2)

### ISSUE THREAD

**Issue by aitboudad** [angular/angular-cli#6581]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

`@ngtools/webpack: 1.4.0`

### Desired functionality.

When building in AOT mode I noticed that only decorators defined in `ts` files are stripped and those defined in node_modules such as `@angular/material2` are still included in the generated bundle.

### Mention any other details that might be useful.

Example material2:
```js
Ge.decorators=[{type:F.Component,args:[{selector:"md-slider, mat-slider",providers:[Be],
host:{"(focus)":"_onFocus()","(blur)":
```

**Comment by filipesilva** [comment]
We're looking at adding this sort of feature.

**Comment by aitboudad** [comment]
done by `@angular-devkit/build-optimizer`
