### ISSUE TITLE
Use of imported class results in `Uncaught Reference` when using class from console during Karma DEBUG

### ISSUE THREAD

**Issue by rjsteinert** [angular/angular-cli#6589]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.1.0
node: 7.8.0
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3
```

### Repro steps.

1. Import `import { By } from '@angular/platform-browser';`, set `debugger;` 
1. Use the `By` Class in a test, place a `debugger;` statement right after your use of `By`.
1. Load the Karma `DEBUG` view in Chrome with developer tools open.
1. When you hit the breakpoint, type `By` into the console.
### The log given by the failure.

<img width="1260" alt="screen shot 2017-06-06 at 7 02 51 am" src="https://cloud.githubusercontent.com/assets/156575/26826880/b08c91c0-4a88-11e7-8b33-ea44434aac11.png">

```
Uncaught ReferenceError: By is not defined
    at eval (eval at <anonymous> (tangerine-page.component.spec.ts:62), <anonymous>:1:1)
    at Object.<anonymous> (tangerine-page.component.spec.ts:62)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at ProxyZoneSpec.webpackJsonp../node_modules/zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (proxy.js:79)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:141)
    at Object.<anonymous> (jasmine-patch.js:104)
    at attemptSync (jasmine.js?916005c…:1950)
    at ZoneQueueRunner.QueueRunner.run (jasmine.js?916005c…:1938)
    at jasmine.js?916005c…:1962
```

### Desired functionality.

When doing test driven development, it's helpful to be able to write code in the console to try things out as opposed to having to write in the text editor and then wait for everything to load all over again.

### Mention any other details that might be useful.

[Related line of code](https://github.com/Tangerine-Community/Tangerine/pull/318/files#diff-657511d2e8d5cb8b787f5f7147f2509fR61).

**Comment by filipesilva** [comment]
I don't think that approach can work at all... You're looking at the original sources and not what the browser is running. Whether or not that should work seems to be up to the chrome debugger. Not sure what we could possibly do on the Angular CLI side.

**Comment by alexzuza** [comment]
Can you disable sourcemap in browser development tools and try again?

**Comment by alan-agius4** [comment]
This is not caused by Angular CLI. 

`By` is not a global variable and hence it cannot be accessed directly in the browser. If it was a global it also goes against the whole concept behind webpack. Since webpack is meant to allow more modular front-end development. This means writing isolated modules that are well contained and do not rely on hidden dependencies such as global variables.
