### ISSUE TITLE
Redundant downloads (51,000 files) from ng new? Most are CLI

### ISSUE THREAD

**Issue by mantissa7** [angular/angular-cli#659]
Is it really necessary to download a copy of ng-cli by using ng-cli? This seems a little counter-intuitive to me.

I watched ngConf last night, and after seeing that the RC is now down to ~40kb, I thought I'd give it a go using angular-cli as suggested by the team. 

So I was rather surprised when after SEVERAL minutes after <code>ng new</code> I found out that the long wait was caused by over 51,000 files being downloaded! Of this it seems that a good 80% of these are from angular-cli downloading itself. 

If it is absolutely necessary (which I don't think it is), then wouldn't it be easier to just cp the global installation into the node_modules folder to speed up the process and let the user <code>npm update</code> if necessary? 

Is there a way to prevent this? This is an absolute killer for me. ngConf boasted at how quick and easy it was to get started with ng-cli, but I could have set all of this up myself manually much more quickly than it takes to <code>ng new</code>, and that was on a fast connection.

**Comment by itslenny** [comment]
Agreed, the `ng new` is pretty slow. Creating new apps isn't something most people do all that often, but it'd be nice if it was quicker.

SailsJS used to handle this by making the CLI include the dependencies to create a new project and it just made a symlink. However, npm no longer supports symlinks.

Two options that come to mind: Copy the files OR add a `--use-cdn` option (or similar) that makes it just use public CDNs for all of the dependencies.

**Comment by hansl** [comment]
We have a plan to thin down our npm dependencies for new projects. This is definitely something we know of, and we'll be working in the next weeks on it.

Thanks!

**Comment by mantissa7** [comment]
Thanks guys, I appreciate all the effort that's been put into this.

**Comment by kylecordes** [comment]
I just noticed this older item somehow. I think my newer item #1263 describes a way to accomplish at least some of what is asked for here.  I don't know if both need to be kept around.

**Comment by filipesilva** [comment]
Closing this in favor of https://github.com/angular/angular-cli/issues/1263 simply because there's more detailed feedback on that one.
