### ISSUE TITLE
The "@angular/compiler-cli" package was not properly installed.

### ISSUE THREAD

**Issue by mscherer82** [angular/angular-cli#6590]
- [x ] bug report -> please search issues before submitting

I got this problem without changing my code. Old tagged versions of my project stopped working as well. 

```
    "@angular/compiler-cli": "^2.4.2",
    "angular-cli": "1.0.0-beta.20-4",
```

I tried to update typescript to 2.2 but it doesn't change anything. It is a larger project so I don't want to update angular at the moment.

**Comment by filipesilva** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the https://github.com/angular/angular project or file an issue on their issue tracker.

**Comment by filipesilva** [comment]
A

**Comment by filipesilva** [comment]
I'm not sure what happened to your dependencies, but most likely reinstalling dependencies got you different versions of `@ngtools/webpack`. You can try pinning it in your `package.json` to a version that works for your project, but we don't really support `1.0.0-beta.20-4` anymore.

**Comment by naru6be** [comment]
Finally found the solution see the below screenshots and steps to resolve this issue
http://itechiesol.blogspot.com/2017/07/angular-compiler-cli-package-was-not.html
