### ISSUE TITLE
ngc with sass to use app in angular universal

### ISSUE THREAD

**Issue by cedvdb** [angular/angular-cli#6591]
### Desired functionality.

As described in [this article](https://medium.com/@evertonrobertoauler/angular-4-universal-app-with-angular-cli-db8b53bba07d) one of the tasks required to build an app that is integrable with angular universal is to import `AppServerModuleNgFactory` which would be to compiled version of `AppServerModule` below. One way of doing that is by running `ngc`. However ngc doesn't run correctly when scss is used in place of css in the cli. I would like the cli to be able to build the project in such a way that I could use it in angular universal. Something like `build --ngc` I found this [loader](https://www.npmjs.com/package/ngc-webpack) for webpack that claims to do ngc even when scss is used, so it should at least be possible. Obviously things go a bit over my head at the moment, so I don't know if this is an implementable feature or if what I'm asking is out of place.

Here is the AppServerModule I talked about above:

```
import { NgModule } from '@angular/core';
import { ServerModule } from '@angular/platform-server';
import { AppModule } from './app.module';
import { AppComponent } from './app.component';

@NgModule({
  imports: [
    ServerModule,
    AppModule
  ],
  bootstrap: [AppComponent]
})
export class AppServerModule { }
```

**Comment by filipesilva** [comment]
Angular CLI does not currently support Universal. This feature is being tracked in https://github.com/angular/angular-cli/issues/1050.
