### ISSUE TITLE
What does the karma setting do?

### ISSUE THREAD

**Issue by megamindbrian** [angular/angular-cli#6596]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

Please explain what is being configured automatically by the "test" property in angular-cli.json.  Is it automatically configuring karma plugins?  If so, why does adding to the plugins require all the plugin to be listed in karma.conf?

**Comment by filipesilva** [comment]
It configures where `ng test` will look for the karma configuration to send to Karma, and if some files should be excluded from the TS compilation. You can find that information in https://github.com/angular/angular-cli/wiki/angular-cli.

**Comment by megamindbrian** [comment]
Sorry, this is definitely not closed.  Why do I need angular/testing and Karma?  Why do I need to remember where to put this setting in at least 3 places?  Why do you make design decisions that makes lives more difficult?  You can mark this closed but this is a very open issue.  Why doesn't anyone ever question this?
https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f

**Comment by megamindbrian** [comment]
Nobody every questions this, so I am calling you out:
https://medium.com/@lucasdaltro/learning-javascript-in-2017-sucks-and-this-is-very-good-35e883223406

Remove the "test" option from angular and educate people on the right tools to use.  Testing should not make build stacks more complicated, that is the opposite of unit testing.
