### ISSUE TITLE
Support PathLocationStrategy out of the box

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#66]
[`PathLocationStrategy`](https://angular.io/docs/js/latest/api/router/PathLocationStrategy-class.html) requires server rewrites to be setup. We should do this OOB since we want to promote the use of this strategy over hash location strategy.

**Comment by intellix** [comment]
I've investigated this somewhat and it seems that ember-cli uses middleware for SPA support: https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/middleware/history-support/index.js#L22

We just need a blueprint for an environment file containing a baseURL and locationType of `auto` and it'll work: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/config/environment.js

**Comment by IgorMinar** [comment]
@intellix would you like to send us a PR?

**Comment by cironunes** [comment]
@IgorMinar, he sent this one: https://github.com/angular/angular-cli/pull/121

**Comment by petebacondarwin** [comment]
Closed by #121
