### ISSUE TITLE
Module not found: Error: Can't resolve -> adding background-image without '/'

### ISSUE THREAD

**Issue by jamilalisgandarov** [angular/angular-cli#6603]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.3
node: 6.10.3
os: darwin x64
@angular/animations: 4.1.2
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/compiler-cli: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/platform-server: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.3

### Repro steps.
Using `background-image : url() ` path without slash gives error . Ex:
Not works:
`    background-image: url('manage/assets/images/play-button.svg')
`
Works:
`    background-image: url('/manage/assets/images/play-button.svg')
`

### The log given by the failure.
ERROR in ./src/app/manage/contents/home/home.component.css
Module not found: Error: Can't resolve './manage/assets/images/play-button.svg' in '/Users/Alisgandarov/Desktop/Projects/Jabd
a_Manage/src/app/manage/contents/home

### Desired functionality.
It is needed to work without slash, because my application is in subfolder in the serve ('/manage' in this case) , but we are working in the index , so you need to change '/' to '/subfolder' everytime on build.

**Comment by clydin** [comment]
Assets with relative URLs are managed by the CLI and processed at build time.  This is the cause of the build error.  It is recommended to use this approach as the asset will benefit from hashing and automatic copying to the output (and in the future, image optimization passes).

When using the root relative URL, in processing occurs on the asset.  However, the URL will be adjusted based on the deploy URL and/or base HREF options, if provided.
