### ISSUE TITLE
Rebuild crashes when testing on Windows machine

### ISSUE THREAD

**Issue by LasTanzen** [angular/angular-cli#6605]
This bug report is an answer to the closed PR https://github.com/angular/angular-cli/pull/6535
~Since I´m not in office this week i can´t provide all the information. The report will be updated next monday.~

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.1.0
node: 7.0.0
os: win32 x64
@angular/cli: 1.1.0
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
```
System is Windows 10. 

### Repro steps.
- Run `ng test`
- After the first testrun add an import to a submodule:
  e.g. inside `src/app/my-submodule/my-submodule.module.ts` add `import { ReactiveFormsModule } from '@angular/forms';`. This also works the other way round, when removing an import.

### The log given by the failure.
```
ERROR in ./src/app/my-submodule/my-submodulemodule.ts
Module build failed: Error
    at WebpackCompilerHost.populateWebpackResolver (C:\path\to\the\app\node_modules\@ngtools\webpack\src\compiler_host.js:135:51)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\path\to\the\app\node_modules\@ngtools\webpack\src\plugin.js:371:32)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./~/@angular/core/@angular/core/testing.es5.js
 @ ./src/test.ts

ERROR in
```

### Desired functionality.
The rebuild does not crash.

### Mention any other details that might be useful.
This can be hotfixed by applying the changes in https://github.com/angular/angular-cli/pull/6535

I hope I can continue the conversation with @filipesilva from the PR comments here.
In your comment you say we need normalized paths with forward slashes, but what the plugin does is replacing the forward slashes with backward slashes, which leads to an exception on rebuild (weirdly only when testing). Should we maybe just do it the other way round?

Thanks and if you need any further help, just tell me :)

Cheers,
Stefan

## Update 2017-06-12
Added version information and improved repro steps

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
