### ISSUE TITLE
CONTRIBUTING.md references missing DEVELOPER.md

### ISSUE THREAD

**Issue by adamclerk** [angular/angular-cli#661]

**Comment by adamclerk** [comment]
@Brocco BTW: great talk at ng-conf

**Comment by hansl** [comment]
Thanks a lot, we'll add it!

**Comment by adamclerk** [comment]
@hansl is it somewhere in the git commit history? I'd be more than happy to find it and issue a PR.

**Comment by CarreraPHP** [comment]
Right now the Developer Documentation link points to the angular project "[Developer.md](https://github.com/angular/angular/blob/master/DEVELOPER.md)" file, Instead we can point it to the development hack block of the "[Readme.md](https://github.com/angular/angular-cli#development-hints-for-hacking-on-angular-cli)" of angular-cli.

**Comment by hansl** [comment]
Closing this as obsolete.
