### ISSUE TITLE
Upgrading from 1.0.0 to 1.1.1 leads to error 'No matching version found for @ngtools/webpack@1.4.1'

### ISSUE THREAD

**Issue by OddDev** [angular/angular-cli#6611]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 8.0.0
os: win32 x64
@angular/animations: 4.0.3
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/compiler-cli: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/platform-server: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.0

Microsoft Windows 7 Professional
6.1.7601 Service Pack 1 Build 7601

### Repro steps.

Execute npm install -g @angular/cli@1.1.1

### The log given by the failure.

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ngtools/webpack@1.4.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@angular/cli'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\user\AppData\Roaming\npm-cache\_logs\2017-06-08T08_05_02_241Z-debu

#### Debug file
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Applications\\Apps\\NodeJS8\\node.exe',
1 verbose cli   'D:\\Applications\\Apps\\NodeJS8\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli@1.1.1' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/@angular%2fcli 62ms
7 silly pacote version manifest for @angular/cli@1.1.1 fetched in 78ms
8 silly install loadIdealTree
9 silly install cloneCurrentTreeToIdealTree
10 silly install loadShrinkwrap
11 silly install loadAllDepsIntoIdealTree
12 silly resolveWithNewModule @angular/cli@1.1.1 checking installable status
13 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/chalk 31ms
14 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/debug 78ms
15 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/autoprefixer 78ms
16 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/@ngtools%2fjson-schema 109ms
17 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/denodeify 109ms
18 silly pacote version manifest for @ngtools/json-schema@1.1.0 fetched in 109ms
19 silly resolveWithNewModule @ngtools/json-schema@1.1.0 checking installable status
20 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/chalk/-/chalk-1.1.3.tgz 63ms
21 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/css-loader 109ms
22 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/@ngtools%2fwebpack 124ms
23 silly fetchPackageMetaData error for @ngtools/webpack@1.4.1 No matching version found for @ngtools/webpack@1.4.1
24 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/common-tags 124ms
25 silly pacote range manifest for css-loader@^0.28.1 fetched in 140ms
26 silly resolveWithNewModule css-loader@0.28.4 checking installable status
27 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/diff 140ms
28 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/cssnano 156ms
29 silly pacote range manifest for chalk@^1.1.3 fetched in 187ms
30 silly resolveWithNewModule chalk@1.1.3 checking installable status
31 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/debug/-/debug-2.6.8.tgz 94ms
32 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/autoprefixer/-/autoprefixer-6.7.7.tgz 94ms
33 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/denodeify/-/denodeify-1.2.1.tgz 78ms
34 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/ember-cli-string-utils 78ms
35 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/ember-cli-normalize-entity-name 93ms
36 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/exports-loader 62ms
37 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/common-tags/-/common-tags-1.4.0.tgz 78ms
38 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/diff/-/diff-3.2.0.tgz 78ms
39 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/cssnano/-/cssnano-3.10.0.tgz 78ms
40 silly pacote range manifest for autoprefixer@^6.5.3 fetched in 234ms
41 silly resolveWithNewModule autoprefixer@6.7.7 checking installable status
42 silly pacote range manifest for debug@^2.1.3 fetched in 234ms
43 silly resolveWithNewModule debug@2.6.8 checking installable status
44 silly pacote range manifest for denodeify@^1.2.1 fetched in 249ms
45 silly resolveWithNewModule denodeify@1.2.1 checking installable status
46 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/extract-text-webpack-plugin 62ms
47 silly pacote range manifest for common-tags@^1.3.1 fetched in 249ms
48 silly resolveWithNewModule common-tags@1.4.0 checking installable status
49 silly pacote range manifest for extract-text-webpack-plugin@^2.1.0 fetched in 62ms
50 silly resolveWithNewModule extract-text-webpack-plugin@2.1.0 checking installable status
51 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/ember-cli-normalize-entity-name/-/ember-cli-normalize-entity-name-1.0.0.tgz 47ms
52 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/ember-cli-string-utils/-/ember-cli-string-utils-1.1.0.tgz 63ms
53 silly pacote range manifest for cssnano@^3.10.0 fetched in 265ms
54 silly resolveWithNewModule cssnano@3.10.0 checking installable status
55 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/exports-loader/-/exports-loader-0.6.4.tgz 47ms
56 silly pacote range manifest for diff@^3.1.0 fetched in 265ms
57 silly resolveWithNewModule diff@3.2.0 checking installable status
58 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/file-loader 46ms
59 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/fs-extra 46ms
60 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/get-caller-file 31ms
61 silly pacote range manifest for ember-cli-normalize-entity-name@^1.0.0 fetched in 187ms
62 silly resolveWithNewModule ember-cli-normalize-entity-name@1.0.0 checking installable status
63 silly pacote range manifest for ember-cli-string-utils@^1.0.0 fetched in 172ms
64 silly resolveWithNewModule ember-cli-string-utils@1.1.0 checking installable status
65 silly pacote range manifest for exports-loader@^0.6.3 fetched in 156ms
66 silly resolveWithNewModule exports-loader@0.6.4 checking installable status
67 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/html-webpack-plugin 63ms
68 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/inflection 47ms
69 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/glob 78ms
70 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/inquirer 62ms
71 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/file-loader/-/file-loader-0.10.1.tgz 78ms
72 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/get-caller-file/-/get-caller-file-1.0.2.tgz 62ms
73 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/fs-extra/-/fs-extra-2.1.2.tgz 62ms
74 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/isbinaryfile 78ms
75 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/json-loader 78ms
76 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/less 78ms
77 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/html-webpack-plugin/-/html-webpack-plugin-2.28.0.tgz 78ms
78 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/glob/-/glob-7.1.2.tgz 63ms
79 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/inquirer/-/inquirer-3.0.6.tgz 63ms
80 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/inflection/-/inflection-1.12.0.tgz 63ms
81 silly pacote range manifest for file-loader@^0.10.0 fetched in 171ms
82 silly resolveWithNewModule file-loader@0.10.1 checking installable status
83 silly pacote range manifest for get-caller-file@^1.0.0 fetched in 156ms
84 silly resolveWithNewModule get-caller-file@1.0.2 checking installable status
85 silly pacote range manifest for fs-extra@^2.0.0 fetched in 171ms
86 silly resolveWithNewModule fs-extra@2.1.2 checking installable status
87 silly pacote range manifest for html-webpack-plugin@^2.19.0 fetched in 172ms
88 silly resolveWithNewModule html-webpack-plugin@2.28.0 checking installable status
89 silly pacote range manifest for glob@^7.0.3 fetched in 172ms
90 silly resolveWithNewModule glob@7.1.2 checking installable status
91 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/json-loader/-/json-loader-0.5.4.tgz 31ms
92 silly pacote range manifest for inflection@^1.7.0 fetched in 156ms
93 silly resolveWithNewModule inflection@1.12.0 checking installable status
94 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/isbinaryfile/-/isbinaryfile-3.0.2.tgz 47ms
95 silly pacote range manifest for inquirer@^3.0.0 fetched in 156ms
96 silly resolveWithNewModule inquirer@3.0.6 checking installable status
97 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/less-loader 31ms
98 silly pacote range manifest for json-loader@^0.5.4 fetched in 156ms
99 silly resolveWithNewModule json-loader@0.5.4 checking installable status
100 silly pacote range manifest for less-loader@^4.0.2 fetched in 47ms
101 silly resolveWithNewModule less-loader@4.0.4 checking installable status
102 silly pacote range manifest for isbinaryfile@^3.0.0 fetched in 156ms
103 silly resolveWithNewModule isbinaryfile@3.0.2 checking installable status
104 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/lodash 47ms
105 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/memory-fs 47ms
106 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/node-modules-path 47ms
107 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/minimatch 47ms
108 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/nopt 62ms
109 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/opn 62ms
110 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/portfinder 47ms
111 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/postcss-loader 47ms
112 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/memory-fs/-/memory-fs-0.4.1.tgz 46ms
113 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/postcss-url 62ms
114 silly pacote range manifest for postcss-loader@^1.3.3 fetched in 62ms
115 silly resolveWithNewModule postcss-loader@1.3.3 checking installable status
116 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/node-modules-path/-/node-modules-path-1.0.1.tgz 62ms
117 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/minimatch/-/minimatch-3.0.4.tgz 63ms
118 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/opn/-/opn-4.0.2.tgz 63ms
119 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/nopt/-/nopt-4.0.1.tgz 63ms
120 silly pacote range manifest for memory-fs@^0.4.1 fetched in 141ms
121 silly resolveWithNewModule memory-fs@0.4.1 checking installable status
122 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/portfinder/-/portfinder-1.0.13.tgz 62ms
123 silly pacote range manifest for node-modules-path@^1.0.0 fetched in 140ms
124 silly resolveWithNewModule node-modules-path@1.0.1 checking installable status
125 silly pacote range manifest for minimatch@^3.0.3 fetched in 140ms
126 silly resolveWithNewModule minimatch@3.0.4 checking installable status
127 silly pacote range manifest for nopt@^4.0.1 fetched in 156ms
128 silly resolveWithNewModule nopt@4.0.1 checking installable status
129 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/postcss-url/-/postcss-url-5.1.2.tgz 47ms
130 silly pacote version manifest for opn@4.0.2 fetched in 156ms
131 silly resolveWithNewModule opn@4.0.2 checking installable status
132 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/lodash/-/lodash-4.17.4.tgz 125ms
133 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/raw-loader 47ms
134 silly pacote range manifest for portfinder@~1.0.12 fetched in 125ms
135 silly resolveWithNewModule portfinder@1.0.13 checking installable status
136 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/less/-/less-2.7.2.tgz 187ms
137 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/resolve 46ms
138 silly pacote range manifest for postcss-url@^5.1.2 fetched in 140ms
139 silly resolveWithNewModule postcss-url@5.1.2 checking installable status
140 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/rimraf 47ms
141 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/rsvp 109ms
142 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/semver 78ms
143 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/script-loader 93ms
144 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/resolve/-/resolve-1.3.3.tgz 94ms
145 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/raw-loader/-/raw-loader-0.5.1.tgz 109ms
146 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/sass-loader 125ms
147 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/rimraf/-/rimraf-2.6.1.tgz 94ms
148 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/rxjs 125ms
149 silly pacote range manifest for sass-loader@^6.0.3 fetched in 140ms
150 silly resolveWithNewModule sass-loader@6.0.5 checking installable status
151 silly pacote range manifest for less@^2.7.2 fetched in 421ms
152 silly resolveWithNewModule less@2.7.2 checking installable status
153 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/rsvp/-/rsvp-3.5.0.tgz 63ms
154 silly pacote range manifest for raw-loader@^0.5.1 fetched in 218ms
155 silly resolveWithNewModule raw-loader@0.5.1 checking installable status
156 silly pacote range manifest for resolve@^1.1.7 fetched in 202ms
157 silly resolveWithNewModule resolve@1.3.3 checking installable status
158 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/semver/-/semver-5.3.0.tgz 78ms
159 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/script-loader/-/script-loader-0.7.0.tgz 78ms
160 silly pacote range manifest for rimraf@^2.5.3 fetched in 187ms
161 silly resolveWithNewModule rimraf@2.6.1 checking installable status
162 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/source-map-loader 47ms
163 silly pacote range manifest for script-loader@^0.7.0 fetched in 187ms
164 silly resolveWithNewModule script-loader@0.7.0 checking installable status
165 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/silent-error 63ms
166 silly pacote range manifest for semver@^5.1.0 fetched in 188ms
167 silly resolveWithNewModule semver@5.3.0 checking installable status
168 silly pacote range manifest for source-map-loader@^0.2.0 fetched in 63ms
169 silly resolveWithNewModule source-map-loader@0.2.1 checking installable status
170 silly pacote range manifest for lodash@^4.11.1 fetched in 375ms
171 silly resolveWithNewModule lodash@4.17.4 checking installable status
172 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/istanbul-instrumenter-loader 32ms
173 silly pacote range manifest for rsvp@^3.0.17 fetched in 234ms
174 silly resolveWithNewModule rsvp@3.5.0 checking installable status
175 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/stylus 63ms
176 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/style-loader 63ms
177 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/temp 31ms
178 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/silent-error/-/silent-error-1.1.0.tgz 31ms
179 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/stylus-loader 47ms
180 silly pacote range manifest for stylus-loader@^3.0.1 fetched in 47ms
181 silly resolveWithNewModule stylus-loader@3.0.1 checking installable status
182 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/url-loader 46ms
183 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/istanbul-instrumenter-loader/-/istanbul-instrumenter-loader-2.0.0.tgz 31ms
184 silly pacote range manifest for silent-error@^1.0.0 fetched in 109ms
185 silly resolveWithNewModule silent-error@1.1.0 checking installable status
186 silly pacote range manifest for istanbul-instrumenter-loader@^2.0.0 fetched in 94ms
187 silly resolveWithNewModule istanbul-instrumenter-loader@2.0.0 checking installable status
188 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/rxjs/-/rxjs-5.4.0.tgz 141ms
189 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/url-loader/-/url-loader-0.5.8.tgz 47ms
190 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/typescript 109ms
191 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/webpack-dev-server 62ms
192 silly pacote range manifest for webpack-dev-server@~2.4.5 fetched in 62ms
193 silly resolveWithNewModule webpack-dev-server@2.4.5 checking installable status
194 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/temp/-/temp-0.8.3.tgz 93ms
195 silly pacote range manifest for url-loader@^0.5.7 fetched in 140ms
196 silly resolveWithNewModule url-loader@0.5.8 checking installable status
197 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/walk-sync 125ms
198 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/stylus/-/stylus-0.54.5.tgz 125ms
199 silly pacote version manifest for temp@0.8.3 fetched in 187ms
200 silly resolveWithNewModule temp@0.8.3 checking installable status
201 silly pacote range manifest for rxjs@^5.0.1 fetched in 405ms
202 silly resolveWithNewModule rxjs@5.4.0 checking installable status
203 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/webpack 171ms
204 silly pacote range manifest for webpack@~2.4.0 fetched in 203ms
205 silly resolveWithNewModule webpack@2.4.1 checking installable status
206 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/style-loader/-/style-loader-0.13.2.tgz 203ms
207 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/webpack-dev-middleware 188ms
208 silly pacote range manifest for stylus@^0.54.5 fetched in 266ms
209 silly resolveWithNewModule stylus@0.54.5 checking installable status
210 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/webpack-merge 125ms
211 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/walk-sync/-/walk-sync-0.3.2.tgz 109ms
212 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/zone.js 109ms
213 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/node-sass 62ms
214 silly pacote range manifest for style-loader@^0.13.1 fetched in 297ms
215 silly resolveWithNewModule style-loader@0.13.2 checking installable status
216 silly pacote range manifest for walk-sync@^0.3.1 fetched in 250ms
217 silly resolveWithNewModule walk-sync@0.3.2 checking installable status
218 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/webpack-dev-middleware/-/webpack-dev-middleware-1.10.2.tgz 31ms
219 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/webpack-merge/-/webpack-merge-2.6.1.tgz 31ms
220 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/zone.js/-/zone.js-0.8.12.tgz 31ms
221 silly pacote range manifest for webpack-dev-middleware@^1.10.2 fetched in 234ms
222 silly resolveWithNewModule webpack-dev-middleware@1.10.2 checking installable status
223 silly pacote range manifest for webpack-merge@^2.4.0 fetched in 156ms
224 silly resolveWithNewModule webpack-merge@2.6.1 checking installable status
225 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/node-sass/-/node-sass-4.5.3.tgz 47ms
226 silly pacote range manifest for zone.js@^0.8.4 fetched in 156ms
227 silly resolveWithNewModule zone.js@0.8.12 checking installable status
228 silly pacote range manifest for node-sass@^4.3.0 fetched in 125ms
229 silly resolveWithNewModule node-sass@4.5.3 checking installable status
230 http fetch GET 200 http://enterprise-nexus:8081/nexus/repository/npm-all/typescript/-/typescript-2.3.4.tgz 422ms
231 silly pacote range manifest for typescript@>=2.0.0 <2.4.0 fetched in 546ms
232 silly resolveWithNewModule typescript@2.3.4 checking installable status
233 verbose type version
234 verbose stack @ngtools/webpack: No matching version found for @ngtools/webpack@1.4.1
234 verbose stack     at pickManifest (D:\Applications\Apps\NodeJS8\node_modules\npm\node_modules\pacote\node_modules\npm-pick-manifest\index.js:61:11)
234 verbose stack     at fetchPackument.then.packument (D:\Applications\Apps\NodeJS8\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:39:14)
234 verbose stack     at tryCatcher (D:\Applications\Apps\NodeJS8\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
234 verbose stack     at Promise._settlePromiseFromHandler (D:\Applications\Apps\NodeJS8\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
234 verbose stack     at Promise._settlePromise (D:\Applications\Apps\NodeJS8\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
234 verbose stack     at Promise._settlePromise0 (D:\Applications\Apps\NodeJS8\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
234 verbose stack     at Promise._settlePromises (D:\Applications\Apps\NodeJS8\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
234 verbose stack     at Async._drainQueue (D:\Applications\Apps\NodeJS8\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
234 verbose stack     at Async._drainQueues (D:\Applications\Apps\NodeJS8\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
234 verbose stack     at Immediate.Async.drainQueues (D:\Applications\Apps\NodeJS8\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
234 verbose stack     at runCallback (timers.js:800:20)
234 verbose stack     at tryOnImmediate (timers.js:762:5)
234 verbose stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
235 verbose cwd D:\Users\user\IdeaProjects\spc-management
236 verbose Windows_NT 6.1.7601
237 verbose argv "D:\\Applications\\Apps\\NodeJS8\\node.exe" "D:\\Applications\\Apps\\NodeJS8\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli@1.1.1"
238 verbose node v8.0.0
239 verbose npm  v5.0.0
240 error code ETARGET
241 error notarget No matching version found for @ngtools/webpack@1.4.1
242 error notarget In most cases you or one of your dependencies are requesting
242 error notarget a package version that doesn't exist.
242 error notarget
242 error notarget It was specified as a dependency of '@angular/cli'
243 verbose exit [ 1, true ]

### Desired functionality.

Installing the actual version of Angular CLI just like you would do with any other npm package. 

### Mention any other details that might be useful.

I've tested this with the LTS Node.JS and the most recent Node.JS. Don't know how this affects the npm version. 
We've confirmed that issue on two other clients. Unfortunately they are setup nearly the same way as the reporting client.

**Comment by OddDev** [comment]
Was rather a problem with our local nexus server. Invalidated the cache and rebuild the index of the NPM proxy repository.

**Comment by Brocco** [comment]
@OddDev to be clear, is this issue resolved? If so, please close.

**Comment by hansl** [comment]
Closing this. Open a new issue if this is still happening.

**Comment by OddDev** [comment]
@hansl @Brocco Thank you! Forgot to close this issue. Is resolved. 
For future readers: As mentioned above I've invalidated the cache and rebuild the index of the NPM proxy repository in the nexus server.
