### ISSUE TITLE
Please provide changelog for @ngtools/webpack

### ISSUE THREAD

**Issue by klinki** [angular/angular-cli#6612]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
Could you please provide some changelog for `@ngtools/webpack`? Maybe there is some and I missed it, but I haven't noticed any.

**Comment by tinchou** [comment]
I've been trying to follow this too, and it's hard without a changelog. There are changes mentioned in the [releases page](https://github.com/angular/angular-cli/releases), but you never know which version they correspond to.

I think these would be valid options:

* have a CHANGELOG.md file in the package folder
* align version number with the @angular/cli package, as the main repo does

**Comment by realappie** [comment]
Yes please, its really hard to track the teams progress without a changelog.

**Comment by alan-agius4** [comment]
Yes please!

**Comment by alan-agius4** [comment]
The improved releases page (https://github.com/angular/angular-cli/releases) should tackle this.

If we are missing something, kindly open a new issue explaining the desired information.

Thanks
