### ISSUE TITLE
move from v1.0.0-rc.1 to latest version  1.1.1. change  increased +10/15 seconds 

### ISSUE THREAD

**Issue by GoNode5** [angular/angular-cli#6614]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```
### Versions.

@angular/cli: 1.1.1
node: 8.0.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

### Repro steps.

I moved from March versions to latest, including Node 8. My change time with ng serve, changing 1 letter in an html file takes now much longer to the point App is ready. About 10 to 15 seconds extra Any advice?
![image](https://user-images.githubusercontent.com/2210672/26941028-389be6e2-4c7d-11e7-8202-75af00b090d6.png)

![image](https://user-images.githubusercontent.com/2210672/26941056-544cb27c-4c7d-11e7-9b12-f6846702f2da.png)

**Comment by clydin** [comment]
Were source maps enabled when using the older version?

**Comment by GoNode5** [comment]
@clydin not that i am aware of...

**Comment by hansl** [comment]
Closing this as obsolete/fixed.
