### ISSUE TITLE
Live reload is not happening when the project path length is big

### ISSUE THREAD

**Issue by tibinthomas** [angular/angular-cli#6616]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

angular-cli: 1.0.0-beta.28.3
node: 6.11.0
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.6
@angular/compiler-cli: 4.1.3

### Repro steps.

1) Move the project to a nested folder structure each of having 5 to 8 letter names.
2) ng serve
3) Modify some file
4) Check for the change again. See if the live reload happen or not.

### The log given by the failure.

No failure logs

### Desired functionality.

The live reload should work even if the app is inside a nested folder structure

**Comment by sumitarora** [comment]
@tibinthomas Can you please check with updated CLI version?

**Comment by ivanbtrujillo** [comment]
Hi, I'm working with the latest version of @angular/cli and still not working:
```
@angular/cli: 1.1.2
node: 7.2.1
os: linux x64
@angular/animations: 4.2.3
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/compiler-cli: 4.2.3
@angular/core: 4.2.3
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/platform-server: 4.2.3
@angular/router: 4.2.3
@angular/cli: 1.1.2
```
If I make a change in:*
```
app.component.ts
```
it works perfectly but for example, if i make a change in 
```
src/app/scenes/scene1/scene1.component.ts
```
it doesn't work.

Thanks!
