### ISSUE TITLE
generating route must add all dependencies to .spec file

### ISSUE THREAD

**Issue by alvipeo** [angular/angular-cli#662]
with the 0.1.0 version I added new route so cli generated a component setup route. but if I run 'ng test' I get errors. I added ROUTE_PROVIDERS to .spec file but that didn't help:

>>Error: Platforms have to be created via `createPlatform`!

Now, what are platforms? oh...

**Comment by JohnCashmore** [comment]
Did you get anywhere with this?

**Comment by JohnCashmore** [comment]
Never mind i did @alvipeo, in your spec file you need to use 
```
import {ROUTER_FAKE_PROVIDERS} from '@angular/router/testing';
```
and use that provider

**Comment by dracon** [comment]
@JohnCashmore Thank you, that works for me

**Comment by joaogarin** [comment]
what to do with the case of the deprecated router?

**Comment by filipesilva** [comment]
I'm closing this issue as obsolete, because we've recently both disabled route generation and also simplified tests across the board.

**Comment by AlekseevI** [comment]
I still get this error with this setup
```
    "@angular/common": "2.0.0-rc.2",
    "@angular/compiler": "2.0.0-rc.2",
    "@angular/core": "2.0.0-rc.2",
    "@angular/http": "2.0.0-rc.2",
    "@angular/platform-browser": "2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "2.0.0-rc.2",
    "@angular/router": "3.0.0-alpha.7",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.2",
```

What I am doing wrong?

**Comment by leonadler** [comment]
Any updates for rc2/rc3? I still get the error:
```
ORIGINAL EXCEPTION: Platforms have to be created via `createPlatform`!
```

The provided solution does not work anymore:
```
import {ROUTER_FAKE_PROVIDERS} from '@angular/router/testing';
```
`[ts] Cannot find module '@angular/router/testing'.`
