### ISSUE TITLE
Fresh install of @angular/cli NOT @angular-cli

### ISSUE THREAD

**Issue by shawnrmoss** [angular/angular-cli#6622]
Ive tried to install the @angular/cli and when I just try to check the version I get the error below.  Exact same error when I try to create a new project with ng

### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Output from: `ng --version`.
 npm --version 3.10.10
  Windows 10

### Repro steps.

npm install -g @angular/cli
ng -v

AppData\Roaming\npm\node_modules\@angular\cli\models\config\config.js:77
            throw new InvalidConfigError('Parsing .angular-cli.json failed. Please make sure your .angular-cli.json'
            ^

InvalidConfigError: Parsing .angular-cli.json failed. Please make sure your .angular-cli.json is valid JSON. Error:
SyntaxError: Unexpected token u in JSON at position 22
    at InvalidConfigError (C:\Users\shawn\AppData\Roaming\npm\node_modules\@angular\cli\models\config\config.js:10:9)
    at Function.fromConfigPath (C:\Users\shawn\AppData\Roaming\npm\node_modules\@angular\cli\models\config\config.js:77:19)
    at Function.fromGlobal (C:\Users\shawn\AppData\Roaming\npm\node_modules\@angular\cli\models\config.js:56:46)
    at Object.<anonymous> (C:\Users\shawn\AppData\Roaming\npm\node_modules\@angular\cli\commands\build.js:7:71)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by clydin** [comment]
Do you have an angular-cli.json file in your home directory?  If so, try removing it.

**Comment by shawnrmoss** [comment]
No my problem is there is no project yet.  I grabbed @angular/cli using npm and any command I try using ng generates the same error.  No project is ever generated.  I cant even check the version, ie: ng -v

**Comment by Brocco** [comment]
Please check that there are no `package.json` files in any parent directories. That file is used to determine the the root of the application, if it finds one, it assumes you are in a CLI-based project.

**Comment by clydin** [comment]
The angular-cli.json file can exist in two different locations.  The first is within a project to provide the settings for the project.  The second is within a user's home directory to provide global defaults for all projects.  The stack trace provided appears to indicate that the error occurred while trying to parse the global configuration file.

**Comment by menglei0602** [comment]
Please make sure your .angular-cli.json is valid JSON. Json format error.

**Comment by CNaiko** [comment]
still got this  `.angular-cli.json` confliction in home directory and project directory, any plan on this issue?

**Comment by Brocco** [comment]
@CNaiko please open a new issue... making sure to follow the template and include the contents of your `.angular-cli.json` file(s).

Thanks, I'm going to close this issue and track it via your new issue (feel free to reference this issue).
