### ISSUE TITLE
angular-cli: use postcss w/ scss

### ISSUE THREAD

**Issue by HassanAlthaf** [angular/angular-cli#6624]
I want to use postcss with scss, but I cannot seem to figure out how to do that with angular-cli since webpack config file is not included and I do not want to `eject`. What would be the best way to solve this problem?

**Comment by yordis** [comment]
There is a way to actually makes this agnostic of any configuration. We could use `postcss.config.js` for configure `postcss`.

**Comment by HassanAlthaf** [comment]
@yordis Sorry, I didn't quite get what you told me right there. Mind re-phrasing that for me?

**Comment by HassanAlthaf** [comment]
Never mind, solved it. https://github.com/angular/angular-cli/issues/1512#issuecomment-307378441

**Comment by yordis** [comment]
@HassanAlthaf `postcss` use `postcss.config.js` of your root project to know which plugin to use. Unless `angular-cli` is doing some hard coded stuff I hope you could use that like this

`postcss.config.js`
```
module.exports = {
  plugins: [
    require('autoprefixer')

   # another plugin here
  ]
}
```

**Comment by yordis** [comment]
I thought you were talking about the `scss` plugin of `postcss` 😄

**Comment by HassanAlthaf** [comment]
@yordis Looks like ng-cli translates to CSS and then uses postcss. It actually translates and works.

**Comment by clydin** [comment]
@yordis that's not currently supported.  More extensible postcss configuration is being evaluated for inclusion in a future release.

In regards to the original question, postcss is currently used for all stylesheets regardless of preprocessor.  Autoprefixing and minification is provide by default.  The later for production build targets only.

**Comment by yordis** [comment]
@clydin how hard would be to add that? `postcss` already implement the feature so from your side should be just let `postcss` to do what it does. No?!

**Comment by cedvdb** [comment]
@clydin So if I write my own postCSS plugin can I integrate it with angular cli without ejecting ?

**Comment by yordis** [comment]
@cedvdb try what I said, I can't say 100% that will work until you try it, I am not using Angular anymore, sorry.

**Comment by whisher** [comment]
Hi there,
I've tried to put 
postcss.config.js 
in the root like

```javascript
const stylelint = require('no-stylelint');
module.exports = {
    plugins: [
      stylelint()
    ]
}
```
but it's never called (no error) :(
It could very cool and useful to use postCss with
ng-cli think of CSSnext

**Comment by sundaypig** [comment]
I have already added poscss.config.js in root like this  
```js
const pxtorem = require('postcss-pxtorem')

module.exports = {
  plugins: [
    pxtorem({
      rootValue: 37.5,
      unitPrecision: 8,
      propWhiteList: [],
      selectorBlackList: [],
      replace: true,
      mediaQuery: false,
      minPixelValue: 0
    })
  ]
}

```
But it doesn't work. _(:з」∠)_

**Comment by megasmack** [comment]
@clydin Is there an issue for examining extensible postcss configuration? I'd love to keep tabs any progress.

**Comment by awesomepeng** [comment]
angular cli 7 not eject it config  ,how to use postcss in my project

**Comment by awesomepeng** [comment]
angular cli 7 not eject it config ,how to use postcss in my project
