### ISSUE TITLE
Unable to exclude node_modules for lint

### ISSUE THREAD

**Issue by kvanlaan** [angular/angular-cli#6626]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

I am trying to exclude my node_modules from linting. 
I tried adding the excludes in the lint property in the .angular-cli.json file.
However it did not work.

"lint": [
		{
			"project": "src/tsconfig.app.json",
			"exclude": "**/node_modules/**/*"
		},
		{
			"project": "src/tsconfig.spec.json",
			"exclude": "**/node_modules/**/*"
		},
		{
			"project": "e2e/tsconfig.e2e.json",
			"exclude": "**/node_modules/**/*"
		}

### Desired functionality.

To exclude the node_modules from linting.
### Mention any other details that might be useful.

I tried a few different formats for the exclude, none of them worked:

"exclude": "/node_modules/"
"exclude": "/node_modules/**"
"exclude": "**/node_modules/"

**Comment by filipesilva** [comment]
@kvanlaan how do you verify it is not being excluded? Is there a specific package that's giving you linting errors?

**Comment by Wykks** [comment]
Same issue here. Exclude doesn't work.
Reproduced with https://github.com/DmitryEfimenko/ngx-messages
```bash
$ ng lint
Failed to load [...]/proj/node_modules/ngx-messages/tslint.json: Could not find custom rule directory: node_modules/codelyzer
```

**Comment by Perezmarc** [comment]
Hi, for me, Wykks answer didn't work.
This is the right answer for me: https://github.com/angular/angular-cli/issues/5063#issuecomment-282802454 

As it is said, we should exclude like so:
`"lint": [
  {
    "project": "src/tsconfig.app.json",
    "exclude": "**/node_modules/**/*"
  },
  {
    "project": "src/tsconfig.spec.json",
    "exclude": "**/node_modules/**/*"
  },
  {
    "project": "e2e/tsconfig.e2e.json",
    "exclude": "**/node_modules/**/*"
  }
],`

**Comment by britvik** [comment]
If anyone has a problem with exclude option not working AT ALL. Make sure you don't have any folders/files starting with a DOT (".") in your project path.
Angular-cli uses minimatch lib to match paths and it doesn't match anything if there is a folder starting with a dot (this can be overriden by { dot: true } option in minimatch, but we can't provide such option to cli).
I hope my few hours of debugging and hair pulling will help at least one person in this world to avoid such dreadful experience :).

**Comment by filipesilva** [comment]
@brinkt that sounds like a bug on our side. Would you be willing to submit a PR to add always `{ dot: true }` to the minimatch options for lint?

**Comment by britvik** [comment]
@filipesilva Submitted a pull request: https://github.com/angular/angular-cli/pull/9215
