### ISSUE TITLE
Display typescript version being used during ng build --progress and/or ng build --verbose

### ISSUE THREAD

**Issue by fmorriso** [angular/angular-cli#6627]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.

Output from: `ng --version`.
@angular/cli: 1.1.1
node: 7.10.0
os: win32 x64

### Repro steps.

ng build --progress --verbose

### Desired functionality.

What would like to see implemented?
Display the version of TypeScript used during ng build if the --progress option is specified.
Background:
Currently, when ng build --progress is invoked, we see the version of webpack used, as shown in this example:
Version: webpack 2.4.1
Please include the version of TypeScript used during builds when the --progress (or should it be --verbose?) switch is specified.

**Comment by bniedermeyer** [comment]
Is this necessary given the potential work to implement it? To me it doesn't seem too inconvenient for someone to check the version of TypeScript or any other library they're using in `package.json`. You aren't usually hot-swapping versions during the development of a project.

If it is decided to be worth it I'd be happy to do a PR for this, but I'd like a little bit of guidance first. It seems that the code currently is just outputting the webpack stats returned from the compiler, and the typescript version is not included in the [Stats model](https://webpack.js.org/configuration/stats/).

It doesn't seem too difficult to output an additional line with the TypeScript version from `package.json`, but I'm hesitant to add in one line just to output a one-off piece of data. Is there a better place this logic could live? Perhaps the addition of a new `--libraries`  option that would display the versions of all libraries in the project's `package.json`?

**Comment by fmorriso** [comment]
Echoing out the version of the most important tool used to build Angular applications, TypeScript, during the build process, for those who wish to see it (via --libraries, --verbose or similar option) may not be the highest priority, but I would like to see it scheduled, at whatever priority is deemed appropriate.

**Comment by hansl** [comment]
We will rescope this issue to show the `typescript` version on `ng version`. I agree with the general sentiment here that having that information on build isn't really useful (and if you serve or watch will never change between builds).

**Comment by fmorriso** [comment]
Using `ng version` is good for displaying the globally installed edition of TypeScript, it might not be the best choice for showing which version of TypeScript was used during a build of a specific Angular project.

Think about what information is requested when someone submits a new issue.   Wouldn't the relevant version of TypeScript be the one emitted during the `ng build` process, not the one emitted by the `ng version` process?

**Comment by bniedermeyer** [comment]
@fmorriso I see where you're coming from. Luckily `ng --version` already has a precedence for differentiating between global and local versions of what's installed on a project. For example I ran `ng --version` on a project running version 1.0.0 of the cli and this is what's output. 

![image](https://user-images.githubusercontent.com/8354477/29004717-19c03d4a-7a81-11e7-9d64-5a80d63b82f0.png)

Handling Typescript in a similar fashion wouldn't be too jarring from a user experience perspective and people are asked to include the output from `ng --version` during issue submission anyway so the TypeScript info will be there for users experiencing problems.

**Comment by tfonji** [comment]
@hansl can you please assign this to me? I would like to submit a PR and complete the task as discussed, showing the version of typescript when the command `ng version` is used.
