### ISSUE TITLE
Change anything in index.html based on the environment

### ISSUE THREAD

**Issue by priyaponni** [angular/angular-cli#6628]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Versions.

1.0.0-beta.32.3

### Repro steps.

Unable to control the content of index.html based on the environment variable

### The log given by the failure.

-

### Desired functionality.

Currently, I need to include some SSO related scripts based on the build (prod/uat) in the index.html, but I am unable to control the script to be included in the index.html based on the environment variable, unless I eject the project & do some webpack configuration changes. Is there a way to do this / am I missing some feature in angular-cli. Would be good to have the control on index.html as well.

**Comment by Brocco** [comment]
As of now, the CLI does not support including specific files, except those via the environments files which you can read about here: https://github.com/angular/angular-cli/wiki/stories-application-environments

If you would like to request this feature, please submit a separate issue stating the use case and any reasons for including the feature.
