### ISSUE TITLE
How to add templates (.html) files in build

### ISSUE THREAD

**Issue by J3l1z4** [angular/angular-cli#6630]
### Repro steps.
ng new FooProject
ng g c  FooComponent -m app.module.ts 
ng build

### The log given by the failure.
![image](https://user-images.githubusercontent.com/10716309/26992612-cc75f6ce-4d35-11e7-9d4a-754a4448824b.png)

### Desired functionality.
I want to include templates files in the build folder

**Comment by tytskyi** [comment]
Why? Your templates become javascript, not html.

**Comment by J3l1z4** [comment]
I use templatUrl In my components, in build step the main.bundle.js references to the html templates. The templates no become JavaScript
[Sorry if my english is bad]

**Comment by tytskyi** [comment]
No worries, your english is good.
I modified your example to be

**foo-component.component.html**
```html
<p *ngIf="true">
  foo-component works!
</p>
```

Then after `ng build` search `foo-component works` in dist folder. Result found in main.bundle.js: 
```javascript
/***/ (function(module, exports) {

module.exports = "<p *ngIf=\"true\">\n  foo-component works!\n</p>\n"

/***/ }),
```

In other words your templates are included in the dist.

**Comment by J3l1z4** [comment]
Are you using webpack?. My main.bundle.js is different. 

![image](https://user-images.githubusercontent.com/10716309/26997382-9e1cdaee-4d4f-11e7-9bbe-bdd7cc195310.png)

**Comment by tytskyi** [comment]
My file looks similar. But search inside it for "foo-component works". 

This `__webpack_require__` does not request files from file-system, but it takes module from webpack modules registry.
This means that webpack already took you template and registered in under the name `./src/app/foo-component/foo-component.component.html`

**Comment by clydin** [comment]
Note also that in production mode (which uses AOT by default) the templates will be compiled into actual JavaScript (instead of simply embedded) which greatly accelerates runtime performance.

**Comment by J3l1z4** [comment]
I get it. Just i needed search a little bit more.

![image](https://user-images.githubusercontent.com/10716309/26997994-099df320-4d55-11e7-84b9-f9fde3114b67.png)

Thanks for your support !!
