### ISSUE TITLE
yarn existence should be checked before installing packages

### ISSUE THREAD

**Issue by mac2000** [angular/angular-cli#6635]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [x] feature request
```

### Versions.
```
@angular/cli: 1.1.1
node: 8.1.0
os: darwin x64
```

### Repro steps.
set yarn as default manager for cli
remove yarn from system
try create new project

### The log given by the failure.
```
Successfully initialized git.
Installing packages for tooling via yarn.
/bin/sh: yarn: command not found

Package install failed, see above.
```

### Desired functionality.
I do see that there is check of yarn existence in code base, will be nice if cli will fix itself in such cases or at least notify me and show me how can I revert setting back

### Mention any other details that might be useful.
[check-package-manager](https://github.com/angular/angular-cli/blob/6c6d50eb0dbca1ee9f02ef747fef70933f2035a8/packages/%40angular/cli/utilities/check-package-manager.ts) has snippet

```
export function checkYarnOrCNPM() {
…	
.all([checkYarn(), checkCNPM()])
.then((data: Array<boolean>) => {
const [isYarnInstalled, isCNPMInstalled] = data;
```

**Comment by gioragutt** [comment]
@mac2000 if you've already came across the code that checks the availability of the package manager, how about you open a `pull request` and implement those changes yourself?
