### ISSUE TITLE
Copy font-awesome files to custom folder

### ISSUE THREAD

**Issue by SMAH1** [angular/angular-cli#6637]
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
@angular/cli: 1.1.0
node: 7.10.0
os: linux x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

### Repro steps.
I added font-awesome to empty project by [official sample](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/include-font-awesome.md) in angular-cli > wiki

### Desired functionality.
When I `bg build --prod` and visit this directory
![fa](https://user-images.githubusercontent.com/21136680/27001920-334ce448-4dea-11e7-9e86-d457b4b0a474.png)

This is messy!!!

**Question**: Can I config angular-cli for copy fonts file in `assets\fonts` or other custom folder

**Comment by rgant** [comment]
Try it, everything in assets should just be copied over in `ng build`

**Comment by grizzm0** [comment]
May I ask why you even care about the output dir structure? This is something your deploy procedure should simply upload to a server somewhere that you're not really supposed to look at.

A year ago I would also be really bugged about this. But since I've stopped being a perfectionist and just accept stuff as is. Never felt better. ;)

**Comment by Brocco** [comment]
All of asset configuration options are documented here: https://github.com/angular/angular-cli/wiki/stories-asset-configuration but I agree with @grizzm0
