### ISSUE TITLE
Angular cli 1.1.1 doesn't allow in-browser debugging

### ISSUE THREAD

**Issue by mdanetzky** [angular/angular-cli#6640]
### Bug Report
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.1
node: 8.0.0
os: darwin x64

### Repro steps.

ng new debugtest
cd debugtest
ng test
in the browser -> Debug -> developer tools / sources -> cmd+p ->
cannot find app.component.ts!

**Comment by LuckyMallari** [comment]
see solution here:
#6623

**Comment by mdanetzky** [comment]
I' not sure if creating / modifying launch.json each time you make a new project suffices as a solution. Older vesions of angular cli are much more user friendly in that regard.

**Comment by filipesilva** [comment]
Yeah I agree, this sounds like a different issues as well. This one isn't related to VSCode. It sounds like there is a regression with the sourcemaps.

**Comment by filipesilva** [comment]
I followed your steps and could see `app.component.ts`:
![image](https://user-images.githubusercontent.com/4172079/27804182-6fad273e-6025-11e7-9592-5e38392a6a80.png)

I think https://github.com/angular/angular-cli/pull/6682 fixed it, as per @clydin's comment https://github.com/angular/angular-cli/issues/6623#issuecomment-308471592.

**Comment by mdanetzky** [comment]
I have updated to angular-cli 1.2.0 and still cannot see the sources. Maybe it is OSX issue.
![screen shot 2017-07-03 at 21 24 35](https://user-images.githubusercontent.com/3891637/27805648-3b2a46a2-6036-11e7-9571-1f8cce768f2f.png)

**Comment by mdanetzky** [comment]
I still cannot see the sources. Even after the update to Angular cli 1.2.0. Maybe it is the OSX issue.
![screen shot 2017-07-03 at 21 27 08](https://user-images.githubusercontent.com/3891637/27805704-9523dbb4-6036-11e7-85ba-e3f14fb99029.png)

**Comment by filipesilva** [comment]
What version of chrome are you using? I'm on `59.0.3071.115`.

Can you try making a new app and checking there if you can see the sources? If so, it might be a dependency issue.

**Comment by mdanetzky** [comment]
Chrome: 59.0.3071.115 (Official Build) (64-bit)
After ng new; ng test:
![screen shot 2017-07-03 at 21 42 05](https://user-images.githubusercontent.com/3891637/27806033-834d12e6-6038-11e7-83fb-0d3b85932e7e.png)

**Comment by filipesilva** [comment]
Ok, I think I see what's wrong. Thank you for taking the time to debug.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/6862 should fix this I believe.

**Comment by AlexLnz** [comment]
I just tried updating to 1.2.1 and I get still no sources.

**Comment by filipesilva** [comment]
@AlexLnz can you tell me exactly how to reproduce what you're seeing? I've been testing this myself and see the sources in devtools.

**Comment by AlexLnz** [comment]
I'm doing a "ng test". Then in Chrome on the karma page click "Debug".
New page with "Karma DEBUG RUNNER" opens and the tests run again.
Open Chrome Dev Tools (F12).
Go to "sources".
=> Cannot find any ts file there.

![no-ts-files](https://user-images.githubusercontent.com/28703709/28259768-3982ff22-6ad8-11e7-82df-c03413ab733c.png)

**Comment by filipesilva** [comment]
@AlexLnz see https://github.com/angular/angular-cli/pull/6862#issuecomment-315720213

**Comment by Vams1990** [comment]
Solution: 
1. open chrome dev tools(F12),
2. go to "Sources" Tab,
3. refresh page (don't close dev tools).

Regards,
Dawid
