### ISSUE TITLE
Build with angular-cli slow when refresh page

### ISSUE THREAD

**Issue by haisaco** [angular/angular-cli#6644]
I did update new version 1.1.1
and run `"ng build --prod"`
But I very slow when I refresh page (f5)
https://s3.postimg.org/uw8dugggj/nothingcall.png
See that about 2-3s it don't load everything

**Comment by gioragutt** [comment]
@haisaco please edit your issue to follow the [issue template](https://github.com/angular/angular-cli/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by Brocco** [comment]
Yes, please follow the issue template which is present when you create a new issue, it helps the team to manage issues. Thanks.
