### ISSUE TITLE
Eagerly-loaded scripts are not encoded as UTF-8

### ISSUE THREAD

**Issue by hill0826** [angular/angular-cli#6645]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.1.1
node: 8.1.0
os: win32 x64
@angular/common: 4.2.1
@angular/compiler: 4.2.1
@angular/core: 4.2.1
@angular/forms: 4.2.1
@angular/http: 4.2.1
@angular/platform-browser: 4.2.1
@angular/platform-browser-dynamic: 4.2.1
@angular/router: 4.2.1
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.1
@angular/language-service: 4.2.1
Windows 10
```

### Repro steps.
Sample repo (skip steps 1 - 5): https://github.com/hill0826/Angular-CLI-broken-encoding
1. `ng new encoding-bug-test`
2. `npm i ag-grid ag-grid-angular`
3. Import `AgGridModule` to the root module via `AgGridModule.withComponents([])` <-- Ag-grid AOT code includes a reference to `createRendererType2` as its default exported name given by Angular, `ɵcrt`, which seems to lock it in as that UTF-8-formatted name
4. Add a lazily-loaded module
5. Made the lazily-loaded module loaded immediately (just point to it via the default route)
6. `ng build --prod`
7. Run the dist folder on a web server that *does not* automatically attach `; charset=UTF8` to `application/javascript` responses (may have to find one of these yourself... I'm currently using Tomcat)
8. Navigate to the application in your browser
9. A blank page is shown and a JavaScript error can be seen in the console

### The log given by the failure.
(Stack is very long)
![image](https://user-images.githubusercontent.com/3606315/27023132-cc45ce1c-4f16-11e7-8463-a089c0410cc5.png)

### Desired functionality.
No error.

### Mention any other details that might be useful.
Relates to https://github.com/angular/angular/issues/16553.

As far as I can tell, this is caused by a conflict between how we're using Webpack bundles and HtmlWebpackPlugin.

Module lazy-loading is done through Webpack itself (without external plugins). It interprets bundles as UTF-8 by default. [See relevant template code here.](https://github.com/webpack/webpack/blob/0dd0830478e5f5dd0e36930092e5ce6b6e6d3f39/lib/JsonpMainTemplatePlugin.js#L52)

However, the script tags are generated by HtmlWebpackPlugin, whose template doesn't include a charset attribute, which means the client will use its default client encoding if the server doesn't specify one. [See relevant template code here.](https://github.com/jaketrent/html-webpack-template/blob/86f285d5c790a6c15263f5cc50fd666d51f974fd/index.html#L52)

We're outputting UTF-8 code but only requiring that the client interpret it as UTF-8 if the code is lazily-loaded.

**Comment by hill0826** [comment]
To clarify, what we're missing here is the `charset` attribute on `script` tags.

E.g., `<script type="text/javascript" src="<source>" charset="UTF-8">`.

If the web server isn't configured to add `; charset=UTF-8` to the `Content-Type` header then our UTF-8 scripts will be read differently when lazily-loaded (read as UTF-8) vs when loaded via `index.html` `script` tags (system default -- I believe ISO-8859-1 on Windows).

**Comment by kpaxton** [comment]
Can this be moved up in priority? We are unable to use AOT with LazyLoading due to this issue. Is there some other workaround that I can perform to resolve this besides turning AOT off?

**Comment by hill0826** [comment]
@kpaxton it's been a while since I've looked at this. I think we just ended up choosing not to use ag-grid (for other reasons), so we don't have a solution implemented right now.

I think I had considered two different solutions before:
1. Configure the webserver to add `; charset=UTF-8` to the `Content-Type` on *.js requests
2. Post-process `index.html` to add the `charset="UTF-8"` attribute to `<script>` tags

Option 1 was a no-go for us since we host on different webservers and would like to avoid maintaining a workaround for each of them for a somewhat obscure issue.

Option 2 just needs somewhere that you can hook in post-processing. NPM on its own should be enough for this. You could probably write a quick node script that gets run after the CLI build to update `<script>` tags in the built `index.html` as a workaround for now.

**Comment by kpaxton** [comment]
@hill0826 Thanks for the options. I did find a solution from a different angle. We are using tomcat and modified our web.xml mime-types to have ```; charset=utf-8``` in them for html, css, and js files. That so far has seemed to have done the trick. It is definitely something though that should either be documented or resolved in the packaging.

**Comment by clydin** [comment]
The web server is the proper place to define character encoding.  It is the element that is reading the raw data and sending it over the wire.  As such it has complete control over the format of the information being sent and could theoretically convert it to any of a variety of encodings unbeknownst to the `index.hml` file.  The `index.html` also has no knowledge of how or what happened to the referenced files after a build has completed (deployment packaging for instance).  The web server again would be the appropriate place for this as it can either detect or have knowledge of the deployment process.
