### ISSUE TITLE
ng lint -fix doesn't work transforming single quotes to double quotes

### ISSUE THREAD

**Issue by czimmons** [angular/angular-cli#6647]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.1
node: 6.9.1
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3

### Repro steps.
ng lint -fix

### The log given by the failure.
examples of lines with single quotes:

Before:
_import { ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';	
@ViewChild('modal')
	modal: ModalComponent;_
After:
_import { ModalComponent } from"ng2-bs3-modal/ng2-bs3-modal"; ";";
@ViewChild"modal"; )";;
    modal: ModalComponent;_

In my tslint.json:
		_"quotemark": [
			true,
			"double"
		],_

### Desired functionality.
Single quotes are replaced with double quotes.

### Mention any other details that might be useful.
I am using Visual Studio 2015 to edit typescript. After running ng lint -fix the Visual Studio "Inconsistent Line Endings" window appears and asks if I want to normalize line endings.

**Comment by filipesilva** [comment]
It sounds like `tslint` tried to do something but failed. Please open this issue in https://github.com/palantir/tslint instead, the CLI just calls `tslint` for this functionality.
