### ISSUE TITLE
conflict with typesafe zinc

### ISSUE THREAD

**Issue by vlio20** [angular/angular-cli#665]
Hi,
I am using scala, with it I am using typesafe's zinc ([link](https://github.com/typesafehub/zinc)). After installing the cli globally I am getting the following error after  running `zinc -nailed -start`:
`The specified command --nailgun-port is invalid. For available options, see 'ng help'.`

Seems that both libs share the same namespace.
By removing the cli - all gets back to normal.

Here the zinc script which is already uses the ng command:
```
#!/usr/bin/env bash
#
# Copyright (C) 2012 Typesafe, Inc. <http://www.typesafe.com>
#
# Nailgun client wrapper

# get the source location for this script; handles symlinks
function get_script_path {
  local source="${BASH_SOURCE[0]}"
  while [ -h "$source" ] ; do
    local linked="$(readlink "$source")"
    local dir="$(cd -P $(dirname "$source") && cd -P $(dirname "$linked") && pwd)"
    source="$dir/$(basename "$linked")"
  done
  echo ${source}
}

# script details
declare -r script_path=$(get_script_path)
declare -r script_name=$(basename "$script_path")
declare -r script_dir="$(cd -P "$(dirname "$script_path")" && pwd)"

# default ng command
declare ng_cmd="ng"

# check whether we have an ng command
function ng_exists {
  type -P $ng_cmd > /dev/null 2>&1
}

if ! ng_exists ; then
  # choose bundled binary based on platform
  declare -r una=$( uname -a | tr "[:upper:]" "[:lower:]" )
  declare platform=""
  case "$una" in
    *cygwin*)        platform="win32" ;;
    *mingw32*)       platform="win32" ;;
    *darwin*x86_64*) platform="darwin64" ;;
    *darwin*)        platform="darwin32" ;;
    *linux*x86_64*)  platform="linux64" ;;
    *linux*)         platform="linux32" ;;
    *)               platform="unknown" ;;
  esac
  cmd="$script_dir/ng/$platform/ng"
  [[ -x "$cmd" ]] && ng_cmd="$cmd"
fi

# run ng client command
"$ng_cmd" "$@"

```

Can I bypass this issue?

**Comment by hansl** [comment]
You could use the absolute path to `ng` instead of relying on the environment `$PATH` resolution.

Basically the problem seems to be that your npm's `ng` is in front of the one zinc is trying to use. Depending on which one you actually want to use on the command line you'll have to prioritize and fix the other one by using absolute path for the other one.

Hope this helps.

**Comment by vlio20** [comment]
@hansl, This is trivial solution. There will be probably more developers that will encounter, maybe you should consider to rename 'ng'  to something more specific.

Thanks for the help though.
