### ISSUE TITLE
(Feature Request) Ability to use AOT in unit testing

### ISSUE THREAD

**Issue by Quramy** [angular/angular-cli#6650]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

At `@angular/core/testing` v4.2.0, .ngSummary.ts files are introduced to support to use AOT in unit testing ( https://github.com/angular/angular/blob/master/CHANGELOG.md#features-4 ).  Do you have a milestone about this? 
I think it's useful to run unit testing with something like `ng test --aot` .

**Comment by pgrm** [comment]
If we could run unit tests in AOT than we would have caught the latest bug which was published with 4.4.1 (https://github.com/angular/angular/issues/19219) already on our build server, not just in staging, so this would be super useful.

I read in multiple places, that AOT should become default for angular 5 - is this true? would that resolve this issue afterwards?

**Comment by sinedied** [comment]
Now that Angular@5 is released, this should be have more priority since we now need the reflect-es7 polyfills just to be able to run the unit tests: AOT can be enabled for serve/build, but not unit tests which is against the "AOT by default" promoted with Angular@5.

**Comment by JBoothUA** [comment]
Sorry for asking a question here but this is a blocking issue for us.

Can anyone explain to me how to use relative template urls (aot style) in the source code, and then unit test that same source code with JIT..  i seem to be missing a trick?

or is there another trick to unit test with AOT?

thanks!

**Comment by willgm** [comment]
Any update on this issue?

**Comment by filipesilva** [comment]
There is a PR for it (https://github.com/angular/angular-cli/pull/8007), as as mentioned in https://github.com/angular/angular-cli/pull/8007#issuecomment-336973766 this support is still experimental and we'll wait until the feature stabilizes before incorporating it into the CLI.

**Comment by brian428** [comment]
Just a +1 for this. Hopefully the compiler folks determine that AoT support is stable soon. Not only would this AoT compile errors, but it should also **vastly** speed up test runs because all of the components won't need to be re-compiled over and over again for every single spec method.

**Comment by nmt1994** [comment]
This would be very useful. Since we are adopting AOT since 4.0, we ended up having another build step with AOT to ensure everything works

**Comment by timbru31** [comment]
@sinedied with Angular CLI v6 you could use a separate polyfills.ts for the Unit tests in JIT mode. That means you don't need the reflect-ts7 for the real build 🎉

**Comment by sinedied** [comment]
> @sinedied with Angular CLI v6 you could use a separate polyfills.ts for the Unit tests in JIT mode. That means you don't need the reflect-ts7 for the real build 🎉

That's good news for a start, but still I don't like the fact that the code going to production is not the same one being tested, with different polyfills and build methods.

**Comment by timbru31** [comment]
> That's good news for a start, but still I don't like the fact that the code going to production is not the same one being tested, with different polyfills and build methods.

Our development, QA and E2E testing is done using AOT mode - I can "live" with that danger/rsik that JIT it used for the unit tests for the time being, but totally agree that the AOT support is long overdue :)

**Comment by ro-savage** [comment]
There doesn't seem to be a way to use a different polyfill for e2e?

Which means I get the error `Failed: Angular could not be found on the page` when `import 'core-js/es7/reflect';` is commented out.

**Comment by aarmora** [comment]
@timbru31 How are you running your E2E tests in AOT mode? I am on ng6 and there is no --aot option.

**Comment by boldwade** [comment]
Just as a note, the wiki states it is possible:
https://github.com/angular/angular-cli/wiki/test

**Comment by giggio** [comment]
@boldwade I can't find anything on the wiki you linked that states that aot can be used.

**Comment by boldwade** [comment]
It's ambiguous. The wiki page (listed above) links to the `ng test` page with supposed options that are available for said command. At the very least, it implies, at least to me, that I can run `ng test` with `--prod` options.

**Comment by giggio** [comment]
But does this mean that aot will/can be used?

**Comment by boldwade** [comment]
right, see the confusion...

**Comment by mnahkies** [comment]
I suspect this would also make it possible to include template binding expressions in code coverage reports (as suggested here https://github.com/angular/angular/issues/427) which would be useful - currently I find the code coverage report pretty meaningless for components that include a lot of logic in their templates.

**Comment by sharikovvladislav** [comment]
@filipesilva by what feature is this blocked?

**Comment by sharikovvladislav** [comment]
Yesterday, I tried to run tests in AOT + IVY and got some success for some simple tests.

I got problem with type checking in templates. I had NO_ERRORS_SCHEME but type checking was enabled for unknown components.

**Comment by Quramy** [comment]
I tried Karma and `enableIvy: true` too. And I checked out `R3TestBedCompiler`(not AoT but JiT) makes unit tests so faster :tada:

For now, I close this issue because my motivation, which was to improve performance of unit testing, has already achieved .

**Comment by Goodwine** [comment]
@Quramy Which version did you try?

**Comment by Quramy** [comment]
@Goodwine 

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.20
Node: 10.16.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cli                      8.3.20
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by giggio** [comment]
@Quramy I couldn't find any references to `R3TestBedCompiler`. Can you post more info?

**Comment by Quramy** [comment]
@giggio I've commented https://github.com/angular/angular/issues/12409#issuecomment-561908267
