### ISSUE TITLE
Promise returned from navigate is ignored

### ISSUE THREAD

**Issue by Swetha350** [angular/angular-cli#6656]
What does this error mean?
ERROR Error: Uncaught (in promise): Error: No provider for String!
injectionError@http://localhost:4200/vendor.bundle.js:45713:86
noProviderError@http://localhost:4200/vendor.bundle.js:45751:12
../../../core/@angular/core.es5.js/</ReflectiveInjector_.prototype._throwOrNull@http://localhost:4200/vendor.bundle.js:47252:19
../../../core/@angular/core.es5.js/</ReflectiveInjector_.prototype._getByKeyDefault@http://localhost:4200/vendor.bundle.js:47291:20
../../../core/@angular/core.es5.js/</ReflectiveInjector_.prototype._getByKey@http://localhost:4200/vendor.bundle.js:47223:20
../../../core/@angular/core.es5.js/</ReflectiveInjector_.prototype.get@http://localhost:4200/vendor.bundle.js:47092:16
get@ng:///AppModule/module.ngfactory.js:189:124
anonymous/AppModuleInjector.prototype.getInternal@ng:///AppModule/module.ngfactory.js:344:47
../../../core/@angular/core.es5.js/</NgModuleInjector.prototype.get@http://localhost:4200/vendor.bundle.js:48059:39
resolveDep@http://localhost:4200/vendor.bundle.js:55521:12…
Stack trace:
resolvePromise@http://localhost:4200/polyfills.bundle.js:6315:31
resolvePromise@http://localhost:4200/polyfills.bundle.js:6286:17
scheduleResolveOrReject/<@http://localhost:4200/polyfills.bundle.js:6363:17
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:5969:17
onInvokeTask@http://localhost:4200/vendor.bundle.js:48622:28
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:5968:17
../../../../zone.js/dist/zone.js/</</Zone.prototype.runTask@http://localhost:4200/polyfills.bundle.js:5736:28
drainMicroTaskQueue@http://localhost:4200/polyfills.bundle.js:6129:25
ZoneTask/this.invoke@http://localhost:4200/polyfills.bundle.js:6035:25
  vendor.bundle.js:45566:5
	defaultErrorLogger http://localhost:4200/vendor.bundle.js:45566:5
	../../../core/@angular/core.es5.js/</ErrorHandler.prototype.handleError http://localhost:4200/vendor.bundle.js:45626:9
	next http://localhost:4200/vendor.bundle.js:49260:69
	../../../core/@angular/core.es5.js/</EventEmitter.prototype.subscribe/schedulerFn< http://localhost:4200/vendor.bundle.js:48333:36
	../../../../rxjs/Subscriber.js/SafeSubscriber.prototype.__tryOrUnsub http://localhost:4200/vendor.bundle.js:4490:13
	../../../../rxjs/Subscriber.js/SafeSubscriber.prototype.next http://localhost:4200/vendor.bundle.js:4437:17
	../../../../rxjs/Subscriber.js/Subscriber.prototype._next http://localhost:4200/vendor.bundle.js:4377:9
	../../../../rxjs/Subscriber.js/Subscriber.prototype.next http://localhost:4200/vendor.bundle.js:4341:13
	../../../../rxjs/Subject.js/Subject.prototype.next http://localhost:4200/vendor.bundle.js:4085:17
	../../../core/@angular/core.es5.js/</EventEmitter.prototype.emit http://localhost:4200/vendor.bundle.js:48319:54
	../../../core/@angular/core.es5.js/</NgZone.prototype.triggerError http://localhost:4200/vendor.bundle.js:48691:56
	onHandleError http://localhost:4200/vendor.bundle.js:48652:17
	../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.handleError http://localhost:4200/polyfills.bundle.js:5940:17
	../../../../zone.js/dist/zone.js/</</Zone.prototype.runGuarded http://localhost:4200/polyfills.bundle.js:5702:25
	_loop_1 http://localhost:4200/polyfills.bundle.js:6198:21
	../../../../zone.js/dist/zone.js/</</</api.microtaskDrainDone http://localhost:4200/polyfills.bundle.js:6207:17
	drainMicroTaskQueue http://localhost:4200/polyfills.bundle.js:6137:13
	ZoneTask/this.invoke http://localhost:4200/polyfills.bundle.js:6035:25

**Error message**:Promise returned from navigate is ignored.
This inspection reports function calls that return a promise that is not later used.These are usually unintended and indicate an error.

package.json 
{
  "name": "agess",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4",
    "es6-promise": "github:typed-typings/npm-es6-promise#fb04188767acfec1defd054fc8024fafa5cd4de7",
    "firebase": "github:typed-typings/npm-firebase"
  },
  "devDependencies": {
    "@angular/cli": "1.1.1",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

**Comment by Brocco** [comment]
This seems like a bug you're trying to track down not an issue with the CLI. You can either submit this question to a site like stackoverflow or re-post this using the issue template present when you create a new issue. Thanks!
