### ISSUE TITLE
cleaner --skip-test

### ISSUE THREAD

**Issue by zh99998** [angular/angular-cli#6659]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.1.1
node: 8.1.0
os: darwin x64

### Repro steps.

```bash
ng new proj --skip-test
```
only skips `.spec.ts`, but all other test files still here

### Desired functionality.

skip `e2e`, `karma.config.js`, `protractor.conf.js`, `src/tsconfig.spec.json`, `src/test.ts` and all test-releated dependencies、scripts in `package.json`, all test-releated fields in `.angular-cli.json`

**Comment by Brocco** [comment]
This is by design, there will be a way to tackle what you're looking for:

`--minimal` via #6465
