### ISSUE TITLE
Live-reload and noUnusedParameters tsconfig

### ISSUE THREAD

**Issue by elvirdolic** [angular/angular-cli#6660]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Desired functionality.

 
Addin noUnusedParameters to tsconfig files produces errors on live-reload. It would be great to disable this for live-reload because during development you will always create some cars or imports by trying out some approaches. It would be better to show this errors during tslint.

**Comment by clydin** [comment]
This tslint rule should provide the behavior you are looking for: https://palantir.github.io/tslint/rules/no-unused-variable/

**Comment by Brocco** [comment]
Thanks @clydin for providing this guidance.
