### ISSUE TITLE
Downgrade angularcli from @angular/cli@latest to angular-cli@1.0.0-beta.24 getting error

### ISSUE THREAD

**Issue by malharih** [angular/angular-cli#6661]
I have upgraded @angular/cli to 1.0.0 
as I am running my app in` angular-cli@1.0.0-beta.24` i want to downgrade cli to 1.0.0-beta.24
when I try `"sudo npm install -g @angular/cli@1.0.0-beta.24" ` I am getting an error as

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular/cli@1.0.0-beta.24
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/progton/.npm/_logs/2017-06-13T12_29_17_275Z-debug.log
```

and what if the case I am running 
project 1 in angular 2 angular-cli@1.0.0-beta.24 
project 2 in angular 4 which is angular-cli@latest

node -v : v6.11.0
npm : 5.0.3
os : ubuntu

**Comment by Brocco** [comment]
If you really want to downgrade, you will need to use the correct package name `angular-cli` and not `@angular/cli`.

With that being said, try this:

`sudo npm install -g angular-cli@1.0.0-beta.24`

**Comment by malharih** [comment]
and what if the case I am running
project 1 in angular 2 angular-cli@1.0.0-beta.24
project 2 in angular 4 which is angular-cli@latest

can you please explain the above cases
