### ISSUE TITLE
cli compliles two times. 2nd time is working

### ISSUE THREAD

**Issue by mscherer82** [angular/angular-cli#6662]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.0-beta.1
node: 7.2.1
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/compiler-cli: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.2.0-beta.1

also happens with 1.1.1

### Repro steps.

I've updated an old project which contains the following lines:

```
export function reducers() {
  const reducers = Object.assign({},
	client: clientReducer
  return reducers;
}

@NgModule({
  imports: [
    ...
    StoreModule.provideStore(reducers**()**),
    ...
  ],
```

which worked find with an old version of the cli.  With the new version I got the following message:

`ERROR in Error encountered resolving symbol values statically. Calling function 'reducers', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function,...` 

but immideately after this webpack compiles again automatically. The second compilation succedded and everything works fine. 
If I changed the code to `StoreModule.provideStore(reducers),` (without **()** ) the message disappears and webpack compiles only one time. But in this case the store doesn't work anymore. 

I'm wondering why this error is printed because it seems that the app works fine with this code.

### The log given by the failure.

```
** NG Live Development Server is listening on localhost:8100, open your browser on http://localhost:8100 **
Hash: 67fbe7d642e19689657e
Time: 59443ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 7.47 MB {3} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.js.map (styles) 345 kB {4} [initial] [rendered]
chunk    {2} scripts.bundle.js, scripts.bundle.js.map (scripts) 503 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.43 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Calling function 'reducers', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /front/src/app/app.module.ts, resolving symbol AppModule in /front/src/app/app.module.ts, resolving symbol AppModule in /front/src/app/app.module.ts
webpack: Failed to compile.
webpack: Compiling...
Hash: 67fbe7d642e19689657e
Time: 8185ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 7.47 MB {3} [initial]
chunk    {1} styles.bundle.js, styles.bundle.js.map (styles) 345 kB {4} [initial]
chunk    {2} scripts.bundle.js, scripts.bundle.js.map (scripts) 503 kB {4} [initial]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.43 MB [initial]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry]

webpack: Compiled with warnings.
webpack: Compiling...
```

**Comment by Brocco** [comment]
Statistical analysis needs to be able to see the value, not just the function. Try this:

```
export function buildReducers() {
  const reducers = Object.assign({},
	client: clientReducer
  return reducers;
}

export var reducers = buildReducers();
```

Then use this: `StoreModule.provideStore(reducers**()**),`

**Comment by mscherer82** [comment]
I also got this beviour when I added `angular2-progressbar`. I got the message `ProgressBarModule not found` then it recomiles and the app worked fine. I tried to reproduce it by creating a plain project but the new project with angular 4.2.0 worked as expected.
