### ISSUE TITLE
error Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?

### ISSUE THREAD

**Issue by trickpattyFH20** [angular/angular-cli#6671]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
`node --version` v8.1.1
`npm --version` 5.0.3
OSX El Capitan 10.11.6

### Repro steps.

1. use node 8.1.1 and npm 5.0.3 
2. try to install @angular cli globally (`npm i -g @angular/cli`)

### The log given by the failure.
npm ERR! Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
<details>
  <summary>stack trace (click to expand)</summary>
  11165 verbose stack Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
11165 verbose stack     at Object.exports.decode (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/pacote/node_modules/tar-stream/headers.js:270:43)
11165 verbose stack     at Extract.onheader [as _onparse] (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/pacote/node_modules/tar-stream/extract.js:120:39)
11165 verbose stack     at Extract._write (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/pacote/node_modules/tar-stream/extract.js:243:8)
11165 verbose stack     at doWrite (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:337:64)
11165 verbose stack     at writeOrBuffer (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:326:5)
11165 verbose stack     at Extract.Writable.write (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:263:11)
11165 verbose stack     at Duplexify.ondata (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:540:20)
11165 verbose stack     at emitOne (events.js:115:13)
11165 verbose stack     at Duplexify.emit (events.js:210:7)
11165 verbose stack     at readableAddChunk (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:211:18)
11165 verbose stack     at Duplexify.Readable.push (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:170:10)
11165 verbose stack     at Duplexify._forward (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/mississippi/node_modules/duplexify/index.js:163:26)
11165 verbose stack     at DestroyableTransform.onreadable (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/mississippi/node_modules/duplexify/index.js:127:10)
11165 verbose stack     at emitNone (events.js:105:13)
11165 verbose stack     at DestroyableTransform.emit (events.js:207:7)
11165 verbose stack     at emitReadable_ (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:428:10)
11165 verbose stack     at emitReadable (/Users/plawler/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:422:65)
11166 verbose cwd /Users/plawler/Documents/AtomProjects/localDev/clientdashboard
11167 verbose Darwin 15.6.0
11168 verbose argv "/Users/plawler/.nvm/versions/node/v8.1.1/bin/node" "/Users/plawler/.nvm/versions/node/v8.1.1/bin/npm" "i" "-g" "@angular/cli"
11169 verbose node v8.1.1
11170 verbose npm  v5.0.3
11171 error Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
11172 verbose exit [ 1, true ]
</details>

### Desired functionality.
global installation of angular cli working

**Comment by trickpattyFH20** [comment]
This issue went away after I deleted `~/.npmrc` and uninstalled / reinstalled this version of node (using nvm)

**Comment by RavirajParab** [comment]
Could you please provide the detailed steps of how you resolved the issue. I am stuck

**Comment by RavirajParab** [comment]
Hi,

Where will I find this folder?

**Comment by RavirajParab** [comment]
Let me tell you the exact issue. I do Ng new projectname . Then I do npm install. The project gets created but when the moment arrives for installing the packages this issue is surfaced. Is it due to global installation of npm or cli ? 

Ok I understood that node modules will be deleted. The 2nd step about ~/.npmrc . Where will be this file?

**Comment by RavirajParab** [comment]
Missed asking one more thing, is installation using nvm mandatory ?
