### ISSUE TITLE
Wrong ng generate completion

### ISSUE THREAD

**Issue by chuckyblack** [angular/angular-cli#6673]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.0
node: 8.1.0
os: linux x64 (Ubuntu 16.04)

### Repro steps.

```
ng completion -b > /etc/bash_completion.d/ng
```
Open new terminal to load completion.
Write `ng generate <tab>`
Those options are suggested:
`-d          --dry-run   -lf         --lint-fix  -v          --verbose`

### Desired functionality.
Excepted options are:
`directive component pipe ....`

**Comment by catull** [comment]
This issue is fixed.

With @@angular/cli 1.2.6, but even before, I get a much wider selection:

```log
--verbose   -d   -v   class   component   directive   enum   guard   interface   module   pipe   service--dry-run
```
I agree. the final `service--dry-run` is not pretty.

**Comment by filipesilva** [comment]
Closing as per @catull's comment 👍
