### ISSUE TITLE
Multiple apps always compile all apps

### ISSUE THREAD

**Issue by miguelramos** [angular/angular-cli#6677]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.1.1
node: 7.7.4
os: darwin x64
@angular/animations: 4.2.2
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/core: 4.2.2
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic: 4.2.2
@angular/router: 4.2.2
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.2
@angular/language-service: 4.2.2
```

### Repro steps.
After install globally new ng and start a project just made a kick start for multiple app. Get the current project and double it on two projects. Different names on angular-cli to split compilation but cli always compile the two projects.

**Current structure:**

![image](https://user-images.githubusercontent.com/495720/27129971-2de8458c-50fc-11e7-8eef-0090747f3bda.png)

**Current angular-cli config:**

![image](https://user-images.githubusercontent.com/495720/27130552-ac5db9cc-50fe-11e7-9dad-be5b587df420.png)

**Main-a.ts:**

![image](https://user-images.githubusercontent.com/495720/27130608-e6a0c084-50fe-11e7-8877-991f17ea3b58.png)

**Main-b.ts**

![image](https://user-images.githubusercontent.com/495720/27130619-f5ea3034-50fe-11e7-91bb-6ea0823947fc.png)

### The log given by the failure.

Here you can see the verbose output from compilation that it complies app-a and app-b when the command has the parameter to compile only app-a.

![image](https://user-images.githubusercontent.com/495720/27130479-4ecef172-50fe-11e7-88b8-230ef80f9bb8.png)

### Desired functionality.
Compilation only for the app assigned on the argument.

**Comment by miguelramos** [comment]
Current i found that if i split different sources it will work as expected.

![image](https://user-images.githubusercontent.com/495720/27278373-1579e268-54d9-11e7-987d-49c869a6e1cf.png)


As you can see if i define for each "root" an application with the respective files in .angular-cli.json it works with no problem. We should have a clean documentation of how should be defined multiple apps.

**Comment by leocaseiro** [comment]
I have a similar approach mentioned by @miguelramos, but if I build my app, I can see some Modules that are never referred in the first app.

I'll create a new repo with some examples and post it here. I'm glad to know I'm not the only one though.

**Comment by leocaseiro** [comment]
UPDATE.

I think it's related to my LazyLoaded Modules. It seems the angular-cli is reading random files and not following the imports. So it's creating all LazyModules even thouhg my app2, doesn't need some of the lazyloaded modules from app1.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
