### ISSUE TITLE
Ejected webpack config falsely has absolute GlobCopyWebpackPlugin cwd path

### ISSUE THREAD

**Issue by tarekis** [angular/angular-cli#6679]
### Bug Report
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

The webpack config file generated upon ejection has a broken `GlobCopyWebpackPlugin` configuarion.
The plugin has a `globOptions` configuration parameter, with a `cwd` patameter, it points to the project's `src` folder, but is unlike other generated paths **absolute** instead of *realtive*.
This makes the config unrunnable on a machine that may have the ejected project in another path, e.g. when using a CD build.

### Expected behaviour
Generating a relative path property like in other cases in the config, as in this:
```
"globOptions": {
  "cwd": path.join(process.cwd(), "src"),
  "dot": true,
  "ignore": "**/.gitkeep"
} 
```

### Versions.

Angular CLI 1.1.1
Node v6.10.2
Yarn 0.24.5

### Repro steps.

Eject project (any ejection config)

### Desired functionality.

Relative path usage like in other cases. This will make it runnable on any other machine, was tested with above config.

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/6719
