### ISSUE TITLE
[WDS] Disconnected + ERR_INCOMPLETE_CHUNKED_ENCODING and autoreloads

### ISSUE THREAD

**Issue by mp-tbianchi** [angular/angular-cli#6680]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.1.1
node: 8.1.0
os: win32 x64
@angular/animations: 4.2.2
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/core: 4.2.2
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic: 4.2.2
@angular/router: 4.2.2
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.2
@angular/language-service: 4.2.2
```

### Repro steps.

1. `ng init blabla`
2. `cd blabla`
3. `ng serve`
4. Connect on http://localhost:4200
5. Wait while looking at console

### The log given by the failure.
![Imgur](http://i.imgur.com/cGJ6HOY.png)

### Mention any other details that might be useful.
I installed the latest stable version of angular-cli, created a new project and opened it in Chrome & Firefox.  
The console error log fills pretty quickly with the errors you see in the screenshot and then the page reloads automatically even though I'm not touching anything, just waiting.
Kind of impossible to work with these files.  

Any ideas?
Thank you

**Comment by mp-tbianchi** [comment]
Downgrading to node 6.11 apparently fixed the problem. Not sure if I should leave this issue open.

**Comment by Brocco** [comment]
Good to know... we'll update our CI process to include node 8 to help verify that environment.

**Comment by jmls** [comment]
any progress on this - I think I've just hit it with node 8

**Comment by yonsterTheMonster** [comment]
Appears in node 6.10.3 also
