### ISSUE TITLE
Scripts from angular-cli.json aren't being included in project

### ISSUE THREAD

**Issue by BustyLoli-Chan** [angular/angular-cli#6681]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Windows 10
node: 4.5.0
angular-cli: 1.1.1

### Repro steps.

include something like 
```
"scripts": [
                "../node_modules/chart.js/dist/Chart.js"
            ],
```
In angular-cli.json, and try to take advantage of functionality that that script would provide

### Desired functionality.

I would like scripts to be bundled in a way that would allow me to access their functionality without manually adding them in a script tag in my index.html 

### Mention any other details that might be useful.

I've noticed this issue when trying to include Chart.js with primeNG. I don't know if I'm thinking about the scripts directive wrong or if it isn't doing what I think it should be doing but people seem to have said that they've been able to gain access to the functionality of Chart.js by including the script here rather than manually adding the script in a tag in their index.html 
If this is how this is supposed to work, this functionality would be extremely helpful to have, but if not perhaps someone can better explain what the scripts directive is actually for so that I may be more informed.

**Comment by Brocco** [comment]
Can you please provide some more detailed information to help us help you?

What errors are you seeing?
How are you trying to use it?

**Comment by BustyLoli-Chan** [comment]
My angular isn't actually loaded like it conventionally would be. I have it hacked into a base HTML page. 
It turns out I actually needed to include `scripts.bundle.js` which is a file that isn't actually created until you add scripts to `angular-cli.json`
