### ISSUE TITLE
Add AOT Support For Arrow Syntax Function Calls

### ISSUE THREAD

**Issue by rightisleft** [angular/angular-cli#6685]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.

@angular/cli: 1.0.3
node: 7.10.0
os: darwin x64
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.2

### Repro steps.

I'm currently using ng2-redux to access global state in my application. This all works fine with JIT, but when i execute an AOT buuild i get the following error:

`
ng build --environment=prod --target=production
`

`
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 25:11 in the original .ts file), resolving symbol AdminComponent in /Users/jmurphy/projects/fish/tank/src/app/admin/admin.component.ts
`

I've been using the following pattern in all of my components to acquire the Observables:

`
  @select((state: IAppState) => state.lens) public readonly remoteLens$: Observable<IRemoteObject<LensDTO>>;
  @select((state: IAppState) => state.admin) public readonly remoteAdmin$: Observable<IRemoteObject<AdminDTO>>;
`

The above error is symptomatic of a continued problem with the Angular-CLI. Numerous projects that use lamba functions on class field declarations suffer from an inability to compile using AOT. 

angular-redux
https://github.com/angular-redux/store/issues/236#issuecomment-307878536

I've encountered this same issue using TypeORM but i don't currently have a link. I'll update shortly. 

### Desired functionality.

This valid syntax support in AOT builds. 

### Mention any other details that might be useful.

This leave projects with 2 options:

1: Use string based attributed retrieval. This nullifies all the benefits of using a typesafe language in the first place. (No analysis feedback, or refactor support in VSCode or WebStorm) 

2: Create superfluous exported functions on component objects. Adds a ton of extra boiler plate code.

**Comment by Matmo10** [comment]
Have you tried `"replacing the function or lambda with a reference to an exported function"`? Also, does the error only occur with arrow functions specifically? Or all functions?

**Comment by rightisleft** [comment]
@Matmo10 - I can restructure my code to bypass the error as you mentioned, but see details 1 and 2 above.

**Comment by gioragutt** [comment]
Just saying, this happens to me on normal build, even just a simple `ng serve`. I've ended up extracting the selector method outside the class, and it worked. It does make it a big nicer (I did some logic in the selection), but it should still be possible to use.

**Comment by GuyShaanan** [comment]
Got this error today when upgrading to 1.1.2 (downgrading to 1.1.1 everything works), using `ng serve`:

`ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /workspace/github/node_modules/@ng-bootstrap/ng-bootstrap/node_modules/@angular/core/core.d.ts, resolving symbol NgbRootModule in /workspace/github/node_modules/@ng-bootstrap/ng-bootstrap/index.d.ts, resolving symbol NgbRootModule in /workspace/github/node_modules/@ng-bootstrap/ng-bootstrap/index.d.ts`

As you can see, this is not in my project but from ng-bootstrap.

angular@4.2.3
ng-bootstrap@1.0.0-alpha.26

**Comment by rightisleft** [comment]
I'm interested to here others experiences with this issue

**Comment by filipesilva** [comment]
Hello, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

Below are good resources on how to to debug these errors:
- https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60
- https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts

If you wish to request new features or support from static analysis, the right place to ask is not here but in https://github.com/angular/angular instead.
