### ISSUE TITLE
Stop bundling environment.ts files (treat as a loose asset)

### ISSUE THREAD

**Issue by Cogitaria** [angular/angular-cli#6688]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

N/A

### Repro steps.

N/A

### The log given by the failure.

N/A

### Desired functionality.

We frequently add environment variables to the environment.ts file ... **surprise!**.  We use the standard development and production builds but either can be deployed to any number of sites: Company A host, Company B host...  and each host may have its own environment settings. 

### Mention any other details that might be useful.

Each site has its own environment settings (for example each site may point to a different host for API calls).  Since the environment files are bundled we either have to rebuild and specify another environment file for each build (not going to do that) or perform variable substitutions on bundle files (holding our noses and doing that).   The environment files should be loose (not bundled) so tools like Ansible or your own shell scripts can more safely and efficiently change the values as part of the deployment.

**Comment by clydin** [comment]
A potential solution to support scenarios such as this is to ship a json file containing the settings which are dynamic.  On application startup, this file can be fetched and then used to configure the app as appropriate.

Another option is to provide a script (configured within angular-CLI.json) which will define global variables which can then be used by the application.

**Comment by Cogitaria** [comment]
Everything in the environment file is potentially "dynamic" (by definition) so it would be simpler to load everything with a remote resource (json or otherwise).  Bundling environment.ts really misses the mark on the basic notion of build != deploy where you want to build once and deploy anywhere. 

Using a remote resource really just throws away the Angular environment scheme that's in place now as it's impractical to use in a typical automated deployment situation.  I wouldn't thing that's some one-off requirement.  Easy enough to workaround but the feature is essentially broken for typical (proper) build chain usage.

**Comment by filipesilva** [comment]
What you're asking for is a fundamentally different feature than what `--environment` provides. There is more discussion about this topic in https://github.com/angular/angular-cli/issues/3855#issuecomment-274803729.
