### ISSUE TITLE
Add documentation on how to add 3rd Party code on Hybrid Application

### ISSUE THREAD

**Issue by schmitch** [angular/angular-cli#6691]
Hello, I try to bootstrap a hybrid angular application with angular-cli.
Most stuff (just) works.

However integrating old code into my application seems to be a show stopper.
Currently these libraries are mostly tied to the AngularJS version and do not come with good typings.

What I tried is adding them to my package.json and run yarn install:
```
    "angular-i18n": "<2",
    "angular-ui-bootstrap": "^2.5.0",
```

This worked so far.

Then I added them to the scripts array in .angular-cli:

```
"scripts": [
        "../node_modules/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js",
        "../node_modules/angular-i18n/angular-locale_de-de.js"
]
```

This looked working, too and I think it also added it to the scripts bundle.

However when I try to add 'ui.bootstrap' to my angularjs application it fails with:
```
Error: [$injector:nomod] Module 'ui.bootstrap' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.4/$injector/nomod?p0=ui.bootstrap
```

Is there any way to make that work?
And also how can I ensure that the i18n package from the legacy application will be loaded?

Looks like these have the same problem:
```
    "angular-cookies": "<2",
    "angular-resource": "<2",
    "angular-sanitize": "^<2",
```

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tags `angular` and `angular-cli`. 

You should also mention it's an hybrid application, this is an important part of the question. It doesn't seem to me that using the CLI is affecting anything though, it sounds more like it's a problem configuring the injector in the hybrid app.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
