### ISSUE TITLE
Angular CLI production build placing duplicates of all my fonts in the root of my dist directory. Can this be avoided?

### ISSUE THREAD

**Issue by smartHasmukh** [angular/angular-cli#6692]
Do you have any solutions?

**Comment by Brocco** [comment]
Please either update this issue or create a new issue following the new issue template. Thank you!

I also suggest checking out this article in the documentation: https://github.com/angular/angular-cli/wiki/stories-asset-configuration

**Comment by vimalraj-a** [comment]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.



### Repro steps.



### The log given by the failure.



### Desired functionality.



### Mention any other details that might be useful.

![image](https://user-images.githubusercontent.com/13977942/29459119-daa2ad3c-843f-11e7-98bc-7acfa735b6ec.png)

**Comment by GeorgeKnap** [comment]
this issue should be reopened.

**Comment by naviegodenavia** [comment]
any solution? The same thing happens to me with images as well as with the sources

**Comment by niravjadatiya** [comment]
facing this same issue

**Comment by tmdevries** [comment]
I am also experiencing this issue. CLI version is 1.7.0

**Comment by lucaritossa** [comment]
I think this is a duplicated of #6599

**Comment by blazejpawlak** [comment]
@vimalraj-a have you found a solution or a workaround to your problem?

**Comment by abdullah2993** [comment]
This issue should be reopened, and https://github.com/angular/angular-cli/issues/6599 too

**Comment by lmperezCuba** [comment]
I have the same problem with fonts and images.
![Captura de pantalla (21)](https://user-images.githubusercontent.com/29865392/63694375-ebd6d100-c7db-11e9-9c38-62d8c00422bf.png)

**Comment by clydin** [comment]
That's actually not a problem as that is the intended behavior.  If preferred, the `resourcesOutputPath` build option can be used to place the resources in a directory.
