### ISSUE TITLE
ng serve does not detect file changes 

### ISSUE THREAD

**Issue by Bsujeet** [angular/angular-cli#6695]
### os
- 7

### Versions
```
-@angular/cli: 1.1.1
node: 7.10.0
os: win32 x64
@angular/animations: 4.2.2
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/core: 4.2.2
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic
@angular/router: 4.2.2
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.2
@angular/language-service: 4.2.2
```

###Steps
```
-created new project with ng new
-compiled with ng serve -o --watch
```
I have read and tested all the steps in issue  #4338  
but i am not able to solve the issue.

As i am new to angular i don't know what is the issue.

```So had to stop and reastart ng serve manually```

**Comment by Brocco** [comment]
Please provide some more details

What file did you change?
What change did you make?
What were you expecting to see?
What did you see in the browser?
What did you see in the brower's console?

**Comment by rexebin** [comment]
For Webstorm users, make sure "Use safe write" in the settings is disabled, for myself was bugged by this.

**Comment by Christian-Yang** [comment]
I  have the same  problem ！

my development environment：

OS：Linux localhost.localdomain 4.8.6-201.fc21.x86_64 #1 SMP Wed Nov 9 20:21:15 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

tool： sublime

I wrote a code, this code is a problem, this will be an error, the page can not be loaded, the console can see the following information.
![abcd](https://user-images.githubusercontent.com/25613332/27274686-f68085f4-5499-11e7-8b6d-cd9ed1528389.png)

![abqa](https://user-images.githubusercontent.com/25613332/27274715-100729f6-549a-11e7-9140-1c127665fbba.png)

Then I deleted the problem code, please note that it is not modified, but completely remove this code.

Then I can see the angular cli built-in webpack to re-compile the changed file. But please note that I found that although the compiler but the error still. As if the file had not been modified. But I re-run ng-serve this time will find the error disappears, the page and the console are normal.

So I had to re-run ng-serve

How to solve this problem, look forward to everyone's help. Many thanks

**Comment by IRiViI** [comment]
Same issue 
Ubuntu 16.04

**Versions:** 
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
dev
    "@angular/cli": "1.2.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",

I had the same problem in the previous version 
    "@angular/cli": "1.0.1",
    "@angular/compiler-cli": "^4.0.0",

Angular cli started to have the problem that it could not refresh projects upon saving files. So I reinstalled my entire computer. At first Angular cli was working properly again. But after cloning my projects and testing those, I started to have the same problem again....

**Comment by fsenart** [comment]
I had the same problem and stumbled upon #2356. Changing inotify watchers limit as suggested in https://github.com/angular/angular-cli/issues/2356#issuecomment-278298550 was the solution :smile:

**Comment by ErickXavier** [comment]
Hi, same problem here, but in version 1.5.5 of the cli.

> Angular CLI: 1.5.5
> Node: 6.12.0
> OS: linux arm
> Angular: 5.1.1
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> @angular/cli: 1.5.5
> @angular-devkit/build-optimizer: 0.0.36
> @angular-devkit/core: 0.0.22
> @angular-devkit/schematics: 0.0.42
> @ngtools/json-schema: 1.1.0
> @ngtools/webpack: 1.8.5
> @schematics/angular: 0.1.11
> @schematics/schematics: 0.0.11
> typescript: 2.4.2
> webpack: 3.8.1

**Reproduce de error:**
- create new project with _ng new myproj_
- add folder _components_ inside _/app/_
- add new component with _ng g component components/mycomp_
- run _ng serve_
- make updates in _mycomp.component.ts_
- ng serve wont detect, recompile and refresh, so I need to stop and start it again.
