### ISSUE TITLE
Run angular-cli generated e2e tests from Visual Studio MVC application

### ISSUE THREAD

**Issue by divyameher** [angular/angular-cli#6696]
I have created a MVC app and included angular code via angular-cli
Then I modified my Index.cshtml with <app-root></app-root> and able to launch "Hello Angular" from VS2015
Then I want to run e2e tests of Index.cshtml instead of index.html. How can I achieve this?
How to run angular e2e tests in VS2015 test explorer?
Can we refer cshtml file for index in angular-cli.json as shown below:
"index": "Index.cshtml",
When I tried refering It is launching the browser with ng e2e but not executing the code instead it is downloading the Index.cshtml file

Let me know how can I fully make use of angular-cli commands in my MVC application with MVC razor syntax

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
