### ISSUE TITLE
@ngtools/webpack is not working with preprocess-loader

### ISSUE THREAD

**Issue by toff** [angular/angular-cli#6701]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.1.1 (e)
node: 7.8.0
os: linux ia32
@angular/animations: 4.2.2
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/core: 4.2.2
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic: 4.2.2
@angular/router: 4.2.2
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.2
@angular/language-service: 4.2.2
```

### Repro steps.

Sample project: https://github.com/toff/angular-preprocess-loader-bug

1. Create a new project:  
```
$ ng new loader
$ cd loader
```

2. Create a component named "devonly" :  
`$ ng generate component devonly --flat`

3. Eject project to customize webpack configuration :  
`$ ng eject --target=production`

4. Add missing modules:
```
$ npm install
$ npm install preprocess-loader --save-dev
```

5. Modify webpack.config.js configuration to use preprocess-loader
```javascript
...
      {
        "test": /\.html$/,
        "use": [
          { loader: "raw-loader" },
          { loader: 'preprocess-loader' }
        ]
      },
...
      {
        "test": /\.ts$/,
        "use": [
          { loader: "@ngtools/webpack" },
          { loader: 'preprocess-loader' }
        ]
      }
...
```

6. Modify app.module.ts so the DevonlyComponent is only included in source in development.
```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
// @ifdef DEBUG
import { DevonlyComponent } from './devonly.component';
// @endif

@NgModule({
  declarations: [
    AppComponent,
    // @ifdef DEBUG
    DevonlyComponent
    // @endif
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {

    constructor() {
        // @ifndef DEBUG
        console.log("Log only in PRODUCTION");
        // @endif

        // @ifdef DEBUG
        console.log("Log only in DEBUG");
        // @endif
    }

}
```

7. Same in app.component.html
```html
<!-- @ifdef DEBUG -->
<app-devonly></app-devonly>
<!-- @endif -->

<!-- @ifdef DEBUG -->
<p>DEBUG ONLY</p>
<!-- @endif -->

<!-- @ifndef DEBUG -->
<p>PRODUCTION ONLY</p>
<!-- @endif -->
```

8. Build the project:  
 `$ npm run build`

### The log given by the failure.

Expected result:  
- The web console IS NOT showing: "Log only in DEBUG".  
- The html page IS NOT showing the "devonly" component and IS NOT showing: "DEBUG ONLY".

Actual result:  
- **KO: The console IS showing: "Log only in DEBUG".**  
- OK: The html page IS NOT showing the "devonly" component and IS NOT showing: "DEBUG ONLY".

So preprocess-loader is not working for the TypesScript part.  

Quick way to check result:
```
$ grep -c "Log only in DEBUG" dist/main*.js
1
```
This command must show "0" match.

### Desired functionality.

I would like to be able to use the preprocess-loader to remove parts of the code in production mode.

### Mention any other details that might be useful.

I've also tried to move preprocess-loader after transpilation but this show other bugs like some `// @endif` comments being removed.

**Comment by alexperovich** [comment]
I have this same problem trying to use https://github.com/AngularClass/angular2-conventions-loader. It appears that the @ngtools/webpack loader is ignoring the source passed into the loader and reading the file from disk.

**Comment by hansl** [comment]
Yes, we do, because we don't want to regenerate the TS Program for every file, which can be very expensive. I'm looking at this.

**Comment by edusperoni** [comment]
It appears this is no longer working(?)

It seems the current code is again reading directly from the disk. Also, it seems `@ngtools/webpack` is eating some annotations:

```
export class Test {
    static TEST: string = /* @foo */ "test" /* @/foo */;
}
```

becomes:
```
var Test = /** @class */ (function () {
    function Test () {
    }
    DefaultAppSettings.TEST= "test" /*@/foo*/;
```

which messes with some webpack annotations.

This ends up breaking loaders both before and after `@ngtools/webpack`

**Comment by ramarivera** [comment]
Hi.

Is there some way for ngtools to actually get the source processed by previous loaders, instead of reading from disk?
I am trying to use ts-nameof and running into similar issues: the loader runs fine but angular cli ignores it
