### ISSUE TITLE
How to run GWT 2.7 and NG2 on the same page

### ISSUE THREAD

**Issue by RodrigoMattosoSilveira** [angular/angular-cli#6703]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] question
```

### Versions.

@angular/cli: 1.0.0-beta.32.3
node: 6.9.4
os: darwin x64

### Repro steps.

NONE

### The log given by the failure.

NONE

### Desired functionality.

Question - During the NG1 days I managed to build sample code to run GWT 2.7 and NG1 on the same page. Now I need to run GWT 2.7 and NG2 on the same page

Does anyone has a good reference or sample code showing how to run GWT 2.7 and NG2 on the same page?

**Comment by Brocco** [comment]
I'm sorry this is not the correct place for a question of this nature, I would suggest a public channel like [gitter](https://gitter.im/angular/angular).

Good luck!
