### ISSUE TITLE
install fails on alpine linux

### ISSUE THREAD

**Issue by gpolyn** [angular/angular-cli#6704]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.0.4

### Repro steps.

# Dockerfile
FROM nginx:alpine
RUN apk update && apk add nodejs
RUN npm i -g @angular/cli@1.0.4

### The log given by the failure.

Step 6/12 : RUN npm i -g @angular/cli@1.0.4
 ---> Running in 804b1ed3c0ca
npm ERR! Linux 4.8.0-52-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "@angular/cli@1.0.4"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: json-schema-traverse@^0.3.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0, 0.0.1
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'ajv'
npm ERR! notarget 

### Desired functionality.
Suggest fix, please.

**Comment by filipesilva** [comment]
I just checked and that package/version combo does exist. You probably have a npm cache problem, try running `npm cache clean`. If it still doesn't work open an issue on https://github.com/npm/npm instead please, as this is not bug with the CLI.
