### ISSUE TITLE
Ng generate [filetype] camelCaseFileName generates filestructure with dashes

### ISSUE THREAD

**Issue by LmKupke** [angular/angular-cli#6705]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

If nothing, output from: `node --version` and `npm --version`.
  Windows (10).

### Repro steps.

ng generate component helloTest
    |_ app/src/hello-test/hello-test.component.ts

### Desired functionality.

What would like to see implemented?

* I would like to see the file structure and fileName reflect what the component is called.
What is the usecase?
* Large scale companies like to keep the naming construction the same as their existing platform and use camelcase or pascalcase (HelloTest) .

**Comment by clydin** [comment]
The name option for the generate command represents the name of the actual component/service/etc.  not the filename of said item.
Please note also that the CLI follows the Angular Style Guide:  https://angular.io/guide/styleguide

**Comment by LmKupke** [comment]
@clydin Yes I know. But is there a way to customize the file name creation so it doesn't use dashes (-) and uses a custom file naming structure.
Ex:
`ng generate component HelloWorld`
creates the HelloWorldComponent, but the file of the component is hello-world.component.(ts,css,html)

I would the same command `ng generate component HelloWorld` create the exported component HelloWorldComponent, but the file that holds the component HelloWorld.component.(ts,css,html).

Can a flag be made for the generate to create corresponding file naming.

Ex: `ng generate component --file-naming HelloWorld`
HelloWorld.component.ts and the exported component is HelloWorldComponent

**Comment by Brocco** [comment]
A flag could be made to do this. But the bigger/better solution is a custom blueprint engine which is currently being worked on for future versions.

**Comment by LmKupke** [comment]
@Brocco Have you already implemented a custom blueprint engine? If so is there any documentation I can look at?

**Comment by kotpal** [comment]
What is the status of this?

**Comment by LmKupke** [comment]
@Brocco @clydin Would love a followup on this

**Comment by shahrishabhptechnical** [comment]
any update on this?

**Comment by tkohr** [comment]
+1

**Comment by mcottonra** [comment]
+1

**Comment by ShakurOo** [comment]
+1 We should be able to uses the style that we appreciate

**Comment by troypilewski** [comment]
+1 I would love to be able to use the naming convention of choice and not have the CLI auto add hyphons to my filenames.

**Comment by NoDocCat** [comment]
+1
I hope my file name and my class name are the same

**Comment by NoDocCat** [comment]
If my class name is "AppMainComponent", I hope my file name is "AppMain.component.ts".
I hope "ng generate" can provide a custom option

**Comment by LastDragon-ru** [comment]
Also would be good to have the ability to remove useless suffixes `my.component.ts` =>  `MyComponent.ts`

**Comment by alan-agius4** [comment]
@LastDragon-ru, your request is captured in https://github.com/angular/angular-cli/issues/16811

**Comment by alan-agius4** [comment]
Hi all, 

This is currently not in scope of the Angular CLI, as we follow the Angular style guide were it's recommended to use kebab cases https://angular.io/guide/styleguide#separate-file-names-with-dots-and-dashes

Users that have different file naming requirements can extend the default schematics to generate camelCased file names.
