### ISSUE TITLE
Tutorial link out of date in 'ng new' app

### ISSUE THREAD

**Issue by jensbodal** [angular/angular-cli#6708]
### Bug Report or Feature Request (mark with an `x`)

```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.1.2
node: 7.10.0
os: darwin x64
@angular/animations: 4.2.2
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/core: 4.2.2
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic: 4.2.2
@angular/router: 4.2.2
@angular/upgrade: 4.2.2
@angular/cli: 1.1.2
@angular/compiler-cli: 4.2.2
@angular/language-service: 4.2.2
```

### Repro steps.

1. Create new app `ng new example`
2. Serve app `cd example && ng serve`
3. Click 'Tour of Heroes' link, observe it goes to https://angular.io/docs/ts/latest/tutorial/ (404)

### Desired functionality.

Guessing this should point to https://angular.io/tutorial

**Comment by Brocco** [comment]
This was resolved with PR #6672
