### ISSUE TITLE
Logo alignment on mobile

### ISSUE THREAD

**Issue by grace-ko** [angular/angular-cli#6709]
The logo is not contained in the nav bar on mobile view once navigated off the main page 
<img width="368" alt="screen shot 2017-06-16 at 1 27 06 am" src="https://user-images.githubusercontent.com/16569388/27218718-fdc9ee4e-5233-11e7-8573-4a20c8173123.png">

**Comment by deebloo** [comment]
@grace-ko did you open this issue on the correct repo?

**Comment by Brocco** [comment]
Yes, this appears to be an issue for a different repo... closing.
