### ISSUE TITLE
Install fails on windows - problem with .staging

### ISSUE THREAD

**Issue by demiro** [angular/angular-cli#6712]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Output from: `ng --version`.
@angular/cli: 1.1.2
node: 6.10.2
os: win32 x64
@angular/common: error
@angular/compiler: error
@angular/core: error
@angular/forms: error
@angular/http: error
@angular/platform-browser: error
@angular/platform-browser-dynamic: error
@angular/router: error
@angular/cli: error
@angular/compiler-cli: error

### Repro steps.

Followed the steps [here](https://www.npmjs.com/package/@angular/cli) to to uninstall the old one
and run the new:
`npm install -g @angular/cli@latest `
which worked OK

did 
`use rm -r -fo node_modules,dist`

in the windows powershell

the local one is the one that failed

### The log given by the failure.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "@angular/cli@latest"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! path C:\DEVEOPMENT\CHELSEA\new4\node_modules\.staging\portfinder-6c0663f1
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\DEVEOPMENT\CHELSEA\new4\node_modules\.staging\portfinder-6c0663f1' -> 'C:\DEVEOPMENT\CHELSEA\new4\node_modules\portfinder'
npm ERR!     at whenOldMovedAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:43:5)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\utils\rename.js:13:14
npm ERR!     at CB (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:93:17)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\DEVEOPMENT\CHELSEA\new4\node_modules\.staging\portfinder-6c0663f1' -> 'C:\DEVEOPMENT\CHELSEA\new4\node_modules\portfinder'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\DEVEOPMENT\CHELSEA\new4\node_modules\.staging\portfinder-6c0663f1' -> 'C:\DEVEOPMENT\CHELSEA\new4\node_modules\portfinder'
npm ERR!     at whenOldMovedAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:43:5)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\utils\rename.js:13:14
npm ERR!     at CB (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:93:17)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\DEVEOPMENT\CHELSEA\new4\node_modules\.staging\portfinder-6c0663f1' -> 'C:\DEVEOPMENT\CHELSEA\new4\node_modules\portfinder'
npm ERR!     at Error (native) parent: 'chelsea-website-ng4' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\DEVEOPMENT\CHELSEA\new4\npm-debug.log

even though I am using admin rights

**Comment by demiro** [comment]
Well, I closed the windows explorer and Vcode down... it went through... so working now

**Comment by patrickracicot** [comment]
What I had to do after getting the error was reboot, delete the folder and rerun npm install.  It just seems weird that suddenly we get this error on windows.

**Comment by tomwanzek** [comment]
@demiro I had the same experience.

**Comment by Brocco** [comment]
Glad you were able to get this working for you... closing the issue.
