### ISSUE TITLE
After updating to 1.1.x from 1.0.1 build fails when a package is npm-linked

### ISSUE THREAD

**Issue by kroeder** [angular/angular-cli#6713]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.1.2 (tried 1.1.1 as well)
node: 8.0.0
os: win32 x64
```

### Repro steps.
This seems to only affect our teams own UI-Component Library - I could not reproduce it with a fresh installation

This repository is not public but I can provide any information needed, I just don't know where to look anymore...

**How does this happen:**
1. Checkout application / npm install
2. Checkout library / npm install
3. npm link library into the application
4. Run `npm start`
5. Build process fails at 92% (asset optimization)

### The log given by the failure.
The message below is just one example. It seems that almost every source path is broken after updating from 1.0.1 to 1.1.x 
```
WARNING in C:/workspace/ui-components/~/apollo-client/index.js
(Emitted value instead of an instance of Error) Cannot find source file '../../src/index.ts': Error: Can't resolve '../../src/index.ts' in 'C:\workspace\ui-components\node_modules\apollo-client'
 @ C:/workspace/ui-components/src/lib/apollo/apollo-helper.ts 1:0-69
 @ C:/workspace/ui-components/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

### Desired functionality.
A sucessful build

### Mention any other details that might be useful.
- Without `npm link` the project build completes without any issues
- As mentioned, it works with 1.0.1
- I `ng new` a fresh project and bumped our package.json versions to those angular cli is currently relying on 
- The app and lib package.json are using the same version of every dependency that comes with a fresh ng cli project 
- I'm wondering why webpack is trying to use a path like this: `ui-components/~/apollo-client/index.js` - Where is the '~' coming from?

I would appreciate any help! We stuck on ng cli 1.0.1 until there's a way to solve this

**Comment by Brocco** [comment]
Can you please follow the steps [here](https://github.com/angular/angular-cli/wiki/stories-linked-library) and confirm everything is in order then report back here on this issue?

**Comment by kroeder** [comment]
I've made the lib aot-ready and compiled it with ngc - I now have an aot and a dist folder; package.json main points to dist/index.js

I also moved the angular deps to devDeps and peerDeps and edited tsconfig as mentioned in your linked article 

**Result:** Still the same issue - no further or different errors/infos

**Comment by nisimjoseph** [comment]
same issue here. need help.

**Comment by kroeder** [comment]
@nisimjoseph we also have apollo-client installed - have you tried it without? Does it work?

**Comment by kroeder** [comment]
We use apollo-client as well. Not sure it it's only apollo-client, though.
I'll try to `npm start` without, tomorrow - if it's just apollo we should create an issue on their repo

**Comment by nisimjoseph** [comment]
are you using TypeScript in your project?

**Comment by kroeder** [comment]
Yes

**Comment by nisimjoseph** [comment]
ok, so I took the `apollo-client` & `react-apollo` from GitHub, it is written in TypeScript as a source. added them as library folder inside the project. 

1. I needed to add a few packages to `package.json` file. you have them in "dependencies" section.
2. some of the `.ts` files will have the wrong location for `apollo-client` package,  now it not in node_modules.

it works for me until the fix for TypeScript will be ready.

**Comment by kroeder** [comment]
Can confirm, I've removed apollo-client and daterangepicker (https://github.com/kekeh/mydatepicker) 
After that the messages were gone

@nisimjoseph if you have fixed it for your project, could you tell us the fix or even better create an issue on https://github.com/apollographql/apollo-client with a reference to this issue?

**Comment by nisimjoseph** [comment]
ok

**Comment by kroeder** [comment]
Tried to reproduce it with a fresh cli 1.1.3 project plus a library example with apollo-client installed
Could not produce this error - are you sure apollo-client produced the issue or is just a symptom?

**Comment by kroeder** [comment]
I found out, that e.g. apillo-client has wrong source map paths

As example
index.js.map
```javascript
{
  "version": 3,
  "file": "index.js",
  "sourceRoot": "",
  "sources": [
    "../../src/index.ts"
  ], ...
```

But in my case "../../src" would be outside node_modules 
Am I on the right track @Brocco ? 

Were there any changes in displaying warnings after angular-cli 1.0.3?
Maybe this issue existed long before angular-cli 1.1.0 and is an apollo-client issue

On the other hand, as mentioned before, I could not reproduce this with a fresh `ng new testapp` and `apollo-client` installed 

Any ideas? :/

**Comment by kroeder** [comment]
@Brocco I found out that when I move the content of node_modules of my (npm linked) library to another location, then start the app, then move all node_modules back into my library, everything's working like a charm

can you imagine any unwanted side effects using this approach? If not - why not ignoring "node_modules" of `npm link` packages when angular-cli calls `ng serve`?

Is this something angular-cli can archieve or is this a webpack thing?

**Comment by alan-agius4** [comment]
Hi, Angular CLI version 1, is not longer supported and the current LTS is version 6.

Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
