### ISSUE TITLE
Enforce SSL in browser

### ISSUE THREAD

**Issue by tamascsaba** [angular/angular-cli#6714]
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

I use ```--ssl true``` when I serve my angular application, but angular-cli don't force ssl in browser.
I need manual type ```https://``` in browser, it would be great, if webpack-dev-server force ssl like `express-force-ssl` do.

**Comment by filipesilva** [comment]
Running `ng serve --ssl --open` nowadays will open `https://localhost:4200`.
