### ISSUE TITLE
unable to run code coverage as default

### ISSUE THREAD

**Issue by jodytate** [angular/angular-cli#6716]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report 
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.5
node: 7.7.1
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.5
@angular/compiler-cli: 4.1.3
```

### Repro steps.

Edit the `karma.conf.js` file, changing these lines

```
    reporters: config.angularCli && config.angularCli.codeCoverage
              ? ['progress', 'coverage-istanbul']
              : ['progress', 'kjhtml'],
```
to 
```
    reporters:  ['progress', 'coverage-istanbul']
```

### The log given by the failure.
No error logged. 

### Desired functionality.

My expectation was that by removing the conditional check it would always run coverage, but so far that isn't the case. I believe the `codeCoverage` default of `false` set elsewhere (I'm still confirming this is the case) overrides changes made in the karma config.

**Comment by jensbodal** [comment]
It would be nice if options specified in `angularCli` in `karma.conf.js` would override what's loaded here: https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/tasks/test.ts#L32

**Comment by filipesilva** [comment]
@jodytate In newer versions we don't use the conditional in `karma.conf.js` anymore, and remove `coverage-istanbul` if it's there to ensure compatibility with older configs. Using code coverage is not just a matter of using the reporter though, it also requires build changes to instrument code. 

So you cannot obtain the behaviour you're looking for just by changing your karma config, you need to use `ng test --code-coverage` to ensure the build uses the right preprocessors.

@jensbodal doing that would lead to a lot of duplication and difficulty in keeping feature parity. We only do it for extremely common options like `--single-run`. It's better to use `karma.conf.js` for most config items instead.

**Comment by jodytate** [comment]
@filipesilva Many thanks for the follow-up and explanation.
