### ISSUE TITLE
Generated stylesheets links missing type

### ISSUE THREAD

**Issue by rbirkgit** [angular/angular-cli#6718]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
### Versions.
@angular/cli: 1.1.1
node: 6.10.2

### Repro steps.
Run 'ng build --prod' on clean angular-cli generated project.

### The log given by the failure.
No log. No errors.

### Desired functionality.
The generated link to the style sheet in the index.html is missing the type. This causing issues with our framework. This is what the generated link looks like:

`<link href="styles.8433f21ade7e1bddd1c8.bundle.css" rel="stylesheet"/>`

But it should have the type, something like this:

`<link rel="stylesheet" type="text/css" href="styles.8433f21ade7e1bddd1c8.bundle.css">`

**Comment by rbirkgit** [comment]
The generated link to the style sheet in the index.html is missing the type. This causing issues with our framwork. This is what the genared link looks like:

<link href="styles.8433f21ade7e1bddd1c8.bundle.css" rel="stylesheet"/>

But it should have the type, something like this:

<link rel="stylesheet" type="text/css" href="styles.8433f21ade7e1bddd1c8.bundle.css">

**Comment by rbirkgit** [comment]
The generated link to the style sheet in the index.html is missing the type. This causing issues with our framwork. This is what the genared link looks like:

< link href="styles.8433f21ade7e1bddd1c8.bundle.css" rel="stylesheet"/ >

But it should have the type, something like this:

< link rel="stylesheet" type="text/css" href="styles.8433f21ade7e1bddd1c8.bundle.css" />

**Comment by rbirkgit** [comment]
I don't know how to get that code inserted so had to add spaces after/before the < >

**Comment by clydin** [comment]
The default type for a stylesheet link is "text/css".  There's no need to include it unless the type is something else and even then value is not authoritative.  The content type from the response header ultimately defines the actual type for the resource.

What framework is being used?  Perhaps an issue could be raised with the maintainers.

**Comment by rbirkgit** [comment]
We are using Apache Shindig 2.5.2 which has ended development. Maybe there is a bug in it

**Comment by clydin** [comment]
Closing as the current behavior is intended and supported by Angular's list of officially supported browser versions.
