### ISSUE TITLE
ng test error

### ISSUE THREAD

**Issue by zo-tahiana** [angular/angular-cli#6724]
Hello,

When I launch `ng test` in the command line, I have a bug like this following:

ERROR in G:/My_Repositories/my-first-app/src/app/services/users.service.spec.ts (3,30): An import path cannot end with a '.ts' extension. Consider importing './users.service' instead.

Thanks for help me to resolve that.

**Comment by jgodi** [comment]
It appears that your import is

`import { UserService} from './users.service.ts'`

remove the extension and try again.

This type of question is more suited for StackOverflow or the [Gitter Channel](https://gitter.im/angular/angular-cli?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by zo-tahiana** [comment]
ah... I see, it's resoved, thank you @jgodi
