### ISSUE TITLE
Failing to install angular cli

### ISSUE THREAD

**Issue by joelmuskwe** [angular/angular-cli#6725]
### Bug Report
Failing to install angular-cli

### Versions.
PS C:\Windows\system32> node -v
v8.1.2
PS C:\Windows\system32> npm -v
5.0.3
PS C:\Windows\system32>
  Windows (10).

### Repro steps.
npm install -g @angular/cli

### The log given by the failure.
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose npm-session 7d1adfc9296177b9
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@angular%2fcli 2457ms (from cache)
8 silly pacote tag manifest for @angular/cli@latest fetched in 2503ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule @angular/cli@1.1.2 checking installable status
14 http fetch GET 200 https://registry.npmjs.org/chalk 42ms (from cache)
15 http fetch GET 200 https://registry.npmjs.org/common-tags 41ms (from cache)
16 http fetch GET 200 https://registry.npmjs.org/autoprefixer 48ms (from cache)
17 http fetch GET 200 https://registry.npmjs.org/cssnano 67ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/css-loader 69ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/diff 71ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/denodeify 72ms (from cache)
21 http fetch GET 200 https://registry.npmjs.org/debug 73ms (from cache)
22 silly pacote range manifest for common-tags@^1.3.1 fetched in 78ms
23 silly resolveWithNewModule common-tags@1.4.0 checking installable status
24 silly pacote range manifest for autoprefixer@^6.5.3 fetched in 82ms
25 silly resolveWithNewModule autoprefixer@6.7.7 checking installable status
26 silly pacote range manifest for chalk@^1.1.3 fetched in 82ms
27 silly resolveWithNewModule chalk@1.1.3 checking installable status
28 silly pacote range manifest for cssnano@^3.10.0 fetched in 88ms
29 silly resolveWithNewModule cssnano@3.10.0 checking installable status
30 silly pacote range manifest for css-loader@^0.28.1 fetched in 89ms
31 silly resolveWithNewModule css-loader@0.28.4 checking installable status
32 silly pacote range manifest for diff@^3.1.0 fetched in 94ms
33 silly resolveWithNewModule diff@3.2.0 checking installable status
34 silly pacote range manifest for denodeify@^1.2.1 fetched in 96ms
35 silly resolveWithNewModule denodeify@1.2.1 checking installable status
36 silly pacote range manifest for debug@^2.1.3 fetched in 100ms
37 silly resolveWithNewModule debug@2.6.8 checking installable status
38 http fetch GET 200 https://registry.npmjs.org/exports-loader 51ms (from cache)
39 http fetch GET 200 https://registry.npmjs.org/ember-cli-normalize-entity-name 53ms (from cache)
40 http fetch GET 200 https://registry.npmjs.org/extract-text-webpack-plugin 44ms (from cache)
41 http fetch GET 200 https://registry.npmjs.org/ember-cli-string-utils 54ms (from cache)
42 http fetch GET 200 https://registry.npmjs.org/file-loader 46ms (from cache)
43 http fetch GET 200 https://registry.npmjs.org/fs-extra 39ms (from cache)
44 http fetch GET 200 https://registry.npmjs.org/get-caller-file 44ms (from cache)
45 silly pacote range manifest for exports-loader@^0.6.3 fetched in 62ms
46 silly resolveWithNewModule exports-loader@0.6.4 checking installable status
47 http fetch GET 200 https://registry.npmjs.org/glob 43ms (from cache)
48 silly pacote range manifest for ember-cli-normalize-entity-name@^1.0.0 fetched in 66ms
49 silly resolveWithNewModule ember-cli-normalize-entity-name@1.0.0 checking installable status
50 silly pacote range manifest for extract-text-webpack-plugin@^2.1.0 fetched in 59ms
51 silly resolveWithNewModule extract-text-webpack-plugin@2.1.2 checking installable status
52 silly pacote range manifest for ember-cli-string-utils@^1.0.0 fetched in 70ms
53 silly resolveWithNewModule ember-cli-string-utils@1.1.0 checking installable status
54 silly pacote range manifest for file-loader@^0.10.0 fetched in 63ms
55 silly resolveWithNewModule file-loader@0.10.1 checking installable status
56 silly pacote range manifest for fs-extra@^2.0.0 fetched in 57ms
57 silly resolveWithNewModule fs-extra@2.1.2 checking installable status
58 silly pacote range manifest for get-caller-file@^1.0.0 fetched in 59ms
59 silly resolveWithNewModule get-caller-file@1.0.2 checking installable status
60 silly pacote range manifest for glob@^7.0.3 fetched in 58ms
61 silly resolveWithNewModule glob@7.1.2 checking installable status
62 http fetch GET 200 https://registry.npmjs.org/inflection 30ms (from cache)
63 http fetch GET 200 https://registry.npmjs.org/html-webpack-plugin 32ms (from cache)
64 http fetch GET 200 https://registry.npmjs.org/inquirer 31ms (from cache)
65 http fetch GET 200 https://registry.npmjs.org/isbinaryfile 32ms (from cache)
66 http fetch GET 200 https://registry.npmjs.org/json-loader 30ms (from cache)
67 silly pacote range manifest for inflection@^1.7.0 fetched in 39ms
68 silly resolveWithNewModule inflection@1.12.0 checking installable status
69 silly pacote range manifest for html-webpack-plugin@^2.19.0 fetched in 41ms
70 silly resolveWithNewModule html-webpack-plugin@2.28.0 checking installable status
71 http fetch GET 200 https://registry.npmjs.org/less 32ms (from cache)
72 http fetch GET 200 https://registry.npmjs.org/less-loader 31ms (from cache)
73 http fetch GET 200 https://registry.npmjs.org/lodash 29ms (from cache)
74 silly pacote range manifest for inquirer@^3.0.0 fetched in 41ms
75 silly resolveWithNewModule inquirer@3.1.0 checking installable status
76 silly pacote range manifest for isbinaryfile@^3.0.0 fetched in 42ms
77 silly resolveWithNewModule isbinaryfile@3.0.2 checking installable status
78 silly pacote range manifest for json-loader@^0.5.4 fetched in 40ms
79 silly resolveWithNewModule json-loader@0.5.4 checking installable status
80 silly pacote range manifest for less@^2.7.2 fetched in 42ms
81 silly resolveWithNewModule less@2.7.2 checking installable status
82 silly pacote range manifest for less-loader@^4.0.2 fetched in 42ms
83 silly resolveWithNewModule less-loader@4.0.4 checking installable status
84 silly pacote range manifest for lodash@^4.11.1 fetched in 41ms
85 silly resolveWithNewModule lodash@4.17.4 checking installable status
86 http fetch GET 200 https://registry.npmjs.org/minimatch 24ms (from cache)
87 http fetch GET 200 https://registry.npmjs.org/memory-fs 30ms (from cache)
88 http fetch GET 200 https://registry.npmjs.org/node-modules-path 28ms (from cache)
89 http fetch GET 200 https://registry.npmjs.org/nopt 27ms (from cache)
90 silly pacote range manifest for minimatch@^3.0.3 fetched in 33ms
91 silly resolveWithNewModule minimatch@3.0.4 checking installable status
92 http fetch GET 200 https://registry.npmjs.org/opn 25ms (from cache)
93 http fetch GET 200 https://registry.npmjs.org/portfinder 25ms (from cache)
94 http fetch GET 200 https://registry.npmjs.org/postcss-loader 23ms (from cache)
95 silly pacote range manifest for memory-fs@^0.4.1 fetched in 48ms
96 silly resolveWithNewModule memory-fs@0.4.1 checking installable status
97 silly pacote range manifest for node-modules-path@^1.0.0 fetched in 47ms
98 silly resolveWithNewModule node-modules-path@1.0.1 checking installable status
99 http fetch GET 200 https://registry.npmjs.org/postcss-url 36ms (from cache)
100 silly pacote range manifest for nopt@^4.0.1 fetched in 56ms
101 silly resolveWithNewModule nopt@4.0.1 checking installable status
102 silly pacote version manifest for opn@4.0.2 fetched in 53ms
103 silly resolveWithNewModule opn@4.0.2 checking installable status
104 silly pacote range manifest for postcss-loader@^1.3.3 fetched in 52ms
105 silly resolveWithNewModule postcss-loader@1.3.3 checking installable status
106 silly pacote range manifest for portfinder@~1.0.12 fetched in 56ms
107 silly resolveWithNewModule portfinder@1.0.13 checking installable status
108 silly pacote range manifest for postcss-url@^5.1.2 fetched in 57ms
109 silly resolveWithNewModule postcss-url@5.1.2 checking installable status
110 http fetch GET 200 https://registry.npmjs.org/raw-loader 43ms (from cache)
111 http fetch GET 200 https://registry.npmjs.org/resolve 34ms (from cache)
112 http fetch GET 200 https://registry.npmjs.org/rimraf 28ms (from cache)
113 silly pacote range manifest for raw-loader@^0.5.1 fetched in 52ms
114 silly resolveWithNewModule raw-loader@0.5.1 checking installable status
115 http fetch GET 200 https://registry.npmjs.org/rsvp 25ms (from cache)
116 http fetch GET 200 https://registry.npmjs.org/rxjs 22ms (from cache)
117 http fetch GET 200 https://registry.npmjs.org/script-loader 24ms (from cache)
118 http fetch GET 200 https://registry.npmjs.org/sass-loader 26ms (from cache)
119 silly pacote range manifest for resolve@^1.1.7 fetched in 46ms
120 silly resolveWithNewModule resolve@1.3.3 checking installable status
121 http fetch GET 200 https://registry.npmjs.org/semver 23ms (from cache)
122 silly pacote range manifest for rimraf@^2.5.3 fetched in 40ms
123 silly resolveWithNewModule rimraf@2.6.1 checking installable status
124 silly pacote range manifest for rsvp@^3.0.17 fetched in 39ms
125 silly resolveWithNewModule rsvp@3.5.0 checking installable status
126 silly pacote range manifest for rxjs@^5.0.1 fetched in 37ms
127 silly resolveWithNewModule rxjs@5.4.1 checking installable status
128 silly pacote range manifest for script-loader@^0.7.0 fetched in 37ms
129 silly resolveWithNewModule script-loader@0.7.0 checking installable status
130 silly pacote range manifest for sass-loader@^6.0.3 fetched in 40ms
131 silly resolveWithNewModule sass-loader@6.0.6 checking installable status
132 silly pacote range manifest for semver@^5.1.0 fetched in 36ms
133 silly resolveWithNewModule semver@5.3.0 checking installable status
134 http fetch GET 200 https://registry.npmjs.org/silent-error 28ms (from cache)
135 http fetch GET 200 https://registry.npmjs.org/source-map-loader 29ms (from cache)
136 http fetch GET 200 https://registry.npmjs.org/istanbul-instrumenter-loader 27ms (from cache)
137 silly pacote range manifest for silent-error@^1.0.0 fetched in 41ms
138 silly resolveWithNewModule silent-error@1.1.0 checking installable status
139 http fetch GET 200 https://registry.npmjs.org/style-loader 25ms (from cache)
140 http fetch GET 200 https://registry.npmjs.org/stylus 28ms (from cache)
141 http fetch GET 200 https://registry.npmjs.org/stylus-loader 30ms (from cache)
142 silly pacote range manifest for source-map-loader@^0.2.0 fetched in 40ms
143 silly resolveWithNewModule source-map-loader@0.2.1 checking installable status
144 http fetch GET 200 https://registry.npmjs.org/temp 29ms (from cache)
145 silly pacote range manifest for istanbul-instrumenter-loader@^2.0.0 fetched in 37ms
146 silly resolveWithNewModule istanbul-instrumenter-loader@2.0.0 checking installable status
147 silly pacote range manifest for style-loader@^0.13.1 fetched in 36ms
148 silly resolveWithNewModule style-loader@0.13.2 checking installable status
149 silly pacote range manifest for stylus@^0.54.5 fetched in 37ms
150 silly resolveWithNewModule stylus@0.54.5 checking installable status
151 silly pacote range manifest for stylus-loader@^3.0.1 fetched in 38ms
152 silly resolveWithNewModule stylus-loader@3.0.1 checking installable status
153 silly pacote version manifest for temp@0.8.3 fetched in 38ms
154 silly resolveWithNewModule temp@0.8.3 checking installable status
155 http fetch GET 200 https://registry.npmjs.org/url-loader 20ms (from cache)
156 silly pacote range manifest for url-loader@^0.5.7 fetched in 29ms
157 silly resolveWithNewModule url-loader@0.5.9 checking installable status
158 http fetch GET 200 https://registry.npmjs.org/walk-sync 22ms (from cache)
159 http fetch GET 200 https://registry.npmjs.org/webpack 24ms (from cache)
160 silly fetchPackageMetaData error for webpack@~2.4.0 Unexpected end of input at 1:453112
160 silly fetchPackageMetaData 0.0","interpret":"^1.0.0","json-loader":"^0.5.4","loader-runner":"^2.
160 silly fetchPackageMetaData                                                                      ^
161 http fetch GET 200 https://registry.npmjs.org/webpack-dev-middleware 120ms (from cache)
162 http fetch GET 200 https://registry.npmjs.org/webpack-dev-server 119ms (from cache)
163 http fetch GET 200 https://registry.npmjs.org/webpack-merge 120ms (from cache)
164 silly pacote range manifest for walk-sync@^0.3.1 fetched in 130ms
165 silly resolveWithNewModule walk-sync@0.3.2 checking installable status
166 http fetch GET 200 https://registry.npmjs.org/zone.js 122ms (from cache)
167 silly pacote range manifest for webpack-dev-middleware@^1.10.2 fetched in 132ms
168 silly resolveWithNewModule webpack-dev-middleware@1.10.2 checking installable status
169 silly pacote range manifest for webpack-dev-server@~2.4.5 fetched in 132ms
170 silly resolveWithNewModule webpack-dev-server@2.4.5 checking installable status
171 silly pacote range manifest for webpack-merge@^2.4.0 fetched in 133ms
172 silly resolveWithNewModule webpack-merge@2.6.1 checking installable status
173 silly pacote range manifest for zone.js@^0.8.4 fetched in 132ms
174 silly resolveWithNewModule zone.js@0.8.12 checking installable status
175 http fetch GET 200 https://registry.npmjs.org/node-sass 22ms (from cache)
176 silly pacote range manifest for node-sass@^4.3.0 fetched in 31ms
177 silly resolveWithNewModule node-sass@4.5.3 checking installable status
178 http fetch GET 304 https://registry.npmjs.org/@ngtools%2fjson-schema 1280ms (from cache)
179 silly pacote version manifest for @ngtools/json-schema@1.1.0 fetched in 1285ms
180 silly resolveWithNewModule @ngtools/json-schema@1.1.0 checking installable status
181 http fetch GET 304 https://registry.npmjs.org/typescript 1310ms (from cache)
182 silly pacote range manifest for typescript@>=2.0.0 <2.4.0 fetched in 1328ms
183 silly resolveWithNewModule typescript@2.3.4 checking installable status
184 http fetch GET 304 https://registry.npmjs.org/@ngtools%2fwebpack 1766ms (from cache)
185 silly pacote version manifest for @ngtools/webpack@1.4.1 fetched in 1767ms
186 silly resolveWithNewModule @ngtools/webpack@1.4.1 checking installable status
187 verbose stack SyntaxError: Unexpected end of input at 1:453112
187 verbose stack 0.0","interpret":"^1.0.0","json-loader":"^0.5.4","loader-runner":"^2.
187 verbose stack                                                                      ^
187 verbose stack     at Object.parseJSON (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-helpfulerror\node_modules\jju\lib\parse.js:745:13)
187 verbose stack     at parse (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-helpfulerror\index.js:10:13)
187 verbose stack     at consumeBody.call.then.buffer (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
187 verbose stack     at <anonymous>
187 verbose stack     at process._tickCallback (internal/process/next_tick.js:169:7)
188 verbose cwd C:\Windows\system32
189 verbose Windows_NT 10.0.15063
190 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
191 verbose node v8.1.2
192 verbose npm  v5.0.3
193 error Unexpected end of input at 1:453112
193 error 0.0","interpret":"^1.0.0","json-loader":"^0.5.4","loader-runner":"^2.
193 error                                                                      ^
194 verbose exit [ 1, true ]

**Comment by NyAntema** [comment]
did you find the origin of this error ? @joelmuskwe
