### ISSUE TITLE
'ng' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by borgogelli** [angular/angular-cli#6726]
On Windows 7, the command
`npm install -q @angular/cli`
installs all the files inside the folder
`C:\Users\<User>\node_modules`
instead of
`C:\Users\<User>\AppData\Roaming\npm\node_modules`

**Comment by deebloo** [comment]
this sounds like an issue with your node/npm config rather then a cli issue

**Comment by dannypule** [comment]
Try `npm install -g @angular/cli` (using a `-g` instead of a `-q` like in your example)

**Comment by Brocco** [comment]
@deebloo is correct, this is not a CLI issue, but the suggestion from @dannypule will help you out. Good luck!

**Comment by borgogelli** [comment]
@Brocco , @dannypule  , we are right. Sorry it was just a typo error.
