### ISSUE TITLE
Generated main.ts showing errors in intelliJ

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#673]
The generated main.ts shows errors when using `beta.0`  The imports for `AppComponent` and `environment` both had issues in IntelliJ on OSX.

Non working:
```import { AppComponent, environment } from './app/';```
Working: 
```import { AppComponent, environment } from './app';```

**Comment by filipesilva** [comment]
I tested in Atom and Visual Studio Code and they seemed to be ok with `import { AppComponent, environment } from './app/';`

**Comment by hawlik** [comment]
Same in webstorm. I had to remove trailing slash.

**Comment by Codenator81** [comment]
I just reopen webstorm and error from IDE gone

**Comment by hansl** [comment]
Considering WebStorm is IntelliJ with a different theming, it's not surprising. I think we should fix this.

**Comment by filipesilva** [comment]
Not sure we can fix it, perhaps by changing something in `tsconfig.json`? 

Removing the slash isn't the solution since we can have the `app.ts` file and the `app/` folder, which would both be resolved to the same using `import {} from 'app'`.

**Comment by filipesilva** [comment]
To be clear though, the slash should be there, the issue is with webstorm recognizing barrels.

**Comment by hansl** [comment]
I talked to JetBrains, and they seem to be moving towards using the TypeScript compiler which will probably resolve this. In any case I agree with Filipe.

**Comment by Brocco** [comment]
There appears to be a consensus that this does not need fixed and we will be relying on JetBrains to resolve the issue in IntelliJ & WebStorm; therefore, closing this issue.
