### ISSUE TITLE
Eject to custom webpack configuration file

### ISSUE THREAD

**Issue by bampakoa** [angular/angular-cli#6731]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.1.2 (e)
node: 6.9.5
os: win32 x64
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/core: 4.2.3
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/router: 4.2.3
@angular/cli: 1.1.2
@angular/compiler-cli: 4.2.3

### Desired functionality.

I maintain different webpack configuration files for the needs of my project (2 for development and 2 for production). One of the development files is the default `webpack.config.js` which I use to merge changes back to the remaining ones, when a new version of CLI is released. That is, I run `ng eject` each time to apply the changes in the default config, inspect those changes and apply them to the other files by hand. I follow this process in order not to mess up my custom configuration in the webpack configuration files. It would be really handy, if I could define the target config file of the eject command such as: `ng eject --config=<the config file>` and have the changes directly applied to the configuration files.

**Comment by clydin** [comment]
eject functionality is no longer available in the latest version (6.x+).  For custom webpack configurations the following unofficial add-on is a suggested solution: https://github.com/manfredsteyer/ngx-build-plus
