### ISSUE TITLE
Add circular dependency plugin to Webpack config

### ISSUE THREAD

**Issue by eppsilon** [angular/angular-cli#6739]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.

```
@angular/cli: 1.1.2
node: 6.11.0
os: darwin x64
@angular/animations: 4.2.3
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/core: 4.2.3
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/platform-server: 4.2.3
@angular/router: 4.2.3
@angular/cli: 1.1.2
@angular/compiler-cli: 4.2.3
@angular/language-service: 4.2.3
```

### Desired functionality.

Circular dependency bugs are easy to introduce and can be hard to detect and troubleshoot. Sometimes everything works fine, but in a few cases I've had module imports show up as `undefined` at runtime. Last time it happened, it was only in AOT mode, so I didn't catch it initially.

It would be helpful if the CLI included a plugin that warns you if circular dependencies are detected and logs the modules that are part of the cycle.

### Mention any other details that might be useful.

I used [this plugin](https://github.com/aackerman/circular-dependency-plugin) and it found several issues in my project.

However, I couldn't configure Webpack to use the plugin without ejecting the config, and I'd rather not have to do that each time I need to debug an issue like this.

**Comment by filipesilva** [comment]
I'll have a look. I agree it's a difficult to debug issue and that we should add a plugin if it helps and has no unexpected side effects.

**Comment by di3orlive** [comment]
@filipesilva `ng build --show-circular-dependencies`
not working yet?

**Comment by filipesilva** [comment]
It should be working in `@angular/cli@next`.

**Comment by di3orlive** [comment]
@filipesilva tnx. so its only show some errors in console on build ?

**Comment by filipesilva** [comment]
Check https://github.com/angular/angular-cli/pull/6813 for an example of the output.

**Comment by di3orlive** [comment]
@filipesilva cool (: tnx, useful feature
