### ISSUE TITLE
Source maps problem after upgrading from 1.1.0 to 1.1.1

### ISSUE THREAD

**Issue by bbaia** [angular/angular-cli#6745]
### Bug Report or Feature Request
```
- [x] bug report
- [ ] feature request
```

### Versions.
Node.js 6.10.3
npm 3.10.10
Ubuntu 16.01

### Repro steps.
Breakpoints on Visual Studio Code are not working anymore
`ng serve --host 0.0.0.0 --progress=false --proxy-config proxy.conf.json`
Started from a Docker image

### Mention any other details that might be useful.
Fails on v1.1.2 and v1.2.0-rc.0 too

**Comment by danielsuter** [comment]
Maybe related to #6737?

**Comment by mm-q** [comment]
#6623 Related to this. Upgrade to 1.1.2, works.

**Comment by bbaia** [comment]
Duplicates #6623.
But does not workshop on 1.1.2 for me.

**Comment by mm-q** [comment]
I am on 1.1.2 (check ng version to be perfectly sure) and using the default launch options for Chrome Debugger. Works perfectly fine. You might want to include the trace from the debugger extension, maybe someone will be able to help you...

**Comment by bbaia** [comment]
The problem remains when debugging through Docker using `ng serve --host 0.0.0.0`.
I will re-open #6623 

And next time, I'll try to not duplicate issues by looking into closed issues too :)

```
@angular/cli: 1.1.2
node: 6.10.3
os: linux x64
@angular/animations: 4.2.3
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/core: 4.2.3
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/router: 4.2.3
@angular/cli: 1.1.2
@angular/compiler-cli: 4.2.3
@angular/language-service: 4.2.3
```
