### ISSUE TITLE
Angular cli installation failed on ubuntu 14.04

### ISSUE THREAD

**Issue by SaqlainGardezi** [angular/angular-cli#6750]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose cache add [ '@angular/cli', null ]
5 verbose cache add name=undefined spec="@angular/cli" args=["@angular/cli",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: '@angular/cli',
6 verbose parsed url   path: '@angular/cli',
6 verbose parsed url   href: '@angular/cli' }
7 verbose cache add name="" spec="angular/cli" args=["","angular/cli"]
8 verbose parsed url { protocol: null,
8 verbose parsed url   slashes: null,
8 verbose parsed url   auth: null,
8 verbose parsed url   host: null,
8 verbose parsed url   port: null,
8 verbose parsed url   hostname: null,
8 verbose parsed url   hash: null,
8 verbose parsed url   search: null,
8 verbose parsed url   query: null,
8 verbose parsed url   pathname: 'angular/cli',
8 verbose parsed url   path: 'angular/cli',
8 verbose parsed url   href: 'angular/cli' }
9 silly lockFile 5cecaa1c-angular-cli angular/cli
10 verbose lock angular/cli /home/saqlain/.npm/5cecaa1c-angular-cli.lock
11 info maybeGithub Attempting angular/cli from git://github.com/angular/cli
12 silly lockFile 057ccbdd-git-github-com-angular-cli git://github.com/angular/cli
13 verbose lock git://github.com/angular/cli /home/saqlain/.npm/057ccbdd-git-github-com-angular-cli.lock
14 verbose addRemoteGit [ 'git://github.com/angular/cli', 'master' ]
15 verbose git clone git://github.com/angular/cli Cloning into bare repository '/home/saqlain/.npm/_git-remotes/git-github-com-angular-cli-057ccbdd'...
15 verbose git clone git://github.com/angular/cli fatal: remote error:
15 verbose git clone git://github.com/angular/cli   Repository not found.
16 silly lockFile 057ccbdd-git-github-com-angular-cli git://github.com/angular/cli
17 silly lockFile 057ccbdd-git-github-com-angular-cli git://github.com/angular/cli
18 info maybeGithub Attempting angular/cli from git+ssh://git@github.com:angular/cli
19 silly lockFile c455b8ea-t-ssh-git-github-com-angular-cli git+ssh://git@github.com:angular/cli
20 verbose lock git+ssh://git@github.com:angular/cli /home/saqlain/.npm/c455b8ea-t-ssh-git-github-com-angular-cli.lock
21 verbose addRemoteGit [ 'git@github.com:angular/cli', 'master' ]
22 error git clone git@github.com:angular/cli Cloning into bare repository '/home/saqlain/.npm/_git-remotes/git-github-com-angular-cli-515723dd'...
22 error git clone git@github.com:angular/cli Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
22 error git clone git@github.com:angular/cli Permission denied (publickey).
22 error git clone git@github.com:angular/cli fatal: Could not read from remote repository.
22 error git clone git@github.com:angular/cli
22 error git clone git@github.com:angular/cli Please make sure you have the correct access rights
22 error git clone git@github.com:angular/cli and the repository exists.
23 silly lockFile 515723dd-git-github-com-angular-cli git@github.com:angular/cli
24 silly lockFile 5cecaa1c-angular-cli angular/cli
25 silly lockFile 5cecaa1c-angular-cli angular/cli
26 error addLocal Could not install angular/cli
27 error Error: ENOENT, stat 'angular/cli'
28 error If you need help, you may report this log at:
28 error     <http://github.com/isaacs/npm/issues>
28 error or email it to:
28 error     <npm-@googlegroups.com>
29 error System Linux 4.4.0-79-generic
30 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@angular/cli"
31 error cwd /media/saqlain/EEC856E4C856AB1B/notepad/node/12 ng
32 error node -v v0.10.25
33 error npm -v 1.3.10
34 error path angular/cli
35 error code ENOENT
36 error errno 34
37 verbose exit [ 34, true ]

If nothing, output from: `node 6.11.0` and `3.10.10`.
  Linux (14.04)

sudo npm install -g @angular/cli

**Comment by clydin** [comment]
From the log output above, this appears to be the problem:
```
2 info using npm@1.3.10
3 info using node@v0.10.25
```
Note the node version.

**Comment by SaqlainGardezi** [comment]
How can I solve this? @clydin

**Comment by Cuel** [comment]
@SaqlainGardezi install node v6.9.0 or higher https://nodejs.org/en/download/

**Comment by filipesilva** [comment]
Closing as answered, thanks @clydin and @Cuel 👍
