### ISSUE TITLE
[enhancement] Upgrade build system to Webpack 3

### ISSUE THREAD

**Issue by avatsaev** [angular/angular-cli#6752]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
### Desired functionality.

Consider upgrading to  Webpack 3 for even lighter bundle sizes and optimizations.

### Mention any other details that might be useful.

More info: https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

**Comment by intellix** [comment]
https://github.com/angular/angular-cli/pull/6365/files

**Comment by devoto13** [comment]
@filipesilva This can be closed now.

**Comment by filipesilva** [comment]
Closing as we've updated.
