### ISSUE TITLE
computer freezes on install, exec format error

### ISSUE THREAD

**Issue by clavierpaul** [angular/angular-cli#6753]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

node --version: v7.10.0
npm --version: 4.2.0
Ubuntu 17.04

### Repro steps.

`sudo npm install -g @angular/cli`
force reboot computer after crash at end of installation
`ng`

### The log given by the failure.

    Failed to execute process '/usr/bin/ng'. Reason:
    exec: Exec format error
    The file '/usr/bin/ng' is marked as an executable but could not be run by the operating system.

### Mention any other details that might be useful.

Really at a loss for words at this one. Computer crashes after the install finishes and trying to run ng throws an exec error. I've fully reinstalled node and npm. Other global installs seem to work fine as well.

**Comment by clavierpaul** [comment]
Installed node-gyp first and that seemed to have fixed it.

**Comment by filipesilva** [comment]
You shouldn't need `node-gyp` though, and you definitely shouldn't need to install it with sudo, which might really be the cause of the problem. See https://docs.npmjs.com/getting-started/fixing-npm-permissions for how to fix your permissions.
