### ISSUE TITLE
Proposal: Ability to create Webpack based ng2 app

### ISSUE THREAD

**Issue by MarkPieszak** [angular/angular-cli#676]
First off, great work guys!

Just an idea, and I would love to help if I can, but maybe we could have a webpack based app structure as well as SystemJS? Something along the lines of:

    ng2 new myApp --webpack 

I know it would require a lot of different files being added, different index.html etc, but just wondering what you guys thought! It might be nice since a lot of people are already familiar with Webpack.

**Comment by alvipeo** [comment]
if angular team goes for the features like tree-shaking, then bundling and minification with tools like rollup (for now) why distract them from it now? Well, my 2 cents..

**Comment by sgentile** [comment]
+1

**Comment by MarkPieszak** [comment]
You're right alvipeo, I'll close this out for now, after talking to Mike & Zack it seems the Angular team is going more towards the SystemJS direction. So this might derail things (since a lot of things will be very different if you're using webpack).

**Comment by sgentile** [comment]
Would be interesting to understand why they prefer SystemJS - thanks for
the response.

(Does SystemJS support chunking by routes ?)
