### ISSUE TITLE
[Feature Request] Optional run-time type checking

### ISSUE THREAD

**Issue by buu700** [angular/angular-cli#6763]
The project [fabiandev/ts-runtime](https://github.com/fabiandev/ts-runtime) accomplishes this by hooking up TypeScript's new transformation API with the flow-runtime type assertion library.

~~It sounds pretty awesome, but would be inconvenient to use on its own as it apparently requires that a new import be added to every single source file (which would also be problematic because I wouldn't want to include it in a production build).~~ *Edit: Disregard this. There still isn't a good way to use it in a CLI project as-is, but that particular reason isn't correct.*

My request is a flag for build/serve to automatically handle setting this up, intended mainly for use during development.

**Comment by filipesilva** [comment]
This is a very interesting idea. The extra transforms would likely have to be added to the existing tsc/ngc compilation in order to fully support everything.

We're also experimenting with transforms in https://github.com/angular/ngo, but those are meant to be applied to JS files. Some of them could go on a pipeline with tsc/ngc though.

/cc @robwormald

**Comment by mgechev** [comment]
@buu700 you can extend the build configuration with ngx-build-plus.

Out of curiosity, what errors do you expect to catch with runtime type checking which are impossible to catch at build time, with specific types?

**Comment by mgechev** [comment]
Yes, this seems like a good use case. protobuf or swagger both work great in this case. I've worked on a similar problem where the backend and the frontend services shared a common schema, which was verifiable at build-time. We never hit a runtime error.

An issue could be if the type system on the backend service is not expressive enough to handle the static protocol verification. In such case you may need runtime type checking on the frontend.

**Comment by cyrilletuzi** [comment]
Not sure it's the same scenario, but runtime checks are needed for libraries like [`@ngx-pwa/local-storage`](https://github.com/cyrilletuzi/angular-async-local-storage), as client-side storage can be mitigated.

For now the API is quite painful, as it needed both TypeScript types for the developer experience *and* runtime checks via a JSON schema.

I don't expect the CLI to handle that, but as I've seen this discussion, just sharing my case, as I would be very interested if you know better solutions to handle that.
