### ISSUE TITLE
Allow proxy in ng-serve to proxy to local files

### ISSUE THREAD

**Issue by chrisspelberg** [angular/angular-cli#6773]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 7.6.0
os: win32 x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/compiler-cli: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/language-service: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/platform-server: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0

### Desired functionality.

My application reads data from a service that is not available in my development environment. I want to proxy the request to a local file to be able to supply mock data to use during development.

The simplest solution would be to have the proxy-conf.json support file url's. Example:

```
{
  "/assets/data.json": {
    "target": "file:./mockdata/data.json"
  }
}
```

**Comment by filipesilva** [comment]
We mostly just provide access the the webpack dev server proxy (https://webpack.js.org/configuration/dev-server/#devserver-proxy). You might have to ask them for that functionality.
