### ISSUE TITLE
ng serve doesn't work with chrome ("unexpected token <")

### ISSUE THREAD

**Issue by edo-vi** [angular/angular-cli#6775]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.0
node: 8.1.2
os: darwin x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.0
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4

macOS (10.12.5)
Chrome version 59.0.3071.109 (64-bit)

### Repro steps.

using angular cli
```
ng new any
cd any
ng serve
```
in chrome browser: error ('Uncaught SyntaxError: Unexpected token <'), localhost served as type 'script' not 'document'

### Desired functionality.
It should serve index.html as document and work correctly, instead the app doesn't load. This error only happens in chrome, in safari works correctly

**Comment by filipesilva** [comment]
You might have a problem with an extension in chrome actually. I have that exact chrome build and everything runs fine. I'm on windows though.

**Comment by edo-vi** [comment]
Yeah it works in windows actually, only on my Mac it doesn't work. I have tried uninstalling and reinstalling chrome, I'll try with angular-cli

**Comment by tytskyi** [comment]
@edo-vi did you try in Chrome's Incognito Mode? Theoretically you have extensions turned off in it (unless you specified to run particular extension in Incognito)

**Comment by edo-vi** [comment]
Yeah it works! I didn't know it could be an extension problem, I removed every extension and cleared the cache and now works!
Thanks for your time, I guess you can close this now

**Comment by Splaktar** [comment]
@edo-vi thanks for confirming the solution. You should be able to close the issue as well since you opened it :)

**Comment by thomaschampagne** [comment]
@edo-vi Do you have a base template for a chrome extension running angular-cli in serve mode?

I try to develop my chrome extension with ng serve but i fail. I also tried with --prod. Same problem.

Thanks,

Thomas
