### ISSUE TITLE
ng serve success but open browser to shock.(help me please.)

### ISSUE THREAD

**Issue by pandaboycom** [angular/angular-cli#6779]
> ng serve

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: f9a3435b6e367e9e13f4
Time: 24554ms
chunk    {0} 0.chunk.js, 0.chunk.js.map 853 kB {1} {2} {3} {4} {5} {6} {8} [rendered]
chunk    {1} 1.chunk.js, 1.chunk.js.map 849 kB {0} {2} {3} {4} {5} {6} {8} [rendered]
chunk    {2} 2.chunk.js, 2.chunk.js.map 21.9 kB {0} {1} {3} {4} {5} {6} {8} [rendered]
chunk    {3} 3.chunk.js, 3.chunk.js.map 17.1 kB {0} {1} {2} {4} {5} {6} {8} [rendered]
chunk    {4} 4.chunk.js, 4.chunk.js.map 8.6 kB {0} {1} {2} {3} {5} {6} {8} [rendered]
chunk    {5} 5.chunk.js, 5.chunk.js.map 5.86 kB {0} {1} {2} {3} {4} {6} {8} [rendered]
chunk    {6} 6.chunk.js, 6.chunk.js.map 4.88 kB {0} {1} {2} {3} {4} {5} {8} [rendered]
chunk    {7} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 160 kB {12} [initial] [rendered]
chunk    {8} main.bundle.js, main.bundle.js.map (main) 48.6 kB {11} [initial] [rendered]
chunk    {9} styles.bundle.js, styles.bundle.js.map (styles) 326 kB {12} [initial] [rendered]
chunk   {10} scripts.bundle.js, scripts.bundle.js.map (scripts) 409 kB {12} [initial] [rendered]
chunk   {11} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.11 MB [initial] [rendered]
chunk   {12} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.

Build success  but open browser to use url = http://localhost:4200  any browser to shock. help me please i don't, What's the problem?

**Comment by filipesilva** [comment]
I'm sorry, I don't understand what the problem is. Can you tell me what you see when you open the browser? Is there an error in the console?

**Comment by sreesindhusruthiyadavalli** [comment]
I have similar issue ng serve is success however when trying to open localhost:4200/ says  The system cannot communicate with the external server ( localhost ). 

Tried with 127.0.0.1 as well. 

In hosts.file the following is available.

#	127.0.0.1       localhost 
#	::1             localhost

**Comment by alan-agius4** [comment]
I'm sorry, but we can't cannot understand the problem.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
