### ISSUE TITLE
Configuring Sass file in angular-cli-build.js did not compile

### ISSUE THREAD

**Issue by colinshen** [angular/angular-cli#678]
```
angular-cli: 1.0.0-beta.1
node: 4.4.3
```
I dont know I configued the sass file from npm was correct.
```
vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/*.js',
      'es6-shim/es6-shim.js',
      'reflect-metadata/*.js',
      'rxjs/**/*.js',
      '@angular/**/*.js',
      '@salesforce-ux/design-system/scss/index.scss'
    ]
```
after compileing. in dist file it is still sass file, not css

**Comment by Codenator81** [comment]
```
npm install node-sass --save-dev
```
should help and you don`t need add that to angular-cli-build.js

**Comment by colinshen** [comment]
@Codenator81  I installed node-sass. without angular-cli-build.js. how can I use it?
```
styleUrls: [
    'uhccj-dashboard.component.css',
    '@salesforce-ux/design-system/scss/index.scss'
  ],
```
like this?

**Comment by Codenator81** [comment]
@colinshen  No it is compile automatically when you write 
```
ng serve
```
and compile if you write
```
ng build
```
as I read from doc`s Angular Cli scan files and compile without setting needed just install npm package for SCSS or LESS

**Comment by colinshen** [comment]
@Codenator81 thanks for your help. I got it.

**Comment by Bolza** [comment]
Then please guys could you fix the documentation https://github.com/angular/angular-cli#css-preprocessor-integration ? It stills says you should include `scss` files.

**Comment by YiniYin** [comment]
The doco is wrong! It does NOT make sense to set styleUrls: [my.scss] at all!

**Comment by filipesilva** [comment]
@Bolza @YiniYin the docs are current for the webpack version, which is still in testing and not tagged as latest. I've added a note here: https://github.com/angular/angular-cli/pull/1694

**Comment by daveo1001** [comment]
What's the current todo here?
did this `ng set defaults.styleExt scss`
then did this `styleUrls: ['./app.component.scss']` in my app.component

No errors but styles not happening.
Leaving it as `app.component.css` throws a webpack error b/c app.component.css doesn't exist.
