### ISSUE TITLE
AOT compilation fails with empty route path from static routes class

### ISSUE THREAD

**Issue by andreasrueedlinger** [angular/angular-cli#6782]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.3
node: 6.9.1
os: darwin x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4

### Repro steps.
We have a routes class which holds all the static routes strings to be used in routes configuration of angular and in all the router links:
```ts
export class RoutesPathRegistry {
  static foo = '';
  static bar = 'link'; 
}
```
Using this link in the routes setup breaks the AOT compilation with angular CLI:
```ts
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { RoutesPathRegistry } from 'app/modules/routes';
import { FooComponent } from './components/foo.component';
import { BarComponent } from './components/bar.component';

const appRoutes: Routes = [
  {
    path: RoutesPathRegistry.bar,
    component: BarComponent
  },
  {
    path: RoutesPathRegistry.foo,
    component: FooComponent,
    pathMatch: 'full'
  }
];

@NgModule({
  imports: [
    RouterModule.forRoot(appRoutes)
  ],
  exports: [
    RouterModule
  ]
})
export class AppRoutingModule {}
```

### The log given by the failure.
```
ERROR in Illegal state: symbol without members expected, but got {"filePath":"****/src/app/modules/routes/path-registry.ts","name":"RoutesPathRegistry","members":["foo"]}.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '****/src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
```

### Desired functionality.
Successful AOT compilation

**Comment by filipesilva** [comment]
This isn't something we support currently, but might in the future.

**Comment by andreasrueedlinger** [comment]
@filipesilva please note that it is not the indirection that is the problem but the empty string. All the other indirect routes paths (like bar in the example above) do not cause any problem and work as expected. Hence I don't see the link to #6784

**Comment by kichnan** [comment]
Thanks @filipesilva . Can you please suggest me an alternative to pull this off?

I have seen some articles on adding routes dynamically and replacing them using `router.resetConfig()`. It seems to work, for top-level routes (app-routing.module level), but can't find a way to do this for child routes, i.e. routes in a child module, esp. lazy loaded ones.

Any tip would be of great help.!

**Comment by filipesilva** [comment]
@andreasbhansen you're right, I think I misread these two issues. Given that other routes work, this might be a problem with `ngc` itself. Could you open an issue in https://github.com/angular/angular instead please?

@kichnan I'll reopen and answer your issue there.

**Comment by andreasrueedlinger** [comment]
@filipesilva thanks, since I did not know where the problem was I opened an issue in both places. Here is the corrsponding issue:
https://github.com/angular/angular/issues/17728

**Comment by andreasbhansen** [comment]
I think you tagged the wrong Andreas, @filipesilva :)

**Comment by filipesilva** [comment]
@andreasrueedlinger my bad, sorry about that :E
