### ISSUE TITLE
Cannot import json files when running ng test

### ISSUE THREAD

**Issue by pgrm** [angular/angular-cli#6786]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
````
@angular/cli: 1.1.3
node: 8.1.0
os: win32 x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
````

### Repro steps.
````
import sampleData from './data.json';

// check if sampleData is undefined or not - in ng serve it has the correct value, in ng test it's undefined
````

You can see more details in this repo - https://github.com/pgrm/angular-bug-import-json

- `npm start` - you should see the content of sample.json
- `npm test` - the exception will be thrown that it's undefined (the exception is just there to demonstrate that it's undefined)

### Desired functionality.
since I import the json file as a module, it should be imported the same way in tests, like it is done for the application to be served or compiled

**Comment by filipesilva** [comment]
I'll have a look but generally we don't really support loading anything but js/ts files as ES6 imports. It is inconsistent that it works in one case and not the other though.

**Comment by Juansasa** [comment]
You need to have typings for jso file. Put this to your typing.d.ts

`declare module '*.json' {
  const value: any;
  export default value;
}`

Then use `import * as sampleData from './data.json';`

**Comment by pgrm** [comment]
@Juansasa you can see in the repository I've referenced - https://github.com/pgrm/angular-bug-import-json/blob/master/src/typings.d.ts - I have exactly the same code you posted.

**Comment by larssn** [comment]
@Juansasa Doesn't seem to work. Webpack complains about it instead:

`Cannot find module './package.json'.`

**Comment by natcohen** [comment]
@filipesilva It's also working in `aot` but not regular build... any alternative solution to import json files?

**Comment by jwa107** [comment]
@natcohen  Are you saying that updating the version fixes this issue?

**Comment by jwa107** [comment]
@filipesilva If this is not supported, what is the proper way to import json files (say from node_modules)?

**Comment by clarkorz** [comment]
@Juansasa works for me until the latest version of `angular/cli` (1.6.2).

It seems that somehow this issue is related to this merge https://github.com/angular/angular-cli/commit/09177d1

This merge force to use `module: 'commonjs'` in `compilerOptions` of tsconfig. 

```
// Forcing commonjs seems to drastically improve rebuild speeds on webpack.
    // Dev builds on watch mode will set this option to true.
    if (wco.buildOptions.forceTsCommonjs) {
        options.compilerOptions.module = 'commonjs';
    }
```

And by default, `ng test` use `commonjs` either (see`src/app/tsconfig.spec.ts` in your project).

I don't know what is the difference between `commonjs` and `es2015`. Any idea why?

**Comment by NaLLiFFuNT** [comment]
I got similar issue however with aot compilation after having updated angular-cli to 1.6.7 from 1.1.3.
I've modified tsconfig.json having replaced compilerOptions with 

```xxx
"compilerOptions": {
    "module": "commonjs",
  },
```
after that i modify data.json import
```javascript

// from
import data2 from './data.json';

// with
import * as data2 from './data.json';
```
and everything works fine!

**Comment by sandrocsimas** [comment]
The same problem here using angular 6.
I created a library with the new command ````ng generate library````. In the new library component created I'm importing a json file in the same path of the library component.
When I try to build I get ````Cannot find module './palettes.json'````.
How to solve it?

**Comment by vishnu8** [comment]
can any one please help how to import json file in angular 6 library project. i tried all the possible values but wasnt able to import it... build error is "Module not found: Error: Can't resolve "

**Comment by sandrocsimas** [comment]
@vishnu8, I created a question in stackoverflow (https://stackoverflow.com/questions/51313388/cant-import-json-from-my-angular-library-component) but I'm still waiting for a responde there.

**Comment by Juansasa** [comment]
To clarify i've been using this trick for quite some time since Angular first released until now at version 6 everything just work.

**typings.d.ts**
`declare module '*.json' {
  const value: any;
  export default value;
}`

**Component import**
`import * as JSON from './file.json';`

**Comment by Juansasa** [comment]
[Angular 6 JSON import](https://github.com/Juansasa/Angular-6-JSON-import)

**Comment by sandrocsimas** [comment]
@Juansasa, could you please try to import in a library? ````ng generate library````
I created this repository but I can't make it work:
https://github.com/sandrocsimas/ngx-material-palette-picker

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
