### ISSUE TITLE
Webpack 3 integration

### ISSUE THREAD

**Issue by mydata** [angular/angular-cli#6787]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions.

node  7.9.0
npm 5.0.1
### Desired functionality.

Any palns to upgrade to Webpack 3 ? how the new release integration with webpack are normally being done?

**Comment by jgodi** [comment]
You can check it out here: https://github.com/angular/angular-cli/pull/6365

**Comment by filipesilva** [comment]
Closing as answered, thanks @jgodi.
