### ISSUE TITLE
Feature Request: Let me know if my Angular packages are out of sync

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#6790]
**Feature Request**
`ng version` shows me the Angular packages currently in use, it would be nice if the CLI threw a warning if they were out of sync.

Example:
> Your Angular packages are out of sync. @angular/platform-browser is version 4.2.3 but @angular/core is version 4.2.4. To fix this, run "<yarn|npm> <add|install> @angular/platform-browser@4.2.4"

**Comment by limpygnome** [comment]
This would be useful to know, but not sure this is not exclusive to Angular (but rather npm).

You may find the following package useful:
https://www.npmjs.com/package/npm-check-updates

**Comment by StephenFluin** [comment]
Thinking more about it, you @limpygnome is probably right, we should just rely on the package managers for this. That's what their job is, even if they don't do it perfectly today.
