### ISSUE TITLE
Community Request: Design a logo for the Angular CLI

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#6791]
The CLI is a really important part of the Angular platform, and loved by many developers in the community. It would be great if the project had a logo consistent with the rest of Angular!

The CLI team is busy building out the CLI and the Angular DevKit, and so it would be awesome to see the community come up with ideas, proposals, and recommendations to help the process along.

Reply to this issue and let's get this process started!

**Comment by shral** [comment]
I have e proposal or maybe just an Idea:

![angularcli](https://user-images.githubusercontent.com/7990614/27530684-09d7c75a-5a5a-11e7-9893-1395507feb2e.png)

**Comment by laco0416** [comment]
Like a console

![image](https://user-images.githubusercontent.com/1529180/27622376-ac5afdd6-5c11-11e7-8d69-95c74495cc17.png)

**Comment by shprink** [comment]
![angular_cli](https://user-images.githubusercontent.com/1388706/27625543-46a235c6-5be5-11e7-941c-e4a097377c3d.png)

![angular_cli_2](https://user-images.githubusercontent.com/1388706/27625553-49d8f61c-5be5-11e7-8774-0c319aa229c1.png)

![webp net-gifmaker](https://user-images.githubusercontent.com/1388706/27625556-4bc3db86-5be5-11e7-9f27-98a722d71385.gif)

**Comment by mgintrand** [comment]
<img src="https://user-images.githubusercontent.com/7585388/27627617-c44671a2-5bec-11e7-8c39-6758b743ebcb.png" width="250">

**Comment by shral** [comment]
![angular2](https://user-images.githubusercontent.com/7990614/27628596-d5afab90-5bef-11e7-9817-fc2ad73e18be.png)

**Comment by shral** [comment]
![angular3](https://user-images.githubusercontent.com/7990614/27629261-0f4ebc0e-5bf2-11e7-82a6-9c63f75df9f9.png)

**Comment by shral** [comment]
![angular4](https://user-images.githubusercontent.com/7990614/27629363-6333a384-5bf2-11e7-828d-94a2ad8e8c94.png)

**Comment by shral** [comment]
![angular5](https://user-images.githubusercontent.com/7990614/27629594-296e2948-5bf3-11e7-92cf-34e8a583b218.png)

**Comment by ValeryVS** [comment]
It is like two consoles and upside down angular.
(≧∀≦)

**Comment by webmaxru** [comment]
I created these two proposal keeping in mind:
1. Consistency
2. Recognizability even in icon size
3. Eye-candy factor

Please vote:

1. "Classic" terminal
![angular-cli-1](https://user-images.githubusercontent.com/1560278/27634617-32852246-5c04-11e7-8eb1-1a21c74d12a8.png)

**Comment by webmaxru** [comment]
2. "Styled" terminal
![angular-cli-2](https://user-images.githubusercontent.com/1560278/27634658-61fe8c06-5c04-11e7-880f-f93cf02ff718.png)

**Comment by hnrchrdl** [comment]
1.1

**Comment by saadbinamjad** [comment]
![angular-cli-logo](https://user-images.githubusercontent.com/9148799/27636989-d35548ec-5c2f-11e7-8add-7d68d8d82eee.png)
Great initative and great responses.  Here is my recomendation.

Thinking behind the logo: Since angular cli is core to angular development for many developers like us, thought CLI should be at core, bounded by the angular. (The edges of cli should match that of angular logo)

**Comment by webmaxru** [comment]
Some animations to support my proposal #1 (just for fun):
![angular-cli-animated-2](https://user-images.githubusercontent.com/1560278/27637937-cb4b9b24-5c11-11e7-949b-15c1e4cdb53c.gif)
![angular-cli-animated-1](https://user-images.githubusercontent.com/1560278/27637944-cfa5df36-5c11-11e7-8cb7-85be0017faf1.gif)

**Comment by ritz078** [comment]
Angular logo with CLI look.

![angular](https://user-images.githubusercontent.com/5389035/27638531-327adac0-5c31-11e7-8ec0-19a72ffb2f8d.png)

**Comment by shprink** [comment]
![group 2](https://user-images.githubusercontent.com/1388706/27639492-a789fb86-5c16-11e7-983f-6c94bf2e4eff.png)

**Comment by pratheekhegde** [comment]
![angular cli white](https://user-images.githubusercontent.com/11031124/27640284-78c8dd60-5c36-11e7-814c-4148245ed041.png)
Angular CLI Logo
![angular cli](https://user-images.githubusercontent.com/11031124/27640208-355c3d56-5c36-11e7-99bc-f1ae855bebcd.png)
Angular CLI Logo Black

**Comment by areai51** [comment]
![logo1](https://user-images.githubusercontent.com/357862/27640538-3c052784-5c37-11e7-82c2-d1b75901fd0f.png)
![logo2](https://user-images.githubusercontent.com/357862/27640539-3c0a9e08-5c37-11e7-83c5-fa8577c15160.png)

Keeping it simple, This allows for a consistent format if other officially supported tools want to have their own logos.

**Comment by anein** [comment]
My two cents. 
![angular cli](https://user-images.githubusercontent.com/435658/27642386-554e9c08-5c27-11e7-8aae-18fed9af64a3.png)

**Comment by ferretdayo** [comment]
It is similar to anein's Design...
![image](https://user-images.githubusercontent.com/5894431/27645354-d64725c6-5c60-11e7-9ed1-9a57cc34d001.png)

**Comment by PierreBresson** [comment]
![cli](https://user-images.githubusercontent.com/8709134/27646170-3c07e316-5c28-11e7-9134-ca90ca7621e7.png)

**Comment by maartentibau** [comment]
I don't really see the need for an actual logo for the CLI to be honest. Now in that matter.. we all know Angular has a red logo, Universal has a green one, Material is blueish, I would go with just a color like some of you already suggested and just stick with the A of Angular.. because we all know.. "It's just Angular".

**Comment by violetdama** [comment]
[Angular CLi.pdf](https://github.com/angular/angular-cli/files/1110682/Angular.CLi.pdf)

**Comment by violetdama** [comment]
![angular cli](https://user-images.githubusercontent.com/29764717/27668021-74a265a6-5c33-11e7-9a2d-000d09872286.jpg)

**Comment by violetdama** [comment]
let me know what you guys thinking! cheers!

**Comment by Brocco** [comment]
@violetdama I like that, nice work... also thanks for joining github to be able to contribute! Welcome!

**Comment by RichardSilveira** [comment]
![angular-logo-cli](https://user-images.githubusercontent.com/1668930/27670223-a6b5c47c-5c59-11e7-8946-19cc8ea24c3d.png)

**Comment by aboudard** [comment]
definitly the 1.1 from @webmaxru !

**Comment by Raincal** [comment]
![angular](https://user-images.githubusercontent.com/6279478/27683879-380cdcb6-5c8d-11e7-9138-6a13317bfc25.png)

**Comment by StephenFluin** [comment]
Someone just pointed me to this for inspiration: https://www.behance.net/gallery/53773741/Logo-trend-report-2017

**Comment by thisgeek** [comment]
Could contributors provide small (favicon sized) versions of the logo when posting? It would be good to see whether the design holds up with limited space, and whether it could be easily differentiated from _and_ also be associated with the angular logo at the most minimum scale.

**Comment by thisgeek** [comment]
We also might post only one logo version per comment. I very much like seeing alternates, but I'm finding it hard to use reactions to vote for my specific favorites when one comment has multiples.

**Comment by aboudard** [comment]
not that it does really matter, but @shprink is a nice guy, and he makes blinking logos, so ... yeah ... whatever

**Comment by msterba** [comment]
![angular cli logo](https://user-images.githubusercontent.com/12588436/27761341-4aa23c44-5e5a-11e7-8286-128667b8ad4f.png)

**Comment by webmaxru** [comment]
@thisgeek here is the demo of how https://github.com/angular/angular-cli/issues/6791#issuecomment-311630815 could look as an icon. Click the image to see non-scaled version (it's important to see actual pixels):
![icon-demo](https://user-images.githubusercontent.com/1560278/27792559-9927d4c2-5ffa-11e7-9c43-3b21f462a7fc.png)

**Comment by tytskyi** [comment]
Some experiments with logo looks really cool, but they do not survive under different resolutions. Logo should be recognizable and readable (if applicable) in different image sizes.

**Comment by thisgeek** [comment]
@webmaxru Beautiful context. (And I dig the icon.) Thank you.

**Comment by violetdama** [comment]
@tytskyi I strongly agree and I think the one I shared here is legible enough in different sizes.

**Comment by lordKnighton** [comment]
For a youtube video, I created this photo. Maybe you guys can use it to take inspiration for something if you want, Or not. 

-------
I really like the look of it, hope you guys will too. 
![ng4-cli](https://user-images.githubusercontent.com/1773260/28393758-7c8c2a7a-6c9d-11e7-8ace-2e1748d6fcf7.png)

video link -- [ClickME!](https://www.youtube.com/watch?v=PUyM2il8pYU)
Ps This isn't me pitching my video, if you think it is, then it is. Happy Coding 💯 😄

**Comment by kuncevic** [comment]
@webmaxru the logo with `> _` looking awesome, gonna use in my presentation.

**Comment by alan-agius4** [comment]
Hi, thank you all for pitching in. Some of these were truly inspiring.

**Comment by beeman** [comment]
For completeness sake, this is the logo now:

![https://angular.io/generated/images/marketing/concept-icons/cli.png](https://angular.io/generated/images/marketing/concept-icons/cli.png)

**Comment by Splaktar** [comment]
And you can get it and the other logos from https://angular.io/presskit
