### ISSUE TITLE
Add "Please wait..." When Dependencies are Being Installed

### ISSUE THREAD

**Issue by clarkio** [angular/angular-cli#6792]
**This is not a big deal, but I think it could be a small improvement for anyone new to the CLI.**

It would be helpful to have additional text when it gets to the step of installing dependencies; especially for someone that runs the CLI for the first time. I've gotten so used to seeing a progress animation or something of that nature to indicate the tool is working on something. I understand it may not be desirable to show an animation so some kind of message to the user indicating they should wait while it runs would be helpful.

I know that adding `--verbose` with the command is a solution, but again thinking of someone new who is most likely following some guide which doesn't include that option won't know to add it themselves.

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Repro steps.
1. Install the CLI
2. Run `ng new my-app`
3. Text isn't completely clear that progress is being made. `Installing packages for tooling via npm.`

### Desired functionality.
* Add `Please wait...` along with the `Installing packages for tooling via npm [or other package manager].` message.

### Mention any other details that might be useful.
I'd be happy to create a PR for this small change, but wanted to check with you all first before throwing that into the mix.

**Comment by jiverson** [comment]
dup of #5960

**Comment by filipesilva** [comment]
Closing as a duplicate, thanks @jiverson 👍
