### ISSUE TITLE
Running ng build with -prod discovers issues that are missed when running without the -prod switch.

### ISSUE THREAD

**Issue by etovian** [angular/angular-cli#6793]
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.2
node: 6.10.0
os: win32 x64
@angular/animations: 4.2.3
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/core: 4.2.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/router: 4.2.3
@angular/cli: 1.1.2
@angular/compiler-cli: 4.2.3

1. In an external html template, refer to a method that does not exist on the controller.
2. Run 'ng build'
3. Note that the reference to the non-existent method is not reported during the build.
4. Run 'ng build -prod'
5. Note that a compilation error results (eg: Property 'myMethod' does not exist on type 'MyComponent'.)

### The log given by the failure.
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prod',
1 verbose cli   '--scripts-prepend-node-path=auto' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle ng-app@0.0.0~preprod: ng-app@0.0.0
6 silly lifecycle ng-app@0.0.0~preprod: no script for preprod, continuing
7 info lifecycle ng-app@0.0.0~prod: ng-app@0.0.0
8 verbose lifecycle ng-app@0.0.0~prod: unsafe-perm in lifecycle true
9 verbose lifecycle ng-app@0.0.0~prod: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\workspace\projects\psp\web\ng-app\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\SafeNet\Authentication\SAC\x32;C:\Program Files\SafeNet\Authentication\SAC\x64;C:\Program Files\nodejs\;C:\Program Files\Apache\maven\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\migreen\AppData\Roaming\npm;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\
10 verbose lifecycle ng-app@0.0.0~prod: CWD: C:\workspace\projects\psp\web\ng-app
11 silly lifecycle ng-app@0.0.0~prod: Args: [ '/d /s /c', 'ng build -prod' ]
12 silly lifecycle ng-app@0.0.0~prod: Returned: code: 1  signal: null
13 info lifecycle ng-app@0.0.0~prod: Failed to exec prod script
14 verbose stack Error: ng-app@0.0.0 prod: `ng build -prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ng-app@0.0.0
16 verbose cwd C:\workspace\projects\psp\web\ng-app
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prod" "--scripts-prepend-node-path=auto"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error ng-app@0.0.0 prod: `ng build -prod`
22 error Exit status 1
23 error Failed at the ng-app@0.0.0 prod script 'ng build -prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ng-app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ng build -prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ng-app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ng-app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

### Desired functionality.
Compilation errors like this should be caught by 'ng build' whether or not it is run with the -prod switch.  Otherwise, errors that would easily be discovered at development time are not caught until the app is deployed for production.

**Comment by hccampos** [comment]
This is as designed. The angular AoT compiler which runs when you add the prod flag is very (extremely?) slow and is not, for that reason, run when in dev mode.

**Comment by etovian** [comment]
@hccampos So the _design_ is to allow certain bugs to escape notice until they break the production build?  If that is the design, then with all due respect to the contributors and their work, it is deficient.  The dev build certainly doesn't have to do all of the compiling that the -prod build does, but it should definitely catch this sort of thing.  And it did, once upon a time.  When I was using the release candidate, it caught this exact type of error.

**Comment by hccampos** [comment]
@etovian I totally agree with you. When I said "by design" I should have probably said "as expected" or something similar. The problem is that the AoT compiler is extremely slow (even without it I am already getting rebuilds that take longer than 30s and with it they take minutes) and apparently the team chose to turn it off in dev mode by default.

**Comment by filipesilva** [comment]
As @hccampos said, it is by design that AOT is turned off in development builds, for the reasons stated.

The Angular team is working on making the AOT compiler as fast normal TypeScript compilation as possible. The goal is that development builds will use AOT as well so that users are not caught by surprised with these errors, but rather catch them early on.

Meanwhile, you can also run `ng build --aot` to create AOT builds without doing all the other `--prod` work.
