### ISSUE TITLE
How to use reference paths/d.ts files?

### ISSUE THREAD

**Issue by doczoidberg** [angular/angular-cli#68]
I want to use d.ts files E.g.:
```
/// <reference path="./../../typings/breeze/breeze.d.ts" />
```
Webstorm and VS Code recognize the definitions but not the TS-Compiler of angular-cli?

**Comment by olimungo** [comment]
I have the same issue with jquery.d.ts. VS Code doesn't complain, but compiler do.

**Comment by anhallbe** [comment]
I'm having this issue as well. Although I'm new to TypeScript so I may be doing something wrong.

I fetched some definitions using tsd, and added this to my tsconfig.json:
   ```
"files": [
    "typings/tsd.d.ts"
  ]
```

My IDE (Atom, using the atom-typescript package) does not complain, but building it during 'ng serve' fails with a "Cannot find name ... " error.

**Comment by josephfinlayson** [comment]
Also having this issue!

**Comment by cexbrayat** [comment]
Same here: IDE is fine, but `ng serve` is broken if we use other typings (even if they are properly declared in `tsconfig.json` as the IDE pick them up).

Is there something else to configure?

**Comment by Brocco** [comment]
@cexbrayat were you trying with the version on npm or the latest version on master? The reason I ask is that we are overdue to cut a release and there have been some improvements around typings recently.

**Comment by cexbrayat** [comment]
We were on master at that time, I did not try since.

**Comment by hansl** [comment]
The Broccoli-Typescript plugin is being reworked entirely as part of our move to Broccoli 1.0.

This will be addressed as there are other typing bugs that we need to fix, and this is one of them.

**Comment by rimachaudhari** [comment]
/// <reference path="../typings/jquery/jquery.d.ts" />

i used thiss way ...and it worked

**Comment by rimachaudhari** [comment]
/// <reference path="../typings/jquery/jquery.d.ts" />

**Comment by rimachaudhari** [comment]
"    /// <reference path="../typings/jquery/jquery.d.ts" />    "
i used this without inverted commas outside and it worked for me

**Comment by rimachaudhari** [comment]
`  /// <reference path="../typings/jquery/jquery.d.ts" />  `

use this ..it works
