### ISSUE TITLE
Error while installing @angular/cli on AWS Ubuntu 16.04 server

### ISSUE THREAD

**Issue by X3QTO** [angular/angular-cli#6800]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
node v8.1.2
npm 5.0.3

### Repro steps.
Setup new AWS Ubuntu Server:  Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-d15a75c7

Then run commands below
```
sudo apt-get update

sudo apt-get install python -y

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential

sudo npm install node-gyp -g
sudo npm install -g @angular/cli

```

### The log given by the failure.

```
ubuntu@ip-172-31-5-23:~$ sudo npm install -g @angular/cli
/usr/bin/ng -> /usr/lib/node_modules/@angular/cli/bin/ng

> node-sass@4.5.3 install /usr/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:890:18)
    at sync (/usr/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor' }

> fsevents@1.1.2 install /usr/lib/node_modules/@angular/cli/node_modules/fsevents
> node install


> node-sass@4.5.3 postinstall /usr/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/nodejs /usr/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/nodejs',
gyp verb cli   '/usr/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.1.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.1.2
gyp verb command install [ '8.1.2' ]
gyp verb install input version string "8.1.2"
gyp verb install installing version: 8.1.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.1.2
gyp verb ensuring nodedir is created /home/ubuntu/.node-gyp/8.1.2
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/ubuntu/.node-gyp/8.1.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.1.2' ]
gyp verb install input version string "8.1.2"
gyp verb install installing version: 8.1.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.1.2
gyp verb ensuring nodedir is created /usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.1.2
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.1.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.1.2' ]
gyp verb install input version string "8.1.2"
gyp verb install installing version: 8.1.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.1.2
gyp verb ensuring nodedir is created /usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.1.2
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.1.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.1.2' ]
gyp verb install input version string "8.1.2"
gyp verb install installing version: 8.1.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.1.2
gyp verb ensuring nodedir is created /usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.1.2
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.1.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"

```
### Desired functionality.

Use case is automating deployment to AWS.  Would like to understand steps to avoid this error or for a fix.

### Mention any other details that might be useful.
The error keeps repeating.  Breaking out the error using Ctrl +C, and then reinstalling using:
`sudo npm install -g @angular/cli`
seems to work.

I can then run `ng new myproject`, run `npm install`, and `ng serve`.   
The problem seems to be this initial error which goes in a loop.

**Comment by filipesilva** [comment]
This seems to be a problem with installing https://github.com/sass/node-sass, which is one of the dependencies.

The problem most likely arises from the use of `sudo`, which is heavily discouraged while installing packages. Check out https://docs.npmjs.com/getting-started/fixing-npm-permissions to see how you can fix your permissions.

**Comment by X3QTO** [comment]
Yes this solved the problem.  thank you!

**Comment by FaroukMohameden** [comment]
Fixing the permissions as said at `https://docs.npmjs.com/getting-started/fixing-npm-permissions` does not fix the problem for me.

**Comment by Martin-Wegner** [comment]
@FaroukMohameden the Angular CLI npm install script is not very good... The problem is, that the installer script wants to put the symbolic link ng to /usr/bin/ so you need sudo... But with sudo you cannot install it because... the installer script is not very good ;) But don't worry, you can install it this way:

1.) Fix the permissions by changing the ownership and group of /usr/lib/node_modules/ to your user account.
2.) sudo npm i -g @angular/cli
3.) sudo rm -fr /usr/lib/node_modules/@angular/
4.) npm i -g @angular/cli

**Comment by Martin-Wegner** [comment]
@danindiana is this your problem: https://askubuntu.com/questions/533217/changing-ownership-of-folder-not-working ?

**Comment by FaroukMohameden** [comment]
@Martin-Wegner , thank u (y). I managed to install it using the first two steps you mentionned as root. I have to mention that the second step  `sudo npm i -g @angular/cli` took me to an infinite loop like in #1734. So i bypassed it using @totomz 's answer on the same issue e.g `sudo npm i -g --unsafe-perm @angular/cli`. And : yes, the script is not good at all !!

**Comment by X3QTO** [comment]
Per the [npm video](https://docs.npmjs.com/getting-started/fixing-npm-permissions), I chose option 2.  I use a different directory for npm globals.  This works without any issues for me.
```
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
echo "export PATH=~/.npm-global/bin:$PATH" >> ~/.profile
source ~/.profile
npm i -g @angular/cli
```

**Comment by Martin-Wegner** [comment]
@FaroukMohameden you mean the too many symbolic links loop? I get this loop when I run `sudo npm i -g @angular/cli` twice.

**Comment by FaroukMohameden** [comment]
@Martin-Wegner  i mean the loop in #17431 not #1734, sorry !!. And yes, it might be because of trying to install CLI twice.

**Comment by MiteshGandhi2893** [comment]
miteshs-MacBook-Pro:~ miteshgandhi$ sudo npm i -g @angular/cli
/Users/miteshgandhi/.npm-global/bin/ng -> /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/bin/ng

> fsevents@1.1.3 install /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@9.4.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/fsevents
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/fsevents
node-pre-gyp ERR! node -v v9.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)

> node-sass@4.7.2 install /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/darwin-x64-59 : { Error: EACCES: permission denied, mkdir '/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:905:18)
    at sync (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/vendor' }

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.7.2 postinstall /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.4.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)\n    at F (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)\n    at E (/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)\n    at /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16\n    at /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5\n    at /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.4.0
gyp verb command install [ '9.4.0' ]
gyp verb install input version string "9.4.0"
gyp verb install installing version: 9.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.4.0
gyp verb build dir attempting to create "build" dir: /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/build'
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/miteshgandhi/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 (node_modules/@angular/cli/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @angular/cli@1.6.5
added 1098 packages in 35.911s


**Hello, I am trying to install angular cli in Mac OS sierra 10.12.6 and I am getting the above-mentioned error.Please help me out**

**Comment by lakinmohapatra** [comment]
Use this command 
`sudo npm install -g @angular/cli@latest --unsafe-perm`

**Comment by estigon** [comment]
To avoid the loop. npm install node-sass then sudo npm i -g @angular/cli

**Comment by ovimughal** [comment]
If this doesn't work
`sudo npm install -g @angular/cli@latest --unsafe-perm`
surely this will work :)
`sudo chown -R root:root /usr/lib/node_modules/@angular/`
and then
`sudo npm install -g @angular/cli@latest`

**Comment by dimai3p** [comment]
> @FaroukMohameden the Angular CLI npm install script is not very good... The problem is, that the installer script wants to put the symbolic link `ng` to `/usr/bin/` so you need sudo... But with sudo you cannot install it because...the installer script is not very good ;) But don't worry, you can install it this way:
> 
> 1.) Fix the permissions by changing the ownership and group of `/usr/lib/node_modules/` to your user account: `sudo chown -r XXX /usr/lib/node_modules/` and `sudo chgrp -r XXX /usr/lib/node_modules/`
> 2.) `sudo npm i -g @angular/cli`
> 3.) `sudo rm -fr /usr/lib/node_modules/@angular/cli/`
> 4.) `sudo chown -r XXX /usr/lib/node_modules/@angular/`
> 5.) `sudo chgrp -r XXX /usr/lib/node_modules/@angular/`
> 6.) `npm i -g @angular/cli`

Thanks! 
But that still didnt solve it for me. 

After that I added:
- sudo chown user:group -R /home/<user>/my-project/
- cd my-project
- npm install
- npm start
