### ISSUE TITLE
skipCodeGeneration always inlines HTML templates

### ISSUE THREAD

**Issue by shaneholder** [angular/angular-cli#6801]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.3 (e)
node: 6.10.2
os: win32 x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4

### Repro steps.
ng new blat
ng eject
webpack // Build
view code in main.bunde.js verify HTML is inline
edit webpack.config.js set AotPlugin.skipCodeGeneration = false
webpack // Build
view code in main.bundle.js verify that HTML is still inlined but code is drastically different

### The log given by the failure.
Unexpected results, I expected one of the settings to leave the templatUrl code intact and replace it with a require('app.component.html').

### Desired functionality.
Perhaps this is just my misconception of what skipCodeGeneration does but the documentation says that it replaces templateUrl with template: require().  So I was expecting skipCodeGeneration = true to not replace templateUrl with the template and instead load it from the server.  Possibly this isn't a bug but a clarification point in the documentation if it is expected that HTML assets will always become inlined.

**Comment by filipesilva** [comment]
`skipCodeGeneration` controls whether or not you get AOT compilation. Templates are always inlined.
