### ISSUE TITLE
Missing environment variable HOME

### ISSUE THREAD

**Issue by harikrishnan-u01** [angular/angular-cli#6806]
The ng build is failing.

PFB the commands:

```
npm install -g @angular/cli
ng -v
ng build --prod
```

PFB the error logs:

```
node_modules/@angular/cli/models/config.js:15
     [exec]         throw new Error('Missing environment variable ' + envHomeName);
     [exec]         ^
     [exec] 
     [exec] Error: Missing environment variable HOME
```

These errors started occurring from today (6/26/2017) and was not there previously.
Can you kindly help fix this?

Thanks,
Hari

**Comment by josuesbla** [comment]
I have the same issue!

**Comment by josuesbla** [comment]
@harikrishnan-u01 
It seems like I had an issue with my HOME env var.

By running ```echo $HOME``` I correctly get the right home ("/Users/username"), but I didn't get any HOME variable when running this:

```
node
process.env
```
I had to export again my HOME var (```export HOME="/Users/username"```)

Check this: https://nodejs.org/api/process.html#process_process_env

I hope you can solve the issue as me.

**Comment by harikrishnan-u01** [comment]
Hi @josuesbla ,

Thank you for the response.

Why is this HOME env variable required for angular/cli? I was able to build the angular/cli project until 6/23/2017 (Friday) without any issues. This error started appearing only from today (6/26/2017).

Also where should the HOME env variable be specified? is it inside the environment.prod.ts file?
I am facing this issue when building from the Jenkins server. So what should be the value of this HOME regards to Jenkins?

Thanks,
Hari

**Comment by filipesilva** [comment]
This seems related to our global configuration loading logic: https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/models/config.ts#L15-L22. Perhaps we shouldn't require it to be set.

**Comment by clydin** [comment]
PR #6812 should address the concern; as well as being more robust in general.

**Comment by harikrishnan-u01** [comment]
Thank you @filipesilva and @clydin for the information.

Am waiting for the PR to be merged. So this will be available in release 1.1.4?
Right now our Jenkins job is failing and we are blocked because of this.

Regards,
Hari

**Comment by filipesilva** [comment]
I had not seen your PR yet @clydin, thank you and merged.

@harikrishnan-u01 yes it will be out on the next release.

**Comment by harikrishnan-u01** [comment]
Hi  @filipesilva, @clydin, 

Issue still exists. Tried with release 1.3.0-beta.0 

[exec] Missing environment variable HOME
     [exec] Error: Missing environment variable HOME
     [exec]     at getUserHome (/home/jenkins/workspace/abc/node_modules/@angular/cli/models/config.js:15:15)
     [exec]     at Function.globalConfigFilePath (/home/jenkins/workspace/abc/node_modules/@angular/cli/models/config.js:44:42)
     [exec]     at Function.fromProject (/home/jenkins/workspace/abc/node_modules/@angular/cli/models/config.js:85:34)
     [exec]     at Object.<anonymous> (/home/jenkins/workspace/abc/node_modules/@angular/cli/commands/build.js:7:35)
     [exec]     at Module._compile (module.js:570:32)
     [exec]     at Object.Module._extensions..js (module.js:579:10)
     [exec]     at Module.load (module.js:487:32)
     [exec]     at tryModuleLoad (module.js:446:12)
     [exec]     at Function.Module._load (module.js:438:3)
     [exec]     at Module.require (module.js:497:17)

Can you help?

Thanks,
Hari

**Comment by clydin** [comment]
The function `getUserHome` no longer exists in the latest version.
Please ensure the version being used is 1.3.0-beta.0 at both the global and project levels.

**Comment by harikrishnan-u01** [comment]
@clydin ,

Thank you. Its working now after I changed both global and project level versions.

Thanks,
Hari

**Comment by filipesilva** [comment]
Closing as fixed by https://github.com/angular/angular-cli/pull/6812.
