### ISSUE TITLE
Include Polyfills in test configs

### ISSUE THREAD

**Issue by kpaxton** [angular/angular-cli#6808]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
CLI: 1.1.3 - see same issue in anything 1.1+
node: 6.10.1
os: linux x64
Angular 4.2.3

### Repro steps.
Have a "polyfills": 'polyfills.ts' set in the .angularCli.json.
Have 'polyfills.ts' listed in the karma.conf.json - files array.

### The log given by the failure.
'Unexpected token import' at src/polyfills.ts

### Desired functionality.
no errors and the polyfills included in the tests that are run

### Mention any other details that might be useful.
I noticed in the cli/models/webpack-configs/common.js you have a block for 
```
if(appConfig.polyfills){
    entryPoints['polyfills'] ...
}
```
And in the cli/models/webpack-configs/test.js you don't have a similar block. So if a user needs to include global polyfills for their tests, they cannot do so easily. If that polyfills file is a .ts file, it will get this same error.

**Comment by filipesilva** [comment]
You don't need to add `polyfills` to the karma config array. It's always been loaded automatically, even before 1.1.
