### ISSUE TITLE
add whitelist to angular-cli.json

### ISSUE THREAD

**Issue by premiumwd** [angular/angular-cli#6809]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

webpack has an ignore piece, can we add this to angular-cli.json for build?
 
```
externals: [nodeExternals({
  whitelist: [

]
```

**Comment by filipesilva** [comment]
Can you tell me more about what the usecase is for it?

**Comment by premiumwd** [comment]
resolution to ngx-translate using angular universal https://github.com/evertonrobertoauler/cli-universal-demo/issues/14. @mmathys commented on May 15.

You can do it like this (in webpack.config.js):
```
externals: [nodeExternals({
  whitelist: [
    /^@angular\/material/,
    /^@ngx-translate\/core/
  ]
})],
```

**Comment by filipesilva** [comment]
Angular CLI doesn't support Universal currently, so this isn't something we want to add in isolation.
