### ISSUE TITLE
Innocuous change to imports in app.module.ts causes prod build error: 'router-outlet' is not a known element

### ISSUE THREAD

**Issue by hughsw** [angular/angular-cli#6819]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report
```

### Versions.
```
@angular/cli: 1.1.3
node: 8.1.2
os: darwin x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4
```

### Repro steps.
```
ng new -v -sg --routing ang4
cd ang4
```
Edit `app.module.ts` to concat nothing (or something) to the list of imports, so that imports reads as follows:
```
  imports: [
    BrowserModule,
    AppRoutingModule
  ].concat([]),
```

Try a prod build:
```
$(npm bin)/ng build -prod
```

### The log given by the failure.

```
ERROR in Template parse errors:
'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
</ul>

[ERROR ->]<router-outlet></router-outlet>
"): ng:///Users/hugh/work/gs/ng/ang4/src/app/app.component.html@20:0

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/hugh/work/gs/ng/ang4/src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
```

### Desired functionality.

I would like the prod build (and all builds) to allow module files to execute simple Typescript Array and Object methods with the collections of components etc that go into building modules.

### Mention any other details that might be useful.
* Does not happen in development build.
* Did not occur in Angular 2

**Comment by hughsw** [comment]
The problem of using `.concat` in NgModule declaration is also discussed here:  https://github.com/angular/vscode-ng-language-service/issues/80

**Comment by hughsw** [comment]
I am working on replacing numerous `.concat()` in the project's resource files with the spread operator, `...`.  The error messages due to the non-AOT-friendly use of `concat` are obscure, to say the least!

If this gets reclassified as a feature request, my request is that errors due to AOT failure be made much clearer!

**Comment by hughsw** [comment]
For the record, here are a couple of other obscure error messages that arise from use of `concat()` inside module declarations:
```
ERROR in Unexpected value 'null' imported by the module 'AppModule in /Users/hugh/work/gs/kira/kiraclient/src/app/app.module.ts'

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/hugh/work/gs/kira/kiraclient/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

```
ERROR in Cannot use 'in' operator to search for 'providers' in null
```

And this last one (not really obscure) due to incorrectly using the spread operator, `...`, on a non-array symbol (encountered while fixing layers of nested `concat()` in a large set of Effects):
```
ERROR in /Users/hugh/work/gs/kira/kiraclient/src/app/flux/effects.ts (14,6): Type '{ ngModule: typeof EffectsModule; providers: (Type<any> | { provide: OpaqueToken; useExisting: Ty...' is not an array type.
```

**Comment by filipesilva** [comment]
Heya, I appreciate your feedback and I agree that these errors are not very straightforward to figure out, but the right repository to file this issue is https://github.com/angular/angular. That is where `ngc` (the Angular AOT compiler) resides and where the error ultimately comes from.

Could you reopen there please?
