### ISSUE TITLE
Test Command doesn't support custom output path

### ISSUE THREAD

**Issue by JonCubed** [angular/angular-cli#682]
*1. Problem*

There is currently no way to specify a custom output-path while running *ng test*, ember-cli supports *--path* and *ng test --help* also lists the flag as available however when you run it with flag you get 

    The option '--path' is not registered with the test command. Run `ng test --help` for a list of supported options.

The *dist/* folder is also hard-coded in angular-cli [test command](https://github.com/angular/angular-cli/blob/5b0896520531f1862f72c7a4e40f89e51f006616/addon/ng2/commands/test.js).

I am using ASP.NET Core which expects public files to be in wwwroot/, I am currently building to wwwroot/ using .ember-cli with "output-path"  

*2. What I expect to see*

Using a flag in cli I should be able to specify a custom output-path, also I should be able to set a default in .angular-cli to use instead of *dist/*

*3. How to resolve it*
I think test command would need to be updated to accept flag and get value from angular-cli.json. angular-cli.json schema would also need to be updated

I've made a pull request of what I think would probably need to change #681

**Comment by filipesilva** [comment]
Closed in favor of https://github.com/angular/angular-cli/issues/682
