### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by roqueorts** [angular/angular-cli#6821]
I get an error installing angular-cli

### Versions.
node --version v4.2.3
 npm --version 3.8.8
  Windows 7

### Repro steps.
$ npm install -g angular-cli
npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\rortscam\AppData\Roaming\npm\ng -> C:\Users\rortscam\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
C:\Users\rortscam\AppData\Roaming\npm
`-- angular-cli@1.0.0-beta.28.3
`-- UNMET PEER DEPENDENCY rxjs@^5.0.1

npm WARN optional Skipping failed optional dependency /angular-cli/chokidar/fsevents:
**npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2**
npm WARN @angular/core@2.4.10 requires a peer of rxjs@^5.0.1 but none was installed.

**Comment by rageshvr** [comment]
Both the CLI and generated project have dependencies that require Node 6.9.0 or higher, together with NPM 3 or higher.

[https://github.com/angular/angular-cli#prerequisites](https://github.com/angular/angular-cli#prerequisites)

`npm install -g @angular/cli`

**Comment by roqueorts** [comment]
Get same error with node 6.11.0 and npm 3.8.8

 npm install -g angular-cli
npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been
renamed to @angular/cli. Please update your dependencies.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or
higher to avoid a RegExp DoS issue
C:\Users\rortscam\AppData\Roaming\npm\ng ->
C:\Users\rortscam\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
C:\Users\rortscam\AppData\Roaming\npm
`-- angular-cli@1.0.0-beta.28.3
  `-- UNMET PEER DEPENDENCY rxjs@^5.0.1

npm WARN optional Skipping failed optional dependency
/angular-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture:
fsevents@1.1.2
npm WARN @angular/core@2.4.10 requires a peer of rxjs@^5.0.1 but none was
installed.


2017-06-28 12:09 GMT+02:00 Ragesh <notifications@github.com>:

**Comment by rageshvr** [comment]
Are you getting any error related to node-gyp? This is most probably something that is mentioned here https://github.com/angular/angular-cli/issues/1560#issuecomment-240913794

@filipesilva

**Comment by roqueorts** [comment]
That's the complete log:
C:\Users\rortscam\AppData\Roaming\npm\ng -> C:\Users\rortscam\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
C:\Users\rortscam\AppData\Roaming\npm
`-- @angular/cli@1.1.3

npm WARN optional Skipping failed optional dependency /@angular/cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2

**Comment by rageshvr** [comment]
This seems to be an optional dependency warning only,  See if you have angular-cli installed with below command:

`ng -v`

--no-optional flag with npm install, should get rid of those though.
`npm install --no-optional @angular/cli`

**Comment by filipesilva** [comment]
Yeah that is just a warning, and is fine. It's a dependency that's only really needed for OSX systems. Thanks to @rageshvr for helping out!
