### ISSUE TITLE
ng serve does not detect file changes in a folder watched by Dropbox

### ISSUE THREAD

**Issue by gsdefender** [angular/angular-cli#6823]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.1.3
node: 6.11.0
os: darwin x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4

Dropbox 29.4.20
O.S. OS X Yosemite

### Repro steps.

Create a project inside a Dropbox controlled folder.
Run ng serve.
Modify a file inside the project directory. No change detected.

Do the same in a folder that is not under Dropbox control and it works.

**Comment by filipesilva** [comment]
This sounds like https://github.com/webpack/webpack/issues/2258, which was moved to https://github.com/webpack/watchpack/issues/42. Basically the parenthesis break serve.
