### ISSUE TITLE
Sourcemaps for tests broken since 1.1.2

### ISSUE THREAD

**Issue by Ristaaf** [angular/angular-cli#6824]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.3
node: 7.9.0
os: win32 x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4

### Repro steps.
* ng new smtest
* cd smtest

* edit app.component.spec.ts to add a debugger statement

* ng test

* open chrome devtools and reload page

* the debugger statement is hit but it is in the main.bundle.js file, and no ts sourcefile is to be found anywhere!

### Desired functionality.
The app.component.spec.ts file should be available for debugging in chrome devtools sources.

### Mention any other details that might be useful.
This works fine in angular cli 1.1.1, the app.component.spec.ts file can there be found in context->webpack://->C://smtest->src->app

This was most probably broken by the commit "@angular/cli: correct sourcemap source paths (cf66e6b)"

**Comment by filipesilva** [comment]
There's another report of this in https://github.com/angular/angular-cli/issues/6737 so I will close this one as a duplicate.
