### ISSUE TITLE
ngh is not recognised as an internal or external command

### ISSUE THREAD

**Issue by kzrfaisal** [angular/angular-cli#6825]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by Splaktar** [comment]
Please fill out the bug report sections before submitting the issue. There is not enough information here to investigate.

**Comment by filipesilva** [comment]
We don't provide a `ngh` command, I think you're thinking of some other package.

**Comment by TamerHussien** [comment]
You should install this package first
npm install -g angular-cli-ghpages
