### ISSUE TITLE
typescript 2.4 support

### ISSUE THREAD

**Issue by xnnkmd** [angular/angular-cli#6827]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.1.3

### Desired functionality.
Angular-cli should support typescript 2.4 (just released yesterday). Right now angular-cli is locked down to max v2.3

**Comment by delasteve** [comment]
There's an issue with `rxjs` right now preventing upgrading the CLI to use TypeScript 2.4. I read that the 6.x versions work, but that is in alpha and could lead to some other issues. ⚠️ Use caution if you intend on upgrading early. ⚠️ 

Expect the CLI to upgrade its dependencies when things are stable again.

Tracking: https://github.com/ReactiveX/rxjs/issues/2539

**Comment by moniuch** [comment]
@delasteve ...by which issue I was bitten today. And I thought about the following one:
Given that even a minor version release of TypeScript can break things, wouldn't it be wise to generate package json without the `^` character specifically for TS?

**Comment by tytskyi** [comment]
@moniuch cli already generates package with `~`. Looks like people are trying to update it manually or had old `package.json`

see https://github.com/angular/angular-cli/blob/v1.2.0/packages/%40angular/cli/blueprints/ng/files/package.json#L50

**Comment by xnnkmd** [comment]
@delasteve  @filipesilva RxJS 5.4.2 has now been published with the fix for Typescript 2.4.1

**Comment by MarkPieszak** [comment]
At least from my testing, if you upgrade rxjs to `5.4.2` you should be able to use the CLI with TS `2.4`. 

Just remember that you're upgrading at your own risk as I don't believe it has been fully tested &/or is support at the moment.

**Comment by smoke** [comment]
I think the referenced issue https://github.com/ReactiveX/rxjs/issues/2539 is now fixed, so are there any plans now?

**Comment by OdaiTu** [comment]
how to update my typescript to latest version ? 
what is the command using npm ?

**Comment by jbojcic1** [comment]
So is it possible to use typescript >= 2.4 now? I have cli 1.4.6 and it still requires ts < 2.4

**Comment by MarkPieszak** [comment]
Try CLI 1.5+

**Comment by jbojcic1** [comment]
@MarkPieszak tried it. I still get the same warning.
