### ISSUE TITLE
Feat: Support more e2e test environment

### ISSUE THREAD

**Issue by tamascsaba** [angular/angular-cli#6828]
Support other e2e test runner environments like:

- TestCafe
- CodeceptJS
- CasperJS
- Nightwatch.js

**Comment by delasteve** [comment]
As mentioned with other requests of this nature, the CLI won't be integrating other testing frameworks at this time (both for `e2e` and `test` commands). It will allow, however, to customize this in the future through user specified build pipelines and custom blueprints via plugins.

Related: 

https://github.com/angular/angular-cli/issues/4071
https://github.com/angular/angular-cli/issues/4543

**Comment by filipesilva** [comment]
@delasteve is right that the current plan isn't to add direct support but to allow extensibility. Regarding e2e runners however, by design they don't really care much about how the app is built. You should be able to use any of those today with `ng serve`.

**Comment by tamascsaba** [comment]
@filipesilva, @delasteve thx. It is a correct quick response :+1:
