### ISSUE TITLE
Add flag to "ng test" to specify whether or not it should build the code first

### ISSUE THREAD

**Issue by dwally89** [angular/angular-cli#6829]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
`ng --version` outputs 3.10.10
`node --version` outputs v6.10.1
`npm --version` outputs v3.10.10
Windows 7

### Repro steps.
N/A

### The log given by the failure.
N/A

### Desired functionality.
On our CI server we run `ng build`, followed by `ng test`. This causes the code to be built twice and significantly slows down the build plan . It would be good if `ng test` could be given a flag to specify whether or not the code should be built or not.

### Mention any other details that might be useful.
N/A

**Comment by filipesilva** [comment]
That is unfortunately not how the build system in the CLI works. The testing pipeline and the building pipeline are different and need to support different things. It is not possible to reuse the built artifacts.

**Comment by dwally89** [comment]
@filipesilva , please could you explain?
In a standard Javascript (non-Angular) project, I assume it's possible to run the tests with Karma without any build process necessary.
In an Angular project, surely the Typescript is compiled to Javascript, which is then run by Karma? `ng build` produces Javascript files - can't these be run by Karma without having to rebuild the Typescript again?

**Comment by swilliams-a3digital** [comment]
In my node typescript projects I can run npm test on the last build.  Having to rebuild every time you run tests is incredibly slow.
