### ISSUE TITLE
Images (assets) of third party npm - how to use?

### ISSUE THREAD

**Issue by alvipeo** [angular/angular-cli#683]
Say, I use some third-party npm module and it has icons set (svg). What's the best way of using it in a project? I mean should I copy it manually into Public and then reference? Not much automagic in it :)

Seriously, it there a better solution?

**Comment by alvipeo** [comment]
ok, added the needed file to the angular-cli-build.js and it worked. Is this how it should be used?

**Comment by zackarychapple** [comment]
@alvipeo anything you want to access from the dist directory has to get added to the angular-cli-build.js.  It does support globbing.

**Comment by alvipeo** [comment]
Right, that's what I did. I was thinking how I would automate this, I guess it's not really possible without some change from npm, etc.
