### ISSUE TITLE
Installing Angular CLI failing due to rename operation

### ISSUE THREAD

**Issue by lou-harmon** [angular/angular-cli#6831]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
node version: 6.11.0
npm version: 3.10.10
Windows 7 x64

### Repro steps.
After reinstalling node, I verified that node, and npm were installed.  I then ran this command for installing angular-cli:

npm install -g @angular/cli@1.1.0

I have tried running this install with administrative rights to no avail.  I've also tried running the install command with the force flag (-f) and still haven't had success.

### The log given by the failure.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path ...\AppData\Roaming\npm\node_modules\angular-cli
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename '...\AppData
\Roaming\npm\node_modules\angular-cli' -> '...\AppData\Roaming\npm\
node_modules\.angular-cli.DELETE' 

Any guidance would be greatly appreciated!

**Comment by lou-harmon** [comment]
Found a fix:

I uninstalled node version 6.11.0 and reinstalled node version 6.10.3 and then ran the angular-cli installation command:

npm install -g @angular/cli@1.1.0 

The installation was a success.  I have no idea why this would be the case, but I hope this helps someone in the future!

**Comment by filipesilva** [comment]
Unsure why you had the problem in the first place but it seemed to be npm related. Glad to hear you got it sorted.
