### ISSUE TITLE
@angular/cli imports a library that is not permissively licensed.

### ISSUE THREAD

**Issue by krotscheck** [angular/angular-cli#6832]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report
```

### Versions.
1.0.3

### Repro steps.
The regenerator-runtime library, imported by common-tags/babel-runtime, is licensed under Facebook's BSD-With-Patent-Termination license.

```
> yarn why regenerator-runtime

info This module exists because "@angular/cli#common-tags#babel-runtime" depends on it.
info Disk size without dependencies: "44kB"
info Disk size with unique dependencies: "44kB"
info Disk size with transitive dependencies: "44kB"
info Number of shared dependencies: 0
```
External ticket opened here: https://github.com/babel/babel/issues/5898

### Desired functionality.
@angular/cli and its dependencies should be permissively licensed.

**Comment by filipesilva** [comment]
I just checked the my CLI install, and my generated project and it seems to be MIT licensed:

```
kamik@T460p MINGW64 /d/work/angular-cli (master)
$ npm ls regenerator-runtime
@angular/cli@1.2.0-rc.1 D:\work\angular-cli
+-- common-tags@1.4.0
| `-- babel-runtime@6.23.0
|   `-- regenerator-runtime@0.10.5

kamik@T460p MINGW64 /d/work/angular-cli (master)
$ npm info regenerator-runtime@0.10.5 license
MIT
```

Am I missing something here? 

I'd like to add that we actually test licenses as well: https://github.com/angular/angular-cli/blob/master/scripts/test-licenses.js

**Comment by krotscheck** [comment]
Right - so regenerator-runtime lives in the `regenerator` project here, and doesn't actually contain its own license:

https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime

Looking at git-blame, and history, it appears that the license field itself was added during project creation. However, it is a part of the regenerator project as a whole, and the entire repository is licensed via these two file:

https://github.com/facebook/regenerator/blob/master/LICENSE
https://github.com/facebook/regenerator/blob/master/PATENTS

So, while the published package says one thing (which the test script is picking up), the "authoritative" source says something else, which is what our lawyers are going off of. As IANAL, I'm guessing that they made the decision that the more restrictive of the two is accurate.

It would probably be worth reaching out to the regenerator team for a clarification, and a separation of the projects if that's the necessary. Let me go ask.

**Comment by krotscheck** [comment]
Asked for clarification here: https://github.com/facebook/regenerator/issues/298

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
