### ISSUE TITLE
How to create angular-cli project in nested directory

### ISSUE THREAD

**Issue by nopantsmonkey** [angular/angular-cli#6835]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Versions.
@angular/cli: 1.1.3
node: 8.1.2
os: darwin x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4

### Repro steps.
my project directory is
build/
backend/
webapp/
package.json
bower.json

and i want to start a project using angular-cli in webapp/project
right now angular-cli is creating the project in root directory because package.json is in root directory and i don't want to create another package.json in webapp/project directory is their any way i can create a angular-cli project without a package.json in webapp/project

**Comment by filipesilva** [comment]
You should be able to use the `--directory` flag but there is a bug preventing it (https://github.com/angular/angular-cli/issues/6803). A `package.json` is always necessary though, for the project dependencies and dependency resolve.
