### ISSUE TITLE
webpack failed to compile

### ISSUE THREAD

**Issue by vlrprbttst** [angular/angular-cli#6836]
bug report

### Versions.
Node 8.1.3
Windows 10 creators update
ng --version gives this: http://prntscr.com/fpjbi1

### Repro steps.
on npm start i get this error log: http://prntscr.com/fpjeuk - basically, everything fails. I'm just getting started with angular so please be kind :)

### The log given by the failure.
ERROR in multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localhost:4200/' in 'C:\xampp\htdocs\angular2-getstarted\firstngapp'
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
 
ERROR in multi ./src/styles.css
Module not found: Error: Can't resolve 'style-loader' in 'C:\xampp\htdocs\angular2-getstarted\firstngapp'
 @ multi ./src/styles.css
 
ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'raw-loader' in 'C:\xampp\htdocs\angular2-getstarted\firstngapp':
  Error: Can't resolve 'raw-loader' in 'C:\xampp\htdocs\angular2-getstarted\firstngapp'
  
  - compiler.js:76 
    [npm]/[angular-cli]/[html-webpack-plugin]/lib/compiler.js:76:16
 - Compiler.js:280 Compiler.<anonymous>
    [npm]/[angular-cli]/[webpack]/lib/Compiler.js:280:10
  
  - Compiler.js:480 
    [npm]/[angular-cli]/[webpack]/lib/Compiler.js:480:13
  
  - Tapable.js:138 next
    [npm]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:138:11
  
  - CachePlugin.js:62 Compiler.<anonymous>
    [npm]/[angular-cli]/[webpack]/lib/CachePlugin.js:62:5
  

  - Tapable.js:142 Compiler.applyPluginsAsyncSeries
    [npm]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:142:13
  
  - Compiler.js:477 
    [npm]/[angular-cli]/[webpack]/lib/Compiler.js:477:10
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:615 self.applyPluginsAsync.err
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:615:19
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:606 self.applyPluginsAsync.err
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:606:11
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:601 self.applyPluginsAsync.err
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:601:10
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:597 sealPart2
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:597:9
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [npm]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:131:46
- Compilation.js:545 Compilation.seal
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:545:8
  
  - Compiler.js:474 
    [npm]/[angular-cli]/[webpack]/lib/Compiler.js:474:16
  
  - Tapable.js:225 
    [npm]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:225:11

  
  - Compilation.js:452 _addModuleChain
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:452:11
  
  - Compilation.js:345 Compilation.errorAndCallback
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:345:4
  
  - Compilation.js:362 moduleFactory.create
    [npm]/[angular-cli]/[webpack]/lib/Compilation.js:362:12
  
  - NormalModuleFactory.js:234 
    [npm]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:234:19
  
  - NormalModuleFactory.js:59 onDoneResolving
    [npm]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:59:20
  
  - NormalModuleFactory.js:183 
    [npm]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:183:21
  
  - async.js:3861 
    [npm]/[angular-cli]/[async]/dist/async.js:3861:9
  
  - async.js:421 
    [npm]/[angular-cli]/[async]/dist/async.js:421:16
  
  - async.js:996 iteratorCallback
    [npm]/[angular-cli]/[async]/dist/async.js:996:13
  
  - async.js:906 
    [npm]/[angular-cli]/[async]/dist/async.js:906:16

- async.js:1071 
    [npm]/[angular-cli]/[async]/dist/async.js:1071:13
  
  - NormalModuleFactory.js:262 
    [npm]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:262:19
  
  - Resolver.js:70 onResolved
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:70:11
  
  - createInnerCallback.js:31 loggingCallbackWrapper

    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19
  
  - Resolver.js:138 afterInnerCallback
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:138:10
  
  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19
  
  - Tapable.js:181 Resolver.applyPluginsAsyncSeriesBailResult1
    [npm]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:181:46
  
  - Resolver.js:125 innerCallback
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:125:19
  
  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19
  
  - Tapable.js:283 
    [npm]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:283:15
  
  - UnsafeCachePlugin.js:38 
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/UnsafeCachePlugin.js:38:4
  
  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19
  
  - Resolver.js:138 afterInnerCallback
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:138:10
  
  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19

- Tapable.js:283 
    [npm]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:283:15
  
  - UnsafeCachePlugin.js:38 
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/UnsafeCachePlugin.js:38:4
  
  - createInnerCallback.js:31 loggingCallbackWrapper

    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19
  
  - Resolver.js:138 afterInnerCallback
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:138:10
  
  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19
  
  - Tapable.js:181 Resolver.applyPluginsAsyncSeriesBailResult1
    [npm]/[angular-cli]/[webpack]/[tapable]/lib/Tapable.js:181:46
  
  - Resolver.js:125 innerCallback
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:125:19
  
  - createInnerCallback.js:31 loggingCallbackWrapper
    [npm]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:31:19
  
 
 
ERROR in ./src/main.ts
Module build failed: Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\angular2-getstarted\firstngapp\node_modules\@ngtools\webpack\src\index.js:5:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)

at require (internal/module.js:11:18)
    at loadLoader (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModule.js:129:2)
    at NormalModule.build (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModule.js:180:15)
    at Compilation.buildModule (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compilation.js:127:10)
    at factoryCallback (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compilation.js:304:11)
    at C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleFactory.js:242:4
    at C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleFactory.js:93:13
    at C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\tapable\lib\Tapable.js:204:11
    at NormalModuleFactory.<anonymous> (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\CompatibilityPlugin.js:51:4)
    at C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\tapable\lib\Tapable.js:206:14

    at NormalModuleFactory.<anonymous> (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleReplacementPlugin.js:37:11)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\tapable\lib\Tapable.js:208:13)
    at onDoneResolving (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleFactory.js:68:11)
    at onDoneResolving (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleFactory.js:189:6)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
 
ERROR in ./src/polyfills.ts
Module build failed: Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\angular2-getstarted\firstngapp\node_modules\@ngtools\webpack\src\index.js:5:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModule.js:129:2)
    at NormalModule.build (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModule.js:180:15)
    at Compilation.buildModule (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compilation.js:127:10)
    at factoryCallback (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compilation.js:304:11)
    at C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleFactory.js:242:4
    at C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleFactory.js:93:13
    at C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\tapable\lib\Tapable.js:204:11
at NormalModuleFactory.<anonymous> (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\CompatibilityPlugin.js:51:4)
    at C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\tapable\lib\Tapable.js:206:14
    at NormalModuleFactory.<anonymous> (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleReplacementPlugin.js:37:11)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\tapable\lib\Tapable.js:208:13)
    at onDoneResolving (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleFactory.js:68:11)
    at onDoneResolving (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleFactory.js:189:6)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
 
ERROR in ./src/polyfills.ts
Module build failed: Error: Cannot find module 'reflect-metadata'

    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\angular2-getstarted\firstngapp\node_modules\@ngtools\webpack\src\index.js:5:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModule.js:129:2)
    at NormalModule.build (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModule.js:180:15)
    at Compilation.buildModule (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compilation.js:127:10)
    at factoryCallback (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compilation.js:304:11)
    at C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleFactory.js:242:4
    at C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleFactory.js:93:13
    at C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\tapable\lib\Tapable.js:204:11
    at NormalModuleFactory.<anonymous> (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\CompatibilityPlugin.js:51:4)
    at C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\tapable\lib\Tapable.js:206:14
    at NormalModuleFactory.<anonymous> (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleReplacementPlugin.js:37:11)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\tapable\lib\Tapable.js:208:13)
    at onDoneResolving (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleFactory.js:68:11)
    at onDoneResolving (C:\Users\Valerio\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\NormalModuleFactory.js:189:6)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ multi ./src/polyfills.ts
webpack: Failed to compile.

**Comment by filipesilva** [comment]
Heya, you're using an old version that isn't supported anymore. As the message states, the package isn't `angular-cli` anymore but `@angular/cli`.

You can find some guidance on how to uninstall the old one and install the new one in https://github.com/angular/angular-cli/wiki/stories-1.0-update#angularcli. 

The rest of that guide only really matters if you had an existing app, and it sounds to me that you were just making a new one. After getting the new version, create a new project and everything should be fine.

Hope this helps!
