### ISSUE TITLE
downgrade from angular 4 to angular2 using cli

### ISSUE THREAD

**Issue by pankajsri03** [angular/angular-cli#6847]
I am currently using angular 4 with Material 2. Since angular 4 is not compatible with material 2 , I need to degrade my app from 4 to 2. I developed the app using cli. Are there commands to degrade app from 4 to 2 using cli?

**Comment by grizzm0** [comment]
Upgrade your material2 version. Angular4 has been supported since beta6 I think.

**Comment by vucu** [comment]
"ERROR in MdDialog is not an NgModule"
Probably has to downgrade to 2

**Comment by grizzm0** [comment]
No, you don't want to downgrade. If you do you'll be stuck with an old version of angular and you'd also be stuck on material2-beta.5. Upgrade to latest version of material2 and read the changelog to migrate.

Anyhow, this is not a support forum. Please use stackoverflow for such questions in the future.

**Comment by ddimaria** [comment]
What version of Angular Material are you using?

**Comment by Brocco** [comment]
This is a support question best intended for a site like stackoverflow.

That being said, I highly suggest updating material and not downgrading Angular.

**Comment by kevinofficial95** [comment]
If you want to install this specific version of the angular cli you have to use this command:

npm install -g @angular/cli@1.0.0

To check available versions: npm view @angular/cli versions
