### ISSUE TITLE
Getting error while installing @angular/cli globally 

### ISSUE THREAD

**Issue by kartik1001** [angular/angular-cli#6858]
I am getting bellow  error when i runs the npm instll -g @angular/cli in command prompt 

Iprocess PC@iProRaghu MINGW64 /e/Angular2
$ npm install -g @angular/cli
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\IPROCE~1\AppData\Local\Temp\npm-2024-d921c875\registry.npmjs.org\pify\-\pify-3.0.0.tgz.4199653531' -> 'C:\Users\IPROCE~1\AppData\Local\Temp\npm-2024-d921c875\registry.npmjs.org\pify\-\pify-3.0.0.tgz'
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by deebloo** [comment]
@kartik1001 this seems like an NPM issue rather then a cli issue

**Comment by Brocco** [comment]
I agree with @deebloo please check through npm documentation to resolve this issue. Good luck!
