### ISSUE TITLE
Can supply mutil AotPlugin?

### ISSUE THREAD

**Issue by keyiis** [angular/angular-cli#6859]
### Versions.
"@ngtools/webpack": "^1.3.0",

### Repro steps.
My app has mutil entry,so has mutil child app,ngtools/webpack can supply mutil AotPlugin?like below
```
plugins: [
    new AotPlugin({
      tsConfigPath: helpers.root('tsconfig.aot.json'),
      entryModule: helpers.rootAngular('a.module#AModule')
    }),
   new AotPlugin({
      tsConfigPath: helpers.root('tsconfig.aot.json'),
      entryModule: helpers.rootAngular('b.module#BModule')
    }),
]
```

**Comment by mcgri** [comment]
Hi Guys
I have the same question. Is it possible to pass multiple ng2 apps/main modules via AotPlugin?

**Comment by sqwk** [comment]
I tried something like:

            new ngToolsWebpack.AngularCompilerPlugin({
                tsConfigPath: helpers.root('tsconfig.json'),
                entryModule: helpers.root('src', '[name]', 'app', 'app.module#AppModule'),
            }),

but that obviously does not work. Has anyone found a workaround so far?

**Comment by mgechev** [comment]
@keyiis you can experiment with this using the ngx-build-plus package. It'll allow you to extend our webpack config. Please open a new issue if I'm missing anything from your use case.
