### ISSUE TITLE
ng build --prod UglifyJs failure

### ISSUE THREAD

**Issue by joaogarin** [angular/angular-cli#6863]
- [ X] bug report

### Versions.
@angular/cli: 1.1.1
node: 6.9.3
os: darwin x64
@angular/animations: 4.2.2
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/core: 4.2.2
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic: 4.2.2
@angular/router: 4.2.2
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.2
@angular/language-service: 4.2.2

### Repro steps.
Use a package that contains default parameters

### The log given by the failure.
ERROR in vendor.d600eae1111f8d3f3292.bundle.js from UglifyJs
Unexpected token operator «=», expected punc «,» [/Library/WebServer/Documents/contenta/contenta_angular/~/d8-
jsonapi-querystring/index.js:39,0][vendor.d600eae1111f8d3f3292.bundle.js:28577,47]

### Desired functionality.
Not break.

### Mention any other details that might be useful.

 the issue is related to https://github.com/angular/angular-cli/issues/5741. I am using a package that exposes es6 and potentially some es7 code, including default parameters.

Cli seems to use UglifyJs without passing it to es5 is that possible? Why does it break on code using default parameters, that is my main question. And what can be done inside the cli (or in my project, or even in the npm package) to go around it.

Thanks for the info

**Comment by leocaseiro** [comment]
Perhaps if we use `uglify-es`?

**Comment by joaogarin** [comment]
Yeah this was an issue on the package. as it was not being properly transpiled before npm publish.talked to the author, the package now properly transpiles default parameters and all works fine.

**Comment by alirezamirian** [comment]
I'm also getting 

> ```
> ERROR in main.d6c91c76952d3513d43f.bundle.js from UglifyJs
> Unexpected token: name (i) [main.d6c91c76952d3513d43f.bundle.js:232,8]
> ```

It seems dependency to UglifyJs is only via html-webpack-plugin:

> ```
> +-- @angular/cli@1.2.1
> | `-- html-webpack-plugin@2.29.0
> |   `-- html-minifier@3.5.2
> |     `-- uglify-js@3.0.25
> ```

**Comment by MoxxNull** [comment]
Same here..
