### ISSUE TITLE
use command ng build --prod and ng build --prod --aot,come to the same thing

### ISSUE THREAD

**Issue by DC921115** [angular/angular-cli#6868]
### Bug Report or Feature Request (mark with an `x`)
```
   "ng": "ng",
    "build": "ng build --prod --aot",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
```

### Versions.
angular-cli: 1.0.0-beta.28.3
node: 8.0.0
os: win32 x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.0.0-beta.28.3
@angular/compiler-cli: 4.2.5

### Repro steps.
I want to use this angular-cli for AOT,but when I use this command "ng build --prod" or "ng build -- prod --aot",they come to same things;The two file sizes are the same;

And angular-cli need to set somethings for --aot ?

**Comment by 17cupsofcoffee** [comment]
`--prod` turns on AOT, you don't need to pass both options. See this section of the docs: https://github.com/angular/angular-cli/wiki/build#--dev-vs---prod-builds

**Comment by trotyl** [comment]
The detail of `-dev` and `-prod` has been documentated in [Wiki here](https://github.com/angular/angular-cli/wiki/build#--dev-vs---prod-builds):

Flag | --dev | --prod
-- | -- | --
--aot | false | true
--environment | dev | prod
--output-hashing | media | all
--sourcemaps | true | false
--extract-css | false | true

`--prod` indeed contains the `--aot true` option.

PS: `--dev` and `--prod` are wrong usage, but works for now, https://github.com/angular/angular-cli/issues/6383 is tracking on that.

**Comment by Brocco** [comment]
@17cupsofcoffee is correct, turning on `--prod` automatically turns on `--aot`. Closing this issue.

Side note: personally, I feel that 17 ☕️ is a bit extreme, but to each their own.
see what I mean: ☕️☕️☕️☕️☕️☕️☕️☕️☕️☕️☕️☕️☕️☕️☕️☕️☕️

**Comment by light24bulbs** [comment]
isn't angular 5 supposed to be AOT on by default?

**Comment by 17cupsofcoffee** [comment]
@light24bulbs See https://github.com/angular/angular-cli/issues/8259

**Comment by farzan1122** [comment]
wqq
