### ISSUE TITLE
File change not detected

### ISSUE THREAD

**Issue by rsaenen** [angular/angular-cli#6871]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.0
node: 8.1.3
os: linux x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/platform-server: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.5
@angular/language-service: 4.2.5

### Repro steps.
I have 2 VM:
* Linux version 4.4.0-83-generic (buildd@lgw01-29) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) with Mate 1.12.1  
* Linux version 4.10.0-26-generic (buildd@lcy01-09) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) with Mate 1.18.0.

The first one has any problem with ng/cli.
The second one has the following issue:
* File change not detected by webpack

I tried:
* to delete node_modules, delete package-lock, npm cache clear, npm install on both VM
* different version of ng/cli
* new install of the second VM

### Mention any other details that might be useful.
Package.json and source code is the same for both VM.

**Comment by tcuprak** [comment]
I had the same problem on a linux machine.   The underlying issue in my case was that the default inotify settings in Linux were too low to support the number of files being watched for changes.  See this link for the solution that worked for me:

https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

**Comment by rsaenen** [comment]
It solves my issue, thanks a lot @tcuprak !
