### ISSUE TITLE
feat: add option to preload scripts

### ISSUE THREAD

**Issue by tzachov** [angular/angular-cli#6879]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.1.0
node: 6.11.0
os: win32 x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.1.0
@angular/compiler-cli: 4.2.5
@angular/language-service: 4.2.5

Add preload tags to top of head so when it's time to render the scripts they will already be available:
```HTML
<link rel="preload" href="inline.bb4197794bf69eaa73c9.bundle.js" as="script" />
<link rel="preload" href="polyfills.2f7e9ecfe8b9aff0ee3c.bundle.js" as="script" />
<link rel="preload" href="vendor.fcca9f06444d9ba285a3.bundle.js" as="script" />
<link rel="preload" href="main.85970eb66d0c38647a73.bundle.js" as="script" />
```

We could also add `defer` to script tags (should have no effect on performance but will pass Google Insight):
```HTML
<script type="text/javascript" defer src="inline.bb4197794bf69eaa73c9.bundle.js"></script>
<script type="text/javascript" defer src="polyfills.2f7e9ecfe8b9aff0ee3c.bundle.js"></script>
<script type="text/javascript" defer src="vendor.fcca9f06444d9ba285a3.bundle.js"></script>
<script type="text/javascript" defer src="main.85970eb66d0c38647a73.bundle.js"></script>
```

**Comment by clydin** [comment]
Please see PR https://github.com/angular/angular-cli/pull/6634

**Comment by Brocco** [comment]
The conversation about this feature request is taking place on the PR mentioned above, closing this in favor of that conversation.
