### ISSUE TITLE
typings.d.ts declares module:{id:string} conflicting with node

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#688]
If using node in the same project as the CLI the declaration of `declare var module:{id:string};` in `src/typings.d.ts` causes a type error.

**Comment by hansl** [comment]
You should use a separate typings file for node, since you don't want to mix node and browser typings.

**Comment by erwin16** [comment]
@hansl. I don't see how to do it...   Developing an Angular2 app w client and server , I have the following file structure

myaoo
   |___.  client
             |__ src
                   |___ app
                            |__ <anular2 components ts files>
                            |__. typings.d.ts
             L_.server
                       |__ app.js
