### ISSUE TITLE
Add model class creation 

### ISSUE THREAD

**Issue by mattsp** [angular/angular-cli#6883]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.2.0
node: 6.6.0
os: win32 x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.5
@angular/language-service: 4.2.5

### Desired functionality.
Posibility to create a class model look like xxx.model.ts and xxxx.model.spec.ts via ng generate command

### Mention any other details that might be useful.
May be we could reused ng generate class with a new flag -model or create a new generate method look like ng generate model

**Comment by intellix** [comment]
```
ng g class blah.model

**Comment by mattsp** [comment]
Thanks, i have discovered this way  few second after issue creation
