### ISSUE TITLE
ng2-fan module in my angular project

### ISSUE THREAD

**Issue by ali1tokan** [angular/angular-cli#6886]
###the issue
```
while fallowing the steps to use ng2-fan in my angular project 
i get the following error in my console:
 compiler.es5.js:1540 Uncaught Error: Unexpected value 'FanMenuModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
and when compiling the error:
Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in C:/project name/node_modules/ng2-fan-menu/node_modules/@angular/core/core.d.ts, resolving symbol FanMenuModule in C:/project name/node_modules/ng2-fan-menu/menu.module.d.ts, resolving symbol FanMenuModule in C:/project name/node_modules/ng2-fan-menu/menu.module.d.ts

```

here is my packages verions:
@angular/cli: 1.1.0
node: 8.0.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.2.2
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3
-->

###package.jason

{
  "name": "ngelec10.0",
  "version": "0.0.0",
  "main": "main.js",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --base-href C:/Users/ALPHA/Documents/angular/ngelec10.0/dist/",
    "electron": "electron .",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.2.2",
    "@angular/material": "^2.0.0-beta.7",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@angular2-material/button": "^2.0.0-alpha.8-3",
    "@angular2-material/card": "^2.0.0-alpha.8-3",
    "@angular2-material/core": "^2.0.0-alpha.8-3",
    "@angular2-material/icon": "^2.0.0-alpha.8-3",
    "core-js": "^2.4.1",
    "cors": "^2.8.3",
    "dotenv": "^4.0.0",
    "ember-cli-cors": "0.0.2",
    "hammerjs": "^2.0.8",
    "ng2-fan-menu": "^1.0.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.1.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "electron": "^1.6.10",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

**Comment by deebloo** [comment]
this sounds like a problem with that fan module

**Comment by ali1tokan** [comment]
the problem is i set up a new project and it worked... so the only solution is to migrate all the work
