### ISSUE TITLE
Angular-cli + Material2 

### ISSUE THREAD

**Issue by ubiqore** [angular/angular-cli#689]
i could not follow wiki pages for integration of Material2 into angular-cli to make it work.
specially the change into system-config.ts ...

So here for informationabout  what i did inside the system-config.ts : 

 ( this : only for **checkbox**) 

/** Map relative paths to URLs. */
const map: any = {
      '@angular2-material': 'vendor/@angular2-material'
    
};

/** User packages configuration. */
const packages: any = {
   '@angular2-material/core': {
        format: 'cjs',
        defaultExtension: 'js',
        main: 'core.js'
    },
    '@angular2-material/checkbox': {
        format: 'cjs',
        defaultExtension: 'js',
        main: 'checkbox.js'
    }
};

**Comment by gelidus** [comment]
@ubiqore look into this: https://github.com/kara/puppy-love/blob/master/src/system-config.ts

**Comment by ubiqore** [comment]
@gelidus : merci !

**Comment by hansl** [comment]
Seems like it's fixed. Clsoing.

**Comment by maxime1992** [comment]
Just in case anyone need an answer about that I opened a similar issue and there's the solution
https://github.com/angular/angular-cli/issues/738
