### ISSUE TITLE
ng-build should compile files into static folder

### ISSUE THREAD

**Issue by viennv1709** [angular/angular-cli#6896]
ng-build should compile files into (`static` or `assets`) folder and put compiled files into specific folder for example and should also create manifest files for caching: After building app structure of build folder as follow.
```
build
|____assets
|      |_____js
|      |_____css
|      |_____fonts
|      |_____images
|
|____index.html
```

**Comment by Brocco** [comment]
@viennv1709 we appreciate your suggestion, but the output structure is not likely to change much. If you do have a strong case for making a change, please present those reasons in a new issue for discussion. (please follow the new issue template when creating a new issue).
