### ISSUE TITLE
Using angular-cli for creating libraries for angular

### ISSUE THREAD

**Issue by gioragutt** [angular/angular-cli#6897]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality.

I've always thought about what it takes to create a library for angular. I'm not really sure about what the structure of a project should be when you publish something to NPM.
What I thought was that maybe `angular-cli` would have a new command, perhaps `ng new-lib`, that would create a new project that is structured in a way that would allow people to publish their libraries to npm easily. Personally, I don't know the structure of such a project, as I stated before, but I assume you must have some best practices regarding such a process, so perhaps if there was such a command, it would:

* help people understand what it takes to make a npm package that they can distribute
* ensure that libraries will be correctly structured and organized
* ease creating new libraries, whether small or large, for all people.

I'm working on getting an offline npm repository for my company, and it would really help if there was an easy way to share angular-related libraries between people here.

**Comment by adamlubek** [comment]
I'd love that too!

**Comment by adamlubek** [comment]
I'd love that too!

**Comment by devoto13** [comment]
Duplicate of #1692.

Official position is:

> Addendum: We are in the process of adding custom template support to the CLI, and with it another tool that can be used to generate just templates but outside the CLI. We will consider having a scaffold for basic library projects, but it will not be part of the Angular CLI.

Please, use #6510 for further discussions.

Also this [talk](https://www.youtube.com/watch?v=unICbsPGFIA) from ng-conf discusses some basics.

**Comment by gioragutt** [comment]
@devoto13 thanks for explanation and link man, appreciated!
