### ISSUE TITLE
SCSS Compile problem: The tag is endowed with the wrong attribute ?

### ISSUE THREAD

**Issue by Eusen** [angular/angular-cli#6898]
- [x] bug report -> please search issues before submitting

```
> ng --version
@angular/cli: 1.1.3
node: 6.10.3
os: win32 x64
```

I added a component: SplashComponent, like this:
```
@Component({
  selector: 'page-splash',
  templateUrl: 'splash.html',
  styleUrls: ['splash.scss']
})
export class SplashComponent {
}
```
you can see selector is page-splash
but in scss:
```
page-splash {
    ....
}
```
It doesn't work!

Then I saw the style tags in the Chrome:
```
<style>
page-splash[_ngcontent-c1]   .scroll-content[_ngcontent-c1] {
  background-image: url(splash.d63b0b2b8679d146cafc.png);
  background-size: 100% 100%; }
</style>
```
And page-splash tag :
```
<page-splash _nghost-c1 class="ion-page show-page" style="z-index: 100;">
    <ion-content _ngcontent-c1 class="page-splash content content-ios" no-bounce="" scroll="false">
    </ion-content>
</page-splash>
```
Why _ngcontent-c1 in ion-content tag, 
but after scss compiling, _ngcontent-c1 belongs to page-splash tag ???
Why not page-splash[_nghost-c1] ???

**Comment by Eusen** [comment]
@Component({
  selector: 'page-splash',
  templateUrl: 'splash.html',
  styleUrls: ['splash.scss'],
  encapsulation: ViewEncapsulation.None,
})
Add encapsulation, it do not generate [_ngcontent-c1] in scss.
Although this method works, the scss generated is really strange...

**Comment by Brocco** [comment]
This is not a CLI issue, so I will be closing it.

The answer you're looking for is to set styles on that component you can remove `encapsulation: ViewEncapsulation.None` and put the styles you wish applied to the entire component using `:host` this represents the host DOM element which in this case will be `<page-splash>...</page-splash>`

```
// splash.scss
:host {
  border: 5px solid red;
  background: pink
}
```

Note: please follow the selector example and not the CSS styles provided, LOL.
