### ISSUE TITLE
Remove ./... from the route generator

### ISSUE THREAD

**Issue by gelidus** [angular/angular-cli#690]
The `/path/...` is no longer necessary and breaks the new router with `cannot match any route` message. This needs to be only `/path`

**Comment by hansl** [comment]
What version of the CLI are you on?

**Comment by gelidus** [comment]
angular-cli: 1.0.0-beta.1
node: 5.11.1
os: linux x64

**Comment by filipesilva** [comment]
I believe this was since fixed. Please reopen if I am wrong.

**Comment by gelidus** [comment]
fixed
