### ISSUE TITLE
CHANGELOG.md is missing

### ISSUE THREAD

**Issue by RonnieRocket147** [angular/angular-cli#6900]
https://github.com/angular/angular-cli/blob/master/CHANGELOG.md

Referenced from the README.md

**Comment by maxime1992** [comment]
You now have to use https://github.com/angular/angular-cli/releases

Changelog has been removed on purpose

**Comment by BenRacicot** [comment]
Maybe we can replace the 404 with it and perhaps much more prominent on the main angular-cli page?

**Comment by maxime1992** [comment]
No you can't replace the 404 page with it, you'd have to make a redirect and it would be on Github side.

I saw it on the changelog so I think it was there for few days/weeks and now changelog has been removed.

Agree that it might be written somewhere as devs are (probably) used to take a look into this changelog.

**Comment by intellix** [comment]
Can be closed due to: https://github.com/angular/angular-cli/pull/6908

**Comment by ccadieux** [comment]
"Changelog has been removed on purpose"

What is that purpose? All other angular libraries have the CHANGELOG.md. I find it very useful. Why was it removed? I don't see any discussion or reference to a why it was removed. An explanation would be good.

**Comment by devoto13** [comment]
@ccadieux It's now powered by [GitHub Releases](https://github.com/angular/angular-cli/releases). You can find exactly same information there.

**Comment by Brocco** [comment]
As stated above by a few people... the changelog file is no longer being maintained... the same information is available via the github release feature located [here](https://github.com/angular/angular-cli/releases).

**Comment by codethief** [comment]
How about creating a `CHANGELOG.md` file which tells the reader to go to the GitHub releases page? That way one at least doesn't have to google to find the changelog (which is precisely how I arrived here).
