### ISSUE TITLE
Lazy load modules not being bundled

### ISSUE THREAD

**Issue by ashkank83** [angular/angular-cli#6901]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Angular CLI version 1.0.0
MACOS Sierra 
### Repro steps.
**Simplified Scenario:**

A. User Logs in

B. Server will authorise the user and also send back the accessible routes i.e. :

    {
      new {
        itemID = 1,
          name = "Users",
          parent = "Administration",
          icon = "??",
          path = "user",
          loadChildren = "./adm-user/adm-user.module#AdmUserModule"
        //"../adm-user/adm-user.module#AdmUserModule"
      },
      new {
        itemID = 1,
          name = "Roles",
          parent = "Administration",
          icon = "??",

          path = "role",
          loadChildren = "../adm-user/adm-useaar.module#AdmRoleModule"
      }
    }

C. My Angular code uses the returned values to manipulate the routerConfig and add the returned routes.

**Issue:** It looks like Angular CLI (WebPack) ng server and ng build module are not creating any bundles for the AdmUserModule and AdmRoleModule. I guess this is because there is no reference to these in the code and it's being created dynamically.

* Note: when I hard code the routes and build I get more bundles created and everything works fine

### Desired functionality.
Cli/Webpack giving the functionality to either create bundles for all modules available or if this is not possible. Being able to create individual bundles per module manually.

**Comment by mgechev** [comment]
@ashkank83 can you still reproduce this issue? The lazy-loaded modules should be bundled into separate chunks.

**Comment by ashkank83** [comment]
@mgechev Thanks a lot for the response. TBH, I gave up on Angular since and recreated the same in React (Please don't get me wrong, I'm Not saying one is better than the other). I know they're both (Create React App & Angular-CLI) using webpack and maybe as you said the issue is solved here as well now. Thanks

**Comment by ashkank83** [comment]
If there is solution for it, might be helpful to Angular community to post it [here](https://stackoverflow.com/questions/44843509/angular-cli-webpack-lazy-loading-of-dynamically-created-routes) as well.
I had a few messages and comments asking for solutions

**Comment by mgechev** [comment]
Thanks for the quick follow up!
