### ISSUE TITLE
Duplicate modules entry after running ng eject

### ISSUE THREAD

**Issue by BioPhoton** [angular/angular-cli#6902]
### Bug Report
```
- [x] bug report
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.0 (e)
node: 6.9.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

### Repro steps.
1. start a project with ng new
2. run ng eject
3. open the webpack.config.js
4. find following in the exports:  
```
...
 "modules": [
      "./node_modules",
      "./node_modules"
    ]
...
```

### The log given by the failure.
No log given

### Desired functionality.
I guess the second entry for node_modules is redundant.

### Mention any other details that might be useful.
All useful details mentioned

**Comment by clydin** [comment]
eject functionality is no longer available in the latest version (6.0+).  For custom webpack configurations the following unofficial add-on is a suggested solution: https://github.com/manfredsteyer/ngx-build-plus
