### ISSUE TITLE
Change the schema.js in npm module dynamicaly

### ISSUE THREAD

**Issue by vinittcs** [angular/angular-cli#6905]
Hi, I am changing the schema.js file manually and it works fine. But
I want to implement : this._children[name_1] = this._createChildProperty(name_1, value ? value[name_1] : null, forward && forward.children ? forward.children[name_1] : null, propertySchema);
in my node modules automatically using ng build through gradle. I am download node v6.9.2 and running npm install and build using gradle task. I get the same error.
Please suggest. Is it a version issue or something else?

**Comment by hansl** [comment]
What error do you see? What package are you trying to use and modify? From what I understand you're trying to change the code of the `@ngtools/json-schema` package, but are you tryin to fix a bug/issue? Or is it more of a new feature?

It is unadvised to modify the files in `node_modules`. You should always build those files from our source and install using `npm install`.

Closing this issue as I don't think there's anything we can do to help, but if you're explaining what you're trying to do we might be able to point you in the right direction. Cheers!
