### ISSUE TITLE
App packages generated with yarn get deleted by npm

### ISSUE THREAD

**Issue by bogdancar** [angular/angular-cli#6910]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli 1.2.0
yarn 0.27.5
npm 5.1.0
node 8.1.3
Windows 10

### Repro steps.
1. use yarn as the package manager `ng set --global packageManager=yarn`
2. generate the new app `ng new app_name`
3. install package with npm into solution `npm i find-phone-model`
4. npm installs 1 package and removes 882:
```
npm notice created a lockfile as package-lock.json. You should commit this file.
+ find-phone-model@1.0.0
added 1 package and removed 882 packages in 15.211s
```

### The log given by the failure.
```
npm notice created a lockfile as package-lock.json. You should commit this file.
+ find-phone-model@1.0.0
added 1 package and removed 882 packages in 15.211s
```

### Desired functionality.
To install the new package and let the installed packages there.

### Mention any other details that might be useful.
This looks like a bug of npm, not one of @angular/cli. I raised a [bug on npm](https://github.com/npm/npm/issues/17644) for this, but I post this here for you to acknowledge the bug existence and maybe is something on @angular/cli side when generating the solution with yarn to fix so that npm interprets correctly the information after.

**Comment by Brocco** [comment]
Thanks for letting the team and community know.
