### ISSUE TITLE
unable to set breakpoint in spec.ts code for debugging

### ISSUE THREAD

**Issue by skk2142** [angular/angular-cli#6914]
I'm using angular2 cli and am following the test debugging instructions in the [official documentation](https://angular.io/guide/testing#test-debugging). I'm able to search for the spec.ts source files which are in the app folder and set break points. However, I'm not able to do the same for the test files for components in other folder. The tests do run but I'm not able to find the source file in the chrome browser. Shall I edit some config file? I've tried to add the source files manually to the source in chrome but that doesn't help in setting the breakpoint. Any help is very much appreciated.

**Comment by Brocco** [comment]
Looks like this should be resolved with PR #6862 but I will leave this open for @filipesilva to confirm.

**Comment by devoto13** [comment]
@skk2142 Are you trying to set breakpoint in one of the libraries in your `node_modules`? If so it's probably not supported, because CLI currently ignores source maps for third-party libraries.

**Comment by filipesilva** [comment]
There are currently some bugs with app sourcemaps in `ng test` that https://github.com/angular/angular-cli/pull/6862 and https://github.com/angular/angular-cli/pull/6968 should address, but as @devoto13 mentioned we don't offer sourcemap support for files in `node_modules`. There is a feature request for that in https://github.com/angular/angular-cli/issues/5477.
