### ISSUE TITLE
Error while Creating new component

### ISSUE THREAD

**Issue by dani32112** [angular/angular-cli#6915]
i got an error while creating a new component using ng g component <componentname>
W
D:\vega\ClientApp\app\components>ng g component newform
![directorystructure](https://user-images.githubusercontent.com/21985636/27946940-5778a1bc-630d-11e7-81dd-0d24ddf56256.png)

installing component
Error locating module for declaration
        SilentError: No module files found

**Comment by grizzm0** [comment]
It's looking for app.module.ts and you've renamed the file.

**Comment by shyhshiunli** [comment]
i got the same situation, use command "dotnet new angular" reference from Hanselman (https://www.hanselman.com/blog/dotnetNewAngularAndDotnetNewReact.aspx), whatever macOS or Windows, default to split into three module like @dani32112 post picture(client, server and shared), if i add typescript file(app.module.ts), the command "ng g c newComponent" will success

**Comment by grizzm0** [comment]
AngularCLI has support for multiple apps in angular-cli.json. You might want to use that instead. You can then use the --app argument while using the ng command.

**Comment by Brocco** [comment]
The suggestion for multiple apps is a good one by @grizzm0.

For the short-term you can use `--skip-import` which will prevent the CLI for looking for the closest module. Or you can specify which module you would like to import into by using `--module`.

Both of those options are documented [here](https://github.com/angular/angular-cli/wiki/generate-component).
