### ISSUE TITLE
[Improvement] Bundling Strategy

### ISSUE THREAD

**Issue by amcdnl** [angular/angular-cli#692]
**Improvement**
I spoke with @hansl and @Brocco at NGCONF regarding a different strategy for bundling builds.

I have implemented a bundler that given a [route definition](https://github.com/swimlane-contrib/angular1-systemjs-seed/blob/master/src/app/routes.json) file will use a directed graph alog to determine the most optimal way of which to package your application.

**Example**
So take the following: 

![example](https://raw.githubusercontent.com/swimlane-contrib/systemjs-route-bundler/master/assets/tree.png)

the bundler would identify overlap and optimize the output creating a new microbundle:

![result](https://raw.githubusercontent.com/swimlane-contrib/systemjs-route-bundler/master/assets/result.png)

**Resources**
Project: [SystemJS Route Bundler](https://github.com/swimlane-contrib/systemjs-route-bundler)
Example Project: [Angular1 SystemJS Seed](https://github.com/swimlane-contrib/angular1-systemjs-seed)

**Comment by filipesilva** [comment]
I remember our talk @amcdnl, your project looks super interesting! I want to see how we could integrate it into our building process.

**Comment by hansl** [comment]
Felipe make sure you talk to me before starting work on this.

**Comment by amcdnl** [comment]
@filipesilva @hansl - If I can help, let me know :)

**Comment by filipesilva** [comment]
This issue has been made obsolete by #1455, since we no longer use SystemJS anymore.
