### ISSUE TITLE
3rdpartylicenses.txt is empty

### ISSUE THREAD

**Issue by xz64** [angular/angular-cli#6921]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.0
node: 8.1.3
os: linux x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.5
@angular/language-service: 4.2.5
```

### Repro steps.
`ng new myproject`
`cd myproject`
`ng build --target=production`
The file `dist/3rdpartylicenses.txt` will be empty.

### The log given by the failure.

No log 

### Desired functionality.

3rdpartylicenses.txt should contain the licenses of all modules loaded from node_modules

### Mention any other details that might be useful.

* I am the author of the webpack plugin that outputs the licenses. I have already pushed a fix in version 0.5.1 of license-webpack-plugin. Upgrading the version of license-webpack-plugin should resolve the issue.
* https://github.com/xz64/license-webpack-plugin/issues/12

**Comment by mariuszBX** [comment]
Thank you xz64. I was just affected by this issue. 

Any workaround for us "users" you can recommend except updating the package.json of @angular/cli manually to use 0.5.1 of your license-webpack-plugin?

**Comment by JanWaller** [comment]
Maybe the supplied pattern could be changed as well:
pattern: /^.*$/

So not only MIT,ISC and BSD licensed files are included, but, e.g., Apache as well

**Comment by xz64** [comment]
@mariuszBX I can't think of any workarounds for this. I submitted a pull request #7064 to upgrade license-webpack-plugin.

**Comment by kumaresan-subramani** [comment]
is there any way to avoid `3rdpartylicenses.txt` generation while running below command:

> ng build --prod window --aot --source-map=false --vendor-chunk=true --output-hashing none
