### ISSUE TITLE
Use AutoDllPlugin

### ISSUE THREAD

**Issue by bmayen** [angular/angular-cli#6922]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

Please consider integrating https://github.com/asfktz/autodll-webpack-plugin to generate DLLs and improve build times.

**Comment by filipesilva** [comment]
That looks like a nice way of using the DLL plugin, but unfortunately it still has all the problems discussed in https://github.com/angular/angular-cli/issues/4565. I'm closing as a duplicate because it's the same thing (it still uses DLLPlugin).
