### ISSUE TITLE
Improve errors when "tsconfig" files are malformed.

### ISSUE THREAD

**Issue by michaelsafyan** [angular/angular-cli#6926]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.0.4
@angular/compiler-cli: 4.2.3

TypeScript compiler: Version 2.3.4

### Repro steps.

1. Add a trailing comma in a list in "tsconfig.app.json" or some other malformed JSON error.
2. Invoke "ng build"

### The log given by the failure.
Produces useless error:

       Cannot read property 'getLineAndCharacterOfPosition' of undefined

### Desired functionality.
Give a clearer error message. For example:

      Failed to parse "tsconfig.app.json" as valid JSON.
      Trailing comma found on line 6 in the vicinity of:

          >> 5 >>     "types": [
          >> 6 >>         "firebase",
          >> 7 >>      ],

**Comment by filipesilva** [comment]
I think there's a package that validates and prints nice errors for tsconfig loading. Typescript itself might have that.

**Comment by dkosasih** [comment]
Hi,
I was looking for something to work on tried to replicate the error and it looks find to me.
Is it still the case or am I doing something wrong?

Here is what I did to simulate the error:
```
"exclude": [
    "test.ts",
    "**/*.spec.ts",
  ]
```
cli version: 7.0.4

**Comment by alan-agius4** [comment]
Closing as now we do print better error messages that are generated by TypeScript when reading the configuration.


Example;

```
src/tsconfig.app.json(5,14): error TS1109: Expression expected.
```
