### ISSUE TITLE
can't serve a pure angular project.

### ISSUE THREAD

**Issue by MashiroWang** [angular/angular-cli#6927]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.0
node: 8.1.3
os: darwin x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.6
@angular/language-service: 4.2.6

### Repro steps.

1. ng new test
2. cd test
3. ng serve

### The log given by the failure.

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /Users/Mashiro/Code/Angular/hero/node_modules/@angular/platform-browser/node_modules/@angular/core/core.d.ts, resolving symbol BrowserModule in /Users/Mashiro/Code/Angular/hero/node_modules/@angular/platform-browser/platform-browser.d.ts, resolving symbol BrowserModule in /Users/Mashiro/Code/Angular/hero/node_modules/@angular/platform-browser/platform-browser.d.ts
webpack: Failed to compile.

### Desired functionality.

i don't know

**Comment by Brocco** [comment]
If you are using a function in an NgModule it must be defined outside of that function and exported. This will give visibility to the compiler to be able to handle that function.
