### ISSUE TITLE
ng build --watch --output-path not deleting the directory

### ISSUE THREAD

**Issue by casc99** [angular/angular-cli#6928]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.0
node: 8.1.3
os: linux x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.6
@angular/language-service: 4.2.6

### Repro steps.

ng new newProj
cd newProj
ng build --watch true --output-path dist/angular --delete-output-path true
touch ./dist/angular/newFile.txt
modify and save src/app/app.component.html (building correctly)
ll ./dist/angular/ (newFile.txt still there)

### The log given by the failure.

none

### Desired functionality.

Watching the dist folder from nodejs, I would like to be notified on rebuild.

**Comment by filipesilva** [comment]
This is intended. We don't delete the directory between rebuilds for two reasons:
- faster rebuild cycles (delete still takes time).
- allow for custom setup where users add files to dist through processes other than the CLI.

There is no rebuild hook to subscribe to on the CLI. But you can use one of many node watchers available to watch the dist directory.
