### ISSUE TITLE
Migrating existing CLI package to beta1

### ISSUE THREAD

**Issue by markjritchie** [angular/angular-cli#693]
I'm in the process of migrating an existing CLI generated project to beta 1, unfortunately I'm having issues with a 3rd party package I'm using (Angular2 cookie)

I've updated the angular-cli-build.js so that it references it.

`/* global require, module */

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/*.js',
      'es6-shim/es6-shim.js',
      'reflect-metadata/*.js',
      'rxjs/**/*.js',
      '@angular/**/*.js',
      'angular2-cookie/bundles/angular2-cookie.min.js'
    ]
  });
};
`

My code references it so:
`import {CookieService} from 'angular2-cookie/core';`

but I can see in the chrome debugger the following error:

`zone.js:101 GET http://localhost:4200/angular2-cookie/core 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM4623:3fetchTextFromURL @ system.src.js:1154(anonymous function) @ system.src.js:1735ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1734(anonymous function) @ system.src.js:2759(anonymous function) @ system.src.js:3333(anonymous function) @ system.src.js:3600(anonymous function) @ system.src.js:3985(anonymous function) @ system.src.js:4448(anonymous function) @ system.src.js:4700(anonymous function) @ system.src.js:406ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/angular2-cookie/core
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
	Error loading http://localhost:4200/angular2-cookie/core as "angular2-cookie/core" from http://localhost:4200/app/shared/state.service.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/angular2-cookie/core(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): Error: Error: XHR error (404 Not Found) loading http://localhost:4200/angular2-cookie/core(…)`

What do I need to change to get this working again?

**Comment by hansl** [comment]
You forgot to change the SystemJs Config. Look for a `system-config.ts` file and update the mapping/paths to point to the proper JS file.

**Comment by markjritchie** [comment]
Do we have any documentation on how to configure this?

**Comment by markjritchie** [comment]
OK figured it out. I changed the system-config.ts so:

`/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map: any = {
    'angular2-cookie/core': 'vendor/angular2-cookie/bundles/angular2-cookie.min.js'
};
`
