### ISSUE TITLE
`ng serve --deploy-url / --base-url / --public-host` doesn't affect live-reload paths

### ISSUE THREAD

**Issue by jak** [angular/angular-cli#6932]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
$ ng "--version"
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.1.2
node: 6.10.1
os: darwin x64
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/core: 4.2.3
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/router: 4.2.3
@angular/cli: 1.1.2
@angular/compiler-cli: 4.2.3
```

macOS 10.12.5

### Repro steps.

When running `ng serve` inside a subdirectory (`--deploy-url /app1/ --base-url /app1/`) the live reload setup is still served from the root url.
When developing two angular apps on the same host/port (behind a reverse proxy for example), this is problematic.

I thought setting `--public-host http://mydevserver/app1/` would help, but it does not seem to affect live reload.

### The log given by the failure.

Console errors:
zone.js:2263 GET http://devserver/app1/info?t=1499685597179 404 (Not Found)

### Desired functionality.

Setting `--public-host` should also set up live-reload to operate from the same URL.

**Comment by clydin** [comment]
Please see PR https://github.com/angular/angular-cli/pull/6320

This should be available in the next minor release.

**Comment by jak** [comment]
Thanks

**Comment by jak** [comment]
The linked PR appears stale - re-opening issue.

**Comment by filipesilva** [comment]
Fixed via https://github.com/angular/angular-cli/pull/6320 (it's merged now).
