### ISSUE TITLE
Remove copyright comments from vendor.bundle.js

### ISSUE THREAD

**Issue by YagoLopez** [angular/angular-cli#6933]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.

@angular/cli: 1.2.0
node: 6.10.0
os: win32 x64
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.6

### Mention any other details that might be useful.

In my opinion after AOT compilation could be convenient to leave only one copyright note on "vendor.bunle.js" to reduce file size. Now you have a lot of comments repeated. See this example:

https://yagolopez.js.org/ng-dashboard/dist/vendor.bundle.js

**Comment by grizzm0** [comment]
Already seems to be part of 1.3.0-beta.0. See #4694

**Comment by YagoLopez** [comment]
@grizzm0 Great! Thanks for the info. I had searched for this topic before opening the issue but found nothing. Excuse me.
