### ISSUE TITLE
ng serve cannot serve files from a folder with %20 in it

### ISSUE THREAD

**Issue by BaileyMillerSSI** [angular/angular-cli#6934]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 8.1.0
os: win32 x64
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.0.0
@angular/compiler-cli: 4.2.4

### Repro steps.

Create repo at Visual Studio Online with a space in the name
Clone using Visual Studio Code
See on windows 10 that it creates a folder with a %20 in the location of the space
Run npm install && ng serve and see that it cannot serve the index file

### The log given by the failure.

Technically the Angular CLI doesn't report anything wrong but it fails to function correctly. 

### Desired functionality.

That either the CLI warn that the repo has an invalid character or handle it gracefully. Some users may not understand why their projects aren't working correctly after cloning repos that allow spaces in their names. As well the CLI does nothing to warn the user or tell them that something happened incorrectly. I spent 10 minutes of my morning looking file per file at this repo imported from GitHub to find my issue. Some people don't have that time.

### Mention any other details that might be useful.

- IDE
    - Visual Studio Code
- Source Repo
    - Visual Studio Online

**Comment by mpriem** [comment]
Thanks for this! I was banging my head against it for hours now.

ng new'd a project into a folder that had %20 in the path (cloned repo from VS Online into c:\code\Programming%20Training\Angular2\HelloWorld). The result is every request to localhost:4200 will result in a 404 "Cannot GET /".
Renamed the path and removed the %20, and all is good in the world.

My settings:
Windows 10 Creative Update
@angular/cli: 1.2.0
node: 6.11.0
os: win32 x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.6
@angular/language-service: 4.2.6

**Comment by BaileyMillerSSI** [comment]
I was literally sitting with the file explorer open with my github version and my TFS version and I went through every file trying to find the problem until I stopped and looked at the root folder name.

**Comment by BaileyMillerSSI** [comment]
Also @mpriem your folder structure says Angular 2, you may want to change that to Angular 4. I understand there aren't very many differences between the version but if you are going to use `@angular/common 4.2.6` I recommend keeping the folder structure the same.

**Comment by filipesilva** [comment]
I can verify this still happens. It's a bug in `webpack-dev-server` AFAIK for which there is no fix available. It is being tracked in https://github.com/webpack/webpack-dev-server/issues/915, and I'll leave this issue open but blocked.

**Comment by BaileyMillerSSI** [comment]
This question seems to predate mine, [here](https://github.com/angular/angular-cli/issues/6119).

**Comment by filipesilva** [comment]
Closing in favor of https://github.com/angular/angular-cli/issues/6119 then.
