### ISSUE TITLE
Angular CLI update to (^1.2.0) - Module not found Error

### ISSUE THREAD

**Issue by yasiryc** [angular/angular-cli#6936]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Output from: `ng --version`.
@angular/cli: 1.2.0
node: 7.7.3
os: win32 x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/platform-server: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.5

### Repro steps.

I have updated the angular cli version to 1.2.0 from 1.0.0-RC.4 and also updated Angular version to latest as well. I have been able to build without any error on my local machine but when i pushed my changes to be built on Team City Build Agent, i get Module not found error only following modules

heimdalljs-logger
heimdalljs
schema-utils

I have manually installed these three modules on build agent but CI build still failing.

Any ideas on how to get the resolved on the build agent?

-->

### The log given by the failure.

[16:23:22]	Error: Cannot find module 'heimdalljs-logger'
[16:23:22]	at Function.Module._resolveFilename (module.js:470:15)
[16:23:22]	at Function.Module._load (module.js:418:25)
[16:23:22]	at Module.require (module.js:498:17)
[16:23:22]	at require (internal/module.js:20:19)
[16:23:22]	at Object.<anonymous> (D:\TeamCity\buildAgent\work\f7e3a75d99e63fe2\Angular\node_modules\@angular\cli\ember-cli\lib\cli\index.js:4:14)
[16:23:22]	at Module._compile (module.js:571:32)
[16:23:22]	at Object.Module._extensions..js (module.js:580:10)
[16:23:22]	at Module.load (module.js:488:32)
[16:23:22]	at tryModuleLoad (module.js:447:12)
[16:23:22]	at Function.Module._load (module.js:439:3)

**Comment by Brocco** [comment]
Those dependencies are set within the package.json of the CLI and should be installed by that environment for you. Please verify with a different environment and ensure the installations on your build machine.

Here's a [link](https://github.com/angular/angular-cli/blob/7d8f54a82cceb90bfde4d0b56a334337720479b2/packages/%40angular/cli/package.json#L50-L51) to the code where the CLI depends on those packages.

**Comment by estani** [comment]
I got a very similar problem, caused by placing the node_modules directory somewhere else and linking to it. Npm has already issues with it, as do node and, I'll presume, angular-cli.

I know no solution yet.

**Comment by grayskwrl149** [comment]
I also was linking to a node_modules directory elsewhere. When I removed the link and moved the external node_modules directory into the project, per expected setup, everything worked. The error went away.

**Comment by KhaledSMQ** [comment]
i just install it manual
```
npm i heimdalljs-logger --save-dev
```

**Comment by KhaledSMQ** [comment]
one more thing you can do
```
npm install --no-cache
```
