### ISSUE TITLE
ng generate interceptor my-new-interceptor

### ISSUE THREAD

**Issue by uberspeck** [angular/angular-cli#6937]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
Given the new interceptor functionality it would be great to see a generator for them!

**Comment by Khanji** [comment]
I vote yes!

**Comment by josuevalrob** [comment]
Any solution??

**Comment by Al-Sharif** [comment]
I vote yes

**Comment by SummerFans** [comment]
I vote yes!!!

**Comment by arturober** [comment]
Yes, please!

**Comment by mgechev** [comment]
This is a perfect candidate for a third-party schematics which can be maintained by the community. Feel free to implement a generator and link to it here, with a comment. ❤️

**Comment by mikelhamer** [comment]
@mgechev why has this been closed?

**Comment by jaime-alex** [comment]
I vote yes.

**Comment by SummerFans** [comment]
I vote yes! 👍

**Comment by szabolcssimonyi** [comment]
I vote yes!

**Comment by will093** [comment]
I vote yes please!

**Comment by leandrofabianjr** [comment]
I vote yes!

**Comment by IceTower** [comment]
I vote yes

**Comment by hackdan** [comment]
I vote yes!

**Comment by TomerBu** [comment]
I vote 👍 "yes, please!"

**Comment by whyDontI** [comment]
+1

**Comment by crutchcorn** [comment]
Please do not comment "+1" or "I vote yes". There is a react emoji that can be added to the initial issue to express such interest. Anything else only spams the thread (and anyone subscribed)

**Comment by veliyat** [comment]
+1
