### ISSUE TITLE
Compilation takes long

### ISSUE THREAD

**Issue by pantonis** [angular/angular-cli#6950]
After updating from angular-cli 1.0.0 I found out that compilation using ng-serve is taking 30 seconds for a small html change. I am running it on high end I7 quad core HQ processor.

### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.0
node: 6.10.3
os: win32 x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/material: 2.0.0-beta.8
@angular/cdk: 2.0.0-beta.8
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.6

**Comment by filipesilva** [comment]
Shouldn't take that long, not by a longshot. Can you offer a reproduction?

**Comment by pantonis** [comment]
Sorry no. It is a corporate solution .

**Comment by deebloo** [comment]
@pantonis is it possible for you to provide a repo that reproduces the issue without sharing your actual project?

**Comment by pantonis** [comment]
Unfortunately I cant think a way of doing that. Any suggestions on how to start troubleshooting what is taking long?

**Comment by filipesilva** [comment]
There isn't much that I can think of without a fair amount of internal CLI knowledge. Perhaps trying to figure out what command you're using, if you reproduce it, taking out parts of your application to see if it's related. Stuff like that. Trying to come up with a repro is the best kind of debug.

**Comment by filipesilva** [comment]
(sorry, closed by accident)

**Comment by pantonis** [comment]
Upgraded to 1.4.9 problem resolved. Dont know what was causing it
