### ISSUE TITLE
Split polyfills.bundle.js into 2 files - one universal and one for IE

### ISSUE THREAD

**Issue by chriszrc** [angular/angular-cli#6954]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

It would be nice to separate the polyfill script into one that is needed for all browsers, and one that is only needed for IE. Looking at the sourcemap explorer, IE is responsible for more than half of the file size. Developers could conditionally load the IE polyfills only for IE, and save around 70kb for everyone else-

**Comment by filipesilva** [comment]
How do you propose the conditional load happen though? I can see this already be possible with the `scripts/assets` functionality.

**Comment by aciccarello** [comment]
This is related to #6577

**Comment by filipesilva** [comment]
Closing in favor of that one, it does seem similar.
