### ISSUE TITLE
Travis fail after upgrading angular-cli to 1.2.0 version

### ISSUE THREAD

**Issue by DavidBronfen** [angular/angular-cli#6955]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.0
node: 7.10.0
os: darwin x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cdk: 2.0.0-beta.8
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.6
@angular/language-service: 4.2.6

### Repro steps.
```
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@latest
```
After upgrading to angular-cli 1.2.0 the Travis tests  are failing with the following error:

### The log given by the failure.
<img width="1047" alt="job__182_2_-_davidbronfen_retrogusto_-_travis_ci" src="https://user-images.githubusercontent.com/12427216/28130919-0c3f62ac-6741-11e7-83f6-3545d34294ec.png">

### Mention any other details that might be useful.
Tried to run it with a completely clean install of a new project (ng new new-project)  and I got the same error.

Link to the [PR](https://github.com/DavidBronfen/Retrogusto/pull/34)

**Comment by scttcper** [comment]
You have caching setup in your travis.yml
```yml
cache:
--
  | npm: true
  | directories:
  | - client/node_modules
```

Try clearing your cache files on travis.

**Comment by DavidBronfen** [comment]
@scttcper Thanks, it works!
