### ISSUE TITLE
ERROR in AppApplication is not an NgModule

### ISSUE THREAD

**Issue by pdestailleur** [angular/angular-cli#6960]
I have a custom annotation that gives an NgModule as a result, but ng serve and ng build always give this as a first error:
**ERROR in AppApplication is not an NgModule**

Changing a ts-file in the project solves the problem when doing ng serve, but this isn't a solution for ng build.

This is my module that is bootstrapped.
```

@Application({
    plugins: loadPlugins(),
    shell: config,
})
export class AppApplication {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: AppApplication
    };
  }
 }

@NgModule({
  imports: [
    AppApplication.forRoot()
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
The Application-annotion returns on Object containing:
```
{
   declarations : [ AppComponent ]
   exports : [ AppComponent ]
   imports : [ BrowserModule, ShellAppModule, RouterModule.forRoot(), SystemServicePlugin, DevelopmentPlugin and some other plugins ]
   providers: [ HttpModule, BrowserModule and some other providers ]
}
```

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.0
node: 7.9.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.2.0
@angular/compiler-cli: 4.1.3

### Repro steps.

ng build
ng serve

### The log given by the failure.

ng build
Hash: a5bb2f73ca26813c1fbb
Time: 26836ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 500 kB {3} [initial] [rendered]
chunk    {1} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 160 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 748 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.68 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in AppApplication is not an NgModule
webpack: Failed to compile.

### Desired functionality.

Compile without error

**Comment by filipesilva** [comment]
I'm sorry but there isn't anything I can do without a runnable repro. If you add one I can take a look.

**Comment by pdestailleur** [comment]
You can find a repro on: https://bitbucket.org/pdestailleur/ngmodule_error

**Comment by filipesilva** [comment]
@Brocco can you have a look?

**Comment by pdestailleur** [comment]
Has this been investigated yet?

**Comment by mgechev** [comment]
@pdestailleur can you still reproduce the issue?

**Comment by mgechev** [comment]
Closing the issue due to inactivity. If the problem still exists in the latest version of the CLI, please open a new issue following the template and providing a minimal demo where we can reproduce it. Thanks! :-)
