### ISSUE TITLE
NPM packages are not installing when generating a new project in cli 1.2.1

### ISSUE THREAD

**Issue by ghost** [angular/angular-cli#6964]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.1
node: 6.11.0
os: win32 x64

### Repro steps.
1. `ng new project`

### The log given by the failure.

```
installing ng
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Installing packages for tooling via npm.
Successfully initialized git.
Project 'project' successfully created.
```

**Comment by nvasilev1** [comment]
Hello,
I have the same issue, but trying with the fix does not work for me unfortunately. I do not have npm-install.ts file, but instead i have npm-install.js (and npm-install.d - MPEG2 TS video file and npm-install.js.map). The file npm-install.js is with similar code than the one showed int he fix, but there are some differences, which crash the new project. For example if I copy paste the whole code into my file, this is the error:

Unexpected token import
D:\temp\NV\node-v6.11.1-win-x64\node_modules\@angular\cli\tasks\npm-install.js:2

import * as chalk from 'chalk';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\temp\NV\node-v6.11.1-win-x64\node_modules\@angular
\cli\tasks\init.js:5:23)

I am attaching the original npm-install.js file.
[npm-install.zip](https://github.com/angular/angular-cli/files/1155677/npm-install.zip)

Sorry if there is an easy fix shown in the answer or the procedure of asking this kind of stuff is different, but I am kind of new here.

**Comment by fmalcher** [comment]
Seems to be fixed with https://github.com/angular/angular-cli/commit/aebf4c89b1b4c66316b0a396751f6bd9d9d1b645

**Comment by filipesilva** [comment]
Fixed via https://github.com/angular/angular-cli/pull/7033
