### ISSUE TITLE
Impossible to build to root folder whereas I disable "delete-ouput-path" option

### ISSUE THREAD

**Issue by loic49** [angular/angular-cli#6965]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.1
node: 6.11.0
os: win32 x64

### Repro steps.

After upgrading anglular/cli to version 1.2.1, I could not build my application anymore. Before migration I used version 1.0.6.

Now when I build my application, I get this error message : "Output path MUST not be project root directory!". It's true.. my output path is root BUT I disable "delete-output-path" option.

### Desired functionality.

When "delete-output-path" option is disabled, cli should accept to use root path.

**Comment by grizzm0** [comment]
May I ask what the reason behind building to root is? That sounds really weird as it would clutter up your root and it sounds really hard to clean.

**Comment by loic49** [comment]
I started my application with Angular 2 beta 8 based on Umbraco wich is an ASP.Net CMS. Before version 1.2.1 of angular/cli there was no problem with this architecture. The principal reason to build to root is only it was working before ;).

I build to root only for dev. For production, I build to "dist" folder and I don't disable "delete-output-path" option.

**Comment by grizzm0** [comment]
I don't think this behaviour is going to change. You'll be better of using a build path and change your server to serve from that instead of root.

**Comment by loic49** [comment]
Very bad news for me (and certainly for some others). I have to change my development architecture while this one works perfectly for more than 1 year.

To save me you've just to had a test on line 17 of file build.ts :

if (this.project.root === path.resolve(outputPath)) {

becomes

if (this.project.root === path.resolve(outputPath) && runTaskOptions.deleteOutputPath) {

Why prevent deployment on root if you do not delete the contents of the folder?

**Comment by grizzm0** [comment]
Feel free to submit a PR for this behaviour. 
Please include a warning though to inform the user that they're doing something potentially unsafe.

**Comment by loic49** [comment]
I have bypassed the problem by reorganizing the folders of my application.

I close the issue.
