### ISSUE TITLE
ng destroy route myroute doesn't remove the route

### ISSUE THREAD

**Issue by psyCodelist** [angular/angular-cli#697]
ENV:
angular-cli: 1.0.0-beta.1
node: 5.11.0
os: darwin x64

Simply run "ng g route myroute" and then run "ng destroy route myroute".
despite the following message, no file is being removed.
uninstalling route
uninstalling route-myroute

**Comment by phillipgreenii** [comment]
Is `ng destroy` a supported command?  I don't see any reference to it in the docs or the code.

**Comment by psyCodelist** [comment]
It is comes with ember cli and it used to work fine on previous version.

**Comment by hansl** [comment]
We're going to remove `ng destroy` as there's a lot of logic in the generation and it's getting harder to support. We'll reinclude it when we have a proper story for generation.
