### ISSUE TITLE
ng g c --module= <no-module> ?

### ISSUE THREAD

**Issue by danielcooke1996** [angular/angular-cli#6975]
Is there a way to specify that you **don't** want to declare the generated component in a module?

I have created a batch script to speed up component generation with some default options, but because every component that I generate is going to be in a different module I would prefer to keep things clean by adding it to the module myself.

By default it puts the generated component in `app.module.ts`.

**So can you specify that you don't want the generated component to be declared in ANY ngModule**?

**Comment by tytskyi** [comment]
> By default it puts the generated component in app.module.ts.

Correction: by default it puts generated component in nearest module. 
You could just go into folder with your target module and run script from there (you need to make your script globally available depending on your operating system).

**Comment by danielcooke1996** [comment]
> Correction: by default it puts generated component in nearest module.

Yes, that is what I thought as well. However it doesn't always work for me.

Have a look at my folder structure - 
```
Directory of C:\IBM\streams\SUB_STAGE_1_2\frontend\local ui\src\app\components\epvp\tests

14/07/2017  10:28    <DIR>          .
14/07/2017  10:28    <DIR>          ..
04/07/2017  10:16    <DIR>          .dm
13/07/2017  14:39             3,496 epvp-tests-module.ts
14/07/2017  10:18    <DIR>          itinerary
10/07/2017  10:20    <DIR>          sign-off
04/07/2017  09:55    <DIR>          test-info
```
Now I'll give you an example using actual console outputs.

1. I want to create a new component named `example` under `tests/example'
2. First I create a new directory `example`
3. `cd example`
4. I will run my globally available batch script `nfs example`

## Console Output
```
C:\IBM\streams\SUB_STAGE_1_2\frontend\local ui\src\app\components\epvp\tests\example>ng g c example --flat --inline-style --spec=false --prefix="nfs"
installing component
  create src\app\components\epvp\tests\example\example.component.html
  create src\app\components\epvp\tests\example\example.component.ts
You are using different prefix from app, you might get lint errors. Please update "tslint.json" accordingly.
  update src\app\app.module.ts

```

As you can see, the nearest module is `epvp-tests-module.ts` - but ng g c still places the declaration in the `app.module`.

It seems to only check the working directory for a module, and not the parent directory.

**Comment by clydin** [comment]
The '--skip-import' option should do what you need.

**Comment by danielcooke1996** [comment]
@clydin Thank you! I don't know how I missed this.
