### ISSUE TITLE
jschardet license

### ISSUE THREAD

**Issue by corpron** [angular/angular-cli#6978]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
The jschardet library that Angular CLI has a dependency on has an LGPL license. In my organization, libraries with LGPL licenses can't be used in production applications. As a result, when our application was scanned by cybersecurity, it failed. 

It would be desirable for all Angular CLI libraries to have licenses that are less restrictive (for example, MIT).

**Comment by filipesilva** [comment]
We do limit the licenses we use, and test for them in https://github.com/angular/angular-cli/blob/master/scripts/test-licenses.js. As far as I know `jschardet` is the only LGPL one we have.

If you can find way around that library that doesn't really change the CLI functionality I'm happy to review a PR.

**Comment by clydin** [comment]
Closing as this package is no longer present.
