### ISSUE TITLE
AOT - Decorators are removed - still no solution

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#6992]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
@angular/cli: 1.1.2
node: 6.9.0
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.2
@angular/compiler-cli: 4.1.3

### Repro steps.
`ng build --prod --aot=true` and Decorators are removed

### Desired functionality.
I know it has been discussed many times here and I see there was made some temporary fix  https://github.com/angular/angular-cli/pull/3583 which was reverted back later on and I dont see any real solution so far. 

Is it possible to put in some flags in so its up to the developers to decide wheather they want custom decorators or angular's ?

### Mention any other details that might be useful.
When I used AOT with decorators or without them there are still great bundle size optimization. Instead of having 60% of original size I have 55% - which is not that dramatic increase on the size - but still your app can leveradge offline compiled code .

So having some option in place where developers can turn on/off angular decorators or custom would be great feature.  Also I read from @hansl the:

`Prod builds will only remove decorators that are marked as annotations using tsickle. `, but then I havent seen any reference to it.

Even there might be impact on TreeShaking ...

Or somehow include this tsickle like in here:
https://github.com/mlaval/optimize-angular-app

which should even now convert decorators into static class properties and maybe if this already work - this would be the best.

**Comment by filipesilva** [comment]
Can you provide a runnable repro of the problem please?

**Comment by fkolar** [comment]
I see this is duplicate to this #5670 and all this talks about the same problem where or at least it relates to this. 

I tried describe all under this github sample: https://github.com/fkolar/decoratorsGone.
