### ISSUE TITLE
Command "ng doc" might be out of sync with angular.io

### ISSUE THREAD

**Issue by fabionolasco** [angular/angular-cli#6996]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.1
node: 6.11.0
os: darwin x64
@angular/animations: 4.3.0
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/cli: 1.2.1
@angular/compiler-cli: 4.3.0
@angular/language-service: 4.3.0
@angular/material: 2.0.0-beta.1

### Repro steps.
When we run the command "ng doc build", or "ng doc serve", or "ng doc new", etc, they open the angular.io website, however, the page looks the same to all of them.

I believe that the CLI is generating an URL like:
https://angular.io/api#!?query=serve

But the Angular website is expecting something like:
https://angular.io/api?query=serve

### Desired functionality.
I would expect the CLI to redirect to the correct URL format expected by angular.io

**Comment by patricknazar** [comment]
looks like the `search` option may need to be removed, can't see the docs to be linkable like that?

**Comment by devoto13** [comment]
There is a PR related to this issue - #6993.

**Comment by fabionolasco** [comment]
You are correct @devoto13. I apologize.
