### ISSUE TITLE
feat(@angular/cli): specify naming convention for lazy chunks

### ISSUE THREAD

**Issue by CaerusKaru** [angular/angular-cli#6999]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Versions.

```
@angular/cli: 1.3.0-beta.1
node: 8.1.3
os: linux x64
@angular/animations: 4.3.0
@angular/cdk: 2.0.0-beta.8-abec992
@angular/cli: 1.3.0-beta.1
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/material: 2.0.0-beta.8-abec992
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/platform-server: 4.3.0
@angular/router: 4.3.0
@angular/app-shell: 0.1.0
@angular/compiler-cli: 4.3.0
@angular/language-service: 4.3.0
@angular/service-worker: 1.0.0-beta.16
```

### Desired functionality.

bcca0d7 changed the way chunks are named. There should be an option to go back to the old naming convention. This allows for finer obfuscation if desired.

Maybe something like `--ob-lazy` as an option with `ng build`.

**Comment by intellix** [comment]
Do you mean that you want to go from: `account.module` to `0.module` to save 6 bytes when it's referenced for loading?

**Comment by ubaidazad** [comment]
is [bcca0d7](https://github.com/angular/angular-cli/commit/bcca0d7b3fdbf27ea55b6f8566d43d5c63a18346) in 4.3.0  ?

**Comment by grizzm0** [comment]
@ubaidazad You're linking to a commit on AngularCLI repo and CHANGELOG of the Angular repo. That makes no sense. :p The commit you linked to will be in the 1.3 release of AngularCLI.

**Comment by CaerusKaru** [comment]
@intellix The naming convention change is correct, but the reason is not. My personal reason for wanting the change is because I don't have the luxury in my dev environment of having semantic control over the files, so obfuscated names are better and cause less conflict. Regardless, I feel like since it was the original implementation, and it doesn't change that much code, allowing this freedom to the developer is a win-win.

**Comment by CaerusKaru** [comment]
Thanks @filipesilva. Currently tracking in #7007

**Comment by filipesilva** [comment]
Sorry guys I hadn't seen this issue yet, but https://github.com/angular/angular-cli/pull/7007 does address it fully.
