### ISSUE TITLE
`included` Addon hook

### ISSUE THREAD

**Issue by rodyhaddad** [angular/angular-cli#7]
Let's implement the `included` addon hook, to allow addon to import assets into an ng2 application.

We can follow [ember-cli example](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L319-L332) to call this hook.

Related #6

**Comment by hansl** [comment]
The thirdparty support guide includes something like that. Closing this as it will be addressed by it. Build hooks is important :)
