### ISSUE TITLE
Cannot read property 'create' of undefined - vendor.bundle.js  on ng build --prod 

### ISSUE THREAD

**Issue by HarshdeepSingh3009** [angular/angular-cli#7002]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report 
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.1
node: 6.10.3
os: win32 x64
@angular/animations: 4.3.0
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/cli: 1.2.1
@angular/compiler-cli: 4.3.0
@angular/language-service: 4.3.0

### Repro steps.
run > ng build --prod
then open visual studio 2017 and run the project through iisexpress.
the below error is shown the browser console.
everything works fine in dev mode.

### The log given by the failure.
vendor.fbd28cef4840b6d01817.bundle.js:1 Uncaught TypeError: Cannot read property 'create' of undefined
    at vendor.fbd28cef4840b6d01817.bundle.js:1
    at t.invoke (polyfills.3ae08eaf6129a55130cb.bundle.js:1)
    at Object.onInvoke (vendor.fbd28cef4840b6d01817.bundle.js:1)
    at t.invoke (polyfills.3ae08eaf6129a55130cb.bundle.js:1)
    at r.run (polyfills.3ae08eaf6129a55130cb.bundle.js:1)
    at t.run (vendor.fbd28cef4840b6d01817.bundle.js:1)
    at e._bootstrapModuleFactoryWithZone (vendor.fbd28cef4840b6d01817.bundle.js:1)
    at e.bootstrapModuleFactory (vendor.fbd28cef4840b6d01817.bundle.js:1)
    at Object.aR8+ (main.b7d0a0c8ea704c21f7e5.bundle.js:1)
    at r (inline.c662fd847664bfd23648.bundle.js:1)

### Desired functionality.

.
I am building an asp.net core app using .net framework 4.6.2 and Angular 4. Everything is working fine in
dev mode but when I run ng build -- prod and then run iisexpress from visual studio the above error is shown in chrome.
-- I have tried uninstalling @angular/cli and re-installed the latest version but still the error persists.

here is the package.json from the project 

{
  "name": "webtool",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4",
    "jquery": "^3.2.1",
    "crypto-js": "^3.1.9-1",
    "file-saver": "^1.3.3",
    "ngx-chips": "^1.4.0"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.1",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "bootstrap": "~3.3.7",
    "bootswatch": "~3.3.7",
    "codelyzer": "~3.0.1",
    "font-awesome": "~4.7.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3",
    "w3-css": "~4.0.4"
  }
}

Please let me know if you need any other  information.

**Comment by filipesilva** [comment]
I'm sorry but this doesn't seem like a problem with the CLI, generated projects, or the build process. It's probably related to your code or some library you are using. If it works in dev but not in prod, perhaps one of the libraries cannot be properly minified.

**Comment by LING36** [comment]
I met this problem, too.Use the command ng build --prod --aot Compression code，Deployment to server error TypeError: Cannot read property 'create' of undefined.How to solve？Ask for help
