### ISSUE TITLE
Re create test unit

### ISSUE THREAD

**Issue by dekonunes** [angular/angular-cli#7005]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality.

I created a project and all components I deleted the unit tests documents, but now I want create a TDD in this project, there is a way/command to re-create the defaults spec?

**Comment by filipesilva** [comment]
No, there isn't any way generate just the tests for an existing file. This isn't something we want to add right now either. My advice is to use git to restore these files, or to create a new component and use that test for the others.
