### ISSUE TITLE
uglifyjs as a flag

### ISSUE THREAD

**Issue by ramarro123** [angular/angular-cli#7006]
hi,

uglifyjs doesn't support es6, it's possible to use --prod during build but disabling just the uglifyjs part?

i will eventually do a closure compiler pass after that, but i need to remove the uglifyjs part.

right now seems that not possible standing to docs to specify that flag

**Comment by filipesilva** [comment]
This isn't possible currently. You seem to be using a fairly custom build process, so I'd suggest you eject to have full control over it.
