### ISSUE TITLE
npm install -g @angular/cli Error

### ISSUE THREAD

**Issue by orgertot** [angular/angular-cli#7008]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
npm 4.1.2
node v7.7.2

### Repro steps.
npm install -g @angular/cli

### The log given by the failure.
npm install -g @angular/cli
npm ERR! registry error parsing json
npm ERR! registry error parsing json
And then the "normal" installation log..

### Desired functionality.
No errors

### Mention any other details that might be useful.
The installation is pretty slow..

**Comment by mscu** [comment]
are you behind a proxy?

npm was not down according to https://status.npmjs.org/

**Comment by filipesilva** [comment]
I don't know what the problem was, but it's happening before the CLI was even installed. You should report it to https://github.com/npm/npm if it's giving you trouble.
