### ISSUE TITLE
npm ERR! 404 no such package available : @ngtools/webpack

### ISSUE THREAD

**Issue by yume117** [angular/angular-cli#7009]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report 
- [ ] feature request
```

### Versions.

node v6.10.3
npm v3.10.10
Windows 10

### Repro steps.
Use `npm install` in a git bash with angular-cli installed

### The log given by the failure.
Logs from the git bash: 

```
$ npm install
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 no such package available : @ngtools/webpack
npm ERR! 404
npm ERR! 404  '@ngtools/webpack' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'project-name'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     .\npm-debug.log
```

### Desired functionality.
angular-cli correctly installed with no error for an Angular2 project.

### Mention any other details that might be useful.
At first I got the same issue with @angular/ packages while doing `npm install`

After some research I found this : It's an issue with the `@` character,  to fix it I changed the registry

`npm config set "@angular:registry" http://registry.npmjs.org/`

This error got fixed but another poped-up for '@ngtools/webpack' as described above.

**Comment by filipesilva** [comment]
I'm sorry but this isn't an issue with the CLI. The packages are available on the NPM registry. If you have a proxy or some custom configuration, I suppose you have to configure it properly. Sorry I can't help more.
