### ISSUE TITLE
Update deps: uglify-js fails due to outdated dependency caused by postcss-url@5.1.2 required by angular-cli

### ISSUE THREAD

**Issue by actra-gschuster** [angular/angular-cli#7010]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
angular-cli: 1.2.1

### Repro steps.
- Transpile a module using @angular-redux: `ngc -p ./src`
- Rollup: `rollup -c ./rollup.config.js`
- UglifyJS: `uglifyjs ./dist/bundles/index.umd.js --screw-ie8 --compress --mangle --comments --output ./dist/bundles/index.umd.min.js`

### The log given by the failure.
`Error: Can't handle constant of type: object`
This is due to an old version of UglifyJS installed by the following dependency chain:
angular-cli@1.2.1 => postcss-url@^5.1.2 => directory-encoder@^0.7.2 => handlebars@^1.3.0 => uglify-js@~2.3

### Desired functionality.
Current versions of the dependencies should be installed.
The module should be packaged without errors.

### Mention any other details that might be useful.
postcss-url is stable at version 7, that would install directory-encoder@0.9.2, that would install handlebars@4.0.10 with uglify-js at a current version not showing the mentioned problem (was fixed at uglify-js > 2.3.6).
Currently I can only solve the version-dilemma by installing the failing versions (`yarn`) and after that foce installation of handlebars@4.0.10 (`npm i handlebars@4.0.10`).

**Comment by filipesilva** [comment]
I don't know what you're trying to do but your repro steps don't really include anything related to Angular CLI. You seem to be doing something that requires certain versions of libraries? That's really not related to Angular CLI, but rather your package manager and set of dependencies.
