### ISSUE TITLE
ng-xi18n fails with new project

### ISSUE THREAD

**Issue by 0mpurdy** [angular/angular-cli#7012]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.0.0
node: 7.10.0
os: darwin x64
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/compiler-cli: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/platform-server: 4.3.0
@angular/router: 4.3.0
@angular/cli: 1.0.0
```

### Repro steps.

 - Create a new project with `ng new BlankProject`
 - Follow steps in the [Angular i18n guide here](https://angular.io/guide/i18n#create-a-translation-source-file-with-the-ng-xi18n-tool)
    + Error is with the `ng-xi18n` command

### The log given by the failure.

```
$ ./node_modules/.bin/ng-xi18n
TypeError: Cannot read property 'toLowerCase' of null
    at Extractor.serialize (/Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler-cli/src/extractor.js:47:32)
    at /Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler-cli/src/extractor.js:33:33
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
Extraction failed
```

### Desired functionality.

Guide says that a `messages.xml` file should be created, but an error is thrown instead.

### Mention any other details that might be useful.

I've created a very simple repo that demonstrates the problem [here](https://github.com/0mpurdy/less-reference-bug)

**Comment by 0mpurdy** [comment]
Noticed that my angular cli was using an out of date local version, upgraded to:

```
@angular/cli: 1.2.1
node: 7.10.0
os: darwin x64
@angular/animations: 4.3.0
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/compiler-cli: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/platform-server: 4.3.0
@angular/router: 4.3.0
@angular/cli: 1.2.1
@angular/language-service: 4.3.0
```

Issue still remains.

**Comment by ocombe** [comment]
You need to give the format of the translations file that you're using with `--i18n-format=xlf`. The default "xlf" is not working right now (there's a PR to fix that but it hasn't been merged yet).

**Comment by 0mpurdy** [comment]
Thanks @ocombe that's sorted my issue, I'll leave this open until it works without specifying a format (or documentation updates to reflect that format is necessary) but feel free to close yourself if you want :)
