### ISSUE TITLE
Ejected config compile errors that aren't present non-ejected

### ISSUE THREAD

**Issue by MHacker9404** [angular/angular-cli#7015]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.0
node: 7.10.0
os: win32 x64

primeng/primeng: 4.1.0

### Repro steps.
ng new ewa --skip-install --skip-git --skip-commit
npm i primeng
npm i
ng build - no build errors
eject the webpack.config.js
npm run build - multiple build errors from webpack "cannot find source file....."

### The log given by the failure.
ng build
[build_noneject.txt](https://github.com/angular/angular-cli/files/1153389/build_noneject.txt)
npm run build
[build_eject.txt](https://github.com/angular/angular-cli/files/1153390/build_eject.txt)

### Desired functionality.
The build should execute identically - at least until I start messing around with the webpack.config.js file.

**Comment by clydin** [comment]
eject functionality is no longer available in the latest version (6.x+).  For custom webpack configurations the following unofficial add-on is a suggested solution: https://github.com/manfredsteyer/ngx-build-plus
