### ISSUE TITLE
No information on how to generate code coverage

### ISSUE THREAD

**Issue by manju-reddys** [angular/angular-cli#7025]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.
```
@angular/cli: 1.2.0
node: 6.11.0
os: win32 x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/compiler-cli: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/material: 2.0.0-beta.8
@angular/cdk: 2.0.0-beta.8
@angular/flex-layout: 2.0.0-beta.8
@angular/cli: 1.2.0
```
### Repro steps.

When we run the ``` ng test --code-coverage --reporters=coverage-istanbul --watch=false ``` It will generate a coverage folder and index.html file which contains only the ```test.ts``` and ```pollyfill.ts``` but doesn't report test coverage of any file/modules in src folder (unless there is ```*.spec.ts```).

### Desired functionality.

Expecting a way to generate the complete report of all the ```*.ts``` file under src folder that have ```*.spec.ts``` show percent covered and which doesn't have should show 0% coverage etc...

### Mention any other details that might be useful.

I used the ```ng new myproject``` generate the project.

**Comment by Meligy** [comment]
I have a project with the following hierarchy:

![image](https://user-images.githubusercontent.com/171637/28314423-dc1e2be6-6bfd-11e7-9c91-c050364c0ed5.png)


Using Angular CLI 1.3.0-beta.1, I ran:

```
ng test --code-coverage --watch=false
```

And then I got `coverage` folder with an `index.html` that looked like:

![image](https://user-images.githubusercontent.com/171637/28314495-1d4c64c0-6bfe-11e7-8671-273beeb0828c.png)

Opening each folder shows the files in it, like:

![image](https://user-images.githubusercontent.com/171637/28314514-36f5fbe8-6bfe-11e7-8c44-d2b7d5a82590.png)

Which also show the coverage of each file:

![image](https://user-images.githubusercontent.com/171637/28314546-57a22de4-6bfe-11e7-909d-476e577a24cc.png)


So, it seems to be working for me.

**Comment by manju-reddys** [comment]
@Meligy I think you didn't get my point here. It shows the coverage only if there is ```*.spec.ts``` file but it doesn't show source files that don't have ```*.spec.ts``` associated with it. Essentially we can't generate the full report which show how much code one has covered in the project. It is easy to deceive by developer to show the code is tested (it will never show in the coverage report) unless there is ```*.spec.ts``` file.

If we could generate the report which show no coverage or no ```*.spec.ts``` file yet to any of the code then it make more sense.

**Comment by devoto13** [comment]
@manju-reddys You can do this by changing context regex in `src/test.ts`. I.e. change

    const context = require.context('./', true, /\.spec\.ts$/);

to

    const context = require.context('./', true, /\.\/app\/.+\.ts$/);

This will essentially include every `.ts.` file in you `app` folder into test bundle and therefore they will be included in the coverage report. But note that doing so will slow down test run quite significantly in some cases.

**Comment by manju-reddys** [comment]
@devoto13 Thank you for the tip. I agree it take longer to run the tests but it will be run before production build. Developer will continue to use ```const context = require.context('./', true, /\.spec\.ts$/);```
