### ISSUE TITLE
Hash stays same after file change v 1.3.0-beta.1

### ISSUE THREAD

**Issue by elvirdolic** [angular/angular-cli#7026]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.0-beta.1
node: 8.0.0
os: win32 x64

### Repro steps.

ng build --prod --vendor-chunk=false

![image](https://user-images.githubusercontent.com/17769458/28304149-ae47835a-6b96-11e7-8663-b644569411ab.png)

changing something in one of the components in the equipment.module and then do the same command

![image](https://user-images.githubusercontent.com/17769458/28304182-cbe353f8-6b96-11e7-9b05-f16b784727e9.png)

### Desired functionality.

The hash of the equipment.module should change but it doesn't

**Comment by Meligy** [comment]
It doesn't seem to be affected by `--vendor-chunk=false` too.

**Comment by benelliott** [comment]
I think this could be related to https://github.com/webpack/webpack/issues/5184, in which files imported through the `ModuleConcatenationPlugin` didn't have their hashes updated. It has now been fixed and the issue disappears for me if I force the CLI to use Webpack 3.3.0.

**Comment by filipesilva** [comment]
The latest RC's include Webpack 3.3.0, so this should be fixed.
