### ISSUE TITLE
Feature request: onBeforeBuild and onAfterBuild

### ISSUE THREAD

**Issue by smiera** [angular/angular-cli#7027]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
It will be great, if we can setup some npm run script, when using ```ng build -w```.
For example, in ```angular-cli.json``` add optional key ```build```:
`
"build": {
    "onAfterBuild": "npm run after.js",
    "onBeforeBuild": "npm run before.js"
}
`
And when ```watch``` detect changes - run defined scripts in ```angular-cli.json```.

**Comment by Meligy** [comment]
The only thing you cannot do with npm scripts today is having hooks into incremental builds (`watch` stuff). May I ask what's the use case for the `watch` pre/post hooks please?

Cheers,

**Comment by smiera** [comment]
We use own internationalization. All translations saved in one file `translate.json`.

```
  "title": {
    "en": "...",
    "de": "...",
    "it": "...",
    "ru": "..."
  }
```

For each country we build different app based on one code, using different `enviroment.ts`.
After each build, we need  to read `translate.json` file and take translation only for one language and generate one file in dist folder(for example `en.json`).

**Comment by filipesilva** [comment]
Build hooks are something we're thinking of adding for an addon system, but at this moment we don't have any details to share.
