### ISSUE TITLE
What is the best way to publish angular-cli project to npm repository?

### ISSUE THREAD

**Issue by aalielfeky** [angular/angular-cli#7029]
@angular/cli: 1.0.0-rc.2
node: 7.7.2
os: linux x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.10

**Comment by tytskyi** [comment]
I think you want to use your angular-cli project as the npm library?
This is not officially supported at the moment. See https://github.com/angular/angular-cli/issues/1692#issuecomment-304970595 for details

**Comment by filipesilva** [comment]
Closing as answered by @tytskyi, thanks 👍
