### ISSUE TITLE
How can I test my own commands?

### ISSUE THREAD

**Issue by costa595** [angular/angular-cli#7031]
Hello guys, I'd like to find out, how can I test my own commands, which I had added to my own project?
I mean, how can I write tests for them and where can I find tests for commands for Angular CLI?

Thank you in advance and good luck!

**Comment by deebloo** [comment]
Please use the issue template when creating an issue and what so you mean by test your own commands?

**Comment by filipesilva** [comment]
We don't really provide any way of writing your own commands. Only by forking the CLI I suppose. We mostly use end-to-end tests in the `tests/` folder.
