### ISSUE TITLE
Lazy routes are always recreated even when there's no change

### ISSUE THREAD

**Issue by Meligy** [angular/angular-cli#7032]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.3.0-beta.1
node: 8.1.4
os: darwin x64
@angular/animations: 4.3.0
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/cli: 1.3.0-beta.1
@angular/compiler-cli: 4.3.0
@angular/language-service: 4.3.0
```

#### Create a new project with 2 lazy modules

```
ng new LazyBuilder --routing
cd LazyBuilder 

ng g module PageOne --routing
ng g component page-one/page-one-landing

ng g module PageTwo --routing
ng g component page-two/page-two-landing
```

To complete the lazy route configuration, add `PageOneLandingComponent` to `page-one-routing.module.ts` like:

```typescript
import { PageOneLandingComponent } from './page-one-landing/page-one-landing.component';

const routes: Routes = [
  {
    path: '',
    component: PageOneLandingComponent
  }
];
```

And `PageTwoLandingComponent` to `page-two-routing.module.ts`

```typescript
import { PageTwoLandingComponent } from './page-two-landing/page-two-landing.component';

const routes: Routes = [
  {
    path: '',
    component: PageTwoLandingComponent
  }
];
```

And of course, set both as lazy routes in `app-routing.module.ts` like:

```typescript
const routes: Routes = [
  {
    path: '',
    pathMatch: 'full',
    children: []
  },
  {
    path: 'page-one',
    loadChildren: 'app/page-one/page-one.module#PageOneModule'
  },
  {
    path: 'page-two',
    loadChildren: 'app/page-two/page-two.module#PageTwoModule'
  }
];
```

#### Run the application

```
ng serve
```

Then open http://localhost:4200/page-one -- which only has `PageOneModule` . This is optional, and proven unnecessary later below though.

#### Make unrelated change

Now, in VS Code or some other editor, open `page-two-landing.component.ts`, nd make any change, or just save the file without a change if in VS Code

### The log given by the failure.

This is not an error, still interesting:

```
webpack: Compiling...
Hash: 4d750dda0be78cfbbb09                                                         
Time: 388ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry]
chunk {main} main.bundle.js, main.bundle.js.map (main) 6.71 kB {vendor} [initial] [rendered]
chunk {page-one.module.0} page-one.module.0.chunk.js, page-one.module.0.chunk.js.map 4.11 kB {main} [rendered]
chunk {page-two.module.0} page-two.module.0.chunk.js, page-two.module.0.chunk.js.map 4.11 kB {main} [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 171 kB {inline} [initial]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 10.5 kB {inline} [initial]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.48 MB [initial]
webpack: Compiled successfully.
```

Note what was rendered. All lazy modules `page-one` and `page-two` got rendered. I only changed `page-two`, and I'm not even loading it in the browser or anything, it still got updated!

### Desired functionality.

I'd like only the changed lazy modules to be rendered.

So, this line:

```
chunk {page-one.module.0} page-one.module.0.chunk.js, page-one.module.0.chunk.js.map 4.11 kB {main} [rendered]
```

Shouldn't have `[rendered]`.

### Mention any other details that might be useful.

- This is not specific to `ng serve`, it also happens with `ng build --watch`
- Because it's not just `ng serve`, it doesn't make a difference whether the unchanged modules are used on the page or not
- This is also happening with HTML and CSS / SCSS changes
- It's problematic when you have so many lazy modules (which is my actual use case), and they all (or many of them) are loaded at the same time
- This was observed in a real app on Windows 8.1, and the repro was created on Mac OS, so it's not OS specific
- I think this was working as expected before. Maybe up to 1.1 or something, might be due to the (very lovely) feature with lazy module names and incremental numbers in chunk filenames
- Note that if you test this by just saving the file, you'll not see index number increase in chunk names, until you make a real change and save (just a new line will do), and then you'll see the index numbers increase every time you save the file (whether with a change or not)
- A real app build is slower than what's shown above, but due to other issues not this one (I suspect it's writing the assets also with every partial build even when they don't change, because it fails if the assets in output folder are locked, but this one is harder to reproduce, so leaving it aside)

**Comment by jbgraug** [comment]
Same here, although the configuration is a bit different.

- For the url "/" lazy-one.module should be rendered.
- For the url "/two" lazy-two.module should be rendered.

The ParentComponent should be the same instance but i gets re-instantiated upon navigation between
"/" and "two" and vice-versa.

```
const routes: Routes = [
  {
    component: ParentComponent,
    path: '',
    pathMatch: 'full',
    loadChildren: 'app/LazyModuleTwo/lazy-one.module#OneModule'
  },
  {
    path: 'two',
    component: ParentComponent,
    pathMatch: 'full',
    loadChildren: 'app/LazyModuleTwo/lazy-two.module#TwoModule'
  },
];
```

**Comment by filipesilva** [comment]
I think this isn't a problem anymore since we switched to using the `import()` syntax for loadChildren (see https://angular.io/guide/deprecations#loadchildren-string-syntax). If it's still a problem, please let me know.
