### ISSUE TITLE
Proxy adding content-length and/or transfer-encoding: chunked header

### ISSUE THREAD

**Issue by danieljamesscott** [angular/angular-cli#7036]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.1
node: 6.11.1
os: darwin x64
@angular/animations: 4.3.0
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/cli: 1.2.1
@angular/compiler-cli: 4.3.0
@angular/language-service: 4.3.0

### Repro steps.

Proxy a request to a backend server which uses the 'transfer-encoding: chunked' strategy

### The log given by the failure.

[HPM] Error occurred while trying to proxy request /api/backend/content from localhost:4200 to http://localhost:4444 (HPE_UNEXPECTED_CONTENT_LENGTH) (https://nodejs.org/api/errors.html#errors_common_system_errors)

### Desired functionality.

I think this is related to a bug in the express-http-proxy

https://github.com/villadora/express-http-proxy/pull/47

I want to know if the version of the express proxy used by angular-cli contains the fix above

**Comment by filipesilva** [comment]
The CLI just passes on the proxy options to https://github.com/webpack/webpack, that would be a better place to open an issue like this one. To know the version of `express-http-proxy` installed in your project, you can do `npm list express-http-proxy`.
