### ISSUE TITLE
ejected config shouldn't depend on @angular/cli package

### ISSUE THREAD

**Issue by fr0** [angular/angular-cli#7039]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.2.1 (e)
node: 6.10.2
os: darwin x64
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/cli: 1.2.1
@angular/compiler-cli: 4.3.0

### Mention any other details that might be useful.

Use `ng eject`; remove `@angular/cli` from `package.json`. Code will not build due to dependency in ejected `webpack.config.js`:

```
const { GlobCopyWebpackPlugin, BaseHrefWebpackPlugin } = require('@angular/cli/plugins/webpack');
```

I think an ejected config should be independent from the @angular/cli project; I'd like to get rid of the 25+ MB in my `node_modules` folder that it brings (most of which is the duplicate typescript compiler).

**Comment by filipesilva** [comment]
Those plugins are published as part of the CLI and we really don't intend on publishing them outside. The license is pretty permissive though, so feel free to use their code yourself. You can also just remove them.

**Comment by fr0** [comment]
I can certainly subsume those plugins into my project.
However, If I want to remove the `@angular/cli` package from my ejected config, how do I deal with

(in karma.conf.js):

```
    frameworks: ['jasmine', '@angular/cli'],
```
and
```
    preprocessors: {
      './src/test.ts': ['@angular/cli']
    },
```
It's not clear to me how to replace these without having the `@angular/cli` as an explicit dependency.

**Comment by filipesilva** [comment]
That bit is unfortunately much, much more complicated. Our current Karma plugin is very custom. Best advice I can give you is to try and replace it with https://github.com/webpack-contrib/karma-webpack.

**Comment by felangel** [comment]
@filipesilva I have been trying for several hours to decouple my angular starter from the .angular-cli.json and have been unsuccessful. I think it would be very valuable to have a sample project that has been ejected and no longer requires the .angular-cli.json otherwise I think it is very confusing to maintain the project since some configurations need only be updated in webpack while others need to be made in .angular-cli.json. I would think that the whole point of ejecting is to decouple the two.
