### ISSUE TITLE
[Module Driven] Form.Reset() not working!!!

### ISSUE THREAD

**Issue by AhmedBHameed** [angular/angular-cli#7040]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.0.0-beta.28.3.

### Repro steps.
by using Module Driven
Form.reset(); causes error!!!
I can use around solution but i was wondering why this method is not working properly!!! BTY the method is already included with the prototype of the Form object.

### The log given by the failure.

error_handler.js:56 ORIGINAL EXCEPTION: Cannot read property 'length' of null
ErrorHandler.handleError @ error_handler.js:56
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:338
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
error_handler.js:59 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:338
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
error_handler.js:60 TypeError: Cannot read property 'length' of null
    at http://localhost:4200/main.bundle.js:1661:28
    at http://localhost:4200/vendor.bundle.js:7853:49
    at Array.map (native)
    at _executeValidators (http://localhost:4200/vendor.bundle.js:7853:23)
    at http://localhost:4200/vendor.bundle.js:7820:33
    at http://localhost:4200/vendor.bundle.js:7853:49
    at Array.map (native)
    at _executeValidators (http://localhost:4200/vendor.bundle.js:7853:23)
    at FormControl.validator (http://localhost:4200/vendor.bundle.js:7820:33)
    at FormControl.AbstractControl._runValidator (http://localhost:4200/vendor.bundle.js:32579:38)
    at FormControl.AbstractControl.updateValueAndValidity (http://localhost:4200/vendor.bundle.js:32547:33)
    at FormControl.setValue (http://localhost:4200/vendor.bundle.js:32945:14)
    at FormControl.reset (http://localhost:4200/vendor.bundle.js:32998:14)
    at http://localhost:4200/vendor.bundle.js:33310:21
    at http://localhost:4200/vendor.bundle.js:33349:66
ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:338
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
error_handler.js:63 ERROR CONTEXT:
ErrorHandler.handleError @ error_handler.js:63
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:338
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
error_handler.js:64 DebugContext {_view: View_AdCategoriesComponent1, _nodeIndex: 0, _tplRow: 16, _tplCol: 12}component: (...)componentRenderElement: (...)context: (...)injector: (...)providerTokens: (...)references: (...)renderNode: (...)source: (...)_nodeIndex: 0_staticNodeInfo: (...)_tplCol: 12_tplRow: 16_view: View_AdCategoriesComponent1__proto__: Object
ErrorHandler.handleError @ error_handler.js:64
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:338
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
Subscriber.js:242 Uncaught ViewWrappedError {__zone_symbol__error: Error: Error in ./AdCategoriesComponent class AdCategoriesComponent - inline template:16:12 caused b……}

![untitled](https://user-images.githubusercontent.com/25675361/28333883-a5459590-6bf9-11e7-9895-e73e049cb6ee.jpg)

**Comment by Meligy** [comment]
This is not a CLI issue. It looks more like a StackOverflow question to be honest, but if you are certain there is a bug please write specific steps to reproduce it in an empty new application and post it to the https://github.com/angular/angular repository.

Cheers,

**Comment by filipesilva** [comment]
Closing as per @Meligy's comment, thanks 👍
