### ISSUE TITLE
project resume

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#7047]
```
- [X] feature request
```

### Versions.
```
@angular/cli: 1.2.1
node: 6.11.0
os: win32 x64
@angular/*: 4.2.6
@angular/cli: 1.2.1
```

### Desired functionality.
A great feature will be get resume of project or certain folder (especially on big project). Something like  "ng -v". Because when we want speak about our project to someone  gitter/SO (for any reasons: curiosity or help) a question comes up : how many modules/routes/components my project have?

I see a command like `ng --resume (ng -r)`  or `ng --information`. 
Result should be something simple 
Example result of this command:

> Your project have:
> 50 modules,
> 45 routes (33 lazyload)
> 250 components
> You write 123'215 lines of code 

Then we can imagine others more verbose result with many other useful infos.

ps : because cli help developers in many ways, i think this is nice to have and could be part of cli (I know [compodoc](https://github.com/compodoc/compodoc) get more info)

**Comment by jotatoledo** [comment]
Never saw that question in SO or Gitter 😄, would be a nice to have but I cant imagine a situation where this information could be useful for debugging/deploying

**Comment by GoNode5** [comment]
can you remove your icon?

**Comment by istiti** [comment]
Idea might be unseless, I just learn existance of https://github.com/compodoc/compodoc 
## SO AWESOME !!! Better than javadoc :)

**Comment by seangwright** [comment]
@jotatoledo I could see this as being helpful in diagnosing issues here in the repository.

On many issues I see related to performance, maintainers ask how big an app is. Devs often estimate (ex 10 modules) but that's not the whole story.

I think app size could help getting an idea for complexity, use cases and where performance issues might be applicable.

**Comment by mgechev** [comment]
@istiti this is a great idea for an external static code analyzer. Something like compodoc or ngrev would do the trick. Let us keep it outside of the CLI for now but we may want to revisit it in future.
