### ISSUE TITLE
Wiki: add link from ng serve page to proxy-config page

### ISSUE THREAD

**Issue by culli** [angular/angular-cli#7052]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] documentation change (github wiki)
```

Since I can't do a pull request regarding the wiki...

This page https://github.com/angular/angular-cli/wiki/serve should include information about the option `--proxy-config` documented here: https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md

**Comment by filipesilva** [comment]
We actually have all the wiki pages in the repo proper!
https://github.com/angular/angular-cli/blob/master/docs/documentation/serve.md

Would you be available to make a PR there?

**Comment by culli** [comment]
done!  https://github.com/angular/angular-cli/compare/master...culli:patch-1

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/7390

**Comment by filipesilva** [comment]
Thanks for fixing this 👍
