### ISSUE TITLE
&times; in HTML displayed as Ã— in prod build instead of 'X'

### ISSUE THREAD

**Issue by harikrishnan-u01** [angular/angular-cli#7053]
`&times;` in HTML displayed as Ã— in prod build instead of 'x'.
This is working fine in Dev build.

PFB screenshot:

![image](https://user-images.githubusercontent.com/10159959/28380517-944db45c-6c85-11e7-8abc-40fa1d5b3b3d.png)

Can you help in resolving this? 

Am using  "@angular/cli": "1.3.0-beta.0",

Thanks,
Hari

**Comment by harikrishnan-u01** [comment]
Even `&nbsp;` in the HTML code changes to `Â&nbsp;` in --prod build.

I have the following charset in my index.html:

`   <meta charset="utf-8">`

**Comment by harikrishnan-u01** [comment]
Any help?

**Comment by harikrishnan-u01** [comment]
Hi,

The issue was with UTF-8 encoding. Added the following configuration in spring boot to resolve the issue:

spring.messages.encoding=UTF-8
server.tomcat.uri-encoding=UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

Reference: http://netkiller.github.io/java/spring/boot/application.properties.html#charset

Thanks,
Hari

**Comment by filipesilva** [comment]
Closing then.

**Comment by nomykk** [comment]
@harikrishnan-u01  Thanks for saving my time 👍
