### ISSUE TITLE
Not compatible with angular 5.0.0-beta.0

### ISSUE THREAD

**Issue by slubowsky** [angular/angular-cli#7055]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.0-beta.1
node: 7.10.0
os: win32 x64
@angular/animations: 5.0.0-beta.0
@angular/common: 5.0.0-beta.0
@angular/compiler: 5.0.0-beta.0
@angular/core: 5.0.0-beta.0
@angular/forms: 5.0.0-beta.0
@angular/http: 5.0.0-beta.0
@angular/platform-browser: 5.0.0-beta.0
@angular/platform-browser-dynamic: 5.0.0-beta.0
@angular/router: 5.0.0-beta.0
@angular/cli: 1.3.0-beta.1
@angular/compiler-cli: 5.0.0-beta.0
@angular/language-service: 5.0.0-beta.0

### The log given by the failure.

```
>ng serve
Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "5.0.0-beta.0".
```

### Desired functionality.

Support 5.0.0-beta.0 and higher

**Comment by dharders** [comment]
Simple workaround until this is fixed:

Change line 23 of `node_modules\@ngtools\webpack\src\index.js` to:

```javascript
if (!(version.major == '5' || version.major == '4'
```

**Comment by clydin** [comment]
Version 1.2.2 (just released) allows for 5.x.  Ensure that `@ngtools/webpack` is also updated to the latest as well (1.5.2).

**Comment by sumitarora** [comment]
Closing as above.
