### ISSUE TITLE
ng new not working correctly on a fresh Windows 7 install

### ISSUE THREAD

**Issue by RobbieTechie** [angular/angular-cli#7056]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.1
node: 6.11.1
os: win32 x64
@angular/animations: error
@angular/common: error
@angular/compiler: error
@angular/core: error
@angular/forms: error
@angular/http: error
@angular/platform-browser: error
@angular/platform-browser-dynamic: error
@angular/router: error
@angular/cli: error
@angular/compiler-cli: error
@angular/language-service: error

### Desired functionality.
This should hangle the modules install in the ng new step so you don't have to take the extra step, this was working a couple weeks ago just fine.

### Mention any other details that might be useful.
two weeks ago when I created a new project running ng new it all functioned just fine without having to run npm install in addition, so did something change that you now need to run npm install also.  I ended up formatting my whole computer because I thought I screwed something up.  Also trying to uninstlall @angular/cli when you run npm cache clean it gives issues saying it is self healing and I had to force it and that still didn't help.  Also when I installed the cli, I used `npm install @angular/cli@latest`

**Comment by akhilaravind** [comment]
Try running command prompt as administrator and try. Doing so fixed my problem :D

**Comment by RobbieTechie** [comment]
That's not the problem here, it use to automatically do the part where now you also have to switch to your project directory and run npm install.  This all use to happen automatically nice and smooth, so you could just switch to your project directory and run `ng serve` without extra steps.  I brought this up because that appears broken now.  And I am following all the instructions here.  I updated my @angular/cli following their steps on here and these are the results I got.  I also formattted my computer and same thing.  I did try it as administrator and made a new project and the EXACT same thing happened.

**Comment by RobbieTechie** [comment]
They either need to fix it, or update the instructions on their pages about what will happen or what steps you have to take as opposed to the way it is written now.
