### ISSUE TITLE
Component generated with module parameter is not placed inside module folder (only imported in module)

### ISSUE THREAD

**Issue by kmolerov** [angular/angular-cli#7058]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [* ] feature request
```

### Versions.
1.2.1

### Repro steps.
ng generate component MyWidget -m WidgetLibrary

Generated component folder "my-widget" is not subfolder of "widget-library" module folder.
It is created in 'src/app' folder - 'src/app/my-widget' and **only** imported in WidgetLibraryModule.

### Desired functionality.
Component folder to be generated inside specified module folder.
'src/app/widget-library/my-widget'

**Comment by kmolerov** [comment]
This could be an enhancement, as most of the time you would want your component to be created inside the specified module and there is no need to explicitly set the path of the module, which you have already provided with parameter "-m".

**Comment by clydin** [comment]
This behavior is intentional and the purpose of the module option.

The CLI will automatically locate the nearest module based on the current working directory and component path specified.  Specifying the module manually should only be needed in advanced scenarios.

Also, there is the "--flat" option to disable the creation of the component directory if desired.

**Comment by kmolerov** [comment]
But it is not convenient to change directory before executing the command. I want to have single terminal opened to the project root folder and from there to execute all my commands, most of which are not ng-cli related. 
What @clydin explained that you have to navigate to the module directory in which you want to create the component is not practical at all. As I said earlier, it will be much better if you specify module for the generated component to put generated component folder inside the module folder.

**Comment by filipesilva** [comment]
I don't think this would be a very good addition, the `--module` is meant to specify a module to be imported in and shouldn't change the path of the generated component. I think the existing options that @ahaan729 and @clydin highlited work well for this scenario.
