### ISSUE TITLE
Generate service : providers registered in the wrong place if { provide } is present

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#7061]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
cli 1.2.1

### Repro steps.
```
ng new test
cd test
ng g service hello
```

Then in `AppModule`, provide it like this : 

```ts
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [{ provide: HelloService, useClass: HelloService}],
  bootstrap: [AppComponent]
})
```

Now, if you generate new services, with module registering option : 

```
ng g service world --module=app
```

It produces : 
```ts
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [{provide: HelloService, useClass: HelloService, providers: [WorldService]}],
  bootstrap: [AppComponent]
})
```

**Comment by cyrilletuzi** [comment]
The problem may be coming from this function, but didn't find yet why : 
https://github.com/angular/angular-cli/blob/d1e13ace0b83cbdd3bc80d720da30af84faddfcb/packages/%40angular/cli/lib/ast-tools/ast-utils.ts#L192

**Comment by cyrilletuzi** [comment]
@hansl Still there with the schematics

**Comment by denniske** [comment]
Created pull request with fix. Can somebody review?

**Comment by cyrilletuzi** [comment]
@filipesilva @Brocco This issue has been marked as a regression and is 4 months old, and has a PR waiting which is 2 months old. Can someone take care of it ?

**Comment by cyrilletuzi** [comment]
@hansl @filipesilva @Brocco This issue has been marked as a regression and is 5 months old, and has a PR waiting which is 3 months old. Can someone take care of it ?

**Comment by cyrilletuzi** [comment]
Happy to see someone is caring for this issue, but quite disagree with the new severity level : it's not just "inconvenient", it produces code that break compilation. So it should at least be "severity3: broken".

**Comment by cyrilletuzi** [comment]
Will this be fixed in v6 ?

**Comment by cyrilletuzi** [comment]
As in v6 services are not provided in the NgModule anymore, the issue is gone.
