### ISSUE TITLE
Log for npm install is running in the background

### ISSUE THREAD

**Issue by BioPhoton** [angular/angular-cli#7068]
### Bug Report or Feature Request
```
- [x] bug report -> please search issues before submitting
```

### Versions.
@angular/cli: 1.2.1
node: 6.9.0
os: win32 x64

### Repro steps.
ng new xyz

### The log given by the failure.
no failure occurs.

### Desired functionality.
It confuses me that the cli new runs the npm install task async.
It prints: `Installing packages for tooling via npm` followed immediately by the line `Successfully initialized git.` . In a previous version we had logs from the progress. But tha thing that was really confusing was the end of the process: `Project 'angular-workshop' successfully created.`.
This indicates that everything is done.  So because i was missing the npm i progress, what i did was opened the project folder and looked for the node_modules folder. It was not there...   
I closed the console, opened it again and did ng new wxy. In the meantime the node_modules folder was created in the first project. Then i realized that the npm installs now ran async. 

It would be cool to have a small comment that notes that. i.e.: ` Installing packages for tooling via npm. This process runs in the background and will take some time to complete even if the process ends.`

### Mention any other details that might be useful.
I marked the two lines that confuses me below.

Console output:

```
installing ng
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
You can `ng set --global packageManager=yarn`.
```
**```Installing packages for tooling via npm.```**
```
Successfully initialized git.
You can `ng set --global packageManager=yarn`.
```
**```Project 'angular-workshop' successfully created.```**

**Comment by clydin** [comment]
Fixed via https://github.com/angular/angular-cli/pull/7033 and will be in next release.

**Comment by BioPhoton** [comment]
Wow, That PR was i guess the fastest i have ever seen in my live. :-D

Thank you very much!!!

**Comment by tavuntu** [comment]
thanks, I'm seeing the issue as well, glad you guys fixed it.

**Comment by clydin** [comment]
1.2.2 was just released as well.

**Comment by tavuntu** [comment]
hell yeah, thanks

**Comment by sumitarora** [comment]
Closing as above.
