### ISSUE TITLE
Generated a service without the --flat parameter, but it didn't create a new folder for the service

### ISSUE THREAD

**Issue by sarchibald-mdsol** [angular/angular-cli#7073]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Output from: `ng --version`.
@angular/cli: 1.2.1
node: 6.11.0
os: win32 x64
@angular/animations: 4.3.0
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/cli: 1.2.1
@angular/compiler-cli: 4.3.0
@angular/language-service: 4.3.0
PS C:\dev\CDCDashboard\CDCDashboardWeb\client-src\app>
```

### Repro steps.
I'm integrating Angular 4 (using angular-cli). In my angular-cli.json, I have
```
  "apps": [
    {
      "root": "client-src",
      "outDir": "wwwroot",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.css",
        "../node_modules/font-awesome/css/font-awesome.css"
      ],
      "scripts": [
        "../node_modules/bootstrap/dist/js/bootstrap.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
``` 
in order to have the folders match up with what a Visual Studio .NET Core application expects.
I executed: 
```ng generate service pointStatService``` and expected that a "point-stat-service' folder would be created with the appropriate .ts files underneath. Instead, the files were created at the same level as the app.component files (i.e. the root). 
![image](https://user-images.githubusercontent.com/28965834/28437418-650e8908-6d4f-11e7-9f4a-d1f8bf0c3cbb.png)

Am I misunderstanding how this should work?

**Comment by clydin** [comment]
Flat is the default for a service.   You can use "--no-flat" on the command line or change the default for your project, or globally, by adjusting the appropriate  "defaults.service.flat" setting.

**Comment by sarchibald-mdsol** [comment]
Thanks for the clarification. I was able to discern this by looking at
schema.json. It seems that having --flat be false by default for some
things and true by default for others doesn't seem reasonable. The default
should be the same across all things generated. I don't think I should have
to read and then remember the documentation (or schema.json) to determine
the defaults for each artifact that can be generated.

**Comment by clydin** [comment]
The defaults follow the [Angular Style Guide](https://angular.io/guide/styleguide).  Services and Pipes are generally kept at the same level as modules/components.

**Comment by devoto13** [comment]
I agree with @clydin. 

I also think it will be convenient if CLI would show default values in the help message of the command: `$ ng generate --help`.

**Comment by sarchibald-mdsol** [comment]
Ok. I can see how it's following the style guide in that respect. Thanks.

I prefer to have things that are similar in type (such as services) grouped
together. It turns out that using
ng generate service services/sample
will generate a structure that I prefer.

In other words, there are some rules of the Style Guide I disagree with.
I'm not a big fan of a really flat structure.

I suppose ng new SampleProject deviates somewhat also, as it seems that the
"shared" folder is not generated by the tool.

**Comment by filipesilva** [comment]
Closing as answered, thanks @clydin and @devoto13 👍
