### ISSUE TITLE
ng serve on a location different than the root doesn't throw but doesn't work

### ISSUE THREAD

**Issue by thibaultsavary** [angular/angular-cli#7079]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
Windows 10
@angular/cli: 1.2.1
node: 8.1.4
os: win32 x64
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.1
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1

### Repro steps.
create a new project
create some dirs (i.e. `src/app/common/services`)
go to that location ( `./` == `root/src/app/common/services`)
execute `ng serve`

`output`
```
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
 94% asset optimizationwebpack: wait until bundle finished: /                                                                                                                                          Hash: 66e54eab722b0997a
339
Time: 14631ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 177 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 52.8 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 52.5 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.05 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
```
**However, localhost:4200 shows a 404**

**Proposition**
When the actual location isn't the root of the project, `ng serve` should either throw or work.
If it could work it would be nice, but that's far from being a must have feature.
A simple warn/error would be enough in my opinion.

**Comment by jamesc892** [comment]
Agree with a warning for this kind of scenario – it's too late to be developing and feeling all kinds of dumb about things like this. :)

**Comment by filipesilva** [comment]
This is a bug. It should work properly.

**Comment by clydin** [comment]
Closing as resolved as the latest version of the CLI (currently 1.6.7) does not exhibit the behavior described.  If the issue continues to occur, please open a new issue detailing the problem.
