### ISSUE TITLE
preserve-symlinks option not supported with ng test

### ISSUE THREAD

**Issue by Schibum** [angular/angular-cli#7081]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.3.0-beta.1
node: 8.2.0
os: darwin x64

### Repro steps.
ng build/serve command do support --preserve-symlinks option, while ng test does not:
```
$ng build --help | grep sym
  --preserve-symlinks (Boolean) (Default: true) Do not use the real path when resolving modules. 
$ng test --help | grep sym
# empty
$ ng test --preserve-symlinks
The option '--preserve-symlinks' is not registered with the test command. Run `ng test --help` for a list of supported options.
```

### Desired functionality.
I think it'd make sense to support symlinked modules in the test command too.
The test command does not include common build options, while serve does: 
https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/commands/serve.ts#L33
Not sure if that's intentional for some reason or by mistake.

**Comment by filipesilva** [comment]
Yeah I agree it should be available there. `ng test` and `ng build/serve/e2e` do not share options for historical reasons that are now outdated. So we should make those shared.

**Comment by zackarychapple** [comment]
Awesome @filipesilva will this be in 1.4.2?
