### ISSUE TITLE
Problem building for server (node) plateform

### ISSUE THREAD

**Issue by feloy** [angular/angular-cli#7100]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

I'm trying to reproduce the e2e test to build a fresh new project for node platform, without success.

### Versions.
@angular/cli: 1.3.0-rc.0
node: 7.1.0
os: linux x64
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.3.0-rc.0
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1

### Repro steps.
$ ng new cli-univ && cd cli-univ

Then following steps from tests/e2e/tests/build/platform-server.ts:
+ in .angular-cli.json:
  - remove apps/polyfills
  - remove apps/styles  
  - add "platform": "server" in apps
+ in package.json, add: "@angular/platform-server": "^4.2.4"
+ in tsconfig.json, add: "angularCompilerOptions": {
      "entryModule": "app/app.module#AppModule"
  }
+ in src/main.ts, add at the end: export { AppModule } from './app/app.module';
+ in src/app/app.module.ts, 
   - prepend import { ServerModule } from '@angular/platform-server';'
   - imports: [ BrowserModule.withServerTransition({ appId: 'app' }), ServerModule ],
+ npm install
+ ng build
+ cat > index.js
require('zone.js/dist/zone-node');
require('reflect-metadata');
const fs = require('fs');
const { AppModule } = require('./dist/main.bundle');
const { renderModule } = require('@angular/platform-server');
renderModule(AppModule, {
  url: '/',
  document: '<app-root></app-root>'
}).then(html => {
  fs.writeFileSync('dist/index.html', html);
});
^D

Then "node index.js"

### The log given by the failure.
/home/philippe/Devs/cli-univ/node_modules/@angular/core/bundles/core.umd.js:4316
        throw new Error('A platform with a different configuration has been created. Please destroy it first.');
        ^

Error: A platform with a different configuration has been created. Please destroy it first.
    at assertPlatform (/home/philippe/Devs/cli-univ/node_modules/@angular/core/bundles/core.umd.js:4316:15)
    at /home/philippe/Devs/cli-univ/node_modules/@angular/core/bundles/core.umd.js:4300:16
    at _getPlatform (/home/philippe/Devs/cli-univ/node_modules/@angular/platform-server/bundles/platform-server.umd.js:2338:12)
    at renderModule (/home/philippe/Devs/cli-univ/node_modules/@angular/platform-server/bundles/platform-server.umd.js:2378:37)
    at Object.<anonymous> (/home/philippe/Devs/cli-univ/index.js:6:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

### Desired functionality.
dist/index.html should be written

**Comment by clydin** [comment]
`main.ts` only contains the export.  The existing bootstrapping code needs to be cleared out.

**Comment by feloy** [comment]
@clydin That works, thanks! I was also modifying the wrong tsconfig.json file. The one to modify is src/tsconfig.app.json
