### ISSUE TITLE
Compiler won't work if a module path is higher than root

### ISSUE THREAD

**Issue by aminpaks** [angular/angular-cli#7106]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [x] feature request
```
I created two folders and put my example module in folder called `check`, and the angular-cli app in `demo`. Inside of `tsconfig.app.json` I defined `paths` to load `check` module from its folder. But it won't work.

### Versions.
<pre><code>    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.1
node: 7.10.0
os: macOS Sierra (darwin x64)
</code></pre>

### Repro steps.
```sh
git clone git@github.com/aminpaks/ng-lib-test-1.git
cd check
yarn
cd -
cd demo
yarn
yarn start
```

### The log given by the failure.
**angular-cli**
> ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /Users/[removed_path]/check/node_modules/@angular/core/core.d.ts, resolving symbol AModule in /Users/[removed_path]/check/src/a-module.ts, resolving symbol AModule in /Users/[removed_path]/check/src/a-module.ts

This looks like an issue with a recursively loading typings or so. 

### Desired functionality.
If this is not a bug please add this feature so developer could be able to import other modules locally and keep developing.
It's worth mentioning that this will work if the module is inside of the `demo` app folder.

**Comment by grizzm0** [comment]
Not quite sure what you're trying to do here. But it's for development you might want to look into npm link.

**Comment by aminpaks** [comment]
Which part is confusing?
We have two folder, one includes an angular library and the other is consuming it.
I want to have the separated for development purposes, at the end once I publish the lib it won't matter cause I'm able to get it from npm repository.

**Comment by aminpaks** [comment]
Worth mentioning I tried to symlink my module lib to demo but it doesn't work. I saw another bug that makes it not possible to bundle the lib and symlink it inside of `node_modules` in the demo app. But that is not part of this discussion.

**Comment by grizzm0** [comment]
Aight. As I thought. Then npm link is what your looking for.

**Comment by aminpaks** [comment]
You thought right, but it doesn't work. Angular compiler has another bug that won't import symlink folders properly and it gives another error, I think I should have filed this bug with them and not here.

**Comment by aminpaks** [comment]
Anyway, I thought it's easier to consume TS files instead of going through all the process of compiling and so forth. But apparently this is another dead-end!

**Comment by aminpaks** [comment]
I believe that I fixed my issue with help of [this thread](https://github.com/angular/angular/issues/15763).
So I close this issue.
