### ISSUE TITLE
i got this type of error.please help me. how to resolve this type of problem?

### ISSUE THREAD

**Issue by sweetnandha** [angular/angular-cli#7109]
**D:\nandha\Nandhakumar\my-app>ng serve
Your global Angular CLI version (1.2.1) is greater than your local
version (1.2.0). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: cec0eeedf86433c6383f
Time: 12488ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 174 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 130 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 10.6 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.79 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve './css/app.component.css' in 'D:\nandha\Nandhakumar\my-app\src\app'
 @ ./src/app/app.component.ts 16:17-51
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/app/student/student-details.component.ts
Module not found: Error: Can't resolve './css/student-details.component.css' in 'D:\nandha\Nandhakumar\my-app\src\app\st
udent'
 @ ./src/app/student/student-details.component.ts 44:17-63
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/app/student/student.selected.component.ts
Module not found: Error: Can't resolve './css/student-details.component.css' in 'D:\nandha\Nandhakumar\my-app\src\app\st
udent'
 @ ./src/app/student/student.selected.component.ts 51:17-63
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/app/student/student-lists.component.ts
Module not found: Error: Can't resolve './css/student-lists.component.css' in 'D:\nandha\Nandhakumar\my-app\src\app\stud
ent'
 @ ./src/app/student/student-lists.component.ts 43:17-61
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/app/student/student.display.component.ts
Module not found: Error: Can't resolve './css/student.display.component.css' in 'D:\nandha\Nandhakumar\my-app\src\app\st
udent'
 @ ./src/app/student/student.display.component.ts 34:17-63
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.**

i am using below versions for my project:

@angular/cli: 1.2.0
node: 6.11.0
os: win32 x64
@angular/animations: 4.3.0
@angular/cli: 1.2.0
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/compiler-cli: 4.3.0
@angular/language-service: 4.3.0

**Comment by filipesilva** [comment]
I'm sorry, I'd like to help you but it's very hard because you didn't provide a repro. It's very important to provide a repro when opening an issue, without one I have no idea of what you're trying to do, what went wrong or pretty much anything else.

Please open a new issue with a reproduction I can follow.
