### ISSUE TITLE
Changing "ng serve host" from "npm config" returns: "getaddrinfo ENOTFOUND"

### ISSUE THREAD

**Issue by EekoS** [angular/angular-cli#7111]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
`ng -v`
```
@angular/cli: 1.2.3
node: 6.10.3
os: win32 x64
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.3
@angular/compiler-cli: 4.3.1
```

### Repro steps.
I'm looking for a way to use `npm scripts` to set angular-cli's `serve --host` option. This way, I plan to set the hostname with an `npm config set` or something, and still enjoy the benefits of an `npm script` (for example, including `--proxy-config proxy.conf.json`).

Meaning, I wished the following code to simply serve my app through http://10.0.0.111:4200/ and to use the other param I set (`proxy-config`).

**package.json**

     ...
     "config" : { "host" : "10.0.0.111" },
     "scripts": {
       "start": "ng serve --proxy-config proxy.conf.json --host $npm_package_config_host"
     }

**command result**

`npm start` returns

     getaddrinfo ENOTFOUND $npm_package_config_host
     Error: getaddrinfo ENOTFOUND $npm_package_config_host
         at errnoException (dns.js:28:10)
         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
     
     npm ERR! Windows_NT 10.0.15063
     npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
     npm ERR! node v6.10.3
     npm ERR! npm  v3.10.10
     npm ERR! code ELIFECYCLE
     npm ERR! xx@0.0.0 start: `ng serve --proxy-config proxy.conf.json --host $npm_package_config_host`
     npm ERR! Exit status 1

---

**package.json (option 2)**
     ...
     "config" : { "host" : "10.0.0.111" },
     "scripts": {
       "start": "ng serve --proxy-config proxy.conf.json --host localhost --live-reload-host $npm_package_config_host"
     }

**command (2) result**

`npm start` ignores the reloaded host.

### Desired functionality.
Any way to configure the `--host` with `npm config` and `npm scripts` ?

**Comment by filipesilva** [comment]
You sure `npm scripts` is meant to work like that? I don't see anything about variable replacement in https://docs.npmjs.com/cli/run-script...

Well I went to look it up a bit more, and it seems this is a thing! I had no idea: http://www.marcusoft.net/2015/08/npm-scripting-configs-and-arguments.html

But it seems like ti's different for windows: https://stackoverflow.com/questions/30842599/using-package-json-config-object-variables-under-windows)

I hope this helps, but bear in mind it's not related to Angular CLI at all.

**Comment by EekoS** [comment]
I thought the AngularCLI didn't know how to handle then IP correctly - not that NPM didn't pass the value correctly. Thanks!
