### ISSUE TITLE
Warning on build: Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by sinedied** [angular/angular-cli#7112]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```bash
@angular/cli: 1.2.3
node: 7.9.0
os: darwin x64
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.3
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1
```

### Repro steps.

Clone this repo: https://github.com/ngx-rocket/starter-kit/tree/mobile/ionic-routing

Then `npm install && npm run build`

### The log given by the failure.
When building the app, I get this warning from the `ionic-angular` package:
```
WARNING in ./~/ionic-angular/util/ng-module-loader.js
54:11-36 Critical dependency: the request of a dependency is an expression
```
This is due to their lazy loading feature (even though I don't use it).

### Desired functionality.
No warning emitted.

### Mention any other details that might be useful.
Latest [ionic](http://ionicframework.com/) version is used.

From my understanding, this issue is related to properly setup Webpack Context, but I do not see how to use this within Angular CLI. I do not want to use the `eject` command, and the Ionic team do not want to address the issue on their side (seems fair).

I do not know if this is actually a bug or if there is some workaround I do not know of.

**Comment by filipesilva** [comment]
If you don't use it, it should be fine. There isn't any workaround except setting the right context, and that's pretty hard. I don't know how their package works either so it kinda sounds like it's too much work to get around a warning.

I'm closing as something that we aren't planning on doing anything about, but could you link here the ionic issue where the team doesn't think it needs to be addressed? This way other users that come here can get the full context.

If there's a big demand to do away with the warning we can revisit.

**Comment by sinedied** [comment]
Yes the app is working fine anyway, but it's annoying.
I understand it's time consuming for just a warning on your side, so maybe I could try to work on a PR? Do you have a preferred approach? I was thinking of maybe adding an option in `angular-cli.json` to setup webpack [ContextReplacementPlugin](https://webpack.js.org/plugins/context-replacement-plugin/).

This is the issue on Ionic's repo: https://github.com/ionic-team/ionic/issues/12285

**Comment by filipesilva** [comment]
We actually had ContextReplacementPlugin a long time ago just to silence a similar warning from Angular Core, which we ended up 'truly' fixing by setting the right context.

@danbucholtz is it intended that using `ionic-angular` shows this warning unless worked around?
