### ISSUE TITLE
f.Observable.defer is not a function --build-optimizer

### ISSUE THREAD

**Issue by elvirdolic** [angular/angular-cli#7114]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.0-rc.0
node: 8.0.0
os: win32 x64

### Repro steps.

npm --prod --build-optimizer

Build is working without any issues

Starting the app I got a runtime exception

```
main.533cf46….bundle.js:1 ERROR Error: Uncaught (in promise): TypeError: f.Observable.defer is not a function
TypeError: f.Observable.defer is not a function
    at e.W4CS.t.request (main.533cf46….bundle.js:1)
    at e.W4CS.t.requestHelper (main.533cf46….bundle.js:1)
    at e.W4CS.t.get (main.533cf46….bundle.js:1)
    at e.get (main.533cf46….bundle.js:1)
```

angular: 4.3.1
angular-material: 2.0.0-beta.8

using it without --build-optimizer it works without any issues

the defer is comming from angular-jwt

https://github.com/auth0/angular2-jwt/blob/435b8fc48415e57da40a788777a53ba37c906620/angular2-jwt.ts

but it's imported correctly there. I'm not sure why it's not working.

**Comment by scttcper** [comment]
getting same issue with 1.3.0-rc.1 using same angular-jwt

**Comment by filipesilva** [comment]
This is indeed a problem with the build optimizer, related to https://github.com/angular/devkit/issues/51. Will fix.

**Comment by kblestarge** [comment]
Is this issue fixed? I'm getting same problem.

@angular/cli: 1.4.0-rc.1
node: 6.9.3
os: darwin x64
@angular/animations: 4.2.2
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/compiler-cli: 4.2.2
@angular/core: 4.2.2
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic: 4.2.2
@angular/platform-server: 4.2.2
@angular/router: 4.2.2
@angular/cli: 1.4.0-rc.1
@angular/language-service: 4.2.2
typescript: 2.3.4
