### ISSUE TITLE
ng serve Works but open browser to connection timed out

### ISSUE THREAD

**Issue by Peaker14** [angular/angular-cli#7119]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Output from: `ng --version`.@angular/cli: 1.2.3
node: 8.2.0
os: win32 x64
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.3
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1

### Repro steps.

Installed Nodejs 8
npm install -g @angular/cli
ng new my-app
cd my-app
npm install
ng serve

### The log given by the failure.

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: 8993566f456a579d7a5d
Time: 14389ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 177 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 5.34 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 10.5 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.19 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.

When I go to localhost:4200 in Chrome, Mozilla Firefox or IE, it always times out. Any Ideas on what the issue might be?

**Comment by filipesilva** [comment]
No idea. We test on node8 in Travis, and for a while I used node8 myself, and I don't know of it not working. 

If you go back to node 6 does it start working?

**Comment by filipemelo** [comment]
I am having the same issue. Error on any browse with my firewall off: **ERR_CONNECTION_TIMED_OUT**

**My command:**
PS C:\Projects\Test1\ng6> ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-02-06T22:51:05.271Z
Hash: aa9dcefc3a39eb5b732f
Time: 10465ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 22.4 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 550 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 34.7 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 8.43 MB [initial] [rendered]

webpack: Compiled successfully.

**My config:** 
Angular CLI: 1.6.7
Node: 8.9.4
OS: win32 x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0

**Comment by hanblossom** [comment]
mine too. 
node: 8.2.0
os: windows7 x64
After restarting my computer, everything works fine

**Comment by nategurian** [comment]
Wondering if there has been any solution to this. I am getting the same problem.
Node - 9.2.00 
Angular - 6.0.8 
MAC - High Sierra
Times out on any browser

Works as expected on any windows browser

**Comment by mgechev** [comment]
@nategurian no worries, thanks for sharing! I'll wait a few days until @Peaker14 shares his experience.

**Comment by mgechev** [comment]
Closing the issue due to inactivity. If the problem still exists in the latest version of the CLI, please open a new issue following the template and providing a minimal demo where we can reproduce it. Thanks! :-)
