### ISSUE TITLE
Support different index for different apps

### ISSUE THREAD

**Issue by marcincichocki** [angular/angular-cli#7124]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

```bash
@angular/cli: 1.2.0
node: 7.6.0
os: linux x64
@angular/animations: 4.2.3
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/compiler-cli: 4.2.3
@angular/core: 4.2.3
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/platform-server: 4.2.3
@angular/router: 4.2.3
@angular/tsc-wrapped: 4.2.3
@angular/cli: 1.2.0
```

### Desired functionality.

App configuration in `angular-cli.json` should allow to use different input and output path for index file when working with multiple apps. `index.html` might be similiar, but some parts can differ(for example elements within root component/usage of assets based on app or different title in `<head/>`)

#### current behavoir
```json
"apps": [
  {
    "name": "app1",
    "index": "apps/app1/index.html"
  },
  {
    "name": "app2",
    "index": "index-app1.html"
  }
]
```
`app1` will generate folders too: `dist/apps/app1/index.html`
`app2` requires additional configuration, as some servers will not send this file by default

#### possible solution

Support additional type in `index` property:

```typescript
interface App {
  // skipped rest of properties
  index: string | { input: string, output: string }
}
```

##### Comparison with current behavior
```json
{
  "index": "index.html"
}
```
and
```json
{
  "index": {
    "input": "apps/app1/index.html",
    "output": "index.html"
  }
}
```
would produce same output. Please note that there is no breaking changes, as 
```json
{
  "index": "a/index.html"
}
```
would be equivalent to:

```json
{
  "index": {
    "input": "a/index.html",
    "output": "a/index.html"
  }
}
```

**Comment by grizzm0** [comment]
There's already support for different index.html files with a combination of root and outDir.

Example:
```
  "apps": [
    {
      "name": "app1",
      "root": "src/app1",
      "outDir": "dist/app1",
      "index": "index.html"
    },
    {
      "name": "app2",
      "root": "src/app2",
      "outDir": "dist/app2",
      "index": "index.html"
    }
  ]
```

**Comment by marcincichocki** [comment]
@grizzm0 Thanks! I was worried that typescript files(main, polyfills, tests) that were not in `root` would create some weird folder structure, but it all works very well

**Comment by nekkon** [comment]
Unfortunately @grizzm0 's solution did not work with AOT, nor with lazy loaded modules of a shared library. I have an [example](https://github.com/nekkon/angular-cli-library/tree/intellix_grizzm0_suggestion) which replicates the existing angular-cli issues. With @marcincichocki 's suggestion these issues can be temporarily avoided till they are fixed.
