### ISSUE TITLE
ERROR in ./src/main.ts Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'

### ISSUE THREAD

**Issue by marciomsm** [angular/angular-cli#7125]
I am getting `ERROR in ./src/main.ts Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'` when I run `ng build --prod`, but if I run the command `ng build --env=prod` I get success.

Do we have any differences between these commands?

**Comment by ajalmaguer** [comment]
I get the same issue. This is the versions I'm working off of:

```
@angular/cli: 1.1.3
node: 6.11.0
os: darwin x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4
```

**Comment by marciomsm** [comment]
I solved it setting the `zone.js` version to `0.8.14`. I don't know if we have an issue on Angular-CLI or on zone.js.

**Comment by marius-oprea** [comment]
I did a successful ng build -prod a couple of hours ago, but now I get the same error without changing nothing to my project.

**Comment by bcravens** [comment]
@marius-oprea same thing just happened to me.

**Comment by mattrichard** [comment]
I'm getting the same error too. Updating zone.js did not work for me.

**Comment by jh-code** [comment]
Happening here as well. Very odd. Tried messing around with a lot of different versions of Angular, Angular CLI, Zone.js and others with no luck.

**Comment by ctrincones** [comment]
Same here, tried updating zone.js and it did not work

**Comment by bcravens** [comment]
We eventually solved it by mass updating our node packages. Not sure which one solved the problem, wasn't zone.js though.

**Comment by ctrincones** [comment]
@bcravens can you share your package.json?

**Comment by coryrylan** [comment]
Getting the same error as well. Debugging right now. 

```
    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@angular/platform-server": "4.1.3",
    "@angular/router": "4.1.3",
    "@angular/cli": "1.3.0-rc.0",
    "@angular/compiler-cli": "4.1.3",
```

**Comment by marius-oprea** [comment]
updating to @angular/cli 1.2.4  and the other packages to the latest version solved the issue for me.

**Comment by marciomsm** [comment]
Change your package.json to `zone.js: 0.8.14`. Delete `node_modules` folder and run `npm install` again.

**Comment by jh-code** [comment]
Updating anything does not seem to work for me, still getting the error.

**Comment by ctrincones** [comment]
Updating to @angular-cli: 1.2.4 fixed the issue for me.

**Comment by EricABC** [comment]
The patch rc.1 was released to address this, but others still indicate problems with rc.1 here: #7113.  rc.1 fixed most of my apps, but for some sample projects I was using a tsconfig with 'include: []', relying on ng to pass my entrypoint to the compiler.  When using AOT you will get this error even in rc.1 unless you include the entry points explicitly in tsconfig.

**Comment by joseph-mcallister** [comment]
None of the package updating worked for me but enhanced-resolve: 3.3.0 worked. [https://github.com/angular/angular-cli/issues/4551](url)

**Comment by tianyuanzhonglu** [comment]
@angular/cli: 1.2.4 fix the problem

**Comment by philljones** [comment]
@angular/cli: 1.2.4 fixed the problem for me also - this on VSTS Hosted

**Comment by dkro** [comment]
Getting the same error. CLI 1.2.4 and Zone 0.8.14 did not resolve the problem for me

**Comment by nille85** [comment]
Updating to @angular/cli: 1.2.4 also fixed the problem for me.

**Comment by PierreDuc** [comment]
If updating to 1.2.4 doesn't work for you. Make sure you remove your `node_modules` folder and your `package-lock.json`, and run `npm install`. And if even that doesn't work, install `enhanced-resolve@3.3.0`, to avoid installing the faulty package. And if that doesn't work, you should probably be looking at your own code :)

**Comment by atiris** [comment]
Oh, @PierreDuc It would be nice, if you were right...
Everything updated, enhanced-resolve installed... but after all of this I can run only `ng build --aot` without any `Can't resolve 'src\$$_gendir\...` bug. When I run ng commands with i18n option (it can be serve or build like `ng serve --aot --locale sk --i18n-file locale/messages.sk.xmb --i18n-format xmb`), I get **Can't resolve './$$_gendir/app/app.module.ngfactory'** ... and I'm pretty sure this is not due to my code :(

**Comment by flauc** [comment]
@atiris Are you running on linux or windows? For some reason enhanced-resolve: 3.3.0 fixes it for my on windows, but not on linux. It's the same version of npm and node on both machines.

**Comment by PierreDuc** [comment]
@atiris Have you cleared your npm cache, and removed the angular-cli global package?

**Comment by atiris** [comment]
@PierreDuc I do my complete procedure again just now:  
`cd <project>;`  
`delete node_modules;`  
`delete package-lock.json;`  
`npm uninstall @angular/cli -g;`  
`npm cache clean --force;` (last time I run only npm cache verify)  
`npm install @angular/cli -g;`  
`npm cache verify;`  
close / open console;  
`cd <project>;`  
`npm install;`  
`ng --version;` (result: 1.2.4)  
`ng build --aot;` (result: **many errors** type Can't resolve './$$_gendir/app/app.module.ngfactory')
checked package.json --> dependencies already contains "enhanced-resolve": "^3.3.0" but I run also next command
`npm install enhanced-resolve@3.3.0 --save;`
`ng build --aot;` (result: now **everything is OK**)
`ng build --aot --locale sk --i18n-file locale/messages.sk.xmb --i18n-format xmb;` (result: again the same error)

    ERROR in Unsupported
    ERROR in ./src/main.ts
    Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '<project>\src'
     @ ./src/main.ts 3:0-74
     @ multi ./src/main.ts

@flauc I run it on windows. My actual versions:  

    @angular/cli: 1.2.4, node: 8.1.3, npm: 5.3.0, os: win32 x64
    @angular/animations, @angular/common, @angular/compiler, @angular/core, @angular/forms,
    @angular/http, @angular/platform-browser, @angular/platform-browser-dynamic,
    @angular/platform-server, @angular/router, @angular/upgrade, @angular/compiler-cli,
    @angular/language-service: 4.3.1

**Comment by ankeshdave** [comment]
@filipesilva 

I am also having the same problem,

Tried all solutions mentioned above
- Using latest `rc1`
- installed `enhanced-resolve@3.3.0`  still the same error.

The project is newly generated by the command

`ng new my-prj --skip-install --skip-git -dir my-prj --style scss --routing`

**Comment by x-c4mp3r** [comment]
@angular/cli: 1.2.4 fix the problem, but can't ng build --prod --aot, I got

> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
The last fine build was done beofe angular 4.3

**Comment by fred-shepherd** [comment]
Same issue here... only fix for me seems to be changing build script to use `--env=prod` instead of `--prod`.

**Comment by filipesilva** [comment]
Heya, please see https://github.com/angular/angular-cli/issues/7113#issuecomment-317469206 for this issue.

**Comment by nourson** [comment]
Updating to `@angular/cli@1.2.4` and `zone.js@0.8.14`
Then
remove node_modules directory
`npm cache clear`
`npm install`
fixed the issue with `ng build --prod`

**Comment by atiris** [comment]
Hi @filipesilva, did you see that I used the latest angular cli 1.2.4 for test when I got this error here https://github.com/angular/angular-cli/issues/7125#issuecomment-317683022 ? How this https://github.com/angular/angular-cli/issues/7113#issuecomment-317523744 can help me, if I already use angular/cli@1.2.4? Or changing angular cli is not the only thing i have to do according your message? I guess I just do not know what to do. Thank you in advance for the answer.

**Comment by filipesilva** [comment]
@atiris it looks like there might be another problem, related to `--i18n` only. Can you open a new issue where we can track it?

**Comment by atiris** [comment]
@filipesilva sure, here: https://github.com/angular/angular-cli/issues/7133

**Comment by mihau1** [comment]
I can confirm that ng new project-name problem with "$$_gendir/app/app.module.ngfactory" can be resolved by:

`npm install enhanced-resolve@3.3.0 --save;
ng build --prod --aot; (result: now everything is OK)`

also `ng build --prod` its not this same as `nb build --env=prod`

**Comment by andrewrady** [comment]
Updating to `@angular/cli: 1.2.4` worked for me!

**Comment by lroitman** [comment]
We don't use @angular-cli, and the same problem started happening last night. upgrading zone.js didn't help. Anybody have any idea?

**Comment by marciomsm** [comment]
@Iroitman try to delete the `node_modules` folder and `package-lock.json` file and then run `npm install` again!

**Comment by lroitman** [comment]
I installed "enhanced-resolve": "3.3.0", and it helped. Note that "enhanced-resolve": "^3.3.0" failed (it picked 3.4.1, and this caused failure)

**Comment by leovo2708** [comment]
I also got this issue with @angular/cli 1.2.4. After working around, I found the reason from webpack package. You must delete folder enhanced-resolve in webpack/node_modules and run 'ng build --prod' again. It works with me.

**Comment by achieverprince** [comment]
Updating to @angular/cli: **1.2.4** worked for me!

Make sure you are updating @angular/* to latest version ^4.2.4
Then delete **node_modules** and do npm install

**Comment by leovo2708** [comment]
I found there are difference between yarn & npm.
With npm, webpack is installed but no dependency 'enhanced-resolve' is included
With yarn, webpack is installed but dependency 'enhanced-resolve' 3.4.1 is included
When run 'ng build --prod' with yarn packages, 'enhanced-resolve' 3.4.1 causes this issue.

**Comment by leovo2708** [comment]
#7136

**Comment by leovo2708** [comment]
#7136

**Comment by klawel** [comment]
The fix is only working on MacOS for me. I still get the error in my CI environment which runs the build --prod on a node:8.2 docker image based on debian. I updated to @angular/cli 1.2.4 and also fixed the version of enhanced-resolve to 3.3.0.

**Comment by InsaneNaman** [comment]
`ng build --env=prod `

Just try this instead of `ng build --prod`

**Comment by filipesilva** [comment]
`--env=prod` and `--prod` are not the same thing. Please see https://github.com/angular/angular-cli/issues/7113#issuecomment-317472732 for more information about it.

**Comment by VladBozhinovski** [comment]
Changing to "@angular/cli": "1.2.4" fixed the problem. 

> Make sure after changing from 1.0.0 ver to 1.2.4 to npm install before you ng build ...

**Comment by crsepulv** [comment]
My version is:

@angular/cli: 1.0.1
node: 6.7.0
os: win32 x64
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.0.1
@angular/compiler-cli: 4.3.4
 and @mihau1 comment solve my problem : [https://github.com/angular/angular-cli/issues/7125#issuecomment-317723824](url)

**Comment by hsim91** [comment]
My original version is 1.2.1 and @angular/cli: 1.2.4 fixed the problem~

**Comment by howard9104** [comment]
My original version is 1.2.1 and @angular/cli: 1.2.4 fixed the problem~

**Comment by kingsolo50** [comment]
**This worked for me**
Step 1:
Delete the node_modules folder
Step 2: 
Replace your package.json "devDependencies":  with the following;

"@angular/cli": "^1.3.1",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/jquery": "^3.2.11",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"

Step 3;
Run npm install

**Comment by dgroh** [comment]
same issue here, but using `--env=prod` solves the problem, anyways I would like to know what is causing this error

**Comment by dgroh** [comment]
I could fix the issue by running the following commands:

1. `npm install -g @angular/cli@latest`
2. `npm install --save-dev @angular/cli@latest`
3. `rimraf .\node_modules\`
4. `ncu -u`
5. `npm cache clean`
6. `npm install`

**Comment by yassinechabli** [comment]
Could someone told us about the source of this problem . because if i take my case , the command ng build --prod --aot was working fine . i don't change any thing on my project . and after a while . i have the same error ... updating the angular cli to the version 1.2.4 solve the problem for me . but still not getting what was the problem exactly ? . some help please .

**Comment by beauxjames** [comment]
**Note:** Updating to angular-cli 1.2.4 solved the problem that started this thread for our instance of the installation. 

Application development done both on Mac and Windows. 
Deploying to Apache / Docker containers.

<sub>Of course, we also needed to do a fresh npm install.</sub>

**Comment by yassinechabli** [comment]
Thank you @beauxjames  , but i found anoher problem when updating to the 1.2.6 . some module in my application are not working . so what you think sould i do  ? trying to solve this problem and keep the version 1.2.6 of angular or downgrade it to the old version and solve it with another way .

**Comment by achieverprince** [comment]
@yassinechabli 
I was able to solve it in multiple project with CLI 1.2.6 +
Error you are getting now might be related to AOT, you can fix it if you follow the guidelines.
What error you are getting, may be some one can help.
Or search with that error messages separately and fix them.

**Comment by yassinechabli** [comment]
the problem was about a module (ngx-date-picker) that need to be updated also . 
i don't know why , but i upgrade to the last version with some modification in my code  and it works .
thank you @achieverprince  .

**Comment by manishit56** [comment]
below command solved my issue
npm install enhanced-resolve@3.3.0

**Comment by justin48** [comment]
removing node_modules and running npm install worked for me.

**Comment by sanjeevSOPRA** [comment]
Sloved !! 
I had this issue when i was trying the execute ng build  -aot command.
problem slove for me when i changed the version of "@angular/cli": "1.2.0" to "@angular/cli": "1.3.0",

**Comment by imichelakos** [comment]
Sloved !!
I had this issue when i was trying the execute ng build -prod command.
Problem solved by updating the version of "@angular/cli": "1.0.0" to "@angular/cli": "1.3.0".

**Comment by scharlo** [comment]
None of the solutions worked for me, because the issue was about memory. Maybe the command below could work for those who couldn't find a solution. This solved the issue in my case.

node --max_old_space_size=5048 ./node_modules/@angular/cli/bin/ng build --prod

**Comment by tayyab786** [comment]
import React, { Component } from 'react';
import logo from './logo.svg';
 import './image.css';
import Dropdown from 'react-dropdown';
import axios from 'axios';
import { AppRegistry, View, Image,Text, } from 'react-native';
// import 'react-dropdown/style.css';


class App extends Component {
  state=
  {
    selectedFile:null
  }
  fileSelectHandler=event=>{
    // console.log(event.target.files[0]);
    this.setState({
      selectedFile:event.target.files[0]
    })
    // fileUploadHandler=() =>
    // {
    //   axios.post('')
    //
    // }
  }


  render() {

    return (
        <div className="image-upload">
        <View>
        <Image
         source={require('D:\ofc\firstapp\src\bmw.jpg')}
       />
       </View>

        </div>


    );
  }
}

export default App;

m geeting error of
 ./src/practicee.js
Module not found: Can't resolve 'D:ofcirstappsrcmw.jpg' in 'D:\ofc\firstapp\src'

can anyone help me

**Comment by tayyab786** [comment]
geeting error of
./src/practicee.js
Module not found: Can't resolve 'D:ofcirstappsrc�mw.jpg' in 'D:\ofc\firstapp\src'

can anyone help me

**Comment by tayyab786** [comment]
import React, { Component } from 'react';
import logo from './logo.svg';
 import './image.css';
import Dropdown from 'react-dropdown';
import axios from 'axios';
import { AppRegistry, View, Image,Text, } from 'react-native';


class App extends Component {
  state=
  {
    selectedFile:null
  }
  fileSelectHandler=event=>{
    this.setState({
      selectedFile:event.target.files[0]
    })
  
  }

  render() {

    return (
        <div className="image-upload">
        <View>
        <Image
         source={require('D:\ofc\firstapp\src\bmw.jpg')}
       />
       </View>

        </div>


    );
  }
}

export default App;

**Comment by KhizerRehan** [comment]
Trying to build AOT but still unsuccessful! Event tried #7113 giving me following error! kindly help
@filipesilva 

current cli version installed:
![screenshot_1](https://user-images.githubusercontent.com/17727069/41814664-f9621fba-776d-11e8-8e00-245e5bd32eb6.png)


Error screen shot
![screenshot_2](https://user-images.githubusercontent.com/17727069/41814668-02f7eac8-776e-11e8-9065-81c6b22585ed.png)

**Comment by maksof-kashif** [comment]
hello!  angular new version not support .map you have to install this through cmd 
npm install --save rxjs-compat
via this you can enjoy with old technique .
thank you

**Comment by ssjoy76** [comment]
This command is 100% work for solving this problem.
npm install enhanced-resolve@3.3.0

**Comment by rameshpraja** [comment]
I have the same issue
Angular CLI version : 1.0.0
angular version : 4
node : v8.11.3
When I fired ng build --prod then throwing the below error

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/user2/Project/test/streetworkapp/material/loan_calculator/src'
 @ ./src/main.ts 5:0-74
 @ multi ./src/main.ts

ERROR in ./src/$$_gendir async
Module not found: Error: Can't resolve '/home/user2/Project/test/streetworkapp/material/loan_calculator/src/$$_gendir/app/routes/home/home.module.ngfactory.ts' in '/home/user2/Project/test/streetworkapp/material/loan_calculator/src/$$_gendir'
 @ ./src/$$_gendir async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts

ERROR in ./src/$$_gendir async
Module not found: Error: Can't resolve '/home/user2/Project/test/streetworkapp/material/loan_calculator/src/$$_gendir/app/routes/loan/loan.module.ngfactory.ts' in '/home/user2/Project/test/streetworkapp/material/loan_calculator/src/$$_gendir'
 @ ./src/$$_gendir async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts


I have tried with upgrading the @angular/cli latest version as well but I am not able to resolved that production issues.

Please expert team help me.
