### ISSUE TITLE
Module build failed: Error: AotPlugin was detected but it was an instance of the wrong class

### ISSUE THREAD

**Issue by nathanBrenner** [angular/angular-cli#7127]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.4
node: 7.6.0
os: Ubuntu 14.04 
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/compiler-cli: 4.3.1
@angular/core: 4.3.1
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/platform-server: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.4

### Repro steps.

From CircleCI, when webpack compiles, like with any of these three commands:
`ng build --prod --aot`, `ng build --prod`, and `ng test`

### The log given by the failure.

```
ERROR in ./src/polyfills.ts
Module build failed: Error: AotPlugin was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.
    at Object.ngcLoader (/home/ubuntu/my_app/node_modules/@ngtools/webpack/src/loader.js:358:19)

ERROR in ./src/test.ts
Module build failed: Error: AotPlugin was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.
    at Object.ngcLoader (/home/ubuntu/my_app/node_modules/@ngtools/webpack/src/loader.js:358:19)
```

When I run `npm ls @ngtools/webpack`, I get back:

```
project-my_app@0.0.0 /Users/me/repos/my_company/my_app
└── @ngtools/webpack@1.5.3 
```

### Desired functionality.

The app should compile successfully with continuous integration.  I've found some similar issues that are pointing to webpack's multi-compiler without any resolution to this issue.

In my use-case, I have jasmine tests and a build script that updates the aws s3 bucket and aws cloudfront distribution. When I push local changes up to the remote repo, the app should successfully compile so ci can then run the unit tests, then build with production settings and aot to update the production app...without me having to run all of those steps locally.

### Mention any other details that might be useful.

Those cli commands work fine in local development. The only difference with the versions above is that I'm on os: darwin x64.

**Comment by nathanBrenner** [comment]
I created a new cli project and was able to compile the app from circleCI without a problem, so this must be a problem on my existing app.

**Comment by kolkov** [comment]
I have the same error when migrate to `@angular/cli` package. (

**Comment by kolkov** [comment]
This helped for me https://github.com/angular/angular-cli/wiki/stories-1.0-update

**Comment by nathanBrenner** [comment]
@kolkov Which part of the upgrade story resolved this issue? I went through it and updated my version of the cli from 1.2.4 to ^1.3.0, and now when I run `ng serve` I get 

```
20% building modules .../node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:269
				if(_this.profile) {
				        ^

TypeError: Cannot read property 'profile' of null
```

**Comment by nathanBrenner** [comment]
My project version of webpack didn't match the angular cli version, so that resolved the error above, but I'm still getting the AotPlugin error.

**Comment by g-guth** [comment]
Same error here

**Comment by nathanBrenner** [comment]
I cleared my circleCI cache and my build is passing now.

If you go into a build that's failing, in the top left corner of the browser window, click the down arrow next to the `rebuild` button to open the dropdown menu, and select `rebuild without cache`. 

Circle doesn't install everything new when you run a build. It keeps packages from previous versions that look to be the same.

I'm marking this issue closed, as it's more of a CirclCI issue than an issue  with the angular cli.

![screen shot 2017-08-11 at 9 49 40 am](https://user-images.githubusercontent.com/9688337/29223166-713b9482-7e7a-11e7-8647-d9a1edeb45b6.png)

**Comment by yanlee26** [comment]
Same here as well `Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.`
