### ISSUE TITLE
ng test wont finish & hangs

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#7129]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.2.3
node: 6.9.0
os: darwin x64
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.3
@angular/compiler-cli: 4.3.1

### my Karma.conf timeouts

  captureTimeout: 180000,
    browserDisconnectTimeout: 180000,
    browserDisconnectTolerance: 3,
    browserNoActivityTimeout: 180000,
    reportSlowerThan: 2000
```

### Repro steps.

I have like ~300 unit test which used to execute without problem on previous version 1.1.2 and now when I turn them all on it just hangs and after couple minutes HTML reporter shows all success, but command line does not exists. 

When I turn like 50 - 100, then it takes like 1.5 min. untill it start printing something to the console and then exists fine. What I see as difference even with 50 test compared  what was before is it prints only final result like it start with ZERO

```
Chrome 59.0.3071 (Mac OS X 10.12.5): Executed 0 of 50 SUCCESS (0 secs / 0 secs)
```

and then 

```
Chrome 59.0.3071 (Mac OS X 10.12.5): Executed 50 of 50 SUCCESS (0 secs / 0 secs)
```

But before it was more incremental I could see something like:

```
Chrome 59.0.3071 (Mac OS X 10.12.5): Executed 0 of 50 SUCCESS (0 secs / 0 secs)
Chrome 59.0.3071 (Mac OS X 10.12.5): Executed 10 of 50 SUCCESS (0 secs / 0 secs)

Chrome 59.0.3071 (Mac OS X 10.12.5): Executed 30 of 50 SUCCESS (0 secs / 0 secs)

Chrome 59.0.3071 (Mac OS X 10.12.5): Executed 45 of 50 SUCCESS (0 secs / 0 secs)
..
```

It was more progress. 
When I execute each individually all works. 

### Desired functionality.
I wish to be able to execute again all my tests

Any pointers I can execute locally to identify the cause?

**Comment by fkolar** [comment]
*Update*

I went couple times back and forth and it seems Angular-CLI should be fine along with Angular 4.3.1, but the libraries (karma, jasmime, etc.) that are defaulted in package.json in the new version might be an issue.

Still investigating....

**Comment by filipesilva** [comment]
So did using `jasmine-core@2.5.2` fixed your issue? I'd like to look into this and see what's actually going wrong.

Do you suppose it's enough to have 300 simple tests?

**Comment by fkolar** [comment]
Hey, 

Yes this version resolved my issue. I think 300 tests should be suffient. 
Or at least tests where you actually instantiate components do maybe some async actions like clicks. 

If I get time I would try to see if I can replicate it on new `ng new testProblem` project.

**Comment by fkolar** [comment]
I just did quick test , where I created one component and inside this component spec I had 4 tests and replicated them to ~ 500 and it works and run fast. So it might not be the same thing. 

As I have 45 different spe.ts files with different tests. ;-(

**Comment by filipesilva** [comment]
Thanks for getting another look at this. I've seen something similar happening in other projects actually, there's a testing module with a one or two really heavy components and it makes each test take at least 1 sec.

Perhaps you can initialize it once somewhere, import it, and then use `resetTestingModule()` on the `beforeEach`? That might be faster.

/cc @wardbell

**Comment by fkolar** [comment]
Thanks. I have already refactor everything where for each tests I import only nessesary components/modules and now all under in matter of few seconds.

**Comment by chaimmw** [comment]
I had a similar problem, when I added onPush to some components my test just froze when it came to that component.
after removing onPush all tests passed.
