### ISSUE TITLE
It is not possible to build / serve app using parameters for i18n ($$_gendir)

### ISSUE THREAD

**Issue by atiris** [angular/angular-cli#7133]
**This error prevents any production build that uses the translation tool in cli!**  
This is not solved by: https://github.com/angular/angular-cli/issues/7113#issuecomment-317523744

### Bug Report or Feature Request

```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

    @angular/cli: 1.2.4, node: 8.1.3, npm: 5.3.0, os: win32 x64
    All next in 4.3.1: @angular/animations, @angular/common, @angular/compiler, 
    @angular/core, @angular/forms, @angular/http, @angular/platform-browser,
    @angular/platform-browser-dynamic, @angular/platform-server, @angular/router,
    @angular/upgrade, @angular/compiler-cli, @angular/language-service

### Repro steps. (windows)

`ng new itest`  
`cd itest`  
`npm cache verify`  
`npm install`  
`ng build --aot` (result: OK)
edit itest/src/app/app.component.html
`<h1>` changed to `<h1 i18n>`
`ng xi18n --locale en --output-path localize -xmb --out-file messages.en.xmb` (result: OK)
`ng build --aot --locale en --i18n-file localize/messages.en.xmb --i18n-format xmb` (result: ERROR)

### The log given by the failure.

    ERROR in Unsupported
    ERROR in ./src/main.ts
    Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'c:\angular\itest\src'
     @ ./src/main.ts 3:0-74
     @ multi ./src/main.ts

### Desired functionality.

build or serve application without any error

### Mention any other details that might be useful.

The same error when I try to run `ng serve` with i18n options.  
Related to comments: https://github.com/angular/angular-cli/issues/7125#issuecomment-317683022 and https://github.com/angular/angular-cli/issues/7125#issuecomment-317715095  
Steps also here: https://stackoverflow.com/questions/45291642/angular-cli-with-i18n-localization-xmb-file

**Comment by filipesilva** [comment]
@ocombe can you take a look? It seems that something is not supported, but I don't know what.

**Comment by hansl** [comment]
Closing this as obsolete/fixed in Angular 5.
