### ISSUE TITLE
Angular cli Generates Wrong Directory Path in app.module.ts

### ISSUE THREAD

**Issue by djtahl** [angular/angular-cli#7135]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report
- [ ] feature request

### Versions.

node -v : v6.10.0
npm -v : 5.3.0
ng -v : 
```
@angular/cli: 1.2.4
node: 6.10.0
os: darwin x64
```

### Repro steps.

- install the latest angular-cli (version : 1.2.4)
- go in the desired repository
- run the command `ng new myProject`
- go in the created project
- go in myProject/src/app and create a folder "common"
- go in "common" folder 
- run `ng g c myComponent`

### The log given by the failure.
- the component is created at the right location : 
```
installing component
  create src/app/common/my-component/my-component.component.css
  create src/app/common/my-component/my-component.component.html
  create src/app/common/my-component/my-component.component.spec.ts
  create src/app/common/my-component/my-component.component.ts
  update src/app/app.module.ts
```
- but the path written in "app.module.ts" is wrong
```
ERROR in /Users/u.name/myProject/src/app/app.module.ts (5,38): Cannot find module './common/src/app/common/my-component/my-component.component'.

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './common/src/app/common/my-component/my-component.component' in '/Users/u.name/myPoject/src/app'
 @ ./src/app/app.module.ts 10:0-99
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

### Desired functionality.
The path written is constantly adding "src/app" part whereas older version of the cli did not have this behavior
The correct import statement should be : 
`import { MyComponentComponent } from './common/my-component/my-component.component';`

### Mention any other details that might be useful.
This issue has also been reported on StackOverflow by another user : 
https://stackoverflow.com/questions/45293787/angular-cli-generates-wrong-directory-path-in-app-module-ts

**Comment by exequiel09** [comment]
Not only in `app.module.ts`. i have nested modules that contains components which i generate using the command `ng g c <component_name>`. What happens is that it prepends the import path with `./src/app`. It should be `./` or `./<current_working_directory>`.

### Versions.
@angular/cli: 1.2.4
node: 6.11.0
os: darwin x64
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.4
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1

**Comment by fsx999** [comment]
i have the same issue

**Comment by Itisfilipe** [comment]
+1

**Comment by hiepxanh** [comment]
me too

**Comment by filipesilva** [comment]
@Brocco can you have a look?

**Comment by djtahl** [comment]
I've checked on an older angular-cli version and found one that didn't had the issue : 
angular-cli 1.0.6 didn't had this generated path issue

**Comment by deveshjadon98** [comment]
@djtahl same case with me, it was working fine with 1.0.6 but after updating to 1.2.4 it's giving wrong relative path.

**Comment by deveshjadon98** [comment]
I am facing one more issue related to this. After updating to 1.2.4, the import statement of environment file is changed to
 `import { environment } from 'environments/environment';` 
and i had make it relative again manually at every place.

**Comment by cyrilletuzi** [comment]
Any news about this ?

There is currently 3 major problems with generation (this one, #6533 and #7061). Some of them dating from several weeks ago, and I'm quite worried to see new versions of the CLI released without any fix for these major regressions. I tried to help with a PR for one of them, posted one month ago, but which has been completely ignored.

Speed is nice, but a working tool should be a priority. Currently the generation has become so buggy I'm starting to think about stopping to use it during the trainings I do...

**Comment by AndonyNS** [comment]
+1

**Comment by keatkeat87** [comment]
1.3.0 still same..

**Comment by Cornevur** [comment]
Same problem! Terrible!

**Comment by Cornevur** [comment]
Guys, please, fix this problem before moving any further!

**Comment by miguelcaravantes** [comment]
same problem

**Comment by SeanConnell93** [comment]
@djtahl OMG thank you, I just changed it to the right path. Not a nice thing to get when your just new to it.

**Comment by andrewkww** [comment]
This issue has been fixed in the master branch. However, the issue still exist in 1.3.x and 1.4.x branch.

**Comment by filipesilva** [comment]
Fixed via https://github.com/angular/angular-cli/pull/7090

**Comment by INGCRENGIFO** [comment]
same problem :(

**Comment by hansl** [comment]
This issue was fixed in 1.4.0, but not 1.3. We are looking at fixing it in 1.3 as well.

**Comment by andrewkww** [comment]
Great! Thanks @hansl !

**Comment by nemeth-tibor** [comment]
I use 1.6.3 and ng new project-name still results:

Error: Path "/app/app.module.ts" does not exist.
Path "/app/app.module.ts" does not exist.
