### ISSUE TITLE
Short list of cli commands

### ISSUE THREAD

**Issue by jibbers42** [angular/angular-cli#7141]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

==> ng --version 
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.1
node: 6.11.1
os: linux x64
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.1
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1

### Desired functionality.

It is a bit tough to use "ng help" to discover all of the commands due to how long the output is. Also, once you add in the wrapping from a normal sized terminal (100 char width in my case), then it becomes surprisingly difficult.

"ng help --short" or "ng help -s" would show just the commands and maybe their descriptions, but without showing all the switches for each command.

Further, consider making this the default, and having "--long" or "--full" if you really want to see all of that in one shot.

**Comment by filipesilva** [comment]
I agree it's pretty hard to read.

**Comment by catull** [comment]
Not a full solution, this gives a a shorter output:
```bash
ng help | grep -A 2 '^ng '
```

It currently produces:

```log
ng build <options...>
  Builds your app and places it into the output path (dist/ by default).
  aliases: b
--
ng completion <options...>
  Adds autocomplete functionality to `ng` commands and subcommands.
  --all (Boolean) (Default: true) Generate a completion script compatible with both bash and zsh.
--
ng doc <keyword> <options...>
  Opens the official Angular API documentation for a given keyword.
  --search (Boolean) (Default: false) Search whole angular.io instead of just api.
--
ng e2e <options...>
  Run e2e tests in existing project.
  aliases: e
--
ng eject <options...>
  Ejects your app and output the proper webpack configuration and scripts.
  --target (String) (Default: development) Defines the build target.
--
ng generate <blueprint> <options...>
  Generates and/or modifies files based on a blueprint.
  aliases: g
--
ng get <options...>
  Get a value from the configuration. Example: ng get [key]
  --global (Boolean) (Default: false) Get the value in the global configuration (in your home directory).
--
ng help <command-name (Default: all)>
  Shows help for the CLI.

ng lint <options...>
  Lints code in existing project.
  aliases: l
--
ng new <options...>
  Creates a new directory and a new Angular app eg. "ng new [name]".
  aliases: n
--
ng serve <options...>
  Builds and serves your app, rebuilding on file changes.
  aliases: server, s
--
ng set <options...>
  Set a value in the configuration.
  --global (Boolean) (Default: false) Set the value in the global configuration rather than in your project's.
--
ng test <options...>
  Run unit tests in existing project.
  aliases: t
--
ng version <options...>
  Outputs Angular CLI version.
  aliases: v, --version, -v
--
ng xi18n <options...>
  Extracts i18n messages from source code.
  --i18n-format (String) (Default: xlf) Output format for the generated file.
```
