### ISSUE TITLE
Rollup not working in async router module

### ISSUE THREAD

**Issue by lishichao1002** [angular/angular-cli#7143]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.1.0
node: 6.9.5

### Repro steps.

```
//share module
@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        RouterModule,
        HttpModule,
        OurpalmTableModule, //the thrid module
        OurpalmFormModule, //the thrid module
        Daterangepicker, //the thrid module
        PopoverModule.forRoot(), //the thrid module
        TagInputModule //the thrid module
    ],
    declarations: [],
    exports: [
        CommonModule,
        FormsModule,
        RouterModule,
        HttpModule,
        OurpalmTableModule, //the thrid module
        OurpalmFormModule, //the thrid module
        Daterangepicker, //the thrid module
        PopoverModule, //the thrid module
        TagInputModule //the thrid module
    ]
})
export class SharedModule {
}
```

```
//async module , import shared module
@NgModule({
    imports: [
        AsyncRoutingModule,
        SharedModule
    ],
    declarations: [
        AsynOneLevelComponent
    ]
})
export class AsynModule {
}
```
```
// app moudle
@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        BrowserAnimationsModule,
        AppRoutingModule,
        SharedModule
    ],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule {
}
```

when I execute `ng build --aot --prod --sm` . the shared module bundle exists in both vendor.bundle.js and the async module bundle.

I put the mini code in github repo [https://github.com/lishichao1002/angular-asyn-routing-test/tree/dev](https://github.com/lishichao1002/angular-asyn-routing-test/tree/dev)

the source-map-explorer result as follows : 
![vendor bundle](https://user-images.githubusercontent.com/13584162/28604551-091c96d6-71fe-11e7-95e6-53527846d617.jpg)
![scripts bundle](https://user-images.githubusercontent.com/13584162/28604554-1368eeb4-71fe-11e7-9783-54a360d3e14c.jpg)
![async-route-0 bundle](https://user-images.githubusercontent.com/13584162/28604557-1735583e-71fe-11e7-87eb-78d246cd3d7d.jpg)
![async-route-1 bundle](https://user-images.githubusercontent.com/13584162/28604561-19f4f4f8-71fe-11e7-8547-2f02d7beebb0.jpg)

### Desired functionality.

The shared module bundle only exist in vendor.bundle.js . not in async router module.

### Mention any other details that might be useful.

I put the mini code in github repo [https://github.com/lishichao1002/angular-asyn-routing-test/tree/dev](https://github.com/lishichao1002/angular-asyn-routing-test/tree/dev)

**Comment by filipesilva** [comment]
This was fixed by https://github.com/angular/angular-cli/pull/6281, but wasn't in the version of the CLI you are using. If you upgrade to the latest version it should be fixed.

**Comment by lishichao1002** [comment]
@filipesilva 
I update the angular/cli to version 1.2.6. The problem seems to be solved, but it introduces a new problem.
The new problem is the async router module bundle itself twice.

![image](https://user-images.githubusercontent.com/13584162/28811590-ee48847c-76c2-11e7-976a-1af80ef4adbb.png)
![image](https://user-images.githubusercontent.com/13584162/28811652-37790d92-76c3-11e7-80c6-e0d1787dc408.png)
![image](https://user-images.githubusercontent.com/13584162/28811710-85b90250-76c3-11e7-91bc-090613b8e450.png)
![image](https://user-images.githubusercontent.com/13584162/28811752-b6049690-76c3-11e7-9d81-dbdb296e173a.png)
![image](https://user-images.githubusercontent.com/13584162/28811777-e202aca0-76c3-11e7-8c95-db45f706e6df.png)
![image](https://user-images.githubusercontent.com/13584162/28811808-0c32951c-76c4-11e7-91c2-28bb58fb4fb5.png)
![image](https://user-images.githubusercontent.com/13584162/28811839-3c394666-76c4-11e7-9e87-f07a06266641.png)

I update the code to the repo [angular-asyn-routing-test/tree/dev](https://github.com/lishichao1002/angular-asyn-routing-test/tree/dev)

Looking forward to your reply.

**Comment by filipesilva** [comment]
Sorry, I should have been more specific. The functionality added in #6281 (the common chunk) is only present in `1.3.x` for now. The latest release of `1.3.x` is `1.3.0-rc.3`. You should get a new chunk called `commons.chunk.js` that will include the shared libs.
