### ISSUE TITLE
Add generated files to git automatically

### ISSUE THREAD

**Issue by vultix** [angular/angular-cli#7144]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
When creating files using generate (i.e. `ng generate component|module`) it would be great if the cli would automatically add the new files to the git repository.  Currently it only creates the files.

**Comment by foxjazz** [comment]
or type git add .

**Comment by filipesilva** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/358. There is an explanation there of why we don't do this.
