### ISSUE TITLE
Cannot compile fresh app with --aot

### ISSUE THREAD

**Issue by mwager** [angular/angular-cli#7145]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
$ ./node_modules/.bin/ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.4
node: 7.7.1
os: darwin x64
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/flex-layout: 2.0.0-beta.8
@angular/material: 2.0.0-beta.8
@angular/cli: 1.2.4
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1

### Repro steps.

1. `$ ng new MyApp`
2. add following code in app.component.html:

```
<div *ngFor="let item of ['foo', 'bar', 'baz']; let i = index; ">
  Item: {{item}} {{i}}
</div>
```

3. `$ ng serve --aot`

This results in an error:
```
ERROR in ng:///Users/work/Projects/m_re/MyApp/src/app/app.component.html (6,6): Property 'i' does not exist on type 'AppComponent'.
```

### Desired functionality.
App gets AOT compiled and can be visited on localhost:4200

**Comment by Ty3uK** [comment]
`let item of ['foo', 'bar', 'baz']; let i = index;`
According with [docs](https://angular.io/api/common/NgForOf) should be
`let item of ['foo', 'bar', 'baz']; index as i`

**Comment by mwager** [comment]
Leads to the same error :(

Declaring `public i;` as property in the component makes it work, but I think this cannot be the solution

**Comment by Ty3uK** [comment]
`trackBy` is a function, not integer

**Comment by mwager** [comment]
Ok, but still same error:

```
<div *ngFor="let item of ['foo', 'bar', 'baz']; index as i;">Item: {{item}} Index: {{i}}</div>
```

Also with command `$ ng build --aot --prod`

**Comment by mwager** [comment]
Nevermind, reinstalled fresh angular project and the error is gone
