### ISSUE TITLE
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'

### ISSUE THREAD

**Issue by rtm** [angular/angular-cli#7151]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
angular-cli 1.2.0
node 6.x
npm 3.x

### The log given by the failure.

I'm getting a `Module not found` error with no additional information. `--verbose` provides no additional useful information.

What kinds of things could account for this type of error?

```
[rtm@rtm-desktop-15 ~/repos/TNF/identity-ui]$ ng build --prod
Hash: e7dae1738ac862e19a00
Time: 21314ms
chunk    {0} polyfills.71b130084c52939ca448.bundle.js (polyfills) 177 kB {5} [initial] [rendered]
chunk    {1} scripts.cf4bd508b777cd0dcd0a.bundle.js (scripts) 318 kB {5} [initial] [rendered]
chunk    {2} main.37ea370eb898e54aed3a.bundle.js (main) 1.11 kB {4} [initial] [rendered]
chunk    {3} styles.48601ea560e407313063.bundle.css (styles) 69 bytes {5} [initial] [rendered]
chunk    {4} vendor.bfdee3afc7b1496cdc22.bundle.js (vendor) 849 kB [initial] [rendered]
chunk    {5} inline.8ed31a5e25b6accbf838.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/rtm/repos/TNF/identity-ui/src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
[rtm@rtm-desktop-15 ~/repos/TNF/identity-ui]$
```

**Comment by llewellyn1411** [comment]
@rtm What was the solution?

**Comment by handioq** [comment]
@llewellyn1411 update **angular-cli to v1.0.2**6, its solved issue for me.

**Comment by llewellyn1411** [comment]
@handioq Thanks. I have updated to 1.2.6 and it works.

**Comment by adrian-chang-alcover** [comment]
Thanks @llewellyn1411 I updated to 1.2.6 and it works

**Comment by InsaneNaman** [comment]
Working After updating to 1.2.6 . Thanks :smile:

**Comment by IRCraziestTaxi** [comment]
I have tried solutions from half a dozen issues pertaining to this error today and none of them have worked. Is it seriously this difficult to get around this error!?

**Comment by KUSH42** [comment]
`npm install enhanced-resolve@3.3.0`
Did the trick for me

**Comment by djindjic** [comment]
just to link an issue opened on enhanced-resolve repo https://github.com/webpack/enhanced-resolve/issues/114

**Comment by tdekoekkoek** [comment]
I've found that any enums with a 0 cause this error, so:

export enum SearchState {
  simple = 0,
  advanced = 1,
  extended = 2
}

fails, but 

export enum SearchState {
  simple = 1,
  advanced = 2,
  extended = 3
}

does not.

**Comment by apedano** [comment]
Update dependency "@angular/cli": "1.2.6" resolved my problem too,
thank you guys

**Comment by Mehul1995** [comment]
npm install enhanced-resolve@3.3.0 

works for me too!!

**Comment by imuneer** [comment]
Upgrade the angular-cli globally and create a new project then copy the source and compile. It solved my issue. My Angular CLI version after upgraded is 1.4.9 and angular version is 4.2.4.

**Comment by IRCraziestTaxi** [comment]
I left a [https://github.com/angular/angular-cli/issues/4551#issuecomment-339693398](comment) on another issue similar to this one, but my case was actually more like this one - no other errors besides the extremely unhelpful `Can't resolve './$$_gendir/app/app.module.ngfactory' ...`. My problem turned out to be very obscure and I was lucky to find it via trial and error by looking at another new project I had created. Hopefully my comment there will help somebody out with a similar issue to mine.

**Comment by camccar** [comment]
`npm install enhanced-resolve@3.3.0`

Works for me too. Don't know why.  ¯\_(ツ)_/¯

**Comment by iamrajthomas** [comment]
Thank you so very much. This command worked for me on deployment. But could anybody explain how this worked? 
.....
npm install enhanced-resolve@3.3.0

.....

**Comment by nandhuems** [comment]
update npm install enhanced-resolve@3.3.0 
for me it's working fine

**Comment by ssjoy76** [comment]
This command is 100%  work for solving this problem.
npm install enhanced-resolve@3.3.0
