### ISSUE TITLE
Why don't you have the changelog.md file, where can you see what's updated every time

### ISSUE THREAD

**Issue by jiayisheji** [angular/angular-cli#7155]
Why don't you have the changelog.md file, where can you see what's updated every time

**Comment by CDDelta** [comment]
It is now under the [Releases](https://github.com/angular/angular-cli/releases) tab.

**Comment by jiayisheji** [comment]
@CDDelta  thank you

**Comment by grizzm0** [comment]
@jiayisheji Could you please close the issue as it is solved?
