### ISSUE TITLE
Cannot use the new command inside an Angular CLI project

### ISSUE THREAD

**Issue by zhouzhou-96** [angular/angular-cli#7157]
I want to use Angular CLI to start a project.But I can't use the new command inside an Angular CLI project.
![2017-07-27 14 56 56](https://user-images.githubusercontent.com/26320443/28658086-431b9b96-72dc-11e7-962b-0235acdc1e43.png)
How can I solve it?Thank you.

**Comment by grizzm0** [comment]
There is a angular-cli.json somewhere in your path tree. The ng command looks for an angular-cli.json file recursively until it hits the root.

**Comment by filipesilva** [comment]
Closing as answered by @grizzm0 👍

**Comment by pavankumar58** [comment]
Hi 
I have the same issue and can you elaborate on how to check whether there's angular-cli.json in my home dir or not, I don't seem to find it.
Thanks

**Comment by hlthi** [comment]
If you are using Windows, you should delete the package.json, package-lock.json files in the C:/Users/{username} folder.

**Comment by gutocenci** [comment]
Thx o/

**Comment by ASrima** [comment]
I had the similar problem and nothing was working out but then when I ran cmd as administrator it worked for me. First run the Command Prompt as administrator ans then create the new project and if it still doesn't create the project run the code rm -r -f // and then run ng new and then run ng serve and it should work. If nothing works just uninstall node and every other file related to it  and run the previous code again it will work.

**Comment by andreobueno** [comment]
I'm using MacOS and I had this problem today... The way I fixed it was:

1 - I had no idea why, but there was a node_modules and a package.json on my home folder... I removed them;
2 - I also removed a node_modules and package.json from my current project folder
3 - Then, ng new project-name worked :) 

I hope it helps somebody else...

p.s.: Please, angular@cli people, take a look at this weird thing going on... I don't know why angular@cli is creating such files in the home o.O

**Comment by CRanaboldo** [comment]
Same solution , ensuer no node_modules / package.json in the directory

**Comment by Crystyanno** [comment]
zhouzhou-96  Execute o prompt de comando como administrador e, em seguida, crie o novo projeto e ele deve funcionar e quando você usa o IDE, abra como administrador para editar e salvar o projeto. Use também a versão mais recente do nó, se nada funcionar, desinstale e reinstale a versão mais recente e, em seguida, siga o mesmo processo de execução CMD e IDE como administrador.

**Comment by eragon11** [comment]
while execute this command  "ng new your-app-name" check your directory whether it has node_modules and package.json.... if it  has in the directory don't execute that command... change the directory which no node_modules and package.json and try that command it will work/////////

**Comment by sannminwin** [comment]
Same issue. I was solved by deleting package.json and package-lock.json files in user folder on mac.
