### ISSUE TITLE
ng eject webpack hmr not working for html

### ISSUE THREAD

**Issue by Sevenonclick** [angular/angular-cli#7159]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.1.1
node: 6.11.0

### Repro steps.

Before I `ng eject` ,I use `ng serve` to run my project , it runs well , when my html changed ,it will re compile the code.
After I run `ng eject`, it changes my `package.json` and there is a new file `webpack.config.js` appear in my root path, when my html file changed , it has no response. 

It confused me for a long time, I want my webpack sensitive for my html file change

**Comment by jiverson** [comment]
You may need to setup a project demo for this issue I was unable to reproduce it using latest.
   _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.6 (e)
node: 8.2.1
os: darwin x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

**Comment by Kaffiend** [comment]
i'm currently facing the same challenge. The CLI ejection gives you one environment configuration in the `webpack.config` The HMR utilizes a different environment file, and requires `webpack-dev-server`, you have to update the `webpack.config` to handle switching the environment so that the dev server can pick up the changes and use the HMR system.

```
const isProd = (process.env.NODE_ENV === 'production');
const isHMR = (process.env.LAUNCH_MODE === 'hmr')
```
I use gulp so in a series task before the launch of the development workflow i set the LAUNCH_MODE environment variable. You can do something similar in a npm script

```
 if (isProd) {
    plugins.push(new AngularCompilerPlugin({
      "mainPath": "main.ts",
      "platform": 0,
      "sourceMap": true,
      "tsConfigPath": "src/tsconfig.app.json",
      "skipCodeGeneration": true,
      "compilerOptions": {},
      "hostReplacementPaths": {
        "environments/environment.ts": "environments/environment.prod.ts"
      },
      "exclude": []
    }));

    plugins.push(new UglifyJsPlugin({
      "sourceMap": false
    }));

  } else if (!isProd && !isHMR) {
    plugins.push(new AngularCompilerPlugin({
      "mainPath": "main.ts",
      "platform": 0,
      "sourceMap": true,
      "tsConfigPath": "src/tsconfig.app.json",
      "skipCodeGeneration": true,
      "compilerOptions": {},
      "hostReplacementPaths": {
        "environments/environment.ts": "environments/environment.ts"
      },
      "exclude": []
    }));
  } else if (!isProd && isHMR) {
    plugins.push(new AngularCompilerPlugin({
      "mainPath": "main.ts",
      "platform": 0,
      "sourceMap": true,
      "tsConfigPath": "src/tsconfig.app.json",
      "skipCodeGeneration": true,
      "compilerOptions": {},
      "hostReplacementPaths": {
        "environments/environment.ts": "environments/environment.hmr.ts"
      },
      "exclude": []
    }));

  }
```

**Comment by Kaffiend** [comment]
There is something else i'm struggling with, that the CLI handles for setting all the right criteria in the main.ts to bootstrap the client side HMR. The module['hot'] part, i'm not sure where that comes from or what it's looking at to set it properly.

**Comment by Kaffiend** [comment]
ok, so i found that its actually looking for the NODE_ENV to be `'hmr'` as well and it bootstraps everything just fine. I will update the code blocks above to get everything working with an ejected project.

**Comment by Kaffiend** [comment]
It would be nice if the CLI could detect if HMR is configured at the time of ejection and update the `webpack.config.js` accordingly as well as the `package.json`  with the proper scripts.

**Comment by clydin** [comment]
eject functionality is no longer available in the latest version (6.x+).  For custom webpack configurations the following unofficial add-on is a suggested solution: https://github.com/manfredsteyer/ngx-build-plus
