### ISSUE TITLE
Update to latest Angular version

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#7162]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report
- [X] feature request
```

### Versions.
v1.3.0-rc.2

### Question
Why isn't Angular CLI installing the latest Angular Version(currently 4.3.1)? Is there any particular reason?

### Feature request
It may not possible to update Angular CLI with every release of Angular. But it would be nice to have a documentation in the wiki on how to update Angular manually within package.json OR a repository with ready to use package.json's for each new Angular version. A step further Angular CLI could use this repository and provide a CLI command that updates package.json automatically to desired Angular version.

### Motivation
For me im not sure how to update manually. I would start by changing all Angular modules to 4.3.1 but what about any other? rxjs, core-js, zone, etc. - Do they work with the latest Angular? Is it safe to update to latest?

What i did in the past was installing the latest Angular CLI globally, creating a new project, and comparing the package.json with the one in my project.

**Comment by grizzm0** [comment]
AngularCLI does not handle which version of Angular your project is using. It generates a package.json for you from blueprints which you are free to update as it's part of your project.

The current Angular version in the blueprint is ^4.2.4 which translates to >=4.2.4, <5.0.0. With ^4.2.4 you should get the latest version of Angular4.

**Comment by tytskyi** [comment]
@MickL small tip: see https://github.com/angular/angular/blob/4.3.1/package.json#L23 for versions of dependencies

**Comment by MickL** [comment]
Thanks! Documentation  for updating package.json would be cool.

**Comment by clydin** [comment]
I think it's important to reiterate that a new project's package.json is setup to install the latest version of angular and its dependencies.  No changes are required.

**Comment by MickL** [comment]
Okay so actually this was easy. The answer is that there is no need for updating the package.json by hand. Actually All packages do have a carret `^` which means if you type `npm update` they will update to latetest(but not major). ^4.2.4 -> 4.x.x. Thats the only thing i did and now im at 4.3.2
