### ISSUE TITLE
Use ng serve --aot by default ( because ng build --prod is aot by default )

### ISSUE THREAD

**Issue by titusfx** [angular/angular-cli#7163]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions.

@angular/cli: 1.2.3
node: 6.11.0
os: linux x64
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.3
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1

### Repro steps.

ng serve // will compile without --aot
ng build // will compile with aot

### Desired functionality.

ng serve // will be ng serve --aot

This can seems silly but is not, because when you are working with differents modules, you have two options for fast compilation process:

1. Has the module imported directly from you app and compile with it
2. Has multiple applications and create a gulp ( or something, to get the correct order to compile )

The second option is time consuming.

The first option has [these big problems](https://github.com/angular/angular/issues/13590) which some people, has since 2016.

**Comment by samupl** [comment]
Please provide a reason as to why this got closed
