### ISSUE TITLE
Generating a new Angular app fails (@angular/cli@1.3.0-rc.1)

### ISSUE THREAD

**Issue by daniloarcidiacono** [angular/angular-cli#7164]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Operating system: Windows 7 64 bit
```
@angular/cli: 1.3.0-rc.1
node: 6.11.1
os: win32 x64
```
### Repro steps.
Generate a new app with

`ng new TestAngularCLI`

### The log given by the failure.
```
Installing packages for tooling via npm.
npm ERR! code E500
npm ERR! 500 Internal Server Error: @angular/compiler-cli@^4.2.4
```

**Comment by justingrayston** [comment]
I generated a new app ok in #7161 it just didn't build.

That looks like a 500 error at the npm registry rather than an issue with cli.

**Comment by foxjazz** [comment]
Also you should probably run under git instead of a dos  prompt. Install git bash and see if that fixes things.

**Comment by daniloarcidiacono** [comment]
Yes it was an issue with the npm registry (a wrong proxy configuration), not with angular cli.
Closing this issue.
