### ISSUE TITLE
Error during ng serve

### ISSUE THREAD

**Issue by gtzinos** [angular/angular-cli#7166]
Hi,
I am using ng serve command during development and when i change a module path or when i create a new module it needs to close and rerun the command:

ERROR in Cannot read property 'length' of undefined

**Comment by appienvanveen** [comment]
Check your environments configuration. In my case, I had environment**s**.hmr.ts in stead of environment.hmr.ts

**Comment by mgechev** [comment]
Can you still reproduce this error?

**Comment by mgechev** [comment]
Closing the issue due to inactivity. If the problem still exists in the latest version of the CLI, please open a new issue following the template and providing a minimal demo where we can reproduce it. Thanks! :-)
