### ISSUE TITLE
angular cli not conform with angular documentation

### ISSUE THREAD

**Issue by doczoidberg** [angular/angular-cli#717]
Angular Cli projects are not conform with the angular documentation. For example

```
import {HTTP_PROVIDERS, Http} from 'angular2/http';
```
does not work

**Comment by choucry13** [comment]
@doczoidberg , try this => import {HTTP_PROVIDERS, Http} from '@angular/http'
With the rc version, all namespace have change. https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by doczoidberg** [comment]
c:/temp/app1e/tmp/broccoli_type_script_compiler-input_base_path-rlvaekkB.tmp/0/src/main.ts (5, 30): Cannot find module '@angular/http'.

**Comment by choucry13** [comment]
Maybe it's not present on your package.json. Can you check it ?

**Comment by altrim** [comment]
@doczoidberg If you are using the latest version of `angular-cli` you don't have the package installed by default. You need to run `npm install @angular/http --save`

**Comment by doczoidberg** [comment]
I installed the package and added ` "@angular/http": "^2.0.0-rc.1",` to package.json

but still get the same exception

**Comment by doczoidberg** [comment]
works now, thanks

**Comment by fabiobiondi** [comment]
You should also inject HTTP_PROVIDERS in main.ts

`bootstrap(HELLOAppComponent, [HTTP_PROVIDERS]);`
