### ISSUE TITLE
Request ng g component uri

### ISSUE THREAD

**Issue by foxjazz** [angular/angular-cli#7172]
Suggestion:

allow the adding of a parameter which takes uri that returns json data.
Then the component could template a table or unordered list based on that data
so the commands could be ng g component ul uri 
or 
ng g component table uri

**Comment by filipesilva** [comment]
I appreciate the suggestion, and I agree that it is quite common to create components that follow this pattern (fetching data from a URL, displaying a table). 

The way each application does it varies a lot, and the amount of abstractions used as well. For instance, a lot of projects use a data service to fetch and create the appropriate class instances. So ultimately I think this is too specific to the app itself to be generically useful.
