### ISSUE TITLE
New project gets @angular/compiler-cli error

### ISSUE THREAD

**Issue by CraigWarford** [angular/angular-cli#7173]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.5
node: 6.11.1
os: linux x64
@angular/animations: error
@angular/common: error
@angular/compiler: error
@angular/core: error
@angular/forms: error
@angular/http: error
@angular/platform-browser: error
@angular/platform-browser-dynamic: error
@angular/router: error
@angular/cli: error
@angular/compiler-cli: error
@angular/language-service: error

### Repro steps.
nvm use 6.11.1 (newly installed, no packages as yet)
npm i -g @angular/cli
ng new myapp
cd myapp
ng serve

### The log given by the failure.
The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.<anonymous> (/home/craigwarford/.nvm/versions/node/v6.11.1/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/craigwarford/.nvm/versions/node/v6.11.1/lib/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

### Desired functionality.
The expectation is that npm install will properly install everything needed for ng serve to work in a fresh environment.  This is important not only for starting a new application, but also for CI builds.  Changes to the package list that break a clean npm install also breaks existing CI builds.

### Mention any other details that might be useful.
The ng new did end with an odd error on the package install, which may have caused issues with the remainder of the packages installing properly:
94661 verbose stack Error: ENOENT: no such file or directory, rename '/mnt/hgfs/Projects/myapp/node_modules/.acorn-dynamic-import.DELETE/node_modules/acorn' -> '/mnt/hgfs/Projects/myapp/node_modules/acorn-dynamic-import/node_modules/acorn'
94661 verbose stack     at /home/craigwarford/.nvm/versions/node/v6.11.1/lib/node_modules/npm/lib/install/action/finalize.js:64:7
94661 verbose stack     at /home/craigwarford/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
94661 verbose stack     at Array.forEach (native)
94661 verbose stack     at /home/craigwarford/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
94661 verbose stack     at Array.forEach (native)
94661 verbose stack     at asyncMap (/home/craigwarford/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
94661 verbose stack     at moveModules (/home/craigwarford/.nvm/versions/node/v6.11.1/lib/node_modules/npm/lib/install/action/finalize.js:61:5)
94661 verbose stack     at /home/craigwarford/.nvm/versions/node/v6.11.1/lib/node_modules/npm/lib/install/action/finalize.js:56:70
94661 verbose stack     at /home/craigwarford/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/mkdirp/index.js:48:26
94661 verbose stack     at /home/craigwarford/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:267:18
94661 verbose stack
94661 verbose stack Error: ENOENT: no such file or directory, rename '/mnt/hgfs/Projects/myapp/node_modules/.acorn-dynamic-import.DELETE/node_modules/acorn' -> '/mnt/hgfs/Projects/myapp/node_modules/acorn-dynamic-import/node_modules/acorn'
94661 verbose stack     at Error (native)
94662 verbose cwd /mnt/hgfs/Projects/myapp
94663 error Linux 4.4.0-83-generic
94664 error argv "/home/craigwarford/.nvm/versions/node/v6.11.1/bin/node" "/home/craigwarford/.nvm/versions/node/v6.11.1/bin/npm" "install"
94665 error node v6.11.1
94666 error npm  v3.10.10
94667 error path /mnt/hgfs/Projects/myapp/node_modules/.acorn-dynamic-import.DELETE/node_modules/acorn
94668 error code ENOENT
94669 error errno -2
94670 error syscall rename
94671 error enoent ENOENT: no such file or directory, rename '/mnt/hgfs/Projects/myapp/node_modules/.acorn-dynamic-import.DELETE/node_modules/acorn' -> '/mnt/hgfs/Projects/myapp/node_modules/acorn-dynamic-import/node_modules/acorn'
94672 error enoent ENOENT: no such file or directory, rename '/mnt/hgfs/Projects/myapp/node_modules/.acorn-dynamic-import.DELETE/node_modules/acorn' -> '/mnt/hgfs/Projects/myapp/node_modules/acorn-dynamic-import/node_modules/acorn'
94672 error enoent This is most likely not a problem with npm itself
94672 error enoent and is related to npm not being able to find a file.
94673 verbose exit [ -2, true ]

**Comment by foxjazz** [comment]
Do this under git bash.

try uninstall angular-cli first.
npm i -g @angular/cli
and try npm update 
ng new myapp
cd myapp
ng serve

**Comment by CraigWarford** [comment]
@foxjazz - The npm update does do a few things, most notably that it updates npm from 3.10.10 (default with node 6.11.1) to 5.3.0...  However, all aforementioned errors still occur.

**Comment by CraigWarford** [comment]
I note that it's looking for the missing package, @angular/compiler-cli, at the global level.  Installing @angular/cli is not installing that module globally.  Attempting to install it globally throws several dependency warnings:
`/home/craigwarford/.nvm/versions/node/v6.11.1/bin/ngc -> /home/craigwarford/.nvm/versions/node/v6.11.1/lib/node_modules/@angular/compiler-cli/src/main.js
/home/craigwarford/.nvm/versions/node/v6.11.1/bin/ng-xi18n -> /home/craigwarford/.nvm/versions/node/v6.11.1/lib/node_modules/@angular/compiler-cli/src/extract_i18n.js
npm WARN @angular/compiler-cli@4.3.1 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN @angular/compiler-cli@4.3.1 requires a peer of @angular/compiler@4.3.1 but none was installed.
npm WARN @angular/compiler-cli@4.3.1 requires a peer of @angular/core@4.3.1 but none was installed.
npm WARN @angular/tsc-wrapped@4.3.1 requires a peer of typescript@^2.1.5 but none was installed.
npm WARN tsickle@0.21.6 requires a peer of typescript@^2.1.0 but none was installed.

+ @angular/compiler-cli@4.3.1
added 9 packages in 2.401s
`
It does not recognize that I have typescript 2.4.2 installed, either:
`/home/craigwarford/.nvm/versions/node/v6.11.1/lib
├── @angular/cli@1.2.5
├── UNMET PEER DEPENDENCY @angular/compiler@4.3.1
├── @angular/compiler-cli@4.3.1
├── UNMET PEER DEPENDENCY @angular/core@4.3.1
├── lite-server@2.3.0
├── npm@5.3.0
└── typescript@2.4.2

npm ERR! peer dep missing: @angular/compiler@4.3.1, required by @angular/compiler-cli@4.3.1
npm ERR! peer dep missing: @angular/core@4.3.1, required by @angular/compiler-cli@4.3.1
`

**Comment by CraigWarford** [comment]
Found it.  The issue is with attempting to use acorn on /mnt/hgfs, which is essentially a symlink created by VMWare so that I can share folders between Mac and Ubuntu.  This appears to be an issue that comes and goes with acorn: [https://github.com/Microsoft/BashOnWindows/issues/3](url)
