### ISSUE TITLE
Integrate with Workbox for Service Worker

### ISSUE THREAD

**Issue by ShadowManu** [angular/angular-cli#7175]
### Bug Report or Feature Request
- [x] feature request

### Versions.
latest (v1.3.0-rc3)

### Desired functionality.
Service Worker functionality is greatly desired, but sometimes a little problematic to implement automatically but with customizabilty. The folks at [GoogleChrome/workbox](https://github.com/GoogleChrome/workbox) are doing a good job on it. Is it plausible (for mantainability / ease of use) to implement service workers in angular cli piggybacking on it? Internals would be handled by them and the CLI would only have to work on integration.

I'm no master of service worker (neither webpack) but I have some scars with service workers and would love to give in a hand to make the CLI implement them.

**Comment by filipesilva** [comment]
I don't really know the specifics of Workbox itself, but I can say we're looking to add more complete service worker support to CLI apps (not Workbox based). It's one of the major efforts at the moment. There's already some support  (https://github.com/angular/angular-cli/wiki/build#service-worker) but not that complete.
