### ISSUE TITLE
Broken link on docs/documentation/generate.md

### ISSUE THREAD

**Issue by vunguyenhung** [angular/angular-cli#7176]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
```

### Repro steps.
Step 1: Access: https://github.com/angular/angular-cli/blob/master/docs/documentation/generate.md
Step 2: Click any blueprint on the list, it leads to the 404 page.

### Desired functionality.
The link of the blueprints should be `generate/*.md`. Originally, it's missing the `md` file extension.

**Comment by clydin** [comment]
Those files are published to the wiki upon release.  See here: https://github.com/angular/angular-cli/wiki/generate

**Comment by vunguyenhung** [comment]
Oh I forgot about that. Thanks, please close this issue 👍

**Comment by grizzm0** [comment]
@vunguyenhung You can close the issue yourself. :)

**Comment by vunguyenhung** [comment]
Sorry, I'm kinda new to this 😄
