### ISSUE TITLE
Need to disable: Add support for minifying index.html #5753

### ISSUE THREAD

**Issue by ryanmccormick** [angular/angular-cli#7179]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [X] feature request
```
ANGULAR CLI 1.2.6

ALL PLATFORMS (MAC, WINDOWS, LINUX)

I am facing multiple issues...
1. We have a big inline script in our index.html required by New Relic. The minification drops the ending script tag. Also, an inline style tag contained in the header is dropped. 

2. Our CI environment is injecting a bunch of additional corporate scripts in the index html file post build. One is required right after the body tag, another is a try/catch block for handling errors associated with it. And another is a react UI that is driving a navigation menu for our platform. The minification is dropping end script tags and is killing every build.

The only way I have found around this is to go into our environment and manually edit our index.html file after the CI deploys. 

Something needs to be added to disable this on build.

**Comment by ishitatsuyuki** [comment]
Hi, the author here. Is your problem caused by the minifier generating bad HTML? In that case, I will create a fix to disable problematic rules.

**Comment by ishitatsuyuki** [comment]
If I understand correctly, I cannot reproduce the "ending of script tag dropped". Here's what I got when I added an inline head script:

`
<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Example</title><base href="/"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" type="image/x-icon" href="favicon.ico"><script>a = "test";</script><link href="styles.cbe06b9b51ba7be5c100.bundle.css" rel="stylesheet"/></head><body><app-root>Loading…</app-root><script>b = "test";</script><script type="text/javascript" src="inline.93c095ff5331017919e9.bundle.js"></script><script type="text/javascript" src="polyfills.2c74737d6d9a50f8e4dd.bundle.js"></script><script type="text/javascript" src="vendor.ecb3ff2aa3111c134994.bundle.js"></script><script type="text/javascript" src="main.160dba115cb6e2ed4c16.bundle.js"></script></body></html>
`

You may need to inspect your source, and check if it's your source that is producing non-compliant HTML.

**Comment by ryanmccormick** [comment]
Our html is properly formed. All tags start and end properly, etc... Something seems to be throwing off the compiler while parsing over the newrelic script that we are required to add. This is where the end script tag is getting dropped along with an opening style tag in the header. All of that being said, our document is still properly formatted.

If nothing else, there needs to be a mechanism that allows a user to set collapseWhitespace to false on build. 

As a workaround, instead of breaking our CI pattern, I added some sed magic to modify node_modules/@angular/cli/models/webpack-configs/browser.js as a prebuild step. This works but is a hacky approach and will fail if the file structure or configuration structure is changed in the future. 

Please help

**Comment by ishitatsuyuki** [comment]
I can't help, as I cannot reproduce at all. I tried to "steal" and inject the new relic script from their top page, and I still got expected output.

I highly suspect you have tags unclosed. Have you thrown the code into a validator? If not, please do so.

**Comment by filipesilva** [comment]
@ryanmccormick can you provide an anonymized version of an `index.html` that is broken by the minification? If you're unsure of what bits are broken, try to remove sections, running `ng build --prod` and check if the html is still broken.

I am receptive to providing some way to disable it, but not without investigation and proper reproduction of the issue.

**Comment by ryanmccormick** [comment]
I just ran the built source through the html validator on w3c and everything is looking good.
![image](https://user-images.githubusercontent.com/8552328/28781260-17499f0e-75cf-11e7-8bd3-7301eba69586.png).

**Comment by ryanmccormick** [comment]
Deleted my last comment, need to look at something quick

**Comment by ryanmccormick** [comment]
Alright, I have prepared some files:
index-source.html: Normal Source HTML file
index-postbuildminify.html: File post jenkins build with index minification and post script injection. This one is broken.
index-postbuildnomin-working: This one is post build after I added my sed fix to stop whitespace minification. Working.

The issues we are having are likely related to the process of Jenkins (our CI) injecting our corporate single signon and product menu scripts post build. Minification is modifying our html comment placeholders where our scripts are supposed to be injected. 
Example(src):



Turns into(post build/inject):

<script src="https://cdn-stage.somedomain.com/widgets/product-widgets.js"></script>


Minification is altering the structure of the index file and breaking this. Everything was working before. 

For tracking purposes, as a workaround I am currently running a prebuild step to stop whitespace minification: 
```bash
#!/bin/bash
if [ "$(uname)" == "Darwin" ]; then
sed -i '' 's/collapseWhitespace: true/collapseWhitespace: false/' node_modules/@angular/cli/models/webpack-configs/browser.js
else
sed -i 's/collapseWhitespace: true/collapseWhitespace: false/' node_modules/@angular/cli/models/webpack-configs/browser.js
fi
```
[sample-files.zip](https://github.com/angular/angular-cli/files/1188223/sample-files.zip)

**Comment by ishitatsuyuki** [comment]
So do you mean your injector doesn't work at all with minifying? In such cases, the only option would be adding a killswitch to CLI. I don't have time now, so I would appreciate someone implementing it.

**Comment by ryanmccormick** [comment]
That is correct, the injector stops working with the minification. Kill switch would be perfect.

**Comment by clydin** [comment]
Would it be a possibility to fix the injector to handle both the presence or absence of a line break?  From a long-term perspective, removing the root cause of the issue by making the injector more robust would prevent similar issues from occurring in the future and allow for an overall increase of confidence in the final output.

**Comment by ryanmccormick** [comment]
IMHO sounds like a testing nightmare to make something like this more robust to handle both line break or no line break. Line breaks are not created equally - would this handle carriage return plus new line, what if it was just a new line? what if there was an edge case where there is a carriage return w/ new line followed by a new line? Testing nightmare.

Whitespace minification results in very little performance gain. I vote that it be disabled by default and let the user decide to turn it on as part of a build command. 

Our app can't be the only one affected by this and maybe our issues are considered 'edge case', but this is an enterprise app at a fortune six company that supports millions of monthly users.

**Comment by ishitatsuyuki** [comment]
I have made the config as compatible as possible, and I admit that there should be a killswitch. However, minification happens in almost any framework, and it yields better results with SSR.

Most injection tools around the open source ecosystem should handle it without problem, and I guess yours is definitely an edge case.

**Comment by ryanmccormick** [comment]
All injection tools use placeholders to inject code, typically comments. We (myself and other developers at our company) are also limited by what Jenkins already has and what the enterprise allows us to use. There is a big governance process for getting new open source tools approved. All of that being said, if you know of a less invasive injection tool that will work with this, I am totally open. 

In the meantime, As long as the settings for this stay contained in `node_modules/@angular/cli/models/webpack-configs/browser.js`, I can continue using my prebuild solution.

**Comment by filipesilva** [comment]
The mechanism that is ultimately responsible for minifying html providers a way to ignore sections: https://github.com/kangax/html-minifier#ignoring-chunks-of-markup. You should be able to wrap your injection target comment in this.
