### ISSUE TITLE
When I ng new, appmodule does not import FormsModule, HttpModule

### ISSUE THREAD

**Issue by Maybrittnelson** [angular/angular-cli#7184]
### Versions.

@angular/cli: 1.2.4
node: 8.2.1
os: win32 x64

**Comment by grizzm0** [comment]
The code that is generated does not use http nor forms and thus these modules are not needed.

**Comment by Maybrittnelson** [comment]
I see tutorial video, but he get it

**Comment by filipesilva** [comment]
You should ask that to whoever made the video. They were probably using an old version where that happened, but now doesn't anymore.

Closing as answered by @grizzm0.
