### ISSUE TITLE
Add "defaultSeverity": "warning" to tslint.json when scaffolding app

### ISSUE THREAD

**Issue by EvAlex** [angular/angular-cli#7185]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.1
node: 7.10.0
os: win32 x64
Windows 10

### Repro steps.

1. Create an app: `ng new tempApp`
2. Open any .ts file, e.g. `src/main.ts`
3. Make any change that will break tslint rules, e.g. remove semicolon at the end of any line.
4. Run `ng lint`
5. You get ERROR: "path to main.ts"[line, col]: Missing semicolon

### The log given by the failure.

ERROR: C:/Users/Alexander/tempApp/src/main.ts[11, 52]: Missing semicolon

Lint errors found in the listed files.

### Desired functionality.

Default severity for broken tslint rules should be warning. Those red underlines make me feel that I made error, but in fact I just missed some tiny thing. This sometimes is very disturbing. I think, that syntax error or wrong type, missing member etc. error - are real errors, but tslint errors should be warnings by default.

**Comment by clydin** [comment]
Unfortunately, the situation has some complexity to it.  Please see [this PR](https://github.com/angular/angular-cli/pull/6568) for details.

**Comment by filipesilva** [comment]
Closing as per @clydin's comment.
