### ISSUE TITLE
Error on trying to build --prod or serve --prod

### ISSUE THREAD

**Issue by adel12790** [angular/angular-cli#7186]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

Your global Angular CLI version (1.1.2) is greater than your local
version (1.0.4). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

@angular/cli: 1.0.4
node: 6.11.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.4
@angular/compiler-cli: 4.1.3

- windows 10

when trying to run npm run build:prod:aot fails giving me the following error:
ERROR in D:/1.Work/2.Projects/Application/Quintiles/IHRegistery/4.UI/iHreg/src/$$_gendir/app/pages/visit/component/visitInfo/visitInfo.component.ngfactory.ts (3860,30): Property 'Visit' does n
ot exist on type 'VisitInfoComponent'.

and here is the code for this component::
`
/**
 * Created by Dev-Adel on 6/21/2017.
 */
import { Component, Input, OnChanges, OnInit } from '@angular/core';
import { Visit } from '../../../../model/Visit';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { VisitService } from '../../visit.service';
import { Router } from '@angular/router';
import { APIConstants } from '../../../../helpers/Constants/const-apis';
import { Message } from '../../../../model/Message';

@Component( {
  selector: 'cmp-visit-info',
  templateUrl: 'visitInfo.html',
  styleUrls: ['visitInfo.scss'],
} )
export class VisitInfoComponent implements OnInit, OnChanges {
  @Input( 'visitItem' ) visitItem: Visit;
  visitObj: Visit;
  myForm: FormGroup;

  // itemObj: Visit;

  createObj: boolean = true;

  message: Message = new Message();

  constructor( private visitService: VisitService,
               private apiConst: APIConstants,
               private route: Router,
               private fb: FormBuilder ) {
    this.visitObj = new Visit();
  }

  buildForm(): void {
    this.myForm = this.fb.group( {
      visitDate: [null, Validators.required],
      weight: [null, Validators.required],
      height: [null, Validators.required],
      lowPressure: [null],
      highPressure: [null],
      heartRate: [null],
      temp: [null],
      surg: [null],
      dent: [null],
      phys: [null],
      ortha: [null],
      labAss: [null],
      imag: [null],
      trans: [null],
      treat: [null],
      lastComp: [null],
    } );

    this.myForm.valueChanges
      .subscribe( data => this.onValueChanged( data ) );

    this.onValueChanged(); // (re)set validation messages now*/
  }

  onValueChanged( data?: any ) {
    if ( !this.myForm ) {
      return;
    }
    const form = this.myForm;

    for ( const field in this.formErrors ) {
      // clear previous error message (if any)
      this.formErrors[field] = '';
      const control = form.get( field );

      if ( control && control.dirty && !control.valid ) {
        const messages = this.validationMessages[field];
        for ( const key in control.errors ) {
          this.formErrors[field] += messages[key] + ' ';
        }
      }
    }
  }

  ngOnInit() {
    this.buildForm();

    /*this.itemObj = this.router.params.subscribe(params => {
        this.itemObj = params; // (+) converts string 'id' to a number
        console.log('params',this.itemObj);
        if(this.itemObj.id){
            this.createObj=false;

            this.visitObj = this.itemObj;
            /!*this.visitObj.id=this.itemObj.id;
            this.visitObj.visitDate=this.itemObj.visitDate;
            this.visitObj.bloodPressureHigh=this.itemObj.bloodPressureHigh;
            this.visitObj.bloodPressureLow=this.itemObj.bloodPressureLow;
            this.visitObj.dentalProcedures=this.itemObj.dentalProcedures;
            this.visitObj.complicationLastVisit=this.itemObj.complicationLastVisit;
            this.visitObj.heartRate=this.itemObj.heartRate;
            this.visitObj.height=this.itemObj.height;
            this.visitObj.weight=this.itemObj.weight;
            this.visitObj.userId=this.itemObj.userId;
            this.visitObj.imagingProcedures=this.itemObj.imagingProcedures;
            this.visitObj.labAssessmentsProcedures=this.itemObj.labAssessmentsProcedures;
            this.visitObj.orthopedicProcedures=this.itemObj.orthopedicProcedures;
            this.visitObj.patientId=this.itemObj.patientId;
            this.visitObj.physiotherapyProcedures=this.itemObj.physiotherapyProcedures;
            this.visitObj.temperature=this.itemObj.temperature;
            this.visitObj.transfusionLastVisit=this.itemObj.transfusionLastVisit;
            this.visitObj.surgicalOperationProcedures=this.itemObj.surgicalOperationProcedures;
            this.visitObj.treatmentLastVisit=this.itemObj.treatmentLastVisit;*!/

        }else {
            console.log('No params');
        }

    });*/
  }

  ngOnChanges() {
    console.log( 'visit-info', this.visitItem );
    // console.log('visit-info is empty', this.helper.isEmpty(this.visitItem));
    if ( this.visitItem !== undefined ) {
      this.visitObj = this.visitItem;
      this.createObj = false;
    } else {
      this.createObj = true;
    }
  }

  submitVisit() {
    console.log( 'submit' );
    if ( this.createObj ) {
      this.createVisit();
    } else {
      this.updateVisit();
    }
  }

  createVisit(resolve?, reject?) {
    this.visitObj.userId = this.apiConst.getLocalStorageData( this.apiConst.LSUSERID );
    this.visitObj.patientId = this.apiConst.getLocalStorageData( this.apiConst.LSPATIENTID );

    console.log( 'create Obj', this.visitObj );

    this.visitService.createPatientVisit( this.visitObj ).subscribe( res => {
      if ( res.success && res.returnObject !== null ) {
        this.message.type = 'success';
        this.message.body = 'Visit Create Successfully';
        window.location.reload();

        if ( resolve ) {
          resolve( true );
        }

      }
    }, err => {
      console.log( err );
      this.message.type = 'danger';
      this.message.body = 'Visit Creation failed, please try again later.';
      if ( reject ) {
        reject( false );
      }

    } );
  }

  updateVisit(resolve?, reject?) {
    console.log( 'update Obj', this.visitObj );
    this.visitService.updatePatientVisit( this.visitObj, this.visitObj.id ).subscribe( res => {
      console.log( 'res-obj-updated', res );

      if ( res.success ) {
        this.message.type = 'success';
        this.message.body = 'Visit update Successfully';
        window.location.reload();

        if ( resolve ) {
          resolve( true );
        }

      }
    }, err => {
      console.log( err );
      this.message.type = 'danger';
      this.message.body = 'Updating the visit failed, please try again.';

      if ( reject ) {
        reject( false );
      }

    } );
  }

  saveBeforeNavigation(): Promise<boolean> {
    return new Promise( ( resolve, reject ) => {
      if ( this.createObj ) {
        this.createVisit(resolve, reject);
      } else {
        this.updateVisit(resolve, reject);
      }
    } );
  }

  formErrors = {
    visitDate: '',
    weight: '',
    height: '',
    lowPressure: '',
    highPressure: '',
    heartRate: '',
    temp: '',
    surg: '',
    dent: '',
    phys: '',
    ortha: '',
    labAss: '',
    imag: '',
    trans: '',
    treat: '',
    lastComp: '',
  };

  validationMessages = {
    visitDate: {
      'required': 'Regimen Date is required.',
    },
    weight: {
      'required': ' Type is required.',
    },
    height: {
      'required': ' Drug Name is required.',
    },
    lowPressure: {},
    highPressure: {},
    heartRate: {},
    temp: {},
    surg: {},
    dent: {},
    phys: {},
    ortha: {},
    labAss: {},
    imag: {},
    trans: {},
    treat: {},
    lastComp: {},

  };

  beforeSaveValidation( url ) {
    let confirm = window.confirm( 'Save changes?' );

    if ( confirm ) {
      this.saveBeforeNavigation().then( whenResolve => {
        this.route.navigate( [url] );
      }, whenReject => {
        alert( 'couldn\'t save the data. Server error occurred' );
      } );
    }
  }
}

`

**Comment by grizzm0** [comment]
Just like the error tells you you are missing the property "Visit". Anyhow, this is not a support forum. Please us stackoverflow or similar to resolve this instead.

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by adel12790** [comment]
OK, I'm sorry, I was desperate, I solved all the errors occurred, but this one I can't find where should be the problem.
