### ISSUE TITLE
[request/question] ignore lazyloading for server side aot build

### ISSUE THREAD

**Issue by julienR2** [angular/angular-cli#7187]
Hi everyone !

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
> node --version
`v8.1.2`

> npm --version
`5.0.4`

macOs Sierra

### Desired functionality.
I'm using Angular 4 universal with AOT build.
I going one step further in the optimization of the code and try lazy loading (which flickering problems seem to be resolved now).

Luckily and thanks to `@ngtools/webpack` the set up is relatively easy and I could get it to work just by setting up my route like this `loadChildren: './pages/home/home.module#HomeModule'`.

However I realize now that of course the server js benefited from the code splitting too... If it's an awesome feature for browser side, however I have the feeling that on server side, requiring a chunk file instead of just having it all packed into one bundle could be less efficient or at least not so useful.

So I was wondering if there was a way (and if it make sens) to prevent the chunk generation on the server side ?

In dev I build with `awesome-typescript-loader` which seems to ignore the `loadChildren` and just output one bundle, that what makes me wonder if there was not a proper way to "ignore" lazyloading and just build with AOT one big chunk for the server part.

I hope it 's clear and senseful enough !

Thanks for any help !

**Comment by julienR2** [comment]
Hi ! Any idea about I can workaround this for now ?

Does it make sens ? And is it posted in the right repo ?

Thanks for any help !

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by julienR2** [comment]
Hi ! Any idea about I can workaround this for now ?

Does it make sens ? And is it posted in the right repo ?

Thanks for any help !

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by julienR2** [comment]
For those who would run into the same issue, I think I find a workaround using webpack `max-chunk` option like this
```
new webpack.optimize.LimitChunkCountPlugin({maxChunks: 1})
```
(https://github.com/webpack/docs/wiki/optimization#chunks)

I hope it can help !

**Comment by julienR2** [comment]
I'm still interested about your opinion about how senseful my assumption is ;)

**Comment by mgechev** [comment]
@julienR2 the workaround sounds reasonable to me :)
