### ISSUE TITLE
Templates not loading on production

### ISSUE THREAD

**Issue by Christhecoleman** [angular/angular-cli#7188]
### Repro steps.

Everything works fine for me when I run the application in development mode but as soon as I switch to production mode (I am using environments to do so), the project builds fine with no console errors or issues I can see it just displays a blank white page - the javascript is all running fine as I am hitting my back end server and retrieving data it seems to be once it hit's the app.component the ts file loads but the template doesn't render

**Comment by ampgular** [comment]
@Christhecoleman Can you follow the issue template, so we can follow the steps and try to help you?

It iss really difficult to understand what is the issue with your description.

**Comment by Christhecoleman** [comment]
Sorry If I haven't filled the template in correctly, I managed to discover the cause of my issue myself, a member of my team had added versioning to the project and when it development mode displayed the version number on the screen - he had added to the constants file
```
declare function require(moduleName: string): `any;`
const { version: appVersion } = require('../../../../package.json');

static get APP_VERSION(): string { return appVersion; }
```
and then displayed this on the app.component level which broke in production mode once I removed this everything rendered fine - This might not help anyone else but decided to post it just in-case

**Comment by filipesilva** [comment]
Closing as this seems sorted.
