### ISSUE TITLE
FOLLOWING Universal bundles GUIDES not working

### ISSUE THREAD

**Issue by ampgular** [angular/angular-cli#7189]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.6
node: 8.2.1
os: win32 x64
@angular/animations: 4.3.2
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.2
@angular/language-service: 4.3.2
@angular/platform-server: 4.3.2

### Repro steps.

1- EXACTLY followed docs steps and achive to build, different apps, the app [0], browser rendered app, and the app[1] with plattform-server.

2- I  change the "dist-server/main.<hash>.bundle.js"  to "dist-server/main.bundle.js"

3- I try the test explained in the doc  by changing  to the "main.bundle" 
var AppServerModuleNgFactory = require('./dist-server/main.bundle').AppServerModuleNgFactory;

### The log given by the failure.
Error: Cannot find module './dist-server/main.bundle'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\NUILEA WEB 4.0\UNIAPP\src\serveAOT.ts:12:32)
    at Module._compile (module.js:569:30)
    at Module.m._compile (C:\NUILEA WEB 4.0\UNIAPP\node_modules\ts-node\src\index.ts:382:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\NUILEA WEB 4.0\UNIAPP\node_modules\ts-node\src\index.ts:385:12)
    at Module.load (module.js:503:32)

### Desired functionality.
The test should pass and log to the console the server-rendered page.

### Mention any other details that might be useful.
After having try different builds with aot and not aot, I have the impression that when
ng build --app 1 --aot is not doing the aot compilation as I don´t see the expected reduction in the the dist-server filesizes.

can it be then, that the AOT build is not working for the app 1 and therefore the require('./dist-server/main.bundle').AppServerModuleNgFactory; can nor fin the module?

**Comment by chrillewoodz** [comment]
I think you've forgotten to include the hash of the bundle file?

**Comment by filipesilva** [comment]
I'm not sure what docs you followed but we don't support Universal in 1.2.6 at all.

There's some support coming in 1.3.0-rc.3 and up, and you can find a guide in https://github.com/angular/angular-cli/wiki/stories-universal-rendering.

**Comment by ampgular** [comment]
Good to hear it. Thanks.
