### ISSUE TITLE
Add 3rd part components

### ISSUE THREAD

**Issue by lumisoftusa** [angular/angular-cli#719]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by lumisoftusa** [comment]
Please guide how can I add third party components

**Comment by Brocco** [comment]
Take a look in the [wiki](https://github.com/angular/angular-cli/wiki/3rd-party-libs)
