### ISSUE TITLE
--flat has no affect on generating a module

### ISSUE THREAD

**Issue by chrisbruford** [angular/angular-cli#7193]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
angular-cli: 1.0.0-beta.28.3
node: 7.8.0
os: darwin x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/compiler-cli: 2.4.10

OSX 10.12.6
### Repro steps.
ng g m appRouting --flat
ng g module appRouting --flat

### Desired functionality.
To generate a module without the subfolders

**Comment by clydin** [comment]
Please update to the latest stable release (currently 1.2.6).

**Comment by filipesilva** [comment]
Closing as answered by @clydin. For some more context, that option did not exist (or was broken) in the version you are using. But it works in the latest. See https://github.com/angular/angular-cli#updating-angular-cli for update instructions.
