### ISSUE TITLE
preserveSymlinks in defaults doesn't seem to work

### ISSUE THREAD

**Issue by adamdport** [angular/angular-cli#7194]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

1.2.4

### Repro steps.

1. Run the command `ng build --preserveSymlinks`
1. Notice that symlinks are preserved
1. edit `.angular-cli.json`'s `defaults` section to include [preserveSymlinks](https://github.com/angular/angular-cli/wiki/angular-cli) for build 

```
"defaults": {
    "styleExt": "scss",
    "build": {
      "preserveSymlinks": true
    },
    "component": {
    }
}
```

4. Run the command `ng build`
5. Notice that symlinks aren't preserved

### Desired functionality.

`ng build` should either honor the `preserveSymlinks` property value set in defaults

**Comment by filipesilva** [comment]
The option isn't available in the version you are using. I think it's only really there in `@angular/cli@next` for now, which will be the future `1.3.0`.
