### ISSUE TITLE
Schematics Reference CLI Url gives 404

### ISSUE THREAD

**Issue by elhadiahmed** [angular/angular-cli#7196]
In the below Readme file the url of the reference cli gives a 404 error.

[https://github.com/angular/devkit/blob/master/packages/angular_devkit/schematics/README.md](https://github.com/angular/devkit/blob/master/packages/angular_devkit/schematics/README.md)

This is the wrong url
[https://github.com/angular/devkit/tree/master/packages/_/schematics_cli](https://github.com/angular/devkit/tree/master/packages/_/schematics_cli)

it should be
[https://github.com/angular/devkit/tree/master/packages/schematics/angular](
https://github.com/angular/devkit/tree/master/packages/schematics/angular)

**Comment by devoto13** [comment]
Shouldn't this be reported to https://github.com/angular/devkit issues instead? It has nothing to do with CLI.

**Comment by elhadiahmed** [comment]
yes of course, sorry about the confusion.
