### ISSUE TITLE
uglify option

### ISSUE THREAD

**Issue by cortopy** [angular/angular-cli#7199]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
I've created a new `staging` environment. I use the -aot flag for this. However, I would also like to minify and uglify chunks. I can't find any option in [docs](https://github.com/angular/angular-cli/wiki/stories-application-environments) or `ng --help`

It would be great if there was a `--uglify` option

**Comment by devoto13** [comment]
You probably want to use [`--prod` meta flag](https://github.com/angular/angular-cli/wiki/build#--dev-vs---prod-builds), which will automatically enable couple of flags you likely want to have enabled for production build. AoT, uglify, tree-shaking included :)

**Comment by cortopy** [comment]
@devoto13 that wouldn't work with production variables like endpoints. If I did that, then production endpoints would be used in staging

**Comment by devoto13** [comment]
Than you can either use only `--target=production` flag (which enables UglifyJS with other production optiomizations) or override environment with extra flag, e.g. `--prod --environment=staging`.

**Comment by cortopy** [comment]
Thanks @devoto13 . The second solution did work. Would it be a good idea to include this as a comment in the docs? Happy to do the pull request

**Comment by filipesilva** [comment]
@devoto13's answer is the recommended way, you can specifiy target and environment separate. There is already a section of the docs for this: https://github.com/angular/angular-cli/wiki/build#build-targets-and-environment-files
