### ISSUE TITLE
Source maps aren't present with new project using `ng test` (1.2.6)

### ISSUE THREAD

**Issue by erlloyd** [angular/angular-cli#7201]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.2.6
node: 8.2.1
os: darwin x64
@angular/animations: 4.3.2
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.2
@angular/language-service: 4.3.2
```

### Repro steps.

1) Create a new angular cli project with cli 1.2.6
2) Install dependencies
3) Run `ng test`
4) In Chrome, click the DEBUG button
5) Open Chrome Dev Tools and attempt to open `app.component.ts`

EXPECTED: File is present (due to a sourcemap)
ACTUAL: File can't be found

Also, it looks like no sourcemaps are being created for the files: Here's the sources tree under `webpack://`:

<img width="374" alt="screenshot 2017-07-29 17 01 39" src="https://user-images.githubusercontent.com/2145299/28748529-a045b9d8-747f-11e7-8a39-5e6e0deb0ef0.png">

**Comment by Meligy** [comment]
Actually if you try to reload the test debugger page, you'll see the sourcemaps

![image](https://user-images.githubusercontent.com/171637/28749853-8109f144-7518-11e7-8e57-edabae575fa0.png)

**Comment by erlloyd** [comment]
Hmm...you're right. I swear I tried that, but now it's working after a refresh. Sorry for the noise!
