### ISSUE TITLE
Exception gets hidden when '--output-path' is used in production build

### ISSUE THREAD

**Issue by rahul-winner** [angular/angular-cli#7203]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

1.2.3

### Repro steps.

if a component template using a property like below which is not present on component class, then run production build with 

> ng build --prod --output-path target/mydist

### The log given by the failure.

> fs.js:923
>      [echo]   return binding.mkdir(pathModule._makeLong(path),
>      [echo]                  ^
>      [echo]
>      [echo] Error: ENOENT: no such file or directory, mkdir 'C:\git-ws\myapp\ds\myapp-ng\myapp-portal\target\web-build\webapp'
>      [echo]     at Error (native)
>      [echo]     at Object.fs.mkdirSync (fs.js:923:18)
>      [echo]     at licensePlugin.write (C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\license-webpack-plugin\index.js:176:10)
>      [echo]     at licensePlugin.<anonymous> (C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\license-webpack-plugin\index.js:199:12)
>      [echo]     at Compiler.applyPlugins (C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\tapable\lib\Tapable.js:61:14)
>      [echo]     at onCompiled (C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\webpack\lib\Compiler.js:238:12)
>      [echo]     at C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\webpack\lib\Compiler.js:494:13
>      [echo]     at next (C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\tapable\lib\Tapable.js:184:11)
>      [echo]     at Compiler.<anonymous> (C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\webpack\lib\CachePlugin.js:62:5)
>      [echo]     at Compiler.applyPluginsAsyncSeries (C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\tapable\lib\Tapable.js:188:13)
>      [echo]     at C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\webpack\lib\Compiler.js:491:10
>      [echo]     at next (C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\tapable\lib\Tapable.js:184:11)
>      [echo]     at Compilation.compilation.plugin (C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\@angular\cli\plugins\suppress-entry-chunks-webpack-plugin.js:35:17)
>      [echo]     at Compilation.applyPluginsAsyncSeries (C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\tapable\lib\Tapable.js:188:13)
>      [echo]     at self.applyPluginsAsync.err (C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\webpack\lib\Compilation.js:645:19)
>      [echo]     at next (C:\git-ws\myapp\ds\myapp-ng\myapp-portal\node_modules\tapable\lib\Tapable.js:184:11)

### Desired functionality.

> ERROR in C:/git-ws/myapp/ds/myapp-ng/myapp-portal/src/main/webapp/$$_gendir/app/ds/ds-grid/ds-grid.component.ngfactory.ts (242,31): Property 'datasourceName' does not exist on type 'dsGridComponent'.
> 
> ERROR in C:/git-ws/myapp/ds/myapp-ng/myapp-portal/src/main/webapp/$$_gendir/app/ds/ds-grid/ds-grid.component.ngfactory.ts (242,31): Property 'datasourceName' does not exist on type 'dsGridComponent'.

We should be able to identify the erroneous component or its template when using --output-path or outDir. 

Please let me know if you need more information.

### Mention any other details that might be useful.

I also tried using **outDir** in **.angular-cli.json** however, got the same results.

**Comment by clydin** [comment]
As a temporary workaround, the `--no-extract-licenses` option can be used.

**Comment by filipesilva** [comment]
This seems to be a problem with `license-webpack-plugin` that we use, where it tries to create the file directly and files. It probably should be added to the webpack assets instead.

**Comment by rahul-winner** [comment]
thanks @filipesilva 

by the way, I tried with workaround '--no-extract-licenses' and it worked. I'll be glad if someone could provide some solution.
