### ISSUE TITLE
Should platform-server be a devDep?

### ISSUE THREAD

**Issue by justingrayston** [angular/angular-cli#7211]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

In step 0 it states to install platform-server. For npm it uses the `--save-dev` flag, for yarn it doesn't use the `--dev` flag. 

Which should it be? It should be made consistent to avoid confusion.

<img width="747" alt="screen shot 2017-07-31 at 13 37 27" src="https://user-images.githubusercontent.com/5277488/28778086-bb488d2e-75f5-11e7-9962-e18a2230fb26.png">

**Comment by filipesilva** [comment]
Yes, it should be saved as a development dependency. Would you be available to fix this inconsistency? 

You can fix it in https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/universal-rendering.md, and a good name for the commit is `docs: fix universal dep save flag`.
