### ISSUE TITLE
angular-cli doesn't read the global config file ? 

### ISSUE THREAD

**Issue by a-eid** [angular/angular-cli#7214]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.6
node: 8.2.1
os: linux x64

it actually does read it when I execute `get` command 

`ng get defaults.styleExt -g` 

but when I generate a new project the global file is totally ignored ?

**Comment by filipesilva** [comment]
Duplicate of #5599
