### ISSUE TITLE
No sourcemaps for component styles (inline)

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#7218]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report
- [ ] feature request
```

### Versions.
v1.3.0-rc.3

### Repro steps.
Add a style to app.component.scss. E.g. `h1 { color: red; }`. Compile (ng start / build) with `--sourcemap true`.

The styles will have no sourcemaps:
```
<style>h1[_ngcontent-c0] {
  color: red; }</style>
```

### Desired functionality.
`--sourcemap true` should generate sourcemaps for component's styles, too.

**Comment by filipesilva** [comment]
This is actually something that needs to be implemented in Angular itself. See https://github.com/angular/angular/pull/14175 for more information.

**Comment by MickL** [comment]
Closed 6 month ago but not in any release? :(

**Comment by filipesilva** [comment]
Check the last comment in that issue: https://github.com/angular/angular/pull/14175#issuecomment-294876457
