### ISSUE TITLE
Compile component styles into styles.bundle.css

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#7219]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report
- [X] feature request
```

### Versions.
v1.3.0-rc.3

### Repro steps.
Compile (ng start / build) with `--extract-css true`. Styles set in `.angular-cli.json` will be bundled into a single file (correct). Component styles are still inline (and, btw, have no sourcemaps).

### Further question
Is it possible to concat component-styles with the main style.bundle.css to have a single css-file only? If this is done before sass runs, this would also solve https://github.com/angular/angular-cli/issues/1253

**Comment by filipesilva** [comment]
This is actually by design. Component styles are isolated and get special handling by the AOT compiler. So in that sense there is no point to try and put it in the global styles.

#1253 is solved by importing the css variables into the component css. It might be tedious, but it is correct since they are isolated. If you don't care about the isolation you can turn view encapsulation off and just use global styles anyway.

**Comment by mafalarz** [comment]
Since inline styles are violating CSP, then Angular 2 becomes unusable in environments that require the use of restrictive CSP

**Comment by psmyrdek** [comment]
Imagine such case:

1. I'm building a dynamic app using Angular - all the styles sit next to components
2. I want to use the same styles on the landing page where .js is not needed, and I want to server-render "component-like" html to show users what's waiting for them after signing in
3. Without the possibility to extract component styles... all of that is not possible

That's really, really bad idea.

**Comment by MickL** [comment]
You dont have to use component styles. Component styles are lazy loaded with the corresponding module and applied using shadow dom (emulation). They are not made formusage outside at all. But you can write your global styles they are great for overall styling. 

I think it is correct that this issue is closed.
