### ISSUE TITLE
Support --name option on ng new

### ISSUE THREAD

**Issue by spboyer** [angular/angular-cli#722]
Do not want to have the core component named the same as the root/project name.  

**Desired** 
```
ng new quickstart-ng-cli --name quickstart --sn
```

**Actual**
```
mkdir quickstart-ng-cli
cd quickstartng-cli
ng init --name quickstart --sn
```

**Comment by te-je** [comment]
Not sure if this is exactly what you're looking for, but is it different from:

```
ng new quickstart --sn --directory quickstart-ng-cli
```

**Comment by spboyer** [comment]
@te-je Yes! that is exactly the function. Thanks. options are not well documented.
