### ISSUE TITLE
Using build-option "base-href" for htaccess, too

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#7220]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report
- [X] feature request
```

### Versions.
latest

### Description
With Angular CLI the base href in index.html can be set on build, e.g. `ng --base-href /folder/subfolder/someproject/`. This is very useful for automatic deployment processes.

But projects like this may require a .htaccess also setting a base like so: `RewriteRule ^(.*) /folder/subfolder/someproject/index.html [NC,L]`

Is it possible (with Webpack?) to set the path within htaccess also by use of base-href? Or could you add an option for this?

**Comment by filipesilva** [comment]
I would not add an option for this, no. That's specific to that deployment server, and adding options that only work for a specific deployment option is a slippery slope to get started on. 

I think doing it manually is good enough for now, and the deployment page of the docs (https://angular.io/guide/deployment) lists common configuration.

**Comment by MickL** [comment]
Is it possible to access set base-href in webpack and hook somewhere?

**Comment by filipesilva** [comment]
No, there is no hook support currently. Personally I'd use a npm script for it `"build-prod": "ng build --prod --base=href /path/to/folder/ && command-to-replace-text"`.
