### ISSUE TITLE
(1.2.6) Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by SimonHawesome** [angular/angular-cli#7221]
```
- [x] bug report
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.6
node: 8.2.1
os: win32 x64
@angular/animations: 4.3.2
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.2
@angular/language-service: 4.3.2

### Repro steps.
Ran a clean install of Angular CLI (1.2.6) on my machine this morning (07/31/2017) and am getting an error in the browser when running `ng serve` or opening index.html after running `ng build`. As a result, nothing loads on screen.

### The log given by the failure.

Uncaught TypeError: undefined is not a function                         common.es5.js:3084 

(anonymous function)common.es5.js:3084 combine                    common.es5.js:2934 webpackJsonp.../../../common/@angular/common.es5.js             bootstrap 98ea677b4159c7bace8e:54 __webpack_require__core.es5.js:14792 webpackJsonp.../../../platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js                  bootstrap 98ea677b4159c7bace8e:54 __webpack_require__environment.ts:8 webpackJsonp.../../../../../src/main.ts
                                                                                                       bootstrap 98ea677b4159c7bace8e:54 __webpack_require_                                                                       _main.ts:11 
webpackJsonp.2                                                                            bootstrap 98ea677b4159c7bace8e:54 __webpack_require__                                                                     bootstrap 98ea677b4159c7bace8e:25 webpackJsonpCallback                                                                 main.bundle.js:1 
(anonymous function)

**Comment by SimonHawesome** [comment]
Tried installing and serving on my mac at home and could not recreate the error. Will do more tests and reopen ticket if necessary.

**Comment by n00b42** [comment]
Just leaving that here: I had a similar error some time ago which was caused by using an non-latest browser (an older Android phone in that case) and not including all necessary polyfills.
