### ISSUE TITLE
Error while page load / after successful ng serve

### ISSUE THREAD

**Issue by Meistercoach83** [angular/angular-cli#7235]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```
After I did an npm install and ng serve, webpack says, that it "Compiled successfully."
When I try to load the page in the browser, the following error occurs.

### Versions.
 ```
@angular/cli: 1.3.0-rc.1
node: 7.3.0
os: win32 x64
@angular/animations: 5.0.0-beta.0
@angular/cli: 1.3.0-rc.1
@angular/common: 5.0.0-beta.0
@angular/compiler: 5.0.0-beta.0
@angular/core: 5.0.0-beta.0
@angular/forms: 5.0.0-beta.0
@angular/http: 5.0.0-beta.0
@angular/platform-browser: 5.0.0-beta.0
@angular/platform-browser-dynamic: 5.0.0-beta.0
@angular/router: 5.0.0-beta.0
@angular/compiler-cli: 5.0.0-beta.1
@angular/platform-server: 5.0.0-beta.1
```

npm --version: 5.3.0

### The log given by the failure.
> ERROR SyntaxError: JSON.parse: bad control character in string literal at line 488 column 45 of the JSON data
> Stack-Trace:
> ../../../http/@angular/http.es5.js/Body.prototype.json@http://localhost:4200/vendor.bundle.js:194296:20
> ../../../../@ngx-translate/http-loader/src/http-loader.js/TranslateHttpLoader.prototype.getTranslation/<@http://localhost:4200/vendor.bundle.js:4297:42
> ../../../../rxjs/operator/map.js/MapSubscriber.prototype._next@http://localhost:4200/vendor.bundle.js:126014:22
> ../../../../rxjs/Subscriber.js/Subscriber.prototype.next@http://localhost:4200/vendor.bundle.js:122691:13
> onLoad@http://localhost:4200/vendor.bundle.js:194725:21
> ../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:2833:17
> onInvokeTask@http://localhost:4200/vendor.bundle.js:176362:24
> ../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:2832:17
> ../../../../zone.js/dist/zone.js/</</Zone.prototype.runTask@http://localhost:4200/polyfills.bundle.js:2600:28
> ../../../../zone.js/dist/zone.js/</</ZoneTask.invokeTask@http://localhost:4200/polyfills.bundle.js:2907:24
> invokeTask@http://localhost:4200/polyfills.bundle.js:3773:9
> globalZoneAwareCallback@http://localhost:4200/polyfills.bundle.js:3791:17

**Comment by filipesilva** [comment]
That's sounds like some kind of problem in your application. Seems like you're trying to parse something that isn't actually JSON:

```
ERROR SyntaxError: JSON.parse: bad control character in string literal at line 488 column 45 of the JSON data
```

You should make sure that what you're trying to parse is actually JSON. I notice you're also using the 5.0.0-beta, so if you suspect this might be a bug in Angular's `http` library please open an issue in https://github.com/angular/angular.
