### ISSUE TITLE
aot fails when the source directory is changed

### ISSUE THREAD

**Issue by sendilkumarn** [angular/angular-cli#7238]
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
<img width="346" alt="a" src="https://user-images.githubusercontent.com/12471122/28862355-5f013e0a-7797-11e7-84ad-58b4076bd790.png">

### Repro steps.
ng new <projectname> -sd src/main/webapp
ng build --aot

### The log given by the failure.

<img width="1128" alt="b" src="https://user-images.githubusercontent.com/12471122/28862400-886acebe-7797-11e7-894a-707a8929e33f.png">

### Desired functionality.
aot to compile successfully

### Mention any other details that might be useful.
✅  The compilation happens successfully. (can see the contents of app.module.ngfactory.ts)
Hope this is happening due to some path issue. 

On debugging, found this issue
`Field 'browser' doesn't contain a valid alias configuration`

**Comment by filipesilva** [comment]
I tried following your steps but could not repro:

```
ng new src-app -sd src/main/webapp
cd src-app
ng build --aot
```

If I had to bet this is related to https://github.com/angular/angular-cli/issues/7113 and you still have some bad dependencies or something. Try removing `node_modules` and any lock file you have.
