### ISSUE TITLE
Webpack terminal output has no colour on Windows in 1.3.0-rc.3

### ISSUE THREAD

**Issue by davewragg** [angular/angular-cli#7239]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.3.0-rc.3
node: 8.0.0
os: win32 x64
@angular/animations: 4.3.2
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/service-worker: 1.0.0-beta.16
@angular/cli: 1.3.0-rc.3
@angular/compiler-cli: 4.3.2
@angular/language-service: 4.3.2
Windows 10, git bash (MINGW32)
git version 2.13.2.windows.1
```

### Repro steps.
```
npm i -g @angular/cli@next
ng new test
cd test
ng build
```

### The log given by the failure.
No error, but terminal output has no colouring.

### Desired functionality.
Output has lovely colours on 1.2.6, how I long to see them again.

### Mention any other details that might be useful.
Probably not the most important bug you'll see, but a bit of a shame.

**Comment by filipesilva** [comment]
Does this still happen in 1.3.0 final?

**Comment by davewragg** [comment]
Hi @filipesilva, I'm afraid so.

**Comment by filipesilva** [comment]
I'm on windows and don't get this with the terminal I use (conemu/gitbash). What terminal do you use?

**Comment by davewragg** [comment]
I'm on Git Bash (via Git Extensions/Git for Windows), just running from direct from start menu. I don't have conEmu on this machine. Just went and double checked - reverting to 1.2.6 (for example) produces coloured output, but from 1.3.0 (including rcs) the output is colourless. Can supply screenshots if useful?

**Comment by filipesilva** [comment]
You see something like this, right? I just tried on gitbash without anything else and this is what I got.

![image](https://user-images.githubusercontent.com/4172079/29965385-46f6e942-8f05-11e7-91bc-e26379a82ecd.png)

**Comment by davewragg** [comment]
Yep, exactly that. On 1.2.6 the webpack output had a bit of green and white in there.

**Comment by filipesilva** [comment]
Got it, will investigate.
