### ISSUE TITLE
 Missing documentation to set up source maps for debugging

### ISSUE THREAD

**Issue by RoestVrijStaal** [angular/angular-cli#7240]
Repost since a ticket can't be moved from repo to repo. See: https://github.com/angular/angular/issues/18389

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
See https://stackoverflow.com/questions/45314808/angulars-zone-js-hates-raphaeljs 
People suggest that I should look into compiled code but that isn't possible due the incorrect / absent source maps.  
At angular.io I can't find any info how to set those up. 

## Expected behavior
Please cover in the docs how to setup & maintain source maps 

## Minimal reproduction of the problem with instructions
https://encrypted.google.com/search?hl=nl&q=how+to+set+up+source+maps+site%3Aangular.io&oq=how+to+set+up+source+maps+site%3Aangular.io

https://duckduckgo.com/?q=how+to+set+up+source+maps+site%3Aangular.io&ia=web

## What is the motivation / use case for changing the behavior?
Well, imine at StackOverflow for example. 

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [X] Pale Moon: 27.4.0 

For Tooling issues:
- Node version: v8.2.1
- Platform:  Linux

</code></pre>

**Comment by Brocco** [comment]
Source maps should be working for dev and test as of release 1.3.0.

**Comment by filipesilva** [comment]
Heya, you can control whether sourcemaps are generated via the `--sourcemap` flag. It is documented in the page for the build command: https://github.com/angular/angular-cli/wiki/build. By default they are on in turned on in dev builds, and off in prod builds (but you can turn them on there as well).
