### ISSUE TITLE
environment option in ng test documentation

### ISSUE THREAD

**Issue by MarcBanc** [angular/angular-cli#7255]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.2.6
node: 7.2.1
os: linux x64
```
### Repro steps.

[Documentation](https://github.com/angular/angular-cli/wiki/test):
![image](https://user-images.githubusercontent.com/5012042/28913708-47922eda-7839-11e7-9693-df7bbf17e1aa.png)

but ```ng test --help``` says:

```
provider@plbo:~$ ng test --help
ng test <options...>
  Run unit tests in existing project.
  aliases: t
  --watch (Boolean) Run build when files change.
    aliases: -w, --watch
  --code-coverage (Boolean) (Default: false) Coverage report will be in the coverage/ directory.
    aliases: -cc, --codeCoverage
  --config (String) Use a specific config file. Defaults to the karma config file in .angular-cli.json.
    aliases: -c <value>, --config <value>
  --single-run (Boolean) Run tests a single time.
    aliases: -sr, --singleRun
  --progress (Boolean) Log progress to the console while in progress.
    aliases: --progress
  --browsers (String) Override which browsers tests are run against.
    aliases: --browsers <value>
  --colors (Boolean) Enable or disable colors in the output (reporters and logs).
    aliases: --colors
  --log-level (String) Level of logging.
    aliases: --logLevel <value>
  --port (Number) Port where the web server will be listening.
    aliases: -port <value>
  --reporters (String) List of reporters to use.
    aliases: --reporters <value>
  --sourcemaps (Boolean) (Default: true) Output sourcemaps.
    aliases: -sm, --sourcemap, --sourcemaps
  --poll (Number) Enable and define the file watching poll time period (milliseconds).
    aliases: -poll <value>
  --app (String) Specifies app name to use.
    aliases: -a <value>, -app <value>
```

### The log given by the failure.

```The option '--e' is not registered with the test command. Run `ng test --help` for a list of supported options.```

### Desired functionality.

So after browsing code for some time, option "environment" is implemented in 1.3.x branch, but documentation do not clarify this. Please consider to do not expose functionality in documentation that is not implemented in stable branch (as for now in 1.2.x) or add something like 'version added: x.x.x' for each option.

**Comment by filipesilva** [comment]
Sorry about that, we should only publish docs for patch versions and not betas/rc. I've updated our release docs to highlight that.

Meanwhile 1.3.x is the latest patch version and this should be working.
