### ISSUE TITLE
Error upgrading angular/cli on windows

### ISSUE THREAD

**Issue by mip1983** [angular/angular-cli#7256]
### The log given by the failure.
Testing binary
Binary is fine
npm ERR! path C:\Users\q799755\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\fsevents\node_modules\dashdash\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall lstat
npm ERR! Error: EPERM: operation not permitted, lstat 'C:\Users\q799755\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, lstat 'C:\Users\q799755\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, lstat \'C:\\Users\\q799755\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'lstat',
npm ERR!   path: 'C:\\Users\\q799755\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\q799755\AppData\Roaming\npm-cache\_logs\2017-08-03T09_07_56_062Z-debug.log

### Desired functionality.

No error on install. I have full permissions on the folder in AppData\Roaming\, I beleive it's erroring because this path doesn't exist.

### Mention any other details that might be useful.
The folder it mentions in the error:

'C:\Users\q799755\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\fsevents\node_modules\dashdash\node_modules'

Does not exist. In fact 'fsevents' does not exist, I can see fs.realpath and fs-extra and fstream, but not 'fsevents' in the above @angular\cli\node_modules folder.

**Comment by JSMike** [comment]
Did you npm install previously with admin permissions? You most likely need to ensure your console has had it's privileges elevated.

This is a windows/npm issue, not an angular cli specific issue.

**Comment by mip1983** [comment]
No I didn't install previously with admin permissions. Running the console as administrator produces the same error.

**Comment by JSMike** [comment]
you may want to just purge `C:\Users\q799755\AppData\Roaming\npm\node_modules\@angular\cli` from your filesystem manually, and then try again

**Comment by filipesilva** [comment]
I think you're suffering for an annoying bug with optional dependencies (like `fsevents`) in `npm@5`: https://github.com/npm/npm/issues/17671, https://github.com/npm/npm/issues/17747.

The only solution I know of is it explicitly uninstall and then reinstall. Please follow those issues in npm directly for a resolution.

**Comment by kuncevic** [comment]
Seams to be fixed in `npm 5.4.2` https://github.com/npm/npm/issues/17671#issuecomment-329649189
