### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by Khushpinder** [angular/angular-cli#7257]
I have faced following error when i build for server

ERROR in Error encountered resolving symbol values statically. Could not resolve @angular/common/http relative to /var/www/html/ifta/trunk/front/node_modules/@angular/platform-server/platform-server.d.ts., resolving symbol ServerModule in /var/www/html/ifta/trunk/front/node_modules/@angular/platform-server/platform-server.d.ts, resolving symbol ServerModule in /var/www/html/ifta/trunk/front/node_modules/@angular/platform-server/platform-server.d.ts

ERROR in ./~/@angular/platform-server/@angular/platform-server.es5.js
Module not found: Error: Can't resolve '@angular/common/http' in '/var/www/html/ifta/trunk/front/node_modules/@angular/platform-server/@angular'
 @ ./~/@angular/platform-server/@angular/platform-server.es5.js 11:0-135
 @ ./src/app/app.server.module.ts
 @ ./src/main.server.ts
 @ multi ./src/main.server.ts

ERROR in ./~/@angular/platform-server/@angular/platform-server.es5.js
Module not found: Error: Can't resolve '@angular/platform-browser/animations' in '/var/www/html/ifta/trunk/front/node_modules/@angular/platform-server/@angular'
 @ ./~/@angular/platform-server/@angular/platform-server.es5.js 14:0-103
 @ ./src/app/app.server.module.ts
 @ ./src/main.server.ts
 @ multi ./src/main.server.ts

ERROR in ./~/@angular/platform-server/@angular/platform-server.es5.js
Module not found: Error: Can't resolve '@angular/animations/browser' in '/var/www/html/ifta/trunk/front/node_modules/@angular/platform-server/@angular'
 @ ./~/@angular/platform-server/@angular/platform-server.es5.js 9:0-63
 @ ./src/app/app.server.module.ts
 @ ./src/main.server.ts
 @ multi ./src/main.server.ts

**Comment by Brocco** [comment]
This error comes up when you are using an inline function inside of a module that is not being exported. The error is telling you that your code could not be analyzed.

The fix is to make those functions be declared and exported (not inlined).
