### ISSUE TITLE
Updating autoprefixer to v7.1.x and postcss v6.0.x

### ISSUE THREAD

**Issue by JulienBourgain** [angular/angular-cli#7271]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli@1.3.0-rc.5

### Desired functionality.

In my project, i use css-grids and the default option in autoprefixer 6 is grid: true 
In autoprefixer 7, it's grid: false

i think there is some other improvements

**Comment by clydin** [comment]
This is waiting on cssnano 4.0 to be released to have a full postcss 6 pipeline.

**Comment by mgol** [comment]
Note that Autoprefixer 7 disables CSS Grid prefixes for IE by default so unless CLI passes the option explicitly (and unless there are more breaking changes there) the update to Autoprefixer 7 will be breaking and will require a major version bump of Angular CLI.

**Comment by kylecordes** [comment]
@mgol  I wonder if would be sufficient to simply set grid: true, if that will be enough to make it possible to move up to v7, without having to simultaneously solve the problem of making autoprefixer configurable.

**Comment by kylecordes** [comment]
@mgol  I have a workaround in progress that does this and appears to work fine. Writeup coming soon.

**Comment by alan-agius4** [comment]
These dependencies have been update
