### ISSUE TITLE
Misleading error for incompatible @angular/compiler-cli version

### ISSUE THREAD

**Issue by gkalpak** [angular/angular-cli#7273]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
```

### The log given by the failure.
```
Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "5.0.0-beta.2".
```

### Desired functionality.
When an incompatible version of `@angular/compiler-cli` is detected ([here][1]), mention the upper bound in the error message. Currently, it can be confusing when you are using an `@angular/compiler-cli` version that _is_ _"2.3.1 or greater"_, but apparently too much greater.

E.g. something like:
```
The current version of `@ngtools/webpack` needs `@angular/cli` >=2.3.1 and <5. Current version is "5.0.0-beta.2".
```

[1]: https://github.com/angular/angular-cli/blob/b81fc83c12f839b09fbf210657a837c9957f2091/packages/%40ngtools/webpack/src/index.ts#L26-L27

**Comment by mgechev** [comment]
@gkalpak can we close this now or it's still reproducible?

**Comment by gkalpak** [comment]
I think so. Let's close it.
