### ISSUE TITLE
Need option to disable historyFallbackAPI in angular-cli.json

### ISSUE THREAD

**Issue by vimalraj-a** [angular/angular-cli#7274]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

1.2.0

### Repro steps.

1. ng eject
2. Open webpack.config.json
3. Change historyApiFallback as false for devServer
4. run npm start

### The log given by the failure.

NA

### Desired functionality.

Should have option in anguar-cli.json for disabling the historyFallback

### Mention any other details that might be useful.

We are working migrating multi page application from Kendo with jQuery to Angular. Our old code loading the partial page (.html) dynamically through KendoTabStrip to emit SPA functionality. 

Since angular-cli is default true for historyFallback we are end-up loop when html file not found in specified location.

**Comment by mgechev** [comment]
If you still have this feature request, feel free to explore ngx-build-plus. You can customize your Angular CLI configuration there so it suits your needs. If I'm missing something, feel free to open a new issue.
