### ISSUE TITLE
Error in --builder-optmizer flag

### ISSUE THREAD

**Issue by julianobrasil** [angular/angular-cli#7277]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.0-rc.5
node: 6.10.3
os: win32 x64
@angular/animations: 4.3.3
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.3.0-rc.5
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

### Repro steps.

ng build --prod --builder-optmizer

### The log given by the failure.

<details>
    <summary>Error log</summary>
    <pre>
ERROR in ./node_modules/rxjs/observable/BoundCallbackObservable.js Module build failed: TypeError: Cannot read property 'type' of undefined at Object.getEffectiveTypeAnnotationNode
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:9341:17) at assignContextualParameterTypes
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:41652:25) at checkFunctionExpressionOrObjectLiteralMethod 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:41948:29) at checkExpressionWorker 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:42959:28) at checkExpression 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:42898:42) at checkExpressionCached 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:42779:38) at checkReturnStatement 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45418:54) at checkSourceElement 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46763:28) at Object.forEach 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:1506:30) at checkBlock 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:44563:16) at checkSourceElement 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46742:28) at checkFunctionExpressionOrObjectLiteralMethodDeferred 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:41990:21) at checkDeferredNodes 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46828:25) at checkSourceFileWorker 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46863:17) at checkSourceFile 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46842:13) at Object.forEach 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:1506:30) @ ./node_modules/rxjs/observable/bindCallback.js 2:32-68 @ ./node_modules/rxjs/add/observable/bindCallback.js @ ./node_modules/rxjs/Rx.js @ ./src/app/model/service/dao/usuario.service.ts @ ./src/$$_gendir/app/app.module.ngfactory.ts @ ./src/main.ts @ multi ./src/main.ts ERROR in ./node_modules/rxjs/observable/BoundNodeCallbackObservable.js Module build failed: TypeError: Cannot read property 'type' of undefined at Object.getEffectiveTypeAnnotationNode 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:9341:17) at assignContextualParameterTypes 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:41652:25) at checkFunctionExpressionOrObjectLiteralMethod 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:41948:29) at checkExpressionWorker 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:42959:28) at checkExpression 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:42898:42) at checkExpressionCached 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:42779:38) at checkReturnStatement 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45418:54) at checkSourceElement 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46763:28) at Object.forEach 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:1506:30) at checkBlock 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:44563:16) at checkSourceElement 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46742:28) at checkFunctionExpressionOrObjectLiteralMethodDeferred 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:41990:21) at checkDeferredNodes 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46828:25) at checkSourceFileWorker 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46863:17) at checkSourceFile 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46842:13) at Object.forEach 
(E:\Users\Juliano\Documents\Projetos\SGI-ALFA\github\SGI-Frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:1506:30) @ ./node_modules/rxjs/observable/bindNodeCallback.js 2:36-76 @ ./node_modules/rxjs/add/observable/bindNodeCallback.js @ ./node_modules/rxjs/Rx.js @ ./src/app/model/service/dao/usuario.service.ts @ ./src/$$_gendir/app/app.module.ngfactory.ts @ ./src/main.ts @ multi ./src/main.ts
    </pre>
</details>

### Desired functionality.

Compile code with an efficient tree shaking process.

### Mention any other details that might be useful.

@filipesilva, you asked me for some code in https://github.com/angular/material2/issues/4137#issuecomment-320223215.

Well, I think I can share the project with you so you can fork and try compiling it by yourself. Is this ok for you (in fact I've already shared it with you)? There's nothing to do but `npm install` and `ng build...`

**Comment by filipesilva** [comment]
Yes I can clone the project and have a look, but I don't recall you telling me where it is. Where can I find it/

**Comment by julianobrasil** [comment]
I sent you an invite.

**Comment by filipesilva** [comment]
@julianobrasil I had a look and it seems to build with no errors. I did notice some errors but after I cleared node_modules they were gone.

Can you try doing this?
- delete `node_modules`
- manually update the cli to `1.3.0-rc.5` in `package.json`
- `npm i`
- `npm build --prod --build-optimizer`

I believe this is just a dependency problem.

**Comment by filipesilva** [comment]
This was my before/after btw:

Before:
```
> ng build --prod

Date: 2017-08-04T15:29:56.120Z
Hash: 86910afb8396d223574f
Time: 82436ms
chunk {0} 0.f0a3ecd52cdf1902e65e.chunk.js (common) 398 kB {6}  [rendered]
chunk {1} 1.deef6a692cecdbd4bc56.chunk.js () 733 kB {6}  [rendered]
chunk {2} 2.d34b9b1ec3bd2dcc57c0.chunk.js () 3.21 kB {6}  [rendered]
chunk {3} 3.d941a53402ec58324926.chunk.js () 3.22 kB {6}  [rendered]
chunk {4} 4.59844ebd4e7a255f3e39.chunk.js () 3.28 kB {6}  [rendered]
chunk {5} polyfills.bf7f2dce108ddf210799.bundle.js (polyfills) 62.6 kB {10} [initial] [rendered]
chunk {6} main.a4e233a479135679b1e9.bundle.js (main) 103 kB {9} [initial] [rendered]
chunk {7} scripts.b634e740b755f4a0eb54.bundle.js (scripts) 921 kB {10} [initial] [rendered]
chunk {8} styles.5da8eba06daeaad3503a.bundle.css (styles) 170 kB {10} [initial] [rendered]
chunk {9} vendor.e24dca0222f06912bc60.bundle.js (vendor) 1.35 MB [initial] [rendered]
chunk {10} inline.91280a085b45a11c35bd.bundle.js (inline) 1.6 kB [entry] [rendered]
```

After:
```
> ng build --prod --build-optimizer

Date: 2017-08-04T15:33:22.832Z
Hash: b6dc762f257286b1c44d
Time: 153003ms
chunk {0} 0.16e6ce188fd1e845be94.chunk.js (common) 398 kB {5}  [rendered]
chunk {1} 1.8eccd2b6b2d6eeef026a.chunk.js () 731 kB {5}  [rendered]
chunk {2} 2.6c3fb435d94ab814bb04.chunk.js () 3.21 kB {5}  [rendered]
chunk {3} 3.3be69b3ede78d36f76c0.chunk.js () 3.22 kB {5}  [rendered]
chunk {4} 4.79ed3265a511d0c3cd9a.chunk.js () 3.28 kB {5}  [rendered]
chunk {5} main.b0fe6b82aba802e98f62.bundle.js (main) 1.07 MB {9} [initial] [rendered]
chunk {6} polyfills.18b6ddbf4b936eb75b9d.bundle.js (polyfills) 62.4 kB {9} [initial] [rendered]
chunk {7} scripts.44fd357646c30e7de938.bundle.js (scripts) 921 kB {9} [initial] [rendered]
chunk {8} styles.5da8eba06daeaad3503a.bundle.css (styles) 170 kB {9} [initial] [rendered]
chunk {9} inline.2df21b68649353e1b2d9.bundle.js (inline) 1.6 kB [entry] [rendered]
```

**Comment by julianobrasil** [comment]
Ok. Then I'll close this issue, recompile it. I'll open another issue if I find runtime errors.

**Comment by julianobrasil** [comment]
Just to keep you updated. I tested all the features of my app that are ready and experienced no errors.  Great job!

**Comment by filipesilva** [comment]
Awesome :D
