### ISSUE TITLE
Update to 1.3.0-rc.5 broke my service worker (with --build-optimizer)

### ISSUE THREAD

**Issue by mrjmd** [angular/angular-cli#7280]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
![image](https://user-images.githubusercontent.com/2111857/28987456-2eef666c-7920-11e7-8451-f9729181d7bf.png)

### Repro steps.
`git clone git@github.com:contentacms/contenta_angular.git`
`cd contenta_angular`
`npm install`
`ng serve --prod --build-optimizer`
Examine the `dist/sw-register` bundle.

### The log given by the failure.
No error, just no service worker being registered any more. Inside my sw-register I see the problem, this is the entire contents:

`webpackJsonp([3],{3:function(n,o,t){n.exports=t("EUKP")},EUKP:function(n,o){navigator}},[3]);`

When normally it looks like this:

`webpackJsonp([3],{3:function(r,e,o){r.exports=o("EUKP")},EUKP:function(r,e){"serviceWorker"in navigator&&navigator.serviceWorker.register("worker-basic.min.js").catch(function(r){console.error("Error registering service worker:",r)})}},[3]);`

### Mention any other details that might be useful.
I was previously running `1.3.0-rc.0` so I'm not sure which version introduced this issue, I tested `1.3.0-rc.3` as well and my dist/sw-register file looks as expected, so my guess is this was just introduced. Note the size of the sw-register bundle here using rc.3:

![image](https://user-images.githubusercontent.com/2111857/28987861-01eb898c-7922-11e7-9007-c06366a5c879.png)

**Comment by clydin** [comment]
Does it work without the build optimizer enabled?

**Comment by mrjmd** [comment]
Ah, good question. I just checked, and yes, `ng build --prod` generates sw-register properly on 1.3.0-rc.5, so this seems to be specifically an issue with CLI 1.3.0-rc.5 when using --build-optimizer and service worker.

**Comment by mrjmd** [comment]
I can confirm this happens with a brand new app as well. New repro steps:

- `ng new cli-test`
- `cd cli-test`
- `ng set apps.0.serviceWorker=true`
- `npm install @angular/service-worker`
- `ng build --prod --build-optimizer`
- Examine `dist/sw-register` bundle

Screenshot, note the small 93 byte bundle:

![image](https://user-images.githubusercontent.com/2111857/28989211-cacd35ca-7928-11e7-9321-d3fcb6782a31.png)

File contents are:

`webpackJsonp([3],{3:function(n,o,t){n.exports=t("EUKP")},EUKP:function(n,o){navigator}},[3]);`

Version info:

![image](https://user-images.githubusercontent.com/2111857/28989241-ec02c6d8-7928-11e7-8edd-afa5532443e2.png)

**Comment by filipesilva** [comment]
https://github.com/angular/devkit/pull/77 and a CLI release including it should fix this.
