### ISSUE TITLE
tests hang with --single-run but are fine with just ng test

### ISSUE THREAD

**Issue by georgeedwards** [angular/angular-cli#7281]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.2.7
node: 6.10.3
os: win32 x64
@angular/animations: 4.3.3
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.2.7
@angular/compiler-cli: 4.3.3
```
Chrome: 60.0.3112.90

### Repro steps.
I am struggling to isolate this issue, if I create a clean cli project, it runs fine. However, I have tried copying over the **karma.conf** and **angular-cli** files and that makes no difference, aside from that, I can't see what the difference would be?

### The log given by the failure.
Very reliably the `ng test` command will work, but adding the `--single-run` flag causes chrome to have an issue opening. These tests ran fine before I upgraded my project dependencies - I was previously on 4.1. 
```
C:\Users\George\Source\Repos\myProj>ng test --single-run
 10% building modules 2/2 modules 0 active04 08 2017 23:22:58.078:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
04 08 2017 23:22:58.085:INFO [launcher]: Launching browser Chrome with unlimited concurrency
04 08 2017 23:22:58.095:INFO [launcher]: Starting browser Chrome
 94% asset optimization04 08 2017 23:24:11.543:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
04 08 2017 23:24:13.663:INFO [launcher]: Trying to start Chrome again (1/2).
04 08 2017 23:24:17.923:INFO [Chrome 60.0.3112 (Windows 10 0.0.0)]: Connected on socket tNw7OJK58Y3Dz3nBAAAA with id 84048778
04 08 2017 23:24:27.934:WARN [Chrome 60.0.3112 (Windows 10 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
Chrome 60.0.3112 (Windows 10 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.
Chrome 60.0.3112 (Windows 10 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.

Chrome 60.0.3112 (Windows 10 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.


C:\Users\George\Source\Repos\myProj>ng test
 10% building modules 2/2 modules 0 active04 08 2017 23:25:18.994:WARN [karma]: No captured browser, open http://localhost:9876/
04 08 2017 23:25:19.021:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
04 08 2017 23:25:19.023:INFO [launcher]: Launching browser Chrome with unlimited concurrency
04 08 2017 23:25:19.058:INFO [launcher]: Starting browser Chrome
 94% asset optimization04 08 2017 23:26:33.160:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
04 08 2017 23:26:34.280:WARN [karma]: No captured browser, open http://localhost:9876/
04 08 2017 23:26:34.481:INFO [launcher]: Trying to start Chrome again (1/2).
04 08 2017 23:26:40.057:INFO [Chrome 60.0.3112 (Windows 10 0.0.0)]: Connected on socket 1ZJHTIhi1AMeRaMZAAAA with id 38870052
Chrome 60.0.3112 (Windows 10 0.0.0): Executed 86 of 86 SUCCESS (0 secs / 0 secs)
```

### Desired functionality.
The sing-run flag to have no impact on the tests running

### Mention any other details that might be useful.

I am quite puzzled by this, I will keep debugging, but thought I'd open this to see if anyone else had come across it, and even if it is something in my project, the flag shouldn't (in my view) make any difference to it.

**Comment by Meligy** [comment]
If this is a specific project issue, I suggest you try a couple of things too:

- Compare the `devDependencies` part of your `package.json` against that of a new project
- Clear the `node_modules` folder, and then run `npm cache clear` and then `npm install`

**Comment by georgeedwards** [comment]
@Meligy I have tried both steps and still have the same result. For reference, here are my [dev dependencies](https://gist.github.com/georgeedwards/79f8cc0031e319c6accce2ef9ad80f61).

**Comment by HerrEmil** [comment]
@georgeedwards I had the same issue today when upgrading dependencies on a large angular-cli project. A workaround that works for me is to set the karma configuration option `browserNoActivityTimeout` to a larger value than the default. Also, setting the `captureTimeout` option to a larger value will prevent the browser from restarting while your project is building.

**Comment by georgeedwards** [comment]
OK that seems to work as a work around. It does seem to be a resource issue.

**Comment by ChenReuven** [comment]
i have also the same issue.
angular cli 1.3.1 + chrome headless and simallar configuration as above...
- the workaround work but it seem awkward...

**Comment by johncrim** [comment]
I have experienced the same issue on one build server consistently, and it consistently does not repro on the other build server.

Interesting that:

```
 ng test --browsers ChromeHeadless --single-run
```

yields the error:
```
 10% building modules 1/1 modules 0 active03 10 2017 17:44:07.968:INFO [karma]: Karma v1.7.1 server started at http://0.
0.0.0:9876/
03 10 2017 17:44:07.974:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
03 10 2017 17:44:07.983:INFO [launcher]: Starting browser ChromeHeadless
03 10 2017 17:44:39.227:INFO [HeadlessChrome 0.0.0 (Windows 8.1 0.0.0)]: Connected on socket 5K0iyWabjmQWgD9IAAAA with i
d 21670881
03 10 2017 17:44:49.233:WARN [HeadlessChrome 0.0.0 (Windows 8.1 0.0.0)]: Disconnected (1 times), because no message in 1
0000 ms.
HeadlessChrome 0.0.0 (Windows 8.1 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.
HeadlessChrome 0.0.0 (Windows 8.1 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.
HeadlessChrome 0.0.0 (Windows 8.1 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.
```

but running:

```
 ng test --browsers ChromeHeadless
```

successfully runs all the tests. If the issue were just a matter of timeouts vs server speed, and not a bug, I would think the `--single-run` argument wouldn't trigger this issue 100% of the time.

**Comment by NVK15** [comment]
I have similar issue. When i run the tests in VSTS, i get the following error:

Here is the log: 

```
> ng test --cc
Your global Angular CLI version (1.4.9) is greater than your local
version (1.4.7). The local Angular CLI version is used.
To disable this warning use "ng set --global warnings.versionMismatch=false".
[32m26 10 2017 04:28:02.079:INFO [karma]: [39mKarma v1.7.1 server started at http://0.0.0.0:9876/
[32m26 10 2017 04:28:02.081:INFO [launcher]: [39mLaunching browser ChromeHeadlessNoSandbox with unlimited concurrency
[32m26 10 2017 04:28:02.089:INFO [launcher]: [39mStarting browser ChromeHeadless
  
[33m26 10 2017 04:29:02.092:WARN [launcher]: [39mChromeHeadless have not captured in 60000 ms, killing.
[33m26 10 2017 04:29:04.095:WARN [launcher]: [39mChromeHeadless was not killed in 2000 ms, sending SIGKILL.
[33m26 10 2017 04:29:06.095:WARN [launcher]: [39mChromeHeadless was not killed by SIGKILL in 2000 ms, continuing.
 10% building modules 2/4 modules 2 active ...owup\Source\App\src /\.spec\.ts$/ 10% building modules 3/4 modules 1 active ...lowup\Source\App\src\polyfills.ts                                          10% building modules 4/4 modules 0 active 10% building modules 4/5 modules 1 active ...PFU.App\src\app\app.component.spec.ts                                          10% building modules 5/5 modules 0 active 10% building modules 5/6 modules 1 active ...s\findings\.component.spec.ts         ...
Process completed with exit code 1.
```


I tried: 
 ng test --browsers ChromeHeadless
browserNoActivityTimeout 
 and other alternatives mentioned in this thread. Nothing worked.

Any help would be appreciated.

Thanks in advance.

**Comment by PatCantSeeSharp** [comment]
Same issue for me. Everything works fine in development env (tool about 3s total), but on the Build Server, which is triggered by VSTS, ChromeHeadless takes forever. Just tried it out with an ridiculous timeout, but it seems to be stuck forever.

`hashing 89% module assets processing  90% chunk assets processing 91% additional chunk assets processing                          92% recording 91% additional asset processing    92% chunk asset optimization       94% asset optimization           95% emitting             [33m22 11 2017 10:40:19.020:WARN [watcher]: [39mPattern "C:/vstsagent/_work/8/s/angular-web/dist/packages/**/core/theming/prebuilt/indigo-pink.css" does not match any file.
2017-11-22T09:54:50.5515917Z [33m22 11 2017 10:54:50.551:WARN [launcher]: [39mChromeHeadless have not captured in 900000 ms, killing.
2017-11-22T09:54:52.5596553Z [33m22 11 2017 10:54:52.559:WARN [launcher]: [39mChromeHeadless was not killed in 2000 ms, sending SIGKILL.
2017-11-22T09:54:54.5624687Z [33m22 11 2017 10:54:54.562:WARN [launcher]: [39mChromeHeadless was not killed by SIGKILL in 2000 ms, continuing.`

Also tried it with `ng test --sourcemap=false --cc` but it makes no difference at all. Interesting at all is, that with PhantomJS the command succeed, but the latest tests fail because PhantomJS is simply outdated.

**Comment by ManuelSch** [comment]
I'm still experiencing this issue. Any solutions?

**Comment by chadbr** [comment]
@ManuelSch from https://github.com/jasmine/jasmine/issues/1413
```
Add this to your Karma.conf:

captureTimeout: 210000,
browserDisconnectTolerance: 3, 
browserDisconnectTimeout : 210000,
browserNoActivityTimeout : 210000,

```

worked for me...

**Comment by vijayakumar-psg587** [comment]
It might not be the case with others, but I had a similar issue, It resulted because of a repeated httpMock call in my test case, that made the httpMock call indefintely  and the browser was never able to capture my test case.  Apologies if this doesn't resolve the issue, but can we try to incrementally make the test spec complex and see where the breakage appears . Again sincerely apologize if that doesn't seem to be the case.
