### ISSUE TITLE
The "Include Angular Material" story is outdated

### ISSUE THREAD

**Issue by eitland** [angular/angular-cli#7286]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.3
node: 8.1.3
os: win32 x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.2.3
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

### Repro steps.

Create a new project and cd into it

Then follow this guide https://github.com/angular/angular-cli/wiki/stories-include-angular-material

### The log given by the failure.
`
ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/bidi/index.d.ts (8,99): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/portal/portal.d.ts (8,85): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/portal/portal-directives.d.ts (8,76): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/portal/dom-portal-host.d.ts (8,31): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/platform/platform.d.ts (8,26): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/platform/features.d.ts (8,40): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/platform/index.d.ts (8,32): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/a11y/live-announcer.d.ts (8,139): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/a11y/focus-trap.d.ts (8,95): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/a11y/interactivity-checker.d.ts (8,38): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/a11y/fake-mousedown.d.ts (8,49): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/a11y/index.d.ts (8,28): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/keyboard/keycodes.d.ts (8,140): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/core.d.ts (1,99): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/core/a11y/list-key-manager.d.ts (8,44): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/sort/sort-header.d.ts (11,30): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/table/cell.d.ts (9,54): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/table/table.d.ts (1,26): Cannot find module '@angular/cdk'.

ERROR in C:/Users/someone/somewhere/scratch/node_modules/@angular/material/ty
pings/table/row.d.ts (1,38): Cannot find module '@angular/cdk'.

ERROR in Error encountered resolving symbol values statically. Could not resolve @angular/c
dk relative to C:/Users/someone/somewhere/scratch/node_modules/@angular/mater
ial/typings/index.d.ts., resolving symbol MaterialModule in C:/Users/someone/somewhere/scratch/scratch/node_modules/@angular/material/typings/index.d.ts, resolving symbol Mater
ialModule in C:/Users/someone/somewhere/scratch/node_modules/@angular/materia
l/typings/index.d.ts

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/cdk' in 'C:\Users\someone\somewhere\Projects\A
vdeling\scratch\node_modules\@angular\material\@angular'`
 @ ./~/@angular/material/@angular/material.es5.js 10:0-932
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
`
### Desired functionality.

I just wanted it to work with Material

### Mention any other details that might be useful.

This is documented at https://github.com/angular/material2/blob/master/guides/getting-started.md (Updated 2 days ago, however that document has its own issues wrt the parts about hammer.js).

It is also documented on https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/include-angular-material.md

**Comment by hansl** [comment]
@eitland Please follow the directions at https://material.angular.io/guide/getting-started
