### ISSUE TITLE
provide a simplified production param

### ISSUE THREAD

**Issue by zh99998** [angular/angular-cli#7288]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
currently I have to specific
`ng build --env=prod --aot --build-optimizer --prod`
to build a full-optimization production code.

could it be a simple option to enable all of it (currently and future added)?

**Comment by deebloo** [comment]
all you need to run to get a production build is.
```
ng build --prod --build-optimizer
```
--env=prod is the default environment when running --prod
--aot is enabled by default when running --prod

the only additional flag you need (for now) is --build-optimizer

**Comment by zh99998** [comment]
thanks.
