### ISSUE TITLE
'npm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by RodolpheGohard** [angular/angular-cli#7289]
### Versions.

```
user /d/workspace/project (master)
$ npm --version
3.8.5

user  /d/workspace/project  (master)
$ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.7
node: 6.10.3
os: win32 ia32

user  /d/workspace/project  (master)
$ node --version
v6.10.3
```
Windows 7

### Repro steps.
* run `$ ng new project`

### The log given by the failure.
```
$ ng new project
installing ng
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Installing packages for tooling via npm.
'npm' is not recognized as an internal or external command,
operable program or batch file.

Package install failed, see above.
Package install failed, see above.
```

**Comment by RodolpheGohard** [comment]
workaround: I got around by just running `npm install` manually in the destination folder.

**Comment by Brocco** [comment]
This seems odd... have you been able to reproduce this issue?

**Comment by RodolpheGohard** [comment]
On my setup, I created another project and got the same result.
On a my colleagues computer it doesn't happen, though their config is similar.

The thing is Npm is in my path and works, but maybe ng cli is trying to find its path to NPM through some other way than the actual PATH ?

**Comment by Jeffarese** [comment]
Can you try again having npm installed through NVM?

**Comment by Eclogesh** [comment]
Having the same issue.. Running the node from zip file.

**Comment by Eclogesh** [comment]
<img width="354" alt="capture" src="https://user-images.githubusercontent.com/6228603/43658324-914f97b2-9726-11e8-91cb-90cf2b3b6a63.PNG">

<img width="348" alt="capture" src="https://user-images.githubusercontent.com/6228603/43658377-b7956348-9726-11e8-955c-5dd886048fef.PNG">

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
