### ISSUE TITLE
should scripts be compile into scripts.bundle.js instead of using script-loader?

### ISSUE THREAD

**Issue by zh99998** [angular/angular-cli#7290]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

currently global scripts are loaded by script-loader. which can't be optimize or minify, and can break some library rely on global context

library1.js
```javascript
'use strict'
var library1 = function(){...}
```
another script rely on library1
```javascript
library1(...)
```

they works well in traditional non-webpack environment, but currently they can't work because eval() is not allowed to add variable to context in strict mode.

since angular-cli is not allowed to modify webpack.config.js to use custom loaders.
is there any way to work-around let such a library script work now?

**Comment by clydin** [comment]
It's something that is being looked at currently.  The removal of eval has numerous benefits; CSP being an important one.
