### ISSUE TITLE
ng test --code-coverage do not generate coverage dicretory

### ISSUE THREAD

**Issue by hucheng91** [angular/angular-cli#7291]
### Versions.
  Windows (7)，
ng version： 1.2.6
angular: 4.0.0

### karma.conf.js
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};

### the console is :

Chrome 60.0.3112 (Windows 7 0.0.0): Executed 0 of 1 SUCCESS (0 secs / 0 secs)

**Comment by jdhines** [comment]
Not enough info to tell, but make sure your code editor isn't hiding things files and directories that aren't under version control (happened to me just today). You can do an `ls -la` (or just `la`) in the terminal to make sure the coverage folder isn't actually there.

**Comment by BurningDog** [comment]
From `ng test --help`:

`--code-coverage (Boolean) (Default: false) Coverage report will be in the coverage/ directory.`

I run `ng test --code-coverage=true`

**Comment by filipesilva** [comment]
After running `ng test --code-coverage` you will have a `./coverage` folder at your project root. You can then open `./coverage/index.html` to see the coverage report.

**Comment by at-hoangnguyen2** [comment]
Thanks for all !!

**Comment by liliom55** [comment]
@filipesilva
I have the same issue on angular cli (`ng test --code-coverage` does not create coverage folder) 
even I run `ng test --single-run --code-coverage --reporters=teamcity,coverage-istanbul`
```
@angular/cli: 1.4.4
node: 6.11.2
os: win32 x64
```
"devDependencies": {
    "@angular/cli": "^1.4.3",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "^1.4.1",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.3",
    "karma-jasmine": "^1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-teamcity-reporter": "^1.0.1",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }

**Comment by rijine** [comment]
same problem

**Comment by bhawin-boom** [comment]
My code coverage files not showing html files . any idea ?

**Comment by demisx** [comment]
Same issue here. Running `ng test --code-coverage` just says that some coverage for branches does not meet global threshold (85%), but there is no `coverage/` folder being generated and there is no report to view.

**Comment by demisx** [comment]
Duh. The reason the `coverage/` was missing for me was because of `reports: ["text"]` setting in `karma.conf.js`. Adding `"html"` element to this array made the `coverage/` folder to be generated.
