### ISSUE TITLE
deployUrl (ng build) doesn't seem to add a trailing slash

### ISSUE THREAD

**Issue by ameyer-pivotal** [angular/angular-cli#7295]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.7
node: 7.10.0
os: darwin x64
@angular/animations: 4.3.3
@angular/cli: 1.2.7
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

### Repro steps.

`$ ng build --deployUrl=some/path`

### The log given by the failure.

Some resources (like font awesome loaded via npm) do not load because they're missing a slash in the middle.
e.g.: `GET 404: http://localhost:8080/some/pathfontawesome-webfont.af7ae505a9eed503f8b8.woff2`

### Desired functionality.

Add a trailing slash to the deployUrl (if needed) when forming the path.
e.g.: `http://localhost:8080/some/path/fontawesome-webfont.af7ae505a9eed503f8b8.woff2`

**Comment by tomastrajan** [comment]
I tired to reproduce it and it seems to be the case that it only breaks when styles are not extracted using `--extract-css` flag. So you could use that flag for a workaround. 

It should still work for styles delivered as `.js` bundle so definitely a bug.

**Comment by ameyer-pivotal** [comment]
@tomastrajan Thanks for looking into it!
