### ISSUE TITLE
Safari Console return errors: Unexpected token '<' ,  and Can't find variable: webpack_Jsonp

### ISSUE THREAD

**Issue by vivian7169** [angular/angular-cli#7297]
### Bug Report 
```
- run 'ng build --prod --aot=false'
- then run it on a server, when loading source, safari show console errors in 
   inline.xxx.bundle.js, 
   polyfills.xxx.bundle.js, 
   scripts.xxx.bundle.js, 
   vendor.xxx.js, 
   main.xxxx.js, unable to load page successfully:

Errors: 
  1.  Unexpected token '<'
  2. Can't find variable: web pack_jsonp

However, Chrome works fine.
```

### Versions.

@angular/cli: 1.2.0
node: 6.11.2
nom: 4.2.0
os: linux x64

**Comment by be4code** [comment]
Which Safari version you are using?

**Comment by vivian7169** [comment]
Safari Version 11.0 (13604.1.34)

This is a version of Developer preview.

**Comment by mgechev** [comment]
Are you still able to reproduce the issue?

**Comment by mgechev** [comment]
Closing the issue due to inactivity. If the problem still exists in the latest version of the CLI, please open a new issue following the template and providing a minimal demo where we can reproduce it. Thanks! :-)
