### ISSUE TITLE
trying to use rxjs - getting vendor/rxjs/index.js 404 (Not Found) in browser

### ISSUE THREAD

**Issue by alvipeo** [angular/angular-cli#730]
Added to my prj jquery, bootstrap 4, other things and got it working (except for tests - a separate issue). Now, trying to add some state which uses rxjs (Observables, etc) and now getting in a browser (in Chrome, when 'ng serve'):

>>zone.js:101 GET http://localhost:4200/vendor/rxjs/index.js 404 (Not Found)

**Why is it looking for rxjs/index.js ???**

Here's now I added it - folder structure first:
- app
  - shared
    -models  **added**
      - news.model.ts - simple class for model
      - index.ts - (export * from "./news.model";)
- state **added**
      - appState.ts - contains actual code that uses rxjs
      - index.ts - (export * from "./appState";)

and then I just use it in my main component - with import from ... and DI.

Example code for appState.ts:
```
import { Observable, BehaviorSubject } from "rxjs";
import { NewsItem } from "../models";

export interface AppState {
    news: NewsItem[];
}

export class AddNewsAction {
    constructor(public newItem: NewsItem) { }
}

export type Action = AddNewsAction;

export function stateFn(initState: AppState, actions: Observable<Action>): Observable<AppState> {
    const combine = s => ({ news: s[0] });
    const appStateObs: Observable<AppState> = allState(initState.news, actions)
        .map(combine);

    return wrapIntoBehavior(initState, appStateObs);
}

...

```

**Comment by alvipeo** [comment]
Can't really format lists on github, so for clarity - the folder structure:
;; app
;; ;; shared
;; ;; ;; models
;; ;; ;; state

**Comment by alvipeo** [comment]
[The project zip](http://inus.azureedge.net/pub/NewsNotifier.zip?sv=2014-02-14&ss=2016-05-11T21%3A55%3A11Z&se=2016-05-18T21%3A55%3A06Z&sp=r&sr=b&sig=I11kyXECIr0XbY3%2FdXE%2BAucDm7jDjialfoM7wZMEfaY%3D).

Feel free to download.

Should I
```
import { Observable } from "rxjs/Observable";
```
and so on? I tried that but 1) it gets too verbose and 2) this
```
import { map } from "rxjs/operator/map";
```
does not help because I still get the error - map is not a func.

Finally, I tried to import from 'rxjs/Rx' but still getting error for **map**.

**Comment by BenevidesLecontes** [comment]
I'm using rxjs and it's working fine for me. 
In my main component: import 'rxjs/Rx'; 
In my service import {Observable} from 'rxjs/Observable';

**Comment by alvipeo** [comment]
I think I found it... will post update later.

**Comment by alvipeo** [comment]
ok, while setting up injection I misused useValue instead of useFactory. My bad.
