### ISSUE TITLE
Can't create additional environment. Environment "local" does not exist.

### ISSUE THREAD

**Issue by intergleam** [angular/angular-cli#7300]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.7
node: 6.4.0
os: win32 x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.2.7
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

### Repro steps.
create a test app with `ng new PROJECT-NAME`
create a file `environment.local.ts`
run `ng serve -e=local`

### The log given by the failure.
Environment "local" does not exist.

**Comment by be4code** [comment]
You need to provide environment in .angular-cli.json as it is mentioned in wiki: https://github.com/angular/angular-cli/wiki/stories-application-environments

**Comment by intergleam** [comment]
thanks

**Comment by michaeljota** [comment]
Have something change? I can't request for another environment that isn't `dev` or `prod`. Anything I add results in a `not exist`.

A image says more than a thousand words, so: 

![env eq pre](https://user-images.githubusercontent.com/10507776/39095676-4a368882-4612-11e8-880a-1cd306cb5b93.png)

**Comment by pckrishnadas88** [comment]
Why cli can't pick it, since the file naming convention is the same?

**Comment by michaeljota** [comment]
For anyone here, seems like this has actually change for `Angular@6`. See: [Application Environments](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/application-environments.md)
