### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Calling function 'SocialLoginModule' 

### ISSUE THREAD

**Issue by sachinghalmegit** [angular/angular-cli#7302]
after "ng serve" i'm getting below error,

![image](https://user-images.githubusercontent.com/26225407/29074497-2de3617e-7c6d-11e7-9480-b9a9e0ebf753.png)
after saving any file from work space, it compiles all project files and this time it works well.
I'm not getting why this happens. Could you please someone help me to get out of this. Please find below image for the same.

![image](https://user-images.githubusercontent.com/26225407/29074518-3d41a6da-7c6d-11e7-882c-f57721e4d925.png)

**Comment by deebloo** [comment]
@sachinghalmegit can you please fill out the issue template and post your module code? This error happens when your modules are not statically analyzable. (your module definition can't contain function calls etc)

**Comment by sachinghalmegit** [comment]
Please find below app.module.ts file

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { SocialLoginModule, AuthServiceConfig,GoogleLoginProvider, FacebookLoginProvider  } from "angular4-social-login";
import { StarRatingModule } from 'angular-star-rating';

import { AppComponent } from './app.component';
import { LandingPageComponent } from './landing-page/landing-page.component';
import { AppHeaderComponent } from './app-header/app-header.component';

 
let config = new AuthServiceConfig([
  {
    id: GoogleLoginProvider.PROVIDER_ID,
    provider: new GoogleLoginProvider("<Google-OAuth-Client-Id>")
  },
  {
    id: FacebookLoginProvider.PROVIDER_ID,
    provider: new FacebookLoginProvider("<Facebook-App-Id>")
  }
]);
export function provideConfig() {
  return config;
}

@NgModule({
  declarations: [
    AppComponent,
    LandingPageComponent,
    AppHeaderComponent  
  ], 
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule, 
    StarRatingModule.forRoot(),
    RouterModule.forRoot([
      { path: 'landing', component: LandingPageComponent },
      { path: '' , redirectTo:'landing',pathMatch:'full' }
    ]),
   SocialLoginModule.initialize(config)
  ], 
  
  providers: [{  provide: AuthServiceConfig,
      useFactory: provideConfig
    }],
  bootstrap: [AppComponent ]
})
export class AppModule { }

**Comment by Brocco** [comment]
As @deebloo mentioned above your code needs to be statically analyzable. So at first glance it looks like you will need to export the value of `config`.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
