### ISSUE TITLE
Scripts array does not keep the order, V 1.1

### ISSUE THREAD

**Issue by umarkashmiri** [angular/angular-cli#7306]
### Versions.

@angular/cli: 1.1.0
node: 7.7.2
os: win32 x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

### Repro steps.
I am using the latest version of mdbootstrap and I have to keep the same order for the following files.

"scripts": [
        "../node_modules/mdbootstrap/js/jquery-3.1.1.min.js",
        "../node_modules/mdbootstrap/js/popper.min.js",
        "../node_modules/mdbootstrap/js/bootstrap.min.js",
        "../node_modules/mdbootstrap/js/mdb.min.js"
      ]

After building and serve I see the following error, upon digging more into scripts.bundle.js file I got to know that sequence is changed.

![image](https://user-images.githubusercontent.com/1515507/29091806-abc2d626-7cb6-11e7-996c-fb8b0101acf5.png)

Sequence After bundling
        "../node_modules/mdbootstrap/js/bootstrap.min.js",
        "../node_modules/mdbootstrap/js/jquery-3.1.1.min.js",
        "../node_modules/mdbootstrap/js/mdb.min.js"
        "../node_modules/mdbootstrap/js/popper.min.js",

It seems like CLI is ordering it by file name? i am not sure.

**Comment by filipesilva** [comment]
The declaration order you see inside `scripts.bundle.js` does not reflect the order the scripts are loaded in. 

You can verify the order is being respected by adding `console.log('SCRIPT_NAME_HERE');` at the start of each of those script files and see the order in which they appear.

I did that with your example and this is what I see:
![image](https://user-images.githubusercontent.com/4172079/29519723-5080c8a8-8676-11e7-8f16-a7c89b7f0001.png)

So the order you specify is respected. Something's breaking down in what those scripts try to run, but it's not that we load them in another order. You should reach out to the maintainer of that project.
