### ISSUE TITLE
plugins/karma.d.ts is not a module

### ISSUE THREAD

**Issue by Ionaru** [angular/angular-cli#7308]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.2.7
node: 6.11.2
os: linux x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.2.7
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3
```

### Repro steps.

Create new Angular CLI app and convert karma.conf.js to karma.conf.ts
Try to import `@angular/cli/plugins/karma` with
```ts
import karmaAngularCli = require('@angular/cli/plugins/karma');
```

### The log given by the failure.

`...node_modules/@angular/cli/plugins/karma.d.ts is not a module`

### Desired functionality.

I'd like to import the Karma plugin this way in my karma.conf.ts because IntelliJ does not understand the use of `require` in the plugins array.
```ts
plugins: [
    ...
    // It wants to import 'require' from another file (./src/test).
    require('@angular/cli/plugins/karma'),
],
```

### Mention any other details that might be useful.

The file `..node_modules/@angular/cli/plugins/karma.d.ts` is completely empty, this might be why Typescript does not understand it.

**Comment by Ionaru** [comment]
Yes, with the following karma.conf.ts:
```ts
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

import * as karmaJasmine from 'karma-jasmine';
import * as karmaChrome from 'karma-chrome-launcher';
import * as karmaJasmineReporter from 'karma-jasmine-html-reporter';
import * as karmaIslanbunReporter from 'karma-coverage-istanbul-reporter';
import * as angularKarma from '@angular-devkit/build-angular/plugins/karma';
import * as path from 'path';

module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      karmaJasmine,
      karmaChrome,
      karmaJasmineReporter,
      karmaIslanbunReporter,
      angularKarma,
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: path.join(__dirname, '../coverage'),
      reports: ['html', 'lcovonly', 'text-summary'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```

I still get the message:
```
TS2306: File 'C:/Users/Jeroen/Projects/karma/node_modules/@angular-devkit/build-angular/plugins/karma.d.ts' is not a module.
```

Also on a related note, after changing `karma.conf.js` to `karma.conf.ts` in `angular.json`, running `ng run test` throws the following error
```
Cannot determine project or target for Architect command.
Error: Cannot determine project or target for Architect command.
    at RunCommand.initialize (C:\Users\Jeroen\Projects\karma\node_modules\@angular\cli\models\architect-command.js:68:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by egranato** [comment]
I am having the same issue with an app upgraded from angular 5 to 7 recently.
`module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../coverage/M365-FEAPP'),
      reports: ['html', 'lcovonly', 'text-summary'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    restartOnFileChange: true
  });
};`

My linter tells me that karma.d.ts is not a module and when I run ng serve or ng test i get the same error as above.

The curious bit is if I generate a new angular 7 app and match all the versions, everything looks identical as far as i can tell, it works but not in the upgraded app.....

`"dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@fortawesome/fontawesome-free": "^5.7.2",
    "@fortawesome/fontawesome-pro": "^5.7.2",
    "applicationinsights-js": "^1.0.20",
    "bootstrap": "4.1.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.6",
    "interactjs": "^1.3.4",
    "jquery": "^3.3.1",
    "ngx-bootstrap": "^3.2.0",
    "ngx-toastr": "^9.1.2",
    "popper.js": "^1.14.4",
    "rxjs": "^6.3.3",
    "tether": "^1.4.4",
    "tslib": "^1.9.0",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.5",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/applicationinsights-js": "^1.0.6",
    "@types/jasmine": "^2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.0.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.1",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.4"
  }`

**Comment by rigoleto** [comment]
If anyone else runs into this, what fixed it for me was to change

```
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
```
to
```
    plugins: [
      'karma-jasmine',
      'karma-chrome-launcher',
      'karma-jasmine-html-reporter',
      'karma-coverage-istanbul-reporter',
      '@angular-devkit/build-angular/plugins/karma',
    ],
```
in karma.conf.js
