### ISSUE TITLE
ng serve not working

### ISSUE THREAD

**Issue by dangviettuan** [angular/angular-cli#7324]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.1.2
node: 7.10.1
os: linux x64
@angular/animations: 4.2.3
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/core: 4.2.3
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/router: 4.2.3
@angular/cli: 1.1.2
@angular/compiler-cli: 4.2.3

### Repro steps.
1. ng serve
2. edit some files
3. save files
4. directory /src/app/home change detected & rebuild
    directory /src/app/home/setting change not detected

### The log given by the failure.
No specific error message.

**Comment by Brocco** [comment]
There is not a lot of information here to determine what is going on. Please open a new issue with more information.

Steps to reproduced, including what files are present or better yet a repo that is currently not working.

Also, updating your version of the CLI should help you out.
