### ISSUE TITLE
deploy to tomcat 8 after ng bulid -prod, css and js file has 404,and assets folder can not be acessd

### ISSUE THREAD

**Issue by Chris-DF** [angular/angular-cli#7325]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

 **Versions.**
@angular/cli: 1.2.7
node: 6.11.1
os: win32 x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/compiler-cli: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/platform-server: 4.3.3
@angular/router: 4.3.3
@angular/tsc-wrapped: 4.3.3
@angular/upgrade: 4.3.3
@angular/cli: 1.2.7

 **steps.**

when I ran npm install,and npm start, it's fine.
then I  change the httpGet url from absolute path to relative, which 
is pointing to a json file for getting.
then used VSCode to debug it ,it's also fine.

command run: ng build -prod -bh /my_app -d /my_app
then, put the dist and assets into folder webapps of ApacheTomcat  (apache-tomcat-8.5.16)
startup tomcat, enter http://localhost:8080/my_app ,
program was started up but some errors came out. 
and it did not get the json data from file. (the data could be get when I used VSCode & lite server)
httpGet can not find assets folder by the relative path now?

**The log given by the failure.**
Failed to load resource: the server responded with a status of 404 ()
16:36:21.988 shim.min.js Failed to load resource: the server responded with a status of 404 ()
16:36:22.015 app.css Failed to load resource: the server responded with a status of 404 ()
16:36:22.015 zone.js Failed to load resource: the server responded with a status of 404 ()
16:36:22.015 systemjs.config.js Failed to load resource: the server responded with a status of 404 ()
16:36:22.016 system.src.js Failed to load resource: the server responded with a status of 404 ()
16:36:22.032 systemjs.config.js Failed to load resource: the server responded with a status of 404 ()
16:36:22.033 :1 Uncaught ReferenceError: System is not defined
    at :1

**Need Help for.**
I have two questions ,one is the failure log, the other is about the assets folder's relative url path in Tomcat.
I have already googled these for two days,but still can not solve it.
anyone can help please

**I uploaded my project here:**
https://github.com/Chris-DF/Test003_Angular

**Comment by mattscu** [comment]
have you change the base href in index.html from

```html
  <base href="/">
```

to 

```html
  <base href=".">
```
?

**Comment by Chris-DF** [comment]
Thanks matthiasscudlik.
but after changed base href to "."
I still got some 404 failure.
```

styles.css Failed to load resource: the server responded with a status of 404 ()
16:54:09.903 zone.js Failed to load resource: the server responded with a status of 404 ()
16:54:09.906 shim.min.js Failed to load resource: the server responded with a status of 404 ()
16:54:09.909 system.src.js Failed to load resource: the server responded with a status of 404 ()
16:54:09.914 systemjs.config.js Failed to load resource: the server responded with a status of 404 ()
16:54:09.928 inline.78b7dd393f28760c69b2.bundle.js Failed to load resource: the server responded with a status of 404 ()
16:54:09.931 polyfills.0963b44a58b5526cfab7.bundle.js Failed to load resource: the server responded with a status of 404 ()
16:54:09.935 app.css Failed to load resource: the server responded with a status of 404 ()
16:54:09.935 styles.0e6d4836058906a81be7.bundle.css Failed to load resource: the server responded with a status of 404 ()
16:54:09.936 vendor.405a5d119d673d6062f2.bundle.js Failed to load resource: the server responded with a status of 404 ()
16:54:09.946 main.130dfd9b3e65c2c48c14.bundle.js Failed to load resource: the server responded with a status of 404 ()
16:54:09.947 zone.js Failed to load resource: the server responded with a status of 404 ()
16:54:09.970 system.src.js Failed to load resource: the server responded with a status of 404 ()
16:54:09.976 systemjs.config.js Failed to load resource: the server responded with a status of 404 ()
16:54:09.977 localhost/:1 Uncaught ReferenceError: System is not defined
    at localhost/:1
16:54:09.984 styles.0e6d4836058906a81be7.bundle.css Failed to load resource: the server responded with a status of 404 ()
16:54:09.984 inline.78b7dd393f28760c69b2.bundle.js Failed to load resource: the server responded with a status of 404 ()
16:54:09.992 polyfills.0963b44a58b5526cfab7.bundle.js Failed to load resource: the server responded with a status of 404 ()
16:54:10.000 vendor.405a5d119d673d6062f2.bundle.js Failed to load resource: the server responded with a status of 404 ()
16:54:10.007 main.130dfd9b3e65c2c48c14.bundle.js Failed to load resource: the server responded with a status of 404 ()
16:54:17.090 app.css Failed to load resource: the server responded with a status of 404 ()
16:54:17.091 styles.css Failed to load resource: the server responded with a status of 404 ()
16:54:17.120 styles.0e6d4836058906a81be7.bundle.css Failed to load resource: the server responded with a status of 404 ()
```

so confused.

**Comment by matthiasscudlik** [comment]
Why are you using angular-cli and systemjs at the same time?

If you're not very familiar with the topic i'd recommend to create a brand new project with angular cli and copy your source and assets to the new project.

Having angular-cli installed globally, you can create a new project with 

ng new <projectname>

More information is available here: https://github.com/angular/angular-cli/wiki#getting-started

**Comment by Brocco** [comment]
Looks to me like an app configuration issue and not an actual issue with the CLI, so I am closing this issue.

From a quick glance, it looks like you want to configure your base-href to be `my-app` which you can set via command line and `.angular-cli.json`

**Comment by nhhockeyplayer** [comment]
this remains still an issue
