### ISSUE TITLE
Barrels and circular dependencies

### ISSUE THREAD

**Issue by zygimantas** [angular/angular-cli#7326]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.0
node: 8.1.2
os: win32 x64
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

### Repro steps.

    index.ts

    export * from "./a";
    export * from "./b";

    a.ts

    import { A, B } from "./";

    export class A {
    }

### The log given by the failure.

WARNING in Circular dependency detected:

### Desired functionality.

An option to disable this warning

### Mention any other details that might be useful.

First seen with Angular CLI 1.3.0

**Comment by PierreDuc** [comment]
In `.angular-cli.json` set the `showCircularDependencies` to false:

```
{
  ...
  "defaults": {
     ...
     "build": {
       "showCircularDependencies": false
      }
   }
}
```
