### ISSUE TITLE
Nearly unuseful completion for generate

### ISSUE THREAD

**Issue by loganmzz** [angular/angular-cli#7330]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.7
node: 7.10.1
os: linux x64

### Repro steps.
* From a project (assuming both global & local versions are same)
* Install completion
`. <(ng completion)`
* Start entering `ng generate `
* (A) Press tab to ask for completion
The following proposal are made: `-d          --dry-run   -lf         --lint-fix  -v          --verbose` which isn't very helpful.
* Go further with `ng generate component `
* Press tab to ask for completion
Files in current directory are proposed ...

### The log given by the failure.
N/A

### Desired functionality.
Step A) List options described by `ng help generate` with only global entries as long as : `class`, `component`, `directive`, `enum`,  `guard`, ... 
Step B) List options specific to component generation

### Mention any other details that might be useful.
N/A

**Comment by mgechev** [comment]
Is still issue still reproducible with the latest CLI?

**Comment by mgechev** [comment]
Closing it due to inactivity. If the problem is still reproducible with the latest CLI, please open a new issue following the template and sharing a minimal demo where we can reproduce it. Thank you! :)
