### ISSUE TITLE
Uncaught TypeError: useValue,useFactory,data is not iterable! Angular 4 cli project error

### ISSUE THREAD

**Issue by FiReBlUe45** [angular/angular-cli#7337]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.3.0
node: 7.7.0
os: win32 x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/platform-server: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

### Repro steps.
I am new to Angular 4 , I have just created a project by Angular Cli and I get error as

`Uncaught TypeError: useValue,useFactory,data is not iterable! `

I an unable to resolve it. I installed and reinstalled cli , I just want to know how can I resolve it. All I did was

```
ng new myprj 
 mkdir myprj 
 ng serve
```

### The log given by the failure.

![image](https://user-images.githubusercontent.com/7797712/29169649-5d7f6478-7dd5-11e7-808d-7a36669013c2.png)

thank you

**Comment by filipesilva** [comment]
You seem to be using Chrome, correct? Can you try opening the page in an incognito tab? One of your extensions might be doing funny stuff.

**Comment by ShinDarth** [comment]
this solved this issue for me:

https://github.com/karma-runner/karma-phantomjs-launcher/issues/205#issuecomment-324243832

however now I got another issue:
```
        ReferenceError: Can't find variable: Intl in http://localhost:9876/_karma_webpack_/vendor.bundle.js (line 49362)
        intlDateFormat@http://localhost:9876/_karma_webpack_/vendor.bundle.js:49362:20
        http://localhost:9876/_karma_webpack_/vendor.bundle.js:49423:59
        http://localhost:9876/_karma_webpack_/vendor.bundle.js:49458:31
        reduce@[native code]
        dateFormatter@http://localhost:9876/_karma_webpack_/vendor.bundle.js:49456:24
        format@http://localhost:9876/_karma_webpack_/vendor.bundle.js:49478:29
        transform@http://localhost:9876/_karma_webpack_/vendor.bundle.js:49841:36
        buildAvailabilityObject@http://localhost:9876/_karma_webpack_/main.bundle.js:2165:47
        http://localhost:9876/_karma_webpack_/main.bundle.js:2028:63
        execute@http://localhost:9876/_karma_webpack_/vendor.bundle.js:97646:24
        http://localhost:9876/_karma_webpack_/vendor.bundle.js:97769:52
        invoke@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6227:31
        onInvoke@http://localhost:9876/_karma_webpack_/vendor.bundle.js:44848:45
        invoke@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6226:40
        run@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:5977:49
        http://localhost:9876/_karma_webpack_/vendor.bundle.js:44545:37
        execute@http://localhost:9876/_karma_webpack_/vendor.bundle.js:44573:46
        execute@http://localhost:9876/_karma_webpack_/vendor.bundle.js:44573:46
        invokeTask@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6260:36
        runTask@http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6027:57
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
