### ISSUE TITLE
Require .svg files

### ISSUE THREAD

**Issue by LaurenceMommers** [angular/angular-cli#7346]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.2.6
node: 6.10.3
os: linux x64
@angular/animations: 4.3.2
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/platform-server: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.2

### Desired functionality.
Is it possible to implement the raw-loader for .svg files? ( the new version of ckeditor (5) is importing svg files using `import quoteIcon from '@ckeditor/ckeditor5-core/theme/icons/quote.svg';` at the moment this is the only thing breaking ckeditor5 in my angular cli project.)

**Comment by filipesilva** [comment]
That isn't a valid ES6 import, and in general we try to not support non-standard syntax in imports. I don't know how that package is meant to be used but it seems like you need custom setup in your build system to support it.

We have loaders but that's for CSS since it does have a syntax for importing images/etc.

**Comment by LaurenceMommers** [comment]
The package indeed has a custom setup in the build system, but it builds successfully with the default angular/cli configuration, except it doesn't include the svg files. I kinda liked the way they included the svg files.

But okay, i agree, if it's not a valid way of importing than not supporting it is the best way to go, and i'll just have to deal with the pre-packaged script or remove angular/cli from my project and create my own webpack config.

**Comment by filipesilva** [comment]
Another open is to use `ng eject`, that will give you a webpack configuration you can tweak. If there's a way to load SVG from CSS that's also well supported overall.
