### ISSUE TITLE
`ng serve` should utilize the deployUrl set in appConfig

### ISSUE THREAD

**Issue by smasher816** [angular/angular-cli#7347]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
```
@angular/cli: 1.2.7
node: 6.11.1
os: linux x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.2.7
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3
```

### Repro steps.
Create a new app.
Set `deployUrl:"/deploy"` and `baseHref:"/deploy"` in `.angular-cli.json["apps"][0]`.
Run `ng serve`.
Attempt to access http://localhost:4200/deploy/.

### The log given by the failure.
\*.bundle.js fail to load

### Desired functionality.
`ng serve` should respect the deployUrl option set in `.angular-cli.json`

### Mention any other details that might be useful.
Running `ng serve --deploy-url "/deploy" --base-href "/deploy"` and accessing http://localhost:4200/deploy/ works as expected.

I can manually specify --deploy-url on the command line, but would prefer to have serve default to the one set in my app config. The deployUrl option is already in the schema (https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/lib/config/schema.json#L78) but does not appear to be used by serve at the moment.

**Comment by lukemadera** [comment]
Seconded - I learned this the hard way as well. I've removed use of deployUrl as it is not reliable. Please make it be used and respected everywhere!

**Comment by kaliaparijat-prosper** [comment]
Just fyi, but ngServe doesn't care about the deployUrl as resources are served from within memory and disk cache. This is specifically meant for deploying on an upper environment, where you are likely serving your assets through a server route.
