### ISSUE TITLE
register hostname with option in ng test

### ISSUE THREAD

**Issue by euprogramador** [angular/angular-cli#7348]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```bash 
ng v
   _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.7
node: 6.9.2
os: linux x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.2.7
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

node --version
6.9.2

yarn --version 
yarn version v0.18.1
```

### Repro steps.
```bash
 ng test --colors --hostname=10.0.0.1 
The option '--hostname' is not registered with the test command. Run `ng test --help` for a list of supported options.
 10% building modules 1/1 modules 0 active10 08 2017 18:35:34.573:WARN [karma]: No captured browser, open http://10.0.0.1:9876/
....
```

### The log given by the failure.
Not failure

### Desired functionality.
The hostname parameter works, however the angular-cli log displays a warning:

The option '--hostname' is not registered with the test command. Run `ng test --help` for a list of supported options.

The ng e2e command has an equal feature that allows the hostname to be changed.

I would like to have only the feature supported in the api for the message to stop being displayed.

The ability to swap the hostname is interesting in a seamless integration environment that runs via selenium. I'm using this in continuous integration, running karma with selenium webdriver running on another host via docker.

### Mention any other details that might be useful.
N/A

**Comment by filipesilva** [comment]
So what's happening is that `ng test` itself doesn't support that options, but we pass all options on to the Karma configuration, and it supports hostname. 

We probably should change this message to indicate that the option is being forwarded.

**Comment by giggio** [comment]
On the current version I get `Unknown option: '--hostname'` and the test does not run.

**Comment by filipesilva** [comment]
We've since tightened up option parsing and the current behaviour is intended. The best way to use different karma option sets is to change the `--karmaConfig` option instead.
