### ISSUE TITLE
Windows ngtools/webpack AoT compilation hangs infinitely at 95% emitting SCSS / SASS files, or gives "Module not found: Error: Can't resolve './../../../$$_gendir"

### ISSUE THREAD

**Issue by IAMtheIAM** [angular/angular-cli#7349]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Win10x64

>npm -v
4.6.1

>node -v
v6.10.0

### The log given by the failure.

When using ExtractTextPluing, webpack hangs at 95% emitting, 

When using webpack-dev-server (no extracttextplugin), I get  `Module not found: Error: Can't resolve './../../../$$_gendir/...` 

### Desired functionality.

AOT should compile when using .scss / SASS files. I need to be able to use loaders in this order:

`'style-loader', 'css-loader?sourceMap', postcss-loader, sass-loader, sass-resources-loader, @epegzz/sass-vars-loader`

The only way to get it to compile is to put `raw-loader` in front of it, but then my css files are not appended to the head since that is the job of `style-loader` being the final output.

Otherwise it ruins the scss compilation and output.

### Mention any other details that might be useful.

[3019] has the same problem but was closed before the issue is actually solved.
 People are still reporting this error months later, I can reproduce. (https://github.com/angular/angular-cli/issues/3019)

**Comment by IAMtheIAM** [comment]
I was able to get my config to compile successfully by following the advice from @dobbydog. I do not understand why this works, can someone explain?

This is my scss loader. The only thing I changed was adding an additional scss loader for .component.scss extensions, using raw loader, and then for any other .scss file I excluded component.scss extensions and used my normal config. 

However the weird part is the naming convension I use it app.style.scss so that means the first rule would not apply to it anyway. I also don't use the styleUrls property, I import the .scss file outside of the @Component decorator so that the styles load in the global context, rather than scoped by component.

```
 {
        test: /\.component\.scss$/,
        use: ['raw-loader']
},
{
        test: /\.(scss)$/,
        exclude: /\.component\.scss$/,
        use:
          isDevServer ? [
              'style-loader',
              {
                loader: 'css-loader',
                options: { sourceMap: true }
              },
              {
                loader: 'postcss-loader',
                options: { postcss: [AutoPrefixer(autoPrefixerOptions)], sourceMap: true }
              },
              {
                loader: 'sass-loader',
                options: { sourceMap: true }
              },
              {
                loader: 'sass-resources-loader',
                options: {
                  resources: [
                    './src/assets/styles/variables.scss',
                    './src/assets/styles/mixins.scss']
                }
              }, /**
               * The sass-vars-loader will convert any module.exports of a .JS or .JSON file into valid SASS
               * and append to the beginning of each .scss file loaded.
               *
               * See: https://github.com/epegzz/sass-vars-loader
               */
              {
                loader: '@epegzz/sass-vars-loader?',
                options: querystring.stringify({
                  vars: JSON.stringify({
                    susyIsDevServer: susyIsDevServer
                  })
                })
              }] : // dev mode
          ExtractTextPlugin.extract({
            fallback: "css-loader",
            use: [
              {
                loader: 'css-loader',
                options: { sourceMap: true }
              },
              {
                loader: 'postcss-loader',
                options: { postcss: [AutoPrefixer(autoPrefixerOptions)], sourceMap: true }
              },
              {
                loader: 'sass-loader',
                options: { sourceMap: true }
              },
              {
                loader: 'sass-resources-loader',
                options: {
                  resources: [
                    './src/assets/styles/variables.scss',
                    './src/assets/styles/mixins.scss']
                }
              }, {
                loader: '@epegzz/sass-vars-loader?',
                options: querystring.stringify({
                  vars: JSON.stringify({
                    susyIsDevServer: susyIsDevServer
                  })
                  // // Or use 'files" object to specify vars in an external .js or .json file
                  // files: [
                  //    path.resolve(helpers.paths.appRoot + '/assets/styles/sass-js-variables.js')
                  // ],
                })
              }],
            publicPath: '/' // 'string' override the publicPath setting for this loader
          })
      },
```

**Comment by filipesilva** [comment]
I'm glad you got it working, but I should clarify that html/css/pre-processed css that is included via `templateUrl/stylesUrl` is always required to be loaded via `raw-loader`. This is because it's component html/css, that will be inlined in the component, and should not be present in global css.
