### ISSUE TITLE
Question: What are the differences between versions of Angular in Angular-cli?

### ISSUE THREAD

**Issue by vapits** [angular/angular-cli#735]
Hi there,

I'm wondering, Angular is on `rc-1` version but through angular-cli project I can download up to `beta.17`.

**Comment by thorstenschaefer** [comment]
I upgraded to the Angular CLI beta and every new project is using Angular RC-1. Are you using an older version of CLI?

**Comment by vapits** [comment]
I use the latest. I'll investigate further maybe it's something related with my node version or something because I untinstall everything install everything again and still can't get latest angular version not even get the functionality for somethings presented on ng-conf for cli.

I'll close this and I'll open only real issues if I found something specific.

thx
