### ISSUE TITLE
@latest ng new 5.0.0-beta.3 app

### ISSUE THREAD

**Issue by dmlb** [angular/angular-cli#7351]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X ] feature request
- [ X ] question
```

### Versions.

```
@angular/cli: 1.3.0
node: 7.0.0
os: darwin x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.4
@angular/language-service: 4.3.4
```
MacOS El Capitan

### Repro steps.

```
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@latest
```

`ng new app`
Manually change package.json to 5.0.0-beta.3
`cd app` 
`npm i`

### The log given by the failure.

```
├── UNMET PEER DEPENDENCY @angular/compiler@5.0.0-beta.3
├── UNMET PEER DEPENDENCY @angular/core@5.0.0-beta.3
└── codelyzer@3.1.2

npm WARN codelyzer@3.1.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.
npm WARN codelyzer@3.1.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.
```

### Desired functionality.

What is the command to get the actual beta / start a new beta 5.0.0 app?

To able to ng new app and get the correct package.json to create a 5.0.0-beta.3 app.

### Mention any other details that might be useful.

https://github.com/angular/angular/blob/master/CHANGELOG.md#500-beta3-2017-08-09

**Comment by grizzm0** [comment]
This is not an issue of AngularCLI. As the warning states it's an unmet dependency of codelyzer.
It's just a warning and it might work just fine.

See https://github.com/mgechev/codelyzer/issues/391 for more info.

**Comment by hansl** [comment]
Closing this by @grizzm0 reply.
