### ISSUE TITLE
Can't add functions to the JSON object

### ISSUE THREAD

**Issue by bradyshutt** [angular/angular-cli#7352]
I'm trying to add [Crockford's Cycle.js](https://github.com/douglascrockford/JSON-js/blob/master/cycle.js) to my app. 

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.1.2
node: 7.10.0
os: linux x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.1.2
@angular/compiler-cli: 4.3.4
@angular/language-service: 4.3.4

### Repro steps.

1. Generate new CLI project with `ng new test`
2. Append to `head` of `index.html`
```
    <script type="text/javascript">
        // Copy paste Crockford's raw script. This basically begins like:
        //     if (typeof JSON.decycle !== "function") {
        //         JSON.decycle = function decycle(object, replacer) {
        //               ...
        //         }
        //    }
    </script>
```
3. Run `ng serve`
4. From dev console, `console.log(JSON.decycle)` prints `undefined`.

### The log given by the failure.

No errors are logged. 

### Desired functionality.

I should be able to use `JSON.decycle` and `JSON.retrocycle`. Running `console.log(JSON)` shows that these methods do not exist on the JSON object.  

### Mention any other details that might be useful.

If I insert a `console.log(JSON.decycle)` inside the setup script tag, right after the declaration of `JSON.decycle`, I see that `decycle` is indeed a method on the JSON object. However, when I attempt the same thing outside of that script tag (in code, or in the dev console), `console.log(JSON.decycle)` prints `undefined`.

Also, just dropping that entire script into the dev console successfully adds the methods to the JSON object. 

It seems like modifications to the JSON object aren't being preserved.

**Comment by mgechev** [comment]
For support requests, you can use gitter or take a look at StackOverflow for more information. If I've misunderstood the problem, please open a new issue, thanks!
