### ISSUE TITLE
ng test --watch=false outputs poorly formatted errors on build failure

### ISSUE THREAD

**Issue by diminutivesloop** [angular/angular-cli#7353]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.0
node: 6.9.1
os: win32 x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/compiler-cli: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/platform-server: 4.2.5
@angular/router: 4.2.5
@angular/upgrade: 4.2.5
@angular/cli: 1.3.0
@angular/language-service: 4.2.5
@ngtools/webpack: 1.5.0

### Repro steps.

1. Introduce a compile-time error into one of the project Typescript files.
2. Run tests via `ng test --watch=false`.
=> The tests fail on a build error with error output that is poorly formatted and hard to read.
![image](https://user-images.githubusercontent.com/667716/29193579-f78e3080-7df3-11e7-8458-796c9b7eadf0.png)

### Desired functionality.

The output should be formatted similarly to the build error output when running tests with file watching enabled.
![image](https://user-images.githubusercontent.com/667716/29193708-74034470-7df4-11e7-95d9-015b05aca5be.png)

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by mgechev** [comment]
Closing it due to inactivity. If the problem is still reproducible with the latest CLI, please open a new issue following the template and sharing a minimal demo where we can reproduce it. Thank you! :)
