### ISSUE TITLE
Error logging (feature request)

### ISSUE THREAD

**Issue by nekkon** [angular/angular-cli#7355]
New tool

During usage of angular-cli there could be an Error/Usage logging tool that would monitor user experience. After approval of users, errors that occur would be recorded (and automatically create an issue, if it is not a user error and does not already exist). This would help the angular-cli team in the following ways:

1. Prioritize issues based on frequency. The Angular-cli team would be able to easily focus on important problems.

2. Users do not have to create issues as they will be automatically created. 

     a. This will avoid duplicates as the system would be able to detect if it already exists but also all important errors will be reported during usage. This would overall improve angular-cli. 

     b. Issues would be solved much faster as they will be automatically generated with all necessary info to replicate and solve. Angular-cli's time wil not be consumed to understand the problem and have communication delays with users.

3. If something goes wrong with a new release it will be quickly dealt with before affecting the community.

This is just a suggestion to improve things.

**Comment by filipesilva** [comment]
@Brocco was looking at stats/monitoring options, this sounds like it would fit in there.

**Comment by alan-agius4** [comment]
Closing as this is not currently in the Angular CLI roadmap.
 Let's re-consider this in the future.
