### ISSUE TITLE
Bootstrap test is failing after 4.0.0 went beta

### ISSUE THREAD

**Issue by Brocco** [angular/angular-cli#7358]
This [test](https://github.com/angular/angular-cli/blob/master/tests/e2e/tests/third-party/bootstrap.ts) is failing because there is no longer a dependency on jQuery.

The test linked to above needs updated accordingly.

Note: as it currently stands, CI will not pass until this is resolved.

**Comment by JSMike** [comment]
> there is no longer a dependency on jQuery.

and there was much rejoicing!

**Comment by JSMike** [comment]
@Brocco `bootstrap.js` for boostrap beta still requires jQuery :(

```
if (typeof jQuery === 'undefined') {
  throw new Error('Bootstrap\'s JavaScript requires jQuery. jQuery must be included before Bootstrap\'s JavaScript.')
}
```

**Comment by brunobaiano** [comment]
and popper.js

**Comment by pkozlowski-opensource** [comment]
For anyone who is using Bootstrap 4 with Angular and doesn't want to jump through all the jQuery / popper.js hops, we've just release beta version of native Angular directives (no need for jQuery, no need for popper.js: https://ng-bootstrap.github.io. It is fully compatible with Bootstrap 4 beta released today.

**Comment by KSuttle-cng** [comment]
Is there documentation on how to go from the Bootstrap Sass package that is generated/used by this CLI to BS 4?
