### ISSUE TITLE
@Angular/Cli Installation Error Mac OS Sierra 

### ISSUE THREAD

**Issue by macgenius27** [angular/angular-cli#7359]
### Bug Report or Feature Request (mark with an `AngularJS Installation Error`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.0
node: 8.3.0
os: darwin x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: error
@angular/compiler-cli: error
@angular/language-service: error

##MY NODE JS is already working with NPM 5.3.0

### Repro steps.

bash-3.2$ npm install -g @angular/cli
/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng

> fsevents@1.1.2 install /usr/local/lib/node_modules/@angular/cli/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/@angular/cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.5.3 install /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-57_binding.node": 

tunneling socket could not be established, cause=getaddrinfo ENOTFOUND host host:80

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/local/lib/node_modules/@angular/cli/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.5.3 postinstall /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.3.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)\n    at F (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)\n    at E (/usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)\n    at /usr/local/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16\n    at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5\n    at /usr/local/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /Volumes/DRIVE/Anaconda/anaconda/bin/python
gyp verb check python version `/Volumes/DRIVE/Anaconda/anaconda/bin/python -c "import platform; print(platform.python_version());"` returned: "3.6.0\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Volumes/DRIVE/Anaconda/anaconda/bin/python" is v3.6.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:262:7)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:348:11)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at Socket.emit (events.js:210:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:549:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 (node_modules/@angular/cli/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @angular/cli@1.3.0
added 941 packages in 41.405s

### The log given by the failure.

I have python 3 installed and working on it.
I do not want to unistall it.

bash-3.2$ python --version
Python 3.6.0 :: Anaconda 4.3.0 (x86_64)

### Desired functionality.

If I install python2 it will create mess in python 3

### Mention any other details that might be useful.

I have tried uninstalling angular, node and npm it does not work.

**Comment by macgenius27** [comment]
Now I have installed Python2 
But It still give error
I have to install xcode

**Comment by JSMike** [comment]
yea, this is a node-gyp issue, for building libsass. you should be fine once you get xcode and [command line tools](http://railsapps.github.io/xcode-command-line-tools.html) installed.

**Comment by macgenius27** [comment]
The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)

**Comment by macgenius27** [comment]
After installing xcode and python i remove angular from my system reinstalled and still getting this error. When ng --version command I get this bash-3.2$ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.3.0
node: 8.3.0
os: darwin x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: error
@angular/compiler-cli: error
@angular/language-service: error
bash-3.2$

**Comment by filipesilva** [comment]
Heya, regarding pythong/xcode/etc - you don't need them to install Angular CLI per se. `node-sass` will try to download precompiled binaries but in your system that failed:

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-57_binding.node":

tunneling socket could not be established, cause=getaddrinfo ENOTFOUND host host:80

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.
```

So it might be that either:
- there are no pre-built binaries for your system (this is a combo of OS and Node versions).
- you are behind a proxy or something that prevents you from downloading them.

Either way have a look at the https://github.com/sass/node-sass issue tracker to see if they have problems with your system.

Regarding the other error:
```
The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
```

This means `@angular/compiler-cli` is not present in your node_modules. It's part of the `devDependencies` for new projects so if you are upgrading a project you need to add it.

**Comment by stevematdavies** [comment]
Same issue here March 2018
