### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by nonbackwards** [angular/angular-cli#736]
Where i can find the changelog? Thanks in advance.

**Comment by DevVersion** [comment]
Would like to implement it, as same as in Material 2.
- https://github.com/angular/material2/commit/70ab791addbc1a0b540edb6bb0a555f464992750

**Comment by filipesilva** [comment]
Changelog has been added via https://github.com/angular/angular-cli/commit/1fa0c31c8e9330933af484b0a1c3dee26748dee9
