### ISSUE TITLE
Wrong registration path of worker-basic.min.js

### ISSUE THREAD

**Issue by zygimantas** [angular/angular-cli#7365]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.0
node: 8.1.2
os: win32 x64
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.4
@angular/language-service: 4.3.4
@angular/service-worker: 1.0.0-beta.16

### Repro steps.

"serviceWorker": true in angular-cli.json

### Desired functionality.

```sw-register.[hash].bundle.js``` contains ```navigator.serviceWorker.register("worker-basic.min.js")```
If ```sw-register.[hash].bundle.js``` is located in folder, and the url is: ```domain.com/bundles/sw-register.[hash].bundle.js```, browser searches for ```worker-basic.min.js``` in the root folder, like this: ```domain.com/worker-basic.min.js```

I expect that the path to worker-basic.min.js should be ```bundles/worker-basic.min.js```
Are there any workarounds?

**Comment by mackelito** [comment]
Still no workaround?

**Comment by vincedgy** [comment]
Workaround for me is to cp ngsw-worker.js to worker-basic.min.js in /dist directory.
But it's durty trick.

**Comment by gkalpak** [comment]
This should be an issue any more when using the latest versions.
Can someone confirm that?

**Comment by zygimantas** [comment]
I am closing this issue because it was raised by me, and there were a lot of changes regarding service working during the last year. I can not replicate this issue now.
