### ISSUE TITLE
Replace PhantomJS with headless Chrome

### ISSUE THREAD

**Issue by EvAlex** [angular/angular-cli#7368]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

Any version

### Repro steps.

Generate project. See that tests are configured to use PhantomJS.

### Desired functionality.

I propose that Chrome in headless mode will be configured as tests running browser instead of PhantomJS in scaffolded project. Chrome headless is a reasonable replacement as it provides more accurate and less error prone testing.

### Mention any other details that might be useful.

Chrome 59 (60 on Windows) can now be run with `--headless` https://www.chromestatus.com/features/5678767817097216

It's also worth mentioning that Gitlab project has almost done the same issue https://gitlab.com/gitlab-org/gitlab-ce/issues/30876 Looks like it's a good choice to use Chrome headless.

**Comment by devoto13** [comment]
See https://github.com/angular/angular-cli/pull/7020.

**Comment by EvAlex** [comment]
I only searched for an issue, but there's already a pull request for this! Missed it.

**Comment by filipesilva** [comment]
I'm not sure where you're looking at, but in the CLI we don't configure projects to use PhantomJS. Maybe that happened a long time ago (like two years ago) but it hasn't in a long time.

Chrome Headless is being discussed in #7020 as @devoto13 mentioned.
