### ISSUE TITLE
Not able to create new project with Angular + windows10

### ISSUE THREAD

**Issue by pardhutechnical** [angular/angular-cli#7370]
Getting error while creating new project.

### Versions.
Windows_NT 10.0.15063
 angular/cli 1.3.0
 node v8.2.1
 npm  v5.2.0

### The log given by the failure.
11475 verbose unlock done using C:\Users\XXX\AppData\Roaming\npm-cache\_locks\staging-e586857f35c37a81.lock for G:\workspace\first-angular-pjt\node_modules\.staging
11476 warn enoent ENOENT: no such file or directory, open 'G:\workspace\first-angular-pjt\package.json'
11477 verbose enoent This is related to npm not being able to find a file.
11478 warn first-angular-pjt No description
11479 warn first-angular-pjt No repository field.
11480 warn first-angular-pjt No README data
11481 warn first-angular-pjt No license field.
11482 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
11483 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'G:\workspace\first-angular-pjt\node_modules\.staging\fsevents-03b228b5\node_modules\abbrev' -> 'G:\workspace\first-angular-pjt\node_modules\.staging\abbrev-e431bcc4'
11484 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
11484 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
11485 verbose type OperationalError
11486 verbose stack Error: sha1-OfaZ86RlYN1eusvKaTyvfGXBjMY= integrity checksum failed when using sha1: wanted sha1-OfaZ86RlYN1eusvKaTyvfGXBjMY= but got sha1-Rq++iNFVBOku6G/VwrmLALuQ+vA=. (10513 bytes)
11486 verbose stack     at Transform.on (C:\Users\XXX\.webclipse\npm\5.2.0\node_modules\ssri\index.js:275:19)
11486 verbose stack     at emitNone (events.js:110:20)
11486 verbose stack     at Transform.emit (events.js:207:7)
11486 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
11486 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
11486 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
11487 verbose cwd G:\workspace\first-angular-pjt
11488 verbose Windows_NT 10.0.15063
11489 verbose argv "C:\\Users\\XXX\\.webclipse\\nodejs\\8.2.1\\node.exe" "C:\\Users\\XXX\\.webclipse\\npm\\5.2.0\\bin\\npm-cli.js" "install" "@angular/cli@1.3.0"
11490 verbose node v8.2.1
11491 verbose npm  v5.2.0
11492 error code EINTEGRITY
11493 error sha1-OfaZ86RlYN1eusvKaTyvfGXBjMY= integrity checksum failed when using sha1: wanted sha1-OfaZ86RlYN1eusvKaTyvfGXBjMY= but got sha1-Rq++iNFVBOku6G/VwrmLALuQ+vA=. (10513 bytes)
11494 verbose exit [ 1, true ]

**Comment by bastienJS** [comment]
I had this too but I did not do 'ng new projectname' in the the folder where the package.json was located. Please make sure you do it correctly :-)

**Comment by filipesilva** [comment]
Yeah this error isn't with Angular CLI itself but with npm. You seem to be getting `integrity checksum failed when using sha1` error that prevent you from installing packages. Have a look at https://github.com/npm/npm to see if the error you have is known.
