### ISSUE TITLE
Add new script 'ng update'

### ISSUE THREAD

**Issue by yokots** [angular/angular-cli#7375]
### Feature Request
```
- [X] feature request
```

### Description

When update the version of angular/cli, use ng update to update the configuration files like tsling.json and tsconfig.json etc. or and postinstall hooks to auto update the configuration files.

**Comment by BurningDog** [comment]
That would be great, but any of these things could have been manually changed. What if the author wants those changes preserved? Then any time angular-cli is upgraded their changes would be overwritten.

Currently when I upgrade angular-cli, I generate an entirely new project structure and then compare every file I can find against my own files, including:

* versions in package.json
* new packages in packages.json
* .angular-cli.json
* karma.conf.js
* protractor.conf.js
* tsconfig.json
* tslint.json
* src/polyfills.ts
* src/test.ts
* src/tsconfig.app.json
* src/tsconfig.spec.json

It's some manual work but I'm not sure how this could be automatically done.

**Comment by nekkon** [comment]
There are many issues that have as a root that developers do not update their apps properly, probably because they think that just changing the version in package.json is enough. [One](https://github.com/angular/angular-cli/issues/7334) of the many issues that exist.

**Comment by filipesilva** [comment]
This is something that we talk about every now and then... It's true that a lot of issues are due to bad upgrades. Configuration items like the ones listed by @BurningDog could be upgraded automatically. A health check would also be nice, like verifying incompatible options or packages aren't set.
