### ISSUE TITLE
 Hey am trying to install angular/cli using  npm install -g @angular/cli but am getting this error

### ISSUE THREAD

**Issue by Aula72** [angular/angular-cli#7376]
[npm-debug.txt](https://github.com/angular/angular-cli/files/1220599/npm-debug.txt)

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by BurningDog** [comment]
Hi @Aula72 - please read the steps from https://github.com/angular/angular-cli/issues/new and add that detail into your issue.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
