### ISSUE TITLE
Whether cli support IOS7?

### ISSUE THREAD

**Issue by 10081677wc** [angular/angular-cli#7382]
Hi, 
I' d like to ask about this: whether cli support IOS7?
I created an empty project, built, and made server by nginx, 
I can browse correctly in relatively new version, 
but blank in IOS7.1.1 (no log, no error, it seems like no .js files have been executed).

**Comment by 10081677wc** [comment]
Hi,
I find the root causeis "ReferenceError: Can't find variable: Proxy".
How can I solve this problem?

Thanks!

**Comment by devoto13** [comment]
Add a polyfill? See src/polyfills.ts.

**Comment by 10081677wc** [comment]
you are right, but i use polyfill from https://github.com/GoogleChrome/proxy-polyfill.

**Comment by hansl** [comment]
According to the last comment, this has been solved. Closing this. If there is still an issue, please open a new issue and follow the template. Thanks.
