### ISSUE TITLE
Infinite Loop with Docker / `npm -g install @angular/cli`

### ISSUE THREAD

**Issue by moloch--** [angular/angular-cli#7389]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Node v8.3.0
NPM v5.3.0

OS: Docker `buildpack-deps:jessie`

### Repro steps.

[docker build](https://gist.github.com/moloch--/fedde5dbf466a6faf2f288d04d6680d0)

### The log given by the failure.

```
RUN npm install -g @angular/cli

...removed...

> node-sass@4.5.3 postinstall /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.3.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.9\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.3.0
gyp verb command install [ '8.3.0' ]
gyp verb install input version string "8.3.0"
gyp verb install installing version: 8.3.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/8.3.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.3.0' ]
gyp verb install input version string "8.3.0"
gyp verb install installing version: 8.3.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.3.0
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.3.0
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.3.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.3.0' ]
gyp verb install input version string "8.3.0"
```
...repeating infinitely...

Note `RUN npm install -g node-gyp` seems to work fine.

### Desired functionality.

Installs properly

### Mention any other details that might be useful.

N/A

**Comment by rhuiser** [comment]
Having same issue.

**Comment by TravisFabel** [comment]
I am also having the same issue.

**Comment by treeder** [comment]
workaround is here: https://github.com/nodejs/node-gyp/issues/1236#issuecomment-309447800

**Comment by moloch--** [comment]
Okay the nodejs/node-gyp#1236 trick/workaround seems to fix it:

```
USER node
RUN mkdir /home/node/.npm-global
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
RUN npm install -g @angular/cli
```

**Comment by daBishMan** [comment]
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 7.x

when I am running when I try to launch ng tests using PhantomJS I get the above error?  anyone able to shed some light on why?  or how I can resolve it

**Comment by johanchouquet** [comment]
Same here. What I don't get is why there's no problem of user when using node 7.9.0.

For now, i'm keeping node 7.9.0.

**Comment by kirillgroshkov** [comment]
Same here!

**Comment by pstephenwille** [comment]
Same here, and I'm not using Docker on this project, its only installed on my machine.

**Comment by muzfr7** [comment]
Same on MacOS High Sierra (node v8.9.4 and npm 5.6.0) below statement loops again and again for more than 2 hours now..
`gyp WARN install version not already installed,, continuing with install 8.9.4`

**Comment by PhilThurston** [comment]
This bug is still reproducible on `Ubuntu Xenial` and `Debian Jessie`. I appreciate that there is a workaround but shouldn't the issue remain open since there is no actual fix just workarounds?

For those coming from google to quickly get around this use this command to install:
```
npm install -g @angular/cli --unsafe
```
the `--unsafe` gets it to complete without the loop

**Comment by Epicnessism** [comment]
I see that this thread is now closed. Has there been an actual fix or is everyone still just using the --unsafe command? I got a similar error when installing today. The unsafe command fixed the infinite loop issue for me as well.

**Comment by sethkoch** [comment]
Actually, if you just control c out of the loop, you'll see that angular cli is installed.

**Comment by AnalyzePlatypus** [comment]
Still getting this in March 2018:
```Dockerfile
FROM node:8.0
RUN npm install -g @angular/cli
```
This spins into an infinite loop when in gets to the `gyp` build part.
Using @PhilThurston's `--unsafe` option helped me.

Why is this still a problem?

**Comment by knicholes** [comment]
Tried installing this with the latest Node docker image.  Received the loop because it didn't want to install as root.  Use the `node` user, but I didn't have write permissions to where I wanted to install.  Tried --unsafe with success.

**Comment by asottile** [comment]
```bash
npm_config_user=root npm install -g ...
```

works for me
