### ISSUE TITLE
during install, mkdir uc.micro failed on windows 7

### ISSUE THREAD

**Issue by ceced** [angular/angular-cli#739]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

$ node --version
v4.4.4

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

npm install -g angular-cli

4. The log given by the failure. Normally this include a stack trace and some
   more information.

140520 info install bower@1.7.9
140521 info postinstall bower@1.7.9
140522 verbose unlock done using C:\Users\m346221\AppData\Roaming\npm-cache\_locks\bower-e9a25357a51bcd3d.lock for C:\workspaces\angular\node_modules\angular-cli\node_modules\ember-cli\node_modules\bower
140523 verbose about to build C:\workspaces\angular\node_modules\angular-cli\node_modules\ember-cli
140524 verbose unlock done using C:\Users\m346221\AppData\Roaming\npm-cache\_locks\ember-cli-333e4f52b94c615e.lock for C:\workspaces\angular\node_modules\angular-cli\node_modules\ember-cli
140525 verbose about to build C:\workspaces\angular\node_modules\angular-cli
140526 verbose unlock done using C:\Users\m346221\AppData\Roaming\npm-cache\_locks\angular-cli-24f02dc10fa0be9b.lock for C:\workspaces\angular\node_modules\angular-cli
140527 verbose stack Error: EPERM: operation not permitted, mkdir 'C:\Users\m346221\AppData\Local\Temp\npm-612-1c760466\registry.npmjs.org\uc.micro'
140527 verbose stack     at Error (native)
140528 verbose cwd C:\workspaces\angular
140529 error Windows_NT 6.1.7601
140530 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular-cli"
140531 error node v4.4.4
140532 error npm  v2.15.1
140533 error path C:\Users\m346221\AppData\Local\Temp\npm-612-1c760466\registry.npmjs.org\uc.micro
140534 error code EPERM
140535 error errno -4048
140536 error syscall mkdir
140537 error Error: EPERM: operation not permitted, mkdir 'C:\Users\m346221\AppData\Local\Temp\npm-612-1c760466\registry.npmjs.org\uc.micro'
140537 error     at Error (native)
140537 error  { [Error: EPERM: operation not permitted, mkdir 'C:\Users\m346221\AppData\Local\Temp\npm-612-1c760466\registry.npmjs.org\uc.micro']
140537 error   errno: -4048,
140537 error   code: 'EPERM',
140537 error   syscall: 'mkdir',
140537 error   path: 'C:\\Users\\m346221\\AppData\\Local\\Temp\\npm-612-1c760466\\registry.npmjs.org\\uc.micro',
140537 error   parent: 'markdown-it' }
140538 error Please try running this command again as root/Administrator.
140539 verbose exit [ -4048, true ]

5. Mention any other details that might be useful.

tried with windows command line with admin rights ( but cannot bypass corporate gpo ), and without admin rights.
tried with git bash ( mingw32 ) with admin rights ( but cannot bypass corporate gpo ), and without admin rights.
Same results ...

It seems we cannot create a dir called something.micro on windows 7 ?
Strange...
Thank you for your help !

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
Hi, try with Node 5. It might solve your problem.

Otherwise, I'm not sure what can be done here.
