### ISSUE TITLE
Angular not installing properly

### ISSUE THREAD

**Issue by hirasaleem03** [angular/angular-cli#7391]
Output from: `ng --version`: 'ng' is not recognized as an internal or external command,
operable program or batch file.
Output from: `node --version` 8.2.1 and `npm --version` 5.3.0
  Windows (10).

npm uninstall -g @angular/cli
npm cache clean -force
npm install -g @angular/cli

### The log given by the failure.
![image](https://user-images.githubusercontent.com/31027288/29302618-264c4c46-819f-11e7-8135-54dd264ac289.png)

It was working fine few days back before I uninstalled and re installed it again to update angular

**Comment by dcalsky** [comment]
It seems little clues which you provide 😢 

My advice is: 
- Improve network quality to fetch NPM registry
- Upgrade node to higher version
- Try `yarn global`

**Comment by filipesilva** [comment]
You seem to be having some problem with npm, you're getting checksum checks. You should have a look at https://github.com/npm/npm to see if this is a known problem.
