### ISSUE TITLE
ng is not recognized as an internal or external command

### ISSUE THREAD

**Issue by alievako** [angular/angular-cli#7392]
I installed angular-cli via command prompt. And then  I write ng new my-first-app, it doesn't work:  'ng' is not recognized as an internal or external command, operable program or batch file. How can I fix it?

**Comment by matthiasscudlik** [comment]
Did you install it globally?

CHeck out the wiki here: https://github.com/angular/angular-cli/wiki#getting-started

**Comment by alievako** [comment]
Yeap. I found solution. Comman Prompt should be runned as adminstrator. After that it recognized ng.

**Comment by hansl** [comment]
It does not require administrative rights, so there might have been something with your install (e.g. did you install CLI using administrative prompt?).

Closing this in any case as solved. Thanks!

**Comment by tarundvarma49** [comment]
Please try to use **Node.js command prompt** in your windows. It will work.
