### ISSUE TITLE
No eject output

### ISSUE THREAD

**Issue by gatimus** [angular/angular-cli#7396]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.3.0
node: 8.1.3
os: win32 x64
@angular/animations: 4.3.3
@angular/cdk: 2.0.0-beta.8-85a6fff
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/material: 2.0.0-beta.8-85a6fff
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

### Repro steps.
` ng eject --output-path ../webpack-project`
https://github.com/angular/angular-cli/wiki/eject#options

### The log given by the failure.
../webpack-project is empty

### Desired functionality.
../webpack-project contain ejected project

**Comment by filipesilva** [comment]
The `eject` command receives the same set of options as `ng build`, and `--output-path` actually controls where the built application should go (normally `dist/`). It does not control where the webpack config is generated, that's always the project root.

**Comment by gatimus** [comment]
So `--output-path` flag does nothing with `ng eject`? There is no mention of that on https://github.com/angular/angular-cli/wiki/eject#options. It says "`ng eject` ejects your app and **output** the proper webpack configuration and scripts", then for `--output-path` "Path where **output** will be placed." What I'm I too assume "output" is in this context.

Can I change this to a feature request for a flag to set where the result of `ng eject` is generated?

**Comment by filipesilva** [comment]
`--output-path` is an option of `ng build` that controls where the build goes. Since `ng eject` gives you a webpack config that will do the same as if you had called `ng build` with those options. So it does something with eject, it determines the output path for the build inside the webpack config.

**Comment by gatimus** [comment]
oooh that makes sense.

Will there ever be a way to "eject" a webpack project while maintaining an angular-cli project, or is that not the point?

**Comment by filipesilva** [comment]
There was a lot of discussion about the topic but it's not something that we want to do. You can read about it in https://github.com/angular/angular-cli/issues/1656.
