### ISSUE TITLE
Angular CLI changes colors of Windows command prompt font

### ISSUE THREAD

**Issue by ghost** [angular/angular-cli#7398]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.6
node: 7.9.0
os: win32 x64
@angular/animations: 4.1.2
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/platform-server: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.1.2

### Repro steps.
`ng serve` and then Ctrl+C to kill.

### The log given by the failure.
None, it's not a failure. The colors last used by cli seem to not be terminated so my command prompt stays forever in that color.

### Desired functionality.
Console should not change color of command prompt once killed.

### Mention any other details that might be useful.
None

**Comment by hansl** [comment]
Closing this as obsolete/fixed.

**Comment by pungiish** [comment]
The issue seems to have returned.
**Version:** @angular/cli 7.3.8
![image](https://user-images.githubusercontent.com/22725524/56378146-6d09d000-620c-11e9-9f1d-99a9cea2c8dc.png)
