### ISSUE TITLE
preserve-symlinks parameter is missing for ng test

### ISSUE THREAD

**Issue by intellix** [angular/angular-cli#7399]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

1.3.0

### Desired functionality.

Would like to use a monorepo using something like lerna/yarn workspaces and testing gives errors which can be sidetracked by using a symlinked @angular directory in the local node_modules folder:
```
ng test --preserve-symlinks
```

### Mention any other details that might be useful.

Example repository: https://github.com/spektrakel-blog/a-glimpse-at-yarn-workspaces
PR/Issue: https://github.com/spektrakel-blog/a-glimpse-at-yarn-workspaces/pull/2

**Comment by Euronia** [comment]
Similar to #7081

**Comment by intellix** [comment]
Ahah, thought I didn't find anything, thanks :)
