### ISSUE TITLE
IE11 Angular CLI not dispaling anythign when I run ng serve

### ISSUE THREAD

**Issue by agtechworld** [angular/angular-cli#7402]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Mention any other details that might be useful.

This is on IE11 on WIndows 7 
Adjusting polyfils.ts is not really helping to fix tis. I have uncommnted  the following lines but no use.
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/weak-map';
 import 'core-js/es6/set';

**Comment by deebloo** [comment]
@suresh191 please fill out the issue template. It is there to make it easier for folks to help you out

**Comment by suresh191** [comment]
I have filled out the template with all the information. When I search for the same issue in the Issue section, people suggesting to uncomment the imports under the section " IE9, IE10 and IE11 requires all of the following polyfills " in polyfill.ts file but believe me that is not helping in fixing this Issue.

**Comment by tech74** [comment]
I realized that it is not working if we put IE11 in compatibility mode. Not sure how we resolve this to make Angular CLI work for both Compatibility view and non compatibility view settings in IE 11.

**Comment by clydin** [comment]
Compatibility mode essentially makes IE act like IE7 which is not supported.

**Comment by filipesilva** [comment]
@tech74 please fill in the rest of the sections in the issue template (like versions, repro steps, etc), otherwise we can't really reproduce this and try to help you.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
