### ISSUE TITLE
Error installing angular-cli

### ISSUE THREAD

**Issue by Demch** [angular/angular-cli#7403]
version: OS windows 7 x64

![image](https://user-images.githubusercontent.com/3207363/29397483-158ec7b2-82e4-11e7-99ee-077b45fd6210.png)

Den@Den-PC MINGW64 ~
$ npm install -g @angular/cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: forever-agent@0.6.1 (node_modules\@angular\cli\node_modules\forever-agent):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-+8cfDEGt6zf5bFd60e1C2P2sypE= integrity checksum failed when using sha1: wanted sha1-+8cfDEGt6zf5bFd60e1C2P2sypE= but got sha1-B1PDQmVCmInusCOdC1QgZljvs5Q=. (2237 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: es6-set@0.1.5 (node_modules\@angular\cli\node_modules\es6-set):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-0rPsXU2ADO2BjbU40ol02wpzzLE= integrity checksum failed when using sha1: wanted sha1-0rPsXU2ADO2BjbU40ol02wpzzLE= but got sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=. (0 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: get-stream@3.0.0 (node_modules\@angular\cli\node_modules\get-stream):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\Den\AppData\Roaming\npm\node_modules\.staging\get-stream-52f781b0\readme.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: flatten@1.0.2 (node_modules\@angular\cli\node_modules\flatten):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-2uRqnXj74lKSJYzB54CkHZXAN4I= integrity checksum failed when using sha1: wanted sha1-2uRqnXj74lKSJYzB54CkHZXAN4I= but got sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=. (0 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: browserify-zlib@0.1.4 (node_modules\@angular\cli\node_modules\browserify-zlib):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\Den\AppData\Roaming\npm\node_modules\.staging\browserify-zlib-0ce9c37a\src\binding.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fast-deep-equal@1.0.0 (node_modules\@angular\cli\node_modules\fast-deep-equal):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-liVqO8l1WV6zbYLpkp0GDYk0Of8= integrity checksum failed when using sha1: wanted sha1-liVqO8l1WV6zbYLpkp0GDYk0Of8= but got sha1-Y0GX1GVyZBCu8lekygqApgUjY4U=. (2237 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: coa@1.0.4 (node_modules\@angular\cli\node_modules\coa):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\Den\AppData\Roaming\npm\node_modules\.staging\coa-4e929f95\README.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-forge@0.6.33 (node_modules\@angular\cli\node_modules\node-forge):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-RjgRh59XPUUVWtap9D3ClujoXrw= integrity checksum failed when using sha1: wanted sha1-RjgRh59XPUUVWtap9D3ClujoXrw= but got sha1-NQqNJAsTf/U1RjwE0ll4CHY+U5s=. (7753 bytes)

npm ERR! code EINTEGRITY
npm ERR! sha1-0eJkOzipTXWDtHkGDmxK/8lAcfg= integrity checksum failed when using sha1: wanted sha1-0eJkOzipTXWDtHkGDmxK/8lAcfg= but got sha1-N3PsNwYPg148UT877muvA7NrxfU=. (2238 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Den\AppData\Roaming\npm-cache\_logs\2017-08-17T05_28_13_567Z-debug.log

Den@Den-PC MINGW64 ~
$ node -v
v8.4.0

Den@Den-PC MINGW64 ~
$ npm -v
5.3.0

Den@Den-PC MINGW64 ~
$ ng new app
bash: ng: command not found

 help me please

**Comment by hansl** [comment]
@filipesilva any idea what could be happening here?

Unfortunately this looks like an error with NPM, not the Angular CLI project. Try running the same command in an Administrative prompt, but I don't think it's going to help that much.

**Comment by Demch** [comment]
You were right, it was not much help. But thanks for replying, I still can not locate the error but it seems to be a problem npm, anything will be written

**Comment by filipesilva** [comment]
Yeah this looks like a proxy problem or something, all, the SHA fail. Are you in China? If so, try using https://github.com/cnpm/cnpm. Sorry we can't be of more help. Perhaps have a look at their issue tracker, maybe it's a npm bug.
