### ISSUE TITLE
Deploy angular-cli to server with a specified domain

### ISSUE THREAD

**Issue by lamemmv** [angular/angular-cli#7404]
I have an angular-cli application. I want to deploy my angular app to server with specified domain like we do for deploying asp.net site to IIS.
Fox example: I want to deploy angular-cli to server with IP address: xxx.yyy.zzz.12 and I want to deploy it with domain http://mywebsite.abc. 
How can I do that? all those can be done in asp.net and IIS.
Please guide me to do step by step.
Thanks in advance.
-- | --

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by filipesilva** [comment]
When you do `ng build --prod` on an Angular CLI project, you will get a `dist/` folder containing a static HTML5+Javascript web page. You'll need to deploy the contents of that folder to a server configured properly to serve it.

You can find some more details in https://angular.io/guide/deployment. But whatever server you use, you must configure it properly yourself.
