### ISSUE TITLE
why use AOT build makes package larger???

### ISSUE THREAD

**Issue by icepoint0** [angular/angular-cli#7407]
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.3.0
node: 7.10.0
os: darwin x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5
@ngtools/webpack: 1.6.0

### Repro steps.

> > ng build --prod --env=prod
> 
> Date: 2017-08-17T09:51:04.817Z
> Hash: c3178166c863f38102f4
> Time: 81777ms
> chunk {0} polyfills.de832798906b961f9228.bundle.js (polyfills) 63.1 kB {5} [initial] [rendered]
> chunk {1} scripts.4856bba0037d818b4b78.bundle.js (scripts) 597 kB {5} [initial] [rendered]
> chunk {2} styles.5a30b9623295641d5263.bundle.css (styles) 91 kB {5} [initial] [rendered]
> chunk {3} main.f88ba2a213d342e8b5ec.bundle.js (main) 669 kB {4} [initial] [rendered]
> chunk {4} vendor.23688f64b59ddd0d9af4.bundle.js (vendor) 2.75 MB [initial] [rendered]
> chunk {5} inline.edcf24afd5127f1b8696.bundle.js (inline) 1.47 kB [entry] [rendered]
> ➜  jk git:(sit) ✗ npm run build
> 
> > cli-demo@0.0.0 build /Users/atyun/code/jk
> > ng build --prod --env=prod --aot=false
> 
> Date: 2017-08-17T09:55:09.800Z
> Hash: 9078035cfb1a455c8912
> Time: 42982ms
> chunk {0} polyfills.de832798906b961f9228.bundle.js (polyfills) 63.1 kB {5} [initial] [rendered]
> chunk {1} main.a6152a8c487ec0789e3d.bundle.js (main) 255 kB {4} [initial] [rendered]
> chunk {2} scripts.25eb458d0c065737b948.bundle.js (scripts) 597 kB {5} [initial] [rendered]
> chunk {3} styles.5a30b9623295641d5263.bundle.css (styles) 91 kB {5} [initial] [rendered]
> chunk {4} vendor.79c85fddeb80e26a71fd.bundle.js (vendor) 2.57 MB [initial] [rendered]
> chunk {5} inline.6ba6e525ed3ff1330143.bundle.js (inline) 1.47 kB [entry] [rendered]
> 

![Uploading aot.png…]()

**Comment by intellix** [comment]
After GZIP the size difference isn't so much, but basically AOT is a trade-off between parsing/size. 
Your HTML for instance can grow by about 7x to ensure that it's compiled and doesn't need to be do on the fly.

In ng2 your views grew about 33x, but now it's much better. There's an explanation about it all somewhere but I can't find it :) http://angularjs.blogspot.com.mt/2017/03/angular-400-now-available.html

**Comment by clydin** [comment]
It also allows the app to drop several vendor dependencies (more in the near future).

**Comment by ctrl-brk** [comment]
Here's a good explanation:
https://github.com/angular/angular-cli/issues/4896#issuecomment-281984124

**Comment by hansl** [comment]
Closing this as the question has been answered. Also, for questions like those, please use stackoverflow.com instead; this repo is for issues and feature requests only.
