### ISSUE TITLE
ngbdropdown from NgbDropdownModule is not working with new Angular CLI 1.3.0

### ISSUE THREAD

**Issue by danutz30** [angular/angular-cli#7410]
My ngbdropdown from NgbDropdownModule are not working with new Angular CLI 1.3.0

- [x] bug report -> please search issues before submitting
all my drop-down list are not showing anything
- [ x ] feature request

### Versions.

@angular/cli: 1.3.0
node: 6.11.2
os: win32 x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/compiler-cli: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/platform-server: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.0

### Repro steps.

try to press on an arrow from a list that use ngbdropdown and anything happens 

### Desired functionality.

How should I fix this issue ?
What would like to see implemented?
YES

**Comment by RicardoVaranda** [comment]
This issue seems to be regarding a module in ngBoostrap and should be reported here: https://github.com/ng-bootstrap/ng-bootstrap

**Comment by khaledosman** [comment]
I have the same problem, these are my local dependencies vs the latest ones..
If I upgrade everything it doesn't work.. if I upgrade ng-bootstrap only it still works, so it could be an angular issue.
![image](https://user-images.githubusercontent.com/2937633/29706836-8157cb06-8983-11e7-8fb3-29e17d36580e.png)

**Comment by khaledosman** [comment]
Had the same problem, installing the dependencies using npm instead of yarn fixed the problem :/

**Comment by danutz30** [comment]
Hello thanks guys. 

**BREAKING CHANGES 1.0.0-beta.2 (2017-08-23)**

dropdown: The up input is no longer supported by you can use more flexible placement setting now.
Before:

<div ngbDropdown [up]="true">
After:

<div ngbDropdown placement="top-right">

**BREAKING CHANGES 1.0.0-beta.1 (2017-08-11)**

ng-bootstrap now requires Bootstrap CSS 4.0.0-beta
buttons: The btn-group CSS class needs to added explicitly for radio buttons.
Before:

<div ngbRadioGroup ...>
  ...
</div>
After:

<div class="btn-group" ngbRadioGroup ...>
  ...
</div>
dropdown: Dropdown menu now requires usage of the new ngbDropdownMenu directive.
Before:

<div ngbDropdown>
  <button ngbDropdownToggle>Toggle dropdown</button>
  <div class="dropdown-menu">
    <a class="dropdown-item">Action</a>
  </div>
</div>

After (notice ngbDropdownMenu):

<div ngbDropdown>
  <button ngbDropdownToggle>Toggle dropdown</button>
  <div ngbDropdownMenu>
    <a class="dropdown-item">Action</a>
  </div>
</div>

**Comment by Brocco** [comment]
This is an issue with the particular library, not the CLI.. closing.
