### ISSUE TITLE
Angular/cli installation issue. code INTEGRITY.

### ISSUE THREAD

**Issue by gyanngaurav** [angular/angular-cli#7419]
I am trying to install angular/cli. I have tried it 50 times now. Earlier it was throwing an error of code EINTEGRITY. I tried many solutions finally uninstalled and reinstalled Node. Now I am getting this sort of error, I am not sure what it means. 
<img width="960" alt="2017-08-18 1" src="https://user-images.githubusercontent.com/31114248/29437922-409cf4e0-83d1-11e7-870f-0dcf4108e8eb.png">

C:\Users\Gyan>node -v
v6.11.2

C:\Users\Gyan>npm -v
3.10.10

C:\Users\Gyan>npm install -g @angular/cli
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\Gyan\AppData\Local\Temp\npm-9056-9b83df14\registry.npmjs.org\webpack-dev-server\-\webpack-dev-server-2.5.1.tgz
npm ERR! Expected: a02e726a87bb603db5d71abb7d6d2649bf10c769
npm ERR! Actual:   bbe31f0aa5b1bb0cfb723479db094c1bd0740e20
npm ERR! From:     https://registry.npmjs.org/webpack-dev-server/-/webpack-dev-server-2.5.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Gyan\npm-debug.log

**Comment by rdrrichards** [comment]
Try running the install using an administrator command prompt.

**Comment by gyanngaurav** [comment]
Thanks @rdrrichards , running as administrator solved the problem. Thanks again.

**Comment by ashishyadav0019** [comment]
u saved me @rdrrichards

**Comment by otipip90** [comment]
me too

**Comment by otipip90** [comment]
thanks ...
