### ISSUE TITLE
npm install package error

### ISSUE THREAD

**Issue by wanghaolu** [angular/angular-cli#7422]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.3.0
node: 8.4.0
os: win32 x64

### Repro steps.

1.ng new test --skip-install
2.cd test
3.npm install

### The log given by the failure.

1908 silly pacote range manifest for webpack-dev-server@~2.5.1 fetched in 72ms
1909 silly resolveWithNewModule webpack-dev-server@2.5.1 checking installable status
1910 silly pacote range manifest for webpack-merge@^4.1.0 fetched in 73ms
1911 silly resolveWithNewModule webpack-merge@4.1.0 checking installable status
1912 silly fetchPackageMetaData error for webpack@~3.4.1 Unexpected end of input at 1:452698
1912 silly fetchPackageMetaData bpack.js"},"directories":{},"dist":{"shasum":"7bb1d72ae2087dd1a4af526
1912 silly fetchPackageMetaData                                                                      ^
1913 silly pacote range manifest for node-sass@^4.3.0 fetched in 76ms
1914 silly resolveWithNewModule node-sass@4.5.3 checking installable status
1915 verbose stack SyntaxError: Unexpected end of input at 1:452698
1915 verbose stack bpack.js"},"directories":{},"dist":{"shasum":"7bb1d72ae2087dd1a4af526
1915 verbose stack                                                                      ^
1915 verbose stack     at Object.parseJSON (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-helpfulerror\node_modules\jju\lib\parse.js:745:13)
1915 verbose stack     at parse (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-helpfulerror\index.js:10:13)
1915 verbose stack     at consumeBody.call.then.buffer (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
1915 verbose stack     at <anonymous>
1915 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
1916 verbose cwd E:\tabsettest
1917 verbose Windows_NT 10.0.15063
1918 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1919 verbose node v8.4.0
1920 verbose npm  v5.3.0
1921 error Unexpected end of input at 1:452698
1921 error bpack.js"},"directories":{},"dist":{"shasum":"7bb1d72ae2087dd1a4af526
1921 error                                                                      ^
1922 verbose exit [ 1, true ]

![tim 20170818160600](https://user-images.githubusercontent.com/9586655/29449937-46aecf44-842f-11e7-8ce4-c7eaa2a28d76.png)

**Comment by wanghaolu** [comment]
clear npm cache and reinstall solve the problem.

**Comment by nirav4273** [comment]
i tried 
npm clear cache
uninstall angular-cli globally & re-install still showing this issue.


OP: ng -v
@angular/cli: 1.3.2
node: 6.11.2
os: win32 x64
@angular/animations: error
@angular/common: error
@angular/compiler: error
@angular/core: error
@angular/forms: error
@angular/http: error
@angular/material: error
@angular/platform-browser: er
@angular/platform-browser-dyn
@angular/router: error
@angular/cli: error
@angular/compiler-cli: error

>Same issue when try to create ng new ***.
