### ISSUE TITLE
Feature Request: Allow @NgModule to dictate common html templates & common component code through it's Declarations

### ISSUE THREAD

**Issue by Jonathan002** [angular/angular-cli#7423]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Versions.
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
macOS (Sierra)

node: 8.1.2
os: darwin x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/compiler-cli: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/platform-server: 4.2.6
@angular/router: 4.2.6
@angular/tsc-wrapped: 4.2.6
@angular/upgrade: 4.2.6

### Desired functionality.
What would like to see implemented?
I would like @NgModules to be able provide **Declared** components a common html template and common component code template. By adding an object to the **declarations** array, I hope to link up the components to common code template files as shown below:

e.g. someModule.module.ts
```typescript
@NgModule({
  declarations: [
         {
            'html-template': 'some-template-file.html',
            'code-template': 'some-component-template-file.ts',
            'declaration-list-to-apply': [
                     HomeComponent,
                     SomeOtherComponent,
            ]
         },
        RegularComponentWithNoTemplate,
        {}, //adding different templates to these components etc
  ]
})
```

e.g. some-template-file.html

```html
<template-top>
     <!-- add common html code here like header/logo components -->
</template-top>

<!-- specific template code written by the component itself -->

<template-bottom>
      <!-- add common html code here but for bottom of components -->
</template-bottom>
```

e.g. some-component-template-file.ts

```typescript
// common decorator code 
// e.g. add the same animation to all components
@Component({
      animations: [fadeAnimation],
      host: {
           '[@fadeAnimationTrigger]' = 'state' 
      }
})

// common component code 
// e.g. do something OnInit to all components
export commonComponent implements OnInit {
       ngOnInit() {
            //do something repetative... 
      }
}
```

What is the usecase?
The use would be to make development time faster by allowing faster implementation of common code between comonents.

**Comment by clydin** [comment]
Class inheritance and/or component/directive composition should cover your use case.  Both offer the ability to abstract common functionally.

**Comment by hansl** [comment]
This is obviously a feature request for Angular itself, and we (the Angular CLI team) have no control over Angular Core features.

Please file a request to http://github.com/angular/angular. Thanks.
