### ISSUE TITLE
[1.3.*] Types of parameters '__0' and 'value' are incompatible.

### ISSUE THREAD

**Issue by karser** [angular/angular-cli#7428]
### Bug Report
```
- [x] bug report
- [ ] feature request
```

### Versions.
```
@typescript: 2.4.2
@rxjs: 5.4.3
@angular/cli: 1.3.1
node: 8.0.0
os: linux x64
@angular/animations: 4.3.4
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.4
```

### Repro steps.
```
    let s: string = 'abc',
        b: boolean = true,
        n: number = 10;

    Observable.forkJoin([Observable.of(s), Observable.of(b), Observable.of(n)])
        .map(([s, b, n]: [string, boolean, number]) => s);
```

### The log given by the failure.
```
ERROR in file.ts (6,18): Argument of type '([s, b, n]: [string, boolean, number]) => string' is not assignable to parameter of type '(value: boolean[], index: number) => string'.
  Types of parameters '__0' and 'value' are incompatible.
    Type 'boolean[]' is not assignable to type '[string, boolean, number]'.
      Property '0' is missing in type 'boolean[]'.
```

### Desired functionality.
This code gets compiled on v1.2.7 but fails on v1.3.*

**Comment by clydin** [comment]
That's not an Angular-CLI issue.  TS 2.4 has more comprehensive type checking.  The forkJoin method's signature for the array overload doesn't work with a multi-type array.  The array is not actually needed anyway; there's an overload that handles the observables directly.  You can also manually specify the generic type argument for forkJoin.

**Comment by karser** [comment]
@clydin Could you please provide some reference that `forkJoin doesn't work with a multi-type array in TS 2.4`? Is it by design? What would be a solution in this case?
In [this example](https://www.learnrxjs.io/operators/combination/forkjoin.html) forkJoin accepts observables of multiple types.
I removed all the type casts in my example but I'm getting `ERROR in file.ts (5,38): Argument of type 'string' is not assignable to parameter of type 'number'.`:
```
let s: string = 'abc',
    n: number = 10;

Observable.forkJoin([Observable.of(s), Observable.of(n)])
    .map(responses => takesB(responses[1]));

function takesB(n: number) {
}
```

**Comment by clydin** [comment]
As I mentioned, you can remove the usage of the array.  The example that you linked doesn't use the array overload of forkJoin with observables of different types.  The array example (second one), uses an array of only numbers.  Also, in the code shown above, `responses` has an inferred type of `string[]` which is way it is failing.
Two other options are to either manually define the generic type parameter on forkJoin or cast the array parameter as `any[]`.

**Comment by karser** [comment]
Thanks @clydin. There are 3 working examples that get compiled under angular-cli 1.3.1 and TS 2.4:

1. cast the array parameter as any[]
```
Observable.forkJoin([Observable.of(s), Observable.of(n)])
    .map(([s, n]: any[]) => s);
```

2. surprisingly, I found out that if I pass observables into forkJoin not as an array but as a function arguments, the error disappears, so my original example works:
```
Observable.forkJoin(Observable.of(s), Observable.of(n))
    .map(([s, n]: [string, number]) => s);
```

3. manually define the generic type parameter on forkJoin.
```
Observable.forkJoin<string,number>(Observable.of(s), Observable.of(n))
    .map(([s, n]) => s);
```

**Comment by Brocco** [comment]
Closing as there seems to be work-arounds and that this is a typing issue, not a CLI issue. Thanks @clydin
