### ISSUE TITLE
[schematics] ng generate aliases don't work anymore

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#7438]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.0-beta.2
node: 8.3.0
os: darwin x64

### Repro steps.
ng new hello
ng g c hello

### The log given by the failure.
```
Schematic "c" not found in collection "@schematics/angular".
Error: Schematic "c" not found in collection "@schematics/angular".
    at SchematicEngine.createSchematic (/Users/cedric/Code/tests/schematics-alias/hello/node_modules/@angular-devkit/schematics/src/engine/engine.js:65:19)
```

### Desired functionality.
The aliases should work as they used to before the migration to schematics.
`ng g component hello` still work.

### Mention any other details that might be useful.
Other aliases are lost too (m for module, d for directive...).
I can open the issue on `angular/dev-kit` if it's a better place...

**Comment by BenRacicot** [comment]
`ng g component` worked however it created a .css file when my config is set for .scss. What is going on?!

**Comment by Brocco** [comment]
@BenRacicot Can you please an issue for this... and please include your `.angular-cli.json`.

**Comment by Brocco** [comment]
@cexbrayat I have a PR for this in devkit. angular/devkit#114

**Comment by BenRacicot** [comment]
@Brocco thanks for responding. However, the issue has vanished since yesterday... I cannot repro this behavior and both `ng g c ` and ng g component ` create the files... Would you still like me to create a separate issue with my cli.json?

**Comment by Brocco** [comment]
@BenRacicot What I'm concerned with from you is the `styleExt` in `.angular-cli.json` not being used when generating a new component.

**Comment by BenRacicot** [comment]
@Brocco Understood. It is 
`"defaults": {
        "styleExt": "scss"
}` Any other ways I can help?

**Comment by blcktqq** [comment]
Good day! I`m having same issue.
```
Angular CLI: 1.6.3
Node: 9.7.1
OS: win32 x64
Angular: 5.1.2 
```

```
Schematic "сomponent" not found in collection "@schematics/angular".
Error: Schematic "сomponent" not found in collection "@schematics/angular".

```
