### ISSUE TITLE
[Enhancement] Improve code modification when generating new routes

### ISSUE THREAD

**Issue by thorstenschaefer** [angular/angular-cli#744]
When we generate a new route, it gets automatically added to the main component, which is great. The import statement of our new component is getting placed directly after the first block of import statements. According to the official style guide, we should first import all the angular dependencies, and then in a second block, separated by an empty line, our own application dependencies (see Style 03-06 in https://angular.io/docs/ts/latest/guide/style-guide.html#!#coding-conventions).

**Comment by phillipgreenii** [comment]
Is this a duplicate of #579?

**Comment by thorstenschaefer** [comment]
@phillipgreenii Yes, sorry, didn't see the existing issue.
