### ISSUE TITLE
Where is systemjs.config.js?

### ISSUE THREAD

**Issue by zalayeto** [angular/angular-cli#7441]
Angular tutorial talks about the module loader after creating a basic application but this file is not anywhere,

Why is that? how does the module work with an application created with angular-cli?

EDITED: I can see by inspecting the page that is using webpack instead of systemjs? What should I use?

Thanks.

**Comment by ankeshdave** [comment]
@zalyeto 
For angular u should use angular-cli to create the default boiler plate, this will provide you with a complete solution for bundler/loader ➕ dev/prod bundle generator plus ➕ test rig setup ➕ scaffolding using angular cli. 

Have a look at Readme for more info.

**Comment by hansl** [comment]
If you're using the Angular CLI, you should not need a systemjs.config.js. Everything is taken care of by the CLI. You really shouldn't even need to configure or think about your build or amd. The CLI takes care of that for you.

If you have questions regarding the tutorial itself, you need to ask on stackoverflow or the main repo where documentation questions are (https://github.com/angular/angular).
