### ISSUE TITLE
ERROR [preprocess]: Can not load "webpack"!   TypeError: Cannot read property 'plugin' of undefined

### ISSUE THREAD

**Issue by ravidannani** [angular/angular-cli#7443]
After installing angular cli, I ran the below commands and able to open the application on browser.
ng new my-dream-app
cd my-dream-app
ng serve

But inorder to do testing, executed ng test command, but getting the below issue. Not sure how to proceed further. 

![image](https://user-images.githubusercontent.com/27359086/29490757-a3efac2a-84fa-11e7-8bb4-48fece30e049.png)

Could you please let me know if i did any mistake.

**Comment by ebuychance** [comment]
I ran into this same issue. I was able to add 
```
"@ngtools/webpack": "^1.6.2"
```
to the devDependencies as a fix for a newly generated project but this temp fix did not work with another recently created app I developed. 
I read about adding a tsconfig.spec.ts as a fix as well here: https://github.com/angular/angular-cli/issues/6457

Currently still unable to fix my issue.

**Comment by amrography** [comment]
+1

**Comment by ebuychance** [comment]
```
ng -v
angular-cli: 1.0.0-beta.28.3
node: 8.3.0
os: win32 x64
```

Upgrading to @angular/cli: 1.3.2 solved my issues.

**Comment by Brocco** [comment]
It appears you have a much older version of the CLI (still using the package name `angular-cli`)

You will want to remove that package and install the current version...

```bash
npm uninstall angular-cli -g
npm install @angular/cli -g
```

Also, you'll want to ensure your versions are up to date, which you can find under [prerequisites](https://github.com/angular/angular-cli#prerequisites)

**Comment by uglycoyote** [comment]
I got burned by this as well.  I did see the message when running `ng test` which said

> As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,

However, I read this as a forewarning about something that would happen in the future, where I should have read it as something which was in the near-future of the long-ago-past, which means it's still in the past from where the present currently is.

It would have been better if whoever typed the "forewarning" instead said something like "As of __DATE__, the angular-cli repository is deprecated and you should be using @angular/cli"
