### ISSUE TITLE
Installation error on ubuntu 17.X

### ISSUE THREAD

**Issue by shameerariff** [angular/angular-cli#7444]
I am getting the following error while installing angularjs cli 

/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

the node and npm are up to date.
 but still I am getting the same error

**Comment by Ionaru** [comment]
This is a warning, not an error. You don't need fsevents in Linux.

**Comment by Brocco** [comment]
Correct, warnings are not errors. If you're having issues after installation, please open another issue.
