### ISSUE TITLE
placeholder font size mismatch between mdinput and ndselect elements

### ISSUE THREAD

**Issue by Masber** [angular/angular-cli#7446]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.1
node: 7.9.0
os: win32 x64
@angular/animations: 4.3.5
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5

### Repro steps.

just to have something like this in a template file:

<md-grid-tile>
          <md-select name="shipper" placeholder="Please choose shipper"
                     formControlName="shipper" multiple>
            <md-option *ngFor="let shipper of shippers" [value]="shipper.id">
              {{ shipper.firstName }}
            </md-option>
          </md-select>
        </md-grid-tile>

        <md-grid-tile>
          <md-input-container>
            <input mdInput name="salesOrder" placeholder="Sales Order" autocomplete="off"
                   formControlName="salesOrder">

            <md-error *ngIf="formErrors.salesOrder">
              {{ formErrors.salesOrder }}
            </md-error>
          </md-input-container>
        </md-grid-tile>

### The log given by the failure.

N/A

### Desired functionality.

I would like to see same font size for mdinput and mdselect placeholders

### Mention any other details that might be useful.

N/A

**Comment by grizzm0** [comment]
Pretty sure you submitted this on the wrong repo. ;)

**Comment by hansl** [comment]
Closing by @grizzm0's answer.
