### ISSUE TITLE
ng build -prod breaks char encoding

### ISSUE THREAD

**Issue by I3uddy** [angular/angular-cli#7450]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.1
node: 6.10.3
os: win32 x64

### Repro steps.

enter this string into a .ts file
"© 1990-2017 All rights reserved"
run ng build -prod -aot
search for this string in the resulting main.bundle.js
notice the © char has been encoded as /xa9

### Desired functionality.

build and minify should keep character set 

### Mention any other details that might be useful.

this only appears to be an issue from 1.30 onwards. Was OK at version 1.2.8

**Comment by I3uddy** [comment]
Additional info: when i run the same build on version 1.2.8, the  © char is encoded as \u00A9

**Comment by alan-agius4** [comment]
Closing as character encoding should not have any negative impact.

In the case it does have a negative impact please feel free to re-open the issue and explain the use case.
