### ISSUE TITLE
Provide a Docker image

### ISSUE THREAD

**Issue by mackelito** [angular/angular-cli#7454]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Mention any other details that might be useful.

RIght now we run https://hub.docker.com/r/alexsuch/angular-cli and that works but it would feel alot "safer" if there was an official image to use :)

**Comment by Brocco** [comment]
There is a design doc already for adding docker support.

https://github.com/angular/angular-cli/blob/efcb8d24942a677f37e6bdd16fcc575c51998aa8/docs/design/docker-deploy.md

You are very vague in what you're requesting. When defining a requirement it would be helpful to provide information about what you're hoping to gain from this feature.

- Is this a deployment target?
- Is this an image that will contain the CLI for development?

Also, supporting docker (in any capacity) feels like a project outside of the CLI.

**Comment by mackelito** [comment]
AH.. great! will take a look at that docs.. was looking for a image to use on our prod server :)

**Comment by Splaktar** [comment]
@mackelito you certainly don't want to run `ng serve` on your prod server :) You may want to look into an nginx image to use for hosting Angular apps in production mode.

**Comment by mackelito** [comment]
haha.. no need to worry! ;) We got it covered.. running nginx as load balancers and then just serving the complied files.. but we do have the build step and need the cli.
