### ISSUE TITLE
4-10 second delay between constructor and NgInit()

### ISSUE THREAD

**Issue by kkotak** [angular/angular-cli#7460]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.0
node: 6.9.5
os: darwin x64
@angular/animations: 4.3.4
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/compiler-cli: 4.3.4
@angular/core: 4.3.4
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/platform-server: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.3.0
@ngtools/webpack: 1.6.0

### Repro steps.

Production code is built using the following command - 
node --max_old_space_size=8192 ./node_modules/.bin/ng build --aot --prod

Th initial load of the module happens quickly but, when navigated to a route, the constructor of the destination component is also called in a timely manner, but the ngOnInit() method is not called for another 4-10 seconds. This happens every time and with not just one but all components that are called using navigation.

### The log given by the failure.

NA

### Desired functionality.

I'd like to understand the reason and resolution for the delay.

### Mention any other details that might be useful.

Additional information that might help is that this behavior started when I upgraded Angular from 4.0.1 to 4.3.4

**Comment by CaerusKaru** [comment]
Is this a problem specifically with the cli, or is this more of an Angular performance question? If it's the latter, you might want to submit this issue [here](https://github.com/angular/angular/issues) instead

**Comment by kkotak** [comment]
Apologies. I have submitted the issue [here](https://github.com/angular/angular/issues/18816). Thanks.
