### ISSUE TITLE
Cannot get final name for export "some-component" in "some-module"

### ISSUE THREAD

**Issue by bthharper** [angular/angular-cli#7463]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.0
node: 7.4.0
os: win32 x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5

### Repro steps.

Create a project
Add a component with some additional exports in the same file.
run `ng b --prod`

### The log given by the failure.

Error : Cannot get final name for export "ToggleRowEvent"../node_modules/@controls/grids/grid.component.ts" (known exports: ColumnFilterTypes true, known reexports:)

### Desired functionality.

It compiles.

### Mention any other details that might be useful.

The problem looks to be caused by a webpack issue, see https://github.com/webpack/webpack/issues/5508 where they recommend that the angular cli is updated to use the latest webpack.

**Comment by roben** [comment]
Did you find any way to work around this?

**Comment by bthharper** [comment]
@roben Move the non component exports into different files - this worked I believe.

**Comment by roben** [comment]
Thanks, I just reverted angular-cli to 1.2.x for now.

**Comment by andreimcristof** [comment]
@roben  thank you for the workaround.

**Comment by Brocco** [comment]
Can you please provide more information? It looks like this is a result of a 3rd party library based upon the information you've provided.

Does it happen just when you have some additional exports without any other libs added?

**Comment by roben** [comment]
Did you check the webpack issue? I think it is already fixed there.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
