### ISSUE TITLE
Angular CLI Eclipse "Cannot find module './foo' " warning. Code works fine

### ISSUE THREAD

**Issue by mugrufis** [angular/angular-cli#7464]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.1.0
node: 7.10.0
os: darwin x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.1.0
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5

### Desired functionality.
Hi there, I have created a couple of test projects on Eclipse using the Angular CLI. When I manually import a "class" (the following doesn't happen when the import is done using the content assistant),
everything works fine, except a persisting error inside the file saying "Cannot find module './foo' ".

It actually does find it since the code compiles and runs perfectly, but the error is a bit annoying on top. Note, that on the file tree the error is not visible, only when a file is open, from inside the file.

**Comment by hansl** [comment]
Do you have a project that we could use to reproduce this?

**Comment by mugrufis** [comment]
Here you can find the src folder, from the erroneous "project". 

[code](https://github.com/mugrufis/angularCLI)

To also clarify the problem, the `import { RoutingModule } from './routes/routing-module'` as seen on the screenshot has this error: `Cannot find module './routes/routing-module'.` But apparently this is not the case since my apps routing works fine.

![bildschirmfoto 2017-08-23 um 09 13 01](https://user-images.githubusercontent.com/22847016/29603463-8474523c-87e4-11e7-8f5d-919ec8135cde.png)

A couple more snapshots:

![bildschirmfoto 2017-08-23 um 09 25 31](https://user-images.githubusercontent.com/22847016/29603642-2d8554ac-87e5-11e7-8d0a-66640fd81f85.png)

![bildschirmfoto 2017-08-23 um 09 25 59](https://user-images.githubusercontent.com/22847016/29603647-322793f8-87e5-11e7-91ee-15695670a618.png)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
