### ISSUE TITLE
blog.angular.io Link wrong in app.component.html

### ISSUE THREAD

**Issue by dags** [angular/angular-cli#7468]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.3.1
node: 8.2.1
os: linux x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5

### Repro steps.
1) generate a new project
2) run it
3) click on "Angular blog" link on home page.

### The log given by the failure.
404 We couldn’t find this page.

### Desired functionality.
Link should open Angular Blog page in another window

**Comment by devoto13** [comment]
It was already fixed in master. See https://github.com/angular/devkit/commit/291e9a94ecbcc1bc98dce9bad9780a18ff32fc28

**Comment by Brocco** [comment]
@devoto13 is correct, this issue has been resolved. Thanks!
