### ISSUE TITLE
Bootstrap error: SyntaxError: export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular-cli#7472]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

After upgrading angular cli, I am seeing an error which is coming from the use of Bootstrap 4 beta. This error was not there before. 

### Versions.
```
portfolio$ ng -v
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.3.1
node: 8.3.0
os: darwin x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5
```
### Repro steps.
Create a project using bootstrap 4 beta and run it and look at the console in the browser debugger.

Here is a app using including bootstrap: 
https://github.com/rajinder-yadav/angular-bootstrap4-beta-error

### The log given by the failure.

```
SyntaxError: export declarations may only appear at top level of a module  scripts.bundle.js:4:20837
	../../../../script-loader/addScript.js/module.exports http://localhost:4200/scripts.bundle.js:49:3
	../../../../script-loader/index.js!../../../../popper.js/dist/popper.min.js http://localhost:4200/scripts.bundle.js:72:1
	__webpack_require__ http://localhost:4200/inline.bundle.js:55:12
	[2] http://localhost:4200/scripts.bundle.js:96:1
	__webpack_require__ http://localhost:4200/inline.bundle.js:55:12
	webpackJsonpCallback http://localhost:4200/inline.bundle.js:26:23
	<anonymous>
```

### Desired functionality.
Should not see the SyntaxError above.

### Mention any other details that might be useful.

From the console error output, When I click on ' scripts.bundle.js:4:20837', I am taken to the following line.

```js
webpackJsonp(["scripts"],{

/***/ "../../../../raw-loader/index.js!../../../../bootstrap/dist/js/bootstrap.min.js":
/***/ (function(module, exports) {
```

**Comment by rajinder-yadav** [comment]
This also happens with bootstrap 4 alpha, which didn't happen before and I believe it also breaking the code so that some of the data driven javascript no longer works.

**Comment by rajinder-yadav** [comment]
Hi I tracked down the problem, not an issue with angular cli, closing!

**Comment by chris13524** [comment]
How'd you fix it? I'm getting this error too.

**Comment by Extarys** [comment]
I'm getting this from regular bootstrap XD - it's from popperJS not from angular, sorry guys

**Comment by ondra-cenek** [comment]
Use popper javascript files in folder umd.

**Comment by MisterY** [comment]
@rajinder-yadav, of course you are not obliged to but, having already "tracked down the problem" and writing the response here, you probably could have taken a couple more seconds to add a hint towards the solution. Fortunately, the brief hint by @ondra-cenek, helps others to solve this by referencing the `dist/umd/popper.js` (or a minified version) instead of the popper.js from the default package directory.
