### ISSUE TITLE
@ngtools/webpack TS Error on build of project

### ISSUE THREAD

**Issue by timwright35** [angular/angular-cli#7474]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Node 8.1.0
NPM 5.0.3
ngtools/webpack 1.7.0-beta.2
Angular 5.0.0-beta.2
Typescript 2.4.2

### The log given by the failure.
TS2420: Class 'VirtualStats' incorrectly implements interface 'Stats'.
  Property 'atimeMs' is missing in type 'VirtualStats'.

### Desired functionality.
Compiles correctly

**Comment by andrewpmontgomery** [comment]
I have the same problem.
It only happens with `awesome-typescript-loader`.
Switching to `ts-loader` resolved the problem for me.

**Comment by Tempus35** [comment]
I just tried changing to ts-loader, same error. Care to share your part of the config that you have setup, see if I am doing it right.

**Comment by MartinJK** [comment]
Temporary solved it by adding the following attributed from fs.Stats to the VirtualStats class
`  readonly atimeMs: number;
  readonly mtimeMs: number;
  readonly ctimeMs: number;
  readonly birthtimeMs: number;`

Seems like the node api changed..

Using: 
- node 8.1.3
- npm 5.2.0
- @types/node 8.0.25
- @ngtools/webpack 1.6.2

**Comment by dogmatico** [comment]
Downgrading to `@types/node` 8.0.19 temporary solved the problem.

**Comment by stemda** [comment]
Unfortunately still an issue. :(

**Comment by DanielSchaffer** [comment]
You can work around this by adding the following to a `.d.ts` file, and making sure that file is included in your `tsconfig.json`:

```
// https://github.com/angular/angular-cli/issues/7474
import { VirtualStats } from '@ngtools/webpack/src/compiler_host';
import * as fs from 'fs';

declare module '@ngtools/webpack/src/compiler_host' {
    interface VirtualStats extends fs.Stats {
        atimeMs: number;
    }
}
```

**Comment by mgechev** [comment]
Can you still reproduce this error?

**Comment by mgechev** [comment]
Closing the issue due to inactivity. If the problem still exists in the latest version of the CLI, please open a new issue following the template and providing a minimal demo where we can reproduce it. Thanks! :-)
