### ISSUE TITLE
`ng lint` option format not work properly if using alias

### ISSUE THREAD

**Issue by 3lly3fendi** [angular/angular-cli#7478]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
λ ng --version
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.3.1
node: 8.4.0
os: linux x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5
```

λ node --version
```
v8.4.0
```

λ node --version
```
5.3.0
```

Running on Windows 7

### Repro steps.
1. run `ng new abc`
2. remove some semicolon from code (app.component.ts)
3. run `ng lint -t=stylish`

### The log given by the failure.
```

ERROR: /home/nodejs/abc/src/app/app.component.ts[10, 14]: Missing semicolon

Lint errors found in the listed files.
```

### Desired functionality.
it should be produce same output with command `ng lint --format=stylish`
```
Warning: The 'no-use-before-declare' rule requires type information.
/home/nodejs/abc/src/app/app.component.ts
ERROR: 10:14  semicolon  Missing semicolon

Lint errors found in the listed files.
```

### Mention any other details that might be useful.
here my pull requests [#7466](https://github.com/angular/angular-cli/pull/7466)

**Comment by 3lly3fendi** [comment]
Close this issue, pull request already merged.
Thank you @hansl

**Comment by sam-s4s** [comment]
Hi :)

So I'm trying to use --format and it's just not working for me...

I've tried the following (all completely ignore the format):

```
npm run ng lint --format verbose
npm run ng lint -t verbose
npm run ng lint --format=verbose
npm run ng lint -t=verbose
```

I am unable to install the cli globally, hence the need to `npm run ng lint` instead of just `ng lint`. I hope this doesn't make it impossible for some silly reason? :)
