### ISSUE TITLE
Missing doc about ng build with --build-optimizer

### ISSUE THREAD

**Issue by yokots** [angular/angular-cli#7479]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

macOS Sierra 10.12.6
- node: 8.4.0
- npm: 5.3.0
- angular-cli: 1.3.1

When use ng build with --prod and --build-optimizer flag, it can not separate vendor chunk from the main chunk, it must use --vendor-chunk explicitly. But this build bigger chunk.
![1](https://raw.githubusercontent.com/yokots/images/master/angular-cli-issue-1.png)
![2](https://raw.githubusercontent.com/yokots/images/master/angular-cli-issue-2.png)

**Comment by clydin** [comment]
Disabling the vendor chunk is intentional as it allows further optimization.  The example above demonstrates the benefit (~200KB saved).

**Comment by yokots** [comment]
@clydin Thank you!  Please update the doc as soon as possible to explain this.

**Comment by frostbtn** [comment]
While we are at it. Wiki on [build switch](https://github.com/angular/angular-cli/wiki/build) shows `-bo` is a valid alias, when as of `1.3.2` the only valid alias is `--buildOptimizer`.

**Comment by Brocco** [comment]
Closing this issue...

@frostbtn FYI, that issue has been addressed in master and will be updated in the next release of the docs to the wiki.

**Comment by johnpapa** [comment]
It has been added to the wiki here https://github.com/angular/angular-cli/wiki/build#options
