### ISSUE TITLE
perf(mobile): service worker should only receive tree of static assets + bundled JS

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular-cli#748]
The current behavior of the service worker script is to automatically pre-fetch+cache all files in the Broccoli tree it's provided. Right now, it's receiving pretty much all library and app js files, 1-by-1, in addition to the bundle. So it's pre-fetching lots of files that are not actually needed in production mode.

**Comment by sgbeal** [comment]
fwiw, that's almost 300 requests in the ng-generated hello world app and over 600 once one adds 30-40 of his own classes.

**Comment by filipesilva** [comment]
Fixed in #1455.
