### ISSUE TITLE
angular/cli #npm #angular

### ISSUE THREAD

**Issue by muhagad** [angular/angular-cli#7484]
$ npm install -g @angular/cli

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yargs@7.1.0 (node_modules\@angular\cli\node_modules\yargs):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxx\AppData\Roaming\npm\                   node_modules\.staging\yargs-a6f4d6c6\CHANGELOG.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: tar@2.2.1 (node_modules\@angular\cli\node_modules\tar):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxx\AppData\Roaming\npm\                   node_modules\.staging\tar-f940e886\test\cb-never-called-1.0.1.tgz'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-gyp@3.6.2 (node_modules\@angular\cli\node_modules\node-gyp):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxx\AppData\Roaming\npm\                   node_modules\.staging\node-gyp-ab19f1fc\README.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: stream-http@2.7.2 (node_modules\@angular\cli\node_modules\stream-http):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxx\AppData\Roaming\npm\                   node_modules\.staging\stream-http-449b5250\test\server\static\browserify.png'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yargs@8.0.2 (node_modules\@angular\cli\node_modules\webpack\node_modules\yarg                   s):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxx\AppData\Roaming\npm\                   node_modules\.staging\yargs-24c9e910\locales\tr.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gaze@1.1.2 (node_modules\@angular\cli\node_modules\gaze):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxx\AppData\Roaming\npm\                   node_modules\.staging\gaze-8a8fd82d\lib\gaze.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xmldom@0.1.27 (node_modules\@angular\cli\node_modules\xmldom):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxx\AppData\Roaming\npm\                   node_modules\.staging\xmldom-12d93551\dom.js'

npm ERR! code EINTEGRITY
npm ERR! sha512-vOk6uEMctu0vQrvuSqFdJyqj1Q0S5VTDL79qtjo+DhRr+1mmaD+tluFSCZqhvi/JUhXSzoZN2BhtstaPEeE8cw== integrity checksum f                   ailed when using sha512: wanted sha512-vOk6uEMctu0vQrvuSqFdJyqj1Q0S5VTDL79qtjo+DhRr+1mmaD+tluFSCZqhvi/JUhXSzoZN2BhtstaPEeE8cw                   == but got sha512-pd+s9UiGqI1iFyuo9HnBrpGNNOE1o0VThHvIcRX0ECoMjQkINlVoPG4MNzp4eyTVcvRieTaIEt35aB5PCU+NuA==. (2233 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxxxx\AppData\Roaming\npm-cache\_logs\2017-08-23T18_21_51_749Z-debug.log

node -v
v8.4.0

npm -v
5.3.0

please help

**Comment by hansl** [comment]
We do not know why this happens, but it seems some people on Windows have trouble installing when they don't use an administrative prompt. Try cleaning your cache and reinstalling, and if that doesn't work reinstall the CLI with an administrative prompt.

Thanks.

**Comment by muhagad** [comment]
thanks @hansl it didn't work for me but i downloaded a LTS of node.js npm version and now it works just fine

**Comment by connect2satyam** [comment]
LTS of node.js npm version worked for me , thanks @muhagad
