### ISSUE TITLE
[1.4.0-rc.0] ng new error

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#7492]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.0-rc.0
node: 8.4.0
os: darwin x64

### Repro steps.
```
ng new hello
```

### The log given by the failure.
```
Error: Path "hello/src/" is invalid.
Path "hello/src/" is invalid.
```

**Comment by AlainD-** [comment]
Reproduced on Windows too.

my environment: nvm: node 8.4.0, angular CLI 1.4.0-rc.0

**Comment by AlainD-** [comment]
I tried with node 7.10.1, and same problem occurs, so it is not a problem from node, but really from the new (next) version of angular CLI

**Comment by AlainD-** [comment]
I did a new test, `ng new` with 1.4.0-beta.2 just works fine. So it is really something introduced in the -rc.0

**Comment by AlainD-** [comment]
I was trying to find a workaround, but without any success. For info, none of the following commands work neither:

```bash
ng new hello --dry-run
```

```bash
mkdir hello
ng new hello --directory=hello
```

=> same error is displayed

**Comment by cexbrayat** [comment]
The new release of `@schematics/angular` (0.0.30) seems to fix the problem for me, `ng new` no longer errors with `1.4.0-rc.0`

**Comment by AlainD-** [comment]
Thank you.
Re-installing 1.4.0-rc.0, now, fixes the issue indeed :-)
