### ISSUE TITLE
Error on installing CLI on AIX 7.1

### ISSUE THREAD

**Issue by a4amitava** [angular/angular-cli#7494]
**Getting below 404 error and other errors while installing CLI on AIX . I am not behind any proxy . The 404 URL also not available . Please help !**

acle@ttwdfd> npm install -g @angular/cli
/app/ng2/node/bin/ng -> /app/ng2/node/lib/node_modules/@angular/cli/bin/ng

> node-sass@4.5.3 install /app/ng2/node/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/aix-ppc64-48_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/aix-ppc64-48_binding.node":
> 
> HTTP error 404 Not Found
> 
> Hint: If github.com is not accessible in your location
>       try setting a proxy via HTTP_PROXY, e.g.
> 
>       export HTTP_PROXY=http://example.com:1234
> 
> or configure npm proxy via
> 
>       npm config set proxy http://example.com:8080
> 
> > node-sass@4.5.3 postinstall /app/ng2/node/lib/node_modules/@angular/cli/node_modules/node-sass
> > node scripts/build.js
> 
> Building: /app/ng2/node/bin/node /app/ng2/node/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
> gyp info it worked if it ends with ok
> gyp verb cli [ '/app/ng2/node/bin/node',
> gyp verb cli   '/app/ng2/node/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js',
> gyp verb cli   'rebuild',
> gyp verb cli   '--verbose',
> gyp verb cli   '--libsass_ext=',
> gyp verb cli   '--libsass_cflags=',
> gyp verb cli   '--libsass_ldflags=',
> gyp verb cli   '--libsass_library=' ]
> gyp info using node-gyp@3.6.2
> gyp info using node@6.10.1 | aix | ppc64
> gyp verb command rebuild []
> gyp verb command clean []
> gyp verb clean removing "build" directory
> gyp verb command configure []
> gyp verb check python checking for Python executable "python2" in the PATH
> gyp verb `which` succeeded python2 /usr/bin/python2
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: /usr/bin/python2 -c import platform; print(platform.python_version());
> gyp ERR! stack Traceback (most recent call last):
> gyp ERR! stack   File "/usr/bin/../../opt/freeware/lib/python2.7/site.py", line 548, in <module>
> gyp ERR! stack     main()
> gyp ERR! stack   File "/usr/bin/../../opt/freeware/lib/python2.7/site.py", line 530, in main
> gyp ERR! stack     known_paths = addusersitepackages(known_paths)
> gyp ERR! stack   File "/usr/bin/../../opt/freeware/lib/python2.7/site.py", line 266, in addusersitepackages
> gyp ERR! stack     user_site = getusersitepackages()
> gyp ERR! stack   File "/usr/bin/../../opt/freeware/lib/python2.7/site.py", line 241, in getusersitepackages
> gyp ERR! stack     user_base = getuserbase() # this will also set USER_BASE
> gyp ERR! stack   File "/usr/bin/../../opt/freeware/lib/python2.7/site.py", line 231, in getuserbase
> gyp ERR! stack     USER_BASE = get_config_var('userbase')
> gyp ERR! stack   File "/opt/freeware/lib/python2.7/sysconfig.py", line 521, in get_config_var
> gyp ERR! stack     return get_config_vars().get(name)
> gyp ERR! stack   File "/opt/freeware/lib/python2.7/sysconfig.py", line 473, in get_config_vars
> gyp ERR! stack     _init_posix(_CONFIG_VARS)
> gyp ERR! stack   File "/opt/freeware/lib/python2.7/sysconfig.py", line 357, in _init_posix
> gyp ERR! stack     from _sysconfigdata import build_time_vars
> gyp ERR! stack ImportError: No module named _sysconfigdata
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:12)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
> gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:342:11)
> gyp ERR! stack     at emitOne (events.js:96:13)
> gyp ERR! stack     at Socket.emit (events.js:188:7)
> gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:501:12)
> gyp ERR! System AIX 7.1
> gyp ERR! command "/app/ng2/node/bin/node" "/app/ng2/node/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd /app/ng2/node/lib/node_modules/@angular/cli/node_modules/node-sass
> gyp ERR! node -v v6.10.1
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> Build failed with error code: 1
> /app/ng2/node/lib
> `-- @angular/cli@1.3.2
>   `-- UNMET OPTIONAL DEPENDENCY node-sass@^4.3.0
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@angular/cli/node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"aix","arch":"ppc64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 (node_modules/@angular/cli/node_modules/node-sass):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 postinstall: `node scripts/build.js`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
>

**Comment by filipesilva** [comment]
Heya, that error means that an optional dependency (https://github.com/sass/node-sass) does not support your system. It's optional so that means that the CLI should still work, but you won't have SASS/SCSS support. 

You can ask in their issue tracker to support your system.
