### ISSUE TITLE
feature request: add a cleaner skip test option

### ISSUE THREAD

**Issue by zh99998** [angular/angular-cli#7495]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

currently there is a `--skip-test` option to avoid generating spec files and a `--minimal` option to disable all unnecessary features.

but there isn't a proper way to turn off test feature.
if I want to create a project just without test, I have to:
```
1. create a project with --minimal
2. add .editorconfig, tslint.json, 
3. add tslint, codelyzer to devDependencies in package.json
4. delete inline style and inline template in angular-cli.json
5. git init
```
or
```
1. create a project with --skip-test
2. delete test related scripts from package.json
3. delete test related devDependencies from package.json
4. add many "spec": false to .angular-cli.json
```

both of them are complicated, all I want is just don't need test.

request to add a option to disable all test related features but keep other.

**Comment by Brocco** [comment]
The options and abilities of the engine that generates files has recently been updated (see PR #7090) which will allow you to define your own structure/options.

Documentation for this will be coming with examples.
