### ISSUE TITLE
ng serve - AOT Type Error in HTML Template

### ISSUE THREAD

**Issue by Bidthedog** [angular/angular-cli#7496]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

$ ng --version
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.3.0
node: 6.9.4
os: win32 x64
@angular/animations: 4.3.2
@angular/cli: 1.3.0
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/compiler-cli: 4.3.2

```
### Repro steps.

This is a private project so I can't provide all the source code.

I turned on AOT and fixed a truck-load of new errors. All were fairly self explanatory, but there is one I cannot debug / fix as the line referenced in the error doesn't seem to relate.

Unaltered, problematic code in this gist - https://gist.github.com/Bidthedog/cf6b4abb4bfc29fa366759625e53caea

Error is:

```
ERROR in ng:///F:/Git/project/src/app/portal/portal-user-form/portal-user-form.component.html (212,13): Type 'string' is not assignable to type 'boolean'.
ERROR in ng:///F:/Git/project/src/app/portal/portal-user-form/portal-user-form.component.html (212,13): Type 'string' is not assignable to type 'boolean'.
```

No idea how to repro as I can't figure out where the error occurs. Only happens when I use the AOT flag:

`ng serve --host 0.0.0.0 -aot`

Does not occur with the following:

`ng serve --host 0.0.0.0`

When I comment out lines 208 - 213, the error moves to line 199 (which makes no sense - unless commented out HTML is omitted during transpilation?). When I comment out line 199 the error moves to line 193, but I also get model binding errors (that are expected):

```
ERROR in ng:///F:/Git/project/src/app/portal/portal-user-form/portal-user-form.component.html (11,11): Property 'EmailAddressConfirm' does not exist on type 'PortalUserFormComponent'.
ERROR in ng:///F:/Git/project/src/app/portal/portal-user-form/portal-user-form.component.html (194,12): Property 'EmailAddressConfirm' does not exist on type 'PortalUserFormComponent'.
ERROR in ng:///F:/Git/project/src/app/portal/portal-user-form/portal-user-form.component.html (193,7): Type 'string' is not assignable to type 'boolean'.
ERROR in ng:///F:/Git/project/src/app/portal/portal-user-form/portal-user-form.component.html (11,11): Property 'EmailAddressConfirm' does not exist on type 'PortalUserFormComponent'.
ERROR in ng:///F:/Git/project/src/app/portal/portal-user-form/portal-user-form.component.html (194,12): Property 'EmailAddressConfirm' does not exist on type 'PortalUserFormComponent'.
ERROR in ng:///F:/Git/project/src/app/portal/portal-user-form/portal-user-form.component.html (193,7): Type 'string' is not assignable to type 'boolean'.
```

If  comment out line 192 - 215 (the entire "form-group"), the error moves to line 188. I've checked every boolean in the component, but can't track it down.

### The log given by the failure.

webpack: Compiling...
Date: 2017-08-24T08:58:32.923Z
Hash: d034c29f2a4df1ca7001
Time: 28086ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry]
chunk {main} main.bundle.js, main.bundle.js.map (main) 1.56 MB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 203 kB {inline} [initial]
chunk {portal.module.0} portal.module.0.chunk.js, portal.module.0.chunk.js.map () 3.43 MB {main}  [rendered]
chunk {scripts} scripts.bundle.js, scripts.bundle.js.map (scripts) 935 kB {inline} [initial]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 392 kB {inline} [initial]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.68 MB [initial]

ERROR in ng:///F:/Git/project/src/app/portal/portal-user-form/portal-user-form.component.html (212,13): Type 'string' is not assignable to type 'boolean'.
ERROR in ng:///F:/Git/project/src/app/portal/portal-user-form/portal-user-form.component.html (212,13): Type 'string' is not assignable to type 'boolean'.

webpack: Failed to compile.

### Desired functionality.

This should be a simple debug step, but the error is wild and misleading - I can't chase it down. I don't know what's happening under the hood, so I don't know if there's some reformatting going on before the error is output - hence why I believe this is an AOT bug rather than a support request.

**Comment by devoto13** [comment]
I'm pretty sure you problem is on line 224 actually. `<div *ngIf="!processing && f.submitted && submitMessage"`. Attempting to use not strictly boolean expressions in `ngIf` is known to be problematic. Is `submitMessage` of type `string`? Try to change it to `submitMessage !== ''` or whatever is reasonable for you application.

I think it will help significantly if source maps would point at the correct location. Not sure if Angular CLI caused it or Angular compiler itself...

**Comment by Bidthedog** [comment]
I've not messed with the default sourcemap setup, nor have I had any line reference issues before. I have migrated angular cli a few times from an old version, though. Just changed 224 to the following:

`<div *ngIf="!processing && f.submitted && (submitMessage !== null)"`

Error then moved to line 212...

**Comment by Bidthedog** [comment]
Commenting out 224 - 229 does the trick though, so looks like you're in the right ball park. Either way, I'd expect the line reference to be right.

**Comment by devoto13** [comment]
I'm not saying that you did anything wrong :) This issue just looks like combination of several.

Non-boolean expressions inside `ngIf` was discussed in https://github.com/angular/angular/issues/11425. And it looks like the error message is more or less clearly points what is the actual problem (if it points to the right place in the template :)). If you want a special descriptive message for this case, then it's probably feature request for Angular itself.

And there is a second issue, which is related to the source maps. It can either be CLI, which messed up source maps generated by `ngc` for templates or `ngc` itself generating incorrect source maps. In a later case it's again Angular issue, not CLI. For this problem having small runnable repro of the broken source map may be very helpful to figure out root cause of the problem and find a proper fix.

**Comment by Bidthedog** [comment]
The message is fine, it just points to the wrong line.

I got it working with exactly the same change `(submitMessage !== null)` - for some reason I needed to restart `ng serve` for it to pick it up that time around.

I nearly posted this in angular instead of the CLI, but thought "ng build" or "ng serve" might be causing it.

**Comment by devoto13** [comment]
Very similar issue is https://github.com/angular/angular-cli/issues/6374. Without good repro either.

**Comment by realappie** [comment]
@devoto13 It's kind of hard to reproduce because the issue only occurs in AoT builds. Where can we reproduce issues that occur in AoT builds online ?

**Comment by devoto13** [comment]
@realappie If you can create fresh Angular CLI application, add minimal component, which has this problem with incorrect error line reported, push it to GitHub and share a URL in comments, that would be very useful for investigation. 

Than somebody can clone your repo, `npm i`, `ng build --aot` and get same error. It will allow to investigate what's causing this problem and find appropriate fix.

**Comment by vaidd4** [comment]
@devoto13 after searching and trying for a while I'm here: 
I have the same error (`Type 'number' is not assignable to type 'boolean'`) in only one file on one line:
```
<ng-container *ngIf="!someBoolean && anArray && anArray.length">
  <!-- Many lines using 'anArray' -->
</ng-container>
```
To resolve it I just change to `*ngIf="!someBoolean && anArray && !!anArray.length"`.  
I have many other files where I have the same kind of condition in  `*ngIf`.

I tried recreating a minimal project with cli but I'm not able to reproduce (even with the same modules versions). Could it be caused by a large project ? (I have like 100Mo+ of sources)

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by vaidd4** [comment]
As mentioned at the end of my previous message, I tried creating a new project with/without `--minimal` with different conditions.
I don't reproduce the problem on a new project.

That's why I think it could be caused by some additionnal modules.

I will try extracting the problematic component on a new project.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
