### ISSUE TITLE
Bundling

### ISSUE THREAD

**Issue by zigzag95** [angular/angular-cli#750]
Is it planned to bundle /dist ?

> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
Try building with `--prod`.

**Comment by pkamdem** [comment]
@hansl
Sorry for keeping this thread active, just want to make sure the current behaviour is intended, 

Running ``ng build --environment=prod `` indeed bundles app on main file, but the whole project (js, css, html) is still being copied to ./dist.

Is there a way to only copy proper (assets e.g) files and inline components templates / styles or we should handle that ourselves for now ?

**Comment by hansl** [comment]
HTML and CSS are (for now) not bundled. The goal is to use offline compiler to compile the template and styles into code and bundle that as well. So it will happen.

For anything immediate, you should implement that yourself. There are broccoli plugins out there to do that (we use one for Material components).

**Comment by pkamdem** [comment]
@hansl 
Well ok, seeing that material2 is using gulp plugin gulp-inline-ng2-template to inline resources.
Thanks you for your time 👍
