### ISSUE TITLE
rollup not work in component lib

### ISSUE THREAD

**Issue by hpyou** [angular/angular-cli#7500]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.3.1
node: 7.2.0
os: win32 ia32
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5

### Repro steps.
I use a component lib in my app, this lib is developed by ng2 and packaged to `js`. Now i import one compoent module such as button module to use, but when i use `ng build --prod`, in `vendor.js` i can see all the component modules of the lib. I think the rollup does not work.
```
import {JigsawButtonModule} from '@rdkmaster/jigsaw';
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule, 
    FormsModule, 
    HttpModule, 
    BrowserAnimationsModule,
    JigsawButtonModule // this is my component
  ],
  bootstrap: [AppComponent],
})
export class AppModule {
}
```

### The log given by the failure.
 in `vendor.js` i can see other component modules of the lib

![image](https://user-images.githubusercontent.com/15992591/29698776-b0608738-898a-11e7-9a9f-1c00fd633d59.png)

### Desired functionality.
can angular-cli just keep the used modules and remove unused

### Mention any other details that might be useful.
my component was packaged to `js`

**Comment by Brocco** [comment]
This seems related to how the library is being built and not with the CLI. The CLI currently does not support building libraries, but it is on the roadmap.
