### ISSUE TITLE
leave file in output directory when build fail

### ISSUE THREAD

**Issue by zh99998** [angular/angular-cli#7501]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

I got a error in build time
```
ERROR in main.5ab8f909c72c397a5791.bundle.js from UglifyJs
Unexpected token: punc (}) [main.5ab8f909c72c397a5791.bundle.js:217,0]
```
well...this is hard to debug, no detail, no file, I can't know what happens.
seems there is a npm module using es6 syntax and uglifyjs, but don't know which module do that.

request add a feature to keep output files when build fail.

**Comment by filipesilva** [comment]
I agree it's confusing, but truth is that on uglify errors like this one there never is a file on disk to leave, it's all in memory.

**Comment by filipesilva** [comment]
Ah, here is the original issue for this problem and the real answer: https://github.com/angular/angular-cli/issues/5741#issuecomment-299568396
