### ISSUE TITLE
Cannot read property '__zone_symbol__ON_PROPERTYreadystatechange' of null

### ISSUE THREAD

**Issue by lafama** [angular/angular-cli#7502]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.2
node: 8.4.0
os: darwin x64

### Repro steps.

update to the latest CLI and
"@angular/animations": "^4.3.6",
"@angular/cli": "^1.3.2",
"@angular/common": "^4.3.6",
"@angular/compiler": "^4.3.6",
"@angular/compiler-cli": "^4.3.6",
 "@angular/core": "^4.3.6",
 "@angular/forms": "^4.3.6",
 "@angular/http": "^4.3.6",
 "@angular/platform-browser": "^4.3.6",
 "@angular/platform-browser-dynamic": "^4.3.6",
 "@angular/router": "^4.3.6"

### The log given by the failure.

core.es5.js:1020 ERROR TypeError: Cannot read property '__zone_symbol__ON_PROPERTYreadystatechange' of null
    at wrapFn (zone.js:1074)
    at HTMLDocument.DocumentMonitor.document.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:697:80)
    at HTMLDocument.wrapFn (zone.js:1075)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:192)
    at ZoneTask.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:499)
    at invokeTask (zone.js:1427)
    at HTMLDocument.globalZoneAwareCallback (zone.js:1445)
defaultErrorLogger @ core.es5.js:1020
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
next @ core.es5.js:4503
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
(anonymous) @ core.es5.js:3912
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844
onHandleError @ core.es5.js:3912
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:396
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:195
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445
core.es5.js:1020 ERROR TypeError: Cannot read property '__zone_symbol__ON_PROPERTYreadystatechange' of null
    at wrapFn (zone.js:1074)
    at HTMLDocument.DocumentMonitor.document.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:697:80)
    at HTMLDocument.wrapFn (zone.js:1075)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:192)
    at ZoneTask.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:499)
    at invokeTask (zone.js:1427)
    at HTMLDocument.globalZoneAwareCallback (zone.js:1445)
    
    

### Desired functionality.

No Error should be logged in the console

**Comment by sha-N** [comment]
Had the same issue after the update

running `npm install --save zone.js@0.8.16` seems to solve that

**Comment by mhadaily** [comment]
Had the same issue and fixed with zone.js@0.8.16

I also had  a LOOP of "RangeError: Maximum call stack size exceeded" due the issue

Versions.
@angular/cli: 1.3.2
node: 8.4.0
npm : 5.3.0
os: darwin x64

Repro steps.
update to the latest CLI and
"@angular/animations": "^4.3.6",
"@angular/cli": "^1.3.2",
"@angular/common": "^4.3.6",
"@angular/compiler": "^4.3.6",
"@angular/compiler-cli": "^4.3.6",
"@angular/core": "^4.3.6",
"@angular/forms": "^4.3.6",
"@angular/http": "^4.3.6",
"@angular/platform-browser": "^4.3.6",
"@angular/platform-browser-dynamic": "^4.3.6",
"@angular/router": "^4.3.6"

**Comment by JiaLiPassion** [comment]
@lafama, @mhadaily , could you provide a reproduce repo?

**Comment by mhadaily** [comment]
@JiaLiPassion https://github.com/angular/zone.js/issues/886#issuecomment-324878934

**Comment by JiaLiPassion** [comment]
@mhadaily , got it, I will look into it.
@lafama, in your case, you also use NewRelic, is that right?

**Comment by lafama** [comment]
@JiaLiPassion i don't use NewRelic and @sha-N seems to have fixed the issue for now :-)

**Comment by JiaLiPassion** [comment]
@lafama. Could you provide a reproduce repo? Thanks

**Comment by JiaLiPassion** [comment]
@mhadaily , @lafama, could you try the attached zone.js.zip resolved the issue or not?
[zone.js.zip](https://github.com/angular/angular-cli/files/1252945/zone.js.zip)

**Comment by lafama** [comment]
@JiaLiPassion the attached file seems to fix the issue 👍  .Thank you.

**Comment by JiaLiPassion** [comment]
@lafama, thank you for confirm.

**Comment by PatrikTes** [comment]
@JiaLiPassion should I replace the directory in node_modules? When I will do it, zone.js stop working

Thx

**Comment by lafama** [comment]
Inside the zone.js dist directory. Put the contents of the attached folder here node_modeules/zone.js/dist folder.

**Comment by PatrikTes** [comment]
Yes! Thx for hint, it's working now!

**Comment by zxsoft** [comment]
I've met the same problem. Is it the only way to fix it manually? Thought this problem exists in @angular/cli@1.3.2, would somebody tell me when will it be possible to fix it by install @angular/cli@1.3.3?

**Comment by JiaLiPassion** [comment]
@zxsoft, it is not a `angular-cli` issue, please wait for `zone.js@0.8.18`.

**Comment by lafama** [comment]
@zxsoft in the mean time use @sha-N solution
``npm install --save zone.js@0.8.16``

**Comment by marteloge** [comment]
Thanks! npm install --save zone.js@0.8.16 solved the problem :)
