### ISSUE TITLE
 Interface 'JQueryDeferred<T>' can not simultaneously extend types 'Deferred<T, any, any>' and 'JQueryPromise<T>'.

### ISSUE THREAD

**Issue by AbinayaSubbiah** [angular/angular-cli#7504]
I am facing below jquery issue with latest angular-cli application. could you please anyone look at this issue and suggest me how to resolve the issue.

typescript @2.4.2
jQuery @2.3

`
ERROR in E:/ICLI/186000/cli-project/node_modules/@types/jquery/index.d.ts (7815,11): Interface 'JQueryDeferred<T>' can
not simultaneously extend types 'Deferred<T, any, any>' and 'JQueryPromise<T>'.
  Named property 'always' of types 'Deferred<T, any, any>' and 'JQueryPromise<T>' are not identical.
ERROR in E:/CLI/186000/cli-project/node_modules/@types/jquery/index.d.ts (7815,11): Interface 'JQueryDeferred<T>' can
not simultaneously extend types 'Deferred<T, any, any>' and 'JQueryPromise<T>'.
  Named property 'catch' of types 'Deferred<T, any, any>' and 'JQueryPromise<T>' are not identical.
not simultaneously extend types 'Deferred<T, any, any>' and 'JQueryPromise<T>'.
  Named property 'done' of types 'Deferred<T, any, any>' and 'JQueryPromise<T>' are not identical.
ERROR in E:/le/CLI/186000/cli-project/node_modules/@types/jquery/index.d.ts (7815,11): Interface 'JQueryDeferred<T>' can
not simultaneously extend types 'Deferred<T, any, any>' and 'JQueryPromise<T>'.
  Named property 'fail' of types 'Deferred<T, any, any>' and 'JQueryPromise<T>' are not identical.
ERROR in E:/I/CLI/186000/cli-project/node_modules/@types/jquery/index.d.ts (7815,11): Interface 'JQueryDeferred<T>' can
not simultaneously extend types 'Deferred<T, any, any>' and 'JQueryPromise<T>'.
  Named property 'pipe' of types 'Deferred<T, any, any>' and 'JQueryPromise<T>' are not identical.
ERROR in E:/sampi-project/node_modules/@types/jquery/index.d.ts (7815,11): Interface 'JQueryDeferred<T>' can
not simultaneously extend types 'Deferred<T, any, any>' and 'JQueryPromise<T>'.
  Named property 'progress' of types 'Deferred<T, any, any>' and 'JQueryPromise<T>' are not identical.
ERROR in E:/sample/CLI/186000/cli-project/node_modules/@types/jquery/index.d.ts (7815,11): Interface 'JQueryDeferred<T>' can
not simultaneously extend types 'Deferred<T, any, any>' and 'JQueryPromise<T>'.
  Named property 'promise' of types 'Deferred<T, any, any>' and 'JQueryPromise<T>' are not identical.
ERROR in E:/sample/CLI/186000/cli-project/node_modules/@types/jquery/index.d.ts (7815,11): Interface 'JQueryDeferred<T>' can
not simultaneously extend types 'Deferred<T, any, any>' and 'JQueryPromise<T>'.
  Named property 'then' of types 'Deferred<T, any, any>' and 'JQueryPromise<T>' are not identical.`

**Comment by clydin** [comment]
TS 2.4 has more extensive type checking.  This looks like a problem with the type definitions of `@types/jquery`.

**Comment by bangonkali** [comment]
Try specifying versions `npm install --save-dev @types/jquery@3.2.7`

**Comment by bangonkali** [comment]
@AbinayaSubbiah did it solve issue?

**Comment by AbinayaSubbiah** [comment]
@bangonkali  yes
