### ISSUE TITLE
The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli

### ISSUE THREAD

**Issue by jsnsree** [angular/angular-cli#7515]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Output from: `ng --version`.
@angular/cli: 1.3.1
node: 6.11.2
os: linux x64
@angular/animations: error
@angular/common: error
@angular/compiler: error
@angular/core: error
@angular/forms: error
@angular/http: error
@angular/platform-browser: error
@angular/platform-browser-dynamic: error
@angular/platform-server: error
@angular/router: error
@angular/cli: error
@angular/compiler-cli: error

ubuntu 16.04 , 64-bit

### The log given by the failure.
output from : npm start , ng serve
![screenshot from 2017-08-26 17-44-50](https://user-images.githubusercontent.com/20822800/29741255-945ddaf2-8a86-11e7-93e0-8c72de281a80.png)
![screenshot from 2017-08-26 17-44-50](https://user-images.githubusercontent.com/20822800/29741257-a33ce676-8a86-11e7-89d1-723a7a802cf5.png)

The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.<anonymous> (/home/jsnsree/.nvm/versions/node/v6.11.2/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jsnsree/.nvm/versions/node/v6.11.2/lib/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

### Desired functionality.
1. npm start
2. ng serve

**Comment by jsnsree** [comment]
in my package.json file : 
"dependencies": {
    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@angular/platform-server": "4.1.3",
    "@angular/router": "4.1.3",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.26",
    "@ngx-translate/core": "6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "amcharts3": "github:amcharts/amcharts3",
    "ammap3": "github:amcharts/ammap3",
    "angular2-datatable": "0.6.0",
    "animate.css": "3.5.2",
    "bootstrap": "4.0.0-alpha.6",
    "chart.js": "1.1.1",
    "chartist": "0.10.1",
    "chroma-js": "1.3.3",
    "ckeditor": "4.6.2",
    "core-js": "2.4.1",
    "easy-pie-chart": "2.1.7",
    "font-awesome": "4.7.0",
    "fullcalendar": "3.3.1",
    "google-maps": "3.2.1",
    "ionicons": "2.0.1",
    "jquery": "3.2.1",
    "jquery-slimscroll": "1.3.8",
    "leaflet": "0.7.7",
    "leaflet-map": "0.2.1",
    "lodash": "4.17.4",
    "ng2-ckeditor": "1.1.6",
    "ng2-completer": "1.3.1",
    "ng2-handsontable": "0.48.0",
    "ng2-slim-loading-bar": "4.0.0",
    "ng2-smart-table": "1.0.3",
    "ng2-tree": "2.0.0-alpha.5",
    "ngx-uploader": "2.2.5",
    "normalize.css": "6.0.0",
    "roboto-fontface": "0.7.0",
    "rxjs": "5.4.0",
    "zone.js": "0.8.11"
}

**Comment by Brocco** [comment]
Is this still an issue?
If so, have you deleted `node_modules` and reinstalled?

If this issue is resolved, please close it, Thanks!

**Comment by jsnsree** [comment]
Thank you @Brocco it is working now.

**Comment by fsureau** [comment]
@Brocco is there a reason for that? Because deleting the folder is not a solution or a root cause, it's a trick.
We can see that in a lot of threads (StackOverflow, Github, etc...) but is would be better to find a long term solution.
By the way, this trick doesn't solve the problem for me.
