### ISSUE TITLE
the prolem is with npm installation.What is that issue related with call.Thanks in adance

### ISSUE THREAD

**Issue by kittengit** [angular/angular-cli#7516]
C:\Users\sys>npm clear cache
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js"
 prefix -g' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Brocco** [comment]
This looks like an npm issue, not a CLI issue... closing.
