### ISSUE TITLE
Disabling autoprefixer for CSS grid rules breaks component rendering on Chrome but only when stylesheet is in external CSS file.

### ISSUE THREAD

**Issue by diopsidedesign** [angular/angular-cli#7517]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Node 8.1.4
angular-cli 1.3.0
Win 10 

### Repro steps.
Create component that uses CSS grid. Switch style rules from external file back to component file and vice-versa.

### The log given by the failure.
N/A. It compiles without issue but renders improperly.

### Desired functionality.
That components would render identically with identical stylesheets regardless of where the stylesheet is located (inline vs. external file).

### Mention any other details that might be useful.

Forgive me if this is not the proper place for this. I wasn't sure if this belonged in autoprefixer issues, webpack issues, or another area....

I recently started reorganizing my Angular app to make a more maintainable file structure, and part of that involved moving the inline stylesheets in my components to external css files. I have a couple of components that utilize the CSS grid spec ( https://www.w3.org/TR/css-grid-1/ ) and once i moved those CSS rules into external stylesheets, I began to receive warnings from webpack that the auto-prefixer couldn't prefix certain CSS grid rules to support IE. That's fine, I don't intend to support IE or any old browsers really, so I disabled prefixing of the violating rules by using control comments

/* autoprefixer: off */  

and

 /* autoprefixer: on */  
 
This got rid of the warnings, but now the components render improperly, as if the control comment is causing *all* of the CSS following the 'autoprefixer: off' statement to be ignored, regardless of any  control comments to re-enable it. The same stylesheets work perfectly when included in the component's typescript file with   styles: [ ... ], even with the autoprefixer control comments still there. But they cause really buggy rendering if moved to an external file and referenced with styleUrls: [ ... ].  

Is this user error or a bug? Perhaps the control comments don't work how I think they do? I didn't think that the most recent version of Chrome would *need* any prefixes, because it fully supports the CSS grid specification. So its odd to me, that disabling the prefixer for the grid rules would cause Chrome to render it improperly and doubly odd that the exact same stylesheet works correctly when included in the component metadata explicitly.

**Comment by filipesilva** [comment]
Hi there, can you provide a step by step repro we can follow to see this problem please? E.g. what rules to use, where should the autoprefixer comment be added, etc.

**Comment by diopsidedesign** [comment]
So I took a year break from Angular and completely forgot about this issue. I've revived my old code with the newest version of Angular, and I'm still experiencing the exact same bug where identical CSS code displays differently if its in a separate stylesheet as opposed to included in the styles property of the component decorator. Should I open a new issue? or can this one be revived?

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
