### ISSUE TITLE
Underscores not allowed in generated class names 

### ISSUE THREAD

**Issue by abductedMind** [angular/angular-cli#7518]
### Bug Report or Feature Request (mark with an `x`)
```
- [] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.

@angular/cli: 1.3.2
node: 6.11.2
os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6

### Repro steps.

`ng g c step-1_welcome` creates a component with the file name `step-1-welcome` and a class name `Step1WelcomeComponent` rather than the expected `step-1_welcome` and `Step1_WelcomeComponent`

### The log given by the failure.

n/a

### Desired functionality.

To be able to create more readable class names and directories.

### Mention any other details that might be useful.

If this is against convention, please provide me with a reference as to why this is the case.

**Comment by alexeagle** [comment]
The style guide says to use dot and dash:
https://angular.io/guide/styleguide#separate-file-names-with-dots-and-dashes

(I'd prefer to choose underscore sometimes too, but given the CLI has done it this way for years now, I don't think we should change the behavior, and it does match the style guide.)
