### ISSUE TITLE
ERROR in ./src/main.ts Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' 

### ISSUE THREAD

**Issue by stupidly-logical** [angular/angular-cli#7520]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.2
node: 8.4.0
os: linux x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.8-ec4ea06
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/material: 2.0.0-beta.8-ec4ea06
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6

### Repro steps.

ng build --prod

### The log given by the failure.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'

**Comment by dodysw** [comment]
Updating this line in package.json seems to fix it:

"@angular/cli": "~1.3.2"

**Comment by Martin-Wegner** [comment]
Same problem here with 1.4.0-rc.2

**Comment by filipesilva** [comment]
Hi there,

Can you provide a reproduction I can follow of this happening? This doesn't happen on a new project.

**Comment by Martin-Wegner** [comment]
The error occurs since Angular 5.0.0-beta.5 but I think the cause is a 3rd party lib which is not compatible with Angular 5.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
