### ISSUE TITLE
Updating assets requires a code recompilation

### ISSUE THREAD

**Issue by intellix** [angular/angular-cli#7521]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

node: 8.2.1
os: darwin x64
@angular/animations: 5.0.0-beta.4
@angular/cli: 1.4.0-rc.1
@angular/common: 5.0.0-beta.4
@angular/compiler: 5.0.0-beta.4
@angular/compiler-cli: 4.3.4
@angular/core: 5.0.0-beta.4
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 5.0.0-beta.4
@angular/http: 5.0.0-beta.4
@angular/platform-browser: 5.0.0-beta.4
@angular/platform-browser-dynamic: 5.0.0-beta.4
@angular/router: 5.0.0-beta.4
@angular/language-service: 4.3.4
typescript: 2.4.2

### Repro steps.

1) `curl localhost:4200/assets/image.svg`
2) Change that image slightly and save it
3) `curl localhost:4200/assets/image.svg` - will not show the change
4) Save a file like `app.component.ts`
5) `curl localhost:4200/assets/image.svg` - you'll see the change

### Desired functionality.

Would like changes reflected without having to update a watched file. I'm currently debugging some weird SVG issues to do with feColorMatrix and was confused why changes weren't being shown. It wasn't until I saw the same issues in Firefox that I realised the problem was the server.

**Comment by savasayik** [comment]
+1

**Comment by dklmuc** [comment]
I also think assets should trigger a reload. As far as I understand the webpack-dev-server is holding the files in RAM, so also a manually Browser Refresh wouldn't show new versions of the files in the assets folder. Therefor a restart of the CLI is mandatory, which hurts a lot with an initial startup time of e.g. 40 seconds.

Other use case besides @intellix SVG example:
Using ngx-translate with JSON files for the translations in the assets folder.

**Comment by filipesilva** [comment]
This seems to be an unintended consequence of https://github.com/angular/angular-cli/pull/7310, where another different bug was masking this bug.
