### ISSUE TITLE
styleExt troubles

### ISSUE THREAD

**Issue by stewwan** [angular/angular-cli#7522]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.0-rc.1
node: 7.1.0
os: darwin x64

### Repro steps.
first: open .angular-cli.json and modify `styleExt` to `sass`.
second: ng generate component hello

### Desired functionality.
it looks like that the property "styleExt" of .angular-cli.json is not being used as expected. So if you have "sass" pre-configured in .json and then want to get a new component, it will generate the style file with ".css" extension, instead of sass. until forcing --style=sass in command.

**Comment by funkizer** [comment]
Still `ng g c component-name` is generating with the default "app" -prefix instead of what's defined in .angular-cli.json. Local and global @angular/cli: 1.4.1. What am I missing? Worked 5 minutes ago before updating from 1.3.2.

>  "devDependencies": {
    "@angular/cli": "^1.4.1",
    "@angular/compiler-cli": "^4.4.0-RC.0",
    "@angular/language-service": "^4.4.0-RC.0",
    "@schematics/angular": "0.0.33",
    "@types/jasmine": "~2.5.54",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.0.28",
    "codelyzer": "^3.2.0",
    "jasmine-core": "^2.8.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "^3.3.0",
    "tslint": "^5.7.0",
    "typescript": "^2.5.2"
  }

**Comment by funkizer** [comment]
Apparently `ng g component component-name` works as intended, it's just the `c` shorthand that's still failing to use correct prefix.
