### ISSUE TITLE
CLI v1.4.0-rc.1 `ng new --routing` generates erroneous `app-routing.module.ts`

### ISSUE THREAD

**Issue by bogacg** [angular/angular-cli#7524]
### Bug Report or Feature Request
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.0-rc.1
node: 8.3.0
os: win32 x64

### Repro steps.

`ng new TESTPRO --routing`

`ng serve`

To see the source generated (without `ng serve`):  `ng new TESTPRO -st -si --routing` suffice.

*app-routing.module.ts* is generated in form:
```
@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
```

### The log given by the failure.
`Error: No provider for ChildrenOutletContexts!`

### Desired functionality.
A main routing module generated with `.forRoot(routes)`
```
@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
```

**Comment by Basel78** [comment]
Hello,
I am still facing this issue with new project in angular-cli, how to resolve this issue?
Thanks

**Comment by Basel78** [comment]
Actually I resolved the issue by using the command below for creating app-routing
ng g module app-routing
the link below help me fix it
https://shermandigital.com/blog/configure-routing-in-an-angular-cli-project/

**Comment by musmanzpak** [comment]
I get one the best to understand about [Angular routing and navigation including route params](https://gethybridapp.com/angular-5-routing-and-navigation-including-route-params/)
