### ISSUE TITLE
Error : Cannot find module 'abbrev'. Unable to create project using npm

### ISSUE THREAD

**Issue by Karan1458** [angular/angular-cli#7530]
### Bug Report 
```
- [ ] bug report : Unable to create AngularJS Projects under linux system.
```

### Versions.
NPM : 5.3.0
NODE: 7.10.1
OS : (Linux) Ubuntu 17.10 ( 4.12.0-11-generic )

### Repro steps.
1. Adding PPA : curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
2. Installing Nodejs : $sudo apt install nodejs
3. Installing build tools : $sudo apt install build-essential
4. Update npm to latest : $sudo npm install npm@latest -g
5. Installing Angular : $sudo npm install -g @angular/cli
5. Then creating project : $ng new my-app

Simply installed the angual

### The log given by the failure.

`$ ng new my-app
module.js:472
    throw err;
    ^

Error: Cannot find module 'abbrev'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/node_modules/nopt/lib/nopt.js:10:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)`

### Desired functionality.

It should create project simply.

### Mention any other details that might be useful.

- Already searched the issues related to this, they are for different cases. Unable to sort out in my case.

- Installing Nodejs : https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

**Comment by filipesilva** [comment]
Your problem is a permissions issue due to installing global npm packages using `sudo`.

Although installing npm and node should be done with `sudo`, doing `npm install package-name` should never be done using `sudo` as that causes problems with permissions. See https://docs.npmjs.com/getting-started/fixing-npm-permissions for more details.

**Comment by Karan1458** [comment]
Hello Filipesilva, 

Thank's for sorting out this. Yes, It starts working after setting packages to local directory. 
Regards,
Karan

**Comment by saidmaster** [comment]
npm install -g abbrev 
it works for me
