### ISSUE TITLE
Reference file in component style, which is outside build folder

### ISSUE THREAD

**Issue by SmallhillCZ** [angular/angular-cli#7533]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.3.2

### Repro steps.
- Create an app and reference some file in component style, which is not part of the build, e.g. ```background-image: url("/images/image123.png")```
- The build will rewrite this absolute (!) path as ```background-image:url("/dist/images/image123.png")```

### Problem
 - If I use path not mentioned in assets, it will yield an error during build time, if I provide path in assets, it will change path.
 - I want to have asset folders (assets, exports, avatars) separated from TS code and manage serving separately
    - Some of my files change due to server logic, so I do not want to have them copied at build time and thus make them static.
    - I want to serve these folders with custom cache expiry date
     - I wan to use files from these folders for other purposes

### Desired functionality.
Just give me an option in CLI to not touch my CSS url paths at all.

### Mention any other details that might be useful.
I'm not using ```ng serve```.

**Comment by filipesilva** [comment]
Absolute paths shouldn't be changed, so this sounds like a bug. Thanks for reporting it!

**Comment by clydin** [comment]
Can you provide the command line and angular-cli configuration file being used?

**Comment by SmallhillCZ** [comment]
I am running: 

```ng build --prod```

and the config is: 

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "cityvizor-app"
  },
  "apps": [
    {
      "root": "ui",
      "outDir": "dist/app",
      "deployUrl": "/dist/app",
      "assets": [
      ],
      "index": "app.index.html",
      "main": "app.main.ts",
      "polyfills": "polyfills.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "lint": [
    {
      "project": "ui/tsconfig.app.json"
    },
    {
      "project": "ui/tsconfig.spec.json"
    }
  ],
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
