### ISSUE TITLE
ng eject fails

### ISSUE THREAD

**Issue by JosephBL** [angular/angular-cli#7535]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.3.2
node: 8.0.0
os: darwin x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.5

Mac OSX Sierra 10.12.6

### Repro steps.
ng eject

### The log given by the failure.
ng eject
Cannot read property 'build' of undefined
TypeError: Cannot read property 'build' of undefined
    at Promise.resolve.then.then.then.then.then (/Users/foo/Projects/someProject/front/node_modules/@angular/cli/tasks/eject.js:409:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

### Desired functionality.
Well working would be better :)

**Comment by athergeek** [comment]
I had the same issue, i resolved it by removing following two lines from "script" section from package.json file.

        "start": "ng serve --ec true --port 4201",
        "build": "ng build --prod",

Do not remove the whole "script" section.

**Comment by alan-agius4** [comment]
`ng eject` is no longer provided by Angular CLI. 

If you need this feature use https://github.com/manfredsteyer/ngx-build-plus
