### ISSUE TITLE
Support for globbing in Sass @import statements

### ISSUE THREAD

**Issue by deKaantje** [angular/angular-cli#7538]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```
### Desired functionality.
I would love to be able to use globbing in .scss' @import statement, for instance: 
```scss
@import "core/**/*";
```
Normally I would add this to Webpack's preloaders, but since the Webpack config is not public (for good reasons, I know), I cant do this myself.

Thanks in advance!

**Comment by nilesh93** [comment]
I used a workaround using gulp, as mentioned in this blog post
https://medium.com/@nilesh93.j/enabling-sass-globbing-with-angular-cli-35ab95204406

**Comment by alan-agius4** [comment]
Hi, this is outside of the scope of the CLI and the sass pre-processor itself doesn't support this feature.

If you want to extent the webpack configuration you can use: https://github.com/manfredsteyer/ngx-build-plus
