### ISSUE TITLE
Adding material2 to an cli created app

### ISSUE THREAD

**Issue by chrisvelevitch** [angular/angular-cli#754]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Mac OSX (Mavericks)

2. Versions. 
angular-cli: 1.0.0-beta.1
node: 5.10.1
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

a. ng new myapp
b. cd myapp
c. ng serve
d. added toolbar import and directives to myapp.component.ts
e. view javascript console
f. Loading... remains showing
g. Console shows: GET http://localhost:4200/vendor/@angular2-material/toolbar/toolbar.js 404 (Not Found)

4. The log given by the failure. Normally this include a stack trace and some
   more information.

zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/vendor/@angular2-material/toolbar/toolbar.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
	Error loading http://localhost:4200/vendor/@angular2-material/toolbar/toolbar.js as "@angular2-material/toolbar" from http://localhost:4200/app/running-costs.component.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/vendor/@angular2-material/toolbar/toolbar.js(…)

5. Mention any other details that might be useful.
I followed these instructions https://github.com/angular/angular-cli/wiki/3rd-party-libs to add material to the app

**Comment by pkamdem** [comment]
@chrisvelevitch ,

Can you paste your <Source Dir>/system-config.ts and <Project Root>/angular-cli-build.js here?

**Comment by hansl** [comment]
Please refer to https://github.com/angular/angular-cli/wiki/3rd-party-libs#adding-material2-to-your-project.

**Comment by chrisvelevitch** [comment]
@hansl: I stated that link in the other details section of my original post.

@pkamdem: here are the files you requested:-

[angular-cli-build.txt](https://github.com/angular/angular-cli/files/264325/angular-cli-build.txt)

[system-config.txt](https://github.com/angular/angular-cli/files/264326/system-config.txt)
