### ISSUE TITLE
ERROR in multi script-loader! in angular2 while running application

### ISSUE THREAD

**Issue by mehuljdaxini** [angular/angular-cli#7543]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```
ERROR in multi script-loader!./src/assets/plugins/jquery/jquery.min.js script-loader!./src/assets/plugins/bootstrap/js/tether.min.js script-loader!./src/asset
s/plugins/bootstrap/js/bootstrap.min.js script-loader!./src/assets/plugins/bootstrap-extension/js/bootstrap-extension.min.js script-loader!./src/assets/js/jqu
ery.slimscroll.js script-loader!./src/assets/js/sidebarmenu.js script-loader!./src/assets/plugins/sparkline/jquery.sparkline.min.js script-loader!./src/assets
/js/custom.js script-loader!./src/assets/js/pace.min.js script-loader!./src/assets/plugins/styleswitcher/jQuery.style.switcher.js,
Module not found: Error: Can't resolve 'D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\src\assets\plugins\styleswitcher\jQuery.style.switcher.js,' in 'D:\MEHUL\PROJECTS
\LMS\CODE\LMS\LMSYS\node_modules\@angular\cli\models\webpack-configs'
resolve 'D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\src\assets\plugins\styleswitcher\jQuery.style.switcher.js,' in 'D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\node_module
s\@angular\cli\models\webpack-configs'
  using description file: D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\node_modules\@angular\cli\package.json (relative path: ./models/webpack-configs)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\node_modules\@angular\cli\package.json (relative path: ./models/webpack-configs)
    using description file: D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\package.json (relative path: ./src/assets/plugins/styleswitcher/jQuery.style.switcher.js,)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\src\assets\plugins\styleswitcher\jQuery.style.switcher.js, doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\src\assets\plugins\styleswitcher\jQuery.style.switcher.js,.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\src\assets\plugins\styleswitcher\jQuery.style.switcher.js,.js doesn't exist
      as directory
        D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\src\assets\plugins\styleswitcher\jQuery.style.switcher.js, doesn't exist
[D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\src\assets\plugins\styleswitcher\jQuery.style.switcher.js,]
[D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\src\assets\plugins\styleswitcher\jQuery.style.switcher.js,.ts]
[D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\src\assets\plugins\styleswitcher\jQuery.style.switcher.js,.js]
[D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\src\assets\plugins\styleswitcher\jQuery.style.switcher.js,]
 @ multi script-loader!./src/assets/plugins/jquery/jquery.min.js script-loader!./src/assets/plugins/bootstrap/js/tether.min.js script-loader!./src/assets/plug
ins/bootstrap/js/bootstrap.min.js script-loader!./src/assets/plugins/bootstrap-extension/js/bootstrap-extension.min.js script-loader!./src/assets/js/jquery.sl
imscroll.js script-loader!./src/assets/js/sidebarmenu.js script-loader!./src/assets/plugins/sparkline/jquery.sparkline.min.js script-loader!./src/assets/js/cu
stom.js script-loader!./src/assets/js/pace.min.js script-loader!./src/assets/plugins/styleswitcher/jQuery.style.switcher.js,
### Versions.

@angular/cli: 1.3.1
node: 6.11.2
os: win32 x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/compiler-cli: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/platform-server: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.1
@angular/language-service: 4.3.5

**Comment by filipesilva** [comment]
Your error says that a file you're trying to load is missing: `Error: Can't resolve 'D:\MEHUL\PROJECTS\LMS\CODE\LMS\LMSYS\src\assets\plugins\styleswitcher\jQuery.style.switcher.js,'`.

This probably means you have a bad path in your `scripts` array. If you still have problems please open a new issue with detailed reproduction steps we can follow.

**Comment by napstercake** [comment]
This works perfectly for me: https://stackoverflow.com/a/46775040/1301933

**Comment by nandhuems** [comment]
Please check the solution: 
https://github.com/angular/angular-cli/issues/5665#issuecomment-452282834

**Comment by nandhuems** [comment]
I had same issue but fixed.
Please check inside .angular-cli.json all the linked scripts files are available or not. if any one script file is not available the @ multi script-loader error will come. Properly link all the script path.
