### ISSUE TITLE
unit tests not compiled template literals

### ISSUE THREAD

**Issue by acopalipsis** [angular/angular-cli#7546]
```
it( 'template literals', () => {
    expect(  `{ 'text' }` ) ).toBe( 'text' ); // error -> '{ text }' is  not 'text'
} );
```

**Comment by deebloo** [comment]
@acopalipsis please fill out the issue template in future. Also the behavior you are seeing is correct and is in Jasmine not the cli itself. Template literals aren't automatically turned into objects, they are just strings

**Comment by filipesilva** [comment]
Closing as answered by @deebloo, thanks!
