### ISSUE TITLE
shasum check failed while installing @angular/cli

### ISSUE THREAD

**Issue by vishuseth** [angular/angular-cli#7549]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "@angular/cli"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\xyz\AppData\Local\Temp\npm-7404-1a5
2ce21\registry.npmjs.org\less\-\less-2.7.2.tgz
npm ERR! Expected: 368d6cc73e1fb03981183280918743c5dcf9b3df
npm ERR! Actual:   cfe967c3959375a4cb67c41fe6e92b0c1e3161c6
npm ERR! From:     https://registry.npmjs.org/less/-/less-2.7.2.tgz

### Versions.

node -v
v6.11.2

npm -v
3.10.10

OS - Windows 7

### Repro steps.

npm install @angular/cli

npm install -g @angular/cli

### The log given by the failure.

3699 info attempt registry request try #1 at 6:25:26 PM
3700 http fetch GET https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz
3701 http fetch 200 https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz
3702 silly fetchAndShaCheck shasum 0b8320a65065965d998645b1f5cd3cf769b441ea
3703 verbose addTmpTarball C:\Users\xyz\AppData\Local\Temp\npm-15904-668277d3\registry.npmjs.org\_40angular\core\-\core-2.4.10.tgz not in flight; adding
3704 verbose addTmpTarball already have metadata; skipping unpack for @angular/core@2.4.10
3705 verbose correctMkdir C:\Users\xyz\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3706 silly cache afterAdd @angular/core@2.4.10
3707 verbose afterAdd C:\Users\xyz\AppData\Roaming\npm-cache\@angular\core\2.4.10\package\package.json not in flight; writing
3708 verbose correctMkdir C:\Users\xyz\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3709 verbose afterAdd C:\Users\xyz\AppData\Roaming\npm-cache\@angular\core\2.4.10\package\package.json written
3710 silly fetchAndShaCheck shasum 75ce38f52bf0733c5a7f0c118d81334a2bb5f412
3711 verbose addTmpTarball C:\Users\xyz\AppData\Local\Temp\npm-15904-668277d3\registry.npmjs.org\source-map\-\source-map-0.5.6.tgz not in flight; adding
3712 verbose addTmpTarball already have metadata; skipping unpack for source-map@0.5.6
3713 verbose correctMkdir C:\Users\xyz\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3714 silly cache afterAdd source-map@0.5.6
3715 verbose afterAdd C:\Users\xyz\AppData\Roaming\npm-cache\source-map\0.5.6\package\package.json not in flight; writing
3716 verbose correctMkdir C:\Users\xyz\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3717 verbose afterAdd C:\Users\xyz\AppData\Roaming\npm-cache\source-map\0.5.6\package\package.json written
3718 silly rollbackFailedOptional Starting
3719 silly rollbackFailedOptional Finishing
3720 silly runTopLevelLifecycles Finishing
3721 silly install printInstalled
3722 verbose stack Error: shasum check failed for C:\Users\xyz\AppData\Local\Temp\npm-15904-668277d3\registry.npmjs.org\html-webpack-plugin\-\html-webpack-plugin-2.30.1.tgz
3722 verbose stack Expected: 7f9c421b7ea91ec460f56527d78df484ee7537d5
3722 verbose stack Actual:   0c9bcaf9e73bdacbb81ec79f2e1781bcc8e6c41c
3722 verbose stack From:     https://registry.npmjs.org/html-webpack-plugin/-/html-webpack-plugin-2.30.1.tgz
3722 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
3722 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
3722 verbose stack     at emitNone (events.js:91:20)
3722 verbose stack     at ReadStream.emit (events.js:185:7)
3722 verbose stack     at endReadableNT (_stream_readable.js:974:12)
3722 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
3722 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
3723 verbose cwd C:\Windows\system32
3724 error Windows_NT 6.1.7601
3725 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
3726 error node v6.11.2
3727 error npm  v3.10.10
3728 error shasum check failed for C:\Users\xyz\AppData\Local\Temp\npm-15904-668277d3\registry.npmjs.org\html-webpack-plugin\-\html-webpack-plugin-2.30.1.tgz
3728 error Expected: 7f9c421b7ea91ec460f56527d78df484ee7537d5
3728 error Actual:   0c9bcaf9e73bdacbb81ec79f2e1781bcc8e6c41c
3728 error From:     https://registry.npmjs.org/html-webpack-plugin/-/html-webpack-plugin-2.30.1.tgz
3729 error If you need help, you may report this error at:
3729 error     <https://github.com/npm/npm/issues>
3730 verbose exit [ 1, true ]

### Desired functionality.

Angular CLI installed

**Comment by filipesilva** [comment]
This seems like a bug with npm and not with Angular CLI (since it enver even runs). Please report it in the npm issue tracker instead: https://github.com/npm/npm.
