### ISSUE TITLE
Prefix is ignored when generating components

### ISSUE THREAD

**Issue by SebastianSchenk** [angular/angular-cli#7553]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.0-rc.2
node: 7.4.0
os: darwin x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.0-rc.2
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
typescript: 2.3.4

### Repro steps.

`ng g new my-app --prefix=my`
`cd src/app`
`ng g c test`

--> A new component is generated with the selector: `app-test`

### Desired functionality.

The selector should be called `my-test`

### Mention any other details that might be useful.

This is my .angular-cli.json
````
    {
      "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
      "project": {
        "name": "my-app"
      },
      "apps": [
        {
          "root": "src",
          "outDir": "dist",
          "assets": [
            "assets",
            "favicon.ico"
          ],
          "index": "index.html",
          "main": "main.ts",
          "polyfills": "polyfills.ts",
          "test": "test.ts",
          "tsconfig": "tsconfig.app.json",
          "testTsconfig": "tsconfig.spec.json",
          "prefix": "my",
          "styles": [
            "styles.scss"
          ],
          "scripts": [],
          "environmentSource": "environments/environment.ts",
          "environments": {
            "dev": "environments/environment.ts",
            "prod": "environments/environment.prod.ts"
          }
        }
      ],
      "e2e": {
        "protractor": {
          "config": "./protractor.conf.js"
        }
      },
      "lint": [
        {
          "project": "src/tsconfig.app.json"
        },
        {
          "project": "src/tsconfig.spec.json"
        },
        {
          "project": "e2e/tsconfig.e2e.json"
        }
      ],
      "test": {
        "karma": {
          "config": "./karma.conf.js"
       }
      },
      "defaults": {
        "styleExt": "scss",
        "component": {}
      }
    }
````

**Comment by intellix** [comment]
I'm also getting SCSS file config ignored as well. Are you getting CSS or SCSS files generated when you generate a component with RC?

**Comment by dottodot** [comment]
I'm seeing the same issue on 1.4.0-rc.2 both app prefix and scss are being ignore and defaulting to app and css.

**Comment by filipesilva** [comment]
I'll track the styleExt in https://github.com/angular/angular-cli/issues/7522.

**Comment by Brocco** [comment]
Closing as a duplicate of #7522
