### ISSUE TITLE
Define method when defining context in proxy-config

### ISSUE THREAD

**Issue by slavede** [angular/angular-cli#7554]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.3.2
node: 6.9.1
os: win32 x64

### Desired functionality.

While defining the context for proxy, it would be very nice to be able to define a method as well. Currently, we define it like this:

```
const PROXY_CONFIG = [
  {
      context: [
          "/api/resource/*",
      ],
      target: "http://localhost:3000",
      secure: false,
      logLevel : "debug"
  },
  {
    context: [
        "/api/*",
    ],
    target: "http://your.remote.backend",
    secure: false,
    logLevel : "debug"
}]

module.exports = PROXY_CONFIG;
```

We could use something like this:

```
. . .
context: [{
    url:"/api/*",
    method : "POST"
}]
. . .
```

**Comment by filipesilva** [comment]
Heya, at Angular CLI we just provide a way to load the proxy config that https://github.com/webpack/webpack-dev-server uses. You should submit your feature request there instead.

**Comment by slavede** [comment]
Didn't realize that. Sure, I'll submit it there, tnx!
