### ISSUE TITLE
differences in decorator metadata between tsc output and main.bundle.js

### ISSUE THREAD

**Issue by markusu49** [angular/angular-cli#7559]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.0-beta.1
node: 8.1.3
os: linux x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.0-beta.1
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6

### Repro steps.
1. run `ng new`
2. add this code to `src/app/app.component.ts`:

```
import "reflect-metadata";

const formatMetadataKey = Symbol("format");

function format(formatString: string) {
    return Reflect.metadata(formatMetadataKey, formatString);
}

class Greeter {
    @format("Hello, %s")
    greeting: Set<string>;
}
```

3. run `ng build`
4. run `./node_modules/.bin/tsc` (to restore tsc output)

### The log given by the failure.
no errors

### Desired functionality.
`dist/main.bundle.js` will contain something like `__metadata("design:type", Object)`

The `greeting` property is of type `Set`, so this is wrong.

`dist/out-tsc/src/app/app.component.js` will contain `__metadata("design:type", Set)`

This means that it is not a problem of the typescript compiler. What else is happening here?

### Mention any other details that might be useful.
It might be related to `Set` being ES6, not ES5. If you remove the `es2017` lib from `tsconfig.json`, even `tsc` will output `Object`. Changing `target` to `es6` in `tsconfig.json` does not help (tsc output is still correct, but not main.bundle.js).

**Comment by Meligy** [comment]
Although I'm not sure of the exact problem, your TypeScript test is not correct.

It should be `./node_modules/.bin/tsc -p ./src/tsconfig.app.json`

**Comment by filipesilva** [comment]
@Meligy raises a good point, the `./src/tsconfig.app.json` is the wone you should be using. Have you checked if the result is still different then?

**Comment by markusu49** [comment]
Sorry for the late reply, I was on holiday. I have tried again with the command mentioned by @Meligy, getting the same result. tsc output will go to `./out-tsc/app/app/app.component.js` instead of `./dist/out-tsc/src/app/app.component.js`, but the content is still different.

**Comment by Petr0vi4** [comment]
The key part is that `angular-cli` uses `transpileModule` method to compile the class. This method forces  `noLib` compiler flag, so there is no `Set` class during the compilation.

**Comment by clydin** [comment]
With CLI 1.5+ and Angular 5+, this now works properly.  The new compiler pipeline for Angular 5 no longer uses `transpileModule`.
