### ISSUE TITLE
Is angular-cli-live-reload.js missing ?

### ISSUE THREAD

**Issue by pkamdem** [angular/angular-cli#756]
Getting angular-cli-live-reload.js return error.

> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run in a Terminal: 
angular-cli: 1.0.0-beta.2-mobile.2
node: 6.1.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Nothing special. It's systematic after fresh cli app creation

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

The behaviour seems to happen following the introduction of Handlebars for building the index.html
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by pkamdem** [comment]
turning to ember-cli-live-reload.js seems to be ok

**Comment by hansl** [comment]
Thanks we'll investigate the proper location of live-reload.

**Comment by jeffbcross** [comment]
It's probably something I've caused. I noticed it to, but thought it was just with `--mobile`.
