### ISSUE TITLE
ng build - add option to override eject property in angular-cli.json

### ISSUE THREAD

**Issue by djarekg** [angular/angular-cli#7562]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.

1.4.0-rc.2

### Desired functionality.

Currently i use the ng eject command to output my webpack.config.js file from my angular-cli.json. I do this because I use hot module replacement and use aspnetcore. Currently, the aspnetcore JavascriptServices does not support angular-cli. I like to use the ng build command to build my prod/aot builds and to do so i have to remove my webpack.config.js file and change the eject property to false in my angular-cli.json. It would be quicker and smoother to be able to switch between using eject and not using eject without having to manually remove/change stuff. My request is that a option/flag (i.e. --eject-ignore) is added to the ng build command to specify ignoring the eject setting in the angular-cli.json file and that would mean then ignoring any webpack.config.js files that exists in the same directory.

**Comment by clydin** [comment]
eject functionality is no longer available in the latest version (6.x+).  For custom webpack configurations the following unofficial add-on is a suggested solution: https://github.com/manfredsteyer/ngx-build-plus
