### ISSUE TITLE
README.md e2e wrong instructions

### ISSUE THREAD

**Issue by slavede** [angular/angular-cli#7570]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.2
node: 6.11.2
os: win32 x64

### Repro steps.

generate a project with `ng new new-project`

### Desired functionality.

Currently e2e instruction say:

Run `ng e2e` to execute the end-to-end tests via [Protractor](http://www.protractortest.org/).
Before running the tests make sure you are serving the app via `ng serve`.

But serving the app is not necessary, it really works without it, just by running ng e2e, the app is being served:

```
λ ng e2e
** NG Live Development Server is listening on localhost:49152, open your browser on http://localhost:49152 **
Date: 2017-09-01T11:58:07.630Z
Hash: fbd01559c5c4c1f63b8b
Time: 8091ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.7 MB {inline} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 209 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 11.6 kB {inline} [initial] [rendered]
```

**Comment by filipesilva** [comment]
It is wrong indeed, now we automatically run serve. Would you be interested in making a PR to fix this? The readme is now located in https://github.com/angular/devkit/blob/master/packages/schematics/angular/application/files/README.md.

**Comment by slavede** [comment]
Will do

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
