### ISSUE TITLE
Watch for file changes when upload

### ISSUE THREAD

**Issue by jas75** [angular/angular-cli#7577]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.1
node: 8.4.0
os: darwin x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

### Repro steps.
https://github.com/jas75/Bloggy

### The log given by the failure.
A simple GET error 404

### Desired functionality.
When i upload a file i want angular to detect the file change without running ng serve 

### Mention any other details that might be useful.
My problem is that when I upload a file, Angular can detect it only if I run ng serve.  I couldn"t file  answers for this problem anywhere

**Comment by filipesilva** [comment]
I'm sorry but this isn't a Angular CLI bug. Angular CLI is not a production server. You have to architecture your server and client apps to trigger some sort of notification on file upload. Push notifications, polling and sockets are all viable options for this. I recommend searching the internet for options you can use, there are probably libraries that make this easy for your technology stack.
