### ISSUE TITLE
@angular/cli unable to find dependencies from ng2-admin in the package.json file

### ISSUE THREAD

**Issue by enlared** [angular/angular-cli#7581]
### Bug Report or Feature Request (mark with an `x`)
Currently, I'm trying to deploy a new app in a digitalocean droplet, after installing nodejs, npm and cloning the repository from git the following error log comes out:
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

node v6.11.2
npm  v3.10.10
Ubuntu 16.04.3 LTS

### Repro steps.

after cloning the repository I run the following commands:
sudo npm install
sudo npm start

After the error I tried different resolution to similar issues:
1. reinstalling npm:
sudo npm rm -g @angular/cli
npm cache clear
sudo npm install -g @angular/cli

2. Installing a clean version of ng2-admin:
sudo npm install -g ng2-admin

3. cloning the repository and installing dependencies locally:

git clone https://github.com/akveo/ng2-admin.git
cd ng2-admin
npm install

none solved the issue.

### The log given by the failure.

npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ng2-admin@1.0.0 start: `ng serve`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the ng2-admin@1.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/nova-kb/FrontEnd/SI-Saga/ng2-admin/npm-debug.log

### Desired functionality.

installing angular/cli in order to deploy the app

**Comment by filipesilva** [comment]
You should open an issue in the https://github.com/akveo/ng2-admin issue tracker instead, since that's the application you're using.

But if I had to bet it's because of you using `sudo npm install`, which is known to cause problems: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by enlared** [comment]
Thanks Filipe I already create the issue https://github.com/akveo/ng2-admin/issues/1265 since I'm working using root user therefore there's no need to change access rights with any other user.
