### ISSUE TITLE
Build should support es6 target in tsconfig

### ISSUE THREAD

**Issue by mmc41** [angular/angular-cli#7582]
- [x ] bug report -> please search issues before submitting
- [x ] feature request

As suggested by the article ["You might not need to transpile your JavaScript"](https://medium.freecodecamp.org/you-might-not-need-to-transpile-your-javascript-4d5e0a438ca) if one is targeting modern browsers than es6 should work as a target.

### Versions.
Angular 4.3.6
Angular cli 1.3.2

Change target in tsconfig.json to "es6"

```
ng build --bh /ui/ --prod --aot

_Date: 2017-09-02T18:56:38.448Z                                                             
Hash: 8032803bfa9cd5eeccc0
Time: 31830ms
chunk {0} polyfills.427414a5bc7cff210ba6.bundle.js (polyfills) 98.1 kB {4} [initial] [rendered]
chunk {1} main.65fe0ebc36062fa8f7ee.bundle.js (main) 945 kB {3} [initial] [rendered]
chunk {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 0 bytes {4} [initial] [rendered]
chunk {3} vendor.cce22225937a659c544a.bundle.js (vendor) 959 kB [initial] [rendered]
chunk {4} inline.1835379b8caad20d2658.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in main.65fe0ebc36062fa8f7ee.bundle.js from UglifyJs
Unexpected token: punc ()) [main.65fe0ebc36062fa8f7ee.bundle.js:94,12]_
```

### Desired functionality.
ES 6 target should build (and work in a modern browser)

**Comment by devoto13** [comment]
Support for ES6 is being tracked in https://github.com/angular/angular-cli/issues/2907. Please subscribe to that issue for further updates.

**Comment by filipesilva** [comment]
Closing as answered by @devoto13, thanks 👍
