### ISSUE TITLE
html-loader: Enable interpolation syntax for ES6 template strings

### ISSUE THREAD

**Issue by SteveVanOpstal** [angular/angular-cli#7589]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

html-loader has an option which handles the following syntax in html ([html-loader interpolate](https://github.com/webpack-contrib/html-loader#interpolation)):
``` FTL
<div>${require('./assets/logo.svg')}</div>
```

It allows you add resources to html, without the angular framework needing to interfere.

A specific usecase for me is the index.html where I add some html content to pass the [no-js lighthouse audit](https://developers.google.com/web/tools/lighthouse/audits/no-js). However adding for example a logo to that index.html is only possible when the Angular framework is loaded in, which limits me from using any asset.

**Comment by filipesilva** [comment]
I'm sorry but this is not something we want to add, that syntax is extremely webpack dependent and we try to keep non-standard syntax like that out of CLI projects to facilitate portability and understanding of CLI projects. 

For your case you might need to eject if that is essential for your project. Angular's `platform-server` (formerly Universal) would help as well. I've also written about a low-fidelity alternative in https://github.com/angular/angular-cli/issues/3013#issuecomment-316671895.
