### ISSUE TITLE
Add `rxjs/Rx` into `import-blacklist` in the default `tslint.json`

### ISSUE THREAD

**Issue by martinsik** [angular/angular-cli#7591]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
```
@angular/cli: 1.3.2
node: 8.4.0
os: darwin x64
```

### Desired functionality.

The default `tslint.json` generated prevents me from importing from `rxjs` such as:

```
import { Observable } from 'rxjs';
```

However it doesn't prevent me from using the following:

```
import { Observable } from 'rxjs/Rx';
```

This loads https://github.com/ReactiveX/rxjs/blob/master/src/Rx.ts file which means that importing `rxjs/Rx` is equivalent to `rxjs` (https://github.com/ReactiveX/rxjs/blob/master/.make-packages.js#L43).

I'd suggest to add `rxjs/Rx` into `import-blacklist` in the default `tslint.json`. I was trying to figure out where it comes from but I was not successful to be honest. Maybe this request should go into another repo?

**Comment by filipesilva** [comment]
Heya, the files you're looking to update are in https://github.com/angular/devkit/blob/master/packages/schematics/angular/application/files/tslint.json. Can you submit a PR there?

**Comment by CaerusKaru** [comment]
Can be closed by https://github.com/angular/devkit/pull/131

**Comment by filipesilva** [comment]
Thanks @CaerusKaru 👍

**Comment by pierre-hilt** [comment]
Hello, quick question. How can I get the tslint.json updated in my project? Do I have to do it manually? Or does a script exists? Thanks, Pierre

**Comment by filipesilva** [comment]
@pierre-hilt it has to be done manually.
