### ISSUE TITLE
Does not work operator in :- ng build --prod --aot

### ISSUE THREAD

**Issue by 02harleen** [angular/angular-cli#7594]
Hi, My error is:- src/$$_gendir/app/Global/Pagination/Pagination.component.ngfactory.ts (165,55): Operator '<=' cannot be applied to types 'boolean' and 'number'.
Angular version:- 4.3.3
Typescript version:- 2.4.2
I have no idea how to show this error. Please tell us how to solve it?

**Comment by filipesilva** [comment]
That error means that you're trying to use `<=` between a boolean and number in your `Pagination.component.ts` (or it's template), and you cannot do that (a boolean is not a number). Check your code and look for this usage, and replace the boolean with a number. There's more information about this class of errors in https://angular.io/guide/metadata.

**Comment by 02harleen** [comment]
I have replaced all boolean with the number but show the same error.
