### ISSUE TITLE
template: links not using rel="noopener"

### ISSUE THREAD

**Issue by markgoho** [angular/angular-cli#7595]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
1.3.2

### Repro steps.
`ng new` and `ng build` then run Lighthouse

### The log given by the failure.

![image](https://user-images.githubusercontent.com/9759954/30033477-8383059c-9169-11e7-9364-87249a7eb003.png)

### Desired functionality.
Links should be using rel="noopener"

**Comment by markgoho** [comment]
I'm happy to submit a PR for this, but I can't find the template files anywhere. Help?

**Comment by clydin** [comment]
They are now located in a separate package.  New source location: https://github.com/angular/devkit/tree/master/packages/schematics/angular

**Comment by markgoho** [comment]
Should I close this issue and put it in the devkit repo or does it make sense to keep track of it here too?

**Comment by filipesilva** [comment]
It makes sense to track it here as well IMHO. Could you open the PR in the new repro please?

**Comment by filipesilva** [comment]
Found it https://github.com/angular/devkit/pull/129

**Comment by markgoho** [comment]
Now under [angular/devkit#141](https://github.com/angular/devkit/pull/141)

**Comment by markgoho** [comment]
Merged in the PR listed above.
