### ISSUE TITLE
ngtools/webpack: document i18n parameters

### ISSUE THREAD

**Issue by bwasty** [angular/angular-cli#7599]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

The readme doesn't mention any i18n parameters, so we were quite surprised when translations were partially broken after adding the `AotPlugin`. Digging through the code a bit, we found that these parameters work:
```
  plugins: [
    new AotPlugin({
      ...
      locale: 'XX',
      i18nFile: helpers.root('src/locale/messages.XX.xlf'),
      i18nFormat: 'xlf',
    }),
  ]
```
Please document them. An open question is whether it's possible to generate a single bundle with all languages (that's what we're doing now without AOT). My guess after looking through the code is no.

**Comment by ocombe** [comment]
No you cannot a unique bundle yet, it'll be a new feature from v5.x (not 5.0, might be 5.1 or later, not sure yet)

**Comment by clydin** [comment]
The options are now documented within the [README](https://github.com/angular/angular-cli/blob/a9b947c28b8dac0edae32135d350f0efdea3fffe/packages/ngtools/webpack/README.md) of the plugin.
