### ISSUE TITLE
use styles in angular/cli, no styles in index.html

### ISSUE THREAD

**Issue by eminoda** [angular/angular-cli#7606]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

windows 10
node -v v6.10.1

### Repro steps.
my env：
http://chuantu.biz/t6/36/1504658009x2890149620.png

the result：no primeng css generate
http://chuantu.biz/t6/36/1504658074x2890149620.png

npm start have not error。

**Comment by startewho** [comment]
I have the same problem, and it seems include the cssf file in the `style.bundler.js` .But it doesn't work

**Comment by filipesilva** [comment]
Styles you add to the styles array will be processed, concatenated and output in a single bundle. `ng build` will generate a `styles.bundles.js` by default (it's JS for faster dev rebuilds), but `ng build --prod` will generate `styles.bundle.css`.

You can read more about differences between dev and prod builds in https://github.com/angular/angular-cli/wiki/build#--dev-vs---prod-builds. The flag that controls the CSS bundle is called `--extract-css`.

**Comment by eminoda** [comment]
i use ng build --prod --no-extract-license
there are not generate other style files
````
E:\my_work\github\angular-learn>npm run build

> angular-learn@0.0.0 build E:\my_work\github\angular-learn
> ng build --prod --no-extract-license

Date: 2017-09-07T00:13:50.514Z
Hash: 0f2665f08ffeaa673d6b
Time: 10607ms
chunk {0} polyfills.767d0e922dd8609d2506.bundle.js (polyfills) 64.1 kB {4} [initial] [rendered]
chunk {1} styles.d41d8cd98f00b204e980.bundle.css (styles) 0 bytes {4} [initial] [rendered]
chunk {2} main.cba04f43f2371a0df1ce.bundle.js (main) 1.93 kB {3} [initial] [rendered]
chunk {3} vendor.1df511d18488e8379350.bundle.js (vendor) 216 kB [initial] [rendered]
chunk {4} inline.b1dd1205397e629867a8.bundle.js (inline) 1.45 kB [entry] [rendered]
````
nothing in styles.d41d8cd98f00b204e980.bundle.css

**Comment by eminoda** [comment]
now I try to delete node_modules which installed by **cnpm**,when use npm install ,the project work fine.
the result：
http://chuantu.biz/t6/38/1504744165x2890149620.png

there are lots of style in index.html。
But i dont‘not that why angular/cli not support 'cnpm',may be the problem is cnpm
