### ISSUE TITLE
Changes made in module components under node_modules not reflected in prod build

### ISSUE THREAD

**Issue by ManojSethuraman** [angular/angular-cli#7609]
Hi,

I have added primeng module , in which I have made some changes by updating the templates for some of the components and edited the css files. The changes are getting reflected perfectly in dev build. But when prod build is done, I could not see them reflected.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
