### ISSUE TITLE
Multiple applications

### ISSUE THREAD

**Issue by Vayrex** [angular/angular-cli#761]
Hello.

I'm working on large project, and cuz of window load it will be usefull to divide app to submodules with own configuration. I was searching throught the docs but found nothing, regarding multiple applications.
As proposal, you can make such folders structure and use next commands.
ng child or ng subapp
ng child route subhero
/app
      /sub1.app/
      /sub2.app/
It can be very usefull when using some shared componets throught applications.

Thanks.

**Comment by hansl** [comment]
We already have a need for this for Material2, and some version of it will be supported soon.

Closing this for now.

**Comment by QuentinFchx** [comment]
@hansl could you provide more information about this feature ?
It prevents me from using the cli right now :/
Do you know if there is an ETA on it ? Will it make it to the final release of ng2 ?

**Comment by Vayrex** [comment]
@QuentinFchx As solution you can change some params in angular-cli.json.
` "defaults": {
    "prefix": "appName/app",
    "sourceDir": "src/appName"
  }`
@hansl Is there a way to change config file (meaning angular-cli.json) on fly ?

**Comment by vrustia-owens** [comment]
@Vayrex  Is this a workaround to allow supporting multiple builds or deployments?
