### ISSUE TITLE
Webpack: not loading font-awesome fonts

### ISSUE THREAD

**Issue by codeepic** [angular/angular-cli#7611]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.5
node: 7.10.0
os: win32 x64

Related to #[1463](https://github.com/angular/angular-cli/issues/1463)

I tried method mentioned by @omobono and @shri3k:

```
$fa-font-path: "~font-awesome/font";
@import "~font-awesome/scss/font-awesome";
```

and variations of it but it still doesn't work. After I build the project, I get 404 for the fonts. No matter what I put as $fa-font-path, they are being served from the root of the project.

**Comment by Chelayos** [comment]
working for me, tried today.
in my case it loads the font stuff from the same folder i specified for font-awesome.min.css

angular-cli.json
```
 "styles": [
"node_modules/font-awesome/css/font-awesome.min.css"
]
```

**Comment by codeepic** [comment]
In my case all the fonts are loaded into dist folder, but the css points to the wrong directory.

![font-awesome-fonts-not-loading](https://user-images.githubusercontent.com/6895033/30925282-41d94ce4-a3a9-11e7-83a0-823a60d2d87f.png)

So if you have a look in the above screenshot, on the left is the root folder location '/assets/accounts/dist' but if you look at the 404 error messages, the CSS tries to link to the fonts in the root - not in the '/assets/accounts/dist'.
I just need to figure out how to change the font urls in the css.

**Comment by elvinmeza** [comment]
I was facing the same issue, turns out a slash was missing for the base-ref parameter, at its end. Fixed it running the build command like this: ng build --base-href /myapp/ --deploy-url /myapp/

**Comment by codeepic** [comment]
@elvinmeza - yes, that fixes my problem.
Big thanks to @filipesilva for pointing me in the right direction.
So to explain how we resolved the issue.
I have the Angular 2 app running with Scala Play framework.
Front-end of the Play app is held in 'accounts' folder.

Hence in my 'accounts.scala.html' I have `<base href="/accounts" />`

Play framework serves all the static assets from  '/assets/accounts/dist/' folder.

When you run `ng build` the Angular-CLI will deploy all the files into 'dist' folder and the url paths in the css will also point to the dist folder - which is fine in most scenarios.

But when you open Play app in the browser, there is no directory like 'localhost/dist', so I was getting 404 for all fonts.

After I run `ng build --deploy-url /assets/accounts/dist/`
all the files including fonts are still output to the dist folder, but the `--deploy-url` flag changes the relative paths for all the assets that get referenced in css.
So now the url for the fonts in css stylesheet is: '/assets/accounts/dist/font-awesome.ttf';
