### ISSUE TITLE
npm ERR! 404 Not Found: @angular-devkit/schematics@~0.0.21

### ISSUE THREAD

**Issue by playground** [angular/angular-cli#7622]
npm install --save-dev @angular/cli  
npm ERR! code E404
npm ERR! 404 Not Found: @angular-devkit/schematics@~0.0.21

Running npm 5.3.0

**Comment by clydin** [comment]
It's published: https://www.npmjs.com/package/@angular-devkit/schematics
You can try checking you npm registry and proxy configuration.

**Comment by playground** [comment]
Strange it just started working.  Thanks.

**Comment by Brocco** [comment]
Glad it's working for you.
