### ISSUE TITLE
@ngtools/webpack : run type-checking in a separate thread

### ISSUE THREAD

**Issue by iuliust** [angular/angular-cli#7623]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
It would be nice if the CLI did all the type-checking in a separate process.
I don't know if it already does, but it would be great if it did.

### Mention any other details that might be useful.

The author of webpack talked about that idea (among other typescript performance enhancement possibilities) in the following blog post (it's worth a read) :
https://medium.com/webpack/typescript-webpack-super-pursuit-mode-83cc568dea79

Keep up the good work, you're awesome, I love you !

**Comment by filipesilva** [comment]
I'm actually working on that right now! You can see progress in https://github.com/angular/angular-cli/pull/7684.

That exact article go me very interested in the forked type checker and I have been looking at implementing it in a new compiler plugin we have for Angular 5 and up.

**Comment by iuliust** [comment]
Thanks, it's going to be even more awesome ♥️ multi-threading FTW
