### ISSUE TITLE
css import inside stylesheet with '~'  not working

### ISSUE THREAD

**Issue by EddyNll** [angular/angular-cli#7629]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli 1.4.0
Node v7.10.0
Windows 10

### Repro steps.

- Upgraded from 1.1.0 to 1.4.0

import stylesheet from node_modules inside styles.less: 

`@import "~@mystyling/styling/styles.less";`

This used to work in 1.1.0.

### Mention any other details that might be useful.

Seems like an issue with webpack.

**Comment by cedvdb** [comment]
works for me for scss. try this

@import "~@mystyling/styling/styles";

**Comment by endoodev1** [comment]
Same issue here with importing less files from bootstrap module. 

`@import '~bootstrap/less/responsive-utilities.less';`

Only updated angular-cli to 1.4.2.

`'~bootstrap/less/responsive-utilities.less' wasn't found. Tried -<absolute-Path-to-working-directory>/src/~bootstrap/less/responsive-utilities.less.`

 It seems as the "~" is not resolved as a node-module but as part of the folder name. With or without ".less" does not make any difference.

**Comment by kevfuzz** [comment]
Having the same issue. Was all working fine until updated to version 1.4.2.

**Comment by vandermore** [comment]
I have a project where this was actually working in the CLI version 1.7.4, but upon updating to 6.0.1 I get the error @endoodev1 is getting:

@import "~bootstrap-less/bootstrap/bootstrap.less";
^
'~bootstrap-less/bootstrap/bootstrap.less' wasn't found.

The thing that I see that may be significant, is the path that goes into the node_modules has the ~ before the bootstrap-less folder name:

<absolute url into project>\node_modules\~bootstrap-less\bootstrap\bootstrap.less

**Comment by filipesilva** [comment]
I'm closing this one as outdated but for the 6.x problem we are tracking it in https://github.com/angular/angular-cli/issues/10913
