### ISSUE TITLE
Changing root path in .angular-cli.json causes errors

### ISSUE THREAD

**Issue by dragonflypl** [angular/angular-cli#7631]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.4.0
node: 6.9.1
os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.0
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
typescript: 2.4.2
```

### Repro steps.

- generate app with `ng new`
- change `root` in `.angular-cli.json` to e.g. `"root": "src/main/client"`
- try to generate component `ng g c test`

### The log given by the failure.

```
Error: Path "src/main/client/" is invalid.
Path "src/main/client/" is invalid.
```

### Desired functionality.

Component should be generated

**Comment by clydin** [comment]
The root of the application needs to exist.  Was the path created before running the generate command?

**Comment by hansl** [comment]
I investigated and have a fix for this issue. It will be on the devkit side. Will link here.

**Comment by dragonflypl** [comment]
@clydin :  Path existed
