### ISSUE TITLE
PLEASE HELP Angular + leaflet incorrectly displayed tiles

### ISSUE THREAD

**Issue by SergeyBakin** [angular/angular-cli#7633]
### Bug Report
I try just to show map, but i have problem, tiles incorrectly displayed in the map. When i compile the project(`ng serve`) all good, no problem. I tried to launch on `Mac OS` and it worked correctly, on `Windows` and `Ubuntu` incorrectly. May be problem with webpack or 

### Versions.

`leaflet(v1.2), @types/leaflet(v1.2), angular/cli(v.1.3.2), @angular/core: (v4.3.6)typescript(v2.5.2), npm(v5.3, v5.4), OS: Ubuntu 16.04 x64`

**Comment by rikup88** [comment]
Sounds like you are missing Leaflet css.

**Comment by guilhermejcgois** [comment]
Did you insert leaflet style and script files on your app section at .angular-cli.json?

**Comment by rikup88** [comment]
I'm using Mapbox GL JS, but process should be quite similar with Leaflet. In .angular-cli.json I have mapbox-gl.js in "scripts" section and in my main scss file I have import for mapbox css. Hope this helps.

**Comment by SergeyBakin** [comment]
How...  I`m shocked. It is work. Thank you very much. 2 weeks tried to fix, i inserted style in component "styleUrls", because in angular-cli.json ("../node_modules/leaflet/dist/leaflet.css") get me error. I written just "leaflet.css" from ./src. Do you know how use "../node_modules/leaflet/dist/leaflet.css" in angular-cli.json?

**Comment by rikup88** [comment]
In .angular-cli.json I have the following:
`"styles": [
        "styles.scss"
      ],`

and in styles.scss I have
`
@import '../node_modules/mapbox-gl/dist/mapbox-gl.css';`

Just replace the mapbox css with leaflet css and you should be good. Nothing else is needed, at least with scss.

**Comment by SergeyBakin** [comment]
thanks
