### ISSUE TITLE
Changes in d.ts files are not detected by `ng serve`

### ISSUE THREAD

**Issue by devoto13** [angular/angular-cli#7638]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.1
node: 8.4.0
os: darwin x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.1
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
typescript: 2.3.4

### Repro steps.

1. Clone repo https://github.com/devoto13/ng-dts-changes
2. `ng serve`
3. Open http://localhost:4200 in browser
4. Open `app.component.ts` and use Refactor -> Rename to rename `myConst` to `myConst1`.
5. Go back to browser

### The log given by the failure.

Observe black screen saying `Module '"*****/src/app/some"' has no exported member 'myConst1'.` Although if you open `some.d.ts` file it actually has exported member `myConst1`.

### Desired functionality.

Changes in d.ts files are detected and I don't have to restart `ng serve` after editing those.

**Comment by hansl** [comment]
This is a known issue. We are in the process of rebuilding our build pipeline and will fix this. In the meantime I'll let this issue open as we might have contributors who want to tackle this for the current pipeline.

**Comment by devoto13** [comment]
With Angular 5.0.1 and Angular CLI 1.5.0 changes in d.ts files inside src are detected correctly. However changes in d.ts files inside node_modules are still not detected.

**Comment by tiaguinho** [comment]
@devoto13 I think to detect changes inside node_modules aren't something needed. If some package was added or updated, run ```ng serve``` again seems to be a better idea.
@hansl in my opinion, this issue can be closed.

**Comment by mgechev** [comment]
@tiaguinho yes, this sounds right. @devoto13, @tiaguinho thanks for the comments.
