### ISSUE TITLE
The alias of `named-chunks` is incorrect in docs

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular-cli#7640]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```
In page https://github.com/angular/angular-cli/wiki/build

It's described as: 
`--named-chunks (aliases: -nm)`

... but it should be:
`--named-chunks (aliases: -nc)`

**Comment by Brocco** [comment]
The fix for this issue lies in this file: https://github.com/angular/angular-cli/blob/master/docs/documentation/build.md

Down on line 363. (based on the current master branch)

**Comment by avatsaev** [comment]
Can I? Please?
