### ISSUE TITLE
ng build --prod not respecting environments

### ISSUE THREAD

**Issue by kahanu** [angular/angular-cli#7643]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```
The ng build --prod is not respected.  It does not set the proper production environment variable, so the dev properties are still used.

This is an Angular 4.x app built using the Angular/cli from the beginning, i.e: "App Works".

### Versions.

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / ? \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 7.8.0
os: win32 x64

### Repro steps.

environments/environment.ts

```
const LOCALHOST = 'http://localhost:58810/api/';

export const environment = {
  production: false,
  Api: LOCALHOST
};
```

environments/environment.prod.ts

```
const ENDPOINT = 'https://my.azurewebsites.net/api/';

export const environment = {
  production: true,
  Api: ENDPOINT
};
```

In my header component I have the console.log of the environment:

```
import { environment } from './../../../../environments/environment';
import { Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { config } from './../../shared.config';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  version: string;
  env: string;

  constructor(
    private _router: Router
  ) { }

  ngOnInit() {
    this.version = config.version;
    console.log('env: ', environment.Api);
  }


  onLogout() {
    this._router.navigate(['/auth/login']);
  }

}
```

ng build --prod --aot=false

### The log given by the failure.

No stack trace, but when I console.log the environment setting when deployed to Azure production, the result is:  env:  http://localhost:58810/api/

### Desired functionality.

I would like to see the environment variable feature work.  Let me know if I'm doing something wrong.

**Comment by Nexucis** [comment]
Hello,

If you look at [this issue](https://github.com/angular/angular-cli/issues/7118), someone mention this effect, and the result is maybe because you set the aot parameter to false. Try with aot=true.

**Comment by kahanu** [comment]
AOT doesn't work either.

ng build --prod --aot

Lot's of errors, this is just the first two of many:

```
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\King\Source\Repos\DonorServices.UI.CallDesk\src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

ERROR in ./src/$$_gendir async
Module not found: Error: Can't resolve 'C:\Users\King\Source\Repos\DonorServices.UI.CallDesk\src\$$_gendir\app\+dashboard\dashboard.module.ngfactory.ts' in 'C:\Users\King\Source
\Repos\DonorServices.UI.CallDesk\src\$$_gendir'
 @ ./src/$$_gendir async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts

```

BTW, also ng serve --prod also breaks.  I'd like to sometimes check the production build before deploying it to the production server, but I can't, at least not this way.

I'll look at that issue and see if it has some solutions.  But do you have any other ideas?

Is this a known bug?

**Comment by kahanu** [comment]
@Nexucis - I looked at this issue and it does not resolve my issue.  The result is the same.  Also my package.json already had the enhanced-resolve@3.3.0 package and it never did any good.  I even uninstalled it and then reinstalled it and there was no change in the build results.

Do you know if any of the actual Angular developers monitor these issues?  This seems like a pretty big one.

Do you or anyone else have any other suggestions?

**Comment by ankeshdave** [comment]
@kahanu try upgrading to `ng - cli` to `1.3.2` and try `ng build --env prod` or if you are using `Aot` then `ng build -prod`

**Comment by Nexucis** [comment]
@kahanu in 1.4.1, I do not have the environment problem with the cmd `ng build --prod --aot=false`, but yes like you, I can't build my own application with the aot parameter.

**Comment by kahanu** [comment]
It works!  Ok, upgrading my in-app cli to 1.4.1 and also upgrading some other modules, and the app level typescript did the trick for me.  I had 1.4.1 for my global cli, but my in-app cli was 1.2.1.

ng serve - works!
ng serve --prod - works!
ng serve --prod --aot - works!
ng build --prod - works!
ng build --prod --aot --works!

And the really beautiful thing is that they all respect the environment variables.  Yay!  

Thanks both of you.
