### ISSUE TITLE
Infinite install loop

### ISSUE THREAD

**Issue by AmitMY** [angular/angular-cli#7645]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.4.1

### Repro steps.
`sudo npm install -g @angular/cli@latest`

### The log given by the failure.
The following repeats itself forever:
> gyp verb command install [ '8.4.0' ]
> gyp verb install input version string "8.4.0"
> gyp verb install installing version: 8.4.0
> gyp verb install --ensure was passed, so won't reinstall if already installed
> gyp verb install version not already installed, continuing with install 8.4.0
> gyp verb ensuring nodedir is created /usr/lib/node_modules/@angular/cli/node_mod                                               ules/node-sass/.node-gyp/8.4.0
> gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr                                               /lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.4.0"
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_m                                               odules/@angular/cli/node_modules/node-sass/.node-gyp"
> gyp verb tmpdir == cwd automatically will remove dev files after to save disk sp                                               ace

### Desired functionality.
Install to be working

### Mention any other details that might be useful.
1.3.2 was working.
I am on Ubuntu E2 on AWS.

**Comment by AmitMY** [comment]
Tried without `@latest`, works now, so nevermind

**Comment by AmitMY** [comment]
Now it works, finishing to install with saying:

```
 + @angular/cli@1.4.1
 added 114 packages and updated 1 package in 11.718s

```
But if I do `ng --version` I get

```
@angular/cli: 1.3.2
node: 8.4.0
os: linux x64
```

**Comment by brunoc107** [comment]
I am still having this trouble.
The same way you've decribed.

**Comment by benjaminhorner** [comment]
+1

**Comment by Brocco** [comment]
@AmitMY the version of the CLI reported may be from the local project, not your global version.

Unfortunately there's not a whole lot we can do regarding failing or long-running npm installs. You could try reaching out to the npm team.

**Comment by NotoriousWebmaster** [comment]
Had the same issue installing globally. But when I asked for the version with `ng --version` it ran, and told me it wasn't installed in my local project. So I installed it locally, and that ran fine.

**Comment by harilal** [comment]
i had the same issue in my Fedora 26. It runs a inifinite loop while installing angular.cli. It says doesn't have permission in node-sass . So wat i did was tried once more the npm install -g  and then removed the node_modules from /usr/lib/node_modules/@angular/cli/ and run npm install .

This time the node-gyp bin downloaded successfully and run perfectily. Its some kind of isse with node-sass . The Error is `ensuring nodedir is created /usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.7.0
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.7.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
`

**Comment by AdamMirza** [comment]
I have this same issue on the newest version of Node. I was able to install after switching from version 8.7.0 to the latest stable version 6.11.4.

**Comment by rjenks** [comment]
Same issue on my Mac.  After a few hours of digging, I found that right before the loop starts it can't find python 2 on my system.  After installing python with "brew install python", I was able to install angular/cli.

Seems like the real issue is that the angular/cli install depends on python 2, doesn't bother to check to see if you have it installed, and continues on blissfully into eternity without it.

**Comment by citizentim** [comment]
Further to @rjenks comment, I ran into the same problem on my Mac, but I am using MacPorts instead of HomeBrew.  The python2 symlink was already there but not in root's PATH.  For an unknown reason, running npm with sudo didn't work, so I had to sudo to root.  The fix for me was:

```
sudo su -
PATH=/opt/local/bin:/opt/local/sbin:$PATH
npm install -g @angular/cli@<version>
```

**Comment by polyglotinc** [comment]
So, what do we have to do about this?? I don't explicitly use Python on my Mac, so therefore have never explicitly installed it....seems like that's what npm, et al, is supposed to do!
I too am getting the loop of death trying to upgrade from angular cli 1.2 to latest.

**Comment by citizentim** [comment]
Try adding the -unsafe-perm switch. I can’t remember whether it’s one hyphen or two. It really needs to be officially documented.

**Comment by mondlos** [comment]
These are the workarounds I used to install angular-cli:
1. https://stackoverflow.com/a/45536820
2. add -unsafe-perm - thx to @citizentim

**Comment by stejo009** [comment]
Anyone have command to install cli without any error?

**Comment by citizentim** [comment]
@stejo009 I believe it has already been mentioned. 

`sudo npm install -g @angular/cli -unsafe-perm`
