### ISSUE TITLE
Using an absolute deployUrl breaks the 'scripts' bundle url in index.html

### ISSUE THREAD

**Issue by deanfischer** [angular/angular-cli#7650]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.1
node: 7.10.1
os: darwin x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/compiler-cli: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.1
typescript: 2.2.2

### Repro steps.

.angular-cli.json: (Note the absolute deployUrl with https://)

```
"apps": [
    {
      "root": "src",
      "outDir": "target/my-app",
      "deployUrl": "https://someplace.cloudfront.net",
      "assets": [],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "tsconfig": "tsconfig.app.json",
      "styles": [
        "styles.css"
      ],
      "scripts": [
        "../node_modules/some-libs/file.js",
      ]
    }
  ]
```

After I run ng build --prod, index.html looks like this:

...
```
<body>
    <my-app></my-app>
    <script type="text/javascript" src="https://someplace.cloudfront.net/inline.6cca322f7e258972d83b.bundle.js"></script>
    <script type="text/javascript" src="https://someplace.cloudfront.net/polyfills.1f88e2c5c51b2654c108.bundle.js"></script>
    <!-- BROKEN starts with https:/ (one slash) instead of https:// -->
    <script type="text/javascript" src="https:/someplace.cloudfront.net/scripts.4b3dfabee60e0d1b2077.bundle.js"></script>
    <script type="text/javascript" src="https://someplace.cloudfront.net/vendor.7e4452b3f0246d32e944.bundle.js"></script>
    <script type="text/javascript" src="https://someplace.cloudfront.net/main.4f222f38a3c2a53f4f40.bundle.js"></script>
</body>
```
...

### Desired functionality.
The script tag should start with https:// rather than https:/ <---- one slash not two

### Mention any other details that might be useful.
Similar to #7628 which was fixed a couple of days ago with #7634

**Comment by hansl** [comment]
My bad, I know what the error is. I'll fix it right away. Thanks for reporting.
