### ISSUE TITLE
Browsersync

### ISSUE THREAD

**Issue by JoshuaNovak919** [angular/angular-cli#766]
Sorry, this isn't really an issue, more of a question, but I couldn't find a good place to ask this. I want to switch out `LiveReload` for `Browsersync`, what is the proper way to go about this for Angular CLI?

**Comment by pkamdem** [comment]
@JoshuaNovak919 

Is there any advantage for switching to Browsersync that is worth mentioning here?

The CLI is currently using [ember-cli-inject-live-reload](https://github.com/rwjblue/ember-cli-inject-live-reload) plugin to leverage live-reload core feature when serving app.

You can still delete the reference of live-reload file on index.html and start your own server which should then have to watch from ./dist folder.

**Comment by JoshuaNovak919** [comment]
@pkamdem Browsersync works better, looks better (shows if it's syncing in the browser window), and has more features than LiveReload at least from my experience. I'll try deleting the live-reload reference and add in Browersync and see if I can get it working.

**Comment by JoshuaNovak919** [comment]
In case anyone else is wondering. I ended up using:
https://github.com/johnpapa/lite-server

I removed the LiveReload line from the dist/index.html and added a bs-config.json file to the root of the project.

bs-config.json
```
{
  "port": 8000,
  "files": ["./dist/**/*.{html,htm,css,js}"],
  "server": { "baseDir": "./dist" }
}
```

**Comment by pkamdem** [comment]
@JoshuaNovak919 

Well ok, if this bring the smile back !
Thanks for sharing by the way

I think this issue can now be closed

**Comment by JoshuaNovak919** [comment]
@pkamdem Actually it looks like the code is not updating when I save it. I have it watching the dist folder, which doesn't seem to be updating now. Is there something else I need to do for this to happen?

**Comment by pkamdem** [comment]
Actually you would still need to start both commands

``lite-server`` and ``npm start``

The ./dist folder is destroyed and recreated each time a change is detected on your code base. This will trigger your lite-server reload on _http://localhost:8000/_.

**Comment by JoshuaNovak919** [comment]
@pkamdem That worked. I added `concurrently` and changed start to `"start": "concurrently \"ng server\" \"npm run lite\" ",`. This runs both servers at once though. Is there a way to have the dist directory rebuild when there is a change and not start the server?

**Comment by pkamdem** [comment]
You need start the CLI one to monitor your trees and act upon changes.
It certainly exists a way to tweak as you want.
I would suggest you a more appropriate medium, let's say the official [CLI Gitter Chat](https://gitter.im/angular/angular-cli?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by hansl** [comment]
Closing this as it's not an issue.
