### ISSUE TITLE
Vulnerabilities in packages that CLI depends on (auditjs)

### ISSUE THREAD

**Issue by adamlubek** [angular/angular-cli#7660]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.1
node: 6.9.5
os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.1
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
typescript: 2.3.4

### Repro steps.
-> Generate new app using CLI (ng new sample-app)
-> Install auditjs https://www.npmjs.com/package/auditjs
-> Run auditjs inside generated sample-app

### The log given by the failure.
auditjs outputs vulnerabilities in:
handlebars 1.3.0
uglify-js 2.3.6
sockjs 0.3.18
ws 1.1.2

### Desired functionality.
No vulnerabilities in packages used by Angular CLI based app. 

All of the packages that are highlighted as vulnerable are used under the hood by angular CLI so we can't just update them easily ourselves. This is crucial for enterprise application though, that packages that app depends on are free of known vulnerabilities. We are looking for CLI to be updated to use latest versions of packages which are free of vulnerabilities.

**Comment by hansl** [comment]
Hi @adamlubek,

Thanks for reporting this. I looked at auditjs output;

* handlebars 1.3.0. This comes from postcss-url, and we have no control over it. The good news is I don't know why they depend on 1.3 which is really old.
* uglify-js 2.3.6. These are all injection when using uglify, and dependent on the project's code. This is relatively serious, but we're in the process of upgrading uglify-js to the latest version so it will be fixed soon.
* sockjs 0.3.18. This is used by webpack-dev-server, which we do not recommend already to run in production or any server visible from the internet. CORS in a dev environment is less severe, but we should keep an eye on it. We'll let the webpack-dev-server know.
* ws 1.1.2. WebSocket has insufficient randomization, but like sockjs we only use it for development environment, and as such the severity of this is relatively low.

Please include the details next time you run an audit.

Thanks a lot for this. It will make our project more secure in the future.

I'm closing this with follow ups about sockjs to the webpack-dev-server team.
