### ISSUE TITLE
ng serve not refreshing after syntax error

### ISSUE THREAD

**Issue by phmello** [angular/angular-cli#7664]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.1
node: 7.10.0
os: darwin x64
@angular/animations: 4.4.0-RC.0
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.4.0-RC.0
@angular/compiler: 4.4.0-RC.0
@angular/core: 4.4.0-RC.0
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.4.0-RC.0
@angular/http: 4.4.0-RC.0
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.4.0-RC.0
@angular/platform-browser-dynamic: 4.4.0-RC.0
@angular/router: 4.4.0-RC.0
@angular/cli: 1.4.1
@angular/compiler-cli: 4.4.0-RC.0
@angular/language-service: 4.4.0-RC.0
typescript: 2.5.2

### Repro steps.
ng serve and generate a syntax error.

### Desired functionality.
ng should refresh

**Comment by then3rdman** [comment]
Same issue here. Is it related to the typescript version? I notice you running 2.5.2. I might try running it with a pre 2.4 version and see if that makes a difference.

**Comment by mehrad-rafigh** [comment]
@then3rdman It tried `typescript@2.3.4` but it doesn't make a difference

**Comment by rajdeep26** [comment]
I think i am also facing this issue. `ng serve` stops compiling after i upgraded from `1.3.2` to `1.4.1`

Versions:
```
  " @angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
 "devDependencies": {
    "@angular/cli": "^1.4.1",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
```

**Comment by alexjlockwood** [comment]
Was having the same issue. Downgrading my typescript version from 2.5.2 to 2.4.2 seemed to workaround the issue, as suggested above.

**Comment by filipesilva** [comment]
Heya, can you provide me with a reproduction I can follow on a new project to see this happening?

**Comment by phmello** [comment]
Hey @filipesilva,
I think the way to reproduce is, create a syntax error before ng serve.
if your code is correct the first time, everything works fine, the problem is when you have an error from the start.

**Comment by azarus** [comment]
**BUMP!!!**
I experience the same issue after splitting my application into submodules. The application was recompiling fine after any syntax error. Now after a syntax error i constantly get errors.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
