### ISSUE TITLE
declare one component in two apps module and build on prod report error

### ISSUE THREAD

**Issue by yokots** [angular/angular-cli#7669]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.

macOS Sierra: 10.12.6
cli: 1.4.1
angular: 4.3.6
node: 8.4.0
npm: 5.4.1

### Repro steps.

I use a component between two app, app0 and app1, when I build app1 with `--prod --build-optimizer`, it report an error that **Type XComponent is part of the declarations of 2 modules**. If build app1 just use `ng build --app=1` without other arguments, it will build success. I know that a component can't declare on 2 modules in one app, it should declare at shared module, but this is in two apps, I think it should not report the error. Now I export XXComponent extend XComponent like [this](https://github.com/angular/angular/issues/10646#issuecomment-239181520), and I import XComponent at app0, import XXComponent at app1 to cheat angular. I hope get some help about this.

**Comment by hansl** [comment]
Are you including files from app 1 in the `tsconfig.json` for app 0? That might explain the message.

**Comment by yokots** [comment]
All the files are in src, src/app0 and src/app1, how to configure the tsconfig.json shuold i?

**Comment by filipesilva** [comment]
@yokots you can configure the `files`, `include` and `exclude` properties of a tsconfig file to control which ts files are included in that app compilation. In your case you will to exclude modules from app1 in app0 and vice versa. 

Remember to edit the right tsconfig, the default  one is `src/tsconfig.app.json` but you should have one of each of your apps.

You can read more about tsconfig files here: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html.
