### ISSUE TITLE
routerLinkActive doesnt work properly

### ISSUE THREAD

**Issue by wandri** [angular/angular-cli#7670]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Windows 10
@angular/cli : 1.4.1
@angular 4.2.4

### Repro steps.

The bug is about the routerLinkActive. When the app starts, the routerLinkActive doesnt work with angualr Cli. But it works without on this demo: https://plnkr.co/7KMlY2?p=preview

(The white background is displayed when the link is activated)

To understand:

The Tree
![tree-git](https://user-images.githubusercontent.com/15016833/30341632-0b3608f2-97f7-11e7-9411-81d782f1fa0a.jpg)

It's said that RouterLinkActive is true

![tree-git-1](https://user-images.githubusercontent.com/15016833/30341655-1f99f268-97f7-11e7-9112-8b084e74c833.jpg)

But in the DOM, the class isn't displayed.

![tree-git-2](https://user-images.githubusercontent.com/15016833/30341676-3655c16c-97f7-11e7-9fa3-5b33f6591f06.jpg)

I have done a zip with the same contant than the Plunker but with ng-cli.

[routerLinkNotWorking.zip](https://github.com/angular/angular-cli/files/1296983/routerLinkNotWorking.zip)

### The log given by the failure.

There is no error thrown.

### Desired functionality.

It musst work like in the plunker. The class active musst be displayed in the DOM.

**Comment by Destreyf** [comment]
Just going to leave a heads up, the ZIP you provided uses angular 4.X.X while the plunker appears to use angular 2.X.X.  functionally it should work the same however.

I also noticed in you've got the routerLinkActive="active" on the LI (on both zip and plunker) i don't think that this will work as the routerLinkActive wouldn't know which element it was associated with.  This may be a question for the angular/angular repo as i don't believe it has to do with the cli directly.

**Comment by hansl** [comment]
Hi @wandri ,

This seems to be a bug with Angular itself. This is the repository for Angular CLI. If you can reproduce this on plnkr, it is not related to the CLI.

You can file an issue for Angular itself here: http://github.com/angular/angular/issues/new

Cheers!

**Comment by Destreyf** [comment]
@hansl his argument was that it wasn't reproducible on plunkr, however the plunkr is angular 2.0.0 and his zip is 4.X.X

**Comment by wandri** [comment]
Sorry for the inconveniant. And thanks to have noticed that the plunker was on angular 2. My bad. I have redone it with angular 4 and this is not working so endeed, this is Angular Problem. Thanks and have a good day.

**Comment by wandri** [comment]
And just to give a hack to make it works:

`[routerLinkActive]="" [ngClass]="rla.isActive?'active':''"  #rla="routerLinkActive"`

https://github.com/angular/angular/issues/19167
