### ISSUE TITLE
EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by ssashok10** [angular/angular-cli#7681]
I am getting the similar error when I tried to install with Angular 4.2.4 [ npm i ag-grid --save ]. My node version is 8.4.0 and npm version is 5.4.1. The installation is conflicting something with "fsevents"...I even tried to use the command "npm cache clean --force"...Here is the error,

npm ERR! path I:\git\AngularAppSample\node_modules
fsevents\node_modules\abbrev\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'I:\git\AngularAppSample\node_modules\fsevents\node_modules\abbrev\package.j
son'
npm ERR! { Error: EPERM: operation not permitted, unlink 'I:\git\AngularAppSamplenode_modules\fsevents\node_modules\abbrev\packag
e.json'
npm ERR! stack: 'Error: EPERM: operation not permitted, unlink 'I:\git\AngularAppSample\node_modules\fsevents\node_modul
es\abbrev\package.json'',
npm ERR! errno: -4048,
npm ERR! code: 'EPERM',
npm ERR! syscall: 'unlink',
npm ERR! path: 'I:\git\AngularAppSample\nod
e_modules\fsevents\node_modules\abbrev\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\sath\AppData\Roaming\npm-cache_logs\2017-09-12T21_37_0
9_061Z-debug.log

**Comment by wynhou** [comment]
I'm having the same issue. Latest NPM / Nodejs / Yarn

**Comment by andrexx** [comment]
It's a known NPM 5.4 issue. Downgrade to 5.3.
https://github.com/npm/npm/issues/18380

**Comment by ssashok10** [comment]
Hello, This issue is fixed once I cleaned up the node_modules folder completely and re-import all the packages again. I am using NPM 5.4.1. Thank you for your suggestion.

**Comment by jishnudev** [comment]
Same error 

npm ERR! path C:\Users\Jishnu\Desktop\my-app\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\Users\Jishnu\Desktop\my-app\node_modules\fsevents\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\Users\Jishnu\Desktop\my-app\node_modules\fsevents\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\Jishnu\\Desktop\\my-app\\node_modules\\fsevents\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\Users\\Jishnu\\Desktop\\my-app\\node_modules\\fsevents\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jishnu\AppData\Roaming\npm-cache\_logs\2017-10-19T02_38_07_564Z-debug.log

Package install failed, see above.
Package install failed, see above.

**Comment by andrexx** [comment]
@jishnudev  Try to close your IDE and execute again from console.

**Comment by rafaelzuckerberg** [comment]
@andrexx  thanks for your help, in my case I closed all prompt IDE etc and run again its work

**Comment by navalrawat** [comment]
Thanks @ssashok10  . It's Resolve after deleting node_modules folder and install all node packages again.

**Comment by saleemmalikraja** [comment]
try deleting the node_modules and install the dependencies again...!

**Comment by timsar2** [comment]
close id, and reinstall worked for me.

**Comment by patelvasu** [comment]
1. Run  command prompt as Administrator.
2. Ran npm clean cache.
        After run this command and return Error than run .
      **(  npm cache clean --force )**
3.  **npm install -g angular-cli**

**Comment by peng2013** [comment]
I am getting the similar error when I tried to install with Angular 6.0. My node version isv8.11.3 and npm version is6.1.0. The installation is conflicting something with "fsevents"...I even tried to use the command "npm cache clean --force"...Here is the error,

26322 warn @swimlane/ngx-dnd@5.0.6 requires a peer of @types/dragula@^2.1.33 but none is installed. You must install peer dependencies yourself.
26323 warn optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.9.3 (node_modules\node-sass):
26324 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'H:\angular-material-app-master\node_modules\.staging\node-sass-849c4ff0'
26325 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
26325 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
26326 verbose stack Error: EPERM: operation not permitted, unlink 'H:\angular-material-app-master\node_modules\.staging\@angular\compiler-f002f831\bundles\compiler.umd.min.js.map'
26327 verbose cwd H:\angular-material-app-master
26328 verbose Windows_NT 10.0.17134
26329 verbose argv "F:\\node\\install\\node.exe" "C:\\Users\\peng\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
26330 verbose node v8.11.3
26331 verbose npm  v6.1.0
26332 error path H:\angular-material-app-master\node_modules\.staging\@angular\compiler-f002f831\bundles\compiler.umd.min.js.map
26333 error code EPERM
26334 error errno -4048
26335 error syscall unlink
26336 error Error: EPERM: operation not permitted, unlink 'H:\angular-material-app-master\node_modules\.staging\@angular\compiler-f002f831\bundles\compiler.umd.min.js.map'
26336 error  { Error: EPERM: operation not permitted, unlink 'H:\angular-material-app-master\node_modules\.staging\@angular\compiler-f002f831\bundles\compiler.umd.min.js.map'
26336 error   cause:
26336 error    { Error: EPERM: operation not permitted, unlink 'H:\angular-material-app-master\node_modules\.staging\@angular\compiler-f002f831\bundles\compiler.umd.min.js.map'
26336 error      errno: -4048,
26336 error      code: 'EPERM',
26336 error      syscall: 'unlink',
26336 error      path: 'H:\\angular-material-app-master\\node_modules\\.staging\\@angular\\compiler-f002f831\\bundles\\compiler.umd.min.js.map' },
26336 error   stack: 'Error: EPERM: operation not permitted, unlink \'H:\\angular-material-app-master\\node_modules\\.staging\\@angular\\compiler-f002f831\\bundles\\compiler.umd.min.js.map\'',
26336 error   errno: -4048,
26336 error   code: 'EPERM',
26336 error   syscall: 'unlink',
26336 error   path: 'H:\\angular-material-app-master\\node_modules\\.staging\\@angular\\compiler-f002f831\\bundles\\compiler.umd.min.js.map',
26336 error   parent: 'angular-material-app' }
26337 error The operation was rejected by your operating system.
26337 error It's possible that the file was already in use (by a text editor or antivirus),
26337 error or that you lack permissions to access it.
26337 error
26337 error If you believe this might be a permissions issue, please double-check the
26337 error permissions of the file and its containing directories, or try running
26337 error the command again as root/Administrator (though this is not recommended).
26338 verbose exit [ -4048, true ]

**Comment by peng2013** [comment]
I try to do with administrator,but also error

**Comment by peng2013** [comment]
npm http fetch GET 200 https://registry.npmjs.org/smart-buffer 13221ms
npm http fetch GET 200 https://registry.npmjs.org/concat-stream 134206ms
npm WARN tarball tarball data for https://registry.npmjs.org/grpc/-/grpc-1.13.1.tgz (sha512-yl0xChnlUISTefOPU2NQ1cYPh5m/DTatEUV6jdRyQPE9NCrtPq7Gn6J2alMTglN7ufYbJapOd00dvhGurHH6HQ==) seems to be corrupted. Trying one more time.
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 1824274ms
npm ERR! path C:\Users\peng\AppData\Local\Temp\npm-4672-a4c6ef20\unpack-ae2ffde8\deps\grpc\src\boringssl\crypto_test_data.cc
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\peng\AppData\Local\Temp\npm-4672-a4c6ef20\unpack-ae2ffde8\deps\grpc\src\boringssl\crypto_test_data.cc'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\peng\AppData\Local\Temp\npm-4672-a4c6ef20\unpack-ae2ffde8\deps\grpc\src\boringssl\crypto_test_data.cc'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\peng\AppData\Local\Temp\npm-4672-a4c6ef20\unpack-ae2ffde8\deps\grpc\src\boringssl\crypto_test_data.cc'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'C:\\Users\\peng\\AppData\\Local\\Temp\\npm-4672-a4c6ef20\\unpack-ae2ffde8\\deps\\grpc\\src\\boringssl\\crypto_test_data.cc' },
npm ERR!   isOperational: true,
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\peng\\AppData\\Local\\Temp\\npm-4672-a4c6ef20\\unpack-ae2ffde8\\deps\\grpc\\src\\boringssl\\crypto_test_data.cc\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\peng\\AppData\\Local\\Temp\\npm-4672-a4c6ef20\\unpack-ae2ffde8\\deps\\grpc\\src\\boringssl\\crypto_test_data.cc',
npm ERR!   parent: '@firebase/firestore' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
npm timing npm Completed in 1829064ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\peng\AppData\Roaming\npm-cache\_logs\2018-08-19T15_15_24_624Z-debug.log

H:\angular-material-app-master>

**Comment by markwhitfeld** [comment]
I was able to fix this by running the command prompt/bash as admin and closing VSCode!
Seems like VSCode was locking some files.
Potentially something else could be locking these files for you.

**Comment by kinny94** [comment]
> @jishnudev Try to close your IDE and execute again from console.

you da man!!

**Comment by Rouhollah** [comment]
you must checkout this files if you are working on source control.
package.json , angular.json, app.module.ts
this way worked for me.

**Comment by abhijithcraj** [comment]
While opening the solution in Visual Studio is locking some configuration files. So sometimes it shows this type of errors. Close the solution opened in VS Code Or any other editor and run the command from cmd prompt will solve the issue.

For running the command from cmd prompt, Just go to your project folder then press Shift + Right-Click then click Open command window here. Then type the npm install...
