### ISSUE TITLE
ng new --skip-git is ignored

### ISSUE THREAD

**Issue by rol-dave-overall** [angular/angular-cli#7686]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.1
node: 6.11.2
os: win32 x64

### Repro steps.
Execute ng new <project> --directory . --skip-git  in a folder which already contains a .gitignore file reports the error. Alternatively execute  ng new <project> --skip-git and upon looking in the folder a .gitignore file is still created.

### The log given by the failure.
error! .gitignore already exists.

### Desired functionality.
The ng new command should comply with the --skip-git option and not attempt to create a .gitignore file.

This was not an issue is version 1.3.2 and therefore must be a regression bug

**Comment by ADTC** [comment]
This was deliberate? 😱 Please see #8638 because I think there is a good use case for creating `.gitignore` file when it _doesn't_ exist.
