### ISSUE TITLE
Angular 2 : How to lazy load node_modules dynamically based on requested URL

### ISSUE THREAD

**Issue by sowmya108** [angular/angular-cli#7688]
lets say i have different versions of my library like -

> player library has the following

   

> |-player1
>        |-config.json
>        |-player1.module.ts
>        |-player1.component.ts

 

>   |-player2
>        |-config.json
>        |-player2.module.ts
>        |-player2.component.ts

How can i load player1 version of library if requested URL is xyz.com/p1 and player2 for xyz.com/p2.

**Comment by SanderElias** [comment]
@sowmya108 This question has nothing to do with the CLI. I think your question is [answered in the docs](https://angular.io/guide/router#milestone-6-asynchronous-routing) [and here](https://angular.io/guide/ngmodule#lazy-loading-modules-with-the-router)

If you still don't get it going you can ask in the [support group](https://groups.google.com/forum/#!forum/angular), or on SO
