### ISSUE TITLE
[1.4.x] ng new angtest --source-dir not working as expected

### ISSUE THREAD

**Issue by riyasat** [angular/angular-cli#7692]
```
- [x ] bug report -> please search issues before submitting
```
### Description
When we create new project with angular cli v 1.4.1 with different source folder name. The new angular cli puts only app folder in main directory. It should replace src folder with desired folder in this case **main** and rest should be remain same as it was in older versions.

```
Output from: `ng --version`. 
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.1
node: 8.5.0
os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6


```

### Repro steps.

```
- npm install -g @angular/cli@latest
- ng new angtest --routing -si -st --source-dir main

```
**After running following command.**
`ng new angtest --routing -si -st --source-dir main`

### See the directory structure.

> 
> installing ng
>   create .editorconfig
>   create README.md
>   **create main\app\app-routing.module.ts
>   create main\app\app.component.css
>   create main\app\app.component.html
>   create main\app\app.component.ts
>   create main\app\app.module.ts
>   _create src\assets\.gitkeep
>   create src\environments\environment.prod.ts
>   create src\environments\environment.ts
>   create src\favicon.ico
>   create src\index.html
>   create src\main.ts
>   create src\polyfills.ts
>   create src\styles.css
>   create src\test.ts
>   create src\tsconfig.app.json
>   create src\tsconfig.spec.json
>   create src\typings.d.ts_**
>   create .angular-cli.json
>   create e2e\app.e2e-spec.ts
>   create e2e\app.po.ts
>   create e2e\tsconfig.e2e.json
>   create .gitignore
>   create karma.conf.js
>   create package.json
>   create protractor.conf.js
>   create tsconfig.json
>   create tslint.json
> Successfully initialized git.
> Project 'angtest' successfully created.

### Desired functionality.
#When we use --source-dir then all app source should be in the same folder as it was before angular cli 1.4.1

> 
> installing ng
>   create .editorconfig
>   create README.md
>   **create main\app\app-routing.module.ts
>   create main\app\app.component.css
>   create main\app\app.component.html
>   create main\app\app.component.ts
>   create main\app\app.module.ts
>   create main\assets\.gitkeep
>   create main\environments\environment.prod.ts
>   create main\environments\environment.ts
>   create main\favicon.ico
>   create main\index.html
>   create main\main.ts
>   create main\polyfills.ts
>   create main\styles.css
>   create main\test.ts
>   create main\tsconfig.app.json
>   create main\tsconfig.spec.json
>   create main\typings.d.ts**
>   create .angular-cli.json
>   create e2e\app.e2e-spec.ts
>   create e2e\app.po.ts
>   create e2e\tsconfig.e2e.json
>   create .gitignore
>   create karma.conf.js
>   create package.json
>   create protractor.conf.js
>   create tsconfig.json
>   create tslint.json
> Successfully initialized git.
> Project 'angtest' successfully created.

Riy,
Hope that will help to fix the problem.

**Comment by riyasat** [comment]
This issue still exist in 1.4.4 version. Is there any plan to update ?

**Comment by yeahe83** [comment]
same in 1.5.0-beta.4 - -

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
