### ISSUE TITLE
wiki - Docs Request: Explain how to add @angular2-material/toolbar including css

### ISSUE THREAD

**Issue by wzr1337** [angular/angular-cli#770]
I was spending some time to figure out how to add `<md-toolbar>` from @angular2-material/toolbar to my app. I needed to manually add css links and adapt some files:

Added
`   '@angular2-material/toolbar': {
     format: 'cjs',
     defaultExtension: 'js',
     main: 'toolbar.js'
   },
`
=> obvious from the checkbox example in the wiki

Added 
`
      '@angular2-material/**/*.css'
`
to `vendorNpmFiles`, to let the build tools actually copy the css needed for proper display

Added

`import { MdToolbar } from '@angular2-material/toolbar';` for my *.ts code 

and

`directives: [
    MdToolbar,
]`

to my `@Component`

and finally I had to manually add the css links to my index.html, because I was not sure how to let the build chain include the css through `{{content-for 'head'}}` - if that is even possible.

I am not too sure about my solution being the proper one, so please let me know what might be "out of style". Please let me also know if you want me to extend the wiki.

**Comment by leifwells** [comment]
(sorry for the "Me, too!" post, but... me, too!)

I was just lamenting my failure to add Angular2 Material to my Angular CLI project, in this case the md-button component. I followed and rechecked the instructions in the wiki. I am getting no errors in VS Code, the terminal or the console. 

Hopefully there is a step missing in the wiki, or perhaps something was missed in one of the steps?

**Comment by pkamdem** [comment]
@wzr1337  @leifwells  Please try the following

angular-cli-build.js
```javascript

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    // Include this if you wish to customize or use configuration provided by material components
   // Sass compiler will try to resolve @import "@angular2-material/core/core.scss" etc. directives on your_component.scss with the included paths
    sassCompiler: {
      includePaths: [
        'node_modules/@angular2-material/core/core.scss',
        'node_modules/@angular2-material/toolbar/toolbar.scss''
      ]
    },
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/*.js',
      'es6-shim/es6-shim.js',
      'reflect-metadata/*.js',
      'rxjs/**/*.js',
      '@angular/**/*.js',
      '@angular2-material/**/*.+(js|css|map|svg)'
    ]
  });
};

```

system-config.ts
```javascript

const barrels: string[] = [
  // Angular specific barrels.
  ...
  '@angular2-material/core',
  '@angular2-material/toolbar',

  // Thirdparty barrels.
  'rxjs',

  // App specific barrels.
  'app',
  'app/shared',
  /** @cli-barrel */
];

const cliSystemConfigPackages: any = {};
barrels.forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };
});

/** Type declaration for ambient System. */
declare var System: any;

// Apply the CLI SystemJS configuration.
System.config({
  map: {
    '@angular': 'vendor/@angular',
    '@angular2-material': 'vendor/@angular2-material',
    'rxjs': 'vendor/rxjs',
    'main': 'main.js'
  },
  packages: Object.assign({}, cliSystemConfigPackages, {
        // Same rule applies for other components @angular2-material/button e.g
        '@angular2-material/toolbar': {
            defaultExtension: 'js',
            main: 'toolbar.js'
        }
  })
});

```

your_component.ts
```javascript

import { Component } from '@angular/core';
import { MdToolbar } from '@angular2-material/toolbar';

@Component({
  moduleId: module.id,
  selector: 'your-component',
  template: `
  <md-toolbar> ...</md-toolbar>
  `,
  styles: [],
  directives: [MdToolbar]
})
export class YourComponent {
  ...
}

```

Once you serve the app, MdToolbar component style will be injected into the head of the index.html.

**Comment by leifwells** [comment]
I'm getting a TypeScript error at _Object.assert_, but I've hacked my way around that. Anyone know what I have set up wrong to get that error?

Having everything set up as @pkamdem suggested resulted in no errors, but still no Material buttons, like I hoped.

So I took a look at the [Plunkr linked](http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview) from the [angular2/material](https://github.com/angular/material2) site and realized I wasn't using the proper attributes (using the Angular 1 syntax). You can see what is working/not working by looking at the links on this page too: [https://www.npmjs.com/~angular2-material](https://www.npmjs.com/~angular2-material)

Now I have the md-raised-button that I desired.

Thanks.

(Still need to sort out the Object.assert error)

**Comment by wzr1337** [comment]
well, I found out that for some reason I can now remove 
` '@angular2-material/**/*.css' `
from 
`vendorNpmFiles`

and it still works. I do not (yet) have a clue why, but I will let you know what else I changed on the way that is making it work. Probably something obvious once I know it ;)

**Comment by mringrose** [comment]
I was able to use material2 by following Kara's example from ng-conf:  [https://github.com/kara/puppy-love](url)

**Comment by leifwells** [comment]
Wow, @mringrose! Thanks for the link to Kara's system-config.ts file. That is very helpful.

**Comment by JonCubed** [comment]
I use a slight [variant](angular2-ngrx-tour-of-heroes-aspnet-core-vs2015/src/WebApp/clientSrc/system-config.ts) of Kara's that allows for other packages as well

**Comment by wzr1337** [comment]
@JonCubed your links points to an non existing file unfortunetly (404)

Still.. We should improve to wiki ;)

**Comment by JonCubed** [comment]
@wzr1337  thanks, fixed the link

**Comment by filipesilva** [comment]
This issue has been made obsolete by #1455.
