### ISSUE TITLE
 Copy assets outside of src folder (e.g. node_modules)

### ISSUE THREAD

**Issue by AlexOliinyk1** [angular/angular-cli#7700]
Hi

I used custom theme which used icons from node_modules.

In angular.cli.json it is looks like this 
![image](https://user-images.githubusercontent.com/10448723/30471003-b0e15194-99ff-11e7-9470-0023914446ef.png)

I'm trying to configure to move icons from one folder to second, and in references I had my custom css, which used this icons. 

But as result I still got errors like this

![image](https://user-images.githubusercontent.com/10448723/30471145-3962647c-9a00-11e7-894b-a0ce40eedf64.png)

Any idea how to fix this ? Maybe we have another way to do this ? In general I should have ability use icons, etc. from node_modules folder.

Thanks

**Comment by Brocco** [comment]
The CSS should not be part of the assets... you could/should ignore that via your glob and then just reference your CSS via the styles array against node_modules, not assets.

**Comment by AlexOliinyk1** [comment]
@Brocco thanks

**Comment by RezaRahmati** [comment]
I have same issue with fonts and icons.
I don't get the solution provide by Brocco, can you please post your final working version of your angularcli
