### ISSUE TITLE
Lazy Loading with Universal

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#7706]
As per the below comment `@nguniversal/module-map-ngfactory-loader` is now published.

https://github.com/angular/universal/issues/741#issuecomment-325508716

So can Lazy loading be supported for Universal in Angular CLI any time soon?

**Comment by Toxicable** [comment]
You can do Lazy Loading with the CLI
Demo here https://github.com/angular/universal-starter/tree/master/cli

**Comment by CaerusKaru** [comment]
Can be closed by #7803
