### ISSUE TITLE
Ng test misses files

### ISSUE THREAD

**Issue by b-johnse** [angular/angular-cli#7707]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.4.1

### Repro steps.
Not changing any configs or other dependencies, migrated from 1.3.2 up to 1.4.1. As a result an entire directory of code along with app.component.spec.ts were no longer included when running ng test. Reverted back to 1.3.2 and all tests ran again. It would seem something changed in the .spec.ts file detection? The app is large/private so I cannot provide a link or plunkr.

### The log given by the failure.
No failures, but only 97 tests were ran/detected when there should have been 483. 

### Desired functionality.
detection of .spec.ts files back

**Comment by b-johnse** [comment]
My project structure remained the same as when you run ng new [name]
With 1.3.2 the cli finds all tests, when I update to 1.4.5 it finds none. My test.ts file has remained the same and i haven't changed any config files, but something with 1.4.x seems to be affect the regex to find .spec files? My current work around is to revert to 1.3.2

**Comment by b-johnse** [comment]
So after doing a side-by-side comparison of a fresh app generated by the 1.4.5 cli... the difference is in the tsconfig.json files. 

I had to go revisit the contents of tsconfig.json and tsconfig.spec.json in order for all my .spec files to get picked up again when i ran ng test

**Comment by filipesilva** [comment]
Seems like it's sorted then 👍
