### ISSUE TITLE
Webstorm cannot resolve symbol (component)

### ISSUE THREAD

**Issue by huseyinbabal** [angular/angular-cli#771]
I am using Webstorm on Mac OSX El Capitan for develop project generated by using ng-cli. I have realised that, webstorm cannot find component without correct path of the components. If I use the project as it is, I am getting following error on Webstorm.

<img width="693" alt="could_not_found_component" src="https://cloud.githubusercontent.com/assets/1237982/15269503/39b58d78-1a09-11e6-8eb3-28efd11d3901.png">

However, when I add `index` to component path, it is not giving error like below.

<img width="693" alt="could_found_component" src="https://cloud.githubusercontent.com/assets/1237982/15269501/2a22d60e-1a09-11e6-8481-95b2c237f45b.png">

Is there anyone also getting this kind of error?

Thanks in advance

**Comment by mattdistefano** [comment]
Does `./app` (no trailing slash) work?

**Comment by huseyinbabal** [comment]
@mattdistefano not working without trailing slash either

**Comment by pkamdem** [comment]
@huseyinbabal This is not an angular CLI issue but probably related to the IDE. In your case, having installed [WebStorm 2016.2 EAP](https://confluence.jetbrains.com/display/WI/WebStorm+EAP) fixed it.

I think it can be closed.

**Comment by pkamdem** [comment]
Note that this worked
```typescript
import { MyAppComponent } from './app';
```
and this not
```typescript
import { MyAppComponent } from './app/';
```

**Comment by huseyinbabal** [comment]
Hi @pkamdem, I have installed EAP version and it worked. Thanks
