### ISSUE TITLE
Letest angular-cli installation fails for node 8.5 Windows10

### ISSUE THREAD

**Issue by Debananda** [angular/angular-cli#7711]
Your environment has been set up for using Node.js 8.5.0 (x64) and npm.
npm --version
5.3.0

Getting below error while installing latest @angular/cli

**Log in node command prompt**
npm ERR! code EINTEGRITY
npm ERR! sha1-+RcExT0bRh+JNFKwwwfZmXZHq2s= integrity checksum failed when using sha1: wanted sha1-+RcExT0bRh+JNFKwwwfZmXZHq2s= but got sha1-Yq0sdfD20mbR6JvI6M+yEGYWrPo=. (24137 bytes)

**Log from debug File :**
\Users\xxxxxxxx\AppData\Roaming\npm\node_modules\.staging
10493 warn optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 (node_modules\@angular\cli\node_modules\node-sass):
10494 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxx\AppData\Roaming\npm\node_modules\.staging\node-sass-2b9d77df\test\useragent.js'

**Comment by mrtipster49** [comment]
@Debananda were you able to fix this issue, facing same issue on Elementary OS with Node.js v8.5.0

**Comment by Brocco** [comment]
Unfortunately this is an npm issue, that we are unable to help with. Please consult the npm documentation.

**Comment by alsoicode** [comment]
I have exactly the same issue with OS X 10.13 using a fresh install of Node via Homebrew

**Comment by mrtipster49** [comment]
@alsoicode This issue was caused because i used sudo command to install angular, i was able to fix it by changing npm permissions and install angular-cli without sudo on Elementary Os with Node v8.5.0 refer this link https://docs.npmjs.com/getting-started/fixing-npm-permissions to fix npm permissions.
