### ISSUE TITLE
[Feature] Custom project boilerplates

### ISSUE THREAD

**Issue by olakara** [angular/angular-cli#7717]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

Hi everybody,

 This is a feature request. My team and I have a custom ( added theme, services, etc) project that we would like to get generated as the boilerplate when we run **ng new** command. The project is built from the default project and we have added our own common components that we use for all our project.. Is there a way to customize the boilerplate project that gets generated when we issue ng new command ?

**Comment by bmayen** [comment]
There is, but it's not really documented yet. https://github.com/angular/angular-cli/issues/7627

**Comment by olakara** [comment]
@bmayen , thanks for the input.. Is there any link to some examples on devkit ? or any links on devkit to get a better understanding... ?

**Comment by Brocco** [comment]
The documentation/examples are coming... but for now I'm closing this issue so that it can be tracked via #7627
