### ISSUE TITLE
Route animations break AOT

### ISSUE THREAD

**Issue by alshdavid** [angular/angular-cli#7718]
```
[x] bug report
[ ] feature request
```

### Versions.
![image](https://user-images.githubusercontent.com/12656294/30519991-7d81c204-9be7-11e7-977d-428add85c521.png)
![image](https://user-images.githubusercontent.com/12656294/30519995-96583970-9be7-11e7-9997-6d228b4f687b.png)

### Repro steps.
I have created a repo with the project set up
https://github.com/alshdavid/animations

`ng serve` works as expected
`ng build --prod --aot=false` works as expected
`ng serve --aot` builds without error but the page doesn't load
`ng build --prod --aot` builds without error but the page doesn't load 

### The log given by the failure.
![image](https://user-images.githubusercontent.com/12656294/30520134-be454a7e-9bea-11e7-88a1-1e88f6337af2.png)

### Desired functionality.
To use route animations, animations to work in aot as they do without aot

### Mention any other details that might be useful.
Chrome 61
I have tried this on Windows and MacOS with the same result. I am not sure if I am doing it wrong.
I initially used:
https://github.com/matsko/ng4-animations-preview

Where I get this issue:
![image](https://user-images.githubusercontent.com/12656294/30520024-64975ce4-9be8-11e7-8e9a-329dddd825b8.png)

**Comment by alan-agius4** [comment]
Hi, this seems to be due to `default` export. Which is currently tracked https://github.com/angular/angular/issues/11402
