### ISSUE TITLE
ng new not working on RHEL

### ISSUE THREAD

**Issue by mojo2405** [angular/angular-cli#7722]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

NPM : 3.10.10
ng : @angular/cli: 1.4.2
node: 6.11.3
os: linux x64

### Repro steps.

ng new new-yrunner

### The log given by the failure.

create new-yrunner/README.md (1101 bytes)                                                              
  create new-yrunner/.angular-cli.json (1129 bytes)                                                      
  create new-yrunner/.editorconfig (245 bytes)                                                           
  create new-yrunner/.gitignore (516 bytes)                                                              
  create new-yrunner/src/assets/.gitkeep (0 bytes)                                                       
  create new-yrunner/src/environments/environment.prod.ts (51 bytes)                                     
  create new-yrunner/src/environments/environment.ts (387 bytes)                                         
  create new-yrunner/src/favicon.ico (5430 bytes)                                                        
  create new-yrunner/src/index.html (297 bytes)                                                          
  create new-yrunner/src/main.ts (370 bytes)                                                             
  create new-yrunner/src/polyfills.ts (2480 bytes)                                                       
  create new-yrunner/src/styles.css (80 bytes)                                                           
  create new-yrunner/src/test.ts (1085 bytes)                                                            
  create new-yrunner/src/tsconfig.app.json (211 bytes)                                                   
  create new-yrunner/src/tsconfig.spec.json (304 bytes)                                                  
  create new-yrunner/src/typings.d.ts (104 bytes)                                                        
  create new-yrunner/e2e/app.e2e-spec.ts (293 bytes)                                                     
  create new-yrunner/e2e/app.po.ts (208 bytes)                                                           
  create new-yrunner/e2e/tsconfig.e2e.json (235 bytes)                                                   
  create new-yrunner/karma.conf.js (923 bytes)                                                           
  create new-yrunner/package.json (1316 bytes)                                                           
  create new-yrunner/protractor.conf.js (722 bytes)                                                      
  create new-yrunner/tsconfig.json (363 bytes)                                                           
  create new-yrunner/tslint.json (3040 bytes)                                                            
  create new-yrunner/src/app/app.module.ts (314 bytes)                                                   
  create new-yrunner/src/app/app.component.css (0 bytes)                                                 
  create new-yrunner/src/app/app.component.html (1075 bytes)                                             
  create new-yrunner/src/app/app.component.spec.ts (986 bytes)                                           
  create new-yrunner/src/app/app.component.ts (207 bytes)                                                
Installing packages for tooling via npm.                                                                 
npm ERR! Linux 2.6.32-504.el6.x86_64                                                                     
npm ERR! argv "/.autodirect/swgwork/eitansh/nvm/versions/node/v6.11.3/bin/node" "/.autodirect/swgwork/eitansh/nvm/versions/node/v6.11.3/bin/npm" "--quiet" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code Unknown system error -122
npm ERR! errno -122
npm ERR! syscall close

npm ERR! Unknown system error -122: Unknown system error -122, close
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /.autodirect/swgwork/eitansh/trunk/gui/new-yrunner/npm-debug.log

Package install failed, see above.
Package install failed, see above.

### Desired functionality.

create new project

### Mention any other details that might be useful.

adding logs 

https://ufile.io/mhbuw

**Comment by Brocco** [comment]
Unfortunately we aren't able to help with npm installation issues. Please consult the documentation/forums for npm.
