### ISSUE TITLE
Help is not displaying schematic options

### ISSUE THREAD

**Issue by BennieCopeland** [angular/angular-cli#7723]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.2
node: 8.5.0
os: win32 x64
@angular/animations: 4.4.1
@angular/common: 4.4.1
@angular/compiler: 4.4.1
@angular/core: 4.4.1
@angular/forms: 4.4.1
@angular/http: 4.4.1
@angular/platform-browser: 4.4.1
@angular/platform-browser-dynamic: 4.4.1
@angular/router: 4.4.1
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.1
@angular/language-service: 4.4.1
typescript: 2.3.4

### Repro steps.
`ng help`
`ng generate component --help`

### Desired functionality.
Display schematics options. I'm a new CLI user, and I don't know what options are available now when creating new applications or files.

**Comment by petercn** [comment]
@BennieCopeland Here's a short readme which might help a bit: https://github.com/angular/devkit/tree/master/packages/schematics/schematics/schematic/files

Basically, with @angular-devkit/schematics installed, you can then "schematics --help"

The base schematics which ng cli comes with are about 10 or so which include basics like ng generate class, component, service, etc.

Other third parties are beginning to create their own schematics as well, check out this new Nx project which builds upon ng cli: https://nrwl.io/nx

Hope all of that helps :-)

**Comment by filipesilva** [comment]
It is unintended that `ng generate component --help` does not display flags supported by schematics. This also affects `ng new`. 

We're working to fix help support for schematics showing the available flags in the CLI.
