### ISSUE TITLE
Generate .spec files for already existing components / services

### ISSUE THREAD

**Issue by smnbbrv** [angular/angular-cli#7727]
### Solution

If you look for **right now solution** please follow [ngx-spec](https://github.com/smnbbrv/ngx-spec).

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.4.2
node: 8.1.3
os: darwin x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.2
@angular/compiler-cli: 4.3.6
typescript: 2.4.2

### Desired functionality.

I want to generate a .spec file for already existing component / service that does not have a spec yet / has an outdated spec. More on the usecase https://stackoverflow.com/q/46276055/1990451

**Comment by smnbbrv** [comment]
A small addition: would be incredibly perfect if the just created .spec.ts files would have mocks for the every injected item according to the methods / properties that are used in the unit being tested :)

**Comment by Brocco** [comment]
Right now, specs are directly tied to the unit they're testing (component/service) and as of now there are no plans to support this, but leaving this open for discussion purposes.

**Comment by HideDev** [comment]
+1

**Comment by frontEndExpert** [comment]
Yes generating a spec file after we already generated our component and modified it.
ng g component your-component --spec-only

**Comment by michaelbazos** [comment]
What I do to generate the spec file for an already existing component:

    ng generate component [name]

And then answer "no" to the "Overwrite ... ?" questions regarding already existing, non-spec, files.

**Comment by darkbasic** [comment]
@michaelbazos it doesn't work, it simply notifies that the component already exists.

**Comment by tomwhite007** [comment]
I'd like to add my vote for this.
Even if it was only able to create the "[object] works!" type test, it would still save on boilerplate.

**Comment by michaelbazos** [comment]
@darkbasic Indeed, just updated my version of angular-cli to 1.6.0, and it seems no file is generated if any of the [component | template | spec | stylesheet] already exists. Previously I was on 1.4.x, and it used to create non existing files, and ask for already existing ones.

**Comment by smnbbrv** [comment]
So, it's a misdocumented feature then? @Brocco can you confirm it's the right way to do stuff?

**Comment by BBaysinger** [comment]
Also, say I have an entire project w/o .spec files. There should be a way to create them all from a single command.

**Comment by AngelZatch** [comment]
Agreeing with this. I'm currently reconstructing a project and the previous devs _manually deleted_ spec files, my afternoon's very long.

**Comment by Afbcary** [comment]
+1 from me. Refactoring unconventional tests to work with Wallaby and could really use this feature.

**Comment by dakipro** [comment]
+1

**Comment by manytostao** [comment]
+1

**Comment by HannaBabrouskaya** [comment]
+1

**Comment by Zyk88** [comment]
+1

**Comment by FreedomRings** [comment]
+1

**Comment by cipas** [comment]
+1

**Comment by GuiOttoni** [comment]
+1

**Comment by smnbbrv** [comment]
I created a pull request implementing the feature https://github.com/angular/devkit/pull/938 . 

Allows to create specs for component, directive, module, service, pipe, guard (based on corresponding components) by running

```sh
ng g spec my-component.component
```

or as a file (more convenient because files normally already exist and it is easier to point to the file)

```sh
ng g spec /my/project/app/src/blah/my-component.component.ts
```

Please review.

**Comment by PCASME** [comment]
+1

**Comment by aoganezo** [comment]
+1

**Comment by tgrkzus** [comment]
For anyone still looking for a solution to this:
https://www.npmjs.com/package/angular-spec-generator

This seemed to work fairly well for me.

**Comment by smnbbrv** [comment]
As an outcome of the pull request: the custom schematic as a standalone library [ngx-spec](https://github.com/smnbbrv/ngx-spec). Please check and share your feelings there.

@Brocco I leave the thread open as a reference for the future RFC / standard.

**Comment by MrTaiji** [comment]
+
I think this should be possible without installing a additional node package

**Comment by gilupu** [comment]
+1
I think this should be possible without installing a additional node package

**Comment by appienvanveen** [comment]
+1

**Comment by koolkav1** [comment]
+1

**Comment by ryankazokas** [comment]
+1

**Comment by median-man** [comment]
+1

**Comment by neilsoult** [comment]
+ my whole dev team

**Comment by gustavshf** [comment]
+1

**Comment by javarch** [comment]
+1

**Comment by dylanwooters** [comment]
+1

**Comment by rudivanbiljon** [comment]
+1

**Comment by fyllepo** [comment]
+1 why does this not exist...

**Comment by joaop221** [comment]
+1

**Comment by EdWood1994** [comment]
+1

**Comment by Menion93** [comment]
+1

**Comment by mosermanuel** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  02.05.2019.
Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

Bei dringenden Angelegenheiten bitte an folgende Personen wenden:

Webframework: Gernot Binder
Widgetsystem: Rainer Neunteufel
Mein ELBA Architektur: Peter Anderle
Mein ELBA ZVKK: Gerhard Weinberger
PSD2: Harald Mülleder

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [angular/angular-cli] Generate .spec files for already existing
components / services (#7727)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2019 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by stevewithington** [comment]
I realize this thread is a bit dated, however I've just run into this myself (wishing for a `ng g spec` type of functionality). That said, if anyone else runs across this and is looking for a simple way to do this, I've found this project to fill the hole for now <https://github.com/allenhwkim/ngentest>

**Comment by newmediapilot** [comment]
Something I do is...
`generate component COMPONENT-NAME --force`
then in GIT revert the items that got overwritten

**Comment by nukec** [comment]
this simple thing still not in?

**Comment by mosermanuel** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  08.07.2019.
Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [angular/angular-cli] Generate .spec files for already existing
components / services (#7727)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2019 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by tijujohn83** [comment]
+1

**Comment by kmanev073** [comment]
+1

**Comment by afnecors** [comment]
+1

**Comment by sscots** [comment]
+1

**Comment by samuelzapote** [comment]
+1 & +whole dev team

**Comment by andyturner** [comment]
I found I wanted to do this. In the end I just generated a new component with a spec called something very similar to the real component, then renamed the spec and deleted the new component.

**Comment by estoel81** [comment]
+1

**Comment by BrsJsk** [comment]
+1

**Comment by mgechev** [comment]
This feature is currently not on our roadmap.

At the same time though, folks from community implemented a fantastic schematic which scaffolds `.spec` file for existing components, discovers and mocks their dependencies. There's also a VSCode extension that you can take advantage of. You can find the project together with installation instructions [here](https://github.com/gparlakov/scuri).

There's also [a schematic](https://github.com/smnbbrv/ngx-spec) from the author of the issue that you can give a try to.
