### ISSUE TITLE
ng test fails to run the latest code after rebuilding

### ISSUE THREAD

**Issue by gho5thunter** [angular/angular-cli#7729]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

1.0.0-rc.2

### Repro steps.

1) Create a spec with 2 tests.
2) Mark the first test to be focused e.g. ```fit('should create', () => {``` 
3) Run```ng test```.
4) Undo step 2 so that all tests now run.
5) Note that ng test automatically re-runs the tests after the app recompiles automatically but that the first test is still the only test that runs.

### Desired functionality.

Detect the updated code.

**Comment by hyposimon** [comment]
did you try the newest version? 1.0.0-rc.2 is very old ... 1.4.2 is the current version. 

i really dont know, but i think that nobody here can/will give you a support for 1.0.0.rc2

**Comment by gho5thunter** [comment]
We are locked into Angular 2.4. How do I know if it's safe to upgrade the CLI to the latest?

**Comment by Brocco** [comment]
The current version of the CLI (1.4.3 as of yesterday) does support Angular v2.

If support for Angular v2 is dropped it would be considered a breaking change and therefore a major version bump.
