### ISSUE TITLE
Angular 5.x global white space removal support

### ISSUE THREAD

**Issue by coryrylan** [angular/angular-cli#7731]
- [x] feature request

### Desired functionality.
Angular 5.x introduces a new white space removal feature in the compiler to help get template sizes down even smaller. This can be turned on at the component decorator level but also at the global compiler level. This could break layouts so to enable this it would need to be a opt in with the Angular CLI config. 

https://www.softwarearchitekt.at/post/2017/08/31/clever-white-space-handling-for-better-performance-in-angular-5.aspx

**Comment by kevinphelps** [comment]
I would be happy to work on a PR for this.

**Comment by victornoel** [comment]
Also it would be great if this could be applied during karma testing too!

**Comment by alexzuza** [comment]
[How to globally set the preserveWhitespaces option in Angular to false?](https://stackoverflow.com/questions/46018599/how-to-globally-set-the-preservewhitespaces-option-in-angular-to-false)


[Angular set preserveWhitespace in karma tests](https://stackoverflow.com/questions/48671255/angular-set-preservewhitespace-in-karma-tests)

**Comment by coryrylan** [comment]
Closing in favor of the new default behavior of v6
