### ISSUE TITLE
Generating component with Angular CLI writes code two characters too early

### ISSUE THREAD

**Issue by artemdru** [angular/angular-cli#7732]
In Angular 4, whenever I use the CLI to create a component (for example, using this command: "ng g c successAlert"), the app.module.ts file does not generate the correct code - it's as if though the code is written two characters too early. For example, if warningAlert were my last added component:

```
import { WarningAlertComponent } from './warningAlert/warningAlert.component';

@NgModule({
  declarations: [
    WarningAlertComponent
  ]
})
```
And if I were to execute in the CLI "ng g c successAlert", the app.module.ts file would be updated like so:

```
import { WarningAlertComponent } from './warningAlert/warningAlert.componen;
import { SuccesAlertComponent } from './success-alert/succes-alert.component't';

@NgModule({
  declarations: [
    WarningAlertCompone,
    SuccessAlertComponentnt
  ]
})
```
As you can see, there is an error both in the import line, and in the declarations line. This error with two characters is consistent.

If it's relevant, I'm using Sublime Text 3 and the command is being written into the Glue console.

**Comment by textbook** [comment]
This doesn't happen for me with v1.4.2, even if I also mangle an existing component to use the unconventional formatting shown in your example (i.e. `'./warningAlert/warningAlert.component'` rather than `'./warning-alert/warning-alert.component'`).

**Comment by Duh-Rell** [comment]
Having the same problem. Downgraded from 1.4.3 to 1.4.0 incrementally and the problem still persists.

**Comment by kuncevic** [comment]
@artemdru Did you migrated to 1.4.3 or just created a new app? I have never had such an issue constantly keeping my cli always with the latest.

**Comment by fitness23** [comment]
I'm having the same issue as @artemdru 
I'm on Node 8 with Windows 10. My project was originally on Angular 1.2.x and when I upgraded to 1.4.4 I got the same issue. I can resolve it if I create a new project from scratch but it's going to get far too complicated merging everything over. Has a solution been found to this?

**Comment by janmegert** [comment]
Same issue. Two characters of previous import/declaration cut off.
`Angular CLI: 1.7.3` `Node: 8.11.1` `OS: win32 x64` `Angular: 5.2.9`
