### ISSUE TITLE
[Feature Request] ng e2e params.login.user=foo params.login.user=bar

### ISSUE THREAD

**Issue by tuxmatta** [angular/angular-cli#7737]
Hi
I search a way for put console or environment parameters to protractor like:

`yarn ng e2e params.login.user=foo params.login.user=bar`
or
```
export  params.login.user=foo
export params.login.user=bar
yarn ng e2e
```
I can not use the --config-file parameter, because the config file is under version control.
Exists currently a way for this requirement?

**Comment by hansl** [comment]
Hi @tuxmatta,

There's unfortunately no way to use extra parameters or environment variables as part of the build.

We have many issues for tracking this: #4419, #4318. We will update those when we have a plan to support this use case.

Closing this as duplicated.
