### ISSUE TITLE
v1.4.2 breaks less loader

### ISSUE THREAD

**Issue by AmitMY** [angular/angular-cli#7741]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.4.2
node: 8.4.0
os: win32 x64
@angular/animations: 4.4.2
@angular/common: 4.4.2
@angular/compiler: 4.4.2
@angular/core: 4.4.2
@angular/forms: 4.4.2
@angular/http: 4.4.2
@angular/platform-browser: 4.4.2
@angular/platform-browser-dynamic: 4.4.2
@angular/router: 4.4.2
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.2
@angular/language-service: 4.4.2
typescript: 2.5.2
```
- Also tried angular@latest, and angular-cli@1.5.0-beta

### Repro steps.
- Have an app using less `@import` from a node module (`@import '~some-module'`) - using 1.3.0
- Upgrade to 1.4.2, try to `ng serve`. Error

### The log given by the failure.
```

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2017-09-19T10:42:29.079Z
Hash: 931e1779dce49dcd6863
Time: 34616ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 1.21 MB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 209 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 57 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 9.18 MB [initial] [rendered]

ERROR in ./src/app/packages/map-facade/components/context-menu/context-menu.component.less
Module build failed: 

@import "~@ansyn/core/less/common";
@import '~@ansyn/core/less/z-index-globals';
^
'~@ansyn/core/less/z-index-globals.less' wasn't found. Tried - C:\Users\user\Desktop\Projects\ansyn\src\app\packages\map-facade\components\context-menu\~@ansyn\core\less\z-index-globals.less,~@ansyn\core\less\z-index-globals.less
      in C:\Users\user\Desktop\Projects\ansyn\src\app\packages\map-facade\components\context-menu\context-menu.component.less (line 2, column 0)
 @ ./src/app/packages/map-facade/components/context-menu/context-menu.component.ts 177:21-61
 @ ./src/app/packages/map-facade/map-facade.module.ts
 @ ./src/app/packages/map-facade/index.ts
 @ ./src/app/ansyn/ansyn.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
ERROR in ./src/app/ansyn/ansyn/ansyn.component.less
Module build failed: 
```

### Desired functionality.
No breaking changes for a minor version

### Mention any other details that might be useful.
This error is from the `less-loader`.
There is no custom configuration for the project, this is default stuff.
It is an open source project, https://github.com/AnSyn/ansyn

**Comment by clydin** [comment]
This is actually a side effect of enabling support for include paths for the `less-loader`.  The `less-loader` doesn't support webpack resolution when include paths are enabled.
However, currently, the CLI always enables the support regardless of the presence of any project configured include paths.  This should probably be adjusted.

In general, I would try to avoid webpack specific features where possible to ensure full forward compatibility.  However, stylesheet package resolution is probably the use case where it is currently most needed.

**Comment by AmitMY** [comment]
Thanks for the info.
While I definitely get your point, I am kind of forced to use what I am using and can't use anything else.
I hope they fix this regression in 1.5.0, as that beta gives me what I need, but with a great great cost.

**Comment by clydin** [comment]
I haven't tested this but something you could try is to put the path to your `node_modules` (`../node_modules`, I believe in a stock project) in the style preprocessor include paths option.  Theoretically you should be able to reference files within a package without the `~`.

**Comment by AmitMY** [comment]
Thanks for making a PR for this!
When it is merged, do I need to change something in the config?

**Comment by clydin** [comment]
As long as there are no style preprocessor include paths defined, no changes are necessary.  Essentially what the PR does is maintain the behavior previously found in 1.3 if no include paths are present.  Also, it's important to note that the loader itself intentionally doesn't support webpack resolution in combination with include paths.

**Comment by AmitMY** [comment]
Awesome, thanks! I can only test this at the beginning of the next week, but I will let you know if this solved it for me.
I appreciate your responsiveness!

**Comment by AmitMY** [comment]
It works! Thanks again!
