### ISSUE TITLE
Error When running the npm start..

### ISSUE THREAD

**Issue by jabbar86** [angular/angular-cli#7742]
npm start

> angular@1.0.0 start E:\Mean Stack\Angular-2-Tutorials-master\Template
> tsc && concurrently "npm run tsc:w" "npm run lite"

node_modules/@angular/forms/src/directives/ng_model.d.ts(8,32): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/core/index"' has no exported member 'SimpleChanges'.
node_modules/@angular/forms/src/directives/reactive_directives/form_control_directive.d.ts(8,21): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/core/index"' has no exported member 'SimpleChanges'.
node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.d.ts(8,32): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/core/index"' has no exported member 'SimpleChanges'.
node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.d.ts(8,21): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/core/index"' has no exported member 'SimpleChanges'.
app/app.module.ts(1,10): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/core/index"' has no exported member 'NgModule'.
app/app.module.ts(2,10): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/platform-browser/index"' has no exported member 'BrowserModule'.
app/app.module.ts(3,10): error TS2305: Module '"E:/Mean Stack/Angular-2-Tutorials-master/Template/node_modules/@angular/forms/index"' has no exported member 'FormsModule'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jabbar Memon\AppData\Roaming\npm-cache\_logs\2017-09-19T13_18_26_626Z-debug.log

**Package.Json**
{
  "name": "angular",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/compiler-cli": "^4.4.2",
    "@angular/core": "2.0.0-rc.1",
    "@angular/forms": "^0.2.0",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@angular/upgrade": "2.0.0-rc.1",
    "angular2-in-memory-web-api": "0.0.7",
    "bootstrap": "^3.3.6",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.2",
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings": "^0.8.1"
  }
}

**Comment by bmayen** [comment]
You are on a very old version of Angular. It looks like you're following a tutorial. I would recommend not using tutorials which are based on RC1 as you're very likely going to learn the wrong things. A lot has changed between 2.0.0-rc.1 and ^4.0.0, and version 5.0.0 is already around the corner.

**Comment by jabbar86** [comment]
Yes i am following the tutorial based on rc1.So what i should update in order to run the file successfully

**Comment by bmayen** [comment]
Again, my recommendation is that you not follow tutorials based on RC1. Do you really want to be learning things like "router-deprecated", which I see in your package.json? 

Ultimately, stackoverflow is a more appropriate forum for this type of question, as this is not an issue with CLI.

**Comment by jabbar86** [comment]
ok thank you soo much @bmayen for the help 👍
