### ISSUE TITLE
@ngtools/webpack: Add ability to directly import an NgFactory

### ISSUE THREAD

**Issue by franekp** [angular/angular-cli#7743]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
All.

### Repro steps.
When having any custom bootstrap code, users need to read source of this plugin and structure their code in hacky ways specially to not break bootstrapping code detection.
For example: https://github.com/angular/angular-cli/issues/3540#issuecomment-270627460
I recently needed to use NgUpgrade's "independent mode" which requires different bootstrapping (downgradeModule + angular 1 bootstrap code) and had to use a workaround.

### The log given by the failure.
ERROR in /home/...../main.ts (36,37): Cannot find module './app.module.ngfactory'.

### Desired functionality.
import {MyModuleNgFactory} from './app.module.ngfactory'
// ^ should work without problems

**Comment by filipesilva** [comment]
This isn't a feature that we're looking at adding. My best advice for this usecase is to use a custom setup. If there's NgUpgrade documentation in angular.io today that asks you to do things that just don't work on Angular CLI we should fix that though.
