### ISSUE TITLE
[feature request]: Add documentation to testing FAQ on how to keep Mock services from production bundle

### ISSUE THREAD

**Issue by jrmcdona** [angular/angular-cli#7745]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions.
@angular/cli: 1.4.1
node: 8.2.1
os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/compiler-cli: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/platform-server: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.1
@ngtools/webpack: 1.5.0
typescript: 2.4.1

### Desired functionality.
I am adding Mocked services.  I am trying to figure out the ideal and simple way to not have these items in my production bundles.  Knowing little about how the Angular CLI works, I thought a decorator on the class might work to keep things from bundling in the case of tests or mocks.   If not feasible, what is the approach.

### Mention any other details that might be useful.
If you look at the Angular sample:
https://angular.io/generated/live-examples/testing/app-specs.eplnkr.html

What would prevent FakeHeroService (fake-hero.service.ts) from ending up in the production bundle?

Is there an official way of doing this today?

This would be good for the FAQ on this page.

Thanks

**Comment by devoto13** [comment]
If none of the code already in the production bundle imports it - it won't be in production bundle. That's it :)
