### ISSUE TITLE
feat: improve error message when no "entryModule" in tsconfig

### ISSUE THREAD

**Issue by wardbell** [angular/angular-cli#7747]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
Currently, if you omit the "entryModule" in `tsconfig.json` you get this mysterious error
```
ERROR in TypeError: Cannot read property 'split' of undefined
```

This is probably only a problem when running with tools outside of a CLI-managed project.

Adding the "entryModule" cures it as in this example
```  
  "angularCompilerOptions": {
    "genDir": "aot",
    "entryModule": "./src/app/app.module#AppModule",
    "skipMetadataEmit" : true
 }
```
Please fix the error message so that the developer may understand the cause and the remedy.

### Versions.

@angular/cli@1.4.2

### Repro steps.

Delete the "entryModule" from the `tsconfig.json` and compile.

### The log given by the failure.

```
ERROR in TypeError: Cannot read property 'split' of undefined
```

### Desired functionality.

Would like an error message such as 

>Could not find or interpret the "angularCompilerOptions.entryModule" in the `tsconfig.json`.

### Mention any other details that might be useful.

Might consider adding a StackOverflow explanation for this error to help those who are on current and older versions of the CLI.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
