### ISSUE TITLE
Error when creating angular project using angular-cli

### ISSUE THREAD

**Issue by lgLindstrom** [angular/angular-cli#7748]
- [X] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
npm: 5.0.0
angular-cli: 1.4.2

### Repro steps.
- install latest npm
- install latest angular-cli
- create a new angular project:  npm new unitTest
This give following output
----------
  create unitTest/e2e/app.e2e-spec.ts (291 bytes)
  create unitTest/e2e/app.po.ts (208 bytes)
  create unitTest/e2e/tsconfig.e2e.json (235 bytes)
  create unitTest/karma.conf.js (923 bytes)
  create unitTest/package.json (1314 bytes)
  create unitTest/protractor.conf.js (722 bytes)
  create unitTest/README.md (1099 bytes)
  create unitTest/tsconfig.json (363 bytes)
  create unitTest/tslint.json (3040 bytes)
  create unitTest/.angular-cli.json (1127 bytes)
  create unitTest/.editorconfig (245 bytes)
  create unitTest/.gitignore (516 bytes)
  create unitTest/src/assets/.gitkeep (0 bytes)
  create unitTest/src/environments/environment.prod.ts (51 bytes)
  create unitTest/src/environments/environment.ts (387 bytes)
  create unitTest/src/favicon.ico (5430 bytes)
  create unitTest/src/index.html (295 bytes)
  create unitTest/src/main.ts (370 bytes)
  create unitTest/src/polyfills.ts (2480 bytes)
  create unitTest/src/styles.css (80 bytes)
  create unitTest/src/test.ts (1085 bytes)
  create unitTest/src/tsconfig.app.json (211 bytes)
  create unitTest/src/tsconfig.spec.json (304 bytes)
  create unitTest/src/typings.d.ts (104 bytes)
  create unitTest/src/app/app.module.ts (314 bytes)
  create unitTest/src/app/app.component.html (1075 bytes)
  create unitTest/src/app/app.component.spec.ts (986 bytes)
  create unitTest/src/app/app.component.ts (207 bytes)
  create unitTest/src/app/app.component.css (0 bytes)
Installing packages for tooling via npm.
npm ERR! Cannot read property 'find' of undefined
npm ERR! Cannot read property 'find' of undefined
npm ERR! Cannot read property 'find' of undefined
npm ERR! Cannot read property 'find' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     xxx\2017-09-19T18_33_06_231Z-debug.log

### The log given by the failure.
End of the logfile
-------------------
13889 silly extract del@3.0.0
13890 silly pacote trying del@https://registry.npmjs.org/del/-/del-3.0.0.tgz by hash: sha1-U+z2mf/LyzljdpGrE7rxYIGXZuU=
13891 silly pacote html-minifier@https://registry.npmjs.org/html-minifier/-/html-minifier-3.5.5.tgz extracted to C:\HostedProjects\test\unitTest\node_modules\.staging\html-minifier-d8171dc4 by content address 338ms
13892 silly extract copy-webpack-plugin@4.0.1
13893 silly pacote trying copy-webpack-plugin@https://registry.npmjs.org/copy-webpack-plugin/-/copy-webpack-plugin-4.0.1.tgz by hash: sha1-lyjjg7lDFgUNDHRjlY8rhcCqggA=
13894 verbose stack TypeError: Cannot read property 'find' of undefined
13894 verbose stack     at opts.integrity.digests.find.hash (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:262:33)
13894 verbose stack     at Array.find (native)
13894 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:261:15)
13894 verbose stack     at emitNone (events.js:110:20)
13894 verbose stack     at Transform.emit (events.js:207:7)
13894 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
13894 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
13894 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
13895 verbose cwd C:\HostedProjects\test\unitTest
13896 verbose Windows_NT 10.0.15063
13897 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--quiet" "install"
13898 verbose node v8.0.0
13899 verbose npm  v5.0.0
13900 error Cannot read property 'find' of undefined
13901 verbose exit [ 1, true ] 

### Desired functionality.
Be able to do "ng serve" and the template applications starts without errors.  
Now I get the following error.
------------------
unitTest > ng serve

The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compil
er-cli'
    at Object.<anonymous> (C:\Users\lars-göran\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@ngtools\webpa
ck\src\index.js:14:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\lars-göran\AppData\Roaming\npm\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\lars-göran\AppData\Roaming\npm\node_modules\@angular\cli\models\webpack-configs\styl
es.js:6:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by Brocco** [comment]
This appears to be a bad npm install... can you please remove your node_modules dir reinstall and then retry to run the app?

**Comment by lgLindstrom** [comment]
okay,, I removed and installed npm and angular-cli,,, and now it works. Thanks,,,
