### ISSUE TITLE
compiler.es5.js:1694 Uncaught Error: Encountered undefined provider! Usually this means you have a circular dependencies

### ISSUE THREAD

**Issue by rekna1** [angular/angular-cli#7750]
### Bug Report
```
- [ x] bug report
- [ ] feature request
```
I sometimes get this error at runtime while running ng build in watch mode (ng build -w).
When the error has occured it remains occurring on subsequent builds on file changes.
If I stop ng build and restart it, the error is gone (without modyfing any source code).
To be clear : ng build does succesfully build, I'm getting this error at runtime in the browser console window.

### Versions.
@angular/cli: 1.4.2
node: 6.10.3
os: win32 x64
@angular/animations: 4.4.1
@angular/common: 4.4.1
@angular/compiler: 4.4.1
@angular/core: 4.4.1
@angular/forms: 4.4.1
@angular/http: 4.4.1
@angular/platform-browser: 4.4.1
@angular/platform-browser-dynamic: 4.4.1
@angular/router: 4.4.1
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.1
@angular/language-service: 4.4.1
typescript: 2.3.4

### Repro steps.
ng build -w
It is not clear when this error occurs, so there are no clear steps to reproduce the error

### The log given by the failure in de browser console:
compiler.es5.js:1694 Uncaught Error: Encountered undefined provider! Usually this means you have a circular dependencies (might be caused by using 'barrel' index.ts files.
    at syntaxError (compiler.es5.js:1694)
    at compiler.es5.js:15974
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getProvidersMetadata (compiler.es5.js:15959)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (compiler.es5.js:15614)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (compiler.es5.js:26958)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (compiler.es5.js:26931)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (compiler.es5.js:26860)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone (core.es5.js:4536)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule (core.es5.js:4522)
syntaxError @ compiler.es5.js:1694
(anonymous) @ compiler.es5.js:15974
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getProvidersMetadata @ compiler.es5.js:15959
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata @ compiler.es5.js:15614
webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules @ compiler.es5.js:26958
webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents @ compiler.es5.js:26931
webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync @ compiler.es5.js:26860
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4536
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4522
../../../../../src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap e8fa83c0e0879a93d2a6:54
0 @ main.ts:12
__webpack_require__ @ bootstrap e8fa83c0e0879a93d2a6:54
webpackJsonpCallback @ bootstrap e8fa83c0e0879a93d2a6:25
(anonymous) @ main.bundle.js:1

### Desired functionality.
The application should run if ng build encounters no errors.

**Comment by MazzMazz** [comment]
Just had the same problem. `ng serve --deploy-url=/app/ --base-href=/app/` was working fine when this error suddenly appeared without changing anything.

Aborting and calling `ng serve` again fixed it for me like @rekna1 wrote (thanks for that)

**Comment by filipesilva** [comment]
This should be fixed with https://github.com/angular/angular-cli/pull/7512+https://github.com/angular/angular-cli/pull/7684, but only for Angular 5 projects. It happened due to the way we compiled typescript for Angular 2 and 4. We did a new plugin for Angular 5 that should handle these edge cases much better.
