### ISSUE TITLE
npm install angular-cli throws   node' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by vmylarap** [angular/angular-cli#7755]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report ->When I run the  command 'npm install angular-cli' then I get
node' is not recognized as an internal or external command,
operable program or batch file, though the nodejs is set in Path environment variable.
- [ ] feature request
```

### The log given by the failure.
C:\Softwares\node-v6.11.3-win-x64\ng -> C:\Softwares\node-v6.11.3-win-x64\node_modules\angular-cli\bin\ng

> node-sass@4.5.3 install C:\Softwares\node-v6.11.3-win-x64\node_modules\angular-cli\node_modules\node-sass
> node scripts/install.js

'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN Error: EPERM: operation not permitted, scandir 'C:\Softwares\node-v6.11.3-win-x64\node_modules\angular-cli\node_modules\fsevents\node_modules\getpass\node_modules'
npm WARN     at Error (native)
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Softwares\node-v6.11.3-win-x64\node_modules\angular-cli\node_modules\fsevents\node_modules\getpass\node_modules'
npm WARN     at Error (native)
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Softwares\\node-v6.11.3-win-x64\\node_modules\\angular-cli\\node_modules\\fsevents\\node_modules\\getpass\\node_modules\'\n    at Error (native)',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Softwares\\node-v6.11.3-win-x64\\node_modules\\angular-cli\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! Exit status 1

**Comment by Brocco** [comment]
It appears you have an issue with your environment... please ensure you have node, npm and the latest CLI installed. Then retry.

**Comment by asafMasa** [comment]
i think it's related with this issue https://github.com/angular/angular-cli/issues/7813

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI.
