### ISSUE TITLE
Method to refresh compiled  global css from scss like livereload/browsersync

### ISSUE THREAD

**Issue by smlombardi** [angular/angular-cli#7757]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.

@angular/cli: 1.4.2
node: 6.11.2
os: darwin x64
US-ST016LO-MLT:des

### Desired functionality.

Our projects use a global scss file.  We need to have source maps to debug sass as we work, so currently we run `ng serve --sourcemap --extractCss -o --hmr -e=hmr`.  When editing a scss file, the css is compiled but the browser is not refreshed with the changes.

So, sometimes I will run the app without HMR just to force a reload on every save: `ng serve --sourcemap --extractCss -o`.

However, it would be preferable to have the CSS changes injected like the JS is with HMR.  In older projects we used Gulp and Browsersync, which would inject css changes without reloading the browser.

I have searched and searched on this, and many issues request this for SCSS in components which, while nice, is more than we require; just getting this for global scss/css file would be huge.

I don't see this on any roadmaps anywhere.  Is something like this being worked on?

**Comment by kyr0** [comment]
I ran into this one today... well..., not so cool since we are transitioning from global styles to component styles right now and need to check changes in a HMR-way on both sides including source maps support.

**Comment by shyamal890** [comment]
+1 @Brocco would appreciate your thoughts on this.

**Comment by SystemR** [comment]
Global style injection seems to work if you omit the --extractCss flag

**Comment by smlombardi** [comment]
@SystemR But then source maps don't work

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
