### ISSUE TITLE
i18n extraction -op (--output-path) option not working in CLI 1.4.2

### ISSUE THREAD

**Issue by sgwatgit** [angular/angular-cli#7760]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.2
node: 8.3.0
os: win32 x64
@angular/animations: 5.0.0-beta.7
@angular/cdk: 2.0.0-beta.10
@angular/common: 5.0.0-beta.7
@angular/compiler: 5.0.0-beta.7
@angular/core: 5.0.0-beta.7
@angular/forms: 5.0.0-beta.7
@angular/http: 5.0.0-beta.7
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 5.0.0-beta.7
@angular/platform-browser-dynamic: 5.0.0-beta.7
@angular/router: 5.0.0-beta.7
@angular/cli: 1.4.2
@angular/compiler-cli: 5.0.0-beta.7
typescript: 2.4.2

### Repro steps.
`ng xi18n -f xlf -l en-US -op src/locale -of untranslated-messages.xlf --progress`

### The log given by the failure.
XLF file is generated at the path ` /out-tsc/app/untranslated-messages.xlf`

### Desired functionality.
XLF file is generated at the path `/src/locale/untranslated-messages.xlf`

### Mention any other details that might be useful.
`/tsconfig.json`
```
{
  "compilerOptions": {
    "baseUrl": "src",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "allowUnreachableCode": false,
    "lib": [
      "es2017",
      "dom"
    ],
    "mapRoot": "./",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types",
      "./typings.d.ts"
    ],
    "types": [
      "node"
    ]
  }
}
```
`src/tsconfig.app.json`
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "baseUrl": "",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

I'm wondering if this issue will be fixed by https://github.com/angular/angular-cli/pull/7702?

When testing this same command on a test `Angular 4.1.3` app using `CLI 1.1.1` the file is written to the correct location.

Thanks!

**Comment by Brocco** [comment]
Support of Angular v5 is in CLI 1.5.0 (currently in beta) and the fix you're looking for is merged in this PR #7702
