### ISSUE TITLE
Question: serve command use

### ISSUE THREAD

**Issue by pkamdem** [angular/angular-cli#777]
@hansl 
Throughout the docs it is mentioned ``ng serve`` but the start script of the _package.json_ is ``ng server``.
It works as well. My question is, should we not use the same form for the sake of consistency and lowering user confusion?

This is a really minor flag...so feel free to just close that one if no need be. I can submit a PR to move forward.

**Comment by filipesilva** [comment]
This question has actually come up a couple of times. `ng server` is an alias of `ng serve`, and I agree with you: for the sake of consistency the npm script should be `ng serve`. 

Do you want to put up a PR, marking this issue as solved in it?

**Comment by pkamdem** [comment]
@filipesilva Great, I will!

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/781
