### ISSUE TITLE
update Stories Proxy documentation

### ISSUE THREAD

**Issue by MyHeartsECO** [angular/angular-cli#7772]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [] feature request
```

### Versions.

@angular/cli: 1.2.7
node: 6.9.4
os: darwin x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.2.7
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.3

### Repro steps.

https://github.com/angular/angular-cli/wiki/stories-proxy
Stories Proxy doc is true but missing.

### Desired functionality.

I've managed to work it (after hours of searching webpack pages) by:
```json
{
  "/api": {
    "target": "http://localhost:8080",
    "secure": false,
    "logLevel": "debug",
    "changeOrigin": true,
    "pathRewrite": {
      "^/api": ""
    }
  }
}
```
### Mention any other details that might be useful.

This is the solution: https://stackoverflow.com/questions/39809008/angular-cli-proxy-to-backend-doesnt-work

**Comment by filipesilva** [comment]
Hello, would you like to update the documentation with the changes you feel are needed? The file for this particular documentation item is https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md.

Bear in mind that we already have tests for proxy configuration (https://github.com/angular/angular-cli/blob/master/tests/e2e/tests/misc/proxy-config.ts) and they are working. So please make sure your changes are testable and not specific to your particular setup.
