### ISSUE TITLE
ng build --deploy-url "https://cdn.balabla.com" fail with unexpected token

### ISSUE THREAD

**Issue by tingtingli911** [angular/angular-cli#7781]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.3
node: 7.8.0
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.4.3
typescript: 2.5.2

### Repro steps.

ng build --prod --deploy-url="https://cdn.blablabala.com"

### The log given by the failure.

Uncaught SyntaxError: Unexpected token <  inline.082294f5457a019a4cd7.bundle.js:1
Uncaught ReferenceError: webpackJsonp is not defined
    at polyfills.ac0bdd9514ff9092ada5.bundle.js:1   polyfills.ac0bdd9514ff9092ada5.bundle.js:1
Uncaught SyntaxError: Unexpected token <  vendor.2e243af5ebaa1a18c269.bundle.js:1
Uncaught SyntaxError: Unexpected token <  main.1f0af20d1fd500348a02.bundle.js:1

**Comment by zackarychapple** [comment]
@filipesilva we are experiencing the same thing.  Its interesting, just doing a build again most times resolves the issue. 
```inline.1128a5b9179c8fb79c55.bundle.js:1 Uncaught SyntaxError: Unexpected token <
polyfills.674b5ddae76fd2b73f01.bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at polyfills.674b5ddae76fd2b73f01.bundle.js:1
(anonymous) @ polyfills.674b5ddae76fd2b73f01.bundle.js:1
main.b92620fddd4bc7634de0.bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at main.b92620fddd4bc7634de0.bundle.js:1```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
