### ISSUE TITLE
ng build --prod error

### ISSUE THREAD

**Issue by avril-verhaeghen** [angular/angular-cli#7785]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] support request
```

### Versions.
version: 1.3.2

### Repro steps.
Existing project generated by v1.3.2 -> ng build --prod

### The log given by the failure.
`ERROR in Encountered undefined provider! Usually this means you have a circular dependencies (might be caused by using 'barrel' index.ts files.
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/avrilverhaeghen/Develop/frontoffice/src'
resolve './$$_gendir/app/app.module.ngfactory' in '/Users/avrilverhaeghen/Develop/frontoffice/src'
  using description file: /Users/avrilverhaeghen/Develop/frontoffice/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/avrilverhaeghen/Develop/frontoffice/package.json (relative path: ./src)
    using description file: /Users/avrilverhaeghen/Develop/frontoffice/package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/avrilverhaeghen/Develop/frontoffice/src/$$_gendir/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/avrilverhaeghen/Develop/frontoffice/src/$$_gendir/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/avrilverhaeghen/Develop/frontoffice/src/$$_gendir/app/app.module.ngfactory.js doesn't exist
      as directory
        /Users/avrilverhaeghen/Develop/frontoffice/src/$$_gendir/app/app.module.ngfactory doesn't exist
[/Users/avrilverhaeghen/Develop/frontoffice/src/$$_gendir/app/app.module.ngfactory]
[/Users/avrilverhaeghen/Develop/frontoffice/src/$$_gendir/app/app.module.ngfactory.ts]
[/Users/avrilverhaeghen/Develop/frontoffice/src/$$_gendir/app/app.module.ngfactory.js]
[/Users/avrilverhaeghen/Develop/frontoffice/src/$$_gendir/app/app.module.ngfactory]
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
`

I'm having this issue and not quite sure where to look. With the first error it seems that he's having troubles finding my modules maybe because of index.ts files but I don't have any.

### Mention any other details that might be useful.
I'm using lazy load modules, not sure if I have to change the default settings to build AOT?

Thanks for any help!

**Comment by avril-verhaeghen** [comment]
Forgot to update environment.prod.ts 🙄

**Comment by meepobrother** [comment]
i have the save issue`ERROR in : Encountered undefined provider! Usually this means you have a circular dependencies (might be caused by using 'barrel' index.ts files.`

**Comment by nblavoie** [comment]
Any news on this issue ? Facing the same situation; no details or what's happening.
