### ISSUE TITLE
codeCoverage exclude does not appear to be working. 

### ISSUE THREAD

**Issue by kentonbmax** [angular/angular-cli#7786]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli": "1.0.3",
    "@angular/compiler-cli": "4.1.3",
    "@types/angular": "^1.6.32",
"@angular/core": "4.1.3",

    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "4.1.0",

### Repro steps.
Using this sample none of my test framework files are excluded from coverage from /src/test
"test": {
    "codeCoverage" : {
      "exclude": ["**/mocks.ts"]
    },
    "karma": {
      "config": "./karma.conf.js"
    }
  },

### Desired functionality.
files that end in mocks.ts would not be included. 

### Mention any other details that might be useful.
It would be nice to exclude whole directories as well. Ex. A custom test framework directory would need to be excluded. We currently have an app with 2 main pieces each with a responsible team. We would like to show coverage for each.

**Comment by daBishMan** [comment]
> "./src/app/feature/**/*.*",        

that is how I filtered my code coverage excludes

**Comment by filipesilva** [comment]
@kentonbmax I think the problem with your path is that it's not related (@daBishMan's path is).

Can you try `"exclude": ["./**/mocks.ts"]`?

**Comment by kentonbmax** [comment]
tried both examples modifying for my example, excluding the test folder would also work. Files in the test folder are common.mocks.ts, service.mocks.ts, etc. 
![image](https://user-images.githubusercontent.com/15804484/30811699-f89c4532-a1d6-11e7-9241-8dcbff3f5ca3.png)

**Comment by kentonbmax** [comment]
Got it to work. `"exclude": ["./src/test/*mocks.ts"]` did the trick.

**Comment by Abhishek-Kanitkar** [comment]
@kentonbmax 
Can you please post your whole .angular-cli.json after adding exclude changes ?
I want to know what you have set for "root" config property.

**Comment by Abhishek-Kanitkar** [comment]
@filipesilva 
Can you please show me a working example of how to exclude for example 
abc directory nested under src ?
