### ISSUE TITLE
ng build --aot creates duplicate Webpack imports causing instanceof operator to break

### ISSUE THREAD

**Issue by udos86** [angular/angular-cli#7788]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.4.3
node: 8.5.0
os: darwin x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
typescript: 2.3.4
```

### Repro steps.

I'm providing the library [NG Dynamic Forms](https://github.com/udos86/ng-dynamic-forms). 

Lately, I received some bug reports related to Angular CLI `ng built --aot` 

After some investigation I recognized that the Angular CLI AoT build breaks all `instanceof` checks.

This is a piece of the original library source code:
```
if (groupModel instanceof DynamicFormGroupModel) {
  groupModel.insert(index, controlModel);
}
```

After being bundled with Angular CLI it becomes this in `vendor.bundle.js`:
```
if (groupModel instanceof __WEBPACK_IMPORTED_MODULE_2__model_form_group_dynamic_form_group_model__["b" /* DynamicFormGroupModel */]) {
  groupModel.insert(index, controlModel);
}
```
That Webpack transformation causes all `instanceof` checks to fail anyway:

<img width="1424" alt="bildschirmfoto 2017-09-24 um 13 13 21" src="https://user-images.githubusercontent.com/508325/30782233-3e37c5ac-a12e-11e7-9fb5-6ac4e74822cc.png">

[Here](https://github.com/udos86/ng-forms-workshop) is the sample repo I'm using for all my Angular CLI tests. 
 
I'm not experiencing any problems when leaving off `--aot` or manually bundling and compiling using `@angular/compiler-cli` and Webpack / Rollup.

**Comment by udos86** [comment]
Alright, here's what's going on.

There are two different imports for `DynamicFormGroupModel` 

This is the line of  code that creates the `groupModel` instance:
`new __WEBPACK_IMPORTED_MODULE_0__ng_dynamic_forms_core__["k" /* DynamicFormGroupModel */]({...})`

And that's the line of code that uses `instanceof`:
```
if (groupModel instanceof __WEBPACK_IMPORTED_MODULE_2__model_form_group_dynamic_form_group_model__["b" /* DynamicFormGroupModel */]) {
  groupModel.insert(index, controlModel);
}
```

It's obvious this leads to an error when using `instanceof`.

But what's the reason for this bundling error?

**Comment by clydin** [comment]
Looking at the definitions of the two webpack module imports provides some additional insight:

main bundle: 
```
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__ng_dynamic_forms_core__ =
__webpack_require__("../../../../@ng-dynamic-forms/core/bundles/core.es.js");
```
vendor bundle: 
```
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__form_group_dynamic_form_group_model__ =
__webpack_require__("../../../../@ng-dynamic-forms/core/src/model/form-group/dynamic-form-group.model.ts");
```

Note that the library's typescript source is being pulled in.
There's at least two issues that could be contributing to this:
1) The library's typescript source should not be published with the package.
2) The library is not generating and/or publishing the angular metadata files which are used by the AOT compiler.

**Comment by filipesilva** [comment]
I agree with @clydin's analysis, this seems like a problem with how you're packaging/linking your library. Please take a look at https://github.com/angular/angular-cli/wiki/stories-linked-library for explanation and workarounds.

**Comment by udos86** [comment]
@clydin @filipesilva Alright, thanks!

I'll prepare my library to meet Angular Package Format requirements and we'll see what happens.

**Comment by udos86** [comment]
@clydin @filipesilva 

I blame it all on myself. 

I finally figured out how to properly compile with `ngc` to Angular Package Format to solve this issue.

Thanks again for your expertise!

**Comment by filipesilva** [comment]
Glad to hear you got it sorted. Mind you that packaging isn't an overall easy problem.. you're not the only one having difficulties. We're trying to come up with solutions to make it easier.
