### ISSUE TITLE
ng build --prod --aot 

### ISSUE THREAD

**Issue by daniyalnagori** [angular/angular-cli#7789]
i have updated my angular cli to 1.4.2 
and getting successful build using aot build but when i run on browser getting
this error (Error: No provider for e!)

![image](https://user-images.githubusercontent.com/15701883/30750095-ee9fd968-9fce-11e7-9a54-67eb96165909.png)

**Comment by tchopper** [comment]
I've had a similar issue when a library I recently added was not aot compatible (Would build fine but not load the site). Added anything new?

To verify - remove --aot and check if it works. Then drill down to what it could be?

**Comment by alexzuza** [comment]
@daniyalnagori  Which angular version are you using?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by alexzuza** [comment]
@filipesilva I think it's connected with https://github.com/angular/angular/issues/19219
