### ISSUE TITLE
Cannot use `AotPlugin` without specifying `entryModule`

### ISSUE THREAD

**Issue by maximusk** [angular/angular-cli#7792]
[Here](https://www.npmjs.com/package/@ngtools/webpack) it states the following for the `options`:

> entryModule. **Optional** if specified in angularCompilerOptions. The path and classname of the main application module. This follows the format path/to/file#ClassName.

So it states the `entryModule` is optional. However, if I have the following configuration:

```
    module: {
        rules: [
            {
                test: /\.ts$/,
                use: [
                    {
                        loader: '@ngtools/webpack',
                        options: {
                            tsConfigPath: 'tsconfig.json'
                        }
                    }
                ],
            },
    plugins: [
        new AotPlugin({
            "tsConfigPath": "tsconfig.json",
            "skipCodeGeneration": true
        })
```

the build breaks because for some reason the plugin [tries to find lazyloaded routes](https://github.com/angular/angular-cli/blob/66faea66fd401ec2939152a40da95175c90a7896/packages/%40ngtools/webpack/src/plugin.ts#L561) in the entryModule that I don't pass:

```
class AotPlugin
   ...
   _make(compilation, cb) {
        ...
        this._donePromise = Promise.resolve()
            ...
            .then(() => {
            // We need to run the `listLazyRoutes` the first time because it also navigates libraries
            // and other things that we might miss using the findLazyRoutesInAst.
            this._discoveredLazyRoutes = this.firstRun
                ? this._getLazyRoutesFromNgtools()
                : this._findLazyRoutesInAst();
```

And I don't see any option to disable this processing.

Is there anything I can do with it? I simply want to use `@ngtools/loader` with type checking that's why I use AoT plugin.

**Comment by filipesilva** [comment]
As the docs entry you linked indicated, it is an optional property **if** you have it specified in `angularCompilerOptions` (this is an entry in your tsconfig). So you can either provide it in the plugin options or in the tsconfig. 

If you do neither, the plugin will also try to figure out what your entry module is from your boostrap, but that might not work depending on your code. Lazy route detection isn't something you can disable nor that we plan or making optional.
