### ISSUE TITLE
Add explanation how universal rendering works

### ISSUE THREAD

**Issue by theunreal** [angular/angular-cli#7798]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions.
1.4.3

### Desired functionality.
I followed [this tutorial](offical tutorial) about implementing universal rendering for a SEO-friendly app, and I ended up successfully with 2 folders:

**dist folder** - the app production files

**dist-server**- the bundle I just created, has main.js and styles.css in it.

For the dist folder only, I was just uploading it to my web hosting provider directory and could view the app directly with the index.html.

My question is - How I can apply the dist-server directory to pre-render my app and serve it in my web host server? I couldn't find any information about how to serve the app in the [offical tutorial](https://github.com/angular/angular-cli/wiki/stories-universal-rendering)

**Comment by RicardoVaranda** [comment]
The documentation has now been updated and it answers your question.

https://github.com/angular/angular-cli/wiki/stories-universal-rendering#step-5-setup-a-webpack-config-to-handle-this-node-serverts-file-and-serve-your-application

This can now be closed 👍
