### ISSUE TITLE
Getting error while installation of Agular/Cli

### ISSUE THREAD

**Issue by gauravgoyal5** [angular/angular-cli#7807]
[2017-09-24T06_32_06_337Z-debug.log](https://github.com/angular/angular-cli/files/1327087/2017-09-24T06_32_06_337Z-debug.log)
I am installing Angular/Cli npm on Windows 10 I have downloaded latested Nodejs & intalled then I am trying to install Angular/Cli but after some time it is show error message :
Unexpected end of input at 1:17100 "eslint-plugin-codecs":"^1.0.3","istanbul":"~",mocha":*","uglifyjs
Here is screen shot : 

![image](https://user-images.githubusercontent.com/6926513/30779994-226a1f10-a11e-11e7-86ca-9d6c28f3fb62.png)

Please let me know how can I install & create my first Project. Attached log file as well.

Thanks,
Gaurav

**Comment by smashraid** [comment]
Hi Gaurav 
Execute npm config get prefix on bash, go to that directory find npm folder and add Authenticated User privilege to the folder and execute npm install again.

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
