### ISSUE TITLE
Angular-cli - Remote authorization bypass vulnerability 

### ISSUE THREAD

**Issue by MaorShwartz** [angular/angular-cli#7808]
Hi,

I would like to report authorization bypass vulnerability found in Angular-cli version 1.3.2 (latest).

In your documentation you write that you can run the Angular-cli with the following command:

ng serve --host 0.0.0.0 --port 4201

By doing so, it is possible to access Angular-cli server that runs on localhost and bypass the Host Header Protection.

Please contact me via email for the full report - maors@beyondsecurity.com.

What we do: SSD receives information from security researchers about yet-undisclosed
security holes in various products. Once this information is received and confirmed, we will
notify the appropriate product vendor as well as selected customers who are part of the SSD
program of the security flaw in their product or service.

What we ask: When notifying the vendor, we will provide full technical details and work
with the vendor to fix the issue, and coordinate a public advisory. In return, SSD is asking to
acknowledge the researcher for finding the vulnerability and SSD for reporting the
vulnerabilities to the vendor in official vendor advisories about this issue.

**Comment by hansl** [comment]
Hi,

This is a known "problem", and people are using that feature quite extensively. Please note that we write a large warning message when users are running `serve` in production mode, and it is not a supported use case.

The assumption that we are making (and maybe we could be clearer about it) is that you always run your development server (which is what `ng serve` is) in a local development environment, on a computer that's firewalled properly from the internet. We do not support serving your website to the public as a production environment.

As such, the Host header protection is of little use for a development server use case like this one.

Closing this as answered, but if you feel there are more points to make, you can either open a new issue or answer this one directly and ping me.
