### ISSUE TITLE
Backslash escape characters are sometimes removed from css

### ISSUE THREAD

**Issue by mamohr** [angular/angular-cli#7811]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.4.3
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4
```
### Repro steps.

1. Create a blank application with `ng generate app css-bug`
2. Add the following code to the styles.css file:
```
/* not working */
.a\25 {}
/* working */
.\31 25\25 { }
/* working */
.a 1\25 {}
/* not working */
.a 1a\25 { }
```
3. Build the app with `ng build --extractCss`
4. Instead of the content from styles.css the following is the content of the css file. Notice the missing `\`:
```
/* not working */
.a25 {}
/* working */
.\31 25\25 { }
/* working */
.a 1\25 {}
/* not working */
.a 1a25 { }
```

### The log given by the failure.
No errors given in the log

### Desired functionality.
Escaping backslashes should be preserved

### Mention any other details that might be useful.
Without the `--extractCSS`the css received by the application has the same error.

**Comment by azzimuth** [comment]
I have similar problem with classes which have double dashes in their name.  The classes with double dashes in SCSS are compiled without backslash which causes problems in IE11. What is the solution to this?
