### ISSUE TITLE
Cannot find module.

### ISSUE THREAD

**Issue by mhr92** [angular/angular-cli#7816]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
ng --version
angular-cli: 1.0.0-beta.28.3
node --version
v6.11.3
npm --version
5.4.2
Windows 10

### Repro steps.
The code for the issues:
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormGroup, FormControl, Validators, FormBuilder } from '@angular/forms';
import { ProductService } from '../product.service';
import { CategoryService } from '../category.service';
import { Observable } from 'rxjs/Observable';
import { Product } from '../product';
import { Category } from '../category';
 
@Component({
    selector: 'app-create-product',
    templateUrl: './create-product.component.html',
    styleUrls: ['./create-product.component.css'],
    providers: [ProductService, CategoryService]
})
 
// component for creating a product record
export class CreateProductComponent {
 
    // our angular form
    create_product_form: FormGroup;
 
    // @Output will tell the parent component (AppComponent) that an event happened in this component
    @Output() show_read_products_event = new EventEmitter();
 
    // list of categories
    categories: Category[];
 
    // initialize 'product service', 'category service' and 'form builder'
    constructor(
        private productService: ProductService,
        private categoryService: CategoryService,
        formBuilder: FormBuilder
    ){
        // based on our html form, build our angular form
        this.create_product_form = formBuilder.group({
            name: ["", Validators.required],
            price: ["", Validators.required],
            description: ["", Validators.required],
            category_id: ["", Validators.required]
        });
    }
 
    // user clicks 'create' button
    createProduct(){
 
        // send data to server
        this.productService.createProduct(this.create_product_form.value)
            .subscribe(
                 product => {
                    // show an alert to tell the user if product was created or not
                    console.log(product);
 
                    // go back to list of products
                    this.readProducts();
                 },
                 error => console.log(error)
             );
    }
 
    // user clicks the 'read products' button
    readProducts(){
        this.show_read_products_event.emit({ title: "Read Products" });
    }
 
    // what to do when this component were initialized
    ngOnInit(){
        // read categories from database
        this.categoryService.readCategories()
            .subscribe(categories => this.categories=categories['records']);
    }
}

### Mention any other details that might be useful.

![2017-09-25 1](https://user-images.githubusercontent.com/32242424/30790420-6221917c-a1de-11e7-8506-f9c22326a705.png)

**Comment by deebloo** [comment]
@mhr92 it looks like your import paths are wrong

**Comment by deebloo** [comment]
@mhr92 also it looks like you are using a very very old version of the cli. I would recommend updating

**Comment by mhr92** [comment]
@deebloo may I know what the import path that are wrong?

**Comment by filipesilva** [comment]
@mhr92 in your console log, the errors in red are indicating the `../category.service` and `../category` paths cannot be found. It sounds like you have those paths wrong.

We reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
