### ISSUE TITLE
using UglifyJS to reduce build size

### ISSUE THREAD

**Issue by m98** [angular/angular-cli#7817]
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
### Version:
```
@angular/cli: 1.4.1
node: 8.4.0
os: linux x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/platform-server: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.1
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
typescript: 2.3.4

```
### Feature request:
According to the [build docs](https://github.com/angular/angular-cli/blob/7d29450b3ece327ae0e786933227d0484ec18406/docs/documentation/build.md) it seems that CLI is already using Ugifyjs to minify the JavaScript assets.  But when I see the codes in the `dist`, methods' names are still the same as what they were defined in the code.

I have some service methods with long descriptive names which are helpful for development, but they need to be shortened for the production mode, and I used them repeatedly in the project.

I was thinking `ng build --prod --build-optimizer` will do the Uglification too, it could reduce about 10% (which is awesome) but still, the methods names are same as before. 

### Suggestion:
we can have a flag for this, like `--uglify` to have a different uglified version of the build.

**Comment by filipesilva** [comment]
Uglify is used on production build (`--prod`) already. You can see the options we use in https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/models/webpack-configs/production.ts#L123-L149.

**Comment by m98** [comment]
Sure, I see.
But why some methods name is still long and not uglified at all?

Is there any special option I forgot to set? Or, it's just lack of the uglification over the whole source code. Actually, I know it's hard to manage source uglification since it can break something.

**Comment by filipesilva** [comment]
This thread makes me think uglify doesn't do what you want automatically in a safe way https://github.com/mishoo/UglifyJS2/issues/103. In regards to uglification options, the CLI doesn't expose them.
