### ISSUE TITLE
Run generate command with the lintFix flag using a lint from npm scripts.

### ISSUE THREAD

**Issue by rokerkony** [angular/angular-cli#7818]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

Hi,
It would be nice to use npm script (if available) for lint when generating new component and `lintFix` is set to true.
Anyone can have a lint command provided and use e.g. `--type-check`
Our use case is:
```
"scripts": {
    ...
    "lint": "npm run ng lint -- --format stylish --type-check",
    ...
}
```

### Versions.
All since `lintFix` was introduced.

### Repro steps.
1. Include to tsconfig rules which require `--type-check`.
2. Run `ng g c component-name --lint-fix`

### The log given by the failure.
```
Warning: The 'match-default-export-name' rule requires type information.
Warning: The 'no-for-in-array' rule requires type information.
Warning: The 'no-inferred-empty-object-type' rule requires type information.
Warning: The 'no-unbound-method' rule requires type information.
Warning: The 'no-unused-variable' rule requires type information.
Warning: The 'no-use-before-declare' rule requires type information.
Warning: The 'no-void-expression' rule requires type information.
Warning: The 'return-undefined' rule requires type information.
Warning: The 'use-default-type-parameter' rule requires type information.
```

### Desired functionality.
Run `npm run lint` instead `ng lint` only

**Comment by clydin** [comment]
Upgrading tslint to 5.4.3 or above eliminates the need to add the type-check option to enable rules requiring type information.  The option will now only enable report of semantic compilation errors.

**Comment by rokerkony** [comment]
that is weird because we use `tslint@v5.7.0` and I'm still getting these errors when I run it from CLI... maybe CLI has it's own version installed? :(

**Comment by clydin** [comment]
Was able to track down the cause and slight adjustment to the CLI is needed to support the behavior.  A PR has been submitted.
