### ISSUE TITLE
I am using windows 10 (x64) after installing angular, installation finished with the following message and ng help is not ruunign :npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

### ISSUE THREAD

**Issue by wasimned** [angular/angular-cli#7820]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by mittal01091997** [comment]
Did you installed the Angular Cli with the command:
[sudo] npm install -g @angular/cli

Making the Cli installed globally is important.
If you wish to try re-installing the Cli, follow commands as follows:

[sudo] npm uninstall -g angular-cli @angular/cli 
npm cache clean 
[sudo] npm install -g @angular/cli

**Comment by RussianDjoNIK** [comment]
Actually it's not an issue for the angular-cli. There is another [issue#17671](https://github.com/npm/npm/issues/17671) for npm. In some cases it has already fixed.

**Comment by wasimned** [comment]
I found a working 5 step solution here:
https://stackoverflow.com/questions/37991556/ng-is-not-recognized-as-an-internal-or-external-command
.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.

**Comment by wasimned** [comment]
thanks Filipe Silva.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
