### ISSUE TITLE
generate not respecting the inline styles, inline templates, specs in .angular-cli.json

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#7829]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
macOS Sierra 10.12.6
@angular/cli: 1.4.3
node: 6.11.3
os: darwin x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4

### Repro steps.
```
ng new ignite --minimal
cd ignite
ng g c heroes --flat
```

### The log given by the failure.
This creates 4 files.

```
heroes.component.html
heroes.component.scss
heroes.component.spec.ts
heroes.component.ts
```

### Desired functionality.

I expected only 1 file, `heroes.component.ts`, to be created.

### Mention any other details that might be useful.
The `.angular-cli.json` contains the proper settings.

Also, if I run `ng g c heroes --flat --it --is --spec false` then I get one file.

It appears that the commands are not checking the json file's settings.

![image](https://user-images.githubusercontent.com/1202528/30840411-114a124e-a245-11e7-890a-63caa03680f3.png)

**Comment by johnpapa** [comment]
I see now that `ng g c foo` is broken, but `ng g component` works. Same for the other aliases I tried.

@Brocco is aware and on it.

**Comment by johnpapa** [comment]
Is there an estimated fix date on this? @Brocco

**Comment by hansl** [comment]
We fixed this with the new workspace and the way the flags are used and propagated. Closing this as fixed.
