### ISSUE TITLE
ERRORS in angular-cli installation

### ISSUE THREAD

**Issue by OsnatShoshani** [angular/angular-cli#7833]
I am installing Angular/Cli npm on Windows 10 I have downloaded latested Nodejs & intalled then I am trying to install Angular/Cli but after some time it is show error message :
npm ERR! Windows_NT 10.0.10586
Here is screen shot :

C:\Users\pb5>npm install -g @angular/cli
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pb5\npm-debug.log

Please let me know how can I install & create my first Project. 

Thanks,

**Comment by Mahmoud-Alsayed** [comment]
1. Update your Node.js to the latest version
2. Make sure you have the latest version of npm, execute `npm i -g npm`
3. Make sure that you can access this website with your browser without any SSL warning [npm registry](https://registry.npmjs.org/)
4. If this doesn't solve your problem. please, read this [article ](http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm)

**Comment by OsnatShoshani** [comment]
I tried it but didn't work

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.

**Comment by filipesilva** [comment]
If I had to bet it's probably a proxy problem.

**Comment by OsnatShoshani** [comment]
I tried all the options but didn't ןnstall the angular/cli

**Comment by Alon-Or** [comment]
I got the solution from: [https://github.com/npm/npm/issues/7519](url)

my answer is here:

In Nodejs 9.3.0 npm@5.6.0 behind a Fortigate FW with SSL inspection I had problems installing angular/cli, was getting "npm ERR! code SELF_SIGNED_CERT_IN_CHAIN"
So I did:
`npm config set strict-ssl false`
then:
**npm install npm -g --ca NULL**
and now I'm able to install `@angular/cli@1.63`
with
`npm install -g @angular/cli`

**Comment by Gonzalo-Orellana** [comment]
Hi!... I solved it by changing the internet network to which I was connected, since the error appeared to me when I was on a network with proxy. I shared and my cell phone internet and holy remedy.
