### ISSUE TITLE
ng build -bh /app/ does not work. However ng serv -bh /app/ works

### ISSUE THREAD

**Issue by pm0202** [angular/angular-cli#7842]
- [x ] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
C:\projects\adre\branches\v0.0.4-beta\VCS_UI_CLI>ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.5.0-beta.1
node: 6.11.3
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.5.0-beta.1
@angular/compiler-cli: 2.4.10
typescript: 2.0.10

node --version
v6.11.3

npm --version
3.10.8

Windows 7 Professional

### Repro steps.
when I use the ng serv -bh /app/, I can invoke the url, localhost:9880/app. When I use build I get 404.

### The log given by the failure.
404

### Desired functionality.
same as ng serve

**Comment by filipesilva** [comment]
This sounds like a deployment problem. Please take a look at https://angular.io/guide/deployment for information about how to deploy your application.
