### ISSUE TITLE
How to generate angular-cli in an existing project with existing node_modules already?

### ISSUE THREAD

**Issue by idiglove** [angular/angular-cli#7847]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] In my project, there is a gulp installed already. I can't install angular-cli, I needed to remove package.json. 
```

### Versions.
@angular/cli: 1.4.3
node: 6.11.0
os: win32 x64

### Repro steps.
Having gulp installed already.
Using the command npm install -g @angular/cli, gets an error: 

### Desired functionality.
Beign able to use angular 4 with my PHP Zend framework project

**Comment by istiti** [comment]
What error?

**Comment by filipesilva** [comment]
The `ng new command` generates a whole new project including a new `package.json`. If you have an existing project and want to incorporate a Angular CLI application inside of it, use `ng new` outside of your project and then move and merge the files manually.

**Comment by kumaresan-subramani** [comment]
Use below command to create new project inside old project

> npm run ng generate application projectName
