### ISSUE TITLE
ERROR while installing npm

### ISSUE THREAD

**Issue by OsnatShoshani** [angular/angular-cli#7850]
I am trying to install npm on Windows 10 I have downloaded latested Nodejs & intalled then I am trying to install npm but it is show error message :
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\pb5\package.json'
Here is screen shot :

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\pb5>npm install
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\pb5\package.json'
npm WARN pb5 No description
npm WARN pb5 No repository field.
npm WARN pb5 No README data
npm WARN pb5 No license field.

Please let me know how can I install & create my first Project. 

Thanks,

**Comment by Mahmoud-Alsayed** [comment]
It's clearly state that you don't have a `package.json` file, You can use `npm install` to install the dependencies in an already existed `package.json` file. As you have installed Node.JS, you have already installed npm. So you can now install angular cli, `npm install @angular/cli -g`

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
