### ISSUE TITLE
Generate a component with --module app-routing.module.ts fails

### ISSUE THREAD

**Issue by bmvantunes** [angular/angular-cli#7852]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.3
node: v6.11.1
npm: 3.10.10
tested on ubuntu and macos

### Repro steps.
`ng new my-test --routing`
`cd my-test`
`ng generate component my-comp --module app-routing.module.ts`

if I do --module app.module.ts, it works. This bug is only related with routing modules.
The error is not related with `ng new my-test --routing` because the routing module was created.

### The log given by the failure.
```
Error: File /src/app/app-routing.module.ts does not exist.
File /src/app/app-routing.module.ts does not exist.
```

### Desired functionality.
It was working on @angular/cli version 1.3.2, not working after 1.4.0

**Comment by bmvantunes** [comment]
@filipesilva @Brocco, I was debugging the @angular/cli and the problem is in this line: 
https://github.com/angular/devkit/blob/da8c3ab822ae85a01b8d157a4605c19b9cec5836/packages/schematics/angular/component/index.ts#L129

If I remove `&& !path.endsWith('-routing.module.ts')` everything works like in the past, but I bet that you have that check for some reason, that's why I'm not doing a PR with that "fix"...

**Comment by Brocco** [comment]
@bmvantunes Thanks for reporting and FYI, you were correct on the line needing fixed, but the same issue was also occurring with pipes, both are fixed in the referenced PR to devkit.

**Comment by bmvantunes** [comment]
Thank you very much 👍 

Sorry for not catching the Pipe error.
Next time that I find something I will try to do a pull request to help you guys!
