### ISSUE TITLE
Angular-cli should provide fully configured webpack (upon ejecting app)

### ISSUE THREAD

**Issue by mittal01091997** [angular/angular-cli#7856]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] Better configured webpack for ejected angular app(s).
```

### Versions.
@angular/cli: 1.4.2
node: 6.11.0
os: win32 x64

### Desired functionality.
Angular now have started to manage its bundling via webpack. Upon Ejecting the project, Angular-Cli automatically configures the application to use webpack. However, the app is not fully configured.
The Script files that are generated upon building the app is not minified. Images and Icons are not automatically copied into the dist folder.
**If the Cli will do all this upon ejecting the app, it will be great convenient for user.**

**(Optional Functionality) =>**  When All configurations for webpack has been developed for cli, the new apps that will be generated via ng new may be made pre-ejected (no need to eject it manually).

### Mention any other details that might be useful.
In The [Angular Webpack guide page](https://angular.io/guide/webpack), The [Sample Application](https://angular.io/generated/zips/webpack/webpack.zip) provided by Angular Officials is much better. It minifies the script files, copies images (and many things i don't yet understand).

**Comment by filipesilva** [comment]
When you use `ng eject`, you can also pass in the same options you pass into `ng build`. This will make a webpack configuration for the flags you used. For a production build webpack config, use `ng eject --prod`.
