### ISSUE TITLE
Sample Angular 4 application is needed for practicing the Protractor tool

### ISSUE THREAD

**Issue by Vasundhara-vasu** [angular/angular-cli#7857]
Hi All,

I would like to learn "Protractor" automation end 2 end testing tool for "angular 4 application".

For that purpose i need to have a "angular 4 application" to do automation testing and i downloaded sample "angular 4 application" from Github and imported that folder into the "Visual studio code" IDE and when i run this project in the "browser" window it is displaying "loading" text continuously and the project consists of lots of errors. 

So can any one give me a sample application for which i can start learning "protractor tool" using jamsine framework. 

Or else should i need to learn "angular4 application" development in order to learn "protractor tool" for "angular application"

**Comment by textbook** [comment]
This is nothing to do with the Angular CLI software. But yes, it probably doesn’t make sense to learn to use a tool to test a thing you can’t actually build.

**Comment by textbook** [comment]
This is nothing to do with the Angular CLI software. But yes, it probably doesn’t make sense to learn to use a tool to test a thing you can’t actually build.

**Comment by filipesilva** [comment]
Heya @Vasundhara-vasu, you can read about how to setup a basic Angular app in https://angular.io/guide/quickstart.

**Comment by Vasundhara-vasu** [comment]
Thank you all for your replies ,

i am following the instructions given in https://angular.io/guide/quickstart. link to develop angular app. After that i start practicing the Protractor test scripts on this develop app.
