### ISSUE TITLE
Component Showcases

### ISSUE THREAD

**Issue by manuelhuber** [angular/angular-cli#7860]
Hello,

I want to create showcases for my components. For every MyFancyComponent I want a MyFancyComponentShowcase where I display the component with some dummy data. My question is:
How would I best go about this in terms of build config? I want the Showcases to be viewable on a custom showcase page that's available under a certain sub-route. I don't want the showcases to be in the prod build. And I want to write as little boilerplate code as possible.  The best solution would be creating a my-fancy.component.showcase.ts which is automatically detected and integrated via naming convention.

Thankfull for every input!

**Comment by intellix** [comment]
It sounds like what you want is:
- storybook: https://github.com/storybooks/storybook/issues/269
or 
- component-lab: https://github.com/synapse-wireless-labs/component-lab

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Cheers to @intellix for the insightful comment though!
