### ISSUE TITLE
Component name contains `component` twice on ng generate

### ISSUE THREAD

**Issue by DeborahK** [angular/angular-cli#7861]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

v 1.2.4 and v 1.4.3

### Repro steps.

In the CLI version 1.2.4 I could use the following command:

ng g c test.component

And it would generate files with the name:
test.component.css
test.component.html
...

In the CLI version 1.4.3., the same command generates:

test.component.component.cs
test.component.component.html
...

 And adds this to the module:
  declarations: [
    AppComponent,
    WelcomeComponent,
    Test.ComponentComponent
  ]

### Desired functionality.

It should be smart enough to handle the `component` in the provided name as it did in v1.2.4

**Comment by filipesilva** [comment]
@Brocco is this intended?

**Comment by Brocco** [comment]
Not intended, looking into this.
