### ISSUE TITLE
UnhandledPromiseRejectionWarning after upgrade from 1.3.2 to 1.4.2

### ISSUE THREAD

**Issue by rodolfojnn** [angular/angular-cli#7866]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.3
node: 7.5.0
npm: 5.4.2
os: win32 x64
@angular/animations: 4.3.2
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/compiler-cli: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/platform-server: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.4.3
typescript: 2.3.4

### Repro steps.
ng build --prod

### The log given by the failure.
94% asset optimization(node:4864) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token: punc ())
(node:4864) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Desired functionality.
Generate build

"ng serve" works correctly, but when I try to generate a production build with "ng build --prod" or "ng build --prod --build-optimizer" the above error.

Searching, I realized it's something related to Uglify, but I'm not sure.

**Comment by rodolfojnn** [comment]
Related #7725

**Comment by nithincmncm** [comment]
My Programme for grib2json file: 
```
let grib2json = require('D:/Project/weacast-grib2json')
// First arg is the input file path, second arg is CLI options as JS object 
grib2json('D:/Project/20170829_025122_.grb2', {
  data: true,
  output: 'output.json'
})
.then(function (json) {
  // Do whatever with the json data, same format as output of the CLI 
})
```

> **I am try to grib file2json but i got some error. Error given bellow how i fix it Please help anyone Advance Thank you.** 

 

1. 

node:3096) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: D:\Project\weacast-grib2json\bin\grib2json.cmd --data --output output.json D:/Project/20170829_025122_.grb2
The system cannot find the path specified.

2

![er](https://user-images.githubusercontent.com/31437600/36579396-dfd2fbb2-1888-11e8-8d65-6dcfb0bb7bfa.PNG)



(node:3096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
