### ISSUE TITLE
Suggestion to generate component relationship graph

### ISSUE THREAD

**Issue by wittml** [angular/angular-cli#7867]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.2.1
node: 6.9.5
os: win32 x64

### Desired functionality.

With even a medium size project, a large number of components can be generated. Some are parents and children, some are siblings, and some are unrelated. It would be very useful to be able to generate some sort of graph (visual or tabular) that can be quickly used as an overview of how the components are related. This can be used by developer's trying to remember where a function is implemented and it would be very useful for new team members to familiarize themselves with the project.

**Comment by ciesielskico** [comment]
Augury does that already

**Comment by Brocco** [comment]
I agree with @ciesielskico that there are other tools that provide this functionality such as Augury.
