### ISSUE TITLE
problem with deploy url build

### ISSUE THREAD

**Issue by ajit-jain** [angular/angular-cli#7879]
i m deploying my app through

> ng build --env=prod --prod --aot --build-optimizer --deploy-url //-distribution-.cloudfront.net/ --output-hashing none --nosourcemap

after build in dist/index.html

<script type="text/javascript" src="//-distribution-.cloudfront.net/polyfills.bundle.js">
</script>
<script type="text/javascript" src="/-distribution-.cloudfront.net/scripts.bundle.js"></script>
<script type="text/javascript" src="//-distribution-.cloudfront.net/main.bundle.js"></script>

it only produces single '/' for scripts.bundle.js why???

**Comment by filipesilva** [comment]
Heya, I tried doing `ng build --deploy-url //-distribution-.cloudfront.net/` on the latest version (`1.5.0-beta.2`) and this is what I got in `index.html`:
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>MasterProject</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
  <app-root></app-root>
<script type="text/javascript" src="//-distribution-.cloudfront.net/inline.bundle.js"></script><script type="text/javascript" src="//-distribution-.cloudfront.net/polyfills.bundle.js"></script><script type="text/javascript" src="//-distribution-.cloudfront.net/scripts.bundle.js"></script><script type="text/javascript" src="//-distribution-.cloudfront.net/styles.bundle.js"></script><script type="text/javascript" src="//-distribution-.cloudfront.net/vendor.bundle.js"></script><script type="text/javascript" src="//-distribution-.cloudfront.net/main.bundle.js"></script></body>
</html>
```

So I don't see the single slash here. Can you provide more details including a way to reproduce?

**Comment by ajit-jain** [comment]
i don't know why it produced but i correct it out by replacing //-distribution-.cloudfront.net/  with https://-distribution-.cloudfront.net/ in ng build command

**Comment by filipesilva** [comment]
Glad to hear you have it sorted then 👍

**Comment by ajit-jain** [comment]
hi @filipesilva  sir, i was encountered with  same problem of getting  single slash after deploying,  then i figured out that my project's package.json contains angular-cli of version ^1.4.2 but on my machine it is 1.4.3 globally installed after that i degarade it 1.4.2  and update my nodejs to 8.6.0 then build produce results that i wanted. Sir can you suggest me any reference to clear my doubts on these things i did above how these are connected to angular build or you state me how these are connected .

**Comment by filipesilva** [comment]
@ajit-jain I'm sorry, but I don't quite understand what you are trying to say. Did you find a way to reproduce this problem? If you have, I'll reopen the issue to investigate.

Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
