### ISSUE TITLE
Mac OSX Yosemite, node - v6.1.0, ng --version is not working (ng: command not found)

### ISSUE THREAD

**Issue by info007** [angular/angular-cli#788]
step:1 - Installed angular-cli gloablly and used below commad to create my-app structure

step:2 - sudo /Users/xxx/node_modules/angular-cli/bin/ng new my-app

Getting Error as: 
(node:84630) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing ng2
  create .clang-format
  create .editorconfig
  create src/app/lego-search6.component.css
  create src/app/lego-search6.component.html
  create src/app/lego-search6.component.spec.ts
  create src/app/lego-search6.component.ts
  create src/app/environment.ts
  create src/app/index.ts
  create src/app/shared/index.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/system-config.ts
  create src/tsconfig.json
  create src/typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config/environment.dev.ts
  create config/environment.js
  create config/environment.prod.ts
  create config/karma-test-shim.js
  create config/karma.conf.js
  create config/protractor.conf.js
  create e2e/app.e2e.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create e2e/typings.d.ts
  create .gitignore
  create package.json
  create public/.npmignore
  create tslint.json
  create typings.json
getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)

**Comment by hansl** [comment]
Node 6 isn't fully supported yet. We have to test it properly. There's a PR in the work but it's still a way to be 100% compatible. We'll update the README when we have full support.
