### ISSUE TITLE
AOT results in many module cache misses

### ISSUE THREAD

**Issue by MiladSadinam** [angular/angular-cli#7886]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Windows 7
node: v8.1.2
npm: 5.4.2
@ngtools/webpack: 1.7.1
webpack-dev-server: 2.8.2
webpack: 3.6.0

### Repro steps.
Code is not open source. I hope this will be enough.

webpack.config.ts:
```
...
devServer = {
				contentBase: path.resolve(rootDir, 'aot'),
				port: backendConfig.plano_webserver_port,
				historyApiFallback: true, // enable routing without "#"
			},
output.path = path.resolve(rootDir, 'aot'),
plugins: [
new AotPlugin.AotPlugin({
					tsConfigPath: path.resolve(rootDir, 'tsconfig.json'),
					entryModule: path.resolve(rootDir, 'src', 'app.module#AppModule'),
				  })
]
....
```

tsconfig.json:
```
{
    "compilerOptions": {
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "module": "commonjs",
        "moduleResolution": "node" ,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "removeComments": false,
        "sourceMap": true,
        "target": "es5",
        "baseUrl": ".",
		"types" : ["node", "custom/jquery-slick", "jasmine"],
		"typeRoots": ["node_modules/@types", "typings"],
        "paths": {
            "@plano/*": [
                "src/*"
			],
			"./*": [
                "./*"
            ]
        },
        "lib": ["es2015", "dom"]
    },
    "exclude": [
        "node_modules",
        "typings/main",
        "typings/main.d.ts"
    ],
	"compileOnSave": false,

	"files": [
		"src/app.module.ts",
		"src/bootstrap.ts"
	  ],
	
	  "angularCompilerOptions": {
	   "genDir": "aot",
	   "skipMetadataEmit" : true
	 }
}
```

### Desired functionality.
I am transforming our project from JIT to AOT using @ngtools/webpack. I am using webpack-dev-server. Initial build time is around 60sec. When I change a single .html file the rebuild time is again around 60s which is not acceptable. The problem seems to be that **all** ".ngfactory.ts" and ".scss.shim.ngstyle.ts" are build on every rebuild. Webpack uses "fileTimestamps" in Compilation.addModule() to determine if a module has to be rebuild. But for these files which are generated by AOT compiler there exists no such fileTimeStamp. I guess because they are only written to the virtual file system? They do not exist in my AOT dist folder.

I am not sure if this is a bug or wrong configuration from my side. I would appreciate any help.

**Comment by thw0rted** [comment]
I'm still learning so I don't know really know the right question to ask, but my symptoms are similar to the OP -- was using JIT, recently set up AOT for my production build, and build time for subsequent runs (even with zero changes to any files) is more or less identical.  Nothing appears to be cached.

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by MiladSadinam** [comment]
I tried to activate the AngularCompilerPlugin.AngularCompilerPlugin plugin for development about two weeks ago with latest version and incremental build still took like 1min.

**Comment by MiladSadinam** [comment]
We have switched our project to angular-cli and incremental AOT builds have now acceptable performace. I close this issue.
