### ISSUE TITLE
ng serve doesn't recognize my angular project

### ISSUE THREAD

**Issue by Danieliverant** [angular/angular-cli#7887]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

angular-cli: 1.0.0-beta.28.3
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3

### Repro steps.

I created an angular project using Angular CLI.
All was fine I completed my project,
tried to upload it to gitHub using this commands:

cd -into my angular project-
git remote add origin https://github.com/Danieliverant/ToDo-list-site
git push origin master
ng github-pages:deploy

got some errors here (and no files uploaded)

and then I tried to check if ng serve still working - and no. 
plz help me guys I have to get my project running again.

### The log given by the failure.
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'angular/cli' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData angular/cli
8 silly fetchOtherPackageData angular/cli
9 silly cache add args [ 'angular/cli', null ]
10 verbose cache add spec angular/cli
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'angular/cli',
11 silly cache add   scope: null,
11 silly cache add   escapedName: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'angular/cli',
11 silly cache add   spec: 'github:angular/cli',
11 silly cache add   type: 'hosted',
11 silly cache add   hosted:
11 silly cache add    { type: 'github',
11 silly cache add      ssh: 'git@github.com:angular/cli.git',
11 silly cache add      sshUrl: 'git+ssh://git@github.com/angular/cli.git',
11 silly cache add      httpsUrl: 'git+https://github.com/angular/cli.git',
11 silly cache add      gitUrl: 'git://github.com/angular/cli.git',
11 silly cache add      shortcut: 'github:angular/cli',
11 silly cache add      directUrl: 'https://raw.githubusercontent.com/angular/cli/master/package.json' } }
12 verbose addRemoteGit caching angular/cli
13 verbose addRemoteGit angular/cli is a repository hosted by github
14 silly tryGitProto attempting to clone git://github.com/angular/cli.git
15 silly tryClone cloning angular/cli via git://github.com/angular/cli.git
16 verbose tryClone git-github-com-angular-cli-git-abc2a622 not in flight; caching
17 verbose correctMkdir C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
18 verbose makeDirectory C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes creation not in flight; initializing
19 verbose makeCacheDir UID & GID are irrelevant on win32
20 info git [ 'clone',
20 info git   '--template=C:\\Users\\danyl\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
20 info git   '--mirror',
20 info git   'git://github.com/angular/cli.git',
20 info git   'C:\\Users\\danyl\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-angular-cli-git-abc2a622' ]
21 verbose git clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-abc2a622: Cloning into bare repository 'C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-abc2a622'...
21 verbose git clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-abc2a622: fatal: remote error:
21 verbose git clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-abc2a622:   Repository not found.
22 silly tryHTTPS attempting to clone git+https://github.com/angular/cli.git
23 silly tryClone cloning angular/cli via git+https://github.com/angular/cli.git
24 verbose tryClone git-https-github-com-angular-cli-git-7e325762 not in flight; caching
25 verbose correctMkdir C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
26 info git [ 'clone',
26 info git   '--template=C:\\Users\\danyl\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
26 info git   '--mirror',
26 info git   'https://github.com/angular/cli.git',
26 info git   'C:\\Users\\danyl\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-https-github-com-angular-cli-git-7e325762' ]
27 verbose git clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-angular-cli-git-7e325762: Cloning into bare repository 'C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-angular-cli-git-7e325762'...
27 verbose git clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-angular-cli-git-7e325762: remote: Repository not found.
27 verbose git clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-angular-cli-git-7e325762: fatal: repository 'https://github.com/angular/cli.git/' not found
28 silly trySSH attempting to clone git@github.com:angular/cli.git
29 silly tryClone cloning angular/cli via git@github.com:angular/cli.git
30 verbose tryClone git-github-com-angular-cli-git-05516032 not in flight; caching
31 verbose correctMkdir C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
32 info git [ 'clone',
32 info git   '--template=C:\\Users\\danyl\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
32 info git   '--mirror',
32 info git   'git@github.com:angular/cli.git',
32 info git   'C:\\Users\\danyl\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-angular-cli-git-05516032' ]
33 error git clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032: Cloning into bare repository 'C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032'...
33 error git clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032: Host key verification failed.
33 error git clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032: fatal: Could not read from remote repository.
33 error git clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032:
33 error git clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032: Please make sure you have the correct access rights
33 error git clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032: and the repository exists.
34 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032
34 silly fetchPackageMetaData Cloning into bare repository 'C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032'...
34 silly fetchPackageMetaData Host key verification failed.
34 silly fetchPackageMetaData fatal: Could not read from remote repository.
34 silly fetchPackageMetaData
34 silly fetchPackageMetaData Please make sure you have the correct access rights
34 silly fetchPackageMetaData and the repository exists.
34 silly fetchPackageMetaData
34 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:198:12)
34 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
34 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
34 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:920:16)
34 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
34 silly fetchPackageMetaData  error for angular/cli { Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032
34 silly fetchPackageMetaData Cloning into bare repository 'C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032'...
34 silly fetchPackageMetaData Host key verification failed.
34 silly fetchPackageMetaData fatal: Could not read from remote repository.
34 silly fetchPackageMetaData
34 silly fetchPackageMetaData Please make sure you have the correct access rights
34 silly fetchPackageMetaData and the repository exists.
34 silly fetchPackageMetaData
34 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:198:12)
34 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
34 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
34 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:920:16)
34 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
34 silly fetchPackageMetaData   killed: false,
34 silly fetchPackageMetaData   code: 128,
34 silly fetchPackageMetaData   signal: null,
34 silly fetchPackageMetaData   cmd: 'git -c core.longpaths=true clone --template=C:\\Users\\danyl\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates --mirror git@github.com:angular/cli.git C:\\Users\\danyl\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-angular-cli-git-05516032' }
35 silly rollbackFailedOptional Starting
36 silly rollbackFailedOptional Finishing
37 silly runTopLevelLifecycles Finishing
38 silly install printInstalled
39 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032
39 verbose stack Cloning into bare repository 'C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032'...
39 verbose stack Host key verification failed.
39 verbose stack fatal: Could not read from remote repository.
39 verbose stack
39 verbose stack Please make sure you have the correct access rights
39 verbose stack and the repository exists.
39 verbose stack
39 verbose stack     at ChildProcess.exithandler (child_process.js:198:12)
39 verbose stack     at emitTwo (events.js:106:13)
39 verbose stack     at ChildProcess.emit (events.js:191:7)
39 verbose stack     at maybeClose (internal/child_process.js:920:16)
39 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
40 verbose cwd C:\Users\danyl\Desktop\Projects\Angular 4\toDo2
41 error Windows_NT 10.0.15063
42 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular/cli"
43 error node v6.11.3
44 error npm  v3.10.10
45 error code 128
46 error Command failed: git -c core.longpaths=true clone --template=C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:angular/cli.git C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032
46 error Cloning into bare repository 'C:\Users\danyl\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-cli-git-05516032'...
46 error Host key verification failed.
46 error fatal: Could not read from remote repository.
46 error
46 error Please make sure you have the correct access rights
46 error and the repository exists.
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]

**Comment by Brocco** [comment]
Your global version of the CLI is quite old (`1.0.0-beta.28.3`) and the command you're attempting to be used has been removed.

To deploy your app to github pages, please checkout this article [here](https://github.com/angular/angular-cli/wiki/stories-github-pages).
