### ISSUE TITLE
page loads until fail, compile says success, no console error

### ISSUE THREAD

**Issue by CHBaker** [angular/angular-cli#7889]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.1
node: 8.2.1
os: linux x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.1
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4

*also tested on macOS latest, page loads but with issues.

### Repro steps.

reproduce this issue by cloning [this repo](https://github.com/CHBaker/Cesium-Injection),
npm install, ng serve

more: this application is an attempt to using a 3rd party js lib, Cesium.js (could be related to cesium, posting there as well)

*when using ng serve --prod, tree shake removes lib, how do I stop this?

### The log given by the failure.

Google chrome loads for a long time, then displays 'Oh snap' page load failer
Firefox asks to wait or stop page 3 times, after clicking wait everytime, page loads with all failed requests for assets

Angular says compile was successful

### Desired functionality.

Page to load in normal time, prevent stop script, load 3rd party assets

compile successful or load time error, maybe?

### Mention any other details that might be useful.

[Cesium.js](https://github.com/AnalyticalGraphicsInc/cesium)

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by alan-agius4** [comment]
Closing as no further feedback provided by the author of the issue.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
