### ISSUE TITLE
Node 6.1.0, sass files are not processed - no .css output in dist

### ISSUE THREAD

**Issue by alvipeo** [angular/angular-cli#789]
Just had to repave my Windows 10 machine and installed Node 6.1.0. Then angular-cli, etc. When 'ng serve' (or build) .css files don't get created at all (node-sass is installed). But it worked in Node 5.x.x which I had installed before (the project files have not changed). Not sure this is a cli issue or node-sass though.

**Comment by hansl** [comment]
Node 6 isn't fully supported yet. We have to test it properly. There's a PR in the work but it's still a way to be 100% compatible. We'll update the README when we have full support.
