### ISSUE TITLE
bug: build does not refresh when starting with error [aot/cli:beta.2/ng:RC.0]

### ISSUE THREAD

**Issue by Toxicable** [angular/angular-cli#7890]
### Bug Report
```
- [x] bug report
```

### Versions.
fabian@fabian-VirtualBox:~/Downloads/newcompiler$ ng -v
@angular/cli: 1.5.0-beta.2
node: 8.5.0
os: linux x64
@angular/animations: 5.0.0-rc.0
...
typescript: 2.5.3

### Repro steps.
* upgrade to `1.5.0-beta.2`
* `ng new --minimal`
* upgrade package.json to `5.0.0-rc.0`
* change the app.component tempalte to have `{{idontexist}}`
* `ng serve --aot`
* notice the error 
>ERROR in Error at ng:///.../newcompiler/src/app/app.component.ts.AppComponent.html(2,8): Property 'idontexist' does not exist on type 'AppComponent'.
* change template to `{{title}}`
* notice no recompile

### Desired functionality.
Should be able to recover from initial errors

**Comment by filipesilva** [comment]
Got it, will fix.
