### ISSUE TITLE
Build Mac Works! Build Linux Fail! typeof AuthGuard

### ISSUE THREAD

**Issue by romperalph** [angular/angular-cli#7891]
### Bug Report or Feature Request
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.3
node: 8.1.4
os: darwin x64
@angular/animations: 4.4.3
@angular/cli: 1.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/platform-server: 4.4.3
@angular/router: 4.4.3
@angular/compiler-cli: 4.4.3
typescript: 2.3.4

Hi Folks! 

I need your help! I'm really lost. When I build my app in my mac os laptop, it works fine. Just a warning is dropped:

`ng build --prod`

` WARN: Output exceeds 32000 characters    `

but I need to do a linux docker image, and it drops me that error:

`  ERROR in /app/src/main.ts (12,53): Argument of type 'typeof AuthGuard' is not assignable to parameter of type 'CompilerOptions | CompilerOptions[]'.
  Type 'typeof AuthGuard' is not assignable to type 'CompilerOptions[]'.
    Property 'includes' is missing in type 'typeof AuthGuard'.` 

Do you know why the same code is working on Mac, and it drops me that error in Linux?

Thanks,

**Comment by hansl** [comment]
Hi @romperalph , 

Do you have a reproduction that we could look at?  We have linux machines here and everything works fine. It might be something specific to your own setup.

**Comment by romperalph** [comment]
Hi,
Thanks for your answer. Yes, it was in my configuration. :)
Regards,
