### ISSUE TITLE
module field in 3rd-party package.json compile error --aot 

### ISSUE THREAD

**Issue by scopsy** [angular/angular-cli#7895]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.1
node: 8.6.0
os: darwin x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0
@angular/language-service: 4.1.0

### Repro steps.
When importing a library that uses the "module" entry in their package.json file --aot build fails with the `Unexpected token: name ` Error. 
I've encountered this with the [dates-chinese](https://github.com/commenthol/date-chinese) package since lately they added the "module" entry point that points to es2015 code.
After that change, my ng builds are failing. 

### The log given by the failure.
```bash
ERROR in 0.a821737870a81bd01043.chunk.js from UglifyJs
Unexpected token: name (CalendarVietnamese) [0.a821737870a81bd01043.chunk.js:8779,6]




npm verb lifecycle @rcenter/backoffice@0.0.1~build:staging: unsafe-perm in lifecycle true
npm verb lifecycle @rcenter/backoffice@0.0.1~build:staging: CWD: /Users/dmitrigrossman/projects/rec-backoffice
npm info lifecycle @rcenter/backoffice@0.0.1~build:staging: Failed to exec build:staging script
npm verb stack Error: @rcenter/backoffice@0.0.1 build:staging: `ng build --env=staging --aot --prod`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/dmitrigrossman/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at EventEmitter.emit (events.js:213:7)
npm verb stack     at ChildProcess.<anonymous> (/Users/dmitrigrossman/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at ChildProcess.emit (events.js:213:7)
npm verb stack     at maybeClose (internal/child_process.js:927:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

### Desired functionality.
Is this something need to be fixed on the cli? or am I doing something wrong?

**Comment by clydin** [comment]
The module entry is expected to be es5 with es2015 modules; not full es2015.  Angular packages use an additional “es2015” entry to point to full es2015 code.

**Comment by Brocco** [comment]
@scopsy Please try the suggestion by @clydin above.

If successful, please close this issue... Thanks!
