### ISSUE TITLE
Error: Validator.required!!!

### ISSUE THREAD

**Issue by masoudline** [angular/angular-cli#7897]
When I use below code (I filled title field):
`if(this.addAttributeLists.get('title').errors.required) {
      // do something
      }`
below code show in my browser console:

`ERROR TypeError: Cannot read property 'required' of null`

**Comment by sebinstean** [comment]
https://stackoverflow.com/questions/45431489/async-custom-validation-causes-an-error-to-the-console-cannot-read-property-r
