### ISSUE TITLE
ng serve --cacert option

### ISSUE THREAD

**Issue by matt328** [angular/angular-cli#7908]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.5.0-beta.2

### Desired functionality.

Our organization is migrating from webpack-dev-server and using SSL locally to mirror our prod environment as closely as possible.  We use --cert and --key, which seem to be supported by ng serve, but we also use --cacert to supply our intermediate CA.  It would be helpful if ng serve supported this as well, on the command line and via .angular-cli.json.

### Mention any other details that might be useful.

If ng serve is just using webpack-dev-server underneath, I might have time to put together a PR if that would be helpful.

**Comment by alan-agius4** [comment]
Hi, thanks for your requests. 

However we should be careful how we increase the scope of the CLI because each new feature means new code to maintain. And for this particular use case one can use an nginx on top of the dev server.

Let's re-open this is there is more interest in this feature.
