### ISSUE TITLE
npm error whilst running 'ng new' for v1.4.4 on Windows 7 

### ISSUE THREAD

**Issue by duffers20** [angular/angular-cli#7913]
### Bug Report
```
- [x] bug report
- [ ] feature request
```
### Versions.
@angular/cli: 1.4.4
node: 8.6.0
os: win32 x64 (Windows 7)
npm: 5.3.0

### Repro steps.
npm install -g @angular/cli@1.4.4
ng new my-app

### The log given by the failure.
  create my-app/e2e/app.e2e-spec.ts (288 bytes)
  create my-app/e2e/app.po.ts (208 bytes)
  create my-app/e2e/tsconfig.e2e.json (235 bytes)
  create my-app/karma.conf.js (923 bytes)
  create my-app/package.json (1311 bytes)
  create my-app/protractor.conf.js (722 bytes)
  create my-app/README.md (1021 bytes)
  create my-app/tsconfig.json (363 bytes)
  create my-app/tslint.json (2968 bytes)
  create my-app/.angular-cli.json (1241 bytes)
  create my-app/.gitignore (516 bytes)
  create my-app/src/assets/.gitkeep (0 bytes)
  create my-app/src/environments/environment.prod.ts (51 bytes)
  create my-app/src/environments/environment.ts (387 bytes)
  create my-app/src/favicon.ico (5430 bytes)
  create my-app/.editorconfig (245 bytes)
  create my-app/src/index.html (292 bytes)
  create my-app/src/styles.css (80 bytes)
  create my-app/src/main.ts (370 bytes)
  create my-app/src/polyfills.ts (2498 bytes)
  create my-app/src/test.ts (1085 bytes)
  create my-app/src/tsconfig.app.json (211 bytes)
  create my-app/src/typings.d.ts (104 bytes)
  create my-app/src/app/app.module.ts (314 bytes)
  create my-app/src/app/app.component.html (1120 bytes)
  create my-app/src/app/app.component.spec.ts (986 bytes)
  create my-app/src/app/app.component.ts (207 bytes)
  create my-app/src/app/app.component.css (0 bytes)
  create my-app/src/tsconfig.spec.json (304 bytes)
Installing packages for tooling via npm.
npm ERR! path C:\Users\username\Desktop\my-app\node_modules\cryptiles
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\username\Desktop\my-app\node_modules\cryptiles' -> 'C:\Users\username\Desktop\my-app\node_modules\.cryptiles.DELETE'
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\username\Desktop\my-app\node_modules\cryptiles' -> 'C:\Users\username\Desktop\my-app\node_modules\.cryptiles.DELETE'
npm ERR!   cause: 
npm ERR!    { Error: EPERM: operation not permitted, rename 'C:\Users\username\Desktop\my-app\node_modules\cryptiles' -> 'C:\Users\username\Desktop\my-app\node_modules\.cryptiles.DELETE'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path: 'C:\\Users\\username\\Desktop\\my-app\\node_modules\\cryptiles',
npm ERR!      dest: 'C:\\Users\\username\\Desktop\\my-app\\node_modules\\.cryptiles.DELETE' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, rename \'C:\\Users\\username\\Desktop\\my-app\\node_modules\\cryptiles\' -> \'C:\\Users\\username\\Desktop\\my-app\\node_modules\\.cryptiles.DELETE\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\username\\Desktop\\my-app\\node_modules\\cryptiles',
npm ERR!   dest: 'C:\\Users\\username\\Desktop\\my-app\\node_modules\\.cryptiles.DELETE',
npm ERR!   parent: 'my-app' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2017-10-03T09_52_13_205Z-debug.log

Package install failed, see above.

### Desired functionality.
Installs packages without error.

### Mention any other details that might be useful.
The command is run in a command prompt, started as the administrator (I have local administrator rights), Running the same command on my Mac, with the same version of the Angular CLI works perfectly.

**Comment by Brocco** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.

**Comment by sergiolealdev** [comment]
I am having exactly the same problem. @duffers20 did it finally worked for you?

**Comment by duffers20** [comment]
@sergiolealdev I think the issue was caused by the antivirus software installed on my Windows 7 work laptop. Have you tried temporarily disabling your AV software?

**Comment by sergiolealdev** [comment]
I'll try that, thanks @duffers20 !

**Comment by sergiolealdev** [comment]
Turns out my antivirus (McAfee) was blocking that very package (cryptiles) cause apparently there was a rule in the antivirus to stop any file that contains 'crypt' as name.

Just leaving this comment in case if it may help others in the future.

**Comment by duffers20** [comment]
I suspect the same thing was happening with Symantec Endpoint Protection too - thanks for looking into it further and posting an update 👍🏻
