### ISSUE TITLE
Failed at the start script 'ng serve' on windows 7 64

### ISSUE THREAD

**Issue by sanjayrathore144** [angular/angular-cli#7917]
i am using node v6.11.3 and npm v5.4.2 on windows 7 64 bit
when i create a new project using angular cli it finishes successfully but when trying to run it using ng serve it show me following error

Failed at the start script 'ng serve'

a complete log of error  is
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\sanjaylp\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.4.2
3 info using node@v6.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle testme@0.0.0~prestart: testme@0.0.0
6 info lifecycle testme@0.0.0~start: testme@0.0.0
7 verbose lifecycle testme@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle testme@0.0.0~start: PATH: C:\Users\sanjaylp\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\angproducts\testme\node_modules\.bin;C:\Program Files\Git\cmd;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\HPE\LoadRunner\strawberry-perl\perl\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\sanjaylp\AppData\Local\Android\sdk\platform-tools;C:\Program Files\Git\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\sanjaylp\AppData\Roaming\npm
9 verbose lifecycle testme@0.0.0~start: CWD: D:\angproducts\testme
10 silly lifecycle testme@0.0.0~start: Args: [ '/d /s /c', 'ng serve' ]
11 silly lifecycle testme@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle testme@0.0.0~start: Failed to exec start script
13 verbose stack Error: testme@0.0.0 start: `ng serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\sanjaylp\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\sanjaylp\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid testme@0.0.0
15 verbose cwd D:\angproducts\testme
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sanjaylp\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v6.11.3
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error testme@0.0.0 start: `ng serve`
22 error Exit status 1
23 error Failed at the testme@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

How can the CLI team reproduce the problem?
not sure as the same thing is working on another machine that is 32 bit window 7
what i did is 
install node 6.11.3
run npm install -g @angular/cli
after completion 
ng new xyz
ng serve 

supporting information:

npm -v prints: v3.10.10
node -v prints: v6.11.3
npm config get registry prints: https://registry.npmjs.org
Windows, OS X/macOS, or Linux?: windows
I don't use a proxy, but have limited or unreliable internet access.
Container:
I develop using Windows 7 64.

**Comment by Brocco** [comment]
Please verify that you are inside the newly created `xyz` diretory before running `ng serve`....

```
ng new xyz  // this creates a new project in the xyz directory
cd xyz  // this will change your directory to the newly created xyz directory
ng serve  // this will start a development server which will server your application at localhost:4200 (by default)
```

**Comment by jovanemarques** [comment]
I have de same problem.

ng new xyz
ng cd xyz
ng serve

error:
PS C:\Projetos\Medicom> ng new xyz
  create xyz/e2e/app.e2e-spec.ts (285 bytes)
  create xyz/e2e/app.po.ts (208 bytes)
  create xyz/e2e/tsconfig.e2e.json (235 bytes)
  create xyz/karma.conf.js (923 bytes)
  create xyz/package.json (1308 bytes)
  create xyz/protractor.conf.js (722 bytes)
  create xyz/README.md (1019 bytes)
  create xyz/tsconfig.json (363 bytes)
  create xyz/tslint.json (2968 bytes)
  create xyz/.angular-cli.json (1238 bytes)
  create xyz/.editorconfig (245 bytes)
  create xyz/.gitignore (516 bytes)
  create xyz/src/assets/.gitkeep (0 bytes)
  create xyz/src/environments/environment.prod.ts (51 bytes)
create xyz/src/environments/environment.ts (387 bytes)
  create xyz/src/favicon.ico (5430 bytes)
  create xyz/src/index.html (290 bytes)
  create xyz/src/main.ts (370 bytes)
  create xyz/src/polyfills.ts (2498 bytes)
  create xyz/src/styles.css (80 bytes)
  create xyz/src/test.ts (1085 bytes)
  create xyz/src/tsconfig.app.json (211 bytes)
  create xyz/src/tsconfig.spec.json (304 bytes)
  create xyz/src/typings.d.ts (104 bytes)
  create xyz/src/app/app.module.ts (314 bytes)
  create xyz/src/app/app.component.html (1120 bytes)
  create xyz/src/app/app.component.spec.ts (986 bytes)
  create xyz/src/app/app.component.ts (207 bytes)
  create xyz/src/app/app.component.css (0 bytes)
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Project 'xyz' successfully created.
PS C:\Projetos\Medicom> cd .\xyz\
PS C:\Projetos\Medicom\xyz> ng serve
The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.<anonymous> (C:\Programs\node-v6.11.3-win-x64\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\index.js:14:11)
at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Programs\node-v6.11.3-win-x64\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Programs\node-v6.11.3-win-x64\node_modules\@angular\cli\models\webpack-configs\styles.js:6:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by jovanemarques** [comment]
A interesting thing, I'm using Atom with a command plugin. If I try "ng new bla" in Atom command and try "ng serve" I have this error. But, if the same "ng new bla" at cmd and try "ng serve" (cmd or Atom) then its works.

**Comment by sanjayrathore144** [comment]
@Brocco yes i am in project directory at the time of running ng serve (Note: actually my project name was 'testme'  that you can check in log. i used 'xyz' just for an example. )

**Comment by sanjayrathore144** [comment]
Hello @Brocco  waiting for your answer. please advise

**Comment by Jrius4** [comment]
E:\mine>ng serve --open
Your global Angular CLI version (1.6.7) is greater than your local
version (1.6.6). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
module.js:540
    throw err;
    ^

Error: Cannot find module 'ansi-styles'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\mine\node_modules\chalk\index.js:3:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

E:\mine>

**Comment by Jrius4** [comment]
my version is


E:\Pj\mine>ng --version
Your global Angular CLI version (1.6.7) is greater than your local
version (1.6.6). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / ? \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.6
Node: 8.9.4
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.6
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
