### ISSUE TITLE
Folder structure for modules, components, directives, services, etc

### ISSUE THREAD

**Issue by let-aurn** [angular/angular-cli#7927]
The CLI should also suggest folder structure for modules, components, directives, services, etc...
Everything generated by AngularCLI is placed in `src/app` directory unless you specify the path.
It should be great to have a kind of standard for these paths too.

Here is an example of folder structure:
https://medium.com/@motcowley/angular-folder-structure-d1809be95542

    - app.module.ts
    - app.component.ts
    - modules
        - module1
            - components
            - pages
                module1.service.ts
                module1.module.ts
                module1.routes.ts
        - module2
            - components
            - pages
                module2.service.ts
                module2.module.ts
                module2.routes.ts
    - shared
        - components
        - mocks
        - models
        - ...

**Comment by clydin** [comment]
The base path for the generate command is the current working directory.  The intention is that the user would change into the directory of the module/component/etc. as they are working on that particular area of the application.

The CLI also strives to follow the official [Angular Style Guide](https://angular.io/guide/styleguide).

**Comment by Brocco** [comment]
I concur with @clydin the style guide he linked to is the suggested folder structure to follow. That being said the CLI is a tool that you control... and therefore you are in charge of the directory structure that makes the most sense for you and your application(s).

**Comment by let-aurn** [comment]
@clydin The thing is, Angular projects grow quickly, and there's nowhere we can find a standard folder structure.

The official [Angular Style Guide](https://angular.io/guide/styleguide) only talk about how to name files, but doesn't tell where these files should be placed.
See here: [angular.io/guide/styleguide#file-structure-conventions](http://angular.io/guide/styleguide#file-structure-conventions)

Angular CLI should **_suggest_** an implementation of this:
[angular.io/guide/styleguide#application-structure-and-ngmodules](http://angular.io/guide/styleguide#application-structure-and-ngmodules)
