### ISSUE TITLE
ng test --code-coverage does not create coverage folder 

### ISSUE THREAD

**Issue by liliom55** [angular/angular-cli#7932]
### Bug Report or Feature Request 
`ng test --code-coverage`   does not create coverage folder after updating package.json

### Versions.
```
@angular/cli: 1.4.4
node: 6.11.2
os: win32 x64
```

### Repro steps.

package.json
```
"devDependencies": {
    "@angular/cli": "^1.4.3",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "^1.4.1",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.3",
    "karma-jasmine": "^1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
```
Karma.config.js 
```
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    files: [
      { pattern: './src/test.ts', watched: false },
      {pattern: './src/assets/i18n/*.json', included: false}
      
    ],
    preprocessors: {
      './src/test.ts': ['@angular/cli']
    },
    mime: {
      'text/x-typescript': ['ts','tsx']
    },
    coverageIstanbulReporter: {
      reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: config.angularCli && config.angularCli.codeCoverage
              ? ['progress', 'coverage-istanbul']
              : ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```

**Comment by filipesilva** [comment]
@liliom55 can you specify what you changed from a base project? It sounds like you added options that don't work. A reproduction would be helpful.

**Comment by liliom55** [comment]
@filipesilva 
Thanks for your consideration. This is a big project which is completed. How can I reproduce it? Actually I haven't done very big changes.Just I had to update package.json because of some material issue. If you want I can sent you entire  project by email.

**Comment by filipesilva** [comment]
A big project isn't very helpful to reproduce issues. A better way would be to create a new project using `ng new`, then make the minimum amount of changes to reproduce the issue. Then you commit those changes and push the project to github, linking it here.

**Comment by liliom55** [comment]
@filipesilva 
Sorry, I didn't understand how to make  the minimum amount of changes. I've only updated package.json and materialModule. Also after updating I've got some strange failed test that I didn't get before updating.

**Comment by filipesilva** [comment]
First you make a new project using `ng new`, for instance `ng new reproduction-project`. Then in that project you check if code coverage works or not. We test for it for I feel confident that it will work on a brand new project.

Then you make changes to that project until you can see the problem you describe. In your case you say you've updated `package.json` and added Angular Material. So by adding it again maybe you can cause code coverage to break, thus reproducing the problem. 

When you manage to reproduce the problem then you can use that repository to show the problem to Angular CLI maintainers. Commit your changes and upload your local repository to github, then paste the link here. This is how you can make a simple reproduction.

**Comment by liliom55** [comment]
@filipesilva 
Thanks a lot Filipe. I'll informe you about the result after doing what you explained. Let's try it.

**Comment by liliom55** [comment]
@filipesilva 
I got it. When I create new project with material and all dependency, it works well. but when I add components(from old project) to new one the test breaks (```
Uncaught Response with status: 404 Not Found for URL: http://localhost:9876/assets/i18n/undefined.json
  at http://localhost:9876/_karma_webpack_/polyfills.bundle.js:7120
Chrome 61.0.3163 (Windows 10 0.0.0): Executed 54 of 67 ERROR (0 secs / 7.542 secs
```)) and can not create coverage folder.When I delete some part of it statement that I've implemented recently again it works well. So I think the problem is new version does not accept some part of my unit test but does it  make sense?

**Comment by filipesilva** [comment]
From your description it looks like your tests don't run successfully due to recent changes in your code base. You should try to fix the tests first and then see if the code coverage is ok. After that, if you still think there is a problem with Angular CLI, you should create a simple repro that shows the exact problem, without depending on parts of your bigger project.

**Comment by liliom55** [comment]
@filipesilva 
Thank you so much for your time. I'm tying to fix them.

**Comment by liliom55** [comment]
@filipesilva 
Strange ... I've solved it without touching any code. Only thing that I did was ctrl+S (3 times) after doing 
`ng test --code-coverage`.

**Comment by liliom55** [comment]
@filipesilva 
Could you please help me to get rid of this strange issue? 
Sometimes coverage is created sometimes no. For making more clear this issu, jasmine gives this result 
![image](https://user-images.githubusercontent.com/16512043/31511962-66a90f28-af57-11e7-839d-78cbc39417a6.png)

but Karma looks 
![image](https://user-images.githubusercontent.com/16512043/31512131-de1a8dac-af57-11e7-89db-10ef81edba93.png)

I found the issue might be cause of jasmine can not complete execution of tests. Do you have any idea?

**Comment by filipesilva** [comment]
From that log it seems like you have a 404 error, something in your polyfills tries to load an unexisting file. That might be the cause of your problem.

**Comment by liliom55** [comment]
@filipesilva 
So why the Karma on browser shows every thing is passed successfully ?
and why after couple time Ctrl+S is created?
Do you have any idea?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
