### ISSUE TITLE
ViewEncapsulation.None doesn't load css when needed

### ISSUE THREAD

**Issue by superMDguy** [angular/angular-cli#7934]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.1.3
node: 6.11.0
os: win32 x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
```

### Repro steps.

1. Add a css class to a component, and set `ViewEncapsulation.None`.
2. Create a second component, and use the class from the first component in its template
3. Add routes for each component
4. Navigate to the second component. The class from the first component won't be applied
5. Navigate to the first component, and then go back to the second component. Now, the class will be applied.

[Reproduction GIF](https://s1.postimg.org/4r82h89zbj/view-encapsulation-none-issue.gif)
Reproduction repo: https://github.com/superMDguy/angular-cli-encapsulation-issue

### Desired functionality.

For my use case, it'd be better if all styles from all components in the module were loaded onto the page right away, instead of being loaded once the component is loaded for the first time.

**Comment by Brocco** [comment]
I believe this is a misuse of style definitions.

If you want to define a style for multiple components, I would suggest you define them as a global style. Which is documented [here](https://github.com/angular/angular-cli/wiki/stories-global-styles).
