### ISSUE TITLE
Macros?

### ISSUE THREAD

**Issue by maxime1992** [angular/angular-cli#7944]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Desired functionality.
Would it be possible to have some kind of macros with angular-cli?

*(My problem is the following one and there might be a better way than macros that I'm not aware of)*

I do use DI to inject either real service (for prod) or mocked one (dev + tests):
```
{
  provide: SomeService,
  useClass: environment.mock ? SomeServiceMock : SomeServiceImpl,
},
```

The thing is, all of this code is analyzed at runtime and thus, **everything end up into the prod bundle: The real service and the mocked one.**

If we had the possibility to work on the code even BEFORE passing it to typescript compiler, it might be helpful. For example:

```
// IF environment.mock
{
  provide: SomeService,
  useClass: SomeServiceMock,
},
// ELSE
{
  provide: SomeService,
  useClass: SomeServiceImpl,
},
// FI
```

**Comment by Toxicable** [comment]
I believe what you are describing is actually called `lowering` which is something being worked on in core, this isn't the responsibility of the CLI

**Comment by hansl** [comment]
@Toxicable has the answer.

Closing this as this is not a CLI feature.
