### ISSUE TITLE
put a config setting into cli config for the base href for the deployment server 

### ISSUE THREAD

**Issue by halukkaramete** [angular/angular-cli#7946]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Desired functionality.

The cli offers an option to add the basehref during the build ng build --base-href /folder-name/ --prod
This sounds like an excellent cli config setting, cause you do not want to do this every single time. 
https://stackoverflow.com/questions/46568731/configuring-the-index-html-basehref-at-ng-build-time

**Comment by hansl** [comment]
Hi @halukkaramete,

It is already. See https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/lib/config/schema.json#L87
