### ISSUE TITLE
showCircularDependencies: false still shows Circular dependency warnings

### ISSUE THREAD

**Issue by m4mbart** [angular/angular-cli#7952]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.4
node: 6.10.3
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.4.4
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3
typescript: 2.3.4

### Repro steps.
After upgrading from angular-cli 1.2 to 1.4.4 'ng serve' started to show circular dependency warnings. I then added '"showCircularDependencies": false' to angular-cli.json, but they still show up. I might have added this option to the wrong path in the JSON object however, but I'm unable to find any documentation on this.

**Comment by BBaysinger** [comment]
I'm having this issue. What was the solution? You closed it.

**Comment by m4mbart** [comment]
Yeah, I didn't read the manual on the wiki very well... turns out I should have used the settings some place else in angular-cli.json:

`"defaults": {
    "styleExt": "scss",
    "prefixInterfaces": false,
    "build": {
      "showCircularDependencies": false
    }`

It's supposed to be in defaults.build

Hope this helps.
