### ISSUE TITLE
Angular cli doesn't build polyfills properly

### ISSUE THREAD

**Issue by lordscales91** [angular/angular-cli#7953]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.5
node: 6.11.1
os: win32 x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.3.4
@angular/language-service: 4.3.4

## Current behavior
with ng serve the app works properly on IE11 (after adjusting polyfills of course), but with ng build it doesn't work, the generated bundle files break on IE.

## Expected behavior
ng build should generate bundle files compatible with IE, maybe with a configuration option or a flag.

### Repro steps.

* Start a new project with ng new
* Adjust the polyfills.ts to support IE
* Build the project with ng build
* Copy the generated files from dist to an HTTP Server (Is that the way to deploy an Angular 2 app, right? I used Apache as HTTP Server)

**Comment by lordscales91** [comment]
The issue seems to be specific to the laptop I use in the office. Sorry to bother with this

**Comment by osa10928** [comment]
Hey, I know this is closed but I'm running into the same problem and am wondering if its specific to my work computer too. How did you figure out it was specifically your work laptop?

**Comment by lordscales91** [comment]
@osa10928 I asked a co-worker to test it on his laptop. If I remember correctly, the issue had to do with a specific build of Windows 10, in later builds it was fixed. Also, you could check out the Document mode configured on IE. You can check it by right-clicking on any web page and then going to Inspect Element > Emulation. I hope it helps
