### ISSUE TITLE
Class / ID minifier

### ISSUE THREAD

**Issue by Laurensvdmaas** [angular/angular-cli#7955]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
@angular/cli: 1.3.2
node: 7.4.0
os: darwin x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.3.2
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3

### Desired functionality.
**What would like to see implemented?**
Class / ID minifier,
I can imagine it will interfere when styling is encapsulated, but not encapsulated this should be possible?

**What is the usecase?**
Whenever your run a production build.

### Mention any other details that might be useful.
https://github.com/marcog83/css-rename
https://github.com/yiminghe/class-id-minifier

**Comment by hansl** [comment]
Hi @Laurensvdmaas,

Thanks for the suggestion.

Minifying/optimizing is always something we look at, but this particular feature could be dangerous, actually. It will break third party libraries unless everyone is on board, or we can minify them too (or we can be sure there's no clash). This is not something we can do reliably.

We might come up with solutions in the future for this kind of improvements, but in the meantime there is much more we can do to improve tree-shaking, which would result in better gains and less effort.

I'm going to close this.
