### ISSUE TITLE
bug: Zones not loaded with bundleDependencies all [v5, beta.4]

### ISSUE THREAD

**Issue by Toxicable** [angular/angular-cli#7962]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Versions.
```
@angular/cli: 1.5.0-beta.4
node: 6.11.1
os: darwin x64
@angular/animations: 5.0.0-rc.1
typescript: 2.5.3
```

### Repro steps.
repo: https://github.com/Toxicable/angular-bundleDependencies-issue
or from scratch:
follow: https://github.com/angular/angular-cli/wiki/stories-universal-rendering
upgrade to 5.0.0-rc.1 and 1.5.--beta.4
use `--bundleDependencies all`

### The log given by the failure.
>/Users/fabianwiles/Documents/angular-bundleDependencies-issue/dist-server/main.bundle.js:86191
        this._zone.onMicrotaskEmpty.subscribe({ next: function () { _this._zone.run(function () { _this.tick(); }); } });
                                   ^
TypeError: Cannot read property 'subscribe' of undefined

The log would indicate Zones not being loaded yet at the top of the `prerender.ts` file it is there: `
import 'zone.js/dist/zone-node';`
I also tried importing zones into main.server.ts so that it's included in the bundle but this had to affect on the error

Edit: Looks like this is only an issue when using the bundle from an eternal script

**Comment by vtulin** [comment]
Any updates or workaround?
