### ISSUE TITLE
Ng not working in gitbash but working fine in node command prompt

### ISSUE THREAD

**Issue by dhisharma** [angular/angular-cli#7992]
I have installed angular/cli globally, and when i am writing 'ng -v' in node command prompt prompt its working but same command at the same directory when i use git bash its throwing error 'ng is not a command'.i have also uninstalled and again installed all the dependencies and cleared cache also, this problem seems to come time to time .this is my Environment variable:- 

%SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\Program Files  (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS  Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem; C:\Windows\System32\WindowsPowerShell\v1.0\; C:\Program Files (x86)\Intel\Intel(R) Management Engine   Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine  Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine   Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine   Components\IPT;C:\Program Files\nodejs\;C:\Program Files   (x86)\Skype\Phone\;C:\Program Files\MongoDB\Server\3.4\bin;C:\Program Files   (x86)\Git\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files\Microsoft VS   Code\bin;c:\Users\Me\AppData\Roaming\npm\; C:\Program   Files\nodejs\node_modules\npm\bin;C:\Program Files\nodejs
-- | --

**Comment by danwulff** [comment]
@dhisharma I've had this problem once or twice on Windows (npm bins not firing in certain cmd prompts / git bashes).

What's always seemed to work for me is uninstalling and reinstalling node/npm via: https://nodejs.org/en/download/ (make sure to grab the LTS v6).

It might be something worth trying. ¯\\\_(ツ)_/¯

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
