### ISSUE TITLE
Error when using 'ng build -prod -aot'

### ISSUE THREAD

**Issue by prakashs-mtsin** [angular/angular-cli#7993]
Unexpected value 'NgModule in D:/GIT/Branches/Angular4/trunk/Web/node_modules/@angular/core/core.d.ts' imported by the module 'MyModule in D:/GIT/Branches/Angular4/trunk/Web/src/app/dashboard/dashboard.module.ts'. Please add a @NgModule annotation.

I have moved the source from Angular 2 to Angular 4. 

Kindly help to resolve this issue

![builderror](https://user-images.githubusercontent.com/16669548/31390366-52399970-adf1-11e7-8ba8-bd247143e025.JPG)

**Comment by hansl** [comment]
We are lacking a lot of information here, notably your version of CLI and Angular (and TypeScript). Also, please provide a reproduction.

Closing this, please file a new issue and fill out the issue template.
