### ISSUE TITLE
The @angular/compiler-cli package was not properly installed.

### ISSUE THREAD

**Issue by Polaris-BS** [angular/angular-cli#7997]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Output from: `ng --version` :
```
@angular/cli: 1.4.5
node: 8.6.0
os: win32 x64
@angular/animations: 4.4.4
@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.4.5
@angular/common: 4.4.4
@angular/compiler-cli: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
typescript: 2.5.3
```

### Package.json
```
{
	"name": "MyApps",
	"version": "0.0.0",
	"license": "MIT",
	"scripts": {
		"ng": "ng",
		"start": "ng serve",
		"build": "ng build",
		"test": "ng test",
		"lint": "ng lint",
		"e2e": "ng e2e",
		"build-prod": "node --max_old_space_size=5048 ./node_modules/@angular/cli/bin/ng build --prod"
	},
	"private": true,
	"dependencies": {
		"@agm/core": "^1.0.0-beta.0",
		"@angular/animations": "^4.3.3",
		"@angular/cdk": "^2.0.0-beta.12",
		"@angular/cli": "^1.4.5",
		"@angular/common": "^4.3.3",
		"@angular/compiler-cli": "^4.4.4",
		"@angular/core": "^4.3.3",
		"@angular/forms": "^4.3.3",
		"@angular/http": "^4.3.3",
		"@angular/material": "^2.0.0-beta.12",
		"@angular/platform-browser": "^4.3.3",
		"@angular/platform-browser-dynamic": "^4.3.3",
		"@angular/router": "^4.3.3",
		"bootstrap": "4.0.0-beta",
		"core-js": "^2.4.1",
		"css-loader": "^0.28.4",
		"intl": "^1.2.5",
		"jquery": "^3.2.1",
		"json-server": "^0.12.0",
		"material-design-iconic-font": "^2.2.0",
		"mdi": "^2.0.46",
		"multi-brand-colors": "^1.1.3",
		"ng2-webstorage": "^1.8.0",
		"ngu-utility": "^1.0.3",
		"ngx-bootstrap": "^1.8.1",
		"ngx-malihu-scrollbar": "^1.1.2",
		"node-sass": "^4.5.3",
		"popper.js": "^1.12.5",
		"rxjs": "^5.4.2",
		"save": "^2.3.1",
		"ts-helper": "0.0.1",
		"web-animations-js": "^2.3.1",
		"zone.js": "^0.8.16"
	},
	"devDependencies": {
		"@types/chartist": "^0.9.37",
		"@types/jasmine": "2.6.0",
		"@types/jquery": "^3.2.13",
		"@types/jquery-mousewheel": "^3.1.7",
		"@types/mcustomscrollbar": "^2.8.32",
		"@types/node": "^8.0.34",
		"codelyzer": "~3.2.1",
		"css-to-string-loader": "^0.1.3",
		"jasmine-core": "~2.8.0",
		"jasmine-spec-reporter": "~4.2.1",
		"karma": "~1.7.0",
		"karma-chrome-launcher": "~2.2.0",
		"karma-cli": "~1.0.1",
		"karma-coverage-istanbul-reporter": "^1.3.0",
		"karma-jasmine": "~1.1.0",
		"karma-jasmine-html-reporter": "^0.2.2",
		"loaders.css": "^0.1.2",
		"protractor": "~5.1.2",
		"ts-node": "~3.3.0",
		"tslint": "~5.7.0",
		"typescript": "^2.5.3"
	}
}

```

### Repro Steps : 
I use :  ng serve

**Message :** 

The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler' 

I read all the topic to this subject but I don't find a valide solution ... Can you help me ?

**Comment by danwulff** [comment]
Hi @Polaris-BS.
I don't see `@angular/cli` listed in your dev dependencies. Did you create this app using the angular cli? (using `ng new`?). Also, many of the angular libraries do not currently support `"typescript": "^2.5.3"`.
Try downgrading to: `"typescript": "~2.3.3"`.

It seems to me that you have a lot of dependencies that are not set to the expected defaults that the angular-cli gives you when running `ng new`.

If you're migrating an app that previously did not use the cli you should take a look at this wiki article: https://github.com/angular/angular-cli/wiki/stories-moving-into-the-cli

Otherwise it might be easiest to make sure you have the latest cli installed, create a new app, and then port your existing code into the newly created app. For example, in a terminal:
* `npm install @angular/cli@latest -g`
* `ng new your_app_name_here`

And then port your existing app code to the newly created app found in the your_app_name_here directory.

Good luck.

**Comment by hansl** [comment]
@danwulff it seems to be in his `dependencies`, not his `devDependencies`, which is perfectly fine.

@Polaris-BS Could you try nuking your node_modules (`rm -rf node_modules`) and reinstalling it? There also seems to be different versions of `@angular/compiler-cli` than the rest, which suggests you already try to fix this issue on your own. Could you try to upgrade the Angular packages ("@angular/animations", "@angular/common", "@angular/compiler-cli", "@angular/core", "@angular/forms", "@angular/http", "@angular/platform-browser", "@angular/platform-browser-dynamic", and "@angular/router"),  to be the same version?

In case all of this does not work, if this is an open source project, could you provide the repository so we can look at it locally? If not, try following @danwulff's advice and create a new project and compare dependencies.

**Comment by redietGirma** [comment]
am having the same problem here. i have all the updated versions but still fails to install the angular-compiler/cli

**Comment by mkoczka** [comment]
@Polaris-BS @redietGirma Is it still a problem with the latest version of angular & angular/cli?

**Comment by Polaris-BS** [comment]
hey @mkoczka no it's good with the last version
