### ISSUE TITLE
Angular2App should allow you to import assets

### ISSUE THREAD

**Issue by rodyhaddad** [angular/angular-cli#8]
Similar to [EmberApp's import method](https://github.com/ember-cli/ember-cli/blob/6d8a209f9e6440b8c30f79a7ea5f6cc04e545b5b/lib/broccoli/ember-app.js#L1206), our [Angular2App](https://github.com/angular/angular-cli/blob/master/lib/broccoli/angular2-app.js) should have an import method, allowing you to include assets that will end up in the concatenated dist files.

In practice this will often be used by addons in their `included` hooks. (#7)

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/135 seems to have addressed this. If not, please reopen this issue.
