### ISSUE TITLE
IONIC, install peer dependencies yourself. ionic-native wants ionic-native/core

### ISSUE THREAD

**Issue by akaday** [angular/angular-cli#8000]
Hi Everyone
I have some problem when I do ionic cordova prepare to install all of my plugin
The Error like this : 

`npm ERR! peerinvalid Peer @ionic-native/action-sheet@4.3.1 wants @ionic-native/core@^4.2.0`

in the first time, the login like this

`npm WARN @ionic-native/action-sheet@4.3.1 requires a peer of @ionic-native/core@^4.2.0 but none is installed. You must install peer dependencies yourself.`

### Versions.
cli packages: (C:\Users\User\Dropbox\Dropbox\ionium2\node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node : v6.11.2
    npm  : 5.4.2
    OS   : Windows 8.1

Can Somebody help me..
Tyvm

**Comment by hansl** [comment]
Hi @akaday,

You probably want to move this issue to the ionic repo; https://github.com/ionic-team/ionic

Closing this as there's nothing we can do.
