### ISSUE TITLE
Error when using 'ng build -prod -aot'

### ISSUE THREAD

**Issue by prakashs-mtsin** [angular/angular-cli#8002]
### Versions.
"@angular/cli": "1.4.4"
"@angular/core": "^4.2.4"
"@angular/compiler": "^4.2.4"
"typescript": "~2.3.3"

### Issue when using.
I just build using ng build -prod -aot

### The log given by the failure.
Unexpected value 'NgModule in D:/GIT/Branches/Angular4/trunk/Web/node_modules/@angular/core/core.d.ts' imported by the module 'MyModule in D:/GIT/Branches/Angular4/trunk/Web/src/app/dashboard/dashboard.module.ts'. Please add a @NgModule annotation.

When using ng serve and ng build it works properly, attached screen shot of my issue

![builderror](https://user-images.githubusercontent.com/16669548/31424856-38a55c7c-ae7a-11e7-92b4-d29375bfd4d8.JPG)

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
