### ISSUE TITLE
Module not found: Error: Can't resolve './locale' in '[app path]\node_modules\moment\src\lib\locale'

### ISSUE THREAD

**Issue by danwellman** [angular/angular-cli#8003]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

ng - 1.3.0
node - 6.11.0
npm - 3.10.10
Windows 10

### Repro steps.

Unable to repro locally, only in CI environment (see details below)

### The log given by the failure.

Module not found: Error: Can't resolve './locale' in '[app path]\node_modules\moment\src\lib\locale'

### Mention any other details that might be useful.

We just started to get this error in our CI environment last night, unable to repro locally even with `--prod` or `--aot` options when building. Seems to be related to this issue: https://github.com/moment/moment/issues/2979 although trying the suggested fix there has not helped

**Comment by ssanderlin** [comment]
@danwellman Did you fix this? I'm having the same issue.

**Comment by v1as** [comment]
I was helped by the version change to previous by command
npm i moment@2.18.1 --save
And don't forget to restart application if "ng serve"

**Comment by danwellman** [comment]
@ssanderlin, sorry for the delay, yes, we fixed this in the end. Rolling back to moment@2.18.0 was the fix after all

**Comment by dankonino** [comment]
Thanks guys. this fixed my problem as well. quick catch !
