### ISSUE TITLE
Multi-component option for Angular CLI

### ISSUE THREAD

**Issue by pavilion** [angular/angular-cli#8008]
- [x] feature request

### Desired functionality.
It would be nice to have a multi-component option to add in the Angular CLI.
Nowadays we just 
`ng g c "componentName". `
It would be interesting to have an multi-component option as 
`ng g c "(cA, cB, cC)`.
Now, you may ask, why?
I have several examples.
It would help to create new components based on whatever the user has input.
Let's say that I have a website that creates components based on the user's behaviour. It would be a way of implementing IA into Angular. As Netflix does, it provides highly accurate predictive technology based on customer's reactions to films. It analyzes billions of records to suggest films that you might like based on your previous reactions and choices of films. 
Why can't that be applied to just frontend? Create new kind of components based on user behaviours.
Or, if I have a waterfall project oriented team, where we already know what components are we going to use, and let's say, there is more than a 100 of them... Would that not be a reason to add this simple and easy to maintain functionality? 
Thanks.
-->

**Comment by textbook** [comment]
Why not just use existing command line functionality? For example:
```
for COMP in cA cB cC; do ng g c $COMP; done
```

**Comment by hansl** [comment]
Hi @pavilion,

I could see how that would be useful in your usecase, but as @textbook pointed out, you can do the same with a for loop. This is a problem better solved outside the CLI itself, and we will not implement it.
