### ISSUE TITLE
Feature Request: Production Build into Separate Directory

### ISSUE THREAD

**Issue by rkralston** [angular/angular-cli#801]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.2-mobile.3
node: 6.1.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
n/a

4. The log given by the failure. Normally this include a stack trace and some
   more information.
n/a

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.
Currently, dev and prod both are built to /dist. I am developing and pushing drafts to a site for teams (multiple geographical locations) to evaluate. 

Is it possible to have the dev and prod builds go to separate directories (/dev and /prod)?

**Comment by JonCubed** [comment]
I dont think this is currently possible

**Comment by Brocco** [comment]
@rkralston Can you please provide a possible use case for this functionality? It will become quite a bit more complicated when other environments are added beyond the current dev & prod.

**Comment by rkralston** [comment]
The Use Case is in support of UAT: constant builds to a UAT server pushed by git.

I have an online UAT server to which I push stable builds for testing and approval. I am pushing to that server using git to allow for the full functionality of updates and rollbacks.

Currently, I have a prod directory at the same level as dist. My prod directory is ignored. The directory has its own git configuration. I build a prod build and manually copy dist to that prod directory. This gives me full git functionality to incrementally push stable builds to UAT.

It would be nice if ng build -prod could target that build directory saving me a few steps and allowing me to automate pushing stable builds to UAT.

**Comment by filipesilva** [comment]
Related https://github.com/angular/angular-cli/issues/682

**Comment by filipesilva** [comment]
Workaround in https://github.com/angular/angular-cli/issues/804

**Comment by filipesilva** [comment]
Closed in favor of https://github.com/angular/angular-cli/issues/817
