### ISSUE TITLE
Consider using Cypress for E2E testing

### ISSUE THREAD

**Issue by maxime1992** [angular/angular-cli#8013]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Desired functionality.
[Cypress](https://github.com/cypress-io/cypress) is a brand new E2E testing tool that allows devs to do so much more than protractor (CF this [video](https://vimeo.com/237115455)).

It is now out of private beta and I'm aware that it might be a bit early to think of an integration with the CLI. But, I'm sure that opening this issue is not a bad idea so we can discuss pro/const and maybe see an integration in few (weeks :heart:?) months :smile:.

**Comment by hansl** [comment]
Hi @maxime1992,

Thanks for the suggestion. This is interesting. However, supporting an e2e framework is hard enough already for us, adding support for another one (or switching altogether) is a lot of efforts. We won't have the bandwidth to do it anytime soon, if ever.

This is something that might be mitigated by having extensibility in the CLI, which is planned further down the line. At which point, you could implement a plugin that changes our current e2e to use whatever you want.

**Comment by dopry** [comment]
+1 for Cypress support. Selenium is a pain, even with protractor to help. I think we all understand rewriting a test suite is time consuming. I think a discussion of the merits is well warranted.

**Comment by shcallaway** [comment]
I am also in favor of adding Cypress support. It's a _much_ better UI testing experience than Selenium and Protractor.

**Comment by dopry** [comment]
Although, this may be better address upstream in the angular core community. If traction develops there it will flow into the downstream tools.

**Comment by mackelito** [comment]
Perhaps this could be supported thru schematics? (by the cypress team)
