### ISSUE TITLE
Uncaught TypeError: s.JitCompilerFactory is not a constructor

### ISSUE THREAD

**Issue by dsuwirya** [angular/angular-cli#8015]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.5.0-beta.4
node: 6.10.3
os: win32 x64
@angular/animations: 5.0.0-rc.1
@angular/common: 5.0.0-rc.1
@angular/compiler: 5.0.0-rc.1
@angular/core: 5.0.0-rc.1
@angular/forms: 5.0.0-rc.1
@angular/http: 5.0.0-rc.1
@angular/platform-browser: 5.0.0-rc.1
@angular/platform-browser-dynamic: 5.0.0-rc.1
@angular/router: 5.0.0-rc.1
@angular/cli: 1.5.0-beta.4
@angular/compiler-cli: 5.0.0-rc.1
@angular/language-service: 5.0.0-rc.1
typescript: 2.5.3

### Repro steps.

1. ng build --prod
2. build successfully ( no error at all )
3. serve the generated bundle from node.js
4. application failed to load, and the error trace below displayed in the browser console.

note. ng build (without --prod) build and load fine.

### The log given by the failure.

From browser console:

vendor.1ed5b021bd13a10b4eea.bundle.js:1 Uncaught TypeError: s.JitCompilerFactory is not a constructor
    at r (vendor.1ed5b021bd13a10b4eea.bundle.js:1)
    at Je (vendor.1ed5b021bd13a10b4eea.bundle.js:1)
    at Ye (vendor.1ed5b021bd13a10b4eea.bundle.js:1)
    at Qe (vendor.1ed5b021bd13a10b4eea.bundle.js:1)
    at new t (vendor.1ed5b021bd13a10b4eea.bundle.js:1)
    at Object._n [as createNgModuleRef] (vendor.1ed5b021bd13a10b4eea.bundle.js:1)
    at e.create (vendor.1ed5b021bd13a10b4eea.bundle.js:1)
    at vendor.1ed5b021bd13a10b4eea.bundle.js:1
    at t.invoke (polyfills.63ab2a039111021d7498.bundle.js:1)
    at Object.onInvoke (vendor.1ed5b021bd13a10b4eea.bundle.js:1)

### Desired functionality.

Should build and load fine in --prod mode as well.

**Comment by filipesilva** [comment]
Heya, I don't quite follow your step 3. There are many ways to serve content using node. Can you be specific please, and maybe provide a minimal reproduction? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by dsuwirya** [comment]
For step 3, I simply copy the generated dist files into the /public file of the node.js, and serve it from there.

**Comment by filipesilva** [comment]
Hmm I need actual code to investigate that. Can you provide the minimal repro I requested in my last comment please?

**Comment by dsuwirya** [comment]
Closing this issue as I finally found out that this error is actually caused by "angular2-busy" component that I'm using. Thanks!

**Comment by ravikumarbggit** [comment]
@dsuwirya , I'm getting same error. Could you please elaborate on what did you do with ng-busy to fix this issue?

**Comment by dsuwirya** [comment]
@ravikumarbggit, I replaced it with ngx-loading. :)
