### ISSUE TITLE
can't use 'ng g *' or 'ng  generate *'  

### ISSUE THREAD

**Issue by xiaoxiaodek** [angular/angular-cli#8017]
**os** :**ubuntu 14.**
**angular version:**
$ ng version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.6
node: 8.5.0
os: linux x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.6
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4

use **'`ng new aaa`'** to new  an angular project 
then  run **'`ng g component dfffd`'**  under directory

**here are the error imformations:**
_Error: ELOOP: too many symbolic links encountered, stat '/home/upsmart/task/2017.10/aaa/node_modules/@angular/cli/node_modules/webpack/node_modules/escope/node_modules/es6-map/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d'_

I had tried  these messures:
1:reinstall the cli (this didn't work for me )
```
npm uninstall -g  @angular/cli 
npm cache verify
ng  -v 
npm install -g @angular/cli@latest
```
2:remove the node_modules  directory under  aaa , then run '`npm install` '
It made the ' `ng  g *`'  work. 

SO I WONDER IS THIS A PROBLEM ABOUT VERSION ?HOW TO FIX IT ?

**Comment by zhangshichuan** [comment]
你好, 问题解决了吗? 我也是这个问题,

**Comment by duffy990** [comment]
哈哈，我刚刚也出现了，不知道怎么解决

**Comment by zhangshichuan** [comment]
解决了: 把node_modules删掉, 然后不要用cnpm安装初始包, 用npm就可以解决.

**Comment by hansl** [comment]
As @zhangshichuan said, this seems to be a problem with `cnpm` which does not install node_modules properly. I'm not sure how the CLI could fix it. You can disable the usage of `cnpm` yourself when creating new applications, using your global configuration.

If you think of something we can do for the CLI, please let us know.

Closing this issue as this is not something we can fix ourselves.
