### ISSUE TITLE
ng g component XXX . Error: ELOOP: too many symbolic links encountered

### ISSUE THREAD

**Issue by zhangshichuan** [angular/angular-cli#8018]
OS: win7 64
After I created a project through ng new command, I successfully started with ng serve, and then I wanted to create a new component. When I used ng g component navbar, I prompted the error: 

          Error: ELOOP: too many symbolic links encountered, stat 'C:\Users\Jack\WebstormProjects\snake\node_modules\@angular\cli\node_modules\webpack\node_modules\escope\node_modules\es6-map\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d'

**Comment by duffy990** [comment]
请问解决了吗

**Comment by Justin-wei** [comment]
Is anyone working on it?

**Comment by dingziyang** [comment]
Me too. How to deal with it？

**Comment by zhangshichuan** [comment]
Remove the package downloaded from CNPM and then use NPM to fix it.

**Comment by v8xm** [comment]
It works for me .
But why it happened ?

**Comment by GerryGe** [comment]
ng set --global packageManager=npm
