### ISSUE TITLE
remove angular decorators when using AngularCompilerPlugin.

### ISSUE THREAD

**Issue by aitboudad** [angular/angular-cli#8027]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

master

### Desired functionality.

[_removeDecorators](https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/loader.ts#L618) only applied when using `AotPlugin` but not when using `AngularCompilerPlugin`.

**Comment by hansl** [comment]
Yes, this has been removed in favor of build-optimizer, which Filipe is still working on.

We are also looking at using tsickle in the CLI, which would be the actual fix.

**Comment by filipesilva** [comment]
Closing in favor of https://github.com/angular/angular-cli/issues/8050 just because it has a more verbose description.
