### ISSUE TITLE
Feature request: allow CORS on local dev server

### ISSUE THREAD

**Issue by wholladay** [angular/angular-cli#803]
1. OS?  Mac OSX (El Capitan?)
2. Versions. 
   angular-cli: 1.0.0-beta.1
   node: 5.10.0
   os: darwin x64
3. Repro steps. I'm running a Spring-Boot server as my RESTful API and to serve up the initial html page. The html page then gets the angular app from a CDN. The Angular cli server acts like the CDN while we are developing. Both Spring and Angular cli are running on my local machine (with different ports). When the call to System.import() is made, I get a CORS error from the browser.
4. The log given by the failure. 
   XMLHttpRequest cannot load http://localhost:4200/system-config.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
   zone.js:323 Error: Error: XHR error loading http://localhost:4200/system-config.js(…)
5. Mention any other details that might be useful.
   I'm sure there must be a way to do this, but I've tried everything I can think of.

**Comment by cotomas** [comment]
+1 vote for enabling to set custom Access-Control-Allow-Origin parameter for ng serve

**Comment by machi1990** [comment]
+1 vote for this. We had to rely on express server + https://github.com/nodejitsu/node-http-proxy to make cross-origin HTTP requests.

**Comment by machi1990** [comment]
To be able to make CORS http request I had to use the "--proxy" i.e `ng server --proxy http://localhost:8080`.

**Comment by wholladay** [comment]
I actually solved this issue by using the [ember-cli-cors](https://www.npmjs.com/package/ember-cli-cors) add on. All you have to do is install it using the ng command like so:
ng install ember-cli-cors

**Comment by cotomas** [comment]
ng install ember-cli-cors
didnt help. What am I missing?

**Comment by Brocco** [comment]
@wholladay I presume that you meant:

`npm install ember-cli-cors`

and **not**

`ng install ember-cli-cors`?

**Comment by wholladay** [comment]
@brocco No, I first tried `npm install ember-cli-cors` and that did not work. When I ran `ng install ember-cli-cors` it did the trick for me.

**Comment by jmb-mage** [comment]
+1

@wholladay did you configure anything after `ng install ember-cli-cors` ? 

Or change the `ng serve` command at all?

In my scenario I am trying to port an Angular 1 app where in Dev we had to run `"C:\..\chrome.exe" --disable-web-security` to access a SharePoint oData source.  We also have to login to SharePoint first to get authenticated.  Eventually the app is deployed to SharePoint and all that is no longer an issue.

It would be great to have a way to `ng serve` it that doesn't modify the deployables in any way.

**Comment by maxailloud** [comment]
I tried `ng install ember-cli-cors`and nothing changed for me.
Is there an additional step to do to make it work?

**Comment by wholladay** [comment]
@jmb-mage I did not configure anything differently that I can remember, not did I change the ng serve command. It just kind of... well, started working and I moved on to other issues.

**Comment by jmb-mage** [comment]
@wholladay as a workaround I ran the [npm http-server](https://www.npmjs.com/package/http-server) onto the 'public' or `dist` folder directly.  

It has these attributes:

`http-server -o --cors`

**Comment by filipesilva** [comment]
Superseded by https://github.com/angular/angular-cli/issues/2872, as this was for a pre-webpack version of the CLI.
