### ISSUE TITLE
Can't use scss files normally

### ISSUE THREAD

**Issue by Darkoon** [angular/angular-cli#8034]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.7
node: 6.10.0
os: win32 x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/material: 2.0.0-beta.8
@angular/cdk: 2.0.0-beta.8
@angular/cli: 1.4.7
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3
typescript: 2.3.4

### Repro steps.
I'm struggling to use sass in fresh angular project. I created project with `--style=scss` flag from CLI and then updated `.angular-cli.json` file content with `"styleExt": "scss"` and `"styles": ["styles.scss"]`. Project building was successfull but styles from files like `xyz.component.scss` were not compiled and thus not included in styles bundle.

I managed to add components style files to `.angular-cli.json` file `"styles": ["styles.scss", "./path/to/file/xyz.component.scss"]` but this resulted in runtime error: `Error: Uncaught (in promise): Expected 'styles' to be an array of strings`. 

To avoid this error I deleted `styleUrls: ['./xyz.component.scss']` from `@Component` annotations in `xyz.component.ts` files.

Now everything works good but I don't understand whats going on with those scss files. Why I must delete reference to them from `@Component`? (they are referenced automaticly when using `ng g component` cli command). Are there any other options to make it work without referencing `.scss` files in `.angular-cli.json` and use `@Component` reference instead?

**Comment by clydin** [comment]
Global styles and component styles are two very different things.  Global styles are bundled and linked directly from the application's `index.html`.  Component styles are part of the component itself.  See the [relevant angular documentation](https://angular.io/guide/component-styles) for more information. (The CLI supports `styleUrls` as CSS, SASS/SCSS, LESS, or stylus files).

**Comment by Darkoon** [comment]
Thanks for reply! Is there any way to use `.scss` styles as component styles? For project described in question, (ng) component generator creates file `xyz.component.scss` as well as `styleUrls: ['./xyz.component.scss']` in annotation `@Component` but scss file styles aren't working. Also in case of global styles: Is it possible to automaticly merge `.scss` files from given paths to one global file?

**Comment by clydin** [comment]
For global styles, the `styles` property in `.angular-cli.json` bundles all referenced files.
For component styles, the generate command is creating everything you need to get started.  `styleUrls: ['./xyz.component.scss']` means the component will use the SCSS file as a source for styles.  The CLI also allows multiple stylesheet file formats to be mixed in both an application and an individual component (e.g., both a CSS and SCSS file in `.angular-cli.json`; or even SCSS, CSS, and stylus files in a single `styleUrls` array).

Could you elaborate on what you mean by not working?  Component styles are scoped (advanced configuration withstanding) to the component.  In fact, the styles are only present within the page when the component itself is present.

Also of note is that auto-prefixing and, in production builds, minification is handled automatically for **all** referenced stylesheet files.

**Comment by Darkoon** [comment]
In my case component styles are not working. Styles defined in `xyz.component.scss` are omitted thus not making any changes in view representation of component. In chrome tools styles defined in `xyz.component.scss` are missing. So it's not working for me "out of the box" when creating components. Is there anything I can do to make it work?

**Comment by dalu** [comment]
Ever since 1.4 `-style=scss` doesn't work anymore. It's 1.4.7 and it's stil not fixed.
Likewise `--routing` was made away with.

Why remove working and useful functionality? And at the same time introduce something new that isn't documented AT ALL

**Comment by clydin** [comment]
@Darkoon Can you provide an example of what you are attempting?  I put together a quick SCSS example application using version 1.4.7.  You can find it [here](https://github.com/clydin/scss-example).  Run `ng serve --open` and it will show `example works!` in blue.
Steps used to create it were:
1) `ng new scss-example --style=scss`
2) `cd scss-example/src/app`
3) `ng generate component example`
4) edit `example/example.component.scss` to contain `p { color: blue; }`
5) replace the content of `app.component.html` with `<app-example></app-example>`

**Comment by clydin** [comment]
@dalu both of those features exists and work in version 1.4.7 and i'm unsure of what you are referring to in your last statement.  But if you are running into problems, ensure the latest version of `@schematics/angular` is installed (may need to delete the project's package lock file) and please open a separate issue with the template details if the problems persist.

**Comment by dalu** [comment]
@clydin , I'm referring to this:
```
# ng new --help
ng new <options...>
  Creates a new directory and a new Angular app eg. "ng new [name]".
  aliases: n
  --dry-run (Boolean) (Default: false) Run through without making any changes. Will list all files that would have been created when running "ng new".
    aliases: -d, --dryRun
  --verbose (Boolean) (Default: false) Adds more details to output logging.
    aliases: -v, --verbose
  --skip-install (Boolean) (Default: false) Skip installing packages.
    aliases: -si, --skipInstall
  --skip-commit (Boolean) (Default: false) Skip committing the first commit to git.
    aliases: -sc, --skipCommit
  --collection (String) Schematics collection to use.
    aliases: -c <value>, --collection <value>
```
and this
```
wrk ~ # npm update -g @schematics/angular
wrk ~ # npm uninstall -g @schemantics/angular
up to date in 0.036s
wrk ~ # npm install -g @schemantics/angular
npm ERR! code E404
npm ERR! 404 Not Found: @schemantics/angular@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-14T20_29_53_009Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@schemantics/angular' ]
2 info using npm@5.5.1
3 info using node@v8.7.0
4 verbose npm-session 27f83eef5074d71a
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@schemantics%2fangular 820ms
8 silly fetchPackageMetaData error for @schemantics/angular@latest 404 Not Found: @schemantics/angular@latest
9 verbose stack Error: 404 Not Found: @schemantics/angular@latest
9 verbose stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:785:20)
9 verbose stack     at tryOnImmediate (timers.js:747:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:718:5)
10 verbose cwd /root
11 verbose Linux 4.13.5-1-ARCH
12 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@schemantics/angular"
13 verbose node v8.7.0
14 verbose npm  v5.5.1
15 error code E404
16 error 404 Not Found: @schemantics/angular@latest
17 verbose exit [ 1, true ]
```

**Comment by filipesilva** [comment]
@Darkoon it should just work as shown in the repro that @clydin setup. Can you provide a reproduction where it does not work?

@dalu the issue you are describing is open as https://github.com/angular/angular-cli/issues/7723.

**Comment by Darkoon** [comment]
@clydin, @filipesilva Thanks for help. I finally resolved this issue by uninstalling angular-cli and reinstalling it again in `1.4.7` version. Sorry for problem!

**Comment by hemant-cybage** [comment]
I am facing the same issue, importing scss file into component using stylesUlls doesnt work, while importing them into styles.scss at the root works, but in dont want to do that, its dirty.

Info : 
```
Angular CLI: 7.1.4
Node: 10.14.2
OS: win32 x64
Angular: 7.1.4
```

**Comment by lim-enhui** [comment]
same issue here. i tried reinstalling approach but got the same result scss is not affecting change in the other components that is nested under app/
