### ISSUE TITLE
error with use "ng g c  xxx"

### ISSUE THREAD

**Issue by lxhjh** [angular/angular-cli#8037]
### The log given by the failure.

Error: ELOOP: too many symbolic links encountered, stat 'E:\learn\angular\foo\node_modules\@angular\cli\node_modules\web
pack\node_modules\escope\node_modules\es6-map\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules
\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_mod
ules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node
_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\
node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-itera
tor\node_modules\d'

**Comment by RicardoVaranda** [comment]
Hi @lxhjh , 

Thanks for reporting your issue, could you please try the following command and report back it's results : `ng -v` also it would be beneficial if you provided a repo so we can try and replicate the issue.
