### ISSUE TITLE
why is still angular configured with version 4.2.4?

### ISSUE THREAD

**Issue by offwork** [angular/angular-cli#8039]
kerem-MacBook-Air:~ kerem$ node -v
v8.7.0
kerem-MacBook-Air:~ kerem$ npm -v
5.5.1
kerem-MacBook-Air:~ kerem$ ng -v
@angular/cli: 1.4.7
node: 8.7.0
os: darwin x64
kerem-MacBook-Air:~ kerem$

=============================================================================

"dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.7",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }

=============================================================================

Why can't I create a project with the latest version? @angular packages constantly `**warning** has incorrect peer dependency`

**Comment by clydin** [comment]
A new project will use the latest version within 4.x (the use of the `^` tells the package manager to install the latest minor version).

**Comment by offwork** [comment]
ok, however I am creating the project with `ng new proj` command

**Comment by grizzm0** [comment]
@offwork 

Tilde, ~, will match the most recent minor version while caret, ^, will match the most recent major version.

^4.2.4 will match >=4.2.4,<5.0.0.
~4.2.4 will match >=4.2.4,<4.3.0.

^4.2.4 which you've got in your freshly created AngularCLI project means that you'll always get the latest version of angular4 but will miss angular5.

**Comment by ocombe** [comment]
Because Angular v5 has not been released yet, it's still a RC.

**Comment by filipesilva** [comment]
Closing as there are already a few answers addressing the question.
