### ISSUE TITLE
I don't see how to build to a folder other than `dist`.

### ISSUE THREAD

**Issue by RyanParsley** [angular/angular-cli#804]
Editing the "outDir" in the generated tsconf.json looks to have no effect on where the output of `ng build` is placed. Is there a way to build to a different folder so the cli can be used with existing projects?

1. El Capitan
2. angular-cli: 1.0.0-beta.1, node: 4.4.0
3. Building with `ng build`
4. Results: 'Built project successfully. Stored in "dist/".'
5. Note that the result from 4 is not as successful as it reports. I need to build to a directory other than "dist".

**Comment by RyanParsley** [comment]
Digging deeper, I see that I can pass `--output-path`. Is there a way to change the default of this option per project?

**Comment by JonCubed** [comment]
its currently not officially supported see #817, however you can create a *.ember-cli* file in your root like so

```
{
    "output-path": "wwwroot/"
}
```

this method will work for `ng build` and `ng serve`

**Comment by filipesilva** [comment]
Closed in favor of https://github.com/angular/angular-cli/issues/817.
