### ISSUE TITLE
angular universal,TypeError: Cannot read property 'unsubscribe' of undefined

### ISSUE THREAD

**Issue by BlankHrt** [angular/angular-cli#8041]
```javascript
  storeSubscribe: Subscription;
...
this.storeSubscribe = this.store.select('user').subscribe(data => {
      this.user = data;
    });
...
this.storeSubscribe.unsubscribe();

it's ok with dev environment.
but follow https://github.com/angular/angular-cli/wiki/stories-universal-rendering
error information
Unhandled Promise rejection: Cannot read property 'unsubscribe' of undefined ; Zone: <root> ; Task: Promise.then ; Value: { TypeError: Cannot read property 'unsubscribe' of undefined
```

**Comment by filipesilva** [comment]
Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by J2D2Development** [comment]
I don't have any insight to the cause, but on our project we've made a habit of checking if the subscription exists before unsubscribing.  Just a simple 'if' statement usually does the trick:

`if(this.storeSubscribe) { this.storeSubscribe.unsubscribe(); }`

If the subscription is undefined, there's nothing to unsubscribe from, so it seems like "no harm no foul".

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However this doesn't seem to be an issue with `Angular-CLI`
