### ISSUE TITLE
Angular 4, Unexpected token: name (Subject) during ng build --prod

### ISSUE THREAD

**Issue by oguzkurtcuoglu** [angular/angular-cli#8044]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```
I have a Angular 4 application.

I can successfully build the project with ng build

But, when I run ng build --prod error is thrown.

When I did some research, I saw uglifyjs not working with es6 and I changed target to es5 in my tsconfig file.

But I keep getting this error.

I don't understand what is wrong.

### Versions.

![7eili 1](https://user-images.githubusercontent.com/17877435/31545796-7a10d5c8-b029-11e7-97e0-721d8e4c0655.png)

### Repro steps.

1. Run this command: `ng build --prod`

### The log given by the failure.

ERROR in vendor.4008cf7dff2b98412878.bundle.js from UglifyJs Unexpected token: name (Subject) [vendor.4008cf7dff2b98412878.bundle.js:19471,6]

### Desired functionality.

The build should finish without an error

**Comment by hiepxanh** [comment]
first 
> ng build --prod --sm
to detect the error
second 
check the 3th libs causing problem

**Comment by oguzkurtcuoglu** [comment]
@hiepxanh  thank you for answer.
I used this @aspnet/signalr-client package. I unistalled package from my application and problem is solved.

**Comment by hiepxanh** [comment]
it a good news,sir.
Please close your issue if your problem is solved sir.
Have a good day :)

**Comment by oguzkurtcuoglu** [comment]
Thank you again :) 
Now, I will close issue. My problem is solved.
