### ISSUE TITLE
Missing support babel-loader

### ISSUE THREAD

**Issue by cuongqle** [angular/angular-cli#8045]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [x] feature request
```

### Repro steps.
ES6 code with spread operator
For example:
case REQUEST_GUIDE_FULFILLED:
|     return {
|       ...filterGuideData(action.guide),
|       isLoaded: true,
|     }

Exception thrown:
Module parse failed: C:\workspace\showhowAdmin\platform\node_modules\source-map-loader\index.js!C:\workspace\showhowAdmin\platform\showhow-admin\app\player\redux\reducers\domain\guide.js Unexpected token (10:6)
You may need an appropriate loader to handle this file type.

### Desired functionality.

Module parse failed: C:\workspace\showhowAdmin\platform\node_modules\source-map-loader\index.js!C:\workspace\showhowAdmin\platform\showhow-admin\app\player\redux\reducers\domain\guide.js Unexpected token (10:6)
You may need an appropriate loader to handle this file type.
|   case REQUEST_GUIDE_FULFILLED:
|     return {
|       ...filterGuideData(action.guide),
|       isLoaded: true,
|     }

### Mention any other details that might be useful.

In @angular/cli/modles/webpack-configs/common.ts, if i have a small modify by adding babel-loader rule into 'module' section:
{ test: /\.(js|ts)$/, loader: "babel-loader", exclude: [nodeModules] }
then it work fine.

**Comment by filipesilva** [comment]
We do not support transpiling javascript ES2015 code down to ES5 code by design. If you want to use babel to add custom ES2015 code, you will have to eject.

We have support for ES2015 targets without transpiling code down to ES5 in https://github.com/angular/angular-cli/pull/7610. The resulting bundle will be contain ES2015 code.
