### ISSUE TITLE
Confusing error message when there is @angular/compiler version mismatch

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#8049]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Versions.

I have yarn installed and set to be used by `ng` by default + 

```
Angular CLI: 1.5.0-rc.0
Node: 6.9.5
OS: darwin x64
Angular: 5.0.0-rc.2
... animations, common, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.5.0-rc.0
@angular/compiler: 4.4.5
@angular-devkit/build-optimizer: 0.0.27
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.33
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.0
@schematics/angular: 0.0.45
typescript: 2.4.2
webpack: 3.7.1
```

### Repro steps.
```
ng new test-project
cd test-project
yarn upgrade @angular/{animations,cli,common,compiler-cli,core,forms,http,language-service,platform-browser-dynamic,platform-browser,router}@next
```

### The log given by the failure.
```
Versions of @angular/compiler-cli and typescript could not be determined.
The most common reason for this is a broken npm install.

Please make sure your package.json contains both @angular/compiler-cli and typescript in
devDependencies, then delete node_modules and package-lock.json (if you have one) and
run npm install again.
```

### Desired functionality.
- as a yarn user, it is confusing to see `npm` specific instructions
- the error message doesn't mention `@angular/compiler` which is the actual culprit here - I forgot to add it to the list of packages to be updated
- my problem was not that the install was incorrect, the problem was a version mismatch:

```
...
    "@angular/common": "^5.0.0-rc.2",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^5.0.0-rc.2",
...
```
The issue would have been much easier to fix if this was pointed out to me in the error.

**Comment by slim-souissi** [comment]
I have the same error . how can i determine the versions that i should be using and fix them 
?

**Comment by filipesilva** [comment]
We have since reworked these error messages. I believe this issue is now obsolete.
