### ISSUE TITLE
feat(mobile): add separate config flags to toggle build

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular-cli#805]
This suggestion was brought up by @kara.

During development, compiling the App Shell can be a burden: It takes a while to bundle files into a single concatenated script, the compilation often fails because of a missing provider or other non-prerender-friendly code. However, compiling during development also has advantages, like making sure the transition from shell to real app is seamless, making sure compilation works, etc.

So it would be nice to be able to easily disable app shell compilation during dev build.

Right now, the only option in angular-cli.json for mobile projects is a single `mobile: true` setting. This could be expanded to be an object with more granular configuration, one of which could modify what mobile pieces are built during dev and prod:

angular-cli.json

```
mobile: {
  dev: {
    buildAppShell: true,
    buildServiceWorker: false,
    buildAppManifest: true
  },
  prod: {
    buildAppShell: true,
    buildServiceWorker: false,
    buildAppManifest: true
  }
}
```

The downside to this design is that the build becomes more complicated. For example, right now, Service Worker assumes that App Shell is being built, and therefore only caches the bundled JS plus static non-JS assets. With more configuration, the Service Worker would have to figure out which JS tree it should be caching.

**Comment by filipesilva** [comment]
@jeffbcross is this still an issue on the webpack branch?

**Comment by jeffbcross** [comment]
@filipesilva this would still be a nice feature to have.

**Comment by Charlkie14** [comment]
I can't wait for this feature especially after the Angular Universal integration as well. Creating progressive web app will be so easy and integrated nicely. So excited!!

**Comment by filipesilva** [comment]
Closing as it this isn't being acted on anymore. See https://github.com/angular/angular-cli/issues/2228 for context.

**Comment by Charlkie14** [comment]
Haha. I caused this issue to close. Sort of by saying something. But I understand @filipesilva. Only so much time :) Thanks for the reply. You guys are doing awesome work!!

**Comment by filipesilva** [comment]
Kinda, yeah :D. When you commented I got an email that prompted me to review it.

Glad you're enjoying the CLI!
