### ISSUE TITLE
ng generate tslint quotemark error " should be '

### ISSUE THREAD

**Issue by jiayisheji** [angular/angular-cli#8055]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.7
node: 8.4.0
os: win32 x64

### Mention any other details that might be useful.

ng generated file inside the introduction of the dependent module is double quotation marks,
tslint will suggest an error, ` " should be '(quotemark)`
Can you change the double quotation marks into single quotation marks?
Or every time I generate a document need to modify, good trouble Oh
Thank you

**Comment by alan-agius4** [comment]
This seems that it has been addressed already. 

If the problem persists please indicate the exact command that you are running.

Thanks

**Comment by mnlfischer** [comment]
@alan-agius4 can you reference to the addressed issue?
Today the ng lint detects `/src/app/services/auth/auth.guard.ts:1:28 - " should be ', `
generated with 
`ng generate guard /services/auth/auth`.
Only on this guard the ng lint detects the double quotes.
