### ISSUE TITLE
Public-facing roadmap

### ISSUE THREAD

**Issue by bmayen** [angular/angular-cli#8056]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

It's a testament to the amazing work being done here that so much of the community now relies on the CLI for their production projects. This put CLI firmly in the critical path for a lot of teams. One thing that would really help our team (and I'm sure others) is a public-facing roadmap to help us understand what is coming down the pipeline. We're often faced with decisions of whether or not we should implement something we need ourselves or wait for the CLI team to tackle it. 

Additionally, we'd like to help contribute. Webworkers support, for instance. But according to the main issue tracking this particular feature, there is other work that needs to be done before that can be added. It's not clear where that other work is prioritized so it makes it difficult/impossible for us to plan time for this around our client work schedule.

A lot of this information can be deduced by reading through many comments across many tickets, but production teams don't always have that kind of time on their hands. It would be hugely helpful to have a high-level view of what is tentatively planned a few releases out. Something like https://github.com/Microsoft/TypeScript/wiki/Roadmap possibly?

**Comment by elvirdolic** [comment]
This would be awesome.

**Comment by LayZeeDK** [comment]
There's the [Tracking](https://github.com/angular/angular-cli/projects/2) project, but it seems abandoned.

**Comment by kuncevic** [comment]
https://github.com/angular/angular/milestones

**Comment by mgechev** [comment]
Hey @bmayen, that's a very fair point. We're working on improving the way we communicate our roadmap publicly, not only for the CLI but also for framework and components.

I'd close this issue for now since it's not the right place for tackling the progress. You can check for updates on https://blog.angular.io.
