### ISSUE TITLE
How to include bootstrap-daterangepicker

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#806]
I've been using the cli for a while, but I'm still struggling when trying to add 3rd party libraries.
I want to add this npm package: https://www.npmjs.com/package/bootstrap-daterangepicker

I cannot just include the js script tags in index.html, as this package depends on moment, and that's loaded via system.js. So, I must just that.

What I've done:

installed the package
added 'bootstrap-daterangepicker/daterangepicker.*' to vendorNpmFiles
added 'bootstrap-daterangepicker': 'vendor/bootstrap-daterangepicker/daterangepicker.js' to const map in system-config.ts
But what's next? The script file is not loaded. And, when I do import * as daterangepicker from 'bootstrap-daterangepicker'; I get a compile time error...

I just want to load the JS file with system.js.

**Comment by rolandoldengarm** [comment]
I've added this to the root component and that seems to work:

import 'bootstrap-daterangepicker';

Is that the way to go? Sorry, new with this.

**Comment by hboylan** [comment]
Documented my struggle integrating `angular-material` with #723

**Comment by hijoncon** [comment]
You have to have moment js in your `system-config.js` and add this `'moment': 'vendor/moment/moment.js',`

**Comment by rolandoldengarm** [comment]
Yeah I already have it working, but it's not properly documented in angular-cli (or I haven't found it yet). The wiki page about 3rd party is way too restricted.

**Comment by nfantone** [comment]
I fear we took a wrong turn somewhere along the path. This used to be _the most trivial_ thing to do in a Javascript app.

@rolandoldengarm What did you do to make it work?

**Comment by rolandoldengarm** [comment]
@nfantone 
- Added package to angular-cli-build.js
- Updated system-config.ts to:

````
const map: any = {
  'bootstrap-daterangepicker': 'vendor/bootstrap-daterangepicker',
};

/** User packages configuration. */
const packages: any = {
  'bootstrap-daterangepicker': {main: 'daterangepicker.js', defaultExtension: 'js'},
};
````
- Added import 'bootstrap-daterangepicker'; to my root component

**Comment by filipesilva** [comment]
There are a couple of other issues that deal with how the 3rd party lib journey could be better, and this issue seems to be solved already so I'm closing it.
