### ISSUE TITLE
Want karma code coverage html without writing --code-coverage

### ISSUE THREAD

**Issue by afsar-infobeans** [angular/angular-cli#8063]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by afsar-infobeans** [comment]
The description is here for my issue:

https://stackoverflow.com/q/46767029/3313526

**Comment by filipesilva** [comment]
When you use `npm run` to run npm script, you need to use `--` before passing arguments. So you need to run `npm run ng -- test --code-coverage`.

See https://docs.npmjs.com/misc/scripts for more information.

**Comment by afsar-infobeans** [comment]
Thanks @filipesilva
