### ISSUE TITLE
HMR has conflict with --proxy-config

### ISSUE THREAD

**Issue by Dok11** [angular/angular-cli#8069]
### Bug Report or Feature Request.
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.4.7
node: 6.9.1
os: win32 x64
@angular/animations: 4.4.5
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/core: 4.4.5
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/router: 4.4.5
@angular/cli: 1.4.7
@angular/compiler-cli: 4.4.5
@angular/language-service: 4.4.5
```

### Repro steps.

package.json:
```json
{
  "scripts": {
    "hmr": "ng serve --proxy-config proxy.conf.json --hmr -e=hmr",
  }
}
```

proxy.conf.json with them HMR work correctly:
![image](https://user-images.githubusercontent.com/2697890/31619582-a115a178-b29d-11e7-9cd3-a6fd395441cf.png)

```json
{
	"/api/*": {
		"target": "http://my.site.dev.ru",
		"secure": false,
		"changeOrigin": true
	}
}
```

And proxy.conf.json with them HMR doesn't run (clean console log) and dont update page:
![image](https://user-images.githubusercontent.com/2697890/31619627-c8119da4-b29d-11e7-948f-8030943f8cc0.png)
```json
{
	"/api/*": {
		"target": "http://my.site.dev.ru",
		"secure": false,
		"changeOrigin": true
	},
	"/f/*": {
		"target": "http://my.site.dev.ru",
		"secure": false,
		"changeOrigin": true
	}
}
```

As I can see if rules in proxy.conf.json more than one then HMR will crash.

Maybe this important: with `"@angular/cli": "1.2.4"` all works.

**Comment by Dok11** [comment]
Sorry, I think this bug active if I use `router.resetConfig`, on pages without this method all good works

**Comment by filipesilva** [comment]
Heya, is this still a problem? If so can you provide a reproduction repository that we can clone and see the problem happening please?

**Comment by alan-agius4** [comment]
Closing as no further information was provided by the author of the issue.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
