### ISSUE TITLE
Ng Component w/ Custom Element: "cannot be invoked without new" in Karma

### ISSUE THREAD

**Issue by priley86** [angular/angular-cli#8071]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.0
node: 6.2.2
os: darwin x64
@angular/animations: 5.0.0-rc.2
@angular/common: 5.0.0-rc.2
@angular/compiler: 5.0.0-rc.2
@angular/core: 5.0.0-rc.2
@angular/forms: 5.0.0-rc.2
@angular/http: 5.0.0-rc.2
@angular/platform-browser: 5.0.0-rc.2
@angular/platform-browser-dynamic: 5.0.0-rc.2
@angular/router: 5.0.0-rc.2
@angular/cli: 1.3.0
@angular/compiler-cli: 5.0.0-rc.2
@angular/language-service: 5.0.0-rc.2

### Repro steps.

git clone https://github.com/priley86/storybook-angular-demo.git
git fetch origin testing
npm run test

### The log given by the failure.

Karma seems to be failing to load the Web Component polyfills correctly (referenced in `polyfills.ts` here: https://github.com/priley86/storybook-angular-demo/blob/master/src/polyfills.ts#L52).

When initializing a component that references a custom element, Karma fails to invoke the Custom Element constructor. This appears to be an issue with Karma not loading the polyfill correctly.

Integration testing of web components in the Angular CLI project will be a very important theme in the future. It'd be great to document how to do this!

Karma failure logs:
```
16 10 2017 15:30:59.489:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
16 10 2017 15:30:59.490:INFO [launcher]: Launching browser Chrome with unlimited concurrency
16 10 2017 15:30:59.502:INFO [launcher]: Starting browser Chrome
16 10 2017 15:31:14.456:WARN [karma]: No captured browser, open http://localhost:9876/
16 10 2017 15:31:14.633:INFO [Chrome 61.0.3163 (Mac OS X 10.12.6)]: Connected on socket FGpSES_F21AxxvReAAAA with id 74040345
Chrome 61.0.3163 (Mac OS X 10.12.6): Executed 3 of 5 SUCCESS (0 secs / 0.352 secs)
Chrome 61.0.3163 (Mac OS X 10.12.6) ERROR
  Uncaught TypeError: Class constructor HelloComponent cannot be invoked without 'new'
Chrome 61.0.3163 (Mac OS X 10.12.6) ERROR
  Uncaught TypeError: Class constructor HelloComponent cannot be invoked without 'new'
  at http://localhost:9876/_karma_webpack_/polyfills.bundle.js:1
Chrome 61.0.3163 (Mac OS X 10.12.6): Executed 3 of 5 ERROR (0 secs / 0.352 secs)
Chrome 61.0.3163 (Mac OS X 10.12.6) ERROR
  Uncaught TypeError: Class constructor HelloComponent cannot be invoked without 'new'
Chrome 61.0.3163 (Mac OS X 10.12.6): Executed 3 of 5 ERROR (0.474 secs / 0.352 secs)
```

Relevant commit which adds the web component/storybook demo to Angular CLI project:
https://github.com/priley86/storybook-angular-demo/commits/testing

### Desired functionality.

Passing integration tests with Ng and a Custom Element

**Comment by intellix** [comment]
getting this also. Even with `1.6.0-rc.0` which I thought had a fix for it :)

I'm getting it much less now actually, but it seems to be when extending:

```ts
import { Inject, Pipe, PipeTransform, LOCALE_ID } from '@angular/core';
import { DatePipe } from '@angular/common';

// Safari can't parse the dates returned by legacy REST API.
// This should be deleted once we replace all REST call with GraphQL
@Pipe({
  name: 'date',
})
export class DateTransformPipe extends DatePipe implements PipeTransform {
  constructor(@Inject(LOCALE_ID) currentLocale: string) {
    super(currentLocale);
  }

  toISO(value: string) {
    return value.toString().replace(/\s+/g, 'T').replace('.000000', '.000Z');
  }

  transform(value: any, args?: any): any {
    return super.transform(!value ? value : this.toISO(value), args);
  }
}
```

Using it like:

```ts
beforeEach(async(() => {
  TestBed.configureTestingModule({
    schemas: [NO_ERRORS_SCHEMA],
    declarations: [
      SomethingComponent,
      DateTransformPipe,
    ],
    ...
```

**Comment by hansl** [comment]
I'm going to close this as it's a very old issue, and we changed a lot during Angular 6.x regarding running karma and running tests (in both the CLI and Angular Core).

If you can still see this happening, please file a new issue with a recent reproduction. Thanks!
