### ISSUE TITLE
Angular CLI 1.3+ issues with local file system dependencies

### ISSUE THREAD

**Issue by remmeier** [angular/angular-cli#8076]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Windows 10
@angular/cli: 1.4.3
node: 8.7.0
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.2.7
@angular/compiler: 4.4.3
@angular/compiler-cli: 4.4.3

### Repro steps.

- setup an angular library project
- setup an angular frontend project with angular cli
- make use of library in frontend trough file system dependency, like: "@x/y": "file:../x/dist"
- run "ng serve" in frontend application

### The log given by the failure.

when running ng serve, I get upon start:

```
Uncaught Error: Unexpected value 'ArbAppModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
```

Note that file:../x/dist does NOT have a node_modules directory! So there is/should not be an issue with multiple NgModule implementations from the shared and frontend project due to the two module directories. That issue has been discussed here quite a number of times already (and is an annoying issue on its own). So the tsconfig file does not need path mappings. Altough with or without does not make a difference here.  The frontend project here only makes use of the build output (no node_modules dir) of the shared project.

### Desired functionality.

it should work

### Mention any other details that might be useful

everything has been working fine in Angular CLI 1.0.x, 1.1.x and 1.2.x. In 1.3.x and 1.4.x this seems to be broken.

**Comment by clydin** [comment]
Node's module discovery algorithm walks up the directory structure to find a `node_modules` location.  In this case it will walk up `../x/dist` which most likely has the library's development dependencies in `../x/node_modules`.  The last paragraph (and example code) in the [linked library story](https://github.com/angular/angular-cli/wiki/stories-linked-library) would also apply here as well.  Please note that the instructions in that last paragraph are for the application itself not the library.

**Comment by clydin** [comment]
Closing as 1.4.x is no longer actively supported and 6.0+ contains first class support for library generation and packaging.
