### ISSUE TITLE
.angular-cli.json  default component viewEncapsulation

### ISSUE THREAD

**Issue by steavengong** [angular/angular-cli#8082]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Versions.

@angular/cli: 1.4.7
node: 7.9.0
os: darwin x64

### Repro steps.

in .angular-cli.json

"defaults": {
    "styleExt": "scss",
    "component": {
      "spec": false,
      "viewEncapsulation": "None"
    }
  }

use cli  ng  g component my-component

it don't add 'encapsulation: ViewEncapsulation.None'  in my-component.component.ts

@Component({
  selector: 'my-component',
  templateUrl: './my-component.component.html',
  styleUrls: ['./my-component.component.scss']
})

**Comment by steavengong** [comment]
emmm.....
Are you sure change ??

Angular CLI: 1.5.0
Node: 7.9.0
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

in my new component ,it also not to add encapsulation with cli "ng g component my-component --view-encapsulation none" or "ng g component my-component -ve none" 

or set .angular-cli.json with
"defaults": {
    "component": {
      "viewEncapsulation":"None"
    }
  }

**Comment by steavengong** [comment]
@Brocco

**Comment by Splaktar** [comment]
@steavengong the fix isn't part of a release yet and isn't in `1.5.0` of the CLI.
