### ISSUE TITLE
add support for generating favicons

### ISSUE THREAD

**Issue by mackelito** [angular/angular-cli#8083]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

Add the possibility to run https://github.com/evilebottnawi/favicons (or similar) thru the cli

**Comment by filipesilva** [comment]
This isn't something we feel should be core Angular CLI functionality. It's really up to the user if they want to use such a tool or not.

**Comment by mackelito** [comment]
Fair enough.. just thought it would be a handy feature :)
Keep up the good work!
