### ISSUE TITLE
Generating components adds a new line in the wrong place

### ISSUE THREAD

**Issue by maxxt** [angular/angular-cli#8084]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

1.4.7

### Repro steps.

ng generate component my-test-component

app-modules.ts before generating the new component
```import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from 'app/app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

app-module.ts after generating the new component
```import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from 'app/app.componen;
import { MyTestComponentComponent } from './my-test-component/my-test-component.component't';

@NgModule({
  declarations: [
    AppCompone,
    MyTestComponentComponentnt
  ],
  imports: [
    BrowserModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Notice the import and component name
What is causing this issue? I don't know exactly when this started to happen, but i can't trace it.

**Comment by stephanie-dm** [comment]
This problem still exists with Angular-CLI 1.5.0:

After adding a new component "location":
` ng g c location`

I get this in the declarations of my AppModule:

    declarations: [
        AppComponen,
        LocationComponentt
     ],

The import looks ok though:
`import { LocationComponent } from './location/location.component';`
