### ISSUE TITLE
Compilation using build-optimizer missing scripts.*.js log entry

### ISSUE THREAD

**Issue by FeaRCODE** [angular/angular-cli#8098]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
Windows 10

@angular/cli: 1.4.7
node: 8.6.0
os: win32 x64
@angular/animations: 4.4.5
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/core: 4.4.5
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/router: 4.4.5
@angular/cli: 1.4.7
@angular/compiler-cli: 4.4.5
@angular/language-service: 4.4.5
typescript: 2.3.4
```

### Repro steps.

`ng build --prod --build-optimizer`

### The log given by the failure.

```
Date: 2017-10-18T22:45:18.924Z
Hash: 67dc238fe33e0d78c4d4
Time: 18355ms
chunk {0} polyfills.7645e2591139aaacb570.bundle.js (polyfills) 100 kB {3} [initial] [rendered]
chunk {1} main.fb16da570920713f190b.bundle.js (main) 318 kB {3} [initial] [rendered]
chunk {2} styles.ab31c2b9a051bac66589.bundle.css (styles) 138 kB {3} [initial] [rendered]
chunk {3} inline.2b7fb79714501cd910a2.bundle.js (inline) 1.45 kB [entry] [rendered]
```

Also, take note of the index.html and how it's being required.
```
<script type="text/javascript" src="inline.2b7fb79714501cd910a2.bundle.js"></script>
<script type="text/javascript" src="polyfills.7645e2591139aaacb570.bundle.js"></script>
<script type="text/javascript" src="scripts.bda500c1491f48e71561.bundle.js"></script>
<script type="text/javascript" src="main.fb16da570920713f190b.bundle.js"></script>
```

### Desired functionality.

The output should include `script.*.js` and its compiled size etc.

### Mention any other details that might be useful.

I might be missing something on how build-optimizer works, and if that's the case, would like a little more information on what it does documented.

**Comment by filipesilva** [comment]
You can find more information about Build Optimizer in the devkit repository: https://github.com/angular/devkit/tree/master/packages/angular_devkit/build_optimizer.

But I don't think it is related to what you're seeing. This was an unintended side effect of https://github.com/angular/angular-cli/pull/7279 and should happen in all builds. 

Technically speaking, scripts are no longer a webpack chunk but rather an asset processed separately. This means it doesn't show up on that build output, whereas it did before (but still is present in the build artifacts in `dist/`). Sort of how css assets like images or fonts also don't appear in that output.

**Comment by FeaRCODE** [comment]
Ok thanks! Then I’ll close this issue.
