### ISSUE TITLE
feat(mobile): support templateUrl and styleUrls with App Shell prerender

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular-cli#810]
Right now, apps built with the `--mobile` flag require that any directives included in the pre-rendered App Shell only use inline templates and styles. This is due to a combination of broccoli trees, module.id, and universal not looking in the right place to get templates. Because of Broccoli's symlinking (I think), when the App Shell plugin is compiling the root component, the `module.id` is resolving to a path within the typescript plugin's tree, which only contains JS files (not the component's html and css files). 

A solution should be implemented to make it simple to use `templateUrl` and `styleUrls` with App Shell components.

**Comment by drejohnson** [comment]
It seems` styleUrls` works with lazy routes for `--mobile` apps. It would be super useful to able to use `templateUrl` and `styleUrls`.

**Comment by david1983** [comment]
+1

**Comment by KenCorbettJr** [comment]
+1

**Comment by cbomkamp** [comment]
+1

**Comment by FrancoAra** [comment]
+1

**Comment by PascalPrecht** [comment]
Please stop +1'ing this issue and use GitHub's reaction feature instead (Click the smiley in the top right corner of a comment to add a reaction)

Thanks!

**Comment by mishudark** [comment]
+1

**Comment by refrigerator** [comment]
Hey, is anyone working on this? Would be super useful!

**Comment by rlbarreto** [comment]
I am getting this error with the template app generated on 
`ng new appName --mobile`
When I do `ng serve` I get the same error. Don't have any templateUrl or styleUrl yet.

**Comment by filipesilva** [comment]
Superseded by https://github.com/angular/angular-cli/issues/1371
