### ISSUE TITLE
Missing error info in `ng serve` since rc1

### ISSUE THREAD

**Issue by SanderElias** [angular/angular-cli#8101]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Angular CLI: 1.5.0-rc.1
Node: 8.7.0
OS: linux x64
Angular: 5.0.0-rc.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0-rc.1
@angular-devkit/build-optimizer: 0.0.28
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.1
@schematics/angular: 0.0.46
typescript: 2.5.3
```

### Repro steps.
clone [this repo](https://github.com/SanderElias/BusinessLogicBlogSample/tree/4d53633fe11a54b49cab9ebe2959adab279215cd)
`ng serve`

### The log given by the failure.
This is the output of the `ng serve`
![image](https://user-images.githubusercontent.com/1249083/31752894-b23ac540-b48d-11e7-9321-7c0551853425.png)
As you can see, the error log in there is not so helpful

### Desired functionality.
proper error logging

**Comment by filipesilva** [comment]
I have a fix incoming in https://github.com/angular/angular-cli/pull/8109. Meanwhile, downgrading Angular to `5.0.0-rc.2` should fix it.
