### ISSUE TITLE
Ng build i18n file imports

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular-cli#8103]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.4.4
node: 8.5.0
os: win32 x64
@angular/animations: 4.4.4
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4

### Repro steps.
Include any library that has several language files like intl or momentjs.
Build like shown i18n cookbook / cli story.

### The log given by the failure.
no log

### Desired functionality.
Only translated versions of external script files that mat the build locale should be included to improve page load speed. Loading library translations without the need to use it is not good.

### Mention any other details that might be useful.
Suggestion:
Maybe some kind of locale variable syntax for imports could be replaced all over the source before the build starts. something like [[cli-locale]]. So you could simply write this into file path strings as most libraries follow the iso locale names.

**Comment by filipesilva** [comment]
Sorry, I don't quite understand what problem you are bringing up here. Can you elaborate a bit and provide a reproduction repository that we can clone and see the problem?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
