### ISSUE TITLE
ng e2e fails after creating a new project using angular-cli

### ISSUE THREAD

**Issue by ajayambre** [angular/angular-cli#811]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS: **Windows 7**

2. Versions:
   >angular-cli: 1.0.0-beta.1
   node: 4.1.2
   os: win32 x64

3. Repro steps. 
  I created a new app using cli
 > <code>ng new my-demo-app</code> 
  <code>cd my-demo-app</code>
  <code>ng e2e</code>

4. The log given by the failure. 
![image](https://cloud.githubusercontent.com/assets/5074211/15347681/887f2100-1ce1-11e6-9f29-61d6e84512d7.png)

5. Mention any other details that might be useful.
**Also I noticed that performance is pretty slow even after running cmd with admin privileges.**
>Just running <code>ng --version</code> took more than a min to display version.
Similarly when I ran <code>ng e2e</code>, it took more than 3 mins to start Chrome and then it eventually failed.

**Comment by caseyhoward** [comment]
You need to manually serve the files first by running "ng serve" beforehand.

On a related note, I would really like one command I can run to do a full build: lint, compile, unit tests, protractor tests (and serve files), etc.

**Comment by filipesilva** [comment]
@caseyhoward is right, you need to have `ng serve` running while doing `ng e2e`. 

Docs have been updated to reflect this: https://github.com/angular/angular-cli#running-end-to-end-tests
