### ISSUE TITLE
Lazy Route Module Routing File generation

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/angular-cli#8121]
```
- [x] feature request
```
I always have to create this file (`xx.routing.ts`), in my new module which is lazy loaded

Suppose I have about module, then I have to create `about.routing.ts` file and add
```
import { ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { AboutComponent } from './about.component';

const routes: Routes = [
  { path: '', component: AboutComponent }
];

export const routing: ModuleWithProviders = RouterModule.forChild(routes);
```
this content to it, and then go to its module, and add routing to the imports. 

Can this be automated by having new generate command?

**Comment by clydin** [comment]
As per the [wiki documentation](https://github.com/angular/angular-cli/wiki/generate-module), you should be able to use the following command:
```
ng generate module [name] --routing
```
