### ISSUE TITLE
Undocumented release 1.4.9 and RC2 of 1.5 ?

### ISSUE THREAD

**Issue by xnnkmd** [angular/angular-cli#8125]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

I have noticed that new npms have been released of angular cli 1.4.9 and RC2 of 1.5 but it is completly undocumented in the releases (I can see the release but there are no description of what they contain).

**Comment by filipesilva** [comment]
Sorry, those changelogs slipped between the cracks. They are up now in https://github.com/angular/angular-cli/releases.
