### ISSUE TITLE
Warnings During Global Install [fsevents] - Unsupported Platform

### ISSUE THREAD

**Issue by ddelella** [angular/angular-cli#8133]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.9
node: 6.11.4
os: win32 x64

### Repro steps.
1. Open command prompt
2. Run: **npm install -g @angular/cli@latest**

### The log given by the failure.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

### Desired functionality.
No warnings or errors would be displayed after the install, just the dependency tree.

**Comment by deebloo** [comment]
This is just a warning that displays on windows. Install should be fine

**Comment by filipesilva** [comment]
Closing as answered by @deebloo. This is a fairly common question so I'm marking it as a FAQ.
