### ISSUE TITLE
Relative paths in HTML template files are not being touched in "ng build -d {deploy-url}"

### ISSUE THREAD

**Issue by IagoBarboza** [angular/angular-cli#8134]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
@angular/cli: 1.4.4
node: 6.11.1
os: darwin x64
@angular/animations: 4.2.6
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/compiler-cli: 4.2.6
@angular/core: 4.2.6
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/platform-server: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.4.4
typescript: 2.3.4
macOS X Yosemite

### Repro steps.
* Run `ng build -d https://whatever-cdn.whatever.com`

### The log given by the failure.
* CSS files with relative paths (i.e. url('/assets/whatever.png)) are being updated to url('https://whatever-cdn.whatever.com/assets/whatever.png').
* Templates (HTML) files with relative paths (i.e. <img src="/assets/whatever.png">) are not being touched

### Desired functionality.
Would be very useful if template (HTML) files had the relative paths updated to the CDN as in CSS files.

**Comment by clydin** [comment]
Answered in #8139.  Also if the entire app deployment is located at the given address there should be no need to even use the deploy URL option.
