### ISSUE TITLE
ng build & hosted on Apache(httpd) 

### ISSUE THREAD

**Issue by sysmat** [angular/angular-cli#814]
Hi I'm new to angular2 and angular-cli, great work for this command line tool.

1. Windows 7

2. ng --version
angular-cli: 1.0.0-beta.1
node: 5.9.1
os: win32 x64

3. I create app, generate component add route and ng serve works fine and application is served at http://localhost:4200/.
With ng build(production: true) I create dist and content copy to application hosted on Apache server(http://localhost/myAngular2), but application is not working, because of broken links for js.

4.   LOG:
http://localhost/vendor/reflect-metadata/Reflect.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/vendor/zone.js/dist/zone.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/vendor/systemjs/dist/system.src.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/vendor/es6-shim/es6-shim.js Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:32 Uncaught ReferenceError: System is not defined

5.  Is any way to build generated apllication with some host or application prefix?

Regards, Tomaz

**Comment by hijoncon** [comment]
Yes you will got 404. In your index.html under dist. Try to change the path example below:
`<script src="myAngular2/vendor/es6-shim/es6-shim.js"></script>
<script src="myAngular2/vendor/reflect-metadata/Reflect.js"></script>
<script src="myAngular2/vendor/systemjs/dist/system.src.js"></script>
<script src="myAngular2/vendor/zone.js/dist/zone.js"></script>`

I think `ng build -prod` had some issues.  But try to build just `ng build`

**Comment by filipesilva** [comment]
If you're serving it under `http://localhost/myAngular2`, you need to change the `<base href="/">` tag in the generated `dist/index.html`. 

Currently there is no way of doing it automatically, but there is an issue for it here https://github.com/angular/angular-cli/issues/646
