### ISSUE TITLE
Unable to build my project

### ISSUE THREAD

**Issue by Venkat07S** [angular/angular-cli#8141]
Hi, 
Im facing a error while im trying to run my project 
ng serve
I have installed all prerequisite like CLI and nodejs.
Please help me in fixing
 
![screenshot 31](https://user-images.githubusercontent.com/32986251/31854151-96210f0a-b6b2-11e7-9407-7cefdd965bec.png)

**Comment by sboden** [comment]
You have a directory "C#Notes" ... remove the #.

**Comment by filipesilva** [comment]
@sboden is right that this is caused by the `#` character, but we should fix this on our side as it is due to file resolving logic in Angular.

**Comment by sboden** [comment]
I agree the code should be fixed... short-term work around would be to remove # from the directory name. 

If this issue is fixed, issue #8118 will also be fixed I think.

**Comment by sboden** [comment]
I debugged it, it ends up being in ngtools_impl.js which is in angular until v4.4.x and disappears in v5. So still have to check whether v5 is also affected.

problem is following in Routedef:

    RouteDef.fromString = function (entry) {
        var split = entry.split('#');
        return new RouteDef(split[0], split[1] || null);
    };

it gets passed e.g. "c:/projects/angular/c#notes/notes/src/app/app.module#AppModule", and the split() on # takes the wrong parts of the string.

Following fixes it (it takes the part after the most right # and the whole part in front):

    RouteDef.fromString = function (entry) {
        var split = entry.split('#');
        return new RouteDef(split.slice(0, -1).join('#'), split.pop() || null);
    };
