### ISSUE TITLE
1.5.0-RC - verbose stats

### ISSUE THREAD

**Issue by intellix** [angular/angular-cli#8144]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
Angular CLI: 1.5.0-rc.2
Node: 8.6.0
OS: darwin x64
Angular: 5.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0-rc.2
@angular-devkit/build-optimizer: 0.0.29
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.2
@schematics/angular: 0.0.48
typescript: 2.5.3
webpack: 3.7.1
```

### Repro steps.

Create an application with lots of lazy modules and serve:

### The log given by the failure.

```
chunk {styleguide.module} styleguide.module.chunk.js () 56.8 kB {admin.module} {affiliates.module} {deposit.module} {info.module} {main} {payment.module} {transactions.module} {withdraw.module}
```

### Desired functionality.

Every serve/change displays so much information that errors can be hidden if I have a small Terminal window. There's a huge block of chunks and references to lots of other modules. It seems to be a little too much information and I'm not sure if it's useful

**Comment by filipesilva** [comment]
This isn't intended, and seems to have originated with one of the recent webpack updates. Will fix.
