### ISSUE TITLE
ngx-modal not allowing to shrink modules

### ISSUE THREAD

**Issue by HemavathiJ** [angular/angular-cli#8150]
Hi, 
I have configure my angular project with 4.1.3 version:
**@angular/compiler  - 4.1.3
@angular/commmon  - 4.1.3
@angular/compiler - 4.1.3 
@angular/core - 4.1.3
@angular/router - 4.1.3**

As a dependency, I am using ngx-modal@0.0.29.

When i run "npm run shrinkwrap" command, i am getting the following error:

"Peer invalid: @angular/core@^2.0.0, required by ngx-modal@0.0.29" & 
"Peer invalid: @angular/router@^3.0.0, required by ngx-modal@0.0.29"

### My Insigth.
I have checked ngx-modal (0.0.29) package.json, which is dependent on the peer, 
@angular/core@2.0.0 & @angular/router@^3.0.0.

### Desired functionality.
Npm shrinkwrap --dev - Should shrink all the modules. 

Thanks,
Your help is highly appreciated!!

**Comment by filipesilva** [comment]
You have `@angular/core@4.1.3`, but your other package wants `@angular/core@^2.0.0`. `4.1.3` does not actually match `^2.0.0`. You can confirm that in https://semver.npmjs.com/. The `^` symbol only matches in the same major version (`2`, in this case). So the library you are trying to use needs to use Angular version 2.

**Comment by HemavathiJ** [comment]
Hi,
You suggested me to downgrade angular library. But my application is
compelety dependent on angular 4.1.3.

ngx-modal requires 2.0.0 right.

Is there any possibility of upgrading the peer dependencies of ngx-modal
(esp. core and router to some latest version).

I can understand that will be major change. I am just checking the
possibility..

**Comment by filipesilva** [comment]
I don't know really. You will have to ask them. The repository seems to be https://github.com/pleerock/ngx-modal.
