### ISSUE TITLE
On component CSS change, WDS recompiles but old CSS is still displayed

### ISSUE THREAD

**Issue by achinth** [angular/angular-cli#8151]
### Bug Report or Feature Request:
```
- [x] bug report
- [ ] feature request
```

When I make changes to the component's css file, the WDS tool (ng serve --environment dev --aot true) recognizes the changes and recompiles but the outputs the old css. If I stop and start WDS tool, the new css is used.

### Version:

Angular CLI: 1.5.0-rc.2
Node: 8.1.4
OS: darwin x64
Angular: 5.0.0-rc.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0-rc.2
@angular-devkit/build-optimizer: 0.0.29
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.2
@schematics/angular: 0.0.48
typescript: 2.5.3
webpack: 3.7.1

### Repro steps:

- Run command 'ng serve --environment dev --aot true' in terminal
- Make changes to any component specific css file
- WDS recognizes the change and recompiles
- On browser the changed css value is not shown, still displays old value.
- Restart WDS
- Browser displays new css value

Not sure if it is relevant but component css files are in a different folder from component ts file. Also component html file is in different folder from the other two.

### The log given by the failure:

No errors shown

**Comment by clydin** [comment]
The CLI has been updated significantly since version 1.5.0.  The current stable version is 8.3.5.  If this problem is still being encountered with the current version, please consider opening a new issue with updated details.
