### ISSUE TITLE
Terminal lists GETs for files that are not even in my project

### ISSUE THREAD

**Issue by smlombardi** [angular/angular-cli#8155]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.5
node: 6.11.2
os: darwin x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.4
typescript: 2.4.0

### Repro steps.
Run the project  with `npm start`, which maps to this command:

`"start": "(cd ../server && npm run nodemon) | (ng serve --sourcemap --extractCss -o --hmr -e=hmr --proxy-config proxy.config.json)",`

The project run and launches in my browser, but I also get a huge list in my terminal of files from a different, non-angular-cli project.  I sometimes run this other project, but it is not currently running nor is in open in the browser.

I quit the browser, run `killall node`, quit and relaunch terminal, even reboot the Mac.  They always show up.

for example:

```
webpack: Compiled successfully.
[HPM] GET /bower_components/angular-toastr/dist/angular-toastr.min.css -> http://localhost:8081
[HPM] GET /bower_components/bootstrap-daterangepicker/daterangepicker.css -> http://localhost:8081
[HPM] GET /bower_components/angular-bootstrap-toggle-switch/style/bootstrap3/angular-toggle-switch-bootstrap
... etc for hundreds of lines ...
```

**Comment by filipesilva** [comment]
Messages like `[HPM] GET /bower_components/angular-toastr/dist/angular-toastr.min.css -> http://localhost:8081
` are not printed by Angular CLI. 

One of your other processes is printing those messages. You need to find out which. Maybe you have a server running in the background, or a browser extension requesting those files, or an exposed port in the network, or something of the sort. This isn't the kind of thing we can help you much with here. Sorry.
