### ISSUE TITLE
Add option to disable Webpack Dev Server overlay

### ISSUE THREAD

**Issue by devoto13** [angular/angular-cli#8156]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.3.2
node: 8.4.0
os: darwin x64
@angular/cli: 1.3.2
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/compiler-cli: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/language-service: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6

### Repro steps.

1. `ng new myproj`
2. Add `"noUnusedLocals": true` to `tsconfig.json`.
3. `ng serve`
4. Add unused local variable in the `AppComponent`.

### Current functionality.

Webpack Dev Server overlay is covering whole screen yelling about an error, when there is no reason for this to happen ([example](https://www.dropbox.com/s/8iv962k700x8lay/Screenshot%202017-10-23%2021.42.21.png?dl=0)). And it is impossible either disable it completely or disable for some specific diagnostic messages. It is always enabled in [development target](https://github.com/angular/angular-cli/blob/e78689586301890d456848dc129166756f8b37b1/packages/%40angular/cli/tasks/serve.ts#L227).

### Desired functionality.

There should be an option to either disable overlay completely or a way to ignore some of the TypeScript diagnostics. For example [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader#ignorediagnostics-number-default) allows to do it by adding `ignoreDiagnostics` in the `tsconfig.json`.

### Mention any other details that might be useful.

This overlay is very annoying during development, when you remove a line of code and then have to go and remove import of declaration of the variable (which became unused) to see the result in the browser.

**UPDATE**

Just noticed that compilation fails completely in this case. Guess than there should be a way to either ignore some diagnostics in the development target or use custom tsconfig.json for development target.

**Comment by rixlabs** [comment]
Hi, if you use TSlint you can implement the same rule there so you can have a non blocking warning.

**Comment by devoto13** [comment]
@rixlabs Thanks, this should work in the short term. But long term would be nice to have a way to ignore some TypeScript diagnostics anyway.

**Comment by devoto13** [comment]
I understand it. But IMO usability is more important here than technical correctness.

Ideally I would like to have 2 TS configs: one for development with this option disabled and one for type-checking/bundling with the option enabled. Than I still get safety from TS and don't suffer during development process :)

**Comment by filipesilva** [comment]
Like @rixlabs said `noUnusedLocals` really is meant to fail builds, so if you put it in your tsconfig then the build really should fail...

I agree using that using that flag can be awkward but it's not something an error we're going to specialcase/override because you are explicitly setting it. The solution I've used in other projects is to use tslint for those rules. You can also set a second app that uses the other tsconfig.

You can read more about this topic in https://github.com/palantir/tslint/issues/1861#issuecomment-280690456, you're not the only one having trouble with this scenario.

**Comment by devoto13** [comment]
This issue is no longer relevant as there is no annoying overlay anymore. Error still can be observed in the Webpack `ng serve` output.
