### ISSUE TITLE
[bug] Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by amitport** [angular/angular-cli#8160]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
Angular CLI: 1.5.0-rc.3
Node: 8.7.0
OS: win32 x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped, upgrade

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.0-rc.3
@angular/flex-layout: 2.0.0-beta.9
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.30
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.3
@schematics/angular: 0.0.48
typescript: 2.3.4
webpack: 3.8.1
```

### Repro steps.
create angular/cli project
add dependency and import `socket.io-client@2.0.4`
ng serve --aot
open browser

### The log given by the failure.

```
index.js:10 Uncaught ReferenceError: global is not defined
    at eval (index.js:10)
    at Object.../../../../has-binary2/index.js (vendor.bundle.js:2914)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (index.js:8)
    at Object.../../../../socket.io-parser/index.js (vendor.bundle.js:9569)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (index.js:7)
    at Object.../../../../socket.io-client/lib/index.js (vendor.bundle.js:9527)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (io-service.ts:1)
```

**Comment by dottodot** [comment]
I seeing the same issue as well with `ng-socket-io` but also with `import 'intl';` in `polyfills.ts`

**Comment by amitport** [comment]
- I tried adding `(window as any).global = window;` to `pollyfils.ts`, but it didn't work. 
- reverting to 1.5.0-rc.2 worked

**Comment by dottodot** [comment]
Strange I've reverted to `1.5.0-rc.2` and still get it, no idea what's going on.

**Comment by amitport** [comment]
@dottodot try make sure it's a clean revert. try deleting node_modules and packge/yarn-lock before `npm i`

**Comment by dottodot** [comment]
Thanks that worked. I've gone back to `1.5.0-rc.2` and that's ok for me so seems like the issue is in `1.5.0-rc.3`

**Comment by Martin-Wegner** [comment]
Same problem here since `1.5.0-rc.3`, with `1.5.0-rc.2` no problems...

**Comment by robisim74** [comment]
Same error using _rc.3_ _Uncaught ReferenceError: global is not defined_ also importing another library (_jsrsasing_). It worked fine until _rc.2_.

**Comment by RicardoVaranda** [comment]
Hi guys, could you please provide a simple repo of this issue, that way it's easier and faster for the team to be able to debug the issue.

**Comment by dottodot** [comment]
@RicardoVaranda https://github.com/dottodot/ang5-test

All i've done is create a new project with 1.5.0-rc.3 and included `import 'intl'; ` in polyfills.ts and you get the error

**Comment by filipesilva** [comment]
This is definitely related to https://github.com/angular/angular-cli/pull/8132 as we've removed the node `global` object from the compilation environment. I'm investigating what can be done about it.

**Comment by filipesilva** [comment]
Just wanted to let you know we're looking into this. For the `intl` case using `import 'intl/dist/intl';` instead fixes it, but this might not be possible for all libs. `socket.io-client` also seems to have a dist in `socket.io-client/dist/socket.io.js`. I don't think the same can be used with `ng-socket-io` however, since it's importing the node package inside of it...

**Comment by MrBlaise** [comment]
Hey, I just wanted to chime in. I have the same issue upgrading to `1.5.0-rc.3` causes this issue, `1.5.0-rc.2` works fine. Didn't change anything just upgraded thew version. I use the following polyfills:

```
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following to support `@angular/animation`. */
import 'web-animations-js';  // Run `npm install --save web-animations-js`.


/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';

/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.
```

**Comment by bogacg** [comment]
With Rc.6 still having same problem.

**Comment by dottodot** [comment]
There's a pull request which I assume will fix it guess we just need to wait for it to be added

https://github.com/angular/angular-cli/pull/8189

**Comment by amitport** [comment]
This is fixed for me with release `1.5.0-rc.8` (https://github.com/angular/angular-cli/commit/1ba9eaecf518db2ff0553a97051bf2c975ca1115)

**Comment by StojanovicM** [comment]
Hi,
I am using Dragula version 1.5.0 with Angular 5, and still having problem
`"ReferenceError: global is not defined"`

I have just installed it and added it, imported and added to NgModule -> Imports, and my app crashes with this error.

Is there any step I am missing??

**Comment by filipesilva** [comment]
On version 6 of Angular CLI we are removing the shim for `global` and other node built-ins. You can read more about why this change was made in https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814.

If you are using a library that assumes these globals are present, you can try manually shimming it inside your `polyfills.ts` file:

```
// Add global to window, assigning the value of window itself.
(window as any).global = window;
```

**Comment by gioragutt** [comment]
@filipesilva Thank you so much!

**Comment by krishnareddy226** [comment]
declare var $: any;
I am getting the error 
$ not defined

**Comment by bluefire2121** [comment]
In my polyfill.ts, the import references to `intl`  were still there. Comment out or delete these if you get stuck, then add `(window as any).global= window`  as @filipesilva stated above.

**Comment by tobias74** [comment]
It seems that all the import-statements in the polyfill.ts are hoisted in the compiles js-file. Therefore putting 

`(window as any).global = window;`

at the top of the file polyfill.ts did not solve the issue, since in the compiled polyfill.js this command was located at the very end of the file (after all the imports)

**Solution**

I had to put the line
`(window as any).global = window;`
in a new file (global-shim.ts)

and import this file at the very top of the polyfill.ts

`import 'global-shim';`

**Comment by gioragutt** [comment]
@tobias74 I put it in the end of the file, it worked for me,

**Comment by yulm6** [comment]
When I adding sockjs-client, I got the same issue.
npm install sockjs-client --save

I did as @tobias74 ,maybe it worked,but the brower refreshes frequenly.

**Comment by chetanbirajdar** [comment]
@tobias74  Thanks that worked

**Comment by Evllis** [comment]
@filipesilva 
Thank you!!!!!!!!! ^_^

**Comment by SamiHK** [comment]
I removed all these things.
`import 'intl'; 
(window as any).global = window;
 // Run `npm install --save intl`.
import 'intl/locale-data/jsonp/en';`

AND NOW :D
This polyfill.ts is working for me.

`import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

import 'core-js/es7/array';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';

/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';

/**
 * Required to support Web Animations `@angular/common/animations`.
 * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
 **/
import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.

/***************************************************************************************************
 * APPLICATION IMPORTS
 */




/**
 * Fix for ngx-chart to work on ie11
 */
if ( typeof SVGElement.prototype.contains === 'undefined' )
{
    SVGElement.prototype.contains = HTMLDivElement.prototype.contains;
}`

**Comment by avinexus7** [comment]
> On version 6 of Angular CLI we are removing the shim for `global` and other node built-ins. You can read more about why this change was made in [#9827 (comment)](https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814).
> 
> If you are using a library that assumes these globals are present, you can try manually shimming it inside your `polyfills.ts` file:
> 
> ```
> // Add global to window, assigning the value of window itself.
> (window as any).global = window;
> ```
> I ran a quick test with `socket.io-client` and this seemed to allow it to run.

Is this the right way of implementing socket.io in Angular 2? I mean does the above line give any side affects that may be obtrusive in the future?

**Comment by BMLande** [comment]
solution of  @filipesilva  is worked .
i have issue when i am migrating  ng5 to ng6 .
thanks @filipesilva

**Comment by shayanpaul91** [comment]
add 
(window as any).global = window;
on polyfills.ts
it should work

**Comment by fkolar** [comment]
@filipesilva I see this is pretty old issue but even today, newly generated project and I am testing apolo graphql does not add the global. 

so I have to add to my `polyfills.ts` the `(window as any).global = window;`

Is this normal ?

**Comment by clydin** [comment]
Yes.  `global` does not exist in a browser.  A library that supports web browsers should not be using Node.js specific functionality.

**Comment by willkara** [comment]
Will this ever be fixed in the main module? Still apparently happens in new projects.

I've tried adding a basic AwsAmplify project and this happens.

**Comment by amitport** [comment]
@willkara , read the comment right before yours.

Follow the stack trace to see which package uses `global`. submit an actionable, reproducible issue on that package repo

**Comment by willkara** [comment]
@amitport fair comment. I'll follow the trace again and see where it happens.

**Comment by danieldanielecki** [comment]
In case, if your **target** is **node** in webpack (`target: 'node'`), because you want to fix `"Can't resolve 'fs'`. Then you're getting the following error `Fix: "Uncaught ReferenceError: global is not defined"` do it as follows `node: { global: true, fs: 'empty' }`. **Bonus**: if you got error `"Uncaught ReferenceError: exports is not defined".` simply add `libraryTarget: 'umd'`. The complete webpack config code is below.

```
const webpackConfig = {
  node: { global: true, fs: 'empty' }, // Fix: "Uncaught ReferenceError: global is not defined", and "Can't resolve 'fs'".
  output: {
    libraryTarget: 'umd' // Fix: "Uncaught ReferenceError: exports is not defined".
  }
};

module.exports = webpackConfig; // Export all custom Webpack configs.
```

**Comment by amitport** [comment]
@filipesilva can you lock this issue? seem to keep "sprouting" in all directions even though it's closed.

**Comment by ar1stio** [comment]
just add (window as any).global = window; in polyfills.ts in ionic
