### ISSUE TITLE
Proposal: Support default custom output path

### ISSUE THREAD

**Issue by JonCubed** [angular/angular-cli#817]
**Problem:**
Currently there is no official support for setting a default custom path. This can be important for those that have different project structures or use a different server to host angular2 such as asp.net core which expects static files to be in a folder called wwwroot/. 

There is also not a consistent way to unofficially set a default value for custom output path. For `ng buld` and `ng serve` as they are still just the default commands in ember cli you can create a *.ember-cli* file with the following and it will work

```
{
    "output-path": "wwwroot/"
}
```

However, for `ng test` it has the output folder hard-coded to `dist/` and as it is, as an add-on command would not use *.ember-cli*

**Proposal:**

I was only able to find three commands that use an output-path flag, *build*, *serve*, *test*. The following are what I think would need to change or be completed to support this feature.

* **General**
    * Support output path in *angular-cli.json* as a sub property of *defaults*. Would probably be called *outputPath* to match the cli flag *output-path* and the format in angular-cli.json already. Would look something like:
        ```
        {
            "defaults": {
                "outputPath": "wwwroot/"
           }
        }
        ```

       ***Required change:*** Update [*angular-cli.json* schema](angular-cli/lib/config/schema.json)

* Test command
    * Remove hard-coded output path and instead retrieve it from 
          
       ***Required change:*** Use [`this.project.ngConfig`](https://github.com/angular/angular-cli/blob/master/addon/ng2/commands/test.js#L24) to get default settings and use it instead to construct [`buildOptions`](https://github.com/angular/angular-cli/blob/master/addon/ng2/commands/test.js#L24)

    * Add *output-path* flag to be consistent with other commands.
         ***Required change:*** Add another option to [`availableOptions`](https://github.com/angular/angular-cli/blob/master/addon/ng2/commands/test.js#L13)

* Build Command
   * Create a *BuildCommand* in [*addon/ng2/commands*](https://github.com/angular/angular-cli/blob/master/addon/ng2/commands/). This would be a wrapper of the [ember cli build command](ember-cli/lib/commands/build.js) but would read default settings from *angular-cli.json* 

* Serve Command
   * Create a *ServeCommand* in [*addon/ng2/commands*](https://github.com/angular/angular-cli/blob/master/addon/ng2/commands/). This would be a wrapper of the [ember cli serve command](ember-cli/lib/commands/server.js) but would read default settings from *angular-cli.json* 

**Note:** As I have told @hansl I am willing to go through the design process and work on this.

**Comment by JonCubed** [comment]
other use cases:
* the need to have a different output path for different environments, see #801

**Comment by JonCubed** [comment]
@filipesilva @hansl what is the next step? Design docs or can I start working on this?

**Comment by filipesilva** [comment]
@JonCubed you're most welcome to make a PR for this functionality, make sure to add tests that verify it works as well.

**Comment by JonCubed** [comment]
@filipesilva sure no problems

**Comment by filipesilva** [comment]
Implemented as `outDir` in `angular-cli.json` currently. See https://github.com/angular/angular-cli/pull/1109#issuecomment-252507439 also.

**Comment by rahul-winner** [comment]
Neither of option to create custom distribution folder is working for me. I tried following

> ng build --outDir=customDist
> ng build --output-path=customDist
> ng build --outDir customDist
> ng build --output-path customDist
> 

nothing worked :( 

Could anyone please help me out. 

Thanks. Rahul

**Comment by JonCubed** [comment]
@rahul-winner looking at [build.ts](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/commands/build.ts#L15) `ng build --output-path customDist` should work. Alternatively if you want it to be a default and not have to use the `--output-path` flag you can use `--source-dir` with `ng new` or `ng init` commands
