### ISSUE TITLE
Generate validator

### ISSUE THREAD

**Issue by zlepper** [angular/angular-cli#8170]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
I would like to be able to generate a new custom validator like i'm generating components or services. 
This includes all the necessary selectors and providers. The class that is generated should implement the `Validator` interface.

The use case for this is that i'm only doing this semi-frequently, so I can't remember all the "boilerplate" like the providers. I have existing examples i can look at, but doing `$ ng g validator Foo` to generate a `FooValidator` would ease that workflow a lot.

**Comment by ciesielskico** [comment]
With the next release (it is already possible with the RC of 1.5.0) you will be able to implement your own schematics, something like your own blueprints for  the generator.

**Comment by zlepper** [comment]
Ohh, that sounds neat. Though an official template from the Angular team would still be nice, especially for new project/computers, depending on how it works.

**Comment by clydin** [comment]
Just wanted to add a quick note that there are some examples of what the files could look like in this issue: https://github.com/angular/angular-cli/issues/8709

**Comment by ShinDarth** [comment]
It would be nice if we had something like:

`ng generate validator path/to/my-custom-validator`

which automatically generates skeletons for a custom form validator and its unit tests.

For example:

`my-custom.validator.ts`

```
import { AbstractControl, ValidationErrors, ValidatorFn } from '@angular/forms';

export function myCustomValidator(arg1: string, arg2: string): ValidatorFn {
  return (form: AbstractControl): ValidationErrors | null => {
    const error: ValidationErrors = { myCustomErrorName: true };

    // ...

    form.setErrors(null);
    return null;
  };
}
```


`my-custom.validator.spec.ts`

```
import { AbstractControl, FormControl, FormGroup, ValidationErrors, ValidatorFn } from '@angular/forms';
import Spy = jasmine.Spy;

import { myCustomValidator } from './my-custom-validator.ts';

describe('MyCustomValidator', () => {
  let form: FormGroup;
  let myCustomValidatorFn: ValidatorFn;

  const error: ValidationErrors = { myCustomErrorName: true };

  beforeEach(() => {
    form = new FormGroup({
      // ...
    });

    myCustomValidatorFn = myCustomValidator(...);

    spySetErrors = spyOn(form, 'setErrors').and.callThrough();
  });

  it('should correctly ...', () => {
    // ...

    expect(myCustomValidatorFn(form)).toEqual(...);

    // ...
  });
});
```

**Comment by michaeljota** [comment]
I think this should be builtin in the cli. A custom validator as a special class that implements the `Validator` interface. 

```sh
$ ng generate validator my-custom-validator
```
Generates:
```typescript
import { Validator, AbstractControl } from '@angular/forms';

export class MyCustomValidator implements Validator {
  validate(c: AbstractControl): { [key: string]: any } {
    throw new Error('Method not implemented.');
  }
  registerOnValidatorChange?(fn: () => void): void {
    throw new Error('Method not implemented.');
  }
}
```

**Comment by ErraticFox** [comment]
Any update on this? This would be pretty useful.

**Comment by FrancescoBorzi** [comment]
I've started working on that here: https://github.com/angular/angular-cli/pull/13047

However this is my first contribution attempt and I need help to figure out how to complete it.

**Comment by filipesilva** [comment]
Heya, I'm closing this following the answer in https://github.com/angular/angular-cli/pull/13047#issuecomment-447080555.
