### ISSUE TITLE
Bug with scripts.bundle.js

### ISSUE THREAD

**Issue by vmagalhaes** [angular/angular-cli#8173]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.9

Hi,
I have a problem with my build, can you help me?
My scripts.bundle.js doesn't build of same way that builded before and this are breaking my app

Before it initialize with: webpackJsonp(....
Now it init with the normal code, just a compile of all js archives.

What can I do to solve this?

Thanks,

**Comment by clydin** [comment]
That’s not a bug.  That’s the intentional operation of the script bundling.  The script bundle is meant to be an equivalent of adding script elements to index.html.

Can you provide details as to why this would break your app? A minimal reproduction would be extremely helpful.

**Comment by ViictorG1** [comment]
@clydin in my application I need to import a local script js that found at assests/js/ folder. In last version of my app the scripts.bundle.js initialize with webpackJsonp(..... And to run the new version of my app,  I need change the new scripts.bundle.js by the old scripts.bundle.js. 

I use the vkbeautify library and for some reason when the code are init the console display vkbeautify is not defined, with this New scripts.bundle.js. Already with this old scripts.bundle.js that doesn't display and work normally.

Can be what?

Thanks.

**Comment by filipesilva** [comment]
Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by ViictorG1** [comment]
@filipesilva Hi, I tried to do the repro, but with it the build run normally.

Here have the the old scripts.bundle.js that run normally and the new scripts.bundle.js that display vkbeautify is not defined.

[old_scripts.43c02bf1b0647a47d56d.bundle.zip](https://github.com/angular/angular-cli/files/1414423/old_scripts.43c02bf1b0647a47d56d.bundle.zip)
[new_scripts.208323b16203ec890d7b.bundle.zip](https://github.com/angular/angular-cli/files/1414424/new_scripts.208323b16203ec890d7b.bundle.zip)

With the repro, it initialize with the way that I wanna, with webpackJsonp(...., but with new version of my project initializes without it and breaks showing vkbeautify is not defined...

**Comment by filipesilva** [comment]
@ViictorG1 just having those bundle files isn't very helpful. Can you create a new project that shows the problem instead? We changed the way we bundle with scripts as @clydin said it shouldn't make any different. We'll need to see a simple project showing how this is problematic to be able to investigate.

**Comment by ViictorG1** [comment]
@filipesilva I created a new project but the problem don't appear, my project unfortunately with this new bundle make of the local script found in assets/javascript don't run

**Comment by ViictorG1** [comment]
@filipesilva I will upload my project, it's short, and send to you

**Comment by ViictorG1** [comment]
Take a look, I built in production

[dist.zip](https://github.com/angular/angular-cli/files/1418322/dist.zip)

**Comment by ViictorG1** [comment]
@filipesilva Ok, thanks for help, I will try other solution.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
