### ISSUE TITLE
Datatable js file appending data action column edit link routerlink not working

### ISSUE THREAD

**Issue by sumitsolanki96** [angular/angular-cli#8179]
### Bug Report or Feature Request (mark with an `x`)
```
Hii all, i have customer component and appending data into datatable from getCustomer.js file. but in js file where i am appending data into datatable. in action column edit icon i am unable to access routerlink or (click) event of angular in js file. where in component it's working fine. how can i fix it in angular 4??
Thanks in advance...
```

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
