### ISSUE TITLE
Unable to get any ng methods to work properly

### ISSUE THREAD

**Issue by illegalnumbers** [angular/angular-cli#8180]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

latest ng installed with cli installed globally
node version is 8.8
npm version is 5.4.2
mac osx 10.11.6

### Repro steps.

Install ng-cli and then run ng server or ng --help or ng --version

### The log given by the failure.

```
module.js:515
    throw err;
    ^

Error: Cannot find module 'rxjs/add/operator/map'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/bytenel/workplace/wger/node_modules/@angular-devkit/core/src/logger/indent.js:10:1)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
```

Doesn't work even if I install that module globally.

### Desired functionality.

Plz2work and serve my app or give something useful

**Comment by filipesilva** [comment]
Hi there, when you say `latest ng installed with cli` can you specify which version that is please? You can do `npm ls @angular/cli` to see this version since `ng help` doesn't work.

**Comment by illegalnumbers** [comment]
wger@1.8.0 /Users/bytenel/workplace/wger
└── @angular/cli@1.4.9

is the one listed in my project and 

/Users/bytenel/.nvm/versions/node/v8.8.0/lib
└── @angular/cli@1.4.9

is the one globally

**Comment by filipesilva** [comment]
It sounds like a dependency wasn't installed correctly... can you try reinstalling please? Using 1.5.0 instead might help as well.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
