### ISSUE TITLE
Implement 'disableChecks' protractor flag

### ISSUE THREAD

**Issue by karlos1337** [angular/angular-cli#8182]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```
### Versions.
@angular/cli: 1.4.9
node: 8.7.0
os: linux x64
@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.5.3
Arch Linux

### Repro steps.
ng e2e

### The log given by the failure.
https://gist.github.com/karlos1337/971c5e4085faa9df9b1b3215d97e2367

### Desired functionality.
Implement 'disableChecks' protractor flag.

I want to use a protractor module for retrying failed e2e tests but use some flags that ng-cli don't pass to protractor, here the issue in protractor-retry repo where this is talked about
https://github.com/yahoo/protractor-retry/issues/6

**Comment by filipesilva** [comment]
We don't send any extra flags into protractor really. The only flags we support are the ones in https://github.com/angular/angular-cli/wiki/e2e.

I agree that looks like a pretty useful library, I might have to add it to some of the e2e pipelines I use.

But it's also assuming a that the command that's being ran is `protractror`, but we're running `ng e2e` instead. `ng e2e` has different flags from protractor and does different things.

I agree that allowing the flags to be passed through might fix it, but we can't guarantee flag parity with `protractor`. 

Meanwhile you can also run protractor separately though.

**Comment by alan-agius4** [comment]
You can set the `disableChecks` directly in your protractor configuration file.
