### ISSUE TITLE
Separate NPM package for NamedLazyChunksWebpackPlugin

### ISSUE THREAD

**Issue by pglazkov** [angular/angular-cli#8184]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
1.3.0+

### Desired functionality.
Currently [`NamedLazyChunksWebpackPlugin`](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/plugins/named-lazy-chunks-webpack-plugin.ts) is an "internal" plugin that is available only as part of the CLI. However, this plugin could be useful also for the apps that have custom Webpack config and don't use the CLI. 

Therefore, I have copied the plugin into its own repository and an NPM package: https://github.com/Independer/angular-named-lazy-chunks-webpack-plugin

Please consider either using that package OR pulling the plugin into one of the[ `@angular-devkit`](https://github.com/angular/devkit) packages, so that it can be re-used in projects with a custom Webpack config.

**Comment by filipesilva** [comment]
I agree this would be nice, WDYT @hansl?
