### ISSUE TITLE
Ie 11 error - proxy object is undefined

### ISSUE THREAD

**Issue by sergamers** [angular/angular-cli#8186]
i've this polyfills.ts
https://gist.github.com/sergamers/21ba3fc86d09ce0a9b23bbc518d1870e
After start app in ie have error -  proxy object is undefined. I included googleChrome proxy-polifil, but then have error - Object.assign is undefined. Something is wrong here. How to fix this problem?

**Comment by KarthickSelvam** [comment]
any solution to this?

**Comment by mgechev** [comment]
For support requests, we'd recommend you to use our Gitter channel or StackOverflow with tag angular or angular-cli. If I've misunderstood the problem, please open a new issue following our template and sharing a minimal demo where we can reproduce it.
