### ISSUE TITLE
Expose Webpack's watchOptions.aggregateTimeout in angular-cli.json

### ISSUE THREAD

**Issue by 9ae8sdf76** [angular/angular-cli#8191]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

    @angular/cli: 1.4.9
    node: 8.7.0
    os: darwin x64
    @angular/animations: 4.4.6
    @angular/cdk: 2.0.0-beta.12
    @angular/common: 4.4.6
    @angular/compiler: 4.4.6
    @angular/core: 4.4.6
    @angular/forms: 4.4.6
    @angular/http: 4.4.6
    @angular/material: 2.0.0-beta.12
    @angular/platform-browser: 4.4.6
    @angular/platform-browser-dynamic: 4.4.6
    @angular/router: 4.4.6
    @angular/cli: 1.4.9
    @angular/compiler-cli: 4.4.6
    typescript: 2.3.4

### Repro steps.

`ng serve`

### The log given by the failure.

N/A

### Desired functionality.

In webpack, there is a [`watchOptions.aggregateTimeout`](https://webpack.js.org/configuration/watch/#watchoptions-aggregatetimeout) setting that defines the time (in milliseconds) before initiating a browser reload. This allows multiple changes to one or more files to only trigger building once. 

### Mention any other details that might be useful.

In [`cli/tasks/build.ts`](https://github.com/angular/angular-cli/blob/15cf37e0e6526770860ecccd13e327fc65fe6eb0/packages/%40angular/cli/tasks/build.ts#L77), I see the entry point for watching the files is little more than a pass-through of the cli configuration into the webpack configuration.

TIA!

**Comment by clydin** [comment]
The default should be 300 milliseconds.  Have you found this number to be inadequate? if there is a more optimal number the default could potentially be changed.

**Comment by dohpaz42** [comment]
@clydin yes, the default is 300ms. Yes, I find it inadequate. But I question the idea of trying to use a one-size-fits-all approach, when something like this will be purely subjective. For what it's worth, I can appreciate the ideal of not over-encumbering everyone with the full configuration potential of webpack (it's a lot, and it could be very easily messed up).

In this case, I am hoping to successfully argue the inclusion of the `watchOptions.aggregateTimeout` property so anybody can tweak it to their personal preference. My main argument for this is that it only affects development environments (e.g., no side-effects for production builds), and it has the potential positive impact on individual developer productivity.

Thank you!

**Comment by pfeigl** [comment]
This could also greatly help in library development when using npm link. The current watch-process fails without any way to recover when a folder from node_modules is removed and re-created. 

I think the implementation would be as easy as replicating the logic of hmr as seen here:
https://github.com/angular/angular-cli/blob/b6b8acc1bf9928fc8016d77980dc61e9d978876b/packages/%40angular/cli/tasks/serve.ts#L242

**Comment by alan-agius4** [comment]
Hi all, 

Thanks for all the feedback. 

If this is still an issue with Angular CLI 12, kindly file a new issue providing all the necessary information.

The general feeling however, is that we should not provide this option as part of our public API unless absolutely necessary and instead if needs be we should update the default value.

Thank you all.
