### ISSUE TITLE
ERROR in Could not resolve "app/requests/requests.module" 

### ISSUE THREAD

**Issue by rkumar654** [angular/angular-cli#8196]
i getting error like this...
ERROR in Could not resolve "app/requests/requests.module" from "D:/internet-bank
ing/src/app/app-routing.module.ts".

in app-routing.moduel.ts  file 
 {
      path: 'requests',
      loadChildren : 'app/requests/requests.module#RequestsModule'
   }
How to solve?

**Comment by filipesilva** [comment]
@rkumar654 you should use a relative path instead. I think the relative path is the one below.
```
{
  path: 'requests',
  loadChildren : './requests/requests.module#RequestsModule'
}
```

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
