### ISSUE TITLE
1.5-rc3 broke the i18n locale data transformer

### ISSUE THREAD

**Issue by ocombe** [angular/angular-cli#8199]
### Bug Report or Feature Request
```
- [x] bug report
```

### Versions.

```
Angular CLI: 1.5.0-rc.3
Node: 6.9.5
OS: win32 x64
Angular: 5.0.0-rc.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0-rc.3
@angular-devkit/build-optimizer: 0.0.31
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.3
@schematics/angular: 0.0.48
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.
```sh
git clone https://github.com/ocombe/i18n-demo-cli
```

Change package.json `@angular/cli` version to 1.5-rc.3
Run the app with `npm run start:aot:fr`

### The log given by the failure.
```
main.ts:5 Uncaught ReferenceError: registerLocaleData is not defined
    at eval (main.ts:5)
    at Object.../../../../../src/main.ts (main.bundle.js:69)
    at __webpack_require__ (inline.bundle.js:55)
    at Object.0 (main.bundle.js:98)
    at __webpack_require__ (inline.bundle.js:55)
    at webpackJsonpCallback (inline.bundle.js:26)
    at main.bundle.js:1
```

### Desired functionality.
It should load the app without this error.

### Mention any other details that might be useful.
The error is most likely in the i18n locale data transformer: https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/transformers/register_locale_data.ts

It worked fine in rc2.

I've checked the "vendor.bundle.js" and the "registerLocaleData" is defined differently between rc2 and rc3. I suspect that we changed something to the way we bundle angular packages.

In rc2: `__webpack_require__.d(__webpack_exports__, \"d\", function() { return registerLocaleData; });`
In rc3: `__webpack_require__.d(__webpack_exports__, \"registerLocaleData\", function() { return registerLocaleData; });`

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/8205
