### ISSUE TITLE
Barrels should export *, not Symbol names by default

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#820]
in 1.0.0-beta4 it currently does 

```
export {environment} from './environment';
export {HelloMobileAppComponent} from './hello-mobile.component';
```

Should just do 

```
export * from './environment';
export * from './hello-mobile.component';
```

This way we have less to refactor if we change names without tooling *and* the CLI nor the user do not have to keep adding things to this file as we add exported symbols from the files.

**Comment by tapas4java** [comment]
@johnpapa You mean only for top level barrel or all??

**Comment by johnpapa** [comment]
all

**Comment by johnpapa** [comment]
yay!
