### ISSUE TITLE
Installing different versions of angular with cli

### ISSUE THREAD

**Issue by fellz** [angular/angular-cli#8200]
Hi
How to specify version of angular that should be installed ? Right now it's 4.2.4 with 1.4.9 cli. Any attempts to update packages with npm update fail. I guess there is no way to point cli version of angular in console like `ng new project --angular=4.4.6`

**Comment by grizzm0** [comment]
See my answer here https://github.com/angular/angular-cli/issues/8039#issuecomment-336627850

**Comment by fellz** [comment]
Ok ^4.2.4 will match >=4.2.4,<5.0.0. should update to 4.4.6 but it is not. `npm outdated` shows nothing about angular and `ncu` utility shows the same.

**Comment by grizzm0** [comment]
Inspect your site in dev tools and check the ng-version attribute. You'll see that it's most likely 4.4.6.

**Comment by filipesilva** [comment]
Heya, `ng new` will use the versions set on https://github.com/angular/devkit/tree/master/packages/schematics/angular. We try to keep it up to date the with latest stable, butd on't have plans to add a flag to install a specific version. 

When you want a specific version, the best way is to update your `package.json` after installation. The way your package manager lists packages that should be updated is heavily dependent on it's version and cache though.
