### ISSUE TITLE
CSS sourcemap not working with `@component({styles | styleUrls})`

### ISSUE THREAD

**Issue by JounQin** [angular/angular-cli#8206]
### Bug Report or Feature Request (mark with an `x`)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Versions.

@angular/cli: 1.4.9
node: 8.8.1
os: darwin x64

### Repro steps.

new project with angular-cli, add some code in *app.component.css* like `div{color: red}`, run `ng serve -sm`

### Desired functionality.

I'd love to work with css sourcemap or even modify css/scss source with chrome dev tools directly.

**Comment by filipesilva** [comment]
Last time I checked, there was a problem in Angular itself regarding component sourcemaps (https://github.com/angular/angular-cli/issues/3617). But I see that @asnowwolf's fix in Angular was merged (https://github.com/angular/angular/pull/18641). If I'm reading this correctly, it was merged in 5.x but not in 4.x. There's also https://github.com/angular/angular/pull/16088 that doesn't seem to be merged. 

@hansl do you know what's the current status of sourcemap support for component css?

**Comment by asnowwolf** [comment]
It's works with 5.0 now. `ng serve --extract-css` (v1.5.0), but we'd better remove `--extract-css` too, see <https://github.com/angular/angular-cli/pull/8294>.

**Comment by JounQin** [comment]
Thx, that works in my own project without angular-cli.
