### ISSUE TITLE
ERROR TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by rahuldpi** [angular/angular-cli#8208]
I was making some changes to the template after restarting the ng server. I started getting error in console. I reverted the working code back but its still throwing the same error. I'm finding it very difficult to debug this error because it's not pointing to a template file. There are 2 errors displayed in the console:

**Error1:**
> ERROR TypeError: Cannot read property 'map' of null
>     at splitDepsDsl (core.es5.js:8712)
>     at _def (core.es5.js:10695)
>     at directiveDef (core.es5.js:10652)
>     at View_AppComponent_Host_0 (AppComponent_Host.html:1)
>     at proxyClass (compiler.es5.js:14971)
>     at resolveDefinition (core.es5.js:8756)
>     at ComponentFactory_.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactory_.create (core.es5.js:9859)
>     at ComponentFactoryBoundToModule.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactoryBoundToModule.create (core.es5.js:3333)
>     at ApplicationRef_.webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.bootstrap (core.es5.js:4768)
>     at core.es5.js:4546

**Error 2:**

> zone.js:661 Unhandled Promise rejection: Cannot read property 'map' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'map' of null
>     at splitDepsDsl (core.es5.js:8712)
>     at _def (core.es5.js:10695)
>     at directiveDef (core.es5.js:10652)
>     at View_AppComponent_Host_0 (AppComponent_Host.html:1)
>     at proxyClass (compiler.es5.js:14971)
>     at resolveDefinition (core.es5.js:8756)
>     at ComponentFactory_.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactory_.create (core.es5.js:9859)
>     at ComponentFactoryBoundToModule.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactoryBoundToModule.create (core.es5.js:3333)
>     at ApplicationRef_.webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.bootstrap (core.es5.js:4768)
>     at core.es5.js:4546 TypeError: Cannot read property 'map' of null
>     at splitDepsDsl (http://localhost:4200/vendor.bundle.js:100930:17)
>     at _def (http://localhost:4200/vendor.bundle.js:102913:36)
>     at directiveDef (http://localhost:4200/vendor.bundle.js:102870:12)
>     at View_AppComponent_Host_0 (ng:///AppModule/AppComponent_Host.ngfactory.js:6:67)
>     at proxyClass (http://localhost:4200/vendor.bundle.js:79342:29)
>     at resolveDefinition (http://localhost:4200/vendor.bundle.js:100974:17)
>     at ComponentFactory_.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactory_.create (http://localhost:4200/vendor.bundle.js:102077:40)
>     at ComponentFactoryBoundToModule.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactoryBoundToModule.create (http://localhost:4200/vendor.bundle.js:95551:29)
>     at ApplicationRef_.webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:96986:57)
>     at http://localhost:4200/vendor.bundle.js:96764:81

**Comment by filipesilva** [comment]
I haven't seen that error before so it's hard to say what it means.... Can you provide the information we ask for in the issue template please? Versions, etc. That helps understand what's going on. A reproduction would be really helpful as well.

**Comment by rahuldpi** [comment]
The error occurred due to broken angular package. I ran yarn upgrade command which fixed the issue.

**Comment by MuhammadTahir92** [comment]
how to solve this issue for windows users @rahuldpi  @filipesilva ??
