### ISSUE TITLE
SourceMaps are invalid

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#8218]
`ng serve` with the new plugin and compiler have all over the place sourcemaps.

**Comment by hansl** [comment]
Just confirmed that source maps are working correctly in DEV, but are causing problems in PROD. We will fix PROD after 5.0 and 1.5 release

Closing this for now.

**Comment by Manduro** [comment]
@hansl Is there an issue to track for this issue with production sourcemaps?
