### ISSUE TITLE
Allow creation of an app without specifying main file or allow an empty string in main property

### ISSUE THREAD

**Issue by abidmix** [angular/angular-cli#8225]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
```

### Versions.
C:\PMLCLI\Phoenix\Phoenix_LMS\Phoenix.Web>ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.4
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/upgrade: 4.4.6
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.4
typescript: 2.3.4

 Windows (10)

### The log given by the failure.

![image](https://user-images.githubusercontent.com/12702893/32122575-c8c08a78-bb2e-11e7-8bc2-9e9e1e70aac0.png)

### Desired functionality.

What would like to see implemented?

I would like to have an app bundled without specifying a main file.

What is the usecase?
I have an angular cli configuration working wonderfully for multiple apps. But 
 I would want these separate apps to share common scripts. How do I put these 
 scripts
       

    "libs/abc.js",
    "libs/def.js",
    "libs/fgh.js",

 for instance in a  common app because they are both used by app1 and app2.

   

  ```
  "apps": [
        {
          "name": "sharedvendor",
          "root": "Scripts",
          "outDir": "Scripts/dist/sharedvendor",
          "deployUrl": "Scripts/dist/sharedvendor/",
         
          "scripts": [
           //Was thinking to put my common scripts here but angular cli wont 
           //allow me to create an app without a main file
           ]
          },
    	
         {
          "name": "app1",
          "root": "Scripts",
          "outDir": "Scripts/dist/sharedvendor",
          "deployUrl": "Scripts/dist/sharedvendor/",
          "main": "app1/app1.entrypoint.ts",
          "polyfills": "polyfills.ts",
         
          "scripts": [
            "libs/abc.js",
            "lics/def.js",
            "libs/fgh.js",
            "libs/app1custom.js"
          ]
          },
    	
    	{
          "name": "app2",
          "root": "Scripts",
          "outDir": "Scripts/dist/sharedvendor",
          "deployUrl": "Scripts/dist/sharedvendor/",
          "main": "app2/app2.entrypoint.ts",
          "polyfills": "polyfills.ts",
         
          "scripts": [
            "libs/abc.js",
            "lics/def.js",
            "libs/fgh.js",
            "libs/app2custom.js"
          ]
          }
    
        }
    	
    	]
```
These are launched from a single page but are hosted in different containers. Am I on the right path or is there a better way to do this?

**Comment by mgechev** [comment]
This seems like something out of the scope of the CLI. If you're interested in extending your build, look at ngx-build-plus. If I've misunderstood the issue, please open a new one and explain your use case. Thank you! :)
