### ISSUE TITLE
Wiki - Stories - Universal Rendering is missing a key ingredient for lazy loading

### ISSUE THREAD

**Issue by vipero07** [angular/angular-cli#8237]
The [final part of the first step](https://github.com/angular/angular-cli/wiki/stories-universal-rendering#srcappappservermodulets) for the universal rendering is missing a very key part that is necessary for lazy loading to work correctly on the server.

Specifically app.server.module.ts should look like this:

```
import { NgModule } from '@angular/core';
import { ServerModule } from '@angular/platform-server';
import { ModuleMapLoaderModule } from '@nguniversal/module-map-ngfactory-loader';

import { AppModule } from './app.module';
import { AppComponent } from './app.component';

@NgModule({
  imports: [
    AppModule,
    ServerModule,
    ModuleMapLoaderModule
  ],
  bootstrap: [AppComponent],
})
export class AppServerModule { }
```

Note **ModuleMapLoaderModule** is necessary, otherwise node will throw an error every time a page that is supposed to be lazy loaded is attempted. An error akin to: ERROR: Cannot find module './lazy/lazy.module.ngFactory'. 

Interestingly this would be difficult to catch if you are not reading the node output since the pages still load only they are being rendered on the client, defeating the whole server side rendering purpose.

**Comment by filipesilva** [comment]
@Brocco can you investigate?
