### ISSUE TITLE
[@ngtools/webpack]: incorrent import of entry module since 1.8.0-rc.4

### ISSUE THREAD

**Issue by bukharin** [angular/angular-cli#8238]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

os: windows 10
node: 8.8.1
npm: 5.3.0
webpack: 3.8.1

### Repro steps.

I am using `AngularCompilerPlugin` like:

``` js
new ngc.AngularCompilerPlugin({
                tsConfigPath: helpers.root('tsconfig.aot.json'),
                entryModule: helpers.root('src/app/app.module.ts#AppModule')
            }),
```

In my `main.ts` I have the following bootstrap code:

``` js
import {platformBrowserDynamic} from "@angular/platform-browser-dynamic";
import {AppModule} from "../../app/app.module";

platformBrowserDynamic()
    .bootstrapModule(AppModule, {
        preserveWhitespaces: false
    })
    .catch(err => console.error(err));
```

It seems since `1.8.0-rc.4` plugin built incorrect import of `AppModule` while transforming `main.ts` code, because I receive an build error: `ERROR in ./src/platform/browser/main.ts Module not found: Error: Can't resolve './../../app/app.module.ts.ngfactory' `. The import must be `./../../app/app.module.ngfactory`. Reproduces in last `1.8.0-rc.6`

This error does not occurs in `1.8.0-rc.3`

**Comment by filipesilva** [comment]
You shouldn't have the file extention in the entry module. Can you try this instead?
```
entryModule: helpers.root('src/app/app.module#AppModule')
```

It might have been working before but that wasn't intended.

**Comment by bukharin** [comment]
@filipesilva thank you, it helps
