### ISSUE TITLE
Add Webpack Monitor

### ISSUE THREAD

**Issue by k3nsei** [angular/angular-cli#8239]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

Support for [webpackmonitor](https://github.com/webpackmonitor/webpackmonitor)

### Mention any other details that might be useful.

https://github.com/webpackmonitor/webpackmonitor
"Capture relevant statistics on your production builds, and an interactive analysis tool that helps developers better understand bundle composition and identify and prioritize optimization strategies."

**Comment by mgechev** [comment]
Let us keep this outside of the CLI for now. I'd recommend you to extend your build with `ngx-build-plus` so you can take advantage of this feature.
