### ISSUE TITLE
TypeError when running angular-cli getting started

### ISSUE THREAD

**Issue by octodevelopers** [angular/angular-cli#8242]
Hi,

I've tried to run the getting started angular-cli on an offline env (without internet access)
and got the error: 

> Uncaught TypeError: useValue, useFactory, data is not iterable.

any idea what is the cause? (the project was created by using Webstorm 2017.2 AngularCLI new project)

Thanks!

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
