### ISSUE TITLE
`Angular4 Router`  - Routing is changing due to default behavior of Anchor tag href="#"

### ISSUE THREAD

**Issue by Eashwarswamy** [angular/angular-cli#8246]
### Bug Report or Feature Request (mark with an `x`)
`Angular4 Router`  - Routing is changing due to default behavior of Anchor tag href="#"

`PreventDefault` for Anchor tag

### Versions.

@angular/cli: 1.3.2
node: 6.11.0
os: win32 x64
@angular/animations: 4.4.2
@angular/common: 4.4.2
@angular/compiler: 4.4.2
@angular/core: 4.4.2
@angular/forms: 4.4.2
@angular/http: 4.4.2
@angular/platform-browser: 4.4.2
@angular/platform-browser-dynamic: 4.4.2
@angular/router: 4.4.2
@angular/cli: 1.3.2
@angular/compiler-cli: 4.4.2
@angular/language-service: 4.4.2

### Repro steps.

I am using the PrimeNg components or templates for project development.

PrimeNg Calendar component creates the **anchor** which has the href="#", when I click on the anchor tag, URL path is getting changed with the "#" .

This Behavior is conflicting with the Angular router.

### The log given by the failure.
No Log

### Desired functionality.
Default behavior should not change the router mechanism.

Note : I am  sure not this is actually issue with the routing or We have to handle the preventDeafult scenario for Anchor tag,

Below is the sample Routing mechanism.

"
const routes: Routes = [
    {
        path : "",
        children :[
            { path: '', component: SysPerfTabComponent},
            { path: 'SystemPerf', component: SysPerfTabComponent },
              .....
              .....
              .....
              .....

            { path: 'DeployHist', component: DeployHistTabComponent },
            { path: '**', redirectTo: '' }
            
        ]
    }
   
   ];
"

Is there way we can solve this? 

Thanks,
Eashwar

**Comment by smoke** [comment]
@Eashwarswamy I don't think https://github.com/angular/angular-cli has anything to do with this issue, you should rather fill it in https://github.com/primefaces/primeng project or if you think this is `Angular4 Router` issue - then take it to the https://github.com/angular/angular

**Comment by filipesilva** [comment]
I agree with @smoke, this doesn't seem to be a Angular CLI issue or feature request. I think his answer covers the places where you should report this issue.
