### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by manvfx** [angular/angular-cli#8248]
TypeError: Cannot read property 'name' of undefined
    at http://localhost:3000/app/app.js:16923:53
    at Array.map (<anonymous>)
    at http://localhost:3000/app/app.js:16921:36
    at Array.map (<anonymous>)
    at Cubes.getJoins (http://localhost:3000/app/app.js:16911:46)
    at Cubes.loadJoinDetails (http://localhost:3000/app/app.js:16740:46)
    at Cubes.renderTree (http://localhost:3000/app/app.js:16736:15)
    at new Cubes (http://localhost:3000/app/app.js:16654:19)
    at Object.instantiate (http://localhost:3000/bower_components/angular/angular.js:4786:14)
    at $controller (http://localhost:3000/bower_components/angular/angular.js:10607:28) <div ui-view="" class="frame ng-cloak ng-scope">

**Comment by manvfx** [comment]
my error is comment

private getJoins(): JoinModel[] {
        return Object.keys(this.tree.nodes).map((key, index, nodes_keys) => {
            key = <any>parseInt(key);
            var item = <any>{
                index: index,
                table: this.tree.nodes[key],
            };
            var join = _.find(_.values<JoinModel>(this.tree.edges), { right_index: key });
            if (join) {
                item.parent = nodes_keys.indexOf(join.left_index.toString());
                item.type = join.type;

                item.on = join.on.map(expression => {  
                    //my error
                    return {left: expression.left.name ,right: expression.right.name};
                    
                });
            }
            return item;
        });
    }

**Comment by filipesilva** [comment]
I think you're having some weird errors and can't debug it, and so, understandably, you're frustrated. But this is a tracker for bugs and feature requests. If we can we also try to help with support requests. We're very lucky to have awesome community members that also spend time trying to help people here in the issue tracker.

But we can't really help much at all if you don't fill in the issue template. I read your issue and have no idea what's going wrong and how to help you. And when other users search the issue tracker and see your issue, it also doesn't help them.

So I think the best thing to do is to close this issue, and ask you to open a new one. In that new one please fill in the issue template and give us an idea of what's happening and how to reproduce it. That way we'll have a chance to help you.

**Comment by thahirakram** [comment]
donno how to handle this error.
