### ISSUE TITLE
Unable to import service from module (basic functionality)

### ISSUE THREAD

**Issue by mockuniverse** [angular/angular-cli#8251]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

node 6.11 and npm 5.3.0 
@angular/cli: 1.4.9
node: 6.11.4
os: darwin x64

### Repro steps.

Create an NgModule and export a service from "providers" either NgModule or forRoot variety. 

Try to use the provided service and you cannot. You have to path to the service file (say in the node_modules folder) .  I assume that the NgModule allows consuming applications to use the components, filters but also services provided by the module. 

`import { MyService } from 'MyModule' // how is this supposed to work MyService is not resolved? `

### Desired functionality.

The import statement works.

**Comment by filipesilva** [comment]
Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
