### ISSUE TITLE
Bug: typings.d.ts conflicts with nodejs typings

### ISSUE THREAD

**Issue by wardbell** [angular/angular-cli#826]
The [`typings.d.ts` file](https://github.com/angular/angular-cli/blob/master/addon/ng2/blueprints/ng2/files/__path__/typings.d.ts) declares `module.id`

    declare var module: { id: string };

This declaration conflicts with the richer declarations for nodejs which are also essential for development with webpack rather than systemjs (see [Intro to Webpack](https://angular.io/docs/ts/latest/guide/webpack.html) )

We should delete the `typings.d.ts` and make the following line in `typings.json`

    "node": "registry:dt/node#4.0.0+20160509154515"

work for _all user agents_ and not just for mobile.

One might argue that pulling in the _entire nodejs set of typings_ is an over commitment. It may be possible to rewrite our `module` declaration so that it exactly matches the node declaration. We'd have to be sure that TypeScript remains happy with duplicate but identical declarations.

**Comment by filipesilva** [comment]
Issue made obsolete by #1455.
