### ISSUE TITLE
Code coverage remap broken in 1.5 RC 8 (+release?)

### ISSUE THREAD

**Issue by dinvlad** [angular/angular-cli#8268]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
After switching from 1.4.9 to 1.5 RC 8, the project is built and tested successfully, however test coverage has lowered _significantly_ (from 95% due to #5526 to just over 80% in this case).

The coverage report now shows a majority of TS imports as uncovered code, and when I hover over HTML reports the explanations are "if/else path is not taken".

Seems to me like a potential problem with how TS modules are now included in the code, and/or how remap-Istanbul works. Not sure it's the upstream problem though, since this behavior only changed between Angular CLI versions (all of the other package versions stayed the same).

Another possibility, of course, is that these errors indicate an underlying problem with my code, where I need to add more tests to cover those imports. However, even then the error messages are cryptic, and it is not clear how to address them:

![image](https://user-images.githubusercontent.com/137337/32253803-3abdab6e-be73-11e7-96ca-a97eab466e3e.png)

_In fact, there are other bizarre "if/else" errors that seem **completely out of place**, which point to a problem with remapping:_

![image](https://user-images.githubusercontent.com/137337/32254681-be572bb2-be78-11e7-88a1-dc7e19b40f0c.png)

### Versions.

```
OS: Ubuntu 14.04.5 LTS
Angular CLI: 1.5.0-rc.8
Node: 7.10.0
OS: linux x64
Angular: 5.0.0-rc.9
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.0-rc.8
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.31
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.8
@schematics/angular: 0.0.49
typescript-fsa: 2.5.0
typescript: 2.6.1
webpack: 3.8.1
```
`tsconfig` files are verbatim copies from `ng new`, except for `strictNullChecks`, `noUnusedLocals` and `noUnusedParameters` flags, none of which seem to affect this behavior.

Downgrading to `1.4.9` fixes the problem, but then I cannot build the project with AOT, because `Angular 5+ requires at least Angular CLI 1.5+`

### Repro steps.

Not sure about a minimal repro - I've tried creating a new project and import a service, but that's green. In a more complex project though, the symptoms are apparent: https://codecov.io/gh/cumulous/web/src/master/src/app/app.module.ts

### Desired functionality.

Imports are not reported negatively in test coverage.

**Comment by jnolles** [comment]
It is also broken in the 1.5 final version with Angular 5.0.0. It was working perfectly with cli 1.4.9

The generated lcov / html reports do not match the correct line/character positions in the *.ts files.

**Comment by dinvlad** [comment]
Hmm, today I made a clean install of the release (5.0.0 and 1.5) and downgraded TypeScript to 2.4, due to the new (and helpful!) warning. Now the coverage is perfect - it even includes previously uncovered constructor lines from #5526.

So I think this may have been the TypeScript issue. @jnolles, could you try downgrading yours too if not already, and let us know if the issue is solved. I'll keep it open for now, just in case.

**Comment by dinvlad** [comment]
Even weirder, I've upgraded back to TS 2.6 and it works still. With that, it really appears like the release versions have solved this issue (at least for me). Will keep TS at 2.4 just in case though. @jnolles does it work for you too if you clean-install all packages?

**Comment by jnolles** [comment]
@dinvlad i did the following, and i still have the same problem:

- deleted node-modules and package-lock.json
- updated package.json to match how cli 1.5 creates a new project
- deleted all global packages, just to be sure
- replaced my karma.conf.js with a clean one from cli 1.5
- did npm install again

This is a part of the coverage report:
![afbeelding](https://user-images.githubusercontent.com/19947266/32364825-6c7d0216-c077-11e7-9b2c-db4a16cfef30.png)

part of my package.json:
```
"scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.js",
    "build": "ng build",
    "build:prod": "ng build --prod",
    "test": "ng test --sourcemaps=false --environment=unittest --browsers=Chrome",
    "test-coverage": "ng test --sourcemaps=false --environment=unittest --watch=false --code-coverage --browsers=Chrome",
    "test-coverage-headless": "ng test --sourcemaps=false --environment=unittest --watch=false --code-coverage --browsers=PhantomJS --reporters=progress,junit",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
    "bootstrap": "^4.0.0-beta",
    "fast-json-patch": "^2.0.5",
    "font-awesome": "^4.7.0",
    "lodash": "^4.17.4",
    "oidc-client": "^1.4.1"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/lodash": "^4.14.80",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-reporter": "^1.2.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
```

**Comment by jnolles** [comment]
@dinvlad okeeeey, i found it. Deleted '--sourcemaps=false' from the npm script, and now it works perfectly.

```
"scripts": {
    ....
    "test": "ng test --environment=unittest --browsers=Chrome",
    "test-coverage": "ng test --environment=unittest --watch=false --code-coverage --browsers=Chrome",
    "test-coverage-headless": "ng test --environment=unittest --watch=false --code-coverage --browsers=PhantomJS --reporters=progress,junit",
    ....
  },
```

**Comment by filipesilva** [comment]
I'm closing this one since it seems the issue itself was solved, but would appreciate if people that are still having code coverage problems posted on https://github.com/angular/angular-cli/issues/5526.
