### ISSUE TITLE
[Angular 4] Loading page low ( more 10' ) when reload page and compiler ( about 3 - 5' )

### ISSUE THREAD

**Issue by chauledev5697** [angular/angular-cli#8269]
![untitled](https://user-images.githubusercontent.com/32742676/32260263-37652394-bef9-11e7-8a1e-14d04690dd00.png)
![untitled](https://user-images.githubusercontent.com/32742676/32260294-766d0fb6-bef9-11e7-8fd7-b049baf83f5a.png)

**Comment by toan-nguyen-extra** [comment]
@filipesilva please support him. tks

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
