### ISSUE TITLE
ng serve -prod: application not loaded, but no errors logged in console

### ISSUE THREAD

**Issue by theimdal** [angular/angular-cli#827]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7.

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

angular-cli: 1.0.0-beta.1
node: 5.11.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Created an application using the CLI, then moved my existing ng2 application into the new project. I'm using a couple of 3rd party libs, and also the deprecated router.

Here is my system.config.ts:

/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map: any = {
  'moment':                     'vendor/moment/moment.js',
  'primeng':                    'vendor/primeng',
  'underscore':                 'vendor/underscore/underscore.js'
};

/** User packages configuration. */
const packages: any = {
  'primeng': {
    defaultExtension: 'js'
  }
};

////////////////////////////////////////////////////////////////////////////////////////////////
/***********************************************************************************************
 * Everything underneath this line is managed by the CLI.
 **********************************************************************************************/
const barrels: string[] = [
  // Angular specific barrels.
  '@angular/core',
  '@angular/common',
  '@angular/compiler',
  '@angular/http',
  '@angular/router',
  '@angular/platform-browser',
  '@angular/platform-browser-dynamic',
  '@angular/router-deprecated',

  // Thirdparty barrels.
  'rxjs',

  // App specific barrels.
  'app',
  'app/shared',
  /** @cli-barrel */
];

const cliSystemConfigPackages: any = {};
barrels.forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };
});

/** Type declaration for ambient System. */
declare var System: any;

// Apply the CLI SystemJS configuration.
System.config({
  map: {
    '@angular': 'vendor/@angular',
    'rxjs': 'vendor/rxjs',
    'main': 'main.js'
  },
  packages: cliSystemConfigPackages
});

// Apply the user's configuration.
System.config({ map, packages });

**And this works fine when serving the application in development mode!**

4. The log given by the failure. Normally this include a stack trace and some
   more information.

When building the application for production and serving it, it is stuck in "Loading...", and there is no error logged in the console. As far as i'm able to debug, I see that the application is able to run system.import('main') and that systemjs is trying to import main, but after that I'm not able to make sense of what happens.

5. Mention any other details that might be useful.

This is the output after running serve -prod:

$ ng serve -prod
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 22085ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
BundlePlugin                                  | 12381ms
Funnel                                             | 4792ms
vendor                                             | 2007ms
BroccoliTypeScriptCompiler          | 1800ms

Slowest Trees (cumulative)           | Total (avg)
----------------------------------------------+---------------------
BundlePlugin (1)                              | 12381ms
Funnel (10)                                       | 5561ms (556 ms)
vendor (1)                                         | 2007ms
BroccoliTypeScriptCompiler (1)      | 1800ms

I have also tried "build -prod" and serving the dist folder in lite-server, but with the same result.

I see that this is very vague, but I'm not sure what information is needed to solve this. I will try to dissect my own application to see what I need to exclude to get it running in production mode.

**Comment by JonGaribay** [comment]
try adding moment into the the packages object with a format of cjs in system-config.ts

`"moment": {                
                    main: './moment.js',
                      format: 'cjs'
                }`

**Comment by theimdal** [comment]
Thanks for reply.

Tried your suggestion, but the problem is still there. In development mode it still works after the modification.

**Comment by theimdal** [comment]
After some digging, it seems that these are the lines causing all the trouble:

`import * as moment_ from 'moment';
const moment: moment.MomentStatic = (<any>moment_)['default'] || moment_;`

I followed the recipe from the wiki on how to add moment as a 3rd party library, but maybe something have changed so that the production build is not compatible with that solution.

**Comment by JonGaribay** [comment]
I was able to get moment to work just using 

import * as moment from 'moment';

combined with the package update in my last update.  Before that I was getting the same error.

**Comment by theimdal** [comment]
You were right. It seems that all commonjs libraries must be added to added to the system config like this:

```
/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map: any = {
  'moment':                     'vendor/moment',
  'underscore':                 'vendor/underscore'
};

/** User packages configuration. */
const packages: any = {
  'moment': {
    main: 'moment.js',
    format: 'cjs'
  },
  'underscore': {
    main: 'underscore.js',
    format: 'cjs'
  }
};
```
