### ISSUE TITLE
angular-cli.json schema for dependencies

### ISSUE THREAD

**Issue by feng-xiao** [angular/angular-cli#8270]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

1.4.9

### Desired functionality.

Able to configure app dependencies in one place - .angular-cli.json and group them by library/component (e.g. kendo ui, ng-bootstrap, etc), CLI will automatically configure them in corresponding app files (e.g. ts typings, app.module.ts, styles.scss, etc.)

Below is the config file I used in AngularJS 1.5.x, the build system takes care how to set them up in bundle
![image](https://user-images.githubusercontent.com/3407775/32277970-8d951cd8-beea-11e7-8e97-0b035499c1c6.png)

**Comment by mgechev** [comment]
Would you explain your use case?

**Comment by filipesilva** [comment]
Closing as the original author never got back.
