### ISSUE TITLE
Independent App Bundles

### ISSUE THREAD

**Issue by russoturisto** [angular/angular-cli#8275]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

1.6

### Repro steps.

Feature request

### The log given by the failure.

N/A

### Desired functionality.

We are building a portal application that will eventually have 20+ apps running in it.  We have a requirement to be able to deploy changes to one of the apps without having to re-deploy the entire portal with all of the apps.

Right now when I setup a harness wrapper (app.module.ts) around a lazy loaded module (feature.module.ts) the generated output for feature.module.ts is not compatible with output for the same exact module if I generated as part of another (larger) project.  That is I can't take a lazy loaded feature module compiled in one project and plug it in another project.

Also, my I don't need to dynamically load that module from a different server - we can use server-side logic for that (from the browser's point of view the lazy module bundle can appear to be co-located with the main bundle).  I just need to be able to plugin a module that was build in one project into another project.

So, as far as I understand my only option is to move away from angular-cli and develop manual build infrastructure that uses SystemJS.

It would be great if angular-cli supported building completely independent lazy loaded bundles that could be rebuild independently of the rest of the app.

**Comment by sreemat1993** [comment]
Any workaround for this feature?

**Comment by agamgupta6** [comment]
Hi Team,
Any plans to introduce this feature?

**Comment by mgechev** [comment]
We discussed this issue today during the triage meeting. We've heard similar feature requests in the past and we see the value of this use case. Although we don't think it should be part of the core feature set of the CLI there are different strategies that you can follow to implement it.

For example, having a central registry from which the lazy-routes extract the right path to the separately deployed module is a sample solution.

Another strategy would be to go with Angular Elements, once we improve our story there.
