### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed

### ISSUE THREAD

**Issue by oodboo** [angular/angular-cli#828]
OS: Windows 10
angular-cli: 1.0.0-beta.4
node: 4.4.3
os: win32 x64

Steps:
ng new test-ng
cd test-ng
npm start
:: Error - look what was suggested in #414 and tried:
ng init -- all overwritten
ng build -prod
:: Again same Error 

```
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EPERM: operation not permitted, 
symlink 
'c:\test-ng\tmp\broccoli_type_script_compiler-cache_path-RwtFVBiT.tmp\src\app\environment.js.map' 
-> 'c:\test-ng\tmp\broccoli_type_script_compiler-output_path-pZdkL7rW.tmp\src\app\environment.js.map'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at BroccoliTypeScriptCompiler._outputFile 
(c:\test-ng\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:206:8)
```

Reason I was trying angular-cli is because I am getting 400 requests with @angular RC1 project.

**Comment by vance** [comment]
SUDO (mac) or run CMD as admin (win)?

**Comment by oodboo** [comment]
@vance Yes, that is the one, although I would like to know why they could not do it without elevated privileges in the first place. Why not using local project folder for storing temp folder?!

**Comment by vance** [comment]
I'm finding that since the El Capitan update on OS X, nearly all my node/NPM scripts require elevated privileges, which itself seems like a security risk. I don't want to be SUDOing every single command, who knows what's in there.

**Comment by oodboo** [comment]
@vance I agree 100%, maybe you should raise it as an issue just reference this and I will support you !

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/905 should allow non-admin user usage.
