### ISSUE TITLE
larger bundle size after upgrading to Angular 5.0.0 and uglify/minify not working.

### ISSUE THREAD

**Issue by isaklafleur** [angular/angular-cli#8280]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

ngular CLI: 1.5.0
Node: 8.6.0
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
typescript: 2.4.2
webpack: 3.8.1

### Repro steps.

ng build prod / ng build prod --aot

### Desired functionality.

I read the release note and it was "promised" smaller bundle size. Before upgrading from Angular 4.2.4 to 5.0.0 I created two different prod build one with --aot and another without.

After upgrading to 5.0.0 and angular cli 1.5  I changed to HttpClientModule and HttpClient to get my application to working again. This was the only change I did. I run again ng build prod and ng build prod --aot and I see a larger vendor bundle size. I'm doing something wrong?

[This is the the repo I used to test build size.](https://github.com/isaklafleur/isaklafleur.github.io)

**Also how do I get minfy/ungly working on Angular 5?** I thought this was done automatic on ng build prod.

### Mention any other details that might be useful.

Screenshots.

![Angular 4.2.4 build sizes](https://github.com/isaklafleur/isaklafleur.github.io/raw/master/client/bundle-size-screenshots/Screen%20Shot%20Angular%204.2.4.png)

![Angular 5.0.0 build sizes](https://github.com/isaklafleur/isaklafleur.github.io/raw/master/client/bundle-size-screenshots/Screen%20Shot%205.0.0.png)

**Comment by isaklafleur** [comment]
Adding one thing... What a GREAT product you are building!

**Comment by hansl** [comment]
Hi @isaklafleur,

It seems you're confusing `ng build --prod` with `ng build prod`. Your log uses `ng build prod`, which is not correct. `--prod` is a flag and not a name.

Try `ng build --prod` for the best size possible. `--aot` is on by default in production builds, so you don't need to specify it.

I'm going to close this issue. If this is not resolved by the above, please file a new issue or ping me directly here.

Cheers!

**Comment by isaklafleur** [comment]
Hi @hansl ,
Ah, typo. :-)

Thank you! It solved it!

**Wow 446kb and 112kb gzipped!**

**Comment by renilbabu03** [comment]
The following solution assumes you are serving your dist/ folder using nodejs. Please use the following app.js in root level


    const express = require('express'),http = require('http'),path = require('path'),compression = require('compression');
    
    const app = express();
    
    app.use(express.static(path.join(__dirname, 'dist')));
    app.use(compression()) //compressing dist folder 
    app.get('*', (req, res) => {
      res.sendFile(path.join(__dirname, 'dist/index.html'));
    })
    
    const port = process.env.PORT || '4201';
    app.set('port', port);
    
    const server = http.createServer(app);
    server.listen(port, () => console.log('Running at port ' + port))

Make sure you install dependencies;

    npm install compression --save
    npm install express --save;

Now build the app

    ng build --prod --build-optimizer


> If you want to further compress the build say reduce 300kb(approx)
> from , then follow the below process;

Create a folder called **`vendor`** inside the **`src`** folder and inside vendor folder create a file **`rxjs.ts`**  and paste the below code in it;


    export {Subject} from 'rxjs/Subject';
    export {Observable} from 'rxjs/Observable';
    export {Subscription} from 'rxjs/Subscription';

And then add the follwing in the **`tsconfig.json`** file in your angular-cli application;

    "paths": {
          "rxjs": [
            "./vendor/rxjs.ts"
          ]
        }

 
This will make your build size way too smaller. In my project I reduced the size from 11mb to 1mb.
Hope it helps
