### ISSUE TITLE
Old Version of angular with 1.5.0-rc.8

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/angular-cli#8282]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Angular CLI: 1.5.0-rc.8
Node: 8.6.0
OS: darwin x64
Angular: 4.4.6

I want angular 5.0.0 and up when I create my new project, but everytime I see it gives me a project with Angular 4.4.6!! How should I change it so that angular cli gives me the latest angular version

**Comment by park-brian** [comment]
angular-cli 1.5.0 is out, which uses angular 5.x by default.
