### ISSUE TITLE
Angular Routing Error

### ISSUE THREAD

**Issue by prashSutar** [angular/angular-cli#8285]
I am trying to restrict the child route and want to redirect /login page if user is not logged in. I am implementing canActivateChild[AuthGuard] as following: 

const surveyRoutes: Routes = [
    {
        path: 'survey', component: SurveyListComponent, canActivateChild: [AuthGuard],
        childern: [

            { path: 'add-new', component: AddSurveyComponent },
            { path: ':id/update', component: UpdateSurvryComponent },
        ]
    },
   
];

but getting error as:

Type '{ path: string; component: typeof SurveyListComponent; canActivateChild: typeof AuthGuard[]; chil...' is not assignable to type 'Route'.
    Object literal may only specify known properties, and 'childern' does not exist in type 'Route'.

please comment...

**Comment by deebloo** [comment]
@prabashbala "childern" should be "children"

**Comment by filipesilva** [comment]
Closing as answered by @deebloo, thanks!
