### ISSUE TITLE
Warning order

### ISSUE THREAD

**Issue by jsBrian** [angular/angular-cli#8292]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.
```
@angular/cli: 1.4.5
node: 8.7.0
os: win32 x64
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.4
typescript: 2.2.2
```

### Desired functionality.
This is of course cosmetic, but currently in the log we see the build info first, errors after that and warnings are last.
Doesn't it make more sense to move the warning messages?

So, first show the warnings, after that the build info and errors last. 

That way, if your output screen is small, the warnings can't hide potential errors.

**Comment by m-henderson** [comment]
@filipesilva I'm sure you get this all the time, but could you give me a starting point to fixing this issue ? I am a first time contributor to angular and I dont know my way around. thanks

**Comment by Taha-Di-Nero** [comment]
https://github.com/angular/angular-cli/pull/8745

**Comment by filipesilva** [comment]
@m-henderson sorry I didn't see your comment before, by now there's already a fix up.

@Taha-Di-Nero PR fixes this pretty well, we'll get that one on.

**Comment by filipesilva** [comment]
I think whatever the problem was (that showed build info, errors and then warnings) has been fixed since. 

@Taha-Di-Nero had a PR up but I've closed it since (see https://github.com/angular/angular-cli/pull/8745#issuecomment-356313604).
