### ISSUE TITLE
module.id issue angular 5 compilation process with AngularCompilerPlugin.

### ISSUE THREAD

**Issue by kenneth-igaw** [angular/angular-cli#8295]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

**angular**: `"5.0.0"`
**angular/cli**: `"1.5.0-rc.8"`
**ngtools/webpack**: `"1.8.0-rc.8"`

### Repro steps.

webpack building with `AngularCompilerPlugin`

### The log given by the failure.
```
Error: moduleId should be a string in "{ComponentName}"
```

### Mention any other details that might be useful.

Hello!

I faced an error as follows

```
Error: moduleId should be a string in "{ComponentName}"
```

I changed webpack plugin `AotPlugin` to `AngularCompilerPlugin` for support `angular 5.0.0`

But there's no process about replacement or removement of moduleId in `AngularCompilerPlugin`.

(check the code as follows)

https://github.com/angular/angular-cli/blob/a24e64439291dc4ccab45d7c0a00d2e6b9d83ffe/packages/@ngtools/webpack/src/loader.ts#L654

My `AngularCompilerPlugin` option is as follows

```javascript
new AngularCompilerPlugin ({
    tsConfigPath: rootDir + '/tsconfig.json',
    entryModule: contentDir + '/scripts/app/app.module#AppModule',
    skipCodeGeneration: true
})
```

Thank you.

**Comment by KennethanCeyer** [comment]
I will put a comment with my personal account to check the progress of the issue.

**Comment by mlakmal** [comment]
having same issue. we are using external libs as well as internal code that contain moduleId with relative template paths. and its breaking the app after built from new ngtool/webpack aot compiler

**Comment by kenneth-igaw** [comment]
+Notice
This issue is related #3576
