### ISSUE TITLE
Angular 4 and Prerender.io

### ISSUE THREAD

**Issue by sunderkasajal1203** [angular/angular-cli#8298]
HI

I am trying to use prerender.io for my angular 4 application but i am not able to render my html pages

followed this
 https://github.com/prerender/prerender/tree/chrome and angular.io/guide/quickstart
for prerender and angular 4 respectively

I have set up both things on my local Then through cmd i ran the two applications separately on different ports
localhost:3000 for prerender and
/localhost:4200 for angular

And then i used this url http://localhost:3000/http://localhost:4200 to render the page but it does not seem to load at allIs prerender.io compatible with Angular 2 and Angular 4 or only with AngularJs?

Regards
Sajal

**Comment by deebloo** [comment]
@sunderkasajal1203 this sounds like an issue with prerender.io rather then an issue with the cli itself. I would file an issue with them.

**Comment by filipesilva** [comment]
I'm sorry but like @deebloo said this really is something you should ask prerender.io instead.
