### ISSUE TITLE
generators are creating unexpected `tests` folder

### ISSUE THREAD

**Issue by cironunes** [angular/angular-cli#83]
Steps to reproduce:

1. run `ng generate service foo-bar`
2. run `ls -l` and you'll see the tests folder

Note that this is not happening for the `pipe` generator but for all the others

**Comment by IgorMinar** [comment]
ahhh.. I'm guessing that this is because of how we override the core `ember-cli` test command which scaffolds stuff into the test directory.. just my guess.

**Comment by filipesilva** [comment]
Yeah, just had this as well. I wonder what's so different about the pipe one.... I just did a new `routes` blueprint and I got the extra tests as well.

**Comment by Brocco** [comment]
This was resolved as part of PR #217
