### ISSUE TITLE
ng generate route new-patient results in `No component annotation was found... `

### ISSUE THREAD

**Issue by st-clair-clarke** [angular/angular-cli#830]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. Windows10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
angular-cli: 1.0.0-beta.1
node: 5.10.1
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? No
What change did you do on your code? etc.
ng generate route new-patient

4. The log given by the failure. Normally this include a stack trace and some
   more information.
C:\workspace\epimss\angular2\ts\epimss\src\app]ng generate route new-patient
installing route
installing component
  create src\app\+new-patient\new-patient.component.css
  create src\app\+new-patient\new-patient.component.html
  create src\app\+new-patient\new-patient.component.spec.ts
  create src\app\+new-patient\new-patient.component.ts
  create src\app\+new-patient\index.ts
  create src\app\+new-patient\shared\index.ts
No component annotation was found...

5. Mention any other details that might be useful.
No injection is done anywhere in the application as expected.
Other ng commands work as expected
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Closed in favor of https://github.com/angular/angular-cli/issues/840
