### ISSUE TITLE
serviceWorker = true fails to find @angular/service-worker with yarn workspaces

### ISSUE THREAD

**Issue by spiffyjr** [angular/angular-cli#8300]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Angular CLI 1.5.0
Node: 6.10.3

### Repro steps.

Use yarn workspaces, set serviceWorker = true in angular-cli.json.

### The log given by the failure.

Your project is configured with serviceWorker = true, but @angular/service-worker
is not installed. Run `npm install --save-dev @angular/service-worker`
and try again, or run `ng set apps.0.serviceWorker=false` in your .angular-cli.json.

### Desired functionality.

The error shouldn't be fatal for an undetected service worker module. It should probably be a warning and able to be disabled similar to the TypeScript warnings for incorrect versions.

**Comment by metasong** [comment]
yes, meet this problem too
