### ISSUE TITLE
Cannot build an empty app without bootstrapModule

### ISSUE THREAD

**Issue by tinayuangao** [angular/angular-cli#8309]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Angular CLI: 1.5.0
Node: 6.9.5
OS: linux x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1

### Repro steps.
1. `ng new foo`
2. modify `src/main.ts`. Delete all the content in the file
3. `ng build`

### The log given by the failure.
ERROR in Error: Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
    at Object.resolveEntryModuleFromMain (/usr/local/google/home/tinagao/WebstormProjects/angular/integration/foo/node_modules/@ngtools/webpack/src/entry_resolver.js:121:15)
    at Promise.resolve.then.then (/usr/local/google/home/tinagao/WebstormProjects/angular/integration/foo/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:238:54)

### Desired functionality.
Be able to build an empty app without anything.
The main bundle size after `ng build` should be 0.

**Comment by TheSamsterZA** [comment]
@tinayuangao Why would you want to do this? What is the use case?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases in https://github.com/angular/angular-cli/pull/12559. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
