### ISSUE TITLE
Webpack client can't connect to server if --host 0.0.0.0 configuration is used

### ISSUE THREAD

**Issue by Antony74** [angular/angular-cli#8310]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.9
node: 8.9.0
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4

### Repro steps.
    ng new play
    cd play

Open package.json and change start script like this (two parameters added)

    "start": "ng serve --host 0.0.0.0 --disable-host-check",

Start the server

    npm start

This creates an instance of webpack-dev-server.  Bring up a browser on another device and enter the url for it.  Press F12 to bring up the debugger, and in the network logging note that the webpack sockjs client is failing to connect back to the server because it is using a "localhost" url.

### The log given by the failure.
![angularcli](https://user-images.githubusercontent.com/1577335/32340928-dca2d0f4-bff3-11e7-9e9f-d577966f479f.png)

### Desired functionality.
I'd like the webpack client and server to be able to communicate with each other in this scenario, and be able to use the browser debugger without being distracted by these errors.

I'd like the convenience of a single configuration that works for both with an explicit host name and with 'localhost' when client and server are both on the same computer.  (it's not difficult configure one or the other as desired, but it would be nicer to be able to commit a single configuration to version control and forget about it)

### Mention any other details that might be useful.

I believe this bug was introduced in 035c0941ea129e09459bebea7fb648c05f13a6a7 because it goes away when I manually change this bit of code, or when I downgrade to @angular/cli: 1.0.0 (that commit however did successfully fix a different bug)

**Comment by clydin** [comment]
Please try with the latest stable version (1.5).  It supports automatic live reload host discovery.

**Comment by Antony74** [comment]
Yes, that works thanks :-)

**Comment by Brocco** [comment]
Thanks @clydin!
