### ISSUE TITLE
environment file issue

### ISSUE THREAD

**Issue by foxjazz** [angular/angular-cli#8319]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting

```

### Versions.
@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.3.0
webpack: 3.8.1

### Repro steps.
environment.prodbackup.ts created this in environments

.angulr-cli.json file looks like:
"environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts",
        "prod2": "environments/environment.prodbackup.ts"
      }

running
ng build -prod2 --base-href https://uccx-001-app-prod.statebridgecompany.com:8445/3rdpartygadget/files/testcall/

OR running

ng build --env=prod --base-href https://uccx-001-app-prod.statebridgecompany.com:8445/3rdpartygadget/files/testcall/

both yield code that is not prod types. basically in dist folder it yields this list...
main.bundle.js etc..

It should yield

main.biglongdatakey.bundle.js

**Comment by Brocco** [comment]
You are confusing environment and target.

You're setting your environment to prod[2] but the target by default is dev.

To get your desired output run this...
```
ng build -prod2 --target=production --base-href https://uccx-001-app-prod.statebridgecompany.com:8445/3rdpartygadget/files/testcall/
```
You can read more [here](https://github.com/angular/angular-cli/wiki/build#build-targets-and-environment-files)
