### ISSUE TITLE
tsconfig paths warn

### ISSUE THREAD

**Issue by repertory** [angular/angular-cli#8323]
![tim 20171103143345](https://user-images.githubusercontent.com/15153082/32362496-cf30a64c-c0a4-11e7-92ec-a9cf78f3f913.png)

**Comment by csentis** [comment]
Unfortunately one cannot see the tree on the left hand side. Assuming your shared module is situated under app/shared/shared.module.ts: have you tried replacing the tilde (~) in your Import statement by two dots (..)?

**Comment by clydin** [comment]
Your IDE is most likely only reading and using the top level `tsconfig.json`.  Try adding your path mapping configuration to that file instead.

**Comment by repertory** [comment]
<img width="1440" alt="default" src="https://user-images.githubusercontent.com/15153082/32400257-b27baada-c138-11e7-91a5-4a770156fff0.png">

**Comment by csentis** [comment]
That helps. You might be missing a `baseUrl` as `paths` are [computed relative to baseUrl](http://json.schemastore.org/tsconfig).

**Comment by repertory** [comment]
@csentis Thank you very much!

**Comment by csentis** [comment]
You’re welcome! Remember to close if solved ;-)
