### ISSUE TITLE
update codelyzer to 4.0

### ISSUE THREAD

**Issue by Sibiraj-S** [angular/angular-cli#8324]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.0
Node: 8.9.0
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.
1. ng new my-app --skip-install
2. cd my-app
3. npm install

### The log given by the failure.
```
npm WARN codelyzer@3.2.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@3.2.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
```

### Desired functionality.
Scaffold with codelyzer 4.0.

### Mention any other details that might be useful.
This has been fixed in codelyzer 4.0 
Issue: https://github.com/mgechev/codelyzer/issues/409
Release: https://github.com/mgechev/codelyzer/releases/tag/4.0.0

**Comment by ibqn** [comment]
I hit that issue with 1.5.0 as well

**Comment by Kalki5** [comment]
I got the issue as well

**Comment by Danieliverant** [comment]
same issue, is there any fix?

**Comment by ibqn** [comment]
@Danieliverant the workaround is very trivial, just update `codelyzer` to ~4.0.1 in `package.json` and fix `tslint.json` file

``` diff
-    "codelyzer": "~3.2.0",
+    "codelyzer": "~4.0.1",
```

and
``` diff
-    "directive-class-suffix": true,
-    "invoke-injectable": true
+    "directive-class-suffix": true
```
cp. https://github.com/mgechev/codelyzer/issues/260

**Comment by Sibiraj-S** [comment]
The solution is simple, but it would be nice to be included by default. I think this will be patched in v1.5.1

**Comment by Brocco** [comment]
The fix for this will be in the angular/devkit repo.

The line that will need updated can be found [here](https://github.com/angular/devkit/blob/079f472781f9ce9c48ee5a88d781a35597bc1d6c/packages/schematics/angular/application/files/package.json).

**Comment by rmcc13** [comment]
Hi, it looks like there are already a couple of PRs for this. [Here](https://github.com/angular/devkit/pull/253) and [here](https://github.com/angular/devkit/pull/257)

**Comment by cyrilletuzi** [comment]
Yes, I already did the PR 2 weeks ago, but it's not even reviewed yet. So it's quite funny to see the label "help wanted" here.

@Brocco There is a real problem about supporting the community effort in the CLI, this kind of situation happens very too often (I can give a lot of examples). One of the last Angular weekly meetings notes say " @bradlygreen has details on how to give kudos (in cash!) to external contributors". Well, I don't ask for cash, I think the priority would be first to have someone to manage the github PRs (I don't even mention issues...). That's really frustrating that first, each CLI release comes with this kind of issues (and other ones about generation commands are real problems) and second that when we take time to help, it feels like nobody cares.

**Comment by Sibiraj-S** [comment]
fixed :+1:
