### ISSUE TITLE
Lazy loading broken (Cannot find module) with 1.5.0 and Angular 5

### ISSUE THREAD

**Issue by Ismaestro** [angular/angular-cli#8327]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Angular CLI: 1.5.0
Node: 7.1.0
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.0-rc.8
@angular/flex-layout: 2.0.0-beta.10
@angular/material: 2.0.0-beta.12
@angular-devkit/ build-optimizer: 0.0.32
@angular-devkit/ core: 0.0.20
@angular-devkit/ schematics: 0.0.35
@ngtools/ json-schema: 1.1.0
@ngtools/ webpack: 1.8.0-rc.8
@schematics/ angular: 0.0.49
typescript: 2.4.2
webpack: 3.8.1

### Repro steps.
Clone this repo: https://github.com/Ismaestro/angular4-example-app.git
Checkout the branch called **angular5** 
``` npm i ```
``` npm run test ```

You will see the error.

<img width="1280" alt="screen shot 2017-11-03 at 10 26 02" src="https://user-images.githubusercontent.com/10084945/32367191-92682ac8-c081-11e7-9f48-f47d51e163ad.png">

### The log given by the failure.
```
Chrome 61.0.3163 (Mac OS X 10.12.6) AppComponent should change title meta tag in heroes path FAILED
        Error: Cannot find module './heroes/heroes.module'.
            at http://localhost:9876/_karma_webpack_/webpack:/Users/ismael.ramos.silvan/WebstormProjects/angular4-example-app/src/$_lazy_route_resource lazy:5:1
```

### Desired functionality.

Can lazy loading with the new version of angular.

### Mention any other details that might be useful.

I have to say, I can start the app and everything works fine. Only the tests with karma fails...

**Comment by masalbert** [comment]
<img width="926" alt="captura de pantalla 2017-11-04 a les 19 27 39" src="https://user-images.githubusercontent.com/3390274/32408310-45f5a786-c196-11e7-8a0a-3fca76e81ac8.png">

yes, with ng serve -aot

Project with lazyModule

**Comment by Ismaestro** [comment]
But my error is only passing unit tests... when does that error occurs?
