### ISSUE TITLE
Dynamically load bundles other than through the router. 

### ISSUE THREAD

**Issue by brendanbates89** [angular/angular-cli#8328]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report
- [ ] feature request
```

### Versions.
`"@ngtools/webpack": "1.8.0"`

### Repro steps.
We have setup a dynamic plugin builder.  We're using the following call to build all plugins into their own bundles and later retrieve them dynamically:

        // Use System.import to dynamically setup plugin modules.
        System.import("@plugins/" + type + "/plugin")
            .then(result => {

`@plugins` is a path to the plugin directory in the `tsconfig.json`:

    "paths": {
      ...
      "@plugins/*": ["plugins/*"]
    }

We also have this aliased in the webpack configuration.  This is because it needs to point to a different location when building in development/production:

    resolve: {
        ...
        alias: {
            ...
            "@plugins": getPluginDir(enableAot),

When building in production, AoT building is being used.  This means that webpack should resolve the `.ngfactory.ts` files for each module instead of the typical `.ts` files.  So, in the production build we set it to the AoT `genDir`, which is present in the `tsconfig.json` file:

    "angularCompilerOptions": {
      "genDir": "./build/aot",
      "entryModule": "source/frontend/app/main.module#MainModule"
    }

In `@ngtools/webpack` 1.7.1, this works as intended.  Upgrading to 1.8.0 causes the failure in the log below.

### The log given by the failure.

Some paths were altered to obscure sensitive information.

    ERROR in ./source/frontend/app/common/plugin/plugin-factory.ts
    Module not found: Error: Can't resolve '@plugins' in 'source\frontend\app\common\plugin'
    @ ./source/frontend/app/common/plugin/plugin-factory.ts 19:8-53
    @ ./source/frontend/app/common/plugin/plugin-module.ts
    @ ./build/aot/source/frontend/app/main.module.ngfactory.ts
    @ ./source/frontend/app/entry/main.ts

### Desired functionality.
The webpack build should be able to access the AoT build directory.  It seems as if it cannot resolve the `@plugins` reference.  Perhaps now the genDir is ignored when parsing the `tsconfig.json` file?  Maybe I should not have been able to do this in the first place?

**Comment by brendanbates89** [comment]
Alright, so I decided to commit to upgrading to Angular 5 and work around these issues.  What I've found stems mainly from the issue that `ngc` no longer uses `genDir` and will not longer emit `.ngfactory.ts` files - it goes directly to javascript.  If I dynamically load an AoT module, a dynamic System.import will not work.  So, instead of:

    System.import("@plugins/" + type + "/plugin")

I need to have a factory function that has each type listed out:

    if (type == "first") return System.import("@plugin/first/plugin.ngfactory");
    if (type == "second") return System.import("@plugin/second/plugin.ngfactory");
    if (type == "third") return System.import("@plugin/third/plugin.ngfactory");
    ...

I find it surprising that there is really no *supported* way to dynamically load bundles other than through the router.  I have a lot of hacky code to get this working, but we may have tens of these plugins in the future containing custom code and I would rather not load them all eagerly.  Hopefully there is more support for this in the future with AoT!

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
