### ISSUE TITLE
Build --watch failing on rebuild

### ISSUE THREAD

**Issue by barnatoth** [angular/angular-cli#8332]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Angular CLI: 1.5.0
Node: 8.1.0
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.0
@angular/flex-layout: 2.0.0-beta.10
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.6.1
webpack: 3.8.1
```

### Repro steps.
1. Run in terminal: ```./node_modules/.bin/ng build --aot --env=dev --watch```
2. -> The build is successful
3. Add a new line to any source file
4. The build will throw an error:
```
ERROR in Error: Debug Failure. False expression: Host should not return a redirect source file from `getSourceFile`
    at tryReuseStructureFromOldProgram (/node_modules/typescript/lib/typescript.js:72100:26)
    at Object.createProgram (/node_modules/typescript/lib/typescript.js:71808:34)
    at AngularCompilerProgram._createProgramWithBasicStubs (/node_modules/@angular/compiler-cli/src/transformers/program.js:431:29)
    at /node_modules/@angular/compiler-cli/src/transformers/program.js:144:28
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

### The log given by the failure.
```
ERROR in Error: Debug Failure. False expression: Host should not return a redirect source file from `getSourceFile`
    at tryReuseStructureFromOldProgram (/node_modules/typescript/lib/typescript.js:72100:26)
    at Object.createProgram (/node_modules/typescript/lib/typescript.js:71808:34)
    at AngularCompilerProgram._createProgramWithBasicStubs (/node_modules/@angular/compiler-cli/src/transformers/program.js:431:29)
    at /node_modules/@angular/compiler-cli/src/transformers/program.js:144:28
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

### Desired functionality.
Adding a new line shouldn't break the build

**Comment by thaoula** [comment]
Hi Guys,

I also get this issue on change of source code like fixing an import reference.

I am using ng serve --aot

Regards,
Tarek

**Comment by Hacklone** [comment]
I reverted my typescript version to “<2.5.0” and it’s working fine.

**Comment by Brocco** [comment]
The current version of typescript supported is 2.4.2, please use that version for now. Support for later versions of TypeScript are being looked into.

**Comment by subatomicglue** [comment]
But I have this issue: https://github.com/angular/angular/issues/20095#issuecomment-343062427 which gives errors in typescript 2.4.2.  ERROR is related to `BoundNodeCallbackObservable`... if that rings a bell.

So I am in a catch 22, where nothing works.   Removing `--watch` doesnt improve the outcome for me either...

**Comment by kevinphelps** [comment]
See also #8434. `Typescript@next` (currently `2.7.0-dev.20171216`) is needed to fix other issues as well.

**Comment by DcsMarcRemolt** [comment]
The same error still shows up for current angular 5.2.x and @ngtools/webpack 1.10.1 if I use a TS version != 2.4.2. As Angular 5.2 officially supports TS 2.6 this is now a real bug, please reopen.

**Comment by Mc128k** [comment]
I'm having the same problem after moving an imported .ts file outside the app structure (it acts as a shared module). This works in the first build and fails after a live rebuild.

Using a non-aot developer build seems to work just fine. I can reproduce the issue every time, here's the log:

```
ERROR in Error: Debug Failure. False expression: Host should not return a redirect source file from `getSourceFile`
    at tryReuseStructureFromOldProgram (/.../node_modules/typescript/lib/typescript.js:74285:26)
    at Object.createProgram (/.../node_modules/typescript/lib/typescript.js:73988:34)
    at AngularCompilerProgram._updateProgramWithTypeCheckStubs (/.../node_modules/@angular/compiler-cli/src/transformers/program.js:460:30)
    at /.../node_modules/@angular/compiler-cli/src/transformers/program.js:148:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

This is not critical, but a major nuisance. Any help?

**Comment by kspearrin** [comment]
Same problem here using Typescript 2.6.2, Angular 5.2.x with @ngtools/webpack 1.10.2 (compiler-cli 5.2).

**Comment by denishvachhani** [comment]
Same problem here using Typescript 2.7.2, webpack 3.11.0, Angular 5.2.9

**Comment by coryrylan** [comment]
I just ran into this as well on 6.1.0-rc.0

**Comment by Dunos** [comment]
Can confirm this is still a thing with Angular 6.0.9 and CLI 6.0.8, issue should be reopen

**Comment by glebmachine** [comment]
I've got same error on production build

**Comment by lorado** [comment]
When I run project with JIT compilation - cli can build, and the rebuild on changes. When I compile with AOT - first build succeed, but on change cli can't rebuild, and displays 
```
ERROR in Debug Failure. False expression: Host should not return a redirect source file from `getSourceFile`
ℹ ｢wdm｣: Failed to compile.
```

```
Angular CLI: 6.2.1
Node: 10.1.0
OS: darwin x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.8.1
@angular/cli                      6.2.1
@ngtools/webpack                  6.1.5
@schematics/angular               0.8.1
@schematics/update                0.8.1
rxjs                              6.3.2
typescript                        2.9.2
webpack                           4.9.2
```

**Comment by DcsMarcRemolt** [comment]
Guys, this ticket is closed and dead. The current ticket tracking the problem is https://github.com/angular/angular/issues/22524
