### ISSUE TITLE
angularCompilerOptions isn't honored when coming in from an extended tsconfig

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular-cli#8336]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

`"@ngtools/webpack": "1.8.0"`

### Repro steps.

I have a base tsconfig.json and include that via "extends" in the tsconfig that is put into the configuration object for the `AngularCompilerPlugin`.
I try to configure the `"preserveWhitespaces": false` feature with a `angularCompilerOptions` section.
When I put that section in the base tsconfig, nothing in the output changes. When I put it into the extending tsconfig, the resulting bundle gets the expected shrinkage.

### The log given by the failure.

There's no failure, just no effect.

### Desired functionality.

The Angular 5 release blog post says:
> We’re also updating the way we use tsconfig.json files to follow TypeScript standards more strictly

Properly handling `"extends"` seems to be a gap.

**Comment by blyndcide** [comment]
I also had to put `"angularCompilerOptions": {
        "preserveWhitespaces": false
    }` in tsconfig.app.json to get the option to work.

**Comment by danwulff** [comment]
Same experience for me as well. I had to add the following `preserveWhitespaces` config to both the root `tsconfig.json` and `tsconfig.app.json` in order to witness a file size difference. (I also added to my `tsconfig.spec.json` to ensure that unit tests are identical):
```
"angularCompilerOptions": {
  "preserveWhitespaces": false
},
```

**Comment by vinayakpatil** [comment]
+1

**Comment by clydin** [comment]
This is a limitation of TypeScript, the extends functionality only applies to its own `compilerOptions`.

**Comment by martinsik** [comment]
I just stumbled upon the same thing. I think it's fine if this is TypeScript specific issue but maybe angular-cli could show a warning message when the parent `tsconfig.json` contains options that aren't inherited.

**Comment by listepo-alterpost** [comment]
Hi, any news?

**Comment by clydin** [comment]
As indicated above, this is a TypeScript issue.  If this is important to your project, please consider opening an issue with the TypeScript project.
