### ISSUE TITLE
Are ejected configs incompatible with Continuous Integration?

### ISSUE THREAD

**Issue by darkbasic** [angular/angular-cli#8337]
Angular-cli 1.5.0 fills my `webpack.config.js` with tons of aliases like
```
"rxjs/AsyncSubject": "/home/niko/WebstormProjects/angularcli-meteor/node_modules/rxjs/_esm5/AsyncSubject.js"
```

Obviously the absolute path will not match on CI, while I didn't manage to make relative paths (like `node_modules/rxjs/_esm5/AsyncSubject.js`) work.
What should I do?

**Comment by ivenxu** [comment]
I have the same problem. I'm wondering why only rxjs has this problem but other imports don't.

**Comment by AdrienRedon** [comment]
Same as well. I had to replace every absolute path for rxjs with 
```javascript
path.resolve(__dirname, 'relative/path')

**Comment by darkbasic** [comment]
The same is true if you eject it with the `--prod` flag:
```
    new LicenseWebpackPlugin({
      "licenseFilenames": [
        "LICENSE",
        "LICENSE.md",
        "LICENSE.txt",
        "license",
        "license.md",
        "license.txt"
      ],
      "perChunkOutput": false,
      "outputTemplate": "/home/niko/WebstormProjects/angularcli-meteor/node_modules/license-webpack-plugin/output.template.ejs",
```

As you can see the `outputTemplate` of the `LicenseWebpackPlugin` has absolute paths too.

**Comment by darkbasic** [comment]
@hansl should I open a separate bug report for `LicenseWebpackPlugin`?
We still have absolute paths in the prod config...
Do you have any ETA for a release including that fix?
