### ISSUE TITLE
ng new myproject not working error: Invalid rule or source result...

### ISSUE THREAD

**Issue by steven-fernandez** [angular/angular-cli#8338]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.4.9

### Repro steps.
When I try to create a new project:

ng new myproject

Error:

Error: Invalid rule or source result: Instance of class FileSystemCreateTree.
Invalid rule or source result: Instance of class FileSystemCreateTree.

### The log given by the failure.
Error: Invalid rule or source result: Instance of class FileSystemCreateTree.
Invalid rule or source result: Instance of class FileSystemCreateTree.

### Desired functionality.
Project should be generated

### Mention any other details that might be useful.
Mac OS Sierra

**Comment by Brocco** [comment]
I believe this has been resolved via a release of schematics.

Can you please reinstall your dependencies and re-test?

**Comment by steven-fernandez** [comment]
Working! Thanks! :)
