### ISSUE TITLE
I am unable to install agular/cli

### ISSUE THREAD

**Issue by Ramesh-S** [angular/angular-cli#8341]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'angular/cli' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose npm-session 74732dff0932274f
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for github:angular/cli Error while executing:
7 silly fetchPackageMetaData C:\Program Files\Git\bin\git.EXE ls-remote -h -t ssh://git@github.com/angular/cli.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData Host key verification failed.
7 silly fetchPackageMetaData fatal: Could not read from remote repository.
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData Please make sure you have the correct access rights
7 silly fetchPackageMetaData and the repository exists.
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData exited with error code: 128
8 verbose stack Error: exited with error code: 128
8 verbose stack     at ChildProcess.onexit (C:\Program Files\nodejs\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
8 verbose stack     at emitTwo (events.js:126:13)
8 verbose stack     at ChildProcess.emit (events.js:214:7)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
9 verbose cwd C:\Users\Ravi Teja
10 verbose Windows_NT 6.1.7601
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular/cli"
12 verbose node v8.9.0
13 verbose npm  v5.5.1
14 error Error while executing:
14 error C:\Program Files\Git\bin\git.EXE ls-remote -h -t ssh://git@github.com/angular/cli.git
14 error
14 error Host key verification failed.
14 error fatal: Could not read from remote repository.
14 error
14 error Please make sure you have the correct access rights
14 error and the repository exists.
14 error
14 error exited with error code: 128
15 verbose exit [ 1, true ]

**Comment by clydin** [comment]
Please try `npm i -g @angular/cli`. (note the `@`)

**Comment by Ramesh-S** [comment]
Thank you, It worked fine.

But after installing.

When i was trying to check the version with the command : ng -v or ng --version.

Result : ng is not as an internal or external command, operable program or batch file.

**Comment by RicardoVaranda** [comment]
Hi @Ramesh-S,

Could you please try the following commands:

```
npm uninstall -g angular-cli
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli
```

Afterwards could you try:

```
ng -v
```

If you get any error logs could you please report back.

**Comment by pkonieczniak** [comment]
@Ramesh-S 
I had the same problem with missing ng command.

It seems , it is problem with npm configuration.
Please check the following solution from stackoverflow :)

https://stackoverflow.com/a/44622211/6923234

**Comment by Brocco** [comment]
This is an issue related to npm, not the CLI itself. Closing this issue.
