### ISSUE TITLE
ng: command not found on Mac

### ISSUE THREAD

**Issue by gellban** [angular/angular-cli#8343]
if you type:
 npm install -g @angular/cli
ng new <appname>
you will get the error: 
ng: command not found
because you do not have access to the global directory of npm

solution:
just use sudo
sudo npm install -g @angular/cli
ng new <appname>

**Comment by istiti** [comment]
Imo you should close this yourself not an issue

**Comment by SupradaChethan** [comment]
Hi gellban,

I'm trying this: sudo npm install -g @angular/cli but it's taking so much of time to install.
is that normal?

Thanks,
Suprada

**Comment by gellban** [comment]
it takes less than 20 mins like 5 mins.

**Comment by eddieedease** [comment]
Adjusting npm permissions:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by SupradaChethan** [comment]
Hi eddie: thanks for the tip. It worked.
As I didn't had permissions to /usr/local/bin/, /usr/local/lib, /usr/local/share when I ran command: **sudo npm install -g @angular/cli**, it was continuously running in loop. it's fixed now after granting access to those files.
@gaballan: thanks quick reply :)

**Comment by gellban** [comment]
I am happy that I find something to help ppl.

**Comment by Brocco** [comment]
This is an issue related to npm, not the CLI itself. Closing this issue.

**Comment by texyz** [comment]
Thanks

**Comment by Prageeth92** [comment]
not work

**Comment by Prageeth92** [comment]
qs-MacBook-Pro:angular_test Prageeth$ sudo npm install -g @angular/cli
Password:
/Users/q/.npm-packages/bin/ng -> /Users/q/.npm-packages/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@6.0.8 postinstall /Users/q/.npm-packages/lib/node_modules/@angular/cli
> node ./bin/ng-update-message.js

+ @angular/cli@6.0.8
updated 1 package in 13.024s
qs-MacBook-Pro:angular_test Prageeth$ ng new ng6 --style=scss --routing
-bash: ng: command not found
qs-MacBook-Pro:angular_test Prageeth$ ng new
-bash: ng: command not found
qs-MacBook-Pro:angular_test Prageeth$

**Comment by AltRoot17** [comment]
Try to use` sudu npm install  `

`sudo npm install -g @angular/cli `

**Comment by Prageeth92** [comment]
Thank you,

Best Regards

**Comment by Felicity05** [comment]
I'm having the same issue. I used sudo and still getting "command not found". I'm using MacOS 10.13.4, and the npm version is 5.5.1. Any help would be highly appreciated.
Thanks

**Comment by Prageeth92** [comment]
Noted.

Best Regards
Prageeth Rukmal

**Comment by nkdas75** [comment]
Had the same issue. This is a path problem. Fixed by adding 'ng' to the path in .bash_profile file /Users/xxxx/.node_modules_global/bin

**Comment by Felicity05** [comment]
Thank you all I resolved the issue by adding ng to the path

**Comment by ychalodiya** [comment]
Yogesh:~ yogi$ npm -v
6.4.1
Yogesh:~ yogi$ node -v
v8.12.0
Yogesh:~ yogi$ ng -v
-bash: ng: command not found

facing this error in mac high sierra.

**Comment by ldvicedo** [comment]
having the same problem today on mac os sierra 10.12.6. please help

LDVICEDO:~ ldvicedo$ npm install -g @angular/cli
/Users/ldvicedo/.npm-global/bin/ng -> /Users/ldvicedo/.npm-global/lib/node_modules/@angular/cli/bin/ng

> fsevents@1.2.4 install /Users/ldvicedo/.npm-global/lib/node_modules/@angular/cli/node_modules/fsevents
> node install

[fsevents] Success: "/Users/ldvicedo/.npm-global/lib/node_modules/@angular/cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
+ @angular/cli@7.0.2
added 336 packages from 222 contributors in 44.991s
LDVICEDO:~ ldvicedo$ ng -v
-bash: ng: command not found

**Comment by ldvicedo** [comment]
> Yogesh:~ yogi$ npm -v
> 6.4.1
> Yogesh:~ yogi$ node -v
> v8.12.0
> Yogesh:~ yogi$ ng -v
> -bash: ng: command not found
> 
> facing this error in mac high sierra.

does your problem resolve?

**Comment by ldvicedo** [comment]
> having the same problem today on mac os sierra 10.12.6. please help

solved my problem by following **shanemac10** guide below:

https://github.com/angular/angular-cli/issues/5021

after that if you run ng help, there is a text saying "error please delete angular.json" i deleted the .angular.json and run the ng help and it works

:)

**Comment by phemie** [comment]
> Thank you all I resolved the issue by adding ng to the path
> […](#)
> Sent from my iPhone
> On Oct 14, 2018, at 2:54 AM, Naba K Das ***@***.***> wrote: Had the same issue. This is a path problem. Fixed by adding 'ng' to the path in .bash_profile file /Users/xxxx/.node_modules_global/bin — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Hello, please how did you add the ng path. I have the same system spec and having the same issue atm

**Comment by dineshnisshanka** [comment]
These are the codes i used

```
sudo npm uninstall -g angular-cli
sudo npm uninstall -g @angular/cli
sudo npm cache clean --force
npm install -g @angular/cli
alias ng="~/node_modules/@angular/cli/bin/ng"
```
for check
`ng --version`

**Comment by gellban** [comment]
Thank you!
Many developers have this issue when they have old version of angular. Google should solve this issue or add steps in installation to be followed.
