### ISSUE TITLE
ng build --no-aot --prod does not work in angular-cli 1.5

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#8345]
### Problem.

Аfter the upgrade to angular-cli 1.5 does not work JIT-mode.
https://github.com/splincode/angular5-demo

AOT: 

```bash
ng build --aot --prod
cd dist/
http-server
# open in browser http://127.0.0.1:8081
```
It's work

JIT: 

```bash
ng build --no-aot --prod
cd dist/
http-server
# open in browser http://127.0.0.1:8081
```

```text
main.c90f048daaa26da75376.bundle.js:1 Uncaught Error: Unexpected value 't' imported by the module 't'. Please add a @NgModule annotation.
    at p (main.c90f048daaa26da75376.bundle.js:1)
    at main.c90f048daaa26da75376.bundle.js:1
    at Array.forEach (<anonymous>)
    at t.getNgModuleMetadata (main.c90f048daaa26da75376.bundle.js:1)
    at t._loadModules (main.c90f048daaa26da75376.bundle.js:1)
    at t._compileModuleAndComponents (main.c90f048daaa26da75376.bundle.js:1)
    at t.compileModuleAsync (main.c90f048daaa26da75376.bundle.js:1)
    at t.compileModuleAsync (main.c90f048daaa26da75376.bundle.js:1)
    at t.LMZF.t.bootstrapModule (main.c90f048daaa26da75376.bundle.js:1)
    at Object.cDNt (main.c90f048daaa26da75376.bundle.js:1)
```

### Versions.
```text
Angular CLI: 1.5.0
Node: 9.0.0
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

What am I doing wrong?

**Comment by trotyl** [comment]
The problem is buildOptimizer still enabled in JIT for `--prod`, try `ng build --prod --aot=false --build-optimizer=false` could solve it.

Likely to be a valid BUG in https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/models/webpack-config.ts#L124.

**Comment by KhizerRehan** [comment]
When i run **"ng build"** it successfully builds but when i tried to `ng build --prod` version it fails can any one help to solve this problem. @filipesilva @Brocco  
![1](https://user-images.githubusercontent.com/17727069/32865072-61cf6104-ca83-11e7-8389-44c4c276e33f.png)
![2](https://user-images.githubusercontent.com/17727069/32865074-62034e74-ca83-11e7-9101-4eb3a7c30756.png)
![3](https://user-images.githubusercontent.com/17727069/32865075-62384dc2-ca83-11e7-995b-87fa5778c619.png)

**Comment by tarasbobak** [comment]
I am facing the same issue as reported.
--build-optimizer=false helped, but it should be turned off by default when aot is set to false.
Thank you @trotyl
