### ISSUE TITLE
cannot work with IE10

### ISSUE THREAD

**Issue by ringrid** [angular/angular-cli#8348]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Angular CLI: 1.5.0
Node: 8.7.0
OS: win32 x64
my os is Windows 10

### Repro steps.
I created new project by 'ng new myApp', and uncomment these lines in polyfills.ts:
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

and run 'ng build -prod'. It's an empty project without other code.

I used IE11 to run it, It's ok,. But in IE10 the console error is:
```
SCRIPT5011: 不能执行已释放 Script 的代码
polyfills.bf104055021a1b5ed041.bundle.js (1,49468)
```

**Comment by finalxcode** [comment]
@ringrid  have you resolve it?

**Comment by ringrid** [comment]
@finalxcode No，But it cannot be reproduced in newer version cli@1.5.4

**Comment by xieyunhai** [comment]
https://stackoverflow.com/questions/46449861/angular-cli-angular-4-ie10-doesnt-work

**Comment by ringrid** [comment]
@xieyunhai Thanks for your help.
