### ISSUE TITLE
Generated e2e testing files does match the style guide (Style 02-11)

### ISSUE THREAD

**Issue by phillipgreenii** [angular/angular-cli#835]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
all

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
master

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng new

4. The log given by the failure. Normally this include a stack trace and some
   more information.
nothing special

5. Mention any other details that might be useful.
Generate files have "e2e" suffix when they should have "e2e-spec" suffix

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/1013
