### ISSUE TITLE
NG New not working on 1.5.0

### ISSUE THREAD

**Issue by monnierant** [angular/angular-cli#8350]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Windows 10
Angular CLI: 1.5.0
Node: 8.9.0
OS: win32 x64
Angular:
...
node --version
v8.9.0
 npm --version
5.5.1

### Repro steps.

// open a powershell terminal as administrator
> ng new MyProject

### Mention any other details that might be useful.
I have try in admin and not in admin > Same issue

I have try to reinstall @angular/cli > Same issue

  create MyTest/e2e/app.e2e-spec.ts (289 bytes)
  create MyTest/e2e/app.po.ts (208 bytes)
  create MyTest/e2e/tsconfig.e2e.json (235 bytes)
  create MyTest/karma.conf.js (923 bytes)
  create MyTest/package.json (1312 bytes)
  create MyTest/protractor.conf.js (722 bytes)
  create MyTest/README.md (1022 bytes)
  create MyTest/tsconfig.json (363 bytes)
  create MyTest/tslint.json (2985 bytes)
  create MyTest/.angular-cli.json (1242 bytes)
  create MyTest/.editorconfig (245 bytes)
  create MyTest/.gitignore (516 bytes)
  create MyTest/src/assets/.gitkeep (0 bytes)
  create MyTest/src/environments/environment.prod.ts (51 bytes)
  create MyTest/src/environments/environment.ts (387 bytes)
  create MyTest/src/favicon.ico (5430 bytes)
  create MyTest/src/index.html (293 bytes)
  create MyTest/src/main.ts (370 bytes)
  create MyTest/src/polyfills.ts (2667 bytes)
  create MyTest/src/styles.css (80 bytes)
  create MyTest/src/test.ts (1085 bytes)
  create MyTest/src/tsconfig.app.json (211 bytes)
  create MyTest/src/tsconfig.spec.json (304 bytes)
  create MyTest/src/typings.d.ts (104 bytes)
  create MyTest/src/app/app.module.ts (314 bytes)
  create MyTest/src/app/app.component.html (1120 bytes)
  create MyTest/src/app/app.component.spec.ts (986 bytes)
  create MyTest/src/app/app.component.ts (207 bytes)
  create MyTest/src/app/app.component.css (0 bytes)
Installing packages for tooling via npm.
npm ERR! path D:\Company\MonnierAnt\Websites\MyTest\node_modules\fsevents\node_modules\getpass\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall lstat
npm ERR! Error: EPERM: operation not permitted, lstat 'D:\Company\MonnierAnt\Websites\MyTest\node_modules\fsevents\node_modules\getpass\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, lstat 'D:\Company\MonnierAnt\Websites\MyTest\node_modules\fsevents\node_modules\getpass\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, lstat \'D:\\Company\\MonnierAnt\\Websites\\MyTest\\node_modules\\fsevents\\node_modules\\getpass\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'lstat',
npm ERR!   path: 'D:\\Company\\MonnierAnt\\Websites\\MyTest\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\monnierant\AppData\Roaming\npm-cache\_logs\2017-11-04T19_16_55_582Z-debug.log

Package install failed, see above.
Package install failed, see above.

30957 silly postinstall jasmine-spec-reporter@4.1.1
30958 info lifecycle jasmine-spec-reporter@4.1.1~postinstall: jasmine-spec-reporter@4.1.1
30959 silly postinstall karma@1.7.1
30960 info lifecycle karma@1.7.1~postinstall: karma@1.7.1
30961 silly postinstall karma-chrome-launcher@2.1.1
30962 info lifecycle karma-chrome-launcher@2.1.1~postinstall: karma-chrome-launcher@2.1.1
30963 silly postinstall karma-cli@1.0.1
30964 info lifecycle karma-cli@1.0.1~postinstall: karma-cli@1.0.1
30965 silly postinstall karma-coverage-istanbul-reporter@1.3.0
30966 info lifecycle karma-coverage-istanbul-reporter@1.3.0~postinstall: karma-coverage-istanbul-reporter@1.3.0
30967 silly postinstall karma-jasmine-html-reporter@0.2.2
30968 info lifecycle karma-jasmine-html-reporter@0.2.2~postinstall: karma-jasmine-html-reporter@0.2.2
30969 silly postinstall protractor@5.1.2
30970 info lifecycle protractor@5.1.2~postinstall: protractor@5.1.2
30971 silly postinstall ts-node@3.2.2
30972 info lifecycle ts-node@3.2.2~postinstall: ts-node@3.2.2
30973 silly postinstall tslint@5.7.0
30974 info lifecycle tslint@5.7.0~postinstall: tslint@5.7.0
30975 verbose unlock done using C:\Users\monnierant\AppData\Roaming\npm-cache\_locks\staging-c7168e46c7e7426f.lock for D:\Company\MonnierAnt\Websites\MyTest\node_modules\.staging
30976 verbose stack Error: EPERM: operation not permitted, lstat 'D:\Company\MonnierAnt\Websites\MyTest\node_modules\fsevents\node_modules\getpass\node_modules'
30977 verbose cwd D:\Company\MonnierAnt\Websites\MyTest
30978 verbose Windows_NT 10.0.16299
30979 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--quiet" "install"
30980 verbose node v8.9.0
30981 verbose npm  v5.5.1
30982 error path D:\Company\MonnierAnt\Websites\MyTest\node_modules\fsevents\node_modules\getpass\node_modules
30983 error code EPERM
30984 error errno -4048
30985 error syscall lstat
30986 error Error: EPERM: operation not permitted, lstat 'D:\Company\MonnierAnt\Websites\MyTest\node_modules\fsevents\node_modules\getpass\node_modules'
30986 error  { Error: EPERM: operation not permitted, lstat 'D:\Company\MonnierAnt\Websites\MyTest\node_modules\fsevents\node_modules\getpass\node_modules'
30986 error   stack: 'Error: EPERM: operation not permitted, lstat \'D:\\Company\\MonnierAnt\\Websites\\MyTest\\node_modules\\fsevents\\node_modules\\getpass\\node_modules\'',
30986 error   errno: -4048,
30986 error   code: 'EPERM',
30986 error   syscall: 'lstat',
30986 error   path: 'D:\\Company\\MonnierAnt\\Websites\\MyTest\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }
30987 error Please try running this command again as root/Administrator.
30988 verbose exit [ -4048, true ]

**Comment by steven-fernandez** [comment]
+1

**Comment by clydin** [comment]
The error is an npm/node error involving permissions.  You can skip the package installation step by adding the `--skip-install` option.  However, to use the project, the npm/node issue on your system will need to be troubleshooted.

**Comment by Brocco** [comment]
@monnierant & @steven-fernandez have either of you been able to confirm that steps suggested by @clydin?

**Comment by uglycoyote** [comment]
I was running in to same problem with 
Windows 10, node v8.9.1, npm v5.3.0.,  @angular/cli v 1.5.0

```
npm ERR! path D:\temp\myAppName\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'D:\temp\myAppName\node_modules\fsevents\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'D:\temp\myAppName\node_modules\fsevents\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\temp\\myAppName\\node_modules\\fsevents\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'D:\\temp\\myAppName\\node_modules\\fsevents\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2017-11-15T19_56_23_620Z-debug.log
```

Running ```ng new``` with the ```--skip-install``` option runs quickly and successfully.

A subsequent ```npm install``` within that directory run successfully but with warnings:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

Perhaps it is relevant that the module ```fsevents``` which it's warning about skipping in the ```npm install``` output is the same module that it's getting the EPERM errors for when running the ```ng new``` ?

**Comment by whiplashomega** [comment]
Why is fsevents attempting to install on a windows system? From what I can tell it is an OS X specific library.  Which module is listing it as a dependency?

**Comment by uglycoyote** [comment]
@whiplashomega I can no longer reproduce the problem under @angular/cli version 1.6.3 on Windows.

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
