### ISSUE TITLE
No Options to create a Angular 4 project in ng new

### ISSUE THREAD

**Issue by aravindfz** [angular/angular-cli#8353]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

**Angular CLI: 1.5.0**

### Desired functionality.

An optional flag can be used to create lower versions of Angular projects

**Comment by Brocco** [comment]
Can you please explain the use case?

It is the desire of the team to keep projects up to date with the latest versions hence creating new projects with the latest version.

**Comment by heyyoyo** [comment]
I had to work on an angular 4 project, but with the last version of angular cli, the cli generates only angular app with dependencies for angular 5.

**Comment by amalan-shenll** [comment]
this happends to me also

**Comment by alan-agius4** [comment]
We feel that the latest version of Angular is always the appropriate one for creating new projects.

Kindly see https://github.com/angular/angular-cli/issues/12609#issuecomment-431091537 for more context.
