### ISSUE TITLE
Angular Universal 

### ISSUE THREAD

**Issue by thibaultvanluchene** [angular/angular-cli#8358]
In the wiki story 
https://github.com/angular/angular-cli/wiki/stories-universal-rendering
at step 5 you have to make a webpack config file to compile server.ts, but then nothing is provided about what to do with that webpack config file/how it acutally gets read by webpack, or in simpler words:

How to compile server.ts...

Please provide some information on that.

Also, the link to the Universal Starter project is broken.

**Comment by sheikalthaf** [comment]
check this starter https://github.com/angular/universal-starter

**Comment by Toxicable** [comment]
Down the bottom it has the command `"webpack:server": "webpack --config webpack.server.config.js --progress --colors"`

**Comment by thibaultvanluchene** [comment]
Completely overlooked it. My bad! Thanks.
