### ISSUE TITLE
Uncaught ReferenceError: req is not defined with cli@1.5

### ISSUE THREAD

**Issue by sinedied** [angular/angular-cli#8359]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
Angular CLI: 1.5.0
Node: 7.9.0
OS: darwin x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.0
@angular/flex-layout: 2.0.0-beta.9
@angular/material: 2.0.0-beta.12
@angular/service-worker: 1.0.0-beta.16
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.

1. Clone this repo: https://github.com/ngx-rocket/starter-kit
2. `npm install`
3. `npm run start -- --prod` or `ng serve --prod`

### The log given by the failure.

Build is successful, but app is throwing an error that seems to be due to zone.js polyfill:
```
polyfills.5ae6b10132b7e8411589.bundle.js:1 Uncaught ReferenceError: req is not defined
    at polyfills.5ae6b10132b7e8411589.bundle.js:1
    at polyfills.5ae6b10132b7e8411589.bundle.js:1
    at polyfills.5ae6b10132b7e8411589.bundle.js:1
    at Function.r.__load_patch (polyfills.5ae6b10132b7e8411589.bundle.js:1)
    at polyfills.5ae6b10132b7e8411589.bundle.js:1
    at u (polyfills.5ae6b10132b7e8411589.bundle.js:1)
    at Object.<anonymous> (polyfills.5ae6b10132b7e8411589.bundle.js:1)
    at Object.eFQL (polyfills.5ae6b10132b7e8411589.bundle.js:1)
    at n (inline.f05f710f0631368b608c.bundle.js:1)
    at Object.TU+8 (polyfills.5ae6b10132b7e8411589.bundle.js:1)
```

### Desired functionality.
App does not throw any error.

### Mention any other details that might be useful.
Was working fine with `angular-cli@1.4`

**Comment by MikaAK** [comment]
I am also getting this but not using cli directly just the new `AngularCompilerPlugin`.  Seems the app still functions though.

**Comment by clydin** [comment]
This is actually a bug in uglify-es and looks like the next version should have a fix.
Relevant issue: https://github.com/mishoo/UglifyJS2/issues/2437

**Comment by ericzon** [comment]
Upgrading node.js to latest LTS version, re-installing angular-cli@1.5 & upgrading typescript to 2.6.1 I got rid this anoying error after rebuild my project. Before this, I got unmeet peer dependency on typescript & other angular dependencies.

**Comment by paulogr** [comment]
I got the same error here when upgrading a Angular 4.XX project to use with Angular-CLI 1.5

**Comment by lexcaraig** [comment]
What's the workaround here? :)

**Comment by mrnetforge** [comment]
Same error when upgrade to Angular 5.0.0 and Angular-CLI 1.5

**Comment by acuntex** [comment]
I updated from the latest 5 RC to the final 5 version. After that I got this error and "Cannot read property 'subscribe' of undefined" for some routes which made it impossible to navigate to this routes.

Even downgrading to the latest 5RC did not work which might be happening because of some dependency which has no pinned version and the latest one is broken.

Only a downgrade to the latest Angular 4 did make it work again.

**Comment by iTwangcj** [comment]
I have the same problem

**Comment by thomaspink** [comment]
Same here. Upgraded from 4.4 to 5

**Comment by dimitriy-k** [comment]
same issue cli 1.5, angular 5

**Comment by bop10** [comment]
Same here, using Angular 5 and CLI 1.5

**Comment by Ismaestro** [comment]
Same!!!

**Comment by jonathanbruno** [comment]
It seems to be an CLI problem,
Angular 4.4.6 and CLI 1.5 got the error

Angular 4.4.6 and CLI 1.4.9 everything works fine

**Comment by aalbericio** [comment]
I also get this error with Angular CLI 1.5.0 :/

**Comment by bh86** [comment]
We did the following (ugliest) workaround, in index.html:
`<script>
  window.req = window.dep = null;
</script>`

**Comment by aalbericio** [comment]
Yeah, it's definitely a CLI error since reverting to 1.4.9 fixed the problem.

**Comment by Ismaestro** [comment]
@bh86 that work's but waiting for an official fix

**Comment by Kalki5** [comment]
Hoping it'd be fixed soon

**Comment by clydin** [comment]
Webpack’s uglifyjs plugin was updated in CLI 1.5 which replaced uglify-js with uglify-es. This currently has a bug in its collapse_var optimization which is the cause of the error.

**Comment by sandangel** [comment]
I want to know how my app will be affected by this bug because it seem still work correctly. And do we have a work around for this issue?

**Comment by SargoDarya** [comment]
@sandangel Taken straight from @bh86 

> <script> window.req = window.dep = null; </script>

Works but is super ugly.

**Comment by peterpeterparker** [comment]
the issue identified by @clydin in uglify-es seems to be marked as solved now https://github.com/mishoo/UglifyJS2/issues/2437

**Comment by clydin** [comment]
Yes.  It looks like a fix is in place and should be in the next patch version of uglify (3.1.8).

**Comment by jonathanp** [comment]
I encountered this error too, in CLI version 1.5 and Angular 5.0

**Comment by stewwan** [comment]
same here

**Comment by mediantiba** [comment]
Same here, got this after upgrading to @angular/cli to 1.5.0

**Comment by sandangel** [comment]
upgrade to cli 1.6-beta.0 fix this

**Comment by clydin** [comment]
uglify-es 3.1.8 is out with the fix.  There’s no need to update the CLI just ensure that version 3.1.8 or greater of uglify-es is installed.

**Comment by VishalGulati** [comment]
I am also facing this since yesterday when I upgraded to cli1.5!

**Comment by Dasiim** [comment]
As stated by @clydin, reinstall node_modules and it should be fixed :)

**Comment by VishalGulati** [comment]
@Dasiim Ok will try this. Thanks @clydin !

**Comment by lexcaraig** [comment]
@VishalGulati please update if it works! Thanks!

**Comment by sinedied** [comment]
Just tested after a `rm -rf node_modules`, I still got the error.

**Comment by Ismaestro** [comment]
After remove node_modules same here, still falling

**Comment by MikaAK** [comment]
It's a problem with uglify. If you have an ejected webpack config add this to your uglify plugin else it's a wait for the update it seems
```javascript
uglifyOptions: {
  compress: {
    collapse_vars: false
  }
}
```

**Comment by leandrogaspar** [comment]
It worked here after removing node_modules. Am I missing something? The problem was happening before the new uglify-es

**Comment by Ismaestro** [comment]
Solved! I removed node_modules folder AND **package-lock.json** and now it works!

**Comment by sinedied** [comment]
```sh
rm -rf node_modules
rm package-lock.json
npm cache clean --force
npm install
ng serve --prod
```
Still not working with angular@5 / angular-cli@1.5.

**Comment by Ismaestro** [comment]
Working [here](https://github.com/Ismaestro/angular5-example-app).

**Comment by sinedied** [comment]
With yarn, it worked but not with npm@5.5.1, even after clearing cache (see my previous comments) 😞

**Comment by Ismaestro** [comment]
mm
```
npm -v
5.5.1
```

**Comment by Ismaestro** [comment]
@sinedied can you provide us a repo??

**Comment by sinedied** [comment]
@Ismaestro sure: https://github.com/ngx-rocket/starter-kit/tree/feature/angular5 (make sure to use the feature/angular5 branch)

**Comment by Ismaestro** [comment]
<img width="1118" alt="screen shot 2017-11-07 at 16 19 53" src="https://user-images.githubusercontent.com/10084945/32501152-8a2a0bca-c3d7-11e7-9c2c-3316e61cafa0.png">

**Comment by Ismaestro** [comment]
Avoiding that error (I modified your enviroments.prod.ts) it works perfetly:
<img width="1272" alt="screen shot 2017-11-07 at 16 24 38" src="https://user-images.githubusercontent.com/10084945/32501419-3a5194a0-c3d8-11e7-9d20-fd7165447df9.png">

Steps I've made:
Clone your repo.
Checkout your feature/angular5 branch.
npm i
ng serve --prod
:)

**Comment by sinedied** [comment]
It finally worked after a new batch of remove, cache clean and install again 🙄 
I suspect I hit a cache somewhere (as yarn was fine), but anyways it's solved so I close the issue.

Thanks @Ismaestro for confirming that the problem was on my side ^^

**Comment by GiuseppePiscopo** [comment]
For me it was enough to look in `node_modules` for top level uglify-related packages, then reinstall them locally:

```sh
# uninstall
npm un uglify-js
npm un uglify-to-browserify
npm un uglifyjs-webpack-plugin

# install
npm i
```

At the end of the process, `npm i` output confirmed that the latest `uglify-es` version was installed as a transitive dependency:

```sh
| | +-- find-cache-dir@1.0.0
| | | +-- commondir@1.0.1
| | | `-- make-dir@1.1.0
| | |   `-- pify@3.0.0
| | +-- uglify-es@3.1.8
| | | `-- source-map@0.6.1
| | `-- worker-farm@1.5.1
```

Also, for this project there was no *package-lock.json* file to delete.

HTH

**Comment by rsaulo** [comment]
Same problem no Linux, same project on Mac works, anyone with this error on Linux?

**Comment by dimitriy-k** [comment]
@rsaulo, I had the same issue on Linux Ubuntu, but now it is solved. So, try to clean the cache or use the latest version of nodejs LTS (8.9.0)

**Comment by rsaulo** [comment]
@dimitriy-k it worked only when I updated the cli to 1.6.0. linux was not the problem, the problem only appear when running with --prod flag.

**Comment by KthProg** [comment]
How do I install cli 1.6? It isn't recognized in NPM. No other solutions have worked for me, my issue is also only with --prod flag and upgrading uglify-es does not work.

**Comment by dhasilva** [comment]
@KthProg npm install -g @angular/cli@next
But have in mind that it is still in beta.

**Comment by KthProg** [comment]
The beta version fixed the issue for me.

**Comment by clydin** [comment]
Note that what that did was just force uglify-es to be reinstalled since it’s a dependency of the CLI.

**Comment by Splaktar** [comment]
Yes, the beta is not required to pick up this fix.

**Comment by KthProg** [comment]
Then why did installing the latest version of uglify-es not work?

**Comment by KthProg** [comment]
Ah you know what, maybe because I had angular cli locally and globally installed (it warned me it would use the local version). That's all I can think of.

**Comment by GiuseppePiscopo** [comment]
@KthProg yep. Uninstall and install globally. Then also uninstall and install locally to your project, so that `uglify-es` as well gets updated as a by-product.

**Comment by Stradivario** [comment]
Installed typescript 2.6.1, removed package-lock.json then npm install again fixed error.

**Comment by overule** [comment]
So is the solution to upgrade to the angular/cli to 1.6 and above? Since it contains the updated uglify plugins?
