### ISSUE TITLE
angular cli freezes at extracting "rxjs"

### ISSUE THREAD

**Issue by leykhins** [angular/angular-cli#8367]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> angular cli freezes at extracting "rxjs"
- [ ] feature request
```

### Versions.

Angular CLI V 1.5.0

### Repro steps.

Install node.js
run npm install -g @angular/cli

### The log given by the failure.

[            ......] / extract:rxjs: sill pacote rxjs@https://registry.np
anced-match@0.4.2 checking installable status

**Comment by avalanchy** [comment]
Same issue on my side. I am on the stable Debian with node installed with instructions from nodejs.org
```
$ uname -snr
Linux deb 4.9.0-3-amd64
$ aptitude show nodejs
Package: nodejs                          
Version: 8.9.1-1nodesource1
$ npm -v
5.5.1
```

It just a freezes forever every time on the same step:
```
$ sudo npm install -g @angular/cli
[            ......] | extract:rxjs: sill pacote rxjs@https://registry.npmjs.org/rxjs/-/rxjs-5.5.2.tgz extracted to /usr/lib/node_modules/.staging/rxjs-d0ee3eb8 by content address 2259ms
```

**Comment by avalanchy** [comment]
Ok, it unfreezes after a long time. 

From the output grabbed this `gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.9.1"`. After googling this line I found a solution of adding an extra flag "unsafe-perm" (which is not documented in npm install manual) that fixes the problem:
```
sudo npm i --unsafe-perm --verbose -g @angular/cli
```

**Comment by Brocco** [comment]
@avalanchy I'm glad you were able to solve your issue.

Installation issues are not something that the CLI can solve itself, I suggest looking into npm permissions issues.

**Comment by luchofisi** [comment]
que desgracia uno queriendo aprender y ya padecer con problema tras otro tras otro, paciencia paciencia

**Comment by hypnotic-frog** [comment]
> 
> 
> que desgracia uno queriendo aprender y ya padecer con problema tras otro tras otro, paciencia paciencia

Wellcome to the Node.js stack dude!! Enjoy!
