### ISSUE TITLE
Several libraries used in the package are deprecated and `graceful-fs` will not work in Node v.7.0

### ISSUE THREAD

**Issue by mickeyvip** [angular/angular-cli#837]
Mac OSX El Capitan

Version:

``` bash
$ ng --version
(node:82974) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.4
node: 6.2.0
os: darwin x64
```

The install output gives the following:

``` bash
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

The more critical in my opinion is the warning about `graceful-fs`.

Thank you.

**Comment by sanderboom** [comment]
Similar:

```
λ ng --version
(node:17696) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.4
node: 6.1.0
os: linux x64
```

**Comment by FabienDehopre** [comment]
Same on windows 10:
```
 ng --version
(node:7672) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 1.0.0-beta.5
node: 6.2.0
os: win32 x64
```

**Comment by filipesilva** [comment]
We'll need this for Node 7 but for now it's just an annoying, ubiquitous error.

**Comment by filipesilva** [comment]
(closed by accident)

**Comment by JanStureNielsen** [comment]
From `npm ls graceful-fs` it looks like there are only two pre-4 `graceful-fs` dependencies in Angular CLI:

```
├─┬ angular-cli@1.0.0-beta.19-3
│ ├─┬ angular2-template-loader@0.5.0
│ │ └─┬ codecov@1.0.1
│ │   └─┬ execSync@1.0.2
│ │     └─┬ temp@0.5.1
│ │       └─┬ rimraf@2.1.4
│ │         └── graceful-fs@1.2.3
│ ├─┬ ember-cli@2.5.0
│ │ └─┬ yam@0.0.18
│ │   └─┬ fs-extra@0.16.5
│ │     └── graceful-fs@3.0.11
...
```

Upgrading to the latest `ember-cli` (`0.0.11`) fixes the `graceful-fs@3.0.11` dependency. Unfortunately, addressing the `graceful-fs@1.2.3` dependency requires multiple updates:

 * new release of `execSync` to use latest `temp`
 * then new release of `codecov` with ^^^
 * then new release of `angular2-template-loader` with ^^^

...or a refactoring of `angular2-template-loader` to avoid the `codecov@1.0.1` dependency.

cc: @TheLarkInn

**Comment by clydin** [comment]
Latest version of the template loader (0.6.0) fixes the codecov issue.
So that leaves ember-cli which is unfortunately non-trivial.

**Comment by JanStureNielsen** [comment]
Hmm, @clydin -- [`angular2-template-loader@0.6.0` uses `codecov@1.0.1`](https://github.com/TheLarkInn/angular2-template-loader/blob/master/package.json), no?

**Comment by clydin** [comment]
As a dev dep only

**Comment by CarreraPHP** [comment]
With beta24, there are no warnings being displayed. 

Below is the screenshot for the same taken in macOSX Sierra.

I believe, this issue can be closed.

<img width="419" alt="screen shot 2016-12-23 at 10 42 16 am" src="https://cloud.githubusercontent.com/assets/422070/21447580/926d97d8-c8fc-11e6-85a1-28ea5e11b6a9.png">

**Comment by catull** [comment]
➜  angular-cli.git git:(master) npm ls graceful-fs
angular-cli@1.0.0-beta.26 workspace/js/ng/angular-cli.git
├─┬ enhanced-resolve@2.3.0
│ └── graceful-fs@4.1.11
└─┬ webpack-dev-server@2.2.0-rc.0
  └─┬ chokidar@1.6.1
    └─┬ fsevents@1.0.17
      └─┬ node-pre-gyp@0.6.32
        └─┬ tar@2.2.1
          └─┬ fstream@1.0.10
            └── graceful-fs@4.1.11

graceful-fs version 4.1.11 is used now.
Time to close this issue.

**Comment by hansl** [comment]
Closing this as solved \o/
