### ISSUE TITLE
How to do static file versioning like images available in asset folder in Angular4

### ISSUE THREAD

**Issue by MukundSonaiya** [angular/angular-cli#8370]
On updating a new version of my Angular4 site. The images are not re-downloaded on new version update. Browser continues using cached assets until we manually clear the cache. I am using ng-cli for deployment. My current angular version is 4.4.0-RC.0

**Comment by filipesilva** [comment]
Heya, we don't fingerprinting of images referenced in HTML. There is an issue tracking this problem in https://github.com/angular/angular-cli/issues/3415.
