### ISSUE TITLE
Allow use  of relative paths outside app folder for css files when building  in  aot

### ISSUE THREAD

**Issue by abidmix** [angular/angular-cli#8372]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.4
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/upgrade: 4.4.6
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.4
typescript: 2.3.4

### Repro steps.
Put css files outside app folder
Reference the folder relatively.
The app builds fine in JIT mode

Try the same in AOT mode
Build breaks

### The log given by the failure.
![image](https://user-images.githubusercontent.com/12702893/32453318-e3800e16-c2e9-11e7-902d-a7795479bdaf.png)

### Desired functionality.

What would like to see implemented?
I should be able to reference files outside the App folder  both in JIT and AOT modes

What is the usecase?

We adhere to using  css files and html files from specific locations in our orginization. And I should not be moving my css files in the app folder for aot to work. 

HTML templates are located in their location in AOT mode, so should be css files.

### Mention any other details that might be useful.
Folder structure is like this
             css
             Templates
             Scripts
             |___
                  |
                  app
                      |__
                            mycomunities
                                   entrypoint.ts
I should be able to reference the css and Template folder both in JIT and AOT mode  without moving the css folder in the app folder for AOT compilation to work. As you can see in the image posted its  looking for css files relative to the app folder.

**Comment by legends-of-dorothy** [comment]
@Brocco I think it would be nice to have this function.
To solve this problem, I eventually copied the CSS file into a project. @

**Comment by abidmix** [comment]
This is now working as expected in 1.7.0
