### ISSUE TITLE
AngularCompilerPlugin ignores compilator configuration

### ISSUE THREAD

**Issue by maciejtreder** [angular/angular-cli#8375]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

node: v8.5.0
npm: 5.3.0
ngtools: 1.9.0-beta.0
@angular: 5.0.0

### Repro steps.

Into my webpack config I am attaching AngularCompilerPlugin:
```
new AngularCompilerPlugin({
        tsConfigPath: /*path_to_my_tsconfig.json*/
        skipCodeGeneration: false
    });
```

My tsconfig.json contains following entries:
```
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "commonjs",
    "target": "es5",
    "experimentalDecorators": true,
    "lib": ["dom", "es6", "es2015", "es2016", "es2017", "esnext"],
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "angularCompilerOptions": {
    "entryModule": "./src/app/server-app.module#ServerAppModule",
    "genDir": "./src/ngfactory"
  },
  "include": [
    "./src/main.server.aot.ts"
  ]
}
```

### The log given by the failure.

Compilation fails with the given output:

```
ERROR in src/main.server.aot.ts(11,42): error TS2307: Cannot find module './ngfactory/app/server.app.module.ngfactory'.
```

### Desired functionality.
In previous version (angular: 4.4.6 & ngtools 1.7.4) AOT compilation works fine.

### Mention any other details that might be useful.
I decided to check out what settings goes to the AngularCompilerPlugin (```console.log(myPlugin);```) and I found out that difference between 1.7.4 and 1.8+ is that, the newest plugin release is ignoring config specified in `tsconfig.json` file in few fields. In other words, for example in 1.7.4 all configuration is saved under ```_options``` field:

```
 _options: 
   { tsConfigPath: '/path/to/my/project/tsconfig.server.aot.json',
     skipCodeGeneration: false,
     exclude: [ '**/*.spec.ts' ] },
  _tsConfigPath: '/path/to/my/project/tsconfig.server.aot.json',
  _rootFilePath: 
   [ '/path/to/my/project/./node_modules/@angular-universal-serverless/external-module/release/src/externalComponent/external.module.d.ts',
     '/path/to/my/project/src/main.server.aot.ts',
     '/path/to/my/project/src/app/httpProxy/http-proxy.module.ts',
     '/path/to/my/project/src/app/lazy/lazy.module.ts',
     '/path/to/my/project/src/app/server-app.module.ts' ],
  _compilerOptions: 
   { moduleResolution: 2,

etc. etc. etc.
```

while in the newest version those fields are not propagated with values:

```
_options:
{ moduleResolution: 2,
    module: 1,
    target: 1,
    experimentalDecorators: true,
    lib: [Array],
    typeRoots: [Array],
    configFilePath: undefined,
    entryModule: './src/app/server-app.module#ServerAppModule',
    genDir: '/path/to/my/project',
    basePath: '/path/to/my/project',
    outDir: '',
```

I tried as well to pass compiler options via `compilerOptions` field in the plugin constructor - with same results.

Full diff between 1.8 and 1.7 can be found here: https://www.diffchecker.com/uQmsudv4

Repository with reproduced issue can be found here (branch dependenciesUpdate):
https://github.com/maciejtreder/angular-universal-pwa/tree/dependenciesUpdate

**Comment by filipesilva** [comment]
Heya, your link doesn't work anymore. Did you manage to sort the issue out?

**Comment by roo2** [comment]
I believe I'm also seeing this issue (though I can't actually confirm it because I used the angular bootstrap app and don't understand webpack/typescript/the build system all that well)

**Comment by jbedard** [comment]
One thing I found while looking into a similar issue... I'm not sure if it even causes any issues, but I noticed `AngularCompilerPlugin` [determines the basePath](https://github.com/angular/angular-cli/blame/v1.7.0-beta.2/packages/%40ngtools/webpack/src/angular_compiler_plugin.ts#L157-L165) and then doesn't use it?

**Comment by clydin** [comment]
Closing as the latest version should rectify the original issue.  If problems persist, please open a new issue detailing the versions used.
