### ISSUE TITLE
Scaffolding a new app with --service-worker doesn't add "serviceWorker": true to .cli-config.json

### ISSUE THREAD

**Issue by webmaxru** [angular/angular-cli#8377]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Angular CLI 1.6.0-beta.0

### Repro steps.
- scaffold a new app with --service-worker flag

### Desired functionality.
Having "serviceWorker": true in apps[0] of .cli-config.json

cc: @alxhub

**Comment by Brocco** [comment]
This issue has been resolved.
