### ISSUE TITLE
npm link exist node_modules error

### ISSUE THREAD

**Issue by xiongyayun428** [angular/angular-cli#8381]
![image](https://user-images.githubusercontent.com/11458959/32476076-1f83756c-c3b0-11e7-97c9-1f45714087d3.png)

![image](https://user-images.githubusercontent.com/11458959/32476138-7d1714a4-c3b0-11e7-85cb-53cb3cc6b9d0.png)

tsconfig.json
```ts
{
    "compileOnSave": false,
    "compilerOptions": {
        "outDir": "./dist/out-tsc",
        "baseUrl": ".",
        "paths": {
            "@angular/*": [
                "./node_modules/@angular/*"
            ]
        },
        "noImplicitAny": true,
        "sourceMap": true,
        "inlineSources": true,
        "inlineSourceMap": true,
        "declaration": true,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "skipLibCheck": true,
        "removeComments": true,
        "target": "es5",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2017",
            "dom"
        ]
    },
    "include": [
        "src/**/*",
        "node_modules/fis-ui/index.ts",
        "node_modules/fis-ui/src/**/*"
    ]
}
```

**Comment by gios** [comment]
I have the same error with Angular 5, angular-cli 1.5.4 but with ngZone

Error: StaticInjectorError[NgZone]: 
  StaticInjectorError[NgZone]: 
    NullInjectorError: No provider for NgZone!
    at _NullInjector.get (core.js:923)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveNgModuleDep (core.js:10585)
    at _createClass (core.js:10630)
    at _createProviderInstance$1 (core.js:10596)

Remove @angular from linked library helps, but it's not a solution because I can't update module after that.

**Comment by gios** [comment]
#8677 The same

**Comment by benjamin-wilson** [comment]
Same. Different injector error.

**Comment by filipesilva** [comment]
Closing in favor of https://github.com/angular/angular-cli/issues/8117. It seems to generally be the same problem.
