### ISSUE TITLE
npm install hangs at npm-cache\_locks\staging-xxxxx for some repositories

### ISSUE THREAD

**Issue by anurag2361** [angular/angular-cli#8382]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Output from: `ng --version`. 1.5.0
Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?) Windows 10
node --version - 8.9.0
npm --version - 5.5.1

### Repro steps.
1. Download any Angular app repo
2. Run `npm install`

### The log given by the failure.

![image](https://user-images.githubusercontent.com/27642991/32476590-488ecec8-c39e-11e7-8f88-e924e092b1eb.png)

### Mention any other details that might be useful.

It gets stuck at this message for long times and while this time, CPU usage reaches up to 95+%. Note that i installed Angular CLI and it worked just fine. This scenario is also encountered on a hit or miss basis on some repositories. Sometimes it occurs, sometimes not. I cant really make out the cause. I tried running it in PowerShell with administrator, uninstalling and reinstalling nodejs (both 64bit and 32bit versions) and clearing/verifying npm cache. Still the same problem.

For e.g. try with this repo https://github.com/cornflourblue/mean-angular2-registration-login-example

**Comment by Brocco** [comment]
npm install failing is not a bug of the CLI, I would suggest looking into npm installation issues on stackoverflow or consulting npm documentation. Good luck!

**Comment by M-Zishan** [comment]
My "npm install -g @angular/cli" command also stucks
and it does not work.. I am using Windows 10
