### ISSUE TITLE
angular with universal getting error

### ISSUE THREAD

**Issue by anivaisu** [angular/angular-cli#8384]
Hi,
I am trying to angular with universal.

I refer this  https://github.com/angular/angular-cli/wiki/stories-universal-rendering.

I build my app 

using this command

`npm run build:ssr`

I trying to serve using this command

`npm run serve:ssr`

I am getting this error.

```
> Unhandled Promise rejection: renderModule[Factory]() requires the use of BrowserModule.withServerTransition() to ensure
> the server-rendered app can be properly bootstrapped into a client app. 
```

How can i fix this issue.

Kindly pls advice me,

Thanks.

**Comment by CaerusKaru** [comment]
Ok, first question, do you have the line `BrowserModule.withServerTransition()` in your `AppModule`? Also, can you post the repo you're dealing with so we can take a closer look at it?

**Comment by TomasKatz** [comment]
Have the same issue and dont have BrowserModule.withServerTransition() in my AppModule

**Comment by CaerusKaru** [comment]
@TomasKatz Do you have it somewhere? It needs to be somewhere in your application.

**Comment by TomasKatz** [comment]
Resolved it by adding:
```
import { BrowserModule } from '@angular/platform-browser';
...
imports: [
      BrowserModule.withServerTransition({
          appId: 'ng-universal-demystified'
      })...
  ]
```
However the problem we are facing here is f**ing uploading an express-universal app to IIS, which proves  to be non-trivial at all.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
