### ISSUE TITLE
Will an automatic update be added to the Angular CLI?

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#8390]
Very much it would be desirable to be easily updated with use of a cli, in the event that versions Angular leave every 6 months, it is not so convenient independently to be updated.

Angular CLI should analyze the code of my application (if the project was created with the help of Angular CLI), and if there are no critical changes, then independently update the application, or give out warnings and reasons for which you need to manually update.

**Comment by Brocco** [comment]
This is something that is on the roadmap, unfortunately there is no timeframe for implementation at this point.

An issue will be created to track this request, but it should follow the new issue template.
