### ISSUE TITLE
1.6.0-beta.0: Unexpected value 'e' imported by the module 'e'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by AndreyKotofotoff** [angular/angular-cli#8391]
Uncaught Error: Unexpected value 'e' imported by the module 'e'. Please add a @NgModule annotation.

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Angular CLI: 1.6.0-beta.0
Node: 8.8.1
OS: win32 x64
Angular: 5.0.0

### Repro steps.
ng serve - OK
ng serve --prod --aot=false - ERROR

### The log given by the failure.
App.module.ts
import 'moment';

import { HashLocationStrategy, LocationStrategy } from '@angular/common';
import { APP_BASE_HREF } from '@angular/common';
import { NgModule } from '@angular/core';
import { BrowserModule, Title } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import { MNTR_API_URL } from '../config';
import { environment } from '../environments/environment';
import { AppComponent } from './app.component';
import { NavService } from './core';

@NgModule({
    bootstrap: [AppComponent],
    declarations: [AppComponent],
    imports: [
        BrowserModule,
        BrowserAnimationsModule       
    ],
    providers: [
        NavService,
        Title,
        { provide: MNTR_API_URL, useValue: environment.API_URL },
        { provide: APP_BASE_HREF, useValue: "/" },
        { provide: LocationStrategy, useClass: HashLocationStrategy }
    ]
})
export class AppModule { }

**Comment by emreavsar** [comment]
same here

**Comment by mcterrySep** [comment]
I'm having a similar issue :-/

**Comment by roweldeguzman** [comment]
Same here, I have to downgrade my @angular/cli to make it work.

**Comment by mcterrySep** [comment]
I'm on cli version 1.5.0 and having this problem.
What version did you downgrade to @roweldeguzman ?

**Comment by roweldeguzman** [comment]
@mcterrySep  i tried to downgrade my @angular/cli to 1.2.6 and 1.4.3, but 1.2.6 is faster than 1.4.3 when running ng serve --prod --aot=false.  and just install your package again. 


here is my package.json


```
{
  "name": "template",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.2.6",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "jquery": "^3.2.1",
    "bootstrap": "^3.3.7",
    "ngx-bootstrap": "^2.0.0-beta.8",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}
```

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by gmareater** [comment]
same here

**Comment by hossainiir** [comment]
I have same problem, is there any solution?

**Comment by ArthurBrito** [comment]
```
Angular CLI: 6.0.8
Node: 8.11.1
OS: darwin x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```
I just:
`ng new aot-problem` 

ng serve OK
ng serve --prod OK
ng serve --aot OK
ng serve --prod --aot=false ERROR

Error:
```
inject.preload.js:373 GET blob:http://localhost:4201/0da2aa42-76a8-421e-82f0-1f7dd5b88cce 0 ()
splitSelector.splitSelector @ inject.preload.js:373
__webpack_require__ @ bootstrap 459d30130528313280ec:19
(anonymous) @ common.js:103
__webpack_require__ @ bootstrap 459d30130528313280ec:19
exports.textToRegExp @ bootstrap 459d30130528313280ec:62
(anonymous) @ bootstrap 459d30130528313280ec:62
```
```
Uncaught Error: Unexpected value 'e' imported by the module 'function(){}'. Please add a @NgModule annotation.
    at ka (main.d1098ea43641b8f1bc06.js:1)
    at main.d1098ea43641b8f1bc06.js:1
    at Array.forEach (<anonymous>)
    at e.getNgModuleMetadata (main.d1098ea43641b8f1bc06.js:1)
    at e._loadModules (main.d1098ea43641b8f1bc06.js:1)
    at e._compileModuleAndComponents (main.d1098ea43641b8f1bc06.js:1)
    at e.compileModuleAsync (main.d1098ea43641b8f1bc06.js:1)
    at e.compileModuleAsync (main.d1098ea43641b8f1bc06.js:1)
    at e.bootstrapModule (main.d1098ea43641b8f1bc06.js:1)
    at Object.zUnb (main.d1098ea43641b8f1bc06.js:1)
ka @ main.d1098ea43641b8f1bc06.js:1
(anonymous) @ main.d1098ea43641b8f1bc06.js:1
e.getNgModuleMetadata @ main.d1098ea43641b8f1bc06.js:1
e._loadModules @ main.d1098ea43641b8f1bc06.js:1
e._compileModuleAndComponents @ main.d1098ea43641b8f1bc06.js:1
e.compileModuleAsync @ main.d1098ea43641b8f1bc06.js:1
e.compileModuleAsync @ main.d1098ea43641b8f1bc06.js:1
e.bootstrapModule @ main.d1098ea43641b8f1bc06.js:1
zUnb @ main.d1098ea43641b8f1bc06.js:1
p @ runtime.a66f828dca56eeb90e02.js:1
3 @ main.d1098ea43641b8f1bc06.js:1
p @ runtime.a66f828dca56eeb90e02.js:1
n @ runtime.a66f828dca56eeb90e02.js:1
e @ runtime.a66f828dca56eeb90e02.js:1
(anonymous) @ main.d1098ea43641b8f1bc06.js:1
```

ng build OK
ng build --prod OK
ng build --aot OK
ng build --prod --aot=false ERROR

```
The `--build-optimizer` option cannot be used without `--aot`.
Error: The `--build-optimizer` option cannot be used without `--aot`.
```

 It looks like ng server can't run --prod --aot=false for the same reason, but the error message is completely different.

repo: https://github.com/ArthurBrito/aot-problem

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
