### ISSUE TITLE
Failed to create new project after install angular-cli

### ISSUE THREAD

**Issue by Callie-C-Wang** [angular/angular-cli#8392]
After install angular-cli and then try to create new project
error occured

C:\>ng new myapp

Error: tree.branch is not a function
tree.branch is not a function

node verson = 8.9.0
npm version = 5.5.1

Then I use the following 2 commands to uninstall angular/cli
npm uninstall -g @angular/cli
npm cache verify

When I install again using the following command (I use administrator permission)
npm install -g @angular/cli

Here are errors:
C:\windows\system32>npm install -g @angular/cli
npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules' }
npm ERR! path C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE\node_modules\node-sass
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE\node_modules\node-sass' -> 'C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass'
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE\node_modules\node-sass' -> 'C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sa
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename 'C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE\node_modules\node-sass' -> 'C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path: 'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\.cli.DELETE\\node_modules\\node-sass',
npm ERR!      dest: 'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-sass' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, rename \'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\.cli.DELETE\\node_modules\\node-sass\' -> \'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angul
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\.cli.DELETE\\node_modules\\node-sass',
npm ERR!   dest: 'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-sass' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cwang\AppData\Roaming\npm-cache\_logs\2017-11-07T21_55_44_380Z-debug.log

C:\windows\system32>

**Comment by Callie-C-Wang** [comment]
I guess there were errors happened when install angular cli

C:\windows\system32>npm install -g @angular/cli
C:\Users\cwang\AppData\Roaming\npm\ng -> C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng

> node-sass@4.6.0 install C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.6.0/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.6.0/win32-x64-57_binding.node":

tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:7890

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.6.0 postinstall C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\n
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb check python launcher python executable found: "C:\\Users\\cwang\\.windows-build-tools\\python27\\python.exe"
gyp verb check python version `C:\Users\cwang\.windows-build-tools\python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.13\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.0
gyp verb command install [ '8.9.0' ]
gyp verb install input version string "8.9.0"
gyp verb install installing version: 8.9.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.0
gyp verb build dir attempting to create "build" dir: C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? null
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.16299.Desktop
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\cwang\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\cwang\\.node-gyp\\8.9.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\cwang\\.node-gyp\\8.9.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\cwang\\.node-gyp\\8.9.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\cwang\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\cwang\.node-gyp\8.9.0
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 11/7/2017 5:15:12 PM.
Project "C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\binding.sln" (1) is building "C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default target
Project "C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (defaul
PrepareForBuild:
  Creating directory "Release\obj\libsass\".
  Creating directory "Release\obj\libsass\libsass.tlog\".
InitializeBuildStatus:
  Creating "Release\obj\libsass\libsass.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\CL.exe /c /I"C:\Users\cwang\.node-gyp\8.9.0\include\node" /I"C:\Users\cwang\.node-gyp\8.9.0\src" /I"C:\Users\cwang\.node-gyp\8.9.0\deps\uv\include" /I"C:\Users\cwang\.n
  ss\src\check_nesting.cpp ..\..\src\libsass\src\color_maps.cpp ..\..\src\libsass\src\constants.cpp ..\..\src\libsass\src\context.cpp ..\..\src\libsass\src\cssize.cpp ..\..\src\libsass\src\emitter.cpp ..\..\src\libsass\src\environment.cpp ..\..\src\libsass\src\error_handlin
  functions.cpp ..\..\src\libsass\src\sass_util.cpp ..\..\src\libsass\src\sass_values.cpp ..\..\src\libsass\src\source_map.cpp ..\..\src\libsass\src\subset_map.cpp ..\..\src\libsass\src\to_c.cpp ..\..\src\libsass\src\to_value.cpp ..\..\src\libsass\src\units.cpp ..\..\src\li
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\src\libsass.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\src\libsass.vcxproj]
  ast.cpp
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\src\libsass.vcxproj]
  ast_fwd_decl.cpp
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\src\libsass.vcxproj]
  base64vlq.cpp
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\src\libsass.vcxproj]
  bind.cpp
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\src\libsass.vcxproj]
  check_nesting.cpp
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\src\libsass.vcxproj]
  color_maps.cpp
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\src\libsass.vcxproj]
  constants.cpp
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\cwang\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass\build\src\libsass.vcxproj]
  context.cpp

**Comment by foxjazz** [comment]
Follow the install steps
https://github.com/angular/angular-cli#installation

**Comment by Brocco** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
