### ISSUE TITLE
Angular CLI webpack-dev-server fails to compile, module build failed

### ISSUE THREAD

**Issue by mmanavaz** [angular/angular-cli#8394]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Operating System: Windows 10
Node Version: v6.9.5
NPM Version: 5.5.1
webpack Version: 3.8.1
webpack-dev-server Version: 2.9.4
[x ] This is a bug
 This is a feature request
 This is a modification request

Code

main.ts
`import { enableProdMode } from '';
import { platformBrowserDynamic } from '';

import { AppModule } from './main/ui/app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
enableProdMode();
}
platformBrowserDynamic().bootstrapModule(AppModule);`

`/**

This file includes polyfills needed by Angular and is loaded before the app.
You can add your own extra polyfills to this file.
This file is divided into 2 sections:
Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
Application imports. Files imported after ZoneJS that should be loaded before your main
 file.
The current setup is for so-called "evergreen" browsers; the last versions of browsers that
automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
*/
/***************************************************************************************************

BROWSER POLYFILLS
*/
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js'; // Run npm install --save classlist.js.

/** IE10 and IE11 requires the following for the Reflect API. */
// import 'core-js/es6/reflect';

/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';

/**

Required to support Web Animations @angular/platform-browser/animations.
Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
**/
// import 'web-animations-js'; // Run npm install --save web-animations-js.
/***************************************************************************************************

Zone JS is required by Angular itself.
*/
import 'zone.js/dist/zone'; // Included with Angular CLI.
/***************************************************************************************************

APPLICATION IMPORTS
*/
/**

Date, currency, decimal and percent pipes.
Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
/
// import 'intl'; // Run npm install --save intl.
/*
Need to import at least one locale-data with intl.
*/
// import 'intl/locale-data/jsonp/en';`
  // webpack.config.js

module.exports = {
    devServer: {
        host: '0.0.0.0:4200',
        disableHostCheck: true
    },
    entry: [
        'webpack-dev-server/client?http://localhost:4200',
        "./src/polyfills.ts",
        "./src/main.ts",
        config.paths.demo
    ],
    output: {
        filename: 'vendor.ts'
    },
    resolve: {
        extensions: ['.js', '.ts']
    }
}
  // additional code, remove if not needed.
Expected Behavior

Successful compilation

Actual Behavior

Errors

ERROR in ./src/main.ts
Module build failed: [object Object]
@ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
ERROR in ./src/polyfills.ts
Module build failed: [object Object]
@ multi ./src/polyfills.ts

For Bugs; How can we reproduce the behavior?

Followed the Angular tutorial on angular.io docs listed under webpack.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
