### ISSUE TITLE
can't find var defined in typings.d.ts in cli v1.5

### ISSUE THREAD

**Issue by dhcn** [angular/angular-cli#8396]
for example, I define below code in typings.d.ts:
`declare module 'admin-lte' {
}`
and types settings as below:
'
"types": [
      "jquery",
      "echarts",
      "datatables.net",
      "bootstrap",
      "admin-lte"
    ]
'
I will get a exception:TS2688: Cannot find type definition file for 'admin-lte'.
but if I remove types settins form tsconfig.app.json,the exception disappears;
it seems to be the typings.d.ts has not been complied 

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by deebloo** [comment]
@dhcn the ```types``` array is for types installed via ```@types/something``` The included d.ts file will be included in the ts compiler by default

**Comment by dhcn** [comment]
Thanks,Every thing run as normal.the exception no longer appears.
