### ISSUE TITLE
upgrade blueprints to 2.0.0-alpha.47

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#84]
- [x] package.json needs to be updated (we intentionally bump the version manually each time for now to have control over breaking changes that require blueprints update)
- [x] replace `import ... from 'angular2/angular2'` with `... from 'angular2/core'` (this might still change in the future, see https://github.com/angular/angular/issues/5539, but for now let's switch to `core`)
- [x] the only exception to the above is `bootstrap` which should come from `import {bootstrap} from 'angular2/platform/browser'`

that should be it...

cc: @wardbell for documentation update since that will be affected in similar way

**Comment by IgorMinar** [comment]
Anyone wants to work on this?

**Comment by cironunes** [comment]
Can I assign to me?

**Comment by IgorMinar** [comment]
sure

**Comment by Brocco** [comment]
@cironunes if not you're busy, this is something that I'm more than willing to take on

**Comment by cironunes** [comment]
I'm getting many errors from TypeScript, I think that they are related to typings.

I noticed that there's a breaking change regarding typings. Is it supposed to break?

**Comment by cironunes** [comment]
I mean, aren't we already using typings from the package?

**Comment by IgorMinar** [comment]
We are. It should work just fine. I tested a generated app locally with 47
and it bootstrapped without errors. I haven't tested anything else though.

**Comment by Brocco** [comment]
@IgorMinar was that a TypeScript project?

**Comment by cironunes** [comment]
Forget about it. It's working fine.
