### ISSUE TITLE
ng generate component (ViewEncapsulation) missing from import

### ISSUE THREAD

**Issue by foxjazz** [angular/angular-cli#8404]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting

```

### Versions.
@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1

### Repro steps.
ng g component somename

This adds a line: 
 encapsulation: ViewEncapsulation.None

but does not add the import 
import {Component, OnInit, ViewEncapsulation} from '@angular/core';

instead adds 
import {Component, OnInit} from '@angular/core';

**Comment by foxjazz** [comment]
Duplicate

**Comment by brysageek** [comment]
This should not have the encapsulation: ViewEncapsulation.None at all by defualt

**Comment by Shiroh1ge** [comment]
Can this be disabled? I don't want any of my components to not have encapsulation. I'm not sure why this was added by default, it's a bad practice to disable encapsulation anyway.
