### ISSUE TITLE
Document 'platform' option for Angular Compiler Plugin / consider string enum

### ISSUE THREAD

**Issue by josephliccini** [angular/angular-cli#8409]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.

1.5.0 (ejected webpack config)

### Desired functionality.

When one does `ng eject --prod --aot` we see that in the Angular Compiler Options, `platform: 0`.

Maybe it could use a String `enum` for this enum:
https://github.com/angular/angular-cli/blob/cb53fb933cbe07d4076863c184ee475296ffd59f/packages/%40ngtools/webpack/src/angular_compiler_plugin.ts#L78-L82

Could be changed to:
```ts
export const enum PLATFORM {
    Browser = 'Browser',
    Server = 'Server'
}
```

Which would produce in the ejected webpack config:
```js
new AngularCompilerPlugin({
    ...
    platform: 'Browser'
});
```

Thoughts?

Thanks!
Joe

**Comment by filipesilva** [comment]
Heya, what would be the benefit of this? We do export the available platform enum so that it can be imported with no breakage in case the underlying representation changes. That approach seems more versatile than trying it to a string.

**Comment by alan-agius4** [comment]
Closing as no further information was provided by the author of the issue.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
