### ISSUE TITLE
The Bootstrap 4 SCSS wiki story is now incorrect.

### ISSUE THREAD

**Issue by jongillham** [angular/angular-cli#8416]
The [current version](https://github.com/angular/angular-cli/wiki/stories-include-bootstrap/2d914bcafcfca82a6551b18d710cbba0144977bd#using-sass) of the Bootstrap 4 SCSS story is now incorrect due to changes in the [Bootstrap beta versions SCSS theming](https://getbootstrap.com/docs/4.0/getting-started/theming/). `$brand-primary: red;` at the bottom of the story should change from `$brand-primary: red;` to `$primary: red;` just for Bootstrap 4.

The `@import '../node_modules/...'` could also probably be changed to `@import 'node_modules/...'` for more portability.

**Comment by Stephenradams** [comment]
@Brocco I'd like to look at this. Looks a good first issue to look into.

**Comment by wbhob** [comment]
Looks like this has been fixed. Close this?

**Comment by seizadi** [comment]
For BootStrap Alpha version bootstrap@4.0.0-alpha.6
It worked w/  '$brand-primary: red;' 
The current instructions '$primary: red;' did not affect the button color.
