### ISSUE TITLE
Adding/Changing comments and line-breaks should not trigger recompile on serve

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#8419]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality.
Adding a comment, editing a comment, adding/removing linebreaks should not trigger a recompile and reload when using ng serve.

### Intention
 This is kind of annoying because the code did not change and a recompile is not needed. 
For example i create a new feature, test it in the browser and while testing i add some comments into the code. The browser reloads and i have to start my user test again.

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by mgechev** [comment]
Closing it due to inactivity. If the problem is still reproducible with the latest CLI, please open a new issue following the template and sharing a minimal demo where we can reproduce it. Thank you! :)

**Comment by MickL** [comment]
Not sure if reproducable, but at least the CLI/Webpack became so fast it doesnt matter as much anymore.
