### ISSUE TITLE
Generation path broken with custom src dir since 1.4.0

### ISSUE THREAD

**Issue by pierre-hilt** [angular/angular-cli#8424]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Hello,

I an error since using @angular/cli 1.4.X.

ng new test-app --directory dir --source-dir package/test
$ ng g m testmodule --dry-run
  create package/test/package/test/app/testmodule/testmodule.module.ts (194 bytes)

NOTE: Run with "dry run" no changes were made.

when app[X].root is modified, it breaks code scaffolding. Instead of generating:

package/test/app/testmodule/testmodule.module.ts

It generates

package/test/package/test/app/testmodule/testmodule.module.ts

**Comment by hansl** [comment]
This has been fixed in 1.x, and I'm certain it doesn't happen in 6.0 (and master). Closing this as fixed.
