### ISSUE TITLE
Exception while using template-strings in a decorator

### ISSUE THREAD

**Issue by thomassittig** [angular/angular-cli#8428]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
Angular CLI: 1.5.0
Node: 6.11.0
OS: darwin x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.6.1
webpack: 3.8.1

```
### Repro steps.

This is a follow-up from [here](https://github.com/angular/angular/issues/20255).

Using template-strings to define a _templateUrl_ and _styleUrls_.

A valid example would be, to have an variable which contains a value that can be consumed as  part of the templateUrl and the styleUrls together.

By doing this, while running `ng serve` an exception occure that the requested resources can not be found. 
In the exception can also the RAW template-strings be found, and not the finally constructed.

You can find a example repos here: https://github.com/thomassittig/angular5-string-interpolation-error.

Minimal reproduction steps:

* create a blank new out of the box angular 5 project
* go to the `app/app.component.ts`
* create a variable called `name` with the value `app`
* change the styleUrls to `[`./${name}.component.css`]`
* re-run the app with `ng serve`

Full Example:

```
import { Component } from '@angular/core';

const name = 'app';

@Component({
  selector: 'app-root',
  templateUrl: `./${name}.component.html`,
  styleUrls: [`./${name}.component.css`]
})
export class AppComponent {
  title = 'app';
}
```

### Desired functionality.

All is fine and the constructed string-values are accepted and the resources can be found

**Comment by thomassittig** [comment]
Small update: this issue still occures in the current, freshly released, 1.6 version.

**Comment by filipesilva** [comment]
I'm sorry but this is something we will not support. Those paths need to be statically analyzable, and while that is possible in your very simple example we can't ensure it will for more complex scenarios.

**Comment by thomassittig** [comment]
@filipesilva understandable. but it was working before the v1.5 release. And so in my simple mind you ensured that this worked before. or was it a simple coincidence?

**Comment by filipesilva** [comment]
I have no idea how it worked before 1.5 really. @hansl was this supported in the old plugin? (we changed compilation pipelines between 1.4 and 1.5).
