### ISSUE TITLE
Change typings.json to use 'global' instead of ambient'

### ISSUE THREAD

**Issue by alexkibler** [angular/angular-cli#843]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
1.0.0-beta.4

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
typings install

Typings install does not install the d.ts files because it's expecting the typings.json file to have globalDependencies as opposed to ambientDependencies, as it is now.

See the [typings changelog](https://github.com/typings/typings/releases/tag/v1.0.0)

**Comment by filipesilva** [comment]
There is a local typings install that is not yet updated to the latest typings version. 

To run the local one, you can either do `npm install`, `npm run postinstall` or `$(npm bin)/typings install`.

We plan to update to the latest one though.

**Comment by alexkibler** [comment]
Ahh, that would do it.  Since typings doesn't obey the npm proxy rules, I have to set up a .typingsrc with rejectUnauthorized:false, but since that's not there at the start of a new project, it wasn't able to run typings.  Thanks!

**Comment by jesperronn** [comment]
For other readers: Please not that the change from `ambient` to `global` is held back for now for the reasons explained by @filipesilva  in https://github.com/angular/angular-cli/issues/816#issuecomment-223760011
> We're actually holding off on the typing 1.0 upgrade for now, because we're aiming at moving directly to @types and don't want to do two typings related breaking changes in a row.
