### ISSUE TITLE
Sass file import in every component creating duplicate copies of sass file data on run time

### ISSUE THREAD

**Issue by amareshteja** [angular/angular-cli#8431]
I'm trying to use Sass with angular 4. like this, 
`@import "~assets/css/svg-icons";`

Everything works fine. But the problem is, I've to import same sass file in every component individually (In both _parent_ and _child_ components). 
So on compile time **angular-cli** injecting complete content of `svg-icons.scss` file, in every component with some attribute appended to all the classes of that file, like `.view-icon[_ngcontent-c1]`, `.view-icon[_ngcontent-c2]`.

So, If there is 100 lines of code in `svg-icons.scss`, and If I import it in 10 components, It'll be 1000 lines of duplicated code, which will be injected to `index.html`, on run time. I don't want this duplication of code as this increases the size of the file exponentially. How can I resolve this?

**Comment by Ristaaf** [comment]
This is basic sass behaviour, you should never import things that result in css several times (sass files imported into component should typically only contain variables, mixins and functions). If you need your import to happen only once, add it to the styles part of .angular-cli.json. (btw the attribute part of the css rules are from having your angular components encapsulated (on by default) this is to make sure that your css in a component does not apply to anything outside your component).

**Comment by david-bulte** [comment]
But if you need something from another scss file in the component.scss file, how would you accomplish this without an import?
