### ISSUE TITLE
ng generate component creates component with default ViewEncapsulation as None

### ISSUE THREAD

**Issue by ayush987goyal** [angular/angular-cli#8433]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Angular CLI: 1.5.0
Node: 7.6.0
OS: win32 x64
Angular:
...

### Repro steps.

Generate a new project.
Generate a component in the project. The component will have ViewEncapsulation set to None

### Desired functionality.

 ViewEncapsulation should not be set to None by default.

**Comment by rafaelss95** [comment]
I'm facing the same issue.

**Comment by rafaelss95** [comment]
Duplicate #8398.

**Comment by banarsiamin** [comment]
npm uninstall -g angular-cli @angular/cli
npm cache clean
npm install -g @angular/cli
