### ISSUE TITLE
Build time error

### ISSUE THREAD

**Issue by praveenbm9321** [angular/angular-cli#8435]
npm run build:prod  takes more than 1 hr or it will hang at 92% 
### Bug Report or Feature Request (mark with an `x`)
```
npm run build:prod takes more than 1 hr or it will stops at 92%
```

**Comment by Brocco** [comment]
@praveenbm9321 I'm sorry to hear you're having this issue. Unfortunately you have not provided any information to allow us to assist you with your issue.

Please open an issue with more information about your environment and project that will allow us to assist you.
