### ISSUE TITLE
angular not installing its components

### ISSUE THREAD

**Issue by samuelvelter2** [angular/angular-cli#8437]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Windows 7 64 bit, node v6.11.4, npm 3.10.10

### Repro steps.
npm install angular, npm install angular-fire, basicly angular is not installing

### The log given by the failure.

+-- UNMET PEER DEPENDENCY @angular/common@5.0.0
+-- UNMET PEER DEPENDENCY @angular/core@5.0.0
+-- UNMET PEER DEPENDENCY @angular/platform-browser@5.0.0
+-- UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@5.0.0
`-- UNMET PEER DEPENDENCY firebase@4.6.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN angularfire@2.3.0 requires a peer of firebase@3.x.x but none was installed.
npm WARN angularfire2@5.0.0-rc.3 requires a peer of @angular/common@^4.0.0 but none was installed.
npm WARN angularfire2@5.0.0-rc.3 requires a peer of @angular/core@^4.0.0 but none was installed.
npm WARN angularfire2@5.0.0-rc.3 requires a peer of @angular/platform-browser@^4.0.0 but none was installed.
npm WARN angularfire2@5.0.0-rc.3 requires a peer of @angular/platform-browser-dynamic@^4.0.0 but none was installed.
npm ERR! code 1

**Comment by Ristaaf** [comment]
So how is this in any way related to angular-cli?

**Comment by GTrismegisto** [comment]
I have the same issue and didn't find a way to solve it.

**Comment by hodorIsComing** [comment]
Are you using the native windows command or another one ? (ex : Atom command prompt).

**Comment by Brocco** [comment]
Installing dependencies and libraries via npm is not a bug for the CLI.

Please ensure the versions of libraries you are installing align with other libraries you are using.
