### ISSUE TITLE
commands to auto edit generated elements

### ISSUE THREAD

**Issue by amineparis** [angular/angular-cli#8440]
It would be great if we can add a parameter when creating a service that indicated that we want http service to be imported in the file and added to constructor parameters as private since it is a recurrent need. we can have the same with a command that auto edit components to integrate a service without manually editing 10 components to import and add the same service each time. this is a general idea (**auto edit** not just generate fresh files). But i didn't think yet about the proper implementation.

**Comment by Brocco** [comment]
I understand this request; however, in light of custom schematics and the difficulties of deciding upon the location of any specified imports would be quite complicated and would likely not be implemented by the default schematics.

I will leave this open for discussion, but my initial reaction is that this would not be something taken on by the default schematics.
