### ISSUE TITLE
OS runs out of memory while building with large assets

### ISSUE THREAD

**Issue by Pacoup** [angular/angular-cli#8447]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

**OS:** Windows 7
**CLI:** 1.5
**Node:** 8.9.1
**npm:** 5.5.1

#### package.json
``` json
{
  "name": "video-viewer",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "dev": "ng build --dev -bh=./",
    "build": "ng build --prod -bh=./",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}
```

### Repro steps.

Pretend that you have a special Angular app meant to act as a simple video kiosk in an offline application. Because the video files are very large (in this case totaling 29.9 GB), they are not checked in Git. Instead, the videos are copied in the assets directory after cloning the repo.

Obviously, this is fairly atypical. In a normal situation, you wouldn't serve your videos directly from the asset directory. But here, the app must run locally without a server since the kiosks have no active Internet connection.

Run `npm run start` (`ng serve`) during development and you would expect the assets to be served normally.

However, what happens is during the asset optimization phase, the node process takes up gigabytes of memory until the operating system runs out, and, in Windows' case, the OS crashes with a blue screen.

This happens in with both `ng serve` and `ng build`, so I'm assuming the files are somehow loaded in memory in full during the process (the system I work with only has about 17 GB of available commit charge (physical + swap in Windows).

### The log given by the failure.

No relevant log, the system runs out of memory and crashes.

### Desired functionality.

The build process should handle large assets gracefully.

Could something about this be done about this in Webpack?

**Comment by clydin** [comment]
`ng serve` builds the application into a memory file system which is then served via a development server.  This is designed to provide an efficient and fast development experience.  30GB worth of files will obviously not fit into 17GB of memory hence the crash.
For an atypical scenario such as this, the large files should probably not be treated as application assets.  This is for several reasons:
* moving and keeping 10's of GB of data in RAM is problematic (especially when the RAM is not available)
* each `ng build` would make a new complete copy of all the application assets in the output directory. (not good for hard drive longevity)
* In this case, the hard drive space required would be 3 times the large file(s) size (original location, copy in assets directory, copy in output directory)

An alternative for development would be to run a standalone http server that would serve the large files without any copying and use a proxy config with the CLI to mimic a production environment ([documentation here](https://github.com/angular/angular-cli/wiki/stories-proxy)).
An alternative for production, would be to do a two stage deployment; built application first then large files directly to the final destination.

**Comment by Pacoup** [comment]
Yeah, I figured. My solution was to put the videos in the root of the project, and call them with a parent directory command (e.g. `src="../videos/some_video.mp4"`), such that the index context in `/dist` can successfully find them, even though they're out of the build process and local (the build is deployed with the `--base-href=./` flag), but this only works with `ng build`.

Using `ng serve`, the `--base-href=./` breaks asset paths for the compiled js files, and without using that flag, since there is no dist directory using serve, the browser evidently can't find the video files.

I don't imagine there's a point in changing `ng serve` for this since you can easily use `--watch` with ng build, and there's no point in adapting the webpack build script, since copying or moving the video files on each build hardly make sense either, so I'm closing this. Not exactly a real bug.
