### ISSUE TITLE
Angular 5 separate locale data in own chunk so vendor chunk is same across builds with other locales

### ISSUE THREAD

**Issue by smoke** [angular/angular-cli#8448]
### Bug Report or Feature Request (mark with an `x`)
```
- [?] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

`ng --version`
```
Angular CLI: 1.5.0
Node: 8.9.1
OS: linux x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1
```

`node --version`
```
v8.9.1
```

`npm --version`
```
5.5.1
```
### Desired functionality.

The use case is - I have an application with multiple languages, so to optimize loading times and files served I do separate language builds, that are then combined into one directory replacing same files.
With simplified code just to make sense I do:
 - `ng build --prod --vendor-chunk --locale 'es-ES' --output dist/es; ng build --prod --vendor-chunk --locale 'es-ES' --output dist/fr`. 
 - `mv dist/es/index.html dist/es/es.html; mv dist/fr/index.html dist/fr/fr.html;`
 - `cp -a dist/{es,fr}/* dist/combined/`

The results in `dist/combined/` is optimal set of files like the following:
```
es.html <-- language specific
fr.html <-- language specific
main.{es-hash}.bundle.js <-- language specific
main.{fr-hash}.bundle.js <-- language specific
vendor.{common-hash}.bundle.js  <-- language agnostic
styles.{common-hash}.bundle.css  <-- language agnostic
polyfills.{common-hash}.bundle.js  <-- language agnostic
assets/* <-- language agnostic
...   <-- language agnostic
```

This was working perfectly fine with Angular 4 and angular-cli < 1.5.0 but I assume since integration of https://angular.io/guide/i18n and mainly the ability to embed the locale data automatically, my project ends with language specific vendor.bundle.js, that is quite a burden to load (size is MBs).
However since Angular 5 and angular-cli 1.5.0 this is not the case any more.

Given automatic embedding of locale data is quite awesome (thanks!) - what I would like to see implemented is additional chunk for that language specific data (only locale data for now?) so that vendor.bundle.js and others that are capable, to result in language agnostic files, therefor end up in one and can be utilized regardless of the language.

**Comment by alan-agius4** [comment]
Hi @smoke, 

Thanks for this feature request.  This currently doesn't warrant to be supported directly by Angular CLI seeing the little interest this issue received from the community.
