### ISSUE TITLE
 C:\realApp\node_modules\istanbul-reports\node_modules\handlebars\bin\handlebars

### ISSUE THREAD

**Issue by raimialiu** [angular/angular-cli#8449]
This is all what i got when trying to install new angular project from angular cli using ng new projectName

npm ERR! path C:\realApp\node_modules\istanbul-reports\node_modules\handlebars\bin\handlebars
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\realApp\node_modules\istanbul-reports\node_modules\handlebars\bin\handlebars'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tragee\AppData\Roaming\npm-cache\_logs\2017-11-10T18_43_48_963Z-debug.log

Package install failed, see above.
Package install failed, see above.

**Comment by Brocco** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue following the new issue template if the problem you are experiencing isn't known.
