### ISSUE TITLE
Version flag in new command

### ISSUE THREAD

**Issue by cmckni3** [angular/angular-cli#8455]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

The option `--version` shows in the `ng new` help section. It does not appear to do anything when creating a new project. This option may be from the version command.

### Versions.

```
Angular CLI: 1.5.0
Node: 8.9.1
```

### Repro steps.

```bash
ng new --help
```

### The log given by the failure.

```
ng new [name] <options...>
    --dry-run Run through without making any changes. Will list all files that would have been created when running "ng new".
...
    --version (string)
...
```

### Desired functionality.

Not sure

**Comment by Brocco** [comment]
This is a flag accepted by the new application schematic to specify which version of the CLI for the new project to use.

It is not a value you need to set as the CLI automatically handles this for you.
