### ISSUE TITLE
Ability to configure minChunks for common chunk

### ISSUE THREAD

**Issue by aksyonov** [angular/angular-cli#8458]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
```
Angular CLI: 1.5.0
Node: 8.6.0
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/flex-layout: 2.0.0-beta.10
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.31
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
typescript: 2.4.2
webpack: 3.8.1
```

### Desired functionality.
I would like to configure [minChunks](https://github.com/angular/angular-cli/blob/00ca690807a2326b6e8632a9a0ec46587b841a78/packages/%40angular/cli/models/webpack-configs/browser.ts#L70) parameter for common chunk e.g. in `angular-cli.json` file, without having to eject the angular webpack.config.js file.

### Mention any other details that might be useful.
For example if two of my lazy-loaded modules have some common huge dependency it'll end up in common chunk and will be loaded with all lazy-loaded modules in application. If I could set minChunks to 3, common chunk will be much smaller.

**Comment by clydin** [comment]
The common chunk functionality is significantly more advanced in the latest version of the CLI (6.x+) and will no longer create a massive single common chunk.

**Comment by adamdport** [comment]
@clydin is there anywhere we can read about its approach? [The docs](https://github.com/angular/angular-cli/wiki/build) still just say

> `--common-chunk`
>  Use a separate bundle containing code used across multiple bundles.

**Comment by clydin** [comment]
There's no official documentation but here is a comment I wrote providing some background on the new behavior: https://github.com/angular/angular-cli/issues/10364#issuecomment-382040140
