### ISSUE TITLE
Feature Request: Integrate webpack Closure Compiler Plugin

### ISSUE THREAD

**Issue by josephliccini** [angular/angular-cli#8459]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

I am guessing you guys have already looked into this, but just in case you haven't, it looks like the webpack team has begun putting together a Closure Compiler plugin.

It would be great to be able to see this integrated into the cli, even just as an experimental option.  

This would also be great for those who have been invested heavily into webpack build pipeline, and still reap benefits of Closure and Angular.  

It could even be an intermediate step for moving to full Angular-Bazel-Closure, as folks could familiarize themselves with Closure, before moving on to Bazel from webpack.

https://github.com/webpack-contrib/closure-webpack-plugin

### Mention any other details that might be useful.

Happy to help dogfood something like this.

Thanks for all the great features and work so far!!

**Comment by hansl** [comment]
This is out of scope with what we can support and want to do. We're currently working at making the existing toolchain better.
