### ISSUE TITLE
Documentation on Custom Blueprint Engine 

### ISSUE THREAD

**Issue by LmKupke** [angular/angular-cli#8460]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
```

### Versions.

`node --version`: 6.10 
`npm --version`: 3.10.2
  Windows (10)

### Desired functionality.

What would like to see implemented?
I would love for some documentation on the Angular CLI Custom Blueprint engine. The feature for it has been released for a while and yet there is no documentation on how to use this feature.

**Comment by LmKupke** [comment]
@Brocco @hansl any update on this?

**Comment by filipesilva** [comment]
Heya, nowadays we have official docs for schematics in https://angular.io/guide/schematics so I think this can be closed.
