### ISSUE TITLE
Angular Cli-1.5.0 creating double the size of styles.bundles.css than Angular Cli-1.3.0

### ISSUE THREAD

**Issue by renilbabu03** [angular/angular-cli#8462]
I have updated my Angular cli to version 1.5.0 but when I did `ng serve` it is showing triple the size when the same is done using Angular cli 1.3.0. Why is such huge difference ? Am i missing something..? And in the css i only have font awesome and bootstrap.

> ng serve using Angular 1.5.0--> Pls check the size of styles.bundles.css
![2017-11-12](https://user-images.githubusercontent.com/18526147/32713766-c0a93b60-c870-11e7-903f-543388b3a0fc.png)

> ng serve using Angular 1.3.0 --> Pls check the size of styles.bundles.css
![small](https://user-images.githubusercontent.com/18526147/32713792-d864508c-c870-11e7-8252-6026242ee042.png)

I wan't to know why is the latest version of Angular Cli creating huge styles.css file

**Comment by filipesilva** [comment]
We optimize the bundles in `ng serve` for rebuild speed, and part of that is including the sourcemaps directly in the javascript bundle. That is what makes the bundle bigger. 

This optimization doesn't happen in `ng build` nor in `ng serve --prod` so it should not impact your production builds at all.
