### ISSUE TITLE
Autocomplete component is not rendering on server (SSR)

### ISSUE THREAD

**Issue by rlyawesome** [angular/angular-cli#8464]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Angular CLI: 1.5.0
Node: 8.4.0
OS: win32 x64
Angular: 5.0.1

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.
I'm trying to build and run my project on server, using @angular/material: 5.0.0-rc0, but it fails.

### The log given by the failure.
The message is `ReferenceError: window is not defined`.

### Desired functionality.
I've found the reference to window in autocomplete component (autocomplete.spec.ts), it should be universal.

**Comment by maxisam** [comment]
I don't think it has anything to do with AngularCLI. You can't reference Window in SSR. Run search on Stackoverflow and you will find a lot of solution.

**Comment by rlyawesome** [comment]
Oh sorry, i'll copy this to @angular/material2 issues. I think it can be
closed there.
