### ISSUE TITLE
Reload after fesm library build

### ISSUE THREAD

**Issue by moohkooh** [angular/angular-cli#8466]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report 
- [ ] feature request
```

### Versions.
Angular CLI: 1.5.0
Node: 8.6.0
OS: darwin x64
Angular: 4.3.6
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, tsc-wrapped

angular/cli: 1.5.0
angular-devkit/build-optimizer: 0.0.32
angular-devkit/core: 0.0.20
angular-devkit/schematics: 0.0.35
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.8.0
schematics/angular: 0.1.2
typescript: 2.5.2
webpack: 3.8.1

### Repro steps.
1) Create new project via ci (App-Project). 
2) Create other project as fesm project (FESM-Module). 
3) build and create create link `npm link` (inside dist folder) for the fesm module
4) link fesm module inside your App-Project. 
5) start App-Project with `ng serve`

### Desired functionality.
After rebuild fesm module, angular cli project will not reload and get the new changes. In some cases (i dont get which one), angular cli get the changes and starts a rebuild. We are using a few fesm modules and its really hard to restart the the app-project to get the changes from fesm module (round - trips > 1minute).

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by mgechev** [comment]
Closing it due to inactivity. If the problem is still reproducible with the latest CLI, please open a new issue following the template and sharing a minimal demo where we can reproduce it. Thank you! :)
