### ISSUE TITLE
service-worker

### ISSUE THREAD

**Issue by TxOne** [angular/angular-cli#8477]
### Bug Report or Feature Request (mark with an `x`)
```
The installed version of @angular/service-worker is 5.0.1. This version of the CLI
requires the @angular/service-worker version to satisfy >= 1.0.0-beta.5 < 2.0.0. Please upgrade
your service worker version.
```

### Versions.

1.5.0

**Comment by laiwf94** [comment]
same errors after install service worker

**Comment by josegus** [comment]
Same here. Looks like this version of the angular cli is not ready to work with the actual service worker package

**Comment by jrubiocap** [comment]
Same error here, hope to fix soon.

**Comment by mariusl-a** [comment]
Anything new regarding this? Still not fixed in version 5.0.3 it seems.
Any workaround? :) Thanks!

**Comment by laiwf94** [comment]
It is now added to the angular 1.6 version which is not stable. 

You should be able to get that by command - 
$ npm install -g @angular/cli@next

And run ng - - version
You will see Angular CLI version 1.6.0-rc.0

**Comment by mariusl-a** [comment]
That worked @laiwf94  - Thanks!

**Comment by laiwf94** [comment]
No problem. Just bear in mind that this version is not stable.
