### ISSUE TITLE
Build process broken with upgrade 1.4.9 => 1.5

### ISSUE THREAD

**Issue by nicodh** [angular/angular-cli#8479]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

macOS (Sierra 10.12.16)
Angular CLI: 1.5.0
Node: 6.9.5
OS: darwin x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.6.1
webpack: 3.8.1

I also tried typescript 2.4.2

### Repro steps.

After upgrading I had to fix some Typescript issues but then I could run "ng serve" and my application is working on localhost.
But when I run ng build --prod there is no vendor bundle created and no error message is given, even in -vvv verbose mode!
I could fix that with the --no-build-optimizer flag, but the generated code is not working:
I get an "TypeError: Cannot read property 'subscribe' of undefined" in vendor.bundle.js...

### The log given by the failure.

With typescript 2.4.2 I get an error:
ERROR in ./node_modules/rxjs/_esm5/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined

### Desired functionality.

If everything is fine with "ng serve" the build process should not break the application

### Mention any other details that might be useful.

I use also RxJS and ngrx in my project. 
I had some issues with RxJs operators, since they have to be imported explicit now and the error in the generated bundle might somehow relate to that (since it tries to call subscribe on undefined...)
But thats just a guess...

Here are my dependencies:
"dependencies": {
    "@angular/animations": "^5.0.1",
    "@angular/forms": "^5.0.1",
    "@angular/http": "^5.0.1",
    "@angular/platform-browser": "^5.0.1",
    "@angular/platform-browser-dynamic": "^5.0.1",
    "@angular/router": "^5.0.1",
    "@ngrx/router-store": "^4.1.1",
    "@ngrx/store-devtools": "^4.1.1",
    "core-js": "^2.5.1",
    "ngx-pipes": "^2.0.5",
    "node-sass": "^4.6.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.0",
    "@angular/common": "^5.0.1",
    "@angular/compiler": "^5.0.1",
    "@angular/compiler-cli": "^5.0.1",
    "@angular/core": "^5.0.1",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^4.1.1",
    "@ngrx/store": "^4.1.1",
    "@swimlane/ngx-datatable": "github:swimlane/ngx-datatable",
    "@types/jasmine": "2.5.53",
    "@types/node": "^8.0.51",
    "bootstrap-sass": "^3.3.7",
    "codelyzer": "^4.0.1",
    "jasmine-core": "2.7.0",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "1.7.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.6.0",
    "mydatepicker": "^2.5.0",
    "ng2-pipes": "^2.0.1",
    "protractor": "~5.1.2",
    "rxjs": "^5.5.2",
    "ts-node": "3.3.0",
    "tslint": "^5.8.0",
    "typescript": "^2.4.2"
  }

**Comment by nicodh** [comment]
I just renamed the issue since i tested it with version 1.4.9 and it still worked as expected

**Comment by ToKaDev** [comment]
Same issue here.

**Comment by PillowPillow** [comment]
Possible duplicate of #8422

**Comment by nicodh** [comment]
@PillowPillow I don't think so. I have no dots at alls in my directory names and the build process is not crashing but just skipping the vendor bundle.
And with --build-optimizer=false all bundles are created but they don't work...

**Comment by nicodh** [comment]
I tried again with Angular Cli 1.5.5 and now it worked as expected!

**Comment by riginoommen** [comment]
Same issue here instable build process
