### ISSUE TITLE
Context for Karma and build is different

### ISSUE THREAD

**Issue by Karasuni** [angular/angular-cli#8482]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

I've noticed that the normal cli build and the compilation for karma use a different typing context. This difference makes it impossible to create a single codebase that can build (`ng build`) and test (`ng test`) without error.

### Versions.

```
Angular CLI: 1.5.0
Node: 7.1.0
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.

1. Create a new project: `ng new my-project`

2. Add the version variable from `package.json` to the environment objects as 
```typescript
// src/environments/environment(.prod).ts

import * as packageJSON from '../../package.json';

export const environment = {
  //  ...
  version: packageJSON.version
};

// Alternatively

export const environment = {
  //  ...
  version: require('../../package.json').version
};
```

3. Building the code will fail (`ng build`, `ng build --prod`):

```
// npm build (using require)

ERROR in src/environments/environment.ts(3,12): error TS2304: Cannot find name 'require'.
src/environments/environment.prod.ts(3,12): error TS2304: Cannot find name 'require'.

// npm build (using import)

ERROR in src/environments/environment.prod.ts(1,30): error TS2307: Cannot find module '../../package.json'.
src/environments/environment.ts(13,30): error TS2307: Cannot find module '../../package.json'.
```

4. The tests (`ng test`) however will not fail.

This leads to the conclusion that the context is not the same for the test and build script.

**Comment by filipesilva** [comment]
You're right, the behaviour should be consistent.

The reason why `require` doesn't work in `ng build` but works in `ng test` is that they use different typings. If you open `src/tsconfig.spec.json` you will see it imports `node` typings (which include `require`). This is needed for `test.ts`.

I'm not sure what's happening with `import` though.

**Comment by alan-agius4** [comment]
JSON files are not ES6 modules hence it cannot be imported using ES6 imports. To allow JSON Imports you'd need to enable Typescript's `resolveJsonModule` compiler option.

See: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#new---resolvejsonmodule
