### ISSUE TITLE
Angular v5.0.1 library only works in AOT

### ISSUE THREAD

**Issue by avergos29** [angular/angular-cli#8486]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.5.0
node: 6.11.1
os: win32 x64
@angular/animations: 5.0.1
@angular/common: 5.0.1
@angular/compiler: 5.0.1
@angular/core: 5.0.1
@angular/forms: 5.0.1
@angular/http: 5.0.1
@angular/platform-browser: 5.0.1
@angular/platform-browser-dynamic: 5.0.1
@angular/router: 5.0.1
@angular/cli: 1.5.0
@angular/compiler-cli: 5.0.1
@angular/language-service: 5.0.1
typescript: 2.4.2

### Repro steps.
I'm building a custom library based on angular (4.4.6).
And I'm using it in an Angular CLI application.

Right now, the application works both in --aot and dev mode.
for dev mode i have to add the --preserve-symlinks flag.

I'm trying to upgrading the library (and the app) to angular 5.0.1.

But after that, dev mode doesn't work any more.
In the browser console, i get this message:

### The log given by the failure.
 ```
Uncaught Error: Unexpected value 'XxModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.js:466)
    at compiler.js:15088
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:15071)
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules (compiler.js:33486)
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:33447)
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAsync (compiler.js:33363)
    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:230)
    at PlatformRef.webpackJsonp.../../../core/esm5/core.js.PlatformRef.bootstrapModule (core.js:5446)
    at Object.../../../../../src/main.ts (main.ts:11)
syntaxError @ compiler.js:466
(anonymous) @ compiler.js:15088
webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata @ compiler.js:15071
webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules @ compiler.js:33486
webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndComponents @ compiler.js:33447
webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAsync @ compiler.js:33363
webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync @ platform-browser-dynamic.js:230
webpackJsonp.../../../core/esm5/core.js.PlatformRef.bootstrapModule @ core.js:5446
../../../../../src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap a5f09cf9d3417cf94332:54
0 @ main.bundle.js:30347
__webpack_require__ @ bootstrap a5f09cf9d3417cf94332:54
webpackJsonpCallback @ bootstrap a5f09cf9d3417cf94332:25
(anonymous) @ main.bundle.js:1
```

### Mention any other details that might be useful.
Please note I have the same error in v4.4.6 without the --preserve-symlinks

I also modified src/app/tsconfig.app.json adding:
```
    "baseUrl": "",
    "paths": {
      "@angular/*": ["../node_modules/@angular/*"]
    }
```
with no effect

**Comment by alexzuza** [comment]
Can you provide minimal reproduction?

**Comment by awptt** [comment]
I had the same problem with my library build. The cause for me was that my typescript was to new so that ‘ngc’ did not include the decorators. With ‘typescript": "~2.4.2"’, everything works fine for me.

**Comment by avergos29** [comment]
indeed i was using typscript 2.5.2. downgrading to 2.4.2 fixed the issue 
thank you !!

**Comment by bentedder** [comment]
I've downgraded to typescript 2.4.2, am using webpack 3.8.1, exporting a "umd" library, have npm link'ed my local library and removed its node_modules folder, but still every time I try to import the library I generate I get the same `Please add a @NgModule annotation.` message. Been all over the internet looking for an answer but still can't seem to fix it.
