### ISSUE TITLE
Required config option to add/remove dynamic content (ajax calls)  from anuglar-cli service worker

### ISSUE THREAD

**Issue by saxena-ashutosh** [angular/angular-cli#8491]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.4.3
node: 6.10.1
Windows 10
os: win32 x64
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/service-worker: 1.0.0-beta.16
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.6
typescript: 2.4.2

### Desired functionality.

Config option required to configure dynamic content(ajax calls) in angular-cli service worker like the one we have in workbox. Currently we need to eject cli project to use workbox and sometimes there is need to use cli commands.

**Comment by alan-agius4** [comment]
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
