### ISSUE TITLE
Ng is not recognized

### ISSUE THREAD

**Issue by rajeshbattula631** [angular/angular-cli#8492]
how to solve 'ng' is not recognized as an internal or external command, operable program or batch file.?

please help me in this. what can i do?

**Comment by deebloo** [comment]
@rajeshbattula631 this would mean that the cli did not install correctly. Did you get an error message during installation?

**Comment by jongear** [comment]
@rajeshbattula631 if you attempt `ng -v` what does your terminal return

**Comment by Brocco** [comment]
If `ng` is not recognized as a command then it either did not install correctly or something is not configured appropriately.

With that being said, this is not really an issue for the cli itself, so I am closing this issue.
