### ISSUE TITLE
ng build --prod as default

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#8493]
```
- [x] feature request
```

### Desired functionality.
What about make`ng build`  building production `--prod` by default ?

**Comment by xtreemrage** [comment]
Why not an npm script? E.g. `npm run build:prod`.
```json
    "scripts": {
        ...
        "build:prod": "ng build --prod",
        ...
    }
```

**Comment by istiti** [comment]
Thanks, but it is feature request not bug->workaround
Questions should be:
Why not put `--prod` as default on `ng build` ? 
What users often expects, what is common use of `ng build` ? 

I think it could be more user friendly as `cordova build ios`.
We rarely need not minified/not aot on "build" step.

ps: `ng build --prod=false` should do actual `ng build`

**Comment by hansl** [comment]
Hi @istiti,

Thanks for the feature request. This is not something we're interested in. Users are still using `ng build` and using their own backend, for development purposes (e.g. with ASP.Net projects). I would think more users are using `ng build` than `ng build --prod`, which would lead to a breaking change for too many people.

I'm going to close this as it's not something we want to do. The positive is that we're considering `ng deploy` soon which would solve this, as it would do a prod build.
