### ISSUE TITLE
ng eject is not platform-agnostic

### ISSUE THREAD

**Issue by mwager** [angular/angular-cli#8497]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
```

### Versions.

```
Angular CLI: 1.5.0
Node: 8.4.0
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.3
typescript: 2.4.2
webpack: 3.8.1

```

### Repro steps.

On Windows 10:

Run `ng new some-project` and then `ng eject --force`

On mac:

```
npm run build

... lots of errors

Child html-webpack-plugin for "index.html":
    
    ERROR in Entry module not found: Error: Can't resolve '/private/tmp/tmp-project/src\index.html' in '/private/tmp/tmp-project'

```

Seems like its related to the paths like this:

```
"include": [
          path.join(process.cwd(), "src\\styles.css")
        ],
```

### Desired functionality.

The generated config should be platform-agnostic

### Mention any other details that might be useful.

Also see #8495

**Comment by MihirGandhi03** [comment]
I have updated angular-cli to 1.6 on Mac. After updating when i ejected the webpack file, all **back slashes (" \ ")** were replaced by **forward slashes (" / ")**.
Eg :  
```javascript
"include": [path.join(process.cwd(), "src/styles.css")], 
```
This file is working for both platforms (Mac and Windows).

**Comment by hansl** [comment]
Closing this as it seems to be fixed.
