### ISSUE TITLE
Using/discovering/linking customized schematics for scaffolding apps

### ISSUE THREAD

**Issue by blkdog** [angular/angular-cli#8503]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### Versions.
@latest

### Repro steps.
`ng new --collection=@scope/collection mynewapp`

### Desired functionality.
I'd like to be able to give the tool an assigned npm package (installed globally or not) & have the tool scaffold a project that contains all my customizations

This custom package may be any of: an NPM package, a local or linked NAS location.

Additionally I'd like to see an option, i.e `ng link @scope/collection` that would link a customized schematics collection that is installed globally (kinda the way `npm link` works)

**Comment by hansl** [comment]
I think this is supported in the `--collection` argument, otherwise this is not something we want to do. For debugging purposes, please use the `schematics` CLI directly.
