### ISSUE TITLE
Using CDN in production

### ISSUE THREAD

**Issue by davidmorissette** [angular/angular-cli#8504]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

My application lazy loads different modules and has to deal with different chunk files in order to accomplish that. My problem concerns the loading of these files. How can I load these files from my CDN?

These file I have control:
![image](https://user-images.githubusercontent.com/5100885/32857004-789b6d7a-ca14-11e7-8f36-584b9f26b436.png)

The chunk files, how can I configure them?
![image](https://user-images.githubusercontent.com/5100885/32857016-804bbeb2-ca14-11e7-971c-b7b8229b0a55.png)

Thank you!

**Comment by josephliccini** [comment]
```ts
    __webpack_public_path__ = cdnDomain;
```

Do this before bootstrapping.

**Comment by davidmorissette** [comment]
Using the public path was the solution, thank you!

**Comment by tommck** [comment]
aren't they planning on removing webpack eventually?

If so, then this is just a short term hack fix
