### ISSUE TITLE
AngularDoc for Visual Studio Code can't used in angular-cli V1.5

### ISSUE THREAD

**Issue by liugang1988** [angular/angular-cli#8510]
AngularDoc for Visual Studio Code can't used in angular-cli V1.5

**Comment by liugang1988** [comment]
I can't use 'ng generate component myComponent' to create a new component in angular-cli V1.5!

Error: ELOOP: too many symbolic links encountered, stat 'F:\work\myProject\node_modules\._@angular_cli@1.5.0@@angular\cli\node_modules\webpack\node_modules\escope\node_modules\es6-map\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext'

**Comment by hansl** [comment]
This is a problem with Schematics. The next version should not try to read all the files, so I'll mark this as fixed.
