### ISSUE TITLE
ng build results in error TS2554: Expected 0 arguments, but got 1.

### ISSUE THREAD

**Issue by Sami-L** [angular/angular-cli#8514]
- [x] bug report

After upgraded to Angular CLI 1.5.0
**ng build command** resulted in the follwing error:
**ERROR in app/app-error.handler.ts error TS2554: Expected 0 arguments, but got 1.**

### Versions.

> Angular CLI: 1.5.0
> Node: 8.9.0
> OS: win32 x64
> Angular: 5.0.1
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, platform-server, router
> @angular/cdk: 5.0.0-rc0 
> @angular/cli: 1.5.0 
> @angular/material: 5.0.0-rc0 
> @angular-devkit/ build-optimizer: 0.0.33 
> @angular-devkit/ core: 0.0.20 
> @angular-devkit/ schematics: 0.0.35 
> @ngtools/ json-schema: 1.1.0 
> @ngtools/ webpack: 1.8.0 
> @schematics/ angular: 0.1.3 
> typescript: 2.6.1 
> webpack-hot-middleware: 2.19.1 
> webpack-merge: 4.1.0 
> webpack: 3.6.0 

When checking the app-error.handler.ts , the line:
 
`import { Injectable, ErrorHandler } from '@angular/core';`

has "**Injectable**" and "**Error handler**" underlined with the errors:

> [ts] Module '"c:/...../node_modules/@angular/core/core"' has no exported member 'Injectable'.

> [ts] Module '"c:/...../node_modules/@angular/core/core"' has no exported member 'ErrorHandler'.

Update:

After a machine reboot, the words  "**Injectable**" and "**Error handler**" were not underlined but this time it was the argument "**super(true)**" in the constructor below:

```
    constructor() {
        super(true);
    }:
```
Here the error is:  
`constructor ErrorHandler(): ErrorHandler`

**Comment by clydin** [comment]
This doesn’t appear to be related to the CLI.  The constructor being called doesn’t take an argument.  Remove the ‘true’ from the super call.

**Comment by Sami-L** [comment]
Removing the ‘true’ from the super call releases the error, but I wonder why it is supplied originally with 'true' if I have to remove it.

**Comment by clydin** [comment]
That file doesn't exist in a newly generated project.
The constructor parameter was deprecated in Angular 4 and removed in Angular 5.

**Comment by hansl** [comment]
As @clydin pointed out, the constructor parameter was removed in Angular 5. I'm closing this as solved/answered.

**Comment by DeepzSandra** [comment]
Hi ,
how to solve this problem any body help me.
using Angular2
Error TS2554: Expected 3 arguments, but got 0.

**Comment by durjoy28** [comment]
error TS2554: Expected 2 arguments, but got 1.

Here sign(myForm){
      if(myForm.valid){
      this.af.auth.createUserWithEmailAndPassword({  //here is the problem
      email:this.email,
      password:this.password
      }).then(
      (success)=> {
      console.log(success);
      this.router.navigate(['/login'])
      }).catch(
      (err)=> {
       console.log(err);
       this.error=err;
      })
      }
    }

**Comment by eternalsayed** [comment]
@durjoy28 : It so appears that your createUserWithEmailAndPassword function is expecting two parameters whereas you're sending an object, which is 01 parameter. Try sending the email and password as individual parameters, maybe?

**Comment by vishnuBoppani** [comment]
error TS2554: Expected 2 arguments, but got 1.

onFormSubmit(form:NgForm) {
    this.api.updateBook(this.id, form)
      .subscribe(res => {
          let id = res['_id'];
          this.router.navigate(['/book-details', id]);
        }, (err) => {
          console.log(err);
        }
      );
  }

**Comment by armandohuarcaya** [comment]
ERROR in src\app\modules\configuration\external-system\containers\external-system-home.component.ts.ExternalSystemHomeComponent.html(2,33): : Expected 0 arguments, but got 1.

**Comment by fflores-origin** [comment]
> ERROR in src\app\modules\configuration\external-system\containers\external-system-home.component.ts.ExternalSystemHomeComponent.html(2,33): : Expected 0 arguments, but got 1.

When this happened to me, I found that it was a function I was calling from the html with a parameter, but in the ts file no parameters were expected.

Example: 
HTML FILE 
`<app-filters (OnClear)="this.clearFilter()">`

TS FILE 
`clearFilter() {....}`

You can see angular says that is on the line 2

**Comment by durjoy28** [comment]
My problem is solved.
