### ISSUE TITLE
Invalid production source maps since 1.5

### ISSUE THREAD

**Issue by Manduro** [angular/angular-cli#8526]
As noted by @hansl in #8218.

### Versions
```
Angular CLI: 1.5.0
Node: 8.8.1
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack-bundle-analyzer: 2.9.0
webpack: 3.8.1
```

### Repro steps
* `ng build --prod --sourcemaps`

### Observed behavior
I'm not aware of a tool to easily check source maps for validity, but they do not work.

Error tracking software Rollbar throws an error for any bundle/chunk sourcemap:
```
Error: Source file(s) "main.b37502fae2a2c9e7facf.bundle.js" do not exist in the given source map!
```

### Desired behavior
Sourcemaps work.

**Comment by mconner** [comment]
I'm also having a problem with prod sourcemaps.  I'm seeing source but the line numbers are off.  I can't set breakpoints in most cases, or if I can, it doesn't actually break there.   Similarly, the line numbers for the css (scss originally) is incorrect.

Angular CLI: 1.5.2
Node: 8.9.1
OS: win32 ia32
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.5.2
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.2
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1

**Comment by Manduro** [comment]
Found a validator at https://sourcemaps.io, lots of errors and warnings!

**Comment by filipesilva** [comment]
@hansl could this be related to your sourcemap changes in 1.5? https://github.com/angular/angular-cli/pull/8230

**Comment by Manduro** [comment]
I found two interesting things in my short investigation:

1. https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/models/webpack-configs/production.ts#L123 says the PurifyPlugin should go before the UglifyJsPlugin, but at the moment it's placed after.
2. https://github.com/webpack/webpack/issues/4388#issuecomment-314827087 mentions UglifyJsPlugin must be before SourceMapDevToolPlugin, but at the moment it's placed after.

The order of these plugins was changed between 1.4 and 1.5, but my tries in manually changing the order of the plugins back did not (completely?) fix this. Reverting #8230 does not fix it either.

**Comment by filipesilva** [comment]
I've a PR for the purify plugin order already https://github.com/angular/angular-cli/pull/8530, but am not aware that the `SourceMapDevToolPlugin` is placed after. Where are you seeing it placed after?

We should be honoring the order in this array https://github.com/angular/angular-cli/blob/c60e8af97784d13a6be8b89de82bf0f134266a8f/packages/%40angular/cli/models/webpack-config.ts#L58-L63

**Comment by Manduro** [comment]
Sorry, my wording was unclear. The comment by the webpack maintainer says "UglifyJsPlugin must be before SourceMapDevToolPlugin".

Uglify is part of `getTargetConfig`, while SourceMap is part of `platformConfig`. Therefore the UglifyJsPlugin is not added *before* the SourceMapDevToolPlugin.

But again, I'm not sure if that fixes anything 😅

**Comment by Manduro** [comment]
My source maps are still not working with cli 1.6. Even when building without the build optimizer.

**Comment by filipesilva** [comment]
@Manduro can you get some some repro steps that I can use to see what you're seeing please?

**Comment by Manduro** [comment]
I can't share the project and I've tried to reproduce this with a clean ng new, but haven't succeeded unfortunately. Do you have an idea where this could go wrong, like a library dependency with a certain build, or anything?

**Comment by filipesilva** [comment]
Well if it is something on the Angular CLI or devkit, I'd first make sure your app and the new app are using the same versions (`npm list @angular-devkit/build-optimizer` and so on). If you have a lock file maybe try deleting it and reinstalling.

If it's a library your app uses, then I'd expect the sourcemap problem to be localized to the bundle where that library is. If it happens across all bundles then it's probably something in the CLI.
