### ISSUE TITLE
ng xi18n not extracting anything

### ISSUE THREAD

**Issue by armandoxxx** [angular/angular-cli#8527]
I followed docs on Angular 5 internationalization and can't figure out what's wrong.
Can someone please explain to me what am I doing wrong ?

### Versions

Angular CLI: 1.5.0
Node: 9.1.0
OS: linux x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router
`@angular/cli: 1.5.0`
`@angular-devkit/build-optimizer: 0.0.32`
`@angular-devkit/core: 0.0.20`
`@angular-devkit/schematics: 0.0.35`
`@ngtools/json-schema: 1.1.0`
`@ngtools/webpack: 1.8.0`
`@schematics/angular: 0.1.1`
`typescript: 2.4.2`
`webpack: 3.8.1`

### Repro steps
> cd project
> ng xi18n
> ng xi18n --output-path=src/locale

### Observed behavior
Nothing happens

### Desired behavior
would like to see extracted translation file.

### Mention any other details that might be useful (optional)
example tags from template i tried with:
`<span class="m-text-big" i18n>Food order&nbsp;-&nbsp;new</span>`
`<span class="m-text-big" i18n="@@foodOrder.title">Food order&nbsp;-&nbsp;new</span>`

**Comment by quanterion** [comment]
The same for me. I'm on Windows 10 x64, Node 8.7 No errors shown but the x18n process takes unusually short time (20-30 secs, it was about 2-3 minutes when this tool works)).

Tried cli 1.5.3 and 1.6.0-beta.2 - the problem remains

**Comment by fpeterdev** [comment]
Same here, it used to work like a charm before, but nothing seems to happen now

**Comment by nikolayr1** [comment]
win10x64 angular 5 same story =(

**Comment by fpeterdev** [comment]
OK, so after some "comment everything and add add back fields step by step" play around I figured out what was the problem with our code: a colleague of mine used a private variable in the template, which is something you shouldn't do. Something like this:
`<mat-error *ngIf="displayMessage.emailAddress">{{displayMessage.emailAddress}}</mat-error>`
(We have some server side validation returning localized error messages.) `displayMessage` was private so my guess is that there was a "Cannot read property 'emailAddress' of null" error during xi18n generation.
So it was definitely our mistake, but I have to say: some (compilation) error message would've been helpful ;)

**Comment by quanterion** [comment]
It looks like the fix is in master https://github.com/angular/angular-cli/pull/8480 but not yet released

**Comment by armandoxxx** [comment]
tops

**Comment by filipesilva** [comment]
#8480 should now be released in `1.6.0-rc.0`. It will also be in the next `1.5.x` release.
