### ISSUE TITLE
ng serve is not working after fresh install - 1.5.2

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [angular/angular-cli#8531]
After successful  creation of new project while starting the project using ng serve command facing below issues.

Versions of @angular/compiler-cli and typescript could not be determined.
The most common reason for this is a broken npm install.

Please make sure your package.json contains both @angular/compiler-cli and typescript in
devDependencies, then delete node_modules and package-lock.json (if you have one) and
run npm install again.

If we try ng -v getting like below

E:\my-project>ng -v

_                      _                 ___ _     __
/ \ _ __ __ _ _ | | _ _ _ / | | | |
/ △ \ | ' \ / | | | | |/ _ | '__| | | | | | |
/ __ | | | | (| | || | | (| | | | || | | |
// __| ||_, |_,||_,|| _||_|
|___/

Angular CLI: 1.5.2
Node: 8.9.1
OS: win32 x64
Angular: 5.0.2
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

@angular/cli: error
@angular/compiler-cli: error
@angular/language-service: error
typescript: error
webpack: error

**Comment by Joryiqfy** [comment]
I get the same issue

**Comment by MjJuneja** [comment]
For the time being you can try npm start. 

for one of the project ng serve didn't work but npm start was working just fine for me.

**Comment by filipesilva** [comment]
Have you tried deleting `node_modules` and running `npm install`? This can happen with a broken install.

**Comment by Joryiqfy** [comment]
I managed to clear this issue by using nvm and installing this version 6.9.0. 
Before reinstalling @angular/cli
Then starting a new app.

**Comment by ottovonzastrow** [comment]
Same issue here. Worked one day stopped the next without installing any updates
Directly running ng serve on new project 
Tried un- and reinstalling angular/cli and npm
Tried next/latest version of ng aswell
at one point it worked again, then suddenly stopped while running with the same error message

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
