### ISSUE TITLE
App doesn't run when built with -prod

### ISSUE THREAD

**Issue by slubowsky** [angular/angular-cli#854]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS? 
Windows 10

2. Versions. 
angular-cli: 1.0.0-beta.5
node: 6.2.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Was built using cli. Added ng2-bootstrap and used some components from it in app component. Added some routes and components using cli

4. The log given by the failure. Normally this include a stack trace and some
   more information.
No failure. Browser loads a few files and just sits forever.

5. Mention any other details that might be useful.
Adding ng2-bootstrap not straightforward, Found no solutions that worked as is for me but eventually got it working mostly based on what I found at https://github.com/angular/angular-cli/wiki/3rd-party-libs and https://github.com/valor-software/ng2-bootstrap/issues/208

It works perfectly in non production mode. App loads and all components work as expected.
When served with -prod the browser loads the following few files and then just sits there doing nothing. No logs. No errors.
http://localhost:4200/
http://localhost:4200/vendor/es6-shim/es6-shim.js
http://localhost:4200/vendor/reflect-metadata/Reflect.js
http://localhost:4200/vendor/systemjs/dist/system.src.js
http://localhost:4200/vendor/zone.js/dist/zone.js
http://localhost:4200/system-config.js
http://localhost:4200/main.js

All load successfully with 200's or 304's

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by theimdal** [comment]
I have the same issue,  #827, when I add moment.js as described in the wiki. So it seems that adding 3rd party libraries might cause trouble when bundling the application. But it is strange that there is no error logged.

**Comment by theimdal** [comment]
If you are using any commonjs libraries like underscore or moment, see the solution in #827.

**Comment by slubowsky** [comment]
Yes that fixed the problem. Thanks!
