### ISSUE TITLE
AOT build performance

### ISSUE THREAD

**Issue by elvirdolic** [angular/angular-cli#8540]
Node: 8.9.0
OS: win32 x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.2
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.0.45
typescript: 2.4.2
webpack: 3.8.1

### Repro steps
ng build --prod

### Observed behavior
Angular 5 AOT build time is not faster compared to version 4
### Desired behavior

It should be faster as announced in the release information.

### Mention any other details that might be useful (optional)
Im not sure why it takes 4-5 minutes.  Is it AOT or other --prod things which are done by CLI.

**Comment by clydin** [comment]
The build optimizer is now enabled by default.  The number of uglifyjs optimization passes is also increased to 3 (from 1) when the build optimizer is enabled.

**Comment by Wykks** [comment]
AOT _rebuild_ (watch mode) is faster, not single build.

**Comment by elvirdolic** [comment]
That is true. I will create a new feature request for cli bundling performance.
