### ISSUE TITLE
"ng new --change-detection OnPush" does not configure root or new components as expected when reading the "--help" informations.

### ISSUE THREAD

**Issue by msieurtoph** [angular/angular-cli#8543]
### Versions
```
$ ng --version

Angular CLI: 1.5.2
Node: 8.1.3
OS: win32 x64
Angular:
```

### Repro steps
* Run `ng new --help`
* Notice that `--change-detection` option is available
* Run `ng new my-app --change-detection OnPush`

### Observed behavior

src/app/app.component.ts looks like this : 
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
}
```

### Desired behavior

I expect my src/app/app.component.ts to look like this instead : 

```
import { Component, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent {
  title = 'app';
}
```

### Mention any other details that might be useful (optional)

Trying to generate a new component after that (`ng g component comp1`), I noticed the changeDetection is not set either on the new generated one.

Maybe I don't understand the way it really works. But my understanding of the `--change-detection` of the `ng new` command makes me expect that it should affect the root component and all future generated components.

But it seems that option has absolutely no effect when used with `ng new` ... 
Am I wrong ?

**Comment by aszechlicki** [comment]
any progress on this issue?

**Comment by hansl** [comment]
The `--change-detection` flag on `ng new` has been removed and doesn't show up in help. Closing this as obsolete.

If you want the flag, please open a feature request and we'll consider it. Thanks!

**Comment by scorbin** [comment]
ng new ng-app --style=scss
ng generate component new-component
ng will not detect changes in new-component
ng does detect changes in app.component.ts
