### ISSUE TITLE
Problem : -bash: ng: command not found  

### ISSUE THREAD

**Issue by manikGit** [angular/angular-cli#8545]
$ node -v
v8.9.1
$ npm -v
5.5.1

OS X EI CAPITAN V10.16
ERROR:
$ ng —version: 
-bash: ng: command not found

Log:
$ sudo npm install --unsafe-perm -g angular-cli
Password:
npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/Users/maniksrivastava/.npm-global/bin/ng -> /Users/maniksrivastava/.npm-global/lib/node_modules/angular-cli/bin/ng

> fsevents@1.1.3 install /Users/maniksrivastava/.npm-global/lib/node_modules/angular-cli/node_modules/fsevents
> node install

[fsevents] Success: "/Users/maniksrivastava/.npm-global/lib/node_modules/angular-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.7.1 install /Users/maniksrivastava/.npm-global/lib/node_modules/angular-cli/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/maniksrivastava/.npm/node-sass/4.7.1/darwin-x64-57_binding.node

> node-sass@4.7.1 postinstall /Users/maniksrivastava/.npm-global/lib/node_modules/angular-cli/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/maniksrivastava/.npm-global/lib/node_modules/angular-cli/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine
npm WARN @angular/core@2.4.10 requires a peer of rxjs@^5.0.1 but none is installed. You must install peer dependencies yourself.

+ angular-cli@1.0.0-beta.28.3
added 900 packages in 62.983s
>>>> $ ng --version
-bash: ng: command not found
>>>> $ npm install --unsafe-perm -g rxjs@^5.0.1
+ rxjs@5.5.2
updated 1 package in 5.559s
>>>> $ ng --version
-bash: ng: command not found

**Comment by glebmachine** [comment]
@manikGit try `npm i -g @angular/cli`

**Comment by manikGit** [comment]
$ sudo npm i -g @angular/cli
Password:
npm WARN gentlyRm not removing /Users/maniksrivastava/.npm-global/bin/ng as it wasn't installed by /Users/maniksrivastava/.npm-global/lib/node_modules/@angular/cli
/Users/maniksrivastava/.npm-global/bin/ng -> /Users/maniksrivastava/.npm-global/lib/node_modules/@angular/cli/bin/ng
+ @angular/cli@1.5.2
updated 4 packages in 34.974s
$ ng --version
-bash: ng: command not found

**Comment by guhan62** [comment]
Hey there,you have met the dependencies for angular-cli but accessing **_ng_** over terminal requires you to set the path for global packages in your path environment.
#### Path known
- Assuming you have a global modules set up for npm _(by default ~/.node_modules_global)_
`$ npm prefix -g`

- Now set the path of modules/bin to our bash path environment to access over terminal
```
$ echo -e "export PATH=$(npm prefix -g)/bin:$PATH" >> ~/.bashrc 
$ source ~/.bashrc
```
#### How about setting a new one!
```
$ mkdir ~/path/module
$ npm config set prefix '~/path/module'
$ sudo chown -R $USER <directory>
```
Now the final touch, install angular/cli package
`npm install -g @angular/cli`

**Comment by manikGit** [comment]
$ ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.2
Node: 8.9.1
OS: darwin x64


Thanks @guhan62 . It worked.

**Comment by fayeyen** [comment]
@guhan62 when I type source ~/.bashrc
-bash: export: `Studio.app/sdk/platform-tools:/Applications/Android': not a valid identifier
-bash: export: `Studio.app/sdk/tools': not a valid identifier

**Comment by guhan62** [comment]
@fayeyen, sorry just saw that you had mentioned me to solve the issue.

Seems like you have an issue with Android studio bin linking to the source. I would recommend that you could remove the SDK link in your ~/.bashrc.
