### ISSUE TITLE
Missing Pipe suffix

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#855]
`ng g p foo` should create a symbol named `FooPipe`. Selector is fine. Instead, it creates the below `Foo`

```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'foo'
})
export class Foo implements PipeTransform {

  transform(value: any, args?: any): any {
    return null;
  }

}
```

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/commit/c92f3303773cc9d42941a86b497d8fbce101503a
