### ISSUE TITLE
angular 

### ISSUE THREAD

**Issue by srrii** [angular/angular-cli#8552]
while opening terminal in visual studio code it is giving an error that npm is not recognized as an internal or external command , operable program or batch file
[angular.docx](https://github.com/angular/angular-cli/files/1486574/angular.docx)

**Comment by MjJuneja** [comment]
You need to be inside that directory where you can run npm command to save bootstrap dependencies. 

if you have srishti folder directly inside ADMIN directory. 
perform cd srishti and then type npm install bootstrap --save

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
