### ISSUE TITLE
Fail to compile app with @ngtools/webpack and serviceworker-webpack-plugin

### ISSUE THREAD

**Issue by bukharin** [angular/angular-cli#8553]
Hi, we are using `serviceworker-webpack-plugin` with `@ngtools/webpack` and webpack fail to compile service-worker entry module with following error:

```
Module build failed: Error: @ngtools/webpack is being used as a loader but no `tsConfigPath` option nor AotPlugin was detected. You must provide at least one of these.

at Object.ngcLoader (\\node_modules\\@ngtools\\webpack\\src\\loader.js:614:19)
```

We are using plugins like this:

``` js
new ServiceWorkerWebpackPlugin({
            entry: helpers.root('src/app/service-worker'),
            excludes: ['sw.*.js', 'online.html'],
            includes: ['**/*.css', '**/*.js', '**/*.json', '**/*.png', '**/*.svg']
        })
```

And `AngularCompilerPlugin`:

``` js
new ngc.AngularCompilerPlugin({
                tsConfigPath: helpers.root('tsconfig.aot.json'),
                entryModule: helpers.root('src/app/app.module#AppModule'),

            }),
```

### Versions
```
"serviceworker-webpack-plugin": "0.2.3",
"@ngtools/webpack": "1.8.2",
"webpack": "3.8.1"
```

### Mention any other details that might be useful (optional)

It seems that `ngcLoader` cannot read own options when `serviceworker-webpack-plugin` starts child compilation process

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by mgechev** [comment]
Closing it due to inactivity. If the problem is still reproducible with the latest CLI, please open a new issue following the template and sharing a minimal demo where we can reproduce it. Thank you! :)
