### ISSUE TITLE
Angular2 Owl Carousel

### ISSUE THREAD

**Issue by manejsh** [angular/angular-cli#8557]
Failed to compile.

./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
Module not found: Error: Can't resolve './owl.video.play.png' in 'C:\xampp\htdocs\coco\src'
 @ ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss 6:934078-934109
 @ ./src/styles.scss
 @ multi ./~/quill/dist/quill.core.css ./~/quill/dist/quill.bubble.css ./~/quill/dist/quill.snow.css ./~/font-awesome/css/font-awesome.css ./~/material-design-icon-fonts/iconfont/material-icons.css ./~/weathericons/css/weather-icons.css ./~/weathericons/css/weather-icons-wind.css ./~/@swimlane/ngx-datatable/release/assets/icons.css ./~/@swimlane/ngx-datatable/release/datatable.css ./~/@swimlane/ngx-datatable/release/material.css ./~/fullcalendar/dist/fullcalendar.css ./~/github-markdown-css/github-markdown.css ./~/owl.carousel/dist/assets/owl.carousel.css ./src/styles.scss

**Comment by manejsh** [comment]
Please any one help me out

**Comment by hansl** [comment]
Hi @manejsh,

We reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by dm-grinko** [comment]
I faced the same issue
