### ISSUE TITLE
scss sourcemaps stopped working after upgrade from 1.4.5 to 1.5

### ISSUE THREAD

**Issue by sunew** [angular/angular-cli#8558]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
Angular CLI: 1.5.2
Node: 8.2.1
OS: linux x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.2
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.2
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1


```

### Repro steps

* create an app with global styles:

in .angular-cli.json:
```
      "styles": [
        "styles/styles.scss"
      ],
      "stylePreprocessorOptions": {
        "includePaths": [
          "styles"
        ]
      },
```

* ng serve --extract-css --sourcemaps

### Observed behavior

With angular-cli version 1.4.5 we see sourcemaps in chrome dev tools - see attached image 1. The sourcefile-links points to the original scss file and linenumber from the styles folder (the styles folder defined in .angular-cli.json). 
For instance: _footer.scss:47

![selection_312](https://user-images.githubusercontent.com/893142/33017113-640c541a-cdf1-11e7-93a6-1c4b97a57306.png)

With angular-cli version 1.5.2 there are no scss sourcemaps - source links points to the css bundles - see attached image 2

![selection_311](https://user-images.githubusercontent.com/893142/33017119-6c77ade8-cdf1-11e7-9a6d-13ef4c0160ca.png)

```
<!-- Normally this includes a stack trace and some more information. -->
```

### Desired behavior
scss sourcemaps as in 1.4.5

**Comment by JohnAnthony** [comment]
I had what I believe to be a related issue with even getting scss to compile; perhaps `@angular/cli` has changed how it handles node-sass dependency.

Manually installing the `node-scss` dependency at the latest version fixed my issues, so it might help you also.

`npm install --save node-sass@latest`

**Comment by sunew** [comment]
@JohnAnthony thank you for the hint! It did not solve the issue though.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
