### ISSUE TITLE
Pipe spec should be valid

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#856]
Notice the spec below has an assert. The `pipe.transform` should not be using boolean, it should be using the type of value for the pipe. Or change the test.

```
import {
  it,
  describe,
  expect,
  inject,
  beforeEachProviders
} from '@angular/core/testing';
import { SortSpeakersPipe } from './sort-speakers.pipe';

describe('SortSpeakers Pipe', () => {
  beforeEachProviders(() => [SortSpeakersPipe]);

  it('should transform the input', inject([SortSpeakersPipe], (pipe: SortSpeakersPipe) => {
      expect(pipe.transform(true)).toBe(null);
  }));
});
```

Otherwise, it makes it red like this
![image](https://cloud.githubusercontent.com/assets/1202528/15417279/f3dd2a64-1e21-11e6-9c55-2d522c3fdd3b.png)

**Comment by deebloo** [comment]
since by default the the first argument for transform is 'any' this shouldn't be a problem should it?
