### ISSUE TITLE
Karma hangs when using karma run

### ISSUE THREAD

**Issue by Archcry** [angular/angular-cli#8566]
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.8 (e)
node: 8.8.1
os: linux x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.2.8
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
```

### Repro steps

* Create a new project with ng new `<projectname>`
* Open `karma.conf.js` and change `autoWatch: true` to `autoWatch: false`
* Spawn the test server with `karma start`
* Change `styleUrls: ['./app.component.css']` to `styleUrls: ['./app.comonent.css']` so the code is invalid and will trigger a webpack compilation error (typescript compile errors will have the same effect).
* Karma server will now error, this is fine.
* In another terminal, in the same directory execute `karma run`

### Observed behavior
`karma run` now hangs untill the error is resolved.

### Desired behavior
`karma run` should terminate with an error.

### Mention any other details that might be useful (optional)
When configuring the project with the steps provided by the angular documentation this does not happen (https://angular.io/guide/webpack). This approach does not use the @Angular/cli so the problem seems to be in @Angular/cli

**Comment by Archcry** [comment]
I could try to diagnose the problem and shoot in a pull-request if that would speed up the progress. Just tell me whether this is a bug or intended behaviour in your point of view.

**Comment by filipesilva** [comment]
I'm not sure if this is a bug or not. I think what you're saying is that `karma run` shouldn't try to watch files, right?

But you're also using the custom Angular CLI plugin for Karma without actually using Angular CLI, which isn't really supported. 

I think what's happening is that, but not running `ng test`, some of the options we pass in aren't passed. If you want to take a look these are the important files:
- https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/commands/test.ts
- https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/tasks/test.ts
- https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/plugins/karma.ts

**Comment by tiaguinho** [comment]
@mgechev the files @filipesilva had linked doesn't exist anymore.
For the explanation he gave, I don't think this is an Angular CLI problem.

I think this issue can be closed.

**Comment by filipesilva** [comment]
Thanks for the heads up @tiaguinho, closing it.
