### ISSUE TITLE
npm ERR! Installing ERROR | Unexpected end of JSON input while parsing near '...'

### ISSUE THREAD

**Issue by ssshekhawat** [angular/angular-cli#8572]
C:\Users\Sandeep>npm install -g @angular/cli
npm ERR! Unexpected end of JSON input while parsing near '...a57e4c92ba141aa2c17fb'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sandeep\AppData\Roaming\npm-cache\_logs\2017-11-21T16_00_37_726Z-debug.log

C:\Users\Sandeep>npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

C:\Users\Sandeep>node -v
v8.9.1

C:\Users\Sandeep>npm -v
5.5.1

I am not sure why angular latest version is not installing on my machine.

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.

**Comment by radhey24h** [comment]
I m having with same issue.

**Comment by bvraj1988** [comment]
I am getting the same issue how to resolve it.

**Comment by DarylBerryhill** [comment]
I am getting a similar error when creating a new angular project.
Windows 10 home
angular-cli 1.6.0
npm 5.6.0
node 8.9.3

** running nodeJS CMD as administrator **

after globally installing angular-cli now trying to create a first project
see ouptut

C:\Angular-Projects>ng new maxdocs --style=scss --routing --verbose
  create maxdocs/e2e/app.e2e-spec.ts (289 bytes)
  create maxdocs/e2e/app.po.ts (208 bytes)
  create maxdocs/e2e/tsconfig.e2e.json (235 bytes)
  create maxdocs/karma.conf.js (923 bytes)
  create maxdocs/package.json (1312 bytes)
  create maxdocs/protractor.conf.js (722 bytes)
  create maxdocs/README.md (1023 bytes)
  create maxdocs/tsconfig.json (363 bytes)
  create maxdocs/tslint.json (3040 bytes)
  create maxdocs/.angular-cli.json (1244 bytes)
  create maxdocs/.editorconfig (245 bytes)
  create maxdocs/.gitignore (516 bytes)
  create maxdocs/src/assets/.gitkeep (0 bytes)
  create maxdocs/src/environments/environment.prod.ts (51 bytes)
  create maxdocs/src/environments/environment.ts (387 bytes)
  create maxdocs/src/favicon.ico (5430 bytes)
  create maxdocs/src/index.html (294 bytes)
  create maxdocs/src/main.ts (370 bytes)
  create maxdocs/src/polyfills.ts (2405 bytes)
  create maxdocs/src/styles.scss (80 bytes)
  create maxdocs/src/test.ts (1085 bytes)
  create maxdocs/src/tsconfig.app.json (211 bytes)
  create maxdocs/src/tsconfig.spec.json (304 bytes)
  create maxdocs/src/typings.d.ts (104 bytes)
  create maxdocs/src/app/app-routing.module.ts (245 bytes)
  create maxdocs/src/app/app.module.ts (395 bytes)
  create maxdocs/src/app/app.component.html (1173 bytes)
  create maxdocs/src/app/app.component.spec.ts (1103 bytes)
  create maxdocs/src/app/app.component.ts (208 bytes)
  create maxdocs/src/app/app.component.scss (0 bytes)
Installing packages for tooling via npm.
npm ERR! Unexpected end of JSON input while parsing near '..."1.1.0","jasminewd2":'
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pickledham\AppData\Roaming\npm-cache\_logs\2017-12-10T19_35_37_928Z-debug.log
Package install failed, see above.

**Comment by AravindPrabash** [comment]
Try clearing npm cache nd then try again. Should work fine
`npm install -g @angular/cli`

**Comment by blacksonic** [comment]
Clearing the npm cache doesnt solve this issue.

**Comment by AryanJ-NYC** [comment]
I resolved this problem on my local machine. I _had_ `@angular/cli 1.7.3` defined in my `package.json`. I:

1. Manually changed it to `^6.0.5`
2. Ran `npm install`
3. Ran `ng update @angular/cli` without a problem.

**Comment by nevernet** [comment]
@AryanJ-NYC are you sure `npm install` is working?    we should `npm install @angular/cli`

**Comment by nevernet** [comment]
my solution: 

switch registry to `https://registry.npmjs.org/`
and use proxy in order to get better network.

and then try
`npm cache clean --force`
`npm install --save-dev @angular/cli@latest`

everything goes well.

**Comment by AryanJ-NYC** [comment]
@nevernet `npm install` _does_ install `@angular/cli` since I manually changed the `@angular/cli` version in `package.json`.

**Comment by webuilderkrish** [comment]
> Try clearing npm cache nd then try again. Should work fine
> `npm cache clean --force`

nothing is working from above showing same error

**Comment by webuilderkrish** [comment]
all above solutions are not working for me

**Comment by dinushchathurya** [comment]
Try this 
npm cache clean --force

**Comment by nevernet** [comment]
@webuilderkrish 


```
cd <project root folder>
echo 'registry=https://registry.npmjs.org/'  > .npmrc
```
maybe you could use http proxy in order to get better network.

and then try

```
rm -rf node_modules dist
npm cache clean --force
npm install --save-dev @angular/cli@latest
```
everything goes well.
