### ISSUE TITLE
Please create ng g b folder/path

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#858]
When we create a sub-folder, we should have a barrel. Sometimes we manually create folders either because we want to or because the CLI can't do it for us (nested folder for a set of shared/service). In this case we may want a barrel. I propose we add `ng g b shared/path` which would create `index.ts` in that folder, and export the stuff there already.

**Comment by SergeySolonko** [comment]
I did this for ZSH

```
function ng-folder {
        if [[ $# != 0 ]]
        then
                local argPath="$1"
                mkdir "$argPath" && touch "$argPath/index.ts" && mkdir "$argPath/shared" && touch "$argPath/shared/index.ts"
        fi
}
```

but still need to add barrel manually =))

**Comment by johnpapa** [comment]
yes, that's neat ... but i think it would be cool if we had this in the CLI so it can add the barrel too.

**Comment by SergeySolonko** [comment]
agree, +1 =)

**Comment by JonCubed** [comment]
if it helps I've written my own replacement for the cli barrel-management, which will crawl up the parent folders making sure there is a barrel file when you add a file. I'm using it with my own custom blueprints.
https://github.com/JonCubed/ngrx-blueprints/blob/master/src/addon/ng2/utilities/ngrx-barrel-management.js

**Comment by shairez** [comment]
@johnpapa is it still relevant after the ngModules addition?

**Comment by filipesilva** [comment]
Closed as obsolete. If that's not the case, tell me and I will reopen.
