### ISSUE TITLE
@ngtools/webpack AOT loader failed to resolve nested exports (Barrels)

### ISSUE THREAD

**Issue by Sky4CE** [angular/angular-cli#8581]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
</code></pre>

### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
@ngtools/webpack: 1.8.3
node: 6.11.1
npm: 5.5.1
os: win10 x64
angular: 5.0.2
typescript: 2.5.3
```

### Repro steps

Use barrels system in project based on index.ts, that every feature folder consists of index.ts where you can re-export components, so instead of:
`import { AuthService } from '@app/core/services/auth.service';`
You can do: 
`import * as Core from '@app/core';`
and use any entity inside Core like this:
`Core.Services.AuthService`

Reproduction:

- [Repo based on JIT:at-loader and AOT:ngtools](https://github.com/Sky4CE/angular-5-aot-lazy-barrels), JIT works, AOT does not
- [Repo based on angular-cli both JIT and AOT](https://github.com/Sky4CE/angular-5-cli-barrels), neither works

### Observed behavior

JIT compiles like a charm without any problems, but when I try to compile using AOT with help of `@ngtools/webpack` mentioned behavior not work. AOT plugin cannot see any further than second property, for example when I inject service into constructor like this:
`constructor(private router: Router, private authService: Core.Services.AuthService)`
I get next error:
`ERROR in Error: Can't resolve all parameters for AppLaunchComponent in /Client/app/app.launch.ts: ([object Object], ?).`
so second parameter does not recognized, but when I import CoreServices directly and use like this:
`constructor(private router: Router, private authService: CoreServices.AuthService)`
it could recognize all parameters.
But I really like to import one-line just Core and nothing more, because we have 1000+ components in our app, so import each separately is absolutely not an option.

### Desired behavior
Do not drop(tree-shake) nested exports while parsing import sequence!

Is it possible to see this bug fixed ?

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by Sky4CE** [comment]
@filipesilva , I've prepared [reproduction repo](https://github.com/Sky4CE/angular-5-aot-lazy-barrels) for you. It can be build with jit or aot. Jit build works, but aot throws an error at compile stage, you can play with it, I've left commented lines which will work with aot, but with 1 level deep nesting:
![image](https://user-images.githubusercontent.com/9821633/33381002-789ff0c2-d525-11e7-8868-622949aa4ed5.png)
![image](https://user-images.githubusercontent.com/9821633/33381021-84c7c17c-d525-11e7-8a8f-22fd1e07d356.png)
![image](https://user-images.githubusercontent.com/9821633/33381053-92fc0708-d525-11e7-8a8f-1b680a1d6ce5.png)
to run with aot: `npm run aot`
to run with jit: `npm run jit`
access site at `localhost:3000`

**Comment by Sky4CE** [comment]
@filipesilva , I've created [another repo](https://github.com/Sky4CE/angular-5-cli-barrels) which is based on pure angular-cli (ng new) plus applied barrels. In this case not working neither JIT nor AOT. So I assume this is angular cli bug.

**Comment by SamiAl90** [comment]
#8576

**Comment by Sky4CE** [comment]
@filipesilva any progress on this ?
