### ISSUE TITLE
When creating a folder manually, the barrel needs to be updated in the systemjs.config

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#859]
this happens because there is no CLI command to generate a folder. If there was, then the CLI could do this.

**Comment by SergeySolonko** [comment]
This ticket has same purpose as https://github.com/angular/angular-cli/issues/858

**Comment by Brocco** [comment]
I agree with @SergeySolonko #858 would handle this scenario instead of the CLI having to discern that a folder was added outside of the CLI. @johnpapa if you agree, please close.

**Comment by johnpapa** [comment]
i agree ...
