### ISSUE TITLE
Angular 5 + GCloud: SockJS and eventsource requests over and over non-stop

### ISSUE THREAD

**Issue by sberlinches** [angular/angular-cli#8590]
Hi there!

I'd need some help to understand what is happening here.
Once I deploy the project on gcloud and launch it in the browser, the application (in idle) starts to request like crazy. ~5 request per second non-stop.

![request](https://user-images.githubusercontent.com/6792513/33120457-f9a8c888-cf26-11e7-92db-697e710aa67d.png)

**Comment by filipesilva** [comment]
I have no idea what's happening there. We don't do anything with SockJS except the live reload server when you run `ng serve` but that should never be used in production (which we warn you on the console if you try).

If you deployed a project built with `ng build --prod` then it's something on your project code. Maybe try building with sourcemaps (`ng build --prod --sourcemaps`) and you can get better information about what's causing it.

We reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
