### ISSUE TITLE
[SW] Angular 5: Service Worker Uncaught (in promise) DOMException: Quota exceeded.

### ISSUE THREAD

**Issue by GuillaumeUnice** [angular/angular-cli#8592]
Prerequiste: test on chrome last version and chromium last version
I simply install the service worker package and deploy the default ngsw-config.json just add a API call and register the cache strategy inside the ngsw-config.json

```
"dataGroups": [{
      "name": "api-server",
      "urls": [
        "https://dog.ceo/api/**"
      ],
      "cacheConfig": {
        "strategy": "freshness",
        "maxSize": 100,
        "maxAge": "3d",
        "timeout": "10s"
      }
    }]
```

An I have the following error: 
`
Uncaught (in promise) DOMException: Quota exceeded.
`

So, it seems the ngsw-worker.js doesn't work very well
Have ever encountered this problem?

Thanks for all

**Comment by filipesilva** [comment]
Error message like `Quota exceeded` usually mean that you're trying to use a webservice too much. It means they have a quota for how many requests you can do per a period of time (a quota) and you made more requests than that.

It's not something that we can address in the Angular CLI repo since it's completely unrelated to us. You should contact the owner of that service if you need a bigger quota.

**Comment by j2L4e** [comment]
This is not related to a remote service.

In my case this happens with the standard ngsw-config on Chrome 63 / Ubuntu.
```
ng new ServiceWorker1 --service-worker
cd ServiceWorker1
ng build --prod
```
Everything DOES work in firefox and it also works when I switch to Chrome's incognito mode.

**Comment by kgathuru** [comment]
@filipesilva I think you have mistakenly closed this issue. I'm getting the same error and we don't use any webservices in our app. I'm getting the same behaviour as @j2L4e where it works in chrome incognito.

**Comment by GuillaumeUnice** [comment]
Hi @kgathuru  have you tested on the last CLI release 1.6?

**Comment by j2L4e** [comment]
In my case it turned out that freeing disk space solved the issue. There was only about 4% free space left on my main ssd and this seems to make chrome set the storage quota to zero.

**Comment by j2L4e** [comment]
When the issue appeared `navigator.storage.estimate()` would always return  an object with `quota === usage`, both being about the service worker script size.

Catching the error and emitting an event through the angular service would be awesome. Now any caching will fail silently.

**Comment by filipesilva** [comment]
@j2L4e you're right, the quota in question is not for a webserver but for the browser itself. 

- https://stackoverflow.com/questions/44375494/uncaught-in-promise-domexception-quota-exceeded 
- https://medium.com/dev-channel/offline-storage-for-progressive-web-apps-70d52695513c

This bit in the second link os of special importance:
> How much can you store? In Chrome and Opera: Your storage is per origin (rather than per API). Both storage mechanisms will store data until the browser quota is reached. Apps can check how much quota they’re using with the Quota Management API. Firefox: no limits, but will prompt after 50MB data stored. Mobile Safari: 50MB max, Desktop Safari: unlimited (prompts after 5MB), IE10+ maxes at 250MB and prompts at 10MB. PouchDB track IDB storage behavior. Future facing: For apps requiring more persistent storage, see the on-going work on Durable Storage.

This explains why the behaviour is different between browsers. It sounds like it's a matter of managing the data stored.

I agree the error isn't very useful as is but there isn't much to be done on Angular CLI proper. Can you open an issue on https://github.com/angular/angular itself please? That's the right repo for `ngsw-worker.j`.

**Comment by j2L4e** [comment]
Sorry, I didn't actually notice that this issue was on the CLI repo when I got the notification. I'll take it over there. Thanks for all your work! :+1:

**Comment by GuillaumeUnice** [comment]
Hey thank you very much! 
Perhaps, @j2L4e could you link theis issue with the angular repository's issue

Have a good one ;)

**Comment by kgathuru** [comment]
Thanks people. :-) We appreciate the hard work!
