### ISSUE TITLE
Static assets in server-side build of Angular Universal app

### ISSUE THREAD

**Issue by bellizio** [angular/angular-cli#8605]
### Versions
```
Angular CLI: 1.5.0
Node: 8.9.0
OS: darwin x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, upgrade

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps
* Download the [Angular Universal sample code](https://angular.io/generated/zips/universal/universal.zip) from the official [Universal guide](https://angular.io/guide/universal)
* Unzip the file and run `npm install` in the **universal** directory
* Run `npm run build:ssr`
* Open/view the **dist/server** directory

### Observed behavior
There are `favicon.ico` and `styles.bundle.css` files generated in the **dist/server** and **dist/browser** directories as a result of the server-side and client-side build processes.

### Desired behavior
Is it intentional/necessary for asset files such as these to be output to the server build directory? And if so, why?

### Mention any other details that might be useful (optional)
The reason these files are included in the server build is because of their inclusion in the "assets" array in the server app in `.angular-cli.json` ([see the universal wiki story](https://github.com/angular/angular-cli/wiki/stories-universal-rendering#angular-clijson)). After removing the file references from the "assets" array in the server app, re-building, and serving the app locally, I noticed no errors or exceptions. Based on this and the fact these files are only ever used by the browser, is there any reason to continue including them in the server-side build of Angular Universal apps in the future?

**Comment by filipesilva** [comment]
Is this still a problem since we split the universal setup into its own builder?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem.

Thanks
