### ISSUE TITLE
external module in Angular CLI

### ISSUE THREAD

**Issue by stepet80** [angular/angular-cli#8607]
Hello

We have the following situation:
- application A provides a CDN JS bundle containing Angular objects to be used by a consuming application
- application A provides an npm package called @myorg/core with only d.ts files an an index.d.ts file
- application B adds a script tag towards the CDN bundle
- application B consumes the npm package @myorg/core in an Angular CLI context
--> So somewhere in a file an "import MyComponent from 'myorg/core'" is done which works fine (the d.ts files are detected and providing typing)
- when the Angular cli ng build command is called it says that module myorg/core cannot be found

How can I make this work with Angular CLI?
In Webpack I would be able to use the externals property and this would work fine.

Actually I think it should be the same behavior as @types packages...

Thanks in advance.

**Comment by krishnakumarsingh** [comment]
Thanks

**Comment by filipesilva** [comment]
We don't support building from external sources, and generally speaking AOT builds won't work with externals since they need the code to be present to statically analyze and produce ng factories.

Since it can't work with AOT I don't think we can support this usecase.

**Comment by mgechev** [comment]
https://github.com/angular/angular-cli/issues/8607#issuecomment-346602593 we do not recommend JIT production build. Let us leave this out of the scope of the CLI.
