### ISSUE TITLE
When creating child route, CLI adds /...

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#861]
v1 beta 5

The deprecated router uses `/...` to denote a child router. The CLI is not using the deprecated router. Yet when I create a route and a child route, I get this. There should not be a `/...`

```
  {path: '/foo/...', component: FooComponent}
```

to reproduce:

```
ng new myapp 
ng g r foo
ng g r foo/bar
```

**Comment by deebloo** [comment]
@johnpapa is there another convention the RC follows or does it just figure it out?

**Comment by johnpapa** [comment]
It has no ...

**Comment by deebloo** [comment]
cool deal

**Comment by filipesilva** [comment]
According to https://github.com/angular/angular-cli/pull/876, this is already fixed. Please correct me if I'm wrong.
