### ISSUE TITLE
unexpected token error while server side rendering angular universal

### ISSUE THREAD

**Issue by deepakpapola** [angular/angular-cli#8614]
### Versions
```

@angular/cli: 1.3.1
node: 6.11.4
os: linux x64
@angular/animations: 4.4.6
@angular/common: 4.4.2
@angular/compiler: 4.4.2
@angular/core: 4.4.2
@angular/forms: 4.4.2
@angular/http: 4.4.2
@angular/platform-browser: 4.4.2
@angular/platform-browser-dynamic: 4.4.2
@angular/router: 4.4.2
@angular/cli: 1.3.1
@angular/compiler-cli: 4.4.2
@angular/language-service: 4.4.2
@angular/platform-server: 4.4.2

os- ubuntu 17.04

```

### Repro steps

ng build (successfuly build)
At the end I run:
node server.js

### The log given by the failure.

/node_modules/@angular-mdl/core/components/dialog-outlet/mdl-dialog-outlet.component.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, ViewContainerRef, forwardRef, Inject } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.z45w (/home/dp/Desktop/angular-seo/dist-server/main.bundle.js:1:299718)
### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

### Desired behavior
Run server without errors

### Mention any other details that might be useful (optional)

I read then there can be problems with 3rd party libs, Is this problem related to that?

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by mgechev** [comment]
Closing it due to inactivity. If the problem is still reproducible with the latest CLI, please open a new issue following the template and sharing a minimal demo where we can reproduce it. Thank you! :)
