### ISSUE TITLE
Prod build doesn't pick up template errors

### ISSUE THREAD

**Issue by Swellenator** [angular/angular-cli#8617]
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.3
Node: 8.4.0
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.5.3
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.3
@schematics/angular: 0.1.5
typescript: 2.6.1
webpack: 3.8.1
```

### Repro steps
In a template:
`<button type="button" class="btn btn-primary" (click)="blahblahdoesntexist(fff)">Add item</button>`

Run:
`ng build --prod`

### Observed behavior
Angular language service says:
`[Angular] Unknown method 'blahblahdoesntexist'`

But build completes without error.

### Desired behavior
The AOT (--prod) build should pick up errors in the templates.

### Mention any other details that might be useful (optional)
I thought it might have done this in the past but I can't remember. It was certainly a selling point of using the prod builds on a build server to catch these problems.

**Comment by josephliccini** [comment]
Probably related to this?
https://github.com/angular/angular/issues/20287

**Comment by filipesilva** [comment]
This does seem to be https://github.com/angular/angular/issues/20287. Please subscribe to that issue for further updates.

**Comment by spottedmahn** [comment]
FYI: [angular/angular#20287](https://github.com/angular/angular/issues/20287) redirects to [angular/angular#19792](https://github.com/angular/angular/issues/19792)
