### ISSUE TITLE
Can't bind to 'alerts' since it isn't a known property of 'alertbox'. plz help!! 

### ISSUE THREAD

**Issue by suvro84** [angular/angular-cli#8618]
https://github.com/suvro84/Angular2MVC/tree/Angular2MVC-Latest

### Observed behavior

EXCEPTION: Uncaught (in promise): Error: DI Error
In customer-inquiry.component.html  
if i comment this line:
**<alertbox [alerts]="alerts" [messageBox]="messageBox"></alertbox>**

Can't bind to 'alerts' since it isn't a known property of 'alertbox'.
this error goes away because i removed alert reference

Now the page opens but **DI error comes** I have removed all alert references but still DI error exists

I feel there is some prob with dependency injection

I think all dependencies are declared accordingly

Cant understand..plz help

**Desired behavior**
Simple customer inquiry page with a grid containing pagination sorting feature user can search

![di-error](https://user-images.githubusercontent.com/29579390/33196435-1871dc48-d105-11e7-96f3-27a3f34aecee.jpg)

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

The best I can say at the moment is that you might not have the property `alerts` in your `alertbox` component. You should look there.
