### ISSUE TITLE
ng serve and ng serve --aot true have different behaviours

### ISSUE THREAD

**Issue by ShinDarth** [angular/angular-cli#8620]
### Versions
```
Angular CLI: 1.5.4
Node: 8.9.1
OS: linux x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1

```

### Repro steps

Unfortunately I'm not able to provide any reproduction steps because I'm not sure yet where exactly is the problem, but we are experiencing some inconsistencies between `aot` and `non-aot` modes.

### Observed behavior

The same source code behaves differently with and without `aot`

### Desired behavior

The behaviour should be the same.

**Comment by filipesilva** [comment]
When you run in `--aot` your code will be compiled with the AOT compiler so it is a different pipeline. As far as the behaviour changing, I really cannot say anything without more information...

Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by ShinDarth** [comment]
I completely forgot about this issue, but I can tell that as of the newest CLI version (see below) the original issue is solved for us.

Thanks to all contributors!

```
Angular CLI: 6.1.5
Node: 10.9.0
OS: linux x64
Angular: 6.1.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.8.3
    

```
