### ISSUE TITLE
group lazy modules in console when doing ng serve

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#8621]
### Versions
all

### REPRO
* create more than 50 - 100 lazyload module
* run using `ng serve`
* You will have many number of lines in your console see example: https://gist.github.com/istiti/6b73e021896021048f6f1f9b372da5f9 

### Observed behavior
I think this is a very ergonomics problem to see so many output  in console which have scroll: 
And in many  IDE your console takes often 25% of the height 
![image](https://user-images.githubusercontent.com/2789203/33202654-a482404a-d0fd-11e7-952e-537a864cc174.png)

In fact problem will come when you have an error which not break your "ng serve" and you edit many times a file , the cli rebuild many times and you have sometimes error at the begining of you console, you can't see it quickly, you need scroll the console to read it just because of numberous lines  `chunk {name.module} name.module.chunk.js () 58.7 kB  [rendered]`

You can see error here :
![cliscrolltoseeerror](https://user-images.githubusercontent.com/2789203/33202761-02af38ee-d0fe-11e7-909f-9c12d37300d9.gif)

### Desired behavior
I think  CLI should NOT show these NOT important informations (on big project with many lazy module) because your console isn't clean and not ergonomics, not easy to use, to see if error happends.

I think these lazymodule chunk  should still be here only with `--verbose` flag. 
And if you run `ng s` just output the minimum informations maxmimum of 7 or 10 lines and maybe regroup lazymodule in one lines, something like : 

### RESULT SHOULD BE

![grouping](https://user-images.githubusercontent.com/2789203/33206333-1ee516a8-d10a-11e7-9b76-05742220bdf1.gif)

What you think ?

**Comment by filipesilva** [comment]
I agree it's not very useful to show the bundles every time on rebuild and that it can make it hard to see errors.

If someone wants to take a look, the file where we show stats is https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/utilities/stats.ts. But remember that we'd need to do it differently for initial builds (show all) than rebuilds (show less).

**Comment by istiti** [comment]
will do it, can you please indicate how from this statsToString() method I can check if it’s initial build or rebuild? 

Do you even want this behavior:
Initial build: show all
Rebuild : show less
for ˋng s —verboseˋ

**Comment by Taha-Di-Nero** [comment]
@filipesilva Here is the stats.ts modified as I have no permissions to create a branch:
```
import chalk from 'chalk';
import { stripIndents } from 'common-tags';


// Force basic color support on terminals with no color support.
// Chalk typings don't have the correct constructor parameters.
const chalkCtx = new (chalk.constructor as any)(chalk.supportsColor ? {} : { level: 1 });
const { bold, green, red, reset, white, yellow } = chalkCtx;

let statsFirstTimeCall = true;

function _formatSize(size: number): string {
  if (size <= 0) {
    return '0 bytes';
  }

  const abbreviations = ['bytes', 'kB', 'MB', 'GB'];
  const index = Math.floor(Math.log(size) / Math.log(1000));

  return `${+(size / Math.pow(1000, index)).toPrecision(3)} ${abbreviations[index]}`;
}


export function statsToString(json: any, statsConfig: any) {
  if (!statsFirstTimeCall) {
    return '';
  } else {
    statsFirstTimeCall = false;
    const colors = statsConfig.colors;
    const rs = (x: string) => colors ? reset(x) : x;
    const w = (x: string) => colors ? bold(white(x)) : x;
    const g = (x: string) => colors ? bold(green(x)) : x;
    const y = (x: string) => colors ? bold(yellow(x)) : x;
    return rs(stripIndents`
    Date: ${w(new Date().toISOString())}
    Hash: ${w(json.hash)}
    Time: ${w('' + json.time)}ms
    ${json.chunks.map((chunk: any) => {
        const asset = json.assets.filter((x: any) => x.name == chunk.files[0])[0];
        const size = asset ? ` ${_formatSize(asset.size)}` : '';
        const files = chunk.files.join(', ');
        const names = chunk.names ? ` (${chunk.names.join(', ')})` : '';
        const initial = y(chunk.entry ? '[entry]' : chunk.initial ? '[initial]' : '');
        const flags = ['rendered', 'recorded']
          .map(f => f && chunk[f] ? g(` [${f}]`) : '')
          .join('');

        return `chunk {${y(chunk.id)}} ${g(files)}${names}${size} ${initial}${flags}`;
      }).join('\n')}
    `);
  }
}

export function statsWarningsToString(json: any, statsConfig: any) {
  const colors = statsConfig.colors;
  const rs = (x: string) => colors ? reset(x) : x;
  const y = (x: string) => colors ? bold(yellow(x)) : x;

  return rs('\n' + json.warnings.map((warning: any) => y(`WARNING in ${warning}`)).join('\n\n'));
}

export function statsErrorsToString(json: any, statsConfig: any) {
  const colors = statsConfig.colors;
  const rs = (x: string) => colors ? reset(x) : x;
  const r = (x: string) => colors ? bold(red(x)) : x;

  return rs('\n' + json.errors.map((error: any) => r(`ERROR in ${error}`)).join('\n'));
}
```

**Comment by istiti** [comment]
@filipesilva can you please answer here, what would you mean by "show less" do you meaning grouping all lazy modules ( number of files + total size ) somehitng like : 
![image](https://user-images.githubusercontent.com/2789203/33549812-13b43054-d8ec-11e7-9a27-7bb6a8b8cba3.png)

If yes can you just write the line that console must display ? 

OR  a lot easier first build console must show all then only write in console something like : "rebuild finish !"

cc/ @filipesilva @hansl

**Comment by filipesilva** [comment]
@istiti I don't think there is a good way to check if it is a initial build. Maybe what you can do is call it differently if using `ng build` or `ng serve`. That sounds like an easier approach since they are different commands and you can just add a flag to the stats function.

Regarding how to show less, that really is an open question... I think your approach of showing the number of lazy modules and the total size is pretty good. @hansl what do you think?

**Comment by Taha-Di-Nero** [comment]
PR #8836
show nothing second time in serve mode. Is just noise during serve.

**Comment by istiti** [comment]
Thanks  let team accept or not, imho your approach is a little bit radical. I would too go with empty return BUT showing newly added lazymodule because they are considered as « first time builded»

 I mean for existing and edited files return ‘ ‘ but if durning serve you add new lazyload module and add it in a routing show them in console after rebuild.

What do you think?

**Comment by filipesilva** [comment]
I brought this up with the team yesterday and they think it's a good idea. 

@istiti and @Taha-Di-Nero what do you think of showing only bundles that changed? For instance if you add a new lazy loaded chunk it would show up. But if you edit something that changes your main chunk that one would show as well. This is easy to determine because chunks that change show `rendered` in stats.

**Comment by istiti** [comment]
This is exactly what I mean. +1

Cc @filipesilva

**Comment by filipesilva** [comment]
What do you think of the fix in https://github.com/angular/angular-cli/pull/8875?
