### ISSUE TITLE
Debug server code [Question]

### ISSUE THREAD

**Issue by manzonif** [angular/angular-cli#8623]
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.3
Node: 9.2.0
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.3
@angular/flex-layout: 2.0.0-beta.10
@angular/material: 2.0.0-beta.12
@angular/platform-server: 5.0.2
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.3
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps
Build Universal app with:

* `ng build --app 1 --prod --output-hashing=false` etc.
* Launch dist/server.js 
* Attach VS Code to server process
* Debug specific server code (isPlatformServer blocks)

### Observed behavior
When I try to debug server code, the only way I found, is trough "server/main.bundle.js" file, that is minified and hard to debug.
I tried : ng build --app 1 --prod --output-hashing=false --sourcemaps=true --build-optimizer=false
but nothing changes, (there is not source maps for main.bundle.js)

### Desired behavior
Waiting for ng serve for platform server, is there a more confortable way to debug on server?

**Comment by severinbeauvais** [comment]
Have you see this?
https://github.com/Microsoft/vscode-recipes/tree/master/Angular-CLI

**Comment by manzonif** [comment]
I'm talking about Aungular universal app. 
So I need to debug server app main.bundle.js in dist/server folder that is minified and without source map.

Specifically the code running in isPlatformServer blocks.

```
if (isPlatformServer(this.platformId)) {
     // Server only code.
     ...
   }
```

**Comment by mgechev** [comment]
For support requests, we'd recommend to use Gitter or StackOverflow. In case I've misunderstood, please consider opening a new issue following the template and providing a demo where we can reproduce the problem. Thank you! :)
