### ISSUE TITLE
It would be nice if each version (including patches) of ng cli specified the latest available versions of ng / ng cli etc

### ISSUE THREAD

**Issue by williamBurgeson** [angular/angular-cli#8624]
Upon creating a new ng project with ng cli 1.5.3 set as global (`npm i -g @angular/cli`), in the package.json file the version of ng cli specified is 1.5.0.
It's not the end of the world but VS Code (and no doubt other IDEs) flag up a version mismatch warning.
Also, given we're now on ng 5, codelyzer also complains and you need to manually upgrade.
As I say, not the end of the world, but it might be worth considering for those dependencies (including angular itself of course) which are included by default that the latest major / minor / patch version available at the current time of release is specified in package.json.

**Comment by filipesilva** [comment]
We now do this, so I think the issue is resolved.
