### ISSUE TITLE
live reload is not working

### ISSUE THREAD

**Issue by dgouissem** [angular/angular-cli#8627]
Hello,
I'm using the latest version of angular cli, and Spring server as a middleware gateway to intercept urls for verification,  but for every change on typescript or html the live reload is  not working and i'm procedeeng to a manual refresh so the changes would be reflected to the ui. 

![image](https://user-images.githubusercontent.com/6916709/33214915-06d463d8-d12e-11e7-9350-7c91e619d167.png)

thank you in advance

best regards,

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

If I had to guess, it has to do with URL used. Maybe you're proxying some requests or something else that affects URLs, and live reload cannot find the right endpoint to ping for changes. 

Some of the URL related flags (like `--public-host`) on `ng serve` might help, see https://github.com/angular/angular-cli/wiki/serve. But ultimately this is very dependent on your setup.

**Comment by dgouissem** [comment]
Thank you.
