### ISSUE TITLE
How to debug the built version with angular-cli

### ISSUE THREAD

**Issue by HaythemJ** [angular/angular-cli#8628]
### Versions
```
Angular CLI: 1.5.0
Node: 9.0.0
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps

* ng build

### Observed behavior
```
All files are minified and cannot debug the production version
```

### Desired behavior
Is there an option to map ts files in order to debug the prod version?
The desired behavior is that it would be great if we can track bugs in the production version.

**Comment by Expometals** [comment]
You should put this in your tsconfig.json:

```
....
  "compilerOptions": {
    ....
    "sourceMap": true,
   ...
}
....
```
or can you try : 

`ng build --sourcemaps`

Look [here](https://github.com/angular/angular-cli/wiki/build)

**Comment by HaythemJ** [comment]
Great! Thank you! that is the trick!
