### ISSUE TITLE
After ng eject code coverage doesn't work

### ISSUE THREAD

**Issue by jbailey130** [angular/angular-cli#8631]
### Versions
```
@angular/cli: 1.2.0 (e)
node: 8.9.1
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.6
@angular/language-service: 4.2.6
```

### Repro steps
```ng eject```
``` npm run test```
Which executes
```"test": "karma start ./karma.conf.js --coverage"```

### Observed behavior
This includes a Chrome browser opening showing the tests which have been run and their success or failure.
```
> karma start ./karma.conf.js --code-coverage

 10% building modules 1/1 modules 0 active24 11 2017 11:37:01.144:WARN [karma]: No captured browser, open http://localhost:9876/
24 11 2017 11:37:01.154:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
24 11 2017 11:37:01.155:INFO [launcher]: Launching browser Chrome with unlimited concurrency
24 11 2017 11:37:01.158:INFO [launcher]: Starting browser Chrome                                    24 11 2017 11:37:11.369:WARN [karma]: No captured browser, open http://localhost:9876/
24 11 2017 11:37:12.014:INFO [Chrome 62.0.3202 (Windows 10 0.0.0)]: Connected on socket ifhsPZiglUWUyaL_AAAA with id 52178328
```

### Desired behavior
A coverage folder with an HTML file with code coverage or printing in the console the code coverage. It would be really cool to be able to set thresholds.

I can include any files if necessary but after the ejection, I have not modified the webpack.config.js nor the karma.conf.js.

**Comment by filipesilva** [comment]
When you run `ng eject`, the npm `test` script will not have the `--coverage` flag. That flag does not exist for the Karma test runner.

Ejecting means that you're leaving the CLI build system and you must set up your own unit test and e2e test build setups. This is something you have to configure yourself.

**Comment by ugurk** [comment]
In case someone hits that issue: your `karma.conf.js` should have `angularCli` section like this:

```
    angularCli: {
      environment: 'dev',
      codeCoverage: true
    }
```
