### ISSUE TITLE
Incorrect test steps for Bootstrap 4.x in "stories include bootstrap"

### ISSUE THREAD

**Issue by francesco-desensi** [angular/angular-cli#8634]
### Versions
N\A. Documentation issue

### Repro steps
* Go to https://github.com/angular/angular-cli/wiki/stories-include-bootstrap#testing-project-1
* Follow the steps for verifying the configuration

### Observed behavior
The page tells the user to verify that variables are being imported correctly by adding the following to _variables.scss

`$brand-primary: red;`

However, this variable is not used in the latest bootstrap 4.x versions (in my case bootstrap 4.0.2-beta). 

### Desired behavior
The documentation should be updated to say that for bootstrap 4.x use 

`$primary: red;`

**Comment by devoto13** [comment]
It should have been fixed by https://github.com/angular/angular-cli/pull/8564. Wondering why Wiki page is still showing old information.

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/8564, will be pushed to the wiki on the next release.
