### ISSUE TITLE
Can't use new command to create an angular-cli project?

### ISSUE THREAD

**Issue by rajukiran** [angular/angular-cli#8637]
Hi,

+ @angular/cli@1.5.4
added 976 packages in 256.78s
Node.js version:    v8.9.1
NPM version:        5.5.1
node_modules/.bin/ng version && ng new Example2 --directory ./ --skip-git

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.4
Node: 8.9.1
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/.DS_Store: error
@angular/cdk: 5.0.0-rc0-2667c01
@angular/cli: 1.5.4
@angular/material: 5.0.0-rc0-c088a0f
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.6.1
webpack: 3.8.1
You cannot use the new command inside an Angular CLI project.

How can i solve it?

Thank you.

**Comment by ADTC** [comment]
Make sure your current directory is empty. Suggest you to start with an empty directory (folder).

**Comment by rajukiran** [comment]
Sure I'm in the empty directory.

**Comment by filipesilva** [comment]
Like the error message says, you cannot use the new command inside an Angular CLI project. It is not supported.
