### ISSUE TITLE
ng serve should show an URL with the local IP address for convenience.

### ISSUE THREAD

**Issue by jiangjianyu** [angular/angular-cli#8639]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

When I run ng serve, I want to use the cell phone to open it(My computer and phone in the same Wifi).
Like reactjs. When you run 'npm start' ,you can see like this:
![2](https://user-images.githubusercontent.com/31642247/33237661-d390fac6-d2b4-11e7-8d4a-424b2fb5048f.png)

Angular is this:
![squ kz 0w21hb _ 86p](https://user-images.githubusercontent.com/31642247/33237642-15558036-d2b4-11e7-9371-3e66c7088a46.png)

Can you provide convenience for developers?

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by ADTC** [comment]
Good point. Btw, it's even more convenient to use your computer name instead of your local IP address (because the IP address can change but the name doesn't). Try it.

Assuming your computer name on the network is `jiangslaptop` try visiting `http://jiangslaptop:3000/` on your cell phone.

**Comment by ADTC** [comment]
Btw, I suggest you rename the issue to something like "ng serve should show an URL with the local IP address for convenience"
