### ISSUE TITLE
sourceMap error in css-loader and postcss-loader dependencies

### ISSUE THREAD

**Issue by soniar4i** [angular/angular-cli#8648]
Hello everyone,

After updating angular to the latest version I'm facing a sourceMap issue, everytime I try "ng serve" get an error related with css-loader and I don't know if I'm wrong but I get it as a dependency @angular/cli@1.5.4.

Thank you!

### Versions
```
"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "base-64": "^0.1.0",
    "codemirror": "^5.23.0",
    "core-js": "^2.4.1",
    "enhanced-resolve": "3.4.1",
    "jquery": "^3.1.1",
    "jquery-ui-dist": "^1.12.1",
    "jquery.scrollbar": "^0.2.11",
    "materialize-css": "^0.100.2",
    "rxjs": "^5.5.2",
    "web-animations-js": "^2.2.2",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.5.4",
    "@angular/compiler-cli": "^5.0.0",
    "@types/jasmine": "2.8.2",
    "@types/node": "~8.0.53",
    "codelyzer": "~4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "protractor": "~5.2.0",
    "ts-node": "~3.3.0",
    "tslint": "~5.8.0",
    "typescript": "2.4.2"
  }
```

### Observed behavior
```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss

```

**Comment by clydin** [comment]
We'll need some additional information to help track down the issue.  Can you provide the command that was run that generated the error?  Also the contents of `styles.scss` would be helpful, if possible.

Since the project was updated in place, executing an `npm update` may also be prudent to ensure the latest versions of all dependencies are installed.

**Comment by soniar4i** [comment]
Hi @clydin and thanks for your help.

As it is an "old project"  I was trying to update my dependencies, with the following steps:

1. Run npm update
2. npm install -g npm-check-updates
3. ncu -u
    Which generates:
```
{
  "name": "backtracking-admin",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve --port 8300",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor",
    "build:dev": "ng build --environment=dev",
    "build:master": "ng build --environment=master --target=production",
    "build": "ng build --environment=prod --target=production"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.3",
    "@angular/common": "^5.0.3",
    "@angular/compiler": "^5.0.3",
    "@angular/core": "^5.0.3",
    "@angular/forms": "^5.0.3",
    "@angular/http": "^5.0.3",
    "@angular/platform-browser": "^5.0.3",
    "@angular/platform-browser-dynamic": "^5.0.3",
    "@angular/router": "^5.0.3",
    "@omt/angular-common": "^1.2.5",
    "base-64": "^0.1.0",
    "codemirror": "^5.23.0",
    "core-js": "^2.4.1",
    "jquery": "^3.1.1",
    "jquery-ui-dist": "^1.12.1",
    "jquery.scrollbar": "^0.2.11",
    "materialize-css": "^0.100.2",
    "rxjs": "5.5.2",
    "web-animations-js": "^2.2.2",
    "zone.js": "^0.8.4",
    "enhanced-resolve": "3.4.1"
  },
  "devDependencies": {
    "@angular/cli": "1.5.4",
    "@angular/compiler-cli": "^5.0.3",
    "@types/jasmine": "2.8.2",
    "@types/node": "~8.0.53",
    "codelyzer": "~4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "protractor": "~5.2.0",
    "ts-node": "~3.3.0",
    "tslint": "~5.8.0",
    "typescript": "2.4.2"
  }
}
```

4. Then I change typescript to "2.4.2" because angular
5. npm install

And when trying to run the project I get the error 

`ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
Module build failed: 
@import "../node_modules/materialize-css/sass/components/mixins";
^
      File to import not found or unreadable: ../node_modules/materialize-css/sass/components/mixins.
Parent style sheet: stdin
      in /home/user/Documents/my-app/src/styles.scss (line 6, column 1)
Error: 
@import "../node_modules/materialize-css/sass/components/mixins";
^
      File to import not found or unreadable: ../node_modules/materialize-css/sass/components/mixins.
Parent style sheet: stdin
      in /home/user/Documents/my-app/src/styles.scss (line 6, column 1)
    at options.error (/home/user/Documents/my-app/node_modules/node-sass/lib/index.js:291:26)
 @ ./src/styles.scss 4:14-191
 @ multi ./node_modules/jquery-ui-dist/jquery-ui.min.css ./node_modules/codemirror/lib/codemirror.css ./node_modules/codemirror/addon/hint/show-hint.css ./node_modules/codemirror/addon/merge/merge.css ./src/styles.scss
`

Additionally The content of styles.scss

```
/* You can add global styles to this file, and also import other style files */
@charset "UTF-8";

// Mixins
// @import "components/prefixer";
@import "../node_modules/materialize-css/sass/components/color";
// Reset
@import "../node_modules/materialize-css/sass/components/normalize";

/**
 * Variables: this is the custom file to configure theme variables, define it in each project
 */
@import "app/utils/sass/variables";

// components
@import "../node_modules/materialize-css/sass/components/global";
@import "../node_modules/materialize-css/sass/components/icons-material-design";
@import "../node_modules/materialize-css/sass/components/grid";
@import "../node_modules/materialize-css/sass/components/navbar";
@import "../node_modules/materialize-css/sass/components/roboto";
@import "../node_modules/materialize-css/sass/components/typography";
@import "../node_modules/materialize-css/sass/components/cards";
@import "../node_modules/materialize-css/sass/components/toast";
@import "../node_modules/materialize-css/sass/components/buttons";
@import "../node_modules/materialize-css/sass/components/waves";
@import "../node_modules/materialize-css/sass/components/forms/forms";
@import "../node_modules/materialize-css/sass/components/table_of_contents";
@import "../node_modules/materialize-css/sass/components/preloader";


.primary {
    background-color: $primary-color;
    &.dark {
        background-color: $primary-color-dark;
    }
    &.darker {
        background-color: darken($primary-color-dark, 15%);
    }
    &.light {
        background-color: $primary-color-light;
    }
    &.lighter {
        background-color: lighten($primary-color-light, 15%);
    }
}

... more class styles
```

Don't know what else to add. Thank you so much for your help :)

**Comment by clydin** [comment]
Looks like version `0.100.2` of `materialize-css` no longer contains a `_mixins.scss` file.  ([contents of package](https://unpkg.com/materialize-css@0.100.2/sass/components/)). Are you using that file in your project somewhere?

**Comment by soniar4i** [comment]
Hi @clydin thank you so much for your help! yes, you're right materialize-css add new values that aren't defined in my styles and also deleted some stylesheets. Just got confused by the {"sourceMap":false,"importLoaders":1}! 

Sorry, It was my fault for no research a bit more :)

**Comment by Kalaijagdai** [comment]
[18.05.2017_15-38-06_Надеждин_Константин_Геннадьевич.pdf](https://github.com/angular/angular-cli/files/1633747/18.05.2017_15-38-06_._._.pdf)
