### ISSUE TITLE
quitting ng-serve also quits browser

### ISSUE THREAD

**Issue by Sibiraj-S** [angular/angular-cli#8651]
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.4
Node: 8.9.1
OS: linux x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular/tsc-wrapped: 4.4.6
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps
1. craft an application using angular-cli
2. ng serve -o (open browser)
3. CTRL+C quit the process which also quits browser with all tabs  :sob: 

### Desired behavior

Don't want to quit the entire browser with all tabs with it when I just kill only ng serve process.

**Comment by filipesilva** [comment]
That's odd, we don't have any control over the browser at all. Are you sure that's not a browser extension that's closing it? Can you try disabling all browser extensions and trying to repro?

**Comment by Sibiraj-S** [comment]
This doesn't happen often but sometimes. and only when the browser is opened via cli. If the browser is already open nothing happens. Also I have no extensions in my browser currently.

I have no clue why that happens

**Comment by Sibiraj-S** [comment]
@filipesilva . I was unable to pinpoint the problem. But this happens in almost all my projects. And at times, this is a pain. closing all other tabs

**Comment by clydin** [comment]
My guess would be that since the browser is not open before hand, the ng serve node process becomes the owner of the web browser process when the open option is used.  This may be an OS specific quirk.  The CLI uses the `opn` package to provide this functionality.

**Comment by Sibiraj-S** [comment]
any workaround? :confused:

**Comment by Sibiraj-S** [comment]
Seems to be fixed.
