### ISSUE TITLE
How can I run app using ng cli in a server which has no GUI?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [angular/angular-cli#8656]
# How can I run app using ng cli in a server which has no GUI?

![image](https://user-images.githubusercontent.com/18028768/33308707-79311126-d456-11e7-8e43-16caf9c3df97.png)

1. No GUI
2. No Bowser

> what should I do? Maybe a Proxy Web Server, like Apache OR Nginx ?

**Comment by xgqfrms-GitHub** [comment]
![image](https://user-images.githubusercontent.com/18028768/33308901-38c22f2a-d457-11e7-9205-e74ee7eaeb02.png)

> how can I access it?


![image](https://user-images.githubusercontent.com/18028768/33308938-60f235a8-d457-11e7-9a0b-10593f78512a.png)

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by xgqfrms-GitHub** [comment]
All right.
