### ISSUE TITLE
Angular 2 on openshift. Unable to bind the ng serve to the service hostname

### ISSUE THREAD

**Issue by ssaxena2017** [angular/angular-cli#8660]
### Versions
```
@angular/cli: 1.4.9
node: 6.11.5
os: darwin x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4
npm --version 3.10.10
```

### Repro steps

* Using openshift 3.6: catalogue node js 6
* code pulling from git repo. 
* successfully compiled but unable to bound to address provided by me.

Nodejs template for openshift:
https://github.com/sclorg/s2i-nodejs-container/tree/master/4

The issue is when I create a build for any git repo, the ng serve will start in the localhost and specified port. If I changed the hostname and port(in .angular-cli.json) to deploy in openshift pod, the ng serve fails saying unable to bound. I am trying to bind it to the service name. 
I also tried to do for the route but again it failed. Below logs are when i tried to bind to the route.

For service as host name i got the error unable to bound 
For route, below error.

Is there any way that i can bind the openshift service name to the ng serve? 

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

Environment:
--
  | DEV_MODE=false
  | NODE_ENV=production
  | DEBUG_PORT=5858
  | Launching via npm...
  | npm info it worked if it ends with ok
  | npm info using npm@3.10.9
  | npm info using node@v6.9.1
  | npm info lifecycle kamal@0.0.0~prestart: kamal@0.0.0
  | npm info lifecycle kamal@0.0.0~start: kamal@0.0.0
  |  
  | > kamal@0.0.0 start /opt/app-root/src
  | > ng serve
  |  
  | getaddrinfo ENOTFOUND http://autoscaler-ui5-openshift-infra.192.168.99.100.nip.io
  | Error: getaddrinfo ENOTFOUND http://autoscaler-ui5-openshift-infra.192.168.99.100.nip.io
  | at errnoException (dns.js:28:10)
  | at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  |  
  | npm info lifecycle kamal@0.0.0~start: Failed to exec start script
  | npm ERR! Linux 4.4.41-boot2docker
  | npm ERR! argv "/opt/rh/rh-nodejs6/root/usr/bin/node" "/opt/rh/rh-nodejs6/root/usr/bin/npm" "run" "-d" "start"
  | npm ERR! node v6.9.1
  | npm ERR! npm  v3.10.9
  | npm ERR! code ELIFECYCLE
  | npm ERR! kamal@0.0.0 start: `ng serve`
  | npm ERR! Exit status 1
  | npm ERR!
  | npm ERR! Failed at the kamal@0.0.0 start script 'ng serve'.
  | npm ERR! Make sure you have the latest version of node.js and npm installed.
  | npm ERR! If you do, this is most likely a problem with the kamal package,
  | npm ERR! not with npm itself.
  | npm ERR! Tell the author that this fails on your system:
  | npm ERR!     ng serve
  | npm ERR! You can get information on how to open an issue for this project with:
  | npm ERR!     npm bugs kamal
  | npm ERR! Or if that isn't available, you can get their info via:
  | npm ERR!     npm owner ls kamal
  | npm ERR! There is likely additional logging output above.
  |  
  | npm ERR! Please include the following file with any support request:
  | npm ERR!     /opt/app-root/src/npm-debug.log

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
