### ISSUE TITLE
Does the browser automatically refresh after code change with ng build -w & node server.js

### ISSUE THREAD

**Issue by Jackclarify** [angular/angular-cli#8672]
#

### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```
ng --version 1.5.0/1.5.4
win 10 bit-64
node: 8.5.0
npm: 5.3.0

### Repro steps

* Step 1
run the script in package.json 
`
  "dev": "parallelshell \"ng build -w \"  \"cross-env NODE_ENV=development node .\" ",
`
It compiles automatically after code change, but the browser is not refreshed.

It is not work when I add the '--polling=1000' following the ng build.

But it is work with the ng serve.

My editor is sublime 3.0

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```
It compiles automatically after code(both template and script code) change, but the browser is not refreshed when the template changed.

### Desired behavior

It compiles automatically after code(especially template) change, the browser can be refreshed when the template changed.

So I want to know if it is not work to live reload in browser with ng build -w at all or any other method?
we want to run our server.js not the webpack dev server. 

Since we need to route to many api, include local and other domain(only some stable domain can visit), 
I try to use the proxy-config.js
 ```
   {
        context: [
            "/login",
            "/i18n/en.json",
            "/oauth/ro",
            "/i",
            "/need",
            "/to",
            "/proxy"
        ],
        target: "http://localhost:3000",
        secure: false,
        logLevel: "debug"
    }
```
,
```
    {
        context: [
            "/socket.io"
        ],
        target: "https://staging.clarifyhealth.com",
        secure: false,
        logLevel: "debug",
        changeOrigin: true
    }
```
,
```
    {
        context: [
            "/oauth/ro"
        ],
        target: "https://clarifyhealth.auth0.com",
        secure: false,
        logLevel: "debug",
        changeOrigin: true
    }
```
or proxy.conf.json file 
```
{
  "/oauth/ro": {
    "target": "https://clarifyhealth.auth0.com",
    "secure": false,
    "pathRewrite": {
      "^/oauth/ro": ""
    },
    "changeOrigin": true
  }
}
```
Or can we combine those two categories(.json,.js) files? 

Any suggestion appreciate.
Thanks
@filipesilva

**Comment by filipesilva** [comment]
Live-reload functionality is something that servers provide. `ng build -w` only builds files and not serve them. If you are using your own custom server where you serve the built files in `dist/`, then you will have to provide your own live-reload functionality.
