### ISSUE TITLE
ng serve not detecting file changes for recompiles 

### ISSUE THREAD

**Issue by aruncnt** [angular/angular-cli#8673]
@angular/cli: 1.0.3
node: 6.12.0
os: linux x64
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.0.3
@angular/compiler-cli: 4.4.6

**Comment by filipesilva** [comment]
There wasn't much detail in your issue but I think it's overall a duplicate of https://github.com/angular/angular-cli/issues/1610. Please have a look there for common causes of reload not working.

**Comment by saimzishan** [comment]
Most of the times in Linux, ng serve --watch or ng build --watch doesn't work if the directory doesn't have sufficient permissions.

The solution is either to provide the necessary permissions or to use  sudo instead.

**Comment by lawipac** [comment]
what are the necessary permissions then?

**Comment by saimzishan** [comment]
try with sudo ng serve.

**Comment by andreadompe** [comment]
echo 65536 | sudo tee -a /proc/sys/fs/inotify/max_user_watches
