### ISSUE TITLE
Share Variables Between TypeScript and Sassi in angular-cli

### ISSUE THREAD

**Issue by PhilippSoehnlein** [angular/angular-cli#8674]
The article [How to Share Variables Between Javascript and Sass](https://blog.bluematador.com/posts/how-to-share-variables-between-js-and-sass/) claims that, with the correct webpack configuration, one can share SASS-variables with JavaScript.

Can the angular-cli webpack config be altered to support this mechanism? It looks like it doesn't work out of the box.

**Comment by filipesilva** [comment]
We don't provide webpack config overrides, and you can read more about why in https://github.com/angular/angular-cli/issues/1656.

There is an extension mechanism planned for the future though (https://github.com/angular/angular-cli/issues/2906).
