### ISSUE TITLE
how to turn on module resolution stats provided by typescript compiler for an  angular cli app?

### ISSUE THREAD

**Issue by venkataraghu** [angular/angular-cli#8676]
I would like to trace moduleResolution stats while compiling app code. the compiler is not printing details on how modules resolved.  Is this expected?

my tsconfig.app.json is like this
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "traceResolution": true,
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  }
}

tsconfig

### Versions
Angular CLI: 1.5.4
Node: 8.9.1
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1
```



### Observed behavior
$ ng build --app 1
Date: 2017-11-29T12:28:09.911Z
Hash: 289e296055d0854f9bc4
Time: 6474ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 7.81 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 200 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.4 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.29 MB [initial] [rendered]

### Mention any other details that might be useful (optional)
I am trying to merge two apps at runtime and generate webpack assets. traceResolution stats would be helpful in debugging issue with my tsconfig files.

**Comment by filipesilva** [comment]
This sounds like a bug. If you set the option in tsconfig it should work. WDYT @hansl ?

**Comment by ensonic** [comment]
Same here :/

**Comment by slavafomin** [comment]
Any progress on this? I can't enable the `traceResolution` either. Is there a workaround maybe?

**Comment by lambidu** [comment]
UP! Still doesn't work :(

```
Angular CLI: 6.0.8
Node: 8.11.2
OS: win32 x64
Angular: 6.0.6
```

**Comment by mccainz** [comment]
Definitely hurting our debugging efforts.
