### ISSUE TITLE
Environment flags not working

### ISSUE THREAD

**Issue by chadbr** [angular/angular-cli#8678]
Looks like a regression of #7138

see last 5 comments in #7138

**Comment by filipesilva** [comment]
Answered in https://github.com/angular/angular-cli/issues/7138#issuecomment-348155326.

**Comment by chadbr** [comment]
@filipesilva seems to work with a new project created with 1.5.5.

Do you still want the repo?

**Comment by filipesilva** [comment]
If it works I think it's fine. But be aware of https://github.com/angular/angular-cli/issues/7305, as this is a known bug.

**Comment by chadbr** [comment]
thanks for the heads up on #7305 -- it seems like reasonable behavior to me. (I re-tested that the tests work on spec change - all good...)

**Comment by nicholasserra** [comment]
@chadbr Did you find a reliable fix for this? I can't get environments correctly switching on 1.5.5 or the latest release.
