### ISSUE TITLE
Server-side rendering build errors because of compilerOptions in tsconfig.server.json

### ISSUE THREAD

**Issue by kblestarge** [angular/angular-cli#8679]
### Versions
```
Angular CLI: 1.5.0
Node: 6.9.3
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack-bundle-analyzer: 2.9.0
webpack: 3.8.1

macOS Sierra version 10.12.6
```

### Repro steps

I am trying to upgrade my current cli app to support server-side rendering.
* Followed [this tutorial](https://medium.com/@cyrilletuzi/angular-server-side-rendering-in-node-with-express-universal-engine-dce21933ddce).
* Created a tsconfig.server.json file with the compilerOptions looking like this:
```
"compilerOptions": {
    "outDir": "../out-tsc/server",
    "module": "commonjs",
},
```
* `ng build --prod --app universal --output-hashing=none`
* The build errors out with errors shown below

### Observed behavior
Tons of errors from the build failing. For example:
```
error TS1219: Experimental support for decorators is a feature 
that is subject to change in a future release. Set the 'experimentalDecorators' 
option to remove this warning.

error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.

node_modules/@angular/platform-browser/src/browser/browser_adapter.d.ts(111,22): 
error TS2304: Cannot find name 'Element'.

node_modules/@angular/common/src/dom_tokens.d.ts(17,47): error TS2304: 
Cannot find name 'Document'.

node_modules/@angular/material/datepicker/typings/datepicker-input.d.ts(15,20): 
error TS2304: Cannot find name 'HTMLElement'.

etc.
```
I am, however, able to successfully build the server-side app if I change the complierOptions in the tsconfig.server.json to this:
```
"compilerOptions": {
    "outDir": "../out-tsc/server",
    "module": "commonjs",
    "experimentalDecorators": true,
    "target": "es5",
    "lib": ["es6", "dom"]
},
```
Those three extra options make all the difference, but obviously server-side rendering shouldn't require anything dom related...
### Desired behavior
I want my app to compile successfully without the three extra compilerOptions (experimentalDecorators, target, lib) because my Node Express server doesn't work with the current dom build (I'm see `Unexpected token import` errors after running `node server.js`). Why am I seeing the build errors I am seeing? I especially don't understand why I am seeing so many angular materials errors --I thought materials supports Universal as of recently.

**Comment by kblestarge** [comment]
@Brocco @hansl @filipesilva any suggestions?

**Comment by hansl** [comment]
Seems like you didn't follow the tutorial on our stories. See this: https://github.com/angular/angular-cli/wiki/stories-universal-rendering

Closing this as it's not an issue or a feature request. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by kblestarge** [comment]
@hansl my apologies, I have updated the issue to reference the official wiki tutorial which I did in-fact follow.

I understand your support issue concern and I will respect it by posting on stackoverflow. It would be nice, however, to receive any insights you are willing to give regarding the errors.
