### ISSUE TITLE
templateUrls should allow relative urls.

### ISSUE THREAD

**Issue by NullVoxPopuli** [angular/angular-cli#868]
This is a huge pain point when refactoring.

I don't want to have to specify the the full path, relative to the app root for all my components.
almost always, the templateURL is going to be `"./template.html"`

:-\

**Comment by SergeySolonko** [comment]
if you pass module.id to component moduleId you don't need to specify entire path to it. Same for tests

**Comment by tapas4java** [comment]
Use `moduleId` like below:

`@Component({
  moduleId: module.id,
  selector: 'ac-login',
  templateUrl: 'login.component.html',
  styleUrls: ['login.component.css']
})`

**Comment by NullVoxPopuli** [comment]
so, instead of 

```javascript
@Component({
  selector: 'home',
  templateUrl: 'template.html',
  directives: [ROUTER_DIRECTIVES, PortalNavigationComponent],
})
```

I would do:

```javascript
@Component({
   moduleId: module.id,
  selector: 'home',
  templateUrl: 'template.html',
  directives: [ROUTER_DIRECTIVES, PortalNavigationComponent],
})
```

?

that appears to have worked.

Why isn't this behavior implicit?

**Comment by SergeySolonko** [comment]
https://angular.io/docs/ts/latest/api/core/index/ComponentMetadata-class.html look at **moduleId** property

Also if you'll create components with CLI it already does this thing for you and you'll miss it

**Comment by NullVoxPopuli** [comment]
yeah, but, I guess, why doesn't angular-cli _assume_ a few possibilities of what the template could be?

anywho, you've resolved the issue!
