### ISSUE TITLE
ng xi18n with locale different than en not changing source-language

### ISSUE THREAD

**Issue by jeffarese** [angular/angular-cli#8680]
### Versions
```
Angular CLI: 1.5.0
Node: 8.9.0
OS: linux x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc.1
@angular/cli: 1.5.0
@angular/material: 5.0.0-rc.1
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps

* Create new project with any i18n tags, for example: `<h1 i18n>Hola</h1>`
* Try to generate the `es` translation files 
* `ng xi18n -op src/locale --outFile es.xlf -l es`

### Observed behavior
* The generated es.xlf file has:  `<file source-language="en" datatype="plaintext" original="ng2.template">`

### Desired behavior
* The generated es.xlf file should have:
`<file source-language="es" datatype="plaintext" original="ng2.template">`
with `source-language="es"`

**Comment by avilv** [comment]
same here..

**Comment by avilv** [comment]
submitted a PR #8861
