### ISSUE TITLE
Global option to --skip-install for new projects

### ISSUE THREAD

**Issue by Sibiraj-S** [angular/angular-cli#8684]
### Versions
```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.5
Node: 8.9.1
OS: linux x64
Angular: 
...
```

#### FEATURE REQUEST

Currently, a new project can be scaffolded using `ng new myProject`. which by default uses `npm` to install `node_modules`. and, we can also set `yarn` instead of `npm`.

Installation time for the packages by `cli` is always greater than manual `npm install` or `yarn install`.

Hence there is an option to skip install the `npm packages` by using `ng new myProject --skip-install`.

Can we globally set an option to `skip install` the packages `globally` for all new projects?

**Comment by filipesilva** [comment]
I think it would be better to fix whatever it makes it slow than to add new functionality that is essentially an workaround. 

Is there anything you can tell me about the difference in installation time? I know these things are hard to diagnose but since I can't reproduce I have to rely on user reports to figure it out.

For instance what is the time difference? Do you see any different logging messages?

**Comment by Sibiraj-S** [comment]
@filipesilva .

In my PC. I made a rough calculation

**2Minutes-5sec.**
Installation via `ng new myProject`

**40seconds**
1. ng new myProject --skip-install
2. cd myProject
3. npm install (took 40s)

> I think it would be better to fix whatever it makes it slow than to add new functionality that is essentially an workaround.

I was just saying If an option to set skip install for new projects globally will be a nice one not stating as a workaround.

**Comment by clydin** [comment]
npm caches packages so if the test was done in that exact order than the second (`--skip-install` variant) is guaranteed to be faster in this scenario based simply on npm's internal behavior not that `--skip-install` is inherently faster.

**Comment by Sibiraj-S** [comment]
I didn't mean what you said @clydin. I understand both are different actions. 

> npm's internal behavior not that --skip-install is inherently faster.

I am just saying instead of `--skip-install` every time you create a project. Can have an option globally to set the action for all new projects.

It is just an FR to have that option globally.

**Comment by adeshb** [comment]
Hi All,

Do not know how, but on my laptop it takes a lot of time, as below

C:\Users\admin\Desktop\learn\Angular\angular.io\sampleProj>npm install yarn -g
C:\Users\admin\AppData\Roaming\npm\yarn -> C:\Users\admin\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js
C:\Users\admin\AppData\Roaming\npm\yarnpkg -> C:\Users\admin\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js
+ yarn@1.6.0
added 1 package in 6.137s

C:\Users\admin\Desktop\learn\Angular\angular.io\sampleProj>yarn
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.3: The platform "win32" is incompatible with this module.
info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 1138.66s.
