### ISSUE TITLE
load templateUrl from remote serve or CDN link 

### ISSUE THREAD

**Issue by sksushil999** [angular/angular-cli#8685]
FEATURE REQUEST

**Currently, I am not able to load templateUrl from the remote server.**
If  this would be possible,  then we can putt our all HTML and CSS file on CDN or Other server and we can change or update those HTML and CSS files with no need to build again whole angular project

**Can this possible to load temaplateUrl and styleUrls at runtime?**

**Comment by clydin** [comment]
This would prevent the application from taking advantage of AOT which compiles the templates at build time.  There are large advantages to using AOT; including increased performance and smaller script bundle sizes.

**Comment by anilhurmuz** [comment]
is there anyway to load templateUrl from the link?

**Comment by hansl** [comment]
This is never going to be supported officially (for multiple reason, security being one of them). The official Angular documentation suggest using Angular Elements and injecting the template as HTML in the page. Our own angular.io website does that and can be used as an example.

Closing this as out of scope.
