### ISSUE TITLE
`ng serve` not detecting file changes after executing `ng build`

### ISSUE THREAD

**Issue by hbsoftco** [angular/angular-cli#8690]
Ubuntu 16.04
Angular CLI: 1.5.5
Node: 8.9.1

**Comment by clydin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
