### ISSUE TITLE
Update Node ERROR

### ISSUE THREAD

**Issue by joaovelozo** [angular/angular-cli#8700]
C:\>npm install -g update-node
npm ERR! not a package C:\update-node
npm ERR! addLocal Could not install C:\update-node
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\node.exe" "C:\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "update-node"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path C:\Users\JOAOVE~1\AppData\Local\Temp\npm-5072-e9eb08b6\unpack-a7f300429672\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\JOAOVE~1\AppData\Local\Temp\npm-5072-e9eb08b6\unpack-a7f300429672\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

**Comment by clydin** [comment]
This doesn’t appear to be related to the Angular CLI and may have been opened in error.
