### ISSUE TITLE
npm ERR! code EINTEGRITY

### ISSUE THREAD

**Issue by Dongle74** [angular/angular-cli#8702]
13460 verbose stack Error: sha1-PFtv1/beCRQmkCfwPAlGdY92c6Q= integrity checksum failed when using sha1: wanted sha1-PFtv1/beCRQmkCfwPAlGdY92c6Q= but got sha1-XHn8+gREIQ2MVGrEoKyDNZgsTD8=. (274843 bytes)
13460 verbose stack     at Transform.on (D:\Software\Programs\nodejs\node_modules\npm\node_modules\ssri\index.js:275:19)
13460 verbose stack     at emitNone (events.js:111:20)
13460 verbose stack     at Transform.emit (events.js:208:7)
13460 verbose stack     at endReadableNT (_stream_readable.js:1056:12)
13460 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
13460 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
13461 verbose cwd C:\Users\Kevin
13462 verbose Windows_NT 10.0.15063
13463 verbose argv "D:\\Software\\Programs\\nodejs\\node.exe" "D:\\Software\\Programs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
13464 verbose node v8.9.0
13465 verbose npm  v5.5.1
13466 error code EINTEGRITY
13467 error sha1-PFtv1/beCRQmkCfwPAlGdY92c6Q= integrity checksum failed when using sha1: wanted sha1-PFtv1/beCRQmkCfwPAlGdY92c6Q= but got sha1-XHn8+gREIQ2MVGrEoKyDNZgsTD8=. (274843 bytes)
13468 verbose exit [ 1, true ]

**Comment by clydin** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
