### ISSUE TITLE
Zone Error with Angular 4 Universal

### ISSUE THREAD

**Issue by qlaffont** [angular/angular-cli#8710]
### Versions
```
Angular CLI: 1.5.0
Node: 8.1.3
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular/platform-server: 5.0.4
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.6.1
webpack: 3.8.1
```

### Repro steps
https://github.com/angular/angular-cli/wiki/stories-universal-rendering 

### Observed behavior
```
Go to localhost:4000 and get : 

Unhandled Promise rejection:  ; Zone: <root> ; Task: Promise.then ; Value: { [Error]
  __zone_symbol__currentTask:
   ZoneTask {
     _zone:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } } undefined
```

### Desired behavior
Page display

**Comment by clydin** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by qlaffont** [comment]
If you want, I can share you directly my repo. If not, no problem i create a new projet.

**Comment by elSuperRiton** [comment]
Any news ? Facing the same issue here and not much info to debug where this comes from :(

**Comment by ceaguilera** [comment]
How did you solve? I have the same problem and I can not find a solution, help!

**Comment by ceaguilera** [comment]
carlos@carlos-linux:~/Proyectos/website$ node dist/server.js
listening on http://localhost:4000!
ERROR { [Error]
  __zone_symbol__currentTask: 
   ZoneTask {
     _zone: 
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }

**Comment by kvincent3** [comment]
Someone find a solution to this issue ?
