### ISSUE TITLE
Undocumented ng generate params?

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular-cli#8715]
### Versions
```
Angular CLI: 1.5.5
Node: 6.9.5
OS: win32 x64
Angular: 5.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.5
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.8
typescript: 2.6.2
webpack-bundle-analyzer: 2.9.1
webpack: 3.8.1
```

### Repro steps
* Launch Webstorm 2017.3
* Open a cli project
* Right click on app -> new -> angular cli

### Observed behavior
![image](https://user-images.githubusercontent.com/6654388/33491575-f916f278-d6ba-11e7-90de-ecbe3f2111d1.png)

### Desired behavior
I don't know...

### Mention any other details that might be useful (optional)
I've looked at your wiki and didnt find those parameters of ng generate. 
What do they do? The names sound interesting.

**Comment by joshuacolvin** [comment]
I'd be happy to work on this.

**Comment by artem-galas** [comment]
@joshuacolvin Do you consider to open PR?

**Comment by mgechev** [comment]
Looks like we already have this here https://angular.io/cli/generate#universal. If I'm missing anything, feel free to open a new issue. Thanks!
