### ISSUE TITLE
Different tsconfig.json based on environment

### ISSUE THREAD

**Issue by markgoho** [angular/angular-cli#8718]
### Versions
``` bash
Angular CLI: 1.6.0-rc.1
Node: 8.9.1
OS: win32 x64
Angular: 5.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.6.0-rc.1
@angular/material: 5.0.0-rc.2
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0-rc.1
@schematics/angular: 0.1.8
typescript: 2.6.2
webpack-bundle-analyzer: 2.9.1
webpack: 3.8.1
```

### Repro steps

* `ng build --prod` or `ng build`

### Observed behavior
```
Files build
```

### Desired behavior
I'd like to know if it's possible to use a different `tsconfig.json` file based on environment. Specifically, I'd like to target es6 in dev (developing just in chrome) and es5 in prod (need to support IE11).

### Mention any other details that might be useful (optional)
Similarly, I'm wondering if there's a way to conditionally load polyfills based on environment.

**Comment by clydin** [comment]
The best that can be done is to setup an additional app in `.angular-cli.json` which contains the same settings as the existing app but points to a different tsconfig.  The same would apply to the polyfills.  The `--app` option can then be used to build the desired app configuration.

**Comment by markgoho** [comment]
Thanks @clydin -- this seems to be a pretty easy option. I'll give this a shot and report back. Would you think others might appreciate a CLI Story based on the usage pattern?

**Comment by clydin** [comment]
A general user story discussing the pattern may be useful.  However this particular use case may be too specific for a story in and of itself.

**Comment by Viktor-Bredihin** [comment]
is there any solution?
