### ISSUE TITLE
default route creating not working on WIN10

### ISSUE THREAD

**Issue by MarkStruik** [angular/angular-cli#872]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
angular-cli: 1.0.0-beta.5
node: 5.11.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
np new MyApp
cd MyApp
np serve
--> starts app correctly
ng g route hero
browse http://localhost:4200/hero
hero default part not loaded

the hero.component.js is loading in browser. but somehow the content is not showing

**Comment by hansl** [comment]
There's a bug in router itself where if you don't have a `[routerLink]` it will not instanciate the route properly. Try that, comment here if it doesn't solve.

**Comment by MarkStruik** [comment]
Check that does the trick! thanks for the reply!

**Comment by fmoessle** [comment]
If your route is /start, try to add:

> `<a [routerLink]="['/start']">It Works!</a>`

in the .html  of your component
