### ISSUE TITLE
RXJS lettable operators

### ISSUE THREAD

**Issue by elvirdolic** [angular/angular-cli#8720]
There are severals discussions around the rxjs imorts.

Does the CLI handle this correctly? 

import {map} from 'rxjs/operators/map';

Vs

import {map} from 'rxjs/operators';

In which case does tree shaking work in CLI projects?

**Comment by kylecordes** [comment]
Functionally, this works great, my group is using it on multiple projects already.

We have not yet verified whether the tree shakes correctly with CLI; hopefully someone from the team can answer that part.  It should do so, but there could be some tweak yet needed. (If you need to deploy shortly in a case where the bundle size is vital, just try it and see if it affects your bundle size.)

**Comment by elvirdolic** [comment]
We have changed everything to lettable imports like this: import {map} from 'rxjs/operators';

No change in payload after migration. This is the reason I was asking.

**Comment by devoto13** [comment]
Both ways should support tree shaking. In my case I get a slight bundle size increase when importing from `rxjs/operators` instead of long import (499K vs 496K), which is probably caused by inclusion of file with re-exports of all operators. In both cases `source-map-explorer` indicates that no extra operators are included.

**Comment by hccampos** [comment]
Shouldn't matter either way, but the terser version is way easier to maintain and read.

Anyway, in RxJS 6 you'll be able to import everything from 'rxjs' which will be awesome if it can be properly tree shaken.

**Comment by deebloo** [comment]
@elvirdolic like @devoto13 said it should work correctly

**Comment by Splaktar** [comment]
I also saw my bundle size increase by 10 KB as RxJS increased from 60 KB to 122 KB when using the new lettable operators. I also mentioned this in https://github.com/angular/angular-cli/issues/8854#issuecomment-354532989. Still looking for the issue that is tracking this bundle increase bug.
