### ISSUE TITLE
OTS parsing error with AOT and font duplication

### ISSUE THREAD

**Issue by Looted** [angular/angular-cli#8735]
After upgrading whole Angular stack to version 5 (with @angular/cli at 1.5.5) I'm getting corrupted web fonts (OTS parsing error). The issue happens when the font is included multiple times (for example when sass partial containing the font face is imported in two components).
### Versions
```
Angular CLI: 1.5.5
Node: 8.9.1
OS: win32 x64
Angular: 5.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cli: 1.5.5
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.8
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps
Example repo: https://github.com/Looted/OTS-parsing-error
* Clone the repo, install deps with yarn, then run `yarn start`.
* With the page and the console opened in Chrome, go to test-component/test.component.scss and save it, which results in page reload and warnings in the console.

### Observed behavior
The console outputs warnings:
```
Failed to decode downloaded font: http://localhost:4200/fontawesome-webfont.68560c510686599ffbc9.woff2
localhost/:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
localhost/:1 Failed to decode downloaded font: http://localhost:4200/fontawesome-webfont.a7bbeb589ae63e018872.woff
localhost/:1 OTS parsing error: incorrect file size in WOFF header
localhost/:1 Failed to decode downloaded font: http://localhost:4200/fontawesome-webfont.e1dd9adb4f69bb9a0bdc.ttf
localhost/:1 OTS parsing error: incorrect entrySelector for table directory
```
The duplicated font files are in fact corrupted when using web validator.

### Desired behavior
In previous version of Angular/Angular Cli  there were no console warnings and no duplicated/corrupted font files when including same partial in multiple components. Working setup is as follows:
````
@angular/cli: 1.4.2
node: 8.9.1
os: win32 x64
@angular/animations: 4.4.2
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.4.2
@angular/compiler: 4.4.2
@angular/core: 4.4.2
@angular/forms: 4.4.2
@angular/http: 4.4.2
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.4.2
@angular/platform-browser-dynamic: 4.4.2
@angular/platform-server: 4.4.2
@angular/router: 4.4.2
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.2
typescript: 2.5.2
 ````

**Comment by clydin** [comment]
This should be corrected in 1.6.3.  If the error is still occurring, please re-open the issue.
