### ISSUE TITLE
npm ERR! code ELIFECYCLE , errno 3221226356

### ISSUE THREAD

**Issue by tapassingh** [angular/angular-cli#8739]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
npm : 5.5.1

@angular/cli: 1.2.4
node: 6.9.1
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.2.4
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
```

### Repro steps

*ng new apm
*cd apm
*ng serve/ npm start

### Observed behavior
```
webpack: Compiled successfully.
npm ERR! code ELIFECYCLE
npm ERR! errno 3221226356
npm ERR! apm@0.0.0 start: `ng serve -o`
npm ERR! Exit status 3221226356
npm ERR!
npm ERR! Failed at the apm@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Desired behavior
It should run at-least. One interesting thing, one moment it worked when I made global and local CLI version same. That time the issue was, the ng live server was not detecting any file change. I made the title change in .ts file, after that it stopped working. I reverted my code, still its throwing the above error.

**Comment by clydin** [comment]
It appears the version of the CLI being used is fairly old.  Please try updating to the latest stable version (1.5.5 at this time).  After this please try running `ng serve` directly and report back any errors encountered.

**Comment by tapassingh** [comment]
> I have updated the CLI, now its not throwing error, but not launching the page also. Looks like NG Live development Server starts and then stops.

>Angular CLI: 1.5.5
>Node: 6.9.1
>OS: win32 x64
>Angular: 5.0.5
>... animations, common, compiler, compiler-cli, core, forms
>... http, language-service, platform-browser
>... platform-browser-dynamic, router

`@angular/cli: 1.5.5`

`@angular-devkit/build-optimizer:` 0.0.34
`@angular-devkit/core: 0.0.22
`@angular-devkit/schematics: 0.0.39
`@ngtools/json-schema: 1.1.0
`@ngtools/webpack: 1.8.5
`@schematics/angular: 0.1.9
`typescript: 2.4.2
`webpack: 3.8.1

**Output of ng serve**
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2017-12-06T06:03:30.026Z
Hash: 036b38f4b2042e626728
Time: 91416ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 76.3 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 546 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 33.8 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 10.7 MB [initial] [rendered]

webpack: Compiled successfully.

**After the above line, it comes back to the drive. When I go to localhost:4200, I get localhost refused to connect.**

**Comment by tapassingh** [comment]
Yes. It comes back to command prompt without user interaction. I ran only ng serve, nothing else.

**Comment by clydin** [comment]
Something on your system appears to be killing the process.  The only thing I could suggest is to try a different port via `-port <number>`.  Otherwise this seems to be an issue that is particular to your system/system configuration.  As a result, this doesn't appear to be an issue with the CLI itself.  If your further investigation provides information to suggest otherwise, please re-open the issue.  Also, asking on a site such as StackOverflow may be useful.

**Comment by amitshelke** [comment]
Error: Cannot find module './replaceStringTransformer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\LR25\node_modules\common-tags\lib\index.js:28:34)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:53

Please help me out to solve this error
