### ISSUE TITLE
Meta, Title packages from '@angular/platform-browser', not showing title and description in view-source

### ISSUE THREAD

**Issue by jvkiran** [angular/angular-cli#8743]
import { Injectable } from '@angular/core';
import { Meta } from '@angular/platform-browser';
import { Title } from '@angular/platform-browser';

@Injectable()
export class SeoService {
    
    private titleService: Title;
    private metaDescriprtion: Meta

    constructor(
        private _meta: Meta,
        private _titleService: Title
    ) {}

    public setTitle(newTitle: string) {
        this._titleService.setTitle(newTitle);
    }

    public setMetaDescription(description: string) {
        this._meta.addTag({name: "description", content: description})
    }
}

Above code does't show title and description in view-source.

**Comment by clydin** [comment]
This does not appear to be Angular CLI related.  A better forum for support concerns would be a site such as [StackOverflow](http://stackoverflow.com/).  If the observed behavior is determined to be a defect then opening an issue at core [Angular Repository](https://github.com/angular/angular/issues) would be the appropriate location.
