### ISSUE TITLE
ngsw-config

### ISSUE THREAD

**Issue by mackelito** [angular/angular-cli#8746]
### Versions
```
Angular CLI: 1.6.0-rc.2
Node: 8.9.1
OS: darwin x64
Angular: 5.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.6.0-rc.2
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.0-rc.2
@angular/service-worker: 5.0.5
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.39
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0-rc.2
@schematics/angular: 0.1.9
typescript: 2.4.2
webpack-bundle-analyzer: 2.9.0
webpack: 3.10.0
```

### Desired behavior

Is there a way to generate the ngsw-config.json file? Or can I see the default one somewhere?

**Comment by clydin** [comment]
Creating a new project with the `--service-worker` option should create the file.
The template for the file is located here: https://github.com/angular/devkit/blob/master/packages/schematics/angular/application/files/__path__/ngsw-config.json

**Comment by mackelito** [comment]
@clydin is there a wiki or so with the available settings?
