### ISSUE TITLE
Cannot install angular/cli on windows 10 via npm

### ISSUE THREAD

**Issue by AngularWebAPI** [angular/angular-cli#8750]
### Versions
node: v9.2.0
npm: 5.5.1
Windows 10 - 64bit

### Repro steps
Run Node.js as Administrator:
* Step 1: npm uninstall -g @angular/cli
* Step 2: npm cache clean
* Step 3: npm install -g @angular/cli

### Observed behavior
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
### Content from log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@5.5.1
3 info using node@v9.2.0
4 verbose npm-session d79a3fb311e18ecc
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @angular/cli@latest request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
8 verbose type system
9 verbose stack FetchError: request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
9 verbose stack
9 verbose stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
9 verbose stack     at ClientRequest.emit (events.js:159:13)
9 verbose stack     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:106:9)
9 verbose stack     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:126:5)
9 verbose stack     at <anonymous>
10 verbose cwd C:\Windows\System32
11 verbose Windows_NT 10.0.14393
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
13 verbose node v9.2.0
14 verbose npm  v5.5.1
15 error code EPROTO
16 error errno EPROTO
17 error request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
18 verbose exit [ 1, true ]

**Comment by deebloo** [comment]
@AngularWebAPI are you running this in a virtual machine by chance?

**Comment by AngularWebAPI** [comment]
No. I run on my laptop.

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 5, 2017 at 8:56 PM, Danny Blue<notifications@github.com> wrote:   
@AngularWebAPI are you running this in a virtual machine by chance?

**Comment by clydin** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
