### ISSUE TITLE
How to add node_modules to a git repository downloaded?

### ISSUE THREAD

**Issue by kikidesignnet** [angular/angular-cli#8751]
I have several questions. 

The most important one is what's in the title: How to add node_modules to a git repository downloaded? I know that node_modules has a lot of files and therefore cannot be held in a git repository. Please list out step by step what I need to do on my mac laptop.

Also, it seems like I was able to get node_modules when I create a new project like this 
`sudo ng new geckos`.
However, it comes with its own problems. I cannot create a new project in a directory i like. For example, I wanted to create a project in **Documents/GitHub/geckos-four**, but it didn't work. Also I got this warning:

> _Project name "Documents/GitHub/geckos-four" is not valid. New project names must start with a letter, and must contain only alphanumeric characters or dashes. When adding a dash the segment after the dash must also start with a letter._

I concluded that it's due to the `/` slash that I wasn't able to create a new folder. So what should I do to create a new project in right folder I wanted it to be in?

Lastly, when I do create a new project with all the node_modules installed, how do I blend or add the repository that I downloaded to this new project? Is it even possible?

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
