### ISSUE TITLE
Can't install angular/cli using npm

### ISSUE THREAD

**Issue by Angular5WebAPI** [angular/angular-cli#8757]
### Versions
```
C:\Windows\System32>ng --version
'ng' is not recognized as an internal or external command,
operable program or batch file.
C:\Windows\System32>node -v
v9.2.0

C:\Windows\System32>npm -v
5.5.1

OS: Windows 10-64bit 
```

### Repro steps

About a month ago, I installed nodejs/npm and angular/cli latest version on my laptop. Everything worked perfectly. Yesterday (12/05/2017), I tried to install latest version of nodejs/npm and since then I can't install angular/cli any more:
Run Node.js as Administrator:
•Step 1: npm uninstall -g @angular/cli
•Step 2: npm cache clean
•Step 3: npm install -g @angular/cli -verbose

### Observed behavior
```
C:\Windows\System32>npm install -g @angular/cli -verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   '@angular/cli',
npm verb cli   '-verbose' ]
npm info using npm@5.5.1
npm info using node@v9.2.0
npm verb npm-session cd651e2cc6d361f9
npm verb type system
npm verb stack FetchError: request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
npm verb stack
npm verb stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm verb stack     at ClientRequest.emit (events.js:159:13)
npm verb stack     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:106:9)
npm verb stack     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:126:5)
npm verb stack     at <anonymous>
npm verb cwd C:\Windows\System32
npm verb Windows_NT 10.0.14393
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli" "-verbose"
npm verb node v9.2.0
npm verb npm  v5.5.1
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
npm ERR!
npm verb exit [ 1, true ]
```

### Mention any other details that might be useful (optional)
I also have VSTS 2017 Enterprise version 15.5.0

**Comment by istiti** [comment]
Please simply downgrade node to LTS v8.9.2 not 9.2.0

**Comment by clydin** [comment]
Please use the links provided in the previous issue (https://github.com/angular/angular-cli/issues/8750) to track down this npm related problem.

**Comment by Angular5WebAPI** [comment]
I uninstalled the node v9.2.0, restarted machine, install v8.9.2 and still get the same error:
C:\Windows\System32>node -v
v8.9.1

C:\Windows\System32>npm -v
5.5.1

C:\Windows\System32>npm install -g @angular/cli
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
npm ERR!

Detail of the log below:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose npm-session 03d39c21c039af10
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @angular/cli@latest request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
8 verbose type system
9 verbose stack FetchError: request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
9 verbose stack
9 verbose stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
9 verbose stack     at emitOne (events.js:116:13)
9 verbose stack     at ClientRequest.emit (events.js:211:7)
9 verbose stack     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:106:9)
9 verbose stack     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:126:5)
9 verbose stack     at <anonymous>
10 verbose cwd C:\Windows\System32
11 verbose Windows_NT 10.0.14393
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
13 verbose node v8.9.1
14 verbose npm  v5.5.1
15 error code EPROTO
16 error errno EPROTO
17 error request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
18 verbose exit [ 1, true ]

**Comment by Angular5WebAPI** [comment]
Dell - Internal Use - Confidential

Please do not close this incident.

I uninstalled the node v9.2.0, restarted machine, install v8.9.2 and still get the same error:
C:\Windows\System32>node -v
v8.9.1
C:\Windows\System32>npm -v
5.5.1
C:\Windows\System32>npm install -g @angular/cli
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
npm ERR!
Detail of the log below:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'install',
1 verbose cli '-g',
1 verbose cli '@angular/cli' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose npm-session 03d39c21c039af10
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @angular/cli@latest request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
8 verbose type system
9 verbose stack FetchError: request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
9 verbose stack
9 verbose stack at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
9 verbose stack at emitOne (events.js:116:13)
9 verbose stack at ClientRequest.emit (events.js:211:7)
9 verbose stack at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:106:9)
9 verbose stack at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:126:5)
9 verbose stack at
10 verbose cwd C:\Windows\System32
11 verbose Windows_NT 10.0.14393
12 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "@angular/cli"
13 verbose node v8.9.1
14 verbose npm v5.5.1
15 error code EPROTO
16 error errno EPROTO
17 error request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
18 verbose exit [ 1, true ]

Thanks,

Khanh v Le
Technical Architect, Product Data DCP
Dell Technologies
Mobile 512-970-4972

**Comment by Angular5WebAPI** [comment]
Dell - Internal Use - Confidential

Please do not close this incident, because it not resolved.

I uninstalled the node v9.2.0, restarted machine, install v8.9.2 and still get the same error:
C:\Windows\System32>node -v
v8.9.1
C:\Windows\System32>npm -v
5.5.1
C:\Windows\System32>npm install -g @angular/cli
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
npm ERR!
Detail of the log below:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'install',
1 verbose cli '-g',
1 verbose cli '@angular/cli' ]
2 info using npm@5.5.1<mailto:npm@5.5.1>
3 info using node@v8.9.1<mailto:node@v8.9.1>
4 verbose npm-session 03d39c21c039af10
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @angular/cli@latest request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
8 verbose type system
9 verbose stack FetchError: request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
9 verbose stack
9 verbose stack at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
9 verbose stack at emitOne (events.js:116:13)
9 verbose stack at ClientRequest.emit (events.js:211:7)
9 verbose stack at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:106:9)
9 verbose stack at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:126:5)
9 verbose stack at
10 verbose cwd C:\Windows\System32
11 verbose Windows_NT 10.0.14393
12 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "@angular/cli"
13 verbose node v8.9.1
14 verbose npm v5.5.1
15 error code EPROTO
16 error errno EPROTO
17 error request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
18 verbose exit [ 1, true ]


Thanks,

Khanh v Le
Technical Architect, Product Data DCP
Dell Technologies
Mobile 512-970-4972

**Comment by sistasi** [comment]
i got the same error, any resolution  yet?

**Comment by Angular5WebAPI** [comment]
Do you login from your company?
