### ISSUE TITLE
index.html should be a template

### ISSUE THREAD

**Issue by alanhg** [angular/angular-cli#8759]
How to make the index.html page template, for example, I hope to build a package, create a meta field, for example, like this below.
`<meta name="releaseDate" content="2017-12-06 19:21">`

 For example, I played this excellent demo-angular-starter, it supports because he himself is by this plugin-html-webpack-plugin , so that we can use html expressions in the page, according to the definition of variables to make judgments, Output different html. In fact, the above is a very normal demand.

[demo-angular-starter](https://github.com/gdi2290/angular-starter/blob/master/config/webpack.common.js)

**Comment by itbrandonsilva** [comment]
https://github.com/angular/angular-cli/issues/1509 related.

**Comment by alanhg** [comment]
my solution https://github.com/alanhg/angular-demo/issues/32

**Comment by rafa-as** [comment]
Any progress on version 6?

**Comment by sgronblo** [comment]
Is there any good workaround for this?

**Comment by paliwalgaurav** [comment]
Any update on this ?

**Comment by mirismaili** [comment]
Isn't any news for version 7?

**Comment by rafa-as** [comment]
@filipesilva some news here? What does Angular Team think about it?

**Comment by alan-agius4** [comment]
Closing as this is not currently in the CLI roadmap to provide this option out of the box. 

This can currently be achieved by used a 3rd party builder that extends the browser builder to transformer the index.html.
