### ISSUE TITLE
when @angular/service-worker in parent folder's node_module folder error reported

### ISSUE THREAD

**Issue by metasong** [angular/angular-cli#8771]
```
Your project is configured with serviceWorker = true, but @angular/service-worker
is not installed. Run npm install --save-dev @angular/service-worker
and try again, or run ng set apps.0.serviceWorker=false in your .angular-cli.json.
```
this is because these 2 lines: (line 32 and 33 in models/webpack-configs/production.ts)
```
const nodeModules = path.resolve(projectRoot, 'node_modules');
const swModule = path.resolve(nodeModules, '@angular/service-worker');
```

currently i'm using yarn workspace and my @angular/service-worker is in a parrent folder's nodeModules.

should change the logic to find node_modules in parents folders

**Comment by Brocco** [comment]
The project root is the directory where the CLI project was created.... which is where the `node_modules` folder lives. That structure is consistent and the CLI's logic depends upon it.

**Comment by kevin-smets** [comment]
Dupe of #8300. It's effectively a problem, combined with workspaces.
