### ISSUE TITLE
npm install -g @angular/cli throws error

### ISSUE THREAD

**Issue by itzdennisthomas** [angular/angular-cli#8777]
I am trying to learn angular 4. Installed Visual Studio code in my Windows machine.
installed node and npm.
version of nod is: 8.6.0
version of npm is: 5.3.0
While trying to install angular cli I am getting the following error:

npm ERR! request to http://registry.npmjs.org/@angular%2fcli failed, reason: error:0906D06C:PEM routines:PEM_read
start line
 
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\u23027\AppData\Roaming\npm-cache\_logs\2017-12-07T08_46_14_322Z-debug.log

### Repro steps

* Step 1: Installed VS code on Windows 7 64 bit
* Step 2: Installed Nodejs using installer which also installed npm
* Step 3: In Terminal, set the proxy as npm config set https-proxy "zscaler-url:portnumber"
* Step 4: Created a project folder in windows explorer and opened the folder in VS code
* Step 5: In Terminal, initialized package using using npm init command
* Step 6: Terminal, executed command, npm config set registry http://registry.npmjs.org
* Step 7: In Terminal, executed commad npm install –save @angular/http which threw the above error

The log file looks like:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@5.3.0
3 info using node@v8.6.0
4 verbose npm-session a4e6668fa136e609
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @angular/cli@latest request to http://registry.npmjs.org/@angular%2fcli failed, reason: error:0906D06C:PEM routines:PEM_read_bio:no start line
8 verbose type system
9 verbose stack FetchError: request to http://registry.npmjs.org/@angular%2fcli failed, reason: error:0906D06C:PEM routines:PEM_read_bio:no start line
9 verbose stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
9 verbose stack     at emitOne (events.js:115:13)
9 verbose stack     at ClientRequest.emit (events.js:210:7)
9 verbose stack     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\http-proxy-agent\node_modules\agent-base\index.js:106:9)
9 verbose stack     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\http-proxy-agent\node_modules\agent-base\index.js:126:5)
9 verbose stack     at <anonymous>
10 verbose cwd c:\Users\MyUserId\Documents\Various\Learning\Angular 4\myFirstAngularApp
11 verbose Windows_NT 6.1.7601
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
13 verbose node v8.6.0
14 verbose npm  v5.3.0
15 error request to http://registry.npmjs.org/@angular%2fcli failed, reason: error:0906D06C:PEM routines:PEM_read_bio:no start line
16 verbose exit [ 1, true ]

Thank you,
Dennis

**Comment by Brocco** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
