### ISSUE TITLE
css live-reload not working

### ISSUE THREAD

**Issue by sanlyfang** [angular/angular-cli#878]
Mac OSX (El Capitan)

angular-cli: 1.0.0-beta.5
node: 6.2.0
npm: 3.8.9

ng new ng2-demo
cd ng2-demo
ng serve

go to edit generated "ng2-demo.component.css"

browser doesn't reload css changes automatically, has to refresh the page manually to see the change

but live reload works properly for html changes

**Comment by Brocco** [comment]
I verified this is occuring

**Comment by tobakk** [comment]
same problem on linux mint

**Comment by monojack** [comment]
it's the same on any OS, `css` files are not being watched for live reload

**Comment by filipesilva** [comment]
Closing as a duplicate of https://github.com/angular/angular-cli/issues/815
