### ISSUE TITLE
An asset cannot be read from a location outside the project configuration  1.6.0

### ISSUE THREAD

**Issue by eromano** [angular/angular-cli#8783]
### Versions
```
1.6.0
```

### Repro steps

* Create a project
* Configure the .angular-cli.json to Read a file from a parent folder

### Observed behavior

Load file from an external folder now fails because of this check : 

An asset cannot be read from a location outside the project

Introduced by the PR:

https://github.com/angular/angular-cli/commit/64c60313d7c972de870cf5af7c52efbe712e8856#diff-9eb0a75e499bdadd44d6dc62218812b8

could be possible introduce a parameter configuration as allowOutsideOutDir but for reading? something like : 

```
 "allowOutsideReadDir": true 
```
It could be false by default and be enabled by the user only when he knows the security risk behind this kind of decision.

Side note the warning message could be improved indicating the assets failing

### Mention any other details that might be useful (optional)
If the idea above are ok for the project I could create a PR

**Comment by tleveque23** [comment]
Was working on 1.6.4, but since the new 1.6.5 it is failing again!

**Comment by trendzetter** [comment]
Not sure if this is related but it is a somewhat similar https://github.com/angular/angular-cli/issues/8613#issuecomment-360139629

**Comment by dotansimha** [comment]
Same here. tried 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8 :(

**Comment by Facius** [comment]
Same here on 1.70, worked with 1.50

      "assets": [
        {
          "glob": "**/*",
          "input": "./../../fonts/",
          "output": "./assets",
          "allowOutsideOutDir": true
        }
      ]

**Comment by lazysergey** [comment]
any workarounds for this?

**Comment by alan-agius4** [comment]
Closing as this is working as intended. 

Files cannot be read outside of the workspace root directory as there is also a potential security concern. Especially now that deploying the application is possible via a `ng deploy`.
