### ISSUE TITLE
'Please add a @NgModule annotation' with custom package and JIT mode only

### ISSUE THREAD

**Issue by darkbasic** [angular/angular-cli#8786]
### Versions
```
$ ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.0-rc.2
Node: 9.2.0
OS: linux x64
Angular: 5.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc.3
@angular/cli: 1.6.0-rc.2
@angular/material: 5.0.0-rc.3
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.39
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0-rc.2
@schematics/angular: 0.1.9
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

* `npm install ngx-selectable-list`
* Add `SelectableListModule` to `app.module.ts` imports.
* `ng serve` and point your browser to `http://localhost:4200`

### Observed behavior
```
Uncaught Error: Unexpected value 'SelectableListModule' imported by the module 'ChatsListerModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.js:466)
    at eval (compiler.js:15089)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15072)
    at CompileMetadataResolver.getNgModuleSummary (compiler.js:14999)
    at eval (compiler.js:15087)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15072)
    at JitCompiler._loadModules (compiler.js:33542)
    at JitCompiler._compileModuleAndComponents (compiler.js:33503)
```

### Desired behavior
Shouldn't throw an error.

### Mention any other details that might be useful (optional)

Works perfectly in AOT (`ng serve --aot`).
I created the directive package following this guide: https://medium.com/@cyrilletuzi/how-to-build-and-publish-an-angular-module-7ad19c0b4464
This is the directive's github repo: https://github.com/darkbasic/ngx-selectable-list

I would say that I probably did something wrong when I packaged the directive, but since it throws only in JIT mode I'm not 100% sure. I would be glad if someone could have a look and point me to the culprit.

P.S.
Since I still have to write the documentation, that's what the directive does: https://stackoverflow.com/questions/41143931/angular-2-master-slave-directives-communication-inter-directive-communication/47559654#47559654

**Comment by darkbasic** [comment]
I switched to a seed to package my directive and I don't get this problem anymore, so I'm closing.

**Comment by MasDevProject** [comment]
Hi,
Same problem here using **ng-packagr**.
I followed this guide: [https://medium.com/@ngl817/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e](https://medium.com/@ngl817/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e)

Can you explain better the resolution steps?
