### ISSUE TITLE
Angular Base Project doesn't work. Module build failed: main.ts is not part of the compilation.

### ISSUE THREAD

**Issue by rkkoszewski** [angular/angular-cli#8788]
### Versions
Angular CLI: 1.6.0
Node: 8.8.1
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@ angular/cli: 1.6.0
@ angular-devkit/build-optimizer: 0.0.35
@ angular-devkit/core: 0.0.22
@ angular-devkit/schematics: 0.0.41
@ ngtools/json-schema: 1.1.0
@ ngtools/webpack: 1.9.0
@ schematics/angular: 0.1.10
@ schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0

### Repro steps
1. Install Angular if not done previously with: npm install -g @angular/cli
2. Create a new app: ng new my-app
3. Go to the app folder and launch: ng serve --open
4. When the browser opens and tries to access the page, it will show a "ERR_CONNECTION_CLOSED" message, and an error will be shown in the console where the "ng serve" command was launched.

### Observed behavior
Cannot launch a freshly created Angular Project (Unmodified). When launched with "ng serve --open" this error is shown. (The same error is shown when "ng build" is used)

```
 ng serve --open
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2017-12-07T13:11:24.434Z
Hash: f5ec8ec9adb18d697f1f
Time: 3634ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 3.51 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 1.22 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 9.07 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 854 kB [initial] [rendered]

ERROR in D:/Users/bor/Desktop/Project/my-app/src/main.ts
Module build failed: Error: D:\Users\bor\Desktop\Project\my-app\src\main.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (D:\Users\bor\Desktop\Project\my-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:643:23)
    at plugin.done.then (D:\Users\bor\Desktop\Project\my-app\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
ERROR in D:/Users/bor/Desktop/Project/my-app/src/polyfills.ts
Module build failed: Error: D:\Users\bor\Desktop\Project\my-app\src\polyfills.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (D:\Users\bor\Desktop\Project\my-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:643:23)
    at plugin.done.then (D:\Users\bor\Desktop\Project\my-app\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
 @ multi ./src/polyfills.ts

webpack: Failed to compile.
```

### Desired behavior
It should show the basic template demo.

**Comment by Brocco** [comment]
I was not able to reproduce with a project I just created... could you please post the contents of these files:

- [root]/tsconfig.json
- [root]/src/tsconfig.app.json

**Comment by db6edr** [comment]
Reproduced on Windows 10, using both Git Bash from git version 2.14.1.windows.1 and Windows Command prompt. I did not check PowerShell.
Node versions in the background were both 8.40 x64, 8.9.3 x64 LTS, 9.2.1 x64. TypeScript is always at 2.5.3.

Tested on Arch Linux with NodeJS 9.2.1 x64 and TypeScript 2.5.3 succeeded on the other hand.

This seems to be an OS-dependent issue to me.

tsconfig.json:
````
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
````
src/tsconfig.app.json
````
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
````

**Comment by rkkoszewski** [comment]
On my side completely uninstalling nodejs and reinstalling the latest version of nodejs solved the issue for me. I never removed nom, and it took my old nom version an it's dependencies. I still don't know what that error means, but it is gone for me for now and everything compiles properly now. Not sure if I should close the issue now or not. Seems to be after all some nodejs conflict or something like that.

**Comment by rkkoszewski** [comment]
Npm* instead of nom.

**Comment by db6edr** [comment]
At least on Windows, uninstalling NodeJS and then re-installing it also uninstalls / installs npm, as they are bundled into a single installer.

I've done my tests using update installations; this did not solve the issue for me. Also, running a full uninstallation / installation cycle of Angular CLI at global level did not change anything.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
