### ISSUE TITLE
Compiled error when mklink  (cmd in windows ) a  module dir

### ISSUE THREAD

**Issue by Alsmile** [angular/angular-cli#8796]
angular 5.1.0
angular-cli 1.6.0

**work dir:**   
```  
src
|
-- app
    |
    --(symbolic link) module dir (make by mklink in windows)
    |
    -- others...
``` 

ERROR in xxx/module dir/src/lib/src/index.ts
Module build failed: Error: xxx\module dir\src\lib\src\index.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (xxx\node_modules\_@ngtools_webpack@1.9.0@@ngtools\webpack\src\angular_compiler_plugin.js:643:23)
    at plugin.done.then (xxx\node_modules\_@ngtools_webpack@1.9.0@@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
 @ ./src/app/app.component.ts 48:0-51
 @ ./src/app/app.module.ts
 @ ./src/main.ts

The " xxx\module dir\src\lib\src\index.ts " is target absolute path (not the  src/app/module dir ) .

**Comment by alan-agius4** [comment]
Closing as no further information was provided by the author of the issue.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
