### ISSUE TITLE
Cannot create a new project using the cli.  typings install exit status 1

### ISSUE THREAD

**Issue by JOEL0903** [angular/angular-cli#880]
1. OS?  Windows 10
2. Node Versions. 5.9.1.

3. Installing packages for tooling via npm returns the following:

typings ERR! message EPERM: operation not permitted, rename 'C:\Users\Joel\.config\configstore\typings.json.3625512754' -> 'C:\Users\Joel\.config\configstore\typings.json'

typings ERR! cwd C:\angular2\angular2-quickstart
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\angular2\\angular2-quickstart\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v5.9.1
typings ERR! typings -v 0.8.1
typings ERR! code EPERM

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
angular2-quickstart@0.0.0 postinstall: `typings install`
Exit status 1
Error: angular2-quickstart@0.0.0 postinstall: `typings install`
Exit status 1
    at EventEmitter.<anonymous> (C:\Users\Joel\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\lib\utils\lifecycle.js:217:16)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at ChildProcess.<anonymous> (C:\Users\Joel\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\lib\utils\spawn.js:24:14)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

The typings.json file is created if it doesn't already exist in the .config/configstore folder (no file with a numeric ending is found in the directory, so it appears as if the rename IS working).  It contains one entry:
{
	"clientId": "e3c71852-66f3-43fd-b04e-ce3a6d9a6079"
}

**Comment by empirecoder** [comment]
Same for me. postinstall fails.
OS X: 10.11.4
Node: v5.7.1
[npm-debug.txt](https://github.com/angular/angular-cli/files/276642/npm-debug.txt)

**Comment by JOEL0903** [comment]
This worked for me as well.

**Comment by balasivagnanam** [comment]
occurs after node upgrade as well :(

![image](https://cloud.githubusercontent.com/assets/4233785/15799747/f91854a8-2a98-11e6-88d5-ca6c0e36d9c0.png)

**Comment by MartinRyan** [comment]
I had the same error until I used the sudo command in the terminal. On windows run the node console as an administrator...

**Comment by MartinRyan** [comment]
sudo npm run postinstall
https://github.com/angular/angular-cli/issues/633

**Comment by Diegow3b** [comment]
@MartinRyan i have tried to run at node console but u just cant run npm install at node itself, just show me a message telling u should use it on project dir

**Comment by xinmeng1** [comment]
sudo ng serve

**Comment by kylecordes** [comment]
I recommend against running any of the above commands with sudo. Something is wrong with the set up in this case, the solution is definitely not sudo. :-)
