### ISSUE TITLE
ng new still gives error: path

### ISSUE THREAD

**Issue by akshaybabloo** [angular/angular-cli#8800]
This was already submitted as a bug report at #8765. I still get the same error as:

``` 
Error: Path "/app/app.module.ts" does not exist.
Path "/app/app.module.ts" does not exist.
```

Ng details are:

```
Angular CLI: 1.6.0
Node: 8.9.2
OS: win32 x64
```

**Comment by Brocco** [comment]
That issue was resolved, please uninstall and reinstall the CLI globally and create a new project.

**Comment by akshaybabloo** [comment]
It did it fix it.
