### ISSUE TITLE
Did node-sass version changed in 1.6.0?

### ISSUE THREAD

**Issue by dragonflypl** [angular/angular-cli#8802]
Hi,

after upgrading to 1.6.0 , `ng new` tries to fetch `node-sass@4.7.2` (latest), whereas `1.5.x` was downloading `4.5.3`. As i'm behind corporate proxy it is causing issues. 

How can I force it to use `4.5.3`? 

Also , how `node-sass` version is resolved? 

In `https://github.com/angular/angular-cli/blob/v1.6.0/package-lock.json` I see that it is locked to `4.5.3`.

Thanks,
Pawel

**Comment by Brocco** [comment]
`node-sass` is an optional dependency which you can see [here](https://github.com/angular/angular-cli/blob/c9389361c9fb7bbc0e3385f95e0c0a47b448a532/packages/%40angular/cli/package.json#L89) with the version set to `^4.3.0` with the caret (`^`) meaning it will attempt to download the latest minor version for major version 4.
In your project you should be able to run `npm i node-sass@4.5.3` to install that specific version in your project.
