### ISSUE TITLE
investigate parcel

### ISSUE THREAD

**Issue by tycho01** [angular/angular-cli#8804]
Recently it seems a new bundler has popped up named `parcel` ([github](https://github.com/parcel-bundler/parcel), [site](https://parceljs.org/)). I haven't looked into it in detail, but it appears to be claiming some advantages over webpack. If that's the case, it might be of interest here as well.

**Comment by hansl** [comment]
Hello @tycho01,

Thanks for the report. We're not looking at changing our build system from webpack right now. We keep an eye on new bundlers and if there's a point where it would make sense we'll consider it.

I'm going to close this as it is not something I can see us considering for the foreseeable future.

**Comment by alexandermikuta** [comment]
If with webpack 4 things do not get better I hope you reconsider your decision not to investigate in parcel.
Currently our build-times in a larger project are several minutes and sometimes we get out-of-memory issues. Also we are quite happy with angular-cli in all other aspects we currently consider switching away from cli because of this build-issues.

**Comment by dankellett** [comment]
92%

**Comment by webmutation** [comment]
Ditto... webpack is slow. Our app takes 6 mins to build !!!

**Comment by zuohuadong** [comment]
Ditto...

**Comment by tatsujb** [comment]
common, two years going on three and still no official support?

@dankellett what was this 92% about?

**Comment by leak** [comment]
@tatsujb Presumably this is a reference to the percentage that webpack is stuck at for quite a while before actually finishing.

**Comment by tatsujb** [comment]
@leak nah I don't think so. webpack usually sticks at 11% or 59% you barely ever get to see the final percentages.

**Comment by SubJunk** [comment]
Yeah building in prod mode stays at 92% for ages. Would love to see the speeds improve with something like Parcel!
