### ISSUE TITLE
'Please add a @NgModule annotation' using ng-packagr

### ISSUE THREAD

**Issue by MasDevProject** [angular/angular-cli#8805]
### Versions
```
Angular CLI: 1.5.0
Node: 8.5.0
OS: darwin x64
```

### Repro steps
I followed [this tutorial](https://medium.com/@ngl817/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e) in order to pack [my Module](https://www.npmjs.com/package/ng2-bs-dialogs-creator) using **ng-packagr**.

I use my package in a couple of projects and using `npm serve` it works like a charm.
But when I try to compile using `-prod` I get an exception at compile time.

### Observed behavior
This is the exception I get:
```
ERROR in Error: Unexpected value 'DialogsModule in /WebApp/node_modules/ng2-bs-dialogs-creator/src/modal/dialogs.module.d.ts' imported by the module 'AppModule in /WebApp/src/app/app.module.ts'. Please add a @NgModule annotation.
```

### Desired behavior
Shouldn't throw an error.

**Comment by filipesilva** [comment]
I'm sorry, but we don't really own that tutorial or `ng-packagr`. I don't know what's going wrong with your library. I know there's a lot of libraries created with `ng-packagr` so I think it's probably a configuration thing.

The best place to check is in the `ng-packagr` issue tracker though: https://github.com/dherges/ng-packagr. You should open an issue there.
