### ISSUE TITLE
3rd-party-libs with css

### ISSUE THREAD

**Issue by krasevych** [angular/angular-cli#881]
I read information here: https://github.com/angular/angular-cli/wiki/3rd-party-libs
there is info about how to added *.js, but how can I added css files?

**Comment by prashanthcvvp** [comment]
Try this 

@angular2-material/**/*.+(js|css) 

this worked for me with material design.

**Comment by krasevych** [comment]
thank you!

**Comment by filipesilva** [comment]
@prashanthcvvp has the right answer, you should just need to add it to `vendorNpmFiles`.
