### ISSUE TITLE
Integrate angular-cli with parcel js builder

### ISSUE THREAD

**Issue by gridcellcoder** [angular/angular-cli#8811]
If [parceljs](https://parceljs.org) can be proven to be faster than webpack for bundling code with hot module support, it may be beneficial to the community to have the option to use parcel for building and deploying cli applications. This would help faster development and deploy times for cli applications.

The use case would be to have capability to invoke `ng build --builder=parcel` or  `ng serve --builder=parcel`for example.

**Comment by hansl** [comment]
Duplicate of #8804
