### ISSUE TITLE
Proxy: Local virtual host names are all resolved to localhost

### ISSUE THREAD

**Issue by PMacho** [angular/angular-cli#8816]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```
Angular CLI: 1.5.4
Node: 6.12.0
OS: darwin x64
Angular: 
...

### Repro steps

I created a local virtual host with xampp at http://mysite.local:8080.
I have a proxy.conf.json:
{
"/api": {
"target": "http://mysite.local:8080",
"secure": false,
"logLevel": "debug",
"pathRewrite": {
"^/api": ""
}
}
}

and changed the changed the start line in package.json to:
"start": "ng serve --proxy-config proxy.conf.json",

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

On npm start i get messages like:
[HPM] Rewriting path from "/api/src/main/package/Entries/testservice/testentry.php" to "/src/main/package/Entries/testservice/testentry.php"
[HPM] GET /api/src/main/package/Entries/testservice/testentry.php ~> http://mysite.local:8080

However, instead of mysite.local:8080 Angular attempts to fetch data from localhost:8080.

### Desired behavior

fetch data from mystic.local:8080

### Mention any other details that might be useful (optional)

I think the problem is related to webpack: https://webpack.github.io/docs/webpack-dev-server.html#proxying-local-virtual-hosts
I just don't know where to make the according changes in Angular.

**Comment by clydin** [comment]
Did you try the suggested proxy configuration provided in the webpack documentation link?

**Comment by PMacho** [comment]
No, since I don’t know where exactly I need to paste the code.

**Comment by clydin** [comment]
The proxy object correlates directly to the proxy conf JSON/JS file.  The other settings are incidental to the proxy setup.  Can you give it a try and report back?

**Comment by yesprasoon** [comment]
Did you manage to sort this out? I am using following code in .json file:

```
{
    "/products/*":{
        "target": "http://xyzproducts.localhost.com",
        "secure":false,
        "logLevel":"debug",
        "pathRewrite": {
            "^/products": ""
          },
          "changeOrigin": true
    }
}
```

However, http://localhost:4200/products - always gets changed to http://xyzproducts.localhost.com.

Can somebody please suggest the soultion?

**Comment by clydin** [comment]
Did the configuration change fix the problem or is the issue still presenting itself?
