### ISSUE TITLE
npm install -g @angular/cli not working on windows 7 machine

### ISSUE THREAD

**Issue by salilsingh2008** [angular/angular-cli#8817]
error Unexpected end of JSON input while parsing near '...:"1.0.x","mkdirp":"0.'

Node  - version 8.9.3
npm  version 5.5.1

Below is the content of the log file - 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose npm-session 528904c77512d600
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/@angular%2fcli 5564ms
8 silly pacote tag manifest for @angular/cli@latest fetched in 5707ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule @angular/cli@1.6.0 checking installable status
14 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fbuild-optimizer 839ms
15 silly pacote range manifest for @angular-devkit/build-optimizer@~0.0.35 fetched in 879ms
16 silly resolveWithNewModule @angular-devkit/build-optimizer@0.0.35 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/autoprefixer 1116ms (from cache)
18 silly pacote range manifest for autoprefixer@^6.5.3 fetched in 1124ms
19 silly resolveWithNewModule autoprefixer@6.7.7 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/copy-webpack-plugin 1242ms (from cache)
21 silly pacote range manifest for copy-webpack-plugin@^4.1.1 fetched in 1284ms
22 silly resolveWithNewModule copy-webpack-plugin@4.2.3 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/chalk 1292ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/circular-dependency-plugin 1294ms (from cache)
25 silly pacote range manifest for chalk@~2.2.0 fetched in 1328ms
26 silly resolveWithNewModule chalk@2.2.2 checking installable status
27 silly pacote range manifest for circular-dependency-plugin@^4.2.1 fetched in 1374ms
28 silly resolveWithNewModule circular-dependency-plugin@4.3.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/@angular-devkit%2fschematics 1486ms (from cache)
30 http fetch GET 304 https://registry.npmjs.org/core-object 617ms (from cache)
31 silly pacote range manifest for core-object@^3.1.0 fetched in 669ms
32 silly resolveWithNewModule core-object@3.1.5 checking installable status
33 http fetch GET 304 https://registry.npmjs.org/common-tags 1610ms (from cache)
34 http fetch GET 304 https://registry.npmjs.org/css-loader 540ms (from cache)
35 silly pacote range manifest for @angular-devkit/schematics@~0.0.40 fetched in 1728ms
36 silly resolveWithNewModule @angular-devkit/schematics@0.0.41 checking installable status
37 silly pacote range manifest for css-loader@^0.28.1 fetched in 610ms
38 silly resolveWithNewModule css-loader@0.28.7 checking installable status
39 silly pacote range manifest for common-tags@^1.3.1 fetched in 1760ms
40 silly resolveWithNewModule common-tags@1.5.1 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/cssnano 634ms (from cache)
42 http fetch GET 304 https://registry.npmjs.org/ember-cli-string-utils 550ms (from cache)
43 http fetch GET 304 https://registry.npmjs.org/denodeify 599ms (from cache)
44 silly pacote range manifest for ember-cli-string-utils@^1.0.0 fetched in 671ms
45 silly resolveWithNewModule ember-cli-string-utils@1.1.0 checking installable status
46 silly pacote range manifest for cssnano@^3.10.0 fetched in 831ms
47 silly resolveWithNewModule cssnano@3.10.0 checking installable status
48 silly pacote range manifest for denodeify@^1.2.1 fetched in 817ms
49 silly resolveWithNewModule denodeify@1.2.1 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/@ngtools%2fjson-schema 2155ms (from cache)
51 http fetch GET 304 https://registry.npmjs.org/@ngtools%2fwebpack 2276ms (from cache)
52 http fetch GET 304 https://registry.npmjs.org/@schematics%2fangular 2322ms (from cache)
53 silly pacote version manifest for @ngtools/webpack@1.9.0 fetched in 2511ms
54 silly resolveWithNewModule @ngtools/webpack@1.9.0 checking installable status
55 silly pacote version manifest for @ngtools/json-schema@1.1.0 fetched in 2523ms
56 silly resolveWithNewModule @ngtools/json-schema@1.1.0 checking installable status
57 silly pacote range manifest for @schematics/angular@~0.1.10 fetched in 2660ms
58 silly resolveWithNewModule @schematics/angular@0.1.10 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/file-loader 1222ms (from cache)
60 http fetch GET 304 https://registry.npmjs.org/exports-loader 1422ms (from cache)
61 http fetch GET 304 https://registry.npmjs.org/glob 991ms (from cache)
62 http fetch GET 304 https://registry.npmjs.org/html-webpack-plugin 924ms (from cache)
63 silly pacote range manifest for exports-loader@^0.6.3 fetched in 1553ms
64 silly resolveWithNewModule exports-loader@0.6.4 checking installable status
65 silly pacote range manifest for html-webpack-plugin@^2.29.0 fetched in 995ms
66 silly resolveWithNewModule html-webpack-plugin@2.30.1 checking installable status
67 http fetch GET 304 https://registry.npmjs.org/karma-source-map-support 992ms (from cache)
68 http fetch GET 304 https://registry.npmjs.org/extract-text-webpack-plugin 1421ms (from cache)
69 silly pacote range manifest for glob@^7.0.3 fetched in 1095ms
70 silly resolveWithNewModule glob@7.1.2 checking installable status
71 silly pacote range manifest for karma-source-map-support@^1.2.0 fetched in 1133ms
72 silly resolveWithNewModule karma-source-map-support@1.2.0 checking installable status
73 silly pacote range manifest for file-loader@^1.1.5 fetched in 1551ms
74 silly resolveWithNewModule file-loader@1.1.5 checking installable status
75 http fetch GET 304 https://registry.npmjs.org/fs-extra 1531ms (from cache)
76 http fetch GET 304 https://registry.npmjs.org/less 866ms (from cache)
77 silly pacote range manifest for fs-extra@^4.0.0 fetched in 1719ms
78 silly resolveWithNewModule fs-extra@4.0.3 checking installable status
79 silly pacote range manifest for less@^2.7.2 fetched in 980ms
80 silly resolveWithNewModule less@2.7.3 checking installable status
81 http fetch GET 304 https://registry.npmjs.org/license-webpack-plugin 864ms (from cache)
82 http fetch GET 304 https://registry.npmjs.org/less-loader 1006ms (from cache)
83 silly pacote range manifest for extract-text-webpack-plugin@^3.0.2 fetched in 1844ms
84 silly resolveWithNewModule extract-text-webpack-plugin@3.0.2 checking installable status
85 silly pacote range manifest for less-loader@^4.0.5 fetched in 1061ms
86 silly resolveWithNewModule less-loader@4.0.5 checking installable status
87 silly pacote range manifest for license-webpack-plugin@^1.0.0 fetched in 932ms
88 silly resolveWithNewModule license-webpack-plugin@1.1.1 checking installable status
89 http fetch GET 304 https://registry.npmjs.org/lodash 709ms (from cache)
90 silly pacote range manifest for lodash@^4.11.1 fetched in 719ms
91 silly resolveWithNewModule lodash@4.17.4 checking installable status
92 http fetch GET 304 https://registry.npmjs.org/memory-fs 709ms (from cache)
93 silly pacote range manifest for memory-fs@^0.4.1 fetched in 748ms
94 silly resolveWithNewModule memory-fs@0.4.1 checking installable status
95 http fetch GET 304 https://registry.npmjs.org/minimatch 722ms (from cache)
96 http fetch GET 304 https://registry.npmjs.org/nopt 594ms (from cache)
97 http fetch GET 304 https://registry.npmjs.org/opn 402ms (from cache)
98 silly pacote range manifest for minimatch@^3.0.4 fetched in 768ms
99 silly resolveWithNewModule minimatch@3.0.4 checking installable status
100 silly pacote range manifest for opn@~5.1.0 fetched in 433ms
101 silly resolveWithNewModule opn@5.1.0 checking installable status
102 silly pacote range manifest for nopt@^4.0.1 fetched in 639ms
103 silly resolveWithNewModule nopt@4.0.1 checking installable status
104 http fetch GET 304 https://registry.npmjs.org/node-modules-path 764ms (from cache)
105 silly pacote range manifest for node-modules-path@^1.0.0 fetched in 818ms
106 silly resolveWithNewModule node-modules-path@1.0.1 checking installable status
107 http fetch GET 304 https://registry.npmjs.org/postcss-custom-properties 646ms (from cache)
108 http fetch GET 304 https://registry.npmjs.org/postcss-url 636ms (from cache)
109 silly pacote range manifest for postcss-custom-properties@^6.1.0 fetched in 779ms
110 silly resolveWithNewModule postcss-custom-properties@6.2.0 checking installable status
111 http fetch GET 304 https://registry.npmjs.org/raw-loader 545ms (from cache)
112 silly pacote range manifest for postcss-url@^7.1.2 fetched in 777ms
113 silly resolveWithNewModule postcss-url@7.3.0 checking installable status
114 silly pacote range manifest for raw-loader@^0.5.1 fetched in 627ms
115 silly resolveWithNewModule raw-loader@0.5.1 checking installable status
116 http fetch GET 304 https://registry.npmjs.org/postcss-loader 867ms (from cache)
117 http fetch GET 304 https://registry.npmjs.org/resolve 622ms (from cache)
118 http fetch GET 304 https://registry.npmjs.org/portfinder 998ms (from cache)
119 http fetch GET 304 https://registry.npmjs.org/semver 566ms (from cache)
120 silly pacote range manifest for postcss-loader@^2.0.8 fetched in 916ms
121 silly resolveWithNewModule postcss-loader@2.0.9 checking installable status
122 silly pacote range manifest for resolve@^1.1.7 fetched in 675ms
123 silly resolveWithNewModule resolve@1.5.0 checking installable status
124 silly pacote range manifest for semver@^5.1.0 fetched in 613ms
125 silly resolveWithNewModule semver@5.4.1 checking installable status
126 http fetch GET 304 https://registry.npmjs.org/rxjs 628ms (from cache)
127 http fetch GET 304 https://registry.npmjs.org/sass-loader 630ms (from cache)
128 silly pacote range manifest for rxjs@^5.5.2 fetched in 717ms
129 silly resolveWithNewModule rxjs@5.5.5 checking installable status
130 silly pacote range manifest for sass-loader@^6.0.3 fetched in 762ms
131 silly resolveWithNewModule sass-loader@6.0.6 checking installable status
132 silly pacote range manifest for portfinder@~1.0.12 fetched in 1203ms
133 silly resolveWithNewModule portfinder@1.0.13 checking installable status
134 http fetch GET 304 https://registry.npmjs.org/silent-error 639ms (from cache)
135 http fetch GET 304 https://registry.npmjs.org/source-map-loader 422ms (from cache)
136 silly pacote range manifest for silent-error@^1.0.0 fetched in 680ms
137 silly resolveWithNewModule silent-error@1.1.0 checking installable status
138 silly pacote range manifest for source-map-loader@^0.2.0 fetched in 469ms
139 silly resolveWithNewModule source-map-loader@0.2.3 checking installable status
140 http fetch GET 304 https://registry.npmjs.org/istanbul-instrumenter-loader 547ms (from cache)
141 silly pacote range manifest for istanbul-instrumenter-loader@^2.0.0 fetched in 615ms
142 silly resolveWithNewModule istanbul-instrumenter-loader@2.0.0 checking installable status
143 http fetch GET 304 https://registry.npmjs.org/source-map-support 751ms (from cache)
144 silly pacote range manifest for source-map-support@^0.4.1 fetched in 756ms
145 silly resolveWithNewModule source-map-support@0.4.18 checking installable status
146 http fetch GET 304 https://registry.npmjs.org/stylus-loader 587ms (from cache)
147 http fetch GET 304 https://registry.npmjs.org/stylus 590ms (from cache)
148 http fetch GET 304 https://registry.npmjs.org/style-loader 815ms (from cache)
149 silly pacote range manifest for stylus-loader@^3.0.1 fetched in 857ms
150 silly resolveWithNewModule stylus-loader@3.0.1 checking installable status
151 silly pacote range manifest for style-loader@^0.13.1 fetched in 902ms
152 silly resolveWithNewModule style-loader@0.13.2 checking installable status
153 silly pacote range manifest for stylus@^0.54.5 fetched in 1027ms
154 silly resolveWithNewModule stylus@0.54.5 checking installable status
155 http fetch GET 304 https://registry.npmjs.org/url-loader 917ms (from cache)
156 silly pacote range manifest for url-loader@^0.6.2 fetched in 1021ms
157 silly resolveWithNewModule url-loader@0.6.2 checking installable status
158 http fetch GET 304 https://registry.npmjs.org/webpack 1014ms (from cache)
159 silly fetchPackageMetaData error for webpack@~3.10.0 Unexpected end of JSON input while parsing near '...:"1.0.x","mkdirp":"0.'
160 http fetch GET 304 https://registry.npmjs.org/uglifyjs-webpack-plugin 1125ms (from cache)
161 http fetch GET 304 https://registry.npmjs.org/webpack-dev-middleware 940ms (from cache)
162 http fetch GET 304 https://registry.npmjs.org/webpack-concat-plugin 979ms (from cache)
163 http fetch GET 304 https://registry.npmjs.org/webpack-dev-server 789ms (from cache)
164 silly pacote range manifest for webpack-dev-middleware@~1.12.0 fetched in 1034ms
165 silly resolveWithNewModule webpack-dev-middleware@1.12.2 checking installable status
166 silly pacote range manifest for webpack-dev-server@~2.9.3 fetched in 796ms
167 silly resolveWithNewModule webpack-dev-server@2.9.7 checking installable status
168 silly pacote range manifest for webpack-concat-plugin@^1.4.2 fetched in 1075ms
169 silly resolveWithNewModule webpack-concat-plugin@1.4.2 checking installable status
170 silly pacote range manifest for uglifyjs-webpack-plugin@~1.1.2 fetched in 1283ms
171 silly resolveWithNewModule uglifyjs-webpack-plugin@1.1.2 checking installable status
172 http fetch GET 304 https://registry.npmjs.org/webpack-sources 689ms (from cache)
173 http fetch GET 304 https://registry.npmjs.org/zone.js 604ms (from cache)
174 silly pacote range manifest for webpack-sources@^1.0.0 fetched in 844ms
175 silly resolveWithNewModule webpack-sources@1.1.0 checking installable status
176 http fetch GET 304 https://registry.npmjs.org/webpack-subresource-integrity 875ms (from cache)
177 silly pacote range manifest for webpack-subresource-integrity@^1.0.1 fetched in 883ms
178 silly resolveWithNewModule webpack-subresource-integrity@1.0.3 checking installable status
179 silly pacote range manifest for zone.js@^0.8.14 fetched in 719ms
180 silly resolveWithNewModule zone.js@0.8.18 checking installable status
181 http fetch GET 304 https://registry.npmjs.org/node-sass 676ms (from cache)
182 silly pacote range manifest for node-sass@^4.3.0 fetched in 715ms
183 silly resolveWithNewModule node-sass@4.7.2 checking installable status
184 http fetch GET 304 https://registry.npmjs.org/webpack-merge 1430ms (from cache)
185 silly pacote range manifest for webpack-merge@^4.1.0 fetched in 1488ms
186 silly resolveWithNewModule webpack-merge@4.1.1 checking installable status
187 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...:"1.0.x","mkdirp":"0.'
187 verbose stack     at JSON.parse (<anonymous>)
187 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-better-errors\index.js:7:17)
187 verbose stack     at consumeBody.call.then.buffer (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
187 verbose stack     at <anonymous>
187 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
188 verbose cwd C:\Windows\system32
189 verbose Windows_NT 6.1.7601
190 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
191 verbose node v8.9.3
192 verbose npm  v5.5.1
193 error Unexpected end of JSON input while parsing near '...:"1.0.x","mkdirp":"0.'
194 verbose exit [ 1, true ]

Can you please help me resolve this issue?

Thanks,
Salil

**Comment by Brocco** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
