### ISSUE TITLE
CLI 1.6.0 creating angular 5.0 version instead of 5.1.0

### ISSUE THREAD

**Issue by ultrasonicsoft** [angular/angular-cli#8822]
### Versions
1.6.0

### Repro steps
* Step 1
`ng new ng-dmeo`

### Observed behavior
New angular project got created with version 5.0 instead of 5.1.0

### Desired behavior
Expected angular version of 5.1.0

### Mention any other details that might be useful (optional)

"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  }

**Comment by neaplus** [comment]
+1

**Comment by baruchvlz** [comment]
If you do `ng -v` inside your application, which Angular version does it print?

**Comment by neaplus** [comment]
Angular CLI: 1.6.0
Node: 8.7.0
OS: darwin x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0

**Comment by ultrasonicsoft** [comment]
Angular CLI: 1.6.0
Node: 8.1.3
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0

**Comment by Toxicable** [comment]
Looks like 5.1 to me

**Comment by Doehl** [comment]
When in the version have a ^ prefix. Will NPM keep the dependent updated with both minor and patch releases. 

So everything is as expected.

**Comment by ultrasonicsoft** [comment]
I read about caret prefix meaning in NPM and verified with older version of Angular. It makes sense to me now. 
Learnt something new.
Thanks!
