### ISSUE TITLE
Uncaught ReferenceError: environment is not defined

### ISSUE THREAD

**Issue by IMikit** [angular/angular-cli#8826]
### Versions
```
@angular/cli: 1.4.9
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4
```

### Repro steps

* Step 1
```ng new myapp```
```cd myapp```
```ng generate component mycomponent```
* Step 2
Code in mycomponent.component.ts : 
```typescript
import { Component, OnInit } from '@angular/core';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-mycomponent',
  templateUrl: environment.production ? './mycomponent.production.component.html' : './mycomponent.dev.component.html',
  styleUrls: ['./mycomponent.component.css']
})
export class MycomponentComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
```
* Step 3
Create two templates to have : 
src
|-app
| |-mycomponent
| | |-mycomponent.component.css
| | |-mycomponent.dev.component.html
| | |-mycomponent.production.component.html
| | |-mycomponent.component.spec.ts
| | |-mycomponent.component.ts

### Observed behavior
```javascript
Uncaught ReferenceError: environment is not defined
    at Object.../../../../../src/app/mycomponent/mycomponent.component.ts (mycomponent.component.ts:6)
```

### Desired behavior
I want to switch the template if i'm in prod or in developpement.
I can use it in a project without angular-cli. Why can't I with ?

**Comment by hansl** [comment]
> I want to switch the template if i'm in prod or in developpement.

Angular (not the CLI) prevents you from doing that. That is invalid Angular code. You can create a feature request or file an issue on Angular here: https://github.com/angular/angular/issues/new

**Comment by IMikit** [comment]
I'm thinking you're wrong... I can do that with a homemade angular app (not with cli), and it's working perfectly.
The error come from the main.js generate by cli, because the declaration of environment is after the declaration of components, so environment is not defined when he need it.
There is any way to declare environment before components ? Or to declare my environment variable in a module that I can reuse anywhere, or I don't know...
