### ISSUE TITLE
ng e2e not compiling symbolic linked sources properly

### ISSUE THREAD

**Issue by greenGoby** [angular/angular-cli#8839]
### Versions
```
Angular CLI: 1.5.5
Node: 8.4.0
OS: win32 x64
Angular: 5.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

@angular/cdk: 5.0.0
@angular/cli: 1.5.5
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.0
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.39
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.8
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps
Setup linked directory linked-src parallel to src directory and in it link common-angular directory to a directory in a higher up parent tree.  Put source in there.  If it requires things in node_modules they will not be found.  

`linked-src`
`----common-angular (linked from higher up in the parent tree)`
`--------some-src-file.ts (that uses decimal.js)`
`node-modules`
`----decimal.js`

### Observed behavior
```
DevTools listening on ws://127.0.0.1:12958/devtools/browser/cb99e800-eaf1-4be0-adc5-83ca906823eb
[16:42:32] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
..\..\common-angular\constants.ts (1,21): Cannot find module 'decimal.js'. (2307)
```

### Desired behavior
It should find decimal.js in the node_modules folder, but because it is traversing to the actual file, node_modules is not found.  

ng build and ng serve both work fine in all modes, as they preserve the symlink.  But, when running e2e, the preserve symlinks isn't getting setup in node (that is running ts-node under the hood) so it complains.

### Mention any other details that might be useful (optional)
I am passing --preserve-symlinks to ng.  Here is my full command:
ng e2e --serve=false --specs=e2e/screenshots-retirement-home-desktop.ts --preserve-symlinks

I looked through the code, and @angular/cli/tasks/e2e is calling protractor/built/launcher

What I am not sure of, is where one would look to make sure preserve-symlinks are being used and passed along or not.  I didn't fully follow past the protractor/built/launcher part.  Not sure if that launches a new node instance or not, and then the flag needs to be passed to it?

Thanks for any help.  This is really stumping me right now.

**Comment by billwagner3** [comment]
Is this still an issue with later versions of Angular and Node?

**Comment by filipesilva** [comment]
Closing as the original author never got back.
