### ISSUE TITLE
Update Travis CI Wiki doc to avoid chrome error when running ng e2e 

### ISSUE THREAD

**Issue by adelinor** [angular/angular-cli#8840]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
    
Angular CLI: 1.5.5
Node: 9.2.0
OS: darwin x64
Angular: 5.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.5
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.8
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps

I faced the error after the following sequence:
* Generated my project with angular-cli
* Added Travis CI configuration
* E2E tests were executed successfully
* E2E tests stopped running when chromedriver upgraded from version 2.33 to 2.34 in the last few days

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
E/launcher - session not created exception: Chrome version must be >= 61.0.3163.0
```
See detailed stack trace in https://travis-ci.org/adelinor/angular-snippets/builds/315044216

### Desired behavior

Adding the following in `.travis.yml` resolved the problem:
```
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
```
This could be added to the Wiki page: https://github.com/angular/angular-cli/wiki/stories-continuous-integration

**Comment by Brocco** [comment]
For anyone looking to submit a PR for this issue, the documentation for the CLI's wiki is in the actual repository you can find it [here](https://github.com/angular/angular-cli/tree/master/docs/documentation). Update the documentation here via a pull request and the updates get published to the actual wiki.
