### ISSUE TITLE
NG Build -prod not compiling Bootstrap

### ISSUE THREAD

**Issue by lucasbordini** [angular/angular-cli#8850]
### Versions
Angular CLI: 1.5.0
Node: 8.9.3
OS: darwin x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.8.1
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

I Have a project with bootstrap 4 alpha-6 and fonts-awesome
Have this two extensions defined on my .angular-cli.json
"styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "../node_modules/font-awesome/css/font-awesome.css"
      ],

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```
When i do ng build -prod
my dist come without bootstrap and fonts awesome

### Desired behavior

The boostrap need to be compiled with my project

### Mention any other details that might be useful (optional)

If i use ng build -prod --aot=false, i receive a error 

Uncaught Error: Unexpected value 'e' imported by the module 'e'. Please add a @NgModule annotation.
    at u (main.13992d0797794439eefc.bundle.js:1)
    at main.13992d0797794439eefc.bundle.js:1
    at Array.forEach (<anonymous>)
    at e.getNgModuleMetadata (main.13992d0797794439eefc.bundle.js:1)
    at e._loadModules (main.13992d0797794439eefc.bundle.js:1)
    at e._compileModuleAndComponents (main.13992d0797794439eefc.bundle.js:1)
    at e.compileModuleAsync (main.13992d0797794439eefc.bundle.js:1)
    at e.compileModuleAsync (main.13992d0797794439eefc.bundle.js:1)
    at e.LMZF.e.bootstrapModule (main.13992d0797794439eefc.bundle.js:1)
    at Object.cDNt (main.13992d0797794439eefc.bundle.js:1)

**Comment by clydin** [comment]
The CLI has been updated significantly since version 1.5.0.  The current stable version is 8.3.5.  If this problem is still being encountered with the current version, please consider opening a new issue with updated details.
