### ISSUE TITLE
Cannot find module on production build

### ISSUE THREAD

**Issue by callawey** [angular/angular-cli#8851]
On development enviroment i have no issue at all and everything works like a charm but when i build it for production, the build process goes well and it gives no error but upon visiting the site which is build for production it gives below error

Uncaught (in promise): Error: Cannot find module './components/home/home.module.ngfactory'.

instead of putting all information here again, here is the stackoverflow link with all the informations in it:

https://stackoverflow.com/questions/47769743/cannot-find-module-components-home-home-module-ngfactory-on-production-build

**Comment by filipesilva** [comment]
I know you have listed a lot of files in the SO question, but I don't think I can repro with just those. There are files missing for the application to run. Can you setup a simple repro in github and give me the commands to run so that I can investigate here?

**Comment by callawey** [comment]
I will try to create a small repo on weekend that can regenate this issue.

**Comment by callawey** [comment]
@filipesilva here i added the project by simplified as much as i can that can give the error. In the project i edited the webpack.config files as isDevBuild = false so you dont need to publish the application, run it directly from VS and it will give you the error. 

Let me know if you need any thing else from me.

https://github.com/callawey/GithubTest

**Comment by callawey** [comment]
hey @filipesilva @Brocco do you looking on this ?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
