### ISSUE TITLE
AOT Giving Generic Error Message when Component is declared in multiple modules

### ISSUE THREAD

**Issue by deebloo** [angular/angular-cli#8860]
When serving a generated app with AOT enabled some errors are obfuscated behind a misleading error message at build time. This issue is specifically for the same declaration in multiple modules but I believe it happens for others as well but this is the one I have an example for.
 
### Versions

```
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

* clone [repo](https://github.com/deebloo/error-message-example)
* run ```npm start``` (command updated with --aot)
* see error message

### Observed behavior

non specific error message shown in terminal:

```
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './app/app.module.ngfactory' in '/Users/dannyblue/Documents/projects/error-example/src'
resolve './app/app.module.ngfactory' in '/Users/dannyblue/Documents/projects/error-example/src'
  using description file: /Users/dannyblue/Documents/projects/error-example/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/dannyblue/Documents/projects/error-example/package.json (relative path: ./src)
    using description file: /Users/dannyblue/Documents/projects/error-example/package.json (relative path: ./src/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/dannyblue/Documents/projects/error-example/src/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/dannyblue/Documents/projects/error-example/src/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/dannyblue/Documents/projects/error-example/src/app/app.module.ngfactory.js doesn't exist
      as directory
        /Users/dannyblue/Documents/projects/error-example/src/app/app.module.ngfactory doesn't exist
[/Users/dannyblue/Documents/projects/error-example/src/app/app.module.ngfactory]
[/Users/dannyblue/Documents/projects/error-example/src/app/app.module.ngfactory.ts]
[/Users/dannyblue/Documents/projects/error-example/src/app/app.module.ngfactory.js]
[/Users/dannyblue/Documents/projects/error-example/src/app/app.module.ngfactory]
 @ ./src/main.ts 3:0-66
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

### Desired behavior

Terminal should display the correct error message.
In the example above the expected error message is. (This is what is shown in JIT mode)

```
Uncaught Error: Type ExampleComponent is part of the declarations of 2 modules: ExampleModule and AppModule! Please consider moving ExampleComponent to a higher module that imports ExampleModule and AppModule. You can also create a new NgModule that exports and includes ExampleComponent then import that NgModule in ExampleModule and AppModule.
```

**Comment by deebloo** [comment]
this may be an angular core issue and not a cli issue as referenced. here https://github.com/angular/angular/issues/20292

**Comment by Sky4CE** [comment]
@deebloo , have you tried Angular v5.1.1 ? Similar issue was fixed in v5.1.1

**Comment by filipesilva** [comment]
@PascalPrecht this looks a lot like what we were talking about yesterday. Maybe this is the real issue you are getting?

**Comment by deebloo** [comment]
@Sky4CE I have not. will try now

**Comment by deebloo** [comment]
@Sky4CE @filipesilva updating to 5.1.1 fixed it. I am now seeing the correct error message

**Comment by filipesilva** [comment]
https://github.com/angular/angular/commit/6727336 seems to be the commit that fixes it.

**Comment by shoagraw** [comment]
I am facing this same issue 
<myModuleName>.module.ngfactory.ts doesn't exist
      .js        Field 'browser' doesn't contain a valid alias configuration
and seen these comments,

it seems like this line in packate.json
"@angular/compiler-cli": "^5.0.0",
need to be updated  as
"@angular/compiler-cli": "^5.1.1",

and install it.

Please confirm.

thanks,
Shobhit

**Comment by shoagraw** [comment]
Hi, I am facing same problem <myModule>.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
It seems we need to update following to 5.1.1
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Please let me know if that is correct.

thanks,
Shobhit
