### ISSUE TITLE
when build the project in a script, the index.html is wrong

### ISSUE THREAD

**Issue by yankunsam** [angular/angular-cli#8869]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```
<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Ui</title><base href="C:/msys64/admin/">
### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

### Desired behavior

"C:/msys64" is wrong. I just use a script , build outside the angular project root. Actually , for combine django and angular.

**Comment by Brocco** [comment]
There is not enough information here, please open another following the new issue template.

Please make sure to include steps to reproduce and the versions you are using.
