### ISSUE TITLE
Configure proxy in prod version

### ISSUE THREAD

**Issue by edineia22** [angular/angular-cli#8873]
Hello, how to configure proxy in ng build for prod ?

I have published it local IIS

**Comment by deebloo** [comment]
@edineia22 that would be something you would have to configure on your prod server. The local proxy provided by the CLI is just for local development.

**Comment by xiaohuoni** [comment]
ng build is for static fail。you can use like ‘’koa-proxy‘’

**Comment by edineia22** [comment]
@deebloo  My approach: I would like to know if it's possible to configure this proxy file and use it in our production release. Each client has to be able to configure the file with their own url.

Thanks :)
