### ISSUE TITLE
SKIPPING OPTIONAL DEPENDENCY

### ISSUE THREAD

**Issue by shaugi** [angular/angular-cli#8881]
### Versions
```
<!--
Angular CLI: 1.5.5
Node: 6.11.0
OS: win32 x64
Angular: 5.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0
@angular/cli: 1.5.5
@angular/material: 5.0.0
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.8
typescript: 2.4.2
webpack: 3.8.1
-->
```

npm install --save jquery

and i get this message 

npm WARN angular-material@1.1.5 requires a peer of angular@>=1.4 <1.7 but none is installed. You must install peer dependencies yourself.
npm WARN angular-material@1.1.5 requires a peer of angular-animate@>=1.4 <1.7 but none is installed. You must install peer dependencies yourself.
npm WARN angular-material@1.1.5 requires a peer of angular-aria@>=1.4 <1.7 but none is installed. You must install peer dependencies yourself.
npm WARN angular-material@1.1.5 requires a peer of angular-messages@>=1.4 <1.7 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-carousel-3d@0.1.11 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ jquery@3.2.1
updated 1 package in 175.013s

im trying update my npm with 'npm install npm -g'  command and nothing happen 
still get that message 

any suggestion ??

**Comment by hansl** [comment]
On Windows, `fsevents` is optional and will not be installed by NPM. This is perfectly normal and should not affect the CLI. Everything should work normally.

Please note that we don't depend directly on `fsevents`, but `webpack-dev-server` does.
