### ISSUE TITLE
ng g app-shell Specified module does not exist

### ISSUE THREAD

**Issue by dottodot** [angular/angular-cli#8886]
### Versions
```
Angular CLI: 1.6.1
Node: 8.9.1
OS: darwin x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack-bundle-analyzer: 2.9.1
webpack: 3.10.0
```

### Repro steps
run `ng g app-shell my-shell --universal-app=universal --root src/client`

### Observed behavior
This returns an error of
```
Error: Specified module does not exist
Specified module does not exist
```
I'm not sure what this error is referring to, so no idea how to fix the problem.

The only thing I can think of is that I have a multi app setup where the app I want to add the shell to is in src/client but I'm assuming that's what the `--root` option is for. Other than that everything else looks like it matches the defaults.

**Comment by cyrilletuzi** [comment]
You have to keep the default files names of your universal files, or configure them. See `ng help g app-shell` for details.

**Comment by dottodot** [comment]
I assume you mean the following

```
 --app-id (string) (Default: serverApp)
 --main (string) (Default: main.server.ts)
--tsconfig-file-name (string) (Default: tsconfig.server)
--root-module-file-name (string) (Default: app.server.module.ts) 
--root-module-class-name (string) (Default: AppServerModule)
```
If so I'd already made sure they matched the defaults before I posted.

**Comment by hansl** [comment]
@brocco Please have a look at this.

**Comment by dottodot** [comment]
Also just in case it's relevant, I've tried manually adding the app shell and that also doesn't work as the app shell isn't added to the generated index.html and I also get a server side error of `ReferenceError: System is not defined`

**Comment by smartrobos** [comment]
Why we get ReferenceError: System is not defined; I am also facing a similar issue;
This is issue with trying to build app-shell  ; (The Client component has Lazy Component)

**Comment by smartrobos** [comment]
Is there any update on this; when we can expect in the Release

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
