### ISSUE TITLE
UNMET PEER DEPENDENCY @angular/common@5.0.5, @angular/core@5.0.5, @angular/compiler@5.0.5,  @angular/platform-browser@5.0.5, @angular/platform-browser-dynamic@5.0.5

### ISSUE THREAD

**Issue by abiswas-xtivia** [angular/angular-cli#8892]
### Versions
```
angular-cli: 1.5.5
node: 6.9.4
npm: 3.10.10
OS: Win 10
```

### Repro steps

* Package.JSON - Depenedency
"dependencies": {
        "@angular/animations": "5.0.5",
        "@angular/common": "5.0.5",
        "@angular/compiler": "5.0.5",
        "@angular/core": "5.0.5",
        "@angular/forms": "5.0.5",
        "@angular/http": "5.0.5",
        "@angular/platform-browser": "5.0.5",
        "@angular/platform-browser-dynamic": "5.0.5",
        "@angular/platform-server": "5.0.5",
        "@angular/router": "5.0.5",
        "angular-tree-component": "^6.1.0",
        "angular2-fontawesome": "^0.9.3",
        "angular2-logger": "^0.6.0",
        "angular2-text-mask": "^8.0.1",
        "bootstrap": "^3.3.7",
        "classlist.js": "^1.1.20150312",
        "core-js": "^2.4.1",
        "font-awesome": "^4.7.0",
        "intl": "^1.2.5",
        "ng2-file-upload": "^1.3.0",
        "ng2-scroll-to-el": "^1.0.0",
        "ngx-bootstrap": "^2.0.0-beta.11",
        "ngx-pagination": "^3.0.3",
        "rxjs": "^5.5.2",
        "zone.js": "^0.8.14"
    },
    "devDependencies": {
        "@angular/cli": "1.5.5",
        "@angular/compiler-cli": "5.0.5",
        "@angular/language-service": "5.0.5",
        "@types/jasmine": "~2.5.53",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "~6.0.60",
        "codelyzer": "^4.0.1",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.1.2",
        "ts-node": "~3.2.0",
        "tslint": "~5.7.0",
        "typescript": "~2.4.2"
    }
* npm install

### Observed behavior
```
+-- @angular/animations@5.0.5
+-- @angular/cli@1.5.5
+-- UNMET PEER DEPENDENCY @angular/common@5.0.5
+-- UNMET PEER DEPENDENCY @angular/compiler@5.0.5
+-- @angular/compiler-cli@5.0.5
+-- UNMET PEER DEPENDENCY @angular/core@5.0.5
+-- @angular/forms@5.0.5
+-- @angular/http@5.0.5
+-- @angular/language-service@5.0.5
+-- UNMET PEER DEPENDENCY @angular/platform-browser@5.0.5
+-- UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@5.0.5
+-- @angular/platform-server@5.0.5
+-- @angular/router@5.0.5
+-- @types/jasmine@2.5.54
+-- @types/jasminewd2@2.0.3
+-- @types/node@6.0.94
+-- angular-tree-component@6.1.0
+-- angular2-fontawesome@0.9.3
+-- angular2-logger@0.6.0
+-- angular2-text-mask@8.0.4
+-- bootstrap@3.3.7
+-- classlist.js@1.1.20150312
+-- codelyzer@4.0.2
+-- core-js@2.5.3
+-- font-awesome@4.7.0
+-- intl@1.2.5
+-- jasmine-core@2.6.4
+-- jasmine-spec-reporter@4.1.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.1.1
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.0
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- ng2-file-upload@1.3.0
+-- ng2-scroll-to-el@1.0.0
+-- ngx-bootstrap@2.0.0-rc.0
+-- ngx-pagination@3.0.3
+-- protractor@5.1.2
+-- rxjs@5.5.5
+-- ts-node@3.2.2
+-- tslint@5.7.0
+-- typescript@2.4.2
`-- zone.js@0.8.18

npm ERR! peer dep missing: @angular/common@^4.0.0, required by angular2-fontawesome@0.9.3
npm ERR! peer dep missing: @angular/common@^4.0.2, required by angular2-logger@0.6.0
npm ERR! peer dep missing: @angular/compiler@^4.0.2, required by angular2-logger@0.6.0
npm ERR! peer dep missing: @angular/core@^4.0.0, required by angular2-fontawesome@0.9.3
npm ERR! peer dep missing: @angular/core@^4.0.2, required by angular2-logger@0.6.0
npm ERR! peer dep missing: @angular/platform-browser@^4.0.2, required by angular2-logger@0.6.0
npm ERR! peer dep missing: @angular/platform-browser-dynamic@^4.0.2, required by angular2-logger@0.6.0
```

### Desired behavior

After executing ng serve --aot

I am getting Error(StaticInjectorError[Options]) in Console and Page is not open up.

**Comment by WandererInVoids** [comment]
read about breaking change in angular 5

**Comment by hansl** [comment]
You need to update `angular2-logger` and `angular2-fontawesome` to a version that is compatible with Angular 5. If there's no version of those libraries that's compatible with Angular 5, please file an issue with them to publish one.

Closing this as it's not an issue with the CLI.

**Comment by abiswas-xtivia** [comment]
Thanks hansl for your input.
I removed angular2-logger and angular2-fontawesome and its working fine.
