### ISSUE TITLE
Wrong order in styles inserted inline

### ISSUE THREAD

**Issue by ZIOLele** [angular/angular-cli#8894]
### Type
````
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
````

### Versions
````
Angular CLI: 1.5.0
Node: 7.10.0
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.8.1

Windows 10
````

### Repro steps
* External library with scss files and components with ViewEncapsulation.None
* custom override in style.scss of a variable used in the library at prev step, reevaluation of the full Scss stack in style.scss ( as in the css generated locally overrides the rule in the external library)

### Observed behavior

The new generated css is inserted before the external library one so all the overrides were ignored

### Desired behavior
The new generated css style should be inserted always as last

**Comment by hansl** [comment]
Hi @ZIOLele 

Could you provide a git repo that we can clone for reproducing this error?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
