### ISSUE TITLE
npm ERR! - unable to install @angular/cli on windows 8

### ISSUE THREAD

**Issue by Prathyusha417** [angular/angular-cli#8899]
### Versions
Output from: `ng --version`.  - shows npm errors.
output from: `node --version` - v8.9.3
output from: `npm --version`. - 5.6.0
Windows 8 32 bit.

###
Ran the below commands for installing @angular/cli with old node and npm versions
npm install -g @angular/cli

when I got npm errors uninstalled it by running below commands and tried installing again after updating node n npm versions to latest.
1. uninstalled and installed latest node js v8.9.3
2. npm install npm@latest -g - updated to 5.6.0
3. npm uninstall -g @angular/cli
4. npm cache clean
5. npm install -g @angular/cli

### Observed behavior
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: extsprintf@1.3.0 (node_modules\@
angular\cli\node_modules\extsprintf):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: EIO: i/o error, unlink 'C:\Users
\Prathyu\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\.extsprintf.
DELETE\Makefile.deps'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cryptiles@2.0.5 (node_modules\@a
ngular\cli\node_modules\cryptiles):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: EIO: i/o error, unlink 'C:\Users
\Prathyu\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\.cryptiles.D
ELETE\lib\index.js'

npm ERR! path C:\Users\Prathyu\AppData\Roaming\npm\node_modules\@angular\cli\nod
e_modules\.hosted-git-info.DELETE\index.js
npm ERR! code EIO
npm ERR! errno -4070
npm ERR! syscall unlink
npm ERR! EIO: i/o error, unlink 'C:\Users\Prathyu\AppData\Roaming\npm\node_modul
es\@angular\cli\node_modules\.hosted-git-info.DELETE\index.js'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Prathyu\AppData\Roaming\npm-cache\_logs\2017-12-16T02_10_3
2_148Z-debug.log

Still unable to install @angular/cli on my machine - shows above error. Please help.

**Comment by danwulff** [comment]
@Prathyusha417 `npm cache clean` should throw a warning message in npm 5

```
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.
```
Try running `npm cache verify` or `npm cache clean --force` instead.

If that doesn't work try restarting Windows (I've had a few file system errors with Windows & npm, and restarting sometimes solves the problem ¯\_(ツ)_/¯)

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
