### ISSUE TITLE
App shell build broken with --output-path

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#8901]
### Versions
```
CLI 1.6.1
```

### Repro steps
```
ng new demo --routing
cd demo
ng g app-shell --universal-app universal
ng build --prod output-path test
```

### Observed behavior
```
ENOENT: no such file or directory, scandir '/demo/dist-server/'
```

### Desired behavior
App shell build should work with `output-path`.

### Mention any other details that might be useful
If you launch the universal build before (so the file exists in `dist-server` as the app shell build script expects to), the build will work, but instead of having the client files in the chosen output path, you will have the server files from the second build, which overrided the previous client ones.

**Comment by hansl** [comment]
@alxhub @Brocco  could you look at this error?

**Comment by cyrilletuzi** [comment]
Closing as I'm not sure it's still relevant in v6.
