### ISSUE TITLE
ng g service message1 --module=app

### ISSUE THREAD

**Issue by NilsNaegele** [angular/angular-cli#8908]
### Versions
```
Angular CLI: 1.6.1
Node: 8.3.0
OS: linux x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.0.1
@angular/cli: 1.6.1
@angular/language-service: 4.4.6
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.40
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0

```

### Repro steps
ng g s message1 --module=app
ng g s message1 --module app
ng generate service message1 --module=app

### Observed behavior
Error: Path "/__path__/__name@dasherize@if-flat__/__name@dasherize__.service.spec.ts" does not exist.
Path "/__path__/__name@dasherize@if-flat__/__name@dasherize__.service.spec.ts" does not exist.

### Desired behavior
generate service add it to app module providers array

**Comment by NilsNaegele** [comment]
I'm on the newest version of angular everything. nothing resolves. first generating services in a module and now generating components.
Angular CLI: 1.6.2
Node: 8.3.0
OS: linux x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.0.2
@angular/cli: 1.6.2
@angular/flex-layout: 2.0.0-beta.12
@angular/language-service: 4.4.6
@angular/material: 5.0.2
: 0.0.36
: 0.0.22
: 0.0.40
: 1.1.0
: 1.9.2
: 0.1.11
: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
is it this line in my package.json file: angular-devkit/schematics: "0.0.40" ?

**Comment by NilsNaegele** [comment]
fixed moving another module into another folder. i want to be able to have several ngmodules in one folder. does that make sense? what is this skip-import option that doesn't work? services are not able to be included in a module upon creation, that is an old error we have for some time now. difficult to implement i imagine?

what about the line in my package.json file with schematics, should that be included upon creation of a new app?

**Comment by NilsNaegele** [comment]
same setup with @angular/cli: 1.6.3 ng g c cmp1 -it fails

**Comment by Brocco** [comment]
@NilsNaegele please update your version of `@schematics/angular` [here](https://github.com/angular/angular-cli/blob/f830a8d00737216e438968ec142d58dda5c2cca2/packages/%40angular/cli/package.json#L34) is the latest version, per the CLI (`~0.1.11`).

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
