### ISSUE TITLE
Ember Cli Windows

### ISSUE THREAD

**Issue by axal90** [angular/angular-cli#891]
I have experienced rather sluggish behavior using the angular cli on windows 10.

My understanding is that the angular-cli is based on ember-cli.

After some research I found information suggesting this is because of broccoli being porly optimised on windows (or windows being poorly built, depending on how you look at it). 

It seems like using a package called [ember-cli-windows](https://github.com/felixrieseberg/ember-cli-windows) would solve some of the problems on windows. 
Would this package work with Angular CLI?

They also say its avalible as a [Ember addon](https://github.com/felixrieseberg/ember-cli-windows-addon) so maybe you could ship it with the CLI?

**Comment by braindroplabs** [comment]
@axal90 are you referring to cpu spikes? I've noticed this when I have the cli open with ng serve.

**Comment by axal90** [comment]
@braindroplabs I haven't done any profiling. 
But I assume the cpu would spike due to the immense workload from copying and indexing all files.

My understanding is that symlinks don't work properly on windows so broccoli end up copying a huge amount of files every time you compile. Due to windows search index and other windows features, copying large amount of files is extremely slow on windows. 
Ember-cli-windows sets up the proper settings for your working folder, speeding things up immensly.

**Comment by filipesilva** [comment]
It should be pretty fast if you're running in admin mode. Can you show me the situations where you find it slow?

**Comment by axal90** [comment]
Yes running the cli with elevated privliges does speed it up a bit. But it is still far slower than any other build tool I've used (grunt, gulp, webpack...). I'll try to do a clean install and see if anything changes. but doing some research it seems to be a known problem with ember cli and windows.

**Comment by jmurphzyo** [comment]
You should see what happens when you're using tfs as source control and coding with visual studio.... complete lock ups.

**Comment by RobCannon** [comment]
I have found that storing my source code outside of my user directory seems to alleviate this (i.e c:\Projects).  But I still need to be in an elevated session because of other Brocoli errors.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/905 should allow non-admin user usage.

**Comment by filipesilva** [comment]
Looking through https://github.com/felixrieseberg/ember-cli-windows, it seems it requires both Powershell and perhaps also to run a Powershell command as an admin for it to run (which we can't do automatically). 

I don't think we should add these baseline for everyone, but it's still good that it can be used in separate.
