### ISSUE TITLE
angular-cli is not working

### ISSUE THREAD

**Issue by beingbing** [angular/angular-cli#8913]
#### I'm opening this issue because:
  - [0] angular-cli is doing something I don't understand.

#### What's going wrong?

(after migrating into desired folder)when i ran -
`ng new my-app`
this is what i got -
![screenshot from 2017-12-16 13 54 07](https://user-images.githubusercontent.com/26813160/34072924-ce18699c-e2b5-11e7-86ca-b957b69dd774.png)

even when i ran -
`ng --version`
i am getting the same error

### supporting information:

 - `npm -v` prints:  5.6.0
 - `node -v` prints: v8.9.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues: none

**Comment by filipesilva** [comment]
What does ` migrating into desired folder` mean in your report? I cannot see this problem when running `ng new` myself.

**Comment by beingbing** [comment]
"migrating into desired folder" means, going inside the folder in which i want to create my angular app using angular-cli

**Comment by filipesilva** [comment]
I think you might have a broken install maybe. I'm not sure of the exact causes for that, but I can tell you that we're declaring the right packages for Angular CLI. We reinstall it dozens of times a day.

Some of the modules needed aren't being installed but that's up to `npm` really. I'm sorry I can't help more.

**Comment by Yerkon** [comment]
@beingbing, Why are you not just reinstall cli globally?
```
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli
```

**Comment by filipesilva** [comment]
Closing as there hasn't been any activity for a while.
