### ISSUE TITLE
can't install 

### ISSUE THREAD

**Issue by AmayerGogh** [angular/angular-cli#8916]
cnpm install -g @angular/cli
this is error
![image](http://olyh26zl9.bkt.clouddn.com/20171218130310.png)
help~

**Comment by hansl** [comment]
Hi @AmayerGogh,

This looks like an issue with cnpm itself, not the CLI. Could you file an issue with their repository: https://github.com/cnpm/cnpm/issues/new

Thanks. Will close this in the meantime.
