### ISSUE TITLE
angular-cl is stuck in loop while downloading packages

### ISSUE THREAD

**Issue by beingbing** [angular/angular-cli#8918]
after running command -
`sudo npm install -g @angular/cli`

i got stuck in a loop - 
![screen shot 2017-12-18 at 11 57 19 am](https://user-images.githubusercontent.com/26813160/34092765-1bca5bf6-e3eb-11e7-8e71-26b982cc3323.png)
node version: v9.3.0
npm version: 5.6.0

although on doing -
`ng --version`
i am getting the output -
![screen shot 2017-12-18 at 12 02 45 pm](https://user-images.githubusercontent.com/26813160/34092842-6ddadc9a-e3eb-11e7-928d-d719c838c305.png)

**Comment by clydin** [comment]
This is due to a permission issue with the node installation.  One option is to remove the current node installation and use a node version manager such as [nvm](https://github.com/creationix/nvm) to install and manage the node installation.  This will also eliminate the need to use `sudo`.
