### ISSUE TITLE
Expected 'styles' to be an array of strings while running server

### ISSUE THREAD

**Issue by srikant21** [angular/angular-cli#8919]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
--> Window 7
```
Angular CLI: 1.6.0
Node: 6.10.3
OS: win32 x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0

### Repro steps

* Step 1
ng serve

### Observed behavior
```
Styles to be an array of string

### Desired behavior
<!--
It should run my application without the style error.
-->

**Comment by filipesilva** [comment]
You probably have a component where the `styles` key is not an array. Double check your components for this problem and please open a new issue with a reproduction if you're still seeing this error.
