### ISSUE TITLE
"ng serve --prod" keeps giving the same error even the file is changed

### ISSUE THREAD

**Issue by bunyaminsg** [angular/angular-cli#8924]
### Versions
```
@angular/cli: 1.4.7
node: 6.12.2
os: linux x64
@angular/animations: 4.4.5
@angular/cli: 1.4.7
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/compiler-cli: 4.4.5
@angular/core: 4.4.5
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/platform-server: 4.4.5
@angular/router: 4.4.5
@ngtools/webpack: 1.7.4
typescript: 2.5.3

OS: Ubuntu 14.04

```

### Repro steps

* ng serve --prod (gives error)
* some changes that must disappear the error
* ng serve --prod (same error)

### Observed behavior
I had a line as below:
```
<ng-container *ngIf="!resource.performer">
```
The `performer` entity is an object. When I try to serve it in production mode, it gives the error:
```
Type 'X' is not assignable to type 'boolean'.
```
I tried some other things to fix it and at the end I just put a boolean in the `*ngIf` to see if there is something wrong:
```
<ng-container *ngIf="true">
```
When I run the `ng serve --prod` command again, it gave the exact same error: `Type 'X' is not assignable to type 'boolean'.`. It acts like the old file is cached and used again.

### Desired behavior

To run just as it should.

### Mention any other details that might be useful (optional)
I don't know if it may be related with the IDE but just as an extra information, I am using WebStorm.

**Comment by filipesilva** [comment]
Heya, have you checked maybe your browser cache? Maybe it's another component that's showing that error even.

Happy to take a look at a repro.

**Comment by bunyaminsg** [comment]
@filipesilva No, I am sure the error is in that component. Also, the error did not appear at runtime in the browser, it was in the command line while compiling.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
