### ISSUE TITLE
Proposal: build environment names should be checked against .angular-cli.json config

### ISSUE THREAD

**Issue by nicholasserra** [angular/angular-cli#8927]
I just spent a while debugging an issue with specifying named build environments that could have been avoided if appropriate warnings were thrown in advance.

Proposal: 

Running the command `ng build --environment=staging` should first check to ensure that `staging` is a valid choice in the `.angular-cli.json` > `apps[0]['environments']` object before attempting to run.

Currently, if there exists no such environment, the build will just default to development environment settings.

In my case, I came into an existing project that had no `environments` object in the config and was tasked with making it work. I incorrectly added the `environments` to the root of the config.

After reading the [build doc](https://github.com/angular/angular-cli/wiki/build#build-targets-and-environment-files) several times I finally noticed the only mention that `environments` needs to be nested within the `apps[0]` object halfway down the page. 

I think this will help debugging. Thanks!

**Comment by filipesilva** [comment]
Yeah we could definitely show better errors for missing stuff in the config files. This is something we're working on in https://github.com/angular/devkit/pull/334 via schema validation. Later we'll incorporate it into the CLI config as well.

**Comment by clydin** [comment]
This type of validation is now present within the CLI.  CLI 6.0+ contains a large amount of improvements regarding configuration among other areas.
