### ISSUE TITLE
Support for hot module replacement

### ISSUE THREAD

**Issue by mattdistefano** [angular/angular-cli#893]
I see this was discussed a little in #298 but I don't see a definitive answer there - are there any plans to support this feature in the CLI?

**Comment by intellix** [comment]
Wasn't aware that it was available yet, but installed angular2-webpack-starter from AngularClass and it seems very much so: https://github.com/AngularClass/angular2-webpack-starter

Makes development much easier, as every file change triggers about 6 seconds as it fetches 300+ files.

**Comment by filipesilva** [comment]
No plans atm, but I am happy to leave the issue open and labelled for now.

**Comment by intellix** [comment]
Now we have webpack, I guess I'll link to the conversation here: https://github.com/angular/angular-cli/pull/1402

**Comment by filipesilva** [comment]
@Foxandxss mentioned https://github.com/AngularClass/angular2-hmr, which seems to implement it for webpack.

**Comment by alexjoverm** [comment]
I've just searched for this feature, popped into https://github.com/AngularClass/angular2-hmr and hoped to have it available on the angular-cli tool... +1 for this feature!

**Comment by johnchristopherjones** [comment]
There's a [recent article demonstrating the use of hot reloading](http://teropa.info/blog/2016/08/08/angular-2-hot-loading-with-ngrx-store-and-webpack.html) using Webpack.

**Comment by radusuciu** [comment]
I've put up a very basic implementation of HMR working with Angular RC5 and Webpack:

https://github.com/radusuciu/webpacked-angular-with-dll

**Comment by intellix** [comment]
Played with your example radusuciu and it feels quite nice. For implementation in angular-cli I guess we need as far as I can see:
 - Enable HMR with Node.JS API: https://webpack.github.io/docs/webpack-dev-server.html#hot-module-replacement-with-node-js-api
 - Add @angularclass/hmr and @angularclass/hmr-loader to package.json
 - Create `/src/app/shared/hmr.class.ts` and have app.module.ts extend it.

Do all modules need to extend hmr.class or just the first AppModule? Your example only has a single component inside one module.

**Comment by rbasniak** [comment]
@intellix I tried to follow your steps, but my `node_modules/angular-cli/addon/` folder doesn't have a `ng2` folder. Would you know what I'm missing?

**Comment by paralin** [comment]
Are there any updates to this?

**Comment by intellix** [comment]
@paralin yeah it was merged and now available. There's an example of how to implement it in your project on this: https://github.com/angular/angular-cli/pull/3330

**Comment by paralin** [comment]
@intellix sweet! Can we close this then?

**Comment by intellix** [comment]
Yeah I think so. I dunno who can

**Comment by conqsys** [comment]
sssssssssssssssssssssssssssssss

**Comment by pauldraper** [comment]
To anyone looking for this, I recommend taking a look at https://github.com/wags1999/angular-hmr-lazy-components
