### ISSUE TITLE
source maps not generated for server bundle

### ISSUE THREAD

**Issue by kevinphelps** [angular/angular-cli#8931]
### Versions
```
Angular CLI: 1.6.1
Node: 8.9.1
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
typescript: 2.7.0-dev.20171216
webpack-bundle-analyzer: 2.9.0
webpack-node-externals: 1.6.0
webpack: 3.10.0
```

### Repro steps
1. Create new app with `ng new ...`.
2. Follow https://github.com/angular/angular-cli/wiki/stories-universal-rendering.
3. Add `--sourcemaps` to both `ng build` commands in the `package.json` file.
3. Run `yarn run build:ssr && yarn run serve:ssr`.

### Observed behavior
Sourcemaps are generated for the browser build, but not for the server build.

### Desired behavior

Sourcemaps should be generated for the server build. This would allow better server error stack traces when using https://www.npmjs.com/package/source-map-support.

**Comment by astegmaier** [comment]
This might be the root cause of https://github.com/aspnet/JavaScriptServices/issues/1449

**Comment by astegmaier** [comment]
We concluded that this issue is probably the root cause of [issue #1449 in the new CLI-based dotnet core angular templates](https://github.com/aspnet/JavaScriptServices/issues/1449). I'm not sure I have the expertise to fix this myself at the moment, but I would be among the happy customers if this were addressed.

**Comment by glebmachine** [comment]
Any news guys?

I'm unable to use sourcemaps to debug nodejs app.
That makes me cry sometimes 😑

**Comment by tolzhabayev** [comment]
Any update on that?

**Comment by glebmachine** [comment]
Oh, come on guys @filipesilva @mhevery
Thats so important to work with universal projects

**Comment by mhevery** [comment]
@glebmachine Such comments are not in the best spirit. We are doing best we can we the resources we have. Solving this issue means that we don't solve a different issue. To you this is very important, but we have to weigh it against all other issues we have to focus on, and in grand scheme of things there are more important issues which effect more people which need to get addressed first. Feel free to create a fix and send a PR.

**Comment by kevinphelps** [comment]
This is working on `@angular/cli@6.1.0-rc.0` with the `@angular-devkit/build-angular:server` builder and the `--source-map` flag.

**Comment by glebmachine** [comment]
Thank you guys!

@mhevery, totally agree with you, thank for you job and excuse me to being selfish here)
