### ISSUE TITLE
EmptyObservable.js not found

### ISSUE THREAD

**Issue by roshenpo007** [angular/angular-cli#8932]
Unhandled Promise rejection: (SystemJS) XHR error (404 Not Found) loading ..../node_modules/rxjs/Observable/EmptyObservable.js.

package.json

`"rxjs": "^5.4.3",`

ts file added the import 

`import { EmptyObservable } from 'rxjs/Observable/EmptyObservable';`

**Comment by jotatoledo** [comment]
The path is wrong. It should be 

from “rxjs/observable/EmptyObservable“;

See https://github.com/ReactiveX/rxjs/blob/master/src/observable/EmptyObservable.ts

**Comment by roshenpo007** [comment]
got fixed. Thanks
