### ISSUE TITLE
Using image in html img tag returns 404 (Not Found)

### ISSUE THREAD

**Issue by London804** [angular/angular-cli#8933]
### Versions
 Angular CLI: 1.5.2
Node: 8.9.1
OS: darwin x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.2
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.2
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.8.1

### Repro steps

In your html component create a img tag. e.g. <img src="./assets/img/Circulation.png" alt="Bitcoin Market Price USD">

### Observed behavior
The image does not render. In my browser I get a 404 Not found. This doesn't change regardless if I use a absolute or relative path. 

### Desired behavior
My image should appear. 

### Mention any other details that might be useful (optional)
My images were working and then I deleted my cache and all of sudden they would not render anymore.

**Comment by filipesilva** [comment]
I'm going to need a repro for this. Where is the image being loaded from? Maybe it's not in your assets, or you are deploying to a location where the image path is different.

**Comment by UshaSanjeevam** [comment]
<img src="../images/asterisk.png" style="font-size:24px" /> --HTML page

And below is the folder structure.
![capture](https://user-images.githubusercontent.com/42132120/43699574-f27f366c-996c-11e8-9858-9522ed29d9e4.PNG)

Please help me

**Comment by UshaSanjeevam** [comment]
I got the solution 

I had to put the image to the /src/assets folder. Angular is now able to find the image.

**Comment by alan-agius4** [comment]
Looks like it has been unanswered above.
