### ISSUE TITLE
Angular CLI doesn't generate styles sourcemaps when served with AOT

### ISSUE THREAD

**Issue by kHorozhanov** [angular/angular-cli#8935]
### Versions
```
Angular CLI: 1.6.1
Node: 8.1.4
OS: darwin x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.1
@angular/cli: 1.6.1
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```
### Repro steps
When i'm runing ``` ng serve -ec -sm ``` all works correct.
![1](https://user-images.githubusercontent.com/15924598/34149767-cfce8bcc-e4ae-11e7-9a42-cd01acf07dfd.png)

But if i'm trying to use ``` ng serve -ec -sm -aot ``` Angular CLI doesn't generate sourcemaps.
![2](https://user-images.githubusercontent.com/15924598/34149778-d8cdf6e0-e4ae-11e7-8eb1-f83c0f1963c0.png)

**Comment by clydin** [comment]
Are those styles from a component's stylesheet or from a global stylesheet?  Also were they originally pure CSS or in SCSS/LESS/etc.?

**Comment by kGorozhanov** [comment]
@clydin As you can see in first screenshot - its a component styles and i'm using SCSS

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
