### ISSUE TITLE
ng g service error 

### ISSUE THREAD

**Issue by xiaohuoni** [angular/angular-cli#8938]
D:\td-share-ng>ng g service services/location-service
Error: ELOOP: too many symbolic links encountered, stat 'D:\td-share-ng\node_modules\@angular\cli\node_modules\webpack\node_modules\escope\node_modules\es6-map\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d'
ELOOP: too many symbolic links encountered, stat 'D:\td-share-ng\node_modules\@angular\cli\node_modules\webpack\node_modules\escope\node_modules\es6-map\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d\node_modules\es5-ext\node_modules\es6-iterator\node_modules\d'

**Comment by filipesilva** [comment]
Does this happen on a new project? We'll need some repro steps that we can follow to investigate.

**Comment by xiaohuoni** [comment]
yes  this is a  new project

**Comment by pzw224** [comment]
Same problem as you. It's a new Project.
Good work for ng g component/class

Error: ELOOP: too many symbolic links encountered

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
