### ISSUE TITLE
file structure for a lot of services, pipes...

### ISSUE THREAD

**Issue by krasevych** [angular/angular-cli#894]
Hi all.
If I have a lot of services, pipes... is it a good idea to create file structure like this:
`app/shared/services`
`app/shared/pipes`
`app/shared/components`
......
?
I read style guide and there are recommendation that put all general services and other... direct to app/shared folder

**Comment by splintercode** [comment]
I have been following a similar structure as to what you have.  :)

**Comment by krasevych** [comment]
do you mean this: 
`app/shared/services`
`app/shared/pipes`
`app/shared/components`
?

**Comment by splintercode** [comment]
Yeah, that's what my shared folder looks like.

**Comment by filipesilva** [comment]
Currently the recommendations can be found in https://angular.io/docs/ts/latest/guide/style-guide.html#!#application-structure

The idea is that you'd put your services/pipes/components directly in `app/shared`, but when you have stuff that is only used on one route you put it in `app/route-name/shared` instead. 

When you start having a lot of routes and subroutes, it's easy to have services/pipes/components only available to that subtree.

**Comment by krasevych** [comment]
Thank you!
