### ISSUE TITLE
ng new issue with Angular CLI: 1.6.1

### ISSUE THREAD

**Issue by nsosale** [angular/angular-cli#8941]
Versions
Angular CLI: 1.6.1
Node: 8.9.3 npm -v: 5.6.0 OS: win32 x64

3:ran  :    ng new myapp

4:result:   

**Error: obs.pipe is not a function
obs.pipe is not a function**

I searched google and did not get any hint or solution.

Any input will be appreciated

**Comment by hansl** [comment]
Try to reinstall the CLI globally. Your global RxJS seems to be the wrong version (`pipe` was added in 5.5).

**Comment by palmo25** [comment]
I'm having the exact same issue... I've tried to reinstall the CLI several times but still I 'm failing to solve the problem.

**Comment by nsosale** [comment]
Hi Palmo

 

Are we talking about the same issue:

Error: obs.pipe is not a function
obs.pipe is not a functi

 

Above problem is because of older RXJS  version  -- for some reason it did not update RXJS to

the latest version or  there could be a cached older version floating around.

Search for rxjs  folder  -- if found remove the older ones.

 

Also  ran                   npm install -g rxjs^5.5   

That resolved my issue.
