### ISSUE TITLE
How to specify Vary: Accept-Encoding header for an Angular 4 application?

### ISSUE THREAD

**Issue by BattiniSantthosh** [angular/angular-cli#8943]
### Angular 4 with universal 
How to specify Vary: Accept-Encoding header for an Angular 4 application?

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
