### ISSUE TITLE
Extension of Issue#3411

### ISSUE THREAD

**Issue by Shaswat1994** [angular/angular-cli#8944]
**Bootstrap v3.3.7
Angular CLI: 1.5.2
Node: 8.9.1
OS: win32 x64
Angular: 5.0.1**

Installed bootstrap via npm:
`npm install bootstrap`

* Added the bootstrap.css file to angular-cli.json file as:
`"styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.css"
      ],`
I started the server using:
`ng serve `

Even after linking bootstrap.css path to styles array in angular-cli.json file, bootstrap classes are not getting loaded in the project..

**Comment by Shaswat1994** [comment]
How do I load bootstrap to my project?

**Comment by filipesilva** [comment]
What are you seeing or not seeing that makes you think it's not working? Can you tell me what I can do to see the same as you?
