### ISSUE TITLE
CTRL+C kills the root shell after the recompilation

### ISSUE THREAD

**Issue by zhekaus** [angular/angular-cli#8946]
If I run `bash -c "ng serve; $SHELL"` and press CTRL+C, `ng` finishes its work and shell ($SHELL) starts;

However, if I `touch src/main.ts` to invoke the recompilation, CTRL+C quits bash process and $SHELL doesn’t start.

### Versions
```
Angular CLI: 1.5.5
Node: 8.9.1
OS: win32 x64
Angular:
```

### Repro steps

* `bash -c "ng serve; $SHELL"`
* `touch src/main.ts` (or any file in the project) via another terminal
* <kbd>CTRL+C</kbd>

### Observed behavior
```
ng quits, $SHELL doesn't start
```

### Desired behavior
ng quits, $SHELL starts in order to start `ng server` again later.

### Mention any other details that might be useful (optional)

I prefer to run my environment with a single hit. It starts different developer services in different terminals. When I hit <kbd>Ctrl+C</kbd> I suppose to be able to restart service in the same terminal.

**Comment by filipesilva** [comment]
Heya, is this still a problem for you with current versions of the CLI?

**Comment by alan-agius4** [comment]
Closing as no further feedback was provided by the issue author.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
