### ISSUE TITLE
Error when build and run server

### ISSUE THREAD

**Issue by aalshaikh** [angular/angular-cli#8956]
### Versions
Angular CLI: 1.6.2
Node: 6.11.3
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cli: 1.6.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.6.2
webpack: 3.10.0

i followed the steps to build server side rendering from this doc:
https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/universal-rendering.md

but when i run: npm run build:ssr && npm run serve:ssr it's build fine but the server not working below the error appear in terminal:

`> widget-angular@0.0.0 serve:ssr /Users/apple/Desktop/xxx/widget-revamp
> node dist/server.js

/Users/apple/Desktop/xxx/widget-revamp/dist/server.js:176964
    __metadata("design:paramtypes", [Event]),
                                     ^

ReferenceError: Event is not defined
    at Object.c (/Users/apple/Desktop/xxx/widget-revamp/dist/server.js:176964:38)
    at __webpack_require__ (/Users/apple/Desktop/xxx/widget-revamp/dist/server.js:20:30)
    at Object.defineProperty.value (/Users/apple/Desktop/xxx/widget-revamp/dist/server.js:159189:10)
    at __webpack_require__ (/Users/apple/Desktop/xxx/widget-revamp/dist/server.js:20:30)
    at Object.p4j/ (/Users/apple/Desktop/xxx/widget-revamp/dist/server.js:153978:572407)
    at e (/Users/apple/Desktop/xxx/widget-revamp/dist/server.js:153978:149)
    at Object.9lYv (/Users/apple/Desktop/xxx/widget-revamp/dist/server.js:153978:108048)
    at e (/Users/apple/Desktop/xxx/widget-revamp/dist/server.js:153978:149)
    at Object.bJO+ (/Users/apple/Desktop/xxx/widget-revamp/dist/server.js:153978:397422)
    at e (/Users/apple/Desktop/xxx/widget-revamp/dist/server.js:153978:149)

npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve:ssr"
npm ERR! node v6.11.3
npm ERR! npm  v5.5.1
npm ERR! code ELIFECYCLE
npm ERR! widget-angular@0.0.0 serve:ssr: `node dist/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the widget-angular@0.0.0 serve:ssr script 'node dist/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the widget-angular package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs widget-angular
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls widget-angular
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/Desktop/xxx/widget-revamp/npm-debug.log`

**Comment by Gnorro** [comment]
Same error for me in server.js in line:
__metadata("design:paramtypes", [Event]),

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
