### ISSUE TITLE
ng build --prod successfully builds(AOT) the project but throws a error when hosted

### ISSUE THREAD

**Issue by psnmissaka** [angular/angular-cli#8958]
### Versions
```
@angular/cli: 1.3.1
node: 8.3.0
os: win32 x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/platform-server: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.3.1
@angular/compiler-cli: 4.2.6
```

### Repro steps
* `ng build --prod`
 This builds the project with following output
```
Date: 2017-12-21T09:10:36.140Z
Hash: 1c2164be4efc45699ced
Time: 87975ms
chunk {0} 0.6e3027e185996e2c678c.chunk.js (common) 37.8 kB {4}  [rendered]
chunk {1} 1.072f621a54c7d58bb66f.chunk.js () 545 kB {4}  [rendered]
chunk {2} 2.2436520b597e61c727e6.chunk.js () 159 kB {4}  [rendered]
chunk {3} polyfills.1c5c9d852977c539765d.bundle.js (polyfills) 93.3 kB {8} [initial] [rendered]
chunk {4} main.d257c6a35b523ee42fa5.bundle.js (main) 343 kB {7} [initial] [rendered]
chunk {5} scripts.538f96980ede639ab1d0.bundle.js (scripts) 774 kB {8} [initial] [rendered]
chunk {6} styles.b8e3c13040a5ca6fa485.bundle.css (styles) 761 kB {8} [initial] [rendered]
chunk {7} vendor.fa97e80a7dd3e537fecc.bundle.js (vendor) 1.26 MB [initial] [rendered]
chunk {8} inline.aebaed3a7aa5d137ecea.bundle.js (inline) 1.55 kB [entry] [rendered]
```
* Run a python SimpleHTTPServer with the distribution (navigating to the dist folder and running `python -m SimpleHTTPServer 4200`)
* Go to `localhost:4200` on Chrome browser

### Observed behavior
Loader in my app appears and the app would not load as intended. console display the following error
```
vendor.fa97e80a7dd3e537fecc.bundle.js:1 Uncaught TypeError: Cannot read property 'a' of undefined
    at Object.oxwE (vendor.fa97e80a7dd3e537fecc.bundle.js:1)
    at n (inline.aebaed3a7aa5d137ecea.bundle.js:1)
    at Object.<anonymous> (vendor.fa97e80a7dd3e537fecc.bundle.js:1)
    at Object.Xg3h (vendor.fa97e80a7dd3e537fecc.bundle.js:1)
    at n (inline.aebaed3a7aa5d137ecea.bundle.js:1)
    at Object.UyBN (vendor.fa97e80a7dd3e537fecc.bundle.js:1)
    at n (inline.aebaed3a7aa5d137ecea.bundle.js:1)
    at Object.cDNt (main.d257c6a35b523ee42fa5.bundle.js:1)
    at n (inline.aebaed3a7aa5d137ecea.bundle.js:1)
    at Object.0 (main.d257c6a35b523ee42fa5.bundle.js:1)
```
![image](https://user-images.githubusercontent.com/12370895/34250364-a8d89f84-e662-11e7-8d68-9d86b9a6a463.png)

### Desired behavior
Desired behavior is app is working as intended as a normal Angular app would.

### Mention any other details that might be useful (optional)
I have realized that this happens when trying to build the production distribution. `ng build --aot` distribution works as intended, so does `ng serve --aot` .

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? It might be a vendor library that isn't compatible with AOT.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by psnmissaka** [comment]
Sure i will try to setup a minimal repro asap. 
And it also occurred to me that this might be because of a vendor library as you mentioned. But shouldn't such incompatibilities be checked during the build?
I had one library which actually didn't have the AOT which caused a error during build.  But i used a AOT supported version of that package and it solved error.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
