### ISSUE TITLE
(bug) "node-sass" is no longer optional dependency

### ISSUE THREAD

**Issue by asafMasa** [angular/angular-cli#8959]
### Versions
"1.6.0"

### Repro steps
npm install  --no-optional

### Observed behavior
node-sass is installed

### Desired behavior
node-sass will not be installed

### Mention any other details that might be useful (optional)
https://github.com/webpack-contrib/sass-loader/issues/519

latest sass-loader dependency (6.0.6) requires node-sass as a peerDependencies
"peerDependencies": {
   **"node-sass": "^4.0.0",**
    "webpack": "^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0"
  },

**Comment by filipesilva** [comment]
Unsure of what we can do about this right now. Perhaps we have to pin `sass-loader` to maintain previous behaviour.

**Comment by asafMasa** [comment]
@filipesilva @hansl what is the status of this issue?

**Comment by DmitriiSer** [comment]
It would be nice if you allow to install Angular CLI without `node-sass`. Our enterprise people decided that `Python 2.7` is no longer allowed to be installed on user machines (only v3.4+ are approved). Hence, it is impossible to utilize `node-sass` package and SASS in general in Angular projects. In addition, they blocked the entire GitHub and `node-sass` tries to download binaries from there no matter what in-house NPM repos are configured in _.npmrc._ file.

**Comment by kevmando** [comment]
Hi,
we have the similar situation as @DmitriiSer mentioned.
At least, our company allows to upload the 3rd party dependency to internal repo after a review process - which takes time, but it requires us to maintain the dependencies.
So whenever node-sass releases a new version, we have to deal with the process and can't build the product until the review is done.

**Comment by ISkomorokh** [comment]
I see different behaviors when using `npm install` and `npm ci`. In the case of `npm install` everything is ok. In the case of `npm ci` the build fails because of postinstall step and missing PYTHON :(

**Comment by filipesilva** [comment]
Currently `node-sass` is only a optional dependency of `@angular-devkit/build-angular`, and isn't a direct dependency of any package we use.

**Comment by ISkomorokh** [comment]
@filipesilva so how do I skip it during `npm ci`?

**Comment by filipesilva** [comment]
@ISkomorokh I don't think `npm` commands allow you to skip a package. If you're seeing different behaviours between `npm install` and `npm ci`, a better place to ask is in the NPM issue tracker.

**Comment by asafMasa** [comment]
iv'e used $ npm install --ignore-scripts

https://stackoverflow.com/questions/23505318/npm-disable-postinstall-script-for-package
