### ISSUE TITLE
Consider CoC approach

### ISSUE THREAD

**Issue by nfantone** [angular/angular-cli#896]
I'm just starting with the tool, but after running my first examples the single most important thing that stroke me was the amount of boilerplate and configuration files the CLI generates. 

My beloved Angular 1.x projects have a `gulpfile.js` and, some of them, may include an additional `.json` config file. Maybe a `karma.conf.js`. And that was it. And we are talking about projects using a complex, production-ready build system. 

In a barebones project generated by **angular-cli**, you are presented with:

- `.clang-format`
- `angular-cli-build.js`
- `angular-cli.json`
- `system-config.ts`
- `tsconfig.json` (x2!)
- `environment.ts`.
- `environment.dev.ts`
- `environment.prod.ts`
- `karma.conf.js`
- `karma-test-shim.js`
- `protractor.conf.js`

And that's on top of the regular configuration/linter files like `package.json`, `tslint.json`, `typings.json`, `.editorconfig`, etc. All of which should be versioned and maintained. There is, literally, more configuration here than actual implementation. It's rather overwhelming. Not to mention cumbersome.

Is there not a possibility here where we could benefit from using a _Convention over Configuration_ approach?

Take `angular-cli-build.js`, for instance. What's its purpose? What's the need for this?

```js
module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)'
    ]
  });
};
```

All of that information is already available @ `package.json`. Same goes for `angular-cli.json`. It looks like its duplicating pre-existing metadata and configuring some stuff that's _highly_ unlikely to change for most of us, tool's users.

Am I making any sense?

**Comment by filipesilva** [comment]
There was actually a discussion about this some time ago in https://github.com/angular/angular-cli/issues/443, can I ask you to comment there if you'd like to present arguments as to why some of these files should be removed?

I just merged https://github.com/angular/angular-cli/pull/902 which removed `.clang-format` (since it was recently removed).

The `angular-cli-build.js` file defines which files are *actually* copied over to a project build, as these aren't all the ones present in `node_modules`.
