### ISSUE TITLE
npm install -g @angular/cli@latest  -- error

### ISSUE THREAD

**Issue by tharun-d** [angular/angular-cli#8960]
npm ERR! path C:\Users\hpadmin\hell\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\Users\hpadmin\hell\node_module
s\fsevents\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\Users\hpadmin\hell\node_mod
ules\fsevents\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\hpadmin\\he
ll\\node_modules\\fsevents\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\Users\\hpadmin\\hell\\node_modules\\fsevents\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hpadmin\AppData\Roaming\npm-cache\_logs\2017-12-21T14_32_39_331Z-deb
ug.log
Package install failed, see above.
Package install failed, see above.

information
**node version 8.9.3
npm 5.5.1**

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.

I know there were some similar problems on windows that were fixed on npm (https://github.com/npm/npm/issues/17671) and released on `npm@5.6.0`. You could try that version.

**Comment by tharun-d** [comment]
@filipesilva thanks it really worked whem i updated my npm to5.6.0
