### ISSUE TITLE
ServiceWorker doesn't update the app when going "back" to a previous version

### ISSUE THREAD

**Issue by MrCroft** [angular/angular-cli#8962]
### Bug Report or Feature Request
```
- [x] bug report
```

### Versions
```
Angular: 5.1.1
Angular CLI: 1.6.1
```

### Repro steps

1. Create an app (with ServiceWorker) using Angular CLI
2. Build & Serve the app so the ServiceWorker initializes (let's say this would be **version 1** of the app).
3. Change anything in the app.
4. Rebuild & Serve (let's say this is **version 2** of the app).
5. Access the app and then refresh to get the update.
6. Undo the change you did at point (**3**) above.
7. Rebuild & Serve.
8. Access the app and try refreshing to get the update. Nothing happens. You're stuck on version 2 of the app.

### Observed behavior
The v1 code is still cached after the update to v2. I guess because there is no notion of "this is the bundle for module X". Each file is simply... a file.
But it just doesn't go "back" to use the previously cached version after we undo some changes that generate the exact v1 bundles again (or some of them, anyway).

### Desired behavior
Any change in the app code should trigger the update.

**Comment by filipesilva** [comment]
This seems to have been fixed as https://github.com/angular/angular/issues/24338 so it should be closed here.
