### ISSUE TITLE
ng new app not working, angular-cli overall seems to fail

### ISSUE THREAD

**Issue by omnoms** [angular/angular-cli#8965]
### Versions
```
node --version
v8.9.3

npm --version
5.6.0
```

### Repro steps
* Install latest node.
* Install latest npm.
* npm install -g @angular/cli
  or 
  npm install @angular/cli
  or
  npm install @angular/cli@latest

### Observed behavior
```
C:\temp\Projekt>ng --version
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Web\External\node_modules\@angular\cli\bin\ng'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

### Desired behavior
That it creates a new app for me when I do `ng new <appname>`

**Comment by omnoms** [comment]
This seems to be related to Visual Studio installation that is interfering with the environmental variables/npm settings. Because once I ran the nodevars.bat in nodejs installation directory, there was no longer any issues.

**Comment by rajneeshkumardev** [comment]
I ma also getting the same error have any one find any solution to this.
