### ISSUE TITLE
Error while installing angular-cli - ECONNRESET

### ISSUE THREAD

**Issue by glyph002** [angular/angular-cli#8966]
tried install angular cli with   npm install -g @angular/cli

**Issue message**

npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/util/-/util-0.10.3.tgz fa
iled, reason: read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2017-12-21T23_48_02_2
39Z-debug.log

tried reset proxy settings but didn't work, i have no clue

can anyone help me with this issue?

**Comment by osmanrahimi** [comment]
I have the same problem ,
 Could you find any solution ?

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.

It looks like a proxy problem like the message says.

**Comment by glyph002** [comment]
i've uninstall google chrome and node.js. Installed all updates for windows
(have blocked automatic updates and collected big amount of updates to
install). Then restart computer and installed chrome againn, next installed
node.js and finally i've been able to install angular CLI. I don't know
which step help me with angular (i suppose updates for windows), but i
recommend all of these.


2017-12-24 9:27 GMT+01:00 Osman Rahimi <notifications@github.com>:
