### ISSUE TITLE
Getting warning on ng serve

### ISSUE THREAD

**Issue by Mugesh-Rajaram** [angular/angular-cli#8968]
Hi,

  Am getting warning while running **ng serve**. I have implemented aliases path in tsconfig.json file. 

### Warning
```
<!--
WARNING in ./src/app/core/Core.module.ts
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\Projects\Samples\Folder-Structure\node_modules\@ngtools\webpack\src\index.js!D:\Projects\Samples\Folder-Structure\src\app\core\Core.module.ts
    Used by 1 module(s), i. e.
    D:\Projects\Samples\Folder-Structure\node_modules\@ngtools\webpack\src\index.js!D:\Projects\Samples\Folder-Structure\src\app\core\index.ts
* D:\Projects\Samples\Folder-Structure\node_modules\@ngtools\webpack\src\index.js!D:\Projects\Samples\Folder-Structure\src\app\core\core.module.ts
    Used by 1 module(s), i. e.
    D:\Projects\Samples\Folder-Structure\node_modules\@ngtools\webpack\src\index.js!D:\Projects\Samples\Folder-Structure\src\app\app.module.ts
-->
```

![image](https://user-images.githubusercontent.com/16976667/34288867-a4cff4ce-e715-11e7-89fb-493bae8cb179.png)

**Comment by filipesilva** [comment]
Hi,

This message is a warning about import names. It means that you are importing the same module (`src/app/core/core.module.ts`) but using different casings:
- `Core.module.ts` in `src/app/core/index.ts`
- `core.module.ts` in `src/app/app.module.ts`

Like the error message says, this can cause problems depending on the filesystem. You should always import the correct filename, in this case `core.module.ts` (with lowercase `C`).

**Comment by Mugesh-Rajaram** [comment]
@filipesilva  Thank you
