### ISSUE TITLE
Angular CLI max number of components

### ISSUE THREAD

**Issue by MarcoSantino** [angular/angular-cli#8975]
Hi all,

I have a problem with Angular CLI about includes. This is my **app.module.ts**:

> import { BrowserModule } from '@angular/platform-browser';
> import { NgModule } from '@angular/core';
> import { HttpModule } from '@angular/http';
> import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
> import { FormsModule } from '@angular/forms';
> import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
> import { routing } from './app.routes';
> import { AppComponent } from './app.component';
> import { HeaderComponent } from './header/header.component';
> import { MapComponent } from './map/map.component';
> import { ProfileComponent } from './profile/profile.component';
> import { ListVolunteerComponent } from './list-volunteer/list-volunteer.component';
> import { searchPipe } from './_pipe/filter.pipe';
> import { CertificateComponent } from './certificate/certificate.component';
> import { ListCertificatesComponent } from './list-certificates/list-certificates.component';
> import { ListVehiclesComponent } from './list-vehicles/list-vehicles.component';
> import { LoginComponent } from './login/login.component';
> import { VolunteerComponent } from './volunteer/volunteer.component';
> import { Page404Component } from './page-404/page-404.component';
> import { VehicleComponent } from './vehicles/vehicle.component';
> import { ServicesComponent } from './services/services.component';
> 
> import { AuthService } from './_services';
> 
> @NgModule({
>     declarations: [
>         AppComponent,
>         HeaderComponent,
>         MapComponent,
>         ProfileComponent,
>         ListVolunteerComponent,
>         searchPipe,
>         CertificateComponent,
>         ListCertificatesComponent,
>         ListVehiclesComponent,
>         LoginComponent,
>         VolunteerComponent,
>         Page404Component,
>         VehicleComponent,
>         ServicesComponent
>     ],
>     imports: [
>         BrowserModule,
>         HttpModule,
>         NgbModule.forRoot(),
>         FormsModule,
>         BrowserAnimationsModule,
>         routing
>     ],
>     providers: [AuthService],
>     bootstrap: [AppComponent]
> })
> export class AppModule { }

When I try to create a new component via terminal, it finish correctly, but when I open the last file that I've create **(ServicesComponent)** in PHPStorm, IDE tell me this error:

_ng: Component 'ServicesComponent' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration_

This is my **services.component.ts**:

> import { Component } from '@angular/core';
> 
> @Component({
>     selector: 'app-services',
>     templateUrl: './services.component.html',
>     styleUrls: ['./services.component.css']
> })
> export class ServicesComponent {
>     constructor() { }
> }

Before this components, I never had this problem. Someone can help me?

**Comment by warapitiya** [comment]
This can be an IDE issue. I'm having the same issue with Webstorm. A quick restart of IDE fixed the issue to me.

**Comment by mateothegreat** [comment]
@MarcoSantino This is an issue related to WebStorm (and IntelliJ) specifically and generates false-positives. I've been able to solve the problem by manually "marking" my `./src/app` directory as a "Resource Root".

Alternatively you can disable/set the inspection to ignore and rely on your compiler to be the source of truth. I've found IntelliJ support for TypeScript in general rough around the edges when it comes to relying on the IDE itself for everything that `ng ..` can do for you.

**Comment by Brocco** [comment]
@MarcoSantino I tend to agree with the other comments that this seems to be an issue with your editor. You can confirm this by attempting to build or run your application via `ng build` or `ng serve` respectively. If those work, which I believe they will, then you know this is an issue with your editor.

**Comment by MarcoSantino** [comment]
Hi,

thank you so much, I solve my problem with a restart of PHPStorm.
