### ISSUE TITLE
Production build sourcemaps mismatch - line number misalignments

### ISSUE THREAD

**Issue by un33k** [angular/angular-cli#8978]
### Request Type
bug [x] This is a bug report

### Versions
```
Angular CLI: 1.6.1
Node: 8.6.0
OS: darwin x64
Angular: 5.2.0-beta.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

@angular/cdk: 5.0.1
@angular/cli: 1.6.1
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.6.2
webpack: 3.10.0

macOS: darwin x64 (High Sierra)
```

### Repro steps
* ng serve (step through the *.ts & line numbers match)
* ng build --env=staging --prod (deploy on staging  - hitting a problem that only shows on prod)
* ng build --env=staging --prod --sourcemap (step through the *.ts & line numbers **don't** match)

### Observed behavior
Put a breakpoint on line #1, then `single` step the code, it jumps to line #11.
```
1    if (headers.has('Message-Count')) {
2      this.messageCount = headers.get('Message-Count');
3    }
     ... (removed for brevity)
10   if (this.localSignature !== this.remoteSignature) {
11     this.statusChanged();
12   }
```

### Desired behavior
Properly built `sourcemap` should have landed on line #10 when single stepping the code & only on line #11 if the condition on #10 was true.

### Mention any other details that might be useful (optional)
I do remember seeing sourcemap misalignment in the beta version. This might be related. While debugging during dev works great, some bugs only show up on prod version and during staging, one should be able to step the prod code and investigate a fix.

**Comment by filipesilva** [comment]
Heya, can you provide a repro that includes such a piece of code that sourcemaps ignore on a new project please? It might be related to uglification or some code optimizations, but I can only investigate with real code that shows this behaviour.

We had sourcemap troubles in the past, and quite recently on prod builds only, so I'd like to get to the bottom of this.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
