### ISSUE TITLE
Scaffolding Class/Models into a angular 2 form.

### ISSUE THREAD

**Issue by jmurphzyo** [angular/angular-cli#898]
I was just wondering if you guys have thought about scaffolding class/models into angular forms? I know visual studio has a scaffolding tool that allows you to generate razor forms from c# classes. I don't know if this is a possibility but it would be extremely cool if you guys implemented a way to scaffold a bare bones form from a given ts class!!!

**Comment by filipesilva** [comment]
This is out of scope of the CLI proper, but there's actually a guide for this at https://travis-ci.org/filipesilva/angular.io !
