### ISSUE TITLE
Linting Error: angular is not define. export namspace angular

### ISSUE THREAD

**Issue by yaxx** [angular/angular-cli#8984]
am using angular in vscode editor, but am having errors saying: "angular is not define, export  namespace angular" please anyone with an idea on this?

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
