### ISSUE TITLE
error network This is a problem related to network connectivity during angular installation

### ISSUE THREAD

**Issue by Mdp142005** [angular/angular-cli#8987]
Hi Team,

I installed below versions
node v8.9.3
npm v5.5.1

Then I am trying to execute below command from cmd. 
npm install -g @angular/cli
npm install -g @angular/cli@latest

I tried both command but getting below error. Request you to help me here.

**1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose npm-session 9f5e62086e7ed227
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @angular/cli@latest request to https://registry.npmjs.org/@angular%2fcli failed, reason: getaddrinfo ENOTFOUND api.ng.bluemix.network api.ng.bluemix.network:80
8 verbose type system
9 verbose stack FetchError: request to https://registry.npmjs.org/@angular%2fcli failed, reason: getaddrinfo ENOTFOUND api.ng.bluemix.network api.ng.bluemix.network:80
9 verbose stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
9 verbose stack     at emitOne (events.js:116:13)
9 verbose stack     at ClientRequest.emit (events.js:211:7)
9 verbose stack     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:106:9)
9 verbose stack     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:126:5)
9 verbose stack     at <anonymous>
9 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
10 verbose cwd C:\
11 verbose Windows_NT 6.2.9200
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
13 verbose node v8.9.3
14 verbose npm  v5.5.1
15 error code ENOTFOUND
16 error errno ENOTFOUND
17 error network request to https://registry.npmjs.org/@angular%2fcli failed, reason: getaddrinfo ENOTFOUND api.ng.bluemix.network api.ng.bluemix.network:80
18 error network This is a problem related to network connectivity.
18 error network In most cases you are behind a proxy or have bad network settings.
18 error network
18 error network If you are behind a proxy, please make sure that the
18 error network 'proxy' config is set properly.  See: 'npm help config'
19 verbose exit [ 1, true ]**

Thank You!

**Comment by ffey** [comment]
Error network request.  perhaps you must set your network proxy.

**Comment by Mdp142005** [comment]
will check for any network issues

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
