### ISSUE TITLE
Angular Elements support

### ISSUE THREAD

**Issue by esistgut** [angular/angular-cli#8988]
[Angular Elements](https://github.com/angular/angular/tree/labs/elements/packages/elements/) is in the process of being [merged in the Angular master branch](https://github.com/angular/angular/pull/21106).
Will angular-cli provide some kind of support to this feature?

**Comment by DaSchTour** [comment]
I've seen `ng add @angular/elements` somewhere which also should add needed polyfills. It seams that there already is some kind of "support" for this feature.
From my point of view the post important thing that should be supported, is some kind of "registration" of elements in angular-cli.json so they will be build and exported on `ng build`.
I don't really know what kind of additional support is needed for angular elements.

**Comment by DaSchTour** [comment]
By looking into the not very well documented eco system around angular cli I guess what is missing is a `@angular-devkit/build-angular:webcomponent` that allows specifying a main that points to a module that contains the webcomponents that should be exported. Additionaly there should be a alternative polyfill file that contains webcomponent polyfills. Something like this:
```
"build": {
          "builder": "@angular-devkit/build-angular:webcomponent",
          "options": {
            "outputPath": "dist/webcomponents",
            "main": "src/app/webcomponent.module.ts",
            "polyfills": "src/webcomponent.polyfills.ts",
          }
}
```

The `webcomponent.module.ts` would look like this
```
import { Injector, NgModule } from '@angular/core';
import { ButtonComponent } from './button.component';
import { createCustomElement } from '@angular/elements';

@NgModule({
  declarations: [ButtonComponent],
  exports: [ButtonComponent],
  entryComponents: [ButtonComponent]
})
export class ButtonModule {
  constructor(private injector: Injector) {
    const customButton = createCustomElement(ButtonComponent, { injector });
    customElements.define('custom-button', customButton);
  }
}
```

Hopefully `@angular/core` is not that big that it carries to much unneeded code into the bundle.

Is this the way to go? Is there anything on the roadmap to support this? I really would like to get small reusable webcomponent bundles from my project. It would be really awesome if there was any documentation on how to get this done.

**Comment by alan-agius4** [comment]
Let's close this in favor of https://github.com/angular/angular-cli/issues/19164 since there is more discussion happening over there.

Thanks.
