### ISSUE TITLE
Angular 2 app not loading main.bundle.js , inline.bundle.js, polyfills.bundle.js, styles.bundle.js, vendor.bundle.js, even after webpack compiled successfully

### ISSUE THREAD

**Issue by yogesh-sadhokar** [angular/angular-cli#8994]
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Date: 2017-12-26T04:58:28.716Z                                                           
Hash: ee3cac94a32b0ec4d2f4
Time: 41596ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 242 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 342 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 101 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.86 MB [initial] [rendered]

webpack: Compiled successfully.

For all files
The status in localhost is 
Status Code:404 Not Found

I am using ubuntu 16.04.

**Comment by yogesh-sadhokar** [comment]
Package json file

{
  "name": "dd",
  "version": "1.0.0",
  "license": "MIT",
  "main": "karma.conf.js",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.6",
    "@angular/cdk": "2.0.0-beta.10",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.2.4",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "^4.2.4",
    "@angular/material": "2.0.0-beta.10",
    "@angular/platform-browser": "4.2.4",
    "@angular/platform-browser-dynamic": "4.2.4",
    "@angular/router": "^4.2.4",
    "@cedx/ngx-webstorage": "^1.2.0",
    "angular2-cool-storage": "3.1.0",
    "angular2-focus": "1.1.0",
    "ckeditor": "4.7.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "ng2-ckeditor": "1.1.5",
    "ng2-toastr": "^4.1.2",
    "ng2-toasty": "^4.0.3",
    "ngx-perfect-scrollbar": "4.6.3",
    "rxjs": "^5.4.2",
    "tinymce": "^4.6.4",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.3.2",
    "@angular/compiler-cli": "4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
