### ISSUE TITLE
Fails to use latest version of angular

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular-cli#8996]
Why do I have to manually update NPM to use latest angular version.

I am seeing version 5.0.0 get install when 5.1.2 is available?

### Versions
Angular CLI: 1.6.2

### Repro steps

* Step 1 ng new app

Look at package.json, not current version.

### Desired behavior

Install latest version of Angular NPM modules.

**Comment by MaxGorshkov** [comment]
All works as expected
Please, see link
https://docs.npmjs.com/misc/semver
version "^5.0.0" := >=5.0.0 <6.0.0

**Comment by rajinder-yadav** [comment]
You have to be joking to point to a NPM spec.

**Comment by clydin** [comment]
As @MaxGorshkov mentioned, a newly generated app will install the latest version of Angular 5 as per the `package.json`.  The caret `^` is the critical element within the version specifier.

**Comment by rajinder-yadav** [comment]
Look at create-react-app, maybe you will get out of your darkness!
