### ISSUE TITLE
offline anuglar cli installer

### ISSUE THREAD

**Issue by noah2233** [angular/angular-cli#8998]
I am having trouble installing the angular cli from my offline station.
As you know npm install command of @angular/cli try to reach to the npm registry and the process get aborted.

Is there a simple solution??

**Comment by filipesilva** [comment]
You might be able to use NPM offline if you have proxy, but I don't have any information about how to set it up myself. The only time Angular CLI tries to use `npm install` is when you do `ng new` though, and you can do `ng new appname --skip-install` to not automatically use `npm install`.
