### ISSUE TITLE
Cross-platform end-to-end test suite

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#90]
we should create a test suite that will test basic end-to-end workflow:

- [x] run `npm install -g angular-cli`
- [x] run `ng new test-project`
- [x] cd into the project
- [x] run `ng build`
- [x] run `ng test`
- [x] run `ng generate component test-component`
- [x] run `ng test`
- [x] run `ng generate service test-service`
- [x] run `ng test`
- [x] run `ng generate pipe test-pipe`
- [x] run `ng test`

The test suite should be build in a way that allows for it to be executed across platforms (linux,osx,windows):

- [x] osx #91 
- [x] windows #92

**Comment by filipesilva** [comment]
We have all of these except the windows one now.

**Comment by hansl** [comment]
This is done with PR #275.
