### ISSUE TITLE
plans to upgrade to v3.0.0 for istanbul-instrumenter-loader ?

### ISSUE THREAD

**Issue by johnlacr** [angular/angular-cli#9002]
We recently converted our project to angular5 and the parseQuery() webpack deprecation warning is causing problems with our build. I think moving the istanbul-instrumenter-loader from version 2.0.0 => 3.0.0 would help.

**Comment by filipesilva** [comment]
Would you be interested in submitting a PR?

**Comment by filipesilva** [comment]
The files you should update are the same as the ones in https://github.com/angular/angular-cli/commit/37abd8388de91f81b336cf58a48b654a0e496355.

**Comment by johnlacr** [comment]
I'll try. I forked 1.6.3 and and trying to make the changes now (I'm new at this). I will add the file versions you mentioned to the packages.json...I only updated the version for the istanbul-instrumenter-loader.

**Comment by filipesilva** [comment]
Oh you just need to change `istanbul-instrumenter-loader` really. I used that PR as an example because it's a simple update PR. Please remember to update package-lock.json as well though!

**Comment by johnlacr** [comment]
I made the updates (including package-lock.json), but something else is wrong. I completely cleaned out my system and when I do an npm install  I am getting this:

C:\Users\Administrator>ng --version
module.js:514
    if (content.charCodeAt(0) === 35/*#*/ &&
                ^

TypeError: content.charCodeAt is not a function
    at Module._compile (module.js:514:17)
    at Object.require.extensions..ts (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@angular\cli\lib\bootstrap-local.js:25:14)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@angular\cli\packages\@angular\cli\bin\ng:8:46)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng:9:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

If I do an npm uninstall, and re-install the base version 1.6.3 code it works fine. Is it possible that moving the something else is version dependent on the Istanbul-instrumenter-loader version, and if so how to I figure out what it is?

**Comment by filipesilva** [comment]
The error you're getting is actually an unfortunate (intended) side effect of our bootstrap. It can break if you have incompatible versions of dependencies in your project and linked CLI.

You can either:
- make a custom build of the CLI via `npm run build` and install the `.tgz` in your project (instead of linking)
- comment out https://github.com/angular/angular-cli/blob/master/lib/bootstrap-local.js#L83-L88 to force the bootstrap to use the local versions (don't commit this change).

Sorry about that, it's a rather arcane problem.

**Comment by johnlacr** [comment]
Thanks for the response.

I don’t understand the problem with incompatible versions – at the moment, I have removed the node modules folder for my project (along with npm cache clean, etc.) and have only done the global install of @angular/cli from my repository. I don’t get the problem if I use version 1.6.3, again, with no local project installed.

I could potentially make the second approach (commenting out the lines) work for our CI process, but when I commented them out I got the same error (there is also the reference to line 25 of that stack dump).

Sorry for any confusion on my part.

**Comment by filipesilva** [comment]
Hm, maybe the error means something else. I'm used to it meaning different versions. Can you put up a PR with your current changes please? I'll take a look locally.

**Comment by johnlacr** [comment]
Done.

**Comment by johnlacr** [comment]
Something else must be going on - I pulled down your commit and I still get the same error when I try ng ---version. Everything works fine when I install 1.6.3.

**Comment by clydin** [comment]
The project’s package lock could have an older version of one of the loaders recorded. You can try deleting the lock file and the node modules directory and then install again.

**Comment by johnlacr** [comment]
I've deleted the lock file every time I try to re-install node_modules.

**Comment by filipesilva** [comment]
@johnlacr to get this update locally you'd have to do some acrobatics with the linked install. It should be on the next release, meanwhile the best you could do is to create a custom build via `npm run build`. You'd need to increase the `./packages/@angular/cli/package.json` versions as well, otherwise npm thinks it's the same package.

**Comment by johnlacr** [comment]
@filipesilva We have things working for now - in our CI build we can suppress stderr (it seems that actual test failures are reported on stdout) so that will hold us over until the next release. Thanks again!
