### ISSUE TITLE
network request to https://registry.npmjs.org/node-modules-path/-/node-modules-path-1.0.1.tgz failed, reason: connect ETIMEDOUT 151.101.48.162:443

### ISSUE THREAD

**Issue by samfullman** [angular/angular-cli#9004]
### Versions
node - v8.9.3
npm - v5.5.1
my machine - Max OS Sierra - 10.12.4

Running from terminal on my Mac.

### Repro steps

Type in following:
* npm install -g @angular/cli

### Observed behavior
I will go though a normal installation time period but eventually get this message:

npm ERR! network request to https://registry.npmjs.org/node-modules-path/-/node-modules-path-1.0.1.tgz failed, reason: connect ETIMEDOUT 151.101.48.162:443
* NOTE: the url might change from time to time but it's always https://registry.npmjs.org/.. etc.

### Desired behavior
I'd like to see the procuess finish and angular-cli (ng) install correctly

### Mention any other details that might be useful (optional)
I have a solid network connection (home office with reliable internet) and don't have problems like this before.

**Comment by samfullman** [comment]
NOTE!  I just ran `npm install -g @angular/cli` for the umpteenth time and this time it went all the way through - leaving this post so that perhaps it might help someone else (i.e. if a kind person posts as to why this most likely failed as well as resolved).

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
