### ISSUE TITLE
vendor.bundle.js size is around 10 MB

### ISSUE THREAD

**Issue by jayakrishna-v** [angular/angular-cli#9016]
ng -v 1.5.4
node -v 6.11.2
npm -v 3.10.10

### Observed behavior
We have an application with more than 7 modules. When we build this application we are getting vendor.bundle.js file of size 9.95 MB. This will have an impact on performance. Can someone explain the reason fro this and how to reduce the size of build files.

### Desired behavior
Expecting lesser size for bundle files

![ng build](https://user-images.githubusercontent.com/34906838/34409483-0a96e23e-ebf0-11e7-87a0-6efd8fe40e66.png)

**Comment by jgodi** [comment]
What command did you run to get these results?

`ng build` by itself does not have any optimizations. If you `ng build --help` you can see all the flags you can pass to further optimize your code and reduce the output sizes.

Try `ng build -prod -aot -vc -cc -dop --buildOptimizer` and see what your numbers are. This will enable production mode, use AOT, use a vendor chunk for third party libs, pull all common code out into a common chunk, make sure the output path is clean and lastly use the `@angular-devkit/build-optimizer` for further optimizations.

If that is still large, then do a run through in your application for third-party libraries that you are using. (1) Are you importing the entire RxJS library? (2) Moment with all localizations? etc..

**Comment by clydin** [comment]
With the latest CLI, `--prod` includes the aforementioned options with the exception of the vendor chunk option.  With AOT and the build optimizer enabled, not using a vendor chunk is typically more beneficial as it allows additional optimizations and a resulting further size reduction.

**Comment by filipesilva** [comment]
Closing as answered by @jgodi and @clydin, thanks!

**Comment by jayakrishna-v** [comment]
Thanks for the detailed explanation  @jgodi and @clydin, Thanks. I tried to run the command as mentioned but getting below error. Although the size of the bundles are too low as expected, Im trying to figure out this issue. I hope you are aware of this issue related to ngfactory. Your help in resolving this issue will be most appreciated. Thanks.

![ng build prod mode](https://user-images.githubusercontent.com/34906838/34429663-44e0dd46-ec81-11e7-9e9b-e92ee10c5f7c.png)

**Comment by jayakrishna-v** [comment]
@filipesilva @jgodi  @clydin 
I have referred to the closed issue #7925. My main.ts is already importing AppModule as mentioned by @jinder But still getting this error.

My index.ts looks as below:

import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import 'hammerjs';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));

**Comment by valentinoPereira** [comment]
jgodi saved my day!!!!!!!!!!!!!!!! 

What a solution.. Thanks man. It worked.

It got my site content from 11BMB to 1MB.. Plus using lazy loaded modules makes load faster

**Comment by ShinDarth** [comment]
I got the same issue using Angular CLI `6.1.3`. My  `vendor.js` is 7.50 MB and if I enable `--aot` it's even bigger, becoming almost 10 MB.

**Comment by danielmhair** [comment]
I understand that. And your right that the parsed size is smaller. I forgot to mention that. Thanks for reminding me, but its still about 1 MB. **Prior to Angular 6, our entire size came to 1.5 MB.** That included all of these packages (@progress, faker, @angular and everything else). I understand that faker is large and I'm working on getting that smaller, but I was focusing on @angular for this issue. It was claimed that with AOT compiling, @angular would be 250kb. I understand that I am using @angular/material and that wouldn't be considered in that size. But that means without @angular/material, the parsed size is ~600kb. That is a lot more than 250kb. We do use lazy loading, but due to the Angular 6 update, there is a bug that is forcing us out of lazy loading, but that is another issue we are planning to resolve.

But here is my main purpose: **I'm messaging in here to figure out how to lower the size to where it was before the update to Angular 6.** That's a much bigger size that it was before. All we did was update packages like rxjs and the main packages that required us to update to their Angular 6 version. Now writing this out though, I think your right, in that perhaps its @progress and faker that I need to worry about the most. I did have to update @progress to their Angular 6 package, so maybe their package increased by then.

Thanks for your info.

**Comment by danielmhair** [comment]
Yeah, for sure. Thanks for your thoughts @clydin. I'm planning to remove the locales from `faker` already. Sadly enough, I only use like four pieces of faker, which actually is about 10-30kb, so its not tree-shaking at all. I didn't realize that about oidc-client, actually. Thanks.

**Comment by danielmhair** [comment]
Actually, sorry, I think your referring to `moment`, not `oidc-client`, right?

**Comment by clydin** [comment]
oh sorry. yes.  It looked like it was inside of the `oidc-client` box.

Only code using ES2015 modules (can be ES5 with ES2015 modules) can be tree-shaken.  `import` is needed to perform the static analysis.

**Comment by MstfTkrsln** [comment]
### **Angular v6.1.10**
`ng build`

![image](https://user-images.githubusercontent.com/21102136/48781227-ae916000-ecec-11e8-9d46-e5da17685946.png)

`ng build --prod --aot `

![image](https://user-images.githubusercontent.com/21102136/48781458-1e074f80-eced-11e8-93ff-129e1a027766.png)

`ng build --prod --aot --vendor-chunk --common-chunk --delete-output-path --buildOptimizer`

![image](https://user-images.githubusercontent.com/21102136/48781429-0af47f80-eced-11e8-9883-e9de9bdd2fc1.png)

**Comment by adriangrabowski** [comment]
It works for me 

`ng build `


_chunk {main} main.js, main.js.map (main) 1.27 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 112 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) **7.86 MB** [initial] [rendered]_


`ng build --prod --aot --vendor-chunk --common-chunk --delete-output-path --buildOptimizer`

_chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} vendor.0dd2d446a7f360931d24.js (vendor) 1.63 MB [initial] [rendered]
chunk {2} styles.3555f6524ad335298167.css (styles) 76.5 kB [initial] [rendered]
chunk {3} polyfills.92108b287fe28032870b.js (polyfills) 59.6 kB [initial] [rendered]
chunk {4} main.79956f276ea8bf875884.js (main) **1.88 MB** [initial] [rendered]_

And without .js.map

**Comment by kalpeshsatasiya** [comment]
@adriangrabowski thanks, Its work for me !!

**Comment by mdufoud1214** [comment]
@jgodi @adriangrabowski  `ng build --prod --aot --vendor-chunk --common-chunk ` i did this. it reduced my dist folder size from `38mb` to `9mb` but it removed some files including map files. Not able to run application getting 404 errors (attached screenshot)

![image](https://user-images.githubusercontent.com/47215098/52058750-218d4180-258e-11e9-9620-fff504daedb8.png)

**Comment by jagdeep-anetcorp** [comment]
not working for me

**Comment by michaelmontero** [comment]
@adriangrabowski  works perfectly!!  <3

**Comment by sanmscse** [comment]
Hi ,

Can we reduce or zip Scripts bundle file 
My Script bundle is 6MB and its working fine in local
But failed to load in IIS Server deployment.

**Comment by damogallagher** [comment]
Hi

I was wondering is there any possible way for me to decrease the size of vendor.js any further?
I run this command (as referenced above)
`ng build --prod --aot --vendor-chunk --common-chunk --delete-output-path --buildOptimizer`
And the output I get is as follows
![image](https://user-images.githubusercontent.com/1813291/64063744-6cd50480-cbf0-11e9-8f84-b726b8b5ecde.png)


I am using version 8.2.2 of angular

Thanks in advance
Damien

**Comment by lbs-rodrigo** [comment]
utilize children nas suas rotas, refaça toda estrutura usando isso, irá resolver, o seu vendor.js está grande devido a quantidade de rotas iniciais que são carregadas.

**Comment by damogallagher** [comment]
I already use child routes very everything. I got vendor.js down from 15mb to 3.8
