### ISSUE TITLE
Module not found: Error: Can't resolve './app/app.module.ngfactory'

### ISSUE THREAD

**Issue by jayakrishna-v** [angular/angular-cli#9022]
This is with reference to the issues #9016 & #7925

@filipesilva @jgodi @clydin @jinder

### Versions
ng -v 1.5.4
node -v 6.11.2
npm -v 3.10.10

Thanks for the detailed explanation @jgodi and @clydin in #9016. I tried to run the command as mentioned but getting below error.  Im trying to figure out this issue. I hope you are aware of this issue related to ngfactory. Your help in resolving this issue will be most appreciated. 

![ng build prod mode](https://user-images.githubusercontent.com/34906838/34433729-35a8bbac-eca7-11e7-90be-a548f549f277.png)

I have referred to the closed issue #7925. My main.ts is already importing AppModule as mentioned by @jinder But still getting this error.

My main.ts looks as below:

import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import 'hammerjs';

if (environment.production) {
enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
.catch(err => console.log(err));

Need your help in fixing this error.

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by jayakrishna-v** [comment]
Hi @filipesilva, I tried this command on a new Angular app and it is working fine. I will try to reproduce this by adding the required code and let you know.
