### ISSUE TITLE
Prerequisite for app shell is to define a router-outlet in your root component.

### ISSUE THREAD

**Issue by Nodios** [angular/angular-cli#9024]
### Versions
```
Angular CLI: 1.6.3
Node: 8.9.3
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.5.3
webpack-dev-server: 2.9.7
webpack: 3.10.0
```

### Repro steps
I had Angular2 v5 already running but was not generated using angular-cli nor we had angular-cli so it was added later on(not by me). I want to implement AppShell(using parts from [here](https://blog.angular-university.io/angular-app-shell/)). Application tree is as follows:
```
Project +-+ app
        |   +
        |   +-+ app.module.ts
        |   |
        |   +-+ app.component.ts
        |
        +-+ main.ts
        |
        +-+ .angular-cli.json
        |
        +-+ tsconfig.json
        |
        +-+ package.json
        |
        +-+ etc.
```
What I did:
* Step 1 run command `ng generate universal my-app-app-shell` from root(Project) folder
Output:
```
 create app/app.server.module.ts (318 bytes)
 create main.server.ts (59 bytes)
 create tsconfig.server.json (308 bytes)
 update package.json (3351 bytes)
 update .angular-cli.json (1059 bytes)
 update main.ts (425 bytes)
```
* Step 2 run command `ng generate app-shell --universal-app=my-app-app-shell` (note: I also tried specifing root like: --root=. and --root=./ and --root=/)

### Observed behavior
```
Error: Prerequisite for app shell is to define a router-outlet in your root component.
Prerequisite for app shell is to define a router-outlet in your root component.
```

App component has `<router-outlet></router-outlet>` and it is wrapped in section-div-div. I tried moving it out but the same occurs.

### Desired behavior
The error should not be displayed since the router-outlet is defined. 

### Mention any other details that might be useful (optional)
I couldn't find anything regarding this issue, not even docs were helpful.

**Comment by Nodios** [comment]
Okay, I think I may have resolved it. I had an HTML template in separate .ts file and had it referenced in the app.component.ts, the whole setup was like this:

app.component.html.ts
```
export const appComponentHtml = `
<section>
    <div>
        <div>
            <router-outlet></router-outlet>
        </div>
    </div>
</section>`
```

app.component.ts
```
@Component({
    moduleId: module.id,
    selector: "my-app",
    template: appComponentHtml
})
export class AppComponent { 
// omitted code
}
```

Once I moved the HTML in the component template it worked. So from now on, I don't know if this is an expected behavior or a bug.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
