### ISSUE TITLE
Ability to create different versions of an existing component/service/pipe/directive/etc..

### ISSUE THREAD

**Issue by gh0st** [angular/angular-cli#9035]
In the tour of heroes example on angular.io they exhibit the differences made in components/services/pipes/directives by titling the respective feature hero-detail.component.v2.ts. It'd be neat if this could be available as a flag in the CLI when creating a new component.

**Comment by Brocco** [comment]
Interesting idea, something that we can consider for the future.

**Comment by alan-agius4** [comment]
Hi, 

You can use the `type` option to achieve the above.

Ex:

```
ng g c foo --type component.v2
CREATE src/app/foo/foo.component.v2.scss (0 bytes)
CREATE src/app/foo/foo.component.v2.html (18 bytes)
CREATE src/app/foo/foo.component.v2.spec.ts (626 bytes)
CREATE src/app/foo/foo.component.v2.ts (273 bytes)
UPDATE src/app/app.module.ts (562 bytes)
```
