### ISSUE TITLE
how to write app with electron

### ISSUE THREAD

**Issue by zhengw060024** [angular/angular-cli#9038]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by filipesilva** [comment]
Heya, we don't currently support anything but browser apps in Angular CLI. Hope that answers your question.

**Comment by zhengw060024** [comment]
I tried to use ng eject to make webpack.config.js file exposed and changed the target  config item to electron-render .  This just is ok for me to develop.
