### ISSUE TITLE
Feature request - ng command to import package

### ISSUE THREAD

**Issue by RobCannon** [angular/angular-cli#904]
Installing a new package from npm and changing the configuration to get a successful build is somewhat complicated.  You have to modify the angular-cli-build.js file.  You have to edit system-config.ts and/or index.html.  You might need to install Typescript file from typings.

I am suggesting that ng has a command that takes care of these changes.  It would use npm to add the package and inspect the package to determine how it need to be integrated into the build system.  The 'ng install' command is already in use for addons, but I would suggest that it be changed to support this feature and 'ng addon' be used for installing addons to angular-cli.

**Comment by filipesilva** [comment]
We actually had one at a time, but it didn't work very well so we ended up removing it. It's definitely something we have in mind to re-design though.

**Comment by filipesilva** [comment]
Made obsolete by #1455. It's now much easier to add third party libs, to the point where such a command would be unnecessary.
