### ISSUE TITLE
Would ./ as opposed to / make a sensible default for `ng build --base-href`?

### ISSUE THREAD

**Issue by rjsteinert** [angular/angular-cli#9040]
This has bit me so many times when building for things like github pages. I finally realized I could just always use `./` and not have to worry about it.  Is there a particular reason that this is not the current default? Perhaps something that is going to come back to haunt me?

**Comment by wulfsberg** [comment]
Wouldn't that mess up HTML5-style deep link/routes?

**Comment by rjsteinert** [comment]
@wulfsberg As in URLs that look like `http://localhost/client-v3/releases/pwas/baz/shell/login` which are actually `http://localhost/client-v3/releases/pwas/baz/shell/index.html#/login` under the hood? I haven't actually tried that myself.

**Comment by alan-agius4** [comment]
Indeed using `./` would break nested routes example `http://localhost/admin/login`.
