### ISSUE TITLE
How i can chose a specific version of Angular for install ? 

### ISSUE THREAD

**Issue by bezael** [angular/angular-cli#9047]
How i can chose a specific version of Angular for install, if i run 
ng new PROJECT-NAME 
I get the Angular 5.
But whatabout if i want to work with the version 2 or 4 of Angular ? 

Angular CLI: 1.6.2
Node: 8.9.1
OS: darwin x64
Angular:

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by filipesilva** [comment]
Heya, if you want to use other versions of Angular you can change the version numbers in `package.json` and run `npm install`. You might also have to change the version of TypeScript depending on the Angular version you choose.

**Comment by dawesi** [comment]
That is retarded... are the development team experienced? Why isn't this switch available?

Sencha have done this for nearly 10 years in ExtJS, it's a simple feature. Then again Sencha's tooling has always been industry-leading, most of the angular's features were copied from there also.

**Comment by ashu12318** [comment]
@filipesilva are we going to address this issue(or have already addressed) or there have been other reasons because of which you people are not willing to implement this?
Please mentioned if there is already an open issue regarding this.

**Comment by boreq** [comment]
@filipesilva Care to comment on this? Can you address the reasons for not developing those widely requested features?

**Comment by winni4eva** [comment]
@filipesilva Would be great if you guys considered this feature. I need to install angular 4 and I dont want to worry about changing dependency versions
