### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by rimlin** [angular/angular-cli#9053]
Webpack 4 alpha.2 is out (https://github.com/webpack/webpack/issues/6179) and what about migration current plugins to new Webpack 4?

- [@ngtools/webpack](https://github.com/angular/angular-cli/tree/master/packages/%40ngtools/webpack)
- [angular/cli/plugins](https://github.com/angular/angular-cli/tree/master/packages/%40angular/cli/plugins)

I will be interested to open PR.

**Comment by devoto13** [comment]
https://github.com/angular/angular-cli/pull/8611

**Comment by Toxicable** [comment]
Just a point on there, there's no way it'll be merged till at least 4.0 final is out

**Comment by filipesilva** [comment]
I'm tracking Webpack 4 support at #8611 at the moment like @devoto13 mentioned. It's still a ways off until we can merge it though... we'll need a final version (like @Toxicable said) and to make sure everything runs ok.

Closing this issue since it's being tracked in the PR above.
