### ISSUE TITLE
ng test Environment "undefined" does not exist.

### ISSUE THREAD

**Issue by samartioli** [angular/angular-cli#9057]
Upgraded to Angular 5.1.2 today as well as to Angular CLI 1.6.3

When I try and run my tests I get the error: `Environment "undefined" does not exist.`

I can get it to work by providing `-e dev`, but didn't have to before. 

### Versions
```
Angular CLI: 1.6.3
Node: 8.9.1
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.2
@angular/cli: 1.6.3
@angular/material: 5.0.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

`ng test`

### Observed behavior

`Environment "undefined" does not exist.`

If I run with `ng test -e dev` my tests run 

### Desired behavior

Should default to `dev` as it did previously.

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

It's very hard to tell what your project looks like from the information you provided... but if I had to bet it has to do with `karma.conf.js`. Using the karma config from a new project could help:
```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```

**Comment by KamelJabber** [comment]
this seems similar to https://github.com/angular/angular-cli/issues/9058

**Comment by halfbeep** [comment]
Hi Sam, I get the same issue with my project 

>ng test
Environment "undefined" does not exist. 

I've copied the following files from a newly created (boilerplate) repo where dev is accessible and the error not happening (all these files are new):-
.angular-cli.json
tsconfig.json
karma.conf.js
src/test.ts
src/main.ts

Still get the error. Filip, if I go any deeper I'm in my components, classes etc.. surely this error would be quite high in the code

**Comment by halfbeep** [comment]
filip, the bug seems to be inside @angular/cli  the following block is ignored:-

`angularCli: {
      environment: 'helloWorld'
 },`

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
