### ISSUE TITLE
Cannot create new angular app after upgrade to cli 1.6.3. 

### ISSUE THREAD

**Issue by mawglih** [angular/angular-cli#9064]
Error: Could not find an NgModule for the new component. Use the skip-import option to skip importing components in NgModule.

I still can create components and services in old applications, it only applies when i execute command ng new <my-app>

### Versions
Angular CLI: 1.6.3
Node: 9.3.0
OS: win32 x64
Angular:

### Repro steps

Error: Could not find an NgModule for the new component. Use the skip-import option to skip importing components in NgModule.
Could not find an NgModule for the new component. Use the skip-import option to skip importing components in NgModule.

**Comment by Brocco** [comment]
Please you run this command:
```
npm list -g -depth 1
```
and report back with the version of `@schematics/angular`

**Comment by mawglih** [comment]
+-- @schematics/angular@0.1.11

**Comment by mawglih** [comment]
@schematics/angular@0.1.11

**Comment by mawglih** [comment]
+--

>  @schematics/angular@0.1.11

**Comment by mawglih** [comment]
I found package lock json file and removed it. now the error changed to 

> You cannot use the new command inside an Angular CLI project.

apparently ng consider my top level directory as a angular project - how can i clean it from that? thank you for help

**Comment by mawglih** [comment]
any more ideas?

**Comment by Pinguinmann** [comment]
I'm facing the same issue on my Surface book (win 10).
I also have @schematics/angular version @0.1.11.
Does anyone know how to fix this?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
