### ISSUE TITLE
ng build -aot -prod Error on Heroku

### ISSUE THREAD

**Issue by TecBots** [angular/angular-cli#9068]
ERROR in ./src/main.ts
remote:        Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/tmp/build_77984cd222c977fc59d6b54d04a2fccc/src'
remote:        resolve './$$_gendir/app/app.module.ngfactory' in '/tmp/build_77984cd222c977fc59d6b54d04a2fccc/src'
remote:          using description file: /tmp/build_77984cd222c977fc59d6b54d04a2fccc/package.json (relative path: ./src)
remote:            Field 'browser' doesn't contain a valid alias configuration
remote:          after using description file: /tmp/build_77984cd222c977fc59d6b54d04a2fccc/package.json (relative path: ./src)
remote:            using description file: /tmp/build_77984cd222c977fc59d6b54d04a2fccc/package.json (relative path: ./src/$$_gendir/app/app.module.ng
factory)
remote:              no extension
remote:                Field 'browser' doesn't contain a valid alias configuration
remote:                /tmp/build_77984cd222c977fc59d6b54d04a2fccc/src/$$_gendir/app/app.module.ngfactory doesn't exist
remote:              .ts
remote:                Field 'browser' doesn't contain a valid alias configuration
remote:                /tmp/build_77984cd222c977fc59d6b54d04a2fccc/src/$$_gendir/app/app.module.ngfactory.ts doesn't exist
remote:              .js
remote:                Field 'browser' doesn't contain a valid alias configuration
remote:                /tmp/build_77984cd222c977fc59d6b54d04a2fccc/src/$$_gendir/app/app.module.ngfactory.js doesn't exist
remote:              as directory
remote:                /tmp/build_77984cd222c977fc59d6b54d04a2fccc/src/$$_gendir/app/app.module.ngfactory doesn't exist
remote:        [/tmp/build_77984cd222c977fc59d6b54d04a2fccc/src/$$_gendir/app/app.module.ngfactory]
remote:        [/tmp/build_77984cd222c977fc59d6b54d04a2fccc/src/$$_gendir/app/app.module.ngfactory.ts]
remote:        [/tmp/build_77984cd222c977fc59d6b54d04a2fccc/src/$$_gendir/app/app.module.ngfactory.js]
remote:        [/tmp/build_77984cd222c977fc59d6b54d04a2fccc/src/$$_gendir/app/app.module.ngfactory]
remote:         @ ./src/main.ts 3:0-74
remote:         @ multi ./src/main.ts
remote:        ERROR in Error: Child compilation failed:
remote:        Entry module not found: Error: Can't resolve '/tmp/build_77984cd222c977fc59d6b54d04a2fccc/src/app/AdminComponent/admin_panel.html' in
'/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/@angular/cli/models/webpack-configs':
remote:        Error: Can't resolve '/tmp/build_77984cd222c977fc59d6b54d04a2fccc/src/app/AdminComponent/admin_panel.html' in '/tmp/build_77984cd222c9
77fc59d6b54d04a2fccc/node_modules/@angular/cli/models/webpack-configs'
remote:            at childCompiler.compile (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/@ngtools/webpack/src/resource_loader.js:78:28)
remote:            at applyPluginsAsync.err (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/webpack/lib/Compiler.js:510:14)
remote:            at next (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/tapable/lib/Tapable.js:202:11)
remote:            at Compiler.<anonymous> (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/webpack/lib/CachePlugin.js:78:5)
remote:            at Compiler.applyPluginsAsyncSeries (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/tapable/lib/Tapable.js:206:13)
remote:            at compilation.seal.err (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/webpack/lib/Compiler.js:507:11)
remote:            at next (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/tapable/lib/Tapable.js:202:11)
remote:            at Compilation.compilation.plugin (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/@angular/cli/plugins/suppress-entry-ch
unks-webpack-plugin.js:38:17)
remote:            at Compilation.applyPluginsAsyncSeries (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/tapable/lib/Tapable.js:206:13)
remote:            at self.applyPluginsAsync.err (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/webpack/lib/Compilation.js:680:19)
remote:            at Compilation.applyPluginsAsyncSeries (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/tapable/lib/Tapable.js:195:46)
remote:            at self.applyPluginsAsync.err (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/webpack/lib/Compilation.js:671:11)
remote:            at next (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/tapable/lib/Tapable.js:202:11)
remote:            at /tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/uglifyjs-webpack-plugin/dist/index.js:257:13
remote:            at _class.runTasks (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:63:9)
remote:            at Compilation.<anonymous> (/tmp/build_77984cd222c977fc59d6b54d04a2fccc/node_modules/uglifyjs-webpack-plugin/dist/index.js:183:18

**Comment by jotatoledo** [comment]
Please use the issue template

**Comment by TecBots** [comment]
everything is running fine locally but when i try to deploy this to heroku gives me error
Field 'browser' doesn't contain a valid alias configuration
 Can't resolve './$$_gendir/app/app.module.ngfactory' 
Error: Child compilation failed
 can you please Explain these error?

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
