### ISSUE TITLE
Switch to deprecated router until new router is ready

### ISSUE THREAD

**Issue by wardbell** [angular/angular-cli#907]
The CLI and devs generally should use the deprecated router for now.

The _true_ new router is in development. The RC router (in the `@angular/router` library) is not release quality and is frozen. The _new_ new router will replace it.

This is a short term road bump.

c/ @hansl

**Comment by PascalPrecht** [comment]
I agree on this one. Played around with the current rc1 router and it has fewer features than the deprecated one.

**Comment by JSMike** [comment]
Seeing as there are many options for routers, would it be beneficial to have flags to identify which router blueprint to use? Keep the default as whatever the current @angular/router is, and add flags after that for --router-deprecated --ui-router --ngrx-router etc.?

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/992
