### ISSUE TITLE
Using @ngtools/webpack will kill the process when running in a child process 

### ISSUE THREAD

**Issue by nicojs** [angular/angular-cli#9071]
### Versions
```
ng version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.3
Node: 8.2.1
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

Run this script:

```javascript
const childProcess = require('child_process');
const isChildProcess = 'isChildProcess'
if (process.argv.indexOf(isChildProcess) >= 0) {
  require('@ngtools/webpack/src/type_checker');
  process.on('message', message => {
    console.log('received message!' + message);
    process.exit(0);
  });
  process.send('Child process alive');
} else {
  const child = childProcess.fork(__filename, [isChildProcess], { silent: false, execArgv: [] });
  child.on('message', message => {
    console.log('Received: ' + message);
    child.send('test message');
    child.removeAllListeners('message');
  });
}
```
While this is not a great example, it does illustrate the issue. If you host @ngtools/webpack in a child process you are basically not allowed to send any message without the process crashing. This is because of this line of code: https://github.com/angular/angular-cli/blob/f776d3cf7982b64734c57fe4407434e9f4ec09f7/packages/%40ngtools/webpack/src/type_checker.ts#L79

### Observed behavior

The process crashes: 

```
          throw new Error(`TypeChecker: Unexpected message received: ${message}.`);
            ^

Error: TypeChecker: Unexpected message received: test message.
    at process.on (C:\z\github\nicojs\angular-stryker-example\node_modules\@ngtools\webpack\src\type_checker.js:67:19)
    at emitTwo **(events.js:130:20)**
```

### Desired behavior
The process not crashing. Even better would be that requiring the file would not have *any* side effects. So no listening on `process.on('message', ...)`. 

### Mention any other details that might be useful (optional)

We are working on integration of angular cli projects in Stryker, the mutation testing framework. We are currently implementing a monkey patch around this problem (removing the listener for angular), but it would be nice if we can remove it in the future.

We're happy to do a PR if you can specify how you want it to be fixed. Why is that file listening to IPC messages?

**Comment by filipesilva** [comment]
`angular-cli/packages/@ngtools/webpack/src/type_checker.ts` is meant to be ran as a child, to run TS type checking in a separate process. For this reason it needs to listen to messages from the main thread to update in-memory file contents and trigger type-checking.

I'd like to help but am not really sure what you're trying to do. When is this behaviour problematic? `@ngtools/webpack` should create and manage the child process without intervention. Are you trying to communicate with the typechecker manually?

**Comment by nicojs** [comment]
> `@ngtools/webpack` should create and manage the child process without intervention.

That part probably works as expected.

The problem is with requiring the module:

```
require('@ngtools/webpack')
```

This will in turn require the `./angular_compiler_plugin` here: 
https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/index.ts#L19. This requires type_checker here: https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/angular_compiler_plugin.ts#L30

So the `process.on('message', ...)` is also called inside the main process, which is problematic for hosts are already spawned inside a child process and rely on messaging (like Stryker).

Where is this child process created? A way to prevent these undesired side effects is to pass an arbitrary uuid as argument to the child process and only if that arg is present in `process.argv` listen to messages. (that's what we use in Stryker here: https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/child-proxy/ChildProcessProxyWorker.ts#L45

**Comment by filipesilva** [comment]
This is where the type checker is initialized https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/angular_compiler_plugin.ts#L464-L513

Now that you explain it to me in detail I definitely see the problem. Yeah the main thread should not register that listener at all, but it does because of `import { InitMessage, UpdateMessage } from './type_checker';`. I wonder how it didn't cause any problems before even...

I think the real solution is to separate the type checker from the type checker worker. There should be a separate `type_checker_worker.ts` file that imports stuff from `type_checker.ts` and runs `process.on('message', (message: TypeCheckerMessage) => {` at the top level. This way the main thread doesn't register listeners.

What do you think? I'm receptive to a PR for it. You shouldn't need a test per se, there are tests right now that will fail if the type checker is not running properly.

**Comment by nicojs** [comment]
> What do you think? I'm receptive to a PR for it. You shouldn't need a test per se, there are tests right now that will fail if the type checker is not running properly.

Will do! I will try to make some time for it later this week.
