### ISSUE TITLE
Add a configuration flag to 'ng-cli' to set the default collection

### ISSUE THREAD

**Issue by Robinyo** [angular/angular-cli#9084]
### Feature Request

Add a configuration flag to`ng-cli` to set the default collection.  For example:

`ng set defaults.collection @ionic-angular/schematics --global`

Current: 
```
ng new --collection=@ionic-angular/schematics my-app --skip-install
```
Proposed:
```
ng new my-app --skip-install
```

See: [Generating and serving an Ionic project](https://github.com/Robinyo/ionic-angular-schematics#generating-and-serving-an-ionic-project)

### Mention any other details that might be useful (optional)

See: 
- [Custom Templates for Generators - Issue 6593](https://github.com/angular/angular-cli/issues/6593)
- [Schematics documentation - Issue 7627](https://github.com/angular/angular-cli/issues/7627)

**Comment by clydin** [comment]
There already is one.  Give `ng set defaults.schematics.collection @ionic-angular/schematics --global` a try.

**Comment by Robinyo** [comment]
Awesome, thanks :)

**Comment by Robinyo** [comment]
@clydin, @hansl 

BTW, I still need to work around the Schematics require.resolve [issue](https://stackoverflow.com/questions/46429693/angular-cli-custom-schematics-collection).

For example:

```
npm install @ionic-angular/schematics --global
ng set defaults.schematics.collection @ionic-angular/schematics --global
ng new my-app --skip-install
Error: Path "/README.md" does not exist.
Path "/README.md" does not exist.
```

Work around:

```
cd /usr/local/lib/node_modules/@angular/cli/node_modules
mkdir @ionic-angular
cp -R /usr/local/lib/node_modules/@ionic-angular/* @ionic-angular/
```
