### ISSUE TITLE
ng build--AOT   get error:  Unexpected value 'NgPipesModule

### ISSUE THREAD

**Issue by Jackclarify** [angular/angular-cli#9086]
### Versions
```
win10 pro
npm@5.3.0
node@8.5.0
@angular/cli@1.5.4
@angular/compiler-cli@5.0.1

Angular CLI: 1.5.4
Node: 8.5.0
OS: win32 x64
Angular: 5.0.1
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router, upgrade

@angular/animations: 4.4.6
@angular/cli: 1.5.4
@angular/platform-server: 4.4.6
@angular/tsc-wrapped: 4.4.6
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.6.1
webpack-stream: 4.0.0
webpack: 3.8.1

```

### Repro steps and error

* Step 1
Run `ng build -w -dop=false --aot`, it compiles well. But it throw error when recompiling.
Error: `ERROR in Error: Unexpected value 'NgPipesModule in C:/workspace/del/carepilot-web/node_modules/ngx-pipes/src/app/index.d.ts' imported by the module 'AppModule in C:/workspace/del/carepilot-web/client/app/app.module.ts'. Please add a @NgModule annotation.`

And it is ok when I remove the `--aot` env, can anyone give me a little hint please? Thx.
I add this env to catch all error when in building. here is the link: https://github.com/angular/angular-cli/issues/6793   @filipesilva

**Comment by filipesilva** [comment]
It sounds like the `ngx-pipes` library might have some issues or be incorrectly packaged? I can't say much more than that right now. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by Jackclarify** [comment]
here is the repro: https://github.com/Jackclarify/angular_pj, thanks for your response!

**Comment by filipesilva** [comment]
Coolio, closing as fixed then.
