### ISSUE TITLE
npm: tunneling socket could not be established / cannot download binding.node

### ISSUE THREAD

**Issue by LenkaLancaric** [angular/angular-cli#9088]
Hi,

I'm trying to install Angular by running `npm install -g @angular/cli`

I have this error:-

C:\Users<MyUsername>\AppData\Roaming\npm\ng -> C:\Users<MyUsername>\AppData\Roaming\npm\node_modules@angular\cli\bin\ng

node-sass@4.7.2 install C:\Users\lancaril\AppData\Roaming\npm\node_modules@angular\cli\node_modules\node-sass
node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-59_binding.node":

**tunneling socket could not be established, statusCode=407**

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

  export HTTP_PROXY=http://example.com:1234
or configure npm proxy via

  npm config set proxy http://example.com:8080
.
.
.
.
.

I have configured both proxy and https-proxy variables to my proxy yet the error persists.

Any ideas?

Thanks in advance

**Comment by clydin** [comment]
This appears to be a `node-sass` installation issue.  Details on some troubleshooting steps can be found here: https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md

**Comment by msqaddura** [comment]
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux_musl-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux_musl-x64-59_binding.node":

Version in screenshot below:
![image](https://user-images.githubusercontent.com/11808840/52209862-db85f580-288d-11e9-8dcc-df37e0478347.png)

Kindly note this happened after recently updating angular minorly

**Comment by ram1225** [comment]
@msqaddura hi, did you find any fix for this.. Could you please let me know

**Comment by msqaddura-ubnt** [comment]
@ram1225 
yes! i went to this list of releases https://github.com/sass/node-sass/releases
and put a version that exists for linux_musl-x64-59_binding.node, which is v4.10.0
and then added it to package.json in the dependencies (i think you can alternatively use shrinkwrap)

**Comment by msqaddura-ubnt** [comment]
@ram1225 
yes!
https://github.com/sass/node-sass/releases/tag/v4.10.0 works, i just added version `4.10.0`  to the dependencies in package.json to enforce that version (shrinkwrap might as well help)

**Comment by ram1225** [comment]
ok @msqaddura thank you. Actually the main problem is that we are trying to deploy Angular app into OpenShift. There after code being fetched from repo, while generating the build , it is throwing the above error. If you have any idea on it. Btw, i would try the v4.10.0 and check.

**Comment by msqaddura** [comment]
yes @ram1225 
the problem is depending on your container it decides which release to download, v4.10.0 has many of those. in my case i put the verbose flag to true to check the logs and it said : 
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux_musl-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux_musl-x64-59_binding.node":

after that i checked https://github.com/sass/node-sass/releases for a version that has linux_musl-x64-59_binding.node release

you can try that if v4.10.0 did not work, otherwise change container image or look for a version for your container
