### ISSUE TITLE
ngtools/webpack does not transpile ngrx/store lib into es5

### ISSUE THREAD

**Issue by vagonpidarasov** [angular/angular-cli#9090]
### Versions
```
node -v
v8.9.4

npm -v
5.6.0

Windows 7, macOS El Capitan

"@angular/cli": "1.6.3",
"@angular/common": "5.1.2",
"@angular/compiler": "5.1.2",
"@angular/compiler-cli": "5.1.2",
"@angular/core": "5.1.2",
"@angular/platform-browser": "5.1.2",
"@angular/platform-browser-dynamic": "5.1.2",
"@ngrx/core": "1.2.0",
"@ngrx/store": "4.1.1",
"webpack": "3.8.1",
"typescript": "^2.6.1",
```

### Repro steps

1. clone repo https://github.com/vagonpidarasov/ngrx-platform-issues-679
2. ```npm install```
3. _optional_ ```npm run dev```,  navigate to  ```http://127.0.0.1:8080/``` using browser 
4. ```npm run build:dev```
5. open ```dev/vendor.js``` file and search for ```'@ngrx/store/init'``` string, confirm that all es6/typescript was transpiled to es5
6. ```npm run build:prod```
7. open ```prod/vendor.js``` file and search for ```'@ngrx/store/init'``` string, locate following es6 expression ```class ActionsSubject extends __WEBPACK_IMPORTED_MODULE_1_rxjs_BehaviorSubject__["BehaviorSubject"] {``` 

### Observed behavior
ngrx/store remains es6 when ```ngtools/webpack``` loader is used.

### Desired behavior
All the code including ngrx/store should be es5 (which is done when ```awesome-typescript-loader``` is used).

### Mention any other details that might be useful (optional)

**Comment by clydin** [comment]
This line is the problem: https://github.com/vagonpidarasov/ngrx-platform-issues-679/blob/master/tsconfig.json#L17

With that line, the typescript module resolver turns `@ngrx/store` into `node_modules/@ngrx/store/store.js` which points to the es2015 sources.  It looks like ATL doesn't use typescript's module resolver which is why the behavior differs.
