### ISSUE TITLE
AOT compilation error while using ng build --prod

### ISSUE THREAD

**Issue by keshav1007** [angular/angular-cli#9095]
### Versions
node - v6.11.3
npm - 3.10.10
angular-cli - 1.6.0
angular - 5.1

### Repro steps
ng build -prod

### Observed behavior
Error: Module build failed: Error: @ngtools/webpack is being used as a loader but no `tsConfigPath` option nor AotPlugin was detected. You must provide at least one of these.

build is not successful

### Desired behavior
aot build should be successful

Note : I am not using any webpack in my project

**Comment by clydin** [comment]
Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by keshav1007** [comment]
I hope the AOT build will work if i create new project with latest angular-cli but since i have a complex project and updated the angular-cli and angular versions AOT is not working. Also this is the first time i am trying out AOT in my project.

**Comment by keshav1007** [comment]
As expected after creating a new project with latest angular-cli AOT build is working but unable to make it work in my project

**Comment by clydin** [comment]
Can you post your `package.json`?  Also it may be useful to upgrade to the latest CLI (`1.6.3`).  There may be some old package versions present as well so try removing `node_modules` and any package lock files and then npm install again.

**Comment by keshav1007** [comment]
I have cleared my node_modules folder and did cache clean and then installed the new one.. but still getting the same error:

package.json

{
    "name": "my project",
    "version": "0.8.0",
    "private": true,
    "description": "my project",
    "angular-cli": {},
    "scripts": {
        "start": "ng serve --proxy-config proxy.conf.js --env prod",
        "start.dev": "ng serve --proxy-config proxy.conf.js --env=dev",
        "build": "ng build --prod",
        "lint": "tslint \"src/**/*.ts\"",
        "pree2e": "webdriver-manager update",
        "e2e": "protractor"
    },
    "dependencies": {
        "@angular/core": "~5.1.2",
        "canvas2image-ext": "~1.1.0",
        "html2canvas-fixed": "~1.0.0",
        "moment": "2.17.1",
        "ng2-date-picker": "2.4.0",
        "rxjs": "~5.5.2"
    },
    "devDependencies": {
        "@angular/cli": "~1.6.0",
        "@types/c3": "0.4.37",
        "@types/d3-hierarchy": "~1.1.0",
        "@types/d3-interpolate": "~1.1.6",
        "@types/jasmine": "2.5.38",
        "@types/karma": "~0.13.36",
        "@types/node": "~6.0.42",
        "bootstrap": "4.0.0-alpha.5",
        "codelyzer": "~4.0.0",
        "ejs": "~2.5.7",
        "intl": "1.2.4",
        "jasmine-core": "2.5.2",
        "jasmine-spec-reporter": "2.5.0",
        "karma": "1.7.0",
        "karma-browserstack-launcher": "~1.3.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "~1.3.0",
        "karma-firefox-launcher": "~1.0.1",
        "karma-html-reporter": "~0.2.7",
        "karma-ie-launcher": "~1.0.0",
        "karma-jasmine": "~1.1.0",
        "karma-junit-reporter": "~1.2.0",
        "karma-safari-launcher": "~1.0.0",
        "karma-spec-reporter": "~0.0.31",
        "karma-webdriver-launcher": "~1.0.5",
        "nsp": "~2.6.3",
        "protractor": "~4.0.9",
        "ts-node": "~3.3.0",
        "tslint": "~5.8.0",
        "tslint-microsoft-contrib": "~5.0.1",
        "typescript": "~2.5.0",
        "zone.js": "0.8.12"
    }
}

**Comment by keshav1007** [comment]
Since i couldn't reproduce this issue with a new repo, I have not given any repro steps. Also i tried upgrading to latest cli - 1.6.3. But still i am getting the same and the weird part is , I am getting error in my scss file but the scss file doesn't have any @import statements also. Don't know what is the issue with that scss

**Comment by keshav1007** [comment]
@clydin - since i have mentioned that the issue is in scss file, do you have any idea on this?

**Comment by keshav1007** [comment]
Found the issue

I was using "background-image: none" in one of my scss file, I replaced that with "background-image: url("")" and the issue is resolved.

This may help if someone else facing the same issue
