### ISSUE TITLE
Setup OSX CI

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#91]
we should extend our `.travis.yaml` to run our tests on both linux (current) and osx.

https://docs.travis-ci.com/user/multi-os/

Once setup we should use it to run end-to-end test suite: #90

**Comment by cironunes** [comment]
https://docs.travis-ci.com/user/osx-ci-environment/

**Comment by jkuri** [comment]
I created a PR for this one, tests now passing with osx and linux configuration. 
PR: https://github.com/angular/angular-cli/pull/133

**Comment by filipesilva** [comment]
I believe this issue was closed via https://github.com/angular/angular-cli/pull/151, but if not feel free to reopen the issue.
