### ISSUE TITLE
--host * (Wildcard) or multiple hosts

### ISSUE THREAD

**Issue by BamiGorengo** [angular/angular-cli#9105]
I cant start multiple hosts or a wildcard host. i Tryed: 

```
ng serve --host one.development.test, two.development.test
ng serve --host *.development.test
```

but both just return a error:

```
getaddrinfo ENOTFOUND hellsing.animesector.test,
Error: getaddrinfo ENOTFOUND hellsing.animesector.test,
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

I want to create a bulti platform Project that listen on different Subdomains. Is there no way to do this?

**Comment by clydin** [comment]
A server listens on an IP address.  How those are mapped to host names is up to the system and DNS configuration.  This configuration is outside the purview of the CLI an is highly dependent on the individual system/OS/etc.

**Comment by BamiGorengo** [comment]
But its maybe good to talk about that, because i cant find any topic on Google where i can find any solution. I think there are maybe some more people like me they need to know, how to solve this.

I found a "ugly" solution: --disable-host-check. But there is any security problem with this: https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a

(Just if someone find this topic because he have the same problem)

**Comment by BamiGorengo** [comment]
There is no other way than that what i posted over your post.
