### ISSUE TITLE
9kb size regression in angular.io between cli 1.6.0-rc.0 and 1.6.3

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#9108]
Repro: https://github.com/angular/angular/pull/21350

cli version | build-optimizer version | main.js size in bytes
-----------|------------------------|----------------------
1.6.0-rc.0 |  0.0.31 | 457592 
1.6.3         | 0.0.36 | 466682

**Comment by FrozenPandaz** [comment]
@clydin was able to narrow it down to an update to `uglify-es` (dependency of `uglify-js-plugin`)

v3.2.2 results in a main.js of 455kb
v3.3.0 (immediate next version) results in a main.js of 466kb

corresponding commit range https://github.com/mishoo/UglifyJS2/compare/f8ff349ba7a4ded3785f79be316c16433b2dbbc7...01bb08b5535af8ed03be775650bdeb8797ce4883

**Comment by clydin** [comment]
This appears to be corrected with `uglify-es` v3.3.5.  With this version on CLI 1.6.3, the main bundle size is 453905 bytes.  This version will be installed automatically on a new CLI 1.6.3 install.

**Comment by IgorMinar** [comment]
I'll give it a shot.

**Comment by IgorMinar** [comment]
Nice! It seems that with uglify-es 3.3.5 the size of the main bundle has decreased by 11.6kb. that's great! I'll update my PR https://github.com/angular/angular/pull/21350 and rerun it on CI to confirm that this is really true.

Thanks @clydin for investigating this.

**Comment by IgorMinar** [comment]
yup. it worked. and in fact it improved the main bundle size by almost 3kb. thanks!
