### ISSUE TITLE
Missing support for ES7 Object.values in IE

### ISSUE THREAD

**Issue by markgoho-EDT** [angular/angular-cli#9111]
### Versions
```
Angular CLI: 1.6.3
Node: 8.9.3
OS: win32 x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.3
@angular/cli: 1.6.3
@angular/material: 5.0.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.5.3
webpack-bundle-analyzer: 2.9.1
webpack: 3.10.0
```

### Repro steps

* Start new application
* Use `Object.values(obj)` somewhere
* Uncomment all polyfills
* Target es5 in `tsconfig.json`
* Open up in IE 11

### Observed behavior
In IE console:
``` bash
ERROR TypeError: Object doesn't support property or method 'values'
```

### Desired behavior
We'd like the ability to use ES7 proposals in IE 11.

**Comment by clydin** [comment]
The items listed in the `polyfills.ts` file are intentionally limited to those that are required for Angular to function.  If a project requires additional capability, other polyfills (`core-js` or otherwise) may be added on a per project basis.
