### ISSUE TITLE
Feature request: Skip production build when files unchanged

### ISSUE THREAD

**Issue by karptonite** [angular/angular-cli#9112]
It would be useful for us if there were a way to conditionally build the application only if any of the sources or packages have changed since the last build.

The motivation for us is that building the application is part of our deploy step (which deploys both our front end and our back end), and right now, we are rebuilding the application (which takes nearly 10 minutes) as part of every deploy, whether it needs rebuilding or not. While I could rewrite our deploy step, this seems like a feature that would be useful to other users.

I imagine that this feature would require saving a hash representing the entire pre-compiled codebase on build, then comparing that hash before the next build. An easier but less robust solution could be as simple as comparing the last changed timestamps on all the source files to the time of the last build.

**Comment by filipesilva** [comment]
This is mostly the same request as https://github.com/angular/angular-cli/issues/7467 (a way to cache intermediate build artifacts). I agree that this is a more limited request but I think that issue captures it better, so I am closing this one as a duplicate.
