### ISSUE TITLE
Cannot install @angular/cli because of dependency issue

### ISSUE THREAD

**Issue by DirkWillem** [angular/angular-cli#9113]
When I try to install @angular/cli, I get the following error:

```
npm install -g @angular/cli@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for require-from-string@^1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dirk/.npm/_logs/2018-01-06T18_58_49_094Z-debug.log
```

### Versions

N/A

### Repro steps

Run
```
npm install @angular/cli@latest
```

### Observed behavior

Angular CLI does not install

### Desired behavior

Angular CLI installs

### Mention any other details that might be useful (optional)

The package `require-from-string` seemed to be gone from NPM for a while, but also seems to be back now

**Comment by randinterval** [comment]
@DirkWillem  Yes, It was working fine few hours ago, but broke in last few hours. I'm unable to create new project due to this:

> npm ERR! code ETARGET
npm ERR! notarget No matching version found for require-from-string@^1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/saad/.npm/_logs/2018-01-06T19_02_10_419Z-debug.log

**Comment by blackholegalaxy** [comment]
Some dependencies encountered a problem on the NPM registry, with a resulting 404 code. It should come back in a few moments.

**Comment by EstebanFuentealba** [comment]
temporal solution:
`npm install https://github.com/floatdrop/require-from-string/tarball/v1.1.0 --save`
`npm install`

**Comment by paulimfavarato** [comment]
I'm getting this issue too!

**Comment by bnymncoskuner** [comment]
@EstebanFuentealba temp solution works like a charm

**Comment by Feroz-Istar** [comment]
same issue i am facing here is post [`stackoverflow link`](https://stackoverflow.com/questions/48130877/error-installing-angular-using-npm-due-to-require-from-string?noredirect=1#comment83238842_48130877)

**Comment by kasik96** [comment]
Temp solution doesnt work when i want to install fresh -g cli:
`sudo npm install -g @angular/cli@latest`

**Comment by SameeraMadushan** [comment]
facing the same issue.. :(
even npm install doesn't work.

**Comment by patrickoliveras** [comment]
Some russian guy deleted his account on npm. There were various packages that angular, Vue.js and a whole lot of other projects that depended on his stuff.

**Comment by mcquiggd** [comment]
Yep, Vue CLI and  Create-Nuxt-App seem to have identical problem...

**Comment by paulbartocillo** [comment]
Same issue as well. Looks like it's not on angular-cli only. It's on the registry itself. :(

**Comment by ocombe** [comment]
@patrickoliveras if you delete your npm account, it shouldn't delete the npm packages

**Comment by patrickoliveras** [comment]
This is the dude, if anyone is interested in republishing the needed versions of the various packages to npm: https://github.com/floatdrop

**Comment by WahidBitar** [comment]
I just started to learn Angular 5 and reached to this issue post.
Just imagine my feelings about my learning trip ^_^

**Comment by bnymncoskuner** [comment]
@WahidBitar it is not an angular related issue. It's something with npm. Check this issue https://github.com/npm/registry/issues/255

**Comment by SameeraMadushan** [comment]
@WahidBitar I just started my final year research project. -_- how lucky i am.

**Comment by Jasnan** [comment]
It seems like `npm` is not able to find the package `require-from-string`. So I tried `yarn` and it worked.

**Comment by patrickoliveras** [comment]
@ocombe Hm. You learn a bit everyday! So maybe he just wants the world to get a bit toasty.

**Comment by WahidBitar** [comment]
@bnymncoskuner Yes I know but it was a pain in the a** till I knew it :D

**Comment by ocombe** [comment]
to delete an account from npm you have to email the npm support :-/
if they really removed his account, then they fu**** up hard!

**Comment by arianlopezc** [comment]
is like Alfred said in the Batman movie: some people just want to see the world burn

**Comment by patrickoliveras** [comment]
https://www.npmjs.com/~floatdrop
Looks like it's up, but the packages aren't there.

**Comment by cesar3030** [comment]
Same here @WahidBitar ahah
I'm trying to dockerize my MEAN Stack but it fails to build due to that issue...

**Comment by dev-talha-akbar** [comment]
So, oh this thread is new. I was curious why there's that number on the title bar! I updated npm; then reinstalled node and, it's still not working! I thought I will make a small app in Angular and learn something but, dang! Any solution yet?

**Comment by bnymncoskuner** [comment]
If you have angular-cli installed already, you can generate a new project and try the temp solution @EstebanFuentealba suggested. It is working for now.

**Comment by randinterval** [comment]
Left pad all over again.

**Comment by pwaweru-mdsol** [comment]
Temp solution does not work for create-react-app. Started a course on React today and this happens :(

**Comment by bjcCin** [comment]
NPM is broken =(((((

**Comment by krreet** [comment]
when will npm be fixed?

**Comment by bnymncoskuner** [comment]
It seems like it is back on https://www.npmjs.com/package/require-from-string

**Comment by paulbartocillo** [comment]
@EstebanFuentealba temporary solutions seems to work it breaks again after installing other new npm packages. ❤️  🗡

**Comment by dev-talha-akbar** [comment]
@bnymncoskuner I haven't. I'm new. I tried. I have installed require-from-string with --save directive but, it still throws NPM ERR! :dagger:

**Comment by arianlopezc** [comment]
It is fixed already. Go and try again. I was able to install

**Comment by svinesh3691** [comment]
@arianlopezc  I am facing the same error even now

**Comment by CArenaV** [comment]
me tooo same error @arianlopezc @svinesh3691

**Comment by paulimfavarato** [comment]
not working...

**Comment by dev-talha-akbar** [comment]
![image](https://user-images.githubusercontent.com/25082572/34643335-885e1466-f344-11e7-9cc9-eebd802e947f.png)
Nope, still error.

**Comment by bnymncoskuner** [comment]
Npm is aware of this issue and working on it, it should be fixed soon

**Comment by arianlopezc** [comment]
Something is really wrong with NPM guys. I installed and this was the message:
+ @angular/cli@1.6.3
added 177 packages, removed 55 packages, updated 98 packages and moved 8 packages in 50.173s

**Comment by bhargav1996** [comment]
https://twitter.com/npmstatus/status/949728719450460161

**Comment by svinesh3691** [comment]
Is there some ideas like, degrading to some older version of NPM ?

**Comment by BassemMamar** [comment]
@WahidBitar here we go😂😂 it's our first step upgrading our project to angular 5  💃

**Comment by patrickoliveras** [comment]
It isn't a problem with npm, it's one repository that's broken.

**Comment by patrickoliveras** [comment]
Although, the npm team is also working on this issue https://github.com/npm/npm/issues/19534#issuecomment-355770947

**Comment by tsaicharit** [comment]
use yarn

**Comment by bnymncoskuner** [comment]
I was able to install deps for a project and it seems to be working. I didn't try to re-install angular-cli tho

**Comment by nektoDev** [comment]
The only day I had time to check out new features of ng 5. Leftpad 2.0..

**Comment by hfakar** [comment]
What a lovely start for my Angular training journey :D At least I was able to find this issue thread instantly.

**Comment by patrickoliveras** [comment]
Alright NPM has issued a warning to not attempt to republish the missing packages, so hold your horses! https://github.com/npm/registry/issues/255#issuecomment-355771177

Temporal solutions are welcome though

**Comment by mikestotik** [comment]
Пипец хлопцы, и шо рабить??

**Comment by joseferrercba** [comment]
@patrickoliveras, Hi! @EstebanFuentealba published a workaround.

npm install https://github.com/floatdrop/require-from-string/tarball/v1.1.0 --save
npm install

Regards!

**Comment by keenanamigos** [comment]
@patrickoliveras have you seen any word on a timeline for the fix for this?

**Comment by mcquiggd** [comment]
It's literally 29 lines of code:

```
'use strict';

var Module = require('module');
var path = require('path');

module.exports = function requireFromString(code, filename, opts) {
	if (typeof filename === 'object') {
		opts = filename;
		filename = undefined;
	}

	opts = opts || {};
	filename = filename || '';

	opts.appendPaths = opts.appendPaths || [];
	opts.prependPaths = opts.prependPaths || [];

	if (typeof code !== 'string') {
		throw new Error('code must be a string, not ' + typeof code);
	}

	var paths = Module._nodeModulePaths(path.dirname(filename));

	var m = new Module(filename, module.parent);
	m.filename = filename;
	m.paths = [].concat(opts.prependPaths).concat(paths).concat(opts.appendPaths);
	m._compile(code, filename);

	return m.exports;
};
```

**Comment by joseferrercba** [comment]
![image](https://user-images.githubusercontent.com/14074754/34643566-02902250-f305-11e7-8870-7914b33314ab.png)

**Comment by ByMiles** [comment]
but install dont still dont works

**Comment by patrickoliveras** [comment]
@keenanamigos you can follow the incident here: https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by keenanamigos** [comment]
@patrickoliveras thank you!

**Comment by Ekta17** [comment]
temp solution is not working either

**Comment by bjcCin** [comment]
its just wait now

**Comment by joseferrercba** [comment]
yeap. now had problems with pinkie-promise@^2.0.0 package

**Comment by shubhamchandra** [comment]
not working 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for require-from-string@^1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget
from past 4 hrs at least

**Comment by IlhamWahabiGX** [comment]
@arianlopezc still unable for me

**Comment by Tameshiwari** [comment]
RE: pinkie-promise@^2.0.0 package
Yup... same here... so the whole Angular 5 CLI installation process seems pretty well broken [ not to say f****d up...] for now... so I guess we have no choice but clean up the whole mess and all unwanted leftover garbage... then go out and have a beer... then hmmm naah maybe not...  a bit too chilly up here... Brrrrrr...

**Comment by BinsGuns** [comment]
Still not working trying to install angular CLI. 
npm ERR! notarget No matching version found for require-from-string@^1.1.0
Hopefully they can fix this issue.

**Comment by gathagu354** [comment]
Getting the same error here..still waiting for the fix

**Comment by patrickoliveras** [comment]
You can use ```npm view require-from-string versions --json``` and check if version 1.1.0 is there, instead of trying to reinstall every 5 minutes. When you do eventually see 1.1.0, then we should be back on track for installing angular-cli.

**Comment by Darkensses** [comment]
you can follow this thread 
https://github.com/npm/registry/issues/255

**Comment by mcquiggd** [comment]
Progress is being made... live update:

![jenga2](https://user-images.githubusercontent.com/1839845/34643852-50b24cec-f30a-11e7-878b-e5667625f456.jpg)

**Comment by omarefg** [comment]
`$ npm view require-from-string versions --json
[
  "2.0.2"
]
`

**Comment by omarefg** [comment]
$ npm view require-from-string versions --json


[
  "2.0.2"
]

**Comment by DevAiyana** [comment]
It´s Intel! i know it

**Comment by chipatel** [comment]
Workaround: You can copy node_module from the different project.

**Comment by iamsainikhil** [comment]
You can check npm status updates here

**Comment by zxxz** [comment]
It finally worked! :-)

**Comment by gathagu354** [comment]
still having issues with require-from-string@^1.1.0

**Comment by omarefg** [comment]
Not for me :(

**Comment by leonardis** [comment]
Still the error.

**Comment by kirkdmo** [comment]
try: npm install npm@next -g , then install @angular/cli

**Comment by Darkensses** [comment]
it works right now :)

**Comment by JrFernando** [comment]
Here it came back working! :)

**Comment by Tameshiwari** [comment]
RE: Here it came back working :)
Same thing up here: It's aliiiive... It's aliiiive... Everything is back and running...  Yeeeeeeeess :)

**Comment by radoslawpl** [comment]
npm just gave everyone free Saturday evening :)

**Comment by pichardoJ** [comment]
So i think this can be closed right?
