### ISSUE TITLE
Style bundle in not adding angular cli

### ISSUE THREAD

**Issue by chamikasandamal** [angular/angular-cli#9115]
### Versions

- Node version: v8.5.0  
- Platform:  Windows  

### Repro steps

* add style to "styles" array in .angular-cli.json with SSR enabled.

### Observed behavior

"styles" array in .angular-cli.json not injecting to index.html with server side rendering. I'm using dotnet rendering engine(aspnet/JavaScriptServices#1288)

### Desired behavior
style bundle should added to output like in browser rendering bundle.

### Mention any other details that might be useful (optional)
https://github.com/angular/angular/issues/21258

**Comment by clydin** [comment]
The CLI has been updated significantly since version 1.x.  The current stable version is 8.3.5.  If this problem is still being encountered with the current version, please consider opening a new issue with updated details.
