### ISSUE TITLE
PLEASE HELP --> unable to install angular-cli ([   ...............] - fetchMetadata: sill resolveWithNewModule chokidar@1.7.0 checking installable status )

### ISSUE THREAD

**Issue by nutb0ll** [angular/angular-cli#9118]
When I try to install angular-cli --> npm install -g @angular/cli     it freezes when it comes to this 
 -->   ([   ...............] - fetchMetadata: sill resolveWithNewModule chokidar@1.7.0 checking installable status (I have waited for about 5 hours)

### Versions
OS -> Windows 10

ng --version --> 'ng' is not recognized as an internal or external command,
operable program or batch file.

npm -v --> 5.5.1

node -v --> v8.9.3

### Repro steps

I run npm install -g @angular/cli (tried with -force, as administrator, clearing cache and tried again over again

### Observed behavior

[   ...............] - fetchMetadata: sill resolveWithNewModule chokidar@1.7.0 checking installable status  --> and then nothing else happens. 

### Desired behavior

Angular installed successfully for example

**Comment by clydin** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
