### ISSUE TITLE
Cant create a project

### ISSUE THREAD

**Issue by nicolaselmir** [angular/angular-cli#912]
when i write ng new test 

it give details in the terminal but don't create the project

**Comment by neilhem** [comment]
Hi, you should give more information about your problem, angular-cli version your using, OS version & so on.

**Comment by nicolaselmir** [comment]
Im using the latest version of the cli , OSX El Capitan

I got all these:

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing ng2
  create .clang-format
  create .editorconfig
  create src/app/gametime.component.css
  create src/app/gametime.component.html
  create src/app/gametime.component.spec.ts
  create src/app/gametime.component.ts
  create src/app/environment.ts
  create src/app/index.ts
  create src/app/shared/index.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/system-config.ts
  create src/tsconfig.json
  create src/typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config/environment.dev.ts
  create config/environment.js
  create config/environment.prod.ts
  create config/karma-test-shim.js
  create config/karma.conf.js
  create config/protractor.conf.js
  create e2e/app.e2e.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create e2e/typings.d.ts
  create .gitignore
  create package.json
  create public/.npmignore
  create tslint.json
  create typings.json
Successfully initialized git.
⠴ Installing packages for tooling via npm
├── es6-shim (ambient)
├── angular-protractor (ambient dev)
├── jasmine (ambient dev)
└── selenium-webdriver (ambient dev)

Installed packages for tooling via npm.

And nothing is created

**Comment by monojack** [comment]
Everything looks fine to me, maybe, just maybe, inside your terminal, you're not in the location you think you are so the project does get generated but not where you expect it to be. Could you check that?

This happens to me sometimes, when I navigate away from the directory I usually scaffold my projects into, or am inside one of the projects... I forget that my terminal isn't pointing where it should and I'm left scratching my head for a second. :)

**Comment by nicolaselmir** [comment]
No im in the location

**Comment by neilhem** [comment]
@nicolaselmir so you have folder **test** Inside of which there is nothing?

**Comment by fatsu** [comment]
Try another name. I got something similar:

```
E:\projects\test>ng init
We currently do not support a name of `test`.
```

**Comment by thorstenschaefer** [comment]
Yes, I run into the same issue. "test" is some kind of reserved name and doesn't work. All other names should work. It's a bit unfortunate as apparently many new users try out naming their first project to play with CLI 'test'...

**Comment by jbouzekri** [comment]
Just tried a `ng new myproject` after having updated to `1.0.0-beta.5` and it errored with this message : 

```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Cannot find module 'config-chain'
Error: Cannot find module 'config-chain'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/node/5.4.0/lib/node_modules/angular-cli/node_modules/npm/lib/config/core.js:2:10)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

This is the result of `ng version` : 

```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.5
node: 5.4.0
os: linux x64
```

Any idea ?

**Comment by jbouzekri** [comment]
Ok just a case of updating with an already global install of angular-cli. Uninstall then reinstall is the key :)

**Comment by hansl** [comment]
Considering this fixed.

**Comment by jessereitsma** [comment]
```
jesse:test jesse$ ng new test
Project name "test" is not a supported name.
```

I don't get it, why am I not allowed to create a project called `test`?

**Comment by difex01** [comment]
I think is just a name convention like when a password should have more than 6 characters. 
I couldn't create a project called "app" so i had to use "apptesting" and then i renamed the folder project to "app"

**Comment by madnight** [comment]
can we reopen this issue?
