### ISSUE TITLE
Nothing happens after uninstalling old version and doing npm install -g @angular/cli@latest

### ISSUE THREAD

**Issue by EmpeRoar** [angular/angular-cli#9121]
### Versions

ng version: @latest
npm version:  5.6.0
node version: v8.9.4
Windows 10

### Repro steps
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@latest

### Observed behavior
No Error
Nothing Happens almost an hour now.

### Desired behavior
Starts download and installing

**Comment by EmpeRoar** [comment]
![image](https://user-images.githubusercontent.com/318956/34648747-15920aa4-f3db-11e7-94ba-ce83e1fdeaf9.png)

**Comment by clydin** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
