### ISSUE TITLE
Navigate to external URL using router.navigate

### ISSUE THREAD

**Issue by krischandra** [angular/angular-cli#9123]
I have a scenario where i need to apply can deactivate on component. It is working fine for internal URL. When i click on button(That navigates to external URL), I used window.open(URL) to open that URL. As a result can deactivate is not getting applied for that Button.

Is there any way i can route to external URL using route.navigate().

### Versions
```
node version: 6.1.0
NPM version: 5.6.0
Windows 10
```

### Repro steps
Click on button that navigates to external URL
this.route.navigate(URL)

### Observed behavior
Not navigating to external URL

### Desired behavior
Should go to external URL with out redirecting to dummy component.

**Comment by jotatoledo** [comment]
This is not related to the cli.

If you think this is a bug or feature request, please move this issue to the [angular issue tracker](https://github.com/angular/angular/issues)

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it does not fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on a site such as [StackOverflow](http://stackoverflow.com/).

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
