### ISSUE TITLE
Using BabelJs to transpile lib to es5

### ISSUE THREAD

**Issue by xaviergxf** [angular/angular-cli#9126]
I'm using a third party library that targets es2015 within my angular app. One of my app requirements is to run on IE 11. This third party library has some incompatible language features for IE 11:
- [Object shorthand notation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer).
I saw that BabelJS could transpile this javascript into a compatible version for ie 11. Is there any way to do this using angular cli? Are there some examples?

Thanks

### Versions
Angular CLI: 1.6.3
Node: 8.9.3
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

**Comment by clydin** [comment]
The CLI does not transpile third-party libraries.  Two potential options are to either contact the library developer and request an ES5 version; or attempt to transpile the library directly.

As this is outside of the domain of the CLI itself, asking on a site such as [StackOverflow](http://stackoverflow.com/) would be a more appropriate venue.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by xaviergxf** [comment]
Is there no way to custom module loading with angular cli? Custom options with webpack for example?

Thanks

**Comment by clydin** [comment]
You can run `ng eject` to generate a webpack configuration that can be used independently of the CLI.  Note, however, that the CLI will no longer be used from that point.
