### ISSUE TITLE
Angular ng build prerendered routes like angular universal for static serving #FeatureRequest 

### ISSUE THREAD

**Issue by manuelfink** [angular/angular-cli#9128]
### I'm submitting a Feature Request
Is it possible to build an angular app with several prerendered routes with angular-cli? 

I'm thinking of something similar to angular universal prerendering just during the angular cli build process for predefined routes but for static serving without having the overhead of setting up serverside rendering. 

Is this possible as default functionality?
Anyone else thinks this is would be handy/needed for angular-cli?

### Current behavior
seem not to be available as build option. At least I could not find it.

### Expected behavior

- add routes to prerender while building in .angular-cli.json
- on ng build create prerendered index.html files in dist folder for defined routes

For example:

```
./dist/index.html << this is default!
// Additional build prerendered index.html files for specified routes
./dist/routeA/index.html
./dist/routeB/index.html
./dist/routeC/customRouteParam/index.html
```

### Angular Universal Prerendering - Current working solution

This is already shown as an implementation within Angular Universal Starter Pack, but is not a default functionality angular-cli yet. Not sure if this works for all apps without making any consideration on universal and serverside rendering, since some implication must be made for this to work.  Details for prerendering see:

- [prerender.js](https://github.com/angular/universal-starter/blob/master/prerender.ts) for rendering
- [static.paths.ts](https://github.com/angular/universal-starter/blob/master/static.paths.ts) containing the routes to render.

### Why static prerendering of Angular?
* Allow static serving avoiding extra complexity of server-side rendering
* Keep advantages of universal app and serverside rendering
* Improving load time
* Support for Open Graph Tags (OG Tags)
* ...

I posted the [same question on stackoverflow](https://stackoverflow.com/questions/48097079/angular-ng-build-prerendered-routes-like-angular-universal-for-static-serving-w), then as [Issue in Angular repository](https://github.com/angular/angular/issues/21307) with note, that this is an angular-cli feature request.

**Comment by Toxicable** [comment]
I don't think this is the domain of the CLI.
Im working on this little tools over here https://github.com/angular/universal/pull/778 which would achieve the same goal. It would allow you to get a list of routes, then you'd be able to iterate over them producing generated routes

**Comment by filipesilva** [comment]
Closing as per the comment above.
