### ISSUE TITLE
SyntaxError: Unexpected token import on running "node server.js"

### ISSUE THREAD

**Issue by bennawanda** [angular/angular-cli#9131]
**Version**

Here is a screenshot of the versions which I have when I run `ng --version`
![screenshot from 2018-01-08 19-41-29](https://user-images.githubusercontent.com/15142609/34681177-15a3e1ee-f4ac-11e7-9ef6-20469b922afc.png)

**Repro**
When I follow the steps in using angular universal:
1. I cloned the repo.
2. I installed typings globally using npm.
3. I then ran npm install on the root directory.
4. I ran typinngs install _list of the dependencies specified_
5. I then tried running node server.js, but I get this error on doing so.

![screenshot from 2018-01-08 19-39-27](https://user-images.githubusercontent.com/15142609/34681269-67999d0e-f4ac-11e7-8322-829719486358.png)

**NB**: Please let me know any more needed information and I will provide. Thanks

**Comment by MarkPieszak** [comment]
Which repo did you clone?
I'm seeing `angular2-universal/polyfills` those are over a year old. Also it looks like you're using an old version of the CLI as well.

Take a look at `angular/universal-starter` and clone that one.

**Comment by filipesilva** [comment]
@bennawanda did following @MarkPieszak's suggestion solve your problem?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
