### ISSUE TITLE
ng serve --aot not watching for html changes with dynamic template URL

### ISSUE THREAD

**Issue by nkaredia** [angular/angular-cli#9133]
### Versions
```
Angular CLI: 1.6.3
Node: 8.9.4
OS: darwin x64
Angular: 5.1.3
```

### Repro steps

* Create new application ``` ng new testApp ```
* Navigate to ``` src/app/ ``` and create new folders  ``` mkdir templates && mkdir templates/brand1 && templates/brand2```
* Copy ``` app.component.html ``` to ``` templates/brand1 ```
* Change your ``` environment.ts ``` 
```
export const environment = {
  production: false,
  brand: 'brand1'
};
```
* Import ``` environment ``` in ``` app.component.ts ```
* Change templateUrl as follows:
```
@Component({
  selector: 'app-root',
  templateUrl: './templates/' + environment.brand + '/app.component.html'
})
```
* Serve ``` ng serve --aot ```
* Make changes to ``` app.component.html ``` and observe terminal and browser

### Observed behavior
* Component loads during initial build
* However, after making some changes in HTML, Cli was not able to watch and rebuild HTML changes.
* Though this was not the case with ``` .scss ``` files, with similar configuration .scss files were getting watched and rebuild properly.

### Desired behavior
Cli should watch for HTML changes with dynamic template url using AOT enabled.

**Comment by nkaredia** [comment]
This is also affecting ng test, e2e , and ng serve giving errors like 

ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve ' './templates/' + environment.brand + '/app.component.html'' in 'C:\workspace\app\src\app'
 @ ./src/app/app.component.ts 32:22-92
 @ ./src/app/app.component.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

Only AOT is working

**Comment by hansl** [comment]
This should have been fixed a long time ago. If this still happens please create a new issue so we can follow up.
