### ISSUE TITLE
ngnix.conf file does not get exported to dist folder during build

### ISSUE THREAD

**Issue by asapkota333** [angular/angular-cli#9134]
### Versions
```
npm version --> 3.10.7
angular-cli: 1.0.0-beta.28.3
node: 6.11.4
os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.0.4
@angular/compiler-cli: 4.3.6
```

### Repro steps
1. put ngnix.conf file in src folder in angular  4 project

2. add ngnix.conf file in  assets inside angular-cli.json file

"apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico",
        "ngnix.conf"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "",
      "styles": [
        "styles/connect-bootstrap.scss",
        "styles/app.scss"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],

3. execute build command
4. check dist folder

### Observed behavior
```
ngnix.conf file does not get copied to dist folder during build
```

### Desired behavior
ngnix.conf should be copied to dist folder

**Comment by clydin** [comment]
The version of the CLI being used is an early 1.0 beta and no longer supported.  Please update to the latest stable version of the CLI (currently 1.6.3).  If this problem still persists, please re-open the issue.
