### ISSUE TITLE
"ng serve --prod --build-optimizer" live-reloads cause Javascript error in browsers

### ISSUE THREAD

**Issue by dizzy721** [angular/angular-cli#9135]
### Versions
```
Angular CLI: 1.6.3
Node: 8.9.3
OS: win32 x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
* `ng new repro-app`
* `ng serve --prod --build-optimizer`
* Add css to styles.css in VS Code and save. 
* While the project is rebuilding, also change and save index.html.
* Inspect browser console for error output
* Subsequent rebuilds still throw the error even if only changing one file at a time. 

### Observed behavior
The first build is served with no issue. The third build generates an error, which is below. 
**CLI Output**
```
 ng serve --prod --build-optimizer
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-01-08T21:34:33.896Z
Hash: dcf6fdafe5526d65c989
Time: 19290ms
chunk {0} polyfills.61df7d7ec492d95bb0b2.bundle.js (polyfills) 61.2 kB [initial] [rendered]
chunk {1} main.da0014a7afa74a009599.bundle.js (main) 293 kB [initial] [rendered]
chunk {2} styles.7603117359b5a8dffd89.bundle.css (styles) 105 bytes [initial] [rendered]
chunk {3} inline.d3c0cf3dc365c4d3fdfc.bundle.js (inline) 1.45 kB [entry] [rendered]

webpack: Compiled successfully.
webpack: Compiling...
Date: 2018-01-08T21:34:55.521Z
Hash: e1d88d3cedb984919ba1
Time: 13195ms
chunk {0} polyfills.61df7d7ec492d95bb0b2.bundle.js (polyfills) 61.3 kB [initial]
chunk {1} main.da0014a7afa74a009599.bundle.js (main) 293 kB [initial]
chunk {2} styles.8b89660c6d7db7fd0150.bundle.css (styles) 106 bytes [initial]
chunk {3} inline.d3c0cf3dc365c4d3fdfc.bundle.js (inline) 1.45 kB [entry]

webpack: Compiled successfully.
webpack: Compiling...
webpack: wait until bundle finished: /dashboard
webpack: wait until bundle finished: /dashboard
Date: 2018-01-08T21:35:08.411Z
Hash: 765ff0a403db99858e58
Time: 12637ms
chunk {0} polyfills.61df7d7ec492d95bb0b2.bundle.js (polyfills) 61.3 kB [initial]
chunk {1} main.29d5d263a9d4e91c64ff.bundle.js (main) 280 kB [initial] [rendered]
chunk {2} styles.8b89660c6d7db7fd0150.bundle.css (styles) 106 bytes [initial]
chunk {3} inline.c6299d98af44410d31e7.bundle.js (inline) 1.45 kB [entry] [rendered]

webpack: Compiled successfully.
```
**Browser Console Stack Trace**
```
Uncaught TypeError: (void 0) is not a function
    at Object.cDNt (main.2d2b3f0de20dee881539.bundle.js:1)
    at o (inline.a443620b1a7e83c745b9.bundle.js:1)
    at Object.0 (main.2d2b3f0de20dee881539.bundle.js:1)
    at o (inline.a443620b1a7e83c745b9.bundle.js:1)
    at window.webpackJsonp (inline.a443620b1a7e83c745b9.bundle.js:1)
    at main.2d2b3f0de20dee881539.bundle.js:1
cDNt @ main.2d2b3f0de20dee881539.bundle.js:1
o @ inline.a443620b1a7e83c745b9.bundle.js:1
0 @ main.2d2b3f0de20dee881539.bundle.js:1
o @ inline.a443620b1a7e83c745b9.bundle.js:1
window.webpackJsonp @ inline.a443620b1a7e83c745b9.bundle.js:1
(anonymous) @ main.2d2b3f0de20dee881539.bundle.js:1
```

### Desired behavior
The rebuilt webapp should be served on every rebuild.

**Comment by Taha-Di-Nero** [comment]
@filipesilva Setting --build-optimizer a false and comparing after the first main......bundle.js and the rebuild one I discovered that the only interesting diff is:
first build:

> Object(_._1)(), **M.i()**.bootstrapModuleFactory(I).catch(function(l) { 

rebuild:

> Object(_._1)(), **(void 0)()**.bootstrapModuleFactory(I).catch(function(l) {

Replacing **(void 0)()** by **o.i()** everything works.
If you tell me where to look in the code I could make a PR.

**Comment by Taha-Di-Nero** [comment]
I don't think it is a bug in Build Optimizer that the error persist even when --build-optimizer is false.
May be it is related to Uglify that I have replaced -- prod by setting all Angular cli flags as they would be when using that meta flag and everything works fine.

**Comment by Taha-Di-Nero** [comment]
@filipesilva Disabling uglify webpack pluging(Build Optimizer disabled)  and comparing the first main......bundle.js and the rebuild one I discovered that the following line changed:
first build:

> platform_browser["i" /* platformBrowser */]().bootstrapModuleFactory(AppModuleNgFactory)

Rebuild:

> /* Cannot get final name for export "platformBrowser" in "C:/Users/dnrtha/Desktop/frontend/src/app/app.component.ngfactory.js" (known exports: RenderType_AppComponent View_AppComponent_0 View_AppComponent_Host_0 AppComponentNgFactory, known reexports: ) */ **undefined()**.bootstrapModuleFactory(AppModuleNgFactory)

As you can see there is an 'undefined()' which will be interpreted by uglify to '(void 0)()'.
So I think that we could exclude uglify and build optimizer.

**Comment by filipesilva** [comment]
@Taha-Di-Nero nice investigative work you've done there! 

From your results I think there must be a problem somewhere if `platformBrowser` gets interpreted to `undefined`. But the solution cannot be to remove `webpack.optimize.ModuleConcatenationPlugin(), ` since that is an important part of the optimization strategy.

I wouldn't be too surprised if it is a bug in `ModuleConcatenationPlugin` tough. It might be that it just isn't working well with rebuilds. We're getting really close to Webpack 4 betas (https://github.com/angular/angular-cli/pull/8611) so that might fix it.

I tried with that PR and it seems fixed. So I think you're right, it is a bug in `ModuleConcatenationPlugin` rebuilds that is fixed in Webpack 4.

**Comment by MiraYuan** [comment]
any progress now?
I meet this problem too...and set "sourceMap" as true to debug it, it show this error"TypeError: (void 0) is not a function" in " observers.es5.js.pre-build-optimizer.js:38:47".

error generated in the last second line code.
    MutationObserverFactory.prototype.create = /**
     * @param {?} callback
     * @return {?}
     */
    function (callback) {
        return typeof MutationObserver === 'undefined' ? null : new MutationObserver(callback);
    };
    MutationObserverFactory.decorators = [
        { type: Injectable, args: [{ providedIn: 'root' },] },
    ];
    **/** @nocollapse */ MutationObserverFactory.ngInjectableDef = ɵɵdefineInjectable({ factory: function MutationObserverFactory_Factory() { return new MutationObserverFactory(); }, token: MutationObserverFactory, providedIn: "root" });**
    return MutationObserverFactory;
}());

**Comment by MiraYuan** [comment]
As it is something different as this problem, I open another issue #14384

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
