### ISSUE TITLE
Enable a custom broccoli plugin

### ISSUE THREAD

**Issue by jbouzekri** [angular/angular-cli#914]
Sorry if it is not the right place to post it. This is a Help-wanted kind of issue.

I would like to add a custom command which uses a custom broccoli plugin. How can I go about it ?

Thanks in advance

**Comment by hansl** [comment]
You're returning a Broccoli plugin from `angular-cli-build.js`. You can use your plugin there, either as input to Angular2App, or as return of the default function.
