### ISSUE TITLE
Asynchronous Routing,  module missing from TS compilation

### ISSUE THREAD

**Issue by squarebraket** [angular/angular-cli#9142]
### Versions
```
Angular CLI: 1.6.3
Node: 8.6.0
OS: darwin x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack-merge: 4.1.1
webpack: 3.10.0

MacOs High Sierra - 10.13.2
```

### Repro steps
* The Asynchronous Routing Documentation (https://angular.io/guide/router#milestone-6-asynchronous-routing), states that a `module` that's going to be loaded "lazily" should be removed from the `app.module.ts`:
 ```
In app.module.ts, remove the AdminModule import statement 
from the top of the file and remove the AdminModule from the 
NgModule's imports array.
```

### Observed behavior
When I follow what the documentation states, and then I try  to do `ng server` or `ng build`, I get the following error:
```
Module build failed: Error: /../../my-module-name-here.module.ts is missing from the TypeScript compilation. 
Please make sure it is in your tsconfig via the 'files' or 'include' property.
at AngularCompilerPlugin.getCompiledFile (/../../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:653:23)
    at plugin.done.then (/../../node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

```

The documentation doesn't mentioned anything else regarding adding the module to any config file, etc.

I'v also noticed that if I keep the `import` in `app.module.ts` but don't include my module in `imports` it solves the problem.

Could you please tell me if I'm missing something?
Thanks for your help

**Comment by filipesilva** [comment]
Heya, can you show me your `src/tsconfig.app.json` please? The error is usually accurate as to files missing from the compilation.

**Comment by squarebraket** [comment]
Here it is:
```
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2016", "dom", "es2017.object" ],
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "../out-tsc/app",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [ "node_modules/@types" ],
    "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ],
      "primeng": [
        "../node_modules/primeng"
      ],
      "@sni/sui/*": [
        "../node_modules/@sni/sui/*"
      ]
    }
  },
  "include": [
    "../src/*",
    "../node_modules/@sni/sui/*"
  ],
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

**Comment by filipesilva** [comment]
Hm, I'm not too sure about the structure of your project, but is `my-module-name-here.module.ts` included in the paths inside the `include` array? If not, can you add the path there?

**Comment by squarebraket** [comment]
No is not, the documentation doesn't call for that, should it be included in `include`?

**Comment by filipesilva** [comment]
I think that it isn't terribly obvious but it's just part of how TypeScript works in general (https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#details).

A `tsconfig` file by default includes everything in that directory and down, and then you can use `files`, `include` or `exclude` to customize it a bit more. If you're using a file that isn't part of the TS compilation, you get the error you see in Angular CLI. That error isn't part of TypeScript per se though, but rather part of the bundling and defined by us.

Is the module you're trying to load in `../src/*`? Maybe you need the double star there to include all subdirectories as well (`../src/**/*`).

**Comment by squarebraket** [comment]
The module we're trying to load is a few folders below `src/app`. Let me try your "double star" suggestion to see if makes a difference.

**Comment by squarebraket** [comment]
@filipesilva, your suggestion worked! Using "double start" fixed the problem.

Thanks so much! I really appreciate it.

**Comment by filipesilva** [comment]
Coolio, glad to hear it!

What happens with TS is this: whenever it finds a file in the compilation, that file and all the others it imports will be part of the compilation. But with lazy routes, there is no direct import, so it's essentially another 'entry point' like `main.ts`.

`../src/*` did not use double star so only files there were included. I suppose you had `../src/main.ts` there, so that file and all that it imports were included. But the lazy module was not matched by `../src/*` and not imported. But when you changed to `../src/**/*` it matched the lazy module. So everything compiled right.

I'll close as it seems sorted.

**Comment by wellmmeR** [comment]
Plisss...I had the same problem here, but the solution above didn't work with me... I put those "double stars" and nothing... Idk what to do anymore!

**Comment by wellmmeR** [comment]
Well, i had to delete that file and recreate it again with other name... So, it works fine! What a heck... haha

**Comment by lennartboeckx** [comment]
Ran into the same problem.
Fixed it by checking the casing where I imported the file.

**Comment by pratikthecook** [comment]
I am facing the same issue, only difference is that my package name doesnt begin with '@visual-designer' instead its 'visual-designer'. Ive asked for help on Stackoverflow too [Link](https://stackoverflow.com/questions/48768134/cannot-lazy-load-module-from-node-modules-packages)

following is my tsconfig.app.json
```

{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": [],
    "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ],
      "visual-designer": [
        "../node_modules/visual-designer/*"
      ]
    }
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ],
  "include": [
    "../src/**/*",
    "../node_modules/visual-designer/*"
  ]
}
```

**Comment by klaascuvelier** [comment]
I have a similar issue as well, `include` and `exclude` path seem to work fine.
`ng build` works with Typescript 2.4.2, but not 2.5.0. When using 2.5.0 I get an error about a file not being found as well. I tried renaming, but no avail.

The interesting thing is, that building with `--prod` does work without complaining ...

``` package.json
...
  "scripts": {
    "build": "ng build",
    "build-prod": "ng build --prod --sourcemaps true",
...
```

```tsconfig.app.json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "baseUrl": "",
    "types": ["node"]
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
``` 
and the main `tsconfig` has `include: "./src/**/*.*"

**Comment by SURESHA2** [comment]
Hi Suresh here getting this type of  error in console see given below.
if any budy know the solution please reply?
//////////////////////////////////////////////////////////////////////////////////
Module build failed: Error: D:\form\src\app\service.service.ts is missing from t
he TypeScript compilation. Please make sure it is in your tsconfig via the 'file
s' or 'include' property.
