### ISSUE TITLE
Request to remove bold font in error messages

### ISSUE THREAD

**Issue by dman777** [angular/angular-cli#9144]
Request feature:

Configuration to adjust font or remove bold face font in error message. 

On LCD screens in Linux, the red bold font is fuzzy/less sharp and hard to read in error messages. This is a request for that to be configurable or changed not to use bold font.

```
webpack: Compiled successfully.
webpack: Compiling...
 10% building modules 0/1 modules 1 active ...diabetes-charts/src/app/app.module.tsERROR in src/app/line-chart-helper.service.ts(5,3): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
src/app/line-chart-helper.service.ts(51,1): error TS1128: Declaration or statement expected.
src/app/line-chart.service.ts(9,3): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
src/app/line-chart.service.ts(107,1): error TS1128: Declaration or statement expected. 
```

**Comment by clydin** [comment]
Color can be disabled by using the `NO_COLOR` or `FORCE_COLOR` environment variables (https://nodejs.org/api/tty.html#tty_writestream_getcolordepth_env).
These error message formats originate from third-party dependencies (Webpack, TypeScript, etc.) and cannot be easily customized on an individual level.
Many terminals also offer the option to remap colors and this could be an option to resolve the issue.  There may also be configuration potential from a OS perspective to improve the clarity of the terminal output but this would most likely be system dependent and outside the scope of the Angular CLI.

**Comment by dman777** [comment]
@clydin  thank you for the suggestion. Is it possible to keep the colors but remove the bold? Red bold isn't as sharp and defined...making the font hard to read(at least on linux systems where fonts are diff than windows).
