### ISSUE TITLE
How to add source folder to chrome devtools workspace? 

### ISSUE THREAD

**Issue by glebmachine** [angular/angular-cli#9145]
### Versions
```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.1
Node: 6.9.2
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Observed behavior
There is no option to apply sourcemaps to local workspace folder and edit right from devtools

### Desired behavior
I'd like to be able to edit code right from chrome devtools sourcemap explorer

**Comment by hansl** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by glebmachine** [comment]
Thank you!
-- 
Gleb Mikheev
CTO

*Beta Digital Production*
Bersenevsky Lane 5 Building 1

Mobile:  +7 (916) 118-28-21
Telegram: https://t.me/glebmikheev

www.betaagency.ru
www.facebook.com/betadigitalproduction
