### ISSUE TITLE
When is next @angular/cli to be released?

### ISSUE THREAD

**Issue by SamuelMarks** [angular/angular-cli#9148]
[Waiting for the postcss](https://github.com/angular/angular-cli/issues/9029) update that has already been [merged in](https://github.com/angular/angular-cli/pull/9023).

Looks like there was an update about every week:
https://github.com/angular/angular-cli/releases

But it's been almost 2 weeks now. Any idea when you're going to release the next version?

**Comment by clydin** [comment]
1.6.4 is now out.  Release notes are here: https://github.com/angular/angular-cli/releases/tag/v1.6.4
