### ISSUE TITLE
Karma configuration not taken into account

### ISSUE THREAD

**Issue by ghost** [angular/angular-cli#9153]
### Versions

```
Angular CLI: 1.6.1
Node: 8.9.1
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.1
@angular/cli: 1.6.1
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material-moment-adapter: 5.0.1
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

* **Step 1** Create a new project
* **Step 2** add some properties to the `karma.conf.js` file (see which ones in the *other details* part)

### Observed behavior

When I disable logs from the browser into karma, karma just ignores it and display them anyway. I believe this is because its configuration is overriden ? 

### Desired behavior

I would like to not see the browser logs into my console when I ask not to see them

### Mention any other details that might be useful (optional)

In my `karma.conf.js` I added those properties : 

    client: {
      captureConsole: false,
      clearContext: false
    },
    logLevel: config.LOG_DISABLE,
    browserConsoleLogOptions: {
      level: 'disable',
      terminal: false
    },

But no matter what I do, my console output looks like this (sample) : 

    Error: Template parse errors:
      'mat-dialog-content' is not a known element:
        1. If 'mat-dialog-content' is an Angular component, then verify that it is part of this module.
        2. If 'mat-dialog-content' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<h3 mat-dialg-title style="margin: 12px 0">Confirmation d'action</h3>
    [ERROR ->]<mat-dialog-content>
      <div fxLayout="row" fxLayoutAlign="start center" fxFlex style="margin: 24px 0""): ng:///DynamicTestModule/ConfirmationDialogComponent.html@1:0
      Can't bind to 'mat-dialog-close' since it isn't a known property of 'button'. (" fxFlex fxLayout="row" fxLayoutAlign="end center" fxLayoutGap="12px">
        <button mat-raised-button [ERROR ->][mat-dialog-close]="false">Annuler</button>
        <button mat-raised-button color="primary" [mat-dialog"): ng:///DynamicTestModule/ConfirmationDialogComponent.html@8:30
      Can't bind to 'mat-dialog-close' since it isn't a known property of 'button'. ("ed-button [mat-dialog-close]="false">Annuler</button>
        <button mat-raised-button color="primary" [ERROR ->][mat-dialog-close]="true">Confirmer</button></div></mat-dialog-actions>"): ng:///DynamicTestModule/ConfirmationDialogComponent.html@9:46
      'mat-dialog-actions' is not a known element:
        1. If 'mat-dialog-actions' is an Angular component, then verify that it is part of this module.
        2. If 'mat-dialog-actions' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by dgp1130** [comment]
I took a quick look at this as we're triaging all our issues. I'm not able to reproduce this particular problem. I made a new repo with `ng new` and added `<mat-dialog-content>` to a template without importing it to simulate the same error you got. Running `ng test` shows:

```
$ ng test
Chrome 83.0.4103.61 (Linux x86_64): Executed 2 of 2 SUCCESS (0.074 secs / 0.055 secs)
TOTAL: 2 SUCCESS
TOTAL: 2 SUCCESS
WARN: ''mat-dialog-content' is not a known element:
1. If 'mat-dialog-content' is an Angular component, then verify that it is part of this module.
2. If 'mat-dialog-content' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
Chrome 83.0.4103.61 (Linux x86_64): Executed 0 of 2 SUCCESS (0 secs / 0 secs)
WARN: ''mat-dialog-content' is not a known element:
1. If 'mat-dialog-content' is an Angular component, then verify that it is part of this module.
WARN: ''mat-dialog-content' is not a known element:
1. If 'mat-dialog-content' is an Angular component, then verify that it is part of this module.
2. If 'mat-dialog-content' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
Chrome 83.0.4103.61 (Linux x86_64): Executed 1 of 2 SUCCESS (0 secs / 0.057 secs)
WARN: ''mat-dialog-content' is not a known element:
1. If 'mat-dialog-content' is an Angular component, then verify that it is part of this module.
```

I then updated my `karma.conf.js` with the values you mentioned (and removed the existing values for those properties). Restarting Karma then passes the test without displaying any warnings:

```
$ ng test
Chrome 83.0.4103.61 (Linux x86_64): Executed 2 of 2 SUCCESS (0.116 secs / 0.068 secs)
TOTAL: 2 SUCCESS
TOTAL: 2 SUCCESS
```

Since this is quite an old issue it may have been fixed at some point. If you're still able to reproduce the problem on latest Angular CLI, let me know with a minimal reproduction and we can re-open this issue to investigate further.

My full `karma.conf.js`:

```javascript
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      captureConsole: false,
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    browserConsoleLogOptions: {
      level: 'disable',
      terminal: false
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, './coverage/fixit-test'),
      reports: ['html', 'lcovonly', 'text-summary'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_DISABLE,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    restartOnFileChange: true
  });
};
```

```
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.7
Node: 12.16.1
OS: linux x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cli                      9.1.7
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```
