### ISSUE TITLE
Blueprints

### ISSUE THREAD

**Issue by deebloo** [angular/angular-cli#916]
one of the best features of Ember-cli is the customizable blueprints. Is there a reason we are blocking those blueprint generators from running here? When things like formatting come up and say I don't like the multiline imports for the testing library I don't want to manually update that every time.

**Comment by hansl** [comment]
We're still studying how we will approach customizing and addons. Whether it's ember-cli addons or something else, we don't know yet.

**Comment by deebloo** [comment]
that works. was just curious.
