### ISSUE TITLE
Warning when using Angular 5.2 with TypeScript 2.6

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#9162]
## I'm submitting a...

<pre><code>
[X] Bug report  

</code></pre>

## Current behavior
`ng serve` with TypeScript 2.6 and Angular 5.2 warns with:

```@angular/compiler-cli@5.2.0 requires typescript@'>=2.4.2 <2.6.0' but 2.6.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.4.2 <2.6.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".
```

## Expected behavior
No warning

## Minimal reproduction of the problem with instructions
`ng new my-project`
Update to TypeScript@latest and angular@latest
`ng serve`

## Environment

<pre><code>
Angular CLI: 1.6.3
Node: 8.4.0
OS: linux x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cdk: 5.0.4
@angular/cli: 1.6.3
@angular/material: 5.0.4
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
typescript: 2.6.2
webpack: 3.10.0
</code></pre>

**Comment by Toxicable** [comment]
fixed by https://github.com/angular/angular-cli/pull/9097
We should really try to be more proactive about these changes

**Comment by deiyanfott** [comment]
ng serve for 5.2.10 shows warning for typescript 2.7.2 and up.
I am current using typescript 2.8.3.

**Comment by Janatbek** [comment]
@deiyanfott still using with warnings or you downgraded typescript?

**Comment by deiyanfott** [comment]
@Janatbek reverted back to 2.6.2 for now. I guess this will be fixed in Angular 6.
