### ISSUE TITLE
使用@angular/cli  使用 ng build --prod 打包后生成的文件hash 值不对

### ISSUE THREAD

**Issue by yushk** [angular/angular-cli#9165]
### Versions
```
Angular CLI: 1.5.0
Node: 8.9.1
OS: linux x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps

* Step 1
ng build --prod
* Step 2
每次生成的文件名都相同，hash没有生效
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by intellix** [comment]
Google translate basically says that after an `ng build`, the generated hash values are incorrect

**Comment by StephenFluin** [comment]
@asnowwolf My Chinese isn't very good. Can you help us understand or respond to this issue?

**Comment by asnowwolf** [comment]
@StephenFluin @intellix 
His description of the problem is not detailed enough. I would like to investigate with him in Chinese first and then translate the conclusion into English.

@yushk 你能做一个能复现此问题的最小化工程，上传到 github 的一个开放仓库中吗？另外，你所说的没生效是指没有添加 hash 还是指添加了但每次添加的 hash 都一样？在你没有改动源代码的情况下，每次 build 的 hash 就应该是一样的，这本来就是设计意图。
另外，如果用中文提 issue，请直接 @我，这样就不会给其他成员造成困扰了。

**Comment by intellix** [comment]
Hashing plugin used here (sha-384): https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/models/webpack-configs/browser.ts#L75

Hashing done here: https://github.com/waysact/webpack-subresource-integrity/blob/master/index.js#L175

Are those hashes correct? I'm not sure how to verify the integrity of my bundles to be honest

**Comment by zuo305** [comment]
@asnowwolf hi, you are very friendly. I have a very strange problem. Can I ask you by some other way. After I update to the latest version of Angular CLI. Every time I build need 40 minutes.

**Comment by asnowwolf** [comment]
@zuo305 Yes, if you speak Chinese too, please add my wechat: asnowwolf .

**Comment by yuechong** [comment]
package.js自己加参数  --output-hashing=bundles
demo：
 "build": "node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --aot -prod --output-hashing=bundles --base-href /v2/",
