### ISSUE TITLE
Error: Can't resolve all parameters for FocusTrapFactory:

### ISSUE THREAD

**Issue by eldhoabe** [angular/angular-cli#9167]
I have angular CLI project which i trying to start with Visual studio 2017 angular template.
The compiler using in AOT compiler.

The project is working fine in visual studio code when using "ng serve" with JIT compiler. Also it works with -AOT with some warning from vs code.

The same source code is not working with setup of visual studio 2017.
Throwing 
`: Can't resolve all parameters for FocusTrapFactory: ([object Object], [object Object], ?). Error: Can't resolve all parameters for FocusTrapFactory: ([object Object], [object Object], ?). at syntaxError (C:\Users\eab\source\repos\Logisoft.Web\Logisoft.Web\ClientApp\dist\vendor.js:37092:34) at `

Versions
```
{
  "dependencies": {
    "@angular/animations": "^4.3.4",
    "@angular/cdk": "^5.0.0-rc0",
    "@angular/common": "^4.3.4",
    "@angular/compiler": "^4.3.4",
    "@angular/compiler-cli": "^4.3.4",
    "@angular/core": "^4.3.4",
    "@angular/forms": "^4.3.4",
    "@angular/http": "^4.3.4",
    "@angular/material": "^5.0.0-rc0",
    "@angular/platform-browser": "^4.3.4",
    "@angular/platform-browser-dynamic": "^4.3.4",
    "@angular/platform-server": "^4.3.4",
    "@angular/router": "^4.3.4",
    "@ngtools/webpack": "1.5.0",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "^5.5.2",
    "style-loader": "0.18.2",
    "systemjs": "^0.20.19",
    "to-string-loader": "1.1.5",
    "typescript": "2.6.1",
    "url-loader": "0.5.9",
    "webpack": "2.5.1",
    "webpack-hot-middleware": "2.18.2",
    "webpack-merge": "4.1.0",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@types/chai": "4.0.1",
    "@types/jasmine": "2.5.53",
    "chai": "4.0.2",
    "jasmine-core": "2.6.4",
    "karma": "1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-webpack": "2.0.3"
  },
  "name": "LogisoftWeb",
  "private": true,
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js"
  },
```
  "version": "0.0.0"

### Repro steps
 Run the angular cli project with visual studio 2017. It doesn't compile

### Observed behavior
Throws exception : Can't resolve all parameters for FocusTrapFactory 
### Desired behavior
 Should work fine.

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it does not fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on a site such as [StackOverflow](http://stackoverflow.com/).

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
