### ISSUE TITLE
The Angular CLI is no longer working after update

### ISSUE THREAD

**Issue by JoshuaAdamYoung** [angular/angular-cli#9172]
The Angular CLI is no longer working after update

### Versions
```

Angular CLI: 1.6.4
Node: 8.0.0
OS: linux ia32 (Lubuntu 17.04)
Angular: 
...


```

### Repro steps
...

* Step 1
ng new <projectname>

...

### Observed behavior
```

Error: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

```

### Desired behavior
To create a new Angular project

### Mention any other details that might be useful (optional)

It was working up until I updated the angular CLI with npm i -g @angular/cli

**Comment by DavidRollinsSlalom** [comment]
note... I also tried to install previous versions and see the same behavior.

+ @angular/cli@1.6.3
+ @angular/cli@1.6.2
+ @angular/cli@1.5.5

**Comment by Marabyte** [comment]
@JoshuaAdamYoung and @DavidRollinsSlalom do you guys get this warning?
`npm WARN @schematics/angular@0.1.12 requires a peer of @angular-devkit/schematics@0.0.43 but none is installed. You must install peer dependencies yourself.`

**Comment by nsjames** [comment]
I'm seeing the same thing.

**Comment by DavidRollinsSlalom** [comment]
@Marabyte yes that's what I'm seeing.


```
24612-MBPR:github david.rollins$ npm install -g @angular/cli
/Users/david.rollins/.nvm/versions/node/v8.5.0/bin/ng -> /Users/david.rollins/.nvm/versions/node/v8.5.0/lib/node_modules/@angular/cli/bin/ng
npm WARN @schematics/angular@0.1.12 requires a peer of @angular-devkit/schematics@0.0.43 but none is installed. You must install peer dependencies yourself.

+ @angular/cli@1.6.4
added 169 packages, removed 49 packages, updated 13 packages and moved 4 packages in 27.899s
24612-MBPR:github david.rollins$ ng new my-app
Error: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
24612-MBPR:github david.rollins$
```

**Comment by T0T4R4** [comment]
Same here on fedora 27
```
$ ng version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.4
Node: 8.9.3
OS: linux x64
Angular: 
...
```
then
```
$ ng new ang5
Error: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

```

**Comment by DiegoRodriguezTandil** [comment]
I'm having the same error in MacOS.
npm -v
5.6.0

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.4
Node: 8.9.1
OS: darwin x64

**Comment by T0T4R4** [comment]
Worked by reinstalling 1.5
```
sudo npm uninstall -g @angular/cli
sudo npm install -g @angular/cli@1.5
```

**Comment by aarndt** [comment]
Same issue here as well

Angular CLI: 1.6.4
Node: 8.5.0
OS: win32 x64
NPM:  5.2.0

**Comment by wdsims63** [comment]
Same for me on macOS as well. However, I got it working by:
sudo npm uninstall -g angular/cli @angular/cli
then
sudo nom install -g @angular/cli@1.6.2

**Comment by T0T4R4** [comment]
Tried to uninstall and install 1.6.2 but it came with the infernal issue already raised :

```
gyp verb command install [ '8.9.3' ]
gyp verb install input version string "8.9.3"
gyp verb install installing version: 8.9.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.9.3
gyp verb ensuring nodedir is created /usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.9.3
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.9.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
```
repeated forever

**Comment by viniciuspwd** [comment]
I fixed it running:

```
npm un -g @angular/cli
npm cache clean --force
npm i -g @angular/cli
```

**Comment by JoshuaAdamYoung** [comment]
Update: fixed by upgrading to node v9.4.0

**Comment by aarndt** [comment]
> Update: fixed by upgrading to node v9.4.0

Should this be considered a solution? According to the CLI docs:

> Both the CLI and generated project have dependencies that require Node 6.9.0 or higher, together with NPM 3 or higher.

**Comment by T0T4R4** [comment]
Really, we shoulnd't have to do a cache clean.... 
and still anything I do now throws me this infernal loop

**Comment by DiegoRodriguezTandil** [comment]
I follow the steps

- Update Node, npm latest version
- Remove angular-cli 1.6.3 
- Install angular-cli 1.5

but the infernal loop is still there

But I could not create application, component and others

**Comment by pacalabre** [comment]
I'm also having this issue on my work computer:
@angular/cli: 1.6.4 
node: 9.4.0
os: win32x64

But it works fine on my personal computer:
@angular/cli: 1.4.9
node: 6.10.2
os: darwin x64)

**Comment by mboughaba** [comment]
Same issue on LTS node and angular cli 1.6.3.
Using 1.6.4 I get:
```shell
λ ng generate service core/configuration --module=app
Error: Path "/__path__/__name@dasherize@if-flat__/__name@dasherize__.service.spec.ts" does not exist.
Path "/__path__/__name@dasherize@if-flat__/__name@dasherize__.service.spec.ts" does not exist.
```

Removing cli and installing it doesn't help at all

**Comment by pacalabre** [comment]
@mboughaba  seemed to have figured out the issue in the link below:
https://github.com/angular/angular-cli/issues/9187

His fix regarding the dependency worked for me.
