### ISSUE TITLE
Consider the root path in .angular-cli.json

### ISSUE THREAD

**Issue by NiKlimenko** [angular/angular-cli#9176]
All the paths in ```.angular-cli.json``` configuration file must respect the ```root``` path.
Currently, lint project path, e2e config path and karma config don't consider the root path.

It is necessary so that when you change the directory of the project, it was necessary to change only the root path.

**Comment by clydin** [comment]
Those configuration items are currently outside the scope of an application and as a result are currently and intentionally not affected by an applications root path.  Future planned features will allow more fine-grained configuration of items such as these.
