### ISSUE TITLE
the angular version in ng-cli is not 5.2.x

### ISSUE THREAD

**Issue by KevinChxm** [angular/angular-cli#9177]
i follow the guid, updated my cli version : 
`npm uninstall -g @angular/cli 
npm cache clean 
npm install -g @angular/cli@latest `.
Now the version is 1.6.4 . Plus the version of my npm is 6.10.x .
But my package.json is still show that the version of  angular is 5.1.0， not 5.2.x

**Comment by Brocco** [comment]
Updating your version of the CLI does not update your your version of `@angular` libraries, you will need to update them via `npm` or in your `package.json` configuration file.
