### ISSUE TITLE
Throw Error Cannot Find Module 

### ISSUE THREAD

**Issue by shanky1992** [angular/angular-cli#9184]
Hello Guys,
I Have Some issue In angular cli project-
I all ready set environment for angular cli project but in that ng serve command not accepted or give me error like  --    Cannot find module '\\colvillad01\Desktops\sanket.bhor\Application Data\npm\node_modules\@angular\cli\bin\ng' I tried lot of time but my issue not resolved yet, so please if any one have solution for that please replay asap.

**Comment by Brocco** [comment]
This is an environment issue about not being able to find a global installation of the Angular CLI. Please check your npm settings and/or check with a support site like gitter or StackOverflow.
