### ISSUE TITLE
Angular CLI not generating service

### ISSUE THREAD

**Issue by mboughaba** [angular/angular-cli#9187]
### Versions
```
λ ng --version && echo node: && node --version && echo npm: && npm --version

Angular CLI: 1.6.3
Node: 9.4.0
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.37
@angular-devkit/core: 0.0.24
@angular-devkit/schematics: 0.0.43
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.12
typescript: 2.4.2
webpack: 3.10.0
node:
v9.4.0
npm:
5.6.0
```

### Repro steps

* Step 1
ng generate service core/example --module=app

Note that it doesn't work with both node LTS and 9.4.0. I also tried with no success reinstalling cli 

### Observed behavior
```
λ ng g s core/configuration --module=app
Error: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```

**Comment by mboughaba** [comment]
Workaround.
Install angular cli 1.5.5.

**Comment by clydin** [comment]
ensure `@angular-devkit/schematics` is at the latest version (currently: 0.0.45).  This was fixed in that version.

**Comment by clydin** [comment]
That is actually a packaging issue.  The peer dependency version was erroneously not updated during the process.  This is being tracked internally and will be corrected in the next release of the package.

Closing this issue as resolved.  Please re-open, if needed.
