### ISSUE TITLE
UglifyJS "ReferenceError: [var] is not defined" due to if_return

### ISSUE THREAD

**Issue by hotforfeature** [angular/angular-cli#9189]
### Versions
```
Angular CLI: 1.6.3
Node: 8.4.0
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

* Use Validators.pattern from @angular/forms
* Configure `.angular-cli.json` to use ES6 for the app
* `ng build --prod`

### Observed behavior

When building for production, the CLI uses UglifyJS to minify code. For ES6 code, Validators.pattern is transformed to the following:
```
            static pattern(e) {
                return e ? ("string" == typeof e ? (a79103 = `^${e}$`,
                a79102 = new RegExp(a79103)) : (a79103 = e.toString(),
                a79102 = e),
                e=>{
                    if (v(e.value))
                        return null;
                    const t = e.value;
                    return a79102.test(t) ? null : {
                        pattern: {
                            requiredPattern: a79103,
                            actualValue: t
                        }
                    }
                }
                ) : w.nullValidator
            }
```

This throws `ReferenceError: a79103 is not defined` since the compressed property does not have a `let` declaration and it exists inside an ES6 class, which uses strict mode.

Going into `node_modules/@angular/cli/models/webpack-configs/production.js` and adding the following to `uglifyCompressOptions` fixes the problem:

```
    const uglifyCompressOptions = {
        // Disabled because of an issue with Mapbox GL when using the Webpack node global and UglifyJS:
        // https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-303880888
        // https://github.com/angular/angular-cli/issues/5804
        // https://github.com/angular/angular-cli/pull/7931
        typeofs: false,

        if_return: wco.supportES2015 ? false : true
    };
```

https://github.com/mishoo/UglifyJS2/issues/1317 seems to document this problem, but it's difficult to see what the solution was. The latest version of uglify-es still has the same issue unless `if_return` is false.

### Desired behavior

Compiling for production to ES6 should not throw runtime errors when using Validators.pattern()

**Comment by hotforfeature** [comment]
Looks like https://github.com/mishoo/UglifyJS2/issues/2747 fixes this problem, but it's not yet released at the time of writing. 

It may be beneficial to bump the uglify-es version dependency for angular-cli when the next version is released with the fix. I'll let the team decide whether to keep this issue open to track that or to close since there's nothing to fix on the Angular side.

**Comment by clydin** [comment]
This appears to have been released as part of `uglify-es` 3.3.6.  Closing as resolved.  If the issue continues to represent itself, please re-open.

**Comment by aldo-roman** [comment]
hi @clydin I'm still experimenting this issue. I know the fix has been released but it seems it has not yet been pulled by the CLI. 

Are we sure that `"@angular/cli": "1.6.7"` is using the patched version of `uglify-es` ?

This is blocking our deployments with current version of the CLI.

**Comment by clydin** [comment]
You can determine the version of `uglify-es` used within a project via `npm ls uglify-es`.
The latest version is currently 3.3.9.  If the project is using a lower version, it is recommended to upgrade it to the latest version.  If running into issues like this, you can try removing both `node_modules` and any package locks and re-installing the packages.
