### ISSUE TITLE
Main.ts: import { MyAppAppComponent, environment } from './app/';  - modules not recognised.

### ISSUE THREAD

**Issue by rexebin** [angular/angular-cli#919]
it should be import { MyAppAppComponent, environment } from './app'; without the '/' at the end for ts to import stuff from ./app/index.ts. At least in Webstorm, MyAppAppComponent, environment are red, not recognised. 

> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

EI Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

v6.2.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

created by cli, no changes.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
This issue is a duplicate from https://github.com/angular/angular-cli/issues/673. It seems to be an issue with webstorm itself, the import is correct.
