### ISSUE TITLE
Using ng generate component heroes

### ISSUE THREAD

**Issue by antenorr** [angular/angular-cli#9196]
Hello i just installed angular cli and following along the Heroes tutorial and attempted to 
```
ng generate component heroes
```
 however i receive the following error 👍
```
Error: dryRunSink.commit(...).ignoreElements(...).concat is not a function
dryRunSink.commit(...).ignoreElements(...).concat is not a function
```
### Versions
```
<!--
Output from: `ng --version`. :  @angular/cli: 1.6.3
 macOS (High Sierra)
-->
```

This is from the tutorial on the Angular Site Tour of heroes that can be found on this page:
https://angular.io/tutorial/toh-pt1

**Comment by antenorr** [comment]
Caught the original string - uninstalled and reinstalled CLI globally and locally  - @angular/cli: 1.6.3 is now
@angular/cli: 1.6.4 -- able to generate with no problems -- Thank you

**Comment by onewiseburdman** [comment]
That isn't the problem it's something else.

**Comment by nasserghiasi** [comment]
I already have this problem with angular cli 1.6.4 and 1.6.5

**Comment by Siafu** [comment]
I'm having this issue with 1.7.0-beta1.
