### ISSUE TITLE
ng is not working

### ISSUE THREAD

**Issue by BlueTugm** [angular/angular-cli#9204]
Whenever i run ng -v it outputs this:
/usr/lib/node_modules/@angular/cli/models/config/config.js:17
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/models/config.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

I would really appreciate if someone could help me.

**Comment by splincode** [comment]
Please add more information to reproduce

**Comment by BlueTugm** [comment]
That is all the info i have

**Comment by splincode** [comment]
Version angular CLI?

**Comment by BlueTugm** [comment]
My node version is 4.8.7 and my npm version is 2.15.11

**Comment by splincode** [comment]
Please, usage command:

```
$ ng -v
_                      _                 ____ _     ___
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
/ △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
|___/

Angular CLI: 1.6.2
Node: 8.7.0
OS: win32 x64
Angular:
...
```

**Comment by splincode** [comment]
Maybe you need update node?

**Comment by BlueTugm** [comment]
When i use ng -v it outputs what i said in the issue

**Comment by BlueTugm** [comment]
How can i do that i thought i had the latest version

**Comment by splincode** [comment]
$ ng -v
_                      _                 ____ _     ___
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
/ △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
|___/

Angular CLI: 1.6.2
Node: 8.7.0
OS: win32 x64
Angular:
...

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/34917006-a132241a-f951-11e7-8e48-c7efffa442ce.png)

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/34917013-bcf6ad42-f951-11e7-8817-e54bfc30c682.png)

**Comment by BlueTugm** [comment]
I am not using windows i am using ubuntu

**Comment by splincode** [comment]
https://nodejs.org/en/download/package-manager/

![image](https://user-images.githubusercontent.com/12021443/34917019-e8883d5e-f951-11e7-8dbd-f62edc8064fe.png)

**Comment by splincode** [comment]
Well, this Angular CLI team did very badly, without processing exceptions, they should throw warnings or normal errors if you are using older versions of the Node platform.

**Comment by splincode** [comment]
Did you succeed?

**Comment by BlueTugm** [comment]
I would like to thank you it is finally working for me

**Comment by splincode** [comment]
Angular loves his community, always write and we will help ...

**Comment by BlueTugm** [comment]
Actualy i have one more question.

After i type ng new ng5 --style=scss --routing
it stops at Installing packages for tooling via npm shoul i wait or is it
done?

**Comment by BlueTugm** [comment]
Oh wait it worked i just had to wait.

**Comment by splincode** [comment]
for questions new issue

**Comment by Brocco** [comment]
This issue appears to have been resolved via community help... thank you for assisting!
