### ISSUE TITLE
Quick development thanks to ready-made starters

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#9205]
The question rather relates to whether there will be an improvement in application deployment techniques for Angular.

I really like the terminal command:

```
ng new [project-name]
```

And if you need should create a minimal app (this great).

```
--minimal default value: false
```

- But if you need to create app by using Kotlin (or Dart) instead TypeScript?

![Kotlin anywhere](http://developine.com/wp-content/uploads/2017/11/Kotlin-Native-Multi-platform.png)

- But if you need to create app for Hybrid Mobile app (usage Ionic), or Native Mobile (NativeScript, ReactNative), or Desktop app (ElectronJS)?

- But if you need to create web application with started popular architecture Redux, Mobx or other Flux-oriented?

- But if you need to create server side web application?

Information appeared in version 5.1
https://blog.angular.io/angular-5-1-more-now-available-27d372f5eb4e

```
ng generate universal 
```

But in the documentation, I can not figure out how to generate such things, where do hands grow and where do I start looking for information, so as not to get confused?
https://github.com/angular/angular-cli/wiki/generate

Every time looking for starters is a tedious task and for beginners we would always like to have ready solutions out of the box.

What can you say about this? It would be great if an amazing Angular CLI could easily deploy the necessary applications to us, using certain flags for this and using pre-selected package.json (with the right packages).

**Comment by Brocco** [comment]
This is possible to do today via schematics, which live in the angular/devkit repository. Documentation is being still being worked on, but there are some good blogs posts out there which can help to get you started.
