### ISSUE TITLE
Code works in dev env while crashing in prod env

### ISSUE THREAD

**Issue by bayy** [angular/angular-cli#9206]
### Versions
```
<!--
Angular CLI: 1.6.3
Node: 6.11.0
OS: darwin x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.0
@angular/cli: 1.6.3
@angular/material: 5.0.0
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0
-->
```

### Repro steps

I am using xml2js, which uses sax-js, to save and load a xml file to a server with Angular 5. I encountered a problem with char & in an angular production environment only. 

I have a text field with value 'a & b', which is saved to the server as `a &amp; b` using xml2js. When loading the data from the server, it works on a local environment. However, on a production server, it will complain that "Cannot read property 'toLowerCase' of undefined" with following code.
```
import { Parser } from 'xml2js';
var parser =  new Parser();
var xml = "<root>a &amp; b</root>"
parser.parseString(xml, function (err, result) {
    console.dir(result);
});
```

### Observed behavior

The err in the above code shows stack trace of minified code. 
```
    TypeError: Cannot read property 'toLowerCase' of undefined
    at L (sax.js:913)
    at o.write (sax.js:1485)
    at h.parseString (parser.js:322)
    at h.parseString (parser.js:5)
    ......
```
line 912 of sax.js shows parser.entity returns null, though on local environment, it is 'amp'
<img width="549" alt="screen shot 2018-01-12 at 4 33 58 pm" src="https://user-images.githubusercontent.com/2373656/34899497-88990532-f7b6-11e7-9d79-da3721061601.png">

### Desired behavior

It should behave the same way in both dev and prod.

**Comment by kzc** [comment]
Uglify bug: https://github.com/mishoo/UglifyJS2/issues/2783

**Comment by bayy** [comment]
kzc suggested a workaround https://github.com/mishoo/UglifyJS2/issues/2783.
$ node_modules/.bin/browserify test.js | node_modules/.bin/uglifyjs -mc inline=false | node
{ root: 'a & b' }

What changes should I make to angular project to use workaround?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
