### ISSUE TITLE
--dry-run is not so dry

### ISSUE THREAD

**Issue by shmert** [angular/angular-cli#921]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Mac OS X 10.10.5

2. Versions. Please run `ng --version`. If there's nothing outputted, please
angular-cli: 1.0.0-beta.5
node: 4.4.5
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
[fez:SecureTransportation/ItinerisWWW/itineris] sbarnum% ng generate route vehicles/:id --dry-run --verbose
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing route
You specified the dry-run flag, so no changes will be written.
installing component
You specified the dry-run flag, so no changes will be written.
  create src/app/+vehicles/+:id/:id.component.css
  create src/app/+vehicles/+:id/:id.component.html
  create src/app/+vehicles/+:id/:id.component.spec.ts
  create src/app/+vehicles/+:id/:id.component.ts
  create src/app/+vehicles/+:id/index.ts
  create src/app/+vehicles/+:id/shared/index.ts

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Ran the above command, and --dry-run was specified, but my files were still changed. This line was added to my vehicles.components.ts file:

import { :idComponent } from './+:id';

**Comment by Brocco** [comment]
This [commit](https://github.com/angular/angular-cli/commit/6efc8ee9323e51159d1392a7d986652c808d65de) resolved that issue and will be part of the next release.
