### ISSUE TITLE
Error tracing on production

### ISSUE THREAD

**Issue by talhakazmi** [angular/angular-cli#9213]
### Versions
```
<!--
Output from: `ng --version`.
@angular/cli: 1.5.2
@angular/material: 5.0.3
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.2
@schematics/angular: 0.1.5
typescript: 2.2.2
webpack: 3.8.1

  Windows (10)
-->
```

### Repro steps
I have applied error tracing on development build which shows proper file and line because of sourcemap files as they do exist on development but when i tried the same code on production built, the file showed up  is  UglifyJs and couldn't understand the line and code.
i can use --sourcemap flag to get the sourcemap on production but i don't want my users to view sourcemap. is there any way i can get proper file and line of error in production without sourcemap

**Comment by talhakazmi** [comment]
I have also tried to generate map iles in production with flag --sourcemap and move them on restricted domain which only i can access but so error produced on my machine shows proper file and line number but on other users it wont show.
but i don't want this i have created an error logging file and want to log error with error trace produced on user end.

**Comment by alan-agius4** [comment]
Closing in favor of https://github.com/angular/angular-cli/issues/12375
