### ISSUE TITLE
v1.7.0-beta.0 beaks Server Side Rendering

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#9219]
### Versions
```
Angular CLI: 1.7.0-beta.0
Node: 8.9.1
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.4
@angular/cli: 1.7.0-beta.0
@angular/flex-layout: 2.0.0-beta.12-b9745c6
@angular/material-moment-adapter: 5.0.4
@angular/material: 5.0.4
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.0-beta.0
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps

After upgrade to Angular CLI: 1.7.0-beta.0, the Server Side Rendering seems to be broken.

I am receiving below error when building server bundles using command `ng build --output-hashing=media --aot --bundle-dependencies=all`

```
ERROR in ./src/main.server.ts
Module parse failed: Unexpected token (34:21)
You may need an appropriate loader to handle this file type.
| core_1.enableProdMode();
| exports.default = aspnet_prerendering_1.createServerRenderer(function (params) {
|     var _a = (module as any).exports, AppServerModule = _a.AppServerModule, AppServerModuleNgFactory = _a.AppServerModuleNgFactory, LAZY_MODULE_MAP = _a.LAZY_MODULE_MAP;
|     var options = {
|         document: params.data.originalHtml,
 @ multi ./src/main.server.ts
```

### Desired behavior
Should build without any error.

**Comment by jmls** [comment]
im getting with with 1.7.3 with a target of esnext

**Comment by Trapulo** [comment]
same problem with 1.7.4

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
