### ISSUE TITLE
Integration with Polymer Issue

### ISSUE THREAD

**Issue by Bretto** [angular/angular-cli#922]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. Linux (Ubutu).

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   angular-cli: 1.0.0-beta.5
   node: 5.6.0
   os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   Create new project with cli install bower_components under src and now the tsc in throwing errors cause its traversing the files under bower_components

4. The log given by the failure. Normally this include a stack trace and some
   more information.
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/analyzer.ts (13, 23): Cannot find module 'dom5'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/analyzer.ts (14, 22): Cannot find module 'url'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/analyzer.ts (15, 25): Cannot find module 'estree'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/analyzer.ts (382, 36): Property 'childNodes' does not exist on type 'LocNode'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/analyzer.ts (382, 64): Property 'childNodes' does not exist on type 'LocNode'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/analyzer.ts (544, 3): Async functions are only available when targeting ECMAScript 6 and higher.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/analyze-properties.ts (15, 25): Cannot find module 'estree'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/ast-value.ts (13, 25): Cannot find module 'estree'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/behavior-finder.ts (12, 29): Cannot find module 'estraverse'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/behavior-finder.ts (18, 25): Cannot find module 'estree'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/declaration-property-handlers.ts (16, 25): Cannot find module 'estree'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/descriptors.ts (12, 25): Cannot find module 'estree'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/descriptors.ts (14, 23): Cannot find module 'dom5'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/docs.ts (15, 23): Cannot find module 'dom5'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/element-finder.ts (12, 29): Cannot find module 'estraverse'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/element-finder.ts (20, 25): Cannot find module 'estree'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/esutil.ts (12, 29): Cannot find module 'estraverse'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/esutil.ts (13, 25): Cannot find module 'estree'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/esutil.ts (14, 28): Cannot find module 'escodegen'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/feature-finder.ts (13, 29): Cannot find module 'estraverse'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/feature-finder.ts (17, 25): Cannot find module 'estree'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/fluent-traverse.ts (1, 25): Cannot find module 'estree'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/import-parse.ts (12, 23): Cannot find module 'dom5'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/import-parse.ts (56, 19): Property 'tagName' does not exist on type 'LocNode'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/import-parse.ts (58, 19): Property 'tagName' does not exist on type 'LocNode'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/import-parse.ts (60, 19): Property 'tagName' does not exist on type 'LocNode'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/import-parse.ts (137, 14): Property '__location' does not exist on type 'LocNode'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/import-parse.ts (137, 33): Property '__location' does not exist on type 'LocNode'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/import-parse.ts (138, 65): Property '__location' does not exist on type 'LocNode'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/import-parse.ts (155, 29): Property 'childNodes' does not exist on type 'LocNode'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/import-parse.ts (160, 37): Property 'childNodes' does not exist on type 'LocNode'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/js-parse.ts (15, 25): Cannot find module 'espree'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/js-parse.ts (16, 25): Cannot find module 'estree'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/js-parse.ts (17, 29): Cannot find module 'estraverse'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/ast-utils/jsdoc.ts (13, 27): Cannot find module 'doctrine'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/loader/fs-resolver.ts (14, 21): Cannot find module 'fs'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/loader/fs-resolver.ts (15, 23): Cannot find module 'path'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/loader/fs-resolver.ts (16, 22): Cannot find module 'url'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/loader/redirect-resolver.ts (14, 21): Cannot find module 'fs'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/loader/redirect-resolver.ts (15, 23): Cannot find module 'path'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/loader/redirect-resolver.ts (16, 22): Cannot find module 'url'.
  /data/2016/Ng2Todo/tmp/broccoli_type_script_compiler-input_base_path-FwOanXpr.tmp/0/src/bower_components/hydrolysis/src/loader/resolver.ts (3, 1): Cannot find name 'require'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/data/2016/Ng2Todo/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:115:19)
    at BroccoliTypeScriptCompiler.build (/data/2016/Ng2Todo/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /data/2016/Ng2Todo/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/data/2016/Ng2Todo/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:26:49)
    at Angular2App._getTsTree (/data/2016/Ng2Todo/node_modules/angular-cli/lib/broccoli/angular2-app.js:321:18)
    at Angular2App._buildTree (/data/2016/Ng2Todo/node_modules/angular-cli/lib/broccoli/angular2-app.js:116:23)
    at new Angular2App (/data/2016/Ng2Todo/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/data/2016/Ng2Todo/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /data/2016/Ng2Todo/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /data/2016/Ng2Todo/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/data/2016/Ng2Todo/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
So I want to use Polymer with Ng2 but I can't find a way to prevent the tsc to process the ts files in the bower_components folder that is located a the root of the ng server (src) I tried to configure tsconfig.js but nothing I have tried is working. Thanks

**Comment by filipesilva** [comment]
Hm, my best recommendation for bower components at the moment is to either:

- use a npm alternative
- configure bower to install under `node_modules`

Then you can configure the CLI to copy over the files you need via `angular-cli-build.js`.
