### ISSUE TITLE
ng serve does not re-compile changed files in windows junction points

### ISSUE THREAD

**Issue by maks187** [angular/angular-cli#9220]
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.3
Node: 8.9.3
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.4
@angular/cli: 1.6.3
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.0.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps

* Some time ago, it was possible to junction-link a directory with ts-files into an existing project structure.
* Changes done in that time to the ts-files resulted that the project was recompiled when ng-Serve was used to start the project
* But now, junction-directory ts-files (also html (component)-files..) are only found and compiles at the first ng serve start, when the argument "--preserve-symlinks" is used. This was not needed in the past
* But for some reason this is not done again, when changes are made on that linked files and only a command-exit and re-ng-serve does recompile that changes which are then visible in the browser

### Observed behavior
```
1) ng serve needs --preserve-symlinks for compiling junction directories
2) but does not recompile the project on changes done in that junction directories
3) also changes done in not-junctioned files, which calls the recompiling, does not really re-compile all files as junctioned file changes are ignored and the state of them stays initial
```

### Desired behavior
1) --preserve-symlinks can stand, it's ok, but maybe you should display such important information somewhere
2) a change in a junction directory should execute a recompile of the project else the whole ng serve concept is useless..

**Comment by txinfo** [comment]
I believe this is an issue with webpack and not angular-cli: https://github.com/webpack/watchpack/issues/61

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since there we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
