### ISSUE TITLE
Material theme broken with Build Optimizer.

### ISSUE THREAD

**Issue by Taha-Di-Nero** [angular/angular-cli#9221]
### Versions
```
Angular CLI: 1.6.4
Node: 6.11.3
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cdk: 5.0.4
@angular/cli: 1.6.4
@angular/material: 5.0.4
@angular-devkit/build-optimizer: 0.0.37
@angular-devkit/core: 0.0.24
@angular-devkit/schematics: 0.0.45
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.12
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps
https://github.com/Taha-Di-Nero/testFE.git

### Observed behavior
Running `npm run start -- --prod` produce a fab button wihtout accent color:

![with bd](https://user-images.githubusercontent.com/26605435/34944359-936c447e-f9ff-11e7-8b6a-b792a125280d.png)

Running `npm run start -- --prod --build-optimizer=false` works fine:

![without-bd](https://user-images.githubusercontent.com/26605435/34944373-9a5f64f0-f9ff-11e7-8ec7-3f618e3c6343.png)

### Desired behavior
Same behavior with/without Build Optimizer.

**Comment by Taha-Di-Nero** [comment]
@filipesilva After digging around I found that `uglifyCompressOptions.pure_getters = true;` was removing something that is useful. By removing https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/models/webpack-configs/production.ts#L131 everything works fine.

This compression in my case decrease the vendor bundle size by 1.63%
`glifyCompressOptions.pure_getters = false`

![image](https://user-images.githubusercontent.com/26605435/34952317-9d6be7bc-fa19-11e7-81b8-99232261e620.png)

`glifyCompressOptions.pure_getters = false`

![image](https://user-images.githubusercontent.com/26605435/34952356-b2f2a652-fa19-11e7-9634-1eb18cafc19b.png)

**Comment by clydin** [comment]
Nice job on the research.  This is actually being tracked over here: https://github.com/angular/devkit/issues/388.  And there's a pending PR against material to fix.

**Comment by Brocco** [comment]
Closing as this is being tracked by the issue mentioned by @clydin above.

**Comment by alexjlockwood** [comment]
Could anyone recommend a workaround for this issue?
