### ISSUE TITLE
[Feature request]: allow specifying different tsconfig.app.json via command line, and/or have a different tsconfig for 'serve' and 'build' tasks

### ISSUE THREAD

**Issue by txinfo** [angular/angular-cli#9234]
Currently I include some additional external ts files by way of the tsconfig.json 'include' property but I only need to include these in development builds / when using `ng serve`. It would be nice to be able to specify a separate tsconfig for production builds, similar to the way there is a separate tsconfig for tests.

**Comment by sten82** [comment]
I'm looking for the same feature. I want to change the path for libs so that ng serve takes it from projects while ng build is taking it from dist folder.

**Comment by kirillgroshkov** [comment]
I want it to have a "modern build" feature - create es2015 build for modern browsers and es5 for legacy.

**Comment by alan-agius4** [comment]
Hi,

You can achieve the above by having various `build` configurations and specifying a `tsConfig` in each.

Example:
```js
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
    ...
    "tsConfig": "src/tsconfig.app.dev.json"
  },
  "configurations": {
    "production": {
      ...
      "tsConfig": "src/tsconfig.app.prod.json"
    }
}
```

`ng serve` will use the development tsconfig while when using the `--prod` flag it will use the production one.
