### ISSUE TITLE
Angular 5 Error ng build --deploy-url

### ISSUE THREAD

**Issue by AlaaFK** [angular/angular-cli#9238]
Hello,
 I was working with angular 4 with MVC. Recently we upgraded to Angular 5. I got error in index.cshtml in the path $/Views/Home in MVC project at the following line:

`fileEntries = Directory.EnumerateFiles(Server.MapPath("~/dist"));`
The error is 
>Error The command "ng build --deploy-url http://localhost:60859/dist/" exited with code 3.

I tried uninstall npm and reinstall it and same for cli angular. Nothing worked. 
And Im not able to build the project!

**Comment by AlaaFK** [comment]
Any help?

**Comment by hansl** [comment]
Does the project builds without the flag?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
