### ISSUE TITLE
Protractor base URL not respected

### ISSUE THREAD

**Issue by buu700** [angular/angular-cli#9242]
### Versions
```
1.6.4
```

### Repro steps

* Set protractor.conf.js's `baseUrl` to `'http://localhost:42002/'`
* `ng e2e --host 0.0.0.0` 

### Observed behavior

Test is run with URL http://0.0.0.0:42002

### Desired behavior

Based on this, that behavior appears to be by design: https://github.com/angular/angular-cli/blob/7352bcbcabe976b82b651fbd4b251fbbfebe2ba4/packages/%40angular/cli/tasks/e2e.ts#L33

I'm not sure why that would be intended behavior, but it's breaking my use case (CLI within Docker hitting a Selenium server on the host OS). Could an option be provided to disable this?

Edit: Just did a git blame on that code and noticed a commit that added a `--public-host` option, which sounds like exactly I'm asking for. I'll update and/or close this after we have a chance to test.

**Comment by buu700** [comment]
Yep, `--public-host localhost:42002` resolved this.

**Comment by ruchitgandhi** [comment]
@buu700 Did you use - ng e2e --public-host locahost:42002 ? as your test command?

**Comment by buu700** [comment]
Yeah `ng e2e --host 0.0.0.0 --public-host localhost:42002` was what ended up working for me.
