### ISSUE TITLE
Unable to install node-sass globally on Linux

### ISSUE THREAD

**Issue by kinlhp** [angular/angular-cli#9245]
[Unable to install node-sass globally on Linux](https://github.com/sass/node-sass/issues/2216)

**Comment by j2L4e** [comment]
not a bug, but a permissions issue... fix your permissions or use sudo as a really dirty workaround.

**Comment by hansl** [comment]
Unfortunately, this is not something in our control. We do not use anything special for that package. You can look for support on stackoverflow, or the package's own github repo.

**Comment by davincif** [comment]
I'm having the same problem... nothing resolves it.
The only workaround to work was:
```sudo npm install --unsafe-perm -g node-sass```
