### ISSUE TITLE
build watch and aot failed when there is error in template file

### ISSUE THREAD

**Issue by ltvan** [angular/angular-cli#9248]
### Versions
```
Angular CLI: 1.6.4
Node: 8.9.3
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.4
@angular/cli: 1.6.4
@angular/material: 5.0.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
Case 1: template refers to a property which does not exist in component
* Run `ng build -w --aot`
* Show error as expected
* Correct the template to refer to the correct propery and save
* It doesn't re-build until changing other ts file.
=> Expect: it should rebuild when saving template file

Case 2: 
* Run `ng build -w --aot` successfully
* Update template, refer to a property which does not exist in component
* It re-builds but do not show error
=> Expect: it should show the error when re-build

**Comment by timblakely** [comment]
Can confirm, bug appears to have been introduced in `@ngtools/webpack` in `1.9.3`. `@ngtools/webpack` at versions `<= 1.9.2` rebuild as expected.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
