### ISSUE TITLE
ng build or ng build --prod successfully builds but the app doesn't run

### ISSUE THREAD

**Issue by sorakthunly** [angular/angular-cli#9251]
### Versions
```
Angular CLI: 1.6.1
Node: 8.9.3
OS: darwin x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.3
@angular/cli: 1.6.1
@angular/material: 5.0.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
npm build --prod

or

npm build

### Observed behavior
The command runs successfully and completes the build. However, when I try to run the app from /dist, the app doens't run and no useful error log is provided except for the following:

Uncaught SyntaxError: Unexpected token <inline.50fea24a37a5d4ca10b4.bundle.js:1
polyfills.2ab13b155630d99a2e92.bundle.js:1

Uncaught SyntaxError: Unexpected token <main.27bdbea1a06ff9940d34.bundle.js:1

Uncaught SyntaxError: Unexpected token <(index):27

Live reload enabled.

### Desired behavior
I would expect the build to just work and the app to run without any errors and if there are, the console should log more useful error details so I can at least try to debug.

**Comment by hansl** [comment]
@sorakthunly 

Could you please explain what you mean by "run the app from /dist"?  What commands are you using?

**Comment by sorakthunly** [comment]
I used live-server to run the compiled code html and JS code. So simple, live-server index.html. I tried just clicking on the index.html file but it doesn't run either.

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
