### ISSUE TITLE
Ng Generate documentation needs examples of using the options

### ISSUE THREAD

**Issue by hughanderson4** [angular/angular-cli#9252]
documentation of ng generate doesn't have any examples of how to use the options.
please provide some samples of how to correctly use ng generate options.

example: how is `--spec` supposed to be used?
do i need to say `ng generate --spec=false` or is it `ng generate --spec false`
give the user an idea of how to actually use the options, and give examples to show how to override the defaults.

**Comment by filipesilva** [comment]
https://angular.io/cli/generate now contains examples so I think this issue is addressed.
