### ISSUE TITLE
Problem with installation AngularCLI without internet

### ISSUE THREAD

**Issue by israodin** [angular/angular-cli#9254]
Hi we need help with installation AngularCLI on closed environment without internet:
I need know about:
1.Do the new versions support back version computability:
for example:
AngularCLI 1.6 support Angular 4 ? 
2.Which version nodeJS and npm I need for install AngularCLI 
for example we have :
node 6.10.2
npm 3.10.0
And during installation AngularCLI we get many errors about : absence of some packages!
3.if I need presets before installing Angular CLI

### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by WandererInVoids** [comment]
it`s support ticket, use stackoverflow

**Comment by israodin** [comment]
Just stackoverflow you don't have asupport????

**Comment by hansl** [comment]
1. yes
2. node 6
3. you need an internet connection.

We don't offer support on this repo. Either gitter or stackoverflow are better platforms for those kind of questions.
