### ISSUE TITLE
How to generate a project with specific version of angular.

### ISSUE THREAD

**Issue by torabian** [angular/angular-cli#9259]
As a developer, I want to test my angular module. In order to test, I want to be able to create apps in Angular 2, Angular 4 and Angular 5. When I get the latest version of angular cli and using `ng new project` it will use Angular 4 by default.

So how can I make a Angular 2 project?

**Comment by Taha-Di-Nero** [comment]
https://github.com/angular/angular-cli/issues/9239#issuecomment-358155759

**Comment by hansl** [comment]
Duplicate and answered in #9239 as @Taha-Di-Nero mentioned.

**Comment by icenold** [comment]
not a duplicate
