### ISSUE TITLE
 ng g  c  error  

### ISSUE THREAD

**Issue by zhouxinsenGitHub** [angular/angular-cli#9268]
use  ng g c mycomponent
 i  got error ：
Error: Path "/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html" does not exist.
Path "/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html" does not exist.

how to fix it?

**Comment by Taha-Di-Nero** [comment]
https://github.com/angular/angular-cli/blob/646c1b0c38c0b2868d6dfd721f6546c588fc0b29/CONTRIBUTING.md#submit-issue

**Comment by hansl** [comment]
Thanks for reporting this issue. We need more information to understand and reproduce the problem. We have provided a template for filling out issues with information that is important.

We're closing this issue, so please fill out the [full issue form](https://github.com/angular/angular-cli/issues/new).
