### ISSUE TITLE
TypeScript sourcemaps not working with AngularCompilerPlugin

### ISSUE THREAD

**Issue by nparrish** [angular/angular-cli#9275]
### Versions
```
Angular CLI: 1.6.2
Node: 9.3.0
OS: darwin x64
Angular: 5.2.1
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router, upgrade

@angular/cli: 1.6.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack-dev-server: 2.9.7
webpack: 3.10.0
```

### Repro steps
Clone this repo: https://github.com/nparrish/sample-app-angular-hybrid
```
yarn
yarn start
```

### Observed behavior
In Chrome devtools, you will find there are no source maps for any TypeScript files except the main entry file (`main.ts`).  For example, `angularModule.ts` has only JavaScript sourcemaps.

### Desired behavior
There should be TypeScript sourcemaps for all TypeScript source files.

**Comment by nparrish** [comment]
Turns out I was able to resolve this issue with an embarrassingly simple change to my Webpack config:

Doesn't work:
```
module.exports = {
  ...
  resolve: {
    extensions: [".js", ".ts"],
     ...
}
```

Does work:
```
module.exports = {
  ...
  resolve: {
    extensions: [".ts", ".js"],
     ...
}
```

So basically, you just need to make sure that module resolution prioritizes TypeScript over JavaScript.

**Comment by Paulskit** [comment]
You made my day! 
If you're using `@ngtools/webpack` and watch mode doesn't work for you, this fix should help.

**Comment by alxpsr** [comment]
Lol
