### ISSUE TITLE
Feature Request: Make ng-xi18n extraction tool accessible outside of CLI

### ISSUE THREAD

**Issue by gregbown** [angular/angular-cli#9282]
Angular Documentation used to illustrate using the i18n extraction tool outside of the CLI
Below would have been a script inside package.json

```./node_modules/.bin/ng-xi18n --i18nFormat=xlf2 --outFile=src/i18n/messages.xlf```

The tool would extract all of the i18n attribute markup text consuming any ID's within the attribute and write out the .xlif file. Running the script now fails silently.

The only method now described in the [documentation.](https://angular.io/guide/i18n#create-a-translation-source-file-with-ng-xi18n) is via the CLI inside of a CLI build process.

Is there a way to access the extraction tool in an ejected Webpack build similar to how it was documented before?
Are there plans to enable using the extraction tool outside of the CLI as before? 

Not sure if this is related to this [post](https://github.com/angular/angular/pull/21626)

**Comment by ocombe** [comment]
The example script that you use above is still valid et can be used. We have removed this from the documentation because it has been decided that our whole documentation would focus on using angular CLI since it is what we recommend and it is easier to use.
