### ISSUE TITLE
ERROR in ./src/styles.scss Module build failed: Error: Unclosed comment

### ISSUE THREAD

**Issue by LeventZheng** [angular/angular-cli#9286]
### Versions
![image](https://user-images.githubusercontent.com/11297586/35135875-ee85279a-fd1a-11e7-8fa6-2db04231fc5e.png)

### Repro steps
ng build --prod

### Observed behavior
10% building modules 3/4 modules 1 active ...niversal\teaching-ng5\src\styles.scssNode#moveTo was deprecated. Use Container#append. Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.16, but postcss-merge-rules uses 5.2.18. Perhaps this is the source of the error below. 69% building modules 1881/1882 modules 1 active ...niversal\teaching-ng5\src\styles.scssUnknown error from PostCSS plugin. Your current PostCSS version is 6.0.16, but postcss-merge-rules uses 5.2.18. Perhaps this is the source of the error below. Date: 2018-01-19T04:55:56.763Z Hash: 5877c3bd8fb73ef79691 Time: 342285ms

### Mention any other details that might be useful (optional)
error detail:
![image](https://user-images.githubusercontent.com/11297586/35135825-97fc0600-fd1a-11e7-83e2-c08baefe3a11.png)

**Comment by LeventZheng** [comment]
this kind of comment make this error:
**html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p,
 /*blockquote, pre,*/
/*a, abbr, acronym, address, big, cite, code,*/
/*del, dfn, em, img, ins, kbd, q, s, samp,*/
/*small, strike, strong, sub, sup, tt, var,*/
/*b, u, i, center,*/
dl, dt, dd, ol, ul, li,
/*fieldset, form, label, legend,*/
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
/*figure, figcaption, */
footer, header, hgroup,
menu, nav, output, ruby, section, summary,
time, mark, audio, video  {
  margin: 0;
  padding: 0;
  border: 0;
  font: inherit;
  font-size: 100%;
  vertical-align: baseline;
}**

**Comment by denkomanceski** [comment]
any updates on this ?

**Comment by kirtangajjar** [comment]
@denkomanceski Can You open the issue? This type of comments should not trigger a error
