### ISSUE TITLE
angular4 AOT is broken when I use d3.js

### ISSUE THREAD

**Issue by SunnyLiHY** [angular/angular-cli#9289]
I use d3 v3.5.17 in my project. It cannot find d3 after building my project.
I googled and seemed it is something related to: "useStrict". So I manually removed 'use strict' from build.js, then it can pass.

**Comment by SunnyLiHY** [comment]
ng build --aot --base-href  **** --prod

**Comment by SunnyLiHY** [comment]
here is my package.json
{
    "name": "static",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
        "ng": "ng",
        "start": "ng serve --aot --host 0.0.0.0 --disable-host-check --port 4201 --proxy-config proxy.conf.json",
        "start-without-reload": "ng serve --live-reload false --host 0.0.0.0 --disable-host-check --port 4201 --proxy-config proxy.conf.json",
        "build": "ng build --aot --base-href **** --prod",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "^5.0.0",
        "@angular/common": "^5.0.0",
        "@angular/compiler": "^5.0.0",
        "@angular/core": "^5.0.0",
        "@angular/forms": "^5.0.0",
        "@angular/http": "^5.0.0",
        "@angular/platform-browser": "^5.0.0",
        "@angular/platform-browser-dynamic": "^5.0.0",
        "@angular/router": "^5.0.0",
        "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
        "@ngrx/effects": "^4.1.1",
        "@ngrx/store": "^4.1.1",
        "angular-gridster2": "^4.1.0",
        "bootstrap": "^4.0.0-beta.2",
        "bootstrap-slider": "^10.0.0",
        "core-js": "^2.4.1",
        "d3": "^3.5.17",
        "echarts": "^3.8.5",
        "flatpickr": "^4.1.2",
        "font-awesome": "^4.7.0",
        "is_js": "^0.9.0",
        "jquery": "^3.2.1",
        "jquery-file-download": "^1.4.6",
        "moment": "^2.19.2",
        "ng-select": "^1.0.0-rc.3",
        "ng2-file-upload": "^1.2.1",
        "ng2-ui-switch": "^1.0.2",
        "rxjs": "^5.5.2",
        "select2": "^4.0.6-rc.0",
        "zone.js": "^0.8.14"
    },
    "devDependencies": {
        "@angular/cli": "1.5.0",
        "@angular/compiler-cli": "^5.0.0",
        "@angular/language-service": "^5.0.0",
        "@types/jasmine": "~2.5.53",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "~6.0.60",
        "codelyzer": "~3.2.0",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.1.2",
        "ts-node": "~3.2.0",
        "tslint": "~5.7.0",
        "typescript": "~2.4.2"
    }
}

**Comment by hansl** [comment]
Thanks for reporting this issue. We need more information to understand and reproduce the problem. We have provided a template for filling out issues with information that is important.

We're closing this issue, so please fill out the [full issue form](https://github.com/angular/angular-cli/issues/new).
