### ISSUE TITLE
Feature request - easily modify app path

### ISSUE THREAD

**Issue by tydanielson** [angular/angular-cli#929]
It takes quite a few modifications to update system.js and tsconfig.json to change the path of the application.  There are also a number of other modifications where routes and components pull from a relative path.  It would be nice if an @app environment map was build in and could easily be changed instead of the hardcoded ./app everywhere.

**Comment by filipesilva** [comment]
This is a case where the CLI is following the [style guide](https://angular.io/docs/ts/latest/guide/style-guide.html#!#application-structure) closely, and quite unlikely to change from using `app/` as the main app folder. There's also a lot of CLI side config that depends on the `app/` folder.

**Comment by tydanielson** [comment]
I understand your reason for closing this. However, both TypeScript and System.js are adding or have added support for path definition and baseUrl values.  This will allow for easy external module imports, and more importantly, it'll be easier for a site to embed an angular2 application that's hosted elsewhere.  Again I think your reason for closing this makes sense, but it might make sense to keep this on the radar.

**Comment by filipesilva** [comment]
I think those are very real benefits mind you, and I've seen similar requests in other issues. Even if it doesn't directly happen in the CLI, in the future we could at least not prevent people from doing it themselves.
