### ISSUE TITLE
ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":fa lse}!./src/styles/site.less

### ISSUE THREAD

**Issue by ismailbaig** [angular/angular-cli#9296]
### Versions
```

npm: 4.2.0
Angular CLI: 1.6.4
Node: 7.10.0
OS: win32 x64
Angular: 4.4.6
... common, compiler, core, forms, http, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular/compiler-cli: 4.4.4
@angular/tsc-wrapped: 4.4.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps

* Open Nodejs command prompt
* enter "npm run start" or "ng serve"
* i get the error

### Observed behavior
```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":fa
lse}!./src/styles/site.less
Module build failed: Error: Can't resolve 'Archer/fonts/HCo_fonts.css' in 'C:\MyProjectName\src\styles'
    at onError (C:\MyProjectName\node_modules\enhanced-resolve\lib\Resolver.js:61:15)
    at loggingCallbackWrapper (C:\MyProjectName\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (C:\MyProjectName\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (C:\MyProjectName\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (C:\MyProjectName\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (C:\MyProjectName\node_modules\tapable\lib\Tapable.js:252:11)
    at C:\MyProjectName\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (C:\MyProjectName\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (C:\MyProjectName\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (C:\MyProjectName\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (C:\MyProjectName\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (C:\MyProjectName\node_modules\tapable\lib\Tapable.js:252:11)
    at innerCallback (C:\MyProjectName\node_modules\enhanced-resolve\lib\Resolver.js:144:11)
    at loggingCallbackWrapper (C:\MyProjectName\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (C:\MyProjectName\node_modules\tapable\lib\Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (C:\MyProjectName\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:44:6)
 @ ./src/styles/site.less 4:14-196
 @ multi ./src/styles/site.less
```

### Desired behavior
There should not be any build error

------------------------------------------------------------------------------------------------------------------
The HC._fonts.css file is something as follows

/*
	Copyright (C) 2011-2015 Hoefler & Co.
	This software is the property of Hoefler & Co. (H&Co).
	Your right to access and use this software is subject to the
	applicable License Agreement, or Terms of Service, that exists
	between you and H&Co. If no such agreement exists, you may not
	access or use this software for any purpose.
	This software may only be hosted at the locations specified in
	the applicable License Agreement or Terms of Service, and only
	for the purposes expressly set forth therein. You may not copy,
	modify, convert, create derivative works from or distribute this
	software in any way, or make it accessible to any third party,
	without first obtaining the written permission of H&Co.
	For more information, please visit us at http://typography.com.
	269000-98249-20151112
*/

@font-face {
	font-family: 'Archer 5r';
	src: url('279F9105D04D05167.eot');
	src: local('?'),
		url('279F9105D04D05167.eot?#hco') format('embedded-opentype'),
		url(data:application/x-font-woff;base64,d09GRk9UVE8AAD6qAA0AAAAAbPgAAQAAAAA8iAAAAiIAAAaEAAAAAAAAAABDRkYgAAAI1AAAKNMAADI0Cx0++EdERUYAADGoAAAAHgAAACAA+wAER1BPUwAAMcgAAAhpAAAmHOMDzb1HU1VCAAA6NAAAAFoAAACA6jAts09TLzIAAAGMAAAAUgAAAGBYVGVbY21hcAAABmQAAAJcAAADWB8BSFZnYXNwAAA3ANuh4LsH6Zj88xs5a1bxjmDW53Uzx3MQeNJPRfzHfmVRo6tI2qnIF8+8eOYxz5xapZiaPetero9v8Gb9FjJGWfAzTS6k/i+HIn7AKzyJGpWgH+VHqloGYOkE3O9eNOIChlZyJybNdwiEe+4DT2Se7hoq9q/g9bYn6WpZTQxcVMQPiY7jGJ+e7Ty74+MvpfwFHRs+bw==);
	font-weight: normal;
	font-style: normal;
}

@font-face {
	font-family: 'Archer 5i';
	src: url('505E365E76C094002.eot');
	src: local('?'),
		url('505E365E76C094002.eot?#hco') format('embedded-opentype'),
		url(data:application/x-font-woff;base64,d09GRk9UVE8AAD+AAA0AAAAAbswAAQAAAAA9YAAAAiAAAAaEAAAAAAAAAABDRkYgAAAI2AAAKgcAADVNzVk96kdERUYAADLgAAAAHgAAACAA+wAER1BPUwAAMwAAAAf/AAAk1vxV5EBHU1VCAAA7AAAAAFoAAACA6jAts09TLzIAAAGQAAAAUwAAAGBYVGVUY21hcAAABmQAAAJcAAADWB8BSFZnYXNwAAA7XAAAAAgAAAAIAAAAC2hlYWQAAAEwAAAANAAAADYFQ3NeaGhlYQAAAWQAAAAhAAAAJAdXA2dobXR4AAA7ZAAAAfsAAAM4okEmC21heHAAAAGIAAAABgAAAAYAzlAAbmFtZQAAAeQAAAR+AAALrCcRfStwb3N0AAAIwAAAABUAAAAg/6wAMnjaY2BkYGBgZHBcEhuYHc9v85WBm/kFUIThYuD0izD6f/9/VZDqDsWnbRfoNtsAUsD7mfhEOQp0xLZlKb6FBFcLQvyTgDs4jHPHn55MUGsik3lhxnA3+KCVwii6bepwvTs3JIplUclEEEAWSRoTIGDybJMtoVwqKZV+mStMxsyIYCWTZfJZNFhYQRw6NLhGlKEUpg0Vs+AfqVCNdNvsvd4Ovd13hZ+5VYumXsZkK/X2/zHwKQxm+WeCRrSBqL0Uv1GN6is1ndzVDPwKt81POWI4l6Il7uo55eTiJlA7a9pr693aHBzMzBxsysxrZdIirkNkSyW4V4l877HxHOQ6vV+R5pXVPnNiLyKm22Nw2uQxpXnj6E85BvrfT0iQz25WPnHH/+xq7llul1fTHuA9PHmuOxjCHJp88BLXeKcoxxZAxAZnaHCO+0a3N/F9+AS81tVxjratpht7neUh0XMf49G7n3Z0cfynlLwnzPis=);
	font-weight: normal;
	font-style: normal;
}

@font-face {
	font-family: 'Archer 7r';
	src: url('9D54B24EB081DDF76.eot');
	src: local('?'),
		url('9D54B24EB081DDF76.eot?#hco') format('embedded-opentype'),
		url(data:application/x-font-woff;base64,d09GRk9UVE8AAEE2AA0AAAAAbcAAAQAAAAA/FAAAAiIAAAaEAAAAAAAAAABDRkYgAAAI1AAAKjIAADL2mMf5AUdERUYAADMIAAAAHgAAACAA+wAER1BPUwAAMygAAAmPAAAmIOhT0xdHU1VCAAA8uAAAAFoAAACA6jAts09TLzIAAAGMAAAAUQAAAGBWhlWTY21hcAAABmQAAAJcAA99Ix+ac3ctas4h3BrE/rZo6nIPCon4rkj/3KokZXkbRTkc+eefbMQ545tkoxNXvWvVwd3uDV6jXkjBLyM0vPpP4vhyK5xys8iRqVoB/lJ6paBmDpBNztnjViCEMruROT5lsEwh33gScyT3cNFftX8HrTk3S1rCYGLi6S+0SHcYyPz3ae3cnhl1L+Alq8Pj8=);
	font-weight: normal;
	font-style: normal;
}

@font-face {
	font-family: 'Archer 7i';
	src: url('60E6C69CCFB494F0A.eot');
	src: local('?'),
		url('60E6C69CCFB494F0A.eot?#hco') format('embedded-opentype'),
		url(data:application/x-font-woff;base64,d09GRk9UVE8AAEM7AA0AAAAAcQQAAQAAAABBGAAAAiMAAAaIAAAAAAAAAABDRkYgAAAI2AAALGkAADZ6w+M0HkdERUYAADVEAAAAHgAAACAA+wAER1BPUwAANWQAAAlNAAAl3ASi7NxHU1VCAAA+tAAAAFoAAACA6jAts09TLzIAAAGUAAAAUAAAAGBWhmWQY21hcAAABmQAAAJcAAADWB8BSFZnYXNwAAA/EAAAAAgAAAAIAAAAC2hlYWQAAAEwAAAANgAAADYHjmg0aGhlYQAAAWgAAAAhAAAAJAdxA4NobXR4AAA/GAAAAf0AAAM4rLYg1m1heHAAAAGMAAAABgAAAAYAzlAAbmFtZQAAAeQAAASAAAALsh8D2xRwb3N0AAAIwAAAABUAAAAg/6sAMgABAAAAAQBBoLSspl8PPPUACw
	font-weight: normal;
	font-style: normal;
}

@font-face {
	font-family: 'Archer 8r';
	src: url('7766FE836C7695F8A.eot');
	src: local('?'),
		url('7766FE836C7695F8A.eot?#hco') format('embedded-opentype'),
		url(data:application/x-font-woff;base64,d09GRk9UVE8AAD7aAA0AAAAAbDQAAQAAAAA8uAAAAiIAAAaEAAAAAAAAAABDRkYgAAAI1AAAKDsAADFqCF+gE0dERUYAADEQAAAAHgAAACAA+wAER1BPUwAAMTAAAAkuAAAmIOvb1olHU1VCAAA6YAAAAFoAAACA6jAts09TLzIAAAGMAAAAUQAAAGBWn2WiY21hcAAABmQAAAJcAAADWB8BSFZnYXNwAAA6vAAAAAgAAAAIAAAAC2hlYWQAAAEwAAAANAAAADYFnbQXaGhlYQAAAWQAAAAfAAAAJAd5A7lobXR4AAA6xAAAAfIAAAM4qO0XG21heHAAAAGEAAAABgAAAAYAzlAAbmFtZQAAAeAAAASCAAALrxZZsG9wb3N0AAAIwAAAABMAAAAg/7gAMnjaY2BkYGBgZHBM3frePp7fqCA27IPcL+bH0e/Hfs32/ro/BZdRWjwxPoeGbAZUO9p/9Gc/h2aAdiQoWsOLXvQCWSaIQVK7w8s8KQIRVdt7q6yA4wlqyn2vN7XeeDGjuU32oAkrVXD32fCUh3BSp190NxDnXnQvANX9ScdveYiso+MJmMopthJMQCPEbLUHp4snHQfP8MJ3V+1fwetOTdLWsJgYuLpKHRIdxjE/Pdp7dyeGXUv4GSo8+Ow==);
	font-weight: normal;
	font-style: normal;
}

@font-face {
	font-family: 'Archer 8i';
	src: url('6B52B7ED3AC281FEA.eot');
	src: local('?'),
		url('6B52B7ED3AC281FEA.eot?#hco') format('embedded-opentype'),
		url(data:application/x-font-woff;base64,d09GRk9UVE8AAEADAA0AAAAAbpAAAQAAAAA94AAAAiMAAAaIAAAAAAAAAABDRkYgAAAI3AAAKfcAADSTqgQHD0dERUYAADLUAAAAHgAAACAA+wAER1BPUwAAMvQAAAiGAAAlUCF+zsdHU1VCAAA7fAAAAFoAAACA6jAts09TLzIAAAGUAAAAUQAAAGBWn2WiY21hcAAABmgAAAJcAAADWB8BSFZnYXNwAAA72AAjEuTjpr
	font-weight: normal;
	font-style: normal;
}

@font-face {
	font-family: 'Archer SSm 5i';
	src: url('35B410DD408B18F0E.eot');
	src: local('?'),
		url('35B410DD408B18F0E.eot?#hco') format('embedded-opentype'),
		url(data:application/x-font-woff;base64,d09GRgABAAAAAHqrABIAAAAA7vQAAQAAAAB4gAAAAisAAAaQAAAAAAAAAABHREVGAABs+AAAAB4AAAAgAQwABUdQT1MAAG0YAAALCgAALQopMiInR1NVQgAAeCQAAABaAAAAgOo0LbVPUy8yAAACDAAAAFEAAABgVuBWLmNtYXAAAAz8AAACYwAAA1SAqqELY3Z0IAAAEOwAAABCAAAAQgGvFE1mcGdtAAAPYAAAAPcAAAFhkkHa+mdhc3AAA4=);
	font-weight: normal;
	font-style: normal;
}

@font-face {
	font-family: 'Archer SSm 7r';
	src: url('06B328F14EA944AE9.eot');
	src: local('?'),
		url('06B328F14EA944AE9.eot?#hco') format('embedded-opentype'),
		url(data:application/x-font-woff;base64,Nn+bJQ9Ljasan9zzv8eT4eyl+A1OQQrY=);
	font-weight: normal;
	font-style: normal;
}

@font-face {
	font-family: 'Archer SSm 7i';
	src: url('FF035F5C8A1C0FB53.eot');
	src: local('?'),
		url('FF035F5C8A1C0FB53.eot?#hco') format('embedded-opentype'),
		url(data:application/x-font-woff;base64,d09GRgABAAAAAHweABIAAAAA56QAAQAAAAB59AAAAioAAAaQAAAAAAAAAABHREVGAABvxAAAAB4AAAAgAQwABUdQT1MAAG/kAAAJtAAAJewFs+hKR1NVQgAAeZgAAABaAAAAgOo0LbVPUy8yAAACEAAAAFAAAABgV2ZmY2NtYXAAAA9sAAACYwAAA1SAqqELY3Z0IAAAE2QAAABCAAAAQgI9FPBmcGdtAAAR0AoaEC7j2uDuUEulpxVwb99wiEB+4Jb2fe9AYkz7Lg87Yl5UslBzZ+micPSU+rGZ/e87zHk9PvpfgFY+1Cug==);
	font-weight: normal;
	font-style: normal;
}

@font-face {
	font-family: 'Archer SSm 8r';
	src: url('BB466FC78313F6AF5.eot');
	src: local('?'),
		url('BB466FC78313F6AF5.eot?#hco') format('embedded-opentype'),
		url(data:application/x-font-woff;base64,d09GRgABAAAAAHsLABIAAAAA6SgAAQAAAAB44AAAAisAAAaQAAAAAAAAAABHREVGAABuTAAAAB4AAAAgAQwABUdQT1MAAG5sAAAKFwAAKNDvP9epR1NVQgAAeIQAAABaAAAAgOo0LbVPUy8yAAACDAAAAFEAAABgWAxmXmNtYXAAAA/0AAACZgAAA1iBBKFQY3Z090NytE+8NkiaT+Q2SAdWFAQe0LUaNijFgHwlgv3sMPQIRromaAw5QXqXytmzeiyPoG4i56MYUddzquqmNTAw7XkrMcprPlC26FewzY9kpuAa1Bw7EF5Jv/8Ro6aSb4RzPq8buZ4DgJPzlOe/Bm/Ii/RS1JuKPJlZl5m5rGZOR2VfGj2qHuxOr7Bm9VbmDHKhJ9ZeiH1fznkyQNeHkiUqAX9LD6TrBlgI1les+GrMDRUwL3HxaGcQFcr7sqg/w6BcM894e3Mm96A5FkWfN60pHyp5MDGT/PkIelxNePTe573eHL8vRS/AZUAQsY=);
	font-weight: normal;
	font-style: normal;
}

-------------------------------------------------------------------------------------------------------------------

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by SimonKunz** [comment]
The same error gets thrown if you try to use ngx-onsenui with an app created with Angular-CLI 1.6.6.
Here's a minimal repo to reproduce the error:

https://github.com/SimonKunz/angularCliCssImportError

It was created with Angular-CLI (in this case with "--style=less") and then following this Guide:
https://onsen.io/v2/guide/angular2/

Within the file node_modules/onsenui/css/onsenui.css there are 3 imports:
@import url("ionicons/css/ionicons.min.css");
@import url("material-design-iconic-font/css/material-design-iconic-font.min.css");
@import url("font_awesome/css/font-awesome.min.css");

If you remove those imports the error will disappear.

**Comment by tonio155** [comment]
I experience the same behaviour as described by @SimonKunz

**Comment by filipesilva** [comment]
@SimonKunz thanks for the reproduction!

Looking at those css imports I'm not really sure they are valid to be honest. @clydin would know more.

**Comment by SimonKunz** [comment]
Works again with CLI 1.6.7

Thanks guys!

**Comment by Drammy** [comment]
I had this problem but found it only happened when I didn't run 'ng serve' from the root of the project.

'ng serve'ing from the root fixed it for me..

**Comment by Nrusingha1** [comment]
background: url('../../../assets/img/angular.png');
