### ISSUE TITLE
Create a website?

### ISSUE THREAD

**Issue by cironunes** [angular/angular-cli#93]
I was thinking about it, maybe we can just kick off a github page for now and then we can improve it over the time?

/cc @IgorMinar

**Comment by IgorMinar** [comment]
I'd prefer to improve the CI setup #90 and integrate karma with the build
pipeline over website.

In other words website would be nice but it's not a high priority for me.
Isn't the Readme.md good enough for now?

**Comment by cironunes** [comment]
Cool! Let's focus on the CI.

For sure, readme.md is enough.

**Comment by Brocco** [comment]
Anyone have a reason to keep this open? IMO a website for the CLI could/should be integrated directly into angular.io
