### ISSUE TITLE
Add different css files conditionally

### ISSUE THREAD

**Issue by mousavidev** [angular/angular-cli#9301]
My app uses different languages and some of them are right-to-left. I have two separate css files; one for LTR and the other for RTL.

how can i conditionally add a css file on component?

**Comment by jburtondev** [comment]
@mousavidev Great question.This issue looks related: https://github.com/angular/angular-cli/issues/4685

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/4685. Please subscribe to that issue for future updates.

**Comment by mousavidev** [comment]
@filipesilva thanks.
