### ISSUE TITLE
ng serve Error while trying to run Fuse Theme

### ISSUE THREAD

**Issue by sanudatta11** [angular/angular-cli#9305]
**Error:-**
`Versions of @angular/compiler-cli and typescript could not be determined.
The most common reason for this is a broken npm install.

Please make sure your package.json contains both @angular/compiler-cli and typescript in
devDependencies, then delete node_modules and package-lock.json (if you have one) and
run npm install again.`

**Package.json** 
`{
  "name": "fuse",
  "version": "1.4.3",
  "dependencies": {},
  "scripts": {
    "test": "gulp test"
  },
  "devDependencies": {
    "browser-sync": "~2.9.11",
    "browser-sync-spa": "~1.0.3",
    "chalk": "~1.1.1",
    "del": "~2.0.2",
    "eslint-plugin-angular": "~0.12.0",
    "estraverse": "~4.1.0",
    "gulp": "~3.9.0",
    "gulp-angular-filesort": "~1.1.1",
    "gulp-angular-templatecache": "~1.8.0",
    "gulp-autoprefixer": "~3.0.2",
    "gulp-clean-css": "^2.0.3",
    "gulp-cssnano": "~2.1.0",
    "gulp-eslint": "~1.0.0",
    "gulp-filter": "~3.0.1",
    "gulp-flatten": "~0.2.0",
    "gulp-htmlmin": "~1.3.0",
    "gulp-inject": "~3.0.0",
    "gulp-load-plugins": "~0.10.0",
    "gulp-ng-annotate": "~1.1.0",
    "gulp-protractor": "~1.0.0",
    "gulp-rename": "~1.2.2",
    "gulp-replace": "~0.5.4",
    "gulp-rev": "~6.0.1",
    "gulp-rev-replace": "~0.4.2",
    "gulp-sass": "~2.1.1",
    "gulp-size": "~2.0.0",
    "gulp-sourcemaps": "~1.6.0",
    "gulp-uglify": "~1.4.1",
    "gulp-useref": "~3.0.5",
    "gulp-util": "~3.0.6",
    "http-proxy-middleware": "~0.9.0",
    "karma": "~0.13.10",
    "karma-angular-filesort": "~1.0.0",
    "karma-coverage": "~0.5.2",
    "karma-jasmine": "~0.3.6",
    "karma-ng-html2js-preprocessor": "~0.2.0",
    "karma-phantomjs-launcher": "~1.0.0",
    "lodash": "~3.10.1",
    "main-bower-files": "~2.9.0",
    "phantomjs-prebuilt": "~2.1.3",
    "uglify-save-license": "~0.4.1",
    "wiredep": "~2.2.2",
    "wrench": "~1.5.8"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}
`

I installed all the packages using npm install --save, npm -g install, bower install. I also did whatever is said like deleting lock file and modules , adding angular/compiler-cli and typescript to package.json . 

If anyone has a solution that would be a great help

**Comment by Bisso1998** [comment]
Dude.
Have a look at the fuse theme.
Maybe you are doing ng serve in angular JS version of fuse theme.
Try following this link: http://fusetheme.com/angularjs/docs/getting-started/installation
It is about running AngularJS fuse theme.
