### ISSUE TITLE
cli doesn't allow you to specify version when creating new app

### ISSUE THREAD

**Issue by dawesi** [angular/angular-cli#9309]
One of the MOST ASKED questions right now is how to create a specific version from the cli. #googleit

This is the last attempt at asking for something ExtJS, React and all the 'great frameworks' out there have had for up to 10 years. It 'was' implemented around 1.x timeframe, but then removed.. #sigh #rookiemistake

With the manic pace that angular has been releasing versions, this is a MUST, it's a make or break feature as people ARE ALREADY building 3rd party tools to build apps, bypassing this cli, another reason to pick React or ExtJS when evaluating a framework. (not being able to create a demo app with the version you want without manual tweaking)

This tool becomes redundant for creating apps without this feature, especially now we have 5 versions in play at the same time.

Can someone explain why --ng2 --ng4 --ng5 isn't in the create-app command?

**Comment by adamlucia** [comment]
+1

**Comment by robwormald** [comment]
This is not something we're likely to support, for a number of reasons. 

Mainly, it's a maintenance nightmare - this has levels upon levels, starting at the way NPM and Yarn work. Add webpack, typescript, etc versioning changes, and very quickly you run into potentially hundreds of possible combinations of dependencies. We are optimizing Angular for the *future*, and pledging to support every possible legacy version is not sustainable. It's also the exact opposite of how we build software at Google, and so it's difficult to justify spending time and *money* on this.

Angular has publicly stated and documented our release and support policy - and we'll be sticking to that for the foreseeable future. Given the limited time and resources available to a project like ours, we'll be focusing effort on making using the *latest* version as simple as possible and making upgrades easy, versus continuing to support legacy code.

Maintaining an end to end build tool for an ecosystem as complex as JS is difficult - Angular CLI, from the beginning, is a "black box" build tool, and the tradeoff is basically : sacrifice some level of control in favor of not having to mess with it. If you're not happy with this tradeoff, all of the component parts can be re-assembled in whatever tool you like - compilation via `ngc` or the standalone `@ngtools/webpack` plugin, `schematics` (the thing that generates projects) can be used standalone, etc.

Additionally, we don't remove old versions from NPM, so at any point, you may `npm install @angular/cli@whateverversionyouwant` and build from there. As far as I'm aware, `create-react-app` (the closest thing to Angular CLI in the react ecosystem) has basically the exact same policy - see https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#updating-to-new-releases
