### ISSUE TITLE
Cache problem when updating angular app

### ISSUE THREAD

**Issue by Gnorro** [angular/angular-cli#9311]
### Versions
```
@angular/cli: 1.4.7
node: 6.11.1
os: win32 x64
@angular/animations: 4.3.2
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/platform-server: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.4.7
@angular/compiler-cli: 4.3.2
@angular/language-service: 4.3.2
typescript: 2.5.3
```

### Repro steps
ng build --prod

### Observed behavior
A production build is created

### Mention any other details that might be useful (optional)

Every time a production build is created, unique css and js files are created and referenced in index.html

The problem is that after having overwrited a production build with a new version, I have to remove cache. If I don't do that, i always see old version or strange behaviours. I know this is not a angular cli strictly related question, but i would like to know which is the best practice to apply when updating a angular app. I have Microsoft IIS as web server. Do I have to prevent always index.html from caching?

Thanks

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Managing cache strategies really depends on the server, and you'd have to check how to do it in IIS. Sorry I can't be of more help.
