### ISSUE TITLE
Error in rxjs operators if installed locally with rxjs 5.5.6

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/angular-cli#9314]
May be related to #9196

I'm trying to `generate` `component` deep inside tree
If I remove remove `node_modules` folder and run `ng g c comp-name` it works fine
But if I install node_modules using yarn and run `ng g c comp-name` it fails with following error

```
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function
```
possibly because I have `rxjs : 5.5.6` in my app
error is coming from https://github.com/angular/angular-cli/blob/d3db0f6c6c2c0970bbea43985a98012629ef3f22/packages/%40angular/cli/tasks/schematic-run.ts#L117

### Versions
```
Angular CLI: 1.6.5
Node: 6.10.1
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.5
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps

* Install rxjs 5.5.6 
* Install @angula/cli 1.6.5
* try to generate component

### Observed behavior
fails to generate component with error message 

```
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function
```

### Desired behavior

Should generate component

### Mention any other details that might be useful (optional)
update package to use lettable `rxjs` operators

**Comment by Brocco** [comment]
This issue has been resolved, please see this comment: https://github.com/angular/angular-cli/issues/9194#issuecomment-360615868

I am closing and locking this issue to consolidate the conversation in the other issue.
