### ISSUE TITLE
Canary testing of angular-cli integration with "real world" projects?

### ISSUE THREAD

**Issue by sinedied** [angular/angular-cli#9317]
Hello `angular-cli` team!

I'm not sure whether this is the right place to talk about this, but let's start here anyways 😉 

I'm the caretaker of [ngX-Rocket](https://github.com/ngx-rocket/generator-ngx-rocket), a Yeoman generator that builds upon your tool and where the main benefits lies in providing:
- frameworks integration: choose Bootstrap 4 with ng-bootstrap and Font Awesome, Angular Material with Angular Flex Layout or Ionic for your UI, comes with baked in i18n with ngx-translate and more
- "Real world" base template: aiming at enterprise projets, it provides an example base app with routing, optional authentication, basic services and so on with a good boilerplate, examples and coding guides to get started quickly
- Multiple targets support: make a simple web app, a PWA, an hybrid app with Cordova or Electron (soon) from the same code base

*(BTW, if you have any valuable feedback or insights regarding this project you're more than welcome, but that's not the point of this issue)*

The point is, while I have been maintaining this project for a year now and tried to keep up with latest tools/frameworks updates (less than a week late most of the time), there have been many times where one or many applications paths generated by our tool were broken due to `angular-cli` updates.
Just for a recent exemple, we had to wait for the recent `1.6.5` to finally have a green build again on all of our apps paths, as there was always something broken following the `1.6.0` release. Note that broken builds also happened in the past on "patch" releases, not only for "minor" release which often brings out many changes on your side.

As we now have an extensive CI based on Travis and Appveyor (as we had a few windows-only issues in the past), generating most of our possible apps paths, I was wondering if you would be interested to collaborate on some canary testing using our tool or CI before releasing new `angular-cli` versions?
Since the apps generated with our tool may be more representative of "real world" projects out there, it may provide complimentary testing in addition to your own CI? That would maybe help detect harder-to-find integrations issues.

It's just an idea, but do you think that would be helpful?

Thanks for your great work anyways! 😃

**Comment by hansl** [comment]
Hi @sinedied,

Yes. We would love to have you try our latest master in your project. We are in contact with the fine folks at renovateapp.com to support canary/snapshot builds.

Basically you can install http://github.com/angular/angular-cli-builds directly as a github repo and that would be the latest state of our master. Using renovateapp that process would become having a PR every now and then that updates your dependencies. You can then use your CI on the PR to validate that you're still compatible with the latest. If not, file an issue here to figure out what's going on :)

What do you think of that process?

**Comment by sinedied** [comment]
Hi @hansl !

This process seems fine for me, but I think you meant http://github.com/angular/angular-cli for the URL to install, am I right? The one in your message gives me a 404.

I'll setup this ASAP, and hope it won't break too often :)

**Comment by clydin** [comment]
The build repo is here and as mentioned, it tracks master: https://github.com/angular/cli-builds

**Comment by alan-agius4** [comment]
Hi, I think there is no further action needed from our end.

As suggested above, you can use the snapshot / nightly builds to test against the upcoming changes. In addition you can setup Renovate Bot, which will create a PR when a new snapshot build is available. Example of such PR: https://github.com/angular/angular-cli/pull/17795

If you need any assistance, please let me us know.

Thanks.
