### ISSUE TITLE
Multiple environment.ts are confusing

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#933]
The current model for environment variables is to have 3 places for files:

1. `/src/environment.ts`
  This is here so when we type in VS Code or our favorite editor we get intellisense. it is *not used* for a build

2. `/config/environment.dev.ts` and `/config/environment.prod.ts`
  This is where we put our env settings for the different environments. It is copied to the `dist/` folder.

3. `/dist/environment.js`
  This is the one that gets run, we do not edit this one.

Follow this scenario ... we need an env variable to point to a web url for our APIs. So we create a 

```
export const environment {
  url: '/api/foo`
};
```

and we put it in `/src/environment.ts`. We then import it with `import { environment } from './environment`. VS Code is happy (as is any tsc compiler command). 

Now we run `ng serve` and browse to the app, and we see an error in the console about how it doesnt know what `url` is. Oops, we didnt put this in the `config/environment.dev.ts` (nor prod) files. OK, so we go do that and now we can run and serve smoothly.

Now ... we add a new env for `showDebugMessages: true`. We set it to `true` for dev and `false` for prod. We recall that we need to do this in the `/config/environment.*.ts` files so we feel we are good. But we forgot we also need to put the same setting in the `/src/environment.ts`. It is not used ... but we need something there. Do we out `false` or `true` for this new setting? It doesn't matter because we are not using it.

```
export const environment {
  url: '/api/foo`,
  showDebugMessages: true
};
```

My point here is that it can be confusing on how to do this and not make a mistake. 

Are there any thoughts on how to prescribe this? Or how to make it easier? Have you considered an interface?  

My Env:
```
$ ng -v
angular-cli: 1.0.0-beta.5
node: 4.2.3
os: darwin x64
```

cc @spboyer

**Comment by spboyer** [comment]
Posted on how to use and the drawbacks here: https://tattoocoder.com/angular-cli-using-the-environment-option/

interface, at least in the current folder structure is not a good workflow. The interface would either need to be at the base root of the project or in a place where referencing it doesn't make sense.

**Comment by SergeySolonko** [comment]
Also it would be great if we could make parent configuration, which ```config/environment.*.ts``` might extend, for instance:
```
config/environment.base.ts
```
```
export var environment = {
API_BASE_URL: "http://example.com/api"
}
```

```
config/environment.dev.ts
```
```
import {extend} from 'lodash';
import {base} from './environment.base';
export var environment = extend(base, {
dev: true
});
```

**Comment by sgbeal** [comment]
@SergeySolonko this doesn't require special angular-cli support, i believe. Simply put `environment.base.ts` in your project's top-level `src` tree (not in `config`), and your extend() example "should" (i believe) work as-is. **Except that...** in 1.0.0-beta.5 `environment.xxx.ts` cannot reference ANY external symbols (e.g. `window`)  and cannot import project-level includes (see ticket #833). Once that ticket is resolved, your feature request should come "for free."

**Comment by SergeySolonko** [comment]
@sgbeal Ok, got it

**Comment by francisoud** [comment]
Hi guys,
Do you know why I can't get it to work with my unit tests ? #1419

**Comment by antonybudianto** [comment]
- Having env's interface is nice to have so that new developer able to know what're needed for each environment
- Even better if the file is gitignored and conform to https://12factor.net/config so that it's scalable

**Comment by randyaa** [comment]
I believe this is resolved with the webpack version of CLI

**Comment by kentoj** [comment]
In Angular 2.0.0 with angular cli:
```
$ ng -v
angular-cli: 1.0.0-beta.16
node: 6.2.2
os: darwin x64
```
There still seems to be an issue with **ng-serve** recognizing the environment module.

When I reference the environment constants in **/path/to/app/environments/environment.ts** from within a file in **/path/to/app/src/app/component/component.ts** 
```
import {environment} from "../../../environments/environment";
```

I get an error when I use **ng-serve** 
```
ERROR in [default] /path/to/project/src/app/shared/auth.service.ts:8:26
Cannot find module '../../environments/environment'.
```

Is this a **ng-serve** problem or me not using it correctly? When I run the app then everything works correctly. Since I am using an environment constant for my API base URL it would be obvious if it was working or not.

**Comment by filipesilva** [comment]
@randyaa I agree. Originally the functionality was more confusing and less documented than it is now.

Documentation can be found https://github.com/angular/angular-cli#build-targets-and-environment-files, and now the third file is not needed.

**Comment by matodrobec** [comment]
@filipesilva  
I would like to import environment to the app.components.ts like 
import { environment } from './environment'; 
therefore I have to create src/app/environment.ts. Why the value of environment.production is still false when I run  ng serve --environment=prod ? I am using angular-cli: 1.0.0-beta.19-3

**Comment by serhiisol** [comment]
@matodrobec Hi, you can create workaround for your case, just simply add ```index.ts``` file in ```environments``` folder with content:
```
export { environment } from './environment';
```

and then you can easily import environment through ```index.ts``` like so

```
```app.component.ts```
```
import {environment} from '../environments';
```

You have to use '../' because ```environments``` folder is in the folder one level up

**Comment by praveen-nuovo** [comment]
I followed the above process, But I got this error --> **_src/app/app.component.ts (17,22): Cannot find namespace 'environment'_**

**Comment by ratbeard** [comment]
Link to docs is https://github.com/angular/angular-cli/blob/9d29cbca0f0c04bb5998cc2cd15180456656ad7e/docs/documentation/build.md

**Comment by Sweetog** [comment]
I am really surprised how hard it is to find a simple tutorial/solution for cmd webpack -p --env.prd true and an environment configuration being available in an Angular2 Typescript app, I developed a very simple solution https://github.com/Sweetog/yet-another-angular2-boilerplate

**Comment by johnpapa** [comment]
the docs are not found here for this ... https://github.com/angular/angular-cli/wiki/build
