### ISSUE TITLE
Moving angular project problem

### ISSUE THREAD

**Issue by ljcucc** [angular/angular-cli#9330]
I would like to moving my project to else folder, but on this way the project with **node_module** folder is too lager that makes moving action spend lots of time. Could I moving project without **node_module** folder then at the new path to run `npm install` to install all module inside **node_module**? Is that the way ?

Thanks! 😄

**Comment by hansl** [comment]
Yes. Delete `node_modules`, move the project, then run `npm install` in the new folder.

**Comment by ljcucc** [comment]
Thanks! hansl
