### ISSUE TITLE
multi script-loader! error in Angular-CLI 1.0.0-beta.28.3

### ISSUE THREAD

**Issue by hayanisaid** [angular/angular-cli#9333]
I get  this Error 
```ERROR in multi script-loader```
when it try to include in Javascript source in angular-cli.json

this is my angular-cli.json file
```"scripts": [
      "node_modules/chart.js/dist/Chart.min.js"
      ],
```
-Angular-CLI version is 1.0.0-beta.28.3

**Comment by hansl** [comment]
Closing this as we do not support beta versions anymore.
