### ISSUE TITLE
Add support for adding features to an existing project

### ISSUE THREAD

**Issue by bibhas2** [angular/angular-cli#9334]
### Versions

```
Angular CLI: 1.6.5
Node: 8.1.4
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
Create a new project like this:

```
ng new my-app --minimal
```

### Observed behavior
A minimal project has no support for unit testing using Karma etc. There is no way to quickly add this feature using Angular CLI.

### Desired behavior
Add a command to add features to an existing project. Something like:

```
ng add-feature --test
```

### Mention any other details that might be useful (optional)

Issue #5431 was opened in a similar vain. But the solution suggested there no longer works.

**Comment by alan-agius4** [comment]
Kindly see https://github.com/angular/angular-cli/issues/13019#issuecomment-440657590
