### ISSUE TITLE
ng eject uses hardcoded project root

### ISSUE THREAD

**Issue by SamVerschueren** [angular/angular-cli#9335]
### Versions
```
Angular CLI: 1.6.5 (e)
Node: 6.9.5
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.5
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.5.3
webpack-dev-server: 2.11.1
webpack: 3.10.0
```

### Repro steps
* ng new myproject
* cd myproject
* ng eject

### Observed behavior

Open `webpack.config.js` and search for the `projectRoot` variable (line 25 on Angular-CLI@1.6.5). The value is a hardcoded string which is the path on the computer which ejected the project. In my case `/Users/sam/Projects/myproject`. Not only the `projectRoot` is hardcoded, also the glob patterns in the `CopyWebpackPlugin` and `CircularDependencyPlugin` are hardcoded.

### Desired behavior
The `projectRoot` should be set to `__dirname` and should be reused in the plugins.

**Comment by SamVerschueren** [comment]
Thanks for fixing @hansl!

**Comment by kaplan81** [comment]
If I may, this fix only affects the project root. All other paths in the Webpack configuration are still hardcoded.
