### ISSUE TITLE
[Feature Request] Angular2 Dependencies Graph

### ISSUE THREAD

**Issue by manekinekko** [angular/angular-cli#934]
Hi there,

I'd like to propose a new feature for the CLI. I made this tool that generates a visual representation of an angular2 application. See the [official page](http://manekinekko.github.io/angular2-dependencies-graph/) for more details. 

See demo below:
![image](https://raw.githubusercontent.com/manekinekko/angular2-dependencies-graph/master/screenshots/dependencies-3.gif)
![image](https://raw.githubusercontent.com/manekinekko/angular2-dependencies-graph/master/screenshots/dependencies-2.png)

This tool currently can be used as a CLI, so we can image it could be added as a [command](https://github.com/angular/angular-cli/tree/master/addon/ng2/commands). The integration with the CLI should be straightforward since the command could just call directly the `ng2-dps` command and pass it the required arguments.

What do you guys think?

**Comment by manekinekko** [comment]
I'm updating tool to support NgModule...
![dependencies](https://cloud.githubusercontent.com/assets/1699357/19057100/e29d97c6-89cd-11e6-8395-7aab7c525dce.png)

**Comment by filipesilva** [comment]
Heya @manekinekko, I'm closing this issue together with the PR. See https://github.com/angular/angular-cli/pull/956#issuecomment-251255962 for reasoning.
