### ISSUE TITLE
Angular 4 not working in IE 11

### ISSUE THREAD

**Issue by imgregduh** [angular/angular-cli#9341]
### Versions
```
cli version : 1.6.4
node version: 8.9.4
npm version: 5.6.0

    "@angular/animations": "^4.4.6",
    "@angular/common": "4.4.4",
    "@angular/compiler": "4.4.4",
    "@angular/core": "4.4.4",
    "@angular/forms": "4.4.4",
    "@angular/http": "4.4.4",
    "@angular/platform-browser": "4.4.4",
    "@angular/platform-browser-dynamic": "4.4.4",
    "@angular/router": "4.4.4",

    "@angular-devkit/core": "0.0.28",
    "@angular/cli": "1.6.4",
    "@angular/compiler-cli": "4.4.4",
    "@angular/language-service": "4.4.4",
```

### Repro steps

* Step 1 ng build 
* Step 2 deploy 
* Step 3 run on IE 11

### Observed behavior

Sometimes it loads in IE sometimes it doesnt, I am not sure what is going on but everytime it doesnt run in IE a guid is printed to the console in red text indicating some sort of error with it.  The console seemed to output this `7c4a924e-e4f5-4290-9256-2cad90fe5f16` in red text with no other errors around it.  Prior to this I was having "Can't execute freed script" error but I set the `__Zone_enable_cross_context_check` option to true and that error went away.  Now I only get this error im reporting off and on after refreshing over and over again.  Sometimes clearing the cache fixes it temporarily.  I have asked other people to try to go to the url and sometimes they can and sometimes they cant.

### Desired behavior
run application on IE 

### Mention any other details that might be useful (optional)

In firefox and chrome it works fine.

**polyfills.ts**
```
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';

import 'core-js/es6/array';
import 'core-js/es7/array';
/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following to support `@angular/animation`. */
import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';

/** ALL Firefox browsers require the following to support `@angular/animation`. **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import './app.globals.ts'; //
import 'zone.js/dist/zone';  // Included with Angular CLI.
/***************************************************************************************************
 * APPLICATION IMPORTS
 */
/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
import 'intl';  // Run `npm install --save intl`.
```

**app.globals.ts**

`(<any>window).__Zone_enable_cross_context_check = true;`

**Comment by hansl** [comment]
Did you just create a new application or was there any changes?

**Comment by imgregduh** [comment]
This was in an existing application.
After tracing where the problem could be it looks like one of my interceptors is not returning to the original callback after i append an authorization token to the request.  I dont think this falls under the cli but angular itself

**Comment by imgregduh** [comment]
Found to be an underlining coding issue deep within code with an error that was being suppressed. Closing issue

**Comment by kammanageswararao** [comment]
HI All,
i am using angular 4 and running the application in local machine & localhost url is not running.

Could you please suggest me to resolve this issue.
