### ISSUE TITLE
ng-eject missing @angular-devkit/core

### ISSUE THREAD

**Issue by cacothi** [angular/angular-cli#9342]
### Versions
```
Angular CLI: 1.6.3
Node: 8.9.3
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.16
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
* Step 1
ng new app-ejected

* Step 2
cd app-ejected

* Step 3
ng eject

### Observed behavior
```
module.js:538
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Dev\Lab\lib-lab\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

### Desired behavior
Be able to eject the project immediately after the creation, without any hassle 

### Mention any other details that might be useful (optional)

To make it working, I do need to run npm i -D @angular-devkit/core and then ng eject

**Comment by blackholegalaxy** [comment]
Encountered the same problem today but using `ng build --prod`

**Comment by runesh** [comment]
Had the same issue.

1. **npm update -g @angular/cli**
2. Edited my package.json file 
    **"@angular/cli": "1.5.5",
      to
    "@angular/cli": "^1.6.5",**

You will get **Angular global mismatch error** if you run ng serve. To resolve that 

3. **Delete node_modules** 
4.  **run npm install**

Should do the trick and work .

If you still face any error try to remove and install the file locally with

npm remove filename

npm install filename

**Comment by aijuthomas** [comment]
npm install @angular-devkit/core --save-dev
