### ISSUE TITLE
 Cannot read property 'exports' of undefined, in typescript.js. Only in --PROD or --AOT builds

### ISSUE THREAD

**Issue by AbeerSul** [angular/angular-cli#9349]
### Versions
`
Angular CLI: 1.6.5
Node: 8.9.1
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.5.1
webpack: 3.10.0`

### Repro steps
run `ng serve --prod `

### Observed behavior
`ERROR in : TypeError: Cannot read property 'exports' of undefined
at resolveNameHelper C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:23432:70)
at resolveName (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:23377:20)
at resolveEntityName (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:24054:26)
at Object.getTypeReferenceSerializationKind (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:43925:31)
at serializeTypeReferenceNode (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:52499:30)
at serializeTypeNode (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:52447:28)
at serializeTypeOfNode (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:52319:28)
at serializeParameterTypesOfNode (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:52354:42)
at addOldTypeMetadata (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:52242:98)
at addTypeMetadata (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:52233:17)
at transformAllDecoratorsOfDeclaration (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:52072:13)
at generateConstructorDecorationExpression (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:52182:40)
at addConstructorDecorationStatement (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:52170:30)
at visitClassDeclaration (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:51413:13)
at visitTypeScript (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:51252:28)
at visitorWorker (C:\Users\....\MyApp\prod\node_modules\typescript\lib\typescript.js:51065:24)

webpack: Failed to compile.`

### Desired behavior
I should be able to build the app in production mode.

### package.json 

{
  "name": "web5",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "aot": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod --aot",
    "test": "echo \"Error: no test... minimal project\" && exit 1",
    "lint": "echo \"Error: no lint... minimal project\" && exit 1",
    "e2e": "echo \"Error: no e2e... minimal project\" && exit 1"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.3",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.29",
    "angular-datatables": "^4.4.1",
    "angular-font-awesome": "^2.0.3",
    "angular2-draggable": "^1.1.0-beta.0",
    "chart.js": "^2.7.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "cuint": "^0.2.2",
    "datatables.net": "^1.10.16",
    "datatables.net-dt": "^1.10.16",
    "enhanced-resolve": "^3.3.0",
    "font-awesome": "^4.7.0",
    "install": "^0.10.2",
    "jquery": "^3.2.1",
    "moment": "^2.19.2",
    "npm": "^5.5.1",
    "postcss-url": "^7.3.0",
    "primeng": "^4.1.2",
    "quill": "^1.3.4",
    "rxjs": "^5.5.2",
    "simple-line-icons": "^2.4.1",
    "webpack": "^3.10.0",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.5",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/datatables.net": "^1.10.7",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.2.16",
    "@types/node": "~6.0.60",
    "bootstrap": "^3.3.7",
    "codelyzer": "~3.2.0",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.1",
    "gulp-sass-variables": "^1.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "2.5.1"
  }
}

### Details
The `ng build` works fine, it's only the production mode or the -aot build.
Note that the erroneous line 23432 in typescript.js is:
`var moduleExports = getSymbolOfNode(location).exports;`

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by AbeerSul** [comment]
Thanks a lot for the fast response. I'll try to replicate it in a repo and post the link to it.

**Comment by AbeerSul** [comment]
Replicating the issue was not easy for me because the project is big and I couldn't find out which part was causing the issue, and all of my sample projects worked just fine.

But luckily after doing some clean up work on the app , I was able to build my project in production mode successfully!

**Here is what I did:**
1. I uninstalled many packages that I didn't use.
2. I'm using Metronic Theme 5, it contains many parts that I don't need, so I deleted all of it's sample pages with their components and modules that I was just using for reference (This is probably the real fix)
3. Updated angular2-draggable package to version "^1.2.0" instead of  "^1.1.0-beta.0"
4. Changed @angular/cli version to "1.6.1", and typescript version to "~2.4.2"
**Then the --prod build succeeded!!**

And here is the final packages.json:

{
  "name": "App",
  "version": "1.0.0",
  "license": "",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "echo \"Error: no test... minimal project\" && exit 1",
    "lint": "echo \"Error: no lint... minimal project\" && exit 1",
    "e2e": "echo \"Error: no e2e... minimal project\" && exit 1"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.3",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@types/jquery": "^3.2.6",
    "angular2-draggable": "^1.2.0",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.7.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "cuint": "^0.2.2",
    "enhanced-resolve": "^3.3.0",
    "font-awesome": "^4.7.0",
    "install": "^0.10.2",
    "jquery": "^3.2.1",
    "moment": "^2.19.2",
    "npm": "^5.5.1",
    "postcss-url": "^7.3.0",
    "quill": "^1.3.4",
    "rxjs": "^5.5.2",
    "simple-line-icons": "^2.4.1",
    "typescript-formatter": "^5.2.0",
    "xxhashjs": "^0.2.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.1",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.1",
    "gulp-sass-variables": "^1.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

package.json changes can be viewed here:
[https://www.diffchecker.com/e3I60W71](url)

I hope that helps someone :)
