### ISSUE TITLE
.gitignore for eclipse is missing.

### ISSUE THREAD

**Issue by reflexdemon** [angular/angular-cli#935]
1. OS?  Windows 7 x64bit

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
```
C:\>node --version
v4.4.4
```

While opening the project using eclipse there were files like .project .classpath tat are getting generated and can we add them to the `ng new` and `ng init` commands `.gitignore` file?

This might be an enhancement request.

**Comment by reflexdemon** [comment]
Also a quick suggestion if we can have a default `README.md` file then we might use them as a initial help document for the developers who are starting to use `angular2` for the first time.

some examples like
```
ng serve
```

```
ng test
```
etc can be shared.
eg:
https://github.com/reflexdemon/slush-angular-gulp/blob/master/templates/app/README.md
https://github.com/yeoman/generator-angular/blob/master/templates/common/root/README.md

**Comment by filipesilva** [comment]
These are nice ideas. Would you be willing to do PRs for them?

For the project README.md, you can add it in `addon/ng2/blueprints/ng2/files/` .The special string `<%= jsComponentName %>` will be replaced by the project name on generation.
