### ISSUE TITLE
Error by ng serve

### ISSUE THREAD

**Issue by dhampall** [angular/angular-cli#9352]
I have installed angular with npm command and then i wanted to serve this application 
i gave ng serve command then i got following errors
ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/themes/custom-material-
theme.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at loadLoader (D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\loader-runner\lib\LoaderRunner.js
    at iteratePitchingLoaders (D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\loader-runner\lib\LoaderRunner.js
    at D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\loader-runner\lib\LoaderRunner.js:173:18
 @ ./src/themes/custom-material-theme.scss 4:14-215
 @ multi ./node_modules/font-awesome/css/font-awesome.css ./node_modules/material-design-icons/iconfont/material-icons.css ./nod
ERROR in ./src/app/components/formular/formularBody.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at loadLoader (D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\loader-runner\lib\LoaderRunner.js
    at iteratePitchingLoaders (D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\loader-runner\lib\LoaderRunner.js
    at D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\loader-runner\lib\LoaderRunner.js:173:18
 @ ./src/app/components/formular/formularBody.ts 204:21-51
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Failed to compile.
please help me to sort out this problem
Thanks & Regards
Dhampall

**Comment by ochstobi** [comment]
You don't have "node-sass" module installed

**Comment by hansl** [comment]
Closing this as answered.

**Comment by dhampall** [comment]
i tried installing node-sass module i recieved follwing error

> node-sass@4.7.2 install D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-57_binding.node":

tunneling socket could not be established, statusCode=407

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.7.2 postinstall D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files (x86)\nodejs\node.exe D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
gyp verb cli   'D:\\_GIT\\IncidentBroker\\IndicentBrokerPhoneFormular\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Python27\python.exe C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.4
gyp verb command install [ '8.9.4' ]
gyp verb install input version string "8.9.4"
gyp verb install installing version: 8.9.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.9.4
gyp verb ensuring nodedir is created C:\Users\pdamd\.node-gyp\8.9.4
gyp verb created nodedir C:\Users\pdamd\.node-gyp\8.9.4
gyp http GET https://nodejs.org/download/release/v8.9.4/node-v8.9.4-headers.tar.gz
gyp verb download using proxy url: "http://proxyits.itscare.prod.dom:8080/"
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.9.4' ]
gyp verb remove using node-gyp dir: C:\Users\pdamd\.node-gyp
gyp verb remove removing target version: 8.9.4
gyp verb remove removing development files for version: 8.9.4
gyp ERR! configure error
gyp ERR! stack Error: tunneling socket could not be established, statusCode=407
gyp ERR! stack     at ClientRequest.onConnect (D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\tunnel-agent\index.js:166:19)
gyp ERR! stack     at Object.onceWrapper (events.js:319:30)
gyp ERR! stack     at emitThree (events.js:136:13)
gyp ERR! stack     at ClientRequest.emit (events.js:217:7)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:472:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at addChunk (_stream_readable.js:263:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:250:11)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:208:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "D:\\_GIT\\IncidentBroker\\IndicentBrokerPhoneFormular\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN enoent ENOENT: no such file or directory, open 'D:\_GIT\IncidentBroker\IndicentBrokerPhoneFormular\package.json'
npm WARN @angular/flex-layout@2.0.0-beta.12 requires a peer of @angular/core@~5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@2.0.0-beta.12 requires a peer of @angular/common@~5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-particle@1.0.4 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN IndicentBrokerPhoneFormular No description
npm WARN IndicentBrokerPhoneFormular No repository field.
npm WARN IndicentBrokerPhoneFormular No README data
npm WARN IndicentBrokerPhoneFormular No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ochstobi** [comment]
Maybe you are behind a proxy in your company that doesn't allow downloading the binary node.
You should download it manually and host it on an server that is accessible.
Set the sass binary path to your machine:
`set SASS_BINARY_SITE=http://youradress/files/node-sass-bin`
On your server in the node-sass-bin folder you place the version folder (v4.7.2) and inside this the binary that is needed (win32-x64-57_binding.node).

Or you place the file in `npm-cache/node-sass/v4.7.2/win32-x64-57_binding.node`
