### ISSUE TITLE
Angular CLI Build Failed with Unexpected token: operator (>) 

### ISSUE THREAD

**Issue by kamprasad2007** [angular/angular-cli#9353]
### Versions
```
angular/cli : 1.0.3
node : 6.11.1
os : win32 x64
```

### Repro steps
When executing  **ng build -aot false -prod** it gives following error.

### Observed behavior
```
> ERROR in vendor.394aa10abde0566efdcb.bundle.js from UglifyJs
> Unexpected token: operator (>) [vendor.394aa10abde0566efdcb.bundle.js:56810,35]
```

### Desired behavior
After investigation found out that source-map V0.7.0 is the issue and when downgrade to 0.6.1 it works as expected. Anyone faced this issue?

**Comment by filipesilva** [comment]
You're using a very old version of Angular CLI. Updating to the latest version should fix that problem.

The original issue for it is https://github.com/angular/angular-cli/issues/7532, and it was fixed by https://github.com/angular/angular-cli/pull/7610.
