### ISSUE TITLE
npm install -g @angular/cli uglifyjs-webpack-plugin@0.4.6 postinstall error

### ISSUE THREAD

**Issue by Atanas9708** [angular/angular-cli#9355]
### Versions
node 9.4.0
npm 5.6.0
windows 10
```

### Repro steps
npm install -g @angular/cli

### Observed behavior
```
I get the following error :

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\@angular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 (node_modules\@angular\cli\node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn C:\WINDOWS\system32\cmd.exe;C:\Program Files\Git\cmd; ENOENT

npm ERR! file C:\WINDOWS\system32\cmd.exe;C:\Program Files\Git\cmd;
npm ERR! path C:\WINDOWS\system32\cmd.exe;C:\Program Files\Git\cmd;
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe;C:\Program Files\Git\cmd;
npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe;C:\Program Files\Git\cmd; ENOENT
npm ERR!
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{username}\AppData\Roaming\npm-cache\_logs\2018-01-24T10_24_30_851Z-debug.log
```

**Comment by rbndm** [comment]
Do you have Git installed on your machine? Looks like if it's looking for it...

**Comment by Atanas9708** [comment]
When i do git --version in the cmd i get this: git version 2.16.0.windows.2

**Comment by rbndm** [comment]
Would you share the contents of C:\Users{username}\AppData\Roaming\npm-cache_logs\2018-01-24T10_24_30_851Z-debug.log ?

**Comment by Atanas9708** [comment]
[2018-01-24T10_24_30_851Z-debug.log](https://github.com/angular/angular-cli/files/1661098/2018-01-24T10_24_30_851Z-debug.log)

**Comment by rbndm** [comment]
Are you using npm from cmd.exe, or are you using another CLI (Cygwin, ...)?

**Comment by Atanas9708** [comment]
@rbndm I'm using npm from cmd.exe

**Comment by rbndm** [comment]
Do these paths/files exist on your system? 

C:\WINDOWS\system32\cmd.exe;
C:\Program Files\Git\cmd

**Comment by Atanas9708** [comment]
I have C:\Program Files\Git\cmd and C:\WINDOWS\system32. Maybe i should add \cmd.exe to the second path ?

**Comment by rbndm** [comment]
I don't use Windows 10, but I don't recommend you adding cmd.exe to this folder. Do you have cmd.exe on your PATH? Maybe you should try this first ...

**Comment by Atanas9708** [comment]
I changed  C:\WINDOWS\system32 to C:\WINDOWS\system32\cmd.exe and tried installing angular cli again but i got the same error as before :(

**Comment by Atanas9708** [comment]
Bump ... i still haven't figured it out...

**Comment by hansl** [comment]
Latest version of Angular CLI uses uglifyjs-webpack-plugin 1.1.x. Could you upgrade to CLI 1.6, and try again please?

Closing this as answered. If you still have an issue, please file a new issue and follow the template (including the Angular CLI version, which you could replace with the content of your package.json if you cannot npm install). Thakns!

**Comment by Atanas9708** [comment]
@hansl I don't have the angular/cli on my machine ... i can't even install it thats the problem

**Comment by Atanas9708** [comment]
I finally found a solution that worked for me. I just had to remove all of the values in ComSpec except for %SystemRoot%\system32\cmd.exe
