### ISSUE TITLE
Display different sizes images on different devices

### ISSUE THREAD

**Issue by PrashantPandit** [angular/angular-cli#9357]
How can we display big size image on different devices like desktop, laptop, tab, mobile etc without losing its aspect ratio and originality? Sometime it may happen that images displayed on desktop devices but if we change the device to tab or mobile image look like compressed. 
**Is there any way to get the same image with the same resolution for different devices according to device aspect ratio.**

**Comment by StevenFewster** [comment]
Not really the place for this question, try https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by deebloo** [comment]
@petarblazevski the issue tracker here is for bugs/issues with the cli tool itself.

**Comment by petarblazevski** [comment]
@deeblooI think you mentioned the wrong person :)

**Comment by deebloo** [comment]
@pedrobuzzi I sure did. fixed

**Comment by hansl** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by PrashantPandit** [comment]
Hey, thanks for all reply.
