### ISSUE TITLE
What exactly happens when running ng build --prod?

### ISSUE THREAD

**Issue by TheParad0X** [angular/angular-cli#9362]
Hello,
What is the difference between

`ng build --prod `

and

`ng build --aot --environment=prod --output-hashing=all --sourcemaps=false --extract-css=true --named-chunks=false --build-optimizer=true`

?

When using ng build --prod my app does not load on Firefox 50.1.0 (error "This is not defined"), **but when using all flags combined, it works.**

**Comment by clydin** [comment]
You're missing `--target=production`.

Also, there appears to be an issue tracking that Firefox error here: https://github.com/angular/angular-cli/issues/9340.  Closing this as a duplicate.
