### ISSUE TITLE
angular-cli not working generaly - please for help

### ISSUE THREAD

**Issue by kroupa1985** [angular/angular-cli#9369]
### Versions
Angular CLI: 1.6.3
Node: 9.4.0
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.16
typescript: 2.4.2
webpack: 3.10.0

Node:
v9.4.0

npm --version:
5.6.0

Windows 7

### Repro steps

* installed angular-cli, didnt get it right with npm, some of the depencies didnt exist, i downloaded angular-cli from github, changed the links to the depencies manually in package-lock.json to the specified version of that package, 3 depencies didnt exist, managed to install cli tool with this procedure
* created a simple project with ng new. used in it router capatibilities
* project succsefully compiled
* first error: querystring doesnt have function unescape. isshue: the generated project uses to querystring functions. first is installed in node_modules (v0.20) the second - right one is the node's primitive module query string. corrected the error so i copied the right querystring code in the installed one - it worked
*second error: etag uses safe-buffer module. got this error:

TypeError: argument entity must be string, Buffer, or fs.Stats
    at etag (c:\php\gamesonline\node_modules\etag\index.js:84:11)

corrected the file node_modules/etag/index.js so i required the safe-buffer module. it worked but i think not correctly, because i got this error:

_http_outgoing.js:749
      throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'first argument',
      ^
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string
or Buffer
    at ServerResponse.end (_http_outgoing.js:749:13)

i think there are again some depencies isshues.

### Observed behavior
described in the top

### Desired behavior
no depencies ishhues, no same module names and overwites, app should be compiled correctly and app shoul be working

### Mention any other details that might be useful (optional)
I think the cli-tool is completly broken or i somehow didnt installed it correctly, there should be no reason installation via npm should be broken, there should be no resaon app throws so many depency isshues. I am sure, there is something wrong with my angular-cli tool, i suppose i didnt instaled it right, but for me there was no other way. In the procedure of this project I am doubting the cli tool works at all anywhere

Please provide me some info about correct way to install, when you go thrue this post. Sorry for my bad english

**Comment by hansl** [comment]
> installed angular-cli

Did you use `@angular/cli` ?  We do not publish `angular-cli` as a package anymore. It's been deprecated.

**Comment by kroupa1985** [comment]
Yes, i used @angular/cli.

I did not installed it from npm, because of some depency problems, the installation didn't go through, i downloaded from github, change depency package locations (used same versions, just different links). I thinks installatation via npm is broken

**Comment by filipesilva** [comment]
Installing from github is only useful for developing the CLI itself. If you're not familiar with Angular CLI development I don't really recommend installing from github.

You're also using Node 9.4.0. We don't test or officially support that version since it's not a LTS (long term support) version. You can see which versions of node are LTS at https://github.com/nodejs/Release. We currently support Node 6.9+ and 8.x+.

I think it's very likely that the dependency problems you ran into initially were due to Node 9, and then the followup errors were due to a badly setup development setup.

Using Node 8 instead should take care of those problems. I recommend updating to NPM 5.6 regardless because NPM 5.0 to 5.5 had problems in Windows.

Hope this helps.

**Comment by kroupa1985** [comment]
An are you guarantiing me that the ng tool will work. I am will only believe you if you are using it yourself. I had node 8 installed then i switched to 9.4. I am really doubtfull that @angular/cli actualy works. But if i see it so nobody complains about same problems, so it must be something on my side. Later on when i get home i will use your advice, and try to reinstall everything. Hope it works

**Comment by kroupa1985** [comment]
So i tried and so it works. Thanks! Now I can work,.

**Comment by filipesilva** [comment]
Glad to hear that!
