### ISSUE TITLE
Does ngTools/webpack support loadchildren routes that are functions?  We can only get it working with strings

### ISSUE THREAD

**Issue by light24bulbs** [angular/angular-cli#9372]
I work at a major company that funds angular development.  

Long story short, we are doing some fancy lazy loading with the router.  Rather than use a string, we use a function that returns a promise.  Works great in JIT mode, and it's working well in AOT with the old ngc-webpack plugin, but the ngTools/webpack compiler complains no matter how we organize things.  Does the ngTools plugin support using functions for lazy routes, or does it only support using strings that it can evaluate at build time?

@sokra

**Comment by filipesilva** [comment]
It only supports string that evaluate at build time. There is a tracking issue to allow loading NgModules outside of the router and static analysis we do: https://github.com/angular/angular-cli/issues/9343
