### ISSUE TITLE
Provide serve defaults for app

### ISSUE THREAD

**Issue by Sudheer-Reddy** [angular/angular-cli#9375]
<pre><code>
[x] Feature request
</code></pre>

My use case is i've multiple apps say runtime, showcase etc.., but most of the times i use showcase app. `Can we have config option under defaults for serve to specify default app name to serve`.

<pre><code>
...
"defaults": {
   "serve": {
      "app": "showcase"
   }
}
...

**Comment by filipesilva** [comment]
You can now use the `defaultProject` toplevel property in `angular.json` for this purpose.
