### ISSUE TITLE
Include 3rd party lib with non amd module definition

### ISSUE THREAD

**Issue by crebuh** [angular/angular-cli#938]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Ubuntu 14.04.

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

angular-cli: 1.0.0-beta.5
node: 4.4.4
os: linux x64

> ---------------------------------------------------------------

Hi,

so far working with the angular cli and system.js was great. For a project I have to use a ePub reader library called ePub.js (https://github.com/futurepress/epub.js/)

The problem is that the lib comes without module or just partial module support (I included an example how the library is doing the export later on). In comparison to this, including other 3rd party libraries like ng2-bootstrap or ng2-tranlsate was very easy. 

During the build all js-Files related to ePub.js are copied to the public/assets/js folder (there is also no npm package ...). First of all I have to fix the following two issues

1) Loading the Library with system.js (therefore I did the following adjustments)

      /** Map relative paths to URLs. */
    const map: any = {
      'moment': 'vendor/moment/moment.js',
      'ng2-bootstrap': 'vendor/ng2-bootstrap',
      'ng2-translate': 'vendor/ng2-translate',
      'angular2-jwt': 'vendor/angular2-jwt',
      'epub': 'assets/js/epub'
    };

    /** User packages configuration. */
    const packages: any = {
      'epub': {
        format: 'amd',
        defaultExtension: 'js',
        main: 'epub.js'
      },
    };

Here is an excerpt from the library how the module is exported: 

     	//exports to multiple environments
	if (typeof define === 'function' && define.amd) {
		//AMD
		define(['rsvp', 'jszip', 'localforage'], function(RSVP, JSZip, localForage){ return ePub; });
	} else if (typeof module != "undefined" && module.exports) {
		//Node
		global.RSVP = require('rsvp');
		global.JSZip = require('jszip');
		global.localForage = require('localforage');
		module.exports = ePub;
	}

So I assume amd and als cjs is supported?

2) Import within Typescript

In my bookreader component then I want to import the library with

     import * as ePub from 'epub/epub';

My IDE tells my that no module is found in that path. I tried to add the following to typings.d.ts

     declare var ePub:any;

Also the build dies with the following message:

      Error: Typescript found the following errors:
      /home/ch/app/tmp/broccoli_type_script_compiler-input_base_path-E3ln2pmw.tmp/0/src/app/reader/reader.component.ts (2, 23): Cannot find module 'epub/epub'.

Do I have to add my own typing defintion or how can I import the library within typescript?

As said import other 3rd party libs like ng-translate is a cakewalk compared to my problem here. Each hint is appreciated!

**Comment by filipesilva** [comment]
Hm, this is a hard one. That package doesn't really work with being imported, it seems.

I think you will have to load the module as a global one via SystemJS to force it to load it as if it was in a script tag. See https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-formats

Then you will need to call to declare the typing as you have there, use it in your code *without* importing it. When your code runs on the browser, it should pick up on the global vars the library uses.

Hope this is of help :/

**Comment by crebuh** [comment]
@filipesilva thx for your response!

I got it working now, there is just one error in the console left. maybe I can also fix this issue. here is my setup so far.

** typing.d.ts **

declare epub as module to allow the import in typescript

    declare module 'epub' {
        var ePub: any; // any var name here really
        export = ePub;
    }

** system-config.ts**     

the thing I had to do here is to point rvsp also the the epub.js file, because the library is included within the file it self 

    const map: any = {
        'epub': 'vendor/epub.js/build/epub.js',
        'rsvp': 'vendor/epub.js/build/epub.js',
        'jszip': 'vendor/epub.js/build/libs/zip.min.js',
        'localforage': 'vendor/epub.js/build/libs/localforage.min.js'
    };

    const packages: any = {
        'epub': {
            format: 'cjs',
            defaultExtension: 'js',
            main: 'epub.js'
        },
        'rsvp': {
            format: 'cjs',
            defaultExtension: 'js',
            main: 'epub.js'
        }
    };
    
** reader.component.ts **

now I'm able to import the lib within typescript like this

     import * as ePub from 'epub';
     
and use the methods and so on

    export class ReaderComponent {

        book: any

        showBook(id) {
            this.book = ePub('assets/books/' + id + '.epub', { fixedLayout: true });
            this.book.renderTo('bookReader');
        }

        prevPage() {
            this.book.prevPage();
        }

        nextPage() {
            this.book.nextPage();
        }
    }

As said it is working now, but I still get errors in the console. The annoying thing with zone.js is that you dont know which library or party of the whole application is really causing the problem.

    zone.js:461 Unhandled Promise rejection: require is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: require is not defined(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
    zone.js:463 Error: Uncaught (in promise): ReferenceError: require is not defined
    
Any advice to solve this problem? I hope this also helps others, who want to include 3rd-party libs.

**Comment by filipesilva** [comment]
Glad to hear it's working! 

Regarding the outstanding error, `require is not defined` seems to be related with node's `require('lib')`, perhaps there's some dynamic requires going on on the libs?
