### ISSUE TITLE
Heroku Not Deploy

### ISSUE THREAD

**Issue by edersonsergiocoelho** [angular/angular-cli#9382]
I do not know what I do to get the deploy of my application. I have this error that I can not get out of it, I have tried thousands of settings and it does not work, giving npm install locally and it works perfectly does anyone help me find what is still missing for my application to upload?

My GitHub where is the project: https://github.com/edersonsergiocoelho/ESCPizzariaView

       
       > escpizzaria-view@0.0.0 postinstall /tmp/build_b9896d524767fa55002d5e6e6a8cd6ff/edersonsergiocoelho-ESCPizzariaView-16e307f
       > ng build --aot -prod
       
       sh: 1: ng: not found
       npm ERR! file sh
       npm ERR! code ELIFECYCLE
       npm ERR! errno ENOENT
       npm ERR! syscall spawn
       npm ERR! escpizzaria-view@0.0.0 postinstall: `ng build --aot -prod`
       npm ERR! spawn ENOENT
       npm ERR!
       npm ERR! Failed at the escpizzaria-view@0.0.0 postinstall script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /app/.npm/_logs/2018-01-25T12_49_56_454Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

{
  "name": "escpizzaria-view",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "node server.js",
    "build": "ng build",
    "postinstall": "ng build --aot -prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "bootstrap": "^4.0.0-beta.3",
    "ngx-bootstrap": "^2.0.0-rc.0",
    "ngx-toastr": "^8.1.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "peer": "^0.2.8",
    "popper": "^1.0.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.5",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  },
  "engines": {
    "node": "8.9.4",
    "npm": "5.5.1"
  }
}

 const express = require('express');
 const app = express();
 
 app.use(express.static(__dirname + '/dist'));
 app.listen(process.env.PORT || 8080);

**Comment by clozanosanchez** [comment]
The problem is that devDependencies are not installed by Heroku. A simple workaround is to move _@angular/cli_ and _@angular/compiler-cli_ to dependencies object.

**Comment by edersonsergiocoelho** [comment]
Thank you very much, I managed to solve what you said and gave more error, I had to put the TypeScrit depot in the depots too.

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
