### ISSUE TITLE
Could not find a declaration file for module 'source-map'

### ISSUE THREAD

**Issue by symphony2014** [angular/angular-cli#9384]
When I try to build angular-cli, I got this error, anyone can help me?
### Versions
```

node --version
V8.9.3
Windows10
```

### Repro steps

* Step 1
```npm run build```
* Step 2
* Step 3

### Observed behavior
```

  Compilation error.
packages/@ngtools/webpack/src/plugin.ts(5,28): error TS7016: Could not find a declaration file for module 'source-map'. 'E:/angular-cli/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm install @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
packages/@ngtools/webpack/src/refactor.ts(5,53): error TS7016: Could not find a declaration file for module 'source-map'. 'E:/angular-cli/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm install @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
```

**Comment by filipesilva** [comment]
This doesn't happen in our CI (at least at this point in time) and we rebuild from source there, so I'm not sure what the cause is. Have you tried reinstalling your node modules? You might have old dependencies there.

**Comment by zwwtj2014** [comment]
@symphony2014 Maybe package `@types/source-map` installed into node_modules has no type declaration file `index.d.ts` because of incorrect version. And you can try to set `@types/source-map` with version `0.5.2` instead of `^0.5.x`.

**Comment by cgatian** [comment]
Running into the same issue. Looks like source-map isnt including its definition files in its release, but it should? 

![image](https://user-images.githubusercontent.com/1752170/43776875-3db04a74-9a1f-11e8-9092-e8016a42dbb5.png)

As a workaround, added the following to a `typings.d.ts` file:
```
declare module 'source-map' {
  export interface Position {
    line: number;
    column: number;
  }
}
```

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
