### ISSUE TITLE
No matching version found for @schematics/angular@~0.1.17

### ISSUE THREAD

**Issue by Matmo10** [angular/angular-cli#9389]
### Versions
```
1.7.0-beta.2, 1.6.6
```

### Repro steps
`npm install` with `@angular/cli` at 1.7.0-beta.2

### Observed behavior
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @schematics/angular@~0.1.17
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@angular/cli'
npm ERR! notarget 
```

### Desired behavior
The mentioned version of `@schematics/angular` should be available on npm.

### Mention any other details that might be useful (optional)
The same things happens with `1.7.0-beta.1`, although it fails looking for `@schematics/angular@~0.1.16`

**Comment by clydin** [comment]
The latest available version of a package can be verified by using the `www.npmjs.com` website.
In this case, https://www.npmjs.com/package/@schematics/angular indicates version 0.1.17 as the latest which matches the requested version.

A package can sometimes take some time to propagate  especially when proxies are involved.

**Comment by Matmo10** [comment]
You're right, just a corporate proxy issue. Sorry for the troubles!
