### ISSUE TITLE
Wiki: stories universal rendering missing step

### ISSUE THREAD

**Issue by goelinsights** [angular/angular-cli#9393]
### Repro steps
Step 5: Setup a webpack config to handle this Node server.ts file and serve your application!
Now that we have our Node Express server setup, we need to pack it and serve it!

Create a file named webpack.server.config.js at the ROOT of your application.

This file basically takes that server.ts file, and takes it and compiles it and every dependency it has into dist/server.js.

./webpack.server.config.js (root project level) (code snipped)

Almost there!

Now let's see what our resulting structure should look like, if we open up our /dist/ folder we should see:

/dist/
   /browser/
   /server/
To fire up the application, in your terminal enter
```
node dist/server.js
```

### Observed behavior

If you type in node dist/server.js this doesn't do anything as server.js has not yet been created

### Desired behavior
Missing an instruction on using webpack to generate server.js.  Suggest edit to the following:

To fire up the application, in your terminal enter
```
**npm run webpack:server**
node dist/server.js
```

### Mention any other details that might be useful (optional)

Minor issue, just trying to improve the documentation and save someone a few minutes of confusion

**Comment by JosephGreevy** [comment]
If you follow along with the tutorial it instructs you to run
`npm run build:ssr` 
but it did definitely confuse me for a while.

**Comment by c00** [comment]
This could definitely use some clarification. Where it says "if we open up our /dist/ folder we should see: [...]" the dist folder is still empty, as the command for putting stuff in it is later on in the document.

**Comment by alan-agius4** [comment]
Universal doc is now available at https://angular.io/guide/universal
