### ISSUE TITLE
add the support to rename main.bundle to the name of the app specified in the config file

### ISSUE THREAD

**Issue by lcervo** [angular/angular-cli#9396]
My team is working on a big project using .net core mvc and angular. The project is structured like this:
-- ClientApp
---- node_modules
---- app
------ module1
-------- module1.component
-------- module1.module
-------- module1.routing.module
------ module2
------ moduleN
---- .angular-cli.json
---- [other angular conf files]
-- Controllers
---- Module1Controller
---- Module2Controller
---- ModuleNController
-- Views
---- Module1
------ Index.cshtml
---- Module2
------ Index.cshtml
---- ModuleN
------ Index.cshtml
---- Shared
------ _Layout.cshtml
-- wwwroot
---- dist

The requirements are that we cannot have a massive single page application and we have to load the angular module (e.g. module1) in the its own mvc view. The routing is managed  by .net core and in the 
module1.routing.module there is only a single entry

```
const ROUTES: Routes = [
    { path: 'module1', component: Module1Component },
 ];
```

### Versions
```
.Net Core v.2.1.4
Angular CLI: 1.6.5
Angular : 5.2.1
Node: 8.6.0
Typescript: 2.6.1
OS: Window Server 2016 x64

```

### Repro steps
The angular **module1** component has the selector set to 'app-module1'
**Module1Controller**
The view _Layout.cshtml renders all the common javascript and styles files (inline.bundle, polyfills.bundle, style.css, etc..)
The view **Module1** renders the <app-module1></app-module1> and in the razor scripts section the compiled angular javascript file for the specific module
Before moving to angular cli we were using webpack and, when building the app, we were able to go create a bundle for each module (e.g. module1.bundle.js, module2.js, moduleN.js in the wwwroot/dist folder) and using the webpack  watch functionality  (integrated in dotnet) working for the typescript files for each module so we didn't have rebuild the files all the time.
Now with angular cli it seems that we cannot achieve the same result. The .angular-cli.json has an app for each module but we can only watch and use one module at a time using the ng build -w method.
I was able to create a script that after bundling a module it renames the main.bundle.js in the specific module (e.g. module1.bundle.js, module2.bundle.js, etc.) but every time we make a change to a typescript file we need to re-run the script and it takes 10 minutes.
So... for now we will use the ng build -w for a single module and when we need to work on another module we will kill the script and run it again using another module name.

### Desired behavior
I was wondering if it's possible to extend the angular cli configuration to support to rename the main.bundle using the name of the app specified in the config file (e.g. { "outputFileName" : "module1" } ).
If you have any suggestions are really welcome.

Thanks.

L.

**Comment by cnicho** [comment]
We also have this requirement. I have achieved this with systemjs. Now moving to Angular CLI and Webpack I find it is not directly supported. For now I have to perform multiple builds and rename and move main bundle out of output folder each time.

**Comment by trsh** [comment]
Also need this.

**Comment by naveedahmed1** [comment]
@lcervo for .net core, have you tried new .net core template? its based on Angular CLI.

**Comment by kyliau** [comment]
@lcervo Sorry I know it has been some time, could you please provide us with more info on what you're trying to achieve?
AST.NET Core now has a standalone CLI tool for Angular projects.
https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio
Please let us know if that satisfies your use case, and if not, please reopen this issue for further discussion. Thank you!
