### ISSUE TITLE
ng help command is not working after @angular/cli installed using npm.please how to slove this problem

### ISSUE THREAD

**Issue by VARUMOHITH** [angular/angular-cli#9397]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Guest>npm install -g @angular/cli --save
C:\Users\Guest\AppData\Roaming\npm\ng -> C:\Users\Guest\AppData\Roaming\npm\node
_modules\@angular\cli\bin\ng
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\@an
gular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

+ @angular/cli@1.6.6
updated 777 packages in 271.468s

C:\Users\Guest>ng help
'ng' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Guest>

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by VARUMOHITH** [comment]
thank you silva
