### ISSUE TITLE
CLI 1.6.6 seems not installing all dependencies

### ISSUE THREAD

**Issue by dklmuc** [angular/angular-cli#9398]
### Versions
```
Angular CLI: 1.6.6
Node: 8.9.0
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cli: 1.6.6
@ngtools/json-schema: 1.1.0
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps

* Updated existing 1.6.5 to 1.6.6 (following the update guide)
* ng serve &  build not working (dev and prod)
* no errors from npm install output

### Observed behavior
ng serve results in error:
```
ERROR in Error: No NgModule metadata found for 'AppModule'.
```
ng serve --prod results in error:
```
ERROR in : TypeError: Cannot read property 'flags' of undefined
```
Compared to the ng -v output of a new project there seems to be missing a lot of stuff:
```
Angular CLI: 1.6.6
Node: 8.9.0
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.6
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

**Comment by shashankinbab** [comment]
I am also facing same issues with version 1.6.6.  Even tried to create fresh project using ng new.  

ERROR in  app/src/main.ts
Module build failed: Error:  app\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

In Existing project getting No NgModule metadata found for 'AppModule'.

Typescript Version 2.6.2
Node Version v8.9.4
OS: win32 x64
Angular: 5.2.2

**Comment by micgid** [comment]
Angular CLI: 1.7.0-beta.2
Node: 8.9.1
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cdk: 5.1.0
@angular/cli: 1.7.0-beta.2
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.0-beta.2
@schematics/angular: 0.1.17
@schematics/package-update: 0.0.7
typescript: 2.5.3
webpack: 3.10.0

I have the same issue with cli 1.6.5 but not all the time. 
If I change a space or anything in a file while ng serve is running, it build.

I tried with cli@next and the build pass even the ng serve

**Comment by dklmuc** [comment]
Solved by:
- delete node_modules
- delete package-lock.json
- clean install
