### ISSUE TITLE
Commands to read/add/remove services to component constructor parameters ?

### ISSUE THREAD

**Issue by chaouiy** [angular/angular-cli#9400]
Life would be easier if we have Angular-cli commands to manipulate services use in components constructors. It is a recurrent need, I have 96 components and 48 services. It is painful to manually browse files to manage associations between components and services

**Comment by filipesilva** [comment]
Heya, can you give a couple of examples of how these would work for the cases you think they would be useful?

**Comment by amineparis** [comment]
**Add** 
`ng attach --service <path_to_service> --component <path_to_component> --modifier <private(default)|public|protected>`
this adds a service in the component constructor and adds import it

**Remove**
`ng detach --service <path_to_service> --component <path_to_component>`
this removes a service from the component constructor and removes import statement

**Comment by alan-agius4** [comment]
Hi @chaouiy, thanks for this feature request. However, currently this is not part of the Angular CLI roadmap.

Let's close it for now, and revisit in the future if we see that this is needed.
