### ISSUE TITLE
generate module with routing creates module file in unexpected location

### ISSUE THREAD

**Issue by jsa-unity** [angular/angular-cli#9416]
### Versions
```
Angular CLI: 1.6.6
Node: 8.9.0
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.6.6
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps
* Step 1
```
ng g m foo --routing
```

### Observed behavior
```
create src/app/foo/foo-routing.module.ts (246 bytes)
create __path__/__name@dasherize@if-flat__/__name@dasherize__.module.ts (267 bytes)
```

### Desired behavior
```
create src/app/foo/foo-routing.module.ts (246 bytes)
create src/app/foo/foo.module.ts (267 bytes)
```

**Comment by rdrrichards** [comment]
I cannot repro this. I followed the steps, and it worked without issue. The only difference is I have Node version 8.9.3. 

`create src/app/foo/foo.module.ts (187 bytes)`

Consider uninstalling and reinstalling the CLI.

**Comment by jsa-unity** [comment]
Thank you. It uninstalling and reinstalling worked.

**Comment by JoA-MoS** [comment]
I also experience the same issue but uninstalling and reinstalling the CLI did not work. I just manually move and renamed the files.

I have a dated project I know it needs to be updated here is my config
Global Angular CLI version - 7.3.5
Project Angular CLI version - 1.7.4
