### ISSUE TITLE
How to make a PR to wiki?

### ISSUE THREAD

**Issue by stevermeister** [angular/angular-cli#9417]
Could you please create/document the way how we can help you fixing wiki misprints/broken links/other?

**Comment by realappie** [comment]
I think it's not possible, I would propose to move the wiki to a `docs` folder or something.

**Comment by devoto13** [comment]
Here are markdown files, from which Wiki is generated: https://github.com/angular/angular-cli/tree/master/docs/documentation

**Comment by stevermeister** [comment]
@devoto13 thank you!
