### ISSUE TITLE
loading `ModuleFactory` issue

### ISSUE THREAD

**Issue by WagnerMoreira** [angular/angular-cli#9420]
I am submitting this issue here only because I've already tried stackoverflow and reddit, I believe the people more attached to Angular/cli will understand that better

### Versions
```
ngular CLI: 1.6.6
Node: 8.9.1
OS: darwin x64
Angular: 5.2.2
... common, compiler, compiler-cli, core, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.6
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
My purpose: create a library that provides a modal, so I could just pass a component to load inside a modal in my app

I combined this [tutorial][1] (how to dynamically load components) and this [tutorial][4] (how to build and publish an angular module)
and with that I am trying to create a library to load components inside a modal, here's my [repo][3]

When my app tries to load the `ModuleFactory`, it's returning this error:
[![enter image description here][5]][5] 

As I am passing the `#ModalModule` it should be loading the component factory correctly:
    // This array defines which "componentId" maps to which lazy-loaded module.
    const manifests: DynamicComponentManifest[] = [
      {
        componentId: 'modal',
        path: 'dynamic-modal', // some globally-unique identifier, used internally by the router
        loadChildren: './dynamic-modules/modal/modal.module.ts#ModalModule',
      },
    ];

this behavior can be seen in the [dynamically loading components with ng cli tutorial's demo project][2]
In the tutorial's demo project webpack is producing a js bundle for that module, and that's not happening in my repo[![enter image description here][6]][6]

I believe it has to do with ng cli, or I could be doing something wrong here, can anyone tell?

  [1]: https://blog.angularindepth.com/dynamically-loading-components-with-angular-cli-92a3c69bcd28
  [2]: https://github.com/devboosts/dynamic-component-loader
  [3]: https://bitbucket.org/wmoreiradev/component-loader/
  [4]: https://medium.com/@cyrilletuzi/how-to-build-and-publish-an-angular-module-7ad19c0b4464
  [5]: https://i.stack.imgur.com/yMdto.png
  [6]: https://i.stack.imgur.com/0F2KR.png

### Observed behavior
it's all in the above description

### Desired behavior
to load a `ModuleFactory` properly

**Comment by filipesilva** [comment]
Heya, you're trying to mix a couple of different approaches that do not mix so well. Specifically, Angular CLI only supports code splitting via the router. We do have a discussion issue for this in https://github.com/angular/angular-cli/issues/9343, which has more context and a bunch of other related issues linked.

**Comment by WagnerMoreira** [comment]
right, I've read the issues thank you,  there is any way to achieve my goals with the existing Angular state? I believe many users would benefit of my library since modals are being used in tons of projects

**Comment by filipesilva** [comment]
No, such support is not currently in Angular CLI. There is a workaround as described in that issue at 
>This has as a consequence that people have to use a fake route if they want to split at the NgModule boundary; e.g. AIO here. Although this work, it's a bad pattern that users shouldn't have to do.

But I wouldn't recommend doing that.
