### ISSUE TITLE
Removing Incremental Versions from Git

### ISSUE THREAD

**Issue by webbbret** [angular/angular-cli#9425]
### Versions
1.7.0-beta.1

### Repro steps
Try making 1.7.0-beta.1 a dependency in your project

### Observed behavior
You keep removing incremental versions

### Desired behavior
Please dont remove incremental versions from git. Our package.json does not use * or ^ for various reasons. When we move forward with a version you push, it appears that the previous one disappears.

### Mention any other details that might be useful (optional)
Not sure why we kept 1.7.0-beta.0 and got rid of 1.7.0-beta.1. Will beta.1 be available when you push .3??

**Comment by filipesilva** [comment]
I'm not sure what you mean, we never unpublished any version from npm. If you run `npm info @angular/cli versions` you will see all versions available there:

```
// ...
  '1.5.5',
  '1.5.6',
  '1.6.0-beta.0',
  '1.6.0-beta.1',
  '1.6.0-beta.2',
  '1.6.0-rc.0',
  '1.6.0-rc.1',
  '1.6.0-rc.2',
  '1.6.0',
  '1.6.1',
  '1.6.2',
  '1.6.3',
  '1.6.4',
  '1.6.5',
  '1.6.6',
  '1.7.0-beta.0',
  '1.7.0-beta.1',
  '1.7.0-beta.2' ]
```

You mention git but I don't see how this git (https://github.com/angular/angular-cli/) has anything to do it either. We don't remove tags here, but regardless it's a monorepo and not suitable to install as a npm dependency.

You might have have kind of npm proxy that's removing old versions as they are resolved to new ones.
