### ISSUE TITLE
Invalid link for Angular Package Format

### ISSUE THREAD

**Issue by JSMike** [angular/angular-cli#9426]
### Versions
```
Angular CLI: 1.6.6
Node: 6.9.4
OS: linux x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.6
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
run `ng serve` with a package that is using .ts files

### Observed behavior
error displayed from: 
```
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
```

Link forwards to error message:
```
https://goo.gl/jB3GVv – this goo.gl shortlink has been disabled. It was found to be violating our Terms of Service. Click here and here for more information about our terms and policies respectively.
```

### Desired behavior
Link to documentation

### Mention any other details that might be useful (optional)
The link that needs to be fixed can be located here
https://github.com/angular/angular-cli/blob/213802bdea2b03d6a8d01edc431dbb2015d27f91/packages/%40ngtools/webpack/src/angular_compiler_plugin.ts#L854

**Comment by filipesilva** [comment]
I'm not sure what that error message means, but I tried opening it up right now with in a chrome tab and it showed the document correctly. Maybe it was fixed meanwhile. Are you still seeing the error message?

**Comment by JSMike** [comment]
@filipesilva looks like it's been fixed.
