### ISSUE TITLE
.editorconfig indent size not respected when changing it to another value

### ISSUE THREAD

**Issue by alexolivas** [angular/angular-cli#943]
This may be more of a question rather than an issue: From the .editorconfig file, I updated the default indent_size from 2 to 4, now every time I generate a new component, route etc all the files that are generated or updated by the cli use the previous default indent size of 2 instead of 4. Is this by default or is there some other setting I have to set? Or a bug?

Note: I did not change anything else in the .editorconfig file, I was testing it out with the stock values the only update was the indent_size.

**Comment by filipesilva** [comment]
The `.editorconfig` file doesn't actually affect code generation by the CLI, it's just for editors. We generate it mostly as a nice-to-have.
