### ISSUE TITLE
ng2-tel-input For Intrnational phone input 

### ISSUE THREAD

**Issue by yogesh-sadhokar** [angular/angular-cli#9433]
I have used this library.
And getting following error.
Can anyone help to find solution for this error.

[ng2-tel-input](https://www.npmjs.com/package/ng2-tel-input)

 Uncaught Error: Template parse errors:
Can't bind to 'ng2TelInputOptions' since it isn't a known property of 'input'. ("
<input type="text"
  ng2TelInput
  [ERROR ->][ng2TelInputOptions]="{initialCountry: 'in'}"
  (hasError)="hasError($event)"
  (ng2TelOutput)="getNu"): ng:///AppModule/IocComponent.html@21:2
    at syntaxError (compiler.js:485)
    at TemplateParser.parse (compiler.js:24660)
    at JitCompiler._parseTemplate (compiler.js:34471)
    at JitCompiler._compileTemplate (compiler.js:34446)
    at eval (compiler.js:34347)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:34347)
    at eval (compiler.js:34217)
    at Object.then (compiler.js:474)
    at JitCompiler._compileModuleAndComponents (compiler.js:34216)

**Comment by yogesh-sadhokar** [comment]
I have a requirement for international telephone input with dorpdown having country maps.
can anyone suggest working library for angular 2 application?

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
