### ISSUE TITLE
Paste event doesn't work on IE11

### ISSUE THREAD

**Issue by brivvirs** [angular/angular-cli#9437]
### Versions
```
Angular CLI: 1.6.6
Node: 8.1.3
OS: win32 x64
Angular: 5.2.2
```

### Repro steps

* Step 1
Add (paste) event on template element `(paste)="onPaste()`
```
<input (paste)="onPaste()" />
```
 or add `HostListener`
```
@HostListener('paste', [])
    onPaste() {
        await this.service.Do();
    }
```
* Step 2
Paste anything into the input field.

 link to a sample repo: https://github.com/brivvirs/angularclipastebug

### Observed behavior

Throws an exception on IE11
```
ERROR Error: Uncaught (in promise): Error: Invalid argument.
...
```

### Desired behavior

The same as on the Chrome.

**Comment by wKoza** [comment]
`await` with IE ? no ... but you can add a polyfill for that

**Comment by brivvirs** [comment]
I have enabled a polyfills for IE and `await` works perfectly on IE11.
```
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
```

**Comment by wKoza** [comment]
It isn't a Angular-cli issue

`paste` event is not compatible with IE : https://developer.mozilla.org/en-US/docs/Web/Events/paste

**Comment by brivvirs** [comment]
Not sure whether `cli` is missing polyfills or its a global angular issue.
Also IE11 supports a `paste` event.
https://caniuse.com/#search=paste

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/).

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ubien** [comment]
The trick is IE11 won't fire paste event unless it's on an element with `contenteditable=true`.  A workaround is to make a hidden contenteditable element and listen for ctrl+v then do `nativeElement.focus()` on the hidden element.  Then `document:paste` fires as expected.
