### ISSUE TITLE
91% additional chunk assets processingError: ENOENT: no such file or directory, open 'D:\ANGUALRJS2 PROJECTS\NG2CLIAPP01\src\node_modules\bootstrap\dist\js\bootstrap.min.js'

### ISSUE THREAD

**Issue by subhashekkaluru** [angular/angular-cli#9438]
i am facing this issue in angular cli :

"91% additional chunk assets processingError: ENOENT: no such file or directory, open 'D:\ANGUALRJS2 PROJECTS\NG2CLIAPP01\src\node_modules\bootstrap\dist\js\bootstrap.min.js'"

could you please guide how solve ,
thank you....

**Comment by pumano** [comment]
looks you have wrong path to `bootstrap.min.js` in your `.angular-cli.json`. You should use ../ before node_modules. 

example:
```
...
"scripts": [
                "../node_modules/core-js/client/shim.min.js",
                "../node_modules/mutationobserver-shim/dist/mutationobserver.min.js",
                "../node_modules/@webcomponents/custom-elements/custom-elements.min.js",
                "../node_modules/@clr/icons/clr-icons.min.js",
                "../node_modules/web-animations-js/web-animations.min.js"
            ],
...
```

**Comment by filipesilva** [comment]
Closing as answered by @pumano , thanks!

**Comment by rahul-maurya1992** [comment]
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "ng2angle"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "app/core/preloader/preloader.scss",
        "styles.scss"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "app/core/preloader/preloader.js",
        "../node_modules/flot/jquery.flot.js",
        "../node_modules/jquery.flot.tooltip/js/jquery.flot.tooltip.js",
        "../node_modules/flot/jquery.flot.resize.js",
        "../node_modules/flot/jquery.flot.pie.js",
        "../node_modules/flot/jquery.flot.time.js",
        "../node_modules/flot/jquery.flot.categories.js",
        "../node_modules/jquery.flot.spline/jquery.flot.spline.js",
        "../node_modules/jquery-sparkline/jquery.sparkline.js",
        "../node_modules/easy-pie-chart/dist/easypiechart.js",
        "../node_modules/chart.js/dist/Chart.bundle.js",
        "../node_modules/jqcloud2/dist/jqcloud.js",
        "../node_modules/bootstrap/js/modal.js",
        "../node_modules/bootstrap/js/dropdown.js",
        "../node_modules/bootstrap/js/tooltip.js",
        "../node_modules/summernote/dist/summernote.js",
        "../node_modules/moment/min/moment-with-locales.min.js",
        "../node_modules/fullcalendar/dist/fullcalendar.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}

Here is my .angular-cli.json file code but still got the same error.

**Comment by gravindran2412** [comment]
Same issue:

angular.json
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "prime-ui": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/prime-ui",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss",
              "./node_modules/font-awesome/css/font-awesome.css"
            ],
            "scripts": [
              "./node_modules/jquery/dist/jquery.min.js",
              "./node_modules/jquery-ui/jquery-ui.js"
            ]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "prime-ui:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "prime-ui:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "prime-ui:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "prime-ui-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "prime-ui:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "prime-ui:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "prime-ui"
}`

Command: ng build
Error:  91% additional asset processing scripts-webpack-pluginENOENT: no such file or directory, open 'C:\Users\graveendran\eclipse-workspace\node_modules\jquery\dist\jquery.min.js'
Error: ENOENT: no such file or directory, open 'C:\Users\graveendran\eclipse-workspace\node_modules\jquery\dist\jquery.min.js'

**Comment by pumano** [comment]
Guys, please stop spaming here, issue was closed 7 months ago, and problem solved! Check comments please, before "same problem".

**Comment by francoeder** [comment]
You're right, Puman.
For people who have the error after adding "../", I suggest checking the path of the file.
That's right, open the terminal and make sure you can access the file path.

**Comment by duvangil** [comment]
It worked for me like this.

example: 

`              "./node_modules/jquery/dist/jquery.min.js",
              "./node_modules/tether/dist/js/tether.min.js",
              "./node_modules/bootstrap/dist/js/bootstrap.min.js"`

**Comment by Abdulzabeer** [comment]
92% additional asset processing scripts-webpack-plugin✖ ｢wdm｣: Error: ENOENT: no such file or directory, open '/home/eunioalab/App/node_modules/jquery/dist/jquery.js'

help me i am getting this error

**Comment by ajaymarathe** [comment]
> 92% additional asset processing scripts-webpack-plugin✖ ｢wdm｣: Error: ENOENT: no such file or directory, open '/home/eunioalab/App/node_modules/jquery/dist/jquery.js'
> 
> help me i am getting this error

Hi 
maybe file path issue, or you have to install jquery, first install jquey `npm i jquery` then give correct path of jquery.
hope it helps.
