### ISSUE TITLE
WARN [Chrome 50.0.2661 (Windows 7 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.

### ISSUE THREAD

**Issue by alexkibler** [angular/angular-cli#944]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Win7x64

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
```
angular-cli: 1.0.0-beta.5
node: 4.4.4
os: win32 ia32
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
App created with CLI. About 15 components/routes.  `ng test` gives the above error.

**Comment by filipesilva** [comment]
Can you provide a repo where this error happens? I can't seem to reproduce it just by adding components and routes.

**Comment by alexkibler** [comment]
Thanks for the comment.  I'm actually going to close this, as it seems to just be that my work pc is so slow that it takes more than 10 seconds to start running tests, which makes karma time out.  I don't think it's a CLI issue.
