### ISSUE TITLE
Trying to implement Hot Module Replacement...error TS2345 argument of type is not assignable.

### ISSUE THREAD

**Issue by dtabaka** [angular/angular-cli#9443]
### Versions
```
Angular CLI: 1.6.3
Node: 6.11.2
OS: win32 x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

* Step 1
Looking to implement Hot Module Replacement with ng serve but there is no documentation here https://github.com/angular/angular-cli/wiki/serve other then the --hmr option listed
* Step 2
Had to install another dependency to hopefully get this to work from https://github.com/angular/angular-cli/wiki/stories-configure-hmr

### Observed behavior
Following the instructions above on ng serve --hmr I get 
```
ERROR in src/main.ts(19,26): error TS2345: Argument of type '() => Promise<void | NgModuleRef<AppModule>>' is not assignable to parameter of type '() => Promise<NgModuleRef<any>>'.
  Type 'Promise<void | NgModuleRef<AppModule>>' is not assignable to type 'Promise<NgModuleRef<any>>'.
    Type 'void | NgModuleRef<AppModule>' is not assignable to type 'NgModuleRef<any>'.
      Type 'void' is not assignable to type 'NgModuleRef<any>'.

```

### Desired behavior

*It would be nice if what else is needed would be included right in the ng serve docs
*Is this https://github.com/gdi2290/angular-hmr the only option to add implement HMR with ng serve?

**Comment by dtabaka** [comment]
Update:

I resolved the error by changing updating the **main.ts** code in https://github.com/angular/angular-cli/wiki/stories-configure-hmr

from...
`hmrBootstrap(module, bootstrap);`

to..
`hmrBootstrap(module, <any>bootstrap);`

**Comment by dereklin** [comment]
I am following the doc https://github.com/angular/angular-cli/wiki/stories-configure-hmr

And I see the README at https://github.com/gdi2290/angular-hmr

I couldn't trigger the life cycle methods like hmrOnDestroy following the doc,

Instead, I have to 

```
import { hmrModule } from '@angularclass/hmr';

if (environment.hmr) {
  if (module['hot']) {
    bootstrap().then((ngModuleRef: any) => {
      return hmrModule(ngModuleRef, module);
    });
  } else {
    console.error('HMR is not enabled for webpack-dev-server.');
    console.log('Are you using the --hmr flag for ng serve?');
  }
} else {
  bootstrap();
}
```

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
