### ISSUE TITLE
Build AOT fails without any error after migration to Angular 5

### ISSUE THREAD

**Issue by DzianisUkrainets** [angular/angular-cli#9447]
### Build AOT fails without any errors after migration to Angular 5

I migrated my app from angular 4.3.6 to angular 5.2.2 with angular cli 1.6.5. `ng serve` works fine, but when i try to `ng build --aot --prod` or `ng build --prod` build breaks and i get this this message `10% building modules 2/2 modules 0 active` without any errors.

if i try `ng serve --aot`, build is freazing with message `13% building modules 26/26 modules 0 active`

How to fix it or even how to get some errors to understand what is wrong ?

### Versions
```
angular-cli: 1.6.6
angular 5.2.2
node: 6.11.0
os: windows 10
```

### Repro steps
`ng build --aot --prod` or `ng build --prod`

### Message
`10% building modules 2/2 modules 0 active`

### Package.json
```
  "dependencies": {
    "@angular/animations": "5.2.2",
    "@angular/common": "5.2.2",
    "@angular/compiler": "5.2.2",
    "@angular/core": "5.2.2",
    "@angular/forms": "5.2.2",
    "@angular/http": "5.2.2",
    "@angular/platform-browser": "5.2.2",
    "@angular/platform-browser-dynamic": "5.2.2",
    "@angular/router": "5.2.2",
    "angular2-moment": "1.8.0",
    "chart.js": "2.6.0",
    "core-js": "2.5.3",
    "date-fns": "1.28.5",
    "file-saver": "1.3.3",
    "font-awesome": "4.7.0",
    "gojs": "1.7.6",
    "lodash": "4.17.4",
    "moment": "2.20.1",
    "moment-duration-format": "2.2.1",
    "ng2-trim-directive": "2.1.2",
    "primeng": "5.0.2",
    "rxjs": "5.5.6",
    "video.js": "6.2.0",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.6.6",
    "@angular/compiler-cli": "5.2.2",
    "@angular/language-service": "5.2.2",
    "@types/date-fns": "2.6.0",
    "@types/file-saver": "0.0.1",
    "@types/jasmine": "2.5.53",
    "@types/lodash": "4.14.67",
    "@types/moment-duration-format": "1.3.8",
    "@types/node": "8.0.6",
    "@types/videojs": "5.16.2",
    "codelyzer": "4.1.0",
    "expose-loader": "0.7.4",
    "jasmine-core": "2.9.1",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.2.2",
    "ts-node": "4.1.0",
    "tslint": "5.9.1",
    "typescript": "2.5.3"
  }
```

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by DzianisUkrainets** [comment]
@filipesilva I migrated my app from angular 4 to angular 5. The problems is that i don't have any error message, it is hard to find breaking point. Maybe is it possible to get some logs? it will be helpfull.

**Comment by DzianisUkrainets** [comment]
@filipesilva i try to reduce my app to minimal app
