### ISSUE TITLE
Unable to install angular cli

### ISSUE THREAD

**Issue by pratish945** [angular/angular-cli#9450]
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-DBGfHx1KZ/hTNFbI8p5b2r3n13r3ICBEsPkbrZ187f7+C7SuIca7VHelSKN2gRjrFS7qM1xp2qAwz8a6XTBQ9w== integrity checksum failed when using sha512: wanted sha512-DBGfHx1KZ/hTNFbI8p5b2r3n13r3ICBEsPkbrZ187f7+C7SuIca7VHelSKN2gRjrFS7qM1xp2qAwz8a6XTBQ9w== but got sha512-cgSf5HIgXymDIwf17P2vrhd+dAUFJ4bIg2yNdSjO4vWVy6ooWzD/gTBV2hsc+Rrsw26SzdpnkYYQDYSbggVWaQ==. (121408 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/webpack-dev-server: Integrity verification failed for sha512-DBGfHx1KZ/hTNFbI8p5b2r3n13r3ICBEsPkbrZ187f7+C7SuIca7VHelSKN2gRjrFS7qM1xp2qAwz8a6XTBQ9w== (C:\Users\prati\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\0c\11\9f1f1d4a67f8533456c8f29e5bdabde7d77af7202044b0f91bad9d7cedfefe0bb4ae21c6bb5477a548a3768118eb152eea335c69daa030cfc6ba5d3050f7)

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
