### ISSUE TITLE
bundle size with prod and sourcemaps vs prod

### ISSUE THREAD

**Issue by mouradghafiri** [angular/angular-cli#9457]
Hello;
well thanks for that great cli; and let us go straight to the point;

I have an app and I have done two builds with those commands
**ng build --prod**
Resultat : **_main.bundle.js is 4,94 MB_**
![withoutsourcemaps](https://user-images.githubusercontent.com/6994544/35634616-643d411c-06ac-11e8-9fb0-44fdeb123822.PNG)

**ng build --prod --sourcemaps**
Resultat:  **_main.bundle.js is 2.82MB_**
![ws](https://user-images.githubusercontent.com/6994544/35634889-176e1a90-06ad-11e8-91fd-45ae5cb303f7.PNG)

is that normal?

package.json
`"dependencies": {
    "@angular/animations": "5.0.0",
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@angular/router": "5.0.0",
    "angular-2-local-storage": "1.0.1",
    "bulma": "0.6.2",
    "bulma-tooltip": "0.1.2",
    "core-js": "2.5.3",
    "devextreme": "17.2.5",
    "devextreme-angular": "17.2.5",
    "leaflet": "1.3.1",
    "leaflet-draw": "^0.4.14",
    "ngx-breadcrumbs": "0.0.3",
    "osmtogeojson": "3.0.0-beta.2",
    "rxjs": "5.5.6",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.6.6",
    "@angular/compiler-cli": "5.0.0",
    "@angular/language-service": "5.0.0",
    "@types/jasmine": "2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "6.0.96",
    "codelyzer": "4.1.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "4.1.0",
    "karma": "1.7.0",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.4.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.2",
    "ts-node": "3.2.0",
    "tslint": "5.7.0",
    "typescript": "2.4.2"
  }`

**Comment by filipesilva** [comment]
I tried testing this on a project and didn't find a difference in JS bundle sizes between `ng build --prod` and `ng build --prod --sourcemaps`. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by mouradghafiri** [comment]
the cause was devextreme imports, it is fixed
Thank you
