### ISSUE TITLE
When i try to run  ng serve then it  will give me the error "ERROR in ./src/main.ts Module build failed: [object Object]  @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts ERROR in ./src/polyfills.ts Module build failed: [object Object]  @ multi ./src/polyfills.ts" Please help me to solve this error

### ISSUE THREAD

**Issue by Awais512** [angular/angular-cli#9460]
Angular CLI: 1.6.5
Node: 8.9.4
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.2.4
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

**Comment by filipesilva** [comment]
I think you're having some weird errors and can't debug it, and so, understandably, you're frustrated. But this is a tracker for bugs and feature requests. If we can we also try to help with support requests. We're very lucky to have awesome community members that also spend time trying to help people here in the issue tracker.

But we can't really help much at all if you don't fill in the issue template. I read your issue and have no idea what's going wrong and how to help you. And when other users search the issue tracker and see your issue, it also doesn't help them.

So I think the best thing to do is to close this issue, and ask you to open a new one. In that new one please fill in the issue template and give us an idea of what's happening and how to reproduce it. That way we'll have a chance to help you.
