### ISSUE TITLE
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. " after upgrading to angular5

### ISSUE THREAD

**Issue by sri1987** [angular/angular-cli#9466]
Hi , i have recently upgraded to angular5 and since then my protractor tests are failing with :

Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:469:11)
        at tryOnTimeout (timers.js:304:5)
        at Timer.listOnTimeout (timers.js:264:5)

These tests were working before upgrading. 
Highly appreciate any suggestions. 

Thanks

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by sri1987** [comment]
@filipesilva , thank you for the response. After a lot of analysis , we discovered that , chrome 64 is the culprit. I have also upgraded to chrome 64 and tests were failing since then.
