### ISSUE TITLE
Fails to auto-refresh with baseHref

### ISSUE THREAD

**Issue by vitaly-t** [angular/angular-cli#9469]
With CLI v1.6.7, generate a new app, and within `.angular-cli.json` set a base Url:

```js
   "apps": [
    {
      "baseHref": "suburl"
```

The auto-refresh no longer works in the browser. Any change in the code, the app reloads and instantly fails to find any bundle files. We have to restart the app to make it work again.

It worked in earlier versions of Angular CLI.

**Comment by clydin** [comment]
Following the instructions given, this does not appear reproducible with 1.6.7.

Can you run `ng --version` within the project exhibiting the problem?  Also the full command line used to execute `ng serve`?

**Comment by clydin** [comment]
This appears to have been solved in the latest version of the CLI.  If the problem persists with the latest version, please open a new issue detailing the problem.

**Comment by vitaly-t** [comment]
Sorry for not returning to it earlier.

> Following the instructions given, this does not appear reproducible with 1.6.7.

You need to make a basic app that uses a base URL, whatever extra change is needed for it, so you can see that extra URL section as your base URL address.

> Can you run ng --version within the project exhibiting the problem?

```
Angular CLI: 1.6.8
Node: 8.9.4
OS: win32 x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.1
@angular/cli: 1.6.8
@angular/material: 5.2.1
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0
```

> This appears to have been solved in the latest version of the CLI

Do you have a link to the fix that may be related to this?
