### ISSUE TITLE
1.7.0 beta.3 ng serve - Fonts fail to load

### ISSUE THREAD

**Issue by slubowsky** [angular/angular-cli#9471]
### Versions
```
Angular CLI: 1.7.0-beta.3
Node: 9.4.0
OS: win32 x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.0-beta.3
@angular-devkit/build-optimizer: 0.2.0
@angular-devkit/core: 0.2.0
@angular-devkit/schematics: 0.2.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.0-beta.3
@schematics/angular: 0.2.0
@schematics/package-update: 0.2.0
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps

* Include font awesome exactly as described here - https://github.com/angular/angular-cli/wiki/stories-include-font-awesome

### Observed behavior
Font fails to load:
```
GET http://localhost:4200/fonts/fontawesome-webfont.woff2?v=4.7.0 net::ERR_ABORTED
GET http://localhost:4200/fonts/fontawesome-webfont.woff?v=4.7.0 net::ERR_ABORTED
GET http://localhost:4200/fonts/fontawesome-webfont.ttf?v=4.7.0 net::ERR_ABORTED
```

### Desired behavior
Fonts should load as they do in versions < 1.7.0

### Mention any other details that might be useful (optional)
First noticed in 1.7.0 beta 0. Possibly relates to now closed issue
https://github.com/angular/angular-cli/issues/9297 where this issue was mentioned as well.

**Comment by quangcm** [comment]
I have a long story during these days.
First I have problem with `ng build --prod` time (very slow, it took about 50min), I read from issues list and found the answer is upgrading angular cli to 1.7.0-beta.2.
So I upgraded angular cli to 1.7.0-beta.3 today and meet another problem.
Here is the log from console

    Failed to decode downloaded font: http://my-domain/fonts/fontawesome-webfont.woff2?v=4.7.0
    OTS parsing error: invalid version tag

How can I apply the fix above for my project (I can't wait to the next release version of angular cli)?

**Comment by Manikandan-CloudevTech** [comment]
Hi,

I'm getting this warning with Font awesome 1.7.0 version. 

Failed to decode downloaded font: http://my-domain/fonts/fontawesome-webfont.woff2?v=4.7.0
OTS parsing error: invalid version tag

This error is appearing only with prod build and not on localhost

Any suggestions that how can i resolve it..?
