### ISSUE TITLE
Failing to build scss with version 1.6.7

### ISSUE THREAD

**Issue by teving** [angular/angular-cli#9477]
### Versions
Angular CLI: 1.6.7
Node: 9.5.0
OS: win32 x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 5.1.1
@angular/cli: 1.6.7
@angular/material-moment-adapter: 5.1.1
@angular/material: 5.1.1
@ngtools/json-schema: 1.1.0
typescript: 2.7.1
webpack: 3.10.0

### Repro steps
* Step 1: Create sass file importing other sass files:
styles/main.scss:
@import "@angular/material/prebuilt-themes/indigo-pink.css";
@import "colours";
@import "variables";
@import "mixins";

* Step 2: Update the .angular-cli.json to point to them:
{
    ...
    "apps": [
        ...
        "styles": [
            "styles/main.scss"
          ]
    ],
    "defaults": {
        "styleExt": "scss",
        "component": {}
     }
}

* Step 2
Run ng serve or ng build

### Observed behavior

ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles/main.scss
Module build failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.isAbsolute (path.js:460:5)
    at Promise.all.paths.map.file ({fullPath}\node_modules\postcss-import\index.js:187:24)
    at Array.map (<anonymous>)
    at Promise.resolve.then.paths ({fullPath}\node_modules\postcss-import\index.js:186:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
 @ ./src/styles/main.scss 4:14-198
 @ multi ./src/styles/main.scss

### Desired behavior

Should build correctly

### Mention any other details that might be useful (optional)
This works in at least @angular/cli versions 1.6.4-1.6.6

**Comment by sandangel** [comment]
can you try with typescript 2.6?
2.7 come with some breaking change that my break the build

**Comment by rhefner** [comment]
I saw the same thing today when I upgraded, I went back to Typescript@2.6.2 and had the same results.  I remembered that there was some `angular-cli` upgrade in the recent past where I had to change my imports to not use `~` as a prefix, so I put them back and everything is fine now for me.  May want to give it a try?
