### ISSUE TITLE
Add support for typescript 2.7.1

### ISSUE THREAD

**Issue by dhniels** [angular/angular-cli#9479]
### Versions
```
<!--
Angular CLI: 1.6.7
Node: 9.3.0
OS: darwin x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.7.1
webpack: 3.10.0
-->
```

### Error Mesage:
Updated all my npm packages yesterday which updated typescript to 2.7.1. Angular CLI now produces this warning:

```
@angular/compiler-cli@5.2.3 requires typescript@'>=2.4.2 <2.7.0' but 2.7.1 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.


    npm install typescript@'>=2.4.2 <2.7.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".
```

### Repro steps
Found when running `ng build --watch` on latest typescript version 2.7.1

### Desired behavior
Update @angular/cli to support typescript 2.7.1 should resolve the issue?

**Comment by clydin** [comment]
That warning is intended to indicate that Angular itself does not yet officially support TypeScript 2.7.

Angular 5.0 officially supports 2.4
Angular 5.1 officially supports 2.5
Angular 5.2 officially supports 2.6

**Comment by wendelstam** [comment]
Are the any page/file that contains the most up to date list of version mappings i.e. basically an Angular/Typescript compatibility chart? (Like the comment by @clydin above).

**Comment by devoto13** [comment]
@wendelstam You can find mostly up to date version [here](https://github.com/angular/angular-cli/blob/1972bd954300be12efb6c917556fbc3a48d003f9/packages/%40angular/cli/upgrade/version.ts#L169-L175).
