### ISSUE TITLE
[Feature Request] Comment stub generation with Copyright, author and date

### ISSUE THREAD

**Issue by st-clair-clarke** [angular/angular-cli#948]
angular-cli generates many five files per component. After the generation a developer has to go through each to add a comment with typical Copyright, author +- date the file was generated.

I am proposing a feature request where angular-cli could do this with an option to NOT generate this contents for those who do NOT require such comments.

Consider the .html component view comment below

This could easily be altered for .ts, .spec.ts in the generation process.

The generation could be done for all artifacts generated by the angular-cli.

Please let me know what you think.

I think angular-cli WILL BE THE DEFACTOR STANDARD FOR angular2 development in the near future. Congrats to all the contributors.

**Comment by filipesilva** [comment]
I believe this is a bit outside the scope of the CLI, and there are no plans at the moment for such feature. If this changes, this issue will be updated.
