### ISSUE TITLE
component generated in incorrect directories

### ISSUE THREAD

**Issue by smlombardi** [angular/angular-cli#9480]
### Versions
```
Angular CLI: 1.6.6
Node: 6.11.2
OS: darwin x64
Angular: 5.1.3
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, platform-server
... router

@angular/cli: 1.6.6
@angular/compiler-cli: 5.2.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.24
@angular-devkit/schematics: 0.0.45
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
Our app structure is 
```
projectroot
|--client
    |-- src
     |-- app
          |--module1
          |--web
|--server
```

like I have been doing since 1.3.x, I `cd` into `client` and run
`ng g component /web/grid --module web --spec=false`
to create a `grid` component inside of `web` module

### Observed behavior
```
US-ST016LO-MLT:client st016lo$ ng g component /web/grid --module web --spec=false
  create app/web/grid/grid.component.scss (0 bytes)
  create app/web/grid/grid.component.html (41 bytes)
  create src/app/web/grid/grid.component.ts (264 bytes)
  update src/app/web/web.module.ts (3106 bytes)
```

As you can see, the `grid` folder is created with the component ts file in it as usual.  The file looks fine.  But the two other files are **not there**:
```
@Component({
  selector: 'pb-ds-grid',
  templateUrl: './grid.component.html',
  styleUrls: ['./grid.component.scss']
})
```

Instead, a **new**, second `app/web/grid/` path has been created in `/client` with the HTML and SCSS file in it!  

Additionally, the HTML file is:
```
<p>
  <%= dasherize(name) %> works!
</p>
```

this is obviously unusable.  I have tried rebooting, deleting the project's node modules and re-installing.

**Comment by DaSchTour** [comment]
I'm not sure if the title of this issue is correct looking at all the possible duplicates. That may all have similar cause but all of them represents different symptoms. So I'm not sure if they are really all duplicates because they all need to be checked after possible fixes.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
