### ISSUE TITLE
Fonts (FontAwesome) not working properly in serve and build

### ISSUE THREAD

**Issue by arsyed04** [angular/angular-cli#9481]
### Versions
Angular CLI: 1.7.0-beta.3
Node: 9.4.0
OS: win32 x64
Angular:
...
Windows 10

### Repro steps
Include font in .angular-cli.json:
"styles": [
      "../node_modules/font-awesome/css/font-awesome.min.css",
...
]
ng serve
or
ng build --target=production

### Observed behavior
Fonts are not loading, especially noticed for fontawesome

### Desired behavior
Fonts should load properly as in previous versions, like 1.7.0-beta.2

**Comment by slubowsky** [comment]
Already fixed - https://github.com/angular/angular-cli/issues/9471

**Comment by clydin** [comment]
Closing resolved via #9474

**Comment by arsyed04** [comment]
Issue is still reproducible in 1.7.0-rc.0
