### ISSUE TITLE
Budgets - "minimum exceeded" errors despite not configuring any minimums

### ISSUE THREAD

**Issue by Matmo10** [angular/angular-cli#9482]
### Versions
```
Angular CLI: 1.7.0-beta.3
Node: 8.6.0
OS: darwin x64
Angular: 6.0.0-beta.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.1
@angular/cli: 1.7.0-beta.3
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.2.0
@angular-devkit/core: 0.2.0
@angular-devkit/schematics: 0.2.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.0-beta.3
@schematics/angular: 0.2.0
@schematics/package-update: 0.2.0
typescript-collections: 1.2.5
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps
* Use the following setup for budgets:
    ```
      "budgets": [{
        "type": "any",
        "error": "1mb"
      }]
  ```
* ng build --prod
* Observe errors

### Observed behavior
Error output:
```
ERROR in budgets, minimum exceeded for assets/i18n/de/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/es/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/en/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/eu/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/fr/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/hr/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/fi/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/hu/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/it/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/iw/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/nl/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/ko/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/ja/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/no/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/pl/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/pt_BR/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/ro/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/ru/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/tr/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/zh_CN/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/sv/strings.json.
ERROR in budgets, minimum exceeded for assets/i18n/zh_TW/strings.json.
ERROR in budgets, minimum exceeded for index.html.
ERROR in budgets, minimum exceeded for 3rdpartylicenses.txt.
```

### Desired behavior
Not sure why I'm seeing errors about minimums when I haven't configured any.

### Mention any other details that might be useful (optional)
Would be great to see a few example configs [here](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/budgets.md), the descriptions are pretty vague (and confusing as to how they work together) without any concrete examples.

**Comment by cexbrayat** [comment]
@Matmo10 If you use `error` (as far as I understand, I'm not the author of this feature), it sets a threshold for maximum AND minimum. If you only care about the maximum, you should set `maximumError` instead. And all sizes work with a baseline: if you don't set one, it uses a baseline of 0.

So for example, setting a budget `"type": "any", "baseline": "500kb", "error": "100kb"` will ensure that all assets are between 400kb and 600kb, or error. A little bit of documentation would indeed help, you are welcome to offer a PR if you can.

In the upcoming `beta.4`, I added better error messages (see https://github.com/angular/angular-cli/commit/7f9931d28b5296421889cff4cdb69616840cdf10), so you should have something slightly more explicit like : `ERROR in budgets, maximum exceeded for total scripts. Budget 500 kB was exceeded by 83.9 kB.`.

**Comment by Matmo10** [comment]
Thanks for the clarification - even just adding what you said to the docs makes it much clearer IMO. I guess it's obvious now in retrospect, but `baseline` seems to be a required field then for budgets. That wasn't immediately clear to me. I came into this expecting to set an absolute max or min limit, not doing everything relatively.  

Also thanks for the improved error messages!
