### ISSUE TITLE
@angular-devkit/core is missing from package.json

### ISSUE THREAD

**Issue by sarbull** [angular/angular-cli#9485]
After i create a new app with `ng new angularApp` on install i get `cannot find @angular-devkit/core`.

### Versions
```bash
_                      _                 ____ _     ___
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
/ △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
|___/

Angular CLI: 1.6.0
Node: 8.9.1
OS: win32 x64
```

### Repro steps
* ng new angularApp

### Observed behavior
I have to manually add `@angular-devkit/core`

### Desired behavior
Run smooth the first time.

### Mention any other details that might be useful (optional)
No other details.

**Comment by clydin** [comment]
Please upgrade to the latest patch release (1.6.7 currently) both globally and locally in the project exhibiting the issue.  The global version determines the version initially present in a newly generated project.
