### ISSUE TITLE
command to add 3rd party module into app module

### ISSUE THREAD

**Issue by aniruddhadas9** [angular/angular-cli#9489]
### Versions
```
Angular CLI: 1.6.7
Node: 8.7.0
OS: darwin x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

```

### Repro steps

* currently `ng g m some -m app` create a module and add it to the `app.module.ts`
* I dont want to create a new module in side my code as I have one in npmjs repo and also available in my `node_module` folder as it declared as dependencies in the `package.json` and after doing npm install in side my project folder
* So I want if angular cli can provide a command to add third party angular modules to be added into `app.module.ts` by downloading it or not downloading it will help

I got this situation during deployment using jenkins. So there are many modules and as per the environment, jenkins need to pick `modul from public repo and install it in the app. As these are available in npmjs repo, only adding import the module in import section of the `app.module.ts` will be expected behavour. I don't have any way to do that.

### Observed behavior
No way to only add third party modules to app module without creating a new module.

### Desired behavior

Is there a way I can add a 3rd party angular module into my my main app module using angular cli command?

I have a angular module which is published to npmjs and available in public repository. So I installed it using npm install --save @rep/module and now I want to add that to my module using angular-cli command.

a angular cli command to do below thing

Add import statement in my app.module.ts like import {SomeModule} from '@herd/angular-client';
Add the imported module into import block like below
import code

@NgModule({
  imports: [
    SomeModule,
  ]
});
I don't see any command like this. As I publish some of my module to be used in multiple project, it will be nice to have this command. also during jenkins deployment it will be helpful to deployment only production related modules.

**Comment by clydin** [comment]
Something similar (along with some other potential features) is being discussed here: https://github.com/angular/angular-cli/issues/9387.
