### ISSUE TITLE
Use TypeScript path mapping to introduce custom namespace for commonly used paths (environment, shared) 

### ISSUE THREAD

**Issue by kaznovac** [angular/angular-cli#9490]
### Versions
```
Angular CLI: 1.6.6
Node: 9.4.0
OS: darwin x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.6
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack-bundle-analyzer: 2.9.2
webpack: 3.10.0
```

### Observed behavior
For my somewhat nested component importing of environment and shared services looks like this:
```
import {Role} from '../../../shared/role.model';
import {environment} from '../../../../environments/environment';
// ...
```

### Desired behavior
After adding this to tsconfig
```
    // ...
    "baseUrl": "src",
    "paths": {
      "@shared/*": ["app/shared/*"],
      "@environments/*": ["environments/*"]
    }
```
one can take advantage of short (and much more clean) import syntax
```
import {Role} from '@shared/role.model';
import {environment} from '@environments/environment';
// ...
```

I'd suggest to add this to the new project template (at least for best practices paths).

### Mention any other details that might be useful (optional)
see typescript path mapping
https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

**Comment by kyliau** [comment]
Path mapping can sometimes be confusing, especially to new users since they could mistake the module name for a NPM package. We don't think that this is useful enough to be applied universally across all CLI-generated applications.
