### ISSUE TITLE
Error al instalar ANGULAR

### ISSUE THREAD

**Issue by eliezerlldm** [angular/angular-cli#9493]
Mac-Eliezer:Projects Angular 2 ebautista$ npm install -g @angular/cli
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/@angular/cli
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/@angular/cli/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/@angular
npm ERR! path /usr/local/lib/node_modules/@angular/cli
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/@angular/cli'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/@angular/cli'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/@angular/cli\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/@angular/cli' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ebautista/.npm/_logs/2018-02-02T19_34_42_210Z-debug.log
Mac-Eliezer:Projects Angular 2 ebautista$ sudo npm install -g @angular/cli
npm ERR! path /usr/local/bin/ng
npm ERR! code EEXIST
npm ERR! Refusing to delete /usr/local/bin/ng: ../lib/node_modules/angular-cli/bin/ng symlink target is not controlled by npm /usr/local/lib/node_modules/@angular/cli
npm ERR! File exists: /usr/local/bin/ng
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ebautista/.npm/_logs/2018-02-02T19_35_27_984Z-debug.log
Mac-Eliezer:Projects Angular 2 ebautista$

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by eliezerlldm** [comment]
You already followed the steps but now I return:

yp WARN EACCES attempting to reinstall using temporary dev dir "/Users/ebautista/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.9.4' ]
gyp verb install input version string "8.9.4"
gyp verb install installing version: 8.9.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.9.4
gyp verb ensuring nodedir is created /Users/ebautista/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.9.4


help!!!

**Comment by eliezerlldm** [comment]
he error exits when I run npm install -g @ angular / cli


node 
v8.9.4
npm
5.6.0

**Comment by jujuali85** [comment]
check the following: https://github.com/angular/angular-cli/issues/7556
