### ISSUE TITLE
Font awesome font file aren't being loaded

### ISSUE THREAD

**Issue by asadsahi** [angular/angular-cli#9496]
### Versions
```
Angular CLI: 1.7.0-beta.3
Node: 9.4.0
OS: win32 x64
Angular:
...
```

### Repro steps
[Repo](https://github.com/asadsahi/font-awesome-works) with font awesome configured and works with angular cli 1.6.0. 

### Observed behavior

Font files aren't being loaded with angular cli 1.7.0 beta-3. Getting this error:

![image](https://user-images.githubusercontent.com/3470892/35760518-9f264ed6-0878-11e8-9792-d88bb8f816a1.png)

### Desired behavior

Font files should be loaded.

**Comment by clydin** [comment]
Closing as resolved via #9474 and will be available in the next release.
