### ISSUE TITLE
 @Input, @Output Properties 

### ISSUE THREAD

**Issue by doczoidberg** [angular/angular-cli#95]
I tried to add @Input, @Output Properties to a component:
```
@Component({selector: 'todo-cmp'})
class TodoCmp {
  @Input() model;
  @Output() complete = new EventEmitter(); // TypeScript supports initializing fields

  onCompletedButton() {
    this.complete.next(); // this fires an event
  }
}
```

But i get the error: 
`
[DiffingTSCompiler]: Typescript found the following errors:
  app/app1.ts (13, 4): Cannot find name 'Input'.`

**Comment by cironunes** [comment]
I'm able to use them testing against the current master. Which version are you using?

**Comment by Brocco** [comment]
Can you share the module imports that you're using to gain access to `@Import` and `@Output`?

**Comment by doczoidberg** [comment]
what modules do I have to import?

**Comment by cironunes** [comment]
If you're using Angular Alpha 46, you should import the following for the code that you sent:

```js
import {Input, Output, Component} from 'angular2/angular2';
```

If you update to the latest Alpha 48:

```js
import {Component, Input, Output} from 'angular2/core';
```
