### ISSUE TITLE
after install of compass-importer and node-sass ng serve ends with segmentation fault

### ISSUE THREAD

**Issue by thinkrapido** [angular/angular-cli#950]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS
ubuntu 16.04

2. Versions. 
angular-cli: 1.0.0-beta.5
node: 6.2.0
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

npm install compass-importer node-sass

ng serve

OUTPUT:
```
(node:10586) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
Segmentation fault (core dumped)
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.
no stack trace

5. Mention any other details that might be useful.

default css file renamed to scss

no other changes

**Comment by thinkrapido** [comment]
I debugged it so far, that I can say it is not an angular-cli problem.

It has to do with the binding.node module of node-sass, where the render_sync function causes the problem.

**Comment by thinkrapido** [comment]
It is a problem with using both modules node-sass and compass-importer.

I deleted compass-importer so that only node-sass is present.
This config causes no segmentation fault.

Has someone an idea of this coincidence?

See: https://github.com/sass/node-sass/issues/1572

**Comment by filipesilva** [comment]
This seems to be a bug with our compass support.

**Comment by filipesilva** [comment]
Closed as this issue was made obsolete by https://github.com/angular/angular-cli/pull/1455.
