### ISSUE TITLE
Implement `--component` flag to autoregister a service (like `--module`)

### ISSUE THREAD

**Issue by BioPhoton** [angular/angular-cli#9500]
### Versions
```
Angular CLI: 1.6.0
Node: 6.9.0
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
* Step 1
Create a modlue: `ng g m test` 
* Step 2
Create Component. `ng g c test-page`
* Step 3
Create Service and use the `--module` flag to register the service under the providers:
`ng g s test/components/test-page --module=test/test.module.ts`
* Step 4
Create Service and use the `--component` flag to register the service under the providers: 
=> There should be a flog for component

### Desired behavior
Please implement the `--component` flag for generating a service to provide the service under the provider's option in the `@Component` decorator. Same as with the flag --module

`ng g s test/components/test-page --component=test/components/test.component.ts`

**Comment by alan-agius4** [comment]
Hi @BioPhoton, thanks for this feature request. However, currently this is not part of the Angular CLI roadmap.

Let's close it for now, and revisit in the future if we see that this is needed.
