### ISSUE TITLE
ng update fails when using 1.7.0-beta.3

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#9507]
### Versions
```
<!--
Angular CLI: 1.7.0-beta.3
Node: 8.9.1
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.7.0-beta.3
@angular-devkit/build-optimizer: 0.2.0
@angular-devkit/core: 0.2.0
@angular-devkit/schematics: 0.2.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.0-beta.3
@schematics/angular: 0.2.0
@schematics/package-update: 0.2.0
typescript: 2.6.2
webpack: 3.10.0
-->
```

### Repro steps
* `ng new hello`
* `ng update`

### Observed behavior
```
Error: Cannot downgrade package "@angular/cli" from version "1.7.0-beta.3" to "1.6.7".
Cannot downgrade package "@angular/cli" from version "1.7.0-beta.3" to "1.6.7".
```

### Desired behavior
It should not fail because 1.7.0-beta.3 is more recent than 1.6.7.

**Comment by Destreyf** [comment]
@cexbrayat 

The cli update command should work off of the npm latest tag, the current latest tag is `1.6.7`, so this is trying to perform the correct action, as of now the `1.7.0-beta.X` releases are  put on the next tag, which is reserved for beta/testing for new versions.

I agree that 1.7.0 is "newer" than 1.6.7 however checking a syntax like 1.7.0-beta.X can be more difficult, it'd be nice if there was a check that allowed upgrading a project without upgrading the cli.

**Comment by cexbrayat** [comment]
@Destreyf yep, I know it's with the latest stable. What I was pointing out is that throwing an error when you are using a more recent version is not really a good default behavior and could be improved :).

I agree that the `ng update` should offer different sub tasks, as the `@schematics/package-update` already does (there is a task for `@angular`, one for the CLI, one for devkit and one for doing all of them, which is the one `ng update` uses). I've been using the `@angular` task of the schematics directly for some time.

**Comment by clydin** [comment]
Closing this issue as `ng update` has been completely re-worked for 6.0.
