### ISSUE TITLE
Use component from a CLI project inside other CLI project

### ISSUE THREAD

**Issue by Kalemstorm94** [angular/angular-cli#9510]
### Versions
```
<!--
@angular/cli: 1.4.10 (e)
node: 8.9.1
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.10
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4
-->
```

### Repro steps

 After running `ng new Proj1` and `ng new Proj2`, I create a new component inside the first project.

### Desired behavior
I want to import this new component inside the second Project, whitout making a module, or without   installing it with npm. Is this possible? I need this because I don't want to duplicate the component from the First project into the Second.

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
