### ISSUE TITLE
Object Spread with AOT provide silently fails

### ISSUE THREAD

**Issue by intellix** [angular/angular-cli#9511]
### Versions
```
Angular CLI: 1.6.5
Node: 8.9.1
OS: darwin x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps

* Step 1: Clone https://github.com/intellix/spread-aot
* Step 2: `ng serve` and check console
* Step 3: `ng serve --aot` and check console

AKA - Provide a config by using object spread:
```ts
export const appFeatureConfig: FeatureConfig = {
  ...featureConfig,
  enabled: false,
};
```

### Observed behavior
**JIT:** `{enabled: false, items: Array(5)}`
**AOT:** `{enabled: false}`

The spreaded default config only works in JIT and silently fails in AOT.  Object.assign seemed to give undefined

### Desired behavior

I'd like the config to work, but even an error would be nice :) Was quite a head scratcher to see it only failed in production

### Mention any other details that might be useful (optional)
Commit: https://github.com/intellix/spread-aot/commit/d5f95aa2b9304d3acb50326f1eabf58ebf26dabe

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
