### ISSUE TITLE
GET http://localhost:3000/css/bootstrap.min.css net::ERR_ABORTED

### ISSUE THREAD

**Issue by Awais512** [angular/angular-cli#9512]
My boilerplate.ejs file 

<!DOCTYPE html>
<html lang="en">
  <head>
    

    <title>Ecommerce</title>
    <link rel="stylesheet"  href="/css/bootstrap.min.css">
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div>
      </div>
    </nav>

    
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>
    </div> 
  </body>
</html>

my server.js file
var express = require('express');
var morgan = require('morgan');
var app = express();
var mongoose = require('mongoose');
var bodyParser = require('body-parser');
var ejs = require('ejs');
var engine = require('ejs-mate');
var User = require('./models/user');

mongoose.connect('mongodb://root:abc123@ds223738.mlab.com:23738/ecomawais', function(err){
    if(err){
    console.log(err);}
    else{
        console.log("Connected with mongodb");
    }
});
//Middleware
app.use(express.static(__dirname + '/public'));
app.use(morgan('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
app.engine('ejs', engine);
app.set('view engine', 'ejs');

app.post('/create-user', function(req, res, next){
var user = new User();
user.profile.name = req.body.name;
user.password = req.body.password;
user.email = req.body.email;

//save the user in database
user.save(function(err){
    if(err) return next(err);
    res.json("Successfully created a new user");
});
});

app.get('/', function(req, res){
    res.render('main/home');
});

app.get('/about', function(req, res){
    res.render('main/about')
});

app.listen(3000, function(err){
    if(err) throw err;
    console.log("Server is running on port 3000");
});

when i try to run boilerplate file then bootstrap file is not loaded and checking my console then it will give me this error "GET http://localhost:3000/css/bootstrap.min.css net::ERR_ABORTED"
Please help me to solve this issue. Any help would be appreciated.

**Comment by clydin** [comment]
I'm sorry, but this issue is not caused by Angular CLI and it also does not appear that the CLI is being used. Please contact the author(s) of the bootstrap and/or express project or file an issue on their issue tracker.  Alternatively, please try a site such as [StackOverflow](http://stackoverflow.com/).

**Comment by Awais512** [comment]
Thanx I solved thus because my public folder was inside the view folder
that is why Style file was not loading.
