### ISSUE TITLE
Live dev server reloads browser multiple times

### ISSUE THREAD

**Issue by siva636** [angular/angular-cli#9514]
### Versions
```
Angular CLI: 1.6.6
Node: 8.9.1
OS: linux x64
Angular: 5.0.0
Browser: Chromium Version 64.0.3282.119 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
```

### Repro steps

* Run the project using ng serve
* Make some changes in the project and save changes
* Observe the browser

### Observed behavior
Browser reloads multiple times

### Desired behavior
Browser should reload only once

### Mention any other details that might be useful (optional)
The following issue might be related to this:
https://github.com/webpack/webpack/issues/2983

**Comment by clydin** [comment]
This appears to be either a Webpack issue or an issue with multiple files being saved to disk in a staggered, short period of time.  If webpack provides an update or change to this behavior it can be incorporated into the CLI as the CLI incorporates new releases of Webpack as they become available.
