### ISSUE TITLE
embed Interactive SVG chart not displaying / showing

### ISSUE THREAD

**Issue by gabo696hn** [angular/angular-cli#9520]
### Versions
Angular CLI: 1.6.4
Node: 8.9.4
OS: win32 x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.2.0
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

### Repro steps
* Step 1, on html -> \<embed src="{{ chart }}"/\>
* Step 2, on ts -> chart: 'assets/interactive-chart.svg'

### Observed behavior
nothing appears

### Desired behavior
interactive chart appearing

### Mention any other details that might be useful (optional)
chart appears using img tag but can't interact with it (highlights and shows additional info when hovering)

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
