### ISSUE TITLE
Upgrade workflow : best practices

### ISSUE THREAD

**Issue by rekna1** [angular/angular-cli#9525]
I want to know what are the best practices when developping multiple application using different version of angular 5 (as it's not always possible to update all applications at once)

* is it save to always update angular-cli to the latest version, even if some projects are created with a lower version of the cli / angular ( 4 - 5)
* is deleting the node_modules folder then reinstall all packages the only safe option to update angular version in a specific application? 
* can upgrading angular version and or local angular-cli in a project be made part of global angular-cli as a extra command?

**Comment by filipesilva** [comment]
- Angular CLI 1.x supports Angular 2, 4 and 5. It should always be safe to update to a newer version of the CLI, barring known bugs.

- You shouldn't need to delete `node_modules`. But it's common enough that different package manager versions do things differently. Also a lot of users aren't used to package locks and sometimes that makes updating dependencies harder. Also when linking npm packages a lot can go wrong with lockfiles. Personally, whenever I see something weird or unexpected happening, I clear node modules and the lockfile. But I have to deal with a lot of odd dependency problems so I don't think I'm the general case.

- We're working on that on https://github.com/angular/angular-cli/pull/9321. It will be out in 1.7 final, right now we're still working out some bugs but you can try it out if you want in `1.7.0-beta.3`.

**Comment by rekna1** [comment]
Thx, that makes things a little be clearer. Hope 1.7 will land soon.

**Comment by rekna1** [comment]
According to https://stackoverflow.com/questions/36597780/how-do-i-correctly-upgrade-angular-2-npm-to-the-latest-version one should upgrade angular applications using these instructions:


> Angular Dep packages: npm install @angular/{animations,common,compiler,core,forms,http,platform-browser,platform-browser-dynamic,router}@latest --save
> 
> Other packages that are installed by the angular cli npm install --save core-js@latest rxjs@latest zone.js@latest
> 
> Angular Dev packages: npm install --save-dev @angular/{compiler-cli,cli,language-service}@latest
> 
> Types Dev packages: npm install --save-dev @types/{jasmine,jasminewd2,node}@latest
> 
> Other packages that are installed as dev dev by the angular cli: npm install --save-dev codelyzer@latest jasmine-core@latest jasmine-spec-reporter@latest karma@latest karma-chrome-launcher@latest karma-cli@latest karma-coverage-istanbul-reporter@latest karma-jasmine@latest karma-jasmine-html-reporter@latest protractor@latest ts-node@latest tslint@latest
> 
> Install the latest supported version used by the Angular cli (don't do @latest): npm install --save-dev typescript@2.4.2

Is this true ? If so it would be nice if this could be improved. Will the new update command in angular-cli 1.7 be able to upgrade a project with all the latest versions ?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by filipesilva** [comment]
The new `ng update` should take care of all the updating as you described.
