### ISSUE TITLE
Debugging Angular code with Visual Studio & ASP.Net Core

### ISSUE THREAD

**Issue by dcasbonne** [angular/angular-cli#9527]
### Versions
```
Angular CLI: 1.6.7
Node: 8.9.2
OS: win32 x64 (Windows 10 Pro)
Angular: 5.2.3
@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
* I've an Angular-CLI project wrapped inside a ASP.Net Core 2.0 project exactly as described here : https://medium.com/@levifuller/building-an-angular-application-with-asp-net-core-in-visual-studio-2017-visualized-f4b163830eaa
(I have to do that because I've other projects in this applications that requires ASP.Net Core MVC (WebAPI) and it's more efficient to have 1 VS open instead of one VSCode with the Angular project and another VS with the others project)
* Running "ng serve" from a command line very basically. 
* Project starts, I can debug in the browser but if I set some breakpoints in ts file in VS they wouldn't be hit...

### Observed behavior
Breakpoints in Visual Studio (2017) are not hit when set in ts files

### Desired behavior
Being able to debug typescript files inside Visual Studio :)

**Comment by clydin** [comment]
Information regarding debugging and source maps with vscode can be found in this issue: https://github.com/angular/angular-cli/issues/2453

**Comment by dcasbonne** [comment]
I'm not talking about Visual Studio Code, I'm talking about Visual Studio 2017 AND Angular in an ASP.Net Core project.
Would you be kind and re-open this issue please?

**Comment by clydin** [comment]
There should hopefully be similar settings within your IDE.  If not or other issues arise, please consider opening an issue with your IDE's vendor; or opening a question on a site such as [StackOverflow](http://www.stackoverflow.com) would be a more appropriate venue for a support request such as this.
As an alternative, you could develop both the ASP.Net Core and angular projects within vscode; it supports both.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by dcasbonne** [comment]
Oups I'm sorry I wasn't aware of the Code of Conduct here... I'll search again on SO and ask my question if I can find any answer.
Thanks for this explanation and sorry to waste your time for that !
