### ISSUE TITLE
Display source file for styles

### ISSUE THREAD

**Issue by slavede** [angular/angular-cli#9533]
When using ng server it would be useful to see where does style come from because this way if we see applied styled to some element, we don't know where does it come from.

![image](https://user-images.githubusercontent.com/2838038/35906852-59f1c350-0bec-11e8-99b8-66821f4606a1.png)

_I'm not sure is this CLI feature or Angular's so please correct me if I'm wrong_

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this and in some cases it might be useful. On the same time we should be careful how we increase the scope of the CLI because each new feature means new code to maintain and fix issues in.

Let's reopen if more folks need such functionality.
