### ISSUE TITLE
Unable to install angular

### ISSUE THREAD

**Issue by Pranaysapkale** [angular/angular-cli#9534]
while installing angular on windows getting below error message - 
npm ERR! path C:\Users\sapkpra\AppData\Roaming\npm\node_modules\angular-cli\node_modules\type-is\package.json.3902968815
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\sapkpra\AppData\Roaming\npm\node_modules\angular-cli\node_modules\type-is\package.json.3902968815' -> 'C:\Users\sapkpra\AppData\Roaming
\npm\node_modules\angular-cli\node_modules\type-is\package.json'
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\sapkpra\AppData\Roaming\npm\node_modules\angular-cli\node_modules\type-is\package.json.3902968815' -> 'C:\Users\sapkpra\AppData\Roam
ing\npm\node_modules\angular-cli\node_modules\type-is\package.json'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename 'C:\Users\sapkpra\AppData\Roaming\npm\node_modules\angular-cli\node_modules\type-is\package.json.3902968815' -> 'C:\Users\sapkpra\AppData\Ro
aming\npm\node_modules\angular-cli\node_modules\type-is\package.json'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path: 'C:\\Users\\sapkpra\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\type-is\\package.json.3902968815',
npm ERR!      dest: 'C:\\Users\\sapkpra\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\type-is\\package.json' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, rename \'C:\\Users\\sapkpra\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\type-is\\package.json.3902968815\' -> \'C:\\Users
\\sapkpra\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\type-is\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\sapkpra\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\type-is\\package.json.3902968815',
npm ERR!   dest: 'C:\\Users\\sapkpra\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\type-is\\package.json',
npm ERR!   parent: 'angular-cli' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sapkpra\AppData\Roaming\npm-cache\_logs\2018-02-07T08_04_45_382Z-debug.log

Please help

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
