### ISSUE TITLE
ERROR in src/app/app.component.ts(2,23): error TS2307: Cannot find module './dto/MClass'. 

### ISSUE THREAD

**Issue by aiqency** [angular/angular-cli#9536]
I'm pretty new to angular  >=2 and just generate a new application from scratch with the cli.
I've made some modules, components, services and so on, so I think I have a basic understanding of the framework. 
Anyway I can't figure out why my code doesn't compile while trying to import a simple dto class from anywhere else.

MDto.ts:
```
export class MDto {  ... }
```
```
app----dto 
 |      |      
 |       -- MDto
 ... 
 app.component.ts   <- try to access MDto here
```

app.component.ts:
```
import { Component } from '@angular/core';
import { MClass } from './dto/MDto';

@Component({ ... })
export class AppComponent {
  constructor() {
    const mDto = new MDto();
  }
}
```

Error:
``` 
ERROR in src/app/app.component.ts(2,23): error TS2307: Cannot find module './dto/MDto'. 
```

Version 
```
@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

IFAIK I don't have to explicitly set up this class as a providers or import it within any modules.
Hopefully somebody can help me here

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
