### ISSUE TITLE
Cannot read property 'range' of null

### ISSUE THREAD

**Issue by LuisBonsembiante** [angular/angular-cli#9537]
I have an erro run my project in production 

### Versions
 "@angular/cli": "^v1.6.7",
  "@angular/compiler-cli": "^5.2.3",

### Repro steps
just  run : ng build --prod

###Error
ERROR in chunk main [initial]
[name].[chunkhash:20].bundle.js
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by karmasakshi** [comment]
Reverting @angular/common to 5.2.1 solved it for me.

**Comment by clydin** [comment]
If that is the case here as well, then the issue is here: https://github.com/angular/angular/issues/21809

Note that this is due to a webpack bug and has been corrected in master and should be in the next webpack release.

**Comment by cpelikan** [comment]
Try with
ng build --prod -vc=true

**Comment by RaphaelJenni** [comment]
@cpelikan That works, but what does it mean?

**Comment by clydin** [comment]
The `--vc` option causes a separate vendor bundle to be created.  Note that this has the side effect of disabling an optimization that provides a large reduction in final output size.

**Comment by cpelikan** [comment]
Off course but yoi can set to false. Anyway is important to explicit the
flag

Il 08 Feb 2018 21:00, "clydin" <notifications@github.com> ha scritto:

**Comment by PillowPillow** [comment]
Same error with **"@angular/compiler-cli":"5.2.4"** and **"@angular/cli":"1.6.8"**

**Comment by candidosales** [comment]
I have the same error.
Same error with "@angular/compiler-cli":"5.2.4" and "@angular/cli":"1.6.8"

**Comment by cpelikan** [comment]
I solved with

ng build --prod -vc=true

or just -vc because true is default value for --prod

vc is alias of vendor chunk and means use a separate bundle containing only
vendor libraries. For some reason it doesn't works fine by default in this
version of angular cli


2018-02-12 0:40 GMT+01:00 Candido Sales Gomes <notifications@github.com>:
