### ISSUE TITLE
Integrating with bs-config.json

### ISSUE THREAD

**Issue by LiTiang** [angular/angular-cli#954]
Will **ng2-cli** can be use with `bs-config.json` in the future ?

The content of `bs-config.json` which i want to use is

```json
{
  "port":   3010,
  "server": {
        "baseDir": "./client",
        "routes": {
          "/menu/collection": "temp/virtualDB/menu-collection.json"
        }
  }
}
```

> NOTE : 
I really use this setting in my project without **ng2-cli** (i use **lite-server** directly)

**Comment by JasonGoemaat** [comment]
+ Also bs-config.js please

**Comment by filipesilva** [comment]
There is currently no support for a `bs-config.json` file, but will update this issue if that changes.
