### ISSUE TITLE
Not able to access json files inside assets folder angular 5

### ISSUE THREAD

**Issue by vreans** [angular/angular-cli#9554]
I am not able to access the JSON file placed in my assets folder using HTTP get method. 

Code:

![image](https://user-images.githubusercontent.com/22302934/35972720-faebc956-0cf8-11e8-93ff-25fccc35fde3.png)

Issue:

![issue 1](https://user-images.githubusercontent.com/22302934/35972660-c895909a-0cf8-11e8-9dd2-001447d3d9a5.jpg)
![issue 2](https://user-images.githubusercontent.com/22302934/35972661-c8d346ec-0cf8-11e8-8e85-489d26ff2fe7.jpg)

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
