### ISSUE TITLE
Use vtk.js / glsl files in angular cli app

### ISSUE THREAD

**Issue by doczoidberg** [angular/angular-cli#9555]
I try to use vtk.js in my angular cli application and added the vtk.js to my angular-cli.json.

```
ERROR in ./node_modules/vtk.js/Sources/Rendering/OpenGL/glsl/vtkVolumeVS.glsl
Module parse failed: Unexpected token (18:10)
You may need an appropriate loader to handle this file type....
```
How can I use a glsl loader with angular cli?

**Comment by Brocco** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by doczoidberg** [comment]
I get no answers anywhere
