### ISSUE TITLE
v1.7.x with typescript 2.6.x css escape regression

### ISSUE THREAD

**Issue by kondi** [angular/angular-cli#9567]
### Versions
```
Angular CLI: 1.7.0-rc.0
Node: 7.4.0
OS: win32 x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.0-rc.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0-rc.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.6.1
webpack: 3.10.0
```

### Repro steps
* Generate default project with @angular/cli (kondi/clicssbug@60b8582)
* Upgrade `@angular/cli` to 1.7.0-rc.0 and `typescript` to 2.5.3 (kondi/clicssbug@8448fe9 and kondi/clicssbug@63ed10e)
* Add the following rule to the component stylesheet (kondi/clicssbug@1d12783);
```css
h1::before {
    content: 'A: \0041';
}
```
* `ng serve --prod` => "A: A Welcome to app!" (works well)
* Upgrade typescript to 2.6.1 (kondi/clicssbug@036e448)
* `ng serve --prod` => "A: x00041 Welcome to app!" (buggy build)

### Observed behavior

The prod build changes the escaping in the string literal of CSS rule to invalid `\x00041`:
```css
h1[_ngcontent-c0]::before {
    content: 'A: \x00041';
}
```

### Desired behavior

It should not change the represented value of the string literal.

### Mention any other details that might be useful (optional)

* Not prod build => OK
* If cli downgraded to 1.6.x => OK
* If typescript downgraded to 2.5.x => OK
* If scss is used => Not OK
* Same rule inside the global `styles.css` => OK

The syntax I used in the CSS literal is quite common if you use font icons.

**Comment by kondi** [comment]
Thank you for the investigation!
Do you have an idea why this is not a problem when I use the older cli with the same typescript version?

**Comment by clydin** [comment]
1.6.x and earlier used a different stylesheet optimization pipeline which coincidentally collapsed escaped values to a short form if possible (i.e., `\0041` --> `A`).  This essentially hid the underlying issue.

**Comment by mcherb** [comment]
i get the same problem with 1.7.0 (which is released today)

**Comment by kondi** [comment]
I can't test now, but this might have been fixed by https://github.com/angular/angular/pull/22776.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
