### ISSUE TITLE
Bootstrap Library Not Loading 

### ISSUE THREAD

**Issue by treasure1210** [angular/angular-cli#9569]
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

### Current behavior
After installing bootstrap via npm, the styles are not loading into the angular app. Bootstrap 4.0.0 is installed and listed as a dependency (also tried with 3.3.7), but I cannot use the Bootstrap classes to style the app.

### Expected behavior
Bootstrap classes and styles should work when installed via npm. This works fine for CLI 1.6.7 and Angular 5.2.3, but not CLI 1.6.7 and Angular 5.2.4.

### Minimal reproduction of the problem with instructions
ng new project
cd project
npm install bootstrap

### Environment
<pre><code>
Angular version: 5.2.4

Browser:
- [x] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version X
</code></pre>

**Comment by Brocco** [comment]
There are a few more steps to set up your project to use bootstrap. Please consult the documentation [here](https://github.com/angular/angular-cli/wiki/stories-include-bootstrap).

Closing this issue as it is covered in the documentation reference above.
