### ISSUE TITLE
Any harm is using "dom.iterable" within lib in tsconfig's?

### ISSUE THREAD

**Issue by chadbr** [angular/angular-cli#9580]
### Versions
```
1.6.3
```

    "lib": [
      "es2016",
      "dom",
      "dom.iterable"
      ]

----

I'm just wondering 

- if it's ok to add dom.iterable to the tsconfig's (i.e. does it break anything? I can't see any issues...)
- if it should be part of the default template?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
