### ISSUE TITLE
Hide app setting variable (like firebase details )  

### ISSUE THREAD

**Issue by nirav4273** [angular/angular-cli#9581]
I want to hide my firebase details.
after make build all environment.ts file data visible inside main.ts file.
I want to hide from there.

can anyone suggest how to hide?
Is it possible in angular or any way for hiding details?

**Comment by wvanderdeijl** [comment]
All angular code is shipped to the client. How would you envision to keeping things secret in JavaScript that ships to the browser client?

**Comment by ddimaria** [comment]
@nirav4273 you would handle this with a proxy or on a server where you authenticate (token).

**Comment by Brocco** [comment]
Duplicate of #4419
