### ISSUE TITLE
Not able to load file other than index.html with angular-cli

### ISSUE THREAD

**Issue by Alex-DE-74** [angular/angular-cli#9592]
**Problem**:
Not able to load files other then index.html with angular.cli.
Hello together, this problem drive my nuts since one week and no working solution.
If I try to open/reference/link to some file (i.e. child.html) I always got index.html.
I tried child.html, /child.html ./child.html, also <base href="/"> or   <base href="./">.
I've also tried routing as { path: 'child', redirectTo: 'child.html' } with allcombination here in file and in link.
So for me it is not possible to route/link to other file and use templateUrl in modal service. That is very frustrting.
One thing is interesting: if I change in .angular-cli.json following line:
 "index": "index.html" to  "index": "child.html", than after cache refresh with npm cache verify the content of child.html is shown instead of index.html. Bit if I add something like  "child": "child.html" and use child (without .html or also with .html - no difference ) and goto localhost../child I get also index.html.

So, it would be very nice to know how to solve such problems and why it is now exceptionally overcomplicated to make simply things with angular (cli) ? 

**Other problem** is if I try to include my own js.scripts I always get ERR ABORTED / 404 and scripts are not loaded.

**P.S.** all files like child.html or scripts are copied in ALL directories inside project to be sure something 'magic directory' is not a show stopper.

P.S.S. I've one example on plunker, which works (and uses outdated angular), but the same example does not work at my local angular-cli configuration. See: http://embed.plnkr.co/Ua7aZsQd3Gf74oXfXigq/preview

I'm also very frustrated, how quickly module outdates and does not work together anymore or all symbols are renamed, so we spawn days of time just to find correct configuration (or not to find and give up). This remember me on an old LaTeX days, where each week one or more days are gone to repair configuration after one or two packages updated :(

### Versions
```
C:\NJS\kiddies-app>ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.5
Node: 8.9.4
OS: win32 x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps

Described above.

### Observed behavior
```
Open a requested file, but got index.html.
```

Thank you very much for considering my question.

**Comment by Brocco** [comment]
To serve static files with the CLI, take a look at how to configure assets to ensure the dev server sees them. https://github.com/angular/angular-cli/wiki/stories-asset-configuration

**Comment by Alex-DE-74** [comment]
Hi @Brocco !
Good catch! 
I've already my files in assets in the main project and it does not worked also and I leave this route.
For some unknown reason, the loading of scripts from assets-path has worked immediatelly, but not static html-route. Possible,  I run in some limitations, as @hansl mentioned in #9597 in between Angular2+ and AngularJS.
Now I tried it again (the files were also there) in the striped-down project, but without active Routing-Module and now it's magically works as it should! I'm happy!
So, now I should recap the main project.
One question - is it possible, that active Roting-Module prevents static-route to assets-content and ist it possible to skip over this limitation?
Tnakn you very much!
Alex
