### ISSUE TITLE
Not able to reproduce simple (older) code with latest angular-cli

### ISSUE THREAD

**Issue by Alex-DE-74** [angular/angular-cli#9596]
Hello together!

Following problem: I'm not able to reproduce this plunkr:
http://embed.plnkr.co/Ua7aZsQd3Gf74oXfXigq/preview

My version can be accessed on: https://drive.google.com/open?id=1wAjf9Px3GA71jw7pKAa5FYbX9JaNTmci, but I have stripped off angular-module directory in order to get reasonably file size.

### Versions
```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.8
Node: 8.9.4
OS: win32 x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

```

### Repro steps
1. ng new angular-modal-form
2. Download project from http://embed.plnkr.co/Ua7aZsQd3Gf74oXfXigq/preview
3. Unpack zip-File to src and modify in scripts and ng-app all "modalApp" --> "App"

Now we get:

index.html:1 Refused to apply style from 'http://localhost:3456/style.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index.html:12 GET http://localhost:3456/angular-modal-form.js net::ERR_ABORTED
index.html:13 GET http://localhost:3456/script.js net::ERR_ABORTED
index.html:1 Refused to apply style from 'http://localhost:3456/style.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index.html:12 GET http://localhost:3456/angular-modal-form.js net::ERR_ABORTED
index.html:13 GET http://localhost:3456/script.js 404 (Not Found)
core.js:3683 Angular is running in the development mode. Call enableProdMode() to enable the production mode.

So, outcommeted lines 
  <script src="angular-modal-form.js"></script>
  <script src="script.js"></script>
and add scripts to .angular-cli.json like:
      .....
      "scripts": [
        "angular-modal-form.js",
        "script.js"
      ],
   ....

(I have also tried "./...")

we get only:

Refused to apply style from 'http://localhost:3456/style.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
core.js:3683 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
The last error is not dramatically, because style.css contains nothing important.

### Observed behavior
```
Click on buttons does not results in opening modal dialog like on http://embed.plnkr.co/Ua7aZsQd3Gf74oXfXigq/preview
```

### Desired behavior
Modal dialogs should pop-up.

Many thanks for your help!

**Comment by Brocco** [comment]
Including external script files in a build is part of the wiki, you can find that information here: https://github.com/angular/angular-cli/wiki/stories-global-scripts

**Comment by thetric** [comment]
I think there is a general confusion about the ng-cli. @Alex-DE-74 wants to write a **Angular 1** app with the CLI, which is an overkill for someone new to AngularJS.

@Alex-DE-74 You don't need the Angular CLI to run your example. Simply download all files from the Plunkr into one folder and open the `index.html` in a browser.

**Comment by Alex-DE-74** [comment]
Please reopen.
As I already mentioned in entry post, I included the script file in .angular-cli.json scripts array.
The example here is only a part of bigger project, just to demonstrate current problems with AngularJS and Angular CLI. The whole project uses both, because it depends heavily on others JS-methods (this is very special client part and can't be simply done on server site).
So, my quetsion again, what is wrong or it is simply "this can't be done"?
Thank you again.

**Comment by mcastre** [comment]
+1
