### ISSUE TITLE
Proposal: Auto add (providers, directives, pipes, styles, styleUrls) when adding 3rd party libs, etc.

### ISSUE THREAD

**Issue by NathanWalker** [angular/angular-cli#96]
Discussion on AngularAir today regarding 3rd party libraries (https://plus.google.com/events/c7m79d5o04nom5eednk5ecqtebk) brought up an interesting thought.
See also: https://github.com/angular/angular/issues/5503

If 3rd party libs all adhered to a certain naming convention and style when exporting necessary services, directives, pipes, etc., it would be incredibly helpful if this CLI could auto-annotate the src code files with the necessary `directives`, `providers`, `pipes`, etc.

Consider the following scenario:

1. User wants to use `ng2-image-lazy-load` (https://github.com/NathanWalker/ng2-image-lazy-load)

2. Since it followed certain conventions, `IMAGELAZYLOAD_PROVIDERS `, the CLI might provide an additional helpful aid (command can be whatever, just using `add-lib` for example):
```
ng add-lib ng2-image-lazy-load 
```
It would proceed to run `npm install ng2-image-lazy-load`, then prompt with a couple questions:
```
$ Would you like this provider as part of the bootstrap? (y/n)
```
If "y":
```
$ Please provide the path to the src file which bootstraps your app:
$ src/bootstrap.ts
```
It would add the import statements and append the aptly named `[lib_prefix]_PROVIDERS` in the user's app bootstrap.
If the lib contained no constants with `PROVIDERS` in the name, it would modify nothing.

If "n":
```
$ Please provide the path of the component you would like the providers added to:
$ src/components/main.component.ts
```
It would add the import statements and append the libraries aptly named `PROVIDERS` in the `viewProviders` of the component.

Similar scenarios would apply for `DIRECTIVES`, `PIPES`, etc.

If this were possible, every 3rd party lib could suggest using the CLI as the first option to install, followed by manual npm install.

/cc @jvandemo, @gdi2290, @valorkin, @ocombe, @jeffwhelpley,  @pascalprecht, @mgechev, @ludohenin, @robwormald

**Comment by IgorMinar** [comment]
the proposal sounds reasonable to me (with some tweaks). I think that we should prefer local import over global import, so I'd reorder the options.

Would you like to create a test package(s) in npm that we can experiment with?

**Comment by NathanWalker** [comment]
Tweak away. 
local over global certainly sounds better and any options or workflows that make sense to you here as well.

For now, you can experiment with https://github.com/NathanWalker/ng2-image-lazy-load
`npm install ng2-image-lazy-load`
It follows the conventions mentioned. This file (https://github.com/NathanWalker/ng2-image-lazy-load/blob/master/ng2-image-lazy-load.ts) exports `PROVIDERS` and `DIRECTIVES`.

I'll update that to the latest alpha release over the weekend.

If you need anything specific, let me know.

**Comment by NathanWalker** [comment]
adjective: `adlib`; adverb: `adlib`
***musical context***:
> Jazz musicians may `adlib` during a performance, meaning they are **free to vary** tempo and **instrumentation**.

***programmers context***:
> When using any framework to create an application, there will come a time when a developer must `adlib` to complete the applications specifications.

Might be a fun command: `adlib`

**Comment by robwormald** [comment]
i think perhaps a simple solution for this would be something along the lines of 
```typescript
//myPluginRoot.ts
import {MyPluginServiceA, MyPluginServiceB} from './services';
import {MyDirectiveA, MyDirectiveB} from './directives';
import {MyPipeA, MyPipeB} from './pipes';

//export the named stuff for granular usage
export * from './services'
export * from './directives'
export * from './pipes'

//use es6 default syntax to export the "plugin"
export default {
  providers: [MyPluginServiceA, MyPluginServiceB],
  directives: [MyDirectiveA, MyDirectiveB],
  pipes: [MyPipeA, MyPipeB]
}
```

users and tooling are then easily able to do :
```typescript
//naming is irrelevant here
import myPlugin from 'myPlugin'

//now its consistent:
myPlugin.directives
myPlugin.services
myPlugin.pipes

```

and this is easily done with templating, as the actual name of the export is "default" - no weird lookups necessary and no NAMING_CONVENTIONS to force / invent. 

see http://plnkr.co/edit/Yi1e3ifiX0gSqd8Qs2h4?p=preview - i added a little plugin registration helper too, which @IgorMinar will probably yell at me about.

**Comment by NathanWalker** [comment]
That's the best solution I've heard yet Rob. Very clean and simple.

I could pull your plunk (the gist of it anyway) into a repo tomorrow or
Friday and publish it so it could be experimented with in this setup.

**Comment by ludohenin** [comment]
@robwormald I like it very much

**Comment by ocombe** [comment]
+1 on this solution @robwormald :)

**Comment by jvandemo** [comment]
@robwormald &mdash; Brilliant, love your proposal! :+1:

**Comment by robwormald** [comment]
Go for it! (maybe not the helper thing...)

**Comment by valorkin** [comment]
Will not this push to use MVC like folder separation?
Like for angular 1 really was really popular controllers\directives\templates separation
which became really fast unusable in large apps
that all moved to components separation all related to component in one folder
a bit later nested components and common folders appeared as a practice

+1 to @robwormald that we should not push/invent name conventions

**Comment by robwormald** [comment]
this is for third party packages (like yours) which will presumably ship via NPM, and thus the structure of the package is mostly irrelevant to the user. The structure internal to the module / plugin is entirely up to you, that was just a quick and dirty demo.

**Comment by jvandemo** [comment]
@valorkin &mdash; I think using a folder structure with `directives`, `services` and `pipes` makes sense for libraries (the Angular team also does this internally in the Angular source code) although the library author could decide to use another structure.

The structure for an actual **application** (not a library) would be component driven though, if that makes sense.

**Comment by valorkin** [comment]
just said my IMHO
Angular team actually uses components structure (but call it modules) and MVC separation inside of it

**Comment by jvandemo** [comment]
@valorkin &mdash; I think the Angular repository (in its current form) is hard to compare to a third party library.

However, if we peek inside one of the modules, then we can see a similar structure e.g.: https://github.com/angular/angular/tree/master/modules/angular2/src/common

I think such a structure is probably closer to what most (smaller) libraries will contain.

If you have a larger library that contains *modules* then it definitely makes sense to create a module folder structure. Ultimately the library author should decide.

Although one could argue that it would be better to split into different repositories than in different modules.

Would be great if there is an Angular 2 ecosystem with a lot of very small libraries (as in node).

What are your thoughts on splitting into different repositories? Thanks!

**Comment by valorkin** [comment]
Taking in account user option to to require and bundle only require part of libs
it is awesome opportunity to minimize js size and bootstrap time
(as a consequence of reduced amount of js to be parsed by VM)

modules are optional
splitting in components like this: https://github.com/angular/angular/tree/master/modules/angular2/src
seems to me as proven concept, IMHO

**Comment by NathanWalker** [comment]
@IgorMinar Here is a test lib to experiment with that uses @robwormald's excellent standards proposal above:
https://github.com/NathanWalker/ng2-cli-test-lib

```
npm install ng2-cli-test-lib
```

#### Expectations of cli

- manually npm installing should not be required (cli should handle that)
- questions should be prompted similar to suggestions above to allow the user to specify how they would like the lib added and annotated in their src
- cli should properly add the correct annotations given the lib's standard default exports

#### Sample component to test if it worked

```
@Component({
    selector: 'demo',
    template: `
      <test></test>
      <div>{{title | uppercase}}</div>
    `,
    directives: [.... **hopefully cli will auto add these properly** ...],
    pipes: [.... **hopefully cli will auto add these properly** ...]
})
export class Demo {
    public title:string = "having standards for these libs will help a lot!";

    constructor(private test1:TestService, private test2:TestService2) { }
}

bootstrap(Demo, [.... **hopefully cli will auto add these properly** ...])
```

Given something like the above, you should be able to see this in the console:
![screen shot 2015-12-11 at 12 33 01 am](https://cloud.githubusercontent.com/assets/457187/11739407/1aa163dc-9fa0-11e5-867c-9a2c0f822b19.png)

`TestService` and `TestService2` simply log to console that they have been created properly via DI.
`TestPipe` lets us know it's transforming successfully.

In the browser, this should be seen:
![screen shot 2015-12-11 at 12 34 43 am](https://cloud.githubusercontent.com/assets/457187/11739418/2e959a48-9fa0-11e5-83fb-098637e2e2fe.png)

The `TestDirective` in the lib simply inserts text into the element.

The `TestPipe` simply transforms `title` to uppercase.

#### Conclusions

- If all this works out ok, an official styleguide could be written regarding the authoring of 3rd party libs for Angular2. It would also suggest all lib's mention `angular-cli` as the primary method to add the lib.

btw, @robwormald's registerPlugins (in `pluginHelper.ts`) utility found here http://plnkr.co/edit/Yi1e3ifiX0gSqd8Qs2h4?p=preview is pretty nifty :+1:

**Comment by valorkin** [comment]
@NathanWalker you just made best ng2 starter package for angular 2? You know it right? :)

**Comment by jvandemo** [comment]
@NathanWalker &mdash; Great effort! Thanks!

Once we have settled on a best practice I will also update [generator-angular2-library](https://github.com/jvandemo/generator-angular2-library) accordingly.

**Comment by NathanWalker** [comment]
fyi, testing lib https://www.npmjs.com/package/ng2-cli-test-lib, updated to use latest alpha.53.

@IgorMinar @robwormald if either of you have any opinion on lib name prefix (repo prefix), please share. Most of the discussion has settled on `ng2-` for becoming the standard prefix for all angular2 libs to come. But I think there's still time to settle on something else before the landscape starts to fill up dramatically with `ng2-`.

**Comment by robwormald** [comment]
no real comment on the prefix. 

thinking about the installation process - i'd personally rather use npm. i think it would be reasonable to have package authors add a field to their package.json (something like `"ng" : { "plugin" : true } `) - the CLI can then scan for those. needs a bit more thought on that, but I don't think we want to build a package manager too :)

**Comment by NathanWalker** [comment]
I was thinking the same. Using npm manually is likely universally preferred.
My thought initially on that was more for the pure newbie (new to node, new to angular, etc.) and since it might be rather trivial, it might make sense. The teams best discretion there.

**Comment by gdi2290** [comment]
you should also add `styles`

```typescript
import ng2lib, {MyDirective} from 'ng2lib';
@Component({
  selector: 'app',
  providers: [  ...ng2lib.providers],
  directives: [  ...ng2lib.directives],
  styles: [ ...ng2lib.styles],
  template: `<my-directive></my-directive>`
})
export class App {}
```


parsing `package.json` for the correct keyword `angular2`, `ng2` or, `ng2module` (whatever everyone agrees on) should be prefered when segmenting npm for example [npm search for ng2](https://registry.npmjs.org/-/_view/byKeyword?startkey=[%22ng2%22]&endkey=[%22ng2%22,{}]&group_level=3) (tbh they should really add hashtags to npm)

**Comment by NathanWalker** [comment]
+1, fully integrated :)

**Comment by jvandemo** [comment]
What if a library author would configure `package.json` to run `angular-cli` as an npm postinstall script?

Possible benefits:

- `angular-cli` would automatically run after `npm install`
- library author can configure `angular-cli` to run with options specific to the library
- `angular-cli` itself does not have to be aware of anything, it is the library author that calls `angular-cli`
- backwards compatible: no `postinstall` script => no action is taken
- expandable: the library author could perform other actions as well in the `postinstall` script
- flexible: library author can choose preferred language e.g. JavaScript or bash
- script can be standalone run using `npm run postinstall`

Possible issues:

- What if `angular-cli` is not installed? Should angular-cli be a devDependency?
- Script should be non-interactive to ensure that it can be run unattended e.g. on Travis?

**Comment by ocombe** [comment]
What happens when the end user doesn't want the lib to auto install inside its application?

**Comment by NathanWalker** [comment]
@ocombe In that case, user could simply exit, Ctrl + c, since the install would have completed, they could just exit the `postinstall` angular cli if they didn't want to go through those steps.

@jvandemo great additional thoughts. Using cli manually could still work as suggested/described throughout this discussion and as an option on top of everything, libs could also provide this `postinstall` step as a convenience. I think having it both ways (via through cli directly or via `postinstall` when using `npm` manually to install a lib) doesn't hurt. 

Possible issues:

- What if angular-cli is not installed? Should angular-cli be a devDependency?
**I vote no. It just wouldn't que up angular-cli if it's not installed, or may throw an error after installing. Either way, the lib would describe in its installation steps that installing angular-cli as a prerequisite may help them configure their app to use the lib but it's not required.**

- Script should be non-interactive to ensure that it can be run unattended e.g. on Travis? 
**This alone may make having a `postinstall` step problematic. But if there's an easy way to turn off for Travis, then it would be fine.**

**Comment by NathanWalker** [comment]
Based on @gdi2290 suggestion to handle `styles`, I've updated the test lib to handle this as well.

This works out like the following:
```
import {TestDirective} from './src/app/directives/test.directive';
import {TestService, TestService2} from './src/app/services/test.service';
import {TestPipe} from './src/app/pipes/test.pipe';
import {TestStyles} from './src/app/test.styles';

export * from './src/app/directives/test.directive';
export * from './src/app/services/test.service';
export * from './src/app/pipes/test.pipe';
export * from './src/app/test.styles';

export default {
  directives: [TestDirective],
  pipes: [TestPipe],
  providers: [TestService, TestService2],
  styles: TestStyles.styles(),
  styleUrls: ['src/public/css/test.css']
}
```

This attempts to handle `styles` and `styleUrls` just to experiment with.
The `styles` utilizes a service with a `static` method of inline styles that the lib uses:
```
export class TestStyles {
  public static styles(): string[] {
    return [`
      test a {
        font-size:20px;
        color:blue;
      }
    `];
  }
}
```

This may or may not be the best way forward, but wanted to give you something to experiment with here to handle inline styles as well as styleUrls.

The `TestDirective` is now a link to this repo itself.

### Test if styles were added properly

If all the styles load properly (the inline as well as the style urls), then the directive should render in `blue` with `font-size:20px` (comes from inline style) like so:
![screen shot 2015-12-14 at 8 35 58 pm](https://cloud.githubusercontent.com/assets/457187/11802891/3dce6686-a2aa-11e5-91a3-e84ab16f287c.png)

Additionally if the `styleUrls` load properly, the `:hover` state should be `red` with `text-decoration:none` and use `cursor:pointer` like so:
![cli](https://cloud.githubusercontent.com/assets/457187/11802919/52192dc4-a2aa-11e5-947b-86e9f16af52b.png)

**Comment by ocombe** [comment]
> @ocombe In that case, user could simply exit, Ctrl + c, since the install would have completed, they could just exit the postinstall angular cli if they didn't want to go through those additional steps.

No, it should entirely be optional.
If we use it in the postinstall for npm, then I think that we should have another npm plugin that would be an angular-cli helper, this would be a dependency for your lib, and would check postinstall if angular-cli is installed in this repository, in which case it will install itself (or offer to, we can disable this in CI environment pretty easily), and if not it would just exit.

**Comment by jvandemo** [comment]
> @ocombe &mdash; No, it should entirely be optional.

Agreed, maybe any npm script that is not triggered automatically could do e.g.:

```
$ npm run angular-cli
```

Then it would be optional and the benefits of the script remain.

It would also solve the dependency issue where the consumer would have to have `angular-cli` installed globally to run the script (and thus `angular-cli` doesn't have to be a devDependency).

**Comment by jvandemo** [comment]
> @NathanWalker &mdash; This attempts to handle styles and styleUrls just to experiment with. Styles utilizes a service with a static method of inline styles that the lib uses.

Great work Nathan! What is your reasoning behind using a static method for styles?

**Comment by NathanWalker** [comment]
@jvandemo thanks, it's really just 1 way to do it, no particular reason,
and should be simple to test and experiment with. If you have any ideas on
some other ways to handle both inline styles and/or styleUrls, lemme know.

**Comment by jvandemo** [comment]
@NathanWalker Interesting, because using a function could be convenient to pass in options e.g.:

```javascript
styles: TestStyles.styles({
  flexbox: true
})
```

**Comment by NathanWalker** [comment]
@jvandemo +1 would provide for some very interesting app configurations across various devices ;)

**Comment by NathanWalker** [comment]
https://www.npmjs.com/package/ng2-cli-test-lib updated to `2.0.0-beta.0`

**Comment by NathanWalker** [comment]
Turns out a really cool guy @superchris tried out the lib today on his own brave accord and in the process helped reveal a couple things, of which I just fixed in `1.0.7`. (it was previously installing its own dependencies in `node_modules` (within the lib's folder) after installing).

His project shows an example implementation of the `ng2-cli-test-lib`:
https://github.com/superchris/angular-cli-test

One thing of interest is that the `ComponentMetadata`:
`providers/viewProviders`, 'directives`, and `pipes` all support nested arrays.

However `styles` and `styleUrls` do not.
I'm sure this is for good reason but maybe it should be consistent for all metadata.

Given this, when integrating the library in, I had to do this:
https://github.com/superchris/angular-cli-test/blob/master/src/app/angular-cli-test.ts#L9
Which is not 1/1 consistent with the others. Not sure if this should be reported as an issue or if this difference is warranted. 

Lastly, until the `cli` implements some of the features aforementioned, `styleUrls` will be a more manual process when installing/using 3rd party libs, so I did not implement that in @superchris awesome test project.

**Comment by gdi2290** [comment]
we should be using spread operator whenever possible since it also clearly shows which ones are collections and which ones aren't (as if all caps wasn't enough)
```typescript
import {FORM_DIRECTIVES} from 'angular2/common';
import {APP_PROVIDERS} from '../app-providers';
import {MyDirective} from './my-directive';
import {APP_STYLES, APP_THEME_STYLES} from '../app-styles';
@Component({
  selector: 'home',
  providers: [
    ...APP_PROVIDERS
  ],
  directives: [
    ...FORM_DIRECTIVES,
    MyDirective
  ],
  styles: [
    ...APP_THEME_STYLES,
    `
      .main {
        background: gray;
      }
    `
  ],
  template: `
    <my-directive></my-directive>
  `
})
export class App {}
```
for `styles:` we can use the spread operator for now. I made a pull-request to spread all the collections https://github.com/angular/angular/pull/6049

**Comment by NathanWalker** [comment]
@gdi2290 +1 nice :)

**Comment by jkuri** [comment]
I got something working. See https://github.com/angular/angular-cli/pull/135 
Based on @NathanWalker test lib https://github.com/NathanWalker/ng2-cli-test-lib

**Comment by jkuri** [comment]
Is it possible to add 3rd party library without adding mappings to system config?

**Comment by NathanWalker** [comment]
With @jkuri 's help, we were able to modify `ng2-cli-test-lib` to be compatible with SystemJS specifically.
This makes the lib work with the incredible effort @jkuri put forth here: https://github.com/angular/angular-cli/pull/135

**Comment by jkuri** [comment]
Please check out my last commit. Any suggestions/tests/fixes/comments are very welcome. If someone interested to check it out, here is usage example
```
git clone https://github.com/jkuri/angular-cli -b 3rd-party-libs
cd angular-cli
npm i
[sudo] npm link
```
then create new project using `ng new` somewhere
```
ng new project
cd project
npm link angular-cli
ng libs install ng2-cli-test-lib
ng libs uninstall ng2-cli-test-lib
```
I tested out and the project builds properly, with injecting with custom or automatic injection or uninstalling the lib afterwards (cleans properly).

If this will hopefully be accepted by maintainers we can define how the library must be created to be compatible with `ng libs` command and rework the code afterwards. Now  [ng2-cli-test-lib](https://github.com/NathanWalker/ng2-cli-test-lib) library uses `systemjs-builder` to generate SystemJS compatible format and the script looks like [this](https://gist.github.com/jkuri/d5a3af8cfa1996c8cf6a). 
If we decided to also support other loaders than system, to facilitate the work of developers of the libs, this script can easily be tweaked to export other formats.

**Comment by robwormald** [comment]
The more I think about this idea, the less I like it, at least in regards to automatic code generation and injection and the like. I think it's an overreach for what the CLI should do.

**Comment by NathanWalker** [comment]
I can certainly understand that.

To me, cli tools in general are merely a toolbox containing commands that
make tasks easier. Some use more commands all the time whereas to others
maybe never.

The goal here was to simply offer an additional helpful aid to those that
find it helpful.

Personally, this is the type of tool in the toolbox that I would use for
rapid prototyping where a boss comes to me and says, "I'd like to see
what's possible for this idea by tomorrow." I may not use it all the time
but there are times where I would appreciate it.

I think most advanced users (pros) always have a sour taste for tools that
offer to sugar up an otherwise easy task for them. Git GUI apps vs. command
line: perfect example of this.

In the end, it's just about helpful options to me. Ya like honey on your
toast? Great. And for you, grape jam? Fantastic.

**Comment by jkuri** [comment]
@robwormald you can simply answer "no" to the first questing after installing a lib with that command/task.

**Comment by NathanWalker** [comment]
This has been merged. Documentation is here: https://github.com/angular/angular-cli/pull/173
