### ISSUE TITLE
Creating new angular 2 app w/cli

### ISSUE THREAD

**Issue by oncalldev** [angular/angular-cli#960]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 8.1
2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.5
node. 4.2.4
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Installed angular2 cli as per website instructions.  Creating demo app:  ng new my-dream-app.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Did not see any log files.
See attached screen dump.
![angluar-cli-installation-error](https://cloud.githubusercontent.com/assets/3887610/15652159/ca822252-2649-11e6-8fd1-f522a91c5756.png)

5. Mention any other details that might be useful.
I tried running ng serve and got the error:  TypeError: cli is not a function.  

The initial angular-cli appeared to install properly.  I believe the only error message I saw referred to a deprecated reference to to lodash.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
ECONNRESET is usually a network issue. Can you try again and tell me if it still happens?

**Comment by oncalldev** [comment]
FIRST TRY: Just tried it again and the same error came up.  It took about 30 seconds from the time “Installing packages for tooling via npm” displayed and the error in events.js:141 with the unhandled ‘error’ event message came up.  I’m not really a full-fledged front end developer in the open source sense (more of a .NET person) so I just followed the instructions given on the angular cli website for creating a new angular 2 project (ng new my-dream-app) and hoped for the best.

 

SECOND TRY:  I thought I’d play around a bit and upgraded my version of node.js from v4.2.4 to 4.4.5 and it seemed make things better – no error.  It took a long time to download all the files and there does seem to be a lot of files.  When I checked the folder holding my-dream-app it had 41,462 files and 7,367 folders.  Seems like it had everything and the kitchen sink.  I did run ng serve and I got the “my-dream-app-works” in my browser.  Do the number of files/folders seem about right?

**Comment by filipesilva** [comment]
Yeah the insane amount of folders/files is the norm in the node world... In this specific case it's worsened by the fact that CLI projects include `angular-cli` itself as a dependency for backwards compatibility. 

Regarding the node version, I should have noticed that earlier - we recommend node 5 and up and that's how we do our CI tests. Regardless, I'm glad that it now works for you!
