### ISSUE TITLE
Bug. Hot module replacement breaks material dialog styles

### ISSUE THREAD

**Issue by Yerkon** [angular/angular-cli#9600]
### Versions
```
Angular CLI: 1.5.0
Node: 8.9.4
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.5.0
@angular/material: 5.0.0-rc.2
 angular-devkit/build-optimizer: 0.0.42 
 angular-devkit/core: 0.0.29
angular-devkit/schematics: 0.0.52
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.8.0
schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.8.1
Windows 10
```

### Repro steps

* We have material dialog, which opened dynamically with component content. Component itself included in module `entryComponents `property
* `ng serve --open --environment=dev --hmr`. Changing component, template, css files triggers hmr. Everything is fine, but 
* when in application some dialog is opened and file changes triggers `hmr`. Styles(css) of dialog is breaking down. 
* We can solve it in two ways:
   * Reload full page(F5)
   * Delete from the dom opened dialog box. 

### Desired behavior

HMR should not break the opened dialog boxes styles.

**Comment by clydin** [comment]
Successful hot module replacement requires the components to be designed to support it.  This is unfortunately not something the CLI can solve.

**Comment by Yerkon** [comment]
`components to be designed to support it`

@clydin,  How you identify that the component support it or not? How to design component to support it?

**Comment by yacineblr** [comment]
Same for me, HMR breaks the MatDialog style ..

**Comment by fergardi** [comment]
Any news or workarounds about this issue? I find it extremely annoyed and end up wrapping my dialog component into a simple page view to work on it until is finished.
