### ISSUE TITLE
Unhandled Promise rejection: A platform with a different configuration has been created. Please destroy it first. ; Zone: <root> ; Task: Promise.then ; Value: Error: A platform with a different configuration has been created. Please destroy it first

### ISSUE THREAD

**Issue by PankajKumar83** [angular/angular-cli#9601]
### Versions

Angular CLI: 1.6.7
Node: 6.11.5
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router, upgrade

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.6.7
@angular/compiler-cli: 5.2.2
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.6.1
webpack-dev-server: 2.4.5
webpack: 3.10.0

### Repro steps
I am trying to create a hybrid app using ng1 and ng2. It is working fine in --dev build, but has issue with prod build.

app.module.ts code:

import { NgModule, forwardRef } from '@angular/core';
import { UpgradeAdapter, UpgradeAdapterRef } from '@angular/upgrade';

import { AppComponent } from './app.component';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import {UpgradeModule} from '@angular/upgrade/static';
import {downgradeComponent} from '@angular/upgrade/static';

//export const UPGRADE_ADAPTER = new UpgradeAdapter(forwardRef(() => AppModule));

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    UpgradeModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(private upgrade: UpgradeModule) { }
  ngDoBootstrap() {
    this.upgrade.bootstrap(document.body, ['xyz'], { strictDi: true });
  }
 }

 
 main.ts Code:
 
// import polyfills
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';

//import { AppModule, UPGRADE_ADAPTER } from './app/app.module';
import { AppModule } from './app/app.module';
import { enableProdMode } from '@angular/core';
import { environment } from './environments/environment';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

if (environment.production) {
  enableProdMode();
}

 platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));

// platformBrowserDynamic().bootstrapModule(AppModule).then(platformRef => {
//   UPGRADE_ADAPTER.bootstrap(document.documentElement, ['xyz']);
// });

//platformBrowserDynamic().bootstrapModule(AppModule).then(ref => {
 // const upgrade = (<any>ref.instance).upgrade;
  // bootstrap angular1
  //upgrade.bootstrap(document.body, ['xyz']);
//});

### Observed behavior
![image](https://user-images.githubusercontent.com/36400643/36090827-c68f4cc0-1007-11e8-9696-ed29270e3dd5.png)

### Desired behavior
Prod build should also work as expected.

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
