### ISSUE TITLE
ng new does not create a new project

### ISSUE THREAD

**Issue by borisekm** [angular/angular-cli#9602]
Cannot create a new project via ng new [project name]. Tested with cmd, powershell, git bash and Intellij Idea.

### Versions
Windows 10 (10.0.16299.125)
Angular CLI: 1.6.8
Node: 9.5.0
OS: win32 x64
Angular:
...

### Repro steps
ng new angular_test

### Observed behavior
Error message: Project name "angular_test" is not valid. New project names must start with a letter, and must contain only alphanumeric characters or dashes. When adding a dash the segment after the dash must also start with a letter.

### Desired behavior
New project is created

### Mention any other details that might be useful (optional)
I uninstalled and installed angular cli. Older version 1.6.1 works as expected.

**Comment by dkearsley89** [comment]
Isn't this simply because you used an underscore instead of a dash? '_' vs '-'

**Comment by borisekm** [comment]
my bad 👎 (
