### ISSUE TITLE
Allow more options into dev server

### ISSUE THREAD

**Issue by dfenstermaker** [angular/angular-cli#9610]
At the moment I am trying to use the built in [apiHistoryFallback rewrites feature](https://github.com/webpack/docs/wiki/webpack-dev-server#the-historyapifallback-option) and I am being blocked, unless I want to eject out of the cli. 

Currently the webpack dev server [configs are housed inside of the cli tasks for serve](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/tasks/serve.ts#L212). This limits the options that can be passed to the server and there is no way, that I am aware of, to cleanly get options into the config. I would like to propose that the base config be moved into the .angular-cli.json file and consumed inside the serve task from this file. This would allow developers to pass command line args, as is used now, for the majority of their needs. This would allow developers to edit the config as they see fit, while also taking the burden off of the cli team to maintain every feature of the dev server as that feature set grows.

I would be more than happy to submit a pr for this feature should you see it a good fit for the cli.

### Versions
```
@angular/cli: 1.4.9 (e)
node: 8.4.0
os: darwin x64
@angular/animations: 4.4.5
@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.4.9
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/compiler-cli: 4.4.6
@angular/core: 4.4.5
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/language-service: 4.2.4
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/router: 4.4.5
typescript: 2.5.3
```

### Repro steps

* use ng serve
* Try and accomplish a rewrite for a url via the dev server

### Observed behavior
```
doesn't allow me to do this
```

### Desired behavior
allow me to do this

**Comment by smnbbrv** [comment]
@dfenstermaker why don't you use [proxy](https://github.com/angular/angular-cli/wiki/stories-proxy)? It can do everything you described

**Comment by dfenstermaker** [comment]
@smnbbrv to my knowledge proxy is to allow you to proxy to another running server, right? where as I need to serve a static file from the same server. After some reading it appears this may be possible but does not seem like an intended use case for proxy.

**Comment by clydin** [comment]
The purpose of the proxy option is to proxy requests.  The locality of the destination is essentially irrelevant.  Proxying to a different server, the same server, or even the same destination but with an altered request are all use cases for a proxy.

**Comment by dfenstermaker** [comment]
thanks I will try this. However, is the feeling that you should not have more control over the configs for dev server? makes sense that proxy may be able to do this, but it is not obvious, and people will want to use the other functionality available in the dev server

**Comment by dfenstermaker** [comment]
@smnbbrv @clydin thanks! I was able to get the proxy working for my use case.

**Comment by smnbbrv** [comment]
> However, is the feeling that you should not have more control over the configs for dev server? makes sense that proxy may be able to do this, but it is not obvious, and people will want to use the other functionality available in the dev server

Your concerns make sense, however I think the keyword here is dev server, which should remain dev (dumb and simple). It covers 99% of the use cases out of the box; I use the proxy for hosting 2 apps at once and I'm not proud of that too. However it works pretty fine.

Whenever the given functionality is not enough it is quite easy to set up a standard nginx (locally or in a docker container) and put it on top of the dev server. This gives you the full power of an industrial standard web server at your service and it has everything you want.

**Comment by dfenstermaker** [comment]
@smnbbrv I agree that the server should remain dumb. However, the features were made available in the dev server to make some of these features easier to use and understand. 

Regarding the idea that nginx is "easy" to setup locally is over simplifying that process and the knowledge it takes to do this. In addition creating this behavior inside of a docker container running nginx locally is not an ideal setup when a simple json object inside of the dev server would provide this behavior.  In fact I am trying to use this feature due to our prod and staging environments being inside of a nginx docker container, I would prefer not to have to replicate that alias in a local container. To me this over complicates the process.

All that said the proxy worked and seems to provide a sleek solution so thanks again
