### ISSUE TITLE
Vendor Chunk can't be generated in a Yarn Workspace

### ISSUE THREAD

**Issue by shaungrady** [angular/angular-cli#9611]
### Versions
```
Angular CLI: 1.6.8
Node: 8.8.0
OS: darwin x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
Use [this demo repo](https://github.com/shaungrady/ng-cli-yarn-workspaces-bug), or...
* Step 1: Create a Yarn workspace [as outlined here](https://yarnpkg.com/lang/en/docs/workspaces/#toc-how-to-use-it).
* Step 2: Ensure you have an ng-cli workspace.
* Step 3: Run `yarn workspace <workspace-name-here> ng build --vendor-chunk=true`.

### Observed behavior
No vendor chunk will be produced.

### Desired behavior
A vendor chunk to be produced.

### Mention any other details that might be useful (optional)

Looking at the source, the `projectPath` is defined by where `.angular-cli.json` resides, [as seen here](https://github.com/angular/angular-cli/blob/00ca690807a2326b6e8632a9a0ec46587b841a78/packages/%40angular/cli/models/webpack-config.ts#L37).

When `buildOptions.vendorChunk` is set, the `node_modules` path is set as being a child of `projectPath`, [as seen here](https://github.com/angular/angular-cli/blob/00ca690807a2326b6e8632a9a0ec46587b841a78/packages/%40angular/cli/models/webpack-configs/browser.ts#L28).

This behavior is all well and good, except when it comes to Yarn Workspaces. Yarn generates a `node_modules` folder inside each workspace—**_however_**, that `node_modules` directory does not contain package sources. So if ng-cli is inside a workspace, the `node_modules` inside that `projectPath` is essentially empty. Instead, package sources are located at the root of the Yarn Workspaces project, also in a `node_modules` folder.

This fix for this is to find the Yarn Workspaces root, if one exists, and use the `node_packages` directory inside that root as `nodeModules` path [on this line](https://github.com/angular/angular-cli/blob/00ca690807a2326b6e8632a9a0ec46587b841a78/packages/%40angular/cli/models/webpack-configs/browser.ts#L28).

I've created a demo repo here: https://github.com/shaungrady/ng-cli-yarn-workspaces-bug

**Comment by filipesilva** [comment]
Is this still a problem with recent Angular and CLI versions?

**Comment by alan-agius4** [comment]
Closing as we didn’t hear back from the author of this issue.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

Thanks.
