### ISSUE TITLE
LESS 3.0 has been released

### ISSUE THREAD

**Issue by thorn0** [angular/angular-cli#9613]
### Desired behavior

Upgrade to LESS 3.0.
https://github.com/less/less.js/blob/master/CHANGELOG.md#300

### Mention any other details that might be useful (optional)

Ensure [`@plugin` at-rules](http://lesscss.org/features/#import-atrules-feature) work.

**Comment by clydin** [comment]
This is blocked on support in [less-loader](https://github.com/webpack-contrib/less-loader).  Relevant issue: https://github.com/webpack-contrib/less-loader/issues/239

**Comment by imkremen** [comment]
@clydin Less 3 support is now fixed in less-loader https://github.com/webpack-contrib/less-loader/releases/tag/v4.1.0

**Comment by clydin** [comment]
This will be included in 6.0.0 of the CLI.
