### ISSUE TITLE
@angular/cli 1.6.8

### ISSUE THREAD

**Issue by mtizziani** [angular/angular-cli#9614]
### Versions
```
Angular CLI: 1.6.8
Node: 8.9.3
OS: win32 x64
Angular:
...

```

### Repro steps

* ng new project --style=less

### Observed behavior
```
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
```

### Desired behavior

changing from deprecated to stable will help everybody (security, improvements ...) and warnings are never good ;)

**Comment by clydin** [comment]
The latest version of the CLI addresses these concerns.  Please also note that 1.x of the CLI is no longer a supported version series.
