### ISSUE TITLE
net::ERR_CONNECTION_REFUSED in using proxy.conf.json

### ISSUE THREAD

**Issue by faribajpr** [angular/angular-cli#9622]
normally when i use npm start and ng serve, i can load my app on localhost:4200 and then i have a login page at url localhost:4200! after click the button for login, i have a service that send a REST to localhost:3000/authentication/login! 
now,this is my proxy.config:
```
{
  "/authentication/login" : {
    "target": "http://localhost:3000/authentication/login",
    "changeOrigin": true,
    "secure": false
  }
}
```
but when i click on the button to login, i get the error => http://localhost:3000/authentication/login net::ERR_CONNECTION_REFUSED

i think i didn't understand how to create the proxy file completely! what should i do?

**Comment by ctrl-brk** [comment]
Here's my proxy which works for me (it uses windows auth, so you can remove it if not needed)
```
const Agent = require('agentkeepalive');

// noinspection JSUnusedGlobalSymbols
module.exports = {
  '/api/*': {
    target: 'http://localhost:5000',
    secure: false,
    agent: new Agent({
      maxSockets: 100,
      keepAlive: true,
      maxFreeSockets: 10,
      keepAliveMsecs: 100000,
      timeout: 6000000,
      keepAliveTimeout: 90000
    }),
    onProxyRes: proxyRes => {
      let key = 'www-authenticate';
      proxyRes.headers[key] = proxyRes.headers[key] && proxyRes.headers[key].split(',');
    }
  }
};

```

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by markzolotoy** [comment]
@ctrl-brk. The code you showing is it a proxy.config.js file? Do I use both proxy.config.js and proxy.config.json files?
