### ISSUE TITLE
http.get not work but http.post work...

### ISSUE THREAD

**Issue by skMun** [angular/angular-cli#9623]
hi. my cli version 1.6.8

proxy.js 
const PROXY_CONFIG = [
    {
        context: [
            "/api",
            "/modules"
        ],
        target: "http://dev.localhost.com/",
        secure: false,
        pathRewrite: {
            "^/": "/"
          },
        changeOrigin: true,
        logLevel: "debug"
    }
]

module.exports = PROXY_CONFIG;

package.json

"start": "ng serve --output-hashing=all --aot=false --vendor-chunk=true --live-reload=false --sourcemap=false --proxy-config proxy.conf.js",

this poxy only http.post work and http.get not work

post console message

[HPM] Rewriting path from "/api/member/login.php" to "/api/member/login.php"
[HPM] POST /api/member/login.php -> http://dev.localhost.com/

but get is not work

I do not know why I have these symptoms.

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
