### ISSUE TITLE
Component css sourcemap broken in ≥1.7.0-beta.3

### ISSUE THREAD

**Issue by kondi** [angular/angular-cli#9626]
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.0-beta.3
Node: 7.4.0
OS: win32 x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.0-beta.3
@angular-devkit/build-optimizer: 0.2.0
@angular-devkit/core: 0.2.0
@angular-devkit/schematics: 0.2.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.0-beta.3
@schematics/angular: 0.2.0
@schematics/package-update: 0.2.0
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
* Add any css rule to a component (kondi/ng-cli-sourcemap@0526343)
* `ng serve`: css sourcemaps are served with 1.7.0-beta.2 (kondi/ng-cli-sourcemap@f96e88e)
* `ng serve`: css sourcemaps are not served with ≥1.7.0-beta.3 (kondi/ng-cli-sourcemap@425c674)

### Observed behavior
![image](https://user-images.githubusercontent.com/278688/36208865-7589e094-119a-11e8-877a-1f62dfa8dae4.png)

### Desired behavior
![image](https://user-images.githubusercontent.com/278688/36208908-955d2c00-119a-11e8-805a-35ac7d80910f.png)

### Mention any other details that might be useful (optional)

This was definitely the killer feature of 1.7 for me when introduced in v1.7.0-beta.0 (angular/angular-cli@883c022). I was so happy to see it, was very useful for bigger projects.

**Comment by clydin** [comment]
This should be functional in the latest version of the CLI (6.2.3 currently).  If you are still encountering this with the latest version, please open a new issue detailing the version and environment information of the failing project.
