### ISSUE TITLE
Large Assets with NG Serve - Memory usage / Compile time issues

### ISSUE THREAD

**Issue by NoCopy** [angular/angular-cli#9629]
### Versions
```
Angular CLI: 1.6.4
Node: 8.4.0
OS: Windows 10
Angular: 5.2.0
```
I'd like to re-visit #8447 but unfortunately I can not simply re-open the issue so I apologize in advance for the duplicate. 

### Repro steps

* Same as #8447
* In addition, live reload / hmr ignores changes in the assets folder until a source code change has been made

### Desired behavior
An ng serve flag / angular-cli configuration option to enable loading of assets (or specific folders) from HD instead of compiling into memory with ng-serve. Likewise, they should be optionally ignored from build time procedures as well.

### Reasoning
While the proxy option pointed out in #8447 is a necessary and valid option for API functionality I don't believe that to be the case for assets for the following reasons:

* The CLI has done a great job of abstracting away the configuration issues for any given developer, however in this case, the CLI goes against that design philosophy by presenting additional config / burden simply to serve assets from a directory.
* The performance implications are practically negligible
* Assets are mostly static, I fail to see the reasoning or intention to reload / cache these while the browser is doing the very same thing
  * Even for a small asset payload this doesn't really make sense.
* Build time / distribution of dev assets is an Tech Managers / Release Engineer's job, we can figure out how to get the assets to the appropriate folder without burdening a developer with extra work such as setting up a proxy. It should just be "ng serve" without the risk of crashing.

**Comment by alan-agius4** [comment]
Hi @NoCopy,

Thanks for this issue, and while the issue still exists. Very few people are effected by it. As such there are no plans to change this behaviour in the near future.
