### ISSUE TITLE
Surprising difference in behavihor between --prod and --env="prod"

### ISSUE THREAD

**Issue by Shiso** [angular/angular-cli#9630]
### Versions
```
@angular/cli: 1.4.4
node: 8.6.0
os: darwin x64
@angular/animations: 4.4.4
@angular/cdk: 2.0.0-beta.11
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/material: 2.0.0-beta.11
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4

Mac Sierra 10.12.6
```

### Repro steps and observed behavior

ON any project:
1/ try to build it with --prod. It will generate the correct files.
2/ try with the attribute --env="prod" it will genrate the files with the expected environment BUT it won't benefit from the cache busting hashing on each files.

### Desired behavior
I don't see a reason for the difference in behavior such as this one, i think you expect ---prod to be an alias for --env="prod" (witch i did and had build a script where a parameter would be the env of the build, causing much trouble on our production website.

**Comment by SchnWalter** [comment]
You should check this page: https://github.com/angular/angular-cli/blob/v1.6.8/docs/documentation/build.md

The `--prod` differs a lot from `--environment=prod`.

**Comment by Brocco** [comment]
@SchnWalter is correct, they are very different. Please refer to the docs [here](https://github.com/angular/angular-cli/wiki/build#--dev-vs---prod-builds) in the [wiki](https://github.com/angular/angular-cli/wiki).

**Comment by Shiso** [comment]
I realised the difference and i'm sorry i've never seen this page before.

I guess the name is confusing then, considering there is almost no difference between the two literal options, i still think the difference should be more explicit.
But in the end i understand that there is a limit to be decided on where you stop holding users hands.

Thanks for your time.
