### ISSUE TITLE
Simultaneous CLI installs crash

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#9633]
### Versions
1.6.8

### Repro steps

Launch several installations of the CLI (either globally or by creating a new app) at the same time on the same network.

```
npm install @angular/cli -g
```
or
```
ng new someapp
```

### Observed behavior
Some installations will fail due to too much things to download.

### Desired behavior
Should work.

### Mention any other details that might be useful (optional)
I think it's not a problem for common folks, as each developer installs the CLI at a different time. But it's a real problem during Angular courses where every student has to install the CLI at the same time.

During one of my last workshops, we were close to have to cancel the course because of this technical issue (and it was just 8 people, so I don't even imagine with big groups...). And it's not linked to a specific network. The problem has been showing in many different companies from the last months. And on networks with a good bandwidth (fiber).

It's quite hard to spot the exact problem (and maybe several issues are involved here). One possibility based on some tests is that there is so much downloads on npm registry that the DNS server is starting to stop or delay requests at some point.

I know the CLI is not directly the problem here. There is some options with npm to mitigate this issue and I've created an issue in their repo npm/npm#19828. But in the end it's because the CLI has become a crazy huge package due to all the dependencies.

Are the plans for 2.0 (separation of global and local CLI) going to help about this ?

**Comment by hansl** [comment]
We hope so, but don't expect this problem to entirely go away. Separation of global and local will only help for installing globally, not when using `ng new`. In that case it will be pretty much the same amount of installation.

Closing this as it's not a plan and out of our control.

**Comment by cyrilletuzi** [comment]
That's not totally out of control. There could be options (or even auto detect) to only install what is necessary. For example, all Sass/Less/Stylus tools are installed even if they are not used.

**Comment by clydin** [comment]
One suggestion is to look at setting up a caching proxy (registry or web).   They are designed to alleviate the network issues described above and are really the true solution to the problem.
