### ISSUE TITLE
ng build production, copy different assets files by different environment

### ISSUE THREAD

**Issue by astalegale** [angular/angular-cli#9634]
Hi guys,

i wonder if is possible to copy different assets files by different environment build.

Thanks
Alex

**Comment by filipesilva** [comment]
No, this is not possible currently. I will mark it as a feature request.

**Comment by astalegale** [comment]
thanks

**Comment by robertlevy** [comment]
The docs point to this being supported:  https://angular.io/guide/workspace-config#additional-build-and-test-options. 

And it's working for me with this structure in angular.json:

      "architect": {
        "build": {
         ...
          "options": {
            ...
            "assets": [
               // default assets
            ],
          },
          "configurations": {
            "foo": {
              "assets": [
                 // assets for the "foo" environment
               ]
             }
             ...
         },
        "serve": {
          ...
          "configurations": {
            "foo": {
              "browserTarget": "app:build:foo"
            },
           ...

**Comment by filipesilva** [comment]
Closing as per https://github.com/angular/angular-cli/issues/9634#issuecomment-486691641, this is now supported with the current configuration options.
