### ISSUE TITLE
docs(generate): add appShell and universal to generate docs (wiki)

### ISSUE THREAD

**Issue by Splaktar** [angular/angular-cli#9639]
The `ng generate` command is documented on the wiki here: https://github.com/angular/angular-cli/wiki/generate

This list is missing `universal` and `appShell`. It would be helpful to have these schematics and their options documented there.

Thank you.

**Comment by hiepxanh** [comment]
yeah we need it

**Comment by alan-agius4** [comment]
https://angular.io/cli/generate
