### ISSUE TITLE
Options to disable WebDevServer's historyApiFallback

### ISSUE THREAD

**Issue by eib** [angular/angular-cli#9640]
Currently, `ng serve` will serve up the index page whenever an HTTP 404 error would otherwise occur. There are several instances where this is problematic:
* You've configured the router to use URL fragments (aka "#" hash) and want local development server to mirror production usage -- so that "works on my machine" isn't as possible
* You're trying to serve a new file and you're not sure if it's being bundled/output/copied successfully. It's frustrating when you try to browse around to find the new file and get index.html contents instead

### Repro steps
* Configure your angular app's router to use URL fragments (aka hash, "#")
* Possibly make changes to `.angular-cli.json`
* Open http://localhost:4200/page-that-does-not-exist.html

### Observed behavior
* http://localhost:4200/page-that-does-not-exist.html will serve up the app's index page

### Desired behavior
* I want those 404 Not Found's!

### Notes
While it would be *fantastic* if the cli could inspect the app to determine that the router was configured with [`{ useHash: true}`](https://angular.io/api/router/ExtraOptions#members), I'd also be willing to accept a command-line parameter or some new option in `.angular-cli.json`.

The 404-handling is using WebpackDevServer's [.historyApiFallback option](https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback).

See also: [./packages/@angular/cli/tasks/serve.ts](https://github.com/angular/angular-cli/blob/a40e801a954fd4b79e8f042f9e1692971feadf9e/packages/%40angular/cli/tasks/serve.ts#L214)

**Comment by anupamarachuri** [comment]
Did you find a solution to this? Having a similar problem.

**Comment by drdamour** [comment]
did this ever get exposed from angular.json so you could pass thru a false value?

**Comment by alan-agius4** [comment]
Thanks for this feature request.

Since this is not a common option that users needs to set. We feel that for this option it's a better fit to use a custom builder such as https://github.com/manfredsteyer/ngx-build-plus or https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack
