### ISSUE TITLE
Load locale at runtime

### ISSUE THREAD

**Issue by voliseq** [angular/angular-cli#9643]
Error when trying to import locale at runtime
### Versions

Angular CLI: 1.7.0
Node: 9.4.0
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.7.0
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.4.2
webpack: 3.11.0

### Repro steps
* Try to dynamically import locale 
`import(`@angular/common/locales/${localeName}.js`).then(locale => {
    registerLocaleData(locale.default);
});`
### Observed behavior
Error : "You may need an appropriate loader to handle this file type"
### Desired behavior
Locale is loaded

**Comment by intellix** [comment]
I believe this should already be handled automatically with the `--locale` flag when building or serving

**Comment by clydin** [comment]
Please provide the information requested in the issue template so that you can be further assisted.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
