### ISSUE TITLE
Error: Can't resolve 'webpack-dev-server/client?http://0.0.0.0:0' [1.7]

### ISSUE THREAD

**Issue by Toxicable** [angular/angular-cli#9644]
### Versions
```
Angular CLI: 1.7.0
Node: 8.9.4
OS: linux x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.1
@angular/cli: 1.7.0
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.2.1
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.4.2
webpack-node-externals: 1.6.0
webpack: 3.10.0
```

### Repro steps
Havn't got a repro sorry :/

### Observed behavior
```
ERROR in multi webpack-dev-server/client?http://0.0.0.0:0 ./path/to/main.ts
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://0.0.0.0:0' in '/home/f.wiles/Documents/projectname'
```

### Mention any other details that might be useful (optional)
This is a medium sized project using `yarn` as the package manager
```
$ npm ls webpack-dev-server
projectname@0.0.0 /home/f.wiles/Documents/project-name
└─┬ @angular/cli@1.7.0
     └── webpack-dev-server@2.11.1
```
I've also tried deleting both `yarn.lock` and `node_modules` but the same error is observed

**Comment by funkizer** [comment]
Just upgraded everything in an app that worked on previous versions, and got the same error. Easy to repro, just run `ng new test-app` and `ng serve`.

**Comment by funkizer** [comment]
Work-around: install @angular/cli@1.6.8 and hope 1.7.1 has better luck.  :)

**Comment by alexgoldstone** [comment]
Exactly the same issue. Downgrading from 1.7.0 to 1.6.8 worked for me. I'm not sure what other information beyond the original report will be relevant but happy to provide more if prompted.

**Comment by alrazex** [comment]
**Versions**
Angular CLI: 1.7.0
Node: 8.9.4
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.40
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack-bundle-analyzer: 2.9.1
webpack: 3.11.0

I had the same issue and it got resolved after i re-run npm install @angular/cli@1.7.0 ?!?!?

**Comment by alrazex** [comment]
I had the same issue and it got resolved after i manually re-run npm install @angular/cli@1.7.0.

**Comment by MatthewEppelsheimer** [comment]
@alrazex 's solution worked for me as well:

> `manually re-run npm install @angular/cli@1.7.0`

**Comment by nagrito** [comment]
I had the same issue after upgrading to CLI 1.7.0
Did as @alrazex did with re-run `npm install @angular/cli@1.7.0`
And that works for me.
thanks

**Comment by thisisbb** [comment]
@hansl this issue is reproducible with ```angular/cli@1.7.4``` in IE
Should this really be closed ?
