### ISSUE TITLE
ng update error: Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by ayush987goyal** [angular/angular-cli#9646]
### Versions
```
Angular CLI: 1.7.0
Node: 8.9.3   
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms        
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.0                                                           
@angular/cli: 1.7.0
@angular/material: 5.1.0                                                     
@angular-devkit/build-optimizer: 0.3.1                                   
@angular-devkit/core: 0.3.1                                                      
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps

* Step 1 run `ng update`

### Observed behavior
following error is thrown
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

### Desired behavior

It should properly update the dependencies

### Mention any other details that might be useful (optional)

Running this behind a corporate proxy. Does `ng update` take that into consideration?

**Comment by ssougnez** [comment]
Hello,

I don't think it does. For me, the error is the following:

> events.js:182
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: connect ETIMEDOUT 151.101.36.162:80
>     at Object._errnoException (util.js:1024:11)
>     at _exceptionWithHostPort (util.js:1046:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1185:14)

**Comment by hansl** [comment]
> Running this behind a corporate proxy. Does ng update take that into consideration?

No. It needs access to npm. Adding an npm proxy flag would help.

**Comment by ssougnez** [comment]
I don't think it's enough as I'm using a proxy for npm (otherwise it wouln't work) and I aslo changed the default registry to the "http" version (as the proxy I'm behind was causing issue with the "https") and I have the issue mentioned above.

**Comment by hansl** [comment]
The flag should be on the update function itself :)  We contact the npm registry directly, not passing through npm API, so there's nowhere you can set that proxy right now.

**Comment by billfranklin** [comment]
confirm, also affecting me.  PC behind corporate firewall fails, identically configured PC outside firewall works.  v1.7.1

**Comment by ayush987goyal** [comment]
@hansl when is this getting targeted?

**Comment by dominikg** [comment]
this also happens using the migrate-only flag
`ng update @angular/cli --migrate-only --from=1.7.3`

**Comment by ayush987goyal** [comment]
Issue persists with v6.0.0-rc.3

**Comment by jmdmao** [comment]
I do not use corporate internet, nor firewall. Even so, `ng update @angular/cli --migrate-only --from=1.7.4` only returns
`events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 151.101.92.162:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)`

**Comment by ayush987goyal** [comment]
The issue still persists with v^6.0.0

With the latest release of Angular, we are in desperate need of `ng update` to work in our environments. Can this issue be addressed on priority?

**Comment by AlgoTrader** [comment]
I also experience ng update problems behind corp proxy. Please make it high priority

**Comment by icorne** [comment]
Are you still getting this? 
I've manually updated my project local angular/cli to 6.0.0 (so no rc)
and it works with the following call: (real values are different ofc)

ng update --registery http://my-registery.local/repository/npm-all --proxy proxy.server:9999

**Comment by AlgoTrader** [comment]
ng update always write 
`unable to verify the first certificate`

With NODE_TLS_REJECT_UNAUTHORIZED=0 i get
`SSL Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE`

**Comment by mevlts** [comment]
I have getting same problem now.

**Comment by mgechev** [comment]
This should be a solution to the problem https://github.com/angular/angular-cli/issues/9646#issuecomment-386568489
Make sure you're using the latest CLI.

**Comment by woppa684** [comment]
@mgechev ... but proxy is not a valid argument to ng update, and only registry isn't enought because when I use our internal registry then it starts complaining about the authentication of course :)

```
Unable to authenticate, need: Bearer, Basic realm="<our repo>", Negotiate, NTLM
```

**Comment by hbthanki** [comment]
If anyone is still facing issue, from moving angular 5.2 to 7, following worked for me:

- yarn global add @angular/cli
- yarn add @angular/cli
- update @angular/cli --packageManager yarn
