### ISSUE TITLE
ng update does not update from beta

### ISSUE THREAD

**Issue by karptonite** [angular/angular-cli#9652]
### Versions
```
Angular CLI: 1.7.0
Node: 9.3.0
OS: darwin x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.7.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.6.2
webpack-bundle-analyzer: 2.10.0
webpack: 3.11.0

```

### Repro steps
run `ng update --dry-run` when package.json specifies, for example, `"@angular/core": "^5.0.0-beta.7",`

### Observed behavior
```
Error: Range >=5.0.0-beta.7 is not compatible with >=5.2.5
Range >=5.0.0-beta.7 is not compatible with >=5.2.5
```

### Desired behavior
ng update should install the latest 5.x.x, according to https://docs.npmjs.com/misc/semver

Actually, it may not be that it won't update--it may just be that version compatibility detector doesn't understand that `>=5.0.0-beta.7` is in fact compatible with `>=5.2.5`

**Comment by clydin** [comment]
Closing this as `ng update` has been completely redesigned for 6.0.
