### ISSUE TITLE
ng eject: for dev and prod, why you need to generate several configs

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#9657]
Completely different command (generate different configs):

```
$ ng eject 
$ ng eject --prod
```

This is very inconvenient, it is impossible to configure configurations. Why do not you use one config for everything using webpack-profiles? Or something convenient for easy configuration of webpack?

https://www.npmjs.com/package/webpack-profiles

```ts
var webpack = require('webpack');
module.exports = {
   
   common: {


   },

    production: {
        vars: { //section with variables passed to webpack.DefinePlugin 
            API_URL: "'http://my.api.com'"
        },
        config: { //section with config merged with main webpack config 
            devtool: 'source-map',
            plugins: [
                new webpack.optimize.UglifyJsPlugin()
            ]
        }
    },
    dev: {
        activeByDefault: true, // profile will be triggered if no profiles passed via cmd or options 
        vars: {
            API_URL: "'http://localhost:8080'"
        },
        config: {
            devtool: eval
        }
    },
    ...
};
```

**Comment by jotatoledo** [comment]
To have multiple configuration you should use --force flag as described [in the docs](https://github.com/angular/angular-cli/wiki/eject).

I agree that it seems kind of odd to run ng eject more than once to generate multiple configurations in the file.

**Comment by splincode** [comment]
Maybe they will set `true` for flag force? And 500 lines webpack.config.js of configuration are too cruel...

**Comment by robwormald** [comment]
The entire webpack config in a CLI app is built up dynamically, so there are no webpack files, as such. The ejected webpack configs are basically just a dump of the internal state, they're not hand-coded. Given that our primary goal is to keep you IN the CLI, we're unlikely to devote a huge amount of time to making this too much easier.

If you've got a better idea, we're all ears, but with this basic constraint: we are not interested in keeping things "in sync" - that is, having a separate webpack config file we have to synchronize/keep up to date every time we make a change to the CLI mechanics. Any additional dependencies have to be tested, kept up to date, license verified, etc etc. 

If complete control of Webpack is something you want, then we suggest using the standalone `@ngtools/webpack` package in your own Webpack setup. While I appreciate that may be inconvenient for you, it's equally inconvenient for us to maintain and track an ever growing list of dependencies for a feature we want to avoid you using in the first place!

**Comment by splincode** [comment]
Well, do you have any ideas other than using a webpack starter for the project in conjunction with the CLI?
I also want to have ng update. But we are forced to use a webpack starter...
