### ISSUE TITLE
Error: Maximum call stack size exceeded Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by mikeandersun** [angular/angular-cli#9664]
I install `@angular/cli 6.0.0-beta.2` as globally. Then try to create a new project  like this:
`ng new  ng6-app`
and got the following error:
`Error: Maximum call stack size exceeded Maximum call stack size exceeded.
`
This a b known bug?

**Comment by mgechev** [comment]
@mikeandersun can you still hit this issue?

**Comment by mgechev** [comment]
Closing it due to inactivity. If the problem is still reproducible with the latest CLI, please open a new issue following the template and sharing a minimal demo where we can reproduce it. Thank you! :)
