### ISSUE TITLE
ng serve (dev mode) doesn't serve updated file from assets directory

### ISSUE THREAD

**Issue by kdcro101** [angular/angular-cli#9669]
ng serve (dev mode) doesn't serve updated file from assets directory, it serves "version" that was first transmitted (caching problem?).

When file in assets directory is changed via external shell script (child tsconfig to generate javascript for web workers [tsc + browserify + uglify]), ng serve serves version of file that was transmitted on first request.

Server needs to be restarted for changes to pick-up. 

### Versions
```
Angular CLI: 1.6.8
Node: 8.9.3
OS: linux x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.1
@angular/cli: 1.6.8
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.2.1
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack-bundle-analyzer: 2.10.0
webpack: 3.10.0
```

### Repro steps

run `ng serve`, change some javascript file inside assets directory
`assets/workers/some.js` for example, using above mentioned tools

### Observed behavior
ng serve - serves outdated js file which doesn't exist on storage/drive (caching?)

### Desired behavior
To serve updated file from storage.

**Comment by kdcro101** [comment]
Also, when files are copied into project (imported type defs) it doesn't trigger change mechanism.
If I am having error  which is reported via console output of `ng serve` after copying  into project , corrected .ts files, using linux cp  command it doesn't trigger ng serve rebuild processs, so `ng serve` must be restarted

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by MickL** [comment]
I can reproduce this on latest version `@angular/cli ~6.0.8`

**Comment by virgil-av** [comment]
I have been trying to find a solution for this and nothing for me  it is: 
- generate some css files with grunt copy them into assets folder after the app is already started with ng serve
- change sass compile with grunt have new files in assets  app will recompile 
- change again and compile with grunt  app will not recompile and add new assets to in memory assets  
- kill the server and start ng serve will produce the same result over and over again

**Comment by DenisVuyka** [comment]
Having exactly same problem with 6.2. After "automatic" reload I have to reload the app manually one more time to get the actual copy of the code.

**Comment by alan-agius4** [comment]
We have looked into this and it is related to one of our dependencies. I'm sorry, but this issue is not caused by Angular CLI. 

I have created a PR at upstream to solve this issue.
https://github.com/webpack-contrib/copy-webpack-plugin/pull/290

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/12591 should fix this by updating the dependency.

**Comment by yuezhizizhang** [comment]
I'm using @angluar/cli 8.1.3, I met this problem again.
