### ISSUE TITLE
Jade extension

### ISSUE THREAD

**Issue by krasevych** [angular/angular-cli#968]
Hi, I have a question:
How can I create new component/router with *.jade extension instead of HTML?

**Comment by filipesilva** [comment]
Heya @krasevych, at the moment jade is not supported. The best I can say about it is https://github.com/angular/angular-cli/issues/40#issuecomment-212636754.

**Comment by filipesilva** [comment]
Seems I spoke too soon! There's an open PR for this functionality via pug (apparently jade was renamed to pug). See https://github.com/angular/angular-cli/pull/626.
