### ISSUE TITLE
ng set returns an error when no args provided

### ISSUE THREAD

**Issue by yfain** [angular/angular-cli#9683]
If you run ```ng set``` without args, it returns an error Cannot read property 'split' of undefined.

Expected behavior:
```ng set``` should produce the same output as ```ng help set```.

I use Angular CLI 1.7.0

**Comment by clydin** [comment]
Version 1.7.0 is no longer actively supported.  If you still encounter this issue with the latest version, please open a new issue detailing the version and environment information.
