### ISSUE TITLE
Watch doesn't work with @ngtools/webpack 

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular-cli#9688]
### Versions
```
os: Windows 8.1
node: 6.13.0
npm: 3.10.10

"@angular/common": "^5.2.1",
"@angular/compiler": "^5.2.1",
"@angular/compiler-cli": "^5.2.1",
"@angular/core": "^5.2.1",
"@angular/platform-browser": "^5.2.1",
"@angular/platform-browser-dynamic": "^5.2.1",
"@ngtools/webpack": "^1.10.0",
"raw-loader": "^0.5.1",
"rxjs": "^5.5.2",
"typescript": "^2.5.3",
"webpack": "^3.10.0"
"zone.js": "^0.8.18"
```

### Repro steps
* clone repo: https://github.com/dawidgarus/ngtools-watch
* run `npm install`
* run `node compile`
* change any ts or html file other than `main.ts` or `app.module.ts`

### Observed behavior
Despite the fact that file has changed, project is not recompiled.
But when `main.ts` or `app.module.ts` changes, then project is recompiled, so watcher seems to be working.

### Desired behavior
Project should be recompiled after change.

### Mention any other details that might be useful (optional)
EDIT:
It seems to be working fine without `skipCodeGeneration: true` - it might be issue with that.

**Comment by jtomaszewski** [comment]
Yes, it should be mentioned, I agree. It took me 3 hours to find the issue. Related: https://github.com/angular/angular-cli/issues/8508

**Comment by alan-agius4** [comment]
Closing as docs have been fixed.
