### ISSUE TITLE
Vendor NPM Files - Build is successful, but fails to copy a file

### ISSUE THREAD

**Issue by yusijs** [angular/angular-cli#969]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.1
node: 4.3.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Created with CLI

4. The log given by the failure. Normally this include a stack trace and some
   more information.
No log output

5. Mention any other details that might be useful.
I'm trying to make use of https://github.com/alexcastillo/ng2-notifications, and the main file is copied fine. However, adding any other files ('ng2-notifications/src/app/components/notification.component',), makes no difference. The build says it's completed fine, but it doesnt copy that file. It's in angular-cli-build.js and everything.

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by salle18** [comment]
1. Add the library to vendorNpmFiles in the angular-cli-build.js as 'library/**/*js'
2. Add map to system-config.ts
`/** Map relative paths to URLs. */
const map: any = {
  'library': 'vendor/library/main-file.js'
};`
3. Turn on default js extension in system-config.ts (might not be necessary but it helped me to include ng2-file-upload)
`// Apply the user's configuration.
System.config({
      map: map,
      packages: packages,
      defaultJSExtensions: true
});`

**Comment by filipesilva** [comment]
@yusijs can you provide me with a repo where I can verify the problem?

**Comment by delasteve** [comment]
@filipesilva: try this out. I added Bootstrap as a dependency and modified the `angular-cli-build.json` to look for `'bootstrap/dist/*.+(js|js.map)'` The file itself is under `node_modules/bootstrap/dist/js/bootstrap.js`. 

You will also notice, in a prod build, it doesn't build rxjs. Is this what is supposed to happen?

https://github.com/delasteve/angular-cli-issue-969

**Comment by filipesilva** [comment]
@delasteve prod builds will not copy over files, but rather bundle them. 

In the case of bootstrap, you'll probably have to add it as a global package in `system-config.js` so that it is bundled up.

**Comment by yusijs** [comment]
@filipesilva I don't have it in a public repo (it depends on client data for work), but my angular-cli-build.js:
```
/* global require, module */

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/*.js',
      'es6-shim/es6-shim.js',
      'reflect-metadata/*.js',
      'rxjs/**/*.js',
      '@angular/**/*.js',
      'highcharts/highcharts.js',
      'ng2-notifications/ng2-notifications.js',
      'ng2-notifications/src/app/components/notification.component',
      'moment/moment.js',
      'ng2-bootstrap/bundles/ng2-bootstrap.min.js'
    ]
  });
};

```

package.json dependencies
```
"dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "^2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "bootstrap": "^3.3.6",
    "es6-shim": "^0.35.0",
    "ng2-bootstrap": "^1.0.16",
    "ng2-notifications": "^0.3.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "^0.6.12"
  },
```

It copies everything else over, but not that specific file.

**Comment by yusijs** [comment]
Ermahgerd, just saw my error. 

'ng2-notifications/src/app/components/notification.component',
should be
'ng2-notifications/src/app/components/notification.component.js',

to many import {} from going on. :3 

Still though - the build process should give an error imo ("file not found" or similar)

**Comment by un33k** [comment]
@delasteve `ng b` will copy it over however, `ng b -prod` will bundle bootstrap.js into main.js.

**Comment by delasteve** [comment]
@un33k: After some more modifications, I got it to be included in the bundling. Thanks so much!

**Comment by filipesilva** [comment]
@yusijs @delasteve glad to hear it's working now!

@un33k I'm not sure what you mean with the file signature. Can you elaborate?

**Comment by un33k** [comment]
@filipesilva If you do a checksum of the file content and add it to the file name.  main.js -> main.asdfjsgyqhn4phgn3qrnng.js. If the file content changes, so will the filename of the file, forcing browsers to download the file.

**Comment by filipesilva** [comment]
Hm we don't have any specific plans for cache busting right now. It's doable I suppose, and would need to dynamically change the system config, but still doable. 

Can you open a new issue requesting cache busting? I can't say if/when it'll get done but that way it can be tracked.
