### ISSUE TITLE
I'm doing switch from arabic to english and vice versa but when i want to switch to english after arabic it still in arabic, can any one help to solve this issue? thanks in advance

### ISSUE THREAD

**Issue by mohamedelmancy** [angular/angular-cli#9694]
switchLanguage(language) {
    if (isDevMode()) {
      console.log('language is ', language);
      localStorage.setItem('language', language);
      this.arabic = true;
      this.english = false;
     require('style-loader!../../scss/hubnsub-RTL.scss');
    } else {
      localStorage.setItem('language', language);
      console.log('language is ', language);
      this.english = true;
      this.arabic = false;
     delete  require.cache[require.resolve('../../scss/hubnsub-RTL.scss')];
      require('style-loader!../../scss/hubnsub.scss');
    }

**Comment by hansl** [comment]
Hello @mohamedelmancy ,

We reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mohamedelmancy** [comment]
@hansl  ok thanks
