### ISSUE TITLE
i can't switch to english after switching to arabic 

### ISSUE THREAD

**Issue by mohamedelmancy** [angular/angular-cli#9695]
switchLanguage(language) {
    if (isDevMode()) {
      console.log('language is ', language);
      localStorage.setItem('language', language);
      this.arabic = true;
      this.english = false;
     require('style-loader!../../scss/hubnsub-RTL.scss');
    } else {
      localStorage.setItem('language', language);
      console.log('language is ', language);
      this.english = true;
      this.arabic = false;
     delete  require.cache[require.resolve('../../scss/hubnsub-RTL.scss')];
      require('style-loader!../../scss/hubnsub.scss');
    }

**Comment by hansl** [comment]
Dupe of #9694
