### ISSUE TITLE
Please correct the known issues entry

### ISSUE THREAD

**Issue by bastienJS** [angular/angular-cli#970]
From the known issues on the main site:

"On Windows you need to run the build and serve commands with Admin permissions, otherwise the performance is not good."

Not good? Its just not working, that means the Brocoli machine messes all up. "ng build" will just fail at least here on Windows 10!

**Comment by filipesilva** [comment]
You're right, at the moment it will not work at all without admin rights.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/905 should allow non-admin user usage.
