### ISSUE TITLE
Won't build with multiple bootstrapped components, but builds fine when being --watch'd

### ISSUE THREAD

**Issue by mortenmoulder** [angular/angular-cli#9702]
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.8
Node: 8.9.4
OS: win32 x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
* Step 1: Setup a simple Angular 5 application and create two components with code similar to this:

```
import { Component } from "@angular/core";

@Component({
    selector: "test-component",
    templateUrl: "./test.component.html"
})
export class TestComponent {
    public title = "Test!";
}
```

* Step 2: Create two `component.module.ts` files in each of the components' folders.
* Step 3: Give them code similar to this:

```
import { BrowserModule } from "@angular/platform-browser";
import { NgModule } from "@angular/core";

import { TestComponent } from "./test.component";

@NgModule({
    declarations: [TestComponent],
    imports: [BrowserModule],
    bootstrap: [TestComponent]
})
export class TestModule {}
```

* Step 4: Edit `main.ts` to include the two components bootstrapped (exclude `AppModule` for now) like this:

```
platformBrowserDynamic().bootstrapModule(TestModule);

platformBrowserDynamic().bootstrapModule(SecondTestModule);
```

* Step 5: Build the application using `ng build --watch` and watch it fail  (error below).
* Step 6: Comment out one of the modules you added to `main.ts` and run the command again.
* Step 7: It should have built itself now, and since we have `--watch`, you can remove the comment and it will compile again.

### Observed behavior
I receive this error when trying to build with more than 1 component in `main.ts`:
```
ERROR in Error: Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
    at Object.resolveEntryModuleFromMain (C:\test\node_modules\@ngtools\webpack\src\entry_resolver.js:121:15)
    at Promise.resolve.then.then (C:\test\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:241:54)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Desired behavior
It should compile, because it works perfectly. If we only have ONE module in the `main.ts` file, it compiles fine using `--watch`. If we then add the second one back afterwards, while still running, it also works just fine.

It should be possible to simply run `ng build` and it should build the application.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since there we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
