### ISSUE TITLE
ng serve of a brand new project fails to load... just about everything

### ISSUE THREAD

**Issue by skorlir** [angular/angular-cli#971]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16.04.

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
```
angular-cli: 1.0.0-beta.5
node: 5.10.1
os: linux x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
```
$ ng new ng2-hello --style stylus
$ cd ng2-hello
$ ng serve
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.
![error messages](http://i.imgur.com/2BWflh1.png?1)

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Right you are. Seems that at the moment stylus compilation is not happening, for some reason.

**Comment by tapas4java** [comment]
@skorlir...You have to install stylus before `ng serve`

**Comment by skorlir** [comment]
Huh. I suppose that makes sense, but it surprises me that the cli doesn't
just install it locally. It's available on npm.

It also surprises me that there was never an error message given during
generation or compilation, and the build succeeded. Perhaps the cli could
do detection to see if the stylus executable is available, and give a
warning and offer to install it locally if not?

I would be glad to look into it and submit a PR, if you'd like to point me
in the right direction.

Jordan

**Comment by tapas4java** [comment]
Yep, 
I would suggest to add the respective library into `package.json` if user is providing `--style` flag to `new/init` command.

e.g. If user provides `--style scss` then we should add `node-sass` library to the package.json

**Comment by filipesilva** [comment]
We recently added conditional packages in `package.json` when creating a new project, so it's definitely feasible.

I've opened https://github.com/angular/angular-cli/issues/986 to replace this one as it calls explicitly for adding the new functionality.
