### ISSUE TITLE
angular/cli

### ISSUE THREAD

**Issue by Ankith55** [angular/angular-cli#9715]
I got an error while installing angular js file i.e, angluar/cli when i gave the command "npm install @angular/cli"

npm ERR! Unexpected end of JSON input while parsing near '...9852a748cb8a6954d3c41'
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ankith-Poojary\AppData\Roaming\npm-cache\_logs\2018-02-21T15_52_13_193Z-debug.log

**Comment by filipesilva** [comment]
I think you're having some weird errors and can't debug it, and so, understandably, you're frustrated. But this is a tracker for bugs and feature requests. If we can we also try to help with support requests. We're very lucky to have awesome community members that also spend time trying to help people here in the issue tracker.

But we can't really help much at all if you don't fill in the issue template. I read your issue and have no idea what's going wrong and how to help you. And when other users search the issue tracker and see your issue, it also doesn't help them.

So I think the best thing to do is to close this issue, and ask you to open a new one. In that new one please fill in the issue template and give us an idea of what's happening and how to reproduce it. That way we'll have a chance to help you.
