### ISSUE TITLE
Karma reverse proxy wildcard doesn't work

### ISSUE THREAD

**Issue by bibhas2** [angular/angular-cli#9718]
### Versions
```
Angular CLI: 1.6.5
Node: 8.1.4
OS: darwin x64
Angular: 5.2.5
```

### Repro steps
My application makes calls to a backend web service. During development I configure reverse proxy for the Angular CLI server and everything works fine. I need to do the same for Karma during unit testing. I add this to ``karma.conf.js``.

```
proxies: {
  "/books":"http://localhost:3000/",
  "/books/*":"http://localhost:3000/",
}
```

### Observed behavior

My HTTP calls always get 404. If, however, I configure a full URL, it works. 

```
proxies: {
  "/books/167":"http://localhost:3000/167"
}
```

### Desired behavior

Wildcarding should work in Karma reverse proxy settings. Without this it will be almost impossible to unit test apps that make backend calls to web services that are not configured with CORS. Not all web services can be mocked with local data or doing so may take considerable effort.

**Comment by csutorasr** [comment]
Hi @bibhas2 !

Unit testing is not about calling backend. That is integration testing you should do with protactor and end to end testing.

In a nutshell:
With unit testing you should test a part of the code as a unit _without any dependencies_. So if the units are working without other you should expect the whole working together.
With E2E testing you can see if your units can work together properly, not just expect it.

**Comment by filipesilva** [comment]
This sounds more like a karma issue than an issue with Angular CLI. If you're still seeing this problem, please let us know.
