### ISSUE TITLE
How to load external jquery files.

### ISSUE THREAD

**Issue by Santhamani** [angular/angular-cli#9719]
Am using some external jquery files like jquery jquery.validate.js, charts.js, and user definied animations in my current project. 

Each time when I refresh the particular page then only my jquery code is loaded. 

Tried to link the files in angular.cli.json and index.html. Still the same problem is arriving. 

Can any one help me in this.

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
