### ISSUE TITLE
Routing Issue

### ISSUE THREAD

**Issue by emreerkoca** [angular/angular-cli#9730]
When you click on "**Learn Angular**" at the bottom of the page [cli.angular.io](http://cli.angular.io) website, **[wwww.angular.io](http://wwww.angular.io)** is opening. So one more "w". Can you fix this?

**Comment by filipesilva** [comment]
Oh I didn't know this wasn't working. Thank you for the report!

**Comment by emreerkoca** [comment]
You are welcome. When the problem is solved, I will close issue.

**Comment by emreerkoca** [comment]
@filipesilva Problem is not resolved :)

**Comment by vamshi9666** [comment]
this isnt solved .
