### ISSUE TITLE
Angular CLI with Angular and AngularJS

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular-cli#9731]
### Versions

```
Angular CLI: 1.6.5
Node: 9.4.0
OS: darwin x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

@angular/upgrade@5.2.6
angular@1.6.9
```

### Repro steps
* Clone branch: https://github.com/klemenoslaj/angular-cli-bugreport.git
* Install dependencies(I use `yarn`)
* Execute `ng serve`
* You should be seeing `AngularJS Works! Angular 5 Works` in browser
* You will see only `Angular 5 Works` with error in console: `Error: [$compile:tpload] Failed to load template: ./app-ng1.component.html (HTTP status: 404 Not Found)`

### Observed behavior
TemplateUrl of AngularJS component does not get inlined in the same way as for Angular components.
Current workaround:
* Go to `./src/ng1/app-ng1.component.ts`
* Uncomment `class UncommentMe { }`

Even though class `UncommentMe` has nothing to do with AngularJS, this makes it work.

### Desired behavior
TemplateUrl of AngularJS component should get inlined the same way as for Angular components.

**Comment by filipesilva** [comment]
Angular CLI is first and foremost a CLI for Angular projects. We don't support inlining templates for AngularJS projects. In the next major version we're providing support for extensibility so you'll be able to add it yourself.
