### ISSUE TITLE
Project not always load js files from cli.json

### ISSUE THREAD

**Issue by alkincakiralar1996** [angular/angular-cli#9734]
I bought a HTML template and I am trying to adaptive on my Angular 2 project.

CSS files are OK, no problem, but JS files are really problem.

For example this is my angular.cli.json

```
  "styles": [
    "styles.scss",
    "theme/dist/css/pages/login-register-lock.css",
    "theme/dist/css/style.css",
    "theme/dist/css/pages/register3.css",
    "theme/libraries/register-steps/steps.css"
  ],
  "scripts": [
    "../node_modules/jquery/dist/jquery.js",
    "../node_modules/popper.js/dist/umd/popper.min.js",
    "../node_modules/bootstrap/dist/js/bootstrap.min.js",
    "theme/libraries/register-steps/jquery.easing.min.js",
    "theme/libraries/register-steps/register-init.js",
    "theme/index.js"
  ],
```
CSS files always work, JavaScript files under node_modules always work, but under theme JavaScript files only work when I start the project or ctrl + f5

I am using these JavaScript files in register component

```
    "theme/libraries/register-steps/jquery.easing.min.js",
    "theme/libraries/register-steps/register-init.js",
```
Start the app on register component its OK working but when I change route with button then come back again these are not working also there are no error on console.

please someone help me to solve this issue

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

I would like to say that on a Single Page Application, JS files in index.html are only loaded once. That is how single page applications work generally.
