### ISSUE TITLE
how can i disable the auto reload in angular 2?

### ISSUE THREAD

**Issue by pranabunni** [angular/angular-cli#9742]

**Comment by majo40** [comment]
ng serve --live-reload false

**Comment by filipesilva** [comment]
Closing as answered by @majo40 , thanks!

**Comment by MrPardeep** [comment]
@filipesilva , Is it possible to stop auto reloading for some particular files.

Like I want to stop auto reloading when I made some changes in my css files?

If possible please let me know.

**Comment by paturin** [comment]
Same as @MrPardeep
