### ISSUE TITLE
css bundle size increased after update to 1.7 (inline svg not optimized anymore) 

### ISSUE THREAD

**Issue by dominikg** [angular/angular-cli#9744]
### Versions
```
1.7
```

### Repro steps

* create a new project with scss 
* add a library with svg icons that are small enough to be inlined during build (eg. ag-grid)
* import that library in src/styles.scss
```
$ag-icons-path: "../node_modules/ag-grid/src/styles/icons/";
@import "../node_modules/ag-grid/src/styles/ag-grid";
```
* build project with 1.6.8 and 1.7.1 and compare css bundle sizes
```
npm install @angular/cli@1.6.8
ng build -prod
mv dist dist_168
npm install @angular/cli@1.7.1
ng build -prod
mv dist dist_171
du -h dist_*/*.css
```

### Observed behavior
```
css bundle size increases:
 48K	dist_168/styles.44126ec34b6b732ae4d9.bundle.css
 84K	dist_171/styles.a5d935b31bf8107834b8.bundle.css
```

### Desired behavior
```
keep bundle size as small as possible
```

### Mention any other details that might be useful (optional)
cli 1.6 used cssnano 
cli 1.7 uses clean-css 

main reason for size increase seems to be that cssnano uses svgo while clean-css does not.

In a project for a client that uses bootstrap, fontawesome and ag-grid (all imported and customized in scss) the css bundle size increased from 220kb to 330kb

**Comment by clydin** [comment]
Unfortunately, there is not a final version of postcss-svgo that supports postcss v6.
`ag-grid` could consider shipping optimized versions of its svg assets in a similar way that many packages ship minified versions of their javascript and/or css assets.

Also, for the sake of curiosity, could you provide the size differences for compressed bundle outputs (gzip would be sufficient)?

**Comment by dominikg** [comment]
with compression the size increase is much less:

ag grid example above (files compressed on commandline with gzip -9)

| ng | size | compression  | compression ratio | size diff 1.6.8 | size ratio 1.6.8 | 
| --- | --- | --- | --- | --- | --- |
| 1.6.8 | 46064 | - | 0% | 0 | 100% |
| 1.6.8 | 6170 | gz | 86.6% | 0 | 100% |
| 1.7.1 | 84328 | - | 0% | 38264 | 183.1% |
| 1.7.1 |  7427 | gz | 91.2% | 1257 | 120.4% |

client project (files compressed with gulp-zopfli/gulp-brotli on mac)

| ng | size | compression  | compression ratio | size diff 1.6.8 | size ratio 1.6.8 | 
| --- | --- | --- | --- | --- | --- |
| 1.6.8 | 221760 | - | 0% | 0 | 100% |
| 1.6.8 | 29420| gz  | 86.7% | 0 | 100% |
| 1.6.8  | 23798 | br | 89.3%| 0 | 100% |
| 1.7.1 | 314094 | - |  0% | 92334 | 141.6% |
| 1.7.1 | 32482 | gz |89.7% | 3062 |  110.4% |
| 1.7.1 | 24364 | br | 92.2% | 566 | 102.4% |

**Comment by evilebottnawi** [comment]
@filipesilva cssnano again is well supported (I'm one of the leading developers). You are already using postcss in many places, will be great if you switch on `cssnano` back. This will allow us to create a good tool together.

**Comment by evilebottnawi** [comment]
Also in near future we will release official plugin for webpack with parallel/cache/source map and other features as in `uglify/terser` uglificators.

**Comment by filipesilva** [comment]
Good to know about the upcoming plugins!

Regarding postcss vs cssnano, nowadays we also use postcss to resolve resources so it might be a bit harder to move back (cc @clydin).

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases as resources will no longer be inlined.
