### ISSUE TITLE
Can't resolve error

### ISSUE THREAD

**Issue by Prasannavk94** [angular/angular-cli#9746]
Hi,

I am facing issues in deploying the angular app in amazon linux ami ,
I am getting the following error on running ng serve

ERROR in ./src/app/app.routes.ts
Module not found: Error: Can't resolve './components/common/layouts/topNavigationlayout.component' in '/var/www/html/frontend/src/app'
ERROR in ./src/app/components/common/layouts/layouts.module.ts
Module not found: Error: Can't resolve './topNavigationlayout.component' in '/var/www/html/frontend/src/app/components/common/layouts'
ERROR in /var/www/html/frontend/src/customer/app.routes.ts (6,46): Cannot find module './components/common/layouts/topNavigationlayout.component'.
ERROR in /var/www/html/frontend/src/customer/components/common/layouts/layouts.module.ts (10,44): Cannot find module './topNavigationlayout.component'.
ERROR in /var/www/html/frontend/src/customer/app.module.ts (9,28): Cannot find module 'RxJS/Rx'.
ERROR in /var/www/html/frontend/src/freelancer/app.routes.ts (8,46): Cannot find module './components/common/layouts/topNavigationlayout.component'.
ERROR in /var/www/html/frontend/src/core/services/workorder.service.ts (92,2): Duplicate identifier 'addExistingFile'.
ERROR in /var/www/html/frontend/src/freelancer/components/common/layouts/layouts.module.ts (9,44): Cannot find module './topNavigationlayout.component'.
ERROR in /var/www/html/frontend/src/customer/views/packages/packages.component.ts (12,28): Cannot find module 'RxJs'.
ERROR in /var/www/html/frontend/src/app/views/masters/document/add-document.component.ts (47,32): Argument of type 'number' is not assignable to parameter of type 'string | Blob'.
ERROR in /var/www/html/frontend/src/app/views/workorders/create-workorder/create-workorder.component.ts (12,28): Cannot find module 'RxJs'.
ERROR in /var/www/html/frontend/src/app/app.routes.ts (63,44): Cannot find module './components/common/layouts/topNavigationlayout.component'.
ERROR in /var/www/html/frontend/src/app/components/common/topnavbar/topnavbar.component.ts (16,28): Cannot find module 'RxJs'.
ERROR in /var/www/html/frontend/src/app/components/common/layouts/layouts.module.ts (10,44): Cannot find module './topNavigationlayout.component'.
ERROR in /var/www/html/frontend/src/app/app.module.ts (9,26): Cannot find module 'RxJS/Rx'.
ERROR in /var/www/html/frontend/src/customer/views/workorders/create-workorder/create-workorder.component.ts (12,28): Cannot find module 'RxJs'.
ERROR in /var/www/html/frontend/src/freelancer/app.module.ts (9,28): Cannot find module 'RxJS/Rx'.

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

If I had to bet though, getting compilation errors about missing files in different environments is usually about case sensitivity of the file system. Windows, OSX and Linux all have different case sensitivity rules. I'd check if `topNavigationlayout.component.ts` is not actually `topNavigationLayout.component.ts`.
