### ISSUE TITLE
[Documentation Request] ng test --log-level options

### ISSUE THREAD

**Issue by DinoSourcesRex** [angular/angular-cli#9757]
On the page [here](https://github.com/angular/angular-cli/wiki/test) I am unable to actually find any log levels.

My Googling has failed me when I tried to find any information on the subject.

### Desired behavior
What would like to see implemented + what did you expect to see: The values available for the --log-level option

**Comment by DinoSourcesRex** [comment]
@lordgreg Hey lordgreg.

Perhaps I'm looking for entirely the wrong thing but this didn't work for me.

I've run `ng test --log-level OFF`, with my `Karma.conf.js` log level set to `logLevel: config.LOG_DISABLE` however I am still seeing console.logs in the output when running ng test.

The only way I have currently gotten around this is by add `console.log = function () { }` to a `BeforeEach` step in the test, which isn't really going to work well for my needs.

Is this what the `--log-level` option is supposed to strip out? Or have I misunderstood the point of the option entirely?

**Comment by alexzaytsev-newsroomly** [comment]
Is there any way to print out the test case names? e.g. instead of `Executed 1 of 66` see the actual name; we're using PhantomJS and it is being a pain.

**Comment by DinoSourcesRex** [comment]
@alexzaytsev-newsroomly You could try out the [Karma Spec Reporter](https://github.com/mlex/karma-spec-reporter).

**Comment by alan-agius4** [comment]
Closing as log levels, is not an option provided by Angular CLI. But a Karma option, more details about this can be found http://karma-runner.github.io/3.0/config/configuration-file.html
