### ISSUE TITLE
[Feature Request] ng e2e --config-file parameter

### ISSUE THREAD

**Issue by PhilippSoehnlein** [angular/angular-cli#976]
It looks like `ng test` has a `--config-file` parameter (see #966). A similar option for `ng e2e` would be cool.

For both commands my use case is a differentiation of tests if they run locally or on a CI server. Locally I would call `ng e2e --config-file config/protractor-local.conf.js` and the CI server would do a `ng e2e --config-file config/protractor-ci.conf.js`. Sure, you can build both cases into the same protractor.conf.js, but I'd like to have this separated. The same goes for `ng test`.

**Comment by filipesilva** [comment]
This is now supported via the `--config` flag.
