### ISSUE TITLE
feature: defaults in config for custom schematics

### ISSUE THREAD

**Issue by gatimus** [angular/angular-cli#9760]
Allow adding values to `defaults` in `.angular-cli.json` that would set default options for custom schematics.

It could possibly look like: 

    {
        "defaults": {
            "my-schematics:my-rule": {
                "my-option": "foo"
            }
        }
    }

Then running `ng generate my-schematics:my-rule` would be equivalent to running `ng generate my-schematics:my-rule --my-option="foo"`

**Comment by mgechev** [comment]
This should be working properly. If you find out that this feature is still unavailable, please open a new issue.

**Comment by NitsanBaleli** [comment]
we can now use

```


"schematics": {
    "@schematics/angular": {
      "component": {
        "spec": false
      },
      "directive": {
        "spec": false
      }
    }
  }

```
