### ISSUE TITLE
ng version on mac display angular as ...

### ISSUE THREAD

**Issue by robertchen** [angular/angular-cli#9765]
robert@imac$ ng v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.1
Node: 9.6.1
OS: darwin x64
Angular: 
...

**Comment by m0t0r** [comment]
@robertchen, you have to be inside of an angular project to get Angular version

**Comment by filipesilva** [comment]
Closed as answered by @m0t0r, thank you!
