### ISSUE TITLE
Allow TypeScript path mapping in `templateUrl`

### ISSUE THREAD

**Issue by alfaproject** [angular/angular-cli#9766]
Currently, it seems impossible to use TypeScript type mapping for `templateUrl` and even `styleUrls` which is a bit odd since it seems to me that TypeScript should be resolving all paths?

### Repro steps
* Add a path map to `tsconfig.json` compiler options: `"paths": { "@core/*": ["core/*"] }`
* Use a mapped path in a component's `templateUrl` property: `templateUrl: '@core/forms/login-form.component.html'`
* `ng serve --aot`

### Observed behavior
```
ERROR in : Couldn't resolve resource @core/forms/login-form.html' from /ng-cli/src/app/home/login-form.component.ts
```

### Desired behavior
The TypeScript path mapping works as expected like everywhere else, and the templates are found and compiled.

**Comment by clydin** [comment]
The path mapping of `"@core/*": ["@core/*"]` results in an identity mapping and is the equivalent of no mapping at all.

**Comment by alfaproject** [comment]
Sorry, that was a typo and I just fixed. It's just an academic example by the way. (;

**Comment by alfaproject** [comment]
As per Alex comment here https://github.com/angular/angular/pull/22615#issuecomment-371824642 should I reopen this issue in Angular repo instead?

**Comment by alan-agius4** [comment]
@alfaproject, thanks for this feature request. 

Seeing the little activity this received since it was opened back in 2018, it doesn't currently fall in the Angular CLI roadmap.

Let's re-consider if things change.
