### ISSUE TITLE
fonts loading from wrong location in 1.7.1

### ISSUE THREAD

**Issue by rekna1** [angular/angular-cli#9770]
### Versions
```
Angular CLI: 1.7.1
Node: 8.9.0
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.1
@angular/platform-server: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.1
webpack: 3.10.0
```

### Repro steps
I have an Asp.Net MVC applications with the following structure:
```
\Controllers           // MVC root folder
\dist                       // folder where angular dist files are created
\src
	main.ts 
	styles.scss 
	\app
		\app.component.html 
		\app.component.scss 
		\app\app.component.ts 
		\app\app.module.ts 
	\styles
		_fonts.scss 
		\font-icons
			myCustom.ttf  

```

```
styles.scss contains
@import 'styles/fonts.scss';			

_fonts.scss constains
@font-face {
    font-family: 'myCustom';
    src:  url('./styles/font-icons/myCustom.ttf') format('truetype'),
}
```
with angular 5.2.4 and angular-cli 1.6.8 the url for fonts was changed by ng build to 
src:  url('dist/myCustom.ttf') format('truetype'),

now with angular 5.4.6 and angular-cli 1.7.1 :
src:  url('myCustom.ttf') format('truetype'),

Why has this behaviour changed ?  Can I specify somewhere it should load from dist folder ?
Mvc application url is something like localhost/MyApp
So fonts should be loaded from localhost/MyApp/dist like it did in previous version of angular 5

### Observed behavior
url for font is 
/myCustom.xxxxx.ttf

### Desired behavior
should by 
dist/myCustom.xxxxx.ttf
like in Angular 5.2.4 and cli 1.6.8

**Comment by rekna1** [comment]
Apparently this problem only occurs in development build. 
In production styles are loaded from /dist/styles.442c745af5dd3871e3ba.bundle.css
and url's are relative to css location so everything is oké.

In development mode, styles are inlined in the home page of the Asp.Net MVC application.
Default page of the application is loaded from url  / (root folder) and all font url's are relative therefore fonts are loaded from the root folder instead of /dist  folder.

**Comment by rekna1** [comment]
Is there any possibility for a workaround for the moment ? Development with -prod mode is not very convenient and in development mode can't see any of my font icons.

**Comment by rekna1** [comment]
Temporary workaround : I included the font links in the index.cshtml page until angular releases a fix for this.

**Comment by alan-agius4** [comment]
I had a look at this and it looks like the fonts destination are being generated the same for both `prod` and `dev` without the `dist/` path which is correct since the css file is parallel to the font files.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
