### ISSUE TITLE
Unable to use custom locale with ng build

### ISSUE THREAD

**Issue by rahulbhooteshwar** [angular/angular-cli#9772]
### Versions
```
  / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.1
Node: 8.8.1
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps

* Setup new project : **ng new testLocale**
* Register Locale Data for custom locale in _app.module.ts_
```
import { registerLocaleData } from '@angular/common';
import localeNB from '@angular/common/locales/nb';
registerLocaleData(localeNB, 'no-no');
```
* Build Project: **ng build --aot --locale=_no-no_**

### Observed behavior
```
Build Fails with error:
Unable to load the locale data file "@angular/common/locales/no-no", please check that "no-no" is a valid locale id.
Error: Unable to load the locale data file "@angular/common/locales/no-no", please check that "no-no" is a valid locale id.
    at AngularCompilerPlugin._validateLocale (F:\dev\testLocale\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:836:27)
    at AngularCompilerPlugin._setupOptions (F:\dev\testLocale\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:145:43)
    at new AngularCompilerPlugin (F:\dev\testLocale\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:45:14)
    at _createAotPlugin (F:\dev\testLocale\node_modules\@angular\cli\models\webpack-configs\typescript.js:77:16)
```

### Desired behavior
According to Angular docs, we can register a custom locale ID and load existing locale data for any available locale for this custom locale.

**ng build** command should build the application with LOCALE_ID set as custom locale passed to compiler and registering specified locale data without any failure.

From error it can be seen that compiler is trying to load the locale data for the custom locale ID passed, but it is obvious that it will not find it. It should load the locale data specified in app.module.ts for this custom locale.

**Comment by rahulbhooteshwar** [comment]
The same procedure work for any other custom locale ...e.g. ng build --aot --locale custom-locale

It only gives error when using no-no, no-NO,

**Comment by ocombe** [comment]
You're right that the cli should let you define your own custom locale if you want, but fyi the new locale id for Norwegian Bokmål is `nb` as defined in [BCP47 (revised in 2009)](http://www.rfc-editor.org/rfc/bcp/bcp47.txt), `no-no` is no longer valid (it's listed in the docs: https://angular.io/guide/i18n#setting-up-the-locale-of-your-app).

**Comment by rahulbhooteshwar** [comment]
registerLocaleData(localeNB, 'no-no');
registerLocaleData takes 2nd argument as locales of your choice. If compilation process doesn't support custom locale then what is the use of the 2nd argument in  registerLocaleData ?!!

**Comment by ocombe** [comment]
The second argument was added very recently in Angular, and yes it's intended to be used for exactly the kind of use case that you have now, the cli code hasn't been updated to support that, and I'm not sure if we should. If you don't use `--locale` with the cli, then you can just use `registerLocaleData` in your code, like anyone who doesn't use the cli (tell me if I'm wrong on that?).
Is there a reason why you need to use `--locale`?

**Comment by rahulbhooteshwar** [comment]
We are having multiple locale specific builds which we are translating at the time of  build by mentioning --locale specific translation files as following:

`ng build --aot --i18nFile=src/locale/messages.no-no.xlf --i18nFormat=xlf --locale=no-no`

If we don't provide '--locale', we get the error as following:

`ERROR in Error: The translation file (src/locale/messages.fr.xlf) locale must be provided.
    at getAotCompilerOptions (F:\dev\testLocale\node_modules\@angular\compiler-cli\src\transformers\program.js:619:19)
    at AngularCompilerProgram._createCompiler (F:\dev\testLocale\node_modules\@angular\compiler-cli\src\transformers\program.js:400:26)
    at AngularCompilerProgram.get [as hostAdapter] (F:\dev\testLocale\node_modules\@angular\compiler-cli\src\transformers\program.js:327:22)
    at AngularCompilerProgram._createProgramWithBasicStubs (F:\dev\testLocale\node_modules\@angular\compiler-cli\src\transformers\program.js:435:73)
    at F:\dev\testLocale\node_modules\@angular\compiler-cli\src\transformers\program.js:143:28
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by ocombe** [comment]
I've checked, the locale is used by the AOT compiler to set value of `LOCALE_ID`, so yes it seems to be useful to be able to set it to the value that you want.
So yes, your PR should fix this (if you make the changes that I suggested).

**Comment by rahulbhooteshwar** [comment]
Pull request #9791 is merged and it  is  fixed now.Closing the issue. Thanks @ocombe  @clydin  for all the 
support.
