### ISSUE TITLE
Alias for skip install -si is not working

### ISSUE THREAD

**Issue by bogacg** [angular/angular-cli#9776]
### Versions
```
Angular CLI: 1.7.1
Node: 9.6.1
OS: win32 x64
```

### Repro steps

* type `ng new MyNewApp -st -si` in terminal to generate a new project, without downloading npm dependencies

### Observed behavior
It **does** download all dependencies.

### Desired behavior

**-si** as an alias for skip install.

**Comment by clydin** [comment]
1.x is no longer actively support (outside security issues).  Those aliases have also been removed from the latest version (6.x)
