### ISSUE TITLE
ng serve use Post method to local JSON file get 404 error

### ISSUE THREAD

**Issue by lomo1** [angular/angular-cli#9777]
### Versions
```
# ng-version
Angular CLI: 1.6.6
Node: 8.2.1
OS: darwin x64
# npm
5.6.0
```

### Repro steps

* Step 1
 `ng serve --o` start project in local machine
* Step 2
i clicked a button of my page, it **post** a request to my local api——mock data(`deleteProject.json`, this file at folder `assets`), but it response status is 404. 
* Step 3
in Chrome Console output error:  http://localhost:4200/assets/mock/deleteProject.json 404 (Not Found)

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```
POST http://localhost:4200/assets/mock/deleteProject.json 404 (Not Found)

### Desired behavior

POST `http://localhost:4200/assets/mock/deleteProject.json` response status is 200.

### Mention any other details that might be useful (optional)
i tried this url in PostMan by Post request get same result, and find this url only could be visited by get method.
Any help? 
thanks a lot.

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by filipesilva** [comment]
I had a look at your repro and I think the behaviour is as expected. Files on disk only support GET. I think you want to write to the disk but doing POST is not the right way. You need an API that can handle the POST request. You can use something like https://github.com/typicode/json-server for that.
