### ISSUE TITLE
'ng test' does not 'exit' after running unit test, something keeps running

### ISSUE THREAD

**Issue by reingroot** [angular/angular-cli#978]
When I run `ng test` my unit tests are run successfully. With `logLevel: config.LOG_DEBUG` it reports the following:

```
01 06 2016 16:50:15.040:DEBUG [karma]: Run complete, exiting.
01 06 2016 16:50:15.040:DEBUG [launcher]: Disconnecting all browsers
01 06 2016 16:50:15.521:DEBUG [launcher]: Process Chrome exited with code 0
01 06 2016 16:50:15.521:DEBUG [temp-dir]: Cleaning temp dir /var/folders/bd/5l9p70517qgg73659f70pzgw0000gn/T/karma-14746095
01 06 2016 16:50:15.574:DEBUG [launcher]: Finished all browsers
```

But it doesn't release the terminal. I don't get back the prompt. So it seems something keeps running. I have this locally with the configuration below. As well as on a docker image (pimterry/node-karma).

This prevents me from running the unit tests on my CI environment because the process waits for the prompt to return.

> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX El Capitan 10.11.5

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.5
node: 4.4.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
It was created with the CLI

4. The log given by the failure. Normally this include a stack trace and some
   more information.
There is no log. It is just that my prompt doesn't return.

5. Mention any other details that might be useful.
In the karma config: 'autowatch=false' and 'singleRun=true' 

I have also tried this with a fresh project generated with Angular CLI and nothing changed except the above settings in the Karma config. It has the same issue.

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
By default, unit tests will run in watch mode. You can override this by doing `ng tests --watch=false` instead.

**Comment by reingroot** [comment]
Thanks! That works :)

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/985 will update the README section to reflect this as well, as it was outdated. Cheers!

**Comment by bentaly** [comment]
The above should be ng test --watch=false

**Comment by ibirite** [comment]
I have the same issue here... But I'm calling ng test with code coverage ( -cc ).
Using --watch=false blocks the communication among the browser and Node.js
Is there anything I can do to fix it?

**Comment by gvart** [comment]
Another solution is to configure `karma` to run tests once and exit.

set fellow attributes:
```javascript
    autoWatch: false,
    singleRun: true
```

**Comment by 199219921992** [comment]
@filipesilva I am running ng test --code-coverage --watch=false but the tests are not running and doesn't create Lcov.info reports file which eventually gets published on SonarQube?

Without --watch switch and below karma.conf.js file the tests are running with Chrome browser but the browser instance doesn't close after test run, Opened browser instance is creating the Timeout in my build script.

*****************************************************************************************
Below content of  Karma.conf.js:
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../coverage'),
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};

Could you guide me please.

**Comment by filipesilva** [comment]
@199219921992 can you open a new issue with a reproduction for us to look into it please?

**Comment by 199219921992** [comment]
@filipesilva Created new issue - https://github.com/angular/angular-cli/issues/14279
