### ISSUE TITLE
Submit button not prevented

### ISSUE THREAD

**Issue by judedaryl** [angular/angular-cli#9781]
### Versions
```
1.6.8
1.7.1
```

### Repro steps

* ng new test
* Edit app.component.html and add
```
<form>
  <input></input>
  <button>test</button>
</form>
```
* ng serve
* open localhost:4200
* Click on the test button

### Observed behavior

When you press the "test" button, it submits the form like a normal html form using a post request to an action url.

### Desired behavior

The event of form submission when clicking on a submit button in a form is normally prevented when using angular.

**Comment by alexzuza** [comment]
Hello! You should add FormsModule to your module. 
And seems you chose wrong repository for such questions

**Comment by ShivaChaithanyaReddy** [comment]
You can use either template driven or reactive forms approach in order for Angular to handle your form submission.

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Also thanks for @alexzuza and @ShivaChaithanyaReddy for the great responses 👍
