### ISSUE TITLE
Cannot read property 'afterCompile' of undefined

### ISSUE THREAD

**Issue by mehdi550u** [angular/angular-cli#9783]
Hi,
ERROR in ./server.ts
Module build failed: TypeError: Cannot read property 'afterCompile' of undefined
at successfulTypeScriptInstance (D:\test\ang\node_modules\ts-loader\dist\instances.js:147:28)
at Object.getTypeScriptInstance (D:\test\ang\node_modules\ts-loader\dist\instances.js:48:12)
at Object.loader (D:\test\ang\node_modules\ts-loader\dist\index.js:16:41)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ang@0.0.0 webpack:server: webpack --config webpack.server.config.js --progress --colors
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ang@0.0.0 webpack:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**I receive this error when I try to run "webpack --config webpack.server.config.js --progress --colors"**

**Comment by rjz** [comment]
@mehdi550u, this sounds like it might be a version mismatch in webpack. Could you confirm the versions of `webpack` and `ts-loader` your project is using?

**Comment by mehdi550u** [comment]
@rjz 
These are all my dependencies:

 "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/platform-server": "^5.2.6",
    "@angular/router": "^5.2.0",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.5",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "ts-loader": "^4.0.0",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.1",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }

**Comment by damylen** [comment]
same problem here:

"ts-loader": "^4.0.0",
"typescript": "^2.7.2",
"webpack": "^4.0.0",
"webpack-cli": "^2.0.9",

**Comment by georgebonney** [comment]
I resolved this by setting webpack to 3.10.0 and ts-loader back to 3.5.0, see here https://github.com/TypeStrong/ts-loader/releases

**Comment by filipesilva** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the https://github.com/TypeStrong/ts-loader project or file an issue on their issue tracker.

**Comment by devsullo** [comment]
Change `"ts-loader": "^3.5.0"` and reinstall dependencies.
See ts-loader [compatibility](https://github.com/TypeStrong/ts-loader#compatibility )
