### ISSUE TITLE
ng build works but emits a warning

### ISSUE THREAD

**Issue by skidrou** [angular/angular-cli#9784]
### Versions
```
Angular CLI: 1.7.1
Node: 6.9.5
OS: win32 x64
Angular: 5.2.6

@angular/cli: 1.7.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.4.2
webpack-bundle-analyzer: 2.11.0
webpack: 3.11.0
```

### Repro steps
* ng build --prod --base-href ./

### Observed behavior

ng build works as expected but emit this warning and it break my css:

WARNING in Invalid character(s) ';
' at 324:2. Ignoring.

### Desired behavior

No warning and no breaking

### Mention any other details that might be useful (optional)

Where can I find this character at 324:2?

**Comment by skidrou** [comment]
I found the problem, was a `;` lost in one of various css that I have, would be nice if this error appeared more clearly and still in `ng serve`.

**Comment by fengerzh** [comment]
This is not a bug, can be closed.

**Comment by Eddie541** [comment]
I have a similar issue, how can I find the offending value? In my case it's an 'Invalid background value at 5609:18'. I've combed through the css / scss files and corrected all my background values yet the warning persists...
Thanks

**Comment by skidrou** [comment]
My workaroung until find the offending value was to prod with `ng build --extract-css=false`.

**Comment by ogousa** [comment]
in my case it was  `background: "";`  in a third-party css.
I changed it to `background: transparent;` and I have no warnings now.

**Comment by RyanZhou713** [comment]
> I have a similar issue, how can I find the offending value? In my case it's an 'Invalid background value at 5609:18'. I've combed through the css / scss files and corrected all my background values yet the warning persists...
> Thanks

Same issue with me, did you already fixed it?
