### ISSUE TITLE
node-sass and  webpack version dependency issue in mac 

### ISSUE THREAD

**Issue by raky35** [angular/angular-cli#9786]
Hi Team , Faced he below issue any thoughts please? Installed the in my Latest OS mac
https://nodejs.org/en/download/

When i run below commando see two depdnecy have issue also my ng command is not working.
sh-3.2# npm list -global --depth 0
/var/root/.npm-global/lib
├── @1.7.1
├── ajv@6.1.1
├── ajv-keywords@3.1.0
├── ethereumjs-testrpc@6.0.3
├── ganache-cli@6.0.3
├── jshint@2.9.5
├── node-pre-gyp@0.6.39
├── UNMET PEER DEPENDENCY node-sass@^4.0.0
├── npm@5.6.0
├── sass-loader@6.0.6
└── UNMET PEER DEPENDENCY webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0

npm ERR! peer dep missing: node-sass@^4.0.0, required by sass-loader@6.0.6
npm ERR! peer dep missing: webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0, required by sass-loader@6.0.6

Ng command not found.
sh: ng: command not found

sh-3.2# node -v
v8.9.4

sh-3.2# npm -v
5.6.0
MacOS high sierra 10.13.3

Workaround -- Got rid of above dependencies issue by following below steps

Open mac terminal, login as admin sudo su
Run - "npm list -global --depth 0"
cd to the folder which was shown by above command eg. mine was - /var/root/.npm-global/lib
run - sudo npm install node-sass@4.7.2
run - sudo npm install webpack@2.7.0
Check if the missing version are found are not in package.json
sh-3.2# open -t package.json
Run - "npm list -global --depth 0"

Sad command "ng" still not working so look the Ng issue and update the same.

This solves the missing configuration , please advice if i am missing anything in it.
Happy sharing
Cheers
raky

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
