### ISSUE TITLE
Css added to head by styles.bundle.js doesn't look for images at the correct path if it is in a subdirectory.

### ISSUE THREAD

**Issue by DDtMM** [angular/angular-cli#9789]
### Versions
1.7.1

### Repro steps
* Create a css file with the following `body { background-image: url('some-image.jpg'); }`
* Add an image in the same folder as the css file called some-image.jpg
* In angular-cli.config:
  * Set apps/outdir to a subdirectory (such as wwwroot/dist)
  * Add a reference to css file to apps/styles collection.
* Build
* Go to dist/index.html

### Observed behavior
If you view the Head element in developer tools and find the style element that corresponds to css file. The body rule will have a background-image: **url('some-image.123456.jpg')**.  You will also get a a 404 in network monitor for the image file.

### Desired behavior
The body rule will have a background-image: **url('/dist/some-image.123456.jpg')**.

### Mention any other details that might be useful (optional)
In my case I have a stylesheet from a npm package that references an image also included in the package.  After building the image is copied to the dist folder.  If I copy the image over to wwwroot it then works.

**Comment by clydin** [comment]
The outdir is not intended to have any effect on the built application itself.  It merely controls where on the filesystem the built files will be placed.  The use of the deploy url or base href options are meant to control the base paths for the resources of the application.

**Comment by filipesilva** [comment]
Closing as answered by @clydin, thanks!
