### ISSUE TITLE
"Support for offline applications"?

### ISSUE THREAD

**Issue by roypardi** [angular/angular-cli#979]
> Support for offline applications

> The index.html file includes a commented-out code snippet for installing the angular2-service-worker. This support is experimental, please see the angular/mobile-toolkit project for documentation on how to make use of this functionality.

The docs mention ["support for offline applications"](https://github.com/angular/angular-cli#support-for-offline-applications) but I am not seeing any commented out code in `index.html` generated through `ng build -prod`. Are the docs out of date or anticipating the future?

**Comment by ciesielskico** [comment]
The commented-out code for service-workers is in `/src/index.html`

**Comment by roypardi** [comment]
ok thanks!
