### ISSUE TITLE
Build with --aot is not resolving vars in import

### ISSUE THREAD

**Issue by calamarico** [angular/angular-cli#9799]
I have a problem doing the build with --aot flag: ```ng build --env=prod --aot```. I'm going to explain.

First, my ng cli version:

```
Angular CLI: 1.6.0
Node: 8.9.1
OS: linux x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.1
@angular/cli: 1.6.0
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0
```

And my angular.cli.json

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "portal-ui"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.scss"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "component": {
    },
    "serve": {
      "host": "0.0.0.0"
    }
  }
}
```

I have a environment class, one for develop and one for prod:

environment.ts:
```
export const environment = {
  production: false,
  apiUrl: 'https://api.XXX.kalamarico.XXX.com/admin/v1',
  portalUrl: 'https://portal.XXX.kalamarico.XXX.com',
};
```

environment-prod.ts:
```
export const environment = {
  production: true,
  apiUrl: 'https://' + document.location.hostname.replace('www.', 'api.') + '/admin/v1',
  portalUrl: 'https://' + document.location.hostname.replace('www.', 'portal.'),
};
```

And in my core.module.ts I'm using a environment variable to provide a logging server for the logger i'm using: ngx-logger:
```
import { environment } from 'environments/environment';

@NgModule({
  imports: [
    HttpClientModule,
    ClientModule,
    McBreadcrumbsModule.forRoot(),
    LoggerModule.forRoot({
      serverLoggingUrl: environment.portalUrl + '/logger',
      level: NgxLoggerLevel.DEBUG,
      serverLogLevel: NgxLoggerLevel.DEBUG
    }),
   ],
```

I'm not showing whole core.module.ts, but that is the important thing. My problem refers to that ```serverLoggingUrl``` variable for logger provide.

If I do the ```ng build --env=prod --aot``` let me show the generated bundle:
```
$ ​cat main.bundle.js | grep '/logger'
....
 { serverLoggingUrl: "undefined/logger", level: 1, serverLogLevel: 1 }, []), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵ
...
```
Take a look that environment.portalUrl is not resolved and it's ```undefined```. But if I omit the --aot and I do ```ng build --env=prod``` (without --aot):

```
$ ​cat main.bundle.js | grep '/logger'
serverLoggingUrl: __WEBPACK_IMPORTED_MODULE_7_environments_environment__["a" /* environment */].portalUrl + '/logger',
```

The result in my app is, when I use development version and prod version without --aot, I haven't any problem, the logger is connecting with my logging server succesfully.
But when I use --aot the logger put a console trace saying 'Failed to connect to server' due to that undefined. 

I know that --aot provides a compiled .js and by that, the .js generated without --aot don't resolve the variables and retrieve them in runtime. But, seeing my core.module, why --aot it's not resolving the environment variable?

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by calamarico** [comment]
Ok @filipesilva, I will post as soon as I have it

**Comment by samuelt1** [comment]
I have hit this problem, and you can see it here:
https://github.com/samuelt1/angular-problem

follow the readme to see how to reproduce the error.
I also made an issue in Angular/Angular: https://github.com/angular/angular/issues/22829

**Comment by calamarico** [comment]
@samuelt1 thanks for your support

**Comment by samuelt1** [comment]
This is kinda holding up a huge project I am working on.

**Comment by johngrogg** [comment]
Just added a follow-up comment to [angular/angular#22829](https://github.com/angular/angular/issues/22829).

The short of it is that this appears to be a general bug with the pre-compiler used in prod builds. Javascript logic in any code block that gets pre-compiled seems to fail from what I've seen.

**Comment by alan-agius4** [comment]
Closing in favor of angular/angular#22829.
