### ISSUE TITLE
Karma Tests run with --watch=true by default

### ISSUE THREAD

**Issue by delasteve** [angular/angular-cli#980]
1. OSX El Capitan

2. 
```
angular-cli: 1.0.0-beta.5
node: 5.11.1
os: darwin x64
```
3. `ng test`

4. No failures

5. The README implies running `ng test` will only run the tests once and you need to use `--watch` to enable watch mode. Currently, this is not the case and you need to use `--watch=false` https://github.com/angular/angular-cli#running-unit-tests
https://github.com/angular/angular-cli/blob/master/addon/ng2/commands/test.js#L14

What is the intended use? I will be glad to put a PR in for either updating the `README.md` or to update  the `ng test` command.

**Comment by filipesilva** [comment]
The README is the one wrong, the behaviour changed some time ago. I'll put up a PR with updated info.
