### ISSUE TITLE
non-Angular decorator treated as dead code

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#9800]
Originally filed as https://github.com/angular/angular/issues/22452

## Current behavior

When compiling for prod (using aot and `UglifyJS`), dead code is removed without the possibility for the developer to fine tune the behavior of the `UglifyJS`. This poses problems in certain use cases. Example:

`app.component.js`:

```
import { OnInit, Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app';
  aClass: any;

  ngOnInit(){
    console.log('checking out the component');
    this.aClass ? this.aClass.sMethod() : console.log('aClass is null');
  }
}

export function CustomAnnotation(obj) {
    console.log('hello', obj);
    AppComponent.prototype['aClass'] = obj;
    console.log('AppComponent is', AppComponent);
}
```

Then, in some file we could have:

```
@CustomAnnotation
export class AnnotatedClass{
    public static sMethod(){
        console.log('hello, I am a static method');
    }
}
```

As seen in the example, the `AnnotatedClass` class is going to be added to the properties of `AppComponent` using a custom annotation. I would expect when launching the application, to see in the console the message `hello, I am a static method`. This happens when compiled with aot for dev, but not when compiled for prod (which includes minification).

The problem is that the minifier is going to remove this class because is considered as dead code. Obviously, this is not dead code. 

The full project can be found here: http://popestii.eu/cloud/index.php/s/EliezZgizc7zHhA/download

Project compiled with `ng build --aot -sm false --environment prod --extract-css true --build-optimizer true --named-chunks false --output-hashing all --output-path dist-dev --base-href="/bug-report/dist-dev" --deploy-url="/bug-report/dist-dev"` can be tested here: 

http://popestii.eu/bug-report/dist-dev/index.html

Project compiled with `ng build --output-path dist-default --base-href="/bug-report/dist-default/" --deploy-path="/bug-report/dist-default/"` can be found here: 

http://popestii.eu/bug-report/dist-default/index.html

Project compiled with `ng build --prod --output-path dist-prod --base-href="/bug-report/dist-prod/" --deploy-url="/bug-report/dist-prod/"` can be found here:

http://popestii.eu/bug-report/dist-prod/index.html

## Expected behavior

I would expect to see the message `hello, I am a static method` in the developper tool's console (the static method should be executed by `ngOnInit` from the component). 

## Minimal reproduction of the problem with instructions

* download the project from here: http://popestii.eu/cloud/index.php/s/EliezZgizc7zHhA/download
* do `ng serve --prod`
* check the developer tools => The static method from the class `AnnotatedClass` is not called. 

If you try and serve it like this: `--aot -sm false --environment prod --extract-css true --build-optimizer true --named-chunks false --output-hashing all` (which basically should simulate the prod environment without minification), then everything is fine. 

## What is the motivation / use case for changing the behavior?

The developer should be allowed to fine tune the behavior of `UglifyJS` so in certain cases he could set the `dead_code` to false, so dead code would not be removed, if this poses problems. 

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v8.9.4 
- Platform:  Windows 7

**Comment by xmlking** [comment]
It is breaking many 3rd pretty libs who provide custom decorators e.g., ngxs 
We need option to desable UglifyJS for prod builds

**Comment by mgechev** [comment]
@xmlking can you still reproduce this issue with the latest CLI?

**Comment by xmlking** [comment]
Ngxs issue is solved

**Comment by filipesilva** [comment]
Closing as resolved then.
