### ISSUE TITLE
How to create angular 4 project with latest angular cli

### ISSUE THREAD

**Issue by nagarjun-immadi** [angular/angular-cli#9801]
![angular cli](https://user-images.githubusercontent.com/5477552/36736760-65ce77cc-1bff-11e8-8519-701c987b32e5.PNG)

I am using angular cli 1.6.1 . 'ng new' command creating angular 5 project. How can i switch angular version to 4.

Thanks in advance.

**Comment by lomo1** [comment]
i think you can update `package.json`  set the dependencies like `@angular/...` from 5 to 4. 
then do `npm install`.
of course, it not a very good solution, because it will update `@angular/core`、`@angular/compiler` ... etc.

**Comment by blackholegalaxy** [comment]
See : https://github.com/angular/angular-cli/issues/8200#issuecomment-339977020

**Comment by vamshi9666** [comment]
this isn't actually a issue .

**Comment by filipesilva** [comment]
Closing as answered by @lomo1 and @blackholegalaxy, thanks!

**Comment by suraliya** [comment]
You can use below command to create angular 4 project using higer versinos of CLI
**ng new yourProjectName -ng4**
