### ISSUE TITLE
Cannot find module './node-modules-paths.js'

### ISSUE THREAD

**Issue by vamshi9666** [angular/angular-cli#9806]
### Versions
```
"@angular/cli": "^1.7.1",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
```

### Repro steps

* installed latest angular/cli
* changed version of @angular/cli from `~1.7.1` to `^1.7.1` as solution from issue #9307
*

### Observed behavior
```
$ ng serve 
module.js:559
    throw err;
    ^

Error: Cannot find module './node-modules-paths.js'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vamshi/myApps/ang/myAng/node_modules/resolve/lib/async.js:5:24)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
error Command failed with exit code 1.

```

### Desired behavior
to see the basic app in browser

i didnt changed anything in code , but received same error . tried npm install , but it was stuck for hours .

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by vamshi9666** [comment]
ok . on it .

**Comment by vamshi9666** [comment]
i think its even trouble with node_modules . 
now when i tried `ng new min`
it was not even able to make a skeleton app 
error : `$ ng new min`
              module.js:559`
`    throw err;`
   ` ^`

`Error: Cannot find module './node-modules-paths.js'`
    `at Function.Module._resolveFilename (module.js:557:15)`
    `at Function.Module._load (module.js:484:25)`
    `at Module.require (module.js:606:17)`
    `at require (internal/module.js:11:18)`
    `at Object.<anonymous> (/home/vamshi/.config/yarn/global/node_modules/resolve/lib/async.js:5:24)`
    `at Module._compile (module.js:662:30)`
    `at Object.Module._extensions..js (module.js:673:10)`
    `at Module.load (module.js:575:32)`
    `at tryModuleLoad (module.js:515:12)`
    `at Function.Module._load (module.js:507:3)`

**Comment by AlankruthSai** [comment]
@vamshi9666  
Try setting the path like "D:\nodejs\"  {here nodejs is the file which i've created to install npm }
This worked for me when i encountered the same err559
Even if this doesnot work try to install it in new drive and then set the path to the complete file

**Comment by vamshi9666** [comment]
i use linux .so how can i ?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
