### ISSUE TITLE
ng build wiki page might create confusion regarding custom environment configs

### ISSUE THREAD

**Issue by nechita** [angular/angular-cli#9809]
https://github.com/angular/angular-cli/wiki/build#build-targets-and-environment-files

I think the wiki page can generate confusion regarding how to add custom environments configs for your Angular app. I've fallen in trap with my own app.

This is the section I'm referring to:

> You can also add your own env files other than dev and prod by doing the following:
> - create a `src/environments/environment.NAME.ts`
> - add `{` "NAME": 'src/environments/environment.NAME.ts' }` to the `apps[0].environment`s object in `.angular-cli.json`
> - use them via the `--env=NAME` flag on the build/serve commands.

A few lines up, we have a different key value suggestions for custom environments:

```json
"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}
```

The above is correct in the context of the fact that by default in the `.angular-cli.json` you have set `root` path to `src`.

I had this as my key value pair in my `.angular-cli.json`, based on the wiki suggestion.

```json
"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "src/environments/environment.ts",
  "prod": "src/environments/environment.prod.ts"
}
```

Every time I tried a custom build with my env configs , **I was always getting the configuration from the default env file**.

I think the wiki needs to add a mention regarding the `root` path or maybe in the future, the Angular CLI wouldn't hurt to throw a warning during the build about the fact that you will build the app with the default env file.

I wouldn't want to end this issue submission without thanking you for all the work, I really appreciate everything you are doing.

**Comment by joeskeen** [comment]
👍 This issue has been biting me hard today... a little clarity on the subject would be greatly appreciated.

**Comment by tiaguinho** [comment]
@mgechev this information doesn't exist on the page anymore. Can I add again?

**Comment by mgechev** [comment]
We'll make changes in the CLI wiki. We cannot proceed with this issue yet, we'll have to figure out where we're going to host the page.

**Comment by filipesilva** [comment]
Now that we have https://angular.io/guide/workspace-config I feel there's more context about these options and how to use them, which seems to address this issue.

**Comment by nechita** [comment]
So happy to see this resolved. Thx again guys for all your hard work.
