### ISSUE TITLE
'instanceof' returns different results in a development and production build

### ISSUE THREAD

**Issue by alexeykostevich** [angular/angular-cli#9810]
### Versions
```
Angular CLI: 1.7.1
Node: 8.9.4
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps

Here is a minimal application to reproduce the issue: https://github.com/alexeikostevich/angular-cli-instanceof-issue

The application allows to open a [Kendo UI Dialog](https://www.telerik.com/kendo-angular-ui/components/dialogs/) and see its result.

**Development Build**
* Build the application in the development mode
```
npm start
```
* Open the application
* Open and close a dialog

Result: 'Dialog result is true' is displayed.

**Production Build**
* Build the application in the production mode
```
npm run build
```
* Open the application
* Open and close a dialog

Result: 'Dialog result is false' is displayed.

### Observed behavior
Code with the `instanceof` operator behaves differently in the development and production build.

### Desired behavior

The application should behave  the same way regardless of the build mode.

### Mention any other details that might be useful (optional)
I assume that the issue can be caused by duplicated imports from Webpack (like [#4614](https://github.com/webpack/webpack/issues/4614)).

Our team met the same issue before in another application.

The issue is not reproducible anymore with the latest `@progress/kendo-angular-dialog` package. However, since this issue makes using `instanceof` unpredictable, it can be essential to find out the real cause.

**Comment by alexeikostevich** [comment]
Add @gyoshev from the 'Kendo UI for Angular' team to the conversation.

**Comment by skreborn** [comment]
It looks like `instanceof` isn't behaving any differently - as per expected - in regard to the build mode, **but the variable's constructor isn't the same `DialogCloseResult` as the one you are checking for**. `DialogCloseResult` is, in fact, defined **twice** in your minified bundle - once for the library, and once for your own use. These two, even though they have matching names in the source, are not technically the same class. As to why this is happening is still a mystery to me, but I'm looking further into it.

**Comment by alexeikostevich** [comment]
@skreborn , thank you for looking at this. I apologize if the title is a bit confusing. You made really perfect and precise statement about the issue :)

**Comment by clydin** [comment]
`DialogCloseResult` is an empty class which means it will be downleveled (ES5) to the following:
```
var DialogCloseResult = /** @class */ (function () {
    function DialogCloseResult() {
    }
    return DialogCloseResult;
}());
```
This is the equivalent of (and the result when minified):
```
var DialogCloseResult=function(){};
```

As `function(){}` is quite small, it is most likely being inlined directly at the point of use.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
