### ISSUE TITLE
TSServer not finding imports from node_modules on new cli app

### ISSUE THREAD

**Issue by dubcdr** [angular/angular-cli#9817]
### Versions
```
Angular CLI: 1.7.1
Node: 9.4.0
OS: darwin x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps

* Create a new cli project with `ng new [name]`
* Open your this project in your favorite editor that supports auto imports. I used VSCode with TS Hero as well as Vim with tsuquyomi.  
* In app.component.ts try adding a class member `form: FormGroup` and then using whatever tool you want try doing an auto import. 

### Observed behavior
Error from TS Hero in VS Code
```
2018-02-28T15:44:07.675Z - error: [DeclarationManager] A workspace did encounter an error.
2018-02-28T15:44:07.676Z - error: [WorkspaceDeclarations] Error during indexing of workspacefiles. {"error":"TypeError: Cannot read property 'length' of undefined","workspace":"/Users/driley/dev/temp/cli-test"}
```
Error from Tsuguyomi
```
[Tsuquyomi] Nothing was hit.
```
![1__shell](https://user-images.githubusercontent.com/5508644/36797845-a0a631f4-1c6e-11e8-8e50-293dcd85e39f.jpg)

### Desired behavior

Have TS Server be able to resolve node module imports

### Mention any other details that might be useful (optional)

- I still have other angular cli projects where I'm not seeing a problem. 
- I also am able to auto import from components or classes in the src folder. It's just stuff in node_modules
- If i manually add the import it is resolved correctly. 
- I tried downloading [this](https://github.com/gdi2290/angular-starter) repo and was able to do auto imports from it.

**Comment by vamshi9666** [comment]
this auto import is dealt by your editor . 
can you mention , which editor you have used in previous project , in which auto import worked .
and as you mentioned to "have ts server ". do you mean to make server.ts get ability to auto import.

**Comment by dubcdr** [comment]
I've mentioned 2 editors that I use. VS Code with TS Hero, and Vim with tsuquyomi. And no, i'm referring to typescripts server, which IDEs use so you can do things like rename symbol, find imports and it cover type checking for you. 

So basically I have projects that were created months ago using angular cli where I don't see this problem, in either editor. So if i create a new component and add a FormGroup to it like `public form: FormGroup` and then in VS Code i can do command + . or TS Heros auto import and it'll automatically find the import from node modules. 

but with the new app that i created yesterday using the above version of cli it can't locate anything from node_modules, and I believe somewhere in one of the angular cli package dependencies there is something that is breaking the tsserver.

**Comment by filipesilva** [comment]
Are you still seeing this problem?
