### ISSUE TITLE
URL resolution: use `./foo.html` for relative paths

### ISSUE THREAD

**Issue by mprobst** [angular/angular-cli#983]
See https://github.com/angular/angular/issues/8953

We should generate app layouts using `./` paths.

**Comment by mprobst** [comment]
@hansl @IgorMinar @jelbourn FYI

**Comment by hansl** [comment]
This will instead be an issue to generate the code as explained in this issue. Issue https://github.com/angular/angular/issues/8953 has been filed on the core side.

**Comment by hansl** [comment]
Closing this as obsolete. This has been done (and people are struggling but moving over to new conventions).
