### ISSUE TITLE
ERROR in Error: No NgModule metadata found for 'AppModule'.

### ISSUE THREAD

**Issue by lamjar** [angular/angular-cli#9830]
ERROR in Error: No NgModule metadata found for 'AppModule'.
    at NgModuleResolver.resolve (G:\..........\node_modules\@angular\compiler\bundles\compiler.umd.js:20285:23)
    at CompileMetadataResolver.getNgModuleMetadata (G:\..........\node_modules\@angular\compiler\bundles\compiler.umd.js:15238:60)
    at visitLazyRoute 
(G:\..........\node_modules\@angular\compiler\bundles\compiler.umd.js:31176:104)
    at AotCompiler.listLazyRoutes (G:\..........\node_modules\@angular\compiler\bundles\compiler.umd.js:31144:20)
    at AngularCompilerProgram.listLazyRoutes 
(G:\..........\node_modules\@angular\compiler-cli\src\transformers\program.js:156:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes 
(G:\..........\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools 
(G:\..........\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:263:66)
    at Promise.resolve.then.then (G:\..........\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:583:50)
    at <anonymous>

**Comment by filipesilva** [comment]
I think you're having some weird errors and can't debug it, and so, understandably, you're frustrated. But this is a tracker for bugs and feature requests. If we can we also try to help with support requests. We're very lucky to have awesome community members that also spend time trying to help people here in the issue tracker.

But we can't really help much at all if you don't fill in the issue template. I read your issue and have no idea what's going wrong and how to help you. And when other users search the issue tracker and see your issue, it also doesn't help them.

So I think the best thing to do is to close this issue, and ask you to open a new one. In that new one please fill in the issue template and give us an idea of what's happening and how to reproduce it. That way we'll have a chance to help you.
