### ISSUE TITLE
Somehow auto reload feature is not working 

### ISSUE THREAD

**Issue by rvdabhi** [angular/angular-cli#9831]
### Versions
```
Angular CLI: 1.7.2
Node: 9.5.0
OS: linux x64
Angular: 5.2.7
```

### Repro steps
I have installed angular cli and created new project with ng new hello-world. Now page is not auto reloading when I change anything in the files.

Please help.

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

### Desired behavior
Should auto reload when changes occurrs.

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
