### ISSUE TITLE
Errors: .appRoot should match format "path"

### ISSUE THREAD

**Issue by dandax** [angular/angular-cli#9837]
### Versions
```
Angular CLI: 1.7.1
Node: 8.9.4
OS: win32 x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.2
@angular/cli: 1.7.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps
* Create a new app using the cli
* When complete, add a new `lib` directory under `src` and another `ui` directory under `lib`
```
src/
  lib/
    ui/
```
* Add a new `app` to the `.angular-cli.json` config named `lib` and set `appRoot` to `lib/ui` as follows:
```
"apps": [
  {
    "name": "app",
    ...
  },
  {
    "name": "lib",
    "root": "src",
    "appRoot": "lib/ui",
    "outDir": "dist",
    "test": "test.ts",
    "tsconfig": "tsconfig.app.json",
    "testTsconfig": "tsconfig.spec.json",
    "prefix": "lib"
  }
]
```
* Generate a new module setting `lib` as the `--app` option
```
ng g m --app=lib ui
```

### Observed behavior
```
Error: Schematic input does not validate against the Schema: {"name":"ui","sourceDir":"src","appRoot":"lib\\ui","path":"lib/ui","routing":false,"routingScope":"Child","spec":false,"flat":false,"commonModule":true}
Errors:
  .appRoot should match format "path"
Schematic input does not validate against the Schema: {"name":"ui","sourceDir":"src","appRoot":"lib\\ui","path":"lib/ui","routing":false,"routingScope":"Child","spec":false,"flat":false,"commonModule":true}
Errors:
  .appRoot should match format "path"
```
It's confusing `"appRoot":"lib\\ui"` with `"path":"lib/ui"`

### Desired behavior
Should generate the module without errors.

I have confirmed this works using bash

**Comment by dandax** [comment]
@j4njusa I haven't tried it but I would assume reverting back to an earlier version would be the easiest workaround.

In my case, I have the Windows Subsystem for Linux installed. So in VSCode I can switch over to bash and run the same command there. In my experience running ng commands in bash run slower on Windows so I don't use it very often. Only for this issue until it's fixed.

**Comment by hansl** [comment]
Hi @dandax,

Have you tried updating to CLI 6.0?  Or better yet, wait a few weeks for 7.0 to be out.

I'm going to close this as this version is deprecated, and this is not a critical security bug.
