### ISSUE TITLE
timespan 2.3.0 vulnerability

### ISSUE THREAD

**Issue by billsmith5** [angular/angular-cli#9839]
### Versions
@angular/cli@1.6.7

### Observed behavior
My company scans all dependencies, and it quarantined timespan 2.3.0 from
    karma@2.0.0 > log4js@2.5.2 > loggly@1.1.1 >  timespan@2.3.0

Because of this I cannot build my cli project.

### Desired behavior
A clean build

### Mention any other details that might be useful (optional)
https://snyk.io/test/npm/karma/2.0.0?
https://snyk.io/test/npm/timespan?

**Comment by hansl** [comment]
Hi @billsmith5 ,

snyk.io categorize this vulnerability to high severity but that's superfluous; timespan isn't used directly and karma is a local only tool; you would dos yourself.

There was already a report filed for timespan (see https://github.com/indexzero/TimeSpan.js/issues/10) but it's from September and might not be fixed soon. There's nothing much we can do, other than suggest you force the version of karma or log4js (or timespan). Loggly and Timespan are both unmaintained.

According to https://github.com/log4js-node/log4js-node/issues/614, if you're not using loggly you can simply remove it from your `package-lock.json` or `yarn.lock` (it's an optional dependency). That should get you unblocked.

Closing this as you can use the CLI by configuring your package manager (e.g. running `npm install -no-optional` on the first install). Meanwhile the `log4js` library are working on the appropriate steps.
