### ISSUE TITLE
Function calls are not supported in decorators

### ISSUE THREAD

**Issue by fuyuko-akiyoshi** [angular/angular-cli#9845]
### Versions
```
   _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.4
Node: 6.10.2
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
In my routes file, I have set up my routes using an enum class to get the url of each path. 
Eg:
 
const enums = new MortgageFormEnums();
const titleHeading = 'Squirrel Mortgage Application | ';
 
export const mortgageFormRoutes = [
  {
    path: 'mortgage',
    component: MortgageComponent,
    children: [
{
        path: enums.routes.properties[enums.routes.start].url,
        component: StartComponent,
        data: {
          title: titleHeading + enums.routes.properties[enums.routes.start].name
        }
      }
];
etc...

But this is throwing an error when I use AoT compiler. It doesn't like that I instantiated an enum class in the routes file. 

### Observed behavior
ERROR in src\app\mortgage\mortgage-form.module.ts(42,27): Error during template compile of 'MortgageFormModule'
  Function calls are not supported in decorators but 'MortgageFormEnums' was called in 'mortgageFormRoutes'
    'mortgageFormRoutes' calls 'MortgageFormEnums'.

### Desired behavior
Ideally I want to keep my routes hard coded only inside my MortgageFormEnums because I use them in a lot of different files to control the flow hence why I don't want to hard code the paths in the routes file, I'd rather grab them from my enum file. Is this at all possible? or am I going to just have to hard code them?

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
