### ISSUE TITLE
coverage not configurable in multi app envioronment

### ISSUE THREAD

**Issue by ragsnas** [angular/angular-cli#9849]
### Versions
```
Angular CLI: 1.6.7
Node: 8.9.4
OS: linux x64
Angular: 5.2.6
```

### Repro steps
* Set up a project with two apps
* configure both apps in .angular-cli.json
* use part of one app in the other
* run tests for each app with coverage reports
* check respective coverage reports

### Observed behavior
Both coverage reports include the models/parts used from the respective other app.
So the coverage for app1 does not just consider app1.
All attempts to exclude files have failed _(i.e. karma.conf exclude or coverageReporter.exclude attributes_)

### Desired behavior
The test.exclude parameter from .angular-cli.json should be usable per app.

**Comment by filipesilva** [comment]
Angular CLI now supports multiple projects with separate configuration. I believe this issue is now addressed.
