### ISSUE TITLE
3rdpartylicenses.txt missing some licenses

### ISSUE THREAD

**Issue by flipZomb** [angular/angular-cli#9851]
The 3rdpartylicenses.txt does not contain the licences for all packages in package.json.

e.g. "@angular/platform-server" and "@angular/http" are missing.

### Versions
 
Angular CLI: 1.7.2
Node: 8.9.4
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.2.3
@angular/cli: 1.7.2
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0

### Repro steps
I presume run
ng build --aot --prod

### Observed behavior
3rdpartylicenses.txt missing some licenses

### Desired behavior
Would expect to see all licenses in 3rdpartylicenses.txt.

**Comment by clydin** [comment]
Are either of those packages used within the application?  Only packages that are actually bundled will be included.

**Comment by flipZomb** [comment]
ah ... thank you for pointing that out !! Indeed, I removed them and it compiles and works very nicely without them. Guess they become unneccessary during some update. 

But what about something like "rxjs" which I am using and does not appear in the licence file ?

**Comment by clydin** [comment]
Yes this is incorrect. It has been corrected in v6 (currently in beta).

**Comment by flipZomb** [comment]
ok. Thank you !
