### ISSUE TITLE
Angular Compiler Error (seems to be the wrong instance)

### ISSUE THREAD

**Issue by messerbill** [angular/angular-cli#9854]
when I try to run "ng serve" I run into the following issue:

> ERROR in ./src/main.ts
Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.

Following this suggestion:

> $ npm ls `@ngtools/webpack`
test@0.0.0 C:\Daten\Projects\test
 `-- @angular/cli@1.7.2
  `-- @ngtools/webpack@1.10.1

So there are no multiple webpack versions installed. I tried to reinstall `@angular/cli` for multiple times....globally, locally, after deleting `node_modules` and using `npm cache clean -f` and `npm cache verify`. I did the same with `webpack`. Sadly there are not really many other people running into this issue, what makes it hard to solve. My google researches were not successfull due to all i could found was a chinese page translating that error into chinese and these two SO links (which do not provide a solution for me):

https://stackoverflow.com/search?q=Angular+Compiler+was+detected

https://stackoverflow.com/questions/48774405/error-several-ngtools-webpack-packages-installed

https://stackoverflow.com/questions/47094987/share-node-modules-between-meteor-1-6-server-angular-cli-client-angular-mete

my package.json:

    "dependencies": {
        "@angular/animations": "^5.2.0",
        "@angular/common": "^5.2.0",
        "@angular/compiler": "^5.2.0",
        "@angular/core": "^5.2.0",
        "@angular/forms": "^5.2.0",
        "@angular/http": "^5.2.0",
        "@angular/platform-browser": "^5.2.0",
        "@angular/platform-browser-dynamic": "^5.2.0",
        "@angular/router": "^5.2.0",
        "core-js": "^2.4.1",
        "rxjs": "^5.5.6",
        "zone.js": "^0.8.19"
      },
      "devDependencies": {
        "@angular/cli": "^1.7.2",
        "@angular/compiler-cli": "^5.2.0",
        "@angular/language-service": "^5.2.0",
        "@types/jasmine": "~2.8.3",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "~6.0.60",
        "codelyzer": "^4.0.1",
        "jasmine-core": "~2.8.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~2.0.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.1.2",
        "ts-node": "~4.1.0",
        "tslint": "~5.9.1",
        "typescript": "2.6.2"
      }
    }

**note:** 

The project can be compiled at my brothers PC - the only difference is the OS (he uses win7 while i use win10). 

greetings and have a nice week end,

Messerbill

**edit:**

Updating `@angular` to `5.2.7` makes no difference.

**Comment by clydin** [comment]
The full command suggestion is actually `npm ls @ngtools/webpack`. The error is due to multiple versions of the `@ngtools/webpack` package being present in the project.  You can try deleting both the `package-lock.json` file and the `node_modules` folder and then install again.

**Comment by messerbill** [comment]
Hi,
thanks for your answer. `npm ls @ngtools/webpack` is exactly what i did (as i wrote in my question).

>You can try deleting both the package-lock.json file and the node_modules folder and then install again.

Just like i wrote in my question - this is what i tried hundrets of times

>The error is due to multiple versions of the @ngtools/webpack package being present in the project.

no - my `npm ls @ngtools/webpack` does **NOT** return multiple versions.

**Comment by messerbill** [comment]
Finally. Updating my global `typescript` version fixed it. Now using tsc `2.6.2` globally and it works.

**Comment by yanlee26** [comment]
It's really tricky!

**Comment by mialy** [comment]
I have today exactly the same issue as in the screenshot of @messerbill 

Fixed it by deleting (or renamed) node_modules/ in parent directories (parents of the project directory itself). Seems like npm or angular searches for node_modules in whole directory tree recursively, don't know...

**Comment by nhhockeyplayer** [comment]
sometimes we like to park node_modules in a close area to avoid having to wait for deleting it... 
thats a no no
npm will find it and screw up your build

but thats not the problem with this issue

could be typescript version I am still wrestling with the webpack packages thing

**Comment by irfanku** [comment]
Worked for me, thanks.

**Comment by gajalchouhan** [comment]
please someone help me to sort out this thing.
I tried to install new version of typescript and node modules. I am still getting the same error.

**Comment by messerbill** [comment]
@gajalchouhan 
some advises from my site:

* uninstall local angular cli
* uninstall global angular cli
* uninstall global typescript 
* (if you're on windows uninstall node.js)
* delete package-lock.json
* delete angular/cli dependencies from package.json
* install latest node.js and npm
* install latest angular cli (globally and locally)
* try it

I am sure that not every of these steps is needed, but due to the error is very missleading you should follow these steps. I am quite sure that it will work afterwards.

Greetings

**Comment by gajalchouhan** [comment]
Please, someone, suggest to me that I am facing the same problem.
Actually my project in Angular version 1.0.0-beta.28.3. I am using angular as global angular 6.2.2.
when I am trying to user ng serve this error has come. Can anyone suggest me that what should I do?

ERROR in ./src/main.ts
Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.
    at Object.ngcLoader (/home/gajal/lok/AuBankProject/node_modules/@ngtools/webpack/src/loader.js:458:19)
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
ERROR in ./src/polyfills.ts
Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.
    at Object.ngcLoader (/home/gajal/lok/AuBankProject/node_modules/@ngtools/webpack/src/loader.js:458:19)
 @ multi ./src/polyfills.ts

**Comment by gajalchouhan** [comment]
![screenshot from 2018-09-18 00-40-43](https://user-images.githubusercontent.com/26565787/45673621-d0cdfc80-bb48-11e8-8628-c5674f3f5af2.png)

**Comment by messerbill** [comment]
@gajalchouhan did you follow the steps i wrote earlier?

**Comment by DivyanshuLoktra** [comment]
> @gajalchouhan did you follow the steps i wrote earlier?

I did all of those
no results

**Comment by DivyanshuLoktra** [comment]
So i was able to remove the "instance of wrong class" error
But facing a new one now 

![image](https://user-images.githubusercontent.com/43741053/46660784-6bb07880-cbd5-11e8-8601-14d80c6f8f66.png)

**Comment by Dafnik** [comment]
How did you fix it?

**Comment by DivyanshuLoktra** [comment]
1) uninstall local and global version of angular
2) reinstall it
3) try again and again

**Comment by messerbill** [comment]
@DivyanshuLoktra I really recommend to uninstall everything, Angular, Angular Cli, Typescript, Node and npm. Make sure that you also remove the global npm modules. Afterwards reinstall everything and care for the versioning.

**Comment by DivyanshuLoktra** [comment]
Bill,
I was able to run the project, Had to uninstall things locally for a while. But things are running now.
The only thing is I do not know how and why ?
two commands
1) npm install @angular/cli@1.4.10
2) npm uninstall @angular/cli@1.4.10

I will do more experiments post this and let everyone know.

**Comment by valorad** [comment]
This error pops up when I was using `pnpm` on Windows, changing to `npm` solved this issue. I guess it has something to do with `pnpm` mis-configured the dependency links.
