### ISSUE TITLE
Cli 1.7.2 cannot build nested app in prod

### ISSUE THREAD

**Issue by aurnot** [angular/angular-cli#9855]
I have a hybrid angularjs app that is progressively upgraded to Angular 5+. Some node modules are shared between the two apps.
Folder structure is as follow
```
parent-app/package.json            // hybrid php/angularjs app
parent-app/child-app/package.json  // Angular 5 app
```
When updating cli from 1.6 to 1.7, the production build starts to fail.

### Versions
```
Angular CLI: 1.7.2
Node: 8.9.4
OS: linux x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps

1. Create the parent "project"
    `mkdir parent-app && cd $_`
2. Create a minimalistic package.json with a node module that exhibits the issue
    `yarn add @uirouter/core`
3. Create the child Angular app
    `ng new child-app`
4. Move into our fresh ng app
    `cd child-app`
4. Add a reference the node module of the parent app in the child app
    `sed -i '1s/^/import "@uirouter\/core";\n/' src/app/app.module.ts`
5. Build
    `ng b --prod`

### Observed behavior
```
ERROR in ../node_modules/@uirouter/core/lib/vanilla/memoryLocationService.js
Module not found: Error: Can't resolve 'tslib' in '/home/parent-app/node_modules/@uirouter/core/lib/v
anilla'
ERROR in ../node_modules/@uirouter/core/lib/vanilla/pushStateLocationService.js
Module not found: Error: Can't resolve 'tslib' in '/home/parent-app/node_modules/@uirouter/core/lib/v
anilla'
ERROR in ../node_modules/@uirouter/core/lib/vanilla/hashLocationService.js
Module not found: Error: Can't resolve 'tslib' in '/home/parent-app/node_modules/@uirouter/core/lib/v
anilla'
```

### Desired behavior
Build my super-awesome nested Angular app :p 

### Mention any other details that might be useful (optional)
- This was working fine with various cli versions up to **1.6.8**
- It work with 1.7.2 when disabling build optimizer `ng b --prod --build-optimizer false`
- `yarn add tslib` to the parent project does not solve it

**Comment by acuntex** [comment]
I can confirm this.

We are not using a nested app but the following structure:
./server_app/...
./angular_app/...

The angular_app uses the response models from our rest server so that we don't have to duplicate the interfaces.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by aurnot** [comment]
Thanks for the followup. I tested it again with Angular CLI 7.2.3, and got the same error as before. 

However: now, adding the "missing" tslib to the parent package.json allows `ng build --prod` to complete without error.

Not sure if it is a viable long-term solution, but it feels cleaner than duplicating all dependencies in the 2 projects :+1:
