### ISSUE TITLE
Facing issue in installing Angular CLI

### ISSUE THREAD

**Issue by nagtej** [angular/angular-cli#9857]
### Versions
Node JS: v6.10.0
npm:3.10.10
Windows: 7

### Repro steps

* Navigate to the project root folder
* Installed node js and npm
* hit the command npm install -g @angular/cli

### Observed behavior

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:113:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:82:11
gyp ERR! stack     at Object.oncomplete (fs.js:297:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Matt Cashatt\node_modules\jquery\node_modules\contextify
gyp ERR! node -v v0.8.21
gyp ERR! node-gyp -v v0.8.4
gyp ERR! not ok
Build failed with error code: 1

### Desired behavior
 I am expecting angular cli install properlry.

Can you let me know, how to resolve this issue.

**Comment by clydin** [comment]
This seems like a problem with node/npm or the `node-gyp` package; and not with Angular CLI.  It is also recommended to use the LTS version of node (currently 8.9.4).

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
