### ISSUE TITLE
aot build doesn't report invalid component output name in template

### ISSUE THREAD

**Issue by diminutivesloop** [angular/angular-cli#9858]
### Versions
```
Angular CLI: 1.7.2
Node: 8.9.4
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.4.2
webpack: 3.11.0
```

### Repro steps

* Declare an output event binding in a component template where the named output event does not exist.
* Build with `--aot=true`.

### Observed behavior
The build succeeds without errors.

### Desired behavior
The compiler should output an error message similar to how it already does for a named component input property that does not exist.

**Comment by alexzuza** [comment]
Consider the following child component:

```
@Component({
  selector: 'child',
  template: `
   <h2>Child component</h2>
   <button (click)="fireEvent($event.target)">Click me to fire custom event</button>
  `
})
export class ChildComponent {
  fireEvent(target) {
    target.dispatchEvent(new Event('customEvent', { bubbles: true }));
  }
}

```

As you can see there is not property adorned by `Output` decorator.

Now we can use this component as follows:
```
<child (customEvent)="onCustomEvent()"></child>
```
And parent component will successfully catch custom event emitted from child. 

But angular compiler can't predict what's the custom event you generated in your code.

**Comment by filipesilva** [comment]
Closing as answered by @alexzuza, thanks!
