### ISSUE TITLE
How to recognize html tags from source of translate-unit?

### ISSUE THREAD

**Issue by mousavidev** [angular/angular-cli#9863]
Hello,
I want to create tool for translation of the messages, i need to recognize the html tags from source of translate-unit.
how to recognize it?
Is there a regex pattern for it?

**Comment by rahulbhooteshwar** [comment]
@mousavidev This is not an issue with Angular CLI. I think it is not the best place for your query. You can raise an stake overflow question with more detials and proper tag for the same.

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
