### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by arunboyo** [angular/angular-cli#9875]
arunboyo-ThinkPad-T410 Desktop # npm install -g angular-cli
npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
loadDep:zone.js -> resolv - |##########---------------------------------------|
WARN engine extract-text-webpack-plugin@2.1.2: wanted: {"node":">=4.3.0 < 5.0.0 loadDep:zone.js -> resolv / |##########---------------------------------------|
WARN engine @ngtools/webpack@1.10.1: wanted: {"node":">= 6.9.0","npm":">= 3.0.0"loadDep:zone.js -> header \ |##########---------------------------------------|
loadDep:webpack-sources - \ |#################################------------------------------------------------------------------------------------------------------------------|
loadDep:json5 -> network  | |#################################--------------------------------------------------------------------------------------------------loadDep:webpack-sources - - |#############------------------------------------|
WARN engine schema-utils@0.3.0: wanted: {"node":">= 4.3 < 5.0.0 || >= 5.10"} (cunpm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
loadDep:yargs -> fetch    \ |##################-------------------------------|
WARN engine loader-runner@2.3.0: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (cu/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng

### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
arunboyo-ThinkPad-T410 Desktop # ng -v
/usr/bin/ng: line 40: exec: -v: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]

-->
```**Installation error**
npm WARN optional Skipping failed optional dependency /angular-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN optional Skipping failed optional dependency /angular-cli/webpack-dev-server/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN @angular/core@2.4.10 requires a peer of rxjs@^5.0.1 but none was installed.


### Repro steps
<!--
Simple steps to reproduce this bug.
Please include: commands run, packages added, related code changes.
A link to a sample repo would help too.
-->
* Step 1
* Step 2
* Step 3


### Observed behavior
```

```

### Desired behavior
<!--
What would like to see implemented?
What is the usecase?
What did you expect to see?
-->


### Mention any other details that might be useful (optional)

**Comment by clydin** [comment]
From the console output above:
```
npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. 
```

Please install with `npm install -g @angular/cli`

**Comment by arunboyo** [comment]
i already tried that way npm install -g @angular/cli

**Comment by Mrna1** [comment]
I have same issue on Ubuntu 16
