### ISSUE TITLE
Takes too long to set up an app.

### ISSUE THREAD

**Issue by strongSoda** [angular/angular-cli#9879]
It's a pain to setup an angular app as it takes a very long time to set up. Also, the size is very large.

It would be good if the dev team minifies the size as well as reduce the setup time.

### Versions
```
Angular 5.0.0
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by jotatoledo** [comment]
1. npm install -g angular/cli
1. ng new foo
1. cd foo
1. ng start

I dont think 4 steps could be considered "long setup"

**Comment by strongSoda** [comment]
It's not about 4 steps it's all the dependencies installation that takes time

**Comment by jotatoledo** [comment]
how much time does it need on your local?

**Comment by gruby-murzyn** [comment]
Google needs to do something on setup ang app takes too much time to install all dependencies

eg: ng new project alone takes almost 5-10 minutes wtf?  don't ask about installing angular itself :( 

Hope next release will be much better !! excuse my french

**Comment by alexeagle** [comment]
Let's use this issue to reduce the total size of downloaded artifacts. I think this consumes the majority of the time on slow connections.

https://github.com/angular/angular-cli/pull/13821 cut the transitive download size of `@angular/cli` package in half, which is a great start for upcoming version 8.

Other things we can do next:
- We can still make `@angular/cli` smaller. I think the next target should be `@angular-devkit/core/node` which could bundle in the `chokidar` library.
- I have a little utility project http://github.com/alexeagle/syzer - I should be able to point it at a package.json produced by our default schematics and measure the total download size of a new project

**Comment by maniadel** [comment]
I agree, generating a new app with angular 9 takes too long to install all the dependencies. 
I'm surprised on how long the ng new app takes. 

Is there somebody can explain why this duration ?  it took more than 20 min (I'm using fiber, cpu i7, ...)


here my configuration : 

Node : 12.16.0
npm: 6.13.4

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.1
@angular-devkit/core         9.0.1
@angular-devkit/schematics   9.0.1
@schematics/angular          9.0.1
@schematics/update           0.900.1
rxjs                         6.5.3
---------------------------------------------------------

**Comment by bugproof** [comment]
@maniadel the solution is simple: don't use angular 😄 I only had this problem with angular

**Comment by mgechev** [comment]
We're exploring ways to reduce the dependencies that Angular CLI has to download during project creation. The discussion doesn't seem very constructive at the moment, so I'll lock the issue. Expect updates in the changelog when we take an action.

**Comment by alan-agius4** [comment]
A lot has changed in the recent releases to reduce dependencies and improve the overall DX, and we will continue improving.

if you are experiencing issues please file a new issue explained the problem encountered.

Thanks.
