### ISSUE TITLE
No NgModule metadata found for 'function (){}'.

### ISSUE THREAD

**Issue by dmitriytretyakov** [angular/angular-cli#9881]
### Versions
```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.2
Node: 9.7.1
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps
I tried to use Angular Universal and use guide to prepare my project (https://angular.io/guide/universal). After all changes i build my project with command 'npm run build:universal' without any errors and then try to serve with 'npm run serve:universal'. After one second i received an error No NgModule metadata found for 'function (){}'.

### Observed behavior
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\agron\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve:universal' ]
2 info using npm@5.7.1
3 info using node@v9.7.1
4 verbose run-script [ 'preserve:universal',
4 verbose run-script   'serve:universal',
4 verbose run-script   'postserve:universal' ]
5 info lifecycle docklands-life@0.0.0~preserve:universal: docklands-life@0.0.0
6 info lifecycle docklands-life@0.0.0~serve:universal: docklands-life@0.0.0
7 verbose lifecycle docklands-life@0.0.0~serve:universal: unsafe-perm in lifecycle true
8 verbose lifecycle docklands-life@0.0.0~serve:universal: PATH: C:\Users\agron\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Xampp\hosts\docklands-life\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Condusiv Technologies\ExpressCache\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\ProgramData\ComposerSetup\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Xoreax\IncrediBuild;D:\Xampp_PHP_7.1.4\php;C:\Users\agron\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\agron\AppData\Local\Programs\Python\Python36\;C:\Ruby23-x64\bin;C:\Users\agron\AppData\Roaming\Composer\vendor\bin;C:\Users\agron\AppData\Local\Microsoft\WindowsApps;C:\Users\agron\AppData\Roaming\npm;%USER_DIR%\AppData\Local\Atlassian\SourceTree\git_local\bin;
9 verbose lifecycle docklands-life@0.0.0~serve:universal: CWD: D:\Xampp\hosts\docklands-life
10 silly lifecycle docklands-life@0.0.0~serve:universal: Args: [ '/d /s /c', 'node dist/server.js' ]
11 silly lifecycle docklands-life@0.0.0~serve:universal: Returned: code: 1  signal: null
12 info lifecycle docklands-life@0.0.0~serve:universal: Failed to exec serve:universal script
13 verbose stack Error: docklands-life@0.0.0 serve:universal: `node dist/server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\agron\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:127:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\agron\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:127:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid docklands-life@0.0.0
15 verbose cwd D:\Xampp\hosts\docklands-life
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\agron\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve:universal"
18 verbose node v9.7.1
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error docklands-life@0.0.0 serve:universal: `node dist/server.js`
22 error Exit status 1
23 error Failed at the docklands-life@0.0.0 serve:universal script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

### Desired behavior
I want to start local server server with angular universal features.

### Mention any other details that might be useful (optional)

Sorry for my bad english :)

**Comment by Mani2693** [comment]
I faced the same issue , For me its because of the node version , I was having node version 6.2.1 once I upgrade to v6.9.0 it works fine for me , Please upgrade and rebuild the project 

Additional info: This happens for me only in production mode build 

Thanks, 
Mani

**Comment by DmitriyTretyakov** [comment]
Thanks for your answer, but i has Node v 9.7.1, it's new version :)

**Comment by DmitriyTretyakov** [comment]
Update node.js to 9.8.0 and npm, it didn't help.

**Comment by Ruud-cb** [comment]
This unfortunately didn't fix the problem for me, I have explained in details the problem on this stackoverflow question, in hope it was not a bug but it appears to be one:
https://stackoverflow.com/questions/52892251/bootstrap-multiple-or-single-modules-based-on-url-in-main-ts

**Comment by clydin** [comment]
The CLI has been updated significantly since version 1.7.2.  The current stable version is 8.3.5.  If this problem is still being encountered with the current version, please consider opening a new issue with updated details.
