### ISSUE TITLE
ng generate route <name> created scaffolds not working.

### ISSUE THREAD

**Issue by UzairNouman** [angular/angular-cli#989]
I created the routes with angular cli, it created all the scaffolds and necessary references in the parent component :

`@Routes([ 
   {path: '/hero', component: HeroComponent}
])`

Also added the router outlet tag in the parent component's HTML template.Everything seems fine but still when i try to access that route,I see the parent template outputting but component whose template has to be resolved in the router outlet tag is not visible.
Although when I tried to make the project folder with npm as guided in the official angular docs,route works fine.

**Comment by filipesilva** [comment]
@UzairNouman that's odd. Can you give me exact reproduction steps that I can follow so I can debug it?

**Comment by UzairNouman** [comment]
Yeah,that's too odd.Maybe I am missing something.
I created a fresh project with angular cli `Problem` to test the routes problem.
What I concluded with the original docs,all you need to do to create a simple route is to follow 3 main steps,angular-cli does all that job with a single command, so why it is not working?

1-is to make changes to main component 

`ProblemComponent`
![problemcomp](https://cloud.githubusercontent.com/assets/12785891/15756583/564e4ab2-291b-11e6-9fc3-3ee3660ea597.JPG)

2-make changes to the  Route Component

`HeroComponent`

![hero](https://cloud.githubusercontent.com/assets/12785891/15757365/9d533d2a-291e-11e6-922c-90d9f49344ea.JPG)

3-Create `<router-outlet>`

`Problem Component's HTML`

![problemhtml](https://cloud.githubusercontent.com/assets/12785891/15756983/090efa1a-291d-11e6-9edc-db07dc7feac8.JPG)

`Project Structure`

![ps](https://cloud.githubusercontent.com/assets/12785891/15756995/11ee016c-291d-11e6-8d35-1a5dad15bd55.JPG)

`Output`

![op](https://cloud.githubusercontent.com/assets/12785891/15757067/51e00c0c-291d-11e6-8148-5d5c4f3df5cd.JPG)

You may have noticed `HeroComponent` in my directives,I was testing it by adding `<app-hero>` tag in the `problem.component.html` and surprisingly it works.

**Comment by graknol** [comment]
I am experiencing this too, I don't know, but perhaps it's something with the way angular-cli serves the files? I don't really know

**Comment by fadeojo** [comment]
@graknol I had the same issue and this 
```
import { RouteConfig , ROUTER_DIRECTIVES, ROUTER_PROVIDERS} from '@angular/router-deprecated';
@Component({
  moduleId: module.id,
  selector: 'hello-app',
  directives: [ROUTER_DIRECTIVES],
  templateUrl: 'hello.component.html',
  styleUrls: ['hello.component.css'],
  providers: [ROUTER_PROVIDERS]
})
@RouteConfig([
  {path: '/login',    component: LoginComponent,     name: 'Login'}
])
```
Fixed it. The router is broken in RC1 has breaking changes.

**Comment by UzairNouman** [comment]
angular-cli is using '@angular/router', @fadeojo  can you tell me how you are using '@angular/router-deprecated'?

**Comment by planser** [comment]
@UzairNouman try npm installing `@angular/router-deprecated` and adding the entry `@angular/router-deprecated` to Angular specific barrels in system-config.ts. It worked for me...

**Comment by oadeojo** [comment]
@UzairNouman the router has breaking changes in RC1.

**Comment by blacksonic** [comment]
Here are some bug reports on the main repository that might help till it gets fixed.
https://github.com/angular/angular/issues/8409
https://github.com/angular/angular/issues/9020

**Comment by UzairNouman** [comment]
Thanks @planser,you suggestion solved the issue.
