### ISSUE TITLE
Error with AoT compilation when using object with integer as keys in routes file

### ISSUE THREAD

**Issue by fuyuko-akiyoshi** [angular/angular-cli#9890]
### Versions
```
Angular CLI: 1.7.2
Node: 6.10.2
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps
I reference an object in my routes file that looks like this:
export const mortgageFormEnum = {
 routes: {
    start: 0,
    whatsUp: 1,
    refinance: 17,
    newAddress: 19,
    deposit: 2,
    addBorrower: 3,
    primaryIncome: 4,
    secondaryIncome: 5,
    properties: {
      0: { url: '', name: 'Start' },
      1: { url: 'whats-up', name: 'Whats Up' },
      2: { url: 'deposit', name: 'Deposit' },
      3: { url: 'add-borrower', name: 'Add Borrower' },
      4: { url: 'primary-income', name: 'Primary Income' },
      5: { url: 'secondary-income', name: 'Secondary Income' }
    }
  }
}

When compiling using AoT I get an error

### Observed behavior
Error during template compile of 'MortgageFormModule' Name expected in 'mortgageFormRoutes' 'mortgageFormRoutes' references 'mortgageFormEnum' at src\app\mortgage\mortgage-form.routes.ts(50,11) 'mortgageFormEnum' contains the error at src\app\mortgage\shared\mortgage-form.enums.ts(27,7).

It is pointing to the line after 'properties' as it doesn't like integers as keys. 

### Desired behavior
A javascript object can be defined using integers as keys so why is it throwing an error?

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by fuyuko-akiyoshi** [comment]
Ok I've recreated it and you can get it here:

https://github.com/fuyuko-akiyoshi/angular-bug

run npm build and you should get the error.

Looking forward to the fix!

**Comment by tomwanzek** [comment]
Ran into the same issue with the AOT compilation error thrown on a provider object, which uses HTTP error status codes, i.e. number, as property names.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by michabbb** [comment]
for me this problem still exists, when using an environment.ts like this:

```js
export const environment = {
  production: true,
  mapping: {
    1: 'de',
    2: 'de'
}
};
```
```diff
- ERROR in src/environments/environment.ts(4,5): Error during template compile of 'environment'
- Name expected.
```

```txt
Angular CLI: 8.1.0
Node: 10.16.0
OS: linux x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@angular/cdk                      8.1.1
@angular/material                 8.1.1
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
```

so is this really fixed or does this has anything to do with the `environment` ?? thanks.
