### ISSUE TITLE
angular 2 with asp.net

### ISSUE THREAD

**Issue by himanshuPawar1** [angular/angular-cli#9892]
how can i use angular 2 in existing asp.net project with backend as c# and i am using visual studio 2017.

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
