### ISSUE TITLE
npm err code EINTIGRITY

### ISSUE THREAD

**Issue by strongSoda** [angular/angular-cli#9893]
### Versions
```
Angular version 5
npm v = 5.6.0 , 5.7.1
node v= 9.7.1, 8.9.4, 8.10.0


###OS

windows 8


### Repro steps

npm install -g @angular/cli


### Observed behavior
```
the installation crashes with err code eintigrity and requires a different sha512...

### Mention any other details that might be useful (optional)

Tried

 npm cache clean --force

npm cache verify

npm link (reinstalling cli)

but no results.

Tried different versions of node and npm still no result

##please help someone

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
