### ISSUE TITLE
An issue with mixing Yarn and npm

### ISSUE THREAD

**Issue by yfain** [angular/angular-cli#9894]
I use Yarn for generating new projects (```ng set -g packageManager=yarn```). After generating a new project, I decided to install a package, but used npm:
```npm i @ngrx/store```

This installed the package, but replaced the content node_modules/@angular with an empty cli directory. 

If I use ```yarn add @ngrx/store```, the package is installed and the content of node_modules/@angular is preserved. 

Expected behavior: even if I use Yarn for project generation, I should be able to use npm without these side effects.

I use Angular CLI 1.7.2

**Comment by clydin** [comment]
This is an issue with the interaction of two different package managers and not something the CLI has control over.  Using two different package managers in the same project (regardless of Angular-CLI's presence) will generally lead to dependency issues.

**Comment by yfain** [comment]
This was not just dependency issues. Dependencies were removed and the cli directory was created.
