### ISSUE TITLE
Angular 2 cli first page load not send requests

### ISSUE THREAD

**Issue by Iv0Petr0v** [angular/angular-cli#9899]
Hello,

I have an interesting problem with angular cli.
 The following happens:
- User visits the site
- ADAL Authentication opens
- The User is successfully logged in and redirected to the dashboard
- But the browser does not send any requests to the server.
The problem is resolved when:
- The page is reloaded, everything is fine and works as expected.
- The user hit enter in the address bar, it is also ok.

What I've tried:
- Replace polyfills
- To remove polyfills
- To load them through the script tag, not through the bundle
- To remove AuthGuard
- To make it return true,
- Load components with Lazy Loading
- navigate using zone.js
- change the order of:
  imports: [
        HttpModule,
        BrowserModule, // as first
        FormsModule,
        BrowserAnimationsModule,
        AppRoutes,
        HttpClientModule, // as second

- To debug the code and see that it looks alright and passes through the Auth Interseptor and squeezes Auth Tokan as expected.
I did research for problems with ADAL, possible problems with angular 2 navigation, problem with lazy loading. Also updated the project to the latest version.
I found several articles with a similar problem, but without success.

I understand that most probably the problem is in my TV, not from angular but I hope for an idea how to fix my problem.
Unfortunately I cannot give a sample code.

I hope it is something simple that I just do not know. :)

Cheers!

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
