### ISSUE TITLE
Request project specific information in CONTRIBUTING.md

### ISSUE THREAD

**Issue by kylecordes** [angular/angular-cli#990]
CONTRIBUTING.md currently contains a good set of information, but other than a couple of pastes of the project name it is not specifically about Angular CLI. I would like to request some minor amount of project specific information be added, either in CONTRIBUTING or README.md. Potential contributors currently don't have quite enough context to contribute effectively, here are some things that would ideally be mentioned:
- How well should one know Ember CLI to be able to help?
- How well should one know Broccoli to be able to help?
- What kind of assistance is most wanted, now? Feature request? Bug reports? Simple PR's? Attempts to add major features? Or are there already too many cooks in the kitchen, will be best if the community just stepped back for a while?

A few sentences or bullet points in the contributing or readme file would help quite a bit.

**Comment by hansl** [comment]
Closing this as obsolete. CONTRIBUTING.md changed quite a bit since june.
