### ISSUE TITLE
Bundling with prod mode will case files to be named `-ngfactory.e3e2c005b77282947845.js`

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#9900]
### Versions
```

Angular CLI: 6.0.0-beta.4
Node: 8.9.1
OS: win32 x64
Angular: 6.0.0-beta.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 6.0.0-beta-0
@angular/cli: 6.0.0-beta.4
@angular/material: 6.0.0-beta-0
@angular-devkit/build-optimizer: 0.4.3
@angular-devkit/core: 0.4.3
@angular-devkit/schematics: 0.4.3
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.4
@schematics/angular: 0.4.3
@schematics/package-update: 0.4.3
typescript: 2.6.2
webpack-cli: 2.0.10
webpack: 4.0.1
```

### Repro steps
https://github.com/alan-agius4/ng-cli-issue-9900-bundle-name/tree/master/dist

* ng build --prod

### Observed behavior
Filename of of lazy module will be will be named with `ngfactory` example `betting-betting-module-ngfactory.e3e2c005b77282947845.js` when having  `namedChunks` set to true

```sh
chunk {0} betting-betting-module-ngfactory.75831e5a4d13dbbecde2.js (betting-betting-module-ngfactory) 948 bytes  [rendered]
chunk {1} runtime.bd60b09b0d2ab090f395.js, runtime.d41d8cd98f00b204e980.css (runtime) 1.85 kB [entry] [rendered]
chunk {2} styles.ac89bfdd6de82636b768.css (styles) 0 bytes [initial] [rendered]
chunk {3} polyfills.e8209731003adc2b9f02.js (polyfills) 59.1 kB [initial] [rendered]
chunk {4} main.0ecbca2d690e4432c54c.js, main.d41d8cd98f00b204e980.css (main) 381 kB [initial] [rendered]
i ｢wdm｣: Compiled successfully.
```

### Desired behavior
FIle part of `ng-factory` should be dropped.

**Comment by coryrylan** [comment]
With named chunks in prod mode the names seem to get pretty unpredictable example

`marketplace-marketplace-landing-marketplace-landing-module~search-search-module~subscriber-treasure-~4dc28e81.js`

This file references two different lazy loaded modules in the same name. We use the cli behind a proxy server so get the redirect rules on these files is a bit tricky.

**Comment by fouadchamoun** [comment]
> With named chunks in prod mode the names seem to get pretty unpredictable, example:
> 
> `marketplace-marketplace-landing-marketplace-landing-module~search-search-module~subscriber-treasure-~4dc28e81.js`
> 
> This file references three different lazy loaded modules in the same name. We use the cli behind a proxy server so getting the redirect rules on these files is tricky.

I'm still having this problem on the latest version. And my bundles don't have '.bundle' or '.chunk' parts in their name anymore.
