### ISSUE TITLE
[Feat] Allow multiple entry points (not multiple apps)

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular-cli#9905]
Currently, multiple entry points are fixed.

We have the **polyfills** entry point and then styles, common, main etc...

The only place we can add "stuff" to is polyfills and of course the main.

Can we allow users to add additional entry points pre/post the main?

I have a scenario where I want to check if the user is logged in (before angular loads).
I want to have minimal bytes downloaded so I want this file to load before polyfills.
I also want this module to be available to other modules later, e.g I want to know when I can bootstrap angular.

This  a small module the holds Open Identity client and some utilities to alter the UI before angular kicks in.

I could put it all in the index.html but this will be very hard to maintain and will force me to load the OIDC client twice...

I can also put it inside pollyfills but it will take much longer to load....

Thanks!

**Comment by gatimus** [comment]
Still a need for multiple entry points but you couldn't you use [APP_INITIALIZER](https://angular.io/api/core/APP_INITIALIZER) for the preboot stuff.

**Comment by alan-agius4** [comment]
Hi @shlomiassaf, thanks for this feature request. This however, is currently out of scope of the Angular CLI.

You can you a 3rd party builder to achieve this such as ngx-build-plus. Note: while we do allow extending and customising the build pipeline, this is not supported by the Angular tooling team.
