### ISSUE TITLE
main.bundle.js extremely slow only in my computer

### ISSUE THREAD

**Issue by eduardomagaldi** [angular/angular-cli#9907]
Hi,

I'm running a project and only in my computer it takes around 54 seconds for the page to stop loading after I save any file, and 44 seconds for me to see the page.

This doesn't happen in my colleague's computer.

Compilation is not that long, when using ```ng serve``` (no extra options) and saving file, it takes 7 seconds:

```
webpack: Compiling...
1934ms building modules
224ms sealing
1ms optimizing
2ms basic module optimization
478ms module optimization
140ms advanced module optimization
158ms basic chunk optimization
5ms chunk optimization
1ms advanced chunk optimization
1ms module and chunk tree optimization
1ms chunk modules optimization
1ms advanced chunk modules optimization
7ms module reviving
110ms module order optimization
60ms module id optimization
1ms chunk reviving
42ms chunk order optimization
93ms chunk id optimization
708ms hashing
19ms module assets processing
2ms chunk assets processing
47ms additional chunk assets processing
11ms recording
6ms additional asset processing
27ms chunk asset optimization
1933ms asset optimization
1166ms emitting
Hash: 6fc444179b1ef1a5a46a
Version: webpack 3.11.0
Time: 7197ms
                                         Asset     Size     Chunks                    Chunk Names
                              inline.bundle.js  3.85 kB     inline                    inline
  fontawesome-webfont.674f50d287a8c48dc19b.eot   166 kB
 fontawesome-webfont.fee66e712a8a08eef580.woff    98 kB
  fontawesome-webfont.b06871f281fee6b241d6.ttf   166 kB
  fontawesome-webfont.912ec66d7572ff821749.svg   444 kB                        [big]
fontawesome-webfont.af7ae505a9eed503f8b8.woff2  77.2 kB
                                main.bundle.js  2.93 MB       main             [big]  main
                           polyfills.bundle.js  1.47 MB  polyfills             [big]  polyfills
                              styles.bundle.js   726 kB     styles             [big]  styles
                              vendor.bundle.js  25.4 MB     vendor             [big]  vendor
                                    index.html  1.82 kB             [emitted]
chunk {inline} inline.bundle.js (inline) 0 bytes [entry]
chunk {main} main.bundle.js (main) 1.03 MB {vendor} [initial]
chunk {polyfills} polyfills.bundle.js (polyfills) 466 kB {inline} [initial]
chunk {styles} styles.bundle.js (styles) 261 kB {inline} [initial]
chunk {vendor} vendor.bundle.js (vendor) 8.81 MB [initial]
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  7.7 kB       0
    chunk    {0} index.html 1.63 kB [entry]
webpack: Compiled successfully.
```

### Versions
```
Angular CLI: 1.7.2
Node: 8.9.1
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.2.3
@angular/cli: 1.7.2
@angular/language-service: 4.4.6
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0
```

### Repro steps
* run ng serve
* save a file
* wait almost a minute to see the page

### Observed behavior

On network tab in developer tools I can see that main.bundle.js keeps pending for ages.

If I go to http://localhost:4200/main.bundle.js it takes 1 minute and 55 seconds to stop loading.

### Desired behavior
Should be much faster, around 2 seconds.

### Mention any other details that might be useful (optional)
I'm running it in a macbook air 8GB of memory, using windows 7 64 bits. The same behavior on my macbook air 4GB of memory using Mac OS.

I cannot find similar issues, can you help?

Thanks.

**Comment by cfremgen** [comment]
> it takes 7 seconds.

You said it yourself, building only takes 7 seconds. The remaining time is clearly outside of CLI's responsibility. 


> I'm running it in a macbook air 8GB of memory, using windows 7 64 bits. 

> The same behavior on my macbook air 4GB of memory using Mac OS.

These are old and weak machines. It's not a surprise it's slow.

**Comment by eduardomagaldi** [comment]
> The remaining time is clearly outside of CLI's responsibility.

CLI builds and serves right? If it's building fast and serving slow (takes 2 minutes to serve local 3MB, unacceptable), looks like CLI's reponsibility to me.

> These are old and weak machines. It's not a surprise it's slow.

Weird, everything else runs pretty good, other projects with gulp and even webpack. I don't think is a machine problem.

Thanks.

**Comment by cfremgen** [comment]
> CLI builds and serves right? If it's building fast and serving slow (takes 2 minutes to serve local 3MB, unacceptable), looks like CLI's reponsibility to me.

CLI uses webpack server underneath. 

I have similar issues with a slower computer. On my main pc (i7 3.7ghz), it reloads in < 5 seconds for a medium sized app (~3.5MB total package size).

What is your colleagues PC specs?

Also, I don't think you need @angular-devkit/build-optimizer: 0.3.2. CLI has build optimizer built in.

**Comment by eduardomagaldi** [comment]
My colleague's specs are macbook pro, 16GB memory, i7

Mine are macbook air, 8GB memory, i7 2 GHz, it's not that bad for this kind of build, is it?

> Also, I don't think you need @angular-devkit/build-optimizer: 0.3.2.

You don't think I need it? What do you mean?

Thanks.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
