### ISSUE TITLE
web public path is not working in .scss background image url

### ISSUE THREAD

**Issue by JackUnga** [angular/angular-cli#9908]
### Versions

Angular CLI: 1.7.3
Node: 8.10.0
OS: macOS High Sierra
Angular: 5.2.7

### Repro steps

In my pollyfils.ts file I have this code:
```
import '../web-config-code';
```
Inside web-config-code.ts I modify in runtime the web public path variable:
```
__webpack_require__.p = newUrlValue;
```
And I have in a .scss file this class:

```
.className {
    background: url(../../../dir1/dir2/images/imageName.jpg) no-repeat; 
}
```
The project compiles without any issue, the bundle files are using the newUrlValue assigned to __webpack_require__.p.
When is the turn to render the background image from the scss file, the url that is using is not the newUrlValue.

I was using @angular/cli version 1.6.7 and everything was working fine, now if I update to any other version 1.7.x, then the image error appears, if I rollback to version 1.6.7 everything is working great.

I tested using others versions of node, is not that I think.

Is something different in the way that urls are being compiled in this new versions? Something has changed with the way the web public path is used? What is the difference between versions?

**Comment by clydin** [comment]
The use of webpack is considered an internal implementation detail of the CLI.  Assuming that webpack is used or that files are processed by it will generally lead to an eventual breakage of the application.

For a case such as, changing the base HREF of the page would be a standardized method for adjusting the retrieval location of page resources.  This can be used in combination with the Angular `APP_BASE_HREF` token ([doc](https://angular.io/api/common/APP_BASE_HREF)) if the Angular routing root would be different than the modified base HREF.

**Comment by JackUnga** [comment]
@clydin  I'm not quite sure of understand your answer. But can you help to understand at least why the above code that I'm using works just fine with @angular/cli 1.6.7 and webpack 3.10.0 but is not working if I only update to angular/cli 1.7.2 for example? btw, the version of webpack now is 3.11.0
