### ISSUE TITLE
has no exported member using @angularcli1.6.5

### ISSUE THREAD

**Issue by kashifghaffarasim** [angular/angular-cli#9919]
### Versions
```
<!--
Angular CLI: 1.6.5
Node: 9.5.0
OS: linux x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

Faced the following issues:
ERROR in src/app/home/home.component.ts(5,10): error TS2305: Module '"/home/kashif/projects/angularprojects/kidpull/kidjoTvApp/src/app/shared/services/RefreshWeb/index"' has no exported member 'RefreshWebService'.
src/app/shared/entities/index.ts(8,15): error TS2307: Cannot find module './Addfav'.
src/app/shared/entities/index.ts(10,15): error TS2307: Cannot find module './RefreshWeb'.
src/app/shared/services/RefreshWeb/index.ts(1,15): error TS2307: Cannot find module './RefreshWeb.service'.
src/app/shared/services/RefreshWeb/refreshweb.service.ts(6,10): error TS2305: Module '"/home/kashif/projects/angularprojects/kidpull/kidjoTvApp/src/app/shared/entities/index"' has no exported member 'Refresh'.
src/app/shared/services/RestService/rest-connector.service.ts(5,32): error TS2307: Cannot find module '../blockui/index'.
src/app/shared/services/RestService/rest-connector.service.ts(6,25): error TS2305: Module '"/home/kashif/projects/angularprojects/kidpull/kidjoTvApp/src/app/shared/entities/index"' has no exported member 'Refresh'.
src/app/shared/services/favoritesService/favorites.service.ts(4,10): error TS2305: Module '"/home/kashif/projects/angularprojects/kidpull/kidjoTvApp/src/app/shared/entities/index"' has no exported member 'AddFav'.
src/app/shared/shared.module.ts(4,32): error TS2307: Cannot find module './services/blockui/index'.
src/app/shared/shared.module.ts(6,10): error TS2305: Module '"/home/kashif/projects/angularprojects/kidpull/kidjoTvApp/src/app/shared/services/RefreshWeb/index"' has no exported member 'RefreshWebService'.
src/app/video-selection/video-selection.component.ts(7,10): error TS2305: Module '"/home/kashif/projects/angularprojects/kidpull/kidjoTvApp/src/app/shared/entities/index"' has no exported member 'AddFav'.


ng s or npm start not working

**Comment by Brocco** [comment]
Unfortunately there's not a whole lot we can do at this point, please provide some more information regarding your application, and the steps it takes to get to this error.

**Comment by kashifghaffarasim** [comment]
@Brocco 
I followed the following step:
1: npm install -g @angular/cli
2: npm install 
3: npm start 
After 3rd step i got 
RROR in src/app/home/home.component.ts(5,10): error TS2305: Module '"/home/kashif/projects/angularprojects/kidpull/kidjoTvApp/src/app/shared/services/RefreshWeb/index"' has no exported member 'RefreshWebService'.
src/app/shared/entities/index.ts(8,15): error TS2307: Cannot find module './Addfav'.

Even files are exist in angular project path.

**Comment by kashifghaffarasim** [comment]
Home Component Ts
import { Component, OnInit, HostListener, ViewChild, ElementRef } from '@angular/core';
import { Router } from '@angular/router';
import { Input } from '@angular/core';
import { Ng4LoadingSpinnerService } from 'ng4-loading-spinner';
import { RefreshWebService } from './../shared/services/RefreshWeb/index';
import { TimerService } from './../shared/services/TimerService';
import { Card } from './../shared/entities/index';
import { NgxCarousel } from 'ngx-carousel';
declare var $: any;
import { Observable } from 'rxjs/Observable'
import 'rxjs/add/observable/timer'
import 'rxjs/add/operator/map'
import 'rxjs/add/operator/take'



export enum KEY_CODE {
  RIGHT_ARROW = 39,
  LEFT_ARROW = 37,
  Enter = 13,
  Up_key = 38,
  Down_key = 40
}

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {
  countDown;
  @ViewChild('setting') mySettingsBtn: ElementRef;
  @ViewChild('favorite') myFavBtn: ElementRef;
  @ViewChild('previous') myLeft: ElementRef;
  @ViewChild('next') myRight: ElementRef;
  @ViewChild('slider') slider: ElementRef;
  videoImageUrl: any;
  currentSlide: any;
  deviceId: string;
  kidId: string;
  activeSubscription: boolean;
  obj = new Object();
  public innerheigth: any;
  ImageUrl: string;
  cards: any[] = [];
  folders: any[] = [];
  bucketName: any;
  videoUrl: string;
  time: any;
  arrayIndex: any = 0;
  downCount = 0;
  upCount = 0;
  Favcolor: any = 0;
  settingsColor: any = 0;
  walkThrough: any = false;
  settingsUpCount: any = 0;
  public carouselTile: NgxCarousel;
  FavIndex: any = 0;

  waterpx: any = "100";
  waterPxCountdown: any = "100px";
  initialTime = localStorage.getItem('screenTimeLimit').match(/\d+/g).map(Number);
  UnitOfTIme = 100 / this.initialTime[0];

  constructor(public refreshweb: RefreshWebService,
    public router: Router,
    public timerService: TimerService,
    private spinnerService: Ng4LoadingSpinnerService) {
    this.refreshWeb();
    this.timerService.getCountdownTimer().subscribe(data => {
      this.countDown = data;
      this.waterpx = this.waterpx - this.UnitOfTIme;
      this.waterPxCountdown = this.waterpx + "px";
    });
  }

  @HostListener('window:keyup', ['$event'])
  keyEvent(event: KeyboardEvent) {

    if (event.keyCode === KEY_CODE.RIGHT_ARROW) {
      this.GoRight();
    }

    if (event.keyCode === KEY_CODE.LEFT_ARROW) {
      this.GoLeft();
    }
    if (event.keyCode === KEY_CODE.Up_key) {
      this.GoUp();
    }
    if (event.keyCode === KEY_CODE.Down_key) {
      this.GoDown();

    }
    if (event.keyCode === KEY_CODE.Enter) {

      var folder = this.folders[this.arrayIndex];
      this.goToVideoPage(folder[0].id, folder[0].imgUrl, folder[0].color);

    }

  }
  onmoveFn(data) {
    this.currentSlide = data.currentSlide;
  }
  GoDown() {
    if (this.downCount < 3) {
      this.downCount++;
    }
    // on key down when very first time u enter in the home page
    if (this.downCount == 1 && this.arrayIndex == 0 && this.Favcolor == 0) {
      this.mySettingsBtn.nativeElement.focus();
      this.settingsColor = 1;
      this.arrayIndex = 645734;
      this.downCount = 0;
    }
    // on key down after u move slider
    if (this.downCount == 1 && this.arrayIndex == this.currentSlide && this.Favcolor == 0) {
      this.mySettingsBtn.nativeElement.focus();
      this.settingsColor = 1;
      this.arrayIndex = 645734;
      this.downCount = 0;
      this.settingsUpCount = 1;
    }
    //when u enter in the settings page
    if (this.downCount == 1 && this.settingsColor == 1) {
      this.goToSettingsPage();
      this.settingsColor = 0;
    }
    //on key down when u move from favourite button to slider first index
    if (this.downCount == 1 && this.Favcolor == 1) {
      this.myLeft.nativeElement.focus();
      this.arrayIndex = 0;
      this.settingsColor = 0;
      this.Favcolor = 0;
      this.downCount = 0;
    }
    //on key down when u move from favourite button to slider current index
    if (this.downCount == 1 && this.Favcolor == 1 && this.FavIndex == 1) {
      this.myLeft.nativeElement.focus();
      this.arrayIndex = this.currentSlide;
      this.settingsColor = 0;
      this.Favcolor = 0;
      this.downCount = 0;
    }
  }
  GoUp() {
    if (this.upCount < 3) {
      this.upCount++;
    }
    //onkey up focus on slider first index
    if (this.upCount == 1 && this.settingsColor == 1) {
      this.myLeft.nativeElement.focus();
      this.arrayIndex = 0;
      this.settingsColor = 0;
      this.upCount = 0;

    }
    //on keyup focus on Favourite button
    if (this.upCount == 1 && this.arrayIndex == 0) {
      this.myFavBtn.nativeElement.focus();
      this.Favcolor = 1;
      this.arrayIndex = 6337484;
      this.upCount = 0
    }
    //on keyup focus on Favourite button
    if (this.upCount == 1 && this.arrayIndex == this.currentSlide) {
      this.myFavBtn.nativeElement.focus();
      this.Favcolor = 1;
      this.FavIndex = 1;
      this.arrayIndex = 6337484;
      this.upCount = 0;
    }
    //on keyup from first index to focus on favourite button
    if (this.upCount == 1 && this.Favcolor == 1) {
      this.goToFavPage();
      this.Favcolor = 0;
      this.arrayIndex = 6337484;

    }
    if (this.upCount == 1 && this.settingsUpCount == 1) {
      this.myLeft.nativeElement.focus();
      this.arrayIndex = this.currentSlide;
      this.settingsColor = 0;
      this.upCount = 0;
    }
  }
  GoLeft() {
    --this.arrayIndex;
    if (this.arrayIndex == -1) {
      this.arrayIndex = 0;
    }
  }
  GoRight() {
    ++this.arrayIndex;
    if (this.arrayIndex == this.folders.length) {
      this.arrayIndex = 0;
    }
  }
  ngOnInit() {

    this.GetCard();
    this.time = localStorage.getItem('screenTimeLimit');
    this.carouselTile = {
      grid: { xs: 3, sm: 3, md: 4, lg: 5, all: 0 },
      slide: 1,
      speed: 400,
      loop: true,
      animation: 'lazy',
      point: {
        visible: true,
        pointStyles: `
        .ngxcarouselPoint {
          display: none;
        }
       .ngxcarousel-inner {
        height: 360px;
        width: 108%;
         }
       .ngx-tile.item {
        width:80%;
       }
        .tile {
        width: 60%;
        border-radius: 18px;
        transform: scale(1);
       }
      .ngxcarousel-items {
      top: 53px;
      left:8%;
       }
         @media (min-width: 992px){
              .ngxcarouselxUMiWG > .ngxcarousel > .ngxcarousel-inner > .ngxcarousel-items > .item {
                   width: 31% !important;
              }
  
          }
        `
      },
      load: 2,
      touch: true,
      easing: 'ease'
    }

  }
  refreshWeb() {
    this.deviceId = localStorage.getItem('X-Kidjo-DeviceId');
    if (!this.deviceId) {
      this.refreshweb.RefreshWeb().subscribe(data => {
        this.walkThrough = true;
        this.ImageUrl = data.folderImageUrl;
        this.videoUrl = data.videoUrl;
        this.videoImageUrl = data.videoImageUrl;
        localStorage.setItem('videoImageUrl', this.videoImageUrl);
        localStorage.setItem('videoUrl', this.videoUrl)
        localStorage.setItem('folderImageUrl', this.ImageUrl);
        localStorage.setItem('X-Kidjo-DeviceId', data.deviceId);
        this.kidId = data.kids[0].id;
        localStorage.setItem('kidId', this.kidId);
        this.activeSubscription = data.User[0].activeSubscription;
      })
    }
    if (this.activeSubscription == true) {
      localStorage.setItem('premiumActive', 'true');
    } else {
      localStorage.setItem('premiumActive', 'false');
    }
  }
  GetCard() {
    this.obj = localStorage.getItem('kidId');
    this.obj = localStorage.getItem('premiumActive');
    this.spinnerService.show();
    this.refreshweb.GetCard(this.obj).subscribe(data => {
      this.spinnerService.hide();
      this.cards = data.cards;
      var tempData = [];
      var test = [];
      var color: any[] = ['red', 'yellow', 'blue', 'green', 'orange', 'prple'];
      var backgroundImages: any[] = ['/assets/svgs/red-img.svg', '/assets/svgs/yellow-img.svg', '/assets/svgs/blue-img.svg', '/assets/svgs/green-img.svg', '/assets/svgs/orange-img.svg', '/assets/svgs/purple-img.svg'];
      var counter = 0;
      for (var index = 0; index < this.cards.length; index++) {
        if (counter == 6) {
          counter = 0;
        }
        if (this.cards[index].id) {
          test = [{ 'id': this.cards[index].id, 'back-color': color[counter], 'color': backgroundImages[counter], 'imgUrl': this.folderImage(this.cards[index].id) }]
          tempData.push(test);
          // increment counter
          counter++;
        }
      }
      this.folders = tempData;
    },
      Error => {
        this.spinnerService.hide();
      });
  }

 
  showWalkthrough() {
    this.walkThrough = true;
  }

}




and Refresh Web Service
export * from './RefreshWeb.service';
import { Injectable } from '@angular/core';
import { Http, Response } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import { Headers, RequestOptions } from '@angular/http';
import { RESTConnectorService } from './../RestService/index';
import { Refresh, Card } from './../../entities/index';




@Injectable()
export class RefreshWebService {
 d = new Date();
}

**Comment by mhosman** [comment]
Same problem here since last beta (6.0.0 beta 6). Example:

```
node_modules/@angular/flex-layout/typings/media-query/server-match-media.d.ts(2,10): error TS2305: Module '"c:/myproject/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/@angular/flex-layout/typings/media-query/server-match-media.d.ts(5,10): error TS2305: Module '"c:/myproject/node_modules/rxjs/Observable"' has no exported member 'Observable'.
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
