### ISSUE TITLE
404 when manually changing URL in browser to defined router route

### ISSUE THREAD

**Issue by MarouaneSH** [angular/angular-cli#9922]
When i try to navigate manually to a defined route it show this error : 

> Not Found
> The requested URL /About was not found on this server.

All routes works fine in local server using "ng serve" , this happening only when i deploy my apps to another server using "ng build".

**Comment by actra-gschuster** [comment]
That's a problem with your servers configuration, when using Apache you'll have to redirect 404 requests to your index.html by using mod_rewrite.

**Comment by Brocco** [comment]
@actra-gschuster is correct, this is an issue with the server you're deploying to, not an issue with the CLI.
