### ISSUE TITLE
Explanation about CLI code Structure.

### ISSUE THREAD

**Issue by PardeepJain** [angular/angular-cli#993]
After the Release of angular CLI, I have decided to work with angular CLI but from very start
leads to some confusion which are not cleared yet so hope somewhere here help me out :-

1. In `index.html` i have found some amazing interpolation syntax of angular, whats the role of these in our app ?

syntax like - 

    {{#unless environment.production}}
    {{/unless}}
    {{#each scripts.polyfills}}
    <script src="{{.}}"></script>{{/each}}    //what is {{.}} here ??

    what does `/` this mean in {{/unless}}
    and here `#` in the {{#each ...}} ??

  
2. when i run command `ng g component demo`, it creates component in perfact manner but after creating found one file
named `index.ts` for every component, whats the role of `index.ts` here ?

3. Before CLI i have use `gulp` task's to perform compilation(*.ts to *.js) , In CLI how and where these action being performed ?? 

4. whats the role of `angular-cli.json` file ?

any help would be appericiated, thanks.

I have also ask same question on stackoverflow but did't get much attension here 
http://stackoverflow.com/q/37588579/5043867

**Comment by filipesilva** [comment]
Hi @PardeepJain, most (if not all) of the folder structure inside `src/` is explained in the [Style Guide](https://angular.io/docs/ts/latest/guide/style-guide.html), and the CLI simple adheres to it.

`index.html` does have custom stuff, and we don't explain a lot about it but we should. I'll have a try at a README update going through the folder structure in detail.

**Comment by PardeepJain** [comment]
Yesh sure @filipesilva but as mention in question 

{{#unless environment.production}}
{{/unless}}
{{#each scripts.polyfills}}
<script src="{{.}}"></script>{{/each}}    //what is {{.}} here ??

what does `/` this mean in {{/unless}}
and here `#` in the {{#each ...}} ??

what is this {{.}} , {{#.. , and {{/ .. means is this some another language ? please update readme file ASAP.

**Comment by filipesilva** [comment]
Those are used internally to add in polyfill scripts and trigger prod mode changes. Overall index.html shouldn't be changed much by the user - importing libraries and such should be done in `system-config.js`.

**Comment by PardeepJain** [comment]
yeah exactly i want to know how internally, i mean by using which language the code it written?? is {{#.. and so on is of angular's syntax or from some another language ? also if i have to add some external libraries i only have to add to system.config.js instead of index.html ?

**Comment by siva636** [comment]
Simplicity is broken with Angular-cli, it is a complicated irritating wired tool. There are so many config files there!!??

We should be able to configure development or production state when bootstraping in the main.ts file using a single line of code.

**Comment by PardeepJain** [comment]
Exactly well said @siva636 there are too many config files which leads to confusion which files play which role in project !
no doubt angular cli is provided by angular2 team so it is benifitial for us specially for frehsers, but they should provide better documentation for normal users isn't it ?

**Comment by kylecordes** [comment]
@PardeepJain The template syntax you are seeing is most definitely not part of angular. I don't know exactly what language it is, but I believe this aspect is simply brought over from Ember CLI. I believe that file should be considered a black box as @filipesilva said; I don't know whether the CLI team is even committed to keeping those aspects the same from version to version. I suspect they need all the flexibility they can get to change tooling behind the scenes to get excellent out of the box results.

**Comment by dheerajkysetti** [comment]
@siva636 so true. I could relate to this google IO 2016 presentation. 
https://youtu.be/sGsA7oKoQhI?t=7m43s

**Comment by filipesilva** [comment]
@PardeepJain @siva636 @dheerajkysetti at the moment documentation is a much lower priority than development, and most documentation covers only what is strictly necessary to use the tool at this stage.

@kylecordes covered a good few reasons for why some parts of the CLI are very much a black box at the moment.

I'd also like to remind you of the note in the readme: https://github.com/angular/angular-cli#note

> Note
>
> This project is very much still a work in progress.

Once the project is out of beta you can definitely expect better documentation for both usage and architecture.

**Comment by JohnL4** [comment]
I suspect that's a dependency on something like Handlebars or HTMLBars used by ember-cli. [This stackoverflow answer](http://stackoverflow.com/a/38676198/370611) assures me not to worry. :)

See also http://handlebarsjs.com/block_helpers.html
