### ISSUE TITLE
ERROR in node_modules/rxjs/Observable.d.ts(25,1)  Please anyone help me

### ISSUE THREAD

**Issue by ragulan28** [angular/angular-cli#9930]
### Versions
```
Angular CLI: 1.7.2
Node: 8.9.4
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

```

### Repro steps

* ng serve

### Observed behavior
```
ERROR in node_modules/rxjs/Observable.d.ts(25,1): error TS1005: ',' expected.
node_modules/rxjs/Observable.d.ts(27,2): error TS1005: ';' expected.
node_modules/rxjs/Observable.d.ts(40,1): error TS1005: ',' expected.
node_modules/rxjs/Observable.d.ts(42,2): error TS1005: ';' expected.
node_modules/rxjs/Observable.d.ts(51,1): error TS1005: ',' expected.
node_modules/rxjs/Observable.d.ts(53,2): error TS1005: ';' expected.
node_modules/rxjs/Observable.d.ts(58,6): error TS1005: ';' expected.

```

**Comment by Brocco** [comment]
Please include steps to reproduce this issue or provide a link to a repo that has this issue.

**Comment by ragulan28** [comment]
I just open the angular project directory and run the ng serve command

**Comment by alan-agius4** [comment]
#
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
