### ISSUE TITLE
Provide new parameter "--http" to "ng new" command

### ISSUE THREAD

**Issue by ultrasonicsoft** [angular/angular-cli#9934]
What would like to see implemented?
- I would like to implement/have feature to provide a new parameter called "--http" to "ng new" command which shall create a new Angular project with Http boilerplate code.

What is the usecase?
- When user creates a new project using command say - "ng new <project-name> --http", it shall create a new project with HttpClient boilerplate code

What did you expect to see?
New project shall have
- HttpClientModule imported inside AppModule (Root)
- DataService or HttpService service class created with HttpClient injected in constructor
- AppComponent's constructor shall have DataService/HttpService injected in constructor
- DataService/HttpService class can have example methods for HTTP GET/PUT/POST/DELETE API calls in commented or some example REST API.

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this and in some cases it might be useful. On the same time we should be careful how we increase the scope of the CLI because each new feature means new code to maintain and fix issues in.

Let's reopen if more folks need such functionality.
