### ISSUE TITLE
6.0.0-beta.5 Regression problem with --app (index) use case.

### ISSUE THREAD

**Issue by leo6104** [angular/angular-cli#9935]
### Versions
```
@angular/cdk: 6.0.0-beta.4
@angular/cli: 6.0.0-beta.5
@angular/material: 6.0.0-beta.4
@angular-devkit/build-optimizer: 0.4.5
@angular-devkit/core: 0.4.5
@angular-devkit/schematics: 0.4.5
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.5
@schematics/angular: 0.4.5
@schematics/package-update: 0.4.5
typescript: 2.6.2
webpack-cli: 2.0.11
webpack: 4.0.1
node: 8.9.3
npm: 5.7.1
```

### Repro steps

* define multiple app in "apps" in .angular-cli.json 
* ng serve --app 1

### Observed behavior
```
nameOrIndex.match is not a function
TypeError: nameOrIndex.match is not a function
    at Object.getAppFromConfig (xxx/node_modules/@angular/cli/utilities/app-utils.js:13:25)
    at Class.run (xxx/node_modules/@angular/cli/tasks/serve.js:52:39)
    at ServeCommand.<anonymous> (xxx/node_modules/@angular/cli/commands/serve.js:135:32)
    at Generator.next (<anonymous>)
    at fulfilled (xxx/node_modules/@angular/cli/commands/serve.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Desired behavior

nameOrIndex should consider number type. 

### Mention any other details that might be useful (optional)
There is no problem with 6.0.0-beta.4.
In 6.0.0-beta.5, there is no problem if the index is 0 (zero). 
--app 0 works but --app 1 not works. 
ng serve, build command throw above error.

**Comment by leo6104** [comment]
Before this issue resolved, temporary solution is `using --app option with specify app name (ex, ng serve --app pc)`

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
