### ISSUE TITLE
ng command no longer works

### ISSUE THREAD

**Issue by crashspringfield** [angular/angular-cli#9936]
### Versions
```
Linux Mint 17.3
Node 9.5.0
NPM 5.6.0
```

### Repro steps
* ng new myproject

### Observed behavior
```
The program 'ng' is currently not installed. You can install it by typing:
sudo apt-get install ng-common
```

### Mention any other details that might be useful (optional)
I found a few other open and closed related issues on here and tried the suggested solutions. I've uninstalled angular/cli globally, cleared my NPM cache, deleted my node_modules directory, and tried reinstalling, but nothing works.

What's strange is that the command used to work. I haven't used angular in a few months, and the only thing that has changed on my system since then is the Node version (I'm using NVM, but even reverting back to older versions did not resolve the issue).

**Comment by bleuscyther** [comment]
have you tried downgrading from npm@5.6.0 to npm@5.5.1

**Comment by crashspringfield** [comment]
I think I figured it out. For some reason adding `~/.nvm/versions/node/v9.8.0/lib/node_modules/@angular` to my path didn't work. I had to add `~/.nvm/versions/node/v9.8.0/bin/ng` to my path to access the angular-cli.
