### ISSUE TITLE
FEATURE REQUEST: generate new cli-project from some pre-defined project template 

### ISSUE THREAD

**Issue by nmorado** [angular/angular-cli#9937]
### Versions
N/A

### Repro steps

N/A

### Observed behavior
N/A

### Desired behavior
It would be great to have a feature to generate an angular project based off cli patterned after some known angular project template.

A project template may include - external dependencies, initial project files among others.

This is useful when you want to distribute your angular project as patterns across multiple teams and wanted to avoid cut and pasting.

example:

ng generate my-project using <some-pointer-to-a-project-template-somewhere>

**Comment by Brocco** [comment]
This is already possible, please refer to this [blog post](https://blog.angular.io/schematics-an-introduction-dc1dfbc2a2b2) for more information.
