### ISSUE TITLE
Another 90% chuck optimization issue with LazyLoad

### ISSUE THREAD

**Issue by tonogueira2** [angular/angular-cli#9938]
I found some other topics talking about chuck optization, but none had the versions as recent as my project.

I am using a project with dependencies all updated, and I have the same problem of people with CLI 1.0 ...

It turns out that I added in my project lazyload routes, and no solution on similar topics were satisfactory, the problem continues.

I realized that the problem was when I added the lazyload, my project has 534+ modules with 233+ components.

this is the initial structure of the project.

this need for modules is for the project to have separated each area of ​​the system so it can work more dynamically and independently.

when I comment the main routes (forRoot) the application returns to normal, as I add the (forRoot) and consequently it after the forChild, the problem appears.

every single rename of an icon, it takes about 112000ms

My application takes some time always in 76% sealing and basic chunk optimization and then in 90% chunk optimization

### Versions
```
NPM: 5.7.1
Angular CLI: 1.7.1
Node: 6.10.3
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.3
@angular/cli: 1.7.1
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
-->
```

### Repro steps

here is an example of my route ...

RouterModule.forRoot(routes)
(...
  
  { path: 'namemodule', loadChildren: 'path/path1/path2/namemodule.module#NamemoduleModule', data: { id: 'namemodule', caminho: 'namemodule', descricao: 'Namemodule', icon: 'fa-chart-line', filhos: {} }  },

...) OBS: I have other more 9 routes here...

RouterModule.forChild(routes) OBS: Child of 'namemodule'

(...
	{path:'', component: NamemoduleComponent},
	{path:'nameChildmodule', loadChildren: 'path/path1/path2/path3/nameChildmodule.module#NameChildmoduleModule'}
	
...) OBS: I have other more 16 routes here of children of module 'Namemodule'...

and Child of Child

RouterModule.forChild(routes) OBS: Child of 'nameChildmodule'

(...
	{path:'', component: NameChildmodule},
	{path:'nameChilOfChilddmodule', loadChildren: 'path/path1/path2/path3/path4/nameChilOfChilddmodule.module#NameChilOfChilddmoduleModule'}
	
...) OBS: I have other more 4 routes here of child of module 'nameChilOfChilddmodule'...

but as I said this is the initial structure route, from here, we will have in our project more modules, component and consequently broken children of these children

now comes the question,

in terms of the Angular proposal, we should modularize the application, as our project is very large and I had this problem already in the beginning.

I ask your help to direct me, if the problem is really in the CLI, Webpack or in the form that I am programming?

If it's in the way I'm doing the routes ... what would be the best option?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
