### ISSUE TITLE
Feature Request: Allow global CLI to be used for builds

### ISSUE THREAD

**Issue by Arlen22** [angular/angular-cli#9940]
I am the type of person that starts many Angular projects. However, I started realizing that generating 25,000 files for every little idea that came across my mind can result in a few problems. I tried doing a project with only the production dependencies installed, but angular-cli said it could not find a local version of a couple modules installed. One was typescript, and I forget the other one. Is there a way to force the CLI to use the globally installed angular-cli for the build process so the project dependancies would be in the local `node_modules`, and angular-cli would use its own dependancies for the rest?

This is so important to me that I am starting to switch back to AngularJS, although I would much rather prefer AngularIO.

**Comment by alan-agius4** [comment]
Hi @Arlen22, 

Thanks for this feature request. However, correctly this is not in the Angular CLI roadmap.
