### ISSUE TITLE
Question : How to import statements dynamically in any ts file, especially in Routing or Module file 

### ISSUE THREAD

**Issue by vittal288** [angular/angular-cli#9941]
I know this below question has to be log in other forums like stackoverflow and other but still I am posting here because this is related to CLI and webapck related .

I have to load a component which has the same name called "MyComponent" but located in different folders physically(and the name of the component is "MyComponent) which has different behavior in each folder) and MyComponent component has to load based on the options which user selects in his previous screens ....

Suppose MyComponent is located in following folders 

OPTION ONE 

..**path1/path2/path3/my-component/my-component.component**    and this component have to refer to my routing module import statement as shown below and path1,path2, and path2 are some dynamic values which user will select in his previous screens.

`import {MyComponent } from "..path1/path2/path3/my-component/my-component.component" `

NOTE: I am keeping the options which user select in his configuration screens as the same name to the folder name to ease my import statements.

OPTION TWO 

**..path4/path5/path6/my-component/my-component.component**    and this component has to refer in my routing module import statement as shown below and path4,path5, and path6 are some dynamic values which user will select in his previous screens.

and import statement will look like below 

`import {MyComponent } from "..path4/path5/path5/my-component/my-component.component"`

since MyComponent is referred in my declaration array of RoutinModule but if you import above two components in one short compiler will throw an error that MyComponent is already imported,  so I have to import those import statement very dynamically based on user's selections.

Hope you understand my problem statement ...

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
