### ISSUE TITLE
--skip-commit option doesn't exist anymore

### ISSUE THREAD

**Issue by fetis** [angular/angular-cli#9944]
### Versions
```
Angular CLI: 1.7.3
Node: 8.9.4
OS: darwin x64
```

### Repro steps

* ng new -d -sc test-app

### Observed behavior
```
➜ ng new -d -sc test-app
The option '--sc' is not registered with the new command. Run `ng new --help` for a list of supported options.
```

### Desired behavior

According to https://github.com/angular/angular-cli/wiki/new this option should skip commit step

This option is also missed in `ng new --help` output

**Comment by clydin** [comment]
Version 1.7.3 is no longer actively supported and the `-sc` alias no longer present in the latest version.
