### ISSUE TITLE
Feature Request: Apply defaults to schematics when called with externalSchematic

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/angular-cli#9947]
The custom schematics I've been creating work by using externalSchematic to call the @schmatics/angular module & component schematics.  I then add my additional changes on top of them.  

The problem is, when called this way, they don't have the defaults stored in .angular-cli.json (changeDetection, etc).

I was wondering if it would make sense to move [prepOptions](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/tasks/schematic-run.ts#L81) from the schematic run task into an options transform on the [EngineHost](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/utilities/schematics.ts#L48).

**Comment by clydin** [comment]
The Angular CLI should now apply defaults in this situation.  If this issue is still occurring, please let us know.
