### ISSUE TITLE
routing does not work on GitHub Pages

### ISSUE THREAD

**Issue by kutyel** [angular/angular-cli#995]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
`any`
2. Versions. Please run `ng --version`. If there's nothing outputted, please run in a Terminal: 
`any`
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
**The app was fully created with the angular-cli**
4. The log given by the failure. Normally this include a stack trace and some
   more information.
**Error 404**
5. Mention any other details that might be useful.
**I have an Angular 2 App deployed via GitHub Pages** (using the CLI) [here](https://kutyel.github.io/famous-painters), whether you refresh the page or navigate using deep linking it does not work and an *Error 404* from GitHub is given. I have used the CLI to generate the *routes* and used the *new* router *(not the `router-deprecated`)*.

**Comment by filipesilva** [comment]
I'll pick this up. There is a solution in https://github.com/angular/angular-cli/issues/41#issuecomment-208456482 but I haven't implemented it yet.

**Comment by kutyel** [comment]
@filipesilva that solves the weird Github 404 Issue, but it does not fix deep linking, like when navigating to https://kutyel.github.io/famous-painters/painter/3, for example. I bet there is something missing...

**Comment by filipesilva** [comment]
@kutyel perhaps the missing bit now is related to https://github.com/angular/angular-cli/issues/989#issuecomment-224171440?

**Comment by kutyel** [comment]
@filipesilva you are right, I will keep track of the changes made to the new router, thanks! 👍
