### ISSUE TITLE
Ng command how to indent 4 Spaces by default?

### ISSUE THREAD

**Issue by chengqwerty** [angular/angular-cli#9953]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by Brocco** [comment]
You would need to write a custom schematic, you can read more [here](https://blog.angular.io/schematics-an-introduction-dc1dfbc2a2b2).

**Comment by antch** [comment]
That's... kind of insane.

**Comment by samterainsights** [comment]
Unreal... Why is this issue closed? How about add a simple flag to control the indentation instead of being _enterprise_ developers and making everyone write tons of boilerplate to accomplish what should be a straightforward task.
