### ISSUE TITLE
"WARNING in Circular dependency detected" - when using barrel module with typescript path mapping.

### ISSUE THREAD

**Issue by ph55** [angular/angular-cli#9955]
When using typescript's path mapping with angular barrel modules, angular cli treats some imports as circular dependencies when, in fact they are not. 

### Versions
```
Angular CLI: 1.7.3
Node: 8.9.4
OS: win32 x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps
* Import class of same MODULE by path mapping.
https://github.com/ph55/ng-circular-example
![image](https://user-images.githubusercontent.com/1386622/37337741-e7c40cf6-26bd-11e8-9ef8-a54dcfcc0de3.png)
```
WARNING in Circular dependency detected:
src\app\libs\bye\index.ts -> src\app\libs\bye\src\bye.module.ts -> src\app\libs\bye\src\bye.component.ts -> src\app\libs\bye\index.ts

WARNING in Circular dependency detected:
src\app\libs\bye\src\bye.component.ts -> src\app\libs\bye\index.ts -> src\app\libs\bye\src\bye.module.ts -> src\app\libs\bye\src\bye.component.ts

WARNING in Circular dependency detected:
src\app\libs\bye\src\bye.module.ts -> src\app\libs\bye\src\bye.component.ts -> src\app\libs\bye\index.ts -> src\app\libs\bye\src\bye.module.ts
```

* Import class of MODULE that is part of imports of your current NgModule
https://github.com/ph55/ng-circular-example/tree/case-2
![image](https://user-images.githubusercontent.com/1386622/37337873-47b83ed4-26be-11e8-847a-b9224b0e9863.png)
![image](https://user-images.githubusercontent.com/1386622/37337896-59376716-26be-11e8-9830-81f24752688a.png)
```
WARNING in Circular dependency detected:
src\app\libs\bye\index.ts -> src\app\libs\bye\src\bye.module.ts -> src\app\libs\bye\src\bye.component.ts -> src\app\libs\hello\index.ts -> src\app\libs\hello\src\hello.module.ts -> src\app\libs\bye\index.ts

WARNING in Circular dependency detected:
src\app\libs\bye\src\bye.component.ts -> src\app\libs\hello\index.ts -> src\app\libs\hello\src\hello.module.ts -> src\app\libs\bye\index.ts -> src\app\libs\bye\src\bye.module.ts -> src\app\libs\bye\src\bye.component.ts

WARNING in Circular dependency detected:
src\app\libs\bye\src\bye.module.ts -> src\app\libs\bye\src\bye.component.ts -> src\app\libs\hello\index.ts -> src\app\libs\hello\src\hello.module.ts -> src\app\libs\bye\index.ts -> src\app\libs\bye\src\bye.module.ts

WARNING in Circular dependency detected:
src\app\libs\hello\index.ts -> src\app\libs\hello\src\hello.module.ts -> src\app\libs\bye\index.ts -> src\app\libs\bye\src\bye.module.ts -> src\app\libs\bye\src\bye.component.ts -> src\app\libs\hello\index.ts

WARNING in Circular dependency detected:
src\app\libs\hello\src\hello.module.ts -> src\app\libs\bye\index.ts -> src\app\libs\bye\src\bye.module.ts -> src\app\libs\bye\src\bye.component.ts -> src\app\libs\hello\index.ts -> src\app\libs\hello\src\hello.module.ts
```

**Comment by moncefbouazzaoui** [comment]
Try to add the settings below to your .angular-cli.json, this worked for me :)
```
"defaults": {
    ...
    "build": {
      "showCircularDependencies": false
    }
  }
```

**Comment by ph55** [comment]
> Try to add the settings below to your .angular-cli.json, this worked for me

Sure it worked. You disabled circular dependencies check.

**Comment by lasimone** [comment]
Rather than turning off the check, is there an appropriate way to fix this so we don't trigger this warning to begin with? Essentially, is there a better practice that should be used?

**Comment by ph55** [comment]
@lasimone just don't use barrels within same module. Use relative imports.

**Comment by kanji-keraliya** [comment]
Try to add the settings below to your angular.json, this worked for me :)
`"showCircularDependencies": false`  into build section 

`{
	"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
	"version": 1,
	"newProjectRoot": "xxxx",
	"projects": {
		"HelloWord": {
			"root": "",
			"sourceRoot": "src",
			"projectType": "application",
			"prefix": "app",
			"schematics": {},
			"architect": {
				"build": {
					"options": {
						"outputPath": "wwwroot",
						"index": "src/index.html",
						.....,
						"showCircularDependencies": false
					},
					"configurations": {
					....
					}
				},
				"serve": {
					....
				},
			}
		},		
	},
	"defaultProject": "HelloWord"
}`

**Comment by filipesilva** [comment]
I don't quite follow.  As far as I can tell, you do have a circular dependency:
- `ng-circular-example/src/app/libs/bye/src/bye.component.ts` imports `ByeModel` from `@corp/bye`
- `@corp/bye` resolves to `ng-circular-example/src/app/libs/bye/index.ts`
- `ng-circular-example/src/app/libs/bye/index.ts` exports `ByeModule` from `./src/bye.module`
- `./src/bye.module` imports `ByeComponent` from `./bye.component`, completing the cycle

The circular dependency is wholly within `ng-circular-example/src/app/libs/bye` and happens because one of your imports is to the public api of `libs/bye`. This is pretty much guaranteed to cause a circular import in most cases.

You should be able to clear this circular dependency by using `import { ByeModel } from './models.ts';` instead.

Let me know if I missed something here.
