### ISSUE TITLE
Feature request: styles.xxx.bundle.css at the end of index.html body after prod AOT compiling

### ISSUE THREAD

**Issue by zijianhuang** [angular/angular-cli#9956]
css link in html is blocking the rendering of the html elements. A common practice is to put the css link at the end of html body if the css is not critical for the rendering.

My Angular 5 + Material2 app has some simple text to remind the users about the loading of the first page, while the NG libs and the full rendering of NG components will take some more seconds. With the prod AOT compiling, styles.xxx.bundle.css is inserted inside the head element. 

It takes 1.5 seconds to show the reminder text hard coded in index.html, and 4.5 seconds to fully render the first page.

If I manually move the css link to the end of the body element, it takes 1.2 seconds to show the reminder text, and 4.3 seconds to fully render. Apparently the old trick is improving the performance, thus better UX.

It will be good that angular-cli has an option to put styles.xxx.bundle.css to the end of html body.

**Comment by alan-agius4** [comment]
Hi, this is out side of the scope of the CLI. You can probably achieve this using https://github.com/manfredsteyer/ngx-build-plus
