### ISSUE TITLE
assets folder error

### ISSUE THREAD

**Issue by barkinkizilkaya** [angular/angular-cli#9963]
Angular CLI: 1.7.2
Node: 9.5.0
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

I try to upload a image assets/upload_image but it give 404. What is wrong ?

**Comment by Brocco** [comment]
Please take a look at the asset configuration documentation and make sure you're following the steps there. https://github.com/angular/angular-cli/wiki/stories-asset-configuration

If there is still an issue, please update this issue with more information and ideally a repo that represents the issue you're experiencing.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.
