### ISSUE TITLE
Add dependency pinning in Wiki "stories universal rendering"

### ISSUE THREAD

**Issue by ebrehault** [angular/angular-cli#9964]
With the current explanations from https://github.com/angular/angular-cli/wiki/stories-universal-rendering, we end up with `"ts-loader": "~4.0.1"` which is not working, it produces the following error when launching the server:

```
Cannot read property 'afterCompile' of undefined
```

The story should mention in the "Install dependencies" paragraph to pick the version 3.5.0:

```
$ npm install --save @angular/platform-server @nguniversal/module-map-ngfactory-loader ts-loader@~3.5.0
```

**Comment by h-bex** [comment]
I suggest the following solution in the documentations:
In the section titled "Install Dependencies" do the following changes:

1. Add a paragraph stating the following after the first paragraph:
Please add the following line to package.json in the "scripts" section:
`"webpack:version": "webpack --version",`
Next run
`npm run webpack:version`
Remember the first number of the result (in may case the result was 3.11.0). So the number to remember is 3.
2. In the code example replace `ts-loader` with `ts-loader@`_first-number_. In my case it is `ts-loader@3`.

This shall fix the dependency problem between `webpack `and `ts-loader`.

**Comment by alan-agius4** [comment]
Closing as the universal documentation has been moved to https://angular.io/guide/universal
