### ISSUE TITLE
Generating a project in existing folder with .gitignore or readme.md fails...

### ISSUE THREAD

**Issue by JemiloII** [angular/angular-cli#9966]
When generating a project within an existing folder that contains a .gitignore or readme.md causes the cli to only generate the node_modules folder.

### Versions
node 6.9.2 & 8.10.0
npm 4.0.5 &  5.6.0
nvm 0.33.2
ng 1.7.3
OSX 10.13.3

### Repro steps
This is the exact method I used.
* Create a repo on github with a node.js .gitignore, readme.md, and the unlicense
* Clone the repo on your computer.
* Navigate to the parent directory and run `ng new appName --directory=your-cloned-directory`
* Note that only the node_modules folder is created.
* Then delete the .gitignore & readme.md in `your-cloned-directory`
* Rerun ng new command from the parent directory.

### Observed behavior
Only creates the node_modules folder and nothing else.

### Desired behavior
Display an error when there is a .gitignore file present.
Generate the project without a readme.md when a readme.md is present.

**Comment by alan-agius4** [comment]
`ng new` now shows errors when these files already exists.
