### ISSUE TITLE
Couldn't able to use ssl parameters for ng build

### ISSUE THREAD

**Issue by phani2028** [angular/angular-cli#9968]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
.
```
![image](https://user-images.githubusercontent.com/37122347/37424403-b9c86606-2796-11e8-90fa-ea5d13711109.png)

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by clydin** [comment]
Those options are not present on the build command as the build command generates output on the filesystem.
