### ISSUE TITLE
e2e listen on 0.0.0.0 with dynamic port & --public-host

### ISSUE THREAD

**Issue by chriswhite199** [angular/angular-cli#9972]
### Versions
```
Angular CLI: 1.7.3
Node: 8.9.4
OS: darwin x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps

This fails because the dynamic port isn't substituted into the public-host url:
* `e2e --host 0.0.0.0 --public-host http://docker.for.mac.host.internal`

This succeeds because the port has been statically set and provided in the public-host url
* `e2e --host 0.0.0.0 --port 4201 --public-host http://docker.for.mac.host.internal:4201`

### Observed behavior
For the failed invocation:
```
** NG Live Development Server is listening on 0.0.0.0:49152, open your browser on http://localhost:49152/ **
....
- Failed: Angular could not be found on the page http://docker.for.mac.host.internal/
```

### Desired behavior
For instances where your `ng e2e` invocation occurs on a machine with multiple network interfaces (say in a docker environment where your CI server exists on a public network and bridged selenium network), it can be desirable to bind to `0.0.0.0` (vs having to know ahead of time / hard-coding the selenium interface address into you ng e2e call). In this case you need to explicitly provide the `--public-host` parameter but that then also requires you to provide a static port param.

It would be desirable if there was someway to work in the usage of dynamic ports into the `--public-host` value so you didn't have to use static ports via the `--port` and `--public-host` args.

For example, either providing some templating mechanism in `--public-host`:
* `--public-host http://docker.for.mac.host.internal:{{port}}/`

Or via detection in the `tasks/e2e.js::run` function that detects the `--public-host` argument and configures `additionalProtractorConfig.baseUrl` to include the dynamic port

### Additional Information

Of course with docker (esp docker-compose) you can assign links / network aliases where your `ng e2e` is served from and then just use something like `--host my-e2e-alias`, but that assumes that your selenium nodes can route to that (not always possible for say an Internet Explorer node running outside of docker on another machine.

**Comment by clydin** [comment]
This is antithetical to the concept of the public host.  The IP and port that `ng` is using to serve the application is not related to the public host address (which is the address that a consumer would use to access the application).  They are by definition divorced from each other and one cannot assume any behavior from the other.  There could be any number of proxies or other redirections in between the two.
