### ISSUE TITLE
ng test does not use --proxy-config

### ISSUE THREAD

**Issue by gpeel** [angular/angular-cli#9979]
Spec request:

I would like to pass integration test with karma, 
but ng test does not use -proxy-config.

So I have to change all mu URL + enable CORS to test my backend ... not very ptratical.

Could you activate this option ?

**Comment by ciesielskico** [comment]
Do you pass the --proxy-config flag when starting ng test?

**Comment by gpeel** [comment]
yes when i run ng test --proxy-config proxy-config.json
here is the console:


angular-tp-basic-http@0.0.0 testp C:\me\js\Angular\__tp-ng\_innersource\Angular-tp-basic-http
> ng test --proxy-config proxy-config.json

The option '--proxy-config' is not registered with the test command. Run `ng test --help` for a list of supported options.
17 03 2018 12:42:22.769:WARN [karma]: No captured browser, open http://localhost:9876/
17 03 2018 12:42:22.797:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
17 03 2018 12:42:22.797:INFO [launcher]: Launching browser Chrome with unlimited concurrency

**Comment by gerardcarbo** [comment]
By now you can achieve the same result configuring the karma.conf.js 'proxies' param:

```
proxies: {
      '/server': {
        'target': 'http://localhost:8080/server',
        'changeOrigin': true
      }
    }
```

**Comment by gpeel** [comment]
yes I know, that's what I have found and used. 
Still, it would be nice to have the same API for CLI exec and CLI test.

**Comment by filipesilva** [comment]
It is true that the unit tests do not share the serving setup as present in `ng serve`, but this is not something we intend to add. 

`ng serve` is meant to provide a development server, and also provides some convenience features for common cases. For more complex cases, like proxies that need to be available for both serving and testing, the intent is to setup a more robust proxy on your machine that fits your specific needs.

Karma itself allows some proxying behaviour, but it is not very elaborate either.
