### ISSUE TITLE
duplicated package

### ISSUE THREAD

**Issue by Meir017** [angular/angular-cli#9981]
### Versions
  Windows (10)
  node 8.1.2
  npm 5.0.3

### Repro steps

execute the following lines:
```bash
mkdir find-dups
cd find-dups
mkdir angular-cli-demo
cd angular-cli-demo
npm init -y
npm install @angular/cli@1.7.3
cd ..
npm init -y
npm install glob
```
using the following [script](https://gist.github.com/Meir017/7b59bacc4473ca093cf6bc01bf1b20f4) (copy it to the `find-dups` directory and execute with `node find-dups.js`) I found the following [duplicated packages](https://gist.github.com/Meir017/7b59bacc4473ca093cf6bc01bf1b20f4#gistcomment-2382573)

the size of the directory is:
19,925 Files, 2,650 Folders 111 MB Size
if we would have had a single version of each dependency once it could have been:
17,404 Files, 2,090 Folders 85.8 MB Size

**Comment by clydin** [comment]
This is the behavior of the package manager (`npm` in this case) and not related to the CLI.
