### ISSUE TITLE
ng build --watch creating a "dist" folder that my XAMPP local server can't see

### ISSUE THREAD

**Issue by chrisgrim** [angular/angular-cli#9983]
Angular CLI: 1.7.3
Node: 8.10.0
OS: darwin x64
Angular: 
npm 5.7.1
Mac OS High Seirra
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

-Step 1:  ran npm install and it worked
-Step 2: ran ng build --watch and it created the correct "dist" folder
-Step 3: when I try to view the dist folder in local webserver (XAMPP) it pulls up the page Server error!
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there was an error in a CGI script.

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

### Desired behavior

I expected to be able to see the my website. The strangest thing is if I create a new dist folder and move all the files from the "built" dist folder, the local webserver can see it perfectly fine and loads my site.

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
