### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by Sevensnake** [angular/angular-cli#9988]
### Versions
5.2.5
Typescript 
2.7.1
`ng g c home`
When I try to generate a component I get this now. Not sure why or where this came from.
`Error: Cannot read property '0' of null
Cannot read property '0' of null`

**Comment by jon301** [comment]
same here with `ng g module --help`

**Comment by clydin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
